# Benchmarking Results from Classification and Regression

#### Set Up

In [1]:
import pandas as pd
import numpy as np
import site
import os

In [2]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import TimeSeriesSplit
from sklearn.utils.class_weight import compute_class_weight

from sklearn.metrics import (
    precision_score, recall_score, f1_score, matthews_corrcoef,
    mean_squared_error, mean_absolute_error, r2_score, confusion_matrix
)

import torch
import torch.nn as nn
import torch.nn.functional as F

from torch.utils.data import Dataset, DataLoader
from torch.optim import Adam
from torch.optim.lr_scheduler import ReduceLROnPlateau
from contextlib import nullcontext

import random

from unicodedata import bidirectional

### Utility Classes and Functions

In [3]:
def set_global_seeds(seed: int = 42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

set_global_seeds(42)

# Datasets
class SequenceDataset(Dataset):
    def __init__(self, X, y):
        self.X = torch.tensor(X, dtype=torch.float32)
        self.y = torch.tensor(y, dtype=torch.float32)

    def __len__(self):
        return self.X.shape[0]

    def __getitem__(self, idx):
        return self.X[idx], self.y[idx]

class OrdinalSequenceDataset(Dataset):
    def __init__(self, X, T):
        self.X = torch.tensor(X, dtype=torch.float32)
        self.T = torch.tensor(T, dtype=torch.float32)

    def __len__(self):
        return self.X.shape[0]

    def __getitem__(self, idx):
        return self.X[idx], self.T[idx]

def make_cumulative_targets(y_int, K):
    y = y_int.reshape(-1, 1)
    ks = np.arange(K-1).reshape(1, -1)
    return (y > ks).astype(np.float32)

def decode_ordinal(probs, thr=0.5):
    return (probs >= thr).sum(axis=1)

# Models
class OrdinalHeadCORN(nn.Module):
    def __init__(self, in_dim, K):
        super().__init__()
        self.fc = nn.Linear(in_dim, K-1)

    def forward(self, h):
        return self.fc(h)


class OrdinalHeadCORAL(nn.Module):
    def __init__(self, in_dim, K):
        super().__init__()
        self.w = nn.Linear(in_dim, 1, bias=False)
        self._beta = nn.Parameter(torch.zeros(K-1))
        self.softplus = nn.Softplus()

    def forward(self, h):
        base = self.w(h)
        deltas = self.softplus(self._beta)
        b = torch.cumsum(deltas, dim=0)
        return base - b



class RNNHead(nn.Module):
    # Shared head:
    #   - RNN stack (LSTM/GRU, uni/bi)
    #   - BatchNorm + Dense(32, ReLU) + Dropout
    #   - Output layer (1 unit): linear (regression) or logits (classification)
    def __init__(self, input_size, rnn_type='LSTM', bidirectional=False, problem_type='classification',
                 n_classes=6, ordinal_head='coral', hidden1=128, hidden2=64, num_layers=1,
                 inter_rnn_drop=0.1, dropout=0.3, use_layernorm=False):
        super().__init__()
        self.problem_type = problem_type
        self.bidirectional = bidirectional
        self.rnn_type = rnn_type.upper()
        self.n_classes = n_classes
        self.ordinal_head = ordinal_head
        self.num_layers = int(num_layers)
        self.hidden1 = int(hidden1)
        self.hidden2 = int(hidden2)

        if self.num_layers not in (1, 2):
            raise ValueError("num_layers must be 1 or 2")

        rnn_cls = {'LSTM': nn.LSTM, 'GRU': nn.GRU}[('GRU' if 'GRU' in self.rnn_type else 'LSTM')]

        self.rnn1 = rnn_cls(
            input_size=input_size, hidden_size=self.hidden1, num_layers=1,
            batch_first=True, dropout=0.0, bidirectional=bidirectional
        )

        self.inter_rnn_drop = nn.Dropout(float(inter_rnn_drop))

        self.rnn2 = None
        if self.num_layers == 2:
            self.rnn2 = rnn_cls(
                input_size=self.hidden1*(2 if bidirectional else 1), hidden_size=self.hidden2, num_layers=1,
                batch_first=True, dropout=0.0, bidirectional=bidirectional
            )
            feat_dim = self.hidden2*(2 if bidirectional else 1)
        else:
            feat_dim = self.hidden1*(2 if bidirectional else 1)

        if use_layernorm:
            self.bn = nn.LayerNorm(feat_dim)
        else:
            self.bn = nn.BatchNorm1d(feat_dim)
        self.fc = nn.Linear(feat_dim, 32)
        self.drop = nn.Dropout(float(dropout))
        if self.problem_type == 'multiclass':
            head = self.ordinal_head.lower() if isinstance(self.ordinal_head, str) else 'coral'
            if head == 'corn':
                self.out = OrdinalHeadCORN(32, self.n_classes)
            else:
                self.out = OrdinalHeadCORAL(32, self.n_classes)
        else:
            self.out = nn.Linear(32, 1)

    def forward(self, x):
        # x: [B, T, F]
        out, _ = self.rnn1(x)
        if self.num_layers == 2:
            out = self.inter_rnn_drop(out)   # inter-layer dropout (sequence-wise)
            out, _ = self.rnn2(out)
        # take last timestep: [B, T, H] -> [B, H]
        out = out[:, -1, :]
        out = self.bn(out)
        out = F.relu(self.fc(out))
        out = self.drop(out)
        out = self.out(out)  # shape [B,1]
        return out  # regression: raw; classification: logits


def build_model(input_shape, model_type='LSTM', problem_type='regression', n_classes=6, ordinal_head='coral',
                hidden1=128, hidden2=64, num_layers=2, inter_rnn_drop=0.1, dropout=0.3, use_layernorm=False):
    seq_len, n_features = input_shape
    model_type = model_type.upper()
    kwargs = dict(
        problem_type=problem_type,
        n_classes=n_classes,
        ordinal_head=ordinal_head,
        hidden1=hidden1,
        hidden2=hidden2,
        num_layers=num_layers,
        inter_rnn_drop=inter_rnn_drop,
        dropout=dropout,
        use_layernorm=use_layernorm,
    )
    if model_type == 'LSTM':
        return RNNHead(n_features, rnn_type='LSTM', bidirectional=False, **kwargs)
    elif model_type == 'BILSTM':
        return RNNHead(n_features, rnn_type='LSTM', bidirectional=True, **kwargs)
    elif model_type == 'GRU':
        return RNNHead(n_features, rnn_type='GRU', bidirectional=False, **kwargs)
    elif model_type == 'BIGRU':
        return RNNHead(n_features, rnn_type='GRU', bidirectional=True, **kwargs)
    else:
        raise ValueError("Model type must be one of: ['LSTM','BiLSTM','GRU','BiGRU']")

# Early Stopping (PyTorch)
class EarlyStopper:
    def __init__(self, patience=15, min_delta=0.0, restore_best=True):
        self.patience = patience
        self.min_delta = min_delta
        self.restore_best = restore_best
        self.best_loss = float('inf')
        self.counter = 0
        self.best_state = None

    def step(self, val_loss, model):
        improved = (self.best_loss - val_loss) > self.min_delta
        if improved:
            self.best_loss = val_loss
            self.counter = 0
            if self.restore_best:
                # Deep copy state dict
                self.best_state = {k: v.detach().clone() for k, v in model.state_dict().items()}
        else:
            self.counter += 1
        return self.counter >= self.patience

    def restore(self, model):
        if self.restore_best and self.best_state is not None:
            model.load_state_dict(self.best_state)

In [4]:
def edge_labels_from_edges(edges, decimals=1):
    labels = []
    C = len(edges) - 1
    for i in range(C):
        lo, hi = edges[i], edges[i+1]
        if i == 0:
            labels.append(f"≤ {hi*100:.{decimals}f}%")
        elif i == C - 1:
            labels.append(f"> {lo*100:.{decimals}f}%")
        else:
            labels.append(f"({lo*100:.{decimals}f}%,{hi*100:.{decimals}f}%]")
    return labels

def pct_return(series, h):
    return series.shift(-h) / series - 1.0

def safe_quantile_edges(x, n_classes=6):
    qs = np.linspace(0, 1, n_classes + 1)
    edges = np.quantile(x, qs)
    for i in range(1, len(edges)):
        if edges[i] <= edges[i-1]:
            edges[i] = np.nextafter(edges[i-1], np.inf)
    return edges

def bucketize_with_edges(x, edges):
    inner = edges[1:-1]
    return np.digitize(x, inner, right=True).astype(int)

@torch.no_grad()
def collect_logits(model, loader, device):
    model.eval()
    chunks = []
    for xb, _ in loader:
        xb = xb.to(device)
        chunks.append(model(xb).detach().cpu())
    return torch.cat(chunks, dim=0)

def find_taus_per_threshold(Z_val, y_val_idx, grid=np.linspace(0, 1, 100)):
    if isinstance(Z_val, torch.Tensor):
        Z_val = Z_val.numpy()
    P_val = 1.0 / (1.0 + np.exp(-Z_val))
    P_rep = monotone_repair_numpy(P_val)
    K_1 = P_rep.shape[1]
    best_taus = np.full(K_1, 0.5, dtype=np.float32)
    for k in range(K_1):
        best_f1, best_tau = -1.0, 0.5
        for tau in grid:
            y_hat = decode_ordinal_with_taus(P_rep, taus_override={k: tau})
            f1 = f1_score(y_val_idx, y_hat, average='macro', zero_division=0)
            if f1 > best_f1:
                best_f1, best_tau = f1, tau
        best_taus[k] = best_tau
    return best_taus

def monotone_repair_numpy(P):
    P = np.asarray(P).copy()
    for k in range(P.shape[1] - 2, -1, -1):
        P[:, k] = np.maximum(P[:, k], P[:, k+1])
    return P

def decode_ordinal_with_taus(P_rep, taus=None, taus_override=None):
    N, K_1 = P_rep.shape
    if taus is None:
        taus = np.full(K_1, 0.5, dtype=np.float32)
    if taus_override:
        taus = taus.copy()
        for k, v in taus_override.items():
            taus[k] = v
    comp = (P_rep >= taus.reshape(1, -1)).astype(np.int32)
    return comp.sum(axis=1).astype(np.int64)

def ordinal_to_class_probs(P_rep):
    N, K_1 = P_rep.shape
    K = K_1 + 1
    Pc = np.empty((N, K), dtype=np.float32)
    Pc[:, 0] = 1.0 - P_rep[:, 0]
    for c in range(1, K - 1):
        Pc[:, c] = np.clip(P_rep[:, c-1] - P_rep[:, c], 0.0, 1.0)
    Pc[:, K - 1] = P_rep[:, K_1 - 1]
    s = Pc.sum(axis=1, keepdims=True)
    return Pc / np.maximum(s, 1e-8)


def best_threshold_from_val(y_true, y_scores, metric='f1', grid=None):
    """
    Sweep probability thresholds on validation scores to maximize a metric.
    metric can be 'f1', 'mcc', 'accuracy', or a callable(y_true,y_pred)->float.
    Returns (best_threshold, best_metric_value).
    """
    y_true = np.asarray(y_true).astype(int)
    y_scores = np.asarray(y_scores).astype(float)
    if grid is None:
        grid = np.linspace(0.05, 0.95, 181)
    metric_fn = None
    if callable(metric):
        metric_fn = metric
    else:
        name = str(metric).lower()
        if name == 'f1':
            metric_fn = lambda yt, yp: f1_score(yt, yp, zero_division=0)
        elif name == 'mcc':
            metric_fn = lambda yt, yp: matthews_corrcoef(yt, yp)
        elif name in ('acc', 'accuracy'):
            metric_fn = lambda yt, yp: (yt == yp).mean()
        else:
            raise ValueError(f"Unsupported metric '{metric}'")
    best_thr = 0.5
    best_val = -np.inf
    for thr in grid:
        preds = (y_scores >= thr).astype(int)
        val = metric_fn(y_true, preds)
        if val > best_val + 1e-12 or (abs(val - best_val) <= 1e-12 and thr < best_thr):
            best_val = float(val)
            best_thr = float(thr)
    return best_thr, best_val

## Stock Prediction Pipeline

In [5]:
class StockPredictionPipeline:
    def __init__(self, df, feature_columns, model_type='LSTM', sequence_length=24, problem_type='regression', horizon_steps=1, n_classes=6, ordinal_head='coral', fixed_bucket_edges=None,
                 hidden1=256, hidden2=64, num_layers=1, inter_rnn_drop=0.0, dropout=0.4,
                 batch_size=32, learning_rate=7e-3, weight_decay=2e-3, lr_patience=7, lr_factor=0.5,
                 early_stopping_patience=20, max_epochs=20, use_layernorm=False, huber_delta=1.0, early_stopping_min_delta=0.0):
        self.df = df.copy()
        self.feature_columns = feature_columns
        self.model_type = model_type
        self.sequence_length = sequence_length
        self.problem_type = problem_type
        self.horizon_steps = horizon_steps
        self.results = []
        self.loss_curves = []
        self.n_classes = n_classes
        self.ordinal_head = ordinal_head
        self.hidden1 = hidden1
        self.hidden2 = hidden2
        self.num_layers = num_layers
        self.inter_rnn_drop = inter_rnn_drop
        self.dropout = dropout
        self.batch_size = batch_size
        self.learning_rate = learning_rate
        self.weight_decay = weight_decay
        self.lr_patience = lr_patience
        self.lr_factor = lr_factor
        self.early_stopping_patience = early_stopping_patience
        self.max_epochs = max_epochs
        self.use_layernorm = use_layernorm
        self.huber_delta = huber_delta
        self.early_stopping_min_delta = early_stopping_min_delta
        self.fixed_bucket_edges = None
        if fixed_bucket_edges is not None:
            edges = np.asarray(fixed_bucket_edges, dtype=float)
            if edges.ndim != 1:
                raise ValueError("fixed_bucket_edges must be a 1D sequence of monotonically increasing numbers")
            if edges.size < 2:
                raise ValueError("fixed_bucket_edges must contain at least two values")
            if np.any(np.diff(edges) <= 0):
                raise ValueError("fixed_bucket_edges must be strictly increasing")
            self.n_classes = int(edges.size - 1)
            self.fixed_bucket_edges = edges

        # Validate
        self._validate_inputs()

        # Device & precision
        self.device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
        self.mixed_precision = torch.cuda.is_available()

        print(f"Pipeline initialized for a '{self.problem_type}' problem "
              f"with horizon {self.horizon_steps} steps. Device: {self.device}")

    def _validate_inputs(self):
        missing_cols = [col for col in self.feature_columns if col not in self.df.columns]
        if missing_cols:
            raise ValueError(f"Missing feature columns: {missing_cols}")

        if 'close' not in self.df.columns and 'close_price' not in self.df.columns:
            raise ValueError("No 'close' or 'close_price' column found in data")

        valid_models = ['LSTM', 'BiLSTM', 'GRU', 'BiGRU']
        if self.model_type not in valid_models:
            raise ValueError(f"Model type must be one of: {valid_models}")

        if self.problem_type not in ['regression', 'classification', 'multiclass']:
            raise ValueError("Problem type must be 'regression', 'classification', or 'multiclass'")

    def create_target_variable(self, company_data):
        company_data = company_data.copy()
        price_col = 'close' if 'close' in company_data.columns else 'close_price'
        if 'date' in company_data.columns:
            company_data = company_data.sort_values('date')
            
        h = self.horizon_steps

        company_data['target_regression'] = (
            np.log(company_data[price_col].shift(-h)) - np.log(company_data[price_col])
        )
        company_data['target_direction'] = (company_data['target_regression'] > 0).astype(int)
        company_data['ret_h'] = pct_return(company_data[price_col], h)
        if self.problem_type == 'multiclass':
            company_data = company_data.dropna(subset=['ret_h'])
        else:
            company_data = company_data.dropna()
        return company_data

    def create_sequences(self, features, *targets):
        X = []
        y_sequences = [[] for _ in targets]
        for i in range(self.sequence_length, len(features)):
            X.append(features[i-self.sequence_length:i])
            for j, target in enumerate(targets):
                y_sequences[j].append(target[i])
        return (np.array(X),) + tuple(np.array(y) for y in y_sequences)

    def _train_one_epoch(self, model, loader, optimizer, loss_fn, scaler):
        model.train()
        total_loss = 0.0
        for xb, yb in loader:
            xb = xb.to(self.device)
            yb = yb.to(self.device).view(-1, 1)

            optimizer.zero_grad(set_to_none=True)

            ctx = torch.amp.autocast('cuda') if self.mixed_precision else nullcontext()
            with ctx:
                logits = model(xb)
                loss = loss_fn(logits, yb)

            if self.mixed_precision:
                scaler.scale(loss).backward()
                scaler.unscale_(optimizer)
                torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
                scaler.step(optimizer)
                scaler.update()
            else:
                loss.backward()
                torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
                optimizer.step()

            total_loss += loss.item() * xb.size(0)

        return total_loss / len(loader.dataset)

    @torch.no_grad()
    def _eval_one_epoch(self, model, loader, loss_fn):
        model.eval()
        total_loss = 0.0
        for xb, yb in loader:
            xb = xb.to(self.device)
            yb = yb.to(self.device).view(-1, 1)
            logits = model(xb)
            loss = loss_fn(logits, yb)
            total_loss += loss.item() * xb.size(0)
        return total_loss / len(loader.dataset)

    def _train_one_epoch_multiclass(self, model, loader, optimizer, scaler, *, pos_weight=None):
        model.train()
        total = 0.0
        for xb, yb in loader:
            xb = xb.to(self.device)
            yb = yb.to(self.device)
            optimizer.zero_grad(set_to_none=True)
            ctx = torch.amp.autocast('cuda') if self.mixed_precision else nullcontext()
            with ctx:
                logits = model(xb)
                bces = []
                for k in range(logits.shape[1]):
                    w = None if pos_weight is None else pos_weight[k]
                    bce_k = F.binary_cross_entropy_with_logits(logits[:, k], yb[:, k], pos_weight=w)
                    bces.append(bce_k)
                loss = torch.stack(bces).mean()
            if self.mixed_precision:
                scaler.scale(loss).backward()
                scaler.unscale_(optimizer)
                torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
                scaler.step(optimizer)
                scaler.update()
            else:
                loss.backward()
                torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
                optimizer.step()
            total += float(loss.item()) * xb.size(0)
        return total / len(loader.dataset)

    @torch.no_grad()
    def _eval_one_epoch_multiclass(self, model, loader, pos_weight=None):
        model.eval()
        total = 0.0
        for xb, yb in loader:
            xb = xb.to(self.device)
            yb = yb.to(self.device)
            logits = model(xb)
            bces = []
            for k in range(logits.shape[1]):
                w = None if pos_weight is None else pos_weight[k]
                bce_k = F.binary_cross_entropy_with_logits(logits[:, k], yb[:, k], pos_weight=w)
                bces.append(bce_k)
            loss = torch.stack(bces).mean()
            total += float(loss.item()) * xb.size(0)
        return total / len(loader.dataset)

    @torch.no_grad()
    def _predict(self, model, loader):
        model.eval()
        outs = []
        for xb, _ in loader:
            xb = xb.to(self.device)
            logits = model(xb).squeeze(1).detach().cpu().numpy()
            outs.append(logits)
        return np.concatenate(outs, axis=0)

    def build_model(self, input_shape):
        model = build_model(
            input_shape,
            model_type=self.model_type,
            problem_type=self.problem_type,
            n_classes=self.n_classes,
            ordinal_head=self.ordinal_head,
            hidden1=self.hidden1,
            hidden2=self.hidden2,
            num_layers=self.num_layers,
            inter_rnn_drop=self.inter_rnn_drop,
            dropout=self.dropout,
            use_layernorm=self.use_layernorm
        )
        return model.to(self.device)

    def process_company(self, company_name, company_data, sector):
        print(f"\nProcessing {company_name} ({sector})...")
        try:
            company_data = self.create_target_variable(company_data)

            # Min samples requirement (same heuristic)
            min_samples = self.sequence_length + self.horizon_steps
            if len(company_data) < min_samples:
                print(f"Insufficient data for {company_name} ({len(company_data)} < {min_samples}). Skipping...")
                return None

            if company_data[self.feature_columns].isnull().any().any():
                print(f"Missing values in features for {company_name}. Skipping...")
                return None

            features = company_data[self.feature_columns].values
            target_reg = company_data['target_regression'].values
            target_dir = company_data['target_direction'].values

            # Create sequences
            X_raw, y_reg, y_dir = self.create_sequences(features, target_reg, target_dir)

            # TimeSeriesSplit
            n_splits = min(5, len(X_raw) // 50)
            if n_splits < 3:
                print(f"Insufficient data for proper time series validation for {company_name}. Skipping...")
                return None

            tscv = TimeSeriesSplit(n_splits=n_splits)
            splits = list(tscv.split(X_raw))
            train_idx, test_idx = splits[-1]

            # Train/Val split (last 20% of train for val)
            val_size = int(0.2 * len(train_idx))
            if val_size == 0:
                print(f'Insufficient data for validation split for {company_name}. Skipping...')
                return None
            final_train_idx = train_idx[:-val_size]
            val_idx = train_idx[-val_size:]
            
            if self.horizon_steps > 1:
                print("Adjusting for multi-step horizon...")
                gap = self.horizon_steps
                if len(final_train_idx) > gap:
                    final_train_idx = final_train_idx[:-gap]  # drop last h labels from train
                if len(val_idx) > gap:
                    val_idx = val_idx[gap:]  # drop last h labels from val
            if len(final_train_idx) == 0 or len(val_idx) == 0:
                print(f'Insufficient data after horizon adjustment for {company_name}. Skipping...')
                return None

            X_train_raw, X_val_raw, X_test_raw = X_raw[final_train_idx], X_raw[val_idx], X_raw[test_idx]
            
            F = X_raw.shape[-1]
            feat_scaler = StandardScaler()
            X_train = feat_scaler.fit_transform(X_train_raw.reshape(-1, F)).reshape(X_train_raw.shape)
            X_val   = feat_scaler.transform(X_val_raw.reshape(-1, F)).reshape(X_val_raw.shape)
            X_test  = feat_scaler.transform(X_test_raw.reshape(-1, F)).reshape(X_test_raw.shape)

            if self.problem_type == 'multiclass':
                if 'ret_h' not in company_data.columns:
                    raise RuntimeError("Expected 'ret_h' for ordinal targets but it was missing.")
                ret_full = company_data['ret_h'].values
                ret_seq_full = ret_full[self.sequence_length:]

                ret_train = ret_seq_full[final_train_idx]
                ret_val = ret_seq_full[val_idx]
                ret_test = ret_seq_full[test_idx]

                if self.fixed_bucket_edges is not None:
                    edges = self.fixed_bucket_edges
                    if int(edges.shape[0] - 1) != self.n_classes:
                        raise ValueError("fixed_bucket_edges length must match n_classes+1")
                else:
                    edges = safe_quantile_edges(ret_train, n_classes=self.n_classes)
                edges = np.asarray(edges, dtype=float)
                K = int(edges.shape[0] - 1)
                label_names = edge_labels_from_edges(edges, decimals=1)

                y_bucket = bucketize_with_edges(ret_seq_full, edges).astype(np.int64)
                y_train = y_bucket[final_train_idx]
                y_val = y_bucket[val_idx]
                y_test = y_bucket[test_idx]

                T_train = make_cumulative_targets(y_train.astype(np.int64), K)
                T_val = make_cumulative_targets(y_val.astype(np.int64), K)
                T_test = make_cumulative_targets(y_test.astype(np.int64), K)

                train_ds = OrdinalSequenceDataset(X_train, T_train)
                val_ds = OrdinalSequenceDataset(X_val, T_val)
                test_ds = OrdinalSequenceDataset(X_test, T_test)

                train_loader = DataLoader(train_ds, batch_size=self.batch_size, shuffle=False, drop_last=False, num_workers=0)
                val_loader = DataLoader(val_ds, batch_size=self.batch_size, shuffle=False, drop_last=False, num_workers=0)
                test_loader = DataLoader(test_ds, batch_size=self.batch_size, shuffle=False, drop_last=False, num_workers=0)

                model = self.build_model((self.sequence_length, len(self.feature_columns)))

                pos_rate = T_train.mean(axis=0)
                pos_weight = (1.0 - pos_rate) / np.clip(pos_rate, 1e-6, 1.0)
                pos_weight_tensor = torch.tensor(pos_weight, dtype=torch.float32).to(self.device)

                optimizer = Adam(model.parameters(), lr=self.learning_rate, eps=1e-7, weight_decay=self.weight_decay)
                scheduler = ReduceLROnPlateau(optimizer, mode='min', factor=self.lr_factor, patience=self.lr_patience, min_lr=1e-7)
                early_stopper = EarlyStopper(patience=self.early_stopping_patience, min_delta=self.early_stopping_min_delta, restore_best=True)
                scaler = torch.amp.GradScaler('cuda', enabled=self.mixed_precision)

                max_epochs = self.max_epochs
                best_val = float('inf')
                epochs_trained = 0
                company_loss_rows = []

                for epoch in range(1, max_epochs + 1):
                    train_loss = self._train_one_epoch_multiclass(model, train_loader, optimizer, scaler, pos_weight=pos_weight_tensor)
                    val_loss = self._eval_one_epoch_multiclass(model, val_loader, pos_weight=pos_weight_tensor)
                    scheduler.step(val_loss)
                    stop = early_stopper.step(val_loss, model)
                    epochs_trained = epoch

                    row = {
                        'company': company_name,
                        'sector': sector,
                        'model_type': self.model_type,
                        'problem_type': self.problem_type,
                        'sequence_length': self.sequence_length,
                        'horizon_steps': self.horizon_steps,
                        'epoch': epoch,
                        'train_loss': float(train_loss),
                        'val_loss': float(val_loss),
                        'train_samples': len(X_train),
                        'val_samples': len(X_val),
                        'test_samples': len(X_test),
                    }

                    company_loss_rows.append(row)
                    self.loss_curves.append(row)

                    if epoch % 10 == 0 or stop:
                        print(f"  Epoch {epoch:03d} - train {train_loss:.5f} | val {val_loss:.5f}")

                    if stop:
                        break

                early_stopper.restore(model)

                Z_val = collect_logits(model, val_loader, self.device)
                taus = find_taus_per_threshold(Z_val, y_val.astype(np.int64))
                P_cum_val = torch.sigmoid(Z_val).cpu().numpy()
                P_rep_val = monotone_repair_numpy(P_cum_val)
                P_class_val = ordinal_to_class_probs(P_rep_val)
                mid_cut = (K // 2)
                y_val_dir = (y_val >= mid_cut).astype(int)
                prob_val_up = P_class_val[:, mid_cut:].sum(axis=1)
                dir_thr, dir_thr_score = best_threshold_from_val(y_val_dir, prob_val_up, metric='mcc')

                Z_test = collect_logits(model, test_loader, self.device)
                P_cum = torch.sigmoid(Z_test).cpu().numpy()
                P_rep = monotone_repair_numpy(P_cum)
                P_class = ordinal_to_class_probs(P_rep)

                y_pred_labels = decode_ordinal_with_taus(P_rep, taus=taus)
                y_true_labels = y_test

                labels = list(range(K))
                cm_counts = confusion_matrix(y_true_labels, y_pred_labels, labels=labels)
                cm_norm = confusion_matrix(y_true_labels, y_pred_labels, labels=labels, normalize='true')

                micro_acc = (y_true_labels == y_pred_labels).mean()
                macro_f1 = f1_score(y_true_labels, y_pred_labels, average='macro', zero_division=0)

                ret_seq_train = ret_seq_full[final_train_idx].astype(np.float32)
                mu_c = np.array([
                    ret_seq_train[y_train == c].mean() if np.any(y_train == c) else 0.0
                    for c in range(K)
                ], dtype=np.float32)

                expected_ret = (P_class * mu_c[None, :]).sum(axis=1)
                expected_ret_mean = float(expected_ret.mean())

                prob_test_up = P_class[:, mid_cut:].sum(axis=1)
                y_true_dir = (y_true_labels >= mid_cut).astype(int)
                y_pred_dir = (prob_test_up >= dir_thr).astype(int)
                precision = precision_score(y_true_dir, y_pred_dir, zero_division=0)
                recall = recall_score(y_true_dir, y_pred_dir, zero_division=0)
                f1 = f1_score(y_true_dir, y_pred_dir, zero_division=0)
                mcc = matthews_corrcoef(y_true_dir, y_pred_dir)
                directional_accuracy = (y_true_dir == y_pred_dir).mean()

                result = {
                    'company': company_name,
                    'sector': sector,
                    'model_type': self.model_type,
                    'problem_type': self.problem_type,
                    'horizon_steps': self.horizon_steps,
                    'macro_f1': macro_f1,
                    'micro_accuracy': micro_acc,
                    'expected_return_mean': expected_ret_mean,
                    'mse': np.nan,
                    'mae': np.nan,
                    'r2': np.nan,
                    'mcc': mcc,
                    'f1': f1,
                    'precision': precision,
                    'recall': recall,
                    'directional_accuracy': directional_accuracy,
                'val_directional_accuracy': val_directional_accuracy if self.problem_type == 'classification' else np.nan,
                'val_mcc': val_mcc if self.problem_type == 'classification' else np.nan,
                'val_f1': val_f1 if self.problem_type == 'classification' else np.nan,
                'val_precision': val_precision if self.problem_type == 'classification' else np.nan,
                'val_recall': val_recall if self.problem_type == 'classification' else np.nan,
                    'n_samples': int(X_raw.shape[0]),
                    'train_samples': int(X_train.shape[0]),
                    'val_samples': int(X_val.shape[0]),
                    'test_samples': int(X_test.shape[0]),
                    'epochs_trained': epochs_trained
                }
                result['confusion_matrix'] = cm_counts.tolist()
                result['confusion_matrix_normalized'] = cm_norm.tolist()
                result['bucket_edges'] = edges.tolist()
                result['bucket_labels'] = label_names
                result['taus'] = taus.astype(float).tolist()
                result['direction_threshold'] = dir_thr
                result['direction_threshold_metric'] = dir_thr_score

                print(f"  Multiclass -> Micro Acc: {micro_acc:.4f}, Macro F1: {macro_f1:.4f}, Expected Return: {expected_ret_mean:.6f}")
                print(f"  Directional threshold -> τ={dir_thr:.3f} (val F1={dir_thr_score:.4f})")

                del model
                torch.cuda.empty_cache()
                return result

            if self.problem_type == 'regression':
                y_train, y_val, y_test = y_reg[final_train_idx], y_reg[val_idx], y_reg[test_idx]
                target_scaler = StandardScaler()
                y_train_scaled = target_scaler.fit_transform(y_train.reshape(-1, 1)).flatten()
                y_val_scaled   = target_scaler.transform(y_val.reshape(-1, 1)).flatten()
                train_target, val_target = y_train_scaled, y_val_scaled
            else:
                y_train, y_val, y_test = y_dir[final_train_idx], y_dir[val_idx], y_dir[test_idx]
                train_target, val_target = y_train, y_val
                target_scaler = None

            # class balance note
            if self.problem_type == 'classification':
                class_ratio = np.mean(y_train)
                if class_ratio < 0.1 or class_ratio > 0.9:
                    print(f"Severe class imbalance for {company_name} ({class_ratio:.3f}). Consider using class weights.")

            # datasets & loaders
            train_ds = SequenceDataset(X_train, train_target)
            val_ds   = SequenceDataset(X_val,   val_target)
            test_ds  = SequenceDataset(X_test,  y_test)

            train_bs = min(self.batch_size, len(train_ds))
            if train_bs < 2:
                print(f'Insufficient training samples for {company_name} (train size={len(train_ds)}). Skipping...')
                return None
            if len(train_ds) % train_bs == 1 and train_bs > 2:
                train_bs -= 1  # avoid batch size 1 for BatchNorm
            val_bs = min(self.batch_size, len(val_ds))
            test_bs = min(self.batch_size, len(test_ds))

            train_loader = DataLoader(train_ds, batch_size=train_bs, shuffle=False,  drop_last=False, num_workers=0)
            val_loader   = DataLoader(val_ds,   batch_size=val_bs,   shuffle=False, drop_last=False, num_workers=0)
            test_loader  = DataLoader(test_ds,  batch_size=test_bs,  shuffle=False, drop_last=False, num_workers=0)

            # build model
            model = self.build_model((self.sequence_length, len(self.feature_columns)))

            # loss functions
            if self.problem_type == 'regression':
                loss_fn = nn.HuberLoss(delta=self.huber_delta)
            else:
                # use BCEWithLogitsLoss for numerical stability (logits input)
                loss_fn = nn.BCEWithLogitsLoss()

            # optimizer & scheduler
            optimizer = Adam(model.parameters(), lr=self.learning_rate, eps=1e-7, weight_decay=self.weight_decay)
            scheduler = ReduceLROnPlateau(optimizer, mode='min', factor=self.lr_factor, patience=self.lr_patience, min_lr=1e-7)
            early_stopper = EarlyStopper(patience=self.early_stopping_patience, min_delta=self.early_stopping_min_delta, restore_best=True)
            scaler = torch.amp.GradScaler('cuda', enabled=self.mixed_precision)

            # training loop
            max_epochs = self.max_epochs
            best_val = float('inf')
            epochs_trained = 0
            company_loss_rows = []  

            for epoch in range(1, max_epochs + 1):
                train_loss = self._train_one_epoch(model, train_loader, optimizer, loss_fn, scaler)
                val_loss = self._eval_one_epoch(model, val_loader, loss_fn)
                scheduler.step(val_loss)
                stop = early_stopper.step(val_loss, model)
                epochs_trained = epoch

                
                row = {
                    'company': company_name,
                    'sector': sector,
                    'model_type': self.model_type,
                    'problem_type': self.problem_type,
                    'sequence_length': self.sequence_length,
                    'horizon_steps': self.horizon_steps,
                    'epoch': epoch,
                    'train_loss': float(train_loss),
                    'val_loss': float(val_loss),
                    'train_samples': len(X_train),
                    'val_samples': len(X_val),
                    'test_samples': len(X_test),
                }
                
                company_loss_rows.append(row)
                self.loss_curves.append(row)

                if epoch % 10 == 0 or stop:
                    print(f"  Epoch {epoch:03d} - train {train_loss:.5f} | val {val_loss:.5f}")

                if stop:
                    break

            # restore best model weights (like Keras restore_best_weights=True)
            early_stopper.restore(model)

            # summarize train/val loss for overfitting checks
            best_train_loss = np.nan
            best_val_loss = np.nan
            final_train_loss = np.nan
            final_val_loss = np.nan
            if company_loss_rows:
                best_val_loss = min(r['val_loss'] for r in company_loss_rows)
                best_train_loss = min(r['train_loss'] for r in company_loss_rows)
                final_train_loss = company_loss_rows[-1]['train_loss']
                final_val_loss = company_loss_rows[-1]['val_loss']

            # predictions
            y_pred_raw = self._predict(model, test_loader)  # raw/regression or logits

            if self.problem_type == 'regression':
                y_pred_unscaled = target_scaler.inverse_transform(y_pred_raw.reshape(-1,1)).flatten() if target_scaler is not None else y_pred_raw
                mse = mean_squared_error(y_test, y_pred_unscaled)
                mae = mean_absolute_error(y_test, y_pred_unscaled)
                r2  = r2_score(y_test, y_pred_unscaled)

                # directional metrics (derived)
                y_test_dir = (y_reg[test_idx] > 0).astype(int)
                y_pred_dir = (y_pred_unscaled > 0).astype(int)
            else:
                # logits -> probs via sigmoid -> learn best threshold on VAL
                val_logits = self._predict(model, val_loader)
                val_probs = 1.0 / (1.0 + np.exp(-val_logits))
                best_thr, best_thr_score = best_threshold_from_val(y_val, val_probs, metric='mcc')
                val_pred_dir = (val_probs >= best_thr).astype(int)
                val_precision = precision_score(y_val, val_pred_dir, zero_division=0)
                val_recall = recall_score(y_val, val_pred_dir, zero_division=0)
                val_f1 = f1_score(y_val, val_pred_dir, zero_division=0)
                val_mcc = matthews_corrcoef(y_val, val_pred_dir)
                val_directional_accuracy = (y_val == val_pred_dir).mean()
                probs = 1.0 / (1.0 + np.exp(-y_pred_raw))
                y_pred_dir = (probs >= best_thr).astype(int)
                y_test_dir = y_test
                mse = mae = r2 = np.nan

            precision = precision_score(y_test_dir, y_pred_dir, zero_division=0)
            recall    = recall_score(y_test_dir, y_pred_dir, zero_division=0)
            f1        = f1_score(y_test_dir, y_pred_dir, zero_division=0)
            mcc       = matthews_corrcoef(y_test_dir, y_pred_dir)
            directional_accuracy = np.mean(y_test_dir == y_pred_dir)

            result = {
                'company': company_name,
                'sector': sector,
                'model_type': self.model_type,
                'problem_type': self.problem_type,
                'horizon_steps': self.horizon_steps,
                'mse': mse,
                'mae': mae,
                'r2': r2,
                'mcc': mcc,
                'f1': f1,
                'precision': precision,
                'recall': recall,
                'directional_accuracy': directional_accuracy,
                'val_directional_accuracy': val_directional_accuracy if self.problem_type == 'classification' else np.nan,
                'val_mcc': val_mcc if self.problem_type == 'classification' else np.nan,
                'val_f1': val_f1 if self.problem_type == 'classification' else np.nan,
                'val_precision': val_precision if self.problem_type == 'classification' else np.nan,
                'val_recall': val_recall if self.problem_type == 'classification' else np.nan,
                'n_samples': int(X_raw.shape[0]),
                'train_samples': int(X_train.shape[0]),
                'val_samples': int(X_val.shape[0]),
                'test_samples': int(X_test.shape[0]),
                'epochs_trained': epochs_trained
            }
            if self.problem_type == 'classification':
                result['best_threshold'] = best_thr
                result['best_threshold_metric'] = best_thr_score

            if self.problem_type == 'regression':
                print(f"  Regression -> MSE: {mse:.6f}, MAE: {mae:.6f}, R²: {r2:.4f}")
            elif self.problem_type == 'classification':
                print(f"  Classification -> best τ={best_thr:.3f} (val F1={best_thr_score:.4f})")
            print(f"  Directional -> Accuracy: {directional_accuracy:.4f}, MCC: {mcc:.4f}, F1: {f1:.4f}")

            # explicit cleanup (PyTorch handles this, but keeps parity with Enrique2025)
            del model
            torch.cuda.empty_cache()

            return result

        except Exception as e:
            print(f"Error processing {company_name}: {str(e)}")
            torch.cuda.empty_cache()
            return None

    def run_pipeline(self):
        company_col = None
        for col_name in ['ticker', 'company', 'symbol']:
            if col_name in self.df.columns:
                company_col = col_name
                break
        if company_col is None:
            company_col = self.df.columns[0]
            print(f"Warning: Using '{company_col}' as company identifier column")

        companies = self.df[company_col].unique()
        print(f"Processing {len(companies)} companies with {self.model_type} model...")
        print(f"Problem type: {self.problem_type}")
        print(f"Sequence length: {self.sequence_length}")
        print(f"Features: {self.feature_columns}")

        successful_companies = 0
        for i, company in enumerate(companies, 1):
            print(f"\n[{i}/{len(companies)}] Processing {company}...")
            company_data = self.df[self.df[company_col] == company].copy()
            sector = company_data['sector'].iloc[0] if 'sector' in company_data.columns else 'Unknown'
            result = self.process_company(company, company_data, sector)
            if result:
                self.results.append(result)
                successful_companies += 1

        print(f"\n{'='*80}")
        print(f"Pipeline completed: {successful_companies}/{len(companies)} companies processed successfully")
        print(f"{'='*80}")

        if self.results:
            self.results_df = pd.DataFrame(self.results)
            return self.results_df
        else:
            print("No companies were processed successfully!")
            return pd.DataFrame()


    def analyze_results(self):
        if not hasattr(self, 'results_df') or self.results_df.empty:
            print("No results to analyze!")
            return None

        df = self.results_df
        analysis = {}

        print("" + "="*80)
        print("STOCK PREDICTION PIPELINE RESULTS")
        print("="*80)
        print(f"Model: {self.model_type} | Problem: {self.problem_type}")
        print(f"Companies analyzed: {len(df)}")
        print(f"Average samples per company: {df['n_samples'].mean():.0f}")

        print("" + "="*50)
        print("OVERALL PERFORMANCE")
        print("="*50)
        if self.problem_type == 'regression':
            print(f"Mean Squared Error:     {df['mse'].mean():.6f} (±{df['mse'].std():.6f})")
            print(f"Mean Absolute Error:    {df['mae'].mean():.6f} (±{df['mae'].std():.6f})")
            print(f"R² Score:              {df['r2'].mean():.4f} (±{df['r2'].std():.4f})")
        if self.problem_type == 'multiclass' and 'micro_accuracy' in df.columns:
            print(f"Micro Accuracy:         {df['micro_accuracy'].mean():.4f} (±{df['micro_accuracy'].std():.4f})")
            print(f"Macro F1 Score:         {df['macro_f1'].mean():.4f} (±{df['macro_f1'].std():.4f})")
            if 'expected_return_mean' in df.columns:
                print(f"Expected Return:        {df['expected_return_mean'].mean():.6f} (±{df['expected_return_mean'].std():.4f})")

        print(f"Directional Accuracy:   {df['directional_accuracy'].mean():.4f} (±{df['directional_accuracy'].std():.4f})")
        print(f"Matthews Correlation:   {df['mcc'].mean():.4f} (±{df['mcc'].std():.4f})")
        print(f"F1 Score:              {df['f1'].mean():.4f} (±{df['f1'].std():.4f})")
        print(f"Precision:             {df['precision'].mean():.4f} (±{df['precision'].std():.4f})")
        print(f"Recall:                {df['recall'].mean():.4f} (±{df['recall'].std():.4f})")

        if self.problem_type == 'multiclass' and 'expected_return_mean' in df.columns:
            print("" + "="*50)
            print("TOP 10 BY EXPECTED RETURN (mean)")
            print("="*50)
            top_er = df.nlargest(10, 'expected_return_mean')
            for _, row in top_er.iterrows():
                print(f"{row['company']:<20} | {row['sector']:<15} | E[r]_mean: {row['expected_return_mean']:.4e} | Macro-F1: {row['macro_f1']:.3f}")

        if 'sector' in df.columns and df['sector'].nunique() > 1:
            print("" + "="*50)
            print("PERFORMANCE BY SECTOR")
            print("="*50)
            sector_stats = df.groupby('sector').agg({
                'directional_accuracy': ['mean', 'std', 'count'],
                'mcc': ['mean', 'std'],
                'r2': 'mean' if self.problem_type == 'regression' else lambda x: np.nan,
                'mae': 'mean' if self.problem_type == 'regression' else lambda x: np.nan
            }).round(4)
            sector_stats.columns = ['_'.join(col).strip() if col[1] else col[0] for col in sector_stats.columns]
            sector_stats = sector_stats.sort_values('directional_accuracy_mean', ascending=False)
            for sector, row in sector_stats.iterrows():
                print(f"{sector:<20} | Acc: {row['directional_accuracy_mean']:.3f}±{row['directional_accuracy_std']:.3f} | "
                      f"MCC: {row['mcc_mean']:.3f} | Companies: {int(row['directional_accuracy_count'])}")

        print("" + "="*50)
        print("TOP 10 PERFORMERS (by Directional Accuracy)")
        print("="*50)
        top_performers = df.nlargest(10, 'directional_accuracy')
        for _, row in top_performers.iterrows():
            print(f"{row['company']:<20} | {row['sector']:<15} | "
                  f"Acc: {row['directional_accuracy']:.3f} | MCC: {row['mcc']:.3f}")

        return analysis

    def save_results(self, results, output_dir='results/benchmarking'):
        if results is not None and not results.empty:
            model_name = self.model_type

            if self.problem_type == 'regression':
                out_dir = os.path.join(output_dir, 'regression')
            elif self.problem_type == 'classification':
                out_dir = os.path.join(output_dir, 'classification')
            else:
                out_dir = os.path.join(output_dir, 'multiclass')

            os.makedirs(out_dir, exist_ok=True)

            output_path = os.path.join(out_dir, f"{model_name}.csv")

            results.to_csv(output_path, index=False)
            print(f"Results saved to {output_path}")
        else:
            print("No results to save.")
            
    def get_loss_curves_df(self):
        if not self.loss_curves:
            print("No loss curves logged yet.")
            return pd.DataFrame()
        return pd.DataFrame(self.loss_curves)

    def save_loss_curves(self, out_path='results/benchmarking/'):
        df = self.get_loss_curves_df()
        if df.empty:
            print("No loss curves to save.")
            return
        if self.problem_type == 'regression':
            out_path = os.path.join(out_path, 'regression', f"{self.model_type}_loss_curves.csv")
        elif self.problem_type == 'classification':
            out_path = os.path.join(out_path, 'classification', f"{self.model_type}_loss_curves.csv")
        else:
            out_path = os.path.join(out_path, 'multiclass', f"{self.model_type}_loss_curves.csv")
            
        os.makedirs(os.path.dirname(out_path), exist_ok=True)
        
        df.to_csv(out_path, index=False)
        print(f"Loss curves saved to {out_path}")

    def get_feature_importance_analysis(self):
        print("Feature importance analysis not implemented yet.")
        print("Consider implementing SHAP values or permutation importance for better insights.")
        return None

## Data Preparation

In [6]:
master_df = pd.read_parquet('../data/dataset/ta_nlp_sector.parquet')

In [7]:
master_df.columns

Index(['date', 'open', 'high', 'low', 'close', 'adj_close', 'volume', 'ticker',
       'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9',
       'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3',
       'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'ret_1d',
       'roll_ret_1d', 'roll_ret_5d', 'roll_ret_20d', 'text', 'sentiment',
       'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy',
       'emotion_neutral', 'emotion_sadness', 'emotion_surprize',
       'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct',
       'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct',
       'emotion_surprize_pct', 'positive_emotion', 'negative_emotion',
       'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct',
       'uncertainty_emotion_pct', 'stance_label', 'finbert_label',
       'stance_score', 'finbert_score', 'finbert_up', 'finbert_down',
       'finbert_neutral', 'sector', 'company_name', 'sector_open_mean',
       'sector_high_mean', 'sector_low_mean', 'sector_close_mean',
       'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d',
       'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector',
       'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector',
       'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector',
       'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower',
       'market_close', 'sector_rel_strength', 'sector_dispersion_1d'],
      dtype='object')

In [8]:
master_df

,date,open,high,low,close,adj_close,volume,ticker,ema_12,ema_26,...,macd_12_26_9_sector,macdh_12_26_9_sector,macds_12_26_9_sector,rsi_14_sector,sector_bb_upper,sector_bb_middle,sector_bb_lower,market_close,sector_rel_strength,sector_dispersion_1d
0,2012-09-04,95.108574,96.448570,94.928574,96.424286,87.121140,91973000.0,AAPL,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1464.800169,NaN,NaN
1,2012-09-05,96.510002,96.621429,95.657143,95.747147,86.509338,84093800.0,AAPL,NaN,NaN,...,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,1481.232189,NaN,0.006548
2,2012-09-06,96.167145,96.898575,95.828575,96.610001,87.288956,97799100.0,AAPL,NaN,NaN,...,NaN,NaN,NaN,28.755774,NaN,NaN,NaN,1502.627054,NaN,0.006476
3,2012-09-07,96.864288,97.497147,96.538574,97.205711,87.827171,82416600.0,AAPL,NaN,NaN,...,NaN,NaN,NaN,28.562466,NaN,NaN,NaN,1506.971629,NaN,0.008604
4,2012-09-10,97.207146,97.612854,94.585716,94.677139,85.542564,121999500.0,AAPL,NaN,NaN,...,NaN,NaN,NaN,22.507443,NaN,NaN,NaN,1503.735325,NaN,0.012007
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108587,2017-08-28,76.900002,76.940002,76.260002,76.470001,76.470001,8229700.0,XOM,77.187452,78.267858,...,-0.111192,0.016355,-0.127548,53.634155,63.049962,61.01430,58.978638,3101.328695,-0.007883,0.005228
108588,2017-08-29,76.209999,76.489998,76.080002,76.449997,76.449997,7060400.0,XOM,77.073998,78.133202,...,-0.067027,0.048417,-0.115443,54.205103,62.862103,60.94445,59.026797,3102.507723,-0.016661,0.002030
108589,2017-08-30,76.239998,76.449997,76.059998,76.099998,76.099998,8218000.0,XOM,76.924151,77.982594,...,-0.037643,0.062240,-0.099883,53.126723,62.639604,60.86875,59.097896,3128.753695,-0.017629,0.004873
108590,2017-08-31,76.269997,76.489998,76.050003,76.330002,76.330002,15641700.0,XOM,76.832744,77.860180,...,0.013408,0.090633,-0.077225,57.342960,62.525437,60.83190,59.138363,3141.201722,-0.008376,0.006185
108591,2017-09-01,76.370003,76.849998,76.320000,76.570000,76.570000,7340800.0,XOM,76.792322,77.764611,...,0.088512,0.132590,-0.044078,62.040301,62.426369,60.80760,59.188831,3136.813139,-0.001766,0.007085

In [9]:
columns_to_check = [
                    'sentiment',
                    
                    'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy',
                    'emotion_neutral', 'emotion_sadness', 'emotion_surprize',
                    'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct',
                    'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct',
                    'emotion_surprize_pct', 
                    
                    'positive_emotion', 'negative_emotion','uncertainty_emotion', 
                    'positive_emotion_pct', 'negative_emotion_pct','uncertainty_emotion_pct', 
                    
                    'stance_label', 'stance_score', 
                    
                    'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down',
                    'finbert_neutral', 
                    
                    'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean',
                    'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d',
                    'sector_ret_20d', 'sector_range', 'sector_vol_20d', 
                    
                    'ema_12_sector','ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector',
                    'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector',
                    'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower',
                    'market_close', 'sector_rel_strength', 'sector_dispersion_1d'
                ]

print(f"Initial master_df shape: {master_df.shape}")

master_df = master_df.dropna(subset=columns_to_check)

print(f"After dropping NaNs in selected columns, master_df shape: {master_df.shape}")

master_df.reset_index(drop=True, inplace=True)

display(master_df)

Initial master_df shape: (108592, 80)
After dropping NaNs in selected columns, master_df shape: (104476, 80)

,date,open,high,low,close,adj_close,volume,ticker,ema_12,ema_26,...,macd_12_26_9_sector,macdh_12_26_9_sector,macds_12_26_9_sector,rsi_14_sector,sector_bb_upper,sector_bb_middle,sector_bb_lower,market_close,sector_rel_strength,sector_dispersion_1d
0,2012-11-14,77.928574,78.207146,76.597145,76.697144,69.613815,119292600.0,AAPL,80.708033,84.949698,...,-0.913108,-0.181794,-0.731314,27.619972,63.948320,61.465736,58.983152,1484.350654,-0.003089,0.006800
1,2012-11-15,76.790001,77.071426,74.660004,75.088570,68.153778,197477700.0,AAPL,79.843501,84.219244,...,-0.926239,-0.155940,-0.770299,32.479352,63.646173,61.261193,58.876213,1484.574993,0.002003,0.019838
2,2012-11-16,75.028572,75.714287,72.250000,75.382858,68.420891,316723400.0,AAPL,79.157248,83.564697,...,-0.892113,-0.097452,-0.794662,37.450172,63.236926,61.078872,58.920817,1497.780485,0.010276,0.010265
3,2012-11-19,77.244286,81.071426,77.125717,80.818573,73.354591,205829400.0,AAPL,79.412836,83.361280,...,-0.733193,0.049174,-0.782368,51.350390,63.001827,61.010079,59.018330,1506.128807,0.024682,0.018850
4,2012-11-20,81.701431,81.707146,79.225716,80.129997,72.729614,160688500.0,AAPL,79.523169,83.121926,...,-0.579416,0.162361,-0.741778,53.267164,62.959435,60.996029,59.032623,1508.629302,0.025531,0.007554
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104471,2017-08-28,76.900002,76.940002,76.260002,76.470001,76.470001,8229700.0,XOM,77.187452,78.267858,...,-0.111192,0.016355,-0.127548,53.634155,63.049962,61.014300,58.978638,3101.328695,-0.007883,0.005228
104472,2017-08-29,76.209999,76.489998,76.080002,76.449997,76.449997,7060400.0,XOM,77.073998,78.133202,...,-0.067027,0.048417,-0.115443,54.205103,62.862103,60.944450,59.026797,3102.507723,-0.016661,0.002030
104473,2017-08-30,76.239998,76.449997,76.059998,76.099998,76.099998,8218000.0,XOM,76.924151,77.982594,...,-0.037643,0.062240,-0.099883,53.126723,62.639604,60.868750,59.097896,3128.753695,-0.017629,0.004873
104474,2017-08-31,76.269997,76.489998,76.050003,76.330002,76.330002,15641700.0,XOM,76.832744,77.860180,...,0.013408,0.090633,-0.077225,57.342960,62.525437,60.831900,59.138363,3141.201722,-0.008376,0.006185
104475,2017-09-01,76.370003,76.849998,76.320000,76.570000,76.570000,7340800.0,XOM,76.792322,77.764611,...,0.088512,0.132590,-0.044078,62.040301,62.426369,60.807600,59.188831,3136.813139,-0.001766,0.007085

In [10]:
print(master_df.columns)

Index(['date', 'open', 'high', 'low', 'close', 'adj_close', 'volume', 'ticker',
       'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9',
       'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3',
       'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'ret_1d',
       'roll_ret_1d', 'roll_ret_5d', 'roll_ret_20d', 'text', 'sentiment',
       'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy',
       'emotion_neutral', 'emotion_sadness', 'emotion_surprize',
       'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct',
       'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct',
       'emotion_surprize_pct', 'positive_emotion', 'negative_emotion',
       'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct',
       'uncertainty_emotion_pct', 'stance_label', 'finbert_label',
       'stance_score', 'finbert_score', 'finbert_up', 'finbert_down',
       'finbert_neutral', 'sector', 'company_name', 'sector_open_mean',
       'sector_high_mean', 'sector_low_mean', 'sector_close_mean',
       'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d',
       'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector',
       'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector',
       'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector',
       'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower',
       'market_close', 'sector_rel_strength', 'sector_dispersion_1d'],
      dtype='object')

In [11]:
feature_columns = [
    'open', 'high', 'low', 'close', 'volume',
    # 'roll_ret_1d', 'roll_ret_5d', 
    # 'roll_ret_20d',
    
    'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9',
    'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3',
    'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv',
]

new_indicator_columns = [
    # 'sentiment',
                    
    # 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy',
    # 'emotion_neutral', 'emotion_sadness', 'emotion_surprize',
    # 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct',
    # 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct',
    # 'emotion_surprize_pct', 
    
    # 'positive_emotion', 'negative_emotion','uncertainty_emotion', 
    # 'positive_emotion_pct', 'negative_emotion_pct','uncertainty_emotion_pct', 
    
    # 'stance_label', 'stance_score', 
    
    # 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down',
    # 'finbert_neutral', 
    
    # 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean',
    # 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d',
    # 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 
    
    # 'ema_12_sector','ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector',
    # 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector',
    # 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower',
    # 'market_close', 'sector_rel_strength', 'sector_dispersion_1d'
]

# feature_columns.extend(new_indicator_columns)



sequence_length=12



all_pipelines = {}
all_results_dfs = {}
all_analyses = {}
fixed_bucket_edges = np.array([-0.08, -0.03, -0.01, 0.0, 0.01, 0.03, 0.08], dtype=float)
n_classes = len(fixed_bucket_edges) - 1
ordinal_head = 'corn'

In [12]:
print(master_df.shape)
master_df = master_df.dropna(subset=feature_columns).sort_values(['ticker','date'])
print(master_df.shape)

(104476, 80)
(104220, 80)

## Pipeline Execution

In [13]:
# print(f"\n{'='*25}\n  RUNNING PIPELINE FOR: GRU\n{'='*25}\n")

# pipeline_GRU = StockPredictionPipeline(
#     df=master_df,
#     feature_columns=feature_columns,
#     model_type='GRU',
#     sequence_length=sequence_length,
#     problem_type='classification',
#     horizon_steps=1,
#     n_classes=n_classes,
#     ordinal_head=ordinal_head,
#     fixed_bucket_edges=fixed_bucket_edges
# )

# results_GRU = pipeline_GRU.run_pipeline()

# loss_df = pipeline_GRU.get_loss_curves_df()

# pipeline_GRU.save_loss_curves('results/benchmarking/')

# if results_GRU is not None and not results_GRU.empty:
#     analysis_GRU = pipeline_GRU.analyze_results()
#     pipeline_GRU.save_results(results_GRU, output_dir='results/benchmarking/')
#     all_pipelines["GRU"] = pipeline_GRU
#     all_results_dfs["GRU"] = results_GRU
#     all_analyses["GRU"] = analysis_GRU

#     print("\nDisplaying first 5 rows of GRU results:")
#     display(results_GRU.head())
# else:
#     print(f"\n[FAILED] Pipeline for GRU did not produce any results.")

# del pipeline_GRU

In [14]:
sentinemt_columns = [
    'sentiment',
]

emotion_columns = [
    'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy',
    'emotion_neutral', 'emotion_sadness', 'emotion_surprize',
    'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct',
    'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct',
    'emotion_surprize_pct',
]

unified_emotion_columns = [
    'positive_emotion', 'negative_emotion','uncertainty_emotion',
    'positive_emotion_pct', 'negative_emotion_pct','uncertainty_emotion_pct',
]

stance_columns = [
    'stance_label', 'stance_score',
]

finbert_columns = [
    'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down',
    'finbert_neutral',
]

sector_columns = ['sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean',
                  'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d',
                  'sector_ret_20d', 'sector_range', 'sector_vol_20d', 
                  
                  'ema_12_sector','ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector',
                  'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector',
                  'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower',
                  'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

In [ ]:
try:
    import optuna
except ImportError:
    import sys
    !{sys.executable} -m pip install optuna
    import optuna
    
from pathlib import Path
from datetime import datetime
    
# Define feature sets to test
feature_sets = {
    'base': feature_columns,
    'sentinment' : feature_columns + sentinemt_columns,
    'emotion' : feature_columns + emotion_columns,
    'unified_emotion': feature_columns + unified_emotion_columns,
    'finbert': feature_columns + finbert_columns,
    'all_nlp': feature_columns + sentinemt_columns + emotion_columns + unified_emotion_columns + stance_columns + finbert_columns,
    # 'sector': feature_columns + sector_columns,
    # 'sector_sentiment': feature_columns + sector_columns + sentinemt_columns,
    # 'sector_emotion': feature_columns + sector_columns + emotion_columns,
    # 'sector_unified_emotion': feature_columns + sector_columns + unified_emotion_columns,
    # 'sector_finbert': feature_columns + sector_columns + finbert_columns,
    # 'sector_all_nlp': feature_columns + sector_columns + sentinemt_columns + emotion_columns + unified_emotion_columns + stance_columns + finbert_columns,
}

def objective(trial):
    params = {
        'problem_type': 'classification',  # or 'classification'
        'feature_set': trial.suggest_categorical('feature_set', list(feature_sets.keys())),
        'model_type': trial.suggest_categorical('model_type', ['LSTM', 'BiLSTM', 'GRU', 'BiGRU']),
        'sequence_length': trial.suggest_int('sequence_length',5, 20, step=5),
        'horizon_steps': trial.suggest_categorical('horizon_steps', [1]),
        'hidden1': trial.suggest_categorical('hidden1', [64, 128, 256]),
        'hidden2': trial.suggest_categorical('hidden2', [32, 64, 128]),
        'num_layers': trial.suggest_categorical('num_layers', [1, 2]),
        'inter_rnn_drop': trial.suggest_float('inter_rnn_drop', 0.0, 0.4, step=0.1),
        'dropout': trial.suggest_float('dropout', 0.0, 0.8, step=0.1),
        'batch_size': trial.suggest_categorical('batch_size', [16, 32, 64]),
        'learning_rate': trial.suggest_float('learning_rate', 1e-6, 1e-2, log=True),
        'weight_decay': trial.suggest_float('weight_decay', 1e-7, 1e-3, log=True),
        'lr_patience': trial.suggest_categorical('lr_patience', [5, 7, 10]),
        'lr_factor': trial.suggest_categorical('lr_factor', [0.4, 0.8]),
        'early_stopping_patience': trial.suggest_categorical('early_stopping_patience', [10, 15, 20]),
        'max_epochs': trial.suggest_categorical('max_epochs', [20, 30, 50]),
        'huber_delta': trial.suggest_float('huber_delta', 0.1, 2.0),
        'early_stopping_min_delta': trial.suggest_float('early_stopping_min_delta', 0.0, 0.01),
    }

    selected_features = feature_sets[params['feature_set']]
    missing_cols = [c for c in selected_features if c not in master_df.columns]
    if missing_cols:
        print(f"Missing columns for feature_set={params['feature_set']}: {missing_cols}")
        return -1.0

    pipeline = StockPredictionPipeline(
        df=master_df,
        feature_columns=selected_features,
        model_type=params['model_type'],
        sequence_length=params['sequence_length'],
        problem_type=params['problem_type'],
        horizon_steps=params['horizon_steps'],
        n_classes=n_classes,
        ordinal_head=ordinal_head,
        fixed_bucket_edges=fixed_bucket_edges,
        hidden1=params['hidden1'],
        hidden2=params['hidden2'],
        num_layers=params['num_layers'],
        inter_rnn_drop=params['inter_rnn_drop'],
        dropout=params['dropout'],
        batch_size=params['batch_size'],
        learning_rate=params['learning_rate'],
        weight_decay=params['weight_decay'],
        lr_patience=params['lr_patience'],
        lr_factor=params['lr_factor'],
        early_stopping_patience=params['early_stopping_patience'],
        max_epochs=params['max_epochs'],
        huber_delta=params['huber_delta'],
        early_stopping_min_delta=params['early_stopping_min_delta']
    )

    results_df = pipeline.run_pipeline()
    del pipeline
    torch.cuda.empty_cache()

    if results_df is None or results_df.empty:
        print('[DEBUG] results_df empty or None')
        return -1.0

    print('[DEBUG] results_df shape:', results_df.shape)
    print('[DEBUG] results_df columns:', results_df.columns.tolist())

    # Aggregate validation metrics
    val_f1 = results_df['val_f1'].mean() if 'val_f1' in results_df.columns else np.nan
    if not np.isfinite(val_f1) and 'best_threshold_metric' in results_df.columns:
        val_f1 = results_df['best_threshold_metric'].mean()
    val_mcc = results_df['val_mcc'].mean() if 'val_mcc' in results_df.columns else np.nan
    print('[DEBUG] val_mcc:', val_mcc)
    val_precision = results_df['val_precision'].mean() if 'val_precision' in results_df.columns else np.nan
    val_recall = results_df['val_recall'].mean() if 'val_recall' in results_df.columns else np.nan
    val_dir_acc = results_df['val_directional_accuracy'].mean() if 'val_directional_accuracy' in results_df.columns else np.nan

    trial.set_user_attr('val_f1', float(val_f1))
    trial.set_user_attr('val_mcc', float(val_mcc))
    trial.set_user_attr('val_precision', float(val_precision))
    trial.set_user_attr('val_recall', float(val_recall))
    trial.set_user_attr('val_directional_accuracy', float(val_dir_acc))

    # Primary metric: mean val MCC (classification) or mean MAE (regression)
    if params['problem_type'] == 'classification':
        score = val_mcc
        if not np.isfinite(score):
            return -1.0
        return float(score)
    else:
        # minimize MAE -> maximize negative MAE
        if 'mae' not in results_df.columns:
            return -1.0
        mae = results_df['mae'].mean()
        if not np.isfinite(mae):
            return -1.0
        return float(-mae)


N_TRIALS = 250

# Run study
study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=N_TRIALS, timeout=60*60*8)  # 8 hours max
# Collect results
optuna_results = study.trials_dataframe()
# include user attrs
user_attrs = pd.DataFrame([t.user_attrs for t in study.trials])
optuna_results = pd.concat([optuna_results, user_attrs], axis=1)
optuna_results = optuna_results.sort_values('value', ascending=False)
optuna_results

timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
out_path = f'../results/benchmarking/classification/optuna_tuning_NLP_1H.csv'
Path('../results/benchmarking/classification').mkdir(parents=True, exist_ok=True)
optuna_results.to_csv(out_path, index=False)
print(f'Saved Optuna results to {out_path}')

[I 2026-02-24 22:23:12,650] A new study created in memory with name: no-name-cb963b44-458d-49e4-9490-3d14de7455d5

Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 5
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.66591 | val 0.69776
  Epoch 011 - train 0.69681 | val 0.69804
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4430, MCC: 0.0000, F1: 0.6140

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.70397 | val 0.80201
  Epoch 011 - train 0.71142 | val 0.80282
  Classification -> best τ=0.535 (val F1=0.1654)
  Directional -> Accuracy: 0.4375, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 6). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.70641 | val 0.68011
  Epoch 015 - train 0.70422 | val 0.68129
  Classification -> best τ=0.505 (val F1=0.3317)
  Directional -> Accuracy: 0.4800, MCC: 0.0401, F1: 0.1875

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.70769 | val 0.74267
  Epoch 011 - train 0.69475 | val 0.74649
  Classification -> best τ=0.550 (val F1=0.1132)
  Directional -> Accuracy: 0.4935, MCC: 0.0385, F1: 0.3607

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.70690 | val 0.73991
  Epoch 011 - train 0.68222 | val 0.74646
  Classification -> best τ=0.545 (val F1=0.3016)
  Directional -> Accuracy: 0.5283, MCC: 0.0647, F1: 0.5098

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.69231 | val 0.73671
  Epoch 011 - train 0.70698 | val 0.74307
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4762, MCC: 0.0000, F1: 0.6452

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.71022 | val 0.70650
  Epoch 011 - train 0.70642 | val 0.70652
  Classification -> best τ=0.555 (val F1=0.1738)
  Directional -> Accuracy: 0.5833, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 6). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.72871 | val 0.67319
  Epoch 011 - train 0.69535 | val 0.67527
  Classification -> best τ=0.480 (val F1=0.1936)
  Directional -> Accuracy: 0.5106, MCC: -0.0846, F1: 0.2581

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.69000 | val 0.69165
  Epoch 015 - train 0.68919 | val 0.69629
  Classification -> best τ=0.530 (val F1=0.3015)
  Directional -> Accuracy: 0.6047, MCC: 0.1332, F1: 0.4138

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for proper time series validation for BRK-A. Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for proper time series validation for BSAC. Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.69969 | val 0.77193
  Epoch 011 - train 0.70916 | val 0.77288
  Classification -> best τ=0.485 (val F1=0.1449)
  Directional -> Accuracy: 0.4306, MCC: 0.0000, F1: 0.6019

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.71153 | val 0.70435
  Epoch 011 - train 0.70973 | val 0.70496
  Classification -> best τ=0.510 (val F1=0.1251)
  Directional -> Accuracy: 0.5192, MCC: -0.0636, F1: 0.0741

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.71822 | val 0.69336
  Epoch 011 - train 0.71326 | val 0.69429
  Classification -> best τ=0.525 (val F1=0.0187)
  Directional -> Accuracy: 0.5167, MCC: 0.1302, F1: 0.6742

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.70096 | val 0.70402
  Epoch 014 - train 0.70253 | val 0.70863
  Classification -> best τ=0.525 (val F1=0.0956)
  Directional -> Accuracy: 0.4222, MCC: -0.2211, F1: 0.1875

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.70222 | val 0.66888
  Epoch 020 - train 0.71628 | val 0.65290
  Classification -> best τ=0.550 (val F1=0.4152)
  Directional -> Accuracy: 0.5397, MCC: 0.0938, F1: 0.2927

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.70562 | val 0.71335
  Epoch 015 - train 0.69096 | val 0.72786
  Classification -> best τ=0.530 (val F1=0.0572)
  Directional -> Accuracy: 0.5091, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.70520 | val 0.70246
  Epoch 011 - train 0.69014 | val 0.70236
  Classification -> best τ=0.505 (val F1=0.2038)
  Directional -> Accuracy: 0.5417, MCC: 0.0000, F1: 0.7027

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.71483 | val 0.71932
  Epoch 011 - train 0.72908 | val 0.72465
  Classification -> best τ=0.510 (val F1=0.2140)
  Directional -> Accuracy: 0.5645, MCC: 0.1252, F1: 0.6087

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.68174 | val 0.74491
  Epoch 011 - train 0.69655 | val 0.74863
  Classification -> best τ=0.530 (val F1=0.1204)
  Directional -> Accuracy: 0.4872, MCC: -0.0707, F1: 0.5745

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.69925 | val 0.68661
  Epoch 013 - train 0.68829 | val 0.68699
  Classification -> best τ=0.520 (val F1=0.2404)
  Directional -> Accuracy: 0.4412, MCC: -0.1664, F1: 0.5366

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 6). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.68934 | val 0.70722
  Epoch 011 - train 0.69902 | val 0.70763
  Classification -> best τ=0.475 (val F1=0.0719)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.68496 | val 0.70706
  Epoch 011 - train 0.69792 | val 0.71092
  Classification -> best τ=0.530 (val F1=0.1627)
  Directional -> Accuracy: 0.6600, MCC: 0.2181, F1: 0.7733

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.71037 | val 0.69992
  Epoch 011 - train 0.70716 | val 0.69957
  Classification -> best τ=0.480 (val F1=0.1777)
  Directional -> Accuracy: 0.3971, MCC: -0.2228, F1: 0.4938

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.71398 | val 0.70237
  Epoch 011 - train 0.70570 | val 0.70164
  Classification -> best τ=0.485 (val F1=0.0062)
  Directional -> Accuracy: 0.4167, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.69900 | val 0.74161
  Epoch 011 - train 0.68744 | val 0.73901
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4853, MCC: 0.0000, F1: 0.6535

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.70556 | val 0.67427
  Epoch 020 - train 0.70775 | val 0.66405
  Classification -> best τ=0.505 (val F1=0.4332)
  Directional -> Accuracy: 0.5345, MCC: -0.1194, F1: 0.6966

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.71732 | val 0.68804
  Epoch 018 - train 0.71087 | val 0.69410
  Classification -> best τ=0.530 (val F1=0.2425)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.5714

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.70358 | val 0.72616
  Epoch 011 - train 0.71472 | val 0.72894
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6000, MCC: 0.0000, F1: 0.7500

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.72839 | val 0.65587
  Epoch 020 - train 0.69828 | val 0.65485
  Classification -> best τ=0.475 (val F1=0.2889)
  Directional -> Accuracy: 0.4407, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.70712 | val 0.70281
  Epoch 011 - train 0.69027 | val 0.70983
  Classification -> best τ=0.530 (val F1=0.2059)
  Directional -> Accuracy: 0.4889, MCC: -0.0391, F1: 0.5965

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.72031 | val 0.70016
  Epoch 011 - train 0.69827 | val 0.70144
  Classification -> best τ=0.455 (val F1=0.1599)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.70857 | val 0.77183
  Epoch 011 - train 0.73772 | val 0.77827
  Classification -> best τ=0.435 (val F1=0.3248)
  Directional -> Accuracy: 0.4783, MCC: -0.2421, F1: 0.6471

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.70279 | val 0.71074
  Epoch 011 - train 0.70672 | val 0.71064
  Classification -> best τ=0.540 (val F1=0.2262)
  Directional -> Accuracy: 0.4906, MCC: -0.0124, F1: 0.3721

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.70232 | val 0.68427
  Epoch 020 - train 0.69456 | val 0.67666
  Classification -> best τ=0.540 (val F1=0.2843)
  Directional -> Accuracy: 0.4533, MCC: 0.0074, F1: 0.1633

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.70028 | val 0.71190
  Epoch 011 - train 0.71508 | val 0.71731
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4878, MCC: 0.0000, F1: 0.6557

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.76976 | val 0.74047
  Epoch 011 - train 0.71814 | val 0.74498
  Classification -> best τ=0.460 (val F1=0.0766)
  Directional -> Accuracy: 0.5435, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.71075 | val 0.68833
  Epoch 013 - train 0.67524 | val 0.68742
  Classification -> best τ=0.485 (val F1=0.2175)
  Directional -> Accuracy: 0.5507, MCC: 0.0913, F1: 0.5974

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.71000 | val 0.70968
  Epoch 011 - train 0.71485 | val 0.71089
  Classification -> best τ=0.520 (val F1=0.1574)
  Directional -> Accuracy: 0.5778, MCC: 0.1540, F1: 0.6122

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.69118 | val 0.71465
  Epoch 011 - train 0.68829 | val 0.71671
  Classification -> best τ=0.540 (val F1=0.1393)
  Directional -> Accuracy: 0.5085, MCC: 0.0352, F1: 0.5672

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.69628 | val 0.76207
  Epoch 011 - train 0.69107 | val 0.76084
  Classification -> best τ=0.510 (val F1=0.0687)
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 6). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.74701 | val 0.71558
  Epoch 011 - train 0.72272 | val 0.71796
  Classification -> best τ=0.535 (val F1=0.3004)
  Directional -> Accuracy: 0.4286, MCC: 0.0857, F1: 0.5000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.72869 | val 0.66783
  Epoch 018 - train 0.74497 | val 0.67357
  Classification -> best τ=0.425 (val F1=0.3273)
  Directional -> Accuracy: 0.4878, MCC: -0.0358, F1: 0.5714

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 6). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.71672 | val 0.73921
  Epoch 011 - train 0.71396 | val 0.73949
  Classification -> best τ=0.500 (val F1=0.0616)
  Directional -> Accuracy: 0.4545, MCC: -0.0905, F1: 0.4474

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.69461 | val 0.69329
  Epoch 011 - train 0.68401 | val 0.69443
  Classification -> best τ=0.510 (val F1=0.1871)
  Directional -> Accuracy: 0.5510, MCC: 0.1094, F1: 0.5926

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.71327 | val 0.74403
  Epoch 011 - train 0.66922 | val 0.74504
  Classification -> best τ=0.545 (val F1=0.1936)
  Directional -> Accuracy: 0.4255, MCC: 0.0000, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.70743 | val 0.70867
  Epoch 011 - train 0.69365 | val 0.71078
  Classification -> best τ=0.510 (val F1=0.0884)
  Directional -> Accuracy: 0.5476, MCC: -0.1623, F1: 0.0952

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.70505 | val 0.92989
  Epoch 011 - train 0.69703 | val 0.93859
  Classification -> best τ=0.450 (val F1=0.0331)
  Directional -> Accuracy: 0.5862, MCC: 0.1484, F1: 0.6571

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.69035 | val 0.71054
  Epoch 011 - train 0.68221 | val 0.71213
  Classification -> best τ=0.480 (val F1=0.1095)
  Directional -> Accuracy: 0.5593, MCC: 0.1240, F1: 0.5938

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.70236 | val 0.69418
  Epoch 011 - train 0.68068 | val 0.69350
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.70142 | val 0.69684
  Epoch 011 - train 0.68368 | val 0.69715
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5172, MCC: 0.0000, F1: 0.6818

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.70488 | val 0.69088

[I 2026-02-24 22:24:01,549] Trial 0 finished with value: 0.1599141835265164 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 5, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.1, 'dropout': 0.6000000000000001, 'batch_size': 32, 'learning_rate': 5.56109939827174e-06, 'weight_decay': 1.1123656878150408e-07, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 0.630499733580434, 'early_stopping_min_delta': 0.002837630266545419}. Best is trial 0 with value: 0.1599141835265164.

  Epoch 015 - train 0.72032 | val 0.69061
  Classification -> best τ=0.485 (val F1=0.2350)
  Directional -> Accuracy: 0.4921, MCC: -0.0182, F1: 0.4667

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.1599141835265164
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 10
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.58029 | val 0.82581
  Epoch 017 - train 0.52132 | val 1.02743
  Classification -> best τ=0.630 (val F1=0.2695)
  Directional -> Accuracy: 0.5513, MCC: 0.0646, F1: 0.3860

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.58758 | val 0.90124
  Epoch 017 - train 0.53399 | val 0.98460
  Classification -> best τ=0.500 (val F1=0.2451)
  Directional -> Accuracy: 0.6383, MCC: 0.2974, F1: 0.7463

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 11). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.59634 | val 0.78899
  Epoch 017 - train 0.54471 | val 0.85319
  Classification -> best τ=0.440 (val F1=0.3303)
  Directional -> Accuracy: 0.4490, MCC: -0.2266, F1: 0.6087

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.58023 | val 1.13265
  Epoch 016 - train 0.52731 | val 1.20160
  Classification -> best τ=0.445 (val F1=0.1535)
  Directional -> Accuracy: 0.5395, MCC: 0.0000, F1: 0.7009

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.57623 | val 0.72998
  Epoch 019 - train 0.49092 | val 0.86194
  Classification -> best τ=0.585 (val F1=0.4567)
  Directional -> Accuracy: 0.5769, MCC: 0.2324, F1: 0.4500

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.53824 | val 1.99422
  Epoch 017 - train 0.47127 | val 2.32172
  Classification -> best τ=0.475 (val F1=0.2234)
  Directional -> Accuracy: 0.4694, MCC: -0.0589, F1: 0.4348

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.62045 | val 0.79324
  Epoch 016 - train 0.57339 | val 0.89101
  Classification -> best τ=0.460 (val F1=0.1679)
  Directional -> Accuracy: 0.4085, MCC: 0.0000, F1: 0.5800

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 11). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.60317 | val 1.46333
  Epoch 016 - train 0.56406 | val 1.75039
  Classification -> best τ=0.470 (val F1=0.1714)
  Directional -> Accuracy: 0.5870, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.56938 | val 0.71074
  Epoch 019 - train 0.47821 | val 0.77298
  Classification -> best τ=0.605 (val F1=0.3838)
  Directional -> Accuracy: 0.6429, MCC: 0.1754, F1: 0.3478

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for proper time series validation for BRK-A. Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for proper time series validation for BSAC. Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.54383 | val 1.77341
  Epoch 016 - train 0.48355 | val 2.29410
  Classification -> best τ=0.425 (val F1=0.1873)
  Directional -> Accuracy: 0.4366, MCC: 0.0000, F1: 0.6078

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.58513 | val 0.81408
  Epoch 020 - train 0.48587 | val 1.15410
  Classification -> best τ=0.490 (val F1=0.1304)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.61170 | val 0.75360
  Epoch 016 - train 0.55786 | val 0.81589
  Classification -> best τ=0.470 (val F1=0.0637)
  Directional -> Accuracy: 0.5085, MCC: 0.0046, F1: 0.6588

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.55869 | val 1.83309
  Epoch 016 - train 0.51100 | val 1.84414
  Classification -> best τ=0.500 (val F1=0.1768)
  Directional -> Accuracy: 0.5682, MCC: 0.1412, F1: 0.5581

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.61709 | val 0.61493
  Epoch 020 - train 0.53366 | val 0.71329
  Classification -> best τ=0.490 (val F1=0.3813)
  Directional -> Accuracy: 0.5323, MCC: 0.0690, F1: 0.6027

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.54337 | val 1.87879
  Epoch 016 - train 0.48968 | val 2.28019
  Classification -> best τ=0.545 (val F1=0.2816)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.56978 | val 0.78712
  Epoch 017 - train 0.50842 | val 0.87437
  Classification -> best τ=0.580 (val F1=0.2645)
  Directional -> Accuracy: 0.5634, MCC: 0.1281, F1: 0.5753

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.61518 | val 1.68508
  Epoch 016 - train 0.57678 | val 2.11567
  Classification -> best τ=0.620 (val F1=0.1189)
  Directional -> Accuracy: 0.3934, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.55382 | val 1.73053
  Epoch 016 - train 0.50505 | val 1.98420
  Classification -> best τ=0.395 (val F1=0.1833)
  Directional -> Accuracy: 0.5844, MCC: 0.1262, F1: 0.6596

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.56491 | val 0.96763
  Epoch 016 - train 0.51430 | val 1.17900
  Classification -> best τ=0.445 (val F1=0.2409)
  Directional -> Accuracy: 0.5522, MCC: 0.0222, F1: 0.6667

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 11). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.54352 | val 1.07310
  Epoch 016 - train 0.48633 | val 0.92452
  Classification -> best τ=0.490 (val F1=0.2584)
  Directional -> Accuracy: 0.4545, MCC: -0.0149, F1: 0.0455

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.56852 | val 1.25998
  Epoch 016 - train 0.52207 | val 1.46693
  Classification -> best τ=0.550 (val F1=0.0882)
  Directional -> Accuracy: 0.6531, MCC: 0.1627, F1: 0.7733

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.59179 | val 1.09784
  Epoch 016 - train 0.53876 | val 1.40183
  Classification -> best τ=0.530 (val F1=0.1939)
  Directional -> Accuracy: 0.5224, MCC: 0.1222, F1: 0.1579

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.59967 | val 0.85244
  Epoch 016 - train 0.54933 | val 1.02811
  Classification -> best τ=0.540 (val F1=0.2423)
  Directional -> Accuracy: 0.4746, MCC: 0.0582, F1: 0.3111

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.57000 | val 0.81884
  Epoch 016 - train 0.51901 | val 1.17534
  Classification -> best τ=0.525 (val F1=0.1326)
  Directional -> Accuracy: 0.4925, MCC: -0.0288, F1: 0.3929

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.57471 | val 0.79445
  Epoch 018 - train 0.51636 | val 0.96249
  Classification -> best τ=0.635 (val F1=0.4138)
  Directional -> Accuracy: 0.5439, MCC: 0.1963, F1: 0.4091

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.57731 | val 0.75776
  Epoch 016 - train 0.53028 | val 0.79428
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4167, MCC: 0.0000, F1: 0.5882

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.58083 | val 1.38419
  Epoch 016 - train 0.54224 | val 1.52704
  Classification -> best τ=0.475 (val F1=0.1775)
  Directional -> Accuracy: 0.5000, MCC: 0.0722, F1: 0.4500

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.58876 | val 0.82365
  Epoch 017 - train 0.53943 | val 1.00053
  Classification -> best τ=0.420 (val F1=0.2464)
  Directional -> Accuracy: 0.5517, MCC: 0.2600, F1: 0.3500

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.56161 | val 0.82507
  Epoch 016 - train 0.50786 | val 0.76436
  Classification -> best τ=0.430 (val F1=0.0329)
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.58851 | val 0.79727
  Epoch 016 - train 0.54003 | val 0.83846
  Classification -> best τ=0.520 (val F1=0.1890)
  Directional -> Accuracy: 0.4889, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.60486 | val 0.76392
  Epoch 016 - train 0.56393 | val 0.74196
  Classification -> best τ=0.440 (val F1=0.0877)
  Directional -> Accuracy: 0.4667, MCC: -0.0357, F1: 0.2941

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.56397 | val 0.78556
  Epoch 017 - train 0.50206 | val 0.90997
  Classification -> best τ=0.395 (val F1=0.2573)
  Directional -> Accuracy: 0.5192, MCC: 0.0000, F1: 0.6835

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.59085 | val 0.80687
  Epoch 016 - train 0.53683 | val 1.00944
  Classification -> best τ=0.505 (val F1=0.1482)
  Directional -> Accuracy: 0.4324, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.59291 | val 0.98559
  Epoch 016 - train 0.55239 | val 1.10996
  Classification -> best τ=0.525 (val F1=0.1918)
  Directional -> Accuracy: 0.5000, MCC: 0.0025, F1: 0.5000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.56265 | val 1.33077
  Epoch 016 - train 0.50677 | val 1.43890
  Classification -> best τ=0.575 (val F1=0.2081)
  Directional -> Accuracy: 0.5333, MCC: 0.0546, F1: 0.4615

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.57028 | val 0.76747
  Epoch 017 - train 0.49942 | val 0.79945
  Classification -> best τ=0.350 (val F1=0.3575)
  Directional -> Accuracy: 0.5735, MCC: 0.2920, F1: 0.4528

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.58706 | val 0.74452
  Epoch 016 - train 0.53313 | val 0.77403
  Classification -> best τ=0.525 (val F1=0.1574)
  Directional -> Accuracy: 0.6591, MCC: 0.3674, F1: 0.7273

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.57144 | val 0.77141
  Epoch 017 - train 0.52231 | val 0.87135
  Classification -> best τ=0.400 (val F1=0.2366)
  Directional -> Accuracy: 0.5690, MCC: 0.2207, F1: 0.6575

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.54995 | val 1.06521
  Epoch 016 - train 0.49530 | val 1.20137
  Classification -> best τ=0.520 (val F1=0.1912)
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 11). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.56478 | val 0.67526
  Epoch 020 - train 0.46458 | val 0.66512
  Classification -> best τ=0.395 (val F1=0.4647)
  Directional -> Accuracy: 0.3902, MCC: 0.1631, F1: 0.5283

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.59167 | val 0.71710
  Epoch 016 - train 0.54502 | val 0.74729
  Classification -> best τ=0.475 (val F1=0.2254)
  Directional -> Accuracy: 0.5250, MCC: 0.0115, F1: 0.6780

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 11). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.54942 | val 1.47325
  Epoch 016 - train 0.48383 | val 2.14722
  Classification -> best τ=0.500 (val F1=0.2382)
  Directional -> Accuracy: 0.5325, MCC: 0.1201, F1: 0.6786

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.57963 | val 0.85014
  Epoch 017 - train 0.52518 | val 0.99145
  Classification -> best τ=0.515 (val F1=0.1055)
  Directional -> Accuracy: 0.5625, MCC: 0.1601, F1: 0.6667

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.54669 | val 1.09704
  Epoch 016 - train 0.50462 | val 1.21074
  Classification -> best τ=0.550 (val F1=0.4359)
  Directional -> Accuracy: 0.3913, MCC: -0.1962, F1: 0.0667

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.57982 | val 1.12288
  Epoch 016 - train 0.52768 | val 1.25676
  Classification -> best τ=0.465 (val F1=0.0564)
  Directional -> Accuracy: 0.3659, MCC: 0.0000, F1: 0.5357

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.57933 | val 1.07195
  Epoch 016 - train 0.53292 | val 1.15620
  Classification -> best τ=0.445 (val F1=0.2840)
  Directional -> Accuracy: 0.5614, MCC: 0.0996, F1: 0.7059

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.57439 | val 1.55305
  Epoch 016 - train 0.51743 | val 1.77206
  Classification -> best τ=0.480 (val F1=0.2908)
  Directional -> Accuracy: 0.4828, MCC: 0.0000, F1: 0.6512

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.60759 | val 0.78259
  Epoch 018 - train 0.53635 | val 1.01346
  Classification -> best τ=0.505 (val F1=0.2844)
  Directional -> Accuracy: 0.5091, MCC: 0.0297, F1: 0.4706

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.57729 | val 0.69441
  Epoch 020 - train 0.47215 | val 1.07142
  Classification -> best τ=0.305 (val F1=0.2156)
  Directional -> Accuracy: 0.4483, MCC: -0.0976, F1: 0.3600

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.57803 | val 1.35322

[I 2026-02-24 22:24:41,780] Trial 1 finished with value: 0.22088503642029134 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 10, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.0, 'batch_size': 16, 'learning_rate': 0.0003819539964256457, 'weight_decay': 1.6863605692683179e-06, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 1.5271775550482418, 'early_stopping_min_delta': 0.002004648190708138}. Best is trial 1 with value: 0.22088503642029134.

  Epoch 016 - train 0.51990 | val 1.59663
  Classification -> best τ=0.550 (val F1=0.2024)
  Directional -> Accuracy: 0.4921, MCC: -0.0402, F1: 0.3333

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.22088503642029134
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 15
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.74190 | val 0.70398
  Epoch 020 - train 0.70744 | val 0.70613
  Classification -> best τ=0.520 (val F1=0.1137)
  Directional -> Accuracy: 0.5455, MCC: 0.2236, F1: 0.6535

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.67769 | val 0.69724
  Epoch 016 - train 0.68986 | val 0.69849
  Classification -> best τ=0.510 (val F1=0.0217)
  Directional -> Accuracy: 0.4565, MCC: 0.0245, F1: 0.1935

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 16). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.73126 | val 0.69283
  Epoch 016 - train 0.71068 | val 0.69668
  Classification -> best τ=0.525 (val F1=0.2477)
  Directional -> Accuracy: 0.4583, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.70582 | val 0.70291
  Epoch 016 - train 0.71711 | val 0.75367
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.71785 | val 0.68767
  Epoch 020 - train 0.68484 | val 0.66717
  Classification -> best τ=0.525 (val F1=0.4217)
  Directional -> Accuracy: 0.7308, MCC: 0.4702, F1: 0.7308

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.72097 | val 0.69346
  Epoch 016 - train 0.69318 | val 0.69540
  Classification -> best τ=0.495 (val F1=0.1132)
  Directional -> Accuracy: 0.4375, MCC: -0.1278, F1: 0.4906

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.72312 | val 0.69566
  Epoch 020 - train 0.71764 | val 0.69593
  Classification -> best τ=0.560 (val F1=0.1231)
  Directional -> Accuracy: 0.4000, MCC: -0.0928, F1: 0.5116

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 16). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.68026 | val 0.67684
  Epoch 016 - train 0.68837 | val 0.67924
  Classification -> best τ=0.485 (val F1=0.1429)
  Directional -> Accuracy: 0.5556, MCC: 0.0055, F1: 0.2308

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.70367 | val 0.68999
  Epoch 020 - train 0.68673 | val 0.68045
  Classification -> best τ=0.525 (val F1=0.3877)
  Directional -> Accuracy: 0.5122, MCC: -0.0226, F1: 0.3750

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 16). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 16). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.70814 | val 0.70007
  Epoch 016 - train 0.71387 | val 0.74371
  Classification -> best τ=0.490 (val F1=0.1807)
  Directional -> Accuracy: 0.4648, MCC: -0.0242, F1: 0.5250

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.70946 | val 0.72797
  Epoch 016 - train 0.74233 | val 0.75940
  Classification -> best τ=0.540 (val F1=0.1715)
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.6400

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.73283 | val 0.69148
  Epoch 020 - train 0.71707 | val 0.69509
  Classification -> best τ=0.500 (val F1=0.1532)
  Directional -> Accuracy: 0.3898, MCC: -0.2626, F1: 0.5135

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.72959 | val 0.67944
  Epoch 016 - train 0.69928 | val 0.68112
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.72414 | val 0.71598
  Epoch 016 - train 0.71932 | val 0.72142
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.72685 | val 0.71520
  Epoch 016 - train 0.72115 | val 0.73298
  Classification -> best τ=0.545 (val F1=0.2123)
  Directional -> Accuracy: 0.5660, MCC: 0.2096, F1: 0.1481

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.74198 | val 0.68465
  Epoch 020 - train 0.69102 | val 0.68496
  Classification -> best τ=0.525 (val F1=0.2723)
  Directional -> Accuracy: 0.5857, MCC: 0.1565, F1: 0.6420

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.74731 | val 0.71013
  Epoch 016 - train 0.72638 | val 0.74191
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6167, MCC: 0.0000, F1: 0.7629

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.71160 | val 0.69093
  Epoch 020 - train 0.71302 | val 0.72066
  Classification -> best τ=0.510 (val F1=0.1917)
  Directional -> Accuracy: 0.5263, MCC: 0.1014, F1: 0.5263

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.73514 | val 0.68892
  Epoch 020 - train 0.72063 | val 0.68113
  Classification -> best τ=0.425 (val F1=0.2523)
  Directional -> Accuracy: 0.5455, MCC: 0.0925, F1: 0.5833

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 16). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.70188 | val 0.69467
  Epoch 020 - train 0.69408 | val 0.68635
  Classification -> best τ=0.550 (val F1=0.2332)
  Directional -> Accuracy: 0.4605, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.69234 | val 0.70368
  Epoch 016 - train 0.71329 | val 0.71147
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.71061 | val 0.69101
  Epoch 020 - train 0.71929 | val 0.69656
  Classification -> best τ=0.505 (val F1=0.2008)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.73952 | val 0.69259
  Epoch 020 - train 0.69427 | val 0.68814
  Classification -> best τ=0.540 (val F1=0.2144)
  Directional -> Accuracy: 0.4483, MCC: -0.1486, F1: 0.5429

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.71237 | val 0.68960
  Epoch 020 - train 0.69036 | val 0.68962
  Classification -> best τ=0.495 (val F1=0.2319)
  Directional -> Accuracy: 0.5000, MCC: 0.0310, F1: 0.5823

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.68798 | val 0.68615
  Epoch 020 - train 0.69475 | val 0.66166
  Classification -> best τ=0.490 (val F1=0.5018)
  Directional -> Accuracy: 0.5714, MCC: 0.2385, F1: 0.4545

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.71855 | val 0.69019
  Epoch 016 - train 0.68034 | val 0.69041
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4255, MCC: 0.0000, F1: 0.5970

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.72506 | val 0.68350
  Epoch 016 - train 0.71038 | val 0.68347
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.73783 | val 0.69802
  Epoch 016 - train 0.71649 | val 0.69837
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5517, MCC: 0.0000, F1: 0.7111

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.69312 | val 0.69227
  Epoch 016 - train 0.70203 | val 0.69245
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.7077

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.72042 | val 0.69011
  Epoch 016 - train 0.75172 | val 0.69052
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.71606 | val 0.69587
  Epoch 016 - train 0.70325 | val 0.70305
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.71151 | val 0.69102
  Epoch 016 - train 0.70320 | val 0.69241
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.71212 | val 0.68627
  Epoch 020 - train 0.69387 | val 0.67038
  Classification -> best τ=0.515 (val F1=0.2771)
  Directional -> Accuracy: 0.4324, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.73975 | val 0.69724
  Epoch 016 - train 0.70893 | val 0.69758
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.72877 | val 0.70210
  Epoch 016 - train 0.69519 | val 0.70768
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.6364

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.69813 | val 0.68852
  Epoch 020 - train 0.68331 | val 0.68825
  Classification -> best τ=0.445 (val F1=0.3767)
  Directional -> Accuracy: 0.5672, MCC: 0.1757, F1: 0.5397

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.70788 | val 0.68967
  Epoch 016 - train 0.70651 | val 0.68991
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.69144 | val 0.68310
  Epoch 020 - train 0.70831 | val 0.68591
  Classification -> best τ=0.465 (val F1=0.1706)
  Directional -> Accuracy: 0.5263, MCC: 0.0358, F1: 0.4000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.69329 | val 0.67605
  Epoch 016 - train 0.71274 | val 0.67649
  Classification -> best τ=0.455 (val F1=0.2260)
  Directional -> Accuracy: 0.4894, MCC: 0.0958, F1: 0.4286

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 16). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.71138 | val 0.69288
  Epoch 016 - train 0.71941 | val 0.69427
  Classification -> best τ=0.500 (val F1=0.3333)
  Directional -> Accuracy: 0.3500, MCC: -0.1048, F1: 0.4800

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.71477 | val 0.69891
  Epoch 016 - train 0.67815 | val 0.69918
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.7000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 16). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.71519 | val 0.68952
  Epoch 020 - train 0.70464 | val 0.68408
  Classification -> best τ=0.500 (val F1=0.2734)
  Directional -> Accuracy: 0.5132, MCC: 0.0531, F1: 0.6606

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.69746 | val 0.69227
  Epoch 016 - train 0.71993 | val 0.69392
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.70515 | val 0.73513
  Epoch 016 - train 0.67325 | val 0.73769
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.75795 | val 0.70508
  Epoch 016 - train 0.72951 | val 0.70849
  Classification -> best τ=0.460 (val F1=0.0605)
  Directional -> Accuracy: 0.5750, MCC: 0.0812, F1: 0.4138

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.69367 | val 0.69550
  Epoch 020 - train 0.70726 | val 0.67723
  Classification -> best τ=0.495 (val F1=0.1359)
  Directional -> Accuracy: 0.5439, MCC: 0.0000, F1: 0.7045

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.69372 | val 0.69581
  Epoch 016 - train 0.70794 | val 0.70114
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.70294 | val 0.69561
  Epoch 016 - train 0.72872 | val 0.71268
  Classification -> best τ=0.505 (val F1=0.1474)
  Directional -> Accuracy: 0.5741, MCC: 0.1436, F1: 0.6230

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.68775 | val 0.71410
  Epoch 016 - train 0.68340 | val 0.74193
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.72946 | val 0.70001

[I 2026-02-24 22:26:03,341] Trial 2 finished with value: 0.12777470081113562 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 15, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.4, 'dropout': 0.8, 'batch_size': 64, 'learning_rate': 5.377674414547859e-05, 'weight_decay': 1.0421365946073962e-07, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 0.42602179276077995, 'early_stopping_min_delta': 0.0005098857686855785}. Best is trial 1 with value: 0.22088503642029134.

  Epoch 016 - train 0.77148 | val 0.74206
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4839, MCC: 0.0000, F1: 0.6522

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.12777470081113562
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: classification
Sequence length: 5
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.73010 | val 0.74852
  Epoch 020 - train 0.69305 | val 0.74832
  Epoch 021 - train 0.71033 | val 0.75534
  Classification -> best τ=0.510 (val F1=0.1903)
  Directional -> Accuracy: 0.5570, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.68219 | val 0.68844
  Epoch 020 - train 0.71740 | val 0.69085
  Epoch 027 - train 0.71264 | val 0.69096
  Classification -> best τ=0.425 (val F1=0.1264)
  Directional -> Accuracy: 0.5833, MCC: 0.1187, F1: 0.6875

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 6). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.72222 | val 0.65999
  Epoch 020 - train 0.69602 | val 0.65696
  Epoch 030 - train 0.70290 | val 0.65584
  Epoch 040 - train 0.72300 | val 0.65502
  Classification -> best τ=0.475 (val F1=0.4203)
  Directional -> Accuracy: 0.5800, MCC: 0.1391, F1: 0.6769

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.72963 | val 0.71403
  Epoch 020 - train 0.70417 | val 0.70030
  Epoch 021 - train 0.70566 | val 0.70228
  Classification -> best τ=0.530 (val F1=0.1396)
  Directional -> Accuracy: 0.5195, MCC: -0.0962, F1: 0.6783

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.73291 | val 0.66409
  Epoch 020 - train 0.73085 | val 0.65318
  Epoch 030 - train 0.67597 | val 0.64870
  Epoch 040 - train 0.70708 | val 0.64238
  Epoch 050 - train 0.72124 | val 0.63934
  Classification -> best τ=0.605 (val F1=0.3984)
  Directional -> Accuracy: 0.6415, MCC: 0.3018, F1: 0.6122

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.72198 | val 0.69377
  Epoch 020 - train 0.76581 | val 0.69488
  Epoch 021 - train 0.72061 | val 0.69538
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4762, MCC: 0.0000, F1: 0.6452

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.70537 | val 0.70935
  Epoch 020 - train 0.73581 | val 0.70424
  Epoch 021 - train 0.73189 | val 0.70444
  Classification -> best τ=0.470 (val F1=0.0249)
  Directional -> Accuracy: 0.4306, MCC: -0.0856, F1: 0.4810

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 6). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.70744 | val 0.93033
  Epoch 020 - train 0.69983 | val 1.04361
  Epoch 021 - train 0.73741 | val 1.02240
  Classification -> best τ=0.545 (val F1=0.1581)
  Directional -> Accuracy: 0.4468, MCC: 0.1737, F1: 0.5938

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.73411 | val 0.70906
  Epoch 020 - train 0.69291 | val 0.71055
  Epoch 021 - train 0.72168 | val 0.70910
  Classification -> best τ=0.475 (val F1=0.2060)
  Directional -> Accuracy: 0.4419, MCC: -0.0664, F1: 0.4545

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for proper time series validation for BRK-A. Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for proper time series validation for BSAC. Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.71390 | val 0.69401
  Epoch 020 - train 0.67296 | val 0.69713
  Epoch 021 - train 0.70939 | val 0.69885
  Classification -> best τ=0.530 (val F1=0.0903)
  Directional -> Accuracy: 0.4306, MCC: 0.0000, F1: 0.6019

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.71982 | val 0.68557
  Epoch 020 - train 0.69656 | val 0.68385
  Epoch 024 - train 0.70763 | val 0.68331
  Classification -> best τ=0.455 (val F1=0.3392)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.69667 | val 0.68141
  Epoch 020 - train 0.70738 | val 0.68153
  Epoch 025 - train 0.73554 | val 0.68452
  Classification -> best τ=0.525 (val F1=0.3675)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0625

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.66045 | val 0.67552
  Epoch 020 - train 0.67526 | val 0.67669
  Epoch 025 - train 0.69224 | val 0.67714
  Classification -> best τ=0.515 (val F1=0.1455)
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.6364

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.71925 | val 0.74888
  Epoch 020 - train 0.71105 | val 0.75081
  Epoch 021 - train 0.72167 | val 0.74796
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4921, MCC: 0.0000, F1: 0.6596

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.71530 | val 0.70201
  Epoch 020 - train 0.70829 | val 0.69483
  Epoch 021 - train 0.70848 | val 0.69902
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4909, MCC: 0.0000, F1: 0.6585

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.70594 | val 0.69481
  Epoch 020 - train 0.70872 | val 0.69654
  Epoch 021 - train 0.70678 | val 0.69728
  Classification -> best τ=0.505 (val F1=0.1770)
  Directional -> Accuracy: 0.5139, MCC: -0.0104, F1: 0.6154

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.70721 | val 0.76368
  Epoch 020 - train 0.68944 | val 0.77593
  Epoch 021 - train 0.70799 | val 0.77809
  Classification -> best τ=0.510 (val F1=0.0778)
  Directional -> Accuracy: 0.4032, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.72249 | val 0.71287
  Epoch 020 - train 0.71576 | val 0.70856
  Epoch 021 - train 0.70121 | val 0.70760
  Classification -> best τ=0.525 (val F1=0.0673)
  Directional -> Accuracy: 0.4103, MCC: -0.1159, F1: 0.3611

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.72645 | val 0.70178
  Epoch 020 - train 0.71080 | val 0.69768
  Epoch 021 - train 0.73664 | val 0.69842
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5882, MCC: 0.0000, F1: 0.7407

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 6). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.71540 | val 0.68720
  Epoch 020 - train 0.70724 | val 0.68737
  Epoch 021 - train 0.70105 | val 0.68859
  Classification -> best τ=0.485 (val F1=0.1166)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.72105 | val 0.68149
  Epoch 020 - train 0.72528 | val 0.68031
  Epoch 026 - train 0.70033 | val 0.68006
  Classification -> best τ=0.510 (val F1=0.2850)
  Directional -> Accuracy: 0.6000, MCC: 0.0816, F1: 0.7143

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.72899 | val 0.70635
  Epoch 020 - train 0.71018 | val 0.70320
  Epoch 021 - train 0.71769 | val 0.70441
  Classification -> best τ=0.505 (val F1=0.0328)
  Directional -> Accuracy: 0.4853, MCC: -0.0311, F1: 0.5570

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.72171 | val 0.71070
  Epoch 020 - train 0.70408 | val 0.71026
  Epoch 021 - train 0.71848 | val 0.71055
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5833, MCC: 0.0000, F1: 0.7368

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.69152 | val 0.76070
  Epoch 020 - train 0.72087 | val 0.76926
  Epoch 021 - train 0.69119 | val 0.77584
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4853, MCC: 0.0000, F1: 0.6535

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.74735 | val 0.70951
  Epoch 020 - train 0.69744 | val 0.69954
  Epoch 021 - train 0.72221 | val 0.70008
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5517, MCC: 0.0000, F1: 0.7111

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.68622 | val 0.72225
  Epoch 020 - train 0.72321 | val 0.73573
  Epoch 021 - train 0.71605 | val 0.73810
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.5714

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.70341 | val 0.70158
  Epoch 020 - train 0.71548 | val 0.70303
  Epoch 021 - train 0.71273 | val 0.70093
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6000, MCC: 0.0000, F1: 0.7500

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.71431 | val 0.68691
  Epoch 020 - train 0.72384 | val 0.68926
  Epoch 021 - train 0.73581 | val 0.68945
  Classification -> best τ=0.495 (val F1=0.2699)
  Directional -> Accuracy: 0.4068, MCC: -0.2632, F1: 0.5333

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.77809 | val 0.69497
  Epoch 020 - train 0.76947 | val 0.69340
  Epoch 021 - train 0.69824 | val 0.69255
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.72674 | val 0.72314
  Epoch 020 - train 0.77362 | val 0.72560
  Epoch 021 - train 0.71778 | val 0.72663
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.71138 | val 0.72630
  Epoch 020 - train 0.70845 | val 0.72618
  Epoch 021 - train 0.74841 | val 0.72186
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5435, MCC: 0.0000, F1: 0.7042

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.70245 | val 0.72138
  Epoch 020 - train 0.69757 | val 0.71669
  Epoch 021 - train 0.73589 | val 0.71772
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5094, MCC: 0.0000, F1: 0.6750

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.73313 | val 0.69170
  Epoch 020 - train 0.71493 | val 0.68824
  Epoch 030 - train 0.70614 | val 0.67838
  Epoch 040 - train 0.70458 | val 0.67168
  Epoch 050 - train 0.70831 | val 0.66808
  Classification -> best τ=0.430 (val F1=0.2849)
  Directional -> Accuracy: 0.5467, MCC: 0.1701, F1: 0.4516

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.64643 | val 0.69455
  Epoch 020 - train 0.70796 | val 0.70534
  Epoch 021 - train 0.71903 | val 0.70887
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4878, MCC: 0.0000, F1: 0.6557

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.69681 | val 0.69291
  Epoch 020 - train 0.72515 | val 0.69280
  Epoch 021 - train 0.72745 | val 0.69131
  Classification -> best τ=0.465 (val F1=0.1453)
  Directional -> Accuracy: 0.3478, MCC: -0.3055, F1: 0.3182

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.73219 | val 0.67297
  Epoch 020 - train 0.71891 | val 0.66948
  Epoch 030 - train 0.74698 | val 0.66618
  Epoch 040 - train 0.71375 | val 0.66276
  Epoch 045 - train 0.70973 | val 0.66164
  Classification -> best τ=0.435 (val F1=0.3607)
  Directional -> Accuracy: 0.4928, MCC: 0.2380, F1: 0.2222

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.73027 | val 0.68662
  Epoch 020 - train 0.71825 | val 0.68569
  Epoch 030 - train 0.70507 | val 0.68549
  Epoch 031 - train 0.67691 | val 0.68523
  Classification -> best τ=0.560 (val F1=0.2564)
  Directional -> Accuracy: 0.5111, MCC: 0.0629, F1: 0.2143

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.71535 | val 0.68612
  Epoch 020 - train 0.71325 | val 0.68841
  Epoch 024 - train 0.71718 | val 0.68762
  Classification -> best τ=0.505 (val F1=0.1613)
  Directional -> Accuracy: 0.5932, MCC: 0.1843, F1: 0.5714

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.74777 | val 0.76658
  Epoch 020 - train 0.73686 | val 0.78173
  Epoch 021 - train 0.74403 | val 0.77895
  Classification -> best τ=0.495 (val F1=0.1167)
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.7595

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 6). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.69874 | val 0.68965
  Epoch 020 - train 0.71329 | val 0.68586
  Epoch 030 - train 0.71142 | val 0.68600
  Epoch 033 - train 0.72042 | val 0.68748
  Classification -> best τ=0.545 (val F1=0.4478)
  Directional -> Accuracy: 0.4048, MCC: 0.1961, F1: 0.5283

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.71836 | val 0.69154
  Epoch 020 - train 0.74558 | val 0.69604
  Epoch 021 - train 0.72070 | val 0.69278
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5122, MCC: 0.0000, F1: 0.6774

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 6). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.72122 | val 0.69982
  Epoch 020 - train 0.72596 | val 0.70161
  Epoch 021 - train 0.73315 | val 0.70304
  Classification -> best τ=0.500 (val F1=0.0479)
  Directional -> Accuracy: 0.4286, MCC: -0.1522, F1: 0.5000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.72777 | val 0.68650
  Epoch 020 - train 0.70026 | val 0.69304
  Epoch 026 - train 0.76918 | val 0.69053
  Classification -> best τ=0.510 (val F1=0.3184)
  Directional -> Accuracy: 0.5102, MCC: 0.0000, F1: 0.0000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.73032 | val 0.66574
  Epoch 020 - train 0.77776 | val 0.66152
  Epoch 030 - train 0.76735 | val 0.65815
  Epoch 033 - train 0.75079 | val 0.66088
  Classification -> best τ=0.470 (val F1=0.3006)
  Directional -> Accuracy: 0.4894, MCC: -0.1092, F1: 0.6129

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.73592 | val 0.71185
  Epoch 020 - train 0.72003 | val 0.71769
  Epoch 021 - train 0.74234 | val 0.72096
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3571, MCC: 0.0000, F1: 0.5263

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.72972 | val 0.71200

[I 2026-02-24 22:27:12,869] Trial 3 finished with value: 0.13499341645369423 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 5, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.8, 'batch_size': 16, 'learning_rate': 7.304295618514388e-06, 'weight_decay': 2.1453308406400938e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 50, 'huber_delta': 0.11431975128252349, 'early_stopping_min_delta': 0.005952380778700501}. Best is trial 1 with value: 0.22088503642029134.

  Epoch 025 - train 0.71801 | val 0.69325
  Classification -> best τ=0.515 (val F1=0.3016)
  Directional -> Accuracy: 0.4444, MCC: -0.1077, F1: 0.5783

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.13499341645369423
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 10
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.69314 | val 0.67410
  Epoch 020 - train 0.68248 | val 0.68844
  Epoch 024 - train 0.68393 | val 0.68758
  Classification -> best τ=0.505 (val F1=0.1997)
  Directional -> Accuracy: 0.5513, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.66713 | val 0.68787
  Epoch 020 - train 0.65240 | val 0.68943
  Epoch 030 - train 0.65469 | val 0.68887
  Classification -> best τ=0.440 (val F1=0.2318)
  Directional -> Accuracy: 0.6809, MCC: 0.4257, F1: 0.7761

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 11). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.68170 | val 0.69918
  Epoch 020 - train 0.67208 | val 0.71377
  Epoch 021 - train 0.66819 | val 0.71404
  Classification -> best τ=0.495 (val F1=0.3043)
  Directional -> Accuracy: 0.5714, MCC: 0.1811, F1: 0.4878

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.66506 | val 0.77927
  Epoch 020 - train 0.66371 | val 0.77960
  Epoch 021 - train 0.67716 | val 0.78309
  Classification -> best τ=0.455 (val F1=0.1039)
  Directional -> Accuracy: 0.5395, MCC: 0.0000, F1: 0.7009

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.67451 | val 0.67980
  Epoch 020 - train 0.66176 | val 0.70901
  Epoch 027 - train 0.65113 | val 0.71353
  Classification -> best τ=0.500 (val F1=0.3267)
  Directional -> Accuracy: 0.5577, MCC: 0.0949, F1: 0.6349

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.65497 | val 0.73817
  Epoch 020 - train 0.63743 | val 0.83055
  Epoch 021 - train 0.64509 | val 0.83619
  Classification -> best τ=0.490 (val F1=0.1956)
  Directional -> Accuracy: 0.4898, MCC: -0.0061, F1: 0.1379

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.68212 | val 0.68471
  Epoch 020 - train 0.67609 | val 0.68957
  Epoch 024 - train 0.67400 | val 0.69020
  Classification -> best τ=0.460 (val F1=0.3033)
  Directional -> Accuracy: 0.4085, MCC: 0.0000, F1: 0.5800

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 11). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.66221 | val 0.84602
  Epoch 020 - train 0.65594 | val 0.99543
  Epoch 021 - train 0.64976 | val 1.00653
  Classification -> best τ=0.540 (val F1=0.1065)
  Directional -> Accuracy: 0.6087, MCC: 0.1699, F1: 0.4706

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.68386 | val 0.73227
  Epoch 020 - train 0.68160 | val 0.74145
  Epoch 021 - train 0.68164 | val 0.74305
  Classification -> best τ=0.545 (val F1=0.2360)
  Directional -> Accuracy: 0.4524, MCC: -0.1220, F1: 0.3429

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for proper time series validation for BRK-A. Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for proper time series validation for BSAC. Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.65514 | val 1.09053
  Epoch 020 - train 0.65576 | val 1.15419
  Epoch 021 - train 0.65361 | val 1.15059
  Classification -> best τ=0.480 (val F1=0.2542)
  Directional -> Accuracy: 0.4366, MCC: 0.0000, F1: 0.6078

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.67716 | val 0.72657
  Epoch 020 - train 0.66547 | val 0.75597
  Epoch 021 - train 0.67262 | val 0.76051
  Classification -> best τ=0.465 (val F1=0.0266)
  Directional -> Accuracy: 0.5385, MCC: 0.0561, F1: 0.4286

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.68150 | val 0.74604
  Epoch 020 - train 0.66138 | val 0.76023
  Epoch 021 - train 0.67810 | val 0.75932
  Classification -> best τ=0.530 (val F1=0.1764)
  Directional -> Accuracy: 0.5424, MCC: 0.1179, F1: 0.6747

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.64586 | val 0.79120
  Epoch 020 - train 0.62681 | val 0.84146
  Epoch 021 - train 0.63757 | val 0.85044
  Classification -> best τ=0.530 (val F1=0.0295)
  Directional -> Accuracy: 0.5909, MCC: 0.1693, F1: 0.3077

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.68807 | val 0.62130
  Epoch 020 - train 0.67898 | val 0.62237
  Epoch 030 - train 0.66952 | val 0.62424
  Classification -> best τ=0.375 (val F1=0.3241)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.5974

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.66323 | val 0.97919
  Epoch 020 - train 0.66079 | val 1.10744
  Epoch 021 - train 0.65473 | val 1.12203
  Classification -> best τ=0.500 (val F1=0.0480)
  Directional -> Accuracy: 0.4630, MCC: -0.0771, F1: 0.4314

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.66082 | val 0.69912
  Epoch 020 - train 0.65107 | val 0.71250
  Epoch 021 - train 0.65849 | val 0.71305
  Classification -> best τ=0.520 (val F1=0.2274)
  Directional -> Accuracy: 0.5352, MCC: 0.0000, F1: 0.6972

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.66506 | val 0.89479
  Epoch 020 - train 0.67251 | val 0.97058
  Epoch 021 - train 0.65868 | val 0.97529
  Classification -> best τ=0.505 (val F1=0.1938)
  Directional -> Accuracy: 0.3934, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.67865 | val 0.82506
  Epoch 020 - train 0.67674 | val 0.90453
  Epoch 021 - train 0.67253 | val 0.91058
  Classification -> best τ=0.540 (val F1=0.1375)
  Directional -> Accuracy: 0.4545, MCC: -0.0385, F1: 0.4474

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.66675 | val 0.69836
  Epoch 020 - train 0.66047 | val 0.67293
  Epoch 030 - train 0.65799 | val 0.66881
  Classification -> best τ=0.390 (val F1=0.2807)
  Directional -> Accuracy: 0.4776, MCC: 0.1598, F1: 0.2222

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 11). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.65826 | val 0.69049
  Epoch 020 - train 0.65315 | val 0.69075
  Epoch 023 - train 0.64245 | val 0.69119
  Classification -> best τ=0.415 (val F1=0.2137)
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.67745 | val 0.69859
  Epoch 020 - train 0.66893 | val 0.72604
  Epoch 024 - train 0.66424 | val 0.73050
  Classification -> best τ=0.520 (val F1=0.2120)
  Directional -> Accuracy: 0.4286, MCC: -0.2294, F1: 0.5484

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.67744 | val 0.74792
  Epoch 020 - train 0.67454 | val 0.76672
  Epoch 021 - train 0.67429 | val 0.76651
  Classification -> best τ=0.515 (val F1=0.0441)
  Directional -> Accuracy: 0.5970, MCC: 0.2045, F1: 0.5424

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.66708 | val 0.77127
  Epoch 020 - train 0.65442 | val 0.77505
  Epoch 021 - train 0.66142 | val 0.77432
  Classification -> best τ=0.540 (val F1=0.1930)
  Directional -> Accuracy: 0.5085, MCC: 0.2085, F1: 0.2927

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.66985 | val 0.81269
  Epoch 020 - train 0.65732 | val 0.83358
  Epoch 021 - train 0.65829 | val 0.83296
  Classification -> best τ=0.480 (val F1=0.1796)
  Directional -> Accuracy: 0.5373, MCC: 0.0673, F1: 0.4746

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.68150 | val 0.66699
  Epoch 020 - train 0.66625 | val 0.64832
  Epoch 030 - train 0.65229 | val 0.64052
  Classification -> best τ=0.460 (val F1=0.4735)
  Directional -> Accuracy: 0.5614, MCC: 0.2071, F1: 0.4681

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.68019 | val 0.69011
  Epoch 020 - train 0.67043 | val 0.70937
  Epoch 021 - train 0.66543 | val 0.70853
  Classification -> best τ=0.510 (val F1=0.3103)
  Directional -> Accuracy: 0.3750, MCC: -0.2182, F1: 0.4000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.67875 | val 0.83931
  Epoch 020 - train 0.66708 | val 0.88950
  Epoch 021 - train 0.67646 | val 0.89254
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.7429

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.66809 | val 0.72293
  Epoch 020 - train 0.65948 | val 0.72488
  Epoch 021 - train 0.67095 | val 0.72518
  Classification -> best τ=0.525 (val F1=0.2750)
  Directional -> Accuracy: 0.5345, MCC: 0.1708, F1: 0.3721

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.68321 | val 0.70810
  Epoch 020 - train 0.68131 | val 0.70139
  Epoch 021 - train 0.67748 | val 0.70169
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.68263 | val 0.68763
  Epoch 020 - train 0.67505 | val 0.70359
  Epoch 021 - train 0.67488 | val 0.70377
  Classification -> best τ=0.495 (val F1=0.3162)
  Directional -> Accuracy: 0.4667, MCC: -0.0786, F1: 0.1429

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.69128 | val 0.65158
  Epoch 020 - train 0.65869 | val 0.66697
  Epoch 028 - train 0.65921 | val 0.67564
  Classification -> best τ=0.595 (val F1=0.1967)
  Directional -> Accuracy: 0.5333, MCC: 0.0000, F1: 0.6957

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.67106 | val 0.68296
  Epoch 020 - train 0.64985 | val 0.67614
  Epoch 030 - train 0.65757 | val 0.67567
  Classification -> best τ=0.460 (val F1=0.1678)
  Directional -> Accuracy: 0.5192, MCC: 0.0000, F1: 0.6835

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.67190 | val 0.67680
  Epoch 020 - train 0.66706 | val 0.65835
  Epoch 030 - train 0.66419 | val 0.65054
  Classification -> best τ=0.510 (val F1=0.2849)
  Directional -> Accuracy: 0.4865, MCC: 0.1594, F1: 0.2083

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.66961 | val 0.68500
  Epoch 020 - train 0.65407 | val 0.73101
  Epoch 027 - train 0.65168 | val 0.74071
  Classification -> best τ=0.525 (val F1=0.3518)
  Directional -> Accuracy: 0.4750, MCC: 0.0000, F1: 0.6441

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.65817 | val 0.89146
  Epoch 020 - train 0.66076 | val 0.97148
  Epoch 021 - train 0.65476 | val 0.97772
  Classification -> best τ=0.465 (val F1=0.0577)
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.6364

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.66574 | val 0.66775
  Epoch 020 - train 0.65676 | val 0.67795
  Epoch 027 - train 0.65919 | val 0.67986
  Classification -> best τ=0.370 (val F1=0.2989)
  Directional -> Accuracy: 0.6176, MCC: 0.2118, F1: 0.6750

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.67328 | val 0.70378
  Epoch 020 - train 0.67933 | val 0.70558
  Epoch 021 - train 0.67506 | val 0.70558
  Classification -> best τ=0.535 (val F1=0.2351)
  Directional -> Accuracy: 0.6364, MCC: 0.2928, F1: 0.5556

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.65708 | val 0.71162
  Epoch 020 - train 0.63567 | val 0.72595
  Epoch 021 - train 0.63088 | val 0.72698
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4655, MCC: 0.0000, F1: 0.6353

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.67102 | val 0.88350
  Epoch 020 - train 0.65872 | val 0.93381
  Epoch 021 - train 0.65871 | val 0.94333
  Classification -> best τ=0.485 (val F1=0.3312)
  Directional -> Accuracy: 0.5833, MCC: 0.0000, F1: 0.7143

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 11). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.70365 | val 0.73290
  Epoch 020 - train 0.68550 | val 0.72713
  Epoch 021 - train 0.69008 | val 0.72439
  Classification -> best τ=0.565 (val F1=0.2059)
  Directional -> Accuracy: 0.4878, MCC: -0.2039, F1: 0.1600

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.66577 | val 0.72960
  Epoch 020 - train 0.67764 | val 0.75214
  Epoch 021 - train 0.65458 | val 0.74773
  Classification -> best τ=0.500 (val F1=0.2988)
  Directional -> Accuracy: 0.5250, MCC: 0.1502, F1: 0.2400

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 11). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.67376 | val 0.69690
  Epoch 020 - train 0.66284 | val 0.70198
  Epoch 030 - train 0.65287 | val 0.71345
  Classification -> best τ=0.445 (val F1=0.2354)
  Directional -> Accuracy: 0.5065, MCC: 0.0000, F1: 0.6724

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.70552 | val 0.71983
  Epoch 020 - train 0.70462 | val 0.72108
  Epoch 021 - train 0.68970 | val 0.72274
  Classification -> best τ=0.415 (val F1=0.1435)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.63461 | val 0.82953
  Epoch 020 - train 0.63390 | val 0.91557
  Epoch 021 - train 0.62698 | val 0.91798
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.66279 | val 0.92876
  Epoch 020 - train 0.65053 | val 1.04146
  Epoch 021 - train 0.64653 | val 1.04211
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3659, MCC: 0.0000, F1: 0.5357

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.67157 | val 0.88609
  Epoch 020 - train 0.67118 | val 0.90878
  Epoch 021 - train 0.66096 | val 0.89931
  Classification -> best τ=0.495 (val F1=0.2840)
  Directional -> Accuracy: 0.5789, MCC: 0.2121, F1: 0.5000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.66081 | val 0.85643
  Epoch 020 - train 0.66615 | val 0.89593
  Epoch 021 - train 0.65676 | val 0.90148
  Classification -> best τ=0.560 (val F1=0.3050)

[I 2026-02-24 22:28:20,838] Trial 4 finished with value: 0.18878668393498577 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 10, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.1, 'batch_size': 32, 'learning_rate': 5.040561341164236e-05, 'weight_decay': 1.1020963624613911e-07, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.88126071845123, 'early_stopping_min_delta': 0.0051078384108595035}. Best is trial 1 with value: 0.22088503642029134.

  Epoch 020 - train 0.67374 | val 0.71540
  Epoch 021 - train 0.67376 | val 0.71857
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4762, MCC: 0.0000, F1: 0.6452

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.18878668393498577
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: classification
Sequence length: 10
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.72543 | val 0.69033
  Epoch 020 - train 0.71729 | val 0.67262
  Epoch 030 - train 0.70846 | val 0.67117
  Classification -> best τ=0.480 (val F1=0.1403)
  Directional -> Accuracy: 0.5897, MCC: 0.1515, F1: 0.4483

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.71156 | val 0.71275
  Epoch 020 - train 0.70040 | val 0.73551
  Epoch 021 - train 0.70459 | val 0.73926
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5532, MCC: 0.0000, F1: 0.7123

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 11). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.72404 | val 0.69646
  Epoch 020 - train 0.70542 | val 0.69382
  Epoch 030 - train 0.68192 | val 0.69064
  Classification -> best τ=0.475 (val F1=0.3783)
  Directional -> Accuracy: 0.4898, MCC: -0.0704, F1: 0.6154

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.71077 | val 0.71311
  Epoch 020 - train 0.70038 | val 0.94370
  Epoch 021 - train 0.71236 | val 0.95028
  Classification -> best τ=0.510 (val F1=0.0591)
  Directional -> Accuracy: 0.5000, MCC: 0.0340, F1: 0.4062

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.71738 | val 0.70365
  Epoch 020 - train 0.72100 | val 0.71403
  Epoch 021 - train 0.72628 | val 0.71405
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.7000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.70093 | val 0.68955
  Epoch 020 - train 0.70452 | val 0.70315
  Epoch 021 - train 0.69675 | val 0.70790
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5102, MCC: 0.0000, F1: 0.6757

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.71474 | val 0.68707
  Epoch 020 - train 0.73276 | val 0.69276
  Epoch 030 - train 0.70681 | val 0.69053
  Classification -> best τ=0.455 (val F1=0.2342)
  Directional -> Accuracy: 0.4085, MCC: 0.0000, F1: 0.5800

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 11). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.74958 | val 0.65659
  Epoch 020 - train 0.74471 | val 0.64673
  Epoch 030 - train 0.75210 | val 0.63175
  Classification -> best τ=0.405 (val F1=0.2092)
  Directional -> Accuracy: 0.5217, MCC: -0.0020, F1: 0.3889

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.72028 | val 0.69390
  Epoch 020 - train 0.67936 | val 0.69589
  Epoch 021 - train 0.71436 | val 0.69635
  Classification -> best τ=0.465 (val F1=0.0195)
  Directional -> Accuracy: 0.6190, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for proper time series validation for BRK-A. Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for proper time series validation for BSAC. Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.71843 | val 0.69999
  Epoch 020 - train 0.69899 | val 0.71119
  Epoch 021 - train 0.70061 | val 0.71205
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4366, MCC: 0.0000, F1: 0.6078

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.70415 | val 0.68374
  Epoch 020 - train 0.72205 | val 0.67301
  Epoch 030 - train 0.70059 | val 0.67310
  Classification -> best τ=0.435 (val F1=0.2176)
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.68028 | val 0.70487
  Epoch 020 - train 0.72629 | val 0.70931
  Epoch 021 - train 0.72304 | val 0.70973
  Classification -> best τ=0.465 (val F1=0.0152)
  Directional -> Accuracy: 0.4237, MCC: -0.1697, F1: 0.5143

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.70179 | val 0.70563
  Epoch 020 - train 0.70949 | val 0.74863
  Epoch 021 - train 0.70184 | val 0.75828
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.73655 | val 0.71075
  Epoch 020 - train 0.73534 | val 0.73347
  Epoch 021 - train 0.71249 | val 0.73545
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.70235 | val 0.71112
  Epoch 020 - train 0.69598 | val 0.71908
  Epoch 021 - train 0.70008 | val 0.71909
  Classification -> best τ=0.545 (val F1=0.1181)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.72276 | val 0.68680
  Epoch 020 - train 0.72049 | val 0.68683
  Epoch 021 - train 0.68018 | val 0.68693
  Classification -> best τ=0.525 (val F1=0.0390)
  Directional -> Accuracy: 0.4366, MCC: -0.1070, F1: 0.3103

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.73810 | val 0.69588
  Epoch 020 - train 0.69138 | val 0.70352
  Epoch 030 - train 0.69113 | val 0.73422
  Classification -> best τ=0.440 (val F1=0.2481)
  Directional -> Accuracy: 0.4098, MCC: -0.2766, F1: 0.5385

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.70332 | val 0.69505
  Epoch 020 - train 0.69793 | val 0.72369
  Epoch 021 - train 0.70900 | val 0.72505
  Classification -> best τ=0.490 (val F1=0.0924)
  Directional -> Accuracy: 0.6234, MCC: 0.1685, F1: 0.7184

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.71762 | val 0.69656
  Epoch 020 - train 0.70494 | val 0.69101
  Epoch 030 - train 0.70142 | val 0.68980
  Classification -> best τ=0.485 (val F1=0.1817)
  Directional -> Accuracy: 0.4478, MCC: -0.1811, F1: 0.5647

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 11). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.71462 | val 0.69955
  Epoch 020 - train 0.69684 | val 0.72214
  Epoch 021 - train 0.71404 | val 0.72231
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.74179 | val 0.69561
  Epoch 020 - train 0.72096 | val 0.69548
  Epoch 030 - train 0.70687 | val 0.70900
  Classification -> best τ=0.510 (val F1=0.1091)
  Directional -> Accuracy: 0.4694, MCC: -0.0921, F1: 0.5517

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.69241 | val 0.69350
  Epoch 020 - train 0.72014 | val 0.69118
  Epoch 030 - train 0.70068 | val 0.69094
  Classification -> best τ=0.475 (val F1=0.2070)
  Directional -> Accuracy: 0.5075, MCC: 0.0038, F1: 0.6598

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.71103 | val 0.69727
  Epoch 020 - train 0.69663 | val 0.70836
  Epoch 021 - train 0.69333 | val 0.70844
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5763, MCC: 0.0000, F1: 0.7312

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.73120 | val 0.69771
  Epoch 020 - train 0.70921 | val 0.73419
  Epoch 021 - train 0.72247 | val 0.73287
  Classification -> best τ=0.475 (val F1=0.0782)
  Directional -> Accuracy: 0.5522, MCC: 0.1116, F1: 0.5714

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.74089 | val 0.69351
  Epoch 020 - train 0.69993 | val 0.70416
  Epoch 021 - train 0.73617 | val 0.70564
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.73596 | val 0.71312
  Epoch 020 - train 0.74966 | val 0.71442
  Epoch 021 - train 0.74356 | val 0.71465
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4167, MCC: 0.0000, F1: 0.5882

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.73333 | val 0.69263
  Epoch 020 - train 0.71623 | val 0.69882
  Epoch 021 - train 0.71842 | val 0.70011
  Classification -> best τ=0.505 (val F1=0.1216)
  Directional -> Accuracy: 0.4318, MCC: -0.1856, F1: 0.5283

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.71221 | val 0.69718
  Epoch 020 - train 0.70947 | val 0.71651
  Epoch 021 - train 0.70817 | val 0.71812
  Classification -> best τ=0.490 (val F1=0.0224)
  Directional -> Accuracy: 0.4310, MCC: -0.2592, F1: 0.5823

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.73646 | val 0.70602
  Epoch 020 - train 0.73348 | val 0.71288
  Epoch 021 - train 0.77120 | val 0.71419
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.67446 | val 0.70764
  Epoch 020 - train 0.69761 | val 0.70897
  Epoch 021 - train 0.68620 | val 0.70900
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.73161 | val 0.71333
  Epoch 020 - train 0.76278 | val 0.72255
  Epoch 021 - train 0.73014 | val 0.72450
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5333, MCC: 0.0000, F1: 0.6957

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.69836 | val 0.68687
  Epoch 020 - train 0.71056 | val 0.67711
  Epoch 030 - train 0.69445 | val 0.67544
  Classification -> best τ=0.465 (val F1=0.2700)
  Directional -> Accuracy: 0.5192, MCC: 0.0000, F1: 0.6835

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.71223 | val 0.68445
  Epoch 020 - train 0.68898 | val 0.69005
  Epoch 028 - train 0.69257 | val 0.68726
  Classification -> best τ=0.440 (val F1=0.1445)
  Directional -> Accuracy: 0.5811, MCC: 0.1883, F1: 0.5753

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.71972 | val 0.69528
  Epoch 020 - train 0.67726 | val 0.69530
  Epoch 021 - train 0.72207 | val 0.69531
  Classification -> best τ=0.490 (val F1=0.2774)
  Directional -> Accuracy: 0.5250, MCC: 0.0613, F1: 0.5581

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.68849 | val 0.69480
  Epoch 020 - train 0.70491 | val 0.70267
  Epoch 021 - train 0.69616 | val 0.70469
  Classification -> best τ=0.505 (val F1=0.0238)
  Directional -> Accuracy: 0.5333, MCC: 0.1175, F1: 0.6182

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.74275 | val 0.70628
  Epoch 020 - train 0.70908 | val 0.70238
  Epoch 021 - train 0.73871 | val 0.70189
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5735, MCC: 0.0000, F1: 0.7290

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.76844 | val 0.70085
  Epoch 020 - train 0.73690 | val 0.69951
  Epoch 030 - train 0.72392 | val 0.69441
  Classification -> best τ=0.540 (val F1=0.1787)
  Directional -> Accuracy: 0.5909, MCC: 0.2169, F1: 0.6786

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.72368 | val 0.68770
  Epoch 020 - train 0.69517 | val 0.69412
  Epoch 021 - train 0.68794 | val 0.69534
  Classification -> best τ=0.485 (val F1=0.1050)
  Directional -> Accuracy: 0.4655, MCC: 0.0000, F1: 0.6353

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.71394 | val 0.67956
  Epoch 020 - train 0.70610 | val 0.67218
  Epoch 030 - train 0.68682 | val 0.68583
  Classification -> best τ=0.470 (val F1=0.3113)
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 11). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.71440 | val 0.68433
  Epoch 020 - train 0.72229 | val 0.68187
  Epoch 030 - train 0.73800 | val 0.67446
  Classification -> best τ=0.400 (val F1=0.2503)
  Directional -> Accuracy: 0.3415, MCC: 0.0000, F1: 0.5091

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.73746 | val 0.70931
  Epoch 020 - train 0.73320 | val 0.71306
  Epoch 021 - train 0.74206 | val 0.71377
  Classification -> best τ=0.535 (val F1=0.2390)
  Directional -> Accuracy: 0.5750, MCC: 0.1857, F1: 0.4848

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 11). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.69537 | val 0.69464
  Epoch 020 - train 0.71414 | val 0.69259
  Epoch 030 - train 0.69180 | val 0.69191
  Classification -> best τ=0.470 (val F1=0.1472)
  Directional -> Accuracy: 0.5325, MCC: 0.0642, F1: 0.5500

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.70013 | val 0.69036
  Epoch 020 - train 0.71783 | val 0.68451
  Epoch 030 - train 0.68926 | val 0.66971
  Classification -> best τ=0.510 (val F1=0.5476)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.72775 | val 0.67385
  Epoch 020 - train 0.72259 | val 0.67835
  Epoch 021 - train 0.68965 | val 0.67917
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.71152 | val 0.67767
  Epoch 020 - train 0.73078 | val 0.67193
  Epoch 030 - train 0.71090 | val 0.67420
  Classification -> best τ=0.535 (val F1=0.4647)
  Directional -> Accuracy: 0.6341, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.71916 | val 0.70564
  Epoch 020 - train 0.68656 | val 0.71701
  Epoch 021 - train 0.70739 | val 0.71934
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5439, MCC: 0.0000, F1: 0.7045

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.73931 | val 0.68804
  Epoch 020 - train 0.71607 | val 0.66779
  Epoch 030 - train 0.71512 | val 0.66572

[I 2026-02-24 22:29:34,937] Trial 5 finished with value: 0.12104061115074678 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 10, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.0, 'dropout': 0.8, 'batch_size': 64, 'learning_rate': 7.865163568556227e-06, 'weight_decay': 2.0120084292419592e-05, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 1.4348307195534467, 'early_stopping_min_delta': 0.001305694166166862}. Best is trial 1 with value: 0.22088503642029134.

  Epoch 030 - train 0.69772 | val 0.70410
  Classification -> best τ=0.530 (val F1=0.3108)
  Directional -> Accuracy: 0.3968, MCC: -0.2080, F1: 0.5000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.12104061115074678
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: classification
Sequence length: 15
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.70250 | val 0.68137
  Epoch 020 - train 0.70669 | val 0.68126
  Epoch 027 - train 0.73522 | val 0.68182
  Classification -> best τ=0.430 (val F1=0.0799)
  Directional -> Accuracy: 0.4286, MCC: -0.1389, F1: 0.5926

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.71534 | val 0.69387
  Epoch 016 - train 0.70463 | val 0.69874
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 16). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.71330 | val 0.68686
  Epoch 020 - train 0.76258 | val 0.68206
  Epoch 030 - train 0.70500 | val 0.68496
  Epoch 032 - train 0.73644 | val 0.68520
  Classification -> best τ=0.490 (val F1=0.3030)
  Directional -> Accuracy: 0.5208, MCC: 0.1205, F1: 0.3429

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.71520 | val 0.69200
  Epoch 016 - train 0.73136 | val 0.69755
  Classification -> best τ=0.525 (val F1=0.1255)
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.72384 | val 0.69619
  Epoch 016 - train 0.73293 | val 0.70596
  Classification -> best τ=0.515 (val F1=0.0077)
  Directional -> Accuracy: 0.5000, MCC: -0.0740, F1: 0.6389

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.76465 | val 0.69658
  Epoch 016 - train 0.74423 | val 0.69805
  Classification -> best τ=0.525 (val F1=0.0618)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.74373 | val 0.69390
  Epoch 020 - train 0.74079 | val 0.69030
  Epoch 030 - train 0.73831 | val 0.69073
  Classification -> best τ=0.625 (val F1=0.2116)
  Directional -> Accuracy: 0.5286, MCC: 0.0352, F1: 0.4407

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 16). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.70060 | val 0.68343
  Epoch 016 - train 0.72809 | val 0.68386
  Classification -> best τ=0.490 (val F1=0.2229)
  Directional -> Accuracy: 0.4222, MCC: -0.0340, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.71653 | val 0.69610
  Epoch 020 - train 0.75288 | val 0.69602
  Epoch 024 - train 0.75108 | val 0.69992
  Classification -> best τ=0.525 (val F1=0.3091)
  Directional -> Accuracy: 0.3659, MCC: 0.0000, F1: 0.5357

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 16). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 16). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.71651 | val 0.69935
  Epoch 016 - train 0.71656 | val 0.72773
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4366, MCC: 0.0000, F1: 0.6078

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.75612 | val 0.69996
  Epoch 016 - train 0.74429 | val 0.70003
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.6400

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.69730 | val 0.70957
  Epoch 016 - train 0.72548 | val 0.73960
  Classification -> best τ=0.480 (val F1=0.1680)
  Directional -> Accuracy: 0.5085, MCC: 0.0000, F1: 0.6742

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.70797 | val 0.72263
  Epoch 016 - train 0.68958 | val 0.73589
  Classification -> best τ=0.465 (val F1=0.1218)
  Directional -> Accuracy: 0.4186, MCC: -0.1734, F1: 0.5902

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.69423 | val 0.67228
  Epoch 020 - train 0.70737 | val 0.65473
  Epoch 030 - train 0.70717 | val 0.65405
  Epoch 040 - train 0.71432 | val 0.65086
  Epoch 050 - train 0.69958 | val 0.64951
  Classification -> best τ=0.490 (val F1=0.4494)
  Directional -> Accuracy: 0.4426, MCC: -0.1137, F1: 0.3929

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.74007 | val 0.68950
  Epoch 020 - train 0.73033 | val 0.67753
  Epoch 030 - train 0.71998 | val 0.67518
  Epoch 039 - train 0.71669 | val 0.67611
  Classification -> best τ=0.445 (val F1=0.3592)
  Directional -> Accuracy: 0.6226, MCC: 0.2773, F1: 0.4118

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.68975 | val 0.67434
  Epoch 020 - train 0.73509 | val 0.65969
  Epoch 030 - train 0.71118 | val 0.66008
  Epoch 033 - train 0.69945 | val 0.65984
  Classification -> best τ=0.545 (val F1=0.3353)
  Directional -> Accuracy: 0.5143, MCC: 0.0262, F1: 0.5405

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.75028 | val 0.70082
  Epoch 016 - train 0.72838 | val 0.70901
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6167, MCC: 0.0000, F1: 0.7629

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.69480 | val 0.69324
  Epoch 016 - train 0.72097 | val 0.70431
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.71830 | val 0.69372
  Epoch 016 - train 0.70736 | val 0.69706
  Classification -> best τ=0.500 (val F1=0.1194)
  Directional -> Accuracy: 0.6364, MCC: 0.2666, F1: 0.6757

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 16). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.73520 | val 0.70958
  Epoch 016 - train 0.72962 | val 0.73499
  Classification -> best τ=0.510 (val F1=0.1560)
  Directional -> Accuracy: 0.5395, MCC: 0.0000, F1: 0.7009

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.70505 | val 0.69504
  Epoch 016 - train 0.70100 | val 0.70152
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.74612 | val 0.69636
  Epoch 016 - train 0.72626 | val 0.70170
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.72202 | val 0.68844
  Epoch 020 - train 0.73061 | val 0.69121
  Epoch 022 - train 0.71900 | val 0.69223
  Classification -> best τ=0.555 (val F1=0.2272)
  Directional -> Accuracy: 0.5345, MCC: -0.0028, F1: 0.6494

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.70763 | val 0.70733
  Epoch 016 - train 0.72134 | val 0.76357
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.74498 | val 0.69598
  Epoch 016 - train 0.74806 | val 0.69764
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.72978 | val 0.69992
  Epoch 016 - train 0.72456 | val 0.69998
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4255, MCC: 0.0000, F1: 0.5970

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.73097 | val 0.69892
  Epoch 016 - train 0.70078 | val 0.69805
  Classification -> best τ=0.485 (val F1=0.0528)
  Directional -> Accuracy: 0.4884, MCC: -0.1075, F1: 0.6071

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.74204 | val 0.70442
  Epoch 016 - train 0.74424 | val 0.72575
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5517, MCC: 0.0000, F1: 0.7111

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.71703 | val 0.69408
  Epoch 016 - train 0.71696 | val 0.69389
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.7077

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.75688 | val 0.69146
  Epoch 016 - train 0.74151 | val 0.69366
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.76070 | val 0.68723
  Epoch 016 - train 0.71456 | val 0.70868
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.72403 | val 0.69872
  Epoch 016 - train 0.71841 | val 0.71418
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.75319 | val 0.70207
  Epoch 016 - train 0.73916 | val 0.70500
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5676, MCC: 0.0000, F1: 0.7241

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.70693 | val 0.69190
  Epoch 016 - train 0.72446 | val 0.69123
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.77645 | val 0.69123
  Epoch 016 - train 0.77984 | val 0.69467
  Classification -> best τ=0.455 (val F1=0.1022)
  Directional -> Accuracy: 0.5333, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.69323 | val 0.68584
  Epoch 020 - train 0.70617 | val 0.67714
  Epoch 030 - train 0.69654 | val 0.67587
  Epoch 034 - train 0.69197 | val 0.67561
  Classification -> best τ=0.405 (val F1=0.3266)
  Directional -> Accuracy: 0.5224, MCC: -0.0248, F1: 0.6364

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.72386 | val 0.69350
  Epoch 016 - train 0.68960 | val 0.69438
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.70755 | val 0.68961
  Epoch 020 - train 0.77434 | val 0.67935
  Epoch 030 - train 0.73189 | val 0.67929
  Epoch 035 - train 0.72015 | val 0.67982
  Classification -> best τ=0.435 (val F1=0.2925)
  Directional -> Accuracy: 0.5614, MCC: 0.1259, F1: 0.5614

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.75003 | val 0.71154
  Epoch 016 - train 0.71817 | val 0.71189
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 16). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.70017 | val 0.68172
  Epoch 016 - train 0.72571 | val 0.67911
  Classification -> best τ=0.475 (val F1=0.1938)
  Directional -> Accuracy: 0.4000, MCC: -0.0262, F1: 0.4783

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.70475 | val 0.69735
  Epoch 020 - train 0.70808 | val 0.69040
  Epoch 030 - train 0.70992 | val 0.68217
  Epoch 040 - train 0.71381 | val 0.67988
  Epoch 050 - train 0.69908 | val 0.68084
  Classification -> best τ=0.410 (val F1=0.3397)
  Directional -> Accuracy: 0.4872, MCC: -0.1097, F1: 0.6296

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 16). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.71271 | val 0.69523
  Epoch 020 - train 0.72717 | val 0.70299
  Epoch 023 - train 0.71506 | val 0.70379
  Classification -> best τ=0.500 (val F1=0.1125)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.69461 | val 0.71172
  Epoch 016 - train 0.72690 | val 0.72765
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.73898 | val 0.68166
  Epoch 020 - train 0.72656 | val 0.67202
  Epoch 030 - train 0.69051 | val 0.65443
  Epoch 040 - train 0.71870 | val 0.63830
  Epoch 050 - train 0.74231 | val 0.63702
  Classification -> best τ=0.510 (val F1=0.5966)
  Directional -> Accuracy: 0.4444, MCC: -0.0349, F1: 0.1379

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.71698 | val 0.68415
  Epoch 020 - train 0.72251 | val 0.68366
  Epoch 029 - train 0.72343 | val 0.68794
  Classification -> best τ=0.530 (val F1=0.2928)
  Directional -> Accuracy: 0.4000, MCC: 0.0147, F1: 0.5000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.72973 | val 0.72440
  Epoch 016 - train 0.73391 | val 0.75798
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5439, MCC: 0.0000, F1: 0.7045

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.76008 | val 0.68694
  Epoch 020 - train 0.71013 | val 0.68712
  Epoch 026 - train 0.69784 | val 0.68856
  Classification -> best τ=0.470 (val F1=0.2554)
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.72270 | val 0.68668
  Epoch 016 - train 0.74517 | val 0.68962
  Classification -> best τ=0.520 (val F1=0.1647)
  Directional -> Accuracy: 0.4815, MCC: 0.0000, F1: 0.0000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.70437 | val 0.68451
  Epoch 020 - train 0.66907 | val 0.68543
  Epoch 027 - train 0.69476 | val 0.68808
  Classification -> best τ=0.500 (val F1=0.2236)
  Directional -> Accuracy: 0.5614, MCC: 0.1303, F1: 0.5098

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.71222 | val 0.68434
  Epoch 020 - train 0.72924 | val 0.67755
  Epoch 030 - train 0.72718 | val 0.67446

[I 2026-02-24 22:30:27,211] Trial 6 finished with value: 0.12999262115144192 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 15, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.1, 'dropout': 0.8, 'batch_size': 64, 'learning_rate': 6.436051550336386e-06, 'weight_decay': 4.3557227545457435e-05, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 0.44827416501961354, 'early_stopping_min_delta': 0.00233699175293296}. Best is trial 1 with value: 0.22088503642029134.

  Epoch 037 - train 0.71744 | val 0.67495
  Classification -> best τ=0.455 (val F1=0.2887)
  Directional -> Accuracy: 0.5161, MCC: 0.0106, F1: 0.1667

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.12999262115144192
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 5
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.64530 | val 0.73274
  Epoch 013 - train 0.65956 | val 0.77184
  Classification -> best τ=0.460 (val F1=0.2471)
  Directional -> Accuracy: 0.5570, MCC: 0.0803, F1: 0.4262

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.69354 | val 0.71113
  Epoch 011 - train 0.65548 | val 0.71110
  Classification -> best τ=0.515 (val F1=0.1009)
  Directional -> Accuracy: 0.5625, MCC: 0.0000, F1: 0.7200

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 6). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.68831 | val 0.69429
  Epoch 020 - train 0.66519 | val 0.70647
  Epoch 022 - train 0.66420 | val 0.72190
  Classification -> best τ=0.490 (val F1=0.4804)
  Directional -> Accuracy: 0.5200, MCC: 0.0897, F1: 0.4000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.68732 | val 0.71909
  Epoch 011 - train 0.68187 | val 0.72084
  Classification -> best τ=0.550 (val F1=0.1747)
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.68207 | val 0.67886
  Epoch 017 - train 0.65562 | val 0.67185
  Classification -> best τ=0.460 (val F1=0.3947)
  Directional -> Accuracy: 0.5283, MCC: 0.0162, F1: 0.6753

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.66267 | val 0.80016
  Epoch 011 - train 0.65757 | val 0.81303
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4762, MCC: 0.0000, F1: 0.6452

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.67813 | val 0.69244
  Epoch 011 - train 0.68763 | val 0.69091
  Classification -> best τ=0.450 (val F1=0.2276)
  Directional -> Accuracy: 0.5000, MCC: 0.0286, F1: 0.5000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 6). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.68630 | val 0.85170
  Epoch 011 - train 0.65248 | val 0.88645
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4043, MCC: 0.0000, F1: 0.5758

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.65682 | val 0.70292
  Epoch 011 - train 0.65845 | val 0.71105
  Classification -> best τ=0.480 (val F1=0.1983)
  Directional -> Accuracy: 0.3953, MCC: 0.0000, F1: 0.5667

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for proper time series validation for BRK-A. Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for proper time series validation for BSAC. Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.68023 | val 0.79913
  Epoch 011 - train 0.65863 | val 0.78590
  Classification -> best τ=0.450 (val F1=0.2765)
  Directional -> Accuracy: 0.4306, MCC: 0.0000, F1: 0.6019

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.67771 | val 0.69636
  Epoch 020 - train 0.67143 | val 0.75446
  Classification -> best τ=0.520 (val F1=0.1787)
  Directional -> Accuracy: 0.5769, MCC: 0.1355, F1: 0.3529

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.67950 | val 0.78321
  Epoch 011 - train 0.67984 | val 0.79199
  Classification -> best τ=0.550 (val F1=0.1923)
  Directional -> Accuracy: 0.5833, MCC: 0.1849, F1: 0.4681

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.61194 | val 0.71528
  Epoch 020 - train 0.62236 | val 0.69468
  Epoch 030 - train 0.60650 | val 0.86197
  Classification -> best τ=0.290 (val F1=0.2232)
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.6364

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.66889 | val 0.67768
  Epoch 015 - train 0.65343 | val 0.72971
  Classification -> best τ=0.430 (val F1=0.2365)
  Directional -> Accuracy: 0.4921, MCC: 0.0000, F1: 0.6596

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.66353 | val 0.84505
  Epoch 011 - train 0.64093 | val 0.88837
  Classification -> best τ=0.540 (val F1=0.1354)
  Directional -> Accuracy: 0.4364, MCC: -0.2446, F1: 0.6076

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.64766 | val 0.69947
  Epoch 015 - train 0.63582 | val 0.76102
  Classification -> best τ=0.565 (val F1=0.2566)
  Directional -> Accuracy: 0.4861, MCC: 0.0756, F1: 0.1778

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.67345 | val 0.92933
  Epoch 011 - train 0.65792 | val 0.93293
  Classification -> best τ=0.535 (val F1=0.0476)
  Directional -> Accuracy: 0.5161, MCC: -0.0325, F1: 0.6154

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.68427 | val 0.93949
  Epoch 011 - train 0.68287 | val 0.95258
  Classification -> best τ=0.505 (val F1=0.0406)
  Directional -> Accuracy: 0.4487, MCC: -0.1708, F1: 0.5567

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.65239 | val 0.77139
  Epoch 012 - train 0.67006 | val 0.75624
  Classification -> best τ=0.525 (val F1=0.2044)
  Directional -> Accuracy: 0.4559, MCC: 0.1212, F1: 0.1778

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 6). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.66820 | val 0.66199
  Epoch 020 - train 0.65045 | val 0.67216
  Classification -> best τ=0.390 (val F1=0.2865)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.67975 | val 0.79436
  Epoch 011 - train 0.67523 | val 0.79691
  Classification -> best τ=0.485 (val F1=0.0528)
  Directional -> Accuracy: 0.6200, MCC: 0.0000, F1: 0.7654

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.67911 | val 0.73359
  Epoch 011 - train 0.67704 | val 0.73611
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.67524 | val 0.69880
  Epoch 011 - train 0.66645 | val 0.70176
  Classification -> best τ=0.515 (val F1=0.0273)
  Directional -> Accuracy: 0.5667, MCC: 0.1189, F1: 0.6176

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.69141 | val 0.72560
  Epoch 011 - train 0.66070 | val 0.74091
  Classification -> best τ=0.470 (val F1=0.1818)
  Directional -> Accuracy: 0.5294, MCC: 0.0759, F1: 0.6000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.67927 | val 0.64293
  Epoch 020 - train 0.63789 | val 0.66067
  Classification -> best τ=0.465 (val F1=0.5264)
  Directional -> Accuracy: 0.5690, MCC: 0.2157, F1: 0.4681

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.64491 | val 0.69501
  Epoch 020 - train 0.63262 | val 0.69659
  Epoch 026 - train 0.63298 | val 0.70207
  Classification -> best τ=0.490 (val F1=0.2431)
  Directional -> Accuracy: 0.5000, MCC: 0.2722, F1: 0.6154

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.66244 | val 0.70270
  Epoch 011 - train 0.67965 | val 0.70566
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6000, MCC: 0.0000, F1: 0.7500

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.67394 | val 0.72620
  Epoch 011 - train 0.65218 | val 0.74245
  Classification -> best τ=0.455 (val F1=0.3066)
  Directional -> Accuracy: 0.4576, MCC: 0.1166, F1: 0.0588

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.66738 | val 0.75554
  Epoch 011 - train 0.67901 | val 0.76219
  Classification -> best τ=0.525 (val F1=0.1504)
  Directional -> Accuracy: 0.4444, MCC: -0.1139, F1: 0.2857

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.68664 | val 0.70759
  Epoch 011 - train 0.69034 | val 0.70516
  Classification -> best τ=0.520 (val F1=0.0119)
  Directional -> Accuracy: 0.5652, MCC: 0.1644, F1: 0.6667

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.67038 | val 0.68656
  Epoch 011 - train 0.69343 | val 0.68585
  Classification -> best τ=0.540 (val F1=0.0214)
  Directional -> Accuracy: 0.5435, MCC: 0.0338, F1: 0.6769

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.65343 | val 0.64902
  Epoch 020 - train 0.65321 | val 0.64490
  Classification -> best τ=0.465 (val F1=0.3795)
  Directional -> Accuracy: 0.5094, MCC: 0.0000, F1: 0.6750

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.67902 | val 0.64368
  Epoch 020 - train 0.66851 | val 0.63634
  Epoch 030 - train 0.63872 | val 0.63172
  Epoch 037 - train 0.63779 | val 0.67343
  Classification -> best τ=0.405 (val F1=0.3523)
  Directional -> Accuracy: 0.5600, MCC: 0.1364, F1: 0.5600

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.65236 | val 0.69865
  Epoch 011 - train 0.65533 | val 0.70053
  Classification -> best τ=0.500 (val F1=0.3477)
  Directional -> Accuracy: 0.5366, MCC: 0.0767, F1: 0.5581

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.66665 | val 0.72023
  Epoch 011 - train 0.65761 | val 0.72583
  Classification -> best τ=0.495 (val F1=0.3533)
  Directional -> Accuracy: 0.4783, MCC: -0.1220, F1: 0.2000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.68451 | val 0.69743
  Epoch 015 - train 0.66669 | val 0.69903
  Classification -> best τ=0.325 (val F1=0.3035)
  Directional -> Accuracy: 0.5942, MCC: 0.2519, F1: 0.5625

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.62483 | val 0.69300
  Epoch 014 - train 0.63670 | val 0.70220
  Classification -> best τ=0.500 (val F1=0.2478)
  Directional -> Accuracy: 0.6000, MCC: 0.2020, F1: 0.5909

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.64112 | val 0.88112
  Epoch 011 - train 0.63138 | val 0.88895
  Classification -> best τ=0.550 (val F1=0.2062)
  Directional -> Accuracy: 0.4746, MCC: -0.1388, F1: 0.1143

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.65245 | val 0.95307
  Epoch 011 - train 0.65714 | val 1.02581
  Classification -> best τ=0.500 (val F1=0.2973)
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.7595

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 6). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.66974 | val 0.66679
  Epoch 020 - train 0.67453 | val 0.64267
  Epoch 030 - train 0.61913 | val 0.66456
  Epoch 032 - train 0.61325 | val 0.65992
  Classification -> best τ=0.355 (val F1=0.3420)
  Directional -> Accuracy: 0.3333, MCC: 0.0000, F1: 0.5000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.67036 | val 0.70849
  Epoch 011 - train 0.66308 | val 0.71515
  Classification -> best τ=0.460 (val F1=0.2303)
  Directional -> Accuracy: 0.5854, MCC: 0.1800, F1: 0.6667

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 6). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.67724 | val 0.72698
  Epoch 013 - train 0.65346 | val 0.75025
  Classification -> best τ=0.565 (val F1=0.2385)
  Directional -> Accuracy: 0.5065, MCC: 0.0227, F1: 0.3448

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.68048 | val 0.80892
  Epoch 011 - train 0.69992 | val 0.85016
  Classification -> best τ=0.505 (val F1=0.0151)
  Directional -> Accuracy: 0.4490, MCC: -0.1358, F1: 0.2286

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.66406 | val 0.70091
  Epoch 011 - train 0.64559 | val 0.70835
  Classification -> best τ=0.480 (val F1=0.1581)
  Directional -> Accuracy: 0.5532, MCC: 0.0921, F1: 0.6038

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.64535 | val 0.96730
  Epoch 011 - train 0.64255 | val 1.00482
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3571, MCC: 0.0000, F1: 0.5263

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.69538 | val 0.77426
  Epoch 011 - train 0.66369 | val 0.80472
  Classification -> best τ=0.500 (val F1=0.1577)
  Directional -> Accuracy: 0.5517, MCC: 0.0531, F1: 0.6667

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.66251 | val 0.86240
  Epoch 011 - train 0.65990 | val 0.90895
  Classification -> best τ=0.505 (val F1=0.4167)
  Directional -> Accuracy: 0.4915, MCC: 0.0000, F1: 0.6591

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.66726 | val 0.76405
  Epoch 011 - train 0.66491 | val 0.77593
  Classification -> best τ=0.525 (val F1=0.1704)
  Directional -> Accuracy: 0.5179, MCC: -0.1255, F1: 0.6824

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.65205 | val 0.76252
  Epoch 011 - train 0.67054 | val 0.76894
  Classification -> best τ=0.470 (val F1=0.1126)
  Directional -> Accuracy: 0.5172, MCC: 0.0000, F1: 0.6818

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...

[I 2026-02-24 22:30:50,497] Trial 7 finished with value: 0.19535406498778174 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 5, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 64, 'learning_rate': 0.0008543725754869059, 'weight_decay': 2.4874392978243986e-07, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 0.15589071840158758, 'early_stopping_min_delta': 0.004831300196772425}. Best is trial 1 with value: 0.22088503642029134.

  Epoch 010 - train 0.67515 | val 0.71417
  Epoch 011 - train 0.69121 | val 0.71617
  Classification -> best τ=0.485 (val F1=0.0151)
  Directional -> Accuracy: 0.5079, MCC: 0.0510, F1: 0.6076

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.19535406498778174
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 10
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.62055 | val 0.74639
  Epoch 020 - train 0.60182 | val 0.75764
  Epoch 021 - train 0.60116 | val 0.75823
  Classification -> best τ=0.515 (val F1=0.1397)
  Directional -> Accuracy: 0.5897, MCC: 0.2060, F1: 0.6098

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.60125 | val 0.68618
  Epoch 020 - train 0.55560 | val 0.68282
  Epoch 028 - train 0.52765 | val 0.68468
  Classification -> best τ=0.485 (val F1=0.2905)
  Directional -> Accuracy: 0.5532, MCC: 0.0000, F1: 0.7123

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 11). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.63626 | val 0.90856
  Epoch 020 - train 0.61937 | val 1.12593
  Epoch 021 - train 0.61845 | val 1.12872
  Classification -> best τ=0.460 (val F1=0.3734)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.64199 | val 0.74824
  Epoch 020 - train 0.62886 | val 0.77987
  Epoch 021 - train 0.62829 | val 0.78523
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5395, MCC: 0.0000, F1: 0.7009

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.58484 | val 0.70694
  Epoch 020 - train 0.55113 | val 0.69619
  Epoch 023 - train 0.54736 | val 0.69805
  Classification -> best τ=0.505 (val F1=0.2928)
  Directional -> Accuracy: 0.5769, MCC: 0.1543, F1: 0.5926

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.58852 | val 1.29639
  Epoch 020 - train 0.56694 | val 1.61256
  Epoch 021 - train 0.56634 | val 1.61394
  Classification -> best τ=0.590 (val F1=0.2381)
  Directional -> Accuracy: 0.5306, MCC: 0.0910, F1: 0.3429

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.63040 | val 0.76630
  Epoch 020 - train 0.60737 | val 0.76670
  Epoch 021 - train 0.60673 | val 0.76871
  Classification -> best τ=0.410 (val F1=0.1732)
  Directional -> Accuracy: 0.4085, MCC: 0.0000, F1: 0.5800

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 11). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.60532 | val 1.36121
  Epoch 020 - train 0.58916 | val 1.54795
  Epoch 021 - train 0.58862 | val 1.55432
  Classification -> best τ=0.475 (val F1=0.1531)
  Directional -> Accuracy: 0.5870, MCC: 0.0931, F1: 0.3448

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.62005 | val 0.78214
  Epoch 020 - train 0.59813 | val 0.83521
  Epoch 021 - train 0.59692 | val 0.83827
  Classification -> best τ=0.500 (val F1=0.1386)
  Directional -> Accuracy: 0.6190, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for proper time series validation for BRK-A. Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for proper time series validation for BSAC. Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.60655 | val 1.15124
  Epoch 020 - train 0.58121 | val 1.45542
  Epoch 021 - train 0.58027 | val 1.49090
  Classification -> best τ=0.390 (val F1=0.2606)
  Directional -> Accuracy: 0.4366, MCC: 0.0000, F1: 0.6078

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.60317 | val 0.81724
  Epoch 020 - train 0.57424 | val 0.98732
  Epoch 021 - train 0.57338 | val 0.99019
  Classification -> best τ=0.515 (val F1=0.2073)
  Directional -> Accuracy: 0.5769, MCC: 0.1488, F1: 0.5417

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.63421 | val 0.74392
  Epoch 020 - train 0.61247 | val 0.72269
  Epoch 021 - train 0.61174 | val 0.72293
  Classification -> best τ=0.495 (val F1=0.1931)
  Directional -> Accuracy: 0.5085, MCC: 0.0000, F1: 0.6742

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.60107 | val 0.80588
  Epoch 020 - train 0.58318 | val 0.80080
  Epoch 021 - train 0.58266 | val 0.80333
  Classification -> best τ=0.465 (val F1=0.1210)
  Directional -> Accuracy: 0.4773, MCC: -0.2469, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.62950 | val 0.70165
  Epoch 020 - train 0.59885 | val 0.71598
  Epoch 023 - train 0.59513 | val 0.71999
  Classification -> best τ=0.370 (val F1=0.1014)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.58494 | val 1.06145
  Epoch 020 - train 0.55854 | val 0.97367
  Epoch 021 - train 0.55786 | val 0.96951
  Classification -> best τ=0.650 (val F1=0.2177)
  Directional -> Accuracy: 0.5556, MCC: 0.2035, F1: 0.1429

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.60101 | val 0.75306
  Epoch 020 - train 0.57833 | val 0.80311
  Epoch 022 - train 0.57656 | val 0.80703
  Classification -> best τ=0.700 (val F1=0.2090)
  Directional -> Accuracy: 0.4648, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.62091 | val 1.21394
  Epoch 020 - train 0.60127 | val 1.25748
  Epoch 021 - train 0.60063 | val 1.26264
  Classification -> best τ=0.455 (val F1=0.1999)
  Directional -> Accuracy: 0.6066, MCC: 0.0000, F1: 0.7551

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.61603 | val 0.99659
  Epoch 020 - train 0.59308 | val 1.13141
  Epoch 021 - train 0.59247 | val 1.13713
  Classification -> best τ=0.445 (val F1=0.0630)
  Directional -> Accuracy: 0.6104, MCC: 0.0000, F1: 0.7581

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.62577 | val 0.65381
  Epoch 020 - train 0.57627 | val 0.72206
  Epoch 030 - train 0.55618 | val 0.75728
  Classification -> best τ=0.390 (val F1=0.3240)
  Directional -> Accuracy: 0.4925, MCC: 0.0631, F1: 0.4138

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 11). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.60144 | val 0.69621
  Epoch 020 - train 0.57455 | val 0.71708
  Epoch 022 - train 0.57168 | val 0.72046
  Classification -> best τ=0.440 (val F1=0.2200)
  Directional -> Accuracy: 0.5455, MCC: 0.1399, F1: 0.4615

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.58880 | val 0.68452
  Epoch 020 - train 0.53269 | val 0.71207
  Epoch 027 - train 0.52065 | val 0.71299
  Classification -> best τ=0.555 (val F1=0.3837)
  Directional -> Accuracy: 0.5714, MCC: 0.1538, F1: 0.6182

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.63567 | val 0.79603
  Epoch 020 - train 0.61732 | val 0.82127
  Epoch 021 - train 0.61676 | val 0.82295
  Classification -> best τ=0.465 (val F1=0.2070)
  Directional -> Accuracy: 0.5522, MCC: 0.1116, F1: 0.6429

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.61556 | val 0.77977
  Epoch 020 - train 0.59219 | val 0.83785
  Epoch 021 - train 0.59080 | val 0.83833
  Classification -> best τ=0.535 (val F1=0.2423)
  Directional -> Accuracy: 0.5254, MCC: 0.1558, F1: 0.4167

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.61339 | val 0.76740
  Epoch 020 - train 0.58999 | val 0.74246
  Epoch 021 - train 0.58930 | val 0.74212
  Classification -> best τ=0.450 (val F1=0.1921)
  Directional -> Accuracy: 0.5672, MCC: 0.1438, F1: 0.5915

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.60350 | val 0.66793
  Epoch 020 - train 0.55431 | val 0.75401
  Epoch 025 - train 0.54370 | val 0.76312
  Classification -> best τ=0.545 (val F1=0.5089)
  Directional -> Accuracy: 0.5614, MCC: 0.1750, F1: 0.5098

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.59643 | val 0.77461
  Epoch 020 - train 0.57222 | val 0.84699
  Epoch 021 - train 0.57157 | val 0.84995
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4167, MCC: 0.0000, F1: 0.5882

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.60700 | val 0.95043
  Epoch 020 - train 0.58838 | val 1.15030
  Epoch 021 - train 0.58784 | val 1.15779
  Classification -> best τ=0.515 (val F1=0.0189)
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.7429

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.61093 | val 0.69745
  Epoch 020 - train 0.56893 | val 0.75286
  Epoch 021 - train 0.56691 | val 0.75784
  Classification -> best τ=0.450 (val F1=0.2650)
  Directional -> Accuracy: 0.5172, MCC: 0.1923, F1: 0.2632

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.60681 | val 0.68744
  Epoch 020 - train 0.55372 | val 0.80851
  Epoch 029 - train 0.53530 | val 0.88106
  Classification -> best τ=0.520 (val F1=0.2262)
  Directional -> Accuracy: 0.5814, MCC: 0.1489, F1: 0.6786

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.65211 | val 0.72593
  Epoch 020 - train 0.63443 | val 0.73297
  Epoch 021 - train 0.63398 | val 0.73290
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.61036 | val 0.69765
  Epoch 020 - train 0.58888 | val 0.71044
  Epoch 021 - train 0.58765 | val 0.71210
  Classification -> best τ=0.515 (val F1=0.1754)
  Directional -> Accuracy: 0.5111, MCC: 0.0513, F1: 0.4211

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.61467 | val 0.68629
  Epoch 020 - train 0.53924 | val 0.70714
  Epoch 024 - train 0.52335 | val 0.71147
  Classification -> best τ=0.400 (val F1=0.2456)
  Directional -> Accuracy: 0.5192, MCC: 0.0000, F1: 0.6835

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.60350 | val 0.69579
  Epoch 020 - train 0.55734 | val 0.70131
  Epoch 025 - train 0.55020 | val 0.70943
  Classification -> best τ=0.365 (val F1=0.2874)
  Directional -> Accuracy: 0.5811, MCC: 0.1883, F1: 0.5753

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.62471 | val 0.72415
  Epoch 020 - train 0.60881 | val 0.76375
  Epoch 021 - train 0.60839 | val 0.76389
  Classification -> best τ=0.445 (val F1=0.3380)
  Directional -> Accuracy: 0.5500, MCC: 0.1163, F1: 0.5909

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.60125 | val 0.86578
  Epoch 020 - train 0.58091 | val 0.90536
  Epoch 021 - train 0.58024 | val 0.90444
  Classification -> best τ=0.565 (val F1=0.0269)
  Directional -> Accuracy: 0.5778, MCC: 0.1545, F1: 0.5581

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.61419 | val 0.71979
  Epoch 020 - train 0.59059 | val 0.73250
  Epoch 021 - train 0.58918 | val 0.73306
  Classification -> best τ=0.445 (val F1=0.2948)
  Directional -> Accuracy: 0.5000, MCC: 0.1613, F1: 0.2917

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.60797 | val 0.71319
  Epoch 020 - train 0.58175 | val 0.73269
  Epoch 021 - train 0.58040 | val 0.73393
  Classification -> best τ=0.525 (val F1=0.0197)
  Directional -> Accuracy: 0.6136, MCC: 0.3107, F1: 0.7119

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.60747 | val 0.82155
  Epoch 020 - train 0.58612 | val 0.89895
  Epoch 021 - train 0.58484 | val 0.89643
  Classification -> best τ=0.535 (val F1=0.1599)
  Directional -> Accuracy: 0.4483, MCC: -0.0880, F1: 0.5000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.59956 | val 1.01698
  Epoch 020 - train 0.57049 | val 1.10981
  Epoch 021 - train 0.56930 | val 1.10689
  Classification -> best τ=0.445 (val F1=0.1826)
  Directional -> Accuracy: 0.5417, MCC: 0.0436, F1: 0.6207

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 11). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.62869 | val 0.67984
  Epoch 020 - train 0.57210 | val 0.69456
  Epoch 028 - train 0.55750 | val 0.69454
  Classification -> best τ=0.505 (val F1=0.4411)
  Directional -> Accuracy: 0.3415, MCC: 0.0000, F1: 0.5091

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.61024 | val 0.72613
  Epoch 020 - train 0.59355 | val 0.75040
  Epoch 021 - train 0.59307 | val 0.75052
  Classification -> best τ=0.475 (val F1=0.3055)
  Directional -> Accuracy: 0.3750, MCC: -0.2453, F1: 0.3243

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 11). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.60303 | val 0.88366
  Epoch 020 - train 0.57332 | val 1.09190
  Epoch 021 - train 0.57158 | val 1.09510
  Classification -> best τ=0.545 (val F1=0.2040)
  Directional -> Accuracy: 0.5065, MCC: 0.0082, F1: 0.5957

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.60519 | val 0.70320
  Epoch 020 - train 0.57007 | val 0.71222
  Epoch 021 - train 0.56743 | val 0.71145
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.58751 | val 0.79669
  Epoch 020 - train 0.56834 | val 0.83085
  Epoch 021 - train 0.56777 | val 0.83178
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.59738 | val 0.96623
  Epoch 020 - train 0.57850 | val 1.00583
  Epoch 021 - train 0.57796 | val 1.00923
  Classification -> best τ=0.545 (val F1=0.1517)
  Directional -> Accuracy: 0.6341, MCC: 0.3667, F1: 0.6341

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.62473 | val 0.87772
  Epoch 020 - train 0.60653 | val 0.93105
  Epoch 021 - train 0.60590 | val 0.93494
  Classification -> best τ=0.525 (val F1=0.1960)
  Directional -> Accuracy: 0.5789, MCC: 0.1883, F1: 0.5385

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.61243 | val 0.97027
  Epoch 020 - train 0.58692 | val 1.03261
  Epoch 021 - train 0.58583 | val 1.03336

[I 2026-02-24 22:31:49,213] Trial 8 finished with value: 0.19217215016074501 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 10, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.0, 'dropout': 0.0, 'batch_size': 32, 'learning_rate': 0.0003812974587348587, 'weight_decay': 0.00024560735067194863, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 50, 'huber_delta': 1.153805769128072, 'early_stopping_min_delta': 0.008240174221380674}. Best is trial 1 with value: 0.22088503642029134.

  Epoch 020 - train 0.59876 | val 0.90562
  Epoch 021 - train 0.59724 | val 0.89582
  Classification -> best τ=0.505 (val F1=0.1601)
  Directional -> Accuracy: 0.5238, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.19217215016074501
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 5
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.66836 | val 0.68996
  Epoch 020 - train 0.66474 | val 0.72761
  Epoch 021 - train 0.66251 | val 0.72881
  Classification -> best τ=0.465 (val F1=0.2363)
  Directional -> Accuracy: 0.5696, MCC: 0.1814, F1: 0.6047

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.68630 | val 0.68893
  Epoch 020 - train 0.66286 | val 0.69592
  Epoch 021 - train 0.65729 | val 0.69614
  Classification -> best τ=0.475 (val F1=0.1811)
  Directional -> Accuracy: 0.3750, MCC: -0.2185, F1: 0.2500

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 6). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.69191 | val 0.68486
  Epoch 020 - train 0.68129 | val 0.69063
  Epoch 021 - train 0.66126 | val 0.69061
  Classification -> best τ=0.530 (val F1=0.2203)
  Directional -> Accuracy: 0.4800, MCC: 0.0642, F1: 0.1333

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.69062 | val 0.69877
  Epoch 020 - train 0.67162 | val 0.74644
  Epoch 021 - train 0.67618 | val 0.74909
  Classification -> best τ=0.545 (val F1=0.0697)
  Directional -> Accuracy: 0.5455, MCC: 0.0468, F1: 0.6602

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.67783 | val 0.67048
  Epoch 020 - train 0.67455 | val 0.63596
  Epoch 030 - train 0.65562 | val 0.62530
  Epoch 040 - train 0.64833 | val 0.62005
  Epoch 050 - train 0.64158 | val 0.61858
  Classification -> best τ=0.485 (val F1=0.4312)
  Directional -> Accuracy: 0.7547, MCC: 0.5072, F1: 0.7719

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.69411 | val 0.69484
  Epoch 020 - train 0.67043 | val 0.70324
  Epoch 021 - train 0.66518 | val 0.70375
  Classification -> best τ=0.545 (val F1=0.1706)
  Directional -> Accuracy: 0.5238, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.69760 | val 0.68682
  Epoch 020 - train 0.68384 | val 0.68638
  Epoch 030 - train 0.67311 | val 0.68817
  Classification -> best τ=0.525 (val F1=0.2436)
  Directional -> Accuracy: 0.5139, MCC: 0.0141, F1: 0.4444

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 6). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.68199 | val 0.70606
  Epoch 020 - train 0.67224 | val 0.75255
  Epoch 021 - train 0.67170 | val 0.75730
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4043, MCC: 0.0000, F1: 0.5758

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.68181 | val 0.68558
  Epoch 020 - train 0.67666 | val 0.68232
  Epoch 030 - train 0.67352 | val 0.68269
  Epoch 036 - train 0.66895 | val 0.68351
  Classification -> best τ=0.535 (val F1=0.3429)
  Directional -> Accuracy: 0.5814, MCC: 0.0891, F1: 0.4000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for proper time series validation for BRK-A. Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for proper time series validation for BSAC. Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.67927 | val 0.76236
  Epoch 020 - train 0.67394 | val 0.81649
  Epoch 021 - train 0.68279 | val 0.81751
  Classification -> best τ=0.485 (val F1=0.1838)
  Directional -> Accuracy: 0.4306, MCC: 0.0000, F1: 0.6019

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.69488 | val 0.69906
  Epoch 020 - train 0.68619 | val 0.73576
  Epoch 021 - train 0.68919 | val 0.73552
  Classification -> best τ=0.500 (val F1=0.2309)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.68785 | val 0.69478
  Epoch 020 - train 0.67956 | val 0.70900
  Epoch 021 - train 0.67228 | val 0.71027
  Classification -> best τ=0.530 (val F1=0.0935)
  Directional -> Accuracy: 0.5167, MCC: 0.0385, F1: 0.6133

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.65724 | val 0.70827
  Epoch 020 - train 0.67363 | val 0.78469
  Epoch 021 - train 0.65908 | val 0.78974
  Classification -> best τ=0.535 (val F1=0.2182)
  Directional -> Accuracy: 0.5556, MCC: 0.0945, F1: 0.2308

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.67335 | val 0.66614
  Epoch 020 - train 0.66738 | val 0.65712
  Epoch 030 - train 0.66700 | val 0.65503
  Epoch 040 - train 0.66125 | val 0.65294
  Epoch 045 - train 0.66336 | val 0.66013
  Classification -> best τ=0.465 (val F1=0.2411)
  Directional -> Accuracy: 0.5714, MCC: 0.1625, F1: 0.6400

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.67203 | val 0.75010
  Epoch 020 - train 0.67851 | val 0.82343
  Epoch 021 - train 0.66874 | val 0.82804
  Classification -> best τ=0.500 (val F1=0.2001)
  Directional -> Accuracy: 0.5091, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.67427 | val 0.67349
  Epoch 020 - train 0.67742 | val 0.67622
  Epoch 030 - train 0.66776 | val 0.68058
  Epoch 031 - train 0.65406 | val 0.68076
  Classification -> best τ=0.510 (val F1=0.2369)
  Directional -> Accuracy: 0.4861, MCC: 0.0161, F1: 0.3509

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.66847 | val 0.81608
  Epoch 020 - train 0.67848 | val 0.98533
  Epoch 021 - train 0.65754 | val 0.99133
  Classification -> best τ=0.515 (val F1=0.0307)
  Directional -> Accuracy: 0.4032, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.69320 | val 0.70763
  Epoch 020 - train 0.67682 | val 0.72156
  Epoch 021 - train 0.67995 | val 0.72216
  Classification -> best τ=0.495 (val F1=0.0428)
  Directional -> Accuracy: 0.6026, MCC: 0.0000, F1: 0.7520

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.66198 | val 0.70411
  Epoch 020 - train 0.65170 | val 0.72012
  Epoch 021 - train 0.65376 | val 0.72024
  Classification -> best τ=0.500 (val F1=0.2279)
  Directional -> Accuracy: 0.4118, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 6). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.67650 | val 0.68873
  Epoch 020 - train 0.66533 | val 0.68665
  Epoch 030 - train 0.65931 | val 0.67546
  Epoch 040 - train 0.65714 | val 0.67183
  Epoch 050 - train 0.63255 | val 0.66913
  Classification -> best τ=0.455 (val F1=0.2335)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.67920 | val 0.69769
  Epoch 020 - train 0.66711 | val 0.71812
  Epoch 021 - train 0.65669 | val 0.71898
  Classification -> best τ=0.495 (val F1=0.0035)
  Directional -> Accuracy: 0.5000, MCC: 0.1211, F1: 0.4444

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.69036 | val 0.71838
  Epoch 020 - train 0.68346 | val 0.72506
  Epoch 021 - train 0.68443 | val 0.72540
  Classification -> best τ=0.465 (val F1=0.0374)
  Directional -> Accuracy: 0.5147, MCC: 0.0434, F1: 0.2326

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.68515 | val 0.69924
  Epoch 020 - train 0.67555 | val 0.70497
  Epoch 021 - train 0.66499 | val 0.70522
  Classification -> best τ=0.530 (val F1=0.1261)
  Directional -> Accuracy: 0.4833, MCC: 0.1326, F1: 0.2791

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.67866 | val 0.70875
  Epoch 020 - train 0.68157 | val 0.70723
  Epoch 021 - train 0.67343 | val 0.70715
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4853, MCC: 0.0000, F1: 0.6535

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.69130 | val 0.68154
  Epoch 020 - train 0.66638 | val 0.66783
  Epoch 030 - train 0.65602 | val 0.65446
  Epoch 040 - train 0.64811 | val 0.64675
  Epoch 050 - train 0.65048 | val 0.64071
  Classification -> best τ=0.505 (val F1=0.4552)
  Directional -> Accuracy: 0.5517, MCC: 0.1844, F1: 0.4348

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.69374 | val 0.69630
  Epoch 020 - train 0.67035 | val 0.70868
  Epoch 021 - train 0.67374 | val 0.70998
  Classification -> best τ=0.470 (val F1=0.2481)
  Directional -> Accuracy: 0.4250, MCC: 0.1307, F1: 0.5818

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.67074 | val 0.70100
  Epoch 020 - train 0.66109 | val 0.74322
  Epoch 021 - train 0.66107 | val 0.74735
  Classification -> best τ=0.505 (val F1=0.0066)
  Directional -> Accuracy: 0.6222, MCC: 0.1689, F1: 0.7213

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.67959 | val 0.72841
  Epoch 020 - train 0.67203 | val 0.72724
  Epoch 021 - train 0.67114 | val 0.72702
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5593, MCC: 0.0000, F1: 0.7174

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.67508 | val 0.69995
  Epoch 020 - train 0.66757 | val 0.75884
  Epoch 021 - train 0.66510 | val 0.76533
  Classification -> best τ=0.540 (val F1=0.3198)
  Directional -> Accuracy: 0.5333, MCC: 0.0811, F1: 0.4324

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.67766 | val 0.70755
  Epoch 020 - train 0.66735 | val 0.71694
  Epoch 021 - train 0.66962 | val 0.71754
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.68855 | val 0.68727
  Epoch 020 - train 0.67334 | val 0.67416
  Epoch 030 - train 0.69160 | val 0.67003
  Epoch 040 - train 0.67770 | val 0.66837
  Epoch 044 - train 0.66112 | val 0.66972
  Classification -> best τ=0.450 (val F1=0.2265)
  Directional -> Accuracy: 0.5435, MCC: 0.0000, F1: 0.7042

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.67263 | val 0.66293
  Epoch 020 - train 0.66626 | val 0.63914
  Epoch 030 - train 0.65552 | val 0.63356
  Epoch 040 - train 0.63791 | val 0.63044
  Epoch 048 - train 0.63776 | val 0.62815
  Classification -> best τ=0.445 (val F1=0.3507)
  Directional -> Accuracy: 0.5094, MCC: 0.0000, F1: 0.6750

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.69013 | val 0.67200
  Epoch 020 - train 0.67642 | val 0.67231
  Epoch 025 - train 0.66993 | val 0.67103
  Classification -> best τ=0.385 (val F1=0.2614)
  Directional -> Accuracy: 0.5733, MCC: 0.1673, F1: 0.5676

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.67222 | val 0.69314
  Epoch 020 - train 0.64713 | val 0.69077
  Epoch 021 - train 0.67150 | val 0.69094
  Classification -> best τ=0.480 (val F1=0.3239)
  Directional -> Accuracy: 0.5854, MCC: 0.2342, F1: 0.6792

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.67293 | val 0.73735
  Epoch 020 - train 0.66676 | val 0.79973
  Epoch 021 - train 0.66394 | val 0.80278
  Classification -> best τ=0.560 (val F1=0.2408)
  Directional -> Accuracy: 0.5435, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.67132 | val 0.67991
  Epoch 020 - train 0.66145 | val 0.67847
  Epoch 028 - train 0.66161 | val 0.68361
  Classification -> best τ=0.545 (val F1=0.2360)
  Directional -> Accuracy: 0.4203, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.67191 | val 0.69251
  Epoch 020 - train 0.64878 | val 0.68522
  Epoch 030 - train 0.64145 | val 0.68383
  Epoch 035 - train 0.64862 | val 0.68507
  Classification -> best τ=0.485 (val F1=0.3718)
  Directional -> Accuracy: 0.6444, MCC: 0.2883, F1: 0.6667

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.65202 | val 0.70062
  Epoch 020 - train 0.66502 | val 0.74368
  Epoch 021 - train 0.65749 | val 0.74565
  Classification -> best τ=0.490 (val F1=0.1234)
  Directional -> Accuracy: 0.4237, MCC: -0.1519, F1: 0.4138

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.68373 | val 0.69466
  Epoch 020 - train 0.66491 | val 0.70817
  Epoch 021 - train 0.66088 | val 0.70842
  Classification -> best τ=0.490 (val F1=0.2683)
  Directional -> Accuracy: 0.5918, MCC: -0.1149, F1: 0.7436

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 6). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.67285 | val 0.67396
  Epoch 020 - train 0.65353 | val 0.66501
  Epoch 030 - train 0.66507 | val 0.65900
  Epoch 040 - train 0.64901 | val 0.65515
  Epoch 049 - train 0.66378 | val 0.65338
  Classification -> best τ=0.420 (val F1=0.3647)
  Directional -> Accuracy: 0.3333, MCC: 0.0000, F1: 0.5000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.69842 | val 0.67743
  Epoch 020 - train 0.68981 | val 0.67940
  Epoch 021 - train 0.68124 | val 0.68051
  Classification -> best τ=0.485 (val F1=0.4277)
  Directional -> Accuracy: 0.3415, MCC: -0.3707, F1: 0.4706

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 6). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.68277 | val 0.70701
  Epoch 020 - train 0.66694 | val 0.73116
  Epoch 021 - train 0.65767 | val 0.73185
  Classification -> best τ=0.495 (val F1=0.1581)
  Directional -> Accuracy: 0.5065, MCC: 0.0000, F1: 0.6724

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.67570 | val 0.70381
  Epoch 020 - train 0.66846 | val 0.71367
  Epoch 021 - train 0.66707 | val 0.71440
  Classification -> best τ=0.540 (val F1=0.1664)
  Directional -> Accuracy: 0.5306, MCC: 0.0581, F1: 0.4651

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.67731 | val 0.68320
  Epoch 020 - train 0.67007 | val 0.71214
  Epoch 021 - train 0.64290 | val 0.71499
  Classification -> best τ=0.480 (val F1=0.3043)
  Directional -> Accuracy: 0.4681, MCC: 0.1814, F1: 0.1379

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...

[I 2026-02-24 22:32:07,608] Trial 9 finished with value: 0.1922062531051576 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 5, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 64, 'learning_rate': 7.792875478012232e-05, 'weight_decay': 0.0009446665637732142, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 50, 'huber_delta': 0.4106809251165815, 'early_stopping_min_delta': 0.007141869970740026}. Best is trial 1 with value: 0.22088503642029134.

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.1922062531051576
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.51221 | val 0.76905
  Epoch 016 - train 0.41253 | val 1.51991
  Classification -> best τ=0.630 (val F1=0.2919)
  Directional -> Accuracy: 0.5263, MCC: -0.0499, F1: 0.1429

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.44977 | val 1.79591
  Epoch 016 - train 0.31978 | val 2.21528
  Classification -> best τ=0.525 (val F1=0.2583)
  Directional -> Accuracy: 0.6222, MCC: 0.2440, F1: 0.6531

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.53612 | val 2.06723
  Epoch 016 - train 0.36876 | val 2.93163
  Classification -> best τ=0.475 (val F1=0.1572)
  Directional -> Accuracy: 0.5319, MCC: 0.0135, F1: 0.6857

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.57714 | val 1.73554
  Epoch 016 - train 0.41594 | val 1.22357
  Classification -> best τ=0.490 (val F1=0.1498)
  Directional -> Accuracy: 0.4800, MCC: 0.0321, F1: 0.2642

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.42184 | val 1.48355
  Epoch 016 - train 0.36746 | val 3.36128
  Classification -> best τ=0.490 (val F1=0.4051)
  Directional -> Accuracy: 0.7451, MCC: 0.4876, F1: 0.7636

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.40132 | val 3.26693
  Epoch 016 - train 0.20226 | val 7.39383
  Classification -> best τ=0.415 (val F1=0.2357)
  Directional -> Accuracy: 0.4043, MCC: -0.1993, F1: 0.3333

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.52521 | val 1.85816
  Epoch 016 - train 0.38506 | val 1.43591
  Classification -> best τ=0.510 (val F1=0.2876)
  Directional -> Accuracy: 0.4638, MCC: 0.1149, F1: 0.5843

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.29949 | val 2.62737
  Epoch 020 - train 0.10793 | val 2.62225
  Classification -> best τ=0.175 (val F1=0.1214)
  Directional -> Accuracy: 0.4419, MCC: 0.1309, F1: 0.6000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.48893 | val 2.30181
  Epoch 016 - train 0.30176 | val 4.15010
  Classification -> best τ=0.445 (val F1=0.2820)
  Directional -> Accuracy: 0.6122, MCC: 0.2027, F1: 0.4242

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.45187 | val 0.76541
  Epoch 020 - train 0.33029 | val 0.97615
  Classification -> best τ=0.470 (val F1=0.2274)
  Directional -> Accuracy: 0.4571, MCC: -0.0355, F1: 0.5128

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.48763 | val 3.95155
  Epoch 016 - train 0.37780 | val 6.71935
  Classification -> best τ=0.740 (val F1=0.2562)
  Directional -> Accuracy: 0.5200, MCC: 0.0401, F1: 0.5000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.55202 | val 1.42936
  Epoch 016 - train 0.37193 | val 2.50799
  Classification -> best τ=0.370 (val F1=0.2573)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.50226 | val 1.29649
  Epoch 019 - train 0.25971 | val 2.47961
  Classification -> best τ=0.530 (val F1=0.3064)
  Directional -> Accuracy: 0.5476, MCC: 0.1003, F1: 0.5366

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.57093 | val 0.69304
  Epoch 020 - train 0.36073 | val 1.17338
  Classification -> best τ=0.345 (val F1=0.3919)
  Directional -> Accuracy: 0.5167, MCC: 0.0467, F1: 0.6420

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.53682 | val 1.57931
  Epoch 016 - train 0.38799 | val 1.51872
  Classification -> best τ=0.515 (val F1=0.1296)
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.47442 | val 2.47516
  Epoch 016 - train 0.36315 | val 3.53998
  Classification -> best τ=0.535 (val F1=0.1667)
  Directional -> Accuracy: 0.4928, MCC: 0.0526, F1: 0.2553

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.52712 | val 4.96883
  Epoch 016 - train 0.41987 | val 7.97666
  Classification -> best τ=0.250 (val F1=0.1905)
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.48095 | val 1.59262
  Epoch 016 - train 0.36509 | val 3.48131
  Classification -> best τ=0.330 (val F1=0.1674)
  Directional -> Accuracy: 0.6133, MCC: 0.1430, F1: 0.7184

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.54098 | val 2.79550
  Epoch 016 - train 0.39848 | val 5.88870
  Classification -> best τ=0.405 (val F1=0.2234)
  Directional -> Accuracy: 0.4769, MCC: 0.0998, F1: 0.2917

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.52128 | val 1.42766
  Epoch 016 - train 0.34910 | val 1.57274
  Classification -> best τ=0.575 (val F1=0.2701)
  Directional -> Accuracy: 0.4267, MCC: -0.1414, F1: 0.0444

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.47630 | val 2.71890
  Epoch 016 - train 0.31160 | val 3.85441
  Classification -> best τ=0.380 (val F1=0.2267)
  Directional -> Accuracy: 0.5532, MCC: 0.1250, F1: 0.5882

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.53489 | val 3.66972
  Epoch 016 - train 0.36006 | val 2.38825
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.53178 | val 2.25777
  Epoch 016 - train 0.36797 | val 1.63790
  Classification -> best τ=0.650 (val F1=0.1826)
  Directional -> Accuracy: 0.4655, MCC: -0.0081, F1: 0.3673

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.48457 | val 0.96749
  Epoch 016 - train 0.39348 | val 1.57616
  Classification -> best τ=0.385 (val F1=0.1614)
  Directional -> Accuracy: 0.4769, MCC: 0.0000, F1: 0.6458

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.48750 | val 1.88475
  Epoch 016 - train 0.29780 | val 2.58268
  Classification -> best τ=0.560 (val F1=0.4795)
  Directional -> Accuracy: 0.5357, MCC: 0.1728, F1: 0.3810

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.37192 | val 1.88088
  Epoch 016 - train 0.30285 | val 2.61435
  Classification -> best τ=0.560 (val F1=0.1131)
  Directional -> Accuracy: 0.4565, MCC: 0.1307, F1: 0.6154

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.50003 | val 1.23436
  Epoch 016 - train 0.36676 | val 1.38616
  Classification -> best τ=0.535 (val F1=0.1936)
  Directional -> Accuracy: 0.4762, MCC: -0.0413, F1: 0.5000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.51581 | val 1.15909
  Epoch 016 - train 0.32982 | val 1.39297
  Classification -> best τ=0.510 (val F1=0.1625)
  Directional -> Accuracy: 0.4561, MCC: 0.1181, F1: 0.0606

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.40098 | val 2.20876
  Epoch 017 - train 0.24606 | val 1.96828
  Classification -> best τ=0.565 (val F1=0.2774)
  Directional -> Accuracy: 0.5366, MCC: 0.0872, F1: 0.5128

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.45112 | val 1.68666
  Epoch 017 - train 0.23783 | val 3.65537
  Classification -> best τ=0.550 (val F1=0.2814)
  Directional -> Accuracy: 0.5116, MCC: 0.0217, F1: 0.4878

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.42288 | val 1.97584
  Epoch 017 - train 0.22982 | val 2.39616
  Classification -> best τ=0.620 (val F1=0.0574)
  Directional -> Accuracy: 0.4884, MCC: -0.0426, F1: 0.5600

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.42017 | val 1.90273
  Epoch 016 - train 0.23598 | val 1.85589
  Classification -> best τ=0.405 (val F1=0.3850)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.49011 | val 1.43168
  Epoch 016 - train 0.48312 | val 1.44470
  Classification -> best τ=0.565 (val F1=0.3104)
  Directional -> Accuracy: 0.4658, MCC: 0.0633, F1: 0.1702

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.38007 | val 1.08933
  Epoch 017 - train 0.18126 | val 1.48274
  Classification -> best τ=0.530 (val F1=0.2887)
  Directional -> Accuracy: 0.5135, MCC: 0.0367, F1: 0.5714

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.47302 | val 3.26878
  Epoch 016 - train 0.26298 | val 5.41655
  Classification -> best τ=0.410 (val F1=0.1329)
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.53326 | val 1.03837
  Epoch 016 - train 0.33054 | val 1.96189
  Classification -> best τ=0.250 (val F1=0.3342)
  Directional -> Accuracy: 0.6364, MCC: 0.2345, F1: 0.7143

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.43088 | val 2.04985
  Epoch 016 - train 0.28514 | val 5.17426
  Classification -> best τ=0.485 (val F1=0.3099)
  Directional -> Accuracy: 0.5952, MCC: 0.2656, F1: 0.4516

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.45855 | val 3.59475
  Epoch 017 - train 0.28512 | val 5.71436
  Classification -> best τ=0.340 (val F1=0.2868)
  Directional -> Accuracy: 0.5714, MCC: 0.2244, F1: 0.6571

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.38351 | val 2.03144
  Epoch 016 - train 0.29195 | val 1.98659
  Classification -> best τ=0.485 (val F1=0.3225)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.41521 | val 1.36720
  Epoch 019 - train 0.21618 | val 1.85740
  Classification -> best τ=0.390 (val F1=0.5125)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.30977 | val 2.08424
  Epoch 016 - train 0.22352 | val 3.07636
  Classification -> best τ=0.565 (val F1=0.0585)
  Directional -> Accuracy: 0.4595, MCC: 0.0000, F1: 0.0000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.50480 | val 2.60684
  Epoch 017 - train 0.38079 | val 4.67339
  Classification -> best τ=0.345 (val F1=0.3358)
  Directional -> Accuracy: 0.5200, MCC: 0.1633, F1: 0.6727

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.38566 | val 1.07403
  Epoch 017 - train 0.20077 | val 1.83451
  Classification -> best τ=0.430 (val F1=0.3367)
  Directional -> Accuracy: 0.5000, MCC: 0.0077, F1: 0.4651

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.32656 | val 1.49632
  Epoch 016 - train 0.15202 | val 1.37689
  Classification -> best τ=0.530 (val F1=0.1581)
  Directional -> Accuracy: 0.5581, MCC: 0.0813, F1: 0.6415

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.30821 | val 1.31254
  Epoch 018 - train 0.16692 | val 3.47600
  Classification -> best τ=0.525 (val F1=0.2974)
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.54717 | val 1.98597
  Epoch 016 - train 0.49283 | val 3.41110
  Classification -> best τ=0.415 (val F1=0.2037)
  Directional -> Accuracy: 0.4643, MCC: -0.1536, F1: 0.6053

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.50583 | val 5.82097
  Epoch 016 - train 0.30740 | val 4.57254
  Classification -> best τ=0.730 (val F1=0.3735)
  Directional -> Accuracy: 0.5536, MCC: 0.1444, F1: 0.6377

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.57287 | val 3.50178
  Epoch 016 - train 0.31367 | val 5.51531
  Classification -> best τ=0.290 (val F1=0.2012)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.40401 | val 5.83259
  Epoch 016 - train 0.28484 | val 10.23158
  Classification -> best τ=0.610 (val F1=0.1979)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.55084 | val 0.74345

[I 2026-02-24 22:33:11,090] Trial 10 finished with value: 0.24541664459522175 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.4, 'dropout': 0.2, 'batch_size': 16, 'learning_rate': 0.005955429972346466, 'weight_decay': 1.4752331220173866e-06, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 1.974586958123333, 'early_stopping_min_delta': 0.003694425505571277}. Best is trial 10 with value: 0.24541664459522175.

  Epoch 016 - train 0.32608 | val 1.76512
  Classification -> best τ=0.375 (val F1=0.3139)
  Directional -> Accuracy: 0.4590, MCC: -0.0722, F1: 0.5075

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.24541664459522175
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.57427 | val 1.13759
  Epoch 017 - train 0.40626 | val 2.61203
  Classification -> best τ=0.420 (val F1=0.3370)
  Directional -> Accuracy: 0.4342, MCC: -0.1104, F1: 0.4691

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.45309 | val 1.05027
  Epoch 017 - train 0.23707 | val 2.49665
  Classification -> best τ=0.470 (val F1=0.1313)
  Directional -> Accuracy: 0.6444, MCC: 0.2704, F1: 0.7576

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.50641 | val 1.13109
  Epoch 017 - train 0.41122 | val 0.98938
  Classification -> best τ=0.400 (val F1=0.2295)
  Directional -> Accuracy: 0.5106, MCC: -0.0231, F1: 0.6349

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.60062 | val 2.47555
  Epoch 020 - train 0.47843 | val 1.56563
  Classification -> best τ=0.685 (val F1=0.2474)
  Directional -> Accuracy: 0.5067, MCC: 0.1208, F1: 0.2745

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.51581 | val 3.20195
  Epoch 016 - train 0.28249 | val 6.42374
  Classification -> best τ=0.355 (val F1=0.3120)
  Directional -> Accuracy: 0.6667, MCC: 0.3879, F1: 0.7536

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.35614 | val 3.48253
  Epoch 016 - train 0.23677 | val 3.19213
  Classification -> best τ=0.395 (val F1=0.1644)
  Directional -> Accuracy: 0.5745, MCC: 0.1969, F1: 0.6667

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.51979 | val 1.56456
  Epoch 016 - train 0.38733 | val 1.50064
  Classification -> best τ=0.375 (val F1=0.2462)
  Directional -> Accuracy: 0.4348, MCC: 0.0049, F1: 0.5517

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.36701 | val 0.97819
  Epoch 016 - train 0.15901 | val 2.50096
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.5902

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.44768 | val 2.55364
  Epoch 016 - train 0.34338 | val 3.93865
  Classification -> best τ=0.395 (val F1=0.2820)
  Directional -> Accuracy: 0.5510, MCC: 0.0714, F1: 0.4211

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.56235 | val 0.83839
  Epoch 017 - train 0.35936 | val 0.77750
  Classification -> best τ=0.465 (val F1=0.1816)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.53548 | val 3.99532
  Epoch 016 - train 0.38553 | val 7.22852
  Classification -> best τ=0.665 (val F1=0.2562)
  Directional -> Accuracy: 0.6200, MCC: 0.2271, F1: 0.5128

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.59984 | val 1.30236
  Epoch 016 - train 0.43610 | val 1.85944
  Classification -> best τ=0.475 (val F1=0.2759)
  Directional -> Accuracy: 0.6724, MCC: 0.3553, F1: 0.7077

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.54341 | val 0.68354
  Epoch 018 - train 0.29320 | val 0.71830
  Classification -> best τ=0.535 (val F1=0.3468)
  Directional -> Accuracy: 0.5238, MCC: 0.0912, F1: 0.5833

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.60022 | val 2.09265
  Epoch 016 - train 0.46107 | val 3.11640
  Classification -> best τ=0.360 (val F1=0.3635)
  Directional -> Accuracy: 0.5500, MCC: 0.1292, F1: 0.6582

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.48131 | val 0.97109
  Epoch 018 - train 0.33327 | val 4.14439
  Classification -> best τ=0.730 (val F1=0.2673)
  Directional -> Accuracy: 0.5577, MCC: 0.1255, F1: 0.5660

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.44265 | val 2.01257
  Epoch 016 - train 0.38190 | val 2.37235
  Classification -> best τ=0.660 (val F1=0.2010)
  Directional -> Accuracy: 0.4638, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.63788 | val 3.64455
  Epoch 016 - train 0.44548 | val 5.78696
  Classification -> best τ=0.640 (val F1=0.1842)
  Directional -> Accuracy: 0.3729, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.55753 | val 1.08731
  Epoch 017 - train 0.34899 | val 2.63826
  Classification -> best τ=0.530 (val F1=0.2236)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.57140 | val 2.70298
  Epoch 016 - train 0.36380 | val 5.76090
  Classification -> best τ=0.380 (val F1=0.2843)
  Directional -> Accuracy: 0.4769, MCC: 0.0998, F1: 0.2917

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.53118 | val 0.88424
  Epoch 016 - train 0.46412 | val 1.78023
  Classification -> best τ=0.615 (val F1=0.2450)
  Directional -> Accuracy: 0.4267, MCC: -0.1192, F1: 0.3175

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.52994 | val 1.27806
  Epoch 016 - train 0.34962 | val 2.82372
  Classification -> best τ=0.640 (val F1=0.2375)
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.53538 | val 3.67600
  Epoch 016 - train 0.40672 | val 2.50904
  Classification -> best τ=0.365 (val F1=0.0992)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.55230 | val 1.79898
  Epoch 018 - train 0.28807 | val 3.64049
  Classification -> best τ=0.690 (val F1=0.2234)
  Directional -> Accuracy: 0.4828, MCC: 0.0370, F1: 0.3750

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.50737 | val 1.94778
  Epoch 017 - train 0.36680 | val 1.00305
  Classification -> best τ=0.285 (val F1=0.1581)
  Directional -> Accuracy: 0.4769, MCC: 0.0000, F1: 0.6458

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.52561 | val 1.29998
  Epoch 016 - train 0.36548 | val 2.37471
  Classification -> best τ=0.415 (val F1=0.4082)
  Directional -> Accuracy: 0.6071, MCC: 0.2386, F1: 0.5926

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.48619 | val 2.10749
  Epoch 016 - train 0.22842 | val 5.47651
  Classification -> best τ=0.525 (val F1=0.2035)
  Directional -> Accuracy: 0.5652, MCC: 0.0782, F1: 0.3750

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.46829 | val 1.81769
  Epoch 016 - train 0.33198 | val 2.99465
  Classification -> best τ=0.555 (val F1=0.1353)
  Directional -> Accuracy: 0.4524, MCC: 0.0534, F1: 0.1481

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.42499 | val 1.65681
  Epoch 017 - train 0.27413 | val 3.10776
  Classification -> best τ=0.380 (val F1=0.2391)
  Directional -> Accuracy: 0.5263, MCC: 0.2741, F1: 0.2703

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.38229 | val 0.99972
  Epoch 017 - train 0.26689 | val 1.19152
  Classification -> best τ=0.525 (val F1=0.4139)
  Directional -> Accuracy: 0.3902, MCC: -0.3000, F1: 0.5283

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.33824 | val 2.63573
  Epoch 016 - train 0.15444 | val 3.06393
  Classification -> best τ=0.570 (val F1=0.2814)
  Directional -> Accuracy: 0.5581, MCC: 0.1169, F1: 0.5581

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.37886 | val 1.85359
  Epoch 018 - train 0.16241 | val 2.12611
  Classification -> best τ=0.550 (val F1=0.2454)
  Directional -> Accuracy: 0.5581, MCC: 0.1107, F1: 0.6984

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.46016 | val 1.11650
  Epoch 016 - train 0.35426 | val 1.67622
  Classification -> best τ=0.445 (val F1=0.3302)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.53153 | val 0.97520
  Epoch 017 - train 0.48802 | val 1.18668
  Classification -> best τ=0.495 (val F1=0.3824)
  Directional -> Accuracy: 0.5342, MCC: 0.1602, F1: 0.4138

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.31115 | val 2.81122
  Epoch 017 - train 0.15374 | val 2.24371
  Classification -> best τ=0.540 (val F1=0.2887)
  Directional -> Accuracy: 0.5405, MCC: 0.0783, F1: 0.3704

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.53740 | val 3.54110
  Epoch 016 - train 0.38280 | val 3.65451
  Classification -> best τ=0.420 (val F1=0.1329)
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.51468 | val 1.09353
  Epoch 016 - train 0.36219 | val 2.05002
  Classification -> best τ=0.210 (val F1=0.2464)
  Directional -> Accuracy: 0.6818, MCC: 0.3565, F1: 0.7742

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.45612 | val 2.15707
  Epoch 017 - train 0.17474 | val 3.66590
  Classification -> best τ=0.680 (val F1=0.2652)
  Directional -> Accuracy: 0.4762, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.50238 | val 3.06979
  Epoch 016 - train 0.35462 | val 3.04627
  Classification -> best τ=0.295 (val F1=0.2755)
  Directional -> Accuracy: 0.4821, MCC: 0.0625, F1: 0.6329

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.50441 | val 1.97132
  Epoch 016 - train 0.31302 | val 2.86750
  Classification -> best τ=0.360 (val F1=0.2504)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.42211 | val 0.94090
  Epoch 017 - train 0.23675 | val 1.59443
  Classification -> best τ=0.380 (val F1=0.1687)
  Directional -> Accuracy: 0.3878, MCC: -0.0973, F1: 0.4643

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.26952 | val 2.01135
  Epoch 016 - train 0.09671 | val 3.46809
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.56340 | val 2.54434
  Epoch 016 - train 0.32852 | val 5.06921
  Classification -> best τ=0.335 (val F1=0.3043)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.39982 | val 1.62788
  Epoch 017 - train 0.17161 | val 1.51181
  Classification -> best τ=0.385 (val F1=0.2933)
  Directional -> Accuracy: 0.4783, MCC: -0.0496, F1: 0.5200

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.28035 | val 1.23740
  Epoch 016 - train 0.12405 | val 2.43147
  Classification -> best τ=0.580 (val F1=0.5052)
  Directional -> Accuracy: 0.4651, MCC: 0.0118, F1: 0.2581

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.26917 | val 1.74968
  Epoch 016 - train 0.19682 | val 2.86900
  Classification -> best τ=0.470 (val F1=0.4216)
  Directional -> Accuracy: 0.3673, MCC: -0.1462, F1: 0.5231

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.53795 | val 1.23448
  Epoch 016 - train 0.48324 | val 1.48254
  Classification -> best τ=0.360 (val F1=0.2037)
  Directional -> Accuracy: 0.4643, MCC: -0.1240, F1: 0.5833

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.51825 | val 1.88996
  Epoch 016 - train 0.35476 | val 5.12311
  Classification -> best τ=0.655 (val F1=0.3723)
  Directional -> Accuracy: 0.5179, MCC: 0.0875, F1: 0.6400

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.58284 | val 3.01387
  Epoch 016 - train 0.33422 | val 5.34827
  Classification -> best τ=0.575 (val F1=0.1626)
  Directional -> Accuracy: 0.6111, MCC: 0.2202, F1: 0.6316

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.41274 | val 5.93567
  Epoch 016 - train 0.29898 | val 5.41344
  Classification -> best τ=0.540 (val F1=0.1244)
  Directional -> Accuracy: 0.4821, MCC: -0.0875, F1: 0.6234

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.48283 | val 0.94324

[I 2026-02-24 22:34:15,171] Trial 11 finished with value: 0.2471174951319538 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.4, 'dropout': 0.2, 'batch_size': 16, 'learning_rate': 0.009357862438710899, 'weight_decay': 1.5516693831563016e-06, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 1.937266601965124, 'early_stopping_min_delta': 0.003303784923187427}. Best is trial 11 with value: 0.2471174951319538.

  Epoch 016 - train 0.37624 | val 2.34839
  Classification -> best τ=0.400 (val F1=0.2039)
  Directional -> Accuracy: 0.4754, MCC: -0.0946, F1: 0.2381

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2471174951319538
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.63040 | val 1.77977
  Epoch 017 - train 0.47765 | val 1.66128
  Classification -> best τ=0.475 (val F1=0.3286)
  Directional -> Accuracy: 0.5263, MCC: 0.0586, F1: 0.5135

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.50905 | val 1.70391
  Epoch 016 - train 0.33888 | val 2.25458
  Classification -> best τ=0.575 (val F1=0.1164)
  Directional -> Accuracy: 0.6222, MCC: 0.2110, F1: 0.6909

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.51113 | val 1.40455
  Epoch 017 - train 0.42572 | val 3.11224
  Classification -> best τ=0.605 (val F1=0.3924)
  Directional -> Accuracy: 0.5319, MCC: 0.1157, F1: 0.3889

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.57216 | val 4.10266
  Epoch 017 - train 0.46481 | val 7.17181
  Classification -> best τ=0.310 (val F1=0.1688)
  Directional -> Accuracy: 0.4800, MCC: -0.0465, F1: 0.5185

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.45829 | val 1.30429
  Epoch 017 - train 0.28679 | val 3.69632
  Classification -> best τ=0.475 (val F1=0.4041)
  Directional -> Accuracy: 0.7059, MCC: 0.4167, F1: 0.7541

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.37218 | val 3.44305
  Epoch 016 - train 0.27097 | val 5.44099
  Classification -> best τ=0.530 (val F1=0.2928)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.52228 | val 2.03356
  Epoch 019 - train 0.33597 | val 1.07557
  Classification -> best τ=0.620 (val F1=0.2691)
  Directional -> Accuracy: 0.4638, MCC: 0.0345, F1: 0.5432

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.43724 | val 1.21654
  Epoch 018 - train 0.17230 | val 2.27467
  Classification -> best τ=0.510 (val F1=0.3639)
  Directional -> Accuracy: 0.5814, MCC: 0.0528, F1: 0.1818

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.51624 | val 2.39914
  Epoch 016 - train 0.33707 | val 4.34514
  Classification -> best τ=0.590 (val F1=0.4040)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.48182 | val 0.71978
  Epoch 017 - train 0.36479 | val 0.86257
  Classification -> best τ=0.490 (val F1=0.1826)
  Directional -> Accuracy: 0.4000, MCC: -0.1980, F1: 0.5714

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.59810 | val 3.30268
  Epoch 016 - train 0.55295 | val 8.11988
  Classification -> best τ=0.705 (val F1=0.1346)
  Directional -> Accuracy: 0.5000, MCC: 0.0234, F1: 0.5455

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.52985 | val 1.67648
  Epoch 016 - train 0.49767 | val 1.89787
  Classification -> best τ=0.445 (val F1=0.3062)
  Directional -> Accuracy: 0.5862, MCC: 0.2067, F1: 0.4286

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.49926 | val 0.85769
  Epoch 017 - train 0.43739 | val 1.88381
  Classification -> best τ=0.420 (val F1=0.2573)
  Directional -> Accuracy: 0.5714, MCC: 0.1647, F1: 0.5909

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.59295 | val 0.71410
  Epoch 018 - train 0.49327 | val 1.69871
  Classification -> best τ=0.255 (val F1=0.3669)
  Directional -> Accuracy: 0.5667, MCC: 0.1667, F1: 0.6667

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.52506 | val 1.02152
  Epoch 016 - train 0.34415 | val 1.27987
  Classification -> best τ=0.530 (val F1=0.3563)
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.58344 | val 1.13662
  Epoch 016 - train 0.40049 | val 1.98013
  Classification -> best τ=0.645 (val F1=0.0983)
  Directional -> Accuracy: 0.4638, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.58815 | val 2.51925
  Epoch 016 - train 0.41419 | val 5.96388
  Classification -> best τ=0.255 (val F1=0.1486)
  Directional -> Accuracy: 0.5932, MCC: 0.0017, F1: 0.7273

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.53795 | val 1.09491
  Epoch 017 - train 0.47970 | val 1.37032
  Classification -> best τ=0.405 (val F1=0.2579)
  Directional -> Accuracy: 0.4800, MCC: -0.1155, F1: 0.5895

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.55337 | val 3.64922
  Epoch 016 - train 0.48840 | val 5.83303
  Classification -> best τ=0.275 (val F1=0.2522)
  Directional -> Accuracy: 0.5692, MCC: 0.0944, F1: 0.6500

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.53566 | val 1.42225
  Epoch 016 - train 0.46334 | val 2.37538
  Classification -> best τ=0.495 (val F1=0.1875)
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.49925 | val 1.10322
  Epoch 016 - train 0.28704 | val 2.77772
  Classification -> best τ=0.490 (val F1=0.2845)
  Directional -> Accuracy: 0.4894, MCC: -0.1042, F1: 0.6000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.49292 | val 1.48893
  Epoch 016 - train 0.42460 | val 3.71411
  Classification -> best τ=0.595 (val F1=0.2319)
  Directional -> Accuracy: 0.5606, MCC: 0.1482, F1: 0.3830

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.52766 | val 1.28343
  Epoch 017 - train 0.48367 | val 1.51745
  Classification -> best τ=0.505 (val F1=0.1461)
  Directional -> Accuracy: 0.4483, MCC: -0.0773, F1: 0.4286

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.60541 | val 0.93256
  Epoch 020 - train 0.39565 | val 1.08764
  Classification -> best τ=0.565 (val F1=0.2449)
  Directional -> Accuracy: 0.4769, MCC: 0.0000, F1: 0.6458

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.58119 | val 1.07240
  Epoch 016 - train 0.40289 | val 2.02796
  Classification -> best τ=0.345 (val F1=0.4082)
  Directional -> Accuracy: 0.5893, MCC: 0.1878, F1: 0.5965

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.50274 | val 2.28876
  Epoch 016 - train 0.23898 | val 6.33973
  Classification -> best τ=0.505 (val F1=0.1981)
  Directional -> Accuracy: 0.5435, MCC: 0.3063, F1: 0.6557

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.57382 | val 0.81350
  Epoch 016 - train 0.40374 | val 5.56403
  Classification -> best τ=0.525 (val F1=0.2402)
  Directional -> Accuracy: 0.4286, MCC: -0.0700, F1: 0.2500

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.56667 | val 1.16911
  Epoch 016 - train 0.38872 | val 2.32094
  Classification -> best τ=0.450 (val F1=0.1847)
  Directional -> Accuracy: 0.4561, MCC: 0.1181, F1: 0.0606

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.46262 | val 0.98885
  Epoch 017 - train 0.39041 | val 1.23411
  Classification -> best τ=0.650 (val F1=0.4862)
  Directional -> Accuracy: 0.4146, MCC: -0.2128, F1: 0.5200

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.51133 | val 2.22969
  Epoch 016 - train 0.24300 | val 3.93333
  Classification -> best τ=0.540 (val F1=0.2814)
  Directional -> Accuracy: 0.5349, MCC: 0.0746, F1: 0.5652

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.45008 | val 1.77620
  Epoch 017 - train 0.19041 | val 3.13302
  Classification -> best τ=0.505 (val F1=0.2282)
  Directional -> Accuracy: 0.5349, MCC: 0.0282, F1: 0.6667

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.62739 | val 1.07961
  Epoch 016 - train 0.37910 | val 2.10935
  Classification -> best τ=0.375 (val F1=0.2273)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.60201 | val 1.04488
  Epoch 016 - train 0.45840 | val 2.34603
  Classification -> best τ=0.540 (val F1=0.3224)
  Directional -> Accuracy: 0.4521, MCC: 0.0438, F1: 0.0909

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.43203 | val 1.14585
  Epoch 018 - train 0.23380 | val 4.45743
  Classification -> best τ=0.550 (val F1=0.1992)
  Directional -> Accuracy: 0.5676, MCC: 0.1586, F1: 0.3333

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.52656 | val 2.72725
  Epoch 016 - train 0.34242 | val 4.87104
  Classification -> best τ=0.365 (val F1=0.1902)
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.59369 | val 1.32443
  Epoch 017 - train 0.39524 | val 1.59785
  Classification -> best τ=0.185 (val F1=0.3551)
  Directional -> Accuracy: 0.6061, MCC: 0.2406, F1: 0.6061

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.38811 | val 4.27765
  Epoch 016 - train 0.26070 | val 5.56682
  Classification -> best τ=0.525 (val F1=0.3499)
  Directional -> Accuracy: 0.6190, MCC: 0.2864, F1: 0.5294

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.45066 | val 2.18508
  Epoch 016 - train 0.30225 | val 2.66450
  Classification -> best τ=0.240 (val F1=0.2543)
  Directional -> Accuracy: 0.4821, MCC: 0.0404, F1: 0.6234

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.38702 | val 1.82184
  Epoch 016 - train 0.23997 | val 2.39870
  Classification -> best τ=0.370 (val F1=0.1709)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.44998 | val 1.24581
  Epoch 018 - train 0.25480 | val 3.72615
  Classification -> best τ=0.280 (val F1=0.2749)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.38097 | val 2.56067
  Epoch 016 - train 0.20350 | val 3.47969
  Classification -> best τ=0.485 (val F1=0.1816)
  Directional -> Accuracy: 0.6216, MCC: 0.2701, F1: 0.7308

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.48567 | val 5.47053
  Epoch 016 - train 0.39547 | val 5.80255
  Classification -> best τ=0.285 (val F1=0.2924)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.50363 | val 0.92507
  Epoch 016 - train 0.29497 | val 1.15841
  Classification -> best τ=0.550 (val F1=0.1064)
  Directional -> Accuracy: 0.5000, MCC: 0.0210, F1: 0.3784

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.28339 | val 1.77222
  Epoch 016 - train 0.10601 | val 2.28033
  Classification -> best τ=0.575 (val F1=0.3175)
  Directional -> Accuracy: 0.4419, MCC: -0.0471, F1: 0.2000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.46635 | val 1.21215
  Epoch 016 - train 0.23798 | val 2.40646
  Classification -> best τ=0.510 (val F1=0.1406)
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.56571 | val 1.89306
  Epoch 016 - train 0.48924 | val 2.96807
  Classification -> best τ=0.310 (val F1=0.2037)
  Directional -> Accuracy: 0.4464, MCC: -0.1588, F1: 0.5634

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.44170 | val 4.16355
  Epoch 016 - train 0.32157 | val 3.09722
  Classification -> best τ=0.740 (val F1=0.3554)
  Directional -> Accuracy: 0.5179, MCC: 0.0226, F1: 0.3721

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.59134 | val 2.71470
  Epoch 016 - train 0.41522 | val 3.45659
  Classification -> best τ=0.195 (val F1=0.1976)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.47544 | val 3.91192
  Epoch 016 - train 0.33140 | val 10.64187
  Classification -> best τ=0.570 (val F1=0.1829)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.61797 | val 1.52968

[I 2026-02-24 22:35:19,675] Trial 12 finished with value: 0.25726033636329926 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.4, 'dropout': 0.30000000000000004, 'batch_size': 16, 'learning_rate': 0.008785569013967882, 'weight_decay': 1.9003057978659247e-06, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 1.942640299723831, 'early_stopping_min_delta': 0.003400842774678895}. Best is trial 12 with value: 0.25726033636329926.

  Epoch 020 - train 0.44956 | val 5.59803
  Classification -> best τ=0.200 (val F1=0.3180)
  Directional -> Accuracy: 0.4590, MCC: -0.0745, F1: 0.6118

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.25726033636329926
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.70229 | val 0.89707
  Epoch 020 - train 0.35178 | val 3.80228
  Classification -> best τ=0.650 (val F1=0.3013)
  Directional -> Accuracy: 0.4737, MCC: -0.0206, F1: 0.5238

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.45478 | val 0.98014
  Epoch 016 - train 0.31811 | val 1.65813
  Classification -> best τ=0.525 (val F1=0.2583)
  Directional -> Accuracy: 0.5778, MCC: 0.0732, F1: 0.6984

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.55896 | val 0.78078
  Epoch 018 - train 0.38521 | val 1.51815
  Classification -> best τ=0.440 (val F1=0.3308)
  Directional -> Accuracy: 0.5532, MCC: 0.0872, F1: 0.6441

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.62441 | val 2.51715
  Epoch 016 - train 0.44045 | val 1.29851
  Classification -> best τ=0.410 (val F1=0.1181)
  Directional -> Accuracy: 0.4933, MCC: -0.0727, F1: 0.6122

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.44896 | val 1.78539
  Epoch 016 - train 0.34916 | val 1.44462
  Classification -> best τ=0.405 (val F1=0.3724)
  Directional -> Accuracy: 0.6078, MCC: 0.2092, F1: 0.6774

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.42707 | val 2.93409
  Epoch 017 - train 0.21886 | val 3.75734
  Classification -> best τ=0.505 (val F1=0.2928)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.57596 | val 1.76250
  Epoch 016 - train 0.40970 | val 1.44424
  Classification -> best τ=0.335 (val F1=0.1922)
  Directional -> Accuracy: 0.4348, MCC: 0.1428, F1: 0.5895

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.43480 | val 1.48512
  Epoch 016 - train 0.23921 | val 2.14758
  Classification -> best τ=0.490 (val F1=0.1214)
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.5902

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.49034 | val 3.56038
  Epoch 016 - train 0.34768 | val 3.75877
  Classification -> best τ=0.605 (val F1=0.4249)
  Directional -> Accuracy: 0.6327, MCC: 0.2887, F1: 0.3571

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.50337 | val 2.31807
  Epoch 016 - train 0.38893 | val 1.81195
  Classification -> best τ=0.480 (val F1=0.2018)
  Directional -> Accuracy: 0.4571, MCC: -0.0908, F1: 0.4062

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.50253 | val 3.41768
  Epoch 016 - train 0.35904 | val 5.90875
  Classification -> best τ=0.770 (val F1=0.2010)
  Directional -> Accuracy: 0.6600, MCC: 0.3411, F1: 0.4848

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.51305 | val 2.30059
  Epoch 016 - train 0.47116 | val 2.61359
  Classification -> best τ=0.510 (val F1=0.2769)
  Directional -> Accuracy: 0.6552, MCC: 0.3306, F1: 0.5833

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.46420 | val 1.02861
  Epoch 017 - train 0.33539 | val 0.71421
  Classification -> best τ=0.570 (val F1=0.3341)
  Directional -> Accuracy: 0.4048, MCC: -0.1961, F1: 0.3590

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.57811 | val 1.59410
  Epoch 016 - train 0.43734 | val 5.86557
  Classification -> best τ=0.335 (val F1=0.2878)
  Directional -> Accuracy: 0.5500, MCC: 0.1292, F1: 0.6582

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.53964 | val 1.05151
  Epoch 016 - train 0.44272 | val 2.69706
  Classification -> best τ=0.630 (val F1=0.2160)
  Directional -> Accuracy: 0.4808, MCC: -0.1017, F1: 0.2286

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.60748 | val 2.84676
  Epoch 016 - train 0.40588 | val 2.74307
  Classification -> best τ=0.560 (val F1=0.1400)
  Directional -> Accuracy: 0.4638, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.58744 | val 2.63041
  Epoch 016 - train 0.42414 | val 3.82354
  Classification -> best τ=0.285 (val F1=0.1486)
  Directional -> Accuracy: 0.6102, MCC: 0.0171, F1: 0.7473

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.54300 | val 1.49592
  Epoch 016 - train 0.43579 | val 2.06232
  Classification -> best τ=0.420 (val F1=0.0667)
  Directional -> Accuracy: 0.3600, MCC: -0.2128, F1: 0.2500

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.50348 | val 3.47545
  Epoch 016 - train 0.36775 | val 4.87239
  Classification -> best τ=0.600 (val F1=0.2234)
  Directional -> Accuracy: 0.4615, MCC: 0.0914, F1: 0.2222

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.52055 | val 1.56745
  Epoch 016 - train 0.35114 | val 2.90269
  Classification -> best τ=0.515 (val F1=0.2609)
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.50123 | val 2.45579
  Epoch 016 - train 0.39581 | val 2.51114
  Classification -> best τ=0.400 (val F1=0.2814)
  Directional -> Accuracy: 0.5319, MCC: 0.2722, F1: 0.4211

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.53098 | val 2.14610
  Epoch 016 - train 0.44550 | val 5.31204
  Classification -> best τ=0.440 (val F1=0.0864)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6526

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.51397 | val 2.51159
  Epoch 016 - train 0.39157 | val 3.65579
  Classification -> best τ=0.750 (val F1=0.3187)
  Directional -> Accuracy: 0.4655, MCC: 0.0453, F1: 0.2439

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.54511 | val 2.36199
  Epoch 017 - train 0.43111 | val 2.58644
  Classification -> best τ=0.365 (val F1=0.1242)
  Directional -> Accuracy: 0.4923, MCC: 0.0075, F1: 0.5823

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.53394 | val 1.01475
  Epoch 016 - train 0.37495 | val 3.56291
  Classification -> best τ=0.565 (val F1=0.4297)
  Directional -> Accuracy: 0.4821, MCC: 0.1096, F1: 0.1714

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.47318 | val 4.86268
  Epoch 016 - train 0.18589 | val 4.54643
  Classification -> best τ=0.655 (val F1=0.2097)
  Directional -> Accuracy: 0.4348, MCC: -0.2496, F1: 0.1333

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.51297 | val 3.55280
  Epoch 016 - train 0.39918 | val 5.55018
  Classification -> best τ=0.605 (val F1=0.0323)
  Directional -> Accuracy: 0.4762, MCC: 0.0000, F1: 0.4211

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.51128 | val 1.96638
  Epoch 016 - train 0.29961 | val 2.85668
  Classification -> best τ=0.385 (val F1=0.1656)
  Directional -> Accuracy: 0.5439, MCC: 0.2218, F1: 0.3810

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.38949 | val 1.15959
  Epoch 017 - train 0.27674 | val 0.88817
  Classification -> best τ=0.560 (val F1=0.3278)
  Directional -> Accuracy: 0.4634, MCC: -0.1617, F1: 0.6071

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.41599 | val 1.60222
  Epoch 016 - train 0.28656 | val 2.45802
  Classification -> best τ=0.580 (val F1=0.2814)
  Directional -> Accuracy: 0.5116, MCC: 0.0261, F1: 0.5333

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.39837 | val 2.45874
  Epoch 018 - train 0.19352 | val 3.96343
  Classification -> best τ=0.535 (val F1=0.1377)
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.47036 | val 1.41186
  Epoch 016 - train 0.30155 | val 1.72579
  Classification -> best τ=0.385 (val F1=0.3850)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.56106 | val 0.85484
  Epoch 018 - train 0.45969 | val 1.56346
  Classification -> best τ=0.545 (val F1=0.3824)
  Directional -> Accuracy: 0.5342, MCC: 0.1602, F1: 0.4138

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.39040 | val 1.96820
  Epoch 017 - train 0.19828 | val 3.97400
  Classification -> best τ=0.505 (val F1=0.0967)
  Directional -> Accuracy: 0.4865, MCC: -0.0327, F1: 0.4242

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.47020 | val 4.06802
  Epoch 016 - train 0.34509 | val 4.45143
  Classification -> best τ=0.445 (val F1=0.1902)
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.51393 | val 1.74052
  Epoch 016 - train 0.36735 | val 2.29421
  Classification -> best τ=0.260 (val F1=0.4100)
  Directional -> Accuracy: 0.6364, MCC: 0.3468, F1: 0.6000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.44528 | val 5.47071
  Epoch 016 - train 0.34350 | val 7.21571
  Classification -> best τ=0.545 (val F1=0.2741)
  Directional -> Accuracy: 0.5952, MCC: 0.2259, F1: 0.5143

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.50854 | val 2.13177
  Epoch 017 - train 0.31081 | val 4.53652
  Classification -> best τ=0.360 (val F1=0.3280)
  Directional -> Accuracy: 0.4107, MCC: -0.1664, F1: 0.4590

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.39591 | val 2.75692
  Epoch 016 - train 0.27122 | val 3.73367
  Classification -> best τ=0.640 (val F1=0.3916)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.40496 | val 1.17579
  Epoch 016 - train 0.32493 | val 2.53168
  Classification -> best τ=0.520 (val F1=0.2417)
  Directional -> Accuracy: 0.6122, MCC: 0.0518, F1: 0.2400

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.36157 | val 2.17036
  Epoch 016 - train 0.21027 | val 2.86065
  Classification -> best τ=0.500 (val F1=0.0585)
  Directional -> Accuracy: 0.4054, MCC: -0.1716, F1: 0.2667

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.57516 | val 4.18530
  Epoch 016 - train 0.29556 | val 9.62544
  Classification -> best τ=0.230 (val F1=0.2655)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.45987 | val 2.00782
  Epoch 017 - train 0.24691 | val 1.93909
  Classification -> best τ=0.415 (val F1=0.2739)
  Directional -> Accuracy: 0.4565, MCC: -0.0961, F1: 0.5098

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.40772 | val 0.81381
  Epoch 020 - train 0.15253 | val 0.89304
  Classification -> best τ=0.620 (val F1=0.7906)
  Directional -> Accuracy: 0.4651, MCC: -0.0905, F1: 0.5306

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.36204 | val 2.25446
  Epoch 016 - train 0.24248 | val 2.19850
  Classification -> best τ=0.485 (val F1=0.3410)
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.54243 | val 1.64792
  Epoch 016 - train 0.50342 | val 3.75159
  Classification -> best τ=0.410 (val F1=0.0731)
  Directional -> Accuracy: 0.3214, MCC: -0.3523, F1: 0.2400

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.50230 | val 1.24198
  Epoch 016 - train 0.32458 | val 5.56663
  Classification -> best τ=0.755 (val F1=0.3535)
  Directional -> Accuracy: 0.5357, MCC: 0.1303, F1: 0.6486

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.62296 | val 2.68074
  Epoch 016 - train 0.43315 | val 5.16144
  Classification -> best τ=0.255 (val F1=0.1866)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.46981 | val 4.13802
  Epoch 016 - train 0.34764 | val 8.51250
  Classification -> best τ=0.670 (val F1=0.2060)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.54142 | val 1.11040

[I 2026-02-24 22:36:22,243] Trial 13 finished with value: 0.2544014534224332 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.4, 'dropout': 0.30000000000000004, 'batch_size': 16, 'learning_rate': 0.00805552301175695, 'weight_decay': 1.7092649356766799e-06, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 1.9950747011416714, 'early_stopping_min_delta': 0.009823152404660224}. Best is trial 12 with value: 0.25726033636329926.

  Epoch 016 - train 0.42596 | val 5.97294
  Classification -> best τ=0.500 (val F1=0.3074)
  Directional -> Accuracy: 0.4918, MCC: -0.0781, F1: 0.1622

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2544014534224332
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.50604 | val 0.85451
  Epoch 020 - train 0.45120 | val 1.15953
  Classification -> best τ=0.550 (val F1=0.2799)
  Directional -> Accuracy: 0.4474, MCC: -0.0174, F1: 0.6111

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.48895 | val 2.37755
  Epoch 016 - train 0.42231 | val 3.58370
  Classification -> best τ=0.485 (val F1=0.1236)
  Directional -> Accuracy: 0.6444, MCC: 0.2475, F1: 0.7419

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.51795 | val 1.06742
  Epoch 017 - train 0.40995 | val 1.17956
  Classification -> best τ=0.555 (val F1=0.2727)
  Directional -> Accuracy: 0.5532, MCC: 0.1751, F1: 0.4000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.54719 | val 3.26907
  Epoch 016 - train 0.45649 | val 1.95307
  Classification -> best τ=0.260 (val F1=0.2470)
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.46492 | val 1.12387
  Epoch 017 - train 0.36606 | val 2.68219
  Classification -> best τ=0.505 (val F1=0.4255)
  Directional -> Accuracy: 0.7647, MCC: 0.5272, F1: 0.7857

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.42048 | val 1.20055
  Epoch 016 - train 0.32416 | val 2.76219
  Classification -> best τ=0.595 (val F1=0.2582)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.53353 | val 1.63412
  Epoch 016 - train 0.47105 | val 1.28859
  Classification -> best τ=0.410 (val F1=0.2723)
  Directional -> Accuracy: 0.5362, MCC: 0.0937, F1: 0.5152

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.44057 | val 0.88275
  Epoch 020 - train 0.30641 | val 1.80933
  Classification -> best τ=0.475 (val F1=0.2218)
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.48899 | val 1.27324
  Epoch 016 - train 0.40969 | val 1.64873
  Classification -> best τ=0.520 (val F1=0.3461)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.50266 | val 1.15311
  Epoch 016 - train 0.39458 | val 1.40657
  Classification -> best τ=0.400 (val F1=0.1958)
  Directional -> Accuracy: 0.4429, MCC: 0.0407, F1: 0.5979

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.49497 | val 3.38434
  Epoch 016 - train 0.40061 | val 4.80007
  Classification -> best τ=0.610 (val F1=0.1985)
  Directional -> Accuracy: 0.5200, MCC: 0.0152, F1: 0.4000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.50691 | val 1.60346
  Epoch 016 - train 0.44391 | val 2.04098
  Classification -> best τ=0.375 (val F1=0.1469)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.44893 | val 1.20955
  Epoch 016 - train 0.38802 | val 1.39176
  Classification -> best τ=0.480 (val F1=0.1908)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.56220 | val 0.95087
  Epoch 016 - train 0.48650 | val 1.33388
  Classification -> best τ=0.495 (val F1=0.3141)
  Directional -> Accuracy: 0.6000, MCC: 0.2041, F1: 0.5556

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.51014 | val 1.37620
  Epoch 016 - train 0.39248 | val 1.48540
  Classification -> best τ=0.685 (val F1=0.2673)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.50365 | val 1.44623
  Epoch 016 - train 0.44865 | val 1.92366
  Classification -> best τ=0.455 (val F1=0.2708)
  Directional -> Accuracy: 0.5797, MCC: 0.2293, F1: 0.7184

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.56656 | val 3.27965
  Epoch 016 - train 0.46860 | val 4.70050
  Classification -> best τ=0.375 (val F1=0.1336)
  Directional -> Accuracy: 0.6441, MCC: 0.1703, F1: 0.7789

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.50448 | val 1.86356
  Epoch 016 - train 0.43039 | val 1.88010
  Classification -> best τ=0.570 (val F1=0.1560)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.51064 | val 4.07947
  Epoch 016 - train 0.48150 | val 4.77248
  Classification -> best τ=0.320 (val F1=0.2166)
  Directional -> Accuracy: 0.5385, MCC: 0.1561, F1: 0.4828

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.48454 | val 0.91391
  Epoch 016 - train 0.41272 | val 1.34605
  Classification -> best τ=0.510 (val F1=0.2952)
  Directional -> Accuracy: 0.4800, MCC: 0.0969, F1: 0.1333

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.48237 | val 1.81427
  Epoch 016 - train 0.38759 | val 3.80725
  Classification -> best τ=0.460 (val F1=0.1931)
  Directional -> Accuracy: 0.4681, MCC: 0.1702, F1: 0.2857

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.51072 | val 2.49715
  Epoch 016 - train 0.45021 | val 3.45786
  Classification -> best τ=0.510 (val F1=0.2361)
  Directional -> Accuracy: 0.5303, MCC: 0.1054, F1: 0.2051

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.52815 | val 1.14740
  Epoch 016 - train 0.46329 | val 1.79700
  Classification -> best τ=0.500 (val F1=0.1669)
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.51299 | val 1.72314
  Epoch 020 - train 0.42259 | val 1.77836
  Classification -> best τ=0.335 (val F1=0.3376)
  Directional -> Accuracy: 0.4769, MCC: 0.0000, F1: 0.6458

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.48397 | val 1.19134
  Epoch 017 - train 0.39732 | val 1.49199
  Classification -> best τ=0.570 (val F1=0.4330)
  Directional -> Accuracy: 0.6250, MCC: 0.3104, F1: 0.5714

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.49693 | val 1.69755
  Epoch 016 - train 0.41911 | val 1.89203
  Classification -> best τ=0.540 (val F1=0.1585)
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.51263 | val 2.32030
  Epoch 016 - train 0.46402 | val 2.89872
  Classification -> best τ=0.470 (val F1=0.1925)
  Directional -> Accuracy: 0.4524, MCC: -0.0829, F1: 0.4651

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.51946 | val 0.91149
  Epoch 016 - train 0.43448 | val 1.35204
  Classification -> best τ=0.475 (val F1=0.2940)
  Directional -> Accuracy: 0.4912, MCC: 0.2083, F1: 0.1714

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.48041 | val 0.85302
  Epoch 016 - train 0.43725 | val 0.89894
  Classification -> best τ=0.505 (val F1=0.1183)
  Directional -> Accuracy: 0.6098, MCC: 0.2421, F1: 0.5789

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.51984 | val 0.91239
  Epoch 016 - train 0.39784 | val 1.46096
  Classification -> best τ=0.470 (val F1=0.3059)
  Directional -> Accuracy: 0.5116, MCC: 0.0397, F1: 0.6038

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.52255 | val 1.03896
  Epoch 018 - train 0.41747 | val 2.08277
  Classification -> best τ=0.635 (val F1=0.1204)
  Directional -> Accuracy: 0.5814, MCC: 0.1503, F1: 0.6400

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.50520 | val 1.24812
  Epoch 016 - train 0.37872 | val 1.55624
  Classification -> best τ=0.585 (val F1=0.2399)
  Directional -> Accuracy: 0.4600, MCC: -0.1839, F1: 0.6087

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.52051 | val 1.01719
  Epoch 018 - train 0.42245 | val 1.11731
  Classification -> best τ=0.335 (val F1=0.3112)
  Directional -> Accuracy: 0.5479, MCC: 0.1207, F1: 0.5352

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.52138 | val 1.23220
  Epoch 016 - train 0.37835 | val 2.16402
  Classification -> best τ=0.515 (val F1=0.2588)
  Directional -> Accuracy: 0.6216, MCC: 0.2498, F1: 0.5333

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.46132 | val 2.27960
  Epoch 016 - train 0.36823 | val 3.53268
  Classification -> best τ=0.605 (val F1=0.2506)
  Directional -> Accuracy: 0.4318, MCC: -0.1288, F1: 0.5098

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.51268 | val 0.88356
  Epoch 016 - train 0.42307 | val 1.15235
  Classification -> best τ=0.375 (val F1=0.3855)
  Directional -> Accuracy: 0.6364, MCC: 0.3659, F1: 0.5862

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.46420 | val 2.11034
  Epoch 016 - train 0.33595 | val 3.61892
  Classification -> best τ=0.570 (val F1=0.2652)
  Directional -> Accuracy: 0.4524, MCC: -0.1058, F1: 0.0800

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.45599 | val 1.78935
  Epoch 016 - train 0.36456 | val 1.62200
  Classification -> best τ=0.325 (val F1=0.2026)
  Directional -> Accuracy: 0.5179, MCC: 0.0878, F1: 0.6087

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.39994 | val 2.35702
  Epoch 016 - train 0.31319 | val 2.35296
  Classification -> best τ=0.750 (val F1=0.2441)
  Directional -> Accuracy: 0.4130, MCC: -0.0062, F1: 0.1818

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.48452 | val 0.64376
  Epoch 020 - train 0.35711 | val 0.69690
  Classification -> best τ=0.230 (val F1=0.4188)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.51222 | val 1.21816
  Epoch 016 - train 0.38663 | val 1.78499
  Classification -> best τ=0.525 (val F1=0.2306)
  Directional -> Accuracy: 0.5946, MCC: 0.1716, F1: 0.6809

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.49598 | val 2.34803
  Epoch 016 - train 0.39253 | val 3.71356
  Classification -> best τ=0.490 (val F1=0.3002)
  Directional -> Accuracy: 0.5333, MCC: 0.2014, F1: 0.6789

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.49433 | val 0.72097
  Epoch 016 - train 0.38597 | val 0.79556
  Classification -> best τ=0.480 (val F1=0.3560)
  Directional -> Accuracy: 0.5217, MCC: 0.0496, F1: 0.5000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.49902 | val 0.91083
  Epoch 016 - train 0.36525 | val 0.93326
  Classification -> best τ=0.535 (val F1=0.1180)
  Directional -> Accuracy: 0.6047, MCC: 0.1813, F1: 0.6792

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.46773 | val 1.23315
  Epoch 016 - train 0.32770 | val 1.79612
  Classification -> best τ=0.425 (val F1=0.2605)
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.52999 | val 2.66695
  Epoch 016 - train 0.45759 | val 3.39633
  Classification -> best τ=0.465 (val F1=0.2483)
  Directional -> Accuracy: 0.5714, MCC: 0.2244, F1: 0.4286

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.50525 | val 1.70720
  Epoch 016 - train 0.41997 | val 2.79849
  Classification -> best τ=0.650 (val F1=0.3666)
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.48317 | val 2.53805
  Epoch 016 - train 0.42896 | val 2.91068
  Classification -> best τ=0.420 (val F1=0.3040)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.44997 | val 3.24144
  Epoch 016 - train 0.34861 | val 4.35662
  Classification -> best τ=0.615 (val F1=0.1633)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.55407 | val 1.43156

[I 2026-02-24 22:37:25,844] Trial 14 finished with value: 0.25077154909313126 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.0019124220671635586, 'weight_decay': 4.773134510754205e-06, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 1.6871091706881791, 'early_stopping_min_delta': 0.00933134423471773}. Best is trial 12 with value: 0.25726033636329926.

  Epoch 016 - train 0.44445 | val 2.12785
  Classification -> best τ=0.460 (val F1=0.2254)
  Directional -> Accuracy: 0.4590, MCC: -0.2042, F1: 0.0571

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.25077154909313126
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 15
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.52104 | val 2.23628
  Epoch 017 - train 0.50172 | val 2.83173
  Classification -> best τ=0.525 (val F1=0.1084)
  Directional -> Accuracy: 0.4416, MCC: -0.1236, F1: 0.3944

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.41611 | val 1.30942
  Epoch 016 - train 0.28964 | val 2.04326
  Classification -> best τ=0.495 (val F1=0.0604)
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 16). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.44813 | val 1.13692
  Epoch 016 - train 0.39844 | val 1.84037
  Classification -> best τ=0.545 (val F1=0.1399)
  Directional -> Accuracy: 0.4583, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.53310 | val 2.54532
  Epoch 016 - train 0.50384 | val 1.79397
  Classification -> best τ=0.455 (val F1=0.1255)
  Directional -> Accuracy: 0.4933, MCC: -0.0022, F1: 0.4865

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.43620 | val 1.13714
  Epoch 018 - train 0.27084 | val 1.67851
  Classification -> best τ=0.570 (val F1=0.4245)
  Directional -> Accuracy: 0.7308, MCC: 0.4629, F1: 0.7407

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.35077 | val 4.37765
  Epoch 016 - train 0.26261 | val 7.32249
  Classification -> best τ=0.570 (val F1=0.3119)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.52289 | val 0.93693
  Epoch 016 - train 0.38112 | val 1.35590
  Classification -> best τ=0.415 (val F1=0.2054)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.5714

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 16). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.36868 | val 6.13032
  Epoch 016 - train 0.25458 | val 10.47756
  Classification -> best τ=0.525 (val F1=0.1512)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.45074 | val 1.35221
  Epoch 016 - train 0.36025 | val 1.97570
  Classification -> best τ=0.520 (val F1=0.2644)
  Directional -> Accuracy: 0.4390, MCC: 0.2134, F1: 0.5660

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 16). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 16). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.54734 | val 1.89227
  Epoch 016 - train 0.37398 | val 2.35758
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4366, MCC: 0.0000, F1: 0.6078

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.47839 | val 3.01734
  Epoch 016 - train 0.37724 | val 2.02963
  Classification -> best τ=0.540 (val F1=0.1798)
  Directional -> Accuracy: 0.5098, MCC: 0.1289, F1: 0.6479

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.49011 | val 1.45982
  Epoch 016 - train 0.41250 | val 1.60056
  Classification -> best τ=0.425 (val F1=0.2645)
  Directional -> Accuracy: 0.5085, MCC: 0.0000, F1: 0.6742

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.41600 | val 4.88942
  Epoch 016 - train 0.33370 | val 5.94049
  Classification -> best τ=0.475 (val F1=0.2091)
  Directional -> Accuracy: 0.5349, MCC: -0.1373, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.54466 | val 1.02219
  Epoch 018 - train 0.41847 | val 1.96289
  Classification -> best τ=0.290 (val F1=0.2965)
  Directional -> Accuracy: 0.5410, MCC: 0.1155, F1: 0.6744

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.45830 | val 8.56486
  Epoch 016 - train 0.39135 | val 11.32329
  Classification -> best τ=0.600 (val F1=0.2798)
  Directional -> Accuracy: 0.5283, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.46710 | val 2.18702
  Epoch 016 - train 0.33642 | val 2.29986
  Classification -> best τ=0.670 (val F1=0.2342)
  Directional -> Accuracy: 0.5143, MCC: 0.0587, F1: 0.4516

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.51038 | val 1.63362
  Epoch 016 - train 0.43825 | val 1.98229
  Classification -> best τ=0.460 (val F1=0.0062)
  Directional -> Accuracy: 0.4833, MCC: -0.0504, F1: 0.5507

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.50735 | val 1.82978
  Epoch 016 - train 0.44768 | val 1.85373
  Classification -> best τ=0.520 (val F1=0.1242)
  Directional -> Accuracy: 0.5921, MCC: 0.0730, F1: 0.7103

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.49555 | val 1.24322
  Epoch 016 - train 0.39813 | val 2.67184
  Classification -> best τ=0.420 (val F1=0.1429)
  Directional -> Accuracy: 0.5758, MCC: 0.2205, F1: 0.5484

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 16). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.42473 | val 0.92651
  Epoch 016 - train 0.35115 | val 2.07495
  Classification -> best τ=0.555 (val F1=0.2434)
  Directional -> Accuracy: 0.4605, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.41958 | val 4.80102
  Epoch 016 - train 0.32224 | val 5.99598
  Classification -> best τ=0.445 (val F1=0.2044)
  Directional -> Accuracy: 0.4375, MCC: 0.1233, F1: 0.2286

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.51124 | val 3.41360
  Epoch 016 - train 0.52916 | val 4.01363
  Classification -> best τ=0.620 (val F1=0.2264)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.50903 | val 1.09764
  Epoch 016 - train 0.34298 | val 1.87399
  Classification -> best τ=0.535 (val F1=0.2272)
  Directional -> Accuracy: 0.5690, MCC: 0.1545, F1: 0.5763

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.48784 | val 5.09526
  Epoch 016 - train 0.34249 | val 6.11773
  Classification -> best τ=0.365 (val F1=0.2054)
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.50134 | val 0.91833
  Epoch 017 - train 0.35755 | val 1.46024
  Classification -> best τ=0.570 (val F1=0.4649)
  Directional -> Accuracy: 0.5357, MCC: 0.1728, F1: 0.3810

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.32093 | val 3.03556
  Epoch 016 - train 0.24804 | val 4.97068
  Classification -> best τ=0.465 (val F1=0.0601)
  Directional -> Accuracy: 0.5532, MCC: -0.0178, F1: 0.1600

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.50114 | val 1.80236
  Epoch 016 - train 0.37685 | val 1.95298
  Classification -> best τ=0.535 (val F1=0.0364)
  Directional -> Accuracy: 0.4884, MCC: -0.0680, F1: 0.5769

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.50377 | val 1.06482
  Epoch 016 - train 0.39756 | val 1.44478
  Classification -> best τ=0.465 (val F1=0.2499)
  Directional -> Accuracy: 0.5172, MCC: 0.1923, F1: 0.2632

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.42497 | val 0.84616
  Epoch 016 - train 0.32126 | val 1.00631
  Classification -> best τ=0.490 (val F1=0.3203)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.7077

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.43077 | val 1.75447
  Epoch 016 - train 0.27023 | val 2.47606
  Classification -> best τ=0.520 (val F1=0.1869)
  Directional -> Accuracy: 0.5455, MCC: 0.2182, F1: 0.1667

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.43426 | val 2.30539
  Epoch 016 - train 0.32143 | val 3.13629
  Classification -> best τ=0.490 (val F1=0.0296)
  Directional -> Accuracy: 0.5682, MCC: 0.1329, F1: 0.5957

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.40722 | val 1.52128
  Epoch 016 - train 0.24401 | val 1.78527
  Classification -> best τ=0.575 (val F1=0.2320)
  Directional -> Accuracy: 0.4118, MCC: -0.1941, F1: 0.4828

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.48072 | val 3.12887
  Epoch 016 - train 0.43327 | val 3.72747
  Classification -> best τ=0.580 (val F1=0.2739)
  Directional -> Accuracy: 0.4324, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.38056 | val 3.60811
  Epoch 016 - train 0.23084 | val 5.80255
  Classification -> best τ=0.455 (val F1=0.4223)
  Directional -> Accuracy: 0.4474, MCC: -0.1443, F1: 0.5882

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.46681 | val 2.43323
  Epoch 016 - train 0.35323 | val 3.03874
  Classification -> best τ=0.555 (val F1=0.2306)
  Directional -> Accuracy: 0.5111, MCC: -0.0066, F1: 0.3529

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.49981 | val 1.28227
  Epoch 016 - train 0.38686 | val 1.36117
  Classification -> best τ=0.330 (val F1=0.3521)
  Directional -> Accuracy: 0.5672, MCC: 0.0884, F1: 0.6588

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.38912 | val 1.68816
  Epoch 019 - train 0.30017 | val 1.71532
  Classification -> best τ=0.505 (val F1=0.3038)
  Directional -> Accuracy: 0.6512, MCC: 0.3596, F1: 0.5455

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.51596 | val 1.37802
  Epoch 016 - train 0.37854 | val 1.27629
  Classification -> best τ=0.450 (val F1=0.2423)
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.39411 | val 3.51246
  Epoch 016 - train 0.25227 | val 4.60579
  Classification -> best τ=0.630 (val F1=0.2676)
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 16). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.36851 | val 1.30207
  Epoch 016 - train 0.27670 | val 1.81192
  Classification -> best τ=0.510 (val F1=0.5422)
  Directional -> Accuracy: 0.4000, MCC: 0.1683, F1: 0.5385

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.40376 | val 1.95175
  Epoch 016 - train 0.28274 | val 2.85671
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.7000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 16). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.51338 | val 2.58137
  Epoch 016 - train 0.38518 | val 4.32210
  Classification -> best τ=0.410 (val F1=0.3073)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.49805 | val 1.88122
  Epoch 016 - train 0.33309 | val 3.08358
  Classification -> best τ=0.515 (val F1=0.1674)
  Directional -> Accuracy: 0.5319, MCC: 0.1036, F1: 0.3125

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.33591 | val 2.74599
  Epoch 016 - train 0.23681 | val 4.51213
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.32702 | val 1.24431
  Epoch 016 - train 0.18671 | val 2.18851
  Classification -> best τ=0.525 (val F1=0.0675)
  Directional -> Accuracy: 0.5750, MCC: 0.3954, F1: 0.6222

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.51574 | val 2.61482
  Epoch 016 - train 0.46371 | val 4.98482
  Classification -> best τ=0.420 (val F1=0.3465)
  Directional -> Accuracy: 0.6140, MCC: 0.2124, F1: 0.6765

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.41835 | val 2.85506
  Epoch 016 - train 0.34690 | val 3.02435
  Classification -> best τ=0.585 (val F1=0.3836)
  Directional -> Accuracy: 0.4912, MCC: 0.0000, F1: 0.5538

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.53003 | val 1.47698
  Epoch 016 - train 0.41364 | val 1.44332
  Classification -> best τ=0.465 (val F1=0.2368)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.43670 | val 1.32320
  Epoch 016 - train 0.34741 | val 1.39434
  Classification -> best τ=0.555 (val F1=0.2218)
  Directional -> Accuracy: 0.5439, MCC: 0.1941, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.56541 | val 0.76891

[I 2026-02-24 22:38:19,676] Trial 15 finished with value: 0.2144003854233161 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 15, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.4, 'dropout': 0.30000000000000004, 'batch_size': 16, 'learning_rate': 0.0028049266512084783, 'weight_decay': 6.703945165026237e-07, 'lr_patience': 7, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 1.7202830310523192, 'early_stopping_min_delta': 0.009819437023864928}. Best is trial 12 with value: 0.25726033636329926.

  Epoch 016 - train 0.43242 | val 1.21308
  Classification -> best τ=0.515 (val F1=0.1389)
  Directional -> Accuracy: 0.4677, MCC: -0.0722, F1: 0.4000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2144003854233161
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.52161 | val 1.04135
  Epoch 016 - train 0.44137 | val 0.82063
  Classification -> best τ=0.665 (val F1=0.2510)
  Directional -> Accuracy: 0.5526, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.49884 | val 2.45332
  Epoch 016 - train 0.40934 | val 3.05718
  Classification -> best τ=0.450 (val F1=0.0510)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.54814 | val 1.10548
  Epoch 016 - train 0.47512 | val 1.21427
  Classification -> best τ=0.610 (val F1=0.2727)
  Directional -> Accuracy: 0.4681, MCC: -0.0135, F1: 0.0741

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.57006 | val 1.88770
  Epoch 016 - train 0.48929 | val 1.07497
  Classification -> best τ=0.375 (val F1=0.1964)
  Directional -> Accuracy: 0.5067, MCC: -0.0248, F1: 0.6022

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.49911 | val 0.94189
  Epoch 017 - train 0.42302 | val 2.05744
  Classification -> best τ=0.460 (val F1=0.4457)
  Directional -> Accuracy: 0.7255, MCC: 0.4479, F1: 0.7500

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.44320 | val 1.14163
  Epoch 017 - train 0.35131 | val 1.92412
  Classification -> best τ=0.585 (val F1=0.2928)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.57786 | val 1.00143
  Epoch 016 - train 0.48794 | val 1.35091
  Classification -> best τ=0.330 (val F1=0.1655)
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.51754 | val 1.00012
  Epoch 016 - train 0.37538 | val 1.61815
  Classification -> best τ=0.540 (val F1=0.1729)
  Directional -> Accuracy: 0.5116, MCC: 0.1075, F1: 0.5714

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.51121 | val 0.99230
  Epoch 019 - train 0.42261 | val 1.51795
  Classification -> best τ=0.535 (val F1=0.4249)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.51346 | val 0.76352
  Epoch 016 - train 0.42846 | val 0.84515
  Classification -> best τ=0.350 (val F1=0.2956)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.53768 | val 3.91586
  Epoch 016 - train 0.42361 | val 4.79291
  Classification -> best τ=0.590 (val F1=0.3563)
  Directional -> Accuracy: 0.5200, MCC: 0.1739, F1: 0.6471

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.54271 | val 1.49432
  Epoch 016 - train 0.50003 | val 1.59457
  Classification -> best τ=0.410 (val F1=0.1469)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.44285 | val 1.17178
  Epoch 016 - train 0.34948 | val 0.84988
  Classification -> best τ=0.485 (val F1=0.2647)
  Directional -> Accuracy: 0.5238, MCC: 0.0673, F1: 0.5455

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.58089 | val 0.71968
  Epoch 017 - train 0.47284 | val 0.72181
  Classification -> best τ=0.375 (val F1=0.3493)
  Directional -> Accuracy: 0.5667, MCC: 0.1667, F1: 0.6667

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.49404 | val 1.70760
  Epoch 016 - train 0.44871 | val 1.56069
  Classification -> best τ=0.580 (val F1=0.2160)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.53788 | val 1.58933
  Epoch 016 - train 0.43047 | val 2.01991
  Classification -> best τ=0.380 (val F1=0.2708)
  Directional -> Accuracy: 0.5652, MCC: 0.1858, F1: 0.7115

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.54759 | val 3.22133
  Epoch 016 - train 0.49676 | val 3.83073
  Classification -> best τ=0.375 (val F1=0.1905)
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.52023 | val 1.07862
  Epoch 016 - train 0.47125 | val 1.11155
  Classification -> best τ=0.535 (val F1=0.1923)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.51881 | val 3.32342
  Epoch 016 - train 0.46571 | val 3.67260
  Classification -> best τ=0.515 (val F1=0.1301)
  Directional -> Accuracy: 0.4615, MCC: 0.0914, F1: 0.2222

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.52456 | val 2.19978
  Epoch 016 - train 0.43554 | val 2.97941
  Classification -> best τ=0.490 (val F1=0.2468)
  Directional -> Accuracy: 0.5067, MCC: 0.1411, F1: 0.2449

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.50496 | val 1.03421
  Epoch 016 - train 0.40266 | val 1.45819
  Classification -> best τ=0.405 (val F1=0.2338)
  Directional -> Accuracy: 0.5319, MCC: -0.0598, F1: 0.6562

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.54030 | val 2.53092
  Epoch 016 - train 0.51782 | val 4.15483
  Classification -> best τ=0.620 (val F1=0.1950)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.57344 | val 0.87591
  Epoch 016 - train 0.47089 | val 1.17821
  Classification -> best τ=0.505 (val F1=0.1669)
  Directional -> Accuracy: 0.4483, MCC: 0.0461, F1: 0.1111

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.53569 | val 2.34737
  Epoch 016 - train 0.42814 | val 2.46993
  Classification -> best τ=0.460 (val F1=0.1693)
  Directional -> Accuracy: 0.5385, MCC: 0.1091, F1: 0.6154

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.52743 | val 1.09593
  Epoch 017 - train 0.38987 | val 1.43392
  Classification -> best τ=0.535 (val F1=0.4057)
  Directional -> Accuracy: 0.5357, MCC: 0.1728, F1: 0.3810

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.50547 | val 1.14377
  Epoch 016 - train 0.40821 | val 1.76111
  Classification -> best τ=0.445 (val F1=0.2035)
  Directional -> Accuracy: 0.5000, MCC: 0.1654, F1: 0.6230

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.54395 | val 1.93695
  Epoch 016 - train 0.46526 | val 3.23242
  Classification -> best τ=0.495 (val F1=0.2582)
  Directional -> Accuracy: 0.5238, MCC: -0.1171, F1: 0.6774

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.54128 | val 1.91281
  Epoch 016 - train 0.43883 | val 2.51898
  Classification -> best τ=0.440 (val F1=0.2946)
  Directional -> Accuracy: 0.5088, MCC: 0.2428, F1: 0.2222

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.50951 | val 0.66850
  Epoch 020 - train 0.37597 | val 1.28635
  Classification -> best τ=0.485 (val F1=0.3518)
  Directional -> Accuracy: 0.5854, MCC: 0.2437, F1: 0.7213

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.46311 | val 1.51538
  Epoch 016 - train 0.37662 | val 2.12464
  Classification -> best τ=0.485 (val F1=0.2814)
  Directional -> Accuracy: 0.5349, MCC: 0.0893, F1: 0.6154

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.53566 | val 0.95802
  Epoch 016 - train 0.43644 | val 1.78085
  Classification -> best τ=0.560 (val F1=0.1299)
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.50222 | val 1.38471
  Epoch 016 - train 0.41752 | val 1.56379
  Classification -> best τ=0.475 (val F1=0.1686)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.50970 | val 1.03808
  Epoch 017 - train 0.49034 | val 1.24093
  Classification -> best τ=0.425 (val F1=0.2794)
  Directional -> Accuracy: 0.5616, MCC: 0.2094, F1: 0.4667

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.52526 | val 1.27200
  Epoch 016 - train 0.45542 | val 1.85618
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.52600 | val 2.17805
  Epoch 016 - train 0.41864 | val 2.34762
  Classification -> best τ=0.420 (val F1=0.1329)
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.51239 | val 1.03356
  Epoch 016 - train 0.43040 | val 1.17805
  Classification -> best τ=0.320 (val F1=0.3525)
  Directional -> Accuracy: 0.5909, MCC: 0.3480, F1: 0.4706

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.48907 | val 2.02885
  Epoch 016 - train 0.39936 | val 2.45238
  Classification -> best τ=0.485 (val F1=0.3873)
  Directional -> Accuracy: 0.6667, MCC: 0.3920, F1: 0.5882

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.53749 | val 1.79913
  Epoch 016 - train 0.44702 | val 2.27418
  Classification -> best τ=0.445 (val F1=0.3039)
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.6341

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.43500 | val 3.87651
  Epoch 016 - train 0.40156 | val 2.84435
  Classification -> best τ=0.670 (val F1=0.2441)
  Directional -> Accuracy: 0.5870, MCC: 0.1416, F1: 0.6545

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.55963 | val 0.65595
  Epoch 020 - train 0.40856 | val 0.79539
  Classification -> best τ=0.330 (val F1=0.5247)
  Directional -> Accuracy: 0.4286, MCC: 0.1170, F1: 0.5484

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.49620 | val 1.14477
  Epoch 016 - train 0.38034 | val 1.96716
  Classification -> best τ=0.505 (val F1=0.3320)
  Directional -> Accuracy: 0.5135, MCC: 0.0726, F1: 0.4000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.52634 | val 1.99316
  Epoch 016 - train 0.44860 | val 3.48586
  Classification -> best τ=0.455 (val F1=0.3259)
  Directional -> Accuracy: 0.5200, MCC: 0.1155, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.50616 | val 0.76058
  Epoch 016 - train 0.44515 | val 0.80920
  Classification -> best τ=0.485 (val F1=0.2080)
  Directional -> Accuracy: 0.5652, MCC: 0.1348, F1: 0.6774

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.49534 | val 0.93191
  Epoch 016 - train 0.37789 | val 1.18304
  Classification -> best τ=0.495 (val F1=0.2282)
  Directional -> Accuracy: 0.6047, MCC: 0.1753, F1: 0.7018

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.49704 | val 0.76958
  Epoch 018 - train 0.36196 | val 1.15934
  Classification -> best τ=0.465 (val F1=0.5514)
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.58253 | val 1.21383
  Epoch 016 - train 0.48976 | val 1.31029
  Classification -> best τ=0.480 (val F1=0.1548)
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.51497 | val 1.13475
  Epoch 016 - train 0.42126 | val 1.86738
  Classification -> best τ=0.655 (val F1=0.2671)
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.49907 | val 3.98148
  Epoch 016 - train 0.40524 | val 4.17794
  Classification -> best τ=0.405 (val F1=0.2273)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.48886 | val 2.91066
  Epoch 016 - train 0.38438 | val 2.45310
  Classification -> best τ=0.685 (val F1=0.2639)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.56005 | val 1.93416

[I 2026-02-24 22:39:22,699] Trial 16 finished with value: 0.2542100711660148 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.5, 'batch_size': 16, 'learning_rate': 0.002460030252568339, 'weight_decay': 6.0361483530974885e-06, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 1.263316664174122, 'early_stopping_min_delta': 0.0069058003122342325}. Best is trial 12 with value: 0.25726033636329926.

  Epoch 016 - train 0.49584 | val 5.20630
  Classification -> best τ=0.520 (val F1=0.1361)
  Directional -> Accuracy: 0.4918, MCC: -0.0355, F1: 0.3673

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2542100711660148
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 15
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.62588 | val 0.96320
  Epoch 011 - train 0.62831 | val 0.96152
  Classification -> best τ=0.525 (val F1=0.1398)
  Directional -> Accuracy: 0.5065, MCC: 0.1199, F1: 0.6275

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.58842 | val 0.85308
  Epoch 012 - train 0.58284 | val 0.87469
  Classification -> best τ=0.445 (val F1=0.3778)
  Directional -> Accuracy: 0.5652, MCC: 0.0604, F1: 0.6875

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 16). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.63516 | val 0.70908
  Epoch 013 - train 0.62164 | val 0.72703
  Classification -> best τ=0.430 (val F1=0.3941)
  Directional -> Accuracy: 0.4792, MCC: -0.0789, F1: 0.5763

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.64092 | val 0.82131
  Epoch 011 - train 0.63067 | val 0.83062
  Classification -> best τ=0.455 (val F1=0.1217)
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.59014 | val 0.65065
  Epoch 014 - train 0.56417 | val 0.66497
  Classification -> best τ=0.620 (val F1=0.3719)
  Directional -> Accuracy: 0.5962, MCC: 0.2906, F1: 0.4615

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.60216 | val 0.94992
  Epoch 011 - train 0.60075 | val 0.97281
  Classification -> best τ=0.550 (val F1=0.0930)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.2500

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.62631 | val 1.07027
  Epoch 011 - train 0.62342 | val 1.08394
  Classification -> best τ=0.440 (val F1=0.2571)
  Directional -> Accuracy: 0.5143, MCC: 0.1667, F1: 0.5854

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 16). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.61325 | val 1.33093
  Epoch 011 - train 0.59794 | val 1.43983
  Classification -> best τ=0.500 (val F1=0.2548)
  Directional -> Accuracy: 0.5778, MCC: 0.0340, F1: 0.0952

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.64258 | val 0.71935
  Epoch 013 - train 0.62539 | val 0.73313
  Classification -> best τ=0.540 (val F1=0.4318)
  Directional -> Accuracy: 0.5366, MCC: -0.0434, F1: 0.2963

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 16). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 16). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.60583 | val 1.19021
  Epoch 011 - train 0.59989 | val 1.19286
  Classification -> best τ=0.535 (val F1=0.0642)
  Directional -> Accuracy: 0.6197, MCC: 0.2776, F1: 0.2286

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.62194 | val 1.61248
  Epoch 011 - train 0.61489 | val 1.66532
  Classification -> best τ=0.480 (val F1=0.1090)
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.6400

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.61409 | val 1.26482
  Epoch 011 - train 0.61708 | val 1.28139
  Classification -> best τ=0.415 (val F1=0.1532)
  Directional -> Accuracy: 0.5085, MCC: 0.0000, F1: 0.6742

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.60292 | val 1.49547
  Epoch 011 - train 0.60138 | val 1.57872
  Classification -> best τ=0.430 (val F1=0.1669)
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.64914 | val 0.62258
  Epoch 020 - train 0.60878 | val 0.61417
  Epoch 023 - train 0.58884 | val 0.64033
  Classification -> best τ=0.515 (val F1=0.3192)
  Directional -> Accuracy: 0.5738, MCC: 0.1564, F1: 0.5185

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.60953 | val 1.86522
  Epoch 011 - train 0.60127 | val 1.92597
  Classification -> best τ=0.565 (val F1=0.1584)
  Directional -> Accuracy: 0.5283, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.60328 | val 1.03769
  Epoch 012 - train 0.58636 | val 1.07889
  Classification -> best τ=0.365 (val F1=0.2605)
  Directional -> Accuracy: 0.5571, MCC: 0.1312, F1: 0.7103

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.61691 | val 1.22520
  Epoch 011 - train 0.61177 | val 1.20219
  Classification -> best τ=0.475 (val F1=0.1920)
  Directional -> Accuracy: 0.6000, MCC: 0.0338, F1: 0.7333

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.62573 | val 1.29766
  Epoch 011 - train 0.61874 | val 1.31007
  Classification -> best τ=0.565 (val F1=0.1455)
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.61004 | val 0.79462
  Epoch 011 - train 0.61475 | val 0.80070
  Classification -> best τ=0.515 (val F1=0.1085)
  Directional -> Accuracy: 0.5758, MCC: -0.0336, F1: 0.7255

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 16). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.57653 | val 0.72062
  Epoch 011 - train 0.56820 | val 0.72887
  Classification -> best τ=0.625 (val F1=0.2137)
  Directional -> Accuracy: 0.5000, MCC: 0.0935, F1: 0.2400

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.60592 | val 0.85283
  Epoch 011 - train 0.59975 | val 0.90169
  Classification -> best τ=0.555 (val F1=0.1635)
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.61961 | val 1.24671
  Epoch 011 - train 0.61911 | val 1.30726
  Classification -> best τ=0.520 (val F1=0.3265)
  Directional -> Accuracy: 0.4697, MCC: -0.0659, F1: 0.3396

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.62817 | val 0.88136
  Epoch 013 - train 0.60632 | val 0.93112
  Classification -> best τ=0.465 (val F1=0.2549)
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.61340 | val 1.64342
  Epoch 011 - train 0.60522 | val 1.74620
  Classification -> best τ=0.365 (val F1=0.2304)
  Directional -> Accuracy: 0.5303, MCC: 0.0665, F1: 0.5373

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.60249 | val 0.69707
  Epoch 013 - train 0.59869 | val 0.71590
  Classification -> best τ=0.560 (val F1=0.4115)
  Directional -> Accuracy: 0.5536, MCC: 0.2064, F1: 0.4186

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.60609 | val 0.85911
  Epoch 011 - train 0.59928 | val 0.89334
  Classification -> best τ=0.480 (val F1=0.1792)
  Directional -> Accuracy: 0.5745, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.64014 | val 0.67698
  Epoch 017 - train 0.62169 | val 0.71494
  Classification -> best τ=0.525 (val F1=0.3753)
  Directional -> Accuracy: 0.5116, MCC: 0.0511, F1: 0.5116

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.63837 | val 0.73607
  Epoch 012 - train 0.61907 | val 0.74726
  Classification -> best τ=0.495 (val F1=0.3108)
  Directional -> Accuracy: 0.5517, MCC: 0.3062, F1: 0.3158

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.60576 | val 1.03386
  Epoch 011 - train 0.62135 | val 1.06888
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.7077

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.63461 | val 0.86837
  Epoch 011 - train 0.61565 | val 0.89845
  Classification -> best τ=0.475 (val F1=0.2475)
  Directional -> Accuracy: 0.4773, MCC: -0.0498, F1: 0.3429

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.64045 | val 0.82808
  Epoch 011 - train 0.63533 | val 0.83671
  Classification -> best τ=0.505 (val F1=0.1778)
  Directional -> Accuracy: 0.4091, MCC: -0.1584, F1: 0.2778

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.61287 | val 0.73369
  Epoch 013 - train 0.58607 | val 0.75359
  Classification -> best τ=0.675 (val F1=0.2320)
  Directional -> Accuracy: 0.4314, MCC: -0.1280, F1: 0.2162

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.60701 | val 0.77684
  Epoch 012 - train 0.60263 | val 0.82948
  Classification -> best τ=0.570 (val F1=0.2704)
  Directional -> Accuracy: 0.5000, MCC: 0.1889, F1: 0.2449

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.59701 | val 1.29043
  Epoch 011 - train 0.61040 | val 1.39866
  Classification -> best τ=0.445 (val F1=0.2326)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.4865

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.61768 | val 0.89744
  Epoch 011 - train 0.60431 | val 0.90688
  Classification -> best τ=0.515 (val F1=0.1410)
  Directional -> Accuracy: 0.4889, MCC: -0.2017, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.60936 | val 0.75138
  Epoch 012 - train 0.59533 | val 0.75352
  Classification -> best τ=0.425 (val F1=0.4238)
  Directional -> Accuracy: 0.6418, MCC: 0.2925, F1: 0.6571

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.64561 | val 0.68845
  Epoch 015 - train 0.60033 | val 0.70089
  Classification -> best τ=0.480 (val F1=0.2775)
  Directional -> Accuracy: 0.6744, MCC: 0.3575, F1: 0.6500

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.60439 | val 0.75299
  Epoch 011 - train 0.60440 | val 0.74928
  Classification -> best τ=0.520 (val F1=0.2236)
  Directional -> Accuracy: 0.5965, MCC: 0.1996, F1: 0.4103

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.60133 | val 1.47423
  Epoch 011 - train 0.58937 | val 1.51662
  Classification -> best τ=0.555 (val F1=0.1871)
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 16). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.63220 | val 0.70454
  Epoch 020 - train 0.57677 | val 0.68065
  Epoch 030 - train 0.50467 | val 0.69104
  Classification -> best τ=0.435 (val F1=0.4667)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.64179 | val 0.80125
  Epoch 011 - train 0.64181 | val 0.81395
  Classification -> best τ=0.475 (val F1=0.2707)
  Directional -> Accuracy: 0.5128, MCC: 0.0081, F1: 0.5778

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 16). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.61054 | val 0.84486
  Epoch 011 - train 0.60190 | val 0.89540
  Classification -> best τ=0.440 (val F1=0.2081)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.62219 | val 0.83907
  Epoch 011 - train 0.60906 | val 0.85883
  Classification -> best τ=0.505 (val F1=0.1512)
  Directional -> Accuracy: 0.5532, MCC: 0.1069, F1: 0.5532

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.62530 | val 0.85794
  Epoch 011 - train 0.62136 | val 0.87571
  Classification -> best τ=0.490 (val F1=0.3780)
  Directional -> Accuracy: 0.5333, MCC: -0.0137, F1: 0.6667

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.62516 | val 0.82810
  Epoch 011 - train 0.60069 | val 0.83727
  Classification -> best τ=0.500 (val F1=0.1078)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.63034 | val 0.99016
  Epoch 011 - train 0.62815 | val 1.00823
  Classification -> best τ=0.450 (val F1=0.2973)
  Directional -> Accuracy: 0.5439, MCC: 0.0000, F1: 0.7045

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.59839 | val 1.22444
  Epoch 011 - train 0.58979 | val 1.27272
  Classification -> best τ=0.565 (val F1=0.2258)
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.63653 | val 1.06578
  Epoch 011 - train 0.63694 | val 1.10207
  Classification -> best τ=0.460 (val F1=0.2368)
  Directional -> Accuracy: 0.5370, MCC: 0.0661, F1: 0.6032

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.62900 | val 0.76243
  Epoch 011 - train 0.62246 | val 0.74812
  Classification -> best τ=0.450 (val F1=0.1685)
  Directional -> Accuracy: 0.5263, MCC: 0.0827, F1: 0.6747

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...

[I 2026-02-24 22:40:02,636] Trial 17 finished with value: 0.234388011786149 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 15, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.4, 'dropout': 0.30000000000000004, 'batch_size': 16, 'learning_rate': 0.0002642777903280229, 'weight_decay': 5.521402309834198e-07, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.727055149285453, 'early_stopping_min_delta': 0.004856629751140251}. Best is trial 12 with value: 0.25726033636329926.

  Epoch 010 - train 0.63857 | val 0.82088
  Epoch 011 - train 0.63523 | val 0.84188
  Classification -> best τ=0.500 (val F1=0.2104)
  Directional -> Accuracy: 0.5806, MCC: 0.2022, F1: 0.6579

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.234388011786149
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.70211 | val 0.74193
  Epoch 016 - train 0.70266 | val 0.74183
  Classification -> best τ=0.480 (val F1=0.0370)
  Directional -> Accuracy: 0.5000, MCC: -0.1154, F1: 0.1364

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.70184 | val 0.70396
  Epoch 016 - train 0.69759 | val 0.70405
  Classification -> best τ=0.465 (val F1=0.0805)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.71389 | val 0.69726
  Epoch 016 - train 0.69737 | val 0.69682
  Classification -> best τ=0.470 (val F1=0.2427)
  Directional -> Accuracy: 0.5319, MCC: 0.0712, F1: 0.5217

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.68815 | val 0.75989
  Epoch 016 - train 0.69200 | val 0.76164
  Classification -> best τ=0.455 (val F1=0.2784)
  Directional -> Accuracy: 0.4267, MCC: -0.1192, F1: 0.1224

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.71823 | val 0.75213
  Epoch 016 - train 0.71295 | val 0.74932
  Classification -> best τ=0.505 (val F1=0.2240)
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.77549 | val 0.74829
  Epoch 016 - train 0.75957 | val 0.74897
  Classification -> best τ=0.550 (val F1=0.3273)
  Directional -> Accuracy: 0.5532, MCC: 0.1229, F1: 0.3226

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.72146 | val 0.85524
  Epoch 016 - train 0.73484 | val 0.84857
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.71576 | val 0.68012
  Epoch 016 - train 0.71901 | val 0.67894
  Classification -> best τ=0.435 (val F1=0.1214)
  Directional -> Accuracy: 0.4419, MCC: 0.0137, F1: 0.5714

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.71131 | val 0.71414
  Epoch 018 - train 0.68981 | val 0.71344
  Classification -> best τ=0.420 (val F1=0.2820)
  Directional -> Accuracy: 0.3265, MCC: -0.3401, F1: 0.3265

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.68089 | val 0.72466
  Epoch 016 - train 0.69720 | val 0.72277
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.69801 | val 0.68790
  Epoch 018 - train 0.71613 | val 0.68700
  Classification -> best τ=0.355 (val F1=0.1667)
  Directional -> Accuracy: 0.6600, MCC: 0.3411, F1: 0.4848

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.68668 | val 0.70316
  Epoch 016 - train 0.68428 | val 0.70294
  Classification -> best τ=0.495 (val F1=0.1882)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.71246 | val 0.69939
  Epoch 016 - train 0.71499 | val 0.69938
  Classification -> best τ=0.470 (val F1=0.1686)
  Directional -> Accuracy: 0.4524, MCC: -0.0464, F1: 0.5660

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.70567 | val 0.71836
  Epoch 016 - train 0.70136 | val 0.71802
  Classification -> best τ=0.545 (val F1=0.3367)
  Directional -> Accuracy: 0.5833, MCC: 0.2023, F1: 0.4186

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.71258 | val 0.73459
  Epoch 016 - train 0.70405 | val 0.73515
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.70079 | val 0.69438
  Epoch 016 - train 0.69437 | val 0.69407
  Classification -> best τ=0.480 (val F1=0.1201)
  Directional -> Accuracy: 0.5362, MCC: 0.0333, F1: 0.6596

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.71803 | val 0.79297
  Epoch 016 - train 0.71477 | val 0.79176
  Classification -> best τ=0.450 (val F1=0.2207)
  Directional -> Accuracy: 0.5254, MCC: -0.0339, F1: 0.6316

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.72942 | val 0.75433
  Epoch 016 - train 0.70533 | val 0.75463
  Classification -> best τ=0.445 (val F1=0.0965)
  Directional -> Accuracy: 0.5333, MCC: 0.0653, F1: 0.5783

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.73420 | val 0.81450
  Epoch 016 - train 0.71168 | val 0.81104
  Classification -> best τ=0.560 (val F1=0.2315)
  Directional -> Accuracy: 0.4923, MCC: -0.0398, F1: 0.5600

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.70511 | val 0.86572
  Epoch 016 - train 0.69834 | val 0.86124
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.71417 | val 0.78730
  Epoch 016 - train 0.69449 | val 0.78656
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.71738 | val 0.72187
  Epoch 016 - train 0.72952 | val 0.72209
  Classification -> best τ=0.560 (val F1=0.1248)
  Directional -> Accuracy: 0.5455, MCC: 0.1476, F1: 0.2500

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.68952 | val 0.68421
  Epoch 016 - train 0.68792 | val 0.68393
  Classification -> best τ=0.530 (val F1=0.1461)
  Directional -> Accuracy: 0.5172, MCC: 0.1339, F1: 0.3913

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.69156 | val 0.71123
  Epoch 016 - train 0.69109 | val 0.71129
  Classification -> best τ=0.520 (val F1=0.1986)
  Directional -> Accuracy: 0.5692, MCC: 0.1867, F1: 0.2222

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.75040 | val 0.84036
  Epoch 016 - train 0.72117 | val 0.83585
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.67220 | val 0.69424
  Epoch 016 - train 0.70353 | val 0.69487
  Classification -> best τ=0.535 (val F1=0.1585)
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.69386 | val 0.67852
  Epoch 020 - train 0.70191 | val 0.67912
  Classification -> best τ=0.495 (val F1=0.2071)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.69120 | val 0.74551
  Epoch 016 - train 0.70163 | val 0.74516
  Classification -> best τ=0.485 (val F1=0.0043)
  Directional -> Accuracy: 0.4386, MCC: -0.2277, F1: 0.5789

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.66118 | val 0.83616
  Epoch 016 - train 0.67513 | val 0.85244
  Classification -> best τ=0.480 (val F1=0.4345)
  Directional -> Accuracy: 0.5122, MCC: -0.1469, F1: 0.6774

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.72697 | val 0.76653
  Epoch 016 - train 0.70845 | val 0.76861
  Classification -> best τ=0.470 (val F1=0.0070)
  Directional -> Accuracy: 0.5581, MCC: 0.1239, F1: 0.5957

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.70547 | val 0.64241
  Epoch 020 - train 0.71550 | val 0.64241
  Classification -> best τ=0.630 (val F1=0.1299)
  Directional -> Accuracy: 0.4651, MCC: -0.0538, F1: 0.4103

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.71653 | val 0.74688
  Epoch 016 - train 0.71395 | val 0.74650
  Classification -> best τ=0.500 (val F1=0.1503)
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.71547 | val 0.66418
  Epoch 017 - train 0.71181 | val 0.66273
  Classification -> best τ=0.390 (val F1=0.2951)
  Directional -> Accuracy: 0.5342, MCC: 0.0742, F1: 0.5526

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.70211 | val 0.69538
  Epoch 016 - train 0.68098 | val 0.69779
  Classification -> best τ=0.505 (val F1=0.2887)
  Directional -> Accuracy: 0.5676, MCC: 0.1586, F1: 0.3333

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.68148 | val 0.71625
  Epoch 016 - train 0.69093 | val 0.71623
  Classification -> best τ=0.470 (val F1=0.2358)
  Directional -> Accuracy: 0.5227, MCC: 0.0099, F1: 0.0870

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.69859 | val 0.68033
  Epoch 019 - train 0.69802 | val 0.67944
  Classification -> best τ=0.590 (val F1=0.2249)
  Directional -> Accuracy: 0.5152, MCC: 0.1279, F1: 0.4074

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.72146 | val 0.84176
  Epoch 016 - train 0.71943 | val 0.84200
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5238, MCC: 0.0000, F1: 0.6875

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.68137 | val 0.69846
  Epoch 016 - train 0.68867 | val 0.69893
  Classification -> best τ=0.460 (val F1=0.1518)
  Directional -> Accuracy: 0.5000, MCC: 0.0340, F1: 0.5758

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.71331 | val 0.72540
  Epoch 016 - train 0.71705 | val 0.72615
  Classification -> best τ=0.525 (val F1=0.2800)
  Directional -> Accuracy: 0.5870, MCC: 0.0537, F1: 0.7077

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.72605 | val 0.70331
  Epoch 020 - train 0.72182 | val 0.70218
  Classification -> best τ=0.560 (val F1=0.3482)
  Directional -> Accuracy: 0.6327, MCC: 0.0568, F1: 0.1000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.72953 | val 0.71315
  Epoch 016 - train 0.72201 | val 0.71649
  Classification -> best τ=0.430 (val F1=0.1816)
  Directional -> Accuracy: 0.4865, MCC: -0.2204, F1: 0.6545

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.71753 | val 0.74729
  Epoch 016 - train 0.72461 | val 0.74595
  Classification -> best τ=0.550 (val F1=0.0599)
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.69872 | val 0.68783
  Epoch 020 - train 0.69619 | val 0.68770
  Classification -> best τ=0.370 (val F1=0.2087)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.6857

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.70050 | val 0.73911
  Epoch 016 - train 0.68879 | val 0.74032
  Classification -> best τ=0.530 (val F1=0.0250)
  Directional -> Accuracy: 0.4186, MCC: -0.1280, F1: 0.3243

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.72026 | val 0.74951
  Epoch 016 - train 0.69609 | val 0.75118
  Classification -> best τ=0.535 (val F1=0.2300)
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.71960 | val 0.70115
  Epoch 018 - train 0.71103 | val 0.69989
  Classification -> best τ=0.615 (val F1=0.1085)
  Directional -> Accuracy: 0.4286, MCC: -0.2067, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.74353 | val 0.80812
  Epoch 016 - train 0.72751 | val 0.80327
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.71067 | val 0.89042
  Epoch 016 - train 0.71562 | val 0.89286
  Classification -> best τ=0.450 (val F1=0.2431)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.70332 | val 0.69552
  Epoch 016 - train 0.70760 | val 0.69419
  Classification -> best τ=0.440 (val F1=0.1633)
  Directional -> Accuracy: 0.4821, MCC: -0.0479, F1: 0.5538

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.71369 | val 0.86141

[I 2026-02-24 22:41:05,456] Trial 18 finished with value: 0.15999485029400098 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.5, 'batch_size': 16, 'learning_rate': 1.6617967913144426e-06, 'weight_decay': 4.332862059640366e-06, 'lr_patience': 7, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 0.8715502911293096, 'early_stopping_min_delta': 0.008237248832174462}. Best is trial 12 with value: 0.25726033636329926.

  Epoch 016 - train 0.70685 | val 0.86277
  Classification -> best τ=0.555 (val F1=0.2719)
  Directional -> Accuracy: 0.4918, MCC: 0.0196, F1: 0.6076

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.15999485029400098
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.51554 | val 2.47031
  Epoch 016 - train 0.42302 | val 2.26918
  Classification -> best τ=0.615 (val F1=0.2510)
  Directional -> Accuracy: 0.5263, MCC: -0.0671, F1: 0.1000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.39512 | val 2.22556
  Epoch 017 - train 0.24824 | val 3.23544
  Classification -> best τ=0.460 (val F1=0.1757)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.53437 | val 1.22109
  Epoch 020 - train 0.32084 | val 1.29333
  Classification -> best τ=0.535 (val F1=0.4065)
  Directional -> Accuracy: 0.4894, MCC: -0.0200, F1: 0.5000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.50690 | val 1.77993
  Epoch 016 - train 0.35810 | val 3.34669
  Classification -> best τ=0.365 (val F1=0.0607)
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.42300 | val 1.29018
  Epoch 018 - train 0.24455 | val 1.47949
  Classification -> best τ=0.430 (val F1=0.4063)
  Directional -> Accuracy: 0.7059, MCC: 0.4260, F1: 0.7619

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.29424 | val 5.11645
  Epoch 016 - train 0.21900 | val 6.26156
  Classification -> best τ=0.530 (val F1=0.2037)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.44444 | val 1.52932
  Epoch 016 - train 0.31526 | val 2.07055
  Classification -> best τ=0.430 (val F1=0.2233)
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.34705 | val 1.54262
  Epoch 016 - train 0.19284 | val 1.92940
  Classification -> best τ=0.470 (val F1=0.3077)
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.44407 | val 2.24887
  Epoch 016 - train 0.31511 | val 2.41690
  Classification -> best τ=0.485 (val F1=0.3461)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.46421 | val 0.74211
  Epoch 018 - train 0.30490 | val 0.96079
  Classification -> best τ=0.475 (val F1=0.2262)
  Directional -> Accuracy: 0.4429, MCC: -0.0481, F1: 0.5301

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.45489 | val 3.32163
  Epoch 016 - train 0.30407 | val 4.20069
  Classification -> best τ=0.550 (val F1=0.2500)
  Directional -> Accuracy: 0.6000, MCC: 0.2059, F1: 0.3333

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.51307 | val 1.52526
  Epoch 016 - train 0.39673 | val 2.00190
  Classification -> best τ=0.510 (val F1=0.2105)
  Directional -> Accuracy: 0.6552, MCC: 0.3409, F1: 0.5652

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.43140 | val 1.07673
  Epoch 018 - train 0.26746 | val 1.92575
  Classification -> best τ=0.535 (val F1=0.3726)
  Directional -> Accuracy: 0.4524, MCC: -0.1353, F1: 0.3030

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.54031 | val 0.69486
  Epoch 019 - train 0.35628 | val 0.94243
  Classification -> best τ=0.315 (val F1=0.4237)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.45322 | val 2.74031
  Epoch 016 - train 0.31391 | val 3.83337
  Classification -> best τ=0.520 (val F1=0.0127)
  Directional -> Accuracy: 0.5769, MCC: 0.1350, F1: 0.4500

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.47308 | val 1.58313
  Epoch 016 - train 0.43184 | val 2.62071
  Classification -> best τ=0.440 (val F1=0.2265)
  Directional -> Accuracy: 0.5942, MCC: 0.2667, F1: 0.7255

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.46920 | val 5.38167
  Epoch 016 - train 0.38660 | val 6.83657
  Classification -> best τ=0.440 (val F1=0.0891)
  Directional -> Accuracy: 0.5593, MCC: -0.0413, F1: 0.6905

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.48074 | val 1.11629
  Epoch 016 - train 0.41515 | val 1.41565
  Classification -> best τ=0.450 (val F1=0.1259)
  Directional -> Accuracy: 0.4133, MCC: -0.0680, F1: 0.2667

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.53408 | val 5.81875
  Epoch 016 - train 0.41634 | val 6.57141
  Classification -> best τ=0.485 (val F1=0.2289)
  Directional -> Accuracy: 0.5077, MCC: 0.1597, F1: 0.3600

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.40878 | val 1.36364
  Epoch 016 - train 0.28265 | val 1.71115
  Classification -> best τ=0.505 (val F1=0.2938)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.47596 | val 2.33765
  Epoch 016 - train 0.30843 | val 4.16270
  Classification -> best τ=0.480 (val F1=0.1765)
  Directional -> Accuracy: 0.6596, MCC: 0.2676, F1: 0.7838

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.50023 | val 2.75896
  Epoch 016 - train 0.40532 | val 2.64603
  Classification -> best τ=0.535 (val F1=0.1878)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.46149 | val 1.14137
  Epoch 016 - train 0.37522 | val 1.22735
  Classification -> best τ=0.600 (val F1=0.3579)
  Directional -> Accuracy: 0.4828, MCC: 0.0658, F1: 0.3182

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.55668 | val 0.81972
  Epoch 016 - train 0.39202 | val 1.32585
  Classification -> best τ=0.405 (val F1=0.2614)
  Directional -> Accuracy: 0.4769, MCC: 0.0000, F1: 0.6458

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.52725 | val 0.90997
  Epoch 017 - train 0.29407 | val 1.52582
  Classification -> best τ=0.540 (val F1=0.5052)
  Directional -> Accuracy: 0.5893, MCC: 0.2195, F1: 0.5490

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.44639 | val 3.33414
  Epoch 016 - train 0.24527 | val 4.69504
  Classification -> best τ=0.555 (val F1=0.0331)
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.42896 | val 2.64984
  Epoch 016 - train 0.28101 | val 2.88508
  Classification -> best τ=0.495 (val F1=0.0786)
  Directional -> Accuracy: 0.5238, MCC: 0.1021, F1: 0.4737

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.45190 | val 1.36255
  Epoch 016 - train 0.32397 | val 1.45424
  Classification -> best τ=0.450 (val F1=0.0898)
  Directional -> Accuracy: 0.5614, MCC: 0.3307, F1: 0.3590

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.36343 | val 0.99857
  Epoch 018 - train 0.22085 | val 1.34425
  Classification -> best τ=0.540 (val F1=0.2774)
  Directional -> Accuracy: 0.5122, MCC: 0.0263, F1: 0.5238

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.43073 | val 1.08134
  Epoch 018 - train 0.17948 | val 1.88778
  Classification -> best τ=0.560 (val F1=0.3501)
  Directional -> Accuracy: 0.4884, MCC: -0.0128, F1: 0.5926

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.35989 | val 2.29020
  Epoch 018 - train 0.15083 | val 3.76363
  Classification -> best τ=0.665 (val F1=0.1204)
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.39401 | val 1.38212
  Epoch 016 - train 0.26680 | val 1.55719
  Classification -> best τ=0.450 (val F1=0.2599)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.55477 | val 0.97712
  Epoch 017 - train 0.42902 | val 2.52632
  Classification -> best τ=0.420 (val F1=0.3809)
  Directional -> Accuracy: 0.5753, MCC: 0.2069, F1: 0.5231

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.28602 | val 1.59058
  Epoch 016 - train 0.15198 | val 1.73726
  Classification -> best τ=0.535 (val F1=0.1992)
  Directional -> Accuracy: 0.5676, MCC: 0.1326, F1: 0.5000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.37376 | val 3.72728
  Epoch 016 - train 0.26297 | val 4.46167
  Classification -> best τ=0.625 (val F1=0.0621)
  Directional -> Accuracy: 0.4545, MCC: -0.1026, F1: 0.6129

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.42339 | val 1.17851
  Epoch 016 - train 0.36127 | val 1.64045
  Classification -> best τ=0.400 (val F1=0.3603)
  Directional -> Accuracy: 0.5455, MCC: 0.1517, F1: 0.5000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.30555 | val 3.36586
  Epoch 017 - train 0.20630 | val 3.56946
  Classification -> best τ=0.580 (val F1=0.2652)
  Directional -> Accuracy: 0.4762, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.41873 | val 2.53793
  Epoch 017 - train 0.28157 | val 4.52597
  Classification -> best τ=0.375 (val F1=0.3984)
  Directional -> Accuracy: 0.5536, MCC: 0.1588, F1: 0.6269

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.29282 | val 2.54046
  Epoch 016 - train 0.26009 | val 2.11816
  Classification -> best τ=0.490 (val F1=0.2474)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.36436 | val 0.91633
  Epoch 019 - train 0.18766 | val 1.50767
  Classification -> best τ=0.345 (val F1=0.2749)
  Directional -> Accuracy: 0.3878, MCC: 0.1100, F1: 0.5455

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.25149 | val 3.16784
  Epoch 016 - train 0.18990 | val 5.32689
  Classification -> best τ=0.515 (val F1=0.1816)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.51585 | val 3.31316
  Epoch 016 - train 0.35234 | val 5.52536
  Classification -> best τ=0.355 (val F1=0.2995)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.34080 | val 0.85193
  Epoch 018 - train 0.21456 | val 1.61792
  Classification -> best τ=0.430 (val F1=0.2933)
  Directional -> Accuracy: 0.4348, MCC: -0.1604, F1: 0.5357

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.23331 | val 2.05482
  Epoch 016 - train 0.13681 | val 3.09955
  Classification -> best τ=0.550 (val F1=0.2530)
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.33508 | val 1.73792
  Epoch 019 - train 0.14516 | val 2.60785
  Classification -> best τ=0.555 (val F1=0.6058)
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.53573 | val 1.45704
  Epoch 016 - train 0.41040 | val 2.21423
  Classification -> best τ=0.495 (val F1=0.1941)
  Directional -> Accuracy: 0.4286, MCC: -0.1925, F1: 0.5429

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.43509 | val 2.25318
  Epoch 016 - train 0.28525 | val 4.48045
  Classification -> best τ=0.665 (val F1=0.3122)
  Directional -> Accuracy: 0.5357, MCC: 0.0728, F1: 0.5357

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.43734 | val 4.16227
  Epoch 016 - train 0.32942 | val 4.27094
  Classification -> best τ=0.375 (val F1=0.2273)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.41182 | val 4.45999
  Epoch 016 - train 0.25077 | val 3.51681
  Classification -> best τ=0.560 (val F1=0.0913)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.48988 | val 1.56539

[I 2026-02-24 22:42:12,287] Trial 19 finished with value: 0.24827332664006463 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.4, 'dropout': 0.2, 'batch_size': 16, 'learning_rate': 0.004905935481563099, 'weight_decay': 5.008181305653483e-05, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 1.4388812823658168, 'early_stopping_min_delta': 8.096460483947993e-05}. Best is trial 12 with value: 0.25726033636329926.

  Epoch 018 - train 0.30319 | val 3.40116
  Classification -> best τ=0.340 (val F1=0.2283)
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.24827332664006463
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 15
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.61100 | val 0.69888
  Epoch 015 - train 0.54640 | val 0.76661
  Classification -> best τ=0.575 (val F1=0.2453)
  Directional -> Accuracy: 0.5065, MCC: -0.0457, F1: 0.2692

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.55385 | val 0.81224
  Epoch 011 - train 0.55728 | val 0.87352
  Classification -> best τ=0.505 (val F1=0.1236)
  Directional -> Accuracy: 0.6087, MCC: 0.1780, F1: 0.7000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 16). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.59510 | val 0.94793
  Epoch 011 - train 0.57862 | val 0.99318
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5417, MCC: 0.0000, F1: 0.7027

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.58472 | val 1.31034
  Epoch 011 - train 0.57275 | val 1.73394
  Classification -> best τ=0.395 (val F1=0.1512)
  Directional -> Accuracy: 0.4933, MCC: 0.0081, F1: 0.4571

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.52137 | val 1.21393
  Epoch 012 - train 0.49004 | val 1.37445
  Classification -> best τ=0.480 (val F1=0.5277)
  Directional -> Accuracy: 0.7500, MCC: 0.5138, F1: 0.7451

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.55244 | val 0.83206
  Epoch 011 - train 0.50196 | val 0.91129
  Classification -> best τ=0.530 (val F1=0.3157)
  Directional -> Accuracy: 0.5417, MCC: 0.0884, F1: 0.4500

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.59912 | val 0.77441
  Epoch 011 - train 0.57406 | val 0.77815
  Classification -> best τ=0.560 (val F1=0.1715)
  Directional -> Accuracy: 0.6286, MCC: 0.1650, F1: 0.2778

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 16). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.51518 | val 1.50311
  Epoch 011 - train 0.51286 | val 1.63266
  Classification -> best τ=0.525 (val F1=0.2229)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.55608 | val 0.78991
  Epoch 011 - train 0.54476 | val 0.84537
  Classification -> best τ=0.535 (val F1=0.3877)
  Directional -> Accuracy: 0.3902, MCC: -0.1115, F1: 0.4444

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 16). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 16). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.58114 | val 0.91729
  Epoch 011 - train 0.55348 | val 1.07509
  Classification -> best τ=0.425 (val F1=0.2038)
  Directional -> Accuracy: 0.4366, MCC: 0.0000, F1: 0.6078

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.53182 | val 1.87358
  Epoch 011 - train 0.54127 | val 1.94622
  Classification -> best τ=0.530 (val F1=0.1551)
  Directional -> Accuracy: 0.5098, MCC: 0.0139, F1: 0.4681

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.55355 | val 0.92512
  Epoch 011 - train 0.54508 | val 0.92485
  Classification -> best τ=0.590 (val F1=0.1166)
  Directional -> Accuracy: 0.5254, MCC: 0.1842, F1: 0.1250

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.55196 | val 1.92758
  Epoch 011 - train 0.52565 | val 1.93057
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.58221 | val 0.72354
  Epoch 013 - train 0.57867 | val 0.74275
  Classification -> best τ=0.320 (val F1=0.1919)
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.54057 | val 2.20399
  Epoch 011 - train 0.52932 | val 2.45187
  Classification -> best τ=0.585 (val F1=0.1822)
  Directional -> Accuracy: 0.5094, MCC: -0.0176, F1: 0.2778

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.54968 | val 0.93889
  Epoch 012 - train 0.53096 | val 0.97492
  Classification -> best τ=0.360 (val F1=0.2516)
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.57572 | val 1.52207
  Epoch 011 - train 0.57807 | val 1.54661
  Classification -> best τ=0.550 (val F1=0.1641)
  Directional -> Accuracy: 0.3833, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.58470 | val 1.87394
  Epoch 011 - train 0.55854 | val 1.99664
  Classification -> best τ=0.455 (val F1=0.1846)
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.56772 | val 1.20394
  Epoch 011 - train 0.56226 | val 1.37234
  Classification -> best τ=0.490 (val F1=0.2249)
  Directional -> Accuracy: 0.4394, MCC: 0.0822, F1: 0.1395

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 16). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.55685 | val 0.85247
  Epoch 014 - train 0.51925 | val 0.87711
  Classification -> best τ=0.540 (val F1=0.2582)
  Directional -> Accuracy: 0.5132, MCC: 0.1105, F1: 0.3019

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.54377 | val 1.22378
  Epoch 011 - train 0.54199 | val 1.37159
  Classification -> best τ=0.475 (val F1=0.2174)
  Directional -> Accuracy: 0.5208, MCC: 0.1237, F1: 0.5106

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.57447 | val 1.17155
  Epoch 011 - train 0.57402 | val 1.10603
  Classification -> best τ=0.495 (val F1=0.2070)
  Directional -> Accuracy: 0.5606, MCC: 0.1286, F1: 0.6234

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.56611 | val 0.78141
  Epoch 013 - train 0.54724 | val 0.86018
  Classification -> best τ=0.560 (val F1=0.2299)
  Directional -> Accuracy: 0.5172, MCC: 0.1339, F1: 0.3913

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.56616 | val 3.35106
  Epoch 011 - train 0.54816 | val 2.87442
  Classification -> best τ=0.430 (val F1=0.2453)
  Directional -> Accuracy: 0.5455, MCC: 0.1215, F1: 0.6053

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.57849 | val 0.70517
  Epoch 014 - train 0.52089 | val 0.77729
  Classification -> best τ=0.550 (val F1=0.5093)
  Directional -> Accuracy: 0.5357, MCC: 0.1728, F1: 0.3810

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.53792 | val 0.86693
  Epoch 011 - train 0.52389 | val 0.91095
  Classification -> best τ=0.490 (val F1=0.0199)
  Directional -> Accuracy: 0.5532, MCC: -0.1269, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.59611 | val 1.29719
  Epoch 011 - train 0.59923 | val 1.45054
  Classification -> best τ=0.520 (val F1=0.1309)
  Directional -> Accuracy: 0.4651, MCC: 0.0208, F1: 0.3429

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.57358 | val 0.95201
  Epoch 011 - train 0.58177 | val 0.99481
  Classification -> best τ=0.455 (val F1=0.2469)
  Directional -> Accuracy: 0.6379, MCC: 0.2573, F1: 0.7042

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.55028 | val 0.73922
  Epoch 011 - train 0.53855 | val 0.73732
  Classification -> best τ=0.505 (val F1=0.1987)
  Directional -> Accuracy: 0.5714, MCC: 0.1212, F1: 0.6400

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.57307 | val 1.16804
  Epoch 011 - train 0.55136 | val 1.30290
  Classification -> best τ=0.515 (val F1=0.1271)
  Directional -> Accuracy: 0.4545, MCC: -0.0945, F1: 0.3684

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.59276 | val 0.79584
  Epoch 015 - train 0.54093 | val 1.06805
  Classification -> best τ=0.590 (val F1=0.1239)
  Directional -> Accuracy: 0.4091, MCC: -0.1876, F1: 0.0714

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.53518 | val 0.88345
  Epoch 012 - train 0.52845 | val 0.90111
  Classification -> best τ=0.505 (val F1=0.2100)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.55544 | val 1.07772
  Epoch 014 - train 0.49585 | val 1.49976
  Classification -> best τ=0.415 (val F1=0.3259)
  Directional -> Accuracy: 0.5405, MCC: 0.1096, F1: 0.5278

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.59002 | val 0.79182
  Epoch 011 - train 0.54715 | val 0.79490
  Classification -> best τ=0.475 (val F1=0.0826)
  Directional -> Accuracy: 0.4211, MCC: -0.1857, F1: 0.5417

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.53944 | val 1.09526
  Epoch 011 - train 0.53715 | val 1.15678
  Classification -> best τ=0.495 (val F1=0.2500)
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.6364

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.54182 | val 0.79468
  Epoch 011 - train 0.53858 | val 0.75846
  Classification -> best τ=0.445 (val F1=0.3521)
  Directional -> Accuracy: 0.5970, MCC: 0.1826, F1: 0.6400

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.54183 | val 0.70571
  Epoch 011 - train 0.54109 | val 0.71570
  Classification -> best τ=0.475 (val F1=0.1869)
  Directional -> Accuracy: 0.5116, MCC: 0.0452, F1: 0.3226

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.57302 | val 0.83850
  Epoch 011 - train 0.56036 | val 0.89196
  Classification -> best τ=0.460 (val F1=0.1508)
  Directional -> Accuracy: 0.4386, MCC: -0.1111, F1: 0.5294

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.51572 | val 1.11272
  Epoch 011 - train 0.52911 | val 0.95858
  Classification -> best τ=0.560 (val F1=0.2676)
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 16). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.52490 | val 0.74079
  Epoch 011 - train 0.50877 | val 0.79621
  Classification -> best τ=0.475 (val F1=0.2491)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.59835 | val 0.80335
  Epoch 011 - train 0.58358 | val 0.81918
  Classification -> best τ=0.490 (val F1=0.2707)
  Directional -> Accuracy: 0.5897, MCC: 0.2511, F1: 0.7241

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 16). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.55517 | val 1.73228
  Epoch 012 - train 0.55184 | val 2.08404
  Classification -> best τ=0.410 (val F1=0.3011)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.59840 | val 0.70866
  Epoch 011 - train 0.57906 | val 0.71553
  Classification -> best τ=0.545 (val F1=0.2485)
  Directional -> Accuracy: 0.5319, MCC: 0.1036, F1: 0.3125

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.57305 | val 0.93698
  Epoch 011 - train 0.53581 | val 0.98350
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.55321 | val 0.80557
  Epoch 014 - train 0.50127 | val 0.97245
  Classification -> best τ=0.455 (val F1=0.2928)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.58157 | val 1.70231
  Epoch 011 - train 0.59255 | val 1.77973
  Classification -> best τ=0.385 (val F1=0.2973)
  Directional -> Accuracy: 0.6842, MCC: 0.3684, F1: 0.7000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.54176 | val 1.68761
  Epoch 011 - train 0.53822 | val 1.80284
  Classification -> best τ=0.555 (val F1=0.3588)
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.57205 | val 2.04995
  Epoch 011 - train 0.56393 | val 2.38502
  Classification -> best τ=0.435 (val F1=0.1166)
  Directional -> Accuracy: 0.5185, MCC: 0.0105, F1: 0.6667

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.57265 | val 1.49258
  Epoch 011 - train 0.54282 | val 1.46382
  Classification -> best τ=0.505 (val F1=0.2071)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...

[I 2026-02-24 22:42:52,496] Trial 20 finished with value: 0.2143427711902521 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 15, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.1, 'dropout': 0.30000000000000004, 'batch_size': 32, 'learning_rate': 0.0008289453555402024, 'weight_decay': 5.103097067683895e-07, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.9674268543765723, 'early_stopping_min_delta': 0.006309621356233749}. Best is trial 12 with value: 0.25726033636329926.

  Epoch 010 - train 0.56882 | val 0.94779
  Epoch 011 - train 0.55357 | val 0.80832
  Classification -> best τ=0.560 (val F1=0.2148)
  Directional -> Accuracy: 0.5161, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2143427711902521
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.55356 | val 0.99550
  Epoch 016 - train 0.49474 | val 1.19234
  Classification -> best τ=0.715 (val F1=0.2125)
  Directional -> Accuracy: 0.5395, MCC: -0.0120, F1: 0.1463

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.50554 | val 2.18950
  Epoch 016 - train 0.44567 | val 2.73295
  Classification -> best τ=0.450 (val F1=0.1313)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.55287 | val 0.81488
  Epoch 018 - train 0.42384 | val 1.08787
  Classification -> best τ=0.375 (val F1=0.3020)
  Directional -> Accuracy: 0.6383, MCC: 0.3262, F1: 0.7385

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.56419 | val 3.88159
  Epoch 016 - train 0.48816 | val 3.77411
  Classification -> best τ=0.360 (val F1=0.1723)
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.50008 | val 1.24158
  Epoch 017 - train 0.43480 | val 1.42539
  Classification -> best τ=0.430 (val F1=0.5242)
  Directional -> Accuracy: 0.7255, MCC: 0.4632, F1: 0.7742

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.47658 | val 2.71345
  Epoch 016 - train 0.35789 | val 4.83386
  Classification -> best τ=0.570 (val F1=0.2265)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.56421 | val 0.80517
  Epoch 016 - train 0.49706 | val 1.51334
  Classification -> best τ=0.410 (val F1=0.2233)
  Directional -> Accuracy: 0.4348, MCC: 0.0787, F1: 0.5806

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.48832 | val 1.36054
  Epoch 016 - train 0.42258 | val 1.72189
  Classification -> best τ=0.495 (val F1=0.1214)
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.5902

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.50328 | val 1.51225
  Epoch 020 - train 0.39028 | val 4.20866
  Classification -> best τ=0.520 (val F1=0.4653)
  Directional -> Accuracy: 0.5714, MCC: 0.1118, F1: 0.1600

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.53132 | val 0.98338
  Epoch 016 - train 0.41215 | val 0.84499
  Classification -> best τ=0.380 (val F1=0.2547)
  Directional -> Accuracy: 0.4429, MCC: 0.0160, F1: 0.5895

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.52548 | val 3.18104
  Epoch 016 - train 0.47357 | val 4.86667
  Classification -> best τ=0.575 (val F1=0.2550)
  Directional -> Accuracy: 0.6400, MCC: 0.2848, F1: 0.4706

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.50510 | val 1.11373
  Epoch 016 - train 0.43942 | val 1.92798
  Classification -> best τ=0.460 (val F1=0.2207)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.46507 | val 0.64229
  Epoch 020 - train 0.37738 | val 0.67785
  Classification -> best τ=0.585 (val F1=0.3903)
  Directional -> Accuracy: 0.5238, MCC: -0.0214, F1: 0.2308

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.55828 | val 0.68165
  Epoch 017 - train 0.56843 | val 0.89897
  Classification -> best τ=0.430 (val F1=0.3919)
  Directional -> Accuracy: 0.5833, MCC: 0.2023, F1: 0.6753

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.54320 | val 2.79787
  Epoch 017 - train 0.43172 | val 1.93813
  Classification -> best τ=0.700 (val F1=0.2160)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.51064 | val 1.33263
  Epoch 016 - train 0.47320 | val 1.84304
  Classification -> best τ=0.415 (val F1=0.2708)
  Directional -> Accuracy: 0.5362, MCC: 0.0000, F1: 0.6981

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.55550 | val 3.02000
  Epoch 016 - train 0.46173 | val 3.99667
  Classification -> best τ=0.680 (val F1=0.1842)
  Directional -> Accuracy: 0.3729, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.53969 | val 1.08970
  Epoch 016 - train 0.49361 | val 1.71934
  Classification -> best τ=0.405 (val F1=0.1733)
  Directional -> Accuracy: 0.5200, MCC: 0.1820, F1: 0.4194

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.54511 | val 3.84475
  Epoch 016 - train 0.44792 | val 4.55749
  Classification -> best τ=0.610 (val F1=0.1809)
  Directional -> Accuracy: 0.4154, MCC: -0.0306, F1: 0.0500

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.52190 | val 1.06101
  Epoch 016 - train 0.42543 | val 1.71247
  Classification -> best τ=0.470 (val F1=0.2406)
  Directional -> Accuracy: 0.4933, MCC: 0.1080, F1: 0.2083

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.52533 | val 2.27819
  Epoch 016 - train 0.43034 | val 3.85926
  Classification -> best τ=0.420 (val F1=0.2403)
  Directional -> Accuracy: 0.5106, MCC: 0.2404, F1: 0.3784

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.53044 | val 2.62342
  Epoch 016 - train 0.46949 | val 4.13662
  Classification -> best τ=0.585 (val F1=0.2319)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.58823 | val 1.06218
  Epoch 016 - train 0.50443 | val 1.02468
  Classification -> best τ=0.455 (val F1=0.1371)
  Directional -> Accuracy: 0.4483, MCC: -0.0773, F1: 0.4286

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.47805 | val 0.84209
  Epoch 018 - train 0.43539 | val 1.21286
  Classification -> best τ=0.750 (val F1=0.1507)
  Directional -> Accuracy: 0.4923, MCC: 0.0042, F1: 0.5714

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.53985 | val 0.89799
  Epoch 018 - train 0.40061 | val 1.20069
  Classification -> best τ=0.630 (val F1=0.4472)
  Directional -> Accuracy: 0.5536, MCC: 0.2064, F1: 0.4186

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.47886 | val 0.76596
  Epoch 016 - train 0.39377 | val 1.69933
  Classification -> best τ=0.510 (val F1=0.1890)
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.58910 | val 1.55824
  Epoch 016 - train 0.51204 | val 1.97766
  Classification -> best τ=0.410 (val F1=0.1964)
  Directional -> Accuracy: 0.5238, MCC: 0.0142, F1: 0.6000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.53388 | val 1.14589
  Epoch 016 - train 0.45527 | val 1.61378
  Classification -> best τ=0.460 (val F1=0.2300)
  Directional -> Accuracy: 0.5439, MCC: 0.3032, F1: 0.3158

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.50437 | val 0.71645
  Epoch 020 - train 0.43374 | val 0.86542
  Classification -> best τ=0.495 (val F1=0.3296)
  Directional -> Accuracy: 0.5122, MCC: -0.0202, F1: 0.6296

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.48512 | val 1.67228
  Epoch 016 - train 0.43932 | val 1.89729
  Classification -> best τ=0.485 (val F1=0.2814)
  Directional -> Accuracy: 0.5116, MCC: 0.0217, F1: 0.4878

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.50086 | val 1.12540
  Epoch 018 - train 0.37171 | val 2.31684
  Classification -> best τ=0.590 (val F1=0.0943)
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.52687 | val 1.21612
  Epoch 016 - train 0.40640 | val 1.45945
  Classification -> best τ=0.465 (val F1=0.2611)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.51602 | val 1.21048
  Epoch 017 - train 0.47452 | val 0.84013
  Classification -> best τ=0.295 (val F1=0.3809)
  Directional -> Accuracy: 0.5753, MCC: 0.1768, F1: 0.5634

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.47454 | val 0.79662
  Epoch 016 - train 0.41785 | val 0.87093
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.49713 | val 2.44824
  Epoch 016 - train 0.39597 | val 2.85613
  Classification -> best τ=0.390 (val F1=0.1329)
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.51826 | val 0.99009
  Epoch 016 - train 0.44731 | val 1.45429
  Classification -> best τ=0.410 (val F1=0.3551)
  Directional -> Accuracy: 0.5303, MCC: 0.2518, F1: 0.3404

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.52964 | val 2.19902
  Epoch 016 - train 0.46058 | val 2.82828
  Classification -> best τ=0.500 (val F1=0.2741)
  Directional -> Accuracy: 0.6190, MCC: 0.2571, F1: 0.5789

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.49555 | val 1.48956
  Epoch 016 - train 0.39481 | val 1.19702
  Classification -> best τ=0.410 (val F1=0.2541)
  Directional -> Accuracy: 0.5000, MCC: 0.0910, F1: 0.6316

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.39351 | val 2.98105
  Epoch 016 - train 0.34645 | val 3.24493
  Classification -> best τ=0.610 (val F1=0.2441)
  Directional -> Accuracy: 0.5870, MCC: -0.1195, F1: 0.7397

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.50461 | val 0.64135
  Epoch 020 - train 0.37114 | val 0.79350
  Classification -> best τ=0.340 (val F1=0.4646)
  Directional -> Accuracy: 0.3878, MCC: 0.1100, F1: 0.5455

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.47415 | val 1.15420
  Epoch 016 - train 0.43161 | val 1.49550
  Classification -> best τ=0.465 (val F1=0.1132)
  Directional -> Accuracy: 0.5135, MCC: 0.0385, F1: 0.5000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.51719 | val 2.36107
  Epoch 016 - train 0.45937 | val 4.16134
  Classification -> best τ=0.440 (val F1=0.3075)
  Directional -> Accuracy: 0.5200, MCC: 0.1633, F1: 0.6727

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.53570 | val 1.12666
  Epoch 016 - train 0.43015 | val 1.29060
  Classification -> best τ=0.415 (val F1=0.2097)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.6857

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.45370 | val 0.94684
  Epoch 016 - train 0.35326 | val 0.94263
  Classification -> best τ=0.590 (val F1=0.2530)
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.43820 | val 0.79631
  Epoch 020 - train 0.33985 | val 1.56470
  Classification -> best τ=0.405 (val F1=0.2605)
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.54109 | val 0.98403
  Epoch 016 - train 0.51920 | val 1.47917
  Classification -> best τ=0.455 (val F1=0.2958)
  Directional -> Accuracy: 0.6964, MCC: 0.3916, F1: 0.7119

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.56063 | val 1.37621
  Epoch 016 - train 0.45838 | val 2.10421
  Classification -> best τ=0.755 (val F1=0.2553)
  Directional -> Accuracy: 0.5000, MCC: 0.1301, F1: 0.6585

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.55862 | val 2.99988
  Epoch 016 - train 0.44584 | val 4.39939
  Classification -> best τ=0.330 (val F1=0.2360)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.47198 | val 3.13861
  Epoch 016 - train 0.35421 | val 2.25670
  Classification -> best τ=0.625 (val F1=0.2060)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.55298 | val 2.38680

[I 2026-02-24 22:43:56,396] Trial 21 finished with value: 0.24905921252584048 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.5, 'batch_size': 16, 'learning_rate': 0.0022765582512943843, 'weight_decay': 5.805736646127573e-06, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 1.1921448241157075, 'early_stopping_min_delta': 0.008302332282858229}. Best is trial 12 with value: 0.25726033636329926.

  Epoch 016 - train 0.46714 | val 4.94381
  Classification -> best τ=0.530 (val F1=0.2639)
  Directional -> Accuracy: 0.4918, MCC: -0.1753, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.24905921252584048
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.57418 | val 0.68158
  Epoch 020 - train 0.52063 | val 2.17302
  Classification -> best τ=0.560 (val F1=0.3625)
  Directional -> Accuracy: 0.3816, MCC: -0.2238, F1: 0.5155

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.47045 | val 2.37958
  Epoch 016 - train 0.54748 | val 2.69256
  Classification -> best τ=0.460 (val F1=0.2539)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.57503 | val 0.62785
  Epoch 020 - train 0.41290 | val 1.65716
  Classification -> best τ=0.350 (val F1=0.4554)
  Directional -> Accuracy: 0.5319, MCC: 0.0712, F1: 0.5217

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.60842 | val 2.14941
  Epoch 016 - train 0.57105 | val 2.96021
  Classification -> best τ=0.480 (val F1=0.1723)
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.53197 | val 1.30818
  Epoch 016 - train 0.39594 | val 1.83456
  Classification -> best τ=0.360 (val F1=0.2758)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.47417 | val 0.96489
  Epoch 016 - train 0.29289 | val 4.41118
  Classification -> best τ=0.295 (val F1=0.1644)
  Directional -> Accuracy: 0.4468, MCC: -0.1229, F1: 0.5806

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.60705 | val 1.58687
  Epoch 016 - train 0.49519 | val 1.97784
  Classification -> best τ=0.615 (val F1=0.1805)
  Directional -> Accuracy: 0.5942, MCC: 0.0331, F1: 0.0667

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.53054 | val 1.11679
  Epoch 018 - train 0.24818 | val 1.30797
  Classification -> best τ=0.520 (val F1=0.1590)
  Directional -> Accuracy: 0.6279, MCC: 0.2025, F1: 0.3333

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.50921 | val 2.94454
  Epoch 016 - train 0.37497 | val 3.99992
  Classification -> best τ=0.515 (val F1=0.4055)
  Directional -> Accuracy: 0.5918, MCC: 0.1804, F1: 0.2308

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.54474 | val 0.99972
  Epoch 016 - train 0.46296 | val 1.27934
  Classification -> best τ=0.505 (val F1=0.1701)
  Directional -> Accuracy: 0.4714, MCC: 0.0000, F1: 0.5316

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.57670 | val 4.00685
  Epoch 016 - train 0.43757 | val 5.06157
  Classification -> best τ=0.760 (val F1=0.2632)
  Directional -> Accuracy: 0.5800, MCC: 0.1445, F1: 0.3226

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.58707 | val 2.01216
  Epoch 016 - train 0.46906 | val 2.14988
  Classification -> best τ=0.390 (val F1=0.1469)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.55040 | val 0.77077
  Epoch 017 - train 0.42684 | val 1.39565
  Classification -> best τ=0.530 (val F1=0.4451)
  Directional -> Accuracy: 0.4286, MCC: -0.3341, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.63364 | val 0.97297
  Epoch 018 - train 0.56723 | val 2.33822
  Classification -> best τ=0.345 (val F1=0.3477)
  Directional -> Accuracy: 0.5833, MCC: 0.2334, F1: 0.6914

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.62607 | val 0.77088
  Epoch 020 - train 0.44503 | val 1.05357
  Classification -> best τ=0.815 (val F1=0.3523)
  Directional -> Accuracy: 0.5192, MCC: 0.0616, F1: 0.5614

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.59445 | val 1.50115
  Epoch 016 - train 0.44434 | val 1.60378
  Classification -> best τ=0.505 (val F1=0.1768)
  Directional -> Accuracy: 0.5797, MCC: 0.1455, F1: 0.6420

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.60365 | val 1.78780
  Epoch 016 - train 0.51557 | val 2.90128
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.58542 | val 0.96897
  Epoch 020 - train 0.42439 | val 1.73627
  Classification -> best τ=0.425 (val F1=0.1667)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.5250

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.55525 | val 3.24206
  Epoch 016 - train 0.45472 | val 5.31206
  Classification -> best τ=0.545 (val F1=0.1231)
  Directional -> Accuracy: 0.4769, MCC: 0.0998, F1: 0.2917

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.58029 | val 1.33580
  Epoch 018 - train 0.42605 | val 1.79315
  Classification -> best τ=0.535 (val F1=0.2656)
  Directional -> Accuracy: 0.5333, MCC: 0.1783, F1: 0.3396

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.53562 | val 1.38322
  Epoch 016 - train 0.44318 | val 3.74011
  Classification -> best τ=0.560 (val F1=0.1943)
  Directional -> Accuracy: 0.4255, MCC: 0.1661, F1: 0.1290

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.62190 | val 1.08414
  Epoch 016 - train 0.51092 | val 2.74865
  Classification -> best τ=0.425 (val F1=0.2256)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.63856 | val 1.24457
  Epoch 017 - train 0.46540 | val 2.35394
  Classification -> best τ=0.490 (val F1=0.1280)
  Directional -> Accuracy: 0.4483, MCC: -0.0773, F1: 0.4286

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.57666 | val 0.98973
  Epoch 017 - train 0.45997 | val 1.50046
  Classification -> best τ=0.575 (val F1=0.0858)
  Directional -> Accuracy: 0.4769, MCC: -0.1153, F1: 0.1500

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.58703 | val 1.39410
  Epoch 017 - train 0.45029 | val 2.76997
  Classification -> best τ=0.460 (val F1=0.3730)
  Directional -> Accuracy: 0.6071, MCC: 0.2642, F1: 0.5600

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.46184 | val 2.04278
  Epoch 016 - train 0.32832 | val 5.40646
  Classification -> best τ=0.570 (val F1=0.1823)
  Directional -> Accuracy: 0.4565, MCC: -0.1609, F1: 0.2424

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.55684 | val 1.31982
  Epoch 016 - train 0.42042 | val 1.14716
  Classification -> best τ=0.585 (val F1=0.0913)
  Directional -> Accuracy: 0.5238, MCC: -0.0323, F1: 0.6429

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.52999 | val 1.95966
  Epoch 016 - train 0.40905 | val 2.36542
  Classification -> best τ=0.450 (val F1=0.1955)
  Directional -> Accuracy: 0.6667, MCC: 0.3819, F1: 0.6415

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.50875 | val 0.93195
  Epoch 017 - train 0.38539 | val 1.39788
  Classification -> best τ=0.420 (val F1=0.3278)
  Directional -> Accuracy: 0.4878, MCC: -0.0873, F1: 0.6182

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.52353 | val 1.01335
  Epoch 016 - train 0.33676 | val 2.75168
  Classification -> best τ=0.555 (val F1=0.2814)
  Directional -> Accuracy: 0.4884, MCC: -0.0318, F1: 0.3889

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.46423 | val 1.82405
  Epoch 018 - train 0.23278 | val 2.63784
  Classification -> best τ=0.705 (val F1=0.1204)
  Directional -> Accuracy: 0.4884, MCC: 0.0474, F1: 0.2143

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.49597 | val 1.79778
  Epoch 016 - train 0.40682 | val 2.47075
  Classification -> best τ=0.775 (val F1=0.2399)
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.58042 | val 0.98891
  Epoch 020 - train 0.43216 | val 2.70263
  Classification -> best τ=0.265 (val F1=0.3982)
  Directional -> Accuracy: 0.5890, MCC: 0.1599, F1: 0.6429

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.45195 | val 0.96937
  Epoch 016 - train 0.23452 | val 1.27659
  Classification -> best τ=0.595 (val F1=0.2887)
  Directional -> Accuracy: 0.4595, MCC: -0.0774, F1: 0.5000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.58387 | val 2.84803
  Epoch 016 - train 0.40500 | val 3.81044
  Classification -> best τ=0.345 (val F1=0.2358)
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.56255 | val 1.29772
  Epoch 016 - train 0.44207 | val 1.10022
  Classification -> best τ=0.360 (val F1=0.3280)
  Directional -> Accuracy: 0.4848, MCC: 0.1062, F1: 0.2917

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.44657 | val 2.95571
  Epoch 016 - train 0.34594 | val 4.18977
  Classification -> best τ=0.565 (val F1=0.2357)
  Directional -> Accuracy: 0.5238, MCC: 0.0983, F1: 0.3333

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.52730 | val 2.06787
  Epoch 016 - train 0.41679 | val 3.03320
  Classification -> best τ=0.330 (val F1=0.2804)
  Directional -> Accuracy: 0.5893, MCC: 0.2134, F1: 0.6349

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.48481 | val 4.38383
  Epoch 016 - train 0.34192 | val 1.69628
  Classification -> best τ=0.450 (val F1=0.3107)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.53327 | val 0.82948
  Epoch 020 - train 0.25713 | val 3.07938
  Classification -> best τ=0.320 (val F1=0.4410)
  Directional -> Accuracy: 0.4490, MCC: 0.2272, F1: 0.5714

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.54974 | val 1.19741
  Epoch 017 - train 0.32407 | val 2.35354
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.58239 | val 2.26140
  Epoch 016 - train 0.44560 | val 5.17940
  Classification -> best τ=0.415 (val F1=0.3317)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.57679 | val 1.06381
  Epoch 017 - train 0.28101 | val 1.91949
  Classification -> best τ=0.435 (val F1=0.3560)
  Directional -> Accuracy: 0.4565, MCC: -0.0763, F1: 0.2424

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.45427 | val 1.60032
  Epoch 016 - train 0.22882 | val 2.83196
  Classification -> best τ=0.560 (val F1=0.4625)
  Directional -> Accuracy: 0.4884, MCC: -0.0044, F1: 0.4762

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.45825 | val 1.54316
  Epoch 019 - train 0.20584 | val 5.41866
  Classification -> best τ=0.470 (val F1=0.2605)
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.62640 | val 1.82456
  Epoch 016 - train 0.49565 | val 2.96098
  Classification -> best τ=0.355 (val F1=0.2513)
  Directional -> Accuracy: 0.5179, MCC: 0.0998, F1: 0.3415

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.48713 | val 2.04192
  Epoch 016 - train 0.41300 | val 4.69641
  Classification -> best τ=0.795 (val F1=0.3241)
  Directional -> Accuracy: 0.5000, MCC: 0.1301, F1: 0.6585

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.65725 | val 3.20697
  Epoch 016 - train 0.51174 | val 4.83953
  Classification -> best τ=0.210 (val F1=0.2457)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.51065 | val 3.80892
  Epoch 020 - train 0.44278 | val 5.32017
  Classification -> best τ=0.340 (val F1=0.1794)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.59444 | val 2.55873

[I 2026-02-24 22:45:02,793] Trial 22 finished with value: 0.24876136634492174 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.5, 'batch_size': 16, 'learning_rate': 0.009091313284653003, 'weight_decay': 2.456070775109492e-06, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 1.2707907598501822, 'early_stopping_min_delta': 0.003976273366683424}. Best is trial 12 with value: 0.25726033636329926.

  Epoch 016 - train 0.44956 | val 8.34427
  Classification -> best τ=0.400 (val F1=0.1764)
  Directional -> Accuracy: 0.4918, MCC: 0.1229, F1: 0.6517

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.24876136634492174
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.51869 | val 0.88711
  Epoch 016 - train 0.45619 | val 0.85118
  Classification -> best τ=0.725 (val F1=0.2510)
  Directional -> Accuracy: 0.5526, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.50184 | val 1.04021
  Epoch 018 - train 0.40073 | val 1.58291
  Classification -> best τ=0.485 (val F1=0.2370)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.53997 | val 0.95876
  Epoch 016 - train 0.45142 | val 1.24682
  Classification -> best τ=0.480 (val F1=0.1314)
  Directional -> Accuracy: 0.5532, MCC: 0.0961, F1: 0.6038

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.54403 | val 2.02055
  Epoch 016 - train 0.47755 | val 1.43913
  Classification -> best τ=0.465 (val F1=0.1691)
  Directional -> Accuracy: 0.5067, MCC: -0.0189, F1: 0.5934

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.48063 | val 1.01570
  Epoch 017 - train 0.39702 | val 1.70554
  Classification -> best τ=0.535 (val F1=0.4458)
  Directional -> Accuracy: 0.7843, MCC: 0.5666, F1: 0.8000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.44892 | val 1.14985
  Epoch 018 - train 0.33218 | val 1.79931
  Classification -> best τ=0.630 (val F1=0.2357)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.56032 | val 0.92138
  Epoch 016 - train 0.48411 | val 1.18931
  Classification -> best τ=0.435 (val F1=0.2435)
  Directional -> Accuracy: 0.5652, MCC: 0.1655, F1: 0.5588

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.49336 | val 0.74374
  Epoch 016 - train 0.41154 | val 0.96814
  Classification -> best τ=0.545 (val F1=0.1502)
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.51964 | val 0.82741
  Epoch 020 - train 0.41269 | val 1.39070
  Classification -> best τ=0.630 (val F1=0.4598)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.49687 | val 0.77105
  Epoch 016 - train 0.44397 | val 0.75830
  Classification -> best τ=0.410 (val F1=0.1628)
  Directional -> Accuracy: 0.4429, MCC: 0.0160, F1: 0.5895

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.51905 | val 3.35851
  Epoch 016 - train 0.42045 | val 4.60148
  Classification -> best τ=0.560 (val F1=0.3118)
  Directional -> Accuracy: 0.6000, MCC: 0.1943, F1: 0.3750

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.53121 | val 1.90868
  Epoch 016 - train 0.46814 | val 2.45804
  Classification -> best τ=0.515 (val F1=0.1708)
  Directional -> Accuracy: 0.5345, MCC: 0.0806, F1: 0.3721

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.49613 | val 0.67914
  Epoch 016 - train 0.39869 | val 0.91632
  Classification -> best τ=0.560 (val F1=0.0511)
  Directional -> Accuracy: 0.4524, MCC: -0.1353, F1: 0.3030

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.55716 | val 0.63590
  Epoch 019 - train 0.49671 | val 0.76770
  Classification -> best τ=0.575 (val F1=0.3387)
  Directional -> Accuracy: 0.5500, MCC: 0.1005, F1: 0.5263

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.50663 | val 3.99326
  Epoch 016 - train 0.42392 | val 3.72574
  Classification -> best τ=0.620 (val F1=0.2160)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.50900 | val 1.24193
  Epoch 016 - train 0.46275 | val 1.65436
  Classification -> best τ=0.405 (val F1=0.2708)
  Directional -> Accuracy: 0.5507, MCC: 0.1304, F1: 0.7048

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.54502 | val 3.55369
  Epoch 016 - train 0.47372 | val 4.13270
  Classification -> best τ=0.380 (val F1=0.1179)
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.51741 | val 1.03931
  Epoch 016 - train 0.47407 | val 1.43648
  Classification -> best τ=0.555 (val F1=0.2236)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.52482 | val 3.47289
  Epoch 016 - train 0.44015 | val 4.73093
  Classification -> best τ=0.535 (val F1=0.2234)
  Directional -> Accuracy: 0.4462, MCC: 0.0859, F1: 0.1429

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.50574 | val 2.68019
  Epoch 016 - train 0.41441 | val 3.08062
  Classification -> best τ=0.510 (val F1=0.2433)
  Directional -> Accuracy: 0.5200, MCC: 0.1714, F1: 0.2800

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.50301 | val 1.48493
  Epoch 016 - train 0.41243 | val 1.73879
  Classification -> best τ=0.440 (val F1=0.1586)
  Directional -> Accuracy: 0.5319, MCC: -0.0118, F1: 0.6333

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.49836 | val 2.36204
  Epoch 016 - train 0.42530 | val 3.43905
  Classification -> best τ=0.565 (val F1=0.2972)
  Directional -> Accuracy: 0.5455, MCC: 0.2182, F1: 0.1667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.56710 | val 1.16731
  Epoch 016 - train 0.50087 | val 1.20954
  Classification -> best τ=0.575 (val F1=0.2033)
  Directional -> Accuracy: 0.4828, MCC: 0.1433, F1: 0.2105

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.53522 | val 0.93958
  Epoch 019 - train 0.45167 | val 1.04038
  Classification -> best τ=0.405 (val F1=0.1828)
  Directional -> Accuracy: 0.4769, MCC: 0.0000, F1: 0.6458

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.54113 | val 0.99939
  Epoch 017 - train 0.45316 | val 1.27168
  Classification -> best τ=0.545 (val F1=0.5049)
  Directional -> Accuracy: 0.5357, MCC: 0.1728, F1: 0.3810

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.52876 | val 0.75107
  Epoch 016 - train 0.46492 | val 1.12014
  Classification -> best τ=0.515 (val F1=0.3368)
  Directional -> Accuracy: 0.5435, MCC: -0.1307, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.51134 | val 1.49859
  Epoch 016 - train 0.44206 | val 1.57183
  Classification -> best τ=0.470 (val F1=0.1936)
  Directional -> Accuracy: 0.4762, MCC: 0.1936, F1: 0.1538

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.50893 | val 0.76795
  Epoch 016 - train 0.43686 | val 1.04030
  Classification -> best τ=0.475 (val F1=0.3126)
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.51169 | val 0.67617
  Epoch 020 - train 0.39010 | val 1.30051
  Classification -> best τ=0.550 (val F1=0.3380)
  Directional -> Accuracy: 0.5854, MCC: 0.1695, F1: 0.6047

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.50982 | val 0.78610
  Epoch 020 - train 0.38381 | val 1.40211
  Classification -> best τ=0.570 (val F1=0.2814)
  Directional -> Accuracy: 0.4884, MCC: -0.0179, F1: 0.5417

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.57852 | val 0.70480
  Epoch 020 - train 0.44697 | val 0.82979
  Classification -> best τ=0.780 (val F1=0.1204)
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.51801 | val 1.06843
  Epoch 016 - train 0.44755 | val 1.48059
  Classification -> best τ=0.505 (val F1=0.2521)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.51539 | val 0.86198
  Epoch 016 - train 0.45925 | val 0.94694
  Classification -> best τ=0.375 (val F1=0.3809)
  Directional -> Accuracy: 0.5342, MCC: 0.1140, F1: 0.4848

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.52561 | val 1.07631
  Epoch 016 - train 0.43023 | val 1.27494
  Classification -> best τ=0.485 (val F1=0.1992)
  Directional -> Accuracy: 0.4054, MCC: -0.1901, F1: 0.3889

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.48695 | val 2.51843
  Epoch 016 - train 0.41216 | val 2.91497
  Classification -> best τ=0.655 (val F1=0.1749)
  Directional -> Accuracy: 0.5455, MCC: 0.1596, F1: 0.0909

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.50089 | val 0.98536
  Epoch 016 - train 0.43789 | val 1.26175
  Classification -> best τ=0.325 (val F1=0.3603)
  Directional -> Accuracy: 0.6061, MCC: 0.3704, F1: 0.5000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.48455 | val 1.21099
  Epoch 016 - train 0.41956 | val 2.02604
  Classification -> best τ=0.510 (val F1=0.3099)
  Directional -> Accuracy: 0.5238, MCC: 0.0608, F1: 0.4737

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.51914 | val 1.37534
  Epoch 017 - train 0.42409 | val 1.77756
  Classification -> best τ=0.385 (val F1=0.3145)
  Directional -> Accuracy: 0.5000, MCC: 0.1192, F1: 0.6410

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.42417 | val 2.89430
  Epoch 016 - train 0.38759 | val 2.81917
  Classification -> best τ=0.530 (val F1=0.2167)
  Directional -> Accuracy: 0.3913, MCC: -0.0687, F1: 0.1250

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.50229 | val 0.64667
  Epoch 020 - train 0.36642 | val 0.75046
  Classification -> best τ=0.380 (val F1=0.5509)
  Directional -> Accuracy: 0.3878, MCC: -0.0518, F1: 0.5000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.47890 | val 1.23483
  Epoch 016 - train 0.39743 | val 1.71045
  Classification -> best τ=0.515 (val F1=0.2623)
  Directional -> Accuracy: 0.5946, MCC: 0.2699, F1: 0.4828

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.52051 | val 1.99749
  Epoch 016 - train 0.42009 | val 3.17418
  Classification -> best τ=0.490 (val F1=0.3068)
  Directional -> Accuracy: 0.5200, MCC: 0.1155, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.51044 | val 0.74550
  Epoch 019 - train 0.42441 | val 1.39365
  Classification -> best τ=0.465 (val F1=0.3403)
  Directional -> Accuracy: 0.5870, MCC: 0.1921, F1: 0.5366

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.51333 | val 0.81232
  Epoch 016 - train 0.41655 | val 0.79862
  Classification -> best τ=0.505 (val F1=0.0610)
  Directional -> Accuracy: 0.5116, MCC: 0.0490, F1: 0.4878

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.50697 | val 0.72842
  Epoch 016 - train 0.40906 | val 1.03452
  Classification -> best τ=0.500 (val F1=0.0889)
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.59314 | val 2.09908
  Epoch 016 - train 0.50082 | val 1.84320
  Classification -> best τ=0.470 (val F1=0.1914)
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.53278 | val 2.20877
  Epoch 016 - train 0.44356 | val 2.60449
  Classification -> best τ=0.580 (val F1=0.3819)
  Directional -> Accuracy: 0.5357, MCC: 0.1768, F1: 0.6667

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.51605 | val 2.69759
  Epoch 016 - train 0.41858 | val 4.01923
  Classification -> best τ=0.450 (val F1=0.1866)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.47939 | val 2.45479
  Epoch 016 - train 0.38149 | val 3.52122
  Classification -> best τ=0.605 (val F1=0.1168)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.55262 | val 1.74506

[I 2026-02-24 22:46:09,858] Trial 23 finished with value: 0.25084822721834726 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.4, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.001375563102748428, 'weight_decay': 1.6448747175069373e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 1.7822422786038685, 'early_stopping_min_delta': 0.006973791192874725}. Best is trial 12 with value: 0.25726033636329926.

  Epoch 016 - train 0.48156 | val 2.80697
  Classification -> best τ=0.530 (val F1=0.2639)
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.25084822721834726
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 15
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.60610 | val 1.23932
  Epoch 016 - train 0.58773 | val 1.89136
  Classification -> best τ=0.550 (val F1=0.0177)
  Directional -> Accuracy: 0.5455, MCC: 0.1174, F1: 0.5783

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.48752 | val 0.87223
  Epoch 016 - train 0.37663 | val 0.92484
  Classification -> best τ=0.425 (val F1=0.1236)
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 16). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.59347 | val 0.95546
  Epoch 016 - train 0.50151 | val 1.45021
  Classification -> best τ=0.485 (val F1=0.2949)
  Directional -> Accuracy: 0.4792, MCC: 0.0247, F1: 0.2424

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.60258 | val 2.58444
  Epoch 016 - train 0.55657 | val 1.31857
  Classification -> best τ=0.430 (val F1=0.2485)
  Directional -> Accuracy: 0.5067, MCC: -0.0452, F1: 0.6263

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.51041 | val 0.89959
  Epoch 016 - train 0.45724 | val 1.17969
  Classification -> best τ=0.515 (val F1=0.3145)
  Directional -> Accuracy: 0.6923, MCC: 0.4148, F1: 0.6667

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.45704 | val 1.96776
  Epoch 017 - train 0.35058 | val 4.88673
  Classification -> best τ=0.630 (val F1=0.3119)
  Directional -> Accuracy: 0.5625, MCC: 0.1251, F1: 0.5714

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.62105 | val 1.18080
  Epoch 016 - train 0.50679 | val 1.50268
  Classification -> best τ=0.320 (val F1=0.2722)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.5714

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 16). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.43085 | val 8.18735
  Epoch 016 - train 0.32200 | val 11.99405
  Classification -> best τ=0.585 (val F1=0.3162)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.56446 | val 2.02733
  Epoch 016 - train 0.45366 | val 2.98857
  Classification -> best τ=0.550 (val F1=0.4523)
  Directional -> Accuracy: 0.4878, MCC: -0.0321, F1: 0.4000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 16). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 16). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.52981 | val 1.23164
  Epoch 019 - train 0.47454 | val 1.32235
  Classification -> best τ=0.220 (val F1=0.2931)
  Directional -> Accuracy: 0.4789, MCC: 0.0382, F1: 0.5747

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.58037 | val 1.71856
  Epoch 016 - train 0.46205 | val 3.03008
  Classification -> best τ=0.670 (val F1=0.1982)
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.6400

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.58076 | val 1.09101
  Epoch 016 - train 0.47298 | val 1.02753
  Classification -> best τ=0.375 (val F1=0.2271)
  Directional -> Accuracy: 0.5085, MCC: 0.0000, F1: 0.6742

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.55187 | val 3.68940
  Epoch 016 - train 0.48028 | val 5.04987
  Classification -> best τ=0.270 (val F1=0.2454)
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.63791 | val 0.64248
  Epoch 017 - train 0.55777 | val 0.93346
  Classification -> best τ=0.380 (val F1=0.3454)
  Directional -> Accuracy: 0.5246, MCC: 0.0503, F1: 0.6420

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.50403 | val 10.57307
  Epoch 016 - train 0.45761 | val 12.39350
  Classification -> best τ=0.695 (val F1=0.2798)
  Directional -> Accuracy: 0.5283, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.53576 | val 1.49508
  Epoch 016 - train 0.48523 | val 1.49054
  Classification -> best τ=0.435 (val F1=0.3641)
  Directional -> Accuracy: 0.6000, MCC: 0.2312, F1: 0.7255

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.59370 | val 1.06975
  Epoch 016 - train 0.47856 | val 1.07454
  Classification -> best τ=0.605 (val F1=0.1259)
  Directional -> Accuracy: 0.4333, MCC: 0.1809, F1: 0.1500

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.59026 | val 2.40340
  Epoch 016 - train 0.53669 | val 2.69562
  Classification -> best τ=0.375 (val F1=0.2137)
  Directional -> Accuracy: 0.6184, MCC: 0.2061, F1: 0.6813

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.54495 | val 2.54667
  Epoch 016 - train 0.52241 | val 3.41735
  Classification -> best τ=0.410 (val F1=0.2464)
  Directional -> Accuracy: 0.5303, MCC: 0.1463, F1: 0.4746

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 16). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.51117 | val 1.02089
  Epoch 016 - train 0.47904 | val 1.28833
  Classification -> best τ=0.590 (val F1=0.2855)
  Directional -> Accuracy: 0.5000, MCC: 0.0935, F1: 0.2400

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.54005 | val 3.99942
  Epoch 016 - train 0.45615 | val 5.93985
  Classification -> best τ=0.375 (val F1=0.2046)
  Directional -> Accuracy: 0.4375, MCC: 0.1233, F1: 0.2286

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.56317 | val 2.75813
  Epoch 016 - train 0.52315 | val 3.66818
  Classification -> best τ=0.395 (val F1=0.1677)
  Directional -> Accuracy: 0.5455, MCC: 0.1476, F1: 0.6739

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.54178 | val 1.27158
  Epoch 016 - train 0.46929 | val 1.89913
  Classification -> best τ=0.585 (val F1=0.2812)
  Directional -> Accuracy: 0.5345, MCC: 0.0951, F1: 0.5263

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.56305 | val 2.11783
  Epoch 016 - train 0.44550 | val 4.69968
  Classification -> best τ=0.340 (val F1=0.2319)
  Directional -> Accuracy: 0.5152, MCC: 0.0341, F1: 0.5152

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.53913 | val 1.14393
  Epoch 016 - train 0.44637 | val 1.41244
  Classification -> best τ=0.530 (val F1=0.4595)
  Directional -> Accuracy: 0.5714, MCC: 0.2385, F1: 0.4545

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.44847 | val 2.52357
  Epoch 016 - train 0.35674 | val 3.16937
  Classification -> best τ=0.475 (val F1=0.2274)
  Directional -> Accuracy: 0.4894, MCC: -0.2003, F1: 0.0769

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.62190 | val 0.83642
  Epoch 020 - train 0.44669 | val 1.34423
  Classification -> best τ=0.375 (val F1=0.3920)
  Directional -> Accuracy: 0.6512, MCC: 0.2804, F1: 0.7619

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.60895 | val 1.27340
  Epoch 016 - train 0.47025 | val 1.82862
  Classification -> best τ=0.440 (val F1=0.2539)
  Directional -> Accuracy: 0.5000, MCC: 0.2105, F1: 0.1714

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.60061 | val 0.98979
  Epoch 020 - train 0.45291 | val 2.67555
  Classification -> best τ=0.535 (val F1=0.4193)
  Directional -> Accuracy: 0.5952, MCC: 0.1961, F1: 0.6047

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.53705 | val 1.92052
  Epoch 016 - train 0.37727 | val 1.89731
  Classification -> best τ=0.600 (val F1=0.1869)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.2143

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.59280 | val 1.44954
  Epoch 016 - train 0.47592 | val 2.06694
  Classification -> best τ=0.395 (val F1=0.1189)
  Directional -> Accuracy: 0.5000, MCC: -0.0753, F1: 0.6333

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.50931 | val 1.03135
  Epoch 016 - train 0.39298 | val 1.39898
  Classification -> best τ=0.645 (val F1=0.2320)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.55546 | val 1.83329
  Epoch 016 - train 0.48463 | val 3.25103
  Classification -> best τ=0.465 (val F1=0.3257)
  Directional -> Accuracy: 0.5676, MCC: 0.2241, F1: 0.4839

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.51685 | val 2.26447
  Epoch 016 - train 0.48487 | val 4.12221
  Classification -> best τ=0.465 (val F1=0.4045)
  Directional -> Accuracy: 0.5263, MCC: 0.0679, F1: 0.6400

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.51033 | val 1.53893
  Epoch 016 - train 0.43856 | val 2.75813
  Classification -> best τ=0.570 (val F1=0.2362)
  Directional -> Accuracy: 0.6000, MCC: 0.2295, F1: 0.6400

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.54307 | val 1.04905
  Epoch 016 - train 0.47248 | val 1.20774
  Classification -> best τ=0.255 (val F1=0.3767)
  Directional -> Accuracy: 0.6269, MCC: 0.2370, F1: 0.6753

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.51945 | val 1.10370
  Epoch 017 - train 0.48787 | val 1.89367
  Classification -> best τ=0.450 (val F1=0.2775)
  Directional -> Accuracy: 0.5349, MCC: 0.1249, F1: 0.2857

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.57185 | val 0.83408
  Epoch 016 - train 0.51698 | val 1.07458
  Classification -> best τ=0.340 (val F1=0.1626)
  Directional -> Accuracy: 0.5263, MCC: 0.1700, F1: 0.6582

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.51891 | val 2.83215
  Epoch 016 - train 0.40819 | val 4.54843
  Classification -> best τ=0.495 (val F1=0.2403)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 16). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.50639 | val 0.86459
  Epoch 019 - train 0.36592 | val 1.39126
  Classification -> best τ=0.365 (val F1=0.3830)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.56210 | val 1.38871
  Epoch 016 - train 0.43236 | val 1.89201
  Classification -> best τ=0.590 (val F1=0.0406)
  Directional -> Accuracy: 0.5128, MCC: 0.2152, F1: 0.1739

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 16). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.58920 | val 2.51468
  Epoch 016 - train 0.47163 | val 4.01559
  Classification -> best τ=0.485 (val F1=0.2585)
  Directional -> Accuracy: 0.5132, MCC: 0.0531, F1: 0.6606

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.55349 | val 1.11890
  Epoch 016 - train 0.45534 | val 1.64711
  Classification -> best τ=0.510 (val F1=0.1560)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.49102 | val 3.32790
  Epoch 016 - train 0.39185 | val 4.50798
  Classification -> best τ=0.470 (val F1=0.1890)
  Directional -> Accuracy: 0.6222, MCC: 0.2197, F1: 0.7119

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.44035 | val 0.82413
  Epoch 017 - train 0.33630 | val 1.17019
  Classification -> best τ=0.470 (val F1=0.3647)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.59882 | val 2.07841
  Epoch 016 - train 0.54560 | val 4.68982
  Classification -> best τ=0.470 (val F1=0.3621)
  Directional -> Accuracy: 0.5439, MCC: 0.0000, F1: 0.7045

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.56400 | val 2.20537
  Epoch 016 - train 0.43072 | val 3.59374
  Classification -> best τ=0.765 (val F1=0.3588)
  Directional -> Accuracy: 0.5088, MCC: 0.0590, F1: 0.6111

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.51591 | val 1.51804
  Epoch 017 - train 0.51253 | val 1.72326
  Classification -> best τ=0.380 (val F1=0.1508)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.55611 | val 0.73884
  Epoch 017 - train 0.41631 | val 1.59905
  Classification -> best τ=0.415 (val F1=0.2962)
  Directional -> Accuracy: 0.5263, MCC: 0.0770, F1: 0.3415

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.54351 | val 0.86038

[I 2026-02-24 22:47:05,447] Trial 24 finished with value: 0.2654562368520373 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 15, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.6000000000000001, 'batch_size': 16, 'learning_rate': 0.00413358010241219, 'weight_decay': 9.563831548741814e-06, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 1.5674316286284349, 'early_stopping_min_delta': 0.007377604881858268}. Best is trial 24 with value: 0.2654562368520373.

  Epoch 016 - train 0.50442 | val 1.01173
  Classification -> best τ=0.555 (val F1=0.3383)
  Directional -> Accuracy: 0.5161, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2654562368520373
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 15
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.54739 | val 2.15845
  Epoch 016 - train 0.56369 | val 2.37565
  Classification -> best τ=0.635 (val F1=0.1989)
  Directional -> Accuracy: 0.5325, MCC: -0.0165, F1: 0.1429

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.49465 | val 1.33445
  Epoch 016 - train 0.39995 | val 1.51116
  Classification -> best τ=0.455 (val F1=0.0615)
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 16). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.58213 | val 0.92426
  Epoch 018 - train 0.47341 | val 1.56259
  Classification -> best τ=0.520 (val F1=0.5416)
  Directional -> Accuracy: 0.3125, MCC: -0.4151, F1: 0.0571

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.65023 | val 2.34818
  Epoch 017 - train 0.53736 | val 3.55897
  Classification -> best τ=0.375 (val F1=0.2359)
  Directional -> Accuracy: 0.4533, MCC: -0.0324, F1: 0.1633

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.53497 | val 1.10904
  Epoch 016 - train 0.42500 | val 1.32281
  Classification -> best τ=0.510 (val F1=0.4105)
  Directional -> Accuracy: 0.6154, MCC: 0.3010, F1: 0.5238

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.40526 | val 2.79506
  Epoch 016 - train 0.35720 | val 4.47823
  Classification -> best τ=0.535 (val F1=0.3254)
  Directional -> Accuracy: 0.6042, MCC: 0.2100, F1: 0.6275

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.62095 | val 0.97803
  Epoch 016 - train 0.52275 | val 1.37066
  Classification -> best τ=0.370 (val F1=0.2365)
  Directional -> Accuracy: 0.5000, MCC: 0.1224, F1: 0.5679

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 16). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.51399 | val 5.26190
  Epoch 016 - train 0.34258 | val 11.35012
  Classification -> best τ=0.550 (val F1=0.2229)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.54353 | val 2.28056
  Epoch 016 - train 0.40219 | val 2.74671
  Classification -> best τ=0.535 (val F1=0.3877)
  Directional -> Accuracy: 0.5366, MCC: -0.0777, F1: 0.2400

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 16). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 16). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.58094 | val 1.09177
  Epoch 016 - train 0.48474 | val 1.80092
  Classification -> best τ=0.440 (val F1=0.1258)
  Directional -> Accuracy: 0.5070, MCC: 0.1231, F1: 0.6067

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.58829 | val 1.84288
  Epoch 016 - train 0.51059 | val 2.38539
  Classification -> best τ=0.650 (val F1=0.1612)
  Directional -> Accuracy: 0.5294, MCC: 0.0704, F1: 0.5556

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.57924 | val 0.96404
  Epoch 016 - train 0.45793 | val 1.13729
  Classification -> best τ=0.465 (val F1=0.1433)
  Directional -> Accuracy: 0.5932, MCC: 0.2257, F1: 0.6923

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.55801 | val 2.68979
  Epoch 016 - train 0.45023 | val 5.15564
  Classification -> best τ=0.290 (val F1=0.3558)
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.62902 | val 0.72060
  Epoch 018 - train 0.54473 | val 0.93739
  Classification -> best τ=0.260 (val F1=0.3134)
  Directional -> Accuracy: 0.5082, MCC: 0.0081, F1: 0.6250

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.51354 | val 7.15903
  Epoch 016 - train 0.44220 | val 9.46784
  Classification -> best τ=0.605 (val F1=0.1616)
  Directional -> Accuracy: 0.5094, MCC: -0.1310, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.54768 | val 1.86783
  Epoch 016 - train 0.47228 | val 2.54671
  Classification -> best τ=0.310 (val F1=0.2927)
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.57033 | val 3.07540
  Epoch 016 - train 0.51032 | val 3.32907
  Classification -> best τ=0.830 (val F1=0.1259)
  Directional -> Accuracy: 0.3833, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.59176 | val 1.43099
  Epoch 016 - train 0.53335 | val 1.74910
  Classification -> best τ=0.475 (val F1=0.1800)
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.57284 | val 1.21440
  Epoch 016 - train 0.52421 | val 1.41184
  Classification -> best τ=0.615 (val F1=0.2249)
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 16). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.53985 | val 0.88012
  Epoch 019 - train 0.41707 | val 1.66479
  Classification -> best τ=0.105 (val F1=0.2913)
  Directional -> Accuracy: 0.4605, MCC: -0.0130, F1: 0.0465

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.54532 | val 1.65654
  Epoch 016 - train 0.44412 | val 2.48687
  Classification -> best τ=0.405 (val F1=0.3143)
  Directional -> Accuracy: 0.6458, MCC: 0.3630, F1: 0.6531

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.56971 | val 4.18404
  Epoch 016 - train 0.54614 | val 4.85420
  Classification -> best τ=0.830 (val F1=0.1287)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.52351 | val 1.20132
  Epoch 016 - train 0.44394 | val 1.55484
  Classification -> best τ=0.510 (val F1=0.2601)
  Directional -> Accuracy: 0.5862, MCC: 0.1166, F1: 0.6923

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.57191 | val 2.95775
  Epoch 016 - train 0.50798 | val 3.15696
  Classification -> best τ=0.240 (val F1=0.2931)
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.51299 | val 1.05214
  Epoch 016 - train 0.39929 | val 1.10413
  Classification -> best τ=0.480 (val F1=0.4595)
  Directional -> Accuracy: 0.5536, MCC: 0.2064, F1: 0.4186

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.50703 | val 2.15082
  Epoch 016 - train 0.38702 | val 3.62397
  Classification -> best τ=0.505 (val F1=0.2582)
  Directional -> Accuracy: 0.5532, MCC: -0.1269, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.58810 | val 1.37753
  Epoch 020 - train 0.49739 | val 3.23998
  Classification -> best τ=0.480 (val F1=0.2151)
  Directional -> Accuracy: 0.5814, MCC: 0.0528, F1: 0.7188

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.57930 | val 0.86981
  Epoch 016 - train 0.48080 | val 1.39975
  Classification -> best τ=0.470 (val F1=0.2655)
  Directional -> Accuracy: 0.4655, MCC: 0.1194, F1: 0.0606

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.53634 | val 0.80198
  Epoch 020 - train 0.45256 | val 0.98657
  Classification -> best τ=0.675 (val F1=0.3548)
  Directional -> Accuracy: 0.5476, MCC: 0.1353, F1: 0.4865

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.47399 | val 1.52871
  Epoch 016 - train 0.34203 | val 1.58992
  Classification -> best τ=0.690 (val F1=0.1869)
  Directional -> Accuracy: 0.5227, MCC: 0.0902, F1: 0.1600

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.62406 | val 1.51221
  Epoch 016 - train 0.48327 | val 1.53218
  Classification -> best τ=0.460 (val F1=0.0296)
  Directional -> Accuracy: 0.4545, MCC: -0.1683, F1: 0.5862

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.51203 | val 1.08694
  Epoch 016 - train 0.44404 | val 1.34603
  Classification -> best τ=0.470 (val F1=0.1866)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.56385 | val 3.92853
  Epoch 016 - train 0.46828 | val 5.31425
  Classification -> best τ=0.505 (val F1=0.3134)
  Directional -> Accuracy: 0.5405, MCC: 0.1770, F1: 0.4333

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.56703 | val 3.00591
  Epoch 016 - train 0.42613 | val 3.95317
  Classification -> best τ=0.440 (val F1=0.3130)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.5366

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.49686 | val 1.28704
  Epoch 016 - train 0.47337 | val 2.11370
  Classification -> best τ=0.600 (val F1=0.3359)
  Directional -> Accuracy: 0.6222, MCC: 0.2500, F1: 0.6222

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.58459 | val 0.70229
  Epoch 016 - train 0.48361 | val 0.90940
  Classification -> best τ=0.240 (val F1=0.3767)
  Directional -> Accuracy: 0.5970, MCC: 0.1641, F1: 0.6667

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.56546 | val 0.80398
  Epoch 016 - train 0.47925 | val 1.40195
  Classification -> best τ=0.460 (val F1=0.1834)
  Directional -> Accuracy: 0.6047, MCC: 0.2379, F1: 0.5143

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.56982 | val 0.67994
  Epoch 020 - train 0.45588 | val 0.84031
  Classification -> best τ=0.520 (val F1=0.3441)
  Directional -> Accuracy: 0.5614, MCC: 0.1968, F1: 0.6575

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.54412 | val 3.71820
  Epoch 016 - train 0.45830 | val 4.99601
  Classification -> best τ=0.560 (val F1=0.2718)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 16). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.50940 | val 1.24137
  Epoch 019 - train 0.36672 | val 1.41945
  Classification -> best τ=0.395 (val F1=0.4247)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.51862 | val 1.32089
  Epoch 016 - train 0.46453 | val 1.95509
  Classification -> best τ=0.455 (val F1=0.1870)
  Directional -> Accuracy: 0.5897, MCC: 0.1755, F1: 0.7037

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 16). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.60656 | val 1.28217
  Epoch 016 - train 0.54361 | val 2.59070
  Classification -> best τ=0.475 (val F1=0.2480)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.59064 | val 1.22808
  Epoch 016 - train 0.45203 | val 1.28035
  Classification -> best τ=0.605 (val F1=0.1733)
  Directional -> Accuracy: 0.5106, MCC: 0.0815, F1: 0.1481

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.51067 | val 2.91688
  Epoch 016 - train 0.38897 | val 3.63564
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.48293 | val 0.96972
  Epoch 017 - train 0.40264 | val 1.39580
  Classification -> best τ=0.490 (val F1=0.2219)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.60583 | val 2.33880
  Epoch 017 - train 0.57782 | val 2.81262
  Classification -> best τ=0.530 (val F1=0.1059)
  Directional -> Accuracy: 0.4737, MCC: 0.1224, F1: 0.0625

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.51731 | val 1.59484
  Epoch 016 - train 0.47064 | val 1.99162
  Classification -> best τ=0.470 (val F1=0.2554)
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.58381 | val 0.72141
  Epoch 017 - train 0.49623 | val 0.93247
  Classification -> best τ=0.545 (val F1=0.1053)
  Directional -> Accuracy: 0.4630, MCC: -0.0891, F1: 0.5397

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.59716 | val 0.73575
  Epoch 020 - train 0.41998 | val 1.18513
  Classification -> best τ=0.645 (val F1=0.3160)
  Directional -> Accuracy: 0.4737, MCC: -0.0671, F1: 0.5714

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.57860 | val 1.97522

[I 2026-02-24 22:48:04,867] Trial 25 finished with value: 0.24551647027717416 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 15, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.4, 'dropout': 0.6000000000000001, 'batch_size': 16, 'learning_rate': 0.004213619201000958, 'weight_decay': 5.415828634670226e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 1.5361104788283204, 'early_stopping_min_delta': 0.009148901570559755}. Best is trial 24 with value: 0.2654562368520373.

  Epoch 016 - train 0.51499 | val 2.23173
  Classification -> best τ=0.600 (val F1=0.1507)
  Directional -> Accuracy: 0.4677, MCC: -0.0754, F1: 0.3774

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.24551647027717416
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 15
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.59953 | val 1.03520
  Epoch 016 - train 0.52218 | val 1.67805
  Classification -> best τ=0.605 (val F1=0.2851)
  Directional -> Accuracy: 0.5455, MCC: 0.0214, F1: 0.1026

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.56173 | val 1.16534
  Epoch 016 - train 0.52814 | val 1.41118
  Classification -> best τ=0.465 (val F1=0.1164)
  Directional -> Accuracy: 0.6087, MCC: 0.2431, F1: 0.7429

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 16). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.60889 | val 0.86158
  Epoch 016 - train 0.56895 | val 1.03325
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5417, MCC: 0.0000, F1: 0.7027

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.63972 | val 1.57837
  Epoch 016 - train 0.56639 | val 2.36854
  Classification -> best τ=0.470 (val F1=0.0784)
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.54241 | val 0.74101
  Epoch 017 - train 0.49601 | val 0.83753
  Classification -> best τ=0.425 (val F1=0.5065)
  Directional -> Accuracy: 0.7500, MCC: 0.5138, F1: 0.7451

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.54589 | val 2.75569
  Epoch 016 - train 0.47135 | val 3.85644
  Classification -> best τ=0.590 (val F1=0.2485)
  Directional -> Accuracy: 0.5625, MCC: 0.2582, F1: 0.2222

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.61180 | val 1.14199
  Epoch 016 - train 0.59107 | val 1.50908
  Classification -> best τ=0.415 (val F1=0.3228)
  Directional -> Accuracy: 0.4857, MCC: 0.0503, F1: 0.5263

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 16). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.54643 | val 2.79828
  Epoch 016 - train 0.48446 | val 4.27418
  Classification -> best τ=0.530 (val F1=0.3368)
  Directional -> Accuracy: 0.5556, MCC: 0.1469, F1: 0.5652

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.60255 | val 0.92700
  Epoch 016 - train 0.55741 | val 0.94316
  Classification -> best τ=0.540 (val F1=0.4273)
  Directional -> Accuracy: 0.6341, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 16). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 16). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.58174 | val 1.07899
  Epoch 016 - train 0.52660 | val 1.29858
  Classification -> best τ=0.405 (val F1=0.2602)
  Directional -> Accuracy: 0.4366, MCC: 0.0000, F1: 0.6078

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.56263 | val 1.92325
  Epoch 016 - train 0.57394 | val 2.44829
  Classification -> best τ=0.530 (val F1=0.1090)
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.6400

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.57640 | val 1.39430
  Epoch 016 - train 0.53199 | val 1.34427
  Classification -> best τ=0.405 (val F1=0.2202)
  Directional -> Accuracy: 0.5085, MCC: 0.0000, F1: 0.6742

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.57199 | val 2.50312
  Epoch 016 - train 0.54837 | val 3.37621
  Classification -> best τ=0.515 (val F1=0.2308)
  Directional -> Accuracy: 0.5581, MCC: 0.0560, F1: 0.2963

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.63337 | val 0.71799
  Epoch 018 - train 0.53216 | val 0.87086
  Classification -> best τ=0.360 (val F1=0.3286)
  Directional -> Accuracy: 0.5410, MCC: 0.0906, F1: 0.6500

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.55532 | val 3.76536
  Epoch 016 - train 0.49342 | val 5.90135
  Classification -> best τ=0.600 (val F1=0.2879)
  Directional -> Accuracy: 0.5283, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.55190 | val 1.25588
  Epoch 016 - train 0.51858 | val 1.13089
  Classification -> best τ=0.605 (val F1=0.2827)
  Directional -> Accuracy: 0.6143, MCC: 0.2347, F1: 0.6197

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.59029 | val 1.36015
  Epoch 016 - train 0.57089 | val 1.55121
  Classification -> best τ=0.485 (val F1=0.0578)
  Directional -> Accuracy: 0.6333, MCC: 0.1406, F1: 0.7556

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.59697 | val 1.01434
  Epoch 016 - train 0.54399 | val 1.08879
  Classification -> best τ=0.380 (val F1=0.1039)
  Directional -> Accuracy: 0.5658, MCC: 0.0053, F1: 0.6916

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.58299 | val 1.24531
  Epoch 016 - train 0.53756 | val 1.39332
  Classification -> best τ=0.540 (val F1=0.2249)
  Directional -> Accuracy: 0.4545, MCC: 0.1218, F1: 0.1818

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 16). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.55163 | val 1.00856
  Epoch 016 - train 0.46918 | val 0.87308
  Classification -> best τ=0.520 (val F1=0.2602)
  Directional -> Accuracy: 0.4605, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.56939 | val 1.92535
  Epoch 016 - train 0.54306 | val 2.21293
  Classification -> best τ=0.495 (val F1=0.2046)
  Directional -> Accuracy: 0.5417, MCC: 0.2914, F1: 0.4500

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.60893 | val 1.82357
  Epoch 016 - train 0.55230 | val 2.17993
  Classification -> best τ=0.590 (val F1=0.2595)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.61533 | val 0.85319
  Epoch 017 - train 0.54915 | val 1.01617
  Classification -> best τ=0.595 (val F1=0.2272)
  Directional -> Accuracy: 0.5000, MCC: 0.0455, F1: 0.4528

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.55851 | val 2.23839
  Epoch 016 - train 0.50923 | val 2.63024
  Classification -> best τ=0.340 (val F1=0.2086)
  Directional -> Accuracy: 0.5758, MCC: 0.1867, F1: 0.6316

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.56293 | val 0.91709
  Epoch 017 - train 0.50634 | val 0.92165
  Classification -> best τ=0.515 (val F1=0.5018)
  Directional -> Accuracy: 0.5536, MCC: 0.2064, F1: 0.4186

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.54966 | val 1.42830
  Epoch 016 - train 0.50820 | val 1.58211
  Classification -> best τ=0.480 (val F1=0.2894)
  Directional -> Accuracy: 0.5319, MCC: -0.0268, F1: 0.2667

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.61256 | val 0.99988
  Epoch 016 - train 0.57558 | val 1.52170
  Classification -> best τ=0.530 (val F1=0.1377)
  Directional -> Accuracy: 0.6047, MCC: 0.1377, F1: 0.7385

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.58487 | val 0.79666
  Epoch 017 - train 0.57734 | val 0.86302
  Classification -> best τ=0.370 (val F1=0.2673)
  Directional -> Accuracy: 0.5517, MCC: 0.2600, F1: 0.3500

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.60285 | val 0.70597
  Epoch 016 - train 0.57251 | val 0.73777
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.7077

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.58578 | val 1.12483
  Epoch 016 - train 0.53806 | val 1.22410
  Classification -> best τ=0.535 (val F1=0.2263)
  Directional -> Accuracy: 0.4773, MCC: -0.0459, F1: 0.4390

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.60364 | val 1.02769
  Epoch 016 - train 0.56423 | val 1.19595
  Classification -> best τ=0.530 (val F1=0.1778)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.58459 | val 0.85705
  Epoch 016 - train 0.53652 | val 0.97417
  Classification -> best τ=0.580 (val F1=0.2320)
  Directional -> Accuracy: 0.4314, MCC: -0.1245, F1: 0.3256

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.57444 | val 1.04873
  Epoch 016 - train 0.52639 | val 2.16123
  Classification -> best τ=0.415 (val F1=0.2658)
  Directional -> Accuracy: 0.5270, MCC: 0.1525, F1: 0.4068

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.60078 | val 1.64793
  Epoch 016 - train 0.53776 | val 2.15106
  Classification -> best τ=0.500 (val F1=0.3337)
  Directional -> Accuracy: 0.4737, MCC: -0.0679, F1: 0.2308

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.59599 | val 1.32227
  Epoch 016 - train 0.53678 | val 1.58479
  Classification -> best τ=0.570 (val F1=0.2357)
  Directional -> Accuracy: 0.5556, MCC: 0.0980, F1: 0.4737

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.58719 | val 0.81157
  Epoch 016 - train 0.51812 | val 0.82252
  Classification -> best τ=0.400 (val F1=0.3521)
  Directional -> Accuracy: 0.6418, MCC: 0.2566, F1: 0.7073

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.62320 | val 0.67816
  Epoch 018 - train 0.55846 | val 0.71939
  Classification -> best τ=0.465 (val F1=0.3265)
  Directional -> Accuracy: 0.6744, MCC: 0.3514, F1: 0.6667

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.59801 | val 0.71694
  Epoch 016 - train 0.53638 | val 0.83450
  Classification -> best τ=0.405 (val F1=0.1508)
  Directional -> Accuracy: 0.4737, MCC: -0.0418, F1: 0.5161

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.58088 | val 2.06468
  Epoch 016 - train 0.48876 | val 3.00607
  Classification -> best τ=0.545 (val F1=0.2676)
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 16). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.52842 | val 0.66173
  Epoch 020 - train 0.46248 | val 0.76818
  Classification -> best τ=0.405 (val F1=0.4247)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.57382 | val 0.96384
  Epoch 016 - train 0.56472 | val 1.29815
  Classification -> best τ=0.500 (val F1=0.1870)
  Directional -> Accuracy: 0.5128, MCC: -0.0473, F1: 0.6545

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 16). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.61581 | val 1.46118
  Epoch 016 - train 0.51779 | val 2.75950
  Classification -> best τ=0.490 (val F1=0.2662)
  Directional -> Accuracy: 0.4868, MCC: -0.0265, F1: 0.5185

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.59394 | val 0.93102
  Epoch 016 - train 0.56541 | val 1.10120
  Classification -> best τ=0.470 (val F1=0.3086)
  Directional -> Accuracy: 0.5106, MCC: 0.1443, F1: 0.0800

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.59690 | val 1.30568
  Epoch 016 - train 0.49666 | val 1.62187
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.56235 | val 0.71437
  Epoch 016 - train 0.50497 | val 0.78042
  Classification -> best τ=0.550 (val F1=0.0675)
  Directional -> Accuracy: 0.6500, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.62641 | val 1.17685
  Epoch 016 - train 0.56695 | val 1.22005
  Classification -> best τ=0.525 (val F1=0.1869)
  Directional -> Accuracy: 0.4561, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.57010 | val 1.15555
  Epoch 016 - train 0.51590 | val 1.26442
  Classification -> best τ=0.500 (val F1=0.4276)
  Directional -> Accuracy: 0.5088, MCC: 0.0223, F1: 0.5172

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.60693 | val 0.70433
  Epoch 020 - train 0.51387 | val 0.92032
  Classification -> best τ=0.445 (val F1=0.2228)
  Directional -> Accuracy: 0.5000, MCC: -0.0409, F1: 0.6400

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.60173 | val 0.80948
  Epoch 020 - train 0.49956 | val 0.73259
  Classification -> best τ=0.590 (val F1=0.3652)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.60943 | val 1.40202

[I 2026-02-24 22:48:59,048] Trial 26 finished with value: 0.23953347942252612 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 15, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.6000000000000001, 'batch_size': 16, 'learning_rate': 0.0010488801232279759, 'weight_decay': 9.515617759117426e-06, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 1.8257084840510274, 'early_stopping_min_delta': 0.00878523304778227}. Best is trial 24 with value: 0.2654562368520373.

  Epoch 016 - train 0.54873 | val 1.19404
  Classification -> best τ=0.530 (val F1=0.1676)
  Directional -> Accuracy: 0.4839, MCC: 0.0000, F1: 0.6522

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.23953347942252612
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 15
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.64161 | val 1.05275
  Epoch 017 - train 0.51796 | val 1.84534
  Classification -> best τ=0.420 (val F1=0.2067)
  Directional -> Accuracy: 0.4805, MCC: 0.0962, F1: 0.6296

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.45175 | val 0.98999
  Epoch 016 - train 0.29861 | val 1.76123
  Classification -> best τ=0.515 (val F1=0.0793)
  Directional -> Accuracy: 0.5217, MCC: 0.0040, F1: 0.6071

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 16). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.51061 | val 1.51590
  Epoch 016 - train 0.36828 | val 1.50055
  Classification -> best τ=0.650 (val F1=0.2892)
  Directional -> Accuracy: 0.4583, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.61634 | val 1.64384
  Epoch 016 - train 0.44503 | val 2.96644
  Classification -> best τ=0.385 (val F1=0.2232)
  Directional -> Accuracy: 0.4933, MCC: -0.0274, F1: 0.5476

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.40375 | val 0.82169
  Epoch 017 - train 0.22922 | val 1.79783
  Classification -> best τ=0.455 (val F1=0.3516)
  Directional -> Accuracy: 0.7115, MCC: 0.4173, F1: 0.7458

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.35121 | val 2.53507
  Epoch 016 - train 0.22961 | val 5.02081
  Classification -> best τ=0.560 (val F1=0.1789)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0769

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.51279 | val 1.65347
  Epoch 016 - train 0.30619 | val 3.56697
  Classification -> best τ=0.470 (val F1=0.2143)
  Directional -> Accuracy: 0.5286, MCC: 0.1527, F1: 0.5714

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 16). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.30797 | val 7.11280
  Epoch 016 - train 0.13465 | val 11.72825
  Classification -> best τ=0.540 (val F1=0.3780)
  Directional -> Accuracy: 0.4222, MCC: -0.0618, F1: 0.5517

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.57361 | val 1.56685
  Epoch 016 - train 0.40337 | val 2.99240
  Classification -> best τ=0.495 (val F1=0.2345)
  Directional -> Accuracy: 0.6341, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 16). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 16). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.52200 | val 1.98337
  Epoch 016 - train 0.41197 | val 0.99037
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4366, MCC: 0.0000, F1: 0.6078

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.51514 | val 1.75475
  Epoch 016 - train 0.34881 | val 2.30664
  Classification -> best τ=0.510 (val F1=0.1835)
  Directional -> Accuracy: 0.4706, MCC: -0.1273, F1: 0.1818

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.62908 | val 0.72731
  Epoch 020 - train 0.41826 | val 1.66206
  Classification -> best τ=0.770 (val F1=0.3257)
  Directional -> Accuracy: 0.6780, MCC: 0.3769, F1: 0.6275

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.43747 | val 3.18300
  Epoch 016 - train 0.33717 | val 3.75256
  Classification -> best τ=0.525 (val F1=0.1700)
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.67164 | val 0.88953
  Epoch 017 - train 0.40697 | val 2.09144
  Classification -> best τ=0.405 (val F1=0.3383)
  Directional -> Accuracy: 0.5574, MCC: 0.1602, F1: 0.6824

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.49546 | val 2.36946
  Epoch 016 - train 0.31671 | val 5.49691
  Classification -> best τ=0.630 (val F1=0.2798)
  Directional -> Accuracy: 0.5283, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.51722 | val 1.75008
  Epoch 016 - train 0.35980 | val 3.67715
  Classification -> best τ=0.745 (val F1=0.3541)
  Directional -> Accuracy: 0.4857, MCC: 0.0035, F1: 0.4000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.60076 | val 1.64600
  Epoch 016 - train 0.45068 | val 2.56833
  Classification -> best τ=0.610 (val F1=0.2219)
  Directional -> Accuracy: 0.3833, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.53472 | val 1.29804
  Epoch 016 - train 0.49715 | val 1.30239
  Classification -> best τ=0.375 (val F1=0.1917)
  Directional -> Accuracy: 0.5921, MCC: 0.0621, F1: 0.7156

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.55324 | val 1.92718
  Epoch 016 - train 0.39986 | val 2.47629
  Classification -> best τ=0.520 (val F1=0.2249)
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 16). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.42428 | val 1.07548
  Epoch 016 - train 0.30603 | val 1.57953
  Classification -> best τ=0.530 (val F1=0.1566)
  Directional -> Accuracy: 0.5000, MCC: -0.1117, F1: 0.6545

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.51715 | val 2.83391
  Epoch 016 - train 0.38198 | val 7.64471
  Classification -> best τ=0.415 (val F1=0.1687)
  Directional -> Accuracy: 0.5000, MCC: 0.1854, F1: 0.4000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.56944 | val 1.01585
  Epoch 016 - train 0.41907 | val 3.09729
  Classification -> best τ=0.450 (val F1=0.1177)
  Directional -> Accuracy: 0.5606, MCC: 0.1690, F1: 0.6742

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.48733 | val 1.68353
  Epoch 016 - train 0.28311 | val 3.54009
  Classification -> best τ=0.680 (val F1=0.3198)
  Directional -> Accuracy: 0.5517, MCC: 0.1248, F1: 0.5517

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.44539 | val 2.86366
  Epoch 016 - train 0.33659 | val 3.05009
  Classification -> best τ=0.450 (val F1=0.2699)
  Directional -> Accuracy: 0.5303, MCC: 0.0665, F1: 0.5373

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.47976 | val 1.95762
  Epoch 016 - train 0.37987 | val 2.67120
  Classification -> best τ=0.485 (val F1=0.3976)
  Directional -> Accuracy: 0.5536, MCC: 0.2064, F1: 0.4186

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.32520 | val 2.17993
  Epoch 016 - train 0.09841 | val 3.46097
  Classification -> best τ=0.490 (val F1=0.2471)
  Directional -> Accuracy: 0.5745, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.46984 | val 0.83954
  Epoch 016 - train 0.41609 | val 1.16856
  Classification -> best τ=0.535 (val F1=0.2151)
  Directional -> Accuracy: 0.5349, MCC: 0.0593, F1: 0.5833

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.54704 | val 0.86497
  Epoch 018 - train 0.38664 | val 2.16571
  Classification -> best τ=0.360 (val F1=0.3133)
  Directional -> Accuracy: 0.4655, MCC: 0.0540, F1: 0.1143

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.44534 | val 2.12128
  Epoch 016 - train 0.26674 | val 3.16038
  Classification -> best τ=0.520 (val F1=0.3158)
  Directional -> Accuracy: 0.5714, MCC: 0.1158, F1: 0.6538

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.34094 | val 1.72169
  Epoch 016 - train 0.22374 | val 2.13422
  Classification -> best τ=0.625 (val F1=0.1869)
  Directional -> Accuracy: 0.5455, MCC: 0.2182, F1: 0.1667

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.35983 | val 2.13856
  Epoch 016 - train 0.22043 | val 2.91432
  Classification -> best τ=0.615 (val F1=0.1239)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.38633 | val 1.27814
  Epoch 016 - train 0.37272 | val 1.50702
  Classification -> best τ=0.600 (val F1=0.2320)
  Directional -> Accuracy: 0.4314, MCC: -0.1280, F1: 0.2162

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.62410 | val 1.41849
  Epoch 017 - train 0.38550 | val 2.60948
  Classification -> best τ=0.345 (val F1=0.3679)
  Directional -> Accuracy: 0.5135, MCC: 0.0710, F1: 0.4706

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.38961 | val 3.19553
  Epoch 016 - train 0.13648 | val 5.37953
  Classification -> best τ=0.345 (val F1=0.2550)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.42405 | val 2.76434
  Epoch 016 - train 0.25477 | val 3.04979
  Classification -> best τ=0.405 (val F1=0.2017)
  Directional -> Accuracy: 0.5333, MCC: 0.1048, F1: 0.6038

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.54721 | val 1.16703
  Epoch 017 - train 0.34715 | val 1.59549
  Classification -> best τ=0.110 (val F1=0.3767)
  Directional -> Accuracy: 0.5522, MCC: 0.0591, F1: 0.6429

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.38186 | val 2.28444
  Epoch 016 - train 0.19563 | val 2.29306
  Classification -> best τ=0.485 (val F1=0.0621)
  Directional -> Accuracy: 0.6512, MCC: 0.3392, F1: 0.5714

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.47525 | val 0.84565
  Epoch 016 - train 0.33894 | val 1.18797
  Classification -> best τ=0.525 (val F1=0.1706)
  Directional -> Accuracy: 0.5965, MCC: 0.1861, F1: 0.5306

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.40887 | val 1.01532
  Epoch 016 - train 0.18434 | val 3.09726
  Classification -> best τ=0.550 (val F1=0.4174)
  Directional -> Accuracy: 0.5957, MCC: -0.0267, F1: 0.7397

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 16). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.38649 | val 1.53482
  Epoch 016 - train 0.22625 | val 2.08997
  Classification -> best τ=0.460 (val F1=0.1391)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.29867 | val 1.68991
  Epoch 016 - train 0.13542 | val 2.98065
  Classification -> best τ=0.505 (val F1=0.1870)
  Directional -> Accuracy: 0.5128, MCC: 0.0000, F1: 0.5957

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 16). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.54612 | val 2.30031
  Epoch 017 - train 0.34759 | val 3.00638
  Classification -> best τ=0.350 (val F1=0.3763)
  Directional -> Accuracy: 0.5263, MCC: 0.1179, F1: 0.6727

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.49067 | val 1.79485
  Epoch 016 - train 0.24578 | val 1.25211
  Classification -> best τ=0.520 (val F1=0.3121)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.29128 | val 4.78338
  Epoch 016 - train 0.07889 | val 9.08368
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.28133 | val 2.46111
  Epoch 016 - train 0.12231 | val 3.88198
  Classification -> best τ=0.485 (val F1=0.4228)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.62182 | val 1.71969
  Epoch 016 - train 0.51708 | val 1.78195
  Classification -> best τ=0.440 (val F1=0.1685)
  Directional -> Accuracy: 0.5439, MCC: 0.0000, F1: 0.7045

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.51612 | val 2.53447
  Epoch 016 - train 0.39050 | val 2.56851
  Classification -> best τ=0.415 (val F1=0.2554)
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.56341 | val 1.77114
  Epoch 017 - train 0.37953 | val 3.10438
  Classification -> best τ=0.485 (val F1=0.0955)
  Directional -> Accuracy: 0.5741, MCC: 0.1448, F1: 0.6462

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.50578 | val 0.68630
  Epoch 020 - train 0.42244 | val 2.36577
  Classification -> best τ=0.260 (val F1=0.2671)
  Directional -> Accuracy: 0.4211, MCC: -0.1576, F1: 0.4211

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.56190 | val 0.75376

[I 2026-02-24 22:49:55,590] Trial 27 finished with value: 0.23616649801135067 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 15, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.1, 'batch_size': 16, 'learning_rate': 0.009097615107488905, 'weight_decay': 8.706402144555656e-07, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 1.6067413623593165, 'early_stopping_min_delta': 0.007596785635465979}. Best is trial 24 with value: 0.2654562368520373.

  Epoch 016 - train 0.41099 | val 1.84677
  Classification -> best τ=0.445 (val F1=0.2232)
  Directional -> Accuracy: 0.4516, MCC: -0.0913, F1: 0.5278

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.23616649801135067
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.62353 | val 0.79214
  Epoch 011 - train 0.62087 | val 0.78680
  Classification -> best τ=0.545 (val F1=0.2409)
  Directional -> Accuracy: 0.5395, MCC: -0.0253, F1: 0.1026

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.62789 | val 0.71465
  Epoch 014 - train 0.61207 | val 0.77296
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.64292 | val 0.67928
  Epoch 018 - train 0.62992 | val 0.71715
  Classification -> best τ=0.415 (val F1=0.4078)
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.63414 | val 1.26347
  Epoch 011 - train 0.63189 | val 1.30845
  Classification -> best τ=0.520 (val F1=0.1712)
  Directional -> Accuracy: 0.4267, MCC: -0.1414, F1: 0.0444

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.62510 | val 0.63095
  Epoch 020 - train 0.57826 | val 0.63640
  Classification -> best τ=0.540 (val F1=0.4051)
  Directional -> Accuracy: 0.6078, MCC: 0.2079, F1: 0.6667

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.62018 | val 0.71898
  Epoch 011 - train 0.60695 | val 0.72467
  Classification -> best τ=0.480 (val F1=0.2357)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.63588 | val 0.73241
  Epoch 011 - train 0.64236 | val 0.73650
  Classification -> best τ=0.465 (val F1=0.2280)
  Directional -> Accuracy: 0.5507, MCC: 0.1175, F1: 0.5231

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.62100 | val 0.71920
  Epoch 011 - train 0.62296 | val 0.72508
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.5902

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.64260 | val 0.67977
  Epoch 020 - train 0.59215 | val 0.69120
  Epoch 024 - train 0.57359 | val 0.70628
  Classification -> best τ=0.535 (val F1=0.4249)
  Directional -> Accuracy: 0.5714, MCC: 0.1118, F1: 0.1600

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.61393 | val 0.80661
  Epoch 011 - train 0.60699 | val 0.80405
  Classification -> best τ=0.480 (val F1=0.1004)
  Directional -> Accuracy: 0.5000, MCC: 0.0630, F1: 0.5570

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.60897 | val 0.78546
  Epoch 011 - train 0.59298 | val 0.81778
  Classification -> best τ=0.530 (val F1=0.2107)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.64170 | val 0.87038
  Epoch 011 - train 0.63017 | val 0.91456
  Classification -> best τ=0.500 (val F1=0.1421)
  Directional -> Accuracy: 0.6207, MCC: 0.2437, F1: 0.6452

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.61885 | val 0.89258
  Epoch 011 - train 0.60317 | val 0.92660
  Classification -> best τ=0.490 (val F1=0.1239)
  Directional -> Accuracy: 0.5476, MCC: 0.0751, F1: 0.4571

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.65486 | val 0.72140
  Epoch 014 - train 0.63562 | val 0.75698
  Classification -> best τ=0.510 (val F1=0.2667)
  Directional -> Accuracy: 0.5500, MCC: 0.1400, F1: 0.6667

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.62355 | val 0.71145
  Epoch 011 - train 0.62612 | val 0.72826
  Classification -> best τ=0.510 (val F1=0.0401)
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.61742 | val 0.73260
  Epoch 013 - train 0.60909 | val 0.76747
  Classification -> best τ=0.450 (val F1=0.2592)
  Directional -> Accuracy: 0.5362, MCC: 0.0000, F1: 0.6981

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.64658 | val 1.08987
  Epoch 011 - train 0.64535 | val 1.13041
  Classification -> best τ=0.530 (val F1=0.1842)
  Directional -> Accuracy: 0.3729, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.63700 | val 0.99111
  Epoch 011 - train 0.63939 | val 1.02627
  Classification -> best τ=0.535 (val F1=0.1354)
  Directional -> Accuracy: 0.5733, MCC: 0.1524, F1: 0.6098

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.64377 | val 0.77019
  Epoch 011 - train 0.64018 | val 0.77928
  Classification -> best τ=0.525 (val F1=0.1809)
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.63594 | val 0.67592
  Epoch 020 - train 0.59393 | val 0.66278
  Epoch 030 - train 0.55446 | val 0.66508
  Classification -> best τ=0.420 (val F1=0.3093)
  Directional -> Accuracy: 0.5467, MCC: 0.0854, F1: 0.5854

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.64531 | val 0.67964
  Epoch 020 - train 0.61757 | val 0.65926
  Epoch 030 - train 0.56460 | val 0.65590
  Classification -> best τ=0.595 (val F1=0.3315)
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.63998 | val 0.76893
  Epoch 011 - train 0.63093 | val 0.77129
  Classification -> best τ=0.515 (val F1=0.1167)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6526

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.65288 | val 0.72104
  Epoch 011 - train 0.65512 | val 0.71957
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.63596 | val 0.74704
  Epoch 011 - train 0.63004 | val 0.74827
  Classification -> best τ=0.525 (val F1=0.1507)
  Directional -> Accuracy: 0.5231, MCC: 0.0147, F1: 0.1622

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.63372 | val 0.65005
  Epoch 020 - train 0.58844 | val 0.63360
  Epoch 029 - train 0.56387 | val 0.63267
  Classification -> best τ=0.430 (val F1=0.4124)
  Directional -> Accuracy: 0.5179, MCC: 0.1188, F1: 0.3721

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.63944 | val 0.70173
  Epoch 011 - train 0.63090 | val 0.70345
  Classification -> best τ=0.460 (val F1=0.1131)
  Directional -> Accuracy: 0.6304, MCC: 0.3294, F1: 0.6667

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.64484 | val 0.77579
  Epoch 011 - train 0.63523 | val 0.77077
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.62727 | val 0.69705
  Epoch 011 - train 0.59946 | val 0.70723
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.64183 | val 0.71306
  Epoch 011 - train 0.63286 | val 0.72257
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.63848 | val 0.72770
  Epoch 011 - train 0.62266 | val 0.73585
  Classification -> best τ=0.520 (val F1=0.2017)
  Directional -> Accuracy: 0.5581, MCC: 0.1366, F1: 0.6275

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.64384 | val 0.72512
  Epoch 011 - train 0.64470 | val 0.73121
  Classification -> best τ=0.485 (val F1=0.0943)
  Directional -> Accuracy: 0.4419, MCC: -0.1297, F1: 0.5000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.60348 | val 0.70686
  Epoch 011 - train 0.60514 | val 0.70492
  Classification -> best τ=0.515 (val F1=0.1016)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.62626 | val 0.70378
  Epoch 015 - train 0.61073 | val 0.72681
  Classification -> best τ=0.460 (val F1=0.2983)
  Directional -> Accuracy: 0.5479, MCC: 0.1713, F1: 0.4590

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.60533 | val 0.78721
  Epoch 011 - train 0.63305 | val 0.81221
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.63855 | val 0.75294
  Epoch 011 - train 0.63159 | val 0.76247
  Classification -> best τ=0.530 (val F1=0.2358)
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.61452 | val 0.71118
  Epoch 013 - train 0.60614 | val 0.72464
  Classification -> best τ=0.455 (val F1=0.3855)
  Directional -> Accuracy: 0.5606, MCC: 0.0552, F1: 0.6667

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.61476 | val 0.69971
  Epoch 011 - train 0.62034 | val 0.70416
  Classification -> best τ=0.465 (val F1=0.1818)
  Directional -> Accuracy: 0.5952, MCC: 0.2656, F1: 0.4516

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.61803 | val 0.73961
  Epoch 016 - train 0.60738 | val 0.76364
  Classification -> best τ=0.565 (val F1=0.2332)
  Directional -> Accuracy: 0.5893, MCC: 0.1895, F1: 0.3030

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.60629 | val 0.79173
  Epoch 014 - train 0.58648 | val 0.99150
  Classification -> best τ=0.535 (val F1=0.4917)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.65094 | val 0.65768
  Epoch 020 - train 0.62025 | val 0.62359
  Epoch 030 - train 0.58773 | val 0.61628
  Classification -> best τ=0.325 (val F1=0.5125)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.64998 | val 0.70922
  Epoch 011 - train 0.65325 | val 0.71350
  Classification -> best τ=0.500 (val F1=0.1688)
  Directional -> Accuracy: 0.5135, MCC: 0.0726, F1: 0.4000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.61367 | val 0.75264
  Epoch 013 - train 0.59985 | val 0.77052
  Classification -> best τ=0.490 (val F1=0.2450)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.64020 | val 0.69651
  Epoch 011 - train 0.63791 | val 0.70555
  Classification -> best τ=0.455 (val F1=0.1909)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.0000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.61470 | val 0.74733
  Epoch 011 - train 0.59842 | val 0.75741
  Classification -> best τ=0.520 (val F1=0.5052)
  Directional -> Accuracy: 0.4651, MCC: -0.0027, F1: 0.3030

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.63145 | val 0.71682
  Epoch 011 - train 0.62822 | val 0.72319
  Classification -> best τ=0.520 (val F1=0.2689)
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.64755 | val 0.74317
  Epoch 011 - train 0.63936 | val 0.75388
  Classification -> best τ=0.510 (val F1=0.0811)
  Directional -> Accuracy: 0.3393, MCC: -0.3145, F1: 0.3019

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.63349 | val 0.74158
  Epoch 011 - train 0.61996 | val 0.74743
  Classification -> best τ=0.475 (val F1=0.1288)
  Directional -> Accuracy: 0.5179, MCC: 0.0287, F1: 0.4490

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.62877 | val 1.09511
  Epoch 011 - train 0.62432 | val 1.18506
  Classification -> best τ=0.490 (val F1=0.1139)
  Directional -> Accuracy: 0.4815, MCC: 0.0000, F1: 0.0000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.62358 | val 1.08017
  Epoch 011 - train 0.63470 | val 1.12660
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...

[I 2026-02-24 22:50:37,743] Trial 28 finished with value: 0.19779583585721255 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.4, 'dropout': 0.30000000000000004, 'batch_size': 32, 'learning_rate': 0.0002203835353731037, 'weight_decay': 2.573055626052897e-06, 'lr_patience': 7, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.8912368935079142, 'early_stopping_min_delta': 0.005841709524632293}. Best is trial 24 with value: 0.2654562368520373.

  Epoch 010 - train 0.64273 | val 0.73284
  Epoch 011 - train 0.62938 | val 0.73740
  Classification -> best τ=0.490 (val F1=0.2597)
  Directional -> Accuracy: 0.3770, MCC: -0.2430, F1: 0.3871

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.19779583585721255
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.67963 | val 0.79469
  Epoch 016 - train 0.67827 | val 0.80268
  Classification -> best τ=0.520 (val F1=0.1713)
  Directional -> Accuracy: 0.5526, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.71009 | val 0.67547
  Epoch 018 - train 0.69375 | val 0.67986
  Classification -> best τ=0.495 (val F1=0.3012)
  Directional -> Accuracy: 0.3333, MCC: -0.3654, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.68306 | val 0.70328
  Epoch 016 - train 0.67042 | val 0.69452
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.69197 | val 0.97061
  Epoch 016 - train 0.69469 | val 1.02399
  Classification -> best τ=0.435 (val F1=0.1964)
  Directional -> Accuracy: 0.4933, MCC: 0.0747, F1: 0.2692

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.68869 | val 0.68549
  Epoch 020 - train 0.67059 | val 0.66183
  Classification -> best τ=0.600 (val F1=0.3309)
  Directional -> Accuracy: 0.5294, MCC: 0.1477, F1: 0.2941

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.67179 | val 0.70769
  Epoch 016 - train 0.65886 | val 0.70715
  Classification -> best τ=0.460 (val F1=0.0778)
  Directional -> Accuracy: 0.4043, MCC: -0.2000, F1: 0.5000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.67633 | val 0.71809
  Epoch 016 - train 0.67748 | val 0.72867
  Classification -> best τ=0.490 (val F1=0.3314)
  Directional -> Accuracy: 0.5652, MCC: 0.1531, F1: 0.5455

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.70188 | val 0.62053
  Epoch 020 - train 0.67888 | val 0.63878
  Classification -> best τ=0.410 (val F1=0.1439)
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.70241 | val 0.78011
  Epoch 016 - train 0.67991 | val 0.77681
  Classification -> best τ=0.560 (val F1=0.1078)
  Directional -> Accuracy: 0.6735, MCC: 0.3373, F1: 0.5556

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.68765 | val 0.84558
  Epoch 016 - train 0.66956 | val 0.86579
  Classification -> best τ=0.420 (val F1=0.3204)
  Directional -> Accuracy: 0.4714, MCC: 0.0739, F1: 0.5934

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.71576 | val 0.88140
  Epoch 016 - train 0.70687 | val 0.93096
  Classification -> best τ=0.545 (val F1=0.1759)
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.6301

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.68325 | val 0.78290
  Epoch 016 - train 0.68879 | val 0.77517
  Classification -> best τ=0.545 (val F1=0.1703)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.70098 | val 0.99411
  Epoch 016 - train 0.69000 | val 0.99577
  Classification -> best τ=0.445 (val F1=0.2214)
  Directional -> Accuracy: 0.5476, MCC: 0.0605, F1: 0.3871

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.68334 | val 0.69438
  Epoch 016 - train 0.68368 | val 0.69751
  Classification -> best τ=0.540 (val F1=0.3026)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.2500

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.71395 | val 1.06996
  Epoch 016 - train 0.69857 | val 1.11727
  Classification -> best τ=0.555 (val F1=0.1769)
  Directional -> Accuracy: 0.6154, MCC: 0.2186, F1: 0.5000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.68205 | val 0.70467
  Epoch 016 - train 0.67448 | val 0.70919
  Classification -> best τ=0.530 (val F1=0.2100)
  Directional -> Accuracy: 0.5507, MCC: 0.0713, F1: 0.6804

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.67592 | val 0.86763
  Epoch 016 - train 0.66880 | val 0.88806
  Classification -> best τ=0.545 (val F1=0.1336)
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.68095 | val 0.69727
  Epoch 016 - train 0.67258 | val 0.69536
  Classification -> best τ=0.635 (val F1=0.1923)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.67195 | val 0.72559
  Epoch 016 - train 0.66815 | val 0.73692
  Classification -> best τ=0.450 (val F1=0.1241)
  Directional -> Accuracy: 0.5385, MCC: 0.2138, F1: 0.4231

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.66601 | val 0.71868
  Epoch 016 - train 0.66138 | val 0.73181
  Classification -> best τ=0.515 (val F1=0.1277)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.67606 | val 0.71508
  Epoch 016 - train 0.68969 | val 0.71134
  Classification -> best τ=0.515 (val F1=0.1496)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.68163 | val 0.80962
  Epoch 016 - train 0.69460 | val 0.82972
  Classification -> best τ=0.530 (val F1=0.1318)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.70265 | val 0.69691
  Epoch 016 - train 0.67741 | val 0.69940
  Classification -> best τ=0.575 (val F1=0.1268)
  Directional -> Accuracy: 0.3966, MCC: -0.1753, F1: 0.0541

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.67849 | val 1.43616
  Epoch 016 - train 0.69941 | val 1.27933
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4769, MCC: 0.0000, F1: 0.6458

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.68409 | val 0.66958
  Epoch 020 - train 0.67033 | val 0.65852
  Classification -> best τ=0.540 (val F1=0.4057)
  Directional -> Accuracy: 0.4821, MCC: 0.0435, F1: 0.2927

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.69743 | val 0.69909
  Epoch 016 - train 0.69342 | val 0.69935
  Classification -> best τ=0.480 (val F1=0.0626)
  Directional -> Accuracy: 0.5217, MCC: -0.1870, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.66354 | val 0.68767
  Epoch 016 - train 0.67339 | val 0.69310
  Classification -> best τ=0.500 (val F1=0.1936)
  Directional -> Accuracy: 0.4524, MCC: -0.0574, F1: 0.4103

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.69183 | val 0.68908
  Epoch 020 - train 0.66453 | val 0.68262
  Classification -> best τ=0.580 (val F1=0.2506)
  Directional -> Accuracy: 0.5088, MCC: 0.0801, F1: 0.4167

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.70893 | val 0.72061
  Epoch 016 - train 0.68197 | val 0.71973
  Classification -> best τ=0.465 (val F1=0.1457)
  Directional -> Accuracy: 0.5366, MCC: 0.0587, F1: 0.5957

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.70676 | val 0.66739
  Epoch 020 - train 0.69796 | val 0.66504
  Classification -> best τ=0.440 (val F1=0.3501)
  Directional -> Accuracy: 0.5349, MCC: 0.1249, F1: 0.6552

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.72121 | val 0.67632
  Epoch 019 - train 0.69024 | val 0.67845
  Classification -> best τ=0.620 (val F1=0.1204)
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.69137 | val 0.66727
  Epoch 020 - train 0.66752 | val 0.66172
  Classification -> best τ=0.455 (val F1=0.3502)
  Directional -> Accuracy: 0.5200, MCC: 0.0537, F1: 0.5000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.67952 | val 0.73028
  Epoch 016 - train 0.67703 | val 0.72382
  Classification -> best τ=0.555 (val F1=0.0953)
  Directional -> Accuracy: 0.4658, MCC: 0.0914, F1: 0.1333

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.67563 | val 0.70679
  Epoch 016 - train 0.69660 | val 0.70993
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.69497 | val 0.84462
  Epoch 016 - train 0.67668 | val 0.90020
  Classification -> best τ=0.465 (val F1=0.1902)
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.67484 | val 0.68278
  Epoch 020 - train 0.64654 | val 0.68943
  Classification -> best τ=0.440 (val F1=0.2410)
  Directional -> Accuracy: 0.4242, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.70106 | val 0.73283
  Epoch 016 - train 0.70067 | val 0.72168
  Classification -> best τ=0.475 (val F1=0.0215)
  Directional -> Accuracy: 0.5952, MCC: 0.1961, F1: 0.5854

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.69427 | val 0.81140
  Epoch 016 - train 0.67609 | val 0.79219
  Classification -> best τ=0.540 (val F1=0.1886)
  Directional -> Accuracy: 0.5714, MCC: 0.1385, F1: 0.5385

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.70994 | val 0.69222
  Epoch 016 - train 0.69870 | val 0.69300
  Classification -> best τ=0.470 (val F1=0.1055)
  Directional -> Accuracy: 0.3913, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.70229 | val 0.73107
  Epoch 016 - train 0.69009 | val 0.72618
  Classification -> best τ=0.480 (val F1=0.1477)
  Directional -> Accuracy: 0.3673, MCC: -0.1393, F1: 0.4561

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.70404 | val 0.69272
  Epoch 016 - train 0.68472 | val 0.69655
  Classification -> best τ=0.455 (val F1=0.1132)
  Directional -> Accuracy: 0.5135, MCC: -0.0299, F1: 0.6400

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.67307 | val 0.68397
  Epoch 020 - train 0.65880 | val 0.67739
  Classification -> best τ=0.570 (val F1=0.2397)
  Directional -> Accuracy: 0.5067, MCC: 0.0499, F1: 0.6542

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.67673 | val 0.70111
  Epoch 016 - train 0.68463 | val 0.69276
  Classification -> best τ=0.510 (val F1=0.2058)
  Directional -> Accuracy: 0.5652, MCC: 0.1241, F1: 0.6154

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.68576 | val 0.70019
  Epoch 016 - train 0.65631 | val 0.70464
  Classification -> best τ=0.525 (val F1=0.3651)
  Directional -> Accuracy: 0.4186, MCC: -0.1150, F1: 0.1935

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.71397 | val 0.73553
  Epoch 016 - train 0.70093 | val 0.74539
  Classification -> best τ=0.450 (val F1=0.5421)
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.68537 | val 0.71479
  Epoch 016 - train 0.68274 | val 0.71954
  Classification -> best τ=0.535 (val F1=0.0422)
  Directional -> Accuracy: 0.3750, MCC: -0.2598, F1: 0.4262

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.66989 | val 0.82116
  Epoch 016 - train 0.67837 | val 0.88760
  Classification -> best τ=0.525 (val F1=0.3307)
  Directional -> Accuracy: 0.5000, MCC: -0.0515, F1: 0.1250

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.68350 | val 0.75787
  Epoch 016 - train 0.68194 | val 0.77275
  Classification -> best τ=0.500 (val F1=0.0906)
  Directional -> Accuracy: 0.5000, MCC: -0.0148, F1: 0.5846

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.67606 | val 1.12507
  Epoch 016 - train 0.67541 | val 1.17074
  Classification -> best τ=0.590 (val F1=0.0913)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.67831 | val 0.79320

[I 2026-02-24 22:51:40,299] Trial 29 finished with value: 0.18443133139922768 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.4, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 2.674324260773321e-05, 'weight_decay': 2.6771185671148874e-07, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 1.8181777030365023, 'early_stopping_min_delta': 0.009919409240872059}. Best is trial 24 with value: 0.2654562368520373.

  Epoch 016 - train 0.66819 | val 0.79387
  Classification -> best τ=0.485 (val F1=0.1077)
  Directional -> Accuracy: 0.4754, MCC: -0.0191, F1: 0.6098

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.18443133139922768
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 15
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.64518 | val 0.67445
  Epoch 014 - train 0.61723 | val 0.67411
  Classification -> best τ=0.540 (val F1=0.2931)
  Directional -> Accuracy: 0.5325, MCC: 0.0398, F1: 0.4194

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.64662 | val 0.71140
  Epoch 012 - train 0.59467 | val 0.84970
  Classification -> best τ=0.550 (val F1=0.1236)
  Directional -> Accuracy: 0.5652, MCC: 0.1260, F1: 0.6000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 16). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.66738 | val 0.73368
  Epoch 016 - train 0.61444 | val 0.73587
  Classification -> best τ=0.540 (val F1=0.3244)
  Directional -> Accuracy: 0.4583, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.67307 | val 1.02796
  Epoch 012 - train 0.66005 | val 1.24753
  Classification -> best τ=0.515 (val F1=0.1864)
  Directional -> Accuracy: 0.5333, MCC: 0.0561, F1: 0.5783

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.58763 | val 0.84425
  Epoch 012 - train 0.62888 | val 0.75603
  Classification -> best τ=0.455 (val F1=0.4345)
  Directional -> Accuracy: 0.7885, MCC: 0.5793, F1: 0.8197

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.64684 | val 1.50309
  Epoch 013 - train 0.58187 | val 1.07198
  Classification -> best τ=0.530 (val F1=0.3649)
  Directional -> Accuracy: 0.6250, MCC: 0.2750, F1: 0.5263

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.68283 | val 0.80123
  Epoch 011 - train 0.66091 | val 0.81322
  Classification -> best τ=0.450 (val F1=0.3143)
  Directional -> Accuracy: 0.5714, MCC: 0.1179, F1: 0.4828

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 16). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.55348 | val 1.33614
  Epoch 015 - train 0.54571 | val 1.67599
  Classification -> best τ=0.455 (val F1=0.0714)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.69567 | val 1.52387
  Epoch 012 - train 0.63623 | val 1.21594
  Classification -> best τ=0.550 (val F1=0.4301)
  Directional -> Accuracy: 0.6829, MCC: 0.3073, F1: 0.5517

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 16). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 16). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.63717 | val 0.86084
  Epoch 012 - train 0.61763 | val 1.02832
  Classification -> best τ=0.480 (val F1=0.1941)
  Directional -> Accuracy: 0.4366, MCC: -0.1093, F1: 0.4444

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.65191 | val 1.22043
  Epoch 014 - train 0.59474 | val 1.93590
  Classification -> best τ=0.580 (val F1=0.2622)
  Directional -> Accuracy: 0.4314, MCC: -0.1306, F1: 0.4528

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.69535 | val 0.73695
  Epoch 015 - train 0.62279 | val 0.80584
  Classification -> best τ=0.715 (val F1=0.2987)
  Directional -> Accuracy: 0.5424, MCC: 0.1774, F1: 0.2286

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.62651 | val 1.19670
  Epoch 013 - train 0.58199 | val 1.87582
  Classification -> best τ=0.325 (val F1=0.2504)
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.71102 | val 0.70327
  Epoch 018 - train 0.62838 | val 0.70570
  Classification -> best τ=0.235 (val F1=0.3536)
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.60773 | val 2.79359
  Epoch 011 - train 0.63019 | val 2.59539
  Classification -> best τ=0.575 (val F1=0.2689)
  Directional -> Accuracy: 0.4151, MCC: -0.1896, F1: 0.5634

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.60646 | val 0.85157
  Epoch 015 - train 0.58089 | val 1.02649
  Classification -> best τ=0.310 (val F1=0.3641)
  Directional -> Accuracy: 0.6571, MCC: 0.3914, F1: 0.7600

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.62307 | val 1.09799
  Epoch 011 - train 0.65874 | val 1.07186
  Classification -> best τ=0.560 (val F1=0.1796)
  Directional -> Accuracy: 0.3833, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.64778 | val 2.33175
  Epoch 013 - train 0.62212 | val 1.55911
  Classification -> best τ=0.440 (val F1=0.1499)
  Directional -> Accuracy: 0.5658, MCC: 0.1290, F1: 0.6118

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.67596 | val 0.80701
  Epoch 012 - train 0.61492 | val 1.00632
  Classification -> best τ=0.425 (val F1=0.3490)
  Directional -> Accuracy: 0.5606, MCC: 0.2134, F1: 0.5085

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 16). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.63880 | val 0.68836
  Epoch 015 - train 0.60077 | val 0.71896
  Classification -> best τ=0.415 (val F1=0.2594)
  Directional -> Accuracy: 0.5132, MCC: 0.1449, F1: 0.2449

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.62406 | val 1.29305
  Epoch 011 - train 0.61950 | val 0.85874
  Classification -> best τ=0.425 (val F1=0.1945)
  Directional -> Accuracy: 0.5000, MCC: 0.0667, F1: 0.5000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.64518 | val 1.27296
  Epoch 011 - train 0.60611 | val 1.35512
  Classification -> best τ=0.640 (val F1=0.2435)
  Directional -> Accuracy: 0.4848, MCC: -0.1240, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.67181 | val 0.73101
  Epoch 011 - train 0.64394 | val 0.74825
  Classification -> best τ=0.660 (val F1=0.3198)
  Directional -> Accuracy: 0.4138, MCC: -0.1111, F1: 0.0556

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.61588 | val 3.36140
  Epoch 011 - train 0.62502 | val 2.67679
  Classification -> best τ=0.405 (val F1=0.1878)
  Directional -> Accuracy: 0.5909, MCC: 0.1760, F1: 0.4255

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.65714 | val 0.67880
  Epoch 012 - train 0.66341 | val 0.74863
  Classification -> best τ=0.570 (val F1=0.3474)
  Directional -> Accuracy: 0.5000, MCC: 0.0996, F1: 0.3000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.61187 | val 0.85179
  Epoch 011 - train 0.63230 | val 0.80847
  Classification -> best τ=0.475 (val F1=0.2067)
  Directional -> Accuracy: 0.5319, MCC: 0.0810, F1: 0.5217

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.72236 | val 0.69418
  Epoch 015 - train 0.60276 | val 1.03357
  Classification -> best τ=0.585 (val F1=0.2324)
  Directional -> Accuracy: 0.5116, MCC: 0.0352, F1: 0.5333

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.63269 | val 0.89211
  Epoch 015 - train 0.61216 | val 0.77976
  Classification -> best τ=0.420 (val F1=0.3959)
  Directional -> Accuracy: 0.5517, MCC: 0.2279, F1: 0.3810

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.72241 | val 0.70275
  Epoch 019 - train 0.68665 | val 0.80411
  Classification -> best τ=0.540 (val F1=0.3548)
  Directional -> Accuracy: 0.4762, MCC: 0.0083, F1: 0.3125

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.65533 | val 0.73663
  Epoch 019 - train 0.58852 | val 1.08920
  Classification -> best τ=0.735 (val F1=0.1869)
  Directional -> Accuracy: 0.5682, MCC: 0.1365, F1: 0.5581

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.72985 | val 0.89165
  Epoch 011 - train 0.69282 | val 0.89735
  Classification -> best τ=0.595 (val F1=0.1229)
  Directional -> Accuracy: 0.3864, MCC: -0.2130, F1: 0.3415

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.60053 | val 0.78284
  Epoch 012 - train 0.57574 | val 1.00723
  Classification -> best τ=0.580 (val F1=0.2320)
  Directional -> Accuracy: 0.4902, MCC: -0.1289, F1: 0.6486

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.62405 | val 1.37626
  Epoch 013 - train 0.60241 | val 1.74042
  Classification -> best τ=0.475 (val F1=0.3541)
  Directional -> Accuracy: 0.5270, MCC: 0.2114, F1: 0.3396

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.65328 | val 0.75425
  Epoch 012 - train 0.64269 | val 0.86522
  Classification -> best τ=0.415 (val F1=0.3130)
  Directional -> Accuracy: 0.5789, MCC: 0.1588, F1: 0.6000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.67984 | val 1.52409
  Epoch 011 - train 0.63488 | val 1.61347
  Classification -> best τ=0.680 (val F1=0.2306)
  Directional -> Accuracy: 0.6000, MCC: 0.1935, F1: 0.4375

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.62913 | val 0.73083
  Epoch 019 - train 0.57396 | val 0.88054
  Classification -> best τ=0.315 (val F1=0.3444)
  Directional -> Accuracy: 0.4627, MCC: 0.1532, F1: 0.1000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.65420 | val 0.70524
  Epoch 015 - train 0.59140 | val 0.92250
  Classification -> best τ=0.595 (val F1=0.2683)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.62904 | val 0.80475
  Epoch 012 - train 0.62405 | val 0.85150
  Classification -> best τ=0.500 (val F1=0.2139)
  Directional -> Accuracy: 0.6316, MCC: 0.2675, F1: 0.5116

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.62352 | val 1.39092
  Epoch 012 - train 0.63298 | val 1.33657
  Classification -> best τ=0.455 (val F1=0.3014)
  Directional -> Accuracy: 0.5532, MCC: -0.1299, F1: 0.7042

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 16). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.59456 | val 1.90311
  Epoch 011 - train 0.59656 | val 1.85859
  Classification -> best τ=0.445 (val F1=0.1556)
  Directional -> Accuracy: 0.4000, MCC: -0.2097, F1: 0.2941

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.65171 | val 0.85816
  Epoch 011 - train 0.65100 | val 0.86279
  Classification -> best τ=0.380 (val F1=0.1870)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.7000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 16). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.66744 | val 0.99046
  Epoch 011 - train 0.65222 | val 1.20656
  Classification -> best τ=0.510 (val F1=0.2706)
  Directional -> Accuracy: 0.5263, MCC: 0.0679, F1: 0.6400

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.73117 | val 0.72483
  Epoch 012 - train 0.68389 | val 0.82860
  Classification -> best τ=0.505 (val F1=0.0936)
  Directional -> Accuracy: 0.5319, MCC: 0.0634, F1: 0.5417

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.56844 | val 1.21906
  Epoch 011 - train 0.56259 | val 1.20813
  Classification -> best τ=0.485 (val F1=0.2000)
  Directional -> Accuracy: 0.5778, MCC: 0.1265, F1: 0.6545

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.69459 | val 0.65963
  Epoch 020 - train 0.53535 | val 0.71289
  Classification -> best τ=0.475 (val F1=0.4497)
  Directional -> Accuracy: 0.4000, MCC: 0.1683, F1: 0.5385

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.62730 | val 1.61280
  Epoch 011 - train 0.64395 | val 1.92770
  Classification -> best τ=0.630 (val F1=0.1869)
  Directional -> Accuracy: 0.4561, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.62514 | val 1.64970
  Epoch 011 - train 0.64376 | val 1.72535
  Classification -> best τ=0.560 (val F1=0.2858)
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.62318 | val 1.21079
  Epoch 011 - train 0.66437 | val 1.26624
  Classification -> best τ=0.330 (val F1=0.2661)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.64505 | val 1.54699
  Epoch 011 - train 0.63274 | val 1.71971
  Classification -> best τ=0.565 (val F1=0.1094)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.67426 | val 1.83489

[I 2026-02-24 22:53:00,060] Trial 30 finished with value: 0.2586336322776642 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 15, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 0.004153506407672798, 'weight_decay': 0.0001391878631648489, 'lr_patience': 7, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 1.40300510933988, 'early_stopping_min_delta': 0.004064492644023292}. Best is trial 24 with value: 0.2654562368520373.

  Epoch 013 - train 0.61497 | val 1.14816
  Classification -> best τ=0.370 (val F1=0.2046)
  Directional -> Accuracy: 0.5161, MCC: 0.0085, F1: 0.1176

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2586336322776642
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 15
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.64693 | val 0.82906
  Epoch 012 - train 0.62190 | val 0.81040
  Classification -> best τ=0.600 (val F1=0.2851)
  Directional -> Accuracy: 0.5065, MCC: -0.0886, F1: 0.1364

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.62712 | val 0.88082
  Epoch 011 - train 0.57838 | val 0.97818
  Classification -> best τ=0.465 (val F1=0.1962)
  Directional -> Accuracy: 0.5870, MCC: 0.1313, F1: 0.6780

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 16). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.64930 | val 0.72573
  Epoch 012 - train 0.60461 | val 0.68692
  Classification -> best τ=0.445 (val F1=0.3941)
  Directional -> Accuracy: 0.5208, MCC: -0.0648, F1: 0.6761

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.66943 | val 1.24888
  Epoch 019 - train 0.61748 | val 1.09180
  Classification -> best τ=0.290 (val F1=0.2396)
  Directional -> Accuracy: 0.4933, MCC: -0.0121, F1: 0.5128

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.60883 | val 0.98369
  Epoch 014 - train 0.54483 | val 1.28598
  Classification -> best τ=0.465 (val F1=0.3847)
  Directional -> Accuracy: 0.4615, MCC: -0.1809, F1: 0.6111

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.61741 | val 0.95217
  Epoch 012 - train 0.57881 | val 0.71358
  Classification -> best τ=0.520 (val F1=0.2290)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6471

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.68122 | val 0.72369
  Epoch 011 - train 0.66964 | val 0.74701
  Classification -> best τ=0.495 (val F1=0.2013)
  Directional -> Accuracy: 0.4714, MCC: 0.1750, F1: 0.5934

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 16). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.64418 | val 0.70311
  Epoch 019 - train 0.46445 | val 0.90695
  Classification -> best τ=0.515 (val F1=0.2039)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.62783 | val 1.08049
  Epoch 013 - train 0.58203 | val 0.91265
  Classification -> best τ=0.540 (val F1=0.5227)
  Directional -> Accuracy: 0.4390, MCC: -0.1618, F1: 0.3030

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 16). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 16). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.63850 | val 0.83280
  Epoch 011 - train 0.64826 | val 1.16375
  Classification -> best τ=0.450 (val F1=0.2254)
  Directional -> Accuracy: 0.4507, MCC: 0.0437, F1: 0.6061

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.64964 | val 0.76850
  Epoch 013 - train 0.63577 | val 1.35835
  Classification -> best τ=0.290 (val F1=0.1557)
  Directional -> Accuracy: 0.6078, MCC: 0.2083, F1: 0.5455

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.61480 | val 0.78669
  Epoch 011 - train 0.65249 | val 0.85245
  Classification -> best τ=0.445 (val F1=0.3148)
  Directional -> Accuracy: 0.5254, MCC: 0.1336, F1: 0.6818

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.61105 | val 1.54060
  Epoch 011 - train 0.63026 | val 1.72683
  Classification -> best τ=0.395 (val F1=0.1818)
  Directional -> Accuracy: 0.4186, MCC: -0.1734, F1: 0.5902

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.63591 | val 0.69804
  Epoch 017 - train 0.58586 | val 0.83977
  Classification -> best τ=0.280 (val F1=0.3134)
  Directional -> Accuracy: 0.5574, MCC: 0.1455, F1: 0.6747

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.60848 | val 1.16506
  Epoch 011 - train 0.63491 | val 1.27112
  Classification -> best τ=0.550 (val F1=0.1150)
  Directional -> Accuracy: 0.5283, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.62360 | val 0.90023
  Epoch 011 - train 0.60463 | val 0.87859
  Classification -> best τ=0.570 (val F1=0.2013)
  Directional -> Accuracy: 0.6000, MCC: 0.2089, F1: 0.6000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.64742 | val 1.13977
  Epoch 011 - train 0.64640 | val 1.11604
  Classification -> best τ=0.455 (val F1=0.1680)
  Directional -> Accuracy: 0.6167, MCC: 0.0446, F1: 0.7579

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.68143 | val 1.66198
  Epoch 011 - train 0.64287 | val 1.86534
  Classification -> best τ=0.505 (val F1=0.1923)
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.67253 | val 1.18178
  Epoch 013 - train 0.63309 | val 1.48004
  Classification -> best τ=0.495 (val F1=0.2983)
  Directional -> Accuracy: 0.3939, MCC: -0.1491, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 16). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.64193 | val 0.69443
  Epoch 013 - train 0.61619 | val 0.68682
  Classification -> best τ=0.475 (val F1=0.2570)
  Directional -> Accuracy: 0.5263, MCC: 0.0061, F1: 0.6471

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.63614 | val 0.70153
  Epoch 014 - train 0.61406 | val 1.03726
  Classification -> best τ=0.440 (val F1=0.3544)
  Directional -> Accuracy: 0.4583, MCC: 0.0497, F1: 0.3810

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.62835 | val 1.32728
  Epoch 011 - train 0.62840 | val 1.51788
  Classification -> best τ=0.480 (val F1=0.2070)
  Directional -> Accuracy: 0.5455, MCC: 0.0976, F1: 0.6154

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.66222 | val 0.87878
  Epoch 015 - train 0.63441 | val 0.87117
  Classification -> best τ=0.685 (val F1=0.3644)
  Directional -> Accuracy: 0.4655, MCC: 0.0453, F1: 0.2439

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.66186 | val 2.01386
  Epoch 013 - train 0.62173 | val 2.19144
  Classification -> best τ=0.535 (val F1=0.1878)
  Directional -> Accuracy: 0.5455, MCC: 0.0679, F1: 0.2857

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.68018 | val 0.65301
  Epoch 020 - train 0.59124 | val 0.80813
  Classification -> best τ=0.515 (val F1=0.5459)
  Directional -> Accuracy: 0.5357, MCC: 0.1728, F1: 0.3810

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.57635 | val 0.81293
  Epoch 011 - train 0.60313 | val 0.78903
  Classification -> best τ=0.560 (val F1=0.1792)
  Directional -> Accuracy: 0.5745, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.67359 | val 0.77596
  Epoch 013 - train 0.62379 | val 0.80084
  Classification -> best τ=0.545 (val F1=0.0713)
  Directional -> Accuracy: 0.5349, MCC: 0.0746, F1: 0.5652

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.60035 | val 0.98444
  Epoch 013 - train 0.63302 | val 0.89754
  Classification -> best τ=0.395 (val F1=0.3551)
  Directional -> Accuracy: 0.5690, MCC: 0.2351, F1: 0.4444

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.67689 | val 0.69957
  Epoch 014 - train 0.63551 | val 0.79679
  Classification -> best τ=0.520 (val F1=0.5399)
  Directional -> Accuracy: 0.5238, MCC: 0.0302, F1: 0.5833

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.61063 | val 0.86230
  Epoch 012 - train 0.65968 | val 0.99537
  Classification -> best τ=0.525 (val F1=0.1869)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.5417

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.67782 | val 0.67924
  Epoch 017 - train 0.59212 | val 0.97107
  Classification -> best τ=0.555 (val F1=0.2374)
  Directional -> Accuracy: 0.5227, MCC: -0.0392, F1: 0.6667

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.61952 | val 0.79331
  Epoch 015 - train 0.59271 | val 0.87614
  Classification -> best τ=0.420 (val F1=0.3686)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.57303 | val 1.70136
  Epoch 011 - train 0.59781 | val 1.61680
  Classification -> best τ=0.575 (val F1=0.2739)
  Directional -> Accuracy: 0.4324, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.63284 | val 1.16989
  Epoch 014 - train 0.67406 | val 0.93321
  Classification -> best τ=0.395 (val F1=0.2041)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6545

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.67291 | val 1.45060
  Epoch 011 - train 0.63078 | val 1.32386
  Classification -> best τ=0.585 (val F1=0.2500)
  Directional -> Accuracy: 0.5556, MCC: 0.1612, F1: 0.0909

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.58045 | val 0.82908
  Epoch 015 - train 0.58829 | val 0.84072
  Classification -> best τ=0.320 (val F1=0.3166)
  Directional -> Accuracy: 0.4776, MCC: 0.0791, F1: 0.2553

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.60996 | val 0.77669
  Epoch 011 - train 0.67362 | val 0.81153
  Classification -> best τ=0.550 (val F1=0.1410)
  Directional -> Accuracy: 0.4651, MCC: -0.1579, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.61976 | val 0.81388
  Epoch 011 - train 0.60528 | val 0.78161
  Classification -> best τ=0.360 (val F1=0.1851)
  Directional -> Accuracy: 0.5088, MCC: 0.0453, F1: 0.5882

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.59943 | val 0.87653
  Epoch 014 - train 0.57839 | val 0.78741
  Classification -> best τ=0.315 (val F1=0.3296)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 16). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.58887 | val 1.01359
  Epoch 016 - train 0.53531 | val 1.51441
  Classification -> best τ=0.280 (val F1=0.4689)
  Directional -> Accuracy: 0.3750, MCC: 0.1175, F1: 0.5283

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.71162 | val 0.73418
  Epoch 014 - train 0.63800 | val 1.07866
  Classification -> best τ=0.385 (val F1=0.2707)
  Directional -> Accuracy: 0.5641, MCC: 0.1065, F1: 0.6909

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 16). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.70214 | val 0.74880
  Epoch 011 - train 0.63599 | val 0.76611
  Classification -> best τ=0.445 (val F1=0.4481)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.61721 | val 0.74612
  Epoch 011 - train 0.70097 | val 0.87576
  Classification -> best τ=0.525 (val F1=0.2544)
  Directional -> Accuracy: 0.5319, MCC: 0.0745, F1: 0.4500

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.58717 | val 1.73505
  Epoch 011 - train 0.59992 | val 1.67111
  Classification -> best τ=0.475 (val F1=0.1387)
  Directional -> Accuracy: 0.6222, MCC: 0.2236, F1: 0.7213

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.64786 | val 0.68955
  Epoch 020 - train 0.52923 | val 0.95358
  Classification -> best τ=0.545 (val F1=0.3647)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.66080 | val 1.39727
  Epoch 015 - train 0.59742 | val 1.43125
  Classification -> best τ=0.585 (val F1=0.1059)
  Directional -> Accuracy: 0.4561, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.63228 | val 1.11032
  Epoch 011 - train 0.63190 | val 1.30307
  Classification -> best τ=0.700 (val F1=0.4000)
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.61575 | val 2.32895
  Epoch 012 - train 0.69373 | val 1.60636
  Classification -> best τ=0.405 (val F1=0.2415)
  Directional -> Accuracy: 0.5556, MCC: 0.1520, F1: 0.6923

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.63236 | val 1.56688
  Epoch 011 - train 0.63573 | val 1.41660
  Classification -> best τ=0.475 (val F1=0.0423)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.65393 | val 0.68793

[I 2026-02-24 22:54:20,010] Trial 31 finished with value: 0.2675669744291094 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 15, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 0.004076804881378551, 'weight_decay': 0.00012956367260086177, 'lr_patience': 7, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 1.423101256139673, 'early_stopping_min_delta': 0.004086135941291317}. Best is trial 31 with value: 0.2675669744291094.

  Epoch 013 - train 0.63694 | val 0.97441
  Classification -> best τ=0.605 (val F1=0.2653)
  Directional -> Accuracy: 0.5161, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2675669744291094
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 15
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.64068 | val 0.82037
  Epoch 015 - train 0.62254 | val 0.95522
  Classification -> best τ=0.505 (val F1=0.2314)
  Directional -> Accuracy: 0.4156, MCC: -0.1437, F1: 0.5055

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.60096 | val 0.81854
  Epoch 011 - train 0.60136 | val 0.91632
  Classification -> best τ=0.410 (val F1=0.2287)
  Directional -> Accuracy: 0.5870, MCC: 0.1700, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 16). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.65385 | val 0.74916
  Epoch 012 - train 0.67609 | val 0.75210
  Classification -> best τ=0.550 (val F1=0.2600)
  Directional -> Accuracy: 0.5000, MCC: 0.0216, F1: 0.4545

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.66043 | val 1.27462
  Epoch 011 - train 0.63570 | val 1.18656
  Classification -> best τ=0.545 (val F1=0.1734)
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.59853 | val 0.84336
  Epoch 014 - train 0.54039 | val 1.11932
  Classification -> best τ=0.410 (val F1=0.3446)
  Directional -> Accuracy: 0.5385, MCC: 0.0154, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.59363 | val 1.64917
  Epoch 012 - train 0.55612 | val 1.31545
  Classification -> best τ=0.600 (val F1=0.3393)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.68062 | val 0.79320
  Epoch 014 - train 0.66107 | val 0.88528
  Classification -> best τ=0.645 (val F1=0.2774)
  Directional -> Accuracy: 0.5429, MCC: -0.0278, F1: 0.2727

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 16). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.59482 | val 2.34976
  Epoch 011 - train 0.59237 | val 2.69068
  Classification -> best τ=0.605 (val F1=0.4183)
  Directional -> Accuracy: 0.5778, MCC: 0.1170, F1: 0.4571

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.65695 | val 0.69559
  Epoch 017 - train 0.54988 | val 1.79061
  Classification -> best τ=0.575 (val F1=0.5227)
  Directional -> Accuracy: 0.3659, MCC: 0.0000, F1: 0.5357

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 16). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 16). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.63210 | val 1.03174
  Epoch 014 - train 0.64197 | val 0.80094
  Classification -> best τ=0.420 (val F1=0.1507)
  Directional -> Accuracy: 0.4789, MCC: 0.0496, F1: 0.5843

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.62949 | val 1.72714
  Epoch 011 - train 0.60621 | val 1.91999
  Classification -> best τ=0.535 (val F1=0.2278)
  Directional -> Accuracy: 0.5686, MCC: 0.1257, F1: 0.4762

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.64032 | val 0.73021
  Epoch 013 - train 0.62024 | val 0.75935
  Classification -> best τ=0.630 (val F1=0.2701)
  Directional -> Accuracy: 0.5593, MCC: 0.2186, F1: 0.2778

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.63807 | val 1.08238
  Epoch 012 - train 0.59126 | val 0.89795
  Classification -> best τ=0.405 (val F1=0.1818)
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.65818 | val 0.81228
  Epoch 015 - train 0.64696 | val 0.70916
  Classification -> best τ=0.325 (val F1=0.3933)
  Directional -> Accuracy: 0.5574, MCC: 0.1602, F1: 0.6824

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.56978 | val 2.75009
  Epoch 011 - train 0.61099 | val 2.70278
  Classification -> best τ=0.530 (val F1=0.2206)
  Directional -> Accuracy: 0.5283, MCC: 0.0273, F1: 0.2857

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.63250 | val 1.19423
  Epoch 013 - train 0.60381 | val 0.78914
  Classification -> best τ=0.470 (val F1=0.3996)
  Directional -> Accuracy: 0.5429, MCC: 0.0661, F1: 0.6098

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.67616 | val 0.98193
  Epoch 011 - train 0.64961 | val 1.05511
  Classification -> best τ=0.505 (val F1=0.2719)
  Directional -> Accuracy: 0.5000, MCC: -0.1650, F1: 0.6429

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.64614 | val 1.77128
  Epoch 011 - train 0.64595 | val 1.72273
  Classification -> best τ=0.510 (val F1=0.0666)
  Directional -> Accuracy: 0.5526, MCC: -0.1016, F1: 0.7018

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.67017 | val 1.42856
  Epoch 011 - train 0.62656 | val 1.19379
  Classification -> best τ=0.295 (val F1=0.2117)
  Directional -> Accuracy: 0.5606, MCC: 0.0654, F1: 0.6506

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 16). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.65862 | val 0.73482
  Epoch 020 - train 0.60638 | val 0.65164
  Classification -> best τ=0.420 (val F1=0.3722)
  Directional -> Accuracy: 0.5658, MCC: 0.1463, F1: 0.5479

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.59729 | val 0.82261
  Epoch 016 - train 0.58713 | val 0.95887
  Classification -> best τ=0.515 (val F1=0.2907)
  Directional -> Accuracy: 0.4375, MCC: 0.2000, F1: 0.1818

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.69698 | val 1.17329
  Epoch 011 - train 0.64605 | val 1.29425
  Classification -> best τ=0.735 (val F1=0.2264)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.63917 | val 0.84416
  Epoch 012 - train 0.64532 | val 0.81693
  Classification -> best τ=0.610 (val F1=0.2598)
  Directional -> Accuracy: 0.5690, MCC: 0.1441, F1: 0.5902

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.63478 | val 2.69646
  Epoch 011 - train 0.62879 | val 2.35870
  Classification -> best τ=0.260 (val F1=0.3037)
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.61749 | val 0.75505
  Epoch 013 - train 0.59637 | val 0.84817
  Classification -> best τ=0.505 (val F1=0.5105)
  Directional -> Accuracy: 0.5536, MCC: 0.1867, F1: 0.4444

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.59135 | val 0.77461
  Epoch 011 - train 0.63980 | val 0.78225
  Classification -> best τ=0.520 (val F1=0.2067)
  Directional -> Accuracy: 0.4468, MCC: -0.1044, F1: 0.4091

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.66565 | val 1.08864
  Epoch 014 - train 0.62987 | val 1.35452
  Classification -> best τ=0.570 (val F1=0.2878)
  Directional -> Accuracy: 0.5814, MCC: 0.1146, F1: 0.6667

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.62991 | val 0.79422
  Epoch 011 - train 0.66066 | val 0.79542
  Classification -> best τ=0.545 (val F1=0.3127)
  Directional -> Accuracy: 0.5000, MCC: 0.1533, F1: 0.2162

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.72939 | val 0.68155
  Epoch 018 - train 0.57599 | val 0.73674
  Classification -> best τ=0.530 (val F1=0.5991)
  Directional -> Accuracy: 0.5000, MCC: 0.0235, F1: 0.4615

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.60703 | val 0.86731
  Epoch 012 - train 0.63686 | val 1.10945
  Classification -> best τ=0.650 (val F1=0.1869)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.4500

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.64211 | val 0.71899
  Epoch 018 - train 0.61247 | val 0.79513
  Classification -> best τ=0.425 (val F1=0.2374)
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.58176 | val 0.81688
  Epoch 011 - train 0.60760 | val 0.75625
  Classification -> best τ=0.495 (val F1=0.3589)
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.62198 | val 1.29977
  Epoch 013 - train 0.59586 | val 2.17903
  Classification -> best τ=0.480 (val F1=0.3470)
  Directional -> Accuracy: 0.5541, MCC: 0.1864, F1: 0.4762

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.55423 | val 0.85815
  Epoch 012 - train 0.72481 | val 1.03055
  Classification -> best τ=0.365 (val F1=0.2227)
  Directional -> Accuracy: 0.5263, MCC: 0.0555, F1: 0.5909

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.60622 | val 1.06741
  Epoch 013 - train 0.58154 | val 1.57147
  Classification -> best τ=0.555 (val F1=0.4015)
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.6364

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.60250 | val 0.74230
  Epoch 015 - train 0.60226 | val 0.77375
  Classification -> best τ=0.265 (val F1=0.3431)
  Directional -> Accuracy: 0.4925, MCC: 0.1685, F1: 0.2273

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.66716 | val 0.67182
  Epoch 020 - train 0.60837 | val 0.74546
  Classification -> best τ=0.540 (val F1=0.3629)
  Directional -> Accuracy: 0.5814, MCC: 0.2074, F1: 0.4375

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.60546 | val 0.80398
  Epoch 014 - train 0.63655 | val 0.80887
  Classification -> best τ=0.460 (val F1=0.1998)
  Directional -> Accuracy: 0.4561, MCC: -0.0745, F1: 0.5231

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.64542 | val 0.61118
  Epoch 020 - train 0.49700 | val 1.10556
  Classification -> best τ=0.355 (val F1=0.4455)
  Directional -> Accuracy: 0.5745, MCC: 0.0806, F1: 0.6667

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 16). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.57184 | val 1.78966
  Epoch 013 - train 0.62454 | val 1.55314
  Classification -> best τ=0.485 (val F1=0.2000)
  Directional -> Accuracy: 0.3500, MCC: -0.0721, F1: 0.5000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.68606 | val 0.70465
  Epoch 020 - train 0.64374 | val 1.12820
  Classification -> best τ=0.230 (val F1=0.3397)
  Directional -> Accuracy: 0.5128, MCC: -0.0188, F1: 0.6275

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 16). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.62686 | val 0.89896
  Epoch 016 - train 0.59697 | val 1.30834
  Classification -> best τ=0.345 (val F1=0.2439)
  Directional -> Accuracy: 0.5132, MCC: 0.1155, F1: 0.6726

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.62551 | val 0.84102
  Epoch 011 - train 0.66753 | val 0.85558
  Classification -> best τ=0.565 (val F1=0.1733)
  Directional -> Accuracy: 0.5745, MCC: 0.1559, F1: 0.6552

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.58539 | val 1.13813
  Epoch 011 - train 0.56974 | val 1.14253
  Classification -> best τ=0.520 (val F1=0.2000)
  Directional -> Accuracy: 0.6222, MCC: 0.2236, F1: 0.7213

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.62970 | val 0.72252
  Epoch 016 - train 0.58449 | val 0.89546
  Classification -> best τ=0.375 (val F1=0.3647)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.67020 | val 1.62457
  Epoch 012 - train 0.66792 | val 1.25831
  Classification -> best τ=0.410 (val F1=0.2975)
  Directional -> Accuracy: 0.7018, MCC: 0.3958, F1: 0.7463

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.58915 | val 1.85807
  Epoch 011 - train 0.63227 | val 1.95229
  Classification -> best τ=0.720 (val F1=0.3170)
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.68548 | val 1.50118
  Epoch 011 - train 0.65647 | val 1.55084
  Classification -> best τ=0.365 (val F1=0.2869)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.66187 | val 1.17946
  Epoch 011 - train 0.65438 | val 1.32941
  Classification -> best τ=0.665 (val F1=0.1707)
  Directional -> Accuracy: 0.5263, MCC: 0.1360, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.65403 | val 0.73731

[I 2026-02-24 22:55:42,272] Trial 32 finished with value: 0.2908549754956826 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 15, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 0.0040007252103064364, 'weight_decay': 0.00016153203859083166, 'lr_patience': 7, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 1.3525689698142827, 'early_stopping_min_delta': 0.004090223734051185}. Best is trial 32 with value: 0.2908549754956826.

  Epoch 013 - train 0.61825 | val 0.68707
  Classification -> best τ=0.325 (val F1=0.2838)
  Directional -> Accuracy: 0.4516, MCC: -0.0928, F1: 0.5526

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2908549754956826
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 15
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.68076 | val 0.70724
  Epoch 019 - train 0.62448 | val 0.76204
  Classification -> best τ=0.510 (val F1=0.2135)
  Directional -> Accuracy: 0.3896, MCC: -0.2887, F1: 0.5607

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.59271 | val 0.94539
  Epoch 011 - train 0.63150 | val 1.10483
  Classification -> best τ=0.440 (val F1=0.1236)
  Directional -> Accuracy: 0.5870, MCC: 0.1700, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 16). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.64575 | val 0.90981
  Epoch 012 - train 0.64515 | val 0.93430
  Classification -> best τ=0.545 (val F1=0.3244)
  Directional -> Accuracy: 0.4792, MCC: 0.0648, F1: 0.1379

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.66886 | val 1.07190
  Epoch 011 - train 0.64581 | val 1.46648
  Classification -> best τ=0.475 (val F1=0.0867)
  Directional -> Accuracy: 0.5200, MCC: 0.0573, F1: 0.5000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.59106 | val 1.49660
  Epoch 013 - train 0.55235 | val 1.53897
  Classification -> best τ=0.395 (val F1=0.3867)
  Directional -> Accuracy: 0.7500, MCC: 0.5061, F1: 0.7937

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.65675 | val 0.92173
  Epoch 012 - train 0.63107 | val 1.23870
  Classification -> best τ=0.530 (val F1=0.1733)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6129

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.69082 | val 0.70796
  Epoch 013 - train 0.66261 | val 0.76283
  Classification -> best τ=0.540 (val F1=0.2041)
  Directional -> Accuracy: 0.4571, MCC: -0.0126, F1: 0.5000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 16). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.69058 | val 1.94180
  Epoch 016 - train 0.54097 | val 1.75539
  Classification -> best τ=0.645 (val F1=0.3669)
  Directional -> Accuracy: 0.5111, MCC: 0.2029, F1: 0.6207

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.58454 | val 1.22873
  Epoch 011 - train 0.63458 | val 1.41874
  Classification -> best τ=0.505 (val F1=0.3977)
  Directional -> Accuracy: 0.4634, MCC: -0.1564, F1: 0.2667

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 16). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 16). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.64572 | val 1.04922
  Epoch 016 - train 0.60584 | val 0.72469
  Classification -> best τ=0.460 (val F1=0.2579)
  Directional -> Accuracy: 0.5493, MCC: 0.1206, F1: 0.5556

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.65251 | val 1.75245
  Epoch 011 - train 0.63243 | val 1.88390
  Classification -> best τ=0.560 (val F1=0.2819)
  Directional -> Accuracy: 0.6078, MCC: 0.2654, F1: 0.3333

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.63494 | val 0.74802
  Epoch 011 - train 0.62166 | val 0.72990
  Classification -> best τ=0.445 (val F1=0.1479)
  Directional -> Accuracy: 0.5085, MCC: 0.0000, F1: 0.6742

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.64623 | val 1.41642
  Epoch 011 - train 0.64180 | val 1.29390
  Classification -> best τ=0.505 (val F1=0.1700)
  Directional -> Accuracy: 0.5116, MCC: -0.0068, F1: 0.4000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.62836 | val 0.79811
  Epoch 014 - train 0.60000 | val 0.77060
  Classification -> best τ=0.385 (val F1=0.3225)
  Directional -> Accuracy: 0.5410, MCC: 0.0825, F1: 0.6216

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.62691 | val 2.12180
  Epoch 011 - train 0.60667 | val 2.52566
  Classification -> best τ=0.500 (val F1=0.2262)
  Directional -> Accuracy: 0.4340, MCC: -0.2096, F1: 0.6053

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.61917 | val 0.94916
  Epoch 014 - train 0.57789 | val 0.98734
  Classification -> best τ=0.515 (val F1=0.2205)
  Directional -> Accuracy: 0.5571, MCC: 0.1056, F1: 0.5974

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.66962 | val 1.25395
  Epoch 011 - train 0.66691 | val 1.18607
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6167, MCC: 0.0000, F1: 0.7629

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.64807 | val 1.41324
  Epoch 011 - train 0.60154 | val 1.33940
  Classification -> best τ=0.395 (val F1=0.2232)
  Directional -> Accuracy: 0.6184, MCC: 0.1554, F1: 0.7184

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.63573 | val 1.11101
  Epoch 012 - train 0.66093 | val 0.93228
  Classification -> best τ=0.340 (val F1=0.2117)
  Directional -> Accuracy: 0.5152, MCC: 0.1796, F1: 0.3846

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 16). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.63244 | val 0.70203
  Epoch 020 - train 0.59573 | val 0.68481
  Classification -> best τ=0.350 (val F1=0.3422)
  Directional -> Accuracy: 0.5526, MCC: 0.1577, F1: 0.4516

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.62094 | val 0.89398
  Epoch 015 - train 0.58633 | val 0.77484
  Classification -> best τ=0.480 (val F1=0.3295)
  Directional -> Accuracy: 0.4583, MCC: 0.2335, F1: 0.2353

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.64158 | val 1.22712
  Epoch 012 - train 0.63319 | val 1.19790
  Classification -> best τ=0.545 (val F1=0.3022)
  Directional -> Accuracy: 0.4545, MCC: -0.0937, F1: 0.3793

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.66391 | val 0.82581
  Epoch 011 - train 0.63272 | val 1.05731
  Classification -> best τ=0.565 (val F1=0.2272)
  Directional -> Accuracy: 0.5690, MCC: 0.1089, F1: 0.6377

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.62516 | val 4.30908
  Epoch 011 - train 0.61319 | val 3.85654
  Classification -> best τ=0.400 (val F1=0.1878)
  Directional -> Accuracy: 0.5758, MCC: 0.1484, F1: 0.5484

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.66360 | val 0.66656
  Epoch 018 - train 0.59897 | val 0.67789
  Classification -> best τ=0.530 (val F1=0.5537)
  Directional -> Accuracy: 0.5536, MCC: 0.2064, F1: 0.4186

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.55584 | val 0.90781
  Epoch 011 - train 0.61038 | val 0.96978
  Classification -> best τ=0.535 (val F1=0.2067)
  Directional -> Accuracy: 0.5106, MCC: 0.0055, F1: 0.4390

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.62538 | val 0.86781
  Epoch 017 - train 0.58279 | val 1.78057
  Classification -> best τ=0.670 (val F1=0.3078)
  Directional -> Accuracy: 0.5116, MCC: 0.1075, F1: 0.4324

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.62177 | val 0.78683
  Epoch 012 - train 0.64480 | val 0.78365
  Classification -> best τ=0.375 (val F1=0.1867)
  Directional -> Accuracy: 0.5517, MCC: 0.1330, F1: 0.5185

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.58486 | val 0.66622
  Epoch 019 - train 0.59570 | val 0.88934
  Classification -> best τ=0.530 (val F1=0.4423)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.7077

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.62141 | val 0.99283
  Epoch 011 - train 0.67641 | val 0.89771
  Classification -> best τ=0.605 (val F1=0.1869)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.3889

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.69625 | val 0.73336
  Epoch 012 - train 0.64349 | val 0.73422
  Classification -> best τ=0.695 (val F1=0.1239)
  Directional -> Accuracy: 0.4318, MCC: -0.1029, F1: 0.2424

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.57510 | val 0.78267
  Epoch 011 - train 0.59658 | val 0.79615
  Classification -> best τ=0.510 (val F1=0.2964)
  Directional -> Accuracy: 0.4510, MCC: -0.1295, F1: 0.5484

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.67961 | val 1.44094
  Epoch 012 - train 0.60011 | val 1.97554
  Classification -> best τ=0.490 (val F1=0.3259)
  Directional -> Accuracy: 0.5811, MCC: 0.1883, F1: 0.5753

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.65130 | val 1.03187
  Epoch 012 - train 0.63774 | val 0.87450
  Classification -> best τ=0.480 (val F1=0.5505)
  Directional -> Accuracy: 0.5263, MCC: 0.0526, F1: 0.5263

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.62805 | val 1.21907
  Epoch 011 - train 0.59043 | val 1.39626
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.6364

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.59550 | val 0.70243
  Epoch 016 - train 0.60857 | val 0.66920
  Classification -> best τ=0.145 (val F1=0.3767)
  Directional -> Accuracy: 0.6418, MCC: 0.3020, F1: 0.6471

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.74246 | val 0.73891
  Epoch 016 - train 0.65974 | val 0.77224
  Classification -> best τ=0.525 (val F1=0.2683)
  Directional -> Accuracy: 0.5814, MCC: 0.2280, F1: 0.4000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.64472 | val 0.82897
  Epoch 011 - train 0.62367 | val 0.76221
  Classification -> best τ=0.410 (val F1=0.1790)
  Directional -> Accuracy: 0.5789, MCC: 0.1747, F1: 0.6129

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.62142 | val 1.05505
  Epoch 011 - train 0.58550 | val 1.03101
  Classification -> best τ=0.480 (val F1=0.3568)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 16). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.57223 | val 1.98027
  Epoch 012 - train 0.60686 | val 1.96810
  Classification -> best τ=0.560 (val F1=0.3907)
  Directional -> Accuracy: 0.3500, MCC: -0.0721, F1: 0.5000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.60191 | val 0.75563
  Epoch 012 - train 0.55420 | val 0.82188
  Classification -> best τ=0.455 (val F1=0.0156)
  Directional -> Accuracy: 0.5385, MCC: 0.1091, F1: 0.4706

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 16). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.63182 | val 0.79478
  Epoch 011 - train 0.63955 | val 0.91257
  Classification -> best τ=0.455 (val F1=0.4220)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.67958 | val 0.91002
  Epoch 016 - train 0.66113 | val 0.91266
  Classification -> best τ=0.530 (val F1=0.1733)
  Directional -> Accuracy: 0.5532, MCC: 0.1390, F1: 0.4000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.62550 | val 1.08126
  Epoch 011 - train 0.56226 | val 1.19724
  Classification -> best τ=0.565 (val F1=0.2774)
  Directional -> Accuracy: 0.4000, MCC: -0.2411, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.63914 | val 0.72942
  Epoch 013 - train 0.68044 | val 0.77967
  Classification -> best τ=0.580 (val F1=0.4587)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.62337 | val 0.77089
  Epoch 012 - train 0.66561 | val 0.93468
  Classification -> best τ=0.660 (val F1=0.1512)
  Directional -> Accuracy: 0.4561, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.63032 | val 1.74867
  Epoch 011 - train 0.59307 | val 2.11171
  Classification -> best τ=0.590 (val F1=0.3819)
  Directional -> Accuracy: 0.5088, MCC: 0.0964, F1: 0.6410

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.62938 | val 1.26222
  Epoch 012 - train 0.61459 | val 1.70825
  Classification -> best τ=0.415 (val F1=0.1801)
  Directional -> Accuracy: 0.4815, MCC: -0.0524, F1: 0.5625

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.66061 | val 0.99271
  Epoch 013 - train 0.64678 | val 1.07702
  Classification -> best τ=0.775 (val F1=0.1990)
  Directional -> Accuracy: 0.4912, MCC: -0.0359, F1: 0.6133

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.66984 | val 0.68661

[I 2026-02-24 22:57:03,077] Trial 33 finished with value: 0.2604524781711651 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 15, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 0.003687655176111078, 'weight_decay': 0.00016676922626641968, 'lr_patience': 7, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 1.3775078356782702, 'early_stopping_min_delta': 0.004068777272024617}. Best is trial 32 with value: 0.2908549754956826.

  Epoch 015 - train 0.63449 | val 0.89216
  Classification -> best τ=0.465 (val F1=0.2836)
  Directional -> Accuracy: 0.4516, MCC: -0.1476, F1: 0.1905

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2604524781711651
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 10
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.62017 | val 0.81714
  Epoch 013 - train 0.63818 | val 1.05403
  Classification -> best τ=0.640 (val F1=0.1997)
  Directional -> Accuracy: 0.5513, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.63038 | val 0.76260
  Epoch 011 - train 0.62644 | val 0.79729
  Classification -> best τ=0.460 (val F1=0.2905)
  Directional -> Accuracy: 0.5745, MCC: 0.1065, F1: 0.6875

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 11). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.65945 | val 0.75587
  Epoch 011 - train 0.62562 | val 0.78658
  Classification -> best τ=0.470 (val F1=0.2829)
  Directional -> Accuracy: 0.4898, MCC: -0.0704, F1: 0.6154

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.67002 | val 0.76650
  Epoch 011 - train 0.65085 | val 0.99208
  Classification -> best τ=0.415 (val F1=0.1898)
  Directional -> Accuracy: 0.5526, MCC: 0.1122, F1: 0.5526

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.64739 | val 0.68466
  Epoch 015 - train 0.55858 | val 0.72258
  Classification -> best τ=0.445 (val F1=0.4064)
  Directional -> Accuracy: 0.6923, MCC: 0.4148, F1: 0.6667

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.62879 | val 1.85898
  Epoch 011 - train 0.57074 | val 2.13502
  Classification -> best τ=0.530 (val F1=0.2629)
  Directional -> Accuracy: 0.5306, MCC: 0.0581, F1: 0.5818

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.66210 | val 0.75052
  Epoch 011 - train 0.65502 | val 0.87890
  Classification -> best τ=0.500 (val F1=0.0962)
  Directional -> Accuracy: 0.4507, MCC: 0.0826, F1: 0.5806

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 11). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.64106 | val 1.63297
  Epoch 011 - train 0.60041 | val 1.84873
  Classification -> best τ=0.510 (val F1=0.2467)
  Directional -> Accuracy: 0.4130, MCC: 0.0000, F1: 0.5846

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.62533 | val 0.72249
  Epoch 015 - train 0.59177 | val 0.73675
  Classification -> best τ=0.565 (val F1=0.3838)
  Directional -> Accuracy: 0.6429, MCC: 0.1658, F1: 0.2857

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for proper time series validation for BRK-A. Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for proper time series validation for BSAC. Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.63041 | val 0.90478
  Epoch 011 - train 0.62360 | val 1.19208
  Classification -> best τ=0.475 (val F1=0.2181)
  Directional -> Accuracy: 0.4366, MCC: 0.0000, F1: 0.6078

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.62382 | val 1.26709
  Epoch 011 - train 0.62067 | val 1.24856
  Classification -> best τ=0.540 (val F1=0.1080)
  Directional -> Accuracy: 0.5192, MCC: 0.0786, F1: 0.5902

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.67323 | val 0.73906
  Epoch 011 - train 0.64012 | val 0.75427
  Classification -> best τ=0.520 (val F1=0.3205)
  Directional -> Accuracy: 0.5085, MCC: 0.0000, F1: 0.6742

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.63056 | val 1.24377
  Epoch 011 - train 0.63098 | val 1.31392
  Classification -> best τ=0.415 (val F1=0.2287)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.64932 | val 0.77303
  Epoch 014 - train 0.60104 | val 0.83637
  Classification -> best τ=0.275 (val F1=0.2643)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.65090 | val 2.64498
  Epoch 011 - train 0.59870 | val 2.86975
  Classification -> best τ=0.615 (val F1=0.2733)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.63325 | val 0.81465
  Epoch 012 - train 0.64671 | val 0.78598
  Classification -> best τ=0.395 (val F1=0.2455)
  Directional -> Accuracy: 0.5352, MCC: 0.0000, F1: 0.6972

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.64205 | val 1.92566
  Epoch 011 - train 0.67325 | val 1.93093
  Classification -> best τ=0.585 (val F1=0.2440)
  Directional -> Accuracy: 0.3934, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.60740 | val 1.11171
  Epoch 011 - train 0.61413 | val 1.47727
  Classification -> best τ=0.425 (val F1=0.1176)
  Directional -> Accuracy: 0.5584, MCC: 0.1054, F1: 0.6136

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.64177 | val 0.75026
  Epoch 011 - train 0.63720 | val 0.73222
  Classification -> best τ=0.540 (val F1=0.2970)
  Directional -> Accuracy: 0.4179, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 11). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.63667 | val 0.71749
  Epoch 012 - train 0.63329 | val 0.78842
  Classification -> best τ=0.445 (val F1=0.2509)
  Directional -> Accuracy: 0.5195, MCC: -0.0054, F1: 0.6263

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.62071 | val 0.75915
  Epoch 018 - train 0.56261 | val 0.89477
  Classification -> best τ=0.410 (val F1=0.3170)
  Directional -> Accuracy: 0.5306, MCC: -0.1056, F1: 0.6667

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.67053 | val 0.84927
  Epoch 011 - train 0.62863 | val 0.82180
  Classification -> best τ=0.550 (val F1=0.2264)
  Directional -> Accuracy: 0.4925, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.65301 | val 0.85327
  Epoch 013 - train 0.62221 | val 1.02042
  Classification -> best τ=0.690 (val F1=0.2992)
  Directional -> Accuracy: 0.4407, MCC: -0.0036, F1: 0.1951

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.60581 | val 0.88154
  Epoch 011 - train 0.64174 | val 0.82900
  Classification -> best τ=0.395 (val F1=0.1992)
  Directional -> Accuracy: 0.4776, MCC: 0.0000, F1: 0.6465

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.64801 | val 0.68984
  Epoch 016 - train 0.60777 | val 0.74453
  Classification -> best τ=0.530 (val F1=0.5431)
  Directional -> Accuracy: 0.5789, MCC: 0.2579, F1: 0.4783

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.63894 | val 0.76801
  Epoch 011 - train 0.66278 | val 0.81286
  Classification -> best τ=0.540 (val F1=0.0555)
  Directional -> Accuracy: 0.6042, MCC: 0.1353, F1: 0.3448

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.61305 | val 1.07282
  Epoch 011 - train 0.67355 | val 1.04843
  Classification -> best τ=0.475 (val F1=0.1430)
  Directional -> Accuracy: 0.5455, MCC: 0.1097, F1: 0.5652

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.63815 | val 0.89309
  Epoch 012 - train 0.62033 | val 1.01081
  Classification -> best τ=0.420 (val F1=0.2394)
  Directional -> Accuracy: 0.5345, MCC: 0.1708, F1: 0.3721

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.57018 | val 0.70755
  Epoch 017 - train 0.58263 | val 1.01584
  Classification -> best τ=0.575 (val F1=0.2673)
  Directional -> Accuracy: 0.5116, MCC: 0.0604, F1: 0.4000

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.61751 | val 0.73145
  Epoch 011 - train 0.70968 | val 0.76085
  Classification -> best τ=0.450 (val F1=0.1512)
  Directional -> Accuracy: 0.5111, MCC: 0.0149, F1: 0.5926

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.63362 | val 0.73345
  Epoch 014 - train 0.61007 | val 0.78358
  Classification -> best τ=0.555 (val F1=0.1715)
  Directional -> Accuracy: 0.4222, MCC: -0.1476, F1: 0.1875

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.61390 | val 0.70187
  Epoch 017 - train 0.57653 | val 0.70314
  Classification -> best τ=0.465 (val F1=0.2769)
  Directional -> Accuracy: 0.5192, MCC: 0.0000, F1: 0.6835

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.64184 | val 0.72461
  Epoch 016 - train 0.62312 | val 0.73682
  Classification -> best τ=0.390 (val F1=0.3351)
  Directional -> Accuracy: 0.5405, MCC: 0.1282, F1: 0.5000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.68618 | val 0.71295
  Epoch 011 - train 0.63414 | val 0.71968
  Classification -> best τ=0.480 (val F1=0.2774)
  Directional -> Accuracy: 0.5000, MCC: -0.0025, F1: 0.4737

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.64778 | val 0.92661
  Epoch 011 - train 0.63201 | val 1.00321
  Classification -> best τ=0.470 (val F1=0.2254)
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.6364

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.63007 | val 0.69318
  Epoch 013 - train 0.61405 | val 0.76290
  Classification -> best τ=0.425 (val F1=0.3219)
  Directional -> Accuracy: 0.6029, MCC: 0.3381, F1: 0.5091

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.62717 | val 0.69417
  Epoch 017 - train 0.56815 | val 0.72754
  Classification -> best τ=0.580 (val F1=0.2564)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.2143

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.63092 | val 0.88746
  Epoch 011 - train 0.60335 | val 0.83038
  Classification -> best τ=0.460 (val F1=0.1624)
  Directional -> Accuracy: 0.4828, MCC: 0.1236, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.58826 | val 1.83042
  Epoch 011 - train 0.59441 | val 2.12432
  Classification -> best τ=0.490 (val F1=0.2799)
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 11). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.60776 | val 0.66513
  Epoch 020 - train 0.57192 | val 0.69890
  Classification -> best τ=0.345 (val F1=0.5214)
  Directional -> Accuracy: 0.3415, MCC: 0.0000, F1: 0.5091

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.60542 | val 0.74485
  Epoch 011 - train 0.64217 | val 0.75037
  Classification -> best τ=0.480 (val F1=0.3564)
  Directional -> Accuracy: 0.4750, MCC: -0.0682, F1: 0.5532

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 11). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.67802 | val 0.91355
  Epoch 013 - train 0.62405 | val 1.01365
  Classification -> best τ=0.450 (val F1=0.3525)
  Directional -> Accuracy: 0.5065, MCC: 0.0000, F1: 0.6724

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.66120 | val 0.69709
  Epoch 020 - train 0.59201 | val 0.75892
  Classification -> best τ=0.570 (val F1=0.3118)
  Directional -> Accuracy: 0.5625, MCC: 0.1406, F1: 0.6441

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.53712 | val 0.84402
  Epoch 011 - train 0.61960 | val 0.88449
  Classification -> best τ=0.505 (val F1=0.3022)
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.59402 | val 1.08921
  Epoch 011 - train 0.56765 | val 1.16157
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3659, MCC: 0.0000, F1: 0.5357

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.65226 | val 0.96429
  Epoch 011 - train 0.64141 | val 1.02936
  Classification -> best τ=0.465 (val F1=0.1651)
  Directional -> Accuracy: 0.5789, MCC: 0.2460, F1: 0.4545

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.62966 | val 0.94310
  Epoch 013 - train 0.62053 | val 1.38441
  Classification -> best τ=0.565 (val F1=0.4090)
  Directional -> Accuracy: 0.5172, MCC: 0.0213, F1: 0.3636

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.64484 | val 2.12847
  Epoch 011 - train 0.60518 | val 2.29002
  Classification -> best τ=0.500 (val F1=0.1903)
  Directional -> Accuracy: 0.5636, MCC: 0.2052, F1: 0.7073

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.63480 | val 0.89572
  Epoch 011 - train 0.62705 | val 1.00338
  Classification -> best τ=0.485 (val F1=0.1841)
  Directional -> Accuracy: 0.5345, MCC: 0.0721, F1: 0.6747

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...

[I 2026-02-24 22:58:02,757] Trial 34 finished with value: 0.25444287248283165 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 10, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 0.0006298774434843242, 'weight_decay': 0.0002854861474508433, 'lr_patience': 7, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 1.0631276460660746, 'early_stopping_min_delta': 0.0026593557938506974}. Best is trial 32 with value: 0.2908549754956826.

  Epoch 010 - train 0.64437 | val 0.84223
  Epoch 011 - train 0.62954 | val 0.86484
  Classification -> best τ=0.555 (val F1=0.2539)
  Directional -> Accuracy: 0.5714, MCC: 0.1361, F1: 0.5091

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.25444287248283165
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 15
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.67216 | val 0.69535
  Epoch 014 - train 0.66581 | val 0.69117
  Classification -> best τ=0.470 (val F1=0.1135)
  Directional -> Accuracy: 0.4675, MCC: -0.0120, F1: 0.5773

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.64277 | val 0.78207
  Epoch 011 - train 0.60477 | val 0.80532
  Classification -> best τ=0.465 (val F1=0.1123)
  Directional -> Accuracy: 0.6087, MCC: 0.1780, F1: 0.7000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 16). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.66463 | val 0.94520
  Epoch 011 - train 0.69488 | val 0.88892
  Classification -> best τ=0.565 (val F1=0.1399)
  Directional -> Accuracy: 0.4375, MCC: -0.1586, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.65006 | val 1.28187
  Epoch 013 - train 0.65420 | val 1.22184
  Classification -> best τ=0.415 (val F1=0.1610)
  Directional -> Accuracy: 0.5467, MCC: 0.0901, F1: 0.5750

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.61217 | val 1.93366
  Epoch 015 - train 0.54944 | val 1.66203
  Classification -> best τ=0.445 (val F1=0.3446)
  Directional -> Accuracy: 0.5577, MCC: 0.0906, F1: 0.6933

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.68973 | val 1.20421
  Epoch 011 - train 0.64158 | val 1.13338
  Classification -> best τ=0.495 (val F1=0.1733)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.69281 | val 0.71025
  Epoch 019 - train 0.64719 | val 0.75917
  Classification -> best τ=0.595 (val F1=0.2774)
  Directional -> Accuracy: 0.4286, MCC: 0.1400, F1: 0.5833

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 16). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.67297 | val 1.10699
  Epoch 011 - train 0.54552 | val 1.22049
  Classification -> best τ=0.590 (val F1=0.2619)
  Directional -> Accuracy: 0.4889, MCC: 0.0675, F1: 0.5660

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.66599 | val 1.20165
  Epoch 011 - train 0.57808 | val 1.29153
  Classification -> best τ=0.625 (val F1=0.3873)
  Directional -> Accuracy: 0.6341, MCC: 0.1153, F1: 0.2857

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 16). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 16). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.66948 | val 0.82151
  Epoch 013 - train 0.63343 | val 0.74939
  Classification -> best τ=0.490 (val F1=0.1283)
  Directional -> Accuracy: 0.4648, MCC: 0.0299, F1: 0.5870

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.62917 | val 1.06889
  Epoch 012 - train 0.64076 | val 1.93236
  Classification -> best τ=0.425 (val F1=0.2248)
  Directional -> Accuracy: 0.6078, MCC: 0.2079, F1: 0.5238

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.67484 | val 0.83600
  Epoch 016 - train 0.63407 | val 0.86595
  Classification -> best τ=0.700 (val F1=0.2394)
  Directional -> Accuracy: 0.4746, MCC: -0.0811, F1: 0.0606

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.65300 | val 1.14016
  Epoch 011 - train 0.62736 | val 1.53007
  Classification -> best τ=0.465 (val F1=0.2644)
  Directional -> Accuracy: 0.5349, MCC: 0.0570, F1: 0.4737

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.67517 | val 0.81593
  Epoch 013 - train 0.60783 | val 1.11897
  Classification -> best τ=0.235 (val F1=0.2609)
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.60432 | val 2.36433
  Epoch 011 - train 0.63098 | val 3.02571
  Classification -> best τ=0.625 (val F1=0.2689)
  Directional -> Accuracy: 0.4906, MCC: -0.0115, F1: 0.5091

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.60789 | val 0.93200
  Epoch 011 - train 0.61497 | val 0.97701
  Classification -> best τ=0.460 (val F1=0.2516)
  Directional -> Accuracy: 0.6429, MCC: 0.2895, F1: 0.7312

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.64912 | val 1.03402
  Epoch 011 - train 0.66471 | val 1.07494
  Classification -> best τ=0.490 (val F1=0.2515)
  Directional -> Accuracy: 0.3833, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.65624 | val 1.51536
  Epoch 012 - train 0.64515 | val 1.54638
  Classification -> best τ=0.430 (val F1=0.1304)
  Directional -> Accuracy: 0.5132, MCC: -0.0248, F1: 0.6022

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.62313 | val 0.75952
  Epoch 012 - train 0.68902 | val 0.88978
  Classification -> best τ=0.400 (val F1=0.2778)
  Directional -> Accuracy: 0.5303, MCC: 0.1830, F1: 0.4364

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 16). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.64360 | val 0.68464
  Epoch 015 - train 0.61750 | val 0.88014
  Classification -> best τ=0.415 (val F1=0.3422)
  Directional -> Accuracy: 0.5000, MCC: -0.0193, F1: 0.5682

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.63411 | val 1.03352
  Epoch 011 - train 0.62787 | val 1.16858
  Classification -> best τ=0.515 (val F1=0.1399)
  Directional -> Accuracy: 0.3958, MCC: 0.1130, F1: 0.0645

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.65127 | val 1.19965
  Epoch 011 - train 0.64601 | val 1.23399
  Classification -> best τ=0.500 (val F1=0.2070)
  Directional -> Accuracy: 0.5303, MCC: 0.0606, F1: 0.5373

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.66476 | val 1.08886
  Epoch 011 - train 0.62054 | val 1.00676
  Classification -> best τ=0.720 (val F1=0.2892)
  Directional -> Accuracy: 0.4483, MCC: 0.1153, F1: 0.0588

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.63702 | val 1.67988
  Epoch 011 - train 0.63694 | val 1.80899
  Classification -> best τ=0.430 (val F1=0.2086)
  Directional -> Accuracy: 0.5152, MCC: 0.0684, F1: 0.6000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.68669 | val 0.67504
  Epoch 014 - train 0.62376 | val 0.73748
  Classification -> best τ=0.530 (val F1=0.4735)
  Directional -> Accuracy: 0.5357, MCC: 0.1534, F1: 0.4091

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.57984 | val 0.91290
  Epoch 011 - train 0.67186 | val 0.88858
  Classification -> best τ=0.450 (val F1=0.3721)
  Directional -> Accuracy: 0.5106, MCC: 0.2003, F1: 0.6230

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.65429 | val 0.67301
  Epoch 020 - train 0.60715 | val 0.91688
  Classification -> best τ=0.540 (val F1=0.2439)
  Directional -> Accuracy: 0.6512, MCC: 0.2588, F1: 0.7368

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.71488 | val 0.86599
  Epoch 012 - train 0.62357 | val 0.89061
  Classification -> best τ=0.370 (val F1=0.2957)
  Directional -> Accuracy: 0.5172, MCC: 0.1361, F1: 0.3333

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.72085 | val 0.70392
  Epoch 018 - train 0.56784 | val 0.75621
  Classification -> best τ=0.575 (val F1=0.4804)
  Directional -> Accuracy: 0.6190, MCC: 0.2251, F1: 0.6667

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.66824 | val 1.86256
  Epoch 011 - train 0.71251 | val 1.41130
  Classification -> best τ=0.580 (val F1=0.1869)
  Directional -> Accuracy: 0.5227, MCC: 0.0479, F1: 0.4324

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.65968 | val 0.76472
  Epoch 011 - train 0.66845 | val 0.75272
  Classification -> best τ=0.535 (val F1=0.2391)
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.58887 | val 0.91529
  Epoch 014 - train 0.59200 | val 0.87057
  Classification -> best τ=0.490 (val F1=0.3509)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.68325 | val 1.26144
  Epoch 012 - train 0.62379 | val 1.12469
  Classification -> best τ=0.445 (val F1=0.2822)
  Directional -> Accuracy: 0.5676, MCC: 0.0000, F1: 0.7241

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.70233 | val 0.84409
  Epoch 011 - train 0.64630 | val 0.81991
  Classification -> best τ=0.405 (val F1=0.3130)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.66234 | val 1.24389
  Epoch 011 - train 0.69216 | val 1.46536
  Classification -> best τ=0.640 (val F1=0.2857)
  Directional -> Accuracy: 0.5333, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.62124 | val 0.68527
  Epoch 012 - train 0.60262 | val 0.79184
  Classification -> best τ=0.355 (val F1=0.3687)
  Directional -> Accuracy: 0.5970, MCC: 0.1978, F1: 0.6197

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.65135 | val 0.77865
  Epoch 020 - train 0.66400 | val 0.83150
  Classification -> best τ=0.540 (val F1=0.3337)
  Directional -> Accuracy: 0.4884, MCC: -0.0051, F1: 0.0833

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.62387 | val 0.75988
  Epoch 011 - train 0.57536 | val 0.75337
  Classification -> best τ=0.400 (val F1=0.2326)
  Directional -> Accuracy: 0.4912, MCC: 0.0458, F1: 0.6329

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.67149 | val 1.06644
  Epoch 015 - train 0.60964 | val 1.48789
  Classification -> best τ=0.465 (val F1=0.2840)
  Directional -> Accuracy: 0.4043, MCC: 0.1162, F1: 0.0667

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 16). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.59798 | val 0.74995
  Epoch 011 - train 0.57042 | val 0.94928
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.64769 | val 0.82824
  Epoch 011 - train 0.64995 | val 0.83736
  Classification -> best τ=0.515 (val F1=0.4024)
  Directional -> Accuracy: 0.4615, MCC: -0.1091, F1: 0.5532

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 16). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.63609 | val 1.14145
  Epoch 011 - train 0.64244 | val 1.21295
  Classification -> best τ=0.415 (val F1=0.3996)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.69540 | val 0.70588
  Epoch 013 - train 0.66541 | val 0.70397
  Classification -> best τ=0.550 (val F1=0.3616)
  Directional -> Accuracy: 0.5319, MCC: 0.1506, F1: 0.6857

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.51789 | val 1.23504
  Epoch 011 - train 0.61553 | val 1.32545
  Classification -> best τ=0.455 (val F1=0.0737)
  Directional -> Accuracy: 0.6000, MCC: 0.1673, F1: 0.7000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.64679 | val 1.10779
  Epoch 014 - train 0.61363 | val 0.75949
  Classification -> best τ=0.420 (val F1=0.3833)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.65761 | val 1.71224
  Epoch 011 - train 0.64652 | val 1.97645
  Classification -> best τ=0.460 (val F1=0.2515)
  Directional -> Accuracy: 0.4386, MCC: -0.1802, F1: 0.5556

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.60543 | val 1.32927
  Epoch 011 - train 0.59306 | val 1.04836
  Classification -> best τ=0.520 (val F1=0.2554)
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.62886 | val 1.18183
  Epoch 011 - train 0.61469 | val 1.24861
  Classification -> best τ=0.360 (val F1=0.2480)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.69968 | val 1.35923
  Epoch 015 - train 0.64520 | val 1.18730
  Classification -> best τ=0.255 (val F1=0.2741)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.64709 | val 0.81601

[I 2026-02-24 22:59:21,993] Trial 35 finished with value: 0.26240983316639943 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 15, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 0.0033991487680509725, 'weight_decay': 0.0009395064509571342, 'lr_patience': 7, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 1.3415343998558524, 'early_stopping_min_delta': 0.004458838766325748}. Best is trial 32 with value: 0.2908549754956826.

  Epoch 015 - train 0.63181 | val 1.22520
  Classification -> best τ=0.465 (val F1=0.2728)
  Directional -> Accuracy: 0.4355, MCC: -0.1252, F1: 0.4776

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.26240983316639943
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 15
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.62386 | val 0.79880
  Epoch 014 - train 0.60822 | val 0.77385
  Classification -> best τ=0.530 (val F1=0.2453)
  Directional -> Accuracy: 0.4805, MCC: -0.0696, F1: 0.3548

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.55643 | val 1.04756
  Epoch 013 - train 0.55996 | val 0.93477
  Classification -> best τ=0.520 (val F1=0.1164)
  Directional -> Accuracy: 0.6957, MCC: 0.3723, F1: 0.7500

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 16). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.60212 | val 0.92814
  Epoch 012 - train 0.60030 | val 0.92440
  Classification -> best τ=0.525 (val F1=0.2648)
  Directional -> Accuracy: 0.4583, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.60922 | val 1.34623
  Epoch 011 - train 0.60601 | val 1.40163
  Classification -> best τ=0.455 (val F1=0.2041)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.52204 | val 0.97438
  Epoch 015 - train 0.51516 | val 1.19291
  Classification -> best τ=0.400 (val F1=0.3837)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.7000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.51315 | val 0.69508
  Epoch 015 - train 0.46341 | val 0.91260
  Classification -> best τ=0.485 (val F1=0.2588)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.65940 | val 0.77682
  Epoch 011 - train 0.65291 | val 0.77244
  Classification -> best τ=0.505 (val F1=0.1721)
  Directional -> Accuracy: 0.4714, MCC: 0.2265, F1: 0.6022

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 16). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.51799 | val 1.57017
  Epoch 011 - train 0.54333 | val 1.73048
  Classification -> best τ=0.490 (val F1=0.1512)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.61429 | val 0.78235
  Epoch 015 - train 0.55476 | val 1.77695
  Classification -> best τ=0.535 (val F1=0.4960)
  Directional -> Accuracy: 0.4634, MCC: -0.0966, F1: 0.3529

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 16). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 16). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.60008 | val 1.04136
  Epoch 011 - train 0.59750 | val 1.02028
  Classification -> best τ=0.445 (val F1=0.2045)
  Directional -> Accuracy: 0.4366, MCC: -0.0312, F1: 0.5918

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.55714 | val 1.21841
  Epoch 011 - train 0.56378 | val 1.20046
  Classification -> best τ=0.545 (val F1=0.1835)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.58516 | val 0.83570
  Epoch 014 - train 0.60969 | val 1.14092
  Classification -> best τ=0.375 (val F1=0.1479)
  Directional -> Accuracy: 0.5085, MCC: 0.0000, F1: 0.6742

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.57191 | val 1.63315
  Epoch 011 - train 0.60150 | val 1.91666
  Classification -> best τ=0.465 (val F1=0.1818)
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.62408 | val 0.90076
  Epoch 014 - train 0.57957 | val 0.90093
  Classification -> best τ=0.380 (val F1=0.2574)
  Directional -> Accuracy: 0.5082, MCC: 0.0054, F1: 0.6512

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.57969 | val 3.41082
  Epoch 011 - train 0.55766 | val 3.60066
  Classification -> best τ=0.540 (val F1=0.2589)
  Directional -> Accuracy: 0.5472, MCC: 0.1468, F1: 0.0769

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.57531 | val 1.11429
  Epoch 012 - train 0.55954 | val 1.17023
  Classification -> best τ=0.450 (val F1=0.2605)
  Directional -> Accuracy: 0.5857, MCC: 0.2306, F1: 0.7238

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.62775 | val 1.28689
  Epoch 011 - train 0.63573 | val 1.43675
  Classification -> best τ=0.565 (val F1=0.2585)
  Directional -> Accuracy: 0.3833, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.61175 | val 2.41338
  Epoch 011 - train 0.61280 | val 1.98868
  Classification -> best τ=0.490 (val F1=0.1799)
  Directional -> Accuracy: 0.5921, MCC: 0.1030, F1: 0.6931

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.64876 | val 1.26457
  Epoch 014 - train 0.58057 | val 1.44495
  Classification -> best τ=0.400 (val F1=0.2778)
  Directional -> Accuracy: 0.5000, MCC: 0.1525, F1: 0.3529

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 16). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.62156 | val 0.82874
  Epoch 019 - train 0.53035 | val 0.77608
  Classification -> best τ=0.680 (val F1=0.3649)
  Directional -> Accuracy: 0.4868, MCC: 0.0996, F1: 0.1333

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.56977 | val 1.27025
  Epoch 014 - train 0.52251 | val 1.86077
  Classification -> best τ=0.470 (val F1=0.3555)
  Directional -> Accuracy: 0.4583, MCC: -0.0436, F1: 0.4800

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.61117 | val 1.28097
  Epoch 011 - train 0.58159 | val 1.43279
  Classification -> best τ=0.450 (val F1=0.1177)
  Directional -> Accuracy: 0.5303, MCC: 0.0928, F1: 0.6593

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.64210 | val 0.85076
  Epoch 014 - train 0.57243 | val 1.04484
  Classification -> best τ=0.570 (val F1=0.2272)
  Directional -> Accuracy: 0.5172, MCC: 0.1015, F1: 0.4400

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.60707 | val 2.50684
  Epoch 011 - train 0.59664 | val 2.55888
  Classification -> best τ=0.470 (val F1=0.1878)
  Directional -> Accuracy: 0.5303, MCC: 0.0921, F1: 0.5974

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.63594 | val 0.66987
  Epoch 020 - train 0.56249 | val 0.76720
  Classification -> best τ=0.485 (val F1=0.5149)
  Directional -> Accuracy: 0.5893, MCC: 0.2195, F1: 0.5490

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.52734 | val 0.77477
  Epoch 011 - train 0.57499 | val 0.79640
  Classification -> best τ=0.495 (val F1=0.1406)
  Directional -> Accuracy: 0.4681, MCC: 0.1814, F1: 0.6154

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.59728 | val 1.08682
  Epoch 011 - train 0.60669 | val 1.23875
  Classification -> best τ=0.485 (val F1=0.0905)
  Directional -> Accuracy: 0.6047, MCC: 0.1508, F1: 0.7018

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.61520 | val 0.93714
  Epoch 011 - train 0.57385 | val 0.96761
  Classification -> best τ=0.520 (val F1=0.1841)
  Directional -> Accuracy: 0.5000, MCC: 0.1533, F1: 0.2162

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.58976 | val 0.67376
  Epoch 020 - train 0.53569 | val 0.63432
  Classification -> best τ=0.610 (val F1=0.4804)
  Directional -> Accuracy: 0.6190, MCC: 0.2311, F1: 0.6522

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.60725 | val 1.01599
  Epoch 011 - train 0.63255 | val 1.13292
  Classification -> best τ=0.555 (val F1=0.1869)
  Directional -> Accuracy: 0.5227, MCC: 0.0902, F1: 0.1600

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.60443 | val 0.79489
  Epoch 012 - train 0.62203 | val 0.80536
  Classification -> best τ=0.485 (val F1=0.1239)
  Directional -> Accuracy: 0.4545, MCC: -0.0199, F1: 0.0769

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.58470 | val 0.89523
  Epoch 016 - train 0.53528 | val 1.02950
  Classification -> best τ=0.450 (val F1=0.2547)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.59672 | val 1.46179
  Epoch 011 - train 0.59632 | val 1.34524
  Classification -> best τ=0.535 (val F1=0.3441)
  Directional -> Accuracy: 0.5405, MCC: 0.1186, F1: 0.5143

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.57192 | val 0.72025
  Epoch 011 - train 0.57160 | val 0.73596
  Classification -> best τ=0.500 (val F1=0.4792)
  Directional -> Accuracy: 0.5263, MCC: 0.0619, F1: 0.6250

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.61119 | val 0.84277
  Epoch 011 - train 0.61592 | val 0.92189
  Classification -> best τ=0.555 (val F1=0.1476)
  Directional -> Accuracy: 0.4444, MCC: -0.0898, F1: 0.5455

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.56276 | val 0.79510
  Epoch 011 - train 0.58896 | val 0.79092
  Classification -> best τ=0.450 (val F1=0.2070)
  Directional -> Accuracy: 0.5672, MCC: 0.1757, F1: 0.5397

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.61621 | val 0.69082
  Epoch 017 - train 0.56094 | val 0.73430
  Classification -> best τ=0.540 (val F1=0.1869)
  Directional -> Accuracy: 0.6279, MCC: 0.2967, F1: 0.5294

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.59729 | val 0.84814
  Epoch 011 - train 0.58760 | val 0.86708
  Classification -> best τ=0.540 (val F1=0.1431)
  Directional -> Accuracy: 0.4211, MCC: -0.1528, F1: 0.4407

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.57418 | val 1.10048
  Epoch 012 - train 0.52019 | val 1.29970
  Classification -> best τ=0.505 (val F1=0.4174)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 16). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.55974 | val 0.78907
  Epoch 011 - train 0.55082 | val 0.81419
  Classification -> best τ=0.480 (val F1=0.2537)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.61299 | val 0.73818
  Epoch 011 - train 0.54718 | val 0.75107
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.7000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 16). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.57856 | val 1.61299
  Epoch 014 - train 0.57111 | val 2.22427
  Classification -> best τ=0.340 (val F1=0.3965)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.60626 | val 0.71819
  Epoch 011 - train 0.58464 | val 0.73875
  Classification -> best τ=0.540 (val F1=0.1733)
  Directional -> Accuracy: 0.4681, MCC: -0.1506, F1: 0.0000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.49987 | val 0.91491
  Epoch 011 - train 0.55998 | val 0.98200
  Classification -> best τ=0.485 (val F1=0.1387)
  Directional -> Accuracy: 0.6000, MCC: 0.1673, F1: 0.7000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.57195 | val 0.77170
  Epoch 018 - train 0.53661 | val 1.11965
  Classification -> best τ=0.330 (val F1=0.4286)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.62213 | val 1.07156
  Epoch 011 - train 0.61525 | val 1.10988
  Classification -> best τ=0.485 (val F1=0.3465)
  Directional -> Accuracy: 0.5614, MCC: 0.0898, F1: 0.6667

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.59992 | val 1.38612
  Epoch 011 - train 0.59615 | val 1.42348
  Classification -> best τ=0.545 (val F1=0.3948)
  Directional -> Accuracy: 0.5088, MCC: 0.0185, F1: 0.5000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.58069 | val 3.24308
  Epoch 011 - train 0.60499 | val 3.10798
  Classification -> best τ=0.505 (val F1=0.2557)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.65684 | val 1.43086
  Epoch 011 - train 0.59808 | val 1.20790
  Classification -> best τ=0.580 (val F1=0.1094)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.61589 | val 1.07987

[I 2026-02-24 23:01:09,407] Trial 36 finished with value: 0.24839913857793458 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 15, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.1, 'dropout': 0.6000000000000001, 'batch_size': 32, 'learning_rate': 0.0011750827064474587, 'weight_decay': 0.0009157802136619162, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 1.006101405937017, 'early_stopping_min_delta': 0.0016179278812279278}. Best is trial 32 with value: 0.2908549754956826.

  Epoch 014 - train 0.59138 | val 1.04861
  Classification -> best τ=0.605 (val F1=0.2653)
  Directional -> Accuracy: 0.5000, MCC: -0.1240, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.24839913857793458
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: classification
Sequence length: 10
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.69770 | val 0.74673
  Epoch 014 - train 0.65878 | val 0.73240
  Classification -> best τ=0.515 (val F1=0.1572)
  Directional -> Accuracy: 0.5513, MCC: 0.1173, F1: 0.5570

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.65842 | val 0.71982
  Epoch 020 - train 0.62986 | val 0.68647
  Classification -> best τ=0.580 (val F1=0.2346)
  Directional -> Accuracy: 0.4255, MCC: -0.1475, F1: 0.4490

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 11). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.70851 | val 0.80241
  Epoch 011 - train 0.68493 | val 0.79141
  Classification -> best τ=0.510 (val F1=0.2010)
  Directional -> Accuracy: 0.4898, MCC: -0.0217, F1: 0.5098

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.70735 | val 0.82287
  Epoch 011 - train 0.68251 | val 0.71096
  Classification -> best τ=0.450 (val F1=0.0784)
  Directional -> Accuracy: 0.5395, MCC: 0.0000, F1: 0.7009

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.64928 | val 0.83327
  Epoch 014 - train 0.64027 | val 0.72331
  Classification -> best τ=0.555 (val F1=0.3591)
  Directional -> Accuracy: 0.5769, MCC: 0.2141, F1: 0.4762

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.62030 | val 0.81570
  Epoch 011 - train 0.62373 | val 0.85903
  Classification -> best τ=0.500 (val F1=0.1031)
  Directional -> Accuracy: 0.6531, MCC: 0.3232, F1: 0.6047

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.68250 | val 0.70732
  Epoch 011 - train 0.69738 | val 0.70414
  Classification -> best τ=0.505 (val F1=0.2877)
  Directional -> Accuracy: 0.3944, MCC: -0.1103, F1: 0.5567

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 11). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.61057 | val 1.46876
  Epoch 011 - train 0.55610 | val 1.71370
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4130, MCC: 0.0000, F1: 0.5846

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.68291 | val 0.71881
  Epoch 013 - train 0.66866 | val 0.72473
  Classification -> best τ=0.485 (val F1=0.3303)
  Directional -> Accuracy: 0.5476, MCC: -0.0877, F1: 0.1739

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for proper time series validation for BRK-A. Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for proper time series validation for BSAC. Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.66356 | val 0.75339
  Epoch 011 - train 0.64819 | val 0.76827
  Classification -> best τ=0.465 (val F1=0.2683)
  Directional -> Accuracy: 0.4366, MCC: 0.0000, F1: 0.6078

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.65900 | val 0.90625
  Epoch 011 - train 0.64236 | val 0.94065
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.69350 | val 0.74593
  Epoch 011 - train 0.68244 | val 0.74447
  Classification -> best τ=0.500 (val F1=0.0473)
  Directional -> Accuracy: 0.6271, MCC: 0.2953, F1: 0.7105

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.64430 | val 0.99682
  Epoch 011 - train 0.63879 | val 1.12135
  Classification -> best τ=0.440 (val F1=0.2379)
  Directional -> Accuracy: 0.5000, MCC: 0.0753, F1: 0.6071

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.67150 | val 0.65678
  Epoch 016 - train 0.66719 | val 0.65941
  Classification -> best τ=0.445 (val F1=0.3681)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6353

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.66894 | val 0.97178
  Epoch 011 - train 0.65329 | val 0.96649
  Classification -> best τ=0.495 (val F1=0.0801)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.66584 | val 0.77179
  Epoch 015 - train 0.66700 | val 0.79842
  Classification -> best τ=0.590 (val F1=0.3164)
  Directional -> Accuracy: 0.5211, MCC: 0.0375, F1: 0.5526

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.65952 | val 0.96961
  Epoch 011 - train 0.69448 | val 0.94468
  Classification -> best τ=0.500 (val F1=0.1189)
  Directional -> Accuracy: 0.3934, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.66723 | val 0.93849
  Epoch 011 - train 0.68053 | val 0.85708
  Classification -> best τ=0.495 (val F1=0.1774)
  Directional -> Accuracy: 0.5844, MCC: 0.1262, F1: 0.6596

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.68044 | val 0.72016
  Epoch 016 - train 0.67777 | val 0.71628
  Classification -> best τ=0.575 (val F1=0.2930)
  Directional -> Accuracy: 0.4627, MCC: 0.0675, F1: 0.2500

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 11). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.67923 | val 0.70894
  Epoch 014 - train 0.64795 | val 0.71198
  Classification -> best τ=0.385 (val F1=0.2764)
  Directional -> Accuracy: 0.5065, MCC: -0.0259, F1: 0.6042

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.66156 | val 0.74958
  Epoch 011 - train 0.69223 | val 0.76895
  Classification -> best τ=0.540 (val F1=0.1299)
  Directional -> Accuracy: 0.6122, MCC: -0.1100, F1: 0.7595

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.69651 | val 0.74776
  Epoch 011 - train 0.68063 | val 0.73871
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5075, MCC: 0.0000, F1: 0.6733

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.65753 | val 0.68893
  Epoch 015 - train 0.67186 | val 0.69116
  Classification -> best τ=0.570 (val F1=0.2743)
  Directional -> Accuracy: 0.5254, MCC: 0.0385, F1: 0.5758

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.66520 | val 0.69524
  Epoch 011 - train 0.66211 | val 0.69413
  Classification -> best τ=0.475 (val F1=0.1283)
  Directional -> Accuracy: 0.5522, MCC: 0.1455, F1: 0.6341

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.68621 | val 0.67615
  Epoch 017 - train 0.65152 | val 0.72609
  Classification -> best τ=0.480 (val F1=0.3750)
  Directional -> Accuracy: 0.5614, MCC: 0.2277, F1: 0.4444

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.70148 | val 0.71372
  Epoch 013 - train 0.66934 | val 0.70388
  Classification -> best τ=0.510 (val F1=0.1373)
  Directional -> Accuracy: 0.4167, MCC: 0.0000, F1: 0.5882

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.66812 | val 0.68732
  Epoch 020 - train 0.62901 | val 0.76125
  Classification -> best τ=0.485 (val F1=0.1749)
  Directional -> Accuracy: 0.5227, MCC: -0.0781, F1: 0.6557

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.67846 | val 0.68302
  Epoch 020 - train 0.67962 | val 0.71331
  Classification -> best τ=0.425 (val F1=0.3180)
  Directional -> Accuracy: 0.5517, MCC: 0.2279, F1: 0.3810

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.64039 | val 0.69564
  Epoch 011 - train 0.67108 | val 0.72659
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.68969 | val 0.74850
  Epoch 011 - train 0.69578 | val 0.76664
  Classification -> best τ=0.535 (val F1=0.0395)
  Directional -> Accuracy: 0.6222, MCC: 0.2440, F1: 0.6531

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.68254 | val 0.67495
  Epoch 020 - train 0.66541 | val 0.67116
  Classification -> best τ=0.575 (val F1=0.3162)
  Directional -> Accuracy: 0.4444, MCC: -0.1071, F1: 0.0741

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.65512 | val 0.66142
  Epoch 020 - train 0.65648 | val 0.69878
  Classification -> best τ=0.445 (val F1=0.3160)
  Directional -> Accuracy: 0.5192, MCC: 0.0000, F1: 0.6835

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.67103 | val 0.66968
  Epoch 016 - train 0.66333 | val 0.67506
  Classification -> best τ=0.430 (val F1=0.3850)
  Directional -> Accuracy: 0.5135, MCC: 0.0803, F1: 0.4545

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.70962 | val 0.70931
  Epoch 011 - train 0.68681 | val 0.70838
  Classification -> best τ=0.470 (val F1=0.1748)
  Directional -> Accuracy: 0.5250, MCC: 0.0613, F1: 0.5581

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.68629 | val 0.89552
  Epoch 011 - train 0.68106 | val 0.94761
  Classification -> best τ=0.440 (val F1=0.1954)
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.6364

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.65729 | val 0.70846
  Epoch 011 - train 0.66392 | val 0.71450
  Classification -> best τ=0.460 (val F1=0.2579)
  Directional -> Accuracy: 0.5882, MCC: 0.1510, F1: 0.6500

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.70912 | val 0.69344
  Epoch 018 - train 0.63363 | val 0.71212
  Classification -> best τ=0.460 (val F1=0.2478)
  Directional -> Accuracy: 0.6591, MCC: 0.3487, F1: 0.5714

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.66463 | val 0.74696
  Epoch 011 - train 0.61253 | val 0.72889
  Classification -> best τ=0.500 (val F1=0.2413)
  Directional -> Accuracy: 0.4655, MCC: -0.0767, F1: 0.4151

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.67140 | val 1.24341
  Epoch 011 - train 0.63840 | val 1.24552
  Classification -> best τ=0.510 (val F1=0.2525)
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 11). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.66752 | val 0.68612
  Epoch 020 - train 0.55271 | val 0.86994
  Classification -> best τ=0.450 (val F1=0.3246)
  Directional -> Accuracy: 0.3659, MCC: 0.0048, F1: 0.5000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.65882 | val 0.74650
  Epoch 011 - train 0.63685 | val 0.77607
  Classification -> best τ=0.460 (val F1=0.3564)
  Directional -> Accuracy: 0.5250, MCC: 0.0553, F1: 0.5128

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 11). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.68716 | val 0.72589
  Epoch 011 - train 0.66802 | val 0.77806
  Classification -> best τ=0.450 (val F1=0.1314)
  Directional -> Accuracy: 0.5065, MCC: 0.0000, F1: 0.6724

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.64962 | val 0.69492
  Epoch 011 - train 0.67726 | val 0.69878
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.61329 | val 0.89337
  Epoch 011 - train 0.71269 | val 0.96073
  Classification -> best τ=0.455 (val F1=0.0423)
  Directional -> Accuracy: 0.5652, MCC: 0.0782, F1: 0.6667

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.69024 | val 0.72610
  Epoch 011 - train 0.65111 | val 0.74075
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3659, MCC: 0.0000, F1: 0.5357

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.69953 | val 0.79937
  Epoch 011 - train 0.68667 | val 0.74210
  Classification -> best τ=0.530 (val F1=0.1629)
  Directional -> Accuracy: 0.6491, MCC: 0.3487, F1: 0.6000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.69305 | val 0.91893
  Epoch 016 - train 0.63018 | val 0.91122
  Classification -> best τ=0.525 (val F1=0.3501)
  Directional -> Accuracy: 0.5517, MCC: 0.1250, F1: 0.2353

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.68208 | val 1.01547
  Epoch 011 - train 0.67014 | val 0.97971
  Classification -> best τ=0.455 (val F1=0.1296)
  Directional -> Accuracy: 0.5818, MCC: 0.1848, F1: 0.7013

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.64173 | val 0.86885
  Epoch 012 - train 0.66175 | val 0.77216
  Classification -> best τ=0.525 (val F1=0.1208)
  Directional -> Accuracy: 0.5172, MCC: 0.0000, F1: 0.6818

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...

[I 2026-02-24 23:02:09,730] Trial 37 finished with value: 0.1950405268672694 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 10, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 32, 'learning_rate': 0.0018992239345023353, 'weight_decay': 0.00033896105951661807, 'lr_patience': 7, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 1.54993487622449, 'early_stopping_min_delta': 0.005448156067646876}. Best is trial 32 with value: 0.2908549754956826.

  Epoch 010 - train 0.65453 | val 0.74974
  Epoch 011 - train 0.67694 | val 0.72962
  Classification -> best τ=0.530 (val F1=0.2345)
  Directional -> Accuracy: 0.5238, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.1950405268672694
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 15
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.70046 | val 0.71198
  Epoch 014 - train 0.68818 | val 0.71452
  Classification -> best τ=0.380 (val F1=0.1341)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.68121 | val 0.68802
  Epoch 020 - train 0.68981 | val 0.68074
  Epoch 022 - train 0.69485 | val 0.68016
  Classification -> best τ=0.445 (val F1=0.1823)
  Directional -> Accuracy: 0.6304, MCC: 0.2280, F1: 0.7213

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 16). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.71721 | val 0.71535
  Epoch 011 - train 0.69882 | val 0.71641
  Classification -> best τ=0.530 (val F1=0.0215)
  Directional -> Accuracy: 0.5625, MCC: 0.1221, F1: 0.5882

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.70452 | val 0.69314
  Epoch 016 - train 0.70940 | val 0.69781
  Classification -> best τ=0.495 (val F1=0.2219)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.69946 | val 0.68169
  Epoch 020 - train 0.68962 | val 0.67274
  Epoch 030 - train 0.67146 | val 0.66401
  Epoch 040 - train 0.67079 | val 0.65866
  Epoch 050 - train 0.66671 | val 0.65320
  Classification -> best τ=0.520 (val F1=0.3867)
  Directional -> Accuracy: 0.5769, MCC: 0.2141, F1: 0.4762

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.67988 | val 0.68876
  Epoch 011 - train 0.68759 | val 0.68968
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.69525 | val 0.69388
  Epoch 011 - train 0.70453 | val 0.69402
  Classification -> best τ=0.490 (val F1=0.0859)
  Directional -> Accuracy: 0.4429, MCC: -0.0939, F1: 0.4179

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 16). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.68557 | val 0.71798
  Epoch 011 - train 0.70624 | val 0.72610
  Classification -> best τ=0.480 (val F1=0.2229)
  Directional -> Accuracy: 0.4889, MCC: -0.0260, F1: 0.4390

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.70874 | val 0.68705
  Epoch 018 - train 0.73277 | val 0.69009
  Classification -> best τ=0.575 (val F1=0.3154)
  Directional -> Accuracy: 0.4390, MCC: -0.0265, F1: 0.4651

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 16). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 16). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.70571 | val 0.85072
  Epoch 011 - train 0.71276 | val 0.85290
  Classification -> best τ=0.480 (val F1=0.2646)
  Directional -> Accuracy: 0.4366, MCC: 0.0000, F1: 0.6078

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.71892 | val 0.70586
  Epoch 011 - train 0.71536 | val 0.70828
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.6400

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.70149 | val 0.72701
  Epoch 011 - train 0.70735 | val 0.72955
  Classification -> best τ=0.535 (val F1=0.2061)
  Directional -> Accuracy: 0.5424, MCC: 0.1905, F1: 0.6897

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.71880 | val 0.80043
  Epoch 011 - train 0.71024 | val 0.81082
  Classification -> best τ=0.465 (val F1=0.2454)
  Directional -> Accuracy: 0.4419, MCC: -0.0471, F1: 0.5714

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.71169 | val 0.78182
  Epoch 011 - train 0.69200 | val 0.78043
  Classification -> best τ=0.535 (val F1=0.2422)
  Directional -> Accuracy: 0.5410, MCC: 0.0952, F1: 0.4400

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.69459 | val 0.77292
  Epoch 011 - train 0.71160 | val 0.77785
  Classification -> best τ=0.535 (val F1=0.0252)
  Directional -> Accuracy: 0.4528, MCC: -0.0756, F1: 0.5672

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.68272 | val 0.67758
  Epoch 020 - train 0.67826 | val 0.67352
  Epoch 022 - train 0.67379 | val 0.67415
  Classification -> best τ=0.555 (val F1=0.3541)
  Directional -> Accuracy: 0.5143, MCC: 0.1004, F1: 0.3462

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.71257 | val 0.73843
  Epoch 011 - train 0.70895 | val 0.73884
  Classification -> best τ=0.515 (val F1=0.0689)
  Directional -> Accuracy: 0.5000, MCC: 0.0406, F1: 0.5161

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.70725 | val 0.73905
  Epoch 011 - train 0.71260 | val 0.74173
  Classification -> best τ=0.465 (val F1=0.1217)
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.69252 | val 0.68111
  Epoch 020 - train 0.70322 | val 0.67855
  Epoch 028 - train 0.68871 | val 0.67789
  Classification -> best τ=0.505 (val F1=0.3346)
  Directional -> Accuracy: 0.5455, MCC: 0.2306, F1: 0.4444

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 16). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.70225 | val 0.70263
  Epoch 011 - train 0.70865 | val 0.70223
  Classification -> best τ=0.490 (val F1=0.1826)
  Directional -> Accuracy: 0.5921, MCC: 0.1848, F1: 0.6076

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.68988 | val 0.75603
  Epoch 011 - train 0.69960 | val 0.75981
  Classification -> best τ=0.470 (val F1=0.2680)
  Directional -> Accuracy: 0.5417, MCC: 0.2130, F1: 0.5000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.71395 | val 0.70935
  Epoch 011 - train 0.70660 | val 0.70924
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.70229 | val 0.72643
  Epoch 011 - train 0.70724 | val 0.72668
  Classification -> best τ=0.495 (val F1=0.0137)
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.68513 | val 0.92334
  Epoch 011 - train 0.66757 | val 0.93340
  Classification -> best τ=0.500 (val F1=0.2797)
  Directional -> Accuracy: 0.5758, MCC: 0.1867, F1: 0.6316

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.70673 | val 0.69566
  Epoch 011 - train 0.69622 | val 0.69505
  Classification -> best τ=0.485 (val F1=0.0888)
  Directional -> Accuracy: 0.4643, MCC: -0.0246, F1: 0.3478

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.66885 | val 0.68507
  Epoch 020 - train 0.68094 | val 0.68236
  Epoch 021 - train 0.67842 | val 0.68278
  Classification -> best τ=0.580 (val F1=0.2067)
  Directional -> Accuracy: 0.5106, MCC: 0.2625, F1: 0.6349

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.70800 | val 0.77839
  Epoch 011 - train 0.68991 | val 0.79363
  Classification -> best τ=0.510 (val F1=0.1816)
  Directional -> Accuracy: 0.3721, MCC: -0.2151, F1: 0.0690

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.72656 | val 0.78085
  Epoch 011 - train 0.71337 | val 0.78059
  Classification -> best τ=0.500 (val F1=0.1187)
  Directional -> Accuracy: 0.4138, MCC: -0.2300, F1: 0.5278

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.69422 | val 0.70132
  Epoch 011 - train 0.72365 | val 0.70117
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.7077

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.69093 | val 0.72083
  Epoch 011 - train 0.70522 | val 0.72290
  Classification -> best τ=0.555 (val F1=0.0212)
  Directional -> Accuracy: 0.5227, MCC: 0.0563, F1: 0.3226

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.69302 | val 0.74151
  Epoch 011 - train 0.68908 | val 0.74741
  Classification -> best τ=0.475 (val F1=0.2089)
  Directional -> Accuracy: 0.5455, MCC: 0.0363, F1: 0.6774

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.70054 | val 0.71787
  Epoch 011 - train 0.71213 | val 0.71740
  Classification -> best τ=0.540 (val F1=0.2177)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.71411 | val 0.70974
  Epoch 014 - train 0.71036 | val 0.70538
  Classification -> best τ=0.490 (val F1=0.1022)
  Directional -> Accuracy: 0.5000, MCC: -0.1009, F1: 0.6337

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.69641 | val 0.67376
  Epoch 020 - train 0.67203 | val 0.66447
  Epoch 025 - train 0.70074 | val 0.67461
  Classification -> best τ=0.495 (val F1=0.4792)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.4571

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.70749 | val 0.69180
  Epoch 011 - train 0.73374 | val 0.69251
  Classification -> best τ=0.460 (val F1=0.3307)
  Directional -> Accuracy: 0.4667, MCC: -0.0357, F1: 0.5714

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.69827 | val 0.70209
  Epoch 011 - train 0.68641 | val 0.70155
  Classification -> best τ=0.495 (val F1=0.1677)
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.71881 | val 0.71496
  Epoch 011 - train 0.70331 | val 0.71701
  Classification -> best τ=0.530 (val F1=0.0150)
  Directional -> Accuracy: 0.4186, MCC: -0.2803, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.71456 | val 0.84419
  Epoch 011 - train 0.69844 | val 0.85387
  Classification -> best τ=0.525 (val F1=0.2236)
  Directional -> Accuracy: 0.4912, MCC: -0.1231, F1: 0.0645

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.71591 | val 0.67379
  Epoch 011 - train 0.70772 | val 0.67357
  Classification -> best τ=0.455 (val F1=0.1537)
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 16). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.68265 | val 0.67121
  Epoch 020 - train 0.69989 | val 0.67182
  Epoch 024 - train 0.69605 | val 0.67449
  Classification -> best τ=0.470 (val F1=0.3779)
  Directional -> Accuracy: 0.5750, MCC: 0.1732, F1: 0.5143

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.74911 | val 0.67753
  Epoch 020 - train 0.76424 | val 0.65696
  Epoch 030 - train 0.69346 | val 0.65739
  Epoch 033 - train 0.70576 | val 0.65936
  Classification -> best τ=0.465 (val F1=0.4564)
  Directional -> Accuracy: 0.5641, MCC: 0.1065, F1: 0.6909

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 16). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.69844 | val 0.69488
  Epoch 011 - train 0.67693 | val 0.69550
  Classification -> best τ=0.525 (val F1=0.1046)
  Directional -> Accuracy: 0.5789, MCC: 0.1588, F1: 0.6000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.67610 | val 0.69747
  Epoch 011 - train 0.69926 | val 0.69964
  Classification -> best τ=0.510 (val F1=0.1132)
  Directional -> Accuracy: 0.5532, MCC: 0.2154, F1: 0.6957

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.71962 | val 0.68860
  Epoch 011 - train 0.76047 | val 0.68937
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.72215 | val 0.69860
  Epoch 011 - train 0.71971 | val 0.69970
  Classification -> best τ=0.495 (val F1=0.4116)
  Directional -> Accuracy: 0.6500, MCC: 0.2308, F1: 0.5000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.69920 | val 0.67185
  Epoch 014 - train 0.67927 | val 0.67416
  Classification -> best τ=0.560 (val F1=0.1379)
  Directional -> Accuracy: 0.5088, MCC: -0.0316, F1: 0.6216

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.71847 | val 0.68119
  Epoch 019 - train 0.72209 | val 0.69089
  Classification -> best τ=0.515 (val F1=0.2536)
  Directional -> Accuracy: 0.4737, MCC: -0.0970, F1: 0.2500

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.70638 | val 0.70075
  Epoch 014 - train 0.73014 | val 0.71025
  Classification -> best τ=0.490 (val F1=0.0832)
  Directional -> Accuracy: 0.5000, MCC: 0.0409, F1: 0.2286

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.69781 | val 0.77483
  Epoch 011 - train 0.71389 | val 0.78469
  Classification -> best τ=0.505 (val F1=0.2349)
  Directional -> Accuracy: 0.5789, MCC: 0.2330, F1: 0.3684

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.72069 | val 0.68446
  Epoch 011 - train 0.69594 | val 0.68463
  Classification -> best τ=0.465 (val F1=0.1483)
  Directional -> Accuracy: 0.5161, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.18028978614835453

[I 2026-02-24 23:03:14,970] Trial 38 finished with value: 0.18028978614835453 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 15, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.1, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 1.594111938394467e-05, 'weight_decay': 0.00051843385494133, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 1.3031096130832158, 'early_stopping_min_delta': 0.004591789619829589}. Best is trial 32 with value: 0.2908549754956826.

Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 10
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.66895 | val 0.90498
  Epoch 011 - train 0.66686 | val 0.92193
  Classification -> best τ=0.495 (val F1=0.2436)
  Directional -> Accuracy: 0.5128, MCC: -0.0838, F1: 0.1364

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.65634 | val 0.76924
  Epoch 012 - train 0.60546 | val 0.75631
  Classification -> best τ=0.510 (val F1=0.2346)
  Directional -> Accuracy: 0.5532, MCC: 0.0556, F1: 0.6667

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 11). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.68519 | val 0.78248
  Epoch 012 - train 0.66607 | val 0.87698
  Classification -> best τ=0.470 (val F1=0.3574)
  Directional -> Accuracy: 0.6327, MCC: 0.2671, F1: 0.6400

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.68908 | val 0.86466
  Epoch 011 - train 0.66378 | val 0.77899
  Classification -> best τ=0.460 (val F1=0.2485)
  Directional -> Accuracy: 0.5395, MCC: 0.0713, F1: 0.5783

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.63265 | val 0.69627
  Epoch 016 - train 0.63080 | val 0.70621
  Classification -> best τ=0.470 (val F1=0.4382)
  Directional -> Accuracy: 0.7500, MCC: 0.4959, F1: 0.7797

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.62220 | val 1.26444
  Epoch 011 - train 0.60311 | val 1.41858
  Classification -> best τ=0.560 (val F1=0.2182)
  Directional -> Accuracy: 0.5306, MCC: 0.1014, F1: 0.3030

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.71622 | val 0.74551
  Epoch 011 - train 0.67305 | val 0.72380
  Classification -> best τ=0.455 (val F1=0.2099)
  Directional -> Accuracy: 0.5352, MCC: 0.1076, F1: 0.5352

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 11). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.66580 | val 1.44574
  Epoch 011 - train 0.62787 | val 1.56864
  Classification -> best τ=0.490 (val F1=0.0645)
  Directional -> Accuracy: 0.4348, MCC: 0.0428, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.66533 | val 0.73861
  Epoch 016 - train 0.65529 | val 0.76678
  Classification -> best τ=0.560 (val F1=0.4301)
  Directional -> Accuracy: 0.5952, MCC: 0.0144, F1: 0.1905

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for proper time series validation for BRK-A. Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for proper time series validation for BSAC. Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.67237 | val 1.15469
  Epoch 011 - train 0.62833 | val 1.22406
  Classification -> best τ=0.460 (val F1=0.2198)
  Directional -> Accuracy: 0.4507, MCC: 0.1052, F1: 0.6139

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.67980 | val 0.75136
  Epoch 011 - train 0.64818 | val 0.75193
  Classification -> best τ=0.525 (val F1=0.0199)
  Directional -> Accuracy: 0.5000, MCC: -0.0249, F1: 0.3810

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.64517 | val 0.83322
  Epoch 011 - train 0.66634 | val 0.88332
  Classification -> best τ=0.545 (val F1=0.0891)
  Directional -> Accuracy: 0.3559, MCC: -0.3154, F1: 0.1739

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.61882 | val 1.23361
  Epoch 011 - train 0.63413 | val 1.19592
  Classification -> best τ=0.445 (val F1=0.2362)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.66653 | val 0.65917
  Epoch 020 - train 0.67434 | val 0.61647
  Epoch 029 - train 0.62295 | val 0.61116
  Classification -> best τ=0.335 (val F1=0.3481)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.62597 | val 2.51173
  Epoch 011 - train 0.64742 | val 2.35006
  Classification -> best τ=0.540 (val F1=0.1223)
  Directional -> Accuracy: 0.5370, MCC: 0.1425, F1: 0.0741

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.66266 | val 0.74963
  Epoch 012 - train 0.66534 | val 0.73187
  Classification -> best τ=0.455 (val F1=0.2856)
  Directional -> Accuracy: 0.5493, MCC: 0.1283, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.68683 | val 1.58673
  Epoch 011 - train 0.65947 | val 1.74156
  Classification -> best τ=0.500 (val F1=0.2440)
  Directional -> Accuracy: 0.5574, MCC: 0.2268, F1: 0.5091

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.66265 | val 0.92392
  Epoch 011 - train 0.67463 | val 1.02924
  Classification -> best τ=0.510 (val F1=0.1103)
  Directional -> Accuracy: 0.3896, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.67265 | val 0.67336
  Epoch 015 - train 0.64740 | val 0.69691
  Classification -> best τ=0.565 (val F1=0.3280)
  Directional -> Accuracy: 0.4179, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 11). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.65578 | val 0.68131
  Epoch 017 - train 0.65168 | val 0.70372
  Classification -> best τ=0.480 (val F1=0.3429)
  Directional -> Accuracy: 0.5455, MCC: 0.0430, F1: 0.6667

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.64729 | val 0.69027
  Epoch 013 - train 0.67606 | val 0.70211
  Classification -> best τ=0.535 (val F1=0.2625)
  Directional -> Accuracy: 0.4898, MCC: 0.2221, F1: 0.3590

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.68035 | val 0.88928
  Epoch 011 - train 0.66329 | val 0.90094
  Classification -> best τ=0.480 (val F1=0.1177)
  Directional -> Accuracy: 0.5224, MCC: 0.0754, F1: 0.6735

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.67553 | val 0.75930
  Epoch 012 - train 0.66940 | val 0.79004
  Classification -> best τ=0.570 (val F1=0.2634)
  Directional -> Accuracy: 0.4746, MCC: 0.1985, F1: 0.1622

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.65816 | val 1.31829
  Epoch 011 - train 0.65027 | val 1.08876
  Classification -> best τ=0.415 (val F1=0.1994)
  Directional -> Accuracy: 0.5224, MCC: 0.0835, F1: 0.6190

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.64734 | val 0.65076
  Epoch 015 - train 0.63107 | val 0.67641
  Classification -> best τ=0.480 (val F1=0.4532)
  Directional -> Accuracy: 0.5614, MCC: 0.2277, F1: 0.4444

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.72222 | val 0.70932
  Epoch 011 - train 0.66922 | val 0.71498
  Classification -> best τ=0.465 (val F1=0.0874)
  Directional -> Accuracy: 0.5208, MCC: -0.2182, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.64003 | val 1.22066
  Epoch 011 - train 0.69256 | val 1.35175
  Classification -> best τ=0.490 (val F1=0.0790)
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.64402 | val 0.80246
  Epoch 011 - train 0.64729 | val 0.82352
  Classification -> best τ=0.455 (val F1=0.2201)
  Directional -> Accuracy: 0.5345, MCC: 0.1708, F1: 0.3721

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.64175 | val 0.71664
  Epoch 011 - train 0.65201 | val 0.73837
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.70452 | val 0.74203
  Epoch 011 - train 0.69845 | val 0.75305
  Classification -> best τ=0.470 (val F1=0.1976)
  Directional -> Accuracy: 0.5778, MCC: 0.1540, F1: 0.6122

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.66403 | val 0.67687
  Epoch 018 - train 0.68721 | val 0.76414
  Classification -> best τ=0.445 (val F1=0.2272)
  Directional -> Accuracy: 0.5333, MCC: 0.0000, F1: 0.6957

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.65206 | val 0.66843
  Epoch 017 - train 0.63355 | val 0.69249
  Classification -> best τ=0.500 (val F1=0.2999)
  Directional -> Accuracy: 0.5192, MCC: 0.0000, F1: 0.6835

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.64951 | val 0.66344
  Epoch 015 - train 0.66788 | val 0.65765
  Classification -> best τ=0.310 (val F1=0.3273)
  Directional -> Accuracy: 0.5676, MCC: 0.1562, F1: 0.5676

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.67841 | val 0.70120
  Epoch 011 - train 0.66508 | val 0.70048
  Classification -> best τ=0.490 (val F1=0.0836)
  Directional -> Accuracy: 0.5250, MCC: 0.1001, F1: 0.6275

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.68074 | val 0.93299
  Epoch 011 - train 0.65186 | val 0.99821
  Classification -> best τ=0.500 (val F1=0.2421)
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.6364

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.68332 | val 0.70409
  Epoch 013 - train 0.62016 | val 0.70329
  Classification -> best τ=0.385 (val F1=0.3575)
  Directional -> Accuracy: 0.5882, MCC: 0.1583, F1: 0.6410

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.64260 | val 0.70817
  Epoch 011 - train 0.64013 | val 0.70217
  Classification -> best τ=0.525 (val F1=0.1636)
  Directional -> Accuracy: 0.4773, MCC: -0.0459, F1: 0.4390

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.67830 | val 0.76012
  Epoch 012 - train 0.67027 | val 0.76917
  Classification -> best τ=0.430 (val F1=0.2076)
  Directional -> Accuracy: 0.5345, MCC: 0.1515, F1: 0.6400

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.65693 | val 1.18823
  Epoch 011 - train 0.63273 | val 1.13667
  Classification -> best τ=0.520 (val F1=0.1912)
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 11). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.63565 | val 0.64385
  Epoch 020 - train 0.61593 | val 0.66832
  Classification -> best τ=0.370 (val F1=0.5214)
  Directional -> Accuracy: 0.3415, MCC: 0.0000, F1: 0.5091

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.64268 | val 0.72378
  Epoch 011 - train 0.69657 | val 0.73111
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5250, MCC: 0.0000, F1: 0.6885

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 11). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.66537 | val 0.77029
  Epoch 013 - train 0.65728 | val 0.93210
  Classification -> best τ=0.480 (val F1=0.2526)
  Directional -> Accuracy: 0.5065, MCC: 0.0000, F1: 0.6724

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.61208 | val 0.72175
  Epoch 011 - train 0.66036 | val 0.71605
  Classification -> best τ=0.515 (val F1=0.2511)
  Directional -> Accuracy: 0.5208, MCC: 0.0436, F1: 0.4390

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.60995 | val 0.87659
  Epoch 011 - train 0.59026 | val 0.92077
  Classification -> best τ=0.555 (val F1=0.1860)
  Directional -> Accuracy: 0.4783, MCC: 0.0217, F1: 0.3684

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.59390 | val 0.97056
  Epoch 011 - train 0.65353 | val 0.99586
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3659, MCC: 0.0000, F1: 0.5357

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.65708 | val 1.16751
  Epoch 011 - train 0.66211 | val 1.18831
  Classification -> best τ=0.480 (val F1=0.1620)
  Directional -> Accuracy: 0.5965, MCC: 0.2585, F1: 0.5106

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.66453 | val 0.88046
  Epoch 011 - train 0.67860 | val 0.99375
  Classification -> best τ=0.530 (val F1=0.1389)
  Directional -> Accuracy: 0.5517, MCC: 0.1152, F1: 0.5938

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.67903 | val 1.58379
  Epoch 011 - train 0.64502 | val 1.52421
  Classification -> best τ=0.485 (val F1=0.2208)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.65181 | val 0.68570
  Epoch 020 - train 0.66319 | val 0.79387
  Classification -> best τ=0.500 (val F1=0.2785)
  Directional -> Accuracy: 0.5517, MCC: 0.0976, F1: 0.6176

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.67537 | val 0.82220

[I 2026-02-24 23:04:15,814] Trial 39 finished with value: 0.22065288641346295 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 10, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 32, 'learning_rate': 0.00042723156841563507, 'weight_decay': 8.279215483689621e-05, 'lr_patience': 7, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.8081843733754305, 'early_stopping_min_delta': 0.0028319117268784475}. Best is trial 32 with value: 0.2908549754956826.

  Epoch 013 - train 0.65910 | val 0.93943
  Classification -> best τ=0.505 (val F1=0.2500)
  Directional -> Accuracy: 0.5238, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.22065288641346295
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: classification
Sequence length: 15
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.67874 | val 0.73679
  Epoch 011 - train 0.67245 | val 0.73806
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.65057 | val 0.68918
  Epoch 018 - train 0.62543 | val 0.73589
  Classification -> best τ=0.440 (val F1=0.1833)
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 16). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.67801 | val 0.68748
  Epoch 017 - train 0.68038 | val 0.71379
  Classification -> best τ=0.520 (val F1=0.2485)
  Directional -> Accuracy: 0.4792, MCC: 0.1342, F1: 0.0741

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.67699 | val 1.37417
  Epoch 011 - train 0.67902 | val 1.35962
  Classification -> best τ=0.485 (val F1=0.1778)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.64287 | val 0.65872
  Epoch 020 - train 0.64142 | val 0.68911
  Classification -> best τ=0.520 (val F1=0.3719)
  Directional -> Accuracy: 0.7308, MCC: 0.4702, F1: 0.7308

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.66611 | val 0.70723
  Epoch 011 - train 0.66144 | val 0.70953
  Classification -> best τ=0.535 (val F1=0.0056)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.68457 | val 0.70445
  Epoch 011 - train 0.69104 | val 0.70591
  Classification -> best τ=0.530 (val F1=0.1204)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.5714

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 16). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.66098 | val 0.77806
  Epoch 011 - train 0.62795 | val 0.79007
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.66665 | val 0.70074
  Epoch 017 - train 0.63542 | val 0.76437
  Classification -> best τ=0.535 (val F1=0.3877)
  Directional -> Accuracy: 0.4878, MCC: -0.0321, F1: 0.4000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 16). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 16). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.67266 | val 0.79025
  Epoch 011 - train 0.64246 | val 0.79363
  Classification -> best τ=0.515 (val F1=0.0358)
  Directional -> Accuracy: 0.6056, MCC: 0.1706, F1: 0.3636

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.68166 | val 0.76500
  Epoch 011 - train 0.65912 | val 0.79787
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.6400

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.69610 | val 0.73451
  Epoch 011 - train 0.70148 | val 0.73462
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5085, MCC: 0.0000, F1: 0.6742

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.64367 | val 0.79818
  Epoch 011 - train 0.64916 | val 0.84053
  Classification -> best τ=0.520 (val F1=0.0046)
  Directional -> Accuracy: 0.5349, MCC: 0.2232, F1: 0.6429

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.66354 | val 0.62800
  Epoch 020 - train 0.64747 | val 0.62915
  Classification -> best τ=0.475 (val F1=0.3315)
  Directional -> Accuracy: 0.5082, MCC: 0.0197, F1: 0.4643

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.67140 | val 1.09688
  Epoch 011 - train 0.67785 | val 1.22796
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4717, MCC: 0.0000, F1: 0.6410

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.67926 | val 0.72301
  Epoch 015 - train 0.64043 | val 0.76429
  Classification -> best τ=0.370 (val F1=0.2927)
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.67290 | val 0.86761
  Epoch 011 - train 0.66151 | val 0.88986
  Classification -> best τ=0.500 (val F1=0.1920)
  Directional -> Accuracy: 0.6167, MCC: 0.0000, F1: 0.7629

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.68662 | val 1.04374
  Epoch 011 - train 0.68194 | val 1.06720
  Classification -> best τ=0.530 (val F1=0.0634)
  Directional -> Accuracy: 0.4868, MCC: 0.1105, F1: 0.3810

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.67803 | val 0.74880
  Epoch 014 - train 0.65690 | val 0.79044
  Classification -> best τ=0.505 (val F1=0.2485)
  Directional -> Accuracy: 0.4697, MCC: 0.0938, F1: 0.2857

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 16). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.67426 | val 0.66876
  Epoch 020 - train 0.66557 | val 0.69206
  Epoch 021 - train 0.66004 | val 0.69312
  Classification -> best τ=0.480 (val F1=0.3277)
  Directional -> Accuracy: 0.5395, MCC: 0.0000, F1: 0.7009

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.68832 | val 0.73512
  Epoch 011 - train 0.66501 | val 0.74965
  Classification -> best τ=0.510 (val F1=0.0089)
  Directional -> Accuracy: 0.4375, MCC: 0.0413, F1: 0.3077

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.68478 | val 0.78864
  Epoch 011 - train 0.68348 | val 0.79314
  Classification -> best τ=0.505 (val F1=0.0696)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.65665 | val 0.71019
  Epoch 014 - train 0.67992 | val 0.73220
  Classification -> best τ=0.550 (val F1=0.3117)
  Directional -> Accuracy: 0.5000, MCC: 0.0698, F1: 0.4082

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.65340 | val 1.31285
  Epoch 013 - train 0.65439 | val 1.49989
  Classification -> best τ=0.490 (val F1=0.1950)
  Directional -> Accuracy: 0.5152, MCC: 0.0950, F1: 0.6279

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.68065 | val 0.66990
  Epoch 020 - train 0.66713 | val 0.66435
  Epoch 023 - train 0.66005 | val 0.67206
  Classification -> best τ=0.530 (val F1=0.3566)
  Directional -> Accuracy: 0.5357, MCC: 0.1020, F1: 0.5000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.67077 | val 0.69832
  Epoch 011 - train 0.67793 | val 0.69943
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4255, MCC: 0.0000, F1: 0.5970

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.66128 | val 0.77784
  Epoch 011 - train 0.65357 | val 0.79804
  Classification -> best τ=0.485 (val F1=0.0511)
  Directional -> Accuracy: 0.3721, MCC: -0.2245, F1: 0.3415

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.67919 | val 0.68470
  Epoch 011 - train 0.67993 | val 0.68698
  Classification -> best τ=0.480 (val F1=0.2908)
  Directional -> Accuracy: 0.5172, MCC: 0.2453, F1: 0.2222

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.66957 | val 0.69183
  Epoch 011 - train 0.67837 | val 0.69099
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.7077

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.69507 | val 0.70720
  Epoch 011 - train 0.69479 | val 0.71920
  Classification -> best τ=0.465 (val F1=0.1869)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.3889

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.69615 | val 0.70884
  Epoch 011 - train 0.67757 | val 0.71862
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.64953 | val 0.68389
  Epoch 018 - train 0.65800 | val 0.70602
  Classification -> best τ=0.505 (val F1=0.1681)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.67408 | val 0.71557
  Epoch 015 - train 0.67924 | val 0.72300
  Classification -> best τ=0.470 (val F1=0.3677)
  Directional -> Accuracy: 0.5946, MCC: 0.1528, F1: 0.6739

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.66832 | val 0.70103
  Epoch 011 - train 0.66225 | val 0.70348
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.68357 | val 0.76996
  Epoch 011 - train 0.66387 | val 0.79185
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.6364

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.63883 | val 0.74873
  Epoch 015 - train 0.62765 | val 0.75425
  Classification -> best τ=0.400 (val F1=0.3521)
  Directional -> Accuracy: 0.5672, MCC: 0.1079, F1: 0.6329

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.65764 | val 0.69023
  Epoch 020 - train 0.67063 | val 0.69001
  Classification -> best τ=0.495 (val F1=0.2810)
  Directional -> Accuracy: 0.5116, MCC: 0.0641, F1: 0.2222

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.64942 | val 0.74868
  Epoch 011 - train 0.64920 | val 0.75086
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.65956 | val 0.85098
  Epoch 011 - train 0.66487 | val 0.91837
  Classification -> best τ=0.525 (val F1=0.0837)
  Directional -> Accuracy: 0.5745, MCC: -0.0834, F1: 0.7222

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 16). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.65750 | val 0.72280
  Epoch 011 - train 0.65502 | val 0.72510
  Classification -> best τ=0.535 (val F1=0.2582)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.66323 | val 0.70675
  Epoch 011 - train 0.66134 | val 0.70922
  Classification -> best τ=0.520 (val F1=0.1870)
  Directional -> Accuracy: 0.5385, MCC: 0.0179, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 16). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.64964 | val 0.71236
  Epoch 011 - train 0.65299 | val 0.71364
  Classification -> best τ=0.475 (val F1=0.2030)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.65969 | val 0.70510
  Epoch 011 - train 0.63769 | val 0.70460
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.67081 | val 0.72489
  Epoch 011 - train 0.65555 | val 0.72675
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.66937 | val 0.71691
  Epoch 011 - train 0.65772 | val 0.72779
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.69067 | val 0.80060
  Epoch 011 - train 0.68520 | val 0.80678
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5439, MCC: 0.0000, F1: 0.7045

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.66452 | val 0.83102
  Epoch 011 - train 0.64511 | val 0.85403
  Classification -> best τ=0.555 (val F1=0.2162)
  Directional -> Accuracy: 0.4912, MCC: -0.0148, F1: 0.4912

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.66626 | val 0.86729
  Epoch 011 - train 0.66504 | val 0.91897
  Classification -> best τ=0.510 (val F1=0.0955)
  Directional -> Accuracy: 0.4815, MCC: 0.0000, F1: 0.0000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.66890 | val 1.01680
  Epoch 011 - train 0.66913 | val 1.02524
  Classification -> best τ=0.545 (val F1=0.0500)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.67340 | val 0.72656
  Epoch 011 - train 0.70738 | val 0.73488
  Classification -> best τ=0.510 (val F1=0.1166)
  Directional -> Accuracy: 0.5323, MCC: 0.1241, F1: 0.6506

[I 2026-02-24 23:05:33,566] Trial 40 finished with value: 0.1368198123219124 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 15, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.6000000000000001, 'batch_size': 32, 'learning_rate': 0.00016868261119386418, 'weight_decay': 0.0005306279159006088, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 1.633149786548119, 'early_stopping_min_delta': 0.005474642331250737}. Best is trial 32 with value: 0.2908549754956826.

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.1368198123219124
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 15
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.66869 | val 0.72768
  Epoch 017 - train 0.59653 | val 0.85483
  Classification -> best τ=0.650 (val F1=0.2453)
  Directional -> Accuracy: 0.5065, MCC: -0.0886, F1: 0.1364

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.62380 | val 1.01832
  Epoch 011 - train 0.61720 | val 1.24143
  Classification -> best τ=0.425 (val F1=0.1424)
  Directional -> Accuracy: 0.5870, MCC: 0.1202, F1: 0.6984

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 16). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.65792 | val 0.87836
  Epoch 012 - train 0.70251 | val 0.90790
  Classification -> best τ=0.500 (val F1=0.2708)
  Directional -> Accuracy: 0.5208, MCC: 0.0249, F1: 0.5818

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.66113 | val 1.12302
  Epoch 011 - train 0.66099 | val 1.00288
  Classification -> best τ=0.505 (val F1=0.0925)
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.66908 | val 1.42647
  Epoch 015 - train 0.53653 | val 2.15505
  Classification -> best τ=0.445 (val F1=0.4357)
  Directional -> Accuracy: 0.7500, MCC: 0.4989, F1: 0.7636

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.59325 | val 0.73838
  Epoch 016 - train 0.48958 | val 1.25045
  Classification -> best τ=0.490 (val F1=0.2176)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.67866 | val 0.69882
  Epoch 014 - train 0.65218 | val 0.74514
  Classification -> best τ=0.510 (val F1=0.2806)
  Directional -> Accuracy: 0.4286, MCC: 0.1400, F1: 0.5833

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 16). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.64464 | val 1.36132
  Epoch 011 - train 0.61682 | val 1.60107
  Classification -> best τ=0.540 (val F1=0.2039)
  Directional -> Accuracy: 0.5778, MCC: 0.1170, F1: 0.4571

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.58927 | val 0.97230
  Epoch 011 - train 0.64229 | val 1.30793
  Classification -> best τ=0.635 (val F1=0.4282)
  Directional -> Accuracy: 0.5854, MCC: 0.1705, F1: 0.5143

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 16). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 16). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.66402 | val 0.82079
  Epoch 015 - train 0.63701 | val 0.86637
  Classification -> best τ=0.445 (val F1=0.1694)
  Directional -> Accuracy: 0.5634, MCC: 0.1733, F1: 0.5974

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.64458 | val 0.85140
  Epoch 012 - train 0.63545 | val 1.45650
  Classification -> best τ=0.425 (val F1=0.2540)
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.6400

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.67831 | val 0.73584
  Epoch 013 - train 0.61483 | val 0.97543
  Classification -> best τ=0.445 (val F1=0.1479)
  Directional -> Accuracy: 0.5085, MCC: 0.0000, F1: 0.6742

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.64088 | val 1.96408
  Epoch 013 - train 0.62420 | val 1.41799
  Classification -> best τ=0.455 (val F1=0.1711)
  Directional -> Accuracy: 0.5349, MCC: 0.0027, F1: 0.2857

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.65791 | val 1.01530
  Epoch 014 - train 0.61746 | val 1.08100
  Classification -> best τ=0.430 (val F1=0.3430)
  Directional -> Accuracy: 0.5902, MCC: 0.1797, F1: 0.6154

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.59302 | val 3.09930
  Epoch 011 - train 0.60512 | val 3.35760
  Classification -> best τ=0.640 (val F1=0.2798)
  Directional -> Accuracy: 0.5283, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.61552 | val 0.81826
  Epoch 011 - train 0.62497 | val 0.83322
  Classification -> best τ=0.445 (val F1=0.2834)
  Directional -> Accuracy: 0.5571, MCC: 0.0890, F1: 0.7048

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.66593 | val 1.16713
  Epoch 011 - train 0.64717 | val 1.27163
  Classification -> best τ=0.445 (val F1=0.1223)
  Directional -> Accuracy: 0.5833, MCC: -0.0067, F1: 0.7191

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.65791 | val 1.53132
  Epoch 011 - train 0.61937 | val 1.44653
  Classification -> best τ=0.410 (val F1=0.1733)
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.66626 | val 1.08085
  Epoch 013 - train 0.65513 | val 0.97006
  Classification -> best τ=0.415 (val F1=0.2778)
  Directional -> Accuracy: 0.4848, MCC: 0.1240, F1: 0.3200

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 16). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.63021 | val 0.65506
  Epoch 020 - train 0.61948 | val 1.01541
  Classification -> best τ=0.325 (val F1=0.3043)
  Directional -> Accuracy: 0.5263, MCC: 0.1393, F1: 0.3333

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.62675 | val 1.65981
  Epoch 013 - train 0.59725 | val 1.71763
  Classification -> best τ=0.440 (val F1=0.3126)
  Directional -> Accuracy: 0.5417, MCC: 0.2914, F1: 0.4500

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.67422 | val 1.20111
  Epoch 011 - train 0.66684 | val 1.06482
  Classification -> best τ=0.605 (val F1=0.2264)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.64859 | val 0.84890
  Epoch 011 - train 0.64932 | val 0.94066
  Classification -> best τ=0.645 (val F1=0.3198)
  Directional -> Accuracy: 0.4138, MCC: -0.1111, F1: 0.0556

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.66989 | val 2.27360
  Epoch 012 - train 0.61318 | val 2.83640
  Classification -> best τ=0.465 (val F1=0.2319)
  Directional -> Accuracy: 0.5606, MCC: 0.1374, F1: 0.5915

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.65487 | val 0.77629
  Epoch 013 - train 0.69862 | val 0.73803
  Classification -> best τ=0.625 (val F1=0.3534)
  Directional -> Accuracy: 0.5000, MCC: 0.0996, F1: 0.3000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.69764 | val 0.76624
  Epoch 015 - train 0.56795 | val 0.99773
  Classification -> best τ=0.520 (val F1=0.2717)
  Directional -> Accuracy: 0.5532, MCC: 0.1315, F1: 0.5532

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.64374 | val 0.73927
  Epoch 016 - train 0.61011 | val 0.98590
  Classification -> best τ=0.550 (val F1=0.3243)
  Directional -> Accuracy: 0.5814, MCC: 0.0908, F1: 0.6897

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.67151 | val 0.81848
  Epoch 012 - train 0.64146 | val 0.76085
  Classification -> best τ=0.420 (val F1=0.2156)
  Directional -> Accuracy: 0.5862, MCC: 0.2461, F1: 0.5000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.65565 | val 0.87291
  Epoch 020 - train 0.56290 | val 0.65657
  Classification -> best τ=0.680 (val F1=0.4193)
  Directional -> Accuracy: 0.5238, MCC: 0.0673, F1: 0.5000

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.55724 | val 1.01750
  Epoch 014 - train 0.62285 | val 0.99505
  Classification -> best τ=0.700 (val F1=0.1869)
  Directional -> Accuracy: 0.5227, MCC: 0.0479, F1: 0.4324

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.64641 | val 1.30288
  Epoch 011 - train 0.63965 | val 1.58085
  Classification -> best τ=0.470 (val F1=0.2374)
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.63062 | val 0.85637
  Epoch 016 - train 0.60112 | val 0.83906
  Classification -> best τ=0.450 (val F1=0.3170)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.62886 | val 2.03082
  Epoch 015 - train 0.56421 | val 2.21654
  Classification -> best τ=0.255 (val F1=0.3723)
  Directional -> Accuracy: 0.5676, MCC: 0.1479, F1: 0.5789

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.68180 | val 0.80041
  Epoch 011 - train 0.69049 | val 0.78978
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.62340 | val 1.03366
  Epoch 013 - train 0.61719 | val 1.22142
  Classification -> best τ=0.465 (val F1=0.2922)
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.6364

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.61098 | val 0.75780
  Epoch 017 - train 0.59482 | val 0.73778
  Classification -> best τ=0.335 (val F1=0.3444)
  Directional -> Accuracy: 0.5821, MCC: 0.2407, F1: 0.5172

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.70025 | val 0.72504
  Epoch 011 - train 0.68368 | val 0.74870
  Classification -> best τ=0.445 (val F1=0.1325)
  Directional -> Accuracy: 0.5116, MCC: 0.0641, F1: 0.2222

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.61056 | val 0.68505
  Epoch 011 - train 0.66432 | val 0.71286
  Classification -> best τ=0.410 (val F1=0.2382)
  Directional -> Accuracy: 0.5614, MCC: 0.1491, F1: 0.6154

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.67546 | val 1.13435
  Epoch 011 - train 0.60752 | val 1.16017
  Classification -> best τ=0.510 (val F1=0.3516)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 16). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.62177 | val 1.38602
  Epoch 011 - train 0.59825 | val 1.66007
  Classification -> best τ=0.455 (val F1=0.2000)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.64175 | val 0.67256
  Epoch 019 - train 0.56438 | val 0.89771
  Classification -> best τ=0.330 (val F1=0.3397)
  Directional -> Accuracy: 0.4615, MCC: -0.2012, F1: 0.6182

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 16). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.62868 | val 1.22368
  Epoch 012 - train 0.60414 | val 1.47406
  Classification -> best τ=0.415 (val F1=0.4430)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.65949 | val 1.27505
  Epoch 011 - train 0.65506 | val 1.28142
  Classification -> best τ=0.475 (val F1=0.3254)
  Directional -> Accuracy: 0.5106, MCC: 0.0237, F1: 0.4889

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.62147 | val 1.16579
  Epoch 011 - train 0.57616 | val 1.23178
  Classification -> best τ=0.490 (val F1=0.2000)
  Directional -> Accuracy: 0.6222, MCC: 0.2236, F1: 0.7213

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.72595 | val 0.87320
  Epoch 014 - train 0.55701 | val 0.78152
  Classification -> best τ=0.485 (val F1=0.4880)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.66339 | val 1.29583
  Epoch 014 - train 0.65896 | val 1.01927
  Classification -> best τ=0.685 (val F1=0.1464)
  Directional -> Accuracy: 0.4035, MCC: -0.2196, F1: 0.4848

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.61326 | val 2.04926
  Epoch 011 - train 0.57572 | val 1.77317
  Classification -> best τ=0.610 (val F1=0.3508)
  Directional -> Accuracy: 0.5614, MCC: 0.1968, F1: 0.6575

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.62053 | val 1.98056
  Epoch 012 - train 0.60693 | val 1.76721
  Classification -> best τ=0.300 (val F1=0.1884)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.65307 | val 1.35975
  Epoch 013 - train 0.65212 | val 0.85849
  Classification -> best τ=0.515 (val F1=0.2225)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.65870 | val 1.43427

[I 2026-02-24 23:06:54,265] Trial 41 finished with value: 0.26490122751622525 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 15, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 0.003332711414143097, 'weight_decay': 0.0001367313669191067, 'lr_patience': 7, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 1.3877133289907673, 'early_stopping_min_delta': 0.004509898356940314}. Best is trial 32 with value: 0.2908549754956826.

  Epoch 016 - train 0.57580 | val 1.69598
  Classification -> best τ=0.395 (val F1=0.3502)
  Directional -> Accuracy: 0.4677, MCC: -0.0572, F1: 0.5926

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.26490122751622525
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 15
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.66109 | val 1.18957
  Epoch 013 - train 0.63104 | val 1.18276
  Classification -> best τ=0.515 (val F1=0.2851)
  Directional -> Accuracy: 0.5584, MCC: 0.0800, F1: 0.3462

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.61339 | val 0.73361
  Epoch 011 - train 0.64311 | val 0.70114
  Classification -> best τ=0.425 (val F1=0.1823)
  Directional -> Accuracy: 0.6087, MCC: 0.1962, F1: 0.7353

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 16). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.68493 | val 0.65825
  Epoch 020 - train 0.60783 | val 0.68614
  Classification -> best τ=0.530 (val F1=0.4233)
  Directional -> Accuracy: 0.4583, MCC: -0.0648, F1: 0.4091

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.68499 | val 1.10666
  Epoch 011 - train 0.64648 | val 1.02794
  Classification -> best τ=0.385 (val F1=0.2137)
  Directional -> Accuracy: 0.5600, MCC: 0.1193, F1: 0.5823

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.56873 | val 1.28301
  Epoch 011 - train 0.55203 | val 1.62150
  Classification -> best τ=0.470 (val F1=0.3765)
  Directional -> Accuracy: 0.6154, MCC: 0.2196, F1: 0.6667

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.57650 | val 0.98695
  Epoch 011 - train 0.55855 | val 1.21425
  Classification -> best τ=0.530 (val F1=0.3393)
  Directional -> Accuracy: 0.5625, MCC: 0.1251, F1: 0.5532

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.70347 | val 0.71858
  Epoch 015 - train 0.62982 | val 0.86127
  Classification -> best τ=0.490 (val F1=0.1750)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.5714

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 16). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.68756 | val 1.31822
  Epoch 011 - train 0.55830 | val 1.71973
  Classification -> best τ=0.520 (val F1=0.2229)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.67072 | val 1.07729
  Epoch 011 - train 0.62472 | val 1.28052
  Classification -> best τ=0.555 (val F1=0.5282)
  Directional -> Accuracy: 0.3902, MCC: -0.1590, F1: 0.3902

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 16). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 16). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.64532 | val 1.16794
  Epoch 011 - train 0.61875 | val 1.12373
  Classification -> best τ=0.450 (val F1=0.2479)
  Directional -> Accuracy: 0.4366, MCC: 0.0000, F1: 0.6078

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.66583 | val 1.68367
  Epoch 011 - train 0.62295 | val 1.89074
  Classification -> best τ=0.580 (val F1=0.2819)
  Directional -> Accuracy: 0.5490, MCC: 0.0860, F1: 0.4651

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.69124 | val 1.12547
  Epoch 014 - train 0.63171 | val 0.73152
  Classification -> best τ=0.365 (val F1=0.1479)
  Directional -> Accuracy: 0.5085, MCC: 0.0000, F1: 0.6742

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.62416 | val 2.02454
  Epoch 011 - train 0.64325 | val 1.72892
  Classification -> best τ=0.465 (val F1=0.3135)
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.68921 | val 0.96844
  Epoch 015 - train 0.64807 | val 1.04437
  Classification -> best τ=0.265 (val F1=0.2501)
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.59953 | val 3.47854
  Epoch 011 - train 0.57360 | val 4.11674
  Classification -> best τ=0.480 (val F1=0.2090)
  Directional -> Accuracy: 0.6415, MCC: 0.2801, F1: 0.5581

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.63472 | val 1.13773
  Epoch 011 - train 0.61213 | val 1.06283
  Classification -> best τ=0.570 (val F1=0.3181)
  Directional -> Accuracy: 0.5143, MCC: 0.0587, F1: 0.4516

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.68721 | val 1.42598
  Epoch 012 - train 0.64407 | val 0.98270
  Classification -> best τ=0.405 (val F1=0.1346)
  Directional -> Accuracy: 0.6167, MCC: 0.0000, F1: 0.7629

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.64366 | val 1.43042
  Epoch 011 - train 0.64856 | val 1.13655
  Classification -> best τ=0.480 (val F1=0.0592)
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.64337 | val 0.97277
  Epoch 012 - train 0.63075 | val 1.16319
  Classification -> best τ=0.385 (val F1=0.2972)
  Directional -> Accuracy: 0.5000, MCC: 0.1111, F1: 0.4000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 16). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.64637 | val 0.65183
  Epoch 020 - train 0.54704 | val 0.94166
  Classification -> best τ=0.290 (val F1=0.2913)
  Directional -> Accuracy: 0.5395, MCC: 0.1241, F1: 0.4444

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.61263 | val 1.07666
  Epoch 011 - train 0.63449 | val 0.77037
  Classification -> best τ=0.485 (val F1=0.2174)
  Directional -> Accuracy: 0.4583, MCC: -0.0648, F1: 0.5000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.66622 | val 1.20346
  Epoch 011 - train 0.65369 | val 1.02325
  Classification -> best τ=0.540 (val F1=0.1276)
  Directional -> Accuracy: 0.5152, MCC: 0.0727, F1: 0.1111

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.67133 | val 0.93500
  Epoch 012 - train 0.65332 | val 0.93424
  Classification -> best τ=0.565 (val F1=0.2272)
  Directional -> Accuracy: 0.4828, MCC: 0.1087, F1: 0.2500

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.66640 | val 2.77500
  Epoch 011 - train 0.64196 | val 2.38299
  Classification -> best τ=0.390 (val F1=0.1878)
  Directional -> Accuracy: 0.5455, MCC: 0.1090, F1: 0.5833

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.65943 | val 0.69370
  Epoch 020 - train 0.61330 | val 0.88681
  Classification -> best τ=0.475 (val F1=0.4105)
  Directional -> Accuracy: 0.6250, MCC: 0.2945, F1: 0.5882

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.56308 | val 0.78654
  Epoch 011 - train 0.63519 | val 0.78733
  Classification -> best τ=0.475 (val F1=0.2717)
  Directional -> Accuracy: 0.5745, MCC: 0.0576, F1: 0.2308

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.69663 | val 0.91843
  Epoch 011 - train 0.67401 | val 0.99941
  Classification -> best τ=0.500 (val F1=0.1309)
  Directional -> Accuracy: 0.4651, MCC: -0.0140, F1: 0.4103

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.66047 | val 0.83634
  Epoch 011 - train 0.65691 | val 0.81746
  Classification -> best τ=0.440 (val F1=0.2652)
  Directional -> Accuracy: 0.5345, MCC: 0.1948, F1: 0.3415

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.72293 | val 0.69513
  Epoch 020 - train 0.64617 | val 0.61252
  Classification -> best τ=0.590 (val F1=0.4208)
  Directional -> Accuracy: 0.5714, MCC: 0.1083, F1: 0.6786

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.62233 | val 1.35617
  Epoch 011 - train 0.66889 | val 1.60335
  Classification -> best τ=0.565 (val F1=0.1869)
  Directional -> Accuracy: 0.5227, MCC: 0.1525, F1: 0.0870

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.67103 | val 0.92369
  Epoch 012 - train 0.67426 | val 0.90226
  Classification -> best τ=0.570 (val F1=0.1778)
  Directional -> Accuracy: 0.4091, MCC: -0.1876, F1: 0.0714

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.61730 | val 0.89169
  Epoch 011 - train 0.59389 | val 0.81485
  Classification -> best τ=0.470 (val F1=0.2680)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.62442 | val 1.61983
  Epoch 012 - train 0.63252 | val 1.50344
  Classification -> best τ=0.490 (val F1=0.3259)
  Directional -> Accuracy: 0.5541, MCC: 0.1516, F1: 0.5217

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.55284 | val 0.79303
  Epoch 011 - train 0.65525 | val 0.79568
  Classification -> best τ=0.395 (val F1=0.3130)
  Directional -> Accuracy: 0.5526, MCC: 0.1715, F1: 0.6792

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.63801 | val 1.20887
  Epoch 011 - train 0.61712 | val 1.34253
  Classification -> best τ=0.560 (val F1=0.1411)
  Directional -> Accuracy: 0.4889, MCC: 0.1410, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.63422 | val 0.70053
  Epoch 011 - train 0.58683 | val 0.74702
  Classification -> best τ=0.425 (val F1=0.3521)
  Directional -> Accuracy: 0.4925, MCC: 0.1685, F1: 0.2273

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.61035 | val 0.68637
  Epoch 015 - train 0.65238 | val 0.71545
  Classification -> best τ=0.490 (val F1=0.3004)
  Directional -> Accuracy: 0.6279, MCC: 0.2967, F1: 0.5294

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.67242 | val 0.76758
  Epoch 011 - train 0.64432 | val 0.77329
  Classification -> best τ=0.475 (val F1=0.1564)
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.61531 | val 2.10194
  Epoch 011 - train 0.62308 | val 2.12380
  Classification -> best τ=0.485 (val F1=0.3026)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 16). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.55925 | val 1.18883
  Epoch 014 - train 0.54601 | val 1.62011
  Classification -> best τ=0.515 (val F1=0.3779)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.64552 | val 0.74689
  Epoch 011 - train 0.65471 | val 0.75478
  Classification -> best τ=0.480 (val F1=0.0793)
  Directional -> Accuracy: 0.5128, MCC: -0.0473, F1: 0.6545

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 16). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.66063 | val 1.00242
  Epoch 011 - train 0.64959 | val 1.07578
  Classification -> best τ=0.415 (val F1=0.3763)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.65789 | val 0.73117
  Epoch 011 - train 0.65127 | val 0.73879
  Classification -> best τ=0.520 (val F1=0.0124)
  Directional -> Accuracy: 0.5957, MCC: 0.2632, F1: 0.7077

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.59488 | val 1.12098
  Epoch 011 - train 0.54011 | val 1.19536
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.60232 | val 0.91268
  Epoch 011 - train 0.65841 | val 0.88752
  Classification -> best τ=0.495 (val F1=0.3647)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.66667 | val 1.71175
  Epoch 011 - train 0.65091 | val 2.11924
  Classification -> best τ=0.455 (val F1=0.2054)
  Directional -> Accuracy: 0.6842, MCC: 0.3684, F1: 0.7000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.60867 | val 1.90749
  Epoch 011 - train 0.59137 | val 2.10696
  Classification -> best τ=0.595 (val F1=0.3359)
  Directional -> Accuracy: 0.5088, MCC: 0.0964, F1: 0.6410

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.68792 | val 1.51241
  Epoch 011 - train 0.67151 | val 1.55293
  Classification -> best τ=0.515 (val F1=0.0770)
  Directional -> Accuracy: 0.4074, MCC: -0.1841, F1: 0.4074

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.68152 | val 1.27916
  Epoch 011 - train 0.64221 | val 1.04681
  Classification -> best τ=0.595 (val F1=0.1009)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.63811 | val 0.79381

[I 2026-02-24 23:08:10,608] Trial 42 finished with value: 0.24322411818513787 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 15, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 0.0015340162521826392, 'weight_decay': 3.039595732573699e-05, 'lr_patience': 7, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 1.4600145370001893, 'early_stopping_min_delta': 0.00441642986991108}. Best is trial 32 with value: 0.2908549754956826.

  Epoch 013 - train 0.59291 | val 0.91994
  Classification -> best τ=0.570 (val F1=0.1507)
  Directional -> Accuracy: 0.4839, MCC: -0.1229, F1: 0.0588

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.24322411818513787
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 15
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.65150 | val 0.76492
  Epoch 014 - train 0.58895 | val 1.10891
  Classification -> best τ=0.500 (val F1=0.2931)
  Directional -> Accuracy: 0.5325, MCC: 0.0220, F1: 0.3333

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.57875 | val 0.88305
  Epoch 011 - train 0.58507 | val 0.97864
  Classification -> best τ=0.455 (val F1=0.1641)
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 16). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.63293 | val 0.80909
  Epoch 011 - train 0.62706 | val 0.81875
  Classification -> best τ=0.605 (val F1=0.1399)
  Directional -> Accuracy: 0.4583, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.64563 | val 2.30521
  Epoch 011 - train 0.66980 | val 1.97559
  Classification -> best τ=0.450 (val F1=0.1771)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.59935 | val 0.85957
  Epoch 013 - train 0.57236 | val 1.08857
  Classification -> best τ=0.570 (val F1=0.3719)
  Directional -> Accuracy: 0.7115, MCC: 0.4190, F1: 0.7541

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.54162 | val 1.04954
  Epoch 012 - train 0.53836 | val 1.13871
  Classification -> best τ=0.465 (val F1=0.2108)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.63050 | val 0.68372
  Epoch 020 - train 0.58207 | val 0.81825
  Classification -> best τ=0.275 (val F1=0.3133)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.5714

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 16). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.52393 | val 1.72873
  Epoch 011 - train 0.59030 | val 2.05736
  Classification -> best τ=0.595 (val F1=0.2229)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.60209 | val 0.95097
  Epoch 011 - train 0.57032 | val 1.35310
  Classification -> best τ=0.530 (val F1=0.5163)
  Directional -> Accuracy: 0.5366, MCC: -0.1712, F1: 0.0952

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 16). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 16). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.62828 | val 1.38888
  Epoch 011 - train 0.63917 | val 0.96946
  Classification -> best τ=0.385 (val F1=0.1654)
  Directional -> Accuracy: 0.4366, MCC: 0.0000, F1: 0.6078

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.58402 | val 0.87211
  Epoch 013 - train 0.60731 | val 1.75235
  Classification -> best τ=0.425 (val F1=0.1835)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.59582 | val 0.77324
  Epoch 011 - train 0.61312 | val 1.15039
  Classification -> best τ=0.515 (val F1=0.1741)
  Directional -> Accuracy: 0.6610, MCC: 0.3310, F1: 0.6296

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.63084 | val 2.37256
  Epoch 011 - train 0.55772 | val 2.04805
  Classification -> best τ=0.405 (val F1=0.2454)
  Directional -> Accuracy: 0.5349, MCC: 0.2232, F1: 0.6429

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.63140 | val 0.83831
  Epoch 012 - train 0.60070 | val 1.05047
  Classification -> best τ=0.345 (val F1=0.2987)
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.58428 | val 3.51530
  Epoch 011 - train 0.61273 | val 4.26899
  Classification -> best τ=0.660 (val F1=0.2525)
  Directional -> Accuracy: 0.5472, MCC: 0.1468, F1: 0.0769

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.59225 | val 0.91549
  Epoch 013 - train 0.61116 | val 0.91134
  Classification -> best τ=0.440 (val F1=0.3382)
  Directional -> Accuracy: 0.6429, MCC: 0.2895, F1: 0.7312

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.62715 | val 1.57078
  Epoch 011 - train 0.63565 | val 1.42912
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6167, MCC: 0.0000, F1: 0.7629

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.60027 | val 1.68634
  Epoch 012 - train 0.63088 | val 1.83467
  Classification -> best τ=0.465 (val F1=0.0951)
  Directional -> Accuracy: 0.5658, MCC: 0.1521, F1: 0.5926

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.62940 | val 1.28368
  Epoch 013 - train 0.59697 | val 0.94307
  Classification -> best τ=0.375 (val F1=0.2674)
  Directional -> Accuracy: 0.5152, MCC: 0.1796, F1: 0.3846

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 16). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.60918 | val 0.75773
  Epoch 011 - train 0.58354 | val 0.82360
  Classification -> best τ=0.425 (val F1=0.2477)
  Directional -> Accuracy: 0.5000, MCC: 0.0602, F1: 0.3214

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.58490 | val 1.36544
  Epoch 016 - train 0.52094 | val 1.34645
  Classification -> best τ=0.460 (val F1=0.4692)
  Directional -> Accuracy: 0.3750, MCC: -0.1657, F1: 0.3182

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.61926 | val 1.38753
  Epoch 012 - train 0.59909 | val 1.72747
  Classification -> best τ=0.755 (val F1=0.2264)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.65748 | val 0.84963
  Epoch 011 - train 0.64080 | val 0.83985
  Classification -> best τ=0.705 (val F1=0.3198)
  Directional -> Accuracy: 0.5000, MCC: 0.1208, F1: 0.3256

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.59581 | val 2.55296
  Epoch 011 - train 0.60342 | val 2.21420
  Classification -> best τ=0.420 (val F1=0.2774)
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.60690 | val 0.72609
  Epoch 014 - train 0.58458 | val 0.64889
  Classification -> best τ=0.675 (val F1=0.4087)
  Directional -> Accuracy: 0.5893, MCC: 0.2696, F1: 0.4889

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.52384 | val 1.00712
  Epoch 011 - train 0.50358 | val 1.09426
  Classification -> best τ=0.505 (val F1=0.3116)
  Directional -> Accuracy: 0.5745, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.70049 | val 0.94494
  Epoch 017 - train 0.56788 | val 1.15578
  Classification -> best τ=0.490 (val F1=0.3385)
  Directional -> Accuracy: 0.5349, MCC: -0.1874, F1: 0.6970

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.62116 | val 0.81608
  Epoch 011 - train 0.59157 | val 0.95601
  Classification -> best τ=0.455 (val F1=0.0846)
  Directional -> Accuracy: 0.6034, MCC: 0.1882, F1: 0.7160

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.69900 | val 0.69769
  Epoch 012 - train 0.59667 | val 0.94487
  Classification -> best τ=0.480 (val F1=0.3844)
  Directional -> Accuracy: 0.5238, MCC: -0.1419, F1: 0.6875

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.55374 | val 1.47101
  Epoch 011 - train 0.53907 | val 1.24004
  Classification -> best τ=0.615 (val F1=0.1869)
  Directional -> Accuracy: 0.5227, MCC: 0.0902, F1: 0.1600

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.71978 | val 0.84175
  Epoch 011 - train 0.59725 | val 0.83655
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.58621 | val 0.86722
  Epoch 013 - train 0.55083 | val 0.84697
  Classification -> best τ=0.405 (val F1=0.2790)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.62705 | val 2.56274
  Epoch 011 - train 0.60881 | val 2.62475
  Classification -> best τ=0.455 (val F1=0.3041)
  Directional -> Accuracy: 0.5405, MCC: 0.1186, F1: 0.5143

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.63211 | val 0.82104
  Epoch 011 - train 0.57560 | val 0.81661
  Classification -> best τ=0.465 (val F1=0.3125)
  Directional -> Accuracy: 0.5789, MCC: 0.2037, F1: 0.6800

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.59002 | val 1.62702
  Epoch 011 - train 0.60237 | val 1.42799
  Classification -> best τ=0.530 (val F1=0.0449)
  Directional -> Accuracy: 0.5333, MCC: 0.0262, F1: 0.2222

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.61211 | val 0.74774
  Epoch 013 - train 0.56852 | val 0.74724
  Classification -> best τ=0.325 (val F1=0.3767)
  Directional -> Accuracy: 0.6567, MCC: 0.3626, F1: 0.6349

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.68343 | val 0.78475
  Epoch 018 - train 0.49775 | val 0.93708
  Classification -> best τ=0.440 (val F1=0.3004)
  Directional -> Accuracy: 0.4651, MCC: -0.0733, F1: 0.2069

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.61341 | val 1.07987
  Epoch 011 - train 0.60791 | val 0.80221
  Classification -> best τ=0.385 (val F1=0.1676)
  Directional -> Accuracy: 0.5439, MCC: 0.2606, F1: 0.6750

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.57982 | val 1.01420
  Epoch 011 - train 0.54211 | val 1.21476
  Classification -> best τ=0.470 (val F1=0.3893)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 16). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.52126 | val 1.61160
  Epoch 015 - train 0.55588 | val 1.26252
  Classification -> best τ=0.435 (val F1=0.4247)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.69242 | val 0.74391
  Epoch 014 - train 0.57296 | val 0.78556
  Classification -> best τ=0.430 (val F1=0.4623)
  Directional -> Accuracy: 0.4872, MCC: -0.0402, F1: 0.5455

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 16). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.60504 | val 1.54683
  Epoch 011 - train 0.59172 | val 1.68341
  Classification -> best τ=0.375 (val F1=0.3218)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.65787 | val 0.73795
  Epoch 011 - train 0.63850 | val 0.76551
  Classification -> best τ=0.475 (val F1=0.2313)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.58954 | val 1.25738
  Epoch 011 - train 0.51906 | val 1.13141
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.59499 | val 0.86725
  Epoch 012 - train 0.57932 | val 0.95722
  Classification -> best τ=0.500 (val F1=0.4921)
  Directional -> Accuracy: 0.3250, MCC: -0.2182, F1: 0.4906

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.64116 | val 1.86602
  Epoch 015 - train 0.61119 | val 1.23324
  Classification -> best τ=0.540 (val F1=0.2326)
  Directional -> Accuracy: 0.5263, MCC: 0.1993, F1: 0.2703

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.60686 | val 1.79375
  Epoch 011 - train 0.57175 | val 2.67227
  Classification -> best τ=0.665 (val F1=0.3126)
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.62171 | val 1.62377
  Epoch 011 - train 0.63433 | val 1.56290
  Classification -> best τ=0.425 (val F1=0.2184)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.64684 | val 1.93327
  Epoch 011 - train 0.60930 | val 1.81418
  Classification -> best τ=0.585 (val F1=0.2157)
  Directional -> Accuracy: 0.4912, MCC: -0.0405, F1: 0.6234

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.61960 | val 1.33558

[I 2026-02-24 23:09:27,236] Trial 43 finished with value: 0.26072844122186106 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 15, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.1, 'dropout': 0.6000000000000001, 'batch_size': 32, 'learning_rate': 0.0028937401414417356, 'weight_decay': 0.00011284722106832131, 'lr_patience': 7, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 1.3385023110596663, 'early_stopping_min_delta': 0.006286451852059952}. Best is trial 32 with value: 0.2908549754956826.

  Epoch 013 - train 0.66391 | val 2.11214
  Classification -> best τ=0.530 (val F1=0.2653)
  Directional -> Accuracy: 0.5161, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.26072844122186106
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 15
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.65415 | val 0.70268
  Epoch 020 - train 0.62096 | val 0.73110
  Classification -> best τ=0.490 (val F1=0.1565)
  Directional -> Accuracy: 0.5974, MCC: 0.1799, F1: 0.5231

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.67417 | val 0.68480
  Epoch 020 - train 0.57319 | val 0.74058
  Classification -> best τ=0.435 (val F1=0.2318)
  Directional -> Accuracy: 0.4783, MCC: -0.0156, F1: 0.4545

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 16). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.71810 | val 0.71271
  Epoch 020 - train 0.61692 | val 0.76289
  Classification -> best τ=0.535 (val F1=0.4256)
  Directional -> Accuracy: 0.5208, MCC: 0.0902, F1: 0.4103

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.69765 | val 0.71984
  Epoch 020 - train 0.65338 | val 0.69287
  Classification -> best τ=0.510 (val F1=0.2875)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.69614 | val 0.66338
  Epoch 020 - train 0.60332 | val 0.67097
  Classification -> best τ=0.470 (val F1=0.3055)
  Directional -> Accuracy: 0.5000, MCC: -0.1225, F1: 0.6579

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.68765 | val 0.71373
  Epoch 020 - train 0.64888 | val 0.69999
  Classification -> best τ=0.510 (val F1=0.1898)
  Directional -> Accuracy: 0.3958, MCC: -0.2130, F1: 0.4528

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.69656 | val 0.68693
  Epoch 020 - train 0.69146 | val 0.68901
  Classification -> best τ=0.505 (val F1=0.2957)
  Directional -> Accuracy: 0.5714, MCC: 0.1179, F1: 0.4828

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 16). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.64692 | val 1.38443
  Epoch 020 - train 0.56043 | val 1.88277
  Classification -> best τ=0.580 (val F1=0.2786)
  Directional -> Accuracy: 0.4222, MCC: -0.0842, F1: 0.5185

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.67701 | val 0.69521
  Epoch 020 - train 0.65055 | val 0.65717
  Classification -> best τ=0.600 (val F1=0.4315)
  Directional -> Accuracy: 0.5122, MCC: -0.2831, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 16). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 16). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.68777 | val 0.73138
  Epoch 020 - train 0.60205 | val 0.70547
  Classification -> best τ=0.530 (val F1=0.1258)
  Directional -> Accuracy: 0.5915, MCC: 0.1514, F1: 0.4727

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.66900 | val 0.72189
  Epoch 020 - train 0.62056 | val 0.88395
  Classification -> best τ=0.300 (val F1=0.1926)
  Directional -> Accuracy: 0.5490, MCC: 0.0982, F1: 0.1481

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.66443 | val 1.06993
  Epoch 020 - train 0.66703 | val 0.97534
  Classification -> best τ=0.415 (val F1=0.3270)
  Directional -> Accuracy: 0.5085, MCC: 0.0000, F1: 0.6742

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.62188 | val 0.79984
  Epoch 020 - train 0.55055 | val 0.69375
  Classification -> best τ=0.530 (val F1=0.3211)
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.65293 | val 0.77573
  Epoch 020 - train 0.64698 | val 0.65443
  Classification -> best τ=0.410 (val F1=0.2534)
  Directional -> Accuracy: 0.6066, MCC: 0.2730, F1: 0.7073

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.68634 | val 0.69389
  Epoch 020 - train 0.64302 | val 0.96776
  Classification -> best τ=0.500 (val F1=0.3770)
  Directional -> Accuracy: 0.6038, MCC: 0.2001, F1: 0.5333

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.67764 | val 0.91039
  Epoch 020 - train 0.60557 | val 0.95815
  Classification -> best τ=0.405 (val F1=0.2605)
  Directional -> Accuracy: 0.5857, MCC: 0.1909, F1: 0.7184

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.67232 | val 0.76629
  Epoch 020 - train 0.63900 | val 0.80220
  Classification -> best τ=0.635 (val F1=0.1796)
  Directional -> Accuracy: 0.3833, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.68220 | val 0.89518
  Epoch 020 - train 0.61500 | val 1.57756
  Classification -> best τ=0.465 (val F1=0.1242)
  Directional -> Accuracy: 0.6184, MCC: 0.1712, F1: 0.7071

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.69385 | val 0.71781
  Epoch 020 - train 0.67463 | val 0.93096
  Classification -> best τ=0.365 (val F1=0.2778)
  Directional -> Accuracy: 0.5000, MCC: 0.1525, F1: 0.3529

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 16). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.70272 | val 0.69537
  Epoch 020 - train 0.66911 | val 0.70055
  Classification -> best τ=0.415 (val F1=0.2910)
  Directional -> Accuracy: 0.4605, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.61325 | val 0.77376
  Epoch 020 - train 0.65778 | val 0.81355
  Classification -> best τ=0.350 (val F1=0.3143)
  Directional -> Accuracy: 0.6250, MCC: 0.1325, F1: 0.7353

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.69317 | val 0.70723
  Epoch 020 - train 0.65518 | val 0.75676
  Classification -> best τ=0.600 (val F1=0.2970)
  Directional -> Accuracy: 0.4545, MCC: -0.1718, F1: 0.0526

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.68127 | val 0.75194
  Epoch 020 - train 0.63888 | val 0.69359
  Classification -> best τ=0.605 (val F1=0.2892)
  Directional -> Accuracy: 0.4828, MCC: 0.0251, F1: 0.4000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.67274 | val 0.70418
  Epoch 020 - train 0.65260 | val 0.83215
  Classification -> best τ=0.575 (val F1=0.2319)
  Directional -> Accuracy: 0.5303, MCC: 0.0589, F1: 0.5079

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.70343 | val 0.67483
  Epoch 020 - train 0.68406 | val 0.64978
  Classification -> best τ=0.480 (val F1=0.5438)
  Directional -> Accuracy: 0.5714, MCC: 0.2385, F1: 0.4545

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.60474 | val 0.72526
  Epoch 020 - train 0.65486 | val 0.92137
  Classification -> best τ=0.575 (val F1=0.1792)
  Directional -> Accuracy: 0.5106, MCC: -0.0692, F1: 0.2581

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.69143 | val 0.69580
  Epoch 020 - train 0.63540 | val 0.71925
  Classification -> best τ=0.610 (val F1=0.1309)
  Directional -> Accuracy: 0.5581, MCC: 0.0852, F1: 0.6275

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.69548 | val 0.69190
  Epoch 020 - train 0.68422 | val 0.71610
  Classification -> best τ=0.485 (val F1=0.3071)
  Directional -> Accuracy: 0.5172, MCC: 0.1923, F1: 0.2632

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.79588 | val 0.74323
  Epoch 020 - train 0.66566 | val 0.69402
  Classification -> best τ=0.540 (val F1=0.4193)
  Directional -> Accuracy: 0.5000, MCC: -0.0588, F1: 0.6182

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.70734 | val 0.93988
  Epoch 020 - train 0.67283 | val 1.12345
  Classification -> best τ=0.585 (val F1=0.0309)
  Directional -> Accuracy: 0.5227, MCC: 0.1525, F1: 0.0870

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.74654 | val 0.82121
  Epoch 020 - train 0.63015 | val 0.86152
  Classification -> best τ=0.430 (val F1=0.2374)
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.68711 | val 0.71169
  Epoch 020 - train 0.57637 | val 0.73350
  Classification -> best τ=0.455 (val F1=0.2696)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.70275 | val 0.64955
  Epoch 020 - train 0.65362 | val 0.66217
  Classification -> best τ=0.405 (val F1=0.2899)
  Directional -> Accuracy: 0.5405, MCC: 0.2127, F1: 0.3929

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.81981 | val 0.73711
  Epoch 020 - train 0.60455 | val 0.69774
  Classification -> best τ=0.445 (val F1=0.3130)
  Directional -> Accuracy: 0.4474, MCC: -0.1291, F1: 0.5714

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.68855 | val 0.88279
  Epoch 020 - train 0.61707 | val 0.98098
  Classification -> best τ=0.640 (val F1=0.2306)
  Directional -> Accuracy: 0.5333, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.68206 | val 0.73098
  Epoch 020 - train 0.61485 | val 0.83493
  Classification -> best τ=0.415 (val F1=0.2409)
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.63248 | val 0.71589
  Epoch 020 - train 0.63486 | val 0.70769
  Classification -> best τ=0.495 (val F1=0.2033)
  Directional -> Accuracy: 0.6512, MCC: 0.3392, F1: 0.5714

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.63484 | val 0.71925
  Epoch 020 - train 0.60284 | val 0.69304
  Classification -> best τ=0.360 (val F1=0.1676)
  Directional -> Accuracy: 0.4561, MCC: -0.0745, F1: 0.5231

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.66308 | val 0.80019
  Epoch 020 - train 0.62126 | val 0.78595
  Classification -> best τ=0.420 (val F1=0.2718)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 16). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.72519 | val 0.77161
  Epoch 020 - train 0.65009 | val 1.02585
  Classification -> best τ=0.500 (val F1=0.3779)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.70129 | val 0.79083
  Epoch 020 - train 0.63468 | val 0.86004
  Classification -> best τ=0.400 (val F1=0.1870)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.7000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 16). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.65318 | val 0.72326
  Epoch 020 - train 0.61756 | val 0.76825
  Classification -> best τ=0.420 (val F1=0.4200)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.67235 | val 0.69359
  Epoch 020 - train 0.63391 | val 0.77918
  Classification -> best τ=0.555 (val F1=0.2544)
  Directional -> Accuracy: 0.5106, MCC: 0.0385, F1: 0.3429

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.67319 | val 0.85187
  Epoch 020 - train 0.67754 | val 0.71613
  Classification -> best τ=0.580 (val F1=0.4000)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.71242 | val 0.73026
  Epoch 020 - train 0.63992 | val 0.95815
  Classification -> best τ=0.535 (val F1=0.3647)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.71196 | val 1.07454
  Epoch 020 - train 0.65097 | val 1.05622
  Classification -> best τ=0.545 (val F1=0.2445)
  Directional -> Accuracy: 0.5614, MCC: 0.2137, F1: 0.4186

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.65188 | val 1.11560
  Epoch 020 - train 0.62163 | val 1.06868
  Classification -> best τ=0.605 (val F1=0.3957)
  Directional -> Accuracy: 0.5088, MCC: 0.0590, F1: 0.6111

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.68957 | val 0.82113
  Epoch 020 - train 0.63306 | val 0.97351
  Classification -> best τ=0.375 (val F1=0.2662)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.66565 | val 0.70055
  Epoch 020 - train 0.63674 | val 0.82846
  Classification -> best τ=0.440 (val F1=0.1518)
  Directional -> Accuracy: 0.4561, MCC: -0.1941, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.66539 | val 0.80354

[I 2026-02-24 23:10:23,804] Trial 44 finished with value: 0.27026294255932265 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 15, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 64, 'learning_rate': 0.004767802600210873, 'weight_decay': 1.4881187271299839e-05, 'lr_patience': 7, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 1.1420558729977972, 'early_stopping_min_delta': 0.002117622227046172}. Best is trial 32 with value: 0.2908549754956826.

  Epoch 020 - train 0.62208 | val 0.92895
  Classification -> best τ=0.555 (val F1=0.1507)
  Directional -> Accuracy: 0.4194, MCC: -0.1927, F1: 0.2500

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.27026294255932265
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 10
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.67552 | val 0.74533
  Epoch 020 - train 0.62535 | val 1.23057
  Classification -> best τ=0.490 (val F1=0.1403)
  Directional -> Accuracy: 0.5897, MCC: 0.1499, F1: 0.3333

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.65660 | val 0.69947
  Epoch 020 - train 0.61558 | val 0.69869
  Classification -> best τ=0.450 (val F1=0.3032)
  Directional -> Accuracy: 0.5957, MCC: 0.1692, F1: 0.7164

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 11). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.65635 | val 0.69489
  Epoch 020 - train 0.61931 | val 0.76734
  Classification -> best τ=0.635 (val F1=0.4571)
  Directional -> Accuracy: 0.5510, MCC: 0.1229, F1: 0.5000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.69520 | val 0.70270
  Epoch 020 - train 0.67711 | val 0.70123
  Classification -> best τ=0.495 (val F1=0.1770)
  Directional -> Accuracy: 0.5395, MCC: 0.0000, F1: 0.7009

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.67181 | val 0.66496
  Epoch 020 - train 0.58307 | val 0.65090
  Classification -> best τ=0.485 (val F1=0.3254)
  Directional -> Accuracy: 0.5385, MCC: 0.0661, F1: 0.5862

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.68386 | val 0.70666
  Epoch 020 - train 0.61233 | val 0.70023
  Classification -> best τ=0.475 (val F1=0.2198)
  Directional -> Accuracy: 0.5102, MCC: 0.0280, F1: 0.4286

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.70097 | val 0.69076
  Epoch 020 - train 0.70147 | val 0.70345
  Classification -> best τ=0.510 (val F1=0.2791)
  Directional -> Accuracy: 0.5211, MCC: -0.0970, F1: 0.1905

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 11). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.61512 | val 1.55622
  Epoch 020 - train 0.65380 | val 2.41796
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4130, MCC: 0.0000, F1: 0.5846

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.68898 | val 0.68369
  Epoch 020 - train 0.62481 | val 0.68311
  Classification -> best τ=0.635 (val F1=0.3873)
  Directional -> Accuracy: 0.5476, MCC: -0.2176, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for proper time series validation for BRK-A. Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for proper time series validation for BSAC. Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.66178 | val 0.75040
  Epoch 020 - train 0.60558 | val 0.86417
  Classification -> best τ=0.625 (val F1=0.1599)
  Directional -> Accuracy: 0.5775, MCC: 0.1358, F1: 0.0625

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.68726 | val 0.68303
  Epoch 020 - train 0.62231 | val 0.76745
  Classification -> best τ=0.505 (val F1=0.3840)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.66056 | val 0.86317
  Epoch 020 - train 0.64514 | val 0.96484
  Classification -> best τ=0.465 (val F1=0.1347)
  Directional -> Accuracy: 0.5932, MCC: 0.2046, F1: 0.6757

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.64275 | val 0.70164
  Epoch 020 - train 0.57151 | val 1.24140
  Classification -> best τ=0.445 (val F1=0.2750)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.67696 | val 0.67385
  Epoch 020 - train 0.62089 | val 0.70869
  Classification -> best τ=0.495 (val F1=0.3952)
  Directional -> Accuracy: 0.4839, MCC: -0.0341, F1: 0.5556

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.66408 | val 0.71069
  Epoch 020 - train 0.64981 | val 0.71434
  Classification -> best τ=0.460 (val F1=0.1183)
  Directional -> Accuracy: 0.4815, MCC: 0.0000, F1: 0.6500

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.65561 | val 0.71072
  Epoch 020 - train 0.61451 | val 0.97495
  Classification -> best τ=0.545 (val F1=0.2891)
  Directional -> Accuracy: 0.5352, MCC: 0.0677, F1: 0.5600

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.66991 | val 0.81194
  Epoch 020 - train 0.63040 | val 1.01306
  Classification -> best τ=0.685 (val F1=0.2440)
  Directional -> Accuracy: 0.3934, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.67672 | val 0.91904
  Epoch 020 - train 0.66990 | val 1.76186
  Classification -> best τ=0.470 (val F1=0.2058)
  Directional -> Accuracy: 0.5065, MCC: 0.2501, F1: 0.3448

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.70845 | val 0.68574
  Epoch 020 - train 0.62065 | val 0.72762
  Classification -> best τ=0.360 (val F1=0.2999)
  Directional -> Accuracy: 0.4030, MCC: -0.1453, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 11). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.69644 | val 0.71888
  Epoch 020 - train 0.65313 | val 0.69996
  Classification -> best τ=0.495 (val F1=0.2594)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.65560 | val 0.80041
  Epoch 020 - train 0.57326 | val 0.91496
  Classification -> best τ=0.375 (val F1=0.2715)
  Directional -> Accuracy: 0.6327, MCC: 0.0568, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.66244 | val 0.74087
  Epoch 020 - train 0.60907 | val 0.74930
  Classification -> best τ=0.550 (val F1=0.1586)
  Directional -> Accuracy: 0.4776, MCC: -0.0539, F1: 0.1463

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.67190 | val 0.70651
  Epoch 020 - train 0.63221 | val 1.17938
  Classification -> best τ=0.455 (val F1=0.2743)
  Directional -> Accuracy: 0.5932, MCC: 0.1531, F1: 0.7391

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.68128 | val 0.70671
  Epoch 020 - train 0.64934 | val 0.70481
  Classification -> best τ=0.435 (val F1=0.0648)
  Directional -> Accuracy: 0.4478, MCC: -0.1834, F1: 0.6186

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.70412 | val 0.66654
  Epoch 020 - train 0.62094 | val 1.13396
  Classification -> best τ=0.470 (val F1=0.4778)
  Directional -> Accuracy: 0.5439, MCC: 0.1963, F1: 0.4091

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.71029 | val 0.71602
  Epoch 020 - train 0.62611 | val 0.78123
  Classification -> best τ=0.545 (val F1=0.3239)
  Directional -> Accuracy: 0.4167, MCC: -0.0510, F1: 0.5625

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.66838 | val 0.68873
  Epoch 020 - train 0.62305 | val 0.70874
  Classification -> best τ=0.550 (val F1=0.1041)
  Directional -> Accuracy: 0.5682, MCC: -0.1269, F1: 0.7246

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.67037 | val 0.72143
  Epoch 020 - train 0.68172 | val 0.81993
  Classification -> best τ=0.485 (val F1=0.2518)
  Directional -> Accuracy: 0.5690, MCC: 0.2157, F1: 0.4681

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.74882 | val 0.72705
  Epoch 020 - train 0.67304 | val 0.69639
  Classification -> best τ=0.500 (val F1=0.2160)
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.63338 | val 0.74933
  Epoch 020 - train 0.64596 | val 0.87093
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.72069 | val 0.66161
  Epoch 020 - train 0.66922 | val 0.62781
  Classification -> best τ=0.715 (val F1=0.2132)
  Directional -> Accuracy: 0.4222, MCC: -0.1429, F1: 0.2353

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.68226 | val 0.66729
  Epoch 020 - train 0.59255 | val 0.94030
  Classification -> best τ=0.315 (val F1=0.3570)
  Directional -> Accuracy: 0.5192, MCC: 0.0000, F1: 0.6835

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.68658 | val 0.67461
  Epoch 020 - train 0.64595 | val 0.72024
  Classification -> best τ=0.345 (val F1=0.2759)
  Directional -> Accuracy: 0.5000, MCC: 0.0558, F1: 0.4308

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.64397 | val 0.68635
  Epoch 020 - train 0.66687 | val 0.77665
  Classification -> best τ=0.570 (val F1=0.3477)
  Directional -> Accuracy: 0.5500, MCC: 0.1746, F1: 0.6538

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.64664 | val 1.08549
  Epoch 020 - train 0.58437 | val 1.18847
  Classification -> best τ=0.615 (val F1=0.2583)
  Directional -> Accuracy: 0.5333, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.69665 | val 0.68127
  Epoch 020 - train 0.65500 | val 0.68373
  Classification -> best τ=0.350 (val F1=0.3101)
  Directional -> Accuracy: 0.5882, MCC: 0.1442, F1: 0.6585

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.67539 | val 0.71539
  Epoch 020 - train 0.63316 | val 0.71886
  Classification -> best τ=0.510 (val F1=0.2754)
  Directional -> Accuracy: 0.5909, MCC: 0.2169, F1: 0.4375

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.64745 | val 0.72365
  Epoch 020 - train 0.60492 | val 0.76592
  Classification -> best τ=0.495 (val F1=0.1687)
  Directional -> Accuracy: 0.4828, MCC: -0.0014, F1: 0.5714

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.70486 | val 0.94536
  Epoch 020 - train 0.65180 | val 1.17430
  Classification -> best τ=0.595 (val F1=0.2470)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 11). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.74039 | val 0.70078
  Epoch 020 - train 0.64190 | val 0.71742
  Classification -> best τ=0.440 (val F1=0.2911)
  Directional -> Accuracy: 0.3415, MCC: 0.0000, F1: 0.5091

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.69404 | val 0.70939
  Epoch 020 - train 0.68767 | val 0.79381
  Classification -> best τ=0.385 (val F1=0.3194)
  Directional -> Accuracy: 0.5250, MCC: 0.0000, F1: 0.6885

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 11). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.68004 | val 0.70514
  Epoch 020 - train 0.61056 | val 0.86909
  Classification -> best τ=0.400 (val F1=0.1974)
  Directional -> Accuracy: 0.5065, MCC: 0.0000, F1: 0.6724

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.63899 | val 0.89491
  Epoch 020 - train 0.58232 | val 0.76881
  Classification -> best τ=0.530 (val F1=0.3858)
  Directional -> Accuracy: 0.5417, MCC: 0.0884, F1: 0.6071

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.76424 | val 0.85680
  Epoch 020 - train 0.61076 | val 1.09047
  Classification -> best τ=0.500 (val F1=0.3730)
  Directional -> Accuracy: 0.5000, MCC: -0.0232, F1: 0.5660

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.69128 | val 1.27043
  Epoch 020 - train 0.61031 | val 1.21922
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3659, MCC: 0.0000, F1: 0.5357

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.64706 | val 0.95166
  Epoch 020 - train 0.63743 | val 1.03010
  Classification -> best τ=0.335 (val F1=0.1950)
  Directional -> Accuracy: 0.4737, MCC: -0.1672, F1: 0.6250

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.69721 | val 0.77011
  Epoch 020 - train 0.61233 | val 0.95071
  Classification -> best τ=0.440 (val F1=0.3427)
  Directional -> Accuracy: 0.4828, MCC: 0.0000, F1: 0.6512

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.68241 | val 0.92376
  Epoch 020 - train 0.62890 | val 1.03059
  Classification -> best τ=0.405 (val F1=0.1443)
  Directional -> Accuracy: 0.5636, MCC: 0.2052, F1: 0.7073

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.67988 | val 0.69050
  Epoch 020 - train 0.60322 | val 0.71439
  Classification -> best τ=0.410 (val F1=0.2033)
  Directional -> Accuracy: 0.5172, MCC: 0.0000, F1: 0.6818

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.68665 | val 0.72951

[I 2026-02-24 23:11:06,771] Trial 45 finished with value: 0.24704929571295087 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 10, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 64, 'learning_rate': 0.006380580106576205, 'weight_decay': 1.5411966407535508e-05, 'lr_patience': 7, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 1.101291029516216, 'early_stopping_min_delta': 0.0016305857933259233}. Best is trial 32 with value: 0.2908549754956826.

  Epoch 020 - train 0.64686 | val 0.78995
  Classification -> best τ=0.520 (val F1=0.2500)
  Directional -> Accuracy: 0.5714, MCC: 0.1685, F1: 0.2703

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.24704929571295087
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 15
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.68436 | val 0.70611
  Epoch 020 - train 0.65720 | val 0.75595
  Classification -> best τ=0.555 (val F1=0.2453)
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.68167 | val 0.68480
  Epoch 020 - train 0.70156 | val 0.72280
  Classification -> best τ=0.430 (val F1=0.2318)
  Directional -> Accuracy: 0.6739, MCC: 0.3279, F1: 0.7273

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 16). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.66326 | val 0.70428
  Epoch 020 - train 0.62588 | val 0.79061
  Classification -> best τ=0.445 (val F1=0.3700)
  Directional -> Accuracy: 0.5417, MCC: 0.0252, F1: 0.6857

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.64735 | val 0.72681
  Epoch 020 - train 0.67791 | val 0.76351
  Classification -> best τ=0.465 (val F1=0.1495)
  Directional -> Accuracy: 0.5733, MCC: 0.1350, F1: 0.6190

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.62584 | val 0.65576
  Epoch 020 - train 0.62703 | val 0.78683
  Classification -> best τ=0.465 (val F1=0.4428)
  Directional -> Accuracy: 0.6538, MCC: 0.2989, F1: 0.7000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.67470 | val 0.69772
  Epoch 020 - train 0.64170 | val 0.72434
  Classification -> best τ=0.485 (val F1=0.2134)
  Directional -> Accuracy: 0.4792, MCC: -0.0449, F1: 0.5614

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.68075 | val 0.68797
  Epoch 020 - train 0.67684 | val 0.71729
  Classification -> best τ=0.405 (val F1=0.2988)
  Directional -> Accuracy: 0.3857, MCC: -0.1474, F1: 0.5567

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 16). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.63893 | val 0.87108
  Epoch 020 - train 0.63626 | val 1.22392
  Classification -> best τ=0.520 (val F1=0.0434)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.66555 | val 0.70019
  Epoch 020 - train 0.63730 | val 0.72893
  Classification -> best τ=0.630 (val F1=0.5827)
  Directional -> Accuracy: 0.6098, MCC: 0.0591, F1: 0.2727

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 16). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 16). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.66768 | val 0.87023
  Epoch 020 - train 0.63478 | val 0.84029
  Classification -> best τ=0.415 (val F1=0.2602)
  Directional -> Accuracy: 0.4366, MCC: 0.0000, F1: 0.6078

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.71254 | val 0.70163
  Epoch 020 - train 0.63804 | val 0.78789
  Classification -> best τ=0.400 (val F1=0.2503)
  Directional -> Accuracy: 0.5686, MCC: 0.1243, F1: 0.4211

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.65982 | val 0.77009
  Epoch 020 - train 0.63385 | val 0.76979
  Classification -> best τ=0.485 (val F1=0.0322)
  Directional -> Accuracy: 0.5085, MCC: 0.0000, F1: 0.6742

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.64514 | val 0.68241
  Epoch 020 - train 0.62913 | val 0.78648
  Classification -> best τ=0.445 (val F1=0.2504)
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.69506 | val 0.65529
  Epoch 020 - train 0.67541 | val 0.69972
  Classification -> best τ=0.485 (val F1=0.3074)
  Directional -> Accuracy: 0.5574, MCC: 0.1602, F1: 0.6824

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.69464 | val 0.75688
  Epoch 020 - train 0.63187 | val 1.19495
  Classification -> best τ=0.575 (val F1=0.2262)
  Directional -> Accuracy: 0.5283, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.67748 | val 0.69279
  Epoch 020 - train 0.66211 | val 0.78149
  Classification -> best τ=0.325 (val F1=0.2605)
  Directional -> Accuracy: 0.5714, MCC: 0.1210, F1: 0.7000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.68373 | val 0.80477
  Epoch 020 - train 0.64769 | val 0.95818
  Classification -> best τ=0.510 (val F1=0.0689)
  Directional -> Accuracy: 0.3833, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.66727 | val 1.01512
  Epoch 020 - train 0.66982 | val 1.13488
  Classification -> best τ=0.420 (val F1=0.1208)
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.67106 | val 0.82838
  Epoch 020 - train 0.65915 | val 0.81820
  Classification -> best τ=0.325 (val F1=0.2464)
  Directional -> Accuracy: 0.5606, MCC: 0.2134, F1: 0.5085

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 16). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.67746 | val 0.67565
  Epoch 020 - train 0.62484 | val 0.67443
  Classification -> best τ=0.405 (val F1=0.2916)
  Directional -> Accuracy: 0.4868, MCC: 0.1519, F1: 0.0930

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.67806 | val 0.72467
  Epoch 020 - train 0.65960 | val 0.99054
  Classification -> best τ=0.510 (val F1=0.0969)
  Directional -> Accuracy: 0.6250, MCC: 0.2000, F1: 0.7000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.67954 | val 0.73452
  Epoch 020 - train 0.65044 | val 0.72367
  Classification -> best τ=0.505 (val F1=0.1187)
  Directional -> Accuracy: 0.5152, MCC: 0.0407, F1: 0.2727

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.70063 | val 0.68011
  Epoch 020 - train 0.63583 | val 0.70126
  Classification -> best τ=0.485 (val F1=0.3026)
  Directional -> Accuracy: 0.5517, MCC: 0.0514, F1: 0.6486

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.70790 | val 0.69646
  Epoch 020 - train 0.66419 | val 0.82053
  Classification -> best τ=0.470 (val F1=0.2453)
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.65757 | val 0.63630
  Epoch 020 - train 0.63364 | val 0.63044
  Classification -> best τ=0.535 (val F1=0.4863)
  Directional -> Accuracy: 0.5536, MCC: 0.2064, F1: 0.4186

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.72388 | val 0.70063
  Epoch 020 - train 0.66639 | val 0.71488
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4255, MCC: 0.0000, F1: 0.5970

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.68451 | val 0.69302
  Epoch 020 - train 0.66676 | val 0.73262
  Classification -> best τ=0.525 (val F1=0.2643)
  Directional -> Accuracy: 0.6047, MCC: 0.1508, F1: 0.7018

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.67946 | val 0.68004
  Epoch 020 - train 0.66913 | val 0.74114
  Classification -> best τ=0.375 (val F1=0.2435)
  Directional -> Accuracy: 0.6207, MCC: 0.2243, F1: 0.7179

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.66090 | val 0.68670
  Epoch 020 - train 0.64329 | val 0.70780
  Classification -> best τ=0.575 (val F1=0.4193)
  Directional -> Accuracy: 0.5714, MCC: 0.1276, F1: 0.6250

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.67362 | val 0.76360
  Epoch 020 - train 0.65847 | val 1.01772
  Classification -> best τ=0.515 (val F1=0.1869)
  Directional -> Accuracy: 0.5455, MCC: 0.2182, F1: 0.1667

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.65962 | val 0.74155
  Epoch 020 - train 0.63000 | val 0.81561
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.63866 | val 0.68118
  Epoch 020 - train 0.66980 | val 0.74166
  Classification -> best τ=0.485 (val F1=0.2240)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.66850 | val 0.69071
  Epoch 020 - train 0.63978 | val 0.72529
  Classification -> best τ=0.590 (val F1=0.3351)
  Directional -> Accuracy: 0.5405, MCC: 0.1627, F1: 0.4516

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.70671 | val 0.69542
  Epoch 020 - train 0.66599 | val 0.69543
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.66590 | val 0.75343
  Epoch 020 - train 0.68271 | val 0.80959
  Classification -> best τ=0.485 (val F1=0.3091)
  Directional -> Accuracy: 0.4889, MCC: 0.1410, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.66678 | val 0.70862
  Epoch 020 - train 0.64784 | val 0.72682
  Classification -> best τ=0.455 (val F1=0.3767)
  Directional -> Accuracy: 0.4925, MCC: 0.1685, F1: 0.2273

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.70221 | val 0.69085
  Epoch 020 - train 0.66814 | val 0.68618
  Classification -> best τ=0.475 (val F1=0.3311)
  Directional -> Accuracy: 0.5116, MCC: 0.0641, F1: 0.2222

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.65076 | val 0.79453
  Epoch 020 - train 0.61809 | val 1.16916
  Classification -> best τ=0.500 (val F1=0.1590)
  Directional -> Accuracy: 0.5088, MCC: 0.0223, F1: 0.5172

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.64655 | val 0.77448
  Epoch 020 - train 0.62597 | val 1.06762
  Classification -> best τ=0.500 (val F1=0.4096)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 16). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.67037 | val 0.68922
  Epoch 020 - train 0.61491 | val 0.87279
  Classification -> best τ=0.465 (val F1=0.3410)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.68897 | val 0.73696
  Epoch 020 - train 0.66899 | val 0.83979
  Classification -> best τ=0.515 (val F1=0.1870)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.7000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 16). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.64269 | val 0.71270
  Epoch 020 - train 0.63801 | val 0.93029
  Classification -> best τ=0.405 (val F1=0.3424)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.68567 | val 0.71621
  Epoch 020 - train 0.70336 | val 0.67975
  Classification -> best τ=0.505 (val F1=0.4151)
  Directional -> Accuracy: 0.5319, MCC: 0.0926, F1: 0.6765

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.69741 | val 0.68285
  Epoch 020 - train 0.59981 | val 0.71955
  Classification -> best τ=0.475 (val F1=0.4719)
  Directional -> Accuracy: 0.5778, MCC: 0.1700, F1: 0.5778

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.69853 | val 0.72661
  Epoch 020 - train 0.65765 | val 0.82440
  Classification -> best τ=0.500 (val F1=0.2277)
  Directional -> Accuracy: 0.6500, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.68144 | val 0.73569
  Epoch 020 - train 0.64690 | val 0.93539
  Classification -> best τ=0.505 (val F1=0.0767)
  Directional -> Accuracy: 0.3509, MCC: -0.3225, F1: 0.4308

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.66670 | val 0.74451
  Epoch 020 - train 0.64940 | val 0.90883
  Classification -> best τ=0.495 (val F1=0.2554)
  Directional -> Accuracy: 0.5088, MCC: 0.1231, F1: 0.6500

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.67218 | val 0.94433
  Epoch 020 - train 0.65206 | val 1.09295
  Classification -> best τ=0.450 (val F1=0.2257)
  Directional -> Accuracy: 0.5741, MCC: 0.1798, F1: 0.6933

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.68592 | val 0.74157
  Epoch 020 - train 0.63658 | val 0.90719
  Classification -> best τ=0.480 (val F1=0.1450)
  Directional -> Accuracy: 0.5614, MCC: 0.2399, F1: 0.6988

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.68538 | val 0.79018

[I 2026-02-24 23:12:02,750] Trial 46 finished with value: 0.24323003417006728 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 15, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 64, 'learning_rate': 0.0005844657901034164, 'weight_decay': 7.505170090509324e-05, 'lr_patience': 7, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 1.159387828985432, 'early_stopping_min_delta': 0.0033670243738154765}. Best is trial 32 with value: 0.2908549754956826.

  Epoch 020 - train 0.64963 | val 0.95084
  Classification -> best τ=0.495 (val F1=0.0732)
  Directional -> Accuracy: 0.5000, MCC: -0.1240, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.24323003417006728
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 15
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.68378 | val 0.71807
  Epoch 020 - train 0.66465 | val 0.69588
  Epoch 030 - train 0.65940 | val 0.71363
  Epoch 036 - train 0.62920 | val 0.72080
  Classification -> best τ=0.525 (val F1=0.1135)
  Directional -> Accuracy: 0.6104, MCC: 0.2108, F1: 0.5588

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.64632 | val 0.70728
  Epoch 020 - train 0.62614 | val 0.68410
  Epoch 030 - train 0.61349 | val 0.68447
  Epoch 037 - train 0.60417 | val 0.68435
  Classification -> best τ=0.455 (val F1=0.2252)
  Directional -> Accuracy: 0.6087, MCC: 0.1761, F1: 0.7188

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 16). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.68173 | val 0.71380
  Epoch 020 - train 0.70173 | val 0.70618
  Epoch 021 - train 0.67680 | val 0.70676
  Classification -> best τ=0.495 (val F1=0.4191)
  Directional -> Accuracy: 0.4583, MCC: -0.0769, F1: 0.4583

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.69058 | val 0.69240
  Epoch 020 - train 0.67796 | val 0.70020
  Epoch 022 - train 0.66963 | val 0.69624
  Classification -> best τ=0.480 (val F1=0.0784)
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.65242 | val 0.67618
  Epoch 020 - train 0.70524 | val 0.67052
  Epoch 030 - train 0.61363 | val 0.76987
  Epoch 033 - train 0.58620 | val 0.80286
  Classification -> best τ=0.460 (val F1=0.4631)
  Directional -> Accuracy: 0.5000, MCC: -0.0493, F1: 0.6176

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.66501 | val 0.71320
  Epoch 020 - train 0.65619 | val 0.71854
  Epoch 021 - train 0.63106 | val 0.71884
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.70440 | val 0.70034
  Epoch 020 - train 0.69394 | val 0.68998
  Epoch 024 - train 0.69956 | val 0.69240
  Classification -> best τ=0.510 (val F1=0.2576)
  Directional -> Accuracy: 0.4857, MCC: 0.0503, F1: 0.5263

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 16). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.64762 | val 1.06700
  Epoch 020 - train 0.59684 | val 1.10798
  Epoch 021 - train 0.60010 | val 1.10614
  Classification -> best τ=0.485 (val F1=0.2229)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.64743 | val 0.69796
  Epoch 020 - train 0.66391 | val 0.68522
  Epoch 030 - train 0.60940 | val 0.70818
  Epoch 040 - train 0.61971 | val 0.70708
  Epoch 041 - train 0.60917 | val 0.70687
  Classification -> best τ=0.575 (val F1=0.3624)
  Directional -> Accuracy: 0.5854, MCC: -0.0791, F1: 0.1053

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 16). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 16). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.66757 | val 0.70875
  Epoch 020 - train 0.63124 | val 0.71719
  Epoch 023 - train 0.62707 | val 0.71150
  Classification -> best τ=0.580 (val F1=0.1114)
  Directional -> Accuracy: 0.5070, MCC: -0.0131, F1: 0.4068

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.66051 | val 0.67234
  Epoch 020 - train 0.60065 | val 0.84147
  Epoch 029 - train 0.62544 | val 0.92141
  Classification -> best τ=0.365 (val F1=0.1557)
  Directional -> Accuracy: 0.5098, MCC: 0.0185, F1: 0.4898

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.69061 | val 0.80419
  Epoch 020 - train 0.65068 | val 0.81338
  Epoch 021 - train 0.62930 | val 0.81470
  Classification -> best τ=0.390 (val F1=0.1479)
  Directional -> Accuracy: 0.5085, MCC: 0.0000, F1: 0.6742

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.62745 | val 0.74091
  Epoch 020 - train 0.57375 | val 0.98365
  Epoch 027 - train 0.55939 | val 1.15226
  Classification -> best τ=0.445 (val F1=0.2869)
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.67764 | val 0.68441
  Epoch 020 - train 0.66250 | val 0.67723
  Epoch 022 - train 0.66209 | val 0.68546
  Classification -> best τ=0.470 (val F1=0.3074)
  Directional -> Accuracy: 0.4918, MCC: -0.0226, F1: 0.5634

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.68842 | val 0.68779
  Epoch 020 - train 0.65420 | val 0.70625
  Epoch 025 - train 0.62697 | val 0.70052
  Classification -> best τ=0.465 (val F1=0.1150)
  Directional -> Accuracy: 0.5283, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.66758 | val 0.76416
  Epoch 020 - train 0.62741 | val 0.75304
  Epoch 023 - train 0.63606 | val 0.77040
  Classification -> best τ=0.695 (val F1=0.3393)
  Directional -> Accuracy: 0.4714, MCC: -0.0100, F1: 0.3019

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.67671 | val 0.73390
  Epoch 020 - train 0.67740 | val 0.76009
  Epoch 029 - train 0.63965 | val 0.80718
  Classification -> best τ=0.670 (val F1=0.2112)
  Directional -> Accuracy: 0.3833, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.68168 | val 0.73579
  Epoch 020 - train 0.65162 | val 0.81229
  Epoch 024 - train 0.67212 | val 0.81684
  Classification -> best τ=0.480 (val F1=0.1610)
  Directional -> Accuracy: 0.6184, MCC: 0.2260, F1: 0.6667

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.67076 | val 0.71316
  Epoch 020 - train 0.67224 | val 0.73784
  Epoch 023 - train 0.65025 | val 0.74642
  Classification -> best τ=0.555 (val F1=0.1279)
  Directional -> Accuracy: 0.4545, MCC: 0.0612, F1: 0.2500

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 16). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.67322 | val 0.67809
  Epoch 020 - train 0.66365 | val 0.67914
  Epoch 030 - train 0.63072 | val 0.68338
  Epoch 035 - train 0.59907 | val 0.67957
  Classification -> best τ=0.520 (val F1=0.3043)
  Directional -> Accuracy: 0.4605, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.69954 | val 0.72056
  Epoch 020 - train 0.63938 | val 0.73565
  Epoch 022 - train 0.68099 | val 0.74415
  Classification -> best τ=0.460 (val F1=0.1906)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.66564 | val 0.76822
  Epoch 020 - train 0.68326 | val 0.77656
  Epoch 021 - train 0.67703 | val 0.77832
  Classification -> best τ=0.470 (val F1=0.0913)
  Directional -> Accuracy: 0.6061, MCC: 0.2137, F1: 0.6286

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.68224 | val 0.69455
  Epoch 020 - train 0.65229 | val 0.68642
  Epoch 022 - train 0.67954 | val 0.68313
  Classification -> best τ=0.520 (val F1=0.2966)
  Directional -> Accuracy: 0.6034, MCC: 0.1806, F1: 0.6667

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.67137 | val 0.69913
  Epoch 020 - train 0.66811 | val 0.69342
  Epoch 024 - train 0.65376 | val 0.69304
  Classification -> best τ=0.490 (val F1=0.1318)
  Directional -> Accuracy: 0.5455, MCC: 0.0747, F1: 0.1667

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.66856 | val 0.66621
  Epoch 020 - train 0.63337 | val 0.66394
  Epoch 027 - train 0.58152 | val 0.67885
  Classification -> best τ=0.480 (val F1=0.3976)
  Directional -> Accuracy: 0.5536, MCC: 0.1867, F1: 0.4444

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.67270 | val 0.75653
  Epoch 020 - train 0.66780 | val 0.90683
  Epoch 021 - train 0.60284 | val 0.90593
  Classification -> best τ=0.540 (val F1=0.2067)
  Directional -> Accuracy: 0.4468, MCC: 0.0178, F1: 0.5806

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.67683 | val 0.68008
  Epoch 020 - train 0.67412 | val 0.68083
  Epoch 024 - train 0.63784 | val 0.68142
  Classification -> best τ=0.585 (val F1=0.1874)
  Directional -> Accuracy: 0.5116, MCC: 0.0866, F1: 0.4615

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.69794 | val 0.67617
  Epoch 020 - train 0.65113 | val 0.68559
  Epoch 027 - train 0.65613 | val 0.68067
  Classification -> best τ=0.420 (val F1=0.3385)
  Directional -> Accuracy: 0.5517, MCC: 0.0642, F1: 0.6486

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.69742 | val 0.73065
  Epoch 020 - train 0.68083 | val 0.74318
  Epoch 021 - train 0.68753 | val 0.74372
  Classification -> best τ=0.460 (val F1=0.2425)
  Directional -> Accuracy: 0.5714, MCC: 0.1350, F1: 0.6087

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.70554 | val 0.84842
  Epoch 020 - train 0.66422 | val 1.10402
  Epoch 021 - train 0.67675 | val 1.11594
  Classification -> best τ=0.625 (val F1=0.1869)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.2667

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.68801 | val 0.71201
  Epoch 020 - train 0.66573 | val 0.83217
  Epoch 025 - train 0.66247 | val 0.81380
  Classification -> best τ=0.490 (val F1=0.0815)
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.67923 | val 0.65919
  Epoch 020 - train 0.63419 | val 0.70390
  Epoch 029 - train 0.58254 | val 0.74241
  Classification -> best τ=0.370 (val F1=0.2965)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.67061 | val 0.67263
  Epoch 020 - train 0.66115 | val 0.76674
  Epoch 023 - train 0.62003 | val 0.76287
  Classification -> best τ=0.390 (val F1=0.3121)
  Directional -> Accuracy: 0.5541, MCC: 0.2008, F1: 0.4590

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.60605 | val 0.69296
  Epoch 020 - train 0.60891 | val 0.69317
  Epoch 022 - train 0.63720 | val 0.69330
  Classification -> best τ=0.485 (val F1=0.3024)
  Directional -> Accuracy: 0.4737, MCC: -0.0619, F1: 0.5833

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.66634 | val 0.72295
  Epoch 020 - train 0.64025 | val 0.76572
  Epoch 021 - train 0.64786 | val 0.76768
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.6364

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.66287 | val 0.86512
  Epoch 020 - train 0.63200 | val 0.88550
  Epoch 025 - train 0.59092 | val 0.87151
  Classification -> best τ=0.390 (val F1=0.3767)
  Directional -> Accuracy: 0.5672, MCC: 0.1650, F1: 0.5538

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.66649 | val 0.71303
  Epoch 020 - train 0.70301 | val 0.69729
  Epoch 030 - train 0.63643 | val 0.69234
  Epoch 040 - train 0.62003 | val 0.69911
  Epoch 048 - train 0.62996 | val 0.69996
  Classification -> best τ=0.500 (val F1=0.1995)
  Directional -> Accuracy: 0.7442, MCC: 0.5199, F1: 0.7027

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.66714 | val 0.68008
  Epoch 020 - train 0.64020 | val 0.71511
  Epoch 025 - train 0.62173 | val 0.70753
  Classification -> best τ=0.450 (val F1=0.2402)
  Directional -> Accuracy: 0.5789, MCC: 0.1910, F1: 0.6364

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.69459 | val 0.72252
  Epoch 020 - train 0.63392 | val 0.77267
  Epoch 022 - train 0.65299 | val 0.76208
  Classification -> best τ=0.460 (val F1=0.3014)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 16). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.67056 | val 0.84278
  Epoch 020 - train 0.65542 | val 1.06866
  Epoch 021 - train 0.64619 | val 1.07359
  Classification -> best τ=0.575 (val F1=0.3779)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.65447 | val 0.81803
  Epoch 020 - train 0.66682 | val 0.80981
  Epoch 021 - train 0.67003 | val 0.80742
  Classification -> best τ=0.395 (val F1=0.1870)
  Directional -> Accuracy: 0.4872, MCC: -0.1435, F1: 0.6429

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 16). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.69670 | val 0.69888
  Epoch 020 - train 0.64946 | val 0.70325
  Epoch 022 - train 0.64498 | val 0.70401
  Classification -> best τ=0.545 (val F1=0.2327)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.66353 | val 0.69843
  Epoch 020 - train 0.60633 | val 0.69439
  Epoch 021 - train 0.65838 | val 0.69422
  Classification -> best τ=0.475 (val F1=0.5060)
  Directional -> Accuracy: 0.4894, MCC: -0.0183, F1: 0.4545

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.62769 | val 0.92101
  Epoch 020 - train 0.62032 | val 1.02483
  Epoch 021 - train 0.57028 | val 1.02662
  Classification -> best τ=0.560 (val F1=0.2774)
  Directional -> Accuracy: 0.4222, MCC: -0.1685, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.66771 | val 0.72126
  Epoch 020 - train 0.71776 | val 0.77409
  Epoch 027 - train 0.66723 | val 0.79561
  Classification -> best τ=0.430 (val F1=0.3647)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.68200 | val 0.88459
  Epoch 020 - train 0.65781 | val 0.90430
  Epoch 023 - train 0.63464 | val 0.92883
  Classification -> best τ=0.440 (val F1=0.2145)

[I 2026-02-24 23:13:35,190] Trial 47 finished with value: 0.2398252997780088 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 15, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.1, 'dropout': 0.8, 'batch_size': 64, 'learning_rate': 0.005832780089040316, 'weight_decay': 0.00020504686803379481, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 50, 'huber_delta': 0.9878748136027157, 'early_stopping_min_delta': 0.0010635916145000119}. Best is trial 32 with value: 0.2908549754956826.

  Epoch 026 - train 0.62667 | val 0.85354
  Classification -> best τ=0.525 (val F1=0.2509)
  Directional -> Accuracy: 0.5645, MCC: 0.2868, F1: 0.6897

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2398252997780088
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 10
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.61854 | val 0.73822
  Epoch 020 - train 0.59220 | val 1.40588
  Classification -> best τ=0.555 (val F1=0.2463)
  Directional -> Accuracy: 0.5513, MCC: 0.0482, F1: 0.2857

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.65619 | val 0.70668
  Epoch 020 - train 0.58085 | val 0.70997
  Classification -> best τ=0.465 (val F1=0.2346)
  Directional -> Accuracy: 0.5532, MCC: 0.0000, F1: 0.7123

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 11). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.65109 | val 0.75773
  Epoch 020 - train 0.60226 | val 0.89080
  Classification -> best τ=0.420 (val F1=0.3574)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.67229 | val 0.90865
  Epoch 020 - train 0.62848 | val 0.89858
  Classification -> best τ=0.445 (val F1=0.0336)
  Directional -> Accuracy: 0.5789, MCC: 0.1384, F1: 0.6596

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.59837 | val 0.68216
  Epoch 020 - train 0.56755 | val 0.74470
  Classification -> best τ=0.485 (val F1=0.3666)
  Directional -> Accuracy: 0.4808, MCC: -0.0786, F1: 0.5846

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.60356 | val 0.74714
  Epoch 020 - train 0.52731 | val 0.75908
  Classification -> best τ=0.535 (val F1=0.2511)
  Directional -> Accuracy: 0.5306, MCC: 0.1169, F1: 0.2581

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.66302 | val 0.68198
  Epoch 020 - train 0.62918 | val 0.79449
  Classification -> best τ=0.385 (val F1=0.2343)
  Directional -> Accuracy: 0.4085, MCC: 0.0000, F1: 0.5800

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 11). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.58204 | val 1.01421
  Epoch 020 - train 0.53827 | val 1.65532
  Classification -> best τ=0.540 (val F1=0.0904)
  Directional -> Accuracy: 0.6304, MCC: 0.2217, F1: 0.5143

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.62336 | val 0.82123
  Epoch 020 - train 0.61147 | val 1.02053
  Classification -> best τ=0.560 (val F1=0.3364)
  Directional -> Accuracy: 0.5952, MCC: 0.0683, F1: 0.3200

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for proper time series validation for BRK-A. Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for proper time series validation for BSAC. Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.62955 | val 0.88159
  Epoch 020 - train 0.56140 | val 0.91628
  Classification -> best τ=0.455 (val F1=0.1703)
  Directional -> Accuracy: 0.5211, MCC: 0.0408, F1: 0.4848

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.62729 | val 0.67888
  Epoch 020 - train 0.56852 | val 0.75109
  Classification -> best τ=0.470 (val F1=0.2430)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.64748 | val 0.81644
  Epoch 020 - train 0.54356 | val 1.12754
  Classification -> best τ=0.420 (val F1=0.1504)
  Directional -> Accuracy: 0.5424, MCC: 0.1905, F1: 0.6897

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.61523 | val 0.72073
  Epoch 020 - train 0.58109 | val 1.00899
  Classification -> best τ=0.470 (val F1=0.2750)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.64835 | val 0.64497
  Epoch 020 - train 0.58472 | val 0.76842
  Classification -> best τ=0.460 (val F1=0.2853)
  Directional -> Accuracy: 0.5806, MCC: 0.2289, F1: 0.6905

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.60072 | val 0.67736
  Epoch 020 - train 0.55256 | val 1.05389
  Classification -> best τ=0.475 (val F1=0.3450)
  Directional -> Accuracy: 0.4630, MCC: -0.0648, F1: 0.5797

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.62832 | val 0.73265
  Epoch 020 - train 0.56110 | val 0.78931
  Classification -> best τ=0.605 (val F1=0.3398)
  Directional -> Accuracy: 0.5352, MCC: 0.1649, F1: 0.3265

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.64533 | val 0.99836
  Epoch 020 - train 0.59202 | val 1.19826
  Classification -> best τ=0.545 (val F1=0.1553)
  Directional -> Accuracy: 0.3934, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.64262 | val 1.04751
  Epoch 020 - train 0.60084 | val 1.22406
  Classification -> best τ=0.480 (val F1=0.1128)
  Directional -> Accuracy: 0.5195, MCC: 0.2123, F1: 0.4127

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.63689 | val 0.68544
  Epoch 020 - train 0.56474 | val 0.96627
  Classification -> best τ=0.405 (val F1=0.2715)
  Directional -> Accuracy: 0.4627, MCC: 0.0915, F1: 0.2174

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 11). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.62730 | val 0.66095
  Epoch 020 - train 0.56928 | val 0.70596
  Classification -> best τ=0.415 (val F1=0.3328)
  Directional -> Accuracy: 0.4675, MCC: 0.0490, F1: 0.0889

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.61635 | val 0.74265
  Epoch 020 - train 0.54568 | val 1.11345
  Classification -> best τ=0.450 (val F1=0.1535)
  Directional -> Accuracy: 0.7143, MCC: 0.3506, F1: 0.8056

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.64681 | val 0.74467
  Epoch 020 - train 0.58825 | val 0.73229
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5075, MCC: 0.0000, F1: 0.6733

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.65064 | val 0.82959
  Epoch 020 - train 0.61361 | val 0.89346
  Classification -> best τ=0.590 (val F1=0.2651)
  Directional -> Accuracy: 0.4576, MCC: 0.1606, F1: 0.1111

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.64392 | val 0.71203
  Epoch 020 - train 0.56872 | val 0.79311
  Classification -> best τ=0.475 (val F1=0.1389)
  Directional -> Accuracy: 0.4478, MCC: -0.1087, F1: 0.5934

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.59606 | val 0.68985
  Epoch 020 - train 0.56713 | val 0.81356
  Classification -> best τ=0.495 (val F1=0.5217)
  Directional -> Accuracy: 0.5439, MCC: 0.1313, F1: 0.5000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.57923 | val 0.71299
  Epoch 020 - train 0.60028 | val 0.81252
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4167, MCC: 0.0000, F1: 0.5882

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.65865 | val 0.96659
  Epoch 020 - train 0.58230 | val 0.94472
  Classification -> best τ=0.490 (val F1=0.1749)
  Directional -> Accuracy: 0.6136, MCC: 0.1833, F1: 0.7536

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.64223 | val 0.73305
  Epoch 020 - train 0.59510 | val 1.08478
  Classification -> best τ=0.510 (val F1=0.2054)
  Directional -> Accuracy: 0.5345, MCC: 0.1948, F1: 0.3415

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.66277 | val 0.67622
  Epoch 020 - train 0.53210 | val 0.65901
  Classification -> best τ=0.645 (val F1=0.3948)
  Directional -> Accuracy: 0.5349, MCC: 0.0786, F1: 0.5238

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.61425 | val 0.76188
  Epoch 020 - train 0.57292 | val 0.98752
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.63873 | val 0.74465
  Epoch 020 - train 0.56571 | val 0.81385
  Classification -> best τ=0.440 (val F1=0.2272)
  Directional -> Accuracy: 0.5333, MCC: 0.0000, F1: 0.6957

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.63685 | val 0.64766
  Epoch 020 - train 0.54464 | val 0.81421
  Classification -> best τ=0.390 (val F1=0.3631)
  Directional -> Accuracy: 0.5192, MCC: 0.0000, F1: 0.6835

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.63981 | val 0.64218
  Epoch 020 - train 0.57593 | val 0.67797
  Classification -> best τ=0.555 (val F1=0.3620)
  Directional -> Accuracy: 0.5000, MCC: 0.1009, F1: 0.3509

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.69756 | val 0.69468
  Epoch 020 - train 0.62594 | val 0.76353
  Classification -> best τ=0.520 (val F1=0.3287)
  Directional -> Accuracy: 0.4750, MCC: 0.0000, F1: 0.6441

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.61631 | val 0.78736
  Epoch 020 - train 0.57810 | val 0.91078
  Classification -> best τ=0.530 (val F1=0.1552)
  Directional -> Accuracy: 0.4889, MCC: -0.0061, F1: 0.5306

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.64701 | val 0.74186
  Epoch 020 - train 0.60858 | val 0.83881
  Classification -> best τ=0.470 (val F1=0.2989)
  Directional -> Accuracy: 0.6324, MCC: 0.2985, F1: 0.6269

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.66548 | val 0.68350
  Epoch 020 - train 0.60931 | val 0.74922
  Classification -> best τ=0.450 (val F1=0.2651)
  Directional -> Accuracy: 0.7727, MCC: 0.5455, F1: 0.7727

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.61634 | val 0.74870
  Epoch 020 - train 0.59432 | val 0.90809
  Classification -> best τ=0.505 (val F1=0.1687)
  Directional -> Accuracy: 0.4310, MCC: -0.1318, F1: 0.4407

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.60008 | val 1.37565
  Epoch 020 - train 0.54299 | val 2.27289
  Classification -> best τ=0.580 (val F1=0.1760)
  Directional -> Accuracy: 0.3958, MCC: 0.0222, F1: 0.1212

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 11). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.66543 | val 0.65400
  Epoch 020 - train 0.56098 | val 0.73660
  Classification -> best τ=0.315 (val F1=0.4326)
  Directional -> Accuracy: 0.3415, MCC: 0.0000, F1: 0.5091

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.67705 | val 0.71433
  Epoch 020 - train 0.64963 | val 0.79897
  Classification -> best τ=0.495 (val F1=0.0510)
  Directional -> Accuracy: 0.4250, MCC: -0.1732, F1: 0.5106

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 11). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.65518 | val 1.05525
  Epoch 020 - train 0.56669 | val 1.70272
  Classification -> best τ=0.440 (val F1=0.4172)
  Directional -> Accuracy: 0.5065, MCC: 0.0000, F1: 0.6724

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.59843 | val 0.74081
  Epoch 020 - train 0.61021 | val 1.42433
  Classification -> best τ=0.605 (val F1=0.3712)
  Directional -> Accuracy: 0.5625, MCC: 0.1278, F1: 0.6038

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.64919 | val 0.78460
  Epoch 020 - train 0.59612 | val 0.97041
  Classification -> best τ=0.515 (val F1=0.0725)
  Directional -> Accuracy: 0.4783, MCC: 0.0217, F1: 0.3684

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.59868 | val 0.96944
  Epoch 020 - train 0.51498 | val 1.20644
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3659, MCC: 0.0000, F1: 0.5357

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.63669 | val 0.87036
  Epoch 020 - train 0.58869 | val 0.97960
  Classification -> best τ=0.455 (val F1=0.1634)
  Directional -> Accuracy: 0.6667, MCC: 0.3437, F1: 0.6667

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.64001 | val 1.01817
  Epoch 020 - train 0.58664 | val 1.26538
  Classification -> best τ=0.525 (val F1=0.3363)
  Directional -> Accuracy: 0.5000, MCC: 0.1280, F1: 0.6588

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.63306 | val 0.95796
  Epoch 020 - train 0.61831 | val 1.25243
  Classification -> best τ=0.410 (val F1=0.2208)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.63759 | val 0.83264
  Epoch 020 - train 0.58288 | val 0.97735
  Classification -> best τ=0.520 (val F1=0.1089)
  Directional -> Accuracy: 0.5517, MCC: 0.1956, F1: 0.6977

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.62689 | val 0.75719

[I 2026-02-24 23:14:16,503] Trial 48 finished with value: 0.22904430136142953 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 10, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.6000000000000001, 'batch_size': 64, 'learning_rate': 0.0017859754927726916, 'weight_decay': 3.162795756501061e-05, 'lr_patience': 7, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.703901946460354, 'early_stopping_min_delta': 0.00514149222203932}. Best is trial 32 with value: 0.2908549754956826.

  Epoch 020 - train 0.59139 | val 0.68306
  Classification -> best τ=0.530 (val F1=0.2475)
  Directional -> Accuracy: 0.5238, MCC: 0.0086, F1: 0.0625

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.22904430136142953
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 15
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.66603 | val 0.74734
  Epoch 020 - train 0.58718 | val 1.00065
  Classification -> best τ=0.530 (val F1=0.2851)
  Directional -> Accuracy: 0.5584, MCC: 0.1257, F1: 0.0556

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.61966 | val 0.67751
  Epoch 020 - train 0.59072 | val 0.68977
  Classification -> best τ=0.450 (val F1=0.3081)
  Directional -> Accuracy: 0.5652, MCC: 0.0280, F1: 0.7143

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 16). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.63168 | val 0.70699
  Epoch 020 - train 0.60489 | val 0.74138
  Classification -> best τ=0.605 (val F1=0.2892)
  Directional -> Accuracy: 0.4583, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.67459 | val 0.72959
  Epoch 020 - train 0.62513 | val 0.80391
  Classification -> best τ=0.535 (val F1=0.0144)
  Directional -> Accuracy: 0.5333, MCC: -0.1059, F1: 0.6957

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.63179 | val 0.70793
  Epoch 020 - train 0.51545 | val 0.78649
  Classification -> best τ=0.480 (val F1=0.3847)
  Directional -> Accuracy: 0.5192, MCC: -0.0636, F1: 0.6753

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.64701 | val 0.69374
  Epoch 020 - train 0.60027 | val 0.71233
  Classification -> best τ=0.475 (val F1=0.3254)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.5200

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.67781 | val 0.67810
  Epoch 020 - train 0.63507 | val 0.69257
  Classification -> best τ=0.490 (val F1=0.3441)
  Directional -> Accuracy: 0.4857, MCC: 0.0503, F1: 0.5263

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 16). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.58301 | val 1.05955
  Epoch 020 - train 0.51958 | val 1.84785
  Classification -> best τ=0.540 (val F1=0.2229)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.65995 | val 0.65395
  Epoch 020 - train 0.56373 | val 0.97937
  Classification -> best τ=0.455 (val F1=0.3708)
  Directional -> Accuracy: 0.5366, MCC: 0.2805, F1: 0.5957

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 16). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 16). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.64433 | val 0.84821
  Epoch 020 - train 0.57286 | val 0.72078
  Classification -> best τ=0.595 (val F1=0.1649)
  Directional -> Accuracy: 0.5211, MCC: -0.0382, F1: 0.2609

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.63978 | val 0.86310
  Epoch 020 - train 0.56440 | val 0.84068
  Classification -> best τ=0.430 (val F1=0.1763)
  Directional -> Accuracy: 0.5294, MCC: 0.0172, F1: 0.1429

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.60740 | val 0.90848
  Epoch 020 - train 0.55634 | val 1.05195
  Classification -> best τ=0.405 (val F1=0.2298)
  Directional -> Accuracy: 0.5085, MCC: 0.0000, F1: 0.6742

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.59385 | val 0.73093
  Epoch 020 - train 0.55655 | val 1.18228
  Classification -> best τ=0.570 (val F1=0.1711)
  Directional -> Accuracy: 0.5581, MCC: 0.0259, F1: 0.0952

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.64722 | val 0.61789
  Epoch 020 - train 0.58331 | val 0.67532
  Classification -> best τ=0.255 (val F1=0.3336)
  Directional -> Accuracy: 0.5738, MCC: 0.2007, F1: 0.6905

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.63080 | val 0.83240
  Epoch 020 - train 0.57620 | val 1.57602
  Classification -> best τ=0.505 (val F1=0.2069)
  Directional -> Accuracy: 0.5849, MCC: 0.1671, F1: 0.5600

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.66223 | val 0.80095
  Epoch 020 - train 0.58093 | val 0.87858
  Classification -> best τ=0.460 (val F1=0.4341)
  Directional -> Accuracy: 0.5857, MCC: 0.1502, F1: 0.6667

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.63825 | val 0.96825
  Epoch 020 - train 0.61805 | val 1.13948
  Classification -> best τ=0.485 (val F1=0.0607)
  Directional -> Accuracy: 0.6000, MCC: 0.0338, F1: 0.7333

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.64220 | val 0.86858
  Epoch 020 - train 0.61971 | val 1.18679
  Classification -> best τ=0.405 (val F1=0.1826)
  Directional -> Accuracy: 0.4474, MCC: -0.0064, F1: 0.3636

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.63214 | val 0.89968
  Epoch 020 - train 0.56848 | val 1.00317
  Classification -> best τ=0.320 (val F1=0.3603)
  Directional -> Accuracy: 0.4848, MCC: 0.1021, F1: 0.3462

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 16). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.63197 | val 0.69881
  Epoch 020 - train 0.55028 | val 0.77194
  Classification -> best τ=0.500 (val F1=0.2950)
  Directional -> Accuracy: 0.4605, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.64302 | val 1.04064
  Epoch 020 - train 0.56058 | val 1.38915
  Classification -> best τ=0.565 (val F1=0.2000)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.65291 | val 0.71564
  Epoch 020 - train 0.59297 | val 0.90831
  Classification -> best τ=0.450 (val F1=0.1677)
  Directional -> Accuracy: 0.5303, MCC: 0.0845, F1: 0.6517

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.64106 | val 0.72177
  Epoch 020 - train 0.56979 | val 0.82405
  Classification -> best τ=0.570 (val F1=0.2272)
  Directional -> Accuracy: 0.5517, MCC: 0.0687, F1: 0.6286

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.67261 | val 0.68715
  Epoch 020 - train 0.61166 | val 1.44790
  Classification -> best τ=0.465 (val F1=0.2319)
  Directional -> Accuracy: 0.5000, MCC: 0.0864, F1: 0.6374

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.62417 | val 0.62633
  Epoch 020 - train 0.57390 | val 0.78538
  Classification -> best τ=0.550 (val F1=0.5788)
  Directional -> Accuracy: 0.5536, MCC: 0.2064, F1: 0.4186

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.62474 | val 0.70758
  Epoch 020 - train 0.57301 | val 0.89408
  Classification -> best τ=0.530 (val F1=0.0910)
  Directional -> Accuracy: 0.5319, MCC: -0.1814, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.66533 | val 0.68205
  Epoch 020 - train 0.62428 | val 0.69831
  Classification -> best τ=0.565 (val F1=0.1818)
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.67363 | val 0.76211
  Epoch 020 - train 0.54280 | val 1.20399
  Classification -> best τ=0.385 (val F1=0.2769)
  Directional -> Accuracy: 0.5345, MCC: 0.1708, F1: 0.3721

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.65941 | val 0.69829
  Epoch 020 - train 0.59136 | val 0.77254
  Classification -> best τ=0.550 (val F1=0.3844)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.7077

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.69013 | val 0.98211
  Epoch 020 - train 0.59296 | val 1.87946
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.61394 | val 0.72878
  Epoch 020 - train 0.57887 | val 1.20773
  Classification -> best τ=0.505 (val F1=0.3236)
  Directional -> Accuracy: 0.3864, MCC: -0.2160, F1: 0.1818

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.60959 | val 0.76596
  Epoch 020 - train 0.49135 | val 1.22364
  Classification -> best τ=0.450 (val F1=0.2325)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.66754 | val 0.91473
  Epoch 020 - train 0.57897 | val 1.08463
  Classification -> best τ=0.375 (val F1=0.3216)
  Directional -> Accuracy: 0.5135, MCC: 0.0903, F1: 0.4375

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.62766 | val 0.76609
  Epoch 020 - train 0.60260 | val 0.80214
  Classification -> best τ=0.420 (val F1=0.3130)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6122

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.62176 | val 0.95078
  Epoch 020 - train 0.55154 | val 0.93273
  Classification -> best τ=0.540 (val F1=0.2306)
  Directional -> Accuracy: 0.5333, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.62558 | val 0.78073
  Epoch 020 - train 0.57909 | val 0.84774
  Classification -> best τ=0.435 (val F1=0.3936)
  Directional -> Accuracy: 0.5970, MCC: 0.3247, F1: 0.4906

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.65372 | val 0.68716
  Epoch 020 - train 0.57767 | val 0.72710
  Classification -> best τ=0.545 (val F1=0.2683)
  Directional -> Accuracy: 0.5349, MCC: 0.1249, F1: 0.2857

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.62685 | val 0.85654
  Epoch 020 - train 0.57333 | val 0.96391
  Classification -> best τ=0.435 (val F1=0.1790)
  Directional -> Accuracy: 0.5439, MCC: 0.1154, F1: 0.6061

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.62188 | val 0.79608
  Epoch 020 - train 0.42527 | val 0.89907
  Classification -> best τ=0.495 (val F1=0.2057)
  Directional -> Accuracy: 0.6170, MCC: 0.0508, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 16). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.59975 | val 1.14817
  Epoch 020 - train 0.54471 | val 1.39950
  Classification -> best τ=0.580 (val F1=0.4526)
  Directional -> Accuracy: 0.3750, MCC: 0.1175, F1: 0.5283

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.64027 | val 0.79096
  Epoch 020 - train 0.56774 | val 0.99515
  Classification -> best τ=0.385 (val F1=0.1870)
  Directional -> Accuracy: 0.5641, MCC: 0.1188, F1: 0.7018

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 16). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.63947 | val 0.81853
  Epoch 020 - train 0.55540 | val 1.06794
  Classification -> best τ=0.445 (val F1=0.3651)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.62835 | val 0.70614
  Epoch 020 - train 0.62258 | val 0.72980
  Classification -> best τ=0.515 (val F1=0.3649)
  Directional -> Accuracy: 0.4894, MCC: -0.0111, F1: 0.2941

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.65939 | val 0.75091
  Epoch 020 - train 0.55934 | val 0.83046
  Classification -> best τ=0.550 (val F1=0.2500)
  Directional -> Accuracy: 0.4222, MCC: -0.1195, F1: 0.0714

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.67330 | val 0.75812
  Epoch 020 - train 0.58509 | val 0.81917
  Classification -> best τ=0.505 (val F1=0.4286)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.64722 | val 0.79547
  Epoch 020 - train 0.60808 | val 1.14182
  Classification -> best τ=0.565 (val F1=0.0558)
  Directional -> Accuracy: 0.5789, MCC: 0.1883, F1: 0.5385

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.65690 | val 1.21720
  Epoch 020 - train 0.54378 | val 1.38283
  Classification -> best τ=0.665 (val F1=0.3108)
  Directional -> Accuracy: 0.5439, MCC: 0.0888, F1: 0.5357

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.66342 | val 1.22588
  Epoch 020 - train 0.56258 | val 2.01871
  Classification -> best τ=0.330 (val F1=0.2283)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.64171 | val 0.75708
  Epoch 020 - train 0.61720 | val 0.77361
  Classification -> best τ=0.505 (val F1=0.1536)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.64585 | val 0.87313

[I 2026-02-24 23:14:44,759] Trial 49 finished with value: 0.2565602699747749 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 15, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.7000000000000001, 'batch_size': 64, 'learning_rate': 0.006021988678512389, 'weight_decay': 9.418595602456849e-06, 'lr_patience': 7, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 1.2163106922903606, 'early_stopping_min_delta': 0.0021953761235450463}. Best is trial 32 with value: 0.2908549754956826.

  Epoch 020 - train 0.57733 | val 1.13634
  Classification -> best τ=0.480 (val F1=0.0638)
  Directional -> Accuracy: 0.4355, MCC: -0.1284, F1: 0.5333

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2565602699747749
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 15
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.67160 | val 0.72157
  Epoch 020 - train 0.67152 | val 0.73487
  Classification -> best τ=0.475 (val F1=0.1989)
  Directional -> Accuracy: 0.5714, MCC: 0.1789, F1: 0.1081

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.67816 | val 0.69447
  Epoch 020 - train 0.60455 | val 0.76317
  Classification -> best τ=0.440 (val F1=0.2370)
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 16). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.67626 | val 0.75795
  Epoch 020 - train 0.66487 | val 0.83191
  Classification -> best τ=0.550 (val F1=0.2892)
  Directional -> Accuracy: 0.4583, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.73018 | val 0.69619
  Epoch 020 - train 0.66191 | val 0.75588
  Classification -> best τ=0.540 (val F1=0.0810)
  Directional -> Accuracy: 0.5067, MCC: 0.0443, F1: 0.4478

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.61591 | val 0.84782
  Epoch 020 - train 0.58966 | val 0.80431
  Classification -> best τ=0.520 (val F1=0.3719)
  Directional -> Accuracy: 0.5769, MCC: 0.1441, F1: 0.6207

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.65357 | val 0.84466
  Epoch 020 - train 0.60351 | val 0.71000
  Classification -> best τ=0.505 (val F1=0.3124)
  Directional -> Accuracy: 0.5208, MCC: 0.0861, F1: 0.6667

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.71509 | val 0.67779
  Epoch 020 - train 0.69143 | val 0.67065
  Classification -> best τ=0.430 (val F1=0.3010)
  Directional -> Accuracy: 0.4571, MCC: 0.1458, F1: 0.5870

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 16). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.66537 | val 0.88632
  Epoch 020 - train 0.56948 | val 1.53826
  Classification -> best τ=0.500 (val F1=0.2039)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.64810 | val 0.72148
  Epoch 020 - train 0.63653 | val 0.72282
  Classification -> best τ=0.525 (val F1=0.4764)
  Directional -> Accuracy: 0.5854, MCC: -0.0791, F1: 0.1053

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 16). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 16). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.71995 | val 0.94375
  Epoch 020 - train 0.61157 | val 0.79781
  Classification -> best τ=0.455 (val F1=0.2305)
  Directional -> Accuracy: 0.4366, MCC: 0.0000, F1: 0.6078

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.66747 | val 0.67884
  Epoch 020 - train 0.65889 | val 0.75229
  Classification -> best τ=0.430 (val F1=0.2248)
  Directional -> Accuracy: 0.5098, MCC: -0.0687, F1: 0.0741

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.72063 | val 0.92995
  Epoch 020 - train 0.62726 | val 1.04451
  Classification -> best τ=0.395 (val F1=0.3019)
  Directional -> Accuracy: 0.5085, MCC: 0.0000, F1: 0.6742

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.69926 | val 0.66574
  Epoch 020 - train 0.61381 | val 0.79924
  Classification -> best τ=0.605 (val F1=0.3211)
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.70275 | val 0.65937
  Epoch 020 - train 0.65215 | val 0.74119
  Classification -> best τ=0.425 (val F1=0.3322)
  Directional -> Accuracy: 0.5574, MCC: 0.1199, F1: 0.6400

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.67956 | val 0.96268
  Epoch 020 - train 0.64612 | val 1.02962
  Classification -> best τ=0.565 (val F1=0.2890)
  Directional -> Accuracy: 0.6226, MCC: 0.2429, F1: 0.6000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.68643 | val 0.79633
  Epoch 020 - train 0.63871 | val 0.73768
  Classification -> best τ=0.585 (val F1=0.2952)
  Directional -> Accuracy: 0.5000, MCC: 0.0516, F1: 0.3636

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.68821 | val 0.86011
  Epoch 020 - train 0.62342 | val 0.85310
  Classification -> best τ=0.495 (val F1=0.1346)
  Directional -> Accuracy: 0.6167, MCC: 0.0000, F1: 0.7629

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.64707 | val 0.81546
  Epoch 020 - train 0.64066 | val 0.86783
  Classification -> best τ=0.495 (val F1=0.1731)
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.65645 | val 0.68869
  Epoch 020 - train 0.63149 | val 0.95701
  Classification -> best τ=0.310 (val F1=0.3342)
  Directional -> Accuracy: 0.5000, MCC: 0.1525, F1: 0.3529

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 16). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.65749 | val 0.66941
  Epoch 020 - train 0.62295 | val 0.70495
  Classification -> best τ=0.465 (val F1=0.2809)
  Directional -> Accuracy: 0.4605, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.68628 | val 0.94929
  Epoch 020 - train 0.61566 | val 1.18422
  Classification -> best τ=0.395 (val F1=0.2174)
  Directional -> Accuracy: 0.4792, MCC: 0.2641, F1: 0.2857

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.73317 | val 0.69206
  Epoch 020 - train 0.67464 | val 0.74722
  Classification -> best τ=0.575 (val F1=0.2547)
  Directional -> Accuracy: 0.5152, MCC: 0.0407, F1: 0.2727

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.66843 | val 0.72379
  Epoch 020 - train 0.63323 | val 0.73776
  Classification -> best τ=0.575 (val F1=0.2431)
  Directional -> Accuracy: 0.5345, MCC: 0.0845, F1: 0.5424

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.65659 | val 0.70642
  Epoch 020 - train 0.62354 | val 1.02605
  Classification -> best τ=0.465 (val F1=0.2469)
  Directional -> Accuracy: 0.5152, MCC: 0.1547, F1: 0.6522

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.66963 | val 0.65951
  Epoch 020 - train 0.58983 | val 0.67317
  Classification -> best τ=0.540 (val F1=0.4752)
  Directional -> Accuracy: 0.5714, MCC: 0.2385, F1: 0.4545

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.66739 | val 0.70925
  Epoch 020 - train 0.62707 | val 0.72457
  Classification -> best τ=0.540 (val F1=0.1807)
  Directional -> Accuracy: 0.5745, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.70232 | val 0.78942
  Epoch 020 - train 0.63521 | val 0.69385
  Classification -> best τ=0.550 (val F1=0.2151)
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.69772 | val 0.75245
  Epoch 020 - train 0.63850 | val 0.78995
  Classification -> best τ=0.465 (val F1=0.2935)
  Directional -> Accuracy: 0.5345, MCC: 0.2275, F1: 0.3077

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.71043 | val 0.68706
  Epoch 020 - train 0.64538 | val 0.78133
  Classification -> best τ=0.500 (val F1=0.3844)
  Directional -> Accuracy: 0.5238, MCC: -0.0663, F1: 0.6774

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.69427 | val 0.77021
  Epoch 020 - train 0.60247 | val 0.91963
  Classification -> best τ=0.475 (val F1=0.0212)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.2143

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.66924 | val 0.65596
  Epoch 020 - train 0.65126 | val 0.68150
  Classification -> best τ=0.610 (val F1=0.3593)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.63008 | val 0.69929
  Epoch 020 - train 0.59575 | val 0.90769
  Classification -> best τ=0.535 (val F1=0.2320)
  Directional -> Accuracy: 0.4902, MCC: -0.1289, F1: 0.6486

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.67931 | val 0.63442
  Epoch 020 - train 0.65212 | val 0.64570
  Classification -> best τ=0.390 (val F1=0.3470)
  Directional -> Accuracy: 0.5270, MCC: 0.1044, F1: 0.4776

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.63447 | val 0.69201
  Epoch 020 - train 0.69236 | val 0.70220
  Classification -> best τ=0.500 (val F1=0.3337)
  Directional -> Accuracy: 0.4474, MCC: -0.1715, F1: 0.6038

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.68102 | val 0.78457
  Epoch 020 - train 0.64772 | val 0.96952
  Classification -> best τ=0.555 (val F1=0.1411)
  Directional -> Accuracy: 0.4222, MCC: -0.1410, F1: 0.5185

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.68010 | val 0.74201
  Epoch 020 - train 0.65085 | val 0.78348
  Classification -> best τ=0.460 (val F1=0.3180)
  Directional -> Accuracy: 0.5075, MCC: 0.0171, F1: 0.5352

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.68181 | val 0.73142
  Epoch 020 - train 0.62924 | val 0.73888
  Classification -> best τ=0.535 (val F1=0.1869)
  Directional -> Accuracy: 0.5814, MCC: 0.2592, F1: 0.3571

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.62550 | val 0.72518
  Epoch 020 - train 0.61893 | val 0.71653
  Classification -> best τ=0.515 (val F1=0.2728)
  Directional -> Accuracy: 0.5088, MCC: 0.0304, F1: 0.5484

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.71706 | val 0.82657
  Epoch 020 - train 0.58196 | val 0.93852
  Classification -> best τ=0.565 (val F1=0.1848)
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 16). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.71377 | val 0.80530
  Epoch 020 - train 0.61558 | val 1.31025
  Classification -> best τ=0.505 (val F1=0.2928)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.70201 | val 0.74805
  Epoch 020 - train 0.65730 | val 0.88662
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.7000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 16). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.70275 | val 0.69634
  Epoch 020 - train 0.62908 | val 0.69080
  Classification -> best τ=0.420 (val F1=0.3519)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.67084 | val 0.69595
  Epoch 020 - train 0.64168 | val 0.71601
  Classification -> best τ=0.435 (val F1=0.4633)
  Directional -> Accuracy: 0.4681, MCC: -0.0602, F1: 0.3590

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.66055 | val 0.78045
  Epoch 020 - train 0.64265 | val 0.89307
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.73287 | val 0.74489
  Epoch 020 - train 0.66234 | val 0.90797
  Classification -> best τ=0.530 (val F1=0.2966)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.72127 | val 1.04389
  Epoch 020 - train 0.62384 | val 1.21365
  Classification -> best τ=0.475 (val F1=0.1602)
  Directional -> Accuracy: 0.5263, MCC: -0.0102, F1: 0.6582

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.69781 | val 0.77224
  Epoch 020 - train 0.57823 | val 1.02593
  Classification -> best τ=0.495 (val F1=0.2554)
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.67474 | val 1.34397
  Epoch 020 - train 0.65381 | val 0.95820
  Classification -> best τ=0.420 (val F1=0.2557)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.65588 | val 0.70481
  Epoch 020 - train 0.65180 | val 0.74770
  Classification -> best τ=0.555 (val F1=0.2157)
  Directional -> Accuracy: 0.4386, MCC: -0.2399, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.70144 | val 1.02600

[I 2026-02-24 23:15:39,383] Trial 50 finished with value: 0.25707620810549603 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 15, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.0, 'dropout': 0.8, 'batch_size': 64, 'learning_rate': 0.0028305992407497045, 'weight_decay': 2.9226598036542685e-05, 'lr_patience': 7, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 1.472870812566433, 'early_stopping_min_delta': 0.0036521300904355947}. Best is trial 32 with value: 0.2908549754956826.

  Epoch 020 - train 0.65024 | val 0.93920
  Classification -> best τ=0.590 (val F1=0.2653)
  Directional -> Accuracy: 0.5161, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.25707620810549603
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 15
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.63912 | val 0.87493
  Epoch 014 - train 0.64302 | val 0.72211
  Classification -> best τ=0.565 (val F1=0.2553)
  Directional -> Accuracy: 0.5195, MCC: 0.0100, F1: 0.3934

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.62186 | val 0.96888
  Epoch 011 - train 0.58938 | val 1.13203
  Classification -> best τ=0.505 (val F1=0.1700)
  Directional -> Accuracy: 0.6304, MCC: 0.2280, F1: 0.7213

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 16). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.67092 | val 0.73500
  Epoch 012 - train 0.66514 | val 0.77897
  Classification -> best τ=0.520 (val F1=0.2949)
  Directional -> Accuracy: 0.6250, MCC: 0.2403, F1: 0.6667

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.68708 | val 1.79989
  Epoch 011 - train 0.63721 | val 1.61580
  Classification -> best τ=0.500 (val F1=0.1304)
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.56560 | val 0.75355
  Epoch 014 - train 0.55106 | val 1.83023
  Classification -> best τ=0.365 (val F1=0.3469)
  Directional -> Accuracy: 0.5769, MCC: 0.1670, F1: 0.7105

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.63187 | val 0.86375
  Epoch 012 - train 0.58950 | val 0.94948
  Classification -> best τ=0.545 (val F1=0.3157)
  Directional -> Accuracy: 0.4792, MCC: -0.0861, F1: 0.6377

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.67708 | val 0.77915
  Epoch 015 - train 0.63910 | val 0.75239
  Classification -> best τ=0.480 (val F1=0.2576)
  Directional -> Accuracy: 0.4714, MCC: 0.1750, F1: 0.5934

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 16). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.48597 | val 1.18594
  Epoch 011 - train 0.56483 | val 1.15429
  Classification -> best τ=0.600 (val F1=0.3764)
  Directional -> Accuracy: 0.5111, MCC: 0.0551, F1: 0.5217

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.70434 | val 0.74719
  Epoch 012 - train 0.62748 | val 0.95204
  Classification -> best τ=0.550 (val F1=0.3091)
  Directional -> Accuracy: 0.3171, MCC: -0.2622, F1: 0.4615

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 16). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 16). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.64453 | val 0.89385
  Epoch 012 - train 0.63389 | val 0.72502
  Classification -> best τ=0.565 (val F1=0.1461)
  Directional -> Accuracy: 0.5634, MCC: 0.0633, F1: 0.3111

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.65245 | val 1.19971
  Epoch 015 - train 0.60830 | val 1.17273
  Classification -> best τ=0.395 (val F1=0.2296)
  Directional -> Accuracy: 0.5098, MCC: -0.1333, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.64888 | val 0.92729
  Epoch 011 - train 0.64204 | val 0.92346
  Classification -> best τ=0.435 (val F1=0.3078)
  Directional -> Accuracy: 0.5085, MCC: 0.0000, F1: 0.6742

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.62010 | val 0.70080
  Epoch 013 - train 0.61699 | val 1.08029
  Classification -> best τ=0.495 (val F1=0.3211)
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.65226 | val 0.83916
  Epoch 014 - train 0.61364 | val 1.02095
  Classification -> best τ=0.300 (val F1=0.2789)
  Directional -> Accuracy: 0.5410, MCC: 0.0906, F1: 0.6500

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.61054 | val 2.93437
  Epoch 011 - train 0.65025 | val 2.92931
  Classification -> best τ=0.485 (val F1=0.1645)
  Directional -> Accuracy: 0.5849, MCC: 0.2232, F1: 0.6562

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.61814 | val 0.96589
  Epoch 011 - train 0.64182 | val 1.17461
  Classification -> best τ=0.505 (val F1=0.3019)
  Directional -> Accuracy: 0.6000, MCC: 0.1913, F1: 0.7083

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.65686 | val 1.27670
  Epoch 012 - train 0.64010 | val 1.34614
  Classification -> best τ=0.360 (val F1=0.1920)
  Directional -> Accuracy: 0.6167, MCC: 0.0000, F1: 0.7629

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.66347 | val 1.42842
  Epoch 012 - train 0.62801 | val 1.34860
  Classification -> best τ=0.400 (val F1=0.2059)
  Directional -> Accuracy: 0.4868, MCC: 0.0498, F1: 0.4507

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.66458 | val 1.17092
  Epoch 013 - train 0.62459 | val 1.07252
  Classification -> best τ=0.505 (val F1=0.2249)
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 16). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.65244 | val 0.68590
  Epoch 020 - train 0.57344 | val 0.72134
  Classification -> best τ=0.525 (val F1=0.2579)
  Directional -> Accuracy: 0.4868, MCC: 0.0589, F1: 0.2041

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.63108 | val 0.88318
  Epoch 013 - train 0.59491 | val 0.96915
  Classification -> best τ=0.455 (val F1=0.3361)
  Directional -> Accuracy: 0.4583, MCC: 0.2335, F1: 0.2353

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.63787 | val 1.08107
  Epoch 011 - train 0.61826 | val 1.40489
  Classification -> best τ=0.440 (val F1=0.1177)
  Directional -> Accuracy: 0.5455, MCC: 0.0937, F1: 0.5946

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.67052 | val 0.73649
  Epoch 011 - train 0.63713 | val 0.78297
  Classification -> best τ=0.575 (val F1=0.2812)
  Directional -> Accuracy: 0.5690, MCC: 0.1545, F1: 0.5763

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.65455 | val 1.83872
  Epoch 012 - train 0.62679 | val 1.54524
  Classification -> best τ=0.390 (val F1=0.1878)
  Directional -> Accuracy: 0.5303, MCC: 0.0753, F1: 0.5634

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.62127 | val 0.74688
  Epoch 015 - train 0.62107 | val 0.71580
  Classification -> best τ=0.460 (val F1=0.4039)
  Directional -> Accuracy: 0.5357, MCC: 0.1728, F1: 0.3810

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.66886 | val 0.91528
  Epoch 011 - train 0.59326 | val 0.94812
  Classification -> best τ=0.430 (val F1=0.2979)
  Directional -> Accuracy: 0.5532, MCC: 0.1842, F1: 0.6038

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.67177 | val 0.82473
  Epoch 016 - train 0.63402 | val 1.07377
  Classification -> best τ=0.620 (val F1=0.3078)
  Directional -> Accuracy: 0.6279, MCC: 0.2245, F1: 0.6923

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.64300 | val 0.89121
  Epoch 012 - train 0.61833 | val 0.88107
  Classification -> best τ=0.325 (val F1=0.2472)
  Directional -> Accuracy: 0.6034, MCC: 0.3182, F1: 0.4889

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.66462 | val 0.67411
  Epoch 020 - train 0.58167 | val 0.66423
  Classification -> best τ=0.555 (val F1=0.4576)
  Directional -> Accuracy: 0.5476, MCC: 0.1003, F1: 0.5581

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.60162 | val 1.48206
  Epoch 011 - train 0.60010 | val 1.17695
  Classification -> best τ=0.595 (val F1=0.1869)
  Directional -> Accuracy: 0.5227, MCC: 0.0902, F1: 0.1600

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.64335 | val 0.70173
  Epoch 011 - train 0.65068 | val 0.73099
  Classification -> best τ=0.600 (val F1=0.1239)
  Directional -> Accuracy: 0.4318, MCC: -0.1021, F1: 0.1935

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.60256 | val 0.86900
  Epoch 011 - train 0.63066 | val 0.83290
  Classification -> best τ=0.430 (val F1=0.2541)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.62095 | val 1.02760
  Epoch 011 - train 0.65195 | val 0.93258
  Classification -> best τ=0.405 (val F1=0.3717)
  Directional -> Accuracy: 0.5811, MCC: 0.1883, F1: 0.5753

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.59903 | val 0.86904
  Epoch 013 - train 0.65906 | val 0.77703
  Classification -> best τ=0.495 (val F1=0.4045)
  Directional -> Accuracy: 0.6316, MCC: 0.3095, F1: 0.5000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.64101 | val 1.10586
  Epoch 011 - train 0.62522 | val 1.30876
  Classification -> best τ=0.525 (val F1=0.1410)
  Directional -> Accuracy: 0.5333, MCC: 0.0857, F1: 0.5714

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.59045 | val 0.74277
  Epoch 012 - train 0.58391 | val 0.75452
  Classification -> best τ=0.435 (val F1=0.3687)
  Directional -> Accuracy: 0.6119, MCC: 0.2630, F1: 0.5938

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.67599 | val 0.70700
  Epoch 013 - train 0.55490 | val 0.72171
  Classification -> best τ=0.510 (val F1=0.1873)
  Directional -> Accuracy: 0.5581, MCC: 0.1788, F1: 0.3448

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.65257 | val 0.76008
  Epoch 012 - train 0.60929 | val 0.82807
  Classification -> best τ=0.435 (val F1=0.2423)
  Directional -> Accuracy: 0.4912, MCC: 0.0084, F1: 0.5797

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.64336 | val 0.90804
  Epoch 012 - train 0.57947 | val 1.17996
  Classification -> best τ=0.475 (val F1=0.1871)
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 16). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.54862 | val 1.31363
  Epoch 011 - train 0.57302 | val 1.56410
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.71888 | val 0.76373
  Epoch 014 - train 0.64555 | val 0.78440
  Classification -> best τ=0.445 (val F1=0.4564)
  Directional -> Accuracy: 0.5385, MCC: 0.0643, F1: 0.5909

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 16). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.64833 | val 1.05677
  Epoch 013 - train 0.62695 | val 1.36407
  Classification -> best τ=0.415 (val F1=0.3729)
  Directional -> Accuracy: 0.5395, MCC: 0.2027, F1: 0.6847

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.69405 | val 0.80252
  Epoch 011 - train 0.64621 | val 0.74811
  Classification -> best τ=0.560 (val F1=0.1733)
  Directional -> Accuracy: 0.5745, MCC: 0.1559, F1: 0.6552

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.59100 | val 0.89644
  Epoch 011 - train 0.55033 | val 0.88183
  Classification -> best τ=0.470 (val F1=0.1387)
  Directional -> Accuracy: 0.5778, MCC: 0.1156, F1: 0.6780

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.70173 | val 0.80635
  Epoch 012 - train 0.61101 | val 0.77830
  Classification -> best τ=0.500 (val F1=0.3647)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.65467 | val 1.22765
  Epoch 016 - train 0.65344 | val 0.86997
  Classification -> best τ=0.765 (val F1=0.1869)
  Directional -> Accuracy: 0.4561, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.63501 | val 2.06056
  Epoch 011 - train 0.60828 | val 2.59534
  Classification -> best τ=0.670 (val F1=0.2946)
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.65484 | val 1.49279
  Epoch 011 - train 0.66953 | val 1.28168
  Classification -> best τ=0.430 (val F1=0.1647)
  Directional -> Accuracy: 0.5926, MCC: 0.2085, F1: 0.6944

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.68415 | val 1.28841
  Epoch 012 - train 0.61262 | val 1.21996
  Classification -> best τ=0.555 (val F1=0.3126)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.63431 | val 0.79599

[I 2026-02-24 23:16:55,207] Trial 51 finished with value: 0.25843438267032065 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 15, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 0.003713112155425373, 'weight_decay': 0.0004601053602980342, 'lr_patience': 7, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 1.3432813383600675, 'early_stopping_min_delta': 0.004452070466089118}. Best is trial 32 with value: 0.2908549754956826.

  Epoch 014 - train 0.59483 | val 0.81183
  Classification -> best τ=0.610 (val F1=0.2653)
  Directional -> Accuracy: 0.5161, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.25843438267032065
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 15
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.65763 | val 0.69564
  Epoch 012 - train 0.64306 | val 0.69185
  Classification -> best τ=0.465 (val F1=0.2164)
  Directional -> Accuracy: 0.3896, MCC: -0.2035, F1: 0.4946

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.62503 | val 0.79835
  Epoch 011 - train 0.62617 | val 0.79818
  Classification -> best τ=0.430 (val F1=0.1236)
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 16). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.66422 | val 1.04807
  Epoch 012 - train 0.66020 | val 1.21016
  Classification -> best τ=0.575 (val F1=0.3171)
  Directional -> Accuracy: 0.4583, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.63833 | val 1.13834
  Epoch 011 - train 0.67049 | val 1.16555
  Classification -> best τ=0.355 (val F1=0.2041)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.61301 | val 1.55672
  Epoch 012 - train 0.56057 | val 1.42906
  Classification -> best τ=0.390 (val F1=0.4605)
  Directional -> Accuracy: 0.7500, MCC: 0.5061, F1: 0.7937

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.59614 | val 0.78735
  Epoch 012 - train 0.58095 | val 0.85164
  Classification -> best τ=0.490 (val F1=0.1733)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.67410 | val 0.71141
  Epoch 012 - train 0.67358 | val 0.75817
  Classification -> best τ=0.560 (val F1=0.2722)
  Directional -> Accuracy: 0.5143, MCC: -0.0369, F1: 0.3462

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 16). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.60235 | val 1.53207
  Epoch 011 - train 0.59981 | val 1.31985
  Classification -> best τ=0.545 (val F1=0.1129)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.65288 | val 1.10288
  Epoch 017 - train 0.51580 | val 2.08095
  Classification -> best τ=0.470 (val F1=0.3411)
  Directional -> Accuracy: 0.5610, MCC: 0.1924, F1: 0.5500

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 16). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 16). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.69457 | val 0.88593
  Epoch 012 - train 0.63243 | val 1.09175
  Classification -> best τ=0.380 (val F1=0.2160)
  Directional -> Accuracy: 0.4085, MCC: -0.1544, F1: 0.5714

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.62719 | val 1.16288
  Epoch 011 - train 0.64166 | val 1.10747
  Classification -> best τ=0.470 (val F1=0.0280)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.65489 | val 0.83127
  Epoch 020 - train 0.56732 | val 0.89699
  Classification -> best τ=0.825 (val F1=0.2987)
  Directional -> Accuracy: 0.5254, MCC: 0.1065, F1: 0.2222

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.59505 | val 1.16313
  Epoch 011 - train 0.60248 | val 1.37485
  Classification -> best τ=0.545 (val F1=0.1711)
  Directional -> Accuracy: 0.5814, MCC: 0.1155, F1: 0.2500

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.68222 | val 0.74092
  Epoch 015 - train 0.61554 | val 0.73062
  Classification -> best τ=0.310 (val F1=0.3071)
  Directional -> Accuracy: 0.5574, MCC: 0.1455, F1: 0.6747

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.62348 | val 1.99247
  Epoch 013 - train 0.58234 | val 3.04760
  Classification -> best τ=0.640 (val F1=0.2262)
  Directional -> Accuracy: 0.5283, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.64582 | val 0.80931
  Epoch 012 - train 0.58516 | val 1.02489
  Classification -> best τ=0.540 (val F1=0.3181)
  Directional -> Accuracy: 0.5286, MCC: 0.1598, F1: 0.3265

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.65001 | val 1.07159
  Epoch 012 - train 0.65094 | val 1.28875
  Classification -> best τ=0.485 (val F1=0.1426)
  Directional -> Accuracy: 0.6000, MCC: 0.1128, F1: 0.7000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.65916 | val 1.22814
  Epoch 011 - train 0.63283 | val 1.37597
  Classification -> best τ=0.425 (val F1=0.1674)
  Directional -> Accuracy: 0.5921, MCC: 0.0933, F1: 0.6990

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.64385 | val 0.95258
  Epoch 011 - train 0.64570 | val 1.11794
  Classification -> best τ=0.435 (val F1=0.1203)
  Directional -> Accuracy: 0.5606, MCC: 0.1805, F1: 0.5397

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 16). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.66501 | val 0.78617
  Epoch 012 - train 0.63510 | val 0.81499
  Classification -> best τ=0.530 (val F1=0.3660)
  Directional -> Accuracy: 0.4605, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.57226 | val 1.57760
  Epoch 012 - train 0.67665 | val 1.18841
  Classification -> best τ=0.540 (val F1=0.1794)
  Directional -> Accuracy: 0.3958, MCC: 0.1130, F1: 0.0645

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.64468 | val 1.46141
  Epoch 011 - train 0.68271 | val 1.43297
  Classification -> best τ=0.605 (val F1=0.2264)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.63783 | val 0.97650
  Epoch 013 - train 0.62340 | val 0.85765
  Classification -> best τ=0.625 (val F1=0.2918)
  Directional -> Accuracy: 0.5345, MCC: 0.1655, F1: 0.4255

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.61838 | val 2.08766
  Epoch 012 - train 0.60031 | val 2.16772
  Classification -> best τ=0.220 (val F1=0.1664)
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.67791 | val 0.74488
  Epoch 017 - train 0.61835 | val 0.64425
  Classification -> best τ=0.505 (val F1=0.4411)
  Directional -> Accuracy: 0.6071, MCC: 0.2642, F1: 0.5600

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.57761 | val 1.25455
  Epoch 018 - train 0.53966 | val 1.06747
  Classification -> best τ=0.425 (val F1=0.3721)
  Directional -> Accuracy: 0.7021, MCC: 0.4688, F1: 0.7200

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.70632 | val 1.16468
  Epoch 011 - train 0.60875 | val 0.74949
  Classification -> best τ=0.500 (val F1=0.2603)
  Directional -> Accuracy: 0.5581, MCC: -0.0473, F1: 0.7077

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.62837 | val 0.79669
  Epoch 011 - train 0.65365 | val 0.80080
  Classification -> best τ=0.545 (val F1=0.1522)
  Directional -> Accuracy: 0.4483, MCC: -0.0197, F1: 0.0588

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.68227 | val 0.68884
  Epoch 018 - train 0.63205 | val 0.86163
  Classification -> best τ=0.595 (val F1=0.2833)
  Directional -> Accuracy: 0.5952, MCC: 0.2835, F1: 0.4848

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.69447 | val 1.30117
  Epoch 014 - train 0.62314 | val 1.06280
  Classification -> best τ=0.620 (val F1=0.1869)
  Directional -> Accuracy: 0.5455, MCC: 0.0913, F1: 0.5652

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.62765 | val 0.69741
  Epoch 011 - train 0.68127 | val 0.70817
  Classification -> best τ=0.580 (val F1=0.1239)
  Directional -> Accuracy: 0.4091, MCC: -0.1876, F1: 0.0714

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.66044 | val 0.82133
  Epoch 011 - train 0.61344 | val 0.81377
  Classification -> best τ=0.550 (val F1=0.2870)
  Directional -> Accuracy: 0.4902, MCC: 0.0687, F1: 0.1333

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.66651 | val 2.40028
  Epoch 012 - train 0.57550 | val 2.07482
  Classification -> best τ=0.450 (val F1=0.3677)
  Directional -> Accuracy: 0.5135, MCC: 0.0803, F1: 0.4545

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.68065 | val 0.90917
  Epoch 012 - train 0.64430 | val 1.03051
  Classification -> best τ=0.410 (val F1=0.4792)
  Directional -> Accuracy: 0.6316, MCC: 0.3095, F1: 0.7083

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.59408 | val 1.20701
  Epoch 011 - train 0.62445 | val 1.18495
  Classification -> best τ=0.545 (val F1=0.0917)
  Directional -> Accuracy: 0.6000, MCC: 0.2619, F1: 0.6667

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.63712 | val 0.73144
  Epoch 016 - train 0.58542 | val 0.75293
  Classification -> best τ=0.215 (val F1=0.3767)
  Directional -> Accuracy: 0.5373, MCC: 0.0693, F1: 0.5753

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.62027 | val 0.66239
  Epoch 019 - train 0.59613 | val 0.88706
  Classification -> best τ=0.630 (val F1=0.3337)
  Directional -> Accuracy: 0.5349, MCC: 0.1249, F1: 0.2857

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.62636 | val 0.85547
  Epoch 011 - train 0.59418 | val 0.86356
  Classification -> best τ=0.445 (val F1=0.2816)
  Directional -> Accuracy: 0.5263, MCC: 0.0808, F1: 0.5970

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.63621 | val 1.13775
  Epoch 012 - train 0.60349 | val 1.14902
  Classification -> best τ=0.455 (val F1=0.3609)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 16). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.64366 | val 0.95213
  Epoch 017 - train 0.51417 | val 1.34934
  Classification -> best τ=0.065 (val F1=0.3721)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.71829 | val 0.85348
  Epoch 011 - train 0.55654 | val 0.89407
  Classification -> best τ=0.505 (val F1=0.2431)
  Directional -> Accuracy: 0.5385, MCC: 0.1231, F1: 0.4375

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 16). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.63320 | val 1.01678
  Epoch 013 - train 0.64365 | val 1.15393
  Classification -> best τ=0.320 (val F1=0.3002)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.62635 | val 1.05437
  Epoch 011 - train 0.66862 | val 0.85118
  Classification -> best τ=0.495 (val F1=0.1789)
  Directional -> Accuracy: 0.4468, MCC: -0.1151, F1: 0.2353

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.63139 | val 1.03768
  Epoch 011 - train 0.52433 | val 0.99393
  Classification -> best τ=0.500 (val F1=0.2500)
  Directional -> Accuracy: 0.5778, MCC: 0.1265, F1: 0.6545

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.58555 | val 0.87950
  Epoch 014 - train 0.57371 | val 0.83492
  Classification -> best τ=0.520 (val F1=0.4880)
  Directional -> Accuracy: 0.4500, MCC: 0.2446, F1: 0.5600

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.64047 | val 0.94085
  Epoch 012 - train 0.64426 | val 1.02325
  Classification -> best τ=0.460 (val F1=0.1685)
  Directional -> Accuracy: 0.5439, MCC: 0.0000, F1: 0.7045

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.64416 | val 2.04155
  Epoch 011 - train 0.64973 | val 2.12638
  Classification -> best τ=0.650 (val F1=0.3108)
  Directional -> Accuracy: 0.5263, MCC: 0.2236, F1: 0.6667

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.65166 | val 1.02986
  Epoch 011 - train 0.65936 | val 1.08801
  Classification -> best τ=0.345 (val F1=0.2283)
  Directional -> Accuracy: 0.5370, MCC: 0.1425, F1: 0.6914

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.63418 | val 0.85648
  Epoch 011 - train 0.64843 | val 0.90462
  Classification -> best τ=0.545 (val F1=0.1434)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.65491 | val 1.03841
  Epoch 011 - train 0.66689 | val 0.90813

[I 2026-02-24 23:18:09,520] Trial 52 finished with value: 0.2558735381742554 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 15, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 0.0032401632821539212, 'weight_decay': 0.00011211237156101598, 'lr_patience': 7, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 1.5976809499756504, 'early_stopping_min_delta': 0.003227456082386291}. Best is trial 32 with value: 0.2908549754956826.

  Classification -> best τ=0.545 (val F1=0.2653)
  Directional -> Accuracy: 0.5000, MCC: -0.0679, F1: 0.0606

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2558735381742554
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 15
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.67028 | val 0.74623
  Epoch 014 - train 0.65447 | val 0.79152
  Classification -> best τ=0.565 (val F1=0.2851)
  Directional -> Accuracy: 0.5325, MCC: 0.0063, F1: 0.2500

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.61080 | val 0.94662
  Epoch 011 - train 0.58812 | val 1.23137
  Classification -> best τ=0.430 (val F1=0.2014)
  Directional -> Accuracy: 0.5652, MCC: 0.0604, F1: 0.6875

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 16). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.67520 | val 0.71265
  Epoch 012 - train 0.67844 | val 0.79381
  Classification -> best τ=0.465 (val F1=0.2871)
  Directional -> Accuracy: 0.4375, MCC: -0.2276, F1: 0.5846

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.67444 | val 0.81151
  Epoch 011 - train 0.65699 | val 0.93529
  Classification -> best τ=0.465 (val F1=0.2337)
  Directional -> Accuracy: 0.4133, MCC: -0.1524, F1: 0.1538

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.60250 | val 1.03785
  Epoch 016 - train 0.55964 | val 1.18173
  Classification -> best τ=0.560 (val F1=0.4747)
  Directional -> Accuracy: 0.6538, MCC: 0.3077, F1: 0.7273

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.59855 | val 0.84192
  Epoch 012 - train 0.63484 | val 0.86297
  Classification -> best τ=0.555 (val F1=0.1517)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.70599 | val 0.75108
  Epoch 011 - train 0.67123 | val 0.74094
  Classification -> best τ=0.555 (val F1=0.1715)
  Directional -> Accuracy: 0.5571, MCC: 0.0497, F1: 0.3922

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 16). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.62478 | val 1.76979
  Epoch 011 - train 0.57115 | val 2.03881
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.73820 | val 0.72583
  Epoch 012 - train 0.64314 | val 0.91804
  Classification -> best τ=0.550 (val F1=0.3364)
  Directional -> Accuracy: 0.4634, MCC: -0.1253, F1: 0.3125

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 16). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 16). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.64348 | val 0.91747
  Epoch 012 - train 0.63852 | val 1.18254
  Classification -> best τ=0.370 (val F1=0.1850)
  Directional -> Accuracy: 0.4648, MCC: -0.0010, F1: 0.5581

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.67539 | val 1.11627
  Epoch 014 - train 0.60661 | val 0.97389
  Classification -> best τ=0.380 (val F1=0.2007)
  Directional -> Accuracy: 0.5294, MCC: 0.0327, F1: 0.3333

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.66068 | val 0.88101
  Epoch 012 - train 0.65223 | val 0.83777
  Classification -> best τ=0.420 (val F1=0.1479)
  Directional -> Accuracy: 0.5085, MCC: 0.0000, F1: 0.6742

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.62358 | val 0.88438
  Epoch 014 - train 0.58300 | val 1.66887
  Classification -> best τ=0.550 (val F1=0.0426)
  Directional -> Accuracy: 0.4884, MCC: -0.0261, F1: 0.4500

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.64083 | val 0.64180
  Epoch 014 - train 0.62593 | val 0.72259
  Classification -> best τ=0.275 (val F1=0.2928)
  Directional -> Accuracy: 0.5574, MCC: 0.1356, F1: 0.6667

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.65338 | val 2.16533
  Epoch 011 - train 0.62325 | val 2.82807
  Classification -> best τ=0.775 (val F1=0.2798)
  Directional -> Accuracy: 0.5283, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.64521 | val 0.79494
  Epoch 013 - train 0.61526 | val 0.83332
  Classification -> best τ=0.475 (val F1=0.4302)
  Directional -> Accuracy: 0.5714, MCC: 0.1200, F1: 0.6512

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.66964 | val 0.99227
  Epoch 012 - train 0.65129 | val 0.93564
  Classification -> best τ=0.755 (val F1=0.2219)
  Directional -> Accuracy: 0.3833, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.68336 | val 1.31094
  Epoch 013 - train 0.63795 | val 1.55897
  Classification -> best τ=0.410 (val F1=0.2232)
  Directional -> Accuracy: 0.5789, MCC: 0.1504, F1: 0.6279

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.65568 | val 0.92858
  Epoch 012 - train 0.65477 | val 1.07110
  Classification -> best τ=0.435 (val F1=0.3644)
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 16). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.63524 | val 0.83587
  Epoch 013 - train 0.63297 | val 0.79380
  Classification -> best τ=0.310 (val F1=0.1940)
  Directional -> Accuracy: 0.3947, MCC: -0.1959, F1: 0.3030

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.59979 | val 1.08749
  Epoch 013 - train 0.61415 | val 1.65419
  Classification -> best τ=0.500 (val F1=0.3544)
  Directional -> Accuracy: 0.4792, MCC: 0.2641, F1: 0.2857

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.64104 | val 1.14926
  Epoch 013 - train 0.63355 | val 1.52485
  Classification -> best τ=0.405 (val F1=0.1677)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.63240 | val 0.86420
  Epoch 011 - train 0.65397 | val 0.90240
  Classification -> best τ=0.705 (val F1=0.3487)
  Directional -> Accuracy: 0.5000, MCC: 0.0455, F1: 0.4528

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.64652 | val 1.58052
  Epoch 013 - train 0.66491 | val 2.07251
  Classification -> best τ=0.345 (val F1=0.3042)
  Directional -> Accuracy: 0.5303, MCC: 0.0859, F1: 0.5867

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.65619 | val 0.67732
  Epoch 015 - train 0.65358 | val 0.66257
  Classification -> best τ=0.590 (val F1=0.4079)
  Directional -> Accuracy: 0.5536, MCC: 0.2064, F1: 0.4186

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.53823 | val 1.18896
  Epoch 011 - train 0.57953 | val 1.31724
  Classification -> best τ=0.565 (val F1=0.3225)
  Directional -> Accuracy: 0.5957, MCC: 0.1713, F1: 0.0952

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.68490 | val 0.80846
  Epoch 013 - train 0.63754 | val 1.11528
  Classification -> best τ=0.500 (val F1=0.1309)
  Directional -> Accuracy: 0.5814, MCC: 0.1400, F1: 0.6400

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.65504 | val 0.71824
  Epoch 013 - train 0.64514 | val 0.76960
  Classification -> best τ=0.450 (val F1=0.1960)
  Directional -> Accuracy: 0.5000, MCC: 0.1533, F1: 0.2162

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.74904 | val 0.69392
  Epoch 020 - train 0.65614 | val 0.76624
  Classification -> best τ=0.420 (val F1=0.3069)
  Directional -> Accuracy: 0.5238, MCC: -0.0663, F1: 0.6774

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.58892 | val 0.95309
  Epoch 012 - train 0.60174 | val 1.09418
  Classification -> best τ=0.740 (val F1=0.1869)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.4500

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.64187 | val 0.91839
  Epoch 011 - train 0.73009 | val 0.88786
  Classification -> best τ=0.535 (val F1=0.0587)
  Directional -> Accuracy: 0.4545, MCC: -0.1336, F1: 0.5556

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.62594 | val 0.81453
  Epoch 013 - train 0.60119 | val 0.76059
  Classification -> best τ=0.710 (val F1=0.2320)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.64189 | val 1.64010
  Epoch 013 - train 0.61886 | val 1.34031
  Classification -> best τ=0.375 (val F1=0.3470)
  Directional -> Accuracy: 0.5405, MCC: 0.1282, F1: 0.5000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.67640 | val 0.84372
  Epoch 011 - train 0.56847 | val 0.87746
  Classification -> best τ=0.450 (val F1=0.4110)
  Directional -> Accuracy: 0.4211, MCC: -0.1615, F1: 0.4762

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.63957 | val 1.06977
  Epoch 011 - train 0.63187 | val 1.02417
  Classification -> best τ=0.565 (val F1=0.3014)
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.6364

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.64873 | val 0.72001
  Epoch 011 - train 0.64529 | val 0.69400
  Classification -> best τ=0.370 (val F1=0.3266)
  Directional -> Accuracy: 0.4627, MCC: -0.0053, F1: 0.3333

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.67949 | val 0.69847
  Epoch 018 - train 0.62969 | val 0.79844
  Classification -> best τ=0.465 (val F1=0.3311)
  Directional -> Accuracy: 0.6047, MCC: 0.2739, F1: 0.4516

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.63699 | val 0.83625
  Epoch 012 - train 0.64779 | val 0.72326
  Classification -> best τ=0.390 (val F1=0.2668)
  Directional -> Accuracy: 0.5439, MCC: 0.1810, F1: 0.6579

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.63952 | val 1.02756
  Epoch 014 - train 0.56650 | val 1.08019
  Classification -> best τ=0.520 (val F1=0.5010)
  Directional -> Accuracy: 0.5532, MCC: -0.0837, F1: 0.6957

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 16). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.69302 | val 1.38028
  Epoch 011 - train 0.63637 | val 1.17958
  Classification -> best τ=0.470 (val F1=0.3410)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.67125 | val 0.77311
  Epoch 011 - train 0.64454 | val 0.82158
  Classification -> best τ=0.520 (val F1=0.2431)
  Directional -> Accuracy: 0.5128, MCC: 0.0317, F1: 0.5128

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 16). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.67340 | val 1.08388
  Epoch 012 - train 0.63367 | val 1.27800
  Classification -> best τ=0.425 (val F1=0.4248)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.69479 | val 0.70454
  Epoch 011 - train 0.64886 | val 0.72501
  Classification -> best τ=0.445 (val F1=0.2544)
  Directional -> Accuracy: 0.5319, MCC: 0.1194, F1: 0.2667

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.75863 | val 1.21694
  Epoch 013 - train 0.55032 | val 1.31493
  Classification -> best τ=0.445 (val F1=0.2000)
  Directional -> Accuracy: 0.6000, MCC: 0.1673, F1: 0.7000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.63209 | val 0.74137
  Epoch 012 - train 0.69524 | val 0.83780
  Classification -> best τ=0.515 (val F1=0.2381)
  Directional -> Accuracy: 0.6500, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.65577 | val 0.86850
  Epoch 011 - train 0.64230 | val 1.25855
  Classification -> best τ=0.430 (val F1=0.2973)
  Directional -> Accuracy: 0.5439, MCC: 0.0168, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.66728 | val 1.41684
  Epoch 011 - train 0.64782 | val 1.94899
  Classification -> best τ=0.730 (val F1=0.3883)
  Directional -> Accuracy: 0.5614, MCC: 0.1576, F1: 0.6269

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.66058 | val 1.46851
  Epoch 012 - train 0.66226 | val 1.40654
  Classification -> best τ=0.345 (val F1=0.1605)
  Directional -> Accuracy: 0.4815, MCC: -0.1890, F1: 0.6500

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.64158 | val 1.56851
  Epoch 013 - train 0.67103 | val 2.25940
  Classification -> best τ=0.420 (val F1=0.2721)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.64586 | val 1.13907

[I 2026-02-24 23:19:24,884] Trial 53 finished with value: 0.2664698488048908 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 15, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 0.005407268514014498, 'weight_decay': 0.0006794342566719898, 'lr_patience': 7, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 1.5001677316742383, 'early_stopping_min_delta': 0.00510138936420622}. Best is trial 32 with value: 0.2908549754956826.

  Epoch 014 - train 0.61360 | val 0.88838
  Classification -> best τ=0.475 (val F1=0.2782)
  Directional -> Accuracy: 0.5000, MCC: 0.0679, F1: 0.6517

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2664698488048908
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 15
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.68319 | val 0.68538
  Epoch 019 - train 0.66299 | val 0.83338
  Classification -> best τ=0.435 (val F1=0.2851)
  Directional -> Accuracy: 0.3896, MCC: -0.2236, F1: 0.5347

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.71403 | val 0.90243
  Epoch 016 - train 0.63132 | val 0.72211
  Classification -> best τ=0.390 (val F1=0.2440)
  Directional -> Accuracy: 0.5435, MCC: 0.0096, F1: 0.6667

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 16). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.68135 | val 0.75922
  Epoch 012 - train 0.68261 | val 0.90053
  Classification -> best τ=0.675 (val F1=0.3402)
  Directional -> Accuracy: 0.5417, MCC: 0.2212, F1: 0.3125

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.68904 | val 1.02380
  Epoch 011 - train 0.67357 | val 1.05665
  Classification -> best τ=0.495 (val F1=0.1778)
  Directional -> Accuracy: 0.5200, MCC: 0.0016, F1: 0.6170

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.67333 | val 1.23135
  Epoch 014 - train 0.62516 | val 1.23277
  Classification -> best τ=0.505 (val F1=0.3847)
  Directional -> Accuracy: 0.5769, MCC: 0.1338, F1: 0.6765

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.56882 | val 0.84997
  Epoch 011 - train 0.64249 | val 0.86737
  Classification -> best τ=0.535 (val F1=0.1733)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6571

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.69038 | val 0.75027
  Epoch 018 - train 0.65709 | val 0.71057
  Classification -> best τ=0.430 (val F1=0.2806)
  Directional -> Accuracy: 0.4714, MCC: 0.0900, F1: 0.5647

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 16). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.64113 | val 2.29017
  Epoch 011 - train 0.73294 | val 2.18935
  Classification -> best τ=0.545 (val F1=0.1048)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.71455 | val 0.77835
  Epoch 015 - train 0.57146 | val 0.78402
  Classification -> best τ=0.475 (val F1=0.3441)
  Directional -> Accuracy: 0.3659, MCC: 0.0000, F1: 0.5357

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 16). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 16). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.67108 | val 0.80149
  Epoch 013 - train 0.63876 | val 0.94426
  Classification -> best τ=0.480 (val F1=0.1535)
  Directional -> Accuracy: 0.5352, MCC: 0.0587, F1: 0.4762

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.67641 | val 0.97066
  Epoch 011 - train 0.64400 | val 1.06116
  Classification -> best τ=0.520 (val F1=0.1835)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.70605 | val 0.75942
  Epoch 020 - train 0.62925 | val 1.10105
  Epoch 025 - train 0.64309 | val 0.73763
  Classification -> best τ=0.675 (val F1=0.2701)
  Directional -> Accuracy: 0.6271, MCC: 0.2833, F1: 0.5417

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.67566 | val 0.76855
  Epoch 019 - train 0.75119 | val 1.52249
  Classification -> best τ=0.345 (val F1=0.2454)
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.71024 | val 0.74419
  Epoch 017 - train 0.64089 | val 0.64849
  Classification -> best τ=0.390 (val F1=0.3180)
  Directional -> Accuracy: 0.5410, MCC: 0.1155, F1: 0.6744

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.65005 | val 1.59834
  Epoch 011 - train 0.64870 | val 1.67500
  Classification -> best τ=0.630 (val F1=0.2262)
  Directional -> Accuracy: 0.5283, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.61989 | val 0.93672
  Epoch 014 - train 0.62147 | val 0.97468
  Classification -> best τ=0.320 (val F1=0.2605)
  Directional -> Accuracy: 0.5714, MCC: 0.1869, F1: 0.7170

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.67923 | val 0.97803
  Epoch 011 - train 0.67440 | val 0.99737
  Classification -> best τ=0.575 (val F1=0.1409)
  Directional -> Accuracy: 0.3833, MCC: -0.1073, F1: 0.2128

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.67860 | val 1.13153
  Epoch 011 - train 0.66432 | val 1.04426
  Classification -> best τ=0.420 (val F1=0.1217)
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.69459 | val 0.66909
  Epoch 020 - train 0.65660 | val 1.07200
  Classification -> best τ=0.470 (val F1=0.4416)
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 16). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.71721 | val 0.69126
  Epoch 013 - train 0.65467 | val 0.67783
  Classification -> best τ=0.300 (val F1=0.2518)
  Directional -> Accuracy: 0.5395, MCC: 0.0000, F1: 0.7009

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.60557 | val 1.17689
  Epoch 011 - train 0.62300 | val 1.31200
  Classification -> best τ=0.480 (val F1=0.2871)
  Directional -> Accuracy: 0.6667, MCC: 0.2604, F1: 0.7500

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.66611 | val 1.18194
  Epoch 014 - train 0.64917 | val 1.49734
  Classification -> best τ=0.465 (val F1=0.0913)
  Directional -> Accuracy: 0.6364, MCC: 0.3012, F1: 0.7000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.66699 | val 0.98754
  Epoch 012 - train 0.65404 | val 1.02717
  Classification -> best τ=0.705 (val F1=0.2907)
  Directional -> Accuracy: 0.5172, MCC: 0.0882, F1: 0.4615

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.67747 | val 1.57143
  Epoch 012 - train 0.63122 | val 0.97220
  Classification -> best τ=0.505 (val F1=0.1878)
  Directional -> Accuracy: 0.5606, MCC: 0.1233, F1: 0.5538

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.65481 | val 0.91544
  Epoch 012 - train 0.65901 | val 0.71107
  Classification -> best τ=0.580 (val F1=0.3859)
  Directional -> Accuracy: 0.5536, MCC: 0.2064, F1: 0.4186

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.60842 | val 0.72310
  Epoch 011 - train 0.65330 | val 0.74447
  Classification -> best τ=0.540 (val F1=0.1792)
  Directional -> Accuracy: 0.5745, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.69343 | val 0.69932
  Epoch 016 - train 0.70719 | val 0.74485
  Classification -> best τ=0.600 (val F1=0.1400)
  Directional -> Accuracy: 0.5116, MCC: 0.0044, F1: 0.5714

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.66553 | val 0.76476
  Epoch 013 - train 0.65942 | val 0.70644
  Classification -> best τ=0.570 (val F1=0.3127)
  Directional -> Accuracy: 0.5000, MCC: 0.1533, F1: 0.2162

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.78484 | val 0.75514
  Epoch 018 - train 0.74639 | val 0.74020
  Classification -> best τ=0.605 (val F1=0.5538)
  Directional -> Accuracy: 0.5238, MCC: 0.0912, F1: 0.4444

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.65274 | val 1.27769
  Epoch 011 - train 0.64719 | val 1.44130
  Classification -> best τ=0.540 (val F1=0.1869)
  Directional -> Accuracy: 0.5227, MCC: 0.0479, F1: 0.4324

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.71091 | val 0.67409
  Epoch 018 - train 0.64942 | val 0.72659
  Classification -> best τ=0.665 (val F1=0.1239)
  Directional -> Accuracy: 0.3864, MCC: -0.2092, F1: 0.2703

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.62903 | val 0.83389
  Epoch 011 - train 0.64296 | val 0.91330
  Classification -> best τ=0.620 (val F1=0.2320)
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.67366 | val 0.81462
  Epoch 011 - train 0.69078 | val 0.87523
  Classification -> best τ=0.345 (val F1=0.3723)
  Directional -> Accuracy: 0.5676, MCC: 0.1562, F1: 0.5676

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.71211 | val 0.75305
  Epoch 015 - train 0.64348 | val 0.91734
  Classification -> best τ=0.465 (val F1=0.1724)
  Directional -> Accuracy: 0.5263, MCC: 0.1644, F1: 0.6786

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.70411 | val 0.92686
  Epoch 011 - train 0.64948 | val 1.03218
  Classification -> best τ=0.485 (val F1=0.2922)
  Directional -> Accuracy: 0.4667, MCC: -0.0449, F1: 0.5385

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.62151 | val 0.79279
  Epoch 011 - train 0.64744 | val 0.80904
  Classification -> best τ=0.290 (val F1=0.3767)
  Directional -> Accuracy: 0.6269, MCC: 0.2370, F1: 0.6753

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.70770 | val 0.73764
  Epoch 020 - train 0.62321 | val 0.80606
  Epoch 024 - train 0.62128 | val 0.93564
  Classification -> best τ=0.575 (val F1=0.3337)
  Directional -> Accuracy: 0.6279, MCC: 0.2967, F1: 0.5294

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.69922 | val 0.92030
  Epoch 013 - train 0.61733 | val 0.82813
  Classification -> best τ=0.330 (val F1=0.2615)
  Directional -> Accuracy: 0.5439, MCC: 0.0792, F1: 0.4800

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.64304 | val 0.74139
  Epoch 012 - train 0.59954 | val 0.84755
  Classification -> best τ=0.475 (val F1=0.2258)
  Directional -> Accuracy: 0.5957, MCC: -0.1162, F1: 0.7467

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 16). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.68152 | val 0.96754
  Epoch 011 - train 0.67062 | val 0.97252
  Classification -> best τ=0.410 (val F1=0.2000)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.90403 | val 1.05157
  Epoch 011 - train 0.71707 | val 1.00787
  Classification -> best τ=0.425 (val F1=0.4623)
  Directional -> Accuracy: 0.5128, MCC: -0.0473, F1: 0.6545

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 16). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.68785 | val 0.72999
  Epoch 012 - train 0.64273 | val 0.96306
  Classification -> best τ=0.420 (val F1=0.3424)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.76400 | val 0.74877
  Epoch 014 - train 0.67049 | val 0.79671
  Classification -> best τ=0.440 (val F1=0.2753)
  Directional -> Accuracy: 0.5532, MCC: 0.2154, F1: 0.6957

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.63025 | val 1.06356
  Epoch 011 - train 0.61574 | val 1.16265
  Classification -> best τ=0.505 (val F1=0.1348)
  Directional -> Accuracy: 0.5333, MCC: 0.0410, F1: 0.6038

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.67553 | val 0.84844
  Epoch 011 - train 0.62712 | val 0.85955
  Classification -> best τ=0.560 (val F1=0.2623)
  Directional -> Accuracy: 0.5500, MCC: 0.0428, F1: 0.4000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.69481 | val 0.78264
  Epoch 011 - train 0.68915 | val 0.80786
  Classification -> best τ=0.585 (val F1=0.1379)
  Directional -> Accuracy: 0.4386, MCC: -0.1567, F1: 0.5294

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.67570 | val 1.59947
  Epoch 011 - train 0.64758 | val 1.56941
  Classification -> best τ=0.610 (val F1=0.3992)
  Directional -> Accuracy: 0.5439, MCC: 0.0974, F1: 0.5667

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.66074 | val 1.27277
  Epoch 012 - train 0.65006 | val 1.29762
  Classification -> best τ=0.295 (val F1=0.2577)
  Directional -> Accuracy: 0.5926, MCC: 0.2490, F1: 0.7105

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.67429 | val 1.02960
  Epoch 013 - train 0.68808 | val 0.77558
  Classification -> best τ=0.360 (val F1=0.1181)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.65891 | val 0.69641

[I 2026-02-24 23:20:46,652] Trial 54 finished with value: 0.25787302050791266 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 15, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 32, 'learning_rate': 0.00610891046663889, 'weight_decay': 7.792681238869075e-05, 'lr_patience': 7, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.4904052771306162, 'early_stopping_min_delta': 0.002437339424585347}. Best is trial 32 with value: 0.2908549754956826.

  Epoch 015 - train 0.68118 | val 0.92237
  Classification -> best τ=0.450 (val F1=0.3502)
  Directional -> Accuracy: 0.4677, MCC: -0.0594, F1: 0.5075

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.25787302050791266
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 15
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.62311 | val 0.91896
  Epoch 015 - train 0.62178 | val 0.87758
  Classification -> best τ=0.445 (val F1=0.2453)
  Directional -> Accuracy: 0.5584, MCC: 0.1479, F1: 0.5952

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.58652 | val 0.99928
  Epoch 013 - train 0.56210 | val 0.98223
  Classification -> best τ=0.545 (val F1=0.2431)
  Directional -> Accuracy: 0.6522, MCC: 0.3895, F1: 0.6000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 16). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.61748 | val 0.98374
  Epoch 014 - train 0.62632 | val 0.75130
  Classification -> best τ=0.505 (val F1=0.4093)
  Directional -> Accuracy: 0.3125, MCC: -0.3679, F1: 0.2326

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.63564 | val 1.69523
  Epoch 011 - train 0.62474 | val 1.46988
  Classification -> best τ=0.450 (val F1=0.1799)
  Directional -> Accuracy: 0.5200, MCC: 0.0518, F1: 0.5135

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.60636 | val 0.92323
  Epoch 013 - train 0.54536 | val 1.14985
  Classification -> best τ=0.480 (val F1=0.4357)
  Directional -> Accuracy: 0.6923, MCC: 0.4292, F1: 0.7714

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.56927 | val 1.18431
  Epoch 015 - train 0.53783 | val 1.20816
  Classification -> best τ=0.555 (val F1=0.3760)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.64692 | val 0.80260
  Epoch 019 - train 0.59386 | val 0.74653
  Classification -> best τ=0.725 (val F1=0.2462)
  Directional -> Accuracy: 0.4857, MCC: -0.0117, F1: 0.4545

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 16). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.53333 | val 1.00432
  Epoch 011 - train 0.50780 | val 1.12195
  Classification -> best τ=0.560 (val F1=0.2988)
  Directional -> Accuracy: 0.4889, MCC: 0.0485, F1: 0.5490

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.57364 | val 1.34479
  Epoch 012 - train 0.56735 | val 1.93340
  Classification -> best τ=0.560 (val F1=0.3877)
  Directional -> Accuracy: 0.5366, MCC: 0.1911, F1: 0.5581

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 16). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 16). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.61193 | val 1.06642
  Epoch 013 - train 0.60398 | val 0.74662
  Classification -> best τ=0.515 (val F1=0.2565)
  Directional -> Accuracy: 0.5634, MCC: 0.0517, F1: 0.2439

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.61759 | val 1.76057
  Epoch 013 - train 0.57777 | val 1.92719
  Classification -> best τ=0.550 (val F1=0.1137)
  Directional -> Accuracy: 0.6078, MCC: 0.2415, F1: 0.3750

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.59753 | val 0.73018
  Epoch 011 - train 0.58579 | val 0.74915
  Classification -> best τ=0.460 (val F1=0.3033)
  Directional -> Accuracy: 0.4915, MCC: -0.1291, F1: 0.6591

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.59157 | val 2.20643
  Epoch 012 - train 0.57966 | val 1.56223
  Classification -> best τ=0.445 (val F1=0.2465)
  Directional -> Accuracy: 0.5814, MCC: 0.1280, F1: 0.4375

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.65629 | val 1.18748
  Epoch 014 - train 0.61106 | val 1.28039
  Classification -> best τ=0.280 (val F1=0.3336)
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.56978 | val 2.74945
  Epoch 011 - train 0.59905 | val 3.50642
  Classification -> best τ=0.480 (val F1=0.1081)
  Directional -> Accuracy: 0.4340, MCC: -0.1221, F1: 0.4828

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.56502 | val 0.96062
  Epoch 011 - train 0.59537 | val 1.12465
  Classification -> best τ=0.560 (val F1=0.2179)
  Directional -> Accuracy: 0.5429, MCC: 0.1054, F1: 0.5152

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.66445 | val 1.29565
  Epoch 011 - train 0.63624 | val 1.13627
  Classification -> best τ=0.545 (val F1=0.2585)
  Directional -> Accuracy: 0.3833, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.61743 | val 2.32479
  Epoch 011 - train 0.62464 | val 1.82852
  Classification -> best τ=0.390 (val F1=0.2232)
  Directional -> Accuracy: 0.5658, MCC: 0.0755, F1: 0.6526

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.64080 | val 1.13624
  Epoch 013 - train 0.59946 | val 1.68482
  Classification -> best τ=0.385 (val F1=0.3603)
  Directional -> Accuracy: 0.5152, MCC: 0.1571, F1: 0.4074

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 16). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.61758 | val 0.96745
  Epoch 017 - train 0.56333 | val 0.71228
  Classification -> best τ=0.325 (val F1=0.3610)
  Directional -> Accuracy: 0.5789, MCC: 0.2064, F1: 0.5000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.58193 | val 0.82035
  Epoch 020 - train 0.49502 | val 2.42457
  Classification -> best τ=0.255 (val F1=0.3555)
  Directional -> Accuracy: 0.5625, MCC: 0.0562, F1: 0.6557

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.62022 | val 1.19557
  Epoch 012 - train 0.59358 | val 1.48893
  Classification -> best τ=0.475 (val F1=0.0835)
  Directional -> Accuracy: 0.4848, MCC: -0.1240, F1: 0.6531

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.60236 | val 1.37816
  Epoch 012 - train 0.61727 | val 1.43015
  Classification -> best τ=0.505 (val F1=0.3185)
  Directional -> Accuracy: 0.5172, MCC: -0.0370, F1: 0.6316

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.60597 | val 2.55209
  Epoch 011 - train 0.58320 | val 3.15050
  Classification -> best τ=0.430 (val F1=0.1878)
  Directional -> Accuracy: 0.5909, MCC: 0.1996, F1: 0.6197

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.62114 | val 0.67990
  Epoch 016 - train 0.58301 | val 0.75980
  Classification -> best τ=0.620 (val F1=0.4015)
  Directional -> Accuracy: 0.5714, MCC: 0.2385, F1: 0.4545

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.56676 | val 0.76893
  Epoch 011 - train 0.53788 | val 0.82632
  Classification -> best τ=0.485 (val F1=0.2067)
  Directional -> Accuracy: 0.4681, MCC: -0.0301, F1: 0.4898

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.63452 | val 1.40134
  Epoch 011 - train 0.56882 | val 1.56349
  Classification -> best τ=0.500 (val F1=0.1818)
  Directional -> Accuracy: 0.5814, MCC: 0.0664, F1: 0.7097

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.62246 | val 1.05635
  Epoch 011 - train 0.59828 | val 0.95066
  Classification -> best τ=0.465 (val F1=0.2769)
  Directional -> Accuracy: 0.6379, MCC: 0.3740, F1: 0.5532

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.68623 | val 0.70860
  Epoch 020 - train 0.50644 | val 0.67368
  Classification -> best τ=0.440 (val F1=0.3677)
  Directional -> Accuracy: 0.5476, MCC: 0.0535, F1: 0.6545

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.55636 | val 1.54812
  Epoch 011 - train 0.56017 | val 2.39331
  Classification -> best τ=0.570 (val F1=0.1869)
  Directional -> Accuracy: 0.4545, MCC: -0.1021, F1: 0.2941

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.64614 | val 1.05413
  Epoch 011 - train 0.59609 | val 0.97392
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.61858 | val 0.91749
  Epoch 014 - train 0.53228 | val 0.89968
  Classification -> best τ=0.425 (val F1=0.3589)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.60500 | val 2.55523
  Epoch 013 - train 0.57934 | val 2.23418
  Classification -> best τ=0.450 (val F1=0.3259)
  Directional -> Accuracy: 0.5676, MCC: 0.1479, F1: 0.5789

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.56461 | val 0.74889
  Epoch 013 - train 0.63618 | val 0.88677
  Classification -> best τ=0.410 (val F1=0.2955)
  Directional -> Accuracy: 0.4474, MCC: -0.1291, F1: 0.5714

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.59241 | val 1.14316
  Epoch 011 - train 0.55171 | val 1.22010
  Classification -> best τ=0.515 (val F1=0.0472)
  Directional -> Accuracy: 0.6222, MCC: 0.2695, F1: 0.6531

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.58189 | val 0.83690
  Epoch 020 - train 0.54859 | val 0.98981
  Classification -> best τ=0.255 (val F1=0.4238)
  Directional -> Accuracy: 0.5075, MCC: 0.1079, F1: 0.3774

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.63410 | val 0.71119
  Epoch 014 - train 0.62652 | val 0.76146
  Classification -> best τ=0.425 (val F1=0.2259)
  Directional -> Accuracy: 0.5349, MCC: 0.0660, F1: 0.6154

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.58502 | val 0.81074
  Epoch 011 - train 0.57380 | val 0.84653
  Classification -> best τ=0.430 (val F1=0.1790)
  Directional -> Accuracy: 0.5263, MCC: 0.0518, F1: 0.5091

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.57288 | val 1.26931
  Epoch 011 - train 0.55349 | val 1.18029
  Classification -> best τ=0.480 (val F1=0.3834)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 16). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.53956 | val 1.10335
  Epoch 018 - train 0.50769 | val 2.39023
  Classification -> best τ=0.350 (val F1=0.2437)
  Directional -> Accuracy: 0.3750, MCC: 0.1175, F1: 0.5283

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.62892 | val 0.77798
  Epoch 011 - train 0.62679 | val 0.77819
  Classification -> best τ=0.520 (val F1=0.0406)
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.0000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 16). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.61682 | val 1.05569
  Epoch 013 - train 0.58592 | val 1.49017
  Classification -> best τ=0.305 (val F1=0.4223)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.57733 | val 1.01901
  Epoch 011 - train 0.65248 | val 0.93011
  Classification -> best τ=0.455 (val F1=0.2043)
  Directional -> Accuracy: 0.5957, MCC: 0.2000, F1: 0.6667

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.58440 | val 1.23832
  Epoch 011 - train 0.52408 | val 1.21223
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.60994 | val 1.15757
  Epoch 017 - train 0.48579 | val 1.10542
  Classification -> best τ=0.245 (val F1=0.4286)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.63267 | val 1.43357
  Epoch 011 - train 0.61058 | val 1.61118
  Classification -> best τ=0.505 (val F1=0.1059)
  Directional -> Accuracy: 0.4561, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.55363 | val 2.13968
  Epoch 011 - train 0.59052 | val 1.90738
  Classification -> best τ=0.655 (val F1=0.4250)
  Directional -> Accuracy: 0.4912, MCC: 0.0663, F1: 0.6420

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.60834 | val 2.34487
  Epoch 012 - train 0.58273 | val 1.92615
  Classification -> best τ=0.340 (val F1=0.3303)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.60987 | val 1.17017
  Epoch 011 - train 0.61445 | val 1.19311
  Classification -> best τ=0.630 (val F1=0.1009)
  Directional -> Accuracy: 0.5439, MCC: 0.0874, F1: 0.6176

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.60697 | val 1.01913

[I 2026-02-24 23:22:04,459] Trial 55 finished with value: 0.2594036932069179 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 15, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.1, 'dropout': 0.6000000000000001, 'batch_size': 32, 'learning_rate': 0.0021556180169263126, 'weight_decay': 0.0003712150239661338, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 1.6917950627879745, 'early_stopping_min_delta': 0.0007698018545088388}. Best is trial 32 with value: 0.2908549754956826.

  Epoch 012 - train 0.58846 | val 1.11545
  Classification -> best τ=0.465 (val F1=0.2574)
  Directional -> Accuracy: 0.4839, MCC: 0.0000, F1: 0.6522

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2594036932069179
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 5
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.60889 | val 1.14016
  Epoch 012 - train 0.61067 | val 1.21927
  Classification -> best τ=0.520 (val F1=0.1903)
  Directional -> Accuracy: 0.5190, MCC: -0.1272, F1: 0.0500

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.67418 | val 0.88186
  Epoch 011 - train 0.62534 | val 1.09197
  Classification -> best τ=0.515 (val F1=0.1654)
  Directional -> Accuracy: 0.6667, MCC: 0.4134, F1: 0.6190

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 6). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.69545 | val 1.00130
  Epoch 011 - train 0.66853 | val 1.05076
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.66953 | val 1.20308
  Epoch 012 - train 0.64799 | val 2.09554
  Classification -> best τ=0.455 (val F1=0.1654)
  Directional -> Accuracy: 0.5714, MCC: 0.1120, F1: 0.6733

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.58540 | val 0.61261
  Epoch 020 - train 0.53463 | val 0.95141
  Classification -> best τ=0.560 (val F1=0.3744)
  Directional -> Accuracy: 0.6604, MCC: 0.3186, F1: 0.6786

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.57340 | val 0.92110
  Epoch 011 - train 0.58964 | val 0.91352
  Classification -> best τ=0.545 (val F1=0.3290)
  Directional -> Accuracy: 0.5238, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.65449 | val 0.70711
  Epoch 011 - train 0.69518 | val 0.77439
  Classification -> best τ=0.545 (val F1=0.1738)
  Directional -> Accuracy: 0.6111, MCC: 0.1627, F1: 0.4167

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 6). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.67992 | val 1.02238
  Epoch 011 - train 0.56961 | val 1.07631
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4043, MCC: 0.0000, F1: 0.5758

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.65311 | val 0.85158
  Epoch 017 - train 0.59343 | val 0.85729
  Classification -> best τ=0.505 (val F1=0.2950)
  Directional -> Accuracy: 0.5814, MCC: 0.0300, F1: 0.2500

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for proper time series validation for BRK-A. Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for proper time series validation for BSAC. Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.62215 | val 0.78185
  Epoch 011 - train 0.59884 | val 0.79813
  Classification -> best τ=0.505 (val F1=0.1871)
  Directional -> Accuracy: 0.4306, MCC: 0.0000, F1: 0.6019

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.64661 | val 1.12263
  Epoch 011 - train 0.62446 | val 1.32050
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.68375 | val 1.01097
  Epoch 011 - train 0.67450 | val 1.19998
  Classification -> best τ=0.475 (val F1=0.0335)
  Directional -> Accuracy: 0.5667, MCC: 0.1345, F1: 0.5938

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.59947 | val 1.59500
  Epoch 011 - train 0.59994 | val 2.04360
  Classification -> best τ=0.510 (val F1=0.2135)
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.6364

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.65054 | val 0.59049
  Epoch 020 - train 0.57646 | val 0.59254
  Classification -> best τ=0.570 (val F1=0.4382)
  Directional -> Accuracy: 0.5873, MCC: 0.2008, F1: 0.6579

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.63074 | val 1.05713
  Epoch 014 - train 0.61955 | val 1.10194
  Classification -> best τ=0.555 (val F1=0.2379)
  Directional -> Accuracy: 0.4909, MCC: -0.0575, F1: 0.1250

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.62582 | val 0.85817
  Epoch 015 - train 0.59926 | val 0.97041
  Classification -> best τ=0.725 (val F1=0.2109)
  Directional -> Accuracy: 0.4583, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.66872 | val 1.55590
  Epoch 011 - train 0.66422 | val 1.39946
  Classification -> best τ=0.530 (val F1=0.0821)
  Directional -> Accuracy: 0.4032, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.66057 | val 1.46501
  Epoch 011 - train 0.61226 | val 1.42525
  Classification -> best τ=0.520 (val F1=0.2486)
  Directional -> Accuracy: 0.3974, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.65906 | val 1.29377
  Epoch 011 - train 0.61471 | val 1.23281
  Classification -> best τ=0.510 (val F1=0.1077)
  Directional -> Accuracy: 0.4853, MCC: 0.1028, F1: 0.3396

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 6). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.61821 | val 1.71093
  Epoch 011 - train 0.59392 | val 1.51079
  Classification -> best τ=0.510 (val F1=0.0347)
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.59031 | val 1.04791
  Epoch 011 - train 0.61427 | val 1.23167
  Classification -> best τ=0.510 (val F1=0.1266)
  Directional -> Accuracy: 0.3800, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.65694 | val 0.77455
  Epoch 011 - train 0.64126 | val 0.79447
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.63550 | val 0.86531
  Epoch 011 - train 0.61692 | val 0.87333
  Classification -> best τ=0.540 (val F1=0.2061)
  Directional -> Accuracy: 0.6333, MCC: 0.2120, F1: 0.7317

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.61827 | val 0.81387
  Epoch 011 - train 0.62916 | val 0.92386
  Classification -> best τ=0.460 (val F1=0.1757)
  Directional -> Accuracy: 0.5294, MCC: 0.0908, F1: 0.6279

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.64394 | val 0.67592
  Epoch 018 - train 0.58503 | val 0.72725
  Classification -> best τ=0.500 (val F1=0.5488)
  Directional -> Accuracy: 0.5690, MCC: 0.2157, F1: 0.4681

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.59771 | val 0.68617
  Epoch 020 - train 0.54801 | val 0.66053
  Classification -> best τ=0.595 (val F1=0.3977)
  Directional -> Accuracy: 0.5500, MCC: 0.0428, F1: 0.4000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.60608 | val 0.70649
  Epoch 011 - train 0.62622 | val 0.71650
  Classification -> best τ=0.505 (val F1=0.1612)
  Directional -> Accuracy: 0.5333, MCC: -0.2182, F1: 0.6957

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.62880 | val 0.86124
  Epoch 015 - train 0.60614 | val 0.92610
  Classification -> best τ=0.425 (val F1=0.2426)
  Directional -> Accuracy: 0.5763, MCC: 0.1903, F1: 0.5455

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.63383 | val 0.68745
  Epoch 018 - train 0.55381 | val 0.89588
  Classification -> best τ=0.550 (val F1=0.2169)
  Directional -> Accuracy: 0.5556, MCC: 0.1556, F1: 0.3750

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.62397 | val 0.73283
  Epoch 011 - train 0.66234 | val 0.75510
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.61541 | val 0.67569
  Epoch 015 - train 0.62951 | val 0.80654
  Classification -> best τ=0.525 (val F1=0.0744)
  Directional -> Accuracy: 0.5435, MCC: 0.0000, F1: 0.7042

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.64108 | val 0.78529
  Epoch 015 - train 0.57829 | val 0.96202
  Classification -> best τ=0.470 (val F1=0.3795)
  Directional -> Accuracy: 0.5094, MCC: 0.0000, F1: 0.6750

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.62910 | val 0.81847
  Epoch 016 - train 0.59126 | val 0.86437
  Classification -> best τ=0.345 (val F1=0.3351)
  Directional -> Accuracy: 0.5467, MCC: 0.1288, F1: 0.5143

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.64447 | val 0.70601
  Epoch 011 - train 0.56032 | val 0.70077
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4878, MCC: 0.0000, F1: 0.6557

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.60815 | val 0.98796
  Epoch 011 - train 0.59263 | val 0.93727
  Classification -> best τ=0.535 (val F1=0.1954)
  Directional -> Accuracy: 0.4348, MCC: -0.1006, F1: 0.5806

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.60493 | val 0.84933
  Epoch 011 - train 0.63985 | val 0.84662
  Classification -> best τ=0.480 (val F1=0.2891)
  Directional -> Accuracy: 0.6667, MCC: 0.3681, F1: 0.6667

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.60539 | val 0.68332
  Epoch 016 - train 0.54908 | val 0.70633
  Classification -> best τ=0.540 (val F1=0.2564)
  Directional -> Accuracy: 0.4889, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.60035 | val 1.69937
  Epoch 011 - train 0.58803 | val 1.98716
  Classification -> best τ=0.480 (val F1=0.0615)
  Directional -> Accuracy: 0.5254, MCC: 0.2200, F1: 0.6667

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.61618 | val 1.73173
  Epoch 013 - train 0.59844 | val 1.70109
  Classification -> best τ=0.510 (val F1=0.2035)
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.7595

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 6). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.60327 | val 0.65510
  Epoch 020 - train 0.54905 | val 0.68239
  Classification -> best τ=0.330 (val F1=0.4411)
  Directional -> Accuracy: 0.5238, MCC: 0.1021, F1: 0.4737

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.58274 | val 0.77914
  Epoch 011 - train 0.58771 | val 0.81483
  Classification -> best τ=0.485 (val F1=0.1667)
  Directional -> Accuracy: 0.4878, MCC: -0.0655, F1: 0.6316

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 6). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.61401 | val 1.50538
  Epoch 011 - train 0.59877 | val 1.82015
  Classification -> best τ=0.465 (val F1=0.1282)
  Directional -> Accuracy: 0.5195, MCC: 0.1162, F1: 0.6783

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.66373 | val 0.84551
  Epoch 011 - train 0.62227 | val 0.87523
  Classification -> best τ=0.520 (val F1=0.2400)
  Directional -> Accuracy: 0.5918, MCC: 0.1883, F1: 0.5000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.61198 | val 0.78808
  Epoch 011 - train 0.57855 | val 0.80701
  Classification -> best τ=0.520 (val F1=0.0236)
  Directional -> Accuracy: 0.5745, MCC: 0.1828, F1: 0.5652

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.61080 | val 0.89033
  Epoch 011 - train 0.57468 | val 0.91086
  Classification -> best τ=0.560 (val F1=0.1370)
  Directional -> Accuracy: 0.5238, MCC: 0.1766, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.67316 | val 0.73890
  Epoch 011 - train 0.66331 | val 0.76069
  Classification -> best τ=0.550 (val F1=0.1588)
  Directional -> Accuracy: 0.4483, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.61582 | val 0.91327
  Epoch 011 - train 0.61049 | val 0.96538
  Classification -> best τ=0.540 (val F1=0.2470)
  Directional -> Accuracy: 0.4915, MCC: 0.0000, F1: 0.6591

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.63981 | val 0.83802
  Epoch 011 - train 0.61963 | val 0.94432
  Classification -> best τ=0.470 (val F1=0.0136)
  Directional -> Accuracy: 0.5893, MCC: 0.1666, F1: 0.6849

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.60642 | val 1.44826
  Epoch 011 - train 0.60072 | val 1.31047
  Classification -> best τ=0.545 (val F1=0.1531)
  Directional -> Accuracy: 0.5000, MCC: 0.0190, F1: 0.3556

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.67164 | val 0.76755

[I 2026-02-24 23:22:56,979] Trial 56 finished with value: 0.18803119010853395 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 5, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 0.0009416291862502937, 'weight_decay': 0.0001761690141225876, 'lr_patience': 7, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 1.2672935313823381, 'early_stopping_min_delta': 0.00531856127333622}. Best is trial 32 with value: 0.2908549754956826.

  Epoch 017 - train 0.61971 | val 0.75944
  Classification -> best τ=0.510 (val F1=0.3344)
  Directional -> Accuracy: 0.5079, MCC: 0.1726, F1: 0.6593

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.18803119010853395
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 15
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.64770 | val 0.77732
  Epoch 020 - train 0.64215 | val 0.81514
  Classification -> best τ=0.540 (val F1=0.1989)
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.65943 | val 0.68089
  Epoch 020 - train 0.59672 | val 0.69173
  Classification -> best τ=0.455 (val F1=0.0995)
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 16). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.69255 | val 0.67870
  Epoch 020 - train 0.64112 | val 0.70748
  Classification -> best τ=0.540 (val F1=0.2782)
  Directional -> Accuracy: 0.4375, MCC: -0.0937, F1: 0.2286

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.66172 | val 0.70118
  Epoch 020 - train 0.64299 | val 0.70104
  Classification -> best τ=0.485 (val F1=0.1304)
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.65978 | val 0.66037
  Epoch 020 - train 0.59272 | val 0.73836
  Classification -> best τ=0.370 (val F1=0.3592)
  Directional -> Accuracy: 0.5577, MCC: 0.1512, F1: 0.7089

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.63950 | val 0.72969
  Epoch 020 - train 0.57702 | val 0.74074
  Classification -> best τ=0.510 (val F1=0.2485)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.2500

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.68038 | val 0.71254
  Epoch 020 - train 0.68072 | val 0.69091
  Classification -> best τ=0.540 (val F1=0.2274)
  Directional -> Accuracy: 0.6000, MCC: 0.0733, F1: 0.2222

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 16). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.67323 | val 1.79329
  Epoch 020 - train 0.56484 | val 2.74484
  Classification -> best τ=0.535 (val F1=0.2039)
  Directional -> Accuracy: 0.4222, MCC: -0.0732, F1: 0.5357

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.67386 | val 0.68641
  Epoch 020 - train 0.63368 | val 0.69959
  Classification -> best τ=0.490 (val F1=0.2259)
  Directional -> Accuracy: 0.5366, MCC: -0.1712, F1: 0.0952

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 16). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 16). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.65191 | val 0.74047
  Epoch 020 - train 0.62413 | val 0.74993
  Classification -> best τ=0.440 (val F1=0.2095)
  Directional -> Accuracy: 0.4366, MCC: -0.0388, F1: 0.5833

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.64487 | val 0.70577
  Epoch 020 - train 0.61564 | val 0.78040
  Classification -> best τ=0.410 (val F1=0.1090)
  Directional -> Accuracy: 0.4314, MCC: -0.1257, F1: 0.4912

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.68214 | val 0.71882
  Epoch 020 - train 0.63897 | val 0.82220
  Classification -> best τ=0.435 (val F1=0.2271)
  Directional -> Accuracy: 0.5085, MCC: 0.0000, F1: 0.6742

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.63772 | val 0.84782
  Epoch 020 - train 0.55189 | val 1.00360
  Classification -> best τ=0.505 (val F1=0.2103)
  Directional -> Accuracy: 0.4884, MCC: 0.0644, F1: 0.5926

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.70412 | val 0.63886
  Epoch 020 - train 0.66038 | val 0.62545
  Classification -> best τ=0.390 (val F1=0.3464)
  Directional -> Accuracy: 0.5902, MCC: 0.1797, F1: 0.6154

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.65488 | val 0.74516
  Epoch 020 - train 0.62939 | val 0.70112
  Classification -> best τ=0.480 (val F1=0.1150)
  Directional -> Accuracy: 0.5283, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.62852 | val 0.74364
  Epoch 020 - train 0.62035 | val 0.75574
  Classification -> best τ=0.685 (val F1=0.3090)
  Directional -> Accuracy: 0.5143, MCC: 0.0653, F1: 0.4333

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.67081 | val 0.83511
  Epoch 020 - train 0.65409 | val 0.97963
  Classification -> best τ=0.435 (val F1=0.1346)
  Directional -> Accuracy: 0.6333, MCC: 0.1344, F1: 0.7609

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.66235 | val 0.95148
  Epoch 020 - train 0.65767 | val 1.29260
  Classification -> best τ=0.455 (val F1=0.0951)
  Directional -> Accuracy: 0.5789, MCC: 0.1396, F1: 0.6364

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.64192 | val 0.68773
  Epoch 020 - train 0.65253 | val 0.97292
  Classification -> best τ=0.525 (val F1=0.1446)
  Directional -> Accuracy: 0.4242, MCC: 0.0336, F1: 0.0952

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 16). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.65794 | val 0.70026
  Epoch 020 - train 0.60284 | val 0.78568
  Classification -> best τ=0.475 (val F1=0.2716)
  Directional -> Accuracy: 0.5132, MCC: 0.1449, F1: 0.2449

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.68419 | val 0.81217
  Epoch 020 - train 0.62865 | val 1.12109
  Classification -> best τ=0.460 (val F1=0.1629)
  Directional -> Accuracy: 0.5000, MCC: 0.1183, F1: 0.4545

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.69708 | val 0.76268
  Epoch 020 - train 0.66441 | val 0.88334
  Classification -> best τ=0.475 (val F1=0.1011)
  Directional -> Accuracy: 0.6364, MCC: 0.2732, F1: 0.6250

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.63129 | val 0.72846
  Epoch 020 - train 0.58862 | val 0.75135
  Classification -> best τ=0.615 (val F1=0.3198)
  Directional -> Accuracy: 0.5172, MCC: 0.1165, F1: 0.4167

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.67737 | val 0.68803
  Epoch 020 - train 0.68386 | val 0.82105
  Classification -> best τ=0.450 (val F1=0.2093)
  Directional -> Accuracy: 0.5303, MCC: 0.1437, F1: 0.6437

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.66607 | val 0.64697
  Epoch 020 - train 0.58315 | val 0.74750
  Classification -> best τ=0.495 (val F1=0.4576)
  Directional -> Accuracy: 0.5357, MCC: 0.1728, F1: 0.3810

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.63108 | val 0.77480
  Epoch 020 - train 0.60783 | val 1.26075
  Classification -> best τ=0.535 (val F1=0.1754)
  Directional -> Accuracy: 0.5745, MCC: 0.0318, F1: 0.0909

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.67374 | val 0.68839
  Epoch 020 - train 0.64596 | val 0.70067
  Classification -> best τ=0.640 (val F1=0.1309)
  Directional -> Accuracy: 0.4651, MCC: -0.0295, F1: 0.4390

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.65589 | val 0.74606
  Epoch 020 - train 0.62273 | val 0.96303
  Classification -> best τ=0.485 (val F1=0.2836)
  Directional -> Accuracy: 0.4483, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.68135 | val 0.74199
  Epoch 020 - train 0.60299 | val 0.68714
  Classification -> best τ=0.550 (val F1=0.3974)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.7077

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.62370 | val 1.19196
  Epoch 020 - train 0.64356 | val 2.10319
  Classification -> best τ=0.590 (val F1=0.1869)
  Directional -> Accuracy: 0.5227, MCC: 0.0479, F1: 0.4324

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.68625 | val 0.76854
  Epoch 020 - train 0.65724 | val 0.77963
  Classification -> best τ=0.475 (val F1=0.3168)
  Directional -> Accuracy: 0.5682, MCC: 0.1751, F1: 0.5128

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.62582 | val 0.74189
  Epoch 020 - train 0.60412 | val 0.81520
  Classification -> best τ=0.475 (val F1=0.3245)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.66850 | val 0.66270
  Epoch 020 - train 0.62125 | val 0.79104
  Classification -> best τ=0.385 (val F1=0.3259)
  Directional -> Accuracy: 0.5000, MCC: 0.0558, F1: 0.4308

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.59853 | val 0.71194
  Epoch 020 - train 0.63107 | val 0.71787
  Classification -> best τ=0.520 (val F1=0.1724)
  Directional -> Accuracy: 0.5263, MCC: 0.0778, F1: 0.6538

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.67373 | val 0.89262
  Epoch 020 - train 0.61700 | val 0.95631
  Classification -> best τ=0.425 (val F1=0.2017)
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.6364

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.66029 | val 0.82818
  Epoch 020 - train 0.65090 | val 0.83817
  Classification -> best τ=0.415 (val F1=0.3767)
  Directional -> Accuracy: 0.6269, MCC: 0.2370, F1: 0.6753

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.69134 | val 0.71115
  Epoch 020 - train 0.60527 | val 0.74608
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.63906 | val 0.83115
  Epoch 020 - train 0.60911 | val 0.70603
  Classification -> best τ=0.545 (val F1=0.1738)
  Directional -> Accuracy: 0.4386, MCC: -0.1161, F1: 0.4667

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.60825 | val 0.85808
  Epoch 020 - train 0.55287 | val 0.72126
  Classification -> best τ=0.450 (val F1=0.3296)
  Directional -> Accuracy: 0.5745, MCC: 0.0806, F1: 0.6667

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 16). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.64389 | val 1.01803
  Epoch 020 - train 0.59281 | val 1.95231
  Classification -> best τ=0.525 (val F1=0.3072)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.63493 | val 0.78990
  Epoch 020 - train 0.59224 | val 0.88319
  Classification -> best τ=0.430 (val F1=0.0406)
  Directional -> Accuracy: 0.5128, MCC: -0.0188, F1: 0.6275

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 16). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.66269 | val 0.74229
  Epoch 020 - train 0.60151 | val 0.85289
  Classification -> best τ=0.410 (val F1=0.3475)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.67606 | val 0.69837
  Epoch 020 - train 0.65388 | val 0.69792
  Classification -> best τ=0.415 (val F1=0.3236)
  Directional -> Accuracy: 0.4894, MCC: -0.0617, F1: 0.6364

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.67001 | val 0.96616
  Epoch 020 - train 0.61986 | val 1.11415
  Classification -> best τ=0.465 (val F1=0.2949)
  Directional -> Accuracy: 0.5778, MCC: 0.1206, F1: 0.6667

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.62372 | val 0.85561
  Epoch 020 - train 0.61639 | val 0.89011
  Classification -> best τ=0.620 (val F1=0.0675)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.67346 | val 0.81399
  Epoch 020 - train 0.65037 | val 1.22848
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5439, MCC: 0.0000, F1: 0.7045

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.64167 | val 0.99859
  Epoch 020 - train 0.59996 | val 1.45352
  Classification -> best τ=0.495 (val F1=0.2554)
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.65935 | val 1.05895
  Epoch 020 - train 0.62560 | val 1.32274
  Classification -> best τ=0.420 (val F1=0.1985)
  Directional -> Accuracy: 0.5926, MCC: 0.2935, F1: 0.7179

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.64578 | val 0.74807
  Epoch 020 - train 0.64593 | val 0.88577
  Classification -> best τ=0.605 (val F1=0.0571)
  Directional -> Accuracy: 0.4561, MCC: -0.0929, F1: 0.5079

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.65086 | val 0.75887

[I 2026-02-24 23:24:19,681] Trial 57 finished with value: 0.21430333913172106 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 15, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.7000000000000001, 'batch_size': 64, 'learning_rate': 0.004870095843307631, 'weight_decay': 0.0006818167400106235, 'lr_patience': 7, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 1.1035448420196836, 'early_stopping_min_delta': 0.005816231673548658}. Best is trial 32 with value: 0.2908549754956826.

  Epoch 020 - train 0.61806 | val 1.05072
  Classification -> best τ=0.555 (val F1=0.0325)
  Directional -> Accuracy: 0.4355, MCC: -0.1260, F1: 0.4615

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.21430333913172106
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: classification
Sequence length: 15
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.70830 | val 0.71652
  Epoch 011 - train 0.70429 | val 0.71764
  Classification -> best τ=0.515 (val F1=0.0577)
  Directional -> Accuracy: 0.5455, MCC: 0.0729, F1: 0.4615

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.71821 | val 0.71573
  Epoch 011 - train 0.71599 | val 0.71926
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 16). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.73865 | val 0.72719
  Epoch 011 - train 0.73387 | val 0.73178
  Classification -> best τ=0.495 (val F1=0.0087)
  Directional -> Accuracy: 0.5208, MCC: -0.0247, F1: 0.6567

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.75153 | val 0.79889
  Epoch 011 - train 0.75362 | val 0.79825
  Classification -> best τ=0.550 (val F1=0.0087)
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.70671 | val 0.67590
  Epoch 016 - train 0.70662 | val 0.67758
  Classification -> best τ=0.615 (val F1=0.2381)
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.72752 | val 0.72671
  Epoch 011 - train 0.71283 | val 0.74674
  Classification -> best τ=0.480 (val F1=0.2079)
  Directional -> Accuracy: 0.5208, MCC: 0.0417, F1: 0.5306

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.71291 | val 0.71384
  Epoch 011 - train 0.70423 | val 0.71451
  Classification -> best τ=0.490 (val F1=0.1429)
  Directional -> Accuracy: 0.5714, MCC: -0.0754, F1: 0.0625

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 16). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.69433 | val 0.76328
  Epoch 011 - train 0.69188 | val 0.76838
  Classification -> best τ=0.545 (val F1=0.1429)
  Directional -> Accuracy: 0.6000, MCC: 0.1297, F1: 0.3077

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.71183 | val 0.71302
  Epoch 011 - train 0.71649 | val 0.71735
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3659, MCC: 0.0000, F1: 0.5357

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 16). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 16). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.72023 | val 0.74556
  Epoch 011 - train 0.72855 | val 0.74753
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4366, MCC: 0.0000, F1: 0.6078

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.72238 | val 0.75238
  Epoch 011 - train 0.71271 | val 0.75605
  Classification -> best τ=0.475 (val F1=0.0599)
  Directional -> Accuracy: 0.4902, MCC: 0.0466, F1: 0.6286

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.71193 | val 0.70789
  Epoch 011 - train 0.74653 | val 0.71000
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5085, MCC: 0.0000, F1: 0.6742

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.68861 | val 0.70902
  Epoch 011 - train 0.73377 | val 0.70696
  Classification -> best τ=0.475 (val F1=0.1700)
  Directional -> Accuracy: 0.6047, MCC: 0.1763, F1: 0.3704

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.71189 | val 0.74224
  Epoch 011 - train 0.75118 | val 0.75114
  Classification -> best τ=0.490 (val F1=0.0935)
  Directional -> Accuracy: 0.4426, MCC: -0.1332, F1: 0.5405

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.74880 | val 0.88639
  Epoch 011 - train 0.72047 | val 0.93457
  Classification -> best τ=0.495 (val F1=0.2540)
  Directional -> Accuracy: 0.4906, MCC: -0.0392, F1: 0.3721

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.73193 | val 0.68636
  Epoch 018 - train 0.70369 | val 0.68512
  Classification -> best τ=0.425 (val F1=0.2172)
  Directional -> Accuracy: 0.4429, MCC: -0.1853, F1: 0.5714

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.74389 | val 0.74751
  Epoch 011 - train 0.72238 | val 0.75551
  Classification -> best τ=0.495 (val F1=0.1259)
  Directional -> Accuracy: 0.4667, MCC: -0.1101, F1: 0.5556

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.73717 | val 0.69510
  Epoch 011 - train 0.73838 | val 0.69518
  Classification -> best τ=0.460 (val F1=0.1208)
  Directional -> Accuracy: 0.6053, MCC: 0.0354, F1: 0.7500

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.70035 | val 0.67892
  Epoch 015 - train 0.74007 | val 0.67898
  Classification -> best τ=0.495 (val F1=0.4073)
  Directional -> Accuracy: 0.5000, MCC: -0.1797, F1: 0.6526

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 16). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.72061 | val 0.74322
  Epoch 011 - train 0.69763 | val 0.74449
  Classification -> best τ=0.490 (val F1=0.2518)
  Directional -> Accuracy: 0.5395, MCC: 0.0000, F1: 0.7009

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.71847 | val 0.69398
  Epoch 011 - train 0.71334 | val 0.69802
  Classification -> best τ=0.520 (val F1=0.2174)
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.70992 | val 0.70097
  Epoch 011 - train 0.71227 | val 0.70109
  Classification -> best τ=0.530 (val F1=0.0141)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.4000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.75033 | val 0.69764
  Epoch 011 - train 0.71633 | val 0.69871
  Classification -> best τ=0.525 (val F1=0.2272)
  Directional -> Accuracy: 0.5172, MCC: 0.0650, F1: 0.5000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.69498 | val 0.78033
  Epoch 011 - train 0.71819 | val 0.78164
  Classification -> best τ=0.535 (val F1=0.0684)
  Directional -> Accuracy: 0.5303, MCC: 0.0107, F1: 0.0606

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.73126 | val 0.69490
  Epoch 011 - train 0.70345 | val 0.69385
  Classification -> best τ=0.490 (val F1=0.0842)
  Directional -> Accuracy: 0.4464, MCC: -0.2064, F1: 0.5867

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.74098 | val 0.69285
  Epoch 011 - train 0.74000 | val 0.69319
  Classification -> best τ=0.510 (val F1=0.1754)
  Directional -> Accuracy: 0.4255, MCC: -0.2200, F1: 0.2286

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.66795 | val 0.72059
  Epoch 011 - train 0.73297 | val 0.73280
  Classification -> best τ=0.520 (val F1=0.1323)
  Directional -> Accuracy: 0.5581, MCC: 0.1467, F1: 0.5581

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.76630 | val 0.70518
  Epoch 011 - train 0.70794 | val 0.70541
  Classification -> best τ=0.505 (val F1=0.0762)
  Directional -> Accuracy: 0.5172, MCC: 0.1361, F1: 0.3333

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.71433 | val 0.68770
  Epoch 011 - train 0.75983 | val 0.68687
  Classification -> best τ=0.505 (val F1=0.1201)
  Directional -> Accuracy: 0.5714, MCC: 0.1083, F1: 0.6786

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.74130 | val 0.69469
  Epoch 011 - train 0.70795 | val 0.69694
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.73325 | val 0.69589
  Epoch 011 - train 0.69642 | val 0.69894
  Classification -> best τ=0.515 (val F1=0.0983)
  Directional -> Accuracy: 0.5000, MCC: -0.0169, F1: 0.5600

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.72404 | val 0.71904
  Epoch 011 - train 0.73890 | val 0.71991
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.72829 | val 0.71904
  Epoch 011 - train 0.72522 | val 0.71910
  Classification -> best τ=0.485 (val F1=0.0880)
  Directional -> Accuracy: 0.4730, MCC: -0.0949, F1: 0.5618

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.73696 | val 0.69611
  Epoch 011 - train 0.76449 | val 0.69739
  Classification -> best τ=0.480 (val F1=0.0543)
  Directional -> Accuracy: 0.4211, MCC: -0.2335, F1: 0.0833

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.75383 | val 0.69284
  Epoch 011 - train 0.77371 | val 0.69538
  Classification -> best τ=0.510 (val F1=0.2883)
  Directional -> Accuracy: 0.5333, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.75354 | val 0.72444
  Epoch 011 - train 0.75029 | val 0.72515
  Classification -> best τ=0.470 (val F1=0.0009)
  Directional -> Accuracy: 0.5970, MCC: 0.1428, F1: 0.7216

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.72654 | val 0.69470
  Epoch 011 - train 0.74265 | val 0.69662
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.77496 | val 0.78770
  Epoch 011 - train 0.76785 | val 0.80180
  Classification -> best τ=0.470 (val F1=0.1590)
  Directional -> Accuracy: 0.4912, MCC: -0.1809, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.71414 | val 0.68346
  Epoch 011 - train 0.70010 | val 0.68367
  Classification -> best τ=0.470 (val F1=0.2057)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 16). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.68737 | val 0.69563
  Epoch 020 - train 0.75810 | val 0.67092
  Epoch 030 - train 0.70974 | val 0.66986
  Classification -> best τ=0.470 (val F1=0.4229)
  Directional -> Accuracy: 0.5750, MCC: -0.0621, F1: 0.1905

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.71105 | val 0.68338
  Epoch 011 - train 0.72075 | val 0.68289
  Classification -> best τ=0.465 (val F1=0.0793)
  Directional -> Accuracy: 0.4872, MCC: -0.2152, F1: 0.6552

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 16). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.73972 | val 0.70910
  Epoch 011 - train 0.72419 | val 0.70903
  Classification -> best τ=0.465 (val F1=0.1241)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.75610 | val 0.70264
  Epoch 011 - train 0.71715 | val 0.70683
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.73174 | val 0.69026
  Epoch 011 - train 0.72438 | val 0.69348
  Classification -> best τ=0.480 (val F1=0.3780)
  Directional -> Accuracy: 0.4222, MCC: -0.1265, F1: 0.3500

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.75095 | val 0.67291
  Epoch 020 - train 0.69621 | val 0.65711
  Epoch 026 - train 0.76310 | val 0.65635
  Classification -> best τ=0.505 (val F1=0.5238)
  Directional -> Accuracy: 0.5500, MCC: 0.3669, F1: 0.6087

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.71920 | val 0.88487
  Epoch 011 - train 0.71581 | val 0.89843
  Classification -> best τ=0.450 (val F1=0.0698)
  Directional -> Accuracy: 0.6316, MCC: 0.3191, F1: 0.5714

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.72757 | val 0.69280
  Epoch 011 - train 0.71198 | val 0.69276
  Classification -> best τ=0.480 (val F1=0.1512)
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.72644 | val 0.68851
  Epoch 011 - train 0.74393 | val 0.68958
  Classification -> best τ=0.530 (val F1=0.0602)
  Directional -> Accuracy: 0.5000, MCC: 0.1324, F1: 0.0690

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.74412 | val 0.71852
  Epoch 011 - train 0.73251 | val 0.71909
  Classification -> best τ=0.540 (val F1=0.0420)
  Directional -> Accuracy: 0.3684, MCC: -0.2744, F1: 0.4375

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.70769 | val 0.71386

[I 2026-02-24 23:25:13,103] Trial 58 finished with value: 0.1323342857353802 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 15, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.8, 'batch_size': 32, 'learning_rate': 1.1336889888402259e-06, 'weight_decay': 0.0002590442218066606, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 1.5255329781404412, 'early_stopping_min_delta': 0.00662257148855534}. Best is trial 32 with value: 0.2908549754956826.

  Epoch 014 - train 0.71467 | val 0.72089
  Classification -> best τ=0.475 (val F1=0.2485)
  Directional -> Accuracy: 0.5161, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.1323342857353802
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 10
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.67324 | val 1.00318
  Epoch 015 - train 0.62710 | val 0.86158
  Classification -> best τ=0.530 (val F1=0.2863)
  Directional -> Accuracy: 0.5385, MCC: 0.0047, F1: 0.2174

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.62355 | val 0.68959
  Epoch 015 - train 0.62129 | val 0.75871
  Classification -> best τ=0.565 (val F1=0.2346)
  Directional -> Accuracy: 0.6170, MCC: 0.2097, F1: 0.7000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 11). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.62783 | val 1.42121
  Epoch 011 - train 0.60530 | val 1.74153
  Classification -> best τ=0.440 (val F1=0.3574)
  Directional -> Accuracy: 0.5102, MCC: -0.1358, F1: 0.6757

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.64854 | val 0.78927
  Epoch 011 - train 0.64430 | val 0.74527
  Classification -> best τ=0.525 (val F1=0.1217)
  Directional -> Accuracy: 0.5395, MCC: 0.0000, F1: 0.7009

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.56577 | val 0.81872
  Epoch 014 - train 0.51923 | val 1.21956
  Classification -> best τ=0.515 (val F1=0.3629)
  Directional -> Accuracy: 0.5769, MCC: 0.1543, F1: 0.5926

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.50640 | val 0.85839
  Epoch 012 - train 0.49300 | val 1.29256
  Classification -> best τ=0.630 (val F1=0.2604)
  Directional -> Accuracy: 0.5510, MCC: 0.2502, F1: 0.2143

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.65304 | val 0.85938
  Epoch 018 - train 0.57140 | val 0.72626
  Classification -> best τ=0.550 (val F1=0.2483)
  Directional -> Accuracy: 0.5493, MCC: 0.0574, F1: 0.4286

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 11). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.63957 | val 4.09981
  Epoch 011 - train 0.53004 | val 3.70142
  Classification -> best τ=0.655 (val F1=0.3315)
  Directional -> Accuracy: 0.5652, MCC: -0.1251, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.63490 | val 0.72391
  Epoch 020 - train 0.49804 | val 1.21799
  Classification -> best τ=0.610 (val F1=0.5367)
  Directional -> Accuracy: 0.5000, MCC: -0.1010, F1: 0.2759

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for proper time series validation for BRK-A. Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for proper time series validation for BSAC. Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.63310 | val 0.90627
  Epoch 012 - train 0.60545 | val 0.92557
  Classification -> best τ=0.245 (val F1=0.0812)
  Directional -> Accuracy: 0.4366, MCC: 0.0000, F1: 0.6078

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.63996 | val 1.42151
  Epoch 013 - train 0.59078 | val 1.36544
  Classification -> best τ=0.505 (val F1=0.3644)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.61328 | val 0.78287
  Epoch 015 - train 0.57286 | val 0.71871
  Classification -> best τ=0.575 (val F1=0.1448)
  Directional -> Accuracy: 0.5085, MCC: 0.0032, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.58776 | val 2.04673
  Epoch 012 - train 0.58269 | val 2.14966
  Classification -> best τ=0.525 (val F1=0.3087)
  Directional -> Accuracy: 0.5227, MCC: 0.0415, F1: 0.4878

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.67996 | val 0.90041
  Epoch 013 - train 0.64506 | val 1.29420
  Classification -> best τ=0.320 (val F1=0.3348)
  Directional -> Accuracy: 0.6290, MCC: 0.2649, F1: 0.6667

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.62268 | val 1.03857
  Epoch 020 - train 0.48674 | val 2.85257
  Classification -> best τ=0.675 (val F1=0.2816)
  Directional -> Accuracy: 0.5926, MCC: 0.2490, F1: 0.3125

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.63951 | val 0.90837
  Epoch 011 - train 0.57264 | val 0.95849
  Classification -> best τ=0.550 (val F1=0.0920)
  Directional -> Accuracy: 0.5352, MCC: 0.1168, F1: 0.4211

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.67396 | val 1.53241
  Epoch 013 - train 0.62426 | val 1.64833
  Classification -> best τ=0.580 (val F1=0.2440)
  Directional -> Accuracy: 0.3770, MCC: -0.1603, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.66722 | val 1.32359
  Epoch 012 - train 0.62630 | val 1.11420
  Classification -> best τ=0.270 (val F1=0.1927)
  Directional -> Accuracy: 0.4286, MCC: 0.1609, F1: 0.1200

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.64140 | val 0.71091
  Epoch 013 - train 0.64861 | val 0.70901
  Classification -> best τ=0.635 (val F1=0.3572)
  Directional -> Accuracy: 0.4179, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 11). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.64079 | val 0.67397
  Epoch 016 - train 0.58145 | val 0.68421
  Classification -> best τ=0.430 (val F1=0.2887)
  Directional -> Accuracy: 0.4675, MCC: 0.0289, F1: 0.1277

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.55969 | val 1.53489
  Epoch 013 - train 0.50714 | val 1.31193
  Classification -> best τ=0.485 (val F1=0.2715)
  Directional -> Accuracy: 0.5306, MCC: -0.1056, F1: 0.6667

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.67111 | val 1.21757
  Epoch 012 - train 0.64773 | val 1.36439
  Classification -> best τ=0.630 (val F1=0.1026)
  Directional -> Accuracy: 0.4925, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.63396 | val 1.00949
  Epoch 011 - train 0.65130 | val 1.15735
  Classification -> best τ=0.600 (val F1=0.3228)
  Directional -> Accuracy: 0.5424, MCC: 0.0278, F1: 0.6400

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.61470 | val 0.78090
  Epoch 013 - train 0.59067 | val 1.37880
  Classification -> best τ=0.340 (val F1=0.1628)
  Directional -> Accuracy: 0.4627, MCC: -0.0819, F1: 0.6250

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.61198 | val 0.78398
  Epoch 011 - train 0.59075 | val 0.97178
  Classification -> best τ=0.640 (val F1=0.2485)
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.56661 | val 0.94771
  Epoch 014 - train 0.48623 | val 1.72886
  Classification -> best τ=0.510 (val F1=0.2647)
  Directional -> Accuracy: 0.5208, MCC: 0.0493, F1: 0.4889

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.62142 | val 1.51043
  Epoch 011 - train 0.60297 | val 1.68361
  Classification -> best τ=0.615 (val F1=0.1902)
  Directional -> Accuracy: 0.5455, MCC: 0.1282, F1: 0.5455

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.62262 | val 0.96653
  Epoch 012 - train 0.59615 | val 1.05742
  Classification -> best τ=0.350 (val F1=0.1663)
  Directional -> Accuracy: 0.5517, MCC: 0.0000, F1: 0.7111

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.60885 | val 0.78711
  Epoch 012 - train 0.67634 | val 0.78061
  Classification -> best τ=0.620 (val F1=0.3948)
  Directional -> Accuracy: 0.5116, MCC: 0.0864, F1: 0.3226

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.63481 | val 1.21823
  Epoch 011 - train 0.59874 | val 1.18153
  Classification -> best τ=0.465 (val F1=0.0892)
  Directional -> Accuracy: 0.4667, MCC: -0.2109, F1: 0.6364

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.57847 | val 0.78427
  Epoch 015 - train 0.53560 | val 0.88733
  Classification -> best τ=0.630 (val F1=0.1612)
  Directional -> Accuracy: 0.4889, MCC: -0.2017, F1: 0.6567

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.64187 | val 0.73821
  Epoch 011 - train 0.58364 | val 0.87366
  Classification -> best τ=0.485 (val F1=0.4485)
  Directional -> Accuracy: 0.4231, MCC: -0.1519, F1: 0.2857

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.61442 | val 0.92279
  Epoch 012 - train 0.61391 | val 0.95023
  Classification -> best τ=0.400 (val F1=0.2916)
  Directional -> Accuracy: 0.5000, MCC: 0.0558, F1: 0.4308

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.64389 | val 0.70360
  Epoch 011 - train 0.66377 | val 0.72082
  Classification -> best τ=0.510 (val F1=0.2509)
  Directional -> Accuracy: 0.5000, MCC: 0.0568, F1: 0.6296

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.59281 | val 1.34937
  Epoch 012 - train 0.51302 | val 2.97953
  Classification -> best τ=0.265 (val F1=0.3201)
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.6364

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.65921 | val 0.70763
  Epoch 012 - train 0.61037 | val 0.74124
  Classification -> best τ=0.225 (val F1=0.3342)
  Directional -> Accuracy: 0.6471, MCC: 0.3019, F1: 0.6667

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.54499 | val 0.86559
  Epoch 011 - train 0.53345 | val 1.18965
  Classification -> best τ=0.380 (val F1=0.2852)
  Directional -> Accuracy: 0.5909, MCC: 0.2041, F1: 0.6667

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.60570 | val 0.89799
  Epoch 012 - train 0.59308 | val 0.98039
  Classification -> best τ=0.495 (val F1=0.3529)
  Directional -> Accuracy: 0.5345, MCC: 0.0235, F1: 0.1818

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.63143 | val 1.17423
  Epoch 011 - train 0.57580 | val 1.35181
  Classification -> best τ=0.285 (val F1=0.1540)
  Directional -> Accuracy: 0.3958, MCC: 0.0222, F1: 0.1212

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 11). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.65388 | val 0.75430
  Epoch 012 - train 0.57207 | val 0.79741
  Classification -> best τ=0.480 (val F1=0.3004)
  Directional -> Accuracy: 0.4878, MCC: 0.1241, F1: 0.5116

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.61600 | val 0.87902
  Epoch 011 - train 0.57290 | val 0.92340
  Classification -> best τ=0.555 (val F1=0.1917)
  Directional -> Accuracy: 0.4750, MCC: 0.0000, F1: 0.0000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 11). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.62686 | val 1.94297
  Epoch 014 - train 0.63425 | val 1.59005
  Classification -> best τ=0.210 (val F1=0.2783)
  Directional -> Accuracy: 0.5065, MCC: 0.0000, F1: 0.6724

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.57885 | val 0.87014
  Epoch 015 - train 0.57072 | val 1.35718
  Classification -> best τ=0.445 (val F1=0.1435)
  Directional -> Accuracy: 0.4792, MCC: -0.0861, F1: 0.6377

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.53470 | val 1.91457
  Epoch 011 - train 0.52206 | val 2.11323
  Classification -> best τ=0.560 (val F1=0.0428)
  Directional -> Accuracy: 0.6087, MCC: 0.1953, F1: 0.6667

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.52048 | val 1.33352
  Epoch 011 - train 0.59048 | val 1.39513
  Classification -> best τ=0.755 (val F1=0.5214)
  Directional -> Accuracy: 0.6341, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.66378 | val 1.14497
  Epoch 012 - train 0.67406 | val 1.21283
  Classification -> best τ=0.465 (val F1=0.2881)
  Directional -> Accuracy: 0.6491, MCC: 0.3661, F1: 0.5833

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.62864 | val 2.60713
  Epoch 011 - train 0.62579 | val 2.13355
  Classification -> best τ=0.475 (val F1=0.3172)
  Directional -> Accuracy: 0.4828, MCC: 0.0000, F1: 0.6512

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.65448 | val 1.06848
  Epoch 011 - train 0.62894 | val 1.27447
  Classification -> best τ=0.435 (val F1=0.2494)
  Directional -> Accuracy: 0.4727, MCC: -0.2274, F1: 0.6420

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.63018 | val 0.99621
  Epoch 011 - train 0.59339 | val 1.14316
  Classification -> best τ=0.470 (val F1=0.1153)
  Directional -> Accuracy: 0.5172, MCC: 0.0000, F1: 0.6818

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.59959 | val 1.29461

[I 2026-02-24 23:26:11,841] Trial 59 finished with value: 0.2578380157469924 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 10, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.6000000000000001, 'batch_size': 32, 'learning_rate': 0.007815581503930932, 'weight_decay': 2.0460475312900334e-05, 'lr_patience': 7, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 1.2273104534542996, 'early_stopping_min_delta': 0.007789351375323102}. Best is trial 32 with value: 0.2908549754956826.

  Epoch 013 - train 0.61491 | val 1.75882
  Classification -> best τ=0.540 (val F1=0.2024)
  Directional -> Accuracy: 0.5556, MCC: 0.1019, F1: 0.3636

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2578380157469924
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 15
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.70900 | val 0.68230
  Epoch 020 - train 0.70348 | val 0.71229
  Classification -> best τ=0.455 (val F1=0.1565)
  Directional -> Accuracy: 0.5455, MCC: 0.0353, F1: 0.2222

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.67952 | val 0.68972
  Epoch 020 - train 0.68929 | val 0.68772
  Classification -> best τ=0.490 (val F1=0.2756)
  Directional -> Accuracy: 0.5652, MCC: 0.0510, F1: 0.6970

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 16). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.72509 | val 0.73226
  Epoch 020 - train 0.71400 | val 0.79350
  Classification -> best τ=0.555 (val F1=0.1221)
  Directional -> Accuracy: 0.5208, MCC: 0.0453, F1: 0.5306

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.69560 | val 0.69461
  Epoch 020 - train 0.68647 | val 0.70627
  Classification -> best τ=0.475 (val F1=0.1976)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.67665 | val 0.68799
  Epoch 020 - train 0.68262 | val 0.67449
  Classification -> best τ=0.595 (val F1=0.4574)
  Directional -> Accuracy: 0.5962, MCC: 0.2906, F1: 0.4615

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.69933 | val 0.70199
  Epoch 020 - train 0.71116 | val 0.73227
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.70414 | val 0.70040
  Epoch 020 - train 0.69554 | val 0.71136
  Classification -> best τ=0.500 (val F1=0.1307)
  Directional -> Accuracy: 0.5143, MCC: 0.0714, F1: 0.5143

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 16). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.71407 | val 0.66257
  Epoch 020 - train 0.71251 | val 0.65184
  Classification -> best τ=0.495 (val F1=0.2786)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.71882 | val 0.71244
  Epoch 020 - train 0.70324 | val 0.75642
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3659, MCC: 0.0000, F1: 0.5357

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 16). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 16). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.68868 | val 0.72699
  Epoch 020 - train 0.67517 | val 0.75024
  Classification -> best τ=0.505 (val F1=0.2510)
  Directional -> Accuracy: 0.4366, MCC: 0.0000, F1: 0.6078

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.72063 | val 0.74288
  Epoch 020 - train 0.71940 | val 0.88509
  Classification -> best τ=0.535 (val F1=0.0889)
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.6400

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.69917 | val 0.70574
  Epoch 020 - train 0.69557 | val 0.72735
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5085, MCC: 0.0000, F1: 0.6742

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.70294 | val 0.68222
  Epoch 020 - train 0.71026 | val 0.68058
  Classification -> best τ=0.540 (val F1=0.0426)
  Directional -> Accuracy: 0.4651, MCC: -0.1185, F1: 0.3030

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.70003 | val 0.72184
  Epoch 020 - train 0.71197 | val 0.73048
  Classification -> best τ=0.500 (val F1=0.0935)
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.69328 | val 0.68881
  Epoch 020 - train 0.68562 | val 0.69772
  Classification -> best τ=0.505 (val F1=0.1584)
  Directional -> Accuracy: 0.5283, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.69511 | val 0.67463
  Epoch 020 - train 0.69515 | val 0.67761
  Classification -> best τ=0.530 (val F1=0.3138)
  Directional -> Accuracy: 0.5429, MCC: 0.0391, F1: 0.6667

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.69754 | val 0.71978
  Epoch 020 - train 0.70389 | val 0.80695
  Classification -> best τ=0.515 (val F1=0.2476)
  Directional -> Accuracy: 0.5667, MCC: 0.1619, F1: 0.5938

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.72216 | val 0.69562
  Epoch 020 - train 0.70489 | val 0.71175
  Classification -> best τ=0.490 (val F1=0.0671)
  Directional -> Accuracy: 0.5658, MCC: -0.1637, F1: 0.7227

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.68207 | val 0.70851
  Epoch 020 - train 0.69012 | val 0.72573
  Classification -> best τ=0.515 (val F1=0.0929)
  Directional -> Accuracy: 0.5606, MCC: 0.1805, F1: 0.5397

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 16). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.70045 | val 0.72729
  Epoch 020 - train 0.69596 | val 0.74759
  Classification -> best τ=0.485 (val F1=0.0181)
  Directional -> Accuracy: 0.4079, MCC: -0.1942, F1: 0.4578

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.67645 | val 0.69499
  Epoch 020 - train 0.68368 | val 0.70500
  Classification -> best τ=0.510 (val F1=0.1521)
  Directional -> Accuracy: 0.6458, MCC: 0.1556, F1: 0.7733

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.69351 | val 0.68636
  Epoch 020 - train 0.69846 | val 0.69389
  Classification -> best τ=0.500 (val F1=0.3451)
  Directional -> Accuracy: 0.4394, MCC: -0.1226, F1: 0.3934

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.71350 | val 0.69433
  Epoch 020 - train 0.71786 | val 0.68935
  Classification -> best τ=0.465 (val F1=0.1632)
  Directional -> Accuracy: 0.3621, MCC: -0.3127, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.71372 | val 0.83210
  Epoch 020 - train 0.70148 | val 0.92158
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.69256 | val 0.69328
  Epoch 020 - train 0.69485 | val 0.68868
  Classification -> best τ=0.515 (val F1=0.2097)
  Directional -> Accuracy: 0.5714, MCC: 0.2385, F1: 0.4545

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.70442 | val 0.69353
  Epoch 020 - train 0.70521 | val 0.70089
  Classification -> best τ=0.505 (val F1=0.1792)
  Directional -> Accuracy: 0.5957, MCC: 0.1280, F1: 0.3448

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.70079 | val 0.67939
  Epoch 020 - train 0.68825 | val 0.69113
  Classification -> best τ=0.570 (val F1=0.1656)
  Directional -> Accuracy: 0.4884, MCC: -0.0352, F1: 0.5417

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.70368 | val 0.68916
  Epoch 020 - train 0.69854 | val 0.67478
  Classification -> best τ=0.540 (val F1=0.3671)
  Directional -> Accuracy: 0.4310, MCC: -0.1469, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.67991 | val 0.69368
  Epoch 020 - train 0.69767 | val 0.70385
  Classification -> best τ=0.545 (val F1=0.1961)
  Directional -> Accuracy: 0.4524, MCC: -0.0464, F1: 0.2581

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.71139 | val 0.69539
  Epoch 020 - train 0.71115 | val 0.68865
  Classification -> best τ=0.520 (val F1=0.2436)
  Directional -> Accuracy: 0.4545, MCC: -0.2182, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.70655 | val 0.70135
  Epoch 020 - train 0.70615 | val 0.70211
  Classification -> best τ=0.480 (val F1=0.1593)
  Directional -> Accuracy: 0.5682, MCC: 0.1021, F1: 0.6885

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.71106 | val 0.68971
  Epoch 020 - train 0.68786 | val 0.69159
  Classification -> best τ=0.495 (val F1=0.2476)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.71030 | val 0.68131
  Epoch 020 - train 0.68595 | val 0.67777
  Classification -> best τ=0.425 (val F1=0.2350)
  Directional -> Accuracy: 0.5811, MCC: 0.1883, F1: 0.5753

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.72689 | val 0.68953
  Epoch 020 - train 0.71779 | val 0.70248
  Classification -> best τ=0.500 (val F1=0.4045)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.5366

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.70556 | val 0.69177
  Epoch 020 - train 0.70031 | val 0.70060
  Classification -> best τ=0.495 (val F1=0.1899)
  Directional -> Accuracy: 0.5333, MCC: 0.0262, F1: 0.2222

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.68300 | val 0.69038
  Epoch 020 - train 0.68180 | val 0.69580
  Classification -> best τ=0.495 (val F1=0.2264)
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.70167 | val 0.68737
  Epoch 020 - train 0.70010 | val 0.67738
  Classification -> best τ=0.460 (val F1=0.4534)
  Directional -> Accuracy: 0.5116, MCC: 0.0162, F1: 0.5882

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.70604 | val 0.69547
  Epoch 020 - train 0.70447 | val 0.70081
  Classification -> best τ=0.510 (val F1=0.1567)
  Directional -> Accuracy: 0.4912, MCC: -0.0453, F1: 0.3256

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.72582 | val 0.69819
  Epoch 020 - train 0.70982 | val 0.71715
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 16). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.71258 | val 0.69010
  Epoch 020 - train 0.70489 | val 0.67492
  Classification -> best τ=0.475 (val F1=0.4229)
  Directional -> Accuracy: 0.6500, MCC: 0.1321, F1: 0.3000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.70935 | val 0.69070
  Epoch 020 - train 0.70523 | val 0.68669
  Classification -> best τ=0.535 (val F1=0.6009)
  Directional -> Accuracy: 0.4359, MCC: -0.1031, F1: 0.2143

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 16). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.68095 | val 0.69627
  Epoch 020 - train 0.68561 | val 0.69072
  Classification -> best τ=0.575 (val F1=0.2296)
  Directional -> Accuracy: 0.5526, MCC: 0.1132, F1: 0.4516

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.68358 | val 0.69231
  Epoch 020 - train 0.69873 | val 0.69817
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.69699 | val 0.69069
  Epoch 020 - train 0.68881 | val 0.69211
  Classification -> best τ=0.495 (val F1=0.2500)
  Directional -> Accuracy: 0.5778, MCC: 0.1700, F1: 0.5778

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.67667 | val 0.71446
  Epoch 020 - train 0.68398 | val 0.77537
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.73710 | val 0.73733
  Epoch 020 - train 0.72411 | val 0.79143
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5439, MCC: 0.0000, F1: 0.7045

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.70468 | val 0.70923
  Epoch 020 - train 0.69258 | val 0.72065
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.71225 | val 0.69261
  Epoch 020 - train 0.71458 | val 0.71686
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.69615 | val 0.72842
  Epoch 020 - train 0.70315 | val 0.80622
  Classification -> best τ=0.515 (val F1=0.0706)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.71438 | val 0.70706

[I 2026-02-24 23:27:48,671] Trial 60 finished with value: 0.1775154133389841 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 15, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.5, 'batch_size': 64, 'learning_rate': 3.0910805572572033e-06, 'weight_decay': 1.1643184031203068e-05, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 1.3910571223993229, 'early_stopping_min_delta': 0.0030037305723289278}. Best is trial 32 with value: 0.2908549754956826.

  Epoch 020 - train 0.70006 | val 0.72398
  Classification -> best τ=0.520 (val F1=0.2148)
  Directional -> Accuracy: 0.5323, MCC: 0.0668, F1: 0.5397

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.1775154133389841
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 15
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.66509 | val 0.74349
  Epoch 011 - train 0.66083 | val 0.74163
  Classification -> best τ=0.500 (val F1=0.2164)
  Directional -> Accuracy: 0.4935, MCC: -0.1199, F1: 0.1333

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.62925 | val 1.10794
  Epoch 012 - train 0.60149 | val 1.77084
  Classification -> best τ=0.450 (val F1=0.2431)
  Directional -> Accuracy: 0.6304, MCC: 0.2280, F1: 0.7213

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 16). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.64476 | val 0.78577
  Epoch 012 - train 0.69076 | val 0.91082
  Classification -> best τ=0.630 (val F1=0.2892)
  Directional -> Accuracy: 0.4583, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.65162 | val 1.14444
  Epoch 011 - train 0.65481 | val 1.08915
  Classification -> best τ=0.405 (val F1=0.1132)
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.63317 | val 1.17992
  Epoch 016 - train 0.55221 | val 1.34695
  Classification -> best τ=0.880 (val F1=0.3139)
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.60422 | val 0.98944
  Epoch 014 - train 0.55513 | val 1.14181
  Classification -> best τ=0.500 (val F1=0.2236)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.65106 | val 0.74396
  Epoch 011 - train 0.68847 | val 0.70186
  Classification -> best τ=0.535 (val F1=0.1715)
  Directional -> Accuracy: 0.6000, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 16). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.55121 | val 1.94425
  Epoch 014 - train 0.56019 | val 1.65111
  Classification -> best τ=0.535 (val F1=0.2229)
  Directional -> Accuracy: 0.4667, MCC: 0.0240, F1: 0.5556

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.63356 | val 1.70403
  Epoch 011 - train 0.65956 | val 1.80382
  Classification -> best τ=0.535 (val F1=0.4301)
  Directional -> Accuracy: 0.5366, MCC: -0.2497, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 16). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 16). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.64094 | val 1.15499
  Epoch 011 - train 0.62925 | val 0.85192
  Classification -> best τ=0.475 (val F1=0.2160)
  Directional -> Accuracy: 0.4648, MCC: 0.0299, F1: 0.5870

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.67233 | val 1.75233
  Epoch 011 - train 0.62425 | val 1.82165
  Classification -> best τ=0.530 (val F1=0.2390)
  Directional -> Accuracy: 0.5490, MCC: 0.0971, F1: 0.5306

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.66668 | val 0.97420
  Epoch 011 - train 0.64288 | val 0.82247
  Classification -> best τ=0.585 (val F1=0.2701)
  Directional -> Accuracy: 0.5593, MCC: 0.2186, F1: 0.2778

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.64907 | val 0.98593
  Epoch 011 - train 0.65326 | val 0.93800
  Classification -> best τ=0.390 (val F1=0.2869)
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.69384 | val 0.81808
  Epoch 012 - train 0.65663 | val 0.70429
  Classification -> best τ=0.345 (val F1=0.2928)
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.63152 | val 1.89046
  Epoch 011 - train 0.62435 | val 2.55223
  Classification -> best τ=0.545 (val F1=0.2262)
  Directional -> Accuracy: 0.5283, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.60027 | val 0.85392
  Epoch 011 - train 0.58257 | val 0.90926
  Classification -> best τ=0.450 (val F1=0.3298)
  Directional -> Accuracy: 0.6429, MCC: 0.3329, F1: 0.7475

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.70136 | val 1.41731
  Epoch 012 - train 0.64396 | val 1.36989
  Classification -> best τ=0.680 (val F1=0.2219)
  Directional -> Accuracy: 0.3833, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.63937 | val 1.48873
  Epoch 011 - train 0.63732 | val 1.18062
  Classification -> best τ=0.420 (val F1=0.1989)
  Directional -> Accuracy: 0.5658, MCC: -0.1057, F1: 0.7179

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.68552 | val 0.92321
  Epoch 011 - train 0.64859 | val 1.03634
  Classification -> best τ=0.420 (val F1=0.2464)
  Directional -> Accuracy: 0.5758, MCC: 0.2787, F1: 0.5000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 16). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.66649 | val 0.77296
  Epoch 018 - train 0.59200 | val 0.80753
  Classification -> best τ=0.480 (val F1=0.3398)
  Directional -> Accuracy: 0.5132, MCC: 0.1105, F1: 0.3019

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.59651 | val 1.20143
  Epoch 015 - train 0.61072 | val 1.20698
  Classification -> best τ=0.430 (val F1=0.3555)
  Directional -> Accuracy: 0.5000, MCC: 0.1491, F1: 0.4286

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.64078 | val 1.03138
  Epoch 011 - train 0.65340 | val 1.19947
  Classification -> best τ=0.460 (val F1=0.1677)
  Directional -> Accuracy: 0.5152, MCC: 0.0362, F1: 0.6190

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.67059 | val 0.84466
  Epoch 011 - train 0.65426 | val 0.80422
  Classification -> best τ=0.640 (val F1=0.2773)
  Directional -> Accuracy: 0.4655, MCC: 0.0286, F1: 0.2791

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.65952 | val 2.28558
  Epoch 011 - train 0.65388 | val 2.91475
  Classification -> best τ=0.490 (val F1=0.1878)
  Directional -> Accuracy: 0.5606, MCC: 0.1135, F1: 0.5085

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.69228 | val 0.69283
  Epoch 013 - train 0.63871 | val 0.74845
  Classification -> best τ=0.430 (val F1=0.3027)
  Directional -> Accuracy: 0.5000, MCC: 0.0039, F1: 0.5172

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.59541 | val 0.72635
  Epoch 011 - train 0.55504 | val 0.77279
  Classification -> best τ=0.515 (val F1=0.2067)
  Directional -> Accuracy: 0.4468, MCC: -0.0570, F1: 0.5000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.64826 | val 0.74709
  Epoch 011 - train 0.65257 | val 0.72374
  Classification -> best τ=0.535 (val F1=0.1309)
  Directional -> Accuracy: 0.4884, MCC: -0.0044, F1: 0.5000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.62661 | val 0.77594
  Epoch 011 - train 0.61475 | val 0.90469
  Classification -> best τ=0.450 (val F1=0.3358)
  Directional -> Accuracy: 0.4828, MCC: 0.1703, F1: 0.1176

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.68175 | val 0.71470
  Epoch 020 - train 0.68097 | val 0.66236
  Classification -> best τ=0.660 (val F1=0.4193)
  Directional -> Accuracy: 0.5952, MCC: 0.2205, F1: 0.5641

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.62256 | val 1.21548
  Epoch 011 - train 0.70190 | val 1.67365
  Classification -> best τ=0.560 (val F1=0.1171)
  Directional -> Accuracy: 0.5227, MCC: 0.1525, F1: 0.0870

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.70670 | val 0.83033
  Epoch 011 - train 0.66645 | val 0.70928
  Classification -> best τ=0.505 (val F1=0.1000)
  Directional -> Accuracy: 0.4773, MCC: -0.1234, F1: 0.6102

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.61829 | val 0.81755
  Epoch 014 - train 0.61522 | val 1.06669
  Classification -> best τ=0.590 (val F1=0.2320)
  Directional -> Accuracy: 0.4510, MCC: -0.1525, F1: 0.5758

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.63635 | val 1.29983
  Epoch 012 - train 0.60485 | val 1.49430
  Classification -> best τ=0.615 (val F1=0.2993)
  Directional -> Accuracy: 0.5135, MCC: 0.1271, F1: 0.3793

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.62062 | val 0.93447
  Epoch 011 - train 0.66812 | val 1.00803
  Classification -> best τ=0.385 (val F1=0.3130)
  Directional -> Accuracy: 0.4737, MCC: -0.0976, F1: 0.6296

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.65191 | val 1.20129
  Epoch 011 - train 0.61499 | val 1.12979
  Classification -> best τ=0.530 (val F1=0.0209)
  Directional -> Accuracy: 0.5333, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.63855 | val 0.69263
  Epoch 011 - train 0.61672 | val 0.71480
  Classification -> best τ=0.405 (val F1=0.3767)
  Directional -> Accuracy: 0.5075, MCC: 0.1432, F1: 0.3265

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.67678 | val 0.79742
  Epoch 014 - train 0.61181 | val 0.70152
  Classification -> best τ=0.480 (val F1=0.3038)
  Directional -> Accuracy: 0.6279, MCC: 0.3176, F1: 0.5000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.63165 | val 0.71886
  Epoch 011 - train 0.64286 | val 0.70127
  Classification -> best τ=0.410 (val F1=0.2453)
  Directional -> Accuracy: 0.5088, MCC: 0.0516, F1: 0.6000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.63872 | val 0.99645
  Epoch 011 - train 0.61578 | val 0.99440
  Classification -> best τ=0.510 (val F1=0.2797)
  Directional -> Accuracy: 0.5957, MCC: 0.0121, F1: 0.7324

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 16). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.58172 | val 1.44228
  Epoch 011 - train 0.55938 | val 1.53011
  Classification -> best τ=0.520 (val F1=0.3072)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.69483 | val 0.79365
  Epoch 011 - train 0.70918 | val 0.77668
  Classification -> best τ=0.505 (val F1=0.1870)
  Directional -> Accuracy: 0.5128, MCC: -0.0188, F1: 0.6275

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 16). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.67832 | val 0.88355
  Epoch 011 - train 0.65152 | val 0.97270
  Classification -> best τ=0.360 (val F1=0.3218)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.61666 | val 0.71291
  Epoch 011 - train 0.67956 | val 0.69536
  Classification -> best τ=0.540 (val F1=0.1733)
  Directional -> Accuracy: 0.5532, MCC: 0.1093, F1: 0.5333

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.58637 | val 0.94656
  Epoch 011 - train 0.61780 | val 1.09041
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.63723 | val 0.78792
  Epoch 017 - train 0.54004 | val 0.90812
  Classification -> best τ=0.555 (val F1=0.4229)
  Directional -> Accuracy: 0.5750, MCC: 0.3954, F1: 0.6222

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.66769 | val 1.50243
  Epoch 011 - train 0.66040 | val 1.33157
  Classification -> best τ=0.490 (val F1=0.1464)
  Directional -> Accuracy: 0.4561, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.61889 | val 1.43487
  Epoch 012 - train 0.60088 | val 2.05851
  Classification -> best τ=0.355 (val F1=0.2554)
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.68706 | val 1.82651
  Epoch 011 - train 0.65635 | val 1.83405
  Classification -> best τ=0.400 (val F1=0.2291)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.69330 | val 1.20920
  Epoch 011 - train 0.63035 | val 1.26096
  Classification -> best τ=0.610 (val F1=0.1009)
  Directional -> Accuracy: 0.4737, MCC: -0.0842, F1: 0.6053

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.64160 | val 0.78555
  Epoch 011 - train 0.63706 | val 0.80135

[I 2026-02-24 23:29:04,172] Trial 61 finished with value: 0.24344165484264405 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 15, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 0.0027177610980108767, 'weight_decay': 0.0006724564479019474, 'lr_patience': 7, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 1.3248353027973654, 'early_stopping_min_delta': 0.004830913705866757}. Best is trial 32 with value: 0.2908549754956826.

  Classification -> best τ=0.580 (val F1=0.2653)
  Directional -> Accuracy: 0.5161, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.24344165484264405
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 15
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.68843 | val 0.67197
  Epoch 020 - train 0.68973 | val 0.75877
  Classification -> best τ=0.475 (val F1=0.1565)
  Directional -> Accuracy: 0.4935, MCC: -0.0577, F1: 0.3158

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.61282 | val 0.92652
  Epoch 011 - train 0.62460 | val 0.96242
  Classification -> best τ=0.405 (val F1=0.1962)
  Directional -> Accuracy: 0.6304, MCC: 0.2526, F1: 0.6667

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 16). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.70314 | val 0.80379
  Epoch 011 - train 0.67795 | val 0.74763
  Classification -> best τ=0.545 (val F1=0.3357)
  Directional -> Accuracy: 0.5208, MCC: 0.0692, F1: 0.4651

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.69561 | val 1.23423
  Epoch 011 - train 0.68704 | val 1.02334
  Classification -> best τ=0.505 (val F1=0.1989)
  Directional -> Accuracy: 0.5333, MCC: 0.1613, F1: 0.3636

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.60222 | val 1.00365
  Epoch 011 - train 0.58284 | val 1.35170
  Classification -> best τ=0.525 (val F1=0.2604)
  Directional -> Accuracy: 0.5769, MCC: 0.1398, F1: 0.6944

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.62615 | val 0.81110
  Epoch 012 - train 0.60133 | val 0.81180
  Classification -> best τ=0.480 (val F1=0.2777)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.70652 | val 0.70826
  Epoch 014 - train 0.69056 | val 0.74852
  Classification -> best τ=0.385 (val F1=0.2588)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.5714

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 16). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.72432 | val 0.87856
  Epoch 020 - train 0.57100 | val 3.68489
  Classification -> best τ=0.590 (val F1=0.2390)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.67819 | val 0.80432
  Epoch 015 - train 0.62271 | val 1.09353
  Classification -> best τ=0.395 (val F1=0.1489)
  Directional -> Accuracy: 0.4634, MCC: 0.1184, F1: 0.5417

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 16). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 16). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.66318 | val 0.89201
  Epoch 012 - train 0.65526 | val 0.84877
  Classification -> best τ=0.420 (val F1=0.2065)
  Directional -> Accuracy: 0.4225, MCC: -0.0899, F1: 0.5684

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.67318 | val 1.20094
  Epoch 013 - train 0.66750 | val 0.77714
  Classification -> best τ=0.485 (val F1=0.3244)
  Directional -> Accuracy: 0.5686, MCC: 0.1633, F1: 0.2143

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.66616 | val 0.74712
  Epoch 016 - train 0.68349 | val 0.83330
  Classification -> best τ=0.315 (val F1=0.1680)
  Directional -> Accuracy: 0.5085, MCC: 0.0000, F1: 0.6742

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.65232 | val 1.06708
  Epoch 013 - train 0.60362 | val 1.16374
  Classification -> best τ=0.445 (val F1=0.2972)
  Directional -> Accuracy: 0.5581, MCC: 0.0259, F1: 0.0952

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.66710 | val 0.79173
  Epoch 015 - train 0.65381 | val 0.76526
  Classification -> best τ=0.325 (val F1=0.3634)
  Directional -> Accuracy: 0.5902, MCC: 0.2087, F1: 0.6835

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.64973 | val 1.24908
  Epoch 011 - train 0.67608 | val 1.39694
  Classification -> best τ=0.720 (val F1=0.2589)
  Directional -> Accuracy: 0.5472, MCC: 0.0779, F1: 0.2500

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.65301 | val 0.90272
  Epoch 014 - train 0.63816 | val 0.78490
  Classification -> best τ=0.645 (val F1=0.3415)
  Directional -> Accuracy: 0.5857, MCC: 0.1502, F1: 0.6667

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.66519 | val 0.98643
  Epoch 011 - train 0.68930 | val 1.05868
  Classification -> best τ=0.385 (val F1=0.1044)
  Directional -> Accuracy: 0.6000, MCC: 0.0990, F1: 0.7073

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.66212 | val 1.22482
  Epoch 013 - train 0.66638 | val 1.11061
  Classification -> best τ=0.350 (val F1=0.1864)
  Directional -> Accuracy: 0.5526, MCC: 0.1704, F1: 0.5405

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.65045 | val 0.70565
  Epoch 011 - train 0.68316 | val 0.73822
  Classification -> best τ=0.455 (val F1=0.3342)
  Directional -> Accuracy: 0.5455, MCC: 0.1887, F1: 0.4828

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 16). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.69619 | val 0.73244
  Epoch 016 - train 0.65716 | val 0.68588
  Classification -> best τ=0.490 (val F1=0.2584)
  Directional -> Accuracy: 0.4868, MCC: 0.1519, F1: 0.0930

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.69493 | val 0.72519
  Epoch 020 - train 0.61623 | val 0.74200
  Classification -> best τ=0.375 (val F1=0.3544)
  Directional -> Accuracy: 0.4583, MCC: 0.2335, F1: 0.2353

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.67970 | val 0.99816
  Epoch 012 - train 0.65847 | val 1.11550
  Classification -> best τ=0.810 (val F1=0.2264)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.70068 | val 0.69357
  Epoch 011 - train 0.68234 | val 0.69877
  Classification -> best τ=0.620 (val F1=0.2272)
  Directional -> Accuracy: 0.5172, MCC: 0.1165, F1: 0.4167

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.68033 | val 0.88778
  Epoch 012 - train 0.65774 | val 1.07540
  Classification -> best τ=0.345 (val F1=0.1603)
  Directional -> Accuracy: 0.4242, MCC: -0.2319, F1: 0.5957

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.67584 | val 0.68376
  Epoch 019 - train 0.64687 | val 0.74416
  Classification -> best τ=0.470 (val F1=0.3610)
  Directional -> Accuracy: 0.5179, MCC: 0.1188, F1: 0.3721

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.63568 | val 0.67303
  Epoch 020 - train 0.55370 | val 0.87293
  Classification -> best τ=0.395 (val F1=0.3623)
  Directional -> Accuracy: 0.4468, MCC: -0.1315, F1: 0.3500

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.71480 | val 0.70358
  Epoch 011 - train 0.68275 | val 0.69264
  Classification -> best τ=0.530 (val F1=0.1309)
  Directional -> Accuracy: 0.6744, MCC: 0.3753, F1: 0.6818

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.68716 | val 0.70814
  Epoch 017 - train 0.65454 | val 0.75128
  Classification -> best τ=0.380 (val F1=0.2211)
  Directional -> Accuracy: 0.5517, MCC: 0.0531, F1: 0.6667

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.76131 | val 0.75446
  Epoch 014 - train 0.64321 | val 0.69902
  Classification -> best τ=0.520 (val F1=0.3203)
  Directional -> Accuracy: 0.5714, MCC: 0.1070, F1: 0.6897

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.65000 | val 1.27960
  Epoch 011 - train 0.73396 | val 1.26654
  Classification -> best τ=0.545 (val F1=0.1869)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.66239 | val 0.77253
  Epoch 017 - train 0.65673 | val 0.76569
  Classification -> best τ=0.555 (val F1=0.1495)
  Directional -> Accuracy: 0.4091, MCC: -0.1693, F1: 0.1333

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.66438 | val 0.79073
  Epoch 012 - train 0.62839 | val 0.84249
  Classification -> best τ=0.525 (val F1=0.3676)
  Directional -> Accuracy: 0.5098, MCC: -0.0051, F1: 0.6032

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.67253 | val 0.72436
  Epoch 013 - train 0.67018 | val 0.89553
  Classification -> best τ=0.650 (val F1=0.2739)
  Directional -> Accuracy: 0.4324, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.65049 | val 0.98065
  Epoch 012 - train 0.65490 | val 1.00027
  Classification -> best τ=0.435 (val F1=0.4045)
  Directional -> Accuracy: 0.5263, MCC: 0.0538, F1: 0.5714

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.68192 | val 0.90104
  Epoch 011 - train 0.72878 | val 0.94363
  Classification -> best τ=0.490 (val F1=0.2922)
  Directional -> Accuracy: 0.6444, MCC: 0.2911, F1: 0.6364

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.66426 | val 0.67899
  Epoch 020 - train 0.61292 | val 0.77342
  Classification -> best τ=0.280 (val F1=0.3687)
  Directional -> Accuracy: 0.4776, MCC: 0.1335, F1: 0.1860

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.69734 | val 0.72640
  Epoch 013 - train 0.67130 | val 0.69061
  Classification -> best τ=0.530 (val F1=0.2683)
  Directional -> Accuracy: 0.4651, MCC: -0.0977, F1: 0.0800

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.64154 | val 0.76110
  Epoch 011 - train 0.67093 | val 0.80956
  Classification -> best τ=0.425 (val F1=0.2764)
  Directional -> Accuracy: 0.5789, MCC: 0.1556, F1: 0.5556

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.61960 | val 1.02490
  Epoch 011 - train 0.65333 | val 0.92968
  Classification -> best τ=0.410 (val F1=0.1162)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 16). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.66363 | val 1.16763
  Epoch 011 - train 0.58993 | val 1.56254
  Classification -> best τ=0.450 (val F1=0.2888)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.69301 | val 0.76716
  Epoch 011 - train 0.81304 | val 0.76825
  Classification -> best τ=0.485 (val F1=0.2431)
  Directional -> Accuracy: 0.4872, MCC: 0.0088, F1: 0.3750

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 16). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.66740 | val 0.76703
  Epoch 011 - train 0.65107 | val 0.75212
  Classification -> best τ=0.490 (val F1=0.3475)
  Directional -> Accuracy: 0.5921, MCC: 0.1848, F1: 0.5753

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.71160 | val 1.13862
  Epoch 011 - train 0.67090 | val 1.42505
  Classification -> best τ=0.475 (val F1=0.1556)
  Directional -> Accuracy: 0.5745, MCC: 0.1559, F1: 0.6552

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.70254 | val 1.34970
  Epoch 011 - train 0.68413 | val 1.50783
  Classification -> best τ=0.460 (val F1=0.2000)
  Directional -> Accuracy: 0.6444, MCC: 0.2859, F1: 0.7419

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.74342 | val 0.87943
  Epoch 013 - train 0.75867 | val 0.86787
  Classification -> best τ=0.490 (val F1=0.2219)
  Directional -> Accuracy: 0.6500, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.70079 | val 0.79877
  Epoch 013 - train 0.65287 | val 1.10067
  Classification -> best τ=0.640 (val F1=0.1869)
  Directional -> Accuracy: 0.4561, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.67520 | val 1.31169
  Epoch 011 - train 0.68818 | val 1.21181
  Classification -> best τ=0.460 (val F1=0.2554)
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.67110 | val 1.26274
  Epoch 011 - train 0.67207 | val 1.61050
  Classification -> best τ=0.420 (val F1=0.2426)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.69882 | val 1.23790
  Epoch 013 - train 0.68289 | val 1.00114
  Classification -> best τ=0.490 (val F1=0.2353)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.65615 | val 1.07431

[I 2026-02-24 23:30:25,605] Trial 62 finished with value: 0.25251925431122246 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 15, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 32, 'learning_rate': 0.004287306249422697, 'weight_decay': 0.0007255507377820029, 'lr_patience': 7, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 0.29737940264634855, 'early_stopping_min_delta': 0.004348006046977313}. Best is trial 32 with value: 0.2908549754956826.

  Epoch 015 - train 0.65865 | val 1.00528
  Classification -> best τ=0.585 (val F1=0.2653)
  Directional -> Accuracy: 0.5161, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.25251925431122246
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 15
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.66705 | val 0.70546
  Epoch 013 - train 0.61752 | val 0.69219
  Classification -> best τ=0.530 (val F1=0.2553)
  Directional -> Accuracy: 0.5325, MCC: 0.0171, F1: 0.3077

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.59688 | val 1.03031
  Epoch 011 - train 0.66985 | val 1.07392
  Classification -> best τ=0.480 (val F1=0.1812)
  Directional -> Accuracy: 0.5870, MCC: 0.1202, F1: 0.6984

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 16). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.70160 | val 0.86581
  Epoch 017 - train 0.68353 | val 0.78930
  Classification -> best τ=0.420 (val F1=0.3544)
  Directional -> Accuracy: 0.5417, MCC: 0.0374, F1: 0.6667

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.65302 | val 1.16265
  Epoch 011 - train 0.64052 | val 0.87928
  Classification -> best τ=0.465 (val F1=0.1533)
  Directional -> Accuracy: 0.5067, MCC: -0.0029, F1: 0.5647

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.59285 | val 1.02113
  Epoch 015 - train 0.52931 | val 1.48333
  Classification -> best τ=0.370 (val F1=0.3592)
  Directional -> Accuracy: 0.5192, MCC: -0.1296, F1: 0.6835

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.55182 | val 1.13286
  Epoch 011 - train 0.57658 | val 1.30955
  Classification -> best τ=0.485 (val F1=0.3393)
  Directional -> Accuracy: 0.4792, MCC: -0.1459, F1: 0.6479

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.68082 | val 0.77031
  Epoch 012 - train 0.63700 | val 0.79878
  Classification -> best τ=0.630 (val F1=0.2116)
  Directional -> Accuracy: 0.6000, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 16). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.60716 | val 1.63132
  Epoch 011 - train 0.60749 | val 1.67034
  Classification -> best τ=0.485 (val F1=0.1512)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.62657 | val 0.85185
  Epoch 011 - train 0.58184 | val 1.19137
  Classification -> best τ=0.605 (val F1=0.4282)
  Directional -> Accuracy: 0.6341, MCC: 0.1153, F1: 0.2857

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 16). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 16). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.64149 | val 0.73758
  Epoch 011 - train 0.62736 | val 0.91022
  Classification -> best τ=0.570 (val F1=0.1587)
  Directional -> Accuracy: 0.5634, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.66027 | val 2.01219
  Epoch 013 - train 0.60675 | val 2.00075
  Classification -> best τ=0.535 (val F1=0.2248)
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.6400

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.64245 | val 0.92849
  Epoch 013 - train 0.64264 | val 0.98271
  Classification -> best τ=0.500 (val F1=0.3357)
  Directional -> Accuracy: 0.5763, MCC: 0.1848, F1: 0.4444

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.58982 | val 1.52219
  Epoch 011 - train 0.63024 | val 1.60761
  Classification -> best τ=0.460 (val F1=0.2454)
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.65390 | val 0.76364
  Epoch 013 - train 0.66521 | val 0.94443
  Classification -> best τ=0.400 (val F1=0.2609)
  Directional -> Accuracy: 0.6066, MCC: 0.2556, F1: 0.7000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.66241 | val 2.90273
  Epoch 012 - train 0.58158 | val 2.96799
  Classification -> best τ=0.610 (val F1=0.2879)
  Directional -> Accuracy: 0.5472, MCC: 0.1468, F1: 0.0769

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.62801 | val 0.88799
  Epoch 012 - train 0.63119 | val 1.11413
  Classification -> best τ=0.345 (val F1=0.2172)
  Directional -> Accuracy: 0.5857, MCC: 0.2306, F1: 0.7238

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.67865 | val 0.98263
  Epoch 012 - train 0.67205 | val 1.08097
  Classification -> best τ=0.625 (val F1=0.1796)
  Directional -> Accuracy: 0.3833, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.63258 | val 1.39526
  Epoch 011 - train 0.64531 | val 1.40882
  Classification -> best τ=0.470 (val F1=0.1770)
  Directional -> Accuracy: 0.4868, MCC: 0.0933, F1: 0.4000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.65843 | val 1.19727
  Epoch 015 - train 0.57862 | val 1.32846
  Classification -> best τ=0.440 (val F1=0.3638)
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 16). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.60137 | val 1.00222
  Epoch 013 - train 0.57777 | val 1.00857
  Classification -> best τ=0.475 (val F1=0.3395)
  Directional -> Accuracy: 0.5263, MCC: -0.0118, F1: 0.6667

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.59852 | val 1.20386
  Epoch 011 - train 0.62049 | val 1.51968
  Classification -> best τ=0.485 (val F1=0.2680)
  Directional -> Accuracy: 0.5000, MCC: 0.0216, F1: 0.5385

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.62288 | val 1.69447
  Epoch 011 - train 0.62121 | val 1.61082
  Classification -> best τ=0.625 (val F1=0.2264)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.68019 | val 1.00854
  Epoch 013 - train 0.61885 | val 1.30847
  Classification -> best τ=0.540 (val F1=0.2812)
  Directional -> Accuracy: 0.5690, MCC: 0.1441, F1: 0.5902

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.65298 | val 3.47743
  Epoch 011 - train 0.61804 | val 2.25683
  Classification -> best τ=0.335 (val F1=0.2383)
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.63375 | val 0.68909
  Epoch 015 - train 0.59801 | val 0.96000
  Classification -> best τ=0.560 (val F1=0.4135)
  Directional -> Accuracy: 0.5357, MCC: 0.1242, F1: 0.4583

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.53856 | val 0.74319
  Epoch 018 - train 0.55562 | val 1.09118
  Classification -> best τ=0.355 (val F1=0.2979)
  Directional -> Accuracy: 0.4255, MCC: 0.0000, F1: 0.5970

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.63470 | val 1.17072
  Epoch 013 - train 0.60491 | val 1.16271
  Classification -> best τ=0.515 (val F1=0.2643)
  Directional -> Accuracy: 0.5814, MCC: 0.0528, F1: 0.7188

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.63526 | val 0.86158
  Epoch 011 - train 0.63740 | val 0.92333
  Classification -> best τ=0.495 (val F1=0.2211)
  Directional -> Accuracy: 0.5517, MCC: 0.2600, F1: 0.3500

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.67642 | val 0.70466
  Epoch 016 - train 0.63879 | val 0.86789
  Classification -> best τ=0.495 (val F1=0.3974)
  Directional -> Accuracy: 0.5476, MCC: 0.0310, F1: 0.6885

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.64060 | val 1.55095
  Epoch 011 - train 0.69319 | val 1.57081
  Classification -> best τ=0.510 (val F1=0.0212)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.3889

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.67183 | val 0.83466
  Epoch 011 - train 0.64728 | val 0.84215
  Classification -> best τ=0.530 (val F1=0.2703)
  Directional -> Accuracy: 0.4773, MCC: -0.0091, F1: 0.3784

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.59262 | val 0.81726
  Epoch 014 - train 0.60679 | val 0.82464
  Classification -> best τ=0.660 (val F1=0.2320)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.61054 | val 1.24578
  Epoch 011 - train 0.62297 | val 1.30483
  Classification -> best τ=0.515 (val F1=0.3655)
  Directional -> Accuracy: 0.5541, MCC: 0.2008, F1: 0.4590

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.67775 | val 0.83737
  Epoch 011 - train 0.62901 | val 0.91524
  Classification -> best τ=0.415 (val F1=0.3024)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.5957

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.65280 | val 1.64167
  Epoch 011 - train 0.59437 | val 1.52017
  Classification -> best τ=0.560 (val F1=0.1411)
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.6364

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.61086 | val 0.81720
  Epoch 011 - train 0.62669 | val 0.79646
  Classification -> best τ=0.425 (val F1=0.3431)
  Directional -> Accuracy: 0.5224, MCC: 0.1724, F1: 0.3600

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.61893 | val 0.79401
  Epoch 012 - train 0.60880 | val 0.80570
  Classification -> best τ=0.510 (val F1=0.1830)
  Directional -> Accuracy: 0.6279, MCC: 0.2967, F1: 0.5294

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.68267 | val 0.79391
  Epoch 012 - train 0.61152 | val 0.84827
  Classification -> best τ=0.455 (val F1=0.2547)
  Directional -> Accuracy: 0.5614, MCC: 0.1491, F1: 0.6154

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.60886 | val 1.53322
  Epoch 012 - train 0.63619 | val 1.44627
  Classification -> best τ=0.505 (val F1=0.2429)
  Directional -> Accuracy: 0.5957, MCC: 0.0392, F1: 0.7246

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 16). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.60319 | val 0.82143
  Epoch 011 - train 0.62459 | val 0.85243
  Classification -> best τ=0.485 (val F1=0.1391)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.57704 | val 0.80213
  Epoch 011 - train 0.64997 | val 0.82807
  Classification -> best τ=0.455 (val F1=0.1870)
  Directional -> Accuracy: 0.5641, MCC: 0.1752, F1: 0.7119

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 16). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.62082 | val 1.09364
  Epoch 012 - train 0.63452 | val 0.97721
  Classification -> best τ=0.615 (val F1=0.2585)
  Directional -> Accuracy: 0.5789, MCC: 0.1637, F1: 0.6279

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.64967 | val 0.71278
  Epoch 011 - train 0.64610 | val 0.77497
  Classification -> best τ=0.515 (val F1=0.0936)
  Directional -> Accuracy: 0.5319, MCC: 0.0852, F1: 0.3889

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.57101 | val 1.07168
  Epoch 011 - train 0.51781 | val 1.16593
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.66391 | val 0.91190
  Epoch 017 - train 0.58221 | val 1.12228
  Classification -> best τ=0.310 (val F1=0.4286)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.63927 | val 2.16647
  Epoch 011 - train 0.69019 | val 2.14517
  Classification -> best τ=0.415 (val F1=0.1703)
  Directional -> Accuracy: 0.6842, MCC: 0.3684, F1: 0.7000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.61129 | val 2.06803
  Epoch 011 - train 0.61659 | val 1.61320
  Classification -> best τ=0.510 (val F1=0.2554)
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.61523 | val 1.18969
  Epoch 011 - train 0.63012 | val 1.32137
  Classification -> best τ=0.510 (val F1=0.0909)
  Directional -> Accuracy: 0.4630, MCC: -0.0695, F1: 0.1714

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.67015 | val 1.70691
  Epoch 011 - train 0.64912 | val 1.61312
  Classification -> best τ=0.565 (val F1=0.1002)
  Directional -> Accuracy: 0.4912, MCC: -0.0405, F1: 0.6234

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.66440 | val 0.99474

[I 2026-02-24 23:31:40,457] Trial 63 finished with value: 0.24354156825404197 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 15, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 0.0015665929434801383, 'weight_decay': 6.095616147285499e-05, 'lr_patience': 7, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 1.5800279867583034, 'early_stopping_min_delta': 0.0038366025769826775}. Best is trial 32 with value: 0.2908549754956826.

  Epoch 013 - train 0.60887 | val 1.31400
  Classification -> best τ=0.505 (val F1=0.2653)
  Directional -> Accuracy: 0.4839, MCC: -0.0598, F1: 0.2727

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.24354156825404197
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 15
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.64240 | val 0.72664
  Epoch 020 - train 0.66055 | val 0.68638
  Classification -> best τ=0.575 (val F1=0.2851)
  Directional -> Accuracy: 0.5195, MCC: -0.0327, F1: 0.2128

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.64889 | val 0.74429
  Epoch 013 - train 0.62491 | val 0.76292
  Classification -> best τ=0.415 (val F1=0.1870)
  Directional -> Accuracy: 0.5652, MCC: 0.0693, F1: 0.6774

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 16). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.68582 | val 0.81713
  Epoch 012 - train 0.66579 | val 0.75921
  Classification -> best τ=0.565 (val F1=0.2261)
  Directional -> Accuracy: 0.4375, MCC: -0.1586, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.67633 | val 0.86694
  Epoch 011 - train 0.67604 | val 0.90877
  Classification -> best τ=0.465 (val F1=0.1917)
  Directional -> Accuracy: 0.4800, MCC: -0.2001, F1: 0.6422

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.59898 | val 1.20935
  Epoch 014 - train 0.59247 | val 1.31534
  Classification -> best τ=0.570 (val F1=0.4345)
  Directional -> Accuracy: 0.7308, MCC: 0.4702, F1: 0.7308

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.64880 | val 0.82987
  Epoch 013 - train 0.60068 | val 0.90994
  Classification -> best τ=0.435 (val F1=0.3254)
  Directional -> Accuracy: 0.5417, MCC: 0.1508, F1: 0.6765

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.68465 | val 0.69903
  Epoch 013 - train 0.68811 | val 0.69178
  Classification -> best τ=0.395 (val F1=0.2129)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.5714

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 16). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.66489 | val 1.39258
  Epoch 011 - train 0.58830 | val 1.65327
  Classification -> best τ=0.480 (val F1=0.1512)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.62470 | val 1.32709
  Epoch 014 - train 0.68849 | val 1.01352
  Classification -> best τ=0.600 (val F1=0.4282)
  Directional -> Accuracy: 0.4878, MCC: 0.2101, F1: 0.5714

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 16). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 16). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.65273 | val 0.78723
  Epoch 016 - train 0.66526 | val 0.86586
  Classification -> best τ=0.420 (val F1=0.2295)
  Directional -> Accuracy: 0.4366, MCC: -0.0455, F1: 0.5745

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.69390 | val 1.05651
  Epoch 011 - train 0.67319 | val 1.00041
  Classification -> best τ=0.330 (val F1=0.2248)
  Directional -> Accuracy: 0.6275, MCC: 0.2593, F1: 0.6275

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.68662 | val 0.95976
  Epoch 015 - train 0.67733 | val 0.76725
  Classification -> best τ=0.430 (val F1=0.2609)
  Directional -> Accuracy: 0.6271, MCC: 0.2728, F1: 0.6944

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.60823 | val 0.67512
  Epoch 020 - train 0.62641 | val 1.22639
  Classification -> best τ=0.560 (val F1=0.2504)
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.65646 | val 0.68781
  Epoch 012 - train 0.67334 | val 0.67808
  Classification -> best τ=0.330 (val F1=0.2775)
  Directional -> Accuracy: 0.5574, MCC: 0.1236, F1: 0.6494

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.66021 | val 1.79495
  Epoch 011 - train 0.67388 | val 1.49061
  Classification -> best τ=0.330 (val F1=0.1524)
  Directional -> Accuracy: 0.4717, MCC: -0.0162, F1: 0.6216

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.60289 | val 0.88288
  Epoch 013 - train 0.65893 | val 0.71864
  Classification -> best τ=0.280 (val F1=0.2927)
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.64779 | val 0.99947
  Epoch 011 - train 0.66463 | val 1.08412
  Classification -> best τ=0.590 (val F1=0.2476)
  Directional -> Accuracy: 0.3667, MCC: -0.1651, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.68779 | val 0.94042
  Epoch 014 - train 0.66317 | val 1.97826
  Classification -> best τ=0.450 (val F1=0.1898)
  Directional -> Accuracy: 0.5395, MCC: -0.0809, F1: 0.6789

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.64773 | val 0.78983
  Epoch 012 - train 0.66971 | val 0.76702
  Classification -> best τ=0.495 (val F1=0.2193)
  Directional -> Accuracy: 0.4091, MCC: -0.1307, F1: 0.3607

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 16). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.66691 | val 0.67353
  Epoch 020 - train 0.61658 | val 0.81682
  Classification -> best τ=0.235 (val F1=0.2518)
  Directional -> Accuracy: 0.5132, MCC: -0.0589, F1: 0.6606

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.62332 | val 0.72767
  Epoch 020 - train 0.57504 | val 0.65957
  Classification -> best τ=0.600 (val F1=0.4330)
  Directional -> Accuracy: 0.3958, MCC: -0.0457, F1: 0.2162

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.64649 | val 1.36311
  Epoch 011 - train 0.64986 | val 1.37808
  Classification -> best τ=0.640 (val F1=0.2264)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.70625 | val 0.74034
  Epoch 014 - train 0.66545 | val 0.92263
  Classification -> best τ=0.625 (val F1=0.3678)
  Directional -> Accuracy: 0.4138, MCC: -0.1078, F1: 0.1905

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.65119 | val 1.55868
  Epoch 011 - train 0.67422 | val 1.18364
  Classification -> best τ=0.510 (val F1=0.1878)
  Directional -> Accuracy: 0.5758, MCC: 0.2319, F1: 0.1765

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.66946 | val 0.67092
  Epoch 014 - train 0.64015 | val 0.65709
  Classification -> best τ=0.480 (val F1=0.5459)
  Directional -> Accuracy: 0.5536, MCC: 0.2064, F1: 0.4186

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.59232 | val 0.75550
  Epoch 011 - train 0.62773 | val 0.75447
  Classification -> best τ=0.600 (val F1=0.2717)
  Directional -> Accuracy: 0.4468, MCC: -0.2371, F1: 0.1333

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.63578 | val 0.92689
  Epoch 012 - train 0.64758 | val 0.80273
  Classification -> best τ=0.480 (val F1=0.2626)
  Directional -> Accuracy: 0.6279, MCC: 0.2000, F1: 0.7333

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.62784 | val 0.73586
  Epoch 015 - train 0.65162 | val 0.71697
  Classification -> best τ=0.325 (val F1=0.2369)
  Directional -> Accuracy: 0.5690, MCC: 0.0917, F1: 0.6988

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.71177 | val 0.71394
  Epoch 012 - train 0.71624 | val 0.78278
  Classification -> best τ=0.505 (val F1=0.3844)
  Directional -> Accuracy: 0.5000, MCC: -0.0338, F1: 0.5882

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.63085 | val 0.97069
  Epoch 013 - train 0.61692 | val 0.93722
  Classification -> best τ=0.590 (val F1=0.1869)
  Directional -> Accuracy: 0.5682, MCC: 0.1365, F1: 0.5778

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.70291 | val 0.65714
  Epoch 020 - train 0.71597 | val 0.72961
  Classification -> best τ=0.790 (val F1=0.2949)
  Directional -> Accuracy: 0.4545, MCC: -0.0430, F1: 0.2500

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.61490 | val 0.77612
  Epoch 014 - train 0.62040 | val 0.75079
  Classification -> best τ=0.430 (val F1=0.2541)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.65837 | val 1.28754
  Epoch 014 - train 0.64117 | val 1.84050
  Classification -> best τ=0.380 (val F1=0.2996)
  Directional -> Accuracy: 0.5270, MCC: 0.1525, F1: 0.4068

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.61741 | val 1.06183
  Epoch 015 - train 0.56553 | val 1.00096
  Classification -> best τ=0.455 (val F1=0.3024)
  Directional -> Accuracy: 0.5789, MCC: 0.1615, F1: 0.6190

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.62228 | val 1.35535
  Epoch 012 - train 0.58503 | val 1.37890
  Classification -> best τ=0.460 (val F1=0.4015)
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.6364

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.63522 | val 0.69930
  Epoch 012 - train 0.60372 | val 0.74218
  Classification -> best τ=0.330 (val F1=0.3767)
  Directional -> Accuracy: 0.5522, MCC: 0.1749, F1: 0.4828

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.63745 | val 0.72991
  Epoch 020 - train 0.60879 | val 0.73407
  Classification -> best τ=0.620 (val F1=0.3337)
  Directional -> Accuracy: 0.6512, MCC: 0.3392, F1: 0.5714

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.61646 | val 0.75511
  Epoch 013 - train 0.64668 | val 0.89926
  Classification -> best τ=0.410 (val F1=0.2094)
  Directional -> Accuracy: 0.4386, MCC: -0.1140, F1: 0.4839

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.60986 | val 0.93225
  Epoch 013 - train 0.59997 | val 1.04266
  Classification -> best τ=0.445 (val F1=0.4174)
  Directional -> Accuracy: 0.5319, MCC: -0.0598, F1: 0.6562

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 16). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.66730 | val 0.77623
  Epoch 011 - train 0.58169 | val 1.10198
  Classification -> best τ=0.455 (val F1=0.3333)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.74051 | val 0.81741
  Epoch 011 - train 0.65537 | val 0.82014
  Classification -> best τ=0.370 (val F1=0.1870)
  Directional -> Accuracy: 0.5641, MCC: 0.1188, F1: 0.7018

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 16). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.63971 | val 0.97672
  Epoch 019 - train 0.63952 | val 0.84160
  Classification -> best τ=0.385 (val F1=0.4710)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.63133 | val 0.79812
  Epoch 012 - train 0.65796 | val 1.06522
  Classification -> best τ=0.540 (val F1=0.2153)
  Directional -> Accuracy: 0.5532, MCC: 0.1357, F1: 0.6769

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.63989 | val 0.95239
  Epoch 012 - train 0.57890 | val 1.01004
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.72001 | val 0.72800
  Epoch 011 - train 0.62593 | val 0.75431
  Classification -> best τ=0.605 (val F1=0.3651)
  Directional -> Accuracy: 0.6500, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.67155 | val 0.69320
  Epoch 011 - train 0.67629 | val 0.68874
  Classification -> best τ=0.555 (val F1=0.2719)
  Directional -> Accuracy: 0.5263, MCC: 0.2516, F1: 0.2286

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.62315 | val 3.08085
  Epoch 011 - train 0.62586 | val 3.37564
  Classification -> best τ=0.600 (val F1=0.2667)
  Directional -> Accuracy: 0.5263, MCC: 0.0101, F1: 0.0690

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.66097 | val 2.49626
  Epoch 013 - train 0.63958 | val 2.80632
  Classification -> best τ=0.265 (val F1=0.3554)
  Directional -> Accuracy: 0.5370, MCC: 0.1425, F1: 0.6914

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.66956 | val 0.88823
  Epoch 015 - train 0.64945 | val 1.27314
  Classification -> best τ=0.445 (val F1=0.2874)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.66298 | val 0.71363

[I 2026-02-24 23:33:05,617] Trial 64 finished with value: 0.2822365194737849 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 15, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 0.007469284198580347, 'weight_decay': 0.0009990490844780952, 'lr_patience': 7, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 1.4296538099210052, 'early_stopping_min_delta': 0.0036658675958153174}. Best is trial 32 with value: 0.2908549754956826.

  Epoch 020 - train 0.62060 | val 0.77214
  Classification -> best τ=0.320 (val F1=0.3271)
  Directional -> Accuracy: 0.4355, MCC: -0.1313, F1: 0.5455

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2822365194737849
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 15
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.61114 | val 1.20879
  Epoch 012 - train 0.60522 | val 0.80300
  Classification -> best τ=0.405 (val F1=0.3161)
  Directional -> Accuracy: 0.4805, MCC: -0.1197, F1: 0.2000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.55870 | val 1.06761
  Epoch 012 - train 0.53255 | val 1.03645
  Classification -> best τ=0.540 (val F1=0.1700)
  Directional -> Accuracy: 0.6957, MCC: 0.3750, F1: 0.7407

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 16). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.62906 | val 0.93794
  Epoch 012 - train 0.61402 | val 1.00534
  Classification -> best τ=0.650 (val F1=0.2052)
  Directional -> Accuracy: 0.5000, MCC: 0.1918, F1: 0.1429

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.68201 | val 1.23337
  Epoch 012 - train 0.66380 | val 1.09160
  Classification -> best τ=0.565 (val F1=0.1095)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.56763 | val 1.69817
  Epoch 012 - train 0.51630 | val 1.70025
  Classification -> best τ=0.440 (val F1=0.4747)
  Directional -> Accuracy: 0.7115, MCC: 0.4475, F1: 0.6939

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.52652 | val 1.55204
  Epoch 011 - train 0.51376 | val 1.34177
  Classification -> best τ=0.550 (val F1=0.3119)
  Directional -> Accuracy: 0.5208, MCC: 0.0682, F1: 0.2069

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.65410 | val 0.68349
  Epoch 020 - train 0.54999 | val 0.80129
  Classification -> best τ=0.590 (val F1=0.2182)
  Directional -> Accuracy: 0.4571, MCC: 0.0437, F1: 0.5476

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 16). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.58734 | val 1.43946
  Epoch 011 - train 0.50111 | val 1.51651
  Classification -> best τ=0.545 (val F1=0.1512)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.64581 | val 1.59010
  Epoch 011 - train 0.56511 | val 1.86889
  Classification -> best τ=0.580 (val F1=0.3877)
  Directional -> Accuracy: 0.5122, MCC: -0.0226, F1: 0.3750

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 16). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 16). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.62349 | val 0.73898
  Epoch 013 - train 0.58526 | val 0.79032
  Classification -> best τ=0.475 (val F1=0.1114)
  Directional -> Accuracy: 0.5634, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.59828 | val 1.66162
  Epoch 011 - train 0.58282 | val 1.38423
  Classification -> best τ=0.495 (val F1=0.1077)
  Directional -> Accuracy: 0.5882, MCC: 0.2176, F1: 0.2759

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.65344 | val 0.71519
  Epoch 018 - train 0.52516 | val 0.97040
  Classification -> best τ=0.585 (val F1=0.2750)
  Directional -> Accuracy: 0.6949, MCC: 0.3913, F1: 0.6897

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.58408 | val 0.89098
  Epoch 014 - train 0.55333 | val 2.49257
  Classification -> best τ=0.315 (val F1=0.2004)
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.67616 | val 0.85694
  Epoch 011 - train 0.61389 | val 0.73962
  Classification -> best τ=0.285 (val F1=0.2928)
  Directional -> Accuracy: 0.5738, MCC: 0.2007, F1: 0.6905

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.62713 | val 1.68173
  Epoch 012 - train 0.55517 | val 1.60721
  Classification -> best τ=0.495 (val F1=0.1734)
  Directional -> Accuracy: 0.5094, MCC: -0.0464, F1: 0.1333

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.59519 | val 1.05091
  Epoch 011 - train 0.56290 | val 1.23836
  Classification -> best τ=0.445 (val F1=0.2605)
  Directional -> Accuracy: 0.5429, MCC: 0.0212, F1: 0.6923

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.63948 | val 1.07078
  Epoch 011 - train 0.60945 | val 1.21206
  Classification -> best τ=0.580 (val F1=0.1259)
  Directional -> Accuracy: 0.3833, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.60721 | val 1.92730
  Epoch 013 - train 0.60458 | val 1.56614
  Classification -> best τ=0.480 (val F1=0.2395)
  Directional -> Accuracy: 0.3684, MCC: -0.1635, F1: 0.1429

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.62462 | val 1.67192
  Epoch 012 - train 0.61552 | val 1.62598
  Classification -> best τ=0.475 (val F1=0.2292)
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 16). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.61051 | val 0.86698
  Epoch 018 - train 0.59809 | val 0.96395
  Classification -> best τ=0.455 (val F1=0.3157)
  Directional -> Accuracy: 0.4868, MCC: 0.1519, F1: 0.0930

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.58929 | val 0.83091
  Epoch 014 - train 0.53893 | val 1.07518
  Classification -> best τ=0.415 (val F1=0.3555)
  Directional -> Accuracy: 0.5625, MCC: -0.0128, F1: 0.6866

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.61519 | val 1.25601
  Epoch 011 - train 0.60744 | val 1.70625
  Classification -> best τ=0.750 (val F1=0.1834)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.62758 | val 0.89553
  Epoch 014 - train 0.57104 | val 2.23093
  Classification -> best τ=0.440 (val F1=0.2549)
  Directional -> Accuracy: 0.5862, MCC: 0.1078, F1: 0.7073

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.61132 | val 2.32225
  Epoch 011 - train 0.62333 | val 1.97761
  Classification -> best τ=0.400 (val F1=0.2319)
  Directional -> Accuracy: 0.5152, MCC: 0.0304, F1: 0.5000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.61338 | val 0.80689
  Epoch 013 - train 0.56095 | val 0.81944
  Classification -> best τ=0.635 (val F1=0.3691)
  Directional -> Accuracy: 0.5536, MCC: 0.2064, F1: 0.4186

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.54431 | val 0.99188
  Epoch 011 - train 0.52995 | val 1.12676
  Classification -> best τ=0.610 (val F1=0.3225)
  Directional -> Accuracy: 0.5106, MCC: -0.2247, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.60796 | val 0.99582
  Epoch 013 - train 0.54201 | val 1.66931
  Classification -> best τ=0.535 (val F1=0.1309)
  Directional -> Accuracy: 0.5814, MCC: 0.1400, F1: 0.6400

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.62706 | val 0.78637
  Epoch 011 - train 0.60754 | val 0.89281
  Classification -> best τ=0.410 (val F1=0.2138)
  Directional -> Accuracy: 0.5172, MCC: 0.1923, F1: 0.2632

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.62434 | val 0.71561
  Epoch 020 - train 0.53859 | val 0.82809
  Classification -> best τ=0.675 (val F1=0.3548)
  Directional -> Accuracy: 0.5238, MCC: 0.0784, F1: 0.4737

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.57973 | val 2.36074
  Epoch 011 - train 0.57200 | val 1.91239
  Classification -> best τ=0.685 (val F1=0.1869)
  Directional -> Accuracy: 0.5227, MCC: 0.0621, F1: 0.2759

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.64435 | val 0.69894
  Epoch 017 - train 0.53675 | val 0.78922
  Classification -> best τ=0.605 (val F1=0.3081)
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.55732 | val 0.92138
  Epoch 011 - train 0.59321 | val 1.01318
  Classification -> best τ=0.540 (val F1=0.1624)
  Directional -> Accuracy: 0.5294, MCC: 0.0513, F1: 0.5714

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.60529 | val 1.37715
  Epoch 011 - train 0.60039 | val 2.15768
  Classification -> best τ=0.330 (val F1=0.3313)
  Directional -> Accuracy: 0.6081, MCC: 0.1800, F1: 0.6882

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.59969 | val 0.93668
  Epoch 013 - train 0.54777 | val 1.14697
  Classification -> best τ=0.455 (val F1=0.2326)
  Directional -> Accuracy: 0.5526, MCC: 0.1715, F1: 0.6792

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.58559 | val 1.62797
  Epoch 013 - train 0.53426 | val 1.91342
  Classification -> best τ=0.700 (val F1=0.2306)
  Directional -> Accuracy: 0.5556, MCC: 0.1612, F1: 0.0909

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.59713 | val 0.94300
  Epoch 012 - train 0.60854 | val 0.81850
  Classification -> best τ=0.400 (val F1=0.3521)
  Directional -> Accuracy: 0.4627, MCC: 0.0930, F1: 0.1429

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.60929 | val 0.73301
  Epoch 012 - train 0.55797 | val 0.83677
  Classification -> best τ=0.415 (val F1=0.3265)
  Directional -> Accuracy: 0.6977, MCC: 0.4094, F1: 0.6667

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.64196 | val 0.73260
  Epoch 014 - train 0.57973 | val 1.03039
  Classification -> best τ=0.525 (val F1=0.4162)
  Directional -> Accuracy: 0.5439, MCC: 0.0820, F1: 0.5000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.57784 | val 0.90825
  Epoch 015 - train 0.48013 | val 1.00205
  Classification -> best τ=0.575 (val F1=0.1871)
  Directional -> Accuracy: 0.4043, MCC: 0.1162, F1: 0.0667

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 16). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.55299 | val 1.79943
  Epoch 013 - train 0.46900 | val 2.05269
  Classification -> best τ=0.490 (val F1=0.3779)
  Directional -> Accuracy: 0.3750, MCC: 0.1175, F1: 0.5283

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.67193 | val 0.97396
  Epoch 012 - train 0.59340 | val 1.01754
  Classification -> best τ=0.385 (val F1=0.1870)
  Directional -> Accuracy: 0.4872, MCC: -0.1435, F1: 0.6429

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 16). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.60467 | val 1.17512
  Epoch 014 - train 0.59766 | val 1.96005
  Classification -> best τ=0.420 (val F1=0.3422)
  Directional -> Accuracy: 0.5395, MCC: 0.2027, F1: 0.6847

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.62424 | val 1.24617
  Epoch 013 - train 0.58234 | val 1.27802
  Classification -> best τ=0.490 (val F1=0.3086)
  Directional -> Accuracy: 0.5106, MCC: 0.0111, F1: 0.6230

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.53790 | val 1.55003
  Epoch 011 - train 0.51326 | val 1.63462
  Classification -> best τ=0.505 (val F1=0.2000)
  Directional -> Accuracy: 0.6000, MCC: 0.1673, F1: 0.7000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.57387 | val 1.02603
  Epoch 017 - train 0.47823 | val 0.93661
  Classification -> best τ=0.370 (val F1=0.3647)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.65689 | val 0.94958
  Epoch 012 - train 0.60923 | val 0.93574
  Classification -> best τ=0.735 (val F1=0.0371)
  Directional -> Accuracy: 0.4912, MCC: 0.1137, F1: 0.1714

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.62770 | val 1.78280
  Epoch 013 - train 0.57501 | val 3.02278
  Classification -> best τ=0.640 (val F1=0.4276)
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.61540 | val 2.98965
  Epoch 012 - train 0.62032 | val 1.82792
  Classification -> best τ=0.515 (val F1=0.2036)
  Directional -> Accuracy: 0.5556, MCC: 0.1052, F1: 0.6129

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.60487 | val 2.23445
  Epoch 013 - train 0.56340 | val 2.20116
  Classification -> best τ=0.630 (val F1=0.2962)
  Directional -> Accuracy: 0.5263, MCC: 0.1360, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...

[I 2026-02-24 23:33:51,919] Trial 65 finished with value: 0.25636440849765296 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 15, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.1, 'dropout': 0.6000000000000001, 'batch_size': 32, 'learning_rate': 0.008028209042388431, 'weight_decay': 0.0003897696569365569, 'lr_patience': 7, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 1.4305465892147498, 'early_stopping_min_delta': 0.0036168090007139657}. Best is trial 32 with value: 0.2908549754956826.

  Epoch 010 - train 0.59235 | val 0.87677
  Epoch 011 - train 0.56542 | val 0.76846
  Classification -> best τ=0.485 (val F1=0.2466)
  Directional -> Accuracy: 0.4194, MCC: -0.1604, F1: 0.4194

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.25636440849765296
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 15
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.72448 | val 0.76946
  Epoch 019 - train 0.68073 | val 0.70151
  Classification -> best τ=0.520 (val F1=0.3541)
  Directional -> Accuracy: 0.5065, MCC: -0.0886, F1: 0.1364

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.66193 | val 0.84070
  Epoch 016 - train 0.68693 | val 0.99996
  Classification -> best τ=0.550 (val F1=0.2431)
  Directional -> Accuracy: 0.6087, MCC: 0.1823, F1: 0.6897

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 16). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.72876 | val 0.72436
  Epoch 012 - train 0.70565 | val 0.68716
  Classification -> best τ=0.580 (val F1=0.3123)
  Directional -> Accuracy: 0.4583, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.69940 | val 0.97584
  Epoch 017 - train 0.67027 | val 0.85778
  Classification -> best τ=0.445 (val F1=0.1417)
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.64321 | val 0.91792
  Epoch 013 - train 0.63306 | val 0.80448
  Classification -> best τ=0.445 (val F1=0.3145)
  Directional -> Accuracy: 0.5962, MCC: 0.1960, F1: 0.6038

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.65165 | val 1.17775
  Epoch 013 - train 0.60045 | val 1.82755
  Classification -> best τ=0.495 (val F1=0.3693)
  Directional -> Accuracy: 0.6042, MCC: 0.2344, F1: 0.6780

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.70243 | val 0.73504
  Epoch 011 - train 0.72193 | val 0.72400
  Classification -> best τ=0.575 (val F1=0.2722)
  Directional -> Accuracy: 0.5571, MCC: 0.1166, F1: 0.5079

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 16). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.76641 | val 2.69927
  Epoch 012 - train 0.60691 | val 2.66613
  Classification -> best τ=0.690 (val F1=0.2619)
  Directional -> Accuracy: 0.4889, MCC: 0.2285, F1: 0.6230

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.68113 | val 0.95130
  Epoch 013 - train 0.69247 | val 1.10738
  Classification -> best τ=0.600 (val F1=0.4743)
  Directional -> Accuracy: 0.5122, MCC: -0.0823, F1: 0.2857

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 16). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 16). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.67696 | val 0.75518
  Epoch 017 - train 0.67325 | val 1.15183
  Classification -> best τ=0.435 (val F1=0.2254)
  Directional -> Accuracy: 0.4507, MCC: 0.0203, F1: 0.5979

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.69262 | val 0.69529
  Epoch 011 - train 0.69757 | val 0.80562
  Classification -> best τ=0.545 (val F1=0.2816)
  Directional -> Accuracy: 0.6275, MCC: 0.3089, F1: 0.3871

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.69875 | val 0.73857
  Epoch 011 - train 0.67019 | val 0.73425
  Classification -> best τ=0.515 (val F1=0.2705)
  Directional -> Accuracy: 0.5254, MCC: 0.0702, F1: 0.3636

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.69981 | val 1.62125
  Epoch 013 - train 0.68565 | val 1.28084
  Classification -> best τ=0.435 (val F1=0.2865)
  Directional -> Accuracy: 0.4651, MCC: 0.1373, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.69971 | val 0.95961
  Epoch 020 - train 0.67509 | val 0.78696
  Epoch 023 - train 0.64015 | val 0.78951
  Classification -> best τ=0.535 (val F1=0.2541)
  Directional -> Accuracy: 0.5574, MCC: 0.1699, F1: 0.3415

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.69790 | val 2.32124
  Epoch 012 - train 0.65924 | val 1.22635
  Classification -> best τ=0.450 (val F1=0.2173)
  Directional -> Accuracy: 0.5283, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.72550 | val 0.77293
  Epoch 012 - train 0.65161 | val 0.80688
  Classification -> best τ=0.465 (val F1=0.3014)
  Directional -> Accuracy: 0.5143, MCC: -0.0761, F1: 0.6667

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.68221 | val 0.80078
  Epoch 012 - train 0.67909 | val 0.90646
  Classification -> best τ=0.745 (val F1=0.2219)
  Directional -> Accuracy: 0.3833, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.71596 | val 0.92198
  Epoch 017 - train 0.68089 | val 1.19035
  Classification -> best τ=0.370 (val F1=0.1674)
  Directional -> Accuracy: 0.5658, MCC: 0.0648, F1: 0.6598

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.67598 | val 0.70388
  Epoch 013 - train 0.67648 | val 0.81506
  Classification -> best τ=0.485 (val F1=0.1150)
  Directional -> Accuracy: 0.4242, MCC: 0.0336, F1: 0.0952

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 16). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.67529 | val 0.81477
  Epoch 013 - train 0.66785 | val 0.89211
  Classification -> best τ=0.450 (val F1=0.3157)
  Directional -> Accuracy: 0.5132, MCC: 0.0659, F1: 0.4127

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.69986 | val 0.68667
  Epoch 020 - train 0.66107 | val 0.69219
  Classification -> best τ=0.545 (val F1=0.2190)
  Directional -> Accuracy: 0.5625, MCC: 0.0562, F1: 0.6557

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.69206 | val 1.42347
  Epoch 014 - train 0.65706 | val 0.97210
  Classification -> best τ=0.840 (val F1=0.2264)
  Directional -> Accuracy: 0.4848, MCC: -0.1240, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.71229 | val 0.82628
  Epoch 011 - train 0.68420 | val 0.83553
  Classification -> best τ=0.585 (val F1=0.2812)
  Directional -> Accuracy: 0.6207, MCC: 0.2785, F1: 0.6071

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.69081 | val 1.56555
  Epoch 013 - train 0.69529 | val 1.33777
  Classification -> best τ=0.365 (val F1=0.2352)
  Directional -> Accuracy: 0.5000, MCC: 0.0590, F1: 0.6207

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.70709 | val 0.65602
  Epoch 014 - train 0.68193 | val 0.67421
  Classification -> best τ=0.515 (val F1=0.4283)
  Directional -> Accuracy: 0.5536, MCC: 0.2064, F1: 0.4186

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.78898 | val 0.78645
  Epoch 012 - train 0.68271 | val 0.76930
  Classification -> best τ=0.600 (val F1=0.3341)
  Directional -> Accuracy: 0.6170, MCC: 0.1869, F1: 0.4375

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.71384 | val 0.69661
  Epoch 013 - train 0.66797 | val 0.68813
  Classification -> best τ=0.605 (val F1=0.1309)
  Directional -> Accuracy: 0.5814, MCC: 0.1270, F1: 0.6538

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.67510 | val 0.74159
  Epoch 015 - train 0.66329 | val 0.79049
  Classification -> best τ=0.385 (val F1=0.3008)
  Directional -> Accuracy: 0.6034, MCC: 0.2157, F1: 0.6102

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.70099 | val 0.71306
  Epoch 018 - train 0.63461 | val 0.77961
  Classification -> best τ=0.535 (val F1=0.3069)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.7077

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.66996 | val 1.33329
  Epoch 011 - train 0.73312 | val 1.37423
  Classification -> best τ=0.490 (val F1=0.0702)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.5217

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.76296 | val 0.74233
  Epoch 016 - train 0.66356 | val 0.73459
  Classification -> best τ=0.750 (val F1=0.3440)
  Directional -> Accuracy: 0.5909, MCC: 0.2516, F1: 0.5000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.66734 | val 0.84365
  Epoch 011 - train 0.62994 | val 0.86476
  Classification -> best τ=0.420 (val F1=0.2668)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.69144 | val 0.77499
  Epoch 012 - train 0.67529 | val 0.85900
  Classification -> best τ=0.630 (val F1=0.2739)
  Directional -> Accuracy: 0.4324, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.64412 | val 0.71982
  Epoch 013 - train 0.59232 | val 0.79727
  Classification -> best τ=0.420 (val F1=0.3223)
  Directional -> Accuracy: 0.6053, MCC: 0.2582, F1: 0.6939

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.72366 | val 0.86612
  Epoch 011 - train 0.68378 | val 0.83504
  Classification -> best τ=0.570 (val F1=0.2004)
  Directional -> Accuracy: 0.6889, MCC: 0.3884, F1: 0.6957

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.69217 | val 0.79030
  Epoch 013 - train 0.66095 | val 0.71787
  Classification -> best τ=0.265 (val F1=0.3431)
  Directional -> Accuracy: 0.5373, MCC: 0.1036, F1: 0.5231

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.65555 | val 0.66362
  Epoch 020 - train 0.67788 | val 0.74095
  Classification -> best τ=0.400 (val F1=0.2775)
  Directional -> Accuracy: 0.5814, MCC: 0.1930, F1: 0.4706

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.67930 | val 0.73431
  Epoch 015 - train 0.69618 | val 0.84059
  Classification -> best τ=0.440 (val F1=0.2326)
  Directional -> Accuracy: 0.5789, MCC: 0.2313, F1: 0.6667

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.66977 | val 0.70507
  Epoch 014 - train 0.63741 | val 0.77426
  Classification -> best τ=0.495 (val F1=0.3893)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 16). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.58112 | val 1.23605
  Epoch 012 - train 0.56713 | val 1.77759
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.76064 | val 0.97696
  Epoch 011 - train 0.85420 | val 1.02898
  Classification -> best τ=0.380 (val F1=0.1870)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.7000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 16). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.68192 | val 0.78514
  Epoch 011 - train 0.69747 | val 0.76581
  Classification -> best τ=0.375 (val F1=0.4446)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.71957 | val 0.69132
  Epoch 015 - train 0.66008 | val 0.75986
  Classification -> best τ=0.485 (val F1=0.2080)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.65297 | val 0.86013
  Epoch 012 - train 0.67865 | val 1.05178
  Classification -> best τ=0.605 (val F1=0.3686)
  Directional -> Accuracy: 0.5111, MCC: 0.0299, F1: 0.5217

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.67151 | val 0.68952
  Epoch 020 - train 0.69811 | val 0.72547
  Epoch 021 - train 0.62949 | val 0.73309
  Classification -> best τ=0.490 (val F1=0.3647)
  Directional -> Accuracy: 0.4500, MCC: 0.0605, F1: 0.5000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.70781 | val 0.82912
  Epoch 013 - train 0.68122 | val 0.83768
  Classification -> best τ=0.615 (val F1=0.2469)
  Directional -> Accuracy: 0.5614, MCC: 0.1802, F1: 0.4681

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.64189 | val 2.65001
  Epoch 011 - train 0.66598 | val 2.91296
  Classification -> best τ=0.550 (val F1=0.3147)
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.70680 | val 1.05979
  Epoch 012 - train 0.67522 | val 1.15284
  Classification -> best τ=0.455 (val F1=0.2020)
  Directional -> Accuracy: 0.5741, MCC: 0.1437, F1: 0.6349

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.66423 | val 0.97945
  Epoch 012 - train 0.67935 | val 1.49465
  Classification -> best τ=0.480 (val F1=0.1518)
  Directional -> Accuracy: 0.4737, MCC: -0.0939, F1: 0.6154

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.72615 | val 0.69072
  Epoch 011 - train 0.68327 | val 0.67461
  Classification -> best τ=0.370 (val F1=0.2782)
  Directional -> Accuracy: 0.4839, MCC: 0.0000, F1: 0.6522

[I 2026-02-24 23:35:10,588] Trial 66 finished with value: 0.2669938339280849 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 15, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 32, 'learning_rate': 0.009673901609815534, 'weight_decay': 0.00011973986763236058, 'lr_patience': 7, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.494863003584783, 'early_stopping_min_delta': 0.001987994110211876}. Best is trial 32 with value: 0.2908549754956826.

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2669938339280849
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 15
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.68396 | val 1.29168
  Epoch 015 - train 0.67056 | val 0.95735
  Classification -> best τ=0.440 (val F1=0.1307)
  Directional -> Accuracy: 0.4545, MCC: -0.0812, F1: 0.4615

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.63366 | val 0.78364
  Epoch 014 - train 0.66405 | val 1.24681
  Classification -> best τ=0.460 (val F1=0.2431)
  Directional -> Accuracy: 0.6522, MCC: 0.2923, F1: 0.6923

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 16). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.66054 | val 0.76327
  Epoch 012 - train 0.69959 | val 0.72031
  Classification -> best τ=0.505 (val F1=0.3020)
  Directional -> Accuracy: 0.5208, MCC: 0.0384, F1: 0.5490

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.68860 | val 1.18934
  Epoch 012 - train 0.64897 | val 0.86967
  Classification -> best τ=0.485 (val F1=0.1217)
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.70327 | val 1.04810
  Epoch 011 - train 0.63562 | val 0.89670
  Classification -> best τ=0.560 (val F1=0.2604)
  Directional -> Accuracy: 0.3846, MCC: -0.2262, F1: 0.3846

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.61776 | val 0.69284
  Epoch 019 - train 0.67208 | val 1.84435
  Classification -> best τ=0.430 (val F1=0.4893)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.70799 | val 0.69382
  Epoch 020 - train 0.68405 | val 0.73082
  Epoch 021 - train 0.69667 | val 0.74841
  Classification -> best τ=0.400 (val F1=0.2887)
  Directional -> Accuracy: 0.4571, MCC: 0.2010, F1: 0.5957

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 16). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.62924 | val 2.71091
  Epoch 011 - train 0.58655 | val 2.62370
  Classification -> best τ=0.635 (val F1=0.1512)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.66661 | val 0.75251
  Epoch 013 - train 0.61326 | val 0.75053
  Classification -> best τ=0.515 (val F1=0.4266)
  Directional -> Accuracy: 0.5366, MCC: -0.0130, F1: 0.3448

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 16). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 16). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.67559 | val 0.89343
  Epoch 015 - train 0.67753 | val 1.39835
  Classification -> best τ=0.345 (val F1=0.1850)
  Directional -> Accuracy: 0.4366, MCC: 0.0000, F1: 0.6078

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.67494 | val 1.50229
  Epoch 013 - train 0.68004 | val 1.03753
  Classification -> best τ=0.415 (val F1=0.2069)
  Directional -> Accuracy: 0.5686, MCC: 0.1306, F1: 0.5217

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.67153 | val 0.88075
  Epoch 014 - train 0.63724 | val 0.91245
  Classification -> best τ=0.655 (val F1=0.2987)
  Directional -> Accuracy: 0.5254, MCC: 0.1065, F1: 0.2222

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.69264 | val 0.88917
  Epoch 013 - train 0.70364 | val 1.03872
  Classification -> best τ=0.595 (val F1=0.2644)
  Directional -> Accuracy: 0.5349, MCC: -0.0598, F1: 0.0909

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.67849 | val 0.64779
  Epoch 012 - train 0.65325 | val 0.64111
  Classification -> best τ=0.335 (val F1=0.3019)
  Directional -> Accuracy: 0.5246, MCC: 0.0531, F1: 0.6506

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.67445 | val 1.39753
  Epoch 013 - train 0.66467 | val 1.27963
  Classification -> best τ=0.775 (val F1=0.2262)
  Directional -> Accuracy: 0.5283, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.69004 | val 0.82811
  Epoch 012 - train 0.61213 | val 0.74918
  Classification -> best τ=0.165 (val F1=0.2927)
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.67355 | val 0.77712
  Epoch 011 - train 0.68478 | val 0.77629
  Classification -> best τ=0.680 (val F1=0.2219)
  Directional -> Accuracy: 0.3833, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.68208 | val 0.95185
  Epoch 011 - train 0.69111 | val 0.78283
  Classification -> best τ=0.500 (val F1=0.1289)
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.70625 | val 0.75184
  Epoch 018 - train 0.63027 | val 1.17989
  Classification -> best τ=0.260 (val F1=0.2778)
  Directional -> Accuracy: 0.5000, MCC: 0.0944, F1: 0.4211

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 16). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.69257 | val 0.97217
  Epoch 014 - train 0.67186 | val 0.93517
  Classification -> best τ=0.465 (val F1=0.2602)
  Directional -> Accuracy: 0.4737, MCC: 0.1067, F1: 0.0476

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.68531 | val 0.86912
  Epoch 020 - train 0.60104 | val 0.90619
  Epoch 026 - train 0.66591 | val 0.96485
  Classification -> best τ=0.605 (val F1=0.4575)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.71392 | val 1.25242
  Epoch 012 - train 0.69770 | val 1.42128
  Classification -> best τ=0.590 (val F1=0.2251)
  Directional -> Accuracy: 0.5152, MCC: 0.0407, F1: 0.2727

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.68179 | val 0.83044
  Epoch 014 - train 0.72111 | val 0.85582
  Classification -> best τ=0.755 (val F1=0.3487)
  Directional -> Accuracy: 0.5172, MCC: 0.1339, F1: 0.3913

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.66265 | val 1.08760
  Epoch 013 - train 0.68282 | val 1.79825
  Classification -> best τ=0.355 (val F1=0.1878)
  Directional -> Accuracy: 0.5758, MCC: 0.1431, F1: 0.5172

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.68438 | val 0.66074
  Epoch 014 - train 0.62787 | val 0.72045
  Classification -> best τ=0.440 (val F1=0.4442)
  Directional -> Accuracy: 0.5714, MCC: 0.2385, F1: 0.4545

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.64968 | val 0.74176
  Epoch 019 - train 0.61008 | val 0.95292
  Classification -> best τ=0.615 (val F1=0.2582)
  Directional -> Accuracy: 0.5745, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.71036 | val 0.68085
  Epoch 015 - train 0.66429 | val 0.96182
  Classification -> best τ=0.600 (val F1=0.1309)
  Directional -> Accuracy: 0.4651, MCC: -0.0140, F1: 0.4103

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.65861 | val 0.72378
  Epoch 015 - train 0.62370 | val 0.84280
  Classification -> best τ=0.355 (val F1=0.2129)
  Directional -> Accuracy: 0.5345, MCC: -0.0033, F1: 0.6667

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.75468 | val 0.71647
  Epoch 018 - train 0.65087 | val 0.75684
  Classification -> best τ=0.530 (val F1=0.3707)
  Directional -> Accuracy: 0.5476, MCC: 0.0310, F1: 0.6885

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.66431 | val 0.98532
  Epoch 012 - train 0.66101 | val 1.16813
  Classification -> best τ=0.600 (val F1=0.1869)
  Directional -> Accuracy: 0.4773, MCC: -0.0455, F1: 0.4651

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.69630 | val 0.68717
  Epoch 013 - train 0.69769 | val 0.75721
  Classification -> best τ=0.695 (val F1=0.1688)
  Directional -> Accuracy: 0.3864, MCC: -0.2178, F1: 0.3721

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.61044 | val 0.78202
  Epoch 012 - train 0.60206 | val 0.78424
  Classification -> best τ=0.330 (val F1=0.3898)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.67745 | val 0.74893
  Epoch 013 - train 0.63442 | val 0.80284
  Classification -> best τ=0.370 (val F1=0.2763)
  Directional -> Accuracy: 0.5676, MCC: 0.2241, F1: 0.4839

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.68244 | val 0.81347
  Epoch 013 - train 0.64888 | val 1.15199
  Classification -> best τ=0.450 (val F1=0.3125)
  Directional -> Accuracy: 0.4737, MCC: -0.0555, F1: 0.5455

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.67535 | val 0.89707
  Epoch 011 - train 0.63298 | val 0.94074
  Classification -> best τ=0.585 (val F1=0.2817)
  Directional -> Accuracy: 0.5333, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.66048 | val 0.67394
  Epoch 020 - train 0.66537 | val 0.76372
  Classification -> best τ=0.175 (val F1=0.3767)
  Directional -> Accuracy: 0.5970, MCC: 0.1826, F1: 0.6400

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.65921 | val 0.68367
  Epoch 012 - train 0.70889 | val 0.77198
  Classification -> best τ=0.415 (val F1=0.3265)
  Directional -> Accuracy: 0.6512, MCC: 0.3392, F1: 0.5714

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.63693 | val 0.87853
  Epoch 012 - train 0.66254 | val 0.79706
  Classification -> best τ=0.440 (val F1=0.2718)
  Directional -> Accuracy: 0.5614, MCC: 0.2181, F1: 0.6667

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.61846 | val 1.13651
  Epoch 013 - train 0.65159 | val 0.78971
  Classification -> best τ=0.540 (val F1=0.2851)
  Directional -> Accuracy: 0.4043, MCC: -0.0121, F1: 0.1765

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 16). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.60912 | val 1.38666
  Epoch 014 - train 0.56791 | val 0.92310
  Classification -> best τ=0.350 (val F1=0.1391)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.70872 | val 0.82212
  Epoch 013 - train 0.65026 | val 0.79757
  Classification -> best τ=0.310 (val F1=0.1870)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.7000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 16). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.68286 | val 0.84123
  Epoch 012 - train 0.63960 | val 0.93298
  Classification -> best τ=0.375 (val F1=0.3218)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.69310 | val 0.86963
  Epoch 014 - train 0.66239 | val 1.37680
  Classification -> best τ=0.530 (val F1=0.3119)
  Directional -> Accuracy: 0.5319, MCC: 0.1460, F1: 0.2143

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.63263 | val 1.23580
  Epoch 011 - train 0.61520 | val 1.30715
  Classification -> best τ=0.420 (val F1=0.2000)
  Directional -> Accuracy: 0.6000, MCC: 0.1673, F1: 0.7000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.75153 | val 0.79087
  Epoch 013 - train 0.68783 | val 0.76188
  Classification -> best τ=0.585 (val F1=0.4497)
  Directional -> Accuracy: 0.6500, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.70087 | val 0.67727
  Epoch 020 - train 0.66342 | val 0.70516
  Epoch 023 - train 0.65890 | val 0.77228
  Classification -> best τ=0.560 (val F1=0.2975)
  Directional -> Accuracy: 0.5439, MCC: 0.0168, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.66113 | val 0.72193
  Epoch 011 - train 0.64907 | val 0.96169
  Classification -> best τ=0.635 (val F1=0.3973)
  Directional -> Accuracy: 0.5263, MCC: 0.0882, F1: 0.6087

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.67846 | val 1.54285
  Epoch 014 - train 0.71552 | val 1.34776
  Classification -> best τ=0.200 (val F1=0.3730)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.68496 | val 1.13082
  Epoch 014 - train 0.64226 | val 1.49767
  Classification -> best τ=0.560 (val F1=0.2157)
  Directional -> Accuracy: 0.5439, MCC: 0.0915, F1: 0.6389

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.67112 | val 1.00208

[I 2026-02-24 23:36:35,158] Trial 67 finished with value: 0.2766743814861254 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 15, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 32, 'learning_rate': 0.006929637538205718, 'weight_decay': 4.012158007246824e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.6228218049820917, 'early_stopping_min_delta': 0.001759908027333876}. Best is trial 32 with value: 0.2908549754956826.

  Epoch 018 - train 0.66751 | val 0.67744
  Classification -> best τ=0.395 (val F1=0.3502)
  Directional -> Accuracy: 0.5484, MCC: 0.1110, F1: 0.6000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2766743814861254
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 15
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.71717 | val 0.72066
  Epoch 019 - train 0.70577 | val 0.81703
  Classification -> best τ=0.460 (val F1=0.3210)
  Directional -> Accuracy: 0.4545, MCC: -0.1856, F1: 0.1600

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.66823 | val 0.76463
  Epoch 018 - train 0.61184 | val 1.14966
  Classification -> best τ=0.410 (val F1=0.3716)
  Directional -> Accuracy: 0.5870, MCC: 0.1202, F1: 0.6984

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 16). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.70879 | val 0.76178
  Epoch 011 - train 0.70341 | val 0.80888
  Classification -> best τ=0.550 (val F1=0.1794)
  Directional -> Accuracy: 0.4792, MCC: -0.0316, F1: 0.4681

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.72838 | val 0.95649
  Epoch 011 - train 0.71482 | val 0.76188
  Classification -> best τ=0.485 (val F1=0.2137)
  Directional -> Accuracy: 0.6267, MCC: 0.2366, F1: 0.6957

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.67341 | val 1.35818
  Epoch 016 - train 0.65804 | val 3.14721
  Classification -> best τ=0.520 (val F1=0.4276)
  Directional -> Accuracy: 0.7500, MCC: 0.4989, F1: 0.7636

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.66618 | val 0.72192
  Epoch 018 - train 0.66644 | val 0.70983
  Classification -> best τ=0.480 (val F1=0.3393)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.73916 | val 0.70553
  Epoch 016 - train 0.71106 | val 0.82611
  Classification -> best τ=0.435 (val F1=0.2683)
  Directional -> Accuracy: 0.5571, MCC: 0.1987, F1: 0.5867

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 16). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.74804 | val 1.51949
  Epoch 011 - train 0.64116 | val 1.58439
  Classification -> best τ=0.490 (val F1=0.1048)
  Directional -> Accuracy: 0.4000, MCC: -0.1764, F1: 0.5714

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.69669 | val 0.70560
  Epoch 020 - train 0.69991 | val 0.87024
  Epoch 028 - train 0.63876 | val 0.68795
  Classification -> best τ=0.665 (val F1=0.4315)
  Directional -> Accuracy: 0.6341, MCC: 0.0916, F1: 0.2105

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 16). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 16). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.71522 | val 0.75638
  Epoch 014 - train 0.71935 | val 0.74356
  Classification -> best τ=0.505 (val F1=0.0887)
  Directional -> Accuracy: 0.5070, MCC: 0.0544, F1: 0.5455

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.75871 | val 0.80840
  Epoch 011 - train 0.65472 | val 0.89233
  Classification -> best τ=0.410 (val F1=0.1448)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.74158 | val 0.72298
  Epoch 012 - train 0.72173 | val 0.86921
  Classification -> best τ=0.655 (val F1=0.2394)
  Directional -> Accuracy: 0.5932, MCC: 0.2184, F1: 0.4783

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.71212 | val 0.72260
  Epoch 016 - train 0.63331 | val 1.25243
  Classification -> best τ=0.585 (val F1=0.2972)
  Directional -> Accuracy: 0.4419, MCC: -0.1600, F1: 0.2941

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.67672 | val 0.75071
  Epoch 016 - train 0.68554 | val 0.64592
  Classification -> best τ=0.250 (val F1=0.3734)
  Directional -> Accuracy: 0.5574, MCC: 0.1236, F1: 0.6494

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.65801 | val 1.06061
  Epoch 018 - train 0.62828 | val 1.42506
  Classification -> best τ=0.465 (val F1=0.2540)
  Directional -> Accuracy: 0.4717, MCC: 0.0000, F1: 0.6410

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.62552 | val 0.84460
  Epoch 011 - train 0.67111 | val 0.81541
  Classification -> best τ=0.590 (val F1=0.2952)
  Directional -> Accuracy: 0.4571, MCC: -0.0702, F1: 0.4242

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.72672 | val 0.79143
  Epoch 012 - train 0.68240 | val 0.95426
  Classification -> best τ=0.565 (val F1=0.2763)
  Directional -> Accuracy: 0.4667, MCC: -0.2482, F1: 0.6190

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.68790 | val 0.74826
  Epoch 020 - train 0.69091 | val 0.70507
  Epoch 021 - train 0.70346 | val 0.72895
  Classification -> best τ=0.615 (val F1=0.2462)
  Directional -> Accuracy: 0.3947, MCC: -0.1023, F1: 0.2333

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.69618 | val 0.86437
  Epoch 012 - train 0.69036 | val 0.74038
  Classification -> best τ=0.580 (val F1=0.1822)
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 16). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.69729 | val 0.77685
  Epoch 013 - train 0.69021 | val 0.77067
  Classification -> best τ=0.550 (val F1=0.2110)
  Directional -> Accuracy: 0.4605, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.72374 | val 0.73918
  Epoch 013 - train 0.69664 | val 0.77708
  Classification -> best τ=0.510 (val F1=0.3555)
  Directional -> Accuracy: 0.4792, MCC: -0.1237, F1: 0.5902

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.67615 | val 1.68175
  Epoch 013 - train 0.72619 | val 1.08083
  Classification -> best τ=0.400 (val F1=0.1578)
  Directional -> Accuracy: 0.6212, MCC: 0.2434, F1: 0.6377

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.68823 | val 1.01670
  Epoch 011 - train 0.67460 | val 1.12033
  Classification -> best τ=0.660 (val F1=0.3644)
  Directional -> Accuracy: 0.5000, MCC: 0.0145, F1: 0.5085

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.71243 | val 1.58868
  Epoch 011 - train 0.69026 | val 1.99727
  Classification -> best τ=0.525 (val F1=0.1895)
  Directional -> Accuracy: 0.5455, MCC: 0.0741, F1: 0.4231

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.70236 | val 0.80265
  Epoch 014 - train 0.69106 | val 1.00522
  Classification -> best τ=0.530 (val F1=0.3735)
  Directional -> Accuracy: 0.5893, MCC: 0.1452, F1: 0.6849

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.63974 | val 0.78187
  Epoch 012 - train 0.57954 | val 0.85559
  Classification -> best τ=0.725 (val F1=0.3225)
  Directional -> Accuracy: 0.5532, MCC: -0.1269, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.65835 | val 0.68139
  Epoch 017 - train 0.66892 | val 0.73333
  Classification -> best τ=0.640 (val F1=0.1874)
  Directional -> Accuracy: 0.4419, MCC: -0.0573, F1: 0.3684

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.68495 | val 0.67162
  Epoch 020 - train 0.63888 | val 0.69004
  Classification -> best τ=0.405 (val F1=0.3237)
  Directional -> Accuracy: 0.5517, MCC: 0.0874, F1: 0.6061

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.77004 | val 0.68002
  Epoch 019 - train 0.64956 | val 0.75418
  Classification -> best τ=0.445 (val F1=0.3844)
  Directional -> Accuracy: 0.5714, MCC: 0.1090, F1: 0.7000

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.66827 | val 0.98646
  Epoch 011 - train 0.65353 | val 0.99728
  Classification -> best τ=0.595 (val F1=0.1869)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0833

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.68195 | val 0.75775
  Epoch 011 - train 0.66570 | val 0.74536
  Classification -> best τ=0.715 (val F1=0.2212)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.65685 | val 0.69037
  Epoch 013 - train 0.65064 | val 0.78438
  Classification -> best τ=0.400 (val F1=0.2696)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.69697 | val 0.76160
  Epoch 020 - train 0.71383 | val 1.11683
  Epoch 023 - train 0.64483 | val 1.20339
  Classification -> best τ=0.435 (val F1=0.3259)
  Directional -> Accuracy: 0.5405, MCC: 0.0362, F1: 0.6304

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.67930 | val 0.69783
  Epoch 013 - train 0.61223 | val 0.71860
  Classification -> best τ=0.490 (val F1=0.4045)
  Directional -> Accuracy: 0.5526, MCC: 0.1291, F1: 0.6531

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.73411 | val 0.93106
  Epoch 011 - train 0.69193 | val 0.98801
  Classification -> best τ=0.500 (val F1=0.4677)
  Directional -> Accuracy: 0.5333, MCC: 0.1557, F1: 0.6441

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.67700 | val 0.73646
  Epoch 012 - train 0.67970 | val 0.71090
  Classification -> best τ=0.370 (val F1=0.3521)
  Directional -> Accuracy: 0.4328, MCC: -0.1079, F1: 0.4062

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.72268 | val 0.71085
  Epoch 020 - train 0.67552 | val 0.84104
  Epoch 021 - train 0.64462 | val 0.72068
  Classification -> best τ=0.505 (val F1=0.3816)
  Directional -> Accuracy: 0.6512, MCC: 0.3392, F1: 0.5714

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.63265 | val 0.72242
  Epoch 020 - train 0.66306 | val 0.86360
  Epoch 023 - train 0.61325 | val 0.79584
  Classification -> best τ=0.420 (val F1=0.2094)
  Directional -> Accuracy: 0.4912, MCC: -0.0148, F1: 0.4912

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.69460 | val 0.68527
  Epoch 013 - train 0.66317 | val 0.85086
  Classification -> best τ=0.430 (val F1=0.2922)
  Directional -> Accuracy: 0.5319, MCC: -0.0118, F1: 0.6333

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 16). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.64028 | val 1.03080
  Epoch 011 - train 0.58762 | val 1.38980
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.68525 | val 0.75575
  Epoch 014 - train 0.66305 | val 0.74800
  Classification -> best τ=0.450 (val F1=0.2431)
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.0000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 16). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.72601 | val 0.72578
  Epoch 013 - train 0.67130 | val 0.71392
  Classification -> best τ=0.575 (val F1=0.2734)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6415

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.70225 | val 0.95303
  Epoch 015 - train 0.68671 | val 0.80387
  Classification -> best τ=0.525 (val F1=0.2544)
  Directional -> Accuracy: 0.5106, MCC: 0.0437, F1: 0.3030

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.67394 | val 0.96095
  Epoch 011 - train 0.62393 | val 1.02860
  Classification -> best τ=0.540 (val F1=0.1890)
  Directional -> Accuracy: 0.4444, MCC: -0.0913, F1: 0.4186

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.67758 | val 0.74148
  Epoch 012 - train 0.68495 | val 0.84402
  Classification -> best τ=0.605 (val F1=0.2966)
  Directional -> Accuracy: 0.6500, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.73903 | val 0.75190
  Epoch 020 - train 0.67218 | val 0.78011
  Epoch 022 - train 0.66699 | val 0.89255
  Classification -> best τ=0.480 (val F1=0.2054)
  Directional -> Accuracy: 0.5263, MCC: -0.0207, F1: 0.6667

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.68411 | val 1.95388
  Epoch 011 - train 0.65812 | val 1.98166
  Classification -> best τ=0.585 (val F1=0.4552)
  Directional -> Accuracy: 0.5263, MCC: 0.0970, F1: 0.6197

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.71210 | val 0.95851
  Epoch 013 - train 0.62999 | val 0.81766
  Classification -> best τ=0.450 (val F1=0.1508)
  Directional -> Accuracy: 0.5741, MCC: 0.2517, F1: 0.7089

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.72988 | val 1.64660
  Epoch 014 - train 0.69297 | val 1.72739
  Classification -> best τ=0.450 (val F1=0.0518)
  Directional -> Accuracy: 0.5965, MCC: 0.2739, F1: 0.7089

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.71974 | val 0.84132

[I 2026-02-24 23:38:35,291] Trial 68 finished with value: 0.27118219973708385 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 15, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 32, 'learning_rate': 0.009990473384051433, 'weight_decay': 3.719535354600491e-05, 'lr_patience': 7, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.6569098216718114, 'early_stopping_min_delta': 0.001923212720684691}. Best is trial 32 with value: 0.2908549754956826.

  Epoch 019 - train 0.65835 | val 1.09740
  Classification -> best τ=0.280 (val F1=0.4038)
  Directional -> Accuracy: 0.4516, MCC: -0.0919, F1: 0.5000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.27118219973708385
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 15
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.71235 | val 0.77041
  Epoch 020 - train 0.72383 | val 0.81424
  Epoch 030 - train 0.67866 | val 0.69788
  Classification -> best τ=0.535 (val F1=0.2851)
  Directional -> Accuracy: 0.5065, MCC: -0.0886, F1: 0.1364

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.64283 | val 0.74226
  Epoch 015 - train 0.64786 | val 0.79438
  Classification -> best τ=0.490 (val F1=0.1962)
  Directional -> Accuracy: 0.5870, MCC: 0.1252, F1: 0.6885

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 16). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.75745 | val 0.72275
  Epoch 020 - train 0.65528 | val 0.78494
  Epoch 021 - train 0.67570 | val 0.69847
  Classification -> best τ=0.555 (val F1=0.3361)
  Directional -> Accuracy: 0.3958, MCC: -0.1917, F1: 0.2927

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.65757 | val 0.78100
  Epoch 011 - train 0.80303 | val 0.72013
  Classification -> best τ=0.460 (val F1=0.1917)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.72115 | val 0.74536
  Epoch 015 - train 0.63985 | val 1.30419
  Classification -> best τ=0.570 (val F1=0.3913)
  Directional -> Accuracy: 0.6346, MCC: 0.3163, F1: 0.5778

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.63412 | val 0.79485
  Epoch 018 - train 0.66477 | val 0.78846
  Classification -> best τ=0.510 (val F1=0.3119)
  Directional -> Accuracy: 0.4583, MCC: -0.1118, F1: 0.5938

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.73862 | val 0.70874
  Epoch 012 - train 0.69447 | val 0.72120
  Classification -> best τ=0.520 (val F1=0.3269)
  Directional -> Accuracy: 0.4857, MCC: -0.0714, F1: 0.3571

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 16). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.64607 | val 1.41618
  Epoch 011 - train 0.70473 | val 1.34272
  Classification -> best τ=0.460 (val F1=0.1512)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.70735 | val 0.65180
  Epoch 020 - train 0.73922 | val 3.99282
  Classification -> best τ=0.450 (val F1=0.3877)
  Directional -> Accuracy: 0.3659, MCC: 0.0000, F1: 0.5357

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 16). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 16). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.68917 | val 1.19762
  Epoch 012 - train 0.63735 | val 1.37367
  Classification -> best τ=0.600 (val F1=0.2456)
  Directional -> Accuracy: 0.4366, MCC: 0.0000, F1: 0.6078

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.73238 | val 0.68152
  Epoch 011 - train 0.73468 | val 0.75379
  Classification -> best τ=0.390 (val F1=0.2816)
  Directional -> Accuracy: 0.5098, MCC: -0.0242, F1: 0.2424

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.68534 | val 0.68363
  Epoch 016 - train 0.72112 | val 0.68393
  Classification -> best τ=0.480 (val F1=0.2333)
  Directional -> Accuracy: 0.5085, MCC: 0.0000, F1: 0.6742

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.67550 | val 0.89355
  Epoch 012 - train 0.68624 | val 1.11621
  Classification -> best τ=0.620 (val F1=0.2501)
  Directional -> Accuracy: 0.4651, MCC: 0.1373, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.67937 | val 0.62253
  Epoch 020 - train 0.68786 | val 0.64158
  Classification -> best τ=0.215 (val F1=0.3336)
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.67554 | val 1.85214
  Epoch 013 - train 0.66398 | val 2.09946
  Classification -> best τ=0.555 (val F1=0.3389)
  Directional -> Accuracy: 0.5660, MCC: 0.2096, F1: 0.1481

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.65613 | val 0.89838
  Epoch 013 - train 0.70214 | val 0.86363
  Classification -> best τ=0.600 (val F1=0.3242)
  Directional -> Accuracy: 0.4857, MCC: 0.0091, F1: 0.3793

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.65284 | val 1.30284
  Epoch 011 - train 0.71562 | val 1.17579
  Classification -> best τ=0.420 (val F1=0.1541)
  Directional -> Accuracy: 0.5833, MCC: -0.0067, F1: 0.7191

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.70232 | val 1.12588
  Epoch 012 - train 0.68995 | val 1.24072
  Classification -> best τ=0.535 (val F1=0.0913)
  Directional -> Accuracy: 0.5658, MCC: 0.1072, F1: 0.6292

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.68624 | val 0.76396
  Epoch 015 - train 0.73780 | val 0.74354
  Classification -> best τ=0.390 (val F1=0.2409)
  Directional -> Accuracy: 0.5000, MCC: 0.1525, F1: 0.3529

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 16). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.67062 | val 0.90231
  Epoch 020 - train 0.72904 | val 0.78914
  Epoch 030 - train 0.62953 | val 1.01757
  Classification -> best τ=0.585 (val F1=0.2838)
  Directional -> Accuracy: 0.4605, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.63011 | val 0.79699
  Epoch 016 - train 0.71093 | val 0.68817
  Classification -> best τ=0.495 (val F1=0.3130)
  Directional -> Accuracy: 0.4167, MCC: -0.0497, F1: 0.3333

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.72601 | val 0.76121
  Epoch 014 - train 0.71222 | val 0.92168
  Classification -> best τ=0.360 (val F1=0.1669)
  Directional -> Accuracy: 0.4091, MCC: -0.1861, F1: 0.4658

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.70750 | val 0.87596
  Epoch 017 - train 0.73043 | val 0.83026
  Classification -> best τ=0.560 (val F1=0.3203)
  Directional -> Accuracy: 0.5862, MCC: 0.2545, F1: 0.5200

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.70002 | val 1.46913
  Epoch 012 - train 0.72218 | val 2.37367
  Classification -> best τ=0.510 (val F1=0.2319)
  Directional -> Accuracy: 0.4394, MCC: -0.1782, F1: 0.2128

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.66020 | val 0.73561
  Epoch 017 - train 0.64948 | val 0.88980
  Classification -> best τ=0.555 (val F1=0.5105)
  Directional -> Accuracy: 0.5179, MCC: 0.1373, F1: 0.3415

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.63822 | val 0.72119
  Epoch 015 - train 0.59207 | val 1.01645
  Classification -> best τ=0.585 (val F1=0.1807)
  Directional -> Accuracy: 0.5745, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.70090 | val 0.68983
  Epoch 017 - train 0.67039 | val 0.71710
  Classification -> best τ=0.585 (val F1=0.1366)
  Directional -> Accuracy: 0.5581, MCC: 0.0427, F1: 0.6667

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.68225 | val 0.71623
  Epoch 016 - train 0.70432 | val 0.82175
  Classification -> best τ=0.480 (val F1=0.2785)
  Directional -> Accuracy: 0.5172, MCC: 0.1923, F1: 0.2632

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.74021 | val 0.70176
  Epoch 012 - train 0.71555 | val 0.81674
  Classification -> best τ=0.520 (val F1=0.2802)
  Directional -> Accuracy: 0.5714, MCC: 0.1194, F1: 0.7097

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.66882 | val 1.02268
  Epoch 011 - train 0.69635 | val 0.99339
  Classification -> best τ=0.470 (val F1=0.1869)
  Directional -> Accuracy: 0.5682, MCC: 0.1365, F1: 0.5581

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.70504 | val 0.65255
  Epoch 011 - train 0.69284 | val 0.67834
  Classification -> best τ=0.585 (val F1=0.3103)
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.58656 | val 0.62385
  Epoch 020 - train 0.61241 | val 1.06202
  Classification -> best τ=0.210 (val F1=0.3898)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.73553 | val 0.67948
  Epoch 019 - train 0.67653 | val 0.75157
  Classification -> best τ=0.285 (val F1=0.3520)
  Directional -> Accuracy: 0.5811, MCC: 0.1883, F1: 0.5753

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.84177 | val 0.78814
  Epoch 017 - train 0.62452 | val 0.84175
  Classification -> best τ=0.515 (val F1=0.3223)
  Directional -> Accuracy: 0.5789, MCC: 0.1857, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.70901 | val 0.86202
  Epoch 012 - train 0.71456 | val 0.94435
  Classification -> best τ=0.425 (val F1=0.2922)
  Directional -> Accuracy: 0.5111, MCC: 0.1048, F1: 0.6333

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.70428 | val 0.73103
  Epoch 013 - train 0.67361 | val 0.81671
  Classification -> best τ=0.380 (val F1=0.2908)
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.73375 | val 0.69857
  Epoch 015 - train 0.69254 | val 0.77814
  Classification -> best τ=0.510 (val F1=0.2810)
  Directional -> Accuracy: 0.5116, MCC: 0.0641, F1: 0.2222

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.69500 | val 0.70843
  Epoch 011 - train 0.71297 | val 0.74019
  Classification -> best τ=0.370 (val F1=0.3820)
  Directional -> Accuracy: 0.4912, MCC: 0.1268, F1: 0.6506

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.63287 | val 0.85210
  Epoch 013 - train 0.65840 | val 0.87010
  Classification -> best τ=0.410 (val F1=0.2718)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 16). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.61259 | val 0.91318
  Epoch 014 - train 0.60372 | val 1.21920
  Classification -> best τ=0.445 (val F1=0.5530)
  Directional -> Accuracy: 0.3750, MCC: 0.1175, F1: 0.5283

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.71236 | val 0.75179
  Epoch 015 - train 0.71507 | val 0.87234
  Classification -> best τ=0.450 (val F1=0.4692)
  Directional -> Accuracy: 0.6410, MCC: 0.2809, F1: 0.7200

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 16). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.68253 | val 0.87725
  Epoch 013 - train 0.68258 | val 0.80820
  Classification -> best τ=0.495 (val F1=0.2812)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.67817 | val 1.32065
  Epoch 011 - train 0.69081 | val 1.59103
  Classification -> best τ=0.650 (val F1=0.1733)
  Directional -> Accuracy: 0.5106, MCC: 0.0617, F1: 0.2069

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.66351 | val 0.83082
  Epoch 016 - train 0.65406 | val 1.27739
  Classification -> best τ=0.325 (val F1=0.1387)
  Directional -> Accuracy: 0.5556, MCC: 0.0520, F1: 0.6774

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.74970 | val 0.81816
  Epoch 011 - train 0.61780 | val 0.87886
  Classification -> best τ=0.485 (val F1=0.2966)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.74577 | val 0.66702
  Epoch 020 - train 0.65449 | val 0.78161
  Classification -> best τ=0.700 (val F1=0.2178)
  Directional -> Accuracy: 0.4561, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.73934 | val 1.68900
  Epoch 012 - train 0.68961 | val 2.02161
  Classification -> best τ=0.445 (val F1=0.2554)
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.66157 | val 0.74071
  Epoch 014 - train 0.67731 | val 0.93001
  Classification -> best τ=0.450 (val F1=0.1232)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.69739 | val 1.20579
  Epoch 013 - train 0.65620 | val 1.55860
  Classification -> best τ=0.475 (val F1=0.2012)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.72740 | val 0.68340

[I 2026-02-24 23:40:36,709] Trial 69 finished with value: 0.27754587730306135 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 15, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 32, 'learning_rate': 0.009994410146457147, 'weight_decay': 4.03794058502404e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.680034337696474, 'early_stopping_min_delta': 0.0018875147761771554}. Best is trial 32 with value: 0.2908549754956826.

  Epoch 013 - train 0.68930 | val 0.71358
  Classification -> best τ=0.385 (val F1=0.3143)
  Directional -> Accuracy: 0.5323, MCC: 0.0609, F1: 0.4912

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.27754587730306135
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 15
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.66240 | val 0.71331
  Epoch 018 - train 0.66914 | val 0.74329
  Classification -> best τ=0.630 (val F1=0.2931)
  Directional -> Accuracy: 0.5325, MCC: 0.0440, F1: 0.4375

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.64560 | val 0.76174
  Epoch 015 - train 0.58935 | val 0.84016
  Classification -> best τ=0.390 (val F1=0.1433)
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 16). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.70201 | val 0.81509
  Epoch 016 - train 0.72505 | val 0.70268
  Classification -> best τ=0.695 (val F1=0.4290)
  Directional -> Accuracy: 0.4792, MCC: -0.0113, F1: 0.3902

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.68426 | val 0.76216
  Epoch 012 - train 0.69120 | val 1.26798
  Classification -> best τ=0.390 (val F1=0.2109)
  Directional -> Accuracy: 0.5600, MCC: 0.1145, F1: 0.5926

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.65350 | val 0.69012
  Epoch 015 - train 0.61027 | val 0.85087
  Classification -> best τ=0.605 (val F1=0.4443)
  Directional -> Accuracy: 0.6731, MCC: 0.3821, F1: 0.6383

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.62623 | val 0.72975
  Epoch 014 - train 0.61260 | val 0.82555
  Classification -> best τ=0.535 (val F1=0.3119)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.71678 | val 0.71383
  Epoch 013 - train 0.69637 | val 0.72431
  Classification -> best τ=0.505 (val F1=0.2610)
  Directional -> Accuracy: 0.5286, MCC: 0.0947, F1: 0.5217

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 16). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.68941 | val 1.75416
  Epoch 011 - train 0.64236 | val 1.66474
  Classification -> best τ=0.455 (val F1=0.1048)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.67217 | val 1.01764
  Epoch 015 - train 0.69454 | val 2.88156
  Classification -> best τ=0.535 (val F1=0.3877)
  Directional -> Accuracy: 0.3902, MCC: -0.0591, F1: 0.4898

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 16). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 16). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.68514 | val 0.90441
  Epoch 013 - train 0.69156 | val 1.06565
  Classification -> best τ=0.445 (val F1=0.3478)
  Directional -> Accuracy: 0.4366, MCC: 0.0000, F1: 0.6078

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.69172 | val 0.96003
  Epoch 011 - train 0.67332 | val 0.88896
  Classification -> best τ=0.465 (val F1=0.1835)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.71610 | val 0.69847
  Epoch 016 - train 0.64073 | val 0.83368
  Classification -> best τ=0.460 (val F1=0.2061)
  Directional -> Accuracy: 0.5424, MCC: 0.1394, F1: 0.6824

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.65249 | val 0.93270
  Epoch 012 - train 0.67575 | val 0.77251
  Classification -> best τ=0.540 (val F1=0.2108)
  Directional -> Accuracy: 0.5814, MCC: 0.1280, F1: 0.4375

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.67586 | val 0.63257
  Epoch 013 - train 0.68574 | val 0.64526
  Classification -> best τ=0.345 (val F1=0.3346)
  Directional -> Accuracy: 0.5410, MCC: 0.1872, F1: 0.6889

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.65343 | val 1.53836
  Epoch 013 - train 0.65500 | val 2.18376
  Classification -> best τ=0.550 (val F1=0.2798)
  Directional -> Accuracy: 0.5283, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.67496 | val 0.86942
  Epoch 011 - train 0.66118 | val 0.69782
  Classification -> best τ=0.500 (val F1=0.3011)
  Directional -> Accuracy: 0.5429, MCC: 0.0702, F1: 0.6000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.71263 | val 1.22899
  Epoch 011 - train 0.69161 | val 1.08572
  Classification -> best τ=0.465 (val F1=0.1920)
  Directional -> Accuracy: 0.6167, MCC: 0.0000, F1: 0.7629

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.66618 | val 0.82468
  Epoch 014 - train 0.69961 | val 0.85584
  Classification -> best τ=0.390 (val F1=0.1764)
  Directional -> Accuracy: 0.6184, MCC: 0.1632, F1: 0.7129

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.67377 | val 0.81877
  Epoch 016 - train 0.65397 | val 1.09036
  Classification -> best τ=0.495 (val F1=0.3254)
  Directional -> Accuracy: 0.4848, MCC: 0.1240, F1: 0.3200

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 16). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.68963 | val 1.07395
  Epoch 012 - train 0.67282 | val 0.75538
  Classification -> best τ=0.415 (val F1=0.2953)
  Directional -> Accuracy: 0.5658, MCC: 0.1584, F1: 0.5217

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.60659 | val 1.32093
  Epoch 016 - train 0.67944 | val 1.30495
  Classification -> best τ=0.480 (val F1=0.2890)
  Directional -> Accuracy: 0.4375, MCC: 0.2000, F1: 0.1818

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.67001 | val 1.07848
  Epoch 013 - train 0.66430 | val 1.60389
  Classification -> best τ=0.630 (val F1=0.2547)
  Directional -> Accuracy: 0.5758, MCC: 0.1905, F1: 0.3913

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.66717 | val 0.93808
  Epoch 014 - train 0.71556 | val 0.76019
  Classification -> best τ=0.670 (val F1=0.2773)
  Directional -> Accuracy: 0.5172, MCC: 0.1339, F1: 0.3913

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.65989 | val 1.29087
  Epoch 012 - train 0.67554 | val 1.65806
  Classification -> best τ=0.475 (val F1=0.2453)
  Directional -> Accuracy: 0.4848, MCC: -0.0011, F1: 0.5750

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.67086 | val 0.67251
  Epoch 017 - train 0.65703 | val 0.82985
  Classification -> best τ=0.485 (val F1=0.4411)
  Directional -> Accuracy: 0.5536, MCC: 0.1867, F1: 0.4444

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.64972 | val 0.80968
  Epoch 011 - train 0.65962 | val 0.84969
  Classification -> best τ=0.490 (val F1=0.1792)
  Directional -> Accuracy: 0.5745, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.76277 | val 0.87503
  Epoch 013 - train 0.67433 | val 0.85303
  Classification -> best τ=0.575 (val F1=0.0444)
  Directional -> Accuracy: 0.5349, MCC: -0.0208, F1: 0.6552

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.66931 | val 0.78343
  Epoch 013 - train 0.68204 | val 0.71030
  Classification -> best τ=0.425 (val F1=0.2584)
  Directional -> Accuracy: 0.4483, MCC: -0.0874, F1: 0.4286

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.72368 | val 0.70115
  Epoch 012 - train 0.68273 | val 0.72720
  Classification -> best τ=0.585 (val F1=0.6210)
  Directional -> Accuracy: 0.5714, MCC: 0.1276, F1: 0.6250

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.66536 | val 0.84315
  Epoch 012 - train 0.72642 | val 0.91563
  Classification -> best τ=0.460 (val F1=0.1869)
  Directional -> Accuracy: 0.5455, MCC: 0.0976, F1: 0.6154

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.69779 | val 0.70862
  Epoch 011 - train 0.68849 | val 0.72960
  Classification -> best τ=0.655 (val F1=0.2498)
  Directional -> Accuracy: 0.4773, MCC: -0.0091, F1: 0.3784

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.62739 | val 0.80024
  Epoch 012 - train 0.63186 | val 1.15156
  Classification -> best τ=0.475 (val F1=0.4404)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.71502 | val 0.74328
  Epoch 016 - train 0.67659 | val 1.01256
  Classification -> best τ=0.310 (val F1=0.3134)
  Directional -> Accuracy: 0.5405, MCC: 0.1770, F1: 0.4333

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.70438 | val 0.79190
  Epoch 015 - train 0.66137 | val 0.77377
  Classification -> best τ=0.545 (val F1=0.4773)
  Directional -> Accuracy: 0.4737, MCC: -0.0778, F1: 0.6154

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.67992 | val 1.03196
  Epoch 012 - train 0.68544 | val 0.86321
  Classification -> best τ=0.580 (val F1=0.2417)
  Directional -> Accuracy: 0.5333, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.68078 | val 0.77728
  Epoch 015 - train 0.65333 | val 0.75302
  Classification -> best τ=0.335 (val F1=0.4179)
  Directional -> Accuracy: 0.5970, MCC: 0.1759, F1: 0.6494

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.69852 | val 0.68661
  Epoch 016 - train 0.67682 | val 0.70261
  Classification -> best τ=0.420 (val F1=0.3180)
  Directional -> Accuracy: 0.6512, MCC: 0.3392, F1: 0.5714

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.67703 | val 0.72803
  Epoch 011 - train 0.67903 | val 0.72392
  Classification -> best τ=0.470 (val F1=0.2166)
  Directional -> Accuracy: 0.4912, MCC: 0.0084, F1: 0.5797

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.65823 | val 0.75678
  Epoch 011 - train 0.66995 | val 0.74536
  Classification -> best τ=0.455 (val F1=0.3609)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 16). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.68603 | val 1.26192
  Epoch 013 - train 0.61298 | val 1.40882
  Classification -> best τ=0.345 (val F1=0.2000)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.82502 | val 0.79229
  Epoch 012 - train 0.68467 | val 0.86281
  Classification -> best τ=0.410 (val F1=0.1870)
  Directional -> Accuracy: 0.4872, MCC: -0.1097, F1: 0.6296

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 16). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.68572 | val 0.80942
  Epoch 013 - train 0.67437 | val 0.88883
  Classification -> best τ=0.370 (val F1=0.2948)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.68137 | val 0.69376
  Epoch 015 - train 0.66266 | val 0.69563
  Classification -> best τ=0.525 (val F1=0.3649)
  Directional -> Accuracy: 0.5319, MCC: 0.0644, F1: 0.6452

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.64480 | val 1.03426
  Epoch 016 - train 0.59133 | val 1.29898
  Classification -> best τ=0.575 (val F1=0.2774)
  Directional -> Accuracy: 0.4889, MCC: 0.0478, F1: 0.3429

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.72932 | val 0.77834
  Epoch 011 - train 0.67888 | val 0.79569
  Classification -> best τ=0.555 (val F1=0.3228)
  Directional -> Accuracy: 0.6500, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.62257 | val 1.07155
  Epoch 011 - train 0.71658 | val 0.99018
  Classification -> best τ=0.530 (val F1=0.1359)
  Directional -> Accuracy: 0.5614, MCC: 0.0896, F1: 0.6988

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.66933 | val 1.40859
  Epoch 011 - train 0.66577 | val 1.78708
  Classification -> best τ=0.510 (val F1=0.2554)
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.66367 | val 1.41785
  Epoch 011 - train 0.64961 | val 1.55349
  Classification -> best τ=0.355 (val F1=0.1884)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.70461 | val 0.83116
  Epoch 012 - train 0.67533 | val 1.05988
  Classification -> best τ=0.615 (val F1=0.2157)
  Directional -> Accuracy: 0.5614, MCC: 0.1669, F1: 0.6835

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.65581 | val 0.76867
  Epoch 011 - train 0.69583 | val 0.78032

[I 2026-02-24 23:42:22,108] Trial 70 finished with value: 0.27959707437769576 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 15, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 32, 'learning_rate': 0.006996096327244695, 'weight_decay': 3.841201767431899e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.6452977364069667, 'early_stopping_min_delta': 0.0015476713608984316}. Best is trial 32 with value: 0.2908549754956826.

  Classification -> best τ=0.455 (val F1=0.2653)
  Directional -> Accuracy: 0.5000, MCC: -0.0395, F1: 0.1622

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.27959707437769576
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 15
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.68431 | val 0.69322
  Epoch 018 - train 0.69359 | val 0.96754
  Classification -> best τ=0.445 (val F1=0.3044)
  Directional -> Accuracy: 0.5455, MCC: 0.0577, F1: 0.3860

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.63381 | val 0.69847
  Epoch 017 - train 0.61316 | val 0.78664
  Classification -> best τ=0.485 (val F1=0.3012)
  Directional -> Accuracy: 0.6957, MCC: 0.3723, F1: 0.7500

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 16). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.71082 | val 0.69924
  Epoch 012 - train 0.67788 | val 0.78819
  Classification -> best τ=0.575 (val F1=0.3130)
  Directional -> Accuracy: 0.3750, MCC: -0.2448, F1: 0.3750

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.69613 | val 1.23794
  Epoch 012 - train 0.69019 | val 0.94561
  Classification -> best τ=0.465 (val F1=0.2313)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.70083 | val 0.70582
  Epoch 017 - train 0.59274 | val 1.03114
  Classification -> best τ=0.635 (val F1=0.4357)
  Directional -> Accuracy: 0.5577, MCC: 0.1962, F1: 0.4103

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.62062 | val 0.82223
  Epoch 017 - train 0.59857 | val 1.98444
  Classification -> best τ=0.510 (val F1=0.3157)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.70242 | val 0.72979
  Epoch 014 - train 0.73772 | val 0.78384
  Classification -> best τ=0.450 (val F1=0.2641)
  Directional -> Accuracy: 0.4714, MCC: 0.1750, F1: 0.5934

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 16). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.69111 | val 1.45518
  Epoch 011 - train 0.69507 | val 1.90181
  Classification -> best τ=0.510 (val F1=0.3368)
  Directional -> Accuracy: 0.5333, MCC: -0.0445, F1: 0.2222

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.68981 | val 0.76531
  Epoch 013 - train 0.69048 | val 0.73412
  Classification -> best τ=0.585 (val F1=0.3877)
  Directional -> Accuracy: 0.5610, MCC: -0.0028, F1: 0.3077

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 16). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 16). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.68333 | val 0.80314
  Epoch 011 - train 0.66782 | val 0.73818
  Classification -> best τ=0.430 (val F1=0.0214)
  Directional -> Accuracy: 0.5775, MCC: 0.1139, F1: 0.4231

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.74044 | val 0.83435
  Epoch 017 - train 0.62350 | val 1.03404
  Classification -> best τ=0.470 (val F1=0.2688)
  Directional -> Accuracy: 0.5490, MCC: 0.0860, F1: 0.4651

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.68886 | val 0.88277
  Epoch 012 - train 0.73217 | val 0.86164
  Classification -> best τ=0.545 (val F1=0.2503)
  Directional -> Accuracy: 0.4746, MCC: -0.0482, F1: 0.3404

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.62332 | val 0.68654
  Epoch 018 - train 0.61768 | val 1.20065
  Classification -> best τ=0.580 (val F1=0.0664)
  Directional -> Accuracy: 0.5116, MCC: 0.0490, F1: 0.5333

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.67962 | val 0.66212
  Epoch 020 - train 0.64583 | val 0.61395
  Epoch 022 - train 0.68542 | val 0.62768
  Classification -> best τ=0.450 (val F1=0.3358)
  Directional -> Accuracy: 0.6066, MCC: 0.2146, F1: 0.6471

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.65414 | val 1.60738
  Epoch 012 - train 0.71554 | val 2.18908
  Classification -> best τ=0.465 (val F1=0.2981)
  Directional -> Accuracy: 0.6226, MCC: 0.2468, F1: 0.6154

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.66426 | val 0.71581
  Epoch 011 - train 0.64473 | val 0.73573
  Classification -> best τ=0.650 (val F1=0.1790)
  Directional -> Accuracy: 0.5571, MCC: 0.1147, F1: 0.5753

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.67612 | val 0.82328
  Epoch 013 - train 0.67979 | val 1.19581
  Classification -> best τ=0.495 (val F1=0.2736)
  Directional -> Accuracy: 0.4000, MCC: -0.1826, F1: 0.4375

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.68391 | val 1.18520
  Epoch 011 - train 0.69502 | val 1.49007
  Classification -> best τ=0.450 (val F1=0.1799)
  Directional -> Accuracy: 0.4868, MCC: 0.1792, F1: 0.3158

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.70760 | val 0.71004
  Epoch 020 - train 0.67193 | val 1.60188
  Epoch 021 - train 0.69029 | val 1.31554
  Classification -> best τ=0.390 (val F1=0.2464)
  Directional -> Accuracy: 0.4394, MCC: 0.0822, F1: 0.1395

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 16). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.67869 | val 0.71532
  Epoch 012 - train 0.69373 | val 0.78737
  Classification -> best τ=0.590 (val F1=0.2485)
  Directional -> Accuracy: 0.4605, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.68847 | val 0.74518
  Epoch 017 - train 0.70152 | val 0.81106
  Classification -> best τ=0.445 (val F1=0.3130)
  Directional -> Accuracy: 0.5417, MCC: 0.0861, F1: 0.5926

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.66181 | val 1.29654
  Epoch 015 - train 0.70515 | val 1.16246
  Classification -> best τ=0.600 (val F1=0.1087)
  Directional -> Accuracy: 0.5152, MCC: 0.0362, F1: 0.3333

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.70117 | val 1.57381
  Epoch 013 - train 0.65537 | val 1.50943
  Classification -> best τ=0.635 (val F1=0.2773)
  Directional -> Accuracy: 0.5345, MCC: 0.1655, F1: 0.4255

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.65992 | val 2.42751
  Epoch 011 - train 0.69796 | val 2.13894
  Classification -> best τ=0.350 (val F1=0.2319)
  Directional -> Accuracy: 0.5455, MCC: 0.1149, F1: 0.5946

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.64956 | val 0.63429
  Epoch 016 - train 0.65527 | val 0.66797
  Classification -> best τ=0.460 (val F1=0.4411)
  Directional -> Accuracy: 0.5357, MCC: 0.1728, F1: 0.3810

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.68007 | val 0.72635
  Epoch 012 - train 0.59219 | val 0.80530
  Classification -> best τ=0.545 (val F1=0.3225)
  Directional -> Accuracy: 0.5957, MCC: 0.1713, F1: 0.0952

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.67185 | val 0.73804
  Epoch 015 - train 0.68037 | val 0.71546
  Classification -> best τ=0.620 (val F1=0.2324)
  Directional -> Accuracy: 0.5581, MCC: 0.0993, F1: 0.6122

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.67758 | val 0.85311
  Epoch 011 - train 0.68894 | val 0.89454
  Classification -> best τ=0.470 (val F1=0.3241)
  Directional -> Accuracy: 0.5000, MCC: -0.0382, F1: 0.5915

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.71670 | val 0.75898
  Epoch 012 - train 0.69195 | val 0.76816
  Classification -> best τ=0.570 (val F1=0.2202)
  Directional -> Accuracy: 0.6429, MCC: 0.2706, F1: 0.7059

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.72630 | val 0.85571
  Epoch 012 - train 0.67364 | val 0.90678
  Classification -> best τ=0.460 (val F1=0.1869)
  Directional -> Accuracy: 0.5227, MCC: 0.0467, F1: 0.5714

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.70303 | val 0.67132
  Epoch 012 - train 0.66307 | val 0.67760
  Classification -> best τ=0.630 (val F1=0.0587)
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.63428 | val 0.81747
  Epoch 015 - train 0.65696 | val 0.76333
  Classification -> best τ=0.425 (val F1=0.2941)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.66681 | val 0.70393
  Epoch 012 - train 0.69465 | val 0.95702
  Classification -> best τ=0.440 (val F1=0.3259)
  Directional -> Accuracy: 0.5405, MCC: 0.1282, F1: 0.5000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.67545 | val 0.71466
  Epoch 013 - train 0.59396 | val 0.70165
  Classification -> best τ=0.500 (val F1=0.4393)
  Directional -> Accuracy: 0.3684, MCC: -0.2646, F1: 0.4000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.70743 | val 0.88255
  Epoch 013 - train 0.65457 | val 1.34830
  Classification -> best τ=0.455 (val F1=0.0945)
  Directional -> Accuracy: 0.5778, MCC: 0.1572, F1: 0.2963

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.66191 | val 0.72241
  Epoch 017 - train 0.65133 | val 0.81881
  Classification -> best τ=0.195 (val F1=0.3166)
  Directional -> Accuracy: 0.5373, MCC: -0.0044, F1: 0.6593

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.69224 | val 0.79286
  Epoch 014 - train 0.70082 | val 0.83318
  Classification -> best τ=0.420 (val F1=0.2775)
  Directional -> Accuracy: 0.6512, MCC: 0.3246, F1: 0.5946

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.72489 | val 0.72315
  Epoch 015 - train 0.65465 | val 0.86138
  Classification -> best τ=0.400 (val F1=0.2094)
  Directional -> Accuracy: 0.5439, MCC: 0.1452, F1: 0.6389

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.65305 | val 0.69447
  Epoch 020 - train 0.63513 | val 0.77838
  Epoch 023 - train 0.59976 | val 0.93454
  Classification -> best τ=0.515 (val F1=0.4439)
  Directional -> Accuracy: 0.5532, MCC: 0.0240, F1: 0.6557

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 16). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.66620 | val 1.59050
  Epoch 011 - train 0.61574 | val 2.11837
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.70836 | val 0.75472
  Epoch 013 - train 0.65950 | val 0.79418
  Classification -> best τ=0.445 (val F1=0.1870)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.7000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 16). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.66974 | val 0.69578
  Epoch 013 - train 0.67943 | val 0.77599
  Classification -> best τ=0.445 (val F1=0.3070)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.70246 | val 0.75288
  Epoch 011 - train 0.71949 | val 0.71251
  Classification -> best τ=0.480 (val F1=0.1132)
  Directional -> Accuracy: 0.5106, MCC: 0.0437, F1: 0.3030

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.73338 | val 0.88746
  Epoch 011 - train 0.60848 | val 1.01413
  Classification -> best τ=0.490 (val F1=0.4000)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.71501 | val 0.81826
  Epoch 011 - train 0.72175 | val 0.70980
  Classification -> best τ=0.545 (val F1=0.3968)
  Directional -> Accuracy: 0.6500, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.64953 | val 1.48786
  Epoch 012 - train 0.68658 | val 1.13192
  Classification -> best τ=0.590 (val F1=0.1869)
  Directional -> Accuracy: 0.3509, MCC: -0.2979, F1: 0.3729

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.67792 | val 1.54223
  Epoch 011 - train 0.64925 | val 1.80258
  Classification -> best τ=0.765 (val F1=0.2875)
  Directional -> Accuracy: 0.5088, MCC: 0.0262, F1: 0.5333

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.71528 | val 1.18055
  Epoch 011 - train 0.71897 | val 1.05717
  Classification -> best τ=0.730 (val F1=0.1154)
  Directional -> Accuracy: 0.4815, MCC: 0.0000, F1: 0.0000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.68847 | val 1.66647
  Epoch 013 - train 0.66403 | val 2.10187
  Classification -> best τ=0.535 (val F1=0.1724)
  Directional -> Accuracy: 0.5614, MCC: 0.1420, F1: 0.6667

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.69903 | val 0.80363

[I 2026-02-24 23:44:12,757] Trial 71 finished with value: 0.2538566923733876 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 15, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 32, 'learning_rate': 0.007304319092697367, 'weight_decay': 4.785062935319362e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.737502542561132, 'early_stopping_min_delta': 0.0017083013899204889}. Best is trial 32 with value: 0.2908549754956826.

  Epoch 014 - train 0.62559 | val 1.94628
  Classification -> best τ=0.475 (val F1=0.1507)
  Directional -> Accuracy: 0.5161, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2538566923733876
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 15
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.67946 | val 0.71153
  Epoch 020 - train 0.66484 | val 0.82738
  Epoch 026 - train 0.68233 | val 0.75852
  Classification -> best τ=0.780 (val F1=0.2851)
  Directional -> Accuracy: 0.5325, MCC: -0.0165, F1: 0.1429

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.60846 | val 0.99472
  Epoch 015 - train 0.65500 | val 0.89173
  Classification -> best τ=0.450 (val F1=0.1236)
  Directional -> Accuracy: 0.5652, MCC: 0.0280, F1: 0.7143

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 16). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.68472 | val 0.77186
  Epoch 017 - train 0.68631 | val 1.05308
  Classification -> best τ=0.650 (val F1=0.3271)
  Directional -> Accuracy: 0.4167, MCC: -0.2267, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.67604 | val 1.40731
  Epoch 011 - train 0.69479 | val 1.41437
  Classification -> best τ=0.455 (val F1=0.1533)
  Directional -> Accuracy: 0.4667, MCC: -0.0469, F1: 0.4286

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.62468 | val 0.79870
  Epoch 016 - train 0.63481 | val 0.95963
  Classification -> best τ=0.475 (val F1=0.4747)
  Directional -> Accuracy: 0.7885, MCC: 0.5820, F1: 0.7925

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.63903 | val 0.88116
  Epoch 011 - train 0.67161 | val 0.91646
  Classification -> best τ=0.475 (val F1=0.1733)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.73243 | val 0.74483
  Epoch 017 - train 0.70357 | val 0.69713
  Classification -> best τ=0.490 (val F1=0.3077)
  Directional -> Accuracy: 0.5429, MCC: 0.0589, F1: 0.4483

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 16). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.69195 | val 1.37022
  Epoch 011 - train 0.62668 | val 1.29966
  Classification -> best τ=0.510 (val F1=0.2229)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.78917 | val 0.68460
  Epoch 015 - train 0.68519 | val 0.93123
  Classification -> best τ=0.510 (val F1=0.3877)
  Directional -> Accuracy: 0.6098, MCC: 0.2638, F1: 0.5789

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 16). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 16). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.70035 | val 1.04514
  Epoch 014 - train 0.69392 | val 0.90192
  Classification -> best τ=0.435 (val F1=0.2245)
  Directional -> Accuracy: 0.4366, MCC: 0.0000, F1: 0.6078

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.70311 | val 0.77126
  Epoch 015 - train 0.68902 | val 1.06362
  Classification -> best τ=0.430 (val F1=0.2278)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.67740 | val 0.69502
  Epoch 011 - train 0.70650 | val 0.72091
  Classification -> best τ=0.475 (val F1=0.2468)
  Directional -> Accuracy: 0.4576, MCC: -0.1510, F1: 0.6098

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.66784 | val 1.24724
  Epoch 011 - train 0.74281 | val 0.71577
  Classification -> best τ=0.495 (val F1=0.2839)
  Directional -> Accuracy: 0.4419, MCC: -0.0901, F1: 0.4783

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.69372 | val 0.64486
  Epoch 020 - train 0.65786 | val 0.62316
  Epoch 023 - train 0.72261 | val 0.63494
  Classification -> best τ=0.320 (val F1=0.3336)
  Directional -> Accuracy: 0.5410, MCC: 0.1155, F1: 0.6744

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.71340 | val 1.17850
  Epoch 011 - train 0.72137 | val 1.47210
  Classification -> best τ=0.625 (val F1=0.2798)
  Directional -> Accuracy: 0.5283, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.70285 | val 0.82182
  Epoch 011 - train 0.72037 | val 0.86730
  Classification -> best τ=0.580 (val F1=0.3710)
  Directional -> Accuracy: 0.5429, MCC: 0.0309, F1: 0.6800

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.73073 | val 0.84270
  Epoch 012 - train 0.74257 | val 0.94032
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6167, MCC: 0.0000, F1: 0.7629

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.65820 | val 0.90752
  Epoch 015 - train 0.66499 | val 0.87076
  Classification -> best τ=0.530 (val F1=0.2210)
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.75311 | val 0.76333
  Epoch 016 - train 0.71825 | val 0.92170
  Classification -> best τ=0.285 (val F1=0.2778)
  Directional -> Accuracy: 0.5606, MCC: 0.1177, F1: 0.6027

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 16). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.68957 | val 0.84682
  Epoch 019 - train 0.68069 | val 1.13367
  Classification -> best τ=0.205 (val F1=0.1923)
  Directional -> Accuracy: 0.6053, MCC: 0.1965, F1: 0.6875

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.67542 | val 0.69838
  Epoch 020 - train 0.63780 | val 0.72253
  Epoch 027 - train 0.59742 | val 1.29146
  Classification -> best τ=0.645 (val F1=0.3963)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.72074 | val 0.94213
  Epoch 012 - train 0.70412 | val 0.93800
  Classification -> best τ=0.640 (val F1=0.1287)
  Directional -> Accuracy: 0.4848, MCC: -0.1240, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.69086 | val 0.87825
  Epoch 012 - train 0.71462 | val 0.83662
  Classification -> best τ=0.710 (val F1=0.2743)
  Directional -> Accuracy: 0.4655, MCC: 0.0453, F1: 0.2439

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.68954 | val 1.53246
  Epoch 014 - train 0.67066 | val 1.70906
  Classification -> best τ=0.425 (val F1=0.3360)
  Directional -> Accuracy: 0.5455, MCC: 0.1215, F1: 0.6053

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.68847 | val 0.75081
  Epoch 018 - train 0.69017 | val 1.22702
  Classification -> best τ=0.505 (val F1=0.4135)
  Directional -> Accuracy: 0.5357, MCC: 0.1376, F1: 0.4348

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.63984 | val 0.94718
  Epoch 014 - train 0.58149 | val 0.82864
  Classification -> best τ=0.565 (val F1=0.2582)
  Directional -> Accuracy: 0.5745, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.72365 | val 0.89120
  Epoch 016 - train 0.66002 | val 1.29834
  Classification -> best τ=0.590 (val F1=0.1818)
  Directional -> Accuracy: 0.5581, MCC: -0.0473, F1: 0.7077

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.69938 | val 0.69297
  Epoch 016 - train 0.68377 | val 0.78543
  Classification -> best τ=0.345 (val F1=0.3310)
  Directional -> Accuracy: 0.5345, MCC: -0.1194, F1: 0.6966

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.77815 | val 0.69164
  Epoch 020 - train 0.69721 | val 0.73371
  Epoch 021 - train 0.76494 | val 0.70381
  Classification -> best τ=0.525 (val F1=0.3548)
  Directional -> Accuracy: 0.4524, MCC: -0.0464, F1: 0.2581

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.68465 | val 0.79438
  Epoch 011 - train 0.69376 | val 0.85580
  Classification -> best τ=0.565 (val F1=0.1869)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.5600

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.71055 | val 0.67288
  Epoch 012 - train 0.70824 | val 0.66317
  Classification -> best τ=0.635 (val F1=0.1802)
  Directional -> Accuracy: 0.5455, MCC: 0.0363, F1: 0.6774

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.65989 | val 0.70907
  Epoch 019 - train 0.60618 | val 0.69273
  Classification -> best τ=0.400 (val F1=0.3265)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.69219 | val 1.10869
  Epoch 013 - train 0.69069 | val 0.69886
  Classification -> best τ=0.440 (val F1=0.3504)
  Directional -> Accuracy: 0.5135, MCC: 0.0903, F1: 0.4375

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.67091 | val 0.71684
  Epoch 020 - train 0.63129 | val 0.88468
  Epoch 021 - train 0.67542 | val 0.89951
  Classification -> best τ=0.470 (val F1=0.3973)
  Directional -> Accuracy: 0.5526, MCC: 0.1291, F1: 0.6531

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.69671 | val 0.87837
  Epoch 012 - train 0.75304 | val 1.15882
  Classification -> best τ=0.565 (val F1=0.2020)
  Directional -> Accuracy: 0.3778, MCC: -0.2500, F1: 0.5000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.68484 | val 0.67059
  Epoch 020 - train 0.59852 | val 0.72893
  Epoch 028 - train 0.61898 | val 0.83750
  Classification -> best τ=0.310 (val F1=0.3773)
  Directional -> Accuracy: 0.5224, MCC: 0.0597, F1: 0.5294

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.76394 | val 0.70733
  Epoch 018 - train 0.67397 | val 0.79262
  Classification -> best τ=0.550 (val F1=0.3914)
  Directional -> Accuracy: 0.6047, MCC: 0.2739, F1: 0.4516

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.73369 | val 0.77194
  Epoch 015 - train 0.77559 | val 0.84933
  Classification -> best τ=0.470 (val F1=0.2236)
  Directional -> Accuracy: 0.5614, MCC: 0.1520, F1: 0.1935

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.70512 | val 0.68612
  Epoch 011 - train 0.66268 | val 0.67826
  Classification -> best τ=0.435 (val F1=0.4406)
  Directional -> Accuracy: 0.5319, MCC: -0.0118, F1: 0.6333

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 16). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.66950 | val 0.96664
  Epoch 011 - train 0.59396 | val 1.79414
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.73885 | val 0.75861
  Epoch 014 - train 0.61497 | val 0.89374
  Classification -> best τ=0.450 (val F1=0.1870)
  Directional -> Accuracy: 0.5385, MCC: 0.0261, F1: 0.6786

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 16). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.71385 | val 0.73364
  Epoch 014 - train 0.69023 | val 0.70175
  Classification -> best τ=0.505 (val F1=0.2359)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.70736 | val 0.70989
  Epoch 020 - train 0.67872 | val 0.91809
  Epoch 027 - train 0.64996 | val 0.76475
  Classification -> best τ=0.520 (val F1=0.3649)
  Directional -> Accuracy: 0.4894, MCC: -0.0139, F1: 0.3684

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.64285 | val 0.89801
  Epoch 015 - train 0.68485 | val 1.29658
  Classification -> best τ=0.460 (val F1=0.3162)
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.73741 | val 0.76121
  Epoch 020 - train 0.67121 | val 0.81952
  Epoch 022 - train 0.57770 | val 0.81616
  Classification -> best τ=0.555 (val F1=0.4229)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.65705 | val 0.71221
  Epoch 015 - train 0.66510 | val 0.73614
  Classification -> best τ=0.565 (val F1=0.1059)
  Directional -> Accuracy: 0.3860, MCC: -0.3000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.68697 | val 1.79896
  Epoch 012 - train 0.71358 | val 1.74469
  Classification -> best τ=0.710 (val F1=0.3108)
  Directional -> Accuracy: 0.5263, MCC: 0.0181, F1: 0.1818

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.68481 | val 0.76130
  Epoch 020 - train 0.68518 | val 0.73477
  Epoch 030 - train 0.66380 | val 0.85533
  Classification -> best τ=0.600 (val F1=0.2527)
  Directional -> Accuracy: 0.5370, MCC: 0.0695, F1: 0.6667

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.70422 | val 0.83979
  Epoch 011 - train 0.67061 | val 0.94694
  Classification -> best τ=0.595 (val F1=0.1141)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.72202 | val 0.68590

[I 2026-02-24 23:46:14,960] Trial 72 finished with value: 0.270047119013573 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 15, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 32, 'learning_rate': 0.009701529485501207, 'weight_decay': 4.159037936117138e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.669916509200038, 'early_stopping_min_delta': 0.0010470928321512374}. Best is trial 32 with value: 0.2908549754956826.

  Epoch 016 - train 0.71952 | val 0.85153
  Classification -> best τ=0.365 (val F1=0.3271)
  Directional -> Accuracy: 0.4677, MCC: -0.0668, F1: 0.4407

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.270047119013573
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 15
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.68690 | val 0.66505
  Epoch 018 - train 0.68051 | val 1.09902
  Classification -> best τ=0.730 (val F1=0.3210)
  Directional -> Accuracy: 0.5195, MCC: -0.0544, F1: 0.1395

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.63023 | val 0.76487
  Epoch 014 - train 0.65494 | val 0.88163
  Classification -> best τ=0.500 (val F1=0.1812)
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 16). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.66927 | val 0.68373
  Epoch 012 - train 0.72729 | val 0.84616
  Classification -> best τ=0.525 (val F1=0.2919)
  Directional -> Accuracy: 0.5208, MCC: 0.2375, F1: 0.2069

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.72570 | val 1.35392
  Epoch 019 - train 0.69475 | val 0.80756
  Classification -> best τ=0.485 (val F1=0.2137)
  Directional -> Accuracy: 0.5467, MCC: 0.1002, F1: 0.5526

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.68897 | val 0.72922
  Epoch 017 - train 0.71960 | val 1.43501
  Classification -> best τ=0.510 (val F1=0.4667)
  Directional -> Accuracy: 0.7115, MCC: 0.4475, F1: 0.6939

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.60858 | val 0.72737
  Epoch 014 - train 0.68580 | val 1.09271
  Classification -> best τ=0.465 (val F1=0.4508)
  Directional -> Accuracy: 0.5625, MCC: 0.2046, F1: 0.2759

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.72583 | val 0.73186
  Epoch 014 - train 0.74457 | val 0.71767
  Classification -> best τ=0.455 (val F1=0.2000)
  Directional -> Accuracy: 0.4857, MCC: 0.1393, F1: 0.5814

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 16). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.59673 | val 2.66749
  Epoch 011 - train 0.66845 | val 3.30025
  Classification -> best τ=0.570 (val F1=0.3368)
  Directional -> Accuracy: 0.5111, MCC: -0.0318, F1: 0.3529

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.69235 | val 0.69147
  Epoch 020 - train 0.70852 | val 0.79086
  Epoch 026 - train 0.59210 | val 0.87959
  Classification -> best τ=0.690 (val F1=0.4382)
  Directional -> Accuracy: 0.5122, MCC: -0.1581, F1: 0.1667

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 16). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 16). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.68077 | val 0.87461
  Epoch 013 - train 0.67259 | val 1.09846
  Classification -> best τ=0.435 (val F1=0.2254)
  Directional -> Accuracy: 0.4366, MCC: -0.0312, F1: 0.5918

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.66740 | val 0.83495
  Epoch 015 - train 0.66316 | val 1.39343
  Classification -> best τ=0.410 (val F1=0.1641)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.69576 | val 0.69472
  Epoch 013 - train 0.71454 | val 1.25065
  Classification -> best τ=0.495 (val F1=0.2110)
  Directional -> Accuracy: 0.5085, MCC: 0.0000, F1: 0.6742

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.68779 | val 1.42757
  Epoch 012 - train 0.69056 | val 1.02136
  Classification -> best τ=0.515 (val F1=0.2708)
  Directional -> Accuracy: 0.5349, MCC: 0.0468, F1: 0.4444

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.70304 | val 0.66312
  Epoch 019 - train 0.68887 | val 0.92727
  Classification -> best τ=0.205 (val F1=0.2501)
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.67309 | val 1.36639
  Epoch 011 - train 0.64829 | val 1.85403
  Classification -> best τ=0.650 (val F1=0.2262)
  Directional -> Accuracy: 0.5283, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.70320 | val 0.81609
  Epoch 011 - train 0.69286 | val 0.69095
  Classification -> best τ=0.635 (val F1=0.3315)
  Directional -> Accuracy: 0.5286, MCC: 0.0925, F1: 0.4590

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.72295 | val 0.86371
  Epoch 011 - train 0.68286 | val 0.80143
  Classification -> best τ=0.645 (val F1=0.0689)
  Directional -> Accuracy: 0.4333, MCC: 0.1137, F1: 0.1905

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.68218 | val 0.80766
  Epoch 019 - train 0.69343 | val 0.70016
  Classification -> best τ=0.620 (val F1=0.2236)
  Directional -> Accuracy: 0.3553, MCC: -0.2051, F1: 0.1695

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.67383 | val 0.67928
  Epoch 020 - train 0.66240 | val 0.89461
  Epoch 030 - train 0.61629 | val 1.35712
  Classification -> best τ=0.190 (val F1=0.3068)
  Directional -> Accuracy: 0.4848, MCC: 0.1240, F1: 0.3200

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 16). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.70026 | val 0.70748
  Epoch 011 - train 0.70669 | val 0.75734
  Classification -> best τ=0.490 (val F1=0.1892)
  Directional -> Accuracy: 0.4605, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.72068 | val 0.67674
  Epoch 020 - train 0.58605 | val 1.02114
  Epoch 026 - train 0.60806 | val 0.73895
  Classification -> best τ=0.530 (val F1=0.3402)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.67749 | val 0.93768
  Epoch 012 - train 0.69066 | val 1.02209
  Classification -> best τ=0.470 (val F1=0.1678)
  Directional -> Accuracy: 0.5758, MCC: 0.2033, F1: 0.6818

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.69885 | val 0.69090
  Epoch 014 - train 0.69116 | val 1.03646
  Classification -> best τ=0.680 (val F1=0.2773)
  Directional -> Accuracy: 0.5172, MCC: 0.0882, F1: 0.4615

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.65440 | val 1.47552
  Epoch 012 - train 0.65529 | val 1.05287
  Classification -> best τ=0.485 (val F1=0.3360)
  Directional -> Accuracy: 0.5758, MCC: 0.1716, F1: 0.6111

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.68031 | val 0.75951
  Epoch 015 - train 0.69180 | val 0.91431
  Classification -> best τ=0.490 (val F1=0.4283)
  Directional -> Accuracy: 0.5357, MCC: 0.1728, F1: 0.3810

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.63396 | val 0.79201
  Epoch 011 - train 0.59822 | val 0.91907
  Classification -> best τ=0.540 (val F1=0.2067)
  Directional -> Accuracy: 0.4255, MCC: -0.1413, F1: 0.4000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.67607 | val 0.87757
  Epoch 020 - train 0.66300 | val 0.74403
  Epoch 027 - train 0.66016 | val 0.71230
  Classification -> best τ=0.540 (val F1=0.3158)
  Directional -> Accuracy: 0.5814, MCC: 0.1400, F1: 0.6400

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.74527 | val 0.73197
  Epoch 016 - train 0.67816 | val 0.78452
  Classification -> best τ=0.540 (val F1=0.2655)
  Directional -> Accuracy: 0.5000, MCC: 0.1533, F1: 0.2162

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.66959 | val 0.86888
  Epoch 013 - train 0.64904 | val 0.88359
  Classification -> best τ=0.555 (val F1=0.2425)
  Directional -> Accuracy: 0.5238, MCC: -0.0083, F1: 0.6429

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.70334 | val 1.42342
  Epoch 017 - train 0.65516 | val 2.47239
  Classification -> best τ=0.695 (val F1=0.1869)
  Directional -> Accuracy: 0.5455, MCC: 0.1021, F1: 0.4118

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.69931 | val 0.67055
  Epoch 020 - train 0.73463 | val 0.98218
  Epoch 021 - train 0.65105 | val 0.93029
  Classification -> best τ=0.635 (val F1=0.4239)
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.61810 | val 0.74466
  Epoch 013 - train 0.64768 | val 0.76927
  Classification -> best τ=0.465 (val F1=0.2941)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.69327 | val 0.84239
  Epoch 016 - train 0.68565 | val 0.90592
  Classification -> best τ=0.400 (val F1=0.3044)
  Directional -> Accuracy: 0.5541, MCC: 0.1736, F1: 0.4923

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.71985 | val 0.73163
  Epoch 017 - train 0.65298 | val 0.74919
  Classification -> best τ=0.475 (val F1=0.2496)
  Directional -> Accuracy: 0.4737, MCC: -0.0529, F1: 0.5000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.70972 | val 1.00313
  Epoch 011 - train 0.68646 | val 0.93419
  Classification -> best τ=0.510 (val F1=0.0714)
  Directional -> Accuracy: 0.6222, MCC: 0.2436, F1: 0.6047

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.69099 | val 0.76265
  Epoch 013 - train 0.72110 | val 0.76128
  Classification -> best τ=0.395 (val F1=0.3444)
  Directional -> Accuracy: 0.6269, MCC: 0.2432, F1: 0.6667

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.70471 | val 0.70804
  Epoch 020 - train 0.71046 | val 0.68437
  Epoch 029 - train 0.62521 | val 0.69214
  Classification -> best τ=0.675 (val F1=0.3337)
  Directional -> Accuracy: 0.5116, MCC: 0.0641, F1: 0.2222

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.69290 | val 0.74599
  Epoch 012 - train 0.71455 | val 0.69268
  Classification -> best τ=0.475 (val F1=0.1697)
  Directional -> Accuracy: 0.5614, MCC: 0.1140, F1: 0.4898

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.71601 | val 0.92921
  Epoch 013 - train 0.64883 | val 0.93509
  Classification -> best τ=0.390 (val F1=0.3321)
  Directional -> Accuracy: 0.5532, MCC: -0.0220, F1: 0.6769

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 16). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.64308 | val 1.05835
  Epoch 011 - train 0.64376 | val 0.72482
  Classification -> best τ=0.520 (val F1=0.3779)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.65275 | val 0.79566
  Epoch 013 - train 0.65104 | val 0.82909
  Classification -> best τ=0.585 (val F1=0.3893)
  Directional -> Accuracy: 0.5128, MCC: 0.0882, F1: 0.3448

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 16). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.69647 | val 0.68589
  Epoch 016 - train 0.69760 | val 0.71334
  Classification -> best τ=0.375 (val F1=0.2727)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.66335 | val 0.70660
  Epoch 020 - train 0.64076 | val 1.17507
  Epoch 023 - train 0.75153 | val 1.08273
  Classification -> best τ=0.570 (val F1=0.3119)
  Directional -> Accuracy: 0.5745, MCC: 0.1583, F1: 0.5238

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.73779 | val 0.87449
  Epoch 011 - train 0.63327 | val 0.89394
  Classification -> best τ=0.460 (val F1=0.0737)
  Directional -> Accuracy: 0.5778, MCC: 0.1265, F1: 0.6545

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.68416 | val 0.70318
  Epoch 016 - train 0.68551 | val 0.83378
  Classification -> best τ=0.580 (val F1=0.4730)
  Directional -> Accuracy: 0.6500, MCC: 0.1321, F1: 0.3000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.74706 | val 0.74126
  Epoch 015 - train 0.72986 | val 0.91656
  Classification -> best τ=0.645 (val F1=0.1869)
  Directional -> Accuracy: 0.4561, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.70010 | val 1.02071
  Epoch 012 - train 0.65277 | val 1.31986
  Classification -> best τ=0.575 (val F1=0.3535)
  Directional -> Accuracy: 0.5088, MCC: 0.0964, F1: 0.6410

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.70925 | val 0.86628
  Epoch 017 - train 0.71254 | val 0.86505
  Classification -> best τ=0.510 (val F1=0.2396)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.68537 | val 0.77643
  Epoch 016 - train 0.66214 | val 0.98153
  Classification -> best τ=0.490 (val F1=0.2320)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.69626 | val 0.74274

[I 2026-02-24 23:48:17,035] Trial 73 finished with value: 0.27567262420578964 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 15, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 32, 'learning_rate': 0.00933664224782087, 'weight_decay': 3.9925105466037855e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.655176145425623, 'early_stopping_min_delta': 0.0003205077206375412}. Best is trial 32 with value: 0.2908549754956826.

  Epoch 018 - train 0.69395 | val 0.74854
  Classification -> best τ=0.555 (val F1=0.2148)
  Directional -> Accuracy: 0.5000, MCC: -0.1240, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.27567262420578964
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 15
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.67716 | val 0.66211
  Epoch 020 - train 0.65969 | val 0.82848
  Epoch 028 - train 0.67292 | val 0.85591
  Classification -> best τ=0.510 (val F1=0.2783)
  Directional -> Accuracy: 0.5195, MCC: -0.0327, F1: 0.2128

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.68872 | val 0.69719
  Epoch 013 - train 0.60489 | val 0.81390
  Classification -> best τ=0.440 (val F1=0.1812)
  Directional -> Accuracy: 0.5870, MCC: 0.1168, F1: 0.7077

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 16). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.68393 | val 0.70410
  Epoch 016 - train 0.67884 | val 0.72512
  Classification -> best τ=0.540 (val F1=0.3402)
  Directional -> Accuracy: 0.4583, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.67233 | val 0.70499
  Epoch 011 - train 0.66322 | val 0.72774
  Classification -> best τ=0.460 (val F1=0.1512)
  Directional -> Accuracy: 0.5067, MCC: -0.0536, F1: 0.6337

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.63906 | val 1.33879
  Epoch 015 - train 0.64346 | val 1.07294
  Classification -> best τ=0.470 (val F1=0.3464)
  Directional -> Accuracy: 0.7308, MCC: 0.4565, F1: 0.7586

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.67933 | val 0.76002
  Epoch 015 - train 0.64367 | val 0.92617
  Classification -> best τ=0.590 (val F1=0.3086)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.70319 | val 0.74100
  Epoch 011 - train 0.66743 | val 0.83086
  Classification -> best τ=0.335 (val F1=0.2134)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.5714

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 16). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.74623 | val 1.47882
  Epoch 011 - train 0.66532 | val 1.51121
  Classification -> best τ=0.575 (val F1=0.2385)
  Directional -> Accuracy: 0.4444, MCC: -0.0507, F1: 0.5098

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.67234 | val 1.10109
  Epoch 011 - train 0.67588 | val 1.41067
  Classification -> best τ=0.585 (val F1=0.3786)
  Directional -> Accuracy: 0.5122, MCC: -0.0226, F1: 0.3750

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 16). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 16). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.65796 | val 1.12001
  Epoch 013 - train 0.67750 | val 0.90337
  Classification -> best τ=0.395 (val F1=0.1403)
  Directional -> Accuracy: 0.4085, MCC: -0.1544, F1: 0.5714

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.67852 | val 1.52581
  Epoch 011 - train 0.68140 | val 1.40877
  Classification -> best τ=0.525 (val F1=0.0963)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.70792 | val 0.81469
  Epoch 020 - train 0.68888 | val 0.77954
  Epoch 021 - train 0.66172 | val 0.82761
  Classification -> best τ=0.445 (val F1=0.2061)
  Directional -> Accuracy: 0.5254, MCC: 0.0811, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.69144 | val 0.77528
  Epoch 014 - train 0.64281 | val 0.72725
  Classification -> best τ=0.555 (val F1=0.1710)
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.69100 | val 0.65684
  Epoch 018 - train 0.71459 | val 0.91947
  Classification -> best τ=0.440 (val F1=0.2877)
  Directional -> Accuracy: 0.5738, MCC: 0.1512, F1: 0.6389

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.67303 | val 0.85271
  Epoch 018 - train 0.66666 | val 1.17106
  Classification -> best τ=0.610 (val F1=0.2798)
  Directional -> Accuracy: 0.5283, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.64005 | val 0.83484
  Epoch 014 - train 0.71829 | val 0.76782
  Classification -> best τ=0.475 (val F1=0.2516)
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.71589 | val 0.75031
  Epoch 012 - train 0.70268 | val 0.80577
  Classification -> best τ=0.575 (val F1=0.2585)
  Directional -> Accuracy: 0.3833, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.69535 | val 0.75791
  Epoch 011 - train 0.69284 | val 0.71708
  Classification -> best τ=0.555 (val F1=0.1940)
  Directional -> Accuracy: 0.3947, MCC: -0.2154, F1: 0.4524

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.65011 | val 0.67411
  Epoch 020 - train 0.72205 | val 0.74129
  Classification -> best τ=0.325 (val F1=0.2464)
  Directional -> Accuracy: 0.4394, MCC: 0.0258, F1: 0.2128

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 16). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.68170 | val 0.88531
  Epoch 012 - train 0.68857 | val 0.75773
  Classification -> best τ=0.550 (val F1=0.2153)
  Directional -> Accuracy: 0.4605, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.69627 | val 0.81130
  Epoch 020 - train 0.59525 | val 1.94796
  Epoch 025 - train 0.60959 | val 1.90140
  Classification -> best τ=0.650 (val F1=0.3031)
  Directional -> Accuracy: 0.3958, MCC: 0.1130, F1: 0.0645

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.70850 | val 0.93070
  Epoch 011 - train 0.67421 | val 1.07107
  Classification -> best τ=0.485 (val F1=0.0959)
  Directional -> Accuracy: 0.5455, MCC: 0.0925, F1: 0.5000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.70651 | val 0.81048
  Epoch 014 - train 0.66512 | val 0.92126
  Classification -> best τ=0.545 (val F1=0.2596)
  Directional -> Accuracy: 0.4310, MCC: -0.0557, F1: 0.1951

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.66233 | val 1.71777
  Epoch 011 - train 0.69262 | val 1.71079
  Classification -> best τ=0.460 (val F1=0.1878)
  Directional -> Accuracy: 0.5455, MCC: 0.0787, F1: 0.4643

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.70239 | val 0.72662
  Epoch 018 - train 0.66745 | val 0.78517
  Classification -> best τ=0.580 (val F1=0.3337)
  Directional -> Accuracy: 0.5714, MCC: 0.3394, F1: 0.3684

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.64121 | val 0.80657
  Epoch 011 - train 0.61402 | val 0.77291
  Classification -> best τ=0.570 (val F1=0.2582)
  Directional -> Accuracy: 0.6596, MCC: 0.2856, F1: 0.5000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.66812 | val 0.68105
  Epoch 020 - train 0.62122 | val 0.77563
  Classification -> best τ=0.550 (val F1=0.1874)
  Directional -> Accuracy: 0.5349, MCC: 0.0746, F1: 0.5652

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.68235 | val 0.77254
  Epoch 016 - train 0.67719 | val 0.84494
  Classification -> best τ=0.325 (val F1=0.2755)
  Directional -> Accuracy: 0.5345, MCC: -0.0033, F1: 0.6667

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.63735 | val 0.96329
  Epoch 020 - train 0.72517 | val 0.67060
  Epoch 030 - train 0.73982 | val 0.66448
  Classification -> best τ=0.625 (val F1=0.3548)
  Directional -> Accuracy: 0.4762, MCC: -0.0123, F1: 0.3889

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.65364 | val 1.11616
  Epoch 015 - train 0.62098 | val 1.76686
  Classification -> best τ=0.580 (val F1=0.2683)
  Directional -> Accuracy: 0.5909, MCC: 0.1826, F1: 0.6087

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.70564 | val 0.73086
  Epoch 014 - train 0.70918 | val 0.74717
  Classification -> best τ=0.400 (val F1=0.2374)
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.66006 | val 0.80355
  Epoch 014 - train 0.66531 | val 0.78326
  Classification -> best τ=0.725 (val F1=0.2320)
  Directional -> Accuracy: 0.4706, MCC: -0.1787, F1: 0.6301

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.67876 | val 0.70788
  Epoch 016 - train 0.65231 | val 0.82343
  Classification -> best τ=0.380 (val F1=0.3290)
  Directional -> Accuracy: 0.5541, MCC: 0.2008, F1: 0.4590

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.63027 | val 0.72533
  Epoch 017 - train 0.59855 | val 0.88406
  Classification -> best τ=0.440 (val F1=0.4773)
  Directional -> Accuracy: 0.5526, MCC: 0.1443, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.65526 | val 0.83893
  Epoch 011 - train 0.76223 | val 1.14390
  Classification -> best τ=0.460 (val F1=0.1336)
  Directional -> Accuracy: 0.4889, MCC: -0.0604, F1: 0.3030

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.66378 | val 0.73913
  Epoch 014 - train 0.66761 | val 0.82349
  Classification -> best τ=0.290 (val F1=0.3431)
  Directional -> Accuracy: 0.5672, MCC: 0.1875, F1: 0.5246

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.66053 | val 0.68980
  Epoch 020 - train 0.63814 | val 0.76706
  Epoch 022 - train 0.64084 | val 0.76867
  Classification -> best τ=0.430 (val F1=0.3180)
  Directional -> Accuracy: 0.6744, MCC: 0.3810, F1: 0.6111

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.64754 | val 1.00144
  Epoch 020 - train 0.62540 | val 0.80354
  Epoch 023 - train 0.63193 | val 0.84545
  Classification -> best τ=0.475 (val F1=0.2261)
  Directional -> Accuracy: 0.4912, MCC: -0.0148, F1: 0.4912

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.65854 | val 0.71531
  Epoch 013 - train 0.62209 | val 1.87332
  Classification -> best τ=0.335 (val F1=0.1661)
  Directional -> Accuracy: 0.5319, MCC: -0.0887, F1: 0.6667

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 16). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.60642 | val 0.98337
  Epoch 012 - train 0.62430 | val 1.06407
  Classification -> best τ=0.430 (val F1=0.4667)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.76281 | val 0.92290
  Epoch 013 - train 0.64218 | val 1.00647
  Classification -> best τ=0.400 (val F1=0.1870)
  Directional -> Accuracy: 0.4872, MCC: -0.2152, F1: 0.6552

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 16). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.69013 | val 0.70332
  Epoch 014 - train 0.66159 | val 0.78207
  Classification -> best τ=0.595 (val F1=0.3075)
  Directional -> Accuracy: 0.5263, MCC: 0.0538, F1: 0.5714

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.65761 | val 0.95315
  Epoch 014 - train 0.70630 | val 0.72623
  Classification -> best τ=0.475 (val F1=0.3254)
  Directional -> Accuracy: 0.4894, MCC: -0.1443, F1: 0.6571

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.69230 | val 0.93307
  Epoch 013 - train 0.61362 | val 1.06938
  Classification -> best τ=0.615 (val F1=0.7593)
  Directional -> Accuracy: 0.4889, MCC: -0.0512, F1: 0.5660

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.71013 | val 0.71230
  Epoch 020 - train 0.62682 | val 0.78821
  Epoch 025 - train 0.58936 | val 0.67609
  Classification -> best τ=0.210 (val F1=0.3647)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.67948 | val 1.20760
  Epoch 011 - train 0.75364 | val 1.10266
  Classification -> best τ=0.495 (val F1=0.3446)
  Directional -> Accuracy: 0.5965, MCC: 0.2585, F1: 0.5106

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.67437 | val 2.35884
  Epoch 011 - train 0.65403 | val 2.71806
  Classification -> best τ=0.620 (val F1=0.3500)
  Directional -> Accuracy: 0.4561, MCC: -0.0974, F1: 0.3922

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.66319 | val 0.83250
  Epoch 020 - train 0.62531 | val 1.38158
  Epoch 021 - train 0.67179 | val 1.54103
  Classification -> best τ=0.355 (val F1=0.2833)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.67557 | val 1.25803
  Epoch 011 - train 0.71383 | val 1.77056
  Classification -> best τ=0.410 (val F1=0.2858)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.70224 | val 0.78477

[I 2026-02-24 23:50:16,223] Trial 74 finished with value: 0.27438387610217774 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 15, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 32, 'learning_rate': 0.007428055151962382, 'weight_decay': 2.5143245014397093e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.8876397353470635, 'early_stopping_min_delta': 6.682759909521673e-05}. Best is trial 32 with value: 0.2908549754956826.

  Epoch 015 - train 0.69987 | val 1.07614
  Classification -> best τ=0.490 (val F1=0.2746)
  Directional -> Accuracy: 0.4677, MCC: -0.1117, F1: 0.1951

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.27438387610217774
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 15
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.66072 | val 0.69439
  Epoch 017 - train 0.67876 | val 0.72164
  Classification -> best τ=0.540 (val F1=0.2931)
  Directional -> Accuracy: 0.5584, MCC: 0.0760, F1: 0.2917

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.62219 | val 1.09739
  Epoch 013 - train 0.59907 | val 1.42551
  Classification -> best τ=0.415 (val F1=0.2317)
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 16). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.73768 | val 0.66802
  Epoch 020 - train 0.67856 | val 0.88345
  Epoch 021 - train 0.73064 | val 0.95113
  Classification -> best τ=0.475 (val F1=0.3361)
  Directional -> Accuracy: 0.5417, MCC: 0.1303, F1: 0.4500

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.69678 | val 1.00640
  Epoch 015 - train 0.70069 | val 1.08451
  Classification -> best τ=0.435 (val F1=0.1565)
  Directional -> Accuracy: 0.5733, MCC: 0.1437, F1: 0.6000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.62840 | val 1.19466
  Epoch 014 - train 0.59183 | val 1.10855
  Classification -> best τ=0.520 (val F1=0.4428)
  Directional -> Accuracy: 0.6923, MCC: 0.4148, F1: 0.6667

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.65117 | val 0.94337
  Epoch 016 - train 0.60021 | val 0.74764
  Classification -> best τ=0.435 (val F1=0.3162)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.71013 | val 0.74591
  Epoch 018 - train 0.70370 | val 0.77230
  Classification -> best τ=0.530 (val F1=0.2143)
  Directional -> Accuracy: 0.4429, MCC: 0.1132, F1: 0.5806

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 16). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.70742 | val 1.82799
  Epoch 011 - train 0.57830 | val 1.73797
  Classification -> best τ=0.605 (val F1=0.2229)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.68384 | val 0.71466
  Epoch 014 - train 0.61311 | val 0.85241
  Classification -> best τ=0.460 (val F1=0.4767)
  Directional -> Accuracy: 0.4878, MCC: -0.0886, F1: 0.3226

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 16). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 16). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.68070 | val 0.80532
  Epoch 015 - train 0.68463 | val 1.06816
  Classification -> best τ=0.405 (val F1=0.1397)
  Directional -> Accuracy: 0.4648, MCC: 0.0443, F1: 0.5957

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.69088 | val 0.72396
  Epoch 014 - train 0.68211 | val 1.01151
  Classification -> best τ=0.440 (val F1=0.3037)
  Directional -> Accuracy: 0.6471, MCC: 0.3003, F1: 0.5263

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.65526 | val 0.88548
  Epoch 015 - train 0.67446 | val 1.18915
  Classification -> best τ=0.630 (val F1=0.2987)
  Directional -> Accuracy: 0.7458, MCC: 0.5185, F1: 0.7059

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.70872 | val 0.83908
  Epoch 014 - train 0.70667 | val 1.22861
  Classification -> best τ=0.555 (val F1=0.2454)
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.66579 | val 0.80723
  Epoch 017 - train 0.72486 | val 0.65034
  Classification -> best τ=0.285 (val F1=0.3784)
  Directional -> Accuracy: 0.5574, MCC: 0.1842, F1: 0.6897

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.65641 | val 0.68183
  Epoch 020 - train 0.57378 | val 1.63759
  Classification -> best τ=0.485 (val F1=0.2500)
  Directional -> Accuracy: 0.4717, MCC: 0.0000, F1: 0.6410

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.67522 | val 0.78232
  Epoch 014 - train 0.69453 | val 0.75069
  Classification -> best τ=0.390 (val F1=0.2605)
  Directional -> Accuracy: 0.5571, MCC: 0.1312, F1: 0.7103

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.69477 | val 1.09237
  Epoch 011 - train 0.71420 | val 0.87642
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6167, MCC: 0.0000, F1: 0.7629

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.69219 | val 1.04455
  Epoch 014 - train 0.66599 | val 1.26848
  Classification -> best τ=0.315 (val F1=0.1533)
  Directional -> Accuracy: 0.5658, MCC: 0.1403, F1: 0.6024

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.66102 | val 0.95864
  Epoch 013 - train 0.66877 | val 1.40333
  Classification -> best τ=0.500 (val F1=0.2249)
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 16). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.63555 | val 1.08753
  Epoch 013 - train 0.67014 | val 0.69535
  Classification -> best τ=0.540 (val F1=0.2313)
  Directional -> Accuracy: 0.4605, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.69541 | val 0.67131
  Epoch 020 - train 0.60686 | val 0.70518
  Epoch 021 - train 0.60014 | val 0.94609
  Classification -> best τ=0.575 (val F1=0.3963)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.69234 | val 1.39268
  Epoch 012 - train 0.65495 | val 1.44834
  Classification -> best τ=0.485 (val F1=0.1650)
  Directional -> Accuracy: 0.5606, MCC: 0.2540, F1: 0.2162

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.66461 | val 0.84306
  Epoch 013 - train 0.65816 | val 1.19519
  Classification -> best τ=0.520 (val F1=0.2494)
  Directional -> Accuracy: 0.6034, MCC: 0.1639, F1: 0.6933

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.69176 | val 1.18822
  Epoch 011 - train 0.69490 | val 1.41307
  Classification -> best τ=0.370 (val F1=0.2678)
  Directional -> Accuracy: 0.4697, MCC: -0.0107, F1: 0.6316

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.69938 | val 0.68106
  Epoch 020 - train 0.67505 | val 0.73942
  Epoch 021 - train 0.64347 | val 0.76168
  Classification -> best τ=0.415 (val F1=0.4283)
  Directional -> Accuracy: 0.6071, MCC: 0.2642, F1: 0.5600

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.57425 | val 0.74143
  Epoch 011 - train 0.63876 | val 0.76260
  Classification -> best τ=0.485 (val F1=0.0292)
  Directional -> Accuracy: 0.4255, MCC: -0.0318, F1: 0.5846

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.73111 | val 0.68127
  Epoch 020 - train 0.63857 | val 1.63151
  Classification -> best τ=0.470 (val F1=0.1818)
  Directional -> Accuracy: 0.5814, MCC: 0.0908, F1: 0.6897

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.72023 | val 0.69944
  Epoch 017 - train 0.66216 | val 0.70869
  Classification -> best τ=0.320 (val F1=0.2369)
  Directional -> Accuracy: 0.5345, MCC: 0.1708, F1: 0.3721

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.66699 | val 0.68894
  Epoch 020 - train 0.66924 | val 0.67045
  Epoch 030 - train 0.60137 | val 0.67758
  Classification -> best τ=0.315 (val F1=0.4543)
  Directional -> Accuracy: 0.5238, MCC: -0.0663, F1: 0.6774

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.67061 | val 1.43813
  Epoch 012 - train 0.69593 | val 2.41053
  Classification -> best τ=0.410 (val F1=0.1574)
  Directional -> Accuracy: 0.5227, MCC: 0.0525, F1: 0.6182

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.71229 | val 0.65884
  Epoch 018 - train 0.63907 | val 0.72125
  Classification -> best τ=0.565 (val F1=0.3408)
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.70637 | val 0.77245
  Epoch 014 - train 0.65267 | val 0.87560
  Classification -> best τ=0.440 (val F1=0.2993)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.67277 | val 0.67326
  Epoch 018 - train 0.68417 | val 1.77149
  Classification -> best τ=0.550 (val F1=0.2681)
  Directional -> Accuracy: 0.4595, MCC: 0.1455, F1: 0.0909

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.63738 | val 0.71472
  Epoch 016 - train 0.61222 | val 0.91518
  Classification -> best τ=0.540 (val F1=0.2496)
  Directional -> Accuracy: 0.5789, MCC: 0.1857, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.72699 | val 0.88183
  Epoch 012 - train 0.65624 | val 0.86657
  Classification -> best τ=0.485 (val F1=0.4350)
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.6364

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.64328 | val 0.70431
  Epoch 013 - train 0.63129 | val 0.68495
  Classification -> best τ=0.305 (val F1=0.2999)
  Directional -> Accuracy: 0.5672, MCC: 0.1875, F1: 0.5246

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.72804 | val 0.75401
  Epoch 020 - train 0.63530 | val 0.69392
  Epoch 026 - train 0.64444 | val 0.69973
  Classification -> best τ=0.635 (val F1=0.2683)
  Directional -> Accuracy: 0.5581, MCC: 0.1788, F1: 0.3448

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.66370 | val 0.69291
  Epoch 011 - train 0.67107 | val 0.75964
  Classification -> best τ=0.470 (val F1=0.1508)
  Directional -> Accuracy: 0.4912, MCC: 0.0040, F1: 0.5672

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.67990 | val 0.68869
  Epoch 015 - train 0.66764 | val 0.94575
  Classification -> best τ=0.360 (val F1=0.1702)
  Directional -> Accuracy: 0.5745, MCC: 0.0406, F1: 0.6875

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 16). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.56384 | val 0.78581
  Epoch 015 - train 0.57392 | val 1.04298
  Classification -> best τ=0.340 (val F1=0.3779)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.75055 | val 0.76621
  Epoch 013 - train 0.69415 | val 0.85416
  Classification -> best τ=0.620 (val F1=0.4154)
  Directional -> Accuracy: 0.4103, MCC: -0.1666, F1: 0.2069

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 16). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.69545 | val 0.75551
  Epoch 017 - train 0.66214 | val 1.25125
  Classification -> best τ=0.425 (val F1=0.3771)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.71851 | val 1.31366
  Epoch 012 - train 0.71503 | val 0.80368
  Classification -> best τ=0.495 (val F1=0.1565)
  Directional -> Accuracy: 0.5745, MCC: 0.1486, F1: 0.5833

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.63071 | val 0.83550
  Epoch 015 - train 0.65018 | val 0.95682
  Classification -> best τ=0.400 (val F1=0.0737)
  Directional -> Accuracy: 0.5778, MCC: 0.1156, F1: 0.6780

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.71349 | val 0.73452
  Epoch 016 - train 0.61639 | val 0.80526
  Classification -> best τ=0.645 (val F1=0.4339)
  Directional -> Accuracy: 0.5500, MCC: 0.0110, F1: 0.3571

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.77260 | val 0.80501
  Epoch 019 - train 0.66718 | val 1.26614
  Classification -> best τ=0.480 (val F1=0.2477)
  Directional -> Accuracy: 0.5965, MCC: 0.2305, F1: 0.5490

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.67176 | val 1.40967
  Epoch 014 - train 0.69214 | val 0.79192
  Classification -> best τ=0.595 (val F1=0.4243)
  Directional -> Accuracy: 0.4912, MCC: 0.1268, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.68048 | val 1.54657
  Epoch 013 - train 0.67276 | val 1.29117
  Classification -> best τ=0.470 (val F1=0.2111)
  Directional -> Accuracy: 0.4259, MCC: -0.1459, F1: 0.4151

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.70161 | val 0.98709
  Epoch 011 - train 0.63645 | val 1.30285
  Classification -> best τ=0.670 (val F1=0.2373)
  Directional -> Accuracy: 0.5789, MCC: 0.2347, F1: 0.7000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.68268 | val 0.75967

[I 2026-02-24 23:52:15,669] Trial 75 finished with value: 0.2693637090550912 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 15, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 32, 'learning_rate': 0.007081917233347823, 'weight_decay': 2.755577210254078e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.8698353757994108, 'early_stopping_min_delta': 5.817009566438838e-05}. Best is trial 32 with value: 0.2908549754956826.

  Epoch 014 - train 0.66504 | val 0.87389
  Classification -> best τ=0.455 (val F1=0.2887)
  Directional -> Accuracy: 0.5645, MCC: 0.1260, F1: 0.5263

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2693637090550912
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 15
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.69458 | val 0.71236
  Epoch 018 - train 0.69772 | val 0.82360
  Classification -> best τ=0.425 (val F1=0.2851)
  Directional -> Accuracy: 0.5065, MCC: -0.0633, F1: 0.2083

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.64669 | val 0.73455
  Epoch 020 - train 0.62911 | val 0.71409
  Epoch 027 - train 0.58126 | val 0.75724
  Classification -> best τ=0.435 (val F1=0.2918)
  Directional -> Accuracy: 0.5870, MCC: 0.1252, F1: 0.6885

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 16). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.69472 | val 0.76484
  Epoch 017 - train 0.69468 | val 0.82768
  Classification -> best τ=0.520 (val F1=0.3938)
  Directional -> Accuracy: 0.4375, MCC: -0.1159, F1: 0.4255

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.70429 | val 0.92849
  Epoch 013 - train 0.65802 | val 1.85967
  Classification -> best τ=0.455 (val F1=0.1778)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.64289 | val 1.19720
  Epoch 014 - train 0.63555 | val 1.40731
  Classification -> best τ=0.555 (val F1=0.4747)
  Directional -> Accuracy: 0.5385, MCC: 0.1581, F1: 0.3684

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.68720 | val 0.73876
  Epoch 012 - train 0.66654 | val 0.97298
  Classification -> best τ=0.425 (val F1=0.3157)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.72025 | val 0.72979
  Epoch 012 - train 0.73485 | val 0.78010
  Classification -> best τ=0.550 (val F1=0.2143)
  Directional -> Accuracy: 0.5429, MCC: 0.0702, F1: 0.4667

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 16). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.73813 | val 0.95867
  Epoch 011 - train 0.63077 | val 1.02506
  Classification -> best τ=0.585 (val F1=0.0198)
  Directional -> Accuracy: 0.4444, MCC: 0.0481, F1: 0.5902

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.72548 | val 0.69781
  Epoch 019 - train 0.71972 | val 0.71786
  Classification -> best τ=0.570 (val F1=0.3318)
  Directional -> Accuracy: 0.6098, MCC: 0.1590, F1: 0.4667

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 16). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 16). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.65584 | val 0.83343
  Epoch 011 - train 0.64013 | val 0.89441
  Classification -> best τ=0.490 (val F1=0.1827)
  Directional -> Accuracy: 0.4789, MCC: 0.0281, F1: 0.5647

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.68335 | val 1.11970
  Epoch 014 - train 0.71472 | val 1.91748
  Classification -> best τ=0.485 (val F1=0.1093)
  Directional -> Accuracy: 0.5098, MCC: -0.0466, F1: 0.1379

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.76803 | val 0.68224
  Epoch 018 - train 0.75946 | val 0.81370
  Classification -> best τ=0.675 (val F1=0.2987)
  Directional -> Accuracy: 0.5254, MCC: 0.1065, F1: 0.2222

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.69950 | val 0.80422
  Epoch 013 - train 0.66792 | val 1.03049
  Classification -> best τ=0.625 (val F1=0.3100)
  Directional -> Accuracy: 0.4419, MCC: -0.2655, F1: 0.0769

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.69511 | val 0.62621
  Epoch 020 - train 0.71506 | val 0.63142
  Epoch 022 - train 0.68150 | val 0.78516
  Classification -> best τ=0.215 (val F1=0.3734)
  Directional -> Accuracy: 0.5738, MCC: 0.2693, F1: 0.7045

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.73467 | val 1.01044
  Epoch 017 - train 0.69051 | val 1.12097
  Classification -> best τ=0.585 (val F1=0.3263)
  Directional -> Accuracy: 0.4717, MCC: -0.0373, F1: 0.5484

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.67922 | val 0.95597
  Epoch 014 - train 0.65780 | val 0.72858
  Classification -> best τ=0.530 (val F1=0.2743)
  Directional -> Accuracy: 0.6714, MCC: 0.3917, F1: 0.7629

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.68528 | val 0.89051
  Epoch 011 - train 0.71312 | val 0.87560
  Classification -> best τ=0.450 (val F1=0.1346)
  Directional -> Accuracy: 0.5333, MCC: -0.1078, F1: 0.6744

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.70123 | val 0.81064
  Epoch 012 - train 0.67493 | val 1.53157
  Classification -> best τ=0.450 (val F1=0.1764)
  Directional -> Accuracy: 0.5921, MCC: 0.1720, F1: 0.6437

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.73505 | val 0.98045
  Epoch 017 - train 0.71998 | val 1.19230
  Classification -> best τ=0.305 (val F1=0.3001)
  Directional -> Accuracy: 0.4697, MCC: 0.0938, F1: 0.2857

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 16). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.71574 | val 1.04840
  Epoch 012 - train 0.71085 | val 1.10955
  Classification -> best τ=0.320 (val F1=0.2637)
  Directional -> Accuracy: 0.5395, MCC: 0.1534, F1: 0.3860

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.65272 | val 1.18752
  Epoch 019 - train 0.61079 | val 1.36902
  Classification -> best τ=0.440 (val F1=0.3769)
  Directional -> Accuracy: 0.3958, MCC: -0.2494, F1: 0.4912

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.69141 | val 0.74370
  Epoch 012 - train 0.70729 | val 1.25584
  Classification -> best τ=0.530 (val F1=0.1578)
  Directional -> Accuracy: 0.6818, MCC: 0.3638, F1: 0.6866

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.69925 | val 0.78254
  Epoch 017 - train 0.65732 | val 0.74587
  Classification -> best τ=0.800 (val F1=0.2437)
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.73443 | val 1.59186
  Epoch 012 - train 0.69318 | val 2.44684
  Classification -> best τ=0.470 (val F1=0.1860)
  Directional -> Accuracy: 0.5455, MCC: 0.1149, F1: 0.5946

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.65224 | val 0.75714
  Epoch 017 - train 0.64865 | val 0.78524
  Classification -> best τ=0.555 (val F1=0.3894)
  Directional -> Accuracy: 0.5357, MCC: 0.1728, F1: 0.3810

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.70037 | val 0.73778
  Epoch 016 - train 0.60307 | val 0.82844
  Classification -> best τ=0.625 (val F1=0.2582)
  Directional -> Accuracy: 0.5745, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.67855 | val 0.68181
  Epoch 020 - train 0.63788 | val 0.71059
  Epoch 022 - train 0.70558 | val 0.71198
  Classification -> best τ=0.620 (val F1=0.1634)
  Directional -> Accuracy: 0.6279, MCC: 0.2025, F1: 0.7419

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.71834 | val 0.70310
  Epoch 014 - train 0.66291 | val 0.79925
  Classification -> best τ=0.430 (val F1=0.2835)
  Directional -> Accuracy: 0.4828, MCC: 0.1703, F1: 0.1176

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.72330 | val 0.75539
  Epoch 012 - train 0.69543 | val 0.68979
  Classification -> best τ=0.420 (val F1=0.3974)
  Directional -> Accuracy: 0.5714, MCC: 0.1194, F1: 0.7097

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.67222 | val 1.22548
  Epoch 011 - train 0.69629 | val 1.46931
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.70108 | val 0.83025
  Epoch 012 - train 0.74618 | val 0.71408
  Classification -> best τ=0.605 (val F1=0.0761)
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.70448 | val 0.66823
  Epoch 020 - train 0.64329 | val 0.85080
  Classification -> best τ=0.375 (val F1=0.3339)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.70560 | val 0.86995
  Epoch 016 - train 0.72480 | val 1.09822
  Classification -> best τ=0.375 (val F1=0.3504)
  Directional -> Accuracy: 0.5405, MCC: 0.1627, F1: 0.4516

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.65599 | val 0.73238
  Epoch 013 - train 0.65936 | val 0.73252
  Classification -> best τ=0.465 (val F1=0.0455)
  Directional -> Accuracy: 0.4737, MCC: -0.0976, F1: 0.6296

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.78146 | val 0.76722
  Epoch 014 - train 0.66703 | val 1.16287
  Classification -> best τ=0.530 (val F1=0.0901)
  Directional -> Accuracy: 0.4667, MCC: -0.2500, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.68140 | val 0.80062
  Epoch 013 - train 0.70366 | val 0.75048
  Classification -> best τ=0.410 (val F1=0.3431)
  Directional -> Accuracy: 0.5970, MCC: 0.2264, F1: 0.5846

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.69653 | val 0.69487
  Epoch 014 - train 0.67728 | val 0.70213
  Classification -> best τ=0.480 (val F1=0.3038)
  Directional -> Accuracy: 0.5116, MCC: 0.0849, F1: 0.1600

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.69329 | val 0.72394
  Epoch 012 - train 0.67574 | val 0.72133
  Classification -> best τ=0.380 (val F1=0.2094)
  Directional -> Accuracy: 0.5088, MCC: 0.0516, F1: 0.6000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.66287 | val 1.04677
  Epoch 014 - train 0.64244 | val 5.04913
  Classification -> best τ=0.515 (val F1=0.2960)
  Directional -> Accuracy: 0.4681, MCC: -0.0096, F1: 0.4681

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 16). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.65331 | val 1.14490
  Epoch 011 - train 0.71213 | val 0.97165
  Classification -> best τ=0.485 (val F1=0.2437)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.74358 | val 0.86617
  Epoch 011 - train 0.70044 | val 0.82703
  Classification -> best τ=0.510 (val F1=0.5235)
  Directional -> Accuracy: 0.5128, MCC: 0.0402, F1: 0.4865

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 16). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.73179 | val 0.70249
  Epoch 016 - train 0.76447 | val 0.90903
  Classification -> best τ=0.490 (val F1=0.4074)
  Directional -> Accuracy: 0.5395, MCC: 0.2027, F1: 0.6847

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.69556 | val 0.70654
  Epoch 020 - train 0.68378 | val 1.06849
  Epoch 021 - train 0.69513 | val 0.90658
  Classification -> best τ=0.530 (val F1=0.2858)
  Directional -> Accuracy: 0.5745, MCC: 0.1726, F1: 0.6774

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.64490 | val 0.99598
  Epoch 013 - train 0.70194 | val 0.99186
  Classification -> best τ=0.465 (val F1=0.1667)
  Directional -> Accuracy: 0.6444, MCC: 0.2883, F1: 0.6667

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.73412 | val 0.69560
  Epoch 011 - train 0.73937 | val 0.71454
  Classification -> best τ=0.600 (val F1=0.4497)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.67690 | val 1.20260
  Epoch 015 - train 0.66760 | val 0.70118
  Classification -> best τ=0.500 (val F1=0.2849)
  Directional -> Accuracy: 0.4561, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.68920 | val 1.38191
  Epoch 012 - train 0.68668 | val 2.50004
  Classification -> best τ=0.585 (val F1=0.3540)
  Directional -> Accuracy: 0.5965, MCC: 0.2896, F1: 0.2581

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.70256 | val 0.94216
  Epoch 014 - train 0.76183 | val 1.13274
  Classification -> best τ=0.395 (val F1=0.2693)
  Directional -> Accuracy: 0.5556, MCC: 0.1090, F1: 0.6571

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.67164 | val 0.80927
  Epoch 011 - train 0.65634 | val 0.96437
  Classification -> best τ=0.360 (val F1=0.2391)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.68275 | val 0.79307

[I 2026-02-24 23:54:06,962] Trial 76 finished with value: 0.2649735450791424 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 15, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 32, 'learning_rate': 0.009646699045206172, 'weight_decay': 4.15134865649993e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.759822754597771, 'early_stopping_min_delta': 0.00029304066062596176}. Best is trial 32 with value: 0.2908549754956826.

  Epoch 012 - train 0.69614 | val 0.97661
  Classification -> best τ=0.420 (val F1=0.2653)
  Directional -> Accuracy: 0.5000, MCC: -0.0679, F1: 0.0606

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2649735450791424
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 15
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.68736 | val 0.69701
  Epoch 020 - train 0.67321 | val 0.66052
  Epoch 030 - train 0.66765 | val 0.66724
  Classification -> best τ=0.615 (val F1=0.2931)
  Directional -> Accuracy: 0.5065, MCC: -0.0886, F1: 0.1364

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.69230 | val 0.68307
  Epoch 020 - train 0.62484 | val 0.72746
  Classification -> best τ=0.395 (val F1=0.3063)
  Directional -> Accuracy: 0.5652, MCC: 0.1055, F1: 0.6296

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 16). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.68201 | val 0.78235
  Epoch 016 - train 0.68732 | val 0.76833
  Classification -> best τ=0.625 (val F1=0.2892)
  Directional -> Accuracy: 0.4583, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.68483 | val 0.72475
  Epoch 011 - train 0.68708 | val 0.74911
  Classification -> best τ=0.510 (val F1=0.2326)
  Directional -> Accuracy: 0.3867, MCC: -0.2935, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.63106 | val 0.66439
  Epoch 019 - train 0.65054 | val 1.05426
  Classification -> best τ=0.560 (val F1=0.4973)
  Directional -> Accuracy: 0.6538, MCC: 0.3880, F1: 0.5714

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.66463 | val 0.72317
  Epoch 015 - train 0.65005 | val 0.74193
  Classification -> best τ=0.510 (val F1=0.2626)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.70743 | val 0.68750
  Epoch 014 - train 0.69316 | val 0.71398
  Classification -> best τ=0.535 (val F1=0.2143)
  Directional -> Accuracy: 0.6286, MCC: 0.1667, F1: 0.2353

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 16). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.66307 | val 1.63862
  Epoch 011 - train 0.64191 | val 1.75786
  Classification -> best τ=0.540 (val F1=0.1195)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.69458 | val 0.65875
  Epoch 020 - train 0.67467 | val 0.66426
  Epoch 028 - train 0.65254 | val 0.65226
  Classification -> best τ=0.470 (val F1=0.3877)
  Directional -> Accuracy: 0.3659, MCC: 0.0000, F1: 0.5357

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 16). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 16). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.65775 | val 0.76818
  Epoch 011 - train 0.67021 | val 0.74092
  Classification -> best τ=0.515 (val F1=0.0120)
  Directional -> Accuracy: 0.4507, MCC: -0.0314, F1: 0.5517

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.66743 | val 0.76240
  Epoch 011 - train 0.68695 | val 0.76954
  Classification -> best τ=0.510 (val F1=0.0557)
  Directional -> Accuracy: 0.4118, MCC: -0.1674, F1: 0.5000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.67763 | val 0.69526
  Epoch 012 - train 0.68567 | val 0.69337
  Classification -> best τ=0.545 (val F1=0.2394)
  Directional -> Accuracy: 0.5593, MCC: 0.2186, F1: 0.2778

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.69433 | val 0.75777
  Epoch 013 - train 0.66513 | val 0.68208
  Classification -> best τ=0.530 (val F1=0.2504)
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.69649 | val 0.67140
  Epoch 020 - train 0.67638 | val 0.62718
  Epoch 028 - train 0.67226 | val 0.63977
  Classification -> best τ=0.315 (val F1=0.3336)
  Directional -> Accuracy: 0.5902, MCC: 0.2209, F1: 0.6914

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.69074 | val 1.00969
  Epoch 014 - train 0.67329 | val 0.87842
  Classification -> best τ=0.535 (val F1=0.3029)
  Directional -> Accuracy: 0.5472, MCC: 0.0830, F1: 0.2000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.66771 | val 0.74127
  Epoch 015 - train 0.67612 | val 0.85870
  Classification -> best τ=0.465 (val F1=0.3997)
  Directional -> Accuracy: 0.5857, MCC: 0.1490, F1: 0.6813

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.68138 | val 0.80734
  Epoch 012 - train 0.70053 | val 0.78140
  Classification -> best τ=0.495 (val F1=0.2402)
  Directional -> Accuracy: 0.5000, MCC: -0.1385, F1: 0.6341

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.67038 | val 0.69420
  Epoch 018 - train 0.68235 | val 0.70085
  Classification -> best τ=0.630 (val F1=0.1800)
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.69861 | val 0.69611
  Epoch 020 - train 0.68176 | val 0.70383
  Epoch 023 - train 0.66355 | val 0.71252
  Classification -> best τ=0.400 (val F1=0.3342)
  Directional -> Accuracy: 0.4848, MCC: -0.0308, F1: 0.5278

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 16). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.67925 | val 0.71109
  Epoch 013 - train 0.66107 | val 0.78094
  Classification -> best τ=0.505 (val F1=0.3157)
  Directional -> Accuracy: 0.4605, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.68285 | val 0.68445
  Epoch 020 - train 0.67887 | val 0.68084
  Epoch 030 - train 0.64599 | val 0.67947
  Classification -> best τ=0.250 (val F1=0.2692)
  Directional -> Accuracy: 0.5833, MCC: -0.0325, F1: 0.7222

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.67942 | val 0.82336
  Epoch 011 - train 0.66715 | val 0.84179
  Classification -> best τ=0.505 (val F1=0.1349)
  Directional -> Accuracy: 0.6212, MCC: 0.2571, F1: 0.5455

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.67347 | val 0.77448
  Epoch 013 - train 0.69227 | val 0.80498
  Classification -> best τ=0.580 (val F1=0.2415)
  Directional -> Accuracy: 0.4655, MCC: 0.1645, F1: 0.1143

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.69119 | val 0.77863
  Epoch 012 - train 0.68855 | val 1.01971
  Classification -> best τ=0.435 (val F1=0.1688)
  Directional -> Accuracy: 0.5303, MCC: 0.0626, F1: 0.5231

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.68138 | val 0.65732
  Epoch 016 - train 0.67159 | val 0.66761
  Classification -> best τ=0.490 (val F1=0.4505)
  Directional -> Accuracy: 0.5536, MCC: 0.1340, F1: 0.5283

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.64330 | val 0.71396
  Epoch 012 - train 0.64318 | val 0.73938
  Classification -> best τ=0.515 (val F1=0.0199)
  Directional -> Accuracy: 0.5106, MCC: 0.0312, F1: 0.4889

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.67975 | val 0.68436
  Epoch 016 - train 0.65217 | val 0.68634
  Classification -> best τ=0.585 (val F1=0.1428)
  Directional -> Accuracy: 0.4651, MCC: -0.0593, F1: 0.4889

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.70034 | val 0.66814
  Epoch 018 - train 0.64368 | val 0.72202
  Classification -> best τ=0.390 (val F1=0.2935)
  Directional -> Accuracy: 0.4828, MCC: 0.1085, F1: 0.1667

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.73502 | val 0.69193
  Epoch 017 - train 0.71595 | val 0.69227
  Classification -> best τ=0.510 (val F1=0.3974)
  Directional -> Accuracy: 0.5952, MCC: 0.1758, F1: 0.7119

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.66894 | val 0.81413
  Epoch 011 - train 0.65247 | val 0.80217
  Classification -> best τ=0.560 (val F1=0.1869)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.3889

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.67188 | val 0.64739
  Epoch 018 - train 0.68588 | val 0.65269
  Classification -> best τ=0.690 (val F1=0.1239)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.70256 | val 0.67785
  Epoch 020 - train 0.62512 | val 0.78682
  Classification -> best τ=0.460 (val F1=0.2461)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.68735 | val 0.66372
  Epoch 020 - train 0.69406 | val 0.73530
  Epoch 026 - train 0.66140 | val 0.81841
  Classification -> best τ=0.380 (val F1=0.3470)
  Directional -> Accuracy: 0.5405, MCC: 0.1186, F1: 0.5143

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.64247 | val 0.74840
  Epoch 011 - train 0.65740 | val 0.75390
  Classification -> best τ=0.400 (val F1=0.3024)
  Directional -> Accuracy: 0.5263, MCC: 0.0679, F1: 0.6400

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.70655 | val 0.72934
  Epoch 012 - train 0.70466 | val 0.73757
  Classification -> best τ=0.505 (val F1=0.2211)
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.6364

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.66711 | val 0.67041
  Epoch 019 - train 0.64329 | val 0.75852
  Classification -> best τ=0.280 (val F1=0.3767)
  Directional -> Accuracy: 0.5075, MCC: 0.1079, F1: 0.3774

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.70855 | val 0.69517
  Epoch 011 - train 0.67323 | val 0.69388
  Classification -> best τ=0.480 (val F1=0.3311)
  Directional -> Accuracy: 0.5116, MCC: 0.0288, F1: 0.4615

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.67734 | val 0.70311
  Epoch 011 - train 0.66055 | val 0.75985
  Classification -> best τ=0.465 (val F1=0.1790)
  Directional -> Accuracy: 0.5263, MCC: 0.0690, F1: 0.5714

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.66510 | val 0.76619
  Epoch 016 - train 0.65542 | val 0.75958
  Classification -> best τ=0.360 (val F1=0.2403)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 16). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.69243 | val 1.07432
  Epoch 011 - train 0.66930 | val 1.02744
  Classification -> best τ=0.525 (val F1=0.2928)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.68857 | val 0.80524
  Epoch 011 - train 0.69381 | val 0.81659
  Classification -> best τ=0.545 (val F1=0.0406)
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.0000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 16). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.68531 | val 0.69715
  Epoch 020 - train 0.66293 | val 0.68397
  Epoch 026 - train 0.64830 | val 0.74503
  Classification -> best τ=0.400 (val F1=0.2888)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.66737 | val 0.81458
  Epoch 012 - train 0.67986 | val 0.85454
  Classification -> best τ=0.530 (val F1=0.1674)
  Directional -> Accuracy: 0.5532, MCC: 0.1704, F1: 0.3226

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.62736 | val 1.12814
  Epoch 011 - train 0.66344 | val 1.06521
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.68800 | val 0.78996
  Epoch 011 - train 0.67614 | val 0.77478
  Classification -> best τ=0.500 (val F1=0.0976)
  Directional -> Accuracy: 0.5500, MCC: -0.0229, F1: 0.3077

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.68597 | val 0.68420
  Epoch 020 - train 0.68683 | val 0.65351
  Epoch 030 - train 0.64436 | val 0.66180
  Classification -> best τ=0.580 (val F1=0.2320)
  Directional -> Accuracy: 0.4912, MCC: 0.0658, F1: 0.2564

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.67121 | val 0.79820
  Epoch 011 - train 0.66342 | val 0.80972
  Classification -> best τ=0.535 (val F1=0.3510)
  Directional -> Accuracy: 0.5614, MCC: 0.1520, F1: 0.1935

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.68147 | val 0.86871
  Epoch 011 - train 0.67753 | val 0.84756
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.66595 | val 0.87566
  Epoch 015 - train 0.68555 | val 0.86704
  Classification -> best τ=0.470 (val F1=0.1963)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.67763 | val 0.71986

[I 2026-02-24 23:56:44,255] Trial 77 finished with value: 0.23778908819538103 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 15, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 32, 'learning_rate': 0.006234129667420977, 'weight_decay': 2.3179722213937525e-05, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.654754676145914, 'early_stopping_min_delta': 0.0004584208619956478}. Best is trial 32 with value: 0.2908549754956826.

  Epoch 017 - train 0.67597 | val 0.80203
  Classification -> best τ=0.410 (val F1=0.2838)
  Directional -> Accuracy: 0.5161, MCC: 0.0435, F1: 0.5714

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.23778908819538103
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.65084 | val 0.71114
  Epoch 018 - train 0.68261 | val 0.70483
  Classification -> best τ=0.600 (val F1=0.2919)
  Directional -> Accuracy: 0.5395, MCC: 0.0059, F1: 0.2222

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.65920 | val 0.71020
  Epoch 012 - train 0.66064 | val 0.79258
  Classification -> best τ=0.480 (val F1=0.1812)
  Directional -> Accuracy: 0.6000, MCC: 0.1323, F1: 0.7353

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.65541 | val 0.87666
  Epoch 016 - train 0.69984 | val 0.85097
  Classification -> best τ=0.740 (val F1=0.3237)
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.66619 | val 2.00627
  Epoch 011 - train 0.71087 | val 0.88899
  Classification -> best τ=0.365 (val F1=0.1867)
  Directional -> Accuracy: 0.5067, MCC: 0.0121, F1: 0.5316

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.65986 | val 0.64451
  Epoch 020 - train 0.58079 | val 0.77059
  Classification -> best τ=0.490 (val F1=0.3725)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.65139 | val 0.72457
  Epoch 019 - train 0.63697 | val 1.42724
  Classification -> best τ=0.505 (val F1=0.3162)
  Directional -> Accuracy: 0.4894, MCC: -0.0815, F1: 0.0769

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.68331 | val 0.75273
  Epoch 013 - train 0.70451 | val 0.72476
  Classification -> best τ=0.620 (val F1=0.1805)
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.71582 | val 0.63357
  Epoch 016 - train 0.61403 | val 0.96509
  Classification -> best τ=0.280 (val F1=0.2588)
  Directional -> Accuracy: 0.4419, MCC: -0.0089, F1: 0.5556

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.72763 | val 0.67939
  Epoch 014 - train 0.65891 | val 0.67516
  Classification -> best τ=0.505 (val F1=0.2335)
  Directional -> Accuracy: 0.4286, MCC: -0.2278, F1: 0.1765

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.66690 | val 0.70915
  Epoch 011 - train 0.64442 | val 0.70520
  Classification -> best τ=0.545 (val F1=0.0387)
  Directional -> Accuracy: 0.4571, MCC: -0.1280, F1: 0.3214

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.68128 | val 2.00645
  Epoch 012 - train 0.61529 | val 1.79934
  Classification -> best τ=0.450 (val F1=0.2722)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.68911 | val 1.30530
  Epoch 016 - train 0.62190 | val 2.11831
  Classification -> best τ=0.440 (val F1=0.2946)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.76639 | val 0.68329
  Epoch 019 - train 0.61234 | val 0.82288
  Classification -> best τ=0.525 (val F1=0.3064)
  Directional -> Accuracy: 0.5476, MCC: 0.1711, F1: 0.6275

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.72645 | val 0.67999
  Epoch 012 - train 0.70878 | val 0.67755
  Classification -> best τ=0.420 (val F1=0.3196)
  Directional -> Accuracy: 0.5167, MCC: 0.0338, F1: 0.4727

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.66205 | val 0.93986
  Epoch 017 - train 0.72698 | val 0.97944
  Classification -> best τ=0.415 (val F1=0.3922)
  Directional -> Accuracy: 0.5192, MCC: -0.0403, F1: 0.1379

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.64822 | val 0.76567
  Epoch 013 - train 0.68902 | val 0.71877
  Classification -> best τ=0.550 (val F1=0.3686)
  Directional -> Accuracy: 0.6232, MCC: 0.2776, F1: 0.7292

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.67419 | val 2.45686
  Epoch 012 - train 0.64093 | val 2.53938
  Classification -> best τ=0.450 (val F1=0.0811)
  Directional -> Accuracy: 0.6102, MCC: 0.1588, F1: 0.6933

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.71618 | val 0.92545
  Epoch 016 - train 0.67323 | val 1.29876
  Classification -> best τ=0.520 (val F1=0.2313)
  Directional -> Accuracy: 0.3867, MCC: -0.1424, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.70327 | val 0.85790
  Epoch 012 - train 0.66437 | val 0.87082
  Classification -> best τ=0.495 (val F1=0.2352)
  Directional -> Accuracy: 0.5692, MCC: 0.2643, F1: 0.4815

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.70874 | val 0.70809
  Epoch 017 - train 0.64650 | val 0.76904
  Classification -> best τ=0.470 (val F1=0.2800)
  Directional -> Accuracy: 0.4800, MCC: 0.1507, F1: 0.0930

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.71798 | val 0.68068
  Epoch 020 - train 0.60869 | val 0.65418
  Epoch 026 - train 0.57450 | val 0.74386
  Classification -> best τ=0.600 (val F1=0.4638)
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.70583 | val 0.71071
  Epoch 011 - train 0.68676 | val 0.71363
  Classification -> best τ=0.410 (val F1=0.1664)
  Directional -> Accuracy: 0.6061, MCC: 0.2425, F1: 0.6829

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.72428 | val 0.70079
  Epoch 017 - train 0.66691 | val 0.68371
  Classification -> best τ=0.565 (val F1=0.3450)
  Directional -> Accuracy: 0.5517, MCC: 0.1044, F1: 0.5806

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.67859 | val 0.76201
  Epoch 012 - train 0.65845 | val 0.70149
  Classification -> best τ=0.540 (val F1=0.2449)
  Directional -> Accuracy: 0.4923, MCC: 0.0075, F1: 0.5823

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.67542 | val 0.67206
  Epoch 018 - train 0.63746 | val 0.71173
  Classification -> best τ=0.530 (val F1=0.4272)
  Directional -> Accuracy: 0.4643, MCC: 0.0136, F1: 0.2105

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.64891 | val 0.87052
  Epoch 014 - train 0.64932 | val 0.70386
  Classification -> best τ=0.490 (val F1=0.2935)
  Directional -> Accuracy: 0.5000, MCC: 0.2317, F1: 0.6349

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.67434 | val 0.68451
  Epoch 013 - train 0.71947 | val 0.75077
  Classification -> best τ=0.555 (val F1=0.2402)
  Directional -> Accuracy: 0.4286, MCC: -0.1132, F1: 0.4000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.66138 | val 0.65879
  Epoch 019 - train 0.62115 | val 0.74900
  Classification -> best τ=0.320 (val F1=0.3280)
  Directional -> Accuracy: 0.5263, MCC: 0.2741, F1: 0.2703

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.72380 | val 0.70422
  Epoch 020 - train 0.67424 | val 0.85254
  Epoch 029 - train 0.53403 | val 1.12822
  Classification -> best τ=0.500 (val F1=0.2403)
  Directional -> Accuracy: 0.3902, MCC: -0.2162, F1: 0.1935

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.73243 | val 0.71401
  Epoch 012 - train 0.67021 | val 0.80251
  Classification -> best τ=0.460 (val F1=0.3365)
  Directional -> Accuracy: 0.5581, MCC: 0.1294, F1: 0.6122

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.70127 | val 0.63184
  Epoch 016 - train 0.68103 | val 1.07266
  Classification -> best τ=0.635 (val F1=0.1377)
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.65926 | val 0.79501
  Epoch 011 - train 0.59794 | val 0.99936
  Classification -> best τ=0.455 (val F1=0.3541)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.66033 | val 0.99487
  Epoch 012 - train 0.67046 | val 0.96281
  Classification -> best τ=0.385 (val F1=0.3505)
  Directional -> Accuracy: 0.5890, MCC: 0.1778, F1: 0.6154

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.67619 | val 0.82356
  Epoch 014 - train 0.60435 | val 0.77521
  Classification -> best τ=0.565 (val F1=0.2887)
  Directional -> Accuracy: 0.5405, MCC: 0.0968, F1: 0.6047

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.68881 | val 0.72263
  Epoch 020 - train 0.69329 | val 0.84553
  Epoch 022 - train 0.64997 | val 0.98734
  Classification -> best τ=0.380 (val F1=0.2920)
  Directional -> Accuracy: 0.4545, MCC: -0.0795, F1: 0.5714

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.70232 | val 0.74965
  Epoch 011 - train 0.68018 | val 0.76857
  Classification -> best τ=0.455 (val F1=0.4292)
  Directional -> Accuracy: 0.5606, MCC: 0.2461, F1: 0.4528

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.67342 | val 0.98827
  Epoch 013 - train 0.72784 | val 1.35143
  Classification -> best τ=0.450 (val F1=0.2986)
  Directional -> Accuracy: 0.7619, MCC: 0.5273, F1: 0.7619

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.66055 | val 1.03337
  Epoch 012 - train 0.67380 | val 1.36979
  Classification -> best τ=0.350 (val F1=0.3217)
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.6341

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.67300 | val 0.99259
  Epoch 013 - train 0.63109 | val 0.89332
  Classification -> best τ=0.510 (val F1=0.2659)
  Directional -> Accuracy: 0.4130, MCC: -0.0062, F1: 0.1818

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.75976 | val 0.64973
  Epoch 020 - train 0.71510 | val 0.64095
  Epoch 030 - train 0.54716 | val 0.64797
  Classification -> best τ=0.390 (val F1=0.6670)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.69417 | val 0.94252
  Epoch 011 - train 0.72740 | val 0.86950
  Classification -> best τ=0.480 (val F1=0.1282)
  Directional -> Accuracy: 0.5135, MCC: 0.0119, F1: 0.5714

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.73493 | val 0.66180
  Epoch 013 - train 0.66138 | val 0.78907
  Classification -> best τ=0.280 (val F1=0.4082)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.68540 | val 0.68238
  Epoch 014 - train 0.67283 | val 0.70891
  Classification -> best τ=0.435 (val F1=0.2855)
  Directional -> Accuracy: 0.5217, MCC: 0.0229, F1: 0.6333

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.69299 | val 0.73538
  Epoch 019 - train 0.55452 | val 1.39733
  Classification -> best τ=0.495 (val F1=0.2557)
  Directional -> Accuracy: 0.5581, MCC: 0.0375, F1: 0.6984

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.72610 | val 0.73477
  Epoch 018 - train 0.61064 | val 0.76225
  Classification -> best τ=0.405 (val F1=0.4682)
  Directional -> Accuracy: 0.3673, MCC: -0.1462, F1: 0.5231

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.72323 | val 0.69278
  Epoch 014 - train 0.70945 | val 0.97906
  Classification -> best τ=0.610 (val F1=0.3040)
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.72782 | val 0.72065
  Epoch 014 - train 0.68297 | val 0.89177
  Classification -> best τ=0.565 (val F1=0.4387)
  Directional -> Accuracy: 0.5536, MCC: 0.1555, F1: 0.6479

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.69635 | val 1.05915
  Epoch 011 - train 0.66811 | val 1.06640
  Classification -> best τ=0.525 (val F1=0.1626)
  Directional -> Accuracy: 0.5556, MCC: 0.1201, F1: 0.5200

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.65460 | val 1.27214
  Epoch 012 - train 0.64320 | val 1.25135
  Classification -> best τ=0.405 (val F1=0.1667)
  Directional -> Accuracy: 0.5357, MCC: 0.1397, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.69691 | val 0.85582
  Epoch 020 - train 0.66989 | val 0.96835

[I 2026-02-24 23:59:05,030] Trial 78 finished with value: 0.2854778105453845 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.1, 'dropout': 0.8, 'batch_size': 32, 'learning_rate': 0.00745719746978342, 'weight_decay': 3.549786880956433e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.9008380760223529, 'early_stopping_min_delta': 0.0009371170617576586}. Best is trial 32 with value: 0.2908549754956826.

  Epoch 023 - train 0.66073 | val 1.49741
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2854778105453845
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.68379 | val 0.66684
  Epoch 016 - train 0.66785 | val 0.79738
  Classification -> best τ=0.585 (val F1=0.2510)
  Directional -> Accuracy: 0.5263, MCC: -0.1479, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.64447 | val 0.70840
  Epoch 016 - train 0.58686 | val 0.83631
  Classification -> best τ=0.485 (val F1=0.1164)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.69405 | val 0.72859
  Epoch 020 - train 0.69079 | val 0.70177
  Epoch 022 - train 0.64676 | val 0.74923
  Classification -> best τ=0.600 (val F1=0.2449)
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.68944 | val 0.74691
  Epoch 011 - train 0.67530 | val 1.28379
  Classification -> best τ=0.450 (val F1=0.1974)
  Directional -> Accuracy: 0.5600, MCC: 0.1059, F1: 0.6118

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.62930 | val 0.67124
  Epoch 019 - train 0.66909 | val 0.74354
  Classification -> best τ=0.520 (val F1=0.4087)
  Directional -> Accuracy: 0.5882, MCC: 0.1697, F1: 0.6769

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.64046 | val 0.76551
  Epoch 011 - train 0.62271 | val 0.81179
  Classification -> best τ=0.485 (val F1=0.2887)
  Directional -> Accuracy: 0.4894, MCC: 0.0000, F1: 0.6571

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.70689 | val 0.74689
  Epoch 011 - train 0.71567 | val 0.74462
  Classification -> best τ=0.375 (val F1=0.2041)
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.67137 | val 0.85102
  Epoch 012 - train 0.73649 | val 0.91893
  Classification -> best τ=0.515 (val F1=0.1752)
  Directional -> Accuracy: 0.4419, MCC: 0.0473, F1: 0.5862

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.67724 | val 0.76073
  Epoch 014 - train 0.64798 | val 0.85449
  Classification -> best τ=0.405 (val F1=0.0829)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.69985 | val 0.74254
  Epoch 011 - train 0.62328 | val 0.81552
  Classification -> best τ=0.480 (val F1=0.1374)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.70128 | val 1.10978
  Epoch 012 - train 0.64653 | val 1.29207
  Classification -> best τ=0.460 (val F1=0.1225)
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.6301

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.68820 | val 1.15941
  Epoch 018 - train 0.65836 | val 1.21240
  Classification -> best τ=0.430 (val F1=0.3308)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.67233 | val 0.71192
  Epoch 011 - train 0.65042 | val 0.76591
  Classification -> best τ=0.570 (val F1=0.1822)
  Directional -> Accuracy: 0.5238, MCC: -0.1419, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.67736 | val 0.76833
  Epoch 020 - train 0.70574 | val 0.92444
  Epoch 025 - train 0.62708 | val 0.74871
  Classification -> best τ=0.555 (val F1=0.3916)
  Directional -> Accuracy: 0.5167, MCC: 0.0338, F1: 0.5538

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.67431 | val 1.17414
  Epoch 013 - train 0.68388 | val 2.02036
  Classification -> best τ=0.530 (val F1=0.2673)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.64645 | val 0.74531
  Epoch 015 - train 0.66512 | val 0.86051
  Classification -> best τ=0.445 (val F1=0.2708)
  Directional -> Accuracy: 0.5942, MCC: 0.1867, F1: 0.7021

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.68523 | val 1.11886
  Epoch 012 - train 0.67420 | val 1.54899
  Classification -> best τ=0.535 (val F1=0.1303)
  Directional -> Accuracy: 0.5593, MCC: 0.2892, F1: 0.5000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.68945 | val 1.12885
  Epoch 011 - train 0.70429 | val 0.96749
  Classification -> best τ=0.535 (val F1=0.0671)
  Directional -> Accuracy: 0.5867, MCC: 0.0680, F1: 0.7048

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.69273 | val 1.10272
  Epoch 012 - train 0.66271 | val 1.30992
  Classification -> best τ=0.450 (val F1=0.2306)
  Directional -> Accuracy: 0.4923, MCC: 0.1307, F1: 0.3265

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.69850 | val 1.40815
  Epoch 014 - train 0.62831 | val 1.03450
  Classification -> best τ=0.475 (val F1=0.2669)
  Directional -> Accuracy: 0.4800, MCC: 0.1507, F1: 0.0930

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.65110 | val 1.50550
  Epoch 012 - train 0.66031 | val 0.83850
  Classification -> best τ=0.475 (val F1=0.2807)
  Directional -> Accuracy: 0.4894, MCC: 0.2066, F1: 0.3333

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.67239 | val 0.84844
  Epoch 011 - train 0.71834 | val 0.76153
  Classification -> best τ=0.505 (val F1=0.2518)
  Directional -> Accuracy: 0.4545, MCC: -0.0911, F1: 0.4375

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.68157 | val 0.75187
  Epoch 016 - train 0.71111 | val 0.71610
  Classification -> best τ=0.690 (val F1=0.3187)
  Directional -> Accuracy: 0.4655, MCC: 0.0995, F1: 0.1622

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.70613 | val 0.75333
  Epoch 012 - train 0.67699 | val 0.82251
  Classification -> best τ=0.460 (val F1=0.2406)
  Directional -> Accuracy: 0.5692, MCC: 0.1561, F1: 0.6111

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.64218 | val 0.79278
  Epoch 013 - train 0.64771 | val 0.73951
  Classification -> best τ=0.445 (val F1=0.3482)
  Directional -> Accuracy: 0.4464, MCC: -0.0622, F1: 0.3111

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.62114 | val 0.77348
  Epoch 014 - train 0.66770 | val 1.09851
  Classification -> best τ=0.550 (val F1=0.1932)
  Directional -> Accuracy: 0.4348, MCC: -0.1055, F1: 0.4583

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.65803 | val 0.73344
  Epoch 018 - train 0.68820 | val 0.86017
  Classification -> best τ=0.565 (val F1=0.2402)
  Directional -> Accuracy: 0.5000, MCC: 0.0430, F1: 0.4615

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.68313 | val 0.84127
  Epoch 011 - train 0.64033 | val 0.80990
  Classification -> best τ=0.445 (val F1=0.2493)
  Directional -> Accuracy: 0.5439, MCC: 0.2554, F1: 0.3500

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.60634 | val 0.75742
  Epoch 017 - train 0.71512 | val 0.75830
  Classification -> best τ=0.530 (val F1=0.0836)
  Directional -> Accuracy: 0.4878, MCC: -0.0121, F1: 0.4615

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.66750 | val 0.71150
  Epoch 015 - train 0.65124 | val 0.73039
  Classification -> best τ=0.430 (val F1=0.2764)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.67782 | val 0.72826
  Epoch 015 - train 0.69556 | val 0.67021
  Classification -> best τ=0.650 (val F1=0.2517)
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.62643 | val 0.75357
  Epoch 014 - train 0.68336 | val 0.93557
  Classification -> best τ=0.625 (val F1=0.1679)
  Directional -> Accuracy: 0.5000, MCC: -0.0939, F1: 0.6479

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.68962 | val 0.67794
  Epoch 019 - train 0.65873 | val 0.80252
  Classification -> best τ=0.345 (val F1=0.3561)
  Directional -> Accuracy: 0.5616, MCC: 0.1530, F1: 0.5429

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.70704 | val 0.75503
  Epoch 011 - train 0.68695 | val 0.80108
  Classification -> best τ=0.470 (val F1=0.4951)
  Directional -> Accuracy: 0.5135, MCC: 0.0416, F1: 0.5909

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.71547 | val 0.85836
  Epoch 011 - train 0.66892 | val 0.93290
  Classification -> best τ=0.460 (val F1=0.3012)
  Directional -> Accuracy: 0.4545, MCC: -0.2585, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.63136 | val 0.80932
  Epoch 011 - train 0.68686 | val 0.78870
  Classification -> best τ=0.380 (val F1=0.2972)
  Directional -> Accuracy: 0.6515, MCC: 0.3543, F1: 0.6349

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.59072 | val 0.76340
  Epoch 017 - train 0.59691 | val 1.15610
  Classification -> best τ=0.585 (val F1=0.3943)
  Directional -> Accuracy: 0.5476, MCC: 0.1706, F1: 0.3448

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.65017 | val 1.29283
  Epoch 011 - train 0.66412 | val 1.32004
  Classification -> best τ=0.390 (val F1=0.2305)
  Directional -> Accuracy: 0.5714, MCC: 0.1260, F1: 0.4545

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.67566 | val 0.84043
  Epoch 011 - train 0.68346 | val 0.82362
  Classification -> best τ=0.440 (val F1=0.2132)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.64551 | val 0.67953
  Epoch 020 - train 0.59596 | val 0.82118
  Epoch 030 - train 0.54609 | val 0.86550
  Classification -> best τ=0.240 (val F1=0.4646)
  Directional -> Accuracy: 0.3469, MCC: -0.1894, F1: 0.5152

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.81718 | val 0.72954
  Epoch 013 - train 0.70225 | val 0.73481
  Classification -> best τ=0.455 (val F1=0.2623)
  Directional -> Accuracy: 0.5946, MCC: 0.3069, F1: 0.4444

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.70105 | val 0.80326
  Epoch 014 - train 0.65014 | val 0.90749
  Classification -> best τ=0.485 (val F1=0.3729)
  Directional -> Accuracy: 0.5200, MCC: 0.1633, F1: 0.6727

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.63485 | val 0.68281
  Epoch 011 - train 0.61401 | val 0.69394
  Classification -> best τ=0.470 (val F1=0.3403)
  Directional -> Accuracy: 0.5652, MCC: 0.1510, F1: 0.5000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.67268 | val 0.96329
  Epoch 012 - train 0.65828 | val 1.08990
  Classification -> best τ=0.475 (val F1=0.2557)
  Directional -> Accuracy: 0.5116, MCC: 0.0153, F1: 0.5532

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.71519 | val 0.71142
  Epoch 016 - train 0.69709 | val 0.75589
  Classification -> best τ=0.480 (val F1=0.4682)
  Directional -> Accuracy: 0.5918, MCC: 0.0552, F1: 0.2857

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.68965 | val 0.93929
  Epoch 016 - train 0.68875 | val 1.17100
  Classification -> best τ=0.485 (val F1=0.2231)
  Directional -> Accuracy: 0.4821, MCC: 0.1255, F1: 0.0645

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.65458 | val 0.75613
  Epoch 014 - train 0.63890 | val 0.81689
  Classification -> best τ=0.670 (val F1=0.3133)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.66619 | val 1.20823
  Epoch 014 - train 0.72380 | val 2.06130
  Classification -> best τ=0.400 (val F1=0.2079)
  Directional -> Accuracy: 0.4815, MCC: -0.0571, F1: 0.5758

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.63470 | val 1.58627
  Epoch 012 - train 0.69984 | val 2.78486
  Classification -> best τ=0.225 (val F1=0.1801)
  Directional -> Accuracy: 0.4821, MCC: -0.0287, F1: 0.4314

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.69388 | val 0.89883
  Epoch 011 - train 0.66363 | val 1.18619

[I 2026-02-25 00:01:17,642] Trial 79 finished with value: 0.2568258861068795 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.0, 'dropout': 0.8, 'batch_size': 32, 'learning_rate': 0.007287718971727443, 'weight_decay': 6.277876997301987e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.8908966925602895, 'early_stopping_min_delta': 0.0012520097735003084}. Best is trial 32 with value: 0.2908549754956826.

  Classification -> best τ=0.455 (val F1=0.1960)
  Directional -> Accuracy: 0.4918, MCC: 0.0338, F1: 0.6265

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2568258861068795
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.67758 | val 1.08259
  Epoch 015 - train 0.67230 | val 0.67330
  Classification -> best τ=0.470 (val F1=0.2510)
  Directional -> Accuracy: 0.5000, MCC: 0.0491, F1: 0.5682

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.65502 | val 1.13780
  Epoch 014 - train 0.61865 | val 0.98281
  Classification -> best τ=0.460 (val F1=0.2431)
  Directional -> Accuracy: 0.5111, MCC: 0.0402, F1: 0.5217

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.68491 | val 0.67335
  Epoch 020 - train 0.60638 | val 0.69765
  Classification -> best τ=0.685 (val F1=0.3237)
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.68875 | val 1.16471
  Epoch 012 - train 0.67394 | val 1.00781
  Classification -> best τ=0.480 (val F1=0.2381)
  Directional -> Accuracy: 0.4667, MCC: 0.1059, F1: 0.0476

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.68348 | val 0.73070
  Epoch 014 - train 0.66952 | val 0.76286
  Classification -> best τ=0.505 (val F1=0.4041)
  Directional -> Accuracy: 0.6078, MCC: 0.2079, F1: 0.6667

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.66746 | val 0.73017
  Epoch 011 - train 0.61089 | val 0.70301
  Classification -> best τ=0.520 (val F1=0.3394)
  Directional -> Accuracy: 0.5106, MCC: 0.0217, F1: 0.5106

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.68391 | val 0.72934
  Epoch 012 - train 0.67892 | val 0.75569
  Classification -> best τ=0.500 (val F1=0.2065)
  Directional -> Accuracy: 0.4928, MCC: 0.0587, F1: 0.5333

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.64108 | val 0.64513
  Epoch 016 - train 0.62168 | val 0.82715
  Classification -> best τ=0.370 (val F1=0.0548)
  Directional -> Accuracy: 0.4419, MCC: -0.0427, F1: 0.5200

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.68496 | val 0.70950
  Epoch 013 - train 0.63232 | val 0.75018
  Classification -> best τ=0.430 (val F1=0.2891)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.63556 | val 0.81936
  Epoch 011 - train 0.65133 | val 0.79339
  Classification -> best τ=0.525 (val F1=0.1998)
  Directional -> Accuracy: 0.5714, MCC: 0.0518, F1: 0.2105

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.69955 | val 1.67964
  Epoch 015 - train 0.61450 | val 1.68147
  Classification -> best τ=0.400 (val F1=0.2778)
  Directional -> Accuracy: 0.5600, MCC: 0.1089, F1: 0.5000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.63636 | val 2.18584
  Epoch 011 - train 0.68990 | val 2.09920
  Classification -> best τ=0.360 (val F1=0.1651)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.68403 | val 0.86824
  Epoch 016 - train 0.66417 | val 0.88550
  Classification -> best τ=0.415 (val F1=0.2235)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.68649 | val 0.70826
  Epoch 012 - train 0.69140 | val 0.67201
  Classification -> best τ=0.400 (val F1=0.2446)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6154

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.67777 | val 2.31783
  Epoch 015 - train 0.67967 | val 2.27280
  Classification -> best τ=0.370 (val F1=0.2291)
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.66146 | val 0.82230
  Epoch 013 - train 0.63830 | val 0.90311
  Classification -> best τ=0.400 (val F1=0.2708)
  Directional -> Accuracy: 0.5942, MCC: 0.2667, F1: 0.7255

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.65049 | val 1.90810
  Epoch 012 - train 0.65738 | val 1.60422
  Classification -> best τ=0.440 (val F1=0.1336)
  Directional -> Accuracy: 0.5763, MCC: -0.1088, F1: 0.7253

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.68465 | val 0.74305
  Epoch 011 - train 0.67591 | val 0.73489
  Classification -> best τ=0.590 (val F1=0.2236)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.70511 | val 0.87136
  Epoch 011 - train 0.65637 | val 1.16976
  Classification -> best τ=0.545 (val F1=0.1842)
  Directional -> Accuracy: 0.4769, MCC: 0.0998, F1: 0.2917

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.64947 | val 0.70522
  Epoch 019 - train 0.67112 | val 0.78783
  Classification -> best τ=0.405 (val F1=0.3871)
  Directional -> Accuracy: 0.5200, MCC: 0.2434, F1: 0.2174

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.64010 | val 0.63347
  Epoch 020 - train 0.57642 | val 0.78899
  Epoch 029 - train 0.51627 | val 0.64078
  Classification -> best τ=0.515 (val F1=0.3803)
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.69479 | val 0.79388
  Epoch 014 - train 0.70104 | val 1.00857
  Classification -> best τ=0.490 (val F1=0.1270)
  Directional -> Accuracy: 0.5606, MCC: 0.1217, F1: 0.5397

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.68921 | val 0.66335
  Epoch 020 - train 0.66563 | val 1.02542
  Epoch 022 - train 0.68831 | val 1.32047
  Classification -> best τ=0.545 (val F1=0.3482)
  Directional -> Accuracy: 0.5345, MCC: 0.1867, F1: 0.4000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.68349 | val 0.69229
  Epoch 015 - train 0.67525 | val 0.71589
  Classification -> best τ=0.465 (val F1=0.1588)
  Directional -> Accuracy: 0.5231, MCC: 0.0719, F1: 0.5974

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.64815 | val 0.65546
  Epoch 019 - train 0.57982 | val 0.95167
  Classification -> best τ=0.455 (val F1=0.4272)
  Directional -> Accuracy: 0.5179, MCC: 0.1188, F1: 0.3721

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.57581 | val 0.87943
  Epoch 011 - train 0.68202 | val 0.90199
  Classification -> best τ=0.535 (val F1=0.0198)
  Directional -> Accuracy: 0.4348, MCC: -0.0406, F1: 0.5806

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.72301 | val 0.69866
  Epoch 020 - train 0.62926 | val 0.69175
  Epoch 028 - train 0.62644 | val 0.68743
  Classification -> best τ=0.675 (val F1=0.1936)
  Directional -> Accuracy: 0.4524, MCC: -0.0168, F1: 0.3030

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.65419 | val 0.72008
  Epoch 016 - train 0.63747 | val 0.86218
  Classification -> best τ=0.545 (val F1=0.3340)
  Directional -> Accuracy: 0.5439, MCC: 0.1441, F1: 0.4800

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.64761 | val 0.69100
  Epoch 013 - train 0.61103 | val 0.83543
  Classification -> best τ=0.520 (val F1=0.0483)
  Directional -> Accuracy: 0.4390, MCC: -0.1678, F1: 0.5490

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.69176 | val 0.89933
  Epoch 011 - train 0.70158 | val 0.94154
  Classification -> best τ=0.555 (val F1=0.0765)
  Directional -> Accuracy: 0.5349, MCC: 0.0691, F1: 0.3333

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.66021 | val 0.66477
  Epoch 015 - train 0.63903 | val 0.68889
  Classification -> best τ=0.720 (val F1=0.0222)
  Directional -> Accuracy: 0.5581, MCC: 0.1655, F1: 0.7077

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.69045 | val 0.74621
  Epoch 016 - train 0.63086 | val 1.00029
  Classification -> best τ=0.310 (val F1=0.3987)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.68930 | val 0.69742
  Epoch 017 - train 0.66618 | val 0.73950
  Classification -> best τ=0.310 (val F1=0.3615)
  Directional -> Accuracy: 0.5753, MCC: 0.1768, F1: 0.5634

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.70623 | val 0.75420
  Epoch 011 - train 0.69568 | val 0.79273
  Classification -> best τ=0.470 (val F1=0.3627)
  Directional -> Accuracy: 0.4865, MCC: -0.0236, F1: 0.5128

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.69129 | val 0.91330
  Epoch 013 - train 0.64951 | val 1.17715
  Classification -> best τ=0.525 (val F1=0.5033)
  Directional -> Accuracy: 0.5682, MCC: 0.2471, F1: 0.6780

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.62572 | val 0.72861
  Epoch 020 - train 0.61418 | val 0.67087
  Epoch 030 - train 0.60588 | val 0.88665
  Classification -> best τ=0.380 (val F1=0.3634)
  Directional -> Accuracy: 0.5606, MCC: 0.0964, F1: 0.6234

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.59907 | val 0.81682
  Epoch 011 - train 0.64124 | val 0.96070
  Classification -> best τ=0.520 (val F1=0.2206)
  Directional -> Accuracy: 0.6190, MCC: 0.2364, F1: 0.6364

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.67095 | val 1.07148
  Epoch 013 - train 0.61240 | val 1.45389
  Classification -> best τ=0.450 (val F1=0.2530)
  Directional -> Accuracy: 0.4821, MCC: 0.0174, F1: 0.6027

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.66227 | val 0.74323
  Epoch 012 - train 0.64616 | val 1.03701
  Classification -> best τ=0.370 (val F1=0.3105)
  Directional -> Accuracy: 0.5435, MCC: 0.0321, F1: 0.6316

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.68450 | val 0.66367
  Epoch 020 - train 0.61120 | val 0.63259
  Epoch 030 - train 0.53977 | val 0.64619
  Classification -> best τ=0.245 (val F1=0.6130)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.71754 | val 0.77564
  Epoch 012 - train 0.84527 | val 0.84793
  Classification -> best τ=0.505 (val F1=0.0585)
  Directional -> Accuracy: 0.4595, MCC: -0.0194, F1: 0.0909

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.66677 | val 0.71323
  Epoch 014 - train 0.65916 | val 0.70969
  Classification -> best τ=0.415 (val F1=0.2725)
  Directional -> Accuracy: 0.4800, MCC: -0.0501, F1: 0.6286

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.70249 | val 0.69555
  Epoch 017 - train 0.64790 | val 0.70705
  Classification -> best τ=0.450 (val F1=0.2681)
  Directional -> Accuracy: 0.5435, MCC: 0.0961, F1: 0.5116

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.80667 | val 0.75692
  Epoch 016 - train 0.64662 | val 0.88999
  Classification -> best τ=0.510 (val F1=0.4799)
  Directional -> Accuracy: 0.5814, MCC: 0.1280, F1: 0.6667

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.76378 | val 0.75079
  Epoch 020 - train 0.63168 | val 0.84106
  Epoch 023 - train 0.61014 | val 0.74943
  Classification -> best τ=0.530 (val F1=0.3752)
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.69934 | val 0.74877
  Epoch 013 - train 0.67466 | val 0.78575
  Classification -> best τ=0.455 (val F1=0.2028)
  Directional -> Accuracy: 0.6607, MCC: 0.3405, F1: 0.6415

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.68715 | val 0.92764
  Epoch 014 - train 0.67613 | val 1.01851
  Classification -> best τ=0.570 (val F1=0.2777)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.65886 | val 1.35011
  Epoch 013 - train 0.67347 | val 1.78348
  Classification -> best τ=0.400 (val F1=0.2952)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.66899 | val 1.32970
  Epoch 011 - train 0.63934 | val 1.45029
  Classification -> best τ=0.605 (val F1=0.2222)
  Directional -> Accuracy: 0.5179, MCC: 0.0187, F1: 0.6301

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.66449 | val 0.88716

[I 2026-02-25 00:03:38,979] Trial 80 finished with value: 0.26303495593830556 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.1, 'dropout': 0.8, 'batch_size': 32, 'learning_rate': 0.005067811676025338, 'weight_decay': 9.475523179999842e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.7778906597872186, 'early_stopping_min_delta': 0.000578083146126355}. Best is trial 32 with value: 0.2908549754956826.

  Epoch 014 - train 0.70449 | val 0.77552
  Classification -> best τ=0.400 (val F1=0.2879)
  Directional -> Accuracy: 0.5574, MCC: 0.1175, F1: 0.5574

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.26303495593830556
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.66934 | val 0.68484
  Epoch 018 - train 0.65235 | val 0.76728
  Classification -> best τ=0.700 (val F1=0.2510)
  Directional -> Accuracy: 0.5526, MCC: 0.0363, F1: 0.1905

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.66227 | val 0.69892
  Epoch 016 - train 0.64755 | val 0.71962
  Classification -> best τ=0.450 (val F1=0.2318)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.68969 | val 0.66189
  Epoch 020 - train 0.66715 | val 0.67178
  Epoch 022 - train 0.64480 | val 0.67534
  Classification -> best τ=0.440 (val F1=0.2779)
  Directional -> Accuracy: 0.6383, MCC: 0.3262, F1: 0.7385

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.65301 | val 1.21983
  Epoch 011 - train 0.66531 | val 1.28520
  Classification -> best τ=0.480 (val F1=0.1813)
  Directional -> Accuracy: 0.5067, MCC: -0.1360, F1: 0.6667

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.66088 | val 0.62654
  Epoch 020 - train 0.62000 | val 0.63918
  Epoch 021 - train 0.61024 | val 0.63603
  Classification -> best τ=0.590 (val F1=0.3795)
  Directional -> Accuracy: 0.5882, MCC: 0.2031, F1: 0.5333

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.65997 | val 0.69184
  Epoch 020 - train 0.66286 | val 0.69659
  Epoch 024 - train 0.65329 | val 0.69632
  Classification -> best τ=0.580 (val F1=0.2357)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.67305 | val 0.69872
  Epoch 013 - train 0.69287 | val 0.69972
  Classification -> best τ=0.425 (val F1=0.1945)
  Directional -> Accuracy: 0.4203, MCC: 0.1002, F1: 0.5833

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.65825 | val 0.69381
  Epoch 018 - train 0.65034 | val 0.71814
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.5902

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.66137 | val 0.69547
  Epoch 020 - train 0.64374 | val 0.66860
  Epoch 030 - train 0.62964 | val 0.67235
  Classification -> best τ=0.470 (val F1=0.3475)
  Directional -> Accuracy: 0.5714, MCC: 0.1599, F1: 0.0870

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.64896 | val 0.78700
  Epoch 011 - train 0.63830 | val 0.79233
  Classification -> best τ=0.490 (val F1=0.2341)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.68671 | val 0.76684
  Epoch 011 - train 0.64598 | val 0.78848
  Classification -> best τ=0.500 (val F1=0.1021)
  Directional -> Accuracy: 0.5400, MCC: 0.0401, F1: 0.3030

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.69185 | val 0.76054
  Epoch 011 - train 0.64681 | val 0.76542
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.64323 | val 0.71031
  Epoch 011 - train 0.63905 | val 0.71157
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.66655 | val 0.65696
  Epoch 020 - train 0.68068 | val 0.67848
  Epoch 023 - train 0.64385 | val 0.69233
  Classification -> best τ=0.445 (val F1=0.2662)
  Directional -> Accuracy: 0.6000, MCC: 0.2018, F1: 0.6250

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.68406 | val 0.77451
  Epoch 011 - train 0.65700 | val 0.77677
  Classification -> best τ=0.540 (val F1=0.1670)
  Directional -> Accuracy: 0.5385, MCC: 0.0976, F1: 0.5714

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.64565 | val 0.68738
  Epoch 016 - train 0.62600 | val 0.69050
  Classification -> best τ=0.420 (val F1=0.2265)
  Directional -> Accuracy: 0.5362, MCC: 0.0000, F1: 0.6981

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.68452 | val 1.23444
  Epoch 011 - train 0.65250 | val 1.29895
  Classification -> best τ=0.515 (val F1=0.0516)
  Directional -> Accuracy: 0.6441, MCC: 0.2461, F1: 0.7123

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.66497 | val 1.12848
  Epoch 013 - train 0.66386 | val 1.29264
  Classification -> best τ=0.525 (val F1=0.1923)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.66516 | val 0.78367
  Epoch 014 - train 0.67050 | val 0.76748
  Classification -> best τ=0.520 (val F1=0.1809)
  Directional -> Accuracy: 0.4154, MCC: -0.0306, F1: 0.0500

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.64754 | val 0.72796
  Epoch 014 - train 0.63872 | val 0.70101
  Classification -> best τ=0.485 (val F1=0.1808)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.66888 | val 0.69230
  Epoch 011 - train 0.65834 | val 0.69292
  Classification -> best τ=0.520 (val F1=0.1261)
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.67945 | val 0.73916
  Epoch 013 - train 0.66518 | val 0.75957
  Classification -> best τ=0.490 (val F1=0.1688)
  Directional -> Accuracy: 0.5303, MCC: 0.0741, F1: 0.3404

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.68716 | val 0.68663
  Epoch 019 - train 0.67312 | val 0.69976
  Classification -> best τ=0.595 (val F1=0.2710)
  Directional -> Accuracy: 0.5000, MCC: 0.1813, F1: 0.2564

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.65596 | val 0.72295
  Epoch 015 - train 0.66523 | val 0.73849
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4769, MCC: 0.0000, F1: 0.6458

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.69071 | val 0.65024
  Epoch 020 - train 0.64525 | val 0.65437
  Epoch 022 - train 0.67031 | val 0.65695
  Classification -> best τ=0.550 (val F1=0.4297)
  Directional -> Accuracy: 0.4464, MCC: -0.0373, F1: 0.1622

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.73218 | val 0.70358
  Epoch 011 - train 0.64223 | val 0.70418
  Classification -> best τ=0.470 (val F1=0.1890)
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.71579 | val 0.78002
  Epoch 011 - train 0.68382 | val 0.80316
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.65524 | val 0.68006
  Epoch 016 - train 0.64946 | val 0.70107
  Classification -> best τ=0.445 (val F1=0.2391)
  Directional -> Accuracy: 0.5965, MCC: 0.2112, F1: 0.5965

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.66630 | val 0.69891
  Epoch 011 - train 0.62561 | val 0.70057
  Classification -> best τ=0.505 (val F1=0.0989)
  Directional -> Accuracy: 0.5122, MCC: 0.0337, F1: 0.5000

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.68880 | val 0.69205
  Epoch 011 - train 0.66627 | val 0.69443
  Classification -> best τ=0.480 (val F1=0.0548)
  Directional -> Accuracy: 0.5581, MCC: 0.1182, F1: 0.4242

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.68308 | val 0.67863
  Epoch 020 - train 0.67642 | val 0.69536
  Epoch 022 - train 0.64733 | val 0.69611
  Classification -> best τ=0.470 (val F1=0.2282)
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.63394 | val 0.75941
  Epoch 011 - train 0.65801 | val 0.77022
  Classification -> best τ=0.515 (val F1=0.0599)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.66653 | val 0.67048
  Epoch 020 - train 0.62516 | val 0.67089
  Epoch 030 - train 0.62936 | val 0.67607
  Classification -> best τ=0.500 (val F1=0.2660)
  Directional -> Accuracy: 0.5342, MCC: 0.1602, F1: 0.4138

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.68247 | val 0.69984
  Epoch 011 - train 0.64102 | val 0.70199
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.65065 | val 0.71742
  Epoch 011 - train 0.68006 | val 0.73759
  Classification -> best τ=0.480 (val F1=0.1902)
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.64382 | val 0.69457
  Epoch 016 - train 0.63240 | val 0.69565
  Classification -> best τ=0.405 (val F1=0.3603)
  Directional -> Accuracy: 0.5909, MCC: 0.1587, F1: 0.6494

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.65683 | val 0.69319
  Epoch 015 - train 0.62985 | val 0.72521
  Classification -> best τ=0.525 (val F1=0.2652)
  Directional -> Accuracy: 0.5000, MCC: 0.0561, F1: 0.2222

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.63456 | val 0.74305
  Epoch 016 - train 0.63125 | val 0.83170
  Classification -> best τ=0.400 (val F1=0.2868)
  Directional -> Accuracy: 0.4821, MCC: -0.0083, F1: 0.5538

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.62761 | val 0.71951
  Epoch 011 - train 0.64134 | val 0.73090
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.73082 | val 0.66599
  Epoch 020 - train 0.62728 | val 0.63364
  Epoch 030 - train 0.65115 | val 0.62104
  Classification -> best τ=0.315 (val F1=0.4708)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.69652 | val 0.70982
  Epoch 011 - train 0.69225 | val 0.71030
  Classification -> best τ=0.530 (val F1=0.3545)
  Directional -> Accuracy: 0.4595, MCC: -0.0358, F1: 0.2308

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.65163 | val 0.69868
  Epoch 015 - train 0.66509 | val 0.71827
  Classification -> best τ=0.465 (val F1=0.2776)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.65755 | val 0.67823
  Epoch 020 - train 0.64743 | val 0.73914
  Classification -> best τ=0.465 (val F1=0.3403)
  Directional -> Accuracy: 0.5000, MCC: 0.1427, F1: 0.0800

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.64728 | val 0.72160
  Epoch 011 - train 0.62701 | val 0.72397
  Classification -> best τ=0.540 (val F1=0.2282)
  Directional -> Accuracy: 0.5116, MCC: -0.1965, F1: 0.6769

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.69111 | val 0.70826
  Epoch 011 - train 0.67343 | val 0.70981
  Classification -> best τ=0.505 (val F1=0.2689)
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.69046 | val 0.76488
  Epoch 011 - train 0.67736 | val 0.77478
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.64387 | val 0.80325
  Epoch 013 - train 0.64031 | val 0.83695
  Classification -> best τ=0.535 (val F1=0.1937)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.67189 | val 0.83711
  Epoch 011 - train 0.66022 | val 0.87418
  Classification -> best τ=0.475 (val F1=0.0048)
  Directional -> Accuracy: 0.4444, MCC: -0.1131, F1: 0.2105

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.66820 | val 0.89029
  Epoch 011 - train 0.65007 | val 0.92779
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.69257 | val 0.70985

[I 2026-02-25 00:06:03,737] Trial 81 finished with value: 0.18516780083212783 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.1, 'dropout': 0.8, 'batch_size': 32, 'learning_rate': 9.651330084903079e-05, 'weight_decay': 3.551954011887095e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.8457901215250632, 'early_stopping_min_delta': 0.0007178127684042573}. Best is trial 32 with value: 0.2908549754956826.

  Epoch 011 - train 0.67618 | val 0.74208
  Classification -> best τ=0.465 (val F1=0.1848)
  Directional -> Accuracy: 0.4754, MCC: -0.0680, F1: 0.3600

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.18516780083212783
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 10
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.69383 | val 0.69799
  Epoch 016 - train 0.68205 | val 0.83476
  Classification -> best τ=0.530 (val F1=0.2863)
  Directional -> Accuracy: 0.5513, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.68816 | val 0.76409
  Epoch 013 - train 0.65733 | val 0.74970
  Classification -> best τ=0.445 (val F1=0.2171)
  Directional -> Accuracy: 0.5319, MCC: -0.1325, F1: 0.6944

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 11). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.75693 | val 0.68205
  Epoch 011 - train 0.73129 | val 0.72519
  Classification -> best τ=0.470 (val F1=0.4523)
  Directional -> Accuracy: 0.5714, MCC: 0.1377, F1: 0.6866

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.72385 | val 0.69274
  Epoch 020 - train 0.66106 | val 0.69156
  Epoch 026 - train 0.68724 | val 0.69499
  Classification -> best τ=0.465 (val F1=0.2388)
  Directional -> Accuracy: 0.5395, MCC: 0.0000, F1: 0.7009

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.68527 | val 0.70147
  Epoch 014 - train 0.68067 | val 0.73999
  Classification -> best τ=0.575 (val F1=0.4508)
  Directional -> Accuracy: 0.5192, MCC: 0.2291, F1: 0.1935

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.61234 | val 1.67578
  Epoch 013 - train 0.72346 | val 2.10276
  Classification -> best τ=0.570 (val F1=0.4972)
  Directional -> Accuracy: 0.4898, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.70698 | val 0.68298
  Epoch 017 - train 0.71505 | val 0.69112
  Classification -> best τ=0.410 (val F1=0.2817)
  Directional -> Accuracy: 0.4648, MCC: 0.0517, F1: 0.5581

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 11). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.71193 | val 2.45790
  Epoch 011 - train 0.66945 | val 2.34570
  Classification -> best τ=0.635 (val F1=0.0137)
  Directional -> Accuracy: 0.4130, MCC: 0.0000, F1: 0.5846

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.66946 | val 0.70323
  Epoch 020 - train 0.72224 | val 0.83997
  Epoch 027 - train 0.65693 | val 0.93120
  Classification -> best τ=0.355 (val F1=0.3364)
  Directional -> Accuracy: 0.6190, MCC: 0.1001, F1: 0.2727

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for proper time series validation for BRK-A. Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for proper time series validation for BSAC. Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.78057 | val 0.89237
  Epoch 012 - train 0.69237 | val 0.84861
  Classification -> best τ=0.535 (val F1=0.1679)
  Directional -> Accuracy: 0.5211, MCC: 0.0480, F1: 0.5000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.72318 | val 0.98042
  Epoch 012 - train 0.76568 | val 0.80673
  Classification -> best τ=0.555 (val F1=0.2633)
  Directional -> Accuracy: 0.6154, MCC: 0.2467, F1: 0.3750

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.74301 | val 0.71409
  Epoch 018 - train 0.70033 | val 0.87691
  Classification -> best τ=0.425 (val F1=0.3893)
  Directional -> Accuracy: 0.5932, MCC: 0.2429, F1: 0.7000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.71216 | val 0.94679
  Epoch 016 - train 0.66795 | val 1.99337
  Classification -> best τ=0.580 (val F1=0.3416)
  Directional -> Accuracy: 0.5227, MCC: 0.0335, F1: 0.4615

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.67630 | val 0.61895
  Epoch 020 - train 0.68412 | val 0.72485
  Epoch 028 - train 0.69914 | val 0.73263
  Classification -> best τ=0.260 (val F1=0.3442)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.68481 | val 1.03925
  Epoch 014 - train 0.69201 | val 0.82622
  Classification -> best τ=0.430 (val F1=0.2816)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.68593 | val 0.72596
  Epoch 013 - train 0.68100 | val 0.75060
  Classification -> best τ=0.640 (val F1=0.3177)
  Directional -> Accuracy: 0.5211, MCC: 0.0375, F1: 0.5526

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.70384 | val 1.25835
  Epoch 016 - train 0.64654 | val 1.36900
  Classification -> best τ=0.705 (val F1=0.1696)
  Directional -> Accuracy: 0.4098, MCC: -0.0434, F1: 0.2174

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.69515 | val 0.92130
  Epoch 011 - train 0.72427 | val 1.12492
  Classification -> best τ=0.405 (val F1=0.1698)
  Directional -> Accuracy: 0.5325, MCC: 0.1406, F1: 0.5135

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.67334 | val 0.69192
  Epoch 020 - train 0.71613 | val 0.68865
  Epoch 029 - train 0.63898 | val 0.74422
  Classification -> best τ=0.490 (val F1=0.3240)
  Directional -> Accuracy: 0.4328, MCC: 0.0371, F1: 0.0952

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 11). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.69841 | val 0.72469
  Epoch 011 - train 0.71772 | val 0.71867
  Classification -> best τ=0.495 (val F1=0.2143)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.69816 | val 0.81557
  Epoch 013 - train 0.63498 | val 0.87579
  Classification -> best τ=0.655 (val F1=0.2402)
  Directional -> Accuracy: 0.3878, MCC: -0.1561, F1: 0.3750

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.68938 | val 0.78334
  Epoch 013 - train 0.68280 | val 0.71599
  Classification -> best τ=0.540 (val F1=0.1618)
  Directional -> Accuracy: 0.5075, MCC: 0.1213, F1: 0.0571

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.71839 | val 0.74783
  Epoch 014 - train 0.67214 | val 0.74456
  Classification -> best τ=0.615 (val F1=0.3308)
  Directional -> Accuracy: 0.4407, MCC: 0.0423, F1: 0.1081

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.68828 | val 0.73402
  Epoch 011 - train 0.67416 | val 0.86180
  Classification -> best τ=0.530 (val F1=0.1921)
  Directional -> Accuracy: 0.4030, MCC: -0.1936, F1: 0.3939

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.74201 | val 0.73469
  Epoch 015 - train 0.68513 | val 1.26355
  Classification -> best τ=0.505 (val F1=0.5137)
  Directional -> Accuracy: 0.5263, MCC: 0.1434, F1: 0.4000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.70782 | val 0.68538
  Epoch 011 - train 0.65429 | val 0.69431
  Classification -> best τ=0.535 (val F1=0.3350)
  Directional -> Accuracy: 0.4375, MCC: 0.1233, F1: 0.5970

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.69082 | val 0.76097
  Epoch 012 - train 0.71947 | val 0.69046
  Classification -> best τ=0.565 (val F1=0.0940)
  Directional -> Accuracy: 0.4545, MCC: 0.0100, F1: 0.3333

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.70866 | val 0.73778
  Epoch 020 - train 0.64225 | val 0.85339
  Epoch 021 - train 0.66356 | val 0.81897
  Classification -> best τ=0.220 (val F1=0.3100)
  Directional -> Accuracy: 0.5345, MCC: -0.1194, F1: 0.6966

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.64905 | val 0.71206
  Epoch 011 - train 0.62484 | val 0.72834
  Classification -> best τ=0.610 (val F1=0.1852)
  Directional -> Accuracy: 0.4419, MCC: -0.1655, F1: 0.0000

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.77423 | val 0.92445
  Epoch 013 - train 0.72358 | val 0.88392
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.64972 | val 0.86413
  Epoch 020 - train 0.61391 | val 0.65766
  Epoch 022 - train 0.63243 | val 0.83213
  Classification -> best τ=0.705 (val F1=0.2015)
  Directional -> Accuracy: 0.4889, MCC: 0.0138, F1: 0.3429

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.76817 | val 0.68180
  Epoch 020 - train 0.60321 | val 0.66628
  Epoch 030 - train 0.66158 | val 0.83802
  Classification -> best τ=0.305 (val F1=0.3443)
  Directional -> Accuracy: 0.5192, MCC: 0.0000, F1: 0.6835

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.72660 | val 0.71940
  Epoch 018 - train 0.74731 | val 0.77190
  Classification -> best τ=0.560 (val F1=0.2678)
  Directional -> Accuracy: 0.4324, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.67306 | val 0.69815
  Epoch 020 - train 0.60960 | val 0.70210
  Epoch 026 - train 0.58993 | val 1.18883
  Classification -> best τ=0.465 (val F1=0.4345)
  Directional -> Accuracy: 0.4500, MCC: -0.1683, F1: 0.6207

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.71280 | val 0.81234
  Epoch 011 - train 0.69209 | val 0.80794
  Classification -> best τ=0.410 (val F1=0.1954)
  Directional -> Accuracy: 0.6000, MCC: 0.2130, F1: 0.3571

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.67822 | val 0.74046
  Epoch 011 - train 0.77229 | val 0.73631
  Classification -> best τ=0.285 (val F1=0.3101)
  Directional -> Accuracy: 0.5000, MCC: 0.1613, F1: 0.2917

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.68244 | val 0.69655
  Epoch 016 - train 0.69614 | val 0.69716
  Classification -> best τ=0.510 (val F1=0.2637)
  Directional -> Accuracy: 0.5682, MCC: 0.1864, F1: 0.3448

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.64084 | val 0.97811
  Epoch 013 - train 0.70564 | val 0.72357
  Classification -> best τ=0.415 (val F1=0.2475)
  Directional -> Accuracy: 0.5172, MCC: 0.0776, F1: 0.6000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.70695 | val 1.06038
  Epoch 012 - train 0.65262 | val 1.57327
  Classification -> best τ=0.605 (val F1=0.3709)
  Directional -> Accuracy: 0.5833, MCC: 0.0000, F1: 0.7143

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 11). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.71049 | val 0.68146
  Epoch 020 - train 0.58528 | val 0.68827
  Epoch 022 - train 0.60078 | val 0.70584
  Classification -> best τ=0.280 (val F1=0.3647)
  Directional -> Accuracy: 0.3415, MCC: 0.0000, F1: 0.5091

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.75674 | val 0.72542
  Epoch 017 - train 0.66284 | val 0.86602
  Classification -> best τ=0.490 (val F1=0.4336)
  Directional -> Accuracy: 0.5250, MCC: 0.0682, F1: 0.4571

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 11). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.72493 | val 0.67929
  Epoch 011 - train 0.71111 | val 0.70390
  Classification -> best τ=0.560 (val F1=0.3686)
  Directional -> Accuracy: 0.4935, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.70926 | val 0.73280
  Epoch 011 - train 0.68355 | val 0.95066
  Classification -> best τ=0.520 (val F1=0.3118)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.73003 | val 1.05185
  Epoch 015 - train 0.60774 | val 1.31530
  Classification -> best τ=0.600 (val F1=0.4671)
  Directional -> Accuracy: 0.4783, MCC: -0.0156, F1: 0.4545

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.63880 | val 1.16163
  Epoch 012 - train 0.69973 | val 1.91066
  Classification -> best τ=0.630 (val F1=0.3941)
  Directional -> Accuracy: 0.6341, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.71159 | val 0.66778
  Epoch 017 - train 0.65653 | val 0.70347
  Classification -> best τ=0.650 (val F1=0.2373)
  Directional -> Accuracy: 0.4561, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.67341 | val 2.02871
  Epoch 011 - train 0.69063 | val 2.96992
  Classification -> best τ=0.545 (val F1=0.3501)
  Directional -> Accuracy: 0.5690, MCC: 0.2520, F1: 0.6835

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.66887 | val 0.91905
  Epoch 015 - train 0.67328 | val 1.29744
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.78107 | val 0.83455
  Epoch 011 - train 0.70408 | val 0.79366
  Classification -> best τ=0.395 (val F1=0.0461)
  Directional -> Accuracy: 0.5172, MCC: 0.0000, F1: 0.6818

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.69850 | val 0.94797
  Epoch 020 - train 0.70020 | val 0.72057

[I 2026-02-25 00:07:33,583] Trial 82 finished with value: 0.2808013494489068 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 10, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 32, 'learning_rate': 0.00978665761754682, 'weight_decay': 2.266160159100802e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.9104037843388562, 'early_stopping_min_delta': 0.0013568890806701897}. Best is trial 32 with value: 0.2908549754956826.

  Epoch 024 - train 0.64567 | val 0.69934
  Classification -> best τ=0.490 (val F1=0.3108)
  Directional -> Accuracy: 0.5714, MCC: 0.1557, F1: 0.3077

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2808013494489068
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 10
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.65630 | val 0.65883
  Epoch 018 - train 0.63836 | val 0.67458
  Classification -> best τ=0.535 (val F1=0.2807)
  Directional -> Accuracy: 0.5385, MCC: 0.0047, F1: 0.2174

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.63800 | val 0.68684
  Epoch 020 - train 0.61880 | val 0.69451
  Epoch 022 - train 0.61525 | val 0.69564
  Classification -> best τ=0.440 (val F1=0.2451)
  Directional -> Accuracy: 0.5745, MCC: 0.1097, F1: 0.6774

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 11). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.65397 | val 0.76096
  Epoch 011 - train 0.65057 | val 0.78822
  Classification -> best τ=0.465 (val F1=0.1913)
  Directional -> Accuracy: 0.5918, MCC: 0.2003, F1: 0.7059

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.64366 | val 1.29154
  Epoch 011 - train 0.64119 | val 1.32470
  Classification -> best τ=0.490 (val F1=0.1791)
  Directional -> Accuracy: 0.4868, MCC: -0.0182, F1: 0.4800

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.63293 | val 0.67519
  Epoch 018 - train 0.60889 | val 0.68919
  Classification -> best τ=0.455 (val F1=0.4892)
  Directional -> Accuracy: 0.7115, MCC: 0.4173, F1: 0.7458

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.61890 | val 0.72474
  Epoch 011 - train 0.61371 | val 0.75022
  Classification -> best τ=0.490 (val F1=0.1031)
  Directional -> Accuracy: 0.4898, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.66681 | val 0.68502
  Epoch 018 - train 0.64999 | val 0.69024
  Classification -> best τ=0.495 (val F1=0.2723)
  Directional -> Accuracy: 0.4930, MCC: 0.0745, F1: 0.5500

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 11). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.61984 | val 0.87813
  Epoch 011 - train 0.61637 | val 0.93216
  Classification -> best τ=0.525 (val F1=0.0626)
  Directional -> Accuracy: 0.4130, MCC: 0.0000, F1: 0.5846

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.66388 | val 0.70684
  Epoch 011 - train 0.66165 | val 0.71014
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3810, MCC: 0.0000, F1: 0.5517

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for proper time series validation for BRK-A. Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for proper time series validation for BSAC. Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.62815 | val 0.99372
  Epoch 011 - train 0.62482 | val 1.01618
  Classification -> best τ=0.480 (val F1=0.0787)
  Directional -> Accuracy: 0.4366, MCC: 0.0000, F1: 0.6078

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.64775 | val 0.89798
  Epoch 011 - train 0.64395 | val 0.92749
  Classification -> best τ=0.560 (val F1=0.0228)
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.64907 | val 0.76797
  Epoch 011 - train 0.64609 | val 0.78186
  Classification -> best τ=0.495 (val F1=0.1680)
  Directional -> Accuracy: 0.5763, MCC: 0.2992, F1: 0.2857

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.63031 | val 0.86810
  Epoch 011 - train 0.62614 | val 0.95950
  Classification -> best τ=0.515 (val F1=0.1709)
  Directional -> Accuracy: 0.5227, MCC: -0.1392, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.67385 | val 0.66835
  Epoch 020 - train 0.65286 | val 0.60609
  Epoch 030 - train 0.63482 | val 0.59986
  Classification -> best τ=0.435 (val F1=0.3374)
  Directional -> Accuracy: 0.5484, MCC: 0.1189, F1: 0.6500

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.62827 | val 1.11457
  Epoch 011 - train 0.62493 | val 1.30344
  Classification -> best τ=0.485 (val F1=0.1125)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.64312 | val 0.69690
  Epoch 015 - train 0.63010 | val 0.70765
  Classification -> best τ=0.425 (val F1=0.2856)
  Directional -> Accuracy: 0.5493, MCC: 0.1283, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.65293 | val 0.99099
  Epoch 011 - train 0.65061 | val 1.05363
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6066, MCC: 0.0000, F1: 0.7551

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.64078 | val 0.88002
  Epoch 011 - train 0.63753 | val 0.89863
  Classification -> best τ=0.515 (val F1=0.0263)
  Directional -> Accuracy: 0.3896, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.64512 | val 0.71103
  Epoch 011 - train 0.64207 | val 0.71306
  Classification -> best τ=0.465 (val F1=0.1014)
  Directional -> Accuracy: 0.4179, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 11). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.62575 | val 0.67741
  Epoch 017 - train 0.60720 | val 0.68377
  Classification -> best τ=0.580 (val F1=0.3190)
  Directional -> Accuracy: 0.3896, MCC: -0.2055, F1: 0.3380

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.64087 | val 0.68737
  Epoch 020 - train 0.61153 | val 0.68673
  Epoch 024 - train 0.60196 | val 0.69252
  Classification -> best τ=0.460 (val F1=0.2715)
  Directional -> Accuracy: 0.5102, MCC: -0.0792, F1: 0.6250

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.65270 | val 0.89968
  Epoch 011 - train 0.65015 | val 0.92688
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5075, MCC: 0.0000, F1: 0.6733

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.65165 | val 0.71390
  Epoch 016 - train 0.63795 | val 0.75401
  Classification -> best τ=0.540 (val F1=0.2423)
  Directional -> Accuracy: 0.5593, MCC: 0.1515, F1: 0.5517

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.63507 | val 0.90151
  Epoch 011 - train 0.63239 | val 0.91234
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4776, MCC: 0.0000, F1: 0.6465

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.64464 | val 0.65240
  Epoch 019 - train 0.62105 | val 0.66517
  Classification -> best τ=0.435 (val F1=0.4319)
  Directional -> Accuracy: 0.5789, MCC: 0.1613, F1: 0.6000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.66654 | val 0.74157
  Epoch 011 - train 0.66250 | val 0.75087
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4167, MCC: 0.0000, F1: 0.5882

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.64437 | val 0.90041
  Epoch 011 - train 0.64047 | val 0.96618
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.7429

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.64958 | val 0.67520
  Epoch 018 - train 0.62556 | val 0.71835
  Classification -> best τ=0.430 (val F1=0.2966)
  Directional -> Accuracy: 0.5172, MCC: 0.1923, F1: 0.2632

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.64818 | val 0.70441
  Epoch 011 - train 0.64432 | val 0.70590
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.65103 | val 0.69938
  Epoch 011 - train 0.64788 | val 0.70283
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.65241 | val 0.70470
  Epoch 020 - train 0.62011 | val 0.68880
  Epoch 025 - train 0.60787 | val 0.69323
  Classification -> best τ=0.460 (val F1=0.2193)
  Directional -> Accuracy: 0.5333, MCC: 0.0144, F1: 0.6866

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.64163 | val 0.65727
  Epoch 020 - train 0.60935 | val 0.66015
  Epoch 021 - train 0.60697 | val 0.66126
  Classification -> best τ=0.465 (val F1=0.2909)
  Directional -> Accuracy: 0.5192, MCC: 0.0000, F1: 0.6835

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.66553 | val 0.70973
  Epoch 020 - train 0.64184 | val 0.69476
  Epoch 030 - train 0.62209 | val 0.69119
  Classification -> best τ=0.540 (val F1=0.2916)
  Directional -> Accuracy: 0.5541, MCC: 0.2008, F1: 0.4590

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.65196 | val 0.69493
  Epoch 011 - train 0.64857 | val 0.69574
  Classification -> best τ=0.510 (val F1=0.1608)
  Directional -> Accuracy: 0.5000, MCC: 0.0187, F1: 0.5652

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.62918 | val 0.80036
  Epoch 011 - train 0.62586 | val 0.84508
  Classification -> best τ=0.485 (val F1=0.2828)
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.6364

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.63485 | val 0.70265
  Epoch 014 - train 0.62549 | val 0.70829
  Classification -> best τ=0.380 (val F1=0.3575)
  Directional -> Accuracy: 0.5735, MCC: 0.2013, F1: 0.5397

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.65288 | val 0.68754
  Epoch 020 - train 0.62691 | val 0.68775
  Epoch 022 - train 0.62249 | val 0.68852
  Classification -> best τ=0.560 (val F1=0.2564)
  Directional -> Accuracy: 0.4773, MCC: -0.0902, F1: 0.0800

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.62020 | val 0.78380
  Epoch 011 - train 0.61769 | val 0.79676
  Classification -> best τ=0.520 (val F1=0.1546)
  Directional -> Accuracy: 0.4655, MCC: -0.0540, F1: 0.5079

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.63556 | val 0.77477
  Epoch 011 - train 0.63032 | val 0.80316
  Classification -> best τ=0.475 (val F1=0.2726)
  Directional -> Accuracy: 0.6042, MCC: 0.0176, F1: 0.7397

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 11). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.64037 | val 0.69740
  Epoch 020 - train 0.59716 | val 0.67391
  Epoch 030 - train 0.56534 | val 0.67125
  Classification -> best τ=0.440 (val F1=0.5373)
  Directional -> Accuracy: 0.3902, MCC: 0.1631, F1: 0.5283

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.63057 | val 0.70864
  Epoch 011 - train 0.62626 | val 0.71338
  Classification -> best τ=0.500 (val F1=0.1690)
  Directional -> Accuracy: 0.5500, MCC: 0.1256, F1: 0.4706

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 11). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.64953 | val 0.71697
  Epoch 015 - train 0.63609 | val 0.75279
  Classification -> best τ=0.460 (val F1=0.2637)
  Directional -> Accuracy: 0.5065, MCC: 0.0000, F1: 0.6724

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.66521 | val 0.68996
  Epoch 011 - train 0.66131 | val 0.69068
  Classification -> best τ=0.470 (val F1=0.1502)
  Directional -> Accuracy: 0.4583, MCC: -0.1118, F1: 0.5938

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.64801 | val 0.69047
  Epoch 011 - train 0.64173 | val 0.69801
  Classification -> best τ=0.455 (val F1=0.1273)
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.64045 | val 0.78713
  Epoch 011 - train 0.63535 | val 0.81771
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3659, MCC: 0.0000, F1: 0.5357

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.64447 | val 0.96615
  Epoch 011 - train 0.64129 | val 0.99011
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5439, MCC: 0.0000, F1: 0.7045

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.65039 | val 0.75342
  Epoch 011 - train 0.64718 | val 0.77281
  Classification -> best τ=0.480 (val F1=0.1588)
  Directional -> Accuracy: 0.4828, MCC: 0.0000, F1: 0.6512

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.64843 | val 1.08684
  Epoch 011 - train 0.64554 | val 1.23422
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.64105 | val 0.86894
  Epoch 011 - train 0.63770 | val 0.88977
  Classification -> best τ=0.500 (val F1=0.0263)
  Directional -> Accuracy: 0.5172, MCC: 0.0213, F1: 0.6111

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.65012 | val 0.93360
  Epoch 011 - train 0.64745 | val 1.00047

[I 2026-02-25 00:08:56,922] Trial 83 finished with value: 0.17244217933139286 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 10, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.0, 'batch_size': 32, 'learning_rate': 4.0522044903887015e-05, 'weight_decay': 2.3393054869597257e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.9543478395436018, 'early_stopping_min_delta': 0.0013836970869855237}. Best is trial 32 with value: 0.2908549754956826.

  Classification -> best τ=0.465 (val F1=0.2146)
  Directional -> Accuracy: 0.5079, MCC: 0.1179, F1: 0.6517

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.17244217933139286
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 10
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.71536 | val 0.69322
  Epoch 015 - train 0.68782 | val 0.69005
  Classification -> best τ=0.530 (val F1=0.3222)
  Directional -> Accuracy: 0.5256, MCC: -0.0501, F1: 0.1395

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.69229 | val 0.76851
  Epoch 015 - train 0.68579 | val 0.68950
  Classification -> best τ=0.420 (val F1=0.3101)
  Directional -> Accuracy: 0.5532, MCC: 0.0000, F1: 0.7123

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 11). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.71773 | val 0.80529
  Epoch 011 - train 0.66347 | val 0.93578
  Classification -> best τ=0.520 (val F1=0.3685)
  Directional -> Accuracy: 0.4286, MCC: -0.1477, F1: 0.1250

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.68460 | val 0.85729
  Epoch 014 - train 0.67368 | val 1.87413
  Classification -> best τ=0.455 (val F1=0.1192)
  Directional -> Accuracy: 0.5921, MCC: 0.1672, F1: 0.6804

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.65610 | val 0.67276
  Epoch 016 - train 0.69329 | val 0.65865
  Classification -> best τ=0.575 (val F1=0.4699)
  Directional -> Accuracy: 0.7115, MCC: 0.4622, F1: 0.6809

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.68623 | val 1.08828
  Epoch 013 - train 0.55864 | val 1.03021
  Classification -> best τ=0.380 (val F1=0.3810)
  Directional -> Accuracy: 0.4898, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.69039 | val 0.69428
  Epoch 013 - train 0.67628 | val 0.74314
  Classification -> best τ=0.475 (val F1=0.2955)
  Directional -> Accuracy: 0.4648, MCC: 0.1149, F1: 0.5870

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 11). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.67019 | val 1.38324
  Epoch 011 - train 0.67563 | val 1.50058
  Classification -> best τ=0.650 (val F1=0.2092)
  Directional -> Accuracy: 0.4130, MCC: 0.0000, F1: 0.5846

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.68500 | val 0.87066
  Epoch 020 - train 0.72898 | val 0.95480
  Epoch 023 - train 0.66045 | val 0.76960
  Classification -> best τ=0.530 (val F1=0.3303)
  Directional -> Accuracy: 0.6429, MCC: 0.2942, F1: 0.5946

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for proper time series validation for BRK-A. Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for proper time series validation for BSAC. Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.68368 | val 0.70567
  Epoch 011 - train 0.66167 | val 0.77387
  Classification -> best τ=0.455 (val F1=0.1710)
  Directional -> Accuracy: 0.4789, MCC: -0.0124, F1: 0.5067

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.72248 | val 0.75362
  Epoch 018 - train 0.62853 | val 0.93551
  Classification -> best τ=0.530 (val F1=0.2355)
  Directional -> Accuracy: 0.5192, MCC: -0.1296, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.71120 | val 0.75333
  Epoch 020 - train 0.66274 | val 0.79152
  Epoch 023 - train 0.69054 | val 0.76032
  Classification -> best τ=0.670 (val F1=0.2862)
  Directional -> Accuracy: 0.6949, MCC: 0.3919, F1: 0.7188

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.67517 | val 1.11864
  Epoch 013 - train 0.60374 | val 0.94299
  Classification -> best τ=0.480 (val F1=0.1922)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.71906 | val 0.65044
  Epoch 017 - train 0.68148 | val 0.84628
  Classification -> best τ=0.290 (val F1=0.3843)
  Directional -> Accuracy: 0.5645, MCC: 0.1543, F1: 0.6582

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.65977 | val 1.01756
  Epoch 012 - train 0.61989 | val 1.56508
  Classification -> best τ=0.445 (val F1=0.2280)
  Directional -> Accuracy: 0.5926, MCC: 0.1816, F1: 0.5417

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.73206 | val 0.76578
  Epoch 015 - train 0.68950 | val 0.77751
  Classification -> best τ=0.560 (val F1=0.3506)
  Directional -> Accuracy: 0.5070, MCC: 0.0233, F1: 0.4928

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.69293 | val 1.28673
  Epoch 011 - train 0.68680 | val 1.19907
  Classification -> best τ=0.565 (val F1=0.2095)
  Directional -> Accuracy: 0.4098, MCC: -0.0040, F1: 0.1429

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.67693 | val 1.10559
  Epoch 011 - train 0.67352 | val 0.82199
  Classification -> best τ=0.445 (val F1=0.2507)
  Directional -> Accuracy: 0.5844, MCC: 0.1477, F1: 0.6444

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.65819 | val 0.68291
  Epoch 020 - train 0.61616 | val 0.81628
  Epoch 030 - train 0.61934 | val 0.95783
  Classification -> best τ=0.525 (val F1=0.4009)
  Directional -> Accuracy: 0.4627, MCC: 0.0488, F1: 0.2800

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 11). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.67966 | val 0.67451
  Epoch 020 - train 0.64059 | val 0.75078
  Classification -> best τ=0.490 (val F1=0.2340)
  Directional -> Accuracy: 0.4935, MCC: -0.1046, F1: 0.6355

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.62901 | val 0.69673
  Epoch 020 - train 0.59803 | val 0.69198
  Epoch 022 - train 0.61033 | val 0.65412
  Classification -> best τ=0.590 (val F1=0.3933)
  Directional -> Accuracy: 0.4082, MCC: 0.1572, F1: 0.1212

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.68454 | val 0.73861
  Epoch 011 - train 0.68672 | val 0.81387
  Classification -> best τ=0.525 (val F1=0.1287)
  Directional -> Accuracy: 0.5373, MCC: 0.0994, F1: 0.3673

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.68018 | val 0.77719
  Epoch 018 - train 0.67325 | val 0.86926
  Classification -> best τ=0.855 (val F1=0.2651)
  Directional -> Accuracy: 0.4915, MCC: 0.2312, F1: 0.2105

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.66056 | val 0.78581
  Epoch 011 - train 0.68161 | val 0.69920
  Classification -> best τ=0.530 (val F1=0.1890)
  Directional -> Accuracy: 0.5672, MCC: 0.1535, F1: 0.6133

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.69446 | val 0.72658
  Epoch 012 - train 0.61192 | val 1.00511
  Classification -> best τ=0.550 (val F1=0.4704)
  Directional -> Accuracy: 0.5439, MCC: 0.2218, F1: 0.3810

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.71340 | val 0.70081
  Epoch 017 - train 0.66815 | val 0.85597
  Classification -> best τ=0.445 (val F1=0.3239)
  Directional -> Accuracy: 0.5625, MCC: 0.2977, F1: 0.6441

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.67746 | val 0.79779
  Epoch 011 - train 0.67647 | val 0.82927
  Classification -> best τ=0.580 (val F1=0.1329)
  Directional -> Accuracy: 0.4773, MCC: 0.0322, F1: 0.4103

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.70255 | val 0.71236
  Epoch 015 - train 0.65670 | val 0.77759
  Classification -> best τ=0.385 (val F1=0.3033)
  Directional -> Accuracy: 0.5172, MCC: 0.1923, F1: 0.2632

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.79276 | val 0.88929
  Epoch 014 - train 0.65841 | val 0.68787
  Classification -> best τ=0.525 (val F1=0.3493)
  Directional -> Accuracy: 0.5814, MCC: 0.1819, F1: 0.5500

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.70951 | val 0.72862
  Epoch 012 - train 0.70620 | val 0.78198
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.72692 | val 0.67130
  Epoch 020 - train 0.62464 | val 0.76661
  Epoch 022 - train 0.67564 | val 0.71351
  Classification -> best τ=0.640 (val F1=0.1361)
  Directional -> Accuracy: 0.4667, MCC: -0.0598, F1: 0.4545

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.64221 | val 0.74947
  Epoch 017 - train 0.64013 | val 0.89667
  Classification -> best τ=0.405 (val F1=0.3875)
  Directional -> Accuracy: 0.5192, MCC: 0.0000, F1: 0.6835

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.69384 | val 0.72194
  Epoch 011 - train 0.66881 | val 0.72399
  Classification -> best τ=0.385 (val F1=0.2907)
  Directional -> Accuracy: 0.5405, MCC: 0.1770, F1: 0.4333

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.65837 | val 0.77932
  Epoch 011 - train 0.69947 | val 0.81552
  Classification -> best τ=0.525 (val F1=0.0070)
  Directional -> Accuracy: 0.5000, MCC: -0.0129, F1: 0.4118

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.63914 | val 1.53451
  Epoch 011 - train 0.65887 | val 1.78126
  Classification -> best τ=0.610 (val F1=0.3407)
  Directional -> Accuracy: 0.5778, MCC: 0.1427, F1: 0.4865

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.67794 | val 0.65200
  Epoch 020 - train 0.65676 | val 0.70220
  Classification -> best τ=0.315 (val F1=0.3463)
  Directional -> Accuracy: 0.6618, MCC: 0.3364, F1: 0.6761

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.69417 | val 0.69142
  Epoch 020 - train 0.72310 | val 1.05554
  Epoch 022 - train 0.61654 | val 0.91891
  Classification -> best τ=0.530 (val F1=0.2637)
  Directional -> Accuracy: 0.5909, MCC: 0.2357, F1: 0.4000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.73149 | val 0.78763
  Epoch 011 - train 0.65001 | val 0.75436
  Classification -> best τ=0.565 (val F1=0.2430)
  Directional -> Accuracy: 0.4828, MCC: -0.0207, F1: 0.5161

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.69576 | val 1.41104
  Epoch 011 - train 0.63816 | val 1.12970
  Classification -> best τ=0.465 (val F1=0.2140)
  Directional -> Accuracy: 0.4167, MCC: 0.0000, F1: 0.2632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 11). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.65955 | val 0.69431
  Epoch 017 - train 0.60780 | val 0.73624
  Classification -> best τ=0.340 (val F1=0.3940)
  Directional -> Accuracy: 0.3415, MCC: 0.0000, F1: 0.5091

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.75832 | val 0.72746
  Epoch 011 - train 0.85468 | val 0.73728
  Classification -> best τ=0.525 (val F1=0.3714)
  Directional -> Accuracy: 0.5000, MCC: 0.0187, F1: 0.4118

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 11). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.67938 | val 0.72452
  Epoch 015 - train 0.66992 | val 0.98885
  Classification -> best τ=0.565 (val F1=0.2481)
  Directional -> Accuracy: 0.5455, MCC: 0.2311, F1: 0.1860

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.66321 | val 0.70279
  Epoch 019 - train 0.70154 | val 0.73663
  Classification -> best τ=0.485 (val F1=0.3712)
  Directional -> Accuracy: 0.5833, MCC: 0.1925, F1: 0.6667

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.64371 | val 0.73344
  Epoch 011 - train 0.64492 | val 0.76249
  Classification -> best τ=0.550 (val F1=0.3022)
  Directional -> Accuracy: 0.4130, MCC: -0.1236, F1: 0.0690

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.63821 | val 1.12990
  Epoch 011 - train 0.74721 | val 0.98848
  Classification -> best τ=0.425 (val F1=0.1551)
  Directional -> Accuracy: 0.3659, MCC: 0.0000, F1: 0.5357

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.68173 | val 0.89932
  Epoch 014 - train 0.67467 | val 1.04625
  Classification -> best τ=0.555 (val F1=0.2767)
  Directional -> Accuracy: 0.4561, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.66388 | val 0.89872
  Epoch 016 - train 0.71479 | val 0.80422
  Classification -> best τ=0.595 (val F1=0.4260)
  Directional -> Accuracy: 0.5345, MCC: 0.1371, F1: 0.0690

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.67518 | val 1.11564
  Epoch 011 - train 0.72052 | val 1.20333
  Classification -> best τ=0.465 (val F1=0.1633)
  Directional -> Accuracy: 0.4727, MCC: -0.0556, F1: 0.4912

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.67256 | val 0.95881
  Epoch 012 - train 0.69621 | val 0.79893
  Classification -> best τ=0.480 (val F1=0.0670)
  Directional -> Accuracy: 0.6207, MCC: 0.3516, F1: 0.7317

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.67638 | val 0.93259

[I 2026-02-25 00:10:22,652] Trial 84 finished with value: 0.2714292782935409 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 10, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 32, 'learning_rate': 0.007216955579053403, 'weight_decay': 1.3046281091314287e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.9168066494092724, 'early_stopping_min_delta': 0.0009051513251588778}. Best is trial 32 with value: 0.2908549754956826.

  Epoch 012 - train 0.65990 | val 1.06939
  Classification -> best τ=0.435 (val F1=0.2626)
  Directional -> Accuracy: 0.4762, MCC: 0.0000, F1: 0.6452

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2714292782935409
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 10
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.68626 | val 0.67648
  Epoch 016 - train 0.64614 | val 0.96905
  Classification -> best τ=0.660 (val F1=0.2463)
  Directional -> Accuracy: 0.5513, MCC: 0.0167, F1: 0.0541

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.66302 | val 0.70256
  Epoch 014 - train 0.64792 | val 0.73374
  Classification -> best τ=0.515 (val F1=0.3394)
  Directional -> Accuracy: 0.5957, MCC: 0.2346, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 11). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.68905 | val 0.76617
  Epoch 011 - train 0.66804 | val 0.76701
  Classification -> best τ=0.530 (val F1=0.2010)
  Directional -> Accuracy: 0.4082, MCC: -0.2328, F1: 0.5246

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.68715 | val 0.79210
  Epoch 020 - train 0.65329 | val 0.73112
  Epoch 030 - train 0.62880 | val 1.58019
  Classification -> best τ=0.515 (val F1=0.2386)
  Directional -> Accuracy: 0.5395, MCC: 0.0000, F1: 0.7009

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.65924 | val 0.68010
  Epoch 017 - train 0.56810 | val 0.81188
  Classification -> best τ=0.525 (val F1=0.4125)
  Directional -> Accuracy: 0.6731, MCC: 0.3471, F1: 0.7385

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.59883 | val 0.81501
  Epoch 013 - train 0.58558 | val 0.99326
  Classification -> best τ=0.460 (val F1=0.2522)
  Directional -> Accuracy: 0.4694, MCC: -0.0599, F1: 0.2778

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.71318 | val 0.68545
  Epoch 020 - train 0.69728 | val 0.67606
  Epoch 028 - train 0.67909 | val 0.67623
  Classification -> best τ=0.470 (val F1=0.2892)
  Directional -> Accuracy: 0.3944, MCC: -0.1103, F1: 0.5567

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 11). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.60827 | val 1.28863
  Epoch 011 - train 0.66585 | val 1.33578
  Classification -> best τ=0.590 (val F1=0.2092)
  Directional -> Accuracy: 0.4130, MCC: 0.0000, F1: 0.5846

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.62733 | val 0.80879
  Epoch 011 - train 0.68534 | val 0.77244
  Classification -> best τ=0.495 (val F1=0.3855)
  Directional -> Accuracy: 0.6905, MCC: 0.3520, F1: 0.6061

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for proper time series validation for BRK-A. Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for proper time series validation for BSAC. Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.65761 | val 1.23396
  Epoch 011 - train 0.65769 | val 1.44426
  Classification -> best τ=0.490 (val F1=0.2602)
  Directional -> Accuracy: 0.4930, MCC: -0.0233, F1: 0.4375

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.70417 | val 1.62946
  Epoch 011 - train 0.66574 | val 1.42108
  Classification -> best τ=0.535 (val F1=0.2376)
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.68104 | val 0.71159
  Epoch 011 - train 0.67068 | val 0.70419
  Classification -> best τ=0.560 (val F1=0.0047)
  Directional -> Accuracy: 0.4915, MCC: -0.0103, F1: 0.3478

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.64708 | val 1.46986
  Epoch 013 - train 0.64417 | val 1.07868
  Classification -> best τ=0.410 (val F1=0.1922)
  Directional -> Accuracy: 0.5000, MCC: 0.1992, F1: 0.6452

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.67753 | val 0.91994
  Epoch 015 - train 0.66544 | val 0.83597
  Classification -> best τ=0.320 (val F1=0.3827)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6353

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.64028 | val 0.78832
  Epoch 013 - train 0.61017 | val 1.11725
  Classification -> best τ=0.445 (val F1=0.3787)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.70128 | val 0.72767
  Epoch 011 - train 0.66844 | val 0.69739
  Classification -> best τ=0.485 (val F1=0.1502)
  Directional -> Accuracy: 0.5634, MCC: 0.1397, F1: 0.7048

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.67907 | val 1.08401
  Epoch 013 - train 0.67762 | val 1.14703
  Classification -> best τ=0.640 (val F1=0.2095)
  Directional -> Accuracy: 0.3934, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.65606 | val 0.86364
  Epoch 011 - train 0.66466 | val 1.00274
  Classification -> best τ=0.425 (val F1=0.1480)
  Directional -> Accuracy: 0.5714, MCC: -0.1025, F1: 0.7227

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.68247 | val 0.68161
  Epoch 020 - train 0.63680 | val 0.68558
  Epoch 027 - train 0.61768 | val 0.83897
  Classification -> best τ=0.340 (val F1=0.3687)
  Directional -> Accuracy: 0.4328, MCC: 0.1043, F1: 0.0500

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 11). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.68566 | val 0.68946
  Epoch 020 - train 0.57725 | val 0.71202
  Epoch 022 - train 0.64731 | val 0.68648
  Classification -> best τ=0.580 (val F1=0.2848)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.67203 | val 1.01906
  Epoch 011 - train 0.61720 | val 0.86948
  Classification -> best τ=0.530 (val F1=0.2193)
  Directional -> Accuracy: 0.6327, MCC: 0.0000, F1: 0.7750

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.68937 | val 0.81215
  Epoch 011 - train 0.67305 | val 0.90208
  Classification -> best τ=0.510 (val F1=0.2234)
  Directional -> Accuracy: 0.4478, MCC: -0.1275, F1: 0.1778

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.68061 | val 0.80020
  Epoch 011 - train 0.66429 | val 0.81346
  Classification -> best τ=0.615 (val F1=0.2559)
  Directional -> Accuracy: 0.4746, MCC: 0.1985, F1: 0.1622

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.67749 | val 0.70351
  Epoch 014 - train 0.65978 | val 0.75902
  Classification -> best τ=0.460 (val F1=0.1075)
  Directional -> Accuracy: 0.4627, MCC: -0.0642, F1: 0.6087

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.62482 | val 0.75527
  Epoch 015 - train 0.64146 | val 0.95133
  Classification -> best τ=0.595 (val F1=0.3680)
  Directional -> Accuracy: 0.5439, MCC: 0.1963, F1: 0.4091

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.65623 | val 0.73421
  Epoch 016 - train 0.57945 | val 0.91193
  Classification -> best τ=0.580 (val F1=0.0476)
  Directional -> Accuracy: 0.5000, MCC: 0.2548, F1: 0.6250

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.70916 | val 0.70819
  Epoch 012 - train 0.61631 | val 0.76467
  Classification -> best τ=0.530 (val F1=0.2661)
  Directional -> Accuracy: 0.5682, MCC: 0.0691, F1: 0.6667

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.63856 | val 0.98297
  Epoch 012 - train 0.62643 | val 1.01016
  Classification -> best τ=0.435 (val F1=0.2394)
  Directional -> Accuracy: 0.5345, MCC: 0.1708, F1: 0.3721

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.69839 | val 0.69127
  Epoch 015 - train 0.60915 | val 1.01941
  Classification -> best τ=0.565 (val F1=0.3243)
  Directional -> Accuracy: 0.5581, MCC: 0.1150, F1: 0.5778

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.64862 | val 0.77831
  Epoch 011 - train 0.72322 | val 0.74240
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.69702 | val 0.73022
  Epoch 016 - train 0.73114 | val 0.75287
  Classification -> best τ=0.645 (val F1=0.2390)
  Directional -> Accuracy: 0.5333, MCC: 0.0000, F1: 0.6957

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.64552 | val 0.72266
  Epoch 017 - train 0.61748 | val 0.70898
  Classification -> best τ=0.450 (val F1=0.3189)
  Directional -> Accuracy: 0.5192, MCC: 0.0000, F1: 0.6835

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.69024 | val 0.94570
  Epoch 016 - train 0.66043 | val 1.20492
  Classification -> best τ=0.400 (val F1=0.2849)
  Directional -> Accuracy: 0.5405, MCC: 0.1770, F1: 0.4333

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.66205 | val 0.78178
  Epoch 011 - train 0.74726 | val 0.75030
  Classification -> best τ=0.470 (val F1=0.1918)
  Directional -> Accuracy: 0.5750, MCC: 0.1857, F1: 0.6383

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.67181 | val 1.14456
  Epoch 011 - train 0.66328 | val 1.21507
  Classification -> best τ=0.510 (val F1=0.1954)
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.6364

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.67928 | val 0.71639
  Epoch 017 - train 0.64591 | val 0.69054
  Classification -> best τ=0.330 (val F1=0.3463)
  Directional -> Accuracy: 0.5441, MCC: 0.1514, F1: 0.4918

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.62123 | val 0.69479
  Epoch 016 - train 0.67435 | val 0.74903
  Classification -> best τ=0.500 (val F1=0.2637)
  Directional -> Accuracy: 0.6136, MCC: 0.2624, F1: 0.4848

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.67072 | val 0.70095
  Epoch 014 - train 0.62641 | val 0.78239
  Classification -> best τ=0.455 (val F1=0.2211)
  Directional -> Accuracy: 0.4828, MCC: 0.0043, F1: 0.5833

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.60687 | val 1.31962
  Epoch 015 - train 0.60567 | val 1.70367
  Classification -> best τ=0.335 (val F1=0.1912)
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 11). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.65095 | val 0.70967
  Epoch 016 - train 0.56480 | val 0.71616
  Classification -> best τ=0.365 (val F1=0.2992)
  Directional -> Accuracy: 0.3415, MCC: 0.0000, F1: 0.5091

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.60020 | val 0.82703
  Epoch 012 - train 0.70133 | val 0.87132
  Classification -> best τ=0.520 (val F1=0.2254)
  Directional -> Accuracy: 0.4750, MCC: -0.0453, F1: 0.4615

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 11). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.66862 | val 0.69759
  Epoch 013 - train 0.66498 | val 0.85420
  Classification -> best τ=0.415 (val F1=0.2601)
  Directional -> Accuracy: 0.5065, MCC: 0.0000, F1: 0.6724

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.68915 | val 0.75505
  Epoch 012 - train 0.69285 | val 0.78293
  Classification -> best τ=0.465 (val F1=0.2156)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.65909 | val 0.67183
  Epoch 019 - train 0.55570 | val 1.15486
  Classification -> best τ=0.600 (val F1=0.3022)
  Directional -> Accuracy: 0.5000, MCC: 0.1274, F1: 0.3030

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.71444 | val 0.82501
  Epoch 016 - train 0.62224 | val 1.04723
  Classification -> best τ=0.620 (val F1=0.4478)
  Directional -> Accuracy: 0.3659, MCC: 0.0000, F1: 0.5357

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.66419 | val 0.85409
  Epoch 016 - train 0.65690 | val 1.19455
  Classification -> best τ=0.535 (val F1=0.1979)
  Directional -> Accuracy: 0.4912, MCC: 0.1746, F1: 0.1212

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.67409 | val 1.29182
  Epoch 011 - train 0.66894 | val 1.28396
  Classification -> best τ=0.640 (val F1=0.3167)
  Directional -> Accuracy: 0.5517, MCC: 0.1202, F1: 0.6061

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.66891 | val 0.95742
  Epoch 011 - train 0.64699 | val 1.25153
  Classification -> best τ=0.485 (val F1=0.2590)
  Directional -> Accuracy: 0.4909, MCC: -0.0808, F1: 0.6316

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.70749 | val 0.77382
  Epoch 017 - train 0.66916 | val 0.76772
  Classification -> best τ=0.390 (val F1=0.1807)
  Directional -> Accuracy: 0.5345, MCC: 0.1371, F1: 0.6897

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.67736 | val 0.74803
  Epoch 011 - train 0.67439 | val 0.80751

[I 2026-02-25 00:11:46,997] Trial 85 finished with value: 0.2489935392357719 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 10, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.1, 'dropout': 0.8, 'batch_size': 32, 'learning_rate': 0.0051943156454866074, 'weight_decay': 7.590715725021247e-06, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.9813121007385317, 'early_stopping_min_delta': 0.00028167363189746206}. Best is trial 32 with value: 0.2908549754956826.

  Classification -> best τ=0.520 (val F1=0.2500)
  Directional -> Accuracy: 0.5238, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2489935392357719
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 5
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.65431 | val 0.86181
  Epoch 013 - train 0.61016 | val 0.87414
  Classification -> best τ=0.605 (val F1=0.2346)
  Directional -> Accuracy: 0.5443, MCC: -0.0091, F1: 0.1429

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.65716 | val 0.75873
  Epoch 011 - train 0.66280 | val 0.73286
  Classification -> best τ=0.515 (val F1=0.1193)
  Directional -> Accuracy: 0.6042, MCC: 0.1843, F1: 0.6667

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 6). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.67242 | val 0.93428
  Epoch 012 - train 0.67520 | val 1.29176
  Classification -> best τ=0.525 (val F1=0.1961)
  Directional -> Accuracy: 0.4800, MCC: 0.0401, F1: 0.1875

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.67177 | val 1.09079
  Epoch 011 - train 0.67013 | val 1.20707
  Classification -> best τ=0.480 (val F1=0.1950)
  Directional -> Accuracy: 0.5195, MCC: 0.1979, F1: 0.2449

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.66190 | val 0.62784
  Epoch 020 - train 0.59258 | val 0.85076
  Epoch 021 - train 0.59173 | val 0.76925
  Classification -> best τ=0.585 (val F1=0.4209)
  Directional -> Accuracy: 0.6792, MCC: 0.3581, F1: 0.6909

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.62286 | val 0.83435
  Epoch 011 - train 0.61038 | val 0.79250
  Classification -> best τ=0.485 (val F1=0.1064)
  Directional -> Accuracy: 0.5238, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.68446 | val 0.69748
  Epoch 011 - train 0.66722 | val 0.74860
  Classification -> best τ=0.490 (val F1=0.2028)
  Directional -> Accuracy: 0.4583, MCC: 0.1762, F1: 0.6061

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 6). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.64716 | val 1.03621
  Epoch 011 - train 0.69843 | val 1.05147
  Classification -> best τ=0.565 (val F1=0.3043)
  Directional -> Accuracy: 0.6596, MCC: 0.2660, F1: 0.5000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.65226 | val 0.84649
  Epoch 012 - train 0.63243 | val 0.75858
  Classification -> best τ=0.510 (val F1=0.3015)
  Directional -> Accuracy: 0.5814, MCC: 0.0891, F1: 0.4000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for proper time series validation for BRK-A. Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for proper time series validation for BSAC. Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.68170 | val 0.69544
  Epoch 011 - train 0.62622 | val 0.71497
  Classification -> best τ=0.480 (val F1=0.2683)
  Directional -> Accuracy: 0.4583, MCC: 0.1470, F1: 0.6139

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.68239 | val 0.93764
  Epoch 011 - train 0.64709 | val 0.86989
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.65203 | val 1.46005
  Epoch 011 - train 0.64983 | val 1.29186
  Classification -> best τ=0.485 (val F1=0.1775)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.62203 | val 1.31128
  Epoch 011 - train 0.63776 | val 1.00232
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.6364

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.66813 | val 0.60947
  Epoch 020 - train 0.61094 | val 0.57145
  Epoch 029 - train 0.59883 | val 0.62879
  Classification -> best τ=0.395 (val F1=0.3953)
  Directional -> Accuracy: 0.5397, MCC: 0.1459, F1: 0.6667

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.64207 | val 0.98771
  Epoch 014 - train 0.65048 | val 1.19330
  Classification -> best τ=0.560 (val F1=0.2942)
  Directional -> Accuracy: 0.5091, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.64803 | val 0.74626
  Epoch 013 - train 0.66985 | val 0.77659
  Classification -> best τ=0.565 (val F1=0.2909)
  Directional -> Accuracy: 0.5417, MCC: 0.1348, F1: 0.4407

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.65684 | val 1.32617
  Epoch 011 - train 0.67166 | val 1.23866
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5968, MCC: 0.0000, F1: 0.7475

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.64959 | val 1.14930
  Epoch 011 - train 0.65292 | val 1.09826
  Classification -> best τ=0.480 (val F1=0.0513)
  Directional -> Accuracy: 0.4487, MCC: 0.1361, F1: 0.1887

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.64084 | val 1.21822
  Epoch 011 - train 0.69151 | val 1.50897
  Classification -> best τ=0.545 (val F1=0.2279)
  Directional -> Accuracy: 0.3971, MCC: -0.1460, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 6). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.67602 | val 0.98726
  Epoch 011 - train 0.61848 | val 1.21590
  Classification -> best τ=0.495 (val F1=0.1909)
  Directional -> Accuracy: 0.4156, MCC: -0.1758, F1: 0.4578

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.64277 | val 1.09978
  Epoch 011 - train 0.65071 | val 1.34957
  Classification -> best τ=0.520 (val F1=0.2303)
  Directional -> Accuracy: 0.6400, MCC: 0.1492, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.66480 | val 0.77451
  Epoch 011 - train 0.65329 | val 0.80957
  Classification -> best τ=0.475 (val F1=0.0434)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.65280 | val 0.75206
  Epoch 011 - train 0.64855 | val 0.78718
  Classification -> best τ=0.540 (val F1=0.2763)
  Directional -> Accuracy: 0.5167, MCC: 0.1690, F1: 0.3830

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.62777 | val 0.73153
  Epoch 011 - train 0.65591 | val 1.15182
  Classification -> best τ=0.490 (val F1=0.2259)
  Directional -> Accuracy: 0.5147, MCC: 0.0530, F1: 0.6118

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.63544 | val 0.66515
  Epoch 014 - train 0.63631 | val 0.69011
  Classification -> best τ=0.480 (val F1=0.5016)
  Directional -> Accuracy: 0.5517, MCC: 0.1238, F1: 0.5357

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.61695 | val 0.68589
  Epoch 020 - train 0.56375 | val 0.80113
  Epoch 022 - train 0.58588 | val 0.81330
  Classification -> best τ=0.425 (val F1=0.2749)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.5714

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.61880 | val 0.77945
  Epoch 011 - train 0.62137 | val 0.80173
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6000, MCC: 0.0000, F1: 0.7500

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.68600 | val 0.87116
  Epoch 014 - train 0.61915 | val 0.77185
  Classification -> best τ=0.460 (val F1=0.2775)
  Directional -> Accuracy: 0.5424, MCC: 0.2518, F1: 0.3415

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.73633 | val 0.68590
  Epoch 019 - train 0.54906 | val 0.75525
  Classification -> best τ=0.550 (val F1=0.1677)
  Directional -> Accuracy: 0.6000, MCC: 0.2060, F1: 0.5714

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.68409 | val 0.79820
  Epoch 013 - train 0.63491 | val 0.75893
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.63058 | val 0.66431
  Epoch 020 - train 0.64213 | val 0.70115
  Epoch 022 - train 0.59521 | val 0.72740
  Classification -> best τ=0.560 (val F1=0.2227)
  Directional -> Accuracy: 0.5435, MCC: 0.0000, F1: 0.7042

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.62171 | val 0.63806
  Epoch 020 - train 0.58633 | val 0.99615
  Classification -> best τ=0.420 (val F1=0.3752)
  Directional -> Accuracy: 0.5283, MCC: 0.0707, F1: 0.6667

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.62177 | val 0.80411
  Epoch 015 - train 0.60905 | val 0.79668
  Classification -> best τ=0.470 (val F1=0.3202)
  Directional -> Accuracy: 0.5200, MCC: 0.0898, F1: 0.4545

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.66700 | val 0.70989
  Epoch 011 - train 0.67100 | val 0.73590
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4878, MCC: 0.0000, F1: 0.6557

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.62447 | val 0.88008
  Epoch 011 - train 0.62406 | val 0.85060
  Classification -> best τ=0.515 (val F1=0.1954)
  Directional -> Accuracy: 0.4565, MCC: 0.0000, F1: 0.6269

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.64070 | val 0.77241
  Epoch 011 - train 0.64592 | val 0.76721
  Classification -> best τ=0.445 (val F1=0.2633)
  Directional -> Accuracy: 0.6232, MCC: 0.2076, F1: 0.6977

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.65753 | val 0.69003
  Epoch 018 - train 0.61480 | val 0.69687
  Classification -> best τ=0.395 (val F1=0.2891)
  Directional -> Accuracy: 0.6444, MCC: 0.3143, F1: 0.5789

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.62024 | val 1.36389
  Epoch 012 - train 0.60809 | val 1.66161
  Classification -> best τ=0.495 (val F1=0.2118)
  Directional -> Accuracy: 0.5085, MCC: 0.0400, F1: 0.5797

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.67888 | val 0.87724
  Epoch 011 - train 0.65833 | val 0.91599
  Classification -> best τ=0.525 (val F1=0.2592)
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 6). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.59898 | val 0.66376
  Epoch 020 - train 0.56302 | val 0.67667
  Epoch 024 - train 0.59209 | val 0.74834
  Classification -> best τ=0.475 (val F1=0.4373)
  Directional -> Accuracy: 0.5238, MCC: -0.0347, F1: 0.3333

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.68539 | val 0.79779
  Epoch 011 - train 0.70086 | val 0.81319
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5122, MCC: 0.0000, F1: 0.6774

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 6). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.65353 | val 1.19845
  Epoch 011 - train 0.63004 | val 1.42850
  Classification -> best τ=0.475 (val F1=0.2036)
  Directional -> Accuracy: 0.5195, MCC: 0.0561, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.63648 | val 1.09327
  Epoch 011 - train 0.68007 | val 1.14179
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4898, MCC: 0.0000, F1: 0.6575

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.63859 | val 0.86217
  Epoch 011 - train 0.65173 | val 0.90022
  Classification -> best τ=0.540 (val F1=0.0236)
  Directional -> Accuracy: 0.5106, MCC: 0.0312, F1: 0.5306

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.63984 | val 0.89048
  Epoch 011 - train 0.63719 | val 1.03052
  Classification -> best τ=0.625 (val F1=0.1370)
  Directional -> Accuracy: 0.3810, MCC: 0.1164, F1: 0.5357

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.71489 | val 0.69590
  Epoch 012 - train 0.66738 | val 0.69290
  Classification -> best τ=0.515 (val F1=0.2392)
  Directional -> Accuracy: 0.5690, MCC: 0.1462, F1: 0.5763

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.65618 | val 1.32897
  Epoch 011 - train 0.62036 | val 1.45558
  Classification -> best τ=0.600 (val F1=0.3675)
  Directional -> Accuracy: 0.5763, MCC: 0.1764, F1: 0.6479

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.66672 | val 0.73215
  Epoch 011 - train 0.61902 | val 0.87660
  Classification -> best τ=0.480 (val F1=0.1476)
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.65909 | val 1.32743
  Epoch 011 - train 0.64073 | val 1.34208
  Classification -> best τ=0.495 (val F1=0.1776)
  Directional -> Accuracy: 0.5172, MCC: 0.0000, F1: 0.6818

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.66107 | val 0.73147

[I 2026-02-25 00:12:14,522] Trial 86 finished with value: 0.20191384590768865 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 5, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 32, 'learning_rate': 0.0022195179163718125, 'weight_decay': 1.8622118982057343e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.8294706803781584, 'early_stopping_min_delta': 0.0013337631318796213}. Best is trial 32 with value: 0.2908549754956826.

  Epoch 016 - train 0.64129 | val 0.83904
  Classification -> best τ=0.480 (val F1=0.2509)
  Directional -> Accuracy: 0.5397, MCC: 0.0649, F1: 0.2564

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.20191384590768865
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 10
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.67479 | val 0.78469
  Epoch 016 - train 0.66862 | val 0.93620
  Classification -> best τ=0.570 (val F1=0.2950)
  Directional -> Accuracy: 0.5256, MCC: -0.0376, F1: 0.1778

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.60081 | val 0.68382
  Epoch 020 - train 0.62985 | val 0.71173
  Classification -> best τ=0.510 (val F1=0.2346)
  Directional -> Accuracy: 0.5957, MCC: 0.2051, F1: 0.5957

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 11). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.64866 | val 1.31785
  Epoch 011 - train 0.68378 | val 1.30789
  Classification -> best τ=0.445 (val F1=0.2887)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.67067 | val 0.69585
  Epoch 020 - train 0.67731 | val 1.42687
  Classification -> best τ=0.435 (val F1=0.1535)
  Directional -> Accuracy: 0.5395, MCC: 0.0538, F1: 0.6237

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.64528 | val 0.81970
  Epoch 016 - train 0.56462 | val 1.03537
  Classification -> best τ=0.470 (val F1=0.4040)
  Directional -> Accuracy: 0.7115, MCC: 0.4217, F1: 0.7273

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.56203 | val 1.14402
  Epoch 012 - train 0.52020 | val 1.78030
  Classification -> best τ=0.405 (val F1=0.2522)
  Directional -> Accuracy: 0.4286, MCC: -0.1678, F1: 0.5333

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.67747 | val 0.69110
  Epoch 013 - train 0.70066 | val 0.82801
  Classification -> best τ=0.515 (val F1=0.2685)
  Directional -> Accuracy: 0.4930, MCC: 0.0041, F1: 0.4706

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 11). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.59179 | val 1.93572
  Epoch 011 - train 0.60431 | val 3.02239
  Classification -> best τ=0.670 (val F1=0.0904)
  Directional -> Accuracy: 0.4130, MCC: 0.0000, F1: 0.5846

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.67745 | val 0.70141
  Epoch 011 - train 0.63546 | val 0.79359
  Classification -> best τ=0.485 (val F1=0.4266)
  Directional -> Accuracy: 0.3571, MCC: -0.2172, F1: 0.4000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for proper time series validation for BRK-A. Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for proper time series validation for BSAC. Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.66244 | val 0.77366
  Epoch 012 - train 0.67616 | val 0.85118
  Classification -> best τ=0.445 (val F1=0.1255)
  Directional -> Accuracy: 0.4225, MCC: -0.1009, F1: 0.5287

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.62777 | val 1.14138
  Epoch 011 - train 0.68248 | val 0.84898
  Classification -> best τ=0.605 (val F1=0.0384)
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.66354 | val 0.73383
  Epoch 020 - train 0.65552 | val 0.85714
  Epoch 022 - train 0.62028 | val 0.91183
  Classification -> best τ=0.795 (val F1=0.3548)
  Directional -> Accuracy: 0.7119, MCC: 0.4758, F1: 0.6383

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.65456 | val 1.15748
  Epoch 012 - train 0.65235 | val 1.56317
  Classification -> best τ=0.580 (val F1=0.1762)
  Directional -> Accuracy: 0.4091, MCC: -0.1614, F1: 0.5357

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.66874 | val 0.80030
  Epoch 013 - train 0.65222 | val 1.38556
  Classification -> best τ=0.255 (val F1=0.3536)
  Directional -> Accuracy: 0.5645, MCC: 0.2626, F1: 0.6966

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.61401 | val 0.83949
  Epoch 011 - train 0.70257 | val 1.13150
  Classification -> best τ=0.445 (val F1=0.3365)
  Directional -> Accuracy: 0.5000, MCC: 0.0225, F1: 0.5970

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.67469 | val 0.77440
  Epoch 014 - train 0.63677 | val 0.96886
  Classification -> best τ=0.425 (val F1=0.2103)
  Directional -> Accuracy: 0.5634, MCC: 0.1827, F1: 0.7103

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.66339 | val 1.35750
  Epoch 011 - train 0.65436 | val 1.23501
  Classification -> best τ=0.605 (val F1=0.2095)
  Directional -> Accuracy: 0.3934, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.65224 | val 1.00602
  Epoch 011 - train 0.66323 | val 0.84402
  Classification -> best τ=0.480 (val F1=0.1126)
  Directional -> Accuracy: 0.4286, MCC: -0.2501, F1: 0.5600

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.68487 | val 0.66510
  Epoch 020 - train 0.62833 | val 0.68660
  Classification -> best τ=0.580 (val F1=0.3022)
  Directional -> Accuracy: 0.4627, MCC: 0.0195, F1: 0.3333

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 11). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.64566 | val 0.70426
  Epoch 015 - train 0.61630 | val 1.60207
  Classification -> best τ=0.535 (val F1=0.2611)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.59502 | val 1.98712
  Epoch 011 - train 0.62573 | val 1.90958
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6327, MCC: 0.0000, F1: 0.7750

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.67841 | val 1.11206
  Epoch 011 - train 0.68743 | val 1.36899
  Classification -> best τ=0.450 (val F1=0.1913)
  Directional -> Accuracy: 0.4776, MCC: -0.0427, F1: 0.4262

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.62741 | val 1.20636
  Epoch 015 - train 0.64307 | val 1.06752
  Classification -> best τ=0.520 (val F1=0.2656)
  Directional -> Accuracy: 0.6441, MCC: 0.2841, F1: 0.6769

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.63750 | val 1.12230
  Epoch 011 - train 0.64804 | val 0.80528
  Classification -> best τ=0.405 (val F1=0.0357)
  Directional -> Accuracy: 0.4627, MCC: -0.0696, F1: 0.6170

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.63018 | val 0.90603
  Epoch 015 - train 0.63536 | val 0.99034
  Classification -> best τ=0.500 (val F1=0.5137)
  Directional -> Accuracy: 0.5614, MCC: 0.2277, F1: 0.4444

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.64194 | val 0.79802
  Epoch 011 - train 0.67041 | val 0.80169
  Classification -> best τ=0.560 (val F1=0.2090)
  Directional -> Accuracy: 0.4792, MCC: 0.0812, F1: 0.5763

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.62616 | val 0.90699
  Epoch 020 - train 0.60568 | val 0.98570
  Epoch 030 - train 0.55680 | val 0.96466
  Classification -> best τ=0.515 (val F1=0.3103)
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.7429

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.63812 | val 0.99430
  Epoch 011 - train 0.61065 | val 1.05782
  Classification -> best τ=0.400 (val F1=0.2054)
  Directional -> Accuracy: 0.5517, MCC: 0.2600, F1: 0.3500

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.56825 | val 0.72024
  Epoch 016 - train 0.65763 | val 0.68375
  Classification -> best τ=0.560 (val F1=0.3344)
  Directional -> Accuracy: 0.5349, MCC: 0.1062, F1: 0.4444

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.68052 | val 0.71413
  Epoch 011 - train 0.65998 | val 0.69817
  Classification -> best τ=0.430 (val F1=0.1581)
  Directional -> Accuracy: 0.5556, MCC: 0.1110, F1: 0.6296

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.69129 | val 0.75768
  Epoch 014 - train 0.69561 | val 0.78331
  Classification -> best τ=0.555 (val F1=0.1581)
  Directional -> Accuracy: 0.5333, MCC: 0.0000, F1: 0.6957

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.57830 | val 0.82239
  Epoch 016 - train 0.57363 | val 0.86951
  Classification -> best τ=0.445 (val F1=0.3265)
  Directional -> Accuracy: 0.5192, MCC: 0.0000, F1: 0.6835

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.69866 | val 0.77332
  Epoch 016 - train 0.63858 | val 1.00034
  Classification -> best τ=0.430 (val F1=0.2649)
  Directional -> Accuracy: 0.5676, MCC: 0.2241, F1: 0.4839

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.64064 | val 0.69527
  Epoch 019 - train 0.59194 | val 1.93771
  Classification -> best τ=0.465 (val F1=0.2365)
  Directional -> Accuracy: 0.5250, MCC: 0.1502, F1: 0.6545

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.61618 | val 1.35248
  Epoch 011 - train 0.64568 | val 1.43764
  Classification -> best τ=0.535 (val F1=0.2929)
  Directional -> Accuracy: 0.5333, MCC: 0.0311, F1: 0.2759

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.64079 | val 0.74558
  Epoch 012 - train 0.64091 | val 0.94316
  Classification -> best τ=0.425 (val F1=0.3810)
  Directional -> Accuracy: 0.5735, MCC: 0.1890, F1: 0.5538

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.66254 | val 0.68513
  Epoch 020 - train 0.57839 | val 0.82420
  Epoch 021 - train 0.61472 | val 0.88642
  Classification -> best τ=0.615 (val F1=0.2637)
  Directional -> Accuracy: 0.5227, MCC: 0.0716, F1: 0.2222

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.62415 | val 0.85086
  Epoch 014 - train 0.59738 | val 0.93727
  Classification -> best τ=0.575 (val F1=0.2171)
  Directional -> Accuracy: 0.6552, MCC: 0.3171, F1: 0.5238

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.55538 | val 1.99639
  Epoch 011 - train 0.65226 | val 1.89631
  Classification -> best τ=0.420 (val F1=0.2799)
  Directional -> Accuracy: 0.4375, MCC: -0.0348, F1: 0.4000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 11). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.63236 | val 0.68051
  Epoch 020 - train 0.50701 | val 0.92856
  Classification -> best τ=0.300 (val F1=0.5214)
  Directional -> Accuracy: 0.3415, MCC: 0.0000, F1: 0.5091

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.64426 | val 0.74726
  Epoch 012 - train 0.67399 | val 0.73769
  Classification -> best τ=0.430 (val F1=0.3194)
  Directional -> Accuracy: 0.5750, MCC: 0.1459, F1: 0.6047

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 11). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.65903 | val 0.80598
  Epoch 015 - train 0.66921 | val 0.94959
  Classification -> best τ=0.450 (val F1=0.3062)
  Directional -> Accuracy: 0.5325, MCC: 0.1201, F1: 0.6786

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.64836 | val 0.73854
  Epoch 011 - train 0.63177 | val 0.72034
  Classification -> best τ=0.560 (val F1=0.3180)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.3684

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.72537 | val 0.74142
  Epoch 018 - train 0.63145 | val 1.29994
  Classification -> best τ=0.460 (val F1=0.4171)
  Directional -> Accuracy: 0.5435, MCC: 0.0339, F1: 0.6441

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.65955 | val 1.03956
  Epoch 011 - train 0.60931 | val 1.10656
  Classification -> best τ=0.520 (val F1=0.3880)
  Directional -> Accuracy: 0.4634, MCC: 0.2497, F1: 0.5769

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.65969 | val 0.78956
  Epoch 011 - train 0.63163 | val 0.78181
  Classification -> best τ=0.615 (val F1=0.1596)
  Directional -> Accuracy: 0.4561, MCC: -0.0168, F1: 0.0606

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.67737 | val 1.16436
  Epoch 012 - train 0.67407 | val 1.40075
  Classification -> best τ=0.455 (val F1=0.1858)
  Directional -> Accuracy: 0.5000, MCC: -0.0127, F1: 0.3830

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.64196 | val 1.17548
  Epoch 014 - train 0.68010 | val 1.53162
  Classification -> best τ=0.540 (val F1=0.1650)
  Directional -> Accuracy: 0.5455, MCC: 0.0743, F1: 0.6377

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.66693 | val 1.05253
  Epoch 012 - train 0.64727 | val 1.01828
  Classification -> best τ=0.510 (val F1=0.2945)
  Directional -> Accuracy: 0.5690, MCC: 0.1337, F1: 0.6269

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.63814 | val 1.24060
  Epoch 011 - train 0.64680 | val 1.13070

[I 2026-02-25 00:13:35,618] Trial 87 finished with value: 0.2565079192603433 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 10, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.1, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 0.00786119745858952, 'weight_decay': 5.831480800446945e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.7122955463988432, 'early_stopping_min_delta': 0.0015132472985592534}. Best is trial 32 with value: 0.2908549754956826.

  Classification -> best τ=0.465 (val F1=0.2121)
  Directional -> Accuracy: 0.4762, MCC: 0.0000, F1: 0.6452

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2565079192603433
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.58501 | val 1.00829
  Epoch 011 - train 0.56891 | val 1.13425
  Classification -> best τ=0.380 (val F1=0.1294)
  Directional -> Accuracy: 0.4474, MCC: 0.0000, F1: 0.6182

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.50270 | val 1.02724
  Epoch 013 - train 0.49447 | val 0.91189
  Classification -> best τ=0.450 (val F1=0.1710)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.50259 | val 0.79436
  Epoch 012 - train 0.50989 | val 0.70723
  Classification -> best τ=0.495 (val F1=0.2784)
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.59684 | val 3.34825
  Epoch 011 - train 0.64688 | val 1.30785
  Classification -> best τ=0.385 (val F1=0.1868)
  Directional -> Accuracy: 0.4267, MCC: -0.1192, F1: 0.1224

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.46900 | val 0.99623
  Epoch 017 - train 0.42533 | val 1.01277
  Classification -> best τ=0.545 (val F1=0.4020)
  Directional -> Accuracy: 0.4706, MCC: -0.2357, F1: 0.6400

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.47904 | val 0.95460
  Epoch 014 - train 0.32462 | val 2.26414
  Classification -> best τ=0.600 (val F1=0.2357)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.58812 | val 0.89561
  Epoch 013 - train 0.55572 | val 1.07411
  Classification -> best τ=0.405 (val F1=0.2384)
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.35333 | val 0.85997
  Epoch 015 - train 0.36284 | val 1.12694
  Classification -> best τ=0.350 (val F1=0.1752)
  Directional -> Accuracy: 0.4186, MCC: -0.0528, F1: 0.5614

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.48404 | val 1.14912
  Epoch 014 - train 0.38950 | val 1.49950
  Classification -> best τ=0.390 (val F1=0.1978)
  Directional -> Accuracy: 0.5714, MCC: 0.1599, F1: 0.0870

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.49860 | val 1.01465
  Epoch 011 - train 0.52817 | val 1.43484
  Classification -> best τ=0.515 (val F1=0.2012)
  Directional -> Accuracy: 0.4857, MCC: 0.0000, F1: 0.5000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.54074 | val 2.26877
  Epoch 013 - train 0.45102 | val 2.49542
  Classification -> best τ=0.535 (val F1=0.2500)
  Directional -> Accuracy: 0.6200, MCC: 0.2766, F1: 0.3448

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.59915 | val 1.31865
  Epoch 014 - train 0.51983 | val 1.62755
  Classification -> best τ=0.280 (val F1=0.2594)
  Directional -> Accuracy: 0.5517, MCC: 0.1429, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.45626 | val 1.33082
  Epoch 015 - train 0.39455 | val 1.54523
  Classification -> best τ=0.420 (val F1=0.1908)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.57124 | val 0.96564
  Epoch 015 - train 0.51611 | val 1.28712
  Classification -> best τ=0.610 (val F1=0.3320)
  Directional -> Accuracy: 0.5667, MCC: 0.1383, F1: 0.6176

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.48891 | val 0.97178
  Epoch 011 - train 0.44570 | val 1.84252
  Classification -> best τ=0.500 (val F1=0.2629)
  Directional -> Accuracy: 0.5192, MCC: 0.0786, F1: 0.5902

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.56121 | val 1.01812
  Epoch 012 - train 0.51028 | val 0.96736
  Classification -> best τ=0.445 (val F1=0.2500)
  Directional -> Accuracy: 0.5652, MCC: 0.1125, F1: 0.6875

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.58232 | val 3.60984
  Epoch 011 - train 0.61655 | val 4.32344
  Classification -> best τ=0.425 (val F1=0.0811)
  Directional -> Accuracy: 0.5424, MCC: -0.0717, F1: 0.6747

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.60597 | val 1.39363
  Epoch 015 - train 0.56980 | val 1.33317
  Classification -> best τ=0.435 (val F1=0.2137)
  Directional -> Accuracy: 0.5333, MCC: 0.0332, F1: 0.6067

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.56937 | val 3.29137
  Epoch 012 - train 0.56781 | val 2.48575
  Classification -> best τ=0.525 (val F1=0.2868)
  Directional -> Accuracy: 0.5385, MCC: 0.2138, F1: 0.4231

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.61864 | val 1.32069
  Epoch 015 - train 0.54570 | val 0.91873
  Classification -> best τ=0.545 (val F1=0.3544)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.51501 | val 0.94548
  Epoch 014 - train 0.47310 | val 2.27031
  Classification -> best τ=0.585 (val F1=0.3287)
  Directional -> Accuracy: 0.4043, MCC: 0.1162, F1: 0.0667

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.62617 | val 1.04788
  Epoch 016 - train 0.51050 | val 1.58233
  Classification -> best τ=0.595 (val F1=0.2975)
  Directional -> Accuracy: 0.4697, MCC: -0.0643, F1: 0.3636

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.58096 | val 1.51489
  Epoch 012 - train 0.54938 | val 1.85963
  Classification -> best τ=0.660 (val F1=0.2864)
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.57903 | val 1.39075
  Epoch 011 - train 0.57140 | val 1.01297
  Classification -> best τ=0.525 (val F1=0.0348)
  Directional -> Accuracy: 0.4769, MCC: -0.0455, F1: 0.4688

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.49314 | val 0.78721
  Epoch 011 - train 0.50519 | val 0.88608
  Classification -> best τ=0.460 (val F1=0.3730)
  Directional -> Accuracy: 0.4643, MCC: -0.0081, F1: 0.2857

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.37701 | val 0.80875
  Epoch 011 - train 0.39311 | val 0.89898
  Classification -> best τ=0.535 (val F1=0.1251)
  Directional -> Accuracy: 0.5652, MCC: 0.0406, F1: 0.1667

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.53366 | val 1.15806
  Epoch 011 - train 0.49683 | val 0.89176
  Classification -> best τ=0.455 (val F1=0.1132)
  Directional -> Accuracy: 0.5714, MCC: 0.1250, F1: 0.6250

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.53764 | val 0.91790
  Epoch 011 - train 0.53395 | val 1.02480
  Classification -> best τ=0.475 (val F1=0.1264)
  Directional -> Accuracy: 0.5263, MCC: -0.0014, F1: 0.6301

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.43284 | val 1.66295
  Epoch 011 - train 0.44598 | val 1.70382
  Classification -> best τ=0.480 (val F1=0.2660)
  Directional -> Accuracy: 0.4878, MCC: -0.0191, F1: 0.4878

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.47970 | val 0.74313
  Epoch 013 - train 0.39871 | val 0.94440
  Classification -> best τ=0.495 (val F1=0.2814)
  Directional -> Accuracy: 0.5581, MCC: 0.1169, F1: 0.5581

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.42580 | val 0.77792
  Epoch 019 - train 0.35101 | val 3.08275
  Classification -> best τ=0.600 (val F1=0.4498)
  Directional -> Accuracy: 0.5116, MCC: 0.0509, F1: 0.4324

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.48212 | val 0.96551
  Epoch 013 - train 0.41717 | val 1.15079
  Classification -> best τ=0.460 (val F1=0.4120)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.56517 | val 1.02966
  Epoch 014 - train 0.54494 | val 0.89459
  Classification -> best τ=0.295 (val F1=0.3346)
  Directional -> Accuracy: 0.5753, MCC: 0.1768, F1: 0.5634

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.37493 | val 1.08857
  Epoch 011 - train 0.36210 | val 1.41692
  Classification -> best τ=0.480 (val F1=0.0594)
  Directional -> Accuracy: 0.5135, MCC: 0.0367, F1: 0.5714

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.49456 | val 1.01629
  Epoch 011 - train 0.47720 | val 1.04851
  Classification -> best τ=0.510 (val F1=0.3012)
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.56726 | val 0.91436
  Epoch 015 - train 0.52043 | val 0.84558
  Classification -> best τ=0.365 (val F1=0.3254)
  Directional -> Accuracy: 0.5455, MCC: 0.1658, F1: 0.4828

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.39436 | val 0.87962
  Epoch 012 - train 0.34323 | val 1.30564
  Classification -> best τ=0.505 (val F1=0.2741)
  Directional -> Accuracy: 0.6667, MCC: 0.3441, F1: 0.6500

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.54344 | val 2.26620
  Epoch 011 - train 0.53023 | val 1.85600
  Classification -> best τ=0.405 (val F1=0.2829)
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.6341

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.42127 | val 1.77518
  Epoch 011 - train 0.37283 | val 0.81291
  Classification -> best τ=0.495 (val F1=0.3749)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.46930 | val 0.81914
  Epoch 016 - train 0.33684 | val 1.15101
  Classification -> best τ=0.450 (val F1=0.4715)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.29979 | val 1.30646
  Epoch 011 - train 0.34579 | val 1.27169
  Classification -> best τ=0.510 (val F1=0.0585)
  Directional -> Accuracy: 0.4595, MCC: 0.0000, F1: 0.0000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.53153 | val 1.65792
  Epoch 014 - train 0.56683 | val 1.61464
  Classification -> best τ=0.510 (val F1=0.2942)
  Directional -> Accuracy: 0.4533, MCC: -0.1397, F1: 0.1633

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.44387 | val 0.76745
  Epoch 012 - train 0.49102 | val 1.08908
  Classification -> best τ=0.440 (val F1=0.2677)
  Directional -> Accuracy: 0.5000, MCC: -0.0547, F1: 0.6462

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.32406 | val 1.25357
  Epoch 011 - train 0.32596 | val 1.23626
  Classification -> best τ=0.500 (val F1=0.0132)
  Directional -> Accuracy: 0.5581, MCC: 0.0728, F1: 0.6545

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.36214 | val 0.66199
  Epoch 014 - train 0.27650 | val 0.83026
  Classification -> best τ=0.490 (val F1=0.6290)
  Directional -> Accuracy: 0.3878, MCC: -0.0687, F1: 0.5312

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.56763 | val 1.41518
  Epoch 011 - train 0.53764 | val 2.04906
  Classification -> best τ=0.495 (val F1=0.1914)
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.50725 | val 1.54663
  Epoch 011 - train 0.58855 | val 1.50614
  Classification -> best τ=0.545 (val F1=0.2157)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.55177 | val 0.78623
  Epoch 019 - train 0.44693 | val 2.34809
  Classification -> best τ=0.535 (val F1=0.3006)
  Directional -> Accuracy: 0.5000, MCC: -0.0719, F1: 0.6582

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.55251 | val 1.43486
  Epoch 011 - train 0.58110 | val 3.30504
  Classification -> best τ=0.445 (val F1=0.0140)
  Directional -> Accuracy: 0.5357, MCC: 0.0675, F1: 0.6667

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.63006 | val 3.51798

[I 2026-02-25 00:15:43,225] Trial 88 finished with value: 0.2496838234255508 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.0, 'dropout': 0.1, 'batch_size': 32, 'learning_rate': 0.004085330968449823, 'weight_decay': 4.8153771597162545e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.80888554712473, 'early_stopping_min_delta': 0.0026392373532709307}. Best is trial 32 with value: 0.2908549754956826.

  Epoch 014 - train 0.55801 | val 3.07872
  Classification -> best τ=0.365 (val F1=0.2847)
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2496838234255508
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 10
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.69027 | val 0.69166
  Epoch 014 - train 0.68310 | val 0.67952
  Classification -> best τ=0.505 (val F1=0.2863)
  Directional -> Accuracy: 0.5128, MCC: -0.0838, F1: 0.1364

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.65024 | val 0.68531
  Epoch 018 - train 0.66697 | val 0.68910
  Classification -> best τ=0.570 (val F1=0.2346)
  Directional -> Accuracy: 0.5957, MCC: 0.1633, F1: 0.6780

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 11). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.68764 | val 0.69440
  Epoch 020 - train 0.69027 | val 0.68111
  Epoch 030 - train 0.65938 | val 0.75125
  Classification -> best τ=0.430 (val F1=0.2907)
  Directional -> Accuracy: 0.4898, MCC: -0.0323, F1: 0.5455

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.68013 | val 0.72785
  Epoch 011 - train 0.68637 | val 0.75712
  Classification -> best τ=0.425 (val F1=0.0601)
  Directional -> Accuracy: 0.5395, MCC: 0.0000, F1: 0.7009

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.65959 | val 0.65566
  Epoch 020 - train 0.62552 | val 0.69025
  Epoch 026 - train 0.63195 | val 0.70444
  Classification -> best τ=0.610 (val F1=0.4567)
  Directional -> Accuracy: 0.6731, MCC: 0.3985, F1: 0.6222

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.63929 | val 0.76362
  Epoch 014 - train 0.69009 | val 0.72077
  Classification -> best τ=0.520 (val F1=0.3341)
  Directional -> Accuracy: 0.4898, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.70726 | val 0.68629
  Epoch 018 - train 0.68643 | val 0.69098
  Classification -> best τ=0.520 (val F1=0.2419)
  Directional -> Accuracy: 0.5634, MCC: 0.0427, F1: 0.3404

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 11). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.69281 | val 1.24013
  Epoch 011 - train 0.58158 | val 1.40294
  Classification -> best τ=0.530 (val F1=0.0255)
  Directional -> Accuracy: 0.4130, MCC: 0.0000, F1: 0.5846

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.69197 | val 0.70824
  Epoch 020 - train 0.68279 | val 0.72294
  Epoch 022 - train 0.68951 | val 0.68705
  Classification -> best τ=0.475 (val F1=0.3786)
  Directional -> Accuracy: 0.5714, MCC: 0.0913, F1: 0.4375

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for proper time series validation for BRK-A. Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for proper time series validation for BSAC. Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.66630 | val 0.71353
  Epoch 014 - train 0.65684 | val 0.75443
  Classification -> best τ=0.460 (val F1=0.2208)
  Directional -> Accuracy: 0.4648, MCC: -0.0010, F1: 0.5581

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.67410 | val 0.81322
  Epoch 011 - train 0.68763 | val 0.82547
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.69681 | val 0.70573
  Epoch 011 - train 0.69347 | val 0.70774
  Classification -> best τ=0.500 (val F1=0.1504)
  Directional -> Accuracy: 0.6610, MCC: 0.3218, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.64881 | val 0.89088
  Epoch 014 - train 0.67110 | val 0.85766
  Classification -> best τ=0.475 (val F1=0.2023)
  Directional -> Accuracy: 0.4773, MCC: 0.0227, F1: 0.5965

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.71574 | val 0.66123
  Epoch 020 - train 0.69051 | val 0.64784
  Epoch 027 - train 0.70018 | val 0.67349
  Classification -> best τ=0.445 (val F1=0.3843)
  Directional -> Accuracy: 0.5323, MCC: 0.0690, F1: 0.6027

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.68960 | val 0.72680
  Epoch 015 - train 0.66820 | val 0.78142
  Classification -> best τ=0.555 (val F1=0.2816)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.69333 | val 0.66018
  Epoch 015 - train 0.69395 | val 0.72211
  Classification -> best τ=0.460 (val F1=0.4151)
  Directional -> Accuracy: 0.6479, MCC: 0.3084, F1: 0.7312

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.68733 | val 0.75654
  Epoch 011 - train 0.67713 | val 0.76880
  Classification -> best τ=0.475 (val F1=0.0300)
  Directional -> Accuracy: 0.4918, MCC: -0.0421, F1: 0.5634

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.68454 | val 0.69863
  Epoch 016 - train 0.68099 | val 0.68907
  Classification -> best τ=0.605 (val F1=0.1936)
  Directional -> Accuracy: 0.3896, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.69196 | val 0.68650
  Epoch 013 - train 0.68958 | val 0.69460
  Classification -> best τ=0.485 (val F1=0.3521)
  Directional -> Accuracy: 0.5522, MCC: -0.0538, F1: 0.7000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 11). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.67331 | val 0.68740
  Epoch 019 - train 0.64438 | val 0.73817
  Classification -> best τ=0.505 (val F1=0.2869)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.71492 | val 0.68820
  Epoch 020 - train 0.66497 | val 0.68145
  Epoch 030 - train 0.65506 | val 0.66054
  Classification -> best τ=0.620 (val F1=0.3233)
  Directional -> Accuracy: 0.4286, MCC: 0.1946, F1: 0.1765

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.67380 | val 0.69412
  Epoch 016 - train 0.69824 | val 0.70261
  Classification -> best τ=0.530 (val F1=0.1817)
  Directional -> Accuracy: 0.5224, MCC: 0.0775, F1: 0.2727

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.68052 | val 0.79137
  Epoch 011 - train 0.68519 | val 0.75624
  Classification -> best τ=0.575 (val F1=0.2352)
  Directional -> Accuracy: 0.5593, MCC: 0.2145, F1: 0.4800

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.68072 | val 0.69577
  Epoch 011 - train 0.66627 | val 0.70535
  Classification -> best τ=0.500 (val F1=0.1890)
  Directional -> Accuracy: 0.5224, MCC: 0.0429, F1: 0.5000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.69251 | val 0.68159
  Epoch 017 - train 0.67711 | val 0.67252
  Classification -> best τ=0.555 (val F1=0.3727)
  Directional -> Accuracy: 0.5614, MCC: 0.1898, F1: 0.4898

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.68030 | val 0.70311
  Epoch 014 - train 0.66910 | val 0.69337
  Classification -> best τ=0.565 (val F1=0.1330)
  Directional -> Accuracy: 0.5833, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.69509 | val 0.69754
  Epoch 011 - train 0.69886 | val 0.71571
  Classification -> best τ=0.515 (val F1=0.0737)
  Directional -> Accuracy: 0.4773, MCC: 0.0322, F1: 0.4103

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.71939 | val 0.68117
  Epoch 018 - train 0.62929 | val 0.77096
  Classification -> best τ=0.395 (val F1=0.2394)
  Directional -> Accuracy: 0.5517, MCC: 0.2036, F1: 0.4091

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.69349 | val 0.69534
  Epoch 018 - train 0.62449 | val 0.69874
  Classification -> best τ=0.535 (val F1=0.2673)
  Directional -> Accuracy: 0.5116, MCC: 0.0604, F1: 0.4000

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.68533 | val 0.71624
  Epoch 013 - train 0.68774 | val 0.72555
  Classification -> best τ=0.525 (val F1=0.3287)
  Directional -> Accuracy: 0.4444, MCC: -0.1425, F1: 0.5614

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.69148 | val 0.63775
  Epoch 018 - train 0.67203 | val 0.66650
  Classification -> best τ=0.655 (val F1=0.1715)
  Directional -> Accuracy: 0.5333, MCC: 0.1336, F1: 0.3636

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.67357 | val 0.65037
  Epoch 018 - train 0.64945 | val 0.70580
  Classification -> best τ=0.380 (val F1=0.3243)
  Directional -> Accuracy: 0.5192, MCC: 0.0000, F1: 0.6835

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.68573 | val 0.67605
  Epoch 019 - train 0.67578 | val 0.69990
  Classification -> best τ=0.560 (val F1=0.2303)
  Directional -> Accuracy: 0.4730, MCC: 0.0446, F1: 0.2909

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.70459 | val 0.69311
  Epoch 011 - train 0.68093 | val 0.70163
  Classification -> best τ=0.505 (val F1=0.1870)
  Directional -> Accuracy: 0.5250, MCC: 0.0453, F1: 0.4865

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.67930 | val 0.76691
  Epoch 011 - train 0.68224 | val 0.77675
  Classification -> best τ=0.500 (val F1=0.2828)
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.6364

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.67949 | val 0.68819
  Epoch 020 - train 0.64596 | val 0.71000
  Epoch 024 - train 0.66313 | val 0.71470
  Classification -> best τ=0.515 (val F1=0.2194)
  Directional -> Accuracy: 0.4265, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.71370 | val 0.72353
  Epoch 011 - train 0.68689 | val 0.72701
  Classification -> best τ=0.495 (val F1=0.1174)
  Directional -> Accuracy: 0.4091, MCC: -0.2169, F1: 0.1875

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.65464 | val 0.75919
  Epoch 011 - train 0.68468 | val 0.73091
  Classification -> best τ=0.480 (val F1=0.1687)
  Directional -> Accuracy: 0.4655, MCC: -0.0581, F1: 0.4918

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.66180 | val 0.79170
  Epoch 012 - train 0.68520 | val 0.83408
  Classification -> best τ=0.480 (val F1=0.3128)
  Directional -> Accuracy: 0.6042, MCC: -0.1130, F1: 0.7532

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 11). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.68537 | val 0.69287
  Epoch 013 - train 0.69510 | val 0.71728
  Classification -> best τ=0.470 (val F1=0.2015)
  Directional -> Accuracy: 0.3415, MCC: 0.0000, F1: 0.5091

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.72500 | val 0.71411
  Epoch 011 - train 0.68380 | val 0.74694
  Classification -> best τ=0.525 (val F1=0.4183)
  Directional -> Accuracy: 0.5250, MCC: 0.0553, F1: 0.5128

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 11). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.70218 | val 0.70923
  Epoch 014 - train 0.68346 | val 0.72354
  Classification -> best τ=0.400 (val F1=0.3142)
  Directional -> Accuracy: 0.5065, MCC: 0.0000, F1: 0.6724

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.68787 | val 0.71117
  Epoch 014 - train 0.66834 | val 0.71975
  Classification -> best τ=0.495 (val F1=0.1755)
  Directional -> Accuracy: 0.5208, MCC: 0.0469, F1: 0.3784

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.66054 | val 1.10959
  Epoch 011 - train 0.65364 | val 1.05598
  Classification -> best τ=0.525 (val F1=0.4359)
  Directional -> Accuracy: 0.4565, MCC: 0.0053, F1: 0.2424

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.68265 | val 0.86393
  Epoch 011 - train 0.69314 | val 0.79028
  Classification -> best τ=0.480 (val F1=0.2448)
  Directional -> Accuracy: 0.3659, MCC: 0.0000, F1: 0.5357

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.70604 | val 0.74686
  Epoch 011 - train 0.67084 | val 0.72362
  Classification -> best τ=0.480 (val F1=0.0574)
  Directional -> Accuracy: 0.3860, MCC: -0.2891, F1: 0.5070

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.67370 | val 0.88120
  Epoch 011 - train 0.65621 | val 0.82308
  Classification -> best τ=0.505 (val F1=0.4664)
  Directional -> Accuracy: 0.5000, MCC: 0.1280, F1: 0.6588

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.67379 | val 0.80083
  Epoch 011 - train 0.67564 | val 0.80131
  Classification -> best τ=0.480 (val F1=0.0499)
  Directional -> Accuracy: 0.4909, MCC: 0.1289, F1: 0.0667

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.73660 | val 0.69595
  Epoch 015 - train 0.68608 | val 0.68993
  Classification -> best τ=0.470 (val F1=0.2435)
  Directional -> Accuracy: 0.5172, MCC: 0.0000, F1: 0.6818

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.71010 | val 0.69488

[I 2026-02-25 00:17:37,982] Trial 89 finished with value: 0.24129991785577268 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 10, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.8, 'batch_size': 32, 'learning_rate': 0.005708015611571461, 'weight_decay': 2.46824002031156e-05, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.6296229162469156, 'early_stopping_min_delta': 0.0018526665316695964}. Best is trial 32 with value: 0.2908549754956826.

  Epoch 017 - train 0.69333 | val 0.70450
  Classification -> best τ=0.495 (val F1=0.2739)
  Directional -> Accuracy: 0.6508, MCC: 0.2982, F1: 0.6071

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.24129991785577268
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.65597 | val 1.11779
  Epoch 015 - train 0.62571 | val 1.17487
  Classification -> best τ=0.560 (val F1=0.2510)
  Directional -> Accuracy: 0.5526, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.68337 | val 1.08163
  Epoch 015 - train 0.61186 | val 0.75881
  Classification -> best τ=0.510 (val F1=0.1812)
  Directional -> Accuracy: 0.6222, MCC: 0.2523, F1: 0.7536

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.62716 | val 0.71689
  Epoch 014 - train 0.64078 | val 0.93827
  Classification -> best τ=0.515 (val F1=0.2064)
  Directional -> Accuracy: 0.4681, MCC: -0.0712, F1: 0.5098

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.64711 | val 1.65879
  Epoch 011 - train 0.64992 | val 1.50743
  Classification -> best τ=0.450 (val F1=0.1961)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.55963 | val 0.69948
  Epoch 019 - train 0.58330 | val 0.75784
  Classification -> best τ=0.610 (val F1=0.4946)
  Directional -> Accuracy: 0.5686, MCC: 0.1633, F1: 0.7027

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.58046 | val 0.75399
  Epoch 011 - train 0.59488 | val 0.80344
  Classification -> best τ=0.515 (val F1=0.2357)
  Directional -> Accuracy: 0.4894, MCC: 0.0000, F1: 0.6571

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.68275 | val 0.77248
  Epoch 012 - train 0.65321 | val 0.83368
  Classification -> best τ=0.510 (val F1=0.2605)
  Directional -> Accuracy: 0.4928, MCC: 0.0335, F1: 0.5070

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.69709 | val 1.34229
  Epoch 015 - train 0.56839 | val 0.99555
  Classification -> best τ=0.435 (val F1=0.0226)
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.58643 | val 0.96842
  Epoch 014 - train 0.62948 | val 1.70779
  Classification -> best τ=0.455 (val F1=0.3301)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.63977 | val 0.81704
  Epoch 011 - train 0.57865 | val 1.23137
  Classification -> best τ=0.430 (val F1=0.2576)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.61735 | val 1.20648
  Epoch 012 - train 0.60715 | val 1.48258
  Classification -> best τ=0.520 (val F1=0.0689)
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.6301

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.62021 | val 1.15480
  Epoch 013 - train 0.58921 | val 1.57449
  Classification -> best τ=0.440 (val F1=0.1469)
  Directional -> Accuracy: 0.5345, MCC: 0.1890, F1: 0.6824

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.63808 | val 1.02726
  Epoch 011 - train 0.63086 | val 0.96151
  Classification -> best τ=0.535 (val F1=0.1239)
  Directional -> Accuracy: 0.5476, MCC: 0.1353, F1: 0.5957

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.67848 | val 0.70022
  Epoch 012 - train 0.63143 | val 0.98176
  Classification -> best τ=0.480 (val F1=0.2667)
  Directional -> Accuracy: 0.5667, MCC: 0.1667, F1: 0.6667

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.66137 | val 2.37093
  Epoch 013 - train 0.56992 | val 1.85741
  Classification -> best τ=0.635 (val F1=0.2160)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.60764 | val 0.86553
  Epoch 015 - train 0.65414 | val 0.83134
  Classification -> best τ=0.285 (val F1=0.3870)
  Directional -> Accuracy: 0.6667, MCC: 0.3554, F1: 0.7473

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.69905 | val 1.75755
  Epoch 011 - train 0.65991 | val 1.65617
  Classification -> best τ=0.435 (val F1=0.0077)
  Directional -> Accuracy: 0.6102, MCC: 0.0975, F1: 0.7229

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.67379 | val 1.16910
  Epoch 012 - train 0.66711 | val 1.68075
  Classification -> best τ=0.540 (val F1=0.1228)
  Directional -> Accuracy: 0.5333, MCC: 0.0546, F1: 0.5882

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.66660 | val 1.66659
  Epoch 012 - train 0.65368 | val 1.85400
  Classification -> best τ=0.430 (val F1=0.3689)
  Directional -> Accuracy: 0.5231, MCC: 0.1299, F1: 0.4561

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.63488 | val 0.63347
  Epoch 020 - train 0.56289 | val 0.82712
  Classification -> best τ=0.440 (val F1=0.4164)
  Directional -> Accuracy: 0.4933, MCC: 0.0890, F1: 0.2400

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.66355 | val 0.99511
  Epoch 017 - train 0.57418 | val 0.69971
  Classification -> best τ=0.280 (val F1=0.3278)
  Directional -> Accuracy: 0.5745, MCC: 0.2287, F1: 0.5652

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.65683 | val 0.96772
  Epoch 013 - train 0.61533 | val 1.03138
  Classification -> best τ=0.500 (val F1=0.2054)
  Directional -> Accuracy: 0.5455, MCC: 0.1325, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.69563 | val 0.70143
  Epoch 020 - train 0.63161 | val 0.96058
  Epoch 021 - train 0.62161 | val 1.11561
  Classification -> best τ=0.760 (val F1=0.3579)
  Directional -> Accuracy: 0.4310, MCC: -0.0557, F1: 0.1951

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.65080 | val 0.74509
  Epoch 015 - train 0.65053 | val 0.88509
  Classification -> best τ=0.475 (val F1=0.1219)
  Directional -> Accuracy: 0.5385, MCC: 0.1166, F1: 0.6250

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.68031 | val 0.66257
  Epoch 018 - train 0.63094 | val 0.75395
  Classification -> best τ=0.630 (val F1=0.5049)
  Directional -> Accuracy: 0.4643, MCC: 0.1211, F1: 0.0625

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.65370 | val 0.79192
  Epoch 011 - train 0.73653 | val 0.78237
  Classification -> best τ=0.510 (val F1=0.2756)
  Directional -> Accuracy: 0.5870, MCC: 0.1700, F1: 0.0952

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.66317 | val 0.69985
  Epoch 020 - train 0.55913 | val 0.86978
  Epoch 028 - train 0.52588 | val 0.82651
  Classification -> best τ=0.315 (val F1=0.1803)
  Directional -> Accuracy: 0.5238, MCC: -0.1936, F1: 0.6875

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.65396 | val 1.03159
  Epoch 012 - train 0.61868 | val 1.04275
  Classification -> best τ=0.595 (val F1=0.2866)
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.60679 | val 0.74608
  Epoch 013 - train 0.64645 | val 1.77560
  Classification -> best τ=0.500 (val F1=0.4109)
  Directional -> Accuracy: 0.5854, MCC: 0.2437, F1: 0.7213

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.62639 | val 0.97923
  Epoch 011 - train 0.54616 | val 1.01542
  Classification -> best τ=0.525 (val F1=0.2814)
  Directional -> Accuracy: 0.5814, MCC: 0.1635, F1: 0.5000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.65467 | val 0.67044
  Epoch 020 - train 0.53217 | val 0.96515
  Epoch 023 - train 0.47619 | val 0.83731
  Classification -> best τ=0.625 (val F1=0.2092)
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.65303 | val 0.90802
  Epoch 013 - train 0.59765 | val 1.16658
  Classification -> best τ=0.415 (val F1=0.3833)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.65627 | val 0.72787
  Epoch 017 - train 0.58858 | val 0.97548
  Classification -> best τ=0.245 (val F1=0.3721)
  Directional -> Accuracy: 0.5753, MCC: 0.1768, F1: 0.5634

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.72556 | val 0.84247
  Epoch 011 - train 0.65323 | val 0.90419
  Classification -> best τ=0.450 (val F1=0.3545)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.67099 | val 0.89004
  Epoch 013 - train 0.61821 | val 1.01784
  Classification -> best τ=0.575 (val F1=0.2503)
  Directional -> Accuracy: 0.5909, MCC: 0.1775, F1: 0.5500

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.66099 | val 0.70619
  Epoch 011 - train 0.63347 | val 0.71988
  Classification -> best τ=0.395 (val F1=0.3525)
  Directional -> Accuracy: 0.6212, MCC: 0.2034, F1: 0.6988

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.60505 | val 0.69786
  Epoch 016 - train 0.49028 | val 1.72383
  Classification -> best τ=0.430 (val F1=0.3443)
  Directional -> Accuracy: 0.6667, MCC: 0.3318, F1: 0.6818

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.65147 | val 1.65524
  Epoch 013 - train 0.57053 | val 1.64859
  Classification -> best τ=0.390 (val F1=0.2868)
  Directional -> Accuracy: 0.4643, MCC: -0.0334, F1: 0.5833

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.62264 | val 0.96994
  Epoch 011 - train 0.55719 | val 1.16707
  Classification -> best τ=0.495 (val F1=0.3954)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.65221 | val 0.71904
  Epoch 020 - train 0.63021 | val 0.68706
  Epoch 030 - train 0.49755 | val 0.63106
  Classification -> best τ=0.350 (val F1=0.6130)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.62943 | val 0.72918
  Epoch 011 - train 0.68057 | val 0.74300
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.62127 | val 1.06779
  Epoch 011 - train 0.61681 | val 1.26299
  Classification -> best τ=0.440 (val F1=0.4117)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.67125 | val 0.70298
  Epoch 015 - train 0.64189 | val 0.96170
  Classification -> best τ=0.440 (val F1=0.3403)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.6857

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.62914 | val 0.83866
  Epoch 011 - train 0.57875 | val 0.89990
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.7164

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.68673 | val 0.69287
  Epoch 014 - train 0.61169 | val 0.94768
  Classification -> best τ=0.500 (val F1=0.6110)
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.63117 | val 1.04912
  Epoch 013 - train 0.70422 | val 1.05272
  Classification -> best τ=0.520 (val F1=0.2077)
  Directional -> Accuracy: 0.5357, MCC: 0.1754, F1: 0.3158

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.64884 | val 1.06692
  Epoch 013 - train 0.61218 | val 0.76573
  Classification -> best τ=0.525 (val F1=0.2553)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.65750 | val 1.45730
  Epoch 011 - train 0.67241 | val 1.46919
  Classification -> best τ=0.555 (val F1=0.1626)
  Directional -> Accuracy: 0.5556, MCC: 0.1310, F1: 0.4783

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.61876 | val 2.60076
  Epoch 011 - train 0.61948 | val 2.62767
  Classification -> best τ=0.495 (val F1=0.0745)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.65422 | val 0.95322

[I 2026-02-25 00:19:55,033] Trial 90 finished with value: 0.2694658255631301 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 0.003417797334337916, 'weight_decay': 1.7514666891834855e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.9174634026362583, 'early_stopping_min_delta': 0.0011245183035544786}. Best is trial 32 with value: 0.2908549754956826.

  Epoch 018 - train 0.60109 | val 0.92929
  Classification -> best τ=0.385 (val F1=0.3349)
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2694658255631301
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 10
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.69626 | val 0.77384
  Epoch 020 - train 0.65507 | val 0.97991
  Epoch 022 - train 0.67195 | val 0.88902
  Classification -> best τ=0.690 (val F1=0.2463)
  Directional -> Accuracy: 0.5256, MCC: -0.0501, F1: 0.1395

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.68253 | val 0.76969
  Epoch 020 - train 0.63840 | val 0.69131
  Epoch 022 - train 0.62436 | val 0.69004
  Classification -> best τ=0.505 (val F1=0.2905)
  Directional -> Accuracy: 0.5745, MCC: 0.1569, F1: 0.5833

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 11). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.69698 | val 0.85784
  Epoch 012 - train 0.67332 | val 0.93274
  Classification -> best τ=0.480 (val F1=0.3447)
  Directional -> Accuracy: 0.5102, MCC: -0.0036, F1: 0.6000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.66671 | val 0.88689
  Epoch 012 - train 0.71032 | val 1.01925
  Classification -> best τ=0.465 (val F1=0.0732)
  Directional -> Accuracy: 0.4868, MCC: -0.1105, F1: 0.6286

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.64190 | val 0.66701
  Epoch 012 - train 0.64621 | val 0.68910
  Classification -> best τ=0.560 (val F1=0.3980)
  Directional -> Accuracy: 0.7692, MCC: 0.5357, F1: 0.7857

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.61553 | val 0.81544
  Epoch 012 - train 0.62507 | val 0.89741
  Classification -> best τ=0.550 (val F1=0.2254)
  Directional -> Accuracy: 0.4898, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.73235 | val 0.69280
  Epoch 013 - train 0.71140 | val 0.69641
  Classification -> best τ=0.545 (val F1=0.2723)
  Directional -> Accuracy: 0.5775, MCC: 0.0983, F1: 0.4231

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 11). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.63114 | val 1.12595
  Epoch 011 - train 0.62694 | val 1.73808
  Classification -> best τ=0.585 (val F1=0.0088)
  Directional -> Accuracy: 0.4130, MCC: 0.0000, F1: 0.5846

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.69539 | val 0.91315
  Epoch 014 - train 0.69010 | val 0.68165
  Classification -> best τ=0.500 (val F1=0.4273)
  Directional -> Accuracy: 0.5714, MCC: 0.0693, F1: 0.4000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for proper time series validation for BRK-A. Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for proper time series validation for BSAC. Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.67907 | val 0.81434
  Epoch 014 - train 0.63032 | val 1.31916
  Classification -> best τ=0.550 (val F1=0.1123)
  Directional -> Accuracy: 0.5634, MCC: 0.0312, F1: 0.1143

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.70600 | val 0.83403
  Epoch 012 - train 0.68770 | val 0.81040
  Classification -> best τ=0.490 (val F1=0.1153)
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.71090 | val 0.70348
  Epoch 012 - train 0.67959 | val 0.71164
  Classification -> best τ=0.540 (val F1=0.1747)
  Directional -> Accuracy: 0.5085, MCC: 0.0354, F1: 0.2927

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.64593 | val 1.19485
  Epoch 015 - train 0.64130 | val 2.02097
  Classification -> best τ=0.570 (val F1=0.3290)
  Directional -> Accuracy: 0.4545, MCC: -0.0760, F1: 0.4783

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.69899 | val 0.62145
  Epoch 020 - train 0.69122 | val 0.61720
  Epoch 022 - train 0.68766 | val 0.67121
  Classification -> best τ=0.300 (val F1=0.3536)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.65259 | val 0.95173
  Epoch 013 - train 0.60531 | val 1.78328
  Classification -> best τ=0.575 (val F1=0.2816)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.66627 | val 0.75263
  Epoch 013 - train 0.67141 | val 0.75148
  Classification -> best τ=0.625 (val F1=0.3854)
  Directional -> Accuracy: 0.5634, MCC: 0.1242, F1: 0.5867

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.67706 | val 1.02180
  Epoch 011 - train 0.66834 | val 1.24788
  Classification -> best τ=0.395 (val F1=0.1253)
  Directional -> Accuracy: 0.5902, MCC: 0.0434, F1: 0.7191

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.69593 | val 0.69464
  Epoch 012 - train 0.69080 | val 0.76016
  Classification -> best τ=0.530 (val F1=0.2308)
  Directional -> Accuracy: 0.4156, MCC: 0.0670, F1: 0.1176

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.65247 | val 0.70110
  Epoch 015 - train 0.63421 | val 0.73011
  Classification -> best τ=0.365 (val F1=0.3266)
  Directional -> Accuracy: 0.5075, MCC: -0.0390, F1: 0.6024

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 11). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.66462 | val 0.77195
  Epoch 012 - train 0.68663 | val 0.70072
  Classification -> best τ=0.470 (val F1=0.3139)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.65479 | val 0.95413
  Epoch 015 - train 0.64649 | val 0.81102
  Classification -> best τ=0.595 (val F1=0.2266)
  Directional -> Accuracy: 0.3673, MCC: -0.0820, F1: 0.1143

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.68684 | val 0.76727
  Epoch 016 - train 0.69486 | val 0.81024
  Classification -> best τ=0.475 (val F1=0.2000)
  Directional -> Accuracy: 0.5373, MCC: 0.1662, F1: 0.2051

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.71400 | val 0.73814
  Epoch 013 - train 0.64618 | val 0.76191
  Classification -> best τ=0.455 (val F1=0.3455)
  Directional -> Accuracy: 0.6780, MCC: 0.3924, F1: 0.7816

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.67721 | val 0.77531
  Epoch 012 - train 0.66417 | val 0.73415
  Classification -> best τ=0.515 (val F1=0.1326)
  Directional -> Accuracy: 0.4478, MCC: -0.1307, F1: 0.3019

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.67381 | val 0.78373
  Epoch 016 - train 0.64672 | val 0.87560
  Classification -> best τ=0.610 (val F1=0.3332)
  Directional -> Accuracy: 0.5439, MCC: 0.1963, F1: 0.4091

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.66839 | val 0.70192
  Epoch 011 - train 0.62491 | val 0.70659
  Classification -> best τ=0.540 (val F1=0.1691)
  Directional -> Accuracy: 0.4583, MCC: 0.0000, F1: 0.5357

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.67632 | val 0.75969
  Epoch 015 - train 0.65731 | val 0.73049
  Classification -> best τ=0.535 (val F1=0.1749)
  Directional -> Accuracy: 0.6364, MCC: 0.2256, F1: 0.7143

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.68782 | val 0.92037
  Epoch 012 - train 0.67228 | val 0.90784
  Classification -> best τ=0.445 (val F1=0.1867)
  Directional -> Accuracy: 0.5690, MCC: 0.2906, F1: 0.3902

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.71470 | val 0.70518
  Epoch 012 - train 0.61742 | val 0.71717
  Classification -> best τ=0.520 (val F1=0.2381)
  Directional -> Accuracy: 0.5349, MCC: 0.0716, F1: 0.5455

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.69107 | val 0.85478
  Epoch 012 - train 0.72088 | val 0.79611
  Classification -> best τ=0.520 (val F1=0.1890)
  Directional -> Accuracy: 0.5778, MCC: 0.1561, F1: 0.5778

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.72611 | val 0.65018
  Epoch 018 - train 0.73639 | val 0.79757
  Classification -> best τ=0.625 (val F1=0.2272)
  Directional -> Accuracy: 0.4667, MCC: -0.1890, F1: 0.6250

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.65632 | val 0.69401
  Epoch 017 - train 0.62186 | val 0.95228
  Classification -> best τ=0.495 (val F1=0.3465)
  Directional -> Accuracy: 0.5192, MCC: 0.0000, F1: 0.6835

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.69312 | val 0.70774
  Epoch 018 - train 0.62450 | val 0.99032
  Classification -> best τ=0.405 (val F1=0.2446)
  Directional -> Accuracy: 0.5135, MCC: 0.1271, F1: 0.3793

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.70779 | val 0.77409
  Epoch 015 - train 0.61808 | val 0.74372
  Classification -> best τ=0.525 (val F1=0.4181)
  Directional -> Accuracy: 0.5000, MCC: 0.1523, F1: 0.6552

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.67892 | val 1.02229
  Epoch 014 - train 0.69232 | val 1.08050
  Classification -> best τ=0.590 (val F1=0.1818)
  Directional -> Accuracy: 0.6000, MCC: 0.2295, F1: 0.6400

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.69271 | val 0.70995
  Epoch 015 - train 0.66733 | val 0.71493
  Classification -> best τ=0.365 (val F1=0.3463)
  Directional -> Accuracy: 0.4853, MCC: 0.1303, F1: 0.2553

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.73024 | val 0.71440
  Epoch 020 - train 0.62243 | val 0.83912
  Epoch 026 - train 0.58717 | val 1.05760
  Classification -> best τ=0.680 (val F1=0.2637)
  Directional -> Accuracy: 0.6591, MCC: 0.3487, F1: 0.5714

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.62328 | val 0.79856
  Epoch 014 - train 0.66199 | val 0.77676
  Classification -> best τ=0.465 (val F1=0.2499)
  Directional -> Accuracy: 0.4138, MCC: -0.1600, F1: 0.4688

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.66056 | val 0.90766
  Epoch 015 - train 0.65184 | val 1.19049
  Classification -> best τ=0.515 (val F1=0.2495)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 11). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.64616 | val 0.69790
  Epoch 016 - train 0.65116 | val 0.87496
  Classification -> best τ=0.335 (val F1=0.6070)
  Directional -> Accuracy: 0.3415, MCC: 0.0000, F1: 0.5091

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.80819 | val 0.85939
  Epoch 011 - train 0.73766 | val 0.81871
  Classification -> best τ=0.510 (val F1=0.2548)
  Directional -> Accuracy: 0.6500, MCC: 0.3114, F1: 0.6316

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 11). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.69250 | val 0.68276
  Epoch 012 - train 0.68415 | val 0.88009
  Classification -> best τ=0.510 (val F1=0.4300)
  Directional -> Accuracy: 0.5195, MCC: 0.0379, F1: 0.5432

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.67286 | val 0.75031
  Epoch 013 - train 0.66552 | val 0.69376
  Classification -> best τ=0.475 (val F1=0.4784)
  Directional -> Accuracy: 0.6042, MCC: 0.2247, F1: 0.6667

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.66103 | val 1.17705
  Epoch 011 - train 0.68350 | val 1.20220
  Classification -> best τ=0.605 (val F1=0.0287)
  Directional -> Accuracy: 0.4130, MCC: -0.1700, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.67710 | val 0.87806
  Epoch 011 - train 0.70300 | val 0.93995
  Classification -> best τ=0.405 (val F1=0.1545)
  Directional -> Accuracy: 0.3659, MCC: 0.0000, F1: 0.5357

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.65454 | val 0.71428
  Epoch 020 - train 0.65526 | val 1.04494
  Epoch 024 - train 0.61401 | val 0.69284
  Classification -> best τ=0.500 (val F1=0.2331)
  Directional -> Accuracy: 0.4386, MCC: -0.2686, F1: 0.6000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.73359 | val 0.96338
  Epoch 011 - train 0.66420 | val 1.22929
  Classification -> best τ=0.535 (val F1=0.3427)
  Directional -> Accuracy: 0.4828, MCC: 0.0000, F1: 0.6512

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.68442 | val 0.95028
  Epoch 015 - train 0.69310 | val 0.90159
  Classification -> best τ=0.395 (val F1=0.2878)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.65532 | val 1.17318
  Epoch 011 - train 0.72492 | val 0.89623
  Classification -> best τ=0.485 (val F1=0.2211)
  Directional -> Accuracy: 0.5172, MCC: 0.0000, F1: 0.6818

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.68525 | val 0.70635
  Epoch 020 - train 0.69152 | val 0.93950
  Epoch 021 - train 0.65155 | val 1.30765

[I 2026-02-25 00:21:20,793] Trial 91 finished with value: 0.2619495964251961 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 10, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 32, 'learning_rate': 0.006977175166461574, 'weight_decay': 1.3071155053148644e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.9188076211507803, 'early_stopping_min_delta': 0.0008959943505451461}. Best is trial 32 with value: 0.2908549754956826.

  Classification -> best τ=0.490 (val F1=0.3011)
  Directional -> Accuracy: 0.5079, MCC: 0.0246, F1: 0.5373

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2619495964251961
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 10
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.69811 | val 0.70667
  Epoch 017 - train 0.67752 | val 0.77808
  Classification -> best τ=0.650 (val F1=0.3222)
  Directional -> Accuracy: 0.5128, MCC: -0.0838, F1: 0.1364

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.69380 | val 0.73736
  Epoch 018 - train 0.65613 | val 0.69213
  Classification -> best τ=0.625 (val F1=0.2346)
  Directional -> Accuracy: 0.4255, MCC: -0.1192, F1: 0.3415

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 11). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.71598 | val 0.83954
  Epoch 011 - train 0.73464 | val 0.87467
  Classification -> best τ=0.400 (val F1=0.4798)
  Directional -> Accuracy: 0.5918, MCC: 0.1875, F1: 0.6970

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.73771 | val 0.72115
  Epoch 013 - train 0.70012 | val 0.83368
  Classification -> best τ=0.425 (val F1=0.2109)
  Directional -> Accuracy: 0.5658, MCC: 0.1180, F1: 0.6207

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.62496 | val 0.75959
  Epoch 012 - train 0.66972 | val 0.74994
  Classification -> best τ=0.470 (val F1=0.3224)
  Directional -> Accuracy: 0.5385, MCC: 0.0468, F1: 0.6364

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.61149 | val 1.37093
  Epoch 011 - train 0.61993 | val 1.35077
  Classification -> best τ=0.515 (val F1=0.3273)
  Directional -> Accuracy: 0.4898, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.68562 | val 0.69256
  Epoch 018 - train 0.73969 | val 0.70064
  Classification -> best τ=0.520 (val F1=0.2673)
  Directional -> Accuracy: 0.5211, MCC: 0.1739, F1: 0.5952

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 11). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.77467 | val 1.56029
  Epoch 011 - train 0.61862 | val 1.71031
  Classification -> best τ=0.615 (val F1=0.0645)
  Directional -> Accuracy: 0.4130, MCC: 0.0000, F1: 0.5846

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.70658 | val 0.67513
  Epoch 020 - train 0.69182 | val 0.71317
  Epoch 030 - train 0.67464 | val 0.69301
  Classification -> best τ=0.525 (val F1=0.3873)
  Directional -> Accuracy: 0.6905, MCC: 0.3520, F1: 0.6061

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for proper time series validation for BRK-A. Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for proper time series validation for BSAC. Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.68570 | val 0.70410
  Epoch 014 - train 0.66234 | val 0.77992
  Classification -> best τ=0.470 (val F1=0.2379)
  Directional -> Accuracy: 0.4930, MCC: 0.0131, F1: 0.5135

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.64949 | val 0.71778
  Epoch 013 - train 0.67214 | val 0.70535
  Classification -> best τ=0.450 (val F1=0.3487)
  Directional -> Accuracy: 0.6538, MCC: 0.3169, F1: 0.5000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.67484 | val 0.94164
  Epoch 014 - train 0.68192 | val 0.84890
  Classification -> best τ=0.675 (val F1=0.3406)
  Directional -> Accuracy: 0.6271, MCC: 0.2620, F1: 0.5926

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.63480 | val 0.95975
  Epoch 011 - train 0.67652 | val 1.41443
  Classification -> best τ=0.500 (val F1=0.1732)
  Directional -> Accuracy: 0.5227, MCC: -0.0392, F1: 0.1600

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.73771 | val 0.63884
  Epoch 011 - train 0.70304 | val 0.64120
  Classification -> best τ=0.420 (val F1=0.3813)
  Directional -> Accuracy: 0.5645, MCC: 0.1307, F1: 0.5263

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.67375 | val 1.21322
  Epoch 012 - train 0.66791 | val 0.90342
  Classification -> best τ=0.410 (val F1=0.2277)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.70319 | val 0.73997
  Epoch 015 - train 0.68654 | val 0.95610
  Classification -> best τ=0.505 (val F1=0.3333)
  Directional -> Accuracy: 0.5493, MCC: 0.0844, F1: 0.6098

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.65592 | val 1.05171
  Epoch 011 - train 0.67738 | val 1.04930
  Classification -> best τ=0.530 (val F1=0.2705)
  Directional -> Accuracy: 0.4098, MCC: -0.1105, F1: 0.3571

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.68315 | val 0.74102
  Epoch 012 - train 0.72628 | val 1.12201
  Classification -> best τ=0.515 (val F1=0.1982)
  Directional -> Accuracy: 0.3896, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.68895 | val 0.71283
  Epoch 014 - train 0.65659 | val 0.75743
  Classification -> best τ=0.485 (val F1=0.3052)
  Directional -> Accuracy: 0.4627, MCC: 0.0331, F1: 0.3077

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 11). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.64996 | val 0.71538
  Epoch 015 - train 0.68275 | val 0.81719
  Classification -> best τ=0.485 (val F1=0.2358)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.65494 | val 0.76285
  Epoch 018 - train 0.69490 | val 0.87482
  Classification -> best τ=0.500 (val F1=0.3426)
  Directional -> Accuracy: 0.4490, MCC: -0.0111, F1: 0.4255

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.70763 | val 0.93203
  Epoch 012 - train 0.69095 | val 0.87681
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5075, MCC: 0.0000, F1: 0.6733

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.70563 | val 0.79531
  Epoch 015 - train 0.68807 | val 0.82679
  Classification -> best τ=0.720 (val F1=0.2904)
  Directional -> Accuracy: 0.4068, MCC: -0.1531, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.70115 | val 0.67787
  Epoch 020 - train 0.60624 | val 8.44520
  Classification -> best τ=0.470 (val F1=0.2439)
  Directional -> Accuracy: 0.5821, MCC: 0.1764, F1: 0.6111

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.65950 | val 0.69603
  Epoch 014 - train 0.67263 | val 0.94547
  Classification -> best τ=0.560 (val F1=0.4027)
  Directional -> Accuracy: 0.5614, MCC: 0.2277, F1: 0.4444

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.67428 | val 0.75109
  Epoch 015 - train 0.68411 | val 0.97113
  Classification -> best τ=0.580 (val F1=0.2249)
  Directional -> Accuracy: 0.4167, MCC: 0.0000, F1: 0.5882

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.67862 | val 0.76374
  Epoch 011 - train 0.71468 | val 0.75893
  Classification -> best τ=0.555 (val F1=0.1283)
  Directional -> Accuracy: 0.6136, MCC: 0.1833, F1: 0.7536

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.64230 | val 0.73490
  Epoch 013 - train 0.71097 | val 0.80727
  Classification -> best τ=0.250 (val F1=0.3100)
  Directional -> Accuracy: 0.5517, MCC: 0.1330, F1: 0.5185

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.63084 | val 0.72113
  Epoch 020 - train 0.62979 | val 0.69087
  Epoch 025 - train 0.55344 | val 0.82623
  Classification -> best τ=0.440 (val F1=0.3118)
  Directional -> Accuracy: 0.5581, MCC: 0.0981, F1: 0.6885

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.68382 | val 0.98636
  Epoch 011 - train 0.68875 | val 0.90091
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.70322 | val 0.67164
  Epoch 016 - train 0.68589 | val 0.75970
  Classification -> best τ=0.640 (val F1=0.1361)
  Directional -> Accuracy: 0.5333, MCC: 0.0000, F1: 0.6957

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.63498 | val 0.70150
  Epoch 018 - train 0.67043 | val 0.76043
  Classification -> best τ=0.400 (val F1=0.3394)
  Directional -> Accuracy: 0.5192, MCC: 0.0000, F1: 0.6835

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.67331 | val 0.68275
  Epoch 020 - train 0.66503 | val 0.74363
  Epoch 025 - train 0.66616 | val 1.04014
  Classification -> best τ=0.475 (val F1=0.3202)
  Directional -> Accuracy: 0.4189, MCC: -0.1341, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.68753 | val 0.72172
  Epoch 011 - train 0.71304 | val 0.69783
  Classification -> best τ=0.520 (val F1=0.1511)
  Directional -> Accuracy: 0.5000, MCC: 0.0330, F1: 0.6000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.68862 | val 1.02545
  Epoch 012 - train 0.63692 | val 1.30327
  Classification -> best τ=0.465 (val F1=0.3883)
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.6364

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.67773 | val 0.70899
  Epoch 014 - train 0.67761 | val 0.72252
  Classification -> best τ=0.415 (val F1=0.3219)
  Directional -> Accuracy: 0.6029, MCC: 0.1997, F1: 0.6400

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.70848 | val 0.70391
  Epoch 019 - train 0.64818 | val 0.77972
  Classification -> best τ=0.545 (val F1=0.2637)
  Directional -> Accuracy: 0.5227, MCC: 0.0467, F1: 0.4615

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.60818 | val 0.90130
  Epoch 011 - train 0.70050 | val 0.81378
  Classification -> best τ=0.490 (val F1=0.2171)
  Directional -> Accuracy: 0.5517, MCC: 0.0825, F1: 0.4091

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.72354 | val 0.95707
  Epoch 011 - train 0.64138 | val 0.98679
  Classification -> best τ=0.425 (val F1=0.1912)
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 11). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.63259 | val 0.65258
  Epoch 019 - train 0.59133 | val 0.77950
  Classification -> best τ=0.330 (val F1=0.4411)
  Directional -> Accuracy: 0.3415, MCC: 0.0000, F1: 0.5091

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.78001 | val 0.78502
  Epoch 012 - train 0.63272 | val 0.75384
  Classification -> best τ=0.465 (val F1=0.3564)
  Directional -> Accuracy: 0.5250, MCC: 0.0682, F1: 0.4571

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 11). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.69699 | val 0.71725
  Epoch 015 - train 0.71061 | val 0.69401
  Classification -> best τ=0.590 (val F1=0.2598)
  Directional -> Accuracy: 0.4935, MCC: -0.0411, F1: 0.6422

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.72986 | val 0.96350
  Epoch 013 - train 0.70185 | val 0.75658
  Classification -> best τ=0.455 (val F1=0.0714)
  Directional -> Accuracy: 0.4375, MCC: -0.1601, F1: 0.5714

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.70495 | val 1.08650
  Epoch 011 - train 0.62724 | val 1.08629
  Classification -> best τ=0.570 (val F1=0.1262)
  Directional -> Accuracy: 0.3913, MCC: -0.2431, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.67536 | val 1.51579
  Epoch 012 - train 0.63754 | val 1.36539
  Classification -> best τ=0.700 (val F1=0.3035)
  Directional -> Accuracy: 0.4878, MCC: 0.0823, F1: 0.5116

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.66883 | val 1.07462
  Epoch 012 - train 0.65383 | val 1.28073
  Classification -> best τ=0.550 (val F1=0.1484)
  Directional -> Accuracy: 0.4737, MCC: -0.1018, F1: 0.5833

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.70373 | val 1.05818
  Epoch 011 - train 0.66365 | val 1.25607
  Classification -> best τ=0.700 (val F1=0.3039)
  Directional -> Accuracy: 0.5345, MCC: 0.1153, F1: 0.6400

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.69943 | val 0.87371
  Epoch 011 - train 0.71655 | val 1.04493
  Classification -> best τ=0.360 (val F1=0.2276)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.68950 | val 0.69399
  Epoch 019 - train 0.66575 | val 0.77524
  Classification -> best τ=0.440 (val F1=0.2085)
  Directional -> Accuracy: 0.4655, MCC: -0.1371, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.72512 | val 0.93476

[I 2026-02-25 00:22:47,629] Trial 92 finished with value: 0.2589645305412843 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 10, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 32, 'learning_rate': 0.007839287208367521, 'weight_decay': 4.33043245510387e-06, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.7775289081685284, 'early_stopping_min_delta': 0.0003583541384258487}. Best is trial 32 with value: 0.2908549754956826.

  Epoch 013 - train 0.67976 | val 1.05993
  Classification -> best τ=0.315 (val F1=0.2492)
  Directional -> Accuracy: 0.4286, MCC: -0.1376, F1: 0.4545

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2589645305412843
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 10
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.66200 | val 0.68569
  Epoch 019 - train 0.67003 | val 0.86055
  Classification -> best τ=0.765 (val F1=0.2463)
  Directional -> Accuracy: 0.5385, MCC: -0.0127, F1: 0.1429

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.67797 | val 0.69957
  Epoch 011 - train 0.65205 | val 0.69613
  Classification -> best τ=0.545 (val F1=0.2346)
  Directional -> Accuracy: 0.5745, MCC: 0.1065, F1: 0.6875

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 11). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.74223 | val 1.09557
  Epoch 011 - train 0.66065 | val 0.95118
  Classification -> best τ=0.525 (val F1=0.3557)
  Directional -> Accuracy: 0.4286, MCC: -0.1701, F1: 0.5172

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.66299 | val 1.08765
  Epoch 013 - train 0.68278 | val 1.26562
  Classification -> best τ=0.500 (val F1=0.1095)
  Directional -> Accuracy: 0.5000, MCC: 0.0692, F1: 0.2963

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.64976 | val 0.65232
  Epoch 019 - train 0.60920 | val 1.13767
  Classification -> best τ=0.570 (val F1=0.4461)
  Directional -> Accuracy: 0.7500, MCC: 0.4959, F1: 0.7719

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.62419 | val 1.10124
  Epoch 013 - train 0.61243 | val 1.58987
  Classification -> best τ=0.505 (val F1=0.2196)
  Directional -> Accuracy: 0.4898, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.70837 | val 0.71146
  Epoch 020 - train 0.67459 | val 0.69454
  Epoch 025 - train 0.65162 | val 0.72719
  Classification -> best τ=0.545 (val F1=0.2099)
  Directional -> Accuracy: 0.4648, MCC: 0.0232, F1: 0.5366

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 11). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.83698 | val 2.21119
  Epoch 011 - train 0.68470 | val 2.36286
  Classification -> best τ=0.515 (val F1=0.1554)
  Directional -> Accuracy: 0.4565, MCC: 0.1788, F1: 0.6032

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.71416 | val 0.68898
  Epoch 020 - train 0.67006 | val 0.69705
  Epoch 030 - train 0.62766 | val 0.63675
  Classification -> best τ=0.530 (val F1=0.4949)
  Directional -> Accuracy: 0.4524, MCC: -0.3508, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for proper time series validation for BRK-A. Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for proper time series validation for BSAC. Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.68493 | val 0.86273
  Epoch 011 - train 0.63110 | val 1.12992
  Classification -> best τ=0.555 (val F1=0.1587)
  Directional -> Accuracy: 0.5070, MCC: -0.0939, F1: 0.1860

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.68180 | val 0.76172
  Epoch 015 - train 0.64852 | val 0.81415
  Classification -> best τ=0.500 (val F1=0.0860)
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.66011 | val 0.75839
  Epoch 012 - train 0.66140 | val 0.93215
  Classification -> best τ=0.495 (val F1=0.1389)
  Directional -> Accuracy: 0.5254, MCC: 0.0811, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.69555 | val 0.99864
  Epoch 013 - train 0.62898 | val 1.01665
  Classification -> best τ=0.425 (val F1=0.2750)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.66174 | val 0.60317
  Epoch 019 - train 0.68902 | val 0.73505
  Classification -> best τ=0.280 (val F1=0.3827)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.74564 | val 0.96275
  Epoch 014 - train 0.66881 | val 1.17208
  Classification -> best τ=0.550 (val F1=0.2816)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.67110 | val 0.83075
  Epoch 014 - train 0.65264 | val 0.77104
  Classification -> best τ=0.550 (val F1=0.3202)
  Directional -> Accuracy: 0.5634, MCC: 0.1084, F1: 0.6437

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.68777 | val 0.90137
  Epoch 011 - train 0.69313 | val 0.97217
  Classification -> best τ=0.535 (val F1=0.1696)
  Directional -> Accuracy: 0.5082, MCC: 0.1482, F1: 0.4231

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.66728 | val 0.77106
  Epoch 014 - train 0.67683 | val 0.91210
  Classification -> best τ=0.415 (val F1=0.1916)
  Directional -> Accuracy: 0.3896, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.67798 | val 0.74144
  Epoch 020 - train 0.62652 | val 0.74801
  Epoch 021 - train 0.61677 | val 0.70474
  Classification -> best τ=0.400 (val F1=0.2982)
  Directional -> Accuracy: 0.4627, MCC: 0.0073, F1: 0.3571

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 11). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.62304 | val 0.69133
  Epoch 017 - train 0.66941 | val 0.70089
  Classification -> best τ=0.570 (val F1=0.2459)
  Directional -> Accuracy: 0.3506, MCC: -0.2859, F1: 0.2857

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.65552 | val 0.76114
  Epoch 017 - train 0.60110 | val 0.82340
  Classification -> best τ=0.580 (val F1=0.3061)
  Directional -> Accuracy: 0.4490, MCC: 0.2272, F1: 0.2286

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.67722 | val 1.02620
  Epoch 011 - train 0.69836 | val 0.97063
  Classification -> best τ=0.555 (val F1=0.1834)
  Directional -> Accuracy: 0.4776, MCC: -0.0497, F1: 0.1860

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.69958 | val 0.72919
  Epoch 014 - train 0.66951 | val 0.86586
  Classification -> best τ=0.580 (val F1=0.2947)
  Directional -> Accuracy: 0.4915, MCC: 0.0467, F1: 0.4231

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.66255 | val 0.79318
  Epoch 011 - train 0.66638 | val 0.73366
  Classification -> best τ=0.460 (val F1=0.1862)
  Directional -> Accuracy: 0.4776, MCC: 0.0000, F1: 0.6465

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.66636 | val 0.69979
  Epoch 012 - train 0.65173 | val 0.73991
  Classification -> best τ=0.525 (val F1=0.4370)
  Directional -> Accuracy: 0.5789, MCC: 0.2579, F1: 0.4783

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.70824 | val 0.89642
  Epoch 013 - train 0.64911 | val 0.98727
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4167, MCC: 0.0000, F1: 0.5882

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.67580 | val 0.71747
  Epoch 020 - train 0.61196 | val 0.71341
  Epoch 021 - train 0.61991 | val 0.70842
  Classification -> best τ=0.540 (val F1=0.2503)
  Directional -> Accuracy: 0.6136, MCC: 0.1833, F1: 0.7536

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.64781 | val 0.71828
  Epoch 012 - train 0.67647 | val 0.75171
  Classification -> best τ=0.410 (val F1=0.3100)
  Directional -> Accuracy: 0.5172, MCC: 0.1361, F1: 0.3333

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.67669 | val 0.69092
  Epoch 019 - train 0.65317 | val 0.97019
  Classification -> best τ=0.585 (val F1=0.2829)
  Directional -> Accuracy: 0.4651, MCC: -0.0486, F1: 0.3784

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.66909 | val 0.75760
  Epoch 012 - train 0.64580 | val 0.77867
  Classification -> best τ=0.550 (val F1=0.0271)
  Directional -> Accuracy: 0.5556, MCC: 0.1330, F1: 0.4444

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.62782 | val 0.75744
  Epoch 011 - train 0.76268 | val 0.75609
  Classification -> best τ=0.580 (val F1=0.1195)
  Directional -> Accuracy: 0.4222, MCC: -0.1476, F1: 0.1875

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.71548 | val 0.67318
  Epoch 016 - train 0.61616 | val 0.71244
  Classification -> best τ=0.520 (val F1=0.2488)
  Directional -> Accuracy: 0.5192, MCC: 0.0000, F1: 0.6835

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.67961 | val 0.69789
  Epoch 016 - train 0.65160 | val 0.74977
  Classification -> best τ=0.575 (val F1=0.2696)
  Directional -> Accuracy: 0.4459, MCC: -0.0187, F1: 0.2264

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.67193 | val 0.74849
  Epoch 014 - train 0.71600 | val 0.82089
  Classification -> best τ=0.460 (val F1=0.3287)
  Directional -> Accuracy: 0.5500, MCC: 0.1746, F1: 0.6538

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.60576 | val 0.94867
  Epoch 011 - train 0.69892 | val 1.00228
  Classification -> best τ=0.515 (val F1=0.2828)
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.6364

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.64431 | val 0.67427
  Epoch 019 - train 0.67138 | val 0.71278
  Classification -> best τ=0.395 (val F1=0.4381)
  Directional -> Accuracy: 0.4706, MCC: 0.0964, F1: 0.2174

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.66669 | val 0.78524
  Epoch 012 - train 0.66039 | val 0.89185
  Classification -> best τ=0.455 (val F1=0.2260)
  Directional -> Accuracy: 0.6591, MCC: 0.3356, F1: 0.5946

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.65276 | val 0.82511
  Epoch 011 - train 0.70063 | val 0.77015
  Classification -> best τ=0.550 (val F1=0.1753)
  Directional -> Accuracy: 0.5690, MCC: 0.1229, F1: 0.4681

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.68964 | val 0.88185
  Epoch 011 - train 0.56694 | val 0.81759
  Classification -> best τ=0.460 (val F1=0.3037)
  Directional -> Accuracy: 0.4167, MCC: 0.0778, F1: 0.1765

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 11). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.74683 | val 0.66442
  Epoch 019 - train 0.59317 | val 0.75640
  Classification -> best τ=0.405 (val F1=0.3647)
  Directional -> Accuracy: 0.3415, MCC: 0.0000, F1: 0.5091

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.85507 | val 0.91085
  Epoch 011 - train 0.68229 | val 0.80597
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5250, MCC: 0.0000, F1: 0.6885

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 11). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.69067 | val 0.71647
  Epoch 014 - train 0.64267 | val 0.82151
  Classification -> best τ=0.485 (val F1=0.2598)
  Directional -> Accuracy: 0.5584, MCC: 0.1299, F1: 0.6531

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.71455 | val 0.77877
  Epoch 011 - train 0.67157 | val 0.80827
  Classification -> best τ=0.500 (val F1=0.2196)
  Directional -> Accuracy: 0.5833, MCC: 0.2236, F1: 0.6875

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.68648 | val 0.98069
  Epoch 011 - train 0.64231 | val 1.03079
  Classification -> best τ=0.590 (val F1=0.4359)
  Directional -> Accuracy: 0.4130, MCC: -0.1700, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.66347 | val 1.03090
  Epoch 011 - train 0.60725 | val 1.14925
  Classification -> best τ=0.515 (val F1=0.0569)
  Directional -> Accuracy: 0.3659, MCC: 0.0000, F1: 0.5357

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.66346 | val 0.79390
  Epoch 014 - train 0.66744 | val 0.81333
  Classification -> best τ=0.555 (val F1=0.1532)
  Directional -> Accuracy: 0.4211, MCC: -0.1621, F1: 0.0571

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.68658 | val 1.07993
  Epoch 011 - train 0.66882 | val 1.07815
  Classification -> best τ=0.570 (val F1=0.2409)
  Directional -> Accuracy: 0.5172, MCC: 0.0270, F1: 0.4400

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.70293 | val 1.28332
  Epoch 014 - train 0.65640 | val 0.99192
  Classification -> best τ=0.310 (val F1=0.0822)
  Directional -> Accuracy: 0.4727, MCC: -0.1727, F1: 0.6329

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.67082 | val 1.31279
  Epoch 012 - train 0.69633 | val 1.22620
  Classification -> best τ=0.605 (val F1=0.2739)
  Directional -> Accuracy: 0.5862, MCC: 0.1692, F1: 0.6364

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.69913 | val 0.73229
  Epoch 011 - train 0.67300 | val 0.78399

[I 2026-02-25 00:24:13,249] Trial 93 finished with value: 0.2408055065991671 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 10, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 32, 'learning_rate': 0.004777134822652057, 'weight_decay': 1.3069339100979087e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.7013104452142869, 'early_stopping_min_delta': 0.0009005123083098778}. Best is trial 32 with value: 0.2908549754956826.

  Classification -> best τ=0.510 (val F1=0.2626)
  Directional -> Accuracy: 0.4762, MCC: 0.0000, F1: 0.6452

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2408055065991671
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 10
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.70824 | val 0.69678
  Epoch 016 - train 0.69840 | val 0.72350
  Classification -> best τ=0.470 (val F1=0.2863)
  Directional -> Accuracy: 0.5000, MCC: -0.0499, F1: 0.3158

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.67234 | val 0.70794
  Epoch 016 - train 0.71135 | val 0.73942
  Classification -> best τ=0.480 (val F1=0.2905)
  Directional -> Accuracy: 0.5957, MCC: 0.1692, F1: 0.7164

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 11). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.73004 | val 0.76682
  Epoch 013 - train 0.70104 | val 0.73430
  Classification -> best τ=0.585 (val F1=0.3043)
  Directional -> Accuracy: 0.4490, MCC: -0.1535, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.69519 | val 0.75044
  Epoch 011 - train 0.68700 | val 0.93370
  Classification -> best τ=0.545 (val F1=0.1917)
  Directional -> Accuracy: 0.5263, MCC: 0.0686, F1: 0.5000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.67927 | val 0.71956
  Epoch 012 - train 0.62898 | val 0.73755
  Classification -> best τ=0.550 (val F1=0.3947)
  Directional -> Accuracy: 0.4423, MCC: -0.0906, F1: 0.1212

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.59519 | val 1.00089
  Epoch 014 - train 0.61025 | val 0.92203
  Classification -> best τ=0.515 (val F1=0.3413)
  Directional -> Accuracy: 0.4898, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.70803 | val 0.69062
  Epoch 020 - train 0.69241 | val 0.68530
  Epoch 030 - train 0.70335 | val 0.69277
  Classification -> best τ=0.590 (val F1=0.2168)
  Directional -> Accuracy: 0.5352, MCC: 0.0330, F1: 0.4211

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 11). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.67689 | val 2.43604
  Epoch 011 - train 0.72608 | val 1.49187
  Classification -> best τ=0.535 (val F1=0.0137)
  Directional -> Accuracy: 0.4130, MCC: 0.0000, F1: 0.5846

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.71844 | val 0.67219
  Epoch 020 - train 0.65648 | val 0.65740
  Epoch 030 - train 0.65151 | val 0.83462
  Classification -> best τ=0.560 (val F1=0.5394)
  Directional -> Accuracy: 0.6190, MCC: 0.2123, F1: 0.5294

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for proper time series validation for BRK-A. Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for proper time series validation for BSAC. Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.67549 | val 0.83208
  Epoch 011 - train 0.64988 | val 1.10152
  Classification -> best τ=0.430 (val F1=0.1015)
  Directional -> Accuracy: 0.4225, MCC: -0.1358, F1: 0.5941

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.67879 | val 0.89714
  Epoch 016 - train 0.66652 | val 1.04129
  Classification -> best τ=0.590 (val F1=0.2430)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.64984 | val 0.74761
  Epoch 020 - train 0.63554 | val 0.83720
  Epoch 025 - train 0.64578 | val 1.15417
  Classification -> best τ=0.625 (val F1=0.2862)
  Directional -> Accuracy: 0.6780, MCC: 0.3769, F1: 0.6275

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.62770 | val 1.29978
  Epoch 013 - train 0.65380 | val 1.36483
  Classification -> best τ=0.415 (val F1=0.2462)
  Directional -> Accuracy: 0.5227, MCC: 0.0415, F1: 0.4878

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.69387 | val 0.65282
  Epoch 020 - train 0.65365 | val 0.66711
  Epoch 028 - train 0.67314 | val 0.62104
  Classification -> best τ=0.190 (val F1=0.3635)
  Directional -> Accuracy: 0.5645, MCC: 0.2182, F1: 0.6897

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.68460 | val 0.90159
  Epoch 015 - train 0.61703 | val 1.21539
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4815, MCC: 0.0000, F1: 0.6500

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.69502 | val 0.85135
  Epoch 011 - train 0.67335 | val 0.71645
  Classification -> best τ=0.545 (val F1=0.4151)
  Directional -> Accuracy: 0.6338, MCC: 0.2712, F1: 0.7174

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.68192 | val 1.15334
  Epoch 011 - train 0.72956 | val 1.01220
  Classification -> best τ=0.590 (val F1=0.1696)
  Directional -> Accuracy: 0.3607, MCC: -0.2286, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.70281 | val 0.91722
  Epoch 013 - train 0.69393 | val 0.84776
  Classification -> best τ=0.470 (val F1=0.1881)
  Directional -> Accuracy: 0.3896, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.67048 | val 0.67152
  Epoch 020 - train 0.67675 | val 0.77879
  Epoch 023 - train 0.65719 | val 0.70697
  Classification -> best τ=0.495 (val F1=0.3126)
  Directional -> Accuracy: 0.4179, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 11). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.67033 | val 0.74151
  Epoch 017 - train 0.64109 | val 0.84784
  Classification -> best τ=0.515 (val F1=0.2594)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.65243 | val 0.87040
  Epoch 016 - train 0.59966 | val 0.94849
  Classification -> best τ=0.500 (val F1=0.3012)
  Directional -> Accuracy: 0.4490, MCC: -0.1002, F1: 0.5091

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.69867 | val 0.71183
  Epoch 014 - train 0.65636 | val 1.15722
  Classification -> best τ=0.625 (val F1=0.2264)
  Directional -> Accuracy: 0.4925, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.64256 | val 0.85096
  Epoch 014 - train 0.64967 | val 0.87256
  Classification -> best τ=0.525 (val F1=0.2626)
  Directional -> Accuracy: 0.6102, MCC: 0.2154, F1: 0.6462

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.68473 | val 0.72423
  Epoch 011 - train 0.65322 | val 0.72112
  Classification -> best τ=0.520 (val F1=0.1804)
  Directional -> Accuracy: 0.4776, MCC: -0.0272, F1: 0.5679

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.65912 | val 0.65915
  Epoch 020 - train 0.59604 | val 1.11116
  Epoch 021 - train 0.64119 | val 0.99788
  Classification -> best τ=0.540 (val F1=0.4748)
  Directional -> Accuracy: 0.5439, MCC: 0.1963, F1: 0.4091

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.65237 | val 0.73738
  Epoch 011 - train 0.72434 | val 0.77587
  Classification -> best τ=0.515 (val F1=0.4622)
  Directional -> Accuracy: 0.4167, MCC: 0.0000, F1: 0.5882

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.65440 | val 0.89642
  Epoch 012 - train 0.67047 | val 0.69230
  Classification -> best τ=0.590 (val F1=0.0538)
  Directional -> Accuracy: 0.4091, MCC: -0.0403, F1: 0.0714

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.67279 | val 0.82682
  Epoch 012 - train 0.62840 | val 1.02402
  Classification -> best τ=0.460 (val F1=0.2811)
  Directional -> Accuracy: 0.4483, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.61098 | val 0.69497
  Epoch 013 - train 0.65883 | val 0.68426
  Classification -> best τ=0.580 (val F1=0.2673)
  Directional -> Accuracy: 0.4651, MCC: -0.0486, F1: 0.3784

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.66433 | val 0.77073
  Epoch 012 - train 0.68625 | val 0.71653
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.71301 | val 0.69566
  Epoch 014 - train 0.71638 | val 0.69537
  Classification -> best τ=0.485 (val F1=0.1706)
  Directional -> Accuracy: 0.5556, MCC: 0.1071, F1: 0.5833

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.66203 | val 0.74612
  Epoch 017 - train 0.63818 | val 0.88457
  Classification -> best τ=0.495 (val F1=0.2488)
  Directional -> Accuracy: 0.5192, MCC: 0.0000, F1: 0.6835

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.69625 | val 0.66183
  Epoch 020 - train 0.68210 | val 0.91660
  Epoch 022 - train 0.65007 | val 1.03784
  Classification -> best τ=0.380 (val F1=0.3761)
  Directional -> Accuracy: 0.5676, MCC: 0.1562, F1: 0.5676

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.60415 | val 0.78260
  Epoch 011 - train 0.61356 | val 0.82605
  Classification -> best τ=0.490 (val F1=0.5903)
  Directional -> Accuracy: 0.5250, MCC: 0.2182, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.67317 | val 1.52225
  Epoch 011 - train 0.64286 | val 1.38799
  Classification -> best τ=0.515 (val F1=0.2421)
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.6364

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.68021 | val 0.67502
  Epoch 020 - train 0.69570 | val 0.70937
  Epoch 021 - train 0.64330 | val 0.70648
  Classification -> best τ=0.220 (val F1=0.3219)
  Directional -> Accuracy: 0.5441, MCC: 0.2432, F1: 0.3922

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.64914 | val 0.67948
  Epoch 019 - train 0.63784 | val 1.11550
  Classification -> best τ=0.555 (val F1=0.2637)
  Directional -> Accuracy: 0.5227, MCC: 0.0716, F1: 0.2222

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.63900 | val 0.71085
  Epoch 012 - train 0.67059 | val 0.75164
  Classification -> best τ=0.355 (val F1=0.1645)
  Directional -> Accuracy: 0.5172, MCC: 0.2180, F1: 0.6585

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.70520 | val 0.99258
  Epoch 011 - train 0.66108 | val 1.20131
  Classification -> best τ=0.600 (val F1=0.1970)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 11). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.67444 | val 0.67197
  Epoch 017 - train 0.57144 | val 0.70088
  Classification -> best τ=0.410 (val F1=0.4856)
  Directional -> Accuracy: 0.3415, MCC: 0.0000, F1: 0.5091

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.68521 | val 0.73478
  Epoch 011 - train 0.83219 | val 0.78097
  Classification -> best τ=0.485 (val F1=0.1917)
  Directional -> Accuracy: 0.5750, MCC: 0.2253, F1: 0.4138

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 11). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.69431 | val 0.75029
  Epoch 017 - train 0.67358 | val 0.96164
  Classification -> best τ=0.495 (val F1=0.5359)
  Directional -> Accuracy: 0.5455, MCC: 0.0911, F1: 0.5455

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.70605 | val 0.81832
  Epoch 014 - train 0.62690 | val 0.82350
  Classification -> best τ=0.480 (val F1=0.2604)
  Directional -> Accuracy: 0.4792, MCC: -0.0420, F1: 0.4444

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.67785 | val 1.00591
  Epoch 011 - train 0.66059 | val 1.13824
  Classification -> best τ=0.625 (val F1=0.3022)
  Directional -> Accuracy: 0.4130, MCC: -0.1700, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.68552 | val 1.39994
  Epoch 011 - train 0.65268 | val 1.35866
  Classification -> best τ=0.475 (val F1=0.2345)
  Directional -> Accuracy: 0.3659, MCC: 0.0000, F1: 0.5357

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.66004 | val 0.79055
  Epoch 011 - train 0.70705 | val 0.91505
  Classification -> best τ=0.465 (val F1=0.0847)
  Directional -> Accuracy: 0.6667, MCC: 0.3362, F1: 0.6780

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.64859 | val 1.15304
  Epoch 013 - train 0.72260 | val 0.85994
  Classification -> best τ=0.630 (val F1=0.3619)
  Directional -> Accuracy: 0.5517, MCC: 0.1418, F1: 0.6389

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.66596 | val 1.22334
  Epoch 012 - train 0.65216 | val 1.06893
  Classification -> best τ=0.460 (val F1=0.1627)
  Directional -> Accuracy: 0.4000, MCC: -0.1976, F1: 0.4000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.67254 | val 1.23221
  Epoch 017 - train 0.67267 | val 1.06540
  Classification -> best τ=0.505 (val F1=0.1089)
  Directional -> Accuracy: 0.5172, MCC: 0.0000, F1: 0.6818

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.67014 | val 0.68308

[I 2026-02-25 00:25:44,277] Trial 94 finished with value: 0.26575088456524126 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 10, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 32, 'learning_rate': 0.006359469410173911, 'weight_decay': 6.868099452082129e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.8836904394216027, 'early_stopping_min_delta': 0.0005891432392772533}. Best is trial 32 with value: 0.2908549754956826.

  Epoch 020 - train 0.71004 | val 1.10432
  Classification -> best τ=0.455 (val F1=0.3108)
  Directional -> Accuracy: 0.5238, MCC: 0.0588, F1: 0.5588

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.26575088456524126
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 10
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.70798 | val 0.67870
  Epoch 012 - train 0.67917 | val 0.80288
  Classification -> best τ=0.400 (val F1=0.2463)
  Directional -> Accuracy: 0.5513, MCC: 0.0772, F1: 0.4444

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.66342 | val 0.73188
  Epoch 016 - train 0.63425 | val 0.78108
  Classification -> best τ=0.480 (val F1=0.3043)
  Directional -> Accuracy: 0.5957, MCC: 0.1860, F1: 0.7246

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 11). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.69906 | val 1.19053
  Epoch 015 - train 0.64832 | val 0.74432
  Classification -> best τ=0.450 (val F1=0.3734)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.65712 | val 0.69921
  Epoch 013 - train 0.66062 | val 0.78089
  Classification -> best τ=0.540 (val F1=0.1674)
  Directional -> Accuracy: 0.5395, MCC: 0.0000, F1: 0.7009

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.61651 | val 0.69573
  Epoch 018 - train 0.58711 | val 0.73780
  Classification -> best τ=0.470 (val F1=0.4040)
  Directional -> Accuracy: 0.7692, MCC: 0.5367, F1: 0.8000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.54990 | val 1.79199
  Epoch 014 - train 0.49159 | val 2.95463
  Classification -> best τ=0.545 (val F1=0.3273)
  Directional -> Accuracy: 0.4898, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.70094 | val 0.74070
  Epoch 019 - train 0.71176 | val 0.73756
  Classification -> best τ=0.585 (val F1=0.3320)
  Directional -> Accuracy: 0.5634, MCC: 0.0203, F1: 0.2791

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 11). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.71540 | val 1.42238
  Epoch 011 - train 0.63351 | val 1.93696
  Classification -> best τ=0.655 (val F1=0.2463)
  Directional -> Accuracy: 0.4130, MCC: 0.0000, F1: 0.5846

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.65750 | val 1.38842
  Epoch 011 - train 0.64276 | val 1.14520
  Classification -> best τ=0.545 (val F1=0.3127)
  Directional -> Accuracy: 0.5238, MCC: -0.0932, F1: 0.2308

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for proper time series validation for BRK-A. Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for proper time series validation for BSAC. Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.64867 | val 0.90263
  Epoch 012 - train 0.64717 | val 0.79220
  Classification -> best τ=0.425 (val F1=0.2785)
  Directional -> Accuracy: 0.4366, MCC: 0.0000, F1: 0.6078

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.65016 | val 1.00058
  Epoch 015 - train 0.58896 | val 0.77122
  Classification -> best τ=0.595 (val F1=0.3006)
  Directional -> Accuracy: 0.6538, MCC: 0.3313, F1: 0.4706

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.69119 | val 0.74059
  Epoch 012 - train 0.69203 | val 0.81825
  Classification -> best τ=0.490 (val F1=0.3204)
  Directional -> Accuracy: 0.5593, MCC: 0.2354, F1: 0.6977

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.64384 | val 1.76840
  Epoch 011 - train 0.62286 | val 1.10855
  Classification -> best τ=0.455 (val F1=0.0295)
  Directional -> Accuracy: 0.3636, MCC: -0.2667, F1: 0.3636

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.68877 | val 0.85202
  Epoch 016 - train 0.69625 | val 0.64472
  Classification -> best τ=0.360 (val F1=0.3481)
  Directional -> Accuracy: 0.5323, MCC: 0.0962, F1: 0.6588

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.69105 | val 1.39182
  Epoch 011 - train 0.66962 | val 1.34140
  Classification -> best τ=0.530 (val F1=0.1459)
  Directional -> Accuracy: 0.4815, MCC: 0.0000, F1: 0.6500

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.66431 | val 0.87878
  Epoch 014 - train 0.63149 | val 0.85785
  Classification -> best τ=0.415 (val F1=0.2455)
  Directional -> Accuracy: 0.5915, MCC: 0.2622, F1: 0.7238

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.65736 | val 1.24549
  Epoch 011 - train 0.69426 | val 0.97851
  Classification -> best τ=0.615 (val F1=0.2095)
  Directional -> Accuracy: 0.3934, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.65653 | val 1.47195
  Epoch 012 - train 0.68635 | val 0.86136
  Classification -> best τ=0.435 (val F1=0.1833)
  Directional -> Accuracy: 0.5584, MCC: 0.1054, F1: 0.6136

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.67497 | val 0.68039
  Epoch 012 - train 0.66372 | val 0.70818
  Classification -> best τ=0.425 (val F1=0.3592)
  Directional -> Accuracy: 0.5224, MCC: -0.0357, F1: 0.6364

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 11). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.67047 | val 0.73428
  Epoch 011 - train 0.65814 | val 0.69591
  Classification -> best τ=0.470 (val F1=0.2309)
  Directional -> Accuracy: 0.4026, MCC: -0.2048, F1: 0.4524

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.61540 | val 0.78180
  Epoch 017 - train 0.64743 | val 1.28314
  Classification -> best τ=0.380 (val F1=0.3104)
  Directional -> Accuracy: 0.4898, MCC: -0.1107, F1: 0.6032

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.67732 | val 1.38970
  Epoch 011 - train 0.73916 | val 1.29548
  Classification -> best τ=0.535 (val F1=0.1833)
  Directional -> Accuracy: 0.5075, MCC: 0.0689, F1: 0.1081

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.67359 | val 0.78561
  Epoch 013 - train 0.68003 | val 0.92476
  Classification -> best τ=0.465 (val F1=0.2256)
  Directional -> Accuracy: 0.5254, MCC: 0.0594, F1: 0.5484

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.64796 | val 0.74456
  Epoch 013 - train 0.62882 | val 1.02840
  Classification -> best τ=0.405 (val F1=0.1142)
  Directional -> Accuracy: 0.4776, MCC: -0.0079, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.59474 | val 0.96983
  Epoch 015 - train 0.55067 | val 1.29924
  Classification -> best τ=0.420 (val F1=0.4845)
  Directional -> Accuracy: 0.5965, MCC: 0.2500, F1: 0.5490

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.55158 | val 0.91922
  Epoch 012 - train 0.59125 | val 1.10413
  Classification -> best τ=0.565 (val F1=0.2563)
  Directional -> Accuracy: 0.5833, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.65289 | val 0.92329
  Epoch 016 - train 0.60864 | val 0.72627
  Classification -> best τ=0.475 (val F1=0.1749)
  Directional -> Accuracy: 0.5909, MCC: 0.0403, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.65741 | val 0.82237
  Epoch 011 - train 0.63004 | val 0.85907
  Classification -> best τ=0.420 (val F1=0.2987)
  Directional -> Accuracy: 0.6207, MCC: 0.2213, F1: 0.6857

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.63404 | val 0.69456
  Epoch 016 - train 0.55426 | val 0.79282
  Classification -> best τ=0.635 (val F1=0.3344)
  Directional -> Accuracy: 0.4884, MCC: 0.0323, F1: 0.2667

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.66887 | val 0.73086
  Epoch 013 - train 0.62348 | val 0.74365
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.66283 | val 0.70566
  Epoch 012 - train 0.64431 | val 0.66700
  Classification -> best τ=0.615 (val F1=0.1581)
  Directional -> Accuracy: 0.5333, MCC: 0.0000, F1: 0.6957

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.65070 | val 0.70640
  Epoch 015 - train 0.57522 | val 1.08635
  Classification -> best τ=0.370 (val F1=0.2958)
  Directional -> Accuracy: 0.5192, MCC: 0.0000, F1: 0.6835

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.69681 | val 0.66629
  Epoch 015 - train 0.69180 | val 0.71855
  Classification -> best τ=0.630 (val F1=0.2678)
  Directional -> Accuracy: 0.4324, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.66058 | val 0.73106
  Epoch 011 - train 0.63971 | val 0.74725
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4750, MCC: 0.0000, F1: 0.6441

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.61743 | val 1.68465
  Epoch 012 - train 0.58560 | val 2.57074
  Classification -> best τ=0.425 (val F1=0.2421)
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.6364

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.64915 | val 0.78775
  Epoch 013 - train 0.60098 | val 0.75723
  Classification -> best τ=0.450 (val F1=0.2146)
  Directional -> Accuracy: 0.4706, MCC: 0.0411, F1: 0.3077

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.60643 | val 0.77181
  Epoch 020 - train 0.58387 | val 0.77027
  Epoch 026 - train 0.57775 | val 1.11538
  Classification -> best τ=0.715 (val F1=0.2637)
  Directional -> Accuracy: 0.5227, MCC: 0.0716, F1: 0.2222

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.61024 | val 0.82602
  Epoch 013 - train 0.63955 | val 0.95794
  Classification -> best τ=0.510 (val F1=0.2413)
  Directional -> Accuracy: 0.5172, MCC: 0.0445, F1: 0.5333

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.62247 | val 0.99333
  Epoch 011 - train 0.64146 | val 1.20013
  Classification -> best τ=0.425 (val F1=0.2441)
  Directional -> Accuracy: 0.4167, MCC: -0.0265, F1: 0.3000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 11). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.54335 | val 0.75949
  Epoch 016 - train 0.64742 | val 0.84272
  Classification -> best τ=0.390 (val F1=0.3468)
  Directional -> Accuracy: 0.3415, MCC: 0.0000, F1: 0.5091

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.66803 | val 0.90047
  Epoch 011 - train 0.67322 | val 0.83123
  Classification -> best τ=0.610 (val F1=0.0510)
  Directional -> Accuracy: 0.4500, MCC: -0.0869, F1: 0.2667

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 11). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.65574 | val 0.80639
  Epoch 013 - train 0.62801 | val 1.26403
  Classification -> best τ=0.530 (val F1=0.3388)
  Directional -> Accuracy: 0.5325, MCC: 0.1201, F1: 0.6786

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.65447 | val 0.69210
  Epoch 019 - train 0.60933 | val 1.08809
  Classification -> best τ=0.535 (val F1=0.3180)
  Directional -> Accuracy: 0.6667, MCC: 0.3333, F1: 0.6667

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.55935 | val 1.10689
  Epoch 011 - train 0.59234 | val 1.21849
  Classification -> best τ=0.570 (val F1=0.0434)
  Directional -> Accuracy: 0.4348, MCC: -0.0510, F1: 0.1875

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.71169 | val 1.01408
  Epoch 011 - train 0.64811 | val 1.11275
  Classification -> best τ=0.615 (val F1=0.4887)
  Directional -> Accuracy: 0.6341, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.66125 | val 0.99939
  Epoch 017 - train 0.65509 | val 0.68164
  Classification -> best τ=0.500 (val F1=0.2492)
  Directional -> Accuracy: 0.5614, MCC: 0.2137, F1: 0.4186

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.69057 | val 1.21966
  Epoch 011 - train 0.68694 | val 1.42517
  Classification -> best τ=0.480 (val F1=0.2908)
  Directional -> Accuracy: 0.4828, MCC: 0.0000, F1: 0.6512

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.66847 | val 1.27336
  Epoch 012 - train 0.67182 | val 1.70877
  Classification -> best τ=0.510 (val F1=0.1722)
  Directional -> Accuracy: 0.4909, MCC: -0.0517, F1: 0.6000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.63832 | val 0.82012
  Epoch 012 - train 0.72731 | val 0.77798
  Classification -> best τ=0.640 (val F1=0.2245)
  Directional -> Accuracy: 0.5517, MCC: 0.1250, F1: 0.6829

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.68876 | val 0.84657
  Epoch 011 - train 0.65880 | val 1.74611

[I 2026-02-25 00:27:04,627] Trial 95 finished with value: 0.24816603798898348 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 10, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 0.008338024662555251, 'weight_decay': 3.275897015464418e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.8032002008212775, 'early_stopping_min_delta': 9.99404088468943e-05}. Best is trial 32 with value: 0.2908549754956826.

  Classification -> best τ=0.520 (val F1=0.2101)
  Directional -> Accuracy: 0.5238, MCC: 0.0725, F1: 0.5946

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.24816603798898348
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 5
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.65701 | val 0.86596
  Epoch 015 - train 0.66085 | val 0.86323
  Classification -> best τ=0.580 (val F1=0.2727)
  Directional -> Accuracy: 0.5823, MCC: 0.1200, F1: 0.3265

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.60765 | val 0.74277
  Epoch 012 - train 0.69288 | val 0.75942
  Classification -> best τ=0.520 (val F1=0.1654)
  Directional -> Accuracy: 0.5625, MCC: 0.0563, F1: 0.6866

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 6). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.73523 | val 0.83565
  Epoch 012 - train 0.62764 | val 0.80553
  Classification -> best τ=0.365 (val F1=0.4199)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.67574 | val 0.78855
  Epoch 013 - train 0.65712 | val 0.69871
  Classification -> best τ=0.480 (val F1=0.2123)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.62691 | val 0.74753
  Epoch 020 - train 0.59463 | val 0.68851
  Epoch 024 - train 0.51635 | val 0.73456
  Classification -> best τ=0.460 (val F1=0.4312)
  Directional -> Accuracy: 0.6604, MCC: 0.3164, F1: 0.7000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.64011 | val 0.98617
  Epoch 011 - train 0.63646 | val 0.91660
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4762, MCC: 0.0000, F1: 0.6452

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.68719 | val 0.71938
  Epoch 016 - train 0.68988 | val 0.70917
  Classification -> best τ=0.385 (val F1=0.2845)
  Directional -> Accuracy: 0.4861, MCC: 0.1038, F1: 0.5843

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 6). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.67578 | val 0.95653
  Epoch 012 - train 0.69412 | val 1.36640
  Classification -> best τ=0.545 (val F1=0.2191)
  Directional -> Accuracy: 0.4043, MCC: 0.0000, F1: 0.5758

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.67811 | val 0.71100
  Epoch 020 - train 0.63480 | val 0.93582
  Epoch 022 - train 0.55542 | val 0.86694
  Classification -> best τ=0.475 (val F1=0.3320)
  Directional -> Accuracy: 0.6279, MCC: 0.1520, F1: 0.2000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for proper time series validation for BRK-A. Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for proper time series validation for BSAC. Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.64569 | val 0.69027
  Epoch 020 - train 0.61451 | val 0.70610
  Epoch 021 - train 0.64258 | val 0.85974
  Classification -> best τ=0.485 (val F1=0.2637)
  Directional -> Accuracy: 0.4722, MCC: -0.0139, F1: 0.5128

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.68684 | val 0.88509
  Epoch 013 - train 0.65252 | val 0.84067
  Classification -> best τ=0.525 (val F1=0.1895)
  Directional -> Accuracy: 0.4423, MCC: -0.1028, F1: 0.4727

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.72093 | val 0.98208
  Epoch 011 - train 0.68821 | val 0.96650
  Classification -> best τ=0.490 (val F1=0.2417)
  Directional -> Accuracy: 0.5333, MCC: 0.1111, F1: 0.2222

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.61691 | val 0.88224
  Epoch 011 - train 0.62466 | val 1.07557
  Classification -> best τ=0.495 (val F1=0.1868)
  Directional -> Accuracy: 0.5111, MCC: 0.0120, F1: 0.4500

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.65638 | val 0.67879
  Epoch 020 - train 0.67474 | val 0.90858
  Epoch 023 - train 0.67667 | val 0.72304
  Classification -> best τ=0.570 (val F1=0.3682)
  Directional -> Accuracy: 0.5397, MCC: 0.0778, F1: 0.4727

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.64928 | val 0.82181
  Epoch 016 - train 0.61888 | val 1.22989
  Classification -> best τ=0.430 (val F1=0.2582)
  Directional -> Accuracy: 0.5091, MCC: 0.0411, F1: 0.6301

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.62571 | val 0.74583
  Epoch 011 - train 0.63984 | val 0.75151
  Classification -> best τ=0.530 (val F1=0.1274)
  Directional -> Accuracy: 0.5139, MCC: 0.0998, F1: 0.3396

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.70323 | val 1.26749
  Epoch 011 - train 0.66930 | val 1.03712
  Classification -> best τ=0.490 (val F1=0.1414)
  Directional -> Accuracy: 0.6129, MCC: 0.1223, F1: 0.7391

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.66250 | val 0.92833
  Epoch 011 - train 0.66398 | val 0.88283
  Classification -> best τ=0.460 (val F1=0.1533)
  Directional -> Accuracy: 0.5256, MCC: 0.2179, F1: 0.4127

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.65703 | val 1.09230
  Epoch 012 - train 0.66549 | val 1.18115
  Classification -> best τ=0.450 (val F1=0.2025)
  Directional -> Accuracy: 0.4118, MCC: -0.0312, F1: 0.0476

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 6). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.64686 | val 0.82768
  Epoch 011 - train 0.65129 | val 0.74771
  Classification -> best τ=0.410 (val F1=0.2039)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.63035 | val 0.72501
  Epoch 015 - train 0.63025 | val 1.13523
  Classification -> best τ=0.460 (val F1=0.3626)
  Directional -> Accuracy: 0.5000, MCC: -0.1211, F1: 0.6269

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.66210 | val 0.74684
  Epoch 011 - train 0.69381 | val 0.74315
  Classification -> best τ=0.590 (val F1=0.1250)
  Directional -> Accuracy: 0.4853, MCC: -0.1222, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.70324 | val 0.72758
  Epoch 011 - train 0.65948 | val 0.77192
  Classification -> best τ=0.605 (val F1=0.2763)
  Directional -> Accuracy: 0.5500, MCC: 0.1251, F1: 0.5574

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.66910 | val 1.09138
  Epoch 013 - train 0.61845 | val 0.70995
  Classification -> best τ=0.610 (val F1=0.1296)
  Directional -> Accuracy: 0.5294, MCC: 0.0584, F1: 0.2000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.66216 | val 0.67973
  Epoch 017 - train 0.60874 | val 0.93164
  Classification -> best τ=0.435 (val F1=0.3935)
  Directional -> Accuracy: 0.5517, MCC: 0.1330, F1: 0.5185

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.75731 | val 0.80351
  Epoch 012 - train 0.65347 | val 0.74514
  Classification -> best τ=0.505 (val F1=0.3021)
  Directional -> Accuracy: 0.6000, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.64854 | val 0.70720
  Epoch 011 - train 0.66320 | val 0.70813
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6000, MCC: 0.0000, F1: 0.7500

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.63391 | val 0.96250
  Epoch 012 - train 0.63645 | val 0.93168
  Classification -> best τ=0.465 (val F1=0.2213)
  Directional -> Accuracy: 0.4915, MCC: 0.0272, F1: 0.4231

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.65549 | val 0.72449
  Epoch 013 - train 0.56852 | val 0.66994
  Classification -> best τ=0.595 (val F1=0.3656)
  Directional -> Accuracy: 0.5556, MCC: 0.1425, F1: 0.4118

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.65414 | val 0.80315
  Epoch 011 - train 0.59066 | val 0.78213
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.71089 | val 0.67082
  Epoch 016 - train 0.66670 | val 0.98096
  Classification -> best τ=0.620 (val F1=0.1084)
  Directional -> Accuracy: 0.5435, MCC: 0.0000, F1: 0.7042

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.63975 | val 0.83635
  Epoch 014 - train 0.65652 | val 0.92109
  Classification -> best τ=0.410 (val F1=0.3592)
  Directional -> Accuracy: 0.5094, MCC: 0.0000, F1: 0.6750

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.67965 | val 0.66996
  Epoch 018 - train 0.63627 | val 0.76773
  Classification -> best τ=0.730 (val F1=0.3898)
  Directional -> Accuracy: 0.4400, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.75104 | val 0.74772
  Epoch 011 - train 0.70927 | val 0.76376
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4878, MCC: 0.0000, F1: 0.6557

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.63273 | val 1.02807
  Epoch 014 - train 0.63343 | val 1.00857
  Classification -> best τ=0.560 (val F1=0.2081)
  Directional -> Accuracy: 0.5652, MCC: 0.1390, F1: 0.5652

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.66126 | val 0.67362
  Epoch 020 - train 0.60673 | val 0.81074
  Classification -> best τ=0.220 (val F1=0.3271)
  Directional -> Accuracy: 0.6667, MCC: 0.3029, F1: 0.7294

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.68475 | val 0.69975
  Epoch 020 - train 0.57666 | val 0.69731
  Epoch 021 - train 0.52325 | val 0.70027
  Classification -> best τ=0.425 (val F1=0.3148)
  Directional -> Accuracy: 0.5778, MCC: 0.2222, F1: 0.3871

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.60114 | val 1.07028
  Epoch 011 - train 0.63128 | val 0.95515
  Classification -> best τ=0.380 (val F1=0.2312)
  Directional -> Accuracy: 0.4746, MCC: 0.0000, F1: 0.6437

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.65015 | val 1.33273
  Epoch 015 - train 0.65327 | val 1.16203
  Classification -> best τ=0.530 (val F1=0.2807)
  Directional -> Accuracy: 0.5714, MCC: 0.0530, F1: 0.6769

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 6). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.77857 | val 0.67651
  Epoch 018 - train 0.54844 | val 0.81525
  Classification -> best τ=0.375 (val F1=0.1994)
  Directional -> Accuracy: 0.3810, MCC: 0.1581, F1: 0.5185

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.83849 | val 0.75110
  Epoch 014 - train 0.65288 | val 0.90175
  Classification -> best τ=0.520 (val F1=0.3851)
  Directional -> Accuracy: 0.5610, MCC: 0.1407, F1: 0.4706

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 6). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.65168 | val 1.01668
  Epoch 011 - train 0.63774 | val 1.24325
  Classification -> best τ=0.510 (val F1=0.1946)
  Directional -> Accuracy: 0.5065, MCC: 0.0000, F1: 0.6724

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.67241 | val 0.77576
  Epoch 013 - train 0.65707 | val 1.32192
  Classification -> best τ=0.585 (val F1=0.1531)
  Directional -> Accuracy: 0.5306, MCC: 0.0617, F1: 0.5306

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.60795 | val 0.98292
  Epoch 011 - train 0.61668 | val 1.01568
  Classification -> best τ=0.535 (val F1=0.1217)
  Directional -> Accuracy: 0.5745, MCC: 0.0000, F1: 0.7297

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.64060 | val 0.99599
  Epoch 012 - train 0.61371 | val 1.00638
  Classification -> best τ=0.595 (val F1=0.1370)
  Directional -> Accuracy: 0.6190, MCC: 0.4440, F1: 0.6522

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.67856 | val 0.72167
  Epoch 014 - train 0.67506 | val 0.69409
  Classification -> best τ=0.495 (val F1=0.2411)
  Directional -> Accuracy: 0.7069, MCC: 0.4242, F1: 0.7119

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.66765 | val 0.97554
  Epoch 012 - train 0.65830 | val 1.10732
  Classification -> best τ=0.555 (val F1=0.4144)
  Directional -> Accuracy: 0.5424, MCC: 0.0851, F1: 0.5424

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.66598 | val 0.98952
  Epoch 011 - train 0.69053 | val 1.14284
  Classification -> best τ=0.460 (val F1=0.0839)
  Directional -> Accuracy: 0.4821, MCC: -0.1353, F1: 0.6329

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.71054 | val 1.22042
  Epoch 018 - train 0.63014 | val 1.57097
  Classification -> best τ=0.385 (val F1=0.2426)
  Directional -> Accuracy: 0.5345, MCC: 0.0860, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.65222 | val 0.69750

[I 2026-02-25 00:28:01,010] Trial 96 finished with value: 0.23160692071833844 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 5, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 32, 'learning_rate': 0.004429240106862244, 'weight_decay': 2.1338629924258474e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.9383074127561595, 'early_stopping_min_delta': 0.0024962347680727867}. Best is trial 32 with value: 0.2908549754956826.

  Epoch 015 - train 0.66196 | val 0.78914
  Classification -> best τ=0.445 (val F1=0.3382)
  Directional -> Accuracy: 0.5714, MCC: 0.1912, F1: 0.6494

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.23160692071833844
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: classification
Sequence length: 15
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.67156 | val 0.72729
  Epoch 019 - train 0.62295 | val 0.73773
  Classification -> best τ=0.505 (val F1=0.2453)
  Directional -> Accuracy: 0.5455, MCC: 0.0541, F1: 0.3636

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.62229 | val 0.86646
  Epoch 011 - train 0.67895 | val 0.84980
  Classification -> best τ=0.470 (val F1=0.0604)
  Directional -> Accuracy: 0.6087, MCC: 0.1780, F1: 0.7000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 16). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.70827 | val 0.75463
  Epoch 012 - train 0.70596 | val 0.81774
  Classification -> best τ=0.495 (val F1=0.4321)
  Directional -> Accuracy: 0.5417, MCC: 0.0000, F1: 0.7027

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.69440 | val 0.80420
  Epoch 011 - train 0.66079 | val 0.90070
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.62349 | val 1.10796
  Epoch 015 - train 0.65347 | val 1.20616
  Classification -> best τ=0.330 (val F1=0.3961)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.7000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.63860 | val 0.70885
  Epoch 016 - train 0.58452 | val 1.22236
  Classification -> best τ=0.470 (val F1=0.2663)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.69934 | val 0.73356
  Epoch 016 - train 0.66328 | val 0.71992
  Classification -> best τ=0.485 (val F1=0.2143)
  Directional -> Accuracy: 0.5143, MCC: 0.1895, F1: 0.5952

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 16). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.67714 | val 1.07028
  Epoch 011 - train 0.66047 | val 0.91320
  Classification -> best τ=0.490 (val F1=0.1048)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.67410 | val 1.19848
  Epoch 011 - train 0.67832 | val 1.02130
  Classification -> best τ=0.500 (val F1=0.4744)
  Directional -> Accuracy: 0.7073, MCC: 0.3530, F1: 0.5714

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 16). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 16). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.69210 | val 0.94037
  Epoch 011 - train 0.64909 | val 0.77406
  Classification -> best τ=0.410 (val F1=0.2510)
  Directional -> Accuracy: 0.4225, MCC: -0.1358, F1: 0.5941

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.65722 | val 0.87047
  Epoch 013 - train 0.72546 | val 0.92555
  Classification -> best τ=0.475 (val F1=0.2814)
  Directional -> Accuracy: 0.5098, MCC: -0.1333, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.67249 | val 0.82168
  Epoch 011 - train 0.68625 | val 0.72824
  Classification -> best τ=0.500 (val F1=0.0272)
  Directional -> Accuracy: 0.5085, MCC: 0.0000, F1: 0.6742

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.65889 | val 1.06847
  Epoch 016 - train 0.64389 | val 0.87030
  Classification -> best τ=0.390 (val F1=0.2869)
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.68168 | val 0.80448
  Epoch 014 - train 0.66165 | val 1.01782
  Classification -> best τ=0.370 (val F1=0.2884)
  Directional -> Accuracy: 0.5738, MCC: 0.1589, F1: 0.6579

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.66555 | val 1.47152
  Epoch 011 - train 0.63402 | val 1.04950
  Classification -> best τ=0.610 (val F1=0.2798)
  Directional -> Accuracy: 0.5283, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.63969 | val 0.71655
  Epoch 013 - train 0.60580 | val 0.87719
  Classification -> best τ=0.480 (val F1=0.3197)
  Directional -> Accuracy: 0.5857, MCC: 0.1518, F1: 0.6588

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.70835 | val 0.84486
  Epoch 011 - train 0.67062 | val 0.93455
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6167, MCC: 0.0000, F1: 0.7629

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.67477 | val 0.83482
  Epoch 017 - train 0.66349 | val 0.92890
  Classification -> best τ=0.620 (val F1=0.1789)
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.67292 | val 0.89587
  Epoch 016 - train 0.66447 | val 0.98508
  Classification -> best τ=0.380 (val F1=0.3603)
  Directional -> Accuracy: 0.5758, MCC: 0.1541, F1: 0.6111

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 16). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.66412 | val 0.72203
  Epoch 017 - train 0.64757 | val 0.75859
  Classification -> best τ=0.525 (val F1=0.2396)
  Directional -> Accuracy: 0.5000, MCC: 0.1873, F1: 0.1364

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.67877 | val 0.68166
  Epoch 020 - train 0.62559 | val 1.39789
  Classification -> best τ=0.425 (val F1=0.2692)
  Directional -> Accuracy: 0.5625, MCC: 0.0770, F1: 0.6441

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.67868 | val 1.93333
  Epoch 011 - train 0.66412 | val 2.03925
  Classification -> best τ=0.475 (val F1=0.0913)
  Directional -> Accuracy: 0.5909, MCC: 0.1861, F1: 0.5424

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.65331 | val 0.92209
  Epoch 015 - train 0.61555 | val 1.38212
  Classification -> best τ=0.620 (val F1=0.3117)
  Directional -> Accuracy: 0.4483, MCC: 0.1153, F1: 0.0588

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.70195 | val 1.29447
  Epoch 011 - train 0.67884 | val 1.90834
  Classification -> best τ=0.440 (val F1=0.2453)
  Directional -> Accuracy: 0.5455, MCC: 0.1290, F1: 0.6154

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.66386 | val 0.68284
  Epoch 018 - train 0.67321 | val 0.64085
  Classification -> best τ=0.465 (val F1=0.5093)
  Directional -> Accuracy: 0.5714, MCC: 0.2385, F1: 0.4545

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.70165 | val 0.73288
  Epoch 011 - train 0.72662 | val 0.71900
  Classification -> best τ=0.485 (val F1=0.2821)
  Directional -> Accuracy: 0.4255, MCC: 0.0000, F1: 0.5970

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.68177 | val 0.69328
  Epoch 020 - train 0.61888 | val 0.66442
  Epoch 030 - train 0.58499 | val 0.96978
  Classification -> best τ=0.590 (val F1=0.3742)
  Directional -> Accuracy: 0.4884, MCC: 0.2324, F1: 0.2143

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.66561 | val 0.81190
  Epoch 012 - train 0.63895 | val 0.82072
  Classification -> best τ=0.450 (val F1=0.2156)
  Directional -> Accuracy: 0.5345, MCC: 0.1948, F1: 0.3415

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.70849 | val 0.79593
  Epoch 012 - train 0.63639 | val 0.69909
  Classification -> best τ=0.525 (val F1=0.1961)
  Directional -> Accuracy: 0.5000, MCC: 0.0976, F1: 0.2759

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.68296 | val 1.85698
  Epoch 011 - train 0.58631 | val 0.78587
  Classification -> best τ=0.530 (val F1=0.0468)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.3529

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.66556 | val 0.64786
  Epoch 020 - train 0.68739 | val 0.69395
  Classification -> best τ=0.700 (val F1=0.1903)
  Directional -> Accuracy: 0.6364, MCC: 0.3105, F1: 0.6000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.66482 | val 0.71848
  Epoch 016 - train 0.60277 | val 0.80085
  Classification -> best τ=0.730 (val F1=0.2320)
  Directional -> Accuracy: 0.6078, MCC: 0.2079, F1: 0.6667

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.67321 | val 0.65905
  Epoch 017 - train 0.63377 | val 0.68970
  Classification -> best τ=0.750 (val F1=0.3084)
  Directional -> Accuracy: 0.4324, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.65541 | val 0.77329
  Epoch 013 - train 0.66124 | val 0.95031
  Classification -> best τ=0.460 (val F1=0.3125)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6122

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.68327 | val 0.96301
  Epoch 011 - train 0.67131 | val 1.15212
  Classification -> best τ=0.520 (val F1=0.0496)
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.6364

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.62114 | val 0.76297
  Epoch 015 - train 0.64205 | val 0.79502
  Classification -> best τ=0.375 (val F1=0.3166)
  Directional -> Accuracy: 0.5224, MCC: 0.0684, F1: 0.5152

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.71736 | val 0.72717
  Epoch 017 - train 0.67317 | val 0.79836
  Classification -> best τ=0.470 (val F1=0.3493)
  Directional -> Accuracy: 0.6512, MCC: 0.3246, F1: 0.5946

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.66222 | val 0.71886
  Epoch 011 - train 0.66275 | val 0.72116
  Classification -> best τ=0.480 (val F1=0.1697)
  Directional -> Accuracy: 0.4912, MCC: -0.0223, F1: 0.4528

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.67974 | val 0.77947
  Epoch 012 - train 0.65243 | val 0.76139
  Classification -> best τ=0.525 (val F1=0.2797)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 16). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.65675 | val 0.71805
  Epoch 011 - train 0.68458 | val 0.89840
  Classification -> best τ=0.470 (val F1=0.3395)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.64664 | val 0.71382
  Epoch 012 - train 0.64676 | val 0.87491
  Classification -> best τ=0.500 (val F1=0.1870)
  Directional -> Accuracy: 0.4872, MCC: -0.1435, F1: 0.6429

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 16). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.66919 | val 0.71417
  Epoch 013 - train 0.67221 | val 0.87954
  Classification -> best τ=0.410 (val F1=0.3270)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.67276 | val 1.02060
  Epoch 015 - train 0.71783 | val 0.92192
  Classification -> best τ=0.470 (val F1=0.2290)
  Directional -> Accuracy: 0.5106, MCC: 0.0183, F1: 0.5490

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.65758 | val 1.06477
  Epoch 011 - train 0.57271 | val 1.03690
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.67283 | val 0.92864
  Epoch 011 - train 0.62305 | val 1.07858
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.65942 | val 0.77299
  Epoch 011 - train 0.65459 | val 0.74352
  Classification -> best τ=0.495 (val F1=0.1512)
  Directional -> Accuracy: 0.4912, MCC: 0.1746, F1: 0.1212

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.68766 | val 1.69788
  Epoch 011 - train 0.65699 | val 1.92645
  Classification -> best τ=0.515 (val F1=0.4735)
  Directional -> Accuracy: 0.5088, MCC: 0.1231, F1: 0.6500

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.68261 | val 1.80825
  Epoch 011 - train 0.65471 | val 1.61009
  Classification -> best τ=0.455 (val F1=0.2085)
  Directional -> Accuracy: 0.5000, MCC: -0.0719, F1: 0.6582

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.69335 | val 1.11613
  Epoch 012 - train 0.69114 | val 1.16625
  Classification -> best τ=0.545 (val F1=0.1635)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.67676 | val 0.95778
  Epoch 011 - train 0.66088 | val 0.85843
  Classification -> best τ=0.515 (val F1=0.2148)
  Directional -> Accuracy: 0.5161, MCC: 0.0000, F1: 0.0000

[I 2026-02-25 00:29:02,077] Trial 97 finished with value: 0.23500976407002255 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 15, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 32, 'learning_rate': 0.0025881850081824545, 'weight_decay': 6.13113760695151e-06, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.9961832071922534, 'early_stopping_min_delta': 0.0022268691402953025}. Best is trial 32 with value: 0.2908549754956826.

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.23500976407002255
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 15
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.64074 | val 0.70247
  Epoch 015 - train 0.65892 | val 0.71411
  Classification -> best τ=0.505 (val F1=0.3210)
  Directional -> Accuracy: 0.5065, MCC: -0.0886, F1: 0.1364

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.62931 | val 1.04939
  Epoch 011 - train 0.58454 | val 1.11808
  Classification -> best τ=0.470 (val F1=0.1236)
  Directional -> Accuracy: 0.5652, MCC: 0.0510, F1: 0.6970

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 16). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.68492 | val 0.76256
  Epoch 012 - train 0.64629 | val 0.88487
  Classification -> best τ=0.470 (val F1=0.3941)
  Directional -> Accuracy: 0.5625, MCC: 0.1586, F1: 0.7123

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.66688 | val 1.11205
  Epoch 012 - train 0.66381 | val 1.48568
  Classification -> best τ=0.445 (val F1=0.1892)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.62414 | val 0.74768
  Epoch 015 - train 0.55845 | val 1.20220
  Classification -> best τ=0.625 (val F1=0.4105)
  Directional -> Accuracy: 0.6154, MCC: 0.2829, F1: 0.5455

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.63830 | val 0.69817
  Epoch 011 - train 0.60984 | val 0.74513
  Classification -> best τ=0.490 (val F1=0.2079)
  Directional -> Accuracy: 0.5625, MCC: 0.1406, F1: 0.6441

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.67539 | val 0.77816
  Epoch 012 - train 0.68535 | val 0.74832
  Classification -> best τ=0.640 (val F1=0.1715)
  Directional -> Accuracy: 0.6286, MCC: 0.1759, F1: 0.1875

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 16). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.61746 | val 1.62847
  Epoch 011 - train 0.60896 | val 1.52054
  Classification -> best τ=0.585 (val F1=0.2936)
  Directional -> Accuracy: 0.4667, MCC: 0.0240, F1: 0.5556

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.63683 | val 1.01465
  Epoch 013 - train 0.61735 | val 1.20460
  Classification -> best τ=0.520 (val F1=0.3318)
  Directional -> Accuracy: 0.4146, MCC: -0.2281, F1: 0.2500

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 16). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 16). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.64860 | val 0.83012
  Epoch 011 - train 0.62396 | val 1.04096
  Classification -> best τ=0.435 (val F1=0.0707)
  Directional -> Accuracy: 0.4507, MCC: -0.0773, F1: 0.4658

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.62260 | val 0.70650
  Epoch 016 - train 0.57862 | val 0.88615
  Classification -> best τ=0.365 (val F1=0.1895)
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.6400

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.64039 | val 1.32361
  Epoch 011 - train 0.64459 | val 1.18994
  Classification -> best τ=0.390 (val F1=0.2394)
  Directional -> Accuracy: 0.5593, MCC: 0.2186, F1: 0.2778

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.64148 | val 1.08281
  Epoch 014 - train 0.62923 | val 1.43911
  Classification -> best τ=0.555 (val F1=0.2778)
  Directional -> Accuracy: 0.5349, MCC: 0.0468, F1: 0.4444

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.67226 | val 0.70130
  Epoch 013 - train 0.62151 | val 0.70563
  Classification -> best τ=0.355 (val F1=0.2970)
  Directional -> Accuracy: 0.5082, MCC: 0.0098, F1: 0.6053

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.62209 | val 2.10352
  Epoch 012 - train 0.62131 | val 2.35681
  Classification -> best τ=0.625 (val F1=0.2798)
  Directional -> Accuracy: 0.5283, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.68662 | val 0.82472
  Epoch 011 - train 0.64504 | val 0.83863
  Classification -> best τ=0.510 (val F1=0.2205)
  Directional -> Accuracy: 0.6143, MCC: 0.2159, F1: 0.7033

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.65038 | val 1.29591
  Epoch 011 - train 0.64942 | val 1.35555
  Classification -> best τ=0.625 (val F1=0.1039)
  Directional -> Accuracy: 0.3833, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.66399 | val 1.04688
  Epoch 012 - train 0.65367 | val 0.74574
  Classification -> best τ=0.540 (val F1=0.2496)
  Directional -> Accuracy: 0.5395, MCC: 0.1980, F1: 0.4776

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.65217 | val 0.83939
  Epoch 014 - train 0.62895 | val 1.45801
  Classification -> best τ=0.350 (val F1=0.2464)
  Directional -> Accuracy: 0.6212, MCC: 0.2410, F1: 0.6575

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 16). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.62303 | val 0.85940
  Epoch 015 - train 0.60990 | val 0.86186
  Classification -> best τ=0.295 (val F1=0.2518)
  Directional -> Accuracy: 0.5395, MCC: 0.0343, F1: 0.6667

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.60084 | val 0.84853
  Epoch 020 - train 0.62637 | val 1.51604
  Epoch 028 - train 0.54432 | val 1.43688
  Classification -> best τ=0.450 (val F1=0.4855)
  Directional -> Accuracy: 0.4375, MCC: 0.1233, F1: 0.2286

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.65243 | val 1.57835
  Epoch 012 - train 0.64059 | val 2.05131
  Classification -> best τ=0.590 (val F1=0.1834)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.62982 | val 1.20255
  Epoch 011 - train 0.64104 | val 1.34821
  Classification -> best τ=0.575 (val F1=0.2907)
  Directional -> Accuracy: 0.4828, MCC: 0.0658, F1: 0.3182

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.63405 | val 6.46406
  Epoch 012 - train 0.61947 | val 13.63606
  Classification -> best τ=0.495 (val F1=0.2319)
  Directional -> Accuracy: 0.5606, MCC: 0.1374, F1: 0.5915

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.70438 | val 0.64595
  Epoch 016 - train 0.66909 | val 0.76295
  Classification -> best τ=0.495 (val F1=0.5322)
  Directional -> Accuracy: 0.5000, MCC: 0.0823, F1: 0.3333

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.58384 | val 0.78448
  Epoch 011 - train 0.58172 | val 0.85819
  Classification -> best τ=0.545 (val F1=0.1309)
  Directional -> Accuracy: 0.4681, MCC: -0.0810, F1: 0.3902

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.69942 | val 0.75684
  Epoch 013 - train 0.63387 | val 0.75612
  Classification -> best τ=0.585 (val F1=0.0573)
  Directional -> Accuracy: 0.5349, MCC: -0.0208, F1: 0.6552

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.64501 | val 0.77035
  Epoch 011 - train 0.67887 | val 0.79491
  Classification -> best τ=0.445 (val F1=0.1645)
  Directional -> Accuracy: 0.5690, MCC: 0.2351, F1: 0.4444

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.74048 | val 0.75318
  Epoch 020 - train 0.56146 | val 0.79680
  Epoch 024 - train 0.60458 | val 0.79459
  Classification -> best τ=0.585 (val F1=0.4193)
  Directional -> Accuracy: 0.6190, MCC: 0.2494, F1: 0.6190

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.64390 | val 1.19902
  Epoch 011 - train 0.65711 | val 1.25990
  Classification -> best τ=0.575 (val F1=0.1869)
  Directional -> Accuracy: 0.5455, MCC: 0.0913, F1: 0.5652

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.64481 | val 0.77210
  Epoch 013 - train 0.68613 | val 0.93046
  Classification -> best τ=0.625 (val F1=0.1506)
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.58849 | val 0.92201
  Epoch 011 - train 0.60729 | val 0.80857
  Classification -> best τ=0.510 (val F1=0.2278)
  Directional -> Accuracy: 0.5490, MCC: 0.1500, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.61839 | val 0.88958
  Epoch 013 - train 0.66466 | val 1.60561
  Classification -> best τ=0.450 (val F1=0.3470)
  Directional -> Accuracy: 0.5676, MCC: 0.2097, F1: 0.5000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.57580 | val 0.69718
  Epoch 019 - train 0.60535 | val 0.79264
  Classification -> best τ=0.425 (val F1=0.4045)
  Directional -> Accuracy: 0.5263, MCC: 0.0619, F1: 0.6250

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.69228 | val 1.34423
  Epoch 011 - train 0.61059 | val 1.52435
  Classification -> best τ=0.465 (val F1=0.1545)
  Directional -> Accuracy: 0.4889, MCC: -0.1048, F1: 0.1481

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.60092 | val 0.84368
  Epoch 014 - train 0.57659 | val 0.70086
  Classification -> best τ=0.280 (val F1=0.3431)
  Directional -> Accuracy: 0.5970, MCC: 0.2509, F1: 0.5574

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.69148 | val 0.74887
  Epoch 017 - train 0.55135 | val 0.72620
  Classification -> best τ=0.450 (val F1=0.4566)
  Directional -> Accuracy: 0.6744, MCC: 0.3810, F1: 0.6111

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.64199 | val 0.93504
  Epoch 013 - train 0.68464 | val 0.91000
  Classification -> best τ=0.405 (val F1=0.3393)
  Directional -> Accuracy: 0.5439, MCC: 0.1154, F1: 0.6061

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.60555 | val 0.99399
  Epoch 018 - train 0.57139 | val 0.71497
  Classification -> best τ=0.505 (val F1=0.4013)
  Directional -> Accuracy: 0.5319, MCC: -0.0118, F1: 0.6333

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 16). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.63694 | val 0.88733
  Epoch 011 - train 0.56256 | val 0.89066
  Classification -> best τ=0.450 (val F1=0.2582)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.67275 | val 0.83303
  Epoch 013 - train 0.63055 | val 0.87654
  Classification -> best τ=0.425 (val F1=0.5235)
  Directional -> Accuracy: 0.4872, MCC: 0.0473, F1: 0.2308

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 16). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.62289 | val 0.90863
  Epoch 013 - train 0.61083 | val 1.30674
  Classification -> best τ=0.700 (val F1=0.2755)
  Directional -> Accuracy: 0.5921, MCC: 0.2005, F1: 0.6593

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.64600 | val 0.85387
  Epoch 013 - train 0.60637 | val 0.73565
  Classification -> best τ=0.490 (val F1=0.3693)
  Directional -> Accuracy: 0.4894, MCC: -0.0509, F1: 0.6250

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.61235 | val 1.02544
  Epoch 011 - train 0.60736 | val 1.31768
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.64513 | val 0.69407
  Epoch 011 - train 0.64449 | val 0.67552
  Classification -> best τ=0.535 (val F1=0.4291)
  Directional -> Accuracy: 0.6250, MCC: -0.1175, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.62214 | val 0.81891
  Epoch 011 - train 0.65631 | val 0.76569
  Classification -> best τ=0.425 (val F1=0.2973)
  Directional -> Accuracy: 0.5263, MCC: -0.1224, F1: 0.6897

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.66038 | val 1.92527
  Epoch 014 - train 0.60562 | val 1.87433
  Classification -> best τ=0.560 (val F1=0.4484)
  Directional -> Accuracy: 0.5263, MCC: 0.0970, F1: 0.6197

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.63305 | val 1.26324
  Epoch 011 - train 0.71100 | val 1.26650
  Classification -> best τ=0.420 (val F1=0.1757)
  Directional -> Accuracy: 0.5741, MCC: 0.1437, F1: 0.6349

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.64267 | val 1.06949
  Epoch 012 - train 0.59201 | val 1.78891
  Classification -> best τ=0.440 (val F1=0.2157)
  Directional -> Accuracy: 0.4737, MCC: -0.0939, F1: 0.6154

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.63067 | val 0.97386

[I 2026-02-25 00:30:47,017] Trial 98 finished with value: 0.2730520500434152 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 15, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 0.006462282342478096, 'weight_decay': 1.1355793565452746e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.5539917464423878, 'early_stopping_min_delta': 0.0014751100623877195}. Best is trial 32 with value: 0.2908549754956826.

  Epoch 012 - train 0.61150 | val 1.49074
  Classification -> best τ=0.510 (val F1=0.2831)
  Directional -> Accuracy: 0.5806, MCC: 0.1731, F1: 0.6176

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2730520500434152
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 15
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.64277 | val 0.67685
  Epoch 016 - train 0.63698 | val 1.15930
  Classification -> best τ=0.550 (val F1=0.2453)
  Directional -> Accuracy: 0.6104, MCC: 0.2340, F1: 0.6154

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.59970 | val 0.92014
  Epoch 013 - train 0.60086 | val 1.46198
  Classification -> best τ=0.470 (val F1=0.1700)
  Directional -> Accuracy: 0.6087, MCC: 0.1812, F1: 0.7273

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 16). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.67024 | val 0.68914
  Epoch 011 - train 0.70746 | val 0.73962
  Classification -> best τ=0.470 (val F1=0.3126)
  Directional -> Accuracy: 0.5417, MCC: 0.0483, F1: 0.6452

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.67312 | val 1.15776
  Epoch 011 - train 0.66753 | val 1.00073
  Classification -> best τ=0.435 (val F1=0.1771)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.63448 | val 0.74118
  Epoch 017 - train 0.57005 | val 0.88865
  Classification -> best τ=0.475 (val F1=0.3920)
  Directional -> Accuracy: 0.6538, MCC: 0.3169, F1: 0.7353

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.57558 | val 1.04193
  Epoch 011 - train 0.60365 | val 0.92007
  Classification -> best τ=0.515 (val F1=0.3254)
  Directional -> Accuracy: 0.5833, MCC: 0.1672, F1: 0.6000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.66055 | val 0.72728
  Epoch 011 - train 0.68472 | val 0.80389
  Classification -> best τ=0.550 (val F1=0.1204)
  Directional -> Accuracy: 0.6000, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 16). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.57727 | val 1.10583
  Epoch 011 - train 0.64130 | val 1.41114
  Classification -> best τ=0.540 (val F1=0.0904)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.65613 | val 1.19827
  Epoch 016 - train 0.62343 | val 1.33239
  Classification -> best τ=0.510 (val F1=0.3290)
  Directional -> Accuracy: 0.4146, MCC: 0.0791, F1: 0.5385

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 16). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 16). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.63356 | val 1.13621
  Epoch 011 - train 0.63934 | val 1.24528
  Classification -> best τ=0.430 (val F1=0.1429)
  Directional -> Accuracy: 0.4366, MCC: 0.0000, F1: 0.6078

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.64437 | val 1.72123
  Epoch 013 - train 0.67906 | val 1.87669
  Classification -> best τ=0.415 (val F1=0.1177)
  Directional -> Accuracy: 0.5882, MCC: 0.1742, F1: 0.4000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.63520 | val 0.76571
  Epoch 018 - train 0.62442 | val 0.67334
  Classification -> best τ=0.735 (val F1=0.3257)
  Directional -> Accuracy: 0.5254, MCC: 0.1065, F1: 0.2222

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.65279 | val 1.12027
  Epoch 011 - train 0.59899 | val 1.29799
  Classification -> best τ=0.430 (val F1=0.2454)
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.65162 | val 0.82840
  Epoch 013 - train 0.65341 | val 1.03160
  Classification -> best τ=0.430 (val F1=0.1986)
  Directional -> Accuracy: 0.5246, MCC: 0.0464, F1: 0.6027

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.63844 | val 1.79729
  Epoch 013 - train 0.63349 | val 4.41510
  Classification -> best τ=0.565 (val F1=0.3029)
  Directional -> Accuracy: 0.4528, MCC: -0.0779, F1: 0.5915

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.60889 | val 0.82238
  Epoch 011 - train 0.59056 | val 0.84855
  Classification -> best τ=0.530 (val F1=0.2676)
  Directional -> Accuracy: 0.6143, MCC: 0.2179, F1: 0.6582

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.67205 | val 1.29008
  Epoch 012 - train 0.66622 | val 1.35115
  Classification -> best τ=0.490 (val F1=0.2112)
  Directional -> Accuracy: 0.4667, MCC: 0.2377, F1: 0.2381

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.66025 | val 1.68055
  Epoch 011 - train 0.68582 | val 1.19323
  Classification -> best τ=0.455 (val F1=0.1533)
  Directional -> Accuracy: 0.5526, MCC: 0.0855, F1: 0.6136

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.66925 | val 0.86699
  Epoch 012 - train 0.66205 | val 1.06566
  Classification -> best τ=0.460 (val F1=0.2778)
  Directional -> Accuracy: 0.5152, MCC: 0.1796, F1: 0.3846

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 16). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.65035 | val 0.71948
  Epoch 020 - train 0.56378 | val 1.12898
  Epoch 027 - train 0.59237 | val 1.24591
  Classification -> best τ=0.355 (val F1=0.3441)
  Directional -> Accuracy: 0.5132, MCC: 0.0598, F1: 0.4308

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.63604 | val 1.51549
  Epoch 011 - train 0.61280 | val 1.12902
  Classification -> best τ=0.490 (val F1=0.1383)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.62542 | val 1.09707
  Epoch 012 - train 0.63489 | val 1.31188
  Classification -> best τ=0.410 (val F1=0.1177)
  Directional -> Accuracy: 0.5455, MCC: 0.1143, F1: 0.6512

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.63621 | val 1.06137
  Epoch 011 - train 0.61670 | val 1.09869
  Classification -> best τ=0.510 (val F1=0.2299)
  Directional -> Accuracy: 0.5345, MCC: 0.0951, F1: 0.5263

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.62870 | val 2.05088
  Epoch 012 - train 0.61757 | val 3.24252
  Classification -> best τ=0.450 (val F1=0.2319)
  Directional -> Accuracy: 0.5606, MCC: 0.1434, F1: 0.6027

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.63629 | val 0.64932
  Epoch 020 - train 0.59633 | val 0.76664
  Classification -> best τ=0.465 (val F1=0.5125)
  Directional -> Accuracy: 0.5893, MCC: 0.2499, F1: 0.5106

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.65479 | val 0.82620
  Epoch 011 - train 0.59427 | val 0.89371
  Classification -> best τ=0.510 (val F1=0.2471)
  Directional -> Accuracy: 0.5745, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.63068 | val 0.88431
  Epoch 011 - train 0.64878 | val 1.19503
  Classification -> best τ=0.510 (val F1=0.1309)
  Directional -> Accuracy: 0.5349, MCC: 0.0746, F1: 0.5652

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.63314 | val 0.76267
  Epoch 012 - train 0.61833 | val 0.76700
  Classification -> best τ=0.395 (val F1=0.1645)
  Directional -> Accuracy: 0.5690, MCC: 0.2351, F1: 0.4444

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.71105 | val 0.68577
  Epoch 020 - train 0.57722 | val 0.75947
  Epoch 029 - train 0.59347 | val 0.77553
  Classification -> best τ=0.410 (val F1=0.3677)
  Directional -> Accuracy: 0.5952, MCC: 0.1795, F1: 0.6383

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.65578 | val 1.52751
  Epoch 011 - train 0.59766 | val 1.39505
  Classification -> best τ=0.540 (val F1=0.1869)
  Directional -> Accuracy: 0.4773, MCC: -0.0498, F1: 0.3429

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.62128 | val 0.73966
  Epoch 017 - train 0.67581 | val 0.95459
  Classification -> best τ=0.595 (val F1=0.1189)
  Directional -> Accuracy: 0.4773, MCC: -0.1234, F1: 0.6102

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.60126 | val 0.81426
  Epoch 018 - train 0.51563 | val 1.55884
  Classification -> best τ=0.495 (val F1=0.2659)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.65561 | val 1.05207
  Epoch 015 - train 0.61002 | val 1.62502
  Classification -> best τ=0.355 (val F1=0.3134)
  Directional -> Accuracy: 0.5405, MCC: 0.1770, F1: 0.4333

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.61466 | val 0.81439
  Epoch 011 - train 0.58927 | val 0.86240
  Classification -> best τ=0.465 (val F1=0.4792)
  Directional -> Accuracy: 0.5263, MCC: 0.0555, F1: 0.5909

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.61580 | val 0.91684
  Epoch 011 - train 0.59515 | val 0.96423
  Classification -> best τ=0.525 (val F1=0.0496)
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.6364

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.60467 | val 0.74861
  Epoch 013 - train 0.61143 | val 0.73645
  Classification -> best τ=0.445 (val F1=0.2373)
  Directional -> Accuracy: 0.4478, MCC: 0.1075, F1: 0.0513

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.72656 | val 0.86268
  Epoch 016 - train 0.65305 | val 0.76281
  Classification -> best τ=0.425 (val F1=0.3296)
  Directional -> Accuracy: 0.6512, MCC: 0.3072, F1: 0.6341

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.62256 | val 0.82517
  Epoch 014 - train 0.58203 | val 0.77528
  Classification -> best τ=0.475 (val F1=0.2207)
  Directional -> Accuracy: 0.5263, MCC: 0.0518, F1: 0.5091

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.62190 | val 0.87946
  Epoch 018 - train 0.52442 | val 1.10549
  Classification -> best τ=0.520 (val F1=0.3057)
  Directional -> Accuracy: 0.5957, MCC: -0.1162, F1: 0.7467

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 16). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.58698 | val 0.90045
  Epoch 011 - train 0.58295 | val 1.15480
  Classification -> best τ=0.505 (val F1=0.2928)
  Directional -> Accuracy: 0.3750, MCC: 0.1175, F1: 0.5283

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.64296 | val 0.80050
  Epoch 011 - train 0.57129 | val 0.80560
  Classification -> best τ=0.450 (val F1=0.1870)
  Directional -> Accuracy: 0.4359, MCC: -0.3130, F1: 0.6071

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 16). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.61881 | val 1.21829
  Epoch 014 - train 0.60889 | val 1.84530
  Classification -> best τ=0.375 (val F1=0.4446)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.69686 | val 0.70466
  Epoch 011 - train 0.64157 | val 0.77454
  Classification -> best τ=0.505 (val F1=0.3119)
  Directional -> Accuracy: 0.5745, MCC: 0.1539, F1: 0.5455

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.58019 | val 1.06208
  Epoch 011 - train 0.62114 | val 1.26476
  Classification -> best τ=0.525 (val F1=0.1000)
  Directional -> Accuracy: 0.4444, MCC: -0.0349, F1: 0.1379

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.72398 | val 0.66095
  Epoch 017 - train 0.62917 | val 0.78295
  Classification -> best τ=0.510 (val F1=0.4228)
  Directional -> Accuracy: 0.4500, MCC: 0.2446, F1: 0.5600

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.67454 | val 0.85899
  Epoch 014 - train 0.62268 | val 1.71091
  Classification -> best τ=0.555 (val F1=0.2523)
  Directional -> Accuracy: 0.5439, MCC: 0.0455, F1: 0.6579

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.60841 | val 1.54455
  Epoch 012 - train 0.58945 | val 2.29051
  Classification -> best τ=0.435 (val F1=0.2554)
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.63100 | val 2.08288
  Epoch 011 - train 0.63291 | val 2.02845
  Classification -> best τ=0.450 (val F1=0.2661)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.65556 | val 1.75346
  Epoch 011 - train 0.62050 | val 1.32628
  Classification -> best τ=0.560 (val F1=0.1083)
  Directional -> Accuracy: 0.4912, MCC: -0.0294, F1: 0.5915

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.64843 | val 1.07783

[I 2026-02-25 00:32:36,437] Trial 99 finished with value: 0.24656152498267034 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 15, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 0.003259747037683338, 'weight_decay': 9.461339260142181e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.5528374294642566, 'early_stopping_min_delta': 0.001755192006606635}. Best is trial 32 with value: 0.2908549754956826.

  Epoch 012 - train 0.63281 | val 1.35730
  Classification -> best τ=0.565 (val F1=0.2898)
  Directional -> Accuracy: 0.5323, MCC: 0.0688, F1: 0.1714

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.24656152498267034
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 15
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.62893 | val 0.78759
  Epoch 013 - train 0.61211 | val 0.97374
  Classification -> best τ=0.470 (val F1=0.2453)
  Directional -> Accuracy: 0.5974, MCC: 0.1904, F1: 0.3111

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.56502 | val 1.18991
  Epoch 013 - train 0.60279 | val 1.04109
  Classification -> best τ=0.485 (val F1=0.2431)
  Directional -> Accuracy: 0.6087, MCC: 0.1812, F1: 0.7273

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 16). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.68870 | val 0.85681
  Epoch 016 - train 0.62734 | val 0.73533
  Classification -> best τ=0.615 (val F1=0.3769)
  Directional -> Accuracy: 0.4583, MCC: -0.0769, F1: 0.4583

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.69232 | val 1.10125
  Epoch 011 - train 0.64198 | val 0.88740
  Classification -> best τ=0.435 (val F1=0.0272)
  Directional -> Accuracy: 0.6000, MCC: 0.1777, F1: 0.6875

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.54337 | val 1.34582
  Epoch 012 - train 0.56154 | val 1.24615
  Classification -> best τ=0.435 (val F1=0.4357)
  Directional -> Accuracy: 0.7115, MCC: 0.4173, F1: 0.7458

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.53981 | val 0.73618
  Epoch 014 - train 0.51417 | val 1.12850
  Classification -> best τ=0.510 (val F1=0.4899)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.63876 | val 0.73552
  Epoch 014 - train 0.66369 | val 0.74252
  Classification -> best τ=0.535 (val F1=0.3164)
  Directional -> Accuracy: 0.4857, MCC: 0.2016, F1: 0.6000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 16). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.60339 | val 1.27445
  Epoch 011 - train 0.55714 | val 1.28831
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.57554 | val 1.07626
  Epoch 012 - train 0.61611 | val 1.22635
  Classification -> best τ=0.555 (val F1=0.3873)
  Directional -> Accuracy: 0.5854, MCC: 0.1443, F1: 0.4848

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 16). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 16). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.62504 | val 0.85006
  Epoch 011 - train 0.61025 | val 0.87557
  Classification -> best τ=0.465 (val F1=0.0767)
  Directional -> Accuracy: 0.4085, MCC: -0.1934, F1: 0.5800

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.64464 | val 1.17826
  Epoch 012 - train 0.63856 | val 1.57947
  Classification -> best τ=0.450 (val F1=0.0463)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.65549 | val 0.71993
  Epoch 013 - train 0.61398 | val 0.86661
  Classification -> best τ=0.555 (val F1=0.2485)
  Directional -> Accuracy: 0.5424, MCC: 0.0972, F1: 0.4490

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.62433 | val 1.27769
  Epoch 011 - train 0.59052 | val 1.36443
  Classification -> best τ=0.405 (val F1=0.0584)
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.63247 | val 0.83270
  Epoch 014 - train 0.63460 | val 0.99703
  Classification -> best τ=0.505 (val F1=0.2541)
  Directional -> Accuracy: 0.5082, MCC: 0.0549, F1: 0.1667

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.56691 | val 2.57332
  Epoch 013 - train 0.56538 | val 2.50643
  Classification -> best τ=0.500 (val F1=0.2145)
  Directional -> Accuracy: 0.4717, MCC: 0.0000, F1: 0.6410

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.60858 | val 0.99286
  Epoch 011 - train 0.60848 | val 0.93249
  Classification -> best τ=0.460 (val F1=0.2997)
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.66151 | val 1.27164
  Epoch 011 - train 0.67194 | val 1.26029
  Classification -> best τ=0.560 (val F1=0.2219)
  Directional -> Accuracy: 0.3833, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.64315 | val 1.27315
  Epoch 011 - train 0.67380 | val 1.18311
  Classification -> best τ=0.430 (val F1=0.1898)
  Directional -> Accuracy: 0.6184, MCC: 0.1430, F1: 0.7603

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.63819 | val 1.15059
  Epoch 013 - train 0.62456 | val 1.50914
  Classification -> best τ=0.380 (val F1=0.2464)
  Directional -> Accuracy: 0.5303, MCC: 0.2056, F1: 0.4151

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 16). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.63077 | val 0.75228
  Epoch 019 - train 0.56624 | val 0.81113
  Classification -> best τ=0.610 (val F1=0.3504)
  Directional -> Accuracy: 0.5263, MCC: 0.0791, F1: 0.4706

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.59768 | val 0.92657
  Epoch 013 - train 0.59220 | val 1.62176
  Classification -> best τ=0.535 (val F1=0.2000)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.62586 | val 1.08041
  Epoch 011 - train 0.64081 | val 1.01316
  Classification -> best τ=0.610 (val F1=0.1187)
  Directional -> Accuracy: 0.5152, MCC: 0.0727, F1: 0.1111

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.61813 | val 1.08103
  Epoch 011 - train 0.65326 | val 1.05293
  Classification -> best τ=0.670 (val F1=0.2437)
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.61953 | val 3.24605
  Epoch 011 - train 0.58638 | val 2.94311
  Classification -> best τ=0.430 (val F1=0.1860)
  Directional -> Accuracy: 0.5152, MCC: 0.0950, F1: 0.6279

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.61661 | val 0.80486
  Epoch 012 - train 0.62357 | val 0.77803
  Classification -> best τ=0.575 (val F1=0.4464)
  Directional -> Accuracy: 0.4643, MCC: 0.0541, F1: 0.1176

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.57224 | val 0.71509
  Epoch 012 - train 0.56963 | val 0.73938
  Classification -> best τ=0.480 (val F1=0.1385)
  Directional -> Accuracy: 0.5957, MCC: 0.1273, F1: 0.1739

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.62142 | val 0.81466
  Epoch 013 - train 0.57190 | val 0.83587
  Classification -> best τ=0.530 (val F1=0.2717)
  Directional -> Accuracy: 0.5581, MCC: 0.1656, F1: 0.5366

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.62247 | val 0.81856
  Epoch 011 - train 0.61849 | val 0.80234
  Classification -> best τ=0.465 (val F1=0.3035)
  Directional -> Accuracy: 0.5517, MCC: 0.0531, F1: 0.6667

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.55286 | val 0.70051
  Epoch 018 - train 0.66925 | val 0.74772
  Classification -> best τ=0.510 (val F1=0.3548)
  Directional -> Accuracy: 0.4286, MCC: -0.1083, F1: 0.2500

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.62315 | val 1.36738
  Epoch 011 - train 0.56971 | val 1.58898
  Classification -> best τ=0.555 (val F1=0.1869)
  Directional -> Accuracy: 0.5227, MCC: 0.0902, F1: 0.1600

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.64268 | val 0.75394
  Epoch 016 - train 0.59840 | val 1.10674
  Classification -> best τ=0.615 (val F1=0.0587)
  Directional -> Accuracy: 0.5227, MCC: -0.1392, F1: 0.6866

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.55387 | val 0.85105
  Epoch 017 - train 0.53253 | val 0.99092
  Classification -> best τ=0.450 (val F1=0.3170)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.64050 | val 0.90624
  Epoch 013 - train 0.61347 | val 1.97807
  Classification -> best τ=0.485 (val F1=0.3874)
  Directional -> Accuracy: 0.5405, MCC: 0.1282, F1: 0.5000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.62425 | val 0.79182
  Epoch 011 - train 0.63551 | val 0.79965
  Classification -> best τ=0.425 (val F1=0.3130)
  Directional -> Accuracy: 0.4737, MCC: -0.0619, F1: 0.5833

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.62856 | val 1.14123
  Epoch 011 - train 0.56815 | val 1.56587
  Classification -> best τ=0.550 (val F1=0.2306)
  Directional -> Accuracy: 0.5556, MCC: 0.0945, F1: 0.2308

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.61649 | val 0.70389
  Epoch 011 - train 0.60405 | val 0.73024
  Classification -> best τ=0.390 (val F1=0.2715)
  Directional -> Accuracy: 0.5522, MCC: 0.1618, F1: 0.5000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.59849 | val 0.76661
  Epoch 020 - train 0.54973 | val 0.76343
  Epoch 023 - train 0.50946 | val 0.75316
  Classification -> best τ=0.645 (val F1=0.3337)
  Directional -> Accuracy: 0.6744, MCC: 0.3810, F1: 0.6111

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.57277 | val 0.80108
  Epoch 011 - train 0.63758 | val 0.76886
  Classification -> best τ=0.475 (val F1=0.1851)
  Directional -> Accuracy: 0.5263, MCC: 0.0745, F1: 0.5846

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.59514 | val 1.25272
  Epoch 013 - train 0.54142 | val 1.52970
  Classification -> best τ=0.435 (val F1=0.2057)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 16). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.61863 | val 1.71714
  Epoch 013 - train 0.51952 | val 1.77448
  Classification -> best τ=0.515 (val F1=0.4472)
  Directional -> Accuracy: 0.3500, MCC: -0.0721, F1: 0.5000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.56185 | val 0.78695
  Epoch 011 - train 0.60718 | val 0.80418
  Classification -> best τ=0.450 (val F1=0.1870)
  Directional -> Accuracy: 0.4872, MCC: -0.2152, F1: 0.6552

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 16). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.61923 | val 0.93074
  Epoch 011 - train 0.60533 | val 1.09587
  Classification -> best τ=0.520 (val F1=0.1801)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.61569 | val 1.29328
  Epoch 011 - train 0.59678 | val 1.03876
  Classification -> best τ=0.515 (val F1=0.2485)
  Directional -> Accuracy: 0.4681, MCC: -0.0687, F1: 0.1935

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.61130 | val 1.49101
  Epoch 011 - train 0.58014 | val 1.35673
  Classification -> best τ=0.535 (val F1=0.4000)
  Directional -> Accuracy: 0.4444, MCC: -0.0439, F1: 0.1935

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.56699 | val 0.95752
  Epoch 011 - train 0.58316 | val 0.81545
  Classification -> best τ=0.565 (val F1=0.0675)
  Directional -> Accuracy: 0.6000, MCC: 0.3187, F1: 0.6000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.67454 | val 1.78172
  Epoch 012 - train 0.62679 | val 2.16116
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5439, MCC: 0.0000, F1: 0.7045

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.62078 | val 1.47867
  Epoch 012 - train 0.57582 | val 2.35584
  Classification -> best τ=0.450 (val F1=0.2554)
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.61898 | val 1.67497
  Epoch 011 - train 0.68275 | val 1.93515
  Classification -> best τ=0.420 (val F1=0.2869)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.61290 | val 1.42725
  Epoch 013 - train 0.63805 | val 1.10450
  Classification -> best τ=0.505 (val F1=0.1707)
  Directional -> Accuracy: 0.5263, MCC: 0.1360, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.62176 | val 0.91243

[I 2026-02-25 00:33:31,662] Trial 100 finished with value: 0.23980382040246398 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 15, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 0.005349400945606463, 'weight_decay': 2.6596144212561412e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.6033536904526842, 'early_stopping_min_delta': 0.0012281437272351336}. Best is trial 32 with value: 0.2908549754956826.

  Epoch 014 - train 0.58972 | val 1.07863
  Classification -> best τ=0.575 (val F1=0.2653)
  Directional -> Accuracy: 0.4839, MCC: -0.1229, F1: 0.0588

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.23980382040246398
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 15
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.70070 | val 0.69548
  Epoch 019 - train 0.68613 | val 0.78888
  Classification -> best τ=0.615 (val F1=0.3210)
  Directional -> Accuracy: 0.5325, MCC: -0.0165, F1: 0.1429

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.69648 | val 0.73405
  Epoch 014 - train 0.65322 | val 0.83306
  Classification -> best τ=0.550 (val F1=0.1962)
  Directional -> Accuracy: 0.5870, MCC: 0.1252, F1: 0.6885

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 16). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.70242 | val 0.82130
  Epoch 011 - train 0.70703 | val 0.77808
  Classification -> best τ=0.500 (val F1=0.1631)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.5200

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.71789 | val 1.14149
  Epoch 011 - train 0.67665 | val 1.13283
  Classification -> best τ=0.435 (val F1=0.1989)
  Directional -> Accuracy: 0.5467, MCC: 0.1875, F1: 0.3929

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.65262 | val 1.09382
  Epoch 016 - train 0.62253 | val 1.46345
  Classification -> best τ=0.530 (val F1=0.4042)
  Directional -> Accuracy: 0.6731, MCC: 0.3504, F1: 0.6792

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.63932 | val 0.69967
  Epoch 017 - train 0.58889 | val 0.78202
  Classification -> best τ=0.480 (val F1=0.3254)
  Directional -> Accuracy: 0.5625, MCC: 0.1771, F1: 0.6769

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.72479 | val 0.69199
  Epoch 012 - train 0.70909 | val 0.68593
  Classification -> best τ=0.475 (val F1=0.2683)
  Directional -> Accuracy: 0.5429, MCC: 0.0126, F1: 0.3600

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 16). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.60486 | val 1.47933
  Epoch 011 - train 0.67213 | val 1.68409
  Classification -> best τ=0.465 (val F1=0.3780)
  Directional -> Accuracy: 0.6000, MCC: 0.1350, F1: 0.3571

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.69951 | val 0.87660
  Epoch 016 - train 0.66027 | val 0.96200
  Classification -> best τ=0.605 (val F1=0.3877)
  Directional -> Accuracy: 0.4878, MCC: -0.0321, F1: 0.4000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 16). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 16). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.65777 | val 1.11800
  Epoch 013 - train 0.65346 | val 0.84135
  Classification -> best τ=0.415 (val F1=0.2479)
  Directional -> Accuracy: 0.4507, MCC: 0.1052, F1: 0.6139

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.68334 | val 1.32823
  Epoch 013 - train 0.67418 | val 1.29756
  Classification -> best τ=0.330 (val F1=0.1557)
  Directional -> Accuracy: 0.5882, MCC: 0.1673, F1: 0.5116

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.71145 | val 0.75990
  Epoch 016 - train 0.67566 | val 0.76672
  Classification -> best τ=0.600 (val F1=0.2966)
  Directional -> Accuracy: 0.6780, MCC: 0.3702, F1: 0.7246

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.69015 | val 0.84235
  Epoch 015 - train 0.67165 | val 1.04186
  Classification -> best τ=0.560 (val F1=0.1700)
  Directional -> Accuracy: 0.5581, MCC: 0.0375, F1: 0.1739

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.69018 | val 0.68940
  Epoch 020 - train 0.62112 | val 0.89411
  Epoch 024 - train 0.74739 | val 1.03268
  Classification -> best τ=0.330 (val F1=0.3523)
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.67088 | val 0.78613
  Epoch 011 - train 0.72440 | val 0.89773
  Classification -> best τ=0.555 (val F1=0.2145)
  Directional -> Accuracy: 0.4717, MCC: 0.0000, F1: 0.6410

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.67255 | val 0.75930
  Epoch 011 - train 0.68635 | val 0.74459
  Classification -> best τ=0.450 (val F1=0.2605)
  Directional -> Accuracy: 0.5000, MCC: -0.1432, F1: 0.6602

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.68870 | val 1.05243
  Epoch 014 - train 0.65652 | val 1.41199
  Classification -> best τ=0.600 (val F1=0.2112)
  Directional -> Accuracy: 0.3833, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.66057 | val 1.02548
  Epoch 011 - train 0.68742 | val 0.96120
  Classification -> best τ=0.480 (val F1=0.1764)
  Directional -> Accuracy: 0.5263, MCC: 0.0313, F1: 0.5909

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.69616 | val 0.69168
  Epoch 020 - train 0.65240 | val 0.89527
  Epoch 021 - train 0.67095 | val 0.82218
  Classification -> best τ=0.335 (val F1=0.2778)
  Directional -> Accuracy: 0.5152, MCC: -0.0836, F1: 0.6444

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 16). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.66625 | val 0.76274
  Epoch 013 - train 0.66899 | val 0.76864
  Classification -> best τ=0.210 (val F1=0.1560)
  Directional -> Accuracy: 0.5395, MCC: 0.0000, F1: 0.7009

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.61957 | val 0.82571
  Epoch 011 - train 0.68793 | val 0.69658
  Classification -> best τ=0.435 (val F1=0.2692)
  Directional -> Accuracy: 0.6042, MCC: 0.3037, F1: 0.5957

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.70442 | val 0.92979
  Epoch 011 - train 0.68112 | val 1.04186
  Classification -> best τ=0.710 (val F1=0.2264)
  Directional -> Accuracy: 0.5303, MCC: 0.1270, F1: 0.1622

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.69099 | val 0.99671
  Epoch 013 - train 0.69225 | val 0.86550
  Classification -> best τ=0.665 (val F1=0.3348)
  Directional -> Accuracy: 0.5345, MCC: 0.1323, F1: 0.4706

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.65270 | val 1.04924
  Epoch 011 - train 0.65936 | val 0.90440
  Classification -> best τ=0.410 (val F1=0.2215)
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.65892 | val 0.67305
  Epoch 013 - train 0.67405 | val 0.79605
  Classification -> best τ=0.590 (val F1=0.3566)
  Directional -> Accuracy: 0.4464, MCC: -0.0299, F1: 0.1143

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.65262 | val 0.80402
  Epoch 014 - train 0.62765 | val 0.95494
  Classification -> best τ=0.560 (val F1=0.3341)
  Directional -> Accuracy: 0.6170, MCC: 0.2002, F1: 0.2500

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.68122 | val 0.71205
  Epoch 016 - train 0.64396 | val 0.71771
  Classification -> best τ=0.560 (val F1=0.2057)
  Directional -> Accuracy: 0.5581, MCC: 0.1656, F1: 0.5366

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.71011 | val 0.71144
  Epoch 016 - train 0.66119 | val 0.69224
  Classification -> best τ=0.385 (val F1=0.2829)
  Directional -> Accuracy: 0.5000, MCC: 0.0382, F1: 0.4314

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.66433 | val 0.81205
  Epoch 018 - train 0.64117 | val 1.01731
  Classification -> best τ=0.510 (val F1=0.2924)
  Directional -> Accuracy: 0.5714, MCC: 0.1718, F1: 0.7188

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.70105 | val 1.12790
  Epoch 011 - train 0.66759 | val 1.07056
  Classification -> best τ=0.590 (val F1=0.2112)
  Directional -> Accuracy: 0.5682, MCC: 0.1438, F1: 0.6275

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.74151 | val 0.70625
  Epoch 014 - train 0.74051 | val 0.78057
  Classification -> best τ=0.620 (val F1=0.2498)
  Directional -> Accuracy: 0.4773, MCC: -0.0682, F1: 0.5490

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.66677 | val 0.67975
  Epoch 019 - train 0.62360 | val 0.89630
  Classification -> best τ=0.450 (val F1=0.3605)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.68165 | val 0.70437
  Epoch 014 - train 0.69208 | val 0.87822
  Classification -> best τ=0.610 (val F1=0.2739)
  Directional -> Accuracy: 0.4324, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.71203 | val 0.69228
  Epoch 020 - train 0.59036 | val 0.88968
  Classification -> best τ=0.425 (val F1=0.3973)
  Directional -> Accuracy: 0.5789, MCC: 0.2037, F1: 0.6800

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.68558 | val 0.90563
  Epoch 011 - train 0.66717 | val 0.99036
  Classification -> best τ=0.465 (val F1=0.2922)
  Directional -> Accuracy: 0.4889, MCC: -0.0714, F1: 0.2581

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.63260 | val 0.80777
  Epoch 011 - train 0.62662 | val 0.70379
  Classification -> best τ=0.505 (val F1=0.3126)
  Directional -> Accuracy: 0.6418, MCC: 0.2704, F1: 0.6842

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.76608 | val 0.67339
  Epoch 020 - train 0.60688 | val 0.75497
  Classification -> best τ=0.600 (val F1=0.3337)
  Directional -> Accuracy: 0.6047, MCC: 0.2739, F1: 0.4516

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.67427 | val 0.71455
  Epoch 011 - train 0.63261 | val 0.68430
  Classification -> best τ=0.395 (val F1=0.1851)
  Directional -> Accuracy: 0.4912, MCC: -0.0075, F1: 0.5246

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.65042 | val 0.70661
  Epoch 015 - train 0.62620 | val 1.16839
  Classification -> best τ=0.505 (val F1=0.5961)
  Directional -> Accuracy: 0.5745, MCC: -0.0074, F1: 0.7059

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 16). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.68819 | val 0.88274
  Epoch 011 - train 0.59053 | val 0.81439
  Classification -> best τ=0.525 (val F1=0.2888)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.76200 | val 0.70422
  Epoch 012 - train 0.81545 | val 0.73188
  Classification -> best τ=0.445 (val F1=0.1870)
  Directional -> Accuracy: 0.4359, MCC: -0.1903, F1: 0.5600

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 16). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.64677 | val 0.87859
  Epoch 015 - train 0.68237 | val 1.33536
  Classification -> best τ=0.405 (val F1=0.3006)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.72448 | val 0.96410
  Epoch 011 - train 0.68592 | val 0.88097
  Classification -> best τ=0.515 (val F1=0.1733)
  Directional -> Accuracy: 0.5106, MCC: 0.0509, F1: 0.2581

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.65654 | val 0.90001
  Epoch 011 - train 0.63314 | val 0.92285
  Classification -> best τ=0.485 (val F1=0.2500)
  Directional -> Accuracy: 0.6000, MCC: 0.1717, F1: 0.6786

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.68057 | val 0.67436
  Epoch 019 - train 0.67593 | val 0.69062
  Classification -> best τ=0.525 (val F1=0.4880)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.67524 | val 0.79318
  Epoch 013 - train 0.72304 | val 1.48575
  Classification -> best τ=0.610 (val F1=0.1602)
  Directional -> Accuracy: 0.5965, MCC: 0.3001, F1: 0.4651

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.66474 | val 1.41530
  Epoch 011 - train 0.64309 | val 1.18937
  Classification -> best τ=0.610 (val F1=0.2667)
  Directional -> Accuracy: 0.5439, MCC: 0.0928, F1: 0.5517

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.68591 | val 1.33206
  Epoch 015 - train 0.62712 | val 4.07420
  Classification -> best τ=0.420 (val F1=0.3164)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.69332 | val 1.14885
  Epoch 011 - train 0.67215 | val 2.00038
  Classification -> best τ=0.500 (val F1=0.1758)
  Directional -> Accuracy: 0.5263, MCC: 0.1360, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.67529 | val 0.99194
  Epoch 011 - train 0.67939 | val 0.69810

[I 2026-02-25 00:35:23,813] Trial 101 finished with value: 0.2743478286595382 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 15, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 32, 'learning_rate': 0.006677220411355307, 'weight_decay': 1.1933529388755444e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.7405233237762274, 'early_stopping_min_delta': 0.000875657230146748}. Best is trial 32 with value: 0.2908549754956826.

  Classification -> best τ=0.515 (val F1=0.2132)
  Directional -> Accuracy: 0.4355, MCC: -0.1816, F1: 0.1860

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2743478286595382
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 15
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.73099 | val 0.67837
  Epoch 017 - train 0.70320 | val 0.71693
  Classification -> best τ=0.430 (val F1=0.3131)
  Directional -> Accuracy: 0.4935, MCC: -0.0394, F1: 0.3810

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.63213 | val 0.79461
  Epoch 015 - train 0.61395 | val 1.25111
  Classification -> best τ=0.405 (val F1=0.3397)
  Directional -> Accuracy: 0.5870, MCC: 0.1313, F1: 0.6780

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 16). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.69833 | val 0.87544
  Epoch 011 - train 0.69120 | val 0.85546
  Classification -> best τ=0.635 (val F1=0.2892)
  Directional -> Accuracy: 0.4583, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.68166 | val 0.86177
  Epoch 020 - train 0.70645 | val 1.17012
  Epoch 021 - train 0.71089 | val 1.30316
  Classification -> best τ=0.595 (val F1=0.3154)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.63366 | val 1.02483
  Epoch 013 - train 0.68587 | val 0.94433
  Classification -> best τ=0.480 (val F1=0.4357)
  Directional -> Accuracy: 0.7115, MCC: 0.4182, F1: 0.7368

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.64579 | val 0.73839
  Epoch 012 - train 0.71290 | val 1.09256
  Classification -> best τ=0.505 (val F1=0.2485)
  Directional -> Accuracy: 0.5208, MCC: 0.0449, F1: 0.4103

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.69651 | val 0.72954
  Epoch 012 - train 0.71908 | val 0.81177
  Classification -> best τ=0.510 (val F1=0.1846)
  Directional -> Accuracy: 0.4429, MCC: 0.1132, F1: 0.5806

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 16). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.67720 | val 2.34883
  Epoch 012 - train 0.68540 | val 2.60318
  Classification -> best τ=0.545 (val F1=0.3280)
  Directional -> Accuracy: 0.4889, MCC: -0.0885, F1: 0.3030

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.69500 | val 0.65386
  Epoch 016 - train 0.65422 | val 0.99833
  Classification -> best τ=0.625 (val F1=0.4315)
  Directional -> Accuracy: 0.6098, MCC: 0.1590, F1: 0.4667

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 16). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 16). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.68200 | val 2.92833
  Epoch 012 - train 0.67957 | val 0.72165
  Classification -> best τ=0.390 (val F1=0.2325)
  Directional -> Accuracy: 0.4366, MCC: 0.0000, F1: 0.6078

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.71843 | val 1.15882
  Epoch 013 - train 0.66541 | val 0.97352
  Classification -> best τ=0.365 (val F1=0.2221)
  Directional -> Accuracy: 0.5686, MCC: 0.2143, F1: 0.1538

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.68808 | val 0.69012
  Epoch 013 - train 0.66771 | val 0.68985
  Classification -> best τ=0.600 (val F1=0.2701)
  Directional -> Accuracy: 0.7119, MCC: 0.4758, F1: 0.6383

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.64330 | val 1.21068
  Epoch 014 - train 0.64271 | val 0.85015
  Classification -> best τ=0.575 (val F1=0.0809)
  Directional -> Accuracy: 0.5814, MCC: 0.1240, F1: 0.1818

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.68280 | val 0.70605
  Epoch 018 - train 0.65566 | val 0.65283
  Classification -> best τ=0.225 (val F1=0.3734)
  Directional -> Accuracy: 0.5410, MCC: 0.1155, F1: 0.6744

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.68227 | val 1.46237
  Epoch 013 - train 0.65072 | val 2.41154
  Classification -> best τ=0.625 (val F1=0.1625)
  Directional -> Accuracy: 0.5094, MCC: -0.1310, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.67020 | val 0.93753
  Epoch 011 - train 0.68767 | val 0.81718
  Classification -> best τ=0.475 (val F1=0.4187)
  Directional -> Accuracy: 0.6429, MCC: 0.3329, F1: 0.7475

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.70230 | val 1.00713
  Epoch 012 - train 0.65313 | val 1.17590
  Classification -> best τ=0.575 (val F1=0.0111)
  Directional -> Accuracy: 0.5667, MCC: 0.0014, F1: 0.6905

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.71510 | val 1.78746
  Epoch 013 - train 0.66614 | val 1.07176
  Classification -> best τ=0.400 (val F1=0.1217)
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.66571 | val 0.69291
  Epoch 020 - train 0.68767 | val 1.04779
  Epoch 028 - train 0.69487 | val 0.74523
  Classification -> best τ=0.410 (val F1=0.2215)
  Directional -> Accuracy: 0.4545, MCC: 0.0247, F1: 0.3077

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 16). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.68056 | val 0.83551
  Epoch 012 - train 0.71587 | val 0.88295
  Classification -> best τ=0.515 (val F1=0.2332)
  Directional -> Accuracy: 0.4605, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.66986 | val 0.71618
  Epoch 012 - train 0.62304 | val 0.96376
  Classification -> best τ=0.495 (val F1=0.3833)
  Directional -> Accuracy: 0.4167, MCC: 0.0000, F1: 0.2632

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.69843 | val 0.80689
  Epoch 016 - train 0.66586 | val 1.38342
  Classification -> best τ=0.515 (val F1=0.2425)
  Directional -> Accuracy: 0.5606, MCC: 0.1226, F1: 0.5246

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.70403 | val 0.68796
  Epoch 015 - train 0.65939 | val 0.88929
  Classification -> best τ=0.770 (val F1=0.3198)
  Directional -> Accuracy: 0.5517, MCC: 0.1960, F1: 0.4583

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.70336 | val 2.32880
  Epoch 011 - train 0.67208 | val 3.33668
  Classification -> best τ=0.490 (val F1=0.1073)
  Directional -> Accuracy: 0.5455, MCC: 0.0814, F1: 0.4828

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.69753 | val 0.64939
  Epoch 018 - train 0.70822 | val 0.94399
  Classification -> best τ=0.545 (val F1=0.5476)
  Directional -> Accuracy: 0.5179, MCC: 0.1373, F1: 0.3415

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.60286 | val 0.72774
  Epoch 012 - train 0.61517 | val 0.83529
  Classification -> best τ=0.640 (val F1=0.4341)
  Directional -> Accuracy: 0.5745, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.67613 | val 0.77975
  Epoch 014 - train 0.68036 | val 0.80164
  Classification -> best τ=0.555 (val F1=0.0364)
  Directional -> Accuracy: 0.5814, MCC: 0.1270, F1: 0.6538

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.74923 | val 0.67833
  Epoch 020 - train 0.65615 | val 0.82816
  Epoch 025 - train 0.66509 | val 0.72373
  Classification -> best τ=0.445 (val F1=0.3355)
  Directional -> Accuracy: 0.5000, MCC: 0.0473, F1: 0.4082

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.74027 | val 0.70501
  Epoch 020 - train 0.75732 | val 0.72911
  Epoch 024 - train 0.64617 | val 0.90517
  Classification -> best τ=0.550 (val F1=0.4193)
  Directional -> Accuracy: 0.4762, MCC: -0.0214, F1: 0.4211

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.64781 | val 0.99193
  Epoch 011 - train 0.75794 | val 1.13522
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.71461 | val 0.82114
  Epoch 012 - train 0.68913 | val 0.79321
  Classification -> best τ=0.370 (val F1=0.2374)
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.65895 | val 0.80758
  Epoch 011 - train 0.64440 | val 0.82683
  Classification -> best τ=0.365 (val F1=0.3304)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.67878 | val 0.75489
  Epoch 015 - train 0.69252 | val 0.73703
  Classification -> best τ=0.410 (val F1=0.3351)
  Directional -> Accuracy: 0.5135, MCC: 0.0903, F1: 0.4375

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.61934 | val 0.78895
  Epoch 011 - train 0.66073 | val 0.84639
  Classification -> best τ=0.450 (val F1=0.0543)
  Directional -> Accuracy: 0.5526, MCC: 0.2357, F1: 0.6909

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.72331 | val 0.75452
  Epoch 016 - train 0.64191 | val 1.22935
  Classification -> best τ=0.460 (val F1=0.2359)
  Directional -> Accuracy: 0.3778, MCC: -0.2373, F1: 0.4615

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.70948 | val 0.76470
  Epoch 014 - train 0.61186 | val 0.82865
  Classification -> best τ=0.380 (val F1=0.3166)
  Directional -> Accuracy: 0.4925, MCC: 0.0538, F1: 0.3929

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.71819 | val 0.71022
  Epoch 020 - train 0.65199 | val 0.69286
  Epoch 024 - train 0.62270 | val 0.72134
  Classification -> best τ=0.385 (val F1=0.3311)
  Directional -> Accuracy: 0.6744, MCC: 0.3810, F1: 0.6111

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.69837 | val 0.81578
  Epoch 011 - train 0.66361 | val 0.75985
  Classification -> best τ=0.375 (val F1=0.3204)
  Directional -> Accuracy: 0.5088, MCC: 0.0681, F1: 0.6216

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.70492 | val 0.85963
  Epoch 014 - train 0.68619 | val 0.88181
  Classification -> best τ=0.515 (val F1=0.4460)
  Directional -> Accuracy: 0.4681, MCC: -0.0301, F1: 0.4898

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 16). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.64964 | val 1.02073
  Epoch 013 - train 0.59824 | val 1.78718
  Classification -> best τ=0.350 (val F1=0.2537)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.67615 | val 0.82647
  Epoch 012 - train 0.65621 | val 0.82312
  Classification -> best τ=0.470 (val F1=0.3893)
  Directional -> Accuracy: 0.4359, MCC: -0.2156, F1: 0.5769

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 16). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.70560 | val 0.84328
  Epoch 013 - train 0.67895 | val 0.76637
  Classification -> best τ=0.525 (val F1=0.2930)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.66299 | val 0.70531
  Epoch 020 - train 0.64428 | val 0.72922
  Epoch 027 - train 0.61456 | val 1.22562
  Classification -> best τ=0.540 (val F1=0.2544)
  Directional -> Accuracy: 0.5532, MCC: 0.1704, F1: 0.3226

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.68097 | val 0.95284
  Epoch 012 - train 0.57259 | val 1.24718
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.73764 | val 0.69047
  Epoch 013 - train 0.69547 | val 0.80239
  Classification -> best τ=0.500 (val F1=0.4497)
  Directional -> Accuracy: 0.3750, MCC: 0.1175, F1: 0.5283

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.71070 | val 0.93483
  Epoch 012 - train 0.75895 | val 0.77955
  Classification -> best τ=0.645 (val F1=0.2178)
  Directional -> Accuracy: 0.4561, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.68508 | val 1.45024
  Epoch 014 - train 0.72298 | val 1.62949
  Classification -> best τ=0.535 (val F1=0.3957)
  Directional -> Accuracy: 0.5614, MCC: 0.1807, F1: 0.6479

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.66959 | val 0.85020
  Epoch 014 - train 0.72404 | val 0.87299
  Classification -> best τ=0.530 (val F1=0.1154)
  Directional -> Accuracy: 0.4815, MCC: 0.0000, F1: 0.0000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.70456 | val 1.11048
  Epoch 011 - train 0.68478 | val 1.25896
  Classification -> best τ=0.450 (val F1=0.0154)
  Directional -> Accuracy: 0.5263, MCC: 0.0514, F1: 0.6301

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.68543 | val 0.75488

[I 2026-02-25 00:37:20,489] Trial 102 finished with value: 0.26632797472448094 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 15, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 32, 'learning_rate': 0.008457237921511337, 'weight_decay': 1.078961680166286e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.7368783755172321, 'early_stopping_min_delta': 0.0015433917314273174}. Best is trial 32 with value: 0.2908549754956826.

  Epoch 012 - train 0.66014 | val 1.18782
  Classification -> best τ=0.355 (val F1=0.2653)
  Directional -> Accuracy: 0.5161, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.26632797472448094
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 15
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.64924 | val 0.65875
  Epoch 020 - train 0.64624 | val 0.89519
  Epoch 029 - train 0.62711 | val 0.91310
  Classification -> best τ=0.590 (val F1=0.2931)
  Directional -> Accuracy: 0.4026, MCC: -0.1862, F1: 0.4103

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.59994 | val 1.01970
  Epoch 016 - train 0.63721 | val 1.27654
  Classification -> best τ=0.470 (val F1=0.2918)
  Directional -> Accuracy: 0.6304, MCC: 0.2287, F1: 0.7119

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 16). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.68895 | val 0.79886
  Epoch 012 - train 0.68302 | val 0.75100
  Classification -> best τ=0.510 (val F1=0.3143)
  Directional -> Accuracy: 0.4375, MCC: -0.1843, F1: 0.5574

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.68820 | val 1.84667
  Epoch 013 - train 0.65479 | val 2.01964
  Classification -> best τ=0.455 (val F1=0.1799)
  Directional -> Accuracy: 0.5200, MCC: 0.0465, F1: 0.5263

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.56981 | val 1.10846
  Epoch 016 - train 0.57273 | val 1.53094
  Classification -> best τ=0.430 (val F1=0.4276)
  Directional -> Accuracy: 0.7308, MCC: 0.4565, F1: 0.7586

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.61774 | val 0.76515
  Epoch 013 - train 0.54285 | val 0.91696
  Classification -> best τ=0.480 (val F1=0.2270)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.71691 | val 0.70999
  Epoch 011 - train 0.68891 | val 0.73428
  Classification -> best τ=0.420 (val F1=0.2381)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.5714

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 16). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.59401 | val 1.67604
  Epoch 011 - train 0.55450 | val 1.50927
  Classification -> best τ=0.610 (val F1=0.2820)
  Directional -> Accuracy: 0.4444, MCC: -0.0055, F1: 0.5614

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.65987 | val 0.64603
  Epoch 018 - train 0.58945 | val 0.64088
  Classification -> best τ=0.660 (val F1=0.4690)
  Directional -> Accuracy: 0.5854, MCC: -0.1720, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 16). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 16). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.65799 | val 0.99763
  Epoch 012 - train 0.65780 | val 0.87848
  Classification -> best τ=0.520 (val F1=0.2826)
  Directional -> Accuracy: 0.4930, MCC: 0.0462, F1: 0.5610

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.62943 | val 1.65490
  Epoch 014 - train 0.64113 | val 1.10036
  Classification -> best τ=0.380 (val F1=0.2485)
  Directional -> Accuracy: 0.6275, MCC: 0.2489, F1: 0.5778

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.61885 | val 0.96637
  Epoch 012 - train 0.66985 | val 0.75728
  Classification -> best τ=0.540 (val F1=0.2029)
  Directional -> Accuracy: 0.5763, MCC: 0.1644, F1: 0.5098

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.62374 | val 1.00111
  Epoch 012 - train 0.67817 | val 1.39205
  Classification -> best τ=0.425 (val F1=0.2454)
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.64939 | val 1.28701
  Epoch 015 - train 0.64784 | val 0.93821
  Classification -> best τ=0.345 (val F1=0.3383)
  Directional -> Accuracy: 0.4918, MCC: -0.0549, F1: 0.6437

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.66605 | val 2.66698
  Epoch 011 - train 0.58924 | val 3.57485
  Classification -> best τ=0.525 (val F1=0.2173)
  Directional -> Accuracy: 0.5094, MCC: 0.0990, F1: 0.6389

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.63521 | val 0.92651
  Epoch 012 - train 0.62921 | val 0.86833
  Classification -> best τ=0.410 (val F1=0.2030)
  Directional -> Accuracy: 0.5714, MCC: 0.1447, F1: 0.7115

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.70305 | val 0.94345
  Epoch 012 - train 0.64066 | val 1.14780
  Classification -> best τ=0.305 (val F1=0.1920)
  Directional -> Accuracy: 0.6167, MCC: 0.0000, F1: 0.7629

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.63680 | val 2.29844
  Epoch 011 - train 0.68249 | val 1.74198
  Classification -> best τ=0.475 (val F1=0.1898)
  Directional -> Accuracy: 0.5921, MCC: 0.1221, F1: 0.6804

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.64599 | val 0.71250
  Epoch 014 - train 0.64284 | val 1.33531
  Classification -> best τ=0.460 (val F1=0.2518)
  Directional -> Accuracy: 0.4848, MCC: 0.1510, F1: 0.2917

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 16). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.65078 | val 0.71420
  Epoch 013 - train 0.65803 | val 0.75554
  Classification -> best τ=0.600 (val F1=0.3454)
  Directional -> Accuracy: 0.4605, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.64436 | val 0.78104
  Epoch 019 - train 0.56646 | val 2.39008
  Classification -> best τ=0.755 (val F1=0.3963)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.65477 | val 1.57577
  Epoch 011 - train 0.64991 | val 1.22908
  Classification -> best τ=0.510 (val F1=0.1650)
  Directional -> Accuracy: 0.5303, MCC: 0.0928, F1: 0.2439

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.63216 | val 1.09001
  Epoch 011 - train 0.64343 | val 1.07665
  Classification -> best τ=0.580 (val F1=0.3088)
  Directional -> Accuracy: 0.5000, MCC: 0.1008, F1: 0.3556

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.65281 | val 1.59557
  Epoch 012 - train 0.62260 | val 2.46985
  Classification -> best τ=0.450 (val F1=0.2453)
  Directional -> Accuracy: 0.5455, MCC: 0.1149, F1: 0.5946

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.69075 | val 0.64327
  Epoch 019 - train 0.60977 | val 0.96915
  Classification -> best τ=0.480 (val F1=0.3970)
  Directional -> Accuracy: 0.5536, MCC: 0.2064, F1: 0.4186

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.59573 | val 0.82670
  Epoch 011 - train 0.57135 | val 0.98024
  Classification -> best τ=0.490 (val F1=0.2339)
  Directional -> Accuracy: 0.6383, MCC: 0.3240, F1: 0.6531

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.67049 | val 0.96717
  Epoch 014 - train 0.66656 | val 0.86756
  Classification -> best τ=0.510 (val F1=0.2603)
  Directional -> Accuracy: 0.5814, MCC: 0.0528, F1: 0.7188

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.65520 | val 0.74766
  Epoch 017 - train 0.61287 | val 0.86461
  Classification -> best τ=0.220 (val F1=0.2673)
  Directional -> Accuracy: 0.5345, MCC: 0.1948, F1: 0.3415

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.67927 | val 0.72209
  Epoch 020 - train 0.62001 | val 0.70355
  Epoch 023 - train 0.60758 | val 0.66410
  Classification -> best τ=0.565 (val F1=0.4193)
  Directional -> Accuracy: 0.4524, MCC: -0.0751, F1: 0.4103

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.69613 | val 2.94719
  Epoch 012 - train 0.58356 | val 4.79527
  Classification -> best τ=0.645 (val F1=0.1869)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.3889

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.67012 | val 0.71874
  Epoch 013 - train 0.66162 | val 0.82483
  Classification -> best τ=0.670 (val F1=0.1495)
  Directional -> Accuracy: 0.5455, MCC: 0.1208, F1: 0.5000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.62613 | val 0.73902
  Epoch 012 - train 0.63369 | val 1.14922
  Classification -> best τ=0.410 (val F1=0.3589)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.64569 | val 1.03134
  Epoch 014 - train 0.63248 | val 2.05896
  Classification -> best τ=0.300 (val F1=0.3074)
  Directional -> Accuracy: 0.5541, MCC: 0.2008, F1: 0.4590

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.60161 | val 0.82627
  Epoch 015 - train 0.60339 | val 0.79332
  Classification -> best τ=0.505 (val F1=0.2496)
  Directional -> Accuracy: 0.5263, MCC: 0.0679, F1: 0.3077

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.61460 | val 0.86568
  Epoch 016 - train 0.55242 | val 1.53196
  Classification -> best τ=0.590 (val F1=0.2417)
  Directional -> Accuracy: 0.5111, MCC: -0.0328, F1: 0.2143

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.58886 | val 0.72780
  Epoch 013 - train 0.60749 | val 0.75723
  Classification -> best τ=0.465 (val F1=0.3572)
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.62147 | val 0.71026
  Epoch 020 - train 0.56329 | val 0.70433
  Epoch 026 - train 0.52337 | val 0.76938
  Classification -> best τ=0.560 (val F1=0.3914)
  Directional -> Accuracy: 0.6744, MCC: 0.4004, F1: 0.5882

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.61979 | val 0.83869
  Epoch 012 - train 0.60768 | val 0.88657
  Classification -> best τ=0.415 (val F1=0.2261)
  Directional -> Accuracy: 0.5614, MCC: 0.1968, F1: 0.6575

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.63473 | val 0.93477
  Epoch 014 - train 0.62915 | val 0.92066
  Classification -> best τ=0.375 (val F1=0.3516)
  Directional -> Accuracy: 0.6170, MCC: 0.0508, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 16). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.64849 | val 0.67476
  Epoch 020 - train 0.52630 | val 1.36620
  Classification -> best τ=0.195 (val F1=0.4667)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.66552 | val 0.81616
  Epoch 012 - train 0.67788 | val 0.78136
  Classification -> best τ=0.465 (val F1=0.1870)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.7000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 16). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.68636 | val 0.74313
  Epoch 015 - train 0.62267 | val 1.70654
  Classification -> best τ=0.510 (val F1=0.3152)
  Directional -> Accuracy: 0.5263, MCC: 0.1644, F1: 0.6786

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.67322 | val 0.77868
  Epoch 011 - train 0.68815 | val 0.81826
  Classification -> best τ=0.500 (val F1=0.3119)
  Directional -> Accuracy: 0.5319, MCC: 0.1036, F1: 0.3125

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.62762 | val 1.14333
  Epoch 012 - train 0.68750 | val 1.23485
  Classification -> best τ=0.500 (val F1=0.1387)
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.59125 | val 0.66976
  Epoch 020 - train 0.60008 | val 1.00334
  Classification -> best τ=0.495 (val F1=0.3568)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.62718 | val 1.71791
  Epoch 014 - train 0.64532 | val 1.14560
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5439, MCC: 0.0000, F1: 0.7045

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.68943 | val 1.82469
  Epoch 011 - train 0.60228 | val 2.16795
  Classification -> best τ=0.420 (val F1=0.3147)
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.64580 | val 1.65880
  Epoch 011 - train 0.70599 | val 2.10075
  Classification -> best τ=0.420 (val F1=0.3085)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.60601 | val 1.46188
  Epoch 012 - train 0.63360 | val 1.13667
  Classification -> best τ=0.620 (val F1=0.1990)
  Directional -> Accuracy: 0.4561, MCC: -0.1538, F1: 0.6076

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.63244 | val 0.99832
  Epoch 011 - train 0.62212 | val 0.94652

[I 2026-02-25 00:39:13,075] Trial 103 finished with value: 0.2760780708204861 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 15, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 0.00621628109062194, 'weight_decay': 6.964315422697748e-06, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.842988817588821, 'early_stopping_min_delta': 0.0007629989593690745}. Best is trial 32 with value: 0.2908549754956826.

  Classification -> best τ=0.380 (val F1=0.2517)
  Directional -> Accuracy: 0.4839, MCC: 0.0000, F1: 0.6522

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2760780708204861
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 15
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.68357 | val 0.66707
  Epoch 020 - train 0.62399 | val 0.73036
  Classification -> best τ=0.430 (val F1=0.2058)
  Directional -> Accuracy: 0.4156, MCC: -0.1828, F1: 0.5794

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.66722 | val 0.77300
  Epoch 014 - train 0.62635 | val 0.82346
  Classification -> best τ=0.465 (val F1=0.1700)
  Directional -> Accuracy: 0.5217, MCC: 0.1036, F1: 0.4500

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 16). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.70292 | val 0.79182
  Epoch 017 - train 0.67202 | val 0.77554
  Classification -> best τ=0.605 (val F1=0.3615)
  Directional -> Accuracy: 0.5833, MCC: 0.2992, F1: 0.4118

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.66552 | val 1.17084
  Epoch 011 - train 0.64253 | val 1.21955
  Classification -> best τ=0.460 (val F1=0.1923)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.61420 | val 0.76291
  Epoch 013 - train 0.66407 | val 0.78992
  Classification -> best τ=0.520 (val F1=0.3237)
  Directional -> Accuracy: 0.6154, MCC: 0.2222, F1: 0.6552

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.61167 | val 0.94296
  Epoch 017 - train 0.56487 | val 0.74582
  Classification -> best τ=0.405 (val F1=0.3254)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.70914 | val 0.69637
  Epoch 020 - train 0.65467 | val 0.71838
  Epoch 024 - train 0.65419 | val 0.94350
  Classification -> best τ=0.340 (val F1=0.2774)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.5714

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 16). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.66034 | val 1.91380
  Epoch 011 - train 0.65315 | val 1.83530
  Classification -> best τ=0.560 (val F1=0.1048)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.68126 | val 0.94394
  Epoch 016 - train 0.70028 | val 1.21842
  Classification -> best τ=0.565 (val F1=0.3877)
  Directional -> Accuracy: 0.4634, MCC: -0.0152, F1: 0.4500

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 16). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 16). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.68992 | val 0.85295
  Epoch 015 - train 0.63351 | val 0.91567
  Classification -> best τ=0.500 (val F1=0.2391)
  Directional -> Accuracy: 0.4366, MCC: -0.0913, F1: 0.4872

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.68015 | val 0.99531
  Epoch 012 - train 0.63521 | val 0.95806
  Classification -> best τ=0.545 (val F1=0.2007)
  Directional -> Accuracy: 0.6078, MCC: 0.2415, F1: 0.3750

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.65272 | val 0.96108
  Epoch 011 - train 0.64716 | val 0.83989
  Classification -> best τ=0.475 (val F1=0.0921)
  Directional -> Accuracy: 0.5254, MCC: 0.0811, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.71576 | val 1.54348
  Epoch 014 - train 0.65276 | val 1.41009
  Classification -> best τ=0.425 (val F1=0.2719)
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.67682 | val 0.63512
  Epoch 017 - train 0.67945 | val 0.85921
  Classification -> best τ=0.250 (val F1=0.2928)
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.64428 | val 2.62104
  Epoch 013 - train 0.67471 | val 3.36346
  Classification -> best τ=0.515 (val F1=0.2798)
  Directional -> Accuracy: 0.4717, MCC: -0.0441, F1: 0.5172

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.68661 | val 0.72856
  Epoch 014 - train 0.64035 | val 0.71173
  Classification -> best τ=0.555 (val F1=0.3701)
  Directional -> Accuracy: 0.6000, MCC: 0.1848, F1: 0.6585

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.68252 | val 1.16938
  Epoch 011 - train 0.63813 | val 1.17283
  Classification -> best τ=0.450 (val F1=0.0149)
  Directional -> Accuracy: 0.6000, MCC: 0.1265, F1: 0.6923

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.67101 | val 0.93852
  Epoch 011 - train 0.70560 | val 0.94372
  Classification -> best τ=0.530 (val F1=0.1236)
  Directional -> Accuracy: 0.5395, MCC: 0.0192, F1: 0.6316

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.68193 | val 0.72294
  Epoch 015 - train 0.63520 | val 1.08397
  Classification -> best τ=0.355 (val F1=0.2778)
  Directional -> Accuracy: 0.5303, MCC: 0.2056, F1: 0.4151

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 16). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.67033 | val 0.68986
  Epoch 012 - train 0.63730 | val 0.77239
  Classification -> best τ=0.375 (val F1=0.2569)
  Directional -> Accuracy: 0.5395, MCC: 0.1325, F1: 0.4262

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.66069 | val 1.53071
  Epoch 014 - train 0.59765 | val 1.07520
  Classification -> best τ=0.550 (val F1=0.2868)
  Directional -> Accuracy: 0.4375, MCC: 0.2000, F1: 0.1818

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.66962 | val 0.98451
  Epoch 011 - train 0.68975 | val 1.11387
  Classification -> best τ=0.490 (val F1=0.1677)
  Directional -> Accuracy: 0.6515, MCC: 0.3101, F1: 0.6849

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.66334 | val 0.99574
  Epoch 011 - train 0.68121 | val 0.95709
  Classification -> best τ=0.555 (val F1=0.3198)
  Directional -> Accuracy: 0.3966, MCC: -0.1753, F1: 0.0541

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.64103 | val 2.30591
  Epoch 011 - train 0.63408 | val 2.58797
  Classification -> best τ=0.380 (val F1=0.1664)
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.69358 | val 0.71217
  Epoch 013 - train 0.65790 | val 0.74518
  Classification -> best τ=0.565 (val F1=0.2796)
  Directional -> Accuracy: 0.4464, MCC: -0.0207, F1: 0.0606

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.68602 | val 0.82533
  Epoch 014 - train 0.60910 | val 0.93847
  Classification -> best τ=0.470 (val F1=0.3721)
  Directional -> Accuracy: 0.5532, MCC: -0.0178, F1: 0.1600

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.69206 | val 0.67764
  Epoch 020 - train 0.65776 | val 0.85395
  Epoch 021 - train 0.63629 | val 0.98035
  Classification -> best τ=0.595 (val F1=0.3078)
  Directional -> Accuracy: 0.5349, MCC: 0.0905, F1: 0.5455

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.64409 | val 0.79368
  Epoch 015 - train 0.67589 | val 0.71221
  Classification -> best τ=0.375 (val F1=0.1780)
  Directional -> Accuracy: 0.5345, MCC: 0.1948, F1: 0.3415

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.77326 | val 0.69983
  Epoch 011 - train 0.78415 | val 0.70170
  Classification -> best τ=0.540 (val F1=0.2425)
  Directional -> Accuracy: 0.5714, MCC: 0.1090, F1: 0.7000

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.72652 | val 0.85340
  Epoch 011 - train 0.67840 | val 0.84642
  Classification -> best τ=0.575 (val F1=0.1869)
  Directional -> Accuracy: 0.4773, MCC: -0.0621, F1: 0.2069

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.72437 | val 0.75746
  Epoch 017 - train 0.64140 | val 0.70865
  Classification -> best τ=0.490 (val F1=0.2374)
  Directional -> Accuracy: 0.5227, MCC: -0.0658, F1: 0.6769

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.59609 | val 0.85624
  Epoch 011 - train 0.61965 | val 0.95200
  Classification -> best τ=0.485 (val F1=0.3245)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.65420 | val 0.68635
  Epoch 018 - train 0.64223 | val 1.40300
  Classification -> best τ=0.345 (val F1=0.3470)
  Directional -> Accuracy: 0.5676, MCC: 0.1562, F1: 0.5676

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.71710 | val 0.80395
  Epoch 011 - train 0.58596 | val 0.87504
  Classification -> best τ=0.485 (val F1=0.3125)
  Directional -> Accuracy: 0.5263, MCC: 0.0679, F1: 0.6400

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.66854 | val 0.97014
  Epoch 011 - train 0.62981 | val 1.03071
  Classification -> best τ=0.505 (val F1=0.2500)
  Directional -> Accuracy: 0.5556, MCC: 0.2359, F1: 0.6667

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.67164 | val 0.72079
  Epoch 016 - train 0.62152 | val 0.74233
  Classification -> best τ=0.325 (val F1=0.3431)
  Directional -> Accuracy: 0.5970, MCC: 0.3017, F1: 0.5091

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.69393 | val 0.69705
  Epoch 013 - train 0.66752 | val 0.80344
  Classification -> best τ=0.495 (val F1=0.3493)
  Directional -> Accuracy: 0.6744, MCC: 0.3810, F1: 0.6111

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.63858 | val 0.73448
  Epoch 012 - train 0.62653 | val 0.74259
  Classification -> best τ=0.460 (val F1=0.1672)
  Directional -> Accuracy: 0.4912, MCC: -0.0262, F1: 0.4314

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.66738 | val 0.76194
  Epoch 011 - train 0.63034 | val 0.75916
  Classification -> best τ=0.570 (val F1=0.5895)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 16). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.71470 | val 0.77120
  Epoch 011 - train 0.66645 | val 0.71858
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.70914 | val 0.82412
  Epoch 011 - train 0.78007 | val 0.79663
  Classification -> best τ=0.500 (val F1=0.2707)
  Directional -> Accuracy: 0.6154, MCC: 0.2604, F1: 0.7273

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 16). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.68509 | val 0.71909
  Epoch 016 - train 0.66158 | val 1.04533
  Classification -> best τ=0.335 (val F1=0.4223)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.66436 | val 0.70674
  Epoch 011 - train 0.68645 | val 0.71092
  Classification -> best τ=0.525 (val F1=0.1898)
  Directional -> Accuracy: 0.5319, MCC: 0.0620, F1: 0.6333

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.65380 | val 0.83448
  Epoch 011 - train 0.63255 | val 0.88330
  Classification -> best τ=0.540 (val F1=0.1387)
  Directional -> Accuracy: 0.6000, MCC: 0.1921, F1: 0.7273

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.74035 | val 0.70449
  Epoch 018 - train 0.64080 | val 0.83777
  Classification -> best τ=0.560 (val F1=0.4497)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.68707 | val 0.91062
  Epoch 012 - train 0.66715 | val 1.03126
  Classification -> best τ=0.460 (val F1=0.0447)
  Directional -> Accuracy: 0.5439, MCC: 0.0168, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.65098 | val 1.71757
  Epoch 012 - train 0.64384 | val 1.58354
  Classification -> best τ=0.415 (val F1=0.2554)
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.63593 | val 1.44893
  Epoch 011 - train 0.67535 | val 1.45762
  Classification -> best τ=0.490 (val F1=0.1508)
  Directional -> Accuracy: 0.5556, MCC: 0.1520, F1: 0.6923

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.66529 | val 1.31180
  Epoch 012 - train 0.64955 | val 1.21169
  Classification -> best τ=0.520 (val F1=0.2112)
  Directional -> Accuracy: 0.4737, MCC: -0.1083, F1: 0.6250

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.68344 | val 0.71712

[I 2026-02-25 00:41:02,738] Trial 104 finished with value: 0.25265869033602467 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 15, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 32, 'learning_rate': 0.0037925413330322628, 'weight_decay': 7.91727957090966e-06, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.855700577363505, 'early_stopping_min_delta': 0.0005790275758514238}. Best is trial 32 with value: 0.2908549754956826.

  Epoch 014 - train 0.63045 | val 1.02118
  Classification -> best τ=0.475 (val F1=0.3032)
  Directional -> Accuracy: 0.5323, MCC: 0.0836, F1: 0.6027

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.25265869033602467
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 15
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.65941 | val 0.66856
  Epoch 019 - train 0.65516 | val 1.21092
  Classification -> best τ=0.640 (val F1=0.3541)
  Directional -> Accuracy: 0.5195, MCC: -0.0423, F1: 0.1778

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.63768 | val 1.04522
  Epoch 012 - train 0.65100 | val 1.05410
  Classification -> best τ=0.465 (val F1=0.1236)
  Directional -> Accuracy: 0.5652, MCC: 0.0604, F1: 0.6875

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 16). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.66821 | val 0.87353
  Epoch 012 - train 0.68189 | val 0.87688
  Classification -> best τ=0.645 (val F1=0.3625)
  Directional -> Accuracy: 0.4583, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.68007 | val 0.69825
  Epoch 011 - train 0.68504 | val 0.76033
  Classification -> best τ=0.495 (val F1=0.1661)
  Directional -> Accuracy: 0.4933, MCC: 0.1360, F1: 0.1739

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.67398 | val 2.06568
  Epoch 017 - train 0.58799 | val 2.73305
  Classification -> best τ=0.410 (val F1=0.4605)
  Directional -> Accuracy: 0.6923, MCC: 0.3858, F1: 0.7500

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.63525 | val 0.84412
  Epoch 012 - train 0.62660 | val 0.82347
  Classification -> best τ=0.285 (val F1=0.2236)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.70756 | val 0.81607
  Epoch 015 - train 0.69466 | val 0.71145
  Classification -> best τ=0.470 (val F1=0.2957)
  Directional -> Accuracy: 0.4286, MCC: 0.0417, F1: 0.5652

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 16). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.59049 | val 1.67014
  Epoch 011 - train 0.56146 | val 1.85435
  Classification -> best τ=0.605 (val F1=0.3780)
  Directional -> Accuracy: 0.6000, MCC: 0.1691, F1: 0.5000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.67616 | val 0.75889
  Epoch 014 - train 0.61356 | val 0.79206
  Classification -> best τ=0.520 (val F1=0.3877)
  Directional -> Accuracy: 0.3659, MCC: 0.0000, F1: 0.5357

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 16). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 16). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.65638 | val 0.78535
  Epoch 011 - train 0.62780 | val 0.99769
  Classification -> best τ=0.435 (val F1=0.1698)
  Directional -> Accuracy: 0.4366, MCC: -0.0312, F1: 0.5918

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.65466 | val 1.24297
  Epoch 013 - train 0.64148 | val 1.35395
  Classification -> best τ=0.395 (val F1=0.3786)
  Directional -> Accuracy: 0.6471, MCC: 0.3495, F1: 0.4375

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.67041 | val 0.84770
  Epoch 012 - train 0.65512 | val 0.88710
  Classification -> best τ=0.615 (val F1=0.2394)
  Directional -> Accuracy: 0.6102, MCC: 0.2966, F1: 0.4390

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.65302 | val 1.45801
  Epoch 011 - train 0.66332 | val 1.43983
  Classification -> best τ=0.390 (val F1=0.3122)
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.72543 | val 0.62336
  Epoch 018 - train 0.63213 | val 1.03319
  Classification -> best τ=0.350 (val F1=0.3618)
  Directional -> Accuracy: 0.5410, MCC: 0.1035, F1: 0.6667

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.62849 | val 1.24798
  Epoch 011 - train 0.63592 | val 1.23234
  Classification -> best τ=0.580 (val F1=0.2262)
  Directional -> Accuracy: 0.5283, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.62958 | val 0.92693
  Epoch 011 - train 0.64490 | val 0.83281
  Classification -> best τ=0.425 (val F1=0.3100)
  Directional -> Accuracy: 0.6429, MCC: 0.3329, F1: 0.7475

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.70449 | val 0.90154
  Epoch 011 - train 0.64799 | val 0.94988
  Classification -> best τ=0.530 (val F1=0.1259)
  Directional -> Accuracy: 0.3833, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.66706 | val 1.12711
  Epoch 013 - train 0.64257 | val 1.82755
  Classification -> best τ=0.460 (val F1=0.1898)
  Directional -> Accuracy: 0.6053, MCC: 0.2270, F1: 0.6341

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.66227 | val 0.92855
  Epoch 015 - train 0.64566 | val 2.17491
  Classification -> best τ=0.350 (val F1=0.2778)
  Directional -> Accuracy: 0.4848, MCC: -0.0421, F1: 0.5405

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 16). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.67844 | val 0.75296
  Epoch 011 - train 0.67248 | val 0.77996
  Classification -> best τ=0.485 (val F1=0.2270)
  Directional -> Accuracy: 0.4605, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.68985 | val 1.22934
  Epoch 017 - train 0.58487 | val 2.97950
  Classification -> best τ=0.500 (val F1=0.2058)
  Directional -> Accuracy: 0.5208, MCC: -0.1152, F1: 0.6567

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.68001 | val 1.35561
  Epoch 013 - train 0.62565 | val 2.08602
  Classification -> best τ=0.375 (val F1=0.1177)
  Directional -> Accuracy: 0.5152, MCC: 0.1240, F1: 0.6735

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.67983 | val 0.97230
  Epoch 015 - train 0.69169 | val 0.91502
  Classification -> best τ=0.640 (val F1=0.3211)
  Directional -> Accuracy: 0.4655, MCC: 0.0286, F1: 0.2791

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.65563 | val 2.03904
  Epoch 012 - train 0.65885 | val 2.72575
  Classification -> best τ=0.360 (val F1=0.2453)
  Directional -> Accuracy: 0.5606, MCC: 0.1503, F1: 0.6133

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.63968 | val 1.00289
  Epoch 016 - train 0.60805 | val 1.37998
  Classification -> best τ=0.415 (val F1=0.4872)
  Directional -> Accuracy: 0.5357, MCC: 0.1728, F1: 0.3810

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.61994 | val 0.99285
  Epoch 011 - train 0.56994 | val 1.01106
  Classification -> best τ=0.585 (val F1=0.1792)
  Directional -> Accuracy: 0.5745, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.68143 | val 0.71904
  Epoch 014 - train 0.62276 | val 0.69543
  Classification -> best τ=0.575 (val F1=0.1818)
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.68304 | val 0.69354
  Epoch 019 - train 0.59986 | val 0.90661
  Classification -> best τ=0.290 (val F1=0.2472)
  Directional -> Accuracy: 0.5345, MCC: -0.0540, F1: 0.6897

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.74155 | val 0.68924
  Epoch 020 - train 0.59968 | val 0.85110
  Classification -> best τ=0.460 (val F1=0.3974)
  Directional -> Accuracy: 0.5952, MCC: 0.1940, F1: 0.7213

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.63681 | val 1.53823
  Epoch 012 - train 0.61891 | val 1.77673
  Classification -> best τ=0.540 (val F1=0.1869)
  Directional -> Accuracy: 0.5227, MCC: 0.0459, F1: 0.5532

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.64856 | val 0.71664
  Epoch 014 - train 0.64577 | val 1.02528
  Classification -> best τ=0.515 (val F1=0.1506)
  Directional -> Accuracy: 0.5227, MCC: -0.0227, F1: 0.6557

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.64723 | val 0.84595
  Epoch 012 - train 0.55739 | val 1.03863
  Classification -> best τ=0.470 (val F1=0.2617)
  Directional -> Accuracy: 0.5490, MCC: 0.0982, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.67242 | val 1.35006
  Epoch 013 - train 0.66947 | val 1.15526
  Classification -> best τ=0.545 (val F1=0.2739)
  Directional -> Accuracy: 0.4324, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.58207 | val 0.70584
  Epoch 016 - train 0.60914 | val 1.16422
  Classification -> best τ=0.525 (val F1=0.2227)
  Directional -> Accuracy: 0.6842, MCC: 0.3769, F1: 0.7143

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.67221 | val 0.89162
  Epoch 011 - train 0.63711 | val 0.92412
  Classification -> best τ=0.465 (val F1=0.2500)
  Directional -> Accuracy: 0.5778, MCC: 0.1890, F1: 0.6275

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.60739 | val 0.76612
  Epoch 017 - train 0.57043 | val 0.92608
  Classification -> best τ=0.165 (val F1=0.3767)
  Directional -> Accuracy: 0.5821, MCC: 0.1421, F1: 0.6410

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.79565 | val 0.77605
  Epoch 014 - train 0.57546 | val 0.74523
  Classification -> best τ=0.505 (val F1=0.4015)
  Directional -> Accuracy: 0.6512, MCC: 0.3392, F1: 0.5714

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.73047 | val 0.95963
  Epoch 013 - train 0.62644 | val 0.72878
  Classification -> best τ=0.420 (val F1=0.1803)
  Directional -> Accuracy: 0.5439, MCC: 0.1085, F1: 0.5938

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.65109 | val 0.81022
  Epoch 012 - train 0.57277 | val 0.74881
  Classification -> best τ=0.475 (val F1=0.2922)
  Directional -> Accuracy: 0.5957, MCC: 0.0392, F1: 0.7246

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 16). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.59468 | val 0.95443
  Epoch 011 - train 0.59833 | val 1.00476
  Classification -> best τ=0.440 (val F1=0.1391)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.66462 | val 0.78339
  Epoch 013 - train 0.60818 | val 0.78462
  Classification -> best τ=0.435 (val F1=0.1870)
  Directional -> Accuracy: 0.5641, MCC: 0.1188, F1: 0.7018

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 16). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.70984 | val 0.77356
  Epoch 014 - train 0.65416 | val 0.92520
  Classification -> best τ=0.600 (val F1=0.1912)
  Directional -> Accuracy: 0.5132, MCC: 0.0531, F1: 0.6606

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.70734 | val 0.77726
  Epoch 014 - train 0.63253 | val 0.91730
  Classification -> best τ=0.490 (val F1=0.2858)
  Directional -> Accuracy: 0.5745, MCC: 0.1539, F1: 0.5455

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.64650 | val 1.15521
  Epoch 011 - train 0.56958 | val 1.41238
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.60390 | val 0.67093
  Epoch 018 - train 0.56326 | val 0.89130
  Classification -> best τ=0.535 (val F1=0.3235)
  Directional -> Accuracy: 0.6750, MCC: 0.1981, F1: 0.3158

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.64228 | val 0.91685
  Epoch 017 - train 0.60076 | val 1.17575
  Classification -> best τ=0.495 (val F1=0.1984)
  Directional -> Accuracy: 0.4912, MCC: -0.0674, F1: 0.6027

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.65254 | val 2.10489
  Epoch 011 - train 0.66369 | val 1.82965
  Classification -> best τ=0.535 (val F1=0.2349)
  Directional -> Accuracy: 0.4737, MCC: -0.0518, F1: 0.4643

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.66742 | val 0.82627
  Epoch 011 - train 0.66679 | val 1.02375
  Classification -> best τ=0.465 (val F1=0.2946)
  Directional -> Accuracy: 0.4815, MCC: -0.1310, F1: 0.6410

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.70790 | val 1.20804
  Epoch 014 - train 0.63664 | val 1.92220
  Classification -> best τ=0.445 (val F1=0.2277)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.66287 | val 0.83030

[I 2026-02-25 00:42:53,664] Trial 105 finished with value: 0.2575372362780395 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 15, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 0.009484604855547168, 'weight_decay': 1.5845739736046498e-05, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 1.7592144478408838, 'early_stopping_min_delta': 0.0007262984072977404}. Best is trial 32 with value: 0.2908549754956826.

  Epoch 016 - train 0.69171 | val 0.93248
  Classification -> best τ=0.480 (val F1=0.2458)
  Directional -> Accuracy: 0.5806, MCC: 0.1629, F1: 0.4583

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2575372362780395
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 15
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.67770 | val 0.80619
  Epoch 020 - train 0.68990 | val 0.74569
  Epoch 022 - train 0.65437 | val 0.85808
  Classification -> best τ=0.545 (val F1=0.3210)
  Directional -> Accuracy: 0.4286, MCC: -0.1166, F1: 0.5769

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.63301 | val 0.86360
  Epoch 013 - train 0.64650 | val 1.07010
  Classification -> best τ=0.465 (val F1=0.1236)
  Directional -> Accuracy: 0.5652, MCC: 0.0782, F1: 0.6667

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 16). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.69127 | val 0.73667
  Epoch 012 - train 0.69805 | val 0.71645
  Classification -> best τ=0.430 (val F1=0.3143)
  Directional -> Accuracy: 0.4583, MCC: -0.1448, F1: 0.5806

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.70397 | val 0.91735
  Epoch 011 - train 0.67332 | val 0.96868
  Classification -> best τ=0.390 (val F1=0.3086)
  Directional -> Accuracy: 0.5200, MCC: 0.0829, F1: 0.4375

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.58807 | val 0.83453
  Epoch 013 - train 0.65496 | val 0.89500
  Classification -> best τ=0.440 (val F1=0.3765)
  Directional -> Accuracy: 0.6731, MCC: 0.3689, F1: 0.6531

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.66370 | val 0.80896
  Epoch 013 - train 0.63246 | val 0.81295
  Classification -> best τ=0.430 (val F1=0.2236)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.69370 | val 0.81592
  Epoch 012 - train 0.68294 | val 0.78565
  Classification -> best τ=0.525 (val F1=0.2462)
  Directional -> Accuracy: 0.5143, MCC: 0.0468, F1: 0.4848

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 16). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.71871 | val 2.14479
  Epoch 012 - train 0.66881 | val 1.88390
  Classification -> best τ=0.635 (val F1=0.3669)
  Directional -> Accuracy: 0.4889, MCC: 0.0900, F1: 0.5818

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.71892 | val 0.73900
  Epoch 020 - train 0.66140 | val 0.63527
  Epoch 030 - train 0.64699 | val 0.95192
  Classification -> best τ=0.490 (val F1=0.3877)
  Directional -> Accuracy: 0.5610, MCC: 0.0802, F1: 0.4375

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 16). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 16). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.68211 | val 0.88860
  Epoch 012 - train 0.63269 | val 1.25443
  Classification -> best τ=0.370 (val F1=0.2254)
  Directional -> Accuracy: 0.4366, MCC: 0.0000, F1: 0.6078

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.68748 | val 1.11671
  Epoch 011 - train 0.69899 | val 1.27314
  Classification -> best τ=0.550 (val F1=0.1521)
  Directional -> Accuracy: 0.5098, MCC: -0.1333, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.70788 | val 0.67856
  Epoch 018 - train 0.65137 | val 0.69035
  Classification -> best τ=0.670 (val F1=0.3257)
  Directional -> Accuracy: 0.7288, MCC: 0.5042, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.63747 | val 0.89728
  Epoch 018 - train 0.58696 | val 1.07362
  Classification -> best τ=0.560 (val F1=0.2468)
  Directional -> Accuracy: 0.5116, MCC: 0.0261, F1: 0.4878

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.67354 | val 0.62849
  Epoch 020 - train 0.64362 | val 0.63784
  Epoch 023 - train 0.64377 | val 0.64769
  Classification -> best τ=0.390 (val F1=0.3024)
  Directional -> Accuracy: 0.5410, MCC: 0.1155, F1: 0.6744

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.65109 | val 2.01323
  Epoch 011 - train 0.67567 | val 2.10255
  Classification -> best τ=0.475 (val F1=0.2689)
  Directional -> Accuracy: 0.5849, MCC: 0.2592, F1: 0.2143

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.64551 | val 0.79449
  Epoch 011 - train 0.65190 | val 0.79556
  Classification -> best τ=0.450 (val F1=0.3382)
  Directional -> Accuracy: 0.6000, MCC: 0.1864, F1: 0.7021

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.66630 | val 1.05371
  Epoch 013 - train 0.67224 | val 0.85050
  Classification -> best τ=0.665 (val F1=0.2219)
  Directional -> Accuracy: 0.3833, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.69449 | val 1.25546
  Epoch 013 - train 0.66973 | val 0.76528
  Classification -> best τ=0.540 (val F1=0.1095)
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.69326 | val 0.71886
  Epoch 012 - train 0.70147 | val 0.83081
  Classification -> best τ=0.520 (val F1=0.2005)
  Directional -> Accuracy: 0.4091, MCC: -0.0327, F1: 0.0488

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 16). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.68774 | val 0.84478
  Epoch 013 - train 0.63380 | val 1.04390
  Classification -> best τ=0.535 (val F1=0.2893)
  Directional -> Accuracy: 0.4605, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.64212 | val 0.71736
  Epoch 013 - train 0.66794 | val 0.71927
  Classification -> best τ=0.440 (val F1=0.3126)
  Directional -> Accuracy: 0.6458, MCC: 0.2205, F1: 0.7302

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.66749 | val 1.52185
  Epoch 011 - train 0.70069 | val 1.34928
  Classification -> best τ=0.510 (val F1=0.1677)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.5926

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.70520 | val 1.66050
  Epoch 014 - train 0.65518 | val 0.93039
  Classification -> best τ=0.710 (val F1=0.3198)
  Directional -> Accuracy: 0.4828, MCC: 0.0370, F1: 0.3750

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.68927 | val 1.89684
  Epoch 011 - train 0.69019 | val 1.70339
  Classification -> best τ=0.450 (val F1=0.2086)
  Directional -> Accuracy: 0.5152, MCC: 0.0563, F1: 0.5789

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.68223 | val 0.70966
  Epoch 013 - train 0.68498 | val 0.69536
  Classification -> best τ=0.470 (val F1=0.3735)
  Directional -> Accuracy: 0.6071, MCC: 0.2642, F1: 0.5600

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.62034 | val 0.69396
  Epoch 011 - train 0.60125 | val 0.71101
  Classification -> best τ=0.530 (val F1=0.2067)
  Directional -> Accuracy: 0.5532, MCC: 0.0921, F1: 0.4878

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.73755 | val 0.77215
  Epoch 016 - train 0.62971 | val 1.04225
  Classification -> best τ=0.475 (val F1=0.2000)
  Directional -> Accuracy: 0.5581, MCC: 0.1140, F1: 0.5957

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.66616 | val 0.69689
  Epoch 015 - train 0.62634 | val 0.86351
  Classification -> best τ=0.395 (val F1=0.2829)
  Directional -> Accuracy: 0.6034, MCC: 0.2013, F1: 0.6349

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.85233 | val 0.71607
  Epoch 018 - train 0.65964 | val 0.74091
  Classification -> best τ=0.560 (val F1=0.5399)
  Directional -> Accuracy: 0.5714, MCC: 0.1435, F1: 0.5909

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.62023 | val 1.00049
  Epoch 014 - train 0.61963 | val 1.23269
  Classification -> best τ=0.490 (val F1=0.1869)
  Directional -> Accuracy: 0.5909, MCC: 0.1818, F1: 0.5909

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.70491 | val 0.74253
  Epoch 012 - train 0.70269 | val 0.72225
  Classification -> best τ=0.595 (val F1=0.0296)
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.66913 | val 0.72463
  Epoch 013 - train 0.60277 | val 0.77552
  Classification -> best τ=0.700 (val F1=0.2320)
  Directional -> Accuracy: 0.5098, MCC: -0.0051, F1: 0.6032

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.66332 | val 0.78853
  Epoch 015 - train 0.68453 | val 0.66740
  Classification -> best τ=0.435 (val F1=0.3074)
  Directional -> Accuracy: 0.5541, MCC: 0.2008, F1: 0.4590

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.56890 | val 0.72226
  Epoch 013 - train 0.61084 | val 0.77679
  Classification -> best τ=0.480 (val F1=0.2550)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6275

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.68382 | val 0.89992
  Epoch 013 - train 0.66954 | val 1.00951
  Classification -> best τ=0.530 (val F1=0.5321)
  Directional -> Accuracy: 0.5111, MCC: 0.0854, F1: 0.6207

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.66675 | val 0.71579
  Epoch 013 - train 0.64218 | val 0.84934
  Classification -> best τ=0.320 (val F1=0.3431)
  Directional -> Accuracy: 0.5672, MCC: 0.0238, F1: 0.7184

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.70641 | val 0.69321
  Epoch 020 - train 0.61444 | val 0.66482
  Epoch 030 - train 0.58579 | val 0.97080
  Classification -> best τ=0.615 (val F1=0.3914)
  Directional -> Accuracy: 0.6512, MCC: 0.3392, F1: 0.5714

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.65415 | val 0.73776
  Epoch 012 - train 0.63900 | val 0.73806
  Classification -> best τ=0.460 (val F1=0.1652)
  Directional -> Accuracy: 0.5088, MCC: 0.0453, F1: 0.5882

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.66828 | val 0.79442
  Epoch 014 - train 0.64464 | val 0.70264
  Classification -> best τ=0.670 (val F1=0.4949)
  Directional -> Accuracy: 0.6383, MCC: 0.2604, F1: 0.6909

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 16). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.63322 | val 0.80807
  Epoch 012 - train 0.62864 | val 1.22979
  Classification -> best τ=0.345 (val F1=0.3779)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.77413 | val 0.71193
  Epoch 018 - train 0.70586 | val 0.84348
  Classification -> best τ=0.455 (val F1=0.4024)
  Directional -> Accuracy: 0.4615, MCC: -0.1091, F1: 0.5532

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 16). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.68885 | val 0.75416
  Epoch 014 - train 0.66657 | val 1.11547
  Classification -> best τ=0.420 (val F1=0.2179)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.68634 | val 0.69336
  Epoch 011 - train 0.72252 | val 0.69201
  Classification -> best τ=0.475 (val F1=0.1898)
  Directional -> Accuracy: 0.5532, MCC: 0.1093, F1: 0.5333

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.66437 | val 0.78166
  Epoch 011 - train 0.55535 | val 0.86845
  Classification -> best τ=0.525 (val F1=0.1387)
  Directional -> Accuracy: 0.5778, MCC: 0.1156, F1: 0.6780

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.77880 | val 0.71833
  Epoch 017 - train 0.67174 | val 0.71637
  Classification -> best τ=0.535 (val F1=0.4286)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.65998 | val 1.01909
  Epoch 014 - train 0.65465 | val 1.13735
  Classification -> best τ=0.460 (val F1=0.1512)
  Directional -> Accuracy: 0.4561, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.65695 | val 1.48115
  Epoch 011 - train 0.67199 | val 1.64362
  Classification -> best τ=0.585 (val F1=0.3508)
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.68393 | val 1.64559
  Epoch 013 - train 0.65735 | val 1.38436
  Classification -> best τ=0.560 (val F1=0.1957)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.69530 | val 1.09671
  Epoch 012 - train 0.67745 | val 1.43669
  Classification -> best τ=0.525 (val F1=0.2579)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.65779 | val 0.71369
  Epoch 011 - train 0.64642 | val 0.81825

[I 2026-02-25 00:44:48,770] Trial 106 finished with value: 0.277675629911904 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 15, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 32, 'learning_rate': 0.0055059305206159, 'weight_decay': 3.8412269864997866e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.6868785723201996, 'early_stopping_min_delta': 1.4330213253921798e-05}. Best is trial 32 with value: 0.2908549754956826.

  Classification -> best τ=0.525 (val F1=0.2746)
  Directional -> Accuracy: 0.5000, MCC: -0.1240, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.277675629911904
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: classification
Sequence length: 15
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.67383 | val 0.72534
  Epoch 015 - train 0.65701 | val 0.98454
  Classification -> best τ=0.500 (val F1=0.0676)
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.68190 | val 0.78795
  Epoch 011 - train 0.67081 | val 0.88061
  Classification -> best τ=0.435 (val F1=0.1252)
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 16). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.65205 | val 0.72406
  Epoch 019 - train 0.64955 | val 0.71437
  Classification -> best τ=0.570 (val F1=0.3963)
  Directional -> Accuracy: 0.4583, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.69163 | val 0.69305
  Epoch 020 - train 0.66698 | val 0.71719
  Epoch 024 - train 0.65164 | val 0.82581
  Classification -> best τ=0.560 (val F1=0.3043)
  Directional -> Accuracy: 0.4800, MCC: 0.1507, F1: 0.0930

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.66936 | val 0.66289
  Epoch 017 - train 0.58462 | val 0.72644
  Classification -> best τ=0.505 (val F1=0.4747)
  Directional -> Accuracy: 0.6538, MCC: 0.3880, F1: 0.5714

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.68725 | val 0.69422
  Epoch 015 - train 0.66413 | val 0.74818
  Classification -> best τ=0.440 (val F1=0.2875)
  Directional -> Accuracy: 0.5208, MCC: 0.0496, F1: 0.3429

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.70530 | val 0.70981
  Epoch 014 - train 0.67660 | val 0.69505
  Classification -> best τ=0.530 (val F1=0.3464)
  Directional -> Accuracy: 0.3857, MCC: -0.1474, F1: 0.5567

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 16). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.63406 | val 2.73121
  Epoch 011 - train 0.69460 | val 2.54384
  Classification -> best τ=0.525 (val F1=0.2229)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.71034 | val 0.71610
  Epoch 014 - train 0.65593 | val 0.74257
  Classification -> best τ=0.505 (val F1=0.3877)
  Directional -> Accuracy: 0.3659, MCC: 0.0000, F1: 0.5357

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 16). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 16). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.68523 | val 0.97673
  Epoch 011 - train 0.67581 | val 0.75544
  Classification -> best τ=0.450 (val F1=0.1283)
  Directional -> Accuracy: 0.4789, MCC: 0.0793, F1: 0.6022

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.67049 | val 0.67367
  Epoch 015 - train 0.64904 | val 0.67410
  Classification -> best τ=0.470 (val F1=0.3244)
  Directional -> Accuracy: 0.6078, MCC: 0.2654, F1: 0.3333

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.65940 | val 0.78565
  Epoch 018 - train 0.64476 | val 0.77799
  Classification -> best τ=0.635 (val F1=0.2394)
  Directional -> Accuracy: 0.6610, MCC: 0.3460, F1: 0.6000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.69708 | val 0.73900
  Epoch 013 - train 0.69248 | val 0.72738
  Classification -> best τ=0.470 (val F1=0.2504)
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.68836 | val 0.69120
  Epoch 020 - train 0.63563 | val 0.61489
  Epoch 029 - train 0.63501 | val 1.14771
  Classification -> best τ=0.290 (val F1=0.3212)
  Directional -> Accuracy: 0.5410, MCC: 0.1155, F1: 0.6744

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.69674 | val 0.78913
  Epoch 016 - train 0.66357 | val 1.74739
  Classification -> best τ=0.490 (val F1=0.3058)
  Directional -> Accuracy: 0.6038, MCC: 0.2588, F1: 0.3226

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.65240 | val 0.76843
  Epoch 016 - train 0.67108 | val 0.91368
  Classification -> best τ=0.390 (val F1=0.2927)
  Directional -> Accuracy: 0.5571, MCC: 0.0890, F1: 0.7048

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.67643 | val 1.08563
  Epoch 012 - train 0.68442 | val 1.03660
  Classification -> best τ=0.415 (val F1=0.0704)
  Directional -> Accuracy: 0.5667, MCC: -0.0432, F1: 0.7045

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.67383 | val 0.77555
  Epoch 015 - train 0.67628 | val 1.08424
  Classification -> best τ=0.480 (val F1=0.1208)
  Directional -> Accuracy: 0.4605, MCC: 0.1641, F1: 0.2264

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.68558 | val 0.77548
  Epoch 017 - train 0.68848 | val 0.69668
  Classification -> best τ=0.350 (val F1=0.3254)
  Directional -> Accuracy: 0.4848, MCC: 0.1240, F1: 0.3200

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 16). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.67099 | val 0.76315
  Epoch 015 - train 0.66134 | val 0.74921
  Classification -> best τ=0.630 (val F1=0.2626)
  Directional -> Accuracy: 0.4605, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.67026 | val 1.05764
  Epoch 020 - train 0.62120 | val 0.92038
  Epoch 026 - train 0.61471 | val 1.55770
  Classification -> best τ=0.515 (val F1=0.2648)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.73097 | val 1.08935
  Epoch 013 - train 0.68098 | val 0.75040
  Classification -> best τ=0.510 (val F1=0.2595)
  Directional -> Accuracy: 0.5303, MCC: 0.0845, F1: 0.2791

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.65870 | val 0.80948
  Epoch 020 - train 0.71265 | val 0.69853
  Epoch 023 - train 0.66940 | val 0.74741
  Classification -> best τ=0.595 (val F1=0.3221)
  Directional -> Accuracy: 0.5000, MCC: 0.1008, F1: 0.3556

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.67655 | val 0.80853
  Epoch 011 - train 0.68481 | val 0.88643
  Classification -> best τ=0.485 (val F1=0.1318)
  Directional -> Accuracy: 0.5909, MCC: 0.1804, F1: 0.5714

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.71649 | val 0.74114
  Epoch 016 - train 0.69840 | val 0.71623
  Classification -> best τ=0.590 (val F1=0.3699)
  Directional -> Accuracy: 0.5357, MCC: 0.1376, F1: 0.4348

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.61557 | val 0.72297
  Epoch 013 - train 0.64849 | val 0.83050
  Classification -> best τ=0.550 (val F1=0.0961)
  Directional -> Accuracy: 0.4894, MCC: -0.0584, F1: 0.3684

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.68531 | val 0.70508
  Epoch 020 - train 0.63183 | val 0.67235
  Epoch 030 - train 0.62359 | val 1.15836
  Classification -> best τ=0.570 (val F1=0.2439)
  Directional -> Accuracy: 0.4884, MCC: -0.0044, F1: 0.5000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.73864 | val 0.79274
  Epoch 013 - train 0.67364 | val 0.70136
  Classification -> best τ=0.450 (val F1=0.2652)
  Directional -> Accuracy: 0.5517, MCC: 0.2600, F1: 0.3500

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.78707 | val 0.78274
  Epoch 020 - train 0.66298 | val 0.73618
  Epoch 022 - train 0.74224 | val 0.69262
  Classification -> best τ=0.575 (val F1=0.3548)
  Directional -> Accuracy: 0.4762, MCC: 0.0387, F1: 0.2143

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.65331 | val 0.92305
  Epoch 011 - train 0.63612 | val 1.04485
  Classification -> best τ=0.555 (val F1=0.1869)
  Directional -> Accuracy: 0.4773, MCC: -0.0498, F1: 0.3429

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.68655 | val 0.65546
  Epoch 020 - train 0.70716 | val 0.64628
  Epoch 030 - train 0.58776 | val 0.66479
  Classification -> best τ=0.700 (val F1=0.2595)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.69079 | val 0.69455
  Epoch 015 - train 0.66387 | val 0.68840
  Classification -> best τ=0.430 (val F1=0.2547)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.66287 | val 0.63723
  Epoch 020 - train 0.60950 | val 1.46257
  Classification -> best τ=0.395 (val F1=0.3259)
  Directional -> Accuracy: 0.5405, MCC: 0.1282, F1: 0.5000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.62824 | val 0.91015
  Epoch 012 - train 0.71861 | val 1.17450
  Classification -> best τ=0.455 (val F1=0.1461)
  Directional -> Accuracy: 0.4737, MCC: -0.0538, F1: 0.5238

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.68956 | val 0.77632
  Epoch 020 - train 0.55453 | val 0.61809
  Epoch 030 - train 0.59167 | val 0.68402
  Classification -> best τ=0.500 (val F1=0.4286)
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.6364

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.64071 | val 0.92319
  Epoch 013 - train 0.60827 | val 1.10768
  Classification -> best τ=0.390 (val F1=0.3702)
  Directional -> Accuracy: 0.4776, MCC: 0.1335, F1: 0.1860

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.69579 | val 0.71541
  Epoch 017 - train 0.66670 | val 0.71070
  Classification -> best τ=0.450 (val F1=0.3004)
  Directional -> Accuracy: 0.6512, MCC: 0.3072, F1: 0.6341

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.67206 | val 0.69078
  Epoch 018 - train 0.68055 | val 0.82244
  Classification -> best τ=0.370 (val F1=0.3126)
  Directional -> Accuracy: 0.5439, MCC: 0.1235, F1: 0.6176

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.68719 | val 0.97724
  Epoch 011 - train 0.73134 | val 0.81873
  Classification -> best τ=0.345 (val F1=0.2403)
  Directional -> Accuracy: 0.6383, MCC: 0.1622, F1: 0.7536

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 16). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.70434 | val 1.45231
  Epoch 011 - train 0.63769 | val 1.94021
  Classification -> best τ=0.525 (val F1=0.2981)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.70128 | val 0.76607
  Epoch 011 - train 0.65948 | val 0.83442
  Classification -> best τ=0.505 (val F1=0.1870)
  Directional -> Accuracy: 0.4872, MCC: -0.1435, F1: 0.6429

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 16). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.70552 | val 0.78533
  Epoch 011 - train 0.64852 | val 0.79515
  Classification -> best τ=0.570 (val F1=0.2510)
  Directional -> Accuracy: 0.5132, MCC: 0.1155, F1: 0.6726

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.65041 | val 0.72432
  Epoch 011 - train 0.68192 | val 0.75166
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.64540 | val 0.83524
  Epoch 011 - train 0.65888 | val 0.84475
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.67748 | val 0.69161
  Epoch 020 - train 0.66197 | val 0.75916
  Epoch 023 - train 0.68903 | val 0.71351
  Classification -> best τ=0.570 (val F1=0.3780)
  Directional -> Accuracy: 0.3750, MCC: -0.0396, F1: 0.4898

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.70554 | val 0.65110
  Epoch 020 - train 0.64389 | val 0.66431
  Classification -> best τ=0.580 (val F1=0.2869)
  Directional -> Accuracy: 0.5614, MCC: 0.2372, F1: 0.3902

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.67620 | val 0.85052
  Epoch 012 - train 0.64313 | val 1.10586
  Classification -> best τ=0.410 (val F1=0.2554)
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.72334 | val 0.99398
  Epoch 017 - train 0.65031 | val 0.74940
  Classification -> best τ=0.390 (val F1=0.2775)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.68057 | val 0.74269
  Epoch 015 - train 0.65582 | val 0.95533
  Classification -> best τ=0.655 (val F1=0.2157)
  Directional -> Accuracy: 0.5088, MCC: 0.0048, F1: 0.6585

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.67072 | val 0.68720

[I 2026-02-25 00:46:03,438] Trial 107 finished with value: 0.25604397858719447 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 15, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 32, 'learning_rate': 0.005287808289058491, 'weight_decay': 3.889883107878484e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.633735960648069, 'early_stopping_min_delta': 0.00019131036923431173}. Best is trial 32 with value: 0.2908549754956826.

  Epoch 014 - train 0.67745 | val 0.68345
  Classification -> best τ=0.425 (val F1=0.2653)
  Directional -> Accuracy: 0.5161, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.25604397858719447
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 15
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.68589 | val 0.67139
  Epoch 019 - train 0.66761 | val 0.71006
  Classification -> best τ=0.650 (val F1=0.3541)
  Directional -> Accuracy: 0.5065, MCC: -0.0886, F1: 0.1364

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.65526 | val 0.72241
  Epoch 016 - train 0.62679 | val 0.72021
  Classification -> best τ=0.470 (val F1=0.1700)
  Directional -> Accuracy: 0.5435, MCC: 0.1833, F1: 0.4324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 16). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.66129 | val 0.70410
  Epoch 020 - train 0.68182 | val 0.71880
  Epoch 028 - train 0.64680 | val 0.84082
  Classification -> best τ=0.375 (val F1=0.3731)
  Directional -> Accuracy: 0.6458, MCC: 0.3496, F1: 0.5854

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.68437 | val 0.75236
  Epoch 013 - train 0.69426 | val 0.71019
  Classification -> best τ=0.545 (val F1=0.0823)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.61630 | val 1.11913
  Epoch 014 - train 0.65394 | val 0.99627
  Classification -> best τ=0.425 (val F1=0.3961)
  Directional -> Accuracy: 0.7115, MCC: 0.4238, F1: 0.7619

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.63993 | val 0.84826
  Epoch 012 - train 0.65109 | val 0.93714
  Classification -> best τ=0.325 (val F1=0.3254)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.5714

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.69380 | val 0.69415
  Epoch 012 - train 0.68623 | val 0.69761
  Classification -> best τ=0.640 (val F1=0.2462)
  Directional -> Accuracy: 0.5714, MCC: -0.0754, F1: 0.0625

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 16). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.64698 | val 1.40541
  Epoch 015 - train 0.58825 | val 1.55969
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.66100 | val 0.72140
  Epoch 020 - train 0.63191 | val 0.69994
  Epoch 023 - train 0.63792 | val 0.70953
  Classification -> best τ=0.570 (val F1=0.4273)
  Directional -> Accuracy: 0.5854, MCC: 0.0679, F1: 0.3704

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 16). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 16). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.66818 | val 0.72003
  Epoch 011 - train 0.64718 | val 0.85604
  Classification -> best τ=0.475 (val F1=0.1827)
  Directional -> Accuracy: 0.4507, MCC: 0.0203, F1: 0.5979

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.67281 | val 0.82045
  Epoch 012 - train 0.68038 | val 0.79418
  Classification -> best τ=0.505 (val F1=0.3439)
  Directional -> Accuracy: 0.5490, MCC: 0.1209, F1: 0.5965

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.73818 | val 0.71703
  Epoch 012 - train 0.69233 | val 0.72109
  Classification -> best τ=0.515 (val F1=0.3187)
  Directional -> Accuracy: 0.5085, MCC: 0.0103, F1: 0.6027

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.65836 | val 0.79851
  Epoch 013 - train 0.69252 | val 0.86082
  Classification -> best τ=0.500 (val F1=0.2037)
  Directional -> Accuracy: 0.4419, MCC: -0.0471, F1: 0.5714

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.68966 | val 0.68304
  Epoch 014 - train 0.69130 | val 0.63978
  Classification -> best τ=0.375 (val F1=0.3586)
  Directional -> Accuracy: 0.5574, MCC: 0.1842, F1: 0.6897

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.66267 | val 0.69262
  Epoch 014 - train 0.68164 | val 0.72710
  Classification -> best τ=0.425 (val F1=0.2145)
  Directional -> Accuracy: 0.4717, MCC: 0.0000, F1: 0.6410

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.65068 | val 0.80227
  Epoch 014 - train 0.64475 | val 0.78106
  Classification -> best τ=0.340 (val F1=0.2927)
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.67728 | val 0.72647
  Epoch 019 - train 0.65395 | val 0.88112
  Classification -> best τ=0.470 (val F1=0.2093)
  Directional -> Accuracy: 0.6333, MCC: 0.1337, F1: 0.7660

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.69529 | val 0.69957
  Epoch 012 - train 0.67524 | val 0.70182
  Classification -> best τ=0.495 (val F1=0.1217)
  Directional -> Accuracy: 0.5789, MCC: 0.0042, F1: 0.7143

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.67682 | val 0.70664
  Epoch 020 - train 0.67429 | val 0.68183
  Epoch 025 - train 0.70674 | val 0.67046
  Classification -> best τ=0.345 (val F1=0.2972)
  Directional -> Accuracy: 0.5303, MCC: 0.0907, F1: 0.5373

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 16). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.66264 | val 0.69015
  Epoch 012 - train 0.65314 | val 0.76145
  Classification -> best τ=0.475 (val F1=0.3652)
  Directional -> Accuracy: 0.4605, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.67838 | val 0.68978
  Epoch 020 - train 0.67868 | val 0.70387
  Epoch 022 - train 0.63694 | val 0.70191
  Classification -> best τ=0.390 (val F1=0.3143)
  Directional -> Accuracy: 0.5625, MCC: 0.0121, F1: 0.6769

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.68085 | val 0.91865
  Epoch 011 - train 0.70035 | val 1.07015
  Classification -> best τ=0.475 (val F1=0.1148)
  Directional -> Accuracy: 0.6061, MCC: 0.2157, F1: 0.6389

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.68194 | val 0.78767
  Epoch 016 - train 0.66671 | val 1.04703
  Classification -> best τ=0.565 (val F1=0.1780)
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.67008 | val 2.06644
  Epoch 012 - train 0.67198 | val 0.98572
  Classification -> best τ=0.485 (val F1=0.2319)
  Directional -> Accuracy: 0.5152, MCC: 0.0011, F1: 0.3333

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.66414 | val 0.75321
  Epoch 011 - train 0.67862 | val 0.71422
  Classification -> best τ=0.575 (val F1=0.1941)
  Directional -> Accuracy: 0.4643, MCC: 0.0541, F1: 0.1176

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.66299 | val 0.69591
  Epoch 019 - train 0.60450 | val 0.76267
  Classification -> best τ=0.545 (val F1=0.1792)
  Directional -> Accuracy: 0.5745, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.64879 | val 0.68890
  Epoch 012 - train 0.65317 | val 0.70584
  Classification -> best τ=0.560 (val F1=0.0473)
  Directional -> Accuracy: 0.4884, MCC: 0.1188, F1: 0.3125

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.67772 | val 0.69331
  Epoch 014 - train 0.67178 | val 0.74327
  Classification -> best τ=0.475 (val F1=0.2430)
  Directional -> Accuracy: 0.4483, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.64416 | val 0.68949
  Epoch 020 - train 0.67637 | val 0.71177
  Classification -> best τ=0.535 (val F1=0.2924)
  Directional -> Accuracy: 0.5952, MCC: 0.1758, F1: 0.7119

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.67868 | val 1.00676
  Epoch 012 - train 0.64400 | val 1.32468
  Classification -> best τ=0.570 (val F1=0.1869)
  Directional -> Accuracy: 0.4545, MCC: -0.1085, F1: 0.2500

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.66431 | val 0.68573
  Epoch 018 - train 0.68125 | val 0.77786
  Classification -> best τ=0.710 (val F1=0.1778)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.67111 | val 0.70238
  Epoch 016 - train 0.63345 | val 0.77484
  Classification -> best τ=0.410 (val F1=0.2893)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.69042 | val 0.69142
  Epoch 020 - train 0.67750 | val 0.66852
  Epoch 030 - train 0.62375 | val 0.71627
  Classification -> best τ=0.605 (val F1=0.2739)
  Directional -> Accuracy: 0.4324, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.66200 | val 0.71645
  Epoch 011 - train 0.69360 | val 0.73053
  Classification -> best τ=0.480 (val F1=0.2145)
  Directional -> Accuracy: 0.5526, MCC: 0.1291, F1: 0.6531

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.69054 | val 0.75263
  Epoch 013 - train 0.66888 | val 0.74372
  Classification -> best τ=0.540 (val F1=0.1411)
  Directional -> Accuracy: 0.4000, MCC: -0.2004, F1: 0.5263

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.65056 | val 0.67121
  Epoch 020 - train 0.63897 | val 0.81877
  Classification -> best τ=0.340 (val F1=0.3702)
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.69243 | val 0.68305
  Epoch 020 - train 0.64949 | val 0.70856
  Epoch 024 - train 0.59957 | val 0.75133
  Classification -> best τ=0.460 (val F1=0.3092)
  Directional -> Accuracy: 0.6279, MCC: 0.2967, F1: 0.5294

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.65582 | val 0.68925
  Epoch 013 - train 0.63573 | val 0.77216
  Classification -> best τ=0.425 (val F1=0.1920)
  Directional -> Accuracy: 0.4386, MCC: -0.1140, F1: 0.4839

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.67516 | val 0.75729
  Epoch 012 - train 0.65492 | val 0.73597
  Classification -> best τ=0.510 (val F1=0.3321)
  Directional -> Accuracy: 0.6596, MCC: 0.2676, F1: 0.7838

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 16). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.64463 | val 0.83079
  Epoch 015 - train 0.62937 | val 1.06783
  Classification -> best τ=0.585 (val F1=0.4152)
  Directional -> Accuracy: 0.4000, MCC: 0.0147, F1: 0.5000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.67954 | val 0.87731
  Epoch 011 - train 0.62822 | val 0.99143
  Classification -> best τ=0.480 (val F1=0.1870)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.7000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 16). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.67758 | val 0.72547
  Epoch 020 - train 0.65547 | val 0.75697
  Epoch 023 - train 0.65051 | val 0.82914
  Classification -> best τ=0.535 (val F1=0.2662)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6346

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.67859 | val 0.75690
  Epoch 011 - train 0.68329 | val 0.76026
  Classification -> best τ=0.550 (val F1=0.1565)
  Directional -> Accuracy: 0.5745, MCC: 0.1486, F1: 0.5833

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.63819 | val 0.83871
  Epoch 011 - train 0.67079 | val 0.87273
  Classification -> best τ=0.490 (val F1=0.1348)
  Directional -> Accuracy: 0.5556, MCC: 0.0751, F1: 0.6429

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.69813 | val 0.71667
  Epoch 020 - train 0.63134 | val 0.64918
  Epoch 030 - train 0.56336 | val 0.77143
  Classification -> best τ=0.385 (val F1=0.3833)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.70356 | val 0.71754
  Epoch 015 - train 0.67681 | val 0.70217
  Classification -> best τ=0.570 (val F1=0.3203)
  Directional -> Accuracy: 0.4561, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.66123 | val 0.92162
  Epoch 011 - train 0.69427 | val 0.92806
  Classification -> best τ=0.575 (val F1=0.2944)
  Directional -> Accuracy: 0.4912, MCC: 0.0040, F1: 0.5672

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.68545 | val 0.69060
  Epoch 018 - train 0.66763 | val 0.71741
  Classification -> best τ=0.580 (val F1=0.1757)
  Directional -> Accuracy: 0.4259, MCC: -0.1667, F1: 0.5079

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.70159 | val 0.76204
  Epoch 014 - train 0.68448 | val 0.78358
  Classification -> best τ=0.495 (val F1=0.1758)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.68036 | val 0.68395
  Epoch 020 - train 0.65609 | val 0.69150

[I 2026-02-25 00:48:51,398] Trial 108 finished with value: 0.24715541647033934 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 15, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 0.009942642123864543, 'weight_decay': 3.3849753185104303e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.6948109691349442, 'early_stopping_min_delta': 5.486782752725492e-05}. Best is trial 32 with value: 0.2908549754956826.

  Epoch 021 - train 0.65035 | val 0.68395
  Classification -> best τ=0.435 (val F1=0.2838)
  Directional -> Accuracy: 0.5161, MCC: 0.0468, F1: 0.5833

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.24715541647033934
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 15
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.66266 | val 0.67422
  Epoch 020 - train 0.67446 | val 0.66295
  Epoch 021 - train 0.65843 | val 0.74313
  Classification -> best τ=0.500 (val F1=0.2851)
  Directional -> Accuracy: 0.4675, MCC: -0.1461, F1: 0.1961

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.64663 | val 0.86062
  Epoch 016 - train 0.62536 | val 0.86760
  Classification -> best τ=0.495 (val F1=0.2431)
  Directional -> Accuracy: 0.6739, MCC: 0.3254, F1: 0.7368

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 16). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.70283 | val 0.67359
  Epoch 020 - train 0.62688 | val 0.69791
  Classification -> best τ=0.645 (val F1=0.3357)
  Directional -> Accuracy: 0.4792, MCC: 0.1342, F1: 0.0741

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.69915 | val 0.73783
  Epoch 017 - train 0.65930 | val 0.96307
  Classification -> best τ=0.480 (val F1=0.1989)
  Directional -> Accuracy: 0.5600, MCC: 0.1101, F1: 0.6024

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.62177 | val 1.09809
  Epoch 012 - train 0.56043 | val 0.94929
  Classification -> best τ=0.525 (val F1=0.5124)
  Directional -> Accuracy: 0.5769, MCC: 0.1993, F1: 0.5000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.67533 | val 0.89653
  Epoch 017 - train 0.63399 | val 0.75114
  Classification -> best τ=0.510 (val F1=0.4633)
  Directional -> Accuracy: 0.3958, MCC: -0.2478, F1: 0.5246

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.66856 | val 0.69955
  Epoch 014 - train 0.70048 | val 0.70885
  Classification -> best τ=0.445 (val F1=0.2274)
  Directional -> Accuracy: 0.4000, MCC: -0.0928, F1: 0.5116

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 16). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.65767 | val 1.23366
  Epoch 011 - train 0.63447 | val 1.26615
  Classification -> best τ=0.590 (val F1=0.2385)
  Directional -> Accuracy: 0.5111, MCC: 0.1085, F1: 0.5769

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.62817 | val 0.84787
  Epoch 016 - train 0.63701 | val 0.68326
  Classification -> best τ=0.685 (val F1=0.4315)
  Directional -> Accuracy: 0.6098, MCC: 0.0591, F1: 0.2727

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 16). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 16). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.71045 | val 0.80101
  Epoch 014 - train 0.63883 | val 1.08318
  Classification -> best τ=0.420 (val F1=0.1397)
  Directional -> Accuracy: 0.4366, MCC: 0.0000, F1: 0.6078

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.73679 | val 1.17873
  Epoch 013 - train 0.68185 | val 1.48334
  Classification -> best τ=0.440 (val F1=0.2622)
  Directional -> Accuracy: 0.5882, MCC: 0.2176, F1: 0.2759

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.68673 | val 0.75401
  Epoch 011 - train 0.65827 | val 0.77505
  Classification -> best τ=0.525 (val F1=0.2394)
  Directional -> Accuracy: 0.4407, MCC: -0.1205, F1: 0.3265

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.64246 | val 0.82819
  Epoch 018 - train 0.66667 | val 1.11647
  Classification -> best τ=0.600 (val F1=0.2869)
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.70069 | val 0.64660
  Epoch 019 - train 0.65671 | val 0.77706
  Classification -> best τ=0.215 (val F1=0.2718)
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.68277 | val 1.96543
  Epoch 011 - train 0.62199 | val 1.80097
  Classification -> best τ=0.530 (val F1=0.3856)
  Directional -> Accuracy: 0.5283, MCC: 0.1254, F1: 0.6377

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.65794 | val 0.72349
  Epoch 013 - train 0.63830 | val 0.74308
  Classification -> best τ=0.595 (val F1=0.3197)
  Directional -> Accuracy: 0.5143, MCC: 0.1130, F1: 0.3200

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.68502 | val 0.98020
  Epoch 011 - train 0.69964 | val 1.01985
  Classification -> best τ=0.570 (val F1=0.1796)
  Directional -> Accuracy: 0.3833, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.66480 | val 0.82604
  Epoch 011 - train 0.68473 | val 0.74069
  Classification -> best τ=0.495 (val F1=0.1535)
  Directional -> Accuracy: 0.6316, MCC: 0.2582, F1: 0.6744

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.66355 | val 0.81771
  Epoch 011 - train 0.67270 | val 0.81175
  Classification -> best τ=0.520 (val F1=0.2439)
  Directional -> Accuracy: 0.4242, MCC: 0.1032, F1: 0.0500

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 16). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.68391 | val 0.81316
  Epoch 011 - train 0.67627 | val 0.78837
  Classification -> best τ=0.580 (val F1=0.1733)
  Directional -> Accuracy: 0.3553, MCC: -0.2834, F1: 0.2222

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.66003 | val 0.72421
  Epoch 015 - train 0.64383 | val 1.00327
  Classification -> best τ=0.500 (val F1=0.2487)
  Directional -> Accuracy: 0.4167, MCC: 0.1615, F1: 0.1250

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.65011 | val 1.02468
  Epoch 014 - train 0.67806 | val 1.30921
  Classification -> best τ=0.430 (val F1=0.1677)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6526

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.66835 | val 0.71545
  Epoch 012 - train 0.68108 | val 0.79347
  Classification -> best τ=0.550 (val F1=0.2431)
  Directional -> Accuracy: 0.5862, MCC: 0.1741, F1: 0.6129

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.66113 | val 1.41386
  Epoch 011 - train 0.63276 | val 1.83972
  Classification -> best τ=0.435 (val F1=0.2453)
  Directional -> Accuracy: 0.5152, MCC: 0.0684, F1: 0.6000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.65287 | val 0.69708
  Epoch 015 - train 0.66546 | val 0.73745
  Classification -> best τ=0.500 (val F1=0.3408)
  Directional -> Accuracy: 0.4464, MCC: -0.0502, F1: 0.2439

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.66767 | val 0.78004
  Epoch 012 - train 0.68861 | val 0.88126
  Classification -> best τ=0.525 (val F1=0.0413)
  Directional -> Accuracy: 0.5745, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.64780 | val 0.68240
  Epoch 020 - train 0.66906 | val 0.71184
  Classification -> best τ=0.535 (val F1=0.1818)
  Directional -> Accuracy: 0.6047, MCC: 0.1377, F1: 0.7385

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.72866 | val 0.73126
  Epoch 013 - train 0.66497 | val 0.75818
  Classification -> best τ=0.400 (val F1=0.2033)
  Directional -> Accuracy: 0.6552, MCC: 0.3350, F1: 0.6429

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.69347 | val 0.70968
  Epoch 011 - train 0.65788 | val 0.71536
  Classification -> best τ=0.490 (val F1=0.3203)
  Directional -> Accuracy: 0.5714, MCC: 0.1194, F1: 0.7097

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.75928 | val 0.99275
  Epoch 011 - train 0.61717 | val 1.05064
  Classification -> best τ=0.540 (val F1=0.1869)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.68656 | val 0.65905
  Epoch 018 - train 0.63494 | val 0.69674
  Classification -> best τ=0.720 (val F1=0.1239)
  Directional -> Accuracy: 0.4091, MCC: -0.1876, F1: 0.0714

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.63414 | val 0.77343
  Epoch 012 - train 0.64401 | val 0.72790
  Classification -> best τ=0.580 (val F1=0.2320)
  Directional -> Accuracy: 0.5098, MCC: 0.0185, F1: 0.5283

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.66061 | val 0.71819
  Epoch 016 - train 0.65274 | val 0.95550
  Classification -> best τ=0.445 (val F1=0.2855)
  Directional -> Accuracy: 0.5405, MCC: 0.1770, F1: 0.4333

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.65438 | val 0.70872
  Epoch 013 - train 0.64417 | val 0.79434
  Classification -> best τ=0.480 (val F1=0.2137)
  Directional -> Accuracy: 0.5526, MCC: 0.1443, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.64109 | val 1.03008
  Epoch 012 - train 0.63824 | val 1.52521
  Classification -> best τ=0.490 (val F1=0.2017)
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.6364

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.66334 | val 0.68988
  Epoch 015 - train 0.62267 | val 0.80508
  Classification -> best τ=0.190 (val F1=0.3431)
  Directional -> Accuracy: 0.5970, MCC: 0.2065, F1: 0.6087

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.70267 | val 0.75041
  Epoch 011 - train 0.67120 | val 0.72824
  Classification -> best τ=0.495 (val F1=0.0885)
  Directional -> Accuracy: 0.6512, MCC: 0.3883, F1: 0.5161

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.66257 | val 0.71001
  Epoch 011 - train 0.69051 | val 0.76099
  Classification -> best τ=0.435 (val F1=0.1873)
  Directional -> Accuracy: 0.5789, MCC: 0.2313, F1: 0.6667

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.60204 | val 0.79147
  Epoch 015 - train 0.57814 | val 0.85836
  Classification -> best τ=0.405 (val F1=0.1299)
  Directional -> Accuracy: 0.5106, MCC: 0.0584, F1: 0.5306

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 16). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.76150 | val 0.92971
  Epoch 011 - train 0.60162 | val 0.99693
  Classification -> best τ=0.510 (val F1=0.2582)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.76397 | val 0.74376
  Epoch 014 - train 0.68022 | val 0.81975
  Classification -> best τ=0.380 (val F1=0.3397)
  Directional -> Accuracy: 0.5641, MCC: 0.1188, F1: 0.7018

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 16). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.65090 | val 0.76261
  Epoch 014 - train 0.65403 | val 0.79857
  Classification -> best τ=0.410 (val F1=0.2752)
  Directional -> Accuracy: 0.5395, MCC: 0.1048, F1: 0.6535

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.69677 | val 0.72121
  Epoch 015 - train 0.69833 | val 0.83245
  Classification -> best τ=0.470 (val F1=0.3680)
  Directional -> Accuracy: 0.5319, MCC: 0.0619, F1: 0.5600

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.67687 | val 0.89350
  Epoch 011 - train 0.62896 | val 0.90100
  Classification -> best τ=0.550 (val F1=0.4781)
  Directional -> Accuracy: 0.5556, MCC: 0.1754, F1: 0.4737

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.66493 | val 0.76726
  Epoch 015 - train 0.62557 | val 0.73512
  Classification -> best τ=0.575 (val F1=0.3968)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.67619 | val 0.85919
  Epoch 013 - train 0.64645 | val 0.94850
  Classification -> best τ=0.540 (val F1=0.2592)
  Directional -> Accuracy: 0.4561, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.68058 | val 1.79641
  Epoch 012 - train 0.64818 | val 1.55724
  Classification -> best τ=0.565 (val F1=0.3535)
  Directional -> Accuracy: 0.5088, MCC: 0.1809, F1: 0.6585

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.62517 | val 1.32213
  Epoch 011 - train 0.67966 | val 1.69832
  Classification -> best τ=0.455 (val F1=0.2448)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.68010 | val 1.78342
  Epoch 011 - train 0.69776 | val 1.56970
  Classification -> best τ=0.575 (val F1=0.1304)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.67448 | val 0.90921

[I 2026-02-25 00:50:46,372] Trial 109 finished with value: 0.2589102862290772 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 15, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.1, 'dropout': 0.8, 'batch_size': 32, 'learning_rate': 0.00441146092740578, 'weight_decay': 5.2932056921466354e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.6027815588286405, 'early_stopping_min_delta': 0.0003905492543936664}. Best is trial 32 with value: 0.2908549754956826.

  Epoch 012 - train 0.64893 | val 0.94367
  Classification -> best τ=0.470 (val F1=0.2653)
  Directional -> Accuracy: 0.5161, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2589102862290772
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 15
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.69142 | val 0.67801
  Epoch 020 - train 0.70149 | val 0.67382
  Epoch 027 - train 0.67840 | val 0.67472
  Classification -> best τ=0.540 (val F1=0.2703)
  Directional -> Accuracy: 0.4805, MCC: -0.0905, F1: 0.2857

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.70267 | val 0.71457
  Epoch 011 - train 0.71640 | val 0.71930
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 16). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.71162 | val 0.68333
  Epoch 020 - train 0.68724 | val 0.68237
  Epoch 030 - train 0.67409 | val 0.68017
  Classification -> best τ=0.440 (val F1=0.3020)
  Directional -> Accuracy: 0.3958, MCC: -0.2058, F1: 0.4082

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.68811 | val 0.76359
  Epoch 011 - train 0.69101 | val 0.77116
  Classification -> best τ=0.475 (val F1=0.1095)
  Directional -> Accuracy: 0.4533, MCC: -0.0368, F1: 0.1961

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.70429 | val 0.66757
  Epoch 020 - train 0.66322 | val 0.65480
  Epoch 030 - train 0.65502 | val 0.65814
  Classification -> best τ=0.465 (val F1=0.4042)
  Directional -> Accuracy: 0.6923, MCC: 0.3805, F1: 0.7419

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.68629 | val 0.70921
  Epoch 011 - train 0.68270 | val 0.71459
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.70023 | val 0.68707
  Epoch 020 - train 0.67639 | val 0.68963
  Classification -> best τ=0.465 (val F1=0.2116)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.5714

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 16). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.70446 | val 0.70941
  Epoch 011 - train 0.71734 | val 0.71575
  Classification -> best τ=0.500 (val F1=0.1585)
  Directional -> Accuracy: 0.4889, MCC: 0.0900, F1: 0.5818

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.71105 | val 0.69798
  Epoch 016 - train 0.68526 | val 0.71402
  Classification -> best τ=0.550 (val F1=0.3977)
  Directional -> Accuracy: 0.3902, MCC: 0.1201, F1: 0.5455

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 16). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 16). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.67796 | val 0.71847
  Epoch 011 - train 0.67843 | val 0.71891
  Classification -> best τ=0.465 (val F1=0.0172)
  Directional -> Accuracy: 0.4366, MCC: -0.0517, F1: 0.5652

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.71553 | val 0.72500
  Epoch 011 - train 0.69203 | val 0.73315
  Classification -> best τ=0.520 (val F1=0.0889)
  Directional -> Accuracy: 0.5294, MCC: 0.0172, F1: 0.1429

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.73286 | val 0.72754
  Epoch 011 - train 0.68748 | val 0.73067
  Classification -> best τ=0.505 (val F1=0.2190)
  Directional -> Accuracy: 0.5593, MCC: 0.1599, F1: 0.3810

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.72034 | val 0.73755
  Epoch 011 - train 0.70116 | val 0.75013
  Classification -> best τ=0.495 (val F1=0.0323)
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.67926 | val 0.63959
  Epoch 020 - train 0.69366 | val 0.62464
  Epoch 030 - train 0.67034 | val 0.61916
  Classification -> best τ=0.450 (val F1=0.3318)
  Directional -> Accuracy: 0.5410, MCC: 0.0887, F1: 0.4815

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.70358 | val 0.80334
  Epoch 011 - train 0.70932 | val 0.86203
  Classification -> best τ=0.510 (val F1=0.0476)
  Directional -> Accuracy: 0.5094, MCC: -0.1310, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.65897 | val 0.64958
  Epoch 019 - train 0.65074 | val 0.65713
  Classification -> best τ=0.650 (val F1=0.4130)
  Directional -> Accuracy: 0.5429, MCC: 0.2107, F1: 0.3333

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.66841 | val 0.72622
  Epoch 015 - train 0.66242 | val 0.75929
  Classification -> best τ=0.525 (val F1=0.3540)
  Directional -> Accuracy: 0.4167, MCC: -0.2052, F1: 0.5070

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.70361 | val 0.92746
  Epoch 011 - train 0.69630 | val 0.93994
  Classification -> best τ=0.465 (val F1=0.0250)
  Directional -> Accuracy: 0.5263, MCC: 0.1770, F1: 0.4545

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.68848 | val 0.74874
  Epoch 011 - train 0.69065 | val 0.75380
  Classification -> best τ=0.480 (val F1=0.0054)
  Directional -> Accuracy: 0.5000, MCC: 0.1525, F1: 0.3529

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 16). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.67098 | val 0.68656
  Epoch 016 - train 0.68833 | val 0.69134
  Classification -> best τ=0.455 (val F1=0.3124)
  Directional -> Accuracy: 0.5000, MCC: 0.0935, F1: 0.2400

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.69383 | val 0.70661
  Epoch 011 - train 0.69648 | val 0.71153
  Classification -> best τ=0.470 (val F1=0.0241)
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.68353 | val 0.72732
  Epoch 011 - train 0.70721 | val 0.73323
  Classification -> best τ=0.530 (val F1=0.2527)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.68900 | val 0.68599
  Epoch 018 - train 0.68127 | val 0.69410
  Classification -> best τ=0.560 (val F1=0.2272)
  Directional -> Accuracy: 0.5172, MCC: 0.0545, F1: 0.5172

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.70862 | val 0.82201
  Epoch 011 - train 0.69252 | val 0.83469
  Classification -> best τ=0.455 (val F1=0.1052)
  Directional -> Accuracy: 0.5000, MCC: 0.0093, F1: 0.5217

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.69491 | val 0.67835
  Epoch 020 - train 0.69298 | val 0.66243
  Epoch 030 - train 0.68891 | val 0.65935
  Classification -> best τ=0.490 (val F1=0.3916)
  Directional -> Accuracy: 0.5179, MCC: 0.1188, F1: 0.3721

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.70365 | val 0.69814
  Epoch 020 - train 0.67075 | val 0.69512
  Epoch 026 - train 0.68390 | val 0.69754
  Classification -> best τ=0.495 (val F1=0.1623)
  Directional -> Accuracy: 0.4255, MCC: 0.0000, F1: 0.5970

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.68965 | val 0.69710
  Epoch 011 - train 0.68502 | val 0.69961
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.69599 | val 0.73129
  Epoch 011 - train 0.72273 | val 0.73292
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5517, MCC: 0.0000, F1: 0.7111

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.66970 | val 0.69211
  Epoch 020 - train 0.67127 | val 0.68221
  Epoch 030 - train 0.72345 | val 0.68097
  Classification -> best τ=0.460 (val F1=0.3595)
  Directional -> Accuracy: 0.4762, MCC: -0.1249, F1: 0.6071

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.67575 | val 0.71272
  Epoch 011 - train 0.67998 | val 0.71920
  Classification -> best τ=0.505 (val F1=0.1721)
  Directional -> Accuracy: 0.5682, MCC: 0.1575, F1: 0.6545

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.72522 | val 0.70730
  Epoch 020 - train 0.65888 | val 0.70595
  Epoch 023 - train 0.67677 | val 0.70619
  Classification -> best τ=0.450 (val F1=0.2374)
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.68336 | val 0.67611
  Epoch 020 - train 0.65847 | val 0.67624
  Epoch 022 - train 0.64866 | val 0.67609
  Classification -> best τ=0.515 (val F1=0.2679)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.68255 | val 0.71520
  Epoch 011 - train 0.68239 | val 0.71483
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5676, MCC: 0.0000, F1: 0.7241

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.69297 | val 0.69160
  Epoch 011 - train 0.71088 | val 0.69157
  Classification -> best τ=0.490 (val F1=0.1124)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6545

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.70932 | val 0.70162
  Epoch 016 - train 0.68148 | val 0.73265
  Classification -> best τ=0.515 (val F1=0.2500)
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.6364

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.67221 | val 0.67949
  Epoch 020 - train 0.64070 | val 0.67135
  Epoch 028 - train 0.64342 | val 0.67590
  Classification -> best τ=0.385 (val F1=0.3431)
  Directional -> Accuracy: 0.6418, MCC: 0.3248, F1: 0.6250

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.68418 | val 0.70014
  Epoch 011 - train 0.70049 | val 0.70199
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.68726 | val 0.72701
  Epoch 011 - train 0.68055 | val 0.72682
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.71148 | val 0.71123
  Epoch 013 - train 0.67789 | val 0.75406
  Classification -> best τ=0.495 (val F1=0.2653)
  Directional -> Accuracy: 0.4681, MCC: 0.0598, F1: 0.3902

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 16). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.68932 | val 0.69399
  Epoch 020 - train 0.66858 | val 0.67714
  Epoch 030 - train 0.68822 | val 0.67855
  Classification -> best τ=0.510 (val F1=0.4107)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.70906 | val 0.70618
  Epoch 011 - train 0.70264 | val 0.70727
  Classification -> best τ=0.520 (val F1=0.1870)
  Directional -> Accuracy: 0.4615, MCC: -0.0878, F1: 0.5116

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 16). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.68149 | val 0.70122
  Epoch 011 - train 0.69795 | val 0.70089
  Classification -> best τ=0.490 (val F1=0.0993)
  Directional -> Accuracy: 0.4868, MCC: -0.0316, F1: 0.2909

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.66660 | val 0.71712
  Epoch 011 - train 0.67583 | val 0.72081
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.74505 | val 0.69243
  Epoch 020 - train 0.71336 | val 0.68018
  Epoch 028 - train 0.67825 | val 0.68894
  Classification -> best τ=0.530 (val F1=0.2774)
  Directional -> Accuracy: 0.5111, MCC: 0.0925, F1: 0.3889

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.68577 | val 0.71529
  Epoch 011 - train 0.68171 | val 0.71963
  Classification -> best τ=0.480 (val F1=0.1584)
  Directional -> Accuracy: 0.6500, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.68803 | val 0.75841
  Epoch 011 - train 0.67424 | val 0.76747
  Classification -> best τ=0.460 (val F1=0.1602)
  Directional -> Accuracy: 0.5263, MCC: 0.0249, F1: 0.6087

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.67863 | val 0.75449
  Epoch 011 - train 0.67477 | val 0.77273
  Classification -> best τ=0.465 (val F1=0.1093)
  Directional -> Accuracy: 0.5263, MCC: 0.1700, F1: 0.6582

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.69965 | val 0.76693
  Epoch 011 - train 0.69552 | val 0.78162
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.70233 | val 0.79312
  Epoch 011 - train 0.69583 | val 0.81667
  Classification -> best τ=0.505 (val F1=0.1587)
  Directional -> Accuracy: 0.5263, MCC: 0.0827, F1: 0.6747

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.69682 | val 0.69743
  Epoch 011 - train 0.68176 | val 0.69551

[I 2026-02-25 00:52:55,254] Trial 110 finished with value: 0.16877921644000962 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 15, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 1.5316042402487785e-05, 'weight_decay': 8.805996077235714e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.8067879339944124, 'early_stopping_min_delta': 0.00104203724115363}. Best is trial 32 with value: 0.2908549754956826.

  Classification -> best τ=0.510 (val F1=0.0067)
  Directional -> Accuracy: 0.6290, MCC: 0.2731, F1: 0.5106

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.16877921644000962
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 15
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.68828 | val 0.68913
  Epoch 019 - train 0.67553 | val 0.76765
  Classification -> best τ=0.570 (val F1=0.2851)
  Directional -> Accuracy: 0.5195, MCC: -0.0544, F1: 0.1395

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.68153 | val 0.80144
  Epoch 013 - train 0.65356 | val 0.93520
  Classification -> best τ=0.435 (val F1=0.1252)
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 16). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.72846 | val 0.72476
  Epoch 015 - train 0.67888 | val 0.77045
  Classification -> best τ=0.540 (val F1=0.3731)
  Directional -> Accuracy: 0.6042, MCC: 0.2212, F1: 0.5957

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.71891 | val 0.94482
  Epoch 018 - train 0.75786 | val 1.20635
  Classification -> best τ=0.340 (val F1=0.2485)
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.59328 | val 0.83187
  Epoch 012 - train 0.59112 | val 1.27040
  Classification -> best τ=0.520 (val F1=0.2787)
  Directional -> Accuracy: 0.6346, MCC: 0.2620, F1: 0.7077

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.67979 | val 0.78637
  Epoch 012 - train 0.68677 | val 1.11270
  Classification -> best τ=0.530 (val F1=0.1132)
  Directional -> Accuracy: 0.4583, MCC: -0.1508, F1: 0.0714

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.69176 | val 0.74397
  Epoch 015 - train 0.68070 | val 0.73065
  Classification -> best τ=0.455 (val F1=0.2722)
  Directional -> Accuracy: 0.4571, MCC: 0.0133, F1: 0.5250

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 16). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.64383 | val 1.75503
  Epoch 011 - train 0.65494 | val 2.07925
  Classification -> best τ=0.495 (val F1=0.2229)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.71147 | val 0.72518
  Epoch 011 - train 0.70797 | val 0.69709
  Classification -> best τ=0.540 (val F1=0.3855)
  Directional -> Accuracy: 0.4634, MCC: -0.1253, F1: 0.3125

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 16). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 16). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.66117 | val 1.00529
  Epoch 013 - train 0.67792 | val 0.76277
  Classification -> best τ=0.545 (val F1=0.1587)
  Directional -> Accuracy: 0.5634, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.69628 | val 1.23787
  Epoch 013 - train 0.71384 | val 0.86406
  Classification -> best τ=0.415 (val F1=0.1521)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.68248 | val 0.95494
  Epoch 011 - train 0.67227 | val 0.80049
  Classification -> best τ=0.365 (val F1=0.3038)
  Directional -> Accuracy: 0.5085, MCC: 0.0000, F1: 0.6742

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.72958 | val 0.89234
  Epoch 013 - train 0.66467 | val 0.69214
  Classification -> best τ=0.530 (val F1=0.1953)
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.67398 | val 0.70835
  Epoch 018 - train 0.64458 | val 0.94674
  Classification -> best τ=0.475 (val F1=0.3358)
  Directional -> Accuracy: 0.5410, MCC: 0.0804, F1: 0.5758

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.65780 | val 1.00254
  Epoch 015 - train 0.62724 | val 1.36746
  Classification -> best τ=0.450 (val F1=0.2608)
  Directional -> Accuracy: 0.5472, MCC: 0.1468, F1: 0.0769

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.70711 | val 0.82798
  Epoch 015 - train 0.66057 | val 0.83989
  Classification -> best τ=0.640 (val F1=0.1798)
  Directional -> Accuracy: 0.5429, MCC: 0.0938, F1: 0.5429

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.67716 | val 1.18687
  Epoch 011 - train 0.66584 | val 1.33703
  Classification -> best τ=0.465 (val F1=0.0580)
  Directional -> Accuracy: 0.6167, MCC: 0.0800, F1: 0.7473

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.69752 | val 1.10587
  Epoch 013 - train 0.66616 | val 4.14779
  Classification -> best τ=0.470 (val F1=0.0930)
  Directional -> Accuracy: 0.6053, MCC: 0.0739, F1: 0.7368

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.66334 | val 0.80084
  Epoch 017 - train 0.66515 | val 1.01063
  Classification -> best τ=0.280 (val F1=0.2464)
  Directional -> Accuracy: 0.4848, MCC: 0.1021, F1: 0.3462

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 16). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.66200 | val 0.80496
  Epoch 019 - train 0.64466 | val 1.01089
  Classification -> best τ=0.510 (val F1=0.2388)
  Directional -> Accuracy: 0.4605, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.67598 | val 1.27047
  Epoch 015 - train 0.64174 | val 1.26635
  Classification -> best τ=0.390 (val F1=0.3539)
  Directional -> Accuracy: 0.4792, MCC: 0.1981, F1: 0.3243

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.66531 | val 1.06251
  Epoch 012 - train 0.64055 | val 1.60323
  Classification -> best τ=0.490 (val F1=0.2715)
  Directional -> Accuracy: 0.6212, MCC: 0.2481, F1: 0.6575

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.69128 | val 0.82614
  Epoch 011 - train 0.65321 | val 0.78413
  Classification -> best τ=0.605 (val F1=0.2596)
  Directional -> Accuracy: 0.5345, MCC: 0.1655, F1: 0.4255

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.67603 | val 1.26589
  Epoch 011 - train 0.70594 | val 1.19020
  Classification -> best τ=0.485 (val F1=0.2242)
  Directional -> Accuracy: 0.4848, MCC: 0.0596, F1: 0.6383

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.68712 | val 0.83027
  Epoch 012 - train 0.63616 | val 0.79873
  Classification -> best τ=0.550 (val F1=0.4186)
  Directional -> Accuracy: 0.5536, MCC: 0.1244, F1: 0.5455

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.60491 | val 0.75057
  Epoch 011 - train 0.57801 | val 0.75440
  Classification -> best τ=0.495 (val F1=0.2067)
  Directional -> Accuracy: 0.6383, MCC: 0.2766, F1: 0.6047

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.70624 | val 0.73244
  Epoch 013 - train 0.63857 | val 0.74440
  Classification -> best τ=0.570 (val F1=0.2152)
  Directional -> Accuracy: 0.5581, MCC: 0.1656, F1: 0.5366

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.70259 | val 0.70864
  Epoch 013 - train 0.66024 | val 0.73299
  Classification -> best τ=0.515 (val F1=0.2119)
  Directional -> Accuracy: 0.5000, MCC: 0.1211, F1: 0.2564

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.69197 | val 0.68686
  Epoch 020 - train 0.64609 | val 0.76647
  Epoch 030 - train 0.64017 | val 0.84895
  Classification -> best τ=0.480 (val F1=0.3677)
  Directional -> Accuracy: 0.4286, MCC: -0.1350, F1: 0.4286

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.63112 | val 1.80174
  Epoch 011 - train 0.62807 | val 2.06262
  Classification -> best τ=0.595 (val F1=0.1869)
  Directional -> Accuracy: 0.5227, MCC: 0.1525, F1: 0.0870

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.70446 | val 0.81699
  Epoch 016 - train 0.74613 | val 0.76069
  Classification -> best τ=0.405 (val F1=0.2212)
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.63905 | val 0.75053
  Epoch 011 - train 0.62622 | val 0.75536
  Classification -> best τ=0.540 (val F1=0.2870)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.65846 | val 0.74604
  Epoch 013 - train 0.69286 | val 1.62982
  Classification -> best τ=0.555 (val F1=0.2739)
  Directional -> Accuracy: 0.4324, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.68542 | val 0.79171
  Epoch 012 - train 0.62699 | val 0.73962
  Classification -> best τ=0.430 (val F1=0.3893)
  Directional -> Accuracy: 0.5263, MCC: 0.0555, F1: 0.5909

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.68514 | val 0.81204
  Epoch 016 - train 0.61093 | val 1.23561
  Classification -> best τ=0.725 (val F1=0.2883)
  Directional -> Accuracy: 0.4889, MCC: -0.0604, F1: 0.3030

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.66154 | val 0.68678
  Epoch 014 - train 0.62002 | val 0.70360
  Classification -> best τ=0.230 (val F1=0.3521)
  Directional -> Accuracy: 0.5522, MCC: 0.0956, F1: 0.5946

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.70522 | val 0.67964
  Epoch 020 - train 0.67211 | val 0.73238
  Epoch 023 - train 0.62594 | val 0.69232
  Classification -> best τ=0.500 (val F1=0.4246)
  Directional -> Accuracy: 0.6744, MCC: 0.3810, F1: 0.6111

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.67743 | val 0.69076
  Epoch 012 - train 0.61940 | val 0.71062
  Classification -> best τ=0.360 (val F1=0.1803)
  Directional -> Accuracy: 0.5088, MCC: 0.0516, F1: 0.6000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.61047 | val 0.69002
  Epoch 020 - train 0.57483 | val 0.97838
  Classification -> best τ=0.675 (val F1=0.3314)
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 16). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.61802 | val 0.76473
  Epoch 014 - train 0.63051 | val 1.55432
  Classification -> best τ=0.575 (val F1=0.3778)
  Directional -> Accuracy: 0.4250, MCC: -0.0504, F1: 0.4390

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.69463 | val 0.76070
  Epoch 014 - train 0.68729 | val 0.74058
  Classification -> best τ=0.445 (val F1=0.2385)
  Directional -> Accuracy: 0.6154, MCC: 0.2254, F1: 0.7059

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 16). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.66495 | val 0.72553
  Epoch 011 - train 0.66495 | val 0.73515
  Classification -> best τ=0.475 (val F1=0.3724)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.69571 | val 0.82978
  Epoch 018 - train 0.64222 | val 0.73738
  Classification -> best τ=0.550 (val F1=0.3119)
  Directional -> Accuracy: 0.5319, MCC: 0.0609, F1: 0.5769

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.68539 | val 0.97855
  Epoch 014 - train 0.73558 | val 1.65843
  Classification -> best τ=0.425 (val F1=0.1387)
  Directional -> Accuracy: 0.6222, MCC: 0.2193, F1: 0.7018

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.66611 | val 0.65242
  Epoch 020 - train 0.61937 | val 0.73437
  Epoch 021 - train 0.65811 | val 0.72840
  Classification -> best τ=0.580 (val F1=0.4497)
  Directional -> Accuracy: 0.4500, MCC: 0.2446, F1: 0.5600

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.64916 | val 0.83739
  Epoch 013 - train 0.71000 | val 1.17195
  Classification -> best τ=0.540 (val F1=0.1685)
  Directional -> Accuracy: 0.5439, MCC: 0.0000, F1: 0.7045

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.68147 | val 1.59791
  Epoch 011 - train 0.67842 | val 1.78131
  Classification -> best τ=0.505 (val F1=0.3250)
  Directional -> Accuracy: 0.5088, MCC: 0.0590, F1: 0.6111

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.74768 | val 1.29190
  Epoch 013 - train 0.64682 | val 1.52481
  Classification -> best τ=0.395 (val F1=0.2662)
  Directional -> Accuracy: 0.5556, MCC: 0.1520, F1: 0.6923

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.69704 | val 0.93828
  Epoch 013 - train 0.72936 | val 1.73666
  Classification -> best τ=0.565 (val F1=0.2079)
  Directional -> Accuracy: 0.5439, MCC: 0.1941, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.65299 | val 0.96582
  Epoch 011 - train 0.66105 | val 0.91649

[I 2026-02-25 00:54:51,582] Trial 111 finished with value: 0.25695441235395633 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 15, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 32, 'learning_rate': 0.0060104265931757795, 'weight_decay': 2.8694146519325803e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.7366857783498615, 'early_stopping_min_delta': 0.0007933505055180258}. Best is trial 32 with value: 0.2908549754956826.

  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4839, MCC: 0.0000, F1: 0.6522

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.25695441235395633
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 15
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.69952 | val 0.66059
  Epoch 020 - train 0.70218 | val 0.66728
  Epoch 021 - train 0.67756 | val 0.67769
  Classification -> best τ=0.545 (val F1=0.3210)
  Directional -> Accuracy: 0.5195, MCC: -0.0423, F1: 0.1778

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.71045 | val 0.78763
  Epoch 015 - train 0.60506 | val 0.72471
  Classification -> best τ=0.505 (val F1=0.1962)
  Directional -> Accuracy: 0.6304, MCC: 0.2287, F1: 0.7119

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 16). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.66937 | val 0.70504
  Epoch 017 - train 0.64562 | val 0.82411
  Classification -> best τ=0.525 (val F1=0.3171)
  Directional -> Accuracy: 0.4792, MCC: 0.1342, F1: 0.0741

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.70094 | val 1.08065
  Epoch 017 - train 0.68250 | val 1.57225
  Classification -> best τ=0.490 (val F1=0.2314)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.67667 | val 0.75216
  Epoch 016 - train 0.59829 | val 1.08267
  Classification -> best τ=0.515 (val F1=0.4105)
  Directional -> Accuracy: 0.7115, MCC: 0.4622, F1: 0.6809

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.66396 | val 0.76933
  Epoch 017 - train 0.58137 | val 1.56848
  Classification -> best τ=0.470 (val F1=0.3254)
  Directional -> Accuracy: 0.6250, MCC: 0.2750, F1: 0.6897

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.71646 | val 0.71415
  Epoch 011 - train 0.71626 | val 0.73061
  Classification -> best τ=0.500 (val F1=0.1204)
  Directional -> Accuracy: 0.4429, MCC: 0.0778, F1: 0.5714

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 16). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.68559 | val 1.35454
  Epoch 016 - train 0.64893 | val 2.25669
  Classification -> best τ=0.570 (val F1=0.3780)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.67483 | val 0.96331
  Epoch 014 - train 0.69841 | val 0.94340
  Classification -> best τ=0.630 (val F1=0.4315)
  Directional -> Accuracy: 0.6098, MCC: 0.0865, F1: 0.3333

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 16). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 16). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.68626 | val 0.87820
  Epoch 011 - train 0.65387 | val 1.06088
  Classification -> best τ=0.435 (val F1=0.1283)
  Directional -> Accuracy: 0.4507, MCC: -0.0060, F1: 0.5806

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.68540 | val 0.84212
  Epoch 013 - train 0.65684 | val 0.93542
  Classification -> best τ=0.395 (val F1=0.2362)
  Directional -> Accuracy: 0.6667, MCC: 0.3652, F1: 0.5143

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.68235 | val 0.96170
  Epoch 019 - train 0.67382 | val 0.89376
  Classification -> best τ=0.300 (val F1=0.2608)
  Directional -> Accuracy: 0.5085, MCC: 0.0000, F1: 0.6742

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.63092 | val 0.97344
  Epoch 015 - train 0.67818 | val 0.91142
  Classification -> best τ=0.560 (val F1=0.1960)
  Directional -> Accuracy: 0.5349, MCC: 0.0570, F1: 0.4737

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.69088 | val 0.63327
  Epoch 017 - train 0.70436 | val 0.67362
  Classification -> best τ=0.285 (val F1=0.3019)
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.67962 | val 0.94193
  Epoch 013 - train 0.62201 | val 1.09296
  Classification -> best τ=0.530 (val F1=0.2798)
  Directional -> Accuracy: 0.5283, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.70156 | val 0.79891
  Epoch 014 - train 0.65401 | val 0.97388
  Classification -> best τ=0.605 (val F1=0.2796)
  Directional -> Accuracy: 0.5143, MCC: 0.0587, F1: 0.4516

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.69754 | val 1.69894
  Epoch 013 - train 0.65059 | val 1.40219
  Classification -> best τ=0.710 (val F1=0.2219)
  Directional -> Accuracy: 0.3833, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.69097 | val 0.94834
  Epoch 013 - train 0.71997 | val 0.83816
  Classification -> best τ=0.415 (val F1=0.1499)
  Directional -> Accuracy: 0.5526, MCC: 0.1565, F1: 0.5526

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.67624 | val 0.89844
  Epoch 013 - train 0.70877 | val 0.81125
  Classification -> best τ=0.550 (val F1=0.2424)
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 16). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.72242 | val 0.78141
  Epoch 011 - train 0.65935 | val 0.76149
  Classification -> best τ=0.525 (val F1=0.2137)
  Directional -> Accuracy: 0.3553, MCC: -0.2925, F1: 0.1695

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.62889 | val 0.69979
  Epoch 012 - train 0.63070 | val 0.77389
  Classification -> best τ=0.515 (val F1=0.2692)
  Directional -> Accuracy: 0.5417, MCC: -0.0237, F1: 0.6562

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.70183 | val 0.96277
  Epoch 011 - train 0.69113 | val 1.00742
  Classification -> best τ=0.585 (val F1=0.1833)
  Directional -> Accuracy: 0.4848, MCC: -0.1240, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.70054 | val 0.77549
  Epoch 013 - train 0.71104 | val 0.77506
  Classification -> best τ=0.525 (val F1=0.3221)
  Directional -> Accuracy: 0.5345, MCC: 0.0951, F1: 0.5263

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.68745 | val 1.56912
  Epoch 012 - train 0.68209 | val 1.91038
  Classification -> best τ=0.485 (val F1=0.3360)
  Directional -> Accuracy: 0.5455, MCC: 0.1215, F1: 0.6053

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.71480 | val 0.90669
  Epoch 016 - train 0.64749 | val 1.47827
  Classification -> best τ=0.440 (val F1=0.4505)
  Directional -> Accuracy: 0.5714, MCC: 0.2023, F1: 0.5000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.73768 | val 0.75166
  Epoch 014 - train 0.62336 | val 0.92207
  Classification -> best τ=0.635 (val F1=0.1792)
  Directional -> Accuracy: 0.5745, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.64925 | val 0.72172
  Epoch 012 - train 0.67388 | val 0.68399
  Classification -> best τ=0.550 (val F1=0.0444)
  Directional -> Accuracy: 0.5116, MCC: 0.0866, F1: 0.4615

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.70076 | val 0.73537
  Epoch 012 - train 0.64462 | val 0.78701
  Classification -> best τ=0.300 (val F1=0.3217)
  Directional -> Accuracy: 0.5172, MCC: 0.1923, F1: 0.2632

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.69254 | val 0.70607
  Epoch 020 - train 0.66898 | val 0.72581
  Epoch 022 - train 0.64436 | val 0.72100
  Classification -> best τ=0.515 (val F1=0.4193)
  Directional -> Accuracy: 0.4762, MCC: -0.0389, F1: 0.4762

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.64964 | val 1.59042
  Epoch 013 - train 0.64463 | val 2.70038
  Classification -> best τ=0.475 (val F1=0.2107)
  Directional -> Accuracy: 0.5455, MCC: 0.1021, F1: 0.6296

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.73283 | val 0.71428
  Epoch 017 - train 0.60693 | val 0.71886
  Classification -> best τ=0.560 (val F1=0.2374)
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.65746 | val 0.77151
  Epoch 015 - train 0.64056 | val 0.72983
  Classification -> best τ=0.385 (val F1=0.2461)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.65844 | val 0.65215
  Epoch 020 - train 0.61248 | val 1.54745
  Epoch 025 - train 0.64344 | val 2.87300
  Classification -> best τ=0.275 (val F1=0.3313)
  Directional -> Accuracy: 0.5946, MCC: 0.2311, F1: 0.5714

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.65859 | val 0.72762
  Epoch 016 - train 0.65192 | val 0.72199
  Classification -> best τ=0.450 (val F1=0.3125)
  Directional -> Accuracy: 0.5526, MCC: 0.1291, F1: 0.6531

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.69240 | val 0.93098
  Epoch 015 - train 0.64915 | val 0.99920
  Classification -> best τ=0.505 (val F1=0.1890)
  Directional -> Accuracy: 0.4444, MCC: -0.1195, F1: 0.3902

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.66632 | val 0.72385
  Epoch 012 - train 0.64536 | val 0.72416
  Classification -> best τ=0.635 (val F1=0.2595)
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.68842 | val 0.67946
  Epoch 020 - train 0.68909 | val 0.68298
  Classification -> best τ=0.500 (val F1=0.3200)
  Directional -> Accuracy: 0.6512, MCC: 0.3142, F1: 0.6154

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.73050 | val 0.68286
  Epoch 015 - train 0.64185 | val 0.81155
  Classification -> best τ=0.445 (val F1=0.3270)
  Directional -> Accuracy: 0.6316, MCC: 0.2981, F1: 0.6769

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.64837 | val 0.69921
  Epoch 014 - train 0.61738 | val 0.74361
  Classification -> best τ=0.520 (val F1=0.3882)
  Directional -> Accuracy: 0.6170, MCC: 0.0508, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 16). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.66948 | val 0.80859
  Epoch 011 - train 0.61173 | val 0.80111
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.64510 | val 0.72813
  Epoch 011 - train 0.66628 | val 0.73560
  Classification -> best τ=0.475 (val F1=0.4024)
  Directional -> Accuracy: 0.5641, MCC: 0.1139, F1: 0.6222

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 16). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.68986 | val 0.66858
  Epoch 020 - train 0.68323 | val 0.84387
  Classification -> best τ=0.420 (val F1=0.3577)
  Directional -> Accuracy: 0.5132, MCC: 0.1155, F1: 0.6726

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.72776 | val 0.76208
  Epoch 013 - train 0.64949 | val 0.89775
  Classification -> best τ=0.525 (val F1=0.2153)
  Directional -> Accuracy: 0.5532, MCC: 0.1069, F1: 0.6316

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.62468 | val 1.24903
  Epoch 011 - train 0.63782 | val 1.32845
  Classification -> best τ=0.530 (val F1=0.0737)
  Directional -> Accuracy: 0.5778, MCC: 0.1265, F1: 0.6545

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.66976 | val 0.69752
  Epoch 016 - train 0.63754 | val 0.84944
  Classification -> best τ=0.525 (val F1=0.2037)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.78126 | val 0.84479
  Epoch 013 - train 0.67696 | val 0.75338
  Classification -> best τ=0.655 (val F1=0.2584)
  Directional -> Accuracy: 0.5088, MCC: 0.1595, F1: 0.2222

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.64151 | val 1.32429
  Epoch 012 - train 0.68100 | val 1.39466
  Classification -> best τ=0.650 (val F1=0.3550)
  Directional -> Accuracy: 0.4912, MCC: 0.1268, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.68579 | val 1.00150
  Epoch 016 - train 0.67436 | val 1.17519
  Classification -> best τ=0.520 (val F1=0.2114)
  Directional -> Accuracy: 0.5185, MCC: 0.0105, F1: 0.6667

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.66301 | val 1.82321
  Epoch 014 - train 0.67914 | val 3.10425
  Classification -> best τ=0.685 (val F1=0.1083)
  Directional -> Accuracy: 0.5263, MCC: 0.0827, F1: 0.6747

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.70128 | val 0.78342

[I 2026-02-25 00:56:52,956] Trial 112 finished with value: 0.2609940290741135 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 15, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 32, 'learning_rate': 0.00695327462117603, 'weight_decay': 7.517543630556065e-06, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.8495662718809018, 'early_stopping_min_delta': 0.0004548484323201129}. Best is trial 32 with value: 0.2908549754956826.

  Epoch 012 - train 0.71231 | val 0.83883
  Classification -> best τ=0.480 (val F1=0.2746)
  Directional -> Accuracy: 0.5323, MCC: 0.0625, F1: 0.2162

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2609940290741135
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 15
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.72249 | val 0.85518
  Epoch 016 - train 0.71090 | val 0.75687
  Classification -> best τ=0.610 (val F1=0.2851)
  Directional -> Accuracy: 0.5325, MCC: -0.0165, F1: 0.1429

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.63323 | val 0.74298
  Epoch 015 - train 0.61912 | val 0.69022
  Classification -> best τ=0.475 (val F1=0.1641)
  Directional -> Accuracy: 0.6304, MCC: 0.2389, F1: 0.7385

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 16). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.71528 | val 0.78356
  Epoch 011 - train 0.74174 | val 0.88670
  Classification -> best τ=0.525 (val F1=0.2477)
  Directional -> Accuracy: 0.4583, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.68511 | val 1.08254
  Epoch 011 - train 0.69112 | val 1.11763
  Classification -> best τ=0.565 (val F1=0.0784)
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.70298 | val 0.76181
  Epoch 015 - train 0.61322 | val 0.73487
  Classification -> best τ=0.585 (val F1=0.5277)
  Directional -> Accuracy: 0.6154, MCC: 0.3240, F1: 0.5000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.64876 | val 0.70606
  Epoch 017 - train 0.68596 | val 0.73434
  Classification -> best τ=0.535 (val F1=0.3086)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.70607 | val 0.74762
  Epoch 016 - train 0.68444 | val 1.22092
  Classification -> best τ=0.485 (val F1=0.1750)
  Directional -> Accuracy: 0.5000, MCC: 0.1650, F1: 0.5882

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 16). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.65043 | val 1.67895
  Epoch 011 - train 0.64159 | val 1.70654
  Classification -> best τ=0.535 (val F1=0.2786)
  Directional -> Accuracy: 0.6000, MCC: 0.1691, F1: 0.5000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.71313 | val 0.70976
  Epoch 018 - train 0.67156 | val 2.76010
  Classification -> best τ=0.635 (val F1=0.4523)
  Directional -> Accuracy: 0.6098, MCC: 0.0264, F1: 0.2000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 16). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 16). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.66765 | val 0.86906
  Epoch 014 - train 0.67873 | val 0.88551
  Classification -> best τ=0.595 (val F1=0.1587)
  Directional -> Accuracy: 0.5634, MCC: 0.0312, F1: 0.1143

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.68412 | val 1.21995
  Epoch 011 - train 0.71440 | val 0.96740
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.6400

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.68458 | val 0.73085
  Epoch 020 - train 0.64784 | val 0.69273
  Epoch 028 - train 0.64417 | val 0.88442
  Classification -> best τ=0.695 (val F1=0.2987)
  Directional -> Accuracy: 0.6780, MCC: 0.4009, F1: 0.5957

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.68257 | val 0.71113
  Epoch 012 - train 0.67979 | val 0.78711
  Classification -> best τ=0.545 (val F1=0.1700)
  Directional -> Accuracy: 0.5814, MCC: 0.1280, F1: 0.4375

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.72450 | val 0.91903
  Epoch 017 - train 0.67959 | val 0.78427
  Classification -> best τ=0.405 (val F1=0.3192)
  Directional -> Accuracy: 0.6066, MCC: 0.2429, F1: 0.6923

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.67454 | val 0.70212
  Epoch 020 - train 0.64526 | val 0.71094
  Classification -> best τ=0.575 (val F1=0.2955)
  Directional -> Accuracy: 0.4151, MCC: -0.1615, F1: 0.5079

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.64579 | val 1.00978
  Epoch 016 - train 0.65227 | val 0.70532
  Classification -> best τ=0.575 (val F1=0.3677)
  Directional -> Accuracy: 0.5857, MCC: 0.1502, F1: 0.6667

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.68124 | val 0.96066
  Epoch 011 - train 0.70284 | val 0.96835
  Classification -> best τ=0.400 (val F1=0.0842)
  Directional -> Accuracy: 0.6000, MCC: 0.0338, F1: 0.7333

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.69123 | val 0.94113
  Epoch 012 - train 0.67461 | val 1.17161
  Classification -> best τ=0.475 (val F1=0.1733)
  Directional -> Accuracy: 0.6184, MCC: 0.1206, F1: 0.7434

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.69458 | val 0.85471
  Epoch 012 - train 0.68523 | val 1.12091
  Classification -> best τ=0.525 (val F1=0.2013)
  Directional -> Accuracy: 0.4091, MCC: -0.0327, F1: 0.0488

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 16). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.68184 | val 0.80449
  Epoch 013 - train 0.69856 | val 1.21839
  Classification -> best τ=0.545 (val F1=0.3157)
  Directional -> Accuracy: 0.4605, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.63803 | val 0.83420
  Epoch 011 - train 0.66772 | val 1.61774
  Classification -> best τ=0.535 (val F1=0.2185)
  Directional -> Accuracy: 0.4583, MCC: -0.0222, F1: 0.4583

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.68401 | val 1.28836
  Epoch 011 - train 0.66699 | val 1.48059
  Classification -> best τ=0.770 (val F1=0.2264)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.71834 | val 0.78486
  Epoch 018 - train 0.70563 | val 1.21094
  Classification -> best τ=0.755 (val F1=0.3088)
  Directional -> Accuracy: 0.4655, MCC: 0.0286, F1: 0.2791

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.68926 | val 2.24070
  Epoch 013 - train 0.69555 | val 2.45623
  Classification -> best τ=0.405 (val F1=0.2674)
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.67096 | val 0.69437
  Epoch 019 - train 0.65003 | val 0.71519
  Classification -> best τ=0.500 (val F1=0.4218)
  Directional -> Accuracy: 0.5357, MCC: 0.1728, F1: 0.3810

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.65721 | val 0.77200
  Epoch 012 - train 0.67470 | val 0.80258
  Classification -> best τ=0.505 (val F1=0.3721)
  Directional -> Accuracy: 0.5745, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.67657 | val 0.77167
  Epoch 018 - train 0.61001 | val 0.84572
  Classification -> best τ=0.555 (val F1=0.1539)
  Directional -> Accuracy: 0.4884, MCC: -0.0680, F1: 0.5769

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.69857 | val 0.84168
  Epoch 012 - train 0.61074 | val 0.84102
  Classification -> best τ=0.410 (val F1=0.3008)
  Directional -> Accuracy: 0.5517, MCC: 0.1330, F1: 0.5185

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.66403 | val 0.77656
  Epoch 020 - train 0.64816 | val 0.81393
  Epoch 030 - train 0.59185 | val 0.75627
  Classification -> best τ=0.540 (val F1=0.3870)
  Directional -> Accuracy: 0.5952, MCC: 0.2071, F1: 0.5854

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.65337 | val 0.97184
  Epoch 011 - train 0.64672 | val 0.97240
  Classification -> best τ=0.615 (val F1=0.1869)
  Directional -> Accuracy: 0.5455, MCC: 0.1179, F1: 0.3333

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.69695 | val 0.67663
  Epoch 015 - train 0.73039 | val 0.82091
  Classification -> best τ=0.585 (val F1=0.1688)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.68438 | val 0.71212
  Epoch 015 - train 0.65903 | val 0.76579
  Classification -> best τ=0.490 (val F1=0.3546)
  Directional -> Accuracy: 0.5098, MCC: 0.0387, F1: 0.4444

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.67596 | val 0.64823
  Epoch 019 - train 0.68332 | val 0.98687
  Classification -> best τ=0.365 (val F1=0.3677)
  Directional -> Accuracy: 0.5541, MCC: 0.1516, F1: 0.5217

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.73956 | val 0.68504
  Epoch 020 - train 0.62630 | val 0.87417
  Classification -> best τ=0.505 (val F1=0.3223)
  Directional -> Accuracy: 0.5789, MCC: 0.1857, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.75811 | val 0.77099
  Epoch 013 - train 0.65363 | val 1.93862
  Classification -> best τ=0.600 (val F1=0.2585)
  Directional -> Accuracy: 0.5333, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.64419 | val 0.70135
  Epoch 017 - train 0.65952 | val 0.83744
  Classification -> best τ=0.345 (val F1=0.3431)
  Directional -> Accuracy: 0.5672, MCC: 0.2155, F1: 0.4912

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.71423 | val 0.71654
  Epoch 016 - train 0.66944 | val 0.71931
  Classification -> best τ=0.500 (val F1=0.2810)
  Directional -> Accuracy: 0.6512, MCC: 0.3596, F1: 0.5455

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.65462 | val 0.79845
  Epoch 011 - train 0.65495 | val 0.90000
  Classification -> best τ=0.385 (val F1=0.1293)
  Directional -> Accuracy: 0.5263, MCC: 0.0556, F1: 0.5263

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.68792 | val 0.85813
  Epoch 014 - train 0.73785 | val 1.12223
  Classification -> best τ=0.400 (val F1=0.3321)
  Directional -> Accuracy: 0.6170, MCC: 0.0508, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 16). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.61529 | val 0.86725
  Epoch 013 - train 0.61265 | val 1.09243
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.71384 | val 0.77136
  Epoch 016 - train 0.68716 | val 0.81808
  Classification -> best τ=0.535 (val F1=0.4564)
  Directional -> Accuracy: 0.3846, MCC: -0.2182, F1: 0.2941

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 16). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.69905 | val 0.66773
  Epoch 020 - train 0.67857 | val 1.16036
  Classification -> best τ=0.430 (val F1=0.3422)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.68179 | val 0.78152
  Epoch 012 - train 0.75748 | val 0.72621
  Classification -> best τ=0.480 (val F1=0.3254)
  Directional -> Accuracy: 0.5532, MCC: 0.1590, F1: 0.6866

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.73086 | val 1.22072
  Epoch 016 - train 0.61331 | val 1.30760
  Classification -> best τ=0.620 (val F1=0.4339)
  Directional -> Accuracy: 0.4889, MCC: -0.0199, F1: 0.5106

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.71022 | val 0.75551
  Epoch 018 - train 0.66411 | val 0.77561
  Classification -> best τ=0.605 (val F1=0.3447)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.67574 | val 0.99846
  Epoch 013 - train 0.73285 | val 1.16814
  Classification -> best τ=0.565 (val F1=0.1685)
  Directional -> Accuracy: 0.6316, MCC: 0.2730, F1: 0.6316

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.69726 | val 0.99144
  Epoch 011 - train 0.65307 | val 0.96782
  Classification -> best τ=0.475 (val F1=0.4276)
  Directional -> Accuracy: 0.5088, MCC: 0.0304, F1: 0.5484

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.69568 | val 0.99464
  Epoch 016 - train 0.67311 | val 0.85103
  Classification -> best τ=0.480 (val F1=0.1154)
  Directional -> Accuracy: 0.4815, MCC: 0.0000, F1: 0.0000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.67461 | val 1.65948
  Epoch 012 - train 0.71468 | val 1.04848
  Classification -> best τ=0.535 (val F1=0.2157)
  Directional -> Accuracy: 0.4211, MCC: -0.2796, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.67937 | val 0.69294
  Epoch 020 - train 0.68837 | val 0.84857

[I 2026-02-25 00:58:58,049] Trial 113 finished with value: 0.26883109649316617 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 15, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 32, 'learning_rate': 0.008608437818246032, 'weight_decay': 4.418660957494739e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.654096669140211, 'early_stopping_min_delta': 1.1513853061827337e-05}. Best is trial 32 with value: 0.2908549754956826.

  Epoch 024 - train 0.67094 | val 0.87127
  Classification -> best τ=0.565 (val F1=0.3090)
  Directional -> Accuracy: 0.4677, MCC: -0.1415, F1: 0.1081

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.26883109649316617
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 15
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.67575 | val 0.69715
  Epoch 012 - train 0.65868 | val 0.79847
  Classification -> best τ=0.450 (val F1=0.1363)
  Directional -> Accuracy: 0.3766, MCC: -0.2309, F1: 0.4667

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.61017 | val 0.75085
  Epoch 011 - train 0.68933 | val 0.73071
  Classification -> best τ=0.425 (val F1=0.1264)
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 16). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.73443 | val 0.91730
  Epoch 013 - train 0.67189 | val 0.78844
  Classification -> best τ=0.570 (val F1=0.2892)
  Directional -> Accuracy: 0.4583, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.70479 | val 0.82444
  Epoch 012 - train 0.67853 | val 0.94586
  Classification -> best τ=0.410 (val F1=0.1304)
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.63868 | val 0.79059
  Epoch 016 - train 0.59791 | val 1.03752
  Classification -> best τ=0.690 (val F1=0.4042)
  Directional -> Accuracy: 0.6923, MCC: 0.3929, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.69166 | val 0.72001
  Epoch 012 - train 0.63154 | val 0.78517
  Classification -> best τ=0.500 (val F1=0.0823)
  Directional -> Accuracy: 0.4167, MCC: -0.2236, F1: 0.5625

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.69118 | val 0.69851
  Epoch 015 - train 0.68193 | val 0.76639
  Classification -> best τ=0.655 (val F1=0.1715)
  Directional -> Accuracy: 0.6286, MCC: 0.2100, F1: 0.1333

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 16). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.66103 | val 1.31210
  Epoch 011 - train 0.69170 | val 1.65705
  Classification -> best τ=0.540 (val F1=0.0714)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.74838 | val 0.68485
  Epoch 020 - train 0.64500 | val 0.66813
  Epoch 030 - train 0.56644 | val 1.07696
  Classification -> best τ=0.395 (val F1=0.4835)
  Directional -> Accuracy: 0.3659, MCC: 0.0000, F1: 0.5357

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 16). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 16). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.63526 | val 0.91918
  Epoch 012 - train 0.64795 | val 0.99944
  Classification -> best τ=0.400 (val F1=0.1283)
  Directional -> Accuracy: 0.4225, MCC: -0.1358, F1: 0.5941

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.74514 | val 1.01147
  Epoch 011 - train 0.72277 | val 1.41471
  Classification -> best τ=0.530 (val F1=0.1673)
  Directional -> Accuracy: 0.4706, MCC: -0.0172, F1: 0.6197

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.72508 | val 0.93220
  Epoch 011 - train 0.71452 | val 0.87286
  Classification -> best τ=0.530 (val F1=0.1891)
  Directional -> Accuracy: 0.5085, MCC: 0.0000, F1: 0.6742

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.69137 | val 1.35228
  Epoch 012 - train 0.63902 | val 0.88014
  Classification -> best τ=0.530 (val F1=0.1700)
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.67146 | val 0.73273
  Epoch 015 - train 0.64997 | val 0.78380
  Classification -> best τ=0.430 (val F1=0.2906)
  Directional -> Accuracy: 0.5410, MCC: 0.1035, F1: 0.6667

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.65746 | val 2.55927
  Epoch 011 - train 0.66686 | val 2.93604
  Classification -> best τ=0.575 (val F1=0.2798)
  Directional -> Accuracy: 0.5283, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.63588 | val 0.79573
  Epoch 013 - train 0.64040 | val 0.89991
  Classification -> best τ=0.460 (val F1=0.3026)
  Directional -> Accuracy: 0.6143, MCC: 0.2137, F1: 0.6966

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.65990 | val 1.61631
  Epoch 011 - train 0.71604 | val 1.35858
  Classification -> best τ=0.440 (val F1=0.2282)
  Directional -> Accuracy: 0.5167, MCC: 0.1421, F1: 0.4727

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.65569 | val 0.81512
  Epoch 011 - train 0.69650 | val 0.73054
  Classification -> best τ=0.485 (val F1=0.0624)
  Directional -> Accuracy: 0.5789, MCC: -0.0138, F1: 0.7193

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.70750 | val 0.68826
  Epoch 020 - train 0.61748 | val 0.96782
  Epoch 021 - train 0.62401 | val 1.14120
  Classification -> best τ=0.455 (val F1=0.3875)
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 16). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.67733 | val 0.71254
  Epoch 013 - train 0.64692 | val 0.74957
  Classification -> best τ=0.630 (val F1=0.2290)
  Directional -> Accuracy: 0.4605, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.60577 | val 1.00800
  Epoch 013 - train 0.59837 | val 1.21095
  Classification -> best τ=0.445 (val F1=0.3555)
  Directional -> Accuracy: 0.5208, MCC: 0.2619, F1: 0.4103

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.69666 | val 1.05952
  Epoch 011 - train 0.68415 | val 1.12415
  Classification -> best τ=0.520 (val F1=0.0651)
  Directional -> Accuracy: 0.6212, MCC: 0.2434, F1: 0.6377

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.71112 | val 0.77240
  Epoch 011 - train 0.66565 | val 0.75984
  Classification -> best τ=0.555 (val F1=0.2516)
  Directional -> Accuracy: 0.5345, MCC: 0.0951, F1: 0.5263

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.71582 | val 1.87180
  Epoch 011 - train 0.66471 | val 1.93842
  Classification -> best τ=0.470 (val F1=0.1656)
  Directional -> Accuracy: 0.4545, MCC: -0.0684, F1: 0.5909

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.67524 | val 0.63538
  Epoch 020 - train 0.62724 | val 0.79673
  Classification -> best τ=0.595 (val F1=0.4384)
  Directional -> Accuracy: 0.6071, MCC: 0.2284, F1: 0.6071

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.62423 | val 0.77338
  Epoch 011 - train 0.70484 | val 0.80284
  Classification -> best τ=0.530 (val F1=0.2067)
  Directional -> Accuracy: 0.4681, MCC: -0.0426, F1: 0.4681

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.69922 | val 0.76582
  Epoch 011 - train 0.65068 | val 0.76233
  Classification -> best τ=0.500 (val F1=0.1309)
  Directional -> Accuracy: 0.5349, MCC: 0.0593, F1: 0.5833

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.68925 | val 0.79374
  Epoch 011 - train 0.69122 | val 0.79283
  Classification -> best τ=0.460 (val F1=0.2033)
  Directional -> Accuracy: 0.5517, MCC: 0.0000, F1: 0.7111

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.65562 | val 0.68737
  Epoch 020 - train 0.57309 | val 0.79015
  Epoch 030 - train 0.59856 | val 0.64506
  Classification -> best τ=0.440 (val F1=0.3590)
  Directional -> Accuracy: 0.5952, MCC: 0.1736, F1: 0.6531

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.67425 | val 1.19095
  Epoch 011 - train 0.69075 | val 0.96401
  Classification -> best τ=0.560 (val F1=0.3154)
  Directional -> Accuracy: 0.5227, MCC: 0.0563, F1: 0.3226

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.66129 | val 0.73780
  Epoch 011 - train 0.70349 | val 0.76476
  Classification -> best τ=0.535 (val F1=0.1778)
  Directional -> Accuracy: 0.4091, MCC: -0.1876, F1: 0.0714

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.69425 | val 0.76000
  Epoch 015 - train 0.64466 | val 0.78129
  Classification -> best τ=0.520 (val F1=0.2296)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.68156 | val 0.74215
  Epoch 015 - train 0.64909 | val 0.99204
  Classification -> best τ=0.435 (val F1=0.2633)
  Directional -> Accuracy: 0.5405, MCC: 0.1770, F1: 0.4333

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.63705 | val 0.70352
  Epoch 011 - train 0.60296 | val 0.71430
  Classification -> best τ=0.515 (val F1=0.3223)
  Directional -> Accuracy: 0.6053, MCC: 0.2265, F1: 0.5161

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.63962 | val 1.01413
  Epoch 013 - train 0.62319 | val 1.27756
  Classification -> best τ=0.500 (val F1=0.2922)
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.6364

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.62679 | val 0.78392
  Epoch 014 - train 0.61809 | val 0.69515
  Classification -> best τ=0.400 (val F1=0.2973)
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.77454 | val 0.85749
  Epoch 020 - train 0.60100 | val 0.76556
  Epoch 026 - train 0.57569 | val 0.86732
  Classification -> best τ=0.585 (val F1=0.3337)
  Directional -> Accuracy: 0.5116, MCC: 0.0641, F1: 0.2222

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.66327 | val 0.82578
  Epoch 013 - train 0.63955 | val 0.75649
  Classification -> best τ=0.445 (val F1=0.2830)
  Directional -> Accuracy: 0.5088, MCC: 0.0148, F1: 0.4815

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.70266 | val 0.77133
  Epoch 011 - train 0.64519 | val 0.84341
  Classification -> best τ=0.520 (val F1=0.3026)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 16). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.55965 | val 1.08296
  Epoch 013 - train 0.61299 | val 1.55315
  Classification -> best τ=0.520 (val F1=0.1974)
  Directional -> Accuracy: 0.3250, MCC: -0.2182, F1: 0.4906

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.71732 | val 0.91223
  Epoch 011 - train 0.68297 | val 0.82563
  Classification -> best τ=0.515 (val F1=0.2496)
  Directional -> Accuracy: 0.4615, MCC: -0.0976, F1: 0.5333

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 16). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.69910 | val 0.71851
  Epoch 011 - train 0.63266 | val 0.76651
  Classification -> best τ=0.580 (val F1=0.2296)
  Directional -> Accuracy: 0.5132, MCC: 0.0676, F1: 0.0976

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.68313 | val 0.70386
  Epoch 011 - train 0.71657 | val 0.69859
  Classification -> best τ=0.535 (val F1=0.1733)
  Directional -> Accuracy: 0.5319, MCC: 0.1460, F1: 0.2143

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.54629 | val 0.88864
  Epoch 011 - train 0.63571 | val 1.18159
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.72895 | val 0.78499
  Epoch 013 - train 0.62594 | val 0.82169
  Classification -> best τ=0.520 (val F1=0.4880)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.68216 | val 1.07948
  Epoch 011 - train 0.66523 | val 0.98190
  Classification -> best τ=0.510 (val F1=0.0133)
  Directional -> Accuracy: 0.4912, MCC: -0.1280, F1: 0.6420

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.66195 | val 1.32629
  Epoch 011 - train 0.67122 | val 1.19802
  Classification -> best τ=0.620 (val F1=0.2739)
  Directional -> Accuracy: 0.5088, MCC: 0.0681, F1: 0.6216

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.67694 | val 1.33724
  Epoch 018 - train 0.63809 | val 3.05601
  Classification -> best τ=0.550 (val F1=0.2114)
  Directional -> Accuracy: 0.6296, MCC: 0.2610, F1: 0.6296

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.68965 | val 1.29270
  Epoch 011 - train 0.67248 | val 1.29127
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.66277 | val 1.26677

[I 2026-02-25 01:00:49,006] Trial 114 finished with value: 0.2295240422507755 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 15, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 32, 'learning_rate': 0.002998369920733854, 'weight_decay': 3.3807405062429274e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.5196931247141747, 'early_stopping_min_delta': 0.003052810689949673}. Best is trial 32 with value: 0.2908549754956826.

  Epoch 013 - train 0.64727 | val 1.06005
  Classification -> best τ=0.500 (val F1=0.3165)
  Directional -> Accuracy: 0.5161, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2295240422507755
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 15
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.63679 | val 0.75587
  Epoch 020 - train 0.53680 | val 1.00283
  Epoch 022 - train 0.59108 | val 1.03715
  Classification -> best τ=0.655 (val F1=0.2851)
  Directional -> Accuracy: 0.5195, MCC: -0.0246, F1: 0.2449

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.61817 | val 1.19846
  Epoch 017 - train 0.47795 | val 1.54310
  Classification -> best τ=0.425 (val F1=0.0406)
  Directional -> Accuracy: 0.5870, MCC: 0.1700, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 16). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.60207 | val 0.75622
  Epoch 017 - train 0.46097 | val 1.24336
  Classification -> best τ=0.585 (val F1=0.2743)
  Directional -> Accuracy: 0.5417, MCC: 0.1870, F1: 0.3529

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.60613 | val 1.22813
  Epoch 016 - train 0.59516 | val 0.94735
  Classification -> best τ=0.505 (val F1=0.1242)
  Directional -> Accuracy: 0.4533, MCC: -0.0604, F1: 0.3492

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.53203 | val 0.92911
  Epoch 018 - train 0.42302 | val 1.68040
  Classification -> best τ=0.480 (val F1=0.2556)
  Directional -> Accuracy: 0.5577, MCC: 0.1512, F1: 0.7089

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.45678 | val 0.73548
  Epoch 018 - train 0.38665 | val 1.61056
  Classification -> best τ=0.520 (val F1=0.2270)
  Directional -> Accuracy: 0.5208, MCC: 0.1459, F1: 0.6761

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.62954 | val 0.76767
  Epoch 016 - train 0.55342 | val 0.92118
  Classification -> best τ=0.480 (val F1=0.2610)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.5714

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 16). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.43258 | val 1.60872
  Epoch 020 - train 0.37423 | val 1.70067
  Classification -> best τ=0.570 (val F1=0.3780)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.60876 | val 1.08612
  Epoch 016 - train 0.48063 | val 1.68018
  Classification -> best τ=0.540 (val F1=0.2919)
  Directional -> Accuracy: 0.6585, MCC: 0.2442, F1: 0.5000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 16). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 16). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.58028 | val 0.82050
  Epoch 018 - train 0.57252 | val 1.15873
  Classification -> best τ=0.465 (val F1=0.1631)
  Directional -> Accuracy: 0.5070, MCC: 0.0831, F1: 0.5783

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.59935 | val 1.30360
  Epoch 016 - train 0.47123 | val 1.45450
  Classification -> best τ=0.490 (val F1=0.0296)
  Directional -> Accuracy: 0.4314, MCC: -0.1278, F1: 0.4727

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.61955 | val 0.89922
  Epoch 018 - train 0.52173 | val 1.35624
  Classification -> best τ=0.580 (val F1=0.2671)
  Directional -> Accuracy: 0.6102, MCC: 0.2234, F1: 0.6567

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.54174 | val 2.34258
  Epoch 017 - train 0.46622 | val 5.12362
  Classification -> best τ=0.520 (val F1=0.0783)
  Directional -> Accuracy: 0.5581, MCC: 0.0901, F1: 0.4571

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.62774 | val 0.85955
  Epoch 018 - train 0.54611 | val 1.03462
  Classification -> best τ=0.300 (val F1=0.3175)
  Directional -> Accuracy: 0.5410, MCC: 0.1155, F1: 0.6744

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.54453 | val 3.92573
  Epoch 018 - train 0.41909 | val 5.41186
  Classification -> best τ=0.530 (val F1=0.3029)
  Directional -> Accuracy: 0.5472, MCC: 0.0914, F1: 0.5200

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.57311 | val 1.02942
  Epoch 016 - train 0.50892 | val 1.44107
  Classification -> best τ=0.550 (val F1=0.2679)
  Directional -> Accuracy: 0.5429, MCC: 0.0661, F1: 0.6098

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.60545 | val 1.90611
  Epoch 016 - train 0.53067 | val 2.90129
  Classification -> best τ=0.490 (val F1=0.0842)
  Directional -> Accuracy: 0.4500, MCC: -0.1360, F1: 0.5352

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.61724 | val 1.33783
  Epoch 019 - train 0.56477 | val 1.10554
  Classification -> best τ=0.405 (val F1=0.1764)
  Directional -> Accuracy: 0.5526, MCC: -0.0365, F1: 0.6852

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.60600 | val 1.48269
  Epoch 018 - train 0.51971 | val 1.97949
  Classification -> best τ=0.410 (val F1=0.2518)
  Directional -> Accuracy: 0.5000, MCC: 0.1525, F1: 0.3529

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 16). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.56241 | val 0.70405
  Epoch 020 - train 0.50406 | val 0.99006
  Classification -> best τ=0.590 (val F1=0.3761)
  Directional -> Accuracy: 0.4868, MCC: 0.0747, F1: 0.1702

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.56978 | val 1.06794
  Epoch 020 - train 0.45506 | val 1.85773
  Epoch 021 - train 0.44256 | val 1.89091
  Classification -> best τ=0.605 (val F1=0.2471)
  Directional -> Accuracy: 0.3958, MCC: -0.0176, F1: 0.1714

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.57366 | val 1.65593
  Epoch 016 - train 0.51745 | val 1.33148
  Classification -> best τ=0.470 (val F1=0.1177)
  Directional -> Accuracy: 0.5152, MCC: 0.1240, F1: 0.6735

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.54351 | val 1.22387
  Epoch 016 - train 0.52012 | val 1.92238
  Classification -> best τ=0.575 (val F1=0.3198)
  Directional -> Accuracy: 0.5172, MCC: 0.0253, F1: 0.5625

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.56911 | val 4.87413
  Epoch 016 - train 0.52661 | val 4.01109
  Classification -> best τ=0.450 (val F1=0.1878)
  Directional -> Accuracy: 0.5455, MCC: 0.1038, F1: 0.5714

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.60716 | val 0.87622
  Epoch 020 - train 0.46847 | val 1.05737
  Epoch 023 - train 0.44976 | val 1.26722
  Classification -> best τ=0.530 (val F1=0.4595)
  Directional -> Accuracy: 0.5357, MCC: 0.1728, F1: 0.3810

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.53878 | val 0.99149
  Epoch 016 - train 0.38908 | val 1.63136
  Classification -> best τ=0.540 (val F1=0.2717)
  Directional -> Accuracy: 0.5957, MCC: 0.1273, F1: 0.1739

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.55512 | val 1.59103
  Epoch 016 - train 0.47099 | val 1.49780
  Classification -> best τ=0.420 (val F1=0.1508)
  Directional -> Accuracy: 0.5581, MCC: 0.0993, F1: 0.6122

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.57538 | val 0.84398
  Epoch 019 - train 0.47346 | val 1.19053
  Classification -> best τ=0.335 (val F1=0.2369)
  Directional -> Accuracy: 0.6034, MCC: 0.1802, F1: 0.6933

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.57688 | val 0.74269
  Epoch 020 - train 0.48248 | val 1.08057
  Epoch 030 - train 0.43048 | val 1.57184
  Classification -> best τ=0.750 (val F1=0.4193)
  Directional -> Accuracy: 0.6190, MCC: 0.2781, F1: 0.5789

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.52849 | val 0.79315
  Epoch 017 - train 0.38790 | val 2.83387
  Classification -> best τ=0.515 (val F1=0.1869)
  Directional -> Accuracy: 0.5682, MCC: 0.1376, F1: 0.5957

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.62294 | val 0.73756
  Epoch 019 - train 0.39849 | val 1.27851
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.52230 | val 1.04205
  Epoch 016 - train 0.46029 | val 1.26978
  Classification -> best τ=0.500 (val F1=0.2454)
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.60000 | val 1.75895
  Epoch 017 - train 0.52043 | val 2.88204
  Classification -> best τ=0.395 (val F1=0.3044)
  Directional -> Accuracy: 0.5405, MCC: 0.1386, F1: 0.4848

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.51958 | val 0.79696
  Epoch 016 - train 0.44959 | val 0.82557
  Classification -> best τ=0.490 (val F1=0.4045)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.5366

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.53293 | val 1.42020
  Epoch 016 - train 0.38623 | val 3.01663
  Classification -> best τ=0.500 (val F1=0.2017)
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.6364

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.55132 | val 0.74120
  Epoch 020 - train 0.46044 | val 0.95126
  Epoch 021 - train 0.47176 | val 0.89820
  Classification -> best τ=0.375 (val F1=0.3954)
  Directional -> Accuracy: 0.5075, MCC: 0.1674, F1: 0.2979

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.55338 | val 0.72978
  Epoch 018 - train 0.41889 | val 1.00698
  Classification -> best τ=0.460 (val F1=0.2683)
  Directional -> Accuracy: 0.6512, MCC: 0.3596, F1: 0.5455

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.60421 | val 0.79679
  Epoch 016 - train 0.55465 | val 0.90297
  Classification -> best τ=0.375 (val F1=0.1676)
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.50094 | val 1.01805
  Epoch 020 - train 0.40477 | val 1.17809
  Classification -> best τ=0.320 (val F1=0.1162)
  Directional -> Accuracy: 0.5745, MCC: -0.0074, F1: 0.7059

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 16). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.52660 | val 0.84367
  Epoch 016 - train 0.40649 | val 1.36117
  Classification -> best τ=0.500 (val F1=0.0413)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.55569 | val 0.78261
  Epoch 020 - train 0.39521 | val 1.63040
  Classification -> best τ=0.400 (val F1=0.2707)
  Directional -> Accuracy: 0.5128, MCC: -0.0473, F1: 0.6545

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 16). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.61050 | val 1.56405
  Epoch 019 - train 0.52761 | val 3.87076
  Classification -> best τ=0.585 (val F1=0.2671)
  Directional -> Accuracy: 0.5132, MCC: 0.0264, F1: 0.4932

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.58374 | val 0.95268
  Epoch 018 - train 0.46750 | val 0.83584
  Classification -> best τ=0.500 (val F1=0.1565)
  Directional -> Accuracy: 0.5106, MCC: 0.0065, F1: 0.6567

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.54394 | val 1.29378
  Epoch 016 - train 0.36965 | val 2.28315
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.54088 | val 0.87681
  Epoch 019 - train 0.41519 | val 1.05364
  Classification -> best τ=0.470 (val F1=0.4228)
  Directional -> Accuracy: 0.5250, MCC: 0.3380, F1: 0.5957

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.58714 | val 2.83766
  Epoch 020 - train 0.51013 | val 2.93735
  Classification -> best τ=0.590 (val F1=0.2719)
  Directional -> Accuracy: 0.4561, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.55868 | val 2.23153
  Epoch 017 - train 0.49713 | val 2.80798
  Classification -> best τ=0.535 (val F1=0.3723)
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.56321 | val 1.65229
  Epoch 018 - train 0.49203 | val 2.61100
  Classification -> best τ=0.440 (val F1=0.1200)
  Directional -> Accuracy: 0.4444, MCC: -0.1310, F1: 0.5312

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.57864 | val 2.47776
  Epoch 016 - train 0.53878 | val 3.70705
  Classification -> best τ=0.395 (val F1=0.1181)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.63585 | val 2.40500

[I 2026-02-25 01:03:21,157] Trial 115 finished with value: 0.22919078046617541 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 15, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 32, 'learning_rate': 0.003984606721771023, 'weight_decay': 2.0086473509604624e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 30, 'huber_delta': 1.7096454416471092, 'early_stopping_min_delta': 0.001166833454452582}. Best is trial 32 with value: 0.2908549754956826.

  Epoch 018 - train 0.50636 | val 2.72168
  Classification -> best τ=0.575 (val F1=0.2653)
  Directional -> Accuracy: 0.5000, MCC: -0.0679, F1: 0.0606

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.22919078046617541
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 15
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.64858 | val 0.68288
  Epoch 020 - train 0.61720 | val 1.03645
  Epoch 021 - train 0.61504 | val 1.12294
  Classification -> best τ=0.590 (val F1=0.2453)
  Directional -> Accuracy: 0.5195, MCC: -0.0708, F1: 0.0976

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.60584 | val 1.04907
  Epoch 012 - train 0.63536 | val 1.31140
  Classification -> best τ=0.475 (val F1=0.1202)
  Directional -> Accuracy: 0.6304, MCC: 0.2573, F1: 0.7463

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 16). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.68891 | val 0.72530
  Epoch 015 - train 0.65481 | val 0.79195
  Classification -> best τ=0.570 (val F1=0.3731)
  Directional -> Accuracy: 0.4792, MCC: 0.0399, F1: 0.1935

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.66553 | val 0.73512
  Epoch 011 - train 0.65950 | val 0.74367
  Classification -> best τ=0.465 (val F1=0.0609)
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.56226 | val 1.38967
  Epoch 013 - train 0.60124 | val 1.24291
  Classification -> best τ=0.425 (val F1=0.4042)
  Directional -> Accuracy: 0.7115, MCC: 0.4361, F1: 0.7059

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.58892 | val 0.90083
  Epoch 011 - train 0.60100 | val 0.96867
  Classification -> best τ=0.485 (val F1=0.2080)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.2000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.67579 | val 0.71463
  Epoch 014 - train 0.66279 | val 0.77827
  Classification -> best τ=0.535 (val F1=0.2143)
  Directional -> Accuracy: 0.4857, MCC: 0.0503, F1: 0.5263

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 16). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.61027 | val 1.39686
  Epoch 011 - train 0.61227 | val 1.51750
  Classification -> best τ=0.530 (val F1=0.1048)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.65809 | val 0.91887
  Epoch 012 - train 0.65283 | val 1.21788
  Classification -> best τ=0.530 (val F1=0.3877)
  Directional -> Accuracy: 0.3659, MCC: 0.0000, F1: 0.5357

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 16). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 16). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.67346 | val 0.76736
  Epoch 011 - train 0.60667 | val 0.78357
  Classification -> best τ=0.460 (val F1=0.1114)
  Directional -> Accuracy: 0.4789, MCC: -0.1214, F1: 0.2449

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.68106 | val 1.11134
  Epoch 011 - train 0.64301 | val 0.93808
  Classification -> best τ=0.540 (val F1=0.0979)
  Directional -> Accuracy: 0.4706, MCC: -0.0119, F1: 0.6301

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.66739 | val 0.69931
  Epoch 017 - train 0.64858 | val 0.73273
  Classification -> best τ=0.625 (val F1=0.2987)
  Directional -> Accuracy: 0.5085, MCC: 0.1291, F1: 0.0645

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.62339 | val 0.80039
  Epoch 011 - train 0.65307 | val 0.78260
  Classification -> best τ=0.520 (val F1=0.1208)
  Directional -> Accuracy: 0.5814, MCC: 0.1155, F1: 0.2500

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.65256 | val 0.63595
  Epoch 017 - train 0.66681 | val 0.71605
  Classification -> best τ=0.355 (val F1=0.2640)
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.63842 | val 2.48567
  Epoch 011 - train 0.60147 | val 2.04585
  Classification -> best τ=0.490 (val F1=0.2145)
  Directional -> Accuracy: 0.6792, MCC: 0.3629, F1: 0.6792

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.62144 | val 0.74322
  Epoch 011 - train 0.60264 | val 0.92235
  Classification -> best τ=0.485 (val F1=0.2605)
  Directional -> Accuracy: 0.5571, MCC: 0.1312, F1: 0.7103

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.67066 | val 1.11805
  Epoch 011 - train 0.64194 | val 1.08936
  Classification -> best τ=0.555 (val F1=0.2219)
  Directional -> Accuracy: 0.3833, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.65480 | val 1.11723
  Epoch 011 - train 0.66839 | val 0.96849
  Classification -> best τ=0.495 (val F1=0.1800)
  Directional -> Accuracy: 0.3816, MCC: -0.1554, F1: 0.2769

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.66286 | val 1.07644
  Epoch 012 - train 0.61717 | val 1.11786
  Classification -> best τ=0.460 (val F1=0.3001)
  Directional -> Accuracy: 0.5152, MCC: 0.0421, F1: 0.5429

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 16). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.63321 | val 0.67637
  Epoch 020 - train 0.56027 | val 0.74009
  Classification -> best τ=0.435 (val F1=0.3660)
  Directional -> Accuracy: 0.5789, MCC: 0.1760, F1: 0.5556

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.63212 | val 0.80121
  Epoch 011 - train 0.60986 | val 0.74261
  Classification -> best τ=0.530 (val F1=0.1567)
  Directional -> Accuracy: 0.3958, MCC: 0.1130, F1: 0.0645

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.68009 | val 1.19435
  Epoch 011 - train 0.65726 | val 1.22374
  Classification -> best τ=0.490 (val F1=0.1011)
  Directional -> Accuracy: 0.6515, MCC: 0.3043, F1: 0.6349

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.66859 | val 0.91808
  Epoch 012 - train 0.64696 | val 0.93843
  Classification -> best τ=0.565 (val F1=0.2272)
  Directional -> Accuracy: 0.5517, MCC: 0.1248, F1: 0.5517

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.64966 | val 1.78118
  Epoch 011 - train 0.61250 | val 2.05684
  Classification -> best τ=0.495 (val F1=0.1878)
  Directional -> Accuracy: 0.5455, MCC: 0.0876, F1: 0.5161

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.61196 | val 0.70812
  Epoch 015 - train 0.59940 | val 0.84125
  Classification -> best τ=0.535 (val F1=0.5125)
  Directional -> Accuracy: 0.5536, MCC: 0.2064, F1: 0.4186

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.56402 | val 0.90902
  Epoch 013 - train 0.53398 | val 0.83796
  Classification -> best τ=0.490 (val F1=0.2067)
  Directional -> Accuracy: 0.5957, MCC: 0.1713, F1: 0.0952

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.67535 | val 0.71759
  Epoch 017 - train 0.61136 | val 0.72644
  Classification -> best τ=0.535 (val F1=0.2587)
  Directional -> Accuracy: 0.5581, MCC: 0.0089, F1: 0.6885

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.65492 | val 0.84176
  Epoch 011 - train 0.63430 | val 0.84721
  Classification -> best τ=0.510 (val F1=0.3358)
  Directional -> Accuracy: 0.5172, MCC: 0.1923, F1: 0.2632

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.67180 | val 0.72357
  Epoch 020 - train 0.67200 | val 0.77561
  Epoch 023 - train 0.60846 | val 0.77871
  Classification -> best τ=0.620 (val F1=0.4804)
  Directional -> Accuracy: 0.5714, MCC: 0.1435, F1: 0.5909

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.58359 | val 1.44181
  Epoch 011 - train 0.70167 | val 1.48875
  Classification -> best τ=0.525 (val F1=0.2263)
  Directional -> Accuracy: 0.4545, MCC: -0.0925, F1: 0.4000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.64537 | val 0.73911
  Epoch 012 - train 0.71387 | val 0.81267
  Classification -> best τ=0.525 (val F1=0.1413)
  Directional -> Accuracy: 0.5227, MCC: 0.1234, F1: 0.3636

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.58656 | val 0.86832
  Epoch 014 - train 0.56101 | val 0.81401
  Classification -> best τ=0.485 (val F1=0.2325)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.62341 | val 1.01987
  Epoch 014 - train 0.63700 | val 1.73178
  Classification -> best τ=0.405 (val F1=0.3290)
  Directional -> Accuracy: 0.5270, MCC: 0.1259, F1: 0.4444

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.60255 | val 0.72096
  Epoch 011 - train 0.60022 | val 0.71829
  Classification -> best τ=0.455 (val F1=0.3223)
  Directional -> Accuracy: 0.5526, MCC: 0.1291, F1: 0.6531

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.67957 | val 0.92013
  Epoch 011 - train 0.65105 | val 0.97664
  Classification -> best τ=0.460 (val F1=0.1410)
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.6364

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.58257 | val 0.74946
  Epoch 011 - train 0.64410 | val 0.73300
  Classification -> best τ=0.390 (val F1=0.3767)
  Directional -> Accuracy: 0.6269, MCC: 0.2432, F1: 0.6667

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.63626 | val 0.75202
  Epoch 011 - train 0.60908 | val 0.80919
  Classification -> best τ=0.490 (val F1=0.2306)
  Directional -> Accuracy: 0.6744, MCC: 0.4004, F1: 0.5882

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.60971 | val 0.73228
  Epoch 011 - train 0.61551 | val 0.71228
  Classification -> best τ=0.490 (val F1=0.2166)
  Directional -> Accuracy: 0.5439, MCC: 0.1810, F1: 0.6579

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.62629 | val 1.06545
  Epoch 014 - train 0.58643 | val 0.80748
  Classification -> best τ=0.600 (val F1=0.2255)
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 16). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.55040 | val 0.95781
  Epoch 011 - train 0.57808 | val 1.00906
  Classification -> best τ=0.515 (val F1=0.4472)
  Directional -> Accuracy: 0.3750, MCC: 0.1175, F1: 0.5283

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.64270 | val 0.76774
  Epoch 011 - train 0.63765 | val 0.80108
  Classification -> best τ=0.520 (val F1=0.0406)
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.0000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 16). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.60300 | val 1.01045
  Epoch 012 - train 0.63270 | val 1.14970
  Classification -> best τ=0.430 (val F1=0.3218)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.71240 | val 0.73891
  Epoch 011 - train 0.65184 | val 0.77226
  Classification -> best τ=0.520 (val F1=0.2046)
  Directional -> Accuracy: 0.4894, MCC: -0.0065, F1: 0.1429

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.59546 | val 1.47655
  Epoch 011 - train 0.60428 | val 1.70675
  Classification -> best τ=0.475 (val F1=0.0737)
  Directional -> Accuracy: 0.6000, MCC: 0.1673, F1: 0.7000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.62881 | val 0.79524
  Epoch 020 - train 0.56672 | val 0.99236
  Epoch 023 - train 0.54285 | val 1.18774
  Classification -> best τ=0.570 (val F1=0.4587)
  Directional -> Accuracy: 0.4750, MCC: 0.2774, F1: 0.5714

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.63534 | val 1.23682
  Epoch 011 - train 0.66484 | val 1.13576
  Classification -> best τ=0.520 (val F1=0.2973)
  Directional -> Accuracy: 0.5439, MCC: 0.0000, F1: 0.7045

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.60706 | val 1.84065
  Epoch 011 - train 0.57909 | val 1.71482
  Classification -> best τ=0.535 (val F1=0.2554)
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.67333 | val 1.35335
  Epoch 011 - train 0.66774 | val 1.45388
  Classification -> best τ=0.515 (val F1=0.1884)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.63878 | val 0.92551
  Epoch 011 - train 0.62480 | val 0.85188
  Classification -> best τ=0.535 (val F1=0.1141)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...

[I 2026-02-25 01:03:51,349] Trial 116 finished with value: 0.24260188010607212 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 15, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 32, 'learning_rate': 0.005534610994435636, 'weight_decay': 0.00021619822763047097, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 1.7727524829444927, 'early_stopping_min_delta': 0.002005014563727537}. Best is trial 32 with value: 0.2908549754956826.

  Epoch 010 - train 0.64803 | val 0.92668
  Epoch 011 - train 0.61262 | val 0.83591
  Classification -> best τ=0.510 (val F1=0.2653)
  Directional -> Accuracy: 0.5161, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.24260188010607212
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 15
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.70735 | val 0.70193
  Epoch 020 - train 0.65185 | val 0.68252
  Epoch 030 - train 0.66824 | val 0.72806
  Classification -> best τ=0.500 (val F1=0.2412)
  Directional -> Accuracy: 0.5195, MCC: -0.0112, F1: 0.3019

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.64736 | val 0.75901
  Epoch 014 - train 0.55036 | val 1.59123
  Classification -> best τ=0.370 (val F1=0.2370)
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 16). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.68237 | val 0.91941
  Epoch 013 - train 0.66987 | val 1.01698
  Classification -> best τ=0.495 (val F1=0.3020)
  Directional -> Accuracy: 0.6458, MCC: 0.3080, F1: 0.7385

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.71221 | val 1.62741
  Epoch 013 - train 0.66884 | val 1.49011
  Classification -> best τ=0.250 (val F1=0.3357)
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.61468 | val 1.56668
  Epoch 013 - train 0.58444 | val 0.88236
  Classification -> best τ=0.460 (val F1=0.2787)
  Directional -> Accuracy: 0.6538, MCC: 0.3022, F1: 0.7188

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.63479 | val 2.33849
  Epoch 012 - train 0.60037 | val 2.94378
  Classification -> best τ=0.420 (val F1=0.4508)
  Directional -> Accuracy: 0.5208, MCC: 0.0534, F1: 0.6349

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.78846 | val 0.75789
  Epoch 014 - train 0.69153 | val 0.80531
  Classification -> best τ=0.440 (val F1=0.2116)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.5714

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 16). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.67525 | val 2.65185
  Epoch 012 - train 0.60147 | val 4.07287
  Classification -> best τ=0.475 (val F1=0.2936)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.69194 | val 0.79239
  Epoch 020 - train 0.61479 | val 1.00147
  Epoch 029 - train 0.60097 | val 1.85388
  Classification -> best τ=0.800 (val F1=0.4315)
  Directional -> Accuracy: 0.5854, MCC: -0.0280, F1: 0.1905

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 16). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 16). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.67848 | val 1.66437
  Epoch 018 - train 0.64647 | val 0.92637
  Classification -> best τ=0.830 (val F1=0.1587)
  Directional -> Accuracy: 0.5634, MCC: 0.0633, F1: 0.3111

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.69347 | val 1.35998
  Epoch 019 - train 0.68169 | val 1.39555
  Classification -> best τ=0.480 (val F1=0.1557)
  Directional -> Accuracy: 0.5098, MCC: 0.0331, F1: 0.5455

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.71418 | val 1.03826
  Epoch 013 - train 0.63813 | val 1.22388
  Classification -> best τ=0.790 (val F1=0.3071)
  Directional -> Accuracy: 0.6780, MCC: 0.3587, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.70397 | val 0.81702
  Epoch 012 - train 0.71071 | val 1.64879
  Classification -> best τ=0.710 (val F1=0.0171)
  Directional -> Accuracy: 0.3953, MCC: -0.1823, F1: 0.5357

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.69163 | val 0.80342
  Epoch 017 - train 0.67706 | val 0.80896
  Classification -> best τ=0.480 (val F1=0.3400)
  Directional -> Accuracy: 0.5574, MCC: 0.1142, F1: 0.6087

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.67445 | val 4.18592
  Epoch 011 - train 0.68455 | val 3.29187
  Classification -> best τ=0.605 (val F1=0.2262)
  Directional -> Accuracy: 0.5283, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.66058 | val 1.28135
  Epoch 011 - train 0.64029 | val 1.36155
  Classification -> best τ=0.315 (val F1=0.2927)
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.67466 | val 2.17798
  Epoch 011 - train 0.71253 | val 1.81980
  Classification -> best τ=0.295 (val F1=0.0842)
  Directional -> Accuracy: 0.6000, MCC: 0.0990, F1: 0.7073

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.73099 | val 0.71738
  Epoch 011 - train 0.67754 | val 1.00274
  Classification -> best τ=0.570 (val F1=0.1923)
  Directional -> Accuracy: 0.3816, MCC: -0.1430, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.76323 | val 0.70830
  Epoch 020 - train 0.68674 | val 0.91532
  Epoch 026 - train 0.65303 | val 0.94090
  Classification -> best τ=0.455 (val F1=0.2726)
  Directional -> Accuracy: 0.5152, MCC: 0.1796, F1: 0.3846

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 16). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.66092 | val 1.12701
  Epoch 013 - train 0.67374 | val 2.19755
  Classification -> best τ=0.490 (val F1=0.3420)
  Directional -> Accuracy: 0.4868, MCC: 0.0473, F1: 0.2353

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.62812 | val 8.67637
  Epoch 011 - train 0.64867 | val 8.67302
  Classification -> best τ=0.600 (val F1=0.2058)
  Directional -> Accuracy: 0.6042, MCC: -0.0222, F1: 0.7467

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.66305 | val 2.98152
  Epoch 013 - train 0.67264 | val 2.19575
  Classification -> best τ=0.295 (val F1=0.2070)
  Directional -> Accuracy: 0.5909, MCC: 0.1928, F1: 0.6494

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.66567 | val 1.46001
  Epoch 012 - train 0.73610 | val 1.35242
  Classification -> best τ=0.610 (val F1=0.1780)
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.67868 | val 2.78366
  Epoch 018 - train 0.65377 | val 2.24228
  Classification -> best τ=0.480 (val F1=0.1318)
  Directional -> Accuracy: 0.5152, MCC: -0.0201, F1: 0.2000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.68504 | val 0.74256
  Epoch 016 - train 0.67246 | val 0.70442
  Classification -> best τ=0.575 (val F1=0.5921)
  Directional -> Accuracy: 0.5357, MCC: 0.1728, F1: 0.3810

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.71802 | val 1.35496
  Epoch 011 - train 0.63909 | val 1.01158
  Classification -> best τ=0.425 (val F1=0.2339)
  Directional -> Accuracy: 0.5745, MCC: 0.0576, F1: 0.2308

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.70600 | val 0.86250
  Epoch 011 - train 0.70960 | val 0.87709
  Classification -> best τ=0.595 (val F1=0.1377)
  Directional -> Accuracy: 0.5814, MCC: 0.1146, F1: 0.6667

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.72202 | val 0.86182
  Epoch 014 - train 0.71863 | val 1.07052
  Classification -> best τ=0.410 (val F1=0.2908)
  Directional -> Accuracy: 0.4828, MCC: 0.1085, F1: 0.1667

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.76929 | val 0.76781
  Epoch 011 - train 0.74046 | val 0.70119
  Classification -> best τ=0.465 (val F1=0.3844)
  Directional -> Accuracy: 0.5952, MCC: 0.1940, F1: 0.7213

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.61830 | val 0.85385
  Epoch 012 - train 0.66637 | val 1.12271
  Classification -> best τ=0.410 (val F1=0.1574)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.76496 | val 1.03689
  Epoch 011 - train 0.71699 | val 1.04805
  Classification -> best τ=0.330 (val F1=0.2374)
  Directional -> Accuracy: 0.5000, MCC: -0.0753, F1: 0.6333

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.66633 | val 0.90595
  Epoch 012 - train 0.60455 | val 0.91135
  Classification -> best τ=0.500 (val F1=0.2366)
  Directional -> Accuracy: 0.5882, MCC: 0.1742, F1: 0.6866

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.72520 | val 0.76307
  Epoch 014 - train 0.70074 | val 1.08633
  Classification -> best τ=0.435 (val F1=0.3717)
  Directional -> Accuracy: 0.5541, MCC: 0.1246, F1: 0.5600

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.63745 | val 1.85606
  Epoch 011 - train 0.57290 | val 2.85597
  Classification -> best τ=0.465 (val F1=0.3130)
  Directional -> Accuracy: 0.5526, MCC: 0.1443, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.62572 | val 1.18712
  Epoch 011 - train 0.71447 | val 1.20866
  Classification -> best τ=0.515 (val F1=0.2857)
  Directional -> Accuracy: 0.6444, MCC: 0.2971, F1: 0.5000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.64878 | val 0.94301
  Epoch 013 - train 0.69133 | val 1.33511
  Classification -> best τ=0.260 (val F1=0.3431)
  Directional -> Accuracy: 0.5522, MCC: 0.1618, F1: 0.5000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.67973 | val 1.02646
  Epoch 012 - train 0.68614 | val 1.17930
  Classification -> best τ=0.520 (val F1=0.1913)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.71105 | val 1.85265
  Epoch 012 - train 0.64955 | val 0.90674
  Classification -> best τ=0.255 (val F1=0.2547)
  Directional -> Accuracy: 0.4912, MCC: 0.1268, F1: 0.6506

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.71594 | val 2.95207
  Epoch 015 - train 0.62743 | val 2.78268
  Classification -> best τ=0.885 (val F1=0.1622)
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 16). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.63725 | val 1.00329
  Epoch 018 - train 0.59808 | val 0.88429
  Classification -> best τ=0.415 (val F1=0.5093)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.69946 | val 1.08811
  Epoch 012 - train 0.62816 | val 0.86693
  Classification -> best τ=0.525 (val F1=0.5649)
  Directional -> Accuracy: 0.5385, MCC: 0.0976, F1: 0.5000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 16). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.71872 | val 0.90458
  Epoch 013 - train 0.67972 | val 0.83246
  Classification -> best τ=0.500 (val F1=0.3422)
  Directional -> Accuracy: 0.5395, MCC: 0.0947, F1: 0.6392

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.69375 | val 0.87648
  Epoch 011 - train 0.68744 | val 0.87879
  Classification -> best τ=0.480 (val F1=0.3086)
  Directional -> Accuracy: 0.5106, MCC: 0.1443, F1: 0.0800

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.62684 | val 1.37202
  Epoch 011 - train 0.60026 | val 2.05927
  Classification -> best τ=0.575 (val F1=0.1474)
  Directional -> Accuracy: 0.5111, MCC: 0.0632, F1: 0.4500

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.64523 | val 0.69833
  Epoch 011 - train 0.71131 | val 0.75051
  Classification -> best τ=0.550 (val F1=0.3780)
  Directional -> Accuracy: 0.6500, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.70887 | val 0.94067
  Epoch 012 - train 0.71677 | val 0.69787
  Classification -> best τ=0.480 (val F1=0.2973)
  Directional -> Accuracy: 0.5439, MCC: 0.0996, F1: 0.5357

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.65265 | val 1.79308
  Epoch 013 - train 0.74207 | val 2.06256
  Classification -> best τ=0.730 (val F1=0.3836)
  Directional -> Accuracy: 0.4912, MCC: 0.1268, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.69734 | val 0.76374
  Epoch 014 - train 0.72812 | val 0.88580
  Classification -> best τ=0.480 (val F1=0.2662)
  Directional -> Accuracy: 0.4444, MCC: -0.1201, F1: 0.5000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.68128 | val 0.92569
  Epoch 011 - train 0.66947 | val 1.39502
  Classification -> best τ=0.635 (val F1=0.1378)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.72858 | val 0.68663

[I 2026-02-25 01:06:50,830] Trial 117 finished with value: 0.27371546736996416 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 15, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 16, 'learning_rate': 0.00799561718426185, 'weight_decay': 1.808919180797299e-05, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.8771446207548441, 'early_stopping_min_delta': 0.0005598719545686875}. Best is trial 32 with value: 0.2908549754956826.

  Epoch 019 - train 0.68395 | val 0.69443
  Classification -> best τ=0.440 (val F1=0.2653)
  Directional -> Accuracy: 0.4516, MCC: -0.1069, F1: 0.3704

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.27371546736996416
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 15
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.68260 | val 0.72114
  Epoch 017 - train 0.65280 | val 0.74860
  Classification -> best τ=0.390 (val F1=0.2783)
  Directional -> Accuracy: 0.4935, MCC: -0.0577, F1: 0.3158

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.62157 | val 0.82615
  Epoch 015 - train 0.57822 | val 0.95553
  Classification -> best τ=0.475 (val F1=0.2573)
  Directional -> Accuracy: 0.6522, MCC: 0.2820, F1: 0.7419

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 16). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.67481 | val 1.33468
  Epoch 012 - train 0.64728 | val 1.10807
  Classification -> best τ=0.560 (val F1=0.3244)
  Directional -> Accuracy: 0.4583, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.66854 | val 1.13925
  Epoch 013 - train 0.65789 | val 0.98103
  Classification -> best τ=0.495 (val F1=0.0913)
  Directional -> Accuracy: 0.5467, MCC: 0.1181, F1: 0.5143

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.57168 | val 1.13204
  Epoch 015 - train 0.64578 | val 0.92418
  Classification -> best τ=0.515 (val F1=0.4260)
  Directional -> Accuracy: 0.6346, MCC: 0.2808, F1: 0.6275

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.64447 | val 0.97728
  Epoch 013 - train 0.55245 | val 1.01677
  Classification -> best τ=0.430 (val F1=0.3693)
  Directional -> Accuracy: 0.5625, MCC: 0.1278, F1: 0.5116

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.68202 | val 0.80528
  Epoch 013 - train 0.66514 | val 0.84911
  Classification -> best τ=0.475 (val F1=0.1633)
  Directional -> Accuracy: 0.4000, MCC: -0.0733, F1: 0.5333

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 16). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.62365 | val 1.54682
  Epoch 011 - train 0.55944 | val 1.60071
  Classification -> best τ=0.510 (val F1=0.3780)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.65242 | val 1.60404
  Epoch 011 - train 0.63312 | val 1.84129
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3659, MCC: 0.0000, F1: 0.5357

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 16). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 16). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.64877 | val 0.98632
  Epoch 012 - train 0.65217 | val 0.87556
  Classification -> best τ=0.455 (val F1=0.1827)
  Directional -> Accuracy: 0.4366, MCC: -0.0388, F1: 0.5833

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.63906 | val 1.10536
  Epoch 012 - train 0.66023 | val 1.46045
  Classification -> best τ=0.520 (val F1=0.1368)
  Directional -> Accuracy: 0.5490, MCC: 0.1136, F1: 0.5818

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.62861 | val 0.79350
  Epoch 020 - train 0.62801 | val 0.92727
  Epoch 021 - train 0.60994 | val 0.76579
  Classification -> best τ=0.860 (val F1=0.2987)
  Directional -> Accuracy: 0.6441, MCC: 0.3591, F1: 0.5116

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.59401 | val 0.90635
  Epoch 016 - train 0.59487 | val 1.06193
  Classification -> best τ=0.390 (val F1=0.3211)
  Directional -> Accuracy: 0.3953, MCC: -0.2482, F1: 0.5667

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.68428 | val 0.75803
  Epoch 020 - train 0.64620 | val 0.97879
  Epoch 023 - train 0.62231 | val 0.93599
  Classification -> best τ=0.380 (val F1=0.3634)
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.61184 | val 2.13992
  Epoch 012 - train 0.60950 | val 1.47683
  Classification -> best τ=0.595 (val F1=0.2798)
  Directional -> Accuracy: 0.5283, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.61419 | val 0.95665
  Epoch 014 - train 0.61471 | val 0.75285
  Classification -> best τ=0.500 (val F1=0.3677)
  Directional -> Accuracy: 0.5143, MCC: -0.0370, F1: 0.6458

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.64304 | val 1.46268
  Epoch 013 - train 0.66792 | val 1.36526
  Classification -> best τ=0.625 (val F1=0.2515)
  Directional -> Accuracy: 0.4833, MCC: 0.2084, F1: 0.3111

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.65521 | val 0.84700
  Epoch 011 - train 0.66307 | val 0.91932
  Classification -> best τ=0.490 (val F1=0.1734)
  Directional -> Accuracy: 0.5658, MCC: 0.0187, F1: 0.6857

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.66681 | val 0.86873
  Epoch 014 - train 0.60225 | val 1.03121
  Classification -> best τ=0.465 (val F1=0.2464)
  Directional -> Accuracy: 0.4242, MCC: 0.0336, F1: 0.0952

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 16). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.64499 | val 0.86254
  Epoch 012 - train 0.63525 | val 0.70841
  Classification -> best τ=0.460 (val F1=0.2337)
  Directional -> Accuracy: 0.5000, MCC: 0.1873, F1: 0.1364

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.64347 | val 0.66364
  Epoch 020 - train 0.53513 | val 0.91840
  Epoch 022 - train 0.51249 | val 0.70975
  Classification -> best τ=0.405 (val F1=0.3736)
  Directional -> Accuracy: 0.4167, MCC: 0.0778, F1: 0.1765

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.65295 | val 1.33452
  Epoch 012 - train 0.59027 | val 1.58293
  Classification -> best τ=0.350 (val F1=0.1677)
  Directional -> Accuracy: 0.4848, MCC: -0.0727, F1: 0.6458

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.67078 | val 0.77947
  Epoch 011 - train 0.63236 | val 0.87335
  Classification -> best τ=0.585 (val F1=0.2272)
  Directional -> Accuracy: 0.6034, MCC: 0.1571, F1: 0.7089

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.66075 | val 2.65777
  Epoch 011 - train 0.67567 | val 2.18548
  Classification -> best τ=0.335 (val F1=0.2319)
  Directional -> Accuracy: 0.4848, MCC: -0.0421, F1: 0.4138

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.67425 | val 0.74829
  Epoch 011 - train 0.63584 | val 0.84050
  Classification -> best τ=0.465 (val F1=0.3370)
  Directional -> Accuracy: 0.5714, MCC: 0.0961, F1: 0.6923

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.63926 | val 0.82902
  Epoch 012 - train 0.59897 | val 0.90979
  Classification -> best τ=0.545 (val F1=0.2582)
  Directional -> Accuracy: 0.5745, MCC: 0.0318, F1: 0.0909

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.67414 | val 0.88271
  Epoch 011 - train 0.64616 | val 1.00962
  Classification -> best τ=0.460 (val F1=0.0680)
  Directional -> Accuracy: 0.5349, MCC: 0.1265, F1: 0.5000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.67955 | val 0.74724
  Epoch 017 - train 0.65622 | val 0.71837
  Classification -> best τ=0.370 (val F1=0.2076)
  Directional -> Accuracy: 0.5345, MCC: 0.0143, F1: 0.6494

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.70488 | val 0.76999
  Epoch 020 - train 0.57513 | val 0.78352
  Epoch 025 - train 0.59323 | val 0.90495
  Classification -> best τ=0.360 (val F1=0.3844)
  Directional -> Accuracy: 0.5476, MCC: 0.0391, F1: 0.6780

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.64166 | val 1.09717
  Epoch 011 - train 0.64664 | val 1.14300
  Classification -> best τ=0.630 (val F1=0.2683)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.68917 | val 0.72674
  Epoch 014 - train 0.64379 | val 0.82957
  Classification -> best τ=0.680 (val F1=0.1239)
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.3429

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.67233 | val 0.86461
  Epoch 015 - train 0.56735 | val 0.86308
  Classification -> best τ=0.390 (val F1=0.2476)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.65239 | val 1.54195
  Epoch 011 - train 0.62199 | val 2.08860
  Classification -> best τ=0.550 (val F1=0.2355)
  Directional -> Accuracy: 0.4324, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.61918 | val 0.78186
  Epoch 011 - train 0.71667 | val 0.78901
  Classification -> best τ=0.470 (val F1=0.3395)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.5581

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.63480 | val 1.40749
  Epoch 012 - train 0.59614 | val 2.13396
  Classification -> best τ=0.640 (val F1=0.2130)
  Directional -> Accuracy: 0.6000, MCC: 0.1924, F1: 0.5500

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.59200 | val 0.66851
  Epoch 016 - train 0.59027 | val 0.80531
  Classification -> best τ=0.325 (val F1=0.3431)
  Directional -> Accuracy: 0.4776, MCC: 0.0478, F1: 0.3137

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.69898 | val 0.71349
  Epoch 015 - train 0.59513 | val 0.70428
  Classification -> best τ=0.475 (val F1=0.3337)
  Directional -> Accuracy: 0.5349, MCC: 0.1249, F1: 0.2857

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.64063 | val 1.02227
  Epoch 016 - train 0.62349 | val 0.82549
  Classification -> best τ=0.380 (val F1=0.2547)
  Directional -> Accuracy: 0.5088, MCC: 0.0453, F1: 0.5882

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.58379 | val 0.72911
  Epoch 011 - train 0.63978 | val 0.76560
  Classification -> best τ=0.455 (val F1=0.2287)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 16). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.57349 | val 1.66477
  Epoch 011 - train 0.60752 | val 1.93082
  Classification -> best τ=0.500 (val F1=0.3072)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.68764 | val 0.75098
  Epoch 013 - train 0.69475 | val 0.83717
  Classification -> best τ=0.560 (val F1=0.4886)
  Directional -> Accuracy: 0.5128, MCC: 0.2152, F1: 0.1739

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 16). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.66122 | val 1.25262
  Epoch 014 - train 0.64553 | val 1.29623
  Classification -> best τ=0.250 (val F1=0.3475)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.65964 | val 0.83890
  Epoch 011 - train 0.67388 | val 0.98978
  Classification -> best τ=0.590 (val F1=0.0315)
  Directional -> Accuracy: 0.4894, MCC: 0.0000, F1: 0.0000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.71278 | val 0.88483
  Epoch 011 - train 0.57587 | val 0.86301
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.68694 | val 0.86204
  Epoch 011 - train 0.64106 | val 0.84391
  Classification -> best τ=0.555 (val F1=0.3651)
  Directional -> Accuracy: 0.6500, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.67711 | val 1.00319
  Epoch 016 - train 0.64408 | val 1.48769
  Classification -> best τ=0.580 (val F1=0.2113)
  Directional -> Accuracy: 0.6316, MCC: 0.3191, F1: 0.5714

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.61661 | val 2.31182
  Epoch 012 - train 0.62525 | val 2.31208
  Classification -> best τ=0.445 (val F1=0.3147)
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.64153 | val 1.86493
  Epoch 012 - train 0.65962 | val 1.63668
  Classification -> best τ=0.440 (val F1=0.1997)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.66920 | val 1.98361
  Epoch 014 - train 0.59979 | val 2.50979
  Classification -> best τ=0.495 (val F1=0.0579)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.65781 | val 0.90321

[I 2026-02-25 01:08:45,934] Trial 118 finished with value: 0.2527464294745459 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 15, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 0.006690587809418336, 'weight_decay': 5.6348782570700194e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.5717871512205408, 'early_stopping_min_delta': 0.0009826235454562402}. Best is trial 32 with value: 0.2908549754956826.

  Epoch 016 - train 0.63225 | val 0.97130
  Classification -> best τ=0.520 (val F1=0.3271)
  Directional -> Accuracy: 0.5484, MCC: 0.1034, F1: 0.5758

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2527464294745459
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 15
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.66154 | val 1.31384
  Epoch 012 - train 0.70091 | val 1.00712
  Classification -> best τ=0.420 (val F1=0.1989)
  Directional -> Accuracy: 0.5195, MCC: -0.0423, F1: 0.1778

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.67628 | val 0.69939
  Epoch 013 - train 0.66357 | val 0.89947
  Classification -> best τ=0.535 (val F1=0.3778)
  Directional -> Accuracy: 0.6304, MCC: 0.2287, F1: 0.7119

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 16). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.69549 | val 0.81927
  Epoch 011 - train 0.67423 | val 0.83035
  Classification -> best τ=0.610 (val F1=0.1399)
  Directional -> Accuracy: 0.4583, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.68884 | val 1.38705
  Epoch 012 - train 0.67639 | val 1.01468
  Classification -> best τ=0.350 (val F1=0.1864)
  Directional -> Accuracy: 0.4133, MCC: -0.1582, F1: 0.1200

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.60691 | val 0.70668
  Epoch 019 - train 0.59810 | val 0.85255
  Classification -> best τ=0.525 (val F1=0.5124)
  Directional -> Accuracy: 0.7500, MCC: 0.4959, F1: 0.7797

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.61682 | val 0.75855
  Epoch 015 - train 0.61217 | val 0.73410
  Classification -> best τ=0.440 (val F1=0.2667)
  Directional -> Accuracy: 0.6042, MCC: 0.2344, F1: 0.6780

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.70332 | val 0.72552
  Epoch 012 - train 0.68619 | val 0.76801
  Classification -> best τ=0.465 (val F1=0.2332)
  Directional -> Accuracy: 0.4714, MCC: 0.1394, F1: 0.5843

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 16). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.70458 | val 1.08406
  Epoch 011 - train 0.63483 | val 1.06212
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.70380 | val 0.80664
  Epoch 013 - train 0.66220 | val 0.89764
  Classification -> best τ=0.575 (val F1=0.4282)
  Directional -> Accuracy: 0.3902, MCC: -0.0264, F1: 0.5098

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 16). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 16). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.69563 | val 0.87045
  Epoch 015 - train 0.66533 | val 0.82518
  Classification -> best τ=0.410 (val F1=0.3333)
  Directional -> Accuracy: 0.4085, MCC: -0.1409, F1: 0.5625

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.69721 | val 1.06454
  Epoch 016 - train 0.67507 | val 0.87033
  Classification -> best τ=0.460 (val F1=0.1763)
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.6400

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.63126 | val 0.72169
  Epoch 017 - train 0.60423 | val 0.86200
  Classification -> best τ=0.680 (val F1=0.2701)
  Directional -> Accuracy: 0.6780, MCC: 0.3874, F1: 0.6122

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.72130 | val 0.80605
  Epoch 019 - train 0.62513 | val 2.53035
  Classification -> best τ=0.435 (val F1=0.1953)
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.64319 | val 0.66223
  Epoch 017 - train 0.66743 | val 0.74097
  Classification -> best τ=0.445 (val F1=0.3192)
  Directional -> Accuracy: 0.5902, MCC: 0.2209, F1: 0.6914

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.66897 | val 1.68062
  Epoch 013 - train 0.66308 | val 1.67659
  Classification -> best τ=0.555 (val F1=0.1822)
  Directional -> Accuracy: 0.5094, MCC: 0.0289, F1: 0.5357

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.66825 | val 0.78911
  Epoch 011 - train 0.65213 | val 0.76321
  Classification -> best τ=0.500 (val F1=0.2516)
  Directional -> Accuracy: 0.5857, MCC: 0.1909, F1: 0.7184

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.70265 | val 0.82533
  Epoch 011 - train 0.68684 | val 0.79986
  Classification -> best τ=0.425 (val F1=0.0062)
  Directional -> Accuracy: 0.6333, MCC: 0.1344, F1: 0.7609

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.67713 | val 1.44705
  Epoch 013 - train 0.65746 | val 0.97922
  Classification -> best τ=0.540 (val F1=0.1799)
  Directional -> Accuracy: 0.5789, MCC: 0.2419, F1: 0.5556

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.66379 | val 0.90463
  Epoch 013 - train 0.68211 | val 0.80101
  Classification -> best τ=0.400 (val F1=0.2464)
  Directional -> Accuracy: 0.5303, MCC: 0.1830, F1: 0.4364

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 16). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.68685 | val 0.84419
  Epoch 015 - train 0.66945 | val 0.68071
  Classification -> best τ=0.520 (val F1=0.2869)
  Directional -> Accuracy: 0.4605, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.59564 | val 0.94439
  Epoch 012 - train 0.66735 | val 0.83843
  Classification -> best τ=0.535 (val F1=0.2692)
  Directional -> Accuracy: 0.6042, MCC: 0.0457, F1: 0.7324

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.66990 | val 1.13847
  Epoch 012 - train 0.65665 | val 1.50997
  Classification -> best τ=0.545 (val F1=0.1768)
  Directional -> Accuracy: 0.5455, MCC: 0.1085, F1: 0.3750

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.69265 | val 0.92164
  Epoch 011 - train 0.64002 | val 1.05289
  Classification -> best τ=0.645 (val F1=0.2773)
  Directional -> Accuracy: 0.5172, MCC: 0.0762, F1: 0.4815

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.67630 | val 1.97184
  Epoch 011 - train 0.64039 | val 1.92014
  Classification -> best τ=0.370 (val F1=0.2494)
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.67739 | val 0.70258
  Epoch 015 - train 0.66788 | val 0.70075
  Classification -> best τ=0.550 (val F1=0.3894)
  Directional -> Accuracy: 0.5536, MCC: 0.1867, F1: 0.4444

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.74218 | val 0.75328
  Epoch 011 - train 0.65158 | val 0.77482
  Classification -> best τ=0.555 (val F1=0.0620)
  Directional -> Accuracy: 0.5532, MCC: 0.1469, F1: 0.5714

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.65587 | val 0.69846
  Epoch 020 - train 0.64655 | val 0.68065
  Epoch 022 - train 0.61720 | val 0.69612
  Classification -> best τ=0.540 (val F1=0.3207)
  Directional -> Accuracy: 0.4651, MCC: 0.0208, F1: 0.3429

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.64026 | val 0.75869
  Epoch 016 - train 0.67456 | val 0.81845
  Classification -> best τ=0.455 (val F1=0.1960)
  Directional -> Accuracy: 0.5345, MCC: 0.1948, F1: 0.3415

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.65663 | val 0.84164
  Epoch 012 - train 0.61298 | val 0.93483
  Classification -> best τ=0.530 (val F1=0.2009)
  Directional -> Accuracy: 0.5000, MCC: 0.0235, F1: 0.4615

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.66084 | val 1.91575
  Epoch 011 - train 0.65173 | val 1.96715
  Classification -> best τ=0.525 (val F1=0.2107)
  Directional -> Accuracy: 0.4318, MCC: -0.1365, F1: 0.4444

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.76170 | val 0.68556
  Epoch 014 - train 0.71548 | val 0.66934
  Classification -> best τ=0.645 (val F1=0.0571)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.65758 | val 0.73772
  Epoch 013 - train 0.61919 | val 0.78327
  Classification -> best τ=0.655 (val F1=0.2320)
  Directional -> Accuracy: 0.4706, MCC: -0.1787, F1: 0.6301

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.66801 | val 0.68102
  Epoch 017 - train 0.67078 | val 1.20470
  Classification -> best τ=0.245 (val F1=0.2593)
  Directional -> Accuracy: 0.5676, MCC: 0.1652, F1: 0.5556

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.73791 | val 0.91892
  Epoch 011 - train 0.64280 | val 1.06838
  Classification -> best τ=0.430 (val F1=0.3223)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.5366

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.66978 | val 0.90416
  Epoch 011 - train 0.79414 | val 0.87211
  Classification -> best τ=0.535 (val F1=0.3185)
  Directional -> Accuracy: 0.5556, MCC: 0.2359, F1: 0.6667

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.66592 | val 0.68545
  Epoch 012 - train 0.65930 | val 0.67869
  Classification -> best τ=0.505 (val F1=0.4328)
  Directional -> Accuracy: 0.5821, MCC: 0.3295, F1: 0.4400

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.68240 | val 0.72759
  Epoch 020 - train 0.64147 | val 0.73071
  Epoch 028 - train 0.60403 | val 0.71008
  Classification -> best τ=0.480 (val F1=0.4015)
  Directional -> Accuracy: 0.6744, MCC: 0.3810, F1: 0.6111

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.67102 | val 0.81031
  Epoch 012 - train 0.66883 | val 0.92124
  Classification -> best τ=0.395 (val F1=0.3109)
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.60804 | val 0.82178
  Epoch 013 - train 0.68025 | val 0.77303
  Classification -> best τ=0.490 (val F1=0.2232)
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 16). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.62776 | val 0.82414
  Epoch 012 - train 0.64060 | val 0.79931
  Classification -> best τ=0.490 (val F1=0.3779)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.72332 | val 0.74641
  Epoch 013 - train 0.57504 | val 0.75919
  Classification -> best τ=0.485 (val F1=0.2707)
  Directional -> Accuracy: 0.5128, MCC: -0.0473, F1: 0.6545

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 16). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.68411 | val 0.70005
  Epoch 014 - train 0.65161 | val 0.69285
  Classification -> best τ=0.425 (val F1=0.2445)
  Directional -> Accuracy: 0.5395, MCC: 0.2027, F1: 0.6847

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.72951 | val 0.70007
  Epoch 011 - train 0.66849 | val 0.71148
  Classification -> best τ=0.495 (val F1=0.4151)
  Directional -> Accuracy: 0.5106, MCC: 0.0311, F1: 0.4103

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.69843 | val 1.01404
  Epoch 011 - train 0.65450 | val 1.15500
  Classification -> best τ=0.530 (val F1=0.1000)
  Directional -> Accuracy: 0.4222, MCC: -0.1107, F1: 0.1333

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.79325 | val 0.76384
  Epoch 014 - train 0.70110 | val 0.71499
  Classification -> best τ=0.590 (val F1=0.3651)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.70475 | val 1.32038
  Epoch 012 - train 0.68233 | val 2.17727
  Classification -> best τ=0.515 (val F1=0.2849)
  Directional -> Accuracy: 0.4561, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.66045 | val 1.89625
  Epoch 011 - train 0.65713 | val 1.95062
  Classification -> best τ=0.605 (val F1=0.3108)
  Directional -> Accuracy: 0.5263, MCC: 0.2236, F1: 0.6667

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.72138 | val 1.26796
  Epoch 011 - train 0.68850 | val 1.37251
  Classification -> best τ=0.405 (val F1=0.0465)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.66718 | val 1.33597
  Epoch 013 - train 0.71478 | val 1.56652
  Classification -> best τ=0.630 (val F1=0.1576)
  Directional -> Accuracy: 0.5614, MCC: 0.2399, F1: 0.6988

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.66660 | val 0.73604
  Epoch 020 - train 0.61593 | val 0.84907

[I 2026-02-25 01:10:52,684] Trial 119 finished with value: 0.2520182099886361 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 15, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 32, 'learning_rate': 0.0050356954020654, 'weight_decay': 5.034146795645271e-06, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.6798806607724066, 'early_stopping_min_delta': 0.0013746067717345337}. Best is trial 32 with value: 0.2908549754956826.

  Epoch 025 - train 0.60837 | val 1.16127
  Classification -> best τ=0.435 (val F1=0.3271)
  Directional -> Accuracy: 0.4677, MCC: -0.0591, F1: 0.6024

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2520182099886361
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: classification
Sequence length: 15
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.66589 | val 0.67767
  Epoch 019 - train 0.65067 | val 0.70875
  Classification -> best τ=0.530 (val F1=0.2453)
  Directional -> Accuracy: 0.4935, MCC: 0.0098, F1: 0.5301

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.62564 | val 0.70343
  Epoch 016 - train 0.62285 | val 0.81028
  Classification -> best τ=0.450 (val F1=0.1168)
  Directional -> Accuracy: 0.5870, MCC: 0.1164, F1: 0.7164

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 16). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.67083 | val 0.74035
  Epoch 016 - train 0.63753 | val 0.76781
  Classification -> best τ=0.545 (val F1=0.3030)
  Directional -> Accuracy: 0.4583, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.64824 | val 0.88726
  Epoch 011 - train 0.66272 | val 0.89175
  Classification -> best τ=0.460 (val F1=0.2137)
  Directional -> Accuracy: 0.5600, MCC: 0.1244, F1: 0.5714

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.63279 | val 0.76097
  Epoch 016 - train 0.59960 | val 0.90065
  Classification -> best τ=0.410 (val F1=0.5004)
  Directional -> Accuracy: 0.6923, MCC: 0.3947, F1: 0.7576

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.61971 | val 0.72232
  Epoch 015 - train 0.59122 | val 0.88563
  Classification -> best τ=0.495 (val F1=0.2806)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.66787 | val 0.71890
  Epoch 013 - train 0.66012 | val 0.72747
  Classification -> best τ=0.490 (val F1=0.2462)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.5714

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 16). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.61832 | val 0.70700
  Epoch 011 - train 0.62461 | val 0.72878
  Classification -> best τ=0.465 (val F1=0.0410)
  Directional -> Accuracy: 0.5111, MCC: -0.0165, F1: 0.3889

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.64588 | val 0.67678
  Epoch 017 - train 0.61870 | val 0.77289
  Classification -> best τ=0.545 (val F1=0.3877)
  Directional -> Accuracy: 0.5610, MCC: 0.2266, F1: 0.5714

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 16). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 16). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.63069 | val 0.89511
  Epoch 011 - train 0.63491 | val 0.90165
  Classification -> best τ=0.530 (val F1=0.1491)
  Directional -> Accuracy: 0.4648, MCC: -0.0010, F1: 0.5581

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.64199 | val 0.88184
  Epoch 011 - train 0.64082 | val 0.93780
  Classification -> best τ=0.475 (val F1=0.2278)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.66218 | val 0.73199
  Epoch 011 - train 0.65166 | val 0.73556
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5085, MCC: 0.0000, F1: 0.6742

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.63202 | val 1.04573
  Epoch 011 - train 0.61222 | val 1.13588
  Classification -> best τ=0.500 (val F1=0.1839)
  Directional -> Accuracy: 0.4651, MCC: 0.0118, F1: 0.5818

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.66121 | val 0.63502
  Epoch 020 - train 0.62783 | val 0.63931
  Epoch 024 - train 0.61674 | val 0.63548
  Classification -> best τ=0.385 (val F1=0.2906)
  Directional -> Accuracy: 0.6066, MCC: 0.2730, F1: 0.7073

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.65003 | val 0.91079
  Epoch 011 - train 0.63732 | val 0.95529
  Classification -> best τ=0.550 (val F1=0.2608)
  Directional -> Accuracy: 0.5660, MCC: 0.1593, F1: 0.2069

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.61846 | val 0.82658
  Epoch 014 - train 0.62528 | val 0.83124
  Classification -> best τ=0.405 (val F1=0.2516)
  Directional -> Accuracy: 0.5714, MCC: 0.1869, F1: 0.7170

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.65446 | val 1.00662
  Epoch 011 - train 0.65400 | val 1.07609
  Classification -> best τ=0.550 (val F1=0.2112)
  Directional -> Accuracy: 0.4500, MCC: 0.0297, F1: 0.3529

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.65229 | val 1.22446
  Epoch 011 - train 0.64190 | val 1.33904
  Classification -> best τ=0.510 (val F1=0.1109)
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.65521 | val 0.73169
  Epoch 016 - train 0.63634 | val 0.85596
  Classification -> best τ=0.375 (val F1=0.2778)
  Directional -> Accuracy: 0.5000, MCC: 0.1525, F1: 0.3529

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 16). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.64607 | val 0.72498
  Epoch 015 - train 0.62338 | val 0.76794
  Classification -> best τ=0.500 (val F1=0.2869)
  Directional -> Accuracy: 0.4605, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.63947 | val 0.94734
  Epoch 011 - train 0.64542 | val 1.06293
  Classification -> best τ=0.480 (val F1=0.2103)
  Directional -> Accuracy: 0.5000, MCC: 0.0436, F1: 0.5200

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.65779 | val 0.90619
  Epoch 011 - train 0.63774 | val 0.94210
  Classification -> best τ=0.515 (val F1=0.0913)
  Directional -> Accuracy: 0.5909, MCC: 0.1819, F1: 0.5846

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.65135 | val 0.69727
  Epoch 015 - train 0.61962 | val 0.73438
  Classification -> best τ=0.580 (val F1=0.2299)
  Directional -> Accuracy: 0.4828, MCC: 0.0658, F1: 0.3182

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.64291 | val 1.63917
  Epoch 012 - train 0.63312 | val 1.66047
  Classification -> best τ=0.480 (val F1=0.2453)
  Directional -> Accuracy: 0.5606, MCC: 0.1782, F1: 0.6420

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.66613 | val 0.66646
  Epoch 020 - train 0.61924 | val 0.69206
  Epoch 025 - train 0.62691 | val 0.68325
  Classification -> best τ=0.530 (val F1=0.4715)
  Directional -> Accuracy: 0.5536, MCC: 0.2064, F1: 0.4186

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.65525 | val 0.70001
  Epoch 011 - train 0.67245 | val 0.70231
  Classification -> best τ=0.490 (val F1=0.0961)
  Directional -> Accuracy: 0.4255, MCC: -0.1828, F1: 0.3077

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.64198 | val 0.90565
  Epoch 011 - train 0.62175 | val 0.98166
  Classification -> best τ=0.485 (val F1=0.1599)
  Directional -> Accuracy: 0.6047, MCC: 0.1334, F1: 0.7302

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.65781 | val 0.74852
  Epoch 011 - train 0.61260 | val 0.75821
  Classification -> best τ=0.480 (val F1=0.0951)
  Directional -> Accuracy: 0.4138, MCC: -0.1699, F1: 0.4333

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.68407 | val 0.69797
  Epoch 011 - train 0.64858 | val 0.69867
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.7077

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.64141 | val 0.81582
  Epoch 011 - train 0.63717 | val 0.86522
  Classification -> best τ=0.535 (val F1=0.3092)
  Directional -> Accuracy: 0.5227, MCC: 0.0563, F1: 0.3226

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.66026 | val 0.71409
  Epoch 011 - train 0.67061 | val 0.71978
  Classification -> best τ=0.500 (val F1=0.2703)
  Directional -> Accuracy: 0.5227, MCC: 0.0256, F1: 0.5882

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.65170 | val 0.69415
  Epoch 016 - train 0.63544 | val 0.72179
  Classification -> best τ=0.455 (val F1=0.2461)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.63021 | val 0.62762
  Epoch 020 - train 0.61760 | val 0.75487
  Classification -> best τ=0.695 (val F1=0.3403)
  Directional -> Accuracy: 0.4324, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.60560 | val 0.69305
  Epoch 016 - train 0.63717 | val 0.72559
  Classification -> best τ=0.470 (val F1=0.2145)
  Directional -> Accuracy: 0.5526, MCC: 0.1443, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.65433 | val 0.73878
  Epoch 011 - train 0.64454 | val 0.74516
  Classification -> best τ=0.540 (val F1=0.1494)
  Directional -> Accuracy: 0.5333, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.64275 | val 0.74270
  Epoch 014 - train 0.63209 | val 0.74862
  Classification -> best τ=0.385 (val F1=0.3266)
  Directional -> Accuracy: 0.5672, MCC: 0.1149, F1: 0.6234

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.64876 | val 0.69480
  Epoch 017 - train 0.60877 | val 0.72260
  Classification -> best τ=0.530 (val F1=0.2683)
  Directional -> Accuracy: 0.5581, MCC: 0.2093, F1: 0.2963

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.63834 | val 0.78845
  Epoch 013 - train 0.63098 | val 0.79572
  Classification -> best τ=0.465 (val F1=0.2718)
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.62127 | val 0.76734
  Epoch 011 - train 0.63257 | val 0.77157
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 16). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.61937 | val 0.74351
  Epoch 011 - train 0.64386 | val 0.76347
  Classification -> best τ=0.525 (val F1=0.3333)
  Directional -> Accuracy: 0.3500, MCC: -0.0721, F1: 0.5000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.65163 | val 0.72286
  Epoch 011 - train 0.64049 | val 0.73322
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.7000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 16). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.63828 | val 0.73597
  Epoch 015 - train 0.62692 | val 0.81346
  Classification -> best τ=0.455 (val F1=0.2584)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.64743 | val 0.70716
  Epoch 011 - train 0.66360 | val 0.71079
  Classification -> best τ=0.470 (val F1=0.0245)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.65305 | val 0.69855
  Epoch 011 - train 0.64277 | val 0.70672
  Classification -> best τ=0.475 (val F1=0.2500)
  Directional -> Accuracy: 0.4222, MCC: -0.1685, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.66187 | val 0.74613
  Epoch 011 - train 0.62188 | val 0.76437
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.65072 | val 0.86030
  Epoch 011 - train 0.64741 | val 0.88112
  Classification -> best τ=0.520 (val F1=0.0091)
  Directional -> Accuracy: 0.4211, MCC: -0.1621, F1: 0.0571

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.62622 | val 1.01411
  Epoch 012 - train 0.63515 | val 1.16965
  Classification -> best τ=0.495 (val F1=0.2794)
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.66189 | val 0.92550
  Epoch 011 - train 0.63565 | val 1.02897
  Classification -> best τ=0.495 (val F1=0.0955)
  Directional -> Accuracy: 0.5370, MCC: 0.2337, F1: 0.1935

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.65337 | val 1.10538
  Epoch 011 - train 0.63461 | val 1.12978
  Classification -> best τ=0.545 (val F1=0.2374)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...

[I 2026-02-25 01:11:54,531] Trial 120 finished with value: 0.20438562760078277 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 15, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 0.0001958897368198249, 'weight_decay': 2.5579152550146645e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.9552454904032923, 'early_stopping_min_delta': 0.0002868068985263808}. Best is trial 32 with value: 0.2908549754956826.

  Epoch 010 - train 0.66668 | val 1.04642
  Epoch 011 - train 0.64733 | val 1.05769
  Classification -> best τ=0.475 (val F1=0.1507)
  Directional -> Accuracy: 0.5806, MCC: 0.2050, F1: 0.3158

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.20438562760078277
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 15
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.71640 | val 0.75258
  Epoch 020 - train 0.70240 | val 0.65641
  Epoch 028 - train 0.69330 | val 0.66132
  Classification -> best τ=0.440 (val F1=0.2662)
  Directional -> Accuracy: 0.5455, MCC: 0.0614, F1: 0.4068

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.63314 | val 0.79301
  Epoch 012 - train 0.67403 | val 0.70116
  Classification -> best τ=0.490 (val F1=0.0245)
  Directional -> Accuracy: 0.4565, MCC: -0.2495, F1: 0.6154

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 16). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.72555 | val 0.70909
  Epoch 013 - train 0.65229 | val 1.10703
  Classification -> best τ=0.510 (val F1=0.3295)
  Directional -> Accuracy: 0.6458, MCC: 0.2895, F1: 0.6667

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.70165 | val 1.36824
  Epoch 013 - train 0.67723 | val 0.85796
  Classification -> best τ=0.490 (val F1=0.2059)
  Directional -> Accuracy: 0.4933, MCC: -0.0072, F1: 0.5000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.63934 | val 1.46521
  Epoch 013 - train 0.65871 | val 1.19303
  Classification -> best τ=0.435 (val F1=0.3765)
  Directional -> Accuracy: 0.7500, MCC: 0.5261, F1: 0.7347

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.73200 | val 2.22376
  Epoch 011 - train 0.57314 | val 4.82038
  Classification -> best τ=0.440 (val F1=0.2777)
  Directional -> Accuracy: 0.5625, MCC: 0.1260, F1: 0.5333

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.71923 | val 0.83066
  Epoch 014 - train 0.69563 | val 1.52479
  Classification -> best τ=0.570 (val F1=0.2134)
  Directional -> Accuracy: 0.6000, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 16). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.68610 | val 2.68546
  Epoch 013 - train 0.58744 | val 3.05900
  Classification -> best τ=0.760 (val F1=0.3571)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.74478 | val 0.90074
  Epoch 020 - train 0.63631 | val 1.31135
  Epoch 021 - train 0.63387 | val 1.21802
  Classification -> best τ=0.520 (val F1=0.3786)
  Directional -> Accuracy: 0.6341, MCC: 0.2718, F1: 0.5714

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 16). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 16). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.66508 | val 1.87232
  Epoch 013 - train 0.61840 | val 2.26110
  Classification -> best τ=0.330 (val F1=0.1827)
  Directional -> Accuracy: 0.4366, MCC: 0.0000, F1: 0.6078

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.69553 | val 0.83258
  Epoch 012 - train 0.65473 | val 0.88462
  Classification -> best τ=0.450 (val F1=0.0739)
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.6400

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.65946 | val 0.71446
  Epoch 020 - train 0.63350 | val 0.82800
  Epoch 024 - train 0.66002 | val 0.83359
  Classification -> best τ=0.290 (val F1=0.2110)
  Directional -> Accuracy: 0.5085, MCC: 0.0000, F1: 0.6742

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.68890 | val 4.08165
  Epoch 012 - train 0.67160 | val 3.78092
  Classification -> best τ=0.585 (val F1=0.2719)
  Directional -> Accuracy: 0.3256, MCC: -0.3943, F1: 0.1714

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.74459 | val 0.67621
  Epoch 016 - train 0.68543 | val 1.20032
  Classification -> best τ=0.275 (val F1=0.2928)
  Directional -> Accuracy: 0.5410, MCC: 0.1035, F1: 0.6667

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.69267 | val 2.75086
  Epoch 011 - train 0.73748 | val 2.46038
  Classification -> best τ=0.765 (val F1=0.2589)
  Directional -> Accuracy: 0.6038, MCC: 0.2113, F1: 0.4324

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.68721 | val 1.12403
  Epoch 011 - train 0.66703 | val 1.04676
  Classification -> best τ=0.480 (val F1=0.3641)
  Directional -> Accuracy: 0.5571, MCC: 0.1312, F1: 0.7103

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.66553 | val 1.76811
  Epoch 013 - train 0.67944 | val 1.26584
  Classification -> best τ=0.385 (val F1=0.1541)
  Directional -> Accuracy: 0.6000, MCC: 0.1265, F1: 0.6923

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.67443 | val 0.87194
  Epoch 012 - train 0.68525 | val 1.21138
  Classification -> best τ=0.690 (val F1=0.2405)
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.74109 | val 0.71195
  Epoch 020 - train 0.64701 | val 0.81939
  Epoch 021 - train 0.65679 | val 0.94301
  Classification -> best τ=0.510 (val F1=0.2605)
  Directional -> Accuracy: 0.4091, MCC: -0.0327, F1: 0.0488

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 16). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.66574 | val 1.36524
  Epoch 011 - train 0.66024 | val 0.91441
  Classification -> best τ=0.330 (val F1=0.1737)
  Directional -> Accuracy: 0.4868, MCC: 0.0589, F1: 0.2041

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.73570 | val 0.76749
  Epoch 014 - train 0.65040 | val 3.23962
  Classification -> best τ=0.485 (val F1=0.1399)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.72847 | val 1.73413
  Epoch 011 - train 0.69630 | val 1.57486
  Classification -> best τ=0.395 (val F1=0.1677)
  Directional -> Accuracy: 0.5152, MCC: 0.0727, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.67171 | val 1.14197
  Epoch 011 - train 0.70955 | val 1.14766
  Classification -> best τ=0.450 (val F1=0.2246)
  Directional -> Accuracy: 0.6034, MCC: 0.1753, F1: 0.7356

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.72561 | val 2.43657
  Epoch 011 - train 0.68450 | val 1.68291
  Classification -> best τ=0.330 (val F1=0.2766)
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.70918 | val 0.79288
  Epoch 015 - train 0.65070 | val 0.81757
  Classification -> best τ=0.595 (val F1=0.4505)
  Directional -> Accuracy: 0.5179, MCC: 0.1373, F1: 0.3415

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.68835 | val 1.06639
  Epoch 012 - train 0.59467 | val 1.08209
  Classification -> best τ=0.440 (val F1=0.3581)
  Directional -> Accuracy: 0.5745, MCC: 0.0318, F1: 0.0909

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.77267 | val 0.72097
  Epoch 011 - train 0.73047 | val 0.74951
  Classification -> best τ=0.645 (val F1=0.2057)
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.72969 | val 0.71969
  Epoch 015 - train 0.74025 | val 0.80182
  Classification -> best τ=0.420 (val F1=0.2652)
  Directional -> Accuracy: 0.5000, MCC: 0.1533, F1: 0.2162

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.81236 | val 0.69672
  Epoch 015 - train 0.64926 | val 0.73775
  Classification -> best τ=0.395 (val F1=0.5204)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.7077

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.77034 | val 1.74578
  Epoch 012 - train 0.69372 | val 2.03026
  Classification -> best τ=0.495 (val F1=0.1869)
  Directional -> Accuracy: 0.5227, MCC: 0.0525, F1: 0.6182

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.66771 | val 1.46860
  Epoch 011 - train 0.65194 | val 1.56649
  Classification -> best τ=0.380 (val F1=0.2374)
  Directional -> Accuracy: 0.5227, MCC: -0.0227, F1: 0.6557

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.67909 | val 1.01135
  Epoch 012 - train 0.59617 | val 1.04337
  Classification -> best τ=0.655 (val F1=0.2320)
  Directional -> Accuracy: 0.4902, MCC: -0.0518, F1: 0.5938

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.68186 | val 1.27304
  Epoch 013 - train 0.66918 | val 1.69911
  Classification -> best τ=0.275 (val F1=0.2652)
  Directional -> Accuracy: 0.5811, MCC: 0.2198, F1: 0.5373

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.61456 | val 1.15470
  Epoch 014 - train 0.59649 | val 2.50645
  Classification -> best τ=0.350 (val F1=0.4792)
  Directional -> Accuracy: 0.5789, MCC: 0.1857, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.70962 | val 0.96510
  Epoch 011 - train 0.71711 | val 0.88284
  Classification -> best τ=0.395 (val F1=0.2017)
  Directional -> Accuracy: 0.5333, MCC: 0.1048, F1: 0.6038

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.64946 | val 1.07603
  Epoch 012 - train 0.68778 | val 1.02096
  Classification -> best τ=0.255 (val F1=0.3431)
  Directional -> Accuracy: 0.6269, MCC: 0.2316, F1: 0.6835

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.70254 | val 0.98248
  Epoch 018 - train 0.57899 | val 2.80855
  Classification -> best τ=0.160 (val F1=0.2810)
  Directional -> Accuracy: 0.5581, MCC: 0.1142, F1: 0.6122

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.71894 | val 0.68095
  Epoch 020 - train 0.62385 | val 0.67891
  Epoch 022 - train 0.58131 | val 0.67945
  Classification -> best τ=0.390 (val F1=0.2453)
  Directional -> Accuracy: 0.5965, MCC: 0.2147, F1: 0.6349

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.61090 | val 1.46240
  Epoch 011 - train 0.69005 | val 1.30074
  Classification -> best τ=0.650 (val F1=0.2525)
  Directional -> Accuracy: 0.3830, MCC: -0.0508, F1: 0.0645

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 16). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.70565 | val 0.85903
  Epoch 012 - train 0.68088 | val 0.91331
  Classification -> best τ=0.445 (val F1=0.2981)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.71984 | val 1.17230
  Epoch 014 - train 0.76842 | val 1.78090
  Classification -> best τ=0.325 (val F1=0.4644)
  Directional -> Accuracy: 0.5897, MCC: 0.1631, F1: 0.6800

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 16). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.70057 | val 0.80362
  Epoch 012 - train 0.67183 | val 0.96087
  Classification -> best τ=0.445 (val F1=0.3011)
  Directional -> Accuracy: 0.5395, MCC: 0.2027, F1: 0.6847

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.65670 | val 0.87775
  Epoch 011 - train 0.66346 | val 1.00940
  Classification -> best τ=0.550 (val F1=0.2588)
  Directional -> Accuracy: 0.5106, MCC: 0.0200, F1: 0.5306

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.58459 | val 1.51275
  Epoch 011 - train 0.57692 | val 1.98536
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.64672 | val 0.80132
  Epoch 016 - train 0.61956 | val 0.87934
  Classification -> best τ=0.505 (val F1=0.2890)
  Directional -> Accuracy: 0.4000, MCC: 0.1683, F1: 0.5385

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.71090 | val 1.19864
  Epoch 013 - train 0.68695 | val 0.97778
  Classification -> best τ=0.675 (val F1=0.2728)
  Directional -> Accuracy: 0.5263, MCC: 0.1446, F1: 0.3415

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.66609 | val 1.06180
  Epoch 011 - train 0.64965 | val 1.64513
  Classification -> best τ=0.635 (val F1=0.3873)
  Directional -> Accuracy: 0.5789, MCC: 0.1910, F1: 0.6364

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.67782 | val 1.42311
  Epoch 011 - train 0.65463 | val 1.87944
  Classification -> best τ=0.555 (val F1=0.2368)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.68333 | val 2.91379
  Epoch 013 - train 0.66442 | val 1.72999
  Classification -> best τ=0.585 (val F1=0.1400)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.69934 | val 0.70166

[I 2026-02-25 01:14:38,907] Trial 121 finished with value: 0.26489986385880726 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 15, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 16, 'learning_rate': 0.008158932203182055, 'weight_decay': 1.85939016547141e-05, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.8717644365999546, 'early_stopping_min_delta': 0.0006612461421603715}. Best is trial 32 with value: 0.2908549754956826.

  Epoch 011 - train 0.70837 | val 0.71436
  Classification -> best τ=0.425 (val F1=0.3502)
  Directional -> Accuracy: 0.5161, MCC: 0.0406, F1: 0.5588

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.26489986385880726
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 15
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.68075 | val 0.87706
  Epoch 012 - train 0.66427 | val 3.05341
  Classification -> best τ=0.520 (val F1=0.0765)
  Directional -> Accuracy: 0.4026, MCC: -0.1904, F1: 0.5490

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.69125 | val 0.78682
  Epoch 017 - train 0.54583 | val 0.72271
  Classification -> best τ=0.475 (val F1=0.1236)
  Directional -> Accuracy: 0.6087, MCC: 0.1761, F1: 0.7188

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 16). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.69766 | val 0.85740
  Epoch 014 - train 0.62293 | val 1.05171
  Classification -> best τ=0.545 (val F1=0.2600)
  Directional -> Accuracy: 0.5833, MCC: 0.1459, F1: 0.6875

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.72634 | val 1.42675
  Epoch 011 - train 0.69848 | val 1.35518
  Classification -> best τ=0.535 (val F1=0.1095)
  Directional -> Accuracy: 0.4667, MCC: -0.0760, F1: 0.5122

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.62390 | val 1.26290
  Epoch 011 - train 0.61013 | val 1.03903
  Classification -> best τ=0.490 (val F1=0.4325)
  Directional -> Accuracy: 0.6731, MCC: 0.3406, F1: 0.7018

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.63728 | val 2.46603
  Epoch 012 - train 0.66849 | val 4.48180
  Classification -> best τ=0.510 (val F1=0.3148)
  Directional -> Accuracy: 0.5417, MCC: 0.0861, F1: 0.4762

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.73329 | val 1.15794
  Epoch 016 - train 0.65834 | val 1.37051
  Classification -> best τ=0.535 (val F1=0.2722)
  Directional -> Accuracy: 0.6000, MCC: 0.0625, F1: 0.1765

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 16). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.65543 | val 5.52486
  Epoch 011 - train 0.60305 | val 6.74365
  Classification -> best τ=0.615 (val F1=0.2229)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.71029 | val 0.75293
  Epoch 015 - train 0.65847 | val 0.71056
  Classification -> best τ=0.565 (val F1=0.4301)
  Directional -> Accuracy: 0.5854, MCC: -0.1720, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 16). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 16). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.63596 | val 1.85877
  Epoch 011 - train 0.59764 | val 1.04162
  Classification -> best τ=0.285 (val F1=0.0350)
  Directional -> Accuracy: 0.4366, MCC: 0.0000, F1: 0.6078

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.79914 | val 1.34725
  Epoch 017 - train 0.66775 | val 4.87077
  Classification -> best τ=0.585 (val F1=0.3037)
  Directional -> Accuracy: 0.6078, MCC: 0.2079, F1: 0.5238

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.65768 | val 0.86001
  Epoch 011 - train 0.65167 | val 0.90025
  Classification -> best τ=0.495 (val F1=0.1450)
  Directional -> Accuracy: 0.3898, MCC: -0.2207, F1: 0.4000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.71703 | val 1.15781
  Epoch 017 - train 0.62748 | val 0.99348
  Classification -> best τ=0.625 (val F1=0.2719)
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.71683 | val 0.83787
  Epoch 015 - train 0.73540 | val 1.16888
  Classification -> best τ=0.285 (val F1=0.3501)
  Directional -> Accuracy: 0.5410, MCC: 0.1035, F1: 0.6667

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.71195 | val 3.07975
  Epoch 011 - train 0.64277 | val 4.01363
  Classification -> best τ=0.830 (val F1=0.2798)
  Directional -> Accuracy: 0.5283, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.63863 | val 1.55390
  Epoch 013 - train 0.59735 | val 1.31813
  Classification -> best τ=0.835 (val F1=0.2734)
  Directional -> Accuracy: 0.4857, MCC: 0.0091, F1: 0.3793

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.66529 | val 1.30604
  Epoch 012 - train 0.67938 | val 1.19348
  Classification -> best τ=0.580 (val F1=0.2659)
  Directional -> Accuracy: 0.5167, MCC: 0.0840, F1: 0.5246

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.65784 | val 3.23174
  Epoch 011 - train 0.76291 | val 3.51391
  Classification -> best τ=0.430 (val F1=0.1565)
  Directional -> Accuracy: 0.5789, MCC: 0.1396, F1: 0.6364

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.78382 | val 0.81165
  Epoch 016 - train 0.64357 | val 1.45320
  Classification -> best τ=0.495 (val F1=0.2566)
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 16). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.68736 | val 0.76838
  Epoch 011 - train 0.61925 | val 0.86205
  Classification -> best τ=0.385 (val F1=0.1286)
  Directional -> Accuracy: 0.5395, MCC: 0.1037, F1: 0.4928

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.62980 | val 3.73093
  Epoch 013 - train 0.58758 | val 3.93954
  Classification -> best τ=0.245 (val F1=0.3143)
  Directional -> Accuracy: 0.5000, MCC: 0.1854, F1: 0.4000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.65071 | val 2.38124
  Epoch 011 - train 0.76117 | val 2.07213
  Classification -> best τ=0.465 (val F1=0.1177)
  Directional -> Accuracy: 0.5606, MCC: 0.1414, F1: 0.6506

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.67784 | val 0.76654
  Epoch 012 - train 0.65748 | val 1.16570
  Classification -> best τ=0.505 (val F1=0.3341)
  Directional -> Accuracy: 0.6034, MCC: 0.2245, F1: 0.6102

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.69479 | val 1.39009
  Epoch 011 - train 0.68986 | val 2.12826
  Classification -> best τ=0.325 (val F1=0.2453)
  Directional -> Accuracy: 0.5303, MCC: 0.1073, F1: 0.6173

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.72089 | val 0.66220
  Epoch 015 - train 0.69206 | val 1.25938
  Classification -> best τ=0.580 (val F1=0.4794)
  Directional -> Accuracy: 0.5714, MCC: 0.2385, F1: 0.4545

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.60617 | val 1.17578
  Epoch 011 - train 0.62706 | val 1.24105
  Classification -> best τ=0.490 (val F1=0.3721)
  Directional -> Accuracy: 0.4681, MCC: 0.1814, F1: 0.6154

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.68672 | val 0.69208
  Epoch 020 - train 0.67972 | val 0.68521
  Epoch 025 - train 0.69773 | val 0.68160
  Classification -> best τ=0.545 (val F1=0.3078)
  Directional -> Accuracy: 0.5349, MCC: 0.1265, F1: 0.5000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.67957 | val 0.76323
  Epoch 013 - train 0.68283 | val 0.98897
  Classification -> best τ=0.180 (val F1=0.2769)
  Directional -> Accuracy: 0.5862, MCC: 0.2892, F1: 0.4545

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.82973 | val 0.70199
  Epoch 020 - train 0.66682 | val 0.72399
  Epoch 025 - train 0.64244 | val 0.72256
  Classification -> best τ=0.555 (val F1=0.4193)
  Directional -> Accuracy: 0.5476, MCC: 0.1220, F1: 0.5128

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.72910 | val 1.26400
  Epoch 011 - train 0.70637 | val 1.43938
  Classification -> best τ=0.545 (val F1=0.1869)
  Directional -> Accuracy: 0.5227, MCC: 0.0467, F1: 0.5714

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.70924 | val 1.41133
  Epoch 011 - train 0.74140 | val 1.17739
  Classification -> best τ=0.460 (val F1=0.2089)
  Directional -> Accuracy: 0.4545, MCC: -0.2297, F1: 0.6129

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.64348 | val 1.02076
  Epoch 012 - train 0.61318 | val 1.07638
  Classification -> best τ=0.665 (val F1=0.2320)
  Directional -> Accuracy: 0.4118, MCC: -0.2652, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.68253 | val 2.07199
  Epoch 011 - train 0.69367 | val 2.60901
  Classification -> best τ=0.390 (val F1=0.3567)
  Directional -> Accuracy: 0.4730, MCC: 0.0049, F1: 0.3810

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.63872 | val 1.23017
  Epoch 014 - train 0.66243 | val 1.19586
  Classification -> best τ=0.495 (val F1=0.2227)
  Directional -> Accuracy: 0.5789, MCC: 0.1615, F1: 0.6190

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.66329 | val 1.39592
  Epoch 011 - train 0.73019 | val 1.47379
  Classification -> best τ=0.440 (val F1=0.2500)
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.6364

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.70208 | val 0.79769
  Epoch 020 - train 0.60355 | val 1.03703
  Epoch 022 - train 0.59962 | val 1.10580
  Classification -> best τ=0.400 (val F1=0.3479)
  Directional -> Accuracy: 0.5522, MCC: 0.2067, F1: 0.4444

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.72293 | val 0.67866
  Epoch 020 - train 0.68429 | val 0.73119
  Epoch 028 - train 0.59614 | val 1.17316
  Classification -> best τ=0.515 (val F1=0.3914)
  Directional -> Accuracy: 0.6744, MCC: 0.3810, F1: 0.6111

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.67296 | val 0.76281
  Epoch 012 - train 0.61474 | val 0.75003
  Classification -> best τ=0.445 (val F1=0.1998)
  Directional -> Accuracy: 0.5088, MCC: 0.0590, F1: 0.6111

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.72471 | val 1.52165
  Epoch 012 - train 0.65032 | val 1.57893
  Classification -> best τ=0.590 (val F1=0.3314)
  Directional -> Accuracy: 0.4468, MCC: 0.0837, F1: 0.2778

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 16). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.70285 | val 0.84239
  Epoch 015 - train 0.62850 | val 0.66674
  Classification -> best τ=0.275 (val F1=0.4247)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.69445 | val 0.94117
  Epoch 015 - train 0.62593 | val 1.29372
  Classification -> best τ=0.425 (val F1=0.1870)
  Directional -> Accuracy: 0.6154, MCC: 0.2234, F1: 0.6512

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 16). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.70269 | val 0.95057
  Epoch 012 - train 0.67566 | val 0.92004
  Classification -> best τ=0.480 (val F1=0.2626)
  Directional -> Accuracy: 0.5132, MCC: 0.0531, F1: 0.6606

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.67053 | val 1.16253
  Epoch 011 - train 0.65466 | val 1.37859
  Classification -> best τ=0.525 (val F1=0.3157)
  Directional -> Accuracy: 0.5957, MCC: 0.2191, F1: 0.6885

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.82250 | val 1.73697
  Epoch 011 - train 0.66556 | val 1.87816
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.66572 | val 0.68904
  Epoch 012 - train 0.63949 | val 0.72773
  Classification -> best τ=0.555 (val F1=0.2404)
  Directional -> Accuracy: 0.4500, MCC: 0.0605, F1: 0.5000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.70813 | val 1.32912
  Epoch 011 - train 0.66966 | val 2.15752
  Classification -> best τ=0.625 (val F1=0.2445)
  Directional -> Accuracy: 0.5088, MCC: 0.2159, F1: 0.1765

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.68664 | val 1.19824
  Epoch 011 - train 0.68070 | val 1.94026
  Classification -> best τ=0.475 (val F1=0.2579)
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.70795 | val 0.68685
  Epoch 011 - train 0.71544 | val 0.70103
  Classification -> best τ=0.550 (val F1=0.2203)
  Directional -> Accuracy: 0.5000, MCC: -0.0521, F1: 0.6494

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.70778 | val 1.35882
  Epoch 011 - train 0.69407 | val 1.32907
  Classification -> best τ=0.500 (val F1=0.1506)
  Directional -> Accuracy: 0.4912, MCC: -0.0048, F1: 0.1212

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.71821 | val 0.66961

[I 2026-02-25 01:17:14,505] Trial 122 finished with value: 0.2568228028686846 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 15, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 16, 'learning_rate': 0.0070837794813691695, 'weight_decay': 3.6684242899587444e-05, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.8295854916125285, 'early_stopping_min_delta': 0.0004450599096807147}. Best is trial 32 with value: 0.2908549754956826.

  Epoch 017 - train 0.69760 | val 0.70614
  Classification -> best τ=0.425 (val F1=0.2342)
  Directional -> Accuracy: 0.5000, MCC: 0.0135, F1: 0.5753

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2568228028686846
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 15
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.71706 | val 0.67837
  Epoch 020 - train 0.68681 | val 0.70208
  Epoch 025 - train 0.68974 | val 0.68478
  Classification -> best τ=0.510 (val F1=0.2453)
  Directional -> Accuracy: 0.5195, MCC: -0.0544, F1: 0.1395

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.62899 | val 0.96360
  Epoch 011 - train 0.63988 | val 0.83362
  Classification -> best τ=0.360 (val F1=0.1700)
  Directional -> Accuracy: 0.6087, MCC: 0.1757, F1: 0.7097

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 16). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.71057 | val 0.83768
  Epoch 011 - train 0.69140 | val 0.72900
  Classification -> best τ=0.400 (val F1=0.3833)
  Directional -> Accuracy: 0.5417, MCC: 0.1080, F1: 0.5000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.74890 | val 0.73125
  Epoch 012 - train 0.73411 | val 1.52645
  Classification -> best τ=0.560 (val F1=0.2462)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.71294 | val 0.85330
  Epoch 011 - train 0.61370 | val 0.66527
  Classification -> best τ=0.165 (val F1=0.3753)
  Directional -> Accuracy: 0.6538, MCC: 0.3077, F1: 0.7273

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.70381 | val 1.04105
  Epoch 015 - train 0.56405 | val 2.26844
  Classification -> best τ=0.570 (val F1=0.4151)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.68097 | val 1.44125
  Epoch 011 - train 0.73885 | val 1.24242
  Classification -> best τ=0.625 (val F1=0.1715)
  Directional -> Accuracy: 0.5857, MCC: -0.0983, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 16). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.67352 | val 5.26302
  Epoch 013 - train 0.63941 | val 7.29600
  Classification -> best τ=0.640 (val F1=0.3368)
  Directional -> Accuracy: 0.4222, MCC: -0.0340, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.87154 | val 0.73060
  Epoch 016 - train 0.72254 | val 0.95661
  Classification -> best τ=0.380 (val F1=0.4404)
  Directional -> Accuracy: 0.4634, MCC: -0.1911, F1: 0.2143

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 16). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 16). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.69689 | val 3.27871
  Epoch 011 - train 0.63004 | val 4.30903
  Classification -> best τ=0.560 (val F1=0.1587)
  Directional -> Accuracy: 0.5775, MCC: 0.0907, F1: 0.1667

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.70534 | val 1.17035
  Epoch 016 - train 0.70292 | val 0.98738
  Classification -> best τ=0.670 (val F1=0.3244)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.68284 | val 1.03164
  Epoch 011 - train 0.76166 | val 0.86887
  Classification -> best τ=0.385 (val F1=0.2608)
  Directional -> Accuracy: 0.5085, MCC: 0.0000, F1: 0.6742

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.73180 | val 0.84101
  Epoch 011 - train 0.69048 | val 0.92790
  Classification -> best τ=0.540 (val F1=0.2037)
  Directional -> Accuracy: 0.3721, MCC: -0.2329, F1: 0.4906

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.68799 | val 0.69663
  Epoch 020 - train 0.71199 | val 0.92511
  Epoch 026 - train 0.64678 | val 2.15790
  Classification -> best τ=0.505 (val F1=0.3961)
  Directional -> Accuracy: 0.5246, MCC: 0.0470, F1: 0.5672

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.74076 | val 2.77575
  Epoch 012 - train 0.78418 | val 3.20885
  Classification -> best τ=0.470 (val F1=0.1782)
  Directional -> Accuracy: 0.5094, MCC: 0.0596, F1: 0.6061

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.67403 | val 1.34324
  Epoch 011 - train 0.72877 | val 1.19001
  Classification -> best τ=0.755 (val F1=0.1565)
  Directional -> Accuracy: 0.4286, MCC: -0.1162, F1: 0.2857

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.70842 | val 0.77818
  Epoch 011 - train 0.69427 | val 0.92908
  Classification -> best τ=0.680 (val F1=0.1796)
  Directional -> Accuracy: 0.3833, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.68454 | val 0.77280
  Epoch 011 - train 0.67233 | val 1.75286
  Classification -> best τ=0.440 (val F1=0.2434)
  Directional -> Accuracy: 0.5132, MCC: 0.2239, F1: 0.3729

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.69162 | val 0.77177
  Epoch 016 - train 0.71826 | val 0.83737
  Classification -> best τ=0.720 (val F1=0.3510)
  Directional -> Accuracy: 0.4545, MCC: 0.0413, F1: 0.2800

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 16). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.75877 | val 0.73701
  Epoch 017 - train 0.68827 | val 1.37062
  Classification -> best τ=0.640 (val F1=0.3242)
  Directional -> Accuracy: 0.4605, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.69201 | val 0.72413
  Epoch 014 - train 0.78275 | val 1.05447
  Classification -> best τ=0.535 (val F1=0.3143)
  Directional -> Accuracy: 0.4792, MCC: 0.0337, F1: 0.4681

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.70727 | val 2.12372
  Epoch 012 - train 0.66864 | val 3.54659
  Classification -> best τ=0.540 (val F1=0.1677)
  Directional -> Accuracy: 0.5758, MCC: 0.1808, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.70949 | val 0.80007
  Epoch 011 - train 0.71300 | val 0.81333
  Classification -> best τ=0.500 (val F1=0.1819)
  Directional -> Accuracy: 0.5345, MCC: 0.0649, F1: 0.5714

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.66726 | val 1.80680
  Epoch 012 - train 0.70246 | val 2.14969
  Classification -> best τ=0.425 (val F1=0.2417)
  Directional -> Accuracy: 0.4848, MCC: -0.0089, F1: 0.5526

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.71070 | val 0.98857
  Epoch 013 - train 0.64390 | val 2.24036
  Classification -> best τ=0.410 (val F1=0.4278)
  Directional -> Accuracy: 0.5179, MCC: 0.1373, F1: 0.3415

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.62961 | val 2.46664
  Epoch 012 - train 0.65977 | val 1.02040
  Classification -> best τ=0.400 (val F1=0.2067)
  Directional -> Accuracy: 0.7234, MCC: 0.4624, F1: 0.7111

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.75221 | val 0.69083
  Epoch 011 - train 0.72396 | val 0.75274
  Classification -> best τ=0.630 (val F1=0.3078)
  Directional -> Accuracy: 0.5116, MCC: 0.0866, F1: 0.4615

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.74678 | val 0.77294
  Epoch 012 - train 0.65047 | val 1.10353
  Classification -> best τ=0.325 (val F1=0.2945)
  Directional -> Accuracy: 0.5172, MCC: -0.0134, F1: 0.6216

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.67536 | val 1.14285
  Epoch 014 - train 0.67845 | val 0.76406
  Classification -> best τ=0.485 (val F1=0.4543)
  Directional -> Accuracy: 0.5000, MCC: -0.1319, F1: 0.6557

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.65671 | val 1.00385
  Epoch 011 - train 0.63918 | val 1.23727
  Classification -> best τ=0.610 (val F1=0.1869)
  Directional -> Accuracy: 0.5227, MCC: 0.0621, F1: 0.2759

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.76368 | val 0.72545
  Epoch 015 - train 0.68239 | val 1.00711
  Classification -> best τ=0.730 (val F1=0.2949)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.72115 | val 0.84135
  Epoch 012 - train 0.77172 | val 0.73960
  Classification -> best τ=0.340 (val F1=0.2177)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.64999 | val 0.68286
  Epoch 011 - train 0.69984 | val 0.71303
  Classification -> best τ=0.365 (val F1=0.3351)
  Directional -> Accuracy: 0.5541, MCC: 0.0271, F1: 0.6796

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.68722 | val 1.05674
  Epoch 015 - train 0.62537 | val 1.31749
  Classification -> best τ=0.480 (val F1=0.3130)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6415

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.74165 | val 0.67967
  Epoch 020 - train 0.65374 | val 1.58634
  Classification -> best τ=0.425 (val F1=0.2857)
  Directional -> Accuracy: 0.5556, MCC: 0.2922, F1: 0.6774

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.73071 | val 1.01599
  Epoch 015 - train 0.67168 | val 1.14128
  Classification -> best τ=0.100 (val F1=0.3521)
  Directional -> Accuracy: 0.5970, MCC: 0.1759, F1: 0.6494

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.69408 | val 0.70456
  Epoch 013 - train 0.64302 | val 0.93253
  Classification -> best τ=0.460 (val F1=0.1271)
  Directional -> Accuracy: 0.6512, MCC: 0.3392, F1: 0.5714

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.63513 | val 0.82831
  Epoch 012 - train 0.75154 | val 0.71207
  Classification -> best τ=0.555 (val F1=0.3305)
  Directional -> Accuracy: 0.4912, MCC: -0.1231, F1: 0.0645

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.69419 | val 0.63628
  Epoch 020 - train 0.66889 | val 0.99725
  Classification -> best τ=0.395 (val F1=0.4872)
  Directional -> Accuracy: 0.5957, MCC: 0.1357, F1: 0.6780

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 16). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.76758 | val 1.40266
  Epoch 012 - train 0.61715 | val 1.62125
  Classification -> best τ=0.255 (val F1=0.3410)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.66713 | val 1.05421
  Epoch 013 - train 0.65125 | val 1.31695
  Classification -> best τ=0.570 (val F1=0.3893)
  Directional -> Accuracy: 0.5641, MCC: 0.1139, F1: 0.6222

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 16). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.73859 | val 1.03219
  Epoch 012 - train 0.70475 | val 0.71931
  Classification -> best τ=0.330 (val F1=0.3006)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.75079 | val 0.83342
  Epoch 013 - train 0.68813 | val 0.78672
  Classification -> best τ=0.495 (val F1=0.1898)
  Directional -> Accuracy: 0.5106, MCC: 0.0509, F1: 0.2581

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.70345 | val 1.22001
  Epoch 011 - train 0.62334 | val 1.44932
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.76013 | val 0.90835
  Epoch 012 - train 0.64802 | val 0.69198
  Classification -> best τ=0.515 (val F1=0.3143)
  Directional -> Accuracy: 0.6250, MCC: -0.0099, F1: 0.1176

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.78337 | val 1.23350
  Epoch 012 - train 0.70707 | val 6.89961
  Classification -> best τ=0.620 (val F1=0.1512)
  Directional -> Accuracy: 0.3333, MCC: -0.3237, F1: 0.2963

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.65998 | val 1.68575
  Epoch 017 - train 0.68685 | val 2.43743
  Classification -> best τ=0.870 (val F1=0.3108)
  Directional -> Accuracy: 0.5789, MCC: 0.1803, F1: 0.2941

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.72596 | val 0.67435
  Epoch 020 - train 0.67124 | val 0.73952
  Classification -> best τ=0.620 (val F1=0.1682)
  Directional -> Accuracy: 0.5000, MCC: -0.1324, F1: 0.6667

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.67544 | val 1.20504
  Epoch 012 - train 0.65772 | val 0.82543
  Classification -> best τ=0.520 (val F1=0.2071)
  Directional -> Accuracy: 0.5439, MCC: 0.1941, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.70368 | val 1.08725

[I 2026-02-25 01:19:58,196] Trial 123 finished with value: 0.2705570769923216 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 15, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 16, 'learning_rate': 0.0097085552555132, 'weight_decay': 9.245723273393851e-06, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.912927023188289, 'early_stopping_min_delta': 0.0007191370480850639}. Best is trial 32 with value: 0.2908549754956826.

  Epoch 012 - train 0.68268 | val 1.06518
  Classification -> best τ=0.375 (val F1=0.0681)
  Directional -> Accuracy: 0.5161, MCC: 0.0839, F1: 0.6429

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2705570769923216
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 15
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.68508 | val 0.81561
  Epoch 013 - train 0.72368 | val 1.41837
  Classification -> best τ=0.700 (val F1=0.2453)
  Directional -> Accuracy: 0.5065, MCC: -0.0886, F1: 0.1364

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.63642 | val 1.02479
  Epoch 012 - train 0.56405 | val 1.11557
  Classification -> best τ=0.535 (val F1=0.1962)
  Directional -> Accuracy: 0.6087, MCC: 0.1823, F1: 0.6897

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 16). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.67936 | val 0.75665
  Epoch 011 - train 0.69131 | val 0.71801
  Classification -> best τ=0.625 (val F1=0.3271)
  Directional -> Accuracy: 0.4583, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.68087 | val 1.26875
  Epoch 011 - train 0.65964 | val 2.19908
  Classification -> best τ=0.455 (val F1=0.0936)
  Directional -> Accuracy: 0.5333, MCC: 0.0816, F1: 0.5205

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.64758 | val 0.76712
  Epoch 012 - train 0.63390 | val 0.75174
  Classification -> best τ=0.710 (val F1=0.4667)
  Directional -> Accuracy: 0.5385, MCC: 0.2673, F1: 0.2500

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.61767 | val 1.02529
  Epoch 013 - train 0.61209 | val 1.83120
  Classification -> best τ=0.540 (val F1=0.3086)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.69096 | val 0.88988
  Epoch 011 - train 0.67804 | val 0.94949
  Classification -> best τ=0.395 (val F1=0.1806)
  Directional -> Accuracy: 0.4000, MCC: -0.0625, F1: 0.5435

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 16). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.68783 | val 3.91881
  Epoch 011 - train 0.61084 | val 5.00083
  Classification -> best τ=0.555 (val F1=0.3280)
  Directional -> Accuracy: 0.4444, MCC: 0.0159, F1: 0.5763

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.72146 | val 0.80613
  Epoch 017 - train 0.63179 | val 1.16690
  Classification -> best τ=0.555 (val F1=0.4282)
  Directional -> Accuracy: 0.5610, MCC: 0.1618, F1: 0.5263

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 16). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 16). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.65469 | val 2.65862
  Epoch 011 - train 0.64065 | val 2.80198
  Classification -> best τ=0.135 (val F1=0.1827)
  Directional -> Accuracy: 0.4366, MCC: 0.0000, F1: 0.6078

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.65521 | val 0.91726
  Epoch 011 - train 0.67928 | val 1.16801
  Classification -> best τ=0.370 (val F1=0.1877)
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.6400

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.65656 | val 0.89109
  Epoch 017 - train 0.64744 | val 0.69909
  Classification -> best τ=0.715 (val F1=0.2394)
  Directional -> Accuracy: 0.6441, MCC: 0.3261, F1: 0.5532

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.65493 | val 1.20095
  Epoch 011 - train 0.63581 | val 1.32868
  Classification -> best τ=0.590 (val F1=0.2108)
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.75094 | val 0.75751
  Epoch 011 - train 0.69217 | val 0.72156
  Classification -> best τ=0.415 (val F1=0.2393)
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.64397 | val 4.27706
  Epoch 011 - train 0.66478 | val 5.13016
  Classification -> best τ=0.650 (val F1=0.2798)
  Directional -> Accuracy: 0.5283, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.71682 | val 0.85547
  Epoch 015 - train 0.66267 | val 1.07841
  Classification -> best τ=0.705 (val F1=0.3197)
  Directional -> Accuracy: 0.5571, MCC: 0.1100, F1: 0.5867

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.66310 | val 1.30842
  Epoch 011 - train 0.66123 | val 1.55465
  Classification -> best τ=0.580 (val F1=0.1796)
  Directional -> Accuracy: 0.5167, MCC: 0.2606, F1: 0.3830

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.65508 | val 1.29084
  Epoch 011 - train 0.66819 | val 1.78405
  Classification -> best τ=0.585 (val F1=0.1517)
  Directional -> Accuracy: 0.4868, MCC: 0.1299, F1: 0.3607

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.64982 | val 0.73083
  Epoch 020 - train 0.61158 | val 1.39908
  Epoch 021 - train 0.56891 | val 2.23888
  Classification -> best τ=0.405 (val F1=0.3380)
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 16). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.65482 | val 1.03636
  Epoch 017 - train 0.62328 | val 1.07293
  Classification -> best τ=0.420 (val F1=0.2953)
  Directional -> Accuracy: 0.4605, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.63927 | val 2.22803
  Epoch 011 - train 0.61489 | val 2.85563
  Classification -> best τ=0.375 (val F1=0.2174)
  Directional -> Accuracy: 0.5625, MCC: 0.1870, F1: 0.5714

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.67158 | val 1.86113
  Epoch 011 - train 0.68730 | val 1.98842
  Classification -> best τ=0.310 (val F1=0.1952)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.68513 | val 0.89921
  Epoch 012 - train 0.66112 | val 0.91394
  Classification -> best τ=0.540 (val F1=0.1777)
  Directional -> Accuracy: 0.3966, MCC: -0.2042, F1: 0.4262

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.70692 | val 0.84829
  Epoch 011 - train 0.67577 | val 1.13927
  Classification -> best τ=0.310 (val F1=0.2319)
  Directional -> Accuracy: 0.5758, MCC: 0.1716, F1: 0.6111

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.62415 | val 0.78592
  Epoch 013 - train 0.62667 | val 1.00604
  Classification -> best τ=0.460 (val F1=0.4826)
  Directional -> Accuracy: 0.5536, MCC: 0.2064, F1: 0.4186

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.56349 | val 2.01682
  Epoch 011 - train 0.62861 | val 1.89152
  Classification -> best τ=0.410 (val F1=0.0961)
  Directional -> Accuracy: 0.5745, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.67739 | val 0.71426
  Epoch 012 - train 0.69379 | val 0.88378
  Classification -> best τ=0.620 (val F1=0.2324)
  Directional -> Accuracy: 0.5349, MCC: 0.0905, F1: 0.5455

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.71263 | val 0.69626
  Epoch 017 - train 0.65905 | val 0.72776
  Classification -> best τ=0.480 (val F1=0.2039)
  Directional -> Accuracy: 0.4655, MCC: -0.0289, F1: 0.3673

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.69188 | val 0.69356
  Epoch 020 - train 0.64290 | val 0.66991
  Epoch 030 - train 0.67834 | val 1.01037
  Classification -> best τ=0.570 (val F1=0.4804)
  Directional -> Accuracy: 0.5238, MCC: 0.0784, F1: 0.4737

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.64599 | val 1.09987
  Epoch 011 - train 0.67216 | val 1.09608
  Classification -> best τ=0.570 (val F1=0.1869)
  Directional -> Accuracy: 0.5682, MCC: 0.1365, F1: 0.5581

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.71308 | val 1.35573
  Epoch 011 - train 0.70298 | val 1.37986
  Classification -> best τ=0.430 (val F1=0.1506)
  Directional -> Accuracy: 0.5227, MCC: 0.0415, F1: 0.5532

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.63303 | val 0.87338
  Epoch 012 - train 0.60305 | val 0.83686
  Classification -> best τ=0.765 (val F1=0.2320)
  Directional -> Accuracy: 0.5686, MCC: 0.1334, F1: 0.6857

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.63960 | val 1.65474
  Epoch 013 - train 0.63991 | val 2.17223
  Classification -> best τ=0.395 (val F1=0.3470)
  Directional -> Accuracy: 0.5541, MCC: 0.1516, F1: 0.5217

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.68293 | val 2.34719
  Epoch 011 - train 0.72312 | val 2.54369
  Classification -> best τ=0.355 (val F1=0.3130)
  Directional -> Accuracy: 0.5263, MCC: 0.1644, F1: 0.6786

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.71821 | val 1.09294
  Epoch 011 - train 0.68559 | val 1.31429
  Classification -> best τ=0.540 (val F1=0.5000)
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.6364

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.71762 | val 0.75573
  Epoch 013 - train 0.67058 | val 0.81131
  Classification -> best τ=0.145 (val F1=0.3431)
  Directional -> Accuracy: 0.6119, MCC: 0.1932, F1: 0.6829

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.67816 | val 1.05557
  Epoch 011 - train 0.67124 | val 1.20723
  Classification -> best τ=0.410 (val F1=0.1995)
  Directional -> Accuracy: 0.6279, MCC: 0.2967, F1: 0.5294

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.62719 | val 0.95451
  Epoch 014 - train 0.65033 | val 0.70575
  Classification -> best τ=0.365 (val F1=0.1920)
  Directional -> Accuracy: 0.5263, MCC: 0.1409, F1: 0.6494

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.75612 | val 1.25999
  Epoch 011 - train 0.64197 | val 0.96424
  Classification -> best τ=0.260 (val F1=0.2960)
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 16). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.63335 | val 0.82427
  Epoch 014 - train 0.60762 | val 0.86002
  Classification -> best τ=0.210 (val F1=0.4667)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.63700 | val 1.13299
  Epoch 013 - train 0.70271 | val 1.08848
  Classification -> best τ=0.420 (val F1=0.1870)
  Directional -> Accuracy: 0.5128, MCC: -0.0188, F1: 0.6275

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 16). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.72396 | val 0.70516
  Epoch 014 - train 0.68433 | val 0.81244
  Classification -> best τ=0.550 (val F1=0.2441)
  Directional -> Accuracy: 0.5132, MCC: 0.0531, F1: 0.6606

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.68937 | val 0.76877
  Epoch 014 - train 0.68229 | val 0.92598
  Classification -> best τ=0.500 (val F1=0.3119)
  Directional -> Accuracy: 0.5532, MCC: 0.1044, F1: 0.5882

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.61313 | val 1.08357
  Epoch 011 - train 0.64263 | val 1.12280
  Classification -> best τ=0.475 (val F1=0.2000)
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.62398 | val 1.26411
  Epoch 013 - train 0.65178 | val 1.30756
  Classification -> best τ=0.525 (val F1=0.3647)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.65273 | val 3.05022
  Epoch 011 - train 0.70915 | val 2.33664
  Classification -> best τ=0.775 (val F1=0.1059)
  Directional -> Accuracy: 0.4561, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.67191 | val 1.00684
  Epoch 013 - train 0.65221 | val 2.64219
  Classification -> best τ=0.345 (val F1=0.2554)
  Directional -> Accuracy: 0.4737, MCC: -0.0101, F1: 0.6341

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.70803 | val 0.83917
  Epoch 014 - train 0.62731 | val 0.89944
  Classification -> best τ=0.745 (val F1=0.1154)
  Directional -> Accuracy: 0.5185, MCC: 0.1048, F1: 0.2353

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.65694 | val 0.84762
  Epoch 011 - train 0.66144 | val 0.90621
  Classification -> best τ=0.405 (val F1=0.1093)
  Directional -> Accuracy: 0.4912, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.72230 | val 0.68532
  Epoch 020 - train 0.67152 | val 0.98413

[I 2026-02-25 01:22:32,898] Trial 124 finished with value: 0.2592616160230587 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 15, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 16, 'learning_rate': 0.0059141899759819795, 'weight_decay': 1.6334139169985784e-07, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.791318335122397, 'early_stopping_min_delta': 0.0012318294430925733}. Best is trial 32 with value: 0.2908549754956826.

  Epoch 026 - train 0.66991 | val 0.72743
  Classification -> best τ=0.405 (val F1=0.3271)
  Directional -> Accuracy: 0.4516, MCC: -0.0946, F1: 0.5641

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2592616160230587
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 15
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.71612 | val 1.04076
  Epoch 020 - train 0.68153 | val 0.74625
  Epoch 025 - train 0.68950 | val 0.69816
  Classification -> best τ=0.395 (val F1=0.3044)
  Directional -> Accuracy: 0.5455, MCC: 0.0468, F1: 0.3137

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.61533 | val 0.80225
  Epoch 012 - train 0.58143 | val 0.91631
  Classification -> best τ=0.485 (val F1=0.1812)
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 16). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.76198 | val 0.74788
  Epoch 013 - train 0.70866 | val 1.09503
  Classification -> best τ=0.460 (val F1=0.3295)
  Directional -> Accuracy: 0.4792, MCC: -0.1431, F1: 0.6269

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.66599 | val 6.07313
  Epoch 011 - train 0.74606 | val 2.86177
  Classification -> best τ=0.275 (val F1=0.1560)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.66348 | val 1.95297
  Epoch 013 - train 0.61191 | val 1.10135
  Classification -> best τ=0.655 (val F1=0.3795)
  Directional -> Accuracy: 0.6346, MCC: 0.3851, F1: 0.5128

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.65454 | val 3.97518
  Epoch 013 - train 0.57576 | val 6.98271
  Classification -> best τ=0.625 (val F1=0.4473)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.70980 | val 0.75211
  Epoch 011 - train 0.70568 | val 0.74865
  Classification -> best τ=0.430 (val F1=0.2857)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.5714

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 16). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.67026 | val 5.51392
  Epoch 011 - train 0.73313 | val 5.40303
  Classification -> best τ=0.485 (val F1=0.2548)
  Directional -> Accuracy: 0.4222, MCC: -0.0950, F1: 0.5000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.71799 | val 1.49701
  Epoch 016 - train 0.70088 | val 1.07865
  Classification -> best τ=0.750 (val F1=0.3624)
  Directional -> Accuracy: 0.6341, MCC: 0.2228, F1: 0.5161

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 16). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 16). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.73908 | val 0.96879
  Epoch 011 - train 0.67243 | val 0.94909
  Classification -> best τ=0.440 (val F1=0.0850)
  Directional -> Accuracy: 0.5070, MCC: 0.0947, F1: 0.5882

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.71635 | val 0.89670
  Epoch 013 - train 0.86431 | val 2.79030
  Classification -> best τ=0.365 (val F1=0.2147)
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.6400

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.62934 | val 0.89949
  Epoch 012 - train 0.70969 | val 0.81099
  Classification -> best τ=0.575 (val F1=0.2701)
  Directional -> Accuracy: 0.4915, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.73117 | val 1.30223
  Epoch 011 - train 0.64893 | val 0.99740
  Classification -> best τ=0.500 (val F1=0.2454)
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.67285 | val 0.69301
  Epoch 019 - train 0.70617 | val 0.81147
  Classification -> best τ=0.260 (val F1=0.3618)
  Directional -> Accuracy: 0.5410, MCC: 0.0906, F1: 0.6500

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.67598 | val 1.28853
  Epoch 013 - train 0.70167 | val 2.16947
  Classification -> best τ=0.545 (val F1=0.2798)
  Directional -> Accuracy: 0.5283, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.69710 | val 0.87169
  Epoch 013 - train 0.64333 | val 1.31472
  Classification -> best τ=0.690 (val F1=0.2723)
  Directional -> Accuracy: 0.5143, MCC: 0.0262, F1: 0.5405

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.66925 | val 1.59128
  Epoch 011 - train 0.67997 | val 1.48917
  Classification -> best τ=0.620 (val F1=0.3224)
  Directional -> Accuracy: 0.4000, MCC: 0.1026, F1: 0.0526

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.72947 | val 1.66087
  Epoch 011 - train 0.65336 | val 2.82042
  Classification -> best τ=0.425 (val F1=0.1917)
  Directional -> Accuracy: 0.5395, MCC: 0.2397, F1: 0.4444

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.69657 | val 0.82858
  Epoch 016 - train 0.73305 | val 0.73161
  Classification -> best τ=0.300 (val F1=0.2409)
  Directional -> Accuracy: 0.4697, MCC: 0.0938, F1: 0.2857

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 16). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.68809 | val 0.90781
  Epoch 011 - train 0.66987 | val 0.93328
  Classification -> best τ=0.395 (val F1=0.2313)
  Directional -> Accuracy: 0.4605, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.64451 | val 2.67186
  Epoch 011 - train 0.61246 | val 3.15488
  Classification -> best τ=0.520 (val F1=0.0722)
  Directional -> Accuracy: 0.5417, MCC: 0.1080, F1: 0.5769

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.71045 | val 1.61315
  Epoch 011 - train 0.69185 | val 1.46230
  Classification -> best τ=0.460 (val F1=0.2070)
  Directional -> Accuracy: 0.5455, MCC: 0.1325, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.73018 | val 0.88210
  Epoch 015 - train 0.68605 | val 1.13317
  Classification -> best τ=0.545 (val F1=0.2947)
  Directional -> Accuracy: 0.5862, MCC: 0.1411, F1: 0.6571

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.70300 | val 1.48800
  Epoch 012 - train 0.75260 | val 1.52437
  Classification -> best τ=0.340 (val F1=0.1318)
  Directional -> Accuracy: 0.5455, MCC: 0.1318, F1: 0.0625

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.65180 | val 1.58381
  Epoch 018 - train 0.71635 | val 1.63119
  Classification -> best τ=0.435 (val F1=0.4105)
  Directional -> Accuracy: 0.5000, MCC: 0.0996, F1: 0.3000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.61647 | val 1.30460
  Epoch 011 - train 0.56452 | val 1.41633
  Classification -> best τ=0.485 (val F1=0.2821)
  Directional -> Accuracy: 0.5745, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.73407 | val 0.69539
  Epoch 020 - train 0.69835 | val 0.67925
  Epoch 023 - train 0.65813 | val 0.70875
  Classification -> best τ=0.645 (val F1=0.2717)
  Directional -> Accuracy: 0.3953, MCC: -0.1334, F1: 0.1333

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.71060 | val 0.80764
  Epoch 014 - train 0.69655 | val 0.94695
  Classification -> best τ=0.270 (val F1=0.3035)
  Directional -> Accuracy: 0.5690, MCC: 0.1859, F1: 0.5098

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.69025 | val 0.70110
  Epoch 020 - train 0.69145 | val 0.80952
  Epoch 021 - train 0.72399 | val 0.82959
  Classification -> best τ=0.535 (val F1=0.2833)
  Directional -> Accuracy: 0.5238, MCC: 0.1249, F1: 0.3750

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.61991 | val 1.55104
  Epoch 011 - train 0.67549 | val 1.69392
  Classification -> best τ=0.700 (val F1=0.1869)
  Directional -> Accuracy: 0.5455, MCC: 0.0913, F1: 0.5652

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.69246 | val 1.02089
  Epoch 013 - train 0.65866 | val 1.28101
  Classification -> best τ=0.715 (val F1=0.1688)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.61647 | val 0.99499
  Epoch 012 - train 0.64494 | val 1.23820
  Classification -> best τ=0.410 (val F1=0.3079)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.66381 | val 2.78665
  Epoch 011 - train 0.67548 | val 1.91416
  Classification -> best τ=0.360 (val F1=0.3134)
  Directional -> Accuracy: 0.5270, MCC: 0.1044, F1: 0.4776

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.61233 | val 1.11032
  Epoch 011 - train 0.61776 | val 1.15590
  Classification -> best τ=0.390 (val F1=0.2227)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.5778

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.70253 | val 1.07799
  Epoch 011 - train 0.72884 | val 1.25235
  Classification -> best τ=0.320 (val F1=0.2922)
  Directional -> Accuracy: 0.5556, MCC: 0.2359, F1: 0.6667

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.61924 | val 1.09592
  Epoch 011 - train 0.65799 | val 1.01454
  Classification -> best τ=0.240 (val F1=0.3767)
  Directional -> Accuracy: 0.6119, MCC: 0.2035, F1: 0.6667

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.68225 | val 0.84088
  Epoch 011 - train 0.69661 | val 0.99533
  Classification -> best τ=0.380 (val F1=0.1513)
  Directional -> Accuracy: 0.4186, MCC: -0.1623, F1: 0.4186

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.71832 | val 0.72290
  Epoch 013 - train 0.68230 | val 0.68676
  Classification -> best τ=0.475 (val F1=0.3015)
  Directional -> Accuracy: 0.5965, MCC: 0.2147, F1: 0.6349

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.61581 | val 1.04487
  Epoch 017 - train 0.59758 | val 1.56965
  Classification -> best τ=0.470 (val F1=0.2794)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 16). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.72984 | val 1.44530
  Epoch 015 - train 0.60080 | val 0.96508
  Classification -> best τ=0.415 (val F1=0.4667)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.72227 | val 1.49051
  Epoch 012 - train 0.65756 | val 1.28084
  Classification -> best τ=0.305 (val F1=0.1870)
  Directional -> Accuracy: 0.4872, MCC: -0.2152, F1: 0.6552

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 16). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.70045 | val 0.81438
  Epoch 013 - train 0.70143 | val 0.76580
  Classification -> best τ=0.575 (val F1=0.3026)
  Directional -> Accuracy: 0.4868, MCC: -0.0531, F1: 0.0930

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.65625 | val 0.71606
  Epoch 011 - train 0.63441 | val 0.72942
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.67400 | val 1.70537
  Epoch 011 - train 0.63853 | val 1.76984
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.70171 | val 0.79707
  Epoch 011 - train 0.68495 | val 0.74776
  Classification -> best τ=0.635 (val F1=0.3447)
  Directional -> Accuracy: 0.3750, MCC: 0.1175, F1: 0.5283

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.66746 | val 1.92194
  Epoch 011 - train 0.70191 | val 1.08969
  Classification -> best τ=0.450 (val F1=0.1591)
  Directional -> Accuracy: 0.6491, MCC: 0.3045, F1: 0.6552

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.73816 | val 1.00963
  Epoch 012 - train 0.64672 | val 3.29102
  Classification -> best τ=0.380 (val F1=0.2554)
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.69401 | val 0.68845
  Epoch 013 - train 0.66346 | val 0.70022
  Classification -> best τ=0.695 (val F1=0.1647)
  Directional -> Accuracy: 0.5370, MCC: 0.0771, F1: 0.5283

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.72433 | val 0.71416
  Epoch 019 - train 0.67506 | val 0.83911
  Classification -> best τ=0.370 (val F1=0.2794)
  Directional -> Accuracy: 0.5263, MCC: 0.1360, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.69898 | val 0.88128

[I 2026-02-25 01:25:06,870] Trial 125 finished with value: 0.2541581368762246 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 15, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 16, 'learning_rate': 0.007907456530825802, 'weight_decay': 4.475306802542345e-05, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.7399219676547435, 'early_stopping_min_delta': 0.0017281272520923978}. Best is trial 32 with value: 0.2908549754956826.

  Epoch 012 - train 0.66461 | val 0.68535
  Classification -> best τ=0.435 (val F1=0.2746)
  Directional -> Accuracy: 0.5000, MCC: -0.1240, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2541581368762246
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 15
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.65295 | val 0.76327
  Epoch 016 - train 0.67256 | val 0.71616
  Classification -> best τ=0.395 (val F1=0.3131)
  Directional -> Accuracy: 0.5195, MCC: -0.0423, F1: 0.1778

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.64308 | val 0.81670
  Epoch 013 - train 0.60799 | val 1.20280
  Classification -> best τ=0.495 (val F1=0.1962)
  Directional -> Accuracy: 0.5870, MCC: 0.1252, F1: 0.6885

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 16). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.69048 | val 0.77141
  Epoch 012 - train 0.64920 | val 0.76512
  Classification -> best τ=0.575 (val F1=0.2868)
  Directional -> Accuracy: 0.4583, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.69007 | val 1.51399
  Epoch 012 - train 0.65722 | val 1.15373
  Classification -> best τ=0.455 (val F1=0.1417)
  Directional -> Accuracy: 0.5600, MCC: 0.0982, F1: 0.6292

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.58664 | val 0.97375
  Epoch 013 - train 0.59861 | val 1.11346
  Classification -> best τ=0.450 (val F1=0.3566)
  Directional -> Accuracy: 0.6731, MCC: 0.3922, F1: 0.7606

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.60009 | val 0.89240
  Epoch 011 - train 0.62657 | val 0.99043
  Classification -> best τ=0.520 (val F1=0.2290)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.69873 | val 0.72201
  Epoch 012 - train 0.65690 | val 0.74760
  Classification -> best τ=0.515 (val F1=0.2462)
  Directional -> Accuracy: 0.5143, MCC: 0.0589, F1: 0.5000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 16). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.63226 | val 1.58378
  Epoch 011 - train 0.59634 | val 1.67021
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.67928 | val 0.69763
  Epoch 020 - train 0.65498 | val 1.03137
  Epoch 021 - train 0.63951 | val 0.90562
  Classification -> best τ=0.595 (val F1=0.4315)
  Directional -> Accuracy: 0.5610, MCC: 0.1618, F1: 0.5263

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 16). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 16). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.64561 | val 0.72518
  Epoch 013 - train 0.67404 | val 1.04168
  Classification -> best τ=0.490 (val F1=0.0471)
  Directional -> Accuracy: 0.5915, MCC: 0.1514, F1: 0.4727

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.65687 | val 1.38829
  Epoch 011 - train 0.64445 | val 1.68742
  Classification -> best τ=0.470 (val F1=0.1090)
  Directional -> Accuracy: 0.4314, MCC: -0.1434, F1: 0.5797

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.68209 | val 0.74323
  Epoch 011 - train 0.64868 | val 0.81607
  Classification -> best τ=0.460 (val F1=0.2300)
  Directional -> Accuracy: 0.5085, MCC: 0.0000, F1: 0.6742

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.65343 | val 1.08996
  Epoch 011 - train 0.68254 | val 1.25968
  Classification -> best τ=0.410 (val F1=0.2004)
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.66551 | val 0.71054
  Epoch 016 - train 0.63465 | val 0.73470
  Classification -> best τ=0.435 (val F1=0.3192)
  Directional -> Accuracy: 0.5574, MCC: 0.1455, F1: 0.6747

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.64745 | val 1.51802
  Epoch 011 - train 0.57382 | val 1.55251
  Classification -> best τ=0.535 (val F1=0.1150)
  Directional -> Accuracy: 0.5283, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.61410 | val 0.83836
  Epoch 017 - train 0.61178 | val 0.81175
  Classification -> best τ=0.630 (val F1=0.2570)
  Directional -> Accuracy: 0.4857, MCC: 0.1574, F1: 0.1000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.69756 | val 0.89141
  Epoch 012 - train 0.66732 | val 0.75780
  Classification -> best τ=0.420 (val F1=0.1346)
  Directional -> Accuracy: 0.6333, MCC: 0.2515, F1: 0.6857

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.67794 | val 1.19469
  Epoch 013 - train 0.65353 | val 1.18746
  Classification -> best τ=0.545 (val F1=0.1789)
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.67654 | val 0.89494
  Epoch 012 - train 0.66346 | val 1.04610
  Classification -> best τ=0.425 (val F1=0.2464)
  Directional -> Accuracy: 0.5455, MCC: 0.1887, F1: 0.4828

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 16). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.66028 | val 0.80616
  Epoch 013 - train 0.64964 | val 0.83661
  Classification -> best τ=0.575 (val F1=0.2869)
  Directional -> Accuracy: 0.4605, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.66185 | val 0.95743
  Epoch 011 - train 0.64034 | val 0.87209
  Classification -> best τ=0.465 (val F1=0.2174)
  Directional -> Accuracy: 0.5417, MCC: 0.0000, F1: 0.6452

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.65883 | val 1.14211
  Epoch 011 - train 0.65427 | val 1.17388
  Classification -> best τ=0.605 (val F1=0.1287)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.64616 | val 1.10197
  Epoch 012 - train 0.64008 | val 1.11143
  Classification -> best τ=0.580 (val F1=0.2504)
  Directional -> Accuracy: 0.5517, MCC: 0.1362, F1: 0.5357

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.63442 | val 2.92610
  Epoch 011 - train 0.61811 | val 4.00571
  Classification -> best τ=0.420 (val F1=0.2086)
  Directional -> Accuracy: 0.5455, MCC: 0.1290, F1: 0.6154

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.62987 | val 0.94442
  Epoch 014 - train 0.64283 | val 0.82487
  Classification -> best τ=0.475 (val F1=0.3161)
  Directional -> Accuracy: 0.5893, MCC: 0.1659, F1: 0.6349

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.60996 | val 1.09615
  Epoch 013 - train 0.59638 | val 0.82384
  Classification -> best τ=0.520 (val F1=0.1792)
  Directional -> Accuracy: 0.5745, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.66465 | val 0.69093
  Epoch 020 - train 0.62407 | val 0.87239
  Epoch 026 - train 0.59765 | val 0.93380
  Classification -> best τ=0.550 (val F1=0.2324)
  Directional -> Accuracy: 0.4884, MCC: 0.0653, F1: 0.3889

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.62750 | val 0.77068
  Epoch 013 - train 0.63181 | val 0.77404
  Classification -> best τ=0.410 (val F1=0.2673)
  Directional -> Accuracy: 0.5517, MCC: 0.0000, F1: 0.7111

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.72782 | val 0.78387
  Epoch 020 - train 0.68936 | val 1.07862
  Epoch 030 - train 0.62678 | val 1.12094
  Classification -> best τ=0.595 (val F1=0.4576)
  Directional -> Accuracy: 0.5238, MCC: 0.0389, F1: 0.5652

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.74065 | val 0.86153
  Epoch 011 - train 0.67851 | val 0.83829
  Classification -> best τ=0.470 (val F1=0.0150)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.3125

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.68801 | val 0.69214
  Epoch 018 - train 0.62514 | val 0.83011
  Classification -> best τ=0.660 (val F1=0.1239)
  Directional -> Accuracy: 0.4091, MCC: -0.2390, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.64267 | val 0.74190
  Epoch 011 - train 0.61803 | val 0.72289
  Classification -> best τ=0.460 (val F1=0.2366)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.67759 | val 0.69939
  Epoch 018 - train 0.63286 | val 1.76430
  Classification -> best τ=0.270 (val F1=0.3723)
  Directional -> Accuracy: 0.5811, MCC: 0.1565, F1: 0.6173

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.60259 | val 0.77485
  Epoch 013 - train 0.57452 | val 0.83088
  Classification -> best τ=0.440 (val F1=0.3130)
  Directional -> Accuracy: 0.5526, MCC: 0.1443, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.61524 | val 0.85892
  Epoch 011 - train 0.66000 | val 0.93711
  Classification -> best τ=0.480 (val F1=0.1410)
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.6364

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.64321 | val 0.69838
  Epoch 011 - train 0.60558 | val 0.73279
  Classification -> best τ=0.395 (val F1=0.3521)
  Directional -> Accuracy: 0.6119, MCC: 0.2035, F1: 0.6667

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.71786 | val 0.72712
  Epoch 015 - train 0.63452 | val 0.69820
  Classification -> best τ=0.530 (val F1=0.2683)
  Directional -> Accuracy: 0.5349, MCC: 0.1249, F1: 0.2857

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.66775 | val 0.70629
  Epoch 011 - train 0.64951 | val 0.72281
  Classification -> best τ=0.425 (val F1=0.1508)
  Directional -> Accuracy: 0.5263, MCC: 0.2236, F1: 0.6667

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.60960 | val 1.29961
  Epoch 012 - train 0.62154 | val 0.71310
  Classification -> best τ=0.545 (val F1=0.1978)
  Directional -> Accuracy: 0.6170, MCC: 0.1251, F1: 0.7273

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 16). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.55474 | val 1.20139
  Epoch 011 - train 0.59354 | val 1.56286
  Classification -> best τ=0.485 (val F1=0.4667)
  Directional -> Accuracy: 0.3750, MCC: 0.1175, F1: 0.5283

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.67118 | val 0.70914
  Epoch 011 - train 0.70646 | val 0.72206
  Classification -> best τ=0.460 (val F1=0.1870)
  Directional -> Accuracy: 0.5641, MCC: 0.1752, F1: 0.7119

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 16). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.65753 | val 0.75322
  Epoch 013 - train 0.65170 | val 0.86450
  Classification -> best τ=0.400 (val F1=0.3011)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.67462 | val 0.92116
  Epoch 011 - train 0.66854 | val 0.92160
  Classification -> best τ=0.520 (val F1=0.2858)
  Directional -> Accuracy: 0.5319, MCC: 0.0764, F1: 0.6667

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.63632 | val 0.90210
  Epoch 011 - train 0.66059 | val 0.89344
  Classification -> best τ=0.475 (val F1=0.2000)
  Directional -> Accuracy: 0.6000, MCC: 0.1921, F1: 0.7273

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.65033 | val 0.72983
  Epoch 015 - train 0.61968 | val 0.93705
  Classification -> best τ=0.520 (val F1=0.4476)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.71146 | val 1.05305
  Epoch 016 - train 0.64263 | val 1.04952
  Classification -> best τ=0.460 (val F1=0.1978)
  Directional -> Accuracy: 0.5789, MCC: 0.1570, F1: 0.6000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.67252 | val 1.01652
  Epoch 011 - train 0.62516 | val 1.03994
  Classification -> best τ=0.515 (val F1=0.2554)
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.66262 | val 1.14639
  Epoch 011 - train 0.68916 | val 0.97345
  Classification -> best τ=0.440 (val F1=0.0580)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.65269 | val 0.91752
  Epoch 011 - train 0.62173 | val 0.86680
  Classification -> best τ=0.580 (val F1=0.1576)
  Directional -> Accuracy: 0.5614, MCC: 0.1350, F1: 0.6575

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...

[I 2026-02-25 01:26:03,365] Trial 126 finished with value: 0.22839062930732365 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 15, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 32, 'learning_rate': 0.004510442384577642, 'weight_decay': 1.5089800389382163e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.895025351308007, 'early_stopping_min_delta': 0.00025188040930811703}. Best is trial 32 with value: 0.2908549754956826.

  Epoch 010 - train 0.68107 | val 1.08810
  Epoch 011 - train 0.66073 | val 0.82136
  Classification -> best τ=0.450 (val F1=0.1088)
  Directional -> Accuracy: 0.4839, MCC: 0.0000, F1: 0.6522

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.22839062930732365
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 15
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.66675 | val 0.66154
  Epoch 020 - train 0.66552 | val 0.65539
  Epoch 029 - train 0.65973 | val 0.66315
  Classification -> best τ=0.545 (val F1=0.3210)
  Directional -> Accuracy: 0.5065, MCC: -0.0886, F1: 0.1364

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.64225 | val 0.72152
  Epoch 011 - train 0.61737 | val 0.73701
  Classification -> best τ=0.430 (val F1=0.1433)
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 16). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.69340 | val 0.67705
  Epoch 020 - train 0.69186 | val 0.69853
  Epoch 023 - train 0.68268 | val 0.70949
  Classification -> best τ=0.660 (val F1=0.3271)
  Directional -> Accuracy: 0.4375, MCC: -0.1586, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.69480 | val 0.72438
  Epoch 020 - train 0.66505 | val 0.71522
  Epoch 021 - train 0.67790 | val 0.73170
  Classification -> best τ=0.450 (val F1=0.2886)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.66347 | val 1.08286
  Epoch 012 - train 0.61834 | val 1.47139
  Classification -> best τ=0.405 (val F1=0.4234)
  Directional -> Accuracy: 0.7115, MCC: 0.4361, F1: 0.7059

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.63014 | val 0.81520
  Epoch 011 - train 0.64747 | val 0.87141
  Classification -> best τ=0.495 (val F1=0.1898)
  Directional -> Accuracy: 0.4792, MCC: -0.0420, F1: 0.5098

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.68935 | val 0.72681
  Epoch 016 - train 0.69759 | val 0.71417
  Classification -> best τ=0.470 (val F1=0.2449)
  Directional -> Accuracy: 0.5429, MCC: 0.0934, F1: 0.5000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 16). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.64788 | val 1.94723
  Epoch 011 - train 0.64234 | val 1.92880
  Classification -> best τ=0.595 (val F1=0.2786)
  Directional -> Accuracy: 0.5556, MCC: 0.0891, F1: 0.4737

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.66519 | val 0.69675
  Epoch 020 - train 0.68040 | val 0.69340
  Epoch 026 - train 0.65763 | val 0.70662
  Classification -> best τ=0.460 (val F1=0.3318)
  Directional -> Accuracy: 0.4146, MCC: -0.0403, F1: 0.4783

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 16). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 16). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.64973 | val 0.77181
  Epoch 011 - train 0.62626 | val 0.77779
  Classification -> best τ=0.380 (val F1=0.2245)
  Directional -> Accuracy: 0.4366, MCC: -0.0633, F1: 0.5455

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.66428 | val 0.82394
  Epoch 012 - train 0.69091 | val 0.83904
  Classification -> best τ=0.480 (val F1=0.1835)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.66838 | val 0.66833
  Epoch 020 - train 0.66054 | val 0.68491
  Epoch 021 - train 0.68308 | val 0.69318
  Classification -> best τ=0.525 (val F1=0.2581)
  Directional -> Accuracy: 0.6271, MCC: 0.2728, F1: 0.6944

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.63506 | val 0.83548
  Epoch 018 - train 0.64423 | val 0.75468
  Classification -> best τ=0.575 (val F1=0.1711)
  Directional -> Accuracy: 0.5581, MCC: 0.0560, F1: 0.2963

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.68286 | val 0.64207
  Epoch 018 - train 0.65941 | val 0.63645
  Classification -> best τ=0.355 (val F1=0.3010)
  Directional -> Accuracy: 0.5246, MCC: 0.0468, F1: 0.6133

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.67121 | val 0.70623
  Epoch 020 - train 0.58835 | val 0.86213
  Classification -> best τ=0.625 (val F1=0.2262)
  Directional -> Accuracy: 0.5283, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.64091 | val 0.70547
  Epoch 011 - train 0.65211 | val 0.72661
  Classification -> best τ=0.545 (val F1=0.1934)
  Directional -> Accuracy: 0.5857, MCC: 0.1674, F1: 0.6133

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.67522 | val 0.81995
  Epoch 011 - train 0.67197 | val 0.78853
  Classification -> best τ=0.550 (val F1=0.1437)
  Directional -> Accuracy: 0.3333, MCC: -0.2910, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.69617 | val 0.79058
  Epoch 011 - train 0.67288 | val 0.78524
  Classification -> best τ=0.525 (val F1=0.1116)
  Directional -> Accuracy: 0.6053, MCC: 0.1375, F1: 0.7000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.66116 | val 0.77512
  Epoch 020 - train 0.65429 | val 0.69822
  Epoch 022 - train 0.64868 | val 0.83411
  Classification -> best τ=0.255 (val F1=0.3342)
  Directional -> Accuracy: 0.5152, MCC: -0.0028, F1: 0.5897

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 16). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.68086 | val 0.68590
  Epoch 012 - train 0.66675 | val 0.69872
  Classification -> best τ=0.465 (val F1=0.2626)
  Directional -> Accuracy: 0.4605, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.68599 | val 0.70729
  Epoch 019 - train 0.65195 | val 0.72647
  Classification -> best τ=0.390 (val F1=0.3143)
  Directional -> Accuracy: 0.5417, MCC: 0.0222, F1: 0.6333

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.66978 | val 0.94239
  Epoch 011 - train 0.69337 | val 1.05433
  Classification -> best τ=0.470 (val F1=0.1678)
  Directional -> Accuracy: 0.6212, MCC: 0.2425, F1: 0.6269

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.64264 | val 1.07158
  Epoch 011 - train 0.69359 | val 1.11129
  Classification -> best τ=0.670 (val F1=0.2299)
  Directional -> Accuracy: 0.5517, MCC: 0.1362, F1: 0.5357

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.68455 | val 0.71630
  Epoch 011 - train 0.67293 | val 0.73756
  Classification -> best τ=0.490 (val F1=0.1961)
  Directional -> Accuracy: 0.4848, MCC: 0.0596, F1: 0.6383

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.69031 | val 0.66636
  Epoch 013 - train 0.68711 | val 0.67282
  Classification -> best τ=0.540 (val F1=0.5105)
  Directional -> Accuracy: 0.5357, MCC: 0.1728, F1: 0.3810

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.64222 | val 0.72614
  Epoch 012 - train 0.64666 | val 0.73939
  Classification -> best τ=0.535 (val F1=0.2471)
  Directional -> Accuracy: 0.4894, MCC: 0.1183, F1: 0.6000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.67258 | val 0.68704
  Epoch 020 - train 0.63233 | val 0.69406
  Epoch 024 - train 0.61065 | val 0.68454
  Classification -> best τ=0.575 (val F1=0.0140)
  Directional -> Accuracy: 0.6047, MCC: 0.1599, F1: 0.6909

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.65730 | val 0.69054
  Epoch 016 - train 0.62809 | val 0.78496
  Classification -> best τ=0.390 (val F1=0.2935)
  Directional -> Accuracy: 0.4828, MCC: 0.1085, F1: 0.1667

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.68300 | val 0.68795
  Epoch 020 - train 0.68572 | val 0.70178
  Epoch 028 - train 0.63998 | val 0.74531
  Classification -> best τ=0.445 (val F1=0.2924)
  Directional -> Accuracy: 0.6190, MCC: 0.3052, F1: 0.7419

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.64613 | val 1.23603
  Epoch 011 - train 0.70161 | val 1.36736
  Classification -> best τ=0.590 (val F1=0.1913)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.67939 | val 0.63914
  Epoch 019 - train 0.67748 | val 0.66264
  Classification -> best τ=0.700 (val F1=0.2498)
  Directional -> Accuracy: 0.3864, MCC: -0.2269, F1: 0.1290

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.62735 | val 0.69537
  Epoch 019 - train 0.57974 | val 0.78912
  Classification -> best τ=0.495 (val F1=0.3067)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.69322 | val 0.66637
  Epoch 014 - train 0.66923 | val 0.67583
  Classification -> best τ=0.405 (val F1=0.2873)
  Directional -> Accuracy: 0.5270, MCC: 0.1525, F1: 0.4068

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.62435 | val 0.79464
  Epoch 011 - train 0.62496 | val 0.80298
  Classification -> best τ=0.445 (val F1=0.3706)
  Directional -> Accuracy: 0.6316, MCC: 0.3394, F1: 0.7200

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.66956 | val 0.72875
  Epoch 014 - train 0.63335 | val 0.75251
  Classification -> best τ=0.405 (val F1=0.2922)
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.6364

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.65970 | val 0.71485
  Epoch 013 - train 0.62679 | val 0.75967
  Classification -> best τ=0.400 (val F1=0.3954)
  Directional -> Accuracy: 0.5970, MCC: 0.1759, F1: 0.6494

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.67821 | val 0.70422
  Epoch 017 - train 0.68437 | val 0.72712
  Classification -> best τ=0.435 (val F1=0.2664)
  Directional -> Accuracy: 0.6279, MCC: 0.3176, F1: 0.5000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.64227 | val 0.70357
  Epoch 013 - train 0.63137 | val 0.69913
  Classification -> best τ=0.495 (val F1=0.1851)
  Directional -> Accuracy: 0.4211, MCC: -0.1508, F1: 0.4590

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.67646 | val 0.81409
  Epoch 014 - train 0.57976 | val 0.82029
  Classification -> best τ=0.485 (val F1=0.2718)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 16). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.62080 | val 1.47783
  Epoch 011 - train 0.59525 | val 1.63959
  Classification -> best τ=0.545 (val F1=0.1556)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.67012 | val 0.84197
  Epoch 011 - train 0.61235 | val 0.84660
  Classification -> best τ=0.445 (val F1=0.0406)
  Directional -> Accuracy: 0.3846, MCC: -0.2234, F1: 0.3684

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 16). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.64884 | val 0.68616
  Epoch 017 - train 0.66455 | val 0.70344
  Classification -> best τ=0.360 (val F1=0.3006)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.66756 | val 0.72767
  Epoch 011 - train 0.67068 | val 0.76121
  Classification -> best τ=0.560 (val F1=0.2290)
  Directional -> Accuracy: 0.6170, MCC: 0.2344, F1: 0.6538

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.65935 | val 1.19712
  Epoch 011 - train 0.60821 | val 1.18951
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.68405 | val 0.72538
  Epoch 014 - train 0.61717 | val 0.71195
  Classification -> best τ=0.480 (val F1=0.2219)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.66981 | val 0.77255
  Epoch 013 - train 0.67084 | val 0.71167
  Classification -> best τ=0.540 (val F1=0.1869)
  Directional -> Accuracy: 0.4561, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.68470 | val 0.83085
  Epoch 011 - train 0.68920 | val 0.77866
  Classification -> best τ=0.480 (val F1=0.2554)
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.65657 | val 0.89824
  Epoch 011 - train 0.67275 | val 0.86733
  Classification -> best τ=0.440 (val F1=0.2184)
  Directional -> Accuracy: 0.5926, MCC: 0.1911, F1: 0.6765

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.69040 | val 0.77470
  Epoch 019 - train 0.65887 | val 0.83064
  Classification -> best τ=0.685 (val F1=0.1009)
  Directional -> Accuracy: 0.5439, MCC: 0.1004, F1: 0.6579

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.66620 | val 0.70902
  Epoch 020 - train 0.68317 | val 0.67043

[I 2026-02-25 01:28:05,716] Trial 127 finished with value: 0.24203398749954086 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 15, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 32, 'learning_rate': 0.0035935013906947793, 'weight_decay': 6.762200792445223e-05, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.99853086801578, 'early_stopping_min_delta': 0.0009544724775244834}. Best is trial 32 with value: 0.2908549754956826.

  Epoch 023 - train 0.66938 | val 0.69270
  Classification -> best τ=0.405 (val F1=0.3518)
  Directional -> Accuracy: 0.5323, MCC: 0.0668, F1: 0.5397

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.24203398749954086
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 15
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.64920 | val 0.69804
  Epoch 018 - train 0.62833 | val 0.71394
  Classification -> best τ=0.685 (val F1=0.2931)
  Directional -> Accuracy: 0.5195, MCC: -0.0423, F1: 0.1778

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.63705 | val 0.73294
  Epoch 013 - train 0.63414 | val 0.77813
  Classification -> best τ=0.510 (val F1=0.1761)
  Directional -> Accuracy: 0.5870, MCC: 0.1313, F1: 0.6780

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 16). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.69285 | val 0.78358
  Epoch 012 - train 0.67174 | val 0.76952
  Classification -> best τ=0.555 (val F1=0.1803)
  Directional -> Accuracy: 0.4583, MCC: -0.1080, F1: 0.5357

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.64779 | val 1.18864
  Epoch 011 - train 0.68927 | val 0.92792
  Classification -> best τ=0.430 (val F1=0.1864)
  Directional -> Accuracy: 0.4667, MCC: 0.0286, F1: 0.1304

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.59758 | val 0.80536
  Epoch 014 - train 0.70849 | val 1.50582
  Classification -> best τ=0.570 (val F1=0.4105)
  Directional -> Accuracy: 0.6154, MCC: 0.3010, F1: 0.5238

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.61047 | val 1.00076
  Epoch 012 - train 0.58079 | val 0.85382
  Classification -> best τ=0.440 (val F1=0.2134)
  Directional -> Accuracy: 0.4792, MCC: -0.0449, F1: 0.3590

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.69053 | val 0.71155
  Epoch 014 - train 0.68452 | val 0.83806
  Classification -> best τ=0.485 (val F1=0.2054)
  Directional -> Accuracy: 0.4143, MCC: 0.0000, F1: 0.5591

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 16). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.59261 | val 1.27097
  Epoch 011 - train 0.63732 | val 1.34484
  Classification -> best τ=0.590 (val F1=0.0279)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.66211 | val 1.23339
  Epoch 011 - train 0.62790 | val 1.53812
  Classification -> best τ=0.505 (val F1=0.0195)
  Directional -> Accuracy: 0.6341, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 16). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 16). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.63928 | val 0.89910
  Epoch 013 - train 0.62416 | val 1.25491
  Classification -> best τ=0.420 (val F1=0.1283)
  Directional -> Accuracy: 0.4507, MCC: 0.1052, F1: 0.6139

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.62541 | val 1.03976
  Epoch 014 - train 0.64582 | val 1.70153
  Classification -> best τ=0.430 (val F1=0.1835)
  Directional -> Accuracy: 0.5294, MCC: 0.0254, F1: 0.2500

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.64361 | val 0.72623
  Epoch 015 - train 0.63027 | val 0.93697
  Classification -> best τ=0.475 (val F1=0.2608)
  Directional -> Accuracy: 0.5085, MCC: 0.0000, F1: 0.6742

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.63115 | val 1.24499
  Epoch 013 - train 0.64741 | val 1.13350
  Classification -> best τ=0.600 (val F1=0.1711)
  Directional -> Accuracy: 0.5581, MCC: 0.0375, F1: 0.1739

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.64793 | val 1.06102
  Epoch 018 - train 0.61695 | val 1.04249
  Classification -> best τ=0.300 (val F1=0.2906)
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.63953 | val 1.70794
  Epoch 015 - train 0.59967 | val 3.30566
  Classification -> best τ=0.540 (val F1=0.2981)
  Directional -> Accuracy: 0.5283, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.61168 | val 0.83517
  Epoch 011 - train 0.64743 | val 0.89772
  Classification -> best τ=0.515 (val F1=0.2605)
  Directional -> Accuracy: 0.5714, MCC: 0.1869, F1: 0.7170

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.66124 | val 1.01817
  Epoch 013 - train 0.62671 | val 0.94452
  Classification -> best τ=0.745 (val F1=0.2219)
  Directional -> Accuracy: 0.3833, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.67154 | val 1.29781
  Epoch 012 - train 0.67491 | val 1.32019
  Classification -> best τ=0.490 (val F1=0.1610)
  Directional -> Accuracy: 0.5789, MCC: 0.1852, F1: 0.6000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.62295 | val 0.82834
  Epoch 017 - train 0.60048 | val 0.87754
  Classification -> best τ=0.335 (val F1=0.2778)
  Directional -> Accuracy: 0.4091, MCC: -0.0327, F1: 0.0488

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 16). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.63199 | val 0.73285
  Epoch 013 - train 0.62053 | val 0.70789
  Classification -> best τ=0.635 (val F1=0.2689)
  Directional -> Accuracy: 0.4605, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.62242 | val 1.47027
  Epoch 012 - train 0.60999 | val 1.19259
  Classification -> best τ=0.440 (val F1=0.1290)
  Directional -> Accuracy: 0.3750, MCC: -0.1491, F1: 0.2857

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.62305 | val 2.15789
  Epoch 011 - train 0.62300 | val 1.87676
  Classification -> best τ=0.660 (val F1=0.1833)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.64724 | val 0.77725
  Epoch 012 - train 0.62358 | val 1.38848
  Classification -> best τ=0.535 (val F1=0.3185)
  Directional -> Accuracy: 0.5000, MCC: 0.0048, F1: 0.5246

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.66459 | val 2.87380
  Epoch 013 - train 0.63655 | val 2.39427
  Classification -> best τ=0.280 (val F1=0.2678)
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.60117 | val 0.84375
  Epoch 013 - train 0.64425 | val 0.95191
  Classification -> best τ=0.470 (val F1=0.2699)
  Directional -> Accuracy: 0.6429, MCC: 0.2837, F1: 0.6667

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.61513 | val 0.70212
  Epoch 018 - train 0.55064 | val 0.74225
  Classification -> best τ=0.325 (val F1=0.2979)
  Directional -> Accuracy: 0.6809, MCC: 0.4665, F1: 0.7170

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.68114 | val 0.77137
  Epoch 016 - train 0.63428 | val 1.06376
  Classification -> best τ=0.665 (val F1=0.0696)
  Directional -> Accuracy: 0.5581, MCC: 0.1872, F1: 0.5128

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.63995 | val 0.93278
  Epoch 011 - train 0.63444 | val 0.91104
  Classification -> best τ=0.475 (val F1=0.1545)
  Directional -> Accuracy: 0.4828, MCC: -0.1595, F1: 0.6341

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.65761 | val 0.71383
  Epoch 020 - train 0.65440 | val 1.15362
  Epoch 029 - train 0.62807 | val 0.80425
  Classification -> best τ=0.415 (val F1=0.3203)
  Directional -> Accuracy: 0.5714, MCC: 0.1158, F1: 0.6538

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.68884 | val 0.89423
  Epoch 015 - train 0.59317 | val 1.40539
  Classification -> best τ=0.680 (val F1=0.1869)
  Directional -> Accuracy: 0.4773, MCC: -0.0525, F1: 0.3030

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.68875 | val 0.72976
  Epoch 013 - train 0.66246 | val 0.77662
  Classification -> best τ=0.550 (val F1=0.2212)
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.62408 | val 0.91366
  Epoch 012 - train 0.62102 | val 0.84347
  Classification -> best τ=0.415 (val F1=0.2659)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.63094 | val 1.03810
  Epoch 016 - train 0.58626 | val 2.32973
  Classification -> best τ=0.640 (val F1=0.2739)
  Directional -> Accuracy: 0.4324, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.56884 | val 0.73375
  Epoch 011 - train 0.65231 | val 0.73417
  Classification -> best τ=0.425 (val F1=0.3395)
  Directional -> Accuracy: 0.5789, MCC: 0.1857, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.68672 | val 0.90812
  Epoch 011 - train 0.65682 | val 0.92811
  Classification -> best τ=0.595 (val F1=0.2306)
  Directional -> Accuracy: 0.5333, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.63019 | val 0.74635
  Epoch 015 - train 0.63973 | val 0.80585
  Classification -> best τ=0.305 (val F1=0.3954)
  Directional -> Accuracy: 0.6119, MCC: 0.2164, F1: 0.6486

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.68216 | val 0.86762
  Epoch 012 - train 0.68543 | val 0.75823
  Classification -> best τ=0.530 (val F1=0.3337)
  Directional -> Accuracy: 0.4651, MCC: -0.0977, F1: 0.0800

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.62745 | val 0.79639
  Epoch 015 - train 0.62292 | val 0.83228
  Classification -> best τ=0.520 (val F1=0.1920)
  Directional -> Accuracy: 0.5439, MCC: 0.1085, F1: 0.5938

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.60897 | val 1.23540
  Epoch 011 - train 0.63021 | val 1.12465
  Classification -> best τ=0.450 (val F1=0.2718)
  Directional -> Accuracy: 0.6383, MCC: 0.1871, F1: 0.7733

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 16). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.54624 | val 1.36285
  Epoch 012 - train 0.63057 | val 1.69625
  Classification -> best τ=0.395 (val F1=0.4667)
  Directional -> Accuracy: 0.3750, MCC: 0.1175, F1: 0.5283

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.66128 | val 0.77312
  Epoch 012 - train 0.60452 | val 0.75209
  Classification -> best τ=0.490 (val F1=0.3895)
  Directional -> Accuracy: 0.4872, MCC: -0.0160, F1: 0.4737

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 16). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.64220 | val 0.72416
  Epoch 019 - train 0.64592 | val 0.98509
  Classification -> best τ=0.475 (val F1=0.3187)
  Directional -> Accuracy: 0.5395, MCC: 0.2027, F1: 0.6847

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.68545 | val 0.70501
  Epoch 018 - train 0.62334 | val 1.78151
  Classification -> best τ=0.430 (val F1=0.4633)
  Directional -> Accuracy: 0.5106, MCC: 0.0045, F1: 0.6667

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.65729 | val 0.87444
  Epoch 012 - train 0.58028 | val 1.06150
  Classification -> best τ=0.465 (val F1=0.4183)
  Directional -> Accuracy: 0.5556, MCC: 0.0913, F1: 0.6154

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.61958 | val 0.74343
  Epoch 012 - train 0.64292 | val 0.84777
  Classification -> best τ=0.610 (val F1=0.4229)
  Directional -> Accuracy: 0.6500, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.65006 | val 1.02353
  Epoch 011 - train 0.67447 | val 1.38499
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5439, MCC: 0.0000, F1: 0.7045

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.65289 | val 2.44990
  Epoch 013 - train 0.62465 | val 1.93516
  Classification -> best τ=0.435 (val F1=0.2530)
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.62363 | val 1.62978
  Epoch 014 - train 0.63131 | val 2.28435
  Classification -> best τ=0.425 (val F1=0.2786)
  Directional -> Accuracy: 0.4630, MCC: -0.2337, F1: 0.6329

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.68053 | val 1.74381
  Epoch 012 - train 0.60957 | val 1.59014
  Classification -> best τ=0.470 (val F1=0.2079)
  Directional -> Accuracy: 0.5263, MCC: 0.0827, F1: 0.6747

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.64726 | val 0.87043
  Epoch 011 - train 0.64579 | val 0.79974

[I 2026-02-25 01:29:51,478] Trial 128 finished with value: 0.24686317127742985 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 15, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 0.006391136056033312, 'weight_decay': 3.065762284960212e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.4613308505076306, 'early_stopping_min_delta': 0.0005348322376040123}. Best is trial 32 with value: 0.2908549754956826.

  Classification -> best τ=0.490 (val F1=0.1677)
  Directional -> Accuracy: 0.5161, MCC: 0.0059, F1: 0.0625

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.24686317127742985
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 15
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.71081 | val 0.81113
  Epoch 013 - train 0.68638 | val 1.16382
  Classification -> best τ=0.590 (val F1=0.3210)
  Directional -> Accuracy: 0.5065, MCC: -0.0886, F1: 0.1364

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.60375 | val 1.06712
  Epoch 012 - train 0.65194 | val 1.36143
  Classification -> best τ=0.415 (val F1=0.1962)
  Directional -> Accuracy: 0.6087, MCC: 0.1962, F1: 0.7353

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 16). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.75437 | val 0.93985
  Epoch 011 - train 0.64748 | val 1.53505
  Classification -> best τ=0.495 (val F1=0.2892)
  Directional -> Accuracy: 0.4583, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.70385 | val 0.76357
  Epoch 014 - train 0.72127 | val 0.71507
  Classification -> best τ=0.730 (val F1=0.2518)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.63028 | val 0.83534
  Epoch 011 - train 0.65698 | val 0.74117
  Classification -> best τ=0.400 (val F1=0.3961)
  Directional -> Accuracy: 0.6154, MCC: 0.2183, F1: 0.6774

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.62613 | val 0.96100
  Epoch 013 - train 0.66933 | val 3.31757
  Classification -> best τ=0.575 (val F1=0.2667)
  Directional -> Accuracy: 0.5417, MCC: 0.0962, F1: 0.3889

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.72014 | val 1.89732
  Epoch 012 - train 0.74273 | val 1.17741
  Classification -> best τ=0.465 (val F1=0.3032)
  Directional -> Accuracy: 0.5571, MCC: 0.1166, F1: 0.5079

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 16). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.56554 | val 6.25032
  Epoch 012 - train 0.69401 | val 5.83429
  Classification -> best τ=0.705 (val F1=0.2548)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.70347 | val 0.74839
  Epoch 018 - train 0.73633 | val 0.70054
  Classification -> best τ=0.500 (val F1=0.4273)
  Directional -> Accuracy: 0.4146, MCC: -0.0679, F1: 0.4545

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 16). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 16). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.65745 | val 2.20248
  Epoch 011 - train 0.71769 | val 1.25655
  Classification -> best τ=0.230 (val F1=0.2479)
  Directional -> Accuracy: 0.4789, MCC: 0.1849, F1: 0.6263

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.70992 | val 1.29869
  Epoch 014 - train 0.71759 | val 1.17949
  Classification -> best τ=0.770 (val F1=0.2622)
  Directional -> Accuracy: 0.5294, MCC: 0.0172, F1: 0.1429

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.64119 | val 0.80304
  Epoch 020 - train 0.68506 | val 0.67426
  Epoch 030 - train 0.66969 | val 0.86255
  Classification -> best τ=0.600 (val F1=0.2343)
  Directional -> Accuracy: 0.6441, MCC: 0.2901, F1: 0.6769

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.67261 | val 2.02570
  Epoch 011 - train 0.69202 | val 1.91207
  Classification -> best τ=0.585 (val F1=0.2091)
  Directional -> Accuracy: 0.6047, MCC: 0.1753, F1: 0.4138

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.68660 | val 0.65147
  Epoch 013 - train 0.71267 | val 0.70018
  Classification -> best τ=0.445 (val F1=0.3322)
  Directional -> Accuracy: 0.6230, MCC: 0.2662, F1: 0.6933

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.71784 | val 3.61573
  Epoch 013 - train 0.67022 | val 2.08705
  Classification -> best τ=0.605 (val F1=0.3795)
  Directional -> Accuracy: 0.5472, MCC: 0.1274, F1: 0.6129

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.71314 | val 1.64711
  Epoch 011 - train 0.71173 | val 1.23413
  Classification -> best τ=0.540 (val F1=0.2427)
  Directional -> Accuracy: 0.5286, MCC: 0.0432, F1: 0.5823

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.76632 | val 0.92190
  Epoch 020 - train 0.71176 | val 1.11512
  Epoch 021 - train 0.69208 | val 1.25479
  Classification -> best τ=0.765 (val F1=0.2219)
  Directional -> Accuracy: 0.3833, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.70427 | val 0.70626
  Epoch 020 - train 0.66144 | val 0.89358
  Epoch 023 - train 0.68519 | val 0.69721
  Classification -> best τ=0.540 (val F1=0.0678)
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.71306 | val 1.76438
  Epoch 018 - train 0.66915 | val 1.01671
  Classification -> best τ=0.545 (val F1=0.3068)
  Directional -> Accuracy: 0.4394, MCC: 0.0487, F1: 0.1778

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 16). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.67897 | val 1.31728
  Epoch 011 - train 0.66332 | val 0.99132
  Classification -> best τ=0.180 (val F1=0.1923)
  Directional -> Accuracy: 0.5395, MCC: 0.0000, F1: 0.7009

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.67163 | val 1.73882
  Epoch 011 - train 0.64218 | val 1.43268
  Classification -> best τ=0.260 (val F1=0.3361)
  Directional -> Accuracy: 0.4583, MCC: 0.1155, F1: 0.3158

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.72090 | val 0.94149
  Epoch 012 - train 0.74335 | val 3.01755
  Classification -> best τ=0.310 (val F1=0.1677)
  Directional -> Accuracy: 0.6364, MCC: 0.2732, F1: 0.6471

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.67703 | val 0.81089
  Epoch 020 - train 0.67858 | val 1.01872
  Classification -> best τ=0.680 (val F1=0.2966)
  Directional -> Accuracy: 0.5172, MCC: 0.0762, F1: 0.4815

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.67916 | val 2.18256
  Epoch 011 - train 0.73952 | val 2.92984
  Classification -> best τ=0.455 (val F1=0.2448)
  Directional -> Accuracy: 0.4394, MCC: -0.1058, F1: 0.5542

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.67591 | val 0.82119
  Epoch 013 - train 0.68005 | val 0.90358
  Classification -> best τ=0.510 (val F1=0.4442)
  Directional -> Accuracy: 0.5357, MCC: 0.1728, F1: 0.3810

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.59146 | val 3.43719
  Epoch 011 - train 0.57737 | val 4.27869
  Classification -> best τ=0.360 (val F1=0.2067)
  Directional -> Accuracy: 0.5532, MCC: -0.1269, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.69472 | val 0.74424
  Epoch 015 - train 0.70568 | val 0.69174
  Classification -> best τ=0.595 (val F1=0.3227)
  Directional -> Accuracy: 0.5349, MCC: -0.1874, F1: 0.6970

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.74629 | val 0.70650
  Epoch 020 - train 0.68741 | val 0.73362
  Epoch 028 - train 0.67242 | val 1.19985
  Classification -> best τ=0.355 (val F1=0.2785)
  Directional -> Accuracy: 0.5862, MCC: 0.1421, F1: 0.7073

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.68699 | val 0.73910
  Epoch 011 - train 0.68714 | val 0.68004
  Classification -> best τ=0.515 (val F1=0.5204)
  Directional -> Accuracy: 0.6190, MCC: 0.2353, F1: 0.7241

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.61707 | val 2.23329
  Epoch 012 - train 0.65868 | val 2.36060
  Classification -> best τ=0.870 (val F1=0.1869)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.3889

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.70317 | val 1.52169
  Epoch 015 - train 0.66224 | val 1.41868
  Classification -> best τ=0.430 (val F1=0.2089)
  Directional -> Accuracy: 0.5000, MCC: -0.0753, F1: 0.6333

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.67100 | val 1.02680
  Epoch 011 - train 0.66674 | val 0.87599
  Classification -> best τ=0.285 (val F1=0.2369)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.72436 | val 0.85363
  Epoch 015 - train 0.69532 | val 1.92710
  Classification -> best τ=0.300 (val F1=0.3259)
  Directional -> Accuracy: 0.5676, MCC: 0.1652, F1: 0.5556

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.71323 | val 0.94380
  Epoch 013 - train 0.69267 | val 1.24418
  Classification -> best τ=0.475 (val F1=0.5017)
  Directional -> Accuracy: 0.5526, MCC: 0.1443, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.71866 | val 1.06130
  Epoch 016 - train 0.66929 | val 1.32172
  Classification -> best τ=0.565 (val F1=0.2182)
  Directional -> Accuracy: 0.5333, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.67262 | val 0.75206
  Epoch 020 - train 0.67846 | val 1.15519
  Epoch 023 - train 0.69640 | val 1.40472
  Classification -> best τ=0.050 (val F1=0.3431)
  Directional -> Accuracy: 0.5522, MCC: 0.0444, F1: 0.6591

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.77385 | val 0.69972
  Epoch 011 - train 0.72050 | val 0.95444
  Classification -> best τ=0.415 (val F1=0.3038)
  Directional -> Accuracy: 0.6279, MCC: 0.3176, F1: 0.5000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.66398 | val 0.75159
  Epoch 020 - train 0.64403 | val 0.86318
  Epoch 027 - train 0.85418 | val 1.28775
  Classification -> best τ=0.575 (val F1=0.2222)
  Directional -> Accuracy: 0.5263, MCC: 0.0387, F1: 0.4255

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.65397 | val 0.99499
  Epoch 012 - train 0.70547 | val 1.29914
  Classification -> best τ=0.240 (val F1=0.1661)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 16). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.66904 | val 0.75386
  Epoch 019 - train 0.57720 | val 1.89475
  Classification -> best τ=0.385 (val F1=0.4229)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.61807 | val 1.30383
  Epoch 014 - train 0.68504 | val 1.15462
  Classification -> best τ=0.360 (val F1=0.2707)
  Directional -> Accuracy: 0.5385, MCC: 0.0179, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 16). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.71619 | val 2.11656
  Epoch 013 - train 0.66541 | val 2.72153
  Classification -> best τ=0.480 (val F1=0.2585)
  Directional -> Accuracy: 0.5132, MCC: 0.0531, F1: 0.6606

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.69393 | val 1.24437
  Epoch 013 - train 0.66247 | val 0.81532
  Classification -> best τ=0.545 (val F1=0.2858)
  Directional -> Accuracy: 0.5106, MCC: 0.0139, F1: 0.5965

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.58123 | val 1.87482
  Epoch 011 - train 0.62136 | val 2.05318
  Classification -> best τ=0.270 (val F1=0.1387)
  Directional -> Accuracy: 0.4889, MCC: -0.1739, F1: 0.6462

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.74369 | val 0.76867
  Epoch 011 - train 0.64416 | val 0.78428
  Classification -> best τ=0.765 (val F1=0.3968)
  Directional -> Accuracy: 0.6000, MCC: 0.2097, F1: 0.5294

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.70169 | val 2.36533
  Epoch 011 - train 0.73822 | val 1.83134
  Classification -> best τ=0.490 (val F1=0.2805)
  Directional -> Accuracy: 0.4737, MCC: -0.0307, F1: 0.4231

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.64865 | val 1.84881
  Epoch 015 - train 0.65079 | val 3.55798
  Classification -> best τ=0.685 (val F1=0.3426)
  Directional -> Accuracy: 0.5088, MCC: 0.1809, F1: 0.6585

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.77638 | val 0.78378
  Epoch 020 - train 0.68938 | val 0.72893
  Epoch 030 - train 0.68706 | val 0.73352
  Classification -> best τ=0.650 (val F1=0.1647)
  Directional -> Accuracy: 0.6111, MCC: 0.2257, F1: 0.6038

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.68793 | val 1.38627
  Epoch 016 - train 0.64737 | val 1.58403
  Classification -> best τ=0.265 (val F1=0.2875)
  Directional -> Accuracy: 0.4386, MCC: -0.1265, F1: 0.3043

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.70687 | val 0.69422
  Epoch 020 - train 0.66985 | val 0.69004

[I 2026-02-25 01:32:13,415] Trial 129 finished with value: 0.28220767753188175 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 15, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.1, 'dropout': 0.8, 'batch_size': 16, 'learning_rate': 0.008055766617001062, 'weight_decay': 2.2252551834723357e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.5064041134088517, 'early_stopping_min_delta': 4.9322504247221506e-06}. Best is trial 32 with value: 0.2908549754956826.

  Epoch 022 - train 0.66854 | val 0.67663
  Classification -> best τ=0.260 (val F1=0.3271)
  Directional -> Accuracy: 0.5161, MCC: 0.0356, F1: 0.5312

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.28220767753188175
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 15
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.68197 | val 0.82278
  Epoch 017 - train 0.61217 | val 0.77109
  Classification -> best τ=0.530 (val F1=0.3044)
  Directional -> Accuracy: 0.4935, MCC: -0.1399, F1: 0.0930

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.61302 | val 1.16156
  Epoch 019 - train 0.60023 | val 1.50565
  Classification -> best τ=0.395 (val F1=0.1870)
  Directional -> Accuracy: 0.5870, MCC: 0.1700, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 16). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.66605 | val 0.73402
  Epoch 020 - train 0.58495 | val 0.79945
  Epoch 023 - train 0.56173 | val 0.92682
  Classification -> best τ=0.575 (val F1=0.3123)
  Directional -> Accuracy: 0.5000, MCC: 0.1918, F1: 0.1429

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.65829 | val 1.35599
  Epoch 016 - train 0.64433 | val 1.54982
  Classification -> best τ=0.375 (val F1=0.2485)
  Directional -> Accuracy: 0.4667, MCC: 0.1059, F1: 0.0476

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.58645 | val 1.69556
  Epoch 016 - train 0.53776 | val 1.75821
  Classification -> best τ=0.425 (val F1=0.3219)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.7000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.64641 | val 1.12875
  Epoch 018 - train 0.53591 | val 2.36794
  Classification -> best τ=0.520 (val F1=0.3242)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.70513 | val 0.70618
  Epoch 020 - train 0.61134 | val 0.93989
  Epoch 024 - train 0.57185 | val 0.90245
  Classification -> best τ=0.495 (val F1=0.3266)
  Directional -> Accuracy: 0.4714, MCC: 0.1750, F1: 0.5934

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 16). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.55390 | val 2.29179
  Epoch 016 - train 0.51919 | val 2.82914
  Classification -> best τ=0.550 (val F1=0.1517)
  Directional -> Accuracy: 0.4222, MCC: -0.0340, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.56569 | val 1.68116
  Epoch 018 - train 0.52844 | val 2.46189
  Classification -> best τ=0.495 (val F1=0.4744)
  Directional -> Accuracy: 0.4390, MCC: 0.2134, F1: 0.5660

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 16). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 16). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.65053 | val 0.78890
  Epoch 016 - train 0.58116 | val 0.90300
  Classification -> best τ=0.635 (val F1=0.1371)
  Directional -> Accuracy: 0.5775, MCC: 0.0899, F1: 0.2105

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.61773 | val 1.29667
  Epoch 020 - train 0.57805 | val 1.79933
  Epoch 021 - train 0.55589 | val 1.22823
  Classification -> best τ=0.415 (val F1=0.2278)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.64669 | val 0.73488
  Epoch 018 - train 0.55614 | val 0.90159
  Classification -> best τ=0.460 (val F1=0.1680)
  Directional -> Accuracy: 0.6271, MCC: 0.2569, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.58734 | val 1.36660
  Epoch 019 - train 0.59238 | val 1.49878
  Classification -> best τ=0.365 (val F1=0.2004)
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.65568 | val 0.64619
  Epoch 020 - train 0.61700 | val 0.78258
  Classification -> best τ=0.320 (val F1=0.2825)
  Directional -> Accuracy: 0.5574, MCC: 0.1455, F1: 0.6747

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.60379 | val 3.09051
  Epoch 016 - train 0.52902 | val 4.49592
  Classification -> best τ=0.485 (val F1=0.1734)
  Directional -> Accuracy: 0.4717, MCC: 0.0000, F1: 0.6410

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.58482 | val 0.89099
  Epoch 016 - train 0.57714 | val 0.73897
  Classification -> best τ=0.485 (val F1=0.2172)
  Directional -> Accuracy: 0.6143, MCC: 0.2677, F1: 0.7327

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.65274 | val 1.21482
  Epoch 016 - train 0.60859 | val 0.99004
  Classification -> best τ=0.660 (val F1=0.1259)
  Directional -> Accuracy: 0.3833, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.64498 | val 1.56890
  Epoch 020 - train 0.60192 | val 1.88152
  Classification -> best τ=0.420 (val F1=0.2290)
  Directional -> Accuracy: 0.5526, MCC: 0.1192, F1: 0.5854

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.63641 | val 1.07595
  Epoch 018 - train 0.59278 | val 1.71099
  Classification -> best τ=0.525 (val F1=0.2712)
  Directional -> Accuracy: 0.4394, MCC: 0.0822, F1: 0.1395

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 16). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.65477 | val 0.78294
  Epoch 018 - train 0.58117 | val 0.95992
  Classification -> best τ=0.615 (val F1=0.3086)
  Directional -> Accuracy: 0.4737, MCC: 0.1067, F1: 0.0476

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.61145 | val 0.85085
  Epoch 017 - train 0.58175 | val 1.06878
  Classification -> best τ=0.395 (val F1=0.2692)
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.63629 | val 1.44047
  Epoch 016 - train 0.59321 | val 1.72637
  Classification -> best τ=0.465 (val F1=0.1677)
  Directional -> Accuracy: 0.5303, MCC: 0.0680, F1: 0.6173

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.68147 | val 1.07301
  Epoch 017 - train 0.59327 | val 1.37629
  Classification -> best τ=0.575 (val F1=0.2654)
  Directional -> Accuracy: 0.5345, MCC: 0.0182, F1: 0.6301

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.66232 | val 1.83261
  Epoch 016 - train 0.62496 | val 2.59697
  Classification -> best τ=0.375 (val F1=0.2791)
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.64069 | val 0.70880
  Epoch 020 - train 0.55610 | val 0.85321
  Classification -> best τ=0.615 (val F1=0.4863)
  Directional -> Accuracy: 0.5714, MCC: 0.2385, F1: 0.4545

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.61729 | val 0.80495
  Epoch 017 - train 0.51843 | val 1.46950
  Classification -> best τ=0.445 (val F1=0.2067)
  Directional -> Accuracy: 0.4468, MCC: 0.1269, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.66909 | val 0.90899
  Epoch 020 - train 0.59836 | val 1.99824
  Classification -> best τ=0.355 (val F1=0.3227)
  Directional -> Accuracy: 0.5581, MCC: -0.1309, F1: 0.7164

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.62265 | val 0.73318
  Epoch 016 - train 0.58406 | val 0.82262
  Classification -> best τ=0.410 (val F1=0.1867)
  Directional -> Accuracy: 0.5517, MCC: 0.2279, F1: 0.3810

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.65639 | val 0.85228
  Epoch 020 - train 0.53706 | val 1.02671
  Classification -> best τ=0.510 (val F1=0.4423)
  Directional -> Accuracy: 0.4286, MCC: -0.2150, F1: 0.5556

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.62588 | val 1.51077
  Epoch 017 - train 0.50743 | val 2.73994
  Classification -> best τ=0.705 (val F1=0.1869)
  Directional -> Accuracy: 0.5227, MCC: 0.0479, F1: 0.4324

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.67165 | val 0.68869
  Epoch 018 - train 0.57154 | val 0.76215
  Classification -> best τ=0.600 (val F1=0.3236)
  Directional -> Accuracy: 0.5227, MCC: -0.1392, F1: 0.6866

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.61435 | val 0.99693
  Epoch 016 - train 0.56394 | val 0.79010
  Classification -> best τ=0.490 (val F1=0.2964)
  Directional -> Accuracy: 0.5294, MCC: 0.1007, F1: 0.4000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.61866 | val 1.90617
  Epoch 016 - train 0.55598 | val 3.85844
  Classification -> best τ=0.375 (val F1=0.3259)
  Directional -> Accuracy: 0.5676, MCC: 0.1562, F1: 0.5676

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.56769 | val 0.80262
  Epoch 020 - train 0.59572 | val 1.01882
  Epoch 023 - train 0.52814 | val 1.05353
  Classification -> best τ=0.445 (val F1=0.3708)
  Directional -> Accuracy: 0.4737, MCC: -0.0976, F1: 0.6296

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.69580 | val 1.17978
  Epoch 017 - train 0.58030 | val 1.72587
  Classification -> best τ=0.630 (val F1=0.2857)
  Directional -> Accuracy: 0.5333, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.62790 | val 0.80147
  Epoch 019 - train 0.59773 | val 1.08317
  Classification -> best τ=0.260 (val F1=0.3521)
  Directional -> Accuracy: 0.4776, MCC: 0.1335, F1: 0.1860

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.67653 | val 0.75365
  Epoch 017 - train 0.63217 | val 0.71118
  Classification -> best τ=0.510 (val F1=0.3200)
  Directional -> Accuracy: 0.5581, MCC: 0.1788, F1: 0.3448

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.65089 | val 0.83951
  Epoch 020 - train 0.54226 | val 0.97108
  Epoch 022 - train 0.54695 | val 0.79367
  Classification -> best τ=0.355 (val F1=0.2668)
  Directional -> Accuracy: 0.4912, MCC: -0.0148, F1: 0.4912

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.60275 | val 0.80087
  Epoch 019 - train 0.55449 | val 0.87701
  Classification -> best τ=0.340 (val F1=0.2722)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 16). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.52577 | val 2.08609
  Epoch 020 - train 0.49112 | val 2.53457
  Classification -> best τ=0.455 (val F1=0.3410)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.59334 | val 0.80255
  Epoch 016 - train 0.67760 | val 0.89813
  Classification -> best τ=0.560 (val F1=0.0406)
  Directional -> Accuracy: 0.5128, MCC: 0.2152, F1: 0.1739

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 16). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.64262 | val 1.02032
  Epoch 017 - train 0.59859 | val 1.86447
  Classification -> best τ=0.360 (val F1=0.3724)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.67672 | val 1.19061
  Epoch 016 - train 0.61917 | val 0.91533
  Classification -> best τ=0.535 (val F1=0.2709)
  Directional -> Accuracy: 0.4894, MCC: -0.0081, F1: 0.2000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.59196 | val 1.23324
  Epoch 020 - train 0.48975 | val 1.64525
  Classification -> best τ=0.575 (val F1=0.4000)
  Directional -> Accuracy: 0.4667, MCC: -0.0219, F1: 0.3684

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.66805 | val 0.77825
  Epoch 020 - train 0.59757 | val 0.74173
  Epoch 021 - train 0.56655 | val 0.79135
  Classification -> best τ=0.385 (val F1=0.3647)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.65982 | val 1.10674
  Epoch 018 - train 0.59922 | val 0.93704
  Classification -> best τ=0.375 (val F1=0.1978)
  Directional -> Accuracy: 0.4912, MCC: -0.0498, F1: 0.5797

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.61906 | val 1.40514
  Epoch 016 - train 0.57351 | val 2.68439
  Classification -> best τ=0.570 (val F1=0.4276)
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.64584 | val 1.87970
  Epoch 019 - train 0.60550 | val 2.60482
  Classification -> best τ=0.355 (val F1=0.1200)
  Directional -> Accuracy: 0.4630, MCC: -0.2337, F1: 0.6329

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.68019 | val 1.16887
  Epoch 017 - train 0.57662 | val 1.50128
  Classification -> best τ=0.465 (val F1=0.2374)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.66838 | val 0.83237

[I 2026-02-25 01:33:59,434] Trial 130 finished with value: 0.2733807403836669 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 15, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.1, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 0.0048749693426424915, 'weight_decay': 2.3224574453420166e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 0.6459492587425676, 'early_stopping_min_delta': 4.0351485775195995e-05}. Best is trial 32 with value: 0.2908549754956826.

  Epoch 018 - train 0.57977 | val 1.21573
  Classification -> best τ=0.470 (val F1=0.2782)
  Directional -> Accuracy: 0.5645, MCC: 0.1380, F1: 0.5970

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2733807403836669
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 15
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.69315 | val 0.69460
  Epoch 020 - train 0.65934 | val 1.01051
  Epoch 022 - train 0.66934 | val 0.88402
  Classification -> best τ=0.790 (val F1=0.2553)
  Directional -> Accuracy: 0.5065, MCC: -0.0633, F1: 0.2083

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.65036 | val 0.71891
  Epoch 016 - train 0.68549 | val 0.72802
  Classification -> best τ=0.485 (val F1=0.1962)
  Directional -> Accuracy: 0.5870, MCC: 0.1202, F1: 0.6984

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 16). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.69179 | val 0.89992
  Epoch 014 - train 0.77162 | val 0.98260
  Classification -> best τ=0.695 (val F1=0.2477)
  Directional -> Accuracy: 0.4583, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.72464 | val 0.99565
  Epoch 012 - train 0.68798 | val 2.65539
  Classification -> best τ=0.540 (val F1=0.2323)
  Directional -> Accuracy: 0.4800, MCC: 0.1507, F1: 0.0930

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.66457 | val 1.99125
  Epoch 011 - train 0.63616 | val 2.92174
  Classification -> best τ=0.400 (val F1=0.3469)
  Directional -> Accuracy: 0.3846, MCC: -0.2381, F1: 0.4286

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.65428 | val 1.08301
  Epoch 015 - train 0.64842 | val 2.71724
  Classification -> best τ=0.230 (val F1=0.2777)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6129

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.72390 | val 1.47685
  Epoch 013 - train 0.70566 | val 1.77171
  Classification -> best τ=0.745 (val F1=0.1963)
  Directional -> Accuracy: 0.5857, MCC: 0.1118, F1: 0.4314

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 16). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.64456 | val 4.25798
  Epoch 011 - train 0.55942 | val 5.32826
  Classification -> best τ=0.700 (val F1=0.3780)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.74150 | val 0.77527
  Epoch 014 - train 0.71431 | val 0.76816
  Classification -> best τ=0.575 (val F1=0.4767)
  Directional -> Accuracy: 0.4390, MCC: -0.1618, F1: 0.3030

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 16). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 16). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.66323 | val 2.26823
  Epoch 012 - train 0.64457 | val 3.17959
  Classification -> best τ=0.300 (val F1=0.1397)
  Directional -> Accuracy: 0.4507, MCC: -0.0155, F1: 0.5714

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.67197 | val 0.93471
  Epoch 011 - train 0.91214 | val 1.79378
  Classification -> best τ=0.715 (val F1=0.1782)
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.6400

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.64928 | val 0.82192
  Epoch 011 - train 0.70731 | val 0.99800
  Classification -> best τ=0.390 (val F1=0.2271)
  Directional -> Accuracy: 0.5085, MCC: 0.0000, F1: 0.6742

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.70886 | val 2.00415
  Epoch 012 - train 0.64474 | val 2.84173
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.72208 | val 0.62707
  Epoch 018 - train 0.71519 | val 0.65289
  Classification -> best τ=0.265 (val F1=0.2752)
  Directional -> Accuracy: 0.5410, MCC: 0.0958, F1: 0.6585

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.80485 | val 1.56264
  Epoch 020 - train 0.71095 | val 1.30335
  Epoch 023 - train 0.70967 | val 1.54811
  Classification -> best τ=0.590 (val F1=0.3137)
  Directional -> Accuracy: 0.4717, MCC: 0.0000, F1: 0.6410

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.68981 | val 1.45564
  Epoch 011 - train 0.68182 | val 1.73501
  Classification -> best τ=0.190 (val F1=0.2927)
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.70162 | val 0.84375
  Epoch 020 - train 0.75246 | val 1.56571
  Classification -> best τ=0.660 (val F1=0.2093)
  Directional -> Accuracy: 0.5833, MCC: -0.0343, F1: 0.7253

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.69779 | val 1.17943
  Epoch 011 - train 0.73474 | val 1.45492
  Classification -> best τ=0.295 (val F1=0.2153)
  Directional -> Accuracy: 0.5395, MCC: 0.2652, F1: 0.4262

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.72798 | val 1.12114
  Epoch 017 - train 0.69861 | val 1.12737
  Classification -> best τ=0.500 (val F1=0.3124)
  Directional -> Accuracy: 0.4697, MCC: 0.0938, F1: 0.2857

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 16). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.72943 | val 0.82237
  Epoch 014 - train 0.65920 | val 0.75763
  Classification -> best τ=0.575 (val F1=0.2332)
  Directional -> Accuracy: 0.4605, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.62888 | val 2.12598
  Epoch 011 - train 0.69172 | val 2.02489
  Classification -> best τ=0.340 (val F1=0.1521)
  Directional -> Accuracy: 0.5625, MCC: -0.0762, F1: 0.7042

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.72388 | val 2.08328
  Epoch 017 - train 0.66638 | val 2.28925
  Classification -> best τ=0.150 (val F1=0.1677)
  Directional -> Accuracy: 0.5303, MCC: 0.0928, F1: 0.6593

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.69387 | val 0.97676
  Epoch 018 - train 0.67118 | val 1.05562
  Classification -> best τ=0.750 (val F1=0.2773)
  Directional -> Accuracy: 0.4828, MCC: 0.0846, F1: 0.2857

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.79930 | val 1.83167
  Epoch 014 - train 0.69031 | val 1.22178
  Classification -> best τ=0.450 (val F1=0.2304)
  Directional -> Accuracy: 0.5000, MCC: -0.0055, F1: 0.4590

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.69565 | val 0.76451
  Epoch 015 - train 0.70086 | val 0.68616
  Classification -> best τ=0.575 (val F1=0.5125)
  Directional -> Accuracy: 0.5357, MCC: 0.1728, F1: 0.3810

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.58565 | val 1.13462
  Epoch 011 - train 0.54030 | val 3.18246
  Classification -> best τ=0.820 (val F1=0.3225)
  Directional -> Accuracy: 0.5532, MCC: -0.1269, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.74515 | val 0.76598
  Epoch 011 - train 0.65110 | val 0.96925
  Classification -> best τ=0.545 (val F1=0.2632)
  Directional -> Accuracy: 0.5581, MCC: 0.2126, F1: 0.4865

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.74401 | val 0.75602
  Epoch 012 - train 0.78995 | val 0.74360
  Classification -> best τ=0.435 (val F1=0.3196)
  Directional -> Accuracy: 0.4483, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.83527 | val 0.70418
  Epoch 015 - train 0.70576 | val 0.72520
  Classification -> best τ=0.445 (val F1=0.2125)
  Directional -> Accuracy: 0.4286, MCC: -0.3341, F1: 0.6000

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.64171 | val 1.41951
  Epoch 011 - train 0.60001 | val 1.45098
  Classification -> best τ=0.570 (val F1=0.0212)
  Directional -> Accuracy: 0.5227, MCC: 0.0455, F1: 0.5116

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.65495 | val 0.79258
  Epoch 011 - train 0.74117 | val 1.13409
  Classification -> best τ=0.785 (val F1=0.2595)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.75655 | val 0.86275
  Epoch 011 - train 0.69956 | val 0.80648
  Classification -> best τ=0.435 (val F1=0.3016)
  Directional -> Accuracy: 0.5098, MCC: -0.0687, F1: 0.6667

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.67369 | val 0.85191
  Epoch 012 - train 0.69151 | val 0.84257
  Classification -> best τ=0.325 (val F1=0.3351)
  Directional -> Accuracy: 0.5405, MCC: 0.1500, F1: 0.4688

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.71493 | val 1.22084
  Epoch 011 - train 0.67190 | val 1.43409
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.68699 | val 1.30090
  Epoch 019 - train 0.70824 | val 0.77513
  Classification -> best τ=0.470 (val F1=0.2922)
  Directional -> Accuracy: 0.6000, MCC: 0.2182, F1: 0.6250

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.68542 | val 1.82831
  Epoch 012 - train 0.72893 | val 0.91435
  Classification -> best τ=0.350 (val F1=0.3521)
  Directional -> Accuracy: 0.4627, MCC: 0.1532, F1: 0.1000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.67630 | val 0.68073
  Epoch 012 - train 0.65378 | val 1.17890
  Classification -> best τ=0.535 (val F1=0.2810)
  Directional -> Accuracy: 0.5814, MCC: 0.2280, F1: 0.4000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.67650 | val 1.11897
  Epoch 015 - train 0.67682 | val 1.56452
  Classification -> best τ=0.420 (val F1=0.2803)
  Directional -> Accuracy: 0.4561, MCC: -0.0820, F1: 0.4746

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.62685 | val 0.84861
  Epoch 017 - train 0.59586 | val 1.09183
  Classification -> best τ=0.420 (val F1=0.2718)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 16). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.69564 | val 0.86410
  Epoch 016 - train 0.69030 | val 0.72897
  Classification -> best τ=0.330 (val F1=0.3830)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.70399 | val 0.95611
  Epoch 012 - train 0.71859 | val 1.06013
  Classification -> best τ=0.530 (val F1=0.2431)
  Directional -> Accuracy: 0.4872, MCC: -0.0402, F1: 0.5455

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 16). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.72827 | val 0.86685
  Epoch 012 - train 0.76712 | val 0.77820
  Classification -> best τ=0.585 (val F1=0.1976)
  Directional -> Accuracy: 0.5263, MCC: 0.0976, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.72153 | val 0.76699
  Epoch 011 - train 0.75476 | val 0.74662
  Classification -> best τ=0.410 (val F1=0.3820)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.59885 | val 1.80055
  Epoch 014 - train 0.65181 | val 1.99078
  Classification -> best τ=0.255 (val F1=0.1387)
  Directional -> Accuracy: 0.5333, MCC: -0.1348, F1: 0.6957

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.62823 | val 1.14328
  Epoch 012 - train 0.64781 | val 0.72965
  Classification -> best τ=0.790 (val F1=0.4667)
  Directional -> Accuracy: 0.6500, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.75484 | val 0.67361
  Epoch 020 - train 0.73341 | val 0.79708
  Classification -> best τ=0.570 (val F1=0.0689)
  Directional -> Accuracy: 0.4386, MCC: -0.1315, F1: 0.4839

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.64160 | val 1.79885
  Epoch 011 - train 0.68901 | val 1.67248
  Classification -> best τ=0.905 (val F1=0.2750)
  Directional -> Accuracy: 0.5263, MCC: 0.1078, F1: 0.6301

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.72283 | val 1.71340
  Epoch 020 - train 0.73589 | val 0.76378
  Epoch 030 - train 0.68985 | val 0.94222
  Classification -> best τ=0.590 (val F1=0.2448)
  Directional -> Accuracy: 0.5556, MCC: 0.2035, F1: 0.7000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.71736 | val 0.69670
  Epoch 018 - train 0.64065 | val 0.74277
  Classification -> best τ=0.625 (val F1=0.2729)
  Directional -> Accuracy: 0.4912, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.69853 | val 0.86334
  Epoch 020 - train 0.71084 | val 0.69982

[I 2026-02-25 01:36:17,498] Trial 131 finished with value: 0.25573820707324957 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 15, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.1, 'dropout': 0.8, 'batch_size': 16, 'learning_rate': 0.008316863639990079, 'weight_decay': 1.9049968501414002e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.1231130433587384, 'early_stopping_min_delta': 0.0007901807238872671}. Best is trial 32 with value: 0.2908549754956826.

  Epoch 024 - train 0.68310 | val 0.86261
  Classification -> best τ=0.520 (val F1=0.2579)
  Directional -> Accuracy: 0.4355, MCC: -0.1291, F1: 0.4262

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.25573820707324957
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 15
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.69830 | val 0.85877
  Epoch 016 - train 0.68416 | val 0.70137
  Classification -> best τ=0.600 (val F1=0.2931)
  Directional -> Accuracy: 0.5195, MCC: -0.0246, F1: 0.2449

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.65214 | val 1.05229
  Epoch 011 - train 0.63644 | val 1.07349
  Classification -> best τ=0.505 (val F1=0.1383)
  Directional -> Accuracy: 0.4565, MCC: -0.0339, F1: 0.3590

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 16). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.70312 | val 1.01174
  Epoch 020 - train 0.74328 | val 0.83737
  Epoch 026 - train 0.68368 | val 0.72337
  Classification -> best τ=0.520 (val F1=0.3539)
  Directional -> Accuracy: 0.5208, MCC: 0.1431, F1: 0.3030

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.71015 | val 1.70402
  Epoch 020 - train 0.68492 | val 0.68733
  Epoch 029 - train 0.69024 | val 1.04605
  Classification -> best τ=0.535 (val F1=0.2386)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.67666 | val 0.77144
  Epoch 012 - train 0.63928 | val 1.48431
  Classification -> best τ=0.560 (val F1=0.3566)
  Directional -> Accuracy: 0.6731, MCC: 0.3387, F1: 0.7119

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.68176 | val 2.89010
  Epoch 013 - train 0.74310 | val 2.10488
  Classification -> best τ=0.495 (val F1=0.3693)
  Directional -> Accuracy: 0.7083, MCC: 0.4181, F1: 0.6957

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.69332 | val 1.54170
  Epoch 012 - train 0.71759 | val 0.76080
  Classification -> best τ=0.325 (val F1=0.2462)
  Directional -> Accuracy: 0.5429, MCC: 0.1179, F1: 0.5294

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 16). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.66118 | val 7.16853
  Epoch 011 - train 0.62020 | val 8.09217
  Classification -> best τ=0.780 (val F1=0.0198)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.68567 | val 0.77560
  Epoch 013 - train 0.76459 | val 0.73393
  Classification -> best τ=0.560 (val F1=0.4744)
  Directional -> Accuracy: 0.5610, MCC: 0.0538, F1: 0.4000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 16). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 16). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.66753 | val 2.20762
  Epoch 011 - train 0.63993 | val 2.23941
  Classification -> best τ=0.615 (val F1=0.1587)
  Directional -> Accuracy: 0.5493, MCC: -0.1052, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.75978 | val 1.00581
  Epoch 012 - train 0.70344 | val 1.61899
  Classification -> best τ=0.240 (val F1=0.1577)
  Directional -> Accuracy: 0.6078, MCC: 0.2654, F1: 0.3333

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.67209 | val 0.82539
  Epoch 014 - train 0.69319 | val 1.12455
  Classification -> best τ=0.490 (val F1=0.1919)
  Directional -> Accuracy: 0.5424, MCC: 0.1905, F1: 0.6897

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.65576 | val 1.52568
  Epoch 014 - train 0.69468 | val 1.35377
  Classification -> best τ=0.660 (val F1=0.2108)
  Directional -> Accuracy: 0.6512, MCC: 0.3174, F1: 0.4000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.76734 | val 0.65495
  Epoch 011 - train 0.71892 | val 0.66892
  Classification -> best τ=0.515 (val F1=0.2884)
  Directional -> Accuracy: 0.5738, MCC: 0.1810, F1: 0.4348

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.72475 | val 2.21298
  Epoch 013 - train 0.69429 | val 1.48238
  Classification -> best τ=0.635 (val F1=0.3562)
  Directional -> Accuracy: 0.6226, MCC: 0.2454, F1: 0.5000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.64079 | val 1.38938
  Epoch 011 - train 0.73238 | val 1.46598
  Classification -> best τ=0.350 (val F1=0.2927)
  Directional -> Accuracy: 0.5429, MCC: 0.0148, F1: 0.6981

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.72669 | val 0.97922
  Epoch 020 - train 0.68418 | val 0.95452
  Epoch 029 - train 0.69296 | val 1.11470
  Classification -> best τ=0.615 (val F1=0.2585)
  Directional -> Accuracy: 0.3833, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.69464 | val 0.70467
  Epoch 013 - train 0.78657 | val 0.70440
  Classification -> best τ=0.610 (val F1=0.1800)
  Directional -> Accuracy: 0.3947, MCC: -0.0354, F1: 0.0417

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.73961 | val 0.86365
  Epoch 011 - train 0.67819 | val 0.83436
  Classification -> best τ=0.560 (val F1=0.3091)
  Directional -> Accuracy: 0.4242, MCC: 0.0053, F1: 0.1364

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 16). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.69331 | val 0.91366
  Epoch 013 - train 0.71857 | val 1.28333
  Classification -> best τ=0.540 (val F1=0.2855)
  Directional -> Accuracy: 0.4868, MCC: 0.0747, F1: 0.1702

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.68550 | val 1.08939
  Epoch 017 - train 0.61434 | val 2.00923
  Classification -> best τ=0.100 (val F1=0.3143)
  Directional -> Accuracy: 0.5417, MCC: 0.2130, F1: 0.5000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.70068 | val 3.77323
  Epoch 012 - train 0.69388 | val 2.53738
  Classification -> best τ=0.825 (val F1=0.2264)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.69772 | val 1.27112
  Epoch 011 - train 0.73289 | val 0.82330
  Classification -> best τ=0.515 (val F1=0.3026)
  Directional -> Accuracy: 0.5862, MCC: 0.1485, F1: 0.6471

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.70838 | val 1.98194
  Epoch 011 - train 0.65576 | val 2.15122
  Classification -> best τ=0.370 (val F1=0.1878)
  Directional -> Accuracy: 0.5152, MCC: 0.0125, F1: 0.4074

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.69381 | val 0.62808
  Epoch 011 - train 0.67926 | val 0.72340
  Classification -> best τ=0.510 (val F1=0.4595)
  Directional -> Accuracy: 0.4821, MCC: 0.0114, F1: 0.3830

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.71853 | val 1.15944
  Epoch 014 - train 0.56659 | val 1.71130
  Classification -> best τ=0.525 (val F1=0.2582)
  Directional -> Accuracy: 0.5745, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.72039 | val 1.39634
  Epoch 020 - train 0.67658 | val 0.86458
  Epoch 028 - train 0.71588 | val 0.99094
  Classification -> best τ=0.595 (val F1=0.2717)
  Directional -> Accuracy: 0.5814, MCC: 0.1854, F1: 0.5909

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.71857 | val 0.76745
  Epoch 014 - train 0.83768 | val 0.75478
  Classification -> best τ=0.205 (val F1=0.3051)
  Directional -> Accuracy: 0.5000, MCC: 0.1533, F1: 0.2162

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.77798 | val 1.25222
  Epoch 012 - train 0.69544 | val 1.45951
  Classification -> best τ=0.485 (val F1=0.4543)
  Directional -> Accuracy: 0.5714, MCC: 0.1718, F1: 0.7188

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.65505 | val 1.62005
  Epoch 011 - train 0.68869 | val 1.76640
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.62838 | val 0.81765
  Epoch 013 - train 0.70141 | val 0.83049
  Classification -> best τ=0.820 (val F1=0.1778)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.67026 | val 1.06455
  Epoch 011 - train 0.63457 | val 1.04997
  Classification -> best τ=0.475 (val F1=0.3115)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.75206 | val 1.04566
  Epoch 013 - train 0.68995 | val 1.41625
  Classification -> best τ=0.565 (val F1=0.2693)
  Directional -> Accuracy: 0.4865, MCC: 0.1594, F1: 0.2083

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.78832 | val 1.02482
  Epoch 011 - train 0.75365 | val 0.77606
  Classification -> best τ=0.425 (val F1=0.3337)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.76090 | val 1.77569
  Epoch 012 - train 0.70134 | val 1.23435
  Classification -> best τ=0.720 (val F1=0.1890)
  Directional -> Accuracy: 0.6000, MCC: 0.2020, F1: 0.5909

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.79855 | val 0.82660
  Epoch 013 - train 0.68184 | val 1.25577
  Classification -> best τ=0.320 (val F1=0.3166)
  Directional -> Accuracy: 0.4925, MCC: 0.0157, F1: 0.4688

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.74901 | val 1.00871
  Epoch 015 - train 0.71895 | val 1.68376
  Classification -> best τ=0.330 (val F1=0.3180)
  Directional -> Accuracy: 0.6047, MCC: 0.2529, F1: 0.4848

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.68948 | val 1.07859
  Epoch 018 - train 0.66376 | val 0.71434
  Classification -> best τ=0.635 (val F1=0.2236)
  Directional -> Accuracy: 0.5439, MCC: 0.0820, F1: 0.5000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.69034 | val 1.02032
  Epoch 014 - train 0.68490 | val 0.79959
  Classification -> best τ=0.595 (val F1=0.3005)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 16). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.72082 | val 0.75155
  Epoch 013 - train 0.64226 | val 1.70553
  Classification -> best τ=0.435 (val F1=0.3333)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.72660 | val 1.07742
  Epoch 014 - train 0.59750 | val 1.56831
  Classification -> best τ=0.435 (val F1=0.1870)
  Directional -> Accuracy: 0.6154, MCC: 0.2254, F1: 0.7059

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 16). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.69516 | val 1.55466
  Epoch 020 - train 0.68984 | val 0.84791
  Epoch 021 - train 0.71859 | val 0.71533
  Classification -> best τ=0.290 (val F1=0.4940)
  Directional -> Accuracy: 0.5132, MCC: 0.1155, F1: 0.6726

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.64167 | val 0.79861
  Epoch 017 - train 0.66265 | val 0.79095
  Classification -> best τ=0.450 (val F1=0.2806)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.63907 | val 2.03136
  Epoch 011 - train 0.59249 | val 2.86442
  Classification -> best τ=0.555 (val F1=0.2097)
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.5769

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.70288 | val 0.72645
  Epoch 020 - train 0.61300 | val 0.97436
  Epoch 027 - train 0.58773 | val 1.54089
  Classification -> best τ=0.510 (val F1=0.3637)
  Directional -> Accuracy: 0.3500, MCC: -0.0721, F1: 0.5000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.74928 | val 0.88005
  Epoch 013 - train 0.83284 | val 1.38416
  Classification -> best τ=0.495 (val F1=0.2023)
  Directional -> Accuracy: 0.4737, MCC: -0.1273, F1: 0.6053

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.71949 | val 2.18157
  Epoch 011 - train 0.74083 | val 2.25721
  Classification -> best τ=0.445 (val F1=0.2554)
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.77242 | val 0.79600
  Epoch 016 - train 0.76225 | val 0.68742
  Classification -> best τ=0.700 (val F1=0.1647)
  Directional -> Accuracy: 0.4815, MCC: -0.0177, F1: 0.2632

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.68867 | val 0.66687
  Epoch 020 - train 0.71887 | val 0.91610
  Classification -> best τ=0.585 (val F1=0.3108)
  Directional -> Accuracy: 0.4912, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.76792 | val 0.67699
  Epoch 020 - train 0.71070 | val 1.28378

[I 2026-02-25 01:38:35,496] Trial 132 finished with value: 0.26969761097890055 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 15, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.1, 'dropout': 0.8, 'batch_size': 16, 'learning_rate': 0.009706432256563575, 'weight_decay': 1.4604656058282134e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.33686081639234694, 'early_stopping_min_delta': 0.00022075188029012447}. Best is trial 32 with value: 0.2908549754956826.

  Epoch 024 - train 0.67009 | val 2.95184
  Classification -> best τ=0.405 (val F1=0.2838)
  Directional -> Accuracy: 0.5000, MCC: 0.0042, F1: 0.5231

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.26969761097890055
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 15
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.72828 | val 0.67789
  Epoch 013 - train 0.68308 | val 0.83418
  Classification -> best τ=0.610 (val F1=0.2783)
  Directional -> Accuracy: 0.5584, MCC: 0.0881, F1: 0.4138

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.67833 | val 0.80100
  Epoch 013 - train 0.59788 | val 1.96665
  Classification -> best τ=0.550 (val F1=0.2431)
  Directional -> Accuracy: 0.6087, MCC: 0.1953, F1: 0.6667

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 16). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.68629 | val 0.85849
  Epoch 013 - train 0.71962 | val 1.30459
  Classification -> best τ=0.385 (val F1=0.3941)
  Directional -> Accuracy: 0.5000, MCC: -0.0483, F1: 0.6129

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.69395 | val 2.17061
  Epoch 017 - train 0.73052 | val 2.37378
  Classification -> best τ=0.575 (val F1=0.1800)
  Directional -> Accuracy: 0.4800, MCC: -0.0631, F1: 0.5517

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.76219 | val 1.52154
  Epoch 013 - train 0.60223 | val 2.11921
  Classification -> best τ=0.630 (val F1=0.3139)
  Directional -> Accuracy: 0.6154, MCC: 0.3948, F1: 0.4444

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.73176 | val 1.37971
  Epoch 013 - train 0.68169 | val 1.00296
  Classification -> best τ=0.425 (val F1=0.4719)
  Directional -> Accuracy: 0.5208, MCC: 0.0426, F1: 0.4651

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.68709 | val 1.25943
  Epoch 011 - train 0.71814 | val 1.55424
  Classification -> best τ=0.625 (val F1=0.2041)
  Directional -> Accuracy: 0.5714, MCC: 0.1400, F1: 0.5161

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 16). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.64716 | val 4.92425
  Epoch 011 - train 0.74659 | val 4.81507
  Classification -> best τ=0.480 (val F1=0.1512)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.80331 | val 0.72249
  Epoch 014 - train 0.79494 | val 0.76887
  Classification -> best τ=0.595 (val F1=0.3838)
  Directional -> Accuracy: 0.5366, MCC: 0.0966, F1: 0.4865

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 16). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 16). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.66577 | val 1.53135
  Epoch 016 - train 0.62884 | val 3.79280
  Classification -> best τ=0.465 (val F1=0.1461)
  Directional -> Accuracy: 0.4930, MCC: 0.0208, F1: 0.5263

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.68031 | val 0.87192
  Epoch 014 - train 0.63963 | val 1.97945
  Classification -> best τ=0.540 (val F1=0.3367)
  Directional -> Accuracy: 0.6667, MCC: 0.3879, F1: 0.4848

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.64672 | val 0.71501
  Epoch 020 - train 0.63236 | val 1.13812
  Epoch 023 - train 0.58348 | val 0.92769
  Classification -> best τ=0.795 (val F1=0.2987)
  Directional -> Accuracy: 0.7288, MCC: 0.4892, F1: 0.6800

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.66356 | val 3.10247
  Epoch 012 - train 0.71018 | val 2.11090
  Classification -> best τ=0.740 (val F1=0.0423)
  Directional -> Accuracy: 0.4419, MCC: -0.0901, F1: 0.4783

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.64323 | val 0.91040
  Epoch 011 - train 0.73143 | val 1.06703
  Classification -> best τ=0.400 (val F1=0.2866)
  Directional -> Accuracy: 0.6230, MCC: 0.2608, F1: 0.5660

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.71124 | val 1.16686
  Epoch 011 - train 0.69382 | val 2.55862
  Classification -> best τ=0.580 (val F1=0.2187)
  Directional -> Accuracy: 0.6226, MCC: 0.2403, F1: 0.5833

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.77093 | val 1.03348
  Epoch 011 - train 0.66362 | val 1.19542
  Classification -> best τ=0.405 (val F1=0.3354)
  Directional -> Accuracy: 0.5429, MCC: 0.0391, F1: 0.6667

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.71293 | val 1.06003
  Epoch 013 - train 0.72036 | val 0.75678
  Classification -> best τ=0.755 (val F1=0.1796)
  Directional -> Accuracy: 0.3833, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.73603 | val 0.95719
  Epoch 011 - train 0.70716 | val 0.94431
  Classification -> best τ=0.360 (val F1=0.1733)
  Directional -> Accuracy: 0.5658, MCC: 0.0187, F1: 0.6857

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.68912 | val 0.83142
  Epoch 019 - train 0.69231 | val 1.70620
  Classification -> best τ=0.545 (val F1=0.1970)
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 16). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.69879 | val 0.92668
  Epoch 017 - train 0.67720 | val 0.99344
  Classification -> best τ=0.575 (val F1=0.3043)
  Directional -> Accuracy: 0.4605, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.62888 | val 2.22930
  Epoch 013 - train 0.72134 | val 2.22084
  Classification -> best τ=0.330 (val F1=0.2692)
  Directional -> Accuracy: 0.6250, MCC: 0.1491, F1: 0.7273

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.72147 | val 1.32423
  Epoch 012 - train 0.76594 | val 1.74139
  Classification -> best τ=0.860 (val F1=0.2264)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.66393 | val 0.88808
  Epoch 016 - train 0.67279 | val 1.29205
  Classification -> best τ=0.550 (val F1=0.3902)
  Directional -> Accuracy: 0.5517, MCC: 0.1143, F1: 0.5667

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.63791 | val 2.54852
  Epoch 011 - train 0.65984 | val 2.81150
  Classification -> best τ=0.315 (val F1=0.3042)
  Directional -> Accuracy: 0.5455, MCC: 0.1149, F1: 0.5946

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.70889 | val 0.80527
  Epoch 011 - train 0.67291 | val 1.10030
  Classification -> best τ=0.485 (val F1=0.3976)
  Directional -> Accuracy: 0.5714, MCC: 0.1656, F1: 0.5556

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.59390 | val 2.47848
  Epoch 011 - train 0.56893 | val 2.05441
  Classification -> best τ=0.195 (val F1=0.2067)
  Directional -> Accuracy: 0.4468, MCC: 0.0487, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.71780 | val 0.68895
  Epoch 014 - train 0.75492 | val 0.75815
  Classification -> best τ=0.595 (val F1=0.1480)
  Directional -> Accuracy: 0.6047, MCC: 0.1366, F1: 0.7213

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.69159 | val 0.87125
  Epoch 015 - train 0.69022 | val 0.77750
  Classification -> best τ=0.525 (val F1=0.2683)
  Directional -> Accuracy: 0.4483, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.68569 | val 0.70413
  Epoch 014 - train 0.76724 | val 0.69154
  Classification -> best τ=0.490 (val F1=0.3870)
  Directional -> Accuracy: 0.6190, MCC: 0.2193, F1: 0.6923

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.64673 | val 1.61930
  Epoch 013 - train 0.65654 | val 1.62352
  Classification -> best τ=0.670 (val F1=0.3337)
  Directional -> Accuracy: 0.6364, MCC: 0.2739, F1: 0.6522

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.72522 | val 1.12789
  Epoch 013 - train 0.67651 | val 0.78267
  Classification -> best τ=0.755 (val F1=0.2498)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.67303 | val 0.80927
  Epoch 012 - train 0.63576 | val 0.91805
  Classification -> best τ=0.835 (val F1=0.2320)
  Directional -> Accuracy: 0.5294, MCC: 0.0172, F1: 0.6757

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.73641 | val 0.92235
  Epoch 013 - train 0.70006 | val 0.95817
  Classification -> best τ=0.200 (val F1=0.3259)
  Directional -> Accuracy: 0.5405, MCC: 0.1282, F1: 0.5000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.76103 | val 0.69473
  Epoch 020 - train 0.63418 | val 1.40262
  Epoch 021 - train 0.57564 | val 1.18990
  Classification -> best τ=0.400 (val F1=0.3337)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.69410 | val 0.89718
  Epoch 014 - train 0.67739 | val 1.69356
  Classification -> best τ=0.315 (val F1=0.2359)
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.6364

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.69236 | val 0.87716
  Epoch 020 - train 0.62632 | val 0.75576
  Epoch 027 - train 0.63889 | val 1.15731
  Classification -> best τ=0.105 (val F1=0.3767)
  Directional -> Accuracy: 0.5522, MCC: 0.0444, F1: 0.6591

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.72081 | val 0.69331
  Epoch 015 - train 0.67478 | val 0.88773
  Classification -> best τ=0.660 (val F1=0.3337)
  Directional -> Accuracy: 0.5814, MCC: 0.2280, F1: 0.4000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.70696 | val 0.73132
  Epoch 012 - train 0.72038 | val 0.87900
  Classification -> best τ=0.380 (val F1=0.2326)
  Directional -> Accuracy: 0.5614, MCC: 0.1968, F1: 0.6575

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.63560 | val 1.65628
  Epoch 012 - train 0.61376 | val 1.81706
  Classification -> best τ=0.535 (val F1=0.2403)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 16). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.65101 | val 0.90038
  Epoch 019 - train 0.68908 | val 0.71286
  Classification -> best τ=0.285 (val F1=0.4247)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.69038 | val 0.94511
  Epoch 012 - train 0.62794 | val 1.28298
  Classification -> best τ=0.320 (val F1=0.1870)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.7000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 16). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.69100 | val 0.66276
  Epoch 012 - train 0.69877 | val 0.73884
  Classification -> best τ=0.435 (val F1=0.3519)
  Directional -> Accuracy: 0.5132, MCC: 0.1155, F1: 0.6726

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.69294 | val 1.02185
  Epoch 011 - train 0.67636 | val 0.82157
  Classification -> best τ=0.490 (val F1=0.3121)
  Directional -> Accuracy: 0.5957, MCC: 0.2077, F1: 0.6780

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.62513 | val 2.35157
  Epoch 011 - train 0.59198 | val 2.38193
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.76489 | val 0.69592
  Epoch 020 - train 0.63273 | val 0.92768
  Epoch 030 - train 0.62927 | val 0.75640
  Classification -> best τ=0.445 (val F1=0.4249)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.67006 | val 1.31593
  Epoch 011 - train 0.74647 | val 1.28295
  Classification -> best τ=0.495 (val F1=0.2285)
  Directional -> Accuracy: 0.4211, MCC: -0.2693, F1: 0.5714

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.65841 | val 2.67732
  Epoch 015 - train 0.64002 | val 3.15478
  Classification -> best τ=0.225 (val F1=0.2554)
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.69202 | val 1.10451
  Epoch 020 - train 0.66161 | val 1.53129
  Epoch 023 - train 0.70644 | val 1.20974
  Classification -> best τ=0.590 (val F1=0.1186)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.61599 | val 0.81646
  Epoch 012 - train 0.66829 | val 0.98029
  Classification -> best τ=0.525 (val F1=0.2434)
  Directional -> Accuracy: 0.5614, MCC: 0.1530, F1: 0.4186

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.68891 | val 0.94799
  Epoch 020 - train 0.71444 | val 0.66536

[I 2026-02-25 01:40:48,844] Trial 133 finished with value: 0.2697280697835805 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 15, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.1, 'dropout': 0.8, 'batch_size': 16, 'learning_rate': 0.007153594564603654, 'weight_decay': 2.95344905707247e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.628414850237932, 'early_stopping_min_delta': 0.0004536023437738755}. Best is trial 32 with value: 0.2908549754956826.

  Epoch 030 - train 0.70496 | val 0.70543
  Classification -> best τ=0.610 (val F1=0.3090)
  Directional -> Accuracy: 0.5161, MCC: 0.0059, F1: 0.0625

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2697280697835805
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 15
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.65929 | val 1.94275
  Epoch 013 - train 0.68324 | val 0.98517
  Classification -> best τ=0.295 (val F1=0.1239)
  Directional -> Accuracy: 0.4675, MCC: 0.1047, F1: 0.6306

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.64271 | val 0.82550
  Epoch 014 - train 0.59596 | val 0.95118
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 16). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.65596 | val 0.90545
  Epoch 014 - train 0.69527 | val 0.99848
  Classification -> best τ=0.600 (val F1=0.2868)
  Directional -> Accuracy: 0.4583, MCC: -0.0707, F1: 0.4348

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.71004 | val 0.78394
  Epoch 012 - train 0.72075 | val 1.01471
  Classification -> best τ=0.650 (val F1=0.1095)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.65652 | val 0.75965
  Epoch 015 - train 0.61297 | val 0.72675
  Classification -> best τ=0.585 (val F1=0.4428)
  Directional -> Accuracy: 0.6731, MCC: 0.4192, F1: 0.6047

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.64332 | val 2.84136
  Epoch 011 - train 0.64320 | val 2.57878
  Classification -> best τ=0.650 (val F1=0.3508)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.67589 | val 1.18106
  Epoch 016 - train 0.70186 | val 0.90920
  Classification -> best τ=0.375 (val F1=0.2294)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.5714

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 16). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.69596 | val 5.50338
  Epoch 011 - train 0.56481 | val 5.69890
  Classification -> best τ=0.485 (val F1=0.2936)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.63753 | val 0.64263
  Epoch 017 - train 0.66756 | val 1.07656
  Classification -> best τ=0.470 (val F1=0.4960)
  Directional -> Accuracy: 0.6098, MCC: 0.0591, F1: 0.2727

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 16). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 16). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.74362 | val 1.56909
  Epoch 012 - train 0.65396 | val 0.98802
  Classification -> best τ=0.170 (val F1=0.1542)
  Directional -> Accuracy: 0.4507, MCC: 0.1052, F1: 0.6139

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.70619 | val 1.32024
  Epoch 019 - train 0.60363 | val 3.04173
  Classification -> best τ=0.845 (val F1=0.2915)
  Directional -> Accuracy: 0.6471, MCC: 0.3495, F1: 0.4375

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.65556 | val 0.77080
  Epoch 011 - train 0.61030 | val 0.72328
  Classification -> best τ=0.515 (val F1=0.2110)
  Directional -> Accuracy: 0.5085, MCC: 0.0000, F1: 0.6742

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.66813 | val 1.07735
  Epoch 014 - train 0.69139 | val 2.51645
  Classification -> best τ=0.565 (val F1=0.2288)
  Directional -> Accuracy: 0.5349, MCC: 0.1185, F1: 0.5833

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.66918 | val 0.73705
  Epoch 015 - train 0.69560 | val 0.83582
  Classification -> best τ=0.510 (val F1=0.3759)
  Directional -> Accuracy: 0.4426, MCC: -0.1136, F1: 0.4138

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.69079 | val 3.21033
  Epoch 011 - train 0.67542 | val 4.82456
  Classification -> best τ=0.530 (val F1=0.2608)
  Directional -> Accuracy: 0.6226, MCC: 0.2519, F1: 0.4737

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.66182 | val 1.29158
  Epoch 011 - train 0.65339 | val 1.49988
  Classification -> best τ=0.580 (val F1=0.3996)
  Directional -> Accuracy: 0.5857, MCC: 0.1539, F1: 0.6506

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.65046 | val 0.85738
  Epoch 020 - train 0.69059 | val 0.97150
  Epoch 021 - train 0.62829 | val 1.00167
  Classification -> best τ=0.300 (val F1=0.1346)
  Directional -> Accuracy: 0.6000, MCC: -0.1026, F1: 0.7500

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.64400 | val 2.18304
  Epoch 012 - train 0.68608 | val 1.80943
  Classification -> best τ=0.235 (val F1=0.1674)
  Directional -> Accuracy: 0.5789, MCC: 0.0986, F1: 0.6667

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.67573 | val 0.79853
  Epoch 013 - train 0.65046 | val 1.22373
  Classification -> best τ=0.310 (val F1=0.2778)
  Directional -> Accuracy: 0.4545, MCC: 0.0247, F1: 0.3077

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 16). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.66190 | val 0.75507
  Epoch 020 - train 0.64730 | val 0.69914
  Epoch 030 - train 0.54610 | val 1.57627
  Classification -> best τ=0.720 (val F1=0.3357)
  Directional -> Accuracy: 0.4737, MCC: 0.1067, F1: 0.0476

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.63287 | val 2.86632
  Epoch 011 - train 0.72159 | val 1.40033
  Classification -> best τ=0.440 (val F1=0.3143)
  Directional -> Accuracy: 0.6250, MCC: 0.1155, F1: 0.7429

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.64843 | val 1.92826
  Epoch 011 - train 0.68914 | val 2.06588
  Classification -> best τ=0.500 (val F1=0.2070)
  Directional -> Accuracy: 0.5455, MCC: 0.1220, F1: 0.6591

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.67300 | val 0.82093
  Epoch 012 - train 0.68877 | val 1.10878
  Classification -> best τ=0.565 (val F1=0.2918)
  Directional -> Accuracy: 0.6034, MCC: 0.2652, F1: 0.5660

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.70433 | val 2.11764
  Epoch 011 - train 0.62895 | val 3.27334
  Classification -> best τ=0.355 (val F1=0.2699)
  Directional -> Accuracy: 0.4848, MCC: -0.0380, F1: 0.4333

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.63395 | val 0.74247
  Epoch 015 - train 0.61265 | val 0.80736
  Classification -> best τ=0.665 (val F1=0.4015)
  Directional -> Accuracy: 0.5179, MCC: 0.1373, F1: 0.3415

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.59919 | val 2.45100
  Epoch 011 - train 0.55258 | val 2.48656
  Classification -> best τ=0.325 (val F1=0.2067)
  Directional -> Accuracy: 0.4255, MCC: 0.0000, F1: 0.5970

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.71883 | val 0.82863
  Epoch 014 - train 0.71351 | val 0.81201
  Classification -> best τ=0.590 (val F1=0.1816)
  Directional -> Accuracy: 0.5581, MCC: 0.0573, F1: 0.6545

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.70314 | val 0.74644
  Epoch 020 - train 0.67331 | val 0.72271
  Epoch 021 - train 0.62545 | val 1.07631
  Classification -> best τ=0.350 (val F1=0.2655)
  Directional -> Accuracy: 0.6034, MCC: 0.3182, F1: 0.4889

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.66676 | val 0.70747
  Epoch 020 - train 0.66592 | val 0.99475
  Epoch 021 - train 0.64164 | val 0.91824
  Classification -> best τ=0.670 (val F1=0.2833)
  Directional -> Accuracy: 0.5000, MCC: 0.2032, F1: 0.1600

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.63352 | val 1.25693
  Epoch 012 - train 0.61517 | val 1.40264
  Classification -> best τ=0.300 (val F1=0.2259)
  Directional -> Accuracy: 0.4773, MCC: -0.0621, F1: 0.6102

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.68326 | val 1.09627
  Epoch 011 - train 0.71285 | val 0.98429
  Classification -> best τ=0.675 (val F1=0.1778)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.60928 | val 0.83976
  Epoch 012 - train 0.54190 | val 1.61087
  Classification -> best τ=0.815 (val F1=0.2320)
  Directional -> Accuracy: 0.5490, MCC: 0.0929, F1: 0.5818

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.70319 | val 1.47898
  Epoch 011 - train 0.67595 | val 0.90524
  Classification -> best τ=0.410 (val F1=0.3093)
  Directional -> Accuracy: 0.5270, MCC: 0.1525, F1: 0.4068

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.64385 | val 1.84764
  Epoch 011 - train 0.58263 | val 2.26561
  Classification -> best τ=0.335 (val F1=0.2496)
  Directional -> Accuracy: 0.5526, MCC: 0.1195, F1: 0.6383

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.66110 | val 0.98858
  Epoch 011 - train 0.66843 | val 1.21993
  Classification -> best τ=0.470 (val F1=0.0854)
  Directional -> Accuracy: 0.5333, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.67142 | val 0.92975
  Epoch 013 - train 0.66614 | val 0.92868
  Classification -> best τ=0.185 (val F1=0.3431)
  Directional -> Accuracy: 0.5821, MCC: 0.1808, F1: 0.5882

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.72857 | val 1.17216
  Epoch 013 - train 0.70472 | val 1.04949
  Classification -> best τ=0.555 (val F1=0.2442)
  Directional -> Accuracy: 0.6047, MCC: 0.2529, F1: 0.4848

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.66793 | val 0.79161
  Epoch 020 - train 0.66374 | val 0.78820
  Epoch 023 - train 0.63577 | val 1.04177
  Classification -> best τ=0.405 (val F1=0.2830)
  Directional -> Accuracy: 0.4912, MCC: -0.0112, F1: 0.5085

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.68895 | val 1.71223
  Epoch 011 - train 0.64304 | val 1.49256
  Classification -> best τ=0.625 (val F1=0.3417)
  Directional -> Accuracy: 0.5745, MCC: 0.0406, F1: 0.6875

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 16). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.71060 | val 0.74459
  Epoch 013 - train 0.56865 | val 0.83979
  Classification -> best τ=0.470 (val F1=0.4689)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.72458 | val 1.08886
  Epoch 015 - train 0.62068 | val 1.49889
  Classification -> best τ=0.410 (val F1=0.1870)
  Directional -> Accuracy: 0.5128, MCC: -0.0473, F1: 0.6545

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 16). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.68189 | val 0.82631
  Epoch 020 - train 0.65860 | val 1.23982
  Epoch 021 - train 0.68294 | val 1.12835
  Classification -> best τ=0.680 (val F1=0.2949)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.71223 | val 0.84454
  Epoch 012 - train 0.60891 | val 0.73477
  Classification -> best τ=0.555 (val F1=0.2153)
  Directional -> Accuracy: 0.5319, MCC: 0.0926, F1: 0.6765

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.54893 | val 1.81456
  Epoch 012 - train 0.52858 | val 1.91395
  Classification -> best τ=0.535 (val F1=0.2712)
  Directional -> Accuracy: 0.5556, MCC: 0.0349, F1: 0.6970

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.64022 | val 0.91207
  Epoch 013 - train 0.76188 | val 0.74652
  Classification -> best τ=0.555 (val F1=0.3651)
  Directional -> Accuracy: 0.6500, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.67215 | val 0.75414
  Epoch 019 - train 0.68343 | val 0.75008
  Classification -> best τ=0.735 (val F1=0.2848)
  Directional -> Accuracy: 0.5088, MCC: 0.1595, F1: 0.2222

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.66959 | val 1.19839
  Epoch 011 - train 0.62167 | val 1.33806
  Classification -> best τ=0.230 (val F1=0.2554)
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.76998 | val 0.86214
  Epoch 020 - train 0.66788 | val 0.71724
  Epoch 024 - train 0.64579 | val 1.03400
  Classification -> best τ=0.670 (val F1=0.1784)
  Directional -> Accuracy: 0.4259, MCC: -0.1555, F1: 0.4746

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.67255 | val 0.99893
  Epoch 018 - train 0.60717 | val 0.94093
  Classification -> best τ=0.450 (val F1=0.2487)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.70812 | val 0.80190

[I 2026-02-25 01:43:00,921] Trial 134 finished with value: 0.2616122285866668 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 15, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.0, 'dropout': 0.8, 'batch_size': 16, 'learning_rate': 0.005782612835898994, 'weight_decay': 4.075373999869904e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.833619119317601, 'early_stopping_min_delta': 0.0015300454007180662}. Best is trial 32 with value: 0.2908549754956826.

  Epoch 012 - train 0.68691 | val 0.67283
  Classification -> best τ=0.445 (val F1=0.2270)
  Directional -> Accuracy: 0.4355, MCC: -0.1474, F1: 0.3137

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2616122285866668
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 15
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.69743 | val 0.98798
  Epoch 014 - train 0.70721 | val 0.71703
  Classification -> best τ=0.440 (val F1=0.2261)
  Directional -> Accuracy: 0.3766, MCC: -0.2309, F1: 0.4667

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.60204 | val 1.07428
  Epoch 012 - train 0.64059 | val 1.13778
  Classification -> best τ=0.450 (val F1=0.1307)
  Directional -> Accuracy: 0.5217, MCC: -0.0083, F1: 0.6207

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 16). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.76750 | val 0.99069
  Epoch 011 - train 0.70515 | val 1.03795
  Classification -> best τ=0.545 (val F1=0.1716)
  Directional -> Accuracy: 0.4792, MCC: -0.0113, F1: 0.3902

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.70348 | val 0.67751
  Epoch 020 - train 0.70360 | val 0.69002
  Classification -> best τ=0.535 (val F1=0.2667)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.67106 | val 0.72955
  Epoch 012 - train 0.59942 | val 0.85694
  Classification -> best τ=0.505 (val F1=0.3765)
  Directional -> Accuracy: 0.7115, MCC: 0.4808, F1: 0.6667

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.60679 | val 5.51086
  Epoch 011 - train 0.65401 | val 5.35790
  Classification -> best τ=0.515 (val F1=0.4108)
  Directional -> Accuracy: 0.4792, MCC: -0.0861, F1: 0.6377

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.73353 | val 1.07058
  Epoch 012 - train 0.73184 | val 1.37476
  Classification -> best τ=0.395 (val F1=0.2891)
  Directional -> Accuracy: 0.5286, MCC: 0.1904, F1: 0.5926

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 16). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.66903 | val 3.53210
  Epoch 011 - train 0.65673 | val 4.94317
  Classification -> best τ=0.160 (val F1=0.2229)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.72686 | val 1.09343
  Epoch 012 - train 0.70597 | val 1.47813
  Classification -> best τ=0.550 (val F1=0.4318)
  Directional -> Accuracy: 0.5122, MCC: -0.1171, F1: 0.2308

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 16). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 16). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.68924 | val 1.19895
  Epoch 011 - train 0.66002 | val 1.44265
  Classification -> best τ=0.305 (val F1=0.1283)
  Directional -> Accuracy: 0.4366, MCC: 0.0000, F1: 0.6078

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.68542 | val 0.74365
  Epoch 013 - train 0.68719 | val 0.96837
  Classification -> best τ=0.525 (val F1=0.2278)
  Directional -> Accuracy: 0.6078, MCC: 0.2092, F1: 0.5000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.69741 | val 0.77493
  Epoch 012 - train 0.68835 | val 2.13117
  Classification -> best τ=0.615 (val F1=0.1663)
  Directional -> Accuracy: 0.6441, MCC: 0.2993, F1: 0.6038

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.71363 | val 0.67680
  Epoch 012 - train 0.66483 | val 1.03753
  Classification -> best τ=0.780 (val F1=0.2465)
  Directional -> Accuracy: 0.4186, MCC: -0.2681, F1: 0.1379

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.69283 | val 0.69096
  Epoch 020 - train 0.70639 | val 0.63693
  Epoch 026 - train 0.68766 | val 0.68737
  Classification -> best τ=0.355 (val F1=0.3268)
  Directional -> Accuracy: 0.5738, MCC: 0.2007, F1: 0.6905

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.67125 | val 2.47334
  Epoch 011 - train 0.67363 | val 2.81931
  Classification -> best τ=0.595 (val F1=0.2262)
  Directional -> Accuracy: 0.5283, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.68903 | val 0.96650
  Epoch 011 - train 0.68653 | val 0.91359
  Classification -> best τ=0.460 (val F1=0.3524)
  Directional -> Accuracy: 0.6000, MCC: 0.1818, F1: 0.6744

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.75628 | val 1.37779
  Epoch 012 - train 0.68865 | val 0.79534
  Classification -> best τ=0.805 (val F1=0.2219)
  Directional -> Accuracy: 0.3833, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.67612 | val 1.87140
  Epoch 011 - train 0.66285 | val 2.85549
  Classification -> best τ=0.430 (val F1=0.1781)
  Directional -> Accuracy: 0.5789, MCC: 0.1504, F1: 0.6279

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.66914 | val 0.95797
  Epoch 011 - train 0.69461 | val 1.34583
  Classification -> best τ=0.695 (val F1=0.2249)
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 16). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.72820 | val 0.85605
  Epoch 020 - train 0.70116 | val 1.28755
  Epoch 023 - train 0.68671 | val 1.53250
  Classification -> best τ=0.375 (val F1=0.3121)
  Directional -> Accuracy: 0.4605, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.66964 | val 1.43551
  Epoch 011 - train 0.67108 | val 1.65182
  Classification -> best τ=0.575 (val F1=0.1180)
  Directional -> Accuracy: 0.5417, MCC: 0.0222, F1: 0.6333

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.69758 | val 0.80198
  Epoch 011 - train 0.74892 | val 0.95061
  Classification -> best τ=0.665 (val F1=0.1834)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.69804 | val 0.72459
  Epoch 011 - train 0.72030 | val 0.70574
  Classification -> best τ=0.610 (val F1=0.2437)
  Directional -> Accuracy: 0.4828, MCC: 0.0658, F1: 0.3182

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.67516 | val 1.34843
  Epoch 011 - train 0.68518 | val 1.25324
  Classification -> best τ=0.525 (val F1=0.1895)
  Directional -> Accuracy: 0.5303, MCC: 0.0225, F1: 0.2051

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.67135 | val 0.70697
  Epoch 018 - train 0.65825 | val 1.49088
  Classification -> best τ=0.505 (val F1=0.5322)
  Directional -> Accuracy: 0.5179, MCC: 0.1373, F1: 0.3415

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.62470 | val 1.30501
  Epoch 011 - train 0.69456 | val 1.26578
  Classification -> best τ=0.520 (val F1=0.1792)
  Directional -> Accuracy: 0.5745, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.69176 | val 0.75667
  Epoch 011 - train 0.73614 | val 1.01126
  Classification -> best τ=0.580 (val F1=0.2048)
  Directional -> Accuracy: 0.6512, MCC: 0.2588, F1: 0.7368

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.68271 | val 0.83603
  Epoch 014 - train 0.74606 | val 0.78660
  Classification -> best τ=0.475 (val F1=0.2894)
  Directional -> Accuracy: 0.4483, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.70336 | val 0.76162
  Epoch 020 - train 0.59689 | val 0.77321
  Epoch 025 - train 0.75193 | val 0.68835
  Classification -> best τ=0.560 (val F1=0.4576)
  Directional -> Accuracy: 0.6190, MCC: 0.2622, F1: 0.6000

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.69331 | val 1.03135
  Epoch 011 - train 0.69889 | val 0.86266
  Classification -> best τ=0.560 (val F1=0.3337)
  Directional -> Accuracy: 0.4091, MCC: -0.1890, F1: 0.3158

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.69278 | val 1.25717
  Epoch 012 - train 0.69989 | val 2.11937
  Classification -> best τ=0.615 (val F1=0.2890)
  Directional -> Accuracy: 0.6818, MCC: 0.3651, F1: 0.6957

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.69013 | val 0.80963
  Epoch 012 - train 0.58840 | val 0.99792
  Classification -> best τ=0.620 (val F1=0.2320)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.74293 | val 0.70858
  Epoch 011 - train 0.70990 | val 1.12343
  Classification -> best τ=0.340 (val F1=0.2774)
  Directional -> Accuracy: 0.5405, MCC: 0.1770, F1: 0.4333

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.73973 | val 1.01522
  Epoch 013 - train 0.53792 | val 1.06567
  Classification -> best τ=0.505 (val F1=0.4045)
  Directional -> Accuracy: 0.5789, MCC: 0.1857, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.72340 | val 0.82343
  Epoch 012 - train 0.67324 | val 0.90132
  Classification -> best τ=0.720 (val F1=0.1774)
  Directional -> Accuracy: 0.5556, MCC: 0.0945, F1: 0.2308

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.67425 | val 0.84630
  Epoch 014 - train 0.66451 | val 0.73177
  Classification -> best τ=0.175 (val F1=0.3431)
  Directional -> Accuracy: 0.5821, MCC: 0.1241, F1: 0.6667

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.70799 | val 0.69813
  Epoch 018 - train 0.67721 | val 0.92729
  Classification -> best τ=0.555 (val F1=0.2683)
  Directional -> Accuracy: 0.6047, MCC: 0.2739, F1: 0.4516

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.70317 | val 0.73098
  Epoch 017 - train 0.60546 | val 0.72141
  Classification -> best τ=0.515 (val F1=0.2166)
  Directional -> Accuracy: 0.5263, MCC: 0.0556, F1: 0.5263

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.67153 | val 1.48764
  Epoch 016 - train 0.71393 | val 2.27563
  Classification -> best τ=0.655 (val F1=0.3935)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 16). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.64686 | val 1.06678
  Epoch 015 - train 0.70009 | val 0.87544
  Classification -> best τ=0.380 (val F1=0.4667)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.67428 | val 1.26916
  Epoch 011 - train 0.77517 | val 1.31837
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.7000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 16). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.69575 | val 0.68104
  Epoch 020 - train 0.71167 | val 0.81999
  Epoch 024 - train 0.68313 | val 0.70067
  Classification -> best τ=0.540 (val F1=0.3508)
  Directional -> Accuracy: 0.5395, MCC: 0.0840, F1: 0.6067

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.67929 | val 1.24782
  Epoch 011 - train 0.68106 | val 1.57893
  Classification -> best τ=0.575 (val F1=0.3086)
  Directional -> Accuracy: 0.4894, MCC: 0.0000, F1: 0.0000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.74254 | val 1.50184
  Epoch 012 - train 0.68208 | val 1.94428
  Classification -> best τ=0.620 (val F1=0.4000)
  Directional -> Accuracy: 0.4000, MCC: -0.2411, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.71596 | val 0.93505
  Epoch 020 - train 0.70252 | val 0.93895
  Epoch 026 - train 0.68846 | val 1.03526
  Classification -> best τ=0.450 (val F1=0.4286)
  Directional -> Accuracy: 0.3750, MCC: 0.1175, F1: 0.5283

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.69928 | val 1.11971
  Epoch 020 - train 0.67416 | val 0.90783
  Epoch 023 - train 0.67458 | val 0.70119
  Classification -> best τ=0.625 (val F1=0.2744)
  Directional -> Accuracy: 0.5263, MCC: 0.1134, F1: 0.4000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.65573 | val 2.50699
  Epoch 011 - train 0.64132 | val 1.16563
  Classification -> best τ=0.845 (val F1=0.3133)
  Directional -> Accuracy: 0.4912, MCC: 0.0338, F1: 0.6234

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.68936 | val 0.76003
  Epoch 013 - train 0.67036 | val 0.68108
  Classification -> best τ=0.560 (val F1=0.1508)
  Directional -> Accuracy: 0.5556, MCC: 0.1090, F1: 0.6571

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.74356 | val 1.46609
  Epoch 015 - train 0.65136 | val 1.54819
  Classification -> best τ=0.585 (val F1=0.1990)
  Directional -> Accuracy: 0.5263, MCC: 0.0514, F1: 0.6301

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.69479 | val 0.66510

[I 2026-02-25 01:45:46,494] Trial 135 finished with value: 0.2742638817689756 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 15, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 16, 'learning_rate': 0.008161190042658754, 'weight_decay': 5.1108356853859673e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.2246077421585776, 'early_stopping_min_delta': 0.00213155265703395}. Best is trial 32 with value: 0.2908549754956826.

  Epoch 013 - train 0.67175 | val 0.90162
  Classification -> best τ=0.280 (val F1=0.3502)
  Directional -> Accuracy: 0.4839, MCC: -0.0206, F1: 0.5676

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2742638817689756
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 15
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.66366 | val 0.75782
  Epoch 020 - train 0.66206 | val 0.75082
  Epoch 022 - train 0.62716 | val 0.72234
  Classification -> best τ=0.600 (val F1=0.2453)
  Directional -> Accuracy: 0.5584, MCC: 0.0760, F1: 0.2917

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.62077 | val 0.81588
  Epoch 011 - train 0.63438 | val 0.88161
  Classification -> best τ=0.450 (val F1=0.1812)
  Directional -> Accuracy: 0.6087, MCC: 0.1761, F1: 0.7188

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 16). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.65555 | val 0.72054
  Epoch 015 - train 0.65188 | val 0.71396
  Classification -> best τ=0.605 (val F1=0.2743)
  Directional -> Accuracy: 0.4792, MCC: 0.1342, F1: 0.0741

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.68304 | val 0.97311
  Epoch 011 - train 0.68026 | val 1.01977
  Classification -> best τ=0.450 (val F1=0.1781)
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.60410 | val 1.67317
  Epoch 013 - train 0.60188 | val 1.61081
  Classification -> best τ=0.560 (val F1=0.4631)
  Directional -> Accuracy: 0.6154, MCC: 0.2682, F1: 0.5652

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.64985 | val 0.85388
  Epoch 011 - train 0.68692 | val 0.79682
  Classification -> best τ=0.510 (val F1=0.3649)
  Directional -> Accuracy: 0.5208, MCC: 0.0436, F1: 0.4390

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.68897 | val 0.69210
  Epoch 016 - train 0.67117 | val 0.71516
  Classification -> best τ=0.575 (val F1=0.2449)
  Directional -> Accuracy: 0.6000, MCC: 0.0928, F1: 0.3000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 16). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.69309 | val 2.01493
  Epoch 012 - train 0.63858 | val 1.77732
  Classification -> best τ=0.595 (val F1=0.3669)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.61331 | val 0.72853
  Epoch 015 - train 0.59097 | val 0.90923
  Classification -> best τ=0.535 (val F1=0.3877)
  Directional -> Accuracy: 0.3659, MCC: 0.0000, F1: 0.5357

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 16). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 16). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.65398 | val 0.74520
  Epoch 020 - train 0.62371 | val 1.05643
  Epoch 030 - train 0.58029 | val 0.91645
  Classification -> best τ=0.535 (val F1=0.3191)
  Directional -> Accuracy: 0.5634, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.67775 | val 1.29660
  Epoch 014 - train 0.68387 | val 0.93599
  Classification -> best τ=0.575 (val F1=0.2622)
  Directional -> Accuracy: 0.6078, MCC: 0.2654, F1: 0.3333

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.67337 | val 0.75104
  Epoch 012 - train 0.67842 | val 0.70700
  Classification -> best τ=0.485 (val F1=0.1479)
  Directional -> Accuracy: 0.5085, MCC: 0.0000, F1: 0.6742

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.66031 | val 0.87800
  Epoch 011 - train 0.58501 | val 0.85775
  Classification -> best τ=0.545 (val F1=0.0847)
  Directional -> Accuracy: 0.5116, MCC: 0.0617, F1: 0.5532

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.67014 | val 0.77223
  Epoch 016 - train 0.62763 | val 0.67816
  Classification -> best τ=0.250 (val F1=0.2718)
  Directional -> Accuracy: 0.5246, MCC: 0.1312, F1: 0.6813

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.67957 | val 0.70395
  Epoch 020 - train 0.64880 | val 0.82905
  Classification -> best τ=0.555 (val F1=0.2689)
  Directional -> Accuracy: 0.5660, MCC: 0.1593, F1: 0.2069

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.63759 | val 0.77591
  Epoch 012 - train 0.63220 | val 0.98653
  Classification -> best τ=0.355 (val F1=0.2927)
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.66558 | val 1.57436
  Epoch 012 - train 0.65510 | val 1.69870
  Classification -> best τ=0.800 (val F1=0.1796)
  Directional -> Accuracy: 0.3833, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.65549 | val 1.25897
  Epoch 013 - train 0.66055 | val 1.26898
  Classification -> best τ=0.440 (val F1=0.1733)
  Directional -> Accuracy: 0.5658, MCC: -0.0460, F1: 0.7080

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.70507 | val 0.77904
  Epoch 011 - train 0.65416 | val 0.73900
  Classification -> best τ=0.430 (val F1=0.2151)
  Directional -> Accuracy: 0.5152, MCC: 0.1796, F1: 0.3846

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 16). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.65124 | val 0.70749
  Epoch 012 - train 0.65687 | val 0.79364
  Classification -> best τ=0.515 (val F1=0.2893)
  Directional -> Accuracy: 0.4868, MCC: 0.1519, F1: 0.0930

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.66544 | val 0.69393
  Epoch 020 - train 0.59616 | val 0.65583
  Epoch 028 - train 0.53714 | val 0.76160
  Classification -> best τ=0.605 (val F1=0.2892)
  Directional -> Accuracy: 0.3958, MCC: 0.1130, F1: 0.0645

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.66784 | val 1.10229
  Epoch 011 - train 0.69359 | val 1.08711
  Classification -> best τ=0.465 (val F1=0.1677)
  Directional -> Accuracy: 0.5758, MCC: 0.1905, F1: 0.6744

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.69447 | val 0.80957
  Epoch 014 - train 0.68407 | val 0.81304
  Classification -> best τ=0.840 (val F1=0.3088)
  Directional -> Accuracy: 0.4483, MCC: 0.0018, F1: 0.2000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.64526 | val 1.03738
  Epoch 013 - train 0.68968 | val 1.01119
  Classification -> best τ=0.510 (val F1=0.1878)
  Directional -> Accuracy: 0.4242, MCC: -0.1716, F1: 0.3214

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.68594 | val 0.71552
  Epoch 020 - train 0.72287 | val 0.63528
  Epoch 030 - train 0.65005 | val 0.65626
  Classification -> best τ=0.630 (val F1=0.5836)
  Directional -> Accuracy: 0.5536, MCC: 0.2064, F1: 0.4186

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.66261 | val 1.03958
  Epoch 013 - train 0.61687 | val 0.78488
  Classification -> best τ=0.580 (val F1=0.1792)
  Directional -> Accuracy: 0.5745, MCC: 0.0318, F1: 0.0909

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.67765 | val 0.72787
  Epoch 014 - train 0.67134 | val 0.74074
  Classification -> best τ=0.670 (val F1=0.2878)
  Directional -> Accuracy: 0.4419, MCC: -0.1297, F1: 0.5000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.66317 | val 0.84903
  Epoch 014 - train 0.64689 | val 0.97921
  Classification -> best τ=0.365 (val F1=0.2829)
  Directional -> Accuracy: 0.5517, MCC: 0.2600, F1: 0.3500

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.65682 | val 0.71933
  Epoch 013 - train 0.66071 | val 0.75654
  Classification -> best τ=0.470 (val F1=0.3844)
  Directional -> Accuracy: 0.5476, MCC: 0.0214, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.69605 | val 0.93187
  Epoch 011 - train 0.63928 | val 0.92788
  Classification -> best τ=0.530 (val F1=0.1869)
  Directional -> Accuracy: 0.5909, MCC: 0.1890, F1: 0.5263

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.71310 | val 0.73088
  Epoch 014 - train 0.69144 | val 0.72779
  Classification -> best τ=0.575 (val F1=0.3475)
  Directional -> Accuracy: 0.7045, MCC: 0.4272, F1: 0.6977

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.66581 | val 0.69727
  Epoch 013 - train 0.60921 | val 0.79967
  Classification -> best τ=0.415 (val F1=0.2547)
  Directional -> Accuracy: 0.4510, MCC: -0.2750, F1: 0.6216

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.69029 | val 0.73729
  Epoch 015 - train 0.68188 | val 0.71531
  Classification -> best τ=0.605 (val F1=0.2993)
  Directional -> Accuracy: 0.5405, MCC: 0.1770, F1: 0.4333

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.66727 | val 1.02495
  Epoch 011 - train 0.68987 | val 0.91953
  Classification -> best τ=0.375 (val F1=0.3024)
  Directional -> Accuracy: 0.5263, MCC: 0.0679, F1: 0.6400

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.66025 | val 0.79634
  Epoch 016 - train 0.62082 | val 0.83870
  Classification -> best τ=0.485 (val F1=0.2500)
  Directional -> Accuracy: 0.5333, MCC: 0.1890, F1: 0.6557

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.62911 | val 0.78887
  Epoch 016 - train 0.62049 | val 0.70527
  Classification -> best τ=0.270 (val F1=0.3431)
  Directional -> Accuracy: 0.5522, MCC: 0.1897, F1: 0.4643

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.71080 | val 0.67119
  Epoch 020 - train 0.64990 | val 0.67933
  Classification -> best τ=0.420 (val F1=0.3004)
  Directional -> Accuracy: 0.6744, MCC: 0.3671, F1: 0.6316

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.67473 | val 0.71018
  Epoch 012 - train 0.66612 | val 0.70096
  Classification -> best τ=0.485 (val F1=0.1851)
  Directional -> Accuracy: 0.5263, MCC: 0.0808, F1: 0.5970

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.68318 | val 0.78516
  Epoch 013 - train 0.58919 | val 0.85060
  Classification -> best τ=0.435 (val F1=0.1661)
  Directional -> Accuracy: 0.5106, MCC: -0.0247, F1: 0.5965

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 16). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.70083 | val 0.80303
  Epoch 014 - train 0.60188 | val 1.29908
  Classification -> best τ=0.500 (val F1=0.4667)
  Directional -> Accuracy: 0.3500, MCC: -0.0721, F1: 0.5000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.74447 | val 0.90307
  Epoch 013 - train 0.62162 | val 0.93510
  Classification -> best τ=0.340 (val F1=0.1870)
  Directional -> Accuracy: 0.5128, MCC: -0.0742, F1: 0.6667

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 16). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.70337 | val 0.73242
  Epoch 011 - train 0.70249 | val 0.70338
  Classification -> best τ=0.475 (val F1=0.2752)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.66453 | val 0.81076
  Epoch 012 - train 0.70509 | val 0.90315
  Classification -> best τ=0.410 (val F1=0.2176)
  Directional -> Accuracy: 0.5532, MCC: 0.1357, F1: 0.6769

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.59383 | val 1.13031
  Epoch 013 - train 0.70023 | val 0.98586
  Classification -> best τ=0.430 (val F1=0.2500)
  Directional -> Accuracy: 0.6222, MCC: 0.2331, F1: 0.7302

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.64928 | val 0.79773
  Epoch 012 - train 0.68719 | val 0.74854
  Classification -> best τ=0.440 (val F1=0.2928)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.66212 | val 0.83313
  Epoch 018 - train 0.62319 | val 0.79381
  Classification -> best τ=0.535 (val F1=0.1984)
  Directional -> Accuracy: 0.6491, MCC: 0.3344, F1: 0.6154

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.61642 | val 1.10880
  Epoch 014 - train 0.57587 | val 1.89230
  Classification -> best τ=0.565 (val F1=0.4276)
  Directional -> Accuracy: 0.5088, MCC: 0.0262, F1: 0.5333

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.65339 | val 0.92866
  Epoch 015 - train 0.64220 | val 0.88689
  Classification -> best τ=0.330 (val F1=0.2415)
  Directional -> Accuracy: 0.5556, MCC: 0.2035, F1: 0.7000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.65753 | val 0.90972
  Epoch 011 - train 0.66681 | val 0.86145
  Classification -> best τ=0.775 (val F1=0.2157)
  Directional -> Accuracy: 0.4211, MCC: -0.1803, F1: 0.5217

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.65659 | val 0.73482

[I 2026-02-25 01:46:37,843] Trial 136 finished with value: 0.27342035745299875 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 15, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 32, 'learning_rate': 0.006073128744842908, 'weight_decay': 7.402009036508118e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.2229921302986011, 'early_stopping_min_delta': 0.0020378249509883564}. Best is trial 32 with value: 0.2908549754956826.

  Epoch 018 - train 0.64732 | val 0.79694
  Classification -> best τ=0.370 (val F1=0.3808)
  Directional -> Accuracy: 0.4839, MCC: 0.0000, F1: 0.6522

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.27342035745299875
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 15
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.58836 | val 1.00989
  Epoch 016 - train 0.58584 | val 1.24488
  Classification -> best τ=0.490 (val F1=0.3683)
  Directional -> Accuracy: 0.3896, MCC: -0.2020, F1: 0.4719

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.50904 | val 0.79440
  Epoch 011 - train 0.55064 | val 1.18308
  Classification -> best τ=0.495 (val F1=0.0881)
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 16). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.57967 | val 1.08165
  Epoch 011 - train 0.54976 | val 0.93884
  Classification -> best τ=0.580 (val F1=0.1399)
  Directional -> Accuracy: 0.4583, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.62824 | val 1.13255
  Epoch 011 - train 0.66613 | val 1.26800
  Classification -> best τ=0.460 (val F1=0.1217)
  Directional -> Accuracy: 0.5200, MCC: 0.0631, F1: 0.4857

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.53141 | val 2.21528
  Epoch 013 - train 0.45118 | val 1.80317
  Classification -> best τ=0.485 (val F1=0.3765)
  Directional -> Accuracy: 0.6923, MCC: 0.3858, F1: 0.7500

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.46579 | val 0.93186
  Epoch 014 - train 0.38378 | val 0.91317
  Classification -> best τ=0.490 (val F1=0.2806)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.61516 | val 0.79475
  Epoch 011 - train 0.58270 | val 1.16531
  Classification -> best τ=0.480 (val F1=0.1664)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.5714

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 16). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.52253 | val 1.97075
  Epoch 011 - train 0.48196 | val 1.91887
  Classification -> best τ=0.560 (val F1=0.4781)
  Directional -> Accuracy: 0.5111, MCC: 0.1085, F1: 0.5769

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.58562 | val 1.25963
  Epoch 013 - train 0.53358 | val 0.75941
  Classification -> best τ=0.535 (val F1=0.3977)
  Directional -> Accuracy: 0.5122, MCC: 0.0597, F1: 0.4737

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 16). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 16). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.59096 | val 0.93607
  Epoch 012 - train 0.58254 | val 0.97458
  Classification -> best τ=0.555 (val F1=0.1587)
  Directional -> Accuracy: 0.5634, MCC: 0.0455, F1: 0.2051

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.63776 | val 1.01655
  Epoch 011 - train 0.60093 | val 1.24104
  Classification -> best τ=0.540 (val F1=0.1368)
  Directional -> Accuracy: 0.6078, MCC: 0.2123, F1: 0.4737

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.62448 | val 0.89584
  Epoch 011 - train 0.59794 | val 0.79384
  Classification -> best τ=0.535 (val F1=0.2701)
  Directional -> Accuracy: 0.6102, MCC: 0.2966, F1: 0.4390

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.54079 | val 2.54374
  Epoch 012 - train 0.53119 | val 2.44959
  Classification -> best τ=0.475 (val F1=0.2869)
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.67456 | val 0.61617
  Epoch 015 - train 0.52306 | val 0.77692
  Classification -> best τ=0.285 (val F1=0.3134)
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.48656 | val 1.91347
  Epoch 011 - train 0.53970 | val 2.17334
  Classification -> best τ=0.495 (val F1=0.2145)
  Directional -> Accuracy: 0.4717, MCC: 0.0000, F1: 0.6410

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.55428 | val 1.11131
  Epoch 011 - train 0.53314 | val 1.33936
  Classification -> best τ=0.430 (val F1=0.2172)
  Directional -> Accuracy: 0.5857, MCC: 0.2306, F1: 0.7238

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.59200 | val 0.83818
  Epoch 011 - train 0.60825 | val 1.02202
  Classification -> best τ=0.490 (val F1=0.2372)
  Directional -> Accuracy: 0.5500, MCC: -0.0514, F1: 0.6824

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.60359 | val 1.42219
  Epoch 012 - train 0.62811 | val 0.81838
  Classification -> best τ=0.440 (val F1=0.1917)
  Directional -> Accuracy: 0.5000, MCC: 0.0344, F1: 0.5128

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.58902 | val 1.14469
  Epoch 011 - train 0.57265 | val 0.90100
  Classification -> best τ=0.480 (val F1=0.1715)
  Directional -> Accuracy: 0.6364, MCC: 0.2067, F1: 0.7447

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 16). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.56437 | val 0.99242
  Epoch 012 - train 0.52730 | val 0.93861
  Classification -> best τ=0.555 (val F1=0.2602)
  Directional -> Accuracy: 0.4605, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.53719 | val 1.78264
  Epoch 013 - train 0.54318 | val 1.94559
  Classification -> best τ=0.455 (val F1=0.2574)
  Directional -> Accuracy: 0.4167, MCC: 0.1615, F1: 0.1250

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.59803 | val 1.59184
  Epoch 011 - train 0.60624 | val 1.65672
  Classification -> best τ=0.475 (val F1=0.1677)
  Directional -> Accuracy: 0.5303, MCC: 0.0741, F1: 0.6353

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.56402 | val 1.76714
  Epoch 011 - train 0.52430 | val 2.34342
  Classification -> best τ=0.595 (val F1=0.2272)
  Directional -> Accuracy: 0.4828, MCC: 0.0658, F1: 0.3182

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.57813 | val 3.02673
  Epoch 011 - train 0.52238 | val 3.10237
  Classification -> best τ=0.465 (val F1=0.2319)
  Directional -> Accuracy: 0.5758, MCC: 0.1716, F1: 0.6111

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.57681 | val 1.00507
  Epoch 014 - train 0.49144 | val 1.46449
  Classification -> best τ=0.530 (val F1=0.3363)
  Directional -> Accuracy: 0.4821, MCC: 0.1096, F1: 0.1714

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.43948 | val 1.70128
  Epoch 011 - train 0.44504 | val 1.65503
  Classification -> best τ=0.580 (val F1=0.1792)
  Directional -> Accuracy: 0.5745, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.54775 | val 1.55201
  Epoch 011 - train 0.55780 | val 1.61921
  Classification -> best τ=0.500 (val F1=0.0269)
  Directional -> Accuracy: 0.5349, MCC: 0.0444, F1: 0.6000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.58080 | val 0.87803
  Epoch 011 - train 0.54692 | val 0.95890
  Classification -> best τ=0.460 (val F1=0.2970)
  Directional -> Accuracy: 0.5517, MCC: 0.1685, F1: 0.4583

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.53794 | val 0.66573
  Epoch 019 - train 0.62767 | val 2.59894
  Classification -> best τ=0.495 (val F1=0.3677)
  Directional -> Accuracy: 0.5952, MCC: 0.1691, F1: 0.6667

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.49557 | val 1.44593
  Epoch 011 - train 0.47565 | val 1.76231
  Classification -> best τ=0.600 (val F1=0.0212)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.55452 | val 0.77405
  Epoch 011 - train 0.57457 | val 0.82064
  Classification -> best τ=0.530 (val F1=0.1506)
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.53159 | val 1.12219
  Epoch 013 - train 0.44166 | val 1.17414
  Classification -> best τ=0.695 (val F1=0.2320)
  Directional -> Accuracy: 0.5098, MCC: -0.0466, F1: 0.6575

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.59361 | val 2.40512
  Epoch 012 - train 0.61599 | val 1.90095
  Classification -> best τ=0.560 (val F1=0.3259)
  Directional -> Accuracy: 0.5405, MCC: 0.1770, F1: 0.4333

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.52058 | val 0.93918
  Epoch 013 - train 0.43050 | val 1.16308
  Classification -> best τ=0.435 (val F1=0.3130)
  Directional -> Accuracy: 0.5526, MCC: 0.1443, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.51191 | val 1.83179
  Epoch 011 - train 0.45780 | val 2.59903
  Classification -> best τ=0.525 (val F1=0.3307)
  Directional -> Accuracy: 0.5111, MCC: 0.0179, F1: 0.4762

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.57937 | val 0.76580
  Epoch 012 - train 0.53888 | val 1.04582
  Classification -> best τ=0.410 (val F1=0.3767)
  Directional -> Accuracy: 0.5224, MCC: 0.1526, F1: 0.3846

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.48539 | val 0.85339
  Epoch 018 - train 0.38632 | val 1.21294
  Classification -> best τ=0.360 (val F1=0.2506)
  Directional -> Accuracy: 0.6512, MCC: 0.3142, F1: 0.6154

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.58591 | val 0.70372
  Epoch 011 - train 0.52809 | val 0.77255
  Classification -> best τ=0.405 (val F1=0.1803)
  Directional -> Accuracy: 0.5263, MCC: 0.1078, F1: 0.6301

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.49641 | val 0.79484
  Epoch 018 - train 0.36185 | val 0.97118
  Classification -> best τ=0.630 (val F1=0.3544)
  Directional -> Accuracy: 0.3617, MCC: -0.1524, F1: 0.0625

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for proper time series validation for PICO. Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 16). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.53053 | val 2.24678
  Epoch 011 - train 0.43313 | val 2.02586
  Classification -> best τ=0.500 (val F1=0.2582)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.55165 | val 0.95550
  Epoch 011 - train 0.52053 | val 0.99361
  Classification -> best τ=0.535 (val F1=0.2431)
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.0000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 16). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.59082 | val 1.60020
  Epoch 011 - train 0.56762 | val 1.86939
  Classification -> best τ=0.340 (val F1=0.1663)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.56955 | val 0.85009
  Epoch 011 - train 0.55773 | val 0.87114
  Classification -> best τ=0.525 (val F1=0.1733)
  Directional -> Accuracy: 0.5957, MCC: 0.2191, F1: 0.6885

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.50363 | val 1.42575
  Epoch 011 - train 0.48221 | val 1.71145
  Classification -> best τ=0.520 (val F1=0.2000)
  Directional -> Accuracy: 0.6000, MCC: 0.1717, F1: 0.6786

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.50803 | val 1.03296
  Epoch 012 - train 0.48378 | val 1.05061
  Classification -> best τ=0.470 (val F1=0.3647)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.58255 | val 2.30756
  Epoch 011 - train 0.58051 | val 2.72464
  Classification -> best τ=0.440 (val F1=0.1685)
  Directional -> Accuracy: 0.5439, MCC: 0.0000, F1: 0.7045

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.52837 | val 3.83079
  Epoch 011 - train 0.56451 | val 3.89806
  Classification -> best τ=0.610 (val F1=0.3508)
  Directional -> Accuracy: 0.5789, MCC: 0.1685, F1: 0.6000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.57742 | val 1.47446
  Epoch 011 - train 0.57059 | val 1.90362
  Classification -> best τ=0.400 (val F1=0.2114)
  Directional -> Accuracy: 0.5556, MCC: 0.2035, F1: 0.7000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.58213 | val 1.28413
  Epoch 011 - train 0.57786 | val 1.28202
  Classification -> best τ=0.470 (val F1=0.0063)
  Directional -> Accuracy: 0.4737, MCC: -0.0770, F1: 0.5946

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.58900 | val 1.11866
  Epoch 014 - train 0.52425 | val 1.50166

[I 2026-02-25 01:47:08,485] Trial 137 finished with value: 0.23719087814939166 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 15, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.5, 'batch_size': 32, 'learning_rate': 0.009889126538102333, 'weight_decay': 4.9913626983537233e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.94539503621139, 'early_stopping_min_delta': 0.002396279888194355}. Best is trial 32 with value: 0.2908549754956826.

  Classification -> best τ=0.545 (val F1=0.2148)
  Directional -> Accuracy: 0.4839, MCC: -0.0839, F1: 0.1579

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.23719087814939166
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.65221 | val 1.25986
  Epoch 013 - train 0.61932 | val 1.27729
  Classification -> best τ=0.440 (val F1=0.2036)
  Directional -> Accuracy: 0.5132, MCC: -0.0693, F1: 0.1778

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.72936 | val 0.72617
  Epoch 011 - train 0.67444 | val 0.70144
  Classification -> best τ=0.425 (val F1=0.0742)
  Directional -> Accuracy: 0.6000, MCC: 0.1764, F1: 0.7429

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.64734 | val 0.71218
  Epoch 011 - train 0.71189 | val 0.69740
  Classification -> best τ=0.495 (val F1=0.3693)
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.64989 | val 1.10933
  Epoch 011 - train 0.65514 | val 1.06770
  Classification -> best τ=0.420 (val F1=0.1868)
  Directional -> Accuracy: 0.4800, MCC: -0.0518, F1: 0.5301

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.66585 | val 0.65417
  Epoch 016 - train 0.62983 | val 0.85302
  Classification -> best τ=0.485 (val F1=0.4158)
  Directional -> Accuracy: 0.5490, MCC: 0.1500, F1: 0.7013

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.63206 | val 0.70165
  Epoch 011 - train 0.67650 | val 0.70010
  Classification -> best τ=0.580 (val F1=0.2357)
  Directional -> Accuracy: 0.5319, MCC: 0.0929, F1: 0.6333

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.68134 | val 0.71833
  Epoch 011 - train 0.68325 | val 0.76848
  Classification -> best τ=0.520 (val F1=0.3086)
  Directional -> Accuracy: 0.5217, MCC: 0.0583, F1: 0.4923

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.72733 | val 0.81098
  Epoch 011 - train 0.67194 | val 1.08692
  Classification -> best τ=0.490 (val F1=0.1729)
  Directional -> Accuracy: 0.5581, MCC: -0.0137, F1: 0.1739

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.72076 | val 0.70867
  Epoch 015 - train 0.63267 | val 1.17237
  Classification -> best τ=0.540 (val F1=0.3039)
  Directional -> Accuracy: 0.5714, MCC: 0.1599, F1: 0.0870

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.63514 | val 0.89346
  Epoch 011 - train 0.64739 | val 1.14507
  Classification -> best τ=0.495 (val F1=0.1998)
  Directional -> Accuracy: 0.5429, MCC: -0.0589, F1: 0.1111

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.67329 | val 1.53518
  Epoch 011 - train 0.67871 | val 1.39351
  Classification -> best τ=0.560 (val F1=0.2562)
  Directional -> Accuracy: 0.6200, MCC: 0.2766, F1: 0.3448

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.65343 | val 1.01585
  Epoch 012 - train 0.63427 | val 1.20802
  Classification -> best τ=0.440 (val F1=0.2453)
  Directional -> Accuracy: 0.5345, MCC: 0.1132, F1: 0.2286

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.61990 | val 0.84714
  Epoch 017 - train 0.69916 | val 0.73218
  Classification -> best τ=0.555 (val F1=0.2910)
  Directional -> Accuracy: 0.5238, MCC: -0.0663, F1: 0.0909

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.68940 | val 0.73360
  Epoch 011 - train 0.66595 | val 0.67079
  Classification -> best τ=0.415 (val F1=0.3012)
  Directional -> Accuracy: 0.5167, MCC: 0.0338, F1: 0.5538

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.68915 | val 1.08127
  Epoch 013 - train 0.69079 | val 0.99204
  Classification -> best τ=0.555 (val F1=0.2673)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.67712 | val 1.21953
  Epoch 011 - train 0.62625 | val 1.13264
  Classification -> best τ=0.410 (val F1=0.3483)
  Directional -> Accuracy: 0.6377, MCC: 0.3302, F1: 0.7423

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.63373 | val 1.92554
  Epoch 012 - train 0.68003 | val 2.02932
  Classification -> best τ=0.635 (val F1=0.1342)
  Directional -> Accuracy: 0.3898, MCC: 0.1013, F1: 0.0526

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.68209 | val 1.01550
  Epoch 016 - train 0.64649 | val 1.01416
  Classification -> best τ=0.800 (val F1=0.1923)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.67667 | val 0.78592
  Epoch 013 - train 0.63456 | val 1.11744
  Classification -> best τ=0.570 (val F1=0.2234)
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.68595 | val 0.66641
  Epoch 020 - train 0.66640 | val 0.71763
  Classification -> best τ=0.575 (val F1=0.2511)
  Directional -> Accuracy: 0.4667, MCC: 0.1059, F1: 0.0476

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.64606 | val 0.87080
  Epoch 020 - train 0.56096 | val 0.73692
  Epoch 022 - train 0.57725 | val 0.65785
  Classification -> best τ=0.610 (val F1=0.4419)
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.73768 | val 0.99754
  Epoch 013 - train 0.71754 | val 0.83055
  Classification -> best τ=0.475 (val F1=0.3714)
  Directional -> Accuracy: 0.4545, MCC: -0.0911, F1: 0.4706

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.66491 | val 0.72973
  Epoch 013 - train 0.65140 | val 0.71617
  Classification -> best τ=0.545 (val F1=0.3189)
  Directional -> Accuracy: 0.4828, MCC: 0.1087, F1: 0.2500

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.69454 | val 0.76697
  Epoch 011 - train 0.66935 | val 0.69301
  Classification -> best τ=0.500 (val F1=0.2390)
  Directional -> Accuracy: 0.4615, MCC: -0.0631, F1: 0.5977

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.65237 | val 0.77158
  Epoch 016 - train 0.63743 | val 0.67338
  Classification -> best τ=0.500 (val F1=0.4057)
  Directional -> Accuracy: 0.5357, MCC: 0.1242, F1: 0.4583

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.69217 | val 0.83224
  Epoch 011 - train 0.69556 | val 0.79489
  Classification -> best τ=0.505 (val F1=0.0105)
  Directional -> Accuracy: 0.5870, MCC: 0.1383, F1: 0.4571

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.71384 | val 0.67886
  Epoch 014 - train 0.65104 | val 0.76813
  Classification -> best τ=0.585 (val F1=0.2178)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.5333

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.64878 | val 0.74569
  Epoch 011 - train 0.65819 | val 0.77160
  Classification -> best τ=0.475 (val F1=0.2113)
  Directional -> Accuracy: 0.5439, MCC: 0.3032, F1: 0.3158

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.87889 | val 0.78321
  Epoch 011 - train 0.64317 | val 0.96335
  Classification -> best τ=0.455 (val F1=0.4139)
  Directional -> Accuracy: 0.6098, MCC: 0.2283, F1: 0.7143

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.74320 | val 0.70720
  Epoch 011 - train 0.69345 | val 0.70834
  Classification -> best τ=0.550 (val F1=0.2814)
  Directional -> Accuracy: 0.5581, MCC: 0.1150, F1: 0.5366

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.76067 | val 0.73710
  Epoch 016 - train 0.67872 | val 0.70980
  Classification -> best τ=0.690 (val F1=0.1729)
  Directional -> Accuracy: 0.4419, MCC: -0.1655, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.64426 | val 0.90294
  Epoch 012 - train 0.61697 | val 0.92665
  Classification -> best τ=0.620 (val F1=0.2969)
  Directional -> Accuracy: 0.4400, MCC: -0.1996, F1: 0.5758

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.67854 | val 0.74879
  Epoch 011 - train 0.62643 | val 0.72867
  Classification -> best τ=0.380 (val F1=0.3391)
  Directional -> Accuracy: 0.5753, MCC: 0.1768, F1: 0.5634

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.61099 | val 1.22316
  Epoch 014 - train 0.67335 | val 0.87882
  Classification -> best τ=0.480 (val F1=0.2887)
  Directional -> Accuracy: 0.5676, MCC: 0.1737, F1: 0.6522

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.69544 | val 0.81828
  Epoch 013 - train 0.66062 | val 0.76132
  Classification -> best τ=0.560 (val F1=0.2589)
  Directional -> Accuracy: 0.5682, MCC: 0.1290, F1: 0.4865

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.63534 | val 0.69846
  Epoch 011 - train 0.66119 | val 0.72984
  Classification -> best τ=0.435 (val F1=0.3551)
  Directional -> Accuracy: 0.5455, MCC: -0.0072, F1: 0.6739

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.59672 | val 1.26587
  Epoch 011 - train 0.63204 | val 1.51097
  Classification -> best τ=0.525 (val F1=0.2741)
  Directional -> Accuracy: 0.6905, MCC: 0.3977, F1: 0.6667

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.66823 | val 0.94881
  Epoch 011 - train 0.66886 | val 0.91146
  Classification -> best τ=0.345 (val F1=0.2622)
  Directional -> Accuracy: 0.5000, MCC: 0.1192, F1: 0.6410

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.69533 | val 1.42497
  Epoch 011 - train 0.65581 | val 1.54895
  Classification -> best τ=0.375 (val F1=0.3397)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.68835 | val 0.66392
  Epoch 020 - train 0.66329 | val 0.65076
  Epoch 023 - train 0.57873 | val 0.63417
  Classification -> best τ=0.315 (val F1=0.4386)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.73971 | val 0.87274
  Epoch 013 - train 0.69161 | val 0.77645
  Classification -> best τ=0.490 (val F1=0.2623)
  Directional -> Accuracy: 0.4324, MCC: -0.1085, F1: 0.2222

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.66147 | val 0.97890
  Epoch 012 - train 0.65500 | val 0.82804
  Classification -> best τ=0.495 (val F1=0.3889)
  Directional -> Accuracy: 0.5200, MCC: 0.0944, F1: 0.6604

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.69176 | val 0.67798
  Epoch 020 - train 0.64562 | val 0.74820
  Epoch 022 - train 0.62157 | val 0.75184
  Classification -> best τ=0.525 (val F1=0.3403)
  Directional -> Accuracy: 0.5000, MCC: 0.0547, F1: 0.2069

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.74184 | val 0.91357
  Epoch 011 - train 0.66452 | val 1.01352
  Classification -> best τ=0.595 (val F1=0.2530)
  Directional -> Accuracy: 0.4419, MCC: -0.0259, F1: 0.0769

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.73236 | val 0.94342
  Epoch 014 - train 0.68919 | val 0.97119
  Classification -> best τ=0.600 (val F1=0.5514)
  Directional -> Accuracy: 0.4286, MCC: 0.0116, F1: 0.5333

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.68482 | val 1.15601
  Epoch 012 - train 0.69346 | val 1.31672
  Classification -> best τ=0.625 (val F1=0.1267)
  Directional -> Accuracy: 0.4464, MCC: -0.1448, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.70568 | val 0.96718
  Epoch 011 - train 0.66352 | val 1.03876
  Classification -> best τ=0.610 (val F1=0.3735)
  Directional -> Accuracy: 0.5714, MCC: 0.1518, F1: 0.6000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.65457 | val 0.98080
  Epoch 011 - train 0.67054 | val 0.99975
  Classification -> best τ=0.300 (val F1=0.2360)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.66522 | val 1.92900
  Epoch 014 - train 0.64295 | val 2.67410
  Classification -> best τ=0.455 (val F1=0.1667)
  Directional -> Accuracy: 0.5357, MCC: 0.1397, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.66407 | val 0.77448

[I 2026-02-25 01:48:48,261] Trial 138 finished with value: 0.2780441847309058 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 32, 'learning_rate': 0.00410830764049513, 'weight_decay': 0.00014899658266374417, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.45132538490326957, 'early_stopping_min_delta': 0.002256808914597386}. Best is trial 32 with value: 0.2908549754956826.

  Epoch 012 - train 0.66074 | val 0.91840
  Classification -> best τ=0.410 (val F1=0.2847)
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2780441847309058
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.54656 | val 1.59689
  Epoch 020 - train 0.50574 | val 1.99064
  Epoch 022 - train 0.44448 | val 1.99768
  Classification -> best τ=0.450 (val F1=0.2771)
  Directional -> Accuracy: 0.5658, MCC: 0.1296, F1: 0.5352

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.46644 | val 0.72414
  Epoch 020 - train 0.37287 | val 0.99239
  Epoch 021 - train 0.37198 | val 0.88469
  Classification -> best τ=0.505 (val F1=0.3330)
  Directional -> Accuracy: 0.6000, MCC: 0.1297, F1: 0.7188

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.49160 | val 0.86526
  Epoch 020 - train 0.39299 | val 1.20612
  Epoch 022 - train 0.36483 | val 1.30380
  Classification -> best τ=0.525 (val F1=0.2449)
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.60610 | val 1.86133
  Epoch 020 - train 0.54336 | val 1.74944
  Epoch 021 - train 0.51590 | val 3.41369
  Classification -> best τ=0.310 (val F1=0.2125)
  Directional -> Accuracy: 0.5200, MCC: -0.0420, F1: 0.6604

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.45091 | val 1.18554
  Epoch 020 - train 0.34291 | val 1.00993
  Epoch 023 - train 0.35877 | val 1.11775
  Classification -> best τ=0.630 (val F1=0.4397)
  Directional -> Accuracy: 0.5294, MCC: 0.0327, F1: 0.6364

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.42424 | val 1.12930
  Epoch 020 - train 0.29370 | val 2.57957
  Epoch 022 - train 0.28019 | val 5.42292
  Classification -> best τ=0.460 (val F1=0.1715)
  Directional -> Accuracy: 0.4894, MCC: 0.0000, F1: 0.6571

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.58215 | val 1.07605
  Epoch 020 - train 0.43263 | val 0.90839
  Epoch 021 - train 0.49104 | val 1.44188
  Classification -> best τ=0.545 (val F1=0.1805)
  Directional -> Accuracy: 0.6087, MCC: 0.1467, F1: 0.0690

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.39543 | val 0.98581
  Epoch 020 - train 0.21411 | val 2.53123
  Epoch 024 - train 0.24628 | val 2.69940
  Classification -> best τ=0.430 (val F1=0.1214)
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.5902

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.47509 | val 1.04882
  Epoch 020 - train 0.30929 | val 2.26086
  Epoch 022 - train 0.26529 | val 2.25932
  Classification -> best τ=0.510 (val F1=0.1945)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.52839 | val 1.36133
  Epoch 020 - train 0.40933 | val 1.54415
  Epoch 022 - train 0.39353 | val 1.30976
  Classification -> best τ=0.515 (val F1=0.0701)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.46544 | val 1.66887
  Epoch 020 - train 0.37190 | val 4.23980
  Epoch 023 - train 0.31299 | val 2.70909
  Classification -> best τ=0.525 (val F1=0.2500)
  Directional -> Accuracy: 0.5400, MCC: 0.0164, F1: 0.0800

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.53028 | val 1.50859
  Epoch 020 - train 0.44436 | val 1.59655
  Epoch 022 - train 0.38681 | val 2.49856
  Classification -> best τ=0.455 (val F1=0.1699)
  Directional -> Accuracy: 0.4310, MCC: -0.2722, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.46272 | val 1.71118
  Epoch 020 - train 0.35586 | val 1.70004
  Epoch 021 - train 0.34722 | val 2.34342
  Classification -> best τ=0.370 (val F1=0.1927)
  Directional -> Accuracy: 0.4286, MCC: -0.1718, F1: 0.6000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.59062 | val 1.12351
  Epoch 020 - train 0.49652 | val 1.24068
  Epoch 021 - train 0.50210 | val 1.49141
  Classification -> best τ=0.480 (val F1=0.2224)
  Directional -> Accuracy: 0.4667, MCC: -0.0673, F1: 0.4286

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.49990 | val 1.36757
  Epoch 020 - train 0.38865 | val 2.11853
  Epoch 023 - train 0.35595 | val 1.07052
  Classification -> best τ=0.680 (val F1=0.2673)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.53029 | val 0.96574
  Epoch 020 - train 0.43628 | val 1.38395
  Epoch 022 - train 0.40529 | val 1.26552
  Classification -> best τ=0.415 (val F1=0.2708)
  Directional -> Accuracy: 0.5942, MCC: 0.2287, F1: 0.7200

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.54262 | val 3.78773
  Epoch 020 - train 0.42065 | val 6.25419
  Epoch 021 - train 0.37670 | val 5.95075
  Classification -> best τ=0.530 (val F1=0.1291)
  Directional -> Accuracy: 0.3729, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.55160 | val 1.54203
  Epoch 020 - train 0.44249 | val 2.86484
  Epoch 021 - train 0.47728 | val 3.93483
  Classification -> best τ=0.485 (val F1=0.1565)
  Directional -> Accuracy: 0.5733, MCC: -0.0401, F1: 0.7193

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.60559 | val 2.26866
  Epoch 020 - train 0.46965 | val 3.60589
  Epoch 022 - train 0.47947 | val 3.14558
  Classification -> best τ=0.530 (val F1=0.2234)
  Directional -> Accuracy: 0.4615, MCC: 0.1262, F1: 0.1860

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.56907 | val 0.75473
  Epoch 020 - train 0.45579 | val 1.75562
  Epoch 023 - train 0.43085 | val 1.62050
  Classification -> best τ=0.510 (val F1=0.3497)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.44855 | val 0.95456
  Epoch 020 - train 0.34871 | val 2.57265
  Epoch 023 - train 0.29607 | val 2.78326
  Classification -> best τ=0.470 (val F1=0.4109)
  Directional -> Accuracy: 0.6170, MCC: 0.1729, F1: 0.7000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.58670 | val 1.14873
  Epoch 020 - train 0.46872 | val 1.36814
  Epoch 021 - train 0.44890 | val 1.56788
  Classification -> best τ=0.585 (val F1=0.1318)
  Directional -> Accuracy: 0.5152, MCC: 0.0727, F1: 0.1111

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.55009 | val 0.84609
  Epoch 020 - train 0.40144 | val 0.94661
  Epoch 021 - train 0.38892 | val 1.39870
  Classification -> best τ=0.640 (val F1=0.3282)
  Directional -> Accuracy: 0.4655, MCC: 0.0028, F1: 0.3404

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.57268 | val 0.99413
  Epoch 020 - train 0.47746 | val 1.42512
  Epoch 022 - train 0.46211 | val 1.51355
  Classification -> best τ=0.565 (val F1=0.3136)
  Directional -> Accuracy: 0.4923, MCC: -0.0359, F1: 0.3529

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.53785 | val 0.70680
  Epoch 020 - train 0.40909 | val 0.89717
  Epoch 025 - train 0.37275 | val 1.06071
  Classification -> best τ=0.520 (val F1=0.3629)
  Directional -> Accuracy: 0.4821, MCC: -0.0283, F1: 0.4912

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.44045 | val 0.88087
  Epoch 020 - train 0.28616 | val 0.98503
  Epoch 021 - train 0.31960 | val 1.14639
  Classification -> best τ=0.520 (val F1=0.1099)
  Directional -> Accuracy: 0.5435, MCC: 0.1609, F1: 0.6038

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.52298 | val 1.47295
  Epoch 020 - train 0.43370 | val 0.90728
  Epoch 023 - train 0.37754 | val 1.05294
  Classification -> best τ=0.435 (val F1=0.1803)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.53289 | val 1.37488
  Epoch 020 - train 0.43001 | val 2.06880
  Epoch 022 - train 0.40930 | val 2.44232
  Classification -> best τ=0.490 (val F1=0.2113)
  Directional -> Accuracy: 0.5263, MCC: 0.2741, F1: 0.2703

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.42664 | val 1.41521
  Epoch 020 - train 0.35867 | val 2.14717
  Epoch 022 - train 0.36835 | val 4.27828
  Classification -> best τ=0.480 (val F1=0.4345)
  Directional -> Accuracy: 0.5610, MCC: 0.1021, F1: 0.6897

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.49041 | val 0.66567
  Epoch 020 - train 0.32534 | val 1.05042
  Epoch 030 - train 0.14476 | val 1.38333
  Classification -> best τ=0.645 (val F1=0.4110)
  Directional -> Accuracy: 0.4651, MCC: -0.0693, F1: 0.4651

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.48188 | val 0.94414
  Epoch 020 - train 0.22045 | val 1.77193
  Epoch 023 - train 0.23328 | val 2.90589
  Classification -> best τ=0.550 (val F1=0.1037)
  Directional -> Accuracy: 0.6047, MCC: 0.2499, F1: 0.5405

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.45477 | val 1.13796
  Epoch 020 - train 0.29218 | val 1.91089
  Epoch 023 - train 0.27375 | val 1.61827
  Classification -> best τ=0.415 (val F1=0.2837)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.60344 | val 1.26897
  Epoch 020 - train 0.50241 | val 0.86112
  Epoch 029 - train 0.39241 | val 2.55324
  Classification -> best τ=0.705 (val F1=0.3387)
  Directional -> Accuracy: 0.5753, MCC: 0.2901, F1: 0.4364

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.47445 | val 1.17870
  Epoch 020 - train 0.31575 | val 4.51834
  Epoch 021 - train 0.30927 | val 4.28366
  Classification -> best τ=0.420 (val F1=0.4951)
  Directional -> Accuracy: 0.5676, MCC: 0.1737, F1: 0.6522

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.48583 | val 1.31339
  Epoch 020 - train 0.31433 | val 2.24840
  Epoch 021 - train 0.30096 | val 1.85469
  Classification -> best τ=0.505 (val F1=0.2914)
  Directional -> Accuracy: 0.5000, MCC: -0.0204, F1: 0.3529

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.54181 | val 0.93069
  Epoch 020 - train 0.41086 | val 0.89135
  Epoch 026 - train 0.34498 | val 1.06849
  Classification -> best τ=0.415 (val F1=0.4538)
  Directional -> Accuracy: 0.4697, MCC: -0.0156, F1: 0.4262

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.43098 | val 1.44656
  Epoch 020 - train 0.32687 | val 1.58440
  Epoch 021 - train 0.26663 | val 1.53526
  Classification -> best τ=0.560 (val F1=0.2568)
  Directional -> Accuracy: 0.6429, MCC: 0.3127, F1: 0.5946

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.53590 | val 1.44495
  Epoch 020 - train 0.43108 | val 3.44433
  Epoch 021 - train 0.43135 | val 2.77835
  Classification -> best τ=0.360 (val F1=0.3567)
  Directional -> Accuracy: 0.5000, MCC: 0.0731, F1: 0.6216

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.43098 | val 2.30504
  Epoch 020 - train 0.28278 | val 5.42744
  Epoch 021 - train 0.23926 | val 5.06580
  Classification -> best τ=0.490 (val F1=0.4335)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.48301 | val 0.68697
  Epoch 020 - train 0.33116 | val 1.26477
  Epoch 026 - train 0.24003 | val 1.64639
  Classification -> best τ=0.415 (val F1=0.3973)
  Directional -> Accuracy: 0.4082, MCC: 0.0264, F1: 0.5246

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.43806 | val 1.16407
  Epoch 020 - train 0.31720 | val 2.65610
  Epoch 021 - train 0.31718 | val 3.07187
  Classification -> best τ=0.520 (val F1=0.0585)
  Directional -> Accuracy: 0.5135, MCC: 0.2204, F1: 0.1818

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.56846 | val 1.16625
  Epoch 020 - train 0.46198 | val 2.27746
  Epoch 021 - train 0.45121 | val 2.66675
  Classification -> best τ=0.590 (val F1=0.2568)
  Directional -> Accuracy: 0.5467, MCC: 0.0956, F1: 0.4333

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.50835 | val 1.10932
  Epoch 020 - train 0.30626 | val 2.17473
  Epoch 023 - train 0.29333 | val 1.90820
  Classification -> best τ=0.435 (val F1=0.3435)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.6857

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.42537 | val 1.21413
  Epoch 020 - train 0.29324 | val 1.95274
  Epoch 021 - train 0.30316 | val 2.10213
  Classification -> best τ=0.490 (val F1=0.2282)
  Directional -> Accuracy: 0.6047, MCC: 0.1753, F1: 0.7018

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.42058 | val 0.76168
  Epoch 020 - train 0.23431 | val 0.95594
  Epoch 030 - train 0.17704 | val 1.48868
  Classification -> best τ=0.250 (val F1=0.5514)
  Directional -> Accuracy: 0.3673, MCC: -0.1462, F1: 0.5231

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.54684 | val 3.02833
  Epoch 020 - train 0.47683 | val 2.95768
  Epoch 021 - train 0.47057 | val 3.62472
  Classification -> best τ=0.460 (val F1=0.1623)
  Directional -> Accuracy: 0.5357, MCC: 0.0716, F1: 0.5517

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.57103 | val 1.68308
  Epoch 020 - train 0.42274 | val 2.39206
  Epoch 021 - train 0.42427 | val 2.32715
  Classification -> best τ=0.620 (val F1=0.2157)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.0000


[I 2026-02-25 01:51:33,857] Trial 139 finished with value: 0.2612517345719242 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 32, 'learning_rate': 0.002442098585966369, 'weight_decay': 0.00017610641464933227, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.6229761388753897, 'early_stopping_min_delta': 0.0026700631996671277}. Best is trial 32 with value: 0.2908549754956826.

  Classification -> best τ=0.445 (val F1=0.1201)
  Directional -> Accuracy: 0.4918, MCC: -0.0512, F1: 0.2791

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2612517345719242
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.64710 | val 0.77134
  Epoch 013 - train 0.62688 | val 0.71779
  Classification -> best τ=0.585 (val F1=0.2510)
  Directional -> Accuracy: 0.5526, MCC: 0.0412, F1: 0.2273

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.63863 | val 0.88309
  Epoch 011 - train 0.59144 | val 0.84361
  Classification -> best τ=0.420 (val F1=0.1870)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.67917 | val 0.70761
  Epoch 012 - train 0.64968 | val 0.72452
  Classification -> best τ=0.360 (val F1=0.4500)
  Directional -> Accuracy: 0.5319, MCC: 0.0135, F1: 0.6857

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.64413 | val 1.37254
  Epoch 012 - train 0.62666 | val 1.25331
  Classification -> best τ=0.410 (val F1=0.2831)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.61987 | val 0.89759
  Epoch 016 - train 0.57318 | val 0.86656
  Classification -> best τ=0.540 (val F1=0.4513)
  Directional -> Accuracy: 0.5294, MCC: 0.0119, F1: 0.6842

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.60045 | val 0.85960
  Epoch 020 - train 0.49416 | val 1.28672
  Epoch 025 - train 0.46327 | val 1.18487
  Classification -> best τ=0.340 (val F1=0.2357)
  Directional -> Accuracy: 0.5106, MCC: 0.0509, F1: 0.6349

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.70650 | val 0.74332
  Epoch 011 - train 0.66536 | val 0.70297
  Classification -> best τ=0.500 (val F1=0.2227)
  Directional -> Accuracy: 0.6087, MCC: 0.1467, F1: 0.0690

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.64856 | val 1.08791
  Epoch 011 - train 0.52775 | val 0.99806
  Classification -> best τ=0.485 (val F1=0.1590)
  Directional -> Accuracy: 0.5581, MCC: 0.0089, F1: 0.2400

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.69237 | val 0.98378
  Epoch 014 - train 0.62790 | val 1.49385
  Classification -> best τ=0.340 (val F1=0.4605)
  Directional -> Accuracy: 0.5510, MCC: 0.0212, F1: 0.0833

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.58913 | val 0.76049
  Epoch 011 - train 0.55637 | val 0.79229
  Classification -> best τ=0.375 (val F1=0.2904)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.60137 | val 2.13543
  Epoch 012 - train 0.61191 | val 2.18699
  Classification -> best τ=0.615 (val F1=0.3537)
  Directional -> Accuracy: 0.5600, MCC: 0.1143, F1: 0.5217

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.59962 | val 1.07679
  Epoch 011 - train 0.63033 | val 1.21512
  Classification -> best τ=0.445 (val F1=0.2243)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6506

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.60021 | val 0.99529
  Epoch 011 - train 0.61242 | val 0.95594
  Classification -> best τ=0.450 (val F1=0.2323)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.70912 | val 0.73187
  Epoch 015 - train 0.67292 | val 0.91576
  Classification -> best τ=0.445 (val F1=0.3282)
  Directional -> Accuracy: 0.5167, MCC: 0.0765, F1: 0.6667

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.60547 | val 0.76685
  Epoch 011 - train 0.66415 | val 0.90878
  Classification -> best τ=0.600 (val F1=0.1670)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.63991 | val 0.75233
  Epoch 013 - train 0.61736 | val 0.81140
  Classification -> best τ=0.425 (val F1=0.4666)
  Directional -> Accuracy: 0.6232, MCC: 0.2376, F1: 0.6667

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.65058 | val 2.29732
  Epoch 011 - train 0.62147 | val 2.15634
  Classification -> best τ=0.410 (val F1=0.0046)
  Directional -> Accuracy: 0.6102, MCC: 0.1285, F1: 0.7089

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.64958 | val 1.68732
  Epoch 011 - train 0.63445 | val 1.61595
  Classification -> best τ=0.555 (val F1=0.0946)
  Directional -> Accuracy: 0.5067, MCC: -0.0221, F1: 0.5843

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.70441 | val 1.25316
  Epoch 012 - train 0.64597 | val 1.58452
  Classification -> best τ=0.430 (val F1=0.3346)
  Directional -> Accuracy: 0.4769, MCC: 0.0998, F1: 0.2917

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.64313 | val 0.68186
  Epoch 016 - train 0.60599 | val 0.76194
  Classification -> best τ=0.610 (val F1=0.2812)
  Directional -> Accuracy: 0.4800, MCC: 0.1507, F1: 0.0930

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.60898 | val 1.29882
  Epoch 020 - train 0.49743 | val 0.82716
  Epoch 023 - train 0.49715 | val 0.71927
  Classification -> best τ=0.590 (val F1=0.3801)
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.68348 | val 0.77090
  Epoch 011 - train 0.65651 | val 0.79948
  Classification -> best τ=0.540 (val F1=0.2678)
  Directional -> Accuracy: 0.5152, MCC: 0.0492, F1: 0.2000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.68896 | val 0.83482
  Epoch 013 - train 0.60384 | val 0.83198
  Classification -> best τ=0.610 (val F1=0.2864)
  Directional -> Accuracy: 0.4828, MCC: 0.0251, F1: 0.4000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.63734 | val 0.90380
  Epoch 011 - train 0.65122 | val 1.05888
  Classification -> best τ=0.420 (val F1=0.0835)
  Directional -> Accuracy: 0.5231, MCC: 0.0776, F1: 0.6076

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.64448 | val 0.77602
  Epoch 017 - train 0.56932 | val 0.84967
  Classification -> best τ=0.395 (val F1=0.3953)
  Directional -> Accuracy: 0.5893, MCC: 0.1723, F1: 0.6230

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.58444 | val 0.87973
  Epoch 011 - train 0.61851 | val 0.83557
  Classification -> best τ=0.550 (val F1=0.1048)
  Directional -> Accuracy: 0.3696, MCC: -0.2756, F1: 0.2927

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.64774 | val 0.68411
  Epoch 019 - train 0.60903 | val 0.69701
  Classification -> best τ=0.660 (val F1=0.2402)
  Directional -> Accuracy: 0.4286, MCC: -0.0807, F1: 0.2941

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.63365 | val 0.77196
  Epoch 013 - train 0.61742 | val 0.81867
  Classification -> best τ=0.495 (val F1=0.2506)
  Directional -> Accuracy: 0.4912, MCC: 0.2083, F1: 0.1714

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.65553 | val 1.03889
  Epoch 013 - train 0.64027 | val 0.96992
  Classification -> best τ=0.520 (val F1=0.3518)
  Directional -> Accuracy: 0.4634, MCC: -0.1617, F1: 0.6071

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.67256 | val 0.71169
  Epoch 018 - train 0.62576 | val 0.77099
  Classification -> best τ=0.470 (val F1=0.2842)
  Directional -> Accuracy: 0.5116, MCC: 0.0288, F1: 0.5532

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.71581 | val 0.74583
  Epoch 012 - train 0.63000 | val 0.79010
  Classification -> best τ=0.615 (val F1=0.1204)
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.62674 | val 0.96908
  Epoch 014 - train 0.60979 | val 0.82735
  Classification -> best τ=0.575 (val F1=0.3465)
  Directional -> Accuracy: 0.3600, MCC: -0.3092, F1: 0.4483

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.62249 | val 0.67755
  Epoch 011 - train 0.62736 | val 0.78659
  Classification -> best τ=0.505 (val F1=0.3104)
  Directional -> Accuracy: 0.5342, MCC: 0.1760, F1: 0.3929

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.61599 | val 0.72950
  Epoch 011 - train 0.63162 | val 0.71881
  Classification -> best τ=0.445 (val F1=0.1604)
  Directional -> Accuracy: 0.4595, MCC: -0.1712, F1: 0.6296

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.72215 | val 1.18646
  Epoch 013 - train 0.61452 | val 1.01845
  Classification -> best τ=0.560 (val F1=0.3627)
  Directional -> Accuracy: 0.5455, MCC: 0.0820, F1: 0.2857

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.63735 | val 0.74234
  Epoch 011 - train 0.60266 | val 0.83353
  Classification -> best τ=0.380 (val F1=0.3001)
  Directional -> Accuracy: 0.5455, MCC: 0.0344, F1: 0.6429

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.59028 | val 2.26017
  Epoch 011 - train 0.68142 | val 2.15043
  Classification -> best τ=0.540 (val F1=0.2568)
  Directional -> Accuracy: 0.5238, MCC: 0.0674, F1: 0.4444

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.65887 | val 1.33679
  Epoch 014 - train 0.60936 | val 1.65479
  Classification -> best τ=0.350 (val F1=0.4185)
  Directional -> Accuracy: 0.4821, MCC: 0.0625, F1: 0.6329

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.55467 | val 1.61535
  Epoch 011 - train 0.56531 | val 2.16801
  Classification -> best τ=0.520 (val F1=0.3370)
  Directional -> Accuracy: 0.5652, MCC: -0.1709, F1: 0.7222

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.63367 | val 0.75226
  Epoch 020 - train 0.54051 | val 0.65275
  Epoch 025 - train 0.61831 | val 0.65594
  Classification -> best τ=0.290 (val F1=0.5125)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.61061 | val 0.69836
  Epoch 015 - train 0.64464 | val 0.87783
  Classification -> best τ=0.545 (val F1=0.2623)
  Directional -> Accuracy: 0.4324, MCC: -0.1115, F1: 0.1600

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.63332 | val 0.85060
  Epoch 013 - train 0.59412 | val 0.85240
  Classification -> best τ=0.310 (val F1=0.3914)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.67513 | val 0.67390
  Epoch 018 - train 0.59657 | val 0.93033
  Classification -> best τ=0.370 (val F1=0.6146)
  Directional -> Accuracy: 0.5000, MCC: 0.0077, F1: 0.4651

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.63139 | val 0.89519
  Epoch 019 - train 0.58526 | val 1.48110
  Classification -> best τ=0.465 (val F1=0.4090)
  Directional -> Accuracy: 0.5349, MCC: 0.0468, F1: 0.6000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.66678 | val 0.98258
  Epoch 016 - train 0.60454 | val 0.94267
  Classification -> best τ=0.610 (val F1=0.5689)
  Directional -> Accuracy: 0.3673, MCC: -0.1814, F1: 0.5373

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.66978 | val 1.93255
  Epoch 012 - train 0.66419 | val 1.55811
  Classification -> best τ=0.680 (val F1=0.2999)
  Directional -> Accuracy: 0.5000, MCC: 0.0731, F1: 0.2632

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.66596 | val 0.87094
  Epoch 012 - train 0.62384 | val 1.02891
  Classification -> best τ=0.510 (val F1=0.3250)
  Directional -> Accuracy: 0.5357, MCC: 0.0625, F1: 0.4091

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.65572 | val 1.22273
  Epoch 014 - train 0.66930 | val 1.43499
  Classification -> best τ=0.415 (val F1=0.1223)
  Directional -> Accuracy: 0.5000, MCC: -0.0521, F1: 0.6494

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.61114 | val 1.83204
  Epoch 012 - train 0.61587 | val 2.11923
  Classification -> best τ=0.470 (val F1=0.1833)
  Directional -> Accuracy: 0.5536, MCC: 0.1995, F1: 0.6988

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.66172 | val 0.70945

[I 2026-02-25 01:53:15,835] Trial 140 finished with value: 0.29322408230766744 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 0.0037454516482407652, 'weight_decay': 0.00014076411729023995, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.49791247206070705, 'early_stopping_min_delta': 0.0018242255551884497}. Best is trial 140 with value: 0.29322408230766744.

  Epoch 015 - train 0.62319 | val 1.51688
  Classification -> best τ=0.355 (val F1=0.2367)
  Directional -> Accuracy: 0.6557, MCC: 0.3111, F1: 0.6441

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.29322408230766744
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.65730 | val 0.90187
  Epoch 012 - train 0.61015 | val 0.99807
  Classification -> best τ=0.555 (val F1=0.2627)
  Directional -> Accuracy: 0.5526, MCC: 0.0633, F1: 0.3704

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.63381 | val 0.68518
  Epoch 020 - train 0.56349 | val 0.75698
  Classification -> best τ=0.425 (val F1=0.2385)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.63632 | val 0.71128
  Epoch 013 - train 0.61582 | val 0.69903
  Classification -> best τ=0.405 (val F1=0.4459)
  Directional -> Accuracy: 0.5319, MCC: 0.0135, F1: 0.6857

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.64809 | val 1.58511
  Epoch 012 - train 0.65645 | val 1.45397
  Classification -> best τ=0.505 (val F1=0.2009)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.63877 | val 1.38701
  Epoch 014 - train 0.64787 | val 1.39816
  Classification -> best τ=0.655 (val F1=0.4220)
  Directional -> Accuracy: 0.6275, MCC: 0.2508, F1: 0.6545

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.65961 | val 0.68881
  Epoch 017 - train 0.55304 | val 0.70655
  Classification -> best τ=0.630 (val F1=0.2887)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.70161 | val 0.76220
  Epoch 011 - train 0.69941 | val 0.76254
  Classification -> best τ=0.540 (val F1=0.1805)
  Directional -> Accuracy: 0.5942, MCC: 0.0331, F1: 0.0667

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.62021 | val 1.03341
  Epoch 012 - train 0.64449 | val 0.78608
  Classification -> best τ=0.410 (val F1=0.1338)
  Directional -> Accuracy: 0.4884, MCC: -0.1634, F1: 0.1538

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.61746 | val 1.17210
  Epoch 012 - train 0.59216 | val 1.22982
  Classification -> best τ=0.415 (val F1=0.1939)
  Directional -> Accuracy: 0.6735, MCC: 0.3467, F1: 0.6522

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.59306 | val 1.03823
  Epoch 011 - train 0.59232 | val 0.96012
  Classification -> best τ=0.400 (val F1=0.2357)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.64734 | val 1.83159
  Epoch 011 - train 0.62689 | val 1.38963
  Classification -> best τ=0.565 (val F1=0.1375)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.61389 | val 1.42120
  Epoch 011 - train 0.62319 | val 1.90625
  Classification -> best τ=0.370 (val F1=0.2969)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.60020 | val 0.97563
  Epoch 013 - train 0.56608 | val 0.94209
  Classification -> best τ=0.660 (val F1=0.2288)
  Directional -> Accuracy: 0.5476, MCC: 0.0214, F1: 0.0952

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.66888 | val 0.76927
  Epoch 020 - train 0.56419 | val 0.64702
  Epoch 022 - train 0.62701 | val 0.91437
  Classification -> best τ=0.430 (val F1=0.3026)
  Directional -> Accuracy: 0.5167, MCC: 0.0467, F1: 0.6420

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.64973 | val 1.44030
  Epoch 014 - train 0.59190 | val 2.11452
  Classification -> best τ=0.690 (val F1=0.2673)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.62354 | val 0.81830
  Epoch 014 - train 0.63916 | val 0.83212
  Classification -> best τ=0.440 (val F1=0.3197)
  Directional -> Accuracy: 0.5362, MCC: 0.0716, F1: 0.5556

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.63622 | val 1.81654
  Epoch 011 - train 0.63972 | val 2.37668
  Classification -> best τ=0.270 (val F1=0.1336)
  Directional -> Accuracy: 0.6271, MCC: 0.0492, F1: 0.7660

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.65683 | val 1.15543
  Epoch 011 - train 0.65574 | val 1.20979
  Classification -> best τ=0.500 (val F1=0.0777)
  Directional -> Accuracy: 0.5067, MCC: 0.0675, F1: 0.4932

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.64407 | val 1.63955
  Epoch 012 - train 0.64071 | val 1.53796
  Classification -> best τ=0.545 (val F1=0.3477)
  Directional -> Accuracy: 0.4462, MCC: -0.0140, F1: 0.3077

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.64066 | val 0.76000
  Epoch 016 - train 0.59891 | val 1.21933
  Classification -> best τ=0.350 (val F1=0.3152)
  Directional -> Accuracy: 0.4933, MCC: -0.0443, F1: 0.5778

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.62420 | val 0.65489
  Epoch 020 - train 0.55773 | val 0.69286
  Epoch 023 - train 0.53714 | val 0.74427
  Classification -> best τ=0.415 (val F1=0.3740)
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.65967 | val 0.92310
  Epoch 011 - train 0.63166 | val 1.26265
  Classification -> best τ=0.445 (val F1=0.2390)
  Directional -> Accuracy: 0.5909, MCC: 0.1819, F1: 0.5846

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.68887 | val 0.69710
  Epoch 020 - train 0.62431 | val 1.07615
  Epoch 021 - train 0.58887 | val 1.12976
  Classification -> best τ=0.540 (val F1=0.2971)
  Directional -> Accuracy: 0.4828, MCC: 0.0658, F1: 0.3182

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.68724 | val 0.87372
  Epoch 013 - train 0.62526 | val 1.47700
  Classification -> best τ=0.515 (val F1=0.1507)
  Directional -> Accuracy: 0.5538, MCC: 0.1173, F1: 0.5797

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.69644 | val 0.69113
  Epoch 020 - train 0.55086 | val 0.77856
  Epoch 022 - train 0.55263 | val 0.85525
  Classification -> best τ=0.520 (val F1=0.3951)
  Directional -> Accuracy: 0.4464, MCC: -0.0440, F1: 0.2051

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.75959 | val 0.68215
  Epoch 020 - train 0.61200 | val 0.89951
  Classification -> best τ=0.300 (val F1=0.3669)
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.67633 | val 0.69593
  Epoch 018 - train 0.62209 | val 0.87404
  Classification -> best τ=0.595 (val F1=0.1936)
  Directional -> Accuracy: 0.5238, MCC: 0.2161, F1: 0.3333

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.57689 | val 1.04299
  Epoch 012 - train 0.58891 | val 0.98393
  Classification -> best τ=0.545 (val F1=0.1940)
  Directional -> Accuracy: 0.4912, MCC: 0.2083, F1: 0.1714

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.71634 | val 0.66350
  Epoch 019 - train 0.51864 | val 1.21556
  Classification -> best τ=0.420 (val F1=0.4345)
  Directional -> Accuracy: 0.5854, MCC: 0.1890, F1: 0.7119

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.62237 | val 0.77880
  Epoch 015 - train 0.55944 | val 0.99675
  Classification -> best τ=0.550 (val F1=0.2814)
  Directional -> Accuracy: 0.5581, MCC: 0.1366, F1: 0.6275

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.67754 | val 0.79115
  Epoch 012 - train 0.61817 | val 0.97340
  Classification -> best τ=0.510 (val F1=0.1937)
  Directional -> Accuracy: 0.5581, MCC: 0.1655, F1: 0.7077

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.59428 | val 0.87285
  Epoch 012 - train 0.61523 | val 1.15544
  Classification -> best τ=0.585 (val F1=0.2399)
  Directional -> Accuracy: 0.4400, MCC: -0.0963, F1: 0.3333

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.63940 | val 0.70760
  Epoch 018 - train 0.57578 | val 1.52327
  Classification -> best τ=0.525 (val F1=0.3824)
  Directional -> Accuracy: 0.5342, MCC: 0.1050, F1: 0.5000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.62767 | val 1.12101
  Epoch 011 - train 0.64303 | val 1.25155
  Classification -> best τ=0.415 (val F1=0.2025)
  Directional -> Accuracy: 0.5676, MCC: 0.1940, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.57540 | val 0.89699
  Epoch 011 - train 0.65522 | val 1.02417
  Classification -> best τ=0.515 (val F1=0.1902)
  Directional -> Accuracy: 0.5682, MCC: 0.2471, F1: 0.6780

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.65130 | val 0.83441
  Epoch 017 - train 0.60461 | val 0.92625
  Classification -> best τ=0.185 (val F1=0.2778)
  Directional -> Accuracy: 0.6061, MCC: 0.1674, F1: 0.7400

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.62211 | val 1.44627
  Epoch 012 - train 0.60252 | val 1.65708
  Classification -> best τ=0.605 (val F1=0.2486)
  Directional -> Accuracy: 0.4762, MCC: -0.0155, F1: 0.1538

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.70021 | val 1.13025
  Epoch 011 - train 0.65587 | val 1.35745
  Classification -> best τ=0.400 (val F1=0.2622)
  Directional -> Accuracy: 0.5357, MCC: 0.1040, F1: 0.5938

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.67732 | val 1.79430
  Epoch 012 - train 0.56753 | val 2.12287
  Classification -> best τ=0.435 (val F1=0.2504)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.60058 | val 0.62871
  Epoch 020 - train 0.57688 | val 0.66867
  Epoch 027 - train 0.52751 | val 0.81082
  Classification -> best τ=0.240 (val F1=0.5247)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.57078 | val 0.73377
  Epoch 011 - train 0.58895 | val 0.83926
  Classification -> best τ=0.470 (val F1=0.3320)
  Directional -> Accuracy: 0.3514, MCC: -0.3301, F1: 0.0769

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.64060 | val 1.02474
  Epoch 012 - train 0.63199 | val 0.96296
  Classification -> best τ=0.430 (val F1=0.2802)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.64922 | val 0.70295
  Epoch 016 - train 0.63012 | val 1.33991
  Classification -> best τ=0.375 (val F1=0.2996)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.6857

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.60399 | val 0.84009
  Epoch 017 - train 0.49224 | val 1.27651
  Classification -> best τ=0.685 (val F1=0.5895)
  Directional -> Accuracy: 0.5349, MCC: 0.0905, F1: 0.5238

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.68747 | val 0.74799
  Epoch 020 - train 0.56535 | val 1.07715
  Epoch 022 - train 0.59678 | val 0.89807
  Classification -> best τ=0.500 (val F1=0.4371)
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.67365 | val 1.71429
  Epoch 011 - train 0.68245 | val 1.64409
  Classification -> best τ=0.530 (val F1=0.1216)
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.67985 | val 1.04060
  Epoch 011 - train 0.63359 | val 1.43078
  Classification -> best τ=0.535 (val F1=0.4276)
  Directional -> Accuracy: 0.5000, MCC: 0.0330, F1: 0.6216

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.62965 | val 1.09966
  Epoch 015 - train 0.65399 | val 1.39500
  Classification -> best τ=0.555 (val F1=0.1348)
  Directional -> Accuracy: 0.5741, MCC: 0.1436, F1: 0.6230

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.64496 | val 1.58443
  Epoch 011 - train 0.62067 | val 1.65971
  Classification -> best τ=0.515 (val F1=0.1168)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.62569 | val 0.73803

[I 2026-02-25 01:55:03,359] Trial 141 finished with value: 0.27555881044939445 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 0.0036272035771275335, 'weight_decay': 0.0001455908559226, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.48382802741312125, 'early_stopping_min_delta': 0.0018116143381320306}. Best is trial 140 with value: 0.29322408230766744.

  Epoch 016 - train 0.60581 | val 0.85121
  Classification -> best τ=0.355 (val F1=0.3103)
  Directional -> Accuracy: 0.5082, MCC: 0.0940, F1: 0.6429

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.27555881044939445
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.61854 | val 1.18966
  Epoch 011 - train 0.62731 | val 0.83241
  Classification -> best τ=0.485 (val F1=0.1635)
  Directional -> Accuracy: 0.5132, MCC: 0.1019, F1: 0.6022

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.64240 | val 0.77020
  Epoch 011 - train 0.62957 | val 0.76841
  Classification -> best τ=0.430 (val F1=0.1150)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.68252 | val 0.75848
  Epoch 012 - train 0.65015 | val 0.69446
  Classification -> best τ=0.455 (val F1=0.2871)
  Directional -> Accuracy: 0.5957, MCC: 0.1864, F1: 0.6885

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.62750 | val 2.42742
  Epoch 012 - train 0.62615 | val 2.24498
  Classification -> best τ=0.365 (val F1=0.1698)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.62553 | val 0.73594
  Epoch 012 - train 0.54697 | val 0.80632
  Classification -> best τ=0.510 (val F1=0.4427)
  Directional -> Accuracy: 0.4902, MCC: -0.0331, F1: 0.5517

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.57360 | val 0.72136
  Epoch 015 - train 0.50325 | val 1.81537
  Classification -> best τ=0.415 (val F1=0.2928)
  Directional -> Accuracy: 0.5745, MCC: 0.2469, F1: 0.6875

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.63980 | val 0.97625
  Epoch 011 - train 0.70245 | val 0.83671
  Classification -> best τ=0.495 (val F1=0.2005)
  Directional -> Accuracy: 0.4493, MCC: -0.0631, F1: 0.4571

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.54765 | val 0.65666
  Epoch 015 - train 0.48473 | val 0.74875
  Classification -> best τ=0.275 (val F1=0.1752)
  Directional -> Accuracy: 0.4186, MCC: -0.0364, F1: 0.5763

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.61561 | val 1.53123
  Epoch 012 - train 0.53699 | val 2.00045
  Classification -> best τ=0.390 (val F1=0.2820)
  Directional -> Accuracy: 0.6531, MCC: 0.2961, F1: 0.6047

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.55914 | val 0.88979
  Epoch 011 - train 0.57438 | val 0.80224
  Classification -> best τ=0.425 (val F1=0.2999)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.57644 | val 1.76880
  Epoch 011 - train 0.58103 | val 1.18832
  Classification -> best τ=0.560 (val F1=0.2778)
  Directional -> Accuracy: 0.5800, MCC: 0.1394, F1: 0.4324

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.60797 | val 1.50799
  Epoch 011 - train 0.56070 | val 1.91337
  Classification -> best τ=0.445 (val F1=0.2945)
  Directional -> Accuracy: 0.5517, MCC: 0.1037, F1: 0.5667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.61198 | val 0.94386
  Epoch 012 - train 0.55842 | val 1.32823
  Classification -> best τ=0.390 (val F1=0.1908)
  Directional -> Accuracy: 0.4762, MCC: -0.0026, F1: 0.5600

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.66219 | val 0.77591
  Epoch 014 - train 0.60511 | val 0.87841
  Classification -> best τ=0.405 (val F1=0.2667)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6512

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.58016 | val 1.36940
  Epoch 012 - train 0.58090 | val 3.73413
  Classification -> best τ=0.595 (val F1=0.2673)
  Directional -> Accuracy: 0.5192, MCC: 0.0416, F1: 0.5098

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.64822 | val 0.79841
  Epoch 014 - train 0.58674 | val 1.15554
  Classification -> best τ=0.395 (val F1=0.2885)
  Directional -> Accuracy: 0.5652, MCC: 0.1088, F1: 0.6667

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.62568 | val 2.54298
  Epoch 011 - train 0.63119 | val 2.21553
  Classification -> best τ=0.655 (val F1=0.1303)
  Directional -> Accuracy: 0.3729, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.61644 | val 1.65870
  Epoch 011 - train 0.61465 | val 1.65076
  Classification -> best τ=0.430 (val F1=0.1733)
  Directional -> Accuracy: 0.6000, MCC: 0.1231, F1: 0.7000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.61514 | val 1.66174
  Epoch 011 - train 0.62576 | val 1.87363
  Classification -> best τ=0.540 (val F1=0.2535)
  Directional -> Accuracy: 0.4769, MCC: 0.0619, F1: 0.3462

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.61253 | val 0.73754
  Epoch 014 - train 0.61435 | val 0.76139
  Classification -> best τ=0.485 (val F1=0.3497)
  Directional -> Accuracy: 0.4667, MCC: 0.1059, F1: 0.0476

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.59116 | val 0.98149
  Epoch 017 - train 0.52086 | val 1.16422
  Classification -> best τ=0.415 (val F1=0.3740)
  Directional -> Accuracy: 0.5106, MCC: 0.2404, F1: 0.3784

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.66009 | val 1.04916
  Epoch 011 - train 0.61983 | val 1.05705
  Classification -> best τ=0.530 (val F1=0.0747)
  Directional -> Accuracy: 0.4545, MCC: -0.1476, F1: 0.1000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.63866 | val 0.81557
  Epoch 012 - train 0.66676 | val 0.75303
  Classification -> best τ=0.565 (val F1=0.2710)
  Directional -> Accuracy: 0.4310, MCC: -0.0263, F1: 0.0571

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.65166 | val 0.80998
  Epoch 019 - train 0.60325 | val 0.93879
  Classification -> best τ=0.440 (val F1=0.2973)
  Directional -> Accuracy: 0.4462, MCC: -0.1051, F1: 0.5814

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.57529 | val 0.75500
  Epoch 018 - train 0.51634 | val 0.84766
  Classification -> best τ=0.570 (val F1=0.4057)
  Directional -> Accuracy: 0.4643, MCC: 0.0541, F1: 0.1176

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.63190 | val 1.51423
  Epoch 011 - train 0.53533 | val 1.88843
  Classification -> best τ=0.645 (val F1=0.1251)
  Directional -> Accuracy: 0.3043, MCC: -0.3893, F1: 0.2727

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.65668 | val 0.93810
  Epoch 019 - train 0.57186 | val 1.27689
  Classification -> best τ=0.545 (val F1=0.2282)
  Directional -> Accuracy: 0.4762, MCC: 0.0786, F1: 0.2667

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.59376 | val 0.91729
  Epoch 011 - train 0.59070 | val 1.27593
  Classification -> best τ=0.490 (val F1=0.1667)
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.58134 | val 0.77634
  Epoch 019 - train 0.57403 | val 0.89501
  Classification -> best τ=0.450 (val F1=0.3278)
  Directional -> Accuracy: 0.4878, MCC: -0.2104, F1: 0.6557

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.59478 | val 0.70413
  Epoch 014 - train 0.56605 | val 1.27923
  Classification -> best τ=0.475 (val F1=0.2842)
  Directional -> Accuracy: 0.4884, MCC: -0.0197, F1: 0.5217

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.61828 | val 0.91697
  Epoch 013 - train 0.57271 | val 0.82926
  Classification -> best τ=0.490 (val F1=0.2517)
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.55156 | val 0.90560
  Epoch 011 - train 0.54033 | val 1.05340
  Classification -> best τ=0.525 (val F1=0.1679)
  Directional -> Accuracy: 0.4600, MCC: -0.1170, F1: 0.5574

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.62841 | val 0.83281
  Epoch 016 - train 0.56180 | val 0.92778
  Classification -> best τ=0.405 (val F1=0.3451)
  Directional -> Accuracy: 0.5753, MCC: 0.1768, F1: 0.5634

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.61708 | val 1.31500
  Epoch 012 - train 0.60341 | val 1.06047
  Classification -> best τ=0.420 (val F1=0.4276)
  Directional -> Accuracy: 0.5405, MCC: 0.0968, F1: 0.6047

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.68810 | val 0.90352
  Epoch 013 - train 0.56147 | val 1.14930
  Classification -> best τ=0.515 (val F1=0.2178)
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.62179 | val 0.75661
  Epoch 014 - train 0.58028 | val 0.76095
  Classification -> best τ=0.370 (val F1=0.3346)
  Directional -> Accuracy: 0.4242, MCC: -0.0271, F1: 0.0500

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.57000 | val 1.81196
  Epoch 013 - train 0.50811 | val 3.24306
  Classification -> best τ=0.525 (val F1=0.2357)
  Directional -> Accuracy: 0.6429, MCC: 0.3290, F1: 0.5714

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.61205 | val 1.19091
  Epoch 011 - train 0.58040 | val 1.49836
  Classification -> best τ=0.365 (val F1=0.4506)
  Directional -> Accuracy: 0.5000, MCC: 0.0910, F1: 0.6316

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.54424 | val 2.05296
  Epoch 014 - train 0.63617 | val 2.40668
  Classification -> best τ=0.530 (val F1=0.3771)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.61940 | val 0.67886
  Epoch 020 - train 0.52208 | val 0.65520
  Epoch 022 - train 0.48949 | val 0.70241
  Classification -> best τ=0.320 (val F1=0.3182)
  Directional -> Accuracy: 0.3469, MCC: -0.1894, F1: 0.5152

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.60132 | val 0.72557
  Epoch 011 - train 0.63215 | val 0.71649
  Classification -> best τ=0.490 (val F1=0.2082)
  Directional -> Accuracy: 0.5405, MCC: 0.1105, F1: 0.4848

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.58788 | val 1.06216
  Epoch 012 - train 0.61720 | val 1.06457
  Classification -> best τ=0.350 (val F1=0.3707)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.61351 | val 0.74666
  Epoch 014 - train 0.66134 | val 0.80332
  Classification -> best τ=0.475 (val F1=0.2933)
  Directional -> Accuracy: 0.5000, MCC: 0.0266, F1: 0.3429

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.67221 | val 0.90425
  Epoch 011 - train 0.57673 | val 0.95836
  Classification -> best τ=0.580 (val F1=0.4166)
  Directional -> Accuracy: 0.5116, MCC: 0.0924, F1: 0.4000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.65014 | val 0.69025
  Epoch 013 - train 0.55086 | val 1.00499
  Classification -> best τ=0.610 (val F1=0.6290)
  Directional -> Accuracy: 0.3878, MCC: -0.0861, F1: 0.5161

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.70468 | val 1.77221
  Epoch 016 - train 0.58163 | val 1.71068
  Classification -> best τ=0.340 (val F1=0.2958)
  Directional -> Accuracy: 0.5714, MCC: 0.1269, F1: 0.6842

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.66496 | val 1.00203
  Epoch 011 - train 0.61402 | val 0.84921
  Classification -> best τ=0.570 (val F1=0.2830)
  Directional -> Accuracy: 0.5179, MCC: 0.0357, F1: 0.5091

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.63601 | val 1.11794
  Epoch 011 - train 0.59096 | val 1.23618
  Classification -> best τ=0.455 (val F1=0.1626)
  Directional -> Accuracy: 0.6111, MCC: 0.2202, F1: 0.6316

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.65284 | val 1.60778
  Epoch 011 - train 0.64500 | val 2.24542
  Classification -> best τ=0.440 (val F1=0.0629)
  Directional -> Accuracy: 0.4107, MCC: -0.1758, F1: 0.3265

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.63363 | val 2.20084

[I 2026-02-25 01:56:42,614] Trial 142 finished with value: 0.2717818163220858 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.6000000000000001, 'batch_size': 32, 'learning_rate': 0.0036347066388829068, 'weight_decay': 0.0001556310094984808, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.48171521536327144, 'early_stopping_min_delta': 0.0017858613411628507}. Best is trial 140 with value: 0.29322408230766744.

  Epoch 014 - train 0.56739 | val 3.35119
  Classification -> best τ=0.425 (val F1=0.2651)
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2717818163220858
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.64558 | val 0.78621
  Epoch 012 - train 0.64565 | val 0.94954
  Classification -> best τ=0.530 (val F1=0.2919)
  Directional -> Accuracy: 0.5263, MCC: -0.0267, F1: 0.2174

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.61181 | val 0.80942
  Epoch 011 - train 0.61823 | val 0.78537
  Classification -> best τ=0.515 (val F1=0.1036)
  Directional -> Accuracy: 0.5778, MCC: 0.0732, F1: 0.6984

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.63628 | val 0.69544
  Epoch 014 - train 0.64346 | val 0.72596
  Classification -> best τ=0.480 (val F1=0.2700)
  Directional -> Accuracy: 0.6383, MCC: 0.2759, F1: 0.6531

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.66988 | val 2.57190
  Epoch 011 - train 0.69685 | val 2.32396
  Classification -> best τ=0.450 (val F1=0.1475)
  Directional -> Accuracy: 0.5200, MCC: 0.0316, F1: 0.5610

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.61781 | val 0.66944
  Epoch 015 - train 0.53899 | val 0.75070
  Classification -> best τ=0.600 (val F1=0.4158)
  Directional -> Accuracy: 0.4902, MCC: -0.0280, F1: 0.5357

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.56043 | val 0.73403
  Epoch 018 - train 0.53141 | val 0.78351
  Classification -> best τ=0.555 (val F1=0.2928)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.65438 | val 0.87217
  Epoch 012 - train 0.66439 | val 0.83563
  Classification -> best τ=0.400 (val F1=0.2233)
  Directional -> Accuracy: 0.4348, MCC: 0.1428, F1: 0.5895

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.71206 | val 1.46369
  Epoch 011 - train 0.57296 | val 1.40331
  Classification -> best τ=0.555 (val F1=0.1502)
  Directional -> Accuracy: 0.5581, MCC: 0.0573, F1: 0.3871

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.61452 | val 0.95610
  Epoch 014 - train 0.57490 | val 1.51013
  Classification -> best τ=0.405 (val F1=0.2076)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.60842 | val 0.74595
  Epoch 011 - train 0.61882 | val 0.79085
  Classification -> best τ=0.450 (val F1=0.2607)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.63565 | val 1.74384
  Epoch 015 - train 0.58067 | val 2.55299
  Classification -> best τ=0.570 (val F1=0.3094)
  Directional -> Accuracy: 0.6200, MCC: 0.2766, F1: 0.3448

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.60693 | val 1.34452
  Epoch 011 - train 0.63757 | val 1.19597
  Classification -> best τ=0.450 (val F1=0.2600)
  Directional -> Accuracy: 0.6724, MCC: 0.3467, F1: 0.6545

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.60036 | val 0.82559
  Epoch 012 - train 0.63637 | val 1.45267
  Classification -> best τ=0.640 (val F1=0.1248)
  Directional -> Accuracy: 0.5476, MCC: 0.0214, F1: 0.0952

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.67654 | val 0.86682
  Epoch 011 - train 0.67922 | val 0.80226
  Classification -> best τ=0.535 (val F1=0.3282)
  Directional -> Accuracy: 0.4833, MCC: -0.0431, F1: 0.2439

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.61400 | val 1.24684
  Epoch 011 - train 0.61268 | val 1.50800
  Classification -> best τ=0.480 (val F1=0.0891)
  Directional -> Accuracy: 0.5000, MCC: 0.0401, F1: 0.5806

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.63791 | val 1.13416
  Epoch 011 - train 0.58508 | val 0.80991
  Classification -> best τ=0.460 (val F1=0.2708)
  Directional -> Accuracy: 0.5362, MCC: 0.0000, F1: 0.6981

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.67983 | val 1.95220
  Epoch 011 - train 0.63852 | val 2.29397
  Classification -> best τ=0.400 (val F1=0.1336)
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.67245 | val 1.06798
  Epoch 013 - train 0.62983 | val 0.92771
  Classification -> best τ=0.685 (val F1=0.1923)
  Directional -> Accuracy: 0.4133, MCC: 0.0949, F1: 0.0435

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.66365 | val 1.49012
  Epoch 012 - train 0.64793 | val 1.72880
  Classification -> best τ=0.545 (val F1=0.2945)
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.64440 | val 1.09432
  Epoch 012 - train 0.62973 | val 0.96241
  Classification -> best τ=0.520 (val F1=0.2369)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.61388 | val 0.74698
  Epoch 018 - train 0.53923 | val 0.94598
  Classification -> best τ=0.510 (val F1=0.3731)
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.66243 | val 1.19031
  Epoch 013 - train 0.62476 | val 0.99872
  Classification -> best τ=0.525 (val F1=0.3177)
  Directional -> Accuracy: 0.4697, MCC: -0.0845, F1: 0.6067

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.68771 | val 0.87931
  Epoch 011 - train 0.68155 | val 0.89215
  Classification -> best τ=0.530 (val F1=0.3379)
  Directional -> Accuracy: 0.5000, MCC: 0.1008, F1: 0.3556

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.63998 | val 0.81247
  Epoch 011 - train 0.64623 | val 1.27737
  Classification -> best τ=0.500 (val F1=0.1936)
  Directional -> Accuracy: 0.5385, MCC: 0.0619, F1: 0.3478

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.65654 | val 0.65892
  Epoch 017 - train 0.57345 | val 0.68533
  Classification -> best τ=0.510 (val F1=0.4795)
  Directional -> Accuracy: 0.5714, MCC: 0.2187, F1: 0.4783

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.59573 | val 1.10043
  Epoch 011 - train 0.58137 | val 1.37343
  Classification -> best τ=0.535 (val F1=0.1048)
  Directional -> Accuracy: 0.5435, MCC: -0.1307, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.64057 | val 1.01107
  Epoch 011 - train 0.64208 | val 0.79746
  Classification -> best τ=0.550 (val F1=0.1936)
  Directional -> Accuracy: 0.5000, MCC: 0.0138, F1: 0.5116

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.62374 | val 0.93735
  Epoch 011 - train 0.60648 | val 0.88540
  Classification -> best τ=0.445 (val F1=0.3237)
  Directional -> Accuracy: 0.4737, MCC: 0.1685, F1: 0.1176

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.58425 | val 0.65538
  Epoch 020 - train 0.53251 | val 0.94706
  Epoch 021 - train 0.57944 | val 0.92267
  Classification -> best τ=0.465 (val F1=0.5913)
  Directional -> Accuracy: 0.5366, MCC: 0.0304, F1: 0.6667

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.57533 | val 0.71342
  Epoch 011 - train 0.61371 | val 0.70804
  Classification -> best τ=0.550 (val F1=0.2814)
  Directional -> Accuracy: 0.4651, MCC: -0.0893, F1: 0.3030

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.66304 | val 0.82577
  Epoch 011 - train 0.64423 | val 0.77936
  Classification -> best τ=0.470 (val F1=0.1377)
  Directional -> Accuracy: 0.6512, MCC: 0.3087, F1: 0.6512

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.62669 | val 1.00807
  Epoch 012 - train 0.58613 | val 1.13320
  Classification -> best τ=0.620 (val F1=0.2399)
  Directional -> Accuracy: 0.5000, MCC: -0.0032, F1: 0.5283

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.62947 | val 0.72924
  Epoch 015 - train 0.59745 | val 1.03017
  Classification -> best τ=0.225 (val F1=0.3773)
  Directional -> Accuracy: 0.5753, MCC: 0.1768, F1: 0.5634

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.61297 | val 0.88823
  Epoch 011 - train 0.61322 | val 0.86553
  Classification -> best τ=0.440 (val F1=0.5590)
  Directional -> Accuracy: 0.5405, MCC: 0.1348, F1: 0.6531

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.65480 | val 0.88260
  Epoch 013 - train 0.64459 | val 1.20951
  Classification -> best τ=0.560 (val F1=0.2442)
  Directional -> Accuracy: 0.5000, MCC: -0.0153, F1: 0.3889

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.62269 | val 0.66601
  Epoch 020 - train 0.58854 | val 0.72410
  Classification -> best τ=0.395 (val F1=0.3551)
  Directional -> Accuracy: 0.5303, MCC: 0.2194, F1: 0.3673

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.61473 | val 1.41053
  Epoch 011 - train 0.60939 | val 1.29288
  Classification -> best τ=0.480 (val F1=0.2357)
  Directional -> Accuracy: 0.5714, MCC: 0.1356, F1: 0.6250

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.65629 | val 0.90935
  Epoch 012 - train 0.58144 | val 1.19230
  Classification -> best τ=0.450 (val F1=0.4294)
  Directional -> Accuracy: 0.5179, MCC: 0.1659, F1: 0.6494

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.58357 | val 1.65048
  Epoch 012 - train 0.56333 | val 2.78176
  Classification -> best τ=0.540 (val F1=0.4012)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.59668 | val 0.69747
  Epoch 020 - train 0.54612 | val 0.61125
  Epoch 030 - train 0.52221 | val 0.63470
  Classification -> best τ=0.280 (val F1=0.6130)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.66201 | val 0.68709
  Epoch 020 - train 0.51208 | val 0.96058
  Epoch 023 - train 0.56384 | val 1.10353
  Classification -> best τ=0.395 (val F1=0.3019)
  Directional -> Accuracy: 0.5135, MCC: 0.0484, F1: 0.4706

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.66296 | val 1.19799
  Epoch 011 - train 0.62268 | val 1.08563
  Classification -> best τ=0.445 (val F1=0.2603)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.71081 | val 0.71459
  Epoch 013 - train 0.69240 | val 0.69031
  Classification -> best τ=0.420 (val F1=0.2419)
  Directional -> Accuracy: 0.4565, MCC: -0.0767, F1: 0.3590

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.58473 | val 1.01136
  Epoch 011 - train 0.65719 | val 1.04041
  Classification -> best τ=0.515 (val F1=0.2282)
  Directional -> Accuracy: 0.6047, MCC: 0.1753, F1: 0.7018

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.74339 | val 0.84656
  Epoch 020 - train 0.61970 | val 0.99344
  Epoch 028 - train 0.49424 | val 0.59310
  Classification -> best τ=0.410 (val F1=0.5131)
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.70230 | val 1.22733
  Epoch 011 - train 0.62109 | val 1.27897
  Classification -> best τ=0.415 (val F1=0.1676)
  Directional -> Accuracy: 0.5714, MCC: 0.1344, F1: 0.6129

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.66752 | val 1.71019
  Epoch 011 - train 0.66381 | val 2.12989
  Classification -> best τ=0.595 (val F1=0.4360)
  Directional -> Accuracy: 0.5714, MCC: 0.1801, F1: 0.6471

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.65694 | val 1.54292
  Epoch 011 - train 0.63527 | val 1.68148
  Classification -> best τ=0.450 (val F1=0.1683)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.64275 | val 2.44569
  Epoch 011 - train 0.60657 | val 1.98295
  Classification -> best τ=0.550 (val F1=0.1168)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.63275 | val 0.81197

[I 2026-02-25 01:58:22,652] Trial 143 finished with value: 0.28272940539894464 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 0.0019220042913783923, 'weight_decay': 0.00010635184304633919, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.47782148957253046, 'early_stopping_min_delta': 0.0035111157376572742}. Best is trial 140 with value: 0.29322408230766744.

  Epoch 019 - train 0.56158 | val 2.09690
  Classification -> best τ=0.375 (val F1=0.3103)
  Directional -> Accuracy: 0.4918, MCC: -0.0275, F1: 0.4151

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.28272940539894464
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.66261 | val 1.15143
  Epoch 012 - train 0.62979 | val 1.07041
  Classification -> best τ=0.495 (val F1=0.3286)
  Directional -> Accuracy: 0.5000, MCC: 0.0169, F1: 0.5128

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.65414 | val 0.96044
  Epoch 011 - train 0.61838 | val 0.99111
  Classification -> best τ=0.530 (val F1=0.0406)
  Directional -> Accuracy: 0.6444, MCC: 0.2466, F1: 0.7333

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.61450 | val 0.68404
  Epoch 014 - train 0.65273 | val 0.74055
  Classification -> best τ=0.520 (val F1=0.3285)
  Directional -> Accuracy: 0.5106, MCC: 0.1333, F1: 0.2069

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.67850 | val 1.08406
  Epoch 012 - train 0.69081 | val 2.06766
  Classification -> best τ=0.385 (val F1=0.2782)
  Directional -> Accuracy: 0.6000, MCC: 0.1892, F1: 0.6429

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.59393 | val 0.74620
  Epoch 014 - train 0.59823 | val 0.79373
  Classification -> best τ=0.515 (val F1=0.4020)
  Directional -> Accuracy: 0.5294, MCC: 0.0291, F1: 0.6471

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.59752 | val 0.72342
  Epoch 011 - train 0.62774 | val 0.81762
  Classification -> best τ=0.515 (val F1=0.2357)
  Directional -> Accuracy: 0.5745, MCC: 0.1486, F1: 0.5652

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.64978 | val 0.97295
  Epoch 012 - train 0.67106 | val 0.93175
  Classification -> best τ=0.475 (val F1=0.1932)
  Directional -> Accuracy: 0.5652, MCC: 0.2924, F1: 0.6341

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.54446 | val 1.61023
  Epoch 013 - train 0.60754 | val 0.87106
  Classification -> best τ=0.540 (val F1=0.0771)
  Directional -> Accuracy: 0.5814, MCC: 0.1027, F1: 0.4000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.62690 | val 0.84872
  Epoch 014 - train 0.59942 | val 1.88428
  Classification -> best τ=0.390 (val F1=0.4068)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.61328 | val 0.79404
  Epoch 011 - train 0.61537 | val 0.75254
  Classification -> best τ=0.430 (val F1=0.3038)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.62194 | val 1.56668
  Epoch 013 - train 0.62076 | val 2.16142
  Classification -> best τ=0.600 (val F1=0.1750)
  Directional -> Accuracy: 0.5800, MCC: 0.2212, F1: 0.1600

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.58753 | val 1.00275
  Epoch 012 - train 0.57338 | val 1.13992
  Classification -> best τ=0.500 (val F1=0.1194)
  Directional -> Accuracy: 0.4828, MCC: -0.0413, F1: 0.2857

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.64715 | val 1.90480
  Epoch 012 - train 0.63428 | val 1.49849
  Classification -> best τ=0.365 (val F1=0.2876)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.69040 | val 0.79090
  Epoch 011 - train 0.66143 | val 0.83477
  Classification -> best τ=0.530 (val F1=0.3994)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.2500

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.59693 | val 1.04849
  Epoch 013 - train 0.56441 | val 2.28117
  Classification -> best τ=0.530 (val F1=0.2673)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.63768 | val 0.96008
  Epoch 011 - train 0.61869 | val 0.84827
  Classification -> best τ=0.415 (val F1=0.2708)
  Directional -> Accuracy: 0.5797, MCC: 0.2293, F1: 0.7184

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.67814 | val 1.95871
  Epoch 011 - train 0.68505 | val 1.89907
  Classification -> best τ=0.665 (val F1=0.1842)
  Directional -> Accuracy: 0.3729, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.62655 | val 1.85169
  Epoch 011 - train 0.62716 | val 1.11497
  Classification -> best τ=0.500 (val F1=0.1800)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.68981 | val 1.42188
  Epoch 011 - train 0.64534 | val 1.37283
  Classification -> best τ=0.480 (val F1=0.2158)
  Directional -> Accuracy: 0.4769, MCC: 0.1610, F1: 0.2273

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.62732 | val 0.72125
  Epoch 013 - train 0.65487 | val 0.78337
  Classification -> best τ=0.495 (val F1=0.3293)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.58845 | val 0.73808
  Epoch 016 - train 0.51911 | val 1.38656
  Classification -> best τ=0.445 (val F1=0.2414)
  Directional -> Accuracy: 0.5106, MCC: 0.1602, F1: 0.4390

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.63311 | val 1.36267
  Epoch 011 - train 0.67653 | val 1.12068
  Classification -> best τ=0.515 (val F1=0.1118)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6598

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.73953 | val 0.79007
  Epoch 015 - train 0.65696 | val 0.93800
  Classification -> best τ=0.545 (val F1=0.2835)
  Directional -> Accuracy: 0.5172, MCC: 0.0882, F1: 0.4615

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.61932 | val 0.91371
  Epoch 011 - train 0.61705 | val 1.00084
  Classification -> best τ=0.480 (val F1=0.0332)
  Directional -> Accuracy: 0.4462, MCC: -0.1024, F1: 0.4706

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.61964 | val 0.67391
  Epoch 017 - train 0.55863 | val 0.74244
  Classification -> best τ=0.500 (val F1=0.4670)
  Directional -> Accuracy: 0.4464, MCC: -0.0373, F1: 0.1622

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.67011 | val 1.26680
  Epoch 011 - train 0.60845 | val 1.46794
  Classification -> best τ=0.595 (val F1=0.0524)
  Directional -> Accuracy: 0.3696, MCC: -0.2526, F1: 0.3556

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.65717 | val 0.68485
  Epoch 014 - train 0.64184 | val 0.85627
  Classification -> best τ=0.610 (val F1=0.1936)
  Directional -> Accuracy: 0.4286, MCC: -0.1514, F1: 0.4783

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.62040 | val 0.94973
  Epoch 013 - train 0.63095 | val 1.08078
  Classification -> best τ=0.305 (val F1=0.2260)
  Directional -> Accuracy: 0.5789, MCC: 0.1312, F1: 0.6471

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.56103 | val 0.94382
  Epoch 011 - train 0.66987 | val 0.80961
  Classification -> best τ=0.475 (val F1=0.0948)
  Directional -> Accuracy: 0.5366, MCC: 0.0789, F1: 0.5366

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.61528 | val 0.72966
  Epoch 016 - train 0.59088 | val 0.71253
  Classification -> best τ=0.485 (val F1=0.3490)
  Directional -> Accuracy: 0.5349, MCC: 0.0783, F1: 0.5833

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.57856 | val 0.82715
  Epoch 012 - train 0.62682 | val 1.02433
  Classification -> best τ=0.490 (val F1=0.1552)
  Directional -> Accuracy: 0.4186, MCC: -0.1533, F1: 0.1935

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.63311 | val 1.06070
  Epoch 012 - train 0.60015 | val 1.03757
  Classification -> best τ=0.470 (val F1=0.3179)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.57140 | val 0.70330
  Epoch 013 - train 0.61004 | val 0.70580
  Classification -> best τ=0.275 (val F1=0.3602)
  Directional -> Accuracy: 0.5479, MCC: 0.1054, F1: 0.5600

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.66211 | val 0.80728
  Epoch 012 - train 0.55432 | val 0.82772
  Classification -> best τ=0.455 (val F1=0.2887)
  Directional -> Accuracy: 0.5405, MCC: 0.0968, F1: 0.6047

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.65267 | val 0.86933
  Epoch 011 - train 0.61735 | val 0.99728
  Classification -> best τ=0.475 (val F1=0.1902)
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.62685 | val 0.76339
  Epoch 011 - train 0.64022 | val 0.81252
  Classification -> best τ=0.445 (val F1=0.4042)
  Directional -> Accuracy: 0.5909, MCC: 0.3480, F1: 0.4706

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.57297 | val 1.02128
  Epoch 012 - train 0.60731 | val 2.04471
  Classification -> best τ=0.505 (val F1=0.1716)
  Directional -> Accuracy: 0.6190, MCC: 0.2864, F1: 0.5294

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.64057 | val 1.27090
  Epoch 012 - train 0.59212 | val 1.39159
  Classification -> best τ=0.425 (val F1=0.3280)
  Directional -> Accuracy: 0.5357, MCC: 0.1754, F1: 0.6486

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.59287 | val 1.93893
  Epoch 012 - train 0.57611 | val 2.08346
  Classification -> best τ=0.500 (val F1=0.3679)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.64387 | val 0.65261
  Epoch 020 - train 0.48172 | val 0.63940
  Epoch 025 - train 0.58673 | val 0.64573
  Classification -> best τ=0.250 (val F1=0.4708)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.67494 | val 0.76153
  Epoch 011 - train 0.64373 | val 0.78239
  Classification -> best τ=0.455 (val F1=0.3320)
  Directional -> Accuracy: 0.5135, MCC: 0.0484, F1: 0.4706

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.65658 | val 1.11806
  Epoch 011 - train 0.67493 | val 1.27085
  Classification -> best τ=0.490 (val F1=0.3553)
  Directional -> Accuracy: 0.5200, MCC: 0.1155, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.69487 | val 0.76597
  Epoch 013 - train 0.73554 | val 1.27657
  Classification -> best τ=0.425 (val F1=0.4882)
  Directional -> Accuracy: 0.4565, MCC: -0.0754, F1: 0.2857

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.64135 | val 0.95873
  Epoch 011 - train 0.53816 | val 1.09704
  Classification -> best τ=0.505 (val F1=0.2855)
  Directional -> Accuracy: 0.6047, MCC: 0.1772, F1: 0.6909

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.60668 | val 0.56812
  Epoch 019 - train 0.56386 | val 1.24084
  Classification -> best τ=0.640 (val F1=0.5557)
  Directional -> Accuracy: 0.3469, MCC: -0.2592, F1: 0.5152

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.69466 | val 1.52000
  Epoch 011 - train 0.63208 | val 1.69912
  Classification -> best τ=0.405 (val F1=0.1850)
  Directional -> Accuracy: 0.4464, MCC: -0.1448, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.65902 | val 1.12726
  Epoch 012 - train 0.60992 | val 1.40075
  Classification -> best τ=0.615 (val F1=0.2845)
  Directional -> Accuracy: 0.5000, MCC: -0.1301, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.63198 | val 2.08634
  Epoch 011 - train 0.58695 | val 2.08963
  Classification -> best τ=0.470 (val F1=0.2079)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.64243 | val 1.62996
  Epoch 011 - train 0.60856 | val 1.38510
  Classification -> best τ=0.540 (val F1=0.1168)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.66624 | val 0.79409
  Epoch 011 - train 0.62587 | val 0.77575

[I 2026-02-25 01:59:57,584] Trial 144 finished with value: 0.261994436410004 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.1, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 0.0020278103725336473, 'weight_decay': 0.00010390333934227609, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.4712514471390082, 'early_stopping_min_delta': 0.0035479357835024893}. Best is trial 140 with value: 0.29322408230766744.

  Classification -> best τ=0.460 (val F1=0.1580)
  Directional -> Accuracy: 0.5082, MCC: -0.0647, F1: 0.0625

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.261994436410004
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.67194 | val 1.03587
  Epoch 012 - train 0.63619 | val 1.14636
  Classification -> best τ=0.550 (val F1=0.2510)
  Directional -> Accuracy: 0.5526, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.62466 | val 0.77844
  Epoch 011 - train 0.62289 | val 0.83867
  Classification -> best τ=0.425 (val F1=0.0541)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.67608 | val 0.74930
  Epoch 012 - train 0.60351 | val 0.83759
  Classification -> best τ=0.560 (val F1=0.2861)
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.66097 | val 1.96785
  Epoch 011 - train 0.68893 | val 1.47998
  Classification -> best τ=0.445 (val F1=0.2052)
  Directional -> Accuracy: 0.5467, MCC: 0.0765, F1: 0.6047

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.63006 | val 0.77451
  Epoch 015 - train 0.58733 | val 0.92850
  Classification -> best τ=0.645 (val F1=0.4397)
  Directional -> Accuracy: 0.4118, MCC: -0.1866, F1: 0.4643

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.59947 | val 0.68921
  Epoch 019 - train 0.44691 | val 1.27068
  Classification -> best τ=0.465 (val F1=0.1644)
  Directional -> Accuracy: 0.6170, MCC: 0.2631, F1: 0.4706

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.65702 | val 0.77805
  Epoch 011 - train 0.65255 | val 0.74801
  Classification -> best τ=0.505 (val F1=0.3223)
  Directional -> Accuracy: 0.5652, MCC: 0.1300, F1: 0.5161

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.56202 | val 0.83008
  Epoch 017 - train 0.58478 | val 0.92434
  Classification -> best τ=0.300 (val F1=0.1214)
  Directional -> Accuracy: 0.5349, MCC: -0.0696, F1: 0.1667

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.61455 | val 0.69741
  Epoch 013 - train 0.61058 | val 0.73670
  Classification -> best τ=0.450 (val F1=0.3039)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.62267 | val 0.99039
  Epoch 016 - train 0.59303 | val 0.81459
  Classification -> best τ=0.475 (val F1=0.3148)
  Directional -> Accuracy: 0.4286, MCC: -0.1110, F1: 0.4595

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.66650 | val 1.13012
  Epoch 012 - train 0.59647 | val 2.04454
  Classification -> best τ=0.520 (val F1=0.1896)
  Directional -> Accuracy: 0.6200, MCC: 0.2408, F1: 0.4242

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.61807 | val 1.56671
  Epoch 011 - train 0.60427 | val 1.63843
  Classification -> best τ=0.455 (val F1=0.2646)
  Directional -> Accuracy: 0.6207, MCC: 0.2572, F1: 0.6765

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.59413 | val 0.87697
  Epoch 012 - train 0.61083 | val 1.15396
  Classification -> best τ=0.370 (val F1=0.2235)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.64055 | val 1.09956
  Epoch 011 - train 0.67037 | val 1.18665
  Classification -> best τ=0.490 (val F1=0.1406)
  Directional -> Accuracy: 0.5167, MCC: 0.0385, F1: 0.3556

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.62055 | val 1.76130
  Epoch 011 - train 0.63010 | val 2.33158
  Classification -> best τ=0.620 (val F1=0.2673)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.63088 | val 0.75132
  Epoch 011 - train 0.60805 | val 0.83736
  Classification -> best τ=0.425 (val F1=0.2100)
  Directional -> Accuracy: 0.5362, MCC: 0.0000, F1: 0.6981

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.65023 | val 2.00056
  Epoch 011 - train 0.67927 | val 2.54010
  Classification -> best τ=0.620 (val F1=0.2186)
  Directional -> Accuracy: 0.3729, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.64565 | val 1.15693
  Epoch 011 - train 0.64594 | val 1.39142
  Classification -> best τ=0.515 (val F1=0.1095)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.63040 | val 1.31928
  Epoch 011 - train 0.58176 | val 1.35883
  Classification -> best τ=0.520 (val F1=0.1398)
  Directional -> Accuracy: 0.4769, MCC: 0.1610, F1: 0.2273

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.64977 | val 0.70727
  Epoch 018 - train 0.57355 | val 0.97254
  Classification -> best τ=0.820 (val F1=0.2606)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.64073 | val 0.67559
  Epoch 020 - train 0.54733 | val 0.78043
  Epoch 021 - train 0.55941 | val 0.70966
  Classification -> best τ=0.415 (val F1=0.3740)
  Directional -> Accuracy: 0.4043, MCC: 0.1162, F1: 0.0667

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.67909 | val 0.88920
  Epoch 017 - train 0.63749 | val 0.83546
  Classification -> best τ=0.510 (val F1=0.2411)
  Directional -> Accuracy: 0.5303, MCC: 0.1768, F1: 0.6804

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.65322 | val 0.90090
  Epoch 013 - train 0.65745 | val 0.96553
  Classification -> best τ=0.645 (val F1=0.2967)
  Directional -> Accuracy: 0.4138, MCC: -0.1111, F1: 0.0556

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.66614 | val 0.75677
  Epoch 015 - train 0.59520 | val 0.88477
  Classification -> best τ=0.465 (val F1=0.1654)
  Directional -> Accuracy: 0.4769, MCC: 0.0000, F1: 0.6458

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.63919 | val 0.63649
  Epoch 016 - train 0.62431 | val 0.67785
  Classification -> best τ=0.535 (val F1=0.4297)
  Directional -> Accuracy: 0.5179, MCC: 0.1188, F1: 0.3721

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.55345 | val 0.86027
  Epoch 011 - train 0.66494 | val 0.94462
  Classification -> best τ=0.440 (val F1=0.1819)
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.61350 | val 0.75444
  Epoch 011 - train 0.67062 | val 0.85869
  Classification -> best τ=0.495 (val F1=0.2439)
  Directional -> Accuracy: 0.5476, MCC: 0.0446, F1: 0.6415

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.57138 | val 1.04487
  Epoch 013 - train 0.58927 | val 1.13175
  Classification -> best τ=0.455 (val F1=0.2225)
  Directional -> Accuracy: 0.4737, MCC: 0.1685, F1: 0.1176

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.64491 | val 0.83515
  Epoch 020 - train 0.56076 | val 1.62862
  Epoch 027 - train 0.52013 | val 1.63470
  Classification -> best τ=0.530 (val F1=0.4730)
  Directional -> Accuracy: 0.5610, MCC: 0.0980, F1: 0.6667

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.59093 | val 0.72876
  Epoch 011 - train 0.62843 | val 0.72725
  Classification -> best τ=0.555 (val F1=0.2814)
  Directional -> Accuracy: 0.5349, MCC: 0.0810, F1: 0.2308

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.62517 | val 0.91927
  Epoch 013 - train 0.66967 | val 1.14784
  Classification -> best τ=0.465 (val F1=0.1377)
  Directional -> Accuracy: 0.5581, MCC: 0.1297, F1: 0.5366

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.59704 | val 1.14846
  Epoch 011 - train 0.60050 | val 1.14504
  Classification -> best τ=0.565 (val F1=0.2399)
  Directional -> Accuracy: 0.3800, MCC: -0.3195, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.64592 | val 0.67706
  Epoch 013 - train 0.60713 | val 0.87326
  Classification -> best τ=0.400 (val F1=0.3602)
  Directional -> Accuracy: 0.5616, MCC: 0.1530, F1: 0.5429

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.61711 | val 0.82417
  Epoch 011 - train 0.59168 | val 0.92724
  Classification -> best τ=0.460 (val F1=0.1688)
  Directional -> Accuracy: 0.5676, MCC: 0.1737, F1: 0.6522

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.67603 | val 0.84594
  Epoch 013 - train 0.61459 | val 0.97559
  Classification -> best τ=0.570 (val F1=0.3221)
  Directional -> Accuracy: 0.6136, MCC: 0.2230, F1: 0.5641

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.61861 | val 0.80634
  Epoch 011 - train 0.63195 | val 0.76089
  Classification -> best τ=0.455 (val F1=0.4042)
  Directional -> Accuracy: 0.5000, MCC: 0.1961, F1: 0.2667

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.61944 | val 1.04317
  Epoch 011 - train 0.57596 | val 1.00683
  Classification -> best τ=0.535 (val F1=0.2206)
  Directional -> Accuracy: 0.6667, MCC: 0.3318, F1: 0.6818

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.63398 | val 1.11863
  Epoch 011 - train 0.62498 | val 1.32381
  Classification -> best τ=0.430 (val F1=0.2450)
  Directional -> Accuracy: 0.5714, MCC: 0.1807, F1: 0.6250

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.57971 | val 2.62523
  Epoch 011 - train 0.58976 | val 2.63063
  Classification -> best τ=0.595 (val F1=0.2441)
  Directional -> Accuracy: 0.3913, MCC: -0.1022, F1: 0.2222

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.68014 | val 0.64550
  Epoch 020 - train 0.62910 | val 0.62082
  Epoch 030 - train 0.53155 | val 0.63688
  Classification -> best τ=0.280 (val F1=0.5247)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.60598 | val 0.74945
  Epoch 011 - train 0.59245 | val 0.76283
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.63774 | val 0.94105
  Epoch 013 - train 0.66153 | val 1.08892
  Classification -> best τ=0.420 (val F1=0.3135)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.64837 | val 0.94334
  Epoch 013 - train 0.58178 | val 1.05953
  Classification -> best τ=0.445 (val F1=0.4515)
  Directional -> Accuracy: 0.4348, MCC: -0.1232, F1: 0.3500

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.63550 | val 0.82470
  Epoch 011 - train 0.57983 | val 0.87898
  Classification -> best τ=0.480 (val F1=0.1234)
  Directional -> Accuracy: 0.5814, MCC: 0.1426, F1: 0.6400

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.65547 | val 0.71782
  Epoch 020 - train 0.51353 | val 0.61470
  Epoch 025 - train 0.51542 | val 0.72737
  Classification -> best τ=0.510 (val F1=0.4385)
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.67507 | val 2.09311
  Epoch 011 - train 0.69885 | val 2.10570
  Classification -> best τ=0.510 (val F1=0.0359)
  Directional -> Accuracy: 0.4821, MCC: -0.0185, F1: 0.4314

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.64006 | val 1.12677
  Epoch 012 - train 0.61494 | val 0.95146
  Classification -> best τ=0.570 (val F1=0.2779)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.63614 | val 1.46217
  Epoch 011 - train 0.61265 | val 1.68590
  Classification -> best τ=0.485 (val F1=0.2132)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.61758 | val 1.80851
  Epoch 011 - train 0.61953 | val 1.78110
  Classification -> best τ=0.535 (val F1=0.1168)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.67780 | val 1.10531

[I 2026-02-25 02:01:37,131] Trial 145 finished with value: 0.24729040466272523 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 0.0012159373078938422, 'weight_decay': 0.0002759552022762205, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.5615430891865885, 'early_stopping_min_delta': 0.004005495908437317}. Best is trial 140 with value: 0.29322408230766744.

  Epoch 013 - train 0.62300 | val 1.05794
  Classification -> best τ=0.545 (val F1=0.1297)
  Directional -> Accuracy: 0.4590, MCC: -0.0903, F1: 0.4000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.24729040466272523
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.60936 | val 0.88546
  Epoch 012 - train 0.64455 | val 0.80033
  Classification -> best τ=0.450 (val F1=0.2431)
  Directional -> Accuracy: 0.5000, MCC: 0.0752, F1: 0.5957

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.62422 | val 0.75106
  Epoch 014 - train 0.60619 | val 0.82974
  Classification -> best τ=0.485 (val F1=0.2252)
  Directional -> Accuracy: 0.6222, MCC: 0.2073, F1: 0.7463

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.64479 | val 0.70749
  Epoch 019 - train 0.67099 | val 1.01648
  Classification -> best τ=0.600 (val F1=0.3537)
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.68215 | val 1.99388
  Epoch 012 - train 0.66631 | val 1.74626
  Classification -> best τ=0.380 (val F1=0.1727)
  Directional -> Accuracy: 0.5467, MCC: 0.0724, F1: 0.6136

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.56802 | val 0.79528
  Epoch 012 - train 0.62363 | val 0.76717
  Classification -> best τ=0.515 (val F1=0.3916)
  Directional -> Accuracy: 0.6667, MCC: 0.3453, F1: 0.6531

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.57332 | val 0.73153
  Epoch 011 - train 0.59331 | val 0.73036
  Classification -> best τ=0.515 (val F1=0.2357)
  Directional -> Accuracy: 0.4894, MCC: 0.0000, F1: 0.6571

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.66539 | val 0.78353
  Epoch 013 - train 0.64928 | val 0.77651
  Classification -> best τ=0.445 (val F1=0.1837)
  Directional -> Accuracy: 0.4493, MCC: 0.0062, F1: 0.5366

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.67499 | val 0.76857
  Epoch 013 - train 0.59182 | val 1.25362
  Classification -> best τ=0.490 (val F1=0.2218)
  Directional -> Accuracy: 0.5581, MCC: -0.1309, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.60987 | val 1.45841
  Epoch 011 - train 0.66214 | val 1.21120
  Classification -> best τ=0.475 (val F1=0.2820)
  Directional -> Accuracy: 0.5918, MCC: 0.1538, F1: 0.4118

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.62228 | val 0.76354
  Epoch 014 - train 0.57181 | val 0.77145
  Classification -> best τ=0.480 (val F1=0.1734)
  Directional -> Accuracy: 0.5143, MCC: 0.0500, F1: 0.5143

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.63009 | val 2.26374
  Epoch 014 - train 0.61577 | val 1.89697
  Classification -> best τ=0.565 (val F1=0.3118)
  Directional -> Accuracy: 0.6400, MCC: 0.3092, F1: 0.6667

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.65070 | val 2.14129
  Epoch 011 - train 0.60865 | val 2.06836
  Classification -> best τ=0.440 (val F1=0.2615)
  Directional -> Accuracy: 0.5172, MCC: 0.1325, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.59808 | val 1.18457
  Epoch 016 - train 0.54922 | val 1.42396
  Classification -> best τ=0.445 (val F1=0.2731)
  Directional -> Accuracy: 0.5238, MCC: 0.1062, F1: 0.6000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.68152 | val 0.95117
  Epoch 013 - train 0.63026 | val 1.05042
  Classification -> best τ=0.445 (val F1=0.3387)
  Directional -> Accuracy: 0.6333, MCC: 0.2828, F1: 0.6857

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.59799 | val 2.68987
  Epoch 011 - train 0.62189 | val 2.53642
  Classification -> best τ=0.615 (val F1=0.2673)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.63745 | val 1.06337
  Epoch 012 - train 0.61767 | val 0.96888
  Classification -> best τ=0.415 (val F1=0.2592)
  Directional -> Accuracy: 0.5652, MCC: 0.1256, F1: 0.7000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.64266 | val 2.13926
  Epoch 011 - train 0.62973 | val 2.15598
  Classification -> best τ=0.425 (val F1=0.0660)
  Directional -> Accuracy: 0.6441, MCC: 0.1506, F1: 0.7640

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.68144 | val 1.80311
  Epoch 012 - train 0.64062 | val 1.01891
  Classification -> best τ=0.605 (val F1=0.2405)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.63131 | val 1.46294
  Epoch 011 - train 0.62737 | val 1.63179
  Classification -> best τ=0.390 (val F1=0.2843)
  Directional -> Accuracy: 0.5538, MCC: 0.1985, F1: 0.4912

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.67326 | val 0.71523
  Epoch 015 - train 0.60312 | val 0.75290
  Classification -> best τ=0.510 (val F1=0.3035)
  Directional -> Accuracy: 0.4800, MCC: 0.1507, F1: 0.0930

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.61358 | val 0.78011
  Epoch 012 - train 0.60821 | val 0.93948
  Classification -> best τ=0.485 (val F1=0.3707)
  Directional -> Accuracy: 0.4681, MCC: -0.0918, F1: 0.5455

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.62432 | val 0.84518
  Epoch 011 - train 0.65097 | val 0.70020
  Classification -> best τ=0.490 (val F1=0.2072)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.3265

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.64307 | val 0.94222
  Epoch 011 - train 0.66560 | val 0.79164
  Classification -> best τ=0.530 (val F1=0.2962)
  Directional -> Accuracy: 0.5517, MCC: 0.1362, F1: 0.5357

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.67659 | val 0.75474
  Epoch 012 - train 0.61303 | val 0.86918
  Classification -> best τ=0.585 (val F1=0.1507)
  Directional -> Accuracy: 0.4923, MCC: -0.0161, F1: 0.4762

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.63808 | val 0.67660
  Epoch 016 - train 0.61356 | val 0.72351
  Classification -> best τ=0.560 (val F1=0.4057)
  Directional -> Accuracy: 0.5536, MCC: 0.1446, F1: 0.5098

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.65114 | val 1.28492
  Epoch 011 - train 0.59805 | val 1.28111
  Classification -> best τ=0.515 (val F1=0.1251)
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.61938 | val 0.67755
  Epoch 020 - train 0.60352 | val 0.88308
  Classification -> best τ=0.550 (val F1=0.2107)
  Directional -> Accuracy: 0.5000, MCC: -0.1005, F1: 0.6316

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.60690 | val 0.85777
  Epoch 012 - train 0.59625 | val 1.03752
  Classification -> best τ=0.405 (val F1=0.2510)
  Directional -> Accuracy: 0.5965, MCC: 0.1923, F1: 0.6230

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.72441 | val 0.75620
  Epoch 015 - train 0.63480 | val 1.30915
  Classification -> best τ=0.570 (val F1=0.5136)
  Directional -> Accuracy: 0.5366, MCC: 0.0241, F1: 0.6780

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.63785 | val 0.81405
  Epoch 020 - train 0.53354 | val 1.08767
  Epoch 025 - train 0.46503 | val 0.93058
  Classification -> best τ=0.470 (val F1=0.3123)
  Directional -> Accuracy: 0.4651, MCC: -0.0664, F1: 0.5106

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.69615 | val 0.80971
  Epoch 017 - train 0.58851 | val 1.00470
  Classification -> best τ=0.495 (val F1=0.1937)
  Directional -> Accuracy: 0.5581, MCC: 0.0981, F1: 0.6885

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.57018 | val 1.11870
  Epoch 012 - train 0.54891 | val 1.27836
  Classification -> best τ=0.445 (val F1=0.3850)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.63929 | val 0.68677
  Epoch 020 - train 0.57699 | val 0.99988
  Epoch 022 - train 0.61621 | val 1.44343
  Classification -> best τ=0.560 (val F1=0.3824)
  Directional -> Accuracy: 0.5753, MCC: 0.2332, F1: 0.4918

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.66435 | val 1.03939
  Epoch 011 - train 0.64226 | val 0.95095
  Classification -> best τ=0.405 (val F1=0.3882)
  Directional -> Accuracy: 0.6216, MCC: 0.3847, F1: 0.7200

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.68209 | val 0.98349
  Epoch 015 - train 0.60701 | val 1.00162
  Classification -> best τ=0.440 (val F1=0.2920)
  Directional -> Accuracy: 0.4773, MCC: -0.0839, F1: 0.2581

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.62285 | val 0.71469
  Epoch 011 - train 0.62313 | val 0.70740
  Classification -> best τ=0.440 (val F1=0.3254)
  Directional -> Accuracy: 0.5909, MCC: 0.1376, F1: 0.6747

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.60307 | val 0.96294
  Epoch 011 - train 0.61598 | val 1.08501
  Classification -> best τ=0.505 (val F1=0.2206)
  Directional -> Accuracy: 0.6667, MCC: 0.3441, F1: 0.6500

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.64042 | val 1.00112
  Epoch 011 - train 0.62620 | val 1.28383
  Classification -> best τ=0.440 (val F1=0.2450)
  Directional -> Accuracy: 0.5536, MCC: 0.1377, F1: 0.6032

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.58535 | val 1.56326
  Epoch 011 - train 0.57017 | val 1.53736
  Classification -> best τ=0.540 (val F1=0.3105)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.61493 | val 0.71392
  Epoch 020 - train 0.58634 | val 0.65074
  Epoch 030 - train 0.58307 | val 0.73273
  Classification -> best τ=0.360 (val F1=0.4976)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.58506 | val 0.79178
  Epoch 011 - train 0.64311 | val 0.83641
  Classification -> best τ=0.455 (val F1=0.0612)
  Directional -> Accuracy: 0.5405, MCC: 0.0427, F1: 0.6531

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.62156 | val 1.15445
  Epoch 013 - train 0.66596 | val 0.88113
  Classification -> best τ=0.385 (val F1=0.3656)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.63913 | val 1.09441
  Epoch 012 - train 0.65002 | val 1.09709
  Classification -> best τ=0.425 (val F1=0.5003)
  Directional -> Accuracy: 0.5870, MCC: 0.1691, F1: 0.6275

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.66800 | val 1.02003
  Epoch 012 - train 0.60924 | val 0.99745
  Classification -> best τ=0.580 (val F1=0.2530)
  Directional -> Accuracy: 0.4884, MCC: 0.0316, F1: 0.3889

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.64287 | val 0.58299
  Epoch 020 - train 0.55530 | val 1.20873
  Classification -> best τ=0.610 (val F1=0.6539)
  Directional -> Accuracy: 0.3878, MCC: -0.0687, F1: 0.5312

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.68937 | val 1.02982
  Epoch 017 - train 0.66323 | val 1.70477
  Classification -> best τ=0.430 (val F1=0.2958)
  Directional -> Accuracy: 0.6607, MCC: 0.3646, F1: 0.6122

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.64358 | val 1.22448
  Epoch 011 - train 0.61922 | val 1.12626
  Classification -> best τ=0.550 (val F1=0.4276)
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.61716 | val 1.14320
  Epoch 011 - train 0.67168 | val 1.30289
  Classification -> best τ=0.380 (val F1=0.2163)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.59852 | val 1.69078
  Epoch 011 - train 0.61024 | val 2.05867
  Classification -> best τ=0.505 (val F1=0.1168)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.61923 | val 0.98306

[I 2026-02-25 02:03:19,580] Trial 146 finished with value: 0.2879588115287853 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 0.0026275091803001265, 'weight_decay': 0.00022159231103591317, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.5150958529461976, 'early_stopping_min_delta': 0.003839223993697824}. Best is trial 140 with value: 0.29322408230766744.

  Epoch 016 - train 0.60303 | val 1.36944
  Classification -> best τ=0.440 (val F1=0.3349)
  Directional -> Accuracy: 0.5574, MCC: 0.2109, F1: 0.6667

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2879588115287853
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.62310 | val 0.84291
  Epoch 012 - train 0.65312 | val 0.76132
  Classification -> best τ=0.495 (val F1=0.2510)
  Directional -> Accuracy: 0.5526, MCC: 0.0503, F1: 0.2917

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.67519 | val 0.73636
  Epoch 011 - train 0.59472 | val 0.72795
  Classification -> best τ=0.465 (val F1=0.0510)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.60864 | val 0.72262
  Epoch 020 - train 0.58153 | val 0.84345
  Epoch 022 - train 0.58747 | val 0.91952
  Classification -> best τ=0.570 (val F1=0.3512)
  Directional -> Accuracy: 0.4894, MCC: 0.1383, F1: 0.0769

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.65068 | val 2.09760
  Epoch 011 - train 0.65139 | val 2.85205
  Classification -> best τ=0.305 (val F1=0.1810)
  Directional -> Accuracy: 0.4267, MCC: -0.1192, F1: 0.3175

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.64524 | val 0.70790
  Epoch 012 - train 0.60315 | val 0.71572
  Classification -> best τ=0.585 (val F1=0.3484)
  Directional -> Accuracy: 0.4314, MCC: -0.1387, F1: 0.4528

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.63832 | val 0.76639
  Epoch 013 - train 0.57730 | val 1.03119
  Classification -> best τ=0.520 (val F1=0.1715)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.66808 | val 0.77687
  Epoch 013 - train 0.66730 | val 0.81747
  Classification -> best τ=0.505 (val F1=0.1805)
  Directional -> Accuracy: 0.5652, MCC: 0.2087, F1: 0.5946

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.66011 | val 0.90780
  Epoch 016 - train 0.60190 | val 1.00296
  Classification -> best τ=0.375 (val F1=0.2192)
  Directional -> Accuracy: 0.4651, MCC: -0.0593, F1: 0.4390

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.62628 | val 1.24179
  Epoch 011 - train 0.65472 | val 1.69233
  Classification -> best τ=0.495 (val F1=0.4249)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.64908 | val 0.90717
  Epoch 018 - train 0.58681 | val 0.86295
  Classification -> best τ=0.395 (val F1=0.1816)
  Directional -> Accuracy: 0.4429, MCC: 0.0160, F1: 0.5895

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.59358 | val 2.14031
  Epoch 011 - train 0.62448 | val 2.35038
  Classification -> best τ=0.510 (val F1=0.1361)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.64451 | val 1.39510
  Epoch 011 - train 0.61800 | val 1.22987
  Classification -> best τ=0.410 (val F1=0.2196)
  Directional -> Accuracy: 0.5172, MCC: 0.1325, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.61029 | val 1.10668
  Epoch 012 - train 0.63239 | val 1.28300
  Classification -> best τ=0.460 (val F1=0.2235)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.69690 | val 0.74279
  Epoch 011 - train 0.65575 | val 0.77861
  Classification -> best τ=0.455 (val F1=0.2839)
  Directional -> Accuracy: 0.5833, MCC: 0.1668, F1: 0.5902

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.62212 | val 3.53104
  Epoch 011 - train 0.58144 | val 2.75270
  Classification -> best τ=0.450 (val F1=0.0869)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.60315 | val 0.75384
  Epoch 015 - train 0.58059 | val 0.84027
  Classification -> best τ=0.375 (val F1=0.3250)
  Directional -> Accuracy: 0.6087, MCC: 0.2071, F1: 0.6582

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.63622 | val 2.43955
  Epoch 011 - train 0.69001 | val 2.50858
  Classification -> best τ=0.545 (val F1=0.1291)
  Directional -> Accuracy: 0.3729, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.66179 | val 1.34415
  Epoch 011 - train 0.65169 | val 1.59338
  Classification -> best τ=0.420 (val F1=0.1217)
  Directional -> Accuracy: 0.6000, MCC: 0.0000, F1: 0.7500

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.66780 | val 1.25889
  Epoch 011 - train 0.61364 | val 1.78372
  Classification -> best τ=0.550 (val F1=0.1931)
  Directional -> Accuracy: 0.4769, MCC: 0.0998, F1: 0.2917

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.65942 | val 0.69853
  Epoch 018 - train 0.58832 | val 0.70651
  Classification -> best τ=0.480 (val F1=0.2975)
  Directional -> Accuracy: 0.4800, MCC: 0.0711, F1: 0.1702

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.61342 | val 0.80391
  Epoch 016 - train 0.57444 | val 0.85266
  Classification -> best τ=0.400 (val F1=0.3278)
  Directional -> Accuracy: 0.5106, MCC: 0.3014, F1: 0.3429

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.70373 | val 0.87986
  Epoch 014 - train 0.63780 | val 0.99082
  Classification -> best τ=0.320 (val F1=0.2054)
  Directional -> Accuracy: 0.5152, MCC: 0.1240, F1: 0.6735

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.63203 | val 0.80443
  Epoch 011 - train 0.67789 | val 0.77045
  Classification -> best τ=0.550 (val F1=0.2554)
  Directional -> Accuracy: 0.5000, MCC: 0.1008, F1: 0.3556

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.65630 | val 0.73996
  Epoch 012 - train 0.61824 | val 0.80216
  Classification -> best τ=0.370 (val F1=0.1755)
  Directional -> Accuracy: 0.4769, MCC: 0.0000, F1: 0.6458

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.64136 | val 0.65429
  Epoch 020 - train 0.53385 | val 0.89690
  Classification -> best τ=0.660 (val F1=0.3953)
  Directional -> Accuracy: 0.4643, MCC: 0.0541, F1: 0.1176

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.55315 | val 1.55829
  Epoch 011 - train 0.60060 | val 1.78226
  Classification -> best τ=0.495 (val F1=0.2935)
  Directional -> Accuracy: 0.4348, MCC: -0.0280, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.65742 | val 0.68842
  Epoch 011 - train 0.65494 | val 0.69245
  Classification -> best τ=0.580 (val F1=0.2071)
  Directional -> Accuracy: 0.5476, MCC: 0.0829, F1: 0.5957

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.63960 | val 0.90300
  Epoch 012 - train 0.60567 | val 1.10562
  Classification -> best τ=0.430 (val F1=0.3032)
  Directional -> Accuracy: 0.6491, MCC: 0.2944, F1: 0.6774

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.69182 | val 0.77744
  Epoch 019 - train 0.63421 | val 0.89021
  Classification -> best τ=0.480 (val F1=0.4862)
  Directional -> Accuracy: 0.5610, MCC: 0.1145, F1: 0.7000

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.69068 | val 0.74848
  Epoch 014 - train 0.53922 | val 0.74392
  Classification -> best τ=0.550 (val F1=0.2814)
  Directional -> Accuracy: 0.5349, MCC: 0.0831, F1: 0.6000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.65162 | val 1.01125
  Epoch 013 - train 0.65978 | val 0.75547
  Classification -> best τ=0.605 (val F1=0.2525)
  Directional -> Accuracy: 0.4651, MCC: -0.0334, F1: 0.2581

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.58890 | val 0.91788
  Epoch 011 - train 0.63134 | val 0.85057
  Classification -> best τ=0.400 (val F1=0.3309)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.61113 | val 0.67990
  Epoch 015 - train 0.59757 | val 1.16222
  Classification -> best τ=0.345 (val F1=0.3982)
  Directional -> Accuracy: 0.6027, MCC: 0.2657, F1: 0.5538

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.61636 | val 0.75017
  Epoch 012 - train 0.61669 | val 0.77269
  Classification -> best τ=0.515 (val F1=0.2887)
  Directional -> Accuracy: 0.5405, MCC: 0.0968, F1: 0.6047

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.66641 | val 0.96513
  Epoch 012 - train 0.67766 | val 1.12177
  Classification -> best τ=0.520 (val F1=0.1563)
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.61233 | val 0.67740
  Epoch 018 - train 0.60580 | val 0.79513
  Classification -> best τ=0.335 (val F1=0.3525)
  Directional -> Accuracy: 0.5152, MCC: 0.1454, F1: 0.3846

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.61201 | val 1.00551
  Epoch 013 - train 0.63711 | val 1.31835
  Classification -> best τ=0.575 (val F1=0.2044)
  Directional -> Accuracy: 0.5000, MCC: 0.0793, F1: 0.1600

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.59591 | val 1.24491
  Epoch 011 - train 0.66597 | val 1.12200
  Classification -> best τ=0.365 (val F1=0.2868)
  Directional -> Accuracy: 0.5536, MCC: 0.1377, F1: 0.6032

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.59693 | val 1.53066
  Epoch 012 - train 0.56365 | val 2.29583
  Classification -> best τ=0.530 (val F1=0.3383)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.61175 | val 0.73826
  Epoch 015 - train 0.61448 | val 0.98135
  Classification -> best τ=0.350 (val F1=0.4386)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.67893 | val 0.74589
  Epoch 015 - train 0.60656 | val 0.88687
  Classification -> best τ=0.440 (val F1=0.3162)
  Directional -> Accuracy: 0.4595, MCC: -0.0882, F1: 0.5000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.60593 | val 1.04167
  Epoch 014 - train 0.60635 | val 1.14310
  Classification -> best τ=0.350 (val F1=0.3707)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.63647 | val 0.83748
  Epoch 012 - train 0.61788 | val 0.89677
  Classification -> best τ=0.415 (val F1=0.4585)
  Directional -> Accuracy: 0.5000, MCC: -0.0334, F1: 0.6230

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.65285 | val 0.94920
  Epoch 011 - train 0.60047 | val 1.04586
  Classification -> best τ=0.515 (val F1=0.2282)
  Directional -> Accuracy: 0.6047, MCC: 0.1772, F1: 0.6909

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.65002 | val 0.68217
  Epoch 016 - train 0.64994 | val 0.71169
  Classification -> best τ=0.800 (val F1=0.6080)
  Directional -> Accuracy: 0.5714, MCC: 0.2281, F1: 0.5882

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.66302 | val 1.63851
  Epoch 011 - train 0.68628 | val 1.84371
  Classification -> best τ=0.350 (val F1=0.1942)
  Directional -> Accuracy: 0.5179, MCC: -0.0030, F1: 0.6301

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.65024 | val 1.86019
  Epoch 012 - train 0.63363 | val 1.30393
  Classification -> best τ=0.535 (val F1=0.4137)
  Directional -> Accuracy: 0.5357, MCC: 0.0728, F1: 0.5357

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.61767 | val 1.56014
  Epoch 011 - train 0.63936 | val 1.79692
  Classification -> best τ=0.390 (val F1=0.2408)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.63972 | val 1.57826
  Epoch 011 - train 0.62851 | val 1.60391
  Classification -> best τ=0.550 (val F1=0.1168)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.66204 | val 1.45251

[I 2026-02-25 02:05:00,650] Trial 147 finished with value: 0.2716168480273454 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 0.002915020536890911, 'weight_decay': 0.00021025486675462068, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.37082019622483153, 'early_stopping_min_delta': 0.004256739400333107}. Best is trial 140 with value: 0.29322408230766744.

  Epoch 015 - train 0.61195 | val 1.72130
  Classification -> best τ=0.410 (val F1=0.2793)
  Directional -> Accuracy: 0.5246, MCC: 0.0370, F1: 0.4314

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2716168480273454
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.65537 | val 1.27027
  Epoch 011 - train 0.62040 | val 1.20967
  Classification -> best τ=0.495 (val F1=0.2510)
  Directional -> Accuracy: 0.5526, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.58993 | val 0.69991
  Epoch 011 - train 0.60286 | val 0.69996
  Classification -> best τ=0.490 (val F1=0.0096)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.63853 | val 0.81980
  Epoch 015 - train 0.58751 | val 1.01803
  Classification -> best τ=0.520 (val F1=0.2559)
  Directional -> Accuracy: 0.5319, MCC: 0.1314, F1: 0.3529

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.64166 | val 2.26857
  Epoch 011 - train 0.61229 | val 1.48033
  Classification -> best τ=0.360 (val F1=0.1964)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.54861 | val 0.82825
  Epoch 015 - train 0.58556 | val 1.10683
  Classification -> best τ=0.595 (val F1=0.3493)
  Directional -> Accuracy: 0.4118, MCC: -0.2141, F1: 0.5161

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.52568 | val 0.74925
  Epoch 011 - train 0.53907 | val 0.71771
  Classification -> best τ=0.545 (val F1=0.3394)
  Directional -> Accuracy: 0.5319, MCC: 0.1506, F1: 0.0833

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.63582 | val 0.79926
  Epoch 011 - train 0.66040 | val 0.85894
  Classification -> best τ=0.520 (val F1=0.1846)
  Directional -> Accuracy: 0.5217, MCC: 0.1743, F1: 0.5926

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.61006 | val 1.72159
  Epoch 016 - train 0.54668 | val 2.05836
  Classification -> best τ=0.555 (val F1=0.1590)
  Directional -> Accuracy: 0.6047, MCC: 0.1334, F1: 0.2609

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.57470 | val 0.70730
  Epoch 012 - train 0.57735 | val 0.95786
  Classification -> best τ=0.490 (val F1=0.4249)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.58339 | val 0.76844
  Epoch 012 - train 0.57520 | val 0.87360
  Classification -> best τ=0.490 (val F1=0.1620)
  Directional -> Accuracy: 0.5571, MCC: 0.0227, F1: 0.2439

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.57261 | val 2.03302
  Epoch 011 - train 0.56450 | val 2.37867
  Classification -> best τ=0.525 (val F1=0.2010)
  Directional -> Accuracy: 0.6000, MCC: 0.2059, F1: 0.3333

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.56715 | val 1.87433
  Epoch 012 - train 0.58155 | val 1.37291
  Classification -> best τ=0.535 (val F1=0.1923)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.52621 | val 1.24563
  Epoch 011 - train 0.56139 | val 1.25730
  Classification -> best τ=0.440 (val F1=0.1908)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.64238 | val 1.17991
  Epoch 011 - train 0.62814 | val 1.19355
  Classification -> best τ=0.525 (val F1=0.1234)
  Directional -> Accuracy: 0.5833, MCC: 0.1849, F1: 0.4681

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.60019 | val 1.86486
  Epoch 012 - train 0.54162 | val 2.60757
  Classification -> best τ=0.580 (val F1=0.2673)
  Directional -> Accuracy: 0.5577, MCC: 0.0863, F1: 0.3030

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.58953 | val 1.03755
  Epoch 011 - train 0.62048 | val 0.95948
  Classification -> best τ=0.510 (val F1=0.3110)
  Directional -> Accuracy: 0.6667, MCC: 0.4165, F1: 0.7629

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.61508 | val 2.37609
  Epoch 011 - train 0.65198 | val 2.53301
  Classification -> best τ=0.560 (val F1=0.1342)
  Directional -> Accuracy: 0.3729, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.61775 | val 1.58053
  Epoch 011 - train 0.63358 | val 1.67908
  Classification -> best τ=0.545 (val F1=0.1923)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.62135 | val 1.89312
  Epoch 011 - train 0.61150 | val 1.87461
  Classification -> best τ=0.475 (val F1=0.1398)
  Directional -> Accuracy: 0.4923, MCC: 0.1307, F1: 0.3265

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.60937 | val 1.01684
  Epoch 013 - train 0.57710 | val 1.20040
  Classification -> best τ=0.515 (val F1=0.2934)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.53617 | val 0.85039
  Epoch 018 - train 0.52799 | val 1.35246
  Classification -> best τ=0.400 (val F1=0.3740)
  Directional -> Accuracy: 0.4894, MCC: 0.2066, F1: 0.3333

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.63247 | val 0.85252
  Epoch 011 - train 0.59904 | val 0.98113
  Classification -> best τ=0.560 (val F1=0.0861)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.1081

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.66373 | val 0.82271
  Epoch 012 - train 0.61005 | val 0.78645
  Classification -> best τ=0.570 (val F1=0.3031)
  Directional -> Accuracy: 0.5000, MCC: 0.0455, F1: 0.4528

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.63257 | val 0.80563
  Epoch 012 - train 0.61898 | val 1.13976
  Classification -> best τ=0.390 (val F1=0.2383)
  Directional -> Accuracy: 0.4769, MCC: 0.0000, F1: 0.6458

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.58848 | val 0.68339
  Epoch 015 - train 0.56227 | val 0.68423
  Classification -> best τ=0.455 (val F1=0.3299)
  Directional -> Accuracy: 0.5536, MCC: 0.0803, F1: 0.6269

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.58695 | val 1.00925
  Epoch 013 - train 0.56176 | val 1.08988
  Classification -> best τ=0.485 (val F1=0.2935)
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.60357 | val 0.73283
  Epoch 020 - train 0.58124 | val 0.67898
  Epoch 022 - train 0.57452 | val 0.73230
  Classification -> best τ=0.575 (val F1=0.2402)
  Directional -> Accuracy: 0.5238, MCC: 0.0550, F1: 0.5455

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.60131 | val 1.36005
  Epoch 013 - train 0.58335 | val 1.50426
  Classification -> best τ=0.450 (val F1=0.2073)
  Directional -> Accuracy: 0.5614, MCC: 0.1055, F1: 0.6154

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.61705 | val 1.01347
  Epoch 011 - train 0.62647 | val 1.02067
  Classification -> best τ=0.490 (val F1=0.0989)
  Directional -> Accuracy: 0.6585, MCC: 0.3100, F1: 0.6957

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.57990 | val 0.68830
  Epoch 017 - train 0.51069 | val 0.80523
  Classification -> best τ=0.595 (val F1=0.2814)
  Directional -> Accuracy: 0.5349, MCC: 0.0658, F1: 0.4444

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.56941 | val 1.28083
  Epoch 011 - train 0.56195 | val 2.03232
  Classification -> best τ=0.515 (val F1=0.1204)
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.56200 | val 0.88295
  Epoch 012 - train 0.53167 | val 1.28300
  Classification -> best τ=0.435 (val F1=0.2932)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.61814 | val 0.84733
  Epoch 013 - train 0.56663 | val 1.37340
  Classification -> best τ=0.475 (val F1=0.2953)
  Directional -> Accuracy: 0.5205, MCC: 0.1344, F1: 0.3860

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.60914 | val 0.94575
  Epoch 011 - train 0.59516 | val 1.09933
  Classification -> best τ=0.375 (val F1=0.5590)
  Directional -> Accuracy: 0.5676, MCC: 0.2266, F1: 0.6800

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.63553 | val 0.83575
  Epoch 012 - train 0.58743 | val 0.98736
  Classification -> best τ=0.515 (val F1=0.2757)
  Directional -> Accuracy: 0.5000, MCC: 0.0424, F1: 0.6207

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.59643 | val 0.75704
  Epoch 013 - train 0.61400 | val 0.73639
  Classification -> best τ=0.400 (val F1=0.3525)
  Directional -> Accuracy: 0.5000, MCC: 0.0718, F1: 0.4211

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.53285 | val 1.26788
  Epoch 011 - train 0.57440 | val 1.14753
  Classification -> best τ=0.490 (val F1=0.2568)
  Directional -> Accuracy: 0.6667, MCC: 0.3708, F1: 0.6111

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.58907 | val 1.24726
  Epoch 013 - train 0.58638 | val 1.18059
  Classification -> best τ=0.375 (val F1=0.3455)
  Directional -> Accuracy: 0.6071, MCC: 0.2894, F1: 0.6765

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.53214 | val 2.27864
  Epoch 011 - train 0.54716 | val 1.59193
  Classification -> best τ=0.540 (val F1=0.4335)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.62245 | val 0.66327
  Epoch 020 - train 0.52043 | val 0.66414
  Epoch 026 - train 0.46707 | val 0.63059
  Classification -> best τ=0.315 (val F1=0.5125)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.52118 | val 0.72981
  Epoch 011 - train 0.56778 | val 0.77044
  Classification -> best τ=0.490 (val F1=0.3545)
  Directional -> Accuracy: 0.4595, MCC: -0.0985, F1: 0.5238

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.60897 | val 1.25320
  Epoch 011 - train 0.61701 | val 1.55200
  Classification -> best τ=0.415 (val F1=0.2330)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.58710 | val 0.92135
  Epoch 016 - train 0.57354 | val 0.89304
  Classification -> best τ=0.475 (val F1=0.2933)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.6857

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.62909 | val 0.92370
  Epoch 011 - train 0.59707 | val 0.98117
  Classification -> best τ=0.530 (val F1=0.2530)
  Directional -> Accuracy: 0.4186, MCC: -0.1155, F1: 0.1379

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.57204 | val 0.58736
  Epoch 019 - train 0.49108 | val 0.73884
  Classification -> best τ=0.570 (val F1=0.5421)
  Directional -> Accuracy: 0.3878, MCC: -0.0687, F1: 0.5312

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.65604 | val 1.66322
  Epoch 011 - train 0.63541 | val 2.15492
  Classification -> best τ=0.490 (val F1=0.1908)
  Directional -> Accuracy: 0.5179, MCC: 0.1659, F1: 0.2286

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.57788 | val 0.96384
  Epoch 011 - train 0.56420 | val 1.05615
  Classification -> best τ=0.575 (val F1=0.4276)
  Directional -> Accuracy: 0.5357, MCC: 0.0994, F1: 0.6176

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.63172 | val 1.99231
  Epoch 011 - train 0.55543 | val 1.64532
  Classification -> best τ=0.545 (val F1=0.1626)
  Directional -> Accuracy: 0.6296, MCC: 0.2610, F1: 0.6296

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.57993 | val 1.96815
  Epoch 011 - train 0.57987 | val 2.27357
  Classification -> best τ=0.485 (val F1=0.1168)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.63375 | val 0.80511
  Epoch 011 - train 0.62296 | val 0.84868

[I 2026-02-25 02:06:36,335] Trial 148 finished with value: 0.2620591148698886 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.6000000000000001, 'batch_size': 32, 'learning_rate': 0.0016544104676043943, 'weight_decay': 0.00013469235029871227, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.4003653048151331, 'early_stopping_min_delta': 0.0037571848462897087}. Best is trial 140 with value: 0.29322408230766744.

  Classification -> best τ=0.530 (val F1=0.2544)
  Directional -> Accuracy: 0.5246, MCC: 0.0244, F1: 0.2927

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2620591148698886
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.64999 | val 0.66306
  Epoch 016 - train 0.63490 | val 0.71997
  Classification -> best τ=0.535 (val F1=0.3013)
  Directional -> Accuracy: 0.5658, MCC: 0.0886, F1: 0.3529

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.64987 | val 0.70904
  Epoch 011 - train 0.61884 | val 0.70113
  Classification -> best τ=0.460 (val F1=0.2722)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.69053 | val 0.73798
  Epoch 014 - train 0.64147 | val 0.72041
  Classification -> best τ=0.445 (val F1=0.4078)
  Directional -> Accuracy: 0.5106, MCC: -0.0081, F1: 0.6102

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.67620 | val 0.73373
  Epoch 011 - train 0.67776 | val 0.73632
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.65087 | val 0.65293
  Epoch 016 - train 0.61480 | val 0.70091
  Classification -> best τ=0.560 (val F1=0.4255)
  Directional -> Accuracy: 0.5294, MCC: 0.0513, F1: 0.5714

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.66948 | val 0.71665
  Epoch 011 - train 0.60671 | val 0.73012
  Classification -> best τ=0.490 (val F1=0.3430)
  Directional -> Accuracy: 0.5106, MCC: 0.0258, F1: 0.5490

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.67843 | val 0.68229
  Epoch 020 - train 0.66295 | val 0.73600
  Classification -> best τ=0.480 (val F1=0.3018)
  Directional -> Accuracy: 0.4928, MCC: 0.0877, F1: 0.5570

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.61410 | val 0.67629
  Epoch 015 - train 0.63425 | val 0.62377
  Classification -> best τ=0.325 (val F1=0.0548)
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.65088 | val 0.73446
  Epoch 013 - train 0.62505 | val 0.77936
  Classification -> best τ=0.525 (val F1=0.2265)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.64233 | val 0.71059
  Epoch 012 - train 0.61583 | val 0.71202
  Classification -> best τ=0.520 (val F1=0.2012)
  Directional -> Accuracy: 0.5286, MCC: 0.0496, F1: 0.4762

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.66185 | val 0.72027
  Epoch 011 - train 0.66381 | val 0.70281
  Classification -> best τ=0.445 (val F1=0.1667)
  Directional -> Accuracy: 0.5400, MCC: 0.0835, F1: 0.5306

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.63599 | val 0.90938
  Epoch 011 - train 0.67238 | val 0.89521
  Classification -> best τ=0.495 (val F1=0.0283)
  Directional -> Accuracy: 0.4483, MCC: -0.1843, F1: 0.6098

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.59527 | val 0.83383
  Epoch 011 - train 0.57112 | val 0.82531
  Classification -> best τ=0.465 (val F1=0.2323)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.67683 | val 0.63005
  Epoch 020 - train 0.61923 | val 0.62921
  Epoch 023 - train 0.61185 | val 0.73399
  Classification -> best τ=0.505 (val F1=0.3387)
  Directional -> Accuracy: 0.5667, MCC: 0.1361, F1: 0.6061

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.64122 | val 0.70344
  Epoch 015 - train 0.65165 | val 0.86612
  Classification -> best τ=0.515 (val F1=0.2160)
  Directional -> Accuracy: 0.5000, MCC: -0.1852, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.64819 | val 0.76940
  Epoch 012 - train 0.64287 | val 0.82295
  Classification -> best τ=0.620 (val F1=0.3170)
  Directional -> Accuracy: 0.4928, MCC: -0.0177, F1: 0.5205

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.66535 | val 0.87846
  Epoch 012 - train 0.65561 | val 0.91330
  Classification -> best τ=0.645 (val F1=0.1842)
  Directional -> Accuracy: 0.3729, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.64951 | val 0.79666
  Epoch 011 - train 0.66162 | val 0.80940
  Classification -> best τ=0.520 (val F1=0.0983)
  Directional -> Accuracy: 0.4667, MCC: -0.0439, F1: 0.4872

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.66430 | val 0.83317
  Epoch 012 - train 0.65970 | val 1.08120
  Classification -> best τ=0.485 (val F1=0.1795)
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.64662 | val 0.65904
  Epoch 020 - train 0.61328 | val 0.69598
  Classification -> best τ=0.400 (val F1=0.3544)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.66964 | val 0.75210
  Epoch 011 - train 0.65118 | val 0.75041
  Classification -> best τ=0.460 (val F1=0.1342)
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.68481 | val 0.79379
  Epoch 011 - train 0.66614 | val 0.80632
  Classification -> best τ=0.560 (val F1=0.0747)
  Directional -> Accuracy: 0.4697, MCC: -0.0707, F1: 0.2857

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.68584 | val 0.70853
  Epoch 012 - train 0.64850 | val 0.74080
  Classification -> best τ=0.540 (val F1=0.2405)
  Directional -> Accuracy: 0.5690, MCC: 0.1255, F1: 0.6154

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.66320 | val 0.72480
  Epoch 012 - train 0.63398 | val 0.69311
  Classification -> best τ=0.435 (val F1=0.1026)
  Directional -> Accuracy: 0.5231, MCC: 0.0776, F1: 0.6076

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.64606 | val 0.64824
  Epoch 018 - train 0.60935 | val 0.77581
  Classification -> best τ=0.370 (val F1=0.3730)
  Directional -> Accuracy: 0.5000, MCC: 0.0565, F1: 0.3913

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.64305 | val 0.71988
  Epoch 011 - train 0.74780 | val 0.73695
  Classification -> best τ=0.515 (val F1=0.2035)
  Directional -> Accuracy: 0.4565, MCC: 0.1307, F1: 0.6154

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.69547 | val 0.71800
  Epoch 011 - train 0.66352 | val 0.69221
  Classification -> best τ=0.575 (val F1=0.1936)
  Directional -> Accuracy: 0.5000, MCC: -0.0138, F1: 0.5532

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.64858 | val 0.72731
  Epoch 013 - train 0.62302 | val 0.79938
  Classification -> best τ=0.425 (val F1=0.2668)
  Directional -> Accuracy: 0.4737, MCC: 0.1685, F1: 0.1176

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.68847 | val 0.72909
  Epoch 020 - train 0.58085 | val 0.66449
  Epoch 029 - train 0.59716 | val 0.78919
  Classification -> best τ=0.655 (val F1=0.4114)
  Directional -> Accuracy: 0.5366, MCC: 0.0472, F1: 0.6275

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.66928 | val 0.76655
  Epoch 011 - train 0.65406 | val 0.79115
  Classification -> best τ=0.520 (val F1=0.2814)
  Directional -> Accuracy: 0.5349, MCC: 0.0831, F1: 0.6000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.70066 | val 0.65180
  Epoch 020 - train 0.57889 | val 0.65072
  Epoch 030 - train 0.56020 | val 0.63571
  Classification -> best τ=0.610 (val F1=0.3985)
  Directional -> Accuracy: 0.5581, MCC: 0.0968, F1: 0.6415

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.61769 | val 0.78731
  Epoch 013 - train 0.58013 | val 1.08091
  Classification -> best τ=0.415 (val F1=0.3789)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.63175 | val 0.83904
  Epoch 013 - train 0.62887 | val 0.74555
  Classification -> best τ=0.505 (val F1=0.2749)
  Directional -> Accuracy: 0.4658, MCC: 0.0308, F1: 0.2353

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.65740 | val 0.88753
  Epoch 011 - train 0.66974 | val 0.82680
  Classification -> best τ=0.455 (val F1=0.2025)
  Directional -> Accuracy: 0.5405, MCC: 0.1348, F1: 0.6531

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.67596 | val 0.77364
  Epoch 015 - train 0.63364 | val 0.78794
  Classification -> best τ=0.465 (val F1=0.2757)
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.66684 | val 0.77287
  Epoch 011 - train 0.62442 | val 0.81262
  Classification -> best τ=0.425 (val F1=0.4292)
  Directional -> Accuracy: 0.5909, MCC: 0.1839, F1: 0.6197

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.67033 | val 0.76204
  Epoch 011 - train 0.60520 | val 0.79465
  Classification -> best τ=0.425 (val F1=0.2251)
  Directional -> Accuracy: 0.7143, MCC: 0.4318, F1: 0.7143

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.63275 | val 0.72046
  Epoch 017 - train 0.60742 | val 0.76170
  Classification -> best τ=0.410 (val F1=0.2946)
  Directional -> Accuracy: 0.5536, MCC: 0.2124, F1: 0.6575

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.57801 | val 0.75282
  Epoch 011 - train 0.57637 | val 0.80387
  Classification -> best τ=0.480 (val F1=0.0952)
  Directional -> Accuracy: 0.5000, MCC: 0.0194, F1: 0.5306

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.65905 | val 0.64868
  Epoch 020 - train 0.60893 | val 0.68527
  Epoch 025 - train 0.60966 | val 0.67454
  Classification -> best τ=0.270 (val F1=0.5125)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.58289 | val 0.85669
  Epoch 011 - train 0.63506 | val 0.83027
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.66976 | val 0.76805
  Epoch 012 - train 0.65403 | val 0.71902
  Classification -> best τ=0.365 (val F1=0.3069)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.67859 | val 0.88798
  Epoch 013 - train 0.62049 | val 0.69239
  Classification -> best τ=0.460 (val F1=0.2933)
  Directional -> Accuracy: 0.5652, MCC: 0.1234, F1: 0.6429

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.65577 | val 0.68023
  Epoch 020 - train 0.57796 | val 0.67455
  Epoch 021 - train 0.58693 | val 0.69315
  Classification -> best τ=0.520 (val F1=0.4743)
  Directional -> Accuracy: 0.6279, MCC: 0.2329, F1: 0.7241

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.64541 | val 0.64099
  Epoch 019 - train 0.56594 | val 0.70712
  Classification -> best τ=0.585 (val F1=0.5689)
  Directional -> Accuracy: 0.3673, MCC: -0.1462, F1: 0.5231

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.66517 | val 1.40639
  Epoch 011 - train 0.67269 | val 1.64240
  Classification -> best τ=0.465 (val F1=0.3272)
  Directional -> Accuracy: 0.6429, MCC: 0.3203, F1: 0.6000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.64809 | val 0.94025
  Epoch 012 - train 0.63041 | val 1.10838
  Classification -> best τ=0.510 (val F1=0.2667)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.67035 | val 1.51946
  Epoch 011 - train 0.63973 | val 1.36216
  Classification -> best τ=0.395 (val F1=0.2004)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.64851 | val 0.72638
  Epoch 020 - train 0.58156 | val 0.69333
  Epoch 030 - train 0.55469 | val 0.86832
  Classification -> best τ=0.515 (val F1=0.1557)
  Directional -> Accuracy: 0.4286, MCC: -0.1399, F1: 0.4074

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.64262 | val 0.75116

[I 2026-02-25 02:08:09,975] Trial 149 finished with value: 0.2555642447066375 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.1, 'dropout': 0.7000000000000001, 'batch_size': 64, 'learning_rate': 0.004343694519813916, 'weight_decay': 0.0004374530669382936, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.6224058255576768, 'early_stopping_min_delta': 0.0047259335654706285}. Best is trial 140 with value: 0.29322408230766744.

  Epoch 014 - train 0.64097 | val 0.85105
  Classification -> best τ=0.500 (val F1=0.1663)
  Directional -> Accuracy: 0.4918, MCC: -0.0582, F1: 0.2439

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2555642447066375
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.63444 | val 0.88092
  Epoch 013 - train 0.63383 | val 0.90223
  Classification -> best τ=0.520 (val F1=0.2627)
  Directional -> Accuracy: 0.5263, MCC: -0.0267, F1: 0.2174

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.64727 | val 0.68896
  Epoch 017 - train 0.60123 | val 0.73550
  Classification -> best τ=0.415 (val F1=0.1754)
  Directional -> Accuracy: 0.6444, MCC: 0.3126, F1: 0.7647

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.65443 | val 0.66664
  Epoch 019 - train 0.64856 | val 0.72301
  Classification -> best τ=0.415 (val F1=0.3678)
  Directional -> Accuracy: 0.5532, MCC: 0.0866, F1: 0.6769

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.65824 | val 2.05432
  Epoch 011 - train 0.62920 | val 1.98071
  Classification -> best τ=0.490 (val F1=0.1698)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.60798 | val 0.66169
  Epoch 016 - train 0.60754 | val 0.67987
  Classification -> best τ=0.675 (val F1=0.3909)
  Directional -> Accuracy: 0.5098, MCC: 0.1905, F1: 0.1379

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.65364 | val 0.69930
  Epoch 015 - train 0.62629 | val 0.71080
  Classification -> best τ=0.540 (val F1=0.0976)
  Directional -> Accuracy: 0.5319, MCC: 0.1506, F1: 0.0833

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.65310 | val 0.76070
  Epoch 011 - train 0.64352 | val 0.77933
  Classification -> best τ=0.515 (val F1=0.2132)
  Directional -> Accuracy: 0.4638, MCC: 0.1149, F1: 0.5843

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.63671 | val 0.81213
  Epoch 011 - train 0.59660 | val 0.83416
  Classification -> best τ=0.530 (val F1=0.2331)
  Directional -> Accuracy: 0.4884, MCC: 0.1607, F1: 0.6071

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.62910 | val 0.67213
  Epoch 015 - train 0.64186 | val 0.69797
  Classification -> best τ=0.440 (val F1=0.3050)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.61072 | val 0.95041
  Epoch 011 - train 0.62381 | val 0.94143
  Classification -> best τ=0.435 (val F1=0.2043)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.62237 | val 1.59350
  Epoch 011 - train 0.61456 | val 1.64285
  Classification -> best τ=0.500 (val F1=0.2125)
  Directional -> Accuracy: 0.5000, MCC: 0.0744, F1: 0.6154

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.63111 | val 0.93287
  Epoch 011 - train 0.61004 | val 1.13406
  Classification -> best τ=0.440 (val F1=0.1955)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6588

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.61534 | val 0.86501
  Epoch 011 - train 0.59644 | val 0.97063
  Classification -> best τ=0.540 (val F1=0.0347)
  Directional -> Accuracy: 0.5000, MCC: -0.0588, F1: 0.2759

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.67387 | val 0.64325
  Epoch 020 - train 0.61091 | val 0.72763
  Epoch 021 - train 0.64327 | val 0.72702
  Classification -> best τ=0.345 (val F1=0.2667)
  Directional -> Accuracy: 0.5500, MCC: 0.1809, F1: 0.6824

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.62844 | val 1.61940
  Epoch 011 - train 0.61172 | val 1.79860
  Classification -> best τ=0.500 (val F1=0.1018)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.60028 | val 0.82751
  Epoch 013 - train 0.60329 | val 0.86829
  Classification -> best τ=0.545 (val F1=0.2655)
  Directional -> Accuracy: 0.5217, MCC: 0.0892, F1: 0.4000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.63074 | val 2.05672
  Epoch 011 - train 0.62015 | val 2.15530
  Classification -> best τ=0.565 (val F1=0.1342)
  Directional -> Accuracy: 0.3729, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.64531 | val 1.63451
  Epoch 011 - train 0.64613 | val 1.73041
  Classification -> best τ=0.445 (val F1=0.1039)
  Directional -> Accuracy: 0.6133, MCC: 0.1990, F1: 0.6742

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.62512 | val 0.94595
  Epoch 011 - train 0.62648 | val 1.03175
  Classification -> best τ=0.555 (val F1=0.2234)
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.60265 | val 0.69916
  Epoch 020 - train 0.58853 | val 0.71096
  Epoch 022 - train 0.59602 | val 0.74982
  Classification -> best τ=0.540 (val F1=0.3331)
  Directional -> Accuracy: 0.4933, MCC: 0.1360, F1: 0.1739

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.61118 | val 0.67784
  Epoch 016 - train 0.61123 | val 0.68588
  Classification -> best τ=0.495 (val F1=0.3278)
  Directional -> Accuracy: 0.5106, MCC: -0.0247, F1: 0.5965

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.68010 | val 0.81227
  Epoch 011 - train 0.65147 | val 0.79991
  Classification -> best τ=0.480 (val F1=0.1765)
  Directional -> Accuracy: 0.5152, MCC: 0.0304, F1: 0.5294

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.64882 | val 0.73440
  Epoch 013 - train 0.67320 | val 0.74487
  Classification -> best τ=0.555 (val F1=0.2554)
  Directional -> Accuracy: 0.5172, MCC: 0.1339, F1: 0.3913

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.63793 | val 0.72931
  Epoch 011 - train 0.63888 | val 0.73228
  Classification -> best τ=0.500 (val F1=0.1271)
  Directional -> Accuracy: 0.5231, MCC: 0.0455, F1: 0.5079

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.64029 | val 0.64688
  Epoch 020 - train 0.61145 | val 0.64191
  Epoch 026 - train 0.56889 | val 0.64636
  Classification -> best τ=0.495 (val F1=0.4388)
  Directional -> Accuracy: 0.5893, MCC: 0.2195, F1: 0.5490

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.63694 | val 0.74891
  Epoch 011 - train 0.63446 | val 0.75821
  Classification -> best τ=0.550 (val F1=0.1065)
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.63054 | val 0.73258
  Epoch 011 - train 0.64689 | val 0.71009
  Classification -> best τ=0.475 (val F1=0.0142)
  Directional -> Accuracy: 0.4524, MCC: 0.0212, F1: 0.2069

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.63268 | val 0.75783
  Epoch 013 - train 0.61258 | val 0.81787
  Classification -> best τ=0.495 (val F1=0.2391)
  Directional -> Accuracy: 0.5088, MCC: 0.2428, F1: 0.2222

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.61172 | val 0.72347
  Epoch 011 - train 0.67547 | val 0.75504
  Classification -> best τ=0.525 (val F1=0.1918)
  Directional -> Accuracy: 0.5122, MCC: 0.0603, F1: 0.4118

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.64242 | val 0.69313
  Epoch 011 - train 0.64993 | val 0.69335
  Classification -> best τ=0.510 (val F1=0.2725)
  Directional -> Accuracy: 0.4651, MCC: -0.0675, F1: 0.4889

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.65245 | val 0.72188
  Epoch 011 - train 0.61894 | val 0.74591
  Classification -> best τ=0.470 (val F1=0.0065)
  Directional -> Accuracy: 0.5581, MCC: 0.0940, F1: 0.6780

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.62554 | val 0.77324
  Epoch 014 - train 0.60301 | val 0.80999
  Classification -> best τ=0.455 (val F1=0.2161)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.63478 | val 0.69228
  Epoch 012 - train 0.61189 | val 0.69951
  Classification -> best τ=0.430 (val F1=0.3346)
  Directional -> Accuracy: 0.5753, MCC: 0.1768, F1: 0.5634

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.63162 | val 0.80839
  Epoch 011 - train 0.61849 | val 0.84502
  Classification -> best τ=0.480 (val F1=0.2025)
  Directional -> Accuracy: 0.5405, MCC: 0.1647, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.61846 | val 0.76790
  Epoch 011 - train 0.65134 | val 0.77047
  Classification -> best τ=0.495 (val F1=0.1902)
  Directional -> Accuracy: 0.4091, MCC: -0.2831, F1: 0.5806

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.62174 | val 0.69734
  Epoch 015 - train 0.60186 | val 0.74939
  Classification -> best τ=0.385 (val F1=0.3525)
  Directional -> Accuracy: 0.5152, MCC: 0.1279, F1: 0.4074

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.59090 | val 0.71602
  Epoch 011 - train 0.59528 | val 0.73154
  Classification -> best τ=0.550 (val F1=0.1846)
  Directional -> Accuracy: 0.5238, MCC: 0.1469, F1: 0.2308

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.63860 | val 0.88243
  Epoch 013 - train 0.62631 | val 0.94587
  Classification -> best τ=0.440 (val F1=0.2622)
  Directional -> Accuracy: 0.5179, MCC: 0.1149, F1: 0.6301

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.56615 | val 1.53840
  Epoch 011 - train 0.61742 | val 1.67309
  Classification -> best τ=0.570 (val F1=0.2815)
  Directional -> Accuracy: 0.4130, MCC: -0.0062, F1: 0.1818

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.65452 | val 0.67254
  Epoch 020 - train 0.61290 | val 0.64841
  Epoch 030 - train 0.59459 | val 0.63524
  Classification -> best τ=0.375 (val F1=0.4976)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.61946 | val 0.73787
  Epoch 014 - train 0.64065 | val 0.77572
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.64313 | val 0.82645
  Epoch 011 - train 0.63151 | val 0.83434
  Classification -> best τ=0.460 (val F1=0.2173)
  Directional -> Accuracy: 0.5067, MCC: 0.0499, F1: 0.6542

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.63226 | val 0.78367
  Epoch 014 - train 0.65697 | val 0.84859
  Classification -> best τ=0.450 (val F1=0.2748)
  Directional -> Accuracy: 0.4783, MCC: -0.0733, F1: 0.5862

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.58482 | val 0.79488
  Epoch 011 - train 0.63735 | val 0.82227
  Classification -> best τ=0.500 (val F1=0.1011)
  Directional -> Accuracy: 0.4186, MCC: -0.1240, F1: 0.0741

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.63812 | val 0.69082
  Epoch 011 - train 0.63468 | val 0.69802
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.64888 | val 1.24770
  Epoch 011 - train 0.65399 | val 1.32157
  Classification -> best τ=0.530 (val F1=0.1548)
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.64066 | val 0.98595
  Epoch 011 - train 0.61408 | val 1.02357
  Classification -> best τ=0.510 (val F1=0.3957)
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.62350 | val 1.13389
  Epoch 011 - train 0.63546 | val 1.20906
  Classification -> best τ=0.470 (val F1=0.1348)
  Directional -> Accuracy: 0.4815, MCC: -0.0131, F1: 0.1765

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.63138 | val 1.43818
  Epoch 011 - train 0.61877 | val 1.50462
  Classification -> best τ=0.595 (val F1=0.1168)
  Directional -> Accuracy: 0.5357, MCC: 0.1397, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.65359 | val 0.96255
  Epoch 011 - train 0.64997 | val 1.08478

[I 2026-02-25 02:09:47,388] Trial 150 finished with value: 0.21120638796820607 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 0.00030820516957708386, 'weight_decay': 8.225426078272914e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.5785862885229908, 'early_stopping_min_delta': 0.003842772534861511}. Best is trial 140 with value: 0.29322408230766744.

  Classification -> best τ=0.535 (val F1=0.1956)
  Directional -> Accuracy: 0.4590, MCC: -0.0864, F1: 0.4211

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.21120638796820607
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.65862 | val 1.10927
  Epoch 011 - train 0.63767 | val 1.12363
  Classification -> best τ=0.470 (val F1=0.1635)
  Directional -> Accuracy: 0.5132, MCC: 0.1137, F1: 0.6105

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.59700 | val 0.71720
  Epoch 011 - train 0.66375 | val 0.73640
  Classification -> best τ=0.455 (val F1=0.0793)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.69724 | val 0.71086
  Epoch 019 - train 0.62686 | val 0.77968
  Classification -> best τ=0.675 (val F1=0.4178)
  Directional -> Accuracy: 0.5319, MCC: 0.1314, F1: 0.3529

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.67500 | val 2.00201
  Epoch 011 - train 0.66587 | val 2.16947
  Classification -> best τ=0.370 (val F1=0.1511)
  Directional -> Accuracy: 0.5867, MCC: 0.1836, F1: 0.5867

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.55626 | val 0.75521
  Epoch 014 - train 0.53614 | val 0.76317
  Classification -> best τ=0.620 (val F1=0.4380)
  Directional -> Accuracy: 0.5294, MCC: 0.1273, F1: 0.3333

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.61854 | val 0.71206
  Epoch 011 - train 0.60195 | val 0.78389
  Classification -> best τ=0.560 (val F1=0.3394)
  Directional -> Accuracy: 0.5106, MCC: 0.0081, F1: 0.2069

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.68509 | val 0.68249
  Epoch 020 - train 0.61260 | val 0.85828
  Classification -> best τ=0.445 (val F1=0.2545)
  Directional -> Accuracy: 0.4058, MCC: -0.0695, F1: 0.5393

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.59108 | val 0.80106
  Epoch 014 - train 0.61402 | val 1.30285
  Classification -> best τ=0.415 (val F1=0.1752)
  Directional -> Accuracy: 0.4186, MCC: -0.0528, F1: 0.5614

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.65115 | val 0.90042
  Epoch 016 - train 0.55235 | val 0.92503
  Classification -> best τ=0.475 (val F1=0.1945)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.64008 | val 0.85187
  Epoch 012 - train 0.60691 | val 1.01862
  Classification -> best τ=0.450 (val F1=0.1816)
  Directional -> Accuracy: 0.4714, MCC: 0.0567, F1: 0.5843

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.63888 | val 1.81295
  Epoch 011 - train 0.65149 | val 1.60162
  Classification -> best τ=0.565 (val F1=0.2621)
  Directional -> Accuracy: 0.6200, MCC: 0.2271, F1: 0.5128

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.64237 | val 1.46022
  Epoch 011 - train 0.60701 | val 1.76582
  Classification -> best τ=0.385 (val F1=0.2594)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.62828 | val 1.22583
  Epoch 011 - train 0.60901 | val 1.23016
  Classification -> best τ=0.520 (val F1=0.1470)
  Directional -> Accuracy: 0.5000, MCC: -0.0138, F1: 0.4324

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.69558 | val 0.65911
  Epoch 020 - train 0.61822 | val 0.75919
  Epoch 022 - train 0.61607 | val 0.91777
  Classification -> best τ=0.425 (val F1=0.2845)
  Directional -> Accuracy: 0.6000, MCC: 0.2182, F1: 0.6667

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.62795 | val 1.34200
  Epoch 011 - train 0.59796 | val 1.86927
  Classification -> best τ=0.590 (val F1=0.2673)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.62963 | val 0.78697
  Epoch 011 - train 0.62327 | val 0.90733
  Classification -> best τ=0.500 (val F1=0.1421)
  Directional -> Accuracy: 0.5217, MCC: 0.0245, F1: 0.5926

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.64227 | val 2.16477
  Epoch 011 - train 0.67632 | val 2.15952
  Classification -> best τ=0.595 (val F1=0.0827)
  Directional -> Accuracy: 0.3729, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.64193 | val 1.07840
  Epoch 012 - train 0.61631 | val 2.05807
  Classification -> best τ=0.550 (val F1=0.2056)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.67401 | val 1.76169
  Epoch 011 - train 0.66964 | val 1.96864
  Classification -> best τ=0.415 (val F1=0.2166)
  Directional -> Accuracy: 0.5231, MCC: 0.1873, F1: 0.3922

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.62530 | val 1.10307
  Epoch 016 - train 0.60993 | val 1.09900
  Classification -> best τ=0.455 (val F1=0.3451)
  Directional -> Accuracy: 0.4667, MCC: -0.0010, F1: 0.2308

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.60626 | val 0.69950
  Epoch 018 - train 0.54526 | val 0.84737
  Classification -> best τ=0.405 (val F1=0.3740)
  Directional -> Accuracy: 0.4894, MCC: 0.1609, F1: 0.3684

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.65785 | val 0.79994
  Epoch 011 - train 0.63583 | val 0.88799
  Classification -> best τ=0.545 (val F1=0.2543)
  Directional -> Accuracy: 0.5606, MCC: 0.2108, F1: 0.2564

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.64178 | val 0.73451
  Epoch 011 - train 0.65425 | val 0.94294
  Classification -> best τ=0.550 (val F1=0.1883)
  Directional -> Accuracy: 0.5000, MCC: 0.1008, F1: 0.3556

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.64373 | val 0.71565
  Epoch 011 - train 0.65953 | val 0.76755
  Classification -> best τ=0.540 (val F1=0.1359)
  Directional -> Accuracy: 0.4923, MCC: -0.0049, F1: 0.5352

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.64485 | val 0.75241
  Epoch 011 - train 0.65801 | val 0.75298
  Classification -> best τ=0.475 (val F1=0.3730)
  Directional -> Accuracy: 0.5179, MCC: 0.0797, F1: 0.4490

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.62285 | val 0.97385
  Epoch 011 - train 0.64005 | val 1.09711
  Classification -> best τ=0.515 (val F1=0.1099)
  Directional -> Accuracy: 0.5870, MCC: 0.1754, F1: 0.5581

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.67077 | val 0.74606
  Epoch 011 - train 0.63536 | val 0.71735
  Classification -> best τ=0.565 (val F1=0.0913)
  Directional -> Accuracy: 0.5476, MCC: -0.1353, F1: 0.7077

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.62732 | val 1.14255
  Epoch 011 - train 0.64325 | val 1.07069
  Classification -> best τ=0.445 (val F1=0.2210)
  Directional -> Accuracy: 0.5789, MCC: 0.1053, F1: 0.6923

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.66647 | val 0.69385
  Epoch 015 - train 0.60433 | val 0.70226
  Classification -> best τ=0.605 (val F1=0.1918)
  Directional -> Accuracy: 0.5122, MCC: 0.0603, F1: 0.4118

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.76086 | val 0.81849
  Epoch 011 - train 0.61776 | val 0.87518
  Classification -> best τ=0.550 (val F1=0.2814)
  Directional -> Accuracy: 0.4884, MCC: -0.0318, F1: 0.3889

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.63124 | val 0.89020
  Epoch 013 - train 0.63100 | val 0.89901
  Classification -> best τ=0.620 (val F1=0.1204)
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.55466 | val 1.12658
  Epoch 015 - train 0.53026 | val 1.19293
  Classification -> best τ=0.365 (val F1=0.3309)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.61351 | val 0.75695
  Epoch 014 - train 0.59223 | val 0.97167
  Classification -> best τ=0.305 (val F1=0.3918)
  Directional -> Accuracy: 0.5753, MCC: 0.1768, F1: 0.5634

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.63624 | val 1.07887
  Epoch 016 - train 0.56899 | val 1.30693
  Classification -> best τ=0.470 (val F1=0.0967)
  Directional -> Accuracy: 0.5676, MCC: 0.1342, F1: 0.4667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.63997 | val 0.85483
  Epoch 011 - train 0.64152 | val 0.90417
  Classification -> best τ=0.485 (val F1=0.1329)
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.65081 | val 0.75264
  Epoch 012 - train 0.64040 | val 0.72927
  Classification -> best τ=0.345 (val F1=0.3855)
  Directional -> Accuracy: 0.5909, MCC: 0.3480, F1: 0.4706

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.59743 | val 1.12017
  Epoch 011 - train 0.58856 | val 1.21945
  Classification -> best τ=0.450 (val F1=0.2986)
  Directional -> Accuracy: 0.6429, MCC: 0.2828, F1: 0.6667

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.66766 | val 1.03126
  Epoch 011 - train 0.62157 | val 1.42863
  Classification -> best τ=0.400 (val F1=0.2110)
  Directional -> Accuracy: 0.5000, MCC: 0.0157, F1: 0.5333

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.60477 | val 1.88929
  Epoch 011 - train 0.56048 | val 2.28333
  Classification -> best τ=0.480 (val F1=0.3451)
  Directional -> Accuracy: 0.5870, MCC: 0.0062, F1: 0.7246

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.71419 | val 0.67992
  Epoch 020 - train 0.64495 | val 0.64760
  Epoch 026 - train 0.49463 | val 0.76580
  Classification -> best τ=0.425 (val F1=0.3973)
  Directional -> Accuracy: 0.4286, MCC: 0.1170, F1: 0.5484

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.70509 | val 0.71809
  Epoch 011 - train 0.65560 | val 0.74665
  Classification -> best τ=0.480 (val F1=0.4776)
  Directional -> Accuracy: 0.4865, MCC: 0.0752, F1: 0.1739

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.65115 | val 1.00662
  Epoch 012 - train 0.62062 | val 1.02745
  Classification -> best τ=0.395 (val F1=0.4361)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.64579 | val 0.74917
  Epoch 013 - train 0.60660 | val 1.47620
  Classification -> best τ=0.430 (val F1=0.2748)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.6857

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.62013 | val 0.79565
  Epoch 011 - train 0.56650 | val 0.78751
  Classification -> best τ=0.470 (val F1=0.2282)
  Directional -> Accuracy: 0.5581, MCC: 0.0813, F1: 0.6415

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.63641 | val 0.87551
  Epoch 020 - train 0.55951 | val 0.63510
  Epoch 022 - train 0.54878 | val 0.77853
  Classification -> best τ=0.600 (val F1=0.4795)
  Directional -> Accuracy: 0.3673, MCC: -0.1462, F1: 0.5231

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.65050 | val 0.99894
  Epoch 011 - train 0.67922 | val 0.88324
  Classification -> best τ=0.550 (val F1=0.1914)
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.70933 | val 1.12593
  Epoch 012 - train 0.68284 | val 1.12611
  Classification -> best τ=0.520 (val F1=0.2650)
  Directional -> Accuracy: 0.5357, MCC: 0.0728, F1: 0.5357

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.64476 | val 0.90055
  Epoch 011 - train 0.64853 | val 0.91033
  Classification -> best τ=0.405 (val F1=0.3040)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.62025 | val 1.50392
  Epoch 011 - train 0.61500 | val 1.84029
  Classification -> best τ=0.730 (val F1=0.1557)
  Directional -> Accuracy: 0.5000, MCC: -0.0187, F1: 0.6000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.64453 | val 0.78004
  Epoch 011 - train 0.65992 | val 0.84036

[I 2026-02-25 02:11:25,894] Trial 151 finished with value: 0.25216160083687683 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 0.0026271183476214415, 'weight_decay': 0.0001553819233664489, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.5435435709155061, 'early_stopping_min_delta': 0.00339572902077052}. Best is trial 140 with value: 0.29322408230766744.

  Classification -> best τ=0.470 (val F1=0.2575)
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.25216160083687683
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.65409 | val 0.90502
  Epoch 011 - train 0.60318 | val 0.94635
  Classification -> best τ=0.420 (val F1=0.2919)
  Directional -> Accuracy: 0.5658, MCC: 0.1351, F1: 0.5479

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.66640 | val 0.70080
  Epoch 011 - train 0.62713 | val 0.72573
  Classification -> best τ=0.525 (val F1=0.0406)
  Directional -> Accuracy: 0.6000, MCC: 0.1500, F1: 0.6897

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.67451 | val 1.06860
  Epoch 015 - train 0.61525 | val 1.07471
  Classification -> best τ=0.565 (val F1=0.2861)
  Directional -> Accuracy: 0.4894, MCC: 0.1383, F1: 0.0769

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.61435 | val 1.85853
  Epoch 011 - train 0.68244 | val 1.36826
  Classification -> best τ=0.440 (val F1=0.2148)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.62389 | val 1.04005
  Epoch 013 - train 0.57603 | val 0.93329
  Classification -> best τ=0.650 (val F1=0.3809)
  Directional -> Accuracy: 0.5686, MCC: 0.1909, F1: 0.4500

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.59499 | val 0.74818
  Epoch 014 - train 0.55578 | val 1.07432
  Classification -> best τ=0.550 (val F1=0.2357)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.68556 | val 0.78837
  Epoch 012 - train 0.67373 | val 0.80849
  Classification -> best τ=0.455 (val F1=0.1922)
  Directional -> Accuracy: 0.4058, MCC: -0.0695, F1: 0.5393

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.59309 | val 0.68023
  Epoch 020 - train 0.54228 | val 1.19595
  Epoch 021 - train 0.49642 | val 1.17686
  Classification -> best τ=0.215 (val F1=0.2588)
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.5902

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.64674 | val 0.91634
  Epoch 014 - train 0.64128 | val 1.07137
  Classification -> best τ=0.310 (val F1=0.2820)
  Directional -> Accuracy: 0.5306, MCC: -0.0594, F1: 0.0800

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.60768 | val 0.75226
  Epoch 011 - train 0.57443 | val 0.73384
  Classification -> best τ=0.535 (val F1=0.2576)
  Directional -> Accuracy: 0.4714, MCC: -0.0496, F1: 0.4478

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.61773 | val 2.01331
  Epoch 013 - train 0.63158 | val 1.72709
  Classification -> best τ=0.510 (val F1=0.2449)
  Directional -> Accuracy: 0.5200, MCC: 0.0467, F1: 0.5200

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.59065 | val 1.87316
  Epoch 014 - train 0.57412 | val 2.67284
  Classification -> best τ=0.600 (val F1=0.3062)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.60649 | val 1.09013
  Epoch 011 - train 0.61523 | val 1.17100
  Classification -> best τ=0.455 (val F1=0.2246)
  Directional -> Accuracy: 0.5476, MCC: 0.1220, F1: 0.5778

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.69971 | val 1.04728
  Epoch 012 - train 0.64532 | val 1.00372
  Classification -> best τ=0.445 (val F1=0.3126)
  Directional -> Accuracy: 0.5333, MCC: 0.0894, F1: 0.6500

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.62741 | val 1.31263
  Epoch 013 - train 0.63644 | val 1.45623
  Classification -> best τ=0.550 (val F1=0.2160)
  Directional -> Accuracy: 0.5385, MCC: 0.0154, F1: 0.0769

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.64963 | val 0.77206
  Epoch 016 - train 0.62276 | val 0.86998
  Classification -> best τ=0.320 (val F1=0.3750)
  Directional -> Accuracy: 0.6957, MCC: 0.4438, F1: 0.7742

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.67985 | val 1.25526
  Epoch 012 - train 0.64695 | val 1.85991
  Classification -> best τ=0.640 (val F1=0.2276)
  Directional -> Accuracy: 0.3729, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.66097 | val 1.15129
  Epoch 013 - train 0.62197 | val 1.49386
  Classification -> best τ=0.555 (val F1=0.2518)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.65222 | val 1.53395
  Epoch 012 - train 0.65066 | val 1.27165
  Classification -> best τ=0.385 (val F1=0.2752)
  Directional -> Accuracy: 0.5077, MCC: 0.1379, F1: 0.3846

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.65408 | val 0.90885
  Epoch 017 - train 0.57903 | val 0.74084
  Classification -> best τ=0.370 (val F1=0.2599)
  Directional -> Accuracy: 0.5333, MCC: 0.1252, F1: 0.4262

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.63567 | val 0.74323
  Epoch 020 - train 0.52674 | val 0.88231
  Epoch 021 - train 0.53014 | val 1.79081
  Classification -> best τ=0.570 (val F1=0.3380)
  Directional -> Accuracy: 0.4043, MCC: 0.1162, F1: 0.0667

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.67395 | val 0.82231
  Epoch 012 - train 0.65459 | val 1.13408
  Classification -> best τ=0.635 (val F1=0.1427)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.66146 | val 0.79989
  Epoch 011 - train 0.66740 | val 0.71922
  Classification -> best τ=0.530 (val F1=0.2405)
  Directional -> Accuracy: 0.5345, MCC: 0.0951, F1: 0.5263

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.66084 | val 0.67762
  Epoch 020 - train 0.64485 | val 1.34344
  Epoch 026 - train 0.60284 | val 0.68395
  Classification -> best τ=0.470 (val F1=0.3278)
  Directional -> Accuracy: 0.4615, MCC: -0.0657, F1: 0.6067

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.67221 | val 0.63785
  Epoch 019 - train 0.62077 | val 0.67999
  Classification -> best τ=0.425 (val F1=0.4045)
  Directional -> Accuracy: 0.5179, MCC: 0.1037, F1: 0.4000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.74230 | val 0.74847
  Epoch 011 - train 0.71285 | val 2.57380
  Classification -> best τ=0.495 (val F1=0.2935)
  Directional -> Accuracy: 0.4130, MCC: -0.1549, F1: 0.4255

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.68792 | val 0.69524
  Epoch 014 - train 0.63836 | val 1.03365
  Classification -> best τ=0.605 (val F1=0.1936)
  Directional -> Accuracy: 0.4286, MCC: -0.1021, F1: 0.3684

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.66298 | val 0.81286
  Epoch 012 - train 0.67267 | val 0.79408
  Classification -> best τ=0.405 (val F1=0.2099)
  Directional -> Accuracy: 0.5439, MCC: 0.3032, F1: 0.3158

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.73233 | val 0.76269
  Epoch 020 - train 0.58338 | val 0.89061
  Epoch 026 - train 0.45314 | val 1.11137
  Classification -> best τ=0.150 (val F1=0.4109)
  Directional -> Accuracy: 0.5366, MCC: 0.0241, F1: 0.6780

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.68798 | val 0.82902
  Epoch 017 - train 0.61963 | val 0.90247
  Classification -> best τ=0.630 (val F1=0.2814)
  Directional -> Accuracy: 0.5116, MCC: 0.0162, F1: 0.4000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.65232 | val 0.67821
  Epoch 016 - train 0.70201 | val 0.74772
  Classification -> best τ=0.565 (val F1=0.0593)
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.61619 | val 0.90706
  Epoch 011 - train 0.59535 | val 0.82140
  Classification -> best τ=0.480 (val F1=0.3270)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.62924 | val 1.11358
  Epoch 015 - train 0.63011 | val 1.09258
  Classification -> best τ=0.330 (val F1=0.3602)
  Directional -> Accuracy: 0.5753, MCC: 0.1768, F1: 0.5634

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.67051 | val 0.85320
  Epoch 011 - train 0.65419 | val 0.90099
  Classification -> best τ=0.435 (val F1=0.6236)
  Directional -> Accuracy: 0.5946, MCC: 0.2815, F1: 0.6939

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.67596 | val 0.88739
  Epoch 012 - train 0.64219 | val 1.02057
  Classification -> best τ=0.375 (val F1=0.2358)
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.65903 | val 0.71083
  Epoch 011 - train 0.64321 | val 0.69536
  Classification -> best τ=0.415 (val F1=0.3551)
  Directional -> Accuracy: 0.4848, MCC: 0.1648, F1: 0.2273

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.56356 | val 1.42001
  Epoch 011 - train 0.65076 | val 1.27489
  Classification -> best τ=0.560 (val F1=0.2741)
  Directional -> Accuracy: 0.4762, MCC: -0.0374, F1: 0.4211

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.61303 | val 1.08099
  Epoch 011 - train 0.57569 | val 1.09807
  Classification -> best τ=0.355 (val F1=0.3455)
  Directional -> Accuracy: 0.4643, MCC: -0.0138, F1: 0.6250

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.62522 | val 2.13889
  Epoch 011 - train 0.56469 | val 2.11782
  Classification -> best τ=0.585 (val F1=0.2698)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.61201 | val 0.78229
  Epoch 013 - train 0.56925 | val 0.65194
  Classification -> best τ=0.430 (val F1=0.3894)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.63197 | val 0.81044
  Epoch 013 - train 0.56026 | val 0.78351
  Classification -> best τ=0.545 (val F1=0.4240)
  Directional -> Accuracy: 0.4865, MCC: 0.1537, F1: 0.0952

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.61841 | val 0.75773
  Epoch 016 - train 0.65367 | val 0.86663
  Classification -> best τ=0.535 (val F1=0.4195)
  Directional -> Accuracy: 0.5200, MCC: 0.1155, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.67010 | val 0.69807
  Epoch 015 - train 0.64171 | val 1.06574
  Classification -> best τ=0.365 (val F1=0.3039)
  Directional -> Accuracy: 0.5217, MCC: 0.0093, F1: 0.6765

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.56436 | val 0.82198
  Epoch 013 - train 0.58657 | val 0.89288
  Classification -> best τ=0.445 (val F1=0.2855)
  Directional -> Accuracy: 0.5581, MCC: 0.0375, F1: 0.6984

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.67555 | val 1.37900
  Epoch 015 - train 0.59346 | val 0.84335
  Classification -> best τ=0.480 (val F1=0.3752)
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.69766 | val 1.41445
  Epoch 016 - train 0.65185 | val 1.81737
  Classification -> best τ=0.570 (val F1=0.1548)
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.64932 | val 0.89729
  Epoch 011 - train 0.67449 | val 1.10349
  Classification -> best τ=0.600 (val F1=0.4045)
  Directional -> Accuracy: 0.6071, MCC: 0.2608, F1: 0.6765

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.61006 | val 2.24593
  Epoch 011 - train 0.63202 | val 1.48291
  Classification -> best τ=0.310 (val F1=0.2766)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.60546 | val 2.48613
  Epoch 011 - train 0.62536 | val 2.43464
  Classification -> best τ=0.585 (val F1=0.1145)
  Directional -> Accuracy: 0.4643, MCC: -0.1768, F1: 0.6250

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.63205 | val 1.01167

[I 2026-02-25 02:13:10,185] Trial 152 finished with value: 0.28478649871702966 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 0.003731346512486228, 'weight_decay': 0.0002243675271149539, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.490558246353952, 'early_stopping_min_delta': 0.003067394049771562}. Best is trial 140 with value: 0.29322408230766744.

  Epoch 012 - train 0.63997 | val 0.85344
  Classification -> best τ=0.435 (val F1=0.2639)
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.28478649871702966
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.66610 | val 0.96515
  Epoch 014 - train 0.63727 | val 0.95829
  Classification -> best τ=0.630 (val F1=0.2510)
  Directional -> Accuracy: 0.5263, MCC: -0.0499, F1: 0.1429

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.63968 | val 0.70236
  Epoch 019 - train 0.60369 | val 0.77013
  Classification -> best τ=0.520 (val F1=0.1236)
  Directional -> Accuracy: 0.6444, MCC: 0.2545, F1: 0.7143

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.64481 | val 0.69776
  Epoch 016 - train 0.62750 | val 0.81191
  Classification -> best τ=0.615 (val F1=0.3005)
  Directional -> Accuracy: 0.5106, MCC: 0.1033, F1: 0.2581

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.64080 | val 2.05145
  Epoch 012 - train 0.65688 | val 1.41172
  Classification -> best τ=0.335 (val F1=0.1991)
  Directional -> Accuracy: 0.4933, MCC: 0.1080, F1: 0.2083

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.59589 | val 0.70184
  Epoch 014 - train 0.59764 | val 0.70743
  Classification -> best τ=0.470 (val F1=0.4063)
  Directional -> Accuracy: 0.5294, MCC: 0.0291, F1: 0.6471

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.60242 | val 0.71169
  Epoch 016 - train 0.57263 | val 0.74835
  Classification -> best τ=0.360 (val F1=0.2928)
  Directional -> Accuracy: 0.4894, MCC: 0.0000, F1: 0.6571

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.66192 | val 0.73189
  Epoch 014 - train 0.66685 | val 0.76144
  Classification -> best τ=0.455 (val F1=0.3364)
  Directional -> Accuracy: 0.4058, MCC: -0.0592, F1: 0.5495

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.65397 | val 1.72474
  Epoch 016 - train 0.59445 | val 2.08900
  Classification -> best τ=0.395 (val F1=0.2874)
  Directional -> Accuracy: 0.5581, MCC: 0.1297, F1: 0.5366

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.62067 | val 1.83158
  Epoch 012 - train 0.57884 | val 2.37987
  Classification -> best τ=0.430 (val F1=0.2855)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.64369 | val 0.71254
  Epoch 020 - train 0.52881 | val 0.77401
  Epoch 022 - train 0.50935 | val 1.01121
  Classification -> best τ=0.380 (val F1=0.1826)
  Directional -> Accuracy: 0.5286, MCC: 0.1260, F1: 0.5823

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.62648 | val 1.71588
  Epoch 013 - train 0.65921 | val 1.89870
  Classification -> best τ=0.315 (val F1=0.3759)
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.6301

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.63804 | val 1.40311
  Epoch 011 - train 0.60458 | val 1.57154
  Classification -> best τ=0.415 (val F1=0.2097)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.62749 | val 1.80488
  Epoch 016 - train 0.58797 | val 1.25770
  Classification -> best τ=0.420 (val F1=0.2246)
  Directional -> Accuracy: 0.4286, MCC: -0.1276, F1: 0.4545

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.64656 | val 1.18251
  Epoch 012 - train 0.68432 | val 0.88514
  Classification -> best τ=0.390 (val F1=0.0955)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.61699 | val 1.57533
  Epoch 012 - train 0.63450 | val 1.98357
  Classification -> best τ=0.495 (val F1=0.2315)
  Directional -> Accuracy: 0.5577, MCC: 0.1018, F1: 0.1481

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.64711 | val 0.85088
  Epoch 014 - train 0.60647 | val 0.85454
  Classification -> best τ=0.555 (val F1=0.3208)
  Directional -> Accuracy: 0.5652, MCC: 0.1121, F1: 0.6429

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.63296 | val 1.82965
  Epoch 013 - train 0.66356 | val 1.89020
  Classification -> best τ=0.750 (val F1=0.1842)
  Directional -> Accuracy: 0.4576, MCC: 0.2346, F1: 0.2381

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.64636 | val 1.21305
  Epoch 011 - train 0.61713 | val 1.66899
  Classification -> best τ=0.555 (val F1=0.1940)
  Directional -> Accuracy: 0.5600, MCC: 0.0884, F1: 0.6292

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.64974 | val 1.29166
  Epoch 011 - train 0.63900 | val 1.24093
  Classification -> best τ=0.475 (val F1=0.2668)
  Directional -> Accuracy: 0.4923, MCC: 0.1307, F1: 0.3265

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.62214 | val 0.92854
  Epoch 019 - train 0.61057 | val 0.80487
  Classification -> best τ=0.410 (val F1=0.3516)
  Directional -> Accuracy: 0.5067, MCC: 0.1052, F1: 0.3019

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.59476 | val 1.41446
  Epoch 016 - train 0.53001 | val 0.92757
  Classification -> best τ=0.515 (val F1=0.2845)
  Directional -> Accuracy: 0.4681, MCC: 0.0887, F1: 0.3590

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.74110 | val 0.75118
  Epoch 012 - train 0.65953 | val 0.85053
  Classification -> best τ=0.510 (val F1=0.1750)
  Directional -> Accuracy: 0.4848, MCC: -0.0346, F1: 0.5854

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.66471 | val 0.76412
  Epoch 014 - train 0.61300 | val 0.79749
  Classification -> best τ=0.545 (val F1=0.3450)
  Directional -> Accuracy: 0.5517, MCC: 0.1362, F1: 0.5357

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.67375 | val 0.79740
  Epoch 014 - train 0.66066 | val 0.87060
  Classification -> best τ=0.370 (val F1=0.0770)
  Directional -> Accuracy: 0.4923, MCC: 0.0445, F1: 0.6374

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.67540 | val 0.68851
  Epoch 019 - train 0.58341 | val 0.81012
  Classification -> best τ=0.585 (val F1=0.5119)
  Directional -> Accuracy: 0.5536, MCC: 0.3111, F1: 0.3243

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.67664 | val 0.89827
  Epoch 011 - train 0.68247 | val 1.06479
  Classification -> best τ=0.450 (val F1=0.2935)
  Directional -> Accuracy: 0.4783, MCC: 0.0793, F1: 0.6000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.62235 | val 0.67746
  Epoch 018 - train 0.61257 | val 0.73924
  Classification -> best τ=0.580 (val F1=0.1936)
  Directional -> Accuracy: 0.5952, MCC: 0.1680, F1: 0.6531

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.62940 | val 0.82690
  Epoch 011 - train 0.64050 | val 1.06771
  Classification -> best τ=0.435 (val F1=0.2575)
  Directional -> Accuracy: 0.5439, MCC: 0.3032, F1: 0.3158

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.64542 | val 1.15632
  Epoch 020 - train 0.60543 | val 1.54364
  Epoch 026 - train 0.51267 | val 2.07043
  Classification -> best τ=0.285 (val F1=0.4862)
  Directional -> Accuracy: 0.5366, MCC: 0.0241, F1: 0.6780

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.62719 | val 0.68904
  Epoch 014 - train 0.61093 | val 0.85099
  Classification -> best τ=0.520 (val F1=0.2814)
  Directional -> Accuracy: 0.4884, MCC: -0.0197, F1: 0.5217

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.69032 | val 0.66861
  Epoch 015 - train 0.61525 | val 0.77421
  Classification -> best τ=0.520 (val F1=0.2517)
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.60844 | val 0.83415
  Epoch 013 - train 0.58108 | val 0.93291
  Classification -> best τ=0.385 (val F1=0.2812)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.63739 | val 0.70568
  Epoch 012 - train 0.62214 | val 0.68924
  Classification -> best τ=0.335 (val F1=0.4351)
  Directional -> Accuracy: 0.5479, MCC: 0.1382, F1: 0.5075

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.71250 | val 0.92340
  Epoch 013 - train 0.58590 | val 0.91933
  Classification -> best τ=0.345 (val F1=0.2833)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.65322 | val 0.78644
  Epoch 011 - train 0.64772 | val 0.86316
  Classification -> best τ=0.450 (val F1=0.3121)
  Directional -> Accuracy: 0.4318, MCC: -0.1300, F1: 0.5283

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.63280 | val 0.70528
  Epoch 012 - train 0.61791 | val 0.73263
  Classification -> best τ=0.270 (val F1=0.3855)
  Directional -> Accuracy: 0.5455, MCC: 0.0344, F1: 0.6429

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.52505 | val 1.98110
  Epoch 011 - train 0.53874 | val 2.03421
  Classification -> best τ=0.530 (val F1=0.2486)
  Directional -> Accuracy: 0.4762, MCC: -0.0374, F1: 0.4211

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.63997 | val 0.80592
  Epoch 013 - train 0.61983 | val 0.99182
  Classification -> best τ=0.415 (val F1=0.2868)
  Directional -> Accuracy: 0.4821, MCC: -0.0234, F1: 0.5085

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.59783 | val 2.38817
  Epoch 011 - train 0.58240 | val 1.83991
  Classification -> best τ=0.580 (val F1=0.2441)
  Directional -> Accuracy: 0.5652, MCC: -0.0460, F1: 0.7059

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.60923 | val 0.65284
  Epoch 014 - train 0.62153 | val 0.73582
  Classification -> best τ=0.370 (val F1=0.4141)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.73069 | val 0.86961
  Epoch 013 - train 0.64630 | val 0.87712
  Classification -> best τ=0.535 (val F1=0.4312)
  Directional -> Accuracy: 0.4595, MCC: -0.0495, F1: 0.3333

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.65624 | val 0.94590
  Epoch 016 - train 0.63867 | val 0.88341
  Classification -> best τ=0.420 (val F1=0.3135)
  Directional -> Accuracy: 0.5200, MCC: 0.1155, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.64004 | val 1.07762
  Epoch 013 - train 0.66649 | val 1.14693
  Classification -> best τ=0.490 (val F1=0.2933)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.0000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.61742 | val 0.84433
  Epoch 011 - train 0.56288 | val 0.90271
  Classification -> best τ=0.585 (val F1=0.3651)
  Directional -> Accuracy: 0.5349, MCC: 0.2850, F1: 0.2857

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.67074 | val 0.83348
  Epoch 012 - train 0.63290 | val 0.91029
  Classification -> best τ=0.440 (val F1=0.6292)
  Directional -> Accuracy: 0.3673, MCC: -0.1468, F1: 0.5079

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.65317 | val 1.20869
  Epoch 012 - train 0.64896 | val 1.81549
  Classification -> best τ=0.530 (val F1=0.2231)
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.70255 | val 0.98961
  Epoch 011 - train 0.65629 | val 0.93021
  Classification -> best τ=0.515 (val F1=0.3119)
  Directional -> Accuracy: 0.5357, MCC: 0.0757, F1: 0.5517

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.65012 | val 1.22100
  Epoch 012 - train 0.67505 | val 1.28928
  Classification -> best τ=0.515 (val F1=0.1657)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.61287 | val 2.73932
  Epoch 011 - train 0.57520 | val 2.49196
  Classification -> best τ=0.355 (val F1=0.0317)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.66540 | val 0.86196

[I 2026-02-25 02:14:53,042] Trial 153 finished with value: 0.2837362600339135 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 0.004844660916109865, 'weight_decay': 0.0002942186835371216, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.49160833353497824, 'early_stopping_min_delta': 0.0033378372394705534}. Best is trial 140 with value: 0.29322408230766744.

  Epoch 011 - train 0.64861 | val 0.81531
  Classification -> best τ=0.505 (val F1=0.2544)
  Directional -> Accuracy: 0.4754, MCC: -0.0633, F1: 0.3846

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2837362600339135
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.64058 | val 0.99439
  Epoch 012 - train 0.60257 | val 0.94770
  Classification -> best τ=0.505 (val F1=0.2510)
  Directional -> Accuracy: 0.5000, MCC: -0.0655, F1: 0.2692

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.61335 | val 1.14413
  Epoch 011 - train 0.60579 | val 0.75414
  Classification -> best τ=0.480 (val F1=0.0406)
  Directional -> Accuracy: 0.6000, MCC: 0.1924, F1: 0.6400

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.60731 | val 0.65930
  Epoch 020 - train 0.55743 | val 0.98229
  Classification -> best τ=0.500 (val F1=0.3835)
  Directional -> Accuracy: 0.4681, MCC: -0.0195, F1: 0.1379

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.65561 | val 2.57088
  Epoch 011 - train 0.63325 | val 2.48312
  Classification -> best τ=0.375 (val F1=0.2782)
  Directional -> Accuracy: 0.5467, MCC: 0.1002, F1: 0.5526

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.59679 | val 0.78006
  Epoch 014 - train 0.56131 | val 0.71437
  Classification -> best τ=0.580 (val F1=0.4692)
  Directional -> Accuracy: 0.4706, MCC: -0.1007, F1: 0.5846

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.59472 | val 0.68230
  Epoch 020 - train 0.48256 | val 2.14892
  Classification -> best τ=0.380 (val F1=0.2928)
  Directional -> Accuracy: 0.5319, MCC: 0.0708, F1: 0.5769

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.62499 | val 0.84252
  Epoch 011 - train 0.63404 | val 0.86497
  Classification -> best τ=0.455 (val F1=0.2056)
  Directional -> Accuracy: 0.4348, MCC: 0.0787, F1: 0.5806

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.54244 | val 0.93630
  Epoch 011 - train 0.55543 | val 1.28023
  Classification -> best τ=0.510 (val F1=0.0792)
  Directional -> Accuracy: 0.4651, MCC: -0.0444, F1: 0.4651

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.57822 | val 0.75556
  Epoch 014 - train 0.55787 | val 0.91040
  Classification -> best τ=0.415 (val F1=0.2915)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.61602 | val 1.09161
  Epoch 013 - train 0.62644 | val 0.78210
  Classification -> best τ=0.485 (val F1=0.2974)
  Directional -> Accuracy: 0.4571, MCC: -0.0512, F1: 0.4865

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.59189 | val 2.31250
  Epoch 011 - train 0.57585 | val 3.28804
  Classification -> best τ=0.535 (val F1=0.1961)
  Directional -> Accuracy: 0.5800, MCC: 0.1411, F1: 0.4615

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.60392 | val 1.02671
  Epoch 011 - train 0.56617 | val 1.06948
  Classification -> best τ=0.515 (val F1=0.1906)
  Directional -> Accuracy: 0.5862, MCC: 0.1762, F1: 0.6250

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.57785 | val 1.89761
  Epoch 011 - train 0.54873 | val 1.93333
  Classification -> best τ=0.370 (val F1=0.2235)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.63048 | val 0.89352
  Epoch 011 - train 0.63471 | val 1.08971
  Classification -> best τ=0.455 (val F1=0.1363)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.59775 | val 2.65128
  Epoch 011 - train 0.58914 | val 2.43945
  Classification -> best τ=0.570 (val F1=0.2160)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.59609 | val 1.24734
  Epoch 013 - train 0.53253 | val 0.93450
  Classification -> best τ=0.310 (val F1=0.2592)
  Directional -> Accuracy: 0.5942, MCC: 0.2287, F1: 0.7200

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.63345 | val 2.36350
  Epoch 012 - train 0.63005 | val 1.92473
  Classification -> best τ=0.475 (val F1=0.0131)
  Directional -> Accuracy: 0.5424, MCC: -0.0717, F1: 0.6747

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.63873 | val 1.42914
  Epoch 012 - train 0.62748 | val 1.78331
  Classification -> best τ=0.555 (val F1=0.1923)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.63836 | val 1.54160
  Epoch 012 - train 0.64136 | val 1.90977
  Classification -> best τ=0.510 (val F1=0.2932)
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.59357 | val 0.92558
  Epoch 013 - train 0.58412 | val 0.88359
  Classification -> best τ=0.480 (val F1=0.2468)
  Directional -> Accuracy: 0.4933, MCC: 0.0747, F1: 0.2692

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.58330 | val 0.69025
  Epoch 020 - train 0.46869 | val 1.33724
  Classification -> best τ=0.450 (val F1=0.3687)
  Directional -> Accuracy: 0.4255, MCC: 0.1661, F1: 0.1290

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.62401 | val 1.17697
  Epoch 011 - train 0.61642 | val 0.87187
  Classification -> best τ=0.465 (val F1=0.0950)
  Directional -> Accuracy: 0.6212, MCC: 0.2425, F1: 0.6269

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.63908 | val 0.76695
  Epoch 011 - train 0.65165 | val 0.79705
  Classification -> best τ=0.555 (val F1=0.2710)
  Directional -> Accuracy: 0.4655, MCC: 0.0286, F1: 0.2791

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.64647 | val 0.80902
  Epoch 012 - train 0.62824 | val 1.00923
  Classification -> best τ=0.550 (val F1=0.2406)
  Directional -> Accuracy: 0.5538, MCC: 0.1218, F1: 0.5915

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.58555 | val 0.66635
  Epoch 017 - train 0.51996 | val 0.73975
  Classification -> best τ=0.525 (val F1=0.4272)
  Directional -> Accuracy: 0.4821, MCC: 0.1096, F1: 0.1714

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.58235 | val 0.78576
  Epoch 011 - train 0.59859 | val 1.03918
  Classification -> best τ=0.510 (val F1=0.2935)
  Directional -> Accuracy: 0.4348, MCC: -0.0693, F1: 0.5357

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.63495 | val 0.72313
  Epoch 011 - train 0.58966 | val 0.79821
  Classification -> best τ=0.515 (val F1=0.0589)
  Directional -> Accuracy: 0.5476, MCC: 0.0962, F1: 0.5778

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.60493 | val 1.17620
  Epoch 013 - train 0.57413 | val 1.25964
  Classification -> best τ=0.510 (val F1=0.3616)
  Directional -> Accuracy: 0.4737, MCC: 0.1685, F1: 0.1176

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.57464 | val 0.69983
  Epoch 014 - train 0.55376 | val 0.92709
  Classification -> best τ=0.480 (val F1=0.3278)
  Directional -> Accuracy: 0.5854, MCC: 0.1890, F1: 0.7119

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.57140 | val 0.70521
  Epoch 011 - train 0.58093 | val 0.78371
  Classification -> best τ=0.485 (val F1=0.2814)
  Directional -> Accuracy: 0.5116, MCC: 0.0179, F1: 0.4324

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.62056 | val 0.82369
  Epoch 013 - train 0.58392 | val 0.95272
  Classification -> best τ=0.460 (val F1=0.2282)
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.56770 | val 0.94206
  Epoch 012 - train 0.54001 | val 1.15371
  Classification -> best τ=0.415 (val F1=0.2932)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.58093 | val 0.74823
  Epoch 013 - train 0.58391 | val 1.02287
  Classification -> best τ=0.390 (val F1=0.3809)
  Directional -> Accuracy: 0.5616, MCC: 0.1446, F1: 0.5556

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.56188 | val 1.01212
  Epoch 011 - train 0.61480 | val 1.20952
  Classification -> best τ=0.455 (val F1=0.4303)
  Directional -> Accuracy: 0.5676, MCC: 0.1737, F1: 0.6522

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.63333 | val 1.00523
  Epoch 011 - train 0.60599 | val 1.05794
  Classification -> best τ=0.450 (val F1=0.1902)
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.59757 | val 0.77984
  Epoch 011 - train 0.59763 | val 0.81718
  Classification -> best τ=0.455 (val F1=0.3254)
  Directional -> Accuracy: 0.5606, MCC: 0.1915, F1: 0.5085

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.53524 | val 1.13106
  Epoch 013 - train 0.52845 | val 1.20295
  Classification -> best τ=0.520 (val F1=0.2568)
  Directional -> Accuracy: 0.7143, MCC: 0.4404, F1: 0.7000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.58463 | val 1.79377
  Epoch 012 - train 0.63031 | val 1.55700
  Classification -> best τ=0.415 (val F1=0.3846)
  Directional -> Accuracy: 0.5179, MCC: 0.1353, F1: 0.6400

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.59495 | val 2.44564
  Epoch 012 - train 0.53568 | val 3.01552
  Classification -> best τ=0.515 (val F1=0.3050)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.67686 | val 0.65805
  Epoch 020 - train 0.50736 | val 0.79534
  Epoch 021 - train 0.56580 | val 0.92949
  Classification -> best τ=0.460 (val F1=0.4141)
  Directional -> Accuracy: 0.3878, MCC: 0.0180, F1: 0.5312

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.63672 | val 0.76411
  Epoch 011 - train 0.52833 | val 0.76721
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.63645 | val 1.03250
  Epoch 012 - train 0.61318 | val 1.13910
  Classification -> best τ=0.435 (val F1=0.4279)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.61079 | val 0.84912
  Epoch 011 - train 0.62556 | val 0.88028
  Classification -> best τ=0.460 (val F1=0.3669)
  Directional -> Accuracy: 0.5435, MCC: 0.0790, F1: 0.6667

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.54600 | val 0.87792
  Epoch 011 - train 0.60781 | val 0.94722
  Classification -> best τ=0.480 (val F1=0.2282)
  Directional -> Accuracy: 0.6047, MCC: 0.1753, F1: 0.7018

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.57492 | val 0.66789
  Epoch 020 - train 0.47301 | val 0.52052
  Epoch 030 - train 0.44027 | val 0.84314
  Classification -> best τ=0.210 (val F1=0.4682)
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.59648 | val 1.44058
  Epoch 011 - train 0.65355 | val 1.53025
  Classification -> best τ=0.430 (val F1=0.1545)
  Directional -> Accuracy: 0.6250, MCC: 0.3031, F1: 0.5532

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.62779 | val 1.09790
  Epoch 013 - train 0.61926 | val 1.34381
  Classification -> best τ=0.655 (val F1=0.3241)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.66898 | val 1.28680
  Epoch 011 - train 0.60881 | val 1.35629
  Classification -> best τ=0.445 (val F1=0.2079)
  Directional -> Accuracy: 0.5556, MCC: 0.1310, F1: 0.6842

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.56594 | val 1.82294
  Epoch 011 - train 0.61479 | val 2.02860
  Classification -> best τ=0.520 (val F1=0.1168)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.60944 | val 0.68919
  Epoch 011 - train 0.57541 | val 0.71077

[I 2026-02-25 02:16:28,191] Trial 154 finished with value: 0.25635679631569297 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.6000000000000001, 'batch_size': 32, 'learning_rate': 0.002080624738683885, 'weight_decay': 0.0002357725241140045, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.5243470521054063, 'early_stopping_min_delta': 0.004252245111292167}. Best is trial 140 with value: 0.29322408230766744.

  Classification -> best τ=0.480 (val F1=0.0328)
  Directional -> Accuracy: 0.4426, MCC: -0.1069, F1: 0.4848

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.25635679631569297
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.64035 | val 1.03836
  Epoch 012 - train 0.64730 | val 2.16140
  Classification -> best τ=0.555 (val F1=0.2036)
  Directional -> Accuracy: 0.5132, MCC: -0.0472, F1: 0.2449

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.69346 | val 0.79451
  Epoch 018 - train 0.57035 | val 0.81387
  Classification -> best τ=0.405 (val F1=0.2722)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.64827 | val 0.66384
  Epoch 018 - train 0.59897 | val 0.69248
  Classification -> best τ=0.475 (val F1=0.3308)
  Directional -> Accuracy: 0.4255, MCC: -0.1374, F1: 0.2286

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.66340 | val 1.69347
  Epoch 011 - train 0.69125 | val 1.21730
  Classification -> best τ=0.395 (val F1=0.1746)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.61957 | val 0.69534
  Epoch 015 - train 0.65839 | val 0.80529
  Classification -> best τ=0.605 (val F1=0.4513)
  Directional -> Accuracy: 0.5882, MCC: 0.2031, F1: 0.5333

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.63273 | val 0.72028
  Epoch 012 - train 0.59377 | val 0.72171
  Classification -> best τ=0.530 (val F1=0.1664)
  Directional -> Accuracy: 0.5532, MCC: 0.1151, F1: 0.3636

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.66962 | val 0.72219
  Epoch 011 - train 0.66969 | val 0.72210
  Classification -> best τ=0.620 (val F1=0.1805)
  Directional -> Accuracy: 0.5797, MCC: -0.1002, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.63351 | val 1.53302
  Epoch 016 - train 0.57410 | val 1.83440
  Classification -> best τ=0.555 (val F1=0.1502)
  Directional -> Accuracy: 0.5581, MCC: -0.0473, F1: 0.0952

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.59446 | val 1.30708
  Epoch 011 - train 0.59784 | val 1.40028
  Classification -> best τ=0.350 (val F1=0.2408)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.59985 | val 0.76014
  Epoch 011 - train 0.65286 | val 0.72536
  Classification -> best τ=0.420 (val F1=0.2241)
  Directional -> Accuracy: 0.4429, MCC: 0.0407, F1: 0.5979

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.62296 | val 1.61942
  Epoch 011 - train 0.65913 | val 1.73064
  Classification -> best τ=0.550 (val F1=0.3613)
  Directional -> Accuracy: 0.6000, MCC: 0.2059, F1: 0.3333

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.65545 | val 1.12089
  Epoch 011 - train 0.57858 | val 1.20323
  Classification -> best τ=0.375 (val F1=0.2097)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.60787 | val 0.98150
  Epoch 013 - train 0.60056 | val 0.88789
  Classification -> best τ=0.265 (val F1=0.2731)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.64986 | val 0.64119
  Epoch 013 - train 0.66600 | val 0.72923
  Classification -> best τ=0.430 (val F1=0.3768)
  Directional -> Accuracy: 0.5667, MCC: 0.1383, F1: 0.6176

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.62216 | val 1.74604
  Epoch 012 - train 0.62378 | val 1.66275
  Classification -> best τ=0.615 (val F1=0.2673)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.62504 | val 0.81478
  Epoch 011 - train 0.63880 | val 0.88441
  Classification -> best τ=0.640 (val F1=0.2933)
  Directional -> Accuracy: 0.4638, MCC: -0.0126, F1: 0.0513

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.67755 | val 2.34095
  Epoch 011 - train 0.66190 | val 2.20148
  Classification -> best τ=0.360 (val F1=0.0660)
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.65509 | val 1.01441
  Epoch 011 - train 0.64119 | val 1.15417
  Classification -> best τ=0.365 (val F1=0.0784)
  Directional -> Accuracy: 0.6133, MCC: 0.1424, F1: 0.7563

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.62994 | val 1.52495
  Epoch 011 - train 0.64855 | val 1.86303
  Classification -> best τ=0.495 (val F1=0.2234)
  Directional -> Accuracy: 0.4615, MCC: 0.0668, F1: 0.2553

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.67262 | val 0.68642
  Epoch 017 - train 0.62493 | val 0.88806
  Classification -> best τ=0.480 (val F1=0.3038)
  Directional -> Accuracy: 0.4933, MCC: 0.1859, F1: 0.1364

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.60544 | val 0.71514
  Epoch 018 - train 0.57421 | val 0.78983
  Classification -> best τ=0.400 (val F1=0.3740)
  Directional -> Accuracy: 0.4255, MCC: 0.1661, F1: 0.1290

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.63498 | val 1.13469
  Epoch 011 - train 0.66557 | val 1.19294
  Classification -> best τ=0.685 (val F1=0.2319)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.67653 | val 0.71465
  Epoch 014 - train 0.67651 | val 0.72378
  Classification -> best τ=0.505 (val F1=0.2405)
  Directional -> Accuracy: 0.4828, MCC: -0.0348, F1: 0.5161

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.63017 | val 0.77113
  Epoch 016 - train 0.64471 | val 0.81491
  Classification -> best τ=0.550 (val F1=0.0835)
  Directional -> Accuracy: 0.5385, MCC: 0.0725, F1: 0.5000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.61289 | val 0.70462
  Epoch 012 - train 0.61395 | val 0.76836
  Classification -> best τ=0.510 (val F1=0.3727)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.59807 | val 0.88239
  Epoch 011 - train 0.64559 | val 0.82302
  Classification -> best τ=0.580 (val F1=0.1048)
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.66489 | val 0.80284
  Epoch 017 - train 0.62615 | val 0.89330
  Classification -> best τ=0.565 (val F1=0.3203)
  Directional -> Accuracy: 0.4762, MCC: -0.0694, F1: 0.5417

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.61952 | val 0.74012
  Epoch 012 - train 0.62941 | val 0.90805
  Classification -> best τ=0.375 (val F1=0.1914)
  Directional -> Accuracy: 0.5439, MCC: 0.2554, F1: 0.3500

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.61262 | val 0.67254
  Epoch 020 - train 0.54988 | val 0.91607
  Epoch 021 - train 0.50615 | val 1.76485
  Classification -> best τ=0.485 (val F1=0.4181)
  Directional -> Accuracy: 0.5854, MCC: 0.1635, F1: 0.6222

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.62829 | val 0.87169
  Epoch 013 - train 0.60389 | val 0.99741
  Classification -> best τ=0.510 (val F1=0.2814)
  Directional -> Accuracy: 0.5581, MCC: 0.1150, F1: 0.5366

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.64148 | val 0.68234
  Epoch 015 - train 0.56131 | val 0.86843
  Classification -> best τ=0.745 (val F1=0.1204)
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.61789 | val 0.92439
  Epoch 011 - train 0.60014 | val 0.93391
  Classification -> best τ=0.505 (val F1=0.4023)
  Directional -> Accuracy: 0.4200, MCC: -0.1394, F1: 0.2927

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.64425 | val 0.69280
  Epoch 012 - train 0.62175 | val 0.87927
  Classification -> best τ=0.380 (val F1=0.3396)
  Directional -> Accuracy: 0.5342, MCC: 0.1140, F1: 0.4848

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.61787 | val 0.84234
  Epoch 011 - train 0.70556 | val 0.82431
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.64848 | val 1.13701
  Epoch 011 - train 0.69393 | val 1.05701
  Classification -> best τ=0.470 (val F1=0.3121)
  Directional -> Accuracy: 0.6591, MCC: 0.3240, F1: 0.6667

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.64707 | val 0.77762
  Epoch 011 - train 0.63923 | val 0.75953
  Classification -> best τ=0.295 (val F1=0.3342)
  Directional -> Accuracy: 0.6061, MCC: 0.2818, F1: 0.5667

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.60076 | val 1.16203
  Epoch 011 - train 0.54789 | val 1.21732
  Classification -> best τ=0.495 (val F1=0.2451)
  Directional -> Accuracy: 0.6190, MCC: 0.2864, F1: 0.5294

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.62099 | val 0.96143
  Epoch 011 - train 0.63598 | val 0.87086
  Classification -> best τ=0.425 (val F1=0.3039)
  Directional -> Accuracy: 0.4821, MCC: 0.0625, F1: 0.6329

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.60653 | val 1.08756
  Epoch 011 - train 0.63363 | val 1.36536
  Classification -> best τ=0.540 (val F1=0.2659)
  Directional -> Accuracy: 0.3913, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.64633 | val 0.71655
  Epoch 019 - train 0.60324 | val 0.63254
  Classification -> best τ=0.385 (val F1=0.5247)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.69960 | val 0.82391
  Epoch 012 - train 0.54380 | val 0.80139
  Classification -> best τ=0.500 (val F1=0.3545)
  Directional -> Accuracy: 0.4324, MCC: -0.1093, F1: 0.2759

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.64094 | val 0.80438
  Epoch 015 - train 0.61416 | val 0.74389
  Classification -> best τ=0.415 (val F1=0.2802)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.64902 | val 1.12885
  Epoch 012 - train 0.65990 | val 1.08114
  Classification -> best τ=0.420 (val F1=0.3989)
  Directional -> Accuracy: 0.5652, MCC: 0.2416, F1: 0.3333

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.61064 | val 0.83378
  Epoch 015 - train 0.51744 | val 1.58240
  Classification -> best τ=0.455 (val F1=0.4799)
  Directional -> Accuracy: 0.6279, MCC: 0.2616, F1: 0.7419

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.70346 | val 0.99897
  Epoch 018 - train 0.55995 | val 0.80991
  Classification -> best τ=0.495 (val F1=0.3752)
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.70289 | val 1.20241
  Epoch 011 - train 0.65953 | val 1.10732
  Classification -> best τ=0.430 (val F1=0.2042)
  Directional -> Accuracy: 0.5536, MCC: 0.1588, F1: 0.4444

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.63497 | val 1.44073
  Epoch 013 - train 0.63264 | val 1.10891
  Classification -> best τ=0.705 (val F1=0.2536)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.66359 | val 1.48169
  Epoch 012 - train 0.63406 | val 1.66951
  Classification -> best τ=0.505 (val F1=0.1847)
  Directional -> Accuracy: 0.4074, MCC: -0.1823, F1: 0.3846

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.64260 | val 1.94395
  Epoch 013 - train 0.60300 | val 2.51586
  Classification -> best τ=0.475 (val F1=0.1168)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.66767 | val 0.85216

[I 2026-02-25 02:18:03,889] Trial 155 finished with value: 0.2670227749433153 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 0.004492094450894059, 'weight_decay': 0.00032533163874009233, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.4528806849278975, 'early_stopping_min_delta': 0.0029571715277926505}. Best is trial 140 with value: 0.29322408230766744.

  Epoch 013 - train 0.62587 | val 1.44502
  Classification -> best τ=0.645 (val F1=0.3892)
  Directional -> Accuracy: 0.5082, MCC: -0.0258, F1: 0.2105

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2670227749433153
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.66900 | val 1.00402
  Epoch 015 - train 0.62125 | val 1.19422
  Classification -> best τ=0.500 (val F1=0.2627)
  Directional -> Accuracy: 0.4737, MCC: 0.0102, F1: 0.5745

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.64329 | val 0.85007
  Epoch 011 - train 0.60705 | val 0.78560
  Classification -> best τ=0.490 (val F1=0.1236)
  Directional -> Accuracy: 0.6667, MCC: 0.3664, F1: 0.6667

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.66370 | val 0.72993
  Epoch 020 - train 0.60355 | val 0.80538
  Epoch 024 - train 0.57697 | val 1.61796
  Classification -> best τ=0.745 (val F1=0.3237)
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.65211 | val 1.77851
  Epoch 011 - train 0.65754 | val 2.31419
  Classification -> best τ=0.375 (val F1=0.1915)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.57052 | val 0.69083
  Epoch 014 - train 0.58112 | val 0.75934
  Classification -> best τ=0.545 (val F1=0.3627)
  Directional -> Accuracy: 0.5490, MCC: 0.1500, F1: 0.7013

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.61919 | val 0.68823
  Epoch 018 - train 0.51207 | val 1.10186
  Classification -> best τ=0.460 (val F1=0.2357)
  Directional -> Accuracy: 0.5957, MCC: 0.1919, F1: 0.5366

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.64371 | val 0.76797
  Epoch 014 - train 0.65515 | val 0.75528
  Classification -> best τ=0.310 (val F1=0.2256)
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.58592 | val 0.68836
  Epoch 020 - train 0.49634 | val 0.91217
  Epoch 021 - train 0.58713 | val 0.97653
  Classification -> best τ=0.185 (val F1=0.1214)
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.5902

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.64903 | val 0.84647
  Epoch 012 - train 0.63342 | val 1.14471
  Classification -> best τ=0.390 (val F1=0.2820)
  Directional -> Accuracy: 0.5306, MCC: 0.0474, F1: 0.4651

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.62630 | val 0.75412
  Epoch 017 - train 0.56598 | val 0.91124
  Classification -> best τ=0.430 (val F1=0.1826)
  Directional -> Accuracy: 0.4571, MCC: 0.0236, F1: 0.5778

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.64528 | val 1.59789
  Epoch 012 - train 0.62265 | val 1.91378
  Classification -> best τ=0.570 (val F1=0.3118)
  Directional -> Accuracy: 0.6200, MCC: 0.2766, F1: 0.3448

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.66442 | val 1.32085
  Epoch 011 - train 0.63588 | val 1.29991
  Classification -> best τ=0.580 (val F1=0.1085)
  Directional -> Accuracy: 0.5345, MCC: 0.1890, F1: 0.1290

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.70033 | val 0.90481
  Epoch 011 - train 0.55807 | val 1.04059
  Classification -> best τ=0.430 (val F1=0.2235)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.66656 | val 0.73811
  Epoch 011 - train 0.67948 | val 0.72203
  Classification -> best τ=0.585 (val F1=0.3864)
  Directional -> Accuracy: 0.5167, MCC: 0.0765, F1: 0.1212

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.60534 | val 1.75541
  Epoch 011 - train 0.59398 | val 1.87391
  Classification -> best τ=0.610 (val F1=0.2160)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.62642 | val 0.80413
  Epoch 013 - train 0.62744 | val 0.96401
  Classification -> best τ=0.465 (val F1=0.2230)
  Directional -> Accuracy: 0.5072, MCC: 0.0467, F1: 0.4138

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.68436 | val 1.45143
  Epoch 011 - train 0.64959 | val 1.59236
  Classification -> best τ=0.660 (val F1=0.1291)
  Directional -> Accuracy: 0.3729, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.63871 | val 1.95508
  Epoch 011 - train 0.61103 | val 2.01006
  Classification -> best τ=0.405 (val F1=0.1733)
  Directional -> Accuracy: 0.5733, MCC: 0.0399, F1: 0.6923

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.66055 | val 1.73247
  Epoch 011 - train 0.63145 | val 1.55153
  Classification -> best τ=0.395 (val F1=0.2061)
  Directional -> Accuracy: 0.5077, MCC: 0.0510, F1: 0.5000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.61802 | val 0.66410
  Epoch 016 - train 0.59345 | val 0.84427
  Classification -> best τ=0.410 (val F1=0.2669)
  Directional -> Accuracy: 0.4933, MCC: 0.1080, F1: 0.2083

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.62806 | val 0.88560
  Epoch 018 - train 0.54442 | val 0.99009
  Classification -> best τ=0.425 (val F1=0.3740)
  Directional -> Accuracy: 0.4468, MCC: 0.2057, F1: 0.1875

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.65915 | val 0.92235
  Epoch 011 - train 0.66404 | val 1.02843
  Classification -> best τ=0.540 (val F1=0.1950)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.67412 | val 0.90173
  Epoch 011 - train 0.67295 | val 0.85136
  Classification -> best τ=0.600 (val F1=0.3282)
  Directional -> Accuracy: 0.5862, MCC: 0.1841, F1: 0.6000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.67174 | val 0.88779
  Epoch 011 - train 0.64999 | val 1.01326
  Classification -> best τ=0.380 (val F1=0.2970)
  Directional -> Accuracy: 0.4769, MCC: 0.0000, F1: 0.6458

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.64112 | val 0.66736
  Epoch 020 - train 0.59180 | val 0.76410
  Epoch 023 - train 0.57430 | val 0.75507
  Classification -> best τ=0.370 (val F1=0.4436)
  Directional -> Accuracy: 0.5357, MCC: 0.1728, F1: 0.3810

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.71645 | val 1.16971
  Epoch 011 - train 0.62198 | val 1.30046
  Classification -> best τ=0.450 (val F1=0.2935)
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.62480 | val 0.81581
  Epoch 011 - train 0.68309 | val 0.72578
  Classification -> best τ=0.510 (val F1=0.1334)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.60453 | val 0.94823
  Epoch 011 - train 0.59425 | val 1.03515
  Classification -> best τ=0.455 (val F1=0.2945)
  Directional -> Accuracy: 0.5088, MCC: 0.2428, F1: 0.2222

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.67944 | val 0.93590
  Epoch 020 - train 0.53166 | val 0.79877
  Epoch 024 - train 0.62298 | val 2.17554
  Classification -> best τ=0.290 (val F1=0.3518)
  Directional -> Accuracy: 0.5366, MCC: 0.0241, F1: 0.6780

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.66233 | val 0.81005
  Epoch 013 - train 0.59832 | val 0.71073
  Classification -> best τ=0.465 (val F1=0.3244)
  Directional -> Accuracy: 0.5116, MCC: 0.0353, F1: 0.5882

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.68488 | val 0.82620
  Epoch 012 - train 0.67830 | val 0.82186
  Classification -> best τ=0.510 (val F1=0.3521)
  Directional -> Accuracy: 0.5116, MCC: 0.0509, F1: 0.4324

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.62825 | val 1.23750
  Epoch 011 - train 0.66088 | val 0.85086
  Classification -> best τ=0.600 (val F1=0.2399)
  Directional -> Accuracy: 0.4800, MCC: 0.1319, F1: 0.0714

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.64660 | val 0.89591
  Epoch 012 - train 0.60943 | val 1.05795
  Classification -> best τ=0.440 (val F1=0.3615)
  Directional -> Accuracy: 0.5616, MCC: 0.1446, F1: 0.5556

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.63591 | val 1.35645
  Epoch 011 - train 0.62664 | val 1.35832
  Classification -> best τ=0.450 (val F1=0.4951)
  Directional -> Accuracy: 0.5676, MCC: 0.1737, F1: 0.6522

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.65644 | val 0.90392
  Epoch 011 - train 0.67306 | val 0.97313
  Classification -> best τ=0.510 (val F1=0.1443)
  Directional -> Accuracy: 0.5682, MCC: 0.1643, F1: 0.6275

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.66614 | val 0.69927
  Epoch 015 - train 0.57700 | val 0.79253
  Classification -> best τ=0.440 (val F1=0.4182)
  Directional -> Accuracy: 0.5758, MCC: 0.1399, F1: 0.6216

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.59692 | val 1.03321
  Epoch 011 - train 0.60346 | val 1.21830
  Classification -> best τ=0.515 (val F1=0.2251)
  Directional -> Accuracy: 0.6190, MCC: 0.2864, F1: 0.5294

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.64947 | val 1.22197
  Epoch 011 - train 0.63974 | val 1.19278
  Classification -> best τ=0.340 (val F1=0.2868)
  Directional -> Accuracy: 0.5179, MCC: 0.1353, F1: 0.6400

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.57062 | val 1.50849
  Epoch 012 - train 0.58451 | val 2.21413
  Classification -> best τ=0.555 (val F1=0.3107)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.57050 | val 0.78974
  Epoch 020 - train 0.54010 | val 0.59055
  Epoch 030 - train 0.46614 | val 0.64944
  Classification -> best τ=0.245 (val F1=0.5125)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.73603 | val 0.70408
  Epoch 013 - train 0.54977 | val 0.80948
  Classification -> best τ=0.480 (val F1=0.4312)
  Directional -> Accuracy: 0.4595, MCC: -0.0710, F1: 0.4444

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.61495 | val 0.87897
  Epoch 012 - train 0.59287 | val 1.11657
  Classification -> best τ=0.385 (val F1=0.3595)
  Directional -> Accuracy: 0.5200, MCC: 0.1633, F1: 0.6727

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.68092 | val 0.78514
  Epoch 019 - train 0.65858 | val 1.09526
  Classification -> best τ=0.480 (val F1=0.2933)
  Directional -> Accuracy: 0.5000, MCC: 0.1427, F1: 0.0800

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.65147 | val 0.90293
  Epoch 018 - train 0.56231 | val 1.05576
  Classification -> best τ=0.400 (val F1=0.2282)
  Directional -> Accuracy: 0.6279, MCC: 0.2419, F1: 0.7333

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.57644 | val 0.79143
  Epoch 016 - train 0.64239 | val 0.84258
  Classification -> best τ=0.585 (val F1=0.3705)
  Directional -> Accuracy: 0.3469, MCC: -0.2592, F1: 0.5152

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.64118 | val 1.43932
  Epoch 012 - train 0.60845 | val 1.45918
  Classification -> best τ=0.530 (val F1=0.1236)
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.68574 | val 0.88578
  Epoch 014 - train 0.61763 | val 1.14088
  Classification -> best τ=0.615 (val F1=0.3920)
  Directional -> Accuracy: 0.5357, MCC: 0.0702, F1: 0.5185

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.65720 | val 1.32806
  Epoch 011 - train 0.58819 | val 1.24053
  Classification -> best τ=0.505 (val F1=0.1626)
  Directional -> Accuracy: 0.6111, MCC: 0.2224, F1: 0.6182

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.63617 | val 1.81229
  Epoch 011 - train 0.64135 | val 1.74680
  Classification -> best τ=0.385 (val F1=0.1667)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.60961 | val 1.06581
  Epoch 011 - train 0.62466 | val 1.24010

[I 2026-02-25 02:19:42,090] Trial 156 finished with value: 0.27279790422545186 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 0.003119731722701923, 'weight_decay': 0.00019327352816355715, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.41896952115015484, 'early_stopping_min_delta': 0.0032056353265025378}. Best is trial 140 with value: 0.29322408230766744.

  Classification -> best τ=0.495 (val F1=0.1748)
  Directional -> Accuracy: 0.3934, MCC: -0.2079, F1: 0.4308

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.27279790422545186
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.65302 | val 0.88827
  Epoch 011 - train 0.66387 | val 0.92137
  Classification -> best τ=0.340 (val F1=0.1704)
  Directional -> Accuracy: 0.4474, MCC: 0.0000, F1: 0.6182

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.65839 | val 0.80569
  Epoch 014 - train 0.57870 | val 0.92614
  Classification -> best τ=0.475 (val F1=0.1700)
  Directional -> Accuracy: 0.6222, MCC: 0.2073, F1: 0.7463

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.62743 | val 0.74025
  Epoch 013 - train 0.62036 | val 0.79744
  Classification -> best τ=0.440 (val F1=0.3020)
  Directional -> Accuracy: 0.4894, MCC: -0.0603, F1: 0.6000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.65188 | val 1.47090
  Epoch 011 - train 0.63575 | val 1.33067
  Classification -> best τ=0.440 (val F1=0.1867)
  Directional -> Accuracy: 0.5067, MCC: -0.1859, F1: 0.6726

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.60723 | val 0.70886
  Epoch 015 - train 0.60901 | val 0.74815
  Classification -> best τ=0.495 (val F1=0.4513)
  Directional -> Accuracy: 0.5686, MCC: 0.1334, F1: 0.6857

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.60827 | val 0.87214
  Epoch 018 - train 0.58623 | val 0.96897
  Classification -> best τ=0.585 (val F1=0.2928)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.68477 | val 0.69570
  Epoch 011 - train 0.66370 | val 0.73213
  Classification -> best τ=0.455 (val F1=0.2137)
  Directional -> Accuracy: 0.4203, MCC: 0.0315, F1: 0.5745

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.65930 | val 0.77888
  Epoch 015 - train 0.57106 | val 0.94259
  Classification -> best τ=0.235 (val F1=0.2168)
  Directional -> Accuracy: 0.5349, MCC: -0.1874, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.64210 | val 1.09553
  Epoch 011 - train 0.67883 | val 1.12553
  Classification -> best τ=0.365 (val F1=0.2408)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.64961 | val 0.88107
  Epoch 012 - train 0.58561 | val 1.01713
  Classification -> best τ=0.365 (val F1=0.2307)
  Directional -> Accuracy: 0.4571, MCC: 0.1485, F1: 0.6122

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.64314 | val 1.57673
  Epoch 013 - train 0.59965 | val 1.77507
  Classification -> best τ=0.465 (val F1=0.3091)
  Directional -> Accuracy: 0.5600, MCC: 0.1000, F1: 0.4500

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.63473 | val 1.15591
  Epoch 011 - train 0.59413 | val 1.17532
  Classification -> best τ=0.480 (val F1=0.1844)
  Directional -> Accuracy: 0.5862, MCC: 0.2646, F1: 0.3333

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.67954 | val 0.77246
  Epoch 014 - train 0.56747 | val 0.77741
  Classification -> best τ=0.380 (val F1=0.2731)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.67050 | val 0.72898
  Epoch 012 - train 0.66302 | val 0.90855
  Classification -> best τ=0.500 (val F1=0.3833)
  Directional -> Accuracy: 0.5667, MCC: 0.1336, F1: 0.5806

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.63430 | val 2.25605
  Epoch 014 - train 0.62461 | val 2.27801
  Classification -> best τ=0.590 (val F1=0.2160)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.61928 | val 0.73409
  Epoch 012 - train 0.58076 | val 0.77231
  Classification -> best τ=0.495 (val F1=0.2980)
  Directional -> Accuracy: 0.5942, MCC: 0.1745, F1: 0.6744

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.66481 | val 2.05717
  Epoch 012 - train 0.64687 | val 2.47653
  Classification -> best τ=0.665 (val F1=0.1137)
  Directional -> Accuracy: 0.3729, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.63602 | val 0.82908
  Epoch 012 - train 0.62879 | val 1.44606
  Classification -> best τ=0.455 (val F1=0.1733)
  Directional -> Accuracy: 0.5867, MCC: 0.0462, F1: 0.7156

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.64141 | val 1.32632
  Epoch 014 - train 0.62140 | val 2.10454
  Classification -> best τ=0.665 (val F1=0.2234)
  Directional -> Accuracy: 0.4308, MCC: 0.0090, F1: 0.1395

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.68034 | val 0.69561
  Epoch 018 - train 0.65057 | val 0.71995
  Classification -> best τ=0.415 (val F1=0.3544)
  Directional -> Accuracy: 0.4800, MCC: 0.0969, F1: 0.1333

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.63160 | val 1.21326
  Epoch 016 - train 0.55557 | val 0.82290
  Classification -> best τ=0.510 (val F1=0.2807)
  Directional -> Accuracy: 0.5532, MCC: 0.1705, F1: 0.5532

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.63517 | val 0.79971
  Epoch 012 - train 0.67398 | val 0.91165
  Classification -> best τ=0.670 (val F1=0.1878)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.69166 | val 0.70357
  Epoch 014 - train 0.66603 | val 0.86779
  Classification -> best τ=0.580 (val F1=0.3379)
  Directional -> Accuracy: 0.4138, MCC: -0.1048, F1: 0.1053

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.68452 | val 0.71310
  Epoch 012 - train 0.63130 | val 0.75560
  Classification -> best τ=0.575 (val F1=0.1962)
  Directional -> Accuracy: 0.5231, MCC: 0.0264, F1: 0.3404

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.58579 | val 0.72771
  Epoch 020 - train 0.51141 | val 0.98282
  Epoch 022 - train 0.53328 | val 1.05846
  Classification -> best τ=0.730 (val F1=0.4057)
  Directional -> Accuracy: 0.5000, MCC: 0.2137, F1: 0.1765

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.62292 | val 1.74459
  Epoch 014 - train 0.58288 | val 1.65365
  Classification -> best τ=0.555 (val F1=0.2318)
  Directional -> Accuracy: 0.4565, MCC: -0.0096, F1: 0.5614

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.66435 | val 0.68595
  Epoch 016 - train 0.64279 | val 0.70467
  Classification -> best τ=0.610 (val F1=0.2402)
  Directional -> Accuracy: 0.4524, MCC: -0.0313, F1: 0.3429

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.63854 | val 0.80988
  Epoch 013 - train 0.65237 | val 0.74045
  Classification -> best τ=0.420 (val F1=0.2510)
  Directional -> Accuracy: 0.5088, MCC: 0.2428, F1: 0.2222

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.61671 | val 0.87964
  Epoch 014 - train 0.60174 | val 0.94404
  Classification -> best τ=0.460 (val F1=0.1580)
  Directional -> Accuracy: 0.5610, MCC: 0.0983, F1: 0.6786

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.66853 | val 0.79858
  Epoch 013 - train 0.60825 | val 0.73253
  Classification -> best τ=0.495 (val F1=0.1382)
  Directional -> Accuracy: 0.4884, MCC: -0.0197, F1: 0.5217

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.64935 | val 0.72385
  Epoch 013 - train 0.59636 | val 0.78503
  Classification -> best τ=0.555 (val F1=0.2092)
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.62724 | val 0.91350
  Epoch 011 - train 0.57224 | val 0.89675
  Classification -> best τ=0.675 (val F1=0.4339)
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.64540 | val 0.70483
  Epoch 011 - train 0.63563 | val 0.81409
  Classification -> best τ=0.395 (val F1=0.3467)
  Directional -> Accuracy: 0.5479, MCC: 0.1851, F1: 0.4407

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.59254 | val 0.94784
  Epoch 012 - train 0.59222 | val 1.22326
  Classification -> best τ=0.505 (val F1=0.1992)
  Directional -> Accuracy: 0.5405, MCC: 0.0783, F1: 0.3704

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.64118 | val 0.93203
  Epoch 011 - train 0.70194 | val 1.00512
  Classification -> best τ=0.545 (val F1=0.3448)
  Directional -> Accuracy: 0.5000, MCC: 0.0780, F1: 0.6452

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.66164 | val 0.68427
  Epoch 020 - train 0.60533 | val 0.79122
  Classification -> best τ=0.285 (val F1=0.3787)
  Directional -> Accuracy: 0.5303, MCC: 0.0613, F1: 0.5634

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.59934 | val 0.86818
  Epoch 016 - train 0.52964 | val 2.12112
  Classification -> best τ=0.755 (val F1=0.3300)
  Directional -> Accuracy: 0.4762, MCC: -0.0155, F1: 0.1538

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.60193 | val 1.19484
  Epoch 011 - train 0.60310 | val 1.53293
  Classification -> best τ=0.320 (val F1=0.3155)
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.6341

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.62066 | val 1.18813
  Epoch 011 - train 0.54615 | val 1.10224
  Classification -> best τ=0.530 (val F1=0.4603)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.57885 | val 0.72201
  Epoch 017 - train 0.52858 | val 0.69170
  Classification -> best τ=0.360 (val F1=0.5617)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.61334 | val 0.72380
  Epoch 011 - train 0.70426 | val 0.79824
  Classification -> best τ=0.445 (val F1=0.1688)
  Directional -> Accuracy: 0.4595, MCC: -0.1105, F1: 0.5455

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.65169 | val 0.97252
  Epoch 015 - train 0.64682 | val 1.12487
  Classification -> best τ=0.225 (val F1=0.3597)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.69133 | val 0.85888
  Epoch 012 - train 0.66925 | val 0.76336
  Classification -> best τ=0.400 (val F1=0.3560)
  Directional -> Accuracy: 0.5652, MCC: 0.2097, F1: 0.3750

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.66263 | val 0.87203
  Epoch 011 - train 0.61736 | val 1.02434
  Classification -> best τ=0.600 (val F1=0.4113)
  Directional -> Accuracy: 0.5116, MCC: 0.0924, F1: 0.4000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.65916 | val 0.83944
  Epoch 014 - train 0.62148 | val 0.74422
  Classification -> best τ=0.430 (val F1=0.4682)
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.68137 | val 1.03036
  Epoch 012 - train 0.66292 | val 1.91954
  Classification -> best τ=0.585 (val F1=0.2194)
  Directional -> Accuracy: 0.5714, MCC: 0.1708, F1: 0.5200

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.66025 | val 0.79090
  Epoch 012 - train 0.62654 | val 0.88956
  Classification -> best τ=0.445 (val F1=0.2858)
  Directional -> Accuracy: 0.5536, MCC: 0.1176, F1: 0.5902

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.65366 | val 1.93722
  Epoch 012 - train 0.66037 | val 2.20731
  Classification -> best τ=0.300 (val F1=0.2663)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.64985 | val 2.08798
  Epoch 011 - train 0.59841 | val 2.64618
  Classification -> best τ=0.465 (val F1=0.1473)
  Directional -> Accuracy: 0.4464, MCC: -0.1225, F1: 0.5231

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.69758 | val 0.78456

[I 2026-02-25 02:21:22,601] Trial 157 finished with value: 0.2770643620195731 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 0.005359739276492214, 'weight_decay': 0.00011485728434961569, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 0.5074359603592097, 'early_stopping_min_delta': 0.003518820805180209}. Best is trial 140 with value: 0.29322408230766744.

  Epoch 015 - train 0.62343 | val 2.19721
  Classification -> best τ=0.365 (val F1=0.1587)
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2770643620195731
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.65469 | val 0.91629
  Epoch 011 - train 0.65067 | val 0.74842
  Classification -> best τ=0.465 (val F1=0.3013)
  Directional -> Accuracy: 0.4211, MCC: -0.1485, F1: 0.4211

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.61389 | val 0.71048
  Epoch 012 - train 0.58301 | val 0.80092
  Classification -> best τ=0.560 (val F1=0.1236)
  Directional -> Accuracy: 0.4889, MCC: 0.0318, F1: 0.4390

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.65956 | val 0.79139
  Epoch 018 - train 0.62987 | val 0.72806
  Classification -> best τ=0.610 (val F1=0.3537)
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.66409 | val 1.14387
  Epoch 012 - train 0.65395 | val 1.26800
  Classification -> best τ=0.470 (val F1=0.2833)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.61114 | val 0.69133
  Epoch 017 - train 0.58299 | val 0.81444
  Classification -> best τ=0.655 (val F1=0.4692)
  Directional -> Accuracy: 0.6667, MCC: 0.3398, F1: 0.7302

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.58240 | val 0.70841
  Epoch 017 - train 0.53009 | val 1.69729
  Classification -> best τ=0.400 (val F1=0.3430)
  Directional -> Accuracy: 0.5745, MCC: 0.1489, F1: 0.5000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.65034 | val 0.73247
  Epoch 017 - train 0.64743 | val 0.87865
  Classification -> best τ=0.670 (val F1=0.2919)
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.64386 | val 1.08841
  Epoch 016 - train 0.56633 | val 0.84405
  Classification -> best τ=0.335 (val F1=0.1214)
  Directional -> Accuracy: 0.3721, MCC: -0.2603, F1: 0.5424

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.62701 | val 0.76194
  Epoch 014 - train 0.57300 | val 1.52293
  Classification -> best τ=0.355 (val F1=0.1353)
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.58792 | val 1.16978
  Epoch 014 - train 0.59474 | val 0.74009
  Classification -> best τ=0.380 (val F1=0.2904)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.62926 | val 1.16696
  Epoch 015 - train 0.59366 | val 2.87174
  Classification -> best τ=0.600 (val F1=0.4971)
  Directional -> Accuracy: 0.6200, MCC: 0.2274, F1: 0.5366

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.60336 | val 1.80582
  Epoch 011 - train 0.61602 | val 2.31769
  Classification -> best τ=0.380 (val F1=0.2172)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.65868 | val 1.54967
  Epoch 013 - train 0.56499 | val 1.24588
  Classification -> best τ=0.470 (val F1=0.1648)
  Directional -> Accuracy: 0.5238, MCC: 0.0912, F1: 0.5833

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.68223 | val 0.84203
  Epoch 012 - train 0.65287 | val 0.83220
  Classification -> best τ=0.540 (val F1=0.3026)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.5312

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.61043 | val 1.47033
  Epoch 011 - train 0.60303 | val 2.00668
  Classification -> best τ=0.585 (val F1=0.2196)
  Directional -> Accuracy: 0.5000, MCC: 0.1852, F1: 0.6486

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.62952 | val 0.78421
  Epoch 012 - train 0.59788 | val 0.80751
  Classification -> best τ=0.530 (val F1=0.1869)
  Directional -> Accuracy: 0.5652, MCC: 0.1829, F1: 0.4643

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.67215 | val 1.77663
  Epoch 011 - train 0.60886 | val 2.24938
  Classification -> best τ=0.270 (val F1=0.1179)
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.64285 | val 1.80410
  Epoch 011 - train 0.65585 | val 1.65790
  Classification -> best τ=0.230 (val F1=0.0985)
  Directional -> Accuracy: 0.5467, MCC: 0.0120, F1: 0.6531

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.65174 | val 1.49786
  Epoch 011 - train 0.65509 | val 1.59435
  Classification -> best τ=0.380 (val F1=0.3343)
  Directional -> Accuracy: 0.5692, MCC: -0.0090, F1: 0.7143

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.64379 | val 0.75529
  Epoch 018 - train 0.65682 | val 0.72846
  Classification -> best τ=0.420 (val F1=0.3293)
  Directional -> Accuracy: 0.4667, MCC: 0.1059, F1: 0.0476

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.62518 | val 0.67895
  Epoch 020 - train 0.54522 | val 0.72059
  Classification -> best τ=0.490 (val F1=0.2964)
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.68135 | val 0.78806
  Epoch 012 - train 0.66962 | val 0.78586
  Classification -> best τ=0.510 (val F1=0.2617)
  Directional -> Accuracy: 0.4848, MCC: -0.0346, F1: 0.5854

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.67924 | val 0.70301
  Epoch 012 - train 0.66118 | val 0.83715
  Classification -> best τ=0.645 (val F1=0.3067)
  Directional -> Accuracy: 0.5172, MCC: 0.0882, F1: 0.4615

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.65632 | val 0.78098
  Epoch 011 - train 0.62238 | val 0.74080
  Classification -> best τ=0.500 (val F1=0.1359)
  Directional -> Accuracy: 0.5538, MCC: 0.1396, F1: 0.6234

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.64642 | val 0.72311
  Epoch 019 - train 0.60315 | val 0.68907
  Classification -> best τ=0.550 (val F1=0.4297)
  Directional -> Accuracy: 0.4643, MCC: 0.0541, F1: 0.1176

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.62511 | val 0.82946
  Epoch 011 - train 0.57290 | val 0.79624
  Classification -> best τ=0.465 (val F1=0.1310)
  Directional -> Accuracy: 0.3913, MCC: -0.1882, F1: 0.4400

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.59873 | val 0.86431
  Epoch 014 - train 0.61916 | val 0.96164
  Classification -> best τ=0.570 (val F1=0.1936)
  Directional -> Accuracy: 0.4286, MCC: -0.1132, F1: 0.4000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.62987 | val 0.93521
  Epoch 017 - train 0.56915 | val 1.24102
  Classification -> best τ=0.305 (val F1=0.2750)
  Directional -> Accuracy: 0.5263, MCC: -0.0518, F1: 0.6667

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.61926 | val 0.76422
  Epoch 015 - train 0.56419 | val 1.15033
  Classification -> best τ=0.470 (val F1=0.3296)
  Directional -> Accuracy: 0.5366, MCC: 0.0166, F1: 0.6885

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.59463 | val 0.70161
  Epoch 012 - train 0.66602 | val 0.72218
  Classification -> best τ=0.545 (val F1=0.2814)
  Directional -> Accuracy: 0.5116, MCC: 0.0197, F1: 0.4615

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.64624 | val 0.81648
  Epoch 013 - train 0.63713 | val 0.80655
  Classification -> best τ=0.695 (val F1=0.1080)
  Directional -> Accuracy: 0.5349, MCC: 0.0593, F1: 0.5833

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.57171 | val 0.89858
  Epoch 015 - train 0.53156 | val 1.23524
  Classification -> best τ=0.385 (val F1=0.3639)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.66103 | val 0.67711
  Epoch 011 - train 0.64808 | val 0.68350
  Classification -> best τ=0.505 (val F1=0.2515)
  Directional -> Accuracy: 0.5205, MCC: 0.1344, F1: 0.3860

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.80861 | val 1.15187
  Epoch 014 - train 0.59465 | val 0.99006
  Classification -> best τ=0.435 (val F1=0.0967)
  Directional -> Accuracy: 0.5676, MCC: 0.1429, F1: 0.6000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.63646 | val 1.18204
  Epoch 011 - train 0.66101 | val 1.19189
  Classification -> best τ=0.470 (val F1=0.2757)
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.65668 | val 0.72579
  Epoch 012 - train 0.64753 | val 0.74967
  Classification -> best τ=0.355 (val F1=0.3525)
  Directional -> Accuracy: 0.5909, MCC: 0.1070, F1: 0.7327

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.64308 | val 0.96511
  Epoch 012 - train 0.57238 | val 0.92656
  Classification -> best τ=0.465 (val F1=0.1257)
  Directional -> Accuracy: 0.6190, MCC: 0.2864, F1: 0.5294

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.62781 | val 1.17887
  Epoch 012 - train 0.65268 | val 1.44268
  Classification -> best τ=0.660 (val F1=0.1615)
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.58188 | val 1.91050
  Epoch 011 - train 0.56402 | val 2.19424
  Classification -> best τ=0.560 (val F1=0.4043)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.68392 | val 0.86107
  Epoch 020 - train 0.65605 | val 0.64795
  Classification -> best τ=0.275 (val F1=0.5617)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.67378 | val 0.79771
  Epoch 014 - train 0.64043 | val 0.81995
  Classification -> best τ=0.355 (val F1=0.4776)
  Directional -> Accuracy: 0.4324, MCC: -0.1122, F1: 0.3226

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.65275 | val 1.04405
  Epoch 011 - train 0.60951 | val 1.11156
  Classification -> best τ=0.355 (val F1=0.3519)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.63871 | val 0.72156
  Epoch 020 - train 0.59293 | val 1.24239
  Classification -> best τ=0.495 (val F1=0.3367)
  Directional -> Accuracy: 0.5217, MCC: 0.0733, F1: 0.3889

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.66974 | val 0.80198
  Epoch 011 - train 0.59455 | val 0.80392
  Classification -> best τ=0.565 (val F1=0.3651)
  Directional -> Accuracy: 0.5349, MCC: 0.2232, F1: 0.3333

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.79197 | val 0.92774
  Epoch 014 - train 0.58957 | val 0.78295
  Classification -> best τ=0.615 (val F1=0.5261)
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.65585 | val 0.74544
  Epoch 014 - train 0.62290 | val 1.28909
  Classification -> best τ=0.595 (val F1=0.3124)
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.64709 | val 1.18247
  Epoch 011 - train 0.70509 | val 0.90145
  Classification -> best τ=0.565 (val F1=0.3170)
  Directional -> Accuracy: 0.5357, MCC: 0.0879, F1: 0.1333

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.66920 | val 1.22365
  Epoch 012 - train 0.62114 | val 1.37548
  Classification -> best τ=0.380 (val F1=0.2048)
  Directional -> Accuracy: 0.5185, MCC: 0.0219, F1: 0.6176

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.63771 | val 1.44945
  Epoch 011 - train 0.61180 | val 1.87537
  Classification -> best τ=0.395 (val F1=0.1168)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.62791 | val 1.27137
  Epoch 011 - train 0.64852 | val 1.74456

[I 2026-02-25 02:23:02,357] Trial 158 finished with value: 0.2749218443156609 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 0.0051050057106111334, 'weight_decay': 0.00012222992982037853, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 0.49311288990076785, 'early_stopping_min_delta': 0.003577880662909636}. Best is trial 140 with value: 0.29322408230766744.

  Classification -> best τ=0.580 (val F1=0.2136)
  Directional -> Accuracy: 0.5246, MCC: 0.0130, F1: 0.1212

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2749218443156609
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.65507 | val 1.24661
  Epoch 012 - train 0.63515 | val 0.78582
  Classification -> best τ=0.535 (val F1=0.2409)
  Directional -> Accuracy: 0.5658, MCC: 0.0950, F1: 0.4000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.68965 | val 0.74202
  Epoch 011 - train 0.66450 | val 0.75923
  Classification -> best τ=0.545 (val F1=0.1236)
  Directional -> Accuracy: 0.5333, MCC: 0.0640, F1: 0.5714

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.65838 | val 0.77368
  Epoch 013 - train 0.64845 | val 0.77049
  Classification -> best τ=0.505 (val F1=0.4399)
  Directional -> Accuracy: 0.4894, MCC: 0.1383, F1: 0.0769

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.64660 | val 2.22733
  Epoch 013 - train 0.62918 | val 1.40647
  Classification -> best τ=0.380 (val F1=0.2568)
  Directional -> Accuracy: 0.4667, MCC: -0.0379, F1: 0.3939

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.62681 | val 0.77583
  Epoch 014 - train 0.60440 | val 0.76878
  Classification -> best τ=0.545 (val F1=0.4063)
  Directional -> Accuracy: 0.4510, MCC: -0.1688, F1: 0.5882

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.64113 | val 0.72420
  Epoch 016 - train 0.55680 | val 1.41081
  Classification -> best τ=0.450 (val F1=0.3892)
  Directional -> Accuracy: 0.5532, MCC: 0.1997, F1: 0.6769

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.67599 | val 0.76500
  Epoch 017 - train 0.64255 | val 0.84886
  Classification -> best τ=0.445 (val F1=0.3077)
  Directional -> Accuracy: 0.4203, MCC: 0.1002, F1: 0.5833

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.68540 | val 2.16148
  Epoch 011 - train 0.67472 | val 2.40611
  Classification -> best τ=0.535 (val F1=0.1502)
  Directional -> Accuracy: 0.6279, MCC: 0.2025, F1: 0.3333

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.64726 | val 0.79958
  Epoch 014 - train 0.60617 | val 1.28265
  Classification -> best τ=0.395 (val F1=0.2112)
  Directional -> Accuracy: 0.5510, MCC: 0.0212, F1: 0.0833

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.61737 | val 0.72266
  Epoch 014 - train 0.57917 | val 0.71953
  Classification -> best τ=0.490 (val F1=0.1275)
  Directional -> Accuracy: 0.4429, MCC: -0.0556, F1: 0.5185

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.64977 | val 1.99163
  Epoch 013 - train 0.57237 | val 2.92739
  Classification -> best τ=0.495 (val F1=0.4523)
  Directional -> Accuracy: 0.6000, MCC: 0.2274, F1: 0.2857

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.67525 | val 1.24745
  Epoch 011 - train 0.59302 | val 1.81174
  Classification -> best τ=0.460 (val F1=0.1578)
  Directional -> Accuracy: 0.5172, MCC: 0.0778, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.62503 | val 0.91148
  Epoch 013 - train 0.56997 | val 1.44618
  Classification -> best τ=0.440 (val F1=0.2323)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.67302 | val 0.71556
  Epoch 020 - train 0.59159 | val 0.71672
  Epoch 028 - train 0.61337 | val 0.74797
  Classification -> best τ=0.680 (val F1=0.1774)
  Directional -> Accuracy: 0.4833, MCC: -0.0431, F1: 0.2439

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.60631 | val 1.94357
  Epoch 012 - train 0.61853 | val 1.84287
  Classification -> best τ=0.605 (val F1=0.2673)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.62627 | val 0.84816
  Epoch 013 - train 0.62096 | val 0.95508
  Classification -> best τ=0.345 (val F1=0.2708)
  Directional -> Accuracy: 0.6087, MCC: 0.3006, F1: 0.7327

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.64090 | val 1.83539
  Epoch 011 - train 0.65384 | val 1.73053
  Classification -> best τ=0.310 (val F1=0.0660)
  Directional -> Accuracy: 0.6610, MCC: 0.2103, F1: 0.7826

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.65107 | val 1.10617
  Epoch 011 - train 0.63480 | val 1.74709
  Classification -> best τ=0.540 (val F1=0.0882)
  Directional -> Accuracy: 0.4667, MCC: -0.1238, F1: 0.5652

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.63865 | val 1.39771
  Epoch 011 - train 0.66782 | val 1.49149
  Classification -> best τ=0.490 (val F1=0.2234)
  Directional -> Accuracy: 0.4308, MCC: 0.0366, F1: 0.0976

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.63328 | val 0.68037
  Epoch 016 - train 0.59695 | val 0.72752
  Classification -> best τ=0.490 (val F1=0.3686)
  Directional -> Accuracy: 0.5067, MCC: 0.0926, F1: 0.3273

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.60530 | val 0.78169
  Epoch 012 - train 0.59917 | val 0.71230
  Classification -> best τ=0.455 (val F1=0.3707)
  Directional -> Accuracy: 0.5532, MCC: 0.0240, F1: 0.6557

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.68656 | val 0.92280
  Epoch 012 - train 0.67564 | val 0.94261
  Classification -> best τ=0.475 (val F1=0.1664)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.68338 | val 0.82450
  Epoch 011 - train 0.66871 | val 0.84339
  Classification -> best τ=0.690 (val F1=0.2864)
  Directional -> Accuracy: 0.5345, MCC: 0.1655, F1: 0.4255

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.64870 | val 0.73474
  Epoch 018 - train 0.65099 | val 0.91340
  Classification -> best τ=0.425 (val F1=0.2579)
  Directional -> Accuracy: 0.4923, MCC: 0.0154, F1: 0.6024

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.67160 | val 0.65889
  Epoch 020 - train 0.59154 | val 0.71011
  Epoch 022 - train 0.57762 | val 0.67938
  Classification -> best τ=0.445 (val F1=0.4472)
  Directional -> Accuracy: 0.5893, MCC: 0.2696, F1: 0.4889

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.62924 | val 1.60241
  Epoch 011 - train 0.58220 | val 1.42283
  Classification -> best τ=0.510 (val F1=0.2935)
  Directional -> Accuracy: 0.4130, MCC: -0.1164, F1: 0.5574

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.64744 | val 0.79161
  Epoch 011 - train 0.68297 | val 0.68838
  Classification -> best τ=0.560 (val F1=0.1936)
  Directional -> Accuracy: 0.5238, MCC: 0.0413, F1: 0.5652

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.62153 | val 0.94118
  Epoch 012 - train 0.61267 | val 1.02338
  Classification -> best τ=0.580 (val F1=0.1625)
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.67064 | val 1.58424
  Epoch 011 - train 0.62718 | val 1.88768
  Classification -> best τ=0.465 (val F1=0.2686)
  Directional -> Accuracy: 0.6341, MCC: 0.2695, F1: 0.7170

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.62603 | val 0.66612
  Epoch 020 - train 0.55314 | val 0.83872
  Classification -> best τ=0.735 (val F1=0.2814)
  Directional -> Accuracy: 0.5116, MCC: 0.0179, F1: 0.4324

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.67484 | val 0.83858
  Epoch 011 - train 0.68313 | val 0.92809
  Classification -> best τ=0.545 (val F1=0.1452)
  Directional -> Accuracy: 0.5116, MCC: 0.0217, F1: 0.5333

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.59560 | val 0.91433
  Epoch 012 - train 0.61386 | val 1.13351
  Classification -> best τ=0.460 (val F1=0.3323)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.65607 | val 0.71867
  Epoch 011 - train 0.64510 | val 0.73493
  Classification -> best τ=0.350 (val F1=0.3602)
  Directional -> Accuracy: 0.5753, MCC: 0.1536, F1: 0.5974

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.67580 | val 1.35242
  Epoch 013 - train 0.62612 | val 1.31105
  Classification -> best τ=0.455 (val F1=0.1992)
  Directional -> Accuracy: 0.5676, MCC: 0.1737, F1: 0.6522

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.63524 | val 1.07062
  Epoch 011 - train 0.64307 | val 1.26058
  Classification -> best τ=0.495 (val F1=0.2757)
  Directional -> Accuracy: 0.5682, MCC: 0.1548, F1: 0.6122

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.61870 | val 0.75048
  Epoch 015 - train 0.58202 | val 0.77523
  Classification -> best τ=0.285 (val F1=0.3525)
  Directional -> Accuracy: 0.6212, MCC: 0.2364, F1: 0.6575

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.52946 | val 1.93770
  Epoch 011 - train 0.58282 | val 1.57469
  Classification -> best τ=0.565 (val F1=0.2652)
  Directional -> Accuracy: 0.5000, MCC: 0.0561, F1: 0.2222

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.68117 | val 1.58531
  Epoch 012 - train 0.61892 | val 0.80674
  Classification -> best τ=0.480 (val F1=0.2305)
  Directional -> Accuracy: 0.5714, MCC: 0.1385, F1: 0.5385

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.62303 | val 1.30720
  Epoch 012 - train 0.64671 | val 2.71386
  Classification -> best τ=0.595 (val F1=0.3497)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.59084 | val 0.64114
  Epoch 020 - train 0.59363 | val 0.69653
  Epoch 022 - train 0.56227 | val 0.70502
  Classification -> best τ=0.275 (val F1=0.5125)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.68782 | val 0.74390
  Epoch 011 - train 0.70660 | val 0.77126
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.63765 | val 0.89779
  Epoch 011 - train 0.64810 | val 0.91313
  Classification -> best τ=0.360 (val F1=0.2924)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.64304 | val 0.81497
  Epoch 014 - train 0.59633 | val 1.04453
  Classification -> best τ=0.450 (val F1=0.3367)
  Directional -> Accuracy: 0.4783, MCC: -0.0382, F1: 0.4545

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.58384 | val 1.02640
  Epoch 011 - train 0.66300 | val 1.06097
  Classification -> best τ=0.595 (val F1=0.2530)
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.66785 | val 0.55402
  Epoch 020 - train 0.60866 | val 0.93395
  Classification -> best τ=0.565 (val F1=0.6590)
  Directional -> Accuracy: 0.3469, MCC: -0.2592, F1: 0.5152

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.68115 | val 2.30543
  Epoch 011 - train 0.68486 | val 2.09582
  Classification -> best τ=0.340 (val F1=0.2958)
  Directional -> Accuracy: 0.6964, MCC: 0.3883, F1: 0.7385

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.60543 | val 1.70311
  Epoch 011 - train 0.65211 | val 1.68926
  Classification -> best τ=0.585 (val F1=0.4829)
  Directional -> Accuracy: 0.5536, MCC: 0.1176, F1: 0.5902

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.62836 | val 1.83166
  Epoch 011 - train 0.64460 | val 1.92291
  Classification -> best τ=0.505 (val F1=0.1626)
  Directional -> Accuracy: 0.6111, MCC: 0.2196, F1: 0.6557

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.66794 | val 1.50943
  Epoch 012 - train 0.57485 | val 1.24714
  Classification -> best τ=0.585 (val F1=0.1557)
  Directional -> Accuracy: 0.4821, MCC: -0.0226, F1: 0.3556

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.63274 | val 0.93143

[I 2026-02-25 02:24:41,463] Trial 159 finished with value: 0.2736291338887855 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 0.0025071715417084774, 'weight_decay': 0.00027717056362193155, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 0.5291530167684976, 'early_stopping_min_delta': 0.0032564211212710147}. Best is trial 140 with value: 0.29322408230766744.

  Epoch 016 - train 0.58342 | val 1.85585
  Classification -> best τ=0.325 (val F1=0.3349)
  Directional -> Accuracy: 0.4918, MCC: 0.0647, F1: 0.6437

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2736291338887855
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.60840 | val 0.95612
  Epoch 018 - train 0.59675 | val 1.39305
  Classification -> best τ=0.545 (val F1=0.2510)
  Directional -> Accuracy: 0.5526, MCC: 0.0249, F1: 0.1053

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.63916 | val 0.86241
  Epoch 018 - train 0.57803 | val 0.83589
  Classification -> best τ=0.535 (val F1=0.0406)
  Directional -> Accuracy: 0.6222, MCC: 0.2523, F1: 0.7536

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.61816 | val 0.75408
  Epoch 018 - train 0.54373 | val 1.08454
  Classification -> best τ=0.490 (val F1=0.3262)
  Directional -> Accuracy: 0.5319, MCC: 0.0504, F1: 0.5926

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.63215 | val 1.89510
  Epoch 016 - train 0.62162 | val 1.62009
  Classification -> best τ=0.475 (val F1=0.2163)
  Directional -> Accuracy: 0.5067, MCC: 0.1698, F1: 0.2128

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.60770 | val 0.72259
  Epoch 019 - train 0.58387 | val 0.74434
  Classification -> best τ=0.550 (val F1=0.4598)
  Directional -> Accuracy: 0.5294, MCC: 0.0215, F1: 0.6667

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.53223 | val 1.28140
  Epoch 016 - train 0.47859 | val 1.22033
  Classification -> best τ=0.485 (val F1=0.2928)
  Directional -> Accuracy: 0.4894, MCC: 0.0000, F1: 0.6571

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.63908 | val 0.80620
  Epoch 020 - train 0.62183 | val 0.86275
  Epoch 021 - train 0.61544 | val 0.96411
  Classification -> best τ=0.560 (val F1=0.1378)
  Directional -> Accuracy: 0.4638, MCC: -0.0046, F1: 0.5067

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.53056 | val 0.74724
  Epoch 020 - train 0.47930 | val 0.81638
  Epoch 024 - train 0.50268 | val 1.43018
  Classification -> best τ=0.460 (val F1=0.0792)
  Directional -> Accuracy: 0.6047, MCC: 0.1366, F1: 0.3200

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.61308 | val 1.42885
  Epoch 018 - train 0.54598 | val 1.73032
  Classification -> best τ=0.380 (val F1=0.2946)
  Directional -> Accuracy: 0.6122, MCC: 0.2079, F1: 0.5366

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.62337 | val 0.76835
  Epoch 016 - train 0.55699 | val 0.73735
  Classification -> best τ=0.540 (val F1=0.1816)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.4615

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.64552 | val 1.64867
  Epoch 017 - train 0.53033 | val 1.86553
  Classification -> best τ=0.480 (val F1=0.2125)
  Directional -> Accuracy: 0.5400, MCC: 0.0551, F1: 0.4103

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.58011 | val 1.33928
  Epoch 019 - train 0.59142 | val 1.26673
  Classification -> best τ=0.530 (val F1=0.2769)
  Directional -> Accuracy: 0.4483, MCC: -0.1429, F1: 0.1579

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.60033 | val 1.20561
  Epoch 017 - train 0.55300 | val 1.48718
  Classification -> best τ=0.295 (val F1=0.2323)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.63169 | val 0.85283
  Epoch 016 - train 0.64114 | val 1.95019
  Classification -> best τ=0.485 (val F1=0.2942)
  Directional -> Accuracy: 0.5667, MCC: 0.1455, F1: 0.6389

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.59342 | val 1.20757
  Epoch 018 - train 0.50475 | val 5.07755
  Classification -> best τ=0.620 (val F1=0.2673)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.63031 | val 0.72385
  Epoch 017 - train 0.55941 | val 1.04772
  Classification -> best τ=0.280 (val F1=0.2592)
  Directional -> Accuracy: 0.5362, MCC: 0.0000, F1: 0.6981

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.62923 | val 2.57532
  Epoch 016 - train 0.61395 | val 2.53892
  Classification -> best τ=0.700 (val F1=0.1842)
  Directional -> Accuracy: 0.3729, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.62434 | val 1.73642
  Epoch 016 - train 0.64782 | val 2.29838
  Classification -> best τ=0.555 (val F1=0.1095)
  Directional -> Accuracy: 0.4800, MCC: 0.0615, F1: 0.4000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.59953 | val 1.56359
  Epoch 017 - train 0.59476 | val 2.14595
  Classification -> best τ=0.420 (val F1=0.2752)
  Directional -> Accuracy: 0.4923, MCC: 0.1307, F1: 0.3265

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.62021 | val 0.77460
  Epoch 018 - train 0.57550 | val 0.74480
  Classification -> best τ=0.335 (val F1=0.2434)
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.56631 | val 0.68556
  Epoch 020 - train 0.49368 | val 1.01356
  Epoch 024 - train 0.43177 | val 0.81563
  Classification -> best τ=0.575 (val F1=0.3287)
  Directional -> Accuracy: 0.4255, MCC: 0.1661, F1: 0.1290

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.67903 | val 0.85371
  Epoch 016 - train 0.59993 | val 1.27371
  Classification -> best τ=0.490 (val F1=0.2390)
  Directional -> Accuracy: 0.6212, MCC: 0.2571, F1: 0.5455

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.68387 | val 0.69568
  Epoch 017 - train 0.62849 | val 0.76988
  Classification -> best τ=0.580 (val F1=0.2392)
  Directional -> Accuracy: 0.5517, MCC: 0.2769, F1: 0.3810

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.61326 | val 1.02267
  Epoch 016 - train 0.60038 | val 1.35036
  Classification -> best τ=0.445 (val F1=0.1359)
  Directional -> Accuracy: 0.5385, MCC: 0.1027, F1: 0.6053

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.63730 | val 0.69575
  Epoch 020 - train 0.53249 | val 0.84099
  Epoch 024 - train 0.50683 | val 0.85114
  Classification -> best τ=0.620 (val F1=0.5445)
  Directional -> Accuracy: 0.4643, MCC: 0.1211, F1: 0.0625

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.59639 | val 1.60891
  Epoch 016 - train 0.48540 | val 1.23482
  Classification -> best τ=0.570 (val F1=0.2935)
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.65690 | val 0.70807
  Epoch 020 - train 0.53296 | val 0.83485
  Epoch 022 - train 0.55016 | val 1.08231
  Classification -> best τ=0.620 (val F1=0.1936)
  Directional -> Accuracy: 0.5000, MCC: 0.0138, F1: 0.5116

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.61974 | val 0.78186
  Epoch 020 - train 0.55916 | val 0.94952
  Classification -> best τ=0.320 (val F1=0.4049)
  Directional -> Accuracy: 0.5614, MCC: 0.3307, F1: 0.3590

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.60601 | val 0.68932
  Epoch 020 - train 0.51052 | val 0.99628
  Epoch 024 - train 0.46073 | val 2.26044
  Classification -> best τ=0.325 (val F1=0.3278)
  Directional -> Accuracy: 0.5122, MCC: -0.1469, F1: 0.6774

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.60662 | val 0.80806
  Epoch 018 - train 0.48176 | val 1.09310
  Classification -> best τ=0.515 (val F1=0.3979)
  Directional -> Accuracy: 0.4651, MCC: -0.0691, F1: 0.5818

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.59501 | val 0.82643
  Epoch 020 - train 0.46827 | val 0.83698
  Epoch 022 - train 0.43944 | val 1.00183
  Classification -> best τ=0.510 (val F1=0.3615)
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.60635 | val 0.92172
  Epoch 016 - train 0.55725 | val 1.25268
  Classification -> best τ=0.540 (val F1=0.2399)
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.60962 | val 0.89489
  Epoch 019 - train 0.57319 | val 1.04322
  Classification -> best τ=0.400 (val F1=0.3192)
  Directional -> Accuracy: 0.5616, MCC: 0.1530, F1: 0.5429

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.52926 | val 1.11761
  Epoch 017 - train 0.48259 | val 1.41288
  Classification -> best τ=0.520 (val F1=0.1992)
  Directional -> Accuracy: 0.5135, MCC: 0.0327, F1: 0.5500

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.67133 | val 0.77736
  Epoch 017 - train 0.53102 | val 1.16190
  Classification -> best τ=0.425 (val F1=0.1329)
  Directional -> Accuracy: 0.5227, MCC: 0.1145, F1: 0.6441

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.60478 | val 0.72507
  Epoch 018 - train 0.56796 | val 0.89708
  Classification -> best τ=0.400 (val F1=0.3254)
  Directional -> Accuracy: 0.4848, MCC: 0.1648, F1: 0.2273

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.60194 | val 1.09066
  Epoch 016 - train 0.54399 | val 1.19106
  Classification -> best τ=0.550 (val F1=0.2443)
  Directional -> Accuracy: 0.5952, MCC: 0.2427, F1: 0.4848

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.60644 | val 1.44562
  Epoch 016 - train 0.60200 | val 2.41649
  Classification -> best τ=0.415 (val F1=0.2755)
  Directional -> Accuracy: 0.5000, MCC: 0.0340, F1: 0.5758

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.53324 | val 1.89960
  Epoch 016 - train 0.48451 | val 2.04571
  Classification -> best τ=0.450 (val F1=0.4043)
  Directional -> Accuracy: 0.5870, MCC: -0.0314, F1: 0.7324

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.64576 | val 0.78628
  Epoch 020 - train 0.53136 | val 0.63336
  Epoch 030 - train 0.50596 | val 0.68889
  Epoch 031 - train 0.43831 | val 0.63189
  Classification -> best τ=0.335 (val F1=0.4646)
  Directional -> Accuracy: 0.3469, MCC: -0.1894, F1: 0.5152

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.59016 | val 0.82933
  Epoch 016 - train 0.49267 | val 0.89681
  Classification -> best τ=0.475 (val F1=0.3545)
  Directional -> Accuracy: 0.4595, MCC: -0.0427, F1: 0.2857

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.63008 | val 1.04245
  Epoch 016 - train 0.56204 | val 1.79937
  Classification -> best τ=0.455 (val F1=0.3583)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.64174 | val 0.67257
  Epoch 020 - train 0.56576 | val 1.95760
  Epoch 024 - train 0.51585 | val 1.85939
  Classification -> best τ=0.355 (val F1=0.3510)
  Directional -> Accuracy: 0.5217, MCC: 0.0200, F1: 0.6452

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.60184 | val 0.99880
  Epoch 016 - train 0.50946 | val 1.77715
  Classification -> best τ=0.480 (val F1=0.2282)
  Directional -> Accuracy: 0.6279, MCC: 0.2329, F1: 0.7241

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.63725 | val 0.81461
  Epoch 017 - train 0.58549 | val 0.82742
  Classification -> best τ=0.555 (val F1=0.6590)
  Directional -> Accuracy: 0.6122, MCC: 0.1604, F1: 0.4571

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.64724 | val 1.33860
  Epoch 017 - train 0.62602 | val 1.75224
  Classification -> best τ=0.505 (val F1=0.2832)
  Directional -> Accuracy: 0.5714, MCC: 0.1925, F1: 0.4783

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.68504 | val 0.96499
  Epoch 016 - train 0.59303 | val 1.13690
  Classification -> best τ=0.565 (val F1=0.3973)
  Directional -> Accuracy: 0.5000, MCC: -0.0187, F1: 0.3333

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.63474 | val 1.20789
  Epoch 016 - train 0.58065 | val 2.10100
  Classification -> best τ=0.340 (val F1=0.2552)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.61468 | val 1.93871
  Epoch 018 - train 0.56279 | val 1.59741
  Classification -> best τ=0.300 (val F1=0.1168)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.62297 | val 0.95225

[I 2026-02-25 02:26:54,541] Trial 160 finished with value: 0.2809592378263171 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.6000000000000001, 'batch_size': 32, 'learning_rate': 0.004114830913268035, 'weight_decay': 0.0005060990251472312, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 0.42793914400244015, 'early_stopping_min_delta': 0.0028462741364862314}. Best is trial 140 with value: 0.29322408230766744.

  Epoch 018 - train 0.59840 | val 1.87019
  Classification -> best τ=0.410 (val F1=0.3382)
  Directional -> Accuracy: 0.4754, MCC: -0.0732, F1: 0.3333

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2809592378263171
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.61488 | val 1.96512
  Epoch 019 - train 0.58245 | val 1.19750
  Classification -> best τ=0.505 (val F1=0.2919)
  Directional -> Accuracy: 0.5526, MCC: 0.0676, F1: 0.3929

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.61279 | val 1.25347
  Epoch 016 - train 0.53711 | val 1.25788
  Classification -> best τ=0.530 (val F1=0.2431)
  Directional -> Accuracy: 0.4667, MCC: 0.1844, F1: 0.1429

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.62252 | val 0.78278
  Epoch 020 - train 0.57187 | val 2.86263
  Epoch 023 - train 0.53307 | val 1.37147
  Classification -> best τ=0.405 (val F1=0.2725)
  Directional -> Accuracy: 0.4468, MCC: -0.0866, F1: 0.1875

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.62296 | val 1.44863
  Epoch 016 - train 0.62393 | val 1.61454
  Classification -> best τ=0.330 (val F1=0.2782)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.60806 | val 0.78230
  Epoch 018 - train 0.56730 | val 1.15207
  Classification -> best τ=0.495 (val F1=0.3627)
  Directional -> Accuracy: 0.5098, MCC: -0.1333, F1: 0.6753

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.59889 | val 0.73006
  Epoch 020 - train 0.47309 | val 1.12362
  Classification -> best τ=0.365 (val F1=0.3430)
  Directional -> Accuracy: 0.5106, MCC: 0.0385, F1: 0.6102

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.63362 | val 0.81041
  Epoch 018 - train 0.62810 | val 1.19902
  Classification -> best τ=0.450 (val F1=0.1985)
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.52264 | val 0.66422
  Epoch 019 - train 0.52732 | val 0.89364
  Classification -> best τ=0.430 (val F1=0.1590)
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.57233 | val 0.75735
  Epoch 018 - train 0.55164 | val 1.72530
  Classification -> best τ=0.560 (val F1=0.4053)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.58955 | val 0.81076
  Epoch 016 - train 0.56280 | val 0.96607
  Classification -> best τ=0.475 (val F1=0.1604)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.63430 | val 1.92423
  Epoch 018 - train 0.56797 | val 2.35810
  Classification -> best τ=0.585 (val F1=0.2758)
  Directional -> Accuracy: 0.5600, MCC: 0.0898, F1: 0.3125

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.59635 | val 1.40976
  Epoch 017 - train 0.56758 | val 1.19292
  Classification -> best τ=0.565 (val F1=0.2105)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.55476 | val 1.17189
  Epoch 018 - train 0.52730 | val 1.45815
  Classification -> best τ=0.380 (val F1=0.1588)
  Directional -> Accuracy: 0.4762, MCC: -0.0214, F1: 0.5217

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.64578 | val 0.73817
  Epoch 016 - train 0.61544 | val 0.93604
  Classification -> best τ=0.510 (val F1=0.1754)
  Directional -> Accuracy: 0.5667, MCC: 0.1345, F1: 0.5938

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.58659 | val 2.03116
  Epoch 018 - train 0.52325 | val 3.17089
  Classification -> best τ=0.685 (val F1=0.2673)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.62247 | val 0.83873
  Epoch 017 - train 0.55233 | val 1.03134
  Classification -> best τ=0.345 (val F1=0.2708)
  Directional -> Accuracy: 0.5942, MCC: 0.2079, F1: 0.7143

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.64987 | val 1.32800
  Epoch 017 - train 0.56532 | val 2.73139
  Classification -> best τ=0.395 (val F1=0.0884)
  Directional -> Accuracy: 0.4068, MCC: -0.1142, F1: 0.3860

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.63887 | val 1.13178
  Epoch 017 - train 0.62268 | val 2.25476
  Classification -> best τ=0.565 (val F1=0.1560)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.61043 | val 2.01936
  Epoch 016 - train 0.60253 | val 2.35883
  Classification -> best τ=0.415 (val F1=0.1280)
  Directional -> Accuracy: 0.4615, MCC: 0.0914, F1: 0.2222

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.63941 | val 1.13823
  Epoch 016 - train 0.59227 | val 0.90196
  Classification -> best τ=0.330 (val F1=0.2279)
  Directional -> Accuracy: 0.4933, MCC: -0.0819, F1: 0.6200

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.58581 | val 0.66580
  Epoch 020 - train 0.54818 | val 1.24705
  Epoch 023 - train 0.47110 | val 0.78727
  Classification -> best τ=0.595 (val F1=0.3689)
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.63904 | val 1.03321
  Epoch 017 - train 0.57129 | val 1.60334
  Classification -> best τ=0.575 (val F1=0.2699)
  Directional -> Accuracy: 0.4697, MCC: -0.0928, F1: 0.1463

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.67517 | val 0.88176
  Epoch 017 - train 0.61421 | val 0.81053
  Classification -> best τ=0.590 (val F1=0.3342)
  Directional -> Accuracy: 0.5000, MCC: 0.1008, F1: 0.3556

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.66350 | val 0.91089
  Epoch 020 - train 0.61061 | val 1.71481
  Epoch 024 - train 0.54768 | val 1.02945
  Classification -> best τ=0.500 (val F1=0.2378)
  Directional -> Accuracy: 0.4923, MCC: 0.0261, F1: 0.6207

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.58426 | val 0.67148
  Epoch 020 - train 0.52876 | val 0.76741
  Epoch 025 - train 0.54205 | val 0.84783
  Classification -> best τ=0.430 (val F1=0.4376)
  Directional -> Accuracy: 0.5179, MCC: 0.0797, F1: 0.4490

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.59647 | val 1.16044
  Epoch 016 - train 0.54702 | val 0.88631
  Classification -> best τ=0.495 (val F1=0.2935)
  Directional -> Accuracy: 0.5435, MCC: 0.1424, F1: 0.5882

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.59921 | val 0.71643
  Epoch 018 - train 0.60358 | val 0.68143
  Classification -> best τ=0.480 (val F1=0.2107)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.64410 | val 0.94086
  Epoch 016 - train 0.56238 | val 0.99556
  Classification -> best τ=0.410 (val F1=0.2668)
  Directional -> Accuracy: 0.5263, MCC: 0.2741, F1: 0.2703

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.59171 | val 0.72034
  Epoch 019 - train 0.54420 | val 1.04538
  Classification -> best τ=0.605 (val F1=0.3477)
  Directional -> Accuracy: 0.5122, MCC: -0.0108, F1: 0.6154

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.65478 | val 0.73585
  Epoch 020 - train 0.50317 | val 0.69943
  Epoch 021 - train 0.51129 | val 0.70660
  Classification -> best τ=0.385 (val F1=0.1777)
  Directional -> Accuracy: 0.5116, MCC: 0.0397, F1: 0.6038

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.61813 | val 1.14610
  Epoch 017 - train 0.56252 | val 1.27879
  Classification -> best τ=0.415 (val F1=0.2517)
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.63765 | val 0.98526
  Epoch 019 - train 0.47919 | val 1.17046
  Classification -> best τ=0.410 (val F1=0.3005)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.60569 | val 0.75599
  Epoch 020 - train 0.58965 | val 0.97836
  Epoch 023 - train 0.58166 | val 1.65955
  Classification -> best τ=0.530 (val F1=0.3568)
  Directional -> Accuracy: 0.5616, MCC: 0.1832, F1: 0.5000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.60242 | val 0.94126
  Epoch 016 - train 0.54517 | val 1.02094
  Classification -> best τ=0.450 (val F1=0.2887)
  Directional -> Accuracy: 0.5676, MCC: 0.1737, F1: 0.6522

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.62002 | val 0.86081
  Epoch 016 - train 0.60710 | val 1.07817
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.63250 | val 0.76594
  Epoch 020 - train 0.57769 | val 0.85113
  Epoch 028 - train 0.52447 | val 0.84876
  Classification -> best τ=0.465 (val F1=0.4034)
  Directional -> Accuracy: 0.5758, MCC: 0.1399, F1: 0.6216

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.57924 | val 1.19243
  Epoch 017 - train 0.54646 | val 1.21695
  Classification -> best τ=0.635 (val F1=0.2652)
  Directional -> Accuracy: 0.4762, MCC: -0.0107, F1: 0.0833

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.61137 | val 1.27658
  Epoch 016 - train 0.57336 | val 1.28819
  Classification -> best τ=0.340 (val F1=0.2946)
  Directional -> Accuracy: 0.5179, MCC: 0.1353, F1: 0.6400

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.58003 | val 1.33902
  Epoch 016 - train 0.51109 | val 1.71694
  Classification -> best τ=0.525 (val F1=0.5216)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.62889 | val 0.67797
  Epoch 020 - train 0.57362 | val 0.68427
  Epoch 030 - train 0.51194 | val 0.70883
  Epoch 033 - train 0.47463 | val 0.67289
  Classification -> best τ=0.355 (val F1=0.4708)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.57651 | val 0.82567
  Epoch 019 - train 0.51416 | val 1.37902
  Classification -> best τ=0.445 (val F1=0.1132)
  Directional -> Accuracy: 0.5135, MCC: 0.0293, F1: 0.5263

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.62151 | val 0.98912
  Epoch 017 - train 0.59762 | val 1.01973
  Classification -> best τ=0.470 (val F1=0.3595)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.68895 | val 0.68304
  Epoch 019 - train 0.56471 | val 1.09966
  Classification -> best τ=0.470 (val F1=0.3560)
  Directional -> Accuracy: 0.4565, MCC: -0.0756, F1: 0.3243

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.66948 | val 1.08702
  Epoch 016 - train 0.54997 | val 1.18120
  Classification -> best τ=0.510 (val F1=0.2855)
  Directional -> Accuracy: 0.6279, MCC: 0.2296, F1: 0.7143

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.60666 | val 0.81376
  Epoch 020 - train 0.55291 | val 0.80703
  Classification -> best τ=0.540 (val F1=0.5421)
  Directional -> Accuracy: 0.3673, MCC: -0.1462, F1: 0.5231

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.62867 | val 1.56030
  Epoch 017 - train 0.61835 | val 1.83972
  Classification -> best τ=0.575 (val F1=0.2787)
  Directional -> Accuracy: 0.5000, MCC: 0.1792, F1: 0.1250

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.63974 | val 1.08476
  Epoch 019 - train 0.61770 | val 1.15298
  Classification -> best τ=0.430 (val F1=0.2825)
  Directional -> Accuracy: 0.5536, MCC: 0.1012, F1: 0.4681

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.63155 | val 2.20302
  Epoch 017 - train 0.61025 | val 2.14964
  Classification -> best τ=0.365 (val F1=0.3097)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.61255 | val 1.73087
  Epoch 016 - train 0.54219 | val 1.68785
  Classification -> best τ=0.460 (val F1=0.1168)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.62430 | val 0.70460

[I 2026-02-25 02:29:09,614] Trial 161 finished with value: 0.2713058243393156 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.6000000000000001, 'batch_size': 32, 'learning_rate': 0.003821893089728022, 'weight_decay': 0.0009009481264000482, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 0.3892751992511918, 'early_stopping_min_delta': 0.002789394699272212}. Best is trial 140 with value: 0.29322408230766744.

  Epoch 017 - train 0.57169 | val 1.70447
  Classification -> best τ=0.445 (val F1=0.1498)
  Directional -> Accuracy: 0.4918, MCC: -0.0401, F1: 0.3404

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2713058243393156
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.64011 | val 0.93591
  Epoch 018 - train 0.58246 | val 0.81683
  Classification -> best τ=0.580 (val F1=0.2510)
  Directional -> Accuracy: 0.5526, MCC: 0.0719, F1: 0.4138

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.58007 | val 0.75662
  Epoch 016 - train 0.59758 | val 0.80412
  Classification -> best τ=0.435 (val F1=0.0406)
  Directional -> Accuracy: 0.6000, MCC: 0.1297, F1: 0.7188

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.66712 | val 0.81754
  Epoch 020 - train 0.59180 | val 1.48668
  Classification -> best τ=0.570 (val F1=0.4245)
  Directional -> Accuracy: 0.5319, MCC: 0.1157, F1: 0.3889

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.67875 | val 1.75563
  Epoch 017 - train 0.64388 | val 1.96615
  Classification -> best τ=0.220 (val F1=0.2163)
  Directional -> Accuracy: 0.4267, MCC: -0.1136, F1: 0.2182

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.64241 | val 0.69803
  Epoch 020 - train 0.53132 | val 0.86948
  Classification -> best τ=0.480 (val F1=0.3395)
  Directional -> Accuracy: 0.5686, MCC: 0.1633, F1: 0.7027

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.62726 | val 1.04320
  Epoch 016 - train 0.58694 | val 0.83745
  Classification -> best τ=0.450 (val F1=0.2335)
  Directional -> Accuracy: 0.4894, MCC: 0.0000, F1: 0.6571

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.68826 | val 0.77729
  Epoch 016 - train 0.64980 | val 0.74322
  Classification -> best τ=0.490 (val F1=0.2135)
  Directional -> Accuracy: 0.5507, MCC: 0.1854, F1: 0.5867

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.64299 | val 1.03573
  Epoch 020 - train 0.61012 | val 1.10219
  Classification -> best τ=0.325 (val F1=0.1214)
  Directional -> Accuracy: 0.4651, MCC: -0.1076, F1: 0.3429

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.62244 | val 0.95968
  Epoch 016 - train 0.57908 | val 1.72220
  Classification -> best τ=0.550 (val F1=0.3039)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.59746 | val 0.75095
  Epoch 016 - train 0.58198 | val 1.34565
  Classification -> best τ=0.490 (val F1=0.1816)
  Directional -> Accuracy: 0.4571, MCC: 0.0236, F1: 0.5778

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.59158 | val 1.43551
  Epoch 017 - train 0.56999 | val 2.24369
  Classification -> best τ=0.495 (val F1=0.2562)
  Directional -> Accuracy: 0.6000, MCC: 0.1948, F1: 0.5652

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.59845 | val 1.03509
  Epoch 016 - train 0.59048 | val 1.28574
  Classification -> best τ=0.460 (val F1=0.2275)
  Directional -> Accuracy: 0.5517, MCC: 0.1588, F1: 0.2778

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.64255 | val 0.97456
  Epoch 020 - train 0.53879 | val 1.28821
  Epoch 024 - train 0.52977 | val 1.34194
  Classification -> best τ=0.580 (val F1=0.3588)
  Directional -> Accuracy: 0.3810, MCC: -0.2981, F1: 0.1875

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.68398 | val 0.90852
  Epoch 018 - train 0.63175 | val 1.21119
  Classification -> best τ=0.545 (val F1=0.1774)
  Directional -> Accuracy: 0.4667, MCC: -0.1857, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.61783 | val 1.53803
  Epoch 019 - train 0.54854 | val 2.10502
  Classification -> best τ=0.685 (val F1=0.2673)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.61050 | val 0.88829
  Epoch 018 - train 0.62308 | val 0.89566
  Classification -> best τ=0.585 (val F1=0.2276)
  Directional -> Accuracy: 0.5652, MCC: 0.2739, F1: 0.3478

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.66199 | val 1.53181
  Epoch 016 - train 0.62917 | val 1.93661
  Classification -> best τ=0.400 (val F1=0.1905)
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.66279 | val 1.10863
  Epoch 016 - train 0.61619 | val 1.77345
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6000, MCC: 0.0000, F1: 0.7500

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.67117 | val 1.61610
  Epoch 017 - train 0.59098 | val 2.29793
  Classification -> best τ=0.515 (val F1=0.3804)
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.61905 | val 0.84493
  Epoch 020 - train 0.57668 | val 1.02422
  Epoch 022 - train 0.56571 | val 1.15212
  Classification -> best τ=0.410 (val F1=0.2691)
  Directional -> Accuracy: 0.4667, MCC: -0.0134, F1: 0.2857

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.63309 | val 0.67140
  Epoch 020 - train 0.54568 | val 0.82341
  Epoch 025 - train 0.52430 | val 1.29902
  Classification -> best τ=0.510 (val F1=0.3296)
  Directional -> Accuracy: 0.5106, MCC: 0.1957, F1: 0.4103

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.67399 | val 0.92945
  Epoch 016 - train 0.66384 | val 0.92109
  Classification -> best τ=0.460 (val F1=0.2390)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6024

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.68825 | val 0.77199
  Epoch 016 - train 0.62689 | val 0.81915
  Classification -> best τ=0.535 (val F1=0.2653)
  Directional -> Accuracy: 0.5345, MCC: 0.1064, F1: 0.5091

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.60322 | val 0.75952
  Epoch 016 - train 0.59639 | val 0.97815
  Classification -> best τ=0.455 (val F1=0.1507)
  Directional -> Accuracy: 0.5077, MCC: 0.0402, F1: 0.5897

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.63794 | val 0.64489
  Epoch 020 - train 0.57895 | val 0.80242
  Epoch 023 - train 0.54643 | val 0.82821
  Classification -> best τ=0.455 (val F1=0.4436)
  Directional -> Accuracy: 0.5714, MCC: 0.1656, F1: 0.5556

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.67821 | val 0.89009
  Epoch 016 - train 0.59026 | val 1.44130
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.67166 | val 0.86956
  Epoch 016 - train 0.66259 | val 1.02010
  Classification -> best τ=0.530 (val F1=0.1936)
  Directional -> Accuracy: 0.5238, MCC: 0.0694, F1: 0.5238

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.62582 | val 0.87770
  Epoch 019 - train 0.60818 | val 1.13659
  Classification -> best τ=0.410 (val F1=0.1944)
  Directional -> Accuracy: 0.5789, MCC: 0.1193, F1: 0.6667

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.65485 | val 0.91214
  Epoch 017 - train 0.64716 | val 0.90858
  Classification -> best τ=0.565 (val F1=0.6078)
  Directional -> Accuracy: 0.5122, MCC: 0.0191, F1: 0.5455

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.68486 | val 1.04113
  Epoch 020 - train 0.53342 | val 1.45035
  Epoch 021 - train 0.50539 | val 1.57505
  Classification -> best τ=0.385 (val F1=0.2304)
  Directional -> Accuracy: 0.5349, MCC: 0.0831, F1: 0.6000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.70521 | val 0.78761
  Epoch 018 - train 0.53403 | val 0.89084
  Classification -> best τ=0.675 (val F1=0.1204)
  Directional -> Accuracy: 0.4651, MCC: -0.0154, F1: 0.0800

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.62527 | val 0.93318
  Epoch 018 - train 0.58975 | val 1.11871
  Classification -> best τ=0.600 (val F1=0.2399)
  Directional -> Accuracy: 0.3800, MCC: -0.2330, F1: 0.2051

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.64339 | val 0.79556
  Epoch 018 - train 0.60886 | val 1.04018
  Classification -> best τ=0.375 (val F1=0.3251)
  Directional -> Accuracy: 0.5479, MCC: 0.1851, F1: 0.4407

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.63105 | val 0.78934
  Epoch 017 - train 0.52790 | val 1.68260
  Classification -> best τ=0.475 (val F1=0.3627)
  Directional -> Accuracy: 0.5135, MCC: 0.0367, F1: 0.5714

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.63395 | val 1.01604
  Epoch 018 - train 0.60351 | val 0.83312
  Classification -> best τ=0.560 (val F1=0.3100)
  Directional -> Accuracy: 0.5682, MCC: 0.1548, F1: 0.6122

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.64819 | val 0.76098
  Epoch 019 - train 0.60396 | val 0.77629
  Classification -> best τ=0.180 (val F1=0.3603)
  Directional -> Accuracy: 0.5909, MCC: 0.1443, F1: 0.6667

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.57420 | val 1.13776
  Epoch 016 - train 0.56592 | val 1.07229
  Classification -> best τ=0.525 (val F1=0.2568)
  Directional -> Accuracy: 0.4762, MCC: -0.0337, F1: 0.3889

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.71764 | val 1.54111
  Epoch 016 - train 0.60472 | val 1.35082
  Classification -> best τ=0.430 (val F1=0.2755)
  Directional -> Accuracy: 0.5179, MCC: 0.0878, F1: 0.6087

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.58280 | val 1.97554
  Epoch 016 - train 0.52843 | val 1.45771
  Classification -> best τ=0.510 (val F1=0.4336)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.67781 | val 0.68742
  Epoch 020 - train 0.56878 | val 0.64502
  Epoch 030 - train 0.51680 | val 0.72863
  Epoch 040 - train 0.46639 | val 0.65463
  Epoch 050 - train 0.37038 | val 0.63359
  Classification -> best τ=0.295 (val F1=0.4176)
  Directional -> Accuracy: 0.3469, MCC: -0.1894, F1: 0.5152

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.57417 | val 0.73700
  Epoch 016 - train 0.56711 | val 0.86179
  Classification -> best τ=0.505 (val F1=0.2631)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.63196 | val 0.91085
  Epoch 016 - train 0.59636 | val 1.08307
  Classification -> best τ=0.410 (val F1=0.3356)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.60650 | val 1.00225
  Epoch 018 - train 0.63043 | val 0.81637
  Classification -> best τ=0.400 (val F1=0.4692)
  Directional -> Accuracy: 0.5000, MCC: 0.0266, F1: 0.3429

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.60078 | val 0.81214
  Epoch 016 - train 0.53074 | val 0.85128
  Classification -> best τ=0.465 (val F1=0.1581)
  Directional -> Accuracy: 0.6279, MCC: 0.2419, F1: 0.7333

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.66692 | val 0.69431
  Epoch 020 - train 0.59738 | val 0.81982
  Epoch 023 - train 0.53763 | val 0.70751
  Classification -> best τ=0.625 (val F1=0.5131)
  Directional -> Accuracy: 0.3673, MCC: -0.1462, F1: 0.5231

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.66084 | val 1.99459
  Epoch 020 - train 0.65403 | val 2.06325
  Epoch 021 - train 0.64040 | val 1.98351
  Classification -> best τ=0.365 (val F1=0.2293)
  Directional -> Accuracy: 0.5536, MCC: 0.1726, F1: 0.4186

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.62585 | val 0.81065
  Epoch 019 - train 0.62224 | val 0.92219
  Classification -> best τ=0.480 (val F1=0.4137)
  Directional -> Accuracy: 0.5714, MCC: 0.2566, F1: 0.6842

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.63637 | val 1.58403
  Epoch 016 - train 0.59984 | val 1.73886
  Classification -> best τ=0.290 (val F1=0.2925)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.65264 | val 1.69192
  Epoch 016 - train 0.62292 | val 2.94366
  Classification -> best τ=0.605 (val F1=0.1557)
  Directional -> Accuracy: 0.4107, MCC: -0.1857, F1: 0.2326

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.65951 | val 1.24575

[I 2026-02-25 02:31:23,005] Trial 162 finished with value: 0.27037037308970713 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 0.003152225448430978, 'weight_decay': 0.0005001591662326736, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 0.4376242361769906, 'early_stopping_min_delta': 0.0023137431334394193}. Best is trial 140 with value: 0.29322408230766744.

  Epoch 016 - train 0.60873 | val 1.70499
  Classification -> best τ=0.545 (val F1=0.2511)
  Directional -> Accuracy: 0.5574, MCC: 0.1105, F1: 0.3077

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.27037037308970713
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.61300 | val 1.44182
  Epoch 020 - train 0.58380 | val 1.45346
  Classification -> best τ=0.500 (val F1=0.2919)
  Directional -> Accuracy: 0.4079, MCC: -0.1616, F1: 0.5545

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.60362 | val 0.79369
  Epoch 020 - train 0.56883 | val 0.83043
  Epoch 021 - train 0.49527 | val 0.77297
  Classification -> best τ=0.405 (val F1=0.2722)
  Directional -> Accuracy: 0.4444, MCC: 0.1289, F1: 0.0741

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.61563 | val 1.03826
  Epoch 017 - train 0.58585 | val 1.73770
  Classification -> best τ=0.535 (val F1=0.4065)
  Directional -> Accuracy: 0.4894, MCC: 0.1383, F1: 0.0769

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.64344 | val 1.65941
  Epoch 016 - train 0.62353 | val 1.87575
  Classification -> best τ=0.355 (val F1=0.1810)
  Directional -> Accuracy: 0.5200, MCC: 0.0414, F1: 0.5385

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.55552 | val 0.72741
  Epoch 017 - train 0.48799 | val 1.28000
  Classification -> best τ=0.555 (val F1=0.4380)
  Directional -> Accuracy: 0.4314, MCC: -0.1278, F1: 0.3830

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.61220 | val 0.78606
  Epoch 020 - train 0.46360 | val 0.96215
  Epoch 021 - train 0.44793 | val 1.07949
  Classification -> best τ=0.475 (val F1=0.2774)
  Directional -> Accuracy: 0.5106, MCC: 0.0311, F1: 0.5818

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.64405 | val 0.81876
  Epoch 017 - train 0.62378 | val 0.84595
  Classification -> best τ=0.360 (val F1=0.2041)
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.62146 | val 0.85597
  Epoch 016 - train 0.49518 | val 0.86597
  Classification -> best τ=0.540 (val F1=0.0522)
  Directional -> Accuracy: 0.4884, MCC: -0.0680, F1: 0.3529

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.61554 | val 1.32897
  Epoch 018 - train 0.51635 | val 1.80082
  Classification -> best τ=0.450 (val F1=0.3641)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.59151 | val 0.68757
  Epoch 020 - train 0.54372 | val 0.78817
  Epoch 025 - train 0.51397 | val 0.77279
  Classification -> best τ=0.540 (val F1=0.1920)
  Directional -> Accuracy: 0.4857, MCC: -0.0248, F1: 0.4545

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.62267 | val 2.15916
  Epoch 018 - train 0.54914 | val 3.20127
  Classification -> best τ=0.555 (val F1=0.2978)
  Directional -> Accuracy: 0.6000, MCC: 0.2059, F1: 0.3333

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.59503 | val 1.23499
  Epoch 017 - train 0.54190 | val 0.97043
  Classification -> best τ=0.510 (val F1=0.3740)
  Directional -> Accuracy: 0.5517, MCC: 0.1843, F1: 0.2353

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.60534 | val 1.09893
  Epoch 017 - train 0.58170 | val 1.40400
  Classification -> best τ=0.390 (val F1=0.1908)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.67064 | val 0.91484
  Epoch 020 - train 0.62731 | val 0.92340
  Epoch 022 - train 0.61811 | val 1.47606
  Classification -> best τ=0.330 (val F1=0.2795)
  Directional -> Accuracy: 0.5500, MCC: 0.2294, F1: 0.6897

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.63797 | val 1.82983
  Epoch 017 - train 0.53606 | val 2.79794
  Classification -> best τ=0.600 (val F1=0.2673)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.62117 | val 0.86166
  Epoch 019 - train 0.55278 | val 0.83659
  Classification -> best τ=0.585 (val F1=0.2173)
  Directional -> Accuracy: 0.4783, MCC: 0.0081, F1: 0.2500

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.63854 | val 2.13023
  Epoch 016 - train 0.61800 | val 2.02265
  Classification -> best τ=0.420 (val F1=0.1387)
  Directional -> Accuracy: 0.5932, MCC: 0.1142, F1: 0.6842

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.61620 | val 1.58044
  Epoch 016 - train 0.61409 | val 1.64729
  Classification -> best τ=0.440 (val F1=0.1289)
  Directional -> Accuracy: 0.5600, MCC: 0.0250, F1: 0.6733

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.62731 | val 1.35750
  Epoch 017 - train 0.58277 | val 2.59638
  Classification -> best τ=0.500 (val F1=0.2942)
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.63747 | val 0.81597
  Epoch 018 - train 0.59288 | val 0.87971
  Classification -> best τ=0.460 (val F1=0.1824)
  Directional -> Accuracy: 0.4800, MCC: 0.1507, F1: 0.0930

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.59004 | val 0.69819
  Epoch 020 - train 0.53791 | val 1.26441
  Epoch 024 - train 0.45763 | val 1.94355
  Classification -> best τ=0.590 (val F1=0.3687)
  Directional -> Accuracy: 0.4043, MCC: 0.1162, F1: 0.0667

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.68296 | val 0.76258
  Epoch 020 - train 0.55636 | val 1.56094
  Epoch 021 - train 0.60040 | val 1.26724
  Classification -> best τ=0.415 (val F1=0.2284)
  Directional -> Accuracy: 0.5303, MCC: 0.0845, F1: 0.6517

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.66768 | val 0.74558
  Epoch 017 - train 0.59419 | val 0.72206
  Classification -> best τ=0.585 (val F1=0.3498)
  Directional -> Accuracy: 0.4828, MCC: 0.0846, F1: 0.2857

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.61083 | val 0.84100
  Epoch 018 - train 0.56947 | val 0.90024
  Classification -> best τ=0.300 (val F1=0.1132)
  Directional -> Accuracy: 0.4769, MCC: 0.0000, F1: 0.6458

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.61628 | val 0.70337
  Epoch 020 - train 0.53641 | val 1.03921
  Epoch 024 - train 0.52686 | val 0.83994
  Classification -> best τ=0.525 (val F1=0.4436)
  Directional -> Accuracy: 0.5357, MCC: 0.1728, F1: 0.3810

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.55836 | val 0.79809
  Epoch 016 - train 0.54926 | val 1.13330
  Classification -> best τ=0.570 (val F1=0.2935)
  Directional -> Accuracy: 0.4565, MCC: 0.0541, F1: 0.6032

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.66200 | val 0.72087
  Epoch 020 - train 0.55918 | val 1.01275
  Epoch 021 - train 0.57478 | val 1.53932
  Classification -> best τ=0.500 (val F1=0.2477)
  Directional -> Accuracy: 0.4762, MCC: -0.0142, F1: 0.4500

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.65540 | val 0.83488
  Epoch 016 - train 0.56292 | val 0.99936
  Classification -> best τ=0.490 (val F1=0.1940)
  Directional -> Accuracy: 0.4561, MCC: 0.1181, F1: 0.0606

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.65092 | val 0.72759
  Epoch 020 - train 0.48911 | val 1.96512
  Epoch 021 - train 0.50739 | val 1.32819
  Classification -> best τ=0.490 (val F1=0.3278)
  Directional -> Accuracy: 0.5610, MCC: 0.1145, F1: 0.7000

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.61528 | val 0.77203
  Epoch 016 - train 0.52473 | val 2.05192
  Classification -> best τ=0.525 (val F1=0.5210)
  Directional -> Accuracy: 0.5116, MCC: 0.0145, F1: 0.3636

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.60079 | val 0.74708
  Epoch 017 - train 0.48977 | val 0.96430
  Classification -> best τ=0.630 (val F1=0.1204)
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.59636 | val 1.02401
  Epoch 016 - train 0.53600 | val 1.33539
  Classification -> best τ=0.555 (val F1=0.2399)
  Directional -> Accuracy: 0.4400, MCC: -0.1048, F1: 0.0667

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.61902 | val 0.76624
  Epoch 016 - train 0.56265 | val 1.26738
  Classification -> best τ=0.540 (val F1=0.1900)
  Directional -> Accuracy: 0.4384, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.51459 | val 0.86927
  Epoch 016 - train 0.53975 | val 1.07350
  Classification -> best τ=0.410 (val F1=0.3651)
  Directional -> Accuracy: 0.5135, MCC: 0.0477, F1: 0.6087

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.61899 | val 0.80569
  Epoch 017 - train 0.51080 | val 1.11077
  Classification -> best τ=0.510 (val F1=0.1676)
  Directional -> Accuracy: 0.3864, MCC: -0.2833, F1: 0.5424

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.62697 | val 0.67070
  Epoch 018 - train 0.57204 | val 0.84343
  Classification -> best τ=0.395 (val F1=0.3254)
  Directional -> Accuracy: 0.6212, MCC: 0.2284, F1: 0.6667

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.59058 | val 1.25645
  Epoch 016 - train 0.49286 | val 1.84235
  Classification -> best τ=0.500 (val F1=0.2357)
  Directional -> Accuracy: 0.4762, MCC: -0.0155, F1: 0.1538

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.61143 | val 1.60460
  Epoch 016 - train 0.54014 | val 1.36382
  Classification -> best τ=0.330 (val F1=0.2450)
  Directional -> Accuracy: 0.5536, MCC: 0.1377, F1: 0.6032

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.52478 | val 2.23462
  Epoch 016 - train 0.44070 | val 2.19626
  Classification -> best τ=0.530 (val F1=0.4012)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.64834 | val 0.64741
  Epoch 020 - train 0.58744 | val 0.63479
  Epoch 030 - train 0.44529 | val 0.69604
  Epoch 036 - train 0.37042 | val 0.65115
  Classification -> best τ=0.345 (val F1=0.5815)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.64834 | val 0.75934
  Epoch 020 - train 0.44823 | val 1.09514
  Epoch 021 - train 0.41279 | val 1.38544
  Classification -> best τ=0.430 (val F1=0.3019)
  Directional -> Accuracy: 0.5405, MCC: 0.0427, F1: 0.6531

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.64361 | val 0.79858
  Epoch 017 - train 0.61764 | val 1.19159
  Classification -> best τ=0.240 (val F1=0.4061)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.57459 | val 0.91558
  Epoch 017 - train 0.61099 | val 0.98594
  Classification -> best τ=0.465 (val F1=0.2748)
  Directional -> Accuracy: 0.5435, MCC: 0.0763, F1: 0.6557

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.57478 | val 1.18835
  Epoch 016 - train 0.52900 | val 1.21671
  Classification -> best τ=0.505 (val F1=0.0381)
  Directional -> Accuracy: 0.5349, MCC: 0.0468, F1: 0.6000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.60382 | val 0.73521
  Epoch 018 - train 0.47803 | val 1.52668
  Classification -> best τ=0.565 (val F1=0.6590)
  Directional -> Accuracy: 0.5918, MCC: 0.1239, F1: 0.4444

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.61605 | val 1.77046
  Epoch 018 - train 0.60802 | val 1.74812
  Classification -> best τ=0.435 (val F1=0.1676)
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.63376 | val 0.89507
  Epoch 016 - train 0.61329 | val 1.25118
  Classification -> best τ=0.535 (val F1=0.2875)
  Directional -> Accuracy: 0.5357, MCC: 0.1397, F1: 0.0714

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.65378 | val 1.67065
  Epoch 016 - train 0.57983 | val 2.76163
  Classification -> best τ=0.350 (val F1=0.2079)
  Directional -> Accuracy: 0.5370, MCC: 0.1425, F1: 0.6914

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.60812 | val 2.21646
  Epoch 016 - train 0.58266 | val 1.80261
  Classification -> best τ=0.410 (val F1=0.1633)
  Directional -> Accuracy: 0.4643, MCC: -0.0625, F1: 0.3478

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.61144 | val 0.80746
  Epoch 020 - train 0.56246 | val 0.97097

[I 2026-02-25 02:33:38,321] Trial 163 finished with value: 0.2733454301059784 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.6000000000000001, 'batch_size': 32, 'learning_rate': 0.004024317197350822, 'weight_decay': 0.00037809528850423955, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 0.32933560003034, 'early_stopping_min_delta': 0.0032366585371419393}. Best is trial 140 with value: 0.29322408230766744.

  Epoch 022 - train 0.51685 | val 1.14108
  Classification -> best τ=0.370 (val F1=0.1513)
  Directional -> Accuracy: 0.4098, MCC: -0.1737, F1: 0.4706

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2733454301059784
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.64034 | val 1.00705
  Epoch 017 - train 0.62016 | val 1.14325
  Classification -> best τ=0.370 (val F1=0.3319)
  Directional -> Accuracy: 0.5263, MCC: 0.1278, F1: 0.6087

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.61476 | val 0.71725
  Epoch 020 - train 0.56092 | val 0.79447
  Epoch 024 - train 0.54289 | val 1.00206
  Classification -> best τ=0.415 (val F1=0.1424)
  Directional -> Accuracy: 0.6000, MCC: 0.1764, F1: 0.7429

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.65389 | val 0.68799
  Epoch 018 - train 0.63927 | val 0.71885
  Classification -> best τ=0.620 (val F1=0.2941)
  Directional -> Accuracy: 0.4255, MCC: -0.1723, F1: 0.0690

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.66244 | val 1.05824
  Epoch 017 - train 0.65169 | val 0.96717
  Classification -> best τ=0.440 (val F1=0.2286)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.61836 | val 0.71214
  Epoch 019 - train 0.59519 | val 0.92461
  Classification -> best τ=0.610 (val F1=0.3795)
  Directional -> Accuracy: 0.6471, MCC: 0.3202, F1: 0.6087

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.62765 | val 0.71630
  Epoch 016 - train 0.53569 | val 1.37485
  Classification -> best τ=0.485 (val F1=0.2108)
  Directional -> Accuracy: 0.4894, MCC: 0.0000, F1: 0.6571

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.67327 | val 0.79110
  Epoch 020 - train 0.64163 | val 0.78253
  Epoch 021 - train 0.62814 | val 0.76847
  Classification -> best τ=0.485 (val F1=0.3024)
  Directional -> Accuracy: 0.4493, MCC: 0.0822, F1: 0.5778

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.65037 | val 1.61370
  Epoch 020 - train 0.57609 | val 0.95941
  Classification -> best τ=0.390 (val F1=0.3468)
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.63974 | val 1.53845
  Epoch 018 - train 0.55623 | val 2.12565
  Classification -> best τ=0.510 (val F1=0.4053)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.62058 | val 0.85984
  Epoch 020 - train 0.60353 | val 0.69662
  Epoch 026 - train 0.55238 | val 0.79222
  Classification -> best τ=0.465 (val F1=0.3401)
  Directional -> Accuracy: 0.4857, MCC: 0.0722, F1: 0.5814

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.63151 | val 1.57340
  Epoch 018 - train 0.54315 | val 2.44242
  Classification -> best τ=0.680 (val F1=0.2722)
  Directional -> Accuracy: 0.6000, MCC: 0.2006, F1: 0.5833

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.62916 | val 1.26083
  Epoch 019 - train 0.58721 | val 1.76133
  Classification -> best τ=0.630 (val F1=0.2646)
  Directional -> Accuracy: 0.7069, MCC: 0.4140, F1: 0.7119

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.66162 | val 1.00692
  Epoch 016 - train 0.57307 | val 0.89968
  Classification -> best τ=0.490 (val F1=0.2647)
  Directional -> Accuracy: 0.5476, MCC: 0.1353, F1: 0.5957

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.66370 | val 0.69157
  Epoch 020 - train 0.64106 | val 0.84725
  Epoch 023 - train 0.61916 | val 0.73147
  Classification -> best τ=0.450 (val F1=0.3282)
  Directional -> Accuracy: 0.5500, MCC: 0.1400, F1: 0.6667

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.66714 | val 1.13848
  Epoch 018 - train 0.55503 | val 2.10608
  Classification -> best τ=0.495 (val F1=0.3313)
  Directional -> Accuracy: 0.5385, MCC: 0.2673, F1: 0.6667

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.64194 | val 0.80854
  Epoch 018 - train 0.59542 | val 1.11937
  Classification -> best τ=0.320 (val F1=0.3015)
  Directional -> Accuracy: 0.5362, MCC: 0.0000, F1: 0.6981

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.67619 | val 1.62749
  Epoch 017 - train 0.66812 | val 2.85130
  Classification -> best τ=0.305 (val F1=0.2048)
  Directional -> Accuracy: 0.6441, MCC: 0.1506, F1: 0.7640

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.63500 | val 1.34643
  Epoch 016 - train 0.64492 | val 1.36574
  Classification -> best τ=0.495 (val F1=0.0558)
  Directional -> Accuracy: 0.4800, MCC: -0.1627, F1: 0.6139

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.64958 | val 1.47641
  Epoch 016 - train 0.66828 | val 2.04400
  Classification -> best τ=0.515 (val F1=0.3180)
  Directional -> Accuracy: 0.4000, MCC: -0.1483, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.61560 | val 0.72778
  Epoch 017 - train 0.61975 | val 0.75278
  Classification -> best τ=0.490 (val F1=0.2468)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.61976 | val 0.66476
  Epoch 020 - train 0.58577 | val 0.91980
  Epoch 022 - train 0.55006 | val 0.67598
  Classification -> best τ=0.375 (val F1=0.2845)
  Directional -> Accuracy: 0.4681, MCC: 0.1702, F1: 0.2857

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.67744 | val 0.75007
  Epoch 016 - train 0.67474 | val 0.76387
  Classification -> best τ=0.530 (val F1=0.1878)
  Directional -> Accuracy: 0.5606, MCC: 0.2540, F1: 0.2162

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.68796 | val 0.71849
  Epoch 020 - train 0.64928 | val 0.89991
  Epoch 024 - train 0.63712 | val 0.81658
  Classification -> best τ=0.730 (val F1=0.2967)
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.65869 | val 0.84602
  Epoch 018 - train 0.65688 | val 0.79125
  Classification -> best τ=0.520 (val F1=0.0816)
  Directional -> Accuracy: 0.4769, MCC: -0.0308, F1: 0.5526

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.63928 | val 0.66967
  Epoch 020 - train 0.58654 | val 0.72973
  Epoch 021 - train 0.59885 | val 0.73656
  Classification -> best τ=0.605 (val F1=0.4795)
  Directional -> Accuracy: 0.4643, MCC: 0.1211, F1: 0.0625

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.62629 | val 1.01178
  Epoch 016 - train 0.61441 | val 1.36193
  Classification -> best τ=0.550 (val F1=0.0524)
  Directional -> Accuracy: 0.5652, MCC: 0.1641, F1: 0.5833

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.65977 | val 0.70474
  Epoch 020 - train 0.59323 | val 0.74000
  Epoch 022 - train 0.62593 | val 0.69332
  Classification -> best τ=0.615 (val F1=0.1936)
  Directional -> Accuracy: 0.4762, MCC: 0.0000, F1: 0.4211

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.65657 | val 0.79927
  Epoch 017 - train 0.58738 | val 1.01345
  Classification -> best τ=0.425 (val F1=0.2789)
  Directional -> Accuracy: 0.4912, MCC: 0.2083, F1: 0.1714

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.56049 | val 0.72850
  Epoch 020 - train 0.55706 | val 0.71911
  Epoch 030 - train 0.55478 | val 1.47935
  Epoch 031 - train 0.50141 | val 0.93228
  Classification -> best τ=0.820 (val F1=0.2774)
  Directional -> Accuracy: 0.4878, MCC: 0.0202, F1: 0.3226

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.64281 | val 0.85741
  Epoch 020 - train 0.57191 | val 1.03508
  Epoch 021 - train 0.56894 | val 1.01349
  Classification -> best τ=0.485 (val F1=0.4110)
  Directional -> Accuracy: 0.5349, MCC: 0.1084, F1: 0.6429

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.63842 | val 0.70623
  Epoch 020 - train 0.54273 | val 0.72056
  Classification -> best τ=0.490 (val F1=0.2517)
  Directional -> Accuracy: 0.5116, MCC: -0.0323, F1: 0.6441

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.63467 | val 0.80887
  Epoch 016 - train 0.55500 | val 1.07881
  Classification -> best τ=0.425 (val F1=0.2918)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.63456 | val 0.76906
  Epoch 020 - train 0.63228 | val 1.23008
  Epoch 030 - train 0.56803 | val 1.51194
  Epoch 036 - train 0.54355 | val 1.31993
  Classification -> best τ=0.635 (val F1=0.3273)
  Directional -> Accuracy: 0.5753, MCC: 0.2069, F1: 0.5231

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.66209 | val 1.44093
  Epoch 016 - train 0.58101 | val 1.53846
  Classification -> best τ=0.440 (val F1=0.2887)
  Directional -> Accuracy: 0.5135, MCC: 0.0367, F1: 0.5714

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.63916 | val 0.86666
  Epoch 016 - train 0.59571 | val 1.06577
  Classification -> best τ=0.470 (val F1=0.2757)
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.64892 | val 0.69454
  Epoch 019 - train 0.60672 | val 0.79370
  Classification -> best τ=0.260 (val F1=0.3366)
  Directional -> Accuracy: 0.4242, MCC: -0.1159, F1: 0.3871

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.61074 | val 0.91028
  Epoch 017 - train 0.51904 | val 1.32590
  Classification -> best τ=0.415 (val F1=0.2819)
  Directional -> Accuracy: 0.7143, MCC: 0.4534, F1: 0.6842

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.65039 | val 1.05229
  Epoch 016 - train 0.66519 | val 1.13894
  Classification -> best τ=0.520 (val F1=0.2382)
  Directional -> Accuracy: 0.5000, MCC: 0.0910, F1: 0.6316

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.57750 | val 1.67397
  Epoch 016 - train 0.54689 | val 2.43275
  Classification -> best τ=0.525 (val F1=0.4043)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.70301 | val 0.62807
  Epoch 020 - train 0.54004 | val 0.64772
  Epoch 030 - train 0.55761 | val 0.59981
  Epoch 040 - train 0.45831 | val 0.67401
  Epoch 045 - train 0.45136 | val 0.64942
  Classification -> best τ=0.275 (val F1=0.5617)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.61703 | val 0.86883
  Epoch 016 - train 0.59845 | val 0.98511
  Classification -> best τ=0.490 (val F1=0.2623)
  Directional -> Accuracy: 0.5135, MCC: 0.1113, F1: 0.3077

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.65658 | val 0.89693
  Epoch 017 - train 0.61356 | val 1.01206
  Classification -> best τ=0.375 (val F1=0.3597)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.68489 | val 0.82777
  Epoch 020 - train 0.60681 | val 1.21547
  Epoch 027 - train 0.55559 | val 1.31868
  Classification -> best τ=0.490 (val F1=0.3560)
  Directional -> Accuracy: 0.4783, MCC: -0.0229, F1: 0.2941

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.62187 | val 0.97236
  Epoch 020 - train 0.54816 | val 1.35584
  Epoch 022 - train 0.52236 | val 1.55669
  Classification -> best τ=0.690 (val F1=0.6031)
  Directional -> Accuracy: 0.6047, MCC: 0.1870, F1: 0.6667

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.65620 | val 0.79629
  Epoch 017 - train 0.61478 | val 1.03787
  Classification -> best τ=0.540 (val F1=0.6292)
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.67941 | val 1.44784
  Epoch 018 - train 0.64806 | val 0.99634
  Classification -> best τ=0.535 (val F1=0.1942)
  Directional -> Accuracy: 0.4286, MCC: -0.1708, F1: 0.5152

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.68267 | val 0.79426
  Epoch 016 - train 0.63257 | val 0.97366
  Classification -> best τ=0.615 (val F1=0.3948)
  Directional -> Accuracy: 0.4643, MCC: -0.0791, F1: 0.4000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.67351 | val 1.33633
  Epoch 016 - train 0.60824 | val 1.81615
  Classification -> best τ=0.300 (val F1=0.2024)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.60948 | val 1.40818
  Epoch 017 - train 0.59861 | val 1.26607
  Classification -> best τ=0.565 (val F1=0.2076)
  Directional -> Accuracy: 0.5357, MCC: 0.1397, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.64518 | val 0.78475

[I 2026-02-25 02:35:58,613] Trial 164 finished with value: 0.2973019295845425 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 0.004936132666753626, 'weight_decay': 0.0006283905956880348, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 0.5871496967453802, 'early_stopping_min_delta': 0.002952058500300668}. Best is trial 164 with value: 0.2973019295845425.

  Epoch 018 - train 0.61786 | val 1.09686
  Classification -> best τ=0.340 (val F1=0.2847)
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2973019295845425
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.66733 | val 0.78124
  Epoch 019 - train 0.63243 | val 1.23467
  Classification -> best τ=0.675 (val F1=0.2919)
  Directional -> Accuracy: 0.5526, MCC: 0.0174, F1: 0.0556

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.65918 | val 1.24326
  Epoch 020 - train 0.59509 | val 0.91868
  Epoch 021 - train 0.58116 | val 1.09550
  Classification -> best τ=0.510 (val F1=0.1700)
  Directional -> Accuracy: 0.5778, MCC: 0.1170, F1: 0.6545

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.67354 | val 0.79996
  Epoch 019 - train 0.58830 | val 0.84093
  Classification -> best τ=0.530 (val F1=0.1964)
  Directional -> Accuracy: 0.6596, MCC: 0.3138, F1: 0.6923

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.65893 | val 1.17926
  Epoch 016 - train 0.64797 | val 1.37947
  Classification -> best τ=0.370 (val F1=0.2086)
  Directional -> Accuracy: 0.5467, MCC: 0.0565, F1: 0.6458

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.62851 | val 0.76858
  Epoch 020 - train 0.52676 | val 0.74777
  Classification -> best τ=0.580 (val F1=0.4946)
  Directional -> Accuracy: 0.4902, MCC: -0.0231, F1: 0.5185

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.62030 | val 0.77318
  Epoch 016 - train 0.55605 | val 1.91899
  Classification -> best τ=0.505 (val F1=0.2357)
  Directional -> Accuracy: 0.4681, MCC: -0.1506, F1: 0.6377

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.66194 | val 0.80300
  Epoch 017 - train 0.65219 | val 0.77695
  Classification -> best τ=0.515 (val F1=0.2322)
  Directional -> Accuracy: 0.6377, MCC: 0.2580, F1: 0.1935

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.75127 | val 0.97093
  Epoch 020 - train 0.53801 | val 0.79481
  Classification -> best τ=0.140 (val F1=0.1214)
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.5902

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.60190 | val 2.52145
  Epoch 016 - train 0.57325 | val 2.35990
  Classification -> best τ=0.485 (val F1=0.2452)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.62184 | val 1.01646
  Epoch 016 - train 0.58180 | val 0.85679
  Classification -> best τ=0.495 (val F1=0.1826)
  Directional -> Accuracy: 0.4571, MCC: 0.0888, F1: 0.6042

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.63195 | val 1.27945
  Epoch 019 - train 0.53758 | val 2.43415
  Classification -> best τ=0.485 (val F1=0.2722)
  Directional -> Accuracy: 0.6200, MCC: 0.2766, F1: 0.3448

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.65927 | val 1.27388
  Epoch 019 - train 0.63572 | val 1.26096
  Classification -> best τ=0.480 (val F1=0.2453)
  Directional -> Accuracy: 0.5517, MCC: 0.1588, F1: 0.2778

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.64198 | val 0.89720
  Epoch 020 - train 0.62961 | val 1.24826
  Epoch 026 - train 0.55025 | val 0.99959
  Classification -> best τ=0.280 (val F1=0.2876)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.65215 | val 0.73081
  Epoch 020 - train 0.65141 | val 0.82695
  Classification -> best τ=0.420 (val F1=0.3706)
  Directional -> Accuracy: 0.5667, MCC: 0.1576, F1: 0.6579

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.63062 | val 1.15552
  Epoch 016 - train 0.57539 | val 2.44780
  Classification -> best τ=0.550 (val F1=0.3169)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.4800

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.64024 | val 0.83547
  Epoch 016 - train 0.63245 | val 0.88232
  Classification -> best τ=0.440 (val F1=0.1474)
  Directional -> Accuracy: 0.5362, MCC: 0.0000, F1: 0.6981

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.68808 | val 1.47475
  Epoch 016 - train 0.61917 | val 2.03658
  Classification -> best τ=0.675 (val F1=0.1342)
  Directional -> Accuracy: 0.3729, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.66147 | val 0.76752
  Epoch 017 - train 0.64288 | val 1.18190
  Classification -> best τ=0.600 (val F1=0.1923)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.67136 | val 1.21044
  Epoch 016 - train 0.63769 | val 2.05388
  Classification -> best τ=0.510 (val F1=0.3075)
  Directional -> Accuracy: 0.5077, MCC: 0.1597, F1: 0.3600

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.66414 | val 0.70833
  Epoch 020 - train 0.57219 | val 1.57715
  Epoch 022 - train 0.64834 | val 1.58472
  Classification -> best τ=0.395 (val F1=0.3150)
  Directional -> Accuracy: 0.6533, MCC: 0.3482, F1: 0.6176

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.60484 | val 0.67407
  Epoch 020 - train 0.53986 | val 0.77991
  Epoch 026 - train 0.50166 | val 0.95671
  Classification -> best τ=0.645 (val F1=0.3137)
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.70078 | val 0.99805
  Epoch 017 - train 0.62690 | val 1.17473
  Classification -> best τ=0.525 (val F1=0.1800)
  Directional -> Accuracy: 0.5152, MCC: 0.0318, F1: 0.5789

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.65565 | val 0.84187
  Epoch 016 - train 0.68150 | val 0.74785
  Classification -> best τ=0.585 (val F1=0.2379)
  Directional -> Accuracy: 0.5862, MCC: 0.1485, F1: 0.6471

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.63041 | val 0.71880
  Epoch 018 - train 0.61121 | val 0.88490
  Classification -> best τ=0.395 (val F1=0.1614)
  Directional -> Accuracy: 0.4769, MCC: 0.0000, F1: 0.6458

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.65028 | val 0.63869
  Epoch 020 - train 0.57364 | val 0.73818
  Epoch 021 - train 0.55863 | val 0.78751
  Classification -> best τ=0.300 (val F1=0.4352)
  Directional -> Accuracy: 0.5357, MCC: 0.1376, F1: 0.4348

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.70245 | val 0.93942
  Epoch 016 - train 0.66630 | val 1.22556
  Classification -> best τ=0.515 (val F1=0.2935)
  Directional -> Accuracy: 0.4565, MCC: 0.1307, F1: 0.6154

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.67960 | val 0.75045
  Epoch 020 - train 0.66035 | val 0.81111
  Epoch 023 - train 0.59950 | val 0.70753
  Classification -> best τ=0.565 (val F1=0.3043)
  Directional -> Accuracy: 0.4524, MCC: -0.0829, F1: 0.4651

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.60688 | val 0.81399
  Epoch 017 - train 0.60389 | val 0.88598
  Classification -> best τ=0.355 (val F1=0.2550)
  Directional -> Accuracy: 0.5439, MCC: 0.2554, F1: 0.3500

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.63226 | val 0.70486
  Epoch 020 - train 0.58273 | val 0.94058
  Epoch 026 - train 0.42525 | val 1.55173
  Classification -> best τ=0.335 (val F1=0.3278)
  Directional -> Accuracy: 0.5366, MCC: 0.0166, F1: 0.6885

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.67342 | val 0.84467
  Epoch 016 - train 0.61279 | val 0.71659
  Classification -> best τ=0.545 (val F1=0.1959)
  Directional -> Accuracy: 0.5116, MCC: 0.0197, F1: 0.4615

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.60609 | val 0.68175
  Epoch 020 - train 0.56175 | val 0.85972
  Epoch 023 - train 0.54381 | val 0.92397
  Classification -> best τ=0.515 (val F1=0.2282)
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.64049 | val 0.87613
  Epoch 016 - train 0.60168 | val 1.03617
  Classification -> best τ=0.495 (val F1=0.3093)
  Directional -> Accuracy: 0.3800, MCC: -0.3195, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.64680 | val 0.66563
  Epoch 020 - train 0.58542 | val 0.83768
  Epoch 022 - train 0.59258 | val 1.29174
  Classification -> best τ=0.535 (val F1=0.3624)
  Directional -> Accuracy: 0.5616, MCC: 0.1955, F1: 0.4839

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.66305 | val 0.93305
  Epoch 017 - train 0.56062 | val 1.03306
  Classification -> best τ=0.345 (val F1=0.2667)
  Directional -> Accuracy: 0.4865, MCC: -0.0065, F1: 0.6415

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.66286 | val 0.89270
  Epoch 016 - train 0.61004 | val 0.91236
  Classification -> best τ=0.530 (val F1=0.3012)
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.63692 | val 0.71022
  Epoch 017 - train 0.62821 | val 0.68048
  Classification -> best τ=0.410 (val F1=0.3603)
  Directional -> Accuracy: 0.6212, MCC: 0.2211, F1: 0.6753

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.59793 | val 0.99284
  Epoch 017 - train 0.56167 | val 1.21458
  Classification -> best τ=0.395 (val F1=0.3443)
  Directional -> Accuracy: 0.6429, MCC: 0.2821, F1: 0.6809

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.64967 | val 1.00387
  Epoch 017 - train 0.57300 | val 1.06340
  Classification -> best τ=0.430 (val F1=0.2530)
  Directional -> Accuracy: 0.5000, MCC: 0.0051, F1: 0.5000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.60832 | val 1.53286
  Epoch 016 - train 0.56508 | val 1.72090
  Classification -> best τ=0.525 (val F1=0.2800)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.69439 | val 0.73474
  Epoch 020 - train 0.59687 | val 0.68652
  Epoch 026 - train 0.55523 | val 0.64576
  Classification -> best τ=0.405 (val F1=0.4386)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.69278 | val 0.75324
  Epoch 016 - train 0.54674 | val 0.95651
  Classification -> best τ=0.500 (val F1=0.4312)
  Directional -> Accuracy: 0.4865, MCC: -0.0031, F1: 0.4242

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.63739 | val 0.78904
  Epoch 017 - train 0.63270 | val 0.79172
  Classification -> best τ=0.410 (val F1=0.4998)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.65653 | val 0.91127
  Epoch 020 - train 0.57459 | val 1.25665
  Epoch 021 - train 0.58824 | val 1.19225
  Classification -> best τ=0.520 (val F1=0.4141)
  Directional -> Accuracy: 0.5217, MCC: 0.0658, F1: 0.4211

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.60634 | val 0.94982
  Epoch 016 - train 0.57945 | val 1.01043
  Classification -> best τ=0.525 (val F1=0.0577)
  Directional -> Accuracy: 0.5116, MCC: -0.0464, F1: 0.6316

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.70851 | val 0.94353
  Epoch 017 - train 0.59288 | val 0.88362
  Classification -> best τ=0.540 (val F1=0.6292)
  Directional -> Accuracy: 0.5510, MCC: -0.1299, F1: 0.0833

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.65713 | val 0.78013
  Epoch 017 - train 0.64823 | val 1.32626
  Classification -> best τ=0.700 (val F1=0.3977)
  Directional -> Accuracy: 0.5000, MCC: 0.1792, F1: 0.1250

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.65566 | val 0.89101
  Epoch 020 - train 0.58847 | val 1.02715
  Classification -> best τ=0.635 (val F1=0.3886)
  Directional -> Accuracy: 0.5357, MCC: 0.1397, F1: 0.0714

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.63887 | val 0.95255
  Epoch 018 - train 0.61388 | val 1.63327
  Classification -> best τ=0.355 (val F1=0.2365)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.61222 | val 1.89655
  Epoch 017 - train 0.61455 | val 1.44434
  Classification -> best τ=0.545 (val F1=0.2402)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.65619 | val 0.76809

[I 2026-02-25 02:38:11,661] Trial 165 finished with value: 0.28842794546339984 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 0.005101478730423974, 'weight_decay': 0.0005067409269318961, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 0.5791984584354782, 'early_stopping_min_delta': 0.00305584617563645}. Best is trial 164 with value: 0.2973019295845425.

  Epoch 017 - train 0.66609 | val 1.63194
  Classification -> best τ=0.415 (val F1=0.3103)
  Directional -> Accuracy: 0.4754, MCC: -0.0269, F1: 0.5789

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.28842794546339984
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.66672 | val 0.85746
  Epoch 017 - train 0.60448 | val 0.89679
  Classification -> best τ=0.560 (val F1=0.2510)
  Directional -> Accuracy: 0.5395, MCC: 0.0306, F1: 0.3396

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.64132 | val 0.69071
  Epoch 016 - train 0.59772 | val 0.70568
  Classification -> best τ=0.430 (val F1=0.1307)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.69677 | val 0.69214
  Epoch 020 - train 0.60493 | val 0.78021
  Epoch 023 - train 0.59867 | val 0.72277
  Classification -> best τ=0.625 (val F1=0.3835)
  Directional -> Accuracy: 0.4468, MCC: -0.1039, F1: 0.0714

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.66557 | val 1.43471
  Epoch 016 - train 0.63553 | val 1.43146
  Classification -> best τ=0.365 (val F1=0.1964)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.61744 | val 0.77184
  Epoch 017 - train 0.55741 | val 0.74044
  Classification -> best τ=0.555 (val F1=0.4985)
  Directional -> Accuracy: 0.5882, MCC: 0.2677, F1: 0.4324

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.59343 | val 0.70499
  Epoch 020 - train 0.52840 | val 0.91416
  Epoch 023 - train 0.49305 | val 1.26145
  Classification -> best τ=0.495 (val F1=0.3873)
  Directional -> Accuracy: 0.5319, MCC: 0.0852, F1: 0.6207

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.67241 | val 0.90319
  Epoch 016 - train 0.65154 | val 0.83907
  Classification -> best τ=0.375 (val F1=0.2280)
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.63315 | val 0.63175
  Epoch 020 - train 0.51947 | val 0.86987
  Epoch 030 - train 0.48736 | val 1.35249
  Classification -> best τ=0.110 (val F1=0.3684)
  Directional -> Accuracy: 0.4884, MCC: -0.0352, F1: 0.4211

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.63529 | val 1.49696
  Epoch 016 - train 0.59453 | val 2.54653
  Classification -> best τ=0.500 (val F1=0.4249)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.62443 | val 0.70404
  Epoch 017 - train 0.55465 | val 0.84967
  Classification -> best τ=0.435 (val F1=0.2576)
  Directional -> Accuracy: 0.5000, MCC: 0.0166, F1: 0.4928

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.63112 | val 1.55844
  Epoch 020 - train 0.51372 | val 2.04866
  Classification -> best τ=0.670 (val F1=0.4082)
  Directional -> Accuracy: 0.5600, MCC: 0.1000, F1: 0.4500

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.62976 | val 1.33642
  Epoch 016 - train 0.57842 | val 1.42742
  Classification -> best τ=0.470 (val F1=0.2592)
  Directional -> Accuracy: 0.6034, MCC: 0.2315, F1: 0.4889

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.61945 | val 1.21291
  Epoch 020 - train 0.56249 | val 1.69920
  Classification -> best τ=0.470 (val F1=0.1686)
  Directional -> Accuracy: 0.4048, MCC: -0.2460, F1: 0.5763

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.67138 | val 0.67842
  Epoch 020 - train 0.63293 | val 0.97380
  Epoch 024 - train 0.61474 | val 0.84110
  Classification -> best τ=0.660 (val F1=0.3289)
  Directional -> Accuracy: 0.5500, MCC: 0.1048, F1: 0.4706

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.59442 | val 1.77852
  Epoch 018 - train 0.56572 | val 1.24552
  Classification -> best τ=0.605 (val F1=0.1512)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.64095 | val 0.82530
  Epoch 016 - train 0.57220 | val 0.91773
  Classification -> best τ=0.460 (val F1=0.2132)
  Directional -> Accuracy: 0.5652, MCC: 0.1141, F1: 0.6341

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.68519 | val 1.78150
  Epoch 016 - train 0.62583 | val 2.10050
  Classification -> best τ=0.690 (val F1=0.0757)
  Directional -> Accuracy: 0.3729, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.67581 | val 1.73194
  Epoch 016 - train 0.62772 | val 1.96875
  Classification -> best τ=0.485 (val F1=0.0784)
  Directional -> Accuracy: 0.5867, MCC: -0.0949, F1: 0.7395

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.62871 | val 1.79128
  Epoch 019 - train 0.60319 | val 2.16533
  Classification -> best τ=0.470 (val F1=0.2289)
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.63181 | val 0.67067
  Epoch 020 - train 0.59561 | val 1.20914
  Epoch 028 - train 0.54588 | val 1.51238
  Classification -> best τ=0.660 (val F1=0.2935)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.61054 | val 0.83542
  Epoch 020 - train 0.54507 | val 0.71374
  Epoch 022 - train 0.51616 | val 0.73393
  Classification -> best τ=0.355 (val F1=0.2845)
  Directional -> Accuracy: 0.5319, MCC: 0.2722, F1: 0.4211

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.67614 | val 0.88085
  Epoch 016 - train 0.62243 | val 1.06618
  Classification -> best τ=0.510 (val F1=0.2049)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.1538

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.67735 | val 0.85227
  Epoch 016 - train 0.62196 | val 0.81406
  Classification -> best τ=0.565 (val F1=0.2653)
  Directional -> Accuracy: 0.5172, MCC: 0.0882, F1: 0.4615

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.66841 | val 0.95281
  Epoch 017 - train 0.63933 | val 0.97033
  Classification -> best τ=0.430 (val F1=0.2083)
  Directional -> Accuracy: 0.5385, MCC: 0.1091, F1: 0.6154

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.60187 | val 0.71299
  Epoch 020 - train 0.59533 | val 0.70403
  Epoch 027 - train 0.52912 | val 0.91200
  Classification -> best τ=0.600 (val F1=0.4388)
  Directional -> Accuracy: 0.5179, MCC: 0.1373, F1: 0.3415

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.62823 | val 0.83637
  Epoch 016 - train 0.55363 | val 1.10601
  Classification -> best τ=0.560 (val F1=0.1981)
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.60176 | val 1.02353
  Epoch 019 - train 0.61404 | val 0.95338
  Classification -> best τ=0.430 (val F1=0.2107)
  Directional -> Accuracy: 0.5000, MCC: -0.1291, F1: 0.6441

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.66482 | val 0.70420
  Epoch 018 - train 0.59127 | val 1.05386
  Classification -> best τ=0.430 (val F1=0.2648)
  Directional -> Accuracy: 0.5263, MCC: 0.2741, F1: 0.2703

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.66421 | val 1.55367
  Epoch 016 - train 0.53978 | val 2.15521
  Classification -> best τ=0.450 (val F1=0.0707)
  Directional -> Accuracy: 0.5366, MCC: 0.0472, F1: 0.6275

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.61258 | val 0.69824
  Epoch 019 - train 0.57473 | val 1.48983
  Classification -> best τ=0.555 (val F1=0.1959)
  Directional -> Accuracy: 0.5116, MCC: 0.0288, F1: 0.5532

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.68394 | val 0.79463
  Epoch 020 - train 0.57191 | val 1.01675
  Classification -> best τ=0.515 (val F1=0.1551)
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.61872 | val 0.85215
  Epoch 016 - train 0.59112 | val 1.07297
  Classification -> best τ=0.485 (val F1=0.2498)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.62351 | val 0.81529
  Epoch 020 - train 0.60012 | val 2.18998
  Classification -> best τ=0.350 (val F1=0.3192)
  Directional -> Accuracy: 0.5479, MCC: 0.1382, F1: 0.5075

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.61732 | val 0.98913
  Epoch 018 - train 0.52189 | val 1.64518
  Classification -> best τ=0.410 (val F1=0.2887)
  Directional -> Accuracy: 0.5946, MCC: 0.2271, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.67237 | val 0.95967
  Epoch 017 - train 0.63173 | val 0.94362
  Classification -> best τ=0.550 (val F1=0.3278)
  Directional -> Accuracy: 0.5682, MCC: 0.1412, F1: 0.5778

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.63057 | val 0.70496
  Epoch 020 - train 0.58793 | val 0.74327
  Epoch 027 - train 0.56787 | val 0.89341
  Classification -> best τ=0.365 (val F1=0.3787)
  Directional -> Accuracy: 0.4697, MCC: 0.1299, F1: 0.1860

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.57554 | val 1.27221
  Epoch 016 - train 0.56048 | val 1.42169
  Classification -> best τ=0.495 (val F1=0.2568)
  Directional -> Accuracy: 0.5238, MCC: 0.0853, F1: 0.3750

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.65755 | val 1.00881
  Epoch 016 - train 0.61554 | val 1.13933
  Classification -> best τ=0.375 (val F1=0.2637)
  Directional -> Accuracy: 0.5000, MCC: 0.1192, F1: 0.6410

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.57415 | val 2.36795
  Epoch 016 - train 0.51267 | val 2.80946
  Classification -> best τ=0.555 (val F1=0.2441)
  Directional -> Accuracy: 0.6304, MCC: 0.1564, F1: 0.7463

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.63183 | val 0.65324
  Epoch 020 - train 0.58093 | val 0.67044
  Epoch 022 - train 0.55012 | val 0.73594
  Classification -> best τ=0.390 (val F1=0.4141)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.62292 | val 0.86171
  Epoch 017 - train 0.61171 | val 0.88011
  Classification -> best τ=0.510 (val F1=0.0585)
  Directional -> Accuracy: 0.4324, MCC: -0.1378, F1: 0.4615

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.63566 | val 0.81200
  Epoch 018 - train 0.59884 | val 1.06374
  Classification -> best τ=0.540 (val F1=0.2652)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.67505 | val 0.74083
  Epoch 017 - train 0.63565 | val 1.00953
  Classification -> best τ=0.420 (val F1=0.3871)
  Directional -> Accuracy: 0.4783, MCC: -0.0229, F1: 0.2941

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.61799 | val 1.02834
  Epoch 016 - train 0.57284 | val 1.33110
  Classification -> best τ=0.485 (val F1=0.2282)
  Directional -> Accuracy: 0.6279, MCC: 0.2329, F1: 0.7241

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.62364 | val 0.87555
  Epoch 020 - train 0.60801 | val 0.95576
  Epoch 029 - train 0.45228 | val 1.06022
  Classification -> best τ=0.540 (val F1=0.5261)
  Directional -> Accuracy: 0.3673, MCC: -0.1814, F1: 0.5373

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.66066 | val 1.40423
  Epoch 016 - train 0.65447 | val 1.82202
  Classification -> best τ=0.525 (val F1=0.1216)
  Directional -> Accuracy: 0.4643, MCC: -0.0248, F1: 0.1667

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.70154 | val 0.91746
  Epoch 017 - train 0.63818 | val 1.01843
  Classification -> best τ=0.485 (val F1=0.2874)
  Directional -> Accuracy: 0.5536, MCC: 0.1032, F1: 0.5098

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.63610 | val 1.23604
  Epoch 016 - train 0.63188 | val 1.13754
  Classification -> best τ=0.385 (val F1=0.3202)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.66205 | val 2.70716
  Epoch 017 - train 0.61001 | val 2.56672
  Classification -> best τ=0.410 (val F1=0.1001)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.65180 | val 0.88446
  Epoch 020 - train 0.59437 | val 0.95910
  Epoch 021 - train 0.58957 | val 1.04223

[I 2026-02-25 02:40:27,345] Trial 166 finished with value: 0.2630275004840029 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 0.0030343926243829433, 'weight_decay': 0.0007366644324698555, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 0.7159619831268584, 'early_stopping_min_delta': 0.0030751297561181852}. Best is trial 164 with value: 0.2973019295845425.

  Classification -> best τ=0.375 (val F1=0.2847)
  Directional -> Accuracy: 0.4918, MCC: 0.0451, F1: 0.6353

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2630275004840029
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.61719 | val 0.93711
  Epoch 017 - train 0.60862 | val 0.90263
  Classification -> best τ=0.515 (val F1=0.2082)
  Directional -> Accuracy: 0.5132, MCC: 0.0014, F1: 0.4127

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.63491 | val 0.74518
  Epoch 018 - train 0.53682 | val 0.80215
  Classification -> best τ=0.530 (val F1=0.1236)
  Directional -> Accuracy: 0.6000, MCC: 0.1419, F1: 0.7000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.64576 | val 0.69586
  Epoch 017 - train 0.61394 | val 0.74362
  Classification -> best τ=0.565 (val F1=0.3171)
  Directional -> Accuracy: 0.4894, MCC: 0.1383, F1: 0.0769

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.64047 | val 1.09076
  Epoch 016 - train 0.61416 | val 1.06903
  Classification -> best τ=0.350 (val F1=0.2782)
  Directional -> Accuracy: 0.5733, MCC: 0.1350, F1: 0.6190

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.56198 | val 0.74154
  Epoch 019 - train 0.48600 | val 0.84213
  Classification -> best τ=0.550 (val F1=0.4513)
  Directional -> Accuracy: 0.5294, MCC: 0.0172, F1: 0.6757

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.54986 | val 1.08192
  Epoch 018 - train 0.47882 | val 0.81090
  Classification -> best τ=0.505 (val F1=0.3095)
  Directional -> Accuracy: 0.5106, MCC: 0.0065, F1: 0.1481

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.64278 | val 0.74148
  Epoch 016 - train 0.60045 | val 0.98276
  Classification -> best τ=0.415 (val F1=0.0947)
  Directional -> Accuracy: 0.4493, MCC: 0.1762, F1: 0.5957

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.56607 | val 1.30560
  Epoch 016 - train 0.58073 | val 1.28423
  Classification -> best τ=0.460 (val F1=0.3295)
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.60283 | val 0.79799
  Epoch 019 - train 0.51082 | val 1.17814
  Classification -> best τ=0.360 (val F1=0.2820)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.58991 | val 0.83816
  Epoch 018 - train 0.52800 | val 0.91458
  Classification -> best τ=0.465 (val F1=0.2005)
  Directional -> Accuracy: 0.5429, MCC: 0.1179, F1: 0.5556

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.60910 | val 2.16269
  Epoch 017 - train 0.53169 | val 3.00565
  Classification -> best τ=0.615 (val F1=0.2151)
  Directional -> Accuracy: 0.5800, MCC: 0.1394, F1: 0.4324

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.60490 | val 1.58028
  Epoch 017 - train 0.52914 | val 1.87362
  Classification -> best τ=0.375 (val F1=0.2630)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.55678 | val 0.76197
  Epoch 016 - train 0.56786 | val 1.03117
  Classification -> best τ=0.535 (val F1=0.1883)
  Directional -> Accuracy: 0.6190, MCC: 0.2567, F1: 0.3333

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.64595 | val 1.00940
  Epoch 016 - train 0.61877 | val 1.10476
  Classification -> best τ=0.550 (val F1=0.3268)
  Directional -> Accuracy: 0.5333, MCC: 0.0680, F1: 0.5758

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.58673 | val 0.96887
  Epoch 016 - train 0.55989 | val 1.72318
  Classification -> best τ=0.605 (val F1=0.2160)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.61112 | val 0.97941
  Epoch 016 - train 0.55534 | val 0.95508
  Classification -> best τ=0.520 (val F1=0.2224)
  Directional -> Accuracy: 0.5797, MCC: 0.1609, F1: 0.5915

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.64542 | val 1.46222
  Epoch 016 - train 0.55736 | val 1.65771
  Classification -> best τ=0.630 (val F1=0.1842)
  Directional -> Accuracy: 0.3729, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.63235 | val 1.31379
  Epoch 016 - train 0.62547 | val 2.36232
  Classification -> best τ=0.535 (val F1=0.1923)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.61629 | val 1.35102
  Epoch 016 - train 0.57274 | val 1.91683
  Classification -> best τ=0.580 (val F1=0.2234)
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.62369 | val 0.67633
  Epoch 020 - train 0.56926 | val 0.83516
  Epoch 027 - train 0.50842 | val 0.71425
  Classification -> best τ=0.390 (val F1=0.3216)
  Directional -> Accuracy: 0.4533, MCC: -0.0276, F1: 0.1277

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.58454 | val 0.92888
  Epoch 016 - train 0.54256 | val 0.78735
  Classification -> best τ=0.455 (val F1=0.2807)
  Directional -> Accuracy: 0.5532, MCC: 0.2606, F1: 0.4878

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.64794 | val 0.81960
  Epoch 016 - train 0.58700 | val 0.96374
  Classification -> best τ=0.540 (val F1=0.1427)
  Directional -> Accuracy: 0.5455, MCC: 0.0954, F1: 0.4643

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.65081 | val 0.77274
  Epoch 016 - train 0.63587 | val 0.81403
  Classification -> best τ=0.515 (val F1=0.2653)
  Directional -> Accuracy: 0.5000, MCC: 0.1008, F1: 0.3556

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.62788 | val 0.69743
  Epoch 020 - train 0.56497 | val 1.34225
  Epoch 030 - train 0.46211 | val 0.79285
  Epoch 040 - train 0.43430 | val 1.09142
  Epoch 042 - train 0.42840 | val 1.10866
  Classification -> best τ=0.390 (val F1=0.3930)
  Directional -> Accuracy: 0.4615, MCC: -0.1309, F1: 0.6316

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.62036 | val 0.62924
  Epoch 020 - train 0.56134 | val 0.79317
  Epoch 025 - train 0.53356 | val 0.79358
  Classification -> best τ=0.630 (val F1=0.4330)
  Directional -> Accuracy: 0.5357, MCC: 0.1728, F1: 0.3810

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.55025 | val 0.77591
  Epoch 016 - train 0.54531 | val 1.10747
  Classification -> best τ=0.515 (val F1=0.2241)
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.63713 | val 0.68467
  Epoch 020 - train 0.57309 | val 0.94912
  Epoch 027 - train 0.55819 | val 0.71112
  Classification -> best τ=0.615 (val F1=0.1936)
  Directional -> Accuracy: 0.4762, MCC: 0.0323, F1: 0.3529

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.60152 | val 1.21157
  Epoch 018 - train 0.54915 | val 1.55816
  Classification -> best τ=0.460 (val F1=0.2359)
  Directional -> Accuracy: 0.5789, MCC: 0.1613, F1: 0.6000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.66817 | val 1.54798
  Epoch 016 - train 0.55678 | val 1.20942
  Classification -> best τ=0.460 (val F1=0.2365)
  Directional -> Accuracy: 0.5854, MCC: 0.1595, F1: 0.6909

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.64661 | val 0.72680
  Epoch 016 - train 0.60741 | val 0.76147
  Classification -> best τ=0.490 (val F1=0.2814)
  Directional -> Accuracy: 0.5116, MCC: 0.0051, F1: 0.0870

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.63683 | val 0.71379
  Epoch 020 - train 0.53399 | val 0.91787
  Epoch 021 - train 0.53843 | val 0.85880
  Classification -> best τ=0.480 (val F1=0.2517)
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.58410 | val 1.12142
  Epoch 016 - train 0.50271 | val 1.15642
  Classification -> best τ=0.475 (val F1=0.2253)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.64116 | val 0.81231
  Epoch 017 - train 0.54921 | val 0.87520
  Classification -> best τ=0.385 (val F1=0.3353)
  Directional -> Accuracy: 0.5753, MCC: 0.1768, F1: 0.5634

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.64425 | val 0.92843
  Epoch 016 - train 0.58236 | val 1.05985
  Classification -> best τ=0.460 (val F1=0.5590)
  Directional -> Accuracy: 0.5405, MCC: 0.1172, F1: 0.6383

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.61328 | val 0.88115
  Epoch 016 - train 0.53291 | val 1.16988
  Classification -> best τ=0.530 (val F1=0.3121)
  Directional -> Accuracy: 0.5909, MCC: 0.1767, F1: 0.5000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.59259 | val 0.81724
  Epoch 016 - train 0.57628 | val 0.81195
  Classification -> best τ=0.385 (val F1=0.3525)
  Directional -> Accuracy: 0.5152, MCC: 0.2249, F1: 0.3043

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.57823 | val 1.18627
  Epoch 016 - train 0.47131 | val 1.86287
  Classification -> best τ=0.515 (val F1=0.2740)
  Directional -> Accuracy: 0.4762, MCC: -0.0155, F1: 0.1538

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.60447 | val 1.24172
  Epoch 017 - train 0.55835 | val 1.80245
  Classification -> best τ=0.405 (val F1=0.2203)
  Directional -> Accuracy: 0.5000, MCC: 0.0731, F1: 0.6216

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.55711 | val 1.50452
  Epoch 018 - train 0.48593 | val 2.02475
  Classification -> best τ=0.570 (val F1=0.2832)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.61702 | val 0.62353
  Epoch 020 - train 0.55296 | val 0.59129
  Epoch 030 - train 0.47428 | val 0.61214
  Epoch 040 - train 0.41817 | val 0.69284
  Epoch 043 - train 0.36708 | val 0.61104
  Classification -> best τ=0.305 (val F1=0.5247)
  Directional -> Accuracy: 0.3469, MCC: -0.1894, F1: 0.5152

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.60650 | val 0.77315
  Epoch 016 - train 0.55101 | val 0.88139
  Classification -> best τ=0.455 (val F1=0.0612)
  Directional -> Accuracy: 0.5135, MCC: 0.0031, F1: 0.5909

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.64350 | val 0.94050
  Epoch 017 - train 0.56385 | val 1.64853
  Classification -> best τ=0.370 (val F1=0.3597)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.67046 | val 0.72826
  Epoch 016 - train 0.60158 | val 1.05147
  Classification -> best τ=0.440 (val F1=0.2058)
  Directional -> Accuracy: 0.5435, MCC: 0.1557, F1: 0.6957

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.60300 | val 0.99246
  Epoch 016 - train 0.53842 | val 1.19846
  Classification -> best τ=0.635 (val F1=0.2530)
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.63042 | val 0.72429
  Epoch 019 - train 0.54735 | val 0.76385
  Classification -> best τ=0.520 (val F1=0.6590)
  Directional -> Accuracy: 0.3673, MCC: -0.1462, F1: 0.5231

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.62957 | val 1.23546
  Epoch 016 - train 0.64295 | val 2.18526
  Classification -> best τ=0.425 (val F1=0.2999)
  Directional -> Accuracy: 0.5893, MCC: 0.2397, F1: 0.4889

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.63578 | val 1.07573
  Epoch 016 - train 0.59476 | val 1.27479
  Classification -> best τ=0.635 (val F1=0.3957)
  Directional -> Accuracy: 0.5179, MCC: 0.0565, F1: 0.5970

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.61183 | val 1.68027
  Epoch 016 - train 0.57828 | val 1.58408
  Classification -> best τ=0.480 (val F1=0.1626)
  Directional -> Accuracy: 0.5926, MCC: 0.1816, F1: 0.6333

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.63567 | val 1.76286
  Epoch 016 - train 0.57202 | val 1.51097
  Classification -> best τ=0.570 (val F1=0.1168)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.64245 | val 0.84986

[I 2026-02-25 02:41:13,184] Trial 167 finished with value: 0.27397843951497053 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 0.004547910665052387, 'weight_decay': 0.0006105651882211385, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 0.5691205705444442, 'early_stopping_min_delta': 0.002562183486995526}. Best is trial 164 with value: 0.2973019295845425.

  Epoch 017 - train 0.57930 | val 1.11900
  Classification -> best τ=0.480 (val F1=0.2131)
  Directional -> Accuracy: 0.4590, MCC: -0.0997, F1: 0.3529

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.27397843951497053
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.63573 | val 1.00246
  Epoch 020 - train 0.59169 | val 0.73392
  Classification -> best τ=0.565 (val F1=0.2510)
  Directional -> Accuracy: 0.6053, MCC: 0.1906, F1: 0.5161

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.63869 | val 0.91175
  Epoch 016 - train 0.60709 | val 0.79968
  Classification -> best τ=0.465 (val F1=0.1700)
  Directional -> Accuracy: 0.5778, MCC: 0.2769, F1: 0.4865

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.68876 | val 0.71466
  Epoch 020 - train 0.59858 | val 0.73348
  Classification -> best τ=0.450 (val F1=0.3262)
  Directional -> Accuracy: 0.5319, MCC: 0.0245, F1: 0.6667

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.66782 | val 1.68144
  Epoch 016 - train 0.63843 | val 1.48590
  Classification -> best τ=0.400 (val F1=0.2125)
  Directional -> Accuracy: 0.5200, MCC: -0.0420, F1: 0.6604

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.60807 | val 0.73175
  Epoch 017 - train 0.54414 | val 0.85560
  Classification -> best τ=0.580 (val F1=0.3795)
  Directional -> Accuracy: 0.5490, MCC: 0.1398, F1: 0.4390

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.59829 | val 0.71534
  Epoch 020 - train 0.49936 | val 2.57385
  Epoch 024 - train 0.43528 | val 1.50571
  Classification -> best τ=0.565 (val F1=0.2335)
  Directional -> Accuracy: 0.5745, MCC: 0.1515, F1: 0.4737

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.66132 | val 0.82585
  Epoch 020 - train 0.60674 | val 0.91688
  Classification -> best τ=0.430 (val F1=0.2584)
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.65391 | val 1.03574
  Epoch 020 - train 0.56551 | val 2.37187
  Epoch 029 - train 0.42851 | val 2.31035
  Classification -> best τ=0.105 (val F1=0.2192)
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.5902

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.63661 | val 0.81977
  Epoch 020 - train 0.52876 | val 1.57060
  Epoch 021 - train 0.55699 | val 1.56519
  Classification -> best τ=0.440 (val F1=0.2891)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.62929 | val 0.79206
  Epoch 017 - train 0.55389 | val 0.77428
  Classification -> best τ=0.440 (val F1=0.2220)
  Directional -> Accuracy: 0.4429, MCC: -0.0402, F1: 0.5412

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.62402 | val 1.71923
  Epoch 018 - train 0.53606 | val 2.88699
  Classification -> best τ=0.595 (val F1=0.3118)
  Directional -> Accuracy: 0.6000, MCC: 0.2059, F1: 0.3333

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.63276 | val 1.08348
  Epoch 017 - train 0.58301 | val 1.95099
  Classification -> best τ=0.485 (val F1=0.3339)
  Directional -> Accuracy: 0.5517, MCC: 0.1319, F1: 0.3500

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.68696 | val 1.19060
  Epoch 018 - train 0.55873 | val 1.65406
  Classification -> best τ=0.415 (val F1=0.2235)
  Directional -> Accuracy: 0.4762, MCC: 0.0214, F1: 0.5926

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.65795 | val 1.07793
  Epoch 016 - train 0.63697 | val 1.30039
  Classification -> best τ=0.480 (val F1=0.2658)
  Directional -> Accuracy: 0.5167, MCC: 0.0343, F1: 0.5672

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.61714 | val 4.00718
  Epoch 017 - train 0.53649 | val 2.73733
  Classification -> best τ=0.520 (val F1=0.2902)
  Directional -> Accuracy: 0.4615, MCC: -0.1581, F1: 0.1765

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.61722 | val 1.02523
  Epoch 016 - train 0.61311 | val 0.90624
  Classification -> best τ=0.535 (val F1=0.2655)
  Directional -> Accuracy: 0.5217, MCC: 0.1079, F1: 0.3529

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.62709 | val 2.32205
  Epoch 016 - train 0.62734 | val 2.43136
  Classification -> best τ=0.415 (val F1=0.1905)
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.64627 | val 1.16332
  Epoch 016 - train 0.62183 | val 1.15297
  Classification -> best τ=0.500 (val F1=0.1846)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.63748 | val 1.70221
  Epoch 016 - train 0.63567 | val 1.85969
  Classification -> best τ=0.470 (val F1=0.3539)
  Directional -> Accuracy: 0.5077, MCC: 0.0077, F1: 0.5556

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.64036 | val 0.81922
  Epoch 019 - train 0.57938 | val 1.21142
  Classification -> best τ=0.590 (val F1=0.2938)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.63909 | val 0.68793
  Epoch 019 - train 0.53261 | val 0.89448
  Classification -> best τ=0.485 (val F1=0.3278)
  Directional -> Accuracy: 0.4255, MCC: -0.1381, F1: 0.4706

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.64138 | val 0.93235
  Epoch 016 - train 0.60847 | val 1.03308
  Classification -> best τ=0.545 (val F1=0.1318)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.67600 | val 0.74347
  Epoch 017 - train 0.61265 | val 0.78556
  Classification -> best τ=0.520 (val F1=0.3286)
  Directional -> Accuracy: 0.4828, MCC: 0.0658, F1: 0.3182

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.72285 | val 0.70932
  Epoch 017 - train 0.61200 | val 0.83106
  Classification -> best τ=0.430 (val F1=0.1679)
  Directional -> Accuracy: 0.4769, MCC: 0.0000, F1: 0.6458

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.61160 | val 0.69640
  Epoch 020 - train 0.57162 | val 0.75223
  Epoch 023 - train 0.55821 | val 0.67735
  Classification -> best τ=0.635 (val F1=0.3807)
  Directional -> Accuracy: 0.4643, MCC: 0.1211, F1: 0.0625

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.62168 | val 0.86030
  Epoch 016 - train 0.56495 | val 1.02598
  Classification -> best τ=0.515 (val F1=0.2035)
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.66932 | val 0.68589
  Epoch 020 - train 0.60883 | val 0.95281
  Epoch 030 - train 0.58496 | val 0.85336
  Epoch 031 - train 0.56302 | val 1.16144
  Classification -> best τ=0.385 (val F1=0.2582)
  Directional -> Accuracy: 0.5000, MCC: -0.0595, F1: 0.6038

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.63164 | val 1.23719
  Epoch 016 - train 0.59211 | val 0.91402
  Classification -> best τ=0.460 (val F1=0.0929)
  Directional -> Accuracy: 0.5614, MCC: 0.0981, F1: 0.6269

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.61761 | val 1.65579
  Epoch 016 - train 0.60791 | val 0.93616
  Classification -> best τ=0.485 (val F1=0.3518)
  Directional -> Accuracy: 0.6098, MCC: 0.2283, F1: 0.7143

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.62253 | val 0.85895
  Epoch 016 - train 0.61494 | val 0.79653
  Classification -> best τ=0.500 (val F1=0.1649)
  Directional -> Accuracy: 0.5581, MCC: 0.1182, F1: 0.4242

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.65208 | val 1.24614
  Epoch 020 - train 0.53742 | val 0.82688
  Epoch 021 - train 0.57920 | val 0.82959
  Classification -> best τ=0.335 (val F1=0.2517)
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.57735 | val 0.83589
  Epoch 016 - train 0.59159 | val 1.02286
  Classification -> best τ=0.455 (val F1=0.1216)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.64294 | val 0.93084
  Epoch 019 - train 0.56252 | val 1.05300
  Classification -> best τ=0.330 (val F1=0.3391)
  Directional -> Accuracy: 0.5616, MCC: 0.1446, F1: 0.5556

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.63189 | val 0.95374
  Epoch 016 - train 0.66438 | val 1.56763
  Classification -> best τ=0.410 (val F1=0.2390)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.64388 | val 0.90335
  Epoch 016 - train 0.61931 | val 1.33550
  Classification -> best τ=0.585 (val F1=0.2031)
  Directional -> Accuracy: 0.6591, MCC: 0.3240, F1: 0.6667

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.62847 | val 0.68559
  Epoch 017 - train 0.59434 | val 0.74367
  Classification -> best τ=0.435 (val F1=0.3855)
  Directional -> Accuracy: 0.6667, MCC: 0.3246, F1: 0.7027

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.60597 | val 1.20476
  Epoch 016 - train 0.52678 | val 1.45399
  Classification -> best τ=0.530 (val F1=0.1650)
  Directional -> Accuracy: 0.6667, MCC: 0.3553, F1: 0.6316

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.63744 | val 1.23225
  Epoch 016 - train 0.59127 | val 1.29064
  Classification -> best τ=0.455 (val F1=0.2868)
  Directional -> Accuracy: 0.4821, MCC: -0.0135, F1: 0.5397

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.64397 | val 1.58290
  Epoch 016 - train 0.48134 | val 2.40978
  Classification -> best τ=0.495 (val F1=0.3397)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.61940 | val 0.66180
  Epoch 020 - train 0.57881 | val 0.65314
  Epoch 030 - train 0.54222 | val 0.61016
  Epoch 040 - train 0.45276 | val 0.75331
  Epoch 045 - train 0.43581 | val 0.64702
  Classification -> best τ=0.290 (val F1=0.6670)
  Directional -> Accuracy: 0.3469, MCC: -0.1894, F1: 0.5152

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.64667 | val 0.71655
  Epoch 016 - train 0.56806 | val 0.83714
  Classification -> best τ=0.510 (val F1=0.0944)
  Directional -> Accuracy: 0.4595, MCC: -0.0710, F1: 0.4444

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.60021 | val 1.00989
  Epoch 016 - train 0.60521 | val 0.95008
  Classification -> best τ=0.500 (val F1=0.2509)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.62828 | val 0.96300
  Epoch 020 - train 0.53622 | val 1.27311
  Epoch 030 - train 0.51986 | val 0.78729
  Classification -> best τ=0.490 (val F1=0.4141)
  Directional -> Accuracy: 0.4783, MCC: -0.0259, F1: 0.3333

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.61451 | val 0.95805
  Epoch 016 - train 0.57991 | val 1.11611
  Classification -> best τ=0.555 (val F1=0.0610)
  Directional -> Accuracy: 0.6279, MCC: 0.2456, F1: 0.6667

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.60250 | val 0.76876
  Epoch 020 - train 0.52108 | val 1.11027
  Epoch 030 - train 0.49299 | val 0.71765
  Epoch 032 - train 0.50899 | val 1.05485
  Classification -> best τ=0.470 (val F1=0.5261)
  Directional -> Accuracy: 0.3469, MCC: -0.2592, F1: 0.5152

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.64525 | val 2.23041
  Epoch 018 - train 0.60049 | val 2.45488
  Classification -> best τ=0.625 (val F1=0.2357)
  Directional -> Accuracy: 0.5179, MCC: 0.1149, F1: 0.3077

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.62723 | val 1.13756
  Epoch 016 - train 0.59162 | val 1.35402
  Classification -> best τ=0.540 (val F1=0.4103)
  Directional -> Accuracy: 0.5357, MCC: 0.1073, F1: 0.6286

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.64349 | val 2.16987
  Epoch 017 - train 0.60497 | val 1.57213
  Classification -> best τ=0.350 (val F1=0.2908)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.61266 | val 1.11422
  Epoch 017 - train 0.65222 | val 1.84408
  Classification -> best τ=0.460 (val F1=0.1667)
  Directional -> Accuracy: 0.5357, MCC: 0.1397, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.60965 | val 0.81618
  Epoch 020 - train 0.58916 | val 0.80391

[I 2026-02-25 02:43:28,661] Trial 168 finished with value: 0.2679021202626558 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 0.002323069339049486, 'weight_decay': 0.0005869575262392469, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 0.677533844172941, 'early_stopping_min_delta': 0.0028630950538020726}. Best is trial 164 with value: 0.2973019295845425.

  Epoch 023 - train 0.55899 | val 1.13136
  Classification -> best τ=0.580 (val F1=0.2639)
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2679021202626558
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.61776 | val 1.30027
  Epoch 016 - train 0.59767 | val 0.91738
  Classification -> best τ=0.470 (val F1=0.2036)
  Directional -> Accuracy: 0.5658, MCC: 0.1104, F1: 0.4762

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.62865 | val 0.78358
  Epoch 020 - train 0.54203 | val 0.90401
  Epoch 021 - train 0.59854 | val 0.73075
  Classification -> best τ=0.415 (val F1=0.0553)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.66785 | val 0.69037
  Epoch 020 - train 0.56447 | val 0.99529
  Epoch 022 - train 0.55842 | val 1.11408
  Classification -> best τ=0.630 (val F1=0.3537)
  Directional -> Accuracy: 0.4894, MCC: 0.1383, F1: 0.0769

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.62205 | val 1.94455
  Epoch 016 - train 0.64686 | val 2.21479
  Classification -> best τ=0.375 (val F1=0.1511)
  Directional -> Accuracy: 0.5600, MCC: 0.1101, F1: 0.6024

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.59655 | val 0.80736
  Epoch 018 - train 0.52227 | val 0.83679
  Classification -> best τ=0.490 (val F1=0.4513)
  Directional -> Accuracy: 0.6667, MCC: 0.3398, F1: 0.7302

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.62232 | val 0.77388
  Epoch 018 - train 0.53038 | val 0.86205
  Classification -> best τ=0.500 (val F1=0.2928)
  Directional -> Accuracy: 0.6596, MCC: 0.3584, F1: 0.7143

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.64441 | val 0.91603
  Epoch 017 - train 0.64904 | val 0.75691
  Classification -> best τ=0.565 (val F1=0.1805)
  Directional -> Accuracy: 0.5797, MCC: 0.0547, F1: 0.2927

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.61132 | val 0.98000
  Epoch 020 - train 0.51226 | val 1.50607
  Epoch 021 - train 0.52152 | val 1.18954
  Classification -> best τ=0.180 (val F1=0.1752)
  Directional -> Accuracy: 0.4186, MCC: -0.2040, F1: 0.2857

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.59016 | val 1.00774
  Epoch 018 - train 0.51154 | val 1.32501
  Classification -> best τ=0.490 (val F1=0.3461)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.62172 | val 0.90398
  Epoch 018 - train 0.51889 | val 1.90405
  Classification -> best τ=0.550 (val F1=0.3186)
  Directional -> Accuracy: 0.4286, MCC: -0.0355, F1: 0.5833

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.54802 | val 1.48564
  Epoch 017 - train 0.54336 | val 1.25845
  Classification -> best τ=0.510 (val F1=0.1809)
  Directional -> Accuracy: 0.5800, MCC: 0.1520, F1: 0.5333

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.58044 | val 1.30969
  Epoch 019 - train 0.55428 | val 1.29995
  Classification -> best τ=0.530 (val F1=0.2654)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.57605 | val 1.06222
  Epoch 016 - train 0.55264 | val 0.83408
  Classification -> best τ=0.415 (val F1=0.1800)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.63261 | val 1.23570
  Epoch 016 - train 0.59178 | val 2.21755
  Classification -> best τ=0.505 (val F1=0.3196)
  Directional -> Accuracy: 0.5167, MCC: 0.0338, F1: 0.5538

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.62819 | val 1.96525
  Epoch 019 - train 0.52513 | val 3.92367
  Classification -> best τ=0.565 (val F1=0.2160)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.61850 | val 0.80698
  Epoch 017 - train 0.56813 | val 0.79709
  Classification -> best τ=0.450 (val F1=0.2708)
  Directional -> Accuracy: 0.6232, MCC: 0.2986, F1: 0.7347

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.65342 | val 1.74346
  Epoch 016 - train 0.61635 | val 2.27127
  Classification -> best τ=0.615 (val F1=0.1291)
  Directional -> Accuracy: 0.3729, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.64509 | val 1.00085
  Epoch 017 - train 0.60429 | val 1.51637
  Classification -> best τ=0.610 (val F1=0.2236)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.64580 | val 1.67661
  Epoch 017 - train 0.59309 | val 2.94797
  Classification -> best τ=0.415 (val F1=0.2752)
  Directional -> Accuracy: 0.4615, MCC: 0.1262, F1: 0.1860

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.62899 | val 0.64280
  Epoch 020 - train 0.56286 | val 0.73497
  Epoch 025 - train 0.51430 | val 0.68770
  Classification -> best τ=0.400 (val F1=0.3514)
  Directional -> Accuracy: 0.6133, MCC: 0.2264, F1: 0.6329

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.60720 | val 0.73013
  Epoch 020 - train 0.48796 | val 0.84847
  Epoch 023 - train 0.50430 | val 0.94814
  Classification -> best τ=0.565 (val F1=0.3055)
  Directional -> Accuracy: 0.4043, MCC: 0.1162, F1: 0.0667

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.64131 | val 0.89640
  Epoch 017 - train 0.63633 | val 0.98475
  Classification -> best τ=0.555 (val F1=0.1950)
  Directional -> Accuracy: 0.5455, MCC: 0.0916, F1: 0.5161

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.61476 | val 0.87588
  Epoch 017 - train 0.58824 | val 0.94728
  Classification -> best τ=0.585 (val F1=0.2864)
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.63839 | val 0.86104
  Epoch 016 - train 0.63094 | val 1.38725
  Classification -> best τ=0.500 (val F1=0.1359)
  Directional -> Accuracy: 0.5231, MCC: 0.0402, F1: 0.4746

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.60791 | val 0.68498
  Epoch 020 - train 0.55417 | val 0.77291
  Epoch 028 - train 0.50563 | val 1.21455
  Classification -> best τ=0.535 (val F1=0.4124)
  Directional -> Accuracy: 0.4821, MCC: 0.0207, F1: 0.3556

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.59654 | val 0.96739
  Epoch 016 - train 0.46691 | val 1.12742
  Classification -> best τ=0.505 (val F1=0.2935)
  Directional -> Accuracy: 0.4783, MCC: -0.0881, F1: 0.3333

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.63889 | val 0.91599
  Epoch 019 - train 0.55199 | val 0.87392
  Classification -> best τ=0.475 (val F1=0.2107)
  Directional -> Accuracy: 0.5714, MCC: 0.0468, F1: 0.7097

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.68034 | val 0.93459
  Epoch 016 - train 0.60450 | val 1.01978
  Classification -> best τ=0.485 (val F1=0.2575)
  Directional -> Accuracy: 0.5965, MCC: 0.1771, F1: 0.6462

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.60533 | val 0.95334
  Epoch 020 - train 0.48472 | val 1.68431
  Classification -> best τ=0.495 (val F1=0.3296)
  Directional -> Accuracy: 0.6098, MCC: 0.2283, F1: 0.7143

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.55427 | val 0.99016
  Epoch 018 - train 0.53011 | val 0.73696
  Classification -> best τ=0.605 (val F1=0.3656)
  Directional -> Accuracy: 0.5116, MCC: 0.0074, F1: 0.1600

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.59285 | val 0.79390
  Epoch 019 - train 0.52720 | val 0.94965
  Classification -> best τ=0.535 (val F1=0.1937)
  Directional -> Accuracy: 0.3721, MCC: -0.2772, F1: 0.4490

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.56327 | val 1.08743
  Epoch 019 - train 0.49160 | val 1.60057
  Classification -> best τ=0.305 (val F1=0.4687)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.62728 | val 0.72427
  Epoch 016 - train 0.62184 | val 0.82803
  Classification -> best τ=0.420 (val F1=0.3570)
  Directional -> Accuracy: 0.5890, MCC: 0.2303, F1: 0.5455

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.65971 | val 0.83393
  Epoch 018 - train 0.53551 | val 1.03938
  Classification -> best τ=0.445 (val F1=0.1992)
  Directional -> Accuracy: 0.5135, MCC: 0.0367, F1: 0.5714

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.69492 | val 0.94970
  Epoch 016 - train 0.54240 | val 1.17759
  Classification -> best τ=0.545 (val F1=0.3103)
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.60166 | val 0.75747
  Epoch 016 - train 0.56749 | val 0.86257
  Classification -> best τ=0.460 (val F1=0.3254)
  Directional -> Accuracy: 0.6061, MCC: 0.1674, F1: 0.7400

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.52682 | val 1.15906
  Epoch 016 - train 0.41863 | val 1.44817
  Classification -> best τ=0.545 (val F1=0.2741)
  Directional -> Accuracy: 0.5952, MCC: 0.2259, F1: 0.5143

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.63375 | val 1.60624
  Epoch 016 - train 0.60898 | val 1.51803
  Classification -> best τ=0.370 (val F1=0.1997)
  Directional -> Accuracy: 0.5536, MCC: 0.1726, F1: 0.6377

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.56617 | val 1.85429
  Epoch 016 - train 0.55361 | val 3.64808
  Classification -> best τ=0.460 (val F1=0.2800)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.54996 | val 0.63474
  Epoch 020 - train 0.52170 | val 0.78748
  Epoch 030 - train 0.46989 | val 0.65657
  Epoch 040 - train 0.43537 | val 0.61875
  Epoch 050 - train 0.36969 | val 0.72052
  Classification -> best τ=0.470 (val F1=0.4976)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.62806 | val 0.84156
  Epoch 016 - train 0.50555 | val 1.40682
  Classification -> best τ=0.490 (val F1=0.2479)
  Directional -> Accuracy: 0.3514, MCC: -0.2962, F1: 0.3684

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.59754 | val 0.79657
  Epoch 017 - train 0.59252 | val 1.03703
  Classification -> best τ=0.415 (val F1=0.4217)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.64183 | val 0.78417
  Epoch 016 - train 0.58760 | val 1.22834
  Classification -> best τ=0.460 (val F1=0.3871)
  Directional -> Accuracy: 0.4783, MCC: -0.0169, F1: 0.2000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.55462 | val 1.07360
  Epoch 016 - train 0.54988 | val 1.45170
  Classification -> best τ=0.480 (val F1=0.2282)
  Directional -> Accuracy: 0.6047, MCC: 0.1772, F1: 0.6909

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.61714 | val 0.87147
  Epoch 020 - train 0.52095 | val 0.77220
  Epoch 021 - train 0.53334 | val 0.92243
  Classification -> best τ=0.570 (val F1=0.5514)
  Directional -> Accuracy: 0.3673, MCC: -0.1468, F1: 0.5079

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.66318 | val 0.77911
  Epoch 016 - train 0.59608 | val 0.76228
  Classification -> best τ=0.465 (val F1=0.2610)
  Directional -> Accuracy: 0.4464, MCC: -0.2436, F1: 0.6076

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.60453 | val 1.03097
  Epoch 016 - train 0.60580 | val 1.07445
  Classification -> best τ=0.510 (val F1=0.2277)
  Directional -> Accuracy: 0.5000, MCC: 0.1301, F1: 0.6585

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.62917 | val 1.59609
  Epoch 020 - train 0.57468 | val 1.37602
  Epoch 022 - train 0.55959 | val 1.30878
  Classification -> best τ=0.355 (val F1=0.1683)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.57137 | val 2.31866
  Epoch 016 - train 0.59329 | val 2.03019
  Classification -> best τ=0.465 (val F1=0.1168)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.63014 | val 0.78176
  Epoch 020 - train 0.56769 | val 1.05120

[I 2026-02-25 02:45:43,084] Trial 169 finished with value: 0.274656943790394 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.6000000000000001, 'batch_size': 32, 'learning_rate': 0.0036259213191164163, 'weight_decay': 0.0009906218155644028, 'lr_patience': 7, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 0.45453819294282816, 'early_stopping_min_delta': 0.002733420482116269}. Best is trial 164 with value: 0.2973019295845425.

  Epoch 024 - train 0.54795 | val 2.66712
  Classification -> best τ=0.255 (val F1=0.2847)
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.274656943790394
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.66768 | val 0.74605
  Epoch 020 - train 0.61863 | val 0.86950
  Epoch 022 - train 0.61020 | val 0.97761
  Classification -> best τ=0.420 (val F1=0.2798)
  Directional -> Accuracy: 0.4474, MCC: 0.0000, F1: 0.6182

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.65735 | val 0.69548
  Epoch 016 - train 0.57699 | val 0.70311
  Classification -> best τ=0.425 (val F1=0.1274)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.66985 | val 0.67687
  Epoch 018 - train 0.62131 | val 0.94939
  Classification -> best τ=0.585 (val F1=0.3924)
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.67778 | val 1.17484
  Epoch 016 - train 0.64667 | val 2.06809
  Classification -> best τ=0.500 (val F1=0.2286)
  Directional -> Accuracy: 0.4533, MCC: -0.0409, F1: 0.2264

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.61177 | val 0.66695
  Epoch 020 - train 0.58132 | val 0.75923
  Epoch 021 - train 0.56133 | val 0.75266
  Classification -> best τ=0.550 (val F1=0.4858)
  Directional -> Accuracy: 0.7059, MCC: 0.4110, F1: 0.7458

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.56806 | val 0.72316
  Epoch 020 - train 0.53317 | val 1.12062
  Epoch 022 - train 0.52091 | val 1.41574
  Classification -> best τ=0.470 (val F1=0.2901)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.65274 | val 0.81638
  Epoch 016 - train 0.63967 | val 0.86597
  Classification -> best τ=0.500 (val F1=0.1932)
  Directional -> Accuracy: 0.5362, MCC: 0.2793, F1: 0.6279

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.67731 | val 0.60641
  Epoch 020 - train 0.56473 | val 0.79375
  Epoch 025 - train 0.47154 | val 1.20504
  Classification -> best τ=0.325 (val F1=0.1590)
  Directional -> Accuracy: 0.5581, MCC: 0.0852, F1: 0.4571

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.61815 | val 1.80224
  Epoch 018 - train 0.53678 | val 3.51333
  Classification -> best τ=0.540 (val F1=0.1945)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.65412 | val 0.75189
  Epoch 016 - train 0.53822 | val 0.73861
  Classification -> best τ=0.490 (val F1=0.1816)
  Directional -> Accuracy: 0.4429, MCC: 0.0407, F1: 0.5979

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.64369 | val 1.84464
  Epoch 017 - train 0.59003 | val 2.16014
  Classification -> best τ=0.615 (val F1=0.3094)
  Directional -> Accuracy: 0.5400, MCC: 0.0164, F1: 0.0800

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.61895 | val 1.19194
  Epoch 016 - train 0.58010 | val 1.44033
  Classification -> best τ=0.445 (val F1=0.1806)
  Directional -> Accuracy: 0.6379, MCC: 0.3651, F1: 0.7273

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.61671 | val 0.75270
  Epoch 018 - train 0.52714 | val 0.86116
  Classification -> best τ=0.485 (val F1=0.2392)
  Directional -> Accuracy: 0.5952, MCC: 0.2368, F1: 0.6383

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.66328 | val 0.75368
  Epoch 017 - train 0.63255 | val 0.85322
  Classification -> best τ=0.420 (val F1=0.3629)
  Directional -> Accuracy: 0.5500, MCC: 0.1214, F1: 0.6494

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.63430 | val 2.48022
  Epoch 017 - train 0.57609 | val 2.31470
  Classification -> best τ=0.450 (val F1=0.2673)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.63870 | val 0.95993
  Epoch 017 - train 0.59760 | val 1.16007
  Classification -> best τ=0.580 (val F1=0.3115)
  Directional -> Accuracy: 0.6087, MCC: 0.2059, F1: 0.6667

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.66714 | val 1.30768
  Epoch 018 - train 0.62799 | val 2.68583
  Classification -> best τ=0.585 (val F1=0.1291)
  Directional -> Accuracy: 0.3729, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.63952 | val 1.07360
  Epoch 016 - train 0.66883 | val 1.29877
  Classification -> best τ=0.525 (val F1=0.2134)
  Directional -> Accuracy: 0.4267, MCC: 0.1351, F1: 0.0851

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.62855 | val 1.30125
  Epoch 016 - train 0.59186 | val 2.57317
  Classification -> best τ=0.485 (val F1=0.2305)
  Directional -> Accuracy: 0.4923, MCC: -0.0077, F1: 0.5217

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.66201 | val 0.73227
  Epoch 020 - train 0.59383 | val 0.71798
  Epoch 030 - train 0.53469 | val 1.14067
  Epoch 031 - train 0.52474 | val 0.92547
  Classification -> best τ=0.375 (val F1=0.3581)
  Directional -> Accuracy: 0.6000, MCC: 0.2571, F1: 0.5312

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.64225 | val 0.81263
  Epoch 020 - train 0.55660 | val 1.21523
  Epoch 030 - train 0.52516 | val 1.34651
  Epoch 039 - train 0.43768 | val 1.14683
  Classification -> best τ=0.355 (val F1=0.3740)
  Directional -> Accuracy: 0.4255, MCC: 0.0834, F1: 0.1818

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.66416 | val 0.92827
  Epoch 020 - train 0.60951 | val 1.13186
  Epoch 022 - train 0.60228 | val 1.12076
  Classification -> best τ=0.770 (val F1=0.2319)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.67021 | val 0.71596
  Epoch 018 - train 0.62575 | val 0.80527
  Classification -> best τ=0.525 (val F1=0.2174)
  Directional -> Accuracy: 0.5345, MCC: 0.1187, F1: 0.4906

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.67150 | val 0.85142
  Epoch 019 - train 0.63619 | val 1.01207
  Classification -> best τ=0.475 (val F1=0.1407)
  Directional -> Accuracy: 0.4462, MCC: -0.1866, F1: 0.6170

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.65539 | val 0.67035
  Epoch 020 - train 0.55552 | val 0.81773
  Epoch 021 - train 0.56866 | val 0.77339
  Classification -> best τ=0.480 (val F1=0.5052)
  Directional -> Accuracy: 0.5357, MCC: 0.1728, F1: 0.3810

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.60009 | val 1.16002
  Epoch 016 - train 0.56183 | val 2.53417
  Classification -> best τ=0.595 (val F1=0.0524)
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.71283 | val 0.85387
  Epoch 020 - train 0.62026 | val 0.72493
  Epoch 030 - train 0.59622 | val 0.86985
  Epoch 040 - train 0.55550 | val 0.78224
  Epoch 041 - train 0.54199 | val 0.82128
  Classification -> best τ=0.505 (val F1=0.4714)
  Directional -> Accuracy: 0.4286, MCC: -0.1840, F1: 0.5200

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.65322 | val 0.65101
  Epoch 020 - train 0.62068 | val 0.96515
  Epoch 025 - train 0.58425 | val 0.92490
  Classification -> best τ=0.305 (val F1=0.3862)
  Directional -> Accuracy: 0.5789, MCC: 0.1809, F1: 0.5714

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.76749 | val 0.94568
  Epoch 020 - train 0.57555 | val 1.26755
  Epoch 028 - train 0.47560 | val 0.85272
  Classification -> best τ=0.365 (val F1=0.3278)
  Directional -> Accuracy: 0.5366, MCC: 0.0166, F1: 0.6885

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.65172 | val 0.83315
  Epoch 016 - train 0.62987 | val 0.69837
  Classification -> best τ=0.485 (val F1=0.3365)
  Directional -> Accuracy: 0.5116, MCC: 0.1508, F1: 0.6667

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.68160 | val 0.81284
  Epoch 019 - train 0.60123 | val 1.16558
  Classification -> best τ=0.570 (val F1=0.2517)
  Directional -> Accuracy: 0.5349, MCC: 0.0224, F1: 0.6774

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.58579 | val 0.95284
  Epoch 018 - train 0.52341 | val 1.48585
  Classification -> best τ=0.535 (val F1=0.3757)
  Directional -> Accuracy: 0.4800, MCC: -0.0338, F1: 0.4800

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.63116 | val 0.74816
  Epoch 016 - train 0.62380 | val 0.80659
  Classification -> best τ=0.395 (val F1=0.3744)
  Directional -> Accuracy: 0.5342, MCC: 0.1465, F1: 0.4333

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.60106 | val 0.94005
  Epoch 018 - train 0.64281 | val 0.96337
  Classification -> best τ=0.575 (val F1=0.2887)
  Directional -> Accuracy: 0.5405, MCC: 0.1712, F1: 0.1053

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.64641 | val 0.89468
  Epoch 016 - train 0.55969 | val 1.17469
  Classification -> best τ=0.500 (val F1=0.3012)
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.61695 | val 0.71248
  Epoch 020 - train 0.58955 | val 0.76700
  Epoch 024 - train 0.55356 | val 0.99750
  Classification -> best τ=0.345 (val F1=0.3634)
  Directional -> Accuracy: 0.5909, MCC: 0.1750, F1: 0.6301

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.65203 | val 0.80722
  Epoch 018 - train 0.57599 | val 1.48703
  Classification -> best τ=0.545 (val F1=0.3364)
  Directional -> Accuracy: 0.6190, MCC: 0.3091, F1: 0.5000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.67483 | val 1.31798
  Epoch 018 - train 0.58157 | val 2.55758
  Classification -> best τ=0.375 (val F1=0.3039)
  Directional -> Accuracy: 0.4643, MCC: -0.0138, F1: 0.6250

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.65940 | val 1.14507
  Epoch 016 - train 0.62864 | val 1.47085
  Classification -> best τ=0.420 (val F1=0.3451)
  Directional -> Accuracy: 0.5870, MCC: 0.0324, F1: 0.7164

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.66960 | val 0.85986
  Epoch 018 - train 0.55657 | val 0.79622
  Classification -> best τ=0.460 (val F1=0.2417)
  Directional -> Accuracy: 0.3265, MCC: -0.2361, F1: 0.4407

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.67708 | val 0.78181
  Epoch 020 - train 0.58696 | val 0.85169
  Epoch 021 - train 0.49398 | val 0.95807
  Classification -> best τ=0.580 (val F1=0.5284)
  Directional -> Accuracy: 0.5676, MCC: 0.1378, F1: 0.5789

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.64315 | val 1.08388
  Epoch 020 - train 0.57565 | val 1.74171
  Classification -> best τ=0.250 (val F1=0.3775)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.64337 | val 0.70698
  Epoch 020 - train 0.64102 | val 1.72961
  Epoch 021 - train 0.59329 | val 2.03685
  Classification -> best τ=0.375 (val F1=0.4084)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.6857

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.61134 | val 0.99602
  Epoch 018 - train 0.46428 | val 1.36560
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.7164

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.64967 | val 0.87186
  Epoch 020 - train 0.63218 | val 0.75143
  Epoch 030 - train 0.47664 | val 1.07903
  Epoch 040 - train 0.42949 | val 0.96176
  Epoch 050 - train 0.28749 | val 1.50028
  Classification -> best τ=0.350 (val F1=0.6110)
  Directional -> Accuracy: 0.3878, MCC: -0.0687, F1: 0.5312

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.65932 | val 1.42178
  Epoch 017 - train 0.61103 | val 2.18369
  Classification -> best τ=0.560 (val F1=0.1914)
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.63438 | val 1.23758
  Epoch 017 - train 0.59822 | val 1.21038
  Classification -> best τ=0.530 (val F1=0.2320)
  Directional -> Accuracy: 0.5000, MCC: -0.0515, F1: 0.1250

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.66449 | val 1.35970
  Epoch 018 - train 0.56884 | val 2.50934
  Classification -> best τ=0.385 (val F1=0.3163)
  Directional -> Accuracy: 0.5370, MCC: 0.0695, F1: 0.6667

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.63794 | val 0.93350
  Epoch 016 - train 0.58065 | val 1.70151
  Classification -> best τ=0.345 (val F1=0.0667)
  Directional -> Accuracy: 0.4821, MCC: -0.0413, F1: 0.5246

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.63634 | val 1.10188

[I 2026-02-25 02:48:08,181] Trial 170 finished with value: 0.2848320584403305 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 0.005125694771645822, 'weight_decay': 0.00043059012107305876, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 0.5097168925476463, 'early_stopping_min_delta': 0.003052176946017391}. Best is trial 164 with value: 0.2973019295845425.

  Epoch 016 - train 0.63524 | val 1.14035
  Classification -> best τ=0.530 (val F1=0.1498)
  Directional -> Accuracy: 0.4262, MCC: -0.1430, F1: 0.4444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2848320584403305
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.64659 | val 0.82375
  Epoch 019 - train 0.62118 | val 1.85353
  Classification -> best τ=0.545 (val F1=0.2919)
  Directional -> Accuracy: 0.5658, MCC: 0.1148, F1: 0.4923

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.63242 | val 0.75982
  Epoch 018 - train 0.56391 | val 0.83217
  Classification -> best τ=0.470 (val F1=0.2526)
  Directional -> Accuracy: 0.5333, MCC: -0.0068, F1: 0.6441

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.65188 | val 0.67968
  Epoch 016 - train 0.61061 | val 0.73382
  Classification -> best τ=0.535 (val F1=0.3114)
  Directional -> Accuracy: 0.5957, MCC: 0.2240, F1: 0.5366

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.64805 | val 1.98435
  Epoch 016 - train 0.64122 | val 1.17799
  Classification -> best τ=0.440 (val F1=0.1084)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.60913 | val 2.18854
  Epoch 019 - train 0.55185 | val 1.15419
  Classification -> best τ=0.590 (val F1=0.3245)
  Directional -> Accuracy: 0.3922, MCC: -0.2637, F1: 0.5079

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.65127 | val 0.69942
  Epoch 016 - train 0.59912 | val 0.71962
  Classification -> best τ=0.565 (val F1=0.2357)
  Directional -> Accuracy: 0.4894, MCC: 0.0000, F1: 0.6571

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.67287 | val 0.73452
  Epoch 019 - train 0.64919 | val 0.78777
  Classification -> best τ=0.555 (val F1=0.1805)
  Directional -> Accuracy: 0.5507, MCC: -0.0062, F1: 0.2791

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.55821 | val 1.27959
  Epoch 016 - train 0.57486 | val 1.26022
  Classification -> best τ=0.470 (val F1=0.1214)
  Directional -> Accuracy: 0.4186, MCC: -0.0364, F1: 0.5763

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.66566 | val 1.47605
  Epoch 018 - train 0.51457 | val 2.48721
  Classification -> best τ=0.405 (val F1=0.2308)
  Directional -> Accuracy: 0.6531, MCC: 0.3099, F1: 0.6383

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.65073 | val 0.95451
  Epoch 016 - train 0.63091 | val 0.82883
  Classification -> best τ=0.400 (val F1=0.2602)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.64780 | val 1.74195
  Epoch 018 - train 0.57673 | val 3.43710
  Classification -> best τ=0.595 (val F1=0.3118)
  Directional -> Accuracy: 0.6000, MCC: 0.2059, F1: 0.3333

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.64539 | val 1.29112
  Epoch 018 - train 0.56882 | val 1.13620
  Classification -> best τ=0.465 (val F1=0.2453)
  Directional -> Accuracy: 0.5517, MCC: 0.2335, F1: 0.1875

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.64074 | val 0.73601
  Epoch 016 - train 0.61659 | val 1.20102
  Classification -> best τ=0.425 (val F1=0.2323)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.65329 | val 1.08125
  Epoch 017 - train 0.62742 | val 1.21070
  Classification -> best τ=0.360 (val F1=0.2667)
  Directional -> Accuracy: 0.4833, MCC: -0.0765, F1: 0.6437

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.65401 | val 1.42238
  Epoch 018 - train 0.57824 | val 2.85873
  Classification -> best τ=0.570 (val F1=0.2673)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.62309 | val 0.83924
  Epoch 018 - train 0.61921 | val 0.92828
  Classification -> best τ=0.445 (val F1=0.4264)
  Directional -> Accuracy: 0.5797, MCC: 0.1438, F1: 0.6506

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.65258 | val 1.71949
  Epoch 019 - train 0.60722 | val 3.10999
  Classification -> best τ=0.485 (val F1=0.0660)
  Directional -> Accuracy: 0.5254, MCC: 0.0215, F1: 0.6000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.67178 | val 1.32032
  Epoch 017 - train 0.62833 | val 1.17743
  Classification -> best τ=0.375 (val F1=0.2446)
  Directional -> Accuracy: 0.6933, MCC: 0.3539, F1: 0.7890

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.64808 | val 1.14199
  Epoch 017 - train 0.62103 | val 2.31018
  Classification -> best τ=0.570 (val F1=0.2000)
  Directional -> Accuracy: 0.4769, MCC: 0.0998, F1: 0.2917

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.65071 | val 0.65714
  Epoch 020 - train 0.55940 | val 2.35098
  Epoch 025 - train 0.55749 | val 0.84099
  Classification -> best τ=0.395 (val F1=0.3799)
  Directional -> Accuracy: 0.6133, MCC: 0.2264, F1: 0.6329

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.61594 | val 1.46524
  Epoch 020 - train 0.48132 | val 0.70210
  Epoch 030 - train 0.44475 | val 0.88440
  Epoch 031 - train 0.45160 | val 0.81520
  Classification -> best τ=0.655 (val F1=0.3801)
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.67277 | val 0.84987
  Epoch 016 - train 0.62852 | val 1.01631
  Classification -> best τ=0.450 (val F1=0.1913)
  Directional -> Accuracy: 0.4545, MCC: -0.1476, F1: 0.6087

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.68877 | val 0.93117
  Epoch 020 - train 0.64187 | val 1.03049
  Epoch 022 - train 0.60723 | val 0.93649
  Classification -> best τ=0.520 (val F1=0.3454)
  Directional -> Accuracy: 0.5345, MCC: 0.0555, F1: 0.5846

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.67903 | val 1.07192
  Epoch 016 - train 0.66777 | val 0.79089
  Classification -> best τ=0.555 (val F1=0.1936)
  Directional -> Accuracy: 0.5077, MCC: -0.0336, F1: 0.1579

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.62999 | val 0.68092
  Epoch 020 - train 0.53911 | val 0.71649
  Epoch 028 - train 0.50986 | val 0.73127
  Classification -> best τ=0.540 (val F1=0.4297)
  Directional -> Accuracy: 0.5179, MCC: 0.1613, F1: 0.3077

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.62335 | val 0.88086
  Epoch 016 - train 0.51692 | val 1.51346
  Classification -> best τ=0.595 (val F1=0.1251)
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.65243 | val 0.73000
  Epoch 020 - train 0.57439 | val 0.71263
  Epoch 030 - train 0.63247 | val 0.70184
  Epoch 031 - train 0.56885 | val 0.95481
  Classification -> best τ=0.600 (val F1=0.1936)
  Directional -> Accuracy: 0.4286, MCC: -0.1021, F1: 0.3684

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.66022 | val 0.70320
  Epoch 018 - train 0.59936 | val 1.02926
  Classification -> best τ=0.540 (val F1=0.2866)
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.64348 | val 0.70030
  Epoch 020 - train 0.49636 | val 1.52763
  Epoch 024 - train 0.51741 | val 0.93273
  Classification -> best τ=0.420 (val F1=0.4109)
  Directional -> Accuracy: 0.6341, MCC: 0.2830, F1: 0.7273

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.63999 | val 0.62693
  Epoch 020 - train 0.59811 | val 0.77610
  Epoch 023 - train 0.57813 | val 0.82123
  Classification -> best τ=0.520 (val F1=0.5410)
  Directional -> Accuracy: 0.4884, MCC: -0.0162, F1: 0.5600

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.66209 | val 0.87538
  Epoch 018 - train 0.56175 | val 0.84021
  Classification -> best τ=0.545 (val F1=0.0601)
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.57467 | val 0.95401
  Epoch 016 - train 0.55501 | val 1.06752
  Classification -> best τ=0.475 (val F1=0.3309)
  Directional -> Accuracy: 0.5000, MCC: 0.1884, F1: 0.1379

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.64985 | val 0.68832
  Epoch 020 - train 0.61098 | val 1.34088
  Epoch 022 - train 0.59471 | val 1.45973
  Classification -> best τ=0.330 (val F1=0.3396)
  Directional -> Accuracy: 0.5753, MCC: 0.1768, F1: 0.5634

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.69778 | val 0.80956
  Epoch 019 - train 0.60022 | val 1.08093
  Classification -> best τ=0.580 (val F1=0.2667)
  Directional -> Accuracy: 0.4865, MCC: -0.0065, F1: 0.6415

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.67929 | val 0.99949
  Epoch 016 - train 0.61901 | val 1.21645
  Classification -> best τ=0.420 (val F1=0.1902)
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.63831 | val 0.73243
  Epoch 016 - train 0.58082 | val 0.83790
  Classification -> best τ=0.450 (val F1=0.3787)
  Directional -> Accuracy: 0.5909, MCC: 0.1443, F1: 0.6667

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.57437 | val 1.55292
  Epoch 018 - train 0.45503 | val 2.21694
  Classification -> best τ=0.495 (val F1=0.3264)
  Directional -> Accuracy: 0.6190, MCC: 0.2697, F1: 0.5556

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.61556 | val 1.11336
  Epoch 018 - train 0.58366 | val 1.68058
  Classification -> best τ=0.505 (val F1=0.2530)
  Directional -> Accuracy: 0.5357, MCC: 0.1132, F1: 0.6061

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.57048 | val 1.68420
  Epoch 016 - train 0.51832 | val 2.04171
  Classification -> best τ=0.590 (val F1=0.2882)
  Directional -> Accuracy: 0.3696, MCC: -0.1490, F1: 0.0645

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.61346 | val 0.66435
  Epoch 020 - train 0.59547 | val 0.63606
  Epoch 030 - train 0.52297 | val 0.82667
  Epoch 035 - train 0.48928 | val 0.79580
  Classification -> best τ=0.230 (val F1=0.3993)
  Directional -> Accuracy: 0.3469, MCC: -0.1894, F1: 0.5152

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.64957 | val 0.81796
  Epoch 020 - train 0.59483 | val 1.01898
  Epoch 022 - train 0.55843 | val 1.04783
  Classification -> best τ=0.400 (val F1=0.3882)
  Directional -> Accuracy: 0.4595, MCC: -0.0985, F1: 0.5238

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.65365 | val 0.87031
  Epoch 020 - train 0.61290 | val 0.98470
  Epoch 023 - train 0.57271 | val 1.25411
  Classification -> best τ=0.235 (val F1=0.4028)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.69627 | val 1.03154
  Epoch 017 - train 0.58687 | val 0.94709
  Classification -> best τ=0.415 (val F1=0.3560)
  Directional -> Accuracy: 0.5217, MCC: 0.1410, F1: 0.2143

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.58039 | val 1.11839
  Epoch 017 - train 0.51447 | val 1.79467
  Classification -> best τ=0.560 (val F1=0.3294)
  Directional -> Accuracy: 0.5116, MCC: 0.0617, F1: 0.4615

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.68489 | val 0.77378
  Epoch 020 - train 0.59557 | val 0.84803
  Epoch 030 - train 0.56424 | val 0.99591
  Epoch 038 - train 0.45615 | val 1.19326
  Classification -> best τ=0.385 (val F1=0.7040)
  Directional -> Accuracy: 0.3673, MCC: -0.1462, F1: 0.5231

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.65262 | val 1.51463
  Epoch 018 - train 0.65973 | val 2.17137
  Classification -> best τ=0.640 (val F1=0.1085)
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.66444 | val 0.93843
  Epoch 017 - train 0.60765 | val 1.49551
  Classification -> best τ=0.555 (val F1=0.2434)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.62196 | val 1.74905
  Epoch 019 - train 0.60586 | val 1.83670
  Classification -> best τ=0.350 (val F1=0.2357)
  Directional -> Accuracy: 0.5185, MCC: 0.0105, F1: 0.6667

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.65391 | val 1.09572
  Epoch 016 - train 0.57850 | val 1.83222
  Classification -> best τ=0.360 (val F1=0.1667)
  Directional -> Accuracy: 0.5179, MCC: 0.0266, F1: 0.5846

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.64433 | val 1.31170
  Epoch 020 - train 0.62966 | val 2.25103
  Epoch 021 - train 0.61558 | val 1.77266

[I 2026-02-25 02:50:28,548] Trial 171 finished with value: 0.2817306765445144 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 0.004907697402249465, 'weight_decay': 0.0003427582547491218, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 0.5904438013752105, 'early_stopping_min_delta': 0.0034194559295235797}. Best is trial 164 with value: 0.2973019295845425.

  Classification -> best τ=0.560 (val F1=0.2639)
  Directional -> Accuracy: 0.4426, MCC: -0.1904, F1: 0.1500

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2817306765445144
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.64661 | val 0.75814
  Epoch 016 - train 0.65921 | val 1.23934
  Classification -> best τ=0.400 (val F1=0.1356)
  Directional -> Accuracy: 0.4342, MCC: -0.0894, F1: 0.5981

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.62459 | val 0.70589
  Epoch 020 - train 0.56490 | val 0.91296
  Epoch 022 - train 0.53861 | val 0.74829
  Classification -> best τ=0.550 (val F1=0.1700)
  Directional -> Accuracy: 0.6444, MCC: 0.2619, F1: 0.7037

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.67640 | val 0.69288
  Epoch 020 - train 0.64640 | val 0.73291
  Epoch 026 - train 0.62241 | val 0.75872
  Classification -> best τ=0.555 (val F1=0.3673)
  Directional -> Accuracy: 0.4894, MCC: 0.0705, F1: 0.1429

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.66651 | val 1.00304
  Epoch 020 - train 0.64492 | val 2.19148
  Epoch 026 - train 0.61528 | val 1.76969
  Classification -> best τ=0.260 (val F1=0.2125)
  Directional -> Accuracy: 0.6000, MCC: 0.1808, F1: 0.6667

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.60804 | val 0.69214
  Epoch 020 - train 0.58103 | val 0.90915
  Epoch 022 - train 0.53079 | val 0.90051
  Classification -> best τ=0.645 (val F1=0.4255)
  Directional -> Accuracy: 0.7451, MCC: 0.4883, F1: 0.7719

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.64451 | val 0.88327
  Epoch 016 - train 0.53728 | val 1.17738
  Classification -> best τ=0.535 (val F1=0.2887)
  Directional -> Accuracy: 0.6383, MCC: 0.3050, F1: 0.6909

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.66719 | val 0.69558
  Epoch 019 - train 0.64241 | val 1.06265
  Classification -> best τ=0.455 (val F1=0.2654)
  Directional -> Accuracy: 0.4638, MCC: 0.0887, F1: 0.5747

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.71074 | val 0.97313
  Epoch 020 - train 0.53235 | val 1.37744
  Epoch 021 - train 0.49381 | val 0.90731
  Classification -> best τ=0.370 (val F1=0.0226)
  Directional -> Accuracy: 0.4651, MCC: -0.1480, F1: 0.2581

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.65512 | val 0.66472
  Epoch 020 - train 0.60697 | val 0.72393
  Epoch 026 - train 0.58353 | val 1.54737
  Classification -> best τ=0.350 (val F1=0.5193)
  Directional -> Accuracy: 0.5918, MCC: 0.1635, F1: 0.2857

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.61359 | val 0.79339
  Epoch 018 - train 0.58922 | val 0.76438
  Classification -> best τ=0.475 (val F1=0.2823)
  Directional -> Accuracy: 0.5143, MCC: 0.1443, F1: 0.6047

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.62943 | val 2.27501
  Epoch 017 - train 0.56752 | val 2.65165
  Classification -> best τ=0.510 (val F1=0.4082)
  Directional -> Accuracy: 0.6000, MCC: 0.2274, F1: 0.2857

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.62792 | val 1.15945
  Epoch 017 - train 0.59900 | val 1.55828
  Classification -> best τ=0.500 (val F1=0.3606)
  Directional -> Accuracy: 0.5345, MCC: 0.1132, F1: 0.2286

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.61906 | val 0.72766
  Epoch 016 - train 0.60341 | val 0.99137
  Classification -> best τ=0.395 (val F1=0.2731)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.65826 | val 0.66291
  Epoch 020 - train 0.64767 | val 0.83914
  Epoch 021 - train 0.62050 | val 0.78808
  Classification -> best τ=0.450 (val F1=0.3367)
  Directional -> Accuracy: 0.4000, MCC: -0.2364, F1: 0.5263

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.62756 | val 0.95178
  Epoch 016 - train 0.57378 | val 1.71382
  Classification -> best τ=0.555 (val F1=0.2673)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.67048 | val 0.95774
  Epoch 019 - train 0.58361 | val 0.94134
  Classification -> best τ=0.500 (val F1=0.1569)
  Directional -> Accuracy: 0.5507, MCC: 0.1554, F1: 0.4364

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.64183 | val 1.67785
  Epoch 016 - train 0.64528 | val 2.74915
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.63912 | val 0.83264
  Epoch 020 - train 0.59613 | val 1.05648
  Epoch 021 - train 0.59878 | val 1.73631
  Classification -> best τ=0.485 (val F1=0.1560)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.66399 | val 1.25176
  Epoch 016 - train 0.61150 | val 2.47035
  Classification -> best τ=0.385 (val F1=0.1640)
  Directional -> Accuracy: 0.5385, MCC: 0.1728, F1: 0.4643

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.62053 | val 0.68296
  Epoch 019 - train 0.58180 | val 1.01128
  Classification -> best τ=0.600 (val F1=0.2408)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.67791 | val 0.87694
  Epoch 020 - train 0.50434 | val 0.87567
  Epoch 027 - train 0.46686 | val 0.80664
  Classification -> best τ=0.605 (val F1=0.3287)
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.66341 | val 0.75795
  Epoch 020 - train 0.60147 | val 1.10361
  Epoch 026 - train 0.57730 | val 1.95570
  Classification -> best τ=0.500 (val F1=0.2273)
  Directional -> Accuracy: 0.4394, MCC: -0.1240, F1: 0.4932

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.66077 | val 0.84881
  Epoch 016 - train 0.63467 | val 0.77299
  Classification -> best τ=0.585 (val F1=0.2875)
  Directional -> Accuracy: 0.5172, MCC: 0.1165, F1: 0.4167

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.68398 | val 0.96536
  Epoch 016 - train 0.63974 | val 0.84210
  Classification -> best τ=0.505 (val F1=0.0690)
  Directional -> Accuracy: 0.5231, MCC: 0.0455, F1: 0.5079

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.63174 | val 0.67040
  Epoch 020 - train 0.55462 | val 0.97741
  Epoch 024 - train 0.53579 | val 0.81470
  Classification -> best τ=0.520 (val F1=0.4057)
  Directional -> Accuracy: 0.5536, MCC: 0.2064, F1: 0.4186

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.62997 | val 0.79480
  Epoch 016 - train 0.59282 | val 2.05089
  Classification -> best τ=0.495 (val F1=0.2935)
  Directional -> Accuracy: 0.4130, MCC: -0.1164, F1: 0.5574

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.66522 | val 0.79341
  Epoch 016 - train 0.65560 | val 0.69776
  Classification -> best τ=0.530 (val F1=0.0525)
  Directional -> Accuracy: 0.4762, MCC: 0.0152, F1: 0.3889

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.61261 | val 0.72129
  Epoch 016 - train 0.57464 | val 0.88346
  Classification -> best τ=0.430 (val F1=0.2940)
  Directional -> Accuracy: 0.4737, MCC: 0.1685, F1: 0.1176

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.65519 | val 0.66908
  Epoch 020 - train 0.50092 | val 1.43051
  Epoch 025 - train 0.53530 | val 1.10026
  Classification -> best τ=0.570 (val F1=0.3477)
  Directional -> Accuracy: 0.5610, MCC: 0.1065, F1: 0.6250

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.64793 | val 0.69237
  Epoch 020 - train 0.53228 | val 1.68922
  Epoch 023 - train 0.48330 | val 1.91985
  Classification -> best τ=0.680 (val F1=0.2814)
  Directional -> Accuracy: 0.4884, MCC: -0.0353, F1: 0.3529

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.68457 | val 0.94801
  Epoch 020 - train 0.52188 | val 0.86014
  Classification -> best τ=0.650 (val F1=0.0574)
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.62678 | val 1.05394
  Epoch 016 - train 0.58013 | val 1.00588
  Classification -> best τ=0.545 (val F1=0.2969)
  Directional -> Accuracy: 0.5800, MCC: 0.1906, F1: 0.5333

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.67640 | val 0.67079
  Epoch 020 - train 0.62279 | val 0.75118
  Epoch 024 - train 0.60869 | val 0.93028
  Classification -> best τ=0.295 (val F1=0.3396)
  Directional -> Accuracy: 0.5753, MCC: 0.1768, F1: 0.5634

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.56612 | val 0.87666
  Epoch 018 - train 0.58132 | val 0.85365
  Classification -> best τ=0.520 (val F1=0.2887)
  Directional -> Accuracy: 0.5676, MCC: 0.1737, F1: 0.6522

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.63951 | val 0.92233
  Epoch 016 - train 0.60458 | val 0.94590
  Classification -> best τ=0.555 (val F1=0.2248)
  Directional -> Accuracy: 0.5227, MCC: 0.1145, F1: 0.6441

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.65017 | val 0.70256
  Epoch 018 - train 0.59839 | val 0.74788
  Classification -> best τ=0.330 (val F1=0.3254)
  Directional -> Accuracy: 0.5758, MCC: 0.0000, F1: 0.7308

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.66125 | val 0.84368
  Epoch 019 - train 0.53218 | val 1.62257
  Classification -> best τ=0.635 (val F1=0.2357)
  Directional -> Accuracy: 0.4524, MCC: -0.1058, F1: 0.0800

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.59752 | val 1.31938
  Epoch 018 - train 0.56031 | val 2.00552
  Classification -> best τ=0.450 (val F1=0.2530)
  Directional -> Accuracy: 0.4821, MCC: -0.0083, F1: 0.5538

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.57371 | val 1.75393
  Epoch 016 - train 0.56456 | val 2.05329
  Classification -> best τ=0.415 (val F1=0.3397)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.62282 | val 0.69937
  Epoch 020 - train 0.57140 | val 0.69387
  Epoch 030 - train 0.47498 | val 0.60841
  Epoch 040 - train 0.47366 | val 0.81877
  Epoch 045 - train 0.39341 | val 0.65500
  Classification -> best τ=0.450 (val F1=0.5606)
  Directional -> Accuracy: 0.3878, MCC: 0.0180, F1: 0.5312

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.68534 | val 0.73166
  Epoch 020 - train 0.60177 | val 0.98323
  Epoch 023 - train 0.52946 | val 1.17107
  Classification -> best τ=0.390 (val F1=0.3699)
  Directional -> Accuracy: 0.5135, MCC: 0.0206, F1: 0.5500

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.67049 | val 0.70814
  Epoch 016 - train 0.61845 | val 0.78031
  Classification -> best τ=0.385 (val F1=0.2448)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.62999 | val 0.68659
  Epoch 020 - train 0.63603 | val 1.01148
  Epoch 023 - train 0.62192 | val 1.19940
  Classification -> best τ=0.470 (val F1=0.3403)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.0000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.72179 | val 0.96000
  Epoch 016 - train 0.57957 | val 0.94865
  Classification -> best τ=0.545 (val F1=0.2530)
  Directional -> Accuracy: 0.3953, MCC: -0.2482, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.71911 | val 0.68669
  Epoch 020 - train 0.56563 | val 0.84346
  Epoch 030 - train 0.54200 | val 1.10375
  Classification -> best τ=0.455 (val F1=0.5249)
  Directional -> Accuracy: 0.4082, MCC: -0.0342, F1: 0.5246

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.70472 | val 1.09376
  Epoch 016 - train 0.63714 | val 1.28888
  Classification -> best τ=0.440 (val F1=0.2392)
  Directional -> Accuracy: 0.4643, MCC: -0.2582, F1: 0.6341

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.63905 | val 0.90507
  Epoch 018 - train 0.58081 | val 0.86202
  Classification -> best τ=0.650 (val F1=0.3883)
  Directional -> Accuracy: 0.4821, MCC: -0.0684, F1: 0.2564

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.67826 | val 0.79953
  Epoch 019 - train 0.61364 | val 1.30337
  Classification -> best τ=0.500 (val F1=0.2383)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.63296 | val 2.25458
  Epoch 016 - train 0.61411 | val 2.19651
  Classification -> best τ=0.510 (val F1=0.1979)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.69060 | val 0.73855

[I 2026-02-25 02:52:48,050] Trial 172 finished with value: 0.2728618584285308 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 0.005031267432515212, 'weight_decay': 0.0004272803998549763, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 0.5856699750062464, 'early_stopping_min_delta': 0.003405742695893082}. Best is trial 164 with value: 0.2973019295845425.

  Epoch 018 - train 0.64290 | val 2.50294
  Classification -> best τ=0.430 (val F1=0.2847)
  Directional -> Accuracy: 0.4918, MCC: 0.1229, F1: 0.6517

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2728618584285308
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.65066 | val 0.71683
  Epoch 020 - train 0.61444 | val 0.75524
  Classification -> best τ=0.550 (val F1=0.2919)
  Directional -> Accuracy: 0.5132, MCC: -0.0573, F1: 0.2128

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.65409 | val 0.68779
  Epoch 016 - train 0.61023 | val 0.71310
  Classification -> best τ=0.465 (val F1=0.0406)
  Directional -> Accuracy: 0.6222, MCC: 0.1941, F1: 0.7385

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.67506 | val 0.67926
  Epoch 020 - train 0.63301 | val 0.70558
  Epoch 021 - train 0.64537 | val 0.71242
  Classification -> best τ=0.450 (val F1=0.3693)
  Directional -> Accuracy: 0.6383, MCC: 0.3262, F1: 0.7385

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.64417 | val 1.91002
  Epoch 016 - train 0.62866 | val 2.05441
  Classification -> best τ=0.385 (val F1=0.1867)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.64993 | val 0.63283
  Epoch 020 - train 0.58786 | val 0.63376
  Epoch 027 - train 0.59235 | val 0.65120
  Classification -> best τ=0.540 (val F1=0.4946)
  Directional -> Accuracy: 0.6078, MCC: 0.2092, F1: 0.6774

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.63985 | val 0.70292
  Epoch 016 - train 0.61090 | val 0.73031
  Classification -> best τ=0.475 (val F1=0.1857)
  Directional -> Accuracy: 0.5532, MCC: 0.1357, F1: 0.2759

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.67038 | val 0.70107
  Epoch 018 - train 0.64228 | val 0.71267
  Classification -> best τ=0.465 (val F1=0.1687)
  Directional -> Accuracy: 0.4783, MCC: 0.1180, F1: 0.5814

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.65026 | val 0.68730
  Epoch 020 - train 0.61022 | val 0.62992
  Epoch 030 - train 0.58831 | val 0.73162
  Epoch 033 - train 0.55686 | val 0.71919
  Classification -> best τ=0.180 (val F1=0.1214)
  Directional -> Accuracy: 0.5116, MCC: -0.0112, F1: 0.4000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.64917 | val 0.67481
  Epoch 020 - train 0.59381 | val 0.66434
  Epoch 030 - train 0.59044 | val 0.68915
  Epoch 033 - train 0.59600 | val 0.68262
  Classification -> best τ=0.445 (val F1=0.3509)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.63007 | val 0.83662
  Epoch 016 - train 0.64361 | val 0.70708
  Classification -> best τ=0.440 (val F1=0.1105)
  Directional -> Accuracy: 0.4429, MCC: 0.0407, F1: 0.5979

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.63069 | val 0.81849
  Epoch 016 - train 0.63831 | val 0.95313
  Classification -> best τ=0.465 (val F1=0.0655)
  Directional -> Accuracy: 0.6000, MCC: 0.1879, F1: 0.4118

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.66918 | val 1.08901
  Epoch 016 - train 0.62457 | val 1.22438
  Classification -> best τ=0.460 (val F1=0.1955)
  Directional -> Accuracy: 0.5172, MCC: 0.1325, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.60769 | val 0.90260
  Epoch 016 - train 0.61426 | val 1.02514
  Classification -> best τ=0.490 (val F1=0.1180)
  Directional -> Accuracy: 0.5476, MCC: 0.1003, F1: 0.5366

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.64684 | val 0.70217
  Epoch 016 - train 0.66147 | val 0.73728
  Classification -> best τ=0.485 (val F1=0.2212)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.63945 | val 1.01072
  Epoch 016 - train 0.61294 | val 1.41282
  Classification -> best τ=0.500 (val F1=0.0976)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.65601 | val 0.75950
  Epoch 018 - train 0.62146 | val 0.77151
  Classification -> best τ=0.420 (val F1=0.2708)
  Directional -> Accuracy: 0.5797, MCC: 0.1885, F1: 0.7129

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.63281 | val 1.60861
  Epoch 016 - train 0.63459 | val 1.93236
  Classification -> best τ=0.545 (val F1=0.1510)
  Directional -> Accuracy: 0.3390, MCC: -0.2429, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.65115 | val 1.02376
  Epoch 016 - train 0.65553 | val 1.21860
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6000, MCC: 0.0000, F1: 0.7500

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.65936 | val 0.79706
  Epoch 016 - train 0.62765 | val 0.89284
  Classification -> best τ=0.510 (val F1=0.1231)
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.64070 | val 0.71580
  Epoch 016 - train 0.63405 | val 0.70712
  Classification -> best τ=0.505 (val F1=0.1682)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.64854 | val 0.73126
  Epoch 016 - train 0.62444 | val 0.75868
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.66181 | val 0.73468
  Epoch 016 - train 0.65087 | val 0.77689
  Classification -> best τ=0.465 (val F1=0.1288)
  Directional -> Accuracy: 0.5758, MCC: 0.1526, F1: 0.5484

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.67762 | val 0.70496
  Epoch 020 - train 0.67040 | val 0.72103
  Classification -> best τ=0.535 (val F1=0.2710)
  Directional -> Accuracy: 0.4655, MCC: 0.0453, F1: 0.2439

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.65272 | val 0.68720
  Epoch 020 - train 0.63122 | val 0.72542
  Epoch 030 - train 0.60888 | val 0.77923
  Classification -> best τ=0.345 (val F1=0.2741)
  Directional -> Accuracy: 0.4769, MCC: 0.0000, F1: 0.6458

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.63832 | val 0.65310
  Epoch 020 - train 0.63075 | val 0.65165
  Epoch 030 - train 0.60210 | val 0.66069
  Epoch 031 - train 0.60877 | val 0.66168
  Classification -> best τ=0.445 (val F1=0.4082)
  Directional -> Accuracy: 0.5893, MCC: 0.2075, F1: 0.5660

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.66630 | val 0.70800
  Epoch 016 - train 0.62063 | val 0.75310
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.65278 | val 0.69888
  Epoch 020 - train 0.62412 | val 0.68715
  Epoch 030 - train 0.63079 | val 0.67909
  Epoch 040 - train 0.62206 | val 0.70722
  Epoch 041 - train 0.60037 | val 0.69278
  Classification -> best τ=0.625 (val F1=0.1936)
  Directional -> Accuracy: 0.5238, MCC: 0.0550, F1: 0.5455

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.62480 | val 0.72165
  Epoch 020 - train 0.60066 | val 0.79123
  Classification -> best τ=0.410 (val F1=0.2235)
  Directional -> Accuracy: 0.5439, MCC: 0.2554, F1: 0.3500

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.63580 | val 0.75500
  Epoch 016 - train 0.64377 | val 0.88731
  Classification -> best τ=0.475 (val F1=0.0601)
  Directional -> Accuracy: 0.5610, MCC: 0.1418, F1: 0.5263

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.64866 | val 0.71761
  Epoch 016 - train 0.63330 | val 0.70381
  Classification -> best τ=0.540 (val F1=0.1542)
  Directional -> Accuracy: 0.4651, MCC: -0.0733, F1: 0.5965

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.65505 | val 0.72390
  Epoch 016 - train 0.64706 | val 0.72881
  Classification -> best τ=0.500 (val F1=0.1143)
  Directional -> Accuracy: 0.5581, MCC: 0.0940, F1: 0.6780

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.64749 | val 0.70533
  Epoch 016 - train 0.60943 | val 0.71839
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.63616 | val 0.72449
  Epoch 019 - train 0.62995 | val 0.72710
  Classification -> best τ=0.435 (val F1=0.2933)
  Directional -> Accuracy: 0.5342, MCC: 0.1602, F1: 0.4138

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.64252 | val 0.78422
  Epoch 016 - train 0.58500 | val 1.05448
  Classification -> best τ=0.500 (val F1=0.3563)
  Directional -> Accuracy: 0.5135, MCC: 0.0293, F1: 0.5263

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.67370 | val 0.75762
  Epoch 016 - train 0.64407 | val 0.84439
  Classification -> best τ=0.450 (val F1=0.1329)
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.63542 | val 0.68815
  Epoch 019 - train 0.61116 | val 0.71929
  Classification -> best τ=0.385 (val F1=0.3525)
  Directional -> Accuracy: 0.6515, MCC: 0.3164, F1: 0.6667

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.64421 | val 0.70787
  Epoch 019 - train 0.61624 | val 0.82639
  Classification -> best τ=0.540 (val F1=0.2652)
  Directional -> Accuracy: 0.5000, MCC: 0.0561, F1: 0.2222

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.65079 | val 0.74015
  Epoch 020 - train 0.61627 | val 0.79544
  Classification -> best τ=0.485 (val F1=0.2755)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.4815

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.62042 | val 0.99171
  Epoch 016 - train 0.60217 | val 1.28171
  Classification -> best τ=0.505 (val F1=0.2441)
  Directional -> Accuracy: 0.3913, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.68582 | val 0.67196
  Epoch 020 - train 0.62181 | val 0.65013
  Epoch 030 - train 0.56834 | val 0.63988
  Epoch 040 - train 0.55413 | val 0.63502
  Epoch 050 - train 0.56975 | val 0.62658
  Classification -> best τ=0.310 (val F1=0.5617)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.68239 | val 0.69993
  Epoch 016 - train 0.66159 | val 0.73977
  Classification -> best τ=0.470 (val F1=0.3801)
  Directional -> Accuracy: 0.5676, MCC: 0.1947, F1: 0.4667

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.63255 | val 0.68856
  Epoch 019 - train 0.62322 | val 0.71158
  Classification -> best τ=0.535 (val F1=0.2148)
  Directional -> Accuracy: 0.5200, MCC: 0.1633, F1: 0.6727

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.66516 | val 0.67833
  Epoch 020 - train 0.64809 | val 0.70110
  Epoch 022 - train 0.65944 | val 0.70098
  Classification -> best τ=0.430 (val F1=0.3560)
  Directional -> Accuracy: 0.5652, MCC: 0.1461, F1: 0.6875

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.60257 | val 0.71228
  Epoch 016 - train 0.59211 | val 0.74441
  Classification -> best τ=0.490 (val F1=0.0250)
  Directional -> Accuracy: 0.5581, MCC: 0.1778, F1: 0.4865

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.65183 | val 0.72009
  Epoch 016 - train 0.61219 | val 0.71160
  Classification -> best τ=0.480 (val F1=0.1186)
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.65048 | val 0.97533
  Epoch 016 - train 0.63928 | val 1.11730
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.62753 | val 0.82222
  Epoch 016 - train 0.61619 | val 0.85656
  Classification -> best τ=0.545 (val F1=0.0572)
  Directional -> Accuracy: 0.4821, MCC: -0.0413, F1: 0.4314

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.66709 | val 1.01098
  Epoch 016 - train 0.62923 | val 1.20630
  Classification -> best τ=0.505 (val F1=0.2078)
  Directional -> Accuracy: 0.5741, MCC: 0.1437, F1: 0.6349

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.61722 | val 0.90505
  Epoch 016 - train 0.61902 | val 1.06374
  Classification -> best τ=0.555 (val F1=0.1145)
  Directional -> Accuracy: 0.4643, MCC: -0.1486, F1: 0.6154

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.65772 | val 0.88725

[I 2026-02-25 02:55:08,428] Trial 173 finished with value: 0.19133898454642226 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 0.0001436593880571436, 'weight_decay': 0.0002920946792063764, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 0.5173518579830966, 'early_stopping_min_delta': 0.0030884263384694547}. Best is trial 164 with value: 0.2973019295845425.

  Epoch 016 - train 0.63023 | val 0.72609
  Classification -> best τ=0.495 (val F1=0.0522)
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.19133898454642226
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.65352 | val 0.95313
  Epoch 020 - train 0.57656 | val 1.26755
  Classification -> best τ=0.675 (val F1=0.2510)
  Directional -> Accuracy: 0.5395, MCC: -0.0253, F1: 0.1026

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.64956 | val 0.76741
  Epoch 020 - train 0.59679 | val 0.94520
  Epoch 021 - train 0.54247 | val 1.06389
  Classification -> best τ=0.510 (val F1=0.2431)
  Directional -> Accuracy: 0.6889, MCC: 0.3728, F1: 0.7200

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.67836 | val 0.73328
  Epoch 019 - train 0.63098 | val 0.79560
  Classification -> best τ=0.365 (val F1=0.3251)
  Directional -> Accuracy: 0.5106, MCC: -0.0705, F1: 0.6667

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.64616 | val 1.53873
  Epoch 016 - train 0.62805 | val 1.29063
  Classification -> best τ=0.345 (val F1=0.1691)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.58221 | val 0.74005
  Epoch 020 - train 0.55521 | val 0.95588
  Epoch 021 - train 0.49637 | val 0.93173
  Classification -> best τ=0.625 (val F1=0.4121)
  Directional -> Accuracy: 0.3529, MCC: -0.3989, F1: 0.5075

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.60472 | val 1.12200
  Epoch 020 - train 0.52586 | val 1.36009
  Epoch 026 - train 0.51101 | val 2.09236
  Classification -> best τ=0.675 (val F1=0.2335)
  Directional -> Accuracy: 0.4894, MCC: -0.1443, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.66047 | val 0.70901
  Epoch 016 - train 0.66504 | val 0.81383
  Classification -> best τ=0.485 (val F1=0.2301)
  Directional -> Accuracy: 0.4493, MCC: 0.1171, F1: 0.5870

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.62654 | val 1.59443
  Epoch 016 - train 0.58211 | val 1.25589
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.5902

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.66459 | val 1.59774
  Epoch 019 - train 0.53273 | val 1.81197
  Classification -> best τ=0.345 (val F1=0.2820)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.64223 | val 0.83724
  Epoch 020 - train 0.57069 | val 2.40621
  Epoch 023 - train 0.52752 | val 2.53638
  Classification -> best τ=0.500 (val F1=0.2220)
  Directional -> Accuracy: 0.4714, MCC: -0.0172, F1: 0.5067

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.56683 | val 2.49581
  Epoch 016 - train 0.59952 | val 2.48634
  Classification -> best τ=0.685 (val F1=0.1750)
  Directional -> Accuracy: 0.5400, MCC: 0.0296, F1: 0.2069

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.58347 | val 1.07176
  Epoch 016 - train 0.55628 | val 1.74689
  Classification -> best τ=0.435 (val F1=0.1942)
  Directional -> Accuracy: 0.6207, MCC: 0.2572, F1: 0.5417

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.62302 | val 1.29205
  Epoch 017 - train 0.61141 | val 0.92699
  Classification -> best τ=0.545 (val F1=0.2323)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.66860 | val 0.77447
  Epoch 017 - train 0.62693 | val 0.69866
  Classification -> best τ=0.510 (val F1=0.3118)
  Directional -> Accuracy: 0.5667, MCC: 0.1361, F1: 0.6061

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.61641 | val 1.75320
  Epoch 016 - train 0.59366 | val 1.93195
  Classification -> best τ=0.545 (val F1=0.2160)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.63943 | val 0.82911
  Epoch 017 - train 0.57914 | val 0.81454
  Classification -> best τ=0.350 (val F1=0.3015)
  Directional -> Accuracy: 0.6087, MCC: 0.3006, F1: 0.7327

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.62661 | val 2.22111
  Epoch 016 - train 0.58847 | val 3.45261
  Classification -> best τ=0.320 (val F1=0.1905)
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.66443 | val 1.26709
  Epoch 016 - train 0.62852 | val 1.46858
  Classification -> best τ=0.490 (val F1=0.1537)
  Directional -> Accuracy: 0.3733, MCC: -0.1784, F1: 0.2540

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.65298 | val 1.32062
  Epoch 017 - train 0.61134 | val 2.42663
  Classification -> best τ=0.325 (val F1=0.2522)
  Directional -> Accuracy: 0.5385, MCC: -0.1854, F1: 0.7000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.64158 | val 0.74049
  Epoch 020 - train 0.61751 | val 0.99132
  Epoch 029 - train 0.55554 | val 1.35394
  Classification -> best τ=0.415 (val F1=0.3755)
  Directional -> Accuracy: 0.6000, MCC: 0.1781, F1: 0.6939

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.68883 | val 0.72418
  Epoch 018 - train 0.54553 | val 0.76008
  Classification -> best τ=0.640 (val F1=0.1918)
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.66441 | val 0.94441
  Epoch 016 - train 0.64658 | val 1.07612
  Classification -> best τ=0.500 (val F1=0.1782)
  Directional -> Accuracy: 0.5152, MCC: 0.0492, F1: 0.6522

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.65787 | val 0.79643
  Epoch 016 - train 0.63812 | val 0.79535
  Classification -> best τ=0.570 (val F1=0.2554)
  Directional -> Accuracy: 0.5172, MCC: 0.0762, F1: 0.4815

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.64060 | val 0.79906
  Epoch 017 - train 0.61797 | val 0.81967
  Classification -> best τ=0.455 (val F1=0.1693)
  Directional -> Accuracy: 0.5077, MCC: 0.0190, F1: 0.5152

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.61599 | val 0.79679
  Epoch 020 - train 0.53811 | val 0.74394
  Epoch 029 - train 0.46673 | val 0.86905
  Classification -> best τ=0.375 (val F1=0.4663)
  Directional -> Accuracy: 0.5357, MCC: 0.1728, F1: 0.3810

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.60145 | val 0.75269
  Epoch 016 - train 0.64012 | val 1.00297
  Classification -> best τ=0.510 (val F1=0.2935)
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.67358 | val 0.71868
  Epoch 020 - train 0.64850 | val 0.68431
  Epoch 030 - train 0.57072 | val 0.89740
  Epoch 035 - train 0.55289 | val 1.52098
  Classification -> best τ=0.605 (val F1=0.1936)
  Directional -> Accuracy: 0.5000, MCC: 0.1005, F1: 0.3636

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.63589 | val 1.18929
  Epoch 019 - train 0.57367 | val 1.02588
  Classification -> best τ=0.400 (val F1=0.2391)
  Directional -> Accuracy: 0.5263, MCC: 0.2741, F1: 0.2703

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.68366 | val 0.94251
  Epoch 020 - train 0.58469 | val 0.98564
  Epoch 027 - train 0.55979 | val 1.26034
  Classification -> best τ=0.630 (val F1=0.2774)
  Directional -> Accuracy: 0.5854, MCC: 0.1635, F1: 0.6222

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.65737 | val 0.70675
  Epoch 018 - train 0.54156 | val 0.79747
  Classification -> best τ=0.555 (val F1=0.2814)
  Directional -> Accuracy: 0.5349, MCC: 0.0893, F1: 0.6154

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.62073 | val 0.70829
  Epoch 020 - train 0.54599 | val 0.84420
  Classification -> best τ=0.635 (val F1=0.0266)
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.58087 | val 0.96475
  Epoch 018 - train 0.54875 | val 1.32463
  Classification -> best τ=0.635 (val F1=0.2969)
  Directional -> Accuracy: 0.5200, MCC: 0.0401, F1: 0.5385

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.64006 | val 0.81546
  Epoch 020 - train 0.57947 | val 1.27278
  Epoch 022 - train 0.59088 | val 1.76297
  Classification -> best τ=0.320 (val F1=0.2951)
  Directional -> Accuracy: 0.5753, MCC: 0.1768, F1: 0.5634

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.70386 | val 0.87001
  Epoch 016 - train 0.58479 | val 0.99021
  Classification -> best τ=0.355 (val F1=0.3651)
  Directional -> Accuracy: 0.5405, MCC: 0.0904, F1: 0.5854

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.63855 | val 1.15046
  Epoch 016 - train 0.61131 | val 1.01961
  Classification -> best τ=0.480 (val F1=0.1902)
  Directional -> Accuracy: 0.5455, MCC: 0.1041, F1: 0.5833

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.63743 | val 0.71980
  Epoch 017 - train 0.60728 | val 0.83390
  Classification -> best τ=0.515 (val F1=0.2294)
  Directional -> Accuracy: 0.5909, MCC: 0.1587, F1: 0.6494

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.55472 | val 1.23983
  Epoch 016 - train 0.54430 | val 1.37089
  Classification -> best τ=0.590 (val F1=0.1716)
  Directional -> Accuracy: 0.5000, MCC: 0.0561, F1: 0.2222

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.65086 | val 1.07130
  Epoch 016 - train 0.66420 | val 1.23588
  Classification -> best τ=0.405 (val F1=0.2804)
  Directional -> Accuracy: 0.5179, MCC: 0.2215, F1: 0.6582

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.59696 | val 1.74651
  Epoch 016 - train 0.52816 | val 2.73770
  Classification -> best τ=0.550 (val F1=0.2441)
  Directional -> Accuracy: 0.5870, MCC: 0.0062, F1: 0.7246

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.67119 | val 0.60665
  Epoch 020 - train 0.52784 | val 0.64318
  Epoch 025 - train 0.57335 | val 0.61930
  Classification -> best τ=0.355 (val F1=0.4188)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.65339 | val 0.80437
  Epoch 020 - train 0.53377 | val 1.00257
  Epoch 022 - train 0.51931 | val 1.31337
  Classification -> best τ=0.510 (val F1=0.2623)
  Directional -> Accuracy: 0.5676, MCC: 0.1479, F1: 0.5556

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.60946 | val 0.88471
  Epoch 018 - train 0.55831 | val 1.25995
  Classification -> best τ=0.505 (val F1=0.4662)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.66456 | val 0.72297
  Epoch 018 - train 0.56451 | val 0.80594
  Classification -> best τ=0.400 (val F1=0.3989)
  Directional -> Accuracy: 0.5652, MCC: 0.1881, F1: 0.4118

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.55225 | val 0.76681
  Epoch 016 - train 0.65091 | val 1.13443
  Classification -> best τ=0.545 (val F1=0.2530)
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.57862 | val 0.72962
  Epoch 020 - train 0.53238 | val 0.77308
  Epoch 021 - train 0.56631 | val 0.84598
  Classification -> best τ=0.675 (val F1=0.6290)
  Directional -> Accuracy: 0.5714, MCC: 0.0887, F1: 0.4324

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.69118 | val 1.08409
  Epoch 017 - train 0.61880 | val 2.05781
  Classification -> best τ=0.475 (val F1=0.1548)
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.62496 | val 1.18653
  Epoch 016 - train 0.59531 | val 1.24263
  Classification -> best τ=0.440 (val F1=0.2500)
  Directional -> Accuracy: 0.5357, MCC: 0.0620, F1: 0.3810

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.67719 | val 1.43957
  Epoch 016 - train 0.60846 | val 1.67788
  Classification -> best τ=0.370 (val F1=0.2079)
  Directional -> Accuracy: 0.5556, MCC: 0.1520, F1: 0.6923

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.62353 | val 1.81629
  Epoch 017 - train 0.56504 | val 2.31935
  Classification -> best τ=0.540 (val F1=0.2764)
  Directional -> Accuracy: 0.5536, MCC: 0.1995, F1: 0.6988

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.58521 | val 0.71058

[I 2026-02-25 02:57:23,604] Trial 174 finished with value: 0.25828830226906585 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 0.003957766301951544, 'weight_decay': 0.0003188751082122586, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 0.742741049224955, 'early_stopping_min_delta': 0.0037877630371961728}. Best is trial 164 with value: 0.2973019295845425.

  Epoch 016 - train 0.60701 | val 1.00983
  Classification -> best τ=0.435 (val F1=0.1811)
  Directional -> Accuracy: 0.4918, MCC: -0.0781, F1: 0.1622

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.25828830226906585
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.64304 | val 0.77660
  Epoch 016 - train 0.64461 | val 1.09291
  Classification -> best τ=0.440 (val F1=0.2759)
  Directional -> Accuracy: 0.4342, MCC: -0.0832, F1: 0.5567

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.60746 | val 0.77524
  Epoch 016 - train 0.55648 | val 0.98876
  Classification -> best τ=0.340 (val F1=0.1870)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.65517 | val 0.69806
  Epoch 020 - train 0.62168 | val 0.83140
  Epoch 021 - train 0.60007 | val 0.79174
  Classification -> best τ=0.300 (val F1=0.3693)
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.65825 | val 1.40789
  Epoch 017 - train 0.67016 | val 1.44007
  Classification -> best τ=0.275 (val F1=0.1730)
  Directional -> Accuracy: 0.5200, MCC: 0.0573, F1: 0.5000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.57080 | val 1.16963
  Epoch 019 - train 0.54024 | val 1.21587
  Classification -> best τ=0.560 (val F1=0.3795)
  Directional -> Accuracy: 0.5098, MCC: 0.0231, F1: 0.5098

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.63625 | val 0.76349
  Epoch 016 - train 0.53361 | val 1.09330
  Classification -> best τ=0.625 (val F1=0.2357)
  Directional -> Accuracy: 0.5957, MCC: 0.2632, F1: 0.3448

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.67366 | val 0.70907
  Epoch 016 - train 0.64108 | val 0.83319
  Classification -> best τ=0.390 (val F1=0.2004)
  Directional -> Accuracy: 0.4493, MCC: 0.1171, F1: 0.5870

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.68435 | val 0.81868
  Epoch 020 - train 0.52875 | val 0.98868
  Epoch 021 - train 0.50947 | val 0.90599
  Classification -> best τ=0.265 (val F1=0.1752)
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.5902

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.61057 | val 1.47650
  Epoch 018 - train 0.51873 | val 1.39305
  Classification -> best τ=0.470 (val F1=0.2265)
  Directional -> Accuracy: 0.7143, MCC: 0.4191, F1: 0.6667

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.61423 | val 0.73719
  Epoch 020 - train 0.57083 | val 1.25396
  Epoch 027 - train 0.55240 | val 2.18244
  Classification -> best τ=0.410 (val F1=0.1816)
  Directional -> Accuracy: 0.4571, MCC: 0.0236, F1: 0.5778

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.62051 | val 2.49779
  Epoch 017 - train 0.61063 | val 2.35622
  Classification -> best τ=0.405 (val F1=0.1480)
  Directional -> Accuracy: 0.5800, MCC: 0.1391, F1: 0.4000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.64583 | val 0.92606
  Epoch 017 - train 0.62551 | val 1.23019
  Classification -> best τ=0.695 (val F1=0.3062)
  Directional -> Accuracy: 0.5345, MCC: 0.1890, F1: 0.1290

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.63221 | val 0.84212
  Epoch 017 - train 0.57307 | val 1.01124
  Classification -> best τ=0.445 (val F1=0.2323)
  Directional -> Accuracy: 0.4286, MCC: -0.1090, F1: 0.5714

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.64400 | val 0.73263
  Epoch 016 - train 0.65156 | val 0.74174
  Classification -> best τ=0.550 (val F1=0.2213)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.2105

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.60571 | val 1.29430
  Epoch 016 - train 0.58664 | val 2.19664
  Classification -> best τ=0.470 (val F1=0.2160)
  Directional -> Accuracy: 0.5385, MCC: 0.0376, F1: 0.2941

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.62521 | val 0.75992
  Epoch 020 - train 0.60779 | val 0.98217
  Epoch 022 - train 0.61248 | val 0.98026
  Classification -> best τ=0.355 (val F1=0.3541)
  Directional -> Accuracy: 0.5507, MCC: 0.0753, F1: 0.6517

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.63710 | val 2.33181
  Epoch 016 - train 0.62721 | val 2.12795
  Classification -> best τ=0.475 (val F1=0.0543)
  Directional -> Accuracy: 0.4576, MCC: -0.0832, F1: 0.5152

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.67073 | val 2.50563
  Epoch 016 - train 0.62432 | val 1.58311
  Classification -> best τ=0.470 (val F1=0.2083)
  Directional -> Accuracy: 0.5467, MCC: 0.1091, F1: 0.5750

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.64510 | val 1.04919
  Epoch 018 - train 0.63991 | val 2.20909
  Classification -> best τ=0.525 (val F1=0.2868)
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.64752 | val 0.66414
  Epoch 020 - train 0.61594 | val 0.84890
  Epoch 025 - train 0.58149 | val 1.35124
  Classification -> best τ=0.415 (val F1=0.3336)
  Directional -> Accuracy: 0.4667, MCC: 0.0492, F1: 0.0909

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.60766 | val 0.87387
  Epoch 020 - train 0.55208 | val 0.68837
  Epoch 023 - train 0.50672 | val 0.74828
  Classification -> best τ=0.625 (val F1=0.3496)
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.72435 | val 0.97536
  Epoch 016 - train 0.65042 | val 1.06772
  Classification -> best τ=0.410 (val F1=0.1920)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.66739 | val 1.00773
  Epoch 020 - train 0.65216 | val 0.73254
  Epoch 027 - train 0.60665 | val 0.96766
  Classification -> best τ=0.615 (val F1=0.3286)
  Directional -> Accuracy: 0.4655, MCC: 0.0453, F1: 0.2439

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.67330 | val 0.70089
  Epoch 020 - train 0.61910 | val 1.40035
  Epoch 024 - train 0.58799 | val 1.28354
  Classification -> best τ=0.440 (val F1=0.2609)
  Directional -> Accuracy: 0.4769, MCC: 0.0000, F1: 0.6458

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.64876 | val 0.71997
  Epoch 017 - train 0.57883 | val 0.79262
  Classification -> best τ=0.625 (val F1=0.4352)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.59665 | val 1.04616
  Epoch 016 - train 0.56406 | val 3.17079
  Classification -> best τ=0.565 (val F1=0.2935)
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.65437 | val 0.68481
  Epoch 017 - train 0.65257 | val 0.92552
  Classification -> best τ=0.590 (val F1=0.3184)
  Directional -> Accuracy: 0.5476, MCC: 0.1434, F1: 0.5128

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.63776 | val 0.79557
  Epoch 017 - train 0.62284 | val 0.83032
  Classification -> best τ=0.385 (val F1=0.3370)
  Directional -> Accuracy: 0.5263, MCC: 0.2230, F1: 0.3077

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.67001 | val 0.68822
  Epoch 020 - train 0.62344 | val 0.88874
  Classification -> best τ=0.525 (val F1=0.4109)
  Directional -> Accuracy: 0.5366, MCC: 0.0241, F1: 0.6780

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.65408 | val 0.70236
  Epoch 016 - train 0.61951 | val 0.89936
  Classification -> best τ=0.480 (val F1=0.2559)
  Directional -> Accuracy: 0.5116, MCC: 0.0288, F1: 0.5532

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.64680 | val 0.73400
  Epoch 017 - train 0.61195 | val 0.83004
  Classification -> best τ=0.620 (val F1=0.1204)
  Directional -> Accuracy: 0.4419, MCC: -0.0933, F1: 0.2500

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.58626 | val 0.97839
  Epoch 016 - train 0.54384 | val 1.21433
  Classification -> best τ=0.620 (val F1=0.3917)
  Directional -> Accuracy: 0.4800, MCC: 0.0401, F1: 0.1875

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.62099 | val 0.71295
  Epoch 020 - train 0.61267 | val 1.05361
  Classification -> best τ=0.330 (val F1=0.3809)
  Directional -> Accuracy: 0.5616, MCC: 0.1368, F1: 0.5676

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.62831 | val 0.87055
  Epoch 017 - train 0.63033 | val 1.06428
  Classification -> best τ=0.440 (val F1=0.3651)
  Directional -> Accuracy: 0.5405, MCC: 0.0855, F1: 0.5641

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.65952 | val 0.97387
  Epoch 016 - train 0.56539 | val 1.39575
  Classification -> best τ=0.475 (val F1=0.2358)
  Directional -> Accuracy: 0.4545, MCC: -0.1026, F1: 0.6129

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.65363 | val 0.67596
  Epoch 018 - train 0.57882 | val 0.95434
  Classification -> best τ=0.325 (val F1=0.3525)
  Directional -> Accuracy: 0.5606, MCC: 0.2072, F1: 0.4912

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.59201 | val 1.23315
  Epoch 017 - train 0.61957 | val 1.43622
  Classification -> best τ=0.480 (val F1=0.2206)
  Directional -> Accuracy: 0.6905, MCC: 0.3977, F1: 0.6667

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.63128 | val 1.02090
  Epoch 016 - train 0.60055 | val 1.11793
  Classification -> best τ=0.475 (val F1=0.1913)
  Directional -> Accuracy: 0.5714, MCC: 0.1432, F1: 0.5556

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.64062 | val 1.33839
  Epoch 016 - train 0.58299 | val 1.84427
  Classification -> best τ=0.520 (val F1=0.3451)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.63355 | val 0.66102
  Epoch 020 - train 0.60160 | val 0.72681
  Epoch 021 - train 0.57368 | val 0.67188
  Classification -> best τ=0.565 (val F1=0.3894)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.62491 | val 0.95685
  Epoch 016 - train 0.60256 | val 0.96829
  Classification -> best τ=0.510 (val F1=0.0585)
  Directional -> Accuracy: 0.5405, MCC: 0.0985, F1: 0.5143

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.60183 | val 0.94029
  Epoch 017 - train 0.58519 | val 1.20636
  Classification -> best τ=0.465 (val F1=0.3880)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.65143 | val 0.75246
  Epoch 018 - train 0.58592 | val 0.84747
  Classification -> best τ=0.405 (val F1=0.3677)
  Directional -> Accuracy: 0.5217, MCC: 0.0169, F1: 0.6562

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.59030 | val 0.93210
  Epoch 016 - train 0.53249 | val 0.98037
  Classification -> best τ=0.595 (val F1=0.3651)
  Directional -> Accuracy: 0.4186, MCC: -0.1155, F1: 0.1379

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.64304 | val 0.83065
  Epoch 018 - train 0.59145 | val 0.86311
  Classification -> best τ=0.510 (val F1=0.2464)
  Directional -> Accuracy: 0.5714, MCC: 0.2560, F1: 0.6038

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.66855 | val 1.25852
  Epoch 018 - train 0.60463 | val 1.17435
  Classification -> best τ=0.530 (val F1=0.3924)
  Directional -> Accuracy: 0.4464, MCC: -0.1448, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.64900 | val 0.79087
  Epoch 020 - train 0.60409 | val 0.94308
  Classification -> best τ=0.695 (val F1=0.3622)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.63203 | val 1.08675
  Epoch 018 - train 0.58604 | val 2.53938
  Classification -> best τ=0.475 (val F1=0.1626)
  Directional -> Accuracy: 0.5926, MCC: 0.1906, F1: 0.5769

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.62932 | val 2.30376
  Epoch 016 - train 0.66660 | val 1.68889
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.62378 | val 0.71043
  Epoch 020 - train 0.60721 | val 0.72107
  Epoch 030 - train 0.58890 | val 0.86600

[I 2026-02-25 02:59:40,118] Trial 175 finished with value: 0.27080726768977054 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 0.005231882726270045, 'weight_decay': 0.0004895447576785847, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 0.42416446095778443, 'early_stopping_min_delta': 0.002995846962934641}. Best is trial 164 with value: 0.2973019295845425.

  Epoch 033 - train 0.54978 | val 0.97541
  Classification -> best τ=0.355 (val F1=0.2575)
  Directional -> Accuracy: 0.4590, MCC: -0.1356, F1: 0.6292

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.27080726768977054
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.67488 | val 1.03929
  Epoch 016 - train 0.64025 | val 0.98994
  Classification -> best τ=0.595 (val F1=0.2510)
  Directional -> Accuracy: 0.5526, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.66322 | val 0.73606
  Epoch 020 - train 0.57122 | val 0.72621
  Epoch 022 - train 0.58199 | val 0.76631
  Classification -> best τ=0.695 (val F1=0.2431)
  Directional -> Accuracy: 0.6667, MCC: 0.3002, F1: 0.7368

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.70206 | val 0.70828
  Epoch 016 - train 0.62472 | val 0.79033
  Classification -> best τ=0.415 (val F1=0.3732)
  Directional -> Accuracy: 0.6596, MCC: 0.4078, F1: 0.7576

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.64448 | val 1.48902
  Epoch 016 - train 0.65034 | val 1.65633
  Classification -> best τ=0.310 (val F1=0.1868)
  Directional -> Accuracy: 0.5200, MCC: 0.0414, F1: 0.5385

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.59738 | val 0.76362
  Epoch 020 - train 0.53592 | val 0.89825
  Classification -> best τ=0.575 (val F1=0.4087)
  Directional -> Accuracy: 0.5294, MCC: 0.0172, F1: 0.6757

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.57913 | val 0.69807
  Epoch 020 - train 0.58192 | val 0.92529
  Epoch 021 - train 0.55530 | val 0.81737
  Classification -> best τ=0.485 (val F1=0.2928)
  Directional -> Accuracy: 0.5745, MCC: 0.1828, F1: 0.6552

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.65992 | val 0.72532
  Epoch 017 - train 0.63976 | val 0.83905
  Classification -> best τ=0.285 (val F1=0.2041)
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.63023 | val 0.89246
  Epoch 016 - train 0.57569 | val 1.39764
  Classification -> best τ=0.415 (val F1=0.1266)
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.66319 | val 0.76859
  Epoch 020 - train 0.60681 | val 0.82408
  Epoch 030 - train 0.53938 | val 1.32698
  Classification -> best τ=0.365 (val F1=0.3641)
  Directional -> Accuracy: 0.6735, MCC: 0.3557, F1: 0.6667

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.63185 | val 0.70794
  Epoch 017 - train 0.56058 | val 0.80365
  Classification -> best τ=0.425 (val F1=0.2433)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.63266 | val 1.59989
  Epoch 016 - train 0.58086 | val 1.57875
  Classification -> best τ=0.540 (val F1=0.1750)
  Directional -> Accuracy: 0.5000, MCC: -0.1884, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.63658 | val 1.02534
  Epoch 017 - train 0.58700 | val 1.43271
  Classification -> best τ=0.465 (val F1=0.2013)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.59967 | val 0.96431
  Epoch 020 - train 0.59323 | val 0.82759
  Epoch 023 - train 0.52743 | val 0.92745
  Classification -> best τ=0.405 (val F1=0.2246)
  Directional -> Accuracy: 0.5952, MCC: 0.2835, F1: 0.6667

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.66830 | val 0.78313
  Epoch 020 - train 0.59982 | val 1.21066
  Epoch 021 - train 0.62893 | val 1.13956
  Classification -> best τ=0.480 (val F1=0.3387)
  Directional -> Accuracy: 0.5333, MCC: 0.0668, F1: 0.5484

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.65067 | val 0.83636
  Epoch 017 - train 0.55171 | val 2.75565
  Classification -> best τ=0.585 (val F1=0.2160)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.66230 | val 0.95337
  Epoch 016 - train 0.58885 | val 0.99135
  Classification -> best τ=0.535 (val F1=0.2723)
  Directional -> Accuracy: 0.4928, MCC: -0.0220, F1: 0.5333

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.65504 | val 1.92799
  Epoch 016 - train 0.61991 | val 2.07911
  Classification -> best τ=0.370 (val F1=0.0103)
  Directional -> Accuracy: 0.6271, MCC: 0.1604, F1: 0.7250

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.66439 | val 1.35132
  Epoch 018 - train 0.62995 | val 1.68250
  Classification -> best τ=0.305 (val F1=0.1733)
  Directional -> Accuracy: 0.6267, MCC: 0.1784, F1: 0.7255

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.63728 | val 1.53780
  Epoch 017 - train 0.65457 | val 2.26094
  Classification -> best τ=0.335 (val F1=0.2843)
  Directional -> Accuracy: 0.5385, MCC: 0.2138, F1: 0.4231

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.65061 | val 0.99066
  Epoch 017 - train 0.60093 | val 1.32462
  Classification -> best τ=0.460 (val F1=0.2083)
  Directional -> Accuracy: 0.3467, MCC: -0.2938, F1: 0.2899

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.64845 | val 0.67296
  Epoch 020 - train 0.56323 | val 0.76217
  Epoch 022 - train 0.55518 | val 0.76197
  Classification -> best τ=0.585 (val F1=0.3427)
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.67181 | val 0.86335
  Epoch 016 - train 0.63055 | val 1.24428
  Classification -> best τ=0.465 (val F1=0.1167)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.66939 | val 0.73417
  Epoch 019 - train 0.64145 | val 0.79858
  Classification -> best τ=0.500 (val F1=0.3095)
  Directional -> Accuracy: 0.4483, MCC: -0.0514, F1: 0.3600

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.66948 | val 0.90432
  Epoch 017 - train 0.58790 | val 1.30937
  Classification -> best τ=0.445 (val F1=0.2737)
  Directional -> Accuracy: 0.4923, MCC: 0.0336, F1: 0.6292

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.68372 | val 0.71504
  Epoch 020 - train 0.58109 | val 0.69509
  Epoch 028 - train 0.52975 | val 0.72687
  Classification -> best τ=0.500 (val F1=0.3824)
  Directional -> Accuracy: 0.5536, MCC: 0.1704, F1: 0.4681

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.65762 | val 1.39027
  Epoch 016 - train 0.57614 | val 1.64447
  Classification -> best τ=0.545 (val F1=0.2035)
  Directional -> Accuracy: 0.4565, MCC: 0.0245, F1: 0.5902

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.68476 | val 0.72643
  Epoch 020 - train 0.63237 | val 1.30374
  Classification -> best τ=0.480 (val F1=0.1803)
  Directional -> Accuracy: 0.5000, MCC: -0.0782, F1: 0.6182

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.65296 | val 0.84114
  Epoch 017 - train 0.59262 | val 0.87270
  Classification -> best τ=0.445 (val F1=0.2789)
  Directional -> Accuracy: 0.5789, MCC: 0.1613, F1: 0.6000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.65773 | val 1.56205
  Epoch 017 - train 0.57293 | val 0.82765
  Classification -> best τ=0.475 (val F1=0.3518)
  Directional -> Accuracy: 0.5610, MCC: 0.0983, F1: 0.6786

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.63394 | val 1.26753
  Epoch 020 - train 0.55310 | val 1.98328
  Classification -> best τ=0.595 (val F1=0.2814)
  Directional -> Accuracy: 0.5349, MCC: 0.0693, F1: 0.5238

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.63713 | val 0.76658
  Epoch 020 - train 0.58501 | val 0.86768
  Classification -> best τ=0.655 (val F1=0.1204)
  Directional -> Accuracy: 0.3953, MCC: -0.2435, F1: 0.0714

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.60802 | val 0.85122
  Epoch 016 - train 0.55246 | val 1.06851
  Classification -> best τ=0.565 (val F1=0.2399)
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.65473 | val 0.80538
  Epoch 016 - train 0.61671 | val 0.79433
  Classification -> best τ=0.440 (val F1=0.2654)
  Directional -> Accuracy: 0.5342, MCC: 0.1465, F1: 0.4333

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.65691 | val 0.82616
  Epoch 016 - train 0.56219 | val 1.04827
  Classification -> best τ=0.470 (val F1=0.2887)
  Directional -> Accuracy: 0.5676, MCC: 0.1599, F1: 0.6364

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.62335 | val 0.90999
  Epoch 018 - train 0.57282 | val 1.22974
  Classification -> best τ=0.570 (val F1=0.3902)
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.64717 | val 0.78690
  Epoch 016 - train 0.58750 | val 0.84079
  Classification -> best τ=0.440 (val F1=0.4073)
  Directional -> Accuracy: 0.4697, MCC: 0.1299, F1: 0.1860

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.62678 | val 1.32344
  Epoch 019 - train 0.55934 | val 1.22390
  Classification -> best τ=0.455 (val F1=0.2819)
  Directional -> Accuracy: 0.6905, MCC: 0.3977, F1: 0.6667

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.62183 | val 0.82343
  Epoch 018 - train 0.57843 | val 1.57602
  Classification -> best τ=0.650 (val F1=0.2305)
  Directional -> Accuracy: 0.5179, MCC: -0.0625, F1: 0.0690

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.59480 | val 1.63905
  Epoch 016 - train 0.56099 | val 2.01603
  Classification -> best τ=0.495 (val F1=0.3146)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.70068 | val 1.30074
  Epoch 020 - train 0.60379 | val 0.66762
  Epoch 030 - train 0.53991 | val 0.66325
  Classification -> best τ=0.225 (val F1=0.4708)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.64228 | val 0.84045
  Epoch 016 - train 0.64310 | val 1.11399
  Classification -> best τ=0.475 (val F1=0.0598)
  Directional -> Accuracy: 0.4595, MCC: -0.1251, F1: 0.5652

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.60980 | val 0.75971
  Epoch 017 - train 0.60129 | val 1.08222
  Classification -> best τ=0.425 (val F1=0.3068)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.67359 | val 0.73787
  Epoch 020 - train 0.58987 | val 0.75026
  Epoch 026 - train 0.59652 | val 0.70050
  Classification -> best τ=0.385 (val F1=0.2793)
  Directional -> Accuracy: 0.5000, MCC: -0.0334, F1: 0.6230

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.64786 | val 0.87396
  Epoch 019 - train 0.58835 | val 1.37245
  Classification -> best τ=0.555 (val F1=0.3294)
  Directional -> Accuracy: 0.5116, MCC: 0.0261, F1: 0.5333

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.61667 | val 0.80650
  Epoch 020 - train 0.55928 | val 0.79104
  Epoch 030 - train 0.49779 | val 0.89615
  Epoch 038 - train 0.44562 | val 1.10608
  Classification -> best τ=0.275 (val F1=0.5514)
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.67350 | val 1.01049
  Epoch 018 - train 0.63436 | val 2.14855
  Classification -> best τ=0.565 (val F1=0.0886)
  Directional -> Accuracy: 0.4107, MCC: -0.1666, F1: 0.2326

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.66068 | val 0.89243
  Epoch 016 - train 0.60077 | val 1.10445
  Classification -> best τ=0.565 (val F1=0.4217)
  Directional -> Accuracy: 0.5357, MCC: 0.0994, F1: 0.6176

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.65248 | val 1.44470
  Epoch 016 - train 0.66280 | val 1.24447
  Classification -> best τ=0.435 (val F1=0.2618)
  Directional -> Accuracy: 0.5741, MCC: 0.2517, F1: 0.7089

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.61383 | val 2.15335
  Epoch 017 - train 0.57208 | val 2.34434
  Classification -> best τ=0.515 (val F1=0.1667)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.62538 | val 0.97891
  Epoch 020 - train 0.59948 | val 0.85211
  Epoch 021 - train 0.59118 | val 0.90060

[I 2026-02-25 03:01:53,481] Trial 176 finished with value: 0.2644416131258251 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 0.003178291661115072, 'weight_decay': 0.0008315548442140589, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 0.6116381920910493, 'early_stopping_min_delta': 0.0034617958821499843}. Best is trial 164 with value: 0.2973019295845425.

  Classification -> best τ=0.320 (val F1=0.2283)
  Directional -> Accuracy: 0.4918, MCC: 0.0647, F1: 0.6437

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2644416131258251
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.63102 | val 0.68858
  Epoch 017 - train 0.59460 | val 1.07766
  Classification -> best τ=0.475 (val F1=0.2627)
  Directional -> Accuracy: 0.4079, MCC: -0.1686, F1: 0.4304

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.66501 | val 0.70362
  Epoch 020 - train 0.57092 | val 0.88423
  Epoch 021 - train 0.63103 | val 0.90669
  Classification -> best τ=0.465 (val F1=0.2287)
  Directional -> Accuracy: 0.5556, MCC: 0.0891, F1: 0.6154

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.65818 | val 0.77377
  Epoch 019 - train 0.61655 | val 0.98739
  Classification -> best τ=0.505 (val F1=0.3308)
  Directional -> Accuracy: 0.5106, MCC: 0.0146, F1: 0.5490

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.69723 | val 0.94012
  Epoch 020 - train 0.64595 | val 0.74080
  Epoch 022 - train 0.67996 | val 0.76772
  Classification -> best τ=0.490 (val F1=0.2103)
  Directional -> Accuracy: 0.4667, MCC: 0.0286, F1: 0.1304

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.66580 | val 0.67071
  Epoch 020 - train 0.59068 | val 0.77272
  Epoch 024 - train 0.56894 | val 0.83786
  Classification -> best τ=0.580 (val F1=0.4598)
  Directional -> Accuracy: 0.5490, MCC: 0.0811, F1: 0.6349

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.66082 | val 0.80504
  Epoch 016 - train 0.55581 | val 0.81148
  Classification -> best τ=0.465 (val F1=0.2928)
  Directional -> Accuracy: 0.5532, MCC: 0.1390, F1: 0.6441

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.70670 | val 0.69787
  Epoch 020 - train 0.63866 | val 0.82760
  Epoch 023 - train 0.66187 | val 0.91437
  Classification -> best τ=0.395 (val F1=0.2280)
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.68547 | val 0.70481
  Epoch 020 - train 0.54403 | val 0.69450
  Epoch 030 - train 0.51564 | val 1.03629
  Epoch 031 - train 0.53138 | val 1.04507
  Classification -> best τ=0.365 (val F1=0.1590)
  Directional -> Accuracy: 0.5116, MCC: 0.0044, F1: 0.4324

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.64232 | val 0.68732
  Epoch 020 - train 0.58433 | val 0.82597
  Epoch 021 - train 0.55422 | val 0.88068
  Classification -> best τ=0.405 (val F1=0.2408)
  Directional -> Accuracy: 0.4898, MCC: 0.1862, F1: 0.6377

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.63738 | val 0.71014
  Epoch 018 - train 0.59127 | val 0.79453
  Classification -> best τ=0.505 (val F1=0.1816)
  Directional -> Accuracy: 0.4714, MCC: 0.0000, F1: 0.5316

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.65757 | val 0.68442
  Epoch 018 - train 0.62365 | val 1.10298
  Classification -> best τ=0.430 (val F1=0.2673)
  Directional -> Accuracy: 0.5400, MCC: 0.0602, F1: 0.4390

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.64669 | val 0.80655
  Epoch 016 - train 0.59214 | val 1.01162
  Classification -> best τ=0.400 (val F1=0.3029)
  Directional -> Accuracy: 0.6034, MCC: 0.2080, F1: 0.6230

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.68761 | val 0.79577
  Epoch 016 - train 0.62812 | val 1.06468
  Classification -> best τ=0.385 (val F1=0.2323)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.72723 | val 0.62513
  Epoch 020 - train 0.65105 | val 0.72808
  Epoch 029 - train 0.59617 | val 0.90295
  Classification -> best τ=0.405 (val F1=0.3407)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.65823 | val 0.86034
  Epoch 018 - train 0.61484 | val 1.26439
  Classification -> best τ=0.570 (val F1=0.2673)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.65571 | val 0.85198
  Epoch 020 - train 0.61392 | val 1.32447
  Epoch 022 - train 0.56776 | val 1.42107
  Classification -> best τ=0.390 (val F1=0.2850)
  Directional -> Accuracy: 0.5362, MCC: 0.0716, F1: 0.5556

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.67767 | val 0.92635
  Epoch 016 - train 0.64249 | val 0.96045
  Classification -> best τ=0.620 (val F1=0.1842)
  Directional -> Accuracy: 0.3729, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.68513 | val 0.84877
  Epoch 019 - train 0.62088 | val 1.19848
  Classification -> best τ=0.460 (val F1=0.1028)
  Directional -> Accuracy: 0.3867, MCC: -0.1123, F1: 0.1154

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.67105 | val 1.07776
  Epoch 016 - train 0.63969 | val 1.86339
  Classification -> best τ=0.355 (val F1=0.2522)
  Directional -> Accuracy: 0.5692, MCC: 0.1227, F1: 0.6216

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.70474 | val 0.69992
  Epoch 016 - train 0.64160 | val 0.68949
  Classification -> best τ=0.460 (val F1=0.3006)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.64506 | val 0.69481
  Epoch 020 - train 0.58095 | val 1.02451
  Epoch 027 - train 0.59665 | val 1.41960
  Classification -> best τ=0.365 (val F1=0.3707)
  Directional -> Accuracy: 0.4894, MCC: 0.0958, F1: 0.4286

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.69229 | val 0.78188
  Epoch 018 - train 0.66851 | val 0.76587
  Classification -> best τ=0.495 (val F1=0.1774)
  Directional -> Accuracy: 0.5455, MCC: 0.1004, F1: 0.6250

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.68361 | val 0.76637
  Epoch 017 - train 0.63827 | val 0.86608
  Classification -> best τ=0.550 (val F1=0.2752)
  Directional -> Accuracy: 0.5517, MCC: 0.0951, F1: 0.5938

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.62930 | val 0.68528
  Epoch 020 - train 0.59055 | val 1.05849
  Epoch 026 - train 0.54813 | val 0.97778
  Classification -> best τ=0.505 (val F1=0.2390)
  Directional -> Accuracy: 0.4462, MCC: -0.1111, F1: 0.5909

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.64724 | val 0.65050
  Epoch 020 - train 0.59034 | val 0.68312
  Epoch 029 - train 0.57705 | val 0.76945
  Classification -> best τ=0.415 (val F1=0.4472)
  Directional -> Accuracy: 0.5893, MCC: 0.1440, F1: 0.7013

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.74824 | val 0.77920
  Epoch 016 - train 0.63364 | val 0.94099
  Classification -> best τ=0.420 (val F1=0.2935)
  Directional -> Accuracy: 0.5652, MCC: 0.1989, F1: 0.6154

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.64993 | val 0.69553
  Epoch 016 - train 0.60910 | val 0.74361
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.64603 | val 0.70247
  Epoch 016 - train 0.64283 | val 0.72607
  Classification -> best τ=0.480 (val F1=0.3225)
  Directional -> Accuracy: 0.5263, MCC: 0.2741, F1: 0.2703

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.83634 | val 0.68763
  Epoch 020 - train 0.66198 | val 0.66933
  Epoch 030 - train 0.62297 | val 0.65737
  Epoch 040 - train 0.56984 | val 1.21818
  Epoch 045 - train 0.51427 | val 2.17121
  Classification -> best τ=0.215 (val F1=0.4109)
  Directional -> Accuracy: 0.5122, MCC: -0.1469, F1: 0.6774

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.67075 | val 0.68526
  Epoch 020 - train 0.63119 | val 1.50600
  Classification -> best τ=0.480 (val F1=0.2814)
  Directional -> Accuracy: 0.5349, MCC: 0.0831, F1: 0.6000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.67722 | val 0.64030
  Epoch 020 - train 0.60203 | val 0.66946
  Epoch 029 - train 0.60812 | val 0.66581
  Classification -> best τ=0.725 (val F1=0.2525)
  Directional -> Accuracy: 0.5116, MCC: 0.0426, F1: 0.4615

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.63691 | val 0.74472
  Epoch 018 - train 0.56395 | val 0.93621
  Classification -> best τ=0.430 (val F1=0.3802)
  Directional -> Accuracy: 0.5400, MCC: 0.0350, F1: 0.6667

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.66047 | val 0.65574
  Epoch 020 - train 0.62360 | val 1.03441
  Epoch 025 - train 0.60620 | val 1.00947
  Classification -> best τ=0.350 (val F1=0.2877)
  Directional -> Accuracy: 0.5479, MCC: 0.1207, F1: 0.5352

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.64207 | val 0.77327
  Epoch 016 - train 0.65643 | val 0.82269
  Classification -> best τ=0.475 (val F1=0.5003)
  Directional -> Accuracy: 0.5135, MCC: 0.0910, F1: 0.6538

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.66970 | val 0.84046
  Epoch 016 - train 0.66161 | val 0.83668
  Classification -> best τ=0.460 (val F1=0.2757)
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.65245 | val 0.73726
  Epoch 016 - train 0.63880 | val 0.73794
  Classification -> best τ=0.460 (val F1=0.4073)
  Directional -> Accuracy: 0.5455, MCC: -0.0072, F1: 0.6739

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.67863 | val 0.80624
  Epoch 016 - train 0.65825 | val 0.78507
  Classification -> best τ=0.530 (val F1=0.2251)
  Directional -> Accuracy: 0.6905, MCC: 0.3786, F1: 0.7111

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.62646 | val 0.69757
  Epoch 016 - train 0.62426 | val 0.78163
  Classification -> best τ=0.345 (val F1=0.2450)
  Directional -> Accuracy: 0.4821, MCC: 0.1255, F1: 0.6420

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.70681 | val 0.84941
  Epoch 016 - train 0.58051 | val 1.09871
  Classification -> best τ=0.435 (val F1=0.2066)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.65272 | val 0.74023
  Epoch 018 - train 0.60663 | val 0.77579
  Classification -> best τ=0.470 (val F1=0.2417)
  Directional -> Accuracy: 0.5510, MCC: 0.0111, F1: 0.3529

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.67261 | val 0.70083
  Epoch 019 - train 0.61664 | val 0.92548
  Classification -> best τ=0.540 (val F1=0.2623)
  Directional -> Accuracy: 0.4595, MCC: 0.0000, F1: 0.0000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.67036 | val 0.71125
  Epoch 020 - train 0.58742 | val 1.13828
  Epoch 021 - train 0.59111 | val 1.31206
  Classification -> best τ=0.425 (val F1=0.2831)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.65893 | val 0.68464
  Epoch 016 - train 0.67780 | val 0.74077
  Classification -> best τ=0.425 (val F1=0.3560)
  Directional -> Accuracy: 0.4348, MCC: -0.1461, F1: 0.1333

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.64592 | val 0.67537
  Epoch 020 - train 0.55480 | val 0.66142
  Epoch 030 - train 0.58572 | val 0.66044
  Epoch 040 - train 0.50933 | val 0.77473
  Epoch 042 - train 0.51144 | val 0.98061
  Classification -> best τ=0.330 (val F1=0.5270)
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.7164

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.78287 | val 0.74037
  Epoch 020 - train 0.62960 | val 0.67040
  Epoch 028 - train 0.58257 | val 0.67926
  Classification -> best τ=0.465 (val F1=0.6292)
  Directional -> Accuracy: 0.3673, MCC: -0.1462, F1: 0.5231

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.65304 | val 0.92936
  Epoch 016 - train 0.60023 | val 1.41267
  Classification -> best τ=0.565 (val F1=0.1914)
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.68177 | val 0.88268
  Epoch 018 - train 0.63616 | val 1.57416
  Classification -> best τ=0.535 (val F1=0.2362)
  Directional -> Accuracy: 0.5536, MCC: 0.1700, F1: 0.6575

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.66852 | val 1.01747
  Epoch 018 - train 0.65047 | val 1.50685
  Classification -> best τ=0.480 (val F1=0.2132)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.65299 | val 0.89849
  Epoch 020 - train 0.58355 | val 0.87288
  Epoch 030 - train 0.59197 | val 0.85828
  Epoch 037 - train 0.53648 | val 0.75648
  Classification -> best τ=0.430 (val F1=0.1473)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.70216 | val 0.67815
  Epoch 020 - train 0.65909 | val 0.71930

[I 2026-02-25 03:04:00,358] Trial 177 finished with value: 0.2815761383539693 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 64, 'learning_rate': 0.0044064475718875885, 'weight_decay': 0.00022257298600141868, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 0.35218783429822853, 'early_stopping_min_delta': 0.0040415367610503634}. Best is trial 164 with value: 0.2973019295845425.

  Epoch 025 - train 0.64120 | val 0.82528
  Classification -> best τ=0.580 (val F1=0.2639)
  Directional -> Accuracy: 0.5246, MCC: 0.0091, F1: 0.0645

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2815761383539693
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.62810 | val 0.68852
  Epoch 017 - train 0.63149 | val 0.72531
  Classification -> best τ=0.420 (val F1=0.2203)
  Directional -> Accuracy: 0.4868, MCC: 0.0472, F1: 0.5895

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.68578 | val 0.68855
  Epoch 020 - train 0.57563 | val 0.70511
  Epoch 026 - train 0.57493 | val 0.73217
  Classification -> best τ=0.465 (val F1=0.2431)
  Directional -> Accuracy: 0.6000, MCC: 0.2388, F1: 0.5909

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.68658 | val 0.69023
  Epoch 020 - train 0.64580 | val 0.84520
  Epoch 023 - train 0.62653 | val 0.88651
  Classification -> best τ=0.385 (val F1=0.3678)
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.68973 | val 0.72953
  Epoch 019 - train 0.68120 | val 0.73249
  Classification -> best τ=0.415 (val F1=0.1712)
  Directional -> Accuracy: 0.5467, MCC: 0.0368, F1: 0.6792

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.63782 | val 0.67370
  Epoch 020 - train 0.60567 | val 0.67503
  Epoch 027 - train 0.58581 | val 0.72252
  Classification -> best τ=0.550 (val F1=0.4457)
  Directional -> Accuracy: 0.5294, MCC: 0.0215, F1: 0.6667

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.61840 | val 0.69860
  Epoch 020 - train 0.58162 | val 0.77677
  Classification -> best τ=0.510 (val F1=0.3394)
  Directional -> Accuracy: 0.5532, MCC: 0.1357, F1: 0.2759

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.69507 | val 0.70177
  Epoch 017 - train 0.65199 | val 0.73983
  Classification -> best τ=0.655 (val F1=0.1805)
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.63054 | val 0.68733
  Epoch 020 - train 0.54355 | val 0.92454
  Epoch 027 - train 0.54402 | val 0.74424
  Classification -> best τ=0.295 (val F1=0.1590)
  Directional -> Accuracy: 0.4419, MCC: -0.0852, F1: 0.4545

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.65941 | val 0.71491
  Epoch 017 - train 0.58965 | val 0.75749
  Classification -> best τ=0.500 (val F1=0.1533)
  Directional -> Accuracy: 0.5306, MCC: -0.1303, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.63241 | val 0.74302
  Epoch 017 - train 0.57135 | val 0.91950
  Classification -> best τ=0.520 (val F1=0.2012)
  Directional -> Accuracy: 0.5857, MCC: 0.1507, F1: 0.5085

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.70424 | val 0.68756
  Epoch 020 - train 0.67052 | val 2.09156
  Epoch 024 - train 0.59367 | val 1.60655
  Classification -> best τ=0.390 (val F1=0.4454)
  Directional -> Accuracy: 0.6200, MCC: 0.2766, F1: 0.3448

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.62327 | val 0.82285
  Epoch 016 - train 0.59437 | val 2.12110
  Classification -> best τ=0.475 (val F1=0.1492)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.70236 | val 0.71305
  Epoch 019 - train 0.58263 | val 0.89027
  Classification -> best τ=0.455 (val F1=0.1908)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.67491 | val 0.63841
  Epoch 020 - train 0.64876 | val 0.74133
  Epoch 021 - train 0.64322 | val 0.79311
  Classification -> best τ=0.420 (val F1=0.3477)
  Directional -> Accuracy: 0.5333, MCC: 0.1111, F1: 0.6667

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.63729 | val 0.83081
  Epoch 020 - train 0.58594 | val 0.81146
  Classification -> best τ=0.640 (val F1=0.2160)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.66621 | val 0.69510
  Epoch 017 - train 0.63659 | val 0.78498
  Classification -> best τ=0.490 (val F1=0.2885)
  Directional -> Accuracy: 0.6232, MCC: 0.2465, F1: 0.7111

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.71988 | val 0.93727
  Epoch 016 - train 0.67122 | val 0.96230
  Classification -> best τ=0.645 (val F1=0.0732)
  Directional -> Accuracy: 0.3729, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.66007 | val 0.79646
  Epoch 016 - train 0.66390 | val 1.03689
  Classification -> best τ=0.535 (val F1=0.1217)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.63427 | val 1.05765
  Epoch 017 - train 0.63061 | val 1.62295
  Classification -> best τ=0.455 (val F1=0.2656)
  Directional -> Accuracy: 0.4000, MCC: -0.1122, F1: 0.0488

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.64503 | val 0.69342
  Epoch 020 - train 0.62508 | val 0.67594
  Epoch 030 - train 0.60278 | val 1.14150
  Epoch 031 - train 0.56074 | val 0.99729
  Classification -> best τ=0.585 (val F1=0.3317)
  Directional -> Accuracy: 0.4667, MCC: 0.1059, F1: 0.0476

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.68659 | val 0.73019
  Epoch 018 - train 0.58970 | val 1.75125
  Classification -> best τ=0.460 (val F1=0.2267)
  Directional -> Accuracy: 0.5957, MCC: -0.0267, F1: 0.7397

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.71107 | val 0.70744
  Epoch 020 - train 0.63201 | val 0.75389
  Epoch 021 - train 0.64400 | val 0.79122
  Classification -> best τ=0.560 (val F1=0.2086)
  Directional -> Accuracy: 0.5758, MCC: 0.1562, F1: 0.5172

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.68706 | val 0.68934
  Epoch 017 - train 0.65656 | val 0.74537
  Classification -> best τ=0.520 (val F1=0.2875)
  Directional -> Accuracy: 0.5517, MCC: -0.0461, F1: 0.7045

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.64686 | val 0.68385
  Epoch 018 - train 0.62620 | val 0.72076
  Classification -> best τ=0.415 (val F1=0.3036)
  Directional -> Accuracy: 0.4769, MCC: 0.0000, F1: 0.6458

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.67393 | val 0.66463
  Epoch 020 - train 0.57654 | val 0.67535
  Epoch 030 - train 0.54891 | val 0.70525
  Classification -> best τ=0.480 (val F1=0.4472)
  Directional -> Accuracy: 0.4643, MCC: 0.0017, F1: 0.2500

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.68650 | val 1.09650
  Epoch 017 - train 0.73490 | val 1.08154
  Classification -> best τ=0.470 (val F1=0.3669)
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.64469 | val 0.73592
  Epoch 020 - train 0.62702 | val 0.70635
  Epoch 021 - train 0.63181 | val 0.74977
  Classification -> best τ=0.550 (val F1=0.2107)
  Directional -> Accuracy: 0.4762, MCC: -0.2161, F1: 0.6333

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.64933 | val 0.73161
  Epoch 016 - train 0.63660 | val 0.84424
  Classification -> best τ=0.445 (val F1=0.2648)
  Directional -> Accuracy: 0.5263, MCC: 0.2741, F1: 0.2703

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.70370 | val 0.73672
  Epoch 020 - train 0.62753 | val 0.64895
  Epoch 030 - train 0.55131 | val 0.86985
  Epoch 040 - train 0.50054 | val 2.07998
  Epoch 043 - train 0.43420 | val 2.49587
  Classification -> best τ=0.655 (val F1=0.4719)
  Directional -> Accuracy: 0.5854, MCC: 0.1865, F1: 0.5641

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.68581 | val 0.80334
  Epoch 020 - train 0.60502 | val 1.12076
  Epoch 022 - train 0.59517 | val 1.11389
  Classification -> best τ=0.635 (val F1=0.2814)
  Directional -> Accuracy: 0.5116, MCC: 0.0353, F1: 0.5882

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.60715 | val 0.65094
  Epoch 020 - train 0.57533 | val 0.65306
  Epoch 030 - train 0.56047 | val 0.65364
  Epoch 037 - train 0.46507 | val 0.69927
  Classification -> best τ=0.700 (val F1=0.3201)
  Directional -> Accuracy: 0.6047, MCC: 0.2683, F1: 0.5143

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.62834 | val 0.81470
  Epoch 018 - train 0.57138 | val 1.16146
  Classification -> best τ=0.435 (val F1=0.2611)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.65973 | val 0.68299
  Epoch 020 - train 0.63902 | val 1.09918
  Epoch 023 - train 0.61132 | val 0.98361
  Classification -> best τ=0.390 (val F1=0.3809)
  Directional -> Accuracy: 0.5479, MCC: 0.1207, F1: 0.5352

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.65235 | val 0.84267
  Epoch 016 - train 0.61606 | val 0.78230
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.65067 | val 0.73273
  Epoch 016 - train 0.64509 | val 0.79895
  Classification -> best τ=0.430 (val F1=0.2757)
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.67080 | val 0.70760
  Epoch 016 - train 0.66740 | val 0.75906
  Classification -> best τ=0.475 (val F1=0.4042)
  Directional -> Accuracy: 0.5455, MCC: 0.1390, F1: 0.5161

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.62592 | val 0.82990
  Epoch 016 - train 0.63736 | val 0.85901
  Classification -> best τ=0.500 (val F1=0.1736)
  Directional -> Accuracy: 0.6905, MCC: 0.3977, F1: 0.6667

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.65687 | val 0.67711
  Epoch 020 - train 0.63170 | val 0.70460
  Epoch 021 - train 0.60420 | val 0.71723
  Classification -> best τ=0.390 (val F1=0.2868)
  Directional -> Accuracy: 0.4643, MCC: -0.0138, F1: 0.6250

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.65078 | val 0.71741
  Epoch 016 - train 0.56671 | val 0.76521
  Classification -> best τ=0.475 (val F1=0.3679)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.69451 | val 0.66801
  Epoch 020 - train 0.64950 | val 0.66033
  Epoch 030 - train 0.61375 | val 0.78752
  Epoch 034 - train 0.52010 | val 0.79904
  Classification -> best τ=0.260 (val F1=0.3568)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.71078 | val 0.75569
  Epoch 020 - train 0.60767 | val 0.72783
  Epoch 021 - train 0.61688 | val 0.72094
  Classification -> best τ=0.555 (val F1=0.5666)
  Directional -> Accuracy: 0.4595, MCC: -0.0194, F1: 0.0909

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.65204 | val 0.73133
  Epoch 017 - train 0.62402 | val 0.75279
  Classification -> best τ=0.475 (val F1=0.4537)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.63342 | val 0.68611
  Epoch 020 - train 0.63923 | val 0.68414
  Epoch 030 - train 0.58836 | val 0.68753
  Classification -> best τ=0.480 (val F1=0.4494)
  Directional -> Accuracy: 0.5652, MCC: 0.2097, F1: 0.3750

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.65563 | val 0.67998
  Epoch 020 - train 0.65920 | val 0.67500
  Epoch 030 - train 0.53216 | val 0.64680
  Epoch 037 - train 0.53092 | val 0.80752
  Classification -> best τ=0.535 (val F1=0.4218)
  Directional -> Accuracy: 0.5349, MCC: 0.0366, F1: 0.6154

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.72467 | val 0.71678
  Epoch 019 - train 0.63582 | val 0.71392
  Classification -> best τ=0.495 (val F1=0.4682)
  Directional -> Accuracy: 0.4082, MCC: 0.1149, F1: 0.5672

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.66237 | val 0.77515
  Epoch 020 - train 0.59609 | val 0.99417
  Epoch 021 - train 0.61277 | val 1.24856
  Classification -> best τ=0.450 (val F1=0.2392)
  Directional -> Accuracy: 0.4821, MCC: -0.1659, F1: 0.6420

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.69982 | val 0.98881
  Epoch 017 - train 0.67155 | val 1.08780
  Classification -> best τ=0.565 (val F1=0.2819)
  Directional -> Accuracy: 0.5179, MCC: 0.1857, F1: 0.6667

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.65625 | val 1.02193
  Epoch 018 - train 0.61175 | val 0.86816
  Classification -> best τ=0.630 (val F1=0.1626)
  Directional -> Accuracy: 0.5926, MCC: 0.1834, F1: 0.6562

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.66278 | val 0.72614
  Epoch 019 - train 0.58986 | val 0.90358
  Classification -> best τ=0.445 (val F1=0.1667)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.65542 | val 0.67852

[I 2026-02-25 03:06:05,915] Trial 178 finished with value: 0.28563230377954696 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 64, 'learning_rate': 0.004424588485183875, 'weight_decay': 0.00035397406630934534, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 0.26678041788975726, 'early_stopping_min_delta': 0.00392295680058326}. Best is trial 164 with value: 0.2973019295845425.

  Epoch 018 - train 0.61001 | val 1.05178
  Classification -> best τ=0.485 (val F1=0.2639)
  Directional -> Accuracy: 0.5082, MCC: -0.0145, F1: 0.2857

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.28563230377954696
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.67399 | val 0.70371
  Epoch 020 - train 0.58729 | val 0.92643
  Epoch 022 - train 0.61822 | val 0.78260
  Classification -> best τ=0.465 (val F1=0.2919)
  Directional -> Accuracy: 0.5395, MCC: 0.0306, F1: 0.3396

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.69469 | val 0.68103
  Epoch 020 - train 0.64444 | val 0.71510
  Epoch 025 - train 0.57962 | val 0.67749
  Classification -> best τ=0.510 (val F1=0.1962)
  Directional -> Accuracy: 0.5556, MCC: 0.1650, F1: 0.5238

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.69834 | val 0.69881
  Epoch 020 - train 0.66614 | val 0.82305
  Epoch 022 - train 0.65583 | val 0.79479
  Classification -> best τ=0.505 (val F1=0.3882)
  Directional -> Accuracy: 0.5106, MCC: 0.0709, F1: 0.3429

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.68975 | val 0.81352
  Epoch 018 - train 0.68250 | val 0.73572
  Classification -> best τ=0.480 (val F1=0.1723)
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.61885 | val 0.64680
  Epoch 020 - train 0.54346 | val 0.64745
  Epoch 026 - train 0.60291 | val 0.68617
  Classification -> best τ=0.605 (val F1=0.4598)
  Directional -> Accuracy: 0.4706, MCC: -0.0601, F1: 0.4906

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.70527 | val 0.75514
  Epoch 016 - train 0.60088 | val 0.71050
  Classification -> best τ=0.515 (val F1=0.2632)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.72467 | val 0.69119
  Epoch 019 - train 0.64638 | val 0.69575
  Classification -> best τ=0.550 (val F1=0.2171)
  Directional -> Accuracy: 0.5507, MCC: 0.0417, F1: 0.3922

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.61254 | val 0.65368
  Epoch 020 - train 0.57765 | val 0.85838
  Epoch 023 - train 0.53102 | val 0.89566
  Classification -> best τ=0.325 (val F1=0.1590)
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.64083 | val 0.76139
  Epoch 020 - train 0.62157 | val 0.88987
  Epoch 021 - train 0.54060 | val 0.88364
  Classification -> best τ=0.440 (val F1=0.3539)
  Directional -> Accuracy: 0.6531, MCC: 0.2922, F1: 0.5854

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.66754 | val 0.72978
  Epoch 016 - train 0.62923 | val 0.76790
  Classification -> best τ=0.520 (val F1=0.1816)
  Directional -> Accuracy: 0.4286, MCC: -0.0355, F1: 0.5833

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.65061 | val 1.32481
  Epoch 018 - train 0.62126 | val 1.25924
  Classification -> best τ=0.360 (val F1=0.1166)
  Directional -> Accuracy: 0.5600, MCC: 0.1542, F1: 0.6071

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.62940 | val 0.72547
  Epoch 017 - train 0.57547 | val 0.97303
  Classification -> best τ=0.525 (val F1=0.1651)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.66502 | val 0.77431
  Epoch 020 - train 0.58929 | val 0.82632
  Classification -> best τ=0.400 (val F1=0.2876)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.63129 | val 0.63172
  Epoch 020 - train 0.60197 | val 0.66865
  Epoch 025 - train 0.60692 | val 1.23074
  Classification -> best τ=0.515 (val F1=0.4213)
  Directional -> Accuracy: 0.5500, MCC: 0.1110, F1: 0.6301

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.64091 | val 0.70232
  Epoch 020 - train 0.57057 | val 1.09237
  Classification -> best τ=0.555 (val F1=0.2673)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.65992 | val 0.72182
  Epoch 017 - train 0.61796 | val 0.83228
  Classification -> best τ=0.505 (val F1=0.3170)
  Directional -> Accuracy: 0.5362, MCC: 0.0759, F1: 0.5429

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.66413 | val 0.94396
  Epoch 016 - train 0.65908 | val 1.11053
  Classification -> best τ=0.365 (val F1=0.0095)
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.69229 | val 0.87416
  Epoch 018 - train 0.63594 | val 1.29426
  Classification -> best τ=0.465 (val F1=0.2706)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.68638 | val 0.88167
  Epoch 016 - train 0.64845 | val 1.24253
  Classification -> best τ=0.405 (val F1=0.2843)
  Directional -> Accuracy: 0.5077, MCC: 0.1597, F1: 0.3600

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.64656 | val 0.66300
  Epoch 020 - train 0.62222 | val 0.86328
  Epoch 025 - train 0.60267 | val 0.83244
  Classification -> best τ=0.485 (val F1=0.3237)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.65906 | val 0.71086
  Epoch 020 - train 0.57914 | val 1.01090
  Epoch 022 - train 0.58025 | val 0.94065
  Classification -> best τ=0.470 (val F1=0.3307)
  Directional -> Accuracy: 0.4681, MCC: 0.0598, F1: 0.3902

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.69332 | val 0.73073
  Epoch 016 - train 0.62279 | val 0.92035
  Classification -> best τ=0.565 (val F1=0.1895)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.68245 | val 0.77077
  Epoch 017 - train 0.66569 | val 0.74272
  Classification -> best τ=0.520 (val F1=0.2894)
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.68157 | val 0.69831
  Epoch 019 - train 0.60393 | val 0.89291
  Classification -> best τ=0.560 (val F1=0.1986)
  Directional -> Accuracy: 0.5846, MCC: 0.1798, F1: 0.6087

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.68717 | val 0.66929
  Epoch 020 - train 0.58947 | val 0.75553
  Epoch 030 - train 0.55200 | val 0.92076
  Epoch 032 - train 0.50731 | val 0.86576
  Classification -> best τ=0.485 (val F1=0.4670)
  Directional -> Accuracy: 0.5357, MCC: 0.1728, F1: 0.3810

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.78457 | val 0.95549
  Epoch 020 - train 0.65417 | val 0.96716
  Classification -> best τ=0.510 (val F1=0.3006)
  Directional -> Accuracy: 0.5652, MCC: 0.0604, F1: 0.2857

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.66131 | val 0.69603
  Epoch 018 - train 0.68065 | val 0.69422
  Classification -> best τ=0.565 (val F1=0.2582)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.63828 | val 0.69525
  Epoch 016 - train 0.59092 | val 0.80429
  Classification -> best τ=0.445 (val F1=0.2391)
  Directional -> Accuracy: 0.5263, MCC: 0.2741, F1: 0.2703

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.69653 | val 0.67799
  Epoch 020 - train 0.66577 | val 0.63499
  Epoch 030 - train 0.60537 | val 0.84241
  Epoch 037 - train 0.49821 | val 2.39208
  Classification -> best τ=0.535 (val F1=0.4099)
  Directional -> Accuracy: 0.4878, MCC: -0.1407, F1: 0.6441

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.69578 | val 0.72373
  Epoch 016 - train 0.65598 | val 0.84983
  Classification -> best τ=0.510 (val F1=0.3354)
  Directional -> Accuracy: 0.4884, MCC: -0.0353, F1: 0.3529

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.75269 | val 0.70389
  Epoch 020 - train 0.63323 | val 0.70775
  Epoch 022 - train 0.60719 | val 1.04915
  Classification -> best τ=0.585 (val F1=0.3556)
  Directional -> Accuracy: 0.4186, MCC: -0.1829, F1: 0.0741

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.63303 | val 0.76270
  Epoch 017 - train 0.60198 | val 1.51024
  Classification -> best τ=0.425 (val F1=0.2837)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.65693 | val 0.70746
  Epoch 020 - train 0.62146 | val 0.74026
  Epoch 023 - train 0.62131 | val 1.05144
  Classification -> best τ=0.335 (val F1=0.3353)
  Directional -> Accuracy: 0.5205, MCC: 0.0806, F1: 0.4776

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.69551 | val 0.79905
  Epoch 016 - train 0.57891 | val 0.92210
  Classification -> best τ=0.460 (val F1=0.3540)
  Directional -> Accuracy: 0.5405, MCC: 0.1172, F1: 0.6383

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.72085 | val 0.73702
  Epoch 016 - train 0.61879 | val 0.88012
  Classification -> best τ=0.435 (val F1=0.2358)
  Directional -> Accuracy: 0.4773, MCC: -0.0144, F1: 0.6230

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.65575 | val 0.72143
  Epoch 016 - train 0.64820 | val 0.73586
  Classification -> best τ=0.430 (val F1=0.3366)
  Directional -> Accuracy: 0.5455, MCC: 0.0152, F1: 0.6591

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.60673 | val 0.78994
  Epoch 016 - train 0.62501 | val 0.81909
  Classification -> best τ=0.545 (val F1=0.1846)
  Directional -> Accuracy: 0.6429, MCC: 0.3511, F1: 0.5455

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.64516 | val 0.75869
  Epoch 018 - train 0.60405 | val 0.73739
  Classification -> best τ=0.380 (val F1=0.2450)
  Directional -> Accuracy: 0.4821, MCC: -0.0029, F1: 0.5672

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.65224 | val 0.73720
  Epoch 020 - train 0.57229 | val 0.86560
  Epoch 029 - train 0.54212 | val 1.17103
  Classification -> best τ=0.360 (val F1=0.2474)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.62433 | val 0.73690
  Epoch 020 - train 0.64017 | val 0.65502
  Epoch 030 - train 0.58813 | val 0.60405
  Epoch 040 - train 0.59782 | val 0.59589
  Epoch 046 - train 0.56154 | val 0.63496
  Classification -> best τ=0.395 (val F1=0.6670)
  Directional -> Accuracy: 0.3469, MCC: -0.1894, F1: 0.5152

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.78244 | val 0.68587
  Epoch 020 - train 0.56925 | val 0.99735
  Epoch 025 - train 0.52121 | val 0.82868
  Classification -> best τ=0.595 (val F1=0.4240)
  Directional -> Accuracy: 0.4595, MCC: -0.0495, F1: 0.3333

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.64285 | val 0.67827
  Epoch 020 - train 0.61434 | val 0.74178
  Epoch 021 - train 0.58087 | val 0.76703
  Classification -> best τ=0.465 (val F1=0.3963)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.61260 | val 0.68716
  Epoch 019 - train 0.61068 | val 0.76947
  Classification -> best τ=0.455 (val F1=0.3989)
  Directional -> Accuracy: 0.4565, MCC: -0.0851, F1: 0.1379

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.64981 | val 0.70509
  Epoch 020 - train 0.59540 | val 0.74236
  Epoch 030 - train 0.55725 | val 0.64301
  Epoch 040 - train 0.52884 | val 0.70962
  Epoch 050 - train 0.43785 | val 0.54176
  Classification -> best τ=0.455 (val F1=0.5733)
  Directional -> Accuracy: 0.4419, MCC: -0.1778, F1: 0.5556

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.67329 | val 0.59861
  Epoch 020 - train 0.58730 | val 0.59319
  Epoch 026 - train 0.52047 | val 0.72834
  Classification -> best τ=0.485 (val F1=0.6292)
  Directional -> Accuracy: 0.3673, MCC: -0.1462, F1: 0.5231

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.67171 | val 1.05943
  Epoch 016 - train 0.66368 | val 1.42984
  Classification -> best τ=0.505 (val F1=0.2256)
  Directional -> Accuracy: 0.5179, MCC: 0.2215, F1: 0.1818

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.66775 | val 0.90457
  Epoch 016 - train 0.58942 | val 1.39251
  Classification -> best τ=0.640 (val F1=0.3156)
  Directional -> Accuracy: 0.5179, MCC: 0.1289, F1: 0.6582

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.67467 | val 0.73984
  Epoch 020 - train 0.63348 | val 1.75349
  Epoch 025 - train 0.63263 | val 1.95238
  Classification -> best τ=0.350 (val F1=0.3436)
  Directional -> Accuracy: 0.5556, MCC: 0.1310, F1: 0.6842

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.63515 | val 0.74495
  Epoch 018 - train 0.61737 | val 0.82863
  Classification -> best τ=0.465 (val F1=0.0754)
  Directional -> Accuracy: 0.4643, MCC: -0.0620, F1: 0.2857

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.68575 | val 0.70930
  Epoch 020 - train 0.62817 | val 1.12245
  Epoch 021 - train 0.62413 | val 1.22556

[I 2026-02-25 03:08:12,170] Trial 179 finished with value: 0.3025280267941637 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 64, 'learning_rate': 0.0045833605382563525, 'weight_decay': 0.0002375103501024552, 'lr_patience': 7, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 0.34728310081841085, 'early_stopping_min_delta': 0.0039521839914542665}. Best is trial 179 with value: 0.3025280267941637.

  Classification -> best τ=0.395 (val F1=0.3349)
  Directional -> Accuracy: 0.4590, MCC: -0.1356, F1: 0.6292

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.3025280267941637
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.62825 | val 0.81474
  Epoch 020 - train 0.59724 | val 0.78035
  Classification -> best τ=0.545 (val F1=0.2510)
  Directional -> Accuracy: 0.5263, MCC: -0.0671, F1: 0.1000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.67251 | val 0.70976
  Epoch 018 - train 0.58842 | val 0.72695
  Classification -> best τ=0.445 (val F1=0.1252)
  Directional -> Accuracy: 0.6000, MCC: 0.1273, F1: 0.7273

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.64053 | val 0.72998
  Epoch 016 - train 0.60718 | val 0.80122
  Classification -> best τ=0.435 (val F1=0.4500)
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.68143 | val 0.73053
  Epoch 016 - train 0.66731 | val 0.83725
  Classification -> best τ=0.420 (val F1=0.1283)
  Directional -> Accuracy: 0.5733, MCC: 0.1437, F1: 0.6000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.66908 | val 0.70398
  Epoch 020 - train 0.60369 | val 0.79115
  Epoch 021 - train 0.53311 | val 0.83273
  Classification -> best τ=0.495 (val F1=0.3627)
  Directional -> Accuracy: 0.5098, MCC: -0.0687, F1: 0.6667

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.61529 | val 0.69265
  Epoch 020 - train 0.59125 | val 0.70347
  Epoch 030 - train 0.53485 | val 0.70460
  Epoch 033 - train 0.52689 | val 0.74109
  Classification -> best τ=0.485 (val F1=0.3397)
  Directional -> Accuracy: 0.5106, MCC: 0.0509, F1: 0.6349

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.67389 | val 0.72158
  Epoch 017 - train 0.63123 | val 0.79128
  Classification -> best τ=0.455 (val F1=0.2108)
  Directional -> Accuracy: 0.4348, MCC: 0.1428, F1: 0.5895

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.63035 | val 0.84584
  Epoch 018 - train 0.61332 | val 1.10322
  Classification -> best τ=0.490 (val F1=0.1502)
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.66884 | val 0.71622
  Epoch 018 - train 0.62203 | val 0.78871
  Classification -> best τ=0.515 (val F1=0.0424)
  Directional -> Accuracy: 0.5714, MCC: 0.1081, F1: 0.4000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.66533 | val 0.74807
  Epoch 016 - train 0.61226 | val 0.75865
  Classification -> best τ=0.490 (val F1=0.0514)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.63382 | val 0.69724
  Epoch 016 - train 0.59666 | val 1.22121
  Classification -> best τ=0.440 (val F1=0.2722)
  Directional -> Accuracy: 0.6200, MCC: 0.2766, F1: 0.3448

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.59936 | val 0.76433
  Epoch 020 - train 0.59002 | val 0.84234
  Classification -> best τ=0.510 (val F1=0.2105)
  Directional -> Accuracy: 0.5517, MCC: 0.2335, F1: 0.1875

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.63579 | val 0.90551
  Epoch 019 - train 0.58703 | val 0.95829
  Classification -> best τ=0.400 (val F1=0.1908)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.65381 | val 0.66565
  Epoch 020 - train 0.63510 | val 0.80662
  Epoch 024 - train 0.61830 | val 1.04590
  Classification -> best τ=0.510 (val F1=0.5040)
  Directional -> Accuracy: 0.5500, MCC: 0.1155, F1: 0.6400

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.64521 | val 0.76169
  Epoch 018 - train 0.60130 | val 1.07785
  Classification -> best τ=0.525 (val F1=0.1512)
  Directional -> Accuracy: 0.4423, MCC: -0.1075, F1: 0.4528

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.63833 | val 0.66677
  Epoch 020 - train 0.60064 | val 0.94300
  Epoch 025 - train 0.57050 | val 0.93359
  Classification -> best τ=0.530 (val F1=0.2810)
  Directional -> Accuracy: 0.5362, MCC: 0.1179, F1: 0.4286

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.68310 | val 0.83036
  Epoch 016 - train 0.62349 | val 1.09082
  Classification -> best τ=0.580 (val F1=0.2276)
  Directional -> Accuracy: 0.3729, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.66914 | val 1.04389
  Epoch 016 - train 0.63400 | val 0.89779
  Classification -> best τ=0.430 (val F1=0.1733)
  Directional -> Accuracy: 0.6000, MCC: 0.1961, F1: 0.6429

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.70627 | val 0.95758
  Epoch 016 - train 0.63249 | val 1.17568
  Classification -> best τ=0.465 (val F1=0.2843)
  Directional -> Accuracy: 0.5846, MCC: 0.1228, F1: 0.6667

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.65283 | val 0.71825
  Epoch 019 - train 0.64007 | val 0.71999
  Classification -> best τ=0.550 (val F1=0.2606)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.68011 | val 0.71314
  Epoch 020 - train 0.58946 | val 0.80326
  Epoch 023 - train 0.55889 | val 0.88095
  Classification -> best τ=0.415 (val F1=0.3278)
  Directional -> Accuracy: 0.5319, MCC: 0.0504, F1: 0.5926

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.68625 | val 0.69491
  Epoch 016 - train 0.63787 | val 0.78602
  Classification -> best τ=0.545 (val F1=0.1878)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.66102 | val 0.77214
  Epoch 019 - train 0.59891 | val 0.82979
  Classification -> best τ=0.510 (val F1=0.2379)
  Directional -> Accuracy: 0.5517, MCC: 0.0687, F1: 0.6286

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.66369 | val 0.73608
  Epoch 016 - train 0.59869 | val 0.76549
  Classification -> best τ=0.505 (val F1=0.1359)
  Directional -> Accuracy: 0.5077, MCC: 0.0917, F1: 0.6444

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.68731 | val 0.65870
  Epoch 020 - train 0.60735 | val 0.65210
  Epoch 030 - train 0.56670 | val 0.66473
  Classification -> best τ=0.350 (val F1=0.4124)
  Directional -> Accuracy: 0.5893, MCC: 0.1723, F1: 0.6230

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.69920 | val 0.70748
  Epoch 016 - train 0.66391 | val 0.72903
  Classification -> best τ=0.490 (val F1=0.1890)
  Directional -> Accuracy: 0.5435, MCC: -0.1307, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.63748 | val 0.70142
  Epoch 020 - train 0.61154 | val 0.68275
  Epoch 030 - train 0.59983 | val 0.69665
  Epoch 034 - train 0.58785 | val 0.69883
  Classification -> best τ=0.610 (val F1=0.2402)
  Directional -> Accuracy: 0.5238, MCC: 0.0278, F1: 0.5833

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.59769 | val 0.73245
  Epoch 016 - train 0.61623 | val 0.87638
  Classification -> best τ=0.475 (val F1=0.2370)
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.65695 | val 0.67238
  Epoch 020 - train 0.60728 | val 0.90925
  Epoch 028 - train 0.59200 | val 0.94466
  Classification -> best τ=0.450 (val F1=0.3518)
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.68012 | val 0.73318
  Epoch 016 - train 0.62394 | val 0.81044
  Classification -> best τ=0.500 (val F1=0.2814)
  Directional -> Accuracy: 0.5116, MCC: 0.0162, F1: 0.4000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.67076 | val 0.73872
  Epoch 020 - train 0.59582 | val 0.80028
  Epoch 022 - train 0.62162 | val 0.81993
  Classification -> best τ=0.650 (val F1=0.1204)
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.59406 | val 0.74471
  Epoch 020 - train 0.56001 | val 1.06846
  Classification -> best τ=0.615 (val F1=0.2399)
  Directional -> Accuracy: 0.4800, MCC: -0.1191, F1: 0.6176

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.65805 | val 0.69488
  Epoch 020 - train 0.61070 | val 0.67981
  Epoch 021 - train 0.60707 | val 0.66831
  Classification -> best τ=0.535 (val F1=0.3023)
  Directional -> Accuracy: 0.4795, MCC: 0.1002, F1: 0.2083

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.68868 | val 0.78027
  Epoch 016 - train 0.64185 | val 0.94111
  Classification -> best τ=0.460 (val F1=0.2588)
  Directional -> Accuracy: 0.5135, MCC: 0.1622, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.70336 | val 0.73424
  Epoch 017 - train 0.64077 | val 0.84429
  Classification -> best τ=0.535 (val F1=0.2936)
  Directional -> Accuracy: 0.6364, MCC: 0.2754, F1: 0.6364

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.65852 | val 0.75851
  Epoch 016 - train 0.62482 | val 0.79910
  Classification -> best τ=0.485 (val F1=0.3787)
  Directional -> Accuracy: 0.6364, MCC: 0.2556, F1: 0.6842

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.66497 | val 0.70099
  Epoch 016 - train 0.61339 | val 0.72024
  Classification -> best τ=0.520 (val F1=0.2652)
  Directional -> Accuracy: 0.6429, MCC: 0.3511, F1: 0.5455

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.64642 | val 0.71760
  Epoch 016 - train 0.63737 | val 0.75277
  Classification -> best τ=0.415 (val F1=0.2354)
  Directional -> Accuracy: 0.5179, MCC: 0.1353, F1: 0.6400

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.60522 | val 0.83307
  Epoch 020 - train 0.56837 | val 1.01380
  Classification -> best τ=0.500 (val F1=0.2118)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.67715 | val 0.67024
  Epoch 020 - train 0.61283 | val 0.63422
  Epoch 030 - train 0.55583 | val 0.71490
  Epoch 040 - train 0.54014 | val 0.70330
  Epoch 041 - train 0.55440 | val 0.68989
  Classification -> best τ=0.245 (val F1=0.5617)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.65949 | val 0.74388
  Epoch 017 - train 0.70167 | val 0.78469
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.64034 | val 0.88752
  Epoch 018 - train 0.60463 | val 0.97524
  Classification -> best τ=0.440 (val F1=0.4028)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.66893 | val 0.66949
  Epoch 020 - train 0.62067 | val 0.66985
  Epoch 030 - train 0.59210 | val 0.71270
  Epoch 038 - train 0.58078 | val 0.74113
  Classification -> best τ=0.450 (val F1=0.5065)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.6857

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.69705 | val 0.71660
  Epoch 016 - train 0.61064 | val 0.72915
  Classification -> best τ=0.530 (val F1=0.0685)
  Directional -> Accuracy: 0.4419, MCC: -0.0375, F1: 0.1429

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.64496 | val 0.68554
  Epoch 020 - train 0.60150 | val 0.62383
  Epoch 030 - train 0.55353 | val 0.65221
  Epoch 035 - train 0.55172 | val 0.62459
  Classification -> best τ=0.510 (val F1=0.5261)
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.71932 | val 0.99206
  Epoch 017 - train 0.65456 | val 1.11890
  Classification -> best τ=0.460 (val F1=0.1914)
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.64414 | val 0.81640
  Epoch 020 - train 0.60586 | val 1.21142
  Epoch 021 - train 0.58281 | val 1.27101
  Classification -> best τ=0.630 (val F1=0.3741)
  Directional -> Accuracy: 0.5357, MCC: 0.1397, F1: 0.0714

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.66757 | val 1.05607
  Epoch 016 - train 0.64686 | val 1.08229
  Classification -> best τ=0.435 (val F1=0.2665)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.67206 | val 0.80081
  Epoch 020 - train 0.63248 | val 0.83734
  Epoch 029 - train 0.55715 | val 0.78938
  Classification -> best τ=0.465 (val F1=0.1833)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.72660 | val 0.73431
  Epoch 020 - train 0.62689 | val 0.91771

[I 2026-02-25 03:10:15,510] Trial 180 finished with value: 0.258795773891522 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 64, 'learning_rate': 0.0018294593133636326, 'weight_decay': 0.00022618281958429153, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 0.2582144785088217, 'early_stopping_min_delta': 0.004107624621652119}. Best is trial 179 with value: 0.3025280267941637.

  Epoch 024 - train 0.61148 | val 0.92676
  Classification -> best τ=0.375 (val F1=0.2847)
  Directional -> Accuracy: 0.4918, MCC: 0.1229, F1: 0.6517

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.258795773891522
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.64200 | val 0.80423
  Epoch 017 - train 0.60406 | val 1.19931
  Classification -> best τ=0.470 (val F1=0.2919)
  Directional -> Accuracy: 0.5132, MCC: 0.0530, F1: 0.5432

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.68344 | val 0.91241
  Epoch 016 - train 0.62805 | val 0.70769
  Classification -> best τ=0.420 (val F1=0.1433)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.70064 | val 0.71434
  Epoch 018 - train 0.63131 | val 0.75513
  Classification -> best τ=0.505 (val F1=0.2064)
  Directional -> Accuracy: 0.4894, MCC: -0.1033, F1: 0.6364

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.69632 | val 0.74085
  Epoch 018 - train 0.68212 | val 0.75583
  Classification -> best τ=0.445 (val F1=0.1723)
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.68774 | val 0.65368
  Epoch 020 - train 0.58887 | val 0.67374
  Epoch 024 - train 0.58159 | val 0.67304
  Classification -> best τ=0.620 (val F1=0.4513)
  Directional -> Accuracy: 0.4510, MCC: -0.0929, F1: 0.4400

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.66126 | val 0.72598
  Epoch 016 - train 0.61959 | val 0.74642
  Classification -> best τ=0.485 (val F1=0.1715)
  Directional -> Accuracy: 0.5745, MCC: 0.1726, F1: 0.3750

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.65662 | val 0.68211
  Epoch 020 - train 0.65403 | val 0.71016
  Epoch 022 - train 0.63380 | val 0.72970
  Classification -> best τ=0.425 (val F1=0.1945)
  Directional -> Accuracy: 0.3913, MCC: -0.1133, F1: 0.5532

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.66715 | val 0.63190
  Epoch 020 - train 0.59195 | val 0.68127
  Epoch 025 - train 0.56221 | val 1.26146
  Classification -> best τ=0.480 (val F1=0.1439)
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.67007 | val 0.75184
  Epoch 018 - train 0.58224 | val 0.85170
  Classification -> best τ=0.530 (val F1=0.3459)
  Directional -> Accuracy: 0.6327, MCC: 0.3303, F1: 0.3077

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.62541 | val 0.68161
  Epoch 020 - train 0.59109 | val 0.76207
  Epoch 025 - train 0.57541 | val 0.82572
  Classification -> best τ=0.475 (val F1=0.2307)
  Directional -> Accuracy: 0.5000, MCC: 0.0742, F1: 0.5679

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.71103 | val 0.69105
  Epoch 018 - train 0.57972 | val 1.22144
  Classification -> best τ=0.485 (val F1=0.2187)
  Directional -> Accuracy: 0.5200, MCC: 0.0276, F1: 0.4545

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.65534 | val 0.80056
  Epoch 018 - train 0.60797 | val 1.20925
  Classification -> best τ=0.470 (val F1=0.2196)
  Directional -> Accuracy: 0.5345, MCC: 0.1000, F1: 0.6582

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.61372 | val 0.79504
  Epoch 016 - train 0.66282 | val 0.76828
  Classification -> best τ=0.555 (val F1=0.1786)
  Directional -> Accuracy: 0.4524, MCC: -0.1711, F1: 0.2069

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.70512 | val 0.64908
  Epoch 020 - train 0.64200 | val 0.79753
  Epoch 021 - train 0.62327 | val 0.71742
  Classification -> best τ=0.445 (val F1=0.3407)
  Directional -> Accuracy: 0.5500, MCC: 0.1110, F1: 0.6301

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.64237 | val 0.74143
  Epoch 017 - train 0.61008 | val 1.02639
  Classification -> best τ=0.510 (val F1=0.2214)
  Directional -> Accuracy: 0.5385, MCC: 0.0154, F1: 0.0769

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.63946 | val 0.70609
  Epoch 020 - train 0.60279 | val 0.90971
  Epoch 022 - train 0.58760 | val 0.89224
  Classification -> best τ=0.615 (val F1=0.3015)
  Directional -> Accuracy: 0.5217, MCC: 0.1200, F1: 0.3265

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.72667 | val 0.89604
  Epoch 016 - train 0.66854 | val 1.23045
  Classification -> best τ=0.590 (val F1=0.2276)
  Directional -> Accuracy: 0.3729, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.68281 | val 0.74864
  Epoch 016 - train 0.66196 | val 0.95488
  Classification -> best τ=0.435 (val F1=0.1255)
  Directional -> Accuracy: 0.5600, MCC: 0.0884, F1: 0.6292

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.64145 | val 1.10239
  Epoch 016 - train 0.63666 | val 1.28195
  Classification -> best τ=0.460 (val F1=0.2843)
  Directional -> Accuracy: 0.5385, MCC: 0.0395, F1: 0.6154

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.65340 | val 0.66196
  Epoch 020 - train 0.59559 | val 0.79874
  Epoch 024 - train 0.61526 | val 1.05613
  Classification -> best τ=0.435 (val F1=0.3234)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.66800 | val 0.71232
  Epoch 018 - train 0.61154 | val 0.90007
  Classification -> best τ=0.490 (val F1=0.2845)
  Directional -> Accuracy: 0.6596, MCC: 0.2797, F1: 0.7241

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.67703 | val 0.84950
  Epoch 017 - train 0.65863 | val 0.87700
  Classification -> best τ=0.535 (val F1=0.2787)
  Directional -> Accuracy: 0.5909, MCC: 0.2357, F1: 0.4000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.65760 | val 0.74891
  Epoch 016 - train 0.63616 | val 0.83774
  Classification -> best τ=0.595 (val F1=0.2520)
  Directional -> Accuracy: 0.5172, MCC: 0.0762, F1: 0.4815

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.66422 | val 0.69977
  Epoch 016 - train 0.59966 | val 0.90882
  Classification -> best τ=0.415 (val F1=0.2609)
  Directional -> Accuracy: 0.4769, MCC: -0.0220, F1: 0.5952

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.68100 | val 0.64507
  Epoch 020 - train 0.62349 | val 0.65536
  Epoch 027 - train 0.54416 | val 0.70663
  Classification -> best τ=0.410 (val F1=0.3730)
  Directional -> Accuracy: 0.5714, MCC: 0.1057, F1: 0.6667

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.63310 | val 0.70027
  Epoch 016 - train 0.64731 | val 0.73739
  Classification -> best τ=0.510 (val F1=0.1310)
  Directional -> Accuracy: 0.5000, MCC: 0.0356, F1: 0.5306

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.69932 | val 0.68161
  Epoch 020 - train 0.60510 | val 0.72967
  Epoch 030 - train 0.58416 | val 0.74514
  Epoch 040 - train 0.57814 | val 0.65320
  Epoch 050 - train 0.57308 | val 0.66359
  Classification -> best τ=0.575 (val F1=0.2831)
  Directional -> Accuracy: 0.4286, MCC: -0.1250, F1: 0.4286

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.63087 | val 0.70560
  Epoch 020 - train 0.58936 | val 1.08153
  Epoch 022 - train 0.58878 | val 1.15345
  Classification -> best τ=0.390 (val F1=0.2781)
  Directional -> Accuracy: 0.5439, MCC: 0.3032, F1: 0.3158

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.71088 | val 0.67798
  Epoch 020 - train 0.56329 | val 1.17757
  Epoch 022 - train 0.64886 | val 0.88610
  Classification -> best τ=0.570 (val F1=0.3477)
  Directional -> Accuracy: 0.5122, MCC: 0.0416, F1: 0.4737

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.68949 | val 0.71536
  Epoch 020 - train 0.62586 | val 0.84630
  Epoch 027 - train 0.54871 | val 1.10057
  Classification -> best τ=0.580 (val F1=0.2814)
  Directional -> Accuracy: 0.5581, MCC: 0.1366, F1: 0.6275

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.68992 | val 0.68152
  Epoch 020 - train 0.62684 | val 0.98454
  Epoch 026 - train 0.59179 | val 1.00399
  Classification -> best τ=0.390 (val F1=0.2517)
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.63512 | val 0.76880
  Epoch 019 - train 0.56413 | val 1.49052
  Classification -> best τ=0.565 (val F1=0.2969)
  Directional -> Accuracy: 0.5800, MCC: 0.2212, F1: 0.7200

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.66114 | val 0.75898
  Epoch 018 - train 0.61400 | val 0.71904
  Classification -> best τ=0.430 (val F1=0.3391)
  Directional -> Accuracy: 0.5616, MCC: 0.1530, F1: 0.5429

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.65110 | val 0.69435
  Epoch 016 - train 0.68252 | val 0.97406
  Classification -> best τ=0.490 (val F1=0.3651)
  Directional -> Accuracy: 0.5135, MCC: 0.0327, F1: 0.5500

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.70887 | val 0.75926
  Epoch 016 - train 0.64601 | val 0.84820
  Classification -> best τ=0.570 (val F1=0.2031)
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.68868 | val 0.72258
  Epoch 016 - train 0.62670 | val 0.77613
  Classification -> best τ=0.455 (val F1=0.3855)
  Directional -> Accuracy: 0.6061, MCC: 0.1517, F1: 0.7174

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.59951 | val 0.68947
  Epoch 016 - train 0.56310 | val 0.81926
  Classification -> best τ=0.490 (val F1=0.1886)
  Directional -> Accuracy: 0.6667, MCC: 0.3441, F1: 0.6500

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.68226 | val 0.69097
  Epoch 020 - train 0.59137 | val 0.67150
  Epoch 030 - train 0.55447 | val 0.66884
  Epoch 040 - train 0.50657 | val 0.78915
  Epoch 047 - train 0.47291 | val 0.78046
  Classification -> best τ=0.455 (val F1=0.3625)
  Directional -> Accuracy: 0.5357, MCC: 0.1754, F1: 0.6486

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.62407 | val 0.84224
  Epoch 016 - train 0.55277 | val 0.97465
  Classification -> best τ=0.500 (val F1=0.3089)
  Directional -> Accuracy: 0.6087, MCC: 0.0475, F1: 0.7500

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.66462 | val 0.70392
  Epoch 020 - train 0.58574 | val 0.64884
  Epoch 030 - train 0.56123 | val 0.65685
  Epoch 037 - train 0.54517 | val 0.64131
  Classification -> best τ=0.400 (val F1=0.4386)
  Directional -> Accuracy: 0.4082, MCC: 0.0726, F1: 0.5397

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.66876 | val 0.71854
  Epoch 020 - train 0.62013 | val 0.78597
  Epoch 023 - train 0.60442 | val 0.81736
  Classification -> best τ=0.530 (val F1=0.3545)
  Directional -> Accuracy: 0.4324, MCC: -0.1115, F1: 0.1600

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.61200 | val 0.79064
  Epoch 020 - train 0.60142 | val 1.06319
  Epoch 021 - train 0.62589 | val 1.06225
  Classification -> best τ=0.425 (val F1=0.4778)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.61565 | val 0.70185
  Epoch 020 - train 0.58506 | val 0.68232
  Epoch 030 - train 0.54546 | val 0.79364
  Classification -> best τ=0.485 (val F1=0.5065)
  Directional -> Accuracy: 0.4783, MCC: -0.0229, F1: 0.2941

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.74467 | val 0.69001
  Epoch 020 - train 0.58812 | val 0.69943
  Epoch 024 - train 0.56313 | val 0.71283
  Classification -> best τ=0.545 (val F1=0.4743)
  Directional -> Accuracy: 0.5814, MCC: 0.1280, F1: 0.6667

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.72589 | val 0.67348
  Epoch 020 - train 0.64977 | val 0.71647
  Epoch 029 - train 0.55272 | val 0.66313
  Classification -> best τ=0.555 (val F1=0.5514)
  Directional -> Accuracy: 0.3878, MCC: -0.0687, F1: 0.5312

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.67492 | val 0.91455
  Epoch 016 - train 0.64327 | val 0.84192
  Classification -> best τ=0.440 (val F1=0.2392)
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.63816 | val 0.83078
  Epoch 016 - train 0.58074 | val 1.19104
  Classification -> best τ=0.570 (val F1=0.2946)
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.67553 | val 1.19155
  Epoch 019 - train 0.61535 | val 1.39679
  Classification -> best τ=0.520 (val F1=0.2079)
  Directional -> Accuracy: 0.4815, MCC: -0.0483, F1: 0.5484

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.62757 | val 0.78814
  Epoch 017 - train 0.60626 | val 0.86859
  Classification -> best τ=0.560 (val F1=0.0422)
  Directional -> Accuracy: 0.5179, MCC: 0.0206, F1: 0.6197

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.69655 | val 0.94069
  Epoch 020 - train 0.61386 | val 0.83475

[I 2026-02-25 03:12:22,464] Trial 181 finished with value: 0.2827259631481907 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 64, 'learning_rate': 0.0028089758553093173, 'weight_decay': 0.00035575293752370123, 'lr_patience': 7, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 0.3497305380583028, 'early_stopping_min_delta': 0.0037268718721566317}. Best is trial 179 with value: 0.3025280267941637.

  Epoch 023 - train 0.62277 | val 0.81522
  Classification -> best τ=0.405 (val F1=0.2847)
  Directional -> Accuracy: 0.6066, MCC: 0.2291, F1: 0.6364

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2827259631481907
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.64787 | val 0.77130
  Epoch 017 - train 0.58546 | val 0.85843
  Classification -> best τ=0.480 (val F1=0.2039)
  Directional -> Accuracy: 0.4868, MCC: 0.0306, F1: 0.5714

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.66000 | val 0.68656
  Epoch 020 - train 0.55721 | val 0.69396
  Epoch 026 - train 0.56547 | val 0.73018
  Classification -> best τ=0.455 (val F1=0.3012)
  Directional -> Accuracy: 0.6222, MCC: 0.2523, F1: 0.7536

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.67914 | val 0.72280
  Epoch 016 - train 0.62105 | val 0.82713
  Classification -> best τ=0.460 (val F1=0.2784)
  Directional -> Accuracy: 0.5745, MCC: 0.1723, F1: 0.7059

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.69296 | val 0.74619
  Epoch 016 - train 0.65791 | val 0.79816
  Classification -> best τ=0.500 (val F1=0.0138)
  Directional -> Accuracy: 0.4933, MCC: -0.0646, F1: 0.6042

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.63533 | val 0.63924
  Epoch 020 - train 0.57712 | val 0.66869
  Epoch 026 - train 0.54166 | val 0.67588
  Classification -> best τ=0.590 (val F1=0.4158)
  Directional -> Accuracy: 0.5490, MCC: 0.0833, F1: 0.6230

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.65679 | val 0.76958
  Epoch 016 - train 0.60916 | val 0.82977
  Classification -> best τ=0.485 (val F1=0.2335)
  Directional -> Accuracy: 0.4894, MCC: -0.0815, F1: 0.0769

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.70925 | val 0.69234
  Epoch 020 - train 0.63473 | val 0.82325
  Classification -> best τ=0.435 (val F1=0.2511)
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.65792 | val 0.64631
  Epoch 020 - train 0.60504 | val 0.95498
  Epoch 025 - train 0.53272 | val 0.96377
  Classification -> best τ=0.305 (val F1=0.1214)
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.5902

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.68966 | val 0.67517
  Epoch 020 - train 0.63357 | val 0.76819
  Epoch 025 - train 0.55303 | val 0.90510
  Classification -> best τ=0.565 (val F1=0.5112)
  Directional -> Accuracy: 0.6122, MCC: 0.2178, F1: 0.3448

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.66700 | val 0.77843
  Epoch 016 - train 0.58088 | val 0.89982
  Classification -> best τ=0.475 (val F1=0.1733)
  Directional -> Accuracy: 0.5857, MCC: 0.1154, F1: 0.3830

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.66223 | val 0.75406
  Epoch 016 - train 0.62418 | val 0.81052
  Classification -> best τ=0.480 (val F1=0.2500)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.68740 | val 0.93455
  Epoch 019 - train 0.57731 | val 0.87270
  Classification -> best τ=0.420 (val F1=0.1651)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.69849 | val 0.75166
  Epoch 019 - train 0.56895 | val 1.12288
  Classification -> best τ=0.415 (val F1=0.2392)
  Directional -> Accuracy: 0.4762, MCC: 0.1419, F1: 0.6333

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.68744 | val 0.62373
  Epoch 020 - train 0.63226 | val 0.65863
  Epoch 024 - train 0.63798 | val 0.73889
  Classification -> best τ=0.405 (val F1=0.3145)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.64948 | val 0.76846
  Epoch 016 - train 0.60251 | val 1.06803
  Classification -> best τ=0.390 (val F1=0.0636)
  Directional -> Accuracy: 0.4808, MCC: 0.0403, F1: 0.6197

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.67858 | val 0.69057
  Epoch 020 - train 0.58426 | val 0.90522
  Classification -> best τ=0.370 (val F1=0.2265)
  Directional -> Accuracy: 0.5362, MCC: 0.0367, F1: 0.6522

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.65081 | val 0.86753
  Epoch 016 - train 0.62525 | val 1.08456
  Classification -> best τ=0.590 (val F1=0.2651)
  Directional -> Accuracy: 0.3729, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.67904 | val 0.71884
  Epoch 016 - train 0.65659 | val 0.92476
  Classification -> best τ=0.360 (val F1=0.1217)
  Directional -> Accuracy: 0.6000, MCC: 0.0000, F1: 0.7500

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.67800 | val 0.91900
  Epoch 020 - train 0.61645 | val 1.45462
  Epoch 022 - train 0.59961 | val 1.63330
  Classification -> best τ=0.355 (val F1=0.2855)
  Directional -> Accuracy: 0.4769, MCC: 0.0998, F1: 0.2917

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.66902 | val 0.68524
  Epoch 020 - train 0.62230 | val 0.92777
  Epoch 024 - train 0.60000 | val 0.80077
  Classification -> best τ=0.430 (val F1=0.3376)
  Directional -> Accuracy: 0.4667, MCC: -0.1006, F1: 0.5556

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.64562 | val 0.70781
  Epoch 017 - train 0.60307 | val 0.81290
  Classification -> best τ=0.455 (val F1=0.2807)
  Directional -> Accuracy: 0.5106, MCC: -0.0699, F1: 0.6230

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.70018 | val 0.72451
  Epoch 020 - train 0.63691 | val 0.76099
  Classification -> best τ=0.490 (val F1=0.2072)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.68498 | val 0.73312
  Epoch 016 - train 0.64726 | val 0.88650
  Classification -> best τ=0.555 (val F1=0.2379)
  Directional -> Accuracy: 0.5690, MCC: 0.1255, F1: 0.6154

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.68204 | val 0.70858
  Epoch 020 - train 0.59961 | val 0.76085
  Epoch 022 - train 0.58840 | val 0.73135
  Classification -> best τ=0.575 (val F1=0.2390)
  Directional -> Accuracy: 0.5077, MCC: -0.0336, F1: 0.1579

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.70496 | val 0.66245
  Epoch 020 - train 0.60852 | val 0.72204
  Epoch 026 - train 0.62355 | val 0.64397
  Classification -> best τ=0.405 (val F1=0.3495)
  Directional -> Accuracy: 0.6071, MCC: 0.2118, F1: 0.6333

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.62833 | val 0.70925
  Epoch 016 - train 0.68173 | val 0.80523
  Classification -> best τ=0.470 (val F1=0.2686)
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.65214 | val 0.67822
  Epoch 020 - train 0.58874 | val 0.67253
  Epoch 030 - train 0.56194 | val 0.67431
  Epoch 034 - train 0.55218 | val 0.71114
  Classification -> best τ=0.650 (val F1=0.2582)
  Directional -> Accuracy: 0.4524, MCC: -0.0829, F1: 0.4651

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.60967 | val 0.71587
  Epoch 016 - train 0.61015 | val 0.83611
  Classification -> best τ=0.500 (val F1=0.1955)
  Directional -> Accuracy: 0.5614, MCC: 0.3307, F1: 0.3590

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.64834 | val 0.67647
  Epoch 020 - train 0.69234 | val 0.87482
  Epoch 028 - train 0.54952 | val 0.92461
  Classification -> best τ=0.460 (val F1=0.4966)
  Directional -> Accuracy: 0.5122, MCC: -0.0317, F1: 0.6429

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.68892 | val 0.70457
  Epoch 020 - train 0.62296 | val 0.83512
  Epoch 026 - train 0.60911 | val 1.13416
  Classification -> best τ=0.680 (val F1=0.2814)
  Directional -> Accuracy: 0.4884, MCC: -0.0318, F1: 0.3889

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.66088 | val 0.75746
  Epoch 020 - train 0.62974 | val 0.68586
  Epoch 028 - train 0.56483 | val 0.92230
  Classification -> best τ=0.435 (val F1=0.2517)
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.67985 | val 0.71620
  Epoch 016 - train 0.57171 | val 0.98187
  Classification -> best τ=0.525 (val F1=0.2399)
  Directional -> Accuracy: 0.4800, MCC: -0.1411, F1: 0.6286

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.66521 | val 0.67835
  Epoch 020 - train 0.61885 | val 0.65793
  Epoch 030 - train 0.57242 | val 0.72604
  Epoch 034 - train 0.53394 | val 0.78167
  Classification -> best τ=0.255 (val F1=0.3313)
  Directional -> Accuracy: 0.5616, MCC: 0.1446, F1: 0.5556

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.75094 | val 0.88879
  Epoch 016 - train 0.57877 | val 1.03066
  Classification -> best τ=0.465 (val F1=0.5590)
  Directional -> Accuracy: 0.5405, MCC: 0.1348, F1: 0.6531

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.69095 | val 0.77077
  Epoch 017 - train 0.60468 | val 0.87682
  Classification -> best τ=0.535 (val F1=0.1902)
  Directional -> Accuracy: 0.5227, MCC: 0.1439, F1: 0.6557

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.63776 | val 0.76431
  Epoch 016 - train 0.61387 | val 0.85636
  Classification -> best τ=0.450 (val F1=0.3634)
  Directional -> Accuracy: 0.5909, MCC: 0.1513, F1: 0.6582

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.70709 | val 0.70868
  Epoch 016 - train 0.57550 | val 0.76881
  Classification -> best τ=0.520 (val F1=0.1614)
  Directional -> Accuracy: 0.6667, MCC: 0.3708, F1: 0.6111

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.66319 | val 0.72247
  Epoch 020 - train 0.58270 | val 0.68875
  Epoch 022 - train 0.57865 | val 0.75635
  Classification -> best τ=0.485 (val F1=0.3172)
  Directional -> Accuracy: 0.4643, MCC: -0.0374, F1: 0.5714

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.63575 | val 0.78015
  Epoch 019 - train 0.57423 | val 0.82460
  Classification -> best τ=0.560 (val F1=0.2562)
  Directional -> Accuracy: 0.4565, MCC: 0.0086, F1: 0.3902

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.74896 | val 0.64697
  Epoch 020 - train 0.62993 | val 0.70133
  Epoch 025 - train 0.64119 | val 0.72168
  Classification -> best τ=0.440 (val F1=0.4141)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.69428 | val 0.72987
  Epoch 016 - train 0.59692 | val 0.79098
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.66754 | val 0.69328
  Epoch 020 - train 0.60704 | val 0.95310
  Epoch 023 - train 0.57991 | val 1.24324
  Classification -> best τ=0.265 (val F1=0.3844)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.64887 | val 0.69645
  Epoch 020 - train 0.67481 | val 0.68345
  Epoch 029 - train 0.60911 | val 0.68617
  Classification -> best τ=0.455 (val F1=0.5595)
  Directional -> Accuracy: 0.4565, MCC: -0.0763, F1: 0.2424

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.62350 | val 0.72740
  Epoch 020 - train 0.62402 | val 0.70065
  Epoch 030 - train 0.55942 | val 0.70618
  Epoch 033 - train 0.52543 | val 0.74083
  Classification -> best τ=0.545 (val F1=0.4431)
  Directional -> Accuracy: 0.6047, MCC: 0.1987, F1: 0.7302

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.64629 | val 0.69747
  Epoch 020 - train 0.66613 | val 0.59068
  Epoch 030 - train 0.59247 | val 0.63345
  Epoch 034 - train 0.55405 | val 0.64601
  Classification -> best τ=0.545 (val F1=0.5131)
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.71570 | val 0.86390
  Epoch 017 - train 0.65186 | val 1.46045
  Classification -> best τ=0.445 (val F1=0.1676)
  Directional -> Accuracy: 0.5536, MCC: 0.0801, F1: 0.6753

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.66038 | val 1.02653
  Epoch 020 - train 0.58312 | val 1.07602
  Classification -> best τ=0.620 (val F1=0.4250)
  Directional -> Accuracy: 0.5714, MCC: 0.1518, F1: 0.6000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.68285 | val 0.95363
  Epoch 018 - train 0.65069 | val 1.24213
  Classification -> best τ=0.450 (val F1=0.2325)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.68684 | val 0.73529
  Epoch 017 - train 0.61051 | val 0.88199
  Classification -> best τ=0.450 (val F1=0.1168)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.67388 | val 0.68363
  Epoch 020 - train 0.60649 | val 0.75990

[I 2026-02-25 03:14:30,030] Trial 182 finished with value: 0.2724818285105435 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 64, 'learning_rate': 0.0027010206118241007, 'weight_decay': 0.00036814692730549863, 'lr_patience': 7, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 0.4044470633026435, 'early_stopping_min_delta': 0.0039187038748598555}. Best is trial 179 with value: 0.3025280267941637.

  Epoch 022 - train 0.57982 | val 0.74285
  Classification -> best τ=0.470 (val F1=0.1106)
  Directional -> Accuracy: 0.5574, MCC: 0.1112, F1: 0.5263

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2724818285105435
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.63434 | val 0.92778
  Epoch 018 - train 0.57975 | val 0.81464
  Classification -> best τ=0.510 (val F1=0.2510)
  Directional -> Accuracy: 0.6053, MCC: 0.1845, F1: 0.4000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.66367 | val 0.69371
  Epoch 018 - train 0.56223 | val 0.71896
  Classification -> best τ=0.440 (val F1=0.1962)
  Directional -> Accuracy: 0.6444, MCC: 0.3126, F1: 0.7647

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.68437 | val 0.75313
  Epoch 016 - train 0.63831 | val 0.77165
  Classification -> best τ=0.465 (val F1=0.1506)
  Directional -> Accuracy: 0.5957, MCC: 0.2128, F1: 0.5581

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.64919 | val 0.80851
  Epoch 018 - train 0.64286 | val 0.83156
  Classification -> best τ=0.495 (val F1=0.1244)
  Directional -> Accuracy: 0.5467, MCC: 0.2261, F1: 0.3462

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.69232 | val 0.62384
  Epoch 020 - train 0.63281 | val 0.65412
  Epoch 025 - train 0.53343 | val 0.68067
  Classification -> best τ=0.585 (val F1=0.4598)
  Directional -> Accuracy: 0.4902, MCC: -0.0094, F1: 0.4583

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.64945 | val 0.72469
  Epoch 019 - train 0.56716 | val 0.88365
  Classification -> best τ=0.465 (val F1=0.2928)
  Directional -> Accuracy: 0.5319, MCC: 0.0687, F1: 0.2667

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.67241 | val 0.74295
  Epoch 018 - train 0.66858 | val 0.78167
  Classification -> best τ=0.450 (val F1=0.2435)
  Directional -> Accuracy: 0.4203, MCC: 0.0315, F1: 0.5745

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.66436 | val 0.75851
  Epoch 016 - train 0.66922 | val 0.93408
  Classification -> best τ=0.515 (val F1=0.1052)
  Directional -> Accuracy: 0.5581, MCC: 0.0269, F1: 0.2963

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.64979 | val 0.69089
  Epoch 019 - train 0.61706 | val 0.91102
  Classification -> best τ=0.375 (val F1=0.2408)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.65703 | val 0.70894
  Epoch 020 - train 0.56560 | val 0.80038
  Epoch 023 - train 0.55169 | val 0.82685
  Classification -> best τ=0.485 (val F1=0.2213)
  Directional -> Accuracy: 0.4429, MCC: 0.0160, F1: 0.5895

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.66103 | val 0.79734
  Epoch 017 - train 0.64302 | val 1.23194
  Classification -> best τ=0.455 (val F1=0.2118)
  Directional -> Accuracy: 0.5800, MCC: 0.1411, F1: 0.4615

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.64356 | val 0.84340
  Epoch 016 - train 0.57621 | val 1.32035
  Classification -> best τ=0.415 (val F1=0.2097)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.60636 | val 0.82248
  Epoch 016 - train 0.59112 | val 0.80301
  Classification -> best τ=0.390 (val F1=0.2246)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.71875 | val 0.66854
  Epoch 020 - train 0.59867 | val 0.66515
  Epoch 030 - train 0.60232 | val 0.94416
  Epoch 033 - train 0.55822 | val 1.15318
  Classification -> best τ=0.415 (val F1=0.3642)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6591

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.63766 | val 0.69827
  Epoch 019 - train 0.59997 | val 0.97756
  Classification -> best τ=0.565 (val F1=0.2160)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.66272 | val 0.68067
  Epoch 020 - train 0.58302 | val 0.73510
  Classification -> best τ=0.510 (val F1=0.2843)
  Directional -> Accuracy: 0.5652, MCC: 0.1442, F1: 0.5455

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.68594 | val 0.85855
  Epoch 017 - train 0.64515 | val 1.09866
  Classification -> best τ=0.475 (val F1=0.1336)
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.68023 | val 0.80407
  Epoch 020 - train 0.62152 | val 0.87470
  Epoch 022 - train 0.64577 | val 0.98511
  Classification -> best τ=0.375 (val F1=0.2153)
  Directional -> Accuracy: 0.5200, MCC: 0.1820, F1: 0.4194

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.65046 | val 1.13363
  Epoch 016 - train 0.62761 | val 1.45180
  Classification -> best τ=0.490 (val F1=0.2535)
  Directional -> Accuracy: 0.4923, MCC: 0.1307, F1: 0.3265

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.66723 | val 0.67752
  Epoch 020 - train 0.61362 | val 0.66483
  Epoch 030 - train 0.56221 | val 0.85338
  Epoch 035 - train 0.56691 | val 1.22802
  Classification -> best τ=0.450 (val F1=0.3259)
  Directional -> Accuracy: 0.4800, MCC: 0.0420, F1: 0.2353

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.65706 | val 0.69261
  Epoch 020 - train 0.58146 | val 1.00067
  Epoch 024 - train 0.52276 | val 1.30143
  Classification -> best τ=0.445 (val F1=0.3307)
  Directional -> Accuracy: 0.5106, MCC: -0.0247, F1: 0.5965

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.68612 | val 0.73798
  Epoch 016 - train 0.64893 | val 0.88977
  Classification -> best τ=0.490 (val F1=0.1149)
  Directional -> Accuracy: 0.5303, MCC: 0.0606, F1: 0.5231

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.64709 | val 0.77293
  Epoch 016 - train 0.65454 | val 0.76840
  Classification -> best τ=0.525 (val F1=0.3498)
  Directional -> Accuracy: 0.5690, MCC: 0.1255, F1: 0.6154

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.64333 | val 0.70749
  Epoch 017 - train 0.60887 | val 0.87515
  Classification -> best τ=0.445 (val F1=0.0314)
  Directional -> Accuracy: 0.4769, MCC: 0.0000, F1: 0.6458

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.65873 | val 0.68029
  Epoch 020 - train 0.56387 | val 0.71669
  Epoch 027 - train 0.52820 | val 0.87369
  Classification -> best τ=0.380 (val F1=0.3495)
  Directional -> Accuracy: 0.5714, MCC: 0.1054, F1: 0.7143

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.72892 | val 0.72340
  Epoch 020 - train 0.61075 | val 0.92782
  Epoch 022 - train 0.62009 | val 1.14982
  Classification -> best τ=0.510 (val F1=0.2241)
  Directional -> Accuracy: 0.5000, MCC: 0.2317, F1: 0.6349

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.71027 | val 0.70565
  Epoch 016 - train 0.63525 | val 0.72668
  Classification -> best τ=0.525 (val F1=0.1273)
  Directional -> Accuracy: 0.4524, MCC: -0.0962, F1: 0.4889

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.63465 | val 0.73280
  Epoch 016 - train 0.66842 | val 0.78910
  Classification -> best τ=0.515 (val F1=0.1625)
  Directional -> Accuracy: 0.4737, MCC: 0.0228, F1: 0.3182

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.71163 | val 0.66750
  Epoch 020 - train 0.65155 | val 0.73379
  Epoch 030 - train 0.58393 | val 1.13720
  Epoch 040 - train 0.54019 | val 1.28946
  Epoch 041 - train 0.54033 | val 1.23786
  Classification -> best τ=0.570 (val F1=0.3671)
  Directional -> Accuracy: 0.5366, MCC: 0.0417, F1: 0.6415

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.68884 | val 0.69091
  Epoch 020 - train 0.60727 | val 0.98514
  Epoch 026 - train 0.61645 | val 0.70652
  Classification -> best τ=0.555 (val F1=0.2814)
  Directional -> Accuracy: 0.5349, MCC: 0.0831, F1: 0.6000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.69239 | val 0.64742
  Epoch 020 - train 0.66277 | val 0.65878
  Epoch 026 - train 0.57736 | val 0.65628
  Classification -> best τ=0.720 (val F1=0.2525)
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.62671 | val 0.81602
  Epoch 017 - train 0.57749 | val 1.21499
  Classification -> best τ=0.545 (val F1=0.2399)
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.66492 | val 0.70036
  Epoch 020 - train 0.60238 | val 0.96335
  Epoch 022 - train 0.60243 | val 0.82032
  Classification -> best τ=0.605 (val F1=0.2725)
  Directional -> Accuracy: 0.4658, MCC: 0.1483, F1: 0.0930

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.64385 | val 0.81845
  Epoch 017 - train 0.65624 | val 0.76467
  Classification -> best τ=0.545 (val F1=0.1992)
  Directional -> Accuracy: 0.5946, MCC: 0.2271, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.67482 | val 0.71978
  Epoch 016 - train 0.64158 | val 0.80883
  Classification -> best τ=0.555 (val F1=0.3103)
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.67013 | val 0.75565
  Epoch 016 - train 0.62448 | val 0.77334
  Classification -> best τ=0.455 (val F1=0.3280)
  Directional -> Accuracy: 0.5909, MCC: 0.1443, F1: 0.6667

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.68642 | val 0.73354
  Epoch 019 - train 0.52924 | val 0.90963
  Classification -> best τ=0.490 (val F1=0.3343)
  Directional -> Accuracy: 0.6905, MCC: 0.3977, F1: 0.6667

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.66332 | val 0.68656
  Epoch 016 - train 0.61245 | val 0.76051
  Classification -> best τ=0.465 (val F1=0.2450)
  Directional -> Accuracy: 0.4821, MCC: -0.0185, F1: 0.5246

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.60029 | val 0.85853
  Epoch 016 - train 0.67069 | val 1.05075
  Classification -> best τ=0.535 (val F1=0.2441)
  Directional -> Accuracy: 0.4130, MCC: -0.0062, F1: 0.1818

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.71139 | val 0.67157
  Epoch 020 - train 0.58821 | val 0.71696
  Epoch 027 - train 0.55193 | val 0.71726
  Classification -> best τ=0.355 (val F1=0.3182)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.71252 | val 0.76398
  Epoch 016 - train 0.69660 | val 0.70029
  Classification -> best τ=0.480 (val F1=0.0585)
  Directional -> Accuracy: 0.4595, MCC: -0.1435, F1: 0.5833

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.64651 | val 0.66609
  Epoch 020 - train 0.61845 | val 0.84513
  Epoch 024 - train 0.57433 | val 0.87709
  Classification -> best τ=0.570 (val F1=0.3880)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.64151 | val 0.73016
  Epoch 018 - train 0.62599 | val 0.67991
  Classification -> best τ=0.465 (val F1=0.4692)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.0000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.65874 | val 0.72755
  Epoch 016 - train 0.64859 | val 0.73316
  Classification -> best τ=0.565 (val F1=0.3651)
  Directional -> Accuracy: 0.4884, MCC: 0.0068, F1: 0.4500

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.61701 | val 0.61944
  Epoch 020 - train 0.59508 | val 0.79874
  Epoch 030 - train 0.54168 | val 0.60981
  Epoch 038 - train 0.57005 | val 0.64415
  Classification -> best τ=0.490 (val F1=0.5261)
  Directional -> Accuracy: 0.3878, MCC: -0.0475, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.66058 | val 0.84243
  Epoch 017 - train 0.61032 | val 1.65125
  Classification -> best τ=0.480 (val F1=0.2455)
  Directional -> Accuracy: 0.5179, MCC: 0.2215, F1: 0.1818

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.65292 | val 0.95861
  Epoch 016 - train 0.59768 | val 1.02572
  Classification -> best τ=0.535 (val F1=0.4000)
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.66246 | val 0.81312
  Epoch 016 - train 0.66399 | val 1.13370
  Classification -> best τ=0.405 (val F1=0.2408)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.63546 | val 0.74856
  Epoch 020 - train 0.60341 | val 0.86159
  Classification -> best τ=0.490 (val F1=0.2465)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.68636 | val 0.73865

[I 2026-02-25 03:16:35,097] Trial 183 finished with value: 0.2606269079039135 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 64, 'learning_rate': 0.0035256251187612874, 'weight_decay': 0.00025333032388299417, 'lr_patience': 7, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 0.29949900754776143, 'early_stopping_min_delta': 0.003713945361785206}. Best is trial 179 with value: 0.3025280267941637.

  Epoch 019 - train 0.64194 | val 0.86717
  Classification -> best τ=0.435 (val F1=0.2847)
  Directional -> Accuracy: 0.5410, MCC: 0.0672, F1: 0.3913

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2606269079039135
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.65411 | val 0.67355
  Epoch 017 - train 0.60806 | val 0.75378
  Classification -> best τ=0.455 (val F1=0.2627)
  Directional -> Accuracy: 0.5263, MCC: 0.0837, F1: 0.5610

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.66089 | val 0.69598
  Epoch 020 - train 0.60942 | val 0.70337
  Epoch 030 - train 0.58255 | val 0.79903
  Epoch 031 - train 0.56690 | val 0.78471
  Classification -> best τ=0.410 (val F1=0.1870)
  Directional -> Accuracy: 0.6667, MCC: 0.3050, F1: 0.7273

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.65027 | val 0.74341
  Epoch 019 - train 0.66221 | val 0.86811
  Classification -> best τ=0.545 (val F1=0.3237)
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.69468 | val 0.73951
  Epoch 016 - train 0.66392 | val 0.94234
  Classification -> best τ=0.520 (val F1=0.0914)
  Directional -> Accuracy: 0.5200, MCC: 0.0267, F1: 0.5714

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.64963 | val 0.67350
  Epoch 020 - train 0.57654 | val 0.66799
  Epoch 029 - train 0.56463 | val 0.67335
  Classification -> best τ=0.515 (val F1=0.4158)
  Directional -> Accuracy: 0.5882, MCC: 0.2176, F1: 0.7123

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.68498 | val 0.71612
  Epoch 016 - train 0.61913 | val 0.75609
  Classification -> best τ=0.475 (val F1=0.2357)
  Directional -> Accuracy: 0.4894, MCC: 0.0000, F1: 0.6571

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.70234 | val 0.69478
  Epoch 020 - train 0.65708 | val 0.68798
  Epoch 021 - train 0.66909 | val 0.69784
  Classification -> best τ=0.350 (val F1=0.2728)
  Directional -> Accuracy: 0.4493, MCC: 0.1762, F1: 0.5957

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.75739 | val 0.69770
  Epoch 018 - train 0.64028 | val 0.91559
  Classification -> best τ=0.490 (val F1=0.1688)
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.67779 | val 0.73008
  Epoch 020 - train 0.61603 | val 0.85918
  Epoch 021 - train 0.56467 | val 0.89114
  Classification -> best τ=0.480 (val F1=0.1945)
  Directional -> Accuracy: 0.6122, MCC: 0.2178, F1: 0.3448

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.61841 | val 0.69970
  Epoch 018 - train 0.59326 | val 0.87775
  Classification -> best τ=0.535 (val F1=0.1869)
  Directional -> Accuracy: 0.5571, MCC: 0.0481, F1: 0.3404

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.66717 | val 0.73725
  Epoch 017 - train 0.62636 | val 0.90739
  Classification -> best τ=0.425 (val F1=0.2063)
  Directional -> Accuracy: 0.5400, MCC: 0.0164, F1: 0.0800

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.63640 | val 1.23283
  Epoch 020 - train 0.58821 | val 1.69504
  Classification -> best τ=0.470 (val F1=0.2172)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6420

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.68925 | val 0.92321
  Epoch 018 - train 0.59239 | val 0.97420
  Classification -> best τ=0.415 (val F1=0.3002)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.67382 | val 0.68275
  Epoch 020 - train 0.63607 | val 0.67815
  Classification -> best τ=0.385 (val F1=0.3493)
  Directional -> Accuracy: 0.5333, MCC: 0.0981, F1: 0.6585

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.61762 | val 0.70903
  Epoch 016 - train 0.64001 | val 0.85379
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.62357 | val 0.71011
  Epoch 020 - train 0.59574 | val 0.82001
  Classification -> best τ=0.555 (val F1=0.3475)
  Directional -> Accuracy: 0.5072, MCC: 0.0411, F1: 0.4333

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.66694 | val 0.94454
  Epoch 018 - train 0.63145 | val 1.17862
  Classification -> best τ=0.530 (val F1=0.1303)
  Directional -> Accuracy: 0.3729, MCC: -0.2177, F1: 0.3934

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.69652 | val 0.74761
  Epoch 016 - train 0.65063 | val 0.96512
  Classification -> best τ=0.525 (val F1=0.1976)
  Directional -> Accuracy: 0.3867, MCC: -0.1814, F1: 0.3611

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.66871 | val 0.81724
  Epoch 018 - train 0.63067 | val 1.26021
  Classification -> best τ=0.460 (val F1=0.2782)
  Directional -> Accuracy: 0.5077, MCC: 0.1597, F1: 0.3600

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.69702 | val 0.67696
  Epoch 020 - train 0.63688 | val 0.78235
  Epoch 021 - train 0.62251 | val 0.74125
  Classification -> best τ=0.490 (val F1=0.2912)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.66490 | val 0.71323
  Epoch 018 - train 0.56736 | val 1.00923
  Classification -> best τ=0.565 (val F1=0.1918)
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.65376 | val 0.75902
  Epoch 016 - train 0.65775 | val 0.77558
  Classification -> best τ=0.540 (val F1=0.2304)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.1951

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.70628 | val 0.74482
  Epoch 020 - train 0.63860 | val 0.73120
  Classification -> best τ=0.485 (val F1=0.2760)
  Directional -> Accuracy: 0.5000, MCC: 0.0455, F1: 0.4528

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.72171 | val 0.70016
  Epoch 018 - train 0.63522 | val 0.74068
  Classification -> best τ=0.430 (val F1=0.1614)
  Directional -> Accuracy: 0.4769, MCC: 0.0000, F1: 0.6458

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.67991 | val 0.66079
  Epoch 020 - train 0.59023 | val 0.68579
  Epoch 023 - train 0.58654 | val 0.67761
  Classification -> best τ=0.460 (val F1=0.4352)
  Directional -> Accuracy: 0.5179, MCC: 0.1188, F1: 0.3721

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.60930 | val 0.71474
  Epoch 020 - train 0.63593 | val 0.73449
  Epoch 021 - train 0.59416 | val 0.71950
  Classification -> best τ=0.490 (val F1=0.2241)
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.73195 | val 0.69203
  Epoch 016 - train 0.63363 | val 0.69393
  Classification -> best τ=0.520 (val F1=0.2582)
  Directional -> Accuracy: 0.5238, MCC: -0.0323, F1: 0.6429

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.66986 | val 0.78241
  Epoch 016 - train 0.64933 | val 0.74663
  Classification -> best τ=0.465 (val F1=0.2347)
  Directional -> Accuracy: 0.5088, MCC: 0.2428, F1: 0.2222

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.67406 | val 0.67673
  Epoch 020 - train 0.62771 | val 0.66002
  Epoch 030 - train 0.59423 | val 0.90695
  Epoch 040 - train 0.51047 | val 1.36313
  Classification -> best τ=0.450 (val F1=0.4345)
  Directional -> Accuracy: 0.5122, MCC: -0.0733, F1: 0.6667

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.70146 | val 0.69137
  Epoch 020 - train 0.65532 | val 0.75286
  Epoch 021 - train 0.55217 | val 0.83773
  Classification -> best τ=0.555 (val F1=0.2814)
  Directional -> Accuracy: 0.5349, MCC: 0.0783, F1: 0.5833

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.71510 | val 0.72038
  Epoch 020 - train 0.62654 | val 0.65050
  Epoch 030 - train 0.56473 | val 0.70832
  Epoch 033 - train 0.51310 | val 0.67469
  Classification -> best τ=0.490 (val F1=0.2517)
  Directional -> Accuracy: 0.5581, MCC: 0.0981, F1: 0.6885

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.62876 | val 0.68773
  Epoch 016 - train 0.59820 | val 0.89741
  Classification -> best τ=0.485 (val F1=0.2645)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.63689 | val 0.66231
  Epoch 020 - train 0.60788 | val 1.00548
  Epoch 025 - train 0.58072 | val 1.22517
  Classification -> best τ=0.400 (val F1=0.2721)
  Directional -> Accuracy: 0.5616, MCC: 0.1446, F1: 0.5556

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.66972 | val 0.77911
  Epoch 016 - train 0.61832 | val 0.79516
  Classification -> best τ=0.505 (val F1=0.2833)
  Directional -> Accuracy: 0.5405, MCC: 0.1647, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.67625 | val 0.90990
  Epoch 018 - train 0.62227 | val 0.93583
  Classification -> best τ=0.575 (val F1=0.1749)
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.66187 | val 0.73804
  Epoch 016 - train 0.63302 | val 0.80078
  Classification -> best τ=0.490 (val F1=0.3525)
  Directional -> Accuracy: 0.5909, MCC: 0.1587, F1: 0.6494

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.64823 | val 0.70705
  Epoch 016 - train 0.69484 | val 0.82556
  Classification -> best τ=0.480 (val F1=0.2986)
  Directional -> Accuracy: 0.6667, MCC: 0.3364, F1: 0.6667

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.64397 | val 0.69882
  Epoch 016 - train 0.63439 | val 0.72748
  Classification -> best τ=0.350 (val F1=0.2530)
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.6341

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.66393 | val 0.72280
  Epoch 017 - train 0.55657 | val 0.85206
  Classification -> best τ=0.445 (val F1=0.2800)
  Directional -> Accuracy: 0.6304, MCC: 0.1859, F1: 0.7671

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.65714 | val 0.69708
  Epoch 020 - train 0.63795 | val 0.65595
  Epoch 030 - train 0.64604 | val 0.61714
  Epoch 040 - train 0.59482 | val 0.71267
  Epoch 050 - train 0.57305 | val 0.71723
  Classification -> best τ=0.195 (val F1=0.4825)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.68348 | val 0.75341
  Epoch 016 - train 0.56780 | val 0.76987
  Classification -> best τ=0.445 (val F1=0.0585)
  Directional -> Accuracy: 0.4595, MCC: -0.0985, F1: 0.5238

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.68005 | val 0.93620
  Epoch 020 - train 0.61950 | val 0.78304
  Epoch 021 - train 0.60037 | val 0.94763
  Classification -> best τ=0.515 (val F1=0.3963)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.75723 | val 0.70870
  Epoch 020 - train 0.60599 | val 0.68692
  Epoch 030 - train 0.60822 | val 0.79415
  Epoch 036 - train 0.54482 | val 0.77223
  Classification -> best τ=0.505 (val F1=0.2748)
  Directional -> Accuracy: 0.5435, MCC: 0.1019, F1: 0.4878

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.73093 | val 0.69920
  Epoch 020 - train 0.63377 | val 0.64846
  Epoch 030 - train 0.58329 | val 0.61717
  Epoch 040 - train 0.51957 | val 0.80747
  Classification -> best τ=0.505 (val F1=0.5270)
  Directional -> Accuracy: 0.5116, MCC: -0.0880, F1: 0.6557

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.71178 | val 0.66970
  Epoch 020 - train 0.61114 | val 0.70630
  Epoch 027 - train 0.56482 | val 0.66315
  Classification -> best τ=0.490 (val F1=0.4682)
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.66509 | val 0.70251
  Epoch 020 - train 0.62751 | val 1.36563
  Epoch 026 - train 0.61884 | val 0.89520
  Classification -> best τ=0.475 (val F1=0.0422)
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.65389 | val 0.89069
  Epoch 016 - train 0.62298 | val 1.04766
  Classification -> best τ=0.475 (val F1=0.2230)
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.70456 | val 0.98436
  Epoch 017 - train 0.65280 | val 1.16284
  Classification -> best τ=0.390 (val F1=0.2128)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.61647 | val 0.77356
  Epoch 019 - train 0.57421 | val 0.92954
  Classification -> best τ=0.530 (val F1=0.1221)
  Directional -> Accuracy: 0.4821, MCC: -0.1289, F1: 0.6420

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.65418 | val 0.75573
  Epoch 020 - train 0.62718 | val 0.87375
  Epoch 021 - train 0.61299 | val 0.84283
  Classification -> best τ=0.470 (val F1=0.2136)
  Directional -> Accuracy: 0.5246, MCC: 0.0191, F1: 0.2162

[I 2026-02-25 03:18:39,595] Trial 184 finished with value: 0.25673086185330873 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 64, 'learning_rate': 0.004172905760675529, 'weight_decay': 0.0005493322605635713, 'lr_patience': 7, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 0.33693221348712193, 'early_stopping_min_delta': 0.004070082171285786}. Best is trial 179 with value: 0.3025280267941637.

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.25673086185330873
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.66227 | val 0.67254
  Epoch 020 - train 0.57512 | val 0.84182
  Epoch 021 - train 0.59257 | val 0.85370
  Classification -> best τ=0.410 (val F1=0.2412)
  Directional -> Accuracy: 0.4737, MCC: 0.0936, F1: 0.6226

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.67682 | val 0.68407
  Epoch 019 - train 0.57879 | val 0.69492
  Classification -> best τ=0.435 (val F1=0.2573)
  Directional -> Accuracy: 0.6222, MCC: 0.2523, F1: 0.7536

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.69136 | val 0.78188
  Epoch 017 - train 0.64140 | val 0.80092
  Classification -> best τ=0.465 (val F1=0.3577)
  Directional -> Accuracy: 0.5106, MCC: 0.0516, F1: 0.4103

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.67261 | val 0.78697
  Epoch 016 - train 0.65248 | val 0.76735
  Classification -> best τ=0.510 (val F1=0.1210)
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.61631 | val 0.66977
  Epoch 020 - train 0.61554 | val 0.67610
  Epoch 027 - train 0.57459 | val 0.71418
  Classification -> best τ=0.590 (val F1=0.4513)
  Directional -> Accuracy: 0.4314, MCC: -0.1577, F1: 0.5085

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.64299 | val 0.70717
  Epoch 018 - train 0.58142 | val 0.87972
  Classification -> best τ=0.490 (val F1=0.2928)
  Directional -> Accuracy: 0.5319, MCC: 0.1506, F1: 0.0833

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.66529 | val 0.69042
  Epoch 020 - train 0.65457 | val 0.85059
  Epoch 022 - train 0.63902 | val 0.76415
  Classification -> best τ=0.500 (val F1=0.1932)
  Directional -> Accuracy: 0.5362, MCC: 0.0937, F1: 0.5152

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.61978 | val 0.73463
  Epoch 018 - train 0.55468 | val 0.93727
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.5902

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.62102 | val 0.69113
  Epoch 018 - train 0.61183 | val 0.77273
  Classification -> best τ=0.390 (val F1=0.2820)
  Directional -> Accuracy: 0.4694, MCC: -0.0921, F1: 0.3500

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.64149 | val 0.69921
  Epoch 018 - train 0.60042 | val 0.77176
  Classification -> best τ=0.480 (val F1=0.1923)
  Directional -> Accuracy: 0.4286, MCC: -0.0657, F1: 0.5455

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.69185 | val 0.68809
  Epoch 019 - train 0.60815 | val 1.56494
  Classification -> best τ=0.450 (val F1=0.2621)
  Directional -> Accuracy: 0.5800, MCC: 0.1520, F1: 0.5333

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.61945 | val 0.78689
  Epoch 017 - train 0.66389 | val 1.05460
  Classification -> best τ=0.485 (val F1=0.3245)
  Directional -> Accuracy: 0.5172, MCC: 0.0346, F1: 0.5333

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.61910 | val 0.88745
  Epoch 016 - train 0.60558 | val 0.80401
  Classification -> best τ=0.440 (val F1=0.1908)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.66011 | val 0.61091
  Epoch 020 - train 0.63469 | val 0.79129
  Epoch 025 - train 0.59657 | val 0.80265
  Classification -> best τ=0.410 (val F1=0.3916)
  Directional -> Accuracy: 0.5167, MCC: 0.0467, F1: 0.6420

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.63298 | val 0.99165
  Epoch 020 - train 0.58994 | val 1.22964
  Classification -> best τ=0.555 (val F1=0.2673)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.66221 | val 0.73482
  Epoch 020 - train 0.61485 | val 0.76535
  Epoch 022 - train 0.57419 | val 0.73466
  Classification -> best τ=0.655 (val F1=0.2723)
  Directional -> Accuracy: 0.5217, MCC: 0.1079, F1: 0.3529

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.64888 | val 0.95892
  Epoch 017 - train 0.61261 | val 1.51719
  Classification -> best τ=0.655 (val F1=0.1291)
  Directional -> Accuracy: 0.3729, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.66756 | val 0.84529
  Epoch 016 - train 0.65694 | val 0.80925
  Classification -> best τ=0.555 (val F1=0.0942)
  Directional -> Accuracy: 0.4667, MCC: 0.0375, F1: 0.3750

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.70588 | val 0.91098
  Epoch 016 - train 0.65074 | val 1.39137
  Classification -> best τ=0.485 (val F1=0.1417)
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.64479 | val 0.67119
  Epoch 019 - train 0.62130 | val 0.68214
  Classification -> best τ=0.495 (val F1=0.3686)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.65118 | val 0.70343
  Epoch 016 - train 0.62881 | val 0.78137
  Classification -> best τ=0.510 (val F1=0.2267)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.69479 | val 0.68599
  Epoch 020 - train 0.63901 | val 0.73260
  Epoch 024 - train 0.62834 | val 0.76361
  Classification -> best τ=0.470 (val F1=0.1760)
  Directional -> Accuracy: 0.5303, MCC: 0.0845, F1: 0.6517

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.64163 | val 0.79695
  Epoch 018 - train 0.65501 | val 0.80350
  Classification -> best τ=0.475 (val F1=0.2529)
  Directional -> Accuracy: 0.5862, MCC: 0.1111, F1: 0.7273

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.66283 | val 0.71012
  Epoch 016 - train 0.61480 | val 0.94967
  Classification -> best τ=0.435 (val F1=0.2174)
  Directional -> Accuracy: 0.4769, MCC: 0.0000, F1: 0.6458

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.65919 | val 0.66001
  Epoch 020 - train 0.60993 | val 0.68835
  Epoch 028 - train 0.55892 | val 0.71508
  Classification -> best τ=0.485 (val F1=0.3267)
  Directional -> Accuracy: 0.5536, MCC: 0.1078, F1: 0.5763

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.72952 | val 0.72952
  Epoch 016 - train 0.62821 | val 0.79827
  Classification -> best τ=0.555 (val F1=0.0198)
  Directional -> Accuracy: 0.4130, MCC: -0.3220, F1: 0.0690

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.66520 | val 0.70749
  Epoch 016 - train 0.65806 | val 0.69931
  Classification -> best τ=0.545 (val F1=0.1936)
  Directional -> Accuracy: 0.5000, MCC: -0.0280, F1: 0.5714

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.69398 | val 0.75847
  Epoch 018 - train 0.61214 | val 0.89846
  Classification -> best τ=0.385 (val F1=0.1939)
  Directional -> Accuracy: 0.5789, MCC: 0.2374, F1: 0.5000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.69190 | val 0.83351
  Epoch 020 - train 0.60146 | val 0.73147
  Epoch 030 - train 0.56700 | val 1.05433
  Epoch 031 - train 0.60182 | val 0.93684
  Classification -> best τ=0.570 (val F1=0.4382)
  Directional -> Accuracy: 0.5610, MCC: 0.0983, F1: 0.6786

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.68454 | val 0.70083
  Epoch 019 - train 0.60669 | val 0.97739
  Classification -> best τ=0.615 (val F1=0.2814)
  Directional -> Accuracy: 0.4884, MCC: -0.0353, F1: 0.3529

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.66378 | val 0.70120
  Epoch 020 - train 0.66654 | val 0.81513
  Epoch 028 - train 0.59662 | val 0.74304
  Classification -> best τ=0.500 (val F1=0.2517)
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.67038 | val 0.72353
  Epoch 018 - train 0.58275 | val 1.37786
  Classification -> best τ=0.540 (val F1=0.2969)
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.65794 | val 0.69639
  Epoch 020 - train 0.62346 | val 0.66873
  Epoch 024 - train 0.59479 | val 0.66368
  Classification -> best τ=0.405 (val F1=0.2952)
  Directional -> Accuracy: 0.5616, MCC: 0.1446, F1: 0.5556

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.67389 | val 0.81930
  Epoch 018 - train 0.61275 | val 0.83625
  Classification -> best τ=0.510 (val F1=0.2316)
  Directional -> Accuracy: 0.5676, MCC: 0.1737, F1: 0.6522

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.66860 | val 0.75537
  Epoch 016 - train 0.65411 | val 0.77750
  Classification -> best τ=0.440 (val F1=0.1329)
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.67401 | val 0.78584
  Epoch 016 - train 0.66074 | val 0.77587
  Classification -> best τ=0.515 (val F1=0.4328)
  Directional -> Accuracy: 0.6061, MCC: 0.2406, F1: 0.6061

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.68962 | val 0.69201
  Epoch 016 - train 0.58563 | val 0.85944
  Classification -> best τ=0.470 (val F1=0.2031)
  Directional -> Accuracy: 0.6429, MCC: 0.3290, F1: 0.5714

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.63822 | val 0.67758
  Epoch 020 - train 0.62119 | val 0.70772
  Epoch 026 - train 0.56434 | val 0.71914
  Classification -> best τ=0.460 (val F1=0.2755)
  Directional -> Accuracy: 0.5179, MCC: 0.0998, F1: 0.6197

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.61038 | val 0.80776
  Epoch 016 - train 0.56479 | val 1.00233
  Classification -> best τ=0.515 (val F1=0.3105)
  Directional -> Accuracy: 0.5870, MCC: 0.0726, F1: 0.6984

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.75692 | val 0.66993
  Epoch 020 - train 0.62744 | val 0.64885
  Epoch 030 - train 0.62089 | val 0.77173
  Epoch 034 - train 0.58171 | val 0.86833
  Classification -> best τ=0.420 (val F1=0.5247)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.69478 | val 0.79012
  Epoch 016 - train 0.62388 | val 0.74201
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.62553 | val 0.73634
  Epoch 018 - train 0.57253 | val 1.11441
  Classification -> best τ=0.425 (val F1=0.3844)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.61477 | val 0.67628
  Epoch 020 - train 0.67063 | val 0.64205
  Epoch 030 - train 0.57856 | val 0.65220
  Epoch 035 - train 0.58814 | val 0.70174
  Classification -> best τ=0.405 (val F1=0.5003)
  Directional -> Accuracy: 0.5217, MCC: 0.0349, F1: 0.5769

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.62777 | val 0.73855
  Epoch 020 - train 0.55818 | val 0.66212
  Epoch 030 - train 0.61492 | val 0.56518
  Epoch 040 - train 0.52327 | val 0.92177
  Epoch 047 - train 0.46266 | val 0.87853
  Classification -> best τ=0.565 (val F1=0.6031)
  Directional -> Accuracy: 0.5814, MCC: 0.1223, F1: 0.6786

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.68420 | val 0.69516
  Epoch 020 - train 0.52472 | val 0.64161
  Epoch 030 - train 0.53745 | val 0.76739
  Epoch 031 - train 0.57755 | val 0.73422
  Classification -> best τ=0.560 (val F1=0.5421)
  Directional -> Accuracy: 0.4082, MCC: 0.1149, F1: 0.5672

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.68144 | val 0.86420
  Epoch 017 - train 0.67483 | val 1.41024
  Classification -> best τ=0.420 (val F1=0.0578)
  Directional -> Accuracy: 0.5357, MCC: 0.1371, F1: 0.3810

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.64210 | val 0.90062
  Epoch 020 - train 0.59554 | val 1.06394
  Epoch 021 - train 0.57426 | val 1.30926
  Classification -> best τ=0.590 (val F1=0.3204)
  Directional -> Accuracy: 0.5000, MCC: -0.0039, F1: 0.4615

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.66697 | val 1.19806
  Epoch 018 - train 0.61349 | val 1.31378
  Classification -> best τ=0.505 (val F1=0.1866)
  Directional -> Accuracy: 0.5741, MCC: 0.1657, F1: 0.6849

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.63791 | val 0.71827
  Epoch 020 - train 0.59446 | val 0.78016
  Epoch 026 - train 0.58982 | val 0.80745
  Classification -> best τ=0.495 (val F1=0.2791)
  Directional -> Accuracy: 0.4643, MCC: -0.0702, F1: 0.4643

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.64571 | val 0.66501
  Epoch 020 - train 0.61996 | val 0.92493

[I 2026-02-25 03:20:42,822] Trial 185 finished with value: 0.26642364746928676 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 64, 'learning_rate': 0.002851323671610583, 'weight_decay': 0.0004034843696697056, 'lr_patience': 7, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 0.38584283562190946, 'early_stopping_min_delta': 0.0036753045955488497}. Best is trial 179 with value: 0.3025280267941637.

  Epoch 024 - train 0.61241 | val 0.85991
  Classification -> best τ=0.335 (val F1=0.3349)
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.26642364746928676
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.66295 | val 0.65246
  Epoch 020 - train 0.64443 | val 0.67461
  Epoch 030 - train 0.61704 | val 0.69606
  Epoch 032 - train 0.63842 | val 0.78458
  Classification -> best τ=0.565 (val F1=0.2919)
  Directional -> Accuracy: 0.6053, MCC: 0.1845, F1: 0.4000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.64254 | val 0.69046
  Epoch 020 - train 0.55466 | val 0.71985
  Epoch 027 - train 0.51943 | val 0.91670
  Classification -> best τ=0.430 (val F1=0.2280)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.68779 | val 0.70055
  Epoch 020 - train 0.64262 | val 0.84027
  Epoch 021 - train 0.60861 | val 0.86414
  Classification -> best τ=0.525 (val F1=0.2759)
  Directional -> Accuracy: 0.4681, MCC: -0.0135, F1: 0.0741

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.68214 | val 0.70018
  Epoch 020 - train 0.65785 | val 0.73559
  Epoch 021 - train 0.64654 | val 0.73800
  Classification -> best τ=0.585 (val F1=0.1590)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.66874 | val 0.64727
  Epoch 020 - train 0.65264 | val 0.81502
  Epoch 028 - train 0.63681 | val 1.00097
  Classification -> best τ=0.650 (val F1=0.5045)
  Directional -> Accuracy: 0.5098, MCC: 0.0280, F1: 0.4898

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.65434 | val 0.69883
  Epoch 016 - train 0.64212 | val 0.70581
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4894, MCC: 0.0000, F1: 0.6571

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.69949 | val 0.69113
  Epoch 017 - train 0.67598 | val 0.69671
  Classification -> best τ=0.430 (val F1=0.2728)
  Directional -> Accuracy: 0.4203, MCC: 0.0033, F1: 0.5652

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.61432 | val 0.58129
  Epoch 020 - train 0.50081 | val 0.76534
  Epoch 025 - train 0.52198 | val 1.15809
  Classification -> best τ=0.300 (val F1=0.2180)
  Directional -> Accuracy: 0.4651, MCC: 0.0696, F1: 0.5818

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.64370 | val 0.84627
  Epoch 016 - train 0.58351 | val 0.83071
  Classification -> best τ=0.465 (val F1=0.2820)
  Directional -> Accuracy: 0.5918, MCC: 0.1557, F1: 0.4444

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.66844 | val 0.71215
  Epoch 017 - train 0.63168 | val 0.75282
  Classification -> best τ=0.485 (val F1=0.2012)
  Directional -> Accuracy: 0.4429, MCC: -0.0630, F1: 0.5063

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.67595 | val 0.79138
  Epoch 020 - train 0.63390 | val 1.04347
  Epoch 026 - train 0.65075 | val 1.12497
  Classification -> best τ=0.575 (val F1=0.3118)
  Directional -> Accuracy: 0.6200, MCC: 0.2766, F1: 0.3448

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.66791 | val 0.71390
  Epoch 019 - train 0.61805 | val 1.02562
  Classification -> best τ=0.450 (val F1=0.2097)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.58399 | val 0.67731
  Epoch 020 - train 0.53281 | val 1.05073
  Epoch 024 - train 0.47838 | val 1.04500
  Classification -> best τ=0.545 (val F1=0.3903)
  Directional -> Accuracy: 0.5238, MCC: 0.0478, F1: 0.5000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.69522 | val 0.69535
  Epoch 020 - train 0.66001 | val 0.66341
  Classification -> best τ=0.355 (val F1=0.3635)
  Directional -> Accuracy: 0.5667, MCC: 0.1667, F1: 0.6667

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.65765 | val 0.67463
  Epoch 020 - train 0.61193 | val 0.73350
  Epoch 025 - train 0.57240 | val 0.82799
  Classification -> best τ=0.520 (val F1=0.3130)
  Directional -> Accuracy: 0.7115, MCC: 0.4238, F1: 0.6341

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.64919 | val 0.88666
  Epoch 017 - train 0.61191 | val 0.90123
  Classification -> best τ=0.690 (val F1=0.2276)
  Directional -> Accuracy: 0.5072, MCC: 0.0135, F1: 0.5278

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.69012 | val 0.88688
  Epoch 016 - train 0.63109 | val 1.09050
  Classification -> best τ=0.695 (val F1=0.1842)
  Directional -> Accuracy: 0.3729, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.66610 | val 0.77606
  Epoch 016 - train 0.69192 | val 0.82168
  Classification -> best τ=0.445 (val F1=0.1842)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.66021 | val 0.73151
  Epoch 016 - train 0.63999 | val 0.69895
  Classification -> best τ=0.505 (val F1=0.2855)
  Directional -> Accuracy: 0.4462, MCC: -0.1985, F1: 0.5714

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.65618 | val 0.69629
  Epoch 017 - train 0.63333 | val 0.71743
  Classification -> best τ=0.450 (val F1=0.2694)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.70753 | val 0.73120
  Epoch 020 - train 0.65029 | val 0.73499
  Epoch 030 - train 0.62515 | val 0.66377
  Epoch 040 - train 0.54546 | val 0.68831
  Epoch 050 - train 0.43546 | val 0.65642
  Classification -> best τ=0.365 (val F1=0.3740)
  Directional -> Accuracy: 0.4468, MCC: -0.0446, F1: 0.4348

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.69103 | val 0.85513
  Epoch 016 - train 0.65503 | val 1.00710
  Classification -> best τ=0.585 (val F1=0.1400)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.69914 | val 0.70069
  Epoch 020 - train 0.64769 | val 0.71311
  Classification -> best τ=0.505 (val F1=0.3301)
  Directional -> Accuracy: 0.5345, MCC: 0.0951, F1: 0.5263

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.62752 | val 0.69248
  Epoch 020 - train 0.58095 | val 0.69660
  Epoch 030 - train 0.56971 | val 0.71665
  Classification -> best τ=0.510 (val F1=0.1507)
  Directional -> Accuracy: 0.5385, MCC: 0.0750, F1: 0.5161

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.62565 | val 0.64565
  Epoch 019 - train 0.57879 | val 0.79407
  Classification -> best τ=0.435 (val F1=0.4436)
  Directional -> Accuracy: 0.5714, MCC: 0.2385, F1: 0.4545

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.62305 | val 0.90803
  Epoch 016 - train 0.64227 | val 1.59955
  Classification -> best τ=0.515 (val F1=0.2035)
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.69421 | val 0.71793
  Epoch 016 - train 0.64816 | val 0.68574
  Classification -> best τ=0.540 (val F1=0.1936)
  Directional -> Accuracy: 0.4524, MCC: -0.1434, F1: 0.5490

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.65024 | val 0.74128
  Epoch 018 - train 0.58547 | val 1.03854
  Classification -> best τ=0.390 (val F1=0.3017)
  Directional -> Accuracy: 0.6140, MCC: 0.2000, F1: 0.6857

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.61513 | val 0.68697
  Epoch 020 - train 0.63957 | val 0.71150
  Epoch 030 - train 0.52892 | val 0.82628
  Epoch 040 - train 0.43075 | val 0.75482
  Epoch 042 - train 0.43060 | val 0.76891
  Classification -> best τ=0.695 (val F1=0.3477)
  Directional -> Accuracy: 0.5122, MCC: -0.0026, F1: 0.6000

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.66047 | val 0.94000
  Epoch 016 - train 0.68238 | val 1.16238
  Classification -> best τ=0.585 (val F1=0.2814)
  Directional -> Accuracy: 0.4884, MCC: -0.0397, F1: 0.3125

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.68219 | val 0.67765
  Epoch 020 - train 0.59934 | val 0.66770
  Epoch 027 - train 0.53631 | val 0.64335
  Classification -> best τ=0.560 (val F1=0.2282)
  Directional -> Accuracy: 0.6512, MCC: 0.2950, F1: 0.6939

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.64981 | val 0.86333
  Epoch 018 - train 0.59039 | val 1.19382
  Classification -> best τ=0.365 (val F1=0.3196)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.65460 | val 0.73549
  Epoch 019 - train 0.62984 | val 0.68029
  Classification -> best τ=0.395 (val F1=0.3313)
  Directional -> Accuracy: 0.5479, MCC: 0.1382, F1: 0.5075

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.60442 | val 0.71203
  Epoch 016 - train 0.58691 | val 0.79697
  Classification -> best τ=0.465 (val F1=0.4485)
  Directional -> Accuracy: 0.5676, MCC: 0.1737, F1: 0.6522

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.69137 | val 0.74791
  Epoch 016 - train 0.64436 | val 0.84656
  Classification -> best τ=0.435 (val F1=0.2358)
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.64852 | val 0.76665
  Epoch 016 - train 0.58757 | val 0.87755
  Classification -> best τ=0.520 (val F1=0.2005)
  Directional -> Accuracy: 0.5758, MCC: 0.0000, F1: 0.7308

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.61247 | val 0.73105
  Epoch 019 - train 0.53359 | val 0.87480
  Classification -> best τ=0.570 (val F1=0.3300)
  Directional -> Accuracy: 0.4762, MCC: -0.0107, F1: 0.0833

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.63770 | val 0.71046
  Epoch 020 - train 0.61850 | val 0.68176
  Classification -> best τ=0.380 (val F1=0.2946)
  Directional -> Accuracy: 0.4643, MCC: -0.0138, F1: 0.6250

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.63494 | val 0.77035
  Epoch 016 - train 0.55431 | val 0.72955
  Classification -> best τ=0.465 (val F1=0.2441)
  Directional -> Accuracy: 0.4783, MCC: 0.0244, F1: 0.4545

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.65094 | val 0.64809
  Epoch 020 - train 0.54366 | val 0.67380
  Epoch 029 - train 0.50995 | val 0.66435
  Classification -> best τ=0.255 (val F1=0.4646)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.62140 | val 1.01036
  Epoch 016 - train 0.54164 | val 1.19193
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.68820 | val 0.67941
  Epoch 019 - train 0.63304 | val 0.75427
  Classification -> best τ=0.475 (val F1=0.3332)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.64340 | val 0.69713
  Epoch 017 - train 0.66358 | val 0.70189
  Classification -> best τ=0.420 (val F1=0.2087)
  Directional -> Accuracy: 0.4130, MCC: -0.1723, F1: 0.2703

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.64200 | val 0.65779
  Epoch 020 - train 0.55441 | val 0.84919
  Epoch 025 - train 0.56932 | val 0.94494
  Classification -> best τ=0.505 (val F1=0.4330)
  Directional -> Accuracy: 0.6047, MCC: 0.2482, F1: 0.7385

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.61580 | val 0.77041
  Epoch 020 - train 0.65890 | val 0.81601
  Epoch 022 - train 0.56458 | val 0.83033
  Classification -> best τ=0.495 (val F1=0.4682)
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.65930 | val 1.13848
  Epoch 017 - train 0.63609 | val 1.68178
  Classification -> best τ=0.495 (val F1=0.1236)
  Directional -> Accuracy: 0.4464, MCC: -0.0812, F1: 0.1622

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.69232 | val 1.44145
  Epoch 017 - train 0.60793 | val 1.87598
  Classification -> best τ=0.555 (val F1=0.2349)
  Directional -> Accuracy: 0.5000, MCC: -0.0330, F1: 0.2222

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.66447 | val 1.09275
  Epoch 018 - train 0.64884 | val 1.11277
  Classification -> best τ=0.620 (val F1=0.1626)
  Directional -> Accuracy: 0.5741, MCC: 0.1744, F1: 0.4889

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.65442 | val 0.70807
  Epoch 020 - train 0.62668 | val 0.81314
  Epoch 024 - train 0.60885 | val 0.71989
  Classification -> best τ=0.450 (val F1=0.1001)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.64558 | val 0.76531

[I 2026-02-25 03:24:03,733] Trial 186 finished with value: 0.26728007198500153 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 64, 'learning_rate': 0.004776945507104381, 'weight_decay': 0.00017813858578554853, 'lr_patience': 7, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 0.3533485153593416, 'early_stopping_min_delta': 0.0032641420308069215}. Best is trial 179 with value: 0.3025280267941637.

  Epoch 018 - train 0.62927 | val 0.84517
  Classification -> best τ=0.480 (val F1=0.2639)
  Directional -> Accuracy: 0.5246, MCC: 0.0091, F1: 0.0645

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.26728007198500153
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.70375 | val 0.70809
  Epoch 016 - train 0.70835 | val 0.70665
  Classification -> best τ=0.530 (val F1=0.0621)
  Directional -> Accuracy: 0.4868, MCC: -0.0667, F1: 0.3390

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.70856 | val 0.70222
  Epoch 016 - train 0.70987 | val 0.70557
  Classification -> best τ=0.525 (val F1=0.1236)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.70698 | val 0.73220
  Epoch 016 - train 0.73009 | val 0.75796
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.69834 | val 0.70313
  Epoch 016 - train 0.69911 | val 0.70554
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.72289 | val 0.69101
  Epoch 016 - train 0.70957 | val 0.69312
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.74630 | val 0.70728
  Epoch 016 - train 0.72052 | val 0.72081
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4894, MCC: 0.0000, F1: 0.6571

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.70480 | val 0.71497
  Epoch 016 - train 0.70767 | val 0.72942
  Classification -> best τ=0.500 (val F1=0.1655)
  Directional -> Accuracy: 0.3913, MCC: -0.1369, F1: 0.4878

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.70874 | val 0.67802
  Epoch 016 - train 0.72081 | val 0.67844
  Classification -> best τ=0.480 (val F1=0.0185)
  Directional -> Accuracy: 0.4186, MCC: -0.0664, F1: 0.5455

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.76216 | val 0.72652
  Epoch 016 - train 0.77284 | val 0.74861
  Classification -> best τ=0.540 (val F1=0.0027)
  Directional -> Accuracy: 0.4490, MCC: -0.0306, F1: 0.5970

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.70606 | val 0.71236
  Epoch 016 - train 0.71434 | val 0.73834
  Classification -> best τ=0.510 (val F1=0.1506)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.70530 | val 0.67997
  Epoch 020 - train 0.70126 | val 0.71063
  Epoch 021 - train 0.68741 | val 0.71140
  Classification -> best τ=0.455 (val F1=0.2588)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.71105 | val 0.70740
  Epoch 016 - train 0.70982 | val 0.72623
  Classification -> best τ=0.515 (val F1=0.2105)
  Directional -> Accuracy: 0.5862, MCC: 0.3071, F1: 0.2941

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.71339 | val 0.67793
  Epoch 016 - train 0.70427 | val 0.68870
  Classification -> best τ=0.590 (val F1=0.0952)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.69153 | val 0.64204
  Epoch 020 - train 0.71054 | val 0.62882
  Epoch 030 - train 0.70530 | val 0.62754
  Classification -> best τ=0.345 (val F1=0.2692)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6053

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.73047 | val 0.68942
  Epoch 020 - train 0.71970 | val 0.69131
  Classification -> best τ=0.510 (val F1=0.1782)
  Directional -> Accuracy: 0.6538, MCC: 0.3077, F1: 0.5263

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.70768 | val 0.71548
  Epoch 016 - train 0.71010 | val 0.72443
  Classification -> best τ=0.500 (val F1=0.2089)
  Directional -> Accuracy: 0.5217, MCC: -0.0558, F1: 0.6796

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.70044 | val 0.70017
  Epoch 016 - train 0.72207 | val 0.70024
  Classification -> best τ=0.500 (val F1=0.1842)
  Directional -> Accuracy: 0.3729, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.71959 | val 0.70596
  Epoch 016 - train 0.71871 | val 0.70344
  Classification -> best τ=0.455 (val F1=0.1733)
  Directional -> Accuracy: 0.6133, MCC: 0.1424, F1: 0.7563

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.70662 | val 0.69941
  Epoch 016 - train 0.70382 | val 0.70346
  Classification -> best τ=0.530 (val F1=0.1809)
  Directional -> Accuracy: 0.5385, MCC: 0.1728, F1: 0.4643

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.70766 | val 0.69736
  Epoch 020 - train 0.71567 | val 0.69760
  Epoch 021 - train 0.71272 | val 0.69734
  Classification -> best τ=0.485 (val F1=0.1340)
  Directional -> Accuracy: 0.5600, MCC: 0.1982, F1: 0.4407

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.74431 | val 0.70663
  Epoch 016 - train 0.76066 | val 0.71418
  Classification -> best τ=0.450 (val F1=0.1457)
  Directional -> Accuracy: 0.5532, MCC: 0.0843, F1: 0.6182

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.71314 | val 0.69422
  Epoch 016 - train 0.71191 | val 0.70108
  Classification -> best τ=0.510 (val F1=0.0950)
  Directional -> Accuracy: 0.5455, MCC: 0.1325, F1: 0.2857

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.71207 | val 0.73485
  Epoch 016 - train 0.71701 | val 0.75293
  Classification -> best τ=0.475 (val F1=0.1280)
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.72503 | val 0.69411
  Epoch 016 - train 0.71497 | val 0.69939
  Classification -> best τ=0.510 (val F1=0.1359)
  Directional -> Accuracy: 0.5077, MCC: -0.0336, F1: 0.1579

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.72814 | val 0.69874
  Epoch 016 - train 0.74086 | val 0.69827
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.72530 | val 0.69462
  Epoch 016 - train 0.74237 | val 0.69738
  Classification -> best τ=0.490 (val F1=0.1585)
  Directional -> Accuracy: 0.4348, MCC: -0.3397, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.70972 | val 0.68395
  Epoch 016 - train 0.70984 | val 0.68446
  Classification -> best τ=0.535 (val F1=0.1936)
  Directional -> Accuracy: 0.4524, MCC: -0.0962, F1: 0.4889

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.71074 | val 0.68390
  Epoch 020 - train 0.70589 | val 0.67660
  Epoch 030 - train 0.69698 | val 0.67447
  Epoch 032 - train 0.69803 | val 0.67418
  Classification -> best τ=0.465 (val F1=0.2294)
  Directional -> Accuracy: 0.5263, MCC: 0.0080, F1: 0.6197

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.69071 | val 0.68935
  Epoch 016 - train 0.72456 | val 0.68976
  Classification -> best τ=0.515 (val F1=0.0216)
  Directional -> Accuracy: 0.5610, MCC: 0.1065, F1: 0.6250

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.67158 | val 0.68663
  Epoch 016 - train 0.68185 | val 0.68604
  Classification -> best τ=0.495 (val F1=0.2814)
  Directional -> Accuracy: 0.5116, MCC: 0.0318, F1: 0.5714

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.74519 | val 0.68152
  Epoch 016 - train 0.70338 | val 0.68465
  Classification -> best τ=0.535 (val F1=0.1096)
  Directional -> Accuracy: 0.4419, MCC: -0.0933, F1: 0.2500

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.70478 | val 0.69220
  Epoch 016 - train 0.69513 | val 0.69337
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.70473 | val 0.69626
  Epoch 016 - train 0.68188 | val 0.70216
  Classification -> best τ=0.490 (val F1=0.0869)
  Directional -> Accuracy: 0.5068, MCC: 0.0329, F1: 0.5000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.73879 | val 0.68589
  Epoch 020 - train 0.68476 | val 0.68285
  Epoch 030 - train 0.69883 | val 0.68534
  Classification -> best τ=0.535 (val F1=0.3882)
  Directional -> Accuracy: 0.4054, MCC: -0.1898, F1: 0.4762

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.73151 | val 0.68171
  Epoch 016 - train 0.71262 | val 0.68682
  Classification -> best τ=0.450 (val F1=0.2358)
  Directional -> Accuracy: 0.6364, MCC: 0.2754, F1: 0.6364

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.70872 | val 0.67549
  Epoch 020 - train 0.73055 | val 0.67381
  Epoch 024 - train 0.70430 | val 0.67360
  Classification -> best τ=0.435 (val F1=0.3091)
  Directional -> Accuracy: 0.5758, MCC: 0.1236, F1: 0.6410

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.73461 | val 0.71376
  Epoch 016 - train 0.75168 | val 0.73891
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5238, MCC: 0.0000, F1: 0.6875

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.73177 | val 0.68663
  Epoch 016 - train 0.71070 | val 0.68698
  Classification -> best τ=0.480 (val F1=0.1913)
  Directional -> Accuracy: 0.5357, MCC: 0.0413, F1: 0.3500

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.71754 | val 0.73757
  Epoch 016 - train 0.74690 | val 0.76326
  Classification -> best τ=0.545 (val F1=0.2185)
  Directional -> Accuracy: 0.4130, MCC: 0.1195, F1: 0.0690

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.71760 | val 0.68220
  Epoch 016 - train 0.71710 | val 0.68518
  Classification -> best τ=0.470 (val F1=0.0677)
  Directional -> Accuracy: 0.4286, MCC: -0.1316, F1: 0.3636

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.73552 | val 0.67714
  Epoch 020 - train 0.73916 | val 0.66535
  Epoch 030 - train 0.72039 | val 0.65784
  Epoch 040 - train 0.73063 | val 0.65810
  Epoch 041 - train 0.71660 | val 0.65828
  Classification -> best τ=0.485 (val F1=0.4776)
  Directional -> Accuracy: 0.5135, MCC: 0.2204, F1: 0.1818

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.72331 | val 0.69963
  Epoch 016 - train 0.71488 | val 0.70017
  Classification -> best τ=0.510 (val F1=0.1590)
  Directional -> Accuracy: 0.4933, MCC: -0.0416, F1: 0.1364

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.70604 | val 0.71407
  Epoch 016 - train 0.71030 | val 0.71399
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.6857

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.70793 | val 0.67629
  Epoch 016 - train 0.68649 | val 0.67484
  Classification -> best τ=0.465 (val F1=0.5052)
  Directional -> Accuracy: 0.4884, MCC: 0.1965, F1: 0.1538

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.69255 | val 0.73614
  Epoch 016 - train 0.74080 | val 0.75135
  Classification -> best τ=0.450 (val F1=0.2605)
  Directional -> Accuracy: 0.5918, MCC: 0.3558, F1: 0.6429

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.73645 | val 0.70965
  Epoch 020 - train 0.69817 | val 0.70079
  Epoch 030 - train 0.71610 | val 0.70315
  Classification -> best τ=0.385 (val F1=0.2958)
  Directional -> Accuracy: 0.5357, MCC: 0.0138, F1: 0.6905

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.72940 | val 0.70204
  Epoch 016 - train 0.70220 | val 0.70885
  Classification -> best τ=0.490 (val F1=0.2230)
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.71699 | val 0.68963
  Epoch 016 - train 0.69979 | val 0.69034
  Classification -> best τ=0.500 (val F1=0.2365)
  Directional -> Accuracy: 0.4444, MCC: -0.1585, F1: 0.5714

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.71323 | val 0.68213
  Epoch 019 - train 0.70987 | val 0.68729
  Classification -> best τ=0.485 (val F1=0.2095)
  Directional -> Accuracy: 0.4643, MCC: -0.1397, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.70608 | val 0.69173

[I 2026-02-25 03:25:01,516] Trial 187 finished with value: 0.16010528027085666 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 64, 'learning_rate': 4.571195394818612e-06, 'weight_decay': 0.0003287865665401637, 'lr_patience': 7, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 0.26190706554452325, 'early_stopping_min_delta': 0.004146436822073771}. Best is trial 179 with value: 0.3025280267941637.

  Epoch 016 - train 0.69113 | val 0.70639
  Classification -> best τ=0.510 (val F1=0.2258)
  Directional -> Accuracy: 0.4426, MCC: -0.1213, F1: 0.3929

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.16010528027085666
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.67949 | val 0.69738
  Epoch 017 - train 0.60584 | val 0.88074
  Classification -> best τ=0.495 (val F1=0.2510)
  Directional -> Accuracy: 0.5132, MCC: -0.1824, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.67266 | val 0.69173
  Epoch 016 - train 0.60033 | val 0.71992
  Classification -> best τ=0.455 (val F1=0.2852)
  Directional -> Accuracy: 0.6000, MCC: 0.1764, F1: 0.7429

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.67164 | val 0.74017
  Epoch 020 - train 0.66635 | val 0.88194
  Epoch 021 - train 0.61243 | val 0.89153
  Classification -> best τ=0.450 (val F1=0.2559)
  Directional -> Accuracy: 0.4255, MCC: -0.1737, F1: 0.5091

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.69796 | val 0.75000
  Epoch 016 - train 0.64995 | val 0.80933
  Classification -> best τ=0.505 (val F1=0.0095)
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.67430 | val 0.65747
  Epoch 020 - train 0.58594 | val 0.69569
  Epoch 026 - train 0.54010 | val 0.79979
  Classification -> best τ=0.525 (val F1=0.3213)
  Directional -> Accuracy: 0.4902, MCC: -0.1289, F1: 0.6486

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.63806 | val 0.72248
  Epoch 016 - train 0.54754 | val 0.80477
  Classification -> best τ=0.510 (val F1=0.1715)
  Directional -> Accuracy: 0.5319, MCC: 0.0609, F1: 0.4762

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.72115 | val 0.68461
  Epoch 020 - train 0.65092 | val 0.70278
  Epoch 026 - train 0.63905 | val 0.72831
  Classification -> best τ=0.430 (val F1=0.2473)
  Directional -> Accuracy: 0.5217, MCC: 0.0819, F1: 0.5217

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.67376 | val 0.85033
  Epoch 016 - train 0.57902 | val 1.11434
  Classification -> best τ=0.525 (val F1=0.1439)
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.69471 | val 0.71480
  Epoch 018 - train 0.59308 | val 0.85388
  Classification -> best τ=0.470 (val F1=0.1024)
  Directional -> Accuracy: 0.6531, MCC: 0.3322, F1: 0.6667

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.65333 | val 0.74169
  Epoch 016 - train 0.61137 | val 0.78148
  Classification -> best τ=0.480 (val F1=0.2538)
  Directional -> Accuracy: 0.4429, MCC: -0.0402, F1: 0.5412

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.65822 | val 0.70549
  Epoch 020 - train 0.55300 | val 1.32883
  Classification -> best τ=0.485 (val F1=0.2107)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.63875 | val 0.75109
  Epoch 018 - train 0.62065 | val 0.97478
  Classification -> best τ=0.425 (val F1=0.1469)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.66832 | val 0.77700
  Epoch 017 - train 0.57949 | val 1.04900
  Classification -> best τ=0.460 (val F1=0.2235)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.68128 | val 0.64505
  Epoch 020 - train 0.59915 | val 0.67861
  Epoch 024 - train 0.63026 | val 0.79609
  Classification -> best τ=0.385 (val F1=0.3601)
  Directional -> Accuracy: 0.4833, MCC: -0.1302, F1: 0.6517

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.67283 | val 0.90068
  Epoch 016 - train 0.61573 | val 1.22241
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.69141 | val 0.83835
  Epoch 020 - train 0.59022 | val 0.87686
  Classification -> best τ=0.520 (val F1=0.3151)
  Directional -> Accuracy: 0.5942, MCC: 0.2260, F1: 0.5333

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.66609 | val 0.97809
  Epoch 017 - train 0.62801 | val 1.02849
  Classification -> best τ=0.630 (val F1=0.1774)
  Directional -> Accuracy: 0.3559, MCC: -0.1703, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.67815 | val 0.90344
  Epoch 016 - train 0.63442 | val 1.26867
  Classification -> best τ=0.540 (val F1=0.1095)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.67481 | val 1.08199
  Epoch 016 - train 0.61900 | val 1.61388
  Classification -> best τ=0.425 (val F1=0.2522)
  Directional -> Accuracy: 0.5077, MCC: 0.1597, F1: 0.3600

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.68334 | val 0.68992
  Epoch 020 - train 0.64472 | val 0.70938
  Classification -> best τ=0.505 (val F1=0.3629)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.63593 | val 0.78355
  Epoch 020 - train 0.58214 | val 1.05226
  Epoch 027 - train 0.55349 | val 1.18465
  Classification -> best τ=0.450 (val F1=0.3740)
  Directional -> Accuracy: 0.5106, MCC: 0.2404, F1: 0.3784

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.67337 | val 0.74965
  Epoch 018 - train 0.63129 | val 0.76326
  Classification -> best τ=0.515 (val F1=0.1716)
  Directional -> Accuracy: 0.5455, MCC: 0.0916, F1: 0.5714

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.67504 | val 0.74343
  Epoch 017 - train 0.64460 | val 0.89806
  Classification -> best τ=0.500 (val F1=0.2417)
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.67211 | val 0.72653
  Epoch 016 - train 0.64232 | val 0.70192
  Classification -> best τ=0.455 (val F1=0.1986)
  Directional -> Accuracy: 0.5385, MCC: 0.1027, F1: 0.6053

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.67336 | val 0.66275
  Epoch 020 - train 0.63378 | val 0.68682
  Epoch 024 - train 0.58131 | val 0.70119
  Classification -> best τ=0.470 (val F1=0.4057)
  Directional -> Accuracy: 0.5536, MCC: 0.1340, F1: 0.5283

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.69021 | val 0.70155
  Epoch 016 - train 0.64832 | val 0.70655
  Classification -> best τ=0.490 (val F1=0.2935)
  Directional -> Accuracy: 0.4130, MCC: -0.1252, F1: 0.5091

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.72419 | val 0.68972
  Epoch 016 - train 0.62606 | val 0.74906
  Classification -> best τ=0.565 (val F1=0.1936)
  Directional -> Accuracy: 0.5000, MCC: 0.0430, F1: 0.4615

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.65510 | val 0.70785
  Epoch 016 - train 0.59371 | val 0.80677
  Classification -> best τ=0.515 (val F1=0.1625)
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.73014 | val 0.66408
  Epoch 020 - train 0.70735 | val 0.64407
  Epoch 030 - train 0.54030 | val 0.79780
  Epoch 036 - train 0.51614 | val 1.61583
  Classification -> best τ=0.430 (val F1=0.5136)
  Directional -> Accuracy: 0.5610, MCC: 0.1145, F1: 0.7000

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.67478 | val 0.80440
  Epoch 016 - train 0.63108 | val 0.88441
  Classification -> best τ=0.595 (val F1=0.2814)
  Directional -> Accuracy: 0.4419, MCC: -0.1463, F1: 0.2500

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.61325 | val 0.73589
  Epoch 016 - train 0.64053 | val 0.73187
  Classification -> best τ=0.515 (val F1=0.2282)
  Directional -> Accuracy: 0.4884, MCC: 0.0124, F1: 0.3529

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.59579 | val 0.75591
  Epoch 016 - train 0.61651 | val 1.06257
  Classification -> best τ=0.460 (val F1=0.2716)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.68083 | val 0.72241
  Epoch 016 - train 0.63326 | val 0.68744
  Classification -> best τ=0.455 (val F1=0.3391)
  Directional -> Accuracy: 0.5342, MCC: 0.1140, F1: 0.4848

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.63371 | val 0.75104
  Epoch 016 - train 0.65777 | val 0.95552
  Classification -> best τ=0.500 (val F1=0.3105)
  Directional -> Accuracy: 0.5405, MCC: 0.1348, F1: 0.6531

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.68544 | val 0.74979
  Epoch 016 - train 0.63731 | val 0.82406
  Classification -> best τ=0.555 (val F1=0.0459)
  Directional -> Accuracy: 0.5455, MCC: 0.1668, F1: 0.6552

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.66896 | val 0.89440
  Epoch 016 - train 0.61144 | val 0.95886
  Classification -> best τ=0.475 (val F1=0.3855)
  Directional -> Accuracy: 0.6061, MCC: 0.1734, F1: 0.6829

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.60081 | val 0.69849
  Epoch 020 - train 0.59381 | val 0.76193
  Epoch 023 - train 0.51957 | val 0.81673
  Classification -> best τ=0.580 (val F1=0.3300)
  Directional -> Accuracy: 0.5714, MCC: 0.2197, F1: 0.4000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.62630 | val 0.79481
  Epoch 020 - train 0.57347 | val 0.70380
  Epoch 023 - train 0.58479 | val 0.72789
  Classification -> best τ=0.425 (val F1=0.3993)
  Directional -> Accuracy: 0.4643, MCC: -0.0138, F1: 0.6250

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.60899 | val 0.78806
  Epoch 016 - train 0.55045 | val 0.77401
  Classification -> best τ=0.580 (val F1=0.2185)
  Directional -> Accuracy: 0.3913, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.71663 | val 0.66349
  Epoch 020 - train 0.58364 | val 0.63569
  Epoch 030 - train 0.58327 | val 0.75687
  Epoch 033 - train 0.56461 | val 0.67461
  Classification -> best τ=0.335 (val F1=0.3682)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.66165 | val 0.79924
  Epoch 016 - train 0.71312 | val 0.76732
  Classification -> best τ=0.490 (val F1=0.0585)
  Directional -> Accuracy: 0.4865, MCC: -0.0595, F1: 0.5778

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.64831 | val 0.79476
  Epoch 018 - train 0.60042 | val 1.07286
  Classification -> best τ=0.385 (val F1=0.3815)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.70285 | val 0.67376
  Epoch 020 - train 0.61534 | val 0.73443
  Epoch 030 - train 0.54518 | val 0.71015
  Classification -> best τ=0.480 (val F1=0.3952)
  Directional -> Accuracy: 0.5870, MCC: 0.1723, F1: 0.6667

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.63327 | val 0.75547
  Epoch 016 - train 0.63512 | val 0.74469
  Classification -> best τ=0.520 (val F1=0.2282)
  Directional -> Accuracy: 0.5814, MCC: 0.1348, F1: 0.6538

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.64072 | val 0.64546
  Epoch 020 - train 0.63500 | val 0.64849
  Epoch 030 - train 0.54260 | val 0.62145
  Epoch 040 - train 0.47460 | val 0.68943
  Epoch 044 - train 0.46179 | val 0.68070
  Classification -> best τ=0.480 (val F1=0.6080)
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.66071 | val 1.11814
  Epoch 017 - train 0.66709 | val 1.11703
  Classification -> best τ=0.555 (val F1=0.1085)
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.67417 | val 1.00233
  Epoch 020 - train 0.60012 | val 1.09777
  Epoch 021 - train 0.58668 | val 1.10664
  Classification -> best τ=0.595 (val F1=0.3510)
  Directional -> Accuracy: 0.6071, MCC: 0.3245, F1: 0.3125

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.66975 | val 1.08397
  Epoch 018 - train 0.63951 | val 1.13040
  Classification -> best τ=0.425 (val F1=0.2665)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.68330 | val 0.75464
  Epoch 016 - train 0.58175 | val 0.84463
  Classification -> best τ=0.535 (val F1=0.1345)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.67609 | val 0.73806
  Epoch 020 - train 0.62711 | val 0.75728
  Epoch 021 - train 0.62384 | val 0.78177

[I 2026-02-25 03:26:59,802] Trial 188 finished with value: 0.25457566339116994 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 64, 'learning_rate': 0.0023500541841305475, 'weight_decay': 0.00024373982770334226, 'lr_patience': 7, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 0.5471970620373784, 'early_stopping_min_delta': 0.00453812476569272}. Best is trial 179 with value: 0.3025280267941637.

  Classification -> best τ=0.565 (val F1=0.2639)
  Directional -> Accuracy: 0.4754, MCC: -0.0946, F1: 0.2381

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.25457566339116994
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.60838 | val 0.67653
  Epoch 020 - train 0.59295 | val 0.81463
  Epoch 024 - train 0.58135 | val 0.80548
  Classification -> best τ=0.515 (val F1=0.1833)
  Directional -> Accuracy: 0.4474, MCC: -0.0249, F1: 0.6038

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.64496 | val 0.70260
  Epoch 016 - train 0.59036 | val 0.76052
  Classification -> best τ=0.415 (val F1=0.2317)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.64302 | val 0.67792
  Epoch 020 - train 0.63016 | val 0.99256
  Epoch 022 - train 0.63556 | val 0.96338
  Classification -> best τ=0.455 (val F1=0.4078)
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.63637 | val 0.83674
  Epoch 016 - train 0.64827 | val 0.88193
  Classification -> best τ=0.495 (val F1=0.1688)
  Directional -> Accuracy: 0.4400, MCC: -0.1277, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.61806 | val 0.66577
  Epoch 020 - train 0.55906 | val 0.71766
  Epoch 027 - train 0.50599 | val 0.77629
  Classification -> best τ=0.565 (val F1=0.3484)
  Directional -> Accuracy: 0.5294, MCC: 0.0327, F1: 0.6364

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.60857 | val 0.70926
  Epoch 016 - train 0.53710 | val 0.71988
  Classification -> best τ=0.465 (val F1=0.2582)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.65730 | val 0.70340
  Epoch 016 - train 0.65289 | val 0.72748
  Classification -> best τ=0.465 (val F1=0.1835)
  Directional -> Accuracy: 0.5507, MCC: 0.2027, F1: 0.5974

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.60820 | val 0.63872
  Epoch 020 - train 0.57032 | val 0.65836
  Epoch 025 - train 0.55160 | val 0.67615
  Classification -> best τ=0.415 (val F1=0.1234)
  Directional -> Accuracy: 0.5349, MCC: -0.0024, F1: 0.3333

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.61703 | val 0.68378
  Epoch 020 - train 0.55882 | val 0.74900
  Epoch 030 - train 0.53672 | val 0.71727
  Epoch 040 - train 0.51358 | val 0.73986
  Classification -> best τ=0.615 (val F1=0.4040)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.62060 | val 0.71036
  Epoch 020 - train 0.56645 | val 0.80488
  Epoch 027 - train 0.57206 | val 0.73432
  Classification -> best τ=0.415 (val F1=0.3038)
  Directional -> Accuracy: 0.4429, MCC: -0.0702, F1: 0.4935

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.65441 | val 0.75961
  Epoch 016 - train 0.59742 | val 0.76936
  Classification -> best τ=0.485 (val F1=0.2107)
  Directional -> Accuracy: 0.6200, MCC: 0.2766, F1: 0.3448

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.63788 | val 0.75020
  Epoch 016 - train 0.59223 | val 0.99879
  Classification -> best τ=0.465 (val F1=0.1318)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.60203 | val 0.77126
  Epoch 016 - train 0.61610 | val 0.84492
  Classification -> best τ=0.480 (val F1=0.1908)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.63114 | val 0.72217
  Epoch 020 - train 0.61523 | val 0.96826
  Epoch 029 - train 0.58981 | val 0.96434
  Classification -> best τ=0.520 (val F1=0.2692)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.60010 | val 0.76215
  Epoch 016 - train 0.59417 | val 0.83068
  Classification -> best τ=0.540 (val F1=0.2334)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.62571 | val 0.68159
  Epoch 020 - train 0.60382 | val 0.82221
  Epoch 024 - train 0.59981 | val 0.92819
  Classification -> best τ=0.310 (val F1=0.2708)
  Directional -> Accuracy: 0.5507, MCC: 0.0713, F1: 0.6804

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.62774 | val 0.81903
  Epoch 016 - train 0.60748 | val 0.99615
  Classification -> best τ=0.565 (val F1=0.2276)
  Directional -> Accuracy: 0.3729, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.63839 | val 0.82636
  Epoch 016 - train 0.63460 | val 1.23843
  Classification -> best τ=0.480 (val F1=0.1923)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.66906 | val 0.90201
  Epoch 017 - train 0.63768 | val 1.32526
  Classification -> best τ=0.425 (val F1=0.2843)
  Directional -> Accuracy: 0.5077, MCC: 0.1597, F1: 0.3600

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.63094 | val 0.69328
  Epoch 020 - train 0.60146 | val 0.82519
  Epoch 022 - train 0.60511 | val 0.84013
  Classification -> best τ=0.565 (val F1=0.2606)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.63196 | val 0.68941
  Epoch 020 - train 0.56188 | val 0.84567
  Epoch 025 - train 0.57352 | val 0.95881
  Classification -> best τ=0.450 (val F1=0.2807)
  Directional -> Accuracy: 0.5957, MCC: 0.1919, F1: 0.6415

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.66595 | val 0.69645
  Epoch 016 - train 0.60092 | val 0.74263
  Classification -> best τ=0.475 (val F1=0.0844)
  Directional -> Accuracy: 0.5758, MCC: 0.1562, F1: 0.6216

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.63611 | val 0.70320
  Epoch 020 - train 0.62405 | val 0.74009
  Epoch 021 - train 0.58443 | val 0.74733
  Classification -> best τ=0.550 (val F1=0.2379)
  Directional -> Accuracy: 0.5517, MCC: 0.0514, F1: 0.6486

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.66320 | val 0.73464
  Epoch 016 - train 0.62337 | val 0.73974
  Classification -> best τ=0.415 (val F1=0.1936)
  Directional -> Accuracy: 0.5846, MCC: 0.1687, F1: 0.5714

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.66473 | val 0.64938
  Epoch 020 - train 0.59198 | val 0.70319
  Epoch 025 - train 0.57010 | val 0.70938
  Classification -> best τ=0.440 (val F1=0.3730)
  Directional -> Accuracy: 0.5714, MCC: 0.1329, F1: 0.6129

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.62720 | val 0.69507
  Epoch 016 - train 0.61885 | val 0.70251
  Classification -> best τ=0.525 (val F1=0.0777)
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.63078 | val 0.70172
  Epoch 020 - train 0.58866 | val 0.67482
  Epoch 030 - train 0.60791 | val 0.69953
  Epoch 035 - train 0.59143 | val 0.68575
  Classification -> best τ=0.595 (val F1=0.2402)
  Directional -> Accuracy: 0.5238, MCC: 0.0278, F1: 0.5833

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.61663 | val 0.71246
  Epoch 016 - train 0.61064 | val 0.82951
  Classification -> best τ=0.470 (val F1=0.2648)
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.62505 | val 0.70901
  Epoch 020 - train 0.63197 | val 0.69341
  Epoch 030 - train 0.55288 | val 0.60426
  Epoch 040 - train 0.53287 | val 0.92426
  Epoch 047 - train 0.56163 | val 0.73664
  Classification -> best τ=0.345 (val F1=0.5577)
  Directional -> Accuracy: 0.5610, MCC: 0.1145, F1: 0.7000

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.66241 | val 0.72532
  Epoch 016 - train 0.62610 | val 0.74639
  Classification -> best τ=0.530 (val F1=0.2814)
  Directional -> Accuracy: 0.5116, MCC: 0.0261, F1: 0.5333

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.65073 | val 0.74820
  Epoch 018 - train 0.58094 | val 0.79894
  Classification -> best τ=0.460 (val F1=0.0943)
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.57770 | val 0.70213
  Epoch 020 - train 0.59082 | val 0.95769
  Classification -> best τ=0.615 (val F1=0.2399)
  Directional -> Accuracy: 0.5600, MCC: 0.1272, F1: 0.5600

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.64148 | val 0.67218
  Epoch 020 - train 0.58934 | val 0.75374
  Epoch 024 - train 0.59865 | val 0.88111
  Classification -> best τ=0.445 (val F1=0.2794)
  Directional -> Accuracy: 0.5616, MCC: 0.1446, F1: 0.5556

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.61782 | val 0.71864
  Epoch 016 - train 0.56086 | val 0.79891
  Classification -> best τ=0.500 (val F1=0.2667)
  Directional -> Accuracy: 0.4595, MCC: -0.0783, F1: 0.5652

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.61821 | val 0.73111
  Epoch 016 - train 0.60553 | val 0.79188
  Classification -> best τ=0.505 (val F1=0.1676)
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.62225 | val 0.73062
  Epoch 016 - train 0.62051 | val 0.81697
  Classification -> best τ=0.435 (val F1=0.3525)
  Directional -> Accuracy: 0.6364, MCC: 0.2556, F1: 0.6842

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.66396 | val 0.70386
  Epoch 016 - train 0.60278 | val 0.70302
  Classification -> best τ=0.520 (val F1=0.2819)
  Directional -> Accuracy: 0.6429, MCC: 0.2821, F1: 0.6809

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.63054 | val 0.72819
  Epoch 017 - train 0.58384 | val 0.84446
  Classification -> best τ=0.505 (val F1=0.1951)
  Directional -> Accuracy: 0.5000, MCC: 0.0413, F1: 0.5882

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.60167 | val 0.72699
  Epoch 018 - train 0.56893 | val 0.87663
  Classification -> best τ=0.575 (val F1=0.2185)
  Directional -> Accuracy: 0.3913, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.64822 | val 0.67806
  Epoch 020 - train 0.61080 | val 0.64935
  Epoch 030 - train 0.61591 | val 0.63067
  Epoch 040 - train 0.53491 | val 0.63916
  Epoch 046 - train 0.57603 | val 0.65974
  Classification -> best τ=0.300 (val F1=0.4708)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.63124 | val 0.75405
  Epoch 016 - train 0.57271 | val 0.79277
  Classification -> best τ=0.530 (val F1=0.0585)
  Directional -> Accuracy: 0.3784, MCC: -0.2303, F1: 0.3030

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.63310 | val 0.70335
  Epoch 020 - train 0.60489 | val 1.08090
  Classification -> best τ=0.455 (val F1=0.3595)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.65293 | val 0.67315
  Epoch 020 - train 0.63712 | val 0.65961
  Epoch 030 - train 0.59652 | val 0.66941
  Epoch 032 - train 0.60638 | val 0.72014
  Classification -> best τ=0.440 (val F1=0.4141)
  Directional -> Accuracy: 0.5217, MCC: 0.0733, F1: 0.3889

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.66313 | val 0.72597
  Epoch 016 - train 0.58750 | val 0.72248
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.7164

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.60936 | val 0.69061
  Epoch 020 - train 0.56191 | val 0.63371
  Epoch 030 - train 0.56431 | val 0.57318
  Epoch 040 - train 0.54424 | val 0.53556
  Epoch 050 - train 0.47916 | val 0.52500
  Classification -> best τ=0.460 (val F1=0.6885)
  Directional -> Accuracy: 0.3673, MCC: -0.1468, F1: 0.5079

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.64221 | val 0.80496
  Epoch 018 - train 0.61865 | val 0.96804
  Classification -> best τ=0.420 (val F1=0.0896)
  Directional -> Accuracy: 0.6250, MCC: 0.2598, F1: 0.6182

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.61424 | val 0.89958
  Epoch 016 - train 0.61107 | val 1.20244
  Classification -> best τ=0.555 (val F1=0.2825)
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.65028 | val 0.90210
  Epoch 016 - train 0.63263 | val 1.09572
  Classification -> best τ=0.455 (val F1=0.3015)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.63012 | val 0.83393
  Epoch 016 - train 0.59903 | val 0.89966
  Classification -> best τ=0.510 (val F1=0.1667)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.65386 | val 0.71563

[I 2026-02-25 03:29:07,840] Trial 189 finished with value: 0.2510596124036086 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.6000000000000001, 'batch_size': 64, 'learning_rate': 0.0006641890742937366, 'weight_decay': 0.0004562412401664919, 'lr_patience': 7, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 0.29861696278037364, 'early_stopping_min_delta': 0.0038813699944735157}. Best is trial 179 with value: 0.3025280267941637.

  Epoch 016 - train 0.61126 | val 0.76328
  Classification -> best τ=0.550 (val F1=0.1498)
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2510596124036086
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.64395 | val 0.97451
  Epoch 020 - train 0.59985 | val 0.98137
  Classification -> best τ=0.565 (val F1=0.2510)
  Directional -> Accuracy: 0.5263, MCC: -0.0671, F1: 0.1000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.63858 | val 0.68607
  Epoch 018 - train 0.60611 | val 0.70632
  Classification -> best τ=0.455 (val F1=0.3397)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.69036 | val 0.69060
  Epoch 020 - train 0.64745 | val 0.77900
  Epoch 024 - train 0.61872 | val 0.88873
  Classification -> best τ=0.440 (val F1=0.4178)
  Directional -> Accuracy: 0.4894, MCC: 0.0705, F1: 0.1429

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.67530 | val 0.90268
  Epoch 016 - train 0.66575 | val 0.83746
  Classification -> best τ=0.460 (val F1=0.0558)
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.63470 | val 0.63550
  Epoch 020 - train 0.56396 | val 0.64773
  Epoch 025 - train 0.56013 | val 0.65825
  Classification -> best τ=0.590 (val F1=0.3795)
  Directional -> Accuracy: 0.4118, MCC: -0.1757, F1: 0.4231

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.65135 | val 0.70036
  Epoch 017 - train 0.60376 | val 0.71447
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4894, MCC: 0.0000, F1: 0.6571

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.72703 | val 0.74247
  Epoch 016 - train 0.64731 | val 0.79275
  Classification -> best τ=0.510 (val F1=0.1805)
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.66062 | val 0.78800
  Epoch 019 - train 0.57303 | val 0.87039
  Classification -> best τ=0.460 (val F1=0.0226)
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.64941 | val 0.68726
  Epoch 020 - train 0.57350 | val 0.71391
  Epoch 022 - train 0.61291 | val 0.77281
  Classification -> best τ=0.525 (val F1=0.3039)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.63845 | val 0.81754
  Epoch 020 - train 0.57811 | val 0.74720
  Epoch 023 - train 0.58237 | val 0.73390
  Classification -> best τ=0.555 (val F1=0.1929)
  Directional -> Accuracy: 0.5143, MCC: 0.0248, F1: 0.4688

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.68832 | val 0.71091
  Epoch 016 - train 0.63475 | val 1.46597
  Classification -> best τ=0.485 (val F1=0.1166)
  Directional -> Accuracy: 0.5800, MCC: 0.1405, F1: 0.3636

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.66065 | val 0.73331
  Epoch 016 - train 0.61638 | val 0.81785
  Classification -> best τ=0.510 (val F1=0.1703)
  Directional -> Accuracy: 0.5517, MCC: 0.1588, F1: 0.2778

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.65798 | val 0.77237
  Epoch 016 - train 0.58743 | val 1.12216
  Classification -> best τ=0.420 (val F1=0.1908)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.70553 | val 0.70013
  Epoch 020 - train 0.67127 | val 0.82053
  Epoch 022 - train 0.61519 | val 0.82614
  Classification -> best τ=0.380 (val F1=0.3477)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.63831 | val 0.73261
  Epoch 016 - train 0.62991 | val 0.83125
  Classification -> best τ=0.510 (val F1=0.2694)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.64924 | val 0.71632
  Epoch 018 - train 0.61751 | val 0.79744
  Classification -> best τ=0.505 (val F1=0.2357)
  Directional -> Accuracy: 0.5507, MCC: 0.0948, F1: 0.5867

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.62582 | val 0.92341
  Epoch 016 - train 0.63499 | val 1.24449
  Classification -> best τ=0.475 (val F1=0.1394)
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.65897 | val 0.82481
  Epoch 016 - train 0.62264 | val 1.12070
  Classification -> best τ=0.475 (val F1=0.1565)
  Directional -> Accuracy: 0.4800, MCC: 0.0765, F1: 0.3810

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.67304 | val 0.90493
  Epoch 019 - train 0.63812 | val 1.69329
  Classification -> best τ=0.405 (val F1=0.3421)
  Directional -> Accuracy: 0.4923, MCC: 0.1307, F1: 0.3265

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.64315 | val 0.71324
  Epoch 019 - train 0.62067 | val 0.76879
  Classification -> best τ=0.440 (val F1=0.2557)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.69281 | val 0.70227
  Epoch 020 - train 0.61579 | val 0.80740
  Epoch 022 - train 0.61230 | val 0.83155
  Classification -> best τ=0.480 (val F1=0.2267)
  Directional -> Accuracy: 0.6383, MCC: 0.1871, F1: 0.7733

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.70327 | val 0.72986
  Epoch 018 - train 0.62031 | val 0.75319
  Classification -> best τ=0.510 (val F1=0.1688)
  Directional -> Accuracy: 0.6061, MCC: 0.2125, F1: 0.5938

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.64710 | val 0.71874
  Epoch 019 - train 0.64827 | val 0.80453
  Classification -> best τ=0.575 (val F1=0.2379)
  Directional -> Accuracy: 0.5862, MCC: 0.1741, F1: 0.6129

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.67925 | val 0.78823
  Epoch 016 - train 0.60947 | val 0.89019
  Classification -> best τ=0.465 (val F1=0.1981)
  Directional -> Accuracy: 0.4769, MCC: 0.0000, F1: 0.6458

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.65112 | val 0.65414
  Epoch 020 - train 0.61533 | val 0.70301
  Epoch 026 - train 0.62801 | val 0.71006
  Classification -> best τ=0.515 (val F1=0.3824)
  Directional -> Accuracy: 0.5893, MCC: 0.2075, F1: 0.5660

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.67192 | val 0.69456
  Epoch 016 - train 0.64834 | val 0.70868
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.67139 | val 0.70443
  Epoch 016 - train 0.64693 | val 0.70174
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.64097 | val 0.75969
  Epoch 019 - train 0.63587 | val 1.10430
  Classification -> best τ=0.460 (val F1=0.2300)
  Directional -> Accuracy: 0.6491, MCC: 0.4222, F1: 0.5652

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.70229 | val 0.67672
  Epoch 020 - train 0.69383 | val 0.81054
  Epoch 030 - train 0.61597 | val 0.81304
  Epoch 040 - train 0.58363 | val 0.59520
  Epoch 050 - train 0.52531 | val 0.67886
  Classification -> best τ=0.460 (val F1=0.4345)
  Directional -> Accuracy: 0.5366, MCC: 0.0304, F1: 0.6667

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.66358 | val 0.75010
  Epoch 016 - train 0.66315 | val 0.75818
  Classification -> best τ=0.540 (val F1=0.2814)
  Directional -> Accuracy: 0.4884, MCC: -0.0353, F1: 0.3529

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.67228 | val 0.67767
  Epoch 020 - train 0.63793 | val 0.76829
  Epoch 024 - train 0.61121 | val 1.03967
  Classification -> best τ=0.560 (val F1=0.1729)
  Directional -> Accuracy: 0.5349, MCC: 0.0786, F1: 0.5238

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.63360 | val 0.70656
  Epoch 017 - train 0.59241 | val 1.01797
  Classification -> best τ=0.575 (val F1=0.2399)
  Directional -> Accuracy: 0.5000, MCC: -0.1242, F1: 0.6575

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.64859 | val 0.66548
  Epoch 020 - train 0.58348 | val 0.85840
  Epoch 024 - train 0.59031 | val 0.79986
  Classification -> best τ=0.265 (val F1=0.3721)
  Directional -> Accuracy: 0.5616, MCC: 0.1446, F1: 0.5556

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.63956 | val 0.73494
  Epoch 016 - train 0.69559 | val 0.79410
  Classification -> best τ=0.500 (val F1=0.2588)
  Directional -> Accuracy: 0.4865, MCC: -0.0094, F1: 0.6275

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.70094 | val 0.76761
  Epoch 016 - train 0.63274 | val 0.80987
  Classification -> best τ=0.490 (val F1=0.3221)
  Directional -> Accuracy: 0.7045, MCC: 0.4095, F1: 0.6977

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.65470 | val 0.75741
  Epoch 016 - train 0.65756 | val 0.79976
  Classification -> best τ=0.460 (val F1=0.2358)
  Directional -> Accuracy: 0.4394, MCC: 0.0401, F1: 0.0976

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.71977 | val 0.71489
  Epoch 016 - train 0.59976 | val 0.75995
  Classification -> best τ=0.530 (val F1=0.2652)
  Directional -> Accuracy: 0.6190, MCC: 0.2864, F1: 0.5294

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.66631 | val 0.75585
  Epoch 017 - train 0.61400 | val 0.86016
  Classification -> best τ=0.480 (val F1=0.2450)
  Directional -> Accuracy: 0.5000, MCC: 0.0274, F1: 0.5625

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.63627 | val 0.74073
  Epoch 017 - train 0.58673 | val 0.93489
  Classification -> best τ=0.475 (val F1=0.3146)
  Directional -> Accuracy: 0.4130, MCC: -0.1244, F1: 0.4000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.66637 | val 0.69040
  Epoch 020 - train 0.64770 | val 0.66752
  Epoch 030 - train 0.63151 | val 0.69968
  Epoch 040 - train 0.57030 | val 0.64109
  Epoch 050 - train 0.54686 | val 0.73664
  Classification -> best τ=0.340 (val F1=0.5247)
  Directional -> Accuracy: 0.3673, MCC: -0.0568, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.68714 | val 0.71701
  Epoch 016 - train 0.61640 | val 0.75651
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.65996 | val 0.76635
  Epoch 017 - train 0.62865 | val 0.93417
  Classification -> best τ=0.440 (val F1=0.2655)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.66448 | val 0.68422
  Epoch 020 - train 0.62237 | val 0.69613
  Epoch 021 - train 0.58439 | val 0.69130
  Classification -> best τ=0.420 (val F1=0.3861)
  Directional -> Accuracy: 0.4783, MCC: -0.0658, F1: 0.5714

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.66100 | val 0.70675
  Epoch 020 - train 0.56929 | val 0.70550
  Epoch 030 - train 0.56492 | val 0.67920
  Epoch 040 - train 0.51676 | val 0.60159
  Epoch 050 - train 0.52436 | val 0.57645
  Classification -> best τ=0.485 (val F1=0.6250)
  Directional -> Accuracy: 0.5814, MCC: 0.1178, F1: 0.6897

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.63708 | val 0.68752
  Epoch 020 - train 0.60093 | val 0.58903
  Epoch 030 - train 0.59736 | val 0.63319
  Epoch 040 - train 0.50728 | val 0.54102
  Epoch 049 - train 0.49615 | val 0.58879
  Classification -> best τ=0.395 (val F1=0.4682)
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.69421 | val 0.85461
  Epoch 019 - train 0.62418 | val 1.05175
  Classification -> best τ=0.425 (val F1=0.2925)
  Directional -> Accuracy: 0.5357, MCC: 0.2582, F1: 0.2353

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.61880 | val 0.91756
  Epoch 016 - train 0.61139 | val 1.29218
  Classification -> best τ=0.600 (val F1=0.2667)
  Directional -> Accuracy: 0.5536, MCC: 0.2676, F1: 0.6835

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.64835 | val 1.32087
  Epoch 016 - train 0.59817 | val 1.12624
  Classification -> best τ=0.470 (val F1=0.2163)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.64850 | val 0.83050
  Epoch 016 - train 0.60330 | val 0.83619
  Classification -> best τ=0.500 (val F1=0.2222)
  Directional -> Accuracy: 0.5179, MCC: 0.0479, F1: 0.4490

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.73049 | val 0.73752

[I 2026-02-25 03:31:08,990] Trial 190 finished with value: 0.24666901912352623 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.0, 'dropout': 0.7000000000000001, 'batch_size': 64, 'learning_rate': 0.0013363759628888386, 'weight_decay': 0.0003222077816051343, 'lr_patience': 7, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 0.49627983887120797, 'early_stopping_min_delta': 0.003378308153993182}. Best is trial 179 with value: 0.3025280267941637.

  Epoch 016 - train 0.65881 | val 0.73291
  Classification -> best τ=0.465 (val F1=0.1120)
  Directional -> Accuracy: 0.4098, MCC: -0.1741, F1: 0.4545

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.24666901912352623
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.65766 | val 0.75429
  Epoch 020 - train 0.63901 | val 0.74088
  Epoch 022 - train 0.60570 | val 0.76793
  Classification -> best τ=0.615 (val F1=0.2510)
  Directional -> Accuracy: 0.5789, MCC: 0.1827, F1: 0.1111

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.64839 | val 0.68386
  Epoch 019 - train 0.60456 | val 0.68526
  Classification -> best τ=0.460 (val F1=0.1962)
  Directional -> Accuracy: 0.5556, MCC: 0.0055, F1: 0.6875

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.63607 | val 0.77322
  Epoch 019 - train 0.59755 | val 0.98859
  Classification -> best τ=0.660 (val F1=0.2861)
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.67131 | val 0.72820
  Epoch 016 - train 0.65646 | val 0.71729
  Classification -> best τ=0.505 (val F1=0.0587)
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.65485 | val 0.63366
  Epoch 020 - train 0.61242 | val 0.65277
  Epoch 025 - train 0.56581 | val 0.68757
  Classification -> best τ=0.500 (val F1=0.4087)
  Directional -> Accuracy: 0.6078, MCC: 0.2092, F1: 0.6774

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.70665 | val 0.75467
  Epoch 020 - train 0.59073 | val 0.75681
  Epoch 026 - train 0.59132 | val 0.68898
  Classification -> best τ=0.545 (val F1=0.1715)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.69179 | val 0.68466
  Epoch 020 - train 0.67592 | val 0.68986
  Epoch 023 - train 0.66796 | val 0.69374
  Classification -> best τ=0.575 (val F1=0.2591)
  Directional -> Accuracy: 0.5797, MCC: 0.0754, F1: 0.3556

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.78494 | val 0.64215
  Epoch 020 - train 0.55706 | val 0.89225
  Epoch 022 - train 0.54822 | val 0.98991
  Classification -> best τ=0.270 (val F1=0.1752)
  Directional -> Accuracy: 0.4186, MCC: -0.0364, F1: 0.5763

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.73064 | val 0.73980
  Epoch 019 - train 0.64077 | val 0.73550
  Classification -> best τ=0.420 (val F1=0.1872)
  Directional -> Accuracy: 0.6531, MCC: 0.3136, F1: 0.4516

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.66365 | val 0.72280
  Epoch 018 - train 0.61340 | val 0.70625
  Classification -> best τ=0.650 (val F1=0.2619)
  Directional -> Accuracy: 0.5571, MCC: -0.0160, F1: 0.1143

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.67596 | val 0.74582
  Epoch 017 - train 0.62144 | val 1.45956
  Classification -> best τ=0.435 (val F1=0.2151)
  Directional -> Accuracy: 0.5200, MCC: -0.0058, F1: 0.2941

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.62613 | val 0.87506
  Epoch 017 - train 0.58383 | val 1.05422
  Classification -> best τ=0.485 (val F1=0.1121)
  Directional -> Accuracy: 0.5690, MCC: 0.2000, F1: 0.6835

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.68624 | val 0.98765
  Epoch 016 - train 0.61319 | val 0.99396
  Classification -> best τ=0.560 (val F1=0.2924)
  Directional -> Accuracy: 0.5476, MCC: 0.1105, F1: 0.5581

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.69280 | val 0.71971
  Epoch 020 - train 0.65551 | val 0.70370
  Classification -> best τ=0.370 (val F1=0.3635)
  Directional -> Accuracy: 0.5333, MCC: 0.1111, F1: 0.6667

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.68929 | val 0.73466
  Epoch 018 - train 0.59909 | val 0.85295
  Classification -> best τ=0.485 (val F1=0.2160)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.62825 | val 0.71171
  Epoch 020 - train 0.63399 | val 0.85657
  Epoch 026 - train 0.61104 | val 0.80516
  Classification -> best τ=0.265 (val F1=0.2708)
  Directional -> Accuracy: 0.5797, MCC: 0.1576, F1: 0.7010

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.65443 | val 0.90479
  Epoch 019 - train 0.65208 | val 1.04582
  Classification -> best τ=0.400 (val F1=0.0046)
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.67761 | val 0.82329
  Epoch 016 - train 0.65469 | val 0.88796
  Classification -> best τ=0.525 (val F1=0.1030)
  Directional -> Accuracy: 0.4133, MCC: -0.0575, F1: 0.2414

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.63686 | val 0.97452
  Epoch 016 - train 0.62173 | val 1.39515
  Classification -> best τ=0.470 (val F1=0.3071)
  Directional -> Accuracy: 0.5077, MCC: 0.1597, F1: 0.3600

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.69149 | val 0.69946
  Epoch 020 - train 0.63942 | val 0.66283
  Epoch 028 - train 0.65685 | val 0.73028
  Classification -> best τ=0.455 (val F1=0.3219)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.67455 | val 0.66613
  Epoch 020 - train 0.60983 | val 1.10441
  Epoch 025 - train 0.56603 | val 1.91949
  Classification -> best τ=0.480 (val F1=0.3380)
  Directional -> Accuracy: 0.5745, MCC: 0.2287, F1: 0.5652

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.69108 | val 0.73611
  Epoch 020 - train 0.62697 | val 0.98559
  Epoch 021 - train 0.64779 | val 0.82253
  Classification -> best τ=0.530 (val F1=0.1878)
  Directional -> Accuracy: 0.5303, MCC: 0.0741, F1: 0.3404

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.67741 | val 0.74214
  Epoch 016 - train 0.59123 | val 0.74307
  Classification -> best τ=0.550 (val F1=0.2379)
  Directional -> Accuracy: 0.5690, MCC: 0.1345, F1: 0.6032

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.65564 | val 0.69573
  Epoch 019 - train 0.61473 | val 0.73344
  Classification -> best τ=0.500 (val F1=0.1986)
  Directional -> Accuracy: 0.5385, MCC: 0.0711, F1: 0.1667

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.64810 | val 0.64177
  Epoch 020 - train 0.60369 | val 0.76567
  Epoch 028 - train 0.57757 | val 0.82593
  Classification -> best τ=0.515 (val F1=0.4795)
  Directional -> Accuracy: 0.4643, MCC: 0.0292, F1: 0.1667

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.70461 | val 0.76130
  Epoch 019 - train 0.60458 | val 0.78176
  Classification -> best τ=0.520 (val F1=0.2035)
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.67342 | val 0.69468
  Epoch 016 - train 0.62350 | val 0.69529
  Classification -> best τ=0.510 (val F1=0.1936)
  Directional -> Accuracy: 0.5000, MCC: 0.0280, F1: 0.4878

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.69382 | val 0.69978
  Epoch 020 - train 0.63245 | val 0.94715
  Epoch 021 - train 0.60663 | val 0.89220
  Classification -> best τ=0.595 (val F1=0.1625)
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.72859 | val 0.72817
  Epoch 020 - train 0.66013 | val 0.65467
  Epoch 030 - train 0.64446 | val 1.20488
  Epoch 035 - train 0.61235 | val 0.86016
  Classification -> best τ=0.475 (val F1=0.4862)
  Directional -> Accuracy: 0.5366, MCC: 0.0166, F1: 0.6885

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.71672 | val 0.77244
  Epoch 020 - train 0.62884 | val 0.96747
  Epoch 021 - train 0.65027 | val 1.00285
  Classification -> best τ=0.650 (val F1=0.2814)
  Directional -> Accuracy: 0.5581, MCC: 0.1169, F1: 0.5581

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.71319 | val 0.71457
  Epoch 020 - train 0.62533 | val 0.62750
  Epoch 030 - train 0.59565 | val 0.71817
  Epoch 036 - train 0.55574 | val 0.69560
  Classification -> best τ=0.635 (val F1=0.2976)
  Directional -> Accuracy: 0.5581, MCC: 0.1297, F1: 0.5366

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.60172 | val 0.83113
  Epoch 016 - train 0.61896 | val 1.52504
  Classification -> best τ=0.430 (val F1=0.3833)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.66177 | val 0.67883
  Epoch 020 - train 0.62850 | val 0.64073
  Epoch 027 - train 0.62349 | val 1.11124
  Classification -> best τ=0.455 (val F1=0.3562)
  Directional -> Accuracy: 0.5342, MCC: 0.1465, F1: 0.4333

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.66957 | val 0.74430
  Epoch 016 - train 0.62268 | val 0.73422
  Classification -> best τ=0.490 (val F1=0.2316)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.72488 | val 0.74338
  Epoch 016 - train 0.64325 | val 0.80870
  Classification -> best τ=0.620 (val F1=0.3103)
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.66961 | val 0.70315
  Epoch 016 - train 0.65649 | val 0.72180
  Classification -> best τ=0.415 (val F1=0.3254)
  Directional -> Accuracy: 0.6061, MCC: 0.1551, F1: 0.7347

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.59175 | val 0.79517
  Epoch 016 - train 0.61300 | val 0.83513
  Classification -> best τ=0.505 (val F1=0.1222)
  Directional -> Accuracy: 0.6667, MCC: 0.3441, F1: 0.6500

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.67419 | val 0.82683
  Epoch 019 - train 0.62207 | val 0.71431
  Classification -> best τ=0.425 (val F1=0.2946)
  Directional -> Accuracy: 0.5536, MCC: 0.1726, F1: 0.6377

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.62757 | val 0.83948
  Epoch 018 - train 0.62455 | val 0.71572
  Classification -> best τ=0.425 (val F1=0.3367)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.68802 | val 0.71237
  Epoch 020 - train 0.65396 | val 0.66146
  Epoch 030 - train 0.63000 | val 0.63275
  Epoch 040 - train 0.56216 | val 0.62363
  Epoch 050 - train 0.56918 | val 0.60194
  Classification -> best τ=0.390 (val F1=0.6670)
  Directional -> Accuracy: 0.3469, MCC: -0.1894, F1: 0.5152

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.73370 | val 0.79590
  Epoch 016 - train 0.62784 | val 0.95594
  Classification -> best τ=0.470 (val F1=0.1282)
  Directional -> Accuracy: 0.4595, MCC: -0.1684, F1: 0.6000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.65730 | val 0.67203
  Epoch 020 - train 0.62994 | val 1.02293
  Epoch 021 - train 0.62923 | val 0.97783
  Classification -> best τ=0.430 (val F1=0.4470)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.63751 | val 0.68819
  Epoch 017 - train 0.62754 | val 0.71810
  Classification -> best τ=0.435 (val F1=0.3871)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.0000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.74817 | val 0.76662
  Epoch 017 - train 0.68586 | val 0.84943
  Classification -> best τ=0.540 (val F1=0.4625)
  Directional -> Accuracy: 0.6512, MCC: 0.3072, F1: 0.6667

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.74668 | val 0.58353
  Epoch 020 - train 0.62159 | val 0.69438
  Epoch 025 - train 0.62917 | val 0.68779
  Classification -> best τ=0.585 (val F1=0.6290)
  Directional -> Accuracy: 0.3673, MCC: -0.1814, F1: 0.5373

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.65044 | val 1.03027
  Epoch 017 - train 0.65102 | val 2.19635
  Classification -> best τ=0.620 (val F1=0.1914)
  Directional -> Accuracy: 0.4821, MCC: 0.1255, F1: 0.0645

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.65160 | val 0.81842
  Epoch 018 - train 0.61747 | val 1.14832
  Classification -> best τ=0.485 (val F1=0.3444)
  Directional -> Accuracy: 0.5357, MCC: 0.1073, F1: 0.6286

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.68558 | val 1.12971
  Epoch 017 - train 0.63677 | val 1.57059
  Classification -> best τ=0.515 (val F1=0.1626)
  Directional -> Accuracy: 0.5926, MCC: 0.1823, F1: 0.6207

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.67568 | val 0.79381
  Epoch 017 - train 0.63830 | val 0.81079
  Classification -> best τ=0.490 (val F1=0.2887)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.65538 | val 0.69760
  Epoch 020 - train 0.61163 | val 0.80721

[I 2026-02-25 03:33:15,925] Trial 191 finished with value: 0.27863773188432306 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 64, 'learning_rate': 0.005948773037678975, 'weight_decay': 0.0005964442921250361, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 0.5881459538582532, 'early_stopping_min_delta': 0.0035403446698900236}. Best is trial 179 with value: 0.3025280267941637.

  Epoch 023 - train 0.63679 | val 0.74852
  Classification -> best τ=0.445 (val F1=0.3349)
  Directional -> Accuracy: 0.5246, MCC: 0.1368, F1: 0.6506

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.27863773188432306
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.65908 | val 0.65622
  Epoch 020 - train 0.62067 | val 0.82121
  Epoch 024 - train 0.58707 | val 0.87685
  Classification -> best τ=0.585 (val F1=0.2510)
  Directional -> Accuracy: 0.5395, MCC: -0.0120, F1: 0.1463

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.62123 | val 0.70599
  Epoch 020 - train 0.61001 | val 0.70575
  Epoch 022 - train 0.59320 | val 0.71578
  Classification -> best τ=0.445 (val F1=0.2385)
  Directional -> Accuracy: 0.6222, MCC: 0.1909, F1: 0.7302

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.65983 | val 0.72576
  Epoch 018 - train 0.62057 | val 0.85920
  Classification -> best τ=0.455 (val F1=0.1572)
  Directional -> Accuracy: 0.4894, MCC: -0.0709, F1: 0.6129

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.66685 | val 0.80807
  Epoch 019 - train 0.64198 | val 0.71232
  Classification -> best τ=0.455 (val F1=0.1283)
  Directional -> Accuracy: 0.5467, MCC: 0.0565, F1: 0.6458

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.65633 | val 0.64743
  Epoch 020 - train 0.59869 | val 0.70235
  Classification -> best τ=0.595 (val F1=0.4051)
  Directional -> Accuracy: 0.5294, MCC: 0.1007, F1: 0.4000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.67395 | val 0.70804
  Epoch 017 - train 0.62516 | val 0.71687
  Classification -> best τ=0.515 (val F1=0.3430)
  Directional -> Accuracy: 0.5745, MCC: 0.1726, F1: 0.3750

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.68555 | val 0.69810
  Epoch 016 - train 0.65579 | val 0.75125
  Classification -> best τ=0.495 (val F1=0.2836)
  Directional -> Accuracy: 0.5507, MCC: 0.1175, F1: 0.5231

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.69009 | val 0.61570
  Epoch 020 - train 0.56848 | val 0.69182
  Epoch 024 - train 0.52195 | val 0.99977
  Classification -> best τ=0.375 (val F1=0.2331)
  Directional -> Accuracy: 0.4651, MCC: 0.0423, F1: 0.5660

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.64304 | val 0.79756
  Epoch 018 - train 0.61946 | val 0.74936
  Classification -> best τ=0.480 (val F1=0.2855)
  Directional -> Accuracy: 0.6327, MCC: 0.2673, F1: 0.4000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.63446 | val 0.72982
  Epoch 018 - train 0.56013 | val 0.96661
  Classification -> best τ=0.595 (val F1=0.0847)
  Directional -> Accuracy: 0.6429, MCC: 0.2710, F1: 0.3590

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.65495 | val 0.75378
  Epoch 018 - train 0.62865 | val 1.11647
  Classification -> best τ=0.420 (val F1=0.2107)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.63165 | val 0.79056
  Epoch 018 - train 0.58623 | val 1.14958
  Classification -> best τ=0.435 (val F1=0.1651)
  Directional -> Accuracy: 0.4828, MCC: -0.0346, F1: 0.4643

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.66967 | val 0.77463
  Epoch 016 - train 0.61113 | val 0.89718
  Classification -> best τ=0.490 (val F1=0.1908)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.66499 | val 0.66654
  Epoch 020 - train 0.64331 | val 0.66934
  Epoch 030 - train 0.59456 | val 0.70254
  Epoch 031 - train 0.58633 | val 0.70475
  Classification -> best τ=0.280 (val F1=0.3669)
  Directional -> Accuracy: 0.5500, MCC: 0.2294, F1: 0.6897

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.66156 | val 0.75913
  Epoch 020 - train 0.61930 | val 1.00426
  Epoch 021 - train 0.57437 | val 0.91361
  Classification -> best τ=0.655 (val F1=0.2673)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.64901 | val 0.93175
  Epoch 017 - train 0.59789 | val 1.07395
  Classification -> best τ=0.545 (val F1=0.4197)
  Directional -> Accuracy: 0.5217, MCC: -0.0150, F1: 0.6598

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.70063 | val 0.76560
  Epoch 016 - train 0.66939 | val 0.95446
  Classification -> best τ=0.470 (val F1=0.0046)
  Directional -> Accuracy: 0.6441, MCC: 0.1703, F1: 0.7789

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.66809 | val 1.06885
  Epoch 019 - train 0.63738 | val 1.53383
  Classification -> best τ=0.410 (val F1=0.1535)
  Directional -> Accuracy: 0.5867, MCC: 0.1742, F1: 0.6265

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.67122 | val 0.77283
  Epoch 017 - train 0.63757 | val 1.58406
  Classification -> best τ=0.465 (val F1=0.3231)
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.66271 | val 0.68265
  Epoch 019 - train 0.64996 | val 0.78107
  Classification -> best τ=0.470 (val F1=0.2669)
  Directional -> Accuracy: 0.4667, MCC: 0.1059, F1: 0.0476

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.67887 | val 0.71965
  Epoch 020 - train 0.57974 | val 1.44447
  Classification -> best τ=0.460 (val F1=0.2267)
  Directional -> Accuracy: 0.5957, MCC: 0.0121, F1: 0.7324

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.65221 | val 0.79137
  Epoch 016 - train 0.65738 | val 0.76558
  Classification -> best τ=0.550 (val F1=0.2678)
  Directional -> Accuracy: 0.4697, MCC: -0.0620, F1: 0.4068

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.68831 | val 0.68060
  Epoch 017 - train 0.68294 | val 0.82578
  Classification -> best τ=0.540 (val F1=0.2971)
  Directional -> Accuracy: 0.6034, MCC: 0.2171, F1: 0.7416

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.68468 | val 0.77046
  Epoch 020 - train 0.63430 | val 0.99417
  Epoch 030 - train 0.58833 | val 1.21726
  Epoch 032 - train 0.60194 | val 0.89588
  Classification -> best τ=0.620 (val F1=0.1986)
  Directional -> Accuracy: 0.4615, MCC: -0.0657, F1: 0.6067

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.66512 | val 0.65097
  Epoch 020 - train 0.59940 | val 0.64472
  Epoch 029 - train 0.63605 | val 0.75985
  Classification -> best τ=0.360 (val F1=0.3730)
  Directional -> Accuracy: 0.5000, MCC: 0.0039, F1: 0.5172

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.77302 | val 0.94728
  Epoch 017 - train 0.64095 | val 0.72035
  Classification -> best τ=0.415 (val F1=0.2935)
  Directional -> Accuracy: 0.4565, MCC: 0.0541, F1: 0.6032

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.71324 | val 0.68105
  Epoch 020 - train 0.62536 | val 0.69322
  Epoch 025 - train 0.64410 | val 0.70700
  Classification -> best τ=0.640 (val F1=0.2161)
  Directional -> Accuracy: 0.4286, MCC: -0.0589, F1: 0.2000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.63110 | val 0.68616
  Epoch 016 - train 0.61684 | val 0.72711
  Classification -> best τ=0.520 (val F1=0.2319)
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.69495 | val 0.77588
  Epoch 016 - train 0.76889 | val 0.77379
  Classification -> best τ=0.515 (val F1=0.4862)
  Directional -> Accuracy: 0.5854, MCC: 0.2437, F1: 0.7213

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.61767 | val 0.76086
  Epoch 017 - train 0.69511 | val 0.92696
  Classification -> best τ=0.565 (val F1=0.2814)
  Directional -> Accuracy: 0.5581, MCC: 0.1294, F1: 0.6122

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.63815 | val 0.63645
  Epoch 020 - train 0.57450 | val 0.66273
  Epoch 030 - train 0.47004 | val 0.65113
  Epoch 040 - train 0.41743 | val 0.64933
  Epoch 043 - train 0.37175 | val 0.73594
  Classification -> best τ=0.720 (val F1=0.3201)
  Directional -> Accuracy: 0.5116, MCC: 0.0864, F1: 0.3226

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.62271 | val 0.67852
  Epoch 018 - train 0.59841 | val 0.80241
  Classification -> best τ=0.565 (val F1=0.2969)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.66084 | val 0.66917
  Epoch 020 - train 0.64234 | val 0.82831
  Epoch 029 - train 0.59330 | val 1.67894
  Classification -> best τ=0.515 (val F1=0.2654)
  Directional -> Accuracy: 0.5479, MCC: 0.1591, F1: 0.4762

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.71995 | val 0.86072
  Epoch 017 - train 0.54788 | val 0.87649
  Classification -> best τ=0.500 (val F1=0.2887)
  Directional -> Accuracy: 0.5676, MCC: 0.1429, F1: 0.6000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.69740 | val 0.73906
  Epoch 016 - train 0.63362 | val 0.91385
  Classification -> best τ=0.580 (val F1=0.2503)
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.67694 | val 0.71319
  Epoch 016 - train 0.66958 | val 0.72225
  Classification -> best τ=0.425 (val F1=0.3342)
  Directional -> Accuracy: 0.5758, MCC: 0.0000, F1: 0.7308

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.66992 | val 0.77151
  Epoch 020 - train 0.53189 | val 0.80368
  Epoch 030 - train 0.42133 | val 1.00543
  Epoch 032 - train 0.56807 | val 0.92212
  Classification -> best τ=0.610 (val F1=0.3105)
  Directional -> Accuracy: 0.5000, MCC: 0.0426, F1: 0.2759

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.66861 | val 0.67040
  Epoch 020 - train 0.61488 | val 0.78200
  Classification -> best τ=0.380 (val F1=0.3192)
  Directional -> Accuracy: 0.4821, MCC: 0.1255, F1: 0.6420

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.61012 | val 0.74986
  Epoch 018 - train 0.63577 | val 0.95614
  Classification -> best τ=0.405 (val F1=0.2474)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.69363 | val 0.67076
  Epoch 018 - train 0.65779 | val 0.68871
  Classification -> best τ=0.480 (val F1=0.3300)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.67420 | val 0.72141
  Epoch 020 - train 0.58203 | val 0.93820
  Epoch 023 - train 0.53179 | val 0.86219
  Classification -> best τ=0.605 (val F1=0.3801)
  Directional -> Accuracy: 0.5135, MCC: 0.1463, F1: 0.2500

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.65797 | val 0.70554
  Epoch 020 - train 0.63273 | val 0.79360
  Epoch 024 - train 0.57181 | val 1.13483
  Classification -> best τ=0.375 (val F1=0.3450)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.70024 | val 0.68692
  Epoch 016 - train 0.65689 | val 0.69552
  Classification -> best τ=0.425 (val F1=0.3560)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.0000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.67015 | val 0.76669
  Epoch 020 - train 0.56276 | val 0.76467
  Epoch 030 - train 0.59371 | val 1.07315
  Epoch 031 - train 0.53949 | val 0.98202
  Classification -> best τ=0.370 (val F1=0.4799)
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.7164

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.74617 | val 0.67440
  Epoch 020 - train 0.62688 | val 0.73064
  Epoch 029 - train 0.56872 | val 0.66888
  Classification -> best τ=0.525 (val F1=0.5249)
  Directional -> Accuracy: 0.3878, MCC: -0.0687, F1: 0.5312

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.66857 | val 1.18158
  Epoch 016 - train 0.63802 | val 1.30090
  Classification -> best τ=0.530 (val F1=0.2111)
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.66986 | val 0.81042
  Epoch 018 - train 0.65370 | val 1.13985
  Classification -> best τ=0.525 (val F1=0.3588)
  Directional -> Accuracy: 0.5179, MCC: 0.0766, F1: 0.6301

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.64252 | val 1.07221
  Epoch 016 - train 0.60814 | val 1.40271
  Classification -> best τ=0.405 (val F1=0.2444)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.68180 | val 0.72267
  Epoch 017 - train 0.64181 | val 0.76857
  Classification -> best τ=0.485 (val F1=0.1164)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.66101 | val 0.68116
  Epoch 020 - train 0.66934 | val 0.85534

[I 2026-02-25 03:35:23,506] Trial 192 finished with value: 0.2796899742818071 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 64, 'learning_rate': 0.0066226746953111535, 'weight_decay': 0.0001985073765668445, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 0.4326740297222885, 'early_stopping_min_delta': 0.0031213025148930746}. Best is trial 179 with value: 0.3025280267941637.

  Epoch 024 - train 0.65116 | val 0.86968
  Classification -> best τ=0.410 (val F1=0.3546)
  Directional -> Accuracy: 0.5574, MCC: 0.1049, F1: 0.3721

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2796899742818071
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.60438 | val 0.71216
  Epoch 019 - train 0.56291 | val 1.52038
  Classification -> best τ=0.575 (val F1=0.2510)
  Directional -> Accuracy: 0.6184, MCC: 0.2238, F1: 0.3830

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.60013 | val 0.69267
  Epoch 020 - train 0.50681 | val 0.80128
  Epoch 023 - train 0.46663 | val 0.87569
  Classification -> best τ=0.490 (val F1=0.1700)
  Directional -> Accuracy: 0.6000, MCC: 0.2060, F1: 0.6250

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.62731 | val 0.70497
  Epoch 019 - train 0.57303 | val 1.10087
  Classification -> best τ=0.375 (val F1=0.3251)
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.67241 | val 0.78714
  Epoch 017 - train 0.63102 | val 0.94092
  Classification -> best τ=0.430 (val F1=0.2265)
  Directional -> Accuracy: 0.5467, MCC: 0.0527, F1: 0.6531

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.56680 | val 0.68374
  Epoch 020 - train 0.59907 | val 0.81353
  Epoch 024 - train 0.50306 | val 0.75211
  Classification -> best τ=0.655 (val F1=0.3309)
  Directional -> Accuracy: 0.5294, MCC: 0.1273, F1: 0.3333

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.58073 | val 0.77700
  Epoch 016 - train 0.52685 | val 0.93553
  Classification -> best τ=0.525 (val F1=0.3430)
  Directional -> Accuracy: 0.4894, MCC: 0.0000, F1: 0.6571

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.62726 | val 0.74591
  Epoch 019 - train 0.60057 | val 1.05935
  Classification -> best τ=0.555 (val F1=0.2227)
  Directional -> Accuracy: 0.5362, MCC: -0.0500, F1: 0.2381

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.58023 | val 0.63012
  Epoch 020 - train 0.51627 | val 1.43881
  Epoch 024 - train 0.44564 | val 1.34084
  Classification -> best τ=0.305 (val F1=0.1590)
  Directional -> Accuracy: 0.5581, MCC: -0.0473, F1: 0.0952

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.61251 | val 0.71265
  Epoch 018 - train 0.50457 | val 0.98211
  Classification -> best τ=0.495 (val F1=0.2891)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.60835 | val 0.74499
  Epoch 017 - train 0.52411 | val 0.94289
  Classification -> best τ=0.500 (val F1=0.2241)
  Directional -> Accuracy: 0.4143, MCC: -0.1377, F1: 0.4533

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.63055 | val 1.02252
  Epoch 020 - train 0.50897 | val 2.75502
  Epoch 021 - train 0.49294 | val 3.53830
  Classification -> best τ=0.435 (val F1=0.2365)
  Directional -> Accuracy: 0.5400, MCC: 0.0655, F1: 0.4651

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.55256 | val 1.03021
  Epoch 018 - train 0.50445 | val 1.10184
  Classification -> best τ=0.505 (val F1=0.1651)
  Directional -> Accuracy: 0.5172, MCC: 0.1325, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.59274 | val 0.77972
  Epoch 016 - train 0.53299 | val 0.88030
  Classification -> best τ=0.480 (val F1=0.2323)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.62160 | val 0.72712
  Epoch 020 - train 0.59128 | val 0.97404
  Classification -> best τ=0.420 (val F1=0.3584)
  Directional -> Accuracy: 0.5667, MCC: 0.2222, F1: 0.6905

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.57804 | val 0.80844
  Epoch 018 - train 0.50561 | val 1.02419
  Classification -> best τ=0.490 (val F1=0.2673)
  Directional -> Accuracy: 0.5192, MCC: -0.0403, F1: 0.1379

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.64815 | val 0.76114
  Epoch 017 - train 0.60012 | val 0.77642
  Classification -> best τ=0.625 (val F1=0.2916)
  Directional -> Accuracy: 0.4928, MCC: 0.0127, F1: 0.4068

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.64152 | val 0.88649
  Epoch 017 - train 0.55231 | val 1.23446
  Classification -> best τ=0.620 (val F1=0.1291)
  Directional -> Accuracy: 0.3729, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.63202 | val 0.90240
  Epoch 018 - train 0.60140 | val 1.40601
  Classification -> best τ=0.540 (val F1=0.1661)
  Directional -> Accuracy: 0.4000, MCC: -0.1147, F1: 0.2857

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.61903 | val 1.14585
  Epoch 016 - train 0.62307 | val 1.93078
  Classification -> best τ=0.495 (val F1=0.3071)
  Directional -> Accuracy: 0.5385, MCC: 0.1561, F1: 0.4828

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.61841 | val 0.72595
  Epoch 020 - train 0.60469 | val 0.82433
  Classification -> best τ=0.495 (val F1=0.2651)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.64200 | val 0.68808
  Epoch 020 - train 0.57751 | val 1.62145
  Epoch 024 - train 0.49636 | val 1.87131
  Classification -> best τ=0.490 (val F1=0.4126)
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.64843 | val 0.96530
  Epoch 018 - train 0.59760 | val 0.75305
  Classification -> best τ=0.485 (val F1=0.2580)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.66710 | val 0.83701
  Epoch 016 - train 0.55907 | val 0.94451
  Classification -> best τ=0.550 (val F1=0.2379)
  Directional -> Accuracy: 0.5345, MCC: 0.1323, F1: 0.4706

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.65860 | val 0.75599
  Epoch 017 - train 0.59133 | val 1.05381
  Classification -> best τ=0.525 (val F1=0.1507)
  Directional -> Accuracy: 0.5231, MCC: 0.0455, F1: 0.5079

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.60383 | val 0.73443
  Epoch 020 - train 0.51330 | val 1.30182
  Epoch 023 - train 0.49123 | val 1.27596
  Classification -> best τ=0.585 (val F1=0.3656)
  Directional -> Accuracy: 0.5714, MCC: 0.2023, F1: 0.5000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.58674 | val 0.73740
  Epoch 020 - train 0.50423 | val 0.86956
  Epoch 021 - train 0.49147 | val 0.83070
  Classification -> best τ=0.465 (val F1=0.2935)
  Directional -> Accuracy: 0.5000, MCC: 0.2317, F1: 0.6349

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.60630 | val 0.71815
  Epoch 020 - train 0.61603 | val 0.65869
  Epoch 030 - train 0.52832 | val 0.67900
  Epoch 040 - train 0.43769 | val 0.90407
  Epoch 041 - train 0.42204 | val 1.04962
  Classification -> best τ=0.580 (val F1=0.2831)
  Directional -> Accuracy: 0.5000, MCC: -0.0595, F1: 0.6038

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.59350 | val 0.78876
  Epoch 016 - train 0.55791 | val 1.05048
  Classification -> best τ=0.415 (val F1=0.2581)
  Directional -> Accuracy: 0.5614, MCC: 0.2858, F1: 0.3902

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.65602 | val 0.76489
  Epoch 018 - train 0.60220 | val 1.17242
  Classification -> best τ=0.560 (val F1=0.4109)
  Directional -> Accuracy: 0.5854, MCC: 0.2437, F1: 0.7213

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.61544 | val 0.80200
  Epoch 016 - train 0.54319 | val 1.08911
  Classification -> best τ=0.545 (val F1=0.2814)
  Directional -> Accuracy: 0.5349, MCC: 0.0977, F1: 0.1667

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.64370 | val 0.63259
  Epoch 020 - train 0.51554 | val 0.73648
  Epoch 026 - train 0.48847 | val 0.84348
  Classification -> best τ=0.525 (val F1=0.2517)
  Directional -> Accuracy: 0.6512, MCC: 0.3087, F1: 0.6512

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.59664 | val 0.72519
  Epoch 019 - train 0.55651 | val 1.02605
  Classification -> best τ=0.405 (val F1=0.2976)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.62600 | val 0.70047
  Epoch 020 - train 0.57338 | val 1.36318
  Classification -> best τ=0.540 (val F1=0.3410)
  Directional -> Accuracy: 0.4932, MCC: 0.0797, F1: 0.3273

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.61323 | val 0.89827
  Epoch 020 - train 0.51566 | val 1.09843
  Epoch 022 - train 0.53263 | val 1.11561
  Classification -> best τ=0.460 (val F1=0.2390)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.61015 | val 0.81862
  Epoch 016 - train 0.50411 | val 1.04794
  Classification -> best τ=0.500 (val F1=0.3792)
  Directional -> Accuracy: 0.4773, MCC: -0.1439, F1: 0.0800

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.65743 | val 0.78208
  Epoch 018 - train 0.55851 | val 0.88548
  Classification -> best τ=0.365 (val F1=0.3603)
  Directional -> Accuracy: 0.5909, MCC: 0.1587, F1: 0.6494

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.61238 | val 0.76435
  Epoch 016 - train 0.49226 | val 0.77926
  Classification -> best τ=0.560 (val F1=0.2652)
  Directional -> Accuracy: 0.5476, MCC: 0.1706, F1: 0.3448

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.63752 | val 0.67160
  Epoch 016 - train 0.58139 | val 0.82754
  Classification -> best τ=0.420 (val F1=0.3567)
  Directional -> Accuracy: 0.5000, MCC: 0.0413, F1: 0.5882

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.56733 | val 0.76446
  Epoch 016 - train 0.49735 | val 0.81225
  Classification -> best τ=0.470 (val F1=0.4226)
  Directional -> Accuracy: 0.5217, MCC: -0.0244, F1: 0.6207

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.60052 | val 0.66720
  Epoch 020 - train 0.58202 | val 0.67440
  Epoch 021 - train 0.54111 | val 0.66900
  Classification -> best τ=0.445 (val F1=0.4708)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.58747 | val 0.69209
  Epoch 020 - train 0.43744 | val 1.33534
  Epoch 026 - train 0.42720 | val 1.41387
  Classification -> best τ=0.735 (val F1=0.4776)
  Directional -> Accuracy: 0.4595, MCC: 0.0000, F1: 0.0000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.61006 | val 0.88870
  Epoch 016 - train 0.57103 | val 1.30885
  Classification -> best τ=0.485 (val F1=0.3051)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.62316 | val 0.68648
  Epoch 020 - train 0.53978 | val 0.78012
  Classification -> best τ=0.465 (val F1=0.3560)
  Directional -> Accuracy: 0.5435, MCC: 0.1633, F1: 0.3226

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.60709 | val 0.69546
  Epoch 020 - train 0.51363 | val 0.58653
  Epoch 030 - train 0.46239 | val 0.44212
  Epoch 040 - train 0.37575 | val 0.45016
  Epoch 048 - train 0.44359 | val 1.10631
  Classification -> best τ=0.700 (val F1=0.6928)
  Directional -> Accuracy: 0.5349, MCC: 0.0468, F1: 0.6000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.63552 | val 0.63196
  Epoch 020 - train 0.55407 | val 0.76346
  Epoch 024 - train 0.49584 | val 0.78596
  Classification -> best τ=0.610 (val F1=0.6590)
  Directional -> Accuracy: 0.3673, MCC: -0.1462, F1: 0.5231

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.62414 | val 0.76585
  Epoch 017 - train 0.57515 | val 1.24056
  Classification -> best τ=0.575 (val F1=0.0149)
  Directional -> Accuracy: 0.5179, MCC: 0.0998, F1: 0.3415

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.62968 | val 0.99664
  Epoch 018 - train 0.56953 | val 1.94620
  Classification -> best τ=0.580 (val F1=0.3920)
  Directional -> Accuracy: 0.5714, MCC: 0.2072, F1: 0.6667

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.64717 | val 1.62770
  Epoch 018 - train 0.58235 | val 2.55140
  Classification -> best τ=0.535 (val F1=0.2649)
  Directional -> Accuracy: 0.5926, MCC: 0.1956, F1: 0.5600

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.60464 | val 0.81869
  Epoch 017 - train 0.53957 | val 0.81073
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.64021 | val 0.80563
  Epoch 020 - train 0.55678 | val 1.03396

[I 2026-02-25 03:37:23,000] Trial 193 finished with value: 0.29443640148627 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.5, 'batch_size': 64, 'learning_rate': 0.004546880931984729, 'weight_decay': 0.00018527663128180475, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 0.44350919335832745, 'early_stopping_min_delta': 0.0031680329201045675}. Best is trial 179 with value: 0.3025280267941637.

  Epoch 024 - train 0.52310 | val 1.36435
  Classification -> best τ=0.445 (val F1=0.2639)
  Directional -> Accuracy: 0.5246, MCC: 0.0397, F1: 0.4528

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.29443640148627
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.59996 | val 0.71736
  Epoch 020 - train 0.56332 | val 0.88347
  Classification -> best τ=0.425 (val F1=0.2051)
  Directional -> Accuracy: 0.4737, MCC: 0.0267, F1: 0.5918

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.65442 | val 0.69208
  Epoch 020 - train 0.56052 | val 0.72016
  Epoch 024 - train 0.51422 | val 0.73891
  Classification -> best τ=0.460 (val F1=0.2370)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.68116 | val 0.69669
  Epoch 020 - train 0.61648 | val 1.16302
  Classification -> best τ=0.580 (val F1=0.2861)
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.66121 | val 0.76320
  Epoch 017 - train 0.64264 | val 0.78873
  Classification -> best τ=0.495 (val F1=0.0169)
  Directional -> Accuracy: 0.5067, MCC: -0.0632, F1: 0.6408

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.59365 | val 0.66939
  Epoch 020 - train 0.54191 | val 0.72861
  Epoch 024 - train 0.48176 | val 0.84327
  Classification -> best τ=0.540 (val F1=0.4598)
  Directional -> Accuracy: 0.4706, MCC: -0.0556, F1: 0.4706

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.65595 | val 0.70319
  Epoch 016 - train 0.55611 | val 0.85059
  Classification -> best τ=0.520 (val F1=0.2037)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.67904 | val 0.70758
  Epoch 017 - train 0.64215 | val 0.77468
  Classification -> best τ=0.470 (val F1=0.1374)
  Directional -> Accuracy: 0.4203, MCC: 0.0315, F1: 0.5745

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.60302 | val 0.79060
  Epoch 020 - train 0.50137 | val 1.18494
  Epoch 030 - train 0.42560 | val 1.23900
  Epoch 031 - train 0.42361 | val 1.21505
  Classification -> best τ=0.390 (val F1=0.2180)
  Directional -> Accuracy: 0.5814, MCC: 0.0789, F1: 0.3077

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.59418 | val 0.70791
  Epoch 020 - train 0.53813 | val 1.08389
  Epoch 021 - train 0.51066 | val 1.12306
  Classification -> best τ=0.490 (val F1=0.2335)
  Directional -> Accuracy: 0.7143, MCC: 0.4226, F1: 0.6818

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.60997 | val 0.70907
  Epoch 016 - train 0.55487 | val 0.89568
  Classification -> best τ=0.495 (val F1=0.0117)
  Directional -> Accuracy: 0.5714, MCC: 0.0248, F1: 0.0625

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.69137 | val 0.79412
  Epoch 017 - train 0.62147 | val 1.79096
  Classification -> best τ=0.415 (val F1=0.1361)
  Directional -> Accuracy: 0.6800, MCC: 0.3817, F1: 0.5294

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.59718 | val 0.79582
  Epoch 016 - train 0.56596 | val 0.99559
  Classification -> best τ=0.485 (val F1=0.1077)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6588

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.63769 | val 0.94847
  Epoch 016 - train 0.56417 | val 0.96069
  Classification -> best τ=0.450 (val F1=0.2392)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.65645 | val 0.61569
  Epoch 020 - train 0.57760 | val 0.91766
  Epoch 024 - train 0.54792 | val 1.37055
  Classification -> best τ=0.445 (val F1=0.3833)
  Directional -> Accuracy: 0.5667, MCC: 0.2673, F1: 0.6977

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.58606 | val 0.76208
  Epoch 018 - train 0.63150 | val 1.16859
  Classification -> best τ=0.575 (val F1=0.2160)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.62768 | val 0.72755
  Epoch 017 - train 0.58155 | val 0.90109
  Classification -> best τ=0.420 (val F1=0.2708)
  Directional -> Accuracy: 0.5507, MCC: 0.0713, F1: 0.6804

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.64320 | val 0.86654
  Epoch 016 - train 0.61954 | val 1.11771
  Classification -> best τ=0.660 (val F1=0.1774)
  Directional -> Accuracy: 0.3729, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.66271 | val 0.95210
  Epoch 016 - train 0.63877 | val 1.59839
  Classification -> best τ=0.530 (val F1=0.2395)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.65649 | val 1.21849
  Epoch 018 - train 0.62332 | val 2.02341
  Classification -> best τ=0.520 (val F1=0.2932)
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.61201 | val 0.67486
  Epoch 019 - train 0.58030 | val 0.74748
  Classification -> best τ=0.455 (val F1=0.2571)
  Directional -> Accuracy: 0.4400, MCC: -0.1277, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.67062 | val 0.72168
  Epoch 016 - train 0.57247 | val 1.17392
  Classification -> best τ=0.585 (val F1=0.0648)
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.64942 | val 0.83599
  Epoch 020 - train 0.57763 | val 0.85733
  Epoch 021 - train 0.60525 | val 0.89442
  Classification -> best τ=0.520 (val F1=0.1885)
  Directional -> Accuracy: 0.5152, MCC: 0.0325, F1: 0.5897

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.65070 | val 0.77048
  Epoch 016 - train 0.59095 | val 0.83138
  Classification -> best τ=0.575 (val F1=0.2379)
  Directional -> Accuracy: 0.5345, MCC: 0.1655, F1: 0.4255

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.64756 | val 0.73151
  Epoch 018 - train 0.57859 | val 1.66287
  Classification -> best τ=0.500 (val F1=0.1507)
  Directional -> Accuracy: 0.5385, MCC: 0.1091, F1: 0.6154

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.62867 | val 0.66760
  Epoch 020 - train 0.56733 | val 0.66151
  Epoch 030 - train 0.50096 | val 0.70953
  Classification -> best τ=0.400 (val F1=0.4330)
  Directional -> Accuracy: 0.5714, MCC: 0.2023, F1: 0.5000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.66789 | val 0.72148
  Epoch 018 - train 0.56164 | val 0.80277
  Classification -> best τ=0.530 (val F1=0.2726)
  Directional -> Accuracy: 0.6087, MCC: 0.1812, F1: 0.3077

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.65304 | val 0.71363
  Epoch 016 - train 0.59457 | val 0.72765
  Classification -> best τ=0.620 (val F1=0.1936)
  Directional -> Accuracy: 0.4524, MCC: -0.0829, F1: 0.4651

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.61339 | val 0.69658
  Epoch 018 - train 0.58117 | val 0.96711
  Classification -> best τ=0.310 (val F1=0.1988)
  Directional -> Accuracy: 0.5439, MCC: 0.2218, F1: 0.3810

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.67942 | val 0.70908
  Epoch 020 - train 0.54650 | val 0.62462
  Epoch 030 - train 0.52940 | val 1.24401
  Epoch 035 - train 0.51275 | val 1.29385
  Classification -> best τ=0.430 (val F1=0.3518)
  Directional -> Accuracy: 0.5610, MCC: 0.1701, F1: 0.7097

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.61125 | val 0.73049
  Epoch 016 - train 0.59219 | val 0.89453
  Classification -> best τ=0.545 (val F1=0.1959)
  Directional -> Accuracy: 0.5116, MCC: 0.0197, F1: 0.4615

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.67774 | val 0.69149
  Epoch 020 - train 0.58835 | val 0.66732
  Epoch 027 - train 0.47002 | val 0.87059
  Classification -> best τ=0.730 (val F1=0.2525)
  Directional -> Accuracy: 0.6279, MCC: 0.2664, F1: 0.6190

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.56796 | val 0.90674
  Epoch 019 - train 0.56484 | val 1.29295
  Classification -> best τ=0.410 (val F1=0.2645)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.62134 | val 0.72043
  Epoch 017 - train 0.57685 | val 1.76822
  Classification -> best τ=0.445 (val F1=0.2953)
  Directional -> Accuracy: 0.5342, MCC: 0.1140, F1: 0.4848

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.61980 | val 0.73861
  Epoch 016 - train 0.57999 | val 0.84627
  Classification -> best τ=0.450 (val F1=0.4951)
  Directional -> Accuracy: 0.5676, MCC: 0.1737, F1: 0.6522

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.65719 | val 0.72361
  Epoch 019 - train 0.62583 | val 0.91260
  Classification -> best τ=0.490 (val F1=0.2537)
  Directional -> Accuracy: 0.5227, MCC: 0.0666, F1: 0.5882

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.66189 | val 0.75166
  Epoch 018 - train 0.61127 | val 0.84858
  Classification -> best τ=0.410 (val F1=0.4042)
  Directional -> Accuracy: 0.5909, MCC: 0.1253, F1: 0.6897

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.59234 | val 0.73812
  Epoch 016 - train 0.53238 | val 1.06794
  Classification -> best τ=0.465 (val F1=0.2251)
  Directional -> Accuracy: 0.7381, MCC: 0.4835, F1: 0.7317

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.60687 | val 0.76266
  Epoch 020 - train 0.58914 | val 0.79780
  Classification -> best τ=0.460 (val F1=0.2868)
  Directional -> Accuracy: 0.4643, MCC: -0.0138, F1: 0.6250

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.61543 | val 0.67916
  Epoch 020 - train 0.58039 | val 1.03710
  Epoch 025 - train 0.49630 | val 1.29405
  Classification -> best τ=0.580 (val F1=0.2254)
  Directional -> Accuracy: 0.5217, MCC: 0.1431, F1: 0.4762

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.63783 | val 0.66588
  Epoch 020 - train 0.54436 | val 0.74068
  Epoch 022 - train 0.57735 | val 0.78468
  Classification -> best τ=0.425 (val F1=0.3300)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.58635 | val 0.82953
  Epoch 016 - train 0.52994 | val 1.01911
  Classification -> best τ=0.525 (val F1=0.0872)
  Directional -> Accuracy: 0.5405, MCC: 0.0792, F1: 0.5641

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.62884 | val 0.73456
  Epoch 020 - train 0.57837 | val 0.93934
  Epoch 021 - train 0.59969 | val 1.01010
  Classification -> best τ=0.395 (val F1=0.3707)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.65499 | val 0.77572
  Epoch 019 - train 0.59283 | val 0.85967
  Classification -> best τ=0.440 (val F1=0.3276)
  Directional -> Accuracy: 0.5870, MCC: 0.3343, F1: 0.3448

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.61958 | val 0.68863
  Epoch 020 - train 0.59036 | val 0.76157
  Epoch 030 - train 0.49833 | val 0.85772
  Epoch 032 - train 0.51533 | val 1.00485
  Classification -> best τ=0.415 (val F1=0.4330)
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.7164

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.64680 | val 0.58006
  Epoch 020 - train 0.62273 | val 0.64782
  Epoch 024 - train 0.56629 | val 0.61802
  Classification -> best τ=0.675 (val F1=0.6110)
  Directional -> Accuracy: 0.4082, MCC: -0.0342, F1: 0.5246

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.63595 | val 1.41294
  Epoch 017 - train 0.58716 | val 1.53047
  Classification -> best τ=0.520 (val F1=0.1085)
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.66733 | val 1.09310
  Epoch 016 - train 0.61863 | val 1.45359
  Classification -> best τ=0.575 (val F1=0.2258)
  Directional -> Accuracy: 0.5179, MCC: 0.1857, F1: 0.6667

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.64184 | val 1.11687
  Epoch 016 - train 0.58380 | val 1.34830
  Classification -> best τ=0.440 (val F1=0.3331)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.64069 | val 0.79478
  Epoch 017 - train 0.60412 | val 0.88139
  Classification -> best τ=0.495 (val F1=0.0552)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.65441 | val 0.68929
  Epoch 020 - train 0.58152 | val 1.08806
  Epoch 021 - train 0.60808 | val 0.86579

[I 2026-02-25 03:39:21,919] Trial 194 finished with value: 0.24801707759204528 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.6000000000000001, 'batch_size': 64, 'learning_rate': 0.003511576035719845, 'weight_decay': 0.0002778507206033574, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 0.4743817712988842, 'early_stopping_min_delta': 0.0037028961947189456}. Best is trial 179 with value: 0.3025280267941637.

  Classification -> best τ=0.470 (val F1=0.1991)
  Directional -> Accuracy: 0.4590, MCC: -0.2042, F1: 0.0571

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.24801707759204528
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.63832 | val 0.73658
  Epoch 017 - train 0.55098 | val 0.86182
  Classification -> best τ=0.485 (val F1=0.2627)
  Directional -> Accuracy: 0.5263, MCC: 0.0313, F1: 0.4375

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.61236 | val 0.71867
  Epoch 020 - train 0.50242 | val 0.74614
  Epoch 023 - train 0.47501 | val 0.84573
  Classification -> best τ=0.470 (val F1=0.1953)
  Directional -> Accuracy: 0.6889, MCC: 0.3547, F1: 0.7407

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.64369 | val 0.75480
  Epoch 019 - train 0.60569 | val 1.01900
  Classification -> best τ=0.390 (val F1=0.3678)
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.62951 | val 0.91853
  Epoch 017 - train 0.60988 | val 0.78368
  Classification -> best τ=0.550 (val F1=0.2470)
  Directional -> Accuracy: 0.5467, MCC: 0.1002, F1: 0.5526

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.55347 | val 0.73927
  Epoch 020 - train 0.54686 | val 0.71996
  Epoch 024 - train 0.48396 | val 0.74050
  Classification -> best τ=0.555 (val F1=0.4876)
  Directional -> Accuracy: 0.5294, MCC: 0.0833, F1: 0.4545

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.60211 | val 0.73504
  Epoch 020 - train 0.47005 | val 2.03441
  Classification -> best τ=0.570 (val F1=0.1644)
  Directional -> Accuracy: 0.5319, MCC: 0.1506, F1: 0.0833

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.68003 | val 0.71645
  Epoch 019 - train 0.61964 | val 0.78204
  Classification -> best τ=0.325 (val F1=0.1925)
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.56052 | val 0.87865
  Epoch 017 - train 0.50514 | val 0.90959
  Classification -> best τ=0.465 (val F1=0.3016)
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.61952 | val 0.75451
  Epoch 017 - train 0.50395 | val 0.97234
  Classification -> best τ=0.465 (val F1=0.2346)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.61187 | val 0.70622
  Epoch 020 - train 0.59165 | val 0.70981
  Epoch 030 - train 0.44350 | val 1.03228
  Classification -> best τ=0.450 (val F1=0.3114)
  Directional -> Accuracy: 0.4571, MCC: -0.0512, F1: 0.4865

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.61185 | val 0.88159
  Epoch 020 - train 0.53264 | val 2.55503
  Classification -> best τ=0.490 (val F1=0.2550)
  Directional -> Accuracy: 0.5800, MCC: 0.1531, F1: 0.2759

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.59393 | val 0.75590
  Epoch 020 - train 0.50004 | val 1.10465
  Epoch 021 - train 0.48287 | val 1.59030
  Classification -> best τ=0.530 (val F1=0.2453)
  Directional -> Accuracy: 0.5862, MCC: 0.2381, F1: 0.3684

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.60587 | val 0.74105
  Epoch 016 - train 0.52621 | val 1.24470
  Classification -> best τ=0.575 (val F1=0.2216)
  Directional -> Accuracy: 0.4762, MCC: -0.0026, F1: 0.5600

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.62788 | val 0.60811
  Epoch 020 - train 0.56931 | val 1.74912
  Epoch 025 - train 0.53027 | val 1.91168
  Classification -> best τ=0.435 (val F1=0.4346)
  Directional -> Accuracy: 0.5333, MCC: 0.1857, F1: 0.6818

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.56685 | val 0.76905
  Epoch 020 - train 0.55046 | val 0.97914
  Classification -> best τ=0.620 (val F1=0.2160)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.63360 | val 0.81977
  Epoch 017 - train 0.55848 | val 0.89688
  Classification -> best τ=0.600 (val F1=0.2810)
  Directional -> Accuracy: 0.5072, MCC: 0.0596, F1: 0.3704

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.61824 | val 1.12330
  Epoch 017 - train 0.58073 | val 1.76371
  Classification -> best τ=0.445 (val F1=0.0660)
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.65169 | val 0.81639
  Epoch 016 - train 0.60911 | val 1.17000
  Classification -> best τ=0.475 (val F1=0.0667)
  Directional -> Accuracy: 0.4533, MCC: -0.0556, F1: 0.4533

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.63245 | val 1.36084
  Epoch 019 - train 0.62062 | val 2.36713
  Classification -> best τ=0.500 (val F1=0.3180)
  Directional -> Accuracy: 0.4154, MCC: -0.0306, F1: 0.0500

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.63020 | val 0.79163
  Epoch 020 - train 0.57460 | val 0.79283
  Epoch 022 - train 0.55674 | val 0.71501
  Classification -> best τ=0.585 (val F1=0.2935)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.60992 | val 0.74321
  Epoch 016 - train 0.58925 | val 1.18829
  Classification -> best τ=0.595 (val F1=0.1918)
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.63082 | val 0.73532
  Epoch 016 - train 0.58819 | val 0.83044
  Classification -> best τ=0.520 (val F1=0.2453)
  Directional -> Accuracy: 0.4697, MCC: -0.0845, F1: 0.1860

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.61067 | val 0.74639
  Epoch 016 - train 0.59064 | val 0.84351
  Classification -> best τ=0.535 (val F1=0.2379)
  Directional -> Accuracy: 0.5690, MCC: 0.1089, F1: 0.6377

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.60694 | val 0.71249
  Epoch 016 - train 0.59680 | val 0.96133
  Classification -> best τ=0.510 (val F1=0.1359)
  Directional -> Accuracy: 0.5077, MCC: -0.0010, F1: 0.3846

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.60435 | val 0.69496
  Epoch 020 - train 0.56283 | val 0.74070
  Epoch 029 - train 0.44147 | val 1.00967
  Classification -> best τ=0.550 (val F1=0.3581)
  Directional -> Accuracy: 0.5357, MCC: 0.1020, F1: 0.5000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.68087 | val 0.71302
  Epoch 017 - train 0.54147 | val 0.93867
  Classification -> best τ=0.495 (val F1=0.1823)
  Directional -> Accuracy: 0.5217, MCC: -0.0553, F1: 0.2143

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.63366 | val 0.69403
  Epoch 019 - train 0.56482 | val 0.70281
  Classification -> best τ=0.555 (val F1=0.2107)
  Directional -> Accuracy: 0.5000, MCC: -0.1698, F1: 0.6557

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.58911 | val 0.67598
  Epoch 018 - train 0.55350 | val 0.75787
  Classification -> best τ=0.355 (val F1=0.2294)
  Directional -> Accuracy: 0.5965, MCC: 0.1651, F1: 0.6667

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.60436 | val 0.65679
  Epoch 020 - train 0.52320 | val 1.21854
  Epoch 025 - train 0.51332 | val 1.61221
  Classification -> best τ=0.660 (val F1=0.3477)
  Directional -> Accuracy: 0.4390, MCC: -0.1114, F1: 0.4103

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.65576 | val 0.75440
  Epoch 016 - train 0.57013 | val 0.93136
  Classification -> best τ=0.575 (val F1=0.1413)
  Directional -> Accuracy: 0.5814, MCC: 0.1993, F1: 0.3571

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.61926 | val 0.63595
  Epoch 020 - train 0.50807 | val 0.70063
  Epoch 030 - train 0.49023 | val 0.83677
  Classification -> best τ=0.735 (val F1=0.2872)
  Directional -> Accuracy: 0.4651, MCC: -0.0154, F1: 0.0800

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.53595 | val 0.87566
  Epoch 019 - train 0.50625 | val 1.62404
  Classification -> best τ=0.450 (val F1=0.3639)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.61600 | val 0.71274
  Epoch 017 - train 0.57280 | val 0.80107
  Classification -> best τ=0.390 (val F1=0.3602)
  Directional -> Accuracy: 0.5342, MCC: 0.1050, F1: 0.5000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.71595 | val 0.74070
  Epoch 016 - train 0.62278 | val 0.88831
  Classification -> best τ=0.405 (val F1=0.5590)
  Directional -> Accuracy: 0.5135, MCC: 0.0560, F1: 0.6250

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.67214 | val 0.73411
  Epoch 016 - train 0.56686 | val 0.96881
  Classification -> best τ=0.495 (val F1=0.2757)
  Directional -> Accuracy: 0.5455, MCC: 0.2585, F1: 0.6774

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.63171 | val 0.82196
  Epoch 016 - train 0.59242 | val 0.85927
  Classification -> best τ=0.550 (val F1=0.2899)
  Directional -> Accuracy: 0.4697, MCC: 0.0397, F1: 0.3137

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.55936 | val 0.78437
  Epoch 018 - train 0.50377 | val 1.22792
  Classification -> best τ=0.455 (val F1=0.2819)
  Directional -> Accuracy: 0.6905, MCC: 0.3877, F1: 0.6829

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.58407 | val 0.71584
  Epoch 016 - train 0.57307 | val 0.77120
  Classification -> best τ=0.400 (val F1=0.2203)
  Directional -> Accuracy: 0.4821, MCC: 0.1255, F1: 0.6420

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.54141 | val 0.71153
  Epoch 018 - train 0.49883 | val 1.05155
  Classification -> best τ=0.480 (val F1=0.3749)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.66776 | val 0.67831
  Epoch 020 - train 0.54813 | val 0.79322
  Epoch 022 - train 0.58954 | val 0.67166
  Classification -> best τ=0.445 (val F1=0.4141)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.62138 | val 0.77481
  Epoch 016 - train 0.52754 | val 0.84148
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.62640 | val 0.78369
  Epoch 020 - train 0.55720 | val 1.44832
  Epoch 021 - train 0.55312 | val 1.50954
  Classification -> best τ=0.410 (val F1=0.3880)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.59966 | val 0.73864
  Epoch 020 - train 0.52640 | val 0.94965
  Epoch 027 - train 0.46225 | val 1.11337
  Classification -> best τ=0.505 (val F1=0.5224)
  Directional -> Accuracy: 0.4565, MCC: -0.0996, F1: 0.0741

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.60517 | val 0.65316
  Epoch 020 - train 0.50078 | val 0.61470
  Epoch 030 - train 0.47181 | val 0.87621
  Epoch 034 - train 0.40760 | val 1.08673
  Classification -> best τ=0.540 (val F1=0.6172)
  Directional -> Accuracy: 0.6744, MCC: 0.3399, F1: 0.7083

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.62789 | val 0.76174
  Epoch 018 - train 0.51693 | val 0.67583
  Classification -> best τ=0.490 (val F1=0.5249)
  Directional -> Accuracy: 0.3673, MCC: -0.1468, F1: 0.5079

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.63308 | val 0.98092
  Epoch 019 - train 0.56387 | val 1.22970
  Classification -> best τ=0.450 (val F1=0.2932)
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.64664 | val 0.76168
  Epoch 019 - train 0.54991 | val 1.87469
  Classification -> best τ=0.555 (val F1=0.2416)
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.64813 | val 1.19939
  Epoch 018 - train 0.60196 | val 2.67035
  Classification -> best τ=0.410 (val F1=0.1657)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.60300 | val 0.77737
  Epoch 016 - train 0.54723 | val 0.85463
  Classification -> best τ=0.450 (val F1=0.1168)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.63896 | val 0.76363

[I 2026-02-25 03:41:21,887] Trial 195 finished with value: 0.28007845956425315 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.5, 'batch_size': 64, 'learning_rate': 0.00459883312549555, 'weight_decay': 0.0003716406697581705, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 0.3672025339078871, 'early_stopping_min_delta': 0.002886039013034846}. Best is trial 179 with value: 0.3025280267941637.

  Epoch 018 - train 0.56871 | val 0.86655
  Classification -> best τ=0.535 (val F1=0.2639)
  Directional -> Accuracy: 0.4754, MCC: -0.0732, F1: 0.3333

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.28007845956425315
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.66876 | val 0.67224
  Epoch 020 - train 0.66154 | val 0.65416
  Epoch 029 - train 0.63020 | val 0.66203
  Classification -> best τ=0.610 (val F1=0.2510)
  Directional -> Accuracy: 0.5395, MCC: -0.1039, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.64720 | val 0.68288
  Epoch 020 - train 0.64147 | val 0.69283
  Epoch 027 - train 0.62839 | val 0.72081
  Classification -> best τ=0.415 (val F1=0.1710)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.67171 | val 0.69323
  Epoch 016 - train 0.66166 | val 0.70150
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.66861 | val 0.69623
  Epoch 016 - train 0.64778 | val 0.70834
  Classification -> best τ=0.530 (val F1=0.1631)
  Directional -> Accuracy: 0.5067, MCC: -0.0747, F1: 0.6476

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.65416 | val 0.66591
  Epoch 020 - train 0.63941 | val 0.64130
  Epoch 030 - train 0.62441 | val 0.63831
  Epoch 038 - train 0.59931 | val 0.64071
  Classification -> best τ=0.520 (val F1=0.4457)
  Directional -> Accuracy: 0.5294, MCC: 0.0435, F1: 0.6000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.66557 | val 0.69160
  Epoch 016 - train 0.66234 | val 0.69624
  Classification -> best τ=0.520 (val F1=0.2928)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.67819 | val 0.68592
  Epoch 020 - train 0.66990 | val 0.69161
  Epoch 022 - train 0.65831 | val 0.69163
  Classification -> best τ=0.505 (val F1=0.1846)
  Directional -> Accuracy: 0.5072, MCC: 0.1130, F1: 0.5641

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.66612 | val 0.72110
  Epoch 016 - train 0.63546 | val 0.72448
  Classification -> best τ=0.515 (val F1=0.0185)
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.5902

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.66408 | val 0.68518
  Epoch 016 - train 0.67035 | val 0.69131
  Classification -> best τ=0.475 (val F1=0.1365)
  Directional -> Accuracy: 0.6327, MCC: 0.2484, F1: 0.5500

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.64947 | val 0.70900
  Epoch 016 - train 0.62364 | val 0.74473
  Classification -> best τ=0.520 (val F1=0.0748)
  Directional -> Accuracy: 0.4286, MCC: -0.0355, F1: 0.5833

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.66820 | val 0.71813
  Epoch 016 - train 0.67107 | val 0.75677
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.6301

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.66225 | val 0.70708
  Epoch 016 - train 0.65413 | val 0.77994
  Classification -> best τ=0.540 (val F1=0.1462)
  Directional -> Accuracy: 0.5517, MCC: 0.1319, F1: 0.3500

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.64216 | val 0.75986
  Epoch 016 - train 0.64366 | val 0.82621
  Classification -> best τ=0.480 (val F1=0.2277)
  Directional -> Accuracy: 0.5476, MCC: 0.0391, F1: 0.2400

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.67205 | val 0.69851
  Epoch 020 - train 0.67145 | val 0.66230
  Epoch 030 - train 0.65343 | val 0.67110
  Epoch 034 - train 0.64162 | val 0.67013
  Classification -> best τ=0.370 (val F1=0.2667)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.66881 | val 0.70450
  Epoch 016 - train 0.65205 | val 0.74156
  Classification -> best τ=0.550 (val F1=0.1901)
  Directional -> Accuracy: 0.5577, MCC: 0.3020, F1: 0.6761

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.66118 | val 0.68589
  Epoch 020 - train 0.64632 | val 0.68618
  Epoch 022 - train 0.64329 | val 0.68728
  Classification -> best τ=0.400 (val F1=0.3015)
  Directional -> Accuracy: 0.5507, MCC: 0.1304, F1: 0.7048

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.65486 | val 0.77971
  Epoch 016 - train 0.65160 | val 0.94800
  Classification -> best τ=0.500 (val F1=0.1774)
  Directional -> Accuracy: 0.3729, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.65879 | val 0.77097
  Epoch 016 - train 0.65891 | val 0.92774
  Classification -> best τ=0.525 (val F1=0.1674)
  Directional -> Accuracy: 0.6133, MCC: 0.1430, F1: 0.7184

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.65414 | val 0.69471
  Epoch 020 - train 0.64126 | val 0.75755
  Epoch 021 - train 0.64313 | val 0.76259
  Classification -> best τ=0.560 (val F1=0.2234)
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.65681 | val 0.68115
  Epoch 020 - train 0.65560 | val 0.67639
  Epoch 030 - train 0.64681 | val 0.66884
  Epoch 039 - train 0.62140 | val 0.67350
  Classification -> best τ=0.675 (val F1=0.2606)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.68327 | val 0.70311
  Epoch 016 - train 0.67105 | val 0.72065
  Classification -> best τ=0.485 (val F1=0.1342)
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.66891 | val 0.70434
  Epoch 016 - train 0.66907 | val 0.73156
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.66009 | val 0.68524
  Epoch 020 - train 0.64317 | val 0.70944
  Epoch 021 - train 0.63998 | val 0.71192
  Classification -> best τ=0.550 (val F1=0.2379)
  Directional -> Accuracy: 0.5172, MCC: -0.0504, F1: 0.6410

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.66567 | val 0.68857
  Epoch 020 - train 0.64521 | val 0.70223
  Epoch 021 - train 0.64571 | val 0.70008
  Classification -> best τ=0.565 (val F1=0.1986)
  Directional -> Accuracy: 0.5385, MCC: 0.0619, F1: 0.2857

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.66865 | val 0.65971
  Epoch 020 - train 0.62247 | val 0.63998
  Epoch 030 - train 0.62803 | val 0.63785
  Epoch 036 - train 0.61949 | val 0.63722
  Classification -> best τ=0.525 (val F1=0.3931)
  Directional -> Accuracy: 0.5357, MCC: 0.1728, F1: 0.3810

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.66740 | val 0.69116
  Epoch 016 - train 0.65442 | val 0.69151
  Classification -> best τ=0.500 (val F1=0.3487)
  Directional -> Accuracy: 0.3913, MCC: -0.2431, F1: 0.5625

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.66728 | val 0.70451
  Epoch 016 - train 0.64826 | val 0.70500
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.65318 | val 0.66664
  Epoch 020 - train 0.63744 | val 0.69478
  Epoch 022 - train 0.63652 | val 0.70037
  Classification -> best τ=0.425 (val F1=0.3077)
  Directional -> Accuracy: 0.5614, MCC: 0.3307, F1: 0.3590

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.65074 | val 0.69475
  Epoch 020 - train 0.65732 | val 0.68936
  Epoch 030 - train 0.60362 | val 0.67252
  Epoch 040 - train 0.62222 | val 0.66224
  Epoch 050 - train 0.60286 | val 0.65565
  Classification -> best τ=0.425 (val F1=0.4345)
  Directional -> Accuracy: 0.6585, MCC: 0.4010, F1: 0.7586

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.66109 | val 0.69752
  Epoch 016 - train 0.65808 | val 0.69596
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.66207 | val 0.71919
  Epoch 016 - train 0.64648 | val 0.72351
  Classification -> best τ=0.465 (val F1=0.1055)
  Directional -> Accuracy: 0.5116, MCC: -0.0323, F1: 0.6441

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.64609 | val 0.70030
  Epoch 020 - train 0.61739 | val 0.72907
  Epoch 022 - train 0.62253 | val 0.73543
  Classification -> best τ=0.530 (val F1=0.3179)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.66664 | val 0.66613
  Epoch 020 - train 0.64542 | val 0.66869
  Epoch 022 - train 0.64606 | val 0.67062
  Classification -> best τ=0.445 (val F1=0.2515)
  Directional -> Accuracy: 0.5205, MCC: 0.1344, F1: 0.3860

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.66663 | val 0.69536
  Epoch 016 - train 0.64373 | val 0.70894
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.66315 | val 0.69985
  Epoch 016 - train 0.64901 | val 0.71976
  Classification -> best τ=0.485 (val F1=0.1329)
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.65218 | val 0.68774
  Epoch 020 - train 0.65129 | val 0.70292
  Epoch 024 - train 0.63847 | val 0.70562
  Classification -> best τ=0.420 (val F1=0.3525)
  Directional -> Accuracy: 0.5909, MCC: 0.1513, F1: 0.6582

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.65528 | val 0.68561
  Epoch 020 - train 0.63772 | val 0.68014
  Epoch 028 - train 0.62224 | val 0.67996
  Classification -> best τ=0.495 (val F1=0.2986)
  Directional -> Accuracy: 0.7143, MCC: 0.4318, F1: 0.7143

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.64541 | val 0.67367
  Epoch 020 - train 0.63709 | val 0.67042
  Epoch 027 - train 0.62938 | val 0.67234
  Classification -> best τ=0.450 (val F1=0.2530)
  Directional -> Accuracy: 0.4643, MCC: -0.0493, F1: 0.5312

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.64281 | val 0.68903
  Epoch 016 - train 0.63384 | val 0.72292
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.66190 | val 0.71730
  Epoch 020 - train 0.63686 | val 0.70525
  Epoch 030 - train 0.60013 | val 0.68664
  Epoch 040 - train 0.63366 | val 0.67846
  Epoch 050 - train 0.60179 | val 0.66853
  Classification -> best τ=0.440 (val F1=0.3286)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.66248 | val 0.71780
  Epoch 016 - train 0.64392 | val 0.73679
  Classification -> best τ=0.525 (val F1=0.1816)
  Directional -> Accuracy: 0.5676, MCC: 0.1808, F1: 0.7143

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.66897 | val 0.69120
  Epoch 020 - train 0.65181 | val 0.70620
  Epoch 022 - train 0.63974 | val 0.70683
  Classification -> best τ=0.415 (val F1=0.2330)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.64962 | val 0.69287
  Epoch 016 - train 0.62453 | val 0.69791
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.6857

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.67807 | val 0.69163
  Epoch 016 - train 0.64492 | val 0.69632
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.7164

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.66215 | val 0.73131
  Epoch 016 - train 0.65333 | val 0.74571
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.68540 | val 0.75534
  Epoch 016 - train 0.67451 | val 0.90549
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.65468 | val 0.73683
  Epoch 016 - train 0.64589 | val 0.83558
  Classification -> best τ=0.530 (val F1=0.0500)
  Directional -> Accuracy: 0.5714, MCC: 0.1388, F1: 0.4783

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.66824 | val 0.75227
  Epoch 016 - train 0.65730 | val 0.88918
  Classification -> best τ=0.460 (val F1=0.1657)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.66782 | val 0.71016
  Epoch 016 - train 0.64411 | val 0.76964
  Classification -> best τ=0.475 (val F1=0.1085)
  Directional -> Accuracy: 0.4286, MCC: -0.2466, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.66342 | val 0.70705

[I 2026-02-25 03:43:32,115] Trial 196 finished with value: 0.17112515928225325 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 64, 'learning_rate': 6.353113865489585e-05, 'weight_decay': 0.0007670449715456715, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 0.5348265556363763, 'early_stopping_min_delta': 0.004382969499397763}. Best is trial 179 with value: 0.3025280267941637.

  Epoch 016 - train 0.66093 | val 0.71346
  Classification -> best τ=0.515 (val F1=0.0232)
  Directional -> Accuracy: 0.3934, MCC: -0.2260, F1: 0.5195

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.17112515928225325
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.62871 | val 0.72079
  Epoch 018 - train 0.57400 | val 1.02253
  Classification -> best τ=0.480 (val F1=0.2510)
  Directional -> Accuracy: 0.5395, MCC: 0.0459, F1: 0.4068

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.61087 | val 0.68278
  Epoch 018 - train 0.52288 | val 0.70966
  Classification -> best τ=0.455 (val F1=0.2802)
  Directional -> Accuracy: 0.6000, MCC: 0.1764, F1: 0.7429

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.62494 | val 0.76826
  Epoch 018 - train 0.54420 | val 1.18695
  Classification -> best τ=0.555 (val F1=0.2727)
  Directional -> Accuracy: 0.4894, MCC: 0.1383, F1: 0.0769

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.65612 | val 0.84308
  Epoch 017 - train 0.62061 | val 0.96417
  Classification -> best τ=0.555 (val F1=0.1712)
  Directional -> Accuracy: 0.5733, MCC: 0.1277, F1: 0.6364

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.59752 | val 0.67130
  Epoch 020 - train 0.55314 | val 0.88744
  Epoch 024 - train 0.49325 | val 0.70422
  Classification -> best τ=0.610 (val F1=0.4946)
  Directional -> Accuracy: 0.4902, MCC: -0.0048, F1: 0.4348

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.59238 | val 0.76071
  Epoch 020 - train 0.54097 | val 1.63504
  Epoch 030 - train 0.51785 | val 2.12974
  Classification -> best τ=0.375 (val F1=0.2357)
  Directional -> Accuracy: 0.5106, MCC: 0.0200, F1: 0.4889

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.66836 | val 0.73816
  Epoch 020 - train 0.63615 | val 0.82620
  Epoch 021 - train 0.59632 | val 0.81424
  Classification -> best τ=0.505 (val F1=0.2691)
  Directional -> Accuracy: 0.5797, MCC: 0.0432, F1: 0.2564

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.69552 | val 0.69256
  Epoch 020 - train 0.46884 | val 1.09803
  Epoch 021 - train 0.46978 | val 1.07747
  Classification -> best τ=0.425 (val F1=0.3295)
  Directional -> Accuracy: 0.6279, MCC: 0.2025, F1: 0.3333

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.63263 | val 0.86830
  Epoch 017 - train 0.55041 | val 1.02449
  Classification -> best τ=0.350 (val F1=0.2408)
  Directional -> Accuracy: 0.6122, MCC: 0.2076, F1: 0.3871

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.60009 | val 0.69006
  Epoch 020 - train 0.52153 | val 0.81315
  Epoch 026 - train 0.50807 | val 0.82736
  Classification -> best τ=0.550 (val F1=0.2192)
  Directional -> Accuracy: 0.4714, MCC: -0.0496, F1: 0.4478

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.57014 | val 1.26134
  Epoch 017 - train 0.52427 | val 2.28406
  Classification -> best τ=0.415 (val F1=0.2500)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.59042 | val 0.76441
  Epoch 016 - train 0.53816 | val 1.09276
  Classification -> best τ=0.345 (val F1=0.1469)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.60662 | val 0.91135
  Epoch 017 - train 0.53388 | val 1.23054
  Classification -> best τ=0.480 (val F1=0.2235)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.66365 | val 0.64034
  Epoch 020 - train 0.57694 | val 1.05794
  Epoch 026 - train 0.60673 | val 1.01844
  Classification -> best τ=0.225 (val F1=0.2667)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.64822 | val 0.76340
  Epoch 019 - train 0.50945 | val 1.09198
  Classification -> best τ=0.445 (val F1=0.2879)
  Directional -> Accuracy: 0.5577, MCC: 0.0906, F1: 0.2069

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.62023 | val 0.73366
  Epoch 020 - train 0.51461 | val 0.90745
  Epoch 021 - train 0.51277 | val 1.07528
  Classification -> best τ=0.500 (val F1=0.3483)
  Directional -> Accuracy: 0.6087, MCC: 0.2144, F1: 0.7033

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.65103 | val 1.05010
  Epoch 017 - train 0.61217 | val 1.58610
  Classification -> best τ=0.455 (val F1=0.0046)
  Directional -> Accuracy: 0.6102, MCC: 0.0171, F1: 0.7473

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.66906 | val 0.91292
  Epoch 017 - train 0.60273 | val 1.61405
  Classification -> best τ=0.485 (val F1=0.1534)
  Directional -> Accuracy: 0.4133, MCC: -0.0575, F1: 0.2414

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.63431 | val 1.36832
  Epoch 016 - train 0.59351 | val 1.98692
  Classification -> best τ=0.520 (val F1=0.2535)
  Directional -> Accuracy: 0.4615, MCC: 0.0914, F1: 0.2222

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.63524 | val 0.68044
  Epoch 020 - train 0.57466 | val 1.19439
  Epoch 021 - train 0.58082 | val 0.81265
  Classification -> best τ=0.470 (val F1=0.3093)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.59911 | val 0.77243
  Epoch 020 - train 0.52251 | val 1.50627
  Epoch 021 - train 0.53265 | val 2.07186
  Classification -> best τ=0.465 (val F1=0.3740)
  Directional -> Accuracy: 0.3830, MCC: -0.2072, F1: 0.4082

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.63430 | val 0.81696
  Epoch 016 - train 0.58592 | val 0.84156
  Classification -> best τ=0.515 (val F1=0.2453)
  Directional -> Accuracy: 0.4394, MCC: -0.1571, F1: 0.1778

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.63931 | val 0.68513
  Epoch 019 - train 0.58148 | val 0.81234
  Classification -> best τ=0.565 (val F1=0.2379)
  Directional -> Accuracy: 0.5862, MCC: 0.1841, F1: 0.6000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.64112 | val 0.70962
  Epoch 020 - train 0.53644 | val 0.79100
  Classification -> best τ=0.420 (val F1=0.2582)
  Directional -> Accuracy: 0.4769, MCC: 0.0000, F1: 0.6458

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.63501 | val 0.65119
  Epoch 020 - train 0.57018 | val 0.75155
  Epoch 026 - train 0.47664 | val 0.84871
  Classification -> best τ=0.650 (val F1=0.4124)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.62970 | val 0.72900
  Epoch 020 - train 0.50112 | val 0.77958
  Epoch 023 - train 0.47048 | val 0.87691
  Classification -> best τ=0.445 (val F1=0.2935)
  Directional -> Accuracy: 0.6522, MCC: 0.2923, F1: 0.6000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.61194 | val 0.70749
  Epoch 020 - train 0.52175 | val 0.70045
  Epoch 030 - train 0.51866 | val 0.68949
  Epoch 040 - train 0.42225 | val 0.72480
  Epoch 043 - train 0.40972 | val 0.76799
  Classification -> best τ=0.640 (val F1=0.1936)
  Directional -> Accuracy: 0.4762, MCC: 0.0000, F1: 0.4211

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.60327 | val 0.71361
  Epoch 018 - train 0.55137 | val 0.77164
  Classification -> best τ=0.390 (val F1=0.4117)
  Directional -> Accuracy: 0.5088, MCC: 0.2428, F1: 0.2222

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.60552 | val 0.67313
  Epoch 020 - train 0.53377 | val 0.99929
  Epoch 025 - train 0.50597 | val 1.83605
  Classification -> best τ=0.580 (val F1=0.4345)
  Directional -> Accuracy: 0.6098, MCC: 0.2283, F1: 0.7143

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.61409 | val 0.93666
  Epoch 016 - train 0.56240 | val 1.22365
  Classification -> best τ=0.560 (val F1=0.2814)
  Directional -> Accuracy: 0.5349, MCC: 0.0716, F1: 0.5455

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.62606 | val 0.67967
  Epoch 020 - train 0.51087 | val 0.73728
  Epoch 028 - train 0.46647 | val 0.91298
  Classification -> best τ=0.485 (val F1=0.2698)
  Directional -> Accuracy: 0.6512, MCC: 0.3015, F1: 0.6667

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.61129 | val 0.83293
  Epoch 020 - train 0.47850 | val 1.83514
  Classification -> best τ=0.275 (val F1=0.3242)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.62879 | val 0.73527
  Epoch 020 - train 0.55403 | val 1.67883
  Epoch 022 - train 0.55183 | val 1.97836
  Classification -> best τ=0.555 (val F1=0.2382)
  Directional -> Accuracy: 0.5205, MCC: 0.1684, F1: 0.3396

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.62794 | val 0.75992
  Epoch 017 - train 0.57968 | val 0.93452
  Classification -> best τ=0.440 (val F1=0.2887)
  Directional -> Accuracy: 0.5946, MCC: 0.2271, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.61867 | val 0.86642
  Epoch 019 - train 0.51566 | val 1.18324
  Classification -> best τ=0.455 (val F1=0.2757)
  Directional -> Accuracy: 0.5455, MCC: 0.1201, F1: 0.6154

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.62694 | val 0.78933
  Epoch 016 - train 0.59030 | val 0.81377
  Classification -> best τ=0.525 (val F1=0.2696)
  Directional -> Accuracy: 0.5758, MCC: 0.0000, F1: 0.7308

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.58255 | val 0.67817
  Epoch 020 - train 0.48878 | val 0.94336
  Epoch 024 - train 0.45639 | val 0.94230
  Classification -> best τ=0.560 (val F1=0.3105)
  Directional -> Accuracy: 0.5952, MCC: 0.2656, F1: 0.4516

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.59776 | val 0.71609
  Epoch 020 - train 0.54992 | val 0.73167
  Epoch 026 - train 0.51731 | val 0.70761
  Classification -> best τ=0.520 (val F1=0.3147)
  Directional -> Accuracy: 0.5179, MCC: 0.0437, F1: 0.5263

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.57968 | val 0.72979
  Epoch 016 - train 0.47820 | val 0.86163
  Classification -> best τ=0.420 (val F1=0.2800)
  Directional -> Accuracy: 0.6087, MCC: 0.1022, F1: 0.7273

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.61342 | val 0.66982
  Epoch 020 - train 0.59220 | val 0.84803
  Epoch 021 - train 0.54553 | val 0.89207
  Classification -> best τ=0.395 (val F1=0.4188)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.60497 | val 0.81621
  Epoch 016 - train 0.51203 | val 0.83044
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.62886 | val 0.71876
  Epoch 017 - train 0.59080 | val 1.06888
  Classification -> best τ=0.460 (val F1=0.4543)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.63787 | val 0.72378
  Epoch 020 - train 0.60564 | val 0.78190
  Epoch 022 - train 0.55720 | val 0.84843
  Classification -> best τ=0.530 (val F1=0.3560)
  Directional -> Accuracy: 0.5000, MCC: 0.0161, F1: 0.4103

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.60738 | val 0.66223
  Epoch 020 - train 0.48397 | val 0.68880
  Epoch 030 - train 0.44248 | val 0.67054
  Epoch 031 - train 0.46382 | val 0.74276
  Classification -> best τ=0.305 (val F1=0.5733)
  Directional -> Accuracy: 0.6047, MCC: 0.1987, F1: 0.7302

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.60110 | val 0.73015
  Epoch 017 - train 0.55904 | val 0.70106
  Classification -> best τ=0.515 (val F1=0.5131)
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.67053 | val 0.77087
  Epoch 016 - train 0.60986 | val 1.03408
  Classification -> best τ=0.525 (val F1=0.2958)
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.61364 | val 1.01301
  Epoch 018 - train 0.56768 | val 2.02161
  Classification -> best τ=0.595 (val F1=0.3170)
  Directional -> Accuracy: 0.5357, MCC: 0.1173, F1: 0.6389

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.60676 | val 1.12465
  Epoch 020 - train 0.58761 | val 1.10551
  Classification -> best τ=0.350 (val F1=0.1866)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.66501 | val 1.01160
  Epoch 019 - train 0.55905 | val 1.89381
  Classification -> best τ=0.470 (val F1=0.2539)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.61476 | val 0.71753
  Epoch 020 - train 0.55271 | val 0.81404

[I 2026-02-25 03:45:38,234] Trial 197 finished with value: 0.2889860722575469 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.5, 'batch_size': 64, 'learning_rate': 0.005512400760878426, 'weight_decay': 0.0002559897433150238, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 0.18361118595335468, 'early_stopping_min_delta': 0.0033760639444195615}. Best is trial 179 with value: 0.3025280267941637.

  Epoch 022 - train 0.55777 | val 0.82381
  Classification -> best τ=0.390 (val F1=0.3586)
  Directional -> Accuracy: 0.5902, MCC: 0.2387, F1: 0.6667

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2889860722575469
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.67739 | val 0.69132
  Epoch 019 - train 0.54521 | val 0.73152
  Classification -> best τ=0.565 (val F1=0.2510)
  Directional -> Accuracy: 0.5526, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.66544 | val 0.69278
  Epoch 017 - train 0.60621 | val 0.75246
  Classification -> best τ=0.445 (val F1=0.1823)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.64509 | val 0.85203
  Epoch 018 - train 0.59669 | val 0.98328
  Classification -> best τ=0.475 (val F1=0.3693)
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.64937 | val 0.96191
  Epoch 018 - train 0.61633 | val 1.04106
  Classification -> best τ=0.455 (val F1=0.0885)
  Directional -> Accuracy: 0.5467, MCC: 0.0527, F1: 0.6531

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.58831 | val 0.66673
  Epoch 019 - train 0.51333 | val 0.78756
  Classification -> best τ=0.500 (val F1=0.3627)
  Directional -> Accuracy: 0.5490, MCC: 0.0860, F1: 0.6102

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.61327 | val 0.71506
  Epoch 018 - train 0.55332 | val 1.28105
  Classification -> best τ=0.490 (val F1=0.4752)
  Directional -> Accuracy: 0.5745, MCC: 0.1723, F1: 0.6429

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.68184 | val 0.69450
  Epoch 017 - train 0.63805 | val 0.69857
  Classification -> best τ=0.490 (val F1=0.1988)
  Directional -> Accuracy: 0.5072, MCC: 0.0459, F1: 0.5000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.58301 | val 0.60950
  Epoch 020 - train 0.58040 | val 0.78651
  Epoch 025 - train 0.47706 | val 0.90230
  Classification -> best τ=0.340 (val F1=0.0226)
  Directional -> Accuracy: 0.5581, MCC: -0.1309, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.64284 | val 0.67614
  Epoch 020 - train 0.51783 | val 1.23353
  Epoch 025 - train 0.46851 | val 1.42433
  Classification -> best τ=0.395 (val F1=0.2452)
  Directional -> Accuracy: 0.5306, MCC: 0.1767, F1: 0.6349

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.60055 | val 0.71731
  Epoch 018 - train 0.58204 | val 0.92331
  Classification -> best τ=0.475 (val F1=0.1923)
  Directional -> Accuracy: 0.4714, MCC: -0.0172, F1: 0.5067

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.71169 | val 0.92764
  Epoch 020 - train 0.59701 | val 1.78383
  Epoch 021 - train 0.56546 | val 1.57334
  Classification -> best τ=0.580 (val F1=0.3613)
  Directional -> Accuracy: 0.6600, MCC: 0.3634, F1: 0.4516

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.62876 | val 0.83374
  Epoch 017 - train 0.56426 | val 1.67835
  Classification -> best τ=0.510 (val F1=0.1255)
  Directional -> Accuracy: 0.4310, MCC: -0.1421, F1: 0.4923

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.72044 | val 0.74406
  Epoch 019 - train 0.55733 | val 1.09430
  Classification -> best τ=0.560 (val F1=0.4160)
  Directional -> Accuracy: 0.5000, MCC: 0.0138, F1: 0.5116

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.67903 | val 0.67991
  Epoch 020 - train 0.56965 | val 1.00886
  Epoch 023 - train 0.56262 | val 1.86269
  Classification -> best τ=0.285 (val F1=0.4237)
  Directional -> Accuracy: 0.5500, MCC: 0.1400, F1: 0.6667

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.62337 | val 0.80846
  Epoch 020 - train 0.54921 | val 0.85649
  Epoch 022 - train 0.52468 | val 0.97953
  Classification -> best τ=0.555 (val F1=0.2160)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.65339 | val 0.68894
  Epoch 017 - train 0.59189 | val 0.80878
  Classification -> best τ=0.510 (val F1=0.2857)
  Directional -> Accuracy: 0.5942, MCC: 0.1841, F1: 0.6216

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.62624 | val 0.85762
  Epoch 016 - train 0.61102 | val 1.35360
  Classification -> best τ=0.680 (val F1=0.1842)
  Directional -> Accuracy: 0.3729, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.65975 | val 0.97278
  Epoch 016 - train 0.61386 | val 1.31083
  Classification -> best τ=0.450 (val F1=0.1499)
  Directional -> Accuracy: 0.5067, MCC: 0.0934, F1: 0.4638

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.66537 | val 1.00578
  Epoch 017 - train 0.62300 | val 1.49520
  Classification -> best τ=0.500 (val F1=0.2919)
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.65883 | val 0.71495
  Epoch 017 - train 0.59855 | val 0.88371
  Classification -> best τ=0.580 (val F1=0.1861)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.61726 | val 0.69472
  Epoch 016 - train 0.58237 | val 0.83379
  Classification -> best τ=0.560 (val F1=0.1918)
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.62793 | val 0.70329
  Epoch 020 - train 0.58540 | val 0.79800
  Epoch 026 - train 0.52663 | val 0.84879
  Classification -> best τ=0.345 (val F1=0.2976)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.65054 | val 0.77771
  Epoch 017 - train 0.60586 | val 0.84270
  Classification -> best τ=0.555 (val F1=0.2379)
  Directional -> Accuracy: 0.5345, MCC: 0.0951, F1: 0.5263

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.63396 | val 0.70745
  Epoch 019 - train 0.56476 | val 1.05556
  Classification -> best τ=0.430 (val F1=0.1491)
  Directional -> Accuracy: 0.4769, MCC: 0.0000, F1: 0.6458

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.62563 | val 0.64357
  Epoch 020 - train 0.52668 | val 0.71489
  Epoch 025 - train 0.49244 | val 0.77244
  Classification -> best τ=0.540 (val F1=0.3656)
  Directional -> Accuracy: 0.4821, MCC: 0.1728, F1: 0.1212

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.64921 | val 0.87126
  Epoch 016 - train 0.55208 | val 1.05791
  Classification -> best τ=0.450 (val F1=0.2935)
  Directional -> Accuracy: 0.5217, MCC: 0.0040, F1: 0.3889

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.64777 | val 0.68648
  Epoch 016 - train 0.58552 | val 0.72792
  Classification -> best τ=0.545 (val F1=0.1964)
  Directional -> Accuracy: 0.4762, MCC: -0.1750, F1: 0.6207

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.61027 | val 0.75980
  Epoch 016 - train 0.58079 | val 0.93174
  Classification -> best τ=0.455 (val F1=0.2575)
  Directional -> Accuracy: 0.5789, MCC: 0.1378, F1: 0.6364

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.75182 | val 0.69505
  Epoch 020 - train 0.56598 | val 0.67754
  Epoch 030 - train 0.56692 | val 1.30918
  Epoch 031 - train 0.47887 | val 1.81754
  Classification -> best τ=0.515 (val F1=0.4139)
  Directional -> Accuracy: 0.5122, MCC: -0.0474, F1: 0.6552

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.66586 | val 0.73695
  Epoch 020 - train 0.53697 | val 1.51941
  Classification -> best τ=0.635 (val F1=0.2814)
  Directional -> Accuracy: 0.5581, MCC: 0.1169, F1: 0.5581

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.63810 | val 0.64175
  Epoch 020 - train 0.57651 | val 0.80814
  Epoch 030 - train 0.52218 | val 0.66462
  Classification -> best τ=0.750 (val F1=0.3201)
  Directional -> Accuracy: 0.4651, MCC: -0.0154, F1: 0.0800

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.64607 | val 0.78809
  Epoch 016 - train 0.56043 | val 0.77721
  Classification -> best τ=0.445 (val F1=0.3748)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.63203 | val 0.67442
  Epoch 017 - train 0.61611 | val 0.71340
  Classification -> best τ=0.395 (val F1=0.3396)
  Directional -> Accuracy: 0.5068, MCC: 0.0558, F1: 0.4545

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.56700 | val 0.84499
  Epoch 017 - train 0.67578 | val 1.05033
  Classification -> best τ=0.460 (val F1=0.0594)
  Directional -> Accuracy: 0.5676, MCC: 0.1429, F1: 0.6000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.68084 | val 0.75236
  Epoch 016 - train 0.59878 | val 0.78804
  Classification -> best τ=0.515 (val F1=0.2757)
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.68478 | val 0.75810
  Epoch 016 - train 0.61440 | val 0.82947
  Classification -> best τ=0.450 (val F1=0.3254)
  Directional -> Accuracy: 0.5758, MCC: 0.0000, F1: 0.7308

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.62905 | val 0.85281
  Epoch 019 - train 0.53948 | val 0.97730
  Classification -> best τ=0.610 (val F1=0.2652)
  Directional -> Accuracy: 0.5000, MCC: 0.1489, F1: 0.0870

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.60824 | val 0.71762
  Epoch 016 - train 0.60674 | val 0.87298
  Classification -> best τ=0.370 (val F1=0.2530)
  Directional -> Accuracy: 0.5179, MCC: 0.1353, F1: 0.6400

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.63174 | val 0.70998
  Epoch 017 - train 0.55125 | val 1.02859
  Classification -> best τ=0.465 (val F1=0.3146)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.62949 | val 0.65410
  Epoch 020 - train 0.56826 | val 0.64596
  Epoch 030 - train 0.46521 | val 0.90208
  Epoch 035 - train 0.41512 | val 0.85611
  Classification -> best τ=0.200 (val F1=0.4708)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.62832 | val 0.77797
  Epoch 018 - train 0.56382 | val 0.83424
  Classification -> best τ=0.460 (val F1=0.2631)
  Directional -> Accuracy: 0.5135, MCC: 0.0119, F1: 0.5714

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.62304 | val 0.78853
  Epoch 018 - train 0.58484 | val 1.12544
  Classification -> best τ=0.415 (val F1=0.3397)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.62598 | val 0.69474
  Epoch 020 - train 0.55858 | val 0.69365
  Epoch 030 - train 0.52915 | val 0.71051
  Epoch 032 - train 0.50104 | val 0.70168
  Classification -> best τ=0.420 (val F1=0.3314)
  Directional -> Accuracy: 0.5652, MCC: 0.1250, F1: 0.6552

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.68573 | val 0.68671
  Epoch 020 - train 0.48874 | val 0.57457
  Epoch 030 - train 0.45917 | val 0.57791
  Epoch 040 - train 0.49087 | val 1.02372
  Epoch 048 - train 0.39482 | val 0.56166
  Classification -> best τ=0.260 (val F1=0.5270)
  Directional -> Accuracy: 0.5581, MCC: 0.0259, F1: 0.7077

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.66669 | val 0.70477
  Epoch 020 - train 0.58887 | val 0.89986
  Epoch 022 - train 0.51281 | val 0.70736
  Classification -> best τ=0.600 (val F1=0.3311)
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.64691 | val 0.95023
  Epoch 017 - train 0.61559 | val 2.20359
  Classification -> best τ=0.520 (val F1=0.1914)
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.64985 | val 0.84036
  Epoch 019 - train 0.57328 | val 1.40707
  Classification -> best τ=0.495 (val F1=0.2218)
  Directional -> Accuracy: 0.5000, MCC: -0.0039, F1: 0.4615

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.69919 | val 1.30050
  Epoch 016 - train 0.61922 | val 1.57614
  Classification -> best τ=0.425 (val F1=0.2572)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.63268 | val 0.76261
  Epoch 020 - train 0.55282 | val 0.77800
  Classification -> best τ=0.470 (val F1=0.2060)
  Directional -> Accuracy: 0.5357, MCC: 0.0879, F1: 0.6829

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.63179 | val 0.68879
  Epoch 020 - train 0.59190 | val 0.78633
  Epoch 021 - train 0.64869 | val 0.89520

[I 2026-02-25 03:47:40,754] Trial 198 finished with value: 0.2733413568333331 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.6000000000000001, 'batch_size': 64, 'learning_rate': 0.004239375300344948, 'weight_decay': 0.00021508903479360275, 'lr_patience': 7, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 0.17407356926603335, 'early_stopping_min_delta': 0.0033419114218173635}. Best is trial 179 with value: 0.3025280267941637.

  Classification -> best τ=0.460 (val F1=0.2866)
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2733413568333331
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.61415 | val 0.79387
  Epoch 017 - train 0.55259 | val 1.10209
  Classification -> best τ=0.515 (val F1=0.2510)
  Directional -> Accuracy: 0.5395, MCC: -0.0120, F1: 0.1463

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.60606 | val 0.71183
  Epoch 016 - train 0.58559 | val 0.75803
  Classification -> best τ=0.440 (val F1=0.2495)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.60964 | val 0.81595
  Epoch 018 - train 0.55321 | val 1.18281
  Classification -> best τ=0.470 (val F1=0.3308)
  Directional -> Accuracy: 0.3830, MCC: -0.2359, F1: 0.4082

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.64766 | val 0.76196
  Epoch 017 - train 0.61655 | val 0.82746
  Classification -> best τ=0.400 (val F1=0.2086)
  Directional -> Accuracy: 0.6000, MCC: 0.1892, F1: 0.6429

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.59624 | val 0.70022
  Epoch 020 - train 0.50792 | val 0.71049
  Epoch 022 - train 0.51938 | val 0.74541
  Classification -> best τ=0.660 (val F1=0.3909)
  Directional -> Accuracy: 0.5098, MCC: 0.0448, F1: 0.4186

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.58307 | val 0.69417
  Epoch 016 - train 0.51213 | val 0.80435
  Classification -> best τ=0.475 (val F1=0.2182)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.64062 | val 0.89875
  Epoch 017 - train 0.58497 | val 1.03614
  Classification -> best τ=0.450 (val F1=0.2232)
  Directional -> Accuracy: 0.4928, MCC: 0.1234, F1: 0.5783

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.59783 | val 0.78485
  Epoch 016 - train 0.53500 | val 0.86316
  Classification -> best τ=0.490 (val F1=0.4135)
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.58708 | val 0.71400
  Epoch 018 - train 0.50097 | val 0.96768
  Classification -> best τ=0.475 (val F1=0.3509)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.61467 | val 0.71317
  Epoch 017 - train 0.54212 | val 0.93262
  Classification -> best τ=0.495 (val F1=0.2974)
  Directional -> Accuracy: 0.4286, MCC: -0.0849, F1: 0.5122

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.63254 | val 0.96387
  Epoch 017 - train 0.55728 | val 1.83807
  Classification -> best τ=0.505 (val F1=0.0903)
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.6301

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.60165 | val 0.74582
  Epoch 017 - train 0.55588 | val 0.82966
  Classification -> best τ=0.510 (val F1=0.0061)
  Directional -> Accuracy: 0.3276, MCC: -0.3450, F1: 0.3390

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.60354 | val 0.93943
  Epoch 017 - train 0.52989 | val 1.89160
  Classification -> best τ=0.455 (val F1=0.0710)
  Directional -> Accuracy: 0.4286, MCC: -0.1194, F1: 0.5862

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.66148 | val 0.63774
  Epoch 020 - train 0.56576 | val 0.99233
  Epoch 023 - train 0.51092 | val 1.03194
  Classification -> best τ=0.400 (val F1=0.3320)
  Directional -> Accuracy: 0.5333, MCC: 0.0692, F1: 0.5882

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.57388 | val 0.71943
  Epoch 020 - train 0.49810 | val 1.16958
  Classification -> best τ=0.485 (val F1=0.2160)
  Directional -> Accuracy: 0.6154, MCC: 0.2334, F1: 0.4118

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.61248 | val 0.77628
  Epoch 017 - train 0.62240 | val 0.79007
  Classification -> best τ=0.500 (val F1=0.2962)
  Directional -> Accuracy: 0.6232, MCC: 0.2535, F1: 0.7174

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.62398 | val 0.86582
  Epoch 016 - train 0.54683 | val 1.25750
  Classification -> best τ=0.405 (val F1=0.1905)
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.63705 | val 0.97653
  Epoch 016 - train 0.61581 | val 1.05153
  Classification -> best τ=0.485 (val F1=0.0784)
  Directional -> Accuracy: 0.6000, MCC: 0.0000, F1: 0.7500

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.61059 | val 1.07873
  Epoch 017 - train 0.56738 | val 2.07024
  Classification -> best τ=0.420 (val F1=0.2522)
  Directional -> Accuracy: 0.5077, MCC: 0.1597, F1: 0.3600

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.60088 | val 0.82659
  Epoch 017 - train 0.57491 | val 1.15146
  Classification -> best τ=0.480 (val F1=0.2669)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.61024 | val 0.68145
  Epoch 020 - train 0.51637 | val 1.44079
  Epoch 022 - train 0.49643 | val 2.01692
  Classification -> best τ=0.495 (val F1=0.3287)
  Directional -> Accuracy: 0.4468, MCC: 0.2057, F1: 0.1875

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.61853 | val 0.75015
  Epoch 016 - train 0.60402 | val 0.84440
  Classification -> best τ=0.530 (val F1=0.2304)
  Directional -> Accuracy: 0.4242, MCC: -0.1673, F1: 0.2692

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.60274 | val 0.70268
  Epoch 018 - train 0.59583 | val 0.85690
  Classification -> best τ=0.795 (val F1=0.2967)
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.63371 | val 0.72062
  Epoch 017 - train 0.53867 | val 1.57375
  Classification -> best τ=0.610 (val F1=0.1507)
  Directional -> Accuracy: 0.4923, MCC: -0.0359, F1: 0.3529

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.60825 | val 0.66197
  Epoch 020 - train 0.49004 | val 0.78724
  Epoch 023 - train 0.48509 | val 0.80303
  Classification -> best τ=0.485 (val F1=0.3608)
  Directional -> Accuracy: 0.4821, MCC: 0.0207, F1: 0.3556

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.67331 | val 0.70370
  Epoch 019 - train 0.52520 | val 0.87711
  Classification -> best τ=0.490 (val F1=0.3669)
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.63513 | val 0.67924
  Epoch 020 - train 0.59943 | val 0.75044
  Epoch 030 - train 0.49478 | val 0.66094
  Classification -> best τ=0.555 (val F1=0.3443)
  Directional -> Accuracy: 0.6190, MCC: 0.1936, F1: 0.7143

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.61073 | val 0.83029
  Epoch 016 - train 0.53965 | val 0.97133
  Classification -> best τ=0.475 (val F1=0.3763)
  Directional -> Accuracy: 0.4561, MCC: 0.1181, F1: 0.0606

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.60750 | val 0.67060
  Epoch 020 - train 0.59320 | val 0.91074
  Epoch 030 - train 0.50815 | val 0.89549
  Epoch 040 - train 0.44104 | val 1.93536
  Epoch 042 - train 0.38791 | val 2.99428
  Classification -> best τ=0.665 (val F1=0.5311)
  Directional -> Accuracy: 0.4878, MCC: -0.0503, F1: 0.5714

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.61143 | val 0.81094
  Epoch 016 - train 0.55849 | val 0.86542
  Classification -> best τ=0.590 (val F1=0.2814)
  Directional -> Accuracy: 0.4884, MCC: -0.0397, F1: 0.3125

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.62829 | val 0.65968
  Epoch 020 - train 0.54204 | val 0.71610
  Epoch 025 - train 0.43914 | val 1.06318
  Classification -> best τ=0.415 (val F1=0.2517)
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.56878 | val 0.81174
  Epoch 016 - train 0.52656 | val 1.40777
  Classification -> best τ=0.495 (val F1=0.2969)
  Directional -> Accuracy: 0.4600, MCC: -0.0983, F1: 0.5263

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.61667 | val 0.72010
  Epoch 019 - train 0.56769 | val 1.12438
  Classification -> best τ=0.415 (val F1=0.3625)
  Directional -> Accuracy: 0.5479, MCC: 0.1207, F1: 0.5352

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.54630 | val 0.74797
  Epoch 018 - train 0.48220 | val 0.96029
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.62230 | val 0.71786
  Epoch 020 - train 0.53619 | val 0.78740
  Classification -> best τ=0.475 (val F1=0.1283)
  Directional -> Accuracy: 0.5227, MCC: 0.0344, F1: 0.4324

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.61558 | val 0.86943
  Epoch 016 - train 0.58336 | val 0.87860
  Classification -> best τ=0.460 (val F1=0.3551)
  Directional -> Accuracy: 0.5303, MCC: 0.0156, F1: 0.6173

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.56349 | val 0.81850
  Epoch 016 - train 0.50872 | val 1.07829
  Classification -> best τ=0.550 (val F1=0.2652)
  Directional -> Accuracy: 0.6667, MCC: 0.3553, F1: 0.6316

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.62684 | val 0.67950
  Epoch 016 - train 0.58632 | val 0.70886
  Classification -> best τ=0.440 (val F1=0.2450)
  Directional -> Accuracy: 0.5357, MCC: 0.1240, F1: 0.6176

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.53062 | val 0.81623
  Epoch 017 - train 0.47110 | val 0.92124
  Classification -> best τ=0.465 (val F1=0.2118)
  Directional -> Accuracy: 0.4783, MCC: -0.0156, F1: 0.5000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.59351 | val 0.69922
  Epoch 020 - train 0.55181 | val 0.76544
  Epoch 021 - train 0.52879 | val 0.76123
  Classification -> best τ=0.460 (val F1=0.2012)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.59870 | val 0.72893
  Epoch 016 - train 0.50392 | val 0.75172
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.63319 | val 0.73153
  Epoch 018 - train 0.56311 | val 1.39509
  Classification -> best τ=0.475 (val F1=0.3656)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.60353 | val 0.69551
  Epoch 020 - train 0.54071 | val 0.69940
  Epoch 030 - train 0.44935 | val 0.90763
  Epoch 032 - train 0.40885 | val 0.83667
  Classification -> best τ=0.510 (val F1=0.3861)
  Directional -> Accuracy: 0.5652, MCC: 0.1232, F1: 0.6296

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.58401 | val 0.62380
  Epoch 020 - train 0.49156 | val 0.54680
  Epoch 030 - train 0.47040 | val 0.49994
  Epoch 040 - train 0.41163 | val 0.58443
  Epoch 047 - train 0.33819 | val 0.90874
  Classification -> best τ=0.420 (val F1=0.6250)
  Directional -> Accuracy: 0.6279, MCC: 0.2296, F1: 0.7143

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.57970 | val 0.67547
  Epoch 020 - train 0.53161 | val 0.70317
  Epoch 022 - train 0.50739 | val 0.65385
  Classification -> best τ=0.535 (val F1=0.5514)
  Directional -> Accuracy: 0.3673, MCC: -0.1468, F1: 0.5079

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.63943 | val 1.00111
  Epoch 017 - train 0.59039 | val 1.30585
  Classification -> best τ=0.455 (val F1=0.1161)
  Directional -> Accuracy: 0.5536, MCC: 0.0812, F1: 0.6835

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.63604 | val 0.84440
  Epoch 017 - train 0.57471 | val 1.54473
  Classification -> best τ=0.590 (val F1=0.3241)
  Directional -> Accuracy: 0.4821, MCC: -0.0246, F1: 0.5538

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.63961 | val 0.94153
  Epoch 017 - train 0.56834 | val 1.03953
  Classification -> best τ=0.450 (val F1=0.2325)
  Directional -> Accuracy: 0.5556, MCC: 0.1131, F1: 0.6667

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.61641 | val 0.78350
  Epoch 019 - train 0.50021 | val 0.99243
  Classification -> best τ=0.445 (val F1=0.1473)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.61595 | val 0.66917
  Epoch 020 - train 0.60199 | val 0.74012

[I 2026-02-25 03:49:40,867] Trial 199 finished with value: 0.2666071810919924 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.5, 'batch_size': 64, 'learning_rate': 0.0032080279998553335, 'weight_decay': 0.000250474776943021, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 0.1565994539889126, 'early_stopping_min_delta': 0.0035771258746424613}. Best is trial 179 with value: 0.3025280267941637.

  Epoch 025 - train 0.51140 | val 1.30540
  Classification -> best τ=0.525 (val F1=0.2639)
  Directional -> Accuracy: 0.4918, MCC: -0.0781, F1: 0.1622

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2666071810919924
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.65419 | val 0.66425
  Epoch 020 - train 0.62366 | val 0.71183
  Epoch 021 - train 0.64685 | val 0.69289
  Classification -> best τ=0.525 (val F1=0.2510)
  Directional -> Accuracy: 0.5000, MCC: -0.2121, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.69200 | val 0.68029
  Epoch 020 - train 0.64951 | val 0.69514
  Epoch 025 - train 0.59089 | val 0.70816
  Classification -> best τ=0.480 (val F1=0.3012)
  Directional -> Accuracy: 0.6222, MCC: 0.1909, F1: 0.7302

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.69860 | val 0.75710
  Epoch 020 - train 0.61753 | val 0.88929
  Epoch 021 - train 0.61616 | val 0.87797
  Classification -> best τ=0.520 (val F1=0.2514)
  Directional -> Accuracy: 0.5532, MCC: 0.2311, F1: 0.3226

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.67329 | val 0.71823
  Epoch 017 - train 0.66770 | val 0.87721
  Classification -> best τ=0.460 (val F1=0.2086)
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.64415 | val 0.65013
  Epoch 020 - train 0.57717 | val 0.72422
  Epoch 023 - train 0.52807 | val 0.99833
  Classification -> best τ=0.585 (val F1=0.4858)
  Directional -> Accuracy: 0.5490, MCC: 0.1295, F1: 0.4651

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.68038 | val 0.69923
  Epoch 020 - train 0.53360 | val 0.69437
  Epoch 030 - train 0.60165 | val 0.80245
  Classification -> best τ=0.575 (val F1=0.2928)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.70058 | val 0.73614
  Epoch 019 - train 0.67898 | val 0.70604
  Classification -> best τ=0.475 (val F1=0.1922)
  Directional -> Accuracy: 0.4928, MCC: 0.1044, F1: 0.5679

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.66459 | val 0.73407
  Epoch 020 - train 0.52978 | val 0.92411
  Classification -> best τ=0.315 (val F1=0.3443)
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.61839 | val 0.68646
  Epoch 020 - train 0.63975 | val 1.00483
  Epoch 022 - train 0.51887 | val 1.08897
  Classification -> best τ=0.440 (val F1=0.2452)
  Directional -> Accuracy: 0.5918, MCC: 0.3222, F1: 0.6774

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.65487 | val 0.68355
  Epoch 020 - train 0.59870 | val 0.95164
  Epoch 025 - train 0.57721 | val 0.82806
  Classification -> best τ=0.470 (val F1=0.3685)
  Directional -> Accuracy: 0.4000, MCC: -0.1980, F1: 0.3636

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.64426 | val 1.09398
  Epoch 017 - train 0.59782 | val 1.69894
  Classification -> best τ=0.490 (val F1=0.2107)
  Directional -> Accuracy: 0.6000, MCC: 0.2274, F1: 0.2857

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.61690 | val 0.89924
  Epoch 018 - train 0.60796 | val 0.91433
  Classification -> best τ=0.510 (val F1=0.2245)
  Directional -> Accuracy: 0.5172, MCC: 0.0413, F1: 0.6216

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.65032 | val 0.75809
  Epoch 016 - train 0.62162 | val 0.82534
  Classification -> best τ=0.490 (val F1=0.2647)
  Directional -> Accuracy: 0.5714, MCC: 0.1783, F1: 0.6087

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.66957 | val 0.64968
  Epoch 020 - train 0.59970 | val 1.09169
  Epoch 022 - train 0.59707 | val 1.40717
  Classification -> best τ=0.425 (val F1=0.3833)
  Directional -> Accuracy: 0.5333, MCC: 0.0668, F1: 0.5484

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.66408 | val 0.77717
  Epoch 019 - train 0.53598 | val 0.75982
  Classification -> best τ=0.620 (val F1=0.2673)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.68890 | val 0.83026
  Epoch 020 - train 0.64211 | val 0.76640
  Epoch 021 - train 0.63799 | val 0.68491
  Classification -> best τ=0.450 (val F1=0.2885)
  Directional -> Accuracy: 0.5652, MCC: 0.1105, F1: 0.6512

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.65636 | val 0.87460
  Epoch 020 - train 0.57885 | val 1.20460
  Epoch 022 - train 0.58376 | val 1.16974
  Classification -> best τ=0.675 (val F1=0.1842)
  Directional -> Accuracy: 0.3729, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.65868 | val 0.88576
  Epoch 017 - train 0.62899 | val 1.97915
  Classification -> best τ=0.505 (val F1=0.0624)
  Directional -> Accuracy: 0.5733, MCC: -0.1351, F1: 0.7288

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.64124 | val 0.90576
  Epoch 016 - train 0.63266 | val 1.64776
  Classification -> best τ=0.400 (val F1=0.2843)
  Directional -> Accuracy: 0.5692, MCC: 0.2643, F1: 0.4815

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.68497 | val 0.70682
  Epoch 018 - train 0.64268 | val 0.74212
  Classification -> best τ=0.495 (val F1=0.2407)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.66879 | val 0.70459
  Epoch 020 - train 0.55712 | val 0.76578
  Epoch 027 - train 0.56756 | val 1.26653
  Classification -> best τ=0.400 (val F1=0.2845)
  Directional -> Accuracy: 0.4894, MCC: 0.2066, F1: 0.3333

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.66920 | val 0.72243
  Epoch 020 - train 0.64612 | val 0.84118
  Epoch 022 - train 0.63106 | val 0.78552
  Classification -> best τ=0.415 (val F1=0.2390)
  Directional -> Accuracy: 0.5152, MCC: 0.0727, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.69843 | val 0.69434
  Epoch 020 - train 0.63811 | val 0.81431
  Classification -> best τ=0.550 (val F1=0.3342)
  Directional -> Accuracy: 0.5690, MCC: 0.1441, F1: 0.5902

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.66019 | val 0.69257
  Epoch 017 - train 0.62312 | val 0.71132
  Classification -> best τ=0.460 (val F1=0.2647)
  Directional -> Accuracy: 0.5077, MCC: 0.1163, F1: 0.6522

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.65324 | val 0.62966
  Epoch 020 - train 0.58065 | val 0.70365
  Epoch 025 - train 0.54953 | val 0.72973
  Classification -> best τ=0.515 (val F1=0.4330)
  Directional -> Accuracy: 0.5357, MCC: 0.1376, F1: 0.4348

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.65446 | val 0.74023
  Epoch 020 - train 0.61184 | val 0.76786
  Epoch 022 - train 0.59724 | val 0.79479
  Classification -> best τ=0.435 (val F1=0.2935)
  Directional -> Accuracy: 0.6739, MCC: 0.3508, F1: 0.6512

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.65485 | val 0.69327
  Epoch 020 - train 0.59033 | val 0.68880
  Epoch 027 - train 0.57524 | val 0.72242
  Classification -> best τ=0.540 (val F1=0.3339)
  Directional -> Accuracy: 0.5952, MCC: 0.1334, F1: 0.7302

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.62855 | val 0.70492
  Epoch 016 - train 0.62464 | val 0.81556
  Classification -> best τ=0.445 (val F1=0.2875)
  Directional -> Accuracy: 0.5088, MCC: 0.2428, F1: 0.2222

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.74599 | val 0.72143
  Epoch 020 - train 0.56768 | val 0.74299
  Epoch 030 - train 0.59562 | val 0.65337
  Epoch 040 - train 0.59405 | val 0.76315
  Epoch 041 - train 0.57206 | val 0.83415
  Classification -> best τ=0.375 (val F1=0.4109)
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.67914 | val 0.76767
  Epoch 020 - train 0.64336 | val 1.08113
  Epoch 021 - train 0.62860 | val 0.89421
  Classification -> best τ=0.590 (val F1=0.2814)
  Directional -> Accuracy: 0.5581, MCC: 0.1366, F1: 0.6275

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.71677 | val 0.66286
  Epoch 020 - train 0.59674 | val 0.79124
  Epoch 025 - train 0.57168 | val 0.77553
  Classification -> best τ=0.505 (val F1=0.3615)
  Directional -> Accuracy: 0.5581, MCC: 0.0944, F1: 0.6545

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.62990 | val 0.73066
  Epoch 016 - train 0.53702 | val 0.82527
  Classification -> best τ=0.410 (val F1=0.3502)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.66456 | val 0.81936
  Epoch 020 - train 0.61749 | val 0.96485
  Epoch 021 - train 0.59455 | val 1.10581
  Classification -> best τ=0.410 (val F1=0.3282)
  Directional -> Accuracy: 0.5068, MCC: 0.0948, F1: 0.3793

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.71878 | val 0.79799
  Epoch 016 - train 0.70072 | val 0.70333
  Classification -> best τ=0.480 (val F1=0.4303)
  Directional -> Accuracy: 0.5405, MCC: 0.1053, F1: 0.6222

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.63235 | val 0.84454
  Epoch 017 - train 0.61906 | val 0.92845
  Classification -> best τ=0.525 (val F1=0.3737)
  Directional -> Accuracy: 0.5909, MCC: 0.1767, F1: 0.5000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.66811 | val 0.73970
  Epoch 018 - train 0.61998 | val 0.74975
  Classification -> best τ=0.475 (val F1=0.3420)
  Directional -> Accuracy: 0.4242, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.64959 | val 0.74152
  Epoch 017 - train 0.54849 | val 0.79245
  Classification -> best τ=0.500 (val F1=0.2304)
  Directional -> Accuracy: 0.6667, MCC: 0.3318, F1: 0.6818

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.67337 | val 0.70314
  Epoch 018 - train 0.63108 | val 0.83082
  Classification -> best τ=0.345 (val F1=0.2868)
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.6341

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.66246 | val 0.82150
  Epoch 018 - train 0.59512 | val 0.69814
  Classification -> best τ=0.505 (val F1=0.2659)
  Directional -> Accuracy: 0.3913, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.71675 | val 0.64609
  Epoch 020 - train 0.59483 | val 0.65026
  Epoch 030 - train 0.57163 | val 0.62751
  Epoch 040 - train 0.58553 | val 0.74710
  Epoch 046 - train 0.49266 | val 0.62356
  Classification -> best τ=0.290 (val F1=0.5617)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.74039 | val 0.76146
  Epoch 020 - train 0.61749 | val 0.88660
  Classification -> best τ=0.555 (val F1=0.4776)
  Directional -> Accuracy: 0.4595, MCC: -0.0194, F1: 0.0909

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.63424 | val 0.72723
  Epoch 020 - train 0.59315 | val 1.16273
  Epoch 021 - train 0.58464 | val 1.19160
  Classification -> best τ=0.460 (val F1=0.4140)
  Directional -> Accuracy: 0.5200, MCC: 0.0944, F1: 0.6604

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.69089 | val 0.75230
  Epoch 020 - train 0.57456 | val 0.70543
  Classification -> best τ=0.460 (val F1=0.3874)
  Directional -> Accuracy: 0.4348, MCC: -0.1348, F1: 0.1875

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.73207 | val 0.69039
  Epoch 020 - train 0.57932 | val 0.65157
  Epoch 030 - train 0.61283 | val 0.73149
  Epoch 035 - train 0.51277 | val 0.76516
  Classification -> best τ=0.475 (val F1=0.3016)
  Directional -> Accuracy: 0.5349, MCC: -0.0306, F1: 0.6774

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.63609 | val 0.68355
  Epoch 020 - train 0.64386 | val 0.65874
  Epoch 030 - train 0.52826 | val 0.65990
  Epoch 034 - train 0.59102 | val 0.63164
  Classification -> best τ=0.470 (val F1=0.6110)
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.69750 | val 0.93642
  Epoch 018 - train 0.61036 | val 1.36689
  Classification -> best τ=0.480 (val F1=0.3073)
  Directional -> Accuracy: 0.5357, MCC: 0.1536, F1: 0.3500

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.62787 | val 0.92327
  Epoch 016 - train 0.62692 | val 1.44514
  Classification -> best τ=0.595 (val F1=0.2500)
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.66958 | val 1.10982
  Epoch 017 - train 0.63674 | val 1.36675
  Classification -> best τ=0.515 (val F1=0.2011)
  Directional -> Accuracy: 0.4815, MCC: -0.0240, F1: 0.3636

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.64977 | val 0.90211
  Epoch 018 - train 0.60099 | val 1.04369
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.66653 | val 0.68486

[I 2026-02-25 03:51:48,098] Trial 200 finished with value: 0.303360648585588 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 64, 'learning_rate': 0.005355625139505699, 'weight_decay': 0.00018642496804680467, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 0.6631402950086193, 'early_stopping_min_delta': 0.0038845628158698624}. Best is trial 200 with value: 0.303360648585588.

  Epoch 018 - train 0.65303 | val 0.79275
  Classification -> best τ=0.390 (val F1=0.1734)
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.303360648585588
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.61444 | val 0.71772
  Epoch 018 - train 0.57997 | val 0.77421
  Classification -> best τ=0.555 (val F1=0.2036)
  Directional -> Accuracy: 0.6053, MCC: 0.1978, F1: 0.3182

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.60090 | val 0.69614
  Epoch 019 - train 0.50070 | val 0.74679
  Classification -> best τ=0.415 (val F1=0.2095)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.62179 | val 0.74804
  Epoch 018 - train 0.57435 | val 1.44102
  Classification -> best τ=0.440 (val F1=0.3214)
  Directional -> Accuracy: 0.5745, MCC: 0.1723, F1: 0.7059

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.67698 | val 0.84157
  Epoch 017 - train 0.60862 | val 0.89233
  Classification -> best τ=0.510 (val F1=0.0845)
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.56781 | val 0.65427
  Epoch 020 - train 0.49929 | val 0.75394
  Epoch 021 - train 0.60048 | val 0.72721
  Classification -> best τ=0.565 (val F1=0.4692)
  Directional -> Accuracy: 0.6078, MCC: 0.2083, F1: 0.6552

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.63583 | val 0.68972
  Epoch 020 - train 0.48231 | val 1.20748
  Epoch 030 - train 0.42888 | val 1.60559
  Classification -> best τ=0.440 (val F1=0.3397)
  Directional -> Accuracy: 0.4894, MCC: -0.0183, F1: 0.5200

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.63922 | val 0.74280
  Epoch 020 - train 0.64942 | val 0.83570
  Epoch 023 - train 0.60119 | val 0.81778
  Classification -> best τ=0.565 (val F1=0.2165)
  Directional -> Accuracy: 0.5652, MCC: 0.0468, F1: 0.3478

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.55836 | val 0.79536
  Epoch 020 - train 0.50078 | val 1.15269
  Classification -> best τ=0.470 (val F1=0.3236)
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.60054 | val 0.80424
  Epoch 020 - train 0.48656 | val 1.25561
  Classification -> best τ=0.480 (val F1=0.1505)
  Directional -> Accuracy: 0.5918, MCC: 0.1751, F1: 0.5455

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.58995 | val 0.73587
  Epoch 020 - train 0.58684 | val 0.72605
  Classification -> best τ=0.495 (val F1=0.2142)
  Directional -> Accuracy: 0.5286, MCC: 0.0747, F1: 0.5217

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.61950 | val 0.72633
  Epoch 020 - train 0.48003 | val 2.45027
  Epoch 024 - train 0.48721 | val 2.07194
  Classification -> best τ=0.630 (val F1=0.4481)
  Directional -> Accuracy: 0.4800, MCC: 0.1319, F1: 0.6389

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.58538 | val 0.86721
  Epoch 019 - train 0.52386 | val 1.10854
  Classification -> best τ=0.495 (val F1=0.1955)
  Directional -> Accuracy: 0.5690, MCC: 0.2722, F1: 0.6988

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.60407 | val 0.75338
  Epoch 016 - train 0.51200 | val 0.90948
  Classification -> best τ=0.430 (val F1=0.2855)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.63775 | val 0.73413
  Epoch 019 - train 0.56590 | val 1.37633
  Classification -> best τ=0.360 (val F1=0.2446)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.63231 | val 0.75024
  Epoch 020 - train 0.54792 | val 0.82998
  Classification -> best τ=0.500 (val F1=0.2381)
  Directional -> Accuracy: 0.5962, MCC: 0.2906, F1: 0.6769

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.61103 | val 0.75503
  Epoch 018 - train 0.57264 | val 0.86235
  Classification -> best τ=0.465 (val F1=0.3483)
  Directional -> Accuracy: 0.6667, MCC: 0.3554, F1: 0.7473

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.65572 | val 0.93050
  Epoch 018 - train 0.60464 | val 1.39902
  Classification -> best τ=0.440 (val F1=0.0046)
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.63989 | val 0.83460
  Epoch 018 - train 0.57245 | val 1.60928
  Classification -> best τ=0.450 (val F1=0.1210)
  Directional -> Accuracy: 0.4667, MCC: 0.1077, F1: 0.2857

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.61601 | val 1.36294
  Epoch 018 - train 0.59732 | val 2.25600
  Classification -> best τ=0.420 (val F1=0.2522)
  Directional -> Accuracy: 0.5692, MCC: 0.2071, F1: 0.5333

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.63486 | val 0.75594
  Epoch 020 - train 0.59244 | val 1.42800
  Classification -> best τ=0.530 (val F1=0.2940)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.60830 | val 0.70692
  Epoch 016 - train 0.53468 | val 1.01829
  Classification -> best τ=0.550 (val F1=0.0483)
  Directional -> Accuracy: 0.4681, MCC: -0.0301, F1: 0.4898

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.65831 | val 0.75124
  Epoch 017 - train 0.57916 | val 0.98501
  Classification -> best τ=0.560 (val F1=0.1860)
  Directional -> Accuracy: 0.4848, MCC: -0.0381, F1: 0.2609

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.60751 | val 0.80487
  Epoch 016 - train 0.59527 | val 0.84937
  Classification -> best τ=0.550 (val F1=0.2379)
  Directional -> Accuracy: 0.5172, MCC: 0.0762, F1: 0.4815

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.60863 | val 0.80460
  Epoch 017 - train 0.53229 | val 1.06619
  Classification -> best τ=0.585 (val F1=0.1359)
  Directional -> Accuracy: 0.5385, MCC: 0.0636, F1: 0.4000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.58683 | val 0.67788
  Epoch 020 - train 0.55712 | val 0.81131
  Epoch 021 - train 0.56223 | val 0.66103
  Classification -> best τ=0.510 (val F1=0.3824)
  Directional -> Accuracy: 0.5893, MCC: 0.2195, F1: 0.5490

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.61492 | val 0.70755
  Epoch 017 - train 0.54408 | val 0.78394
  Classification -> best τ=0.440 (val F1=0.2035)
  Directional -> Accuracy: 0.5652, MCC: 0.0406, F1: 0.1667

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.63946 | val 0.67610
  Epoch 019 - train 0.57949 | val 0.69223
  Classification -> best τ=0.585 (val F1=0.1936)
  Directional -> Accuracy: 0.4762, MCC: 0.0323, F1: 0.3529

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.60004 | val 0.78547
  Epoch 016 - train 0.57504 | val 0.94944
  Classification -> best τ=0.380 (val F1=0.1939)
  Directional -> Accuracy: 0.5789, MCC: 0.2830, F1: 0.4545

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.66849 | val 0.74177
  Epoch 020 - train 0.51001 | val 0.99495
  Epoch 022 - train 0.51127 | val 0.78173
  Classification -> best τ=0.510 (val F1=0.5577)
  Directional -> Accuracy: 0.5610, MCC: 0.1701, F1: 0.7097

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.65438 | val 0.85857
  Epoch 017 - train 0.56443 | val 0.86533
  Classification -> best τ=0.565 (val F1=0.2814)
  Directional -> Accuracy: 0.5349, MCC: 0.0675, F1: 0.5000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.61572 | val 0.64200
  Epoch 020 - train 0.53745 | val 0.63596
  Epoch 027 - train 0.46135 | val 0.71686
  Classification -> best τ=0.645 (val F1=0.3143)
  Directional -> Accuracy: 0.6047, MCC: 0.2683, F1: 0.5143

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.58190 | val 1.01220
  Epoch 019 - train 0.47566 | val 2.03226
  Classification -> best τ=0.360 (val F1=0.4120)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.62743 | val 0.68058
  Epoch 020 - train 0.55807 | val 1.15118
  Epoch 030 - train 0.49133 | val 0.89305
  Epoch 038 - train 0.55723 | val 2.02272
  Classification -> best τ=0.240 (val F1=0.3346)
  Directional -> Accuracy: 0.5342, MCC: 0.0966, F1: 0.5143

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.59455 | val 0.83557
  Epoch 016 - train 0.53578 | val 0.92682
  Classification -> best τ=0.470 (val F1=0.3651)
  Directional -> Accuracy: 0.4324, MCC: -0.1836, F1: 0.5882

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.65900 | val 0.73641
  Epoch 020 - train 0.53333 | val 0.71348
  Epoch 030 - train 0.49831 | val 1.28379
  Classification -> best τ=0.400 (val F1=0.2757)
  Directional -> Accuracy: 0.5455, MCC: 0.1461, F1: 0.6429

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.63292 | val 0.76122
  Epoch 018 - train 0.58740 | val 0.82615
  Classification -> best τ=0.330 (val F1=0.2778)
  Directional -> Accuracy: 0.5758, MCC: 0.0000, F1: 0.7308

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.53329 | val 0.84865
  Epoch 020 - train 0.49790 | val 0.96713
  Epoch 021 - train 0.52720 | val 1.03775
  Classification -> best τ=0.520 (val F1=0.3556)
  Directional -> Accuracy: 0.6667, MCC: 0.3708, F1: 0.6111

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.59682 | val 0.74160
  Epoch 020 - train 0.55453 | val 0.77885
  Epoch 021 - train 0.58484 | val 0.81283
  Classification -> best τ=0.365 (val F1=0.3280)
  Directional -> Accuracy: 0.5000, MCC: 0.0910, F1: 0.6316

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.56429 | val 0.76938
  Epoch 018 - train 0.49578 | val 0.75981
  Classification -> best τ=0.410 (val F1=0.2474)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.66903 | val 0.74101
  Epoch 020 - train 0.60560 | val 0.65233
  Epoch 030 - train 0.52426 | val 0.70015
  Epoch 040 - train 0.44450 | val 0.63257
  Epoch 050 - train 0.44059 | val 0.74327
  Classification -> best τ=0.405 (val F1=0.6130)
  Directional -> Accuracy: 0.3673, MCC: -0.0568, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.65480 | val 0.91271
  Epoch 016 - train 0.55601 | val 1.13567
  Classification -> best τ=0.515 (val F1=0.0585)
  Directional -> Accuracy: 0.5135, MCC: 0.1463, F1: 0.2500

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.60126 | val 0.72802
  Epoch 020 - train 0.56641 | val 1.39310
  Epoch 023 - train 0.51967 | val 1.54969
  Classification -> best τ=0.370 (val F1=0.4124)
  Directional -> Accuracy: 0.5200, MCC: 0.1155, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.58647 | val 0.73073
  Epoch 020 - train 0.50187 | val 0.71985
  Epoch 028 - train 0.45562 | val 0.74239
  Classification -> best τ=0.490 (val F1=0.4141)
  Directional -> Accuracy: 0.5217, MCC: 0.0596, F1: 0.4500

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.55552 | val 0.69394
  Epoch 020 - train 0.48997 | val 0.68467
  Epoch 030 - train 0.46799 | val 1.19105
  Epoch 037 - train 0.28824 | val 1.18715
  Classification -> best τ=0.405 (val F1=0.5270)
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.7164

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.62695 | val 0.67922
  Epoch 018 - train 0.58644 | val 0.67599
  Classification -> best τ=0.560 (val F1=0.6290)
  Directional -> Accuracy: 0.3673, MCC: -0.1539, F1: 0.4918

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.64576 | val 0.71350
  Epoch 017 - train 0.56468 | val 1.30474
  Classification -> best τ=0.485 (val F1=0.2453)
  Directional -> Accuracy: 0.4107, MCC: -0.2575, F1: 0.5479

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.64751 | val 1.15620
  Epoch 016 - train 0.54456 | val 2.05232
  Classification -> best τ=0.520 (val F1=0.2845)
  Directional -> Accuracy: 0.5357, MCC: 0.1768, F1: 0.6667

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.62262 | val 1.12862
  Epoch 017 - train 0.58761 | val 2.20149
  Classification -> best τ=0.520 (val F1=0.1626)
  Directional -> Accuracy: 0.5185, MCC: 0.0447, F1: 0.4800

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.60922 | val 0.75316
  Epoch 017 - train 0.52587 | val 0.93958
  Classification -> best τ=0.510 (val F1=0.2829)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.66254 | val 0.67843

[I 2026-02-25 03:53:54,036] Trial 201 finished with value: 0.2830189507051884 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.5, 'batch_size': 64, 'learning_rate': 0.004984946772969711, 'weight_decay': 0.0001792767027106804, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 0.19585959014813178, 'early_stopping_min_delta': 0.0038304604268901725}. Best is trial 200 with value: 0.303360648585588.

  Epoch 018 - train 0.57565 | val 0.92125
  Classification -> best τ=0.485 (val F1=0.2258)
  Directional -> Accuracy: 0.4754, MCC: -0.1368, F1: 0.1111

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2830189507051884
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.59642 | val 0.71701
  Epoch 017 - train 0.58531 | val 0.87889
  Classification -> best τ=0.465 (val F1=0.2627)
  Directional -> Accuracy: 0.4079, MCC: -0.1586, F1: 0.4706

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.66040 | val 0.70108
  Epoch 019 - train 0.54284 | val 0.72493
  Classification -> best τ=0.430 (val F1=0.2431)
  Directional -> Accuracy: 0.6000, MCC: 0.1764, F1: 0.7429

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.63429 | val 0.71125
  Epoch 020 - train 0.54018 | val 1.07546
  Classification -> best τ=0.370 (val F1=0.3308)
  Directional -> Accuracy: 0.5319, MCC: 0.0290, F1: 0.6562

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.64703 | val 0.78942
  Epoch 020 - train 0.62941 | val 0.74713
  Epoch 021 - train 0.62378 | val 0.75657
  Classification -> best τ=0.590 (val F1=0.1590)
  Directional -> Accuracy: 0.4667, MCC: 0.1059, F1: 0.0476

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.61655 | val 0.64195
  Epoch 020 - train 0.51480 | val 0.90301
  Epoch 022 - train 0.54745 | val 0.84166
  Classification -> best τ=0.625 (val F1=0.4051)
  Directional -> Accuracy: 0.5882, MCC: 0.2451, F1: 0.4615

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.60134 | val 0.75597
  Epoch 017 - train 0.54207 | val 0.82479
  Classification -> best τ=0.555 (val F1=0.3273)
  Directional -> Accuracy: 0.6170, MCC: 0.2510, F1: 0.5000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.66369 | val 0.75552
  Epoch 017 - train 0.61504 | val 0.70031
  Classification -> best τ=0.585 (val F1=0.1805)
  Directional -> Accuracy: 0.5942, MCC: 0.0331, F1: 0.0667

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.64708 | val 0.63421
  Epoch 019 - train 0.51186 | val 0.99255
  Classification -> best τ=0.285 (val F1=0.2180)
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.61790 | val 0.74251
  Epoch 019 - train 0.53111 | val 1.19921
  Classification -> best τ=0.400 (val F1=0.2494)
  Directional -> Accuracy: 0.7143, MCC: 0.4282, F1: 0.6111

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.62264 | val 0.69316
  Epoch 020 - train 0.52358 | val 0.74558
  Epoch 021 - train 0.53624 | val 0.87948
  Classification -> best τ=0.500 (val F1=0.3834)
  Directional -> Accuracy: 0.4429, MCC: -0.0402, F1: 0.5412

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.58890 | val 0.73522
  Epoch 020 - train 0.54254 | val 1.58876
  Epoch 021 - train 0.54869 | val 2.62668
  Classification -> best τ=0.460 (val F1=0.2449)
  Directional -> Accuracy: 0.5400, MCC: 0.1070, F1: 0.5818

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.62483 | val 1.02152
  Epoch 016 - train 0.51380 | val 1.75498
  Classification -> best τ=0.500 (val F1=0.2105)
  Directional -> Accuracy: 0.5690, MCC: 0.2000, F1: 0.3243

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.59050 | val 0.91652
  Epoch 017 - train 0.55643 | val 1.41980
  Classification -> best τ=0.415 (val F1=0.2731)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.63433 | val 0.67605
  Epoch 016 - train 0.58119 | val 1.45009
  Classification -> best τ=0.495 (val F1=0.2789)
  Directional -> Accuracy: 0.5500, MCC: 0.1048, F1: 0.4706

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.57235 | val 0.85422
  Epoch 020 - train 0.51308 | val 0.78314
  Epoch 023 - train 0.44820 | val 1.06978
  Classification -> best τ=0.565 (val F1=0.2673)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.63725 | val 0.78847
  Epoch 017 - train 0.54460 | val 1.06201
  Classification -> best τ=0.425 (val F1=0.2708)
  Directional -> Accuracy: 0.5652, MCC: 0.1171, F1: 0.6939

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.63427 | val 0.87342
  Epoch 018 - train 0.58096 | val 1.14164
  Classification -> best τ=0.560 (val F1=0.2953)
  Directional -> Accuracy: 0.5763, MCC: -0.0661, F1: 0.7191

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.63985 | val 0.90404
  Epoch 018 - train 0.58882 | val 1.79480
  Classification -> best τ=0.505 (val F1=0.1231)
  Directional -> Accuracy: 0.4400, MCC: -0.1541, F1: 0.5227

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.62456 | val 0.97160
  Epoch 016 - train 0.60594 | val 1.89330
  Classification -> best τ=0.465 (val F1=0.3142)
  Directional -> Accuracy: 0.5538, MCC: 0.0365, F1: 0.6588

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.64481 | val 0.69643
  Epoch 019 - train 0.61901 | val 0.86663
  Classification -> best τ=0.515 (val F1=0.3006)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.60154 | val 0.73057
  Epoch 020 - train 0.55628 | val 1.73376
  Epoch 022 - train 0.53360 | val 1.76241
  Classification -> best τ=0.485 (val F1=0.3278)
  Directional -> Accuracy: 0.5957, MCC: 0.2128, F1: 0.6275

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.64596 | val 0.68511
  Epoch 020 - train 0.62491 | val 0.90995
  Epoch 024 - train 0.53313 | val 0.93029
  Classification -> best τ=0.585 (val F1=0.4074)
  Directional -> Accuracy: 0.5606, MCC: 0.1260, F1: 0.6133

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.62477 | val 0.76259
  Epoch 019 - train 0.55936 | val 0.96040
  Classification -> best τ=0.590 (val F1=0.3213)
  Directional -> Accuracy: 0.5862, MCC: 0.1649, F1: 0.6250

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.60591 | val 0.88730
  Epoch 017 - train 0.63791 | val 0.79862
  Classification -> best τ=0.585 (val F1=0.1507)
  Directional -> Accuracy: 0.4923, MCC: -0.0359, F1: 0.3529

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.68218 | val 0.64553
  Epoch 020 - train 0.56205 | val 0.87716
  Epoch 026 - train 0.50341 | val 0.97973
  Classification -> best τ=0.535 (val F1=0.3824)
  Directional -> Accuracy: 0.5357, MCC: 0.1534, F1: 0.4091

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.64504 | val 0.70013
  Epoch 020 - train 0.51632 | val 0.86135
  Epoch 030 - train 0.50815 | val 0.94870
  Epoch 033 - train 0.47301 | val 1.04124
  Classification -> best τ=0.625 (val F1=0.2686)
  Directional -> Accuracy: 0.6304, MCC: 0.2631, F1: 0.6047

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.65427 | val 0.68333
  Epoch 020 - train 0.54864 | val 0.69364
  Epoch 023 - train 0.56726 | val 0.71729
  Classification -> best τ=0.575 (val F1=0.2402)
  Directional -> Accuracy: 0.4286, MCC: -0.0323, F1: 0.0769

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.58771 | val 0.74453
  Epoch 017 - train 0.55173 | val 0.83974
  Classification -> best τ=0.395 (val F1=0.1568)
  Directional -> Accuracy: 0.5614, MCC: 0.2071, F1: 0.4681

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.63736 | val 0.79358
  Epoch 020 - train 0.57910 | val 1.33165
  Classification -> best τ=0.520 (val F1=0.3518)
  Directional -> Accuracy: 0.5122, MCC: -0.0317, F1: 0.6429

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.61850 | val 0.77724
  Epoch 016 - train 0.57139 | val 1.19299
  Classification -> best τ=0.525 (val F1=0.3398)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.58644 | val 0.66492
  Epoch 020 - train 0.53948 | val 0.70571
  Epoch 023 - train 0.54152 | val 0.70809
  Classification -> best τ=0.645 (val F1=0.3201)
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.58241 | val 0.74135
  Epoch 017 - train 0.53670 | val 1.04531
  Classification -> best τ=0.420 (val F1=0.2150)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.64205 | val 0.78142
  Epoch 019 - train 0.54247 | val 1.33577
  Classification -> best τ=0.595 (val F1=0.2725)
  Directional -> Accuracy: 0.4384, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.59707 | val 0.84149
  Epoch 016 - train 0.55237 | val 1.06489
  Classification -> best τ=0.560 (val F1=0.1992)
  Directional -> Accuracy: 0.5676, MCC: 0.1737, F1: 0.6522

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.65814 | val 0.74384
  Epoch 017 - train 0.53076 | val 1.03175
  Classification -> best τ=0.510 (val F1=0.3103)
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.63282 | val 0.70778
  Epoch 018 - train 0.59576 | val 0.74589
  Classification -> best τ=0.460 (val F1=0.1715)
  Directional -> Accuracy: 0.6212, MCC: 0.2284, F1: 0.6667

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.56023 | val 0.91208
  Epoch 016 - train 0.48835 | val 0.98986
  Classification -> best τ=0.510 (val F1=0.2652)
  Directional -> Accuracy: 0.6190, MCC: 0.2864, F1: 0.5294

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.63128 | val 0.74197
  Epoch 020 - train 0.55394 | val 0.86766
  Epoch 022 - train 0.54793 | val 0.89270
  Classification -> best τ=0.415 (val F1=0.3039)
  Directional -> Accuracy: 0.5000, MCC: 0.0499, F1: 0.6000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.56626 | val 0.78680
  Epoch 016 - train 0.50258 | val 0.74745
  Classification -> best τ=0.440 (val F1=0.3397)
  Directional -> Accuracy: 0.5870, MCC: -0.1195, F1: 0.7397

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.65400 | val 0.72090
  Epoch 020 - train 0.55605 | val 0.83031
  Epoch 030 - train 0.50118 | val 1.01444
  Epoch 031 - train 0.48960 | val 1.09750
  Classification -> best τ=0.275 (val F1=0.5125)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.58671 | val 0.70499
  Epoch 020 - train 0.46554 | val 0.69210
  Epoch 029 - train 0.40215 | val 0.97485
  Classification -> best τ=0.580 (val F1=0.6239)
  Directional -> Accuracy: 0.5135, MCC: 0.0484, F1: 0.4706

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.60228 | val 0.71162
  Epoch 019 - train 0.53372 | val 1.19425
  Classification -> best τ=0.430 (val F1=0.4217)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.59394 | val 0.71757
  Epoch 017 - train 0.59617 | val 0.71793
  Classification -> best τ=0.410 (val F1=0.2933)
  Directional -> Accuracy: 0.4565, MCC: -0.0790, F1: 0.1935

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.56670 | val 0.69194
  Epoch 020 - train 0.46662 | val 0.64955
  Epoch 030 - train 0.36767 | val 0.64493
  Epoch 040 - train 0.24377 | val 1.74451
  Epoch 043 - train 0.22066 | val 1.90457
  Classification -> best τ=0.370 (val F1=0.5752)
  Directional -> Accuracy: 0.6512, MCC: 0.2861, F1: 0.7368

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.59549 | val 0.59632
  Epoch 020 - train 0.57862 | val 0.64479
  Epoch 029 - train 0.40960 | val 0.73046
  Classification -> best τ=0.580 (val F1=0.5557)
  Directional -> Accuracy: 0.3673, MCC: -0.1468, F1: 0.5079

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.61592 | val 0.81862
  Epoch 017 - train 0.58135 | val 1.25055
  Classification -> best τ=0.650 (val F1=0.2239)
  Directional -> Accuracy: 0.5179, MCC: 0.1659, F1: 0.2286

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.61369 | val 1.10244
  Epoch 020 - train 0.50954 | val 2.14180
  Classification -> best τ=0.660 (val F1=0.3359)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.59325 | val 1.46208
  Epoch 017 - train 0.55452 | val 2.69482
  Classification -> best τ=0.445 (val F1=0.2410)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.60897 | val 0.72284
  Epoch 020 - train 0.51170 | val 0.96388
  Epoch 021 - train 0.47875 | val 0.92587
  Classification -> best τ=0.540 (val F1=0.2236)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.65378 | val 0.70799
  Epoch 020 - train 0.57826 | val 0.69171
  Epoch 021 - train 0.54980 | val 0.80687

[I 2026-02-25 03:55:55,903] Trial 202 finished with value: 0.30226495647894897 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.5, 'batch_size': 64, 'learning_rate': 0.005306249002214901, 'weight_decay': 0.00018787645542325248, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 0.21039518746726618, 'early_stopping_min_delta': 0.003916704573859668}. Best is trial 200 with value: 0.303360648585588.

  Classification -> best τ=0.465 (val F1=0.4242)
  Directional -> Accuracy: 0.5246, MCC: 0.0163, F1: 0.1714

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.30226495647894897
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.60494 | val 0.71729
  Epoch 020 - train 0.57959 | val 0.84143
  Epoch 023 - train 0.56292 | val 1.02804
  Classification -> best τ=0.720 (val F1=0.2510)
  Directional -> Accuracy: 0.5395, MCC: -0.0120, F1: 0.1463

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.59641 | val 0.74060
  Epoch 019 - train 0.54822 | val 0.74836
  Classification -> best τ=0.430 (val F1=0.3012)
  Directional -> Accuracy: 0.6222, MCC: 0.1909, F1: 0.7302

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.62883 | val 0.73947
  Epoch 018 - train 0.58233 | val 1.37435
  Classification -> best τ=0.600 (val F1=0.1383)
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.63194 | val 1.02567
  Epoch 020 - train 0.60366 | val 0.94567
  Epoch 022 - train 0.58240 | val 0.85325
  Classification -> best τ=0.450 (val F1=0.2125)
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.58759 | val 0.67985
  Epoch 020 - train 0.55990 | val 0.69732
  Epoch 022 - train 0.54320 | val 0.68017
  Classification -> best τ=0.550 (val F1=0.3493)
  Directional -> Accuracy: 0.7059, MCC: 0.4085, F1: 0.7368

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.58529 | val 0.75287
  Epoch 016 - train 0.53820 | val 0.73060
  Classification -> best τ=0.480 (val F1=0.0679)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.66394 | val 0.69423
  Epoch 020 - train 0.60411 | val 0.81907
  Epoch 024 - train 0.56579 | val 0.88948
  Classification -> best τ=0.445 (val F1=0.2449)
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.64316 | val 0.67873
  Epoch 020 - train 0.48662 | val 0.74348
  Epoch 021 - train 0.44763 | val 0.78101
  Classification -> best τ=0.240 (val F1=0.1752)
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.5902

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.56764 | val 0.92408
  Epoch 017 - train 0.45427 | val 1.40106
  Classification -> best τ=0.435 (val F1=0.1474)
  Directional -> Accuracy: 0.5510, MCC: 0.0212, F1: 0.0833

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.63253 | val 0.68457
  Epoch 020 - train 0.49828 | val 1.01373
  Epoch 024 - train 0.49398 | val 0.72016
  Classification -> best τ=0.450 (val F1=0.2262)
  Directional -> Accuracy: 0.4714, MCC: 0.0000, F1: 0.5316

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.61263 | val 1.11116
  Epoch 019 - train 0.54690 | val 3.33875
  Classification -> best τ=0.535 (val F1=0.4232)
  Directional -> Accuracy: 0.6400, MCC: 0.2715, F1: 0.5263

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.59335 | val 1.09819
  Epoch 016 - train 0.56517 | val 1.28621
  Classification -> best τ=0.440 (val F1=0.2097)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.61424 | val 0.80655
  Epoch 020 - train 0.49032 | val 0.88758
  Epoch 021 - train 0.47915 | val 0.83121
  Classification -> best τ=0.540 (val F1=0.2876)
  Directional -> Accuracy: 0.4286, MCC: -0.1718, F1: 0.6000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.65593 | val 0.63035
  Epoch 020 - train 0.56219 | val 1.58054
  Epoch 024 - train 0.58370 | val 1.72671
  Classification -> best τ=0.510 (val F1=0.3026)
  Directional -> Accuracy: 0.5667, MCC: 0.1414, F1: 0.6286

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.59627 | val 0.73618
  Epoch 019 - train 0.56356 | val 1.01550
  Classification -> best τ=0.565 (val F1=0.1512)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.63592 | val 0.71969
  Epoch 018 - train 0.61528 | val 0.75346
  Classification -> best τ=0.570 (val F1=0.1393)
  Directional -> Accuracy: 0.4928, MCC: 0.0526, F1: 0.2553

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.66501 | val 1.31027
  Epoch 016 - train 0.59716 | val 1.42196
  Classification -> best τ=0.700 (val F1=0.1303)
  Directional -> Accuracy: 0.3729, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.64311 | val 1.18694
  Epoch 016 - train 0.57356 | val 2.31392
  Classification -> best τ=0.305 (val F1=0.1217)
  Directional -> Accuracy: 0.5200, MCC: -0.0615, F1: 0.6400

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.66519 | val 1.15549
  Epoch 019 - train 0.60937 | val 1.94362
  Classification -> best τ=0.545 (val F1=0.4071)
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.64420 | val 0.67583
  Epoch 019 - train 0.58821 | val 0.76427
  Classification -> best τ=0.510 (val F1=0.2938)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.61514 | val 0.71839
  Epoch 020 - train 0.50520 | val 1.19231
  Epoch 023 - train 0.49224 | val 1.24541
  Classification -> best τ=0.450 (val F1=0.3307)
  Directional -> Accuracy: 0.4894, MCC: 0.2718, F1: 0.2941

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.65570 | val 0.85129
  Epoch 018 - train 0.58419 | val 0.98195
  Classification -> best τ=0.455 (val F1=0.2125)
  Directional -> Accuracy: 0.4545, MCC: -0.0954, F1: 0.5263

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.67487 | val 0.80322
  Epoch 020 - train 0.55957 | val 0.85009
  Epoch 021 - train 0.56096 | val 0.99957
  Classification -> best τ=0.510 (val F1=0.3852)
  Directional -> Accuracy: 0.5517, MCC: 0.0230, F1: 0.6750

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.64646 | val 0.73568
  Epoch 017 - train 0.55967 | val 0.89513
  Classification -> best τ=0.490 (val F1=0.1507)
  Directional -> Accuracy: 0.5692, MCC: 0.1393, F1: 0.5625

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.60707 | val 0.66594
  Epoch 020 - train 0.52717 | val 0.76535
  Epoch 027 - train 0.44335 | val 0.97792
  Classification -> best τ=0.620 (val F1=0.3953)
  Directional -> Accuracy: 0.4821, MCC: 0.0313, F1: 0.3256

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.59321 | val 0.73748
  Epoch 017 - train 0.54785 | val 0.91791
  Classification -> best τ=0.525 (val F1=0.2786)
  Directional -> Accuracy: 0.5870, MCC: 0.1700, F1: 0.0952

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.64850 | val 0.70595
  Epoch 020 - train 0.60770 | val 0.68612
  Epoch 021 - train 0.58777 | val 0.69451
  Classification -> best τ=0.570 (val F1=0.1334)
  Directional -> Accuracy: 0.5476, MCC: 0.0446, F1: 0.6415

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.59698 | val 0.85846
  Epoch 018 - train 0.53080 | val 0.85307
  Classification -> best τ=0.380 (val F1=0.1913)
  Directional -> Accuracy: 0.6316, MCC: 0.2373, F1: 0.7273

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.59783 | val 0.65785
  Epoch 020 - train 0.54713 | val 0.75161
  Epoch 030 - train 0.41152 | val 1.77390
  Classification -> best τ=0.380 (val F1=0.4109)
  Directional -> Accuracy: 0.5854, MCC: 0.2437, F1: 0.7213

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.63772 | val 0.75849
  Epoch 017 - train 0.54081 | val 0.95158
  Classification -> best τ=0.595 (val F1=0.2814)
  Directional -> Accuracy: 0.5349, MCC: 0.0675, F1: 0.5000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.56090 | val 0.67772
  Epoch 020 - train 0.54360 | val 0.69484
  Epoch 023 - train 0.44183 | val 0.91135
  Classification -> best τ=0.650 (val F1=0.1729)
  Directional -> Accuracy: 0.6512, MCC: 0.3087, F1: 0.6512

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.58044 | val 0.87814
  Epoch 016 - train 0.52518 | val 1.31555
  Classification -> best τ=0.410 (val F1=0.2837)
  Directional -> Accuracy: 0.5600, MCC: 0.1548, F1: 0.7105

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.63700 | val 0.67611
  Epoch 019 - train 0.57264 | val 0.89208
  Classification -> best τ=0.360 (val F1=0.3244)
  Directional -> Accuracy: 0.5479, MCC: 0.1291, F1: 0.5217

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.67499 | val 0.88090
  Epoch 016 - train 0.56901 | val 0.95551
  Classification -> best τ=0.470 (val F1=0.4500)
  Directional -> Accuracy: 0.5676, MCC: 0.1940, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.63355 | val 0.79592
  Epoch 016 - train 0.54732 | val 0.89409
  Classification -> best τ=0.570 (val F1=0.3103)
  Directional -> Accuracy: 0.5000, MCC: -0.0780, F1: 0.0833

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.64550 | val 0.74453
  Epoch 019 - train 0.60108 | val 0.79738
  Classification -> best τ=0.575 (val F1=0.2618)
  Directional -> Accuracy: 0.4242, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.53478 | val 0.85381
  Epoch 020 - train 0.46624 | val 0.96302
  Epoch 021 - train 0.42610 | val 0.85376
  Classification -> best τ=0.475 (val F1=0.2741)
  Directional -> Accuracy: 0.6905, MCC: 0.4122, F1: 0.6486

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.61029 | val 0.67966
  Epoch 020 - train 0.50989 | val 0.75472
  Epoch 021 - train 0.51216 | val 0.98246
  Classification -> best τ=0.360 (val F1=0.2946)
  Directional -> Accuracy: 0.4821, MCC: 0.0404, F1: 0.6234

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.52808 | val 0.69988
  Epoch 016 - train 0.46733 | val 0.84301
  Classification -> best τ=0.495 (val F1=0.2441)
  Directional -> Accuracy: 0.4130, MCC: -0.0062, F1: 0.1818

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.65251 | val 0.70847
  Epoch 020 - train 0.53111 | val 0.62683
  Epoch 030 - train 0.51777 | val 0.60928
  Epoch 040 - train 0.43149 | val 0.66921
  Epoch 045 - train 0.37502 | val 0.68808
  Classification -> best τ=0.405 (val F1=0.5247)
  Directional -> Accuracy: 0.3469, MCC: -0.1894, F1: 0.5152

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.60320 | val 0.72852
  Epoch 016 - train 0.58312 | val 0.81946
  Classification -> best τ=0.435 (val F1=0.0872)
  Directional -> Accuracy: 0.4595, MCC: -0.1251, F1: 0.5652

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.60146 | val 0.70422
  Epoch 020 - train 0.55383 | val 1.48021
  Epoch 024 - train 0.53582 | val 1.49359
  Classification -> best τ=0.390 (val F1=0.4142)
  Directional -> Accuracy: 0.5200, MCC: 0.1155, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.60123 | val 0.68166
  Epoch 018 - train 0.51514 | val 0.75072
  Classification -> best τ=0.435 (val F1=0.4141)
  Directional -> Accuracy: 0.5217, MCC: 0.0455, F1: 0.5217

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.58996 | val 0.65062
  Epoch 020 - train 0.52452 | val 0.53091
  Epoch 030 - train 0.37958 | val 0.69922
  Epoch 040 - train 0.24571 | val 0.98817
  Epoch 049 - train 0.18306 | val 2.18749
  Classification -> best τ=0.690 (val F1=0.7678)
  Directional -> Accuracy: 0.4651, MCC: -0.0675, F1: 0.4889

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.60869 | val 0.65427
  Epoch 020 - train 0.56354 | val 0.71270
  Epoch 022 - train 0.50060 | val 0.69299
  Classification -> best τ=0.605 (val F1=0.6110)
  Directional -> Accuracy: 0.4082, MCC: -0.0342, F1: 0.5246

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.64788 | val 0.83014
  Epoch 016 - train 0.65193 | val 0.78704
  Classification -> best τ=0.460 (val F1=0.2610)
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.64240 | val 0.90722
  Epoch 017 - train 0.58367 | val 1.18752
  Classification -> best τ=0.495 (val F1=0.3027)
  Directional -> Accuracy: 0.5714, MCC: 0.1443, F1: 0.5714

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.62120 | val 1.29619
  Epoch 017 - train 0.60297 | val 1.91821
  Classification -> best τ=0.380 (val F1=0.1776)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.64077 | val 0.78376
  Epoch 018 - train 0.56018 | val 0.87852
  Classification -> best τ=0.485 (val F1=0.1446)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.65236 | val 0.68233
  Epoch 020 - train 0.53978 | val 0.83678

[I 2026-02-25 03:58:01,185] Trial 203 finished with value: 0.27870945250460066 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.5, 'batch_size': 64, 'learning_rate': 0.005618980143329713, 'weight_decay': 0.00017843890884801155, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 0.2093207801628853, 'early_stopping_min_delta': 0.0037733718112932524}. Best is trial 200 with value: 0.303360648585588.

  Epoch 025 - train 0.53317 | val 0.88123
  Classification -> best τ=0.590 (val F1=0.2639)
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.27870945250460066
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.57025 | val 0.72224
  Epoch 019 - train 0.55328 | val 0.97110
  Classification -> best τ=0.565 (val F1=0.3286)
  Directional -> Accuracy: 0.5526, MCC: 0.0412, F1: 0.2273

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.58891 | val 0.69024
  Epoch 020 - train 0.49229 | val 0.74360
  Epoch 023 - train 0.43356 | val 0.74204
  Classification -> best τ=0.495 (val F1=0.1812)
  Directional -> Accuracy: 0.6444, MCC: 0.2704, F1: 0.7576

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.62408 | val 0.76107
  Epoch 018 - train 0.58312 | val 1.04007
  Classification -> best τ=0.450 (val F1=0.3005)
  Directional -> Accuracy: 0.4894, MCC: -0.0200, F1: 0.5000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.64245 | val 0.88625
  Epoch 017 - train 0.63549 | val 0.78024
  Classification -> best τ=0.465 (val F1=0.1210)
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.62133 | val 0.74353
  Epoch 020 - train 0.47246 | val 0.78285
  Epoch 021 - train 0.47246 | val 0.76652
  Classification -> best τ=0.535 (val F1=0.4255)
  Directional -> Accuracy: 0.5098, MCC: 0.0048, F1: 0.5763

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.57416 | val 0.69199
  Epoch 020 - train 0.48598 | val 1.36340
  Epoch 026 - train 0.38583 | val 1.43224
  Classification -> best τ=0.570 (val F1=0.2357)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.63129 | val 0.75359
  Epoch 020 - train 0.57315 | val 0.81602
  Classification -> best τ=0.465 (val F1=0.2495)
  Directional -> Accuracy: 0.4348, MCC: 0.0049, F1: 0.5517

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.55604 | val 0.65618
  Epoch 018 - train 0.45649 | val 1.76335
  Classification -> best τ=0.390 (val F1=0.1752)
  Directional -> Accuracy: 0.5814, MCC: 0.0364, F1: 0.1000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.58113 | val 0.69579
  Epoch 020 - train 0.47845 | val 1.36709
  Epoch 023 - train 0.45983 | val 1.73286
  Classification -> best τ=0.400 (val F1=0.2076)
  Directional -> Accuracy: 0.5714, MCC: 0.1772, F1: 0.6038

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.60735 | val 0.74672
  Epoch 018 - train 0.54909 | val 0.89288
  Classification -> best τ=0.490 (val F1=0.2249)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.58172 | val 1.18150
  Epoch 017 - train 0.49049 | val 1.47703
  Classification -> best τ=0.400 (val F1=0.2942)
  Directional -> Accuracy: 0.5800, MCC: 0.1405, F1: 0.3636

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.57249 | val 0.76155
  Epoch 020 - train 0.47798 | val 1.06549
  Epoch 022 - train 0.43878 | val 1.38202
  Classification -> best τ=0.630 (val F1=0.2453)
  Directional -> Accuracy: 0.6724, MCC: 0.3727, F1: 0.5957

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.62178 | val 1.12086
  Epoch 016 - train 0.48063 | val 1.59297
  Classification -> best τ=0.495 (val F1=0.2323)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.61046 | val 0.61337
  Epoch 020 - train 0.53330 | val 0.80020
  Epoch 023 - train 0.51357 | val 0.73876
  Classification -> best τ=0.450 (val F1=0.4213)
  Directional -> Accuracy: 0.5500, MCC: 0.1028, F1: 0.5970

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.57728 | val 0.90452
  Epoch 019 - train 0.46373 | val 1.83767
  Classification -> best τ=0.565 (val F1=0.2673)
  Directional -> Accuracy: 0.4615, MCC: -0.0376, F1: 0.5758

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.61412 | val 0.72170
  Epoch 020 - train 0.52003 | val 0.84728
  Classification -> best τ=0.450 (val F1=0.3110)
  Directional -> Accuracy: 0.6087, MCC: 0.2144, F1: 0.7033

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.64055 | val 0.90957
  Epoch 017 - train 0.55315 | val 1.43590
  Classification -> best τ=0.530 (val F1=0.0586)
  Directional -> Accuracy: 0.4237, MCC: -0.2826, F1: 0.5641

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.63379 | val 0.93712
  Epoch 016 - train 0.64194 | val 1.62144
  Classification -> best τ=0.525 (val F1=0.0513)
  Directional -> Accuracy: 0.4000, MCC: -0.1315, F1: 0.3284

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.63091 | val 1.35489
  Epoch 016 - train 0.54955 | val 2.39185
  Classification -> best τ=0.485 (val F1=0.2638)
  Directional -> Accuracy: 0.5231, MCC: 0.1150, F1: 0.4746

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.62666 | val 0.68233
  Epoch 020 - train 0.57889 | val 0.74868
  Epoch 023 - train 0.54736 | val 0.84362
  Classification -> best τ=0.385 (val F1=0.2982)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.59911 | val 0.70340
  Epoch 020 - train 0.50037 | val 1.46152
  Epoch 026 - train 0.40445 | val 1.90263
  Classification -> best τ=0.350 (val F1=0.3278)
  Directional -> Accuracy: 0.5319, MCC: 0.0504, F1: 0.5926

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.59552 | val 0.75002
  Epoch 017 - train 0.60692 | val 1.02230
  Classification -> best τ=0.470 (val F1=0.1664)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6024

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.58128 | val 0.74779
  Epoch 017 - train 0.57715 | val 0.76470
  Classification -> best τ=0.770 (val F1=0.2967)
  Directional -> Accuracy: 0.4483, MCC: 0.1153, F1: 0.0588

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.59736 | val 0.77392
  Epoch 017 - train 0.52909 | val 1.29747
  Classification -> best τ=0.500 (val F1=0.1626)
  Directional -> Accuracy: 0.5231, MCC: 0.1153, F1: 0.6437

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.59141 | val 0.69794
  Epoch 020 - train 0.44858 | val 1.00799
  Epoch 022 - train 0.47133 | val 1.03892
  Classification -> best τ=0.440 (val F1=0.3495)
  Directional -> Accuracy: 0.4464, MCC: -0.1867, F1: 0.5753

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.55819 | val 0.79957
  Epoch 017 - train 0.52872 | val 0.91492
  Classification -> best τ=0.530 (val F1=0.1890)
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.62605 | val 0.73630
  Epoch 020 - train 0.50795 | val 0.67599
  Epoch 030 - train 0.48701 | val 0.90965
  Epoch 034 - train 0.40906 | val 1.06160
  Classification -> best τ=0.600 (val F1=0.2810)
  Directional -> Accuracy: 0.5238, MCC: 0.1452, F1: 0.4118

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.60635 | val 0.72379
  Epoch 017 - train 0.56693 | val 0.77021
  Classification -> best τ=0.380 (val F1=0.2260)
  Directional -> Accuracy: 0.5614, MCC: 0.2530, F1: 0.4186

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.57817 | val 0.65790
  Epoch 020 - train 0.50722 | val 0.96272
  Epoch 030 - train 0.40069 | val 1.53211
  Epoch 032 - train 0.43770 | val 1.84130
  Classification -> best τ=0.690 (val F1=0.4114)
  Directional -> Accuracy: 0.5122, MCC: 0.0416, F1: 0.4737

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.59959 | val 0.73494
  Epoch 017 - train 0.54607 | val 0.83915
  Classification -> best τ=0.530 (val F1=0.2814)
  Directional -> Accuracy: 0.5116, MCC: 0.0288, F1: 0.5532

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.63607 | val 0.75026
  Epoch 020 - train 0.43582 | val 1.08535
  Epoch 021 - train 0.42099 | val 0.96964
  Classification -> best τ=0.590 (val F1=0.3615)
  Directional -> Accuracy: 0.4884, MCC: -0.0864, F1: 0.6207

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.56553 | val 0.69870
  Epoch 018 - train 0.53421 | val 1.13947
  Classification -> best τ=0.445 (val F1=0.3433)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.61318 | val 0.81787
  Epoch 020 - train 0.54873 | val 0.86763
  Epoch 023 - train 0.55529 | val 1.31572
  Classification -> best τ=0.480 (val F1=0.2400)
  Directional -> Accuracy: 0.5342, MCC: 0.1237, F1: 0.4688

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.58689 | val 0.72349
  Epoch 017 - train 0.54629 | val 1.04058
  Classification -> best τ=0.535 (val F1=0.1604)
  Directional -> Accuracy: 0.4865, MCC: -0.0187, F1: 0.5581

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.59683 | val 0.75122
  Epoch 016 - train 0.53854 | val 0.98738
  Classification -> best τ=0.535 (val F1=0.2506)
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.63451 | val 0.76049
  Epoch 016 - train 0.56989 | val 0.84735
  Classification -> best τ=0.340 (val F1=0.3603)
  Directional -> Accuracy: 0.6364, MCC: 0.2491, F1: 0.6923

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.54791 | val 0.87509
  Epoch 018 - train 0.49906 | val 1.08132
  Classification -> best τ=0.545 (val F1=0.3105)
  Directional -> Accuracy: 0.6905, MCC: 0.4321, F1: 0.6286

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.58497 | val 0.74668
  Epoch 016 - train 0.52210 | val 0.79248
  Classification -> best τ=0.595 (val F1=0.1913)
  Directional -> Accuracy: 0.5714, MCC: 0.1281, F1: 0.4783

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.53176 | val 0.72742
  Epoch 016 - train 0.48783 | val 0.87084
  Classification -> best τ=0.480 (val F1=0.2474)
  Directional -> Accuracy: 0.5652, MCC: -0.0460, F1: 0.7059

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.60259 | val 0.68249
  Epoch 020 - train 0.48671 | val 0.64424
  Epoch 030 - train 0.45302 | val 0.67887
  Epoch 032 - train 0.42803 | val 0.68060
  Classification -> best τ=0.340 (val F1=0.5125)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.56111 | val 0.84653
  Epoch 016 - train 0.49855 | val 0.97122
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.58874 | val 1.07937
  Epoch 020 - train 0.53326 | val 1.78459
  Epoch 021 - train 0.52344 | val 1.96503
  Classification -> best τ=0.370 (val F1=0.3620)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.60490 | val 0.66892
  Epoch 020 - train 0.47449 | val 0.66330
  Epoch 026 - train 0.41570 | val 0.94759
  Classification -> best τ=0.315 (val F1=0.4216)
  Directional -> Accuracy: 0.5217, MCC: 0.0200, F1: 0.6452

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.64277 | val 0.82799
  Epoch 020 - train 0.49353 | val 0.71947
  Epoch 021 - train 0.50457 | val 0.72282
  Classification -> best τ=0.490 (val F1=0.3294)
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.7164

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.61863 | val 0.73603
  Epoch 020 - train 0.46094 | val 0.64880
  Epoch 030 - train 0.35446 | val 0.58231
  Epoch 040 - train 0.29821 | val 0.86483
  Epoch 047 - train 0.26066 | val 0.75389
  Classification -> best τ=0.840 (val F1=0.6095)
  Directional -> Accuracy: 0.3469, MCC: -0.2151, F1: 0.4667

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.64171 | val 1.01598
  Epoch 016 - train 0.57947 | val 1.59688
  Classification -> best τ=0.555 (val F1=0.3040)
  Directional -> Accuracy: 0.4821, MCC: 0.0625, F1: 0.1212

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.63834 | val 1.30712
  Epoch 018 - train 0.50469 | val 2.00370
  Classification -> best τ=0.565 (val F1=0.3836)
  Directional -> Accuracy: 0.5357, MCC: 0.0930, F1: 0.6061

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.64186 | val 0.94996
  Epoch 020 - train 0.53759 | val 2.04457
  Epoch 021 - train 0.51841 | val 2.00274
  Classification -> best τ=0.395 (val F1=0.2570)
  Directional -> Accuracy: 0.5185, MCC: 0.0073, F1: 0.6750

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.58950 | val 0.77755
  Epoch 018 - train 0.50495 | val 0.95635
  Classification -> best τ=0.515 (val F1=0.1557)
  Directional -> Accuracy: 0.4286, MCC: -0.1466, F1: 0.2381

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.59844 | val 0.83558

[I 2026-02-25 04:00:04,250] Trial 204 finished with value: 0.27119984709564743 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 64, 'learning_rate': 0.005642773812648611, 'weight_decay': 0.0001583598923327566, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 0.18542219024102607, 'early_stopping_min_delta': 0.003918904281167665}. Best is trial 200 with value: 0.303360648585588.

  Epoch 018 - train 0.51906 | val 1.34453
  Classification -> best τ=0.450 (val F1=0.1748)
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.27119984709564743
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.60174 | val 0.69810
  Epoch 018 - train 0.56499 | val 0.76563
  Classification -> best τ=0.395 (val F1=0.0739)
  Directional -> Accuracy: 0.5658, MCC: 0.1620, F1: 0.5926

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.60909 | val 0.71563
  Epoch 017 - train 0.54112 | val 0.71305
  Classification -> best τ=0.460 (val F1=0.2287)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.65329 | val 0.75722
  Epoch 017 - train 0.59620 | val 0.95463
  Classification -> best τ=0.515 (val F1=0.2449)
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.65600 | val 0.79441
  Epoch 016 - train 0.63393 | val 0.89579
  Classification -> best τ=0.460 (val F1=0.1430)
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.57906 | val 0.67333
  Epoch 020 - train 0.47346 | val 0.68597
  Epoch 023 - train 0.43605 | val 0.71362
  Classification -> best τ=0.620 (val F1=0.3795)
  Directional -> Accuracy: 0.4706, MCC: -0.0556, F1: 0.4706

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.58820 | val 0.70451
  Epoch 020 - train 0.48466 | val 1.69275
  Classification -> best τ=0.530 (val F1=0.2182)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.64720 | val 0.72105
  Epoch 019 - train 0.63429 | val 0.79717
  Classification -> best τ=0.615 (val F1=0.2227)
  Directional -> Accuracy: 0.5652, MCC: -0.0787, F1: 0.0625

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.61376 | val 0.63735
  Epoch 020 - train 0.45974 | val 1.71428
  Epoch 023 - train 0.44114 | val 2.64615
  Classification -> best τ=0.245 (val F1=0.1752)
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.5902

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.60247 | val 0.69599
  Epoch 020 - train 0.50833 | val 0.75188
  Epoch 023 - train 0.53347 | val 0.94234
  Classification -> best τ=0.365 (val F1=0.2820)
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.62122 | val 0.70764
  Epoch 020 - train 0.54903 | val 0.72021
  Epoch 027 - train 0.49586 | val 0.86568
  Classification -> best τ=0.335 (val F1=0.2607)
  Directional -> Accuracy: 0.4429, MCC: -0.0556, F1: 0.5185

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.61620 | val 0.84732
  Epoch 017 - train 0.58555 | val 2.38812
  Classification -> best τ=0.575 (val F1=0.2103)
  Directional -> Accuracy: 0.6600, MCC: 0.3634, F1: 0.4516

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.59230 | val 0.99073
  Epoch 018 - train 0.53453 | val 0.96717
  Classification -> best τ=0.475 (val F1=0.1492)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.62138 | val 1.06555
  Epoch 017 - train 0.53493 | val 1.38017
  Classification -> best τ=0.435 (val F1=0.2731)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.63955 | val 0.66806
  Epoch 020 - train 0.55609 | val 0.67930
  Classification -> best τ=0.400 (val F1=0.3864)
  Directional -> Accuracy: 0.4833, MCC: -0.0370, F1: 0.5753

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.59395 | val 0.79564
  Epoch 020 - train 0.52732 | val 1.14169
  Epoch 021 - train 0.52054 | val 1.11181
  Classification -> best τ=0.555 (val F1=0.2673)
  Directional -> Accuracy: 0.5577, MCC: 0.0949, F1: 0.4390

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.63337 | val 0.69191
  Epoch 020 - train 0.59161 | val 0.87682
  Epoch 024 - train 0.53039 | val 1.11157
  Classification -> best τ=0.495 (val F1=0.2434)
  Directional -> Accuracy: 0.5217, MCC: 0.0405, F1: 0.5479

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.63105 | val 0.99990
  Epoch 016 - train 0.57113 | val 1.05753
  Classification -> best τ=0.500 (val F1=0.1291)
  Directional -> Accuracy: 0.4915, MCC: 0.1891, F1: 0.3750

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.64318 | val 1.22530
  Epoch 016 - train 0.62584 | val 1.16153
  Classification -> best τ=0.505 (val F1=0.1217)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.62115 | val 1.29999
  Epoch 019 - train 0.56731 | val 3.01583
  Classification -> best τ=0.505 (val F1=0.3180)
  Directional -> Accuracy: 0.4462, MCC: 0.0859, F1: 0.1429

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.61993 | val 0.74054
  Epoch 020 - train 0.54376 | val 0.82092
  Classification -> best τ=0.470 (val F1=0.2225)
  Directional -> Accuracy: 0.5200, MCC: -0.0166, F1: 0.6400

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.62085 | val 0.86044
  Epoch 018 - train 0.52067 | val 1.84919
  Classification -> best τ=0.445 (val F1=0.3707)
  Directional -> Accuracy: 0.5106, MCC: 0.0584, F1: 0.5306

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.63050 | val 0.78209
  Epoch 016 - train 0.59071 | val 0.85350
  Classification -> best τ=0.505 (val F1=0.2147)
  Directional -> Accuracy: 0.4394, MCC: -0.1226, F1: 0.4789

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.60032 | val 0.80065
  Epoch 018 - train 0.59911 | val 1.00689
  Classification -> best τ=0.655 (val F1=0.1826)
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.62463 | val 0.79211
  Epoch 020 - train 0.56120 | val 0.93060
  Epoch 022 - train 0.55545 | val 0.97555
  Classification -> best τ=0.395 (val F1=0.1320)
  Directional -> Accuracy: 0.4769, MCC: 0.0000, F1: 0.6458

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.61638 | val 0.74665
  Epoch 017 - train 0.58918 | val 0.97626
  Classification -> best τ=0.450 (val F1=0.4663)
  Directional -> Accuracy: 0.5714, MCC: 0.2385, F1: 0.4545

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.69192 | val 0.82429
  Epoch 017 - train 0.55378 | val 0.83845
  Classification -> best τ=0.470 (val F1=0.2935)
  Directional -> Accuracy: 0.4783, MCC: 0.1870, F1: 0.6250

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.68484 | val 0.68556
  Epoch 020 - train 0.56465 | val 0.73167
  Epoch 030 - train 0.50194 | val 0.98416
  Classification -> best τ=0.580 (val F1=0.2161)
  Directional -> Accuracy: 0.5000, MCC: 0.1698, F1: 0.2759

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.58715 | val 0.69910
  Epoch 018 - train 0.54307 | val 0.87738
  Classification -> best τ=0.355 (val F1=0.2260)
  Directional -> Accuracy: 0.5614, MCC: 0.2277, F1: 0.4444

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.76093 | val 0.68650
  Epoch 020 - train 0.51591 | val 0.63463
  Epoch 030 - train 0.48619 | val 0.94302
  Epoch 034 - train 0.44889 | val 1.68387
  Classification -> best τ=0.580 (val F1=0.4719)
  Directional -> Accuracy: 0.5122, MCC: 0.0050, F1: 0.5833

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.55919 | val 0.79466
  Epoch 018 - train 0.50914 | val 1.09073
  Classification -> best τ=0.625 (val F1=0.2814)
  Directional -> Accuracy: 0.5581, MCC: 0.1169, F1: 0.5581

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.64476 | val 0.67862
  Epoch 020 - train 0.52491 | val 0.80184
  Classification -> best τ=0.645 (val F1=0.2151)
  Directional -> Accuracy: 0.4884, MCC: -0.0604, F1: 0.5926

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.58332 | val 0.75644
  Epoch 016 - train 0.54160 | val 1.17377
  Classification -> best τ=0.495 (val F1=0.4451)
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.60494 | val 0.66265
  Epoch 020 - train 0.56995 | val 1.16245
  Epoch 024 - train 0.53016 | val 1.41129
  Classification -> best τ=0.350 (val F1=0.3268)
  Directional -> Accuracy: 0.5342, MCC: 0.1465, F1: 0.4333

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.66160 | val 0.81990
  Epoch 018 - train 0.54166 | val 1.03364
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.63651 | val 0.77369
  Epoch 016 - train 0.55870 | val 1.00128
  Classification -> best τ=0.535 (val F1=0.2537)
  Directional -> Accuracy: 0.5682, MCC: 0.1548, F1: 0.6122

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.63947 | val 0.76434
  Epoch 020 - train 0.57042 | val 0.81168
  Epoch 021 - train 0.57729 | val 0.81662
  Classification -> best τ=0.325 (val F1=0.3855)
  Directional -> Accuracy: 0.5909, MCC: 0.1313, F1: 0.6824

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.68180 | val 0.90703
  Epoch 016 - train 0.56432 | val 1.15306
  Classification -> best τ=0.540 (val F1=0.3556)
  Directional -> Accuracy: 0.6667, MCC: 0.3553, F1: 0.6316

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.63018 | val 0.69768
  Epoch 016 - train 0.54001 | val 0.76683
  Classification -> best τ=0.420 (val F1=0.3039)
  Directional -> Accuracy: 0.4821, MCC: 0.0404, F1: 0.6234

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.56862 | val 0.74934
  Epoch 016 - train 0.46186 | val 0.89319
  Classification -> best τ=0.495 (val F1=0.2441)
  Directional -> Accuracy: 0.3913, MCC: -0.1022, F1: 0.2222

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.66763 | val 0.70147
  Epoch 020 - train 0.55297 | val 0.78109
  Epoch 021 - train 0.56301 | val 0.66300
  Classification -> best τ=0.415 (val F1=0.3125)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.65497 | val 0.78544
  Epoch 020 - train 0.53999 | val 0.88190
  Epoch 030 - train 0.38255 | val 1.61443
  Epoch 031 - train 0.44847 | val 1.56790
  Classification -> best τ=0.475 (val F1=0.3699)
  Directional -> Accuracy: 0.4595, MCC: -0.0882, F1: 0.5000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.60547 | val 0.77693
  Epoch 017 - train 0.57448 | val 1.12313
  Classification -> best τ=0.430 (val F1=0.4537)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.61960 | val 0.70147
  Epoch 020 - train 0.53399 | val 0.74267
  Epoch 030 - train 0.42801 | val 0.69374
  Epoch 034 - train 0.39315 | val 1.06138
  Classification -> best τ=0.480 (val F1=0.6146)
  Directional -> Accuracy: 0.5652, MCC: 0.1326, F1: 0.5652

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.58383 | val 0.69576
  Epoch 020 - train 0.50616 | val 0.62619
  Epoch 030 - train 0.39793 | val 0.65651
  Epoch 040 - train 0.33908 | val 0.88257
  Epoch 041 - train 0.29396 | val 0.85071
  Classification -> best τ=0.200 (val F1=0.5270)
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.7164

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.62791 | val 0.54872
  Epoch 020 - train 0.49050 | val 0.61882
  Epoch 025 - train 0.49421 | val 0.66795
  Classification -> best τ=0.535 (val F1=0.6058)
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.68649 | val 0.89013
  Epoch 019 - train 0.61108 | val 0.99470
  Classification -> best τ=0.495 (val F1=0.2565)
  Directional -> Accuracy: 0.5357, MCC: 0.1371, F1: 0.3810

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.64976 | val 1.06144
  Epoch 018 - train 0.59608 | val 1.57989
  Classification -> best τ=0.475 (val F1=0.3500)
  Directional -> Accuracy: 0.5357, MCC: 0.0830, F1: 0.5806

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.63072 | val 0.85753
  Epoch 017 - train 0.62436 | val 1.07269
  Classification -> best τ=0.515 (val F1=0.2024)
  Directional -> Accuracy: 0.5370, MCC: 0.0648, F1: 0.6479

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.62772 | val 0.68912
  Epoch 020 - train 0.51817 | val 0.95282
  Epoch 025 - train 0.46428 | val 1.15473
  Classification -> best τ=0.390 (val F1=0.1667)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.67581 | val 0.84060
  Epoch 020 - train 0.59270 | val 0.96463

[I 2026-02-25 04:02:07,559] Trial 205 finished with value: 0.27995584443411103 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.5, 'batch_size': 64, 'learning_rate': 0.005381709402924997, 'weight_decay': 0.0001726479228849922, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 0.8467201814464518, 'early_stopping_min_delta': 0.0034355814337038862}. Best is trial 200 with value: 0.303360648585588.

  Epoch 023 - train 0.57109 | val 0.75845
  Classification -> best τ=0.435 (val F1=0.2039)
  Directional -> Accuracy: 0.4754, MCC: -0.0862, F1: 0.2727

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.27995584443411103
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.59340 | val 0.88017
  Epoch 018 - train 0.52491 | val 1.04426
  Classification -> best τ=0.430 (val F1=0.1968)
  Directional -> Accuracy: 0.4474, MCC: 0.0000, F1: 0.6182

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.61931 | val 0.71973
  Epoch 019 - train 0.53677 | val 0.76184
  Classification -> best τ=0.390 (val F1=0.1870)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.62913 | val 0.77711
  Epoch 018 - train 0.57994 | val 1.30184
  Classification -> best τ=0.505 (val F1=0.3383)
  Directional -> Accuracy: 0.4894, MCC: 0.0081, F1: 0.3684

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.65288 | val 0.76642
  Epoch 016 - train 0.59419 | val 0.78186
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.60798 | val 0.70429
  Epoch 020 - train 0.48387 | val 0.81841
  Epoch 022 - train 0.47443 | val 0.82485
  Classification -> best τ=0.470 (val F1=0.3612)
  Directional -> Accuracy: 0.5098, MCC: -0.1333, F1: 0.6753

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.56819 | val 0.69862
  Epoch 016 - train 0.49694 | val 0.80200
  Classification -> best τ=0.490 (val F1=0.2928)
  Directional -> Accuracy: 0.5106, MCC: 0.0096, F1: 0.2581

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.63162 | val 0.73203
  Epoch 018 - train 0.57509 | val 1.20129
  Classification -> best τ=0.480 (val F1=0.1988)
  Directional -> Accuracy: 0.4928, MCC: 0.1725, F1: 0.5977

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.50337 | val 0.99014
  Epoch 020 - train 0.44510 | val 1.77445
  Classification -> best τ=0.425 (val F1=0.1214)
  Directional -> Accuracy: 0.4884, MCC: -0.0680, F1: 0.3529

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.57546 | val 0.72828
  Epoch 020 - train 0.48188 | val 1.17633
  Epoch 021 - train 0.46005 | val 1.18516
  Classification -> best τ=0.495 (val F1=0.4249)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.58301 | val 0.79072
  Epoch 017 - train 0.50858 | val 0.99392
  Classification -> best τ=0.450 (val F1=0.2241)
  Directional -> Accuracy: 0.4429, MCC: 0.0407, F1: 0.5979

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.56803 | val 1.43472
  Epoch 016 - train 0.49643 | val 2.70759
  Classification -> best τ=0.595 (val F1=0.1400)
  Directional -> Accuracy: 0.5600, MCC: 0.1350, F1: 0.5769

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.54086 | val 0.87028
  Epoch 017 - train 0.50847 | val 1.68656
  Classification -> best τ=0.530 (val F1=0.1844)
  Directional -> Accuracy: 0.6207, MCC: 0.2420, F1: 0.6333

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.56606 | val 1.05748
  Epoch 018 - train 0.51045 | val 1.59262
  Classification -> best τ=0.485 (val F1=0.2644)
  Directional -> Accuracy: 0.4524, MCC: -0.1220, F1: 0.3429

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.62527 | val 0.76389
  Epoch 017 - train 0.54714 | val 0.86607
  Classification -> best τ=0.545 (val F1=0.1774)
  Directional -> Accuracy: 0.5500, MCC: 0.1048, F1: 0.4706

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.56963 | val 0.90886
  Epoch 017 - train 0.48135 | val 0.80031
  Classification -> best τ=0.450 (val F1=0.0661)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.58047 | val 0.82710
  Epoch 020 - train 0.52020 | val 1.05482
  Classification -> best τ=0.405 (val F1=0.2927)
  Directional -> Accuracy: 0.5797, MCC: 0.1834, F1: 0.5397

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.59625 | val 1.14031
  Epoch 016 - train 0.55055 | val 1.07886
  Classification -> best τ=0.505 (val F1=0.0499)
  Directional -> Accuracy: 0.6441, MCC: 0.1703, F1: 0.7789

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.61395 | val 1.29750
  Epoch 016 - train 0.59577 | val 1.49537
  Classification -> best τ=0.405 (val F1=0.1898)
  Directional -> Accuracy: 0.5867, MCC: 0.1155, F1: 0.6737

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.60793 | val 1.72153
  Epoch 016 - train 0.56861 | val 2.69025
  Classification -> best τ=0.400 (val F1=0.2166)
  Directional -> Accuracy: 0.5385, MCC: 0.2138, F1: 0.4231

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.60000 | val 0.72648
  Epoch 020 - train 0.52501 | val 1.08829
  Epoch 023 - train 0.54071 | val 0.88966
  Classification -> best τ=0.440 (val F1=0.2613)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.58160 | val 0.78805
  Epoch 020 - train 0.52907 | val 1.40555
  Epoch 023 - train 0.46557 | val 3.21280
  Classification -> best τ=0.375 (val F1=0.2845)
  Directional -> Accuracy: 0.5106, MCC: 0.1957, F1: 0.4103

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.61695 | val 0.70575
  Epoch 017 - train 0.57773 | val 0.86710
  Classification -> best τ=0.560 (val F1=0.1895)
  Directional -> Accuracy: 0.5909, MCC: 0.1978, F1: 0.4906

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.61349 | val 0.74672
  Epoch 016 - train 0.56926 | val 0.91798
  Classification -> best τ=0.610 (val F1=0.3282)
  Directional -> Accuracy: 0.5345, MCC: 0.0951, F1: 0.5263

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.61086 | val 0.96793
  Epoch 018 - train 0.52868 | val 1.01448
  Classification -> best τ=0.480 (val F1=0.1291)
  Directional -> Accuracy: 0.5231, MCC: 0.0669, F1: 0.5867

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.60743 | val 0.67587
  Epoch 020 - train 0.48817 | val 1.00653
  Classification -> best τ=0.530 (val F1=0.5052)
  Directional -> Accuracy: 0.4464, MCC: -0.0373, F1: 0.1622

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.61261 | val 0.73261
  Epoch 019 - train 0.55312 | val 0.83066
  Classification -> best τ=0.455 (val F1=0.2935)
  Directional -> Accuracy: 0.5217, MCC: 0.1433, F1: 0.6071

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.62147 | val 0.69367
  Epoch 016 - train 0.56982 | val 0.67931
  Classification -> best τ=0.565 (val F1=0.1291)
  Directional -> Accuracy: 0.5476, MCC: -0.1353, F1: 0.7077

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.59140 | val 0.92733
  Epoch 016 - train 0.53618 | val 1.41233
  Classification -> best τ=0.510 (val F1=0.2940)
  Directional -> Accuracy: 0.4561, MCC: 0.1181, F1: 0.0606

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.63289 | val 0.65420
  Epoch 020 - train 0.54008 | val 1.14354
  Epoch 030 - train 0.46577 | val 1.31780
  Epoch 031 - train 0.41777 | val 1.42854
  Classification -> best τ=0.675 (val F1=0.4114)
  Directional -> Accuracy: 0.5366, MCC: 0.0528, F1: 0.6122

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.60287 | val 0.83873
  Epoch 016 - train 0.52292 | val 0.86908
  Classification -> best τ=0.575 (val F1=0.2814)
  Directional -> Accuracy: 0.4884, MCC: -0.0353, F1: 0.3529

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.62066 | val 0.71320
  Epoch 016 - train 0.57974 | val 0.70851
  Classification -> best τ=0.505 (val F1=0.0943)
  Directional -> Accuracy: 0.4884, MCC: -0.1381, F1: 0.6452

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.57585 | val 1.21970
  Epoch 018 - train 0.48597 | val 2.17866
  Classification -> best τ=0.450 (val F1=0.2645)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.58133 | val 0.69571
  Epoch 018 - train 0.54064 | val 1.08475
  Classification -> best τ=0.395 (val F1=0.3396)
  Directional -> Accuracy: 0.5342, MCC: 0.1050, F1: 0.5000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.62778 | val 0.82560
  Epoch 016 - train 0.52080 | val 0.88582
  Classification -> best τ=0.465 (val F1=0.4658)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.60413 | val 0.86251
  Epoch 016 - train 0.52324 | val 0.90906
  Classification -> best τ=0.585 (val F1=0.3221)
  Directional -> Accuracy: 0.5682, MCC: 0.1300, F1: 0.4242

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.60666 | val 0.86852
  Epoch 016 - train 0.57689 | val 0.91347
  Classification -> best τ=0.400 (val F1=0.4292)
  Directional -> Accuracy: 0.6212, MCC: 0.2145, F1: 0.6835

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.57623 | val 0.85117
  Epoch 016 - train 0.52502 | val 1.11088
  Classification -> best τ=0.420 (val F1=0.3343)
  Directional -> Accuracy: 0.6667, MCC: 0.3708, F1: 0.6111

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.60474 | val 0.71977
  Epoch 018 - train 0.49889 | val 0.81175
  Classification -> best τ=0.405 (val F1=0.2946)
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.6341

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.56515 | val 0.79888
  Epoch 017 - train 0.48057 | val 1.04058
  Classification -> best τ=0.570 (val F1=0.2185)
  Directional -> Accuracy: 0.3913, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.60510 | val 0.66388
  Epoch 020 - train 0.50494 | val 0.82784
  Epoch 030 - train 0.41901 | val 1.05940
  Epoch 031 - train 0.44203 | val 0.89251
  Classification -> best τ=0.290 (val F1=0.3682)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.49386 | val 0.90040
  Epoch 016 - train 0.49955 | val 1.14674
  Classification -> best τ=0.500 (val F1=0.0585)
  Directional -> Accuracy: 0.4865, MCC: 0.0171, F1: 0.3448

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.59788 | val 1.20386
  Epoch 017 - train 0.53370 | val 2.20623
  Classification -> best τ=0.370 (val F1=0.3844)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.58615 | val 0.68829
  Epoch 020 - train 0.51988 | val 0.86847
  Classification -> best τ=0.480 (val F1=0.3560)
  Directional -> Accuracy: 0.4565, MCC: -0.0851, F1: 0.1379

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.61896 | val 0.75668
  Epoch 016 - train 0.57355 | val 0.74669
  Classification -> best τ=0.575 (val F1=0.0685)
  Directional -> Accuracy: 0.4419, MCC: -0.0375, F1: 0.1429

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.56440 | val 0.69835
  Epoch 020 - train 0.50384 | val 0.64536
  Epoch 030 - train 0.39951 | val 0.58148
  Epoch 036 - train 0.34579 | val 0.85998
  Classification -> best τ=0.400 (val F1=0.5514)
  Directional -> Accuracy: 0.3878, MCC: -0.0861, F1: 0.5161

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.60124 | val 1.22650
  Epoch 017 - train 0.55278 | val 1.26321
  Classification -> best τ=0.435 (val F1=0.0231)
  Directional -> Accuracy: 0.5357, MCC: 0.0827, F1: 0.5185

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.59719 | val 1.35149
  Epoch 017 - train 0.53309 | val 2.33679
  Classification -> best τ=0.630 (val F1=0.2157)
  Directional -> Accuracy: 0.5714, MCC: 0.1616, F1: 0.3333

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.61696 | val 1.30433
  Epoch 016 - train 0.55001 | val 1.76973
  Classification -> best τ=0.400 (val F1=0.2004)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.56894 | val 0.77255
  Epoch 020 - train 0.50675 | val 0.89097
  Epoch 021 - train 0.50081 | val 0.93917
  Classification -> best τ=0.515 (val F1=0.1005)
  Directional -> Accuracy: 0.5179, MCC: 0.0187, F1: 0.6301

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.63214 | val 0.92654

[I 2026-02-25 04:02:46,240] Trial 206 finished with value: 0.24593372274019287 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.5, 'batch_size': 64, 'learning_rate': 0.00690801174803241, 'weight_decay': 0.0002905677750486412, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 0.28259852249018924, 'early_stopping_min_delta': 0.0031397420585494197}. Best is trial 200 with value: 0.303360648585588.

  Epoch 016 - train 0.56349 | val 1.17682
  Classification -> best τ=0.480 (val F1=0.1734)
  Directional -> Accuracy: 0.4754, MCC: -0.0732, F1: 0.3333

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.24593372274019287
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.60453 | val 0.73197
  Epoch 020 - train 0.57528 | val 0.90573
  Epoch 023 - train 0.53071 | val 0.95676
  Classification -> best τ=0.635 (val F1=0.2919)
  Directional -> Accuracy: 0.5132, MCC: 0.0237, F1: 0.4789

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.57005 | val 0.68791
  Epoch 017 - train 0.53215 | val 0.72447
  Classification -> best τ=0.480 (val F1=0.2496)
  Directional -> Accuracy: 0.5556, MCC: -0.0159, F1: 0.6970

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.63141 | val 0.80067
  Epoch 020 - train 0.61386 | val 1.02532
  Classification -> best τ=0.505 (val F1=0.2398)
  Directional -> Accuracy: 0.4468, MCC: -0.1039, F1: 0.0714

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.66763 | val 0.85853
  Epoch 018 - train 0.60583 | val 1.50738
  Classification -> best τ=0.490 (val F1=0.1767)
  Directional -> Accuracy: 0.5467, MCC: 0.0643, F1: 0.6304

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.63812 | val 0.67365
  Epoch 020 - train 0.47451 | val 0.76044
  Classification -> best τ=0.570 (val F1=0.4041)
  Directional -> Accuracy: 0.3725, MCC: -0.2659, F1: 0.4286

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.56514 | val 0.71098
  Epoch 016 - train 0.53065 | val 1.02789
  Classification -> best τ=0.440 (val F1=0.2928)
  Directional -> Accuracy: 0.4894, MCC: 0.0000, F1: 0.6571

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.64156 | val 0.77623
  Epoch 016 - train 0.61358 | val 1.12197
  Classification -> best τ=0.440 (val F1=0.1568)
  Directional -> Accuracy: 0.4638, MCC: 0.0887, F1: 0.5747

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.58868 | val 0.82398
  Epoch 019 - train 0.46916 | val 1.09442
  Classification -> best τ=0.335 (val F1=0.2962)
  Directional -> Accuracy: 0.4419, MCC: -0.1656, F1: 0.2941

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.60442 | val 0.71053
  Epoch 020 - train 0.47771 | val 0.86427
  Classification -> best τ=0.465 (val F1=0.1505)
  Directional -> Accuracy: 0.5918, MCC: 0.1537, F1: 0.3750

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.61117 | val 0.71004
  Epoch 020 - train 0.49526 | val 0.97346
  Epoch 023 - train 0.46698 | val 1.00981
  Classification -> best τ=0.655 (val F1=0.2220)
  Directional -> Accuracy: 0.5286, MCC: 0.0577, F1: 0.4923

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.61086 | val 0.84590
  Epoch 017 - train 0.54033 | val 1.03167
  Classification -> best τ=0.455 (val F1=0.3062)
  Directional -> Accuracy: 0.6400, MCC: 0.3215, F1: 0.4000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.55438 | val 0.93779
  Epoch 017 - train 0.52577 | val 0.88245
  Classification -> best τ=0.535 (val F1=0.2453)
  Directional -> Accuracy: 0.5690, MCC: 0.2265, F1: 0.2857

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.55606 | val 1.01677
  Epoch 017 - train 0.54592 | val 1.26744
  Classification -> best τ=0.400 (val F1=0.2731)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.61789 | val 0.68096
  Epoch 020 - train 0.55584 | val 0.83578
  Classification -> best τ=0.455 (val F1=0.3141)
  Directional -> Accuracy: 0.5500, MCC: 0.1558, F1: 0.6747

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.59173 | val 0.92274
  Epoch 020 - train 0.52086 | val 1.28061
  Epoch 022 - train 0.49244 | val 1.38320
  Classification -> best τ=0.660 (val F1=0.2673)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.62596 | val 0.70633
  Epoch 018 - train 0.60308 | val 0.82403
  Classification -> best τ=0.495 (val F1=0.2962)
  Directional -> Accuracy: 0.6522, MCC: 0.3257, F1: 0.7391

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.61773 | val 0.96338
  Epoch 018 - train 0.55550 | val 1.66084
  Classification -> best τ=0.470 (val F1=0.1878)
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.59743 | val 1.03041
  Epoch 017 - train 0.60343 | val 1.11985
  Classification -> best τ=0.510 (val F1=0.1116)
  Directional -> Accuracy: 0.5333, MCC: 0.0439, F1: 0.5977

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.64425 | val 1.32403
  Epoch 016 - train 0.59864 | val 2.64568
  Classification -> best τ=0.555 (val F1=0.2535)
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.64306 | val 0.69133
  Epoch 020 - train 0.57008 | val 0.92381
  Epoch 021 - train 0.55032 | val 0.79053
  Classification -> best τ=0.405 (val F1=0.2205)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.60945 | val 0.74647
  Epoch 016 - train 0.57100 | val 0.90430
  Classification -> best τ=0.495 (val F1=0.2267)
  Directional -> Accuracy: 0.6170, MCC: 0.0508, F1: 0.7568

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.61522 | val 0.80300
  Epoch 016 - train 0.57598 | val 0.94462
  Classification -> best τ=0.525 (val F1=0.1878)
  Directional -> Accuracy: 0.5606, MCC: 0.1319, F1: 0.4528

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.64433 | val 0.75921
  Epoch 017 - train 0.57660 | val 0.87694
  Classification -> best τ=0.555 (val F1=0.3031)
  Directional -> Accuracy: 0.5862, MCC: 0.1649, F1: 0.6250

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.60144 | val 0.74994
  Epoch 019 - train 0.55267 | val 1.41797
  Classification -> best τ=0.455 (val F1=0.0594)
  Directional -> Accuracy: 0.4769, MCC: 0.0000, F1: 0.6458

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.60569 | val 0.67575
  Epoch 020 - train 0.50658 | val 0.76804
  Epoch 024 - train 0.46461 | val 0.99933
  Classification -> best τ=0.640 (val F1=0.3656)
  Directional -> Accuracy: 0.4643, MCC: 0.0136, F1: 0.2105

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.65144 | val 0.78411
  Epoch 016 - train 0.59178 | val 0.77366
  Classification -> best τ=0.450 (val F1=0.2035)
  Directional -> Accuracy: 0.5870, MCC: 0.2861, F1: 0.6545

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.63666 | val 0.71121
  Epoch 016 - train 0.60154 | val 0.71747
  Classification -> best τ=0.595 (val F1=0.2107)
  Directional -> Accuracy: 0.5238, MCC: -0.0525, F1: 0.6552

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.62034 | val 0.82922
  Epoch 018 - train 0.53021 | val 1.25570
  Classification -> best τ=0.435 (val F1=0.2359)
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.60939 | val 0.66311
  Epoch 020 - train 0.51649 | val 0.83846
  Epoch 030 - train 0.49254 | val 2.64320
  Epoch 033 - train 0.40320 | val 1.43529
  Classification -> best τ=0.490 (val F1=0.4345)
  Directional -> Accuracy: 0.4878, MCC: -0.2104, F1: 0.6557

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.57804 | val 0.85435
  Epoch 017 - train 0.54669 | val 1.38017
  Classification -> best τ=0.565 (val F1=0.2814)
  Directional -> Accuracy: 0.5581, MCC: 0.1169, F1: 0.5581

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.62831 | val 0.69940
  Epoch 017 - train 0.58463 | val 0.83515
  Classification -> best τ=0.535 (val F1=0.2517)
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.55922 | val 0.80148
  Epoch 020 - train 0.47110 | val 1.84005
  Epoch 021 - train 0.48271 | val 1.99489
  Classification -> best τ=0.595 (val F1=0.2969)
  Directional -> Accuracy: 0.5400, MCC: 0.1170, F1: 0.4651

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.60798 | val 0.73673
  Epoch 020 - train 0.54093 | val 0.75561
  Epoch 023 - train 0.52588 | val 0.84375
  Classification -> best τ=0.205 (val F1=0.3520)
  Directional -> Accuracy: 0.5616, MCC: 0.1446, F1: 0.5556

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.60196 | val 0.90300
  Epoch 018 - train 0.52094 | val 1.29909
  Classification -> best τ=0.465 (val F1=0.1693)
  Directional -> Accuracy: 0.4595, MCC: -0.0774, F1: 0.5000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.62774 | val 0.87900
  Epoch 017 - train 0.54526 | val 1.06775
  Classification -> best τ=0.410 (val F1=0.3121)
  Directional -> Accuracy: 0.5455, MCC: 0.1026, F1: 0.1667

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.63743 | val 0.70829
  Epoch 018 - train 0.54886 | val 0.96769
  Classification -> best τ=0.460 (val F1=0.3899)
  Directional -> Accuracy: 0.6061, MCC: 0.2101, F1: 0.6389

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.59395 | val 0.83399
  Epoch 016 - train 0.48611 | val 0.82450
  Classification -> best τ=0.435 (val F1=0.2819)
  Directional -> Accuracy: 0.7381, MCC: 0.4767, F1: 0.7442

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.60399 | val 0.77030
  Epoch 020 - train 0.52864 | val 0.87543
  Epoch 021 - train 0.50201 | val 0.86699
  Classification -> best τ=0.430 (val F1=0.2305)
  Directional -> Accuracy: 0.4643, MCC: -0.0138, F1: 0.6250

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.58091 | val 0.80142
  Epoch 018 - train 0.48385 | val 0.94406
  Classification -> best τ=0.445 (val F1=0.3105)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.60262 | val 0.74280
  Epoch 020 - train 0.48569 | val 0.71268
  Epoch 023 - train 0.44507 | val 0.84459
  Classification -> best τ=0.455 (val F1=0.3125)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.58277 | val 0.74023
  Epoch 018 - train 0.50002 | val 0.88552
  Classification -> best τ=0.535 (val F1=0.0872)
  Directional -> Accuracy: 0.4595, MCC: -0.0427, F1: 0.2857

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.60101 | val 0.92779
  Epoch 017 - train 0.57006 | val 1.22096
  Classification -> best τ=0.435 (val F1=0.3466)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.62322 | val 0.69350
  Epoch 017 - train 0.57015 | val 0.75142
  Classification -> best τ=0.435 (val F1=0.3861)
  Directional -> Accuracy: 0.4565, MCC: -0.0996, F1: 0.0741

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.58519 | val 0.68632
  Epoch 020 - train 0.51264 | val 0.84543
  Epoch 021 - train 0.56148 | val 0.77258
  Classification -> best τ=0.460 (val F1=0.3371)
  Directional -> Accuracy: 0.5116, MCC: -0.0464, F1: 0.6316

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.61013 | val 0.63727
  Epoch 020 - train 0.50245 | val 0.58203
  Epoch 030 - train 0.40883 | val 0.68342
  Epoch 034 - train 0.36775 | val 0.66374
  Classification -> best τ=0.545 (val F1=0.4606)
  Directional -> Accuracy: 0.3673, MCC: -0.1468, F1: 0.5079

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.65004 | val 0.70215
  Epoch 020 - train 0.57247 | val 0.96970
  Epoch 023 - train 0.54526 | val 1.04549
  Classification -> best τ=0.565 (val F1=0.1676)
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.60426 | val 0.90153
  Epoch 020 - train 0.53473 | val 1.54837
  Epoch 022 - train 0.49148 | val 1.50042
  Classification -> best τ=0.510 (val F1=0.3444)
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.61294 | val 1.05713
  Epoch 017 - train 0.57630 | val 2.72232
  Classification -> best τ=0.390 (val F1=0.2663)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.62461 | val 0.79989
  Epoch 020 - train 0.56583 | val 0.84250
  Epoch 022 - train 0.55050 | val 0.86899
  Classification -> best τ=0.480 (val F1=0.2930)
  Directional -> Accuracy: 0.4286, MCC: -0.1443, F1: 0.4483

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.62014 | val 0.84383

[I 2026-02-25 04:04:44,022] Trial 207 finished with value: 0.2632254530452341 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.5, 'batch_size': 64, 'learning_rate': 0.00485770221739089, 'weight_decay': 0.00012801946831709278, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 0.10975393476285829, 'early_stopping_min_delta': 0.003655380843694842}. Best is trial 200 with value: 0.303360648585588.

  Epoch 018 - train 0.54133 | val 1.44306
  Classification -> best τ=0.435 (val F1=0.1007)
  Directional -> Accuracy: 0.4262, MCC: -0.1412, F1: 0.4615

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2632254530452341
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.63443 | val 0.70128
  Epoch 020 - train 0.61169 | val 0.71734
  Epoch 030 - train 0.59169 | val 0.86141
  Epoch 040 - train 0.53224 | val 0.84888
  Classification -> best τ=0.450 (val F1=0.3286)
  Directional -> Accuracy: 0.4605, MCC: 0.1039, F1: 0.6239

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.66637 | val 0.68628
  Epoch 020 - train 0.59606 | val 0.69736
  Epoch 023 - train 0.54407 | val 0.71342
  Classification -> best τ=0.465 (val F1=0.2431)
  Directional -> Accuracy: 0.6222, MCC: 0.1909, F1: 0.7302

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.69056 | val 0.72026
  Epoch 018 - train 0.62413 | val 0.95097
  Classification -> best τ=0.565 (val F1=0.2449)
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.65728 | val 0.70620
  Epoch 016 - train 0.64625 | val 0.76356
  Classification -> best τ=0.490 (val F1=0.1210)
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.64590 | val 0.64616
  Epoch 020 - train 0.59432 | val 0.76005
  Epoch 028 - train 0.55369 | val 0.69165
  Classification -> best τ=0.540 (val F1=0.3665)
  Directional -> Accuracy: 0.3725, MCC: -0.3378, F1: 0.5152

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.62790 | val 0.70714
  Epoch 020 - train 0.55898 | val 0.96709
  Epoch 024 - train 0.55755 | val 0.79300
  Classification -> best τ=0.520 (val F1=0.1195)
  Directional -> Accuracy: 0.4255, MCC: -0.1969, F1: 0.1818

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.69409 | val 0.68490
  Epoch 020 - train 0.67342 | val 0.70767
  Epoch 028 - train 0.63879 | val 0.70080
  Classification -> best τ=0.590 (val F1=0.2605)
  Directional -> Accuracy: 0.4348, MCC: -0.1192, F1: 0.4000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.60679 | val 0.71857
  Epoch 019 - train 0.60938 | val 0.96798
  Classification -> best τ=0.375 (val F1=0.0289)
  Directional -> Accuracy: 0.4884, MCC: -0.1323, F1: 0.2143

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.60957 | val 0.68567
  Epoch 016 - train 0.60252 | val 0.79472
  Classification -> best τ=0.440 (val F1=0.2408)
  Directional -> Accuracy: 0.5102, MCC: 0.1103, F1: 0.6129

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.63530 | val 0.71016
  Epoch 017 - train 0.59502 | val 0.81966
  Classification -> best τ=0.460 (val F1=0.1816)
  Directional -> Accuracy: 0.4143, MCC: -0.1154, F1: 0.5060

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.63312 | val 0.79134
  Epoch 018 - train 0.59597 | val 1.05159
  Classification -> best τ=0.445 (val F1=0.2450)
  Directional -> Accuracy: 0.6400, MCC: 0.2848, F1: 0.4706

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.64261 | val 0.80939
  Epoch 016 - train 0.60940 | val 1.04029
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.63446 | val 0.76193
  Epoch 016 - train 0.63112 | val 0.99938
  Classification -> best τ=0.525 (val F1=0.2277)
  Directional -> Accuracy: 0.4286, MCC: -0.1946, F1: 0.2500

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.68627 | val 0.63932
  Epoch 020 - train 0.63413 | val 0.91227
  Epoch 030 - train 0.61380 | val 0.87303
  Classification -> best τ=0.505 (val F1=0.3558)
  Directional -> Accuracy: 0.5333, MCC: 0.0727, F1: 0.6111

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.64389 | val 0.80164
  Epoch 016 - train 0.56836 | val 0.93905
  Classification -> best τ=0.495 (val F1=0.3118)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.64273 | val 0.64063
  Epoch 020 - train 0.60037 | val 0.76999
  Epoch 025 - train 0.58059 | val 0.83645
  Classification -> best τ=0.580 (val F1=0.3288)
  Directional -> Accuracy: 0.5652, MCC: 0.1730, F1: 0.4828

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.66708 | val 0.90807
  Epoch 016 - train 0.62224 | val 1.38437
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.67517 | val 0.87403
  Epoch 017 - train 0.65029 | val 1.02599
  Classification -> best τ=0.315 (val F1=0.0784)
  Directional -> Accuracy: 0.6000, MCC: 0.0000, F1: 0.7500

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.68284 | val 1.10315
  Epoch 016 - train 0.64199 | val 1.39076
  Classification -> best τ=0.445 (val F1=0.3140)
  Directional -> Accuracy: 0.5692, MCC: 0.0760, F1: 0.6667

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.67157 | val 0.67601
  Epoch 019 - train 0.60512 | val 0.81600
  Classification -> best τ=0.520 (val F1=0.3150)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.64803 | val 0.67509
  Epoch 020 - train 0.59721 | val 1.00829
  Epoch 025 - train 0.52856 | val 1.36453
  Classification -> best τ=0.490 (val F1=0.3296)
  Directional -> Accuracy: 0.4255, MCC: 0.1661, F1: 0.1290

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.68986 | val 0.74450
  Epoch 017 - train 0.61609 | val 0.79904
  Classification -> best τ=0.565 (val F1=0.2674)
  Directional -> Accuracy: 0.5303, MCC: 0.0786, F1: 0.3111

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.69772 | val 0.82693
  Epoch 017 - train 0.64520 | val 0.83691
  Classification -> best τ=0.680 (val F1=0.3282)
  Directional -> Accuracy: 0.5172, MCC: 0.0762, F1: 0.4815

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.66291 | val 0.69271
  Epoch 020 - train 0.59796 | val 0.72220
  Epoch 022 - train 0.57707 | val 0.97238
  Classification -> best τ=0.430 (val F1=0.3365)
  Directional -> Accuracy: 0.4769, MCC: 0.0000, F1: 0.6458

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.67394 | val 0.82421
  Epoch 020 - train 0.61163 | val 0.71907
  Epoch 028 - train 0.53192 | val 0.79465
  Classification -> best τ=0.350 (val F1=0.4352)
  Directional -> Accuracy: 0.6429, MCC: 0.3123, F1: 0.7500

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.60835 | val 0.80936
  Epoch 016 - train 0.63139 | val 1.00075
  Classification -> best τ=0.440 (val F1=0.2935)
  Directional -> Accuracy: 0.4565, MCC: 0.1307, F1: 0.6154

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.67750 | val 0.69571
  Epoch 018 - train 0.59668 | val 0.71186
  Classification -> best τ=0.510 (val F1=0.2107)
  Directional -> Accuracy: 0.5238, MCC: -0.1171, F1: 0.6774

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.66406 | val 0.69465
  Epoch 016 - train 0.60874 | val 0.72977
  Classification -> best τ=0.500 (val F1=0.2648)
  Directional -> Accuracy: 0.5439, MCC: 0.3032, F1: 0.3158

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.68395 | val 0.67407
  Epoch 020 - train 0.60756 | val 0.80037
  Epoch 030 - train 0.63202 | val 1.29488
  Epoch 037 - train 0.52677 | val 1.29738
  Classification -> best τ=0.335 (val F1=0.3518)
  Directional -> Accuracy: 0.5366, MCC: 0.0166, F1: 0.6885

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.68258 | val 0.72202
  Epoch 016 - train 0.60301 | val 0.98072
  Classification -> best τ=0.530 (val F1=0.3244)
  Directional -> Accuracy: 0.4419, MCC: -0.1436, F1: 0.5862

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.69133 | val 0.65131
  Epoch 020 - train 0.64457 | val 0.73301
  Epoch 024 - train 0.64670 | val 0.68114
  Classification -> best τ=0.450 (val F1=0.2517)
  Directional -> Accuracy: 0.6047, MCC: 0.2203, F1: 0.7119

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.65264 | val 0.72602
  Epoch 020 - train 0.56988 | val 1.15707
  Epoch 021 - train 0.53632 | val 1.28947
  Classification -> best τ=0.325 (val F1=0.2932)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.65424 | val 0.77425
  Epoch 017 - train 0.65429 | val 0.68083
  Classification -> best τ=0.445 (val F1=0.3273)
  Directional -> Accuracy: 0.5342, MCC: 0.1465, F1: 0.4333

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.63799 | val 0.89167
  Epoch 019 - train 0.59805 | val 0.94052
  Classification -> best τ=0.490 (val F1=0.0559)
  Directional -> Accuracy: 0.4054, MCC: -0.2479, F1: 0.5600

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.65647 | val 0.77227
  Epoch 017 - train 0.62535 | val 0.98385
  Classification -> best τ=0.500 (val F1=0.2506)
  Directional -> Accuracy: 0.4318, MCC: -0.3022, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.67727 | val 0.71505
  Epoch 016 - train 0.67294 | val 0.77679
  Classification -> best τ=0.475 (val F1=0.2820)
  Directional -> Accuracy: 0.5606, MCC: 0.0881, F1: 0.6329

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.66582 | val 0.70342
  Epoch 016 - train 0.61608 | val 0.85375
  Classification -> best τ=0.515 (val F1=0.3300)
  Directional -> Accuracy: 0.5238, MCC: 0.1469, F1: 0.2308

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.66683 | val 0.71694
  Epoch 020 - train 0.59465 | val 0.71509
  Epoch 024 - train 0.57345 | val 0.67104
  Classification -> best τ=0.545 (val F1=0.2382)
  Directional -> Accuracy: 0.4464, MCC: -0.0925, F1: 0.4918

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.58534 | val 0.81985
  Epoch 016 - train 0.59264 | val 1.15264
  Classification -> best τ=0.500 (val F1=0.2441)
  Directional -> Accuracy: 0.4348, MCC: -0.0309, F1: 0.3500

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.73323 | val 0.65324
  Epoch 020 - train 0.65086 | val 0.66490
  Epoch 030 - train 0.63785 | val 0.65070
  Epoch 040 - train 0.49113 | val 0.63705
  Epoch 047 - train 0.51979 | val 0.62833
  Classification -> best τ=0.310 (val F1=0.5617)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.81081 | val 0.81652
  Epoch 020 - train 0.60094 | val 0.74018
  Classification -> best τ=0.475 (val F1=0.3699)
  Directional -> Accuracy: 0.5135, MCC: 0.0890, F1: 0.3571

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.64043 | val 0.74551
  Epoch 018 - train 0.61585 | val 1.08688
  Classification -> best τ=0.445 (val F1=0.3397)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.69960 | val 0.70875
  Epoch 020 - train 0.58082 | val 0.70644
  Epoch 030 - train 0.55985 | val 0.78476
  Epoch 031 - train 0.60151 | val 0.75261
  Classification -> best τ=0.460 (val F1=0.3952)
  Directional -> Accuracy: 0.5000, MCC: -0.0210, F1: 0.5965

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.64787 | val 0.73779
  Epoch 020 - train 0.58181 | val 0.78516
  Epoch 022 - train 0.59805 | val 0.79870
  Classification -> best τ=0.535 (val F1=0.4625)
  Directional -> Accuracy: 0.6047, MCC: 0.1753, F1: 0.7018

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.65360 | val 0.60288
  Epoch 020 - train 0.59622 | val 0.73199
  Epoch 024 - train 0.58577 | val 0.74446
  Classification -> best τ=0.655 (val F1=0.6292)
  Directional -> Accuracy: 0.3878, MCC: -0.0861, F1: 0.5161

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.68250 | val 0.86313
  Epoch 016 - train 0.64772 | val 1.16175
  Classification -> best τ=0.490 (val F1=0.2610)
  Directional -> Accuracy: 0.4464, MCC: -0.2436, F1: 0.6076

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.66025 | val 0.85344
  Epoch 016 - train 0.61938 | val 1.03236
  Classification -> best τ=0.450 (val F1=0.2230)
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.64656 | val 0.85713
  Epoch 018 - train 0.62420 | val 2.02064
  Classification -> best τ=0.630 (val F1=0.1626)
  Directional -> Accuracy: 0.5741, MCC: 0.2320, F1: 0.3784

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.68020 | val 0.79741
  Epoch 017 - train 0.58997 | val 0.91699
  Classification -> best τ=0.470 (val F1=0.1091)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.66812 | val 0.76882

[I 2026-02-25 04:06:52,013] Trial 208 finished with value: 0.26781329927944575 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 64, 'learning_rate': 0.0035729065175653437, 'weight_decay': 0.00020303718562768736, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 0.6597376197203754, 'early_stopping_min_delta': 0.004177718809673088}. Best is trial 200 with value: 0.303360648585588.

  Epoch 017 - train 0.62726 | val 0.75175
  Classification -> best τ=0.475 (val F1=0.1498)
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.26781329927944575
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.63106 | val 0.77678
  Epoch 020 - train 0.61244 | val 1.52032
  Epoch 021 - train 0.59722 | val 1.03216
  Classification -> best τ=0.375 (val F1=0.1635)
  Directional -> Accuracy: 0.5658, MCC: 0.1620, F1: 0.5926

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.58281 | val 0.70035
  Epoch 020 - train 0.49668 | val 0.68566
  Classification -> best τ=0.465 (val F1=0.1700)
  Directional -> Accuracy: 0.4444, MCC: -0.0763, F1: 0.4186

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.63318 | val 0.77267
  Epoch 016 - train 0.59853 | val 0.88652
  Classification -> best τ=0.485 (val F1=0.2559)
  Directional -> Accuracy: 0.4255, MCC: -0.1737, F1: 0.5091

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.67345 | val 0.77880
  Epoch 018 - train 0.66491 | val 0.73912
  Classification -> best τ=0.495 (val F1=0.1283)
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.60200 | val 0.77383
  Epoch 020 - train 0.51149 | val 0.81849
  Epoch 028 - train 0.46592 | val 0.67642
  Classification -> best τ=0.570 (val F1=0.4380)
  Directional -> Accuracy: 0.4314, MCC: -0.1278, F1: 0.3830

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.63667 | val 0.70035
  Epoch 016 - train 0.56694 | val 0.74819
  Classification -> best τ=0.545 (val F1=0.2357)
  Directional -> Accuracy: 0.5957, MCC: 0.2361, F1: 0.3871

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.66076 | val 0.71016
  Epoch 018 - train 0.63452 | val 0.81622
  Classification -> best τ=0.510 (val F1=0.2542)
  Directional -> Accuracy: 0.5217, MCC: 0.0699, F1: 0.5075

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.52585 | val 0.70506
  Epoch 020 - train 0.53965 | val 0.82868
  Epoch 021 - train 0.45837 | val 0.97202
  Classification -> best τ=0.400 (val F1=0.2218)
  Directional -> Accuracy: 0.5581, MCC: 0.0993, F1: 0.4865

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.60246 | val 0.68805
  Epoch 020 - train 0.51233 | val 0.78606
  Epoch 024 - train 0.51993 | val 0.97754
  Classification -> best τ=0.415 (val F1=0.1978)
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.64162 | val 0.73263
  Epoch 016 - train 0.62217 | val 0.89829
  Classification -> best τ=0.535 (val F1=0.0585)
  Directional -> Accuracy: 0.5286, MCC: -0.0302, F1: 0.2667

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.62505 | val 0.68829
  Epoch 020 - train 0.63531 | val 0.94636
  Epoch 024 - train 0.65574 | val 0.66352
  Classification -> best τ=0.435 (val F1=0.4082)
  Directional -> Accuracy: 0.6000, MCC: 0.1847, F1: 0.5000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.61566 | val 0.78435
  Epoch 018 - train 0.56269 | val 0.71404
  Classification -> best τ=0.495 (val F1=0.2242)
  Directional -> Accuracy: 0.4310, MCC: -0.2000, F1: 0.1081

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.61051 | val 0.69720
  Epoch 020 - train 0.49608 | val 1.22442
  Classification -> best τ=0.485 (val F1=0.1927)
  Directional -> Accuracy: 0.4762, MCC: -0.0026, F1: 0.5600

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.64049 | val 0.68990
  Epoch 020 - train 0.58345 | val 0.68988
  Epoch 030 - train 0.57091 | val 0.65622
  Epoch 039 - train 0.49428 | val 0.69532
  Classification -> best τ=0.325 (val F1=0.3584)
  Directional -> Accuracy: 0.5667, MCC: 0.1789, F1: 0.6750

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.67388 | val 0.82122
  Epoch 016 - train 0.62148 | val 1.13657
  Classification -> best τ=0.520 (val F1=0.2467)
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.61774 | val 0.75232
  Epoch 018 - train 0.52516 | val 1.09545
  Classification -> best τ=0.520 (val F1=0.3044)
  Directional -> Accuracy: 0.5652, MCC: 0.1945, F1: 0.4444

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.61236 | val 1.09895
  Epoch 016 - train 0.58701 | val 1.85854
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.66462 | val 0.79838
  Epoch 017 - train 0.65031 | val 1.78443
  Classification -> best τ=0.470 (val F1=0.1733)
  Directional -> Accuracy: 0.5867, MCC: 0.0000, F1: 0.7304

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.65161 | val 0.74909
  Epoch 020 - train 0.57898 | val 1.01582
  Classification -> best τ=0.385 (val F1=0.2752)
  Directional -> Accuracy: 0.4923, MCC: 0.1307, F1: 0.3265

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.63897 | val 0.69196
  Epoch 020 - train 0.57406 | val 0.76233
  Epoch 026 - train 0.53836 | val 0.72636
  Classification -> best τ=0.405 (val F1=0.3293)
  Directional -> Accuracy: 0.5067, MCC: 0.2161, F1: 0.1778

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.64743 | val 0.72703
  Epoch 020 - train 0.57586 | val 0.70934
  Epoch 030 - train 0.58014 | val 1.03422
  Classification -> best τ=0.445 (val F1=0.4109)
  Directional -> Accuracy: 0.4468, MCC: -0.0843, F1: 0.4800

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.68449 | val 0.85826
  Epoch 016 - train 0.67390 | val 0.80546
  Classification -> best τ=0.565 (val F1=0.2086)
  Directional -> Accuracy: 0.4242, MCC: -0.1518, F1: 0.4062

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.64295 | val 0.83150
  Epoch 020 - train 0.55970 | val 1.17858
  Epoch 021 - train 0.55193 | val 0.97326
  Classification -> best τ=0.775 (val F1=0.2967)
  Directional -> Accuracy: 0.5000, MCC: 0.2369, F1: 0.2162

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.69584 | val 0.70090
  Epoch 020 - train 0.65663 | val 0.76074
  Epoch 030 - train 0.56249 | val 0.72137
  Classification -> best τ=0.550 (val F1=0.2390)
  Directional -> Accuracy: 0.5846, MCC: 0.1646, F1: 0.5424

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.65334 | val 0.65132
  Epoch 020 - train 0.60961 | val 0.67192
  Epoch 024 - train 0.55758 | val 0.66993
  Classification -> best τ=0.330 (val F1=0.4272)
  Directional -> Accuracy: 0.5357, MCC: 0.0393, F1: 0.6176

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.61012 | val 0.72600
  Epoch 016 - train 0.56275 | val 0.91563
  Classification -> best τ=0.470 (val F1=0.1310)
  Directional -> Accuracy: 0.5652, MCC: 0.1154, F1: 0.5000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.68136 | val 0.68472
  Epoch 016 - train 0.59801 | val 0.68795
  Classification -> best τ=0.565 (val F1=0.0574)
  Directional -> Accuracy: 0.5238, MCC: 0.0000, F1: 0.6154

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.68589 | val 0.74034
  Epoch 020 - train 0.61124 | val 0.87226
  Epoch 021 - train 0.58666 | val 0.82775
  Classification -> best τ=0.415 (val F1=0.2391)
  Directional -> Accuracy: 0.5088, MCC: 0.2428, F1: 0.2222

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.62216 | val 0.67205
  Epoch 020 - train 0.55630 | val 0.70469
  Epoch 028 - train 0.37739 | val 1.02322
  Classification -> best τ=0.400 (val F1=0.4109)
  Directional -> Accuracy: 0.5610, MCC: 0.1701, F1: 0.7097

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.59360 | val 0.82489
  Epoch 017 - train 0.56352 | val 1.21472
  Classification -> best τ=0.550 (val F1=0.2814)
  Directional -> Accuracy: 0.5349, MCC: 0.0783, F1: 0.5833

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.60733 | val 0.70906
  Epoch 020 - train 0.50673 | val 0.65620
  Epoch 030 - train 0.38185 | val 1.15757
  Epoch 032 - train 0.33837 | val 1.05365
  Classification -> best τ=0.370 (val F1=0.2517)
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.58702 | val 0.74709
  Epoch 019 - train 0.52172 | val 1.25222
  Classification -> best τ=0.385 (val F1=0.4158)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.67883 | val 0.67485
  Epoch 020 - train 0.66789 | val 0.77072
  Epoch 028 - train 0.59522 | val 0.90942
  Classification -> best τ=0.325 (val F1=0.3602)
  Directional -> Accuracy: 0.5205, MCC: 0.0723, F1: 0.4928

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.58387 | val 0.76180
  Epoch 016 - train 0.52974 | val 0.98865
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.64521 | val 0.69960
  Epoch 020 - train 0.62740 | val 0.93943
  Epoch 021 - train 0.61701 | val 1.03331
  Classification -> best τ=0.470 (val F1=0.1902)
  Directional -> Accuracy: 0.5455, MCC: 0.1668, F1: 0.6552

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.67471 | val 0.71345
  Epoch 019 - train 0.63491 | val 0.73860
  Classification -> best τ=0.460 (val F1=0.3287)
  Directional -> Accuracy: 0.4242, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.57384 | val 0.78156
  Epoch 017 - train 0.52856 | val 0.76890
  Classification -> best τ=0.490 (val F1=0.1690)
  Directional -> Accuracy: 0.7143, MCC: 0.4719, F1: 0.6667

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.60036 | val 0.68502
  Epoch 019 - train 0.53262 | val 0.82979
  Classification -> best τ=0.410 (val F1=0.2946)
  Directional -> Accuracy: 0.5179, MCC: 0.1149, F1: 0.6301

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.55679 | val 0.74350
  Epoch 019 - train 0.42542 | val 0.95687
  Classification -> best τ=0.560 (val F1=0.2254)
  Directional -> Accuracy: 0.3913, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.61719 | val 0.66140
  Epoch 020 - train 0.54320 | val 0.66864
  Epoch 023 - train 0.47259 | val 0.76553
  Classification -> best τ=0.430 (val F1=0.3300)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.60351 | val 0.79278
  Epoch 016 - train 0.52931 | val 1.14656
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.65569 | val 0.72298
  Epoch 017 - train 0.58474 | val 0.89502
  Classification -> best τ=0.480 (val F1=0.3339)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.56867 | val 0.70692
  Epoch 017 - train 0.51277 | val 0.75047
  Classification -> best τ=0.420 (val F1=0.4141)
  Directional -> Accuracy: 0.5217, MCC: 0.0229, F1: 0.6333

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.64003 | val 0.68028
  Epoch 020 - train 0.50778 | val 0.73550
  Epoch 027 - train 0.40067 | val 1.17486
  Classification -> best τ=0.405 (val F1=0.4330)
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.7164

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.60339 | val 0.68776
  Epoch 017 - train 0.57262 | val 0.70036
  Classification -> best τ=0.500 (val F1=0.5421)
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.65165 | val 1.28663
  Epoch 016 - train 0.61339 | val 2.26877
  Classification -> best τ=0.525 (val F1=0.1914)
  Directional -> Accuracy: 0.4286, MCC: -0.1247, F1: 0.2381

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.62394 | val 0.91482
  Epoch 017 - train 0.57914 | val 1.30428
  Classification -> best τ=0.495 (val F1=0.1635)
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.70556 | val 1.08182
  Epoch 020 - train 0.60101 | val 1.40406
  Classification -> best τ=0.455 (val F1=0.2365)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.64123 | val 0.73122
  Epoch 016 - train 0.58740 | val 0.88187
  Classification -> best τ=0.500 (val F1=0.0589)
  Directional -> Accuracy: 0.5179, MCC: 0.0069, F1: 0.6747

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.66406 | val 0.72755

[I 2026-02-25 04:08:17,962] Trial 209 finished with value: 0.2518043029570274 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.5, 'batch_size': 64, 'learning_rate': 0.006121420623750447, 'weight_decay': 0.00035727698139540625, 'lr_patience': 7, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 0.2528890790659038, 'early_stopping_min_delta': 0.003884531784398455}. Best is trial 200 with value: 0.303360648585588.

  Epoch 020 - train 0.62375 | val 0.86595
  Epoch 021 - train 0.62985 | val 0.89081
  Classification -> best τ=0.395 (val F1=0.3127)
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2518043029570274
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.58968 | val 0.77208
  Epoch 017 - train 0.52995 | val 1.69065
  Classification -> best τ=0.405 (val F1=0.2799)
  Directional -> Accuracy: 0.4474, MCC: 0.0000, F1: 0.6182

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.64393 | val 0.71860
  Epoch 017 - train 0.54303 | val 0.81999
  Classification -> best τ=0.430 (val F1=0.1260)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.64237 | val 0.71993
  Epoch 017 - train 0.57141 | val 0.99058
  Classification -> best τ=0.565 (val F1=0.2398)
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.64767 | val 0.88445
  Epoch 017 - train 0.63245 | val 0.79791
  Classification -> best τ=0.510 (val F1=0.1283)
  Directional -> Accuracy: 0.5333, MCC: 0.0469, F1: 0.5977

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.60170 | val 0.67009
  Epoch 020 - train 0.52093 | val 0.73141
  Epoch 023 - train 0.48034 | val 0.74268
  Classification -> best τ=0.570 (val F1=0.4041)
  Directional -> Accuracy: 0.4118, MCC: -0.1806, F1: 0.4444

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.56806 | val 0.75919
  Epoch 016 - train 0.53000 | val 1.09966
  Classification -> best τ=0.525 (val F1=0.3430)
  Directional -> Accuracy: 0.5319, MCC: 0.0609, F1: 0.4762

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.67664 | val 0.70003
  Epoch 020 - train 0.59679 | val 0.81340
  Epoch 021 - train 0.59763 | val 0.75858
  Classification -> best τ=0.365 (val F1=0.2847)
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.61239 | val 0.73454
  Epoch 020 - train 0.51006 | val 1.47223
  Classification -> best τ=0.390 (val F1=0.1214)
  Directional -> Accuracy: 0.4419, MCC: -0.0427, F1: 0.5200

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.58419 | val 0.74529
  Epoch 020 - train 0.44407 | val 1.16437
  Classification -> best τ=0.455 (val F1=0.3509)
  Directional -> Accuracy: 0.5714, MCC: 0.1005, F1: 0.2759

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.65705 | val 0.72548
  Epoch 019 - train 0.53172 | val 0.86230
  Classification -> best τ=0.570 (val F1=0.1593)
  Directional -> Accuracy: 0.6000, MCC: 0.1473, F1: 0.3913

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.62839 | val 1.09334
  Epoch 018 - train 0.55405 | val 2.99833
  Classification -> best τ=0.400 (val F1=0.1961)
  Directional -> Accuracy: 0.6000, MCC: 0.1847, F1: 0.5000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.59140 | val 0.80932
  Epoch 017 - train 0.52949 | val 1.05674
  Classification -> best τ=0.530 (val F1=0.1255)
  Directional -> Accuracy: 0.5345, MCC: 0.1132, F1: 0.2286

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.62041 | val 0.85456
  Epoch 016 - train 0.50847 | val 1.30182
  Classification -> best τ=0.420 (val F1=0.2876)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.64802 | val 0.65053
  Epoch 020 - train 0.59278 | val 1.31064
  Epoch 024 - train 0.55089 | val 1.32688
  Classification -> best τ=0.440 (val F1=0.3320)
  Directional -> Accuracy: 0.5667, MCC: 0.1961, F1: 0.6829

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.58514 | val 0.82838
  Epoch 019 - train 0.53255 | val 1.35047
  Classification -> best τ=0.550 (val F1=0.2673)
  Directional -> Accuracy: 0.5000, MCC: -0.0929, F1: 0.1333

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.62968 | val 0.71823
  Epoch 017 - train 0.55713 | val 0.83377
  Classification -> best τ=0.560 (val F1=0.2876)
  Directional -> Accuracy: 0.4928, MCC: -0.0093, F1: 0.4928

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.65518 | val 0.85120
  Epoch 020 - train 0.56923 | val 1.05840
  Epoch 021 - train 0.58125 | val 1.21073
  Classification -> best τ=0.690 (val F1=0.1842)
  Directional -> Accuracy: 0.3729, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.65152 | val 1.11138
  Epoch 016 - train 0.60035 | val 2.32972
  Classification -> best τ=0.455 (val F1=0.1217)
  Directional -> Accuracy: 0.6000, MCC: 0.0000, F1: 0.7500

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.62692 | val 0.98750
  Epoch 016 - train 0.59723 | val 1.85521
  Classification -> best τ=0.530 (val F1=0.3943)
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.61498 | val 0.74014
  Epoch 018 - train 0.56906 | val 1.01033
  Classification -> best τ=0.525 (val F1=0.2371)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.60940 | val 0.71254
  Epoch 020 - train 0.54175 | val 1.03324
  Epoch 023 - train 0.52796 | val 1.46976
  Classification -> best τ=0.420 (val F1=0.4492)
  Directional -> Accuracy: 0.4894, MCC: -0.0584, F1: 0.5714

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.63585 | val 0.79028
  Epoch 016 - train 0.60818 | val 0.83086
  Classification -> best τ=0.535 (val F1=0.2453)
  Directional -> Accuracy: 0.4848, MCC: -0.0312, F1: 0.4138

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.62326 | val 0.70664
  Epoch 016 - train 0.59465 | val 0.80913
  Classification -> best τ=0.505 (val F1=0.2379)
  Directional -> Accuracy: 0.5517, MCC: 0.0514, F1: 0.6486

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.63090 | val 0.81978
  Epoch 017 - train 0.56899 | val 1.31328
  Classification -> best τ=0.400 (val F1=0.1633)
  Directional -> Accuracy: 0.5077, MCC: 0.0402, F1: 0.5897

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.60507 | val 0.66308
  Epoch 020 - train 0.55166 | val 0.73344
  Epoch 026 - train 0.50459 | val 0.75783
  Classification -> best τ=0.500 (val F1=0.4719)
  Directional -> Accuracy: 0.4464, MCC: -0.0373, F1: 0.1622

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.64925 | val 0.84838
  Epoch 016 - train 0.56687 | val 1.11036
  Classification -> best τ=0.515 (val F1=0.2935)
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.63807 | val 0.72117
  Epoch 016 - train 0.59369 | val 0.68837
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.65077 | val 0.74479
  Epoch 017 - train 0.59225 | val 0.93061
  Classification -> best τ=0.330 (val F1=0.1939)
  Directional -> Accuracy: 0.5789, MCC: 0.2830, F1: 0.4545

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.59911 | val 0.68075
  Epoch 020 - train 0.51879 | val 1.04440
  Epoch 024 - train 0.47342 | val 1.17492
  Classification -> best τ=0.535 (val F1=0.4345)
  Directional -> Accuracy: 0.5610, MCC: 0.0980, F1: 0.6667

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.63373 | val 0.78814
  Epoch 016 - train 0.59241 | val 0.83258
  Classification -> best τ=0.580 (val F1=0.2814)
  Directional -> Accuracy: 0.4651, MCC: -0.0893, F1: 0.3030

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.65153 | val 0.79757
  Epoch 020 - train 0.49628 | val 0.98084
  Epoch 030 - train 0.43697 | val 0.78431
  Epoch 040 - train 0.34252 | val 1.00090
  Epoch 041 - train 0.33808 | val 1.27781
  Classification -> best τ=0.795 (val F1=0.2151)
  Directional -> Accuracy: 0.5116, MCC: 0.0604, F1: 0.4000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.56621 | val 1.19865
  Epoch 020 - train 0.49472 | val 1.68469
  Classification -> best τ=0.355 (val F1=0.2884)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.60843 | val 0.68368
  Epoch 020 - train 0.54583 | val 0.97448
  Epoch 028 - train 0.54445 | val 1.28070
  Classification -> best τ=0.475 (val F1=0.2721)
  Directional -> Accuracy: 0.5205, MCC: 0.1211, F1: 0.4068

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.68511 | val 0.71635
  Epoch 017 - train 0.54188 | val 0.96629
  Classification -> best τ=0.520 (val F1=0.0967)
  Directional -> Accuracy: 0.5135, MCC: 0.0327, F1: 0.5500

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.61190 | val 0.83519
  Epoch 016 - train 0.57018 | val 0.85207
  Classification -> best τ=0.565 (val F1=0.3103)
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.61670 | val 0.81714
  Epoch 016 - train 0.63042 | val 0.78649
  Classification -> best τ=0.455 (val F1=0.4292)
  Directional -> Accuracy: 0.6212, MCC: 0.2778, F1: 0.6154

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.54616 | val 0.87528
  Epoch 018 - train 0.50094 | val 1.12225
  Classification -> best τ=0.520 (val F1=0.3364)
  Directional -> Accuracy: 0.5238, MCC: 0.1168, F1: 0.2857

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.59563 | val 0.71733
  Epoch 020 - train 0.51848 | val 0.79999
  Classification -> best τ=0.415 (val F1=0.2203)
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.6341

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.57546 | val 0.79818
  Epoch 020 - train 0.46575 | val 0.77649
  Epoch 030 - train 0.38784 | val 1.13337
  Epoch 033 - train 0.37735 | val 1.03461
  Classification -> best τ=0.460 (val F1=0.3050)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.60568 | val 0.75535
  Epoch 020 - train 0.58135 | val 0.77874
  Epoch 021 - train 0.59410 | val 0.74771
  Classification -> best τ=0.420 (val F1=0.4188)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.66581 | val 0.74697
  Epoch 020 - train 0.47972 | val 0.96107
  Epoch 021 - train 0.53755 | val 1.08952
  Classification -> best τ=0.525 (val F1=0.4368)
  Directional -> Accuracy: 0.4324, MCC: -0.1115, F1: 0.1600

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.59049 | val 0.85528
  Epoch 020 - train 0.55468 | val 1.56178
  Classification -> best τ=0.660 (val F1=0.2165)
  Directional -> Accuracy: 0.5467, MCC: 0.1000, F1: 0.5952

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.59992 | val 0.66807
  Epoch 020 - train 0.55767 | val 0.70762
  Epoch 029 - train 0.44764 | val 0.75826
  Classification -> best τ=0.440 (val F1=0.5065)
  Directional -> Accuracy: 0.4130, MCC: -0.2002, F1: 0.1290

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.58781 | val 0.69687
  Epoch 020 - train 0.54776 | val 0.63205
  Epoch 030 - train 0.46185 | val 0.51505
  Epoch 040 - train 0.38876 | val 0.52150
  Epoch 050 - train 0.30708 | val 0.36500
  Classification -> best τ=0.380 (val F1=0.7906)
  Directional -> Accuracy: 0.5814, MCC: 0.1178, F1: 0.6897

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.56615 | val 0.64776
  Epoch 018 - train 0.56585 | val 0.72150
  Classification -> best τ=0.585 (val F1=0.6947)
  Directional -> Accuracy: 0.5714, MCC: 0.2281, F1: 0.5882

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.66333 | val 0.81668
  Epoch 016 - train 0.58132 | val 1.46534
  Classification -> best τ=0.515 (val F1=0.1903)
  Directional -> Accuracy: 0.5714, MCC: 0.2471, F1: 0.4000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.59314 | val 0.91356
  Epoch 019 - train 0.52175 | val 1.33939
  Classification -> best τ=0.560 (val F1=0.2747)
  Directional -> Accuracy: 0.5357, MCC: 0.1397, F1: 0.0714

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.62361 | val 1.12602
  Epoch 017 - train 0.59510 | val 1.96037
  Classification -> best τ=0.460 (val F1=0.2128)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.57926 | val 0.73130
  Epoch 017 - train 0.51567 | val 1.01232
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.65210 | val 0.68119

[I 2026-02-25 04:10:18,154] Trial 210 finished with value: 0.28114666854424164 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.5, 'batch_size': 64, 'learning_rate': 0.004820634887001003, 'weight_decay': 0.0002743424438172637, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 0.5927899543221329, 'early_stopping_min_delta': 0.003403967259382205}. Best is trial 200 with value: 0.303360648585588.

  Epoch 020 - train 0.52792 | val 1.09487
  Classification -> best τ=0.485 (val F1=0.2007)
  Directional -> Accuracy: 0.5082, MCC: 0.0239, F1: 0.5312

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.28114666854424164
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.67545 | val 0.71158
  Epoch 020 - train 0.58205 | val 0.99309
  Epoch 021 - train 0.59023 | val 0.95878
  Classification -> best τ=0.390 (val F1=0.3227)
  Directional -> Accuracy: 0.4474, MCC: 0.0000, F1: 0.6182

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.67876 | val 0.71008
  Epoch 016 - train 0.62972 | val 0.73142
  Classification -> best τ=0.425 (val F1=0.2317)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.68606 | val 0.70003
  Epoch 019 - train 0.64628 | val 0.74076
  Classification -> best τ=0.390 (val F1=0.3678)
  Directional -> Accuracy: 0.5532, MCC: 0.1039, F1: 0.6957

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.68748 | val 0.71515
  Epoch 016 - train 0.64561 | val 0.85252
  Classification -> best τ=0.445 (val F1=0.1210)
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.64495 | val 0.66803
  Epoch 020 - train 0.57285 | val 0.67060
  Epoch 027 - train 0.54975 | val 0.70431
  Classification -> best τ=0.555 (val F1=0.4946)
  Directional -> Accuracy: 0.5686, MCC: 0.1278, F1: 0.6207

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.75976 | val 0.73850
  Epoch 016 - train 0.56279 | val 0.80725
  Classification -> best τ=0.515 (val F1=0.2357)
  Directional -> Accuracy: 0.4468, MCC: -0.1151, F1: 0.5667

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.67535 | val 0.68751
  Epoch 020 - train 0.65091 | val 0.69434
  Epoch 026 - train 0.63719 | val 0.84412
  Classification -> best τ=0.435 (val F1=0.3308)
  Directional -> Accuracy: 0.4203, MCC: 0.0315, F1: 0.5745

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.64332 | val 0.69998
  Epoch 020 - train 0.59861 | val 0.69486
  Epoch 029 - train 0.48841 | val 0.82370
  Classification -> best τ=0.445 (val F1=0.1502)
  Directional -> Accuracy: 0.4884, MCC: 0.0454, F1: 0.5417

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.64853 | val 0.67546
  Epoch 018 - train 0.59228 | val 0.88101
  Classification -> best τ=0.450 (val F1=0.3475)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.62268 | val 0.68171
  Epoch 020 - train 0.54944 | val 0.79234
  Epoch 025 - train 0.55705 | val 0.93722
  Classification -> best τ=0.600 (val F1=0.2194)
  Directional -> Accuracy: 0.5286, MCC: 0.0172, F1: 0.4000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.68892 | val 0.93966
  Epoch 018 - train 0.64926 | val 1.59984
  Classification -> best τ=0.465 (val F1=0.4467)
  Directional -> Accuracy: 0.6000, MCC: 0.1848, F1: 0.4444

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.64738 | val 0.88393
  Epoch 018 - train 0.56946 | val 1.14575
  Classification -> best τ=0.570 (val F1=0.0325)
  Directional -> Accuracy: 0.6724, MCC: 0.3467, F1: 0.6545

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.64628 | val 0.76262
  Epoch 016 - train 0.57458 | val 0.95601
  Classification -> best τ=0.600 (val F1=0.1421)
  Directional -> Accuracy: 0.5238, MCC: 0.0302, F1: 0.4444

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.69322 | val 0.63107
  Epoch 020 - train 0.65048 | val 0.92598
  Epoch 026 - train 0.60060 | val 1.27065
  Classification -> best τ=0.285 (val F1=0.3282)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.63600 | val 0.83808
  Epoch 020 - train 0.55096 | val 0.82690
  Epoch 023 - train 0.54767 | val 1.07767
  Classification -> best τ=0.625 (val F1=0.2673)
  Directional -> Accuracy: 0.5192, MCC: -0.0636, F1: 0.0741

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.69063 | val 0.69991
  Epoch 020 - train 0.59327 | val 0.83640
  Epoch 022 - train 0.57581 | val 0.89037
  Classification -> best τ=0.540 (val F1=0.3395)
  Directional -> Accuracy: 0.5942, MCC: 0.2260, F1: 0.5333

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.66546 | val 1.10726
  Epoch 017 - train 0.63099 | val 1.44807
  Classification -> best τ=0.425 (val F1=0.1336)
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.68467 | val 0.82322
  Epoch 016 - train 0.64112 | val 1.18135
  Classification -> best τ=0.535 (val F1=0.1656)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.66721 | val 0.90831
  Epoch 017 - train 0.65058 | val 1.32626
  Classification -> best τ=0.455 (val F1=0.2522)
  Directional -> Accuracy: 0.5231, MCC: 0.1873, F1: 0.3922

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.67354 | val 0.66465
  Epoch 020 - train 0.62611 | val 0.97613
  Epoch 024 - train 0.61636 | val 0.95221
  Classification -> best τ=0.250 (val F1=0.2161)
  Directional -> Accuracy: 0.5200, MCC: -0.0040, F1: 0.6250

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.64984 | val 0.70534
  Epoch 020 - train 0.59386 | val 0.84967
  Classification -> best τ=0.495 (val F1=0.2807)
  Directional -> Accuracy: 0.5319, MCC: -0.0887, F1: 0.6667

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.66061 | val 0.76069
  Epoch 016 - train 0.63493 | val 0.84879
  Classification -> best τ=0.480 (val F1=0.1664)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6118

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.68127 | val 0.76867
  Epoch 016 - train 0.66412 | val 0.77201
  Classification -> best τ=0.685 (val F1=0.2864)
  Directional -> Accuracy: 0.4655, MCC: 0.0286, F1: 0.2791

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.66833 | val 0.75232
  Epoch 017 - train 0.62828 | val 0.83386
  Classification -> best τ=0.400 (val F1=0.1614)
  Directional -> Accuracy: 0.4769, MCC: 0.0000, F1: 0.6458

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.67925 | val 0.64487
  Epoch 020 - train 0.57386 | val 0.77175
  Epoch 024 - train 0.54192 | val 0.77494
  Classification -> best τ=0.460 (val F1=0.3953)
  Directional -> Accuracy: 0.5000, MCC: 0.0116, F1: 0.5000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.71163 | val 0.74540
  Epoch 016 - train 0.59140 | val 0.85655
  Classification -> best τ=0.465 (val F1=0.2935)
  Directional -> Accuracy: 0.5435, MCC: 0.1264, F1: 0.5714

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.61932 | val 0.69658
  Epoch 016 - train 0.65133 | val 0.74222
  Classification -> best τ=0.540 (val F1=0.2123)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.64230 | val 0.74944
  Epoch 018 - train 0.58103 | val 0.83184
  Classification -> best τ=0.400 (val F1=0.2260)
  Directional -> Accuracy: 0.5439, MCC: 0.2218, F1: 0.3810

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.75465 | val 0.67993
  Epoch 018 - train 0.68611 | val 0.76775
  Classification -> best τ=0.525 (val F1=0.4109)
  Directional -> Accuracy: 0.5366, MCC: 0.0166, F1: 0.6885

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.67081 | val 0.70073
  Epoch 018 - train 0.67489 | val 0.95454
  Classification -> best τ=0.515 (val F1=0.2962)
  Directional -> Accuracy: 0.5581, MCC: 0.1294, F1: 0.6122

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.66292 | val 0.70031
  Epoch 020 - train 0.63999 | val 0.66481
  Epoch 030 - train 0.58106 | val 0.85894
  Epoch 032 - train 0.57097 | val 0.75974
  Classification -> best τ=0.710 (val F1=0.1729)
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.60492 | val 0.86866
  Epoch 016 - train 0.56449 | val 1.31772
  Classification -> best τ=0.545 (val F1=0.2969)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.68690 | val 0.72358
  Epoch 020 - train 0.60852 | val 0.66991
  Epoch 030 - train 0.57879 | val 0.82965
  Epoch 032 - train 0.57307 | val 0.99189
  Classification -> best τ=0.375 (val F1=0.3396)
  Directional -> Accuracy: 0.5753, MCC: 0.1684, F1: 0.5753

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.66093 | val 0.76158
  Epoch 016 - train 0.62786 | val 1.00488
  Classification -> best τ=0.415 (val F1=0.2588)
  Directional -> Accuracy: 0.4324, MCC: -0.1456, F1: 0.5532

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.68017 | val 0.85470
  Epoch 017 - train 0.65096 | val 0.78158
  Classification -> best τ=0.610 (val F1=0.2480)
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.71520 | val 0.73178
  Epoch 019 - train 0.64922 | val 0.74615
  Classification -> best τ=0.390 (val F1=0.3525)
  Directional -> Accuracy: 0.5909, MCC: 0.1587, F1: 0.6494

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.58188 | val 0.82211
  Epoch 016 - train 0.51202 | val 0.92656
  Classification -> best τ=0.455 (val F1=0.2819)
  Directional -> Accuracy: 0.7381, MCC: 0.4835, F1: 0.7317

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.66654 | val 0.66799
  Epoch 016 - train 0.63161 | val 0.77888
  Classification -> best τ=0.430 (val F1=0.2450)
  Directional -> Accuracy: 0.5714, MCC: 0.1807, F1: 0.6250

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.61216 | val 0.72643
  Epoch 016 - train 0.57046 | val 0.97419
  Classification -> best τ=0.570 (val F1=0.2268)
  Directional -> Accuracy: 0.3913, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.65542 | val 0.73643
  Epoch 019 - train 0.59831 | val 0.68118
  Classification -> best τ=0.425 (val F1=0.4188)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.70709 | val 0.76911
  Epoch 016 - train 0.58298 | val 1.06657
  Classification -> best τ=0.460 (val F1=0.0585)
  Directional -> Accuracy: 0.5135, MCC: -0.0171, F1: 0.6250

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.69879 | val 0.78014
  Epoch 020 - train 0.63149 | val 0.96608
  Epoch 022 - train 0.60509 | val 0.91051
  Classification -> best τ=0.380 (val F1=0.3259)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.69900 | val 0.68371
  Epoch 020 - train 0.62297 | val 0.71895
  Epoch 024 - train 0.56489 | val 0.72574
  Classification -> best τ=0.430 (val F1=0.3403)
  Directional -> Accuracy: 0.5000, MCC: 0.1427, F1: 0.0800

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.64607 | val 0.71075
  Epoch 020 - train 0.59937 | val 0.62148
  Epoch 030 - train 0.54536 | val 0.63396
  Epoch 039 - train 0.49448 | val 0.69574
  Classification -> best τ=0.250 (val F1=0.4799)
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.7164

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.62515 | val 0.73812
  Epoch 020 - train 0.59169 | val 0.63550
  Epoch 030 - train 0.55894 | val 0.60301
  Epoch 038 - train 0.55607 | val 0.68261
  Classification -> best τ=0.500 (val F1=0.6947)
  Directional -> Accuracy: 0.3673, MCC: -0.1462, F1: 0.5231

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.63348 | val 0.83855
  Epoch 016 - train 0.64137 | val 1.67210
  Classification -> best τ=0.425 (val F1=0.2985)
  Directional -> Accuracy: 0.6250, MCC: 0.2404, F1: 0.6769

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.73554 | val 0.86581
  Epoch 018 - train 0.61119 | val 1.13266
  Classification -> best τ=0.580 (val F1=0.2349)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.67896 | val 0.77711
  Epoch 018 - train 0.62811 | val 1.09831
  Classification -> best τ=0.405 (val F1=0.2572)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.62527 | val 0.84386
  Epoch 016 - train 0.66781 | val 0.88627
  Classification -> best τ=0.535 (val F1=0.1557)
  Directional -> Accuracy: 0.4107, MCC: -0.2874, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.68054 | val 0.71526

[I 2026-02-25 04:12:21,756] Trial 211 finished with value: 0.2764959198597006 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 64, 'learning_rate': 0.004301293915244237, 'weight_decay': 0.00022092996471558904, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 0.20400364315653113, 'early_stopping_min_delta': 0.0042751239957859654}. Best is trial 200 with value: 0.303360648585588.

  Epoch 019 - train 0.61850 | val 0.87767
  Classification -> best τ=0.435 (val F1=0.2639)
  Directional -> Accuracy: 0.5082, MCC: -0.0451, F1: 0.1176

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2764959198597006
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.56420 | val 0.88506
  Epoch 020 - train 0.51003 | val 1.32093
  Classification -> best τ=0.450 (val F1=0.1430)
  Directional -> Accuracy: 0.5658, MCC: 0.1620, F1: 0.5926

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.55002 | val 0.75372
  Epoch 017 - train 0.50751 | val 0.80704
  Classification -> best τ=0.515 (val F1=0.2779)
  Directional -> Accuracy: 0.5333, MCC: 0.0782, F1: 0.5532

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.59245 | val 0.74825
  Epoch 017 - train 0.53633 | val 0.87688
  Classification -> best τ=0.470 (val F1=0.1978)
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.63180 | val 0.72538
  Epoch 017 - train 0.58222 | val 0.76396
  Classification -> best τ=0.420 (val F1=0.2782)
  Directional -> Accuracy: 0.5733, MCC: 0.1392, F1: 0.6098

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.53339 | val 0.71689
  Epoch 020 - train 0.45443 | val 0.86061
  Epoch 021 - train 0.45235 | val 0.89002
  Classification -> best τ=0.555 (val F1=0.3484)
  Directional -> Accuracy: 0.4118, MCC: -0.1806, F1: 0.4444

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.55190 | val 0.69796
  Epoch 016 - train 0.47146 | val 0.71732
  Classification -> best τ=0.455 (val F1=0.2582)
  Directional -> Accuracy: 0.4894, MCC: 0.0000, F1: 0.6571

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.60428 | val 0.87480
  Epoch 018 - train 0.54342 | val 0.95162
  Classification -> best τ=0.635 (val F1=0.1805)
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.47064 | val 0.70944
  Epoch 020 - train 0.36134 | val 1.35904
  Epoch 022 - train 0.38055 | val 2.30306
  Classification -> best τ=0.290 (val F1=0.1752)
  Directional -> Accuracy: 0.4419, MCC: 0.0473, F1: 0.5862

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.56069 | val 0.68170
  Epoch 020 - train 0.46001 | val 1.31563
  Epoch 024 - train 0.43978 | val 1.35279
  Classification -> best τ=0.515 (val F1=0.2335)
  Directional -> Accuracy: 0.5918, MCC: 0.1635, F1: 0.2857

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.55088 | val 0.83980
  Epoch 016 - train 0.46811 | val 1.18937
  Classification -> best τ=0.460 (val F1=0.2607)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.58683 | val 0.73449
  Epoch 019 - train 0.46637 | val 1.39611
  Classification -> best τ=0.475 (val F1=0.1667)
  Directional -> Accuracy: 0.5200, MCC: 0.0788, F1: 0.5862

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.54489 | val 0.79290
  Epoch 016 - train 0.45682 | val 1.00722
  Classification -> best τ=0.500 (val F1=0.1469)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.57163 | val 0.93152
  Epoch 016 - train 0.49892 | val 1.66618
  Classification -> best τ=0.470 (val F1=0.2876)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.58528 | val 0.73525
  Epoch 020 - train 0.49082 | val 1.31212
  Epoch 021 - train 0.52477 | val 1.39525
  Classification -> best τ=0.395 (val F1=0.3407)
  Directional -> Accuracy: 0.6167, MCC: 0.3634, F1: 0.7229

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.53988 | val 0.73907
  Epoch 017 - train 0.44118 | val 1.04071
  Classification -> best τ=0.540 (val F1=0.2673)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.59656 | val 0.78856
  Epoch 020 - train 0.50017 | val 0.97595
  Epoch 023 - train 0.50151 | val 0.97007
  Classification -> best τ=0.625 (val F1=0.3395)
  Directional -> Accuracy: 0.4928, MCC: 0.1063, F1: 0.1463

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.58656 | val 1.04541
  Epoch 017 - train 0.53859 | val 1.64539
  Classification -> best τ=0.475 (val F1=0.0980)
  Directional -> Accuracy: 0.6271, MCC: 0.0884, F1: 0.7556

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.61984 | val 0.79433
  Epoch 016 - train 0.58278 | val 1.27750
  Classification -> best τ=0.480 (val F1=0.0784)
  Directional -> Accuracy: 0.6000, MCC: 0.0000, F1: 0.7500

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.62379 | val 1.44744
  Epoch 016 - train 0.51290 | val 1.87751
  Classification -> best τ=0.445 (val F1=0.3343)
  Directional -> Accuracy: 0.5538, MCC: 0.0140, F1: 0.6742

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.58749 | val 0.67510
  Epoch 019 - train 0.51643 | val 1.12936
  Classification -> best τ=0.555 (val F1=0.2606)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.52716 | val 0.82831
  Epoch 018 - train 0.47497 | val 1.18872
  Classification -> best τ=0.495 (val F1=0.2267)
  Directional -> Accuracy: 0.6170, MCC: 0.0508, F1: 0.7568

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.57128 | val 0.69524
  Epoch 019 - train 0.52653 | val 0.74847
  Classification -> best τ=0.515 (val F1=0.2865)
  Directional -> Accuracy: 0.5455, MCC: 0.0976, F1: 0.6154

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.59143 | val 0.84631
  Epoch 017 - train 0.53587 | val 0.92152
  Classification -> best τ=0.700 (val F1=0.2864)
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.56406 | val 0.82036
  Epoch 017 - train 0.46435 | val 1.07948
  Classification -> best τ=0.535 (val F1=0.1936)
  Directional -> Accuracy: 0.4615, MCC: -0.1368, F1: 0.1860

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.56864 | val 0.65023
  Epoch 020 - train 0.45088 | val 0.90330
  Epoch 024 - train 0.41644 | val 0.90130
  Classification -> best τ=0.590 (val F1=0.3730)
  Directional -> Accuracy: 0.4643, MCC: 0.1211, F1: 0.0625

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.55490 | val 0.74875
  Epoch 016 - train 0.47958 | val 0.87041
  Classification -> best τ=0.480 (val F1=0.2935)
  Directional -> Accuracy: 0.5652, MCC: 0.0280, F1: 0.0909

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.58152 | val 0.67554
  Epoch 020 - train 0.51897 | val 0.70588
  Epoch 025 - train 0.49379 | val 0.67372
  Classification -> best τ=0.590 (val F1=0.2402)
  Directional -> Accuracy: 0.4286, MCC: -0.0700, F1: 0.2500

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.54640 | val 0.84544
  Epoch 016 - train 0.51166 | val 1.37170
  Classification -> best τ=0.430 (val F1=0.1939)
  Directional -> Accuracy: 0.5965, MCC: 0.2671, F1: 0.5306

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.52718 | val 0.71842
  Epoch 020 - train 0.44215 | val 1.01925
  Epoch 024 - train 0.40698 | val 1.48812
  Classification -> best τ=0.470 (val F1=0.4139)
  Directional -> Accuracy: 0.5854, MCC: 0.1688, F1: 0.7018

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.59070 | val 0.75795
  Epoch 016 - train 0.48257 | val 1.10127
  Classification -> best τ=0.520 (val F1=0.2814)
  Directional -> Accuracy: 0.5116, MCC: 0.0197, F1: 0.4615

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.58326 | val 0.85380
  Epoch 017 - train 0.48735 | val 1.21636
  Classification -> best τ=0.485 (val F1=0.0679)
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.53248 | val 0.84623
  Epoch 020 - train 0.43371 | val 1.56200
  Epoch 021 - train 0.42624 | val 1.63490
  Classification -> best τ=0.605 (val F1=0.2969)
  Directional -> Accuracy: 0.4600, MCC: -0.0602, F1: 0.4000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.57198 | val 0.74266
  Epoch 020 - train 0.49691 | val 1.27441
  Classification -> best τ=0.490 (val F1=0.2971)
  Directional -> Accuracy: 0.5342, MCC: 0.1140, F1: 0.4848

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.51620 | val 0.75323
  Epoch 020 - train 0.48401 | val 1.04031
  Epoch 022 - train 0.48433 | val 1.02713
  Classification -> best τ=0.445 (val F1=0.3105)
  Directional -> Accuracy: 0.4865, MCC: -0.0065, F1: 0.6415

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.58448 | val 0.80546
  Epoch 017 - train 0.50285 | val 0.88680
  Classification -> best τ=0.540 (val F1=0.3278)
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.57425 | val 0.87490
  Epoch 016 - train 0.54112 | val 0.98249
  Classification -> best τ=0.500 (val F1=0.3280)
  Directional -> Accuracy: 0.5758, MCC: 0.0000, F1: 0.7308

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.53981 | val 0.77736
  Epoch 016 - train 0.50493 | val 1.11573
  Classification -> best τ=0.500 (val F1=0.2819)
  Directional -> Accuracy: 0.7143, MCC: 0.4273, F1: 0.7273

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.58419 | val 0.81014
  Epoch 016 - train 0.51329 | val 0.87164
  Classification -> best τ=0.440 (val F1=0.2450)
  Directional -> Accuracy: 0.5357, MCC: 0.1371, F1: 0.6286

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.52301 | val 0.81436
  Epoch 016 - train 0.41817 | val 0.91738
  Classification -> best τ=0.455 (val F1=0.3146)
  Directional -> Accuracy: 0.5870, MCC: 0.0062, F1: 0.7246

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.58061 | val 0.74566
  Epoch 018 - train 0.54931 | val 0.81037
  Classification -> best τ=0.460 (val F1=0.3533)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.52239 | val 0.78723
  Epoch 016 - train 0.51449 | val 0.89360
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.57945 | val 0.79000
  Epoch 018 - train 0.54571 | val 1.22447
  Classification -> best τ=0.465 (val F1=0.3914)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.61223 | val 0.66481
  Epoch 020 - train 0.47319 | val 0.75002
  Epoch 030 - train 0.38489 | val 0.71425
  Epoch 032 - train 0.35881 | val 1.29809
  Classification -> best τ=0.390 (val F1=0.4494)
  Directional -> Accuracy: 0.5652, MCC: 0.1434, F1: 0.5238

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.57403 | val 0.71926
  Epoch 020 - train 0.47250 | val 0.75067
  Epoch 027 - train 0.38154 | val 1.08661
  Classification -> best τ=0.335 (val F1=0.2855)
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.7164

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.55242 | val 0.63138
  Epoch 020 - train 0.44336 | val 0.64319
  Epoch 030 - train 0.33898 | val 0.80691
  Epoch 031 - train 0.31855 | val 0.84368
  Classification -> best τ=0.325 (val F1=0.4682)
  Directional -> Accuracy: 0.3673, MCC: -0.1462, F1: 0.5231

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.64470 | val 0.89314
  Epoch 017 - train 0.56668 | val 1.05493
  Classification -> best τ=0.450 (val F1=0.2985)
  Directional -> Accuracy: 0.6607, MCC: 0.3810, F1: 0.5957

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.56061 | val 1.02548
  Epoch 017 - train 0.52566 | val 1.22974
  Classification -> best τ=0.575 (val F1=0.2157)
  Directional -> Accuracy: 0.5536, MCC: 0.1100, F1: 0.3243

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.55181 | val 1.51736
  Epoch 017 - train 0.50084 | val 2.58619
  Classification -> best τ=0.380 (val F1=0.2570)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.54218 | val 0.80973
  Epoch 016 - train 0.47220 | val 0.99170
  Classification -> best τ=0.560 (val F1=0.1145)
  Directional -> Accuracy: 0.4643, MCC: -0.1173, F1: 0.5946

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.61176 | val 0.69980
  Epoch 020 - train 0.51087 | val 0.96278

[I 2026-02-25 04:14:17,982] Trial 212 finished with value: 0.260589421255376 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.30000000000000004, 'batch_size': 64, 'learning_rate': 0.002899057971175519, 'weight_decay': 0.00024465564218643444, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 0.5143531760828225, 'early_stopping_min_delta': 0.0039900301603821645}. Best is trial 200 with value: 0.303360648585588.

  Epoch 023 - train 0.46243 | val 1.77072
  Classification -> best τ=0.570 (val F1=0.2639)
  Directional -> Accuracy: 0.5082, MCC: -0.1229, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.260589421255376
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.61842 | val 0.69942
  Epoch 017 - train 0.56346 | val 0.77810
  Classification -> best τ=0.445 (val F1=0.1616)
  Directional -> Accuracy: 0.4342, MCC: -0.0894, F1: 0.5981

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.59328 | val 0.75498
  Epoch 018 - train 0.48914 | val 0.82355
  Classification -> best τ=0.455 (val F1=0.2095)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.62887 | val 0.72435
  Epoch 016 - train 0.61726 | val 0.85230
  Classification -> best τ=0.520 (val F1=0.1004)
  Directional -> Accuracy: 0.4681, MCC: -0.0195, F1: 0.1379

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.65105 | val 0.86510
  Epoch 017 - train 0.63048 | val 0.74216
  Classification -> best τ=0.475 (val F1=0.2448)
  Directional -> Accuracy: 0.4533, MCC: -0.0223, F1: 0.0889

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.58045 | val 0.68486
  Epoch 020 - train 0.51251 | val 0.67162
  Epoch 023 - train 0.48611 | val 0.75527
  Classification -> best τ=0.580 (val F1=0.4598)
  Directional -> Accuracy: 0.5098, MCC: 0.0000, F1: 0.5902

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.58662 | val 0.75447
  Epoch 016 - train 0.50840 | val 1.14459
  Classification -> best τ=0.520 (val F1=0.2887)
  Directional -> Accuracy: 0.4894, MCC: 0.0000, F1: 0.6571

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.67488 | val 0.73275
  Epoch 020 - train 0.60306 | val 1.07457
  Epoch 023 - train 0.54571 | val 1.22467
  Classification -> best τ=0.460 (val F1=0.3018)
  Directional -> Accuracy: 0.4783, MCC: 0.1448, F1: 0.5909

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.53953 | val 0.78318
  Epoch 017 - train 0.47035 | val 0.68060
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.5902

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.57943 | val 0.73257
  Epoch 020 - train 0.51645 | val 1.13312
  Classification -> best τ=0.410 (val F1=0.2308)
  Directional -> Accuracy: 0.4694, MCC: 0.0332, F1: 0.6061

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.59004 | val 0.71581
  Epoch 020 - train 0.54729 | val 0.73291
  Epoch 029 - train 0.47549 | val 0.79757
  Classification -> best τ=0.540 (val F1=0.2951)
  Directional -> Accuracy: 0.5286, MCC: 0.0661, F1: 0.5075

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.59605 | val 0.78340
  Epoch 017 - train 0.60463 | val 2.59493
  Classification -> best τ=0.540 (val F1=0.3613)
  Directional -> Accuracy: 0.6400, MCC: 0.2848, F1: 0.4706

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.58184 | val 0.96787
  Epoch 018 - train 0.52492 | val 1.09075
  Classification -> best τ=0.515 (val F1=0.2097)
  Directional -> Accuracy: 0.4310, MCC: -0.2000, F1: 0.5823

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.60426 | val 0.84658
  Epoch 016 - train 0.54775 | val 1.35118
  Classification -> best τ=0.430 (val F1=0.2731)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.67624 | val 0.61938
  Epoch 020 - train 0.58008 | val 1.05176
  Epoch 025 - train 0.53671 | val 0.87175
  Classification -> best τ=0.465 (val F1=0.3141)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.56776 | val 0.94875
  Epoch 017 - train 0.53466 | val 2.37414
  Classification -> best τ=0.470 (val F1=0.1018)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.60158 | val 0.86340
  Epoch 018 - train 0.53891 | val 1.05399
  Classification -> best τ=0.415 (val F1=0.2708)
  Directional -> Accuracy: 0.5507, MCC: 0.0713, F1: 0.6804

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.65421 | val 1.12631
  Epoch 016 - train 0.56149 | val 1.06634
  Classification -> best τ=0.690 (val F1=0.1065)
  Directional -> Accuracy: 0.3729, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.63229 | val 1.05773
  Epoch 016 - train 0.60104 | val 1.27379
  Classification -> best τ=0.445 (val F1=0.2446)
  Directional -> Accuracy: 0.5733, MCC: 0.0915, F1: 0.6596

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.63211 | val 1.23922
  Epoch 016 - train 0.62075 | val 1.80170
  Classification -> best τ=0.525 (val F1=0.2366)
  Directional -> Accuracy: 0.4923, MCC: -0.1193, F1: 0.6207

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.66455 | val 0.70871
  Epoch 020 - train 0.57722 | val 1.14414
  Epoch 022 - train 0.56457 | val 1.14745
  Classification -> best τ=0.415 (val F1=0.2676)
  Directional -> Accuracy: 0.4667, MCC: -0.1252, F1: 0.5833

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.59719 | val 0.72083
  Epoch 020 - train 0.50825 | val 0.89659
  Epoch 021 - train 0.49763 | val 0.88546
  Classification -> best τ=0.520 (val F1=0.3721)
  Directional -> Accuracy: 0.4468, MCC: 0.2057, F1: 0.1875

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.65022 | val 0.69169
  Epoch 018 - train 0.60264 | val 0.79502
  Classification -> best τ=0.520 (val F1=0.2865)
  Directional -> Accuracy: 0.4545, MCC: -0.0925, F1: 0.4000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.64084 | val 0.80054
  Epoch 017 - train 0.60469 | val 0.87422
  Classification -> best τ=0.575 (val F1=0.2875)
  Directional -> Accuracy: 0.5690, MCC: 0.1441, F1: 0.5902

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.62695 | val 0.95292
  Epoch 017 - train 0.54706 | val 1.35495
  Classification -> best τ=0.430 (val F1=0.1936)
  Directional -> Accuracy: 0.4769, MCC: 0.0000, F1: 0.6458

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.61353 | val 0.73798
  Epoch 017 - train 0.52092 | val 0.77280
  Classification -> best τ=0.505 (val F1=0.3727)
  Directional -> Accuracy: 0.5357, MCC: 0.1728, F1: 0.3810

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.59365 | val 0.71388
  Epoch 020 - train 0.51588 | val 0.86002
  Epoch 021 - train 0.49346 | val 0.74412
  Classification -> best τ=0.470 (val F1=0.2935)
  Directional -> Accuracy: 0.4565, MCC: 0.1307, F1: 0.6154

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.62590 | val 0.69749
  Epoch 020 - train 0.57765 | val 0.67504
  Epoch 030 - train 0.52117 | val 0.65140
  Epoch 040 - train 0.47000 | val 0.77732
  Epoch 046 - train 0.39456 | val 0.85126
  Classification -> best τ=0.650 (val F1=0.3536)
  Directional -> Accuracy: 0.5238, MCC: 0.0550, F1: 0.5455

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.58460 | val 0.84021
  Epoch 016 - train 0.53492 | val 1.02100
  Classification -> best τ=0.465 (val F1=0.3540)
  Directional -> Accuracy: 0.5263, MCC: 0.2741, F1: 0.2703

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.67046 | val 0.65654
  Epoch 020 - train 0.54799 | val 0.96916
  Epoch 024 - train 0.49618 | val 0.95540
  Classification -> best τ=0.575 (val F1=0.3477)
  Directional -> Accuracy: 0.5122, MCC: -0.0108, F1: 0.6154

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.65232 | val 0.89421
  Epoch 016 - train 0.55504 | val 1.21081
  Classification -> best τ=0.515 (val F1=0.2271)
  Directional -> Accuracy: 0.5581, MCC: 0.1239, F1: 0.5957

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.62243 | val 0.71681
  Epoch 018 - train 0.55209 | val 0.90257
  Classification -> best τ=0.515 (val F1=0.1729)
  Directional -> Accuracy: 0.5349, MCC: 0.1193, F1: 0.4118

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.56023 | val 0.98975
  Epoch 016 - train 0.51759 | val 1.69721
  Classification -> best τ=0.430 (val F1=0.4694)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.61918 | val 0.73864
  Epoch 020 - train 0.54421 | val 1.83549
  Epoch 021 - train 0.56713 | val 1.64832
  Classification -> best τ=0.340 (val F1=0.3313)
  Directional -> Accuracy: 0.5616, MCC: 0.1530, F1: 0.5429

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.57333 | val 0.81982
  Epoch 018 - train 0.56101 | val 1.27830
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.61787 | val 0.82055
  Epoch 019 - train 0.54281 | val 0.79539
  Classification -> best τ=0.470 (val F1=0.2757)
  Directional -> Accuracy: 0.5227, MCC: 0.0415, F1: 0.4878

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.64681 | val 0.73744
  Epoch 016 - train 0.57983 | val 0.84897
  Classification -> best τ=0.495 (val F1=0.2464)
  Directional -> Accuracy: 0.5758, MCC: 0.0000, F1: 0.7308

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.59728 | val 0.71522
  Epoch 016 - train 0.48792 | val 0.87720
  Classification -> best τ=0.545 (val F1=0.2652)
  Directional -> Accuracy: 0.6429, MCC: 0.3511, F1: 0.5455

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.63720 | val 0.71894
  Epoch 016 - train 0.55581 | val 0.87007
  Classification -> best τ=0.385 (val F1=0.2450)
  Directional -> Accuracy: 0.5714, MCC: 0.2471, F1: 0.6667

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.54383 | val 0.78321
  Epoch 016 - train 0.43651 | val 0.96273
  Classification -> best τ=0.455 (val F1=0.3105)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.62296 | val 0.67786
  Epoch 020 - train 0.51208 | val 0.69767
  Epoch 021 - train 0.56686 | val 0.83097
  Classification -> best τ=0.305 (val F1=0.4188)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.59666 | val 0.81357
  Epoch 016 - train 0.54448 | val 1.04313
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.59861 | val 0.78287
  Epoch 019 - train 0.55838 | val 1.61467
  Classification -> best τ=0.460 (val F1=0.3609)
  Directional -> Accuracy: 0.5200, MCC: 0.1155, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.58819 | val 0.67949
  Epoch 020 - train 0.49841 | val 0.72896
  Epoch 030 - train 0.41727 | val 0.84641
  Classification -> best τ=0.530 (val F1=0.4141)
  Directional -> Accuracy: 0.4783, MCC: -0.0455, F1: 0.5000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.58698 | val 0.69362
  Epoch 020 - train 0.54626 | val 0.70017
  Epoch 029 - train 0.37578 | val 0.79306
  Classification -> best τ=0.485 (val F1=0.5270)
  Directional -> Accuracy: 0.5814, MCC: 0.1178, F1: 0.6897

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.64694 | val 0.65460
  Epoch 020 - train 0.52489 | val 0.64316
  Epoch 027 - train 0.50909 | val 0.62855
  Classification -> best τ=0.610 (val F1=0.6110)
  Directional -> Accuracy: 0.3673, MCC: -0.1462, F1: 0.5231

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.65157 | val 0.83617
  Epoch 020 - train 0.56344 | val 0.86744
  Classification -> best τ=0.565 (val F1=0.0296)
  Directional -> Accuracy: 0.4464, MCC: -0.0837, F1: 0.3111

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.59652 | val 0.83009
  Epoch 017 - train 0.55184 | val 1.07789
  Classification -> best τ=0.615 (val F1=0.2779)
  Directional -> Accuracy: 0.5357, MCC: 0.0879, F1: 0.1333

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.63534 | val 0.87854
  Epoch 020 - train 0.56519 | val 1.42827
  Epoch 024 - train 0.54612 | val 2.39107
  Classification -> best τ=0.715 (val F1=0.1626)
  Directional -> Accuracy: 0.5556, MCC: 0.1052, F1: 0.6364

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.60021 | val 0.77973
  Epoch 020 - train 0.54080 | val 0.94942
  Epoch 024 - train 0.47952 | val 1.00252
  Classification -> best τ=0.620 (val F1=0.1557)
  Directional -> Accuracy: 0.4464, MCC: -0.1135, F1: 0.4918

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.64202 | val 0.67772
  Epoch 020 - train 0.54700 | val 1.38069

[I 2026-02-25 04:16:18,450] Trial 213 finished with value: 0.2653817244748936 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.5, 'batch_size': 64, 'learning_rate': 0.003836057650636271, 'weight_decay': 0.00016647577068219568, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 0.5566256226014472, 'early_stopping_min_delta': 0.004042929542134957}. Best is trial 200 with value: 0.303360648585588.

  Epoch 022 - train 0.52451 | val 1.64522
  Classification -> best τ=0.330 (val F1=0.2283)
  Directional -> Accuracy: 0.5246, MCC: 0.1648, F1: 0.6588

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2653817244748936
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.66851 | val 0.76146
  Epoch 017 - train 0.62879 | val 0.77149
  Classification -> best τ=0.570 (val F1=0.2036)
  Directional -> Accuracy: 0.5526, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.62729 | val 0.69178
  Epoch 019 - train 0.60149 | val 0.69953
  Classification -> best τ=0.410 (val F1=0.2820)
  Directional -> Accuracy: 0.6222, MCC: 0.2073, F1: 0.7463

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.70140 | val 0.71447
  Epoch 020 - train 0.60622 | val 1.11311
  Epoch 024 - train 0.58868 | val 1.18856
  Classification -> best τ=0.485 (val F1=0.3313)
  Directional -> Accuracy: 0.5532, MCC: 0.1581, F1: 0.4324

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.65741 | val 0.74999
  Epoch 017 - train 0.67560 | val 0.76777
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.62925 | val 0.66767
  Epoch 020 - train 0.57059 | val 0.67838
  Epoch 022 - train 0.49924 | val 0.68588
  Classification -> best τ=0.560 (val F1=0.4457)
  Directional -> Accuracy: 0.4314, MCC: -0.1667, F1: 0.5246

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.63109 | val 0.72583
  Epoch 017 - train 0.66172 | val 0.89811
  Classification -> best τ=0.505 (val F1=0.1664)
  Directional -> Accuracy: 0.5957, MCC: 0.2077, F1: 0.4571

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.67850 | val 0.68611
  Epoch 020 - train 0.65205 | val 0.74569
  Epoch 028 - train 0.63257 | val 0.89279
  Classification -> best τ=0.440 (val F1=0.2936)
  Directional -> Accuracy: 0.4203, MCC: 0.1002, F1: 0.5833

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.75466 | val 0.59812
  Epoch 020 - train 0.60441 | val 0.61787
  Epoch 025 - train 0.55665 | val 1.09471
  Classification -> best τ=0.340 (val F1=0.1052)
  Directional -> Accuracy: 0.5349, MCC: -0.0024, F1: 0.3333

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.67480 | val 0.71771
  Epoch 017 - train 0.63928 | val 0.73574
  Classification -> best τ=0.470 (val F1=0.2218)
  Directional -> Accuracy: 0.5510, MCC: 0.0212, F1: 0.0833

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.66355 | val 0.69628
  Epoch 020 - train 0.60805 | val 0.79812
  Epoch 026 - train 0.58224 | val 0.71704
  Classification -> best τ=0.470 (val F1=0.2538)
  Directional -> Accuracy: 0.5286, MCC: 0.0747, F1: 0.5217

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.70343 | val 0.82130
  Epoch 017 - train 0.65798 | val 1.36826
  Classification -> best τ=0.405 (val F1=0.2063)
  Directional -> Accuracy: 0.6000, MCC: 0.1943, F1: 0.3750

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.65820 | val 0.71877
  Epoch 019 - train 0.59671 | val 1.00796
  Classification -> best τ=0.440 (val F1=0.2097)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.69504 | val 0.81861
  Epoch 016 - train 0.57890 | val 1.04982
  Classification -> best τ=0.525 (val F1=0.2235)
  Directional -> Accuracy: 0.4524, MCC: -0.0214, F1: 0.6102

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.70151 | val 0.64869
  Epoch 020 - train 0.66612 | val 0.86680
  Epoch 027 - train 0.58932 | val 1.10850
  Classification -> best τ=0.435 (val F1=0.3916)
  Directional -> Accuracy: 0.5333, MCC: 0.0894, F1: 0.6500

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.66237 | val 0.84571
  Epoch 017 - train 0.60612 | val 0.84961
  Classification -> best τ=0.485 (val F1=0.3169)
  Directional -> Accuracy: 0.5577, MCC: 0.1417, F1: 0.5965

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.66223 | val 0.70377
  Epoch 017 - train 0.62019 | val 0.71351
  Classification -> best τ=0.575 (val F1=0.3038)
  Directional -> Accuracy: 0.5362, MCC: 0.0853, F1: 0.5152

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.66078 | val 0.94979
  Epoch 016 - train 0.61831 | val 1.14306
  Classification -> best τ=0.645 (val F1=0.1842)
  Directional -> Accuracy: 0.3729, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.68068 | val 0.78982
  Epoch 016 - train 0.61703 | val 0.98700
  Classification -> best τ=0.490 (val F1=0.1764)
  Directional -> Accuracy: 0.5467, MCC: -0.0266, F1: 0.6731

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.64741 | val 1.08527
  Epoch 016 - train 0.62159 | val 1.34567
  Classification -> best τ=0.500 (val F1=0.2770)
  Directional -> Accuracy: 0.5385, MCC: -0.0474, F1: 0.6739

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.69093 | val 0.67869
  Epoch 019 - train 0.65611 | val 0.85642
  Classification -> best τ=0.500 (val F1=0.3799)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.67170 | val 0.69856
  Epoch 020 - train 0.55789 | val 1.41156
  Epoch 027 - train 0.51046 | val 1.29536
  Classification -> best τ=0.420 (val F1=0.3296)
  Directional -> Accuracy: 0.4043, MCC: 0.0267, F1: 0.1250

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.69402 | val 0.71852
  Epoch 016 - train 0.63374 | val 0.95811
  Classification -> best τ=0.495 (val F1=0.0876)
  Directional -> Accuracy: 0.4545, MCC: -0.1039, F1: 0.5610

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.64162 | val 0.75971
  Epoch 020 - train 0.63934 | val 0.74857
  Epoch 022 - train 0.61571 | val 0.81601
  Classification -> best τ=0.550 (val F1=0.2835)
  Directional -> Accuracy: 0.6897, MCC: 0.3585, F1: 0.7429

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.67852 | val 0.73774
  Epoch 016 - train 0.63675 | val 0.69236
  Classification -> best τ=0.485 (val F1=0.1507)
  Directional -> Accuracy: 0.5692, MCC: 0.1561, F1: 0.6111

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.69195 | val 0.69185
  Epoch 020 - train 0.57020 | val 0.66216
  Epoch 023 - train 0.57055 | val 0.68053
  Classification -> best τ=0.520 (val F1=0.4297)
  Directional -> Accuracy: 0.5536, MCC: 0.3111, F1: 0.3243

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.64817 | val 0.81548
  Epoch 017 - train 0.61180 | val 0.95369
  Classification -> best τ=0.475 (val F1=0.2935)
  Directional -> Accuracy: 0.5435, MCC: 0.1424, F1: 0.5882

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.64659 | val 0.70331
  Epoch 016 - train 0.62322 | val 0.82338
  Classification -> best τ=0.525 (val F1=0.0525)
  Directional -> Accuracy: 0.5714, MCC: 0.1840, F1: 0.5500

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.65317 | val 0.73292
  Epoch 017 - train 0.63893 | val 0.92168
  Classification -> best τ=0.450 (val F1=0.2750)
  Directional -> Accuracy: 0.5439, MCC: 0.2218, F1: 0.3810

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.57671 | val 0.70070
  Epoch 018 - train 0.63366 | val 1.20669
  Classification -> best τ=0.585 (val F1=0.2774)
  Directional -> Accuracy: 0.4878, MCC: -0.0121, F1: 0.4615

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.64537 | val 0.81982
  Epoch 018 - train 0.65003 | val 0.86563
  Classification -> best τ=0.540 (val F1=0.2814)
  Directional -> Accuracy: 0.5581, MCC: 0.1169, F1: 0.5581

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.63512 | val 0.64636
  Epoch 020 - train 0.57417 | val 0.64893
  Epoch 028 - train 0.56559 | val 0.69428
  Classification -> best τ=0.730 (val F1=0.2872)
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.64100 | val 0.74665
  Epoch 017 - train 0.60380 | val 0.89228
  Classification -> best τ=0.565 (val F1=0.2399)
  Directional -> Accuracy: 0.4200, MCC: -0.1445, F1: 0.1714

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.65462 | val 0.66725
  Epoch 018 - train 0.63040 | val 0.72065
  Classification -> best τ=0.390 (val F1=0.3391)
  Directional -> Accuracy: 0.5479, MCC: 0.1382, F1: 0.5075

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.77828 | val 0.83573
  Epoch 016 - train 0.60680 | val 0.82009
  Classification -> best τ=0.410 (val F1=0.5590)
  Directional -> Accuracy: 0.5405, MCC: 0.1348, F1: 0.6531

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.75425 | val 0.71001
  Epoch 019 - train 0.63233 | val 0.87993
  Classification -> best τ=0.495 (val F1=0.3464)
  Directional -> Accuracy: 0.5682, MCC: 0.1288, F1: 0.4571

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.65891 | val 0.72011
  Epoch 019 - train 0.62440 | val 0.79257
  Classification -> best τ=0.430 (val F1=0.2088)
  Directional -> Accuracy: 0.6364, MCC: 0.2807, F1: 0.6571

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.63151 | val 0.82922
  Epoch 016 - train 0.56257 | val 0.84328
  Classification -> best τ=0.385 (val F1=0.2986)
  Directional -> Accuracy: 0.6905, MCC: 0.4122, F1: 0.6486

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.63518 | val 0.76492
  Epoch 016 - train 0.62369 | val 0.83901
  Classification -> best τ=0.390 (val F1=0.2450)
  Directional -> Accuracy: 0.5357, MCC: 0.1754, F1: 0.6486

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.59582 | val 0.92219
  Epoch 019 - train 0.51723 | val 1.00566
  Classification -> best τ=0.565 (val F1=0.3294)
  Directional -> Accuracy: 0.4130, MCC: 0.1195, F1: 0.0690

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.80686 | val 0.68841
  Epoch 020 - train 0.61928 | val 0.67382
  Epoch 030 - train 0.58229 | val 0.59270
  Epoch 040 - train 0.55963 | val 0.60603
  Epoch 045 - train 0.54472 | val 0.61980
  Classification -> best τ=0.330 (val F1=0.6130)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.63196 | val 0.84857
  Epoch 016 - train 0.60196 | val 1.02995
  Classification -> best τ=0.505 (val F1=0.0585)
  Directional -> Accuracy: 0.4595, MCC: -0.0792, F1: 0.4737

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.65716 | val 0.73296
  Epoch 020 - train 0.61705 | val 0.87550
  Epoch 022 - train 0.60081 | val 1.10582
  Classification -> best τ=0.370 (val F1=0.3259)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.76339 | val 0.68949
  Epoch 016 - train 0.60197 | val 0.71348
  Classification -> best τ=0.475 (val F1=0.3952)
  Directional -> Accuracy: 0.5652, MCC: 0.1348, F1: 0.6774

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.72006 | val 0.71584
  Epoch 020 - train 0.58763 | val 0.81013
  Epoch 024 - train 0.62511 | val 0.85849
  Classification -> best τ=0.525 (val F1=0.4743)
  Directional -> Accuracy: 0.5581, MCC: 0.0644, F1: 0.6667

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.63901 | val 0.63454
  Epoch 020 - train 0.64094 | val 0.73536
  Epoch 024 - train 0.57774 | val 0.68411
  Classification -> best τ=0.530 (val F1=0.5514)
  Directional -> Accuracy: 0.3673, MCC: -0.1462, F1: 0.5231

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.67516 | val 0.75407
  Epoch 017 - train 0.62939 | val 1.02993
  Classification -> best τ=0.625 (val F1=0.2519)
  Directional -> Accuracy: 0.4643, MCC: -0.0248, F1: 0.1667

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.68664 | val 1.00355
  Epoch 020 - train 0.63394 | val 1.35166
  Classification -> best τ=0.540 (val F1=0.3133)
  Directional -> Accuracy: 0.6250, MCC: 0.2482, F1: 0.6038

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.61985 | val 1.76790
  Epoch 017 - train 0.63438 | val 1.98532
  Classification -> best τ=0.370 (val F1=0.3202)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.63242 | val 0.84558
  Epoch 017 - train 0.56986 | val 0.89755
  Classification -> best τ=0.480 (val F1=0.1473)
  Directional -> Accuracy: 0.5714, MCC: 0.2466, F1: 0.7073

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.68287 | val 0.77844

[I 2026-02-25 04:18:18,146] Trial 214 finished with value: 0.2800309854492258 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.1, 'dropout': 0.7000000000000001, 'batch_size': 64, 'learning_rate': 0.004889456168666476, 'weight_decay': 0.00020251896876237598, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 0.3095291927371761, 'early_stopping_min_delta': 0.0036051496416191686}. Best is trial 200 with value: 0.303360648585588.

  Epoch 018 - train 0.62698 | val 0.75709
  Classification -> best τ=0.460 (val F1=0.2639)
  Directional -> Accuracy: 0.5574, MCC: 0.1370, F1: 0.6087

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2800309854492258
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.63793 | val 0.66197
  Epoch 020 - train 0.58094 | val 0.77392
  Epoch 024 - train 0.61291 | val 0.66848
  Classification -> best τ=0.620 (val F1=0.2919)
  Directional -> Accuracy: 0.5526, MCC: 0.0174, F1: 0.0556

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.63801 | val 0.70359
  Epoch 017 - train 0.61529 | val 0.74658
  Classification -> best τ=0.470 (val F1=0.1833)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.68288 | val 0.71539
  Epoch 018 - train 0.60613 | val 0.82504
  Classification -> best τ=0.530 (val F1=0.1174)
  Directional -> Accuracy: 0.4894, MCC: 0.0471, F1: 0.2000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.69052 | val 0.71551
  Epoch 018 - train 0.64200 | val 0.79909
  Classification -> best τ=0.530 (val F1=0.1915)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.66025 | val 0.73768
  Epoch 018 - train 0.61220 | val 0.67904
  Classification -> best τ=0.625 (val F1=0.4397)
  Directional -> Accuracy: 0.5490, MCC: 0.1906, F1: 0.3429

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.72457 | val 0.69319
  Epoch 018 - train 0.61141 | val 0.74789
  Classification -> best τ=0.485 (val F1=0.4330)
  Directional -> Accuracy: 0.5319, MCC: 0.1506, F1: 0.0833

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.67393 | val 0.72333
  Epoch 020 - train 0.65340 | val 0.81244
  Epoch 022 - train 0.64479 | val 0.74408
  Classification -> best τ=0.450 (val F1=0.2388)
  Directional -> Accuracy: 0.4348, MCC: 0.0787, F1: 0.5806

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.72091 | val 0.67844
  Epoch 020 - train 0.55232 | val 0.91682
  Classification -> best τ=0.315 (val F1=0.1752)
  Directional -> Accuracy: 0.5581, MCC: -0.0137, F1: 0.1739

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.60888 | val 0.68823
  Epoch 019 - train 0.58764 | val 0.76796
  Classification -> best τ=0.460 (val F1=0.2346)
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.63882 | val 0.85934
  Epoch 017 - train 0.61005 | val 0.96950
  Classification -> best τ=0.465 (val F1=0.2241)
  Directional -> Accuracy: 0.4571, MCC: 0.0389, F1: 0.5870

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.65409 | val 0.97244
  Epoch 020 - train 0.57737 | val 1.08963
  Epoch 021 - train 0.59613 | val 1.26330
  Classification -> best τ=0.530 (val F1=0.3118)
  Directional -> Accuracy: 0.5600, MCC: 0.1048, F1: 0.1538

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.64882 | val 0.69232
  Epoch 020 - train 0.60081 | val 0.84509
  Epoch 023 - train 0.59561 | val 0.77627
  Classification -> best τ=0.710 (val F1=0.2453)
  Directional -> Accuracy: 0.5517, MCC: 0.1588, F1: 0.2778

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.67841 | val 0.68401
  Epoch 020 - train 0.58984 | val 0.81733
  Epoch 025 - train 0.56361 | val 1.04203
  Classification -> best τ=0.520 (val F1=0.2910)
  Directional -> Accuracy: 0.4762, MCC: -0.0478, F1: 0.4500

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.66147 | val 0.69504
  Epoch 019 - train 0.61723 | val 0.83851
  Classification -> best τ=0.325 (val F1=0.3407)
  Directional -> Accuracy: 0.5667, MCC: 0.1383, F1: 0.6176

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.69228 | val 0.74366
  Epoch 020 - train 0.58308 | val 0.77405
  Epoch 024 - train 0.54848 | val 1.15351
  Classification -> best τ=0.625 (val F1=0.2673)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.64851 | val 0.68350
  Epoch 020 - train 0.62851 | val 0.70370
  Classification -> best τ=0.460 (val F1=0.2962)
  Directional -> Accuracy: 0.5797, MCC: 0.1424, F1: 0.6667

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.65215 | val 0.84496
  Epoch 018 - train 0.61772 | val 1.23043
  Classification -> best τ=0.625 (val F1=0.1291)
  Directional -> Accuracy: 0.3898, MCC: 0.1013, F1: 0.0526

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.66254 | val 0.94535
  Epoch 016 - train 0.65172 | val 1.52192
  Classification -> best τ=0.430 (val F1=0.1781)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.64072 | val 1.24531
  Epoch 017 - train 0.60725 | val 1.84485
  Classification -> best τ=0.630 (val F1=0.2234)
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.66334 | val 0.67827
  Epoch 020 - train 0.67691 | val 0.77549
  Epoch 027 - train 0.61641 | val 0.68550
  Classification -> best τ=0.540 (val F1=0.3757)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.65534 | val 0.78442
  Epoch 019 - train 0.61748 | val 0.77015
  Classification -> best τ=0.405 (val F1=0.3278)
  Directional -> Accuracy: 0.5319, MCC: -0.0118, F1: 0.6333

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.68123 | val 0.85689
  Epoch 020 - train 0.60279 | val 1.44152
  Epoch 022 - train 0.63603 | val 1.02108
  Classification -> best τ=0.565 (val F1=0.2093)
  Directional -> Accuracy: 0.5455, MCC: 0.1004, F1: 0.4231

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.65743 | val 0.80285
  Epoch 020 - train 0.65365 | val 0.80583
  Epoch 028 - train 0.60677 | val 0.79695
  Classification -> best τ=0.575 (val F1=0.4174)
  Directional -> Accuracy: 0.5862, MCC: 0.1166, F1: 0.6923

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.67511 | val 0.72456
  Epoch 020 - train 0.60553 | val 0.74638
  Epoch 029 - train 0.59848 | val 1.14554
  Classification -> best τ=0.600 (val F1=0.2390)
  Directional -> Accuracy: 0.4769, MCC: 0.0000, F1: 0.6458

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.66155 | val 0.63818
  Epoch 020 - train 0.61559 | val 0.63638
  Epoch 029 - train 0.55339 | val 0.80302
  Classification -> best τ=0.655 (val F1=0.4124)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.63892 | val 0.69416
  Epoch 020 - train 0.58173 | val 0.73440
  Epoch 024 - train 0.57476 | val 0.78941
  Classification -> best τ=0.495 (val F1=0.3669)
  Directional -> Accuracy: 0.7174, MCC: 0.5505, F1: 0.7547

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.63668 | val 0.68718
  Epoch 020 - train 0.61563 | val 0.68586
  Epoch 030 - train 0.58534 | val 0.70324
  Epoch 040 - train 0.55372 | val 0.67385
  Epoch 041 - train 0.53561 | val 0.67906
  Classification -> best τ=0.535 (val F1=0.2282)
  Directional -> Accuracy: 0.5476, MCC: 0.0829, F1: 0.5957

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.66610 | val 0.67328
  Epoch 019 - train 0.60796 | val 0.76943
  Classification -> best τ=0.400 (val F1=0.2300)
  Directional -> Accuracy: 0.5439, MCC: 0.0737, F1: 0.5938

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.67982 | val 0.72559
  Epoch 020 - train 0.64152 | val 0.66254
  Epoch 030 - train 0.55750 | val 0.89117
  Epoch 035 - train 0.55533 | val 1.24149
  Classification -> best τ=0.570 (val F1=0.4181)
  Directional -> Accuracy: 0.4390, MCC: -0.2107, F1: 0.5818

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.68288 | val 0.84287
  Epoch 017 - train 0.66095 | val 0.83757
  Classification -> best τ=0.540 (val F1=0.2814)
  Directional -> Accuracy: 0.5349, MCC: 0.0716, F1: 0.5455

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.71299 | val 0.75882
  Epoch 019 - train 0.61357 | val 0.92371
  Classification -> best τ=0.585 (val F1=0.1886)
  Directional -> Accuracy: 0.5349, MCC: 0.0435, F1: 0.6296

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.63514 | val 0.72916
  Epoch 019 - train 0.60532 | val 1.24888
  Classification -> best τ=0.450 (val F1=0.2368)
  Directional -> Accuracy: 0.4400, MCC: -0.1143, F1: 0.4400

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.65070 | val 0.72356
  Epoch 020 - train 0.61640 | val 0.72997
  Epoch 023 - train 0.63467 | val 0.70175
  Classification -> best τ=0.405 (val F1=0.3602)
  Directional -> Accuracy: 0.5616, MCC: 0.1446, F1: 0.5556

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.67321 | val 0.70676
  Epoch 018 - train 0.59950 | val 0.95407
  Classification -> best τ=0.475 (val F1=0.2390)
  Directional -> Accuracy: 0.4865, MCC: -0.0065, F1: 0.6415

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.74314 | val 0.77106
  Epoch 020 - train 0.64680 | val 0.79823
  Epoch 027 - train 0.62407 | val 0.85030
  Classification -> best τ=0.595 (val F1=0.1749)
  Directional -> Accuracy: 0.5000, MCC: -0.1457, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.66067 | val 0.68515
  Epoch 018 - train 0.65186 | val 0.84661
  Classification -> best τ=0.375 (val F1=0.3525)
  Directional -> Accuracy: 0.5758, MCC: 0.1236, F1: 0.6410

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.62005 | val 0.71206
  Epoch 020 - train 0.53312 | val 0.73544
  Classification -> best τ=0.585 (val F1=0.3300)
  Directional -> Accuracy: 0.5000, MCC: 0.1489, F1: 0.0870

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.68169 | val 0.68099
  Epoch 020 - train 0.62515 | val 0.68528
  Classification -> best τ=0.410 (val F1=0.2622)
  Directional -> Accuracy: 0.4821, MCC: 0.0625, F1: 0.6329

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.63842 | val 0.81445
  Epoch 016 - train 0.57592 | val 0.77141
  Classification -> best τ=0.450 (val F1=0.3679)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.74704 | val 0.65909
  Epoch 020 - train 0.67203 | val 0.75657
  Epoch 022 - train 0.58849 | val 0.79180
  Classification -> best τ=0.490 (val F1=0.4141)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.63604 | val 0.90737
  Epoch 018 - train 0.55272 | val 0.85058
  Classification -> best τ=0.530 (val F1=0.3019)
  Directional -> Accuracy: 0.5405, MCC: 0.1684, F1: 0.3704

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.65928 | val 0.65389
  Epoch 020 - train 0.60328 | val 1.22731
  Epoch 022 - train 0.61652 | val 1.23907
  Classification -> best τ=0.355 (val F1=0.3466)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.71347 | val 0.67940
  Epoch 017 - train 0.63469 | val 0.68243
  Classification -> best τ=0.490 (val F1=0.3560)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.0000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.63663 | val 0.68928
  Epoch 020 - train 0.58200 | val 0.74082
  Epoch 027 - train 0.54859 | val 0.72546
  Classification -> best τ=0.565 (val F1=0.6250)
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.7164

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.80781 | val 0.62511
  Epoch 020 - train 0.65514 | val 0.82890
  Epoch 025 - train 0.58147 | val 0.69773
  Classification -> best τ=0.575 (val F1=0.6290)
  Directional -> Accuracy: 0.3878, MCC: -0.0687, F1: 0.5312

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.65418 | val 0.90769
  Epoch 018 - train 0.62183 | val 1.82308
  Classification -> best τ=0.515 (val F1=0.3371)
  Directional -> Accuracy: 0.5357, MCC: 0.1536, F1: 0.3500

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.74476 | val 0.71858
  Epoch 020 - train 0.62533 | val 1.31921
  Epoch 021 - train 0.63324 | val 1.46822
  Classification -> best τ=0.600 (val F1=0.4300)
  Directional -> Accuracy: 0.5357, MCC: 0.1303, F1: 0.6486

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.66486 | val 0.95129
  Epoch 018 - train 0.67494 | val 1.22516
  Classification -> best τ=0.365 (val F1=0.2325)
  Directional -> Accuracy: 0.5741, MCC: 0.2517, F1: 0.7089

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.62997 | val 0.80041
  Epoch 020 - train 0.59284 | val 0.74090
  Epoch 024 - train 0.61249 | val 0.79249
  Classification -> best τ=0.525 (val F1=0.0259)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.66491 | val 0.71578

[I 2026-02-25 04:20:28,160] Trial 215 finished with value: 0.29727784411961833 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 64, 'learning_rate': 0.0065616559168718835, 'weight_decay': 0.0004183188972057029, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 0.1446883269079247, 'early_stopping_min_delta': 0.0032155499793543618}. Best is trial 200 with value: 0.303360648585588.

  Epoch 019 - train 0.61694 | val 0.95036
  Classification -> best τ=0.430 (val F1=0.3349)
  Directional -> Accuracy: 0.5574, MCC: 0.1088, F1: 0.5091

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.29727784411961833
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.66174 | val 0.65041
  Epoch 020 - train 0.61188 | val 0.85737
  Epoch 025 - train 0.58308 | val 0.78029
  Classification -> best τ=0.570 (val F1=0.2510)
  Directional -> Accuracy: 0.5395, MCC: -0.0120, F1: 0.1463

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.63284 | val 0.71181
  Epoch 016 - train 0.61448 | val 0.69504
  Classification -> best τ=0.405 (val F1=0.2707)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.67123 | val 0.72172
  Epoch 018 - train 0.64076 | val 0.75803
  Classification -> best τ=0.580 (val F1=0.3237)
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.66457 | val 0.82104
  Epoch 018 - train 0.67520 | val 0.69702
  Classification -> best τ=0.610 (val F1=0.1590)
  Directional -> Accuracy: 0.4667, MCC: 0.1059, F1: 0.0476

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.67216 | val 0.67041
  Epoch 020 - train 0.56233 | val 0.68350
  Epoch 028 - train 0.55621 | val 0.70716
  Classification -> best τ=0.580 (val F1=0.4513)
  Directional -> Accuracy: 0.4510, MCC: -0.1136, F1: 0.5172

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.64054 | val 0.69804
  Epoch 017 - train 0.68369 | val 0.69906
  Classification -> best τ=0.515 (val F1=0.2887)
  Directional -> Accuracy: 0.4894, MCC: -0.0509, F1: 0.2000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.70010 | val 0.68183
  Epoch 020 - train 0.66337 | val 0.79783
  Epoch 024 - train 0.64911 | val 0.76787
  Classification -> best τ=0.480 (val F1=0.2732)
  Directional -> Accuracy: 0.5217, MCC: 0.1549, F1: 0.5823

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.65709 | val 0.67378
  Epoch 020 - train 0.56175 | val 0.75650
  Epoch 021 - train 0.59780 | val 0.85074
  Classification -> best τ=0.340 (val F1=0.1502)
  Directional -> Accuracy: 0.5349, MCC: -0.1874, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.64357 | val 0.73652
  Epoch 018 - train 0.57557 | val 1.04558
  Classification -> best τ=0.450 (val F1=0.4232)
  Directional -> Accuracy: 0.5510, MCC: 0.0852, F1: 0.4762

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.65299 | val 0.72121
  Epoch 019 - train 0.63711 | val 0.80062
  Classification -> best τ=0.545 (val F1=0.1620)
  Directional -> Accuracy: 0.5143, MCC: -0.1296, F1: 0.1053

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.67004 | val 0.89992
  Epoch 019 - train 0.62183 | val 1.22754
  Classification -> best τ=0.495 (val F1=0.4942)
  Directional -> Accuracy: 0.5800, MCC: 0.1438, F1: 0.4878

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.64290 | val 0.76463
  Epoch 020 - train 0.56583 | val 1.06273
  Classification -> best τ=0.415 (val F1=0.2591)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.66063 | val 0.71489
  Epoch 020 - train 0.57421 | val 0.69369
  Epoch 030 - train 0.50344 | val 0.96172
  Epoch 031 - train 0.53522 | val 0.95658
  Classification -> best τ=0.450 (val F1=0.2392)
  Directional -> Accuracy: 0.5476, MCC: 0.1003, F1: 0.5366

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.67067 | val 0.62442
  Epoch 020 - train 0.63073 | val 0.75618
  Epoch 024 - train 0.63765 | val 0.64537
  Classification -> best τ=0.285 (val F1=0.3083)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.64658 | val 0.72183
  Epoch 019 - train 0.61664 | val 0.83334
  Classification -> best τ=0.505 (val F1=0.2673)
  Directional -> Accuracy: 0.5769, MCC: 0.1670, F1: 0.2143

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.66358 | val 0.72885
  Epoch 017 - train 0.64954 | val 0.70157
  Classification -> best τ=0.715 (val F1=0.4344)
  Directional -> Accuracy: 0.5217, MCC: 0.0405, F1: 0.5479

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.64354 | val 1.03498
  Epoch 019 - train 0.61947 | val 1.21307
  Classification -> best τ=0.680 (val F1=0.1842)
  Directional -> Accuracy: 0.4068, MCC: 0.1444, F1: 0.1026

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.66934 | val 0.79872
  Epoch 018 - train 0.63303 | val 1.38225
  Classification -> best τ=0.515 (val F1=0.1109)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.66521 | val 0.85096
  Epoch 020 - train 0.64245 | val 1.60587
  Epoch 022 - train 0.64414 | val 1.66661
  Classification -> best τ=0.750 (val F1=0.2234)
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.67764 | val 0.67323
  Epoch 020 - train 0.66204 | val 0.67472
  Epoch 024 - train 0.62487 | val 0.69481
  Classification -> best τ=0.455 (val F1=0.3499)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.65542 | val 0.73761
  Epoch 020 - train 0.58860 | val 1.14600
  Epoch 023 - train 0.52737 | val 1.42577
  Classification -> best τ=0.450 (val F1=0.3307)
  Directional -> Accuracy: 0.5106, MCC: 0.0805, F1: 0.5106

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.66739 | val 0.73304
  Epoch 019 - train 0.66369 | val 0.77438
  Classification -> best τ=0.460 (val F1=0.1608)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6598

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.64843 | val 0.80146
  Epoch 016 - train 0.63789 | val 0.82725
  Classification -> best τ=0.555 (val F1=0.2379)
  Directional -> Accuracy: 0.5517, MCC: 0.0601, F1: 0.6389

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.67872 | val 0.69641
  Epoch 017 - train 0.62511 | val 0.70125
  Classification -> best τ=0.530 (val F1=0.1936)
  Directional -> Accuracy: 0.5231, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.63638 | val 0.63710
  Epoch 020 - train 0.59578 | val 0.64073
  Epoch 024 - train 0.58246 | val 0.80596
  Classification -> best τ=0.475 (val F1=0.3824)
  Directional -> Accuracy: 0.5714, MCC: 0.2952, F1: 0.4000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.63042 | val 0.69629
  Epoch 020 - train 0.64882 | val 0.80202
  Epoch 025 - train 0.59158 | val 1.09286
  Classification -> best τ=0.415 (val F1=0.2935)
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.71694 | val 0.72965
  Epoch 020 - train 0.63605 | val 0.72460
  Epoch 021 - train 0.63633 | val 0.70456
  Classification -> best τ=0.610 (val F1=0.1353)
  Directional -> Accuracy: 0.4762, MCC: 0.0152, F1: 0.3889

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.68123 | val 0.66464
  Epoch 020 - train 0.61193 | val 0.74287
  Epoch 028 - train 0.58849 | val 0.81530
  Classification -> best τ=0.335 (val F1=0.2766)
  Directional -> Accuracy: 0.6316, MCC: 0.2362, F1: 0.7042

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.72959 | val 0.67946
  Epoch 020 - train 0.63580 | val 0.81863
  Classification -> best τ=0.510 (val F1=0.4109)
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.66820 | val 0.70481
  Epoch 017 - train 0.67532 | val 0.70592
  Classification -> best τ=0.540 (val F1=0.2814)
  Directional -> Accuracy: 0.5116, MCC: 0.0288, F1: 0.5532

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.69085 | val 0.68165
  Epoch 020 - train 0.56955 | val 0.68569
  Epoch 021 - train 0.57878 | val 0.66290
  Classification -> best τ=0.520 (val F1=0.2517)
  Directional -> Accuracy: 0.5581, MCC: 0.0981, F1: 0.6885

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.60654 | val 0.70945
  Epoch 016 - train 0.59345 | val 0.81078
  Classification -> best τ=0.440 (val F1=0.3142)
  Directional -> Accuracy: 0.5400, MCC: 0.1070, F1: 0.4889

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.68266 | val 0.67792
  Epoch 019 - train 0.65647 | val 0.70660
  Classification -> best τ=0.350 (val F1=0.3918)
  Directional -> Accuracy: 0.5479, MCC: 0.1382, F1: 0.5075

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.61507 | val 0.79229
  Epoch 019 - train 0.67324 | val 0.87343
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.68645 | val 0.80618
  Epoch 016 - train 0.65327 | val 0.83974
  Classification -> best τ=0.485 (val F1=0.3121)
  Directional -> Accuracy: 0.4773, MCC: -0.0214, F1: 0.5965

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.65863 | val 0.67329
  Epoch 020 - train 0.61475 | val 0.82349
  Epoch 025 - train 0.61076 | val 0.87263
  Classification -> best τ=0.315 (val F1=0.3787)
  Directional -> Accuracy: 0.4848, MCC: 0.0867, F1: 0.3200

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.62285 | val 0.77846
  Epoch 017 - train 0.55727 | val 0.77822
  Classification -> best τ=0.425 (val F1=0.2933)
  Directional -> Accuracy: 0.5714, MCC: 0.1386, F1: 0.6667

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.65492 | val 0.67270
  Epoch 020 - train 0.62052 | val 0.84968
  Classification -> best τ=0.445 (val F1=0.2946)
  Directional -> Accuracy: 0.4107, MCC: -0.1690, F1: 0.4407

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.60607 | val 0.68054
  Epoch 020 - train 0.55042 | val 0.80210
  Epoch 029 - train 0.51880 | val 0.99436
  Classification -> best τ=0.680 (val F1=0.3372)
  Directional -> Accuracy: 0.4565, MCC: -0.0124, F1: 0.4186

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.68158 | val 0.72000
  Epoch 020 - train 0.60441 | val 0.66874
  Epoch 030 - train 0.58180 | val 0.60797
  Epoch 040 - train 0.55474 | val 0.77791
  Epoch 043 - train 0.55064 | val 0.61206
  Classification -> best τ=0.335 (val F1=0.5617)
  Directional -> Accuracy: 0.3469, MCC: -0.1894, F1: 0.5152

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.75668 | val 0.87780
  Epoch 016 - train 0.65130 | val 0.79790
  Classification -> best τ=0.470 (val F1=0.3545)
  Directional -> Accuracy: 0.5676, MCC: 0.1602, F1: 0.5294

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.64532 | val 0.72666
  Epoch 020 - train 0.59022 | val 1.09653
  Epoch 021 - train 0.60232 | val 1.26697
  Classification -> best τ=0.405 (val F1=0.3339)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.65650 | val 0.68919
  Epoch 017 - train 0.63453 | val 0.67386
  Classification -> best τ=0.430 (val F1=0.4315)
  Directional -> Accuracy: 0.4565, MCC: -0.0851, F1: 0.1379

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.65631 | val 0.65408
  Epoch 020 - train 0.57453 | val 0.78738
  Epoch 024 - train 0.53995 | val 0.94026
  Classification -> best τ=0.545 (val F1=0.5270)
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.7164

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.70788 | val 0.67313
  Epoch 020 - train 0.60193 | val 0.75326
  Epoch 022 - train 0.64316 | val 0.72316
  Classification -> best τ=0.555 (val F1=0.5514)
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.69215 | val 1.00202
  Epoch 020 - train 0.60839 | val 1.91575
  Epoch 021 - train 0.62805 | val 1.88390
  Classification -> best τ=0.470 (val F1=0.2194)
  Directional -> Accuracy: 0.5536, MCC: 0.2915, F1: 0.2857

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.67602 | val 0.95615
  Epoch 018 - train 0.64821 | val 1.22536
  Classification -> best τ=0.565 (val F1=0.3535)
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.67198 | val 1.17096
  Epoch 017 - train 0.63468 | val 2.02700
  Classification -> best τ=0.455 (val F1=0.3015)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.65296 | val 0.85910
  Epoch 020 - train 0.64114 | val 0.79463
  Epoch 022 - train 0.63196 | val 0.89053
  Classification -> best τ=0.545 (val F1=0.1164)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.67095 | val 0.69836

[I 2026-02-25 04:22:35,173] Trial 216 finished with value: 0.29603352315473996 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 64, 'learning_rate': 0.007098818707741073, 'weight_decay': 0.00044699991028935025, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 0.11498532848792797, 'early_stopping_min_delta': 0.003231974028736825}. Best is trial 200 with value: 0.303360648585588.

  Epoch 018 - train 0.65203 | val 0.87214
  Classification -> best τ=0.475 (val F1=0.1502)
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.29603352315473996
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.63151 | val 0.73077
  Epoch 017 - train 0.64990 | val 0.69000
  Classification -> best τ=0.425 (val F1=0.2523)
  Directional -> Accuracy: 0.3947, MCC: -0.2697, F1: 0.2069

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.66806 | val 0.68390
  Epoch 017 - train 0.64934 | val 0.71012
  Classification -> best τ=0.450 (val F1=0.2802)
  Directional -> Accuracy: 0.5778, MCC: 0.0340, F1: 0.7246

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.67077 | val 0.67077
  Epoch 020 - train 0.60678 | val 0.67841
  Epoch 030 - train 0.53951 | val 0.87602
  Epoch 034 - train 0.52272 | val 0.96015
  Classification -> best τ=0.585 (val F1=0.3835)
  Directional -> Accuracy: 0.5106, MCC: 0.1333, F1: 0.2069

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.67726 | val 0.72823
  Epoch 020 - train 0.65205 | val 0.75006
  Epoch 030 - train 0.65076 | val 0.78077
  Epoch 032 - train 0.64802 | val 0.75875
  Classification -> best τ=0.475 (val F1=0.2316)
  Directional -> Accuracy: 0.4800, MCC: 0.1507, F1: 0.0930

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.64732 | val 0.63966
  Epoch 020 - train 0.57336 | val 0.66220
  Epoch 023 - train 0.55025 | val 0.66434
  Classification -> best τ=0.575 (val F1=0.5279)
  Directional -> Accuracy: 0.5882, MCC: 0.2451, F1: 0.4615

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.70742 | val 0.69848
  Epoch 016 - train 0.64564 | val 0.76320
  Classification -> best τ=0.500 (val F1=0.2357)
  Directional -> Accuracy: 0.4894, MCC: 0.0000, F1: 0.6571

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.67641 | val 0.67718
  Epoch 020 - train 0.66677 | val 0.68308
  Epoch 025 - train 0.65419 | val 0.80220
  Classification -> best τ=0.530 (val F1=0.2605)
  Directional -> Accuracy: 0.5072, MCC: 0.0459, F1: 0.5000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.61928 | val 0.61765
  Epoch 020 - train 0.51451 | val 0.74421
  Classification -> best τ=0.370 (val F1=0.1052)
  Directional -> Accuracy: 0.5581, MCC: 0.0573, F1: 0.3871

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.63694 | val 0.71013
  Epoch 018 - train 0.60009 | val 0.74356
  Classification -> best τ=0.440 (val F1=0.2218)
  Directional -> Accuracy: 0.6327, MCC: 0.3303, F1: 0.3077

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.65767 | val 0.71574
  Epoch 016 - train 0.60440 | val 0.70847
  Classification -> best τ=0.555 (val F1=0.1733)
  Directional -> Accuracy: 0.5286, MCC: 0.0661, F1: 0.5075

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.69782 | val 0.72564
  Epoch 017 - train 0.65660 | val 0.69403
  Classification -> best τ=0.385 (val F1=0.3094)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.63353 | val 1.26161
  Epoch 019 - train 0.60563 | val 1.21106
  Classification -> best τ=0.505 (val F1=0.2587)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.62730 | val 0.88883
  Epoch 017 - train 0.57382 | val 1.26534
  Classification -> best τ=0.470 (val F1=0.2304)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.67654 | val 0.76717
  Epoch 020 - train 0.64522 | val 0.74871
  Epoch 023 - train 0.62224 | val 0.78538
  Classification -> best τ=0.355 (val F1=0.3083)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.64084 | val 0.69432
  Epoch 018 - train 0.60670 | val 0.70066
  Classification -> best τ=0.505 (val F1=0.2673)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.69803 | val 0.81882
  Epoch 017 - train 0.60278 | val 0.78572
  Classification -> best τ=0.660 (val F1=0.2916)
  Directional -> Accuracy: 0.5652, MCC: 0.1165, F1: 0.6250

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.66739 | val 0.83398
  Epoch 019 - train 0.64417 | val 0.83111
  Classification -> best τ=0.675 (val F1=0.2651)
  Directional -> Accuracy: 0.3729, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.66949 | val 0.82715
  Epoch 018 - train 0.66046 | val 1.13202
  Classification -> best τ=0.345 (val F1=0.1565)
  Directional -> Accuracy: 0.4800, MCC: 0.1940, F1: 0.2642

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.65806 | val 0.76542
  Epoch 016 - train 0.66325 | val 0.77340
  Classification -> best τ=0.375 (val F1=0.2166)
  Directional -> Accuracy: 0.5077, MCC: 0.1597, F1: 0.3600

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.67058 | val 0.67095
  Epoch 020 - train 0.67290 | val 0.66540
  Epoch 030 - train 0.65518 | val 0.66594
  Epoch 038 - train 0.58057 | val 0.67386
  Classification -> best τ=0.450 (val F1=0.3234)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.67822 | val 0.70949
  Epoch 019 - train 0.61114 | val 0.71733
  Classification -> best τ=0.470 (val F1=0.2338)
  Directional -> Accuracy: 0.5106, MCC: 0.0373, F1: 0.5490

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.69358 | val 0.78462
  Epoch 016 - train 0.66299 | val 0.94698
  Classification -> best τ=0.540 (val F1=0.1318)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0571

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.65518 | val 0.68445
  Epoch 020 - train 0.61726 | val 0.69108
  Epoch 024 - train 0.61116 | val 0.83016
  Classification -> best τ=0.625 (val F1=0.3231)
  Directional -> Accuracy: 0.5517, MCC: 0.1960, F1: 0.4583

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.65396 | val 0.69334
  Epoch 017 - train 0.64115 | val 0.73649
  Classification -> best τ=0.485 (val F1=0.0594)
  Directional -> Accuracy: 0.4769, MCC: 0.0000, F1: 0.6458

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.65958 | val 0.67064
  Epoch 020 - train 0.52862 | val 0.82581
  Epoch 024 - train 0.48182 | val 1.07937
  Classification -> best τ=0.390 (val F1=0.3482)
  Directional -> Accuracy: 0.4643, MCC: -0.0757, F1: 0.5000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.68018 | val 0.80305
  Epoch 017 - train 0.59877 | val 0.79011
  Classification -> best τ=0.480 (val F1=0.1383)
  Directional -> Accuracy: 0.5870, MCC: 0.1700, F1: 0.0952

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.69163 | val 0.68886
  Epoch 020 - train 0.57423 | val 0.70517
  Epoch 026 - train 0.58697 | val 0.68201
  Classification -> best τ=0.560 (val F1=0.0913)
  Directional -> Accuracy: 0.4762, MCC: -0.1217, F1: 0.5926

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.65680 | val 0.72227
  Epoch 019 - train 0.58530 | val 0.82931
  Classification -> best τ=0.280 (val F1=0.2260)
  Directional -> Accuracy: 0.6140, MCC: 0.1949, F1: 0.7179

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.68612 | val 0.68651
  Epoch 020 - train 0.61810 | val 0.79854
  Epoch 030 - train 0.56486 | val 1.10515
  Classification -> best τ=0.550 (val F1=0.4139)
  Directional -> Accuracy: 0.6098, MCC: 0.2162, F1: 0.7037

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.65365 | val 1.00252
  Epoch 016 - train 0.64362 | val 1.68110
  Classification -> best τ=0.510 (val F1=0.3398)
  Directional -> Accuracy: 0.5349, MCC: 0.0973, F1: 0.6296

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.68674 | val 0.70226
  Epoch 020 - train 0.56375 | val 0.68963
  Epoch 030 - train 0.50893 | val 0.65790
  Epoch 038 - train 0.45337 | val 0.70399
  Classification -> best τ=0.695 (val F1=0.2321)
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.61946 | val 1.01774
  Epoch 020 - train 0.61410 | val 1.37181
  Epoch 023 - train 0.53985 | val 1.54920
  Classification -> best τ=0.370 (val F1=0.3356)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.65615 | val 0.68677
  Epoch 017 - train 0.61774 | val 0.73108
  Classification -> best τ=0.425 (val F1=0.2640)
  Directional -> Accuracy: 0.5616, MCC: 0.1446, F1: 0.5556

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.64471 | val 0.75806
  Epoch 016 - train 0.61253 | val 0.84917
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.65772 | val 0.78010
  Epoch 016 - train 0.65320 | val 0.84771
  Classification -> best τ=0.460 (val F1=0.2537)
  Directional -> Accuracy: 0.5455, MCC: 0.0807, F1: 0.4444

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.68819 | val 0.70084
  Epoch 020 - train 0.63854 | val 0.74400
  Epoch 022 - train 0.60790 | val 0.74683
  Classification -> best τ=0.445 (val F1=0.3254)
  Directional -> Accuracy: 0.5758, MCC: 0.1316, F1: 0.6316

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.62963 | val 0.84095
  Epoch 016 - train 0.60872 | val 0.90175
  Classification -> best τ=0.460 (val F1=0.2819)
  Directional -> Accuracy: 0.7143, MCC: 0.4266, F1: 0.7391

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.65739 | val 0.68764
  Epoch 017 - train 0.63623 | val 0.73679
  Classification -> best τ=0.560 (val F1=0.2305)
  Directional -> Accuracy: 0.5179, MCC: 0.0185, F1: 0.4255

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.62527 | val 0.95628
  Epoch 018 - train 0.51939 | val 1.30405
  Classification -> best τ=0.475 (val F1=0.2185)
  Directional -> Accuracy: 0.3913, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.69288 | val 0.70084
  Epoch 020 - train 0.62502 | val 0.72833
  Epoch 027 - train 0.59452 | val 0.75357
  Classification -> best τ=0.385 (val F1=0.3182)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.68962 | val 0.74152
  Epoch 020 - train 0.56374 | val 0.70671
  Epoch 030 - train 0.55561 | val 0.78226
  Epoch 031 - train 0.46498 | val 0.84777
  Classification -> best τ=0.645 (val F1=0.4776)
  Directional -> Accuracy: 0.5405, MCC: 0.1251, F1: 0.4516

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.64920 | val 0.68282
  Epoch 017 - train 0.61307 | val 0.71103
  Classification -> best τ=0.575 (val F1=0.3496)
  Directional -> Accuracy: 0.5867, MCC: 0.2406, F1: 0.3404

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.66858 | val 0.68374
  Epoch 018 - train 0.58323 | val 0.76145
  Classification -> best τ=0.385 (val F1=0.3994)
  Directional -> Accuracy: 0.5652, MCC: 0.1679, F1: 0.6970

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.64795 | val 0.80948
  Epoch 020 - train 0.69816 | val 0.75903
  Classification -> best τ=0.525 (val F1=0.2331)
  Directional -> Accuracy: 0.5116, MCC: -0.0880, F1: 0.6557

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.64742 | val 0.79912
  Epoch 020 - train 0.62596 | val 0.65800
  Epoch 021 - train 0.58819 | val 0.66219
  Classification -> best τ=0.510 (val F1=0.5557)
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.66886 | val 0.96306
  Epoch 018 - train 0.62416 | val 1.10403
  Classification -> best τ=0.445 (val F1=0.0290)
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.66619 | val 0.94514
  Epoch 017 - train 0.60338 | val 1.73002
  Classification -> best τ=0.575 (val F1=0.3119)
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.63133 | val 1.03308
  Epoch 017 - train 0.60852 | val 1.09463
  Classification -> best τ=0.500 (val F1=0.1139)
  Directional -> Accuracy: 0.5741, MCC: 0.1459, F1: 0.5965

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.64745 | val 0.80119
  Epoch 020 - train 0.64107 | val 0.74677
  Classification -> best τ=0.515 (val F1=0.1168)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.65618 | val 0.89825

[I 2026-02-25 04:23:43,463] Trial 217 finished with value: 0.25872789455589623 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 64, 'learning_rate': 0.006862133804555519, 'weight_decay': 0.00044976636432799994, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 0.11898020745150913, 'early_stopping_min_delta': 0.003196062282893116}. Best is trial 200 with value: 0.303360648585588.

  Epoch 020 - train 0.60282 | val 0.85149
  Epoch 021 - train 0.57602 | val 0.84261
  Classification -> best τ=0.450 (val F1=0.2847)
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.25872789455589623
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.66139 | val 0.67753
  Epoch 017 - train 0.61192 | val 0.82501
  Classification -> best τ=0.535 (val F1=0.2510)
  Directional -> Accuracy: 0.6184, MCC: 0.2435, F1: 0.3256

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.65943 | val 0.69696
  Epoch 020 - train 0.61469 | val 0.71964
  Epoch 023 - train 0.60362 | val 0.71923
  Classification -> best τ=0.465 (val F1=0.2918)
  Directional -> Accuracy: 0.6444, MCC: 0.3126, F1: 0.7647

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.70105 | val 0.69950
  Epoch 017 - train 0.65151 | val 0.82701
  Classification -> best τ=0.510 (val F1=0.1737)
  Directional -> Accuracy: 0.4681, MCC: -0.0333, F1: 0.2857

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.67984 | val 0.72874
  Epoch 018 - train 0.66151 | val 0.74923
  Classification -> best τ=0.480 (val F1=0.1473)
  Directional -> Accuracy: 0.5333, MCC: -0.0286, F1: 0.6847

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.63281 | val 0.67504
  Epoch 020 - train 0.59378 | val 0.66325
  Epoch 023 - train 0.58288 | val 0.66987
  Classification -> best τ=0.605 (val F1=0.4539)
  Directional -> Accuracy: 0.4706, MCC: -0.0556, F1: 0.4706

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.63632 | val 0.72661
  Epoch 018 - train 0.59168 | val 0.71856
  Classification -> best τ=0.530 (val F1=0.1715)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.67045 | val 0.69579
  Epoch 020 - train 0.65850 | val 0.71910
  Classification -> best τ=0.555 (val F1=0.2301)
  Directional -> Accuracy: 0.5652, MCC: 0.0781, F1: 0.4231

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.61622 | val 0.69892
  Epoch 020 - train 0.61017 | val 0.77773
  Epoch 021 - train 0.58759 | val 0.80925
  Classification -> best τ=0.300 (val F1=0.1590)
  Directional -> Accuracy: 0.5349, MCC: -0.0696, F1: 0.1667

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.67877 | val 0.76582
  Epoch 017 - train 0.60838 | val 0.73423
  Classification -> best τ=0.510 (val F1=0.2788)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.63944 | val 0.69475
  Epoch 016 - train 0.66024 | val 0.75620
  Classification -> best τ=0.510 (val F1=0.0828)
  Directional -> Accuracy: 0.4286, MCC: -0.0518, F1: 0.5652

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.66252 | val 0.78162
  Epoch 018 - train 0.63754 | val 1.43578
  Classification -> best τ=0.405 (val F1=0.2562)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.64675 | val 0.94350
  Epoch 016 - train 0.57448 | val 1.34456
  Classification -> best τ=0.500 (val F1=0.2105)
  Directional -> Accuracy: 0.5862, MCC: 0.3071, F1: 0.2941

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.59559 | val 0.71252
  Epoch 016 - train 0.60173 | val 0.80602
  Classification -> best τ=0.455 (val F1=0.2323)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.70246 | val 0.65036
  Epoch 020 - train 0.63659 | val 0.62843
  Epoch 030 - train 0.59652 | val 0.66378
  Epoch 033 - train 0.59706 | val 1.21617
  Classification -> best τ=0.350 (val F1=0.2911)
  Directional -> Accuracy: 0.4667, MCC: -0.1857, F1: 0.6364

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.66023 | val 0.71591
  Epoch 019 - train 0.62388 | val 1.05683
  Classification -> best τ=0.525 (val F1=0.2160)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.63295 | val 0.72501
  Epoch 019 - train 0.60522 | val 0.82792
  Classification -> best τ=0.565 (val F1=0.3170)
  Directional -> Accuracy: 0.5072, MCC: 0.1013, F1: 0.2609

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.66113 | val 1.04835
  Epoch 017 - train 0.65401 | val 1.16342
  Classification -> best τ=0.485 (val F1=0.2186)
  Directional -> Accuracy: 0.4407, MCC: 0.0413, F1: 0.3265

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.67493 | val 0.92728
  Epoch 019 - train 0.63194 | val 0.86325
  Classification -> best τ=0.445 (val F1=0.2388)
  Directional -> Accuracy: 0.4933, MCC: 0.2178, F1: 0.2963

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.63571 | val 0.86015
  Epoch 016 - train 0.62987 | val 1.40718
  Classification -> best τ=0.420 (val F1=0.3057)
  Directional -> Accuracy: 0.6000, MCC: 0.2168, F1: 0.6176

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.69628 | val 0.66997
  Epoch 020 - train 0.64841 | val 0.69599
  Epoch 024 - train 0.63040 | val 0.71720
  Classification -> best τ=0.480 (val F1=0.3581)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.65919 | val 0.72146
  Epoch 018 - train 0.61537 | val 0.73818
  Classification -> best τ=0.440 (val F1=0.3278)
  Directional -> Accuracy: 0.5106, MCC: -0.0699, F1: 0.6230

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.67140 | val 0.88362
  Epoch 017 - train 0.71213 | val 0.83079
  Classification -> best τ=0.580 (val F1=0.1688)
  Directional -> Accuracy: 0.5455, MCC: 0.1325, F1: 0.2857

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.67879 | val 0.72826
  Epoch 020 - train 0.66335 | val 0.76241
  Epoch 022 - train 0.63895 | val 0.77399
  Classification -> best τ=0.635 (val F1=0.3864)
  Directional -> Accuracy: 0.5172, MCC: 0.1339, F1: 0.3913

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.70437 | val 0.69404
  Epoch 020 - train 0.64926 | val 0.70919
  Epoch 026 - train 0.58572 | val 0.84089
  Classification -> best τ=0.515 (val F1=0.2390)
  Directional -> Accuracy: 0.5231, MCC: 0.0669, F1: 0.5867

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.69670 | val 0.62563
  Epoch 020 - train 0.65176 | val 0.80057
  Epoch 025 - train 0.58581 | val 0.81051
  Classification -> best τ=0.400 (val F1=0.4045)
  Directional -> Accuracy: 0.5714, MCC: 0.1656, F1: 0.5556

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.69561 | val 0.71447
  Epoch 017 - train 0.65834 | val 0.86851
  Classification -> best τ=0.440 (val F1=0.2935)
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.64306 | val 0.71629
  Epoch 017 - train 0.64390 | val 0.69719
  Classification -> best τ=0.575 (val F1=0.1353)
  Directional -> Accuracy: 0.4762, MCC: 0.0152, F1: 0.3889

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.63819 | val 0.70421
  Epoch 017 - train 0.64935 | val 0.68302
  Classification -> best τ=0.495 (val F1=0.1644)
  Directional -> Accuracy: 0.4737, MCC: 0.1685, F1: 0.1176

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.73819 | val 0.67145
  Epoch 020 - train 0.64822 | val 0.67212
  Epoch 030 - train 0.59043 | val 0.75600
  Epoch 037 - train 0.53238 | val 1.28190
  Classification -> best τ=0.485 (val F1=0.4109)
  Directional -> Accuracy: 0.5122, MCC: -0.1469, F1: 0.6774

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.72995 | val 0.82090
  Epoch 018 - train 0.57899 | val 1.04382
  Classification -> best τ=0.555 (val F1=0.2814)
  Directional -> Accuracy: 0.4884, MCC: -0.0179, F1: 0.5417

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.70360 | val 0.64882
  Epoch 020 - train 0.60766 | val 0.65565
  Epoch 029 - train 0.50812 | val 0.63711
  Classification -> best τ=0.750 (val F1=0.2151)
  Directional -> Accuracy: 0.4419, MCC: -0.0981, F1: 0.1429

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.64315 | val 0.74695
  Epoch 020 - train 0.57022 | val 0.93749
  Epoch 023 - train 0.55606 | val 0.80185
  Classification -> best τ=0.415 (val F1=0.3069)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.66068 | val 0.69854
  Epoch 020 - train 0.64495 | val 0.69295
  Epoch 027 - train 0.63330 | val 0.84599
  Classification -> best τ=0.370 (val F1=0.3354)
  Directional -> Accuracy: 0.5342, MCC: 0.1050, F1: 0.5000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.66230 | val 0.79254
  Epoch 016 - train 0.53543 | val 0.78334
  Classification -> best τ=0.450 (val F1=0.4303)
  Directional -> Accuracy: 0.5405, MCC: 0.0904, F1: 0.5854

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.66322 | val 0.84061
  Epoch 017 - train 0.65819 | val 0.78967
  Classification -> best τ=0.445 (val F1=0.3121)
  Directional -> Accuracy: 0.6364, MCC: 0.2818, F1: 0.6522

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.64306 | val 0.68152
  Epoch 020 - train 0.65896 | val 0.74955
  Classification -> best τ=0.440 (val F1=0.3525)
  Directional -> Accuracy: 0.5606, MCC: 0.0466, F1: 0.6742

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.71117 | val 0.74165
  Epoch 017 - train 0.53802 | val 0.75603
  Classification -> best τ=0.480 (val F1=0.3343)
  Directional -> Accuracy: 0.5714, MCC: 0.1779, F1: 0.7000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.66171 | val 0.66991
  Epoch 020 - train 0.63648 | val 0.77961
  Classification -> best τ=0.430 (val F1=0.2622)
  Directional -> Accuracy: 0.5357, MCC: 0.1536, F1: 0.6389

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.60853 | val 0.69624
  Epoch 016 - train 0.60036 | val 0.78864
  Classification -> best τ=0.425 (val F1=0.1720)
  Directional -> Accuracy: 0.4565, MCC: 0.0086, F1: 0.3902

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.68527 | val 0.72039
  Epoch 020 - train 0.59030 | val 0.63114
  Epoch 030 - train 0.57075 | val 0.62806
  Epoch 040 - train 0.60829 | val 0.70712
  Epoch 046 - train 0.50801 | val 0.89785
  Classification -> best τ=0.345 (val F1=0.6130)
  Directional -> Accuracy: 0.3469, MCC: -0.1894, F1: 0.5152

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.75823 | val 0.90325
  Epoch 018 - train 0.64364 | val 1.01354
  Classification -> best τ=0.430 (val F1=0.3882)
  Directional -> Accuracy: 0.5405, MCC: 0.0635, F1: 0.6047

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.65656 | val 0.68210
  Epoch 020 - train 0.60739 | val 0.71587
  Epoch 021 - train 0.61453 | val 0.68362
  Classification -> best τ=0.475 (val F1=0.3859)
  Directional -> Accuracy: 0.5067, MCC: 0.1147, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.63765 | val 0.68886
  Epoch 018 - train 0.63062 | val 0.67655
  Classification -> best τ=0.430 (val F1=0.4515)
  Directional -> Accuracy: 0.5000, MCC: 0.0118, F1: 0.4390

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.69824 | val 0.71251
  Epoch 016 - train 0.64775 | val 0.70034
  Classification -> best τ=0.485 (val F1=0.4568)
  Directional -> Accuracy: 0.5116, MCC: 0.1767, F1: 0.2759

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.75373 | val 0.68109
  Epoch 020 - train 0.68028 | val 0.64217
  Classification -> best τ=0.580 (val F1=0.4682)
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.67679 | val 0.70142
  Epoch 020 - train 0.63968 | val 1.17543
  Epoch 024 - train 0.62687 | val 0.95097
  Classification -> best τ=0.545 (val F1=0.2130)
  Directional -> Accuracy: 0.3571, MCC: -0.3090, F1: 0.4375

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.64381 | val 1.04520
  Epoch 017 - train 0.66869 | val 0.90487
  Classification -> best τ=0.525 (val F1=0.3920)
  Directional -> Accuracy: 0.5000, MCC: 0.1301, F1: 0.6585

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.68516 | val 1.10788
  Epoch 017 - train 0.62212 | val 2.04005
  Classification -> best τ=0.415 (val F1=0.2163)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.64354 | val 0.78021
  Epoch 018 - train 0.62441 | val 0.80153
  Classification -> best τ=0.425 (val F1=0.2222)
  Directional -> Accuracy: 0.3929, MCC: -0.2425, F1: 0.1500

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.67293 | val 0.75216

[I 2026-02-25 04:25:49,207] Trial 218 finished with value: 0.2884686208986815 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 64, 'learning_rate': 0.007078652505921144, 'weight_decay': 0.0006584521932902351, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 0.14163008807674832, 'early_stopping_min_delta': 0.0030355301727743966}. Best is trial 200 with value: 0.303360648585588.

  Epoch 020 - train 0.63916 | val 0.71493
  Classification -> best τ=0.450 (val F1=0.1991)
  Directional -> Accuracy: 0.5082, MCC: -0.0647, F1: 0.0625

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2884686208986815
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.66092 | val 0.65431
  Epoch 020 - train 0.63694 | val 0.66833
  Epoch 027 - train 0.62744 | val 0.68035
  Classification -> best τ=0.480 (val F1=0.3625)
  Directional -> Accuracy: 0.6053, MCC: 0.1975, F1: 0.5455

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.63868 | val 0.68554
  Epoch 017 - train 0.62449 | val 0.71394
  Classification -> best τ=0.465 (val F1=0.1549)
  Directional -> Accuracy: 0.6000, MCC: 0.1297, F1: 0.7188

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.69515 | val 0.69926
  Epoch 017 - train 0.62790 | val 0.73660
  Classification -> best τ=0.525 (val F1=0.2764)
  Directional -> Accuracy: 0.4681, MCC: -0.0135, F1: 0.0741

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.68572 | val 0.70495
  Epoch 017 - train 0.67181 | val 0.72936
  Classification -> best τ=0.490 (val F1=0.1810)
  Directional -> Accuracy: 0.4933, MCC: -0.0072, F1: 0.5000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.66095 | val 0.67377
  Epoch 020 - train 0.59818 | val 0.69052
  Epoch 021 - train 0.65091 | val 0.70303
  Classification -> best τ=0.620 (val F1=0.4121)
  Directional -> Accuracy: 0.4706, MCC: -0.0435, F1: 0.4000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.63780 | val 0.70223
  Epoch 017 - train 0.66761 | val 0.72484
  Classification -> best τ=0.465 (val F1=0.0778)
  Directional -> Accuracy: 0.5532, MCC: 0.1357, F1: 0.2759

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.67290 | val 0.70720
  Epoch 020 - train 0.67777 | val 0.74744
  Epoch 029 - train 0.64219 | val 0.73605
  Classification -> best τ=0.345 (val F1=0.2280)
  Directional -> Accuracy: 0.4783, MCC: 0.1448, F1: 0.5909

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.60270 | val 0.72888
  Epoch 019 - train 0.60070 | val 0.73744
  Classification -> best τ=0.380 (val F1=0.1214)
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.5902

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.65909 | val 0.75470
  Epoch 016 - train 0.56365 | val 0.79930
  Classification -> best τ=0.490 (val F1=0.1723)
  Directional -> Accuracy: 0.5102, MCC: 0.1340, F1: 0.6250

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.62403 | val 0.74979
  Epoch 018 - train 0.62591 | val 0.76625
  Classification -> best τ=0.550 (val F1=0.1137)
  Directional -> Accuracy: 0.5286, MCC: 0.0000, F1: 0.3529

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.67094 | val 0.81661
  Epoch 017 - train 0.63602 | val 1.15855
  Classification -> best τ=0.490 (val F1=0.1021)
  Directional -> Accuracy: 0.4000, MCC: -0.2006, F1: 0.3750

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.69592 | val 0.71028
  Epoch 017 - train 0.63853 | val 1.17388
  Classification -> best τ=0.460 (val F1=0.1469)
  Directional -> Accuracy: 0.5172, MCC: 0.1325, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.63079 | val 0.79170
  Epoch 016 - train 0.58951 | val 0.86695
  Classification -> best τ=0.615 (val F1=0.1449)
  Directional -> Accuracy: 0.5952, MCC: 0.1940, F1: 0.2609

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.68826 | val 0.68310
  Epoch 020 - train 0.63792 | val 0.67217
  Epoch 030 - train 0.63171 | val 0.65026
  Epoch 032 - train 0.62258 | val 0.67347
  Classification -> best τ=0.335 (val F1=0.3430)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.5161

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.70688 | val 0.71512
  Epoch 019 - train 0.66182 | val 0.69826
  Classification -> best τ=0.475 (val F1=0.0696)
  Directional -> Accuracy: 0.5769, MCC: 0.1338, F1: 0.4211

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.64253 | val 0.91271
  Epoch 017 - train 0.64376 | val 0.92481
  Classification -> best τ=0.585 (val F1=0.3475)
  Directional -> Accuracy: 0.5072, MCC: 0.0467, F1: 0.4138

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.67688 | val 0.94172
  Epoch 016 - train 0.64635 | val 0.91035
  Classification -> best τ=0.670 (val F1=0.0923)
  Directional -> Accuracy: 0.4237, MCC: 0.1785, F1: 0.1500

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.68304 | val 0.69895
  Epoch 019 - train 0.66736 | val 0.74955
  Classification -> best τ=0.450 (val F1=0.1733)
  Directional -> Accuracy: 0.5200, MCC: 0.2041, F1: 0.4000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.65143 | val 0.71521
  Epoch 020 - train 0.67523 | val 0.72114
  Epoch 021 - train 0.64145 | val 0.72346
  Classification -> best τ=0.425 (val F1=0.2752)
  Directional -> Accuracy: 0.4769, MCC: 0.0998, F1: 0.2917

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.66733 | val 0.68212
  Epoch 020 - train 0.63381 | val 0.67327
  Epoch 027 - train 0.60373 | val 0.66131
  Classification -> best τ=0.445 (val F1=0.3293)
  Directional -> Accuracy: 0.5733, MCC: 0.3018, F1: 0.3846

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.67174 | val 0.70866
  Epoch 020 - train 0.64048 | val 0.68329
  Epoch 030 - train 0.60335 | val 0.82472
  Epoch 034 - train 0.63554 | val 1.15200
  Classification -> best τ=0.505 (val F1=0.3740)
  Directional -> Accuracy: 0.4468, MCC: 0.0497, F1: 0.3158

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.67094 | val 0.93942
  Epoch 016 - train 0.68182 | val 1.10887
  Classification -> best τ=0.670 (val F1=0.2308)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.65968 | val 0.69147
  Epoch 017 - train 0.62417 | val 0.71461
  Classification -> best τ=0.565 (val F1=0.2554)
  Directional -> Accuracy: 0.4828, MCC: 0.0141, F1: 0.4231

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.65648 | val 0.69572
  Epoch 017 - train 0.63730 | val 0.69491
  Classification -> best τ=0.445 (val F1=0.1271)
  Directional -> Accuracy: 0.5385, MCC: 0.0777, F1: 0.5312

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.66415 | val 0.62551
  Epoch 020 - train 0.55804 | val 0.70270
  Epoch 025 - train 0.57133 | val 0.75748
  Classification -> best τ=0.510 (val F1=0.5533)
  Directional -> Accuracy: 0.5000, MCC: 0.0996, F1: 0.3000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.64765 | val 0.69637
  Epoch 020 - train 0.60897 | val 0.71028
  Epoch 026 - train 0.65736 | val 0.69908
  Classification -> best τ=0.575 (val F1=0.4019)
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.71301 | val 0.69627
  Epoch 020 - train 0.63889 | val 0.71101
  Epoch 021 - train 0.63947 | val 0.71491
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.68054 | val 0.72494
  Epoch 019 - train 0.63724 | val 0.71775
  Classification -> best τ=0.315 (val F1=0.1939)
  Directional -> Accuracy: 0.5789, MCC: 0.1378, F1: 0.6364

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.66546 | val 0.69119
  Epoch 020 - train 0.67530 | val 0.66707
  Epoch 030 - train 0.56875 | val 0.67325
  Epoch 040 - train 0.56625 | val 0.65679
  Epoch 042 - train 0.55738 | val 0.66835
  Classification -> best τ=0.565 (val F1=0.3287)
  Directional -> Accuracy: 0.5854, MCC: 0.1688, F1: 0.7018

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.68090 | val 0.74855
  Epoch 016 - train 0.64883 | val 0.88315
  Classification -> best τ=0.575 (val F1=0.2814)
  Directional -> Accuracy: 0.5116, MCC: 0.0197, F1: 0.4615

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.64780 | val 0.64776
  Epoch 020 - train 0.62458 | val 0.62734
  Epoch 030 - train 0.59302 | val 0.65980
  Epoch 040 - train 0.48799 | val 1.07445
  Epoch 041 - train 0.52667 | val 0.98298
  Classification -> best τ=0.725 (val F1=0.3201)
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.66001 | val 0.71082
  Epoch 019 - train 0.61180 | val 0.95352
  Classification -> best τ=0.370 (val F1=0.3242)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.66383 | val 0.66732
  Epoch 020 - train 0.68713 | val 0.73639
  Epoch 030 - train 0.66820 | val 0.71131
  Epoch 040 - train 0.66262 | val 0.75631
  Classification -> best τ=0.485 (val F1=0.4426)
  Directional -> Accuracy: 0.5205, MCC: 0.1499, F1: 0.3636

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.68033 | val 0.70018
  Epoch 020 - train 0.55625 | val 0.70573
  Epoch 022 - train 0.57957 | val 0.77608
  Classification -> best τ=0.505 (val F1=0.2887)
  Directional -> Accuracy: 0.5405, MCC: 0.0968, F1: 0.6047

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.65990 | val 0.73391
  Epoch 016 - train 0.63679 | val 0.79499
  Classification -> best τ=0.565 (val F1=0.2503)
  Directional -> Accuracy: 0.5455, MCC: 0.0793, F1: 0.4118

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.68653 | val 0.71242
  Epoch 018 - train 0.67491 | val 0.74156
  Classification -> best τ=0.315 (val F1=0.3855)
  Directional -> Accuracy: 0.5758, MCC: 0.1011, F1: 0.6667

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.67655 | val 0.71909
  Epoch 016 - train 0.62361 | val 0.71320
  Classification -> best τ=0.490 (val F1=0.2741)
  Directional -> Accuracy: 0.6190, MCC: 0.2864, F1: 0.5294

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.64448 | val 0.69951
  Epoch 018 - train 0.61139 | val 0.69819
  Classification -> best τ=0.435 (val F1=0.2946)
  Directional -> Accuracy: 0.5714, MCC: 0.2471, F1: 0.6667

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.61466 | val 0.75656
  Epoch 016 - train 0.55594 | val 0.78946
  Classification -> best τ=0.485 (val F1=0.3397)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.60675 | val 0.63699
  Epoch 020 - train 0.61042 | val 0.76540
  Epoch 026 - train 0.53235 | val 0.84600
  Classification -> best τ=0.390 (val F1=0.4386)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.61329 | val 0.86503
  Epoch 016 - train 0.55337 | val 0.85927
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.66046 | val 0.66486
  Epoch 020 - train 0.62899 | val 0.73176
  Epoch 030 - train 0.60813 | val 1.07951
  Classification -> best τ=0.330 (val F1=0.4428)
  Directional -> Accuracy: 0.5200, MCC: 0.1633, F1: 0.6727

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.64260 | val 0.70326
  Epoch 020 - train 0.65888 | val 0.68538
  Classification -> best τ=0.450 (val F1=0.1327)
  Directional -> Accuracy: 0.4565, MCC: -0.0996, F1: 0.0741

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.63232 | val 0.78098
  Epoch 020 - train 0.59973 | val 0.67729
  Epoch 030 - train 0.50197 | val 0.92090
  Epoch 031 - train 0.47604 | val 0.92139
  Classification -> best τ=0.610 (val F1=0.5170)
  Directional -> Accuracy: 0.6512, MCC: 0.2816, F1: 0.7273

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.66392 | val 0.68840
  Epoch 020 - train 0.53417 | val 0.67314
  Epoch 030 - train 0.45699 | val 0.73481
  Epoch 034 - train 0.45020 | val 0.79770
  Classification -> best τ=0.460 (val F1=0.5421)
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.65225 | val 0.98573
  Epoch 016 - train 0.62840 | val 1.37376
  Classification -> best τ=0.470 (val F1=0.2639)
  Directional -> Accuracy: 0.6071, MCC: 0.2119, F1: 0.7027

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.63632 | val 0.90969
  Epoch 017 - train 0.58546 | val 1.46012
  Classification -> best τ=0.600 (val F1=0.3666)
  Directional -> Accuracy: 0.5179, MCC: 0.0333, F1: 0.4906

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.66118 | val 0.77284
  Epoch 016 - train 0.64133 | val 0.84425
  Classification -> best τ=0.385 (val F1=0.1956)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.64159 | val 0.95265
  Epoch 017 - train 0.64667 | val 0.77489
  Classification -> best τ=0.550 (val F1=0.1168)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.68072 | val 0.70622

[I 2026-02-25 04:28:52,085] Trial 219 finished with value: 0.2575808889554628 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 64, 'learning_rate': 0.006078331955953239, 'weight_decay': 0.0006922235076799785, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 0.14967317410443448, 'early_stopping_min_delta': 0.002995880765848804}. Best is trial 200 with value: 0.303360648585588.

  Epoch 016 - train 0.67249 | val 0.70266
  Classification -> best τ=0.425 (val F1=0.0725)
  Directional -> Accuracy: 0.4590, MCC: -0.0829, F1: 0.4407

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2575808889554628
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.62985 | val 0.66998
  Epoch 020 - train 0.60744 | val 0.75598
  Epoch 023 - train 0.60992 | val 0.79611
  Classification -> best τ=0.620 (val F1=0.2510)
  Directional -> Accuracy: 0.5789, MCC: 0.1827, F1: 0.1111

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.61794 | val 0.68396
  Epoch 020 - train 0.70861 | val 0.77250
  Epoch 024 - train 0.64431 | val 0.70865
  Classification -> best τ=0.480 (val F1=0.2431)
  Directional -> Accuracy: 0.4444, MCC: 0.1289, F1: 0.0741

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.69574 | val 0.71916
  Epoch 020 - train 0.62902 | val 0.85911
  Epoch 027 - train 0.63370 | val 1.00669
  Classification -> best τ=0.485 (val F1=0.4065)
  Directional -> Accuracy: 0.5319, MCC: 0.1034, F1: 0.4211

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.68597 | val 0.76494
  Epoch 017 - train 0.67701 | val 0.70053
  Classification -> best τ=0.455 (val F1=0.1210)
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.64589 | val 0.66932
  Epoch 017 - train 0.59167 | val 0.69750
  Classification -> best τ=0.630 (val F1=0.3909)
  Directional -> Accuracy: 0.4314, MCC: -0.1280, F1: 0.2162

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.71097 | val 0.71345
  Epoch 020 - train 0.67505 | val 0.69946
  Epoch 027 - train 0.60181 | val 0.80058
  Classification -> best τ=0.470 (val F1=0.2692)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.68109 | val 0.69326
  Epoch 020 - train 0.69355 | val 0.72721
  Classification -> best τ=0.535 (val F1=0.2591)
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.76558 | val 0.61930
  Epoch 020 - train 0.59986 | val 0.82962
  Classification -> best τ=0.250 (val F1=0.2601)
  Directional -> Accuracy: 0.5349, MCC: -0.0696, F1: 0.1667

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.66315 | val 0.69516
  Epoch 020 - train 0.59339 | val 1.01267
  Classification -> best τ=0.445 (val F1=0.2855)
  Directional -> Accuracy: 0.5714, MCC: 0.1118, F1: 0.1600

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.67244 | val 0.70997
  Epoch 020 - train 0.62553 | val 0.73373
  Classification -> best τ=0.445 (val F1=0.3038)
  Directional -> Accuracy: 0.4286, MCC: -0.0442, F1: 0.5745

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.68406 | val 0.71135
  Epoch 020 - train 0.63784 | val 1.56198
  Epoch 021 - train 0.62123 | val 1.77950
  Classification -> best τ=0.425 (val F1=0.1750)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.65453 | val 0.83683
  Epoch 019 - train 0.58794 | val 1.18440
  Classification -> best τ=0.555 (val F1=0.1996)
  Directional -> Accuracy: 0.4828, MCC: -0.0379, F1: 0.5714

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.72510 | val 0.79267
  Epoch 016 - train 0.57941 | val 1.05374
  Classification -> best τ=0.475 (val F1=0.2731)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.69864 | val 0.64086
  Epoch 019 - train 0.67714 | val 0.64137
  Classification -> best τ=0.415 (val F1=0.3477)
  Directional -> Accuracy: 0.5167, MCC: 0.0343, F1: 0.5672

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.66467 | val 0.70396
  Epoch 020 - train 0.59390 | val 0.87212
  Epoch 021 - train 0.59751 | val 1.01744
  Classification -> best τ=0.545 (val F1=0.2160)
  Directional -> Accuracy: 0.5769, MCC: 0.1486, F1: 0.2667

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.65923 | val 0.77645
  Epoch 019 - train 0.63070 | val 0.74184
  Classification -> best τ=0.625 (val F1=0.3228)
  Directional -> Accuracy: 0.5362, MCC: 0.1271, F1: 0.4074

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.65473 | val 0.87493
  Epoch 017 - train 0.65318 | val 1.05357
  Classification -> best τ=0.500 (val F1=0.2787)
  Directional -> Accuracy: 0.4576, MCC: -0.0481, F1: 0.4839

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.66822 | val 0.91877
  Epoch 018 - train 0.65204 | val 0.92802
  Classification -> best τ=0.560 (val F1=0.1656)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.68703 | val 1.00577
  Epoch 016 - train 0.65029 | val 1.83290
  Classification -> best τ=0.435 (val F1=0.2752)
  Directional -> Accuracy: 0.5231, MCC: 0.1873, F1: 0.3922

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.66494 | val 0.66981
  Epoch 020 - train 0.65652 | val 0.70649
  Epoch 022 - train 0.62667 | val 0.68686
  Classification -> best τ=0.535 (val F1=0.2940)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.68690 | val 0.70905
  Epoch 020 - train 0.60766 | val 0.87176
  Epoch 028 - train 0.54990 | val 0.79142
  Classification -> best τ=0.480 (val F1=0.3252)
  Directional -> Accuracy: 0.4043, MCC: 0.1162, F1: 0.0667

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.66995 | val 0.72433
  Epoch 016 - train 0.66554 | val 0.84642
  Classification -> best τ=0.565 (val F1=0.1318)
  Directional -> Accuracy: 0.4394, MCC: -0.1213, F1: 0.4478

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.70289 | val 0.67689
  Epoch 020 - train 0.66050 | val 0.79179
  Epoch 022 - train 0.64001 | val 0.76672
  Classification -> best τ=0.585 (val F1=0.2379)
  Directional -> Accuracy: 0.5345, MCC: 0.0951, F1: 0.5263

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.68350 | val 0.72494
  Epoch 020 - train 0.59845 | val 0.68971
  Epoch 030 - train 0.59335 | val 0.71705
  Epoch 036 - train 0.56708 | val 0.70795
  Classification -> best τ=0.460 (val F1=0.2644)
  Directional -> Accuracy: 0.4769, MCC: 0.0000, F1: 0.6458

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.67957 | val 0.62336
  Epoch 020 - train 0.60546 | val 0.77985
  Epoch 030 - train 0.57959 | val 0.76377
  Epoch 040 - train 0.50936 | val 0.87143
  Classification -> best τ=0.465 (val F1=0.4743)
  Directional -> Accuracy: 0.4643, MCC: 0.0292, F1: 0.1667

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.71928 | val 0.74553
  Epoch 020 - train 0.67825 | val 0.71302
  Epoch 029 - train 0.59597 | val 0.73910
  Classification -> best τ=0.450 (val F1=0.2935)
  Directional -> Accuracy: 0.5652, MCC: 0.3397, F1: 0.6667

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.66826 | val 0.71528
  Epoch 020 - train 0.61099 | val 0.75069
  Epoch 021 - train 0.62689 | val 0.75927
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.65784 | val 0.68177
  Epoch 016 - train 0.61089 | val 0.69616
  Classification -> best τ=0.515 (val F1=0.2323)
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.66340 | val 0.70596
  Epoch 016 - train 0.70115 | val 0.68575
  Classification -> best τ=0.540 (val F1=0.4862)
  Directional -> Accuracy: 0.6341, MCC: 0.2695, F1: 0.7170

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.66264 | val 0.81679
  Epoch 017 - train 0.61343 | val 0.97642
  Classification -> best τ=0.475 (val F1=0.2814)
  Directional -> Accuracy: 0.5349, MCC: 0.0783, F1: 0.5833

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.66834 | val 0.64989
  Epoch 020 - train 0.59945 | val 0.66508
  Epoch 030 - train 0.58311 | val 0.64182
  Epoch 040 - train 0.51708 | val 0.61930
  Epoch 050 - train 0.43106 | val 0.75154
  Classification -> best τ=0.540 (val F1=0.3281)
  Directional -> Accuracy: 0.5349, MCC: 0.0716, F1: 0.5455

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.62907 | val 0.68502
  Epoch 018 - train 0.59799 | val 0.85764
  Classification -> best τ=0.370 (val F1=0.3833)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.65927 | val 0.65041
  Epoch 020 - train 0.63901 | val 0.68806
  Epoch 021 - train 0.64963 | val 0.64622
  Classification -> best τ=0.385 (val F1=0.3982)
  Directional -> Accuracy: 0.5616, MCC: 0.1955, F1: 0.4839

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.61050 | val 0.79888
  Epoch 016 - train 0.62985 | val 0.74025
  Classification -> best τ=0.515 (val F1=0.2588)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.66722 | val 0.74275
  Epoch 016 - train 0.63973 | val 1.00052
  Classification -> best τ=0.565 (val F1=0.2818)
  Directional -> Accuracy: 0.5227, MCC: 0.0455, F1: 0.5116

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.66293 | val 0.70088
  Epoch 020 - train 0.65051 | val 0.74423
  Epoch 022 - train 0.63390 | val 0.73682
  Classification -> best τ=0.360 (val F1=0.3525)
  Directional -> Accuracy: 0.6364, MCC: 0.2491, F1: 0.6923

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.66346 | val 0.70207
  Epoch 016 - train 0.56216 | val 0.73363
  Classification -> best τ=0.605 (val F1=0.2652)
  Directional -> Accuracy: 0.5238, MCC: 0.1168, F1: 0.2857

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.64642 | val 0.67762
  Epoch 020 - train 0.60530 | val 0.70767
  Epoch 023 - train 0.57052 | val 0.76721
  Classification -> best τ=0.515 (val F1=0.2717)
  Directional -> Accuracy: 0.5179, MCC: 0.0234, F1: 0.4490

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.65395 | val 0.85216
  Epoch 016 - train 0.60430 | val 0.92260
  Classification -> best τ=0.555 (val F1=0.2659)
  Directional -> Accuracy: 0.3913, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.69388 | val 0.66669
  Epoch 020 - train 0.58401 | val 0.65499
  Epoch 030 - train 0.60319 | val 0.59688
  Epoch 040 - train 0.55501 | val 0.63678
  Epoch 045 - train 0.52134 | val 0.63623
  Classification -> best τ=0.295 (val F1=0.6130)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.67582 | val 0.80690
  Epoch 016 - train 0.58145 | val 0.96034
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.65900 | val 0.68879
  Epoch 020 - train 0.61260 | val 0.86156
  Classification -> best τ=0.460 (val F1=0.3620)
  Directional -> Accuracy: 0.5067, MCC: 0.0499, F1: 0.6542

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.66102 | val 0.68931
  Epoch 020 - train 0.62079 | val 0.72482
  Classification -> best τ=0.490 (val F1=0.2933)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.0000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.69811 | val 0.72040
  Epoch 019 - train 0.57847 | val 0.80580
  Classification -> best τ=0.480 (val F1=0.4799)
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.7164

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.65027 | val 0.70598
  Epoch 020 - train 0.60540 | val 0.65390
  Epoch 022 - train 0.59944 | val 0.62490
  Classification -> best τ=0.625 (val F1=0.6290)
  Directional -> Accuracy: 0.3673, MCC: -0.1468, F1: 0.5079

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.69109 | val 0.82939
  Epoch 017 - train 0.67570 | val 1.29271
  Classification -> best τ=0.620 (val F1=0.1548)
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.66773 | val 0.81703
  Epoch 016 - train 0.65576 | val 1.18978
  Classification -> best τ=0.520 (val F1=0.2830)
  Directional -> Accuracy: 0.5000, MCC: 0.1301, F1: 0.6585

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.66170 | val 1.15850
  Epoch 017 - train 0.63588 | val 1.37771
  Classification -> best τ=0.575 (val F1=0.2011)
  Directional -> Accuracy: 0.5741, MCC: 0.1509, F1: 0.6667

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.70365 | val 0.74269
  Epoch 016 - train 0.65280 | val 0.74261
  Classification -> best τ=0.565 (val F1=0.2222)
  Directional -> Accuracy: 0.5000, MCC: -0.0227, F1: 0.6111

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.70164 | val 0.69119
  Epoch 020 - train 0.65642 | val 0.81534

[I 2026-02-25 04:31:00,899] Trial 220 finished with value: 0.2858717442487158 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 64, 'learning_rate': 0.007779756618735465, 'weight_decay': 0.0005688975569590108, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 0.14061572396168404, 'early_stopping_min_delta': 0.002639041850119475}. Best is trial 200 with value: 0.303360648585588.

  Epoch 023 - train 0.64367 | val 0.70355
  Classification -> best τ=0.445 (val F1=0.1848)
  Directional -> Accuracy: 0.3934, MCC: -0.2084, F1: 0.4638

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2858717442487158
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.64507 | val 0.75422
  Epoch 020 - train 0.60644 | val 0.78236
  Epoch 021 - train 0.61288 | val 0.76193
  Classification -> best τ=0.570 (val F1=0.3286)
  Directional -> Accuracy: 0.5789, MCC: 0.1186, F1: 0.3333

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.64823 | val 0.69357
  Epoch 020 - train 0.67428 | val 0.70324
  Epoch 022 - train 0.60757 | val 0.69428
  Classification -> best τ=0.455 (val F1=0.2307)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.65790 | val 0.75296
  Epoch 020 - train 0.64256 | val 0.81655
  Epoch 021 - train 0.62224 | val 0.79229
  Classification -> best τ=0.435 (val F1=0.0857)
  Directional -> Accuracy: 0.4894, MCC: -0.0255, F1: 0.5200

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.68970 | val 0.70956
  Epoch 020 - train 0.66103 | val 0.97639
  Epoch 021 - train 0.65785 | val 0.91888
  Classification -> best τ=0.440 (val F1=0.1723)
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.66366 | val 0.66955
  Epoch 018 - train 0.57935 | val 0.67250
  Classification -> best τ=0.550 (val F1=0.4255)
  Directional -> Accuracy: 0.6863, MCC: 0.3897, F1: 0.6667

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.68703 | val 0.69485
  Epoch 020 - train 0.61592 | val 0.71306
  Epoch 026 - train 0.58199 | val 0.69203
  Classification -> best τ=0.505 (val F1=0.2582)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.68517 | val 0.68615
  Epoch 020 - train 0.65961 | val 0.69301
  Epoch 027 - train 0.67356 | val 0.70766
  Classification -> best τ=0.500 (val F1=0.2495)
  Directional -> Accuracy: 0.5942, MCC: 0.1683, F1: 0.5172

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.64115 | val 0.65724
  Epoch 019 - train 0.58129 | val 0.84673
  Classification -> best τ=0.340 (val F1=0.3016)
  Directional -> Accuracy: 0.4186, MCC: -0.1539, F1: 0.3902

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.62409 | val 0.71323
  Epoch 017 - train 0.56773 | val 0.79225
  Classification -> best τ=0.395 (val F1=0.1353)
  Directional -> Accuracy: 0.5918, MCC: 0.2131, F1: 0.6154

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.65429 | val 0.70038
  Epoch 017 - train 0.61188 | val 0.83853
  Classification -> best τ=0.460 (val F1=0.1275)
  Directional -> Accuracy: 0.4714, MCC: -0.0254, F1: 0.4932

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.71339 | val 0.76880
  Epoch 020 - train 0.66193 | val 1.35955
  Epoch 022 - train 0.60833 | val 1.19568
  Classification -> best τ=0.485 (val F1=0.3094)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.64656 | val 0.74345
  Epoch 020 - train 0.61507 | val 0.94729
  Epoch 021 - train 0.59118 | val 0.84206
  Classification -> best τ=0.465 (val F1=0.2946)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.62510 | val 0.77333
  Epoch 016 - train 0.57425 | val 0.68101
  Classification -> best τ=0.540 (val F1=0.2780)
  Directional -> Accuracy: 0.3333, MCC: -0.3414, F1: 0.4615

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.66032 | val 0.70816
  Epoch 020 - train 0.66143 | val 0.64843
  Epoch 028 - train 0.68000 | val 0.70084
  Classification -> best τ=0.480 (val F1=0.3477)
  Directional -> Accuracy: 0.5167, MCC: 0.0343, F1: 0.5672

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.66450 | val 0.80537
  Epoch 020 - train 0.59058 | val 0.78626
  Epoch 022 - train 0.59284 | val 0.76329
  Classification -> best τ=0.615 (val F1=0.2160)
  Directional -> Accuracy: 0.5577, MCC: 0.0986, F1: 0.4651

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.67309 | val 0.73364
  Epoch 017 - train 0.64113 | val 0.71656
  Classification -> best τ=0.505 (val F1=0.4197)
  Directional -> Accuracy: 0.6087, MCC: 0.2208, F1: 0.7097

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.68315 | val 0.78152
  Epoch 016 - train 0.65708 | val 1.23453
  Classification -> best τ=0.425 (val F1=0.1336)
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.67801 | val 0.81384
  Epoch 020 - train 0.64979 | val 1.11749
  Epoch 021 - train 0.68354 | val 0.83851
  Classification -> best τ=0.475 (val F1=0.2332)
  Directional -> Accuracy: 0.6133, MCC: 0.2515, F1: 0.6329

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.71513 | val 1.05959
  Epoch 019 - train 0.62719 | val 1.50547
  Classification -> best τ=0.380 (val F1=0.3071)
  Directional -> Accuracy: 0.5231, MCC: 0.0337, F1: 0.5753

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.69008 | val 0.70792
  Epoch 020 - train 0.65830 | val 0.72599
  Epoch 029 - train 0.59153 | val 0.71983
  Classification -> best τ=0.550 (val F1=0.3269)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.68841 | val 0.68199
  Epoch 020 - train 0.62134 | val 0.80650
  Epoch 024 - train 0.53394 | val 0.89421
  Classification -> best τ=0.375 (val F1=0.3278)
  Directional -> Accuracy: 0.4894, MCC: -0.0168, F1: 0.5385

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.67627 | val 0.76255
  Epoch 018 - train 0.64842 | val 0.76556
  Classification -> best τ=0.560 (val F1=0.2352)
  Directional -> Accuracy: 0.4545, MCC: -0.1220, F1: 0.1818

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.67737 | val 0.70750
  Epoch 017 - train 0.71197 | val 0.69945
  Classification -> best τ=0.555 (val F1=0.3379)
  Directional -> Accuracy: 0.5345, MCC: 0.0951, F1: 0.5263

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.69150 | val 0.69477
  Epoch 017 - train 0.67995 | val 0.87286
  Classification -> best τ=0.405 (val F1=0.0722)
  Directional -> Accuracy: 0.4615, MCC: -0.0616, F1: 0.5783

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.65078 | val 0.64103
  Epoch 020 - train 0.60502 | val 0.69143
  Epoch 026 - train 0.52756 | val 0.80787
  Classification -> best τ=0.395 (val F1=0.4719)
  Directional -> Accuracy: 0.5536, MCC: 0.1158, F1: 0.5614

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.68743 | val 0.69496
  Epoch 018 - train 0.64549 | val 0.72594
  Classification -> best τ=0.485 (val F1=0.2935)
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.64673 | val 0.69408
  Epoch 016 - train 0.66466 | val 0.71744
  Classification -> best τ=0.570 (val F1=0.2582)
  Directional -> Accuracy: 0.4762, MCC: -0.0142, F1: 0.4500

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.66075 | val 0.73543
  Epoch 020 - train 0.61460 | val 0.84035
  Classification -> best τ=0.395 (val F1=0.2300)
  Directional -> Accuracy: 0.5088, MCC: 0.2428, F1: 0.2222

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.74435 | val 0.72489
  Epoch 020 - train 0.62820 | val 0.65172
  Epoch 030 - train 0.57619 | val 1.41247
  Epoch 035 - train 0.58416 | val 2.56151
  Classification -> best τ=0.460 (val F1=0.4139)
  Directional -> Accuracy: 0.5610, MCC: 0.0983, F1: 0.6786

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.70454 | val 0.69826
  Epoch 017 - train 0.65087 | val 0.75784
  Classification -> best τ=0.555 (val F1=0.2814)
  Directional -> Accuracy: 0.5581, MCC: 0.1169, F1: 0.5581

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.64672 | val 0.65642
  Epoch 020 - train 0.57805 | val 0.63489
  Epoch 027 - train 0.57249 | val 0.64212
  Classification -> best τ=0.765 (val F1=0.3201)
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.61855 | val 0.70201
  Epoch 020 - train 0.60564 | val 0.88145
  Classification -> best τ=0.475 (val F1=0.3323)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.67003 | val 0.69937
  Epoch 019 - train 0.66536 | val 0.69574
  Classification -> best τ=0.460 (val F1=0.3744)
  Directional -> Accuracy: 0.5068, MCC: 0.0643, F1: 0.4375

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.65053 | val 0.70433
  Epoch 019 - train 0.66711 | val 0.81179
  Classification -> best τ=0.520 (val F1=0.1992)
  Directional -> Accuracy: 0.4324, MCC: -0.2266, F1: 0.0870

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.67844 | val 0.72497
  Epoch 016 - train 0.65893 | val 0.82725
  Classification -> best τ=0.660 (val F1=0.3103)
  Directional -> Accuracy: 0.5000, MCC: -0.1457, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.67516 | val 0.70633
  Epoch 019 - train 0.63725 | val 0.80541
  Classification -> best τ=0.435 (val F1=0.2809)
  Directional -> Accuracy: 0.6212, MCC: 0.2911, F1: 0.6032

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.67761 | val 0.68319
  Epoch 020 - train 0.57674 | val 0.76700
  Epoch 030 - train 0.53359 | val 0.81457
  Epoch 032 - train 0.50679 | val 0.85815
  Classification -> best τ=0.535 (val F1=0.3490)
  Directional -> Accuracy: 0.5714, MCC: 0.2530, F1: 0.3571

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.66982 | val 0.68994
  Epoch 020 - train 0.65214 | val 1.03521
  Epoch 022 - train 0.64527 | val 0.98898
  Classification -> best τ=0.360 (val F1=0.2256)
  Directional -> Accuracy: 0.4821, MCC: 0.0030, F1: 0.5797

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.68144 | val 0.76873
  Epoch 016 - train 0.57766 | val 0.77846
  Classification -> best τ=0.390 (val F1=0.1709)
  Directional -> Accuracy: 0.6304, MCC: 0.1859, F1: 0.7671

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.64882 | val 0.69012
  Epoch 020 - train 0.60087 | val 0.67712
  Epoch 030 - train 0.58491 | val 0.62079
  Epoch 040 - train 0.55149 | val 0.61634
  Epoch 050 - train 0.55026 | val 0.83890
  Classification -> best τ=0.280 (val F1=0.5125)
  Directional -> Accuracy: 0.3469, MCC: -0.1894, F1: 0.5152

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.67403 | val 0.76140
  Epoch 019 - train 0.62073 | val 0.96483
  Classification -> best τ=0.480 (val F1=0.3882)
  Directional -> Accuracy: 0.5676, MCC: 0.1378, F1: 0.5789

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.65400 | val 0.67485
  Epoch 020 - train 0.63257 | val 0.98324
  Epoch 021 - train 0.65490 | val 0.92333
  Classification -> best τ=0.385 (val F1=0.2932)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.65700 | val 0.69573
  Epoch 019 - train 0.59998 | val 0.72587
  Classification -> best τ=0.430 (val F1=0.5015)
  Directional -> Accuracy: 0.4783, MCC: -0.0417, F1: 0.4783

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.72302 | val 0.70590
  Epoch 020 - train 0.61624 | val 0.77593
  Epoch 021 - train 0.59074 | val 0.77436
  Classification -> best τ=0.530 (val F1=0.2331)
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.7164

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.70013 | val 0.71240
  Epoch 020 - train 0.65747 | val 0.68976
  Epoch 021 - train 0.60608 | val 0.70808
  Classification -> best τ=0.590 (val F1=0.6292)
  Directional -> Accuracy: 0.3673, MCC: -0.1462, F1: 0.5231

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.65088 | val 1.32615
  Epoch 016 - train 0.64984 | val 1.36169
  Classification -> best τ=0.570 (val F1=0.1914)
  Directional -> Accuracy: 0.4821, MCC: 0.1255, F1: 0.0645

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.67166 | val 0.82400
  Epoch 018 - train 0.65335 | val 1.10931
  Classification -> best τ=0.550 (val F1=0.2530)
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.67311 | val 0.80527
  Epoch 017 - train 0.63912 | val 1.25472
  Classification -> best τ=0.370 (val F1=0.2024)
  Directional -> Accuracy: 0.6111, MCC: 0.3315, F1: 0.7273

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.67545 | val 0.79302
  Epoch 019 - train 0.64990 | val 0.78878
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.68139 | val 0.69590

[I 2026-02-25 04:33:08,899] Trial 221 finished with value: 0.2831006348717218 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 64, 'learning_rate': 0.007768120678504728, 'weight_decay': 0.0005451828697094949, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 0.1332504775948881, 'early_stopping_min_delta': 0.0025608837193170798}. Best is trial 200 with value: 0.303360648585588.

  Epoch 019 - train 0.65663 | val 0.68087
  Classification -> best τ=0.425 (val F1=0.2847)
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2831006348717218
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.65524 | val 0.66785
  Epoch 020 - train 0.61975 | val 0.66664
  Epoch 026 - train 0.63251 | val 0.68327
  Classification -> best τ=0.665 (val F1=0.2510)
  Directional -> Accuracy: 0.5263, MCC: -0.0180, F1: 0.2500

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.64831 | val 0.68635
  Epoch 017 - train 0.62083 | val 0.69753
  Classification -> best τ=0.485 (val F1=0.2431)
  Directional -> Accuracy: 0.6000, MCC: 0.1273, F1: 0.7273

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.69792 | val 0.69441
  Epoch 020 - train 0.62911 | val 0.86213
  Classification -> best τ=0.545 (val F1=0.2727)
  Directional -> Accuracy: 0.4894, MCC: 0.1383, F1: 0.0769

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.67209 | val 0.71970
  Epoch 020 - train 0.64733 | val 0.77443
  Epoch 026 - train 0.66258 | val 0.71724
  Classification -> best τ=0.440 (val F1=0.2782)
  Directional -> Accuracy: 0.5867, MCC: 0.1603, F1: 0.6353

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.60184 | val 0.64426
  Epoch 020 - train 0.55369 | val 0.67583
  Epoch 026 - train 0.58072 | val 0.77325
  Classification -> best τ=0.595 (val F1=0.4255)
  Directional -> Accuracy: 0.6863, MCC: 0.3897, F1: 0.6667

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.63387 | val 0.72677
  Epoch 017 - train 0.58823 | val 0.78237
  Classification -> best τ=0.460 (val F1=0.2928)
  Directional -> Accuracy: 0.5319, MCC: 0.0687, F1: 0.2667

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.70326 | val 0.68276
  Epoch 020 - train 0.67059 | val 0.70381
  Epoch 026 - train 0.66748 | val 0.79717
  Classification -> best τ=0.470 (val F1=0.3693)
  Directional -> Accuracy: 0.4493, MCC: 0.0062, F1: 0.5366

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.58016 | val 0.65570
  Epoch 017 - train 0.61358 | val 0.65432
  Classification -> best τ=0.395 (val F1=0.3443)
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.63900 | val 0.72744
  Epoch 019 - train 0.58923 | val 0.86287
  Classification -> best τ=0.500 (val F1=0.0617)
  Directional -> Accuracy: 0.6327, MCC: 0.2464, F1: 0.5263

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.62300 | val 0.80735
  Epoch 020 - train 0.65834 | val 0.73620
  Epoch 030 - train 0.56480 | val 1.31112
  Classification -> best τ=0.400 (val F1=0.2607)
  Directional -> Accuracy: 0.4857, MCC: 0.0875, F1: 0.5909

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.68389 | val 0.87405
  Epoch 020 - train 0.64993 | val 1.59322
  Classification -> best τ=0.345 (val F1=0.2048)
  Directional -> Accuracy: 0.6200, MCC: 0.2539, F1: 0.3871

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.63450 | val 0.75728
  Epoch 020 - train 0.60703 | val 1.06381
  Epoch 021 - train 0.61640 | val 0.90136
  Classification -> best τ=0.535 (val F1=0.2769)
  Directional -> Accuracy: 0.6552, MCC: 0.3409, F1: 0.5652

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.64379 | val 0.75227
  Epoch 020 - train 0.56205 | val 0.91892
  Classification -> best τ=0.550 (val F1=0.2855)
  Directional -> Accuracy: 0.4286, MCC: -0.1070, F1: 0.5556

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.66745 | val 0.64825
  Epoch 020 - train 0.64546 | val 0.82523
  Epoch 021 - train 0.61555 | val 0.85884
  Classification -> best τ=0.420 (val F1=0.3118)
  Directional -> Accuracy: 0.5667, MCC: 0.1383, F1: 0.6176

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.66747 | val 0.69233
  Epoch 020 - train 0.60561 | val 1.11674
  Classification -> best τ=0.455 (val F1=0.1852)
  Directional -> Accuracy: 0.5000, MCC: 0.0929, F1: 0.6286

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.65917 | val 0.80311
  Epoch 018 - train 0.61286 | val 0.74844
  Classification -> best τ=0.710 (val F1=0.2933)
  Directional -> Accuracy: 0.5072, MCC: 0.0765, F1: 0.3200

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.67536 | val 1.19299
  Epoch 016 - train 0.64896 | val 1.10852
  Classification -> best τ=0.595 (val F1=0.0557)
  Directional -> Accuracy: 0.4915, MCC: -0.0677, F1: 0.5833

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.67983 | val 0.91324
  Epoch 018 - train 0.65496 | val 1.72950
  Classification -> best τ=0.590 (val F1=0.2110)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.65462 | val 0.89374
  Epoch 018 - train 0.61812 | val 1.88526
  Classification -> best τ=0.495 (val F1=0.1777)
  Directional -> Accuracy: 0.4462, MCC: 0.0307, F1: 0.2174

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.65017 | val 0.68930
  Epoch 020 - train 0.65084 | val 1.09994
  Classification -> best τ=0.495 (val F1=0.3259)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.66697 | val 0.70001
  Epoch 020 - train 0.59996 | val 1.03135
  Epoch 022 - train 0.61731 | val 0.84275
  Classification -> best τ=0.490 (val F1=0.3707)
  Directional -> Accuracy: 0.5745, MCC: 0.1583, F1: 0.6154

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.68579 | val 0.75118
  Epoch 017 - train 0.66228 | val 0.79389
  Classification -> best τ=0.525 (val F1=0.0861)
  Directional -> Accuracy: 0.4242, MCC: -0.1808, F1: 0.2083

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.68166 | val 0.73323
  Epoch 020 - train 0.64916 | val 0.75662
  Classification -> best τ=0.630 (val F1=0.3342)
  Directional -> Accuracy: 0.5345, MCC: 0.1477, F1: 0.4490

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.65603 | val 0.71012
  Epoch 017 - train 0.64684 | val 0.71026
  Classification -> best τ=0.620 (val F1=0.2390)
  Directional -> Accuracy: 0.5692, MCC: 0.1523, F1: 0.3000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.66581 | val 0.64050
  Epoch 020 - train 0.64319 | val 0.70078
  Epoch 025 - train 0.60504 | val 0.68685
  Classification -> best τ=0.545 (val F1=0.4330)
  Directional -> Accuracy: 0.4821, MCC: 0.0587, F1: 0.2564

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.65164 | val 0.71848
  Epoch 017 - train 0.62601 | val 0.72960
  Classification -> best τ=0.480 (val F1=0.2935)
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.71433 | val 0.69792
  Epoch 019 - train 0.63748 | val 0.70235
  Classification -> best τ=0.545 (val F1=0.1803)
  Directional -> Accuracy: 0.5000, MCC: -0.0430, F1: 0.5882

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.68910 | val 0.69520
  Epoch 018 - train 0.64482 | val 0.76774
  Classification -> best τ=0.370 (val F1=0.2507)
  Directional -> Accuracy: 0.4737, MCC: 0.0115, F1: 0.3478

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.67159 | val 0.74963
  Epoch 020 - train 0.66229 | val 0.75708
  Epoch 029 - train 0.63179 | val 0.67201
  Classification -> best τ=0.555 (val F1=0.3671)
  Directional -> Accuracy: 0.4146, MCC: -0.1865, F1: 0.4783

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.68344 | val 0.87515
  Epoch 016 - train 0.63377 | val 1.02256
  Classification -> best τ=0.570 (val F1=0.2814)
  Directional -> Accuracy: 0.5349, MCC: 0.0664, F1: 0.4737

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.68576 | val 0.65082
  Epoch 020 - train 0.58492 | val 0.73095
  Epoch 024 - train 0.60319 | val 0.65796
  Classification -> best τ=0.510 (val F1=0.3395)
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.62006 | val 0.78492
  Epoch 020 - train 0.57821 | val 0.97653
  Epoch 021 - train 0.56338 | val 1.04465
  Classification -> best τ=0.325 (val F1=0.3196)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.66190 | val 0.68028
  Epoch 020 - train 0.63998 | val 0.72520
  Epoch 022 - train 0.62768 | val 0.74290
  Classification -> best τ=0.360 (val F1=0.2994)
  Directional -> Accuracy: 0.5616, MCC: 0.1622, F1: 0.5294

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.73093 | val 0.78209
  Epoch 016 - train 0.70145 | val 0.83329
  Classification -> best τ=0.500 (val F1=0.4276)
  Directional -> Accuracy: 0.5135, MCC: 0.1622, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.67171 | val 0.79870
  Epoch 017 - train 0.65773 | val 0.94395
  Classification -> best τ=0.605 (val F1=0.2503)
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.66769 | val 0.69709
  Epoch 018 - train 0.67158 | val 0.73485
  Classification -> best τ=0.515 (val F1=0.3001)
  Directional -> Accuracy: 0.4848, MCC: 0.0867, F1: 0.3200

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.66536 | val 0.71848
  Epoch 016 - train 0.53708 | val 0.76166
  Classification -> best τ=0.475 (val F1=0.1614)
  Directional -> Accuracy: 0.7381, MCC: 0.4767, F1: 0.7442

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.63758 | val 0.69568
  Epoch 020 - train 0.61953 | val 0.74771
  Epoch 021 - train 0.63289 | val 0.81273
  Classification -> best τ=0.410 (val F1=0.2946)
  Directional -> Accuracy: 0.5357, MCC: 0.1754, F1: 0.6486

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.60748 | val 0.69447
  Epoch 019 - train 0.54689 | val 0.83825
  Classification -> best τ=0.530 (val F1=0.2441)
  Directional -> Accuracy: 0.3913, MCC: -0.0687, F1: 0.1250

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.66436 | val 0.74737
  Epoch 020 - train 0.63787 | val 0.66832
  Epoch 030 - train 0.61846 | val 0.63102
  Epoch 040 - train 0.56426 | val 0.69659
  Epoch 044 - train 0.50457 | val 0.64942
  Classification -> best τ=0.375 (val F1=0.5606)
  Directional -> Accuracy: 0.3469, MCC: -0.1894, F1: 0.5152

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.79839 | val 0.74493
  Epoch 016 - train 0.63029 | val 0.85738
  Classification -> best τ=0.410 (val F1=0.1525)
  Directional -> Accuracy: 0.4595, MCC: -0.1435, F1: 0.5833

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.65297 | val 0.64986
  Epoch 020 - train 0.62360 | val 0.96090
  Epoch 024 - train 0.61245 | val 1.03045
  Classification -> best τ=0.365 (val F1=0.3397)
  Directional -> Accuracy: 0.5200, MCC: 0.1155, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.66043 | val 0.70123
  Epoch 017 - train 0.62805 | val 0.68704
  Classification -> best τ=0.490 (val F1=0.1909)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.0000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.66373 | val 0.69260
  Epoch 020 - train 0.60780 | val 0.67879
  Epoch 030 - train 0.56486 | val 0.53316
  Epoch 040 - train 0.53086 | val 0.73860
  Epoch 045 - train 0.54443 | val 0.99958
  Classification -> best τ=0.425 (val F1=0.6250)
  Directional -> Accuracy: 0.5814, MCC: 0.1734, F1: 0.7273

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.67755 | val 0.63288
  Epoch 019 - train 0.60107 | val 0.67659
  Classification -> best τ=0.590 (val F1=0.5689)
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.67443 | val 0.96337
  Epoch 020 - train 0.63754 | val 1.20569
  Classification -> best τ=0.535 (val F1=0.0959)
  Directional -> Accuracy: 0.3393, MCC: -0.3646, F1: 0.4478

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.65840 | val 1.08399
  Epoch 020 - train 0.61878 | val 1.31300
  Epoch 022 - train 0.64227 | val 1.35537
  Classification -> best τ=0.660 (val F1=0.3622)
  Directional -> Accuracy: 0.4821, MCC: -0.0333, F1: 0.4912

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.68180 | val 0.98539
  Epoch 017 - train 0.61303 | val 1.88956
  Classification -> best τ=0.510 (val F1=0.0533)
  Directional -> Accuracy: 0.5000, MCC: 0.1324, F1: 0.0690

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.65513 | val 0.74824
  Epoch 020 - train 0.62694 | val 0.81049
  Epoch 022 - train 0.61821 | val 0.73478
  Classification -> best τ=0.515 (val F1=0.4023)
  Directional -> Accuracy: 0.4286, MCC: -0.2276, F1: 0.5789

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.65678 | val 0.68466

[I 2026-02-25 04:35:17,679] Trial 222 finished with value: 0.28087839765695777 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 64, 'learning_rate': 0.006941569387143247, 'weight_decay': 0.0006071582818326673, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 0.16256251456830925, 'early_stopping_min_delta': 0.0026121669803252016}. Best is trial 200 with value: 0.303360648585588.

  Epoch 017 - train 0.66254 | val 0.82113
  Classification -> best τ=0.435 (val F1=0.0930)
  Directional -> Accuracy: 0.4262, MCC: -0.1523, F1: 0.3860

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.28087839765695777
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.65792 | val 0.64762
  Epoch 020 - train 0.64494 | val 0.66939
  Epoch 024 - train 0.60165 | val 0.71439
  Classification -> best τ=0.525 (val F1=0.2919)
  Directional -> Accuracy: 0.5132, MCC: -0.0841, F1: 0.1395

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.60548 | val 0.68733
  Epoch 020 - train 0.63498 | val 0.74213
  Epoch 028 - train 0.58443 | val 0.70074
  Classification -> best τ=0.405 (val F1=0.3220)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.66392 | val 0.75947
  Epoch 017 - train 0.64997 | val 0.88619
  Classification -> best τ=0.515 (val F1=0.2818)
  Directional -> Accuracy: 0.5957, MCC: 0.2793, F1: 0.4571

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.71065 | val 0.70970
  Epoch 016 - train 0.65478 | val 0.81976
  Classification -> best τ=0.445 (val F1=0.0885)
  Directional -> Accuracy: 0.4667, MCC: -0.1079, F1: 0.5652

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.65216 | val 0.64094
  Epoch 020 - train 0.57972 | val 0.68104
  Epoch 021 - train 0.58279 | val 0.67872
  Classification -> best τ=0.535 (val F1=0.4539)
  Directional -> Accuracy: 0.7255, MCC: 0.4530, F1: 0.7308

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.69034 | val 0.71318
  Epoch 020 - train 0.59053 | val 0.74833
  Epoch 028 - train 0.51926 | val 1.82001
  Classification -> best τ=0.555 (val F1=0.1715)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.68794 | val 0.68520
  Epoch 020 - train 0.68146 | val 0.75081
  Epoch 025 - train 0.64728 | val 0.75118
  Classification -> best τ=0.480 (val F1=0.2836)
  Directional -> Accuracy: 0.4203, MCC: 0.1002, F1: 0.5833

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.75684 | val 0.61697
  Epoch 020 - train 0.60337 | val 0.69560
  Epoch 030 - train 0.48016 | val 0.91083
  Classification -> best τ=0.245 (val F1=0.1752)
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.5902

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.70512 | val 0.70980
  Epoch 020 - train 0.59894 | val 0.79164
  Classification -> best τ=0.520 (val F1=0.1945)
  Directional -> Accuracy: 0.6122, MCC: 0.2076, F1: 0.3871

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.65434 | val 0.76201
  Epoch 020 - train 0.58436 | val 0.82849
  Epoch 030 - train 0.54739 | val 0.90182
  Epoch 031 - train 0.55623 | val 1.00428
  Classification -> best τ=0.410 (val F1=0.2433)
  Directional -> Accuracy: 0.5143, MCC: 0.1886, F1: 0.6222

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.67665 | val 0.97989
  Epoch 018 - train 0.57994 | val 1.17215
  Classification -> best τ=0.495 (val F1=0.2182)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.64576 | val 0.80694
  Epoch 018 - train 0.61236 | val 1.24561
  Classification -> best τ=0.545 (val F1=0.2906)
  Directional -> Accuracy: 0.4138, MCC: -0.1794, F1: 0.3200

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.62607 | val 0.93494
  Epoch 019 - train 0.59002 | val 0.88763
  Classification -> best τ=0.620 (val F1=0.1449)
  Directional -> Accuracy: 0.4762, MCC: -0.0673, F1: 0.3889

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.64024 | val 0.63123
  Epoch 020 - train 0.63130 | val 0.89455
  Epoch 025 - train 0.60150 | val 0.71443
  Classification -> best τ=0.475 (val F1=0.3584)
  Directional -> Accuracy: 0.5167, MCC: 0.0338, F1: 0.5538

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.64807 | val 0.71821
  Epoch 019 - train 0.54922 | val 1.05298
  Classification -> best τ=0.460 (val F1=0.2160)
  Directional -> Accuracy: 0.5192, MCC: -0.0261, F1: 0.1935

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.65952 | val 0.71265
  Epoch 017 - train 0.63995 | val 0.83274
  Classification -> best τ=0.460 (val F1=0.3563)
  Directional -> Accuracy: 0.5797, MCC: 0.1455, F1: 0.6420

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.67447 | val 0.78033
  Epoch 016 - train 0.64611 | val 1.05523
  Classification -> best τ=0.565 (val F1=0.2651)
  Directional -> Accuracy: 0.3898, MCC: 0.0189, F1: 0.1000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.67415 | val 0.93266
  Epoch 017 - train 0.64727 | val 0.79561
  Classification -> best τ=0.470 (val F1=0.1771)
  Directional -> Accuracy: 0.4000, MCC: -0.1961, F1: 0.4444

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.66186 | val 0.99153
  Epoch 016 - train 0.69263 | val 1.20293
  Classification -> best τ=0.475 (val F1=0.1517)
  Directional -> Accuracy: 0.5231, MCC: 0.1873, F1: 0.3922

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.66451 | val 0.66862
  Epoch 020 - train 0.63232 | val 0.70223
  Epoch 024 - train 0.60770 | val 0.70784
  Classification -> best τ=0.435 (val F1=0.3544)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.65068 | val 0.68441
  Epoch 020 - train 0.58083 | val 0.95263
  Epoch 030 - train 0.54515 | val 1.13869
  Classification -> best τ=0.385 (val F1=0.3080)
  Directional -> Accuracy: 0.4894, MCC: 0.0465, F1: 0.4783

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.66735 | val 0.76540
  Epoch 016 - train 0.64749 | val 0.70447
  Classification -> best τ=0.485 (val F1=0.3242)
  Directional -> Accuracy: 0.4848, MCC: -0.0362, F1: 0.5952

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.67796 | val 0.69478
  Epoch 020 - train 0.64993 | val 0.74720
  Epoch 030 - train 0.59516 | val 0.80110
  Classification -> best τ=0.290 (val F1=0.3179)
  Directional -> Accuracy: 0.6379, MCC: 0.2430, F1: 0.7342

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.68789 | val 0.69444
  Epoch 020 - train 0.66312 | val 1.02412
  Epoch 026 - train 0.60276 | val 0.86912
  Classification -> best τ=0.585 (val F1=0.1936)
  Directional -> Accuracy: 0.5231, MCC: 0.0669, F1: 0.5867

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.69130 | val 0.62988
  Epoch 020 - train 0.62460 | val 0.67450
  Epoch 024 - train 0.57448 | val 0.76115
  Classification -> best τ=0.540 (val F1=0.4719)
  Directional -> Accuracy: 0.5179, MCC: 0.1188, F1: 0.3721

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.73655 | val 0.66567
  Epoch 020 - train 0.61381 | val 0.70109
  Epoch 025 - train 0.61054 | val 0.73301
  Classification -> best τ=0.540 (val F1=0.4019)
  Directional -> Accuracy: 0.6087, MCC: 0.1761, F1: 0.3571

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.64963 | val 0.74058
  Epoch 016 - train 0.63100 | val 0.70425
  Classification -> best τ=0.610 (val F1=0.1353)
  Directional -> Accuracy: 0.4286, MCC: -0.1667, F1: 0.5000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.65801 | val 0.75506
  Epoch 016 - train 0.64134 | val 0.82441
  Classification -> best τ=0.425 (val F1=0.2260)
  Directional -> Accuracy: 0.5789, MCC: 0.2374, F1: 0.5000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.69951 | val 0.87355
  Epoch 020 - train 0.64078 | val 0.76421
  Epoch 021 - train 0.60311 | val 0.69345
  Classification -> best τ=0.475 (val F1=0.4109)
  Directional -> Accuracy: 0.5854, MCC: 0.2437, F1: 0.7213

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.71754 | val 0.75439
  Epoch 020 - train 0.69445 | val 0.92713
  Epoch 028 - train 0.60778 | val 0.76752
  Classification -> best τ=0.630 (val F1=0.2814)
  Directional -> Accuracy: 0.5116, MCC: 0.0217, F1: 0.4878

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.69587 | val 0.71043
  Epoch 018 - train 0.62151 | val 0.73522
  Classification -> best τ=0.595 (val F1=0.1560)
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.59393 | val 0.68666
  Epoch 020 - train 0.59811 | val 0.92746
  Epoch 023 - train 0.55553 | val 0.95283
  Classification -> best τ=0.360 (val F1=0.2599)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.65819 | val 0.77530
  Epoch 019 - train 0.64530 | val 0.70215
  Classification -> best τ=0.435 (val F1=0.3032)
  Directional -> Accuracy: 0.5616, MCC: 0.1368, F1: 0.5676

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.64695 | val 0.83986
  Epoch 017 - train 0.61823 | val 1.00256
  Classification -> best τ=0.550 (val F1=0.2887)
  Directional -> Accuracy: 0.5946, MCC: 0.2271, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.64519 | val 0.93724
  Epoch 018 - train 0.67293 | val 0.96781
  Classification -> best τ=0.440 (val F1=0.2358)
  Directional -> Accuracy: 0.4773, MCC: -0.2085, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.66017 | val 0.77916
  Epoch 018 - train 0.64225 | val 0.78749
  Classification -> best τ=0.390 (val F1=0.4042)
  Directional -> Accuracy: 0.5909, MCC: 0.2154, F1: 0.5846

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.68672 | val 0.75763
  Epoch 018 - train 0.61344 | val 1.08743
  Classification -> best τ=0.530 (val F1=0.2486)
  Directional -> Accuracy: 0.5000, MCC: 0.0561, F1: 0.2222

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.65056 | val 0.71384
  Epoch 018 - train 0.63031 | val 0.75399
  Classification -> best τ=0.465 (val F1=0.3690)
  Directional -> Accuracy: 0.4643, MCC: -0.0199, F1: 0.6154

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.61221 | val 0.72245
  Epoch 016 - train 0.58579 | val 1.13104
  Classification -> best τ=0.455 (val F1=0.3050)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.64745 | val 0.68793
  Epoch 020 - train 0.58927 | val 0.64523
  Epoch 030 - train 0.62429 | val 0.65053
  Epoch 040 - train 0.58866 | val 0.64938
  Epoch 050 - train 0.54686 | val 0.65490
  Classification -> best τ=0.385 (val F1=0.5815)
  Directional -> Accuracy: 0.3469, MCC: -0.1894, F1: 0.5152

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.69484 | val 0.97146
  Epoch 020 - train 0.55213 | val 1.04966
  Epoch 021 - train 0.59339 | val 1.14359
  Classification -> best τ=0.520 (val F1=0.4240)
  Directional -> Accuracy: 0.5405, MCC: 0.1105, F1: 0.4848

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.67436 | val 0.65504
  Epoch 020 - train 0.62311 | val 1.08593
  Epoch 024 - train 0.61425 | val 0.81080
  Classification -> best τ=0.365 (val F1=0.3135)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.70560 | val 0.71268
  Epoch 018 - train 0.61885 | val 0.68127
  Classification -> best τ=0.415 (val F1=0.2855)
  Directional -> Accuracy: 0.5217, MCC: 0.0134, F1: 0.6667

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.67652 | val 0.82342
  Epoch 020 - train 0.62495 | val 0.86221
  Epoch 021 - train 0.59044 | val 0.87338
  Classification -> best τ=0.695 (val F1=0.3651)
  Directional -> Accuracy: 0.6047, MCC: 0.1943, F1: 0.6531

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.76104 | val 0.71306
  Epoch 020 - train 0.60763 | val 0.66772
  Epoch 021 - train 0.59596 | val 0.66369
  Classification -> best τ=0.580 (val F1=0.6290)
  Directional -> Accuracy: 0.3673, MCC: -0.1468, F1: 0.5079

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.65746 | val 0.76615
  Epoch 020 - train 0.64216 | val 1.17811
  Classification -> best τ=0.565 (val F1=0.1548)
  Directional -> Accuracy: 0.5179, MCC: 0.0878, F1: 0.3721

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.66218 | val 0.94135
  Epoch 017 - train 0.64142 | val 1.14296
  Classification -> best τ=0.535 (val F1=0.2157)
  Directional -> Accuracy: 0.6429, MCC: 0.4222, F1: 0.7297

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.64836 | val 1.40970
  Epoch 017 - train 0.60790 | val 1.25069
  Classification -> best τ=0.455 (val F1=0.2322)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.69412 | val 0.77182
  Epoch 020 - train 0.65153 | val 0.78223
  Epoch 021 - train 0.60618 | val 0.82512
  Classification -> best τ=0.430 (val F1=0.1168)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.68241 | val 0.68008
  Epoch 020 - train 0.70324 | val 0.74622

[I 2026-02-25 04:37:27,700] Trial 223 finished with value: 0.28385297523128683 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 64, 'learning_rate': 0.007765279121481237, 'weight_decay': 0.00048586867904681837, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 0.14096949429777927, 'early_stopping_min_delta': 0.002823233487803667}. Best is trial 200 with value: 0.303360648585588.

  Epoch 025 - train 0.63945 | val 0.72809
  Classification -> best τ=0.410 (val F1=0.1942)
  Directional -> Accuracy: 0.4918, MCC: -0.0582, F1: 0.2439

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.28385297523128683
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.65671 | val 0.67056
  Epoch 020 - train 0.60188 | val 0.79771
  Classification -> best τ=0.540 (val F1=0.2510)
  Directional -> Accuracy: 0.5526, MCC: 0.0412, F1: 0.2273

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.65348 | val 0.68684
  Epoch 020 - train 0.59713 | val 0.68635
  Epoch 026 - train 0.59552 | val 0.72745
  Classification -> best τ=0.445 (val F1=0.1882)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.66213 | val 0.69424
  Epoch 016 - train 0.64069 | val 0.81264
  Classification -> best τ=0.535 (val F1=0.2514)
  Directional -> Accuracy: 0.4043, MCC: -0.1937, F1: 0.1765

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.70270 | val 0.71158
  Epoch 020 - train 0.66549 | val 0.78122
  Epoch 021 - train 0.66838 | val 0.74537
  Classification -> best τ=0.500 (val F1=0.2381)
  Directional -> Accuracy: 0.5200, MCC: 0.0120, F1: 0.6000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.62331 | val 0.66599
  Epoch 020 - train 0.60168 | val 0.76279
  Classification -> best τ=0.530 (val F1=0.4711)
  Directional -> Accuracy: 0.5882, MCC: 0.1673, F1: 0.6441

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.67541 | val 0.69383
  Epoch 020 - train 0.61021 | val 0.73743
  Epoch 030 - train 0.59655 | val 0.74674
  Epoch 040 - train 0.48849 | val 0.75033
  Epoch 043 - train 0.49367 | val 1.05925
  Classification -> best τ=0.355 (val F1=0.2887)
  Directional -> Accuracy: 0.6383, MCC: 0.3053, F1: 0.5143

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.69655 | val 0.69396
  Epoch 017 - train 0.67723 | val 0.69431
  Classification -> best τ=0.630 (val F1=0.1805)
  Directional -> Accuracy: 0.6232, MCC: 0.2091, F1: 0.1333

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.65100 | val 0.64483
  Epoch 020 - train 0.60731 | val 0.90352
  Epoch 023 - train 0.58341 | val 0.80223
  Classification -> best τ=0.435 (val F1=0.3295)
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.61349 | val 0.70492
  Epoch 017 - train 0.60088 | val 1.07283
  Classification -> best τ=0.380 (val F1=0.1939)
  Directional -> Accuracy: 0.4898, MCC: 0.0869, F1: 0.6154

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.68158 | val 0.76431
  Epoch 018 - train 0.61572 | val 0.69397
  Classification -> best τ=0.510 (val F1=0.0671)
  Directional -> Accuracy: 0.4857, MCC: 0.0589, F1: 0.5714

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.66430 | val 0.86636
  Epoch 020 - train 0.62112 | val 1.77785
  Epoch 022 - train 0.61570 | val 1.74581
  Classification -> best τ=0.525 (val F1=0.2758)
  Directional -> Accuracy: 0.5400, MCC: 0.1287, F1: 0.6102

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.65516 | val 0.75899
  Epoch 019 - train 0.64572 | val 0.90727
  Classification -> best τ=0.320 (val F1=0.2591)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.70039 | val 0.70365
  Epoch 017 - train 0.61457 | val 0.75244
  Classification -> best τ=0.550 (val F1=0.2323)
  Directional -> Accuracy: 0.4762, MCC: 0.0214, F1: 0.5926

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.67276 | val 0.65242
  Epoch 020 - train 0.65361 | val 0.68329
  Epoch 023 - train 0.63140 | val 1.01468
  Classification -> best τ=0.330 (val F1=0.3477)
  Directional -> Accuracy: 0.5333, MCC: 0.1857, F1: 0.6818

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.62819 | val 0.70789
  Epoch 019 - train 0.64726 | val 0.72687
  Classification -> best τ=0.450 (val F1=0.2160)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.62879 | val 0.72552
  Epoch 017 - train 0.63441 | val 0.77977
  Classification -> best τ=0.610 (val F1=0.3601)
  Directional -> Accuracy: 0.5217, MCC: 0.0031, F1: 0.6374

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.69386 | val 0.98753
  Epoch 016 - train 0.63913 | val 1.18613
  Classification -> best τ=0.455 (val F1=0.0499)
  Directional -> Accuracy: 0.6271, MCC: 0.0492, F1: 0.7660

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.66237 | val 0.74335
  Epoch 019 - train 0.64917 | val 1.06691
  Classification -> best τ=0.425 (val F1=0.1304)
  Directional -> Accuracy: 0.5867, MCC: 0.0575, F1: 0.7103

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.64821 | val 0.94471
  Epoch 016 - train 0.64260 | val 1.26527
  Classification -> best τ=0.505 (val F1=0.2197)
  Directional -> Accuracy: 0.4462, MCC: -0.0667, F1: 0.4194

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.69469 | val 0.76872
  Epoch 020 - train 0.64329 | val 0.75391
  Epoch 021 - train 0.65413 | val 0.93844
  Classification -> best τ=0.520 (val F1=0.2940)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.65801 | val 0.72782
  Epoch 018 - train 0.58850 | val 1.06876
  Classification -> best τ=0.550 (val F1=0.2807)
  Directional -> Accuracy: 0.6170, MCC: 0.1251, F1: 0.7273

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.67723 | val 0.71338
  Epoch 017 - train 0.62468 | val 0.70761
  Classification -> best τ=0.435 (val F1=0.2733)
  Directional -> Accuracy: 0.5606, MCC: 0.1857, F1: 0.2927

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.67245 | val 0.70875
  Epoch 018 - train 0.64830 | val 0.74557
  Classification -> best τ=0.485 (val F1=0.3215)
  Directional -> Accuracy: 0.5862, MCC: 0.1522, F1: 0.7333

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.67079 | val 0.69485
  Epoch 020 - train 0.59609 | val 1.04290
  Epoch 024 - train 0.62569 | val 0.80343
  Classification -> best τ=0.525 (val F1=0.1936)
  Directional -> Accuracy: 0.4923, MCC: -0.0077, F1: 0.5217

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.65248 | val 0.64941
  Epoch 020 - train 0.61849 | val 0.80490
  Epoch 028 - train 0.52365 | val 0.91702
  Classification -> best τ=0.385 (val F1=0.3951)
  Directional -> Accuracy: 0.5536, MCC: 0.1158, F1: 0.5614

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.66629 | val 0.69446
  Epoch 020 - train 0.61768 | val 0.76954
  Epoch 029 - train 0.59926 | val 0.81200
  Classification -> best τ=0.560 (val F1=0.1890)
  Directional -> Accuracy: 0.5870, MCC: 0.1700, F1: 0.0952

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.66286 | val 0.68198
  Epoch 016 - train 0.64138 | val 0.68274
  Classification -> best τ=0.555 (val F1=0.1803)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.67470 | val 0.71317
  Epoch 017 - train 0.62849 | val 0.70679
  Classification -> best τ=0.340 (val F1=0.2294)
  Directional -> Accuracy: 0.5614, MCC: 0.3307, F1: 0.3590

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.75041 | val 0.69128
  Epoch 016 - train 0.67189 | val 0.71216
  Classification -> best τ=0.545 (val F1=0.3477)
  Directional -> Accuracy: 0.5854, MCC: 0.1770, F1: 0.5854

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.67965 | val 0.80129
  Epoch 017 - train 0.67999 | val 0.77923
  Classification -> best τ=0.565 (val F1=0.2017)
  Directional -> Accuracy: 0.5349, MCC: 0.0716, F1: 0.5455

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.65368 | val 0.66425
  Epoch 018 - train 0.71385 | val 0.75575
  Classification -> best τ=0.640 (val F1=0.1729)
  Directional -> Accuracy: 0.6047, MCC: 0.2683, F1: 0.5143

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.67340 | val 0.68657
  Epoch 019 - train 0.58061 | val 0.93476
  Classification -> best τ=0.460 (val F1=0.3005)
  Directional -> Accuracy: 0.4800, MCC: 0.0254, F1: 0.2353

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.65399 | val 0.70895
  Epoch 020 - train 0.63566 | val 0.68094
  Epoch 030 - train 0.58473 | val 0.90762
  Epoch 031 - train 0.62215 | val 1.13451
  Classification -> best τ=0.345 (val F1=0.2535)
  Directional -> Accuracy: 0.5479, MCC: 0.0983, F1: 0.5714

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.66600 | val 0.74051
  Epoch 017 - train 0.59587 | val 0.72278
  Classification -> best τ=0.515 (val F1=0.1992)
  Directional -> Accuracy: 0.5676, MCC: 0.1737, F1: 0.6522

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.68323 | val 0.84411
  Epoch 016 - train 0.65324 | val 0.94740
  Classification -> best τ=0.520 (val F1=0.1329)
  Directional -> Accuracy: 0.5455, MCC: 0.1668, F1: 0.6552

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.69311 | val 0.70760
  Epoch 020 - train 0.64381 | val 0.73286
  Classification -> best τ=0.335 (val F1=0.3525)
  Directional -> Accuracy: 0.6364, MCC: 0.2312, F1: 0.7391

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.72079 | val 0.71012
  Epoch 020 - train 0.58474 | val 0.82151
  Classification -> best τ=0.515 (val F1=0.3300)
  Directional -> Accuracy: 0.6190, MCC: 0.2864, F1: 0.5294

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.68994 | val 0.66906
  Epoch 016 - train 0.64269 | val 0.79042
  Classification -> best τ=0.495 (val F1=0.2850)
  Directional -> Accuracy: 0.6071, MCC: 0.2455, F1: 0.6452

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.63332 | val 0.73200
  Epoch 016 - train 0.58347 | val 0.72793
  Classification -> best τ=0.395 (val F1=0.2474)
  Directional -> Accuracy: 0.5000, MCC: -0.0602, F1: 0.5965

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.66245 | val 0.64132
  Epoch 020 - train 0.62223 | val 0.72130
  Epoch 027 - train 0.59926 | val 0.90478
  Classification -> best τ=0.420 (val F1=0.4795)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.67451 | val 0.79283
  Epoch 018 - train 0.62156 | val 0.89465
  Classification -> best τ=0.425 (val F1=0.3882)
  Directional -> Accuracy: 0.5135, MCC: 0.0595, F1: 0.4375

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.66606 | val 0.75040
  Epoch 020 - train 0.63428 | val 0.84293
  Epoch 021 - train 0.62455 | val 0.84240
  Classification -> best τ=0.435 (val F1=0.3135)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.68322 | val 0.70554
  Epoch 017 - train 0.58241 | val 0.75369
  Classification -> best τ=0.470 (val F1=0.2058)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.0000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.69534 | val 0.84788
  Epoch 018 - train 0.54327 | val 0.79995
  Classification -> best τ=0.515 (val F1=0.5270)
  Directional -> Accuracy: 0.4884, MCC: -0.1767, F1: 0.6452

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.66098 | val 0.65378
  Epoch 020 - train 0.60683 | val 0.62364
  Epoch 030 - train 0.54784 | val 0.64001
  Epoch 040 - train 0.45016 | val 0.64143
  Epoch 042 - train 0.48188 | val 0.59194
  Classification -> best τ=0.550 (val F1=0.6590)
  Directional -> Accuracy: 0.3878, MCC: -0.0687, F1: 0.5312

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.68988 | val 1.07446
  Epoch 017 - train 0.63671 | val 2.34823
  Classification -> best τ=0.515 (val F1=0.1676)
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.63181 | val 0.90707
  Epoch 017 - train 0.64454 | val 0.91017
  Classification -> best τ=0.580 (val F1=0.2667)
  Directional -> Accuracy: 0.5357, MCC: 0.0675, F1: 0.2353

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.66487 | val 0.95046
  Epoch 017 - train 0.59765 | val 1.58293
  Classification -> best τ=0.355 (val F1=0.2410)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.66572 | val 0.75509
  Epoch 020 - train 0.66097 | val 0.82226
  Epoch 021 - train 0.60469 | val 0.79681
  Classification -> best τ=0.465 (val F1=0.1168)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.68566 | val 0.68079

[I 2026-02-25 04:39:32,474] Trial 224 finished with value: 0.26827889681784567 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 64, 'learning_rate': 0.007983698466156151, 'weight_decay': 0.000519763878864944, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 0.10693712840882974, 'early_stopping_min_delta': 0.002498551770222542}. Best is trial 200 with value: 0.303360648585588.

  Epoch 019 - train 0.63474 | val 0.75167
  Classification -> best τ=0.425 (val F1=0.3180)
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.26827889681784567
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.64994 | val 0.68751
  Epoch 020 - train 0.61493 | val 0.70139
  Epoch 027 - train 0.60266 | val 0.69047
  Classification -> best τ=0.515 (val F1=0.2919)
  Directional -> Accuracy: 0.4868, MCC: -0.1019, F1: 0.2353

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.62511 | val 0.69735
  Epoch 017 - train 0.62547 | val 0.71517
  Classification -> best τ=0.510 (val F1=0.3254)
  Directional -> Accuracy: 0.6000, MCC: 0.1764, F1: 0.7429

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.68529 | val 0.75318
  Epoch 018 - train 0.64396 | val 0.99269
  Classification -> best τ=0.465 (val F1=0.2398)
  Directional -> Accuracy: 0.5319, MCC: 0.1314, F1: 0.3529

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.67170 | val 0.72041
  Epoch 017 - train 0.65498 | val 0.77377
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.64508 | val 0.64053
  Epoch 020 - train 0.58127 | val 0.72185
  Epoch 024 - train 0.54659 | val 1.00402
  Classification -> best τ=0.560 (val F1=0.5045)
  Directional -> Accuracy: 0.4314, MCC: -0.1306, F1: 0.4082

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.59487 | val 0.71266
  Epoch 018 - train 0.59358 | val 0.72343
  Classification -> best τ=0.460 (val F1=0.1644)
  Directional -> Accuracy: 0.5106, MCC: 0.0283, F1: 0.5660

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.71161 | val 0.68545
  Epoch 020 - train 0.66689 | val 0.70590
  Epoch 024 - train 0.65422 | val 0.80638
  Classification -> best τ=0.535 (val F1=0.2496)
  Directional -> Accuracy: 0.6232, MCC: 0.1639, F1: 0.2353

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.70981 | val 0.61943
  Epoch 020 - train 0.54073 | val 0.67482
  Classification -> best τ=0.310 (val F1=0.2331)
  Directional -> Accuracy: 0.5814, MCC: 0.0664, F1: 0.2500

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.67681 | val 0.68658
  Epoch 018 - train 0.57512 | val 0.85241
  Classification -> best τ=0.500 (val F1=0.2855)
  Directional -> Accuracy: 0.5714, MCC: 0.1118, F1: 0.1600

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.64155 | val 0.71620
  Epoch 020 - train 0.60569 | val 0.69920
  Epoch 030 - train 0.55136 | val 1.07067
  Epoch 032 - train 0.50799 | val 1.06699
  Classification -> best τ=0.505 (val F1=0.2302)
  Directional -> Accuracy: 0.5143, MCC: -0.0085, F1: 0.3929

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.65631 | val 0.70232
  Epoch 018 - train 0.59069 | val 0.77801
  Classification -> best τ=0.515 (val F1=0.2588)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.65202 | val 0.86196
  Epoch 018 - train 0.60489 | val 0.85553
  Classification -> best τ=0.485 (val F1=0.1469)
  Directional -> Accuracy: 0.4138, MCC: -0.2199, F1: 0.5526

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.62081 | val 0.71715
  Epoch 017 - train 0.61497 | val 0.82290
  Classification -> best τ=0.590 (val F1=0.1883)
  Directional -> Accuracy: 0.4524, MCC: -0.1220, F1: 0.3429

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.67486 | val 0.66352
  Epoch 016 - train 0.66165 | val 0.69052
  Classification -> best τ=0.400 (val F1=0.3669)
  Directional -> Accuracy: 0.5667, MCC: 0.1789, F1: 0.6750

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.67551 | val 0.72160
  Epoch 017 - train 0.61598 | val 0.74993
  Classification -> best τ=0.395 (val F1=0.1816)
  Directional -> Accuracy: 0.4231, MCC: -0.1403, F1: 0.4643

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.65788 | val 0.75838
  Epoch 020 - train 0.61615 | val 0.83351
  Epoch 021 - train 0.61423 | val 0.78353
  Classification -> best τ=0.480 (val F1=0.2708)
  Directional -> Accuracy: 0.5507, MCC: 0.0773, F1: 0.6437

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.65228 | val 0.88843
  Epoch 018 - train 0.64047 | val 0.95992
  Classification -> best τ=0.630 (val F1=0.1291)
  Directional -> Accuracy: 0.3898, MCC: 0.1013, F1: 0.0526

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.67314 | val 0.78793
  Epoch 016 - train 0.62799 | val 1.34851
  Classification -> best τ=0.440 (val F1=0.1733)
  Directional -> Accuracy: 0.6000, MCC: 0.0000, F1: 0.7500

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.65460 | val 0.84448
  Epoch 018 - train 0.64136 | val 1.61962
  Classification -> best τ=0.385 (val F1=0.2843)
  Directional -> Accuracy: 0.5231, MCC: 0.1299, F1: 0.4561

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.65687 | val 0.69278
  Epoch 019 - train 0.63549 | val 0.83050
  Classification -> best τ=0.390 (val F1=0.3462)
  Directional -> Accuracy: 0.5333, MCC: -0.1059, F1: 0.6957

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.64693 | val 0.68779
  Epoch 019 - train 0.59745 | val 0.81476
  Classification -> best τ=0.555 (val F1=0.3898)
  Directional -> Accuracy: 0.4255, MCC: 0.1661, F1: 0.1290

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.71208 | val 0.80011
  Epoch 018 - train 0.64972 | val 0.78871
  Classification -> best τ=0.585 (val F1=0.3123)
  Directional -> Accuracy: 0.4091, MCC: -0.2041, F1: 0.2353

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.67085 | val 0.76396
  Epoch 016 - train 0.63817 | val 0.79234
  Classification -> best τ=0.610 (val F1=0.3282)
  Directional -> Accuracy: 0.5000, MCC: 0.0842, F1: 0.3830

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.64947 | val 0.75005
  Epoch 020 - train 0.60316 | val 0.71030
  Epoch 022 - train 0.59848 | val 0.80366
  Classification -> best τ=0.535 (val F1=0.2390)
  Directional -> Accuracy: 0.5692, MCC: 0.1561, F1: 0.6111

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.65724 | val 0.62614
  Epoch 020 - train 0.61463 | val 0.73463
  Epoch 027 - train 0.55903 | val 0.83285
  Classification -> best τ=0.455 (val F1=0.4795)
  Directional -> Accuracy: 0.5714, MCC: 0.1656, F1: 0.5556

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.74211 | val 0.69788
  Epoch 020 - train 0.61917 | val 0.75697
  Epoch 021 - train 0.59672 | val 0.83012
  Classification -> best τ=0.585 (val F1=0.2726)
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.62184 | val 0.68259
  Epoch 018 - train 0.64593 | val 0.69894
  Classification -> best τ=0.570 (val F1=0.0786)
  Directional -> Accuracy: 0.4048, MCC: -0.2240, F1: 0.4898

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.66594 | val 0.72703
  Epoch 019 - train 0.58669 | val 0.74092
  Classification -> best τ=0.390 (val F1=0.1667)
  Directional -> Accuracy: 0.5439, MCC: 0.2218, F1: 0.3810

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.71714 | val 0.66593
  Epoch 020 - train 0.63424 | val 0.75814
  Epoch 030 - train 0.56623 | val 0.65553
  Epoch 040 - train 0.55679 | val 0.76611
  Epoch 042 - train 0.55170 | val 0.83838
  Classification -> best τ=0.485 (val F1=0.3518)
  Directional -> Accuracy: 0.5366, MCC: 0.0241, F1: 0.6780

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.70485 | val 0.76132
  Epoch 020 - train 0.62628 | val 0.84650
  Epoch 021 - train 0.60918 | val 0.89209
  Classification -> best τ=0.510 (val F1=0.1959)
  Directional -> Accuracy: 0.5116, MCC: 0.0397, F1: 0.6038

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.64034 | val 0.71329
  Epoch 020 - train 0.62659 | val 0.64858
  Epoch 022 - train 0.61209 | val 0.69977
  Classification -> best τ=0.640 (val F1=0.2525)
  Directional -> Accuracy: 0.4419, MCC: -0.0944, F1: 0.2941

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.63421 | val 0.78487
  Epoch 016 - train 0.58205 | val 0.91569
  Classification -> best τ=0.540 (val F1=0.2969)
  Directional -> Accuracy: 0.4400, MCC: -0.1548, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.65800 | val 0.76321
  Epoch 020 - train 0.62727 | val 0.86572
  Epoch 030 - train 0.60158 | val 1.16413
  Epoch 033 - train 0.57419 | val 1.35514
  Classification -> best τ=0.270 (val F1=0.3602)
  Directional -> Accuracy: 0.5479, MCC: 0.1291, F1: 0.5217

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.64649 | val 0.83650
  Epoch 016 - train 0.70457 | val 0.77280
  Classification -> best τ=0.495 (val F1=0.1992)
  Directional -> Accuracy: 0.4324, MCC: -0.1327, F1: 0.4615

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.67771 | val 0.75934
  Epoch 019 - train 0.62207 | val 0.87717
  Classification -> best τ=0.480 (val F1=0.3121)
  Directional -> Accuracy: 0.5682, MCC: 0.3022, F1: 0.6885

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.68727 | val 0.72971
  Epoch 019 - train 0.65751 | val 0.72184
  Classification -> best τ=0.400 (val F1=0.3280)
  Directional -> Accuracy: 0.6212, MCC: 0.2778, F1: 0.6154

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.67727 | val 0.67137
  Epoch 020 - train 0.57069 | val 0.83137
  Epoch 025 - train 0.53347 | val 0.91313
  Classification -> best τ=0.595 (val F1=0.3873)
  Directional -> Accuracy: 0.5000, MCC: 0.1489, F1: 0.0870

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.66743 | val 0.67711
  Epoch 016 - train 0.63889 | val 0.69529
  Classification -> best τ=0.385 (val F1=0.2450)
  Directional -> Accuracy: 0.5357, MCC: 0.1536, F1: 0.6389

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.62347 | val 0.67404
  Epoch 020 - train 0.63874 | val 0.77167
  Epoch 025 - train 0.57821 | val 0.77595
  Classification -> best τ=0.370 (val F1=0.2474)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.66185 | val 0.68336
  Epoch 020 - train 0.61934 | val 0.64304
  Epoch 030 - train 0.50412 | val 0.81327
  Epoch 035 - train 0.50790 | val 0.93067
  Classification -> best τ=0.310 (val F1=0.4188)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.65869 | val 0.93358
  Epoch 016 - train 0.62266 | val 0.96729
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.66301 | val 0.67913
  Epoch 020 - train 0.57592 | val 0.92778
  Epoch 024 - train 0.56379 | val 1.20564
  Classification -> best τ=0.390 (val F1=0.3358)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.62171 | val 0.67424
  Epoch 020 - train 0.66920 | val 0.69117
  Epoch 027 - train 0.58818 | val 0.69624
  Classification -> best τ=0.460 (val F1=0.3367)
  Directional -> Accuracy: 0.4783, MCC: -0.0134, F1: 0.1429

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.61559 | val 0.76112
  Epoch 020 - train 0.57084 | val 0.80428
  Epoch 028 - train 0.60211 | val 0.77691
  Classification -> best τ=0.540 (val F1=0.6325)
  Directional -> Accuracy: 0.6512, MCC: 0.2861, F1: 0.7368

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.70425 | val 0.70929
  Epoch 020 - train 0.62268 | val 0.70097
  Epoch 022 - train 0.58056 | val 0.69665
  Classification -> best τ=0.565 (val F1=0.6290)
  Directional -> Accuracy: 0.3673, MCC: -0.1468, F1: 0.5079

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.70343 | val 0.82238
  Epoch 016 - train 0.64628 | val 1.05276
  Classification -> best τ=0.475 (val F1=0.2037)
  Directional -> Accuracy: 0.5000, MCC: -0.0499, F1: 0.6216

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.68508 | val 0.83081
  Epoch 016 - train 0.66902 | val 1.47937
  Classification -> best τ=0.565 (val F1=0.3376)
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.68336 | val 1.13668
  Epoch 018 - train 0.63409 | val 1.76808
  Classification -> best τ=0.515 (val F1=0.2078)
  Directional -> Accuracy: 0.6296, MCC: 0.2570, F1: 0.6667

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.65237 | val 0.78967
  Epoch 017 - train 0.61639 | val 0.96621
  Classification -> best τ=0.400 (val F1=0.1794)
  Directional -> Accuracy: 0.5536, MCC: 0.1072, F1: 0.5614

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.68251 | val 0.69197
  Epoch 020 - train 0.59825 | val 0.72953
  Epoch 021 - train 0.63641 | val 0.76822

[I 2026-02-25 04:41:39,995] Trial 225 finished with value: 0.2781086390004812 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 64, 'learning_rate': 0.006169525433611565, 'weight_decay': 0.000444051664189727, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 0.1389100076144629, 'early_stopping_min_delta': 0.002947055218801055}. Best is trial 200 with value: 0.303360648585588.

  Classification -> best τ=0.395 (val F1=0.3103)
  Directional -> Accuracy: 0.5246, MCC: 0.1648, F1: 0.6588

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2781086390004812
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.64722 | val 0.69950
  Epoch 016 - train 0.65586 | val 0.75546
  Classification -> best τ=0.480 (val F1=0.2627)
  Directional -> Accuracy: 0.5658, MCC: 0.0832, F1: 0.2979

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.65216 | val 0.70938
  Epoch 020 - train 0.63966 | val 0.71168
  Epoch 030 - train 0.58104 | val 0.75795
  Epoch 033 - train 0.56076 | val 0.72882
  Classification -> best τ=0.525 (val F1=0.1700)
  Directional -> Accuracy: 0.6444, MCC: 0.2960, F1: 0.6667

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.64918 | val 0.71942
  Epoch 020 - train 0.64835 | val 0.80906
  Epoch 028 - train 0.61624 | val 0.93923
  Classification -> best τ=0.590 (val F1=0.2449)
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.68229 | val 0.72784
  Epoch 017 - train 0.65521 | val 0.70413
  Classification -> best τ=0.535 (val F1=0.1141)
  Directional -> Accuracy: 0.5067, MCC: -0.1859, F1: 0.6726

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.66828 | val 0.64731
  Epoch 020 - train 0.61450 | val 0.66568
  Epoch 026 - train 0.58577 | val 0.75509
  Classification -> best τ=0.520 (val F1=0.4158)
  Directional -> Accuracy: 0.5294, MCC: 0.0291, F1: 0.6471

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.60042 | val 0.74812
  Epoch 019 - train 0.59907 | val 0.74548
  Classification -> best τ=0.485 (val F1=0.2582)
  Directional -> Accuracy: 0.5532, MCC: 0.2154, F1: 0.1600

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.68362 | val 0.69933
  Epoch 018 - train 0.68387 | val 0.69367
  Classification -> best τ=0.600 (val F1=0.2227)
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.59635 | val 0.64979
  Epoch 020 - train 0.49190 | val 0.84380
  Epoch 021 - train 0.68869 | val 0.86538
  Classification -> best τ=0.340 (val F1=0.1823)
  Directional -> Accuracy: 0.4884, MCC: -0.0866, F1: 0.3125

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.63692 | val 0.70898
  Epoch 019 - train 0.55586 | val 0.91232
  Classification -> best τ=0.470 (val F1=0.1978)
  Directional -> Accuracy: 0.4694, MCC: 0.1303, F1: 0.6286

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.64920 | val 0.68262
  Epoch 020 - train 0.63046 | val 0.73570
  Epoch 025 - train 0.57844 | val 0.70029
  Classification -> best τ=0.245 (val F1=0.1816)
  Directional -> Accuracy: 0.4571, MCC: 0.0888, F1: 0.6042

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.62393 | val 0.82214
  Epoch 018 - train 0.59680 | val 1.52018
  Classification -> best τ=0.405 (val F1=0.2408)
  Directional -> Accuracy: 0.6200, MCC: 0.2330, F1: 0.4571

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.66825 | val 0.71523
  Epoch 016 - train 0.59126 | val 1.36630
  Classification -> best τ=0.520 (val F1=0.1834)
  Directional -> Accuracy: 0.4828, MCC: -0.0413, F1: 0.5946

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.66127 | val 0.86297
  Epoch 016 - train 0.61266 | val 0.82695
  Classification -> best τ=0.430 (val F1=0.2731)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.70098 | val 0.68525
  Epoch 020 - train 0.64482 | val 0.84462
  Epoch 029 - train 0.64780 | val 0.77570
  Classification -> best τ=0.480 (val F1=0.3407)
  Directional -> Accuracy: 0.6333, MCC: 0.2828, F1: 0.6857

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.63056 | val 0.85707
  Epoch 018 - train 0.61751 | val 0.82145
  Classification -> best τ=0.475 (val F1=0.1852)
  Directional -> Accuracy: 0.5577, MCC: 0.1512, F1: 0.0800

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.69171 | val 0.69246
  Epoch 020 - train 0.63996 | val 0.69928
  Epoch 022 - train 0.63781 | val 0.72238
  Classification -> best τ=0.495 (val F1=0.2684)
  Directional -> Accuracy: 0.5072, MCC: 0.0311, F1: 0.4688

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.65072 | val 0.75943
  Epoch 016 - train 0.63192 | val 0.93217
  Classification -> best τ=0.615 (val F1=0.2559)
  Directional -> Accuracy: 0.3729, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.66255 | val 0.85401
  Epoch 020 - train 0.66801 | val 0.98302
  Classification -> best τ=0.445 (val F1=0.1764)
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.6600

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.65545 | val 1.00016
  Epoch 018 - train 0.64614 | val 1.49195
  Classification -> best τ=0.445 (val F1=0.2752)
  Directional -> Accuracy: 0.5077, MCC: 0.1597, F1: 0.3600

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.69307 | val 0.67086
  Epoch 020 - train 0.66385 | val 0.67324
  Classification -> best τ=0.445 (val F1=0.2852)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.72464 | val 0.70855
  Epoch 018 - train 0.64753 | val 0.76527
  Classification -> best τ=0.500 (val F1=0.3278)
  Directional -> Accuracy: 0.4894, MCC: -0.0168, F1: 0.5385

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.65619 | val 0.81345
  Epoch 017 - train 0.63510 | val 0.79425
  Classification -> best τ=0.575 (val F1=0.1895)
  Directional -> Accuracy: 0.5152, MCC: 0.0727, F1: 0.1111

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.65536 | val 0.66095
  Epoch 020 - train 0.63738 | val 0.74313
  Epoch 025 - train 0.63712 | val 0.72611
  Classification -> best τ=0.620 (val F1=0.2914)
  Directional -> Accuracy: 0.5517, MCC: 0.0951, F1: 0.5938

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.70813 | val 0.71382
  Epoch 020 - train 0.61644 | val 0.70586
  Epoch 027 - train 0.59152 | val 0.76478
  Classification -> best τ=0.645 (val F1=0.2390)
  Directional -> Accuracy: 0.4308, MCC: -0.1779, F1: 0.2449

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.69347 | val 0.76981
  Epoch 020 - train 0.60323 | val 0.65446
  Epoch 028 - train 0.53343 | val 0.84283
  Classification -> best τ=0.490 (val F1=0.4149)
  Directional -> Accuracy: 0.5000, MCC: 0.0684, F1: 0.3636

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.66880 | val 0.74164
  Epoch 017 - train 0.59776 | val 0.76732
  Classification -> best τ=0.450 (val F1=0.2935)
  Directional -> Accuracy: 0.4783, MCC: 0.1870, F1: 0.6250

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.67314 | val 0.72104
  Epoch 018 - train 0.62762 | val 0.68863
  Classification -> best τ=0.580 (val F1=0.1250)
  Directional -> Accuracy: 0.5238, MCC: 0.0000, F1: 0.6154

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.67105 | val 0.68992
  Epoch 020 - train 0.63859 | val 0.70676
  Epoch 028 - train 0.60095 | val 0.68588
  Classification -> best τ=0.465 (val F1=0.2391)
  Directional -> Accuracy: 0.5263, MCC: 0.2741, F1: 0.2703

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.65821 | val 0.99625
  Epoch 016 - train 0.58251 | val 0.90823
  Classification -> best τ=0.530 (val F1=0.2618)
  Directional -> Accuracy: 0.5854, MCC: 0.2437, F1: 0.7213

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.67854 | val 1.09183
  Epoch 020 - train 0.58742 | val 1.22865
  Classification -> best τ=0.560 (val F1=0.2814)
  Directional -> Accuracy: 0.5116, MCC: 0.0528, F1: 0.6316

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.69926 | val 0.69232
  Epoch 019 - train 0.68083 | val 0.84627
  Classification -> best τ=0.520 (val F1=0.2517)
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.62851 | val 0.72174
  Epoch 020 - train 0.54951 | val 1.17964
  Classification -> best τ=0.705 (val F1=0.2399)
  Directional -> Accuracy: 0.4800, MCC: 0.1319, F1: 0.0714

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.69590 | val 0.66653
  Epoch 020 - train 0.65293 | val 0.71274
  Epoch 028 - train 0.63305 | val 0.79608
  Classification -> best τ=0.340 (val F1=0.3396)
  Directional -> Accuracy: 0.5616, MCC: 0.1446, F1: 0.5556

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.71913 | val 0.75771
  Epoch 020 - train 0.63788 | val 0.90339
  Classification -> best τ=0.455 (val F1=0.2833)
  Directional -> Accuracy: 0.5405, MCC: 0.1348, F1: 0.6531

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.67382 | val 0.82467
  Epoch 020 - train 0.64688 | val 1.04620
  Classification -> best τ=0.495 (val F1=0.2294)
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.69672 | val 0.71402
  Epoch 020 - train 0.63744 | val 0.76091
  Epoch 027 - train 0.62121 | val 0.72328
  Classification -> best τ=0.565 (val F1=0.1970)
  Directional -> Accuracy: 0.4242, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.64765 | val 0.68333
  Epoch 020 - train 0.61263 | val 0.88246
  Epoch 024 - train 0.53718 | val 0.89589
  Classification -> best τ=0.600 (val F1=0.2740)
  Directional -> Accuracy: 0.4762, MCC: -0.0155, F1: 0.1538

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.67902 | val 0.67068
  Epoch 018 - train 0.64742 | val 0.68039
  Classification -> best τ=0.380 (val F1=0.2622)
  Directional -> Accuracy: 0.5714, MCC: 0.2471, F1: 0.6667

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.64587 | val 0.74460
  Epoch 018 - train 0.59173 | val 0.92216
  Classification -> best τ=0.370 (val F1=0.1195)
  Directional -> Accuracy: 0.6522, MCC: 0.2659, F1: 0.7778

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.62531 | val 0.72110
  Epoch 020 - train 0.61547 | val 0.66941
  Epoch 030 - train 0.60338 | val 0.63366
  Epoch 040 - train 0.57598 | val 0.69983
  Epoch 043 - train 0.56120 | val 0.67180
  Classification -> best τ=0.340 (val F1=0.5815)
  Directional -> Accuracy: 0.3469, MCC: -0.1894, F1: 0.5152

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.63285 | val 0.74960
  Epoch 017 - train 0.56196 | val 1.04717
  Classification -> best τ=0.530 (val F1=0.2623)
  Directional -> Accuracy: 0.5135, MCC: 0.2204, F1: 0.1818

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.65546 | val 0.70372
  Epoch 020 - train 0.61932 | val 0.99280
  Epoch 021 - train 0.62980 | val 1.01480
  Classification -> best τ=0.470 (val F1=0.4217)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.60193 | val 0.67988
  Epoch 020 - train 0.61702 | val 0.70924
  Epoch 026 - train 0.63034 | val 0.77074
  Classification -> best τ=0.435 (val F1=0.4141)
  Directional -> Accuracy: 0.4348, MCC: -0.1232, F1: 0.3500

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.69011 | val 0.81732
  Epoch 020 - train 0.59566 | val 0.79103
  Epoch 021 - train 0.65359 | val 0.78339
  Classification -> best τ=0.450 (val F1=0.5270)
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.7164

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.67794 | val 0.66357
  Epoch 020 - train 0.60593 | val 0.76479
  Epoch 023 - train 0.61057 | val 0.70392
  Classification -> best τ=0.510 (val F1=0.5421)
  Directional -> Accuracy: 0.3878, MCC: -0.0687, F1: 0.5312

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.65462 | val 0.79944
  Epoch 017 - train 0.67525 | val 0.93624
  Classification -> best τ=0.500 (val F1=0.2392)
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.63883 | val 0.78100
  Epoch 018 - train 0.64867 | val 1.08445
  Classification -> best τ=0.620 (val F1=0.4387)
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.69514 | val 0.86649
  Epoch 016 - train 0.65572 | val 1.26749
  Classification -> best τ=0.415 (val F1=0.2618)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.68410 | val 0.74073
  Epoch 016 - train 0.65208 | val 0.75313
  Classification -> best τ=0.495 (val F1=0.1168)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.68795 | val 0.68424

[I 2026-02-25 04:43:48,958] Trial 226 finished with value: 0.2732946766586392 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 64, 'learning_rate': 0.008139085441751678, 'weight_decay': 0.0006330745593250385, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 0.2020933757904055, 'early_stopping_min_delta': 0.002755603466848263}. Best is trial 200 with value: 0.303360648585588.

  Epoch 018 - train 0.66442 | val 0.68904
  Classification -> best τ=0.455 (val F1=0.2651)
  Directional -> Accuracy: 0.5082, MCC: 0.0140, F1: 0.4828

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2732946766586392
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.62804 | val 0.89100
  Epoch 019 - train 0.57950 | val 0.91481
  Classification -> best τ=0.505 (val F1=0.2510)
  Directional -> Accuracy: 0.5526, MCC: 0.0458, F1: 0.2609

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.62622 | val 0.68995
  Epoch 016 - train 0.56590 | val 0.72563
  Classification -> best τ=0.455 (val F1=0.1274)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.72986 | val 0.71940
  Epoch 018 - train 0.65978 | val 0.89132
  Classification -> best τ=0.530 (val F1=0.3482)
  Directional -> Accuracy: 0.4894, MCC: 0.1383, F1: 0.0769

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.69138 | val 0.70762
  Epoch 016 - train 0.64191 | val 0.74109
  Classification -> best τ=0.460 (val F1=0.0763)
  Directional -> Accuracy: 0.5333, MCC: 0.0134, F1: 0.6535

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.61310 | val 0.74661
  Epoch 018 - train 0.57655 | val 0.72921
  Classification -> best τ=0.505 (val F1=0.3622)
  Directional -> Accuracy: 0.5490, MCC: 0.0806, F1: 0.6761

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.64620 | val 0.77651
  Epoch 016 - train 0.55825 | val 0.69639
  Classification -> best τ=0.535 (val F1=0.2928)
  Directional -> Accuracy: 0.6170, MCC: 0.2375, F1: 0.5500

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.68030 | val 0.71525
  Epoch 020 - train 0.63933 | val 0.80967
  Epoch 021 - train 0.63967 | val 0.89430
  Classification -> best τ=0.435 (val F1=0.2732)
  Directional -> Accuracy: 0.4493, MCC: 0.0822, F1: 0.5778

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.59302 | val 0.61098
  Epoch 020 - train 0.53784 | val 0.88843
  Epoch 025 - train 0.53885 | val 0.91898
  Classification -> best τ=0.365 (val F1=0.4047)
  Directional -> Accuracy: 0.4419, MCC: -0.0852, F1: 0.4545

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.64944 | val 0.70789
  Epoch 020 - train 0.54417 | val 0.91058
  Classification -> best τ=0.410 (val F1=0.3461)
  Directional -> Accuracy: 0.7143, MCC: 0.4226, F1: 0.6818

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.61802 | val 0.72202
  Epoch 016 - train 0.61767 | val 0.89848
  Classification -> best τ=0.500 (val F1=0.2453)
  Directional -> Accuracy: 0.5143, MCC: 0.0683, F1: 0.5405

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.67778 | val 0.76501
  Epoch 019 - train 0.56282 | val 1.57340
  Classification -> best τ=0.535 (val F1=0.3118)
  Directional -> Accuracy: 0.6600, MCC: 0.3634, F1: 0.4516

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.63441 | val 0.77902
  Epoch 016 - train 0.57158 | val 1.27484
  Classification -> best τ=0.475 (val F1=0.1469)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.63038 | val 0.71163
  Epoch 016 - train 0.59023 | val 0.90285
  Classification -> best τ=0.430 (val F1=0.2731)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.64487 | val 0.69707
  Epoch 017 - train 0.59839 | val 0.91341
  Classification -> best τ=0.460 (val F1=0.3477)
  Directional -> Accuracy: 0.5500, MCC: 0.1214, F1: 0.6494

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.63278 | val 0.71035
  Epoch 020 - train 0.56999 | val 0.90465
  Classification -> best τ=0.570 (val F1=0.2673)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.65238 | val 0.72657
  Epoch 018 - train 0.60080 | val 0.72818
  Classification -> best τ=0.730 (val F1=0.1728)
  Directional -> Accuracy: 0.4638, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.66510 | val 0.82573
  Epoch 017 - train 0.60871 | val 1.22848
  Classification -> best τ=0.630 (val F1=0.1291)
  Directional -> Accuracy: 0.3729, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.68897 | val 0.82201
  Epoch 016 - train 0.63349 | val 1.12390
  Classification -> best τ=0.515 (val F1=0.2236)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.65329 | val 0.96907
  Epoch 018 - train 0.62966 | val 1.62290
  Classification -> best τ=0.360 (val F1=0.3140)
  Directional -> Accuracy: 0.5231, MCC: 0.0233, F1: 0.5867

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.64917 | val 0.70987
  Epoch 018 - train 0.59296 | val 0.88526
  Classification -> best τ=0.585 (val F1=0.2606)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.62857 | val 0.76446
  Epoch 016 - train 0.56919 | val 0.95528
  Classification -> best τ=0.490 (val F1=0.1586)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.66084 | val 0.75169
  Epoch 018 - train 0.56999 | val 0.78842
  Classification -> best τ=0.455 (val F1=0.2855)
  Directional -> Accuracy: 0.6061, MCC: 0.2342, F1: 0.6750

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.64232 | val 0.77443
  Epoch 016 - train 0.63666 | val 0.74985
  Classification -> best τ=0.660 (val F1=0.2864)
  Directional -> Accuracy: 0.5000, MCC: 0.2369, F1: 0.2162

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.62283 | val 0.73668
  Epoch 020 - train 0.60819 | val 0.84260
  Classification -> best τ=0.505 (val F1=0.1507)
  Directional -> Accuracy: 0.5692, MCC: 0.1509, F1: 0.6000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.62851 | val 0.65104
  Epoch 020 - train 0.57845 | val 0.72080
  Epoch 026 - train 0.52524 | val 0.82818
  Classification -> best τ=0.575 (val F1=0.3495)
  Directional -> Accuracy: 0.4821, MCC: 0.0587, F1: 0.2564

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.73011 | val 0.75935
  Epoch 016 - train 0.59074 | val 0.81050
  Classification -> best τ=0.420 (val F1=0.2935)
  Directional -> Accuracy: 0.5217, MCC: 0.0881, F1: 0.5600

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.66162 | val 0.68411
  Epoch 016 - train 0.61639 | val 0.73686
  Classification -> best τ=0.575 (val F1=0.1936)
  Directional -> Accuracy: 0.4048, MCC: -0.1291, F1: 0.1935

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.63511 | val 0.68426
  Epoch 020 - train 0.60035 | val 0.79521
  Classification -> best τ=0.340 (val F1=0.2260)
  Directional -> Accuracy: 0.5789, MCC: 0.1193, F1: 0.6667

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.62062 | val 0.66325
  Epoch 020 - train 0.63954 | val 0.67390
  Epoch 030 - train 0.60629 | val 0.69866
  Epoch 040 - train 0.56896 | val 0.96684
  Epoch 043 - train 0.49511 | val 0.89577
  Classification -> best τ=0.355 (val F1=0.4862)
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.64531 | val 0.79407
  Epoch 016 - train 0.60207 | val 0.95896
  Classification -> best τ=0.530 (val F1=0.2814)
  Directional -> Accuracy: 0.4884, MCC: -0.0318, F1: 0.3889

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.62345 | val 0.66668
  Epoch 020 - train 0.59856 | val 0.70184
  Epoch 025 - train 0.55293 | val 0.92868
  Classification -> best τ=0.550 (val F1=0.1886)
  Directional -> Accuracy: 0.4419, MCC: -0.1655, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.57402 | val 0.88661
  Epoch 020 - train 0.53023 | val 1.61225
  Epoch 021 - train 0.55280 | val 1.41172
  Classification -> best τ=0.655 (val F1=0.2969)
  Directional -> Accuracy: 0.5000, MCC: -0.1242, F1: 0.6575

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.62514 | val 0.67861
  Epoch 018 - train 0.61149 | val 0.73659
  Classification -> best τ=0.345 (val F1=0.3809)
  Directional -> Accuracy: 0.5616, MCC: 0.1446, F1: 0.5556

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.63899 | val 0.74476
  Epoch 016 - train 0.59994 | val 0.74048
  Classification -> best τ=0.480 (val F1=0.1992)
  Directional -> Accuracy: 0.5676, MCC: 0.1737, F1: 0.6522

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.62565 | val 0.77840
  Epoch 016 - train 0.64770 | val 0.82559
  Classification -> best τ=0.490 (val F1=0.2757)
  Directional -> Accuracy: 0.5227, MCC: 0.2085, F1: 0.6667

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.67699 | val 0.71969
  Epoch 016 - train 0.65033 | val 0.78078
  Classification -> best τ=0.460 (val F1=0.3525)
  Directional -> Accuracy: 0.6212, MCC: 0.2453, F1: 0.6479

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.63758 | val 0.82149
  Epoch 016 - train 0.58559 | val 0.87386
  Classification -> best τ=0.500 (val F1=0.2819)
  Directional -> Accuracy: 0.6905, MCC: 0.4122, F1: 0.6486

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.63880 | val 0.70852
  Epoch 017 - train 0.60946 | val 0.76395
  Classification -> best τ=0.415 (val F1=0.2829)
  Directional -> Accuracy: 0.5000, MCC: 0.0910, F1: 0.6316

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.60477 | val 0.69033
  Epoch 019 - train 0.59110 | val 0.89468
  Classification -> best τ=0.530 (val F1=0.2441)
  Directional -> Accuracy: 0.3913, MCC: -0.0687, F1: 0.1250

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.70083 | val 0.65241
  Epoch 020 - train 0.58583 | val 0.69810
  Epoch 027 - train 0.54684 | val 0.74803
  Classification -> best τ=0.375 (val F1=0.4141)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.63627 | val 0.78978
  Epoch 016 - train 0.62247 | val 0.82391
  Classification -> best τ=0.480 (val F1=0.1525)
  Directional -> Accuracy: 0.5135, MCC: -0.0472, F1: 0.6538

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.61793 | val 0.70639
  Epoch 020 - train 0.59374 | val 1.13021
  Epoch 022 - train 0.58727 | val 1.22291
  Classification -> best τ=0.410 (val F1=0.4387)
  Directional -> Accuracy: 0.5200, MCC: 0.1633, F1: 0.6727

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.71662 | val 0.69668
  Epoch 020 - train 0.63846 | val 0.68494
  Epoch 027 - train 0.53239 | val 0.74023
  Classification -> best τ=0.445 (val F1=0.4515)
  Directional -> Accuracy: 0.5217, MCC: 0.2041, F1: 0.1538

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.64371 | val 0.68835
  Epoch 020 - train 0.63900 | val 0.64833
  Epoch 030 - train 0.52595 | val 0.59545
  Epoch 040 - train 0.48351 | val 0.55819
  Epoch 050 - train 0.42087 | val 0.55447
  Classification -> best τ=0.155 (val F1=0.5752)
  Directional -> Accuracy: 0.5814, MCC: 0.1240, F1: 0.7188

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.61558 | val 0.61717
  Epoch 020 - train 0.60184 | val 0.69735
  Epoch 030 - train 0.53715 | val 0.64557
  Epoch 038 - train 0.50671 | val 0.69600
  Classification -> best τ=0.510 (val F1=0.5421)
  Directional -> Accuracy: 0.3878, MCC: -0.0687, F1: 0.5312

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.66604 | val 0.99711
  Epoch 016 - train 0.63121 | val 1.24769
  Classification -> best τ=0.325 (val F1=0.2958)
  Directional -> Accuracy: 0.6786, MCC: 0.3721, F1: 0.6667

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.63389 | val 0.98739
  Epoch 018 - train 0.63229 | val 1.47887
  Classification -> best τ=0.580 (val F1=0.3992)
  Directional -> Accuracy: 0.5536, MCC: 0.1279, F1: 0.2424

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.65238 | val 1.16254
  Epoch 016 - train 0.64166 | val 1.76725
  Classification -> best τ=0.455 (val F1=0.1562)
  Directional -> Accuracy: 0.5000, MCC: -0.0521, F1: 0.6494

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.60632 | val 0.82317
  Epoch 017 - train 0.59971 | val 0.78512
  Classification -> best τ=0.415 (val F1=0.1168)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.68828 | val 0.68549
  Epoch 020 - train 0.61716 | val 0.76314

[I 2026-02-25 04:44:51,888] Trial 227 finished with value: 0.28369589624172886 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 64, 'learning_rate': 0.005512617808077223, 'weight_decay': 0.0005287135998350913, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 0.24017896177148257, 'early_stopping_min_delta': 0.0031824435939044405}. Best is trial 200 with value: 0.303360648585588.

  Epoch 024 - train 0.58158 | val 0.89296
  Classification -> best τ=0.485 (val F1=0.2544)
  Directional -> Accuracy: 0.4918, MCC: -0.0401, F1: 0.3404

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.28369589624172886
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.64076 | val 0.80825
  Epoch 018 - train 0.58335 | val 1.03962
  Classification -> best τ=0.515 (val F1=0.2082)
  Directional -> Accuracy: 0.5263, MCC: 0.0206, F1: 0.4000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.63445 | val 0.72910
  Epoch 016 - train 0.60144 | val 0.71012
  Classification -> best τ=0.460 (val F1=0.2370)
  Directional -> Accuracy: 0.6000, MCC: 0.1764, F1: 0.7429

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.67015 | val 0.77419
  Epoch 016 - train 0.62822 | val 0.92383
  Classification -> best τ=0.575 (val F1=0.1383)
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.65659 | val 0.82460
  Epoch 018 - train 0.67183 | val 0.70587
  Classification -> best τ=0.465 (val F1=0.0877)
  Directional -> Accuracy: 0.5333, MCC: 0.0286, F1: 0.6316

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.60663 | val 0.62808
  Epoch 020 - train 0.57553 | val 0.78282
  Epoch 023 - train 0.58410 | val 0.66069
  Classification -> best τ=0.520 (val F1=0.4457)
  Directional -> Accuracy: 0.5490, MCC: 0.0860, F1: 0.6102

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.62891 | val 0.73839
  Epoch 016 - train 0.59193 | val 0.95217
  Classification -> best τ=0.540 (val F1=0.2357)
  Directional -> Accuracy: 0.4681, MCC: -0.0687, F1: 0.6032

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.65657 | val 0.71463
  Epoch 018 - train 0.64648 | val 0.69858
  Classification -> best τ=0.465 (val F1=0.2384)
  Directional -> Accuracy: 0.5072, MCC: 0.0835, F1: 0.5405

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.76510 | val 0.70886
  Epoch 020 - train 0.58796 | val 0.78341
  Epoch 021 - train 0.53218 | val 0.75788
  Classification -> best τ=0.280 (val F1=0.2218)
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.61796 | val 0.68792
  Epoch 020 - train 0.54317 | val 1.09366
  Epoch 021 - train 0.53612 | val 1.16955
  Classification -> best τ=0.430 (val F1=0.4249)
  Directional -> Accuracy: 0.6531, MCC: 0.2922, F1: 0.5854

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.63878 | val 0.72102
  Epoch 016 - train 0.60632 | val 0.72257
  Classification -> best τ=0.510 (val F1=0.1337)
  Directional -> Accuracy: 0.6286, MCC: 0.2333, F1: 0.3158

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.65890 | val 0.77564
  Epoch 016 - train 0.58998 | val 1.02818
  Classification -> best τ=0.475 (val F1=0.1375)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.63015 | val 0.82447
  Epoch 017 - train 0.53456 | val 1.18501
  Classification -> best τ=0.555 (val F1=0.1194)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.58090 | val 1.02310
  Epoch 016 - train 0.58308 | val 1.31274
  Classification -> best τ=0.450 (val F1=0.1908)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.64051 | val 0.63233
  Epoch 020 - train 0.62330 | val 0.72451
  Epoch 030 - train 0.55767 | val 0.72361
  Classification -> best τ=0.380 (val F1=0.3477)
  Directional -> Accuracy: 0.5167, MCC: 0.1302, F1: 0.6742

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.62147 | val 0.81863
  Epoch 017 - train 0.59887 | val 0.81233
  Classification -> best τ=0.495 (val F1=0.2160)
  Directional -> Accuracy: 0.5385, MCC: 0.0154, F1: 0.0769

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.62942 | val 0.79283
  Epoch 018 - train 0.59674 | val 0.96186
  Classification -> best τ=0.375 (val F1=0.2265)
  Directional -> Accuracy: 0.5362, MCC: 0.0299, F1: 0.6667

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.65026 | val 1.00753
  Epoch 017 - train 0.65017 | val 1.14363
  Classification -> best τ=0.615 (val F1=0.2276)
  Directional -> Accuracy: 0.4068, MCC: 0.1444, F1: 0.1026

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.66774 | val 0.81759
  Epoch 016 - train 0.64312 | val 1.07748
  Classification -> best τ=0.480 (val F1=0.1132)
  Directional -> Accuracy: 0.6133, MCC: 0.1576, F1: 0.7071

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.63070 | val 1.38381
  Epoch 019 - train 0.61404 | val 2.08724
  Classification -> best τ=0.480 (val F1=0.3539)
  Directional -> Accuracy: 0.4154, MCC: -0.0306, F1: 0.0500

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.64922 | val 0.66546
  Epoch 020 - train 0.62990 | val 0.74129
  Epoch 024 - train 0.58717 | val 0.90792
  Classification -> best τ=0.515 (val F1=0.3038)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.64784 | val 0.69707
  Epoch 016 - train 0.61662 | val 0.81080
  Classification -> best τ=0.570 (val F1=0.1918)
  Directional -> Accuracy: 0.4681, MCC: 0.2403, F1: 0.2424

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.67092 | val 0.71539
  Epoch 017 - train 0.62186 | val 0.83243
  Classification -> best τ=0.540 (val F1=0.2072)
  Directional -> Accuracy: 0.6061, MCC: 0.2125, F1: 0.6176

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.68197 | val 0.77762
  Epoch 017 - train 0.61879 | val 0.86081
  Classification -> best τ=0.555 (val F1=0.2379)
  Directional -> Accuracy: 0.5345, MCC: 0.1323, F1: 0.4706

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.64704 | val 0.69834
  Epoch 016 - train 0.61106 | val 0.76332
  Classification -> best τ=0.470 (val F1=0.1936)
  Directional -> Accuracy: 0.5231, MCC: 0.1330, F1: 0.6517

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.64010 | val 0.66244
  Epoch 020 - train 0.57229 | val 0.79046
  Epoch 023 - train 0.54723 | val 0.76899
  Classification -> best τ=0.420 (val F1=0.4795)
  Directional -> Accuracy: 0.5000, MCC: 0.0196, F1: 0.4815

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.63676 | val 0.72460
  Epoch 016 - train 0.63245 | val 0.75461
  Classification -> best τ=0.450 (val F1=0.2935)
  Directional -> Accuracy: 0.4783, MCC: 0.0370, F1: 0.5714

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.69277 | val 0.69943
  Epoch 016 - train 0.63585 | val 0.69426
  Classification -> best τ=0.575 (val F1=0.1936)
  Directional -> Accuracy: 0.4286, MCC: -0.0807, F1: 0.2941

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.63207 | val 0.75234
  Epoch 016 - train 0.59822 | val 0.81337
  Classification -> best τ=0.510 (val F1=0.2225)
  Directional -> Accuracy: 0.5439, MCC: 0.3032, F1: 0.3158

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.63770 | val 0.68391
  Epoch 020 - train 0.64439 | val 0.65106
  Epoch 030 - train 0.52188 | val 0.80261
  Epoch 036 - train 0.55256 | val 0.81020
  Classification -> best τ=0.320 (val F1=0.4109)
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.63306 | val 0.76836
  Epoch 016 - train 0.62571 | val 0.87174
  Classification -> best τ=0.570 (val F1=0.2814)
  Directional -> Accuracy: 0.4884, MCC: -0.0353, F1: 0.3529

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.68369 | val 0.66960
  Epoch 020 - train 0.56222 | val 0.64901
  Epoch 030 - train 0.60388 | val 0.89399
  Epoch 040 - train 0.49960 | val 0.84492
  Epoch 050 - train 0.42388 | val 0.85750
  Classification -> best τ=0.625 (val F1=0.2741)
  Directional -> Accuracy: 0.6279, MCC: 0.2581, F1: 0.6364

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.59878 | val 0.79253
  Epoch 016 - train 0.55602 | val 1.06869
  Classification -> best τ=0.475 (val F1=0.3850)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.64630 | val 0.71606
  Epoch 018 - train 0.60636 | val 0.68427
  Classification -> best τ=0.430 (val F1=0.2983)
  Directional -> Accuracy: 0.5342, MCC: 0.1602, F1: 0.4138

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.66034 | val 0.76031
  Epoch 016 - train 0.63575 | val 0.75574
  Classification -> best τ=0.525 (val F1=0.2390)
  Directional -> Accuracy: 0.4595, MCC: -0.1712, F1: 0.6296

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.64201 | val 0.73968
  Epoch 020 - train 0.61474 | val 0.90115
  Classification -> best τ=0.485 (val F1=0.2757)
  Directional -> Accuracy: 0.5000, MCC: 0.0263, F1: 0.5926

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.65048 | val 0.78251
  Epoch 016 - train 0.62267 | val 0.83656
  Classification -> best τ=0.460 (val F1=0.4073)
  Directional -> Accuracy: 0.5909, MCC: 0.1666, F1: 0.6400

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.61539 | val 0.73953
  Epoch 020 - train 0.52686 | val 0.91861
  Epoch 021 - train 0.53206 | val 0.98658
  Classification -> best τ=0.545 (val F1=0.3364)
  Directional -> Accuracy: 0.6429, MCC: 0.3290, F1: 0.5714

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.63934 | val 0.67490
  Epoch 016 - train 0.59147 | val 0.70754
  Classification -> best τ=0.415 (val F1=0.2450)
  Directional -> Accuracy: 0.4821, MCC: -0.0135, F1: 0.5397

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.61536 | val 0.81101
  Epoch 016 - train 0.56300 | val 0.86411
  Classification -> best τ=0.485 (val F1=0.4043)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.61513 | val 0.64574
  Epoch 020 - train 0.58616 | val 0.71061
  Epoch 029 - train 0.56666 | val 0.75104
  Classification -> best τ=0.275 (val F1=0.4188)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.68771 | val 0.75209
  Epoch 016 - train 0.58852 | val 0.73347
  Classification -> best τ=0.495 (val F1=0.0585)
  Directional -> Accuracy: 0.5135, MCC: 0.1113, F1: 0.3077

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.65405 | val 0.68116
  Epoch 018 - train 0.59251 | val 1.02911
  Classification -> best τ=0.485 (val F1=0.4537)
  Directional -> Accuracy: 0.5200, MCC: 0.1633, F1: 0.6727

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.61926 | val 0.67837
  Epoch 020 - train 0.60946 | val 0.69617
  Epoch 027 - train 0.56222 | val 0.74404
  Classification -> best τ=0.430 (val F1=0.4692)
  Directional -> Accuracy: 0.4783, MCC: -0.0318, F1: 0.4000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.66615 | val 0.71912
  Epoch 020 - train 0.58189 | val 0.57248
  Epoch 030 - train 0.52306 | val 0.57692
  Epoch 040 - train 0.46457 | val 0.54539
  Epoch 050 - train 0.41651 | val 0.71640
  Classification -> best τ=0.220 (val F1=0.6250)
  Directional -> Accuracy: 0.5349, MCC: -0.1373, F1: 0.6970

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.68191 | val 0.62831
  Epoch 020 - train 0.59206 | val 0.69976
  Epoch 024 - train 0.55589 | val 0.68814
  Classification -> best τ=0.545 (val F1=0.6590)
  Directional -> Accuracy: 0.3878, MCC: -0.0861, F1: 0.5161

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.65038 | val 0.95006
  Epoch 017 - train 0.61327 | val 1.45651
  Classification -> best τ=0.455 (val F1=0.2832)
  Directional -> Accuracy: 0.6250, MCC: 0.2420, F1: 0.6957

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.60748 | val 0.95201
  Epoch 019 - train 0.58728 | val 1.22334
  Classification -> best τ=0.510 (val F1=0.2554)
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.61994 | val 1.14792
  Epoch 016 - train 0.63153 | val 1.51471
  Classification -> best τ=0.340 (val F1=0.1657)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.64572 | val 0.86244
  Epoch 017 - train 0.59467 | val 0.85583
  Classification -> best τ=0.510 (val F1=0.0842)
  Directional -> Accuracy: 0.5714, MCC: 0.2466, F1: 0.7073

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.65752 | val 0.68795
  Epoch 020 - train 0.61835 | val 0.87343

[I 2026-02-25 04:45:56,639] Trial 228 finished with value: 0.27830420429533365 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 64, 'learning_rate': 0.005933442915079905, 'weight_decay': 0.0005283792157019945, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 0.18353996223274338, 'early_stopping_min_delta': 0.002838986883149558}. Best is trial 200 with value: 0.303360648585588.

  Epoch 024 - train 0.57674 | val 0.78846
  Classification -> best τ=0.430 (val F1=0.2575)
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.27830420429533365
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.62242 | val 0.66272
  Epoch 020 - train 0.58513 | val 0.93178
  Epoch 022 - train 0.60254 | val 0.73343
  Classification -> best τ=0.455 (val F1=0.2510)
  Directional -> Accuracy: 0.5526, MCC: 0.0719, F1: 0.4138

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.62689 | val 0.69575
  Epoch 017 - train 0.59616 | val 0.73447
  Classification -> best τ=0.495 (val F1=0.1700)
  Directional -> Accuracy: 0.6444, MCC: 0.2493, F1: 0.7241

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.64707 | val 0.71026
  Epoch 019 - train 0.63711 | val 1.03175
  Classification -> best τ=0.440 (val F1=0.3020)
  Directional -> Accuracy: 0.5319, MCC: 0.0417, F1: 0.6207

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.65629 | val 0.82033
  Epoch 018 - train 0.67093 | val 0.75088
  Classification -> best τ=0.495 (val F1=0.1631)
  Directional -> Accuracy: 0.5600, MCC: 0.1101, F1: 0.6024

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.65509 | val 0.64373
  Epoch 020 - train 0.55370 | val 0.72123
  Epoch 026 - train 0.49120 | val 0.84209
  Classification -> best τ=0.565 (val F1=0.4397)
  Directional -> Accuracy: 0.5490, MCC: 0.1019, F1: 0.5490

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.64324 | val 0.89949
  Epoch 016 - train 0.59793 | val 1.06353
  Classification -> best τ=0.505 (val F1=0.2928)
  Directional -> Accuracy: 0.5532, MCC: 0.1229, F1: 0.3226

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.66727 | val 0.71992
  Epoch 018 - train 0.63501 | val 0.73352
  Classification -> best τ=0.495 (val F1=0.2322)
  Directional -> Accuracy: 0.5652, MCC: 0.2259, F1: 0.6053

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.62929 | val 0.61149
  Epoch 018 - train 0.59158 | val 0.75165
  Classification -> best τ=0.375 (val F1=0.0226)
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.60367 | val 0.71596
  Epoch 016 - train 0.55406 | val 0.90006
  Classification -> best τ=0.435 (val F1=0.2408)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.61138 | val 0.71411
  Epoch 017 - train 0.59646 | val 0.72670
  Classification -> best τ=0.575 (val F1=0.1508)
  Directional -> Accuracy: 0.5571, MCC: 0.0481, F1: 0.3404

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.67288 | val 0.77863
  Epoch 018 - train 0.57518 | val 1.03227
  Classification -> best τ=0.490 (val F1=0.3094)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.59724 | val 0.76719
  Epoch 018 - train 0.56957 | val 0.80177
  Classification -> best τ=0.470 (val F1=0.1469)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.60082 | val 0.71114
  Epoch 020 - train 0.56260 | val 0.93394
  Epoch 023 - train 0.54023 | val 0.92198
  Classification -> best τ=0.455 (val F1=0.2235)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.67041 | val 0.64570
  Epoch 020 - train 0.64151 | val 0.80236
  Epoch 021 - train 0.60547 | val 0.71776
  Classification -> best τ=0.430 (val F1=0.3407)
  Directional -> Accuracy: 0.5500, MCC: 0.1809, F1: 0.6824

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.67525 | val 0.87275
  Epoch 018 - train 0.60585 | val 1.06782
  Classification -> best τ=0.480 (val F1=0.2673)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.61765 | val 0.77252
  Epoch 017 - train 0.60489 | val 0.84049
  Classification -> best τ=0.570 (val F1=0.2826)
  Directional -> Accuracy: 0.5507, MCC: 0.1667, F1: 0.4151

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.64394 | val 1.13664
  Epoch 016 - train 0.63200 | val 1.46325
  Classification -> best τ=0.400 (val F1=0.0660)
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.65885 | val 1.12091
  Epoch 017 - train 0.65257 | val 1.31789
  Classification -> best τ=0.430 (val F1=0.1242)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.64255 | val 0.95811
  Epoch 018 - train 0.59077 | val 1.75165
  Classification -> best τ=0.340 (val F1=0.3140)
  Directional -> Accuracy: 0.5538, MCC: 0.1530, F1: 0.5397

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.67774 | val 0.67432
  Epoch 020 - train 0.61374 | val 0.69712
  Epoch 022 - train 0.63886 | val 0.70586
  Classification -> best τ=0.450 (val F1=0.3516)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.67688 | val 0.69182
  Epoch 020 - train 0.59538 | val 1.09042
  Classification -> best τ=0.430 (val F1=0.4109)
  Directional -> Accuracy: 0.5745, MCC: 0.0406, F1: 0.6875

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.66447 | val 0.74736
  Epoch 016 - train 0.60957 | val 0.79029
  Classification -> best τ=0.490 (val F1=0.1233)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6292

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.67111 | val 0.68503
  Epoch 018 - train 0.64471 | val 0.77114
  Classification -> best τ=0.500 (val F1=0.3835)
  Directional -> Accuracy: 0.6034, MCC: 0.1806, F1: 0.6667

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.64134 | val 0.70910
  Epoch 020 - train 0.59350 | val 0.78748
  Classification -> best τ=0.460 (val F1=0.1992)
  Directional -> Accuracy: 0.4769, MCC: 0.0000, F1: 0.6458

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.62796 | val 0.64794
  Epoch 020 - train 0.58979 | val 0.78972
  Epoch 023 - train 0.55843 | val 0.83041
  Classification -> best τ=0.495 (val F1=0.4472)
  Directional -> Accuracy: 0.4821, MCC: -0.0131, F1: 0.4528

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.64044 | val 0.69904
  Epoch 016 - train 0.59993 | val 0.70898
  Classification -> best τ=0.420 (val F1=0.2035)
  Directional -> Accuracy: 0.5435, MCC: 0.3063, F1: 0.6557

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.69552 | val 0.70067
  Epoch 016 - train 0.64405 | val 0.72394
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.62154 | val 0.76740
  Epoch 016 - train 0.60232 | val 0.87315
  Classification -> best τ=0.505 (val F1=0.3363)
  Directional -> Accuracy: 0.5088, MCC: 0.2428, F1: 0.2222

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.75693 | val 0.73099
  Epoch 020 - train 0.54609 | val 0.65454
  Epoch 030 - train 0.56575 | val 0.95738
  Epoch 040 - train 0.49588 | val 1.61841
  Epoch 041 - train 0.47419 | val 1.88632
  Classification -> best τ=0.380 (val F1=0.3518)
  Directional -> Accuracy: 0.5122, MCC: -0.0474, F1: 0.6552

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.66311 | val 0.98278
  Epoch 016 - train 0.59016 | val 1.03222
  Classification -> best τ=0.545 (val F1=0.2814)
  Directional -> Accuracy: 0.4884, MCC: -0.0318, F1: 0.3889

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.76306 | val 0.67458
  Epoch 020 - train 0.62023 | val 0.73723
  Epoch 021 - train 0.58892 | val 0.68682
  Classification -> best τ=0.510 (val F1=0.1937)
  Directional -> Accuracy: 0.5814, MCC: 0.1533, F1: 0.6897

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.62281 | val 0.90430
  Epoch 019 - train 0.60707 | val 2.09638
  Classification -> best τ=0.695 (val F1=0.2399)
  Directional -> Accuracy: 0.4200, MCC: -0.1405, F1: 0.2162

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.64581 | val 0.69813
  Epoch 020 - train 0.60112 | val 0.89981
  Epoch 028 - train 0.55447 | val 1.14020
  Classification -> best τ=0.345 (val F1=0.2890)
  Directional -> Accuracy: 0.5342, MCC: 0.1237, F1: 0.4688

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.67023 | val 0.73410
  Epoch 020 - train 0.58916 | val 0.80950
  Classification -> best τ=0.485 (val F1=0.1208)
  Directional -> Accuracy: 0.4865, MCC: -0.0263, F1: 0.4865

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.65520 | val 0.73641
  Epoch 020 - train 0.62389 | val 0.90897
  Classification -> best τ=0.475 (val F1=0.2757)
  Directional -> Accuracy: 0.5682, MCC: 0.1412, F1: 0.5778

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.67344 | val 0.71565
  Epoch 016 - train 0.64364 | val 0.83014
  Classification -> best τ=0.355 (val F1=0.3603)
  Directional -> Accuracy: 0.6061, MCC: 0.1734, F1: 0.6829

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.63310 | val 0.68468
  Epoch 020 - train 0.53913 | val 1.04859
  Epoch 024 - train 0.46389 | val 1.01422
  Classification -> best τ=0.495 (val F1=0.3693)
  Directional -> Accuracy: 0.5000, MCC: 0.0561, F1: 0.2222

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.65845 | val 0.68537
  Epoch 016 - train 0.60647 | val 0.90077
  Classification -> best τ=0.375 (val F1=0.2541)
  Directional -> Accuracy: 0.4821, MCC: 0.1255, F1: 0.6420

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.65152 | val 0.71467
  Epoch 016 - train 0.58275 | val 0.73953
  Classification -> best τ=0.535 (val F1=0.2659)
  Directional -> Accuracy: 0.3913, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.64630 | val 0.64221
  Epoch 020 - train 0.59976 | val 0.64301
  Epoch 030 - train 0.54906 | val 0.63192
  Epoch 040 - train 0.51952 | val 0.67823
  Epoch 043 - train 0.48696 | val 0.73135
  Classification -> best τ=0.310 (val F1=0.5125)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.69015 | val 0.77710
  Epoch 016 - train 0.61792 | val 0.84954
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.62942 | val 0.84256
  Epoch 017 - train 0.60007 | val 0.99771
  Classification -> best τ=0.465 (val F1=0.3963)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.65386 | val 0.68042
  Epoch 020 - train 0.58174 | val 0.72032
  Epoch 028 - train 0.57535 | val 1.13999
  Classification -> best τ=0.445 (val F1=0.5065)
  Directional -> Accuracy: 0.5000, MCC: 0.0118, F1: 0.4390

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.62376 | val 0.66310
  Epoch 020 - train 0.63647 | val 0.63307
  Epoch 030 - train 0.53628 | val 0.63278
  Epoch 040 - train 0.46629 | val 0.70352
  Epoch 042 - train 0.45469 | val 0.80766
  Classification -> best τ=0.415 (val F1=0.5752)
  Directional -> Accuracy: 0.5581, MCC: 0.0259, F1: 0.7077

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.60800 | val 0.71728
  Epoch 020 - train 0.59538 | val 0.72032
  Epoch 030 - train 0.49201 | val 0.70099
  Epoch 033 - train 0.47460 | val 0.86866
  Classification -> best τ=0.475 (val F1=0.3672)
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.62429 | val 1.44633
  Epoch 016 - train 0.62621 | val 2.33232
  Classification -> best τ=0.520 (val F1=0.1914)
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.63495 | val 1.07737
  Epoch 017 - train 0.61971 | val 1.47006
  Classification -> best τ=0.610 (val F1=0.2536)
  Directional -> Accuracy: 0.4643, MCC: -0.1397, F1: 0.6341

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.65910 | val 1.08389
  Epoch 017 - train 0.61455 | val 1.38013
  Classification -> best τ=0.480 (val F1=0.1866)
  Directional -> Accuracy: 0.5370, MCC: 0.0642, F1: 0.6377

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.64760 | val 0.78448
  Epoch 017 - train 0.60072 | val 0.74407
  Classification -> best τ=0.535 (val F1=0.2579)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.68399 | val 0.71148

[I 2026-02-25 04:47:04,563] Trial 229 finished with value: 0.2644583403163443 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 64, 'learning_rate': 0.007356313056923394, 'weight_decay': 0.0004157664236849218, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 0.25196706340890923, 'early_stopping_min_delta': 0.0030180922129027193}. Best is trial 200 with value: 0.303360648585588.

  Epoch 019 - train 0.58681 | val 1.05062
  Classification -> best τ=0.490 (val F1=0.1790)
  Directional -> Accuracy: 0.4918, MCC: 0.0145, F1: 0.5974

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2644583403163443
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.62496 | val 0.67834
  Epoch 020 - train 0.62287 | val 0.83524
  Epoch 024 - train 0.61201 | val 0.71170
  Classification -> best τ=0.550 (val F1=0.2510)
  Directional -> Accuracy: 0.5526, MCC: 0.0310, F1: 0.1500

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.63524 | val 0.68870
  Epoch 016 - train 0.61805 | val 0.68811
  Classification -> best τ=0.405 (val F1=0.2095)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.66484 | val 0.73669
  Epoch 019 - train 0.60976 | val 0.97824
  Classification -> best τ=0.540 (val F1=0.2727)
  Directional -> Accuracy: 0.4894, MCC: 0.0471, F1: 0.2000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.68513 | val 0.76839
  Epoch 016 - train 0.67453 | val 0.76540
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.62268 | val 0.66589
  Epoch 018 - train 0.60187 | val 0.66733
  Classification -> best τ=0.490 (val F1=0.4458)
  Directional -> Accuracy: 0.6275, MCC: 0.2489, F1: 0.6667

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.67839 | val 0.71212
  Epoch 020 - train 0.62261 | val 0.81079
  Epoch 021 - train 0.57696 | val 0.90102
  Classification -> best τ=0.480 (val F1=0.2928)
  Directional -> Accuracy: 0.5319, MCC: 0.0620, F1: 0.3529

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.69043 | val 0.71930
  Epoch 018 - train 0.65486 | val 0.70801
  Classification -> best τ=0.495 (val F1=0.2056)
  Directional -> Accuracy: 0.4638, MCC: 0.1149, F1: 0.5843

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.60789 | val 0.71890
  Epoch 020 - train 0.61339 | val 0.86201
  Epoch 023 - train 0.50532 | val 1.34705
  Classification -> best τ=0.365 (val F1=0.1052)
  Directional -> Accuracy: 0.4884, MCC: -0.1634, F1: 0.1538

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.66969 | val 0.67946
  Epoch 018 - train 0.55505 | val 0.97240
  Classification -> best τ=0.440 (val F1=0.2129)
  Directional -> Accuracy: 0.5714, MCC: 0.1118, F1: 0.1600

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.66271 | val 0.73439
  Epoch 017 - train 0.55473 | val 0.82349
  Classification -> best τ=0.560 (val F1=0.2325)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.63702 | val 0.84265
  Epoch 017 - train 0.62639 | val 1.60316
  Classification -> best τ=0.550 (val F1=0.3612)
  Directional -> Accuracy: 0.6000, MCC: 0.2274, F1: 0.2857

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.64323 | val 0.71474
  Epoch 019 - train 0.56814 | val 0.79369
  Classification -> best τ=0.500 (val F1=0.1703)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.4082

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.61835 | val 0.81560
  Epoch 017 - train 0.56540 | val 1.17523
  Classification -> best τ=0.475 (val F1=0.2910)
  Directional -> Accuracy: 0.5238, MCC: 0.0478, F1: 0.5000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.67125 | val 0.63496
  Epoch 020 - train 0.59708 | val 0.66254
  Epoch 030 - train 0.58793 | val 0.62913
  Epoch 031 - train 0.57784 | val 0.63787
  Classification -> best τ=0.470 (val F1=0.3916)
  Directional -> Accuracy: 0.5167, MCC: 0.0349, F1: 0.5797

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.63539 | val 0.78327
  Epoch 016 - train 0.62594 | val 0.75793
  Classification -> best τ=0.475 (val F1=0.3536)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.65658 | val 0.81328
  Epoch 018 - train 0.62097 | val 0.81844
  Classification -> best τ=0.375 (val F1=0.2708)
  Directional -> Accuracy: 0.5652, MCC: 0.1171, F1: 0.6939

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.68555 | val 0.82327
  Epoch 017 - train 0.62180 | val 0.99663
  Classification -> best τ=0.425 (val F1=0.1336)
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.67060 | val 0.80845
  Epoch 016 - train 0.63848 | val 0.82140
  Classification -> best τ=0.470 (val F1=0.2080)
  Directional -> Accuracy: 0.4400, MCC: 0.0748, F1: 0.1923

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.63025 | val 1.17485
  Epoch 017 - train 0.65536 | val 1.77794
  Classification -> best τ=0.355 (val F1=0.2843)
  Directional -> Accuracy: 0.4923, MCC: 0.1307, F1: 0.3265

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.65367 | val 0.72676
  Epoch 020 - train 0.62159 | val 0.74281
  Epoch 022 - train 0.60542 | val 0.73735
  Classification -> best τ=0.465 (val F1=0.2934)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.63162 | val 0.67623
  Epoch 020 - train 0.62584 | val 1.23479
  Epoch 025 - train 0.58019 | val 1.53593
  Classification -> best τ=0.425 (val F1=0.3278)
  Directional -> Accuracy: 0.4468, MCC: -0.0240, F1: 0.4091

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.62633 | val 0.72192
  Epoch 016 - train 0.65806 | val 0.77545
  Classification -> best τ=0.500 (val F1=0.1664)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.65854 | val 0.75834
  Epoch 016 - train 0.63909 | val 0.77838
  Classification -> best τ=0.650 (val F1=0.2520)
  Directional -> Accuracy: 0.4483, MCC: -0.0116, F1: 0.2381

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.63576 | val 0.71489
  Epoch 020 - train 0.61171 | val 0.76897
  Epoch 022 - train 0.58556 | val 0.94346
  Classification -> best τ=0.580 (val F1=0.2390)
  Directional -> Accuracy: 0.4923, MCC: -0.0105, F1: 0.5075

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.65852 | val 0.63935
  Epoch 020 - train 0.58481 | val 0.74490
  Epoch 021 - train 0.59730 | val 0.76894
  Classification -> best τ=0.530 (val F1=0.4297)
  Directional -> Accuracy: 0.4821, MCC: 0.1728, F1: 0.1212

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.63839 | val 0.70185
  Epoch 016 - train 0.61365 | val 0.73841
  Classification -> best τ=0.480 (val F1=0.2935)
  Directional -> Accuracy: 0.4783, MCC: -0.0382, F1: 0.4545

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.67226 | val 0.69328
  Epoch 020 - train 0.60746 | val 0.70119
  Epoch 028 - train 0.56418 | val 0.67991
  Classification -> best τ=0.575 (val F1=0.2161)
  Directional -> Accuracy: 0.5714, MCC: 0.1250, F1: 0.6250

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.61290 | val 0.80790
  Epoch 018 - train 0.59562 | val 1.20345
  Classification -> best τ=0.475 (val F1=0.2668)
  Directional -> Accuracy: 0.5263, MCC: 0.1635, F1: 0.3721

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.65388 | val 0.66843
  Epoch 020 - train 0.58110 | val 0.63824
  Epoch 030 - train 0.55826 | val 1.49925
  Epoch 036 - train 0.54450 | val 1.28013
  Classification -> best τ=0.310 (val F1=0.4109)
  Directional -> Accuracy: 0.5122, MCC: -0.1469, F1: 0.6774

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.65250 | val 0.78958
  Epoch 016 - train 0.63113 | val 1.00606
  Classification -> best τ=0.550 (val F1=0.2814)
  Directional -> Accuracy: 0.5116, MCC: 0.0261, F1: 0.5333

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.67422 | val 0.65409
  Epoch 020 - train 0.54511 | val 0.61826
  Epoch 030 - train 0.57492 | val 0.66985
  Epoch 034 - train 0.51023 | val 0.79058
  Classification -> best τ=0.745 (val F1=0.3201)
  Directional -> Accuracy: 0.4419, MCC: -0.0940, F1: 0.2000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.59560 | val 0.80319
  Epoch 018 - train 0.55432 | val 1.16893
  Classification -> best τ=0.625 (val F1=0.2399)
  Directional -> Accuracy: 0.5200, MCC: 0.0695, F1: 0.4545

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.65363 | val 0.67577
  Epoch 020 - train 0.61177 | val 0.67523
  Epoch 024 - train 0.60027 | val 0.72321
  Classification -> best τ=0.615 (val F1=0.2343)
  Directional -> Accuracy: 0.4932, MCC: 0.1639, F1: 0.2128

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.66480 | val 0.78602
  Epoch 016 - train 0.56995 | val 0.85792
  Classification -> best τ=0.395 (val F1=0.1604)
  Directional -> Accuracy: 0.5135, MCC: 0.0416, F1: 0.5909

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.66414 | val 0.75671
  Epoch 016 - train 0.60935 | val 0.88198
  Classification -> best τ=0.590 (val F1=0.2503)
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.66243 | val 0.72934
  Epoch 016 - train 0.65021 | val 0.81378
  Classification -> best τ=0.430 (val F1=0.3068)
  Directional -> Accuracy: 0.5455, MCC: 0.0874, F1: 0.5833

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.65463 | val 0.74426
  Epoch 016 - train 0.55019 | val 0.80742
  Classification -> best τ=0.480 (val F1=0.1846)
  Directional -> Accuracy: 0.6429, MCC: 0.3290, F1: 0.5714

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.60609 | val 0.69251
  Epoch 016 - train 0.59825 | val 0.83641
  Classification -> best τ=0.445 (val F1=0.2110)
  Directional -> Accuracy: 0.5179, MCC: 0.0998, F1: 0.6197

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.61727 | val 0.76529
  Epoch 017 - train 0.56170 | val 0.94319
  Classification -> best τ=0.475 (val F1=0.0917)
  Directional -> Accuracy: 0.5217, MCC: -0.0706, F1: 0.6452

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.68940 | val 0.65409
  Epoch 020 - train 0.60553 | val 0.63563
  Epoch 030 - train 0.48267 | val 0.76184
  Classification -> best τ=0.415 (val F1=0.3533)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.64980 | val 0.77042
  Epoch 016 - train 0.63660 | val 0.75147
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.63300 | val 0.87881
  Epoch 017 - train 0.61188 | val 1.25087
  Classification -> best τ=0.445 (val F1=0.3707)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.61517 | val 0.68058
  Epoch 020 - train 0.61429 | val 0.70137
  Epoch 026 - train 0.60323 | val 0.73719
  Classification -> best τ=0.490 (val F1=0.4515)
  Directional -> Accuracy: 0.4348, MCC: -0.1234, F1: 0.3158

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.69960 | val 0.66709
  Epoch 020 - train 0.57194 | val 0.72406
  Epoch 025 - train 0.55437 | val 0.73658
  Classification -> best τ=0.490 (val F1=0.4330)
  Directional -> Accuracy: 0.5581, MCC: 0.0259, F1: 0.7077

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.65715 | val 0.65508
  Epoch 020 - train 0.58822 | val 0.59018
  Epoch 030 - train 0.59086 | val 0.71941
  Epoch 035 - train 0.54102 | val 0.72094
  Classification -> best τ=0.515 (val F1=0.6110)
  Directional -> Accuracy: 0.3878, MCC: -0.0687, F1: 0.5312

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.62410 | val 0.88262
  Epoch 016 - train 0.62237 | val 1.05422
  Classification -> best τ=0.415 (val F1=0.2727)
  Directional -> Accuracy: 0.5536, MCC: 0.1899, F1: 0.3902

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.66159 | val 0.96163
  Epoch 018 - train 0.59019 | val 1.33865
  Classification -> best τ=0.545 (val F1=0.2579)
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.64395 | val 1.03858
  Epoch 016 - train 0.59622 | val 1.69426
  Classification -> best τ=0.410 (val F1=0.1807)
  Directional -> Accuracy: 0.5370, MCC: 0.0758, F1: 0.6753

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.63343 | val 0.74597
  Epoch 017 - train 0.61532 | val 0.73841
  Classification -> best τ=0.515 (val F1=0.1161)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.68025 | val 0.67176
  Epoch 020 - train 0.60026 | val 0.86506

[I 2026-02-25 04:48:10,565] Trial 230 finished with value: 0.2635861391435997 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 64, 'learning_rate': 0.0054257499650256745, 'weight_decay': 0.0007474865185883803, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 0.14699437887573627, 'early_stopping_min_delta': 0.003194762195311756}. Best is trial 200 with value: 0.303360648585588.

  Epoch 023 - train 0.61578 | val 0.98282
  Classification -> best τ=0.520 (val F1=0.2639)
  Directional -> Accuracy: 0.5410, MCC: 0.0871, F1: 0.1250

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2635861391435997
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.63767 | val 0.72198
  Epoch 020 - train 0.61600 | val 0.73446
  Classification -> best τ=0.530 (val F1=0.2510)
  Directional -> Accuracy: 0.5658, MCC: 0.1283, F1: 0.0571

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.62922 | val 0.70149
  Epoch 019 - train 0.59410 | val 0.72499
  Classification -> best τ=0.465 (val F1=0.2280)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.66758 | val 0.69264
  Epoch 020 - train 0.61291 | val 0.83116
  Classification -> best τ=0.500 (val F1=0.3924)
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.68531 | val 0.75711
  Epoch 016 - train 0.64454 | val 0.92685
  Classification -> best τ=0.485 (val F1=0.1298)
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.62985 | val 0.67044
  Epoch 020 - train 0.57308 | val 0.66515
  Epoch 027 - train 0.49957 | val 0.75609
  Classification -> best τ=0.590 (val F1=0.3213)
  Directional -> Accuracy: 0.4314, MCC: -0.1667, F1: 0.5246

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.59400 | val 0.69298
  Epoch 017 - train 0.63721 | val 0.84867
  Classification -> best τ=0.460 (val F1=0.3394)
  Directional -> Accuracy: 0.4894, MCC: -0.0045, F1: 0.6471

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.66797 | val 0.69362
  Epoch 020 - train 0.63851 | val 0.75480
  Epoch 022 - train 0.64027 | val 0.71443
  Classification -> best τ=0.540 (val F1=0.2145)
  Directional -> Accuracy: 0.5507, MCC: 0.0417, F1: 0.3922

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.62265 | val 0.65083
  Epoch 020 - train 0.54539 | val 0.87747
  Epoch 025 - train 0.48658 | val 1.19352
  Classification -> best τ=0.510 (val F1=0.3295)
  Directional -> Accuracy: 0.6047, MCC: 0.1366, F1: 0.3200

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.64072 | val 0.75638
  Epoch 020 - train 0.56788 | val 1.07300
  Epoch 021 - train 0.54524 | val 1.13308
  Classification -> best τ=0.550 (val F1=0.2335)
  Directional -> Accuracy: 0.6122, MCC: 0.2178, F1: 0.3448

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.58779 | val 0.71885
  Epoch 020 - train 0.57641 | val 0.79851
  Epoch 022 - train 0.57908 | val 0.91725
  Classification -> best τ=0.465 (val F1=0.1816)
  Directional -> Accuracy: 0.4857, MCC: 0.0365, F1: 0.5500

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.67381 | val 0.83556
  Epoch 018 - train 0.55915 | val 1.45586
  Classification -> best τ=0.450 (val F1=0.1166)
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.6301

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.61275 | val 0.83727
  Epoch 016 - train 0.63100 | val 0.96252
  Classification -> best τ=0.485 (val F1=0.1194)
  Directional -> Accuracy: 0.6207, MCC: 0.2572, F1: 0.5417

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.62205 | val 0.82633
  Epoch 016 - train 0.56509 | val 0.90190
  Classification -> best τ=0.435 (val F1=0.2304)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.65825 | val 0.68182
  Epoch 020 - train 0.60610 | val 0.76071
  Epoch 023 - train 0.58337 | val 1.06460
  Classification -> best τ=0.410 (val F1=0.3268)
  Directional -> Accuracy: 0.6000, MCC: 0.2182, F1: 0.6667

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.64818 | val 0.72586
  Epoch 016 - train 0.60230 | val 0.76521
  Classification -> best τ=0.465 (val F1=0.0223)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.63738 | val 0.72547
  Epoch 018 - train 0.59893 | val 0.83809
  Classification -> best τ=0.430 (val F1=0.2265)
  Directional -> Accuracy: 0.5652, MCC: 0.1171, F1: 0.6939

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.67839 | val 0.90854
  Epoch 016 - train 0.62241 | val 0.96769
  Classification -> best τ=0.500 (val F1=0.2276)
  Directional -> Accuracy: 0.4068, MCC: 0.1444, F1: 0.1026

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.66244 | val 0.81850
  Epoch 016 - train 0.64765 | val 1.39974
  Classification -> best τ=0.395 (val F1=0.0784)
  Directional -> Accuracy: 0.6133, MCC: 0.1173, F1: 0.7387

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.60237 | val 1.12993
  Epoch 018 - train 0.61715 | val 1.74353
  Classification -> best τ=0.520 (val F1=0.3238)
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.63683 | val 0.68245
  Epoch 020 - train 0.60424 | val 0.68594
  Epoch 030 - train 0.55517 | val 0.88929
  Classification -> best τ=0.385 (val F1=0.3030)
  Directional -> Accuracy: 0.4667, MCC: 0.0492, F1: 0.0909

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.63743 | val 0.69571
  Epoch 020 - train 0.55827 | val 1.21225
  Epoch 021 - train 0.58533 | val 1.20205
  Classification -> best τ=0.425 (val F1=0.3307)
  Directional -> Accuracy: 0.5532, MCC: 0.0446, F1: 0.6441

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.68121 | val 0.71940
  Epoch 017 - train 0.59748 | val 0.77674
  Classification -> best τ=0.540 (val F1=0.2674)
  Directional -> Accuracy: 0.4697, MCC: -0.0845, F1: 0.6067

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.67727 | val 0.72861
  Epoch 017 - train 0.61832 | val 0.76902
  Classification -> best τ=0.560 (val F1=0.2379)
  Directional -> Accuracy: 0.5690, MCC: 0.1089, F1: 0.6377

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.63741 | val 0.73123
  Epoch 016 - train 0.58181 | val 0.83575
  Classification -> best τ=0.455 (val F1=0.1885)
  Directional -> Accuracy: 0.4615, MCC: -0.0923, F1: 0.3636

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.63724 | val 0.61678
  Epoch 020 - train 0.58216 | val 0.69897
  Epoch 025 - train 0.55723 | val 0.75120
  Classification -> best τ=0.505 (val F1=0.4388)
  Directional -> Accuracy: 0.5357, MCC: 0.1728, F1: 0.3810

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.75238 | val 0.71138
  Epoch 020 - train 0.62326 | val 0.77718
  Classification -> best τ=0.495 (val F1=0.1864)
  Directional -> Accuracy: 0.5652, MCC: 0.3397, F1: 0.6667

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.66959 | val 0.68884
  Epoch 020 - train 0.61800 | val 0.68041
  Epoch 021 - train 0.61251 | val 0.68024
  Classification -> best τ=0.580 (val F1=0.1936)
  Directional -> Accuracy: 0.4762, MCC: -0.0413, F1: 0.5000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.61187 | val 0.74639
  Epoch 017 - train 0.58913 | val 1.07867
  Classification -> best τ=0.460 (val F1=0.2519)
  Directional -> Accuracy: 0.5088, MCC: 0.2428, F1: 0.2222

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.68964 | val 0.66164
  Epoch 020 - train 0.59275 | val 1.10622
  Epoch 030 - train 0.51730 | val 1.06814
  Epoch 033 - train 0.50222 | val 1.73080
  Classification -> best τ=0.730 (val F1=0.4114)
  Directional -> Accuracy: 0.5122, MCC: 0.0503, F1: 0.4444

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.68146 | val 0.76678
  Epoch 016 - train 0.66588 | val 1.01330
  Classification -> best τ=0.515 (val F1=0.2814)
  Directional -> Accuracy: 0.4884, MCC: -0.0197, F1: 0.5217

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.67009 | val 0.65090
  Epoch 020 - train 0.65609 | val 0.71009
  Epoch 024 - train 0.54939 | val 0.64663
  Classification -> best τ=0.595 (val F1=0.1027)
  Directional -> Accuracy: 0.5116, MCC: -0.0323, F1: 0.6441

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.63270 | val 0.75761
  Epoch 017 - train 0.56359 | val 1.38946
  Classification -> best τ=0.520 (val F1=0.2849)
  Directional -> Accuracy: 0.5600, MCC: 0.1048, F1: 0.7027

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.63949 | val 0.72368
  Epoch 016 - train 0.61544 | val 0.69030
  Classification -> best τ=0.415 (val F1=0.3809)
  Directional -> Accuracy: 0.5616, MCC: 0.1446, F1: 0.5556

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.64744 | val 0.74699
  Epoch 016 - train 0.58513 | val 0.80796
  Classification -> best τ=0.435 (val F1=0.1992)
  Directional -> Accuracy: 0.5676, MCC: 0.1737, F1: 0.6522

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.64681 | val 0.78348
  Epoch 017 - train 0.63500 | val 0.85204
  Classification -> best τ=0.565 (val F1=0.2480)
  Directional -> Accuracy: 0.6364, MCC: 0.2818, F1: 0.6522

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.66575 | val 0.80495
  Epoch 016 - train 0.59990 | val 0.78085
  Classification -> best τ=0.450 (val F1=0.3254)
  Directional -> Accuracy: 0.5758, MCC: 0.0000, F1: 0.7308

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.62741 | val 0.71831
  Epoch 016 - train 0.55138 | val 0.86978
  Classification -> best τ=0.450 (val F1=0.2819)
  Directional -> Accuracy: 0.6429, MCC: 0.2860, F1: 0.6512

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.63583 | val 0.73317
  Epoch 016 - train 0.62116 | val 0.71048
  Classification -> best τ=0.415 (val F1=0.2450)
  Directional -> Accuracy: 0.4821, MCC: 0.1255, F1: 0.6420

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.60652 | val 0.73707
  Epoch 016 - train 0.56612 | val 0.88759
  Classification -> best τ=0.540 (val F1=0.4336)
  Directional -> Accuracy: 0.5652, MCC: -0.0153, F1: 0.6970

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.68573 | val 0.65810
  Epoch 020 - train 0.58027 | val 0.88029
  Epoch 027 - train 0.53591 | val 0.70614
  Classification -> best τ=0.300 (val F1=0.4646)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.71726 | val 0.86344
  Epoch 016 - train 0.58318 | val 0.81005
  Classification -> best τ=0.505 (val F1=0.0585)
  Directional -> Accuracy: 0.5135, MCC: 0.0890, F1: 0.3571

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.64520 | val 0.74852
  Epoch 020 - train 0.60646 | val 1.28154
  Classification -> best τ=0.375 (val F1=0.3397)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.62295 | val 0.67618
  Epoch 020 - train 0.60626 | val 0.68646
  Epoch 025 - train 0.59421 | val 0.69160
  Classification -> best τ=0.440 (val F1=0.3952)
  Directional -> Accuracy: 0.4783, MCC: -0.0169, F1: 0.2000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.61159 | val 0.71675
  Epoch 020 - train 0.53916 | val 0.66233
  Epoch 030 - train 0.51906 | val 0.70027
  Epoch 040 - train 0.44893 | val 0.83969
  Epoch 049 - train 0.38419 | val 0.73798
  Classification -> best τ=0.395 (val F1=0.4330)
  Directional -> Accuracy: 0.5581, MCC: 0.0471, F1: 0.6885

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.64351 | val 0.71803
  Epoch 020 - train 0.56664 | val 0.65883
  Epoch 030 - train 0.53049 | val 0.67571
  Epoch 036 - train 0.48625 | val 0.70851
  Classification -> best τ=0.490 (val F1=0.5689)
  Directional -> Accuracy: 0.3878, MCC: -0.0687, F1: 0.5312

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.65913 | val 0.81593
  Epoch 016 - train 0.65808 | val 1.20869
  Classification -> best τ=0.405 (val F1=0.2958)
  Directional -> Accuracy: 0.6607, MCC: 0.3198, F1: 0.7246

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.63658 | val 0.99329
  Epoch 016 - train 0.61438 | val 1.23836
  Classification -> best τ=0.475 (val F1=0.2230)
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.62667 | val 1.54493
  Epoch 016 - train 0.59377 | val 1.38414
  Classification -> best τ=0.450 (val F1=0.2004)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.61132 | val 0.75060
  Epoch 020 - train 0.59835 | val 0.75443
  Epoch 021 - train 0.55069 | val 0.76116
  Classification -> best τ=0.500 (val F1=0.0488)
  Directional -> Accuracy: 0.5536, MCC: 0.1995, F1: 0.6988

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.66186 | val 0.71390

[I 2026-02-25 04:49:16,781] Trial 231 finished with value: 0.2635456662916301 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 64, 'learning_rate': 0.005574614350775438, 'weight_decay': 0.0005579535951388751, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 0.23282133904454616, 'early_stopping_min_delta': 0.0032358467702647345}. Best is trial 200 with value: 0.303360648585588.

  Epoch 020 - train 0.65687 | val 0.90702
  Classification -> best τ=0.490 (val F1=0.2639)
  Directional -> Accuracy: 0.5246, MCC: 0.0269, F1: 0.3256

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2635456662916301
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.68159 | val 0.67348
  Epoch 017 - train 0.64200 | val 0.79924
  Classification -> best τ=0.645 (val F1=0.2919)
  Directional -> Accuracy: 0.5526, MCC: 0.0174, F1: 0.0556

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.67831 | val 0.68543
  Epoch 020 - train 0.60686 | val 0.75819
  Epoch 025 - train 0.55316 | val 0.72919
  Classification -> best τ=0.445 (val F1=0.2431)
  Directional -> Accuracy: 0.7111, MCC: 0.4088, F1: 0.7869

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.64690 | val 0.72652
  Epoch 020 - train 0.61158 | val 0.79636
  Classification -> best τ=0.485 (val F1=0.2861)
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.67128 | val 0.70033
  Epoch 017 - train 0.66859 | val 0.72342
  Classification -> best τ=0.445 (val F1=0.1210)
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.67057 | val 0.63773
  Epoch 020 - train 0.60182 | val 0.69808
  Epoch 025 - train 0.59306 | val 0.77931
  Classification -> best τ=0.625 (val F1=0.4195)
  Directional -> Accuracy: 0.6275, MCC: 0.2659, F1: 0.6122

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.67630 | val 0.69694
  Epoch 020 - train 0.63387 | val 0.71311
  Epoch 030 - train 0.64734 | val 0.72189
  Epoch 034 - train 0.54660 | val 0.77144
  Classification -> best τ=0.450 (val F1=0.2928)
  Directional -> Accuracy: 0.5957, MCC: 0.2191, F1: 0.4242

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.69321 | val 0.70938
  Epoch 020 - train 0.65339 | val 0.76161
  Epoch 026 - train 0.63376 | val 0.84234
  Classification -> best τ=0.435 (val F1=0.2654)
  Directional -> Accuracy: 0.4638, MCC: 0.0887, F1: 0.5747

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.59191 | val 0.67046
  Epoch 018 - train 0.63258 | val 0.63792
  Classification -> best τ=0.330 (val F1=0.2962)
  Directional -> Accuracy: 0.6047, MCC: 0.1818, F1: 0.1053

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.60885 | val 0.69133
  Epoch 017 - train 0.57936 | val 1.02297
  Classification -> best τ=0.465 (val F1=0.1978)
  Directional -> Accuracy: 0.4694, MCC: 0.0594, F1: 0.6176

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.66959 | val 0.74632
  Epoch 017 - train 0.61262 | val 0.77318
  Classification -> best τ=0.570 (val F1=0.1924)
  Directional -> Accuracy: 0.4714, MCC: -0.0172, F1: 0.5067

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.65409 | val 1.25261
  Epoch 018 - train 0.64264 | val 1.66558
  Classification -> best τ=0.535 (val F1=0.4015)
  Directional -> Accuracy: 0.6400, MCC: 0.2987, F1: 0.4375

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.68201 | val 0.78477
  Epoch 017 - train 0.60182 | val 1.40537
  Classification -> best τ=0.500 (val F1=0.2193)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6588

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.64950 | val 0.81566
  Epoch 017 - train 0.58925 | val 0.81911
  Classification -> best τ=0.625 (val F1=0.1588)
  Directional -> Accuracy: 0.5714, MCC: 0.1946, F1: 0.6250

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.68607 | val 0.62945
  Epoch 018 - train 0.61854 | val 0.65856
  Classification -> best τ=0.570 (val F1=0.3282)
  Directional -> Accuracy: 0.4667, MCC: -0.1336, F1: 0.0588

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.67027 | val 0.69439
  Epoch 018 - train 0.61205 | val 1.04995
  Classification -> best τ=0.485 (val F1=0.2160)
  Directional -> Accuracy: 0.5385, MCC: 0.0154, F1: 0.0769

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.66524 | val 0.71142
  Epoch 017 - train 0.62625 | val 0.77557
  Classification -> best τ=0.470 (val F1=0.3870)
  Directional -> Accuracy: 0.5362, MCC: 0.0432, F1: 0.6364

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.67376 | val 0.91788
  Epoch 016 - train 0.65947 | val 1.48999
  Classification -> best τ=0.470 (val F1=0.1635)
  Directional -> Accuracy: 0.6610, MCC: 0.2199, F1: 0.7619

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.66144 | val 0.75071
  Epoch 018 - train 0.66028 | val 0.93415
  Classification -> best τ=0.435 (val F1=0.1864)
  Directional -> Accuracy: 0.4533, MCC: 0.1938, F1: 0.1633

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.65978 | val 0.90373
  Epoch 018 - train 0.63382 | val 1.20947
  Classification -> best τ=0.465 (val F1=0.3202)
  Directional -> Accuracy: 0.4769, MCC: 0.0998, F1: 0.2917

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.65877 | val 0.66055
  Epoch 020 - train 0.64147 | val 0.69982
  Epoch 024 - train 0.60852 | val 0.90159
  Classification -> best τ=0.475 (val F1=0.3234)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.64289 | val 0.70345
  Epoch 020 - train 0.57392 | val 0.83832
  Epoch 030 - train 0.57097 | val 1.51116
  Classification -> best τ=0.390 (val F1=0.3080)
  Directional -> Accuracy: 0.4255, MCC: -0.0996, F1: 0.4255

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.68971 | val 0.73595
  Epoch 018 - train 0.63798 | val 0.77688
  Classification -> best τ=0.500 (val F1=0.3348)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.3529

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.66117 | val 0.69512
  Epoch 020 - train 0.64220 | val 0.68177
  Epoch 029 - train 0.62829 | val 0.73967
  Classification -> best τ=0.325 (val F1=0.2776)
  Directional -> Accuracy: 0.6034, MCC: 0.1955, F1: 0.6462

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.67701 | val 0.70022
  Epoch 018 - train 0.64115 | val 0.83454
  Classification -> best τ=0.540 (val F1=0.2406)
  Directional -> Accuracy: 0.5538, MCC: 0.1575, F1: 0.6420

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.63909 | val 0.60902
  Epoch 020 - train 0.55881 | val 0.70776
  Epoch 025 - train 0.59762 | val 0.77135
  Classification -> best τ=0.505 (val F1=0.4646)
  Directional -> Accuracy: 0.5179, MCC: 0.1373, F1: 0.3415

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.65715 | val 0.94120
  Epoch 016 - train 0.60824 | val 0.72223
  Classification -> best τ=0.510 (val F1=0.1890)
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.72373 | val 0.74461
  Epoch 020 - train 0.62664 | val 0.72462
  Classification -> best τ=0.540 (val F1=0.1578)
  Directional -> Accuracy: 0.5714, MCC: 0.0913, F1: 0.6667

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.63956 | val 0.72232
  Epoch 016 - train 0.61645 | val 0.78760
  Classification -> best τ=0.370 (val F1=0.2260)
  Directional -> Accuracy: 0.5614, MCC: 0.2858, F1: 0.3902

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.74142 | val 0.71720
  Epoch 020 - train 0.65214 | val 0.67380
  Epoch 030 - train 0.57124 | val 1.25261
  Epoch 031 - train 0.58550 | val 1.22540
  Classification -> best τ=0.545 (val F1=0.3518)
  Directional -> Accuracy: 0.5122, MCC: -0.1469, F1: 0.6774

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.74014 | val 0.79813
  Epoch 016 - train 0.65714 | val 0.87778
  Classification -> best τ=0.610 (val F1=0.2842)
  Directional -> Accuracy: 0.5116, MCC: 0.0162, F1: 0.4000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.68583 | val 0.71354
  Epoch 017 - train 0.65278 | val 0.72574
  Classification -> best τ=0.490 (val F1=0.2517)
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.61662 | val 0.72264
  Epoch 018 - train 0.61615 | val 0.91951
  Classification -> best τ=0.330 (val F1=0.2563)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.66629 | val 0.67916
  Epoch 020 - train 0.63323 | val 0.68328
  Epoch 030 - train 0.60218 | val 0.89493
  Epoch 032 - train 0.61009 | val 0.94801
  Classification -> best τ=0.255 (val F1=0.3173)
  Directional -> Accuracy: 0.5479, MCC: 0.1128, F1: 0.5479

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.70139 | val 0.72818
  Epoch 016 - train 0.57753 | val 0.79125
  Classification -> best τ=0.495 (val F1=0.5003)
  Directional -> Accuracy: 0.5405, MCC: 0.1348, F1: 0.6531

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.65962 | val 0.81222
  Epoch 016 - train 0.64336 | val 0.87656
  Classification -> best τ=0.455 (val F1=0.1283)
  Directional -> Accuracy: 0.5455, MCC: 0.0788, F1: 0.3750

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.66582 | val 0.71778
  Epoch 017 - train 0.65110 | val 0.72790
  Classification -> best τ=0.340 (val F1=0.3001)
  Directional -> Accuracy: 0.6061, MCC: 0.1863, F1: 0.6667

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.61859 | val 0.72007
  Epoch 016 - train 0.55064 | val 0.77299
  Classification -> best τ=0.575 (val F1=0.2652)
  Directional -> Accuracy: 0.5714, MCC: 0.2197, F1: 0.4000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.64530 | val 0.68995
  Epoch 019 - train 0.63048 | val 0.73581
  Classification -> best τ=0.425 (val F1=0.2530)
  Directional -> Accuracy: 0.5179, MCC: 0.0998, F1: 0.6197

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.60862 | val 0.70245
  Epoch 019 - train 0.59585 | val 0.87679
  Classification -> best τ=0.495 (val F1=0.4603)
  Directional -> Accuracy: 0.5217, MCC: -0.0244, F1: 0.6207

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.69763 | val 0.66268
  Epoch 020 - train 0.56865 | val 0.62425
  Epoch 030 - train 0.57847 | val 0.85200
  Epoch 034 - train 0.55406 | val 0.71174
  Classification -> best τ=0.380 (val F1=0.4188)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.73128 | val 0.80859
  Epoch 018 - train 0.57525 | val 0.73804
  Classification -> best τ=0.460 (val F1=0.3882)
  Directional -> Accuracy: 0.4865, MCC: -0.0293, F1: 0.5128

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.65542 | val 0.68056
  Epoch 020 - train 0.61963 | val 1.17219
  Classification -> best τ=0.435 (val F1=0.3620)
  Directional -> Accuracy: 0.5200, MCC: 0.1633, F1: 0.6727

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.69807 | val 0.66972
  Epoch 017 - train 0.65787 | val 0.74215
  Classification -> best τ=0.440 (val F1=0.3717)
  Directional -> Accuracy: 0.5000, MCC: -0.0421, F1: 0.6349

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.71211 | val 0.82903
  Epoch 020 - train 0.63992 | val 0.66944
  Epoch 030 - train 0.53963 | val 0.63144
  Epoch 040 - train 0.52857 | val 0.83277
  Epoch 046 - train 0.53389 | val 0.76042
  Classification -> best τ=0.455 (val F1=0.4148)
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.7164

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.67795 | val 0.70949
  Epoch 020 - train 0.61716 | val 0.75674
  Epoch 024 - train 0.63389 | val 0.67270
  Classification -> best τ=0.545 (val F1=0.4795)
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.66493 | val 0.87734
  Epoch 017 - train 0.64185 | val 1.23311
  Classification -> best τ=0.640 (val F1=0.2239)
  Directional -> Accuracy: 0.4643, MCC: -0.0248, F1: 0.1667

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.69376 | val 0.82080
  Epoch 016 - train 0.63941 | val 0.95584
  Classification -> best τ=0.620 (val F1=0.2667)
  Directional -> Accuracy: 0.5536, MCC: 0.1555, F1: 0.6479

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.65290 | val 1.10934
  Epoch 017 - train 0.64814 | val 1.27158
  Classification -> best τ=0.405 (val F1=0.1866)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.64482 | val 0.75698
  Epoch 018 - train 0.62278 | val 0.84553
  Classification -> best τ=0.530 (val F1=0.1443)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.67409 | val 0.68277
  Epoch 020 - train 0.64000 | val 0.78816

[I 2026-02-25 04:51:20,171] Trial 232 finished with value: 0.28836708108324516 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 64, 'learning_rate': 0.0070859193958063196, 'weight_decay': 0.0004663351983394647, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 0.10473224766817327, 'early_stopping_min_delta': 0.0026849522009295143}. Best is trial 200 with value: 0.303360648585588.

  Epoch 024 - train 0.62685 | val 0.75297
  Classification -> best τ=0.410 (val F1=0.2847)
  Directional -> Accuracy: 0.5410, MCC: 0.1199, F1: 0.6216

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.28836708108324516
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.64751 | val 0.66898
  Epoch 020 - train 0.58231 | val 0.66520
  Epoch 021 - train 0.61195 | val 0.65836
  Classification -> best τ=0.525 (val F1=0.2919)
  Directional -> Accuracy: 0.5658, MCC: 0.0917, F1: 0.3774

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.60979 | val 0.69923
  Epoch 019 - train 0.61668 | val 0.69973
  Classification -> best τ=0.455 (val F1=0.1833)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.65880 | val 0.73491
  Epoch 019 - train 0.57025 | val 1.01049
  Classification -> best τ=0.430 (val F1=0.3262)
  Directional -> Accuracy: 0.5319, MCC: 0.0245, F1: 0.6667

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.65298 | val 0.70195
  Epoch 017 - train 0.65510 | val 0.72436
  Classification -> best τ=0.490 (val F1=0.0543)
  Directional -> Accuracy: 0.5733, MCC: 0.1350, F1: 0.6190

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.64422 | val 0.65839
  Epoch 020 - train 0.58593 | val 0.67775
  Epoch 023 - train 0.53427 | val 0.68015
  Classification -> best τ=0.515 (val F1=0.4051)
  Directional -> Accuracy: 0.5490, MCC: 0.0892, F1: 0.5965

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.60312 | val 0.71100
  Epoch 019 - train 0.53067 | val 0.77936
  Classification -> best τ=0.495 (val F1=0.3430)
  Directional -> Accuracy: 0.5957, MCC: 0.1920, F1: 0.5957

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.66670 | val 0.76996
  Epoch 020 - train 0.62907 | val 0.83380
  Classification -> best τ=0.410 (val F1=0.2056)
  Directional -> Accuracy: 0.4493, MCC: 0.0822, F1: 0.5778

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.66506 | val 0.61091
  Epoch 020 - train 0.55559 | val 0.71888
  Epoch 025 - train 0.54949 | val 0.84348
  Classification -> best τ=0.255 (val F1=0.1752)
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.5902

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.65929 | val 0.78771
  Epoch 020 - train 0.54124 | val 1.20101
  Epoch 023 - train 0.51671 | val 1.33726
  Classification -> best τ=0.265 (val F1=0.2408)
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.64259 | val 0.73409
  Epoch 017 - train 0.57183 | val 0.85225
  Classification -> best τ=0.555 (val F1=0.1733)
  Directional -> Accuracy: 0.5571, MCC: 0.0775, F1: 0.4364

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.67670 | val 1.10674
  Epoch 018 - train 0.59629 | val 1.02496
  Classification -> best τ=0.475 (val F1=0.3151)
  Directional -> Accuracy: 0.5000, MCC: -0.0032, F1: 0.4681

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.63100 | val 0.73081
  Epoch 017 - train 0.56540 | val 0.89805
  Classification -> best τ=0.470 (val F1=0.2097)
  Directional -> Accuracy: 0.5172, MCC: 0.0529, F1: 0.6500

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.61433 | val 0.74623
  Epoch 019 - train 0.54701 | val 0.85445
  Classification -> best τ=0.500 (val F1=0.2991)
  Directional -> Accuracy: 0.4762, MCC: -0.0478, F1: 0.4500

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.67701 | val 0.61947
  Epoch 020 - train 0.61981 | val 0.65927
  Epoch 027 - train 0.57089 | val 0.85875
  Classification -> best τ=0.465 (val F1=0.3477)
  Directional -> Accuracy: 0.5667, MCC: 0.1667, F1: 0.6667

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.62956 | val 0.82732
  Epoch 016 - train 0.58978 | val 0.86524
  Classification -> best τ=0.530 (val F1=0.2694)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.63066 | val 0.84065
  Epoch 020 - train 0.59393 | val 1.07609
  Epoch 021 - train 0.58017 | val 1.10506
  Classification -> best τ=0.545 (val F1=0.2810)
  Directional -> Accuracy: 0.5362, MCC: 0.1179, F1: 0.4286

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.65338 | val 1.04820
  Epoch 017 - train 0.63681 | val 1.08050
  Classification -> best τ=0.545 (val F1=0.1291)
  Directional -> Accuracy: 0.3729, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.66539 | val 0.91951
  Epoch 016 - train 0.63727 | val 1.10931
  Classification -> best τ=0.505 (val F1=0.0867)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.66546 | val 1.01330
  Epoch 020 - train 0.62185 | val 1.43197
  Classification -> best τ=0.405 (val F1=0.2940)
  Directional -> Accuracy: 0.4923, MCC: 0.1307, F1: 0.3265

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.63283 | val 0.67995
  Epoch 016 - train 0.61541 | val 0.93297
  Classification -> best τ=0.495 (val F1=0.2366)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.64356 | val 0.75868
  Epoch 020 - train 0.59856 | val 1.23575
  Epoch 021 - train 0.56067 | val 1.20113
  Classification -> best τ=0.455 (val F1=0.4109)
  Directional -> Accuracy: 0.5106, MCC: -0.0247, F1: 0.5965

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.62711 | val 0.74909
  Epoch 016 - train 0.59822 | val 0.76655
  Classification -> best τ=0.510 (val F1=0.1782)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.4762

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.65338 | val 0.80880
  Epoch 016 - train 0.66877 | val 0.78414
  Classification -> best τ=0.655 (val F1=0.2864)
  Directional -> Accuracy: 0.4483, MCC: 0.1153, F1: 0.0588

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.68327 | val 0.71535
  Epoch 017 - train 0.60868 | val 0.74621
  Classification -> best τ=0.430 (val F1=0.1797)
  Directional -> Accuracy: 0.5846, MCC: 0.1694, F1: 0.4255

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.67760 | val 0.67529
  Epoch 020 - train 0.60413 | val 0.74463
  Epoch 023 - train 0.59746 | val 0.77117
  Classification -> best τ=0.520 (val F1=0.3394)
  Directional -> Accuracy: 0.5357, MCC: 0.2812, F1: 0.2778

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.75001 | val 0.72839
  Epoch 020 - train 0.55911 | val 0.80468
  Epoch 023 - train 0.53201 | val 0.92032
  Classification -> best τ=0.525 (val F1=0.4328)
  Directional -> Accuracy: 0.6304, MCC: 0.3294, F1: 0.6667

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.64428 | val 0.69348
  Epoch 020 - train 0.59939 | val 0.71336
  Classification -> best τ=0.580 (val F1=0.1936)
  Directional -> Accuracy: 0.4762, MCC: -0.0694, F1: 0.5417

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.66357 | val 0.69311
  Epoch 020 - train 0.58149 | val 0.98218
  Classification -> best τ=0.310 (val F1=0.2550)
  Directional -> Accuracy: 0.6140, MCC: 0.2416, F1: 0.6207

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.65769 | val 0.69945
  Epoch 020 - train 0.60818 | val 0.67638
  Epoch 030 - train 0.53893 | val 1.11066
  Epoch 040 - train 0.47845 | val 1.74814
  Epoch 041 - train 0.44232 | val 1.59172
  Classification -> best τ=0.410 (val F1=0.3518)
  Directional -> Accuracy: 0.5366, MCC: 0.0166, F1: 0.6885

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.64841 | val 0.79970
  Epoch 016 - train 0.58906 | val 0.92162
  Classification -> best τ=0.580 (val F1=0.2814)
  Directional -> Accuracy: 0.5116, MCC: 0.0162, F1: 0.4000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.66906 | val 0.63947
  Epoch 020 - train 0.56948 | val 0.60672
  Epoch 030 - train 0.54745 | val 0.86740
  Epoch 032 - train 0.51073 | val 1.21285
  Classification -> best τ=0.535 (val F1=0.3329)
  Directional -> Accuracy: 0.6279, MCC: 0.2484, F1: 0.6667

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.64403 | val 0.72751
  Epoch 019 - train 0.56500 | val 1.02947
  Classification -> best τ=0.600 (val F1=0.2969)
  Directional -> Accuracy: 0.5000, MCC: 0.1242, F1: 0.1935

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.63460 | val 0.66318
  Epoch 018 - train 0.60905 | val 0.70762
  Classification -> best τ=0.340 (val F1=0.3467)
  Directional -> Accuracy: 0.5205, MCC: 0.1094, F1: 0.4262

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.63209 | val 0.79557
  Epoch 016 - train 0.62922 | val 0.94218
  Classification -> best τ=0.445 (val F1=0.2588)
  Directional -> Accuracy: 0.4865, MCC: -0.0263, F1: 0.4865

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.67094 | val 0.76585
  Epoch 017 - train 0.62542 | val 0.87490
  Classification -> best τ=0.480 (val F1=0.2358)
  Directional -> Accuracy: 0.4545, MCC: -0.0932, F1: 0.4286

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.63967 | val 0.79407
  Epoch 016 - train 0.60688 | val 0.87823
  Classification -> best τ=0.415 (val F1=0.3254)
  Directional -> Accuracy: 0.5909, MCC: 0.1376, F1: 0.6747

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.65890 | val 0.76916
  Epoch 019 - train 0.52777 | val 0.83143
  Classification -> best τ=0.525 (val F1=0.1716)
  Directional -> Accuracy: 0.5714, MCC: 0.2530, F1: 0.3571

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.65916 | val 0.72156
  Epoch 018 - train 0.60700 | val 0.74684
  Classification -> best τ=0.420 (val F1=0.2530)
  Directional -> Accuracy: 0.5357, MCC: 0.1371, F1: 0.6286

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.60578 | val 0.75097
  Epoch 016 - train 0.53108 | val 0.75827
  Classification -> best τ=0.485 (val F1=0.0314)
  Directional -> Accuracy: 0.6304, MCC: 0.1493, F1: 0.7536

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.63223 | val 0.66690
  Epoch 020 - train 0.56968 | val 0.64320
  Epoch 030 - train 0.59185 | val 0.70648
  Epoch 035 - train 0.53759 | val 0.82626
  Classification -> best τ=0.430 (val F1=0.5617)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.61583 | val 0.74599
  Epoch 020 - train 0.54809 | val 0.83757
  Epoch 021 - train 0.54591 | val 0.82445
  Classification -> best τ=0.500 (val F1=0.3801)
  Directional -> Accuracy: 0.4324, MCC: -0.1122, F1: 0.3226

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.63863 | val 0.69572
  Epoch 017 - train 0.60581 | val 0.98626
  Classification -> best τ=0.410 (val F1=0.4061)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.66225 | val 0.68291
  Epoch 020 - train 0.59895 | val 0.71237
  Epoch 028 - train 0.58617 | val 0.79352
  Classification -> best τ=0.535 (val F1=0.3989)
  Directional -> Accuracy: 0.5000, MCC: 0.0766, F1: 0.1481

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.69872 | val 0.73606
  Epoch 020 - train 0.60353 | val 0.65383
  Epoch 030 - train 0.51698 | val 0.59813
  Epoch 040 - train 0.52479 | val 0.51224
  Epoch 049 - train 0.42642 | val 0.78344
  Classification -> best τ=0.150 (val F1=0.5270)
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.7164

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.61941 | val 0.58472
  Epoch 020 - train 0.60314 | val 0.62492
  Epoch 025 - train 0.59129 | val 0.67018
  Classification -> best τ=0.595 (val F1=0.6590)
  Directional -> Accuracy: 0.4286, MCC: 0.0116, F1: 0.5333

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.65977 | val 0.99929
  Epoch 017 - train 0.63812 | val 1.40141
  Classification -> best τ=0.450 (val F1=0.1085)
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.66079 | val 0.87266
  Epoch 016 - train 0.61159 | val 1.20736
  Classification -> best τ=0.550 (val F1=0.3204)
  Directional -> Accuracy: 0.5893, MCC: 0.1758, F1: 0.5106

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.64190 | val 0.94851
  Epoch 018 - train 0.62206 | val 1.85107
  Classification -> best τ=0.450 (val F1=0.2004)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.64075 | val 0.76868
  Epoch 016 - train 0.60224 | val 0.72620
  Classification -> best τ=0.560 (val F1=0.0114)
  Directional -> Accuracy: 0.5536, MCC: 0.1100, F1: 0.6667

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.68825 | val 0.69346

[I 2026-02-25 04:52:29,002] Trial 233 finished with value: 0.2781863130598041 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 64, 'learning_rate': 0.006893611396930101, 'weight_decay': 0.0004313843496013325, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 0.17489435838888703, 'early_stopping_min_delta': 0.0026776035270118124}. Best is trial 200 with value: 0.303360648585588.

  Epoch 017 - train 0.59502 | val 0.86920
  Classification -> best τ=0.505 (val F1=0.3074)
  Directional -> Accuracy: 0.4262, MCC: -0.1455, F1: 0.4262

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2781863130598041
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.63958 | val 0.67338
  Epoch 020 - train 0.67481 | val 0.70387
  Epoch 030 - train 0.60597 | val 0.70230
  Epoch 038 - train 0.58144 | val 0.85233
  Classification -> best τ=0.630 (val F1=0.3286)
  Directional -> Accuracy: 0.5132, MCC: 0.0407, F1: 0.5195

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.65115 | val 0.69092
  Epoch 016 - train 0.62578 | val 0.75805
  Classification -> best τ=0.430 (val F1=0.3114)
  Directional -> Accuracy: 0.6222, MCC: 0.2440, F1: 0.6531

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.70833 | val 0.74247
  Epoch 017 - train 0.64434 | val 0.80400
  Classification -> best τ=0.510 (val F1=0.2793)
  Directional -> Accuracy: 0.5319, MCC: 0.2449, F1: 0.2143

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.69499 | val 0.95235
  Epoch 016 - train 0.67876 | val 0.78122
  Classification -> best τ=0.495 (val F1=0.0157)
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.65344 | val 0.64124
  Epoch 020 - train 0.60203 | val 0.74701
  Epoch 025 - train 0.56844 | val 0.69174
  Classification -> best τ=0.590 (val F1=0.4598)
  Directional -> Accuracy: 0.5490, MCC: 0.0892, F1: 0.5965

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.64643 | val 0.71379
  Epoch 016 - train 0.63845 | val 0.77052
  Classification -> best τ=0.555 (val F1=0.3430)
  Directional -> Accuracy: 0.5957, MCC: 0.2000, F1: 0.4865

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.69681 | val 0.72398
  Epoch 020 - train 0.64686 | val 0.86581
  Classification -> best τ=0.460 (val F1=0.2196)
  Directional -> Accuracy: 0.5362, MCC: 0.1618, F1: 0.5789

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.62977 | val 0.66853
  Epoch 020 - train 0.59911 | val 0.83469
  Epoch 026 - train 0.51217 | val 0.93656
  Classification -> best τ=0.470 (val F1=0.3295)
  Directional -> Accuracy: 0.5581, MCC: 0.1297, F1: 0.5366

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.66487 | val 0.72292
  Epoch 018 - train 0.62607 | val 0.89211
  Classification -> best τ=0.535 (val F1=0.2891)
  Directional -> Accuracy: 0.6122, MCC: 0.2829, F1: 0.2400

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.69695 | val 0.71190
  Epoch 018 - train 0.58746 | val 0.71155
  Classification -> best τ=0.525 (val F1=0.0585)
  Directional -> Accuracy: 0.5857, MCC: 0.1154, F1: 0.3830

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.68264 | val 0.79219
  Epoch 020 - train 0.67658 | val 1.65568
  Epoch 023 - train 0.58995 | val 1.86850
  Classification -> best τ=0.475 (val F1=0.2294)
  Directional -> Accuracy: 0.6000, MCC: 0.2274, F1: 0.2857

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.62896 | val 0.75031
  Epoch 016 - train 0.62352 | val 1.18882
  Classification -> best τ=0.470 (val F1=0.2097)
  Directional -> Accuracy: 0.5345, MCC: 0.1361, F1: 0.6747

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.65432 | val 0.65626
  Epoch 020 - train 0.55378 | val 1.24377
  Epoch 024 - train 0.56548 | val 1.76638
  Classification -> best τ=0.560 (val F1=0.4470)
  Directional -> Accuracy: 0.5238, MCC: 0.1062, F1: 0.6000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.67934 | val 0.65031
  Epoch 020 - train 0.64716 | val 0.80759
  Epoch 028 - train 0.64080 | val 0.98872
  Classification -> best τ=0.360 (val F1=0.3477)
  Directional -> Accuracy: 0.5500, MCC: 0.2294, F1: 0.6897

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.68619 | val 0.79948
  Epoch 019 - train 0.58957 | val 0.79332
  Classification -> best τ=0.540 (val F1=0.2160)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.69103 | val 0.69011
  Epoch 017 - train 0.67272 | val 0.74699
  Classification -> best τ=0.485 (val F1=0.3536)
  Directional -> Accuracy: 0.4783, MCC: -0.0750, F1: 0.5714

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.65189 | val 0.92532
  Epoch 018 - train 0.68048 | val 0.89285
  Classification -> best τ=0.525 (val F1=0.1774)
  Directional -> Accuracy: 0.3729, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.68964 | val 0.82196
  Epoch 017 - train 0.68428 | val 0.91034
  Classification -> best τ=0.535 (val F1=0.1864)
  Directional -> Accuracy: 0.4933, MCC: 0.0110, F1: 0.5128

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.66010 | val 1.25876
  Epoch 016 - train 0.62185 | val 2.22669
  Classification -> best τ=0.560 (val F1=0.2973)
  Directional -> Accuracy: 0.4769, MCC: -0.1653, F1: 0.6136

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.67074 | val 0.68232
  Epoch 019 - train 0.64433 | val 0.65729
  Classification -> best τ=0.390 (val F1=0.3011)
  Directional -> Accuracy: 0.4000, MCC: -0.2205, F1: 0.4706

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.69913 | val 0.77163
  Epoch 020 - train 0.63352 | val 0.92867
  Epoch 021 - train 0.61669 | val 1.15735
  Classification -> best τ=0.410 (val F1=0.2845)
  Directional -> Accuracy: 0.5106, MCC: 0.0373, F1: 0.5490

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.68240 | val 0.75087
  Epoch 018 - train 0.64692 | val 1.01647
  Classification -> best τ=0.565 (val F1=0.2411)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.67727 | val 0.68711
  Epoch 016 - train 0.65425 | val 0.72673
  Classification -> best τ=0.695 (val F1=0.3282)
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.65330 | val 0.71115
  Epoch 017 - train 0.62476 | val 0.69230
  Classification -> best τ=0.520 (val F1=0.1936)
  Directional -> Accuracy: 0.5385, MCC: 0.0619, F1: 0.3478

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.65892 | val 0.64292
  Epoch 020 - train 0.58966 | val 0.79655
  Epoch 030 - train 0.58324 | val 0.96615
  Classification -> best τ=0.445 (val F1=0.4588)
  Directional -> Accuracy: 0.5179, MCC: 0.1037, F1: 0.4000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.64728 | val 0.72029
  Epoch 020 - train 0.67676 | val 0.75644
  Epoch 030 - train 0.57572 | val 0.85399
  Epoch 031 - train 0.61470 | val 0.84762
  Classification -> best τ=0.585 (val F1=0.1890)
  Directional -> Accuracy: 0.5870, MCC: 0.1700, F1: 0.0952

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.65216 | val 0.68837
  Epoch 020 - train 0.65579 | val 0.67941
  Epoch 030 - train 0.57802 | val 0.69198
  Epoch 031 - train 0.60239 | val 0.68248
  Classification -> best τ=0.580 (val F1=0.2402)
  Directional -> Accuracy: 0.4286, MCC: -0.1132, F1: 0.4000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.68471 | val 0.68607
  Epoch 020 - train 0.62980 | val 0.74783
  Epoch 022 - train 0.60770 | val 0.77108
  Classification -> best τ=0.370 (val F1=0.3618)
  Directional -> Accuracy: 0.5789, MCC: 0.1312, F1: 0.6471

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.74779 | val 0.68589
  Epoch 020 - train 0.63619 | val 0.70812
  Epoch 030 - train 0.52553 | val 1.10824
  Epoch 032 - train 0.55312 | val 0.68195
  Classification -> best τ=0.510 (val F1=0.4382)
  Directional -> Accuracy: 0.5610, MCC: 0.0996, F1: 0.6538

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.64245 | val 0.93911
  Epoch 016 - train 0.62571 | val 0.95495
  Classification -> best τ=0.590 (val F1=0.2814)
  Directional -> Accuracy: 0.5581, MCC: 0.1150, F1: 0.5366

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.65574 | val 0.68564
  Epoch 020 - train 0.65143 | val 0.72746
  Epoch 030 - train 0.54451 | val 0.81833
  Epoch 040 - train 0.47097 | val 0.61014
  Epoch 050 - train 0.42272 | val 0.71610
  Classification -> best τ=0.615 (val F1=0.3156)
  Directional -> Accuracy: 0.4651, MCC: -0.0334, F1: 0.2581

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.60168 | val 0.74807
  Epoch 017 - train 0.60213 | val 0.69552
  Classification -> best τ=0.680 (val F1=0.2399)
  Directional -> Accuracy: 0.5200, MCC: -0.0642, F1: 0.6757

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.65712 | val 0.72310
  Epoch 017 - train 0.62795 | val 0.67606
  Classification -> best τ=0.330 (val F1=0.3434)
  Directional -> Accuracy: 0.5479, MCC: 0.1382, F1: 0.5075

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.84647 | val 0.77319
  Epoch 016 - train 0.63398 | val 0.80177
  Classification -> best τ=0.565 (val F1=0.1992)
  Directional -> Accuracy: 0.5676, MCC: 0.1737, F1: 0.6522

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.66199 | val 0.73802
  Epoch 016 - train 0.64694 | val 0.83570
  Classification -> best τ=0.545 (val F1=0.3627)
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.68471 | val 0.70584
  Epoch 020 - train 0.65139 | val 0.77778
  Epoch 029 - train 0.62104 | val 0.79190
  Classification -> best τ=0.170 (val F1=0.3525)
  Directional -> Accuracy: 0.5758, MCC: 0.0000, F1: 0.7308

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.74014 | val 0.69062
  Epoch 020 - train 0.50740 | val 0.71489
  Classification -> best τ=0.590 (val F1=0.2652)
  Directional -> Accuracy: 0.5000, MCC: 0.0793, F1: 0.1600

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.63253 | val 0.72166
  Epoch 020 - train 0.64707 | val 0.71862
  Classification -> best τ=0.535 (val F1=0.2305)
  Directional -> Accuracy: 0.6429, MCC: 0.2992, F1: 0.4737

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.61905 | val 0.73067
  Epoch 016 - train 0.55179 | val 0.67094
  Classification -> best τ=0.330 (val F1=0.3105)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.74389 | val 0.75319
  Epoch 017 - train 0.61905 | val 0.69610
  Classification -> best τ=0.355 (val F1=0.1477)
  Directional -> Accuracy: 0.3878, MCC: 0.1100, F1: 0.5455

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.69663 | val 1.09270
  Epoch 017 - train 0.57192 | val 0.86154
  Classification -> best τ=0.515 (val F1=0.2106)
  Directional -> Accuracy: 0.4595, MCC: -0.0283, F1: 0.1667

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.70470 | val 0.67413
  Epoch 020 - train 0.62011 | val 0.89517
  Epoch 024 - train 0.59130 | val 0.92366
  Classification -> best τ=0.285 (val F1=0.3870)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.66943 | val 0.69227
  Epoch 020 - train 0.62021 | val 0.74139
  Epoch 022 - train 0.66153 | val 0.83988
  Classification -> best τ=0.430 (val F1=0.3952)
  Directional -> Accuracy: 0.5000, MCC: 0.0161, F1: 0.4103

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.66404 | val 0.76097
  Epoch 020 - train 0.63233 | val 0.71741
  Epoch 023 - train 0.62013 | val 0.70827
  Classification -> best τ=0.545 (val F1=0.5270)
  Directional -> Accuracy: 0.4419, MCC: -0.2275, F1: 0.5862

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.69995 | val 0.72738
  Epoch 017 - train 0.64167 | val 0.76241
  Classification -> best τ=0.670 (val F1=0.6290)
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.67686 | val 1.10969
  Epoch 017 - train 0.62791 | val 1.42568
  Classification -> best τ=0.540 (val F1=0.0290)
  Directional -> Accuracy: 0.4643, MCC: -0.0334, F1: 0.2500

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.64434 | val 0.96071
  Epoch 018 - train 0.67810 | val 0.98051
  Classification -> best τ=0.365 (val F1=0.2830)
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.65823 | val 0.91867
  Epoch 017 - train 0.66037 | val 0.97419
  Classification -> best τ=0.455 (val F1=0.3202)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.67311 | val 0.85113
  Epoch 016 - train 0.66009 | val 0.79003
  Classification -> best τ=0.445 (val F1=0.1345)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.66667 | val 0.80540
  Epoch 020 - train 0.65284 | val 0.69382
  Epoch 021 - train 0.62198 | val 0.70499

[I 2026-02-25 04:54:34,246] Trial 234 finished with value: 0.28672971702238925 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 64, 'learning_rate': 0.00837961047634878, 'weight_decay': 0.0006593159068036858, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 0.10056472954436738, 'early_stopping_min_delta': 0.0026059134644959535}. Best is trial 200 with value: 0.303360648585588.

  Classification -> best τ=0.385 (val F1=0.2367)
  Directional -> Accuracy: 0.5082, MCC: 0.0940, F1: 0.6429

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.28672971702238925
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.67943 | val 0.66131
  Epoch 020 - train 0.67416 | val 0.65254
  Epoch 030 - train 0.59164 | val 0.69813
  Epoch 035 - train 0.57240 | val 0.86454
  Classification -> best τ=0.690 (val F1=0.2919)
  Directional -> Accuracy: 0.5395, MCC: 0.0059, F1: 0.2222

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.62879 | val 0.71564
  Epoch 017 - train 0.62336 | val 0.69395
  Classification -> best τ=0.435 (val F1=0.1710)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.69933 | val 0.69669
  Epoch 019 - train 0.62646 | val 0.80919
  Classification -> best τ=0.645 (val F1=0.3589)
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.68767 | val 0.69924
  Epoch 019 - train 0.65311 | val 0.83605
  Classification -> best τ=0.470 (val F1=0.1713)
  Directional -> Accuracy: 0.4800, MCC: 0.0544, F1: 0.2041

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.65734 | val 0.65248
  Epoch 018 - train 0.62585 | val 0.67569
  Classification -> best τ=0.485 (val F1=0.5047)
  Directional -> Accuracy: 0.6078, MCC: 0.2390, F1: 0.5652

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.79475 | val 0.68560
  Epoch 020 - train 0.64573 | val 0.69366
  Epoch 025 - train 0.62501 | val 0.87591
  Classification -> best τ=0.500 (val F1=0.2582)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.70353 | val 0.70063
  Epoch 020 - train 0.65105 | val 0.78277
  Epoch 022 - train 0.65943 | val 0.70992
  Classification -> best τ=0.470 (val F1=0.2135)
  Directional -> Accuracy: 0.5217, MCC: 0.1221, F1: 0.5600

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.70070 | val 0.60984
  Epoch 020 - train 0.61137 | val 0.61272
  Epoch 022 - train 0.54555 | val 0.64577
  Classification -> best τ=0.325 (val F1=0.3325)
  Directional -> Accuracy: 0.5814, MCC: 0.0664, F1: 0.2500

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.62679 | val 0.72865
  Epoch 020 - train 0.58340 | val 0.71408
  Epoch 030 - train 0.57712 | val 0.77599
  Epoch 033 - train 0.50059 | val 0.86221
  Classification -> best τ=0.460 (val F1=0.2949)
  Directional -> Accuracy: 0.5918, MCC: 0.2636, F1: 0.6552

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.65944 | val 0.71304
  Epoch 020 - train 0.62712 | val 0.69268
  Epoch 030 - train 0.57641 | val 0.84412
  Epoch 031 - train 0.57445 | val 1.45193
  Classification -> best τ=0.545 (val F1=0.2282)
  Directional -> Accuracy: 0.5286, MCC: 0.0577, F1: 0.4923

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.63327 | val 0.78061
  Epoch 018 - train 0.60427 | val 1.29912
  Classification -> best τ=0.455 (val F1=0.2606)
  Directional -> Accuracy: 0.6200, MCC: 0.2539, F1: 0.3871

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.66391 | val 0.86101
  Epoch 018 - train 0.54164 | val 1.04468
  Classification -> best τ=0.575 (val F1=0.2105)
  Directional -> Accuracy: 0.5862, MCC: 0.2646, F1: 0.3333

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.68576 | val 0.70934
  Epoch 016 - train 0.60937 | val 0.84496
  Classification -> best τ=0.560 (val F1=0.2502)
  Directional -> Accuracy: 0.4762, MCC: 0.0083, F1: 0.5769

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.69666 | val 0.63237
  Epoch 018 - train 0.62906 | val 0.62119
  Classification -> best τ=0.320 (val F1=0.4048)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.4828

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.67107 | val 0.71026
  Epoch 016 - train 0.62798 | val 0.89437
  Classification -> best τ=0.500 (val F1=0.3022)
  Directional -> Accuracy: 0.4808, MCC: 0.0636, F1: 0.6301

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.66150 | val 0.68883
  Epoch 017 - train 0.65182 | val 0.75743
  Classification -> best τ=0.620 (val F1=0.3599)
  Directional -> Accuracy: 0.5942, MCC: 0.2287, F1: 0.7200

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.69169 | val 1.41990
  Epoch 016 - train 0.62607 | val 1.20014
  Classification -> best τ=0.465 (val F1=0.1905)
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.65146 | val 0.87741
  Epoch 020 - train 0.64447 | val 0.79164
  Epoch 021 - train 0.65551 | val 0.76799
  Classification -> best τ=0.395 (val F1=0.1217)
  Directional -> Accuracy: 0.5600, MCC: -0.0308, F1: 0.6972

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.63923 | val 0.92827
  Epoch 016 - train 0.67980 | val 1.80035
  Classification -> best τ=0.460 (val F1=0.3266)
  Directional -> Accuracy: 0.5077, MCC: 0.1597, F1: 0.3600

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.66297 | val 0.66492
  Epoch 020 - train 0.64679 | val 0.69132
  Epoch 025 - train 0.60484 | val 0.69399
  Classification -> best τ=0.505 (val F1=0.3545)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.65019 | val 0.69208
  Epoch 019 - train 0.62161 | val 0.84507
  Classification -> best τ=0.555 (val F1=0.1478)
  Directional -> Accuracy: 0.5319, MCC: -0.0346, F1: 0.6452

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.67354 | val 0.83365
  Epoch 019 - train 0.63721 | val 0.78183
  Classification -> best τ=0.460 (val F1=0.2976)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.64854 | val 0.76872
  Epoch 018 - train 0.64758 | val 0.76470
  Classification -> best τ=0.580 (val F1=0.3031)
  Directional -> Accuracy: 0.4310, MCC: -0.1255, F1: 0.4407

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.67930 | val 0.72368
  Epoch 020 - train 0.63448 | val 0.93309
  Epoch 021 - train 0.64823 | val 0.74088
  Classification -> best τ=0.505 (val F1=0.1986)
  Directional -> Accuracy: 0.5231, MCC: 0.0776, F1: 0.6076

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.68748 | val 0.65111
  Epoch 020 - train 0.62585 | val 0.72542
  Epoch 030 - train 0.56973 | val 0.87919
  Classification -> best τ=0.500 (val F1=0.4149)
  Directional -> Accuracy: 0.5179, MCC: 0.1373, F1: 0.3415

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.66171 | val 0.70650
  Epoch 020 - train 0.60392 | val 0.82025
  Epoch 021 - train 0.59516 | val 0.80990
  Classification -> best τ=0.565 (val F1=0.2726)
  Directional -> Accuracy: 0.6087, MCC: 0.2722, F1: 0.6400

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.65971 | val 0.69587
  Epoch 019 - train 0.62276 | val 0.69217
  Classification -> best τ=0.585 (val F1=0.1334)
  Directional -> Accuracy: 0.4762, MCC: -0.2161, F1: 0.6333

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.64543 | val 0.71612
  Epoch 019 - train 0.60707 | val 0.79483
  Classification -> best τ=0.350 (val F1=0.3323)
  Directional -> Accuracy: 0.5439, MCC: 0.2218, F1: 0.3810

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.65350 | val 0.68412
  Epoch 020 - train 0.65273 | val 0.84659
  Epoch 030 - train 0.57970 | val 1.80714
  Epoch 033 - train 0.52686 | val 2.09026
  Classification -> best τ=0.535 (val F1=0.4382)
  Directional -> Accuracy: 0.4878, MCC: -0.1407, F1: 0.6441

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.64193 | val 0.83037
  Epoch 017 - train 0.61603 | val 0.94219
  Classification -> best τ=0.580 (val F1=0.2814)
  Directional -> Accuracy: 0.5581, MCC: 0.1150, F1: 0.5366

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.73567 | val 0.68729
  Epoch 020 - train 0.58576 | val 0.64276
  Epoch 030 - train 0.57350 | val 0.62306
  Epoch 039 - train 0.40883 | val 0.72368
  Classification -> best τ=0.760 (val F1=0.3201)
  Directional -> Accuracy: 0.4651, MCC: -0.0154, F1: 0.0800

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.62826 | val 0.70418
  Epoch 016 - train 0.59101 | val 0.74818
  Classification -> best τ=0.625 (val F1=0.3574)
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.64794 | val 0.67542
  Epoch 020 - train 0.61193 | val 0.76304
  Epoch 022 - train 0.61627 | val 0.92641
  Classification -> best τ=0.405 (val F1=0.2574)
  Directional -> Accuracy: 0.5205, MCC: 0.1211, F1: 0.4068

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.68266 | val 0.80027
  Epoch 019 - train 0.66650 | val 0.81452
  Classification -> best τ=0.470 (val F1=0.0289)
  Directional -> Accuracy: 0.4595, MCC: -0.0783, F1: 0.5652

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.68863 | val 0.76308
  Epoch 020 - train 0.62203 | val 0.84979
  Classification -> best τ=0.500 (val F1=0.4021)
  Directional -> Accuracy: 0.6364, MCC: 0.2754, F1: 0.6364

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.67643 | val 0.67451
  Epoch 016 - train 0.65025 | val 0.75998
  Classification -> best τ=0.380 (val F1=0.3855)
  Directional -> Accuracy: 0.5606, MCC: 0.0162, F1: 0.6947

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.62063 | val 0.83169
  Epoch 017 - train 0.53709 | val 0.90513
  Classification -> best τ=0.625 (val F1=0.3364)
  Directional -> Accuracy: 0.4762, MCC: -0.0155, F1: 0.1538

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.63800 | val 0.68139
  Epoch 020 - train 0.66602 | val 0.69055
  Epoch 024 - train 0.61992 | val 0.71273
  Classification -> best τ=0.370 (val F1=0.3039)
  Directional -> Accuracy: 0.4821, MCC: 0.0625, F1: 0.6329

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.63652 | val 0.72652
  Epoch 019 - train 0.59453 | val 0.76699
  Classification -> best τ=0.470 (val F1=0.1564)
  Directional -> Accuracy: 0.4348, MCC: 0.0894, F1: 0.1875

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.69472 | val 0.67427
  Epoch 020 - train 0.58835 | val 0.62191
  Epoch 030 - train 0.58049 | val 0.76817
  Epoch 033 - train 0.55218 | val 0.68137
  Classification -> best τ=0.365 (val F1=0.5247)
  Directional -> Accuracy: 0.3469, MCC: -0.1894, F1: 0.5152

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.74515 | val 0.92441
  Epoch 016 - train 0.59608 | val 0.90941
  Classification -> best τ=0.450 (val F1=0.0585)
  Directional -> Accuracy: 0.4865, MCC: -0.0385, F1: 0.5366

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.67167 | val 0.69443
  Epoch 020 - train 0.62732 | val 0.85594
  Epoch 023 - train 0.58761 | val 0.96116
  Classification -> best τ=0.435 (val F1=0.3096)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.72124 | val 0.72370
  Epoch 017 - train 0.61164 | val 0.81305
  Classification -> best τ=0.390 (val F1=0.3287)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.0000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.72096 | val 0.73786
  Epoch 018 - train 0.62048 | val 0.80461
  Classification -> best τ=0.545 (val F1=0.4166)
  Directional -> Accuracy: 0.4651, MCC: -0.0786, F1: 0.5106

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.68565 | val 0.68171
  Epoch 020 - train 0.60821 | val 0.67566
  Epoch 021 - train 0.61778 | val 0.67338
  Classification -> best τ=0.635 (val F1=0.3672)
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.64980 | val 0.76553
  Epoch 017 - train 0.64913 | val 0.97384
  Classification -> best τ=0.610 (val F1=0.1914)
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.65623 | val 0.76623
  Epoch 016 - train 0.65639 | val 0.91621
  Classification -> best τ=0.580 (val F1=0.3204)
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.71840 | val 0.94826
  Epoch 018 - train 0.63883 | val 1.73519
  Classification -> best τ=0.505 (val F1=0.3324)
  Directional -> Accuracy: 0.4259, MCC: -0.2113, F1: 0.5634

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.65314 | val 0.87891
  Epoch 016 - train 0.64224 | val 0.77202
  Classification -> best τ=0.390 (val F1=0.1473)
  Directional -> Accuracy: 0.5893, MCC: 0.2874, F1: 0.7160

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.65847 | val 0.69975
  Epoch 020 - train 0.70810 | val 0.75179
  Epoch 030 - train 0.60828 | val 0.98070

[I 2026-02-25 04:56:41,143] Trial 235 finished with value: 0.2839922179666049 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 64, 'learning_rate': 0.007842003596615046, 'weight_decay': 0.000673034440059666, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 0.1313355891698484, 'early_stopping_min_delta': 0.002537907375893072}. Best is trial 200 with value: 0.303360648585588.

  Epoch 032 - train 0.62998 | val 0.92041
  Classification -> best τ=0.470 (val F1=0.2283)
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2839922179666049
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.64928 | val 0.66054
  Epoch 020 - train 0.64378 | val 0.78298
  Epoch 030 - train 0.59439 | val 0.77020
  Epoch 031 - train 0.59799 | val 0.74303
  Classification -> best τ=0.660 (val F1=0.2919)
  Directional -> Accuracy: 0.5395, MCC: 0.0559, F1: 0.4444

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.62054 | val 0.68848
  Epoch 020 - train 0.60138 | val 0.70466
  Epoch 021 - train 0.58168 | val 0.71807
  Classification -> best τ=0.410 (val F1=0.3893)
  Directional -> Accuracy: 0.6000, MCC: 0.1323, F1: 0.7353

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.68284 | val 0.71983
  Epoch 020 - train 0.62431 | val 0.99068
  Epoch 021 - train 0.64311 | val 0.95487
  Classification -> best τ=0.525 (val F1=0.2727)
  Directional -> Accuracy: 0.5745, MCC: 0.1988, F1: 0.4737

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.68067 | val 0.80785
  Epoch 017 - train 0.64645 | val 0.85602
  Classification -> best τ=0.455 (val F1=0.1448)
  Directional -> Accuracy: 0.4933, MCC: -0.0505, F1: 0.5870

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.63877 | val 0.66134
  Epoch 020 - train 0.60043 | val 0.68504
  Epoch 026 - train 0.59983 | val 0.69791
  Classification -> best τ=0.585 (val F1=0.4087)
  Directional -> Accuracy: 0.5098, MCC: -0.0687, F1: 0.6667

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.67252 | val 0.69839
  Epoch 020 - train 0.61251 | val 0.85345
  Epoch 025 - train 0.58327 | val 1.13519
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4894, MCC: 0.0000, F1: 0.6571

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.69162 | val 0.68276
  Epoch 020 - train 0.68493 | val 0.67644
  Epoch 030 - train 0.67883 | val 0.74060
  Epoch 035 - train 0.63343 | val 0.95792
  Classification -> best τ=0.380 (val F1=0.2511)
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.66389 | val 0.68637
  Epoch 020 - train 0.60373 | val 0.68567
  Epoch 021 - train 0.53992 | val 0.72871
  Classification -> best τ=0.310 (val F1=0.3880)
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.66142 | val 0.72934
  Epoch 020 - train 0.55241 | val 1.04057
  Classification -> best τ=0.325 (val F1=0.1939)
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.66469 | val 0.70056
  Epoch 016 - train 0.63587 | val 0.73393
  Classification -> best τ=0.500 (val F1=0.1936)
  Directional -> Accuracy: 0.4571, MCC: -0.0098, F1: 0.5476

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.67640 | val 0.82833
  Epoch 019 - train 0.62475 | val 1.05693
  Classification -> best τ=0.465 (val F1=0.2500)
  Directional -> Accuracy: 0.5200, MCC: 0.0152, F1: 0.4000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.68037 | val 0.86209
  Epoch 018 - train 0.63372 | val 1.02119
  Classification -> best τ=0.425 (val F1=0.2945)
  Directional -> Accuracy: 0.5517, MCC: 0.1429, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.62513 | val 0.74620
  Epoch 020 - train 0.59881 | val 1.02767
  Epoch 022 - train 0.57751 | val 0.85378
  Classification -> best τ=0.670 (val F1=0.3325)
  Directional -> Accuracy: 0.4762, MCC: -0.0673, F1: 0.3889

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.68975 | val 0.62175
  Epoch 020 - train 0.63640 | val 0.99995
  Epoch 024 - train 0.64030 | val 0.75264
  Classification -> best τ=0.335 (val F1=0.4048)
  Directional -> Accuracy: 0.5500, MCC: 0.2294, F1: 0.6897

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.65135 | val 0.73081
  Epoch 020 - train 0.59520 | val 0.78633
  Epoch 021 - train 0.62246 | val 0.90652
  Classification -> best τ=0.535 (val F1=0.2673)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.66807 | val 0.74180
  Epoch 018 - train 0.62535 | val 0.81519
  Classification -> best τ=0.570 (val F1=0.3208)
  Directional -> Accuracy: 0.5507, MCC: 0.0880, F1: 0.6076

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.65028 | val 1.08836
  Epoch 018 - train 0.63466 | val 1.40564
  Classification -> best τ=0.665 (val F1=0.0557)
  Directional -> Accuracy: 0.3729, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.68451 | val 0.91880
  Epoch 019 - train 0.66290 | val 1.01770
  Classification -> best τ=0.410 (val F1=0.2153)
  Directional -> Accuracy: 0.6133, MCC: 0.1361, F1: 0.7238

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.67676 | val 0.96882
  Epoch 020 - train 0.65101 | val 1.70862
  Epoch 021 - train 0.64042 | val 1.91770
  Classification -> best τ=0.440 (val F1=0.2166)
  Directional -> Accuracy: 0.4462, MCC: 0.0307, F1: 0.2174

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.65095 | val 0.67332
  Epoch 020 - train 0.61817 | val 0.75979
  Epoch 030 - train 0.61026 | val 0.81760
  Epoch 039 - train 0.60114 | val 0.78931
  Classification -> best τ=0.420 (val F1=0.3062)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.67819 | val 0.68169
  Epoch 020 - train 0.61855 | val 1.03397
  Epoch 025 - train 0.56595 | val 1.03628
  Classification -> best τ=0.440 (val F1=0.3707)
  Directional -> Accuracy: 0.5745, MCC: -0.0074, F1: 0.7059

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.66359 | val 0.73047
  Epoch 016 - train 0.68048 | val 0.76623
  Classification -> best τ=0.510 (val F1=0.1996)
  Directional -> Accuracy: 0.4394, MCC: -0.1226, F1: 0.4789

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.67525 | val 0.69139
  Epoch 020 - train 0.64698 | val 0.74573
  Epoch 022 - train 0.63100 | val 0.72540
  Classification -> best τ=0.570 (val F1=0.3215)
  Directional -> Accuracy: 0.5517, MCC: 0.0951, F1: 0.5938

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.66144 | val 0.68872
  Epoch 017 - train 0.66963 | val 0.81205
  Classification -> best τ=0.475 (val F1=0.1271)
  Directional -> Accuracy: 0.5692, MCC: 0.1426, F1: 0.5758

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.68704 | val 0.66805
  Epoch 020 - train 0.63640 | val 0.66051
  Epoch 027 - train 0.59285 | val 0.72331
  Classification -> best τ=0.540 (val F1=0.4272)
  Directional -> Accuracy: 0.4643, MCC: 0.0292, F1: 0.1667

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.67355 | val 0.75053
  Epoch 018 - train 0.63705 | val 0.74098
  Classification -> best τ=0.425 (val F1=0.2935)
  Directional -> Accuracy: 0.5217, MCC: 0.1216, F1: 0.5926

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.69216 | val 0.69961
  Epoch 020 - train 0.63466 | val 0.69287
  Epoch 021 - train 0.65607 | val 0.70849
  Classification -> best τ=0.555 (val F1=0.1936)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.66600 | val 0.66882
  Epoch 020 - train 0.62712 | val 0.73206
  Epoch 021 - train 0.60487 | val 0.76446
  Classification -> best τ=0.400 (val F1=0.2945)
  Directional -> Accuracy: 0.5789, MCC: 0.2202, F1: 0.5200

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.62342 | val 0.67582
  Epoch 020 - train 0.61891 | val 0.70882
  Epoch 024 - train 0.59469 | val 0.70686
  Classification -> best τ=0.495 (val F1=0.4109)
  Directional -> Accuracy: 0.5610, MCC: 0.1701, F1: 0.7097

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.68263 | val 0.74577
  Epoch 016 - train 0.65610 | val 0.87127
  Classification -> best τ=0.515 (val F1=0.3244)
  Directional -> Accuracy: 0.4884, MCC: -0.0238, F1: 0.4762

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.64527 | val 0.67585
  Epoch 020 - train 0.66659 | val 0.75190
  Epoch 022 - train 0.63406 | val 0.96243
  Classification -> best τ=0.560 (val F1=0.2741)
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.64545 | val 0.73514
  Epoch 016 - train 0.60382 | val 0.78675
  Classification -> best τ=0.555 (val F1=0.3465)
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.67919 | val 0.67310
  Epoch 017 - train 0.62693 | val 0.73043
  Classification -> best τ=0.320 (val F1=0.3927)
  Directional -> Accuracy: 0.5479, MCC: 0.1291, F1: 0.5217

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.64816 | val 0.76241
  Epoch 016 - train 0.63138 | val 0.91605
  Classification -> best τ=0.430 (val F1=0.2588)
  Directional -> Accuracy: 0.4324, MCC: -0.1586, F1: 0.5714

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.64957 | val 0.77536
  Epoch 016 - train 0.67919 | val 0.95352
  Classification -> best τ=0.400 (val F1=0.2757)
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.69745 | val 0.68415
  Epoch 020 - train 0.65781 | val 0.73297
  Epoch 024 - train 0.64253 | val 0.77382
  Classification -> best τ=0.405 (val F1=0.3814)
  Directional -> Accuracy: 0.4545, MCC: 0.1517, F1: 0.1000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.67600 | val 0.71740
  Epoch 020 - train 0.55693 | val 0.75030
  Epoch 023 - train 0.52929 | val 0.98882
  Classification -> best τ=0.485 (val F1=0.2741)
  Directional -> Accuracy: 0.7143, MCC: 0.4318, F1: 0.7143

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.68017 | val 0.71089
  Epoch 017 - train 0.64330 | val 0.70351
  Classification -> best τ=0.450 (val F1=0.3625)
  Directional -> Accuracy: 0.5357, MCC: 0.0827, F1: 0.5517

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.62194 | val 0.66114
  Epoch 020 - train 0.60577 | val 0.68519
  Epoch 030 - train 0.55425 | val 0.66497
  Classification -> best τ=0.590 (val F1=0.2924)
  Directional -> Accuracy: 0.6304, MCC: 0.1490, F1: 0.7606

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.74708 | val 0.69364
  Epoch 020 - train 0.61164 | val 0.63704
  Epoch 030 - train 0.60122 | val 0.66057
  Epoch 039 - train 0.52469 | val 0.66006
  Classification -> best τ=0.335 (val F1=0.6130)
  Directional -> Accuracy: 0.3469, MCC: -0.1894, F1: 0.5152

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.73197 | val 1.04204
  Epoch 016 - train 0.57193 | val 0.94868
  Classification -> best τ=0.405 (val F1=0.3306)
  Directional -> Accuracy: 0.5135, MCC: -0.0752, F1: 0.6667

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.68376 | val 0.68587
  Epoch 020 - train 0.61536 | val 0.77224
  Epoch 022 - train 0.62401 | val 0.86456
  Classification -> best τ=0.375 (val F1=0.3450)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.68596 | val 0.68649
  Epoch 018 - train 0.62866 | val 0.69370
  Classification -> best τ=0.395 (val F1=0.3952)
  Directional -> Accuracy: 0.4348, MCC: -0.1234, F1: 0.3158

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.61494 | val 0.62529
  Epoch 020 - train 0.65809 | val 0.87689
  Epoch 024 - train 0.59435 | val 0.69630
  Classification -> best τ=0.495 (val F1=0.5270)
  Directional -> Accuracy: 0.5349, MCC: -0.1373, F1: 0.6970

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.72663 | val 0.79651
  Epoch 017 - train 0.62968 | val 0.67699
  Classification -> best τ=0.575 (val F1=0.6292)
  Directional -> Accuracy: 0.5714, MCC: 0.1061, F1: 0.4615

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.66480 | val 0.74080
  Epoch 017 - train 0.66607 | val 0.75038
  Classification -> best τ=0.585 (val F1=0.0890)
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.65621 | val 0.78069
  Epoch 020 - train 0.68979 | val 0.92511
  Epoch 023 - train 0.63192 | val 0.86878
  Classification -> best τ=0.590 (val F1=0.3535)
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.65833 | val 1.17495
  Epoch 018 - train 0.62906 | val 1.38961
  Classification -> best τ=0.570 (val F1=0.2345)
  Directional -> Accuracy: 0.5370, MCC: 0.0946, F1: 0.4444

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.66074 | val 0.74351
  Epoch 017 - train 0.65003 | val 0.94147
  Classification -> best τ=0.500 (val F1=0.1667)
  Directional -> Accuracy: 0.4821, MCC: -0.0384, F1: 0.5085

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.68314 | val 0.68156
  Epoch 020 - train 0.62340 | val 0.72814

[I 2026-02-25 04:58:52,162] Trial 236 finished with value: 0.298622297550642 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 64, 'learning_rate': 0.008367057654319198, 'weight_decay': 0.0006840658776189569, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 0.10312816651640115, 'early_stopping_min_delta': 0.002795207018541637}. Best is trial 200 with value: 0.303360648585588.

  Epoch 028 - train 0.65672 | val 0.70693
  Classification -> best τ=0.370 (val F1=0.2283)
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.298622297550642
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.68399 | val 0.67514
  Epoch 020 - train 0.60765 | val 0.67436
  Epoch 023 - train 0.60183 | val 0.74747
  Classification -> best τ=0.470 (val F1=0.2510)
  Directional -> Accuracy: 0.5526, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.67856 | val 0.69240
  Epoch 019 - train 0.60360 | val 0.70221
  Classification -> best τ=0.485 (val F1=0.3012)
  Directional -> Accuracy: 0.4889, MCC: 0.0485, F1: 0.4103

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.70444 | val 0.71405
  Epoch 017 - train 0.65716 | val 0.76807
  Classification -> best τ=0.540 (val F1=0.2779)
  Directional -> Accuracy: 0.5106, MCC: -0.0471, F1: 0.6567

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.66754 | val 0.73202
  Epoch 017 - train 0.66725 | val 0.83479
  Classification -> best τ=0.420 (val F1=0.1810)
  Directional -> Accuracy: 0.5067, MCC: 0.0646, F1: 0.3934

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.64203 | val 0.68568
  Epoch 020 - train 0.60010 | val 0.66293
  Epoch 029 - train 0.57131 | val 0.73316
  Classification -> best τ=0.590 (val F1=0.4457)
  Directional -> Accuracy: 0.3725, MCC: -0.2542, F1: 0.3846

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.67535 | val 0.69020
  Epoch 020 - train 0.62483 | val 0.69206
  Epoch 021 - train 0.62547 | val 0.69408
  Classification -> best τ=0.520 (val F1=0.2037)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.67965 | val 0.69891
  Epoch 018 - train 0.70579 | val 0.70977
  Classification -> best τ=0.550 (val F1=0.2605)
  Directional -> Accuracy: 0.5942, MCC: 0.1054, F1: 0.3636

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.68943 | val 0.77262
  Epoch 020 - train 0.65272 | val 0.81304
  Epoch 023 - train 0.56595 | val 0.77912
  Classification -> best τ=0.340 (val F1=0.1502)
  Directional -> Accuracy: 0.5116, MCC: 0.1323, F1: 0.5882

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.65194 | val 0.74216
  Epoch 016 - train 0.63553 | val 0.75336
  Classification -> best τ=0.370 (val F1=0.3539)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.66837 | val 0.71347
  Epoch 018 - train 0.61636 | val 1.47194
  Classification -> best τ=0.540 (val F1=0.2249)
  Directional -> Accuracy: 0.4429, MCC: -0.0318, F1: 0.5517

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.69285 | val 1.02251
  Epoch 017 - train 0.61942 | val 1.16220
  Classification -> best τ=0.475 (val F1=0.1346)
  Directional -> Accuracy: 0.5800, MCC: 0.1394, F1: 0.4324

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.69244 | val 0.77844
  Epoch 019 - train 0.61014 | val 0.87757
  Classification -> best τ=0.475 (val F1=0.2097)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.63112 | val 0.67788
  Epoch 017 - train 0.61772 | val 0.87706
  Classification -> best τ=0.575 (val F1=0.1686)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.68705 | val 0.61558
  Epoch 020 - train 0.63621 | val 0.67575
  Epoch 025 - train 0.64680 | val 0.64892
  Classification -> best τ=0.420 (val F1=0.3706)
  Directional -> Accuracy: 0.5500, MCC: 0.1155, F1: 0.6400

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.66709 | val 0.73537
  Epoch 020 - train 0.61602 | val 0.76903
  Epoch 022 - train 0.59753 | val 0.80326
  Classification -> best τ=0.525 (val F1=0.2160)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.65635 | val 0.74141
  Epoch 017 - train 0.67666 | val 0.70872
  Classification -> best τ=0.495 (val F1=0.1474)
  Directional -> Accuracy: 0.5217, MCC: -0.0357, F1: 0.6733

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.71551 | val 0.75278
  Epoch 020 - train 0.64037 | val 0.85994
  Epoch 021 - train 0.67461 | val 0.83515
  Classification -> best τ=0.585 (val F1=0.2276)
  Directional -> Accuracy: 0.3729, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.67587 | val 0.89898
  Epoch 018 - train 0.66737 | val 1.16291
  Classification -> best τ=0.395 (val F1=0.1217)
  Directional -> Accuracy: 0.4800, MCC: -0.1155, F1: 0.5895

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.67521 | val 0.84492
  Epoch 017 - train 0.66164 | val 1.77578
  Classification -> best τ=0.470 (val F1=0.2269)
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.66702 | val 0.66502
  Epoch 020 - train 0.66028 | val 0.72753
  Epoch 026 - train 0.64052 | val 0.78180
  Classification -> best τ=0.480 (val F1=0.3778)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.69335 | val 0.69959
  Epoch 020 - train 0.61645 | val 0.83354
  Classification -> best τ=0.420 (val F1=0.2807)
  Directional -> Accuracy: 0.5319, MCC: -0.0887, F1: 0.6667

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.70815 | val 0.74881
  Epoch 016 - train 0.62468 | val 0.91914
  Classification -> best τ=0.560 (val F1=0.2215)
  Directional -> Accuracy: 0.4848, MCC: -0.0492, F1: 0.6304

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.70035 | val 0.70186
  Epoch 016 - train 0.66972 | val 0.73639
  Classification -> best τ=0.565 (val F1=0.2379)
  Directional -> Accuracy: 0.5345, MCC: 0.0278, F1: 0.6197

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.67999 | val 0.69163
  Epoch 020 - train 0.64386 | val 0.73937
  Epoch 021 - train 0.66085 | val 0.86246
  Classification -> best τ=0.550 (val F1=0.1936)
  Directional -> Accuracy: 0.5538, MCC: 0.1051, F1: 0.2927

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.66682 | val 0.65555
  Epoch 020 - train 0.65622 | val 0.70926
  Epoch 030 - train 0.57947 | val 0.69346
  Epoch 039 - train 0.53007 | val 0.81912
  Classification -> best τ=0.525 (val F1=0.3951)
  Directional -> Accuracy: 0.4821, MCC: 0.1096, F1: 0.1714

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.74715 | val 0.76274
  Epoch 018 - train 0.58808 | val 0.77615
  Classification -> best τ=0.595 (val F1=0.1585)
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.65539 | val 0.73709
  Epoch 018 - train 0.61241 | val 0.71143
  Classification -> best τ=0.600 (val F1=0.1936)
  Directional -> Accuracy: 0.4048, MCC: -0.1340, F1: 0.2424

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.67691 | val 0.68066
  Epoch 020 - train 0.62913 | val 0.71245
  Epoch 022 - train 0.63479 | val 0.74212
  Classification -> best τ=0.495 (val F1=0.1940)
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.73550 | val 0.68311
  Epoch 020 - train 0.64222 | val 0.71907
  Classification -> best τ=0.535 (val F1=0.4109)
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.66385 | val 0.84904
  Epoch 016 - train 0.63134 | val 0.75133
  Classification -> best τ=0.540 (val F1=0.2814)
  Directional -> Accuracy: 0.5814, MCC: 0.1615, F1: 0.5263

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.69552 | val 0.66090
  Epoch 020 - train 0.58983 | val 0.68734
  Epoch 030 - train 0.70201 | val 0.69919
  Epoch 040 - train 0.50558 | val 0.65209
  Epoch 050 - train 0.46125 | val 0.70796
  Classification -> best τ=0.675 (val F1=0.4147)
  Directional -> Accuracy: 0.4186, MCC: -0.1829, F1: 0.0741

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.61038 | val 0.77112
  Epoch 017 - train 0.64192 | val 0.81760
  Classification -> best τ=0.375 (val F1=0.2978)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.65957 | val 0.80515
  Epoch 019 - train 0.63153 | val 0.69748
  Classification -> best τ=0.345 (val F1=0.3785)
  Directional -> Accuracy: 0.5205, MCC: 0.0894, F1: 0.4615

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.61989 | val 0.78432
  Epoch 016 - train 0.61452 | val 0.82739
  Classification -> best τ=0.455 (val F1=0.3651)
  Directional -> Accuracy: 0.5135, MCC: 0.0684, F1: 0.6400

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.65668 | val 0.83220
  Epoch 018 - train 0.64669 | val 0.81590
  Classification -> best τ=0.425 (val F1=0.2757)
  Directional -> Accuracy: 0.5455, MCC: 0.1596, F1: 0.0909

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.66046 | val 0.70183
  Epoch 016 - train 0.65508 | val 0.72823
  Classification -> best τ=0.495 (val F1=0.2449)
  Directional -> Accuracy: 0.5909, MCC: 0.1253, F1: 0.6897

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.62041 | val 0.71438
  Epoch 020 - train 0.57080 | val 0.75771
  Classification -> best τ=0.575 (val F1=0.2486)
  Directional -> Accuracy: 0.5952, MCC: 0.2656, F1: 0.4516

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.65559 | val 0.70910
  Epoch 020 - train 0.63243 | val 0.69204
  Epoch 022 - train 0.62059 | val 0.71030
  Classification -> best τ=0.530 (val F1=0.2742)
  Directional -> Accuracy: 0.5357, MCC: 0.0620, F1: 0.4800

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.61346 | val 0.72093
  Epoch 016 - train 0.64503 | val 0.81136
  Classification -> best τ=0.420 (val F1=0.1298)
  Directional -> Accuracy: 0.5652, MCC: 0.0873, F1: 0.6429

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.65765 | val 0.68240
  Epoch 020 - train 0.61814 | val 0.71327
  Epoch 030 - train 0.52032 | val 0.77217
  Classification -> best τ=0.340 (val F1=0.4188)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.75470 | val 0.81438
  Epoch 018 - train 0.63420 | val 0.99590
  Classification -> best τ=0.490 (val F1=0.2106)
  Directional -> Accuracy: 0.4324, MCC: -0.1122, F1: 0.3226

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.67225 | val 0.65264
  Epoch 020 - train 0.63425 | val 0.99824
  Epoch 024 - train 0.59311 | val 1.35479
  Classification -> best τ=0.495 (val F1=0.3865)
  Directional -> Accuracy: 0.5200, MCC: 0.1155, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.62116 | val 0.72972
  Epoch 016 - train 0.62946 | val 0.71790
  Classification -> best τ=0.435 (val F1=0.3367)
  Directional -> Accuracy: 0.5217, MCC: 0.1124, F1: 0.2667

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.70473 | val 0.76369
  Epoch 018 - train 0.62531 | val 0.75411
  Classification -> best τ=0.580 (val F1=0.4568)
  Directional -> Accuracy: 0.5814, MCC: 0.1854, F1: 0.5714

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.70568 | val 0.67905
  Epoch 020 - train 0.57435 | val 0.68032
  Epoch 024 - train 0.57606 | val 0.71574
  Classification -> best τ=0.480 (val F1=0.5514)
  Directional -> Accuracy: 0.3673, MCC: -0.1814, F1: 0.5373

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.67566 | val 0.75623
  Epoch 019 - train 0.62519 | val 1.27891
  Classification -> best τ=0.535 (val F1=0.1458)
  Directional -> Accuracy: 0.6071, MCC: 0.2026, F1: 0.6765

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.66521 | val 0.80832
  Epoch 016 - train 0.65188 | val 1.03533
  Classification -> best τ=0.510 (val F1=0.2230)
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.65162 | val 0.85061
  Epoch 017 - train 0.63767 | val 0.98359
  Classification -> best τ=0.485 (val F1=0.0666)
  Directional -> Accuracy: 0.5000, MCC: -0.1324, F1: 0.6667

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.70849 | val 0.75106
  Epoch 020 - train 0.64134 | val 0.71166
  Epoch 026 - train 0.60580 | val 0.99652
  Classification -> best τ=0.520 (val F1=0.2981)
  Directional -> Accuracy: 0.4821, MCC: -0.0333, F1: 0.4727

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.66521 | val 0.68005
  Epoch 020 - train 0.67794 | val 0.71131
  Epoch 030 - train 0.64575 | val 0.93733
  Epoch 031 - train 0.63141 | val 0.90758

[I 2026-02-25 05:00:58,135] Trial 237 finished with value: 0.2685274254290196 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 64, 'learning_rate': 0.008694105674487975, 'weight_decay': 0.0007601242875757567, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 0.1017775353359493, 'early_stopping_min_delta': 0.0023919040459689576}. Best is trial 200 with value: 0.303360648585588.

  Classification -> best τ=0.390 (val F1=0.2847)
  Directional -> Accuracy: 0.4590, MCC: -0.1356, F1: 0.6292

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2685274254290196
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.64375 | val 0.66361
  Epoch 020 - train 0.61103 | val 0.68222
  Epoch 021 - train 0.63575 | val 0.68777
  Classification -> best τ=0.610 (val F1=0.2510)
  Directional -> Accuracy: 0.5526, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.62994 | val 0.72169
  Epoch 020 - train 0.59241 | val 0.71363
  Epoch 027 - train 0.61463 | val 0.69602
  Classification -> best τ=0.410 (val F1=0.3130)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.68476 | val 0.69220
  Epoch 018 - train 0.62015 | val 0.95316
  Classification -> best τ=0.505 (val F1=0.3537)
  Directional -> Accuracy: 0.5745, MCC: 0.1381, F1: 0.6296

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.66751 | val 0.69309
  Epoch 020 - train 0.66681 | val 0.86917
  Epoch 022 - train 0.67796 | val 0.85141
  Classification -> best τ=0.495 (val F1=0.2009)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.65124 | val 0.65905
  Epoch 020 - train 0.59211 | val 0.66583
  Epoch 029 - train 0.56531 | val 0.71832
  Classification -> best τ=0.550 (val F1=0.3493)
  Directional -> Accuracy: 0.5686, MCC: 0.1243, F1: 0.6562

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.67428 | val 0.70920
  Epoch 017 - train 0.65563 | val 0.74057
  Classification -> best τ=0.470 (val F1=0.1857)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.69604 | val 0.71113
  Epoch 020 - train 0.69213 | val 0.70784
  Epoch 023 - train 0.65827 | val 0.75454
  Classification -> best τ=0.515 (val F1=0.2495)
  Directional -> Accuracy: 0.5507, MCC: -0.0208, F1: 0.2439

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.56061 | val 0.63744
  Epoch 018 - train 0.61386 | val 0.69466
  Classification -> best τ=0.285 (val F1=0.1590)
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.67430 | val 0.69752
  Epoch 016 - train 0.61961 | val 0.70794
  Classification -> best τ=0.495 (val F1=0.4121)
  Directional -> Accuracy: 0.4694, MCC: 0.0168, F1: 0.5938

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.64267 | val 0.71851
  Epoch 020 - train 0.60527 | val 0.85659
  Epoch 022 - train 0.63664 | val 0.79049
  Classification -> best τ=0.460 (val F1=0.1275)
  Directional -> Accuracy: 0.4571, MCC: 0.0236, F1: 0.5778

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.65772 | val 0.83217
  Epoch 020 - train 0.62282 | val 1.53679
  Epoch 023 - train 0.62876 | val 1.22469
  Classification -> best τ=0.430 (val F1=0.3094)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.63295 | val 0.78453
  Epoch 017 - train 0.60652 | val 0.88328
  Classification -> best τ=0.545 (val F1=0.1578)
  Directional -> Accuracy: 0.3793, MCC: -0.2651, F1: 0.2174

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.59440 | val 0.77788
  Epoch 017 - train 0.63919 | val 0.87357
  Classification -> best τ=0.470 (val F1=0.2246)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.68149 | val 0.66094
  Epoch 016 - train 0.66947 | val 0.66644
  Classification -> best τ=0.420 (val F1=0.3596)
  Directional -> Accuracy: 0.5500, MCC: 0.1214, F1: 0.6494

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.65619 | val 0.92561
  Epoch 019 - train 0.62801 | val 0.80726
  Classification -> best τ=0.530 (val F1=0.2160)
  Directional -> Accuracy: 0.5577, MCC: 0.1512, F1: 0.0800

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.67888 | val 0.69548
  Epoch 020 - train 0.65997 | val 0.75343
  Epoch 029 - train 0.65537 | val 0.76484
  Classification -> best τ=0.500 (val F1=0.3452)
  Directional -> Accuracy: 0.5652, MCC: 0.1258, F1: 0.5946

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.67043 | val 0.86117
  Epoch 016 - train 0.66808 | val 0.99930
  Classification -> best τ=0.560 (val F1=0.2787)
  Directional -> Accuracy: 0.5593, MCC: -0.1006, F1: 0.7045

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.65570 | val 0.78046
  Epoch 016 - train 0.66359 | val 0.81046
  Classification -> best τ=0.475 (val F1=0.1781)
  Directional -> Accuracy: 0.5733, MCC: 0.1211, F1: 0.6364

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.70253 | val 0.92082
  Epoch 020 - train 0.66942 | val 1.85867
  Classification -> best τ=0.340 (val F1=0.2522)
  Directional -> Accuracy: 0.4923, MCC: 0.1307, F1: 0.3265

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.68225 | val 0.67569
  Epoch 020 - train 0.65815 | val 0.67053
  Epoch 026 - train 0.67039 | val 0.67804
  Classification -> best τ=0.465 (val F1=0.3544)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.67937 | val 0.68105
  Epoch 020 - train 0.60141 | val 0.78012
  Epoch 029 - train 0.58434 | val 1.19898
  Classification -> best τ=0.460 (val F1=0.3518)
  Directional -> Accuracy: 0.4043, MCC: -0.1537, F1: 0.4167

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.69117 | val 0.77647
  Epoch 016 - train 0.66946 | val 0.79362
  Classification -> best τ=0.600 (val F1=0.2140)
  Directional -> Accuracy: 0.5152, MCC: 0.0325, F1: 0.4074

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.71673 | val 0.67801
  Epoch 020 - train 0.66144 | val 0.83879
  Epoch 025 - train 0.64068 | val 0.84065
  Classification -> best τ=0.390 (val F1=0.3179)
  Directional -> Accuracy: 0.5345, MCC: 0.0081, F1: 0.6400

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.65685 | val 0.68220
  Epoch 020 - train 0.67629 | val 0.76653
  Epoch 025 - train 0.65029 | val 0.78237
  Classification -> best τ=0.660 (val F1=0.2390)
  Directional -> Accuracy: 0.5077, MCC: -0.0075, F1: 0.3333

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.67502 | val 0.65129
  Epoch 020 - train 0.57536 | val 0.73756
  Epoch 022 - train 0.56221 | val 0.76109
  Classification -> best τ=0.510 (val F1=0.4149)
  Directional -> Accuracy: 0.5000, MCC: 0.2137, F1: 0.1765

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.66836 | val 0.69952
  Epoch 020 - train 0.57223 | val 0.75334
  Epoch 022 - train 0.58477 | val 0.86485
  Classification -> best τ=0.520 (val F1=0.3669)
  Directional -> Accuracy: 0.5870, MCC: 0.2014, F1: 0.5957

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.64092 | val 0.69088
  Epoch 020 - train 0.62159 | val 0.69103
  Classification -> best τ=0.550 (val F1=0.2759)
  Directional -> Accuracy: 0.5952, MCC: 0.1273, F1: 0.7213

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.65335 | val 0.67158
  Epoch 017 - train 0.66929 | val 0.72237
  Classification -> best τ=0.390 (val F1=0.2946)
  Directional -> Accuracy: 0.5088, MCC: 0.1880, F1: 0.2632

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.79966 | val 0.73082
  Epoch 017 - train 0.63360 | val 0.68492
  Classification -> best τ=0.500 (val F1=0.3296)
  Directional -> Accuracy: 0.6098, MCC: 0.2516, F1: 0.7241

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.68174 | val 0.78255
  Epoch 017 - train 0.69177 | val 0.82664
  Classification -> best τ=0.510 (val F1=0.1959)
  Directional -> Accuracy: 0.5581, MCC: 0.1366, F1: 0.6275

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.72521 | val 0.67652
  Epoch 020 - train 0.59818 | val 0.73529
  Epoch 030 - train 0.57020 | val 0.64924
  Epoch 039 - train 0.54270 | val 0.69037
  Classification -> best τ=0.720 (val F1=0.2525)
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.62063 | val 0.67170
  Epoch 020 - train 0.59212 | val 0.95375
  Epoch 024 - train 0.55575 | val 0.97843
  Classification -> best τ=0.695 (val F1=0.2969)
  Directional -> Accuracy: 0.5200, MCC: -0.1319, F1: 0.6842

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.66358 | val 0.74752
  Epoch 020 - train 0.63740 | val 0.91668
  Epoch 030 - train 0.63047 | val 0.85994
  Epoch 031 - train 0.60980 | val 1.06121
  Classification -> best τ=0.365 (val F1=0.3561)
  Directional -> Accuracy: 0.5890, MCC: 0.1923, F1: 0.5946

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.64876 | val 0.73191
  Epoch 020 - train 0.61184 | val 1.05787
  Classification -> best τ=0.470 (val F1=0.2887)
  Directional -> Accuracy: 0.5676, MCC: 0.1599, F1: 0.6364

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.67589 | val 0.78896
  Epoch 017 - train 0.65168 | val 0.93193
  Classification -> best τ=0.365 (val F1=0.1902)
  Directional -> Accuracy: 0.5909, MCC: 0.2073, F1: 0.6400

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.68731 | val 0.69828
  Epoch 020 - train 0.65385 | val 0.70550
  Classification -> best τ=0.450 (val F1=0.3634)
  Directional -> Accuracy: 0.5909, MCC: 0.2040, F1: 0.5970

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.61880 | val 0.70501
  Epoch 019 - train 0.56534 | val 0.78298
  Classification -> best τ=0.460 (val F1=0.2206)
  Directional -> Accuracy: 0.6429, MCC: 0.2828, F1: 0.6667

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.64194 | val 0.68507
  Epoch 016 - train 0.63751 | val 0.87687
  Classification -> best τ=0.385 (val F1=0.2530)
  Directional -> Accuracy: 0.4821, MCC: 0.1255, F1: 0.6420

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.63883 | val 0.74513
  Epoch 016 - train 0.55535 | val 0.77291
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.76441 | val 0.70171
  Epoch 019 - train 0.61479 | val 0.68541
  Classification -> best τ=0.400 (val F1=0.3533)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.70731 | val 0.75720
  Epoch 016 - train 0.59732 | val 0.98028
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.63296 | val 0.75474
  Epoch 016 - train 0.63251 | val 0.80133
  Classification -> best τ=0.430 (val F1=0.3466)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.63192 | val 0.69549
  Epoch 017 - train 0.62111 | val 0.72728
  Classification -> best τ=0.470 (val F1=0.2739)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.0000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.66027 | val 0.75205
  Epoch 020 - train 0.65511 | val 0.69405
  Epoch 027 - train 0.57443 | val 0.73761
  Classification -> best τ=0.585 (val F1=0.4743)
  Directional -> Accuracy: 0.4419, MCC: -0.1448, F1: 0.5200

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.72333 | val 0.73964
  Epoch 020 - train 0.58703 | val 0.67375
  Epoch 024 - train 0.59955 | val 0.68952
  Classification -> best τ=0.535 (val F1=0.6290)
  Directional -> Accuracy: 0.3673, MCC: -0.1814, F1: 0.5373

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.66021 | val 0.81703
  Epoch 016 - train 0.64074 | val 0.95252
  Classification -> best τ=0.460 (val F1=0.1942)
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.66073 | val 0.80893
  Epoch 020 - train 0.61683 | val 1.05824
  Epoch 023 - train 0.62458 | val 0.89515
  Classification -> best τ=0.615 (val F1=0.4000)
  Directional -> Accuracy: 0.5357, MCC: 0.1073, F1: 0.6286

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.68052 | val 0.83284
  Epoch 018 - train 0.60471 | val 1.18357
  Classification -> best τ=0.575 (val F1=0.1776)
  Directional -> Accuracy: 0.5000, MCC: 0.0225, F1: 0.3415

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.66987 | val 0.74333
  Epoch 020 - train 0.63868 | val 0.74204
  Classification -> best τ=0.480 (val F1=0.1667)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.69459 | val 0.68764

[I 2026-02-25 05:03:02,640] Trial 238 finished with value: 0.27658472032037335 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 64, 'learning_rate': 0.008530939491471844, 'weight_decay': 0.0006739800851189165, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 0.15271232587403538, 'early_stopping_min_delta': 0.0027442245863306697}. Best is trial 200 with value: 0.303360648585588.

  Epoch 018 - train 0.65782 | val 1.20492
  Classification -> best τ=0.455 (val F1=0.3138)
  Directional -> Accuracy: 0.5902, MCC: 0.1771, F1: 0.5614

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.27658472032037335
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.64135 | val 0.66065
  Epoch 020 - train 0.60319 | val 0.68904
  Epoch 022 - train 0.57753 | val 0.66325
  Classification -> best τ=0.565 (val F1=0.2510)
  Directional -> Accuracy: 0.5395, MCC: -0.0120, F1: 0.1463

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.63681 | val 0.72554
  Epoch 019 - train 0.63153 | val 0.71197
  Classification -> best τ=0.435 (val F1=0.3407)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.72354 | val 0.69535
  Epoch 019 - train 0.65884 | val 0.79687
  Classification -> best τ=0.530 (val F1=0.2725)
  Directional -> Accuracy: 0.4894, MCC: -0.0440, F1: 0.5714

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.68663 | val 0.74224
  Epoch 016 - train 0.65315 | val 0.98915
  Classification -> best τ=0.525 (val F1=0.1736)
  Directional -> Accuracy: 0.5067, MCC: 0.0072, F1: 0.5432

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.67100 | val 0.68259
  Epoch 020 - train 0.58110 | val 0.67340
  Classification -> best τ=0.560 (val F1=0.4041)
  Directional -> Accuracy: 0.4118, MCC: -0.1806, F1: 0.4444

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.67709 | val 0.69650
  Epoch 019 - train 0.63667 | val 0.80320
  Classification -> best τ=0.560 (val F1=0.2692)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.68887 | val 0.71018
  Epoch 017 - train 0.66609 | val 0.81938
  Classification -> best τ=0.515 (val F1=0.2441)
  Directional -> Accuracy: 0.5942, MCC: 0.0880, F1: 0.3000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.60412 | val 0.86825
  Epoch 019 - train 0.60641 | val 0.87595
  Classification -> best τ=0.385 (val F1=0.3295)
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.62224 | val 0.70085
  Epoch 020 - train 0.57576 | val 1.05582
  Epoch 027 - train 0.56862 | val 0.74221
  Classification -> best τ=0.235 (val F1=0.2820)
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.63102 | val 0.76391
  Epoch 017 - train 0.61906 | val 0.81810
  Classification -> best τ=0.470 (val F1=0.1826)
  Directional -> Accuracy: 0.4714, MCC: 0.1281, F1: 0.6105

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.65303 | val 0.70153
  Epoch 018 - train 0.64495 | val 1.19743
  Classification -> best τ=0.405 (val F1=0.0891)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.61703 | val 0.73831
  Epoch 020 - train 0.56899 | val 0.88084
  Classification -> best τ=0.435 (val F1=0.2943)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.65955 | val 0.85044
  Epoch 016 - train 0.59075 | val 0.91450
  Classification -> best τ=0.460 (val F1=0.1588)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.67342 | val 0.64879
  Epoch 020 - train 0.65036 | val 0.62988
  Epoch 030 - train 0.62135 | val 0.85728
  Epoch 032 - train 0.58990 | val 0.80212
  Classification -> best τ=0.235 (val F1=0.3282)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.67270 | val 0.72970
  Epoch 019 - train 0.59170 | val 0.75704
  Classification -> best τ=0.500 (val F1=0.2673)
  Directional -> Accuracy: 0.6731, MCC: 0.3387, F1: 0.6222

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.64327 | val 0.69924
  Epoch 017 - train 0.64880 | val 0.80926
  Classification -> best τ=0.475 (val F1=0.1917)
  Directional -> Accuracy: 0.5797, MCC: 0.1424, F1: 0.6667

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.62251 | val 1.00572
  Epoch 016 - train 0.60380 | val 1.21093
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.67271 | val 1.18360
  Epoch 017 - train 0.64295 | val 1.20567
  Classification -> best τ=0.550 (val F1=0.2395)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.64848 | val 0.88408
  Epoch 018 - train 0.64154 | val 1.29592
  Classification -> best τ=0.490 (val F1=0.2648)
  Directional -> Accuracy: 0.4462, MCC: -0.0963, F1: 0.4706

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.68448 | val 0.70230
  Epoch 020 - train 0.62527 | val 0.69631
  Epoch 022 - train 0.63913 | val 0.71132
  Classification -> best τ=0.425 (val F1=0.2462)
  Directional -> Accuracy: 0.5333, MCC: 0.1355, F1: 0.4068

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.65205 | val 0.68169
  Epoch 020 - train 0.62957 | val 0.79448
  Epoch 022 - train 0.59092 | val 0.87160
  Classification -> best τ=0.455 (val F1=0.3707)
  Directional -> Accuracy: 0.5745, MCC: 0.1798, F1: 0.6000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.67570 | val 0.83469
  Epoch 016 - train 0.65456 | val 0.75484
  Classification -> best τ=0.415 (val F1=0.1664)
  Directional -> Accuracy: 0.5303, MCC: 0.1054, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.65258 | val 0.73511
  Epoch 016 - train 0.64241 | val 0.84614
  Classification -> best τ=0.545 (val F1=0.2379)
  Directional -> Accuracy: 0.5517, MCC: -0.0461, F1: 0.7045

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.62864 | val 0.69475
  Epoch 019 - train 0.59697 | val 0.73756
  Classification -> best τ=0.400 (val F1=0.1614)
  Directional -> Accuracy: 0.4769, MCC: 0.0000, F1: 0.6458

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.63227 | val 0.65044
  Epoch 020 - train 0.61087 | val 0.74793
  Epoch 024 - train 0.61475 | val 0.74010
  Classification -> best τ=0.555 (val F1=0.3951)
  Directional -> Accuracy: 0.5357, MCC: 0.1728, F1: 0.3810

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.62193 | val 0.80397
  Epoch 020 - train 0.61112 | val 0.73858
  Classification -> best τ=0.500 (val F1=0.3764)
  Directional -> Accuracy: 0.6522, MCC: 0.3015, F1: 0.6190

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.67478 | val 0.69536
  Epoch 016 - train 0.64846 | val 0.69156
  Classification -> best τ=0.575 (val F1=0.1936)
  Directional -> Accuracy: 0.5238, MCC: 0.1217, F1: 0.4444

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.65935 | val 0.69156
  Epoch 016 - train 0.64780 | val 0.82526
  Classification -> best τ=0.395 (val F1=0.1913)
  Directional -> Accuracy: 0.5439, MCC: 0.1963, F1: 0.4091

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.69073 | val 0.68537
  Epoch 020 - train 0.68266 | val 0.67205
  Epoch 030 - train 0.59114 | val 0.83069
  Epoch 040 - train 0.57543 | val 0.92480
  Epoch 047 - train 0.54032 | val 0.79443
  Classification -> best τ=0.635 (val F1=0.4730)
  Directional -> Accuracy: 0.6098, MCC: 0.2153, F1: 0.6364

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.67776 | val 0.70725
  Epoch 020 - train 0.60173 | val 0.91081
  Epoch 025 - train 0.61099 | val 1.22236
  Classification -> best τ=0.645 (val F1=0.2814)
  Directional -> Accuracy: 0.5116, MCC: 0.0197, F1: 0.4615

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.71302 | val 0.65834
  Epoch 019 - train 0.58102 | val 0.66251
  Classification -> best τ=0.575 (val F1=0.2517)
  Directional -> Accuracy: 0.5349, MCC: 0.0282, F1: 0.6667

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.62424 | val 0.76836
  Epoch 016 - train 0.58026 | val 0.88183
  Classification -> best τ=0.540 (val F1=0.3917)
  Directional -> Accuracy: 0.4200, MCC: -0.1394, F1: 0.2927

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.65052 | val 0.72034
  Epoch 018 - train 0.62790 | val 0.80663
  Classification -> best τ=0.350 (val F1=0.2794)
  Directional -> Accuracy: 0.5616, MCC: 0.1225, F1: 0.5897

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.66860 | val 0.85184
  Epoch 016 - train 0.65550 | val 0.79024
  Classification -> best τ=0.485 (val F1=0.2667)
  Directional -> Accuracy: 0.4865, MCC: -0.0065, F1: 0.6415

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.68500 | val 0.76254
  Epoch 019 - train 0.61752 | val 1.05643
  Classification -> best τ=0.465 (val F1=0.3121)
  Directional -> Accuracy: 0.5227, MCC: 0.0214, F1: 0.2759

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.66399 | val 0.72503
  Epoch 016 - train 0.66152 | val 0.70595
  Classification -> best τ=0.360 (val F1=0.2778)
  Directional -> Accuracy: 0.5758, MCC: 0.0000, F1: 0.7308

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.68791 | val 0.78550
  Epoch 016 - train 0.59384 | val 0.72587
  Classification -> best τ=0.520 (val F1=0.1355)
  Directional -> Accuracy: 0.6429, MCC: 0.2919, F1: 0.6341

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.64690 | val 0.68931
  Epoch 016 - train 0.59326 | val 0.80860
  Classification -> best τ=0.465 (val F1=0.2755)
  Directional -> Accuracy: 0.5000, MCC: 0.0601, F1: 0.6111

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.62349 | val 0.66732
  Epoch 020 - train 0.58498 | val 0.70979
  Epoch 024 - train 0.55331 | val 0.74389
  Classification -> best τ=0.475 (val F1=0.2441)
  Directional -> Accuracy: 0.5652, MCC: 0.1241, F1: 0.6154

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.67601 | val 0.75921
  Epoch 018 - train 0.66194 | val 0.73051
  Classification -> best τ=0.465 (val F1=0.3894)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.60085 | val 0.77675
  Epoch 020 - train 0.66034 | val 0.91027
  Epoch 022 - train 0.60285 | val 0.82560
  Classification -> best τ=0.555 (val F1=0.3162)
  Directional -> Accuracy: 0.4595, MCC: -0.0495, F1: 0.3333

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.64732 | val 0.65795
  Epoch 020 - train 0.61641 | val 0.84691
  Epoch 023 - train 0.62021 | val 0.93177
  Classification -> best τ=0.410 (val F1=0.3189)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.70435 | val 0.73508
  Epoch 018 - train 0.65778 | val 0.71461
  Classification -> best τ=0.475 (val F1=0.3904)
  Directional -> Accuracy: 0.5435, MCC: 0.0790, F1: 0.6667

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.68972 | val 0.71389
  Epoch 020 - train 0.55092 | val 0.73533
  Epoch 023 - train 0.58804 | val 0.68967
  Classification -> best τ=0.570 (val F1=0.5270)
  Directional -> Accuracy: 0.6279, MCC: 0.3078, F1: 0.7500

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.65755 | val 0.70516
  Epoch 017 - train 0.60750 | val 0.72243
  Classification -> best τ=0.390 (val F1=0.6292)
  Directional -> Accuracy: 0.5510, MCC: -0.0530, F1: 0.2143

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.66762 | val 0.89063
  Epoch 016 - train 0.62548 | val 1.62161
  Classification -> best τ=0.545 (val F1=0.3040)
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.66199 | val 0.83267
  Epoch 016 - train 0.65350 | val 1.03776
  Classification -> best τ=0.585 (val F1=0.4000)
  Directional -> Accuracy: 0.5536, MCC: 0.1897, F1: 0.6667

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.67823 | val 1.02914
  Epoch 017 - train 0.62873 | val 1.06525
  Classification -> best τ=0.425 (val F1=0.2365)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.64389 | val 0.83551
  Epoch 020 - train 0.66868 | val 0.70375
  Epoch 022 - train 0.64034 | val 0.77111
  Classification -> best τ=0.455 (val F1=0.0649)
  Directional -> Accuracy: 0.5179, MCC: 0.0187, F1: 0.6301

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.67058 | val 0.76322
  Epoch 020 - train 0.67233 | val 0.76598

[I 2026-02-25 05:04:58,845] Trial 239 finished with value: 0.27989213773818544 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 64, 'learning_rate': 0.006992382409198175, 'weight_decay': 0.0006547292356707355, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 0.11099381241789197, 'early_stopping_min_delta': 0.0029591356886861974}. Best is trial 200 with value: 0.303360648585588.

  Epoch 024 - train 0.63557 | val 0.87868
  Classification -> best τ=0.460 (val F1=0.3074)
  Directional -> Accuracy: 0.5246, MCC: 0.0130, F1: 0.1212

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.27989213773818544
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.63776 | val 0.82254
  Epoch 020 - train 0.57610 | val 1.08836
  Epoch 024 - train 0.48250 | val 1.54658
  Classification -> best τ=0.615 (val F1=0.2510)
  Directional -> Accuracy: 0.5789, MCC: 0.1827, F1: 0.1111

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.55701 | val 0.71945
  Epoch 020 - train 0.42485 | val 0.83688
  Epoch 023 - train 0.42850 | val 1.02490
  Classification -> best τ=0.395 (val F1=0.1833)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.64753 | val 0.76143
  Epoch 020 - train 0.56114 | val 1.95104
  Epoch 023 - train 0.54351 | val 2.64089
  Classification -> best τ=0.570 (val F1=0.3835)
  Directional -> Accuracy: 0.4043, MCC: -0.2064, F1: 0.1250

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.64298 | val 0.73273
  Epoch 020 - train 0.61853 | val 0.73806
  Epoch 030 - train 0.52028 | val 0.94102
  Epoch 036 - train 0.51982 | val 0.71955
  Classification -> best τ=0.410 (val F1=0.3069)
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.51233 | val 0.69888
  Epoch 020 - train 0.53753 | val 0.81260
  Epoch 028 - train 0.40530 | val 0.82976
  Classification -> best τ=0.575 (val F1=0.4598)
  Directional -> Accuracy: 0.5294, MCC: 0.0765, F1: 0.4783

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.53733 | val 0.83684
  Epoch 020 - train 0.44794 | val 0.93476
  Epoch 025 - train 0.39469 | val 1.19604
  Classification -> best τ=0.550 (val F1=0.1443)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.63282 | val 0.79024
  Epoch 020 - train 0.56772 | val 0.98201
  Epoch 022 - train 0.50878 | val 1.15150
  Classification -> best τ=0.510 (val F1=0.2549)
  Directional -> Accuracy: 0.5652, MCC: 0.0468, F1: 0.3478

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.48546 | val 0.74378
  Epoch 020 - train 0.34932 | val 2.09266
  Epoch 025 - train 0.27167 | val 1.99703
  Classification -> best τ=0.295 (val F1=0.0068)
  Directional -> Accuracy: 0.4884, MCC: -0.0866, F1: 0.3125

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.58233 | val 0.78679
  Epoch 020 - train 0.48123 | val 1.29670
  Epoch 023 - train 0.47556 | val 1.24508
  Classification -> best τ=0.555 (val F1=0.4092)
  Directional -> Accuracy: 0.5510, MCC: 0.0212, F1: 0.0833

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.57088 | val 0.88132
  Epoch 020 - train 0.46549 | val 0.95116
  Epoch 026 - train 0.40776 | val 1.35114
  Classification -> best τ=0.490 (val F1=0.2172)
  Directional -> Accuracy: 0.4429, MCC: -0.0481, F1: 0.5301

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.58545 | val 0.96875
  Epoch 020 - train 0.47540 | val 2.20876
  Epoch 023 - train 0.45910 | val 2.33244
  Classification -> best τ=0.495 (val F1=0.3094)
  Directional -> Accuracy: 0.6400, MCC: 0.3092, F1: 0.6667

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.50363 | val 0.75740
  Epoch 020 - train 0.44320 | val 0.90863
  Epoch 024 - train 0.35734 | val 1.19802
  Classification -> best τ=0.610 (val F1=0.2453)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0645

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.50723 | val 0.99783
  Epoch 020 - train 0.42528 | val 2.00190
  Epoch 024 - train 0.41382 | val 1.70637
  Classification -> best τ=0.545 (val F1=0.3566)
  Directional -> Accuracy: 0.5476, MCC: 0.0677, F1: 0.4242

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.56217 | val 0.87605
  Epoch 020 - train 0.47514 | val 2.86556
  Epoch 021 - train 0.49248 | val 3.59990
  Classification -> best τ=0.425 (val F1=0.3012)
  Directional -> Accuracy: 0.6333, MCC: 0.3015, F1: 0.7027

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.57702 | val 0.76213
  Epoch 020 - train 0.51479 | val 0.79470
  Epoch 025 - train 0.38557 | val 1.14395
  Classification -> best τ=0.565 (val F1=0.2160)
  Directional -> Accuracy: 0.5962, MCC: 0.1852, F1: 0.5532

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.61958 | val 0.79382
  Epoch 020 - train 0.55343 | val 1.01194
  Epoch 024 - train 0.52893 | val 1.01861
  Classification -> best τ=0.540 (val F1=0.4852)
  Directional -> Accuracy: 0.5362, MCC: 0.0367, F1: 0.6522

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.57481 | val 1.26178
  Epoch 020 - train 0.51732 | val 1.54096
  Epoch 021 - train 0.47287 | val 1.81241
  Classification -> best τ=0.615 (val F1=0.1510)
  Directional -> Accuracy: 0.3729, MCC: -0.1041, F1: 0.1778

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.63830 | val 0.83458
  Epoch 020 - train 0.58459 | val 1.95791
  Epoch 022 - train 0.60025 | val 2.29507
  Classification -> best τ=0.465 (val F1=0.2109)
  Directional -> Accuracy: 0.6000, MCC: 0.0000, F1: 0.7500

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.59980 | val 1.37031
  Epoch 020 - train 0.54033 | val 2.60975
  Epoch 023 - train 0.52213 | val 3.16005
  Classification -> best τ=0.590 (val F1=0.2175)
  Directional -> Accuracy: 0.4462, MCC: -0.0012, F1: 0.2800

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.60866 | val 0.72849
  Epoch 020 - train 0.51480 | val 0.82599
  Epoch 021 - train 0.54801 | val 0.97517
  Classification -> best τ=0.505 (val F1=0.2656)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.60751 | val 0.78621
  Epoch 020 - train 0.44844 | val 2.36978
  Epoch 025 - train 0.40649 | val 3.14175
  Classification -> best τ=0.565 (val F1=0.3518)
  Directional -> Accuracy: 0.4043, MCC: -0.1919, F1: 0.4615

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.59441 | val 0.90540
  Epoch 020 - train 0.53907 | val 0.83269
  Epoch 021 - train 0.53222 | val 1.07164
  Classification -> best τ=0.380 (val F1=0.1664)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.56105 | val 0.74652
  Epoch 020 - train 0.43705 | val 0.89294
  Epoch 023 - train 0.39581 | val 1.16967
  Classification -> best τ=0.540 (val F1=0.2743)
  Directional -> Accuracy: 0.5517, MCC: 0.0425, F1: 0.6579

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.59093 | val 0.82896
  Epoch 020 - train 0.49798 | val 1.23225
  Epoch 027 - train 0.46571 | val 1.49141
  Classification -> best τ=0.410 (val F1=0.2159)
  Directional -> Accuracy: 0.4769, MCC: 0.0000, F1: 0.6458

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.53740 | val 0.84198
  Epoch 020 - train 0.61655 | val 0.81388
  Epoch 023 - train 0.57485 | val 0.93569
  Classification -> best τ=0.590 (val F1=0.4082)
  Directional -> Accuracy: 0.4821, MCC: 0.0207, F1: 0.3556

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.54551 | val 0.78692
  Epoch 020 - train 0.38823 | val 1.34873
  Epoch 024 - train 0.30273 | val 1.14635
  Classification -> best τ=0.555 (val F1=0.0524)
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.58407 | val 0.67481
  Epoch 020 - train 0.49304 | val 0.93454
  Epoch 028 - train 0.44995 | val 1.18750
  Classification -> best τ=0.585 (val F1=0.2582)
  Directional -> Accuracy: 0.4286, MCC: -0.0589, F1: 0.2000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.57138 | val 0.82724
  Epoch 020 - train 0.49475 | val 1.11756
  Epoch 025 - train 0.48634 | val 1.09440
  Classification -> best τ=0.540 (val F1=0.2319)
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.53880 | val 0.91415
  Epoch 020 - train 0.40497 | val 1.68802
  Epoch 025 - train 0.38707 | val 3.40177
  Classification -> best τ=0.495 (val F1=0.3518)
  Directional -> Accuracy: 0.4878, MCC: -0.2104, F1: 0.6557

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.54418 | val 0.96198
  Epoch 020 - train 0.47250 | val 1.55801
  Epoch 022 - train 0.43315 | val 1.40118
  Classification -> best τ=0.405 (val F1=0.3244)
  Directional -> Accuracy: 0.5116, MCC: 0.0353, F1: 0.5882

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.55472 | val 0.75854
  Epoch 020 - train 0.39415 | val 0.81141
  Epoch 026 - train 0.25464 | val 1.02699
  Classification -> best τ=0.650 (val F1=0.2724)
  Directional -> Accuracy: 0.5814, MCC: 0.2849, F1: 0.4000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.56224 | val 0.91498
  Epoch 020 - train 0.40334 | val 1.32718
  Epoch 023 - train 0.47245 | val 1.15358
  Classification -> best τ=0.330 (val F1=0.2161)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.60711 | val 0.74849
  Epoch 020 - train 0.56102 | val 0.83241
  Epoch 030 - train 0.45253 | val 1.46946
  Epoch 033 - train 0.47071 | val 1.81805
  Classification -> best τ=0.455 (val F1=0.3032)
  Directional -> Accuracy: 0.5479, MCC: 0.1713, F1: 0.4590

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.52425 | val 0.96455
  Epoch 020 - train 0.43163 | val 2.07149
  Epoch 022 - train 0.39039 | val 1.77597
  Classification -> best τ=0.575 (val F1=0.1992)
  Directional -> Accuracy: 0.5405, MCC: 0.1071, F1: 0.1905

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.59294 | val 0.85972
  Epoch 020 - train 0.48456 | val 1.20719
  Epoch 027 - train 0.36264 | val 1.74499
  Classification -> best τ=0.395 (val F1=0.3121)
  Directional -> Accuracy: 0.5455, MCC: 0.1988, F1: 0.6667

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.59722 | val 0.94147
  Epoch 020 - train 0.52193 | val 1.02465
  Epoch 024 - train 0.49524 | val 1.27520
  Classification -> best τ=0.515 (val F1=0.3212)
  Directional -> Accuracy: 0.4394, MCC: -0.0162, F1: 0.2128

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.52233 | val 0.92893
  Epoch 020 - train 0.35097 | val 1.69053
  Epoch 022 - train 0.32504 | val 1.91607
  Classification -> best τ=0.445 (val F1=0.2986)
  Directional -> Accuracy: 0.6190, MCC: 0.2337, F1: 0.6667

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.54996 | val 0.97564
  Epoch 020 - train 0.52066 | val 1.54106
  Epoch 024 - train 0.50164 | val 1.61586
  Classification -> best τ=0.425 (val F1=0.2622)
  Directional -> Accuracy: 0.5893, MCC: 0.2397, F1: 0.6567

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.47035 | val 0.76074
  Epoch 020 - train 0.35874 | val 0.73698
  Epoch 024 - train 0.27308 | val 0.93148
  Classification -> best τ=0.500 (val F1=0.2539)
  Directional -> Accuracy: 0.4348, MCC: 0.0460, F1: 0.2353

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.56733 | val 0.73942
  Epoch 020 - train 0.43965 | val 0.74522
  Epoch 021 - train 0.42127 | val 0.81044
  Classification -> best τ=0.505 (val F1=0.4141)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.53392 | val 0.86898
  Epoch 020 - train 0.37256 | val 1.64851
  Epoch 021 - train 0.31303 | val 1.52107
  Classification -> best τ=0.565 (val F1=0.0585)
  Directional -> Accuracy: 0.5405, MCC: 0.2058, F1: 0.3200

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.58341 | val 0.97954
  Epoch 020 - train 0.54160 | val 1.17156
  Epoch 024 - train 0.49548 | val 1.74943
  Classification -> best τ=0.610 (val F1=0.2652)
  Directional -> Accuracy: 0.5600, MCC: 0.1357, F1: 0.6292

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.60814 | val 0.66011
  Epoch 020 - train 0.50386 | val 1.35023
  Epoch 030 - train 0.33413 | val 1.26291
  Classification -> best τ=0.455 (val F1=0.5224)
  Directional -> Accuracy: 0.4783, MCC: -0.0093, F1: 0.0769

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.52913 | val 0.63632
  Epoch 020 - train 0.40932 | val 0.93063
  Epoch 030 - train 0.27854 | val 2.05162
  Classification -> best τ=0.535 (val F1=0.4568)
  Directional -> Accuracy: 0.6279, MCC: 0.2383, F1: 0.6800

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.52924 | val 0.67160
  Epoch 020 - train 0.43582 | val 0.76174
  Epoch 030 - train 0.27694 | val 0.81795
  Epoch 037 - train 0.21539 | val 1.20483
  Classification -> best τ=0.330 (val F1=0.5514)
  Directional -> Accuracy: 0.4286, MCC: -0.0530, F1: 0.4815

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.57908 | val 1.39411
  Epoch 020 - train 0.54399 | val 2.41908
  Epoch 021 - train 0.56639 | val 1.72515
  Classification -> best τ=0.650 (val F1=0.2787)
  Directional -> Accuracy: 0.5000, MCC: 0.1792, F1: 0.1250

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.54257 | val 1.51976
  Epoch 020 - train 0.51321 | val 2.98842

[I 2026-02-25 05:07:26,943] Trial 240 finished with value: 0.27982664400748086 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 64, 'learning_rate': 0.008351848262029324, 'weight_decay': 0.00040919235494582675, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 50, 'huber_delta': 0.10159686072092727, 'early_stopping_min_delta': 0.0025310994754426394}. Best is trial 200 with value: 0.303360648585588.

  Epoch 027 - train 0.39756 | val 1.20883
  Classification -> best τ=0.385 (val F1=0.1674)
  Directional -> Accuracy: 0.5246, MCC: 0.0732, F1: 0.5915

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.27982664400748086
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.69280 | val 0.65355
  Epoch 020 - train 0.61607 | val 0.78212
  Epoch 025 - train 0.60947 | val 0.86887
  Classification -> best τ=0.535 (val F1=0.2919)
  Directional -> Accuracy: 0.5789, MCC: 0.1321, F1: 0.4667

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.66949 | val 0.71943
  Epoch 020 - train 0.62129 | val 0.68297
  Classification -> best τ=0.495 (val F1=0.2431)
  Directional -> Accuracy: 0.6889, MCC: 0.3513, F1: 0.7667

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.66679 | val 0.75525
  Epoch 018 - train 0.65039 | val 0.78227
  Classification -> best τ=0.510 (val F1=0.3924)
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.67557 | val 0.73879
  Epoch 018 - train 0.67660 | val 0.82010
  Classification -> best τ=0.480 (val F1=0.2782)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.63073 | val 0.65065
  Epoch 020 - train 0.58617 | val 0.75006
  Epoch 022 - train 0.61383 | val 0.72270
  Classification -> best τ=0.605 (val F1=0.5047)
  Directional -> Accuracy: 0.5294, MCC: 0.0398, F1: 0.6129

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.72460 | val 0.71432
  Epoch 020 - train 0.59484 | val 0.75613
  Epoch 030 - train 0.59012 | val 0.74898
  Epoch 032 - train 0.52481 | val 0.88646
  Classification -> best τ=0.465 (val F1=0.2037)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.67950 | val 0.71293
  Epoch 020 - train 0.63768 | val 0.73896
  Epoch 022 - train 0.65221 | val 0.75992
  Classification -> best τ=0.445 (val F1=0.1645)
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.69487 | val 0.63078
  Epoch 020 - train 0.58875 | val 1.28924
  Epoch 027 - train 0.56518 | val 0.91463
  Classification -> best τ=0.280 (val F1=0.1752)
  Directional -> Accuracy: 0.3721, MCC: -0.2024, F1: 0.4706

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.69933 | val 0.68765
  Epoch 017 - train 0.59994 | val 0.78429
  Classification -> best τ=0.400 (val F1=0.1353)
  Directional -> Accuracy: 0.4694, MCC: 0.0332, F1: 0.6061

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.64466 | val 0.78378
  Epoch 017 - train 0.60114 | val 0.76854
  Classification -> best τ=0.545 (val F1=0.2922)
  Directional -> Accuracy: 0.5000, MCC: 0.0742, F1: 0.5679

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.64365 | val 0.85053
  Epoch 017 - train 0.63031 | val 1.44371
  Classification -> best τ=0.605 (val F1=0.3094)
  Directional -> Accuracy: 0.6200, MCC: 0.2766, F1: 0.3448

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.65785 | val 0.73593
  Epoch 018 - train 0.55662 | val 1.02018
  Classification -> best τ=0.570 (val F1=0.2105)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.68035 | val 0.74604
  Epoch 020 - train 0.56352 | val 0.97841
  Epoch 021 - train 0.52961 | val 1.12891
  Classification -> best τ=0.630 (val F1=0.3142)
  Directional -> Accuracy: 0.5000, MCC: -0.0046, F1: 0.4615

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.64569 | val 0.63501
  Epoch 020 - train 0.63623 | val 0.67963
  Epoch 021 - train 0.63296 | val 0.74073
  Classification -> best τ=0.330 (val F1=0.3477)
  Directional -> Accuracy: 0.5333, MCC: 0.1111, F1: 0.6667

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.66741 | val 0.70545
  Epoch 020 - train 0.58449 | val 0.88895
  Epoch 024 - train 0.56213 | val 1.05541
  Classification -> best τ=0.610 (val F1=0.2160)
  Directional -> Accuracy: 0.5192, MCC: -0.1296, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.64838 | val 0.69717
  Epoch 020 - train 0.60222 | val 0.80376
  Epoch 022 - train 0.60070 | val 1.04376
  Classification -> best τ=0.660 (val F1=0.3095)
  Directional -> Accuracy: 0.5652, MCC: 0.1730, F1: 0.4828

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.63902 | val 0.84772
  Epoch 016 - train 0.65620 | val 0.98847
  Classification -> best τ=0.735 (val F1=0.1842)
  Directional -> Accuracy: 0.3729, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.67081 | val 0.76949
  Epoch 018 - train 0.62081 | val 1.17034
  Classification -> best τ=0.370 (val F1=0.1917)
  Directional -> Accuracy: 0.5200, MCC: 0.0219, F1: 0.5814

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.66104 | val 1.04186
  Epoch 016 - train 0.62961 | val 1.16859
  Classification -> best τ=0.465 (val F1=0.2752)
  Directional -> Accuracy: 0.5077, MCC: 0.1597, F1: 0.3600

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.66370 | val 0.66794
  Epoch 020 - train 0.65231 | val 0.68469
  Epoch 029 - train 0.60477 | val 0.69442
  Classification -> best τ=0.480 (val F1=0.2938)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.67845 | val 0.75524
  Epoch 020 - train 0.58707 | val 0.99151
  Epoch 022 - train 0.54769 | val 1.16949
  Classification -> best τ=0.470 (val F1=0.3307)
  Directional -> Accuracy: 0.5745, MCC: -0.0074, F1: 0.7059

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.66591 | val 0.93944
  Epoch 017 - train 0.64278 | val 0.98246
  Classification -> best τ=0.505 (val F1=0.2062)
  Directional -> Accuracy: 0.5606, MCC: 0.1571, F1: 0.3556

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.67151 | val 0.69528
  Epoch 017 - train 0.65564 | val 0.74983
  Classification -> best τ=0.505 (val F1=0.2760)
  Directional -> Accuracy: 0.5517, MCC: 0.0514, F1: 0.6486

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.64419 | val 0.69968
  Epoch 019 - train 0.58411 | val 0.88527
  Classification -> best τ=0.515 (val F1=0.1507)
  Directional -> Accuracy: 0.5385, MCC: 0.0808, F1: 0.5455

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.68438 | val 0.70269
  Epoch 020 - train 0.59276 | val 0.81804
  Epoch 021 - train 0.59403 | val 0.93014
  Classification -> best τ=0.505 (val F1=0.4388)
  Directional -> Accuracy: 0.5357, MCC: 0.1728, F1: 0.3810

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.67851 | val 0.75355
  Epoch 018 - train 0.60200 | val 0.84145
  Classification -> best τ=0.540 (val F1=0.1932)
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.63575 | val 0.69669
  Epoch 020 - train 0.61674 | val 0.71233
  Epoch 022 - train 0.62000 | val 0.72472
  Classification -> best τ=0.555 (val F1=0.1936)
  Directional -> Accuracy: 0.5238, MCC: 0.0278, F1: 0.5833

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.67432 | val 0.68393
  Epoch 020 - train 0.62196 | val 0.68014
  Epoch 026 - train 0.58653 | val 0.72578
  Classification -> best τ=0.440 (val F1=0.3050)
  Directional -> Accuracy: 0.5263, MCC: 0.0509, F1: 0.5574

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.68374 | val 0.68439
  Epoch 020 - train 0.61136 | val 0.71245
  Epoch 029 - train 0.57080 | val 1.37371
  Classification -> best τ=0.505 (val F1=0.4345)
  Directional -> Accuracy: 0.5122, MCC: -0.1469, F1: 0.6774

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.67866 | val 0.80090
  Epoch 020 - train 0.65368 | val 0.84596
  Classification -> best τ=0.530 (val F1=0.2814)
  Directional -> Accuracy: 0.5116, MCC: 0.0397, F1: 0.6038

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.65794 | val 0.78080
  Epoch 020 - train 0.62498 | val 0.69944
  Epoch 030 - train 0.62498 | val 0.76699
  Classification -> best τ=0.560 (val F1=0.2095)
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.59905 | val 0.70068
  Epoch 020 - train 0.59509 | val 0.85577
  Epoch 022 - train 0.56805 | val 0.84230
  Classification -> best τ=0.380 (val F1=0.3323)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.66155 | val 0.66915
  Epoch 016 - train 0.64671 | val 0.68675
  Classification -> best τ=0.400 (val F1=0.3809)
  Directional -> Accuracy: 0.5753, MCC: 0.1768, F1: 0.5634

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.65287 | val 0.74604
  Epoch 016 - train 0.56977 | val 0.93437
  Classification -> best τ=0.570 (val F1=0.2887)
  Directional -> Accuracy: 0.5405, MCC: 0.0898, F1: 0.2609

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.69156 | val 0.78426
  Epoch 020 - train 0.65241 | val 0.90620
  Epoch 022 - train 0.68178 | val 0.87938
  Classification -> best τ=0.450 (val F1=0.2757)
  Directional -> Accuracy: 0.4773, MCC: -0.1439, F1: 0.0800

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.64313 | val 0.75255
  Epoch 016 - train 0.62417 | val 0.82249
  Classification -> best τ=0.420 (val F1=0.4292)
  Directional -> Accuracy: 0.6061, MCC: 0.1734, F1: 0.6829

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.64715 | val 0.79473
  Epoch 018 - train 0.52652 | val 0.86303
  Classification -> best τ=0.465 (val F1=0.2357)
  Directional -> Accuracy: 0.6905, MCC: 0.3928, F1: 0.7451

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.62750 | val 0.70244
  Epoch 020 - train 0.60724 | val 1.00076
  Classification -> best τ=0.395 (val F1=0.2868)
  Directional -> Accuracy: 0.5357, MCC: 0.1754, F1: 0.6486

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.63218 | val 0.76671
  Epoch 019 - train 0.57264 | val 0.79143
  Classification -> best τ=0.520 (val F1=0.2185)
  Directional -> Accuracy: 0.3913, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.65327 | val 0.69525
  Epoch 020 - train 0.64237 | val 0.64778
  Epoch 030 - train 0.60838 | val 0.69931
  Epoch 033 - train 0.53160 | val 0.74815
  Classification -> best τ=0.410 (val F1=0.4188)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.84613 | val 0.68024
  Epoch 020 - train 0.57470 | val 0.82011
  Epoch 021 - train 0.64913 | val 0.85138
  Classification -> best τ=0.355 (val F1=0.4368)
  Directional -> Accuracy: 0.5676, MCC: 0.1167, F1: 0.6364

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.63668 | val 0.72736
  Epoch 020 - train 0.63104 | val 0.85385
  Epoch 023 - train 0.59406 | val 1.08394
  Classification -> best τ=0.420 (val F1=0.3331)
  Directional -> Accuracy: 0.5200, MCC: 0.1633, F1: 0.6727

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.67186 | val 0.70796
  Epoch 020 - train 0.58569 | val 0.70313
  Classification -> best τ=0.510 (val F1=0.3403)
  Directional -> Accuracy: 0.5435, MCC: 0.1945, F1: 0.2759

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.73567 | val 0.72697
  Epoch 020 - train 0.59036 | val 0.90425
  Classification -> best τ=0.475 (val F1=0.5367)
  Directional -> Accuracy: 0.6279, MCC: 0.2616, F1: 0.7419

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.67264 | val 0.71638
  Epoch 020 - train 0.59718 | val 0.72589
  Epoch 021 - train 0.61043 | val 0.70215
  Classification -> best τ=0.500 (val F1=0.4682)
  Directional -> Accuracy: 0.3673, MCC: -0.1814, F1: 0.5373

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.65922 | val 0.70930
  Epoch 016 - train 0.67465 | val 0.95764
  Classification -> best τ=0.685 (val F1=0.1216)
  Directional -> Accuracy: 0.4286, MCC: -0.1432, F1: 0.4483

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.68421 | val 0.78826
  Epoch 020 - train 0.64280 | val 1.11572
  Epoch 022 - train 0.61666 | val 1.08313
  Classification -> best τ=0.455 (val F1=0.4000)
  Directional -> Accuracy: 0.5179, MCC: 0.0766, F1: 0.6301

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.64657 | val 1.62943
  Epoch 019 - train 0.62723 | val 1.77296
  Classification -> best τ=0.430 (val F1=0.2552)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.65480 | val 0.77819
  Epoch 020 - train 0.59194 | val 0.74206
  Epoch 030 - train 0.56249 | val 0.77686
  Epoch 033 - train 0.53208 | val 0.87563
  Classification -> best τ=0.475 (val F1=0.1667)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.66197 | val 0.75922

[I 2026-02-25 05:09:31,221] Trial 241 finished with value: 0.28556749645521506 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 64, 'learning_rate': 0.006400006348813665, 'weight_decay': 0.0004996570909546003, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 0.15928775372462484, 'early_stopping_min_delta': 0.00288157685876502}. Best is trial 200 with value: 0.303360648585588.

  Epoch 016 - train 0.63573 | val 0.78458
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.28556749645521506
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.66375 | val 0.66957
  Epoch 020 - train 0.65450 | val 0.71597
  Epoch 024 - train 0.60925 | val 0.69980
  Classification -> best τ=0.560 (val F1=0.2510)
  Directional -> Accuracy: 0.5395, MCC: 0.0059, F1: 0.2222

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.63368 | val 0.68476
  Epoch 020 - train 0.60216 | val 0.73462
  Classification -> best τ=0.495 (val F1=0.3012)
  Directional -> Accuracy: 0.7111, MCC: 0.5449, F1: 0.6667

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.67349 | val 0.70506
  Epoch 017 - train 0.66070 | val 0.79459
  Classification -> best τ=0.525 (val F1=0.2359)
  Directional -> Accuracy: 0.6170, MCC: 0.2764, F1: 0.5500

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.68662 | val 0.72435
  Epoch 017 - train 0.66124 | val 0.76065
  Classification -> best τ=0.505 (val F1=0.0942)
  Directional -> Accuracy: 0.5600, MCC: 0.0875, F1: 0.7080

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.65929 | val 0.67675
  Epoch 020 - train 0.62908 | val 0.66578
  Epoch 021 - train 0.58547 | val 0.80075
  Classification -> best τ=0.510 (val F1=0.4158)
  Directional -> Accuracy: 0.3922, MCC: -0.2810, F1: 0.5231

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.61211 | val 0.71037
  Epoch 016 - train 0.63025 | val 0.92920
  Classification -> best τ=0.495 (val F1=0.0976)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.69544 | val 0.69128
  Epoch 020 - train 0.66193 | val 0.78921
  Epoch 023 - train 0.67469 | val 0.76482
  Classification -> best τ=0.535 (val F1=0.1988)
  Directional -> Accuracy: 0.5217, MCC: 0.0699, F1: 0.5075

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.63985 | val 0.83342
  Epoch 016 - train 0.64661 | val 0.99624
  Classification -> best τ=0.385 (val F1=0.1234)
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.69320 | val 0.69183
  Epoch 017 - train 0.59167 | val 0.78562
  Classification -> best τ=0.395 (val F1=0.2129)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.66770 | val 0.76272
  Epoch 019 - train 0.61605 | val 0.70032
  Classification -> best τ=0.565 (val F1=0.2133)
  Directional -> Accuracy: 0.5000, MCC: -0.0251, F1: 0.4068

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.67325 | val 0.95549
  Epoch 020 - train 0.61293 | val 1.11731
  Epoch 021 - train 0.63263 | val 1.04169
  Classification -> best τ=0.485 (val F1=0.3094)
  Directional -> Accuracy: 0.5600, MCC: 0.1048, F1: 0.1538

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.66352 | val 0.77251
  Epoch 016 - train 0.60991 | val 1.07510
  Classification -> best τ=0.480 (val F1=0.2427)
  Directional -> Accuracy: 0.5172, MCC: 0.0440, F1: 0.6316

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.64392 | val 0.70641
  Epoch 019 - train 0.64559 | val 1.23643
  Classification -> best τ=0.450 (val F1=0.2304)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.68002 | val 0.71359
  Epoch 018 - train 0.67233 | val 0.71161
  Classification -> best τ=0.585 (val F1=0.3378)
  Directional -> Accuracy: 0.5500, MCC: 0.1048, F1: 0.4706

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.62024 | val 0.71169
  Epoch 018 - train 0.58383 | val 0.85285
  Classification -> best τ=0.535 (val F1=0.2160)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.66764 | val 0.70062
  Epoch 017 - train 0.65446 | val 0.77254
  Classification -> best τ=0.635 (val F1=0.3388)
  Directional -> Accuracy: 0.5217, MCC: 0.0405, F1: 0.5479

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.65184 | val 0.94601
  Epoch 020 - train 0.60335 | val 1.16220
  Classification -> best τ=0.390 (val F1=0.1336)
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.66575 | val 0.90667
  Epoch 017 - train 0.62787 | val 1.12444
  Classification -> best τ=0.545 (val F1=0.1556)
  Directional -> Accuracy: 0.3733, MCC: -0.1601, F1: 0.1455

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.66672 | val 0.92917
  Epoch 019 - train 0.64331 | val 1.66057
  Classification -> best τ=0.315 (val F1=0.2522)
  Directional -> Accuracy: 0.4923, MCC: 0.1307, F1: 0.3265

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.65900 | val 0.65784
  Epoch 020 - train 0.66688 | val 0.70896
  Epoch 025 - train 0.64290 | val 0.78814
  Classification -> best τ=0.455 (val F1=0.3871)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.64713 | val 0.68399
  Epoch 020 - train 0.58918 | val 0.99075
  Epoch 025 - train 0.54099 | val 1.55194
  Classification -> best τ=0.470 (val F1=0.3707)
  Directional -> Accuracy: 0.5319, MCC: -0.0598, F1: 0.6562

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.68691 | val 0.73862
  Epoch 017 - train 0.63084 | val 0.76563
  Classification -> best τ=0.525 (val F1=0.2766)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.5714

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.70172 | val 0.69261
  Epoch 020 - train 0.67214 | val 0.69999
  Classification -> best τ=0.480 (val F1=0.2894)
  Directional -> Accuracy: 0.5172, MCC: 0.0253, F1: 0.5625

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.67753 | val 0.76620
  Epoch 019 - train 0.61513 | val 0.85096
  Classification -> best τ=0.480 (val F1=0.1271)
  Directional -> Accuracy: 0.4923, MCC: -0.0320, F1: 0.3774

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.65947 | val 0.64524
  Epoch 020 - train 0.61476 | val 0.68071
  Epoch 023 - train 0.59426 | val 0.67640
  Classification -> best τ=0.410 (val F1=0.4376)
  Directional -> Accuracy: 0.5000, MCC: -0.0460, F1: 0.6000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.65959 | val 0.71204
  Epoch 016 - train 0.57971 | val 0.69988
  Classification -> best τ=0.420 (val F1=0.2935)
  Directional -> Accuracy: 0.5435, MCC: 0.1123, F1: 0.5532

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.64219 | val 0.69634
  Epoch 019 - train 0.61440 | val 0.68193
  Classification -> best τ=0.570 (val F1=0.0534)
  Directional -> Accuracy: 0.4048, MCC: -0.1340, F1: 0.2424

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.65452 | val 0.70427
  Epoch 018 - train 0.61807 | val 0.74509
  Classification -> best τ=0.455 (val F1=0.2347)
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.75360 | val 0.69132
  Epoch 019 - train 0.65150 | val 0.74093
  Classification -> best τ=0.580 (val F1=0.4099)
  Directional -> Accuracy: 0.4634, MCC: -0.0789, F1: 0.5000

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.67098 | val 0.78318
  Epoch 016 - train 0.62372 | val 0.87216
  Classification -> best τ=0.535 (val F1=0.2814)
  Directional -> Accuracy: 0.5349, MCC: 0.0675, F1: 0.5000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.68613 | val 0.64854
  Epoch 017 - train 0.69270 | val 0.80396
  Classification -> best τ=0.675 (val F1=0.1096)
  Directional -> Accuracy: 0.4884, MCC: -0.1381, F1: 0.6452

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.61712 | val 0.88170
  Epoch 016 - train 0.59581 | val 1.16240
  Classification -> best τ=0.515 (val F1=0.2816)
  Directional -> Accuracy: 0.6000, MCC: 0.1879, F1: 0.6970

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.64811 | val 0.73090
  Epoch 020 - train 0.62877 | val 0.75434
  Epoch 022 - train 0.65816 | val 0.75625
  Classification -> best τ=0.520 (val F1=0.2343)
  Directional -> Accuracy: 0.4384, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.67368 | val 0.70225
  Epoch 020 - train 0.62993 | val 0.71322
  Epoch 024 - train 0.59873 | val 1.24643
  Classification -> best τ=0.540 (val F1=0.2887)
  Directional -> Accuracy: 0.5405, MCC: 0.0774, F1: 0.4848

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.69750 | val 0.71115
  Epoch 020 - train 0.65911 | val 0.89386
  Epoch 023 - train 0.63369 | val 0.84205
  Classification -> best τ=0.745 (val F1=0.3103)
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.66946 | val 0.72434
  Epoch 016 - train 0.62095 | val 0.75108
  Classification -> best τ=0.400 (val F1=0.3525)
  Directional -> Accuracy: 0.6061, MCC: 0.1627, F1: 0.6977

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.63484 | val 0.73209
  Epoch 016 - train 0.61145 | val 0.86089
  Classification -> best τ=0.490 (val F1=0.3499)
  Directional -> Accuracy: 0.6429, MCC: 0.2860, F1: 0.6512

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.62993 | val 0.66863
  Epoch 017 - train 0.62709 | val 0.82150
  Classification -> best τ=0.435 (val F1=0.2327)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.4815

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.60979 | val 1.04863
  Epoch 016 - train 0.56716 | val 0.85703
  Classification -> best τ=0.510 (val F1=0.2441)
  Directional -> Accuracy: 0.3913, MCC: -0.0475, F1: 0.0667

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.72517 | val 0.70600
  Epoch 018 - train 0.70458 | val 0.68886
  Classification -> best τ=0.430 (val F1=0.3533)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.71409 | val 0.82281
  Epoch 019 - train 0.64196 | val 0.76811
  Classification -> best τ=0.395 (val F1=0.3019)
  Directional -> Accuracy: 0.4595, MCC: -0.1435, F1: 0.5833

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.64673 | val 0.68666
  Epoch 020 - train 0.63730 | val 0.97509
  Epoch 023 - train 0.60815 | val 1.08358
  Classification -> best τ=0.495 (val F1=0.3677)
  Directional -> Accuracy: 0.5333, MCC: 0.2014, F1: 0.6789

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.63856 | val 0.68414
  Epoch 019 - train 0.60890 | val 0.70920
  Classification -> best τ=0.425 (val F1=0.3952)
  Directional -> Accuracy: 0.5000, MCC: 0.1427, F1: 0.0800

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.75457 | val 0.75526
  Epoch 020 - train 0.61380 | val 0.84597
  Classification -> best τ=0.440 (val F1=0.4330)
  Directional -> Accuracy: 0.5814, MCC: 0.1155, F1: 0.7097

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.72958 | val 0.64075
  Epoch 020 - train 0.59678 | val 0.68286
  Epoch 025 - train 0.58005 | val 0.65100
  Classification -> best τ=0.550 (val F1=0.2605)
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.65385 | val 0.95846
  Epoch 016 - train 0.65521 | val 1.39214
  Classification -> best τ=0.715 (val F1=0.1914)
  Directional -> Accuracy: 0.4821, MCC: 0.1255, F1: 0.0645

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.66257 | val 0.89543
  Epoch 020 - train 0.65067 | val 0.95243
  Epoch 021 - train 0.61718 | val 0.95616
  Classification -> best τ=0.595 (val F1=0.3622)
  Directional -> Accuracy: 0.6071, MCC: 0.2313, F1: 0.4500

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.67779 | val 0.83290
  Epoch 018 - train 0.64177 | val 1.11818
  Classification -> best τ=0.350 (val F1=0.2431)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.70622 | val 0.77799
  Epoch 017 - train 0.62583 | val 0.90033
  Classification -> best τ=0.335 (val F1=0.2222)
  Directional -> Accuracy: 0.4107, MCC: -0.2874, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.69969 | val 0.70231
  Epoch 020 - train 0.62682 | val 1.05176
  Epoch 021 - train 0.64640 | val 0.96086

[I 2026-02-25 05:11:28,984] Trial 242 finished with value: 0.2648140055377318 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 64, 'learning_rate': 0.006509659737774079, 'weight_decay': 0.0008505438744725244, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 0.15387517940923143, 'early_stopping_min_delta': 0.0028082744136491674}. Best is trial 200 with value: 0.303360648585588.

  Classification -> best τ=0.385 (val F1=0.1843)
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2648140055377318
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.64657 | val 0.67589
  Epoch 017 - train 0.61765 | val 0.71164
  Classification -> best τ=0.525 (val F1=0.2510)
  Directional -> Accuracy: 0.5526, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.63410 | val 0.68337
  Epoch 020 - train 0.56832 | val 0.69110
  Epoch 023 - train 0.56464 | val 0.68748
  Classification -> best τ=0.490 (val F1=0.1812)
  Directional -> Accuracy: 0.6222, MCC: 0.2440, F1: 0.6531

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.66237 | val 0.68114
  Epoch 020 - train 0.63052 | val 0.91822
  Epoch 021 - train 0.61519 | val 0.97367
  Classification -> best τ=0.560 (val F1=0.2861)
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.69833 | val 0.71577
  Epoch 017 - train 0.65909 | val 0.72120
  Classification -> best τ=0.530 (val F1=0.1210)
  Directional -> Accuracy: 0.5333, MCC: 0.0188, F1: 0.6465

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.63335 | val 0.67328
  Epoch 019 - train 0.59913 | val 0.69453
  Classification -> best τ=0.485 (val F1=0.3808)
  Directional -> Accuracy: 0.4706, MCC: -0.0833, F1: 0.5574

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.70414 | val 0.70339
  Epoch 020 - train 0.60760 | val 0.70536
  Epoch 028 - train 0.54789 | val 0.79875
  Classification -> best τ=0.485 (val F1=0.2132)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.69543 | val 0.71385
  Epoch 020 - train 0.65627 | val 0.70470
  Classification -> best τ=0.555 (val F1=0.1800)
  Directional -> Accuracy: 0.5797, MCC: -0.0315, F1: 0.0645

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.68533 | val 0.67968
  Epoch 020 - train 0.57291 | val 0.62227
  Epoch 022 - train 0.52411 | val 0.63387
  Classification -> best τ=0.275 (val F1=0.1502)
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.5902

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.68466 | val 0.71977
  Epoch 018 - train 0.54546 | val 0.83020
  Classification -> best τ=0.490 (val F1=0.2881)
  Directional -> Accuracy: 0.6122, MCC: 0.2027, F1: 0.4242

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.65499 | val 0.73676
  Epoch 020 - train 0.65019 | val 0.74759
  Epoch 030 - train 0.58208 | val 0.91185
  Epoch 032 - train 0.58828 | val 1.32296
  Classification -> best τ=0.540 (val F1=0.2282)
  Directional -> Accuracy: 0.5000, MCC: 0.0430, F1: 0.5333

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.67895 | val 0.78799
  Epoch 019 - train 0.60743 | val 1.62900
  Classification -> best τ=0.505 (val F1=0.1675)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.65440 | val 0.72931
  Epoch 020 - train 0.59758 | val 1.00403
  Classification -> best τ=0.475 (val F1=0.2654)
  Directional -> Accuracy: 0.4655, MCC: -0.0851, F1: 0.5867

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.64384 | val 0.74406
  Epoch 020 - train 0.61165 | val 1.16922
  Epoch 023 - train 0.58745 | val 1.41643
  Classification -> best τ=0.495 (val F1=0.3002)
  Directional -> Accuracy: 0.3571, MCC: -0.2901, F1: 0.4906

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.67376 | val 0.66997
  Epoch 016 - train 0.66089 | val 0.65351
  Classification -> best τ=0.450 (val F1=0.4317)
  Directional -> Accuracy: 0.5500, MCC: 0.1048, F1: 0.4706

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.69955 | val 0.70229
  Epoch 020 - train 0.57643 | val 0.70807
  Epoch 024 - train 0.61770 | val 0.82186
  Classification -> best τ=0.515 (val F1=0.2160)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.65866 | val 0.67221
  Epoch 020 - train 0.60037 | val 0.86554
  Epoch 024 - train 0.55802 | val 0.97623
  Classification -> best τ=0.570 (val F1=0.2723)
  Directional -> Accuracy: 0.5507, MCC: 0.1374, F1: 0.4746

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.66903 | val 0.82299
  Epoch 016 - train 0.63245 | val 1.04937
  Classification -> best τ=0.615 (val F1=0.1842)
  Directional -> Accuracy: 0.3729, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.68698 | val 0.77980
  Epoch 018 - train 0.64239 | val 0.83350
  Classification -> best τ=0.490 (val F1=0.1581)
  Directional -> Accuracy: 0.3867, MCC: -0.1424, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.66219 | val 1.16011
  Epoch 018 - train 0.64026 | val 1.51779
  Classification -> best τ=0.405 (val F1=0.2491)
  Directional -> Accuracy: 0.4462, MCC: -0.1530, F1: 0.5385

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.68564 | val 0.68790
  Epoch 020 - train 0.65342 | val 0.75694
  Epoch 024 - train 0.62124 | val 0.77072
  Classification -> best τ=0.525 (val F1=0.2812)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.66043 | val 0.70340
  Epoch 020 - train 0.61881 | val 0.87632
  Epoch 027 - train 0.59817 | val 1.14287
  Classification -> best τ=0.470 (val F1=0.3740)
  Directional -> Accuracy: 0.5106, MCC: 0.0584, F1: 0.5306

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.68071 | val 0.78779
  Epoch 018 - train 0.65215 | val 0.83300
  Classification -> best τ=0.460 (val F1=0.2791)
  Directional -> Accuracy: 0.4545, MCC: -0.1004, F1: 0.5500

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.65367 | val 0.70157
  Epoch 020 - train 0.64094 | val 0.75193
  Classification -> best τ=0.640 (val F1=0.3031)
  Directional -> Accuracy: 0.5345, MCC: 0.1867, F1: 0.4000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.68019 | val 0.71979
  Epoch 020 - train 0.62212 | val 0.78235
  Epoch 023 - train 0.58466 | val 1.05751
  Classification -> best τ=0.440 (val F1=0.1992)
  Directional -> Accuracy: 0.4769, MCC: 0.0000, F1: 0.6458

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.66750 | val 0.63931
  Epoch 020 - train 0.65298 | val 0.70413
  Epoch 026 - train 0.57765 | val 0.76589
  Classification -> best τ=0.525 (val F1=0.4057)
  Directional -> Accuracy: 0.4464, MCC: -0.0373, F1: 0.1622

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.67587 | val 0.71425
  Epoch 017 - train 0.63147 | val 0.81755
  Classification -> best τ=0.440 (val F1=0.2935)
  Directional -> Accuracy: 0.5652, MCC: 0.1801, F1: 0.6000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.66016 | val 0.68831
  Epoch 019 - train 0.63771 | val 0.69687
  Classification -> best τ=0.580 (val F1=0.1936)
  Directional -> Accuracy: 0.4286, MCC: -0.0913, F1: 0.3333

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.68802 | val 0.69752
  Epoch 017 - train 0.62790 | val 0.82866
  Classification -> best τ=0.425 (val F1=0.2294)
  Directional -> Accuracy: 0.5614, MCC: 0.3307, F1: 0.3590

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.80222 | val 0.68206
  Epoch 020 - train 0.59238 | val 0.63610
  Epoch 030 - train 0.66913 | val 1.47708
  Epoch 035 - train 0.53638 | val 2.00693
  Classification -> best τ=0.515 (val F1=0.4099)
  Directional -> Accuracy: 0.5122, MCC: -0.0317, F1: 0.6429

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.66996 | val 0.72559
  Epoch 020 - train 0.64019 | val 0.92518
  Epoch 028 - train 0.53737 | val 0.99689
  Classification -> best τ=0.620 (val F1=0.2814)
  Directional -> Accuracy: 0.5349, MCC: 0.0664, F1: 0.4737

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.73865 | val 0.65510
  Epoch 017 - train 0.65407 | val 0.81768
  Classification -> best τ=0.550 (val F1=0.1746)
  Directional -> Accuracy: 0.5581, MCC: 0.0981, F1: 0.6885

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.59032 | val 0.74451
  Epoch 019 - train 0.61440 | val 0.99135
  Classification -> best τ=0.390 (val F1=0.1687)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.67440 | val 0.67617
  Epoch 020 - train 0.61819 | val 0.68604
  Epoch 030 - train 0.62460 | val 0.75848
  Epoch 037 - train 0.61277 | val 0.94080
  Classification -> best τ=0.385 (val F1=0.3396)
  Directional -> Accuracy: 0.5616, MCC: 0.1530, F1: 0.5429

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.59914 | val 0.79672
  Epoch 017 - train 0.57727 | val 1.06809
  Classification -> best τ=0.515 (val F1=0.1992)
  Directional -> Accuracy: 0.5676, MCC: 0.1737, F1: 0.6522

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.65965 | val 0.88019
  Epoch 019 - train 0.65313 | val 0.93219
  Classification -> best τ=0.405 (val F1=0.1902)
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.68639 | val 0.71052
  Epoch 020 - train 0.65215 | val 0.72305
  Epoch 030 - train 0.61612 | val 0.89486
  Classification -> best τ=0.350 (val F1=0.3280)
  Directional -> Accuracy: 0.6061, MCC: 0.2529, F1: 0.5938

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.72008 | val 0.71284
  Epoch 016 - train 0.55049 | val 0.81167
  Classification -> best τ=0.550 (val F1=0.3264)
  Directional -> Accuracy: 0.4762, MCC: -0.0231, F1: 0.2667

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.65467 | val 0.71364
  Epoch 016 - train 0.61157 | val 0.74167
  Classification -> best τ=0.380 (val F1=0.2530)
  Directional -> Accuracy: 0.5179, MCC: 0.1149, F1: 0.6301

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.66345 | val 0.79737
  Epoch 016 - train 0.61121 | val 0.83271
  Classification -> best τ=0.380 (val F1=0.2800)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.72762 | val 0.66176
  Epoch 020 - train 0.63422 | val 0.64569
  Epoch 030 - train 0.59590 | val 0.61696
  Epoch 040 - train 0.55586 | val 0.59407
  Epoch 050 - train 0.53380 | val 0.62714
  Classification -> best τ=0.330 (val F1=0.6130)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.70564 | val 0.80758
  Epoch 016 - train 0.62231 | val 0.81030
  Classification -> best τ=0.510 (val F1=0.0585)
  Directional -> Accuracy: 0.4324, MCC: -0.1085, F1: 0.2222

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.63325 | val 0.72119
  Epoch 020 - train 0.63653 | val 1.25449
  Epoch 023 - train 0.58160 | val 1.17716
  Classification -> best τ=0.420 (val F1=0.3450)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.65122 | val 0.68821
  Epoch 018 - train 0.58434 | val 0.71076
  Classification -> best τ=0.425 (val F1=0.2933)
  Directional -> Accuracy: 0.5217, MCC: 0.0948, F1: 0.3125

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.63272 | val 0.62841
  Epoch 020 - train 0.60764 | val 0.75741
  Epoch 023 - train 0.55199 | val 0.69036
  Classification -> best τ=0.580 (val F1=0.5752)
  Directional -> Accuracy: 0.6047, MCC: 0.1763, F1: 0.7119

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.76126 | val 0.77693
  Epoch 020 - train 0.65558 | val 0.70731
  Epoch 021 - train 0.63909 | val 0.73246
  Classification -> best τ=0.545 (val F1=0.5081)
  Directional -> Accuracy: 0.3673, MCC: -0.1462, F1: 0.5231

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.69238 | val 0.89935
  Epoch 017 - train 0.65250 | val 0.80117
  Classification -> best τ=0.635 (val F1=0.1335)
  Directional -> Accuracy: 0.3929, MCC: -0.2038, F1: 0.2609

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.69641 | val 0.76402
  Epoch 018 - train 0.65985 | val 0.83783
  Classification -> best τ=0.555 (val F1=0.3723)
  Directional -> Accuracy: 0.5536, MCC: 0.1555, F1: 0.6479

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.64854 | val 1.08745
  Epoch 019 - train 0.61425 | val 1.97026
  Classification -> best τ=0.515 (val F1=0.2345)
  Directional -> Accuracy: 0.5000, MCC: 0.0331, F1: 0.2703

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.65179 | val 0.79462
  Epoch 019 - train 0.63108 | val 0.88042
  Classification -> best τ=0.525 (val F1=0.0827)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.67386 | val 0.69065
  Epoch 020 - train 0.65408 | val 0.87934
  Epoch 021 - train 0.64648 | val 0.76944

[I 2026-02-25 05:13:38,278] Trial 243 finished with value: 0.2707011759276831 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 64, 'learning_rate': 0.00739024002002555, 'weight_decay': 0.0005051974989672767, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 0.14761542033905195, 'early_stopping_min_delta': 0.002948308066428924}. Best is trial 200 with value: 0.303360648585588.

  Classification -> best τ=0.385 (val F1=0.2847)
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2707011759276831
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.66854 | val 0.69206
  Epoch 020 - train 0.59630 | val 0.69200
  Classification -> best τ=0.645 (val F1=0.2510)
  Directional -> Accuracy: 0.5658, MCC: 0.1283, F1: 0.0571

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.68241 | val 0.68161
  Epoch 017 - train 0.64584 | val 0.71192
  Classification -> best τ=0.430 (val F1=0.3294)
  Directional -> Accuracy: 0.6222, MCC: 0.2073, F1: 0.7463

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.68838 | val 0.72040
  Epoch 017 - train 0.66546 | val 0.73597
  Classification -> best τ=0.445 (val F1=0.3878)
  Directional -> Accuracy: 0.5957, MCC: 0.1864, F1: 0.6885

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.68088 | val 0.88023
  Epoch 020 - train 0.65562 | val 1.69598
  Classification -> best τ=0.500 (val F1=0.1946)
  Directional -> Accuracy: 0.4933, MCC: 0.0536, F1: 0.3214

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.65957 | val 0.67557
  Epoch 020 - train 0.59396 | val 1.21036
  Epoch 021 - train 0.56137 | val 1.37179
  Classification -> best τ=0.650 (val F1=0.4195)
  Directional -> Accuracy: 0.5098, MCC: 0.0826, F1: 0.2857

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.64407 | val 0.70847
  Epoch 019 - train 0.59188 | val 0.70881
  Classification -> best τ=0.460 (val F1=0.2582)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.71694 | val 0.71348
  Epoch 017 - train 0.64326 | val 0.92734
  Classification -> best τ=0.440 (val F1=0.3411)
  Directional -> Accuracy: 0.5217, MCC: 0.1376, F1: 0.5714

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.71765 | val 0.63990
  Epoch 020 - train 0.53736 | val 0.87173
  Epoch 021 - train 0.50297 | val 1.01668
  Classification -> best τ=0.345 (val F1=0.3639)
  Directional -> Accuracy: 0.5581, MCC: -0.1309, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.66774 | val 0.68527
  Epoch 020 - train 0.61587 | val 0.74917
  Epoch 022 - train 0.52999 | val 0.87144
  Classification -> best τ=0.550 (val F1=0.2788)
  Directional -> Accuracy: 0.7143, MCC: 0.4191, F1: 0.6667

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.67288 | val 0.70069
  Epoch 020 - train 0.55683 | val 0.72987
  Epoch 026 - train 0.55846 | val 3.63622
  Classification -> best τ=0.515 (val F1=0.1445)
  Directional -> Accuracy: 0.5000, MCC: 0.0430, F1: 0.5333

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.63701 | val 0.84889
  Epoch 018 - train 0.57871 | val 1.10913
  Classification -> best τ=0.470 (val F1=0.3118)
  Directional -> Accuracy: 0.5800, MCC: 0.1716, F1: 0.2222

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.62632 | val 0.76256
  Epoch 019 - train 0.59532 | val 1.05899
  Classification -> best τ=0.635 (val F1=0.3062)
  Directional -> Accuracy: 0.5862, MCC: 0.2381, F1: 0.3684

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.66052 | val 0.72756
  Epoch 018 - train 0.62586 | val 0.84038
  Classification -> best τ=0.590 (val F1=0.2392)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.67283 | val 0.60951
  Epoch 020 - train 0.64141 | val 0.98942
  Epoch 030 - train 0.53695 | val 1.45378
  Classification -> best τ=0.235 (val F1=0.3669)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.64558 | val 0.70456
  Epoch 016 - train 0.62348 | val 0.82796
  Classification -> best τ=0.410 (val F1=0.1296)
  Directional -> Accuracy: 0.5769, MCC: 0.2560, F1: 0.6667

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.67179 | val 0.74663
  Epoch 019 - train 0.62802 | val 0.80821
  Classification -> best τ=0.425 (val F1=0.3397)
  Directional -> Accuracy: 0.5942, MCC: 0.2079, F1: 0.7143

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.64744 | val 0.96323
  Epoch 016 - train 0.63409 | val 0.98198
  Classification -> best τ=0.485 (val F1=0.2276)
  Directional -> Accuracy: 0.4915, MCC: 0.1891, F1: 0.3750

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.67386 | val 1.11124
  Epoch 016 - train 0.63802 | val 1.20313
  Classification -> best τ=0.475 (val F1=0.1534)
  Directional -> Accuracy: 0.5067, MCC: 0.1816, F1: 0.3729

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.65667 | val 0.81142
  Epoch 019 - train 0.63450 | val 2.65936
  Classification -> best τ=0.470 (val F1=0.2725)
  Directional -> Accuracy: 0.4769, MCC: 0.0998, F1: 0.2917

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.67889 | val 0.69670
  Epoch 020 - train 0.65275 | val 0.73074
  Epoch 023 - train 0.62374 | val 0.71461
  Classification -> best τ=0.440 (val F1=0.2219)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.68187 | val 0.72124
  Epoch 020 - train 0.63469 | val 0.83753
  Epoch 022 - train 0.61975 | val 0.97895
  Classification -> best τ=0.420 (val F1=0.3278)
  Directional -> Accuracy: 0.4043, MCC: -0.1919, F1: 0.4615

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.68603 | val 0.75144
  Epoch 020 - train 0.65751 | val 0.87681
  Classification -> best τ=0.510 (val F1=0.2931)
  Directional -> Accuracy: 0.6061, MCC: 0.2226, F1: 0.6579

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.65086 | val 0.71151
  Epoch 017 - train 0.63115 | val 0.77045
  Classification -> best τ=0.655 (val F1=0.3342)
  Directional -> Accuracy: 0.5172, MCC: 0.0882, F1: 0.4615

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.67067 | val 0.71889
  Epoch 018 - train 0.62179 | val 0.95959
  Classification -> best τ=0.465 (val F1=0.1507)
  Directional -> Accuracy: 0.5231, MCC: 0.0428, F1: 0.4918

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.61838 | val 0.66094
  Epoch 020 - train 0.55296 | val 0.83717
  Epoch 023 - train 0.52432 | val 0.89008
  Classification -> best τ=0.435 (val F1=0.4082)
  Directional -> Accuracy: 0.5893, MCC: 0.2075, F1: 0.5660

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.71082 | val 0.72381
  Epoch 019 - train 0.53633 | val 0.73122
  Classification -> best τ=0.515 (val F1=0.2935)
  Directional -> Accuracy: 0.5000, MCC: 0.1274, F1: 0.6102

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.68995 | val 0.69117
  Epoch 020 - train 0.61806 | val 0.68272
  Epoch 030 - train 0.59411 | val 0.71084
  Epoch 038 - train 0.50884 | val 0.71576
  Classification -> best τ=0.670 (val F1=0.2810)
  Directional -> Accuracy: 0.4762, MCC: 0.1171, F1: 0.2143

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.64764 | val 0.72982
  Epoch 018 - train 0.60831 | val 0.83035
  Classification -> best τ=0.325 (val F1=0.2575)
  Directional -> Accuracy: 0.5263, MCC: 0.2230, F1: 0.3077

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.75885 | val 0.72205
  Epoch 020 - train 0.57549 | val 0.70622
  Epoch 023 - train 0.57207 | val 0.74681
  Classification -> best τ=0.555 (val F1=0.3380)
  Directional -> Accuracy: 0.4390, MCC: -0.0983, F1: 0.2069

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.65833 | val 0.75089
  Epoch 017 - train 0.66025 | val 0.93498
  Classification -> best τ=0.600 (val F1=0.2814)
  Directional -> Accuracy: 0.5349, MCC: 0.0716, F1: 0.5455

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.69940 | val 0.71121
  Epoch 020 - train 0.59579 | val 0.74491
  Epoch 030 - train 0.46427 | val 0.69823
  Epoch 040 - train 0.41449 | val 1.15764
  Epoch 042 - train 0.39992 | val 0.82635
  Classification -> best τ=0.570 (val F1=0.2976)
  Directional -> Accuracy: 0.5116, MCC: 0.0217, F1: 0.5333

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.60387 | val 0.73682
  Epoch 019 - train 0.53617 | val 0.82663
  Classification -> best τ=0.580 (val F1=0.2566)
  Directional -> Accuracy: 0.4400, MCC: -0.1996, F1: 0.5758

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.64823 | val 0.67156
  Epoch 020 - train 0.67572 | val 0.73184
  Epoch 029 - train 0.60060 | val 0.77916
  Classification -> best τ=0.385 (val F1=0.3223)
  Directional -> Accuracy: 0.5205, MCC: 0.0894, F1: 0.4615

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.77199 | val 0.73752
  Epoch 019 - train 0.52083 | val 1.03523
  Classification -> best τ=0.545 (val F1=0.1992)
  Directional -> Accuracy: 0.4865, MCC: -0.0211, F1: 0.5366

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.71571 | val 0.78447
  Epoch 020 - train 0.60577 | val 1.02399
  Epoch 022 - train 0.64860 | val 1.08429
  Classification -> best τ=0.555 (val F1=0.2031)
  Directional -> Accuracy: 0.5000, MCC: -0.1457, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.68086 | val 0.68657
  Epoch 020 - train 0.64584 | val 0.73364
  Classification -> best τ=0.405 (val F1=0.3280)
  Directional -> Accuracy: 0.5000, MCC: 0.1624, F1: 0.2979

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.60944 | val 0.81581
  Epoch 016 - train 0.55801 | val 0.87570
  Classification -> best τ=0.575 (val F1=0.2652)
  Directional -> Accuracy: 0.5476, MCC: 0.1706, F1: 0.3448

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.66359 | val 0.71241
  Epoch 020 - train 0.59203 | val 0.96695
  Epoch 021 - train 0.59650 | val 0.95197
  Classification -> best τ=0.485 (val F1=0.2742)
  Directional -> Accuracy: 0.5357, MCC: 0.0620, F1: 0.4800

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.63160 | val 0.70353
  Epoch 018 - train 0.61267 | val 0.83848
  Classification -> best τ=0.395 (val F1=0.3105)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.64260 | val 0.69167
  Epoch 020 - train 0.59072 | val 0.63433
  Epoch 022 - train 0.57520 | val 0.63914
  Classification -> best τ=0.440 (val F1=0.4795)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.83405 | val 0.99894
  Epoch 016 - train 0.78329 | val 1.08518
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.66127 | val 0.67363
  Epoch 020 - train 0.56552 | val 1.10126
  Epoch 023 - train 0.60766 | val 1.41355
  Classification -> best τ=0.270 (val F1=0.3844)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.66280 | val 0.68085
  Epoch 020 - train 0.62889 | val 0.72395
  Epoch 028 - train 0.55864 | val 0.89964
  Classification -> best τ=0.480 (val F1=0.2933)
  Directional -> Accuracy: 0.4783, MCC: -0.0259, F1: 0.3333

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.64124 | val 0.64419
  Epoch 020 - train 0.49045 | val 0.78370
  Epoch 025 - train 0.50393 | val 0.68639
  Classification -> best τ=0.565 (val F1=0.3651)
  Directional -> Accuracy: 0.4651, MCC: 0.0306, F1: 0.2069

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.69194 | val 0.70335
  Epoch 017 - train 0.60996 | val 0.71486
  Classification -> best τ=0.495 (val F1=0.3638)
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.70945 | val 0.85338
  Epoch 016 - train 0.61928 | val 1.46720
  Classification -> best τ=0.595 (val F1=0.2727)
  Directional -> Accuracy: 0.5536, MCC: 0.1726, F1: 0.4186

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.70455 | val 0.78075
  Epoch 017 - train 0.65852 | val 1.25090
  Classification -> best τ=0.470 (val F1=0.2230)
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.66466 | val 0.94144
  Epoch 018 - train 0.60436 | val 1.63402
  Classification -> best τ=0.435 (val F1=0.1115)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.67222 | val 0.76988
  Epoch 016 - train 0.64998 | val 0.80381
  Classification -> best τ=0.390 (val F1=0.1168)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.67453 | val 0.85844

[I 2026-02-25 05:15:45,571] Trial 244 finished with value: 0.274128497403141 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 64, 'learning_rate': 0.009614052711813183, 'weight_decay': 1.080914760302185e-06, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 0.1807405101871133, 'early_stopping_min_delta': 0.0026897196471606867}. Best is trial 200 with value: 0.303360648585588.

  Epoch 017 - train 0.62120 | val 0.96216
  Classification -> best τ=0.425 (val F1=0.1367)
  Directional -> Accuracy: 0.4590, MCC: -0.0871, F1: 0.6207

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.274128497403141
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.64323 | val 0.67652
  Epoch 017 - train 0.60497 | val 0.68329
  Classification -> best τ=0.515 (val F1=0.2627)
  Directional -> Accuracy: 0.5395, MCC: -0.0120, F1: 0.1463

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.65085 | val 0.68105
  Epoch 020 - train 0.56151 | val 0.73274
  Epoch 025 - train 0.57153 | val 0.72921
  Classification -> best τ=0.465 (val F1=0.1812)
  Directional -> Accuracy: 0.6222, MCC: 0.1967, F1: 0.7119

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.62606 | val 0.74185
  Epoch 018 - train 0.67120 | val 0.87860
  Classification -> best τ=0.425 (val F1=0.4078)
  Directional -> Accuracy: 0.5106, MCC: -0.1383, F1: 0.6761

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.66733 | val 0.74412
  Epoch 017 - train 0.63598 | val 0.81336
  Classification -> best τ=0.505 (val F1=0.0852)
  Directional -> Accuracy: 0.5067, MCC: 0.0573, F1: 0.4127

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.67258 | val 0.64135
  Epoch 020 - train 0.54353 | val 0.76028
  Epoch 025 - train 0.56966 | val 0.68931
  Classification -> best τ=0.565 (val F1=0.4513)
  Directional -> Accuracy: 0.4902, MCC: -0.0094, F1: 0.4583

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.67326 | val 0.73509
  Epoch 016 - train 0.62919 | val 0.69682
  Classification -> best τ=0.500 (val F1=0.3394)
  Directional -> Accuracy: 0.6170, MCC: 0.2375, F1: 0.5500

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.68712 | val 0.72190
  Epoch 020 - train 0.66090 | val 0.70667
  Epoch 021 - train 0.65752 | val 0.67904
  Classification -> best τ=0.485 (val F1=0.1840)
  Directional -> Accuracy: 0.5507, MCC: 0.0950, F1: 0.4918

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.68521 | val 0.75854
  Epoch 020 - train 0.56578 | val 0.84786
  Classification -> best τ=0.295 (val F1=0.2962)
  Directional -> Accuracy: 0.5349, MCC: -0.0423, F1: 0.2308

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.68060 | val 0.70208
  Epoch 020 - train 0.57801 | val 0.89884
  Classification -> best τ=0.470 (val F1=0.1978)
  Directional -> Accuracy: 0.5714, MCC: 0.2278, F1: 0.6441

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.64371 | val 0.82457
  Epoch 016 - train 0.60789 | val 0.76639
  Classification -> best τ=0.580 (val F1=0.1998)
  Directional -> Accuracy: 0.5286, MCC: -0.1833, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.65584 | val 0.79326
  Epoch 020 - train 0.60545 | val 1.26076
  Epoch 021 - train 0.55850 | val 1.13543
  Classification -> best τ=0.465 (val F1=0.3612)
  Directional -> Accuracy: 0.6000, MCC: 0.2274, F1: 0.2857

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.64368 | val 0.84440
  Epoch 016 - train 0.56877 | val 0.96540
  Classification -> best τ=0.445 (val F1=0.2097)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.68683 | val 0.74538
  Epoch 019 - train 0.57770 | val 0.85800
  Classification -> best τ=0.480 (val F1=0.2323)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.66328 | val 0.61792
  Epoch 020 - train 0.61528 | val 0.70967
  Epoch 025 - train 0.58783 | val 1.26286
  Classification -> best τ=0.445 (val F1=0.3916)
  Directional -> Accuracy: 0.6000, MCC: 0.2182, F1: 0.6667

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.65974 | val 0.90816
  Epoch 020 - train 0.59247 | val 0.85339
  Epoch 022 - train 0.57352 | val 0.83495
  Classification -> best τ=0.520 (val F1=0.2160)
  Directional -> Accuracy: 0.5192, MCC: -0.0261, F1: 0.1935

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.65850 | val 0.70816
  Epoch 017 - train 0.61922 | val 0.73334
  Classification -> best τ=0.450 (val F1=0.4264)
  Directional -> Accuracy: 0.5652, MCC: 0.1256, F1: 0.7000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.67363 | val 0.77622
  Epoch 020 - train 0.63597 | val 1.31465
  Classification -> best τ=0.690 (val F1=0.1303)
  Directional -> Accuracy: 0.3390, MCC: -0.2429, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.65624 | val 0.77294
  Epoch 019 - train 0.65615 | val 1.19983
  Classification -> best τ=0.610 (val F1=0.2397)
  Directional -> Accuracy: 0.3867, MCC: -0.1424, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.65466 | val 0.97617
  Epoch 018 - train 0.63335 | val 1.66019
  Classification -> best τ=0.450 (val F1=0.2305)
  Directional -> Accuracy: 0.4923, MCC: 0.1307, F1: 0.3265

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.67445 | val 0.66908
  Epoch 020 - train 0.65022 | val 0.66147
  Epoch 030 - train 0.60846 | val 0.74559
  Epoch 037 - train 0.60402 | val 0.75171
  Classification -> best τ=0.495 (val F1=0.3269)
  Directional -> Accuracy: 0.4667, MCC: 0.1059, F1: 0.0476

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.66379 | val 0.80186
  Epoch 020 - train 0.56139 | val 0.90311
  Epoch 024 - train 0.58532 | val 0.91646
  Classification -> best τ=0.445 (val F1=0.3278)
  Directional -> Accuracy: 0.5106, MCC: 0.0373, F1: 0.5490

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.64604 | val 0.75751
  Epoch 016 - train 0.65376 | val 0.93375
  Classification -> best τ=0.525 (val F1=0.1878)
  Directional -> Accuracy: 0.5606, MCC: 0.1361, F1: 0.4314

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.65643 | val 0.70998
  Epoch 020 - train 0.67316 | val 0.73473
  Classification -> best τ=0.490 (val F1=0.2760)
  Directional -> Accuracy: 0.5345, MCC: 0.0555, F1: 0.5846

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.68995 | val 0.69678
  Epoch 020 - train 0.61988 | val 0.72605
  Epoch 021 - train 0.64518 | val 0.72375
  Classification -> best τ=0.420 (val F1=0.2365)
  Directional -> Accuracy: 0.4769, MCC: 0.0000, F1: 0.6458

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.64567 | val 0.65198
  Epoch 020 - train 0.64183 | val 0.75136
  Epoch 025 - train 0.57945 | val 0.78790
  Classification -> best τ=0.455 (val F1=0.3299)
  Directional -> Accuracy: 0.5357, MCC: 0.0926, F1: 0.5185

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.63032 | val 0.70973
  Epoch 020 - train 0.62326 | val 0.86693
  Epoch 021 - train 0.61762 | val 0.87089
  Classification -> best τ=0.600 (val F1=0.3407)
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.69880 | val 0.70314
  Epoch 016 - train 0.64988 | val 0.74313
  Classification -> best τ=0.570 (val F1=0.0142)
  Directional -> Accuracy: 0.4762, MCC: -0.0278, F1: 0.4762

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.63733 | val 0.71704
  Epoch 017 - train 0.61213 | val 0.82946
  Classification -> best τ=0.360 (val F1=0.2294)
  Directional -> Accuracy: 0.5965, MCC: 0.2353, F1: 0.5660

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.64767 | val 0.71874
  Epoch 020 - train 0.65980 | val 0.70436
  Epoch 030 - train 0.57000 | val 0.64268
  Epoch 039 - train 0.48899 | val 2.96061
  Classification -> best τ=0.490 (val F1=0.3518)
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.66715 | val 0.73565
  Epoch 020 - train 0.63870 | val 1.11969
  Classification -> best τ=0.700 (val F1=0.2814)
  Directional -> Accuracy: 0.4884, MCC: -0.0318, F1: 0.3889

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.65640 | val 0.62039
  Epoch 020 - train 0.63827 | val 0.89668
  Epoch 025 - train 0.58147 | val 0.80229
  Classification -> best τ=0.620 (val F1=0.3329)
  Directional -> Accuracy: 0.6512, MCC: 0.3015, F1: 0.6667

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.67321 | val 0.83931
  Epoch 016 - train 0.62053 | val 0.78496
  Classification -> best τ=0.480 (val F1=0.2837)
  Directional -> Accuracy: 0.5600, MCC: 0.1042, F1: 0.6207

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.66586 | val 0.65746
  Epoch 020 - train 0.63010 | val 0.98476
  Epoch 028 - train 0.65016 | val 0.95117
  Classification -> best τ=0.270 (val F1=0.3313)
  Directional -> Accuracy: 0.5616, MCC: 0.1446, F1: 0.5556

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.68161 | val 0.69109
  Epoch 016 - train 0.71078 | val 0.70965
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.72372 | val 0.75403
  Epoch 018 - train 0.62482 | val 0.78169
  Classification -> best τ=0.570 (val F1=0.2903)
  Directional -> Accuracy: 0.5455, MCC: 0.0807, F1: 0.4444

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.67047 | val 0.69508
  Epoch 020 - train 0.65521 | val 0.71851
  Epoch 023 - train 0.64385 | val 0.75407
  Classification -> best τ=0.295 (val F1=0.3525)
  Directional -> Accuracy: 0.5909, MCC: 0.1750, F1: 0.6301

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.69257 | val 0.71880
  Epoch 019 - train 0.52171 | val 0.84071
  Classification -> best τ=0.505 (val F1=0.3105)
  Directional -> Accuracy: 0.6429, MCC: 0.3290, F1: 0.5714

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.65853 | val 0.68831
  Epoch 017 - train 0.62150 | val 0.73041
  Classification -> best τ=0.580 (val F1=0.2305)
  Directional -> Accuracy: 0.5893, MCC: 0.1646, F1: 0.4390

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.66096 | val 0.67891
  Epoch 017 - train 0.61747 | val 0.90105
  Classification -> best τ=0.435 (val F1=0.3105)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.68792 | val 0.65453
  Epoch 020 - train 0.59673 | val 0.67411
  Epoch 023 - train 0.60869 | val 0.70633
  Classification -> best τ=0.385 (val F1=0.4188)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.69309 | val 0.77403
  Epoch 018 - train 0.60484 | val 0.91073
  Classification -> best τ=0.480 (val F1=0.2623)
  Directional -> Accuracy: 0.4324, MCC: -0.1167, F1: 0.3636

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.64328 | val 0.68923
  Epoch 017 - train 0.63995 | val 1.09536
  Classification -> best τ=0.400 (val F1=0.3087)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.61835 | val 0.68478
  Epoch 017 - train 0.63468 | val 0.75500
  Classification -> best τ=0.490 (val F1=0.3560)
  Directional -> Accuracy: 0.5000, MCC: 0.1427, F1: 0.0800

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.67256 | val 0.65569
  Epoch 020 - train 0.63619 | val 0.62766
  Epoch 030 - train 0.56860 | val 0.90491
  Epoch 037 - train 0.47772 | val 0.75268
  Classification -> best τ=0.545 (val F1=0.5752)
  Directional -> Accuracy: 0.6279, MCC: 0.2616, F1: 0.7419

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.73557 | val 0.67041
  Epoch 020 - train 0.61935 | val 0.72500
  Epoch 024 - train 0.62688 | val 0.62490
  Classification -> best τ=0.505 (val F1=0.5514)
  Directional -> Accuracy: 0.5714, MCC: 0.1610, F1: 0.5333

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.68252 | val 0.89275
  Epoch 017 - train 0.62366 | val 1.20650
  Classification -> best τ=0.490 (val F1=0.2641)
  Directional -> Accuracy: 0.5179, MCC: 0.0998, F1: 0.3415

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.68700 | val 0.90619
  Epoch 017 - train 0.61183 | val 1.29017
  Classification -> best τ=0.650 (val F1=0.2729)
  Directional -> Accuracy: 0.5357, MCC: 0.1768, F1: 0.6667

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.64932 | val 1.05917
  Epoch 020 - train 0.64862 | val 2.35269
  Epoch 021 - train 0.62428 | val 1.92455
  Classification -> best τ=0.510 (val F1=0.2024)
  Directional -> Accuracy: 0.5741, MCC: 0.1509, F1: 0.6667

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.67189 | val 0.78671
  Epoch 018 - train 0.64722 | val 0.93031
  Classification -> best τ=0.405 (val F1=0.1415)
  Directional -> Accuracy: 0.4464, MCC: -0.1995, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.68708 | val 0.74004

[I 2026-02-25 05:17:50,997] Trial 245 finished with value: 0.27781486623399193 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 64, 'learning_rate': 0.00617978024847245, 'weight_decay': 0.00032916091557214636, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 0.10327790130770569, 'early_stopping_min_delta': 0.002323304712240744}. Best is trial 200 with value: 0.303360648585588.

  Epoch 017 - train 0.64879 | val 0.87324
  Classification -> best τ=0.490 (val F1=0.1498)
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.27781486623399193
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.64195 | val 0.66219
  Epoch 020 - train 0.62226 | val 0.65482
  Epoch 029 - train 0.62036 | val 0.86945
  Classification -> best τ=0.575 (val F1=0.2919)
  Directional -> Accuracy: 0.5395, MCC: -0.0253, F1: 0.1026

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.70399 | val 0.67862
  Epoch 020 - train 0.59975 | val 0.74483
  Classification -> best τ=0.465 (val F1=0.2539)
  Directional -> Accuracy: 0.6000, MCC: 0.1764, F1: 0.7429

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.64412 | val 0.69334
  Epoch 019 - train 0.65615 | val 1.00263
  Classification -> best τ=0.455 (val F1=0.2295)
  Directional -> Accuracy: 0.6170, MCC: 0.2281, F1: 0.6897

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.67765 | val 0.70864
  Epoch 017 - train 0.65736 | val 0.73409
  Classification -> best τ=0.500 (val F1=0.0642)
  Directional -> Accuracy: 0.5200, MCC: 0.0573, F1: 0.5000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.63421 | val 0.65357
  Epoch 020 - train 0.61906 | val 0.69938
  Epoch 030 - train 0.57566 | val 0.65076
  Epoch 032 - train 0.52341 | val 0.66878
  Classification -> best τ=0.600 (val F1=0.3244)
  Directional -> Accuracy: 0.4706, MCC: -0.1787, F1: 0.6301

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.67163 | val 0.70277
  Epoch 016 - train 0.64905 | val 0.70596
  Classification -> best τ=0.575 (val F1=0.2037)
  Directional -> Accuracy: 0.5532, MCC: 0.1357, F1: 0.2759

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.68129 | val 0.68427
  Epoch 020 - train 0.67265 | val 0.76878
  Epoch 029 - train 0.66516 | val 0.72899
  Classification -> best τ=0.500 (val F1=0.2542)
  Directional -> Accuracy: 0.5797, MCC: 0.1335, F1: 0.4912

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.71910 | val 0.67757
  Epoch 020 - train 0.58310 | val 0.66280
  Epoch 027 - train 0.53679 | val 0.66016
  Classification -> best τ=0.350 (val F1=0.4756)
  Directional -> Accuracy: 0.5581, MCC: 0.0713, F1: 0.4242

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.64916 | val 0.73876
  Epoch 020 - train 0.55605 | val 1.03415
  Epoch 023 - train 0.54449 | val 1.09699
  Classification -> best τ=0.290 (val F1=0.2408)
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.65642 | val 0.69687
  Epoch 020 - train 0.63297 | val 0.69416
  Epoch 030 - train 0.56780 | val 1.07795
  Epoch 039 - train 0.54530 | val 0.84883
  Classification -> best τ=0.350 (val F1=0.3804)
  Directional -> Accuracy: 0.4429, MCC: -0.0123, F1: 0.5714

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.65639 | val 0.77004
  Epoch 017 - train 0.62613 | val 0.95554
  Classification -> best τ=0.560 (val F1=0.1750)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.65372 | val 0.79528
  Epoch 018 - train 0.61548 | val 1.35468
  Classification -> best τ=0.525 (val F1=0.3029)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.61085 | val 0.75952
  Epoch 017 - train 0.57069 | val 1.02007
  Classification -> best τ=0.475 (val F1=0.3002)
  Directional -> Accuracy: 0.4524, MCC: -0.0214, F1: 0.6102

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.69438 | val 0.62228
  Epoch 020 - train 0.64779 | val 0.87704
  Epoch 025 - train 0.64026 | val 0.74074
  Classification -> best τ=0.430 (val F1=0.3407)
  Directional -> Accuracy: 0.5500, MCC: 0.1292, F1: 0.6582

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.66356 | val 0.76213
  Epoch 019 - train 0.58406 | val 0.79777
  Classification -> best τ=0.520 (val F1=0.2673)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.64519 | val 0.73336
  Epoch 020 - train 0.63689 | val 0.74652
  Epoch 023 - train 0.61326 | val 0.70922
  Classification -> best τ=0.490 (val F1=0.2434)
  Directional -> Accuracy: 0.5652, MCC: 0.1442, F1: 0.5455

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.67522 | val 0.81635
  Epoch 016 - train 0.65674 | val 0.95957
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.66928 | val 0.86121
  Epoch 016 - train 0.66772 | val 0.95377
  Classification -> best τ=0.490 (val F1=0.1536)
  Directional -> Accuracy: 0.4133, MCC: -0.0680, F1: 0.2667

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.67814 | val 1.01172
  Epoch 016 - train 0.59780 | val 1.45525
  Classification -> best τ=0.470 (val F1=0.2944)
  Directional -> Accuracy: 0.4462, MCC: -0.1066, F1: 0.4857

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.65985 | val 0.66891
  Epoch 020 - train 0.62394 | val 0.73756
  Epoch 030 - train 0.61820 | val 0.79467
  Epoch 033 - train 0.58292 | val 0.68907
  Classification -> best τ=0.440 (val F1=0.3492)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.70699 | val 0.68170
  Epoch 020 - train 0.61328 | val 1.05623
  Epoch 022 - train 0.60504 | val 1.02048
  Classification -> best τ=0.430 (val F1=0.3278)
  Directional -> Accuracy: 0.5106, MCC: -0.0037, F1: 0.5818

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.69006 | val 0.75390
  Epoch 016 - train 0.66185 | val 0.84185
  Classification -> best τ=0.505 (val F1=0.1431)
  Directional -> Accuracy: 0.3939, MCC: -0.2342, F1: 0.5000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.70382 | val 0.72235
  Epoch 019 - train 0.65363 | val 0.73132
  Classification -> best τ=0.430 (val F1=0.2962)
  Directional -> Accuracy: 0.5172, MCC: 0.0650, F1: 0.5000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.65843 | val 0.70937
  Epoch 020 - train 0.63134 | val 1.04912
  Epoch 022 - train 0.61701 | val 0.96010
  Classification -> best τ=0.420 (val F1=0.1584)
  Directional -> Accuracy: 0.5385, MCC: 0.1368, F1: 0.6429

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.63552 | val 0.63839
  Epoch 020 - train 0.63078 | val 0.76767
  Epoch 026 - train 0.56527 | val 0.86570
  Classification -> best τ=0.425 (val F1=0.4436)
  Directional -> Accuracy: 0.5179, MCC: 0.1188, F1: 0.3721

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.71448 | val 0.73161
  Epoch 017 - train 0.56779 | val 1.06167
  Classification -> best τ=0.525 (val F1=0.2935)
  Directional -> Accuracy: 0.4565, MCC: -0.0877, F1: 0.4186

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.67354 | val 0.70802
  Epoch 016 - train 0.65768 | val 0.72546
  Classification -> best τ=0.610 (val F1=0.1936)
  Directional -> Accuracy: 0.5952, MCC: 0.1578, F1: 0.6667

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.64417 | val 0.68306
  Epoch 017 - train 0.59437 | val 0.81269
  Classification -> best τ=0.330 (val F1=0.2550)
  Directional -> Accuracy: 0.5439, MCC: 0.2218, F1: 0.3810

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.70999 | val 0.73174
  Epoch 020 - train 0.59446 | val 0.64747
  Epoch 030 - train 0.52699 | val 1.73558
  Epoch 038 - train 0.43951 | val 2.11543
  Classification -> best τ=0.615 (val F1=0.4063)
  Directional -> Accuracy: 0.5366, MCC: 0.0528, F1: 0.6122

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.65858 | val 0.97494
  Epoch 019 - train 0.61255 | val 1.17572
  Classification -> best τ=0.490 (val F1=0.3490)
  Directional -> Accuracy: 0.5116, MCC: 0.0288, F1: 0.5532

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.66794 | val 0.64957
  Epoch 020 - train 0.64673 | val 0.63607
  Epoch 030 - train 0.53810 | val 0.72933
  Epoch 040 - train 0.43749 | val 0.69210
  Epoch 048 - train 0.47097 | val 0.66354
  Classification -> best τ=0.640 (val F1=0.3612)
  Directional -> Accuracy: 0.5349, MCC: 0.1062, F1: 0.4444

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.62799 | val 0.70057
  Epoch 020 - train 0.63040 | val 0.95271
  Epoch 030 - train 0.52726 | val 0.99953
  Epoch 031 - train 0.55241 | val 0.79195
  Classification -> best τ=0.295 (val F1=0.2976)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.65085 | val 0.66404
  Epoch 020 - train 0.64459 | val 0.74800
  Epoch 030 - train 0.61565 | val 0.83317
  Epoch 031 - train 0.61081 | val 0.78644
  Classification -> best τ=0.260 (val F1=0.3520)
  Directional -> Accuracy: 0.5479, MCC: 0.1207, F1: 0.5352

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.70777 | val 0.87844
  Epoch 016 - train 0.66019 | val 0.83232
  Classification -> best τ=0.445 (val F1=0.4951)
  Directional -> Accuracy: 0.5135, MCC: 0.0367, F1: 0.5714

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.67843 | val 0.85111
  Epoch 016 - train 0.63329 | val 0.99651
  Classification -> best τ=0.450 (val F1=0.2757)
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.65112 | val 0.72123
  Epoch 018 - train 0.66656 | val 0.72065
  Classification -> best τ=0.530 (val F1=0.2566)
  Directional -> Accuracy: 0.4242, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.65286 | val 0.69771
  Epoch 016 - train 0.64340 | val 0.69124
  Classification -> best τ=0.505 (val F1=0.2986)
  Directional -> Accuracy: 0.7143, MCC: 0.4404, F1: 0.7000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.67895 | val 0.78239
  Epoch 018 - train 0.64665 | val 0.83006
  Classification -> best τ=0.375 (val F1=0.2916)
  Directional -> Accuracy: 0.4821, MCC: -0.0083, F1: 0.5538

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.67346 | val 0.83552
  Epoch 016 - train 0.63070 | val 0.69608
  Classification -> best τ=0.460 (val F1=0.3105)
  Directional -> Accuracy: 0.5217, MCC: 0.0742, F1: 0.5417

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.72088 | val 0.69033
  Epoch 020 - train 0.61301 | val 0.65527
  Epoch 030 - train 0.64646 | val 0.64017
  Epoch 040 - train 0.59808 | val 0.61423
  Epoch 050 - train 0.55363 | val 0.62693
  Classification -> best τ=0.355 (val F1=0.5617)
  Directional -> Accuracy: 0.3469, MCC: -0.1894, F1: 0.5152

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.63947 | val 0.74801
  Epoch 019 - train 0.58447 | val 0.92929
  Classification -> best τ=0.425 (val F1=0.4776)
  Directional -> Accuracy: 0.5405, MCC: 0.0792, F1: 0.5641

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.66481 | val 0.70354
  Epoch 020 - train 0.63242 | val 0.71528
  Epoch 022 - train 0.60138 | val 0.81060
  Classification -> best τ=0.385 (val F1=0.3259)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.62124 | val 0.70174
  Epoch 020 - train 0.62944 | val 0.69353
  Epoch 022 - train 0.62176 | val 0.71231
  Classification -> best τ=0.415 (val F1=0.2087)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.6857

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.72681 | val 0.71782
  Epoch 020 - train 0.63845 | val 0.72317
  Epoch 022 - train 0.59823 | val 0.71765
  Classification -> best τ=0.595 (val F1=0.6031)
  Directional -> Accuracy: 0.4884, MCC: -0.0924, F1: 0.6071

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.69741 | val 0.69284
  Epoch 020 - train 0.63469 | val 0.69959
  Classification -> best τ=0.580 (val F1=0.6292)
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.68804 | val 0.85411
  Epoch 017 - train 0.60081 | val 1.13723
  Classification -> best τ=0.575 (val F1=0.1914)
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.66778 | val 0.91982
  Epoch 016 - train 0.63624 | val 1.10429
  Classification -> best τ=0.535 (val F1=0.3723)
  Directional -> Accuracy: 0.5714, MCC: 0.1801, F1: 0.6471

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.65121 | val 1.46830
  Epoch 018 - train 0.62466 | val 2.11417
  Classification -> best τ=0.320 (val F1=0.2357)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.66647 | val 0.78936
  Epoch 020 - train 0.60953 | val 0.79484
  Epoch 022 - train 0.62105 | val 0.81244
  Classification -> best τ=0.695 (val F1=0.2182)
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.70185 | val 0.79738

[I 2026-02-25 05:20:07,812] Trial 246 finished with value: 0.29805655179697665 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 64, 'learning_rate': 0.006285428473803227, 'weight_decay': 0.0006088420761605675, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 0.20344503891101337, 'early_stopping_min_delta': 0.0030917724153951376}. Best is trial 200 with value: 0.303360648585588.

  Epoch 019 - train 0.64951 | val 0.82850
  Classification -> best τ=0.400 (val F1=0.1286)
  Directional -> Accuracy: 0.4098, MCC: -0.1926, F1: 0.3333

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.29805655179697665
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.64464 | val 0.66086
  Epoch 020 - train 0.64199 | val 0.65481
  Epoch 030 - train 0.62233 | val 0.71220
  Epoch 031 - train 0.61490 | val 0.67932
  Classification -> best τ=0.585 (val F1=0.2919)
  Directional -> Accuracy: 0.5263, MCC: -0.0267, F1: 0.2174

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.65703 | val 0.68971
  Epoch 019 - train 0.63739 | val 0.71386
  Classification -> best τ=0.380 (val F1=0.2861)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.67705 | val 0.68192
  Epoch 020 - train 0.65607 | val 0.79890
  Epoch 026 - train 0.63986 | val 0.88319
  Classification -> best τ=0.515 (val F1=0.4245)
  Directional -> Accuracy: 0.4894, MCC: 0.0231, F1: 0.2941

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.68403 | val 0.71698
  Epoch 020 - train 0.66285 | val 0.73820
  Epoch 024 - train 0.68406 | val 0.76024
  Classification -> best τ=0.400 (val F1=0.1210)
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.64811 | val 0.67238
  Epoch 017 - train 0.62940 | val 0.68323
  Classification -> best τ=0.565 (val F1=0.3808)
  Directional -> Accuracy: 0.6667, MCC: 0.3550, F1: 0.6383

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.76748 | val 0.79727
  Epoch 019 - train 0.65544 | val 0.73768
  Classification -> best τ=0.435 (val F1=0.2632)
  Directional -> Accuracy: 0.4894, MCC: -0.0509, F1: 0.2000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.69063 | val 0.69900
  Epoch 020 - train 0.67861 | val 0.69634
  Epoch 021 - train 0.63526 | val 0.71395
  Classification -> best τ=0.445 (val F1=0.2435)
  Directional -> Accuracy: 0.5507, MCC: 0.1697, F1: 0.5753

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.69769 | val 0.63546
  Epoch 018 - train 0.60301 | val 0.61846
  Classification -> best τ=0.295 (val F1=0.2588)
  Directional -> Accuracy: 0.4186, MCC: -0.2254, F1: 0.2424

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.69830 | val 0.74876
  Epoch 020 - train 0.56464 | val 0.74688
  Epoch 021 - train 0.57345 | val 0.79276
  Classification -> best τ=0.330 (val F1=0.2408)
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.65454 | val 0.69429
  Epoch 017 - train 0.64696 | val 0.70201
  Classification -> best τ=0.460 (val F1=0.2220)
  Directional -> Accuracy: 0.4143, MCC: -0.1018, F1: 0.5773

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.67261 | val 0.75417
  Epoch 018 - train 0.62947 | val 1.51364
  Classification -> best τ=0.545 (val F1=0.2500)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.63288 | val 0.74472
  Epoch 016 - train 0.64463 | val 0.92382
  Classification -> best τ=0.475 (val F1=0.2282)
  Directional -> Accuracy: 0.5690, MCC: 0.2265, F1: 0.6914

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.66750 | val 0.80834
  Epoch 016 - train 0.57789 | val 0.97973
  Classification -> best τ=0.425 (val F1=0.2731)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.67641 | val 0.61721
  Epoch 020 - train 0.67284 | val 0.63585
  Epoch 030 - train 0.61584 | val 0.59852
  Epoch 040 - train 0.59679 | val 0.66119
  Epoch 044 - train 0.57341 | val 0.81367
  Classification -> best τ=0.375 (val F1=0.3281)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.69481 | val 0.71176
  Epoch 018 - train 0.56751 | val 1.02609
  Classification -> best τ=0.515 (val F1=0.2673)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.65789 | val 0.62413
  Epoch 020 - train 0.62259 | val 0.73473
  Epoch 024 - train 0.62377 | val 0.74202
  Classification -> best τ=0.580 (val F1=0.3288)
  Directional -> Accuracy: 0.5072, MCC: 0.0874, F1: 0.2917

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.63512 | val 0.92815
  Epoch 017 - train 0.63779 | val 1.14017
  Classification -> best τ=0.510 (val F1=0.1342)
  Directional -> Accuracy: 0.3729, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.68126 | val 0.84178
  Epoch 016 - train 0.62655 | val 1.76410
  Classification -> best τ=0.460 (val F1=0.1039)
  Directional -> Accuracy: 0.4933, MCC: -0.0440, F1: 0.5682

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.68323 | val 0.85612
  Epoch 016 - train 0.61139 | val 1.41658
  Classification -> best τ=0.525 (val F1=0.2914)
  Directional -> Accuracy: 0.5538, MCC: -0.0133, F1: 0.6882

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.67724 | val 0.67989
  Epoch 020 - train 0.66000 | val 0.67750
  Epoch 028 - train 0.65964 | val 0.70125
  Classification -> best τ=0.500 (val F1=0.3499)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.69718 | val 0.68334
  Epoch 020 - train 0.60153 | val 0.70135
  Epoch 030 - train 0.55809 | val 1.67214
  Epoch 033 - train 0.52643 | val 1.38032
  Classification -> best τ=0.400 (val F1=0.3518)
  Directional -> Accuracy: 0.4894, MCC: 0.2066, F1: 0.3333

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.68383 | val 0.79410
  Epoch 016 - train 0.64400 | val 0.85737
  Classification -> best τ=0.695 (val F1=0.1318)
  Directional -> Accuracy: 0.5455, MCC: 0.1476, F1: 0.2500

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.65036 | val 0.70145
  Epoch 016 - train 0.64702 | val 0.77223
  Classification -> best τ=0.510 (val F1=0.3342)
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.68252 | val 0.71710
  Epoch 020 - train 0.66902 | val 0.70043
  Classification -> best τ=0.400 (val F1=0.1854)
  Directional -> Accuracy: 0.4769, MCC: 0.0000, F1: 0.6458

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.62210 | val 0.64792
  Epoch 020 - train 0.58982 | val 0.77444
  Epoch 030 - train 0.55603 | val 0.93299
  Epoch 031 - train 0.56123 | val 0.94951
  Classification -> best τ=0.530 (val F1=0.4149)
  Directional -> Accuracy: 0.4821, MCC: 0.0313, F1: 0.3256

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.70091 | val 0.75239
  Epoch 016 - train 0.67940 | val 0.71770
  Classification -> best τ=0.510 (val F1=0.1868)
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.71535 | val 0.69661
  Epoch 019 - train 0.65554 | val 0.71300
  Classification -> best τ=0.600 (val F1=0.0525)
  Directional -> Accuracy: 0.5000, MCC: 0.0138, F1: 0.5116

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.67176 | val 0.71139
  Epoch 016 - train 0.63525 | val 0.70387
  Classification -> best τ=0.390 (val F1=0.2946)
  Directional -> Accuracy: 0.5263, MCC: 0.2741, F1: 0.2703

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.68712 | val 0.75365
  Epoch 018 - train 0.70741 | val 0.80219
  Classification -> best τ=0.560 (val F1=0.3671)
  Directional -> Accuracy: 0.5366, MCC: 0.0649, F1: 0.5778

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.69895 | val 0.73377
  Epoch 017 - train 0.59305 | val 1.11818
  Classification -> best τ=0.425 (val F1=0.2221)
  Directional -> Accuracy: 0.4651, MCC: -0.0670, F1: 0.5660

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.69202 | val 0.67254
  Epoch 020 - train 0.59853 | val 0.75245
  Epoch 030 - train 0.61032 | val 0.67777
  Epoch 040 - train 0.46134 | val 0.64633
  Epoch 048 - train 0.39084 | val 0.79393
  Classification -> best τ=0.450 (val F1=0.3329)
  Directional -> Accuracy: 0.4884, MCC: 0.0323, F1: 0.2667

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.64543 | val 0.72230
  Epoch 016 - train 0.60800 | val 0.77978
  Classification -> best τ=0.625 (val F1=0.3917)
  Directional -> Accuracy: 0.3800, MCC: -0.3195, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.65896 | val 0.65257
  Epoch 020 - train 0.62232 | val 0.65164
  Epoch 027 - train 0.62295 | val 0.82096
  Classification -> best τ=0.295 (val F1=0.3809)
  Directional -> Accuracy: 0.5479, MCC: 0.1054, F1: 0.5600

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.66334 | val 0.71417
  Epoch 016 - train 0.60058 | val 0.86244
  Classification -> best τ=0.515 (val F1=0.2887)
  Directional -> Accuracy: 0.5676, MCC: 0.1737, F1: 0.6522

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.72294 | val 0.76713
  Epoch 016 - train 0.68097 | val 0.76724
  Classification -> best τ=0.605 (val F1=0.2503)
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.66401 | val 0.72391
  Epoch 018 - train 0.62422 | val 0.74795
  Classification -> best τ=0.385 (val F1=0.3254)
  Directional -> Accuracy: 0.4848, MCC: 0.1648, F1: 0.2273

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.68617 | val 0.68846
  Epoch 019 - train 0.60396 | val 0.99639
  Classification -> best τ=0.575 (val F1=0.2740)
  Directional -> Accuracy: 0.5714, MCC: 0.2197, F1: 0.4000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.65181 | val 0.66596
  Epoch 019 - train 0.63531 | val 0.76799
  Classification -> best τ=0.375 (val F1=0.2622)
  Directional -> Accuracy: 0.5000, MCC: 0.0413, F1: 0.5882

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.65760 | val 0.82263
  Epoch 020 - train 0.58108 | val 0.71736
  Epoch 021 - train 0.60123 | val 0.70822
  Classification -> best τ=0.445 (val F1=0.3954)
  Directional -> Accuracy: 0.5435, MCC: 0.1089, F1: 0.5714

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.72555 | val 0.67626
  Epoch 019 - train 0.62215 | val 0.65990
  Classification -> best τ=0.375 (val F1=0.4976)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.63317 | val 0.74822
  Epoch 016 - train 0.63105 | val 0.79312
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.66546 | val 0.68030
  Epoch 020 - train 0.61637 | val 0.78804
  Epoch 021 - train 0.62708 | val 0.78603
  Classification -> best τ=0.450 (val F1=0.4466)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.64199 | val 0.74151
  Epoch 018 - train 0.58886 | val 0.68894
  Classification -> best τ=0.435 (val F1=0.2933)
  Directional -> Accuracy: 0.5217, MCC: 0.0455, F1: 0.5217

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.75344 | val 0.77255
  Epoch 016 - train 0.59245 | val 0.73982
  Classification -> best τ=0.525 (val F1=0.1299)
  Directional -> Accuracy: 0.4419, MCC: -0.0813, F1: 0.3684

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.61982 | val 0.69549
  Epoch 020 - train 0.63043 | val 0.72273
  Epoch 022 - train 0.61427 | val 0.67153
  Classification -> best τ=0.565 (val F1=0.4682)
  Directional -> Accuracy: 0.6327, MCC: 0.1462, F1: 0.1818

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.67352 | val 0.96184
  Epoch 017 - train 0.64043 | val 1.22328
  Classification -> best τ=0.330 (val F1=0.2958)
  Directional -> Accuracy: 0.6071, MCC: 0.2717, F1: 0.5217

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.68861 | val 0.90591
  Epoch 019 - train 0.63940 | val 0.93195
  Classification -> best τ=0.550 (val F1=0.3160)
  Directional -> Accuracy: 0.5357, MCC: 0.0643, F1: 0.2778

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.65756 | val 1.21871
  Epoch 017 - train 0.64028 | val 1.81659
  Classification -> best τ=0.480 (val F1=0.1847)
  Directional -> Accuracy: 0.5370, MCC: 0.1425, F1: 0.6914

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.64733 | val 0.77668
  Epoch 019 - train 0.63876 | val 0.86235
  Classification -> best τ=0.385 (val F1=0.1168)
  Directional -> Accuracy: 0.4286, MCC: -0.1388, F1: 0.3846

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.64789 | val 0.70260

[I 2026-02-25 05:22:17,069] Trial 247 finished with value: 0.2736904387193564 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 64, 'learning_rate': 0.008436740852957465, 'weight_decay': 0.0006389236321709594, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 0.20420774031445071, 'early_stopping_min_delta': 0.003030087843917659}. Best is trial 200 with value: 0.303360648585588.

  Epoch 018 - train 0.63372 | val 0.84846
  Classification -> best τ=0.350 (val F1=0.2057)
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2736904387193564
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.65848 | val 0.67133
  Epoch 020 - train 0.62068 | val 0.65237
  Epoch 030 - train 0.59941 | val 0.63261
  Epoch 040 - train 0.57702 | val 0.77090
  Epoch 044 - train 0.56737 | val 0.66732
  Classification -> best τ=0.400 (val F1=0.3013)
  Directional -> Accuracy: 0.5132, MCC: 0.0917, F1: 0.5934

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.60163 | val 0.69292
  Epoch 019 - train 0.60934 | val 0.71065
  Classification -> best τ=0.455 (val F1=0.2942)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.67363 | val 0.70004
  Epoch 020 - train 0.62719 | val 0.88556
  Classification -> best τ=0.460 (val F1=0.3020)
  Directional -> Accuracy: 0.5957, MCC: 0.1825, F1: 0.6780

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.67597 | val 0.71349
  Epoch 020 - train 0.68097 | val 0.78909
  Epoch 021 - train 0.67358 | val 0.73213
  Classification -> best τ=0.495 (val F1=0.1905)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.68879 | val 0.68014
  Epoch 020 - train 0.62639 | val 0.67847
  Epoch 021 - train 0.64724 | val 0.68538
  Classification -> best τ=0.605 (val F1=0.4753)
  Directional -> Accuracy: 0.4902, MCC: 0.0466, F1: 0.1875

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.71040 | val 0.70071
  Epoch 016 - train 0.65453 | val 0.70883
  Classification -> best τ=0.490 (val F1=0.1644)
  Directional -> Accuracy: 0.4681, MCC: -0.0926, F1: 0.6269

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.68575 | val 0.68036
  Epoch 020 - train 0.68704 | val 0.69056
  Epoch 030 - train 0.66844 | val 0.70171
  Epoch 031 - train 0.67351 | val 0.69266
  Classification -> best τ=0.470 (val F1=0.3931)
  Directional -> Accuracy: 0.4493, MCC: 0.0572, F1: 0.5682

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.65691 | val 0.63612
  Epoch 019 - train 0.56852 | val 0.65543
  Classification -> best τ=0.345 (val F1=0.1823)
  Directional -> Accuracy: 0.5349, MCC: -0.0423, F1: 0.2308

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.65597 | val 0.83933
  Epoch 016 - train 0.60254 | val 0.75168
  Classification -> best τ=0.535 (val F1=0.1978)
  Directional -> Accuracy: 0.5510, MCC: 0.1544, F1: 0.6071

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.66273 | val 0.71872
  Epoch 017 - train 0.65544 | val 0.70679
  Classification -> best τ=0.500 (val F1=0.1258)
  Directional -> Accuracy: 0.5429, MCC: 0.1083, F1: 0.5429

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.67980 | val 0.70911
  Epoch 020 - train 0.65853 | val 1.15259
  Classification -> best τ=0.465 (val F1=0.3151)
  Directional -> Accuracy: 0.5200, MCC: 0.0788, F1: 0.5862

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.65029 | val 0.80337
  Epoch 016 - train 0.58937 | val 1.04033
  Classification -> best τ=0.475 (val F1=0.1421)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.66976 | val 0.75992
  Epoch 016 - train 0.60541 | val 0.96654
  Classification -> best τ=0.495 (val F1=0.0989)
  Directional -> Accuracy: 0.4286, MCC: -0.1946, F1: 0.2500

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.63511 | val 0.63766
  Epoch 020 - train 0.65043 | val 0.68190
  Epoch 027 - train 0.64465 | val 0.64873
  Classification -> best τ=0.360 (val F1=0.3635)
  Directional -> Accuracy: 0.5333, MCC: 0.0788, F1: 0.6316

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.65587 | val 0.72327
  Epoch 020 - train 0.62991 | val 0.68293
  Epoch 021 - train 0.64786 | val 0.68141
  Classification -> best τ=0.425 (val F1=0.2732)
  Directional -> Accuracy: 0.4808, MCC: 0.1296, F1: 0.6400

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.66090 | val 0.72938
  Epoch 018 - train 0.68795 | val 0.67354
  Classification -> best τ=0.540 (val F1=0.4216)
  Directional -> Accuracy: 0.6522, MCC: 0.3601, F1: 0.7500

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.63524 | val 0.78512
  Epoch 016 - train 0.65588 | val 0.84980
  Classification -> best τ=0.535 (val F1=0.2207)
  Directional -> Accuracy: 0.4746, MCC: -0.1133, F1: 0.5753

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.64931 | val 0.88720
  Epoch 017 - train 0.66342 | val 0.94053
  Classification -> best τ=0.415 (val F1=0.2137)
  Directional -> Accuracy: 0.5867, MCC: 0.0970, F1: 0.6869

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.67491 | val 0.70476
  Epoch 020 - train 0.68273 | val 0.82535
  Epoch 024 - train 0.61303 | val 1.01788
  Classification -> best τ=0.450 (val F1=0.3601)
  Directional -> Accuracy: 0.5077, MCC: 0.1597, F1: 0.3600

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.67874 | val 0.67905
  Epoch 020 - train 0.66983 | val 0.72974
  Epoch 030 - train 0.62435 | val 0.67209
  Epoch 033 - train 0.60812 | val 0.67146
  Classification -> best τ=0.480 (val F1=0.3259)
  Directional -> Accuracy: 0.4933, MCC: 0.1859, F1: 0.1364

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.69153 | val 0.68004
  Epoch 020 - train 0.66799 | val 0.71406
  Epoch 030 - train 0.59894 | val 0.69835
  Epoch 031 - train 0.62549 | val 0.68045
  Classification -> best τ=0.520 (val F1=0.3518)
  Directional -> Accuracy: 0.4681, MCC: 0.1239, F1: 0.3243

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.66881 | val 0.88089
  Epoch 016 - train 0.69028 | val 0.86098
  Classification -> best τ=0.520 (val F1=0.1427)
  Directional -> Accuracy: 0.4091, MCC: -0.1839, F1: 0.3607

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.68237 | val 0.68179
  Epoch 020 - train 0.67955 | val 0.69827
  Epoch 030 - train 0.67070 | val 0.68622
  Epoch 040 - train 0.64072 | val 0.82260
  Epoch 043 - train 0.62023 | val 0.84199
  Classification -> best τ=0.435 (val F1=0.3119)
  Directional -> Accuracy: 0.5690, MCC: 0.1345, F1: 0.6032

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.65967 | val 0.70126
  Epoch 017 - train 0.64330 | val 0.70002
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4769, MCC: 0.0000, F1: 0.6458

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.66224 | val 0.67572
  Epoch 020 - train 0.63421 | val 0.66082
  Epoch 030 - train 0.59961 | val 0.70502
  Epoch 036 - train 0.56093 | val 0.67046
  Classification -> best τ=0.415 (val F1=0.3629)
  Directional -> Accuracy: 0.5536, MCC: 0.1867, F1: 0.4444

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.65628 | val 0.74061
  Epoch 020 - train 0.62680 | val 1.32704
  Epoch 024 - train 0.57137 | val 1.13798
  Classification -> best τ=0.530 (val F1=0.3669)
  Directional -> Accuracy: 0.5870, MCC: 0.1549, F1: 0.5128

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.67126 | val 0.71215
  Epoch 020 - train 0.64118 | val 0.71365
  Epoch 028 - train 0.63720 | val 0.70658
  Classification -> best τ=0.630 (val F1=0.2402)
  Directional -> Accuracy: 0.4762, MCC: -0.1452, F1: 0.6071

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.68726 | val 0.70920
  Epoch 019 - train 0.66415 | val 0.69081
  Classification -> best τ=0.340 (val F1=0.2510)
  Directional -> Accuracy: 0.4561, MCC: -0.0157, F1: 0.2791

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.79628 | val 0.68934
  Epoch 020 - train 0.64692 | val 0.72432
  Epoch 030 - train 0.62140 | val 0.68111
  Epoch 040 - train 0.54474 | val 0.68758
  Epoch 043 - train 0.59108 | val 0.75479
  Classification -> best τ=0.505 (val F1=0.3296)
  Directional -> Accuracy: 0.5366, MCC: 0.0241, F1: 0.6780

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.61627 | val 1.31204
  Epoch 018 - train 0.56712 | val 1.47097
  Classification -> best τ=0.540 (val F1=0.2814)
  Directional -> Accuracy: 0.5349, MCC: 0.0716, F1: 0.5455

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.69649 | val 0.64353
  Epoch 020 - train 0.63179 | val 0.61935
  Epoch 030 - train 0.60586 | val 0.80491
  Epoch 035 - train 0.54665 | val 0.66554
  Classification -> best τ=0.745 (val F1=0.3439)
  Directional -> Accuracy: 0.4419, MCC: -0.1655, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.68564 | val 0.68872
  Epoch 020 - train 0.54036 | val 1.26639
  Epoch 021 - train 0.57395 | val 1.28844
  Classification -> best τ=0.310 (val F1=0.2563)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.66656 | val 1.00839
  Epoch 017 - train 0.66420 | val 1.02305
  Classification -> best τ=0.465 (val F1=0.2709)
  Directional -> Accuracy: 0.5479, MCC: 0.1382, F1: 0.5075

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.66011 | val 0.71625
  Epoch 020 - train 0.63274 | val 0.79287
  Epoch 027 - train 0.62254 | val 1.02008
  Classification -> best τ=0.535 (val F1=0.3627)
  Directional -> Accuracy: 0.5676, MCC: 0.1737, F1: 0.6522

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.69924 | val 0.72234
  Epoch 016 - train 0.63987 | val 0.98260
  Classification -> best τ=0.550 (val F1=0.2503)
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.67042 | val 0.69658
  Epoch 020 - train 0.66703 | val 0.68430
  Epoch 024 - train 0.66353 | val 0.71125
  Classification -> best τ=0.425 (val F1=0.3254)
  Directional -> Accuracy: 0.6061, MCC: 0.2015, F1: 0.6486

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.61480 | val 0.69757
  Epoch 017 - train 0.58604 | val 0.75533
  Classification -> best τ=0.470 (val F1=0.2986)
  Directional -> Accuracy: 0.7381, MCC: 0.4767, F1: 0.7442

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.61447 | val 0.67758
  Epoch 016 - train 0.61884 | val 0.78773
  Classification -> best τ=0.455 (val F1=0.2382)
  Directional -> Accuracy: 0.5179, MCC: 0.1149, F1: 0.6301

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.62974 | val 0.71084
  Epoch 020 - train 0.53626 | val 0.73273
  Epoch 022 - train 0.50055 | val 0.74142
  Classification -> best τ=0.520 (val F1=0.2441)
  Directional -> Accuracy: 0.5217, MCC: 0.1179, F1: 0.5000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.63067 | val 0.64808
  Epoch 020 - train 0.60548 | val 0.67094
  Epoch 025 - train 0.57649 | val 0.71504
  Classification -> best τ=0.410 (val F1=0.4141)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.60842 | val 0.89541
  Epoch 016 - train 0.56347 | val 1.01318
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.67579 | val 0.69522
  Epoch 020 - train 0.62974 | val 0.75022
  Epoch 030 - train 0.61489 | val 0.68057
  Epoch 032 - train 0.63406 | val 0.66710
  Classification -> best τ=0.510 (val F1=0.3963)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.61935 | val 0.69874
  Epoch 018 - train 0.61473 | val 0.71162
  Classification -> best τ=0.460 (val F1=0.0830)
  Directional -> Accuracy: 0.4565, MCC: -0.0851, F1: 0.1379

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.63741 | val 0.74693
  Epoch 018 - train 0.63091 | val 0.73216
  Classification -> best τ=0.530 (val F1=0.3558)
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.7164

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.67355 | val 0.62758
  Epoch 020 - train 0.62128 | val 0.76600
  Epoch 025 - train 0.58094 | val 0.66828
  Classification -> best τ=0.570 (val F1=0.5421)
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.65344 | val 0.82106
  Epoch 016 - train 0.63312 | val 1.21444
  Classification -> best τ=0.450 (val F1=0.0636)
  Directional -> Accuracy: 0.4821, MCC: -0.0234, F1: 0.4528

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.64419 | val 0.85410
  Epoch 019 - train 0.61994 | val 1.48915
  Classification -> best τ=0.465 (val F1=0.2875)
  Directional -> Accuracy: 0.5714, MCC: 0.1476, F1: 0.5862

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.67663 | val 0.79094
  Epoch 016 - train 0.65839 | val 1.15047
  Classification -> best τ=0.440 (val F1=0.1847)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.65714 | val 0.75656
  Epoch 020 - train 0.61474 | val 0.74615
  Epoch 030 - train 0.61225 | val 0.73264
  Epoch 038 - train 0.59247 | val 0.80841
  Classification -> best τ=0.470 (val F1=0.1446)

[I 2026-02-25 05:23:54,701] Trial 248 finished with value: 0.2670827096791003 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 64, 'learning_rate': 0.006917049780633944, 'weight_decay': 0.0008198120253710333, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 0.14487859469732367, 'early_stopping_min_delta': 0.002831284780761629}. Best is trial 200 with value: 0.303360648585588.

  Epoch 040 - train 0.59797 | val 0.74524
  Classification -> best τ=0.315 (val F1=0.2921)
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2670827096791003
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.64953 | val 0.80051
  Epoch 017 - train 0.61034 | val 0.84061
  Classification -> best τ=0.445 (val F1=0.2036)
  Directional -> Accuracy: 0.5526, MCC: 0.0249, F1: 0.1053

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for proper time series validation for ABB. Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.66880 | val 0.72538
  Epoch 017 - train 0.57991 | val 0.71227
  Classification -> best τ=0.400 (val F1=0.2904)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 21). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.72270 | val 0.77417
  Epoch 019 - train 0.64182 | val 0.84210
  Classification -> best τ=0.540 (val F1=0.3171)
  Directional -> Accuracy: 0.5319, MCC: 0.1314, F1: 0.3529

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.66648 | val 0.76432
  Epoch 017 - train 0.65416 | val 0.77322
  Classification -> best τ=0.505 (val F1=0.1093)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.66751 | val 0.63477
  Epoch 020 - train 0.62098 | val 0.76621
  Epoch 024 - train 0.58542 | val 1.10122
  Classification -> best τ=0.580 (val F1=0.4598)
  Directional -> Accuracy: 0.5882, MCC: 0.1690, F1: 0.6316

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.63763 | val 0.71843
  Epoch 020 - train 0.64534 | val 0.70685
  Epoch 029 - train 0.55851 | val 1.05968
  Classification -> best τ=0.480 (val F1=0.2108)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.68909 | val 0.69220
  Epoch 018 - train 0.65430 | val 0.72265
  Classification -> best τ=0.570 (val F1=0.2194)
  Directional -> Accuracy: 0.6087, MCC: 0.1467, F1: 0.0690

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for proper time series validation for BBL. Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 21). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.69972 | val 0.69295
  Epoch 018 - train 0.54713 | val 0.75983
  Classification -> best τ=0.440 (val F1=0.1752)
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.5902

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.66374 | val 0.72086
  Epoch 020 - train 0.60185 | val 0.74324
  Classification -> best τ=0.410 (val F1=0.2265)
  Directional -> Accuracy: 0.6735, MCC: 0.3339, F1: 0.5789

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 21). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 21). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.65065 | val 0.73725
  Epoch 016 - train 0.61168 | val 0.72044
  Classification -> best τ=0.545 (val F1=0.1137)
  Directional -> Accuracy: 0.5429, MCC: -0.0589, F1: 0.1111

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.64583 | val 0.81007
  Epoch 017 - train 0.63542 | val 0.94352
  Classification -> best τ=0.455 (val F1=0.1802)
  Directional -> Accuracy: 0.5800, MCC: 0.1445, F1: 0.3226

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.66509 | val 0.74028
  Epoch 017 - train 0.59358 | val 0.83152
  Classification -> best τ=0.535 (val F1=0.2105)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.66316 | val 0.70336
  Epoch 016 - train 0.56871 | val 0.76522
  Classification -> best τ=0.575 (val F1=0.1908)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for proper time series validation for CODI. Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.68183 | val 0.61932
  Epoch 020 - train 0.63169 | val 0.74311
  Epoch 025 - train 0.60094 | val 0.90169
  Classification -> best τ=0.285 (val F1=0.3282)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.64390 | val 0.83340
  Epoch 018 - train 0.62184 | val 1.32680
  Classification -> best τ=0.540 (val F1=0.2673)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.66661 | val 0.71898
  Epoch 017 - train 0.61421 | val 0.74781
  Classification -> best τ=0.395 (val F1=0.3536)
  Directional -> Accuracy: 0.6232, MCC: 0.2368, F1: 0.6905

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.67496 | val 0.95822
  Epoch 017 - train 0.64981 | val 1.13150
  Classification -> best τ=0.575 (val F1=0.1291)
  Directional -> Accuracy: 0.6102, MCC: 0.2415, F1: 0.6462

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.67452 | val 0.93009
  Epoch 018 - train 0.63854 | val 0.85606
  Classification -> best τ=0.555 (val F1=0.1581)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.67084 | val 0.87053
  Epoch 016 - train 0.62731 | val 1.48359
  Classification -> best τ=0.480 (val F1=0.2366)
  Directional -> Accuracy: 0.5077, MCC: 0.1597, F1: 0.3600

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 21). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.66113 | val 0.69703
  Epoch 020 - train 0.66168 | val 0.74397
  Epoch 023 - train 0.65348 | val 0.81474
  Classification -> best τ=0.475 (val F1=0.3336)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.67193 | val 0.67993
  Epoch 020 - train 0.57577 | val 0.98156
  Epoch 026 - train 0.57595 | val 1.32943
  Classification -> best τ=0.425 (val F1=0.3307)
  Directional -> Accuracy: 0.4894, MCC: 0.0037, F1: 0.5200

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for proper time series validation for HRG. Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for proper time series validation for HSBC. Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for proper time series validation for IEP. Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.67381 | val 0.73134
  Epoch 018 - train 0.64868 | val 0.79585
  Classification -> best τ=0.530 (val F1=0.2494)
  Directional -> Accuracy: 0.6364, MCC: 0.2862, F1: 0.5714

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.65809 | val 0.76357
  Epoch 017 - train 0.66347 | val 0.72027
  Classification -> best τ=0.670 (val F1=0.3282)
  Directional -> Accuracy: 0.5000, MCC: 0.0842, F1: 0.3830

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.68236 | val 0.69922
  Epoch 018 - train 0.62406 | val 0.87458
  Classification -> best τ=0.470 (val F1=0.1507)
  Directional -> Accuracy: 0.5231, MCC: 0.0776, F1: 0.6076

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.65389 | val 0.73308
  Epoch 020 - train 0.60089 | val 0.71317
  Epoch 022 - train 0.57473 | val 0.73585
  Classification -> best τ=0.605 (val F1=0.4903)
  Directional -> Accuracy: 0.5357, MCC: 0.1974, F1: 0.3500

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.68987 | val 0.70907
  Epoch 019 - train 0.67387 | val 0.70917
  Classification -> best τ=0.475 (val F1=0.2935)
  Directional -> Accuracy: 0.4565, MCC: -0.0553, F1: 0.4898

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.69390 | val 0.68937
  Epoch 016 - train 0.64467 | val 0.68798
  Classification -> best τ=0.575 (val F1=0.2976)
  Directional -> Accuracy: 0.5000, MCC: 0.0280, F1: 0.4878

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.64604 | val 0.70863
  Epoch 019 - train 0.61230 | val 0.78461
  Classification -> best τ=0.430 (val F1=0.2479)
  Directional -> Accuracy: 0.5263, MCC: 0.2741, F1: 0.2703

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.72011 | val 0.67752
  Epoch 020 - train 0.59719 | val 0.66573
  Epoch 030 - train 0.57684 | val 1.51508
  Epoch 033 - train 0.57394 | val 1.05845
  Classification -> best τ=0.660 (val F1=0.3477)
  Directional -> Accuracy: 0.4634, MCC: -0.0716, F1: 0.4762

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.68955 | val 0.87244
  Epoch 016 - train 0.64619 | val 1.42815
  Classification -> best τ=0.555 (val F1=0.2814)
  Directional -> Accuracy: 0.4884, MCC: -0.0353, F1: 0.3529

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.66144 | val 0.73280
  Epoch 017 - train 0.62936 | val 0.72360
  Classification -> best τ=0.560 (val F1=0.2525)
  Directional -> Accuracy: 0.5581, MCC: 0.1822, F1: 0.4242

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.65325 | val 0.68407
  Epoch 017 - train 0.62630 | val 1.01338
  Classification -> best τ=0.415 (val F1=0.2488)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.66579 | val 0.65219
  Epoch 020 - train 0.64737 | val 0.89377
  Epoch 029 - train 0.62105 | val 0.98737
  Classification -> best τ=0.240 (val F1=0.3520)
  Directional -> Accuracy: 0.5616, MCC: 0.1446, F1: 0.5556

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for proper time series validation for NGG. Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.63089 | val 0.70008
  Epoch 020 - train 0.58584 | val 1.08724
  Epoch 025 - train 0.54446 | val 0.93042
  Classification -> best τ=0.425 (val F1=0.3464)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.71606 | val 0.75733
  Epoch 018 - train 0.60867 | val 0.85189
  Classification -> best τ=0.435 (val F1=0.2358)
  Directional -> Accuracy: 0.6364, MCC: 0.2910, F1: 0.6667

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.70318 | val 0.71789
  Epoch 016 - train 0.66131 | val 0.72650
  Classification -> best τ=0.445 (val F1=0.2464)
  Directional -> Accuracy: 0.5758, MCC: 0.0000, F1: 0.7308

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.63342 | val 0.72891
  Epoch 020 - train 0.54053 | val 0.87082
  Epoch 022 - train 0.52890 | val 0.80171
  Classification -> best τ=0.520 (val F1=0.2967)
  Directional -> Accuracy: 0.5952, MCC: 0.2427, F1: 0.4848

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.64986 | val 0.67229
  Epoch 019 - train 0.61970 | val 0.72768
  Classification -> best τ=0.385 (val F1=0.2305)
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.6341

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.62786 | val 0.72460
  Epoch 018 - train 0.63279 | val 0.73946
  Classification -> best τ=0.615 (val F1=0.2659)
  Directional -> Accuracy: 0.3913, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 21). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for proper time series validation for PTR. Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 21). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for proper time series validation for REX. Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.68613 | val 0.69864
  Epoch 020 - train 0.68011 | val 0.95944
  Epoch 023 - train 0.57355 | val 0.70397
  Classification -> best τ=0.405 (val F1=0.1477)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for proper time series validation for SNP. Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.66023 | val 0.74317
  Epoch 018 - train 0.51690 | val 0.83107
  Classification -> best τ=0.465 (val F1=0.0944)
  Directional -> Accuracy: 0.4595, MCC: -0.0564, F1: 0.3750

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 21). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for proper time series validation for SRE. Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.65989 | val 0.72711
  Epoch 020 - train 0.61627 | val 1.05798
  Epoch 029 - train 0.57790 | val 1.47982
  Classification -> best τ=0.445 (val F1=0.3677)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for proper time series validation for UL. Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for proper time series validation for UN. Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.67884 | val 0.68513
  Epoch 017 - train 0.62983 | val 0.68694
  Classification -> best τ=0.470 (val F1=0.4141)
  Directional -> Accuracy: 0.5870, MCC: 0.1686, F1: 0.6415

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.63669 | val 0.71529
  Epoch 020 - train 0.63974 | val 0.69536
  Epoch 021 - train 0.59834 | val 0.68462
  Classification -> best τ=0.380 (val F1=0.5270)
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.7164

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.67543 | val 0.62920
  Epoch 020 - train 0.58027 | val 0.68953
  Epoch 024 - train 0.58113 | val 0.70056
  Classification -> best τ=0.605 (val F1=0.6110)
  Directional -> Accuracy: 0.3673, MCC: -0.1814, F1: 0.5373

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.66118 | val 0.89399
  Epoch 018 - train 0.60517 | val 1.36067
  Classification -> best τ=0.470 (val F1=0.1942)
  Directional -> Accuracy: 0.6607, MCC: 0.3362, F1: 0.7397

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.67245 | val 0.86313
  Epoch 016 - train 0.63857 | val 1.08105
  Classification -> best τ=0.530 (val F1=0.3819)
  Directional -> Accuracy: 0.5357, MCC: 0.1486, F1: 0.6579

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.62518 | val 1.26799
  Epoch 020 - train 0.63254 | val 2.20376
  Epoch 022 - train 0.61395 | val 2.04686
  Classification -> best τ=0.345 (val F1=0.2330)
  Directional -> Accuracy: 0.5370, MCC: 0.1425, F1: 0.6914

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.66201 | val 0.78357
  Epoch 016 - train 0.62732 | val 0.79580
  Classification -> best τ=0.505 (val F1=0.1473)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.66615 | val 0.70321
  Epoch 020 - train 0.65806 | val 0.71831

[I 2026-02-25 05:25:55,720] Trial 249 finished with value: 0.2712850326908944 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 64, 'learning_rate': 0.006023639267399404, 'weight_decay': 0.000618773686731216, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 0.18358988690875097, 'early_stopping_min_delta': 0.002597429756161186}. Best is trial 200 with value: 0.303360648585588.

  Epoch 025 - train 0.59739 | val 1.03491
  Classification -> best τ=0.580 (val F1=0.2397)
  Directional -> Accuracy: 0.4754, MCC: -0.0732, F1: 0.3333

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2712850326908944
Saved Optuna results to ../results/benchmarking/classification/optuna_tuning_base_1H.csv