# Benchmarking Results from Classification and Regression

#### Set Up

In [1]:
import pandas as pd
import numpy as np
import site
import os

In [2]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import TimeSeriesSplit
from sklearn.utils.class_weight import compute_class_weight

from sklearn.metrics import (
    precision_score, recall_score, f1_score, matthews_corrcoef,
    mean_squared_error, mean_absolute_error, r2_score, confusion_matrix
)

import torch
import torch.nn as nn
import torch.nn.functional as F

from torch.utils.data import Dataset, DataLoader
from torch.optim import Adam
from torch.optim.lr_scheduler import ReduceLROnPlateau
from contextlib import nullcontext

import random

from unicodedata import bidirectional

### Utility Classes and Functions

In [3]:
def set_global_seeds(seed: int = 42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

set_global_seeds(42)

# Datasets
class SequenceDataset(Dataset):
    def __init__(self, X, y):
        self.X = torch.tensor(X, dtype=torch.float32)
        self.y = torch.tensor(y, dtype=torch.float32)

    def __len__(self):
        return self.X.shape[0]

    def __getitem__(self, idx):
        return self.X[idx], self.y[idx]

class OrdinalSequenceDataset(Dataset):
    def __init__(self, X, T):
        self.X = torch.tensor(X, dtype=torch.float32)
        self.T = torch.tensor(T, dtype=torch.float32)

    def __len__(self):
        return self.X.shape[0]

    def __getitem__(self, idx):
        return self.X[idx], self.T[idx]

def make_cumulative_targets(y_int, K):
    y = y_int.reshape(-1, 1)
    ks = np.arange(K-1).reshape(1, -1)
    return (y > ks).astype(np.float32)

def decode_ordinal(probs, thr=0.5):
    return (probs >= thr).sum(axis=1)

# Models
class OrdinalHeadCORN(nn.Module):
    def __init__(self, in_dim, K):
        super().__init__()
        self.fc = nn.Linear(in_dim, K-1)

    def forward(self, h):
        return self.fc(h)


class OrdinalHeadCORAL(nn.Module):
    def __init__(self, in_dim, K):
        super().__init__()
        self.w = nn.Linear(in_dim, 1, bias=False)
        self._beta = nn.Parameter(torch.zeros(K-1))
        self.softplus = nn.Softplus()

    def forward(self, h):
        base = self.w(h)
        deltas = self.softplus(self._beta)
        b = torch.cumsum(deltas, dim=0)
        return base - b



class RNNHead(nn.Module):
    # Shared head:
    #   - RNN stack (LSTM/GRU, uni/bi)
    #   - BatchNorm + Dense(32, ReLU) + Dropout
    #   - Output layer (1 unit): linear (regression) or logits (classification)
    def __init__(self, input_size, rnn_type='LSTM', bidirectional=False, problem_type='classification',
                 n_classes=6, ordinal_head='coral', hidden1=128, hidden2=64, num_layers=1,
                 inter_rnn_drop=0.1, dropout=0.3, use_layernorm=False):
        super().__init__()
        self.problem_type = problem_type
        self.bidirectional = bidirectional
        self.rnn_type = rnn_type.upper()
        self.n_classes = n_classes
        self.ordinal_head = ordinal_head
        self.num_layers = int(num_layers)
        self.hidden1 = int(hidden1)
        self.hidden2 = int(hidden2)

        if self.num_layers not in (1, 2):
            raise ValueError("num_layers must be 1 or 2")

        rnn_cls = {'LSTM': nn.LSTM, 'GRU': nn.GRU}[('GRU' if 'GRU' in self.rnn_type else 'LSTM')]

        self.rnn1 = rnn_cls(
            input_size=input_size, hidden_size=self.hidden1, num_layers=1,
            batch_first=True, dropout=0.0, bidirectional=bidirectional
        )

        self.inter_rnn_drop = nn.Dropout(float(inter_rnn_drop))

        self.rnn2 = None
        if self.num_layers == 2:
            self.rnn2 = rnn_cls(
                input_size=self.hidden1*(2 if bidirectional else 1), hidden_size=self.hidden2, num_layers=1,
                batch_first=True, dropout=0.0, bidirectional=bidirectional
            )
            feat_dim = self.hidden2*(2 if bidirectional else 1)
        else:
            feat_dim = self.hidden1*(2 if bidirectional else 1)

        if use_layernorm:
            self.bn = nn.LayerNorm(feat_dim)
        else:
            self.bn = nn.BatchNorm1d(feat_dim)
        self.fc = nn.Linear(feat_dim, 32)
        self.drop = nn.Dropout(float(dropout))
        if self.problem_type == 'multiclass':
            head = self.ordinal_head.lower() if isinstance(self.ordinal_head, str) else 'coral'
            if head == 'corn':
                self.out = OrdinalHeadCORN(32, self.n_classes)
            else:
                self.out = OrdinalHeadCORAL(32, self.n_classes)
        else:
            self.out = nn.Linear(32, 1)

    def forward(self, x):
        # x: [B, T, F]
        out, _ = self.rnn1(x)
        if self.num_layers == 2:
            out = self.inter_rnn_drop(out)   # inter-layer dropout (sequence-wise)
            out, _ = self.rnn2(out)
        # take last timestep: [B, T, H] -> [B, H]
        out = out[:, -1, :]
        out = self.bn(out)
        out = F.relu(self.fc(out))
        out = self.drop(out)
        out = self.out(out)  # shape [B,1]
        return out  # regression: raw; classification: logits


def build_model(input_shape, model_type='LSTM', problem_type='regression', n_classes=6, ordinal_head='coral',
                hidden1=128, hidden2=64, num_layers=2, inter_rnn_drop=0.1, dropout=0.3, use_layernorm=False):
    seq_len, n_features = input_shape
    model_type = model_type.upper()
    kwargs = dict(
        problem_type=problem_type,
        n_classes=n_classes,
        ordinal_head=ordinal_head,
        hidden1=hidden1,
        hidden2=hidden2,
        num_layers=num_layers,
        inter_rnn_drop=inter_rnn_drop,
        dropout=dropout,
        use_layernorm=use_layernorm,
    )
    if model_type == 'LSTM':
        return RNNHead(n_features, rnn_type='LSTM', bidirectional=False, **kwargs)
    elif model_type == 'BILSTM':
        return RNNHead(n_features, rnn_type='LSTM', bidirectional=True, **kwargs)
    elif model_type == 'GRU':
        return RNNHead(n_features, rnn_type='GRU', bidirectional=False, **kwargs)
    elif model_type == 'BIGRU':
        return RNNHead(n_features, rnn_type='GRU', bidirectional=True, **kwargs)
    else:
        raise ValueError("Model type must be one of: ['LSTM','BiLSTM','GRU','BiGRU']")

# Early Stopping (PyTorch)
class EarlyStopper:
    def __init__(self, patience=15, min_delta=0.0, restore_best=True):
        self.patience = patience
        self.min_delta = min_delta
        self.restore_best = restore_best
        self.best_loss = float('inf')
        self.counter = 0
        self.best_state = None

    def step(self, val_loss, model):
        improved = (self.best_loss - val_loss) > self.min_delta
        if improved:
            self.best_loss = val_loss
            self.counter = 0
            if self.restore_best:
                # Deep copy state dict
                self.best_state = {k: v.detach().clone() for k, v in model.state_dict().items()}
        else:
            self.counter += 1
        return self.counter >= self.patience

    def restore(self, model):
        if self.restore_best and self.best_state is not None:
            model.load_state_dict(self.best_state)

In [4]:
def edge_labels_from_edges(edges, decimals=1):
    labels = []
    C = len(edges) - 1
    for i in range(C):
        lo, hi = edges[i], edges[i+1]
        if i == 0:
            labels.append(f"≤ {hi*100:.{decimals}f}%")
        elif i == C - 1:
            labels.append(f"> {lo*100:.{decimals}f}%")
        else:
            labels.append(f"({lo*100:.{decimals}f}%,{hi*100:.{decimals}f}%]")
    return labels

def pct_return(series, h):
    return series.shift(-h) / series - 1.0

def safe_quantile_edges(x, n_classes=6):
    qs = np.linspace(0, 1, n_classes + 1)
    edges = np.quantile(x, qs)
    for i in range(1, len(edges)):
        if edges[i] <= edges[i-1]:
            edges[i] = np.nextafter(edges[i-1], np.inf)
    return edges

def bucketize_with_edges(x, edges):
    inner = edges[1:-1]
    return np.digitize(x, inner, right=True).astype(int)

@torch.no_grad()
def collect_logits(model, loader, device):
    model.eval()
    chunks = []
    for xb, _ in loader:
        xb = xb.to(device)
        chunks.append(model(xb).detach().cpu())
    return torch.cat(chunks, dim=0)

def find_taus_per_threshold(Z_val, y_val_idx, grid=np.linspace(0, 1, 100)):
    if isinstance(Z_val, torch.Tensor):
        Z_val = Z_val.numpy()
    P_val = 1.0 / (1.0 + np.exp(-Z_val))
    P_rep = monotone_repair_numpy(P_val)
    K_1 = P_rep.shape[1]
    best_taus = np.full(K_1, 0.5, dtype=np.float32)
    for k in range(K_1):
        best_f1, best_tau = -1.0, 0.5
        for tau in grid:
            y_hat = decode_ordinal_with_taus(P_rep, taus_override={k: tau})
            f1 = f1_score(y_val_idx, y_hat, average='macro', zero_division=0)
            if f1 > best_f1:
                best_f1, best_tau = f1, tau
        best_taus[k] = best_tau
    return best_taus

def monotone_repair_numpy(P):
    P = np.asarray(P).copy()
    for k in range(P.shape[1] - 2, -1, -1):
        P[:, k] = np.maximum(P[:, k], P[:, k+1])
    return P

def decode_ordinal_with_taus(P_rep, taus=None, taus_override=None):
    N, K_1 = P_rep.shape
    if taus is None:
        taus = np.full(K_1, 0.5, dtype=np.float32)
    if taus_override:
        taus = taus.copy()
        for k, v in taus_override.items():
            taus[k] = v
    comp = (P_rep >= taus.reshape(1, -1)).astype(np.int32)
    return comp.sum(axis=1).astype(np.int64)

def ordinal_to_class_probs(P_rep):
    N, K_1 = P_rep.shape
    K = K_1 + 1
    Pc = np.empty((N, K), dtype=np.float32)
    Pc[:, 0] = 1.0 - P_rep[:, 0]
    for c in range(1, K - 1):
        Pc[:, c] = np.clip(P_rep[:, c-1] - P_rep[:, c], 0.0, 1.0)
    Pc[:, K - 1] = P_rep[:, K_1 - 1]
    s = Pc.sum(axis=1, keepdims=True)
    return Pc / np.maximum(s, 1e-8)


def best_threshold_from_val(y_true, y_scores, metric='f1', grid=None):
    """
    Sweep probability thresholds on validation scores to maximize a metric.
    metric can be 'f1', 'mcc', 'accuracy', or a callable(y_true,y_pred)->float.
    Returns (best_threshold, best_metric_value).
    """
    y_true = np.asarray(y_true).astype(int)
    y_scores = np.asarray(y_scores).astype(float)
    if grid is None:
        grid = np.linspace(0.05, 0.95, 181)
    metric_fn = None
    if callable(metric):
        metric_fn = metric
    else:
        name = str(metric).lower()
        if name == 'f1':
            metric_fn = lambda yt, yp: f1_score(yt, yp, zero_division=0)
        elif name == 'mcc':
            metric_fn = lambda yt, yp: matthews_corrcoef(yt, yp)
        elif name in ('acc', 'accuracy'):
            metric_fn = lambda yt, yp: (yt == yp).mean()
        else:
            raise ValueError(f"Unsupported metric '{metric}'")
    best_thr = 0.5
    best_val = -np.inf
    for thr in grid:
        preds = (y_scores >= thr).astype(int)
        val = metric_fn(y_true, preds)
        if val > best_val + 1e-12 or (abs(val - best_val) <= 1e-12 and thr < best_thr):
            best_val = float(val)
            best_thr = float(thr)
    return best_thr, best_val

## Stock Prediction Pipeline

In [5]:
class StockPredictionPipeline:
    def __init__(self, df, feature_columns, model_type='LSTM', sequence_length=24, problem_type='regression', horizon_steps=1, n_classes=6, ordinal_head='coral', fixed_bucket_edges=None,
                 hidden1=256, hidden2=64, num_layers=1, inter_rnn_drop=0.0, dropout=0.4,
                 batch_size=32, learning_rate=7e-3, weight_decay=2e-3, lr_patience=7, lr_factor=0.5,
                 early_stopping_patience=20, max_epochs=20, use_layernorm=False, huber_delta=1.0, early_stopping_min_delta=0.0):
        self.df = df.copy()
        self.feature_columns = feature_columns
        self.model_type = model_type
        self.sequence_length = sequence_length
        self.problem_type = problem_type
        self.horizon_steps = horizon_steps
        self.results = []
        self.loss_curves = []
        self.n_classes = n_classes
        self.ordinal_head = ordinal_head
        self.hidden1 = hidden1
        self.hidden2 = hidden2
        self.num_layers = num_layers
        self.inter_rnn_drop = inter_rnn_drop
        self.dropout = dropout
        self.batch_size = batch_size
        self.learning_rate = learning_rate
        self.weight_decay = weight_decay
        self.lr_patience = lr_patience
        self.lr_factor = lr_factor
        self.early_stopping_patience = early_stopping_patience
        self.max_epochs = max_epochs
        self.use_layernorm = use_layernorm
        self.huber_delta = huber_delta
        self.early_stopping_min_delta = early_stopping_min_delta
        self.fixed_bucket_edges = None
        if fixed_bucket_edges is not None:
            edges = np.asarray(fixed_bucket_edges, dtype=float)
            if edges.ndim != 1:
                raise ValueError("fixed_bucket_edges must be a 1D sequence of monotonically increasing numbers")
            if edges.size < 2:
                raise ValueError("fixed_bucket_edges must contain at least two values")
            if np.any(np.diff(edges) <= 0):
                raise ValueError("fixed_bucket_edges must be strictly increasing")
            self.n_classes = int(edges.size - 1)
            self.fixed_bucket_edges = edges

        # Validate
        self._validate_inputs()

        # Device & precision
        self.device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
        self.mixed_precision = torch.cuda.is_available()

        print(f"Pipeline initialized for a '{self.problem_type}' problem "
              f"with horizon {self.horizon_steps} steps. Device: {self.device}")

    def _validate_inputs(self):
        missing_cols = [col for col in self.feature_columns if col not in self.df.columns]
        if missing_cols:
            raise ValueError(f"Missing feature columns: {missing_cols}")

        if 'close' not in self.df.columns and 'close_price' not in self.df.columns:
            raise ValueError("No 'close' or 'close_price' column found in data")

        valid_models = ['LSTM', 'BiLSTM', 'GRU', 'BiGRU']
        if self.model_type not in valid_models:
            raise ValueError(f"Model type must be one of: {valid_models}")

        if self.problem_type not in ['regression', 'classification', 'multiclass']:
            raise ValueError("Problem type must be 'regression', 'classification', or 'multiclass'")

    def create_target_variable(self, company_data):
        company_data = company_data.copy()
        price_col = 'close' if 'close' in company_data.columns else 'close_price'
        if 'date' in company_data.columns:
            company_data = company_data.sort_values('date')
            
        h = self.horizon_steps

        company_data['target_regression'] = (
            np.log(company_data[price_col].shift(-h)) - np.log(company_data[price_col])
        )
        company_data['target_direction'] = (company_data['target_regression'] > 0).astype(int)
        company_data['ret_h'] = pct_return(company_data[price_col], h)
        if self.problem_type == 'multiclass':
            company_data = company_data.dropna(subset=['ret_h'])
        else:
            company_data = company_data.dropna()
        return company_data

    def create_sequences(self, features, *targets):
        X = []
        y_sequences = [[] for _ in targets]
        for i in range(self.sequence_length, len(features)):
            X.append(features[i-self.sequence_length:i])
            for j, target in enumerate(targets):
                y_sequences[j].append(target[i])
        return (np.array(X),) + tuple(np.array(y) for y in y_sequences)

    def _train_one_epoch(self, model, loader, optimizer, loss_fn, scaler):
        model.train()
        total_loss = 0.0
        for xb, yb in loader:
            xb = xb.to(self.device)
            yb = yb.to(self.device).view(-1, 1)

            optimizer.zero_grad(set_to_none=True)

            ctx = torch.amp.autocast('cuda') if self.mixed_precision else nullcontext()
            with ctx:
                logits = model(xb)
                loss = loss_fn(logits, yb)

            if self.mixed_precision:
                scaler.scale(loss).backward()
                scaler.unscale_(optimizer)
                torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
                scaler.step(optimizer)
                scaler.update()
            else:
                loss.backward()
                torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
                optimizer.step()

            total_loss += loss.item() * xb.size(0)

        return total_loss / len(loader.dataset)

    @torch.no_grad()
    def _eval_one_epoch(self, model, loader, loss_fn):
        model.eval()
        total_loss = 0.0
        for xb, yb in loader:
            xb = xb.to(self.device)
            yb = yb.to(self.device).view(-1, 1)
            logits = model(xb)
            loss = loss_fn(logits, yb)
            total_loss += loss.item() * xb.size(0)
        return total_loss / len(loader.dataset)

    def _train_one_epoch_multiclass(self, model, loader, optimizer, scaler, *, pos_weight=None):
        model.train()
        total = 0.0
        for xb, yb in loader:
            xb = xb.to(self.device)
            yb = yb.to(self.device)
            optimizer.zero_grad(set_to_none=True)
            ctx = torch.amp.autocast('cuda') if self.mixed_precision else nullcontext()
            with ctx:
                logits = model(xb)
                bces = []
                for k in range(logits.shape[1]):
                    w = None if pos_weight is None else pos_weight[k]
                    bce_k = F.binary_cross_entropy_with_logits(logits[:, k], yb[:, k], pos_weight=w)
                    bces.append(bce_k)
                loss = torch.stack(bces).mean()
            if self.mixed_precision:
                scaler.scale(loss).backward()
                scaler.unscale_(optimizer)
                torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
                scaler.step(optimizer)
                scaler.update()
            else:
                loss.backward()
                torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
                optimizer.step()
            total += float(loss.item()) * xb.size(0)
        return total / len(loader.dataset)

    @torch.no_grad()
    def _eval_one_epoch_multiclass(self, model, loader, pos_weight=None):
        model.eval()
        total = 0.0
        for xb, yb in loader:
            xb = xb.to(self.device)
            yb = yb.to(self.device)
            logits = model(xb)
            bces = []
            for k in range(logits.shape[1]):
                w = None if pos_weight is None else pos_weight[k]
                bce_k = F.binary_cross_entropy_with_logits(logits[:, k], yb[:, k], pos_weight=w)
                bces.append(bce_k)
            loss = torch.stack(bces).mean()
            total += float(loss.item()) * xb.size(0)
        return total / len(loader.dataset)

    @torch.no_grad()
    def _predict(self, model, loader):
        model.eval()
        outs = []
        for xb, _ in loader:
            xb = xb.to(self.device)
            logits = model(xb).squeeze(1).detach().cpu().numpy()
            outs.append(logits)
        return np.concatenate(outs, axis=0)

    def build_model(self, input_shape):
        model = build_model(
            input_shape,
            model_type=self.model_type,
            problem_type=self.problem_type,
            n_classes=self.n_classes,
            ordinal_head=self.ordinal_head,
            hidden1=self.hidden1,
            hidden2=self.hidden2,
            num_layers=self.num_layers,
            inter_rnn_drop=self.inter_rnn_drop,
            dropout=self.dropout,
            use_layernorm=self.use_layernorm
        )
        return model.to(self.device)

    def process_company(self, company_name, company_data, sector):
        print(f"\nProcessing {company_name} ({sector})...")
        try:
            company_data = self.create_target_variable(company_data)

            # Min samples requirement (same heuristic)
            min_samples = self.sequence_length + 75 + self.horizon_steps
            if len(company_data) < min_samples:
                print(f"Insufficient data for {company_name} ({len(company_data)} < {min_samples}). Skipping...")
                return None

            if company_data[self.feature_columns].isnull().any().any():
                print(f"Missing values in features for {company_name}. Skipping...")
                return None

            features = company_data[self.feature_columns].values
            target_reg = company_data['target_regression'].values
            target_dir = company_data['target_direction'].values

            # Create sequences
            X_raw, y_reg, y_dir = self.create_sequences(features, target_reg, target_dir)

            # TimeSeriesSplit
            n_splits = min(5, len(X_raw) // 50)
            if n_splits < 3:
                print(f"Insufficient data for proper time series validation for {company_name}. Skipping...")
                return None

            tscv = TimeSeriesSplit(n_splits=n_splits)
            splits = list(tscv.split(X_raw))
            train_idx, test_idx = splits[-1]

            # Train/Val split (last 20% of train for val)
            val_size = int(0.2 * len(train_idx))
            if val_size == 0:
                print(f'Insufficient data for validation split for {company_name}. Skipping...')
                return None
            final_train_idx = train_idx[:-val_size]
            val_idx = train_idx[-val_size:]
            
            if self.horizon_steps > 1:
                print("Adjusting for multi-step horizon...")
                gap = self.horizon_steps
                if len(final_train_idx) > gap:
                    final_train_idx = final_train_idx[:-gap]  # drop last h labels from train
                if len(val_idx) > gap:
                    val_idx = val_idx[gap:]  # drop last h labels from val
            if len(final_train_idx) == 0 or len(val_idx) == 0:
                print(f'Insufficient data after horizon adjustment for {company_name}. Skipping...')
                return None

            X_train_raw, X_val_raw, X_test_raw = X_raw[final_train_idx], X_raw[val_idx], X_raw[test_idx]
            
            F = X_raw.shape[-1]
            feat_scaler = StandardScaler()
            X_train = feat_scaler.fit_transform(X_train_raw.reshape(-1, F)).reshape(X_train_raw.shape)
            X_val   = feat_scaler.transform(X_val_raw.reshape(-1, F)).reshape(X_val_raw.shape)
            X_test  = feat_scaler.transform(X_test_raw.reshape(-1, F)).reshape(X_test_raw.shape)

            if self.problem_type == 'multiclass':
                if 'ret_h' not in company_data.columns:
                    raise RuntimeError("Expected 'ret_h' for ordinal targets but it was missing.")
                ret_full = company_data['ret_h'].values
                ret_seq_full = ret_full[self.sequence_length:]

                ret_train = ret_seq_full[final_train_idx]
                ret_val = ret_seq_full[val_idx]
                ret_test = ret_seq_full[test_idx]

                if self.fixed_bucket_edges is not None:
                    edges = self.fixed_bucket_edges
                    if int(edges.shape[0] - 1) != self.n_classes:
                        raise ValueError("fixed_bucket_edges length must match n_classes+1")
                else:
                    edges = safe_quantile_edges(ret_train, n_classes=self.n_classes)
                edges = np.asarray(edges, dtype=float)
                K = int(edges.shape[0] - 1)
                label_names = edge_labels_from_edges(edges, decimals=1)

                y_bucket = bucketize_with_edges(ret_seq_full, edges).astype(np.int64)
                y_train = y_bucket[final_train_idx]
                y_val = y_bucket[val_idx]
                y_test = y_bucket[test_idx]

                T_train = make_cumulative_targets(y_train.astype(np.int64), K)
                T_val = make_cumulative_targets(y_val.astype(np.int64), K)
                T_test = make_cumulative_targets(y_test.astype(np.int64), K)

                train_ds = OrdinalSequenceDataset(X_train, T_train)
                val_ds = OrdinalSequenceDataset(X_val, T_val)
                test_ds = OrdinalSequenceDataset(X_test, T_test)

                train_loader = DataLoader(train_ds, batch_size=self.batch_size, shuffle=False, drop_last=False, num_workers=0)
                val_loader = DataLoader(val_ds, batch_size=self.batch_size, shuffle=False, drop_last=False, num_workers=0)
                test_loader = DataLoader(test_ds, batch_size=self.batch_size, shuffle=False, drop_last=False, num_workers=0)

                model = self.build_model((self.sequence_length, len(self.feature_columns)))

                pos_rate = T_train.mean(axis=0)
                pos_weight = (1.0 - pos_rate) / np.clip(pos_rate, 1e-6, 1.0)
                pos_weight_tensor = torch.tensor(pos_weight, dtype=torch.float32).to(self.device)

                optimizer = Adam(model.parameters(), lr=self.learning_rate, eps=1e-7, weight_decay=self.weight_decay)
                scheduler = ReduceLROnPlateau(optimizer, mode='min', factor=self.lr_factor, patience=self.lr_patience, min_lr=1e-7)
                early_stopper = EarlyStopper(patience=self.early_stopping_patience, min_delta=self.early_stopping_min_delta, restore_best=True)
                scaler = torch.amp.GradScaler('cuda', enabled=self.mixed_precision)

                max_epochs = self.max_epochs
                best_val = float('inf')
                epochs_trained = 0
                company_loss_rows = []

                for epoch in range(1, max_epochs + 1):
                    train_loss = self._train_one_epoch_multiclass(model, train_loader, optimizer, scaler, pos_weight=pos_weight_tensor)
                    val_loss = self._eval_one_epoch_multiclass(model, val_loader, pos_weight=pos_weight_tensor)
                    scheduler.step(val_loss)
                    stop = early_stopper.step(val_loss, model)
                    epochs_trained = epoch

                    row = {
                        'company': company_name,
                        'sector': sector,
                        'model_type': self.model_type,
                        'problem_type': self.problem_type,
                        'sequence_length': self.sequence_length,
                        'horizon_steps': self.horizon_steps,
                        'epoch': epoch,
                        'train_loss': float(train_loss),
                        'val_loss': float(val_loss),
                        'train_samples': len(X_train),
                        'val_samples': len(X_val),
                        'test_samples': len(X_test),
                    }

                    company_loss_rows.append(row)
                    self.loss_curves.append(row)

                    if epoch % 10 == 0 or stop:
                        print(f"  Epoch {epoch:03d} - train {train_loss:.5f} | val {val_loss:.5f}")

                    if stop:
                        break

                early_stopper.restore(model)

                Z_val = collect_logits(model, val_loader, self.device)
                taus = find_taus_per_threshold(Z_val, y_val.astype(np.int64))
                P_cum_val = torch.sigmoid(Z_val).cpu().numpy()
                P_rep_val = monotone_repair_numpy(P_cum_val)
                P_class_val = ordinal_to_class_probs(P_rep_val)
                mid_cut = (K // 2)
                y_val_dir = (y_val >= mid_cut).astype(int)
                prob_val_up = P_class_val[:, mid_cut:].sum(axis=1)
                dir_thr, dir_thr_score = best_threshold_from_val(y_val_dir, prob_val_up, metric='mcc')

                Z_test = collect_logits(model, test_loader, self.device)
                P_cum = torch.sigmoid(Z_test).cpu().numpy()
                P_rep = monotone_repair_numpy(P_cum)
                P_class = ordinal_to_class_probs(P_rep)

                y_pred_labels = decode_ordinal_with_taus(P_rep, taus=taus)
                y_true_labels = y_test

                labels = list(range(K))
                cm_counts = confusion_matrix(y_true_labels, y_pred_labels, labels=labels)
                cm_norm = confusion_matrix(y_true_labels, y_pred_labels, labels=labels, normalize='true')

                micro_acc = (y_true_labels == y_pred_labels).mean()
                macro_f1 = f1_score(y_true_labels, y_pred_labels, average='macro', zero_division=0)

                ret_seq_train = ret_seq_full[final_train_idx].astype(np.float32)
                mu_c = np.array([
                    ret_seq_train[y_train == c].mean() if np.any(y_train == c) else 0.0
                    for c in range(K)
                ], dtype=np.float32)

                expected_ret = (P_class * mu_c[None, :]).sum(axis=1)
                expected_ret_mean = float(expected_ret.mean())

                prob_test_up = P_class[:, mid_cut:].sum(axis=1)
                y_true_dir = (y_true_labels >= mid_cut).astype(int)
                y_pred_dir = (prob_test_up >= dir_thr).astype(int)
                precision = precision_score(y_true_dir, y_pred_dir, zero_division=0)
                recall = recall_score(y_true_dir, y_pred_dir, zero_division=0)
                f1 = f1_score(y_true_dir, y_pred_dir, zero_division=0)
                mcc = matthews_corrcoef(y_true_dir, y_pred_dir)
                directional_accuracy = (y_true_dir == y_pred_dir).mean()

                result = {
                    'company': company_name,
                    'sector': sector,
                    'model_type': self.model_type,
                    'problem_type': self.problem_type,
                    'horizon_steps': self.horizon_steps,
                    'macro_f1': macro_f1,
                    'micro_accuracy': micro_acc,
                    'expected_return_mean': expected_ret_mean,
                    'mse': np.nan,
                    'mae': np.nan,
                    'r2': np.nan,
                    'mcc': mcc,
                    'f1': f1,
                    'precision': precision,
                    'recall': recall,
                    'directional_accuracy': directional_accuracy,
                'val_directional_accuracy': val_directional_accuracy if self.problem_type == 'classification' else np.nan,
                'val_mcc': val_mcc if self.problem_type == 'classification' else np.nan,
                'val_f1': val_f1 if self.problem_type == 'classification' else np.nan,
                'val_precision': val_precision if self.problem_type == 'classification' else np.nan,
                'val_recall': val_recall if self.problem_type == 'classification' else np.nan,
                    'n_samples': int(X_raw.shape[0]),
                    'train_samples': int(X_train.shape[0]),
                    'val_samples': int(X_val.shape[0]),
                    'test_samples': int(X_test.shape[0]),
                    'epochs_trained': epochs_trained
                }
                result['confusion_matrix'] = cm_counts.tolist()
                result['confusion_matrix_normalized'] = cm_norm.tolist()
                result['bucket_edges'] = edges.tolist()
                result['bucket_labels'] = label_names
                result['taus'] = taus.astype(float).tolist()
                result['direction_threshold'] = dir_thr
                result['direction_threshold_metric'] = dir_thr_score

                print(f"  Multiclass -> Micro Acc: {micro_acc:.4f}, Macro F1: {macro_f1:.4f}, Expected Return: {expected_ret_mean:.6f}")
                print(f"  Directional threshold -> τ={dir_thr:.3f} (val F1={dir_thr_score:.4f})")

                del model
                torch.cuda.empty_cache()
                return result

            if self.problem_type == 'regression':
                y_train, y_val, y_test = y_reg[final_train_idx], y_reg[val_idx], y_reg[test_idx]
                target_scaler = StandardScaler()
                y_train_scaled = target_scaler.fit_transform(y_train.reshape(-1, 1)).flatten()
                y_val_scaled   = target_scaler.transform(y_val.reshape(-1, 1)).flatten()
                train_target, val_target = y_train_scaled, y_val_scaled
            else:
                y_train, y_val, y_test = y_dir[final_train_idx], y_dir[val_idx], y_dir[test_idx]
                train_target, val_target = y_train, y_val
                target_scaler = None

            # class balance note
            if self.problem_type == 'classification':
                class_ratio = np.mean(y_train)
                if class_ratio < 0.1 or class_ratio > 0.9:
                    print(f"Severe class imbalance for {company_name} ({class_ratio:.3f}). Consider using class weights.")

            # datasets & loaders
            train_ds = SequenceDataset(X_train, train_target)
            val_ds   = SequenceDataset(X_val,   val_target)
            test_ds  = SequenceDataset(X_test,  y_test)

            train_bs = min(self.batch_size, len(train_ds))
            if train_bs < 2:
                print(f'Insufficient training samples for {company_name} (train size={len(train_ds)}). Skipping...')
                return None
            if len(train_ds) % train_bs == 1 and train_bs > 2:
                train_bs -= 1  # avoid batch size 1 for BatchNorm
            val_bs = min(self.batch_size, len(val_ds))
            test_bs = min(self.batch_size, len(test_ds))

            train_loader = DataLoader(train_ds, batch_size=train_bs, shuffle=False,  drop_last=False, num_workers=0)
            val_loader   = DataLoader(val_ds,   batch_size=val_bs,   shuffle=False, drop_last=False, num_workers=0)
            test_loader  = DataLoader(test_ds,  batch_size=test_bs,  shuffle=False, drop_last=False, num_workers=0)

            # build model
            model = self.build_model((self.sequence_length, len(self.feature_columns)))

            # loss functions
            if self.problem_type == 'regression':
                loss_fn = nn.HuberLoss(delta=self.huber_delta)
            else:
                # use BCEWithLogitsLoss for numerical stability (logits input)
                loss_fn = nn.BCEWithLogitsLoss()

            # optimizer & scheduler
            optimizer = Adam(model.parameters(), lr=self.learning_rate, eps=1e-7, weight_decay=self.weight_decay)
            scheduler = ReduceLROnPlateau(optimizer, mode='min', factor=self.lr_factor, patience=self.lr_patience, min_lr=1e-7)
            early_stopper = EarlyStopper(patience=self.early_stopping_patience, min_delta=self.early_stopping_min_delta, restore_best=True)
            scaler = torch.amp.GradScaler('cuda', enabled=self.mixed_precision)

            # training loop
            max_epochs = self.max_epochs
            best_val = float('inf')
            epochs_trained = 0
            company_loss_rows = []  

            for epoch in range(1, max_epochs + 1):
                train_loss = self._train_one_epoch(model, train_loader, optimizer, loss_fn, scaler)
                val_loss = self._eval_one_epoch(model, val_loader, loss_fn)
                scheduler.step(val_loss)
                stop = early_stopper.step(val_loss, model)
                epochs_trained = epoch

                
                row = {
                    'company': company_name,
                    'sector': sector,
                    'model_type': self.model_type,
                    'problem_type': self.problem_type,
                    'sequence_length': self.sequence_length,
                    'horizon_steps': self.horizon_steps,
                    'epoch': epoch,
                    'train_loss': float(train_loss),
                    'val_loss': float(val_loss),
                    'train_samples': len(X_train),
                    'val_samples': len(X_val),
                    'test_samples': len(X_test),
                }
                
                company_loss_rows.append(row)
                self.loss_curves.append(row)

                if epoch % 10 == 0 or stop:
                    print(f"  Epoch {epoch:03d} - train {train_loss:.5f} | val {val_loss:.5f}")

                if stop:
                    break

            # restore best model weights (like Keras restore_best_weights=True)
            early_stopper.restore(model)

            # summarize train/val loss for overfitting checks
            best_train_loss = np.nan
            best_val_loss = np.nan
            final_train_loss = np.nan
            final_val_loss = np.nan
            if company_loss_rows:
                best_val_loss = min(r['val_loss'] for r in company_loss_rows)
                best_train_loss = min(r['train_loss'] for r in company_loss_rows)
                final_train_loss = company_loss_rows[-1]['train_loss']
                final_val_loss = company_loss_rows[-1]['val_loss']

            # predictions
            y_pred_raw = self._predict(model, test_loader)  # raw/regression or logits

            if self.problem_type == 'regression':
                y_pred_unscaled = target_scaler.inverse_transform(y_pred_raw.reshape(-1,1)).flatten() if target_scaler is not None else y_pred_raw
                mse = mean_squared_error(y_test, y_pred_unscaled)
                mae = mean_absolute_error(y_test, y_pred_unscaled)
                r2  = r2_score(y_test, y_pred_unscaled)

                # directional metrics (derived)
                y_test_dir = (y_reg[test_idx] > 0).astype(int)
                y_pred_dir = (y_pred_unscaled > 0).astype(int)
            else:
                # logits -> probs via sigmoid -> learn best threshold on VAL
                val_logits = self._predict(model, val_loader)
                val_probs = 1.0 / (1.0 + np.exp(-val_logits))
                best_thr, best_thr_score = best_threshold_from_val(y_val, val_probs, metric='mcc')
                val_pred_dir = (val_probs >= best_thr).astype(int)
                val_precision = precision_score(y_val, val_pred_dir, zero_division=0)
                val_recall = recall_score(y_val, val_pred_dir, zero_division=0)
                val_f1 = f1_score(y_val, val_pred_dir, zero_division=0)
                val_mcc = matthews_corrcoef(y_val, val_pred_dir)
                val_directional_accuracy = (y_val == val_pred_dir).mean()
                probs = 1.0 / (1.0 + np.exp(-y_pred_raw))
                y_pred_dir = (probs >= best_thr).astype(int)
                y_test_dir = y_test
                mse = mae = r2 = np.nan

            precision = precision_score(y_test_dir, y_pred_dir, zero_division=0)
            recall    = recall_score(y_test_dir, y_pred_dir, zero_division=0)
            f1        = f1_score(y_test_dir, y_pred_dir, zero_division=0)
            mcc       = matthews_corrcoef(y_test_dir, y_pred_dir)
            directional_accuracy = np.mean(y_test_dir == y_pred_dir)

            result = {
                'company': company_name,
                'sector': sector,
                'model_type': self.model_type,
                'problem_type': self.problem_type,
                'horizon_steps': self.horizon_steps,
                'mse': mse,
                'mae': mae,
                'r2': r2,
                'mcc': mcc,
                'f1': f1,
                'precision': precision,
                'recall': recall,
                'directional_accuracy': directional_accuracy,
                'val_directional_accuracy': val_directional_accuracy if self.problem_type == 'classification' else np.nan,
                'val_mcc': val_mcc if self.problem_type == 'classification' else np.nan,
                'val_f1': val_f1 if self.problem_type == 'classification' else np.nan,
                'val_precision': val_precision if self.problem_type == 'classification' else np.nan,
                'val_recall': val_recall if self.problem_type == 'classification' else np.nan,
                'n_samples': int(X_raw.shape[0]),
                'train_samples': int(X_train.shape[0]),
                'val_samples': int(X_val.shape[0]),
                'test_samples': int(X_test.shape[0]),
                'epochs_trained': epochs_trained
            }
            if self.problem_type == 'classification':
                result['best_threshold'] = best_thr
                result['best_threshold_metric'] = best_thr_score

            if self.problem_type == 'regression':
                print(f"  Regression -> MSE: {mse:.6f}, MAE: {mae:.6f}, R²: {r2:.4f}")
            elif self.problem_type == 'classification':
                print(f"  Classification -> best τ={best_thr:.3f} (val F1={best_thr_score:.4f})")
            print(f"  Directional -> Accuracy: {directional_accuracy:.4f}, MCC: {mcc:.4f}, F1: {f1:.4f}")

            # explicit cleanup (PyTorch handles this, but keeps parity with Enrique2025)
            del model
            torch.cuda.empty_cache()

            return result

        except Exception as e:
            print(f"Error processing {company_name}: {str(e)}")
            torch.cuda.empty_cache()
            return None

    def run_pipeline(self):
        company_col = None
        for col_name in ['ticker', 'company', 'symbol']:
            if col_name in self.df.columns:
                company_col = col_name
                break
        if company_col is None:
            company_col = self.df.columns[0]
            print(f"Warning: Using '{company_col}' as company identifier column")

        companies = self.df[company_col].unique()
        print(f"Processing {len(companies)} companies with {self.model_type} model...")
        print(f"Problem type: {self.problem_type}")
        print(f"Sequence length: {self.sequence_length}")
        print(f"Features: {self.feature_columns}")

        successful_companies = 0
        for i, company in enumerate(companies, 1):
            print(f"\n[{i}/{len(companies)}] Processing {company}...")
            company_data = self.df[self.df[company_col] == company].copy()
            sector = company_data['sector'].iloc[0] if 'sector' in company_data.columns else 'Unknown'
            result = self.process_company(company, company_data, sector)
            if result:
                self.results.append(result)
                successful_companies += 1

        print(f"\n{'='*80}")
        print(f"Pipeline completed: {successful_companies}/{len(companies)} companies processed successfully")
        print(f"{'='*80}")

        if self.results:
            self.results_df = pd.DataFrame(self.results)
            return self.results_df
        else:
            print("No companies were processed successfully!")
            return pd.DataFrame()


    def analyze_results(self):
        if not hasattr(self, 'results_df') or self.results_df.empty:
            print("No results to analyze!")
            return None

        df = self.results_df
        analysis = {}

        print("" + "="*80)
        print("STOCK PREDICTION PIPELINE RESULTS")
        print("="*80)
        print(f"Model: {self.model_type} | Problem: {self.problem_type}")
        print(f"Companies analyzed: {len(df)}")
        print(f"Average samples per company: {df['n_samples'].mean():.0f}")

        print("" + "="*50)
        print("OVERALL PERFORMANCE")
        print("="*50)
        if self.problem_type == 'regression':
            print(f"Mean Squared Error:     {df['mse'].mean():.6f} (±{df['mse'].std():.6f})")
            print(f"Mean Absolute Error:    {df['mae'].mean():.6f} (±{df['mae'].std():.6f})")
            print(f"R² Score:              {df['r2'].mean():.4f} (±{df['r2'].std():.4f})")
        if self.problem_type == 'multiclass' and 'micro_accuracy' in df.columns:
            print(f"Micro Accuracy:         {df['micro_accuracy'].mean():.4f} (±{df['micro_accuracy'].std():.4f})")
            print(f"Macro F1 Score:         {df['macro_f1'].mean():.4f} (±{df['macro_f1'].std():.4f})")
            if 'expected_return_mean' in df.columns:
                print(f"Expected Return:        {df['expected_return_mean'].mean():.6f} (±{df['expected_return_mean'].std():.4f})")

        print(f"Directional Accuracy:   {df['directional_accuracy'].mean():.4f} (±{df['directional_accuracy'].std():.4f})")
        print(f"Matthews Correlation:   {df['mcc'].mean():.4f} (±{df['mcc'].std():.4f})")
        print(f"F1 Score:              {df['f1'].mean():.4f} (±{df['f1'].std():.4f})")
        print(f"Precision:             {df['precision'].mean():.4f} (±{df['precision'].std():.4f})")
        print(f"Recall:                {df['recall'].mean():.4f} (±{df['recall'].std():.4f})")

        if self.problem_type == 'multiclass' and 'expected_return_mean' in df.columns:
            print("" + "="*50)
            print("TOP 10 BY EXPECTED RETURN (mean)")
            print("="*50)
            top_er = df.nlargest(10, 'expected_return_mean')
            for _, row in top_er.iterrows():
                print(f"{row['company']:<20} | {row['sector']:<15} | E[r]_mean: {row['expected_return_mean']:.4e} | Macro-F1: {row['macro_f1']:.3f}")

        if 'sector' in df.columns and df['sector'].nunique() > 1:
            print("" + "="*50)
            print("PERFORMANCE BY SECTOR")
            print("="*50)
            sector_stats = df.groupby('sector').agg({
                'directional_accuracy': ['mean', 'std', 'count'],
                'mcc': ['mean', 'std'],
                'r2': 'mean' if self.problem_type == 'regression' else lambda x: np.nan,
                'mae': 'mean' if self.problem_type == 'regression' else lambda x: np.nan
            }).round(4)
            sector_stats.columns = ['_'.join(col).strip() if col[1] else col[0] for col in sector_stats.columns]
            sector_stats = sector_stats.sort_values('directional_accuracy_mean', ascending=False)
            for sector, row in sector_stats.iterrows():
                print(f"{sector:<20} | Acc: {row['directional_accuracy_mean']:.3f}±{row['directional_accuracy_std']:.3f} | "
                      f"MCC: {row['mcc_mean']:.3f} | Companies: {int(row['directional_accuracy_count'])}")

        print("" + "="*50)
        print("TOP 10 PERFORMERS (by Directional Accuracy)")
        print("="*50)
        top_performers = df.nlargest(10, 'directional_accuracy')
        for _, row in top_performers.iterrows():
            print(f"{row['company']:<20} | {row['sector']:<15} | "
                  f"Acc: {row['directional_accuracy']:.3f} | MCC: {row['mcc']:.3f}")

        return analysis

    def save_results(self, results, output_dir='results/benchmarking'):
        if results is not None and not results.empty:
            model_name = self.model_type

            if self.problem_type == 'regression':
                out_dir = os.path.join(output_dir, 'regression')
            elif self.problem_type == 'classification':
                out_dir = os.path.join(output_dir, 'classification')
            else:
                out_dir = os.path.join(output_dir, 'multiclass')

            os.makedirs(out_dir, exist_ok=True)

            output_path = os.path.join(out_dir, f"{model_name}.csv")

            results.to_csv(output_path, index=False)
            print(f"Results saved to {output_path}")
        else:
            print("No results to save.")
            
    def get_loss_curves_df(self):
        if not self.loss_curves:
            print("No loss curves logged yet.")
            return pd.DataFrame()
        return pd.DataFrame(self.loss_curves)

    def save_loss_curves(self, out_path='results/benchmarking/'):
        df = self.get_loss_curves_df()
        if df.empty:
            print("No loss curves to save.")
            return
        if self.problem_type == 'regression':
            out_path = os.path.join(out_path, 'regression', f"{self.model_type}_loss_curves.csv")
        elif self.problem_type == 'classification':
            out_path = os.path.join(out_path, 'classification', f"{self.model_type}_loss_curves.csv")
        else:
            out_path = os.path.join(out_path, 'multiclass', f"{self.model_type}_loss_curves.csv")
            
        os.makedirs(os.path.dirname(out_path), exist_ok=True)
        
        df.to_csv(out_path, index=False)
        print(f"Loss curves saved to {out_path}")

    def get_feature_importance_analysis(self):
        print("Feature importance analysis not implemented yet.")
        print("Consider implementing SHAP values or permutation importance for better insights.")
        return None

## Data Preparation

In [6]:
master_df = pd.read_parquet('../data/dataset/ta_nlp_sector.parquet')

In [7]:
master_df.columns

Index(['date', 'open', 'high', 'low', 'close', 'adj_close', 'volume', 'ticker',
       'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9',
       'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3',
       'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'ret_1d',
       'roll_ret_1d', 'roll_ret_5d', 'roll_ret_20d', 'text', 'sentiment',
       'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy',
       'emotion_neutral', 'emotion_sadness', 'emotion_surprize',
       'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct',
       'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct',
       'emotion_surprize_pct', 'positive_emotion', 'negative_emotion',
       'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct',
       'uncertainty_emotion_pct', 'stance_label', 'finbert_label',
       'stance_score', 'finbert_score', 'finbert_up', 'finbert_down',
       'finbert_neutral', 'sector', 'company_name', 'sector_open_mean',
       'sector_high_mean', 'sector_low_mean', 'sector_close_mean',
       'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d',
       'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector',
       'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector',
       'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector',
       'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower',
       'market_close', 'sector_rel_strength', 'sector_dispersion_1d'],
      dtype='object')

In [8]:
master_df

,date,open,high,low,close,adj_close,volume,ticker,ema_12,ema_26,...,macd_12_26_9_sector,macdh_12_26_9_sector,macds_12_26_9_sector,rsi_14_sector,sector_bb_upper,sector_bb_middle,sector_bb_lower,market_close,sector_rel_strength,sector_dispersion_1d
0,2012-09-04,95.108574,96.448570,94.928574,96.424286,87.121140,91973000.0,AAPL,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1464.800169,NaN,NaN
1,2012-09-05,96.510002,96.621429,95.657143,95.747147,86.509338,84093800.0,AAPL,NaN,NaN,...,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,1481.232189,NaN,0.006548
2,2012-09-06,96.167145,96.898575,95.828575,96.610001,87.288956,97799100.0,AAPL,NaN,NaN,...,NaN,NaN,NaN,28.755774,NaN,NaN,NaN,1502.627054,NaN,0.006476
3,2012-09-07,96.864288,97.497147,96.538574,97.205711,87.827171,82416600.0,AAPL,NaN,NaN,...,NaN,NaN,NaN,28.562466,NaN,NaN,NaN,1506.971629,NaN,0.008604
4,2012-09-10,97.207146,97.612854,94.585716,94.677139,85.542564,121999500.0,AAPL,NaN,NaN,...,NaN,NaN,NaN,22.507443,NaN,NaN,NaN,1503.735325,NaN,0.012007
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108587,2017-08-28,76.900002,76.940002,76.260002,76.470001,76.470001,8229700.0,XOM,77.187452,78.267858,...,-0.111192,0.016355,-0.127548,53.634155,63.049962,61.01430,58.978638,3101.328695,-0.007883,0.005228
108588,2017-08-29,76.209999,76.489998,76.080002,76.449997,76.449997,7060400.0,XOM,77.073998,78.133202,...,-0.067027,0.048417,-0.115443,54.205103,62.862103,60.94445,59.026797,3102.507723,-0.016661,0.002030
108589,2017-08-30,76.239998,76.449997,76.059998,76.099998,76.099998,8218000.0,XOM,76.924151,77.982594,...,-0.037643,0.062240,-0.099883,53.126723,62.639604,60.86875,59.097896,3128.753695,-0.017629,0.004873
108590,2017-08-31,76.269997,76.489998,76.050003,76.330002,76.330002,15641700.0,XOM,76.832744,77.860180,...,0.013408,0.090633,-0.077225,57.342960,62.525437,60.83190,59.138363,3141.201722,-0.008376,0.006185
108591,2017-09-01,76.370003,76.849998,76.320000,76.570000,76.570000,7340800.0,XOM,76.792322,77.764611,...,0.088512,0.132590,-0.044078,62.040301,62.426369,60.80760,59.188831,3136.813139,-0.001766,0.007085

In [9]:
columns_to_check = [
                    'sentiment',
                    
                    'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy',
                    'emotion_neutral', 'emotion_sadness', 'emotion_surprize',
                    'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct',
                    'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct',
                    'emotion_surprize_pct', 
                    
                    'positive_emotion', 'negative_emotion','uncertainty_emotion', 
                    'positive_emotion_pct', 'negative_emotion_pct','uncertainty_emotion_pct', 
                    
                    'stance_label', 'stance_score', 
                    
                    'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down',
                    'finbert_neutral', 
                    
                    'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean',
                    'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d',
                    'sector_ret_20d', 'sector_range', 'sector_vol_20d', 
                    
                    'ema_12_sector','ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector',
                    'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector',
                    'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower',
                    'market_close', 'sector_rel_strength', 'sector_dispersion_1d'
                ]

print(f"Initial master_df shape: {master_df.shape}")

master_df = master_df.dropna(subset=columns_to_check)

print(f"After dropping NaNs in selected columns, master_df shape: {master_df.shape}")

master_df.reset_index(drop=True, inplace=True)

display(master_df)

Initial master_df shape: (108592, 80)
After dropping NaNs in selected columns, master_df shape: (104476, 80)

,date,open,high,low,close,adj_close,volume,ticker,ema_12,ema_26,...,macd_12_26_9_sector,macdh_12_26_9_sector,macds_12_26_9_sector,rsi_14_sector,sector_bb_upper,sector_bb_middle,sector_bb_lower,market_close,sector_rel_strength,sector_dispersion_1d
0,2012-11-14,77.928574,78.207146,76.597145,76.697144,69.613815,119292600.0,AAPL,80.708033,84.949698,...,-0.913108,-0.181794,-0.731314,27.619972,63.948320,61.465736,58.983152,1484.350654,-0.003089,0.006800
1,2012-11-15,76.790001,77.071426,74.660004,75.088570,68.153778,197477700.0,AAPL,79.843501,84.219244,...,-0.926239,-0.155940,-0.770299,32.479352,63.646173,61.261193,58.876213,1484.574993,0.002003,0.019838
2,2012-11-16,75.028572,75.714287,72.250000,75.382858,68.420891,316723400.0,AAPL,79.157248,83.564697,...,-0.892113,-0.097452,-0.794662,37.450172,63.236926,61.078872,58.920817,1497.780485,0.010276,0.010265
3,2012-11-19,77.244286,81.071426,77.125717,80.818573,73.354591,205829400.0,AAPL,79.412836,83.361280,...,-0.733193,0.049174,-0.782368,51.350390,63.001827,61.010079,59.018330,1506.128807,0.024682,0.018850
4,2012-11-20,81.701431,81.707146,79.225716,80.129997,72.729614,160688500.0,AAPL,79.523169,83.121926,...,-0.579416,0.162361,-0.741778,53.267164,62.959435,60.996029,59.032623,1508.629302,0.025531,0.007554
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104471,2017-08-28,76.900002,76.940002,76.260002,76.470001,76.470001,8229700.0,XOM,77.187452,78.267858,...,-0.111192,0.016355,-0.127548,53.634155,63.049962,61.014300,58.978638,3101.328695,-0.007883,0.005228
104472,2017-08-29,76.209999,76.489998,76.080002,76.449997,76.449997,7060400.0,XOM,77.073998,78.133202,...,-0.067027,0.048417,-0.115443,54.205103,62.862103,60.944450,59.026797,3102.507723,-0.016661,0.002030
104473,2017-08-30,76.239998,76.449997,76.059998,76.099998,76.099998,8218000.0,XOM,76.924151,77.982594,...,-0.037643,0.062240,-0.099883,53.126723,62.639604,60.868750,59.097896,3128.753695,-0.017629,0.004873
104474,2017-08-31,76.269997,76.489998,76.050003,76.330002,76.330002,15641700.0,XOM,76.832744,77.860180,...,0.013408,0.090633,-0.077225,57.342960,62.525437,60.831900,59.138363,3141.201722,-0.008376,0.006185
104475,2017-09-01,76.370003,76.849998,76.320000,76.570000,76.570000,7340800.0,XOM,76.792322,77.764611,...,0.088512,0.132590,-0.044078,62.040301,62.426369,60.807600,59.188831,3136.813139,-0.001766,0.007085

In [10]:
print(master_df.columns)

Index(['date', 'open', 'high', 'low', 'close', 'adj_close', 'volume', 'ticker',
       'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9',
       'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3',
       'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'ret_1d',
       'roll_ret_1d', 'roll_ret_5d', 'roll_ret_20d', 'text', 'sentiment',
       'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy',
       'emotion_neutral', 'emotion_sadness', 'emotion_surprize',
       'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct',
       'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct',
       'emotion_surprize_pct', 'positive_emotion', 'negative_emotion',
       'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct',
       'uncertainty_emotion_pct', 'stance_label', 'finbert_label',
       'stance_score', 'finbert_score', 'finbert_up', 'finbert_down',
       'finbert_neutral', 'sector', 'company_name', 'sector_open_mean',
       'sector_high_mean', 'sector_low_mean', 'sector_close_mean',
       'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d',
       'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector',
       'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector',
       'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector',
       'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower',
       'market_close', 'sector_rel_strength', 'sector_dispersion_1d'],
      dtype='object')

In [11]:
feature_columns = [
    'open', 'high', 'low', 'close', 'volume',
    # 'roll_ret_1d', 'roll_ret_5d', 
    # 'roll_ret_20d',
    
    'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9',
    'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3',
    'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv',
]

new_indicator_columns = [
    # 'sentiment',
                    
    # 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy',
    # 'emotion_neutral', 'emotion_sadness', 'emotion_surprize',
    # 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct',
    # 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct',
    # 'emotion_surprize_pct', 
    
    # 'positive_emotion', 'negative_emotion','uncertainty_emotion', 
    # 'positive_emotion_pct', 'negative_emotion_pct','uncertainty_emotion_pct', 
    
    # 'stance_label', 'stance_score', 
    
    # 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down',
    # 'finbert_neutral', 
    
    # 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean',
    # 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d',
    # 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 
    
    # 'ema_12_sector','ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector',
    # 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector',
    # 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower',
    # 'market_close', 'sector_rel_strength', 'sector_dispersion_1d'
]

# feature_columns.extend(new_indicator_columns)



sequence_length=12



all_pipelines = {}
all_results_dfs = {}
all_analyses = {}
fixed_bucket_edges = np.array([-0.08, -0.03, -0.01, 0.0, 0.01, 0.03, 0.08], dtype=float)
n_classes = len(fixed_bucket_edges) - 1
ordinal_head = 'corn'

In [12]:
print(master_df.shape)
master_df = master_df.dropna(subset=feature_columns).sort_values(['ticker','date'])
print(master_df.shape)

(104476, 80)
(104220, 80)

## Pipeline Execution

In [13]:
# print(f"\n{'='*25}\n  RUNNING PIPELINE FOR: GRU\n{'='*25}\n")

# pipeline_GRU = StockPredictionPipeline(
#     df=master_df,
#     feature_columns=feature_columns,
#     model_type='GRU',
#     sequence_length=sequence_length,
#     problem_type='classification',
#     horizon_steps=1,
#     n_classes=n_classes,
#     ordinal_head=ordinal_head,
#     fixed_bucket_edges=fixed_bucket_edges
# )

# results_GRU = pipeline_GRU.run_pipeline()

# loss_df = pipeline_GRU.get_loss_curves_df()

# pipeline_GRU.save_loss_curves('results/benchmarking/')

# if results_GRU is not None and not results_GRU.empty:
#     analysis_GRU = pipeline_GRU.analyze_results()
#     pipeline_GRU.save_results(results_GRU, output_dir='results/benchmarking/')
#     all_pipelines["GRU"] = pipeline_GRU
#     all_results_dfs["GRU"] = results_GRU
#     all_analyses["GRU"] = analysis_GRU

#     print("\nDisplaying first 5 rows of GRU results:")
#     display(results_GRU.head())
# else:
#     print(f"\n[FAILED] Pipeline for GRU did not produce any results.")

# del pipeline_GRU

In [14]:
sentinemt_columns = [
    'sentiment',
]

emotion_columns = [
    'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy',
    'emotion_neutral', 'emotion_sadness', 'emotion_surprize',
    'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct',
    'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct',
    'emotion_surprize_pct',
]

unified_emotion_columns = [
    'positive_emotion', 'negative_emotion','uncertainty_emotion',
    'positive_emotion_pct', 'negative_emotion_pct','uncertainty_emotion_pct',
]

stance_columns = [
    'stance_label', 'stance_score',
]

finbert_columns = [
    'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down',
    'finbert_neutral',
]

sector_columns = ['sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean',
                  'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d',
                  'sector_ret_20d', 'sector_range', 'sector_vol_20d', 
                  
                  'ema_12_sector','ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector',
                  'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector',
                  'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower',
                  'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

In [15]:
try:
    import optuna
except ImportError:
    import sys
    !{sys.executable} -m pip install optuna
    import optuna
    
from pathlib import Path
from datetime import datetime
    
# Define feature sets to test
feature_sets = {
    'base': feature_columns,
    # 'sentinment' : feature_columns + sentinemt_columns,
    # 'emotion' : feature_columns + emotion_columns,
    # 'unified_emotion': feature_columns + unified_emotion_columns,
    # 'finbert': feature_columns + finbert_columns,
    # 'all_nlp': feature_columns + sentinemt_columns + emotion_columns + unified_emotion_columns + stance_columns + finbert_columns,
    # 'sector': feature_columns + sector_columns,
    # 'sector_sentiment': feature_columns + sector_columns + sentinemt_columns,
    # 'sector_emotion': feature_columns + sector_columns + emotion_columns,
    # 'sector_unified_emotion': feature_columns + sector_columns + unified_emotion_columns,
    # 'sector_finbert': feature_columns + sector_columns + finbert_columns,
    # 'sector_all_nlp': feature_columns + sector_columns + sentinemt_columns + emotion_columns + unified_emotion_columns + stance_columns + finbert_columns,
}

def objective(trial):
    params = {
        'problem_type': 'regression',  # or 'classification'
        'feature_set': trial.suggest_categorical('feature_set', list(feature_sets.keys())),
        'model_type': trial.suggest_categorical('model_type', ['LSTM', 'BiLSTM', 'GRU', 'BiGRU']),
        'sequence_length': trial.suggest_int('sequence_length', 6, 36, step=6),
        'horizon_steps': trial.suggest_categorical('horizon_steps', [1]),
        'hidden1': trial.suggest_categorical('hidden1', [64, 128, 256]),
        'hidden2': trial.suggest_categorical('hidden2', [32, 64, 128]),
        'num_layers': trial.suggest_categorical('num_layers', [1, 2]),
        'inter_rnn_drop': trial.suggest_float('inter_rnn_drop', 0.0, 0.4, step=0.1),
        'dropout': trial.suggest_float('dropout', 0.0, 0.8, step=0.1),
        'batch_size': trial.suggest_categorical('batch_size', [16, 32, 64]),
        'learning_rate': trial.suggest_float('learning_rate', 1e-6, 1e-2, log=True),
        'weight_decay': trial.suggest_float('weight_decay', 1e-7, 1e-3, log=True),
        'lr_patience': trial.suggest_categorical('lr_patience', [5, 7, 10]),
        'lr_factor': trial.suggest_categorical('lr_factor', [0.4, 0.8]),
        'early_stopping_patience': trial.suggest_categorical('early_stopping_patience', [10, 15, 20]),
        'max_epochs': trial.suggest_categorical('max_epochs', [20, 30, 50]),
        'huber_delta': trial.suggest_float('huber_delta', 0.1, 2.0),
        'early_stopping_min_delta': trial.suggest_float('early_stopping_min_delta', 0.0, 0.01),
    }

    selected_features = feature_sets[params['feature_set']]
    missing_cols = [c for c in selected_features if c not in master_df.columns]
    if missing_cols:
        print(f"Missing columns for feature_set={params['feature_set']}: {missing_cols}")
        return -1.0

    pipeline = StockPredictionPipeline(
        df=master_df,
        feature_columns=selected_features,
        model_type=params['model_type'],
        sequence_length=params['sequence_length'],
        problem_type=params['problem_type'],
        horizon_steps=params['horizon_steps'],
        n_classes=n_classes,
        ordinal_head=ordinal_head,
        fixed_bucket_edges=fixed_bucket_edges,
        hidden1=params['hidden1'],
        hidden2=params['hidden2'],
        num_layers=params['num_layers'],
        inter_rnn_drop=params['inter_rnn_drop'],
        dropout=params['dropout'],
        batch_size=params['batch_size'],
        learning_rate=params['learning_rate'],
        weight_decay=params['weight_decay'],
        lr_patience=params['lr_patience'],
        lr_factor=params['lr_factor'],
        early_stopping_patience=params['early_stopping_patience'],
        max_epochs=params['max_epochs'],
        huber_delta=params['huber_delta'],
        early_stopping_min_delta=params['early_stopping_min_delta']
    )

    results_df = pipeline.run_pipeline()
    del pipeline
    torch.cuda.empty_cache()

    if results_df is None or results_df.empty:
        print('[DEBUG] results_df empty or None')
        return -1.0

    print('[DEBUG] results_df shape:', results_df.shape)
    print('[DEBUG] results_df columns:', results_df.columns.tolist())

    # Aggregate validation metrics
    val_f1 = results_df['val_f1'].mean() if 'val_f1' in results_df.columns else np.nan
    if not np.isfinite(val_f1) and 'best_threshold_metric' in results_df.columns:
        val_f1 = results_df['best_threshold_metric'].mean()
    val_mcc = results_df['val_mcc'].mean() if 'val_mcc' in results_df.columns else np.nan
    print('[DEBUG] val_mcc:', val_mcc)
    val_precision = results_df['val_precision'].mean() if 'val_precision' in results_df.columns else np.nan
    val_recall = results_df['val_recall'].mean() if 'val_recall' in results_df.columns else np.nan
    val_dir_acc = results_df['val_directional_accuracy'].mean() if 'val_directional_accuracy' in results_df.columns else np.nan

    trial.set_user_attr('val_f1', float(val_f1))
    trial.set_user_attr('val_mcc', float(val_mcc))
    trial.set_user_attr('val_precision', float(val_precision))
    trial.set_user_attr('val_recall', float(val_recall))
    trial.set_user_attr('val_directional_accuracy', float(val_dir_acc))

    # Primary metric: mean val MCC (classification) or mean MAE (regression)
    if params['problem_type'] == 'classification':
        score = val_mcc
        if not np.isfinite(score):
            return -1.0
        return float(score)
    else:
        # minimize MAE -> maximize negative MAE
        if 'mae' not in results_df.columns:
            return -1.0
        mae = results_df['mae'].mean()
        if not np.isfinite(mae):
            return -1.0
        return float(-mae)


N_TRIALS = 250

# Run study
study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=N_TRIALS, timeout=60*60*8)  # 8 hours max
# Collect results
optuna_results = study.trials_dataframe()
# include user attrs
user_attrs = pd.DataFrame([t.user_attrs for t in study.trials])
optuna_results = pd.concat([optuna_results, user_attrs], axis=1)
optuna_results = optuna_results.sort_values('value', ascending=False)
optuna_results

timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
out_path = f'../results/benchmarking/regression/optuna_tuning_base_1H.csv'
Path('../results/benchmarking/regression').mkdir(parents=True, exist_ok=True)
optuna_results.to_csv(out_path, index=False)
print(f'Saved Optuna results to {out_path}')

[I 2026-02-22 20:38:42,996] A new study created in memory with name: no-name-1a155a8c-8172-4f55-8ba0-6d0c7bb16c19

Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: regression
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.24522 | val 0.36190
  Epoch 020 - train 0.22854 | val 0.36392
  Epoch 021 - train 0.23592 | val 0.35497
  Regression -> MSE: 0.000246, MAE: 0.012477, R²: -0.0232
  Directional -> Accuracy: 0.4474, MCC: 0.0000, F1: 0.6182

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.22244 | val 0.27612
  Epoch 020 - train 0.23161 | val 0.26444
  Epoch 021 - train 0.21883 | val 0.26780
  Regression -> MSE: 0.000705, MAE: 0.019870, R²: -0.0099
  Directional -> Accuracy: 0.6000, MCC: 0.1764, F1: 0.7429

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.24725 | val 0.37797
  Epoch 020 - train 0.22810 | val 0.37746
  Epoch 021 - train 0.22542 | val 0.37872
  Regression -> MSE: 0.000314, MAE: 0.014461, R²: 0.0017
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.6857

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.20839 | val 0.20168
  Epoch 020 - train 0.20631 | val 0.19873
  Epoch 030 - train 0.21067 | val 0.20280
  Epoch 035 - train 0.20742 | val 0.20818
  Regression -> MSE: 0.000388, MAE: 0.015263, R²: -0.0979
  Directional -> Accuracy: 0.5405, MCC: 0.0427, F1: 0.6531

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.23546 | val 0.22570
  Epoch 020 - train 0.24268 | val 0.22402
  Epoch 021 - train 0.23910 | val 0.22391
  Regression -> MSE: 0.000206, MAE: 0.010316, R²: 0.0009
  Directional -> Accuracy: 0.4800, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.24299 | val 0.41193
  Epoch 020 - train 0.21985 | val 0.40922
  Epoch 026 - train 0.21325 | val 0.41361
  Regression -> MSE: 0.000589, MAE: 0.018795, R²: -0.0407
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.23779 | val 0.33562
  Epoch 020 - train 0.23902 | val 0.32220
  Epoch 021 - train 0.24025 | val 0.31757
  Regression -> MSE: 0.000252, MAE: 0.012285, R²: -0.0158
  Directional -> Accuracy: 0.3971, MCC: -0.0366, F1: 0.5591

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.21882 | val 0.25215
  Epoch 020 - train 0.22689 | val 0.26221
  Epoch 021 - train 0.23675 | val 0.25659
  Regression -> MSE: 0.000662, MAE: 0.020421, R²: -0.0842
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.26374 | val 0.45469
  Epoch 020 - train 0.25626 | val 0.45193
  Epoch 021 - train 0.25763 | val 0.44490
  Regression -> MSE: 0.000374, MAE: 0.016023, R²: -0.0025
  Directional -> Accuracy: 0.4375, MCC: 0.0000, F1: 0.6087

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.23887 | val 0.30626
  Epoch 020 - train 0.22217 | val 0.30306
  Epoch 021 - train 0.22517 | val 0.30084
  Regression -> MSE: 0.000247, MAE: 0.011939, R²: -0.0077
  Directional -> Accuracy: 0.5362, MCC: 0.1557, F1: 0.5897

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.20858 | val 0.34250
  Epoch 020 - train 0.22259 | val 0.34068
  Epoch 021 - train 0.21396 | val 0.34148
  Regression -> MSE: 0.000316, MAE: 0.013522, R²: -0.0118
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.24556 | val 0.28266
  Epoch 020 - train 0.23076 | val 0.28422
  Epoch 021 - train 0.25033 | val 0.28560
  Regression -> MSE: 0.000678, MAE: 0.019322, R²: 0.0112
  Directional -> Accuracy: 0.6316, MCC: 0.2812, F1: 0.5714

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.23063 | val 0.24666
  Epoch 020 - train 0.23908 | val 0.24727
  Epoch 021 - train 0.23562 | val 0.24774
  Regression -> MSE: 0.000138, MAE: 0.009063, R²: -0.0032
  Directional -> Accuracy: 0.5476, MCC: 0.2343, F1: 0.6545

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.20717 | val 0.32472
  Epoch 020 - train 0.21060 | val 0.32185
  Epoch 021 - train 0.22351 | val 0.32271
  Regression -> MSE: 0.000224, MAE: 0.010644, R²: 0.0094
  Directional -> Accuracy: 0.5167, MCC: 0.0603, F1: 0.6588

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.22672 | val 0.49683
  Epoch 020 - train 0.22018 | val 0.49742
  Epoch 021 - train 0.20968 | val 0.49977
  Regression -> MSE: 0.000368, MAE: 0.016035, R²: -0.0045
  Directional -> Accuracy: 0.5686, MCC: 0.1115, F1: 0.4500

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.25350 | val 0.25650
  Epoch 020 - train 0.25000 | val 0.24842
  Epoch 021 - train 0.24821 | val 0.24691
  Regression -> MSE: 0.000113, MAE: 0.008258, R²: -0.0428
  Directional -> Accuracy: 0.4348, MCC: -0.1256, F1: 0.0930

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.22838 | val 0.36988
  Epoch 020 - train 0.21838 | val 0.37226
  Epoch 025 - train 0.22359 | val 0.37302
  Regression -> MSE: 0.000180, MAE: 0.010893, R²: -0.1397
  Directional -> Accuracy: 0.4138, MCC: 0.0322, F1: 0.1905

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.23417 | val 0.24865
  Epoch 020 - train 0.23715 | val 0.24911
  Epoch 021 - train 0.22766 | val 0.24651
  Regression -> MSE: 0.000303, MAE: 0.014326, R²: -0.1074
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.22269 | val 0.39418
  Epoch 020 - train 0.22629 | val 0.38577
  Epoch 021 - train 0.22037 | val 0.38148
  Regression -> MSE: 0.000203, MAE: 0.010472, R²: -0.3371
  Directional -> Accuracy: 0.4219, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.24033 | val 0.36468
  Epoch 020 - train 0.24016 | val 0.36350
  Epoch 021 - train 0.24846 | val 0.36167
  Regression -> MSE: 0.000261, MAE: 0.011498, R²: -0.1484
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.23290 | val 0.48935
  Epoch 020 - train 0.25186 | val 0.47708
  Epoch 021 - train 0.23539 | val 0.48309
  Regression -> MSE: 0.000181, MAE: 0.010017, R²: -0.2542
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.23154 | val 0.34303
  Epoch 020 - train 0.22341 | val 0.33758
  Epoch 021 - train 0.22742 | val 0.33947
  Regression -> MSE: 0.000168, MAE: 0.010727, R²: -0.0134
  Directional -> Accuracy: 0.5077, MCC: 0.0000, F1: 0.6735

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.24741 | val 0.28041
  Epoch 020 - train 0.23630 | val 0.27783
  Epoch 021 - train 0.24427 | val 0.27714
  Regression -> MSE: 0.000084, MAE: 0.007103, R²: 0.0317
  Directional -> Accuracy: 0.5439, MCC: 0.0500, F1: 0.6286

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.22702 | val 0.35445
  Epoch 020 - train 0.23391 | val 0.35713
  Epoch 021 - train 0.22188 | val 0.35286
  Regression -> MSE: 0.000213, MAE: 0.011051, R²: -0.0117
  Directional -> Accuracy: 0.4769, MCC: -0.1024, F1: 0.1905

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.21648 | val 0.24899
  Epoch 020 - train 0.21223 | val 0.23534
  Epoch 021 - train 0.21240 | val 0.23355
  Regression -> MSE: 0.000103, MAE: 0.008384, R²: -0.1471
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.23768 | val 0.34792
  Epoch 020 - train 0.21832 | val 0.33888
  Epoch 021 - train 0.24432 | val 0.34100
  Regression -> MSE: 0.000131, MAE: 0.009630, R²: -0.3178
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.24416 | val 0.21695
  Epoch 020 - train 0.22471 | val 0.21407
  Epoch 021 - train 0.23053 | val 0.21299
  Regression -> MSE: 0.000238, MAE: 0.012791, R²: -0.0035
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.24151 | val 0.27329
  Epoch 020 - train 0.23582 | val 0.27077
  Epoch 021 - train 0.23705 | val 0.26962
  Regression -> MSE: 0.000206, MAE: 0.008758, R²: -0.2167
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.22810 | val 0.24845
  Epoch 020 - train 0.23340 | val 0.24384
  Epoch 021 - train 0.21305 | val 0.24294
  Regression -> MSE: 0.000250, MAE: 0.012300, R²: -0.0304
  Directional -> Accuracy: 0.4500, MCC: 0.0000, F1: 0.0000

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.23766 | val 0.41006
  Epoch 020 - train 0.22229 | val 0.40395
  Epoch 021 - train 0.21337 | val 0.40878
  Regression -> MSE: 0.000239, MAE: 0.010238, R²: -0.0141
  Directional -> Accuracy: 0.4762, MCC: 0.0000, F1: 0.6452

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.24510 | val 0.24793
  Epoch 020 - train 0.24692 | val 0.25105
  Epoch 021 - train 0.27408 | val 0.25109
  Regression -> MSE: 0.000138, MAE: 0.008432, R²: 0.0005
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.7077

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.23482 | val 0.31019
  Epoch 020 - train 0.23591 | val 0.30962
  Epoch 021 - train 0.23209 | val 0.30972
  Regression -> MSE: 0.000184, MAE: 0.010164, R²: -0.0043
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.21139 | val 0.32672
  Epoch 020 - train 0.21165 | val 0.31841
  Epoch 021 - train 0.21300 | val 0.31754
  Regression -> MSE: 0.000314, MAE: 0.011963, R²: -0.1815
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.21355 | val 0.27405
  Epoch 020 - train 0.20472 | val 0.28267
  Epoch 021 - train 0.22027 | val 0.28106
  Regression -> MSE: 0.000179, MAE: 0.010266, R²: 0.0213
  Directional -> Accuracy: 0.5581, MCC: 0.2093, F1: 0.6780

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.23069 | val 0.21905
  Epoch 020 - train 0.21772 | val 0.21684
  Epoch 021 - train 0.23695 | val 0.21689
  Regression -> MSE: 0.000357, MAE: 0.011919, R²: -0.0273
  Directional -> Accuracy: 0.5758, MCC: 0.0000, F1: 0.7308

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.25406 | val 0.15083
  Epoch 020 - train 0.24689 | val 0.14910
  Epoch 021 - train 0.25640 | val 0.14894
  Regression -> MSE: 0.000114, MAE: 0.008462, R²: -0.0824
  Directional -> Accuracy: 0.5238, MCC: 0.0000, F1: 0.6875

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.22627 | val 0.31478
  Epoch 020 - train 0.23448 | val 0.31562
  Epoch 021 - train 0.22864 | val 0.31529
  Regression -> MSE: 0.000220, MAE: 0.011251, R²: -0.0002
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.22670 | val 0.42078
  Epoch 020 - train 0.23461 | val 0.41857
  Epoch 021 - train 0.23602 | val 0.41951
  Regression -> MSE: 0.000094, MAE: 0.007561, R²: -0.2691
  Directional -> Accuracy: 0.3913, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.22670 | val 0.16725
  Epoch 020 - train 0.22679 | val 0.16491
  Epoch 021 - train 0.23561 | val 0.16233
  Regression -> MSE: 0.000322, MAE: 0.014476, R²: -0.0340
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.22951 | val 0.29600
  Epoch 020 - train 0.23467 | val 0.29601
  Epoch 021 - train 0.23187 | val 0.29682
  Regression -> MSE: 0.000083, MAE: 0.006968, R²: -0.0604
  Directional -> Accuracy: 0.5135, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.23201 | val 0.28484
  Epoch 020 - train 0.24236 | val 0.28510
  Epoch 021 - train 0.21785 | val 0.28484
  Regression -> MSE: 0.000306, MAE: 0.014435, R²: -0.0179
  Directional -> Accuracy: 0.4000, MCC: -0.2257, F1: 0.1818

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.20811 | val 0.27407
  Epoch 020 - train 0.20764 | val 0.27850
  Epoch 021 - train 0.21956 | val 0.27711
  Regression -> MSE: 0.000102, MAE: 0.007234, R²: -0.0005
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.24076 | val 0.31508
  Epoch 020 - train 0.24959 | val 0.31601
  Epoch 021 - train 0.25769 | val 0.31589
  Regression -> MSE: 0.000184, MAE: 0.010641, R²: -0.0490
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.21330 | val 0.27774
  Epoch 020 - train 0.22186 | val 0.27414
  Epoch 021 - train 0.21671 | val 0.27345
  Regression -> MSE: 0.000238, MAE: 0.012118, R²: -0.0555
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.24235 | val 0.29407
  Epoch 020 - train 0.22817 | val 0.30277
  Epoch 021 - train 0.22973 | val 0.30241
  Regression -> MSE: 0.000094, MAE: 0.007822, R²: -0.0015
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.25346 | val 0.38360
  Epoch 020 - train 0.24505 | val 0.38443
  Epoch 021 - train 0.24107 | val 0.38374
  Regression -> MSE: 0.000168, MAE: 0.010379, R²: -0.0085
  Directional -> Accuracy: 0.4906, MCC: 0.0000, F1: 0.0000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.23157 | val 0.27321
  Epoch 020 - train 0.22781 | val 0.27493
  Epoch 021 - train 0.23311 | val 0.27467
  Regression -> MSE: 0.000127, MAE: 0.009147, R²: -0.0747
  Directional -> Accuracy: 0.4727, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.24745 | val 0.34286

[I 2026-02-22 20:40:24,086] Trial 0 finished with value: -0.011726291989495666 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.5, 'batch_size': 16, 'learning_rate': 8.969758242934265e-06, 'weight_decay': 4.060937782427519e-07, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 50, 'huber_delta': 0.3770651289331417, 'early_stopping_min_delta': 0.007027532284037333}. Best is trial 0 with value: -0.011726291989495666.

  Epoch 020 - train 0.23707 | val 0.34365
  Epoch 021 - train 0.23775 | val 0.34118
  Regression -> MSE: 0.000246, MAE: 0.012743, R²: -0.0243
  Directional -> Accuracy: 0.4833, MCC: 0.0000, F1: 0.6517

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 12
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.22268 | val 0.28616
  Epoch 011 - train 0.22225 | val 0.28767
  Regression -> MSE: 0.000246, MAE: 0.012516, R²: -0.0015
  Directional -> Accuracy: 0.5128, MCC: 0.0100, F1: 0.4412

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 88). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.22689 | val 0.21160
  Epoch 011 - train 0.22482 | val 0.21133
  Regression -> MSE: 0.000705, MAE: 0.019857, R²: -0.0199
  Directional -> Accuracy: 0.4468, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 88). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.24639 | val 0.35057
  Epoch 016 - train 0.23488 | val 0.34986
  Regression -> MSE: 0.000347, MAE: 0.014604, R²: -0.0040
  Directional -> Accuracy: 0.5625, MCC: 0.2031, F1: 0.4324

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.20841 | val 0.23498
  Epoch 011 - train 0.20028 | val 0.23491
  Regression -> MSE: 0.000350, MAE: 0.014523, R²: -0.0160
  Directional -> Accuracy: 0.5132, MCC: -0.0305, F1: 0.6408

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.23671 | val 0.20858
  Epoch 018 - train 0.23272 | val 0.20675
  Regression -> MSE: 0.000201, MAE: 0.010066, R²: -0.0022
  Directional -> Accuracy: 0.5962, MCC: 0.2117, F1: 0.5714

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.21375 | val 0.44889
  Epoch 011 - train 0.22352 | val 0.44347
  Regression -> MSE: 0.000597, MAE: 0.018745, R²: -0.0434
  Directional -> Accuracy: 0.4898, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.24365 | val 0.29603
  Epoch 011 - train 0.24672 | val 0.29573
  Regression -> MSE: 0.000252, MAE: 0.012036, R²: -0.0232
  Directional -> Accuracy: 0.6000, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 88). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 88). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.22991 | val 0.43485
  Epoch 011 - train 0.23503 | val 0.44762
  Regression -> MSE: 0.000618, MAE: 0.019498, R²: -0.0570
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.21951 | val 0.33604
  Epoch 017 - train 0.23788 | val 0.33372
  Regression -> MSE: 0.000355, MAE: 0.015918, R²: -0.0506
  Directional -> Accuracy: 0.3810, MCC: 0.0000, F1: 0.5517

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 88). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 88). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.24311 | val 0.32332
  Epoch 011 - train 0.24118 | val 0.31621
  Regression -> MSE: 0.000244, MAE: 0.011567, R²: -0.0239
  Directional -> Accuracy: 0.5634, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.22072 | val 0.31493
  Epoch 016 - train 0.21301 | val 0.31510
  Regression -> MSE: 0.000364, MAE: 0.014344, R²: -0.1905
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.25252 | val 0.27571
  Epoch 011 - train 0.24128 | val 0.27717
  Regression -> MSE: 0.000673, MAE: 0.019628, R²: -0.0056
  Directional -> Accuracy: 0.5085, MCC: 0.0000, F1: 0.6742

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.24036 | val 0.21697
  Epoch 011 - train 0.23314 | val 0.21632
  Regression -> MSE: 0.000151, MAE: 0.009662, R²: -0.0056
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 88). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.21801 | val 0.28624
  Epoch 019 - train 0.21770 | val 0.28485
  Regression -> MSE: 0.000253, MAE: 0.011918, R²: -0.1263
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.23246 | val 0.56516
  Epoch 011 - train 0.22492 | val 0.57042
  Regression -> MSE: 0.000378, MAE: 0.016470, R²: -0.0064
  Directional -> Accuracy: 0.4717, MCC: 0.0000, F1: 0.6410

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.24520 | val 0.29052
  Epoch 011 - train 0.24000 | val 0.28917
  Regression -> MSE: 0.000109, MAE: 0.008093, R²: -0.0249
  Directional -> Accuracy: 0.4648, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.23429 | val 0.42626
  Epoch 011 - train 0.23889 | val 0.42232
  Regression -> MSE: 0.000160, MAE: 0.009831, R²: 0.0006
  Directional -> Accuracy: 0.6167, MCC: 0.0000, F1: 0.7629

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.24154 | val 0.28302
  Epoch 011 - train 0.23552 | val 0.27864
  Regression -> MSE: 0.000302, MAE: 0.014168, R²: -0.1242
  Directional -> Accuracy: 0.3896, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.21144 | val 0.32254
  Epoch 011 - train 0.20871 | val 0.32195
  Regression -> MSE: 0.000154, MAE: 0.008657, R²: -0.0420
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.7429

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 88). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.23433 | val 0.32413
  Epoch 014 - train 0.24108 | val 0.32382
  Regression -> MSE: 0.000492, MAE: 0.017804, R²: -1.1712
  Directional -> Accuracy: 0.4605, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.22757 | val 0.27108
  Epoch 011 - train 0.23676 | val 0.27183
  Regression -> MSE: 0.000154, MAE: 0.008812, R²: -0.0350
  Directional -> Accuracy: 0.6327, MCC: 0.0000, F1: 0.7750

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 88). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 88). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 88). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.21766 | val 0.27035
  Epoch 011 - train 0.21911 | val 0.27000
  Regression -> MSE: 0.000199, MAE: 0.010777, R²: -0.1259
  Directional -> Accuracy: 0.4925, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.24140 | val 0.27365
  Epoch 011 - train 0.23577 | val 0.27397
  Regression -> MSE: 0.000090, MAE: 0.007294, R²: -0.0738
  Directional -> Accuracy: 0.4237, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.23871 | val 0.27022
  Epoch 011 - train 0.23557 | val 0.26994
  Regression -> MSE: 0.000223, MAE: 0.011276, R²: -0.0191
  Directional -> Accuracy: 0.5224, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.22084 | val 0.22177
  Epoch 011 - train 0.23242 | val 0.22171
  Regression -> MSE: 0.000092, MAE: 0.008110, R²: -0.0045
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.26431 | val 0.16282
  Epoch 011 - train 0.25276 | val 0.16480
  Regression -> MSE: 0.000128, MAE: 0.009286, R²: -0.0156
  Directional -> Accuracy: 0.5833, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.25609 | val 0.44596
  Epoch 011 - train 0.25402 | val 0.44323
  Regression -> MSE: 0.000238, MAE: 0.012719, R²: -0.0006
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.7429

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.23109 | val 0.27199
  Epoch 020 - train 0.23663 | val 0.26899
  Epoch 021 - train 0.23504 | val 0.26946
  Regression -> MSE: 0.000207, MAE: 0.009187, R²: -0.2630
  Directional -> Accuracy: 0.5690, MCC: 0.2351, F1: 0.4444

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.24631 | val 0.17253
  Epoch 011 - train 0.24610 | val 0.17297
  Regression -> MSE: 0.000236, MAE: 0.011957, R²: -0.0057
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.22825 | val 0.34333
  Epoch 011 - train 0.23195 | val 0.34316
  Regression -> MSE: 0.000251, MAE: 0.010508, R²: -0.0014
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.23685 | val 0.32445
  Epoch 011 - train 0.24469 | val 0.32777
  Regression -> MSE: 0.000137, MAE: 0.008370, R²: -0.0309
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.23736 | val 0.31885
  Epoch 011 - train 0.24998 | val 0.32020
  Regression -> MSE: 0.000191, MAE: 0.010454, R²: -0.0118
  Directional -> Accuracy: 0.5098, MCC: -0.0106, F1: 0.6154

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.21587 | val 0.26469
  Epoch 013 - train 0.21346 | val 0.26528
  Regression -> MSE: 0.000290, MAE: 0.011437, R²: -0.1217
  Directional -> Accuracy: 0.5270, MCC: 0.1044, F1: 0.4776

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 88). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.21703 | val 0.20079
  Epoch 011 - train 0.20295 | val 0.20101
  Regression -> MSE: 0.000163, MAE: 0.010154, R²: -0.0050
  Directional -> Accuracy: 0.5128, MCC: 0.1581, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.22786 | val 0.27325
  Epoch 011 - train 0.22661 | val 0.27161
  Regression -> MSE: 0.000184, MAE: 0.010451, R²: -0.0076
  Directional -> Accuracy: 0.5333, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.22749 | val 0.19658
  Epoch 019 - train 0.22545 | val 0.19561
  Regression -> MSE: 0.000366, MAE: 0.012705, R²: -0.0477
  Directional -> Accuracy: 0.5588, MCC: 0.0515, F1: 0.6667

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.27067 | val 0.17374
  Epoch 011 - train 0.26570 | val 0.17602
  Regression -> MSE: 0.000131, MAE: 0.008479, R²: -0.2626
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.23099 | val 0.31308
  Epoch 011 - train 0.23660 | val 0.31368
  Regression -> MSE: 0.000217, MAE: 0.011245, R²: -0.0078
  Directional -> Accuracy: 0.4655, MCC: 0.0000, F1: 0.6353

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.24352 | val 0.37796
  Epoch 011 - train 0.24348 | val 0.38060
  Regression -> MSE: 0.000096, MAE: 0.007700, R²: -0.2087
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 88). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 88). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 88). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 88). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.24012 | val 0.18892
  Epoch 011 - train 0.23862 | val 0.18794
  Regression -> MSE: 0.000346, MAE: 0.015633, R²: -0.0537
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 88). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.24836 | val 0.14916
  Epoch 011 - train 0.25056 | val 0.15149
  Regression -> MSE: 0.000251, MAE: 0.011199, R²: -0.0531
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.7000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 88). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 88). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.24284 | val 0.27617
  Epoch 011 - train 0.24098 | val 0.27601
  Regression -> MSE: 0.000086, MAE: 0.007094, R²: -0.0783
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 88). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 88). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 88). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.24076 | val 0.32355
  Epoch 011 - train 0.22621 | val 0.32063
  Regression -> MSE: 0.000368, MAE: 0.015349, R²: -0.0227
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.24364 | val 0.25753
  Epoch 011 - train 0.24707 | val 0.25525
  Regression -> MSE: 0.000097, MAE: 0.007224, R²: -0.0001
  Directional -> Accuracy: 0.6000, MCC: 0.1673, F1: 0.7000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.27320 | val 0.34745
  Epoch 011 - train 0.26713 | val 0.34973
  Regression -> MSE: 0.000188, MAE: 0.010747, R²: -0.0376
  Directional -> Accuracy: 0.3659, MCC: 0.0000, F1: 0.5357

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.22386 | val 0.32529
  Epoch 011 - train 0.22203 | val 0.32198
  Regression -> MSE: 0.000218, MAE: 0.011557, R²: 0.0073
  Directional -> Accuracy: 0.5439, MCC: 0.0000, F1: 0.7045

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.23287 | val 0.29083
  Epoch 011 - train 0.22960 | val 0.29439
  Regression -> MSE: 0.000094, MAE: 0.007809, R²: -0.0315
  Directional -> Accuracy: 0.4828, MCC: 0.0000, F1: 0.6512

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.24899 | val 0.37282
  Epoch 011 - train 0.24755 | val 0.37272
  Regression -> MSE: 0.000161, MAE: 0.010082, R²: -0.0001
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.23266 | val 0.28887
  Epoch 011 - train 0.23091 | val 0.29368
  Regression -> MSE: 0.000121, MAE: 0.008839, R²: -0.0648
  Directional -> Accuracy: 0.4912, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.24322 | val 0.40915
  Epoch 011 - train 0.24115 | val 0.40574
  Regression -> MSE: 0.000231, MAE: 0.012139, R²: 0.0092
  Directional -> Accuracy: 0.5484, MCC: 0.1370, F1: 0.6410

[I 2026-02-22 20:42:10,394] Trial 1 finished with value: -0.011769943692354347 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 12, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.30000000000000004, 'batch_size': 16, 'learning_rate': 3.1676822834852685e-06, 'weight_decay': 0.0005484893161688419, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 0.3967051016831257, 'early_stopping_min_delta': 0.00971986567378289}. Best is trial 0 with value: -0.011726291989495666.

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: regression
Sequence length: 6
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.34626 | val 1.08321
  Epoch 020 - train 0.34206 | val 1.21056
  Epoch 021 - train 0.33859 | val 1.21231
  Regression -> MSE: 0.000249, MAE: 0.012496, R²: -0.0117
  Directional -> Accuracy: 0.5570, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 82). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.37546 | val 1.16413
  Epoch 020 - train 0.37123 | val 1.13406
  Epoch 021 - train 0.35575 | val 1.12912
  Regression -> MSE: 0.000691, MAE: 0.019519, R²: -0.0201
  Directional -> Accuracy: 0.4375, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 82). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.37995 | val 0.94691
  Epoch 020 - train 0.37981 | val 0.96419
  Epoch 021 - train 0.40122 | val 0.96230
  Regression -> MSE: 0.000370, MAE: 0.015473, R²: -0.0653
  Directional -> Accuracy: 0.4694, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.29263 | val 0.69013
  Epoch 020 - train 0.28959 | val 0.69307
  Epoch 021 - train 0.29799 | val 0.70391
  Regression -> MSE: 0.000481, MAE: 0.017409, R²: -0.3548
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.34841 | val 0.34841
  Epoch 020 - train 0.35197 | val 0.33827
  Epoch 030 - train 0.32485 | val 0.33909
  Epoch 038 - train 0.33569 | val 0.34131
  Regression -> MSE: 0.000218, MAE: 0.010317, R²: -0.0976
  Directional -> Accuracy: 0.6604, MCC: 0.3281, F1: 0.6538

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.36356 | val 2.31837
  Epoch 020 - train 0.36695 | val 2.23097
  Epoch 021 - train 0.34638 | val 2.22749
  Regression -> MSE: 0.000487, MAE: 0.017090, R²: 0.0184
  Directional -> Accuracy: 0.5610, MCC: 0.1701, F1: 0.1000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.38879 | val 0.82841
  Epoch 020 - train 0.37939 | val 0.85198
  Epoch 021 - train 0.39720 | val 0.84620
  Regression -> MSE: 0.000260, MAE: 0.012158, R²: -0.0152
  Directional -> Accuracy: 0.5915, MCC: 0.0317, F1: 0.0645

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 82). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 82). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.35669 | val 0.56503
  Epoch 020 - train 0.30468 | val 0.68145
  Epoch 030 - train 0.31560 | val 0.75185
  Epoch 031 - train 0.31489 | val 0.75173
  Regression -> MSE: 0.000860, MAE: 0.022258, R²: -0.5173
  Directional -> Accuracy: 0.5957, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.37813 | val 0.80047
  Epoch 020 - train 0.35427 | val 0.78543
  Epoch 023 - train 0.34604 | val 0.78900
  Regression -> MSE: 0.000369, MAE: 0.015413, R²: 0.0399
  Directional -> Accuracy: 0.5814, MCC: 0.2288, F1: 0.5909

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 82). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 82). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.40936 | val 1.45017
  Epoch 020 - train 0.36482 | val 1.61513
  Epoch 021 - train 0.37383 | val 1.61848
  Regression -> MSE: 0.000239, MAE: 0.011921, R²: -0.0007
  Directional -> Accuracy: 0.4444, MCC: 0.1032, F1: 0.6078

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.36216 | val 1.07548
  Epoch 020 - train 0.34804 | val 1.15824
  Epoch 021 - train 0.33789 | val 1.15487
  Regression -> MSE: 0.000308, MAE: 0.013551, R²: -0.0043
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.41724 | val 0.68055
  Epoch 020 - train 0.39867 | val 0.74178
  Epoch 021 - train 0.39621 | val 0.74323
  Regression -> MSE: 0.000659, MAE: 0.019215, R²: 0.0005
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.37752 | val 0.75108
  Epoch 020 - train 0.36016 | val 0.76895
  Epoch 021 - train 0.39496 | val 0.76657
  Regression -> MSE: 0.000145, MAE: 0.009239, R²: 0.0144
  Directional -> Accuracy: 0.6222, MCC: 0.2585, F1: 0.6383

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 82). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.31843 | val 0.61520
  Epoch 020 - train 0.32350 | val 0.61868
  Epoch 023 - train 0.32347 | val 0.62039
  Regression -> MSE: 0.000235, MAE: 0.011205, R²: -0.0456
  Directional -> Accuracy: 0.5556, MCC: 0.1366, F1: 0.6410

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.37091 | val 2.10866
  Epoch 020 - train 0.38691 | val 2.46795
  Epoch 021 - train 0.37532 | val 2.47827
  Regression -> MSE: 0.000385, MAE: 0.016637, R²: -0.0057
  Directional -> Accuracy: 0.4815, MCC: 0.0000, F1: 0.6500

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.38278 | val 0.74455
  Epoch 020 - train 0.38286 | val 0.74937
  Epoch 021 - train 0.37457 | val 0.75347
  Regression -> MSE: 0.000106, MAE: 0.007780, R²: -0.0100
  Directional -> Accuracy: 0.5417, MCC: 0.0336, F1: 0.6733

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.37286 | val 1.49367
  Epoch 020 - train 0.35305 | val 1.55362
  Epoch 021 - train 0.35595 | val 1.55726
  Regression -> MSE: 0.000158, MAE: 0.009976, R²: -0.0010
  Directional -> Accuracy: 0.5410, MCC: 0.0947, F1: 0.5758

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.35573 | val 0.89221
  Epoch 020 - train 0.34974 | val 0.92261
  Epoch 021 - train 0.34273 | val 0.92560
  Regression -> MSE: 0.000272, MAE: 0.013146, R²: -0.0038
  Directional -> Accuracy: 0.5641, MCC: 0.0699, F1: 0.6531

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.31636 | val 0.72167
  Epoch 020 - train 0.31691 | val 0.73381
  Epoch 022 - train 0.31667 | val 0.73264
  Regression -> MSE: 0.000249, MAE: 0.012190, R²: -0.6071
  Directional -> Accuracy: 0.4179, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 82). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.39284 | val 0.82401
  Epoch 020 - train 0.34905 | val 0.81779
  Epoch 022 - train 0.35458 | val 0.81507
  Regression -> MSE: 0.000352, MAE: 0.014255, R²: -0.5196
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.36342 | val 0.69859
  Epoch 020 - train 0.36477 | val 0.70133
  Epoch 022 - train 0.35444 | val 0.70142
  Regression -> MSE: 0.000164, MAE: 0.009533, R²: -0.1004
  Directional -> Accuracy: 0.4800, MCC: 0.2610, F1: 0.2778

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 82). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 82). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 82). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.37728 | val 0.52511
  Epoch 020 - train 0.36696 | val 0.53804
  Epoch 021 - train 0.38994 | val 0.53826
  Regression -> MSE: 0.000204, MAE: 0.010883, R²: -0.1245
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.1053

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.38111 | val 0.69110
  Epoch 020 - train 0.39609 | val 0.69919
  Epoch 021 - train 0.38827 | val 0.69918
  Regression -> MSE: 0.000083, MAE: 0.006822, R²: -0.0025
  Directional -> Accuracy: 0.5667, MCC: -0.0388, F1: 0.7174

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.38260 | val 0.65672
  Epoch 020 - train 0.37828 | val 0.63731
  Epoch 021 - train 0.35907 | val 0.63678
  Regression -> MSE: 0.000226, MAE: 0.011200, R²: -0.0476
  Directional -> Accuracy: 0.5294, MCC: 0.0647, F1: 0.1579

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.31848 | val 0.29497
  Epoch 020 - train 0.30695 | val 0.31748
  Epoch 023 - train 0.31997 | val 0.31728
  Regression -> MSE: 0.000103, MAE: 0.008206, R²: -0.1460
  Directional -> Accuracy: 0.5345, MCC: 0.1519, F1: 0.4000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.42842 | val 0.24344
  Epoch 020 - train 0.37256 | val 0.27416
  Epoch 021 - train 0.37225 | val 0.27691
  Regression -> MSE: 0.000128, MAE: 0.009351, R²: -0.0242
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.39704 | val 0.67719
  Epoch 020 - train 0.36524 | val 0.60328
  Epoch 021 - train 0.38228 | val 0.60690
  Regression -> MSE: 0.000328, MAE: 0.014394, R²: -0.1269
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.39855 | val 0.67396
  Epoch 020 - train 0.39555 | val 0.67474
  Epoch 021 - train 0.38093 | val 0.67434
  Regression -> MSE: 0.000164, MAE: 0.007776, R²: -0.0157
  Directional -> Accuracy: 0.5593, MCC: 0.0000, F1: 0.7174

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.39846 | val 0.46354
  Epoch 020 - train 0.41115 | val 0.58913
  Epoch 021 - train 0.39507 | val 0.59158
  Regression -> MSE: 0.000231, MAE: 0.011855, R²: -0.0018
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.6866

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.39101 | val 0.64562
  Epoch 020 - train 0.32328 | val 0.63820
  Epoch 030 - train 0.36636 | val 0.63180
  Epoch 040 - train 0.32546 | val 0.63020
  Epoch 050 - train 0.32501 | val 0.62930
  Regression -> MSE: 0.000261, MAE: 0.011574, R²: -0.0081
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.4390

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.39076 | val 0.74254
  Epoch 020 - train 0.37602 | val 0.75234
  Epoch 021 - train 0.38551 | val 0.75280
  Regression -> MSE: 0.000150, MAE: 0.008909, R²: -0.0721
  Directional -> Accuracy: 0.4565, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.37004 | val 0.66640
  Epoch 020 - train 0.36232 | val 0.67918
  Epoch 023 - train 0.36423 | val 0.68315
  Regression -> MSE: 0.000238, MAE: 0.012115, R²: -0.2792
  Directional -> Accuracy: 0.5192, MCC: 0.0000, F1: 0.6835

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.32190 | val 0.64949
  Epoch 020 - train 0.31248 | val 0.64794
  Epoch 022 - train 0.31723 | val 0.64716
  Regression -> MSE: 0.000316, MAE: 0.011979, R²: -0.2118
  Directional -> Accuracy: 0.4800, MCC: 0.0997, F1: 0.2041

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 82). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.36840 | val 0.43169
  Epoch 020 - train 0.31767 | val 0.42560
  Epoch 027 - train 0.34382 | val 0.44147
  Regression -> MSE: 0.000181, MAE: 0.010624, R²: -0.1177
  Directional -> Accuracy: 0.4878, MCC: 0.0000, F1: 0.6557

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.35182 | val 0.82981
  Epoch 020 - train 0.33359 | val 0.82522
  Epoch 021 - train 0.32259 | val 0.82711
  Regression -> MSE: 0.000212, MAE: 0.011051, R²: 0.0098
  Directional -> Accuracy: 0.5217, MCC: 0.0362, F1: 0.4762

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.34252 | val 0.40136
  Epoch 020 - train 0.33413 | val 0.40745
  Epoch 026 - train 0.31173 | val 0.40594
  Regression -> MSE: 0.000384, MAE: 0.013998, R²: -0.1154
  Directional -> Accuracy: 0.4348, MCC: 0.1033, F1: 0.0488

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.40234 | val 0.32349
  Epoch 020 - train 0.35977 | val 0.33141
  Epoch 023 - train 0.34937 | val 0.33177
  Regression -> MSE: 0.000111, MAE: 0.008038, R²: -0.0948
  Directional -> Accuracy: 0.5556, MCC: 0.1093, F1: 0.5833

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.40589 | val 1.35465
  Epoch 020 - train 0.39445 | val 1.46153
  Epoch 021 - train 0.40274 | val 1.46067
  Regression -> MSE: 0.000211, MAE: 0.010942, R²: 0.0042
  Directional -> Accuracy: 0.5254, MCC: 0.0137, F1: 0.1250

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.36941 | val 1.39116
  Epoch 020 - train 0.34977 | val 1.46025
  Epoch 021 - train 0.37120 | val 1.45585
  Regression -> MSE: 0.000082, MAE: 0.007137, R²: -0.0253
  Directional -> Accuracy: 0.5918, MCC: -0.1149, F1: 0.7436

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 82). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 82). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 82). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 82). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.36969 | val 0.30528
  Epoch 020 - train 0.33987 | val 0.30141
  Epoch 030 - train 0.33787 | val 0.30737
  Epoch 033 - train 0.31839 | val 0.30531
  Regression -> MSE: 0.000358, MAE: 0.016176, R²: -0.1414
  Directional -> Accuracy: 0.3333, MCC: 0.0000, F1: 0.5000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 82). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.39421 | val 0.27935
  Epoch 020 - train 0.38942 | val 0.28355
  Epoch 021 - train 0.38182 | val 0.28400
  Regression -> MSE: 0.000234, MAE: 0.011012, R²: -0.0255
  Directional -> Accuracy: 0.4878, MCC: -0.0538, F1: 0.6182

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 82). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 82). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.35600 | val 0.74896
  Epoch 020 - train 0.35019 | val 0.78633
  Epoch 021 - train 0.34186 | val 0.78780
  Regression -> MSE: 0.000082, MAE: 0.007149, R²: 0.0018
  Directional -> Accuracy: 0.5195, MCC: 0.1162, F1: 0.6783

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 82). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 82). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.43403 | val 0.49245
  Epoch 020 - train 0.39838 | val 0.57257
  Epoch 030 - train 0.39058 | val 0.69397
  Epoch 036 - train 0.36115 | val 0.72154
  Regression -> MSE: 0.000411, MAE: 0.015654, R²: -0.1111
  Directional -> Accuracy: 0.4898, MCC: -0.0061, F1: 0.6377

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.32605 | val 0.55217
  Epoch 020 - train 0.31114 | val 0.59592
  Epoch 029 - train 0.32287 | val 0.60016
  Regression -> MSE: 0.000085, MAE: 0.006865, R²: 0.1077
  Directional -> Accuracy: 0.6170, MCC: 0.2072, F1: 0.6786

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.39135 | val 0.82714
  Epoch 020 - train 0.40484 | val 0.85577
  Epoch 021 - train 0.40046 | val 0.85556
  Regression -> MSE: 0.000196, MAE: 0.010010, R²: -0.0263
  Directional -> Accuracy: 0.6429, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.38202 | val 0.50003
  Epoch 020 - train 0.34258 | val 0.52872
  Epoch 026 - train 0.34681 | val 0.52810
  Regression -> MSE: 0.000244, MAE: 0.012202, R²: -0.1289
  Directional -> Accuracy: 0.5517, MCC: 0.0000, F1: 0.7111

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.35773 | val 1.05362
  Epoch 020 - train 0.34874 | val 0.99893

[I 2026-02-22 20:42:56,111] Trial 2 finished with value: -0.01192065882014951 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 6, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.5, 'batch_size': 16, 'learning_rate': 0.0002735665608301041, 'weight_decay': 0.00012799801041741825, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 50, 'huber_delta': 1.3379759747206312, 'early_stopping_min_delta': 0.0038772831168442214}. Best is trial 0 with value: -0.011726291989495666.

  Epoch 020 - train 0.35798 | val 0.75984
  Epoch 021 - train 0.38926 | val 0.75920
  Regression -> MSE: 0.000244, MAE: 0.012345, R²: -0.0586
  Directional -> Accuracy: 0.5238, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.43094 | val 0.78671
  Epoch 020 - train 0.43749 | val 0.78472
  Regression -> MSE: 0.000248, MAE: 0.012469, R²: -0.0000
  Directional -> Accuracy: 0.5584, MCC: 0.1554, F1: 0.6047

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.43640 | val 0.44555
  Epoch 017 - train 0.44599 | val 0.44957
  Regression -> MSE: 0.000646, MAE: 0.018886, R²: 0.0567
  Directional -> Accuracy: 0.6522, MCC: 0.2923, F1: 0.6923

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.50573 | val 1.01388
  Epoch 012 - train 0.49024 | val 0.98507
  Regression -> MSE: 0.000329, MAE: 0.014589, R²: -0.0615
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.37468 | val 0.43474
  Epoch 016 - train 0.36048 | val 0.64538
  Regression -> MSE: 0.000347, MAE: 0.014521, R²: 0.0070
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.45747 | val 0.51114
  Epoch 020 - train 0.43738 | val 0.44632
  Regression -> MSE: 0.000217, MAE: 0.010792, R²: -0.0670
  Directional -> Accuracy: 0.4902, MCC: -0.0231, F1: 0.5185

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.47783 | val 1.15056
  Epoch 011 - train 0.44965 | val 1.14522
  Regression -> MSE: 0.000551, MAE: 0.018165, R²: 0.0069
  Directional -> Accuracy: 0.4894, MCC: 0.0000, F1: 0.6571

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.44750 | val 0.66367
  Epoch 017 - train 0.45510 | val 0.64663
  Regression -> MSE: 0.000241, MAE: 0.012035, R²: 0.0188
  Directional -> Accuracy: 0.4493, MCC: 0.0208, F1: 0.5476

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.45476 | val 0.66524
  Epoch 018 - train 0.42269 | val 0.69329
  Regression -> MSE: 0.000614, MAE: 0.019531, R²: -0.0273
  Directional -> Accuracy: 0.4773, MCC: 0.0534, F1: 0.5490

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.46718 | val 0.60602
  Epoch 011 - train 0.44347 | val 0.62073
  Regression -> MSE: 0.000382, MAE: 0.015984, R²: 0.0038
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.46843 | val 0.68257
  Epoch 018 - train 0.43772 | val 0.68776
  Regression -> MSE: 0.000243, MAE: 0.012247, R²: -0.0068
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.42687 | val 0.78969
  Epoch 017 - train 0.42463 | val 0.97336
  Regression -> MSE: 0.000317, MAE: 0.013611, R²: -0.0199
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.47969 | val 0.59916
  Epoch 011 - train 0.45368 | val 0.61596
  Regression -> MSE: 0.000672, MAE: 0.019462, R²: 0.0075
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.41376 | val 0.53480
  Epoch 015 - train 0.43128 | val 0.65250
  Regression -> MSE: 0.000140, MAE: 0.009289, R²: -0.0110
  Directional -> Accuracy: 0.5349, MCC: 0.1036, F1: 0.5652

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.40508 | val 0.69766
  Epoch 015 - train 0.38863 | val 0.69062
  Regression -> MSE: 0.000224, MAE: 0.010673, R²: 0.0053
  Directional -> Accuracy: 0.5246, MCC: 0.0690, F1: 0.3556

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.46691 | val 1.34854
  Epoch 020 - train 0.42086 | val 1.36928
  Regression -> MSE: 0.000360, MAE: 0.015900, R²: 0.0046
  Directional -> Accuracy: 0.5962, MCC: 0.1787, F1: 0.5116

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.50405 | val 0.51454
  Epoch 012 - train 0.48475 | val 0.49492
  Regression -> MSE: 0.000106, MAE: 0.007761, R²: 0.0212
  Directional -> Accuracy: 0.5571, MCC: 0.0759, F1: 0.6869

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.43610 | val 1.03463
  Epoch 011 - train 0.43565 | val 1.03489
  Regression -> MSE: 0.000156, MAE: 0.009811, R²: 0.0010
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.47071 | val 0.46808
  Epoch 019 - train 0.42539 | val 0.77767
  Regression -> MSE: 0.000292, MAE: 0.013872, R²: -0.0745
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.39617 | val 0.72712
  Epoch 016 - train 0.37100 | val 0.72769
  Regression -> MSE: 0.000181, MAE: 0.009764, R²: -0.2133
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.47067 | val 0.88905
  Epoch 020 - train 0.44468 | val 0.86459
  Regression -> MSE: 0.000329, MAE: 0.013651, R²: -0.4541
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.47388 | val 0.69141
  Epoch 019 - train 0.47056 | val 0.69427
  Regression -> MSE: 0.000159, MAE: 0.009024, R²: -0.1071
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.43509 | val 0.56447
  Epoch 018 - train 0.42231 | val 0.58083
  Regression -> MSE: 0.000164, MAE: 0.010147, R²: 0.0052
  Directional -> Accuracy: 0.5909, MCC: 0.1826, F1: 0.6087

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.46099 | val 0.65662
  Epoch 013 - train 0.46118 | val 0.65979
  Regression -> MSE: 0.000085, MAE: 0.007061, R²: -0.0015
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.45022 | val 0.65230
  Epoch 020 - train 0.42933 | val 0.65932
  Regression -> MSE: 0.000209, MAE: 0.010984, R²: 0.0116
  Directional -> Accuracy: 0.5303, MCC: 0.0589, F1: 0.5079

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.40155 | val 0.35109
  Epoch 015 - train 0.39011 | val 0.36242
  Regression -> MSE: 0.000100, MAE: 0.008329, R²: -0.0886
  Directional -> Accuracy: 0.4464, MCC: -0.1158, F1: 0.4918

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.56755 | val 0.44681
  Epoch 014 - train 0.50703 | val 0.37702
  Regression -> MSE: 0.000101, MAE: 0.008565, R²: 0.0177
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.49882 | val 0.46245
  Epoch 012 - train 0.45800 | val 0.45428
  Regression -> MSE: 0.000236, MAE: 0.012688, R²: -0.0184
  Directional -> Accuracy: 0.5581, MCC: 0.0269, F1: 0.6780

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.43611 | val 0.59389
  Epoch 012 - train 0.44925 | val 0.59947
  Regression -> MSE: 0.000185, MAE: 0.007977, R²: -0.1104
  Directional -> Accuracy: 0.5439, MCC: 0.3032, F1: 0.3158

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.57104 | val 0.39792
  Epoch 020 - train 0.48680 | val 0.38163
  Regression -> MSE: 0.000238, MAE: 0.011938, R²: -0.0078
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.48248 | val 1.03575
  Epoch 013 - train 0.46539 | val 1.06045
  Regression -> MSE: 0.000224, MAE: 0.009808, R²: 0.0297
  Directional -> Accuracy: 0.5581, MCC: 0.1294, F1: 0.6122

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.50008 | val 0.65312
  Epoch 020 - train 0.45643 | val 1.09342
  Regression -> MSE: 0.000141, MAE: 0.008338, R²: -0.0479
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.48405 | val 0.67189
  Epoch 016 - train 0.44263 | val 0.69802
  Regression -> MSE: 0.000204, MAE: 0.010747, R²: -0.0851
  Directional -> Accuracy: 0.4600, MCC: -0.0296, F1: 0.1818

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.39773 | val 0.60340
  Epoch 018 - train 0.38513 | val 0.61141
  Regression -> MSE: 0.000284, MAE: 0.011074, R²: -0.0848
  Directional -> Accuracy: 0.5479, MCC: 0.1851, F1: 0.4407

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.56131 | val 0.39917
  Epoch 013 - train 0.43040 | val 0.36508
  Regression -> MSE: 0.000162, MAE: 0.010310, R²: 0.0300
  Directional -> Accuracy: 0.5789, MCC: 0.1857, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.42481 | val 0.56869
  Epoch 011 - train 0.40380 | val 0.59565
  Regression -> MSE: 0.000182, MAE: 0.010340, R²: -0.0114
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.43506 | val 0.42208
  Epoch 016 - train 0.42115 | val 0.42464
  Regression -> MSE: 0.000338, MAE: 0.012057, R²: 0.0125
  Directional -> Accuracy: 0.5075, MCC: 0.1239, F1: 0.3529

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.50691 | val 0.24672
  Epoch 011 - train 0.48585 | val 0.23049
  Regression -> MSE: 0.000107, MAE: 0.008112, R²: -0.0152
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.46225 | val 0.80176
  Epoch 016 - train 0.45464 | val 0.80427
  Regression -> MSE: 0.000219, MAE: 0.011235, R²: -0.0030
  Directional -> Accuracy: 0.5614, MCC: 0.1968, F1: 0.6575

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.46272 | val 1.11582
  Epoch 011 - train 0.45051 | val 1.12411
  Regression -> MSE: 0.000089, MAE: 0.007384, R²: -0.1441
  Directional -> Accuracy: 0.4468, MCC: 0.0837, F1: 0.2778

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.44811 | val 0.27971
  Epoch 016 - train 0.44802 | val 0.28221
  Regression -> MSE: 0.000309, MAE: 0.013767, R²: -0.0052
  Directional -> Accuracy: 0.6327, MCC: 0.0000, F1: 0.0000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.42754 | val 0.25298
  Epoch 020 - train 0.46483 | val 0.19542
  Regression -> MSE: 0.000239, MAE: 0.011332, R²: 0.0206
  Directional -> Accuracy: 0.4474, MCC: -0.1192, F1: 0.5116

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.42280 | val 0.60005
  Epoch 014 - train 0.45050 | val 0.59959
  Regression -> MSE: 0.000079, MAE: 0.006965, R²: 0.0236
  Directional -> Accuracy: 0.5200, MCC: 0.0944, F1: 0.6604

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.46819 | val 0.61041
  Epoch 013 - train 0.51058 | val 0.63175
  Regression -> MSE: 0.000313, MAE: 0.014546, R²: -0.0213
  Directional -> Accuracy: 0.5106, MCC: 0.1443, F1: 0.0800

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.47409 | val 0.59893
  Epoch 016 - train 0.53263 | val 0.54623
  Regression -> MSE: 0.000097, MAE: 0.007245, R²: 0.0149
  Directional -> Accuracy: 0.4773, MCC: 0.0045, F1: 0.4103

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.45457 | val 0.72807
  Epoch 012 - train 0.43162 | val 0.73040
  Regression -> MSE: 0.000171, MAE: 0.009714, R²: 0.0039
  Directional -> Accuracy: 0.3878, MCC: -0.0687, F1: 0.5312

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.40348 | val 0.59633
  Epoch 017 - train 0.39373 | val 0.67398
  Regression -> MSE: 0.000222, MAE: 0.011600, R²: 0.0050
  Directional -> Accuracy: 0.6429, MCC: 0.2821, F1: 0.6667

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.45643 | val 0.75549
  Epoch 018 - train 0.44809 | val 1.16824
  Regression -> MSE: 0.000091, MAE: 0.007638, R²: 0.0122
  Directional -> Accuracy: 0.5614, MCC: 0.2479, F1: 0.6753

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.46416 | val 0.99197
  Epoch 011 - train 0.46219 | val 1.02736
  Regression -> MSE: 0.000166, MAE: 0.010358, R²: -0.0109
  Directional -> Accuracy: 0.4259, MCC: -0.1448, F1: 0.3111

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.43467 | val 0.71199
  Epoch 011 - train 0.45077 | val 0.71964
  Regression -> MSE: 0.000128, MAE: 0.009099, R²: -0.1038
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.49648 | val 0.92405

[I 2026-02-22 20:43:55,457] Trial 3 finished with value: -0.011473394984568777 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.8, 'batch_size': 64, 'learning_rate': 0.004517980107682094, 'weight_decay': 5.9452599113053025e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 1.6057114730681976, 'early_stopping_min_delta': 0.003994966715816989}. Best is trial 3 with value: -0.011473394984568777.

  Epoch 016 - train 0.46932 | val 0.96077
  Regression -> MSE: 0.000236, MAE: 0.012274, R²: 0.0030
  Directional -> Accuracy: 0.6066, MCC: 0.2103, F1: 0.5000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: regression
Sequence length: 12
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.11919 | val 0.14935
  Epoch 020 - train 0.11473 | val 0.15123
  Epoch 021 - train 0.11403 | val 0.15131
  Regression -> MSE: 0.000248, MAE: 0.012600, R²: -0.0103
  Directional -> Accuracy: 0.5000, MCC: 0.0188, F1: 0.5185

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 88). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.12134 | val 0.14235
  Epoch 016 - train 0.11803 | val 0.15057
  Regression -> MSE: 0.000696, MAE: 0.019709, R²: -0.0073
  Directional -> Accuracy: 0.5532, MCC: 0.0843, F1: 0.6182

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 88). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.13102 | val 0.19454
  Epoch 020 - train 0.12715 | val 0.19631
  Epoch 021 - train 0.12432 | val 0.19639
  Regression -> MSE: 0.000356, MAE: 0.015180, R²: -0.0305
  Directional -> Accuracy: 0.6458, MCC: 0.3496, F1: 0.5854

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.10321 | val 0.12508
  Epoch 016 - train 0.10098 | val 0.12260
  Regression -> MSE: 0.000362, MAE: 0.014697, R²: -0.0492
  Directional -> Accuracy: 0.4605, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.12559 | val 0.12252
  Epoch 020 - train 0.11900 | val 0.11796
  Epoch 030 - train 0.11394 | val 0.11532
  Regression -> MSE: 0.000194, MAE: 0.009393, R²: 0.0320
  Directional -> Accuracy: 0.6923, MCC: 0.4304, F1: 0.6522

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.11466 | val 0.23809
  Epoch 016 - train 0.11641 | val 0.28915
  Regression -> MSE: 0.000586, MAE: 0.018584, R²: -0.0231
  Directional -> Accuracy: 0.4898, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.12627 | val 0.15010
  Epoch 020 - train 0.12045 | val 0.15030
  Epoch 022 - train 0.12375 | val 0.15046
  Regression -> MSE: 0.000269, MAE: 0.013360, R²: -0.0931
  Directional -> Accuracy: 0.4429, MCC: 0.0523, F1: 0.5618

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 88). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 88). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.12054 | val 0.20442
  Epoch 016 - train 0.11757 | val 0.25639
  Regression -> MSE: 0.000619, MAE: 0.019484, R²: -0.0591
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.11737 | val 0.18648
  Epoch 016 - train 0.11339 | val 0.18525
  Regression -> MSE: 0.000339, MAE: 0.014827, R²: -0.0018
  Directional -> Accuracy: 0.5714, MCC: 0.1132, F1: 0.4706

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 88). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 88). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.11866 | val 0.19294
  Epoch 016 - train 0.11825 | val 0.20805
  Regression -> MSE: 0.000237, MAE: 0.011781, R²: 0.0029
  Directional -> Accuracy: 0.4366, MCC: 0.0000, F1: 0.6078

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.11155 | val 0.25488
  Epoch 016 - train 0.10927 | val 0.28691
  Regression -> MSE: 0.000308, MAE: 0.013562, R²: -0.0070
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.12594 | val 0.14660
  Epoch 016 - train 0.12437 | val 0.14475
  Regression -> MSE: 0.000674, MAE: 0.019530, R²: -0.0061
  Directional -> Accuracy: 0.5085, MCC: 0.0000, F1: 0.6742

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.12595 | val 0.16016
  Epoch 016 - train 0.11939 | val 0.19145
  Regression -> MSE: 0.000150, MAE: 0.009462, R²: -0.0001
  Directional -> Accuracy: 0.5000, MCC: -0.0169, F1: 0.4211

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 88). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.11469 | val 0.16417
  Epoch 020 - train 0.11084 | val 0.17596
  Epoch 021 - train 0.10994 | val 0.17690
  Regression -> MSE: 0.000221, MAE: 0.010647, R²: 0.0154
  Directional -> Accuracy: 0.5645, MCC: 0.1291, F1: 0.5714

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.12483 | val 0.29069
  Epoch 016 - train 0.12140 | val 0.31505
  Regression -> MSE: 0.000377, MAE: 0.016566, R²: -0.0024
  Directional -> Accuracy: 0.4717, MCC: 0.0000, F1: 0.6410

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.12858 | val 0.13422
  Epoch 019 - train 0.12058 | val 0.13636
  Regression -> MSE: 0.000107, MAE: 0.007831, R²: -0.0046
  Directional -> Accuracy: 0.5352, MCC: 0.0000, F1: 0.6972

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.12205 | val 0.34937
  Epoch 016 - train 0.11769 | val 0.31691
  Regression -> MSE: 0.000163, MAE: 0.009758, R²: -0.0162
  Directional -> Accuracy: 0.6167, MCC: 0.0000, F1: 0.7629

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.11985 | val 0.13536
  Epoch 016 - train 0.11546 | val 0.12947
  Regression -> MSE: 0.000286, MAE: 0.012874, R²: -0.0661
  Directional -> Accuracy: 0.6104, MCC: 0.0000, F1: 0.7581

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.10946 | val 0.16847
  Epoch 016 - train 0.10776 | val 0.16707
  Regression -> MSE: 0.000170, MAE: 0.009178, R²: -0.1539
  Directional -> Accuracy: 0.3939, MCC: -0.1143, F1: 0.0476

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 88). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.12902 | val 0.18884
  Epoch 016 - train 0.12352 | val 0.18441
  Regression -> MSE: 0.000253, MAE: 0.011454, R²: -0.1153
  Directional -> Accuracy: 0.4605, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.11996 | val 0.15285
  Epoch 016 - train 0.11860 | val 0.15107
  Regression -> MSE: 0.000171, MAE: 0.009477, R²: -0.1514
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 88). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 88). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 88). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.11966 | val 0.14983
  Epoch 016 - train 0.11303 | val 0.15265
  Regression -> MSE: 0.000193, MAE: 0.010618, R²: -0.0907
  Directional -> Accuracy: 0.4925, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.13384 | val 0.14519
  Epoch 020 - train 0.12691 | val 0.14941
  Epoch 025 - train 0.12482 | val 0.15274
  Regression -> MSE: 0.000123, MAE: 0.008730, R²: -0.4663
  Directional -> Accuracy: 0.4237, MCC: -0.0697, F1: 0.2273

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.12287 | val 0.23398
  Epoch 018 - train 0.11764 | val 0.26591
  Regression -> MSE: 0.000217, MAE: 0.011157, R²: 0.0075
  Directional -> Accuracy: 0.6119, MCC: 0.2354, F1: 0.4583

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.11356 | val 0.09727
  Epoch 020 - train 0.10941 | val 0.09475
  Epoch 030 - train 0.10228 | val 0.09403
  Regression -> MSE: 0.000095, MAE: 0.008078, R²: -0.0338
  Directional -> Accuracy: 0.5614, MCC: 0.1400, F1: 0.5614

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.12686 | val 0.07992
  Epoch 016 - train 0.12111 | val 0.09263
  Regression -> MSE: 0.000137, MAE: 0.009634, R²: -0.0865
  Directional -> Accuracy: 0.4167, MCC: 0.0000, F1: 0.5882

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.12869 | val 0.11100
  Epoch 020 - train 0.12348 | val 0.11127
  Epoch 026 - train 0.12667 | val 0.11576
  Regression -> MSE: 0.000250, MAE: 0.012735, R²: -0.0524
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.7429

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.11768 | val 0.14977
  Epoch 016 - train 0.11571 | val 0.15117
  Regression -> MSE: 0.000185, MAE: 0.007951, R²: -0.1293
  Directional -> Accuracy: 0.5345, MCC: 0.2275, F1: 0.3077

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.12265 | val 0.10065
  Epoch 020 - train 0.11511 | val 0.09767
  Epoch 030 - train 0.11811 | val 0.09826
  Regression -> MSE: 0.000244, MAE: 0.012048, R²: -0.0404
  Directional -> Accuracy: 0.4884, MCC: -0.0426, F1: 0.5600

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.12562 | val 0.19480
  Epoch 016 - train 0.12146 | val 0.19515
  Regression -> MSE: 0.000251, MAE: 0.010547, R²: -0.0013
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.13211 | val 0.16143
  Epoch 020 - train 0.12948 | val 0.16617
  Regression -> MSE: 0.000142, MAE: 0.008435, R²: -0.0677
  Directional -> Accuracy: 0.5333, MCC: 0.0000, F1: 0.6957

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.11891 | val 0.15533
  Epoch 020 - train 0.11515 | val 0.15443
  Epoch 030 - train 0.11440 | val 0.15559
  Regression -> MSE: 0.000242, MAE: 0.012102, R²: -0.2848
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.11180 | val 0.16295
  Epoch 016 - train 0.10545 | val 0.16165
  Regression -> MSE: 0.000265, MAE: 0.010564, R²: -0.0255
  Directional -> Accuracy: 0.5676, MCC: 0.0000, F1: 0.7241

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 88). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.10875 | val 0.11279
  Epoch 016 - train 0.11067 | val 0.11980
  Regression -> MSE: 0.000163, MAE: 0.010139, R²: -0.0010
  Directional -> Accuracy: 0.4872, MCC: -0.0087, F1: 0.6296

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.11309 | val 0.16815
  Epoch 016 - train 0.11393 | val 0.17235
  Regression -> MSE: 0.000199, MAE: 0.011057, R²: -0.0896
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.6364

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.11473 | val 0.11997
  Epoch 018 - train 0.10797 | val 0.12194
  Regression -> MSE: 0.000359, MAE: 0.012930, R²: -0.0277
  Directional -> Accuracy: 0.4265, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.13100 | val 0.08810
  Epoch 020 - train 0.12731 | val 0.08721
  Epoch 030 - train 0.12302 | val 0.08693
  Regression -> MSE: 0.000141, MAE: 0.008821, R²: -0.3581
  Directional -> Accuracy: 0.4545, MCC: -0.1581, F1: 0.0769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.12155 | val 0.16967
  Epoch 016 - train 0.11736 | val 0.16937
  Regression -> MSE: 0.000222, MAE: 0.011415, R²: -0.0327
  Directional -> Accuracy: 0.4655, MCC: 0.0000, F1: 0.6353

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.11606 | val 0.25830
  Epoch 016 - train 0.11604 | val 0.26907
  Regression -> MSE: 0.000087, MAE: 0.007336, R²: -0.0995
  Directional -> Accuracy: 0.4167, MCC: -0.0710, F1: 0.3636

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 88). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 88). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 88). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 88). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.12460 | val 0.09355
  Epoch 020 - train 0.11774 | val 0.09431
  Epoch 025 - train 0.11877 | val 0.09483
  Regression -> MSE: 0.000333, MAE: 0.013596, R²: -0.0151
  Directional -> Accuracy: 0.6750, MCC: 0.2182, F1: 0.1333

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 88). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.13555 | val 0.10380
  Epoch 016 - train 0.13591 | val 0.10424
  Regression -> MSE: 0.000255, MAE: 0.011286, R²: -0.0731
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.7000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 88). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 88). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.11727 | val 0.14605
  Epoch 020 - train 0.11418 | val 0.14762
  Epoch 021 - train 0.11284 | val 0.14813
  Regression -> MSE: 0.000078, MAE: 0.006974, R²: 0.0240
  Directional -> Accuracy: 0.5263, MCC: 0.1179, F1: 0.6727

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 88). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 88). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 88). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.12761 | val 0.19208
  Epoch 016 - train 0.12189 | val 0.19968
  Regression -> MSE: 0.000380, MAE: 0.015449, R²: -0.0558
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.11701 | val 0.15032
  Epoch 016 - train 0.11589 | val 0.15249
  Regression -> MSE: 0.000097, MAE: 0.007216, R²: -0.0021
  Directional -> Accuracy: 0.5778, MCC: 0.1195, F1: 0.7164

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.12473 | val 0.19887
  Epoch 016 - train 0.12214 | val 0.22715
  Regression -> MSE: 0.000182, MAE: 0.010340, R²: -0.0090
  Directional -> Accuracy: 0.3659, MCC: 0.0000, F1: 0.5357

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.11293 | val 0.15785
  Epoch 016 - train 0.11351 | val 0.17234
  Regression -> MSE: 0.000220, MAE: 0.011578, R²: -0.0006
  Directional -> Accuracy: 0.5439, MCC: 0.0000, F1: 0.7045

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.12299 | val 0.20164
  Epoch 016 - train 0.11830 | val 0.20103
  Regression -> MSE: 0.000093, MAE: 0.007805, R²: -0.0234
  Directional -> Accuracy: 0.4828, MCC: 0.0000, F1: 0.6512

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.12968 | val 0.23923
  Epoch 016 - train 0.12778 | val 0.26141
  Regression -> MSE: 0.000162, MAE: 0.010199, R²: -0.0098
  Directional -> Accuracy: 0.4364, MCC: -0.1445, F1: 0.5079

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.11606 | val 0.19764
  Epoch 016 - train 0.11618 | val 0.19772
  Regression -> MSE: 0.000114, MAE: 0.008764, R²: 0.0028
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.12706 | val 0.17742
  Epoch 020 - train 0.12065 | val 0.17215

[I 2026-02-22 20:44:56,651] Trial 4 finished with value: -0.011600150585216677 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 12, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.30000000000000004, 'batch_size': 32, 'learning_rate': 2.7253863575753965e-05, 'weight_decay': 6.528411857653041e-06, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 30, 'huber_delta': 0.1899376286937843, 'early_stopping_min_delta': 0.0010610053426754519}. Best is trial 3 with value: -0.011473394984568777.

  Epoch 030 - train 0.11986 | val 0.17423
  Regression -> MSE: 0.000259, MAE: 0.012550, R²: -0.1106
  Directional -> Accuracy: 0.5161, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: regression
Sequence length: 36
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.38018 | val 0.69357
  Epoch 011 - train 0.36035 | val 0.70354
  Regression -> MSE: 0.000242, MAE: 0.012393, R²: -0.0299
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.6168

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 112). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.40176 | val 0.47690
  Epoch 012 - train 0.37370 | val 0.50905
  Regression -> MSE: 0.000729, MAE: 0.019951, R²: -0.0232
  Directional -> Accuracy: 0.6047, MCC: 0.3252, F1: 0.5641

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for AEP (109 < 112). Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 112). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.39494 | val 0.84654
  Epoch 018 - train 0.35688 | val 0.98137
  Regression -> MSE: 0.000328, MAE: 0.014547, R²: -0.0298
  Directional -> Accuracy: 0.5227, MCC: 0.1439, F1: 0.2222

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.33904 | val 0.39888
  Epoch 014 - train 0.30965 | val 0.39198
  Regression -> MSE: 0.000359, MAE: 0.014667, R²: -0.0073
  Directional -> Accuracy: 0.5556, MCC: 0.0936, F1: 0.6190

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.36166 | val 0.34253
  Epoch 020 - train 0.35012 | val 0.36425
  Regression -> MSE: 0.000196, MAE: 0.009205, R²: 0.0698
  Directional -> Accuracy: 0.7500, MCC: 0.4991, F1: 0.7600

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.33637 | val 0.83011
  Epoch 011 - train 0.33903 | val 0.84157
  Regression -> MSE: 0.000555, MAE: 0.018095, R²: 0.0087
  Directional -> Accuracy: 0.5682, MCC: 0.1690, F1: 0.6667

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.40412 | val 0.54079
  Epoch 020 - train 0.38355 | val 0.57400
  Epoch 021 - train 0.38263 | val 0.56755
  Regression -> MSE: 0.000255, MAE: 0.011999, R²: 0.0007
  Directional -> Accuracy: 0.6212, MCC: 0.2125, F1: 0.1379

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 112). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 112). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.33699 | val 0.59523
  Epoch 011 - train 0.32524 | val 0.58447
  Regression -> MSE: 0.000585, MAE: 0.018870, R²: -0.0101
  Directional -> Accuracy: 0.5897, MCC: 0.1553, F1: 0.5000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.39886 | val 0.65692
  Epoch 011 - train 0.36728 | val 0.66520
  Regression -> MSE: 0.000387, MAE: 0.015899, R²: -0.0152
  Directional -> Accuracy: 0.4565, MCC: 0.1307, F1: 0.6154

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 112). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 112). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 112). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.38402 | val 0.62954
  Epoch 011 - train 0.38655 | val 0.63478
  Regression -> MSE: 0.000246, MAE: 0.012009, R²: 0.0021
  Directional -> Accuracy: 0.4030, MCC: -0.1146, F1: 0.5238

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.35533 | val 0.76280
  Epoch 011 - train 0.35015 | val 0.80570
  Regression -> MSE: 0.000317, MAE: 0.013483, R²: -0.0162
  Directional -> Accuracy: 0.4255, MCC: -0.1317, F1: 0.4490

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.39724 | val 0.52544
  Epoch 012 - train 0.38294 | val 0.54038
  Regression -> MSE: 0.000677, MAE: 0.019322, R²: 0.0256
  Directional -> Accuracy: 0.6000, MCC: 0.1949, F1: 0.6333

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 112). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.39014 | val 0.59736
  Epoch 013 - train 0.36302 | val 0.71359
  Regression -> MSE: 0.000145, MAE: 0.009413, R²: -0.0048
  Directional -> Accuracy: 0.5000, MCC: 0.0089, F1: 0.5385

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 112). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.33892 | val 0.63228
  Epoch 015 - train 0.31350 | val 0.65995
  Regression -> MSE: 0.000228, MAE: 0.010643, R²: 0.0067
  Directional -> Accuracy: 0.5517, MCC: 0.1077, F1: 0.5357

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.37266 | val 1.17244
  Epoch 011 - train 0.38310 | val 1.14795
  Regression -> MSE: 0.000371, MAE: 0.016191, R²: 0.0067
  Directional -> Accuracy: 0.5918, MCC: 0.3222, F1: 0.6774

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.40173 | val 0.50400
  Epoch 011 - train 0.39285 | val 0.49609
  Regression -> MSE: 0.000110, MAE: 0.007901, R²: -0.0024
  Directional -> Accuracy: 0.5075, MCC: -0.0431, F1: 0.6374

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 112). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.37754 | val 0.89890
  Epoch 011 - train 0.34672 | val 0.90195
  Regression -> MSE: 0.000153, MAE: 0.009744, R²: -0.0105
  Directional -> Accuracy: 0.6071, MCC: 0.0000, F1: 0.7556

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.37974 | val 0.49134
  Epoch 013 - train 0.37846 | val 0.48398
  Regression -> MSE: 0.000279, MAE: 0.013115, R²: -0.0078
  Directional -> Accuracy: 0.5890, MCC: 0.0000, F1: 0.7414

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.31293 | val 0.58694
  Epoch 020 - train 0.31455 | val 0.59924
  Regression -> MSE: 0.000180, MAE: 0.009669, R²: -0.1700
  Directional -> Accuracy: 0.4355, MCC: 0.0393, F1: 0.1026

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 112). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.40556 | val 0.75736
  Epoch 020 - train 0.36030 | val 0.74478
  Epoch 026 - train 0.35727 | val 0.74327
  Regression -> MSE: 0.000373, MAE: 0.014913, R²: -0.6408
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.37467 | val 0.60080
  Epoch 013 - train 0.35777 | val 0.60942
  Regression -> MSE: 0.000150, MAE: 0.008527, R²: -0.0107
  Directional -> Accuracy: 0.6000, MCC: 0.1231, F1: 0.7000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 112). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 112). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 112). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.36268 | val 0.51445
  Epoch 015 - train 0.32647 | val 0.53387
  Regression -> MSE: 0.000168, MAE: 0.010520, R²: 0.0152
  Directional -> Accuracy: 0.4921, MCC: 0.0000, F1: 0.6596

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.40128 | val 0.58740
  Epoch 011 - train 0.38620 | val 0.64546
  Regression -> MSE: 0.000088, MAE: 0.007177, R²: 0.0120
  Directional -> Accuracy: 0.5818, MCC: 0.1571, F1: 0.6230

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.40045 | val 0.59216
  Epoch 015 - train 0.39481 | val 0.57367
  Regression -> MSE: 0.000215, MAE: 0.011120, R²: 0.0072
  Directional -> Accuracy: 0.5714, MCC: 0.1376, F1: 0.5263

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.34116 | val 0.33634
  Epoch 020 - train 0.30099 | val 0.34339
  Epoch 024 - train 0.29745 | val 0.32968
  Regression -> MSE: 0.000097, MAE: 0.008045, R²: -0.0713
  Directional -> Accuracy: 0.5660, MCC: 0.2449, F1: 0.4103

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.37640 | val 0.46070
  Epoch 014 - train 0.39335 | val 0.47841
  Regression -> MSE: 0.000087, MAE: 0.007969, R²: 0.0480
  Directional -> Accuracy: 0.5476, MCC: 0.2178, F1: 0.6275

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.42423 | val 0.28183
  Epoch 011 - train 0.36743 | val 0.28446
  Regression -> MSE: 0.000296, MAE: 0.013537, R²: -0.0651
  Directional -> Accuracy: 0.4167, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.40146 | val 0.56100
  Epoch 011 - train 0.39164 | val 0.56038
  Regression -> MSE: 0.000193, MAE: 0.008181, R²: -0.1237
  Directional -> Accuracy: 0.4630, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
Insufficient data for proper time series validation for MDT. Skipping...

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.40170 | val 0.91020
  Epoch 014 - train 0.37090 | val 0.93161
  Regression -> MSE: 0.000238, MAE: 0.010207, R²: 0.0060
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.41218 | val 0.51568
  Epoch 011 - train 0.38567 | val 0.51668
  Regression -> MSE: 0.000148, MAE: 0.008549, R²: -0.0394
  Directional -> Accuracy: 0.5500, MCC: 0.1231, F1: 0.5263

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.38545 | val 0.59241
  Epoch 020 - train 0.34876 | val 0.57803
  Epoch 023 - train 0.34290 | val 0.58880
  Regression -> MSE: 0.000208, MAE: 0.011411, R²: -0.0933
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.31805 | val 0.53961
  Epoch 012 - train 0.31162 | val 0.54390
  Regression -> MSE: 0.000309, MAE: 0.011673, R²: -0.1629
  Directional -> Accuracy: 0.5143, MCC: 0.1300, F1: 0.3462

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 112). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.34709 | val 0.38867
  Epoch 015 - train 0.31570 | val 0.39920
  Regression -> MSE: 0.000216, MAE: 0.011419, R²: -0.0341
  Directional -> Accuracy: 0.4694, MCC: 0.0000, F1: 0.6389

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 112). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.35610 | val 0.40318
  Epoch 015 - train 0.34261 | val 0.41818
  Regression -> MSE: 0.000362, MAE: 0.012922, R²: -0.0119
  Directional -> Accuracy: 0.4531, MCC: 0.0220, F1: 0.1463

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.31633 | val 0.26760
  Epoch 012 - train 0.35680 | val 0.26684
  Regression -> MSE: 0.000111, MAE: 0.007826, R²: -0.1459
  Directional -> Accuracy: 0.5102, MCC: 0.0061, F1: 0.1429

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.39430 | val 0.76657
  Epoch 011 - train 0.36821 | val 0.76556
  Regression -> MSE: 0.000219, MAE: 0.011247, R²: -0.0101
  Directional -> Accuracy: 0.5185, MCC: -0.1275, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.39159 | val 1.03575
  Epoch 011 - train 0.36501 | val 1.05561
  Regression -> MSE: 0.000089, MAE: 0.007266, R²: -0.2450
  Directional -> Accuracy: 0.3864, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 112). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for PPL (108 < 112). Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 112). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 112). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 112). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.35690 | val 0.27430
  Epoch 011 - train 0.37379 | val 0.27597
  Regression -> MSE: 0.000301, MAE: 0.013638, R²: -0.0087
  Directional -> Accuracy: 0.6889, MCC: 0.2132, F1: 0.1250

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 112). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 112). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 112). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.33550 | val 0.71299
  Epoch 012 - train 0.33686 | val 0.75805
  Regression -> MSE: 0.000079, MAE: 0.006888, R²: -0.0055
  Directional -> Accuracy: 0.4861, MCC: -0.0342, F1: 0.2745

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 112). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 112). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 112). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 112). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.38737 | val 0.64997
  Epoch 020 - train 0.34266 | val 0.64435
  Epoch 028 - train 0.31881 | val 0.64844
  Regression -> MSE: 0.000280, MAE: 0.013726, R²: 0.0101
  Directional -> Accuracy: 0.5349, MCC: 0.0660, F1: 0.6154

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.39822 | val 0.37004
  Epoch 011 - train 0.36228 | val 0.37150
  Regression -> MSE: 0.000111, MAE: 0.007635, R²: -0.0248
  Directional -> Accuracy: 0.5897, MCC: 0.0000, F1: 0.7419

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.38346 | val 0.64157
  Epoch 011 - train 0.37914 | val 0.64418
  Regression -> MSE: 0.000191, MAE: 0.010747, R²: -0.0495
  Directional -> Accuracy: 0.3778, MCC: 0.0000, F1: 0.5484

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.35140 | val 0.51621
  Epoch 011 - train 0.33324 | val 0.51286
  Regression -> MSE: 0.000239, MAE: 0.012165, R²: -0.0320
  Directional -> Accuracy: 0.4528, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.37032 | val 0.82114
  Epoch 011 - train 0.36025 | val 0.81419
  Regression -> MSE: 0.000091, MAE: 0.007843, R²: -0.0369
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.41609 | val 0.77399
  Epoch 015 - train 0.40115 | val 0.77900
  Regression -> MSE: 0.000174, MAE: 0.010719, R²: -0.0250
  Directional -> Accuracy: 0.4902, MCC: 0.0000, F1: 0.6579

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.36301 | val 0.70616
  Epoch 016 - train 0.33922 | val 0.86073
  Regression -> MSE: 0.000122, MAE: 0.009064, R²: -0.0313
  Directional -> Accuracy: 0.5283, MCC: 0.0632, F1: 0.4681

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.38919 | val 0.80228

[I 2026-02-22 20:45:40,823] Trial 5 finished with value: -0.011595894034825813 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 36, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.0, 'dropout': 0.7000000000000001, 'batch_size': 64, 'learning_rate': 0.003580212764347875, 'weight_decay': 3.8839702707686967e-05, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.0634031259187102, 'early_stopping_min_delta': 0.005574153185882939}. Best is trial 3 with value: -0.011473394984568777.

  Epoch 014 - train 0.36700 | val 0.84811
  Regression -> MSE: 0.000250, MAE: 0.012957, R²: -0.0116
  Directional -> Accuracy: 0.4655, MCC: 0.0000, F1: 0.6353

================================================================================
Pipeline completed: 47/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (47, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 6
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.21664 | val 0.25562
  Epoch 014 - train 0.20354 | val 0.25656
  Regression -> MSE: 0.000247, MAE: 0.012577, R²: -0.0033
  Directional -> Accuracy: 0.5570, MCC: 0.1161, F1: 0.5333

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 82). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.24453 | val 0.21469
  Epoch 011 - train 0.24044 | val 0.20975
  Regression -> MSE: 0.000717, MAE: 0.019965, R²: -0.0585
  Directional -> Accuracy: 0.4375, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 82). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.22511 | val 0.35703
  Epoch 014 - train 0.23673 | val 0.35264
  Regression -> MSE: 0.000339, MAE: 0.014926, R²: 0.0223
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.18877 | val 0.22441
  Epoch 011 - train 0.19028 | val 0.21115
  Regression -> MSE: 0.000365, MAE: 0.014862, R²: -0.0289
  Directional -> Accuracy: 0.4935, MCC: -0.1399, F1: 0.6486

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.22987 | val 0.20868
  Epoch 011 - train 0.21684 | val 0.20582
  Regression -> MSE: 0.000202, MAE: 0.010035, R²: -0.0203
  Directional -> Accuracy: 0.5283, MCC: 0.0000, F1: 0.6914

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.20912 | val 0.42524
  Epoch 011 - train 0.21511 | val 0.42105
  Regression -> MSE: 0.000498, MAE: 0.017246, R²: -0.0026
  Directional -> Accuracy: 0.4634, MCC: 0.0000, F1: 0.6333

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.21947 | val 0.27671
  Epoch 011 - train 0.22272 | val 0.27351
  Regression -> MSE: 0.000264, MAE: 0.012324, R²: -0.0306
  Directional -> Accuracy: 0.5915, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 82). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 82). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.22739 | val 0.24066
  Epoch 020 - train 0.22561 | val 0.23713
  Regression -> MSE: 0.000710, MAE: 0.020558, R²: -0.2524
  Directional -> Accuracy: 0.5957, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.21435 | val 0.28988
  Epoch 011 - train 0.20854 | val 0.29043
  Regression -> MSE: 0.000390, MAE: 0.015617, R²: -0.0144
  Directional -> Accuracy: 0.6047, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 82). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 82). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.22290 | val 0.36542
  Epoch 011 - train 0.22581 | val 0.35563
  Regression -> MSE: 0.000247, MAE: 0.011579, R²: -0.0351
  Directional -> Accuracy: 0.5694, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.20408 | val 0.37836
  Epoch 011 - train 0.19539 | val 0.38051
  Regression -> MSE: 0.000308, MAE: 0.013797, R²: -0.0030
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.22461 | val 0.24977
  Epoch 011 - train 0.22932 | val 0.25059
  Regression -> MSE: 0.000664, MAE: 0.019347, R²: -0.0075
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.23154 | val 0.21470
  Epoch 011 - train 0.21328 | val 0.21513
  Regression -> MSE: 0.000147, MAE: 0.009361, R²: -0.0011
  Directional -> Accuracy: 0.4667, MCC: -0.0403, F1: 0.5556

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 82). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.21671 | val 0.32737
  Epoch 011 - train 0.22101 | val 0.32419
  Regression -> MSE: 0.000232, MAE: 0.011228, R²: -0.0305
  Directional -> Accuracy: 0.4921, MCC: 0.0000, F1: 0.6596

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.21546 | val 0.43359
  Epoch 011 - train 0.21504 | val 0.43678
  Regression -> MSE: 0.000385, MAE: 0.016692, R²: -0.0043
  Directional -> Accuracy: 0.4815, MCC: 0.0000, F1: 0.6500

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.23511 | val 0.26721
  Epoch 011 - train 0.23380 | val 0.26334
  Regression -> MSE: 0.000106, MAE: 0.007968, R²: -0.0122
  Directional -> Accuracy: 0.4583, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.20170 | val 0.38796
  Epoch 011 - train 0.20331 | val 0.38878
  Regression -> MSE: 0.000159, MAE: 0.009963, R²: -0.0068
  Directional -> Accuracy: 0.6066, MCC: 0.0000, F1: 0.7551

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.21232 | val 0.21852
  Epoch 011 - train 0.21777 | val 0.21234
  Regression -> MSE: 0.000272, MAE: 0.012980, R²: -0.0031
  Directional -> Accuracy: 0.6026, MCC: 0.0000, F1: 0.7520

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.21771 | val 0.31125
  Epoch 011 - train 0.20467 | val 0.31395
  Regression -> MSE: 0.000170, MAE: 0.009205, R²: -0.0973
  Directional -> Accuracy: 0.4179, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 82). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.23388 | val 0.30616
  Epoch 011 - train 0.23488 | val 0.30385
  Regression -> MSE: 0.000249, MAE: 0.011364, R²: -0.0751
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.22419 | val 0.30691
  Epoch 011 - train 0.23241 | val 0.30852
  Regression -> MSE: 0.000157, MAE: 0.009016, R²: -0.0521
  Directional -> Accuracy: 0.6200, MCC: 0.0000, F1: 0.7654

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 82). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 82). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 82). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.20779 | val 0.22344
  Epoch 014 - train 0.21053 | val 0.22315
  Regression -> MSE: 0.000210, MAE: 0.011451, R²: -0.1562
  Directional -> Accuracy: 0.4265, MCC: -0.1592, F1: 0.2909

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.23832 | val 0.28214
  Epoch 011 - train 0.24265 | val 0.27947
  Regression -> MSE: 0.000084, MAE: 0.006961, R²: -0.0166
  Directional -> Accuracy: 0.5833, MCC: 0.0000, F1: 0.7368

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.21844 | val 0.25337
  Epoch 011 - train 0.22025 | val 0.25433
  Regression -> MSE: 0.000215, MAE: 0.011202, R²: -0.0003
  Directional -> Accuracy: 0.4853, MCC: 0.0000, F1: 0.6535

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.20814 | val 0.16544
  Epoch 018 - train 0.20622 | val 0.16227
  Regression -> MSE: 0.000102, MAE: 0.008523, R²: -0.1368
  Directional -> Accuracy: 0.5000, MCC: 0.0072, F1: 0.5085

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.22387 | val 0.13232
  Epoch 011 - train 0.22207 | val 0.13792
  Regression -> MSE: 0.000129, MAE: 0.009410, R²: -0.0350
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.25137 | val 0.36783
  Epoch 011 - train 0.24513 | val 0.36951
  Regression -> MSE: 0.000337, MAE: 0.014656, R²: -0.1560
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.22115 | val 0.26524
  Epoch 011 - train 0.22527 | val 0.26562
  Regression -> MSE: 0.000180, MAE: 0.007852, R²: -0.1149
  Directional -> Accuracy: 0.4407, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.22586 | val 0.20456
  Epoch 011 - train 0.22762 | val 0.20377
  Regression -> MSE: 0.000230, MAE: 0.011833, R²: 0.0028
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.6866

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.22556 | val 0.27609
  Epoch 011 - train 0.22914 | val 0.27751
  Regression -> MSE: 0.000259, MAE: 0.010739, R²: -0.0010
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.23621 | val 0.27965
  Epoch 011 - train 0.23369 | val 0.27865
  Regression -> MSE: 0.000145, MAE: 0.008621, R²: -0.0341
  Directional -> Accuracy: 0.4565, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.23627 | val 0.26848
  Epoch 016 - train 0.22075 | val 0.26756
  Regression -> MSE: 0.000191, MAE: 0.010298, R²: -0.0276
  Directional -> Accuracy: 0.5962, MCC: 0.1901, F1: 0.6182

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.20732 | val 0.24497
  Epoch 011 - train 0.20620 | val 0.24348
  Regression -> MSE: 0.000266, MAE: 0.010593, R²: -0.0166
  Directional -> Accuracy: 0.6133, MCC: 0.1944, F1: 0.7010

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 82). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.21022 | val 0.22999
  Epoch 011 - train 0.22379 | val 0.23280
  Regression -> MSE: 0.000164, MAE: 0.010157, R²: -0.0119
  Directional -> Accuracy: 0.4878, MCC: 0.0000, F1: 0.6557

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.21828 | val 0.20756
  Epoch 011 - train 0.21053 | val 0.20837
  Regression -> MSE: 0.000213, MAE: 0.011066, R²: 0.0025
  Directional -> Accuracy: 0.5435, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.22096 | val 0.20280
  Epoch 011 - train 0.21709 | val 0.20193
  Regression -> MSE: 0.000345, MAE: 0.012062, R²: -0.0026
  Directional -> Accuracy: 0.4203, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.26201 | val 0.25141
  Epoch 011 - train 0.26056 | val 0.26063
  Regression -> MSE: 0.000133, MAE: 0.008448, R²: -0.3088
  Directional -> Accuracy: 0.4889, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.22745 | val 0.26963
  Epoch 011 - train 0.21928 | val 0.27010
  Regression -> MSE: 0.000211, MAE: 0.010971, R²: -0.0001
  Directional -> Accuracy: 0.5254, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.21709 | val 0.38071
  Epoch 011 - train 0.22662 | val 0.37995
  Regression -> MSE: 0.000089, MAE: 0.007430, R²: -0.1193
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 82). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 82). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 82). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 82). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.21567 | val 0.18435
  Epoch 011 - train 0.22741 | val 0.18571
  Regression -> MSE: 0.000316, MAE: 0.014018, R²: -0.0059
  Directional -> Accuracy: 0.6667, MCC: 0.0000, F1: 0.0000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 82). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.23189 | val 0.13504
  Epoch 020 - train 0.22896 | val 0.13515
  Epoch 023 - train 0.23735 | val 0.13629
  Regression -> MSE: 0.000239, MAE: 0.011318, R²: -0.0450
  Directional -> Accuracy: 0.5122, MCC: 0.0290, F1: 0.4737

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 82). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 82). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.20982 | val 0.27259
  Epoch 011 - train 0.21201 | val 0.27392
  Regression -> MSE: 0.000082, MAE: 0.007160, R²: 0.0003
  Directional -> Accuracy: 0.5065, MCC: 0.0000, F1: 0.6724

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 82). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 82). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.22475 | val 0.25641
  Epoch 011 - train 0.23630 | val 0.25464
  Regression -> MSE: 0.000382, MAE: 0.015700, R²: -0.0314
  Directional -> Accuracy: 0.4898, MCC: 0.0000, F1: 0.6575

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.21920 | val 0.23684
  Epoch 011 - train 0.21161 | val 0.23838
  Regression -> MSE: 0.000095, MAE: 0.007175, R²: -0.0018
  Directional -> Accuracy: 0.5745, MCC: 0.0000, F1: 0.7297

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.26076 | val 0.28189
  Epoch 011 - train 0.25802 | val 0.28293
  Regression -> MSE: 0.000193, MAE: 0.010670, R²: -0.0116
  Directional -> Accuracy: 0.3571, MCC: 0.0000, F1: 0.5263

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.21019 | val 0.25887
  Epoch 011 - train 0.20819 | val 0.26152
  Regression -> MSE: 0.000223, MAE: 0.011726, R²: -0.0326
  Directional -> Accuracy: 0.4483, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.20658 | val 0.24761
  Epoch 011 - train 0.21335 | val 0.25109
  Regression -> MSE: 0.000090, MAE: 0.007507, R²: 0.0014
  Directional -> Accuracy: 0.5085, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.23740 | val 0.43721
  Epoch 011 - train 0.21598 | val 0.43198
  Regression -> MSE: 0.000158, MAE: 0.009993, R²: 0.0006
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.22989 | val 0.26493
  Epoch 011 - train 0.23408 | val 0.26339
  Regression -> MSE: 0.000134, MAE: 0.009071, R²: -0.1938
  Directional -> Accuracy: 0.4828, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...

[I 2026-02-22 20:46:53,828] Trial 6 finished with value: -0.011586043004078339 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 6, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.5, 'batch_size': 16, 'learning_rate': 5.628865921163215e-06, 'weight_decay': 0.00012052978923819984, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.3615669926234314, 'early_stopping_min_delta': 0.007106693450721494}. Best is trial 3 with value: -0.011473394984568777.

  Epoch 010 - train 0.21348 | val 0.34372
  Epoch 011 - train 0.22744 | val 0.34252
  Regression -> MSE: 0.000236, MAE: 0.012081, R²: -0.0267
  Directional -> Accuracy: 0.5238, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: regression
Sequence length: 6
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.38024 | val 0.63877
  Epoch 011 - train 0.37114 | val 0.64455
  Regression -> MSE: 0.000262, MAE: 0.013045, R²: -0.0660
  Directional -> Accuracy: 0.4430, MCC: 0.0000, F1: 0.6140

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 82). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.42518 | val 0.67188
  Epoch 011 - train 0.40964 | val 0.67839
  Regression -> MSE: 0.000692, MAE: 0.019664, R²: -0.0221
  Directional -> Accuracy: 0.5208, MCC: -0.1839, F1: 0.6849

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 82). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.42579 | val 0.90409
  Epoch 011 - train 0.44019 | val 0.90295
  Regression -> MSE: 0.000353, MAE: 0.015129, R²: -0.0177
  Directional -> Accuracy: 0.5306, MCC: 0.0923, F1: 0.4390

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.34719 | val 0.57473
  Epoch 011 - train 0.33364 | val 0.60666
  Regression -> MSE: 0.000420, MAE: 0.015906, R²: -0.1843
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.40668 | val 0.36584
  Epoch 020 - train 0.37623 | val 0.35402
  Regression -> MSE: 0.000210, MAE: 0.009907, R²: -0.0609
  Directional -> Accuracy: 0.5283, MCC: 0.0000, F1: 0.6914

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.41552 | val 0.93912
  Epoch 019 - train 0.39580 | val 0.93027
  Regression -> MSE: 0.000572, MAE: 0.018490, R²: -0.1517
  Directional -> Accuracy: 0.4634, MCC: 0.0000, F1: 0.6333

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.44077 | val 0.67060
  Epoch 012 - train 0.41070 | val 0.66941
  Regression -> MSE: 0.000250, MAE: 0.012295, R²: 0.0236
  Directional -> Accuracy: 0.4789, MCC: 0.0127, F1: 0.5067

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 82). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 82). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.40479 | val 0.54962
  Epoch 020 - train 0.37869 | val 0.51390
  Regression -> MSE: 0.000568, MAE: 0.018399, R²: -0.0013
  Directional -> Accuracy: 0.5957, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.43252 | val 0.75976
  Epoch 011 - train 0.41935 | val 0.73393
  Regression -> MSE: 0.000392, MAE: 0.016453, R²: -0.0183
  Directional -> Accuracy: 0.3953, MCC: 0.0000, F1: 0.5667

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 82). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 82). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.38828 | val 0.82335
  Epoch 011 - train 0.41228 | val 0.79867
  Regression -> MSE: 0.000244, MAE: 0.011489, R²: -0.0233
  Directional -> Accuracy: 0.5556, MCC: -0.0013, F1: 0.1579

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.40010 | val 1.00139
  Epoch 011 - train 0.39982 | val 0.98745
  Regression -> MSE: 0.000321, MAE: 0.014218, R²: -0.0469
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.42051 | val 0.52344
  Epoch 011 - train 0.42703 | val 0.52382
  Regression -> MSE: 0.000657, MAE: 0.019100, R²: 0.0029
  Directional -> Accuracy: 0.5667, MCC: 0.1455, F1: 0.4583

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.39439 | val 0.46215
  Epoch 020 - train 0.39246 | val 0.44566
  Regression -> MSE: 0.000157, MAE: 0.009316, R²: -0.0688
  Directional -> Accuracy: 0.6222, MCC: 0.2373, F1: 0.5143

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 82). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.37314 | val 0.58355
  Epoch 013 - train 0.36342 | val 0.59697
  Regression -> MSE: 0.000218, MAE: 0.010924, R²: 0.0297
  Directional -> Accuracy: 0.4921, MCC: -0.0116, F1: 0.5556

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.40489 | val 1.58157
  Epoch 011 - train 0.41938 | val 1.68390
  Regression -> MSE: 0.000402, MAE: 0.016604, R²: -0.0497
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.42691 | val 0.54169
  Epoch 011 - train 0.44552 | val 0.55296
  Regression -> MSE: 0.000107, MAE: 0.007833, R²: -0.0129
  Directional -> Accuracy: 0.5000, MCC: 0.0383, F1: 0.4000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.41010 | val 1.05451
  Epoch 011 - train 0.41025 | val 1.05270
  Regression -> MSE: 0.000172, MAE: 0.010076, R²: -0.0899
  Directional -> Accuracy: 0.6066, MCC: 0.0000, F1: 0.7551

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.39571 | val 0.57668
  Epoch 011 - train 0.42167 | val 0.57734
  Regression -> MSE: 0.000280, MAE: 0.013456, R²: -0.0317
  Directional -> Accuracy: 0.3974, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.35827 | val 0.56406
  Epoch 020 - train 0.34394 | val 0.57852
  Regression -> MSE: 0.000181, MAE: 0.009730, R²: -0.1685
  Directional -> Accuracy: 0.4925, MCC: 0.1096, F1: 0.3462

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 82). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.39938 | val 0.71259
  Epoch 012 - train 0.42265 | val 0.71265
  Regression -> MSE: 0.000276, MAE: 0.012054, R²: -0.1900
  Directional -> Accuracy: 0.5065, MCC: 0.1681, F1: 0.2083

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.42034 | val 0.52863
  Epoch 011 - train 0.44990 | val 0.53090
  Regression -> MSE: 0.000162, MAE: 0.009188, R²: -0.0867
  Directional -> Accuracy: 0.4000, MCC: 0.0243, F1: 0.1176

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 82). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 82). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 82). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.39804 | val 0.49348
  Epoch 011 - train 0.39370 | val 0.48808
  Regression -> MSE: 0.000181, MAE: 0.010840, R²: 0.0044
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.43494 | val 0.68962
  Epoch 011 - train 0.43520 | val 0.69065
  Regression -> MSE: 0.000084, MAE: 0.007070, R²: -0.0179
  Directional -> Accuracy: 0.5833, MCC: 0.0000, F1: 0.7368

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.40069 | val 0.58216
  Epoch 011 - train 0.41098 | val 0.57000
  Regression -> MSE: 0.000215, MAE: 0.011208, R²: 0.0011
  Directional -> Accuracy: 0.5294, MCC: 0.0759, F1: 0.6000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.36849 | val 0.27016
  Epoch 014 - train 0.37313 | val 0.27574
  Regression -> MSE: 0.000093, MAE: 0.007809, R²: -0.0348
  Directional -> Accuracy: 0.5862, MCC: 0.1942, F1: 0.5714

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.41940 | val 0.29727
  Epoch 013 - train 0.41072 | val 0.32042
  Regression -> MSE: 0.000135, MAE: 0.009611, R²: -0.0780
  Directional -> Accuracy: 0.4490, MCC: 0.0195, F1: 0.5846

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.42085 | val 0.21555
  Epoch 011 - train 0.44608 | val 0.21691
  Regression -> MSE: 0.000305, MAE: 0.013907, R²: -0.0458
  Directional -> Accuracy: 0.5111, MCC: -0.0379, F1: 0.6071

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.40453 | val 0.50780
  Epoch 013 - train 0.39086 | val 0.52125
  Regression -> MSE: 0.000211, MAE: 0.009098, R²: -0.3091
  Directional -> Accuracy: 0.4576, MCC: 0.1166, F1: 0.0588

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.44402 | val 0.39554
  Epoch 011 - train 0.41345 | val 0.39396
  Regression -> MSE: 0.000234, MAE: 0.012001, R²: -0.0138
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.6866

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.40196 | val 0.59685
  Epoch 011 - train 0.45886 | val 0.60194
  Regression -> MSE: 0.000260, MAE: 0.010769, R²: -0.0045
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.44911 | val 0.61909
  Epoch 011 - train 0.46659 | val 0.61697
  Regression -> MSE: 0.000154, MAE: 0.009098, R²: -0.0997
  Directional -> Accuracy: 0.4565, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.42900 | val 0.55327
  Epoch 013 - train 0.42424 | val 0.55214
  Regression -> MSE: 0.000194, MAE: 0.010866, R²: -0.0406
  Directional -> Accuracy: 0.5577, MCC: 0.2078, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.35942 | val 0.51938
  Epoch 011 - train 0.35567 | val 0.51920
  Regression -> MSE: 0.000293, MAE: 0.011283, R²: -0.1219
  Directional -> Accuracy: 0.4400, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 82). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.43916 | val 0.46313
  Epoch 015 - train 0.41509 | val 0.47200
  Regression -> MSE: 0.000164, MAE: 0.010249, R²: -0.0141
  Directional -> Accuracy: 0.4878, MCC: 0.0000, F1: 0.6557

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.35884 | val 0.46555
  Epoch 011 - train 0.39274 | val 0.47861
  Regression -> MSE: 0.000237, MAE: 0.011759, R²: -0.1063
  Directional -> Accuracy: 0.4565, MCC: 0.0000, F1: 0.6269

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.38515 | val 0.38716
  Epoch 017 - train 0.39860 | val 0.38313
  Regression -> MSE: 0.000349, MAE: 0.012862, R²: -0.0132
  Directional -> Accuracy: 0.4783, MCC: 0.0645, F1: 0.3333

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.46597 | val 0.48777
  Epoch 011 - train 0.41625 | val 0.47215
  Regression -> MSE: 0.000152, MAE: 0.009063, R²: -0.4965
  Directional -> Accuracy: 0.4889, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.41798 | val 0.98446
  Epoch 011 - train 0.41302 | val 0.98627
  Regression -> MSE: 0.000213, MAE: 0.010994, R²: -0.0065
  Directional -> Accuracy: 0.5593, MCC: 0.1135, F1: 0.3158

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.41778 | val 1.09423
  Epoch 011 - train 0.43086 | val 1.10402
  Regression -> MSE: 0.000096, MAE: 0.007673, R²: -0.2002
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 82). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 82). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 82). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 82). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.42217 | val 0.31636
  Epoch 011 - train 0.41241 | val 0.31516
  Regression -> MSE: 0.000315, MAE: 0.013762, R²: -0.0025
  Directional -> Accuracy: 0.6667, MCC: 0.0000, F1: 0.0000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 82). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.43067 | val 0.28025
  Epoch 011 - train 0.42291 | val 0.27840
  Regression -> MSE: 0.000231, MAE: 0.010957, R²: -0.0125
  Directional -> Accuracy: 0.5610, MCC: 0.1205, F1: 0.6250

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 82). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 82). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.38826 | val 0.68307
  Epoch 011 - train 0.38874 | val 0.69558
  Regression -> MSE: 0.000092, MAE: 0.007324, R²: -0.1261
  Directional -> Accuracy: 0.4935, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 82). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 82). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.42869 | val 0.49252
  Epoch 012 - train 0.43738 | val 0.44982
  Regression -> MSE: 0.000366, MAE: 0.015539, R²: 0.0099
  Directional -> Accuracy: 0.5510, MCC: 0.1193, F1: 0.6207

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.41536 | val 0.56073
  Epoch 011 - train 0.41682 | val 0.55686
  Regression -> MSE: 0.000099, MAE: 0.007003, R²: -0.0440
  Directional -> Accuracy: 0.5745, MCC: 0.0000, F1: 0.7297

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.43341 | val 0.86718
  Epoch 011 - train 0.43190 | val 0.89044
  Regression -> MSE: 0.000194, MAE: 0.010765, R²: -0.0156
  Directional -> Accuracy: 0.3571, MCC: 0.0000, F1: 0.5263

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.38696 | val 0.59433
  Epoch 011 - train 0.41334 | val 0.56939
  Regression -> MSE: 0.000232, MAE: 0.011836, R²: -0.0713
  Directional -> Accuracy: 0.4483, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.38896 | val 0.57940
  Epoch 011 - train 0.38773 | val 0.58035
  Regression -> MSE: 0.000095, MAE: 0.007805, R²: -0.0548
  Directional -> Accuracy: 0.4915, MCC: 0.0000, F1: 0.6591

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.40925 | val 1.11286
  Epoch 011 - train 0.42618 | val 1.13728
  Regression -> MSE: 0.000163, MAE: 0.010122, R²: -0.0298
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.0000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.39259 | val 0.80544
  Epoch 011 - train 0.37741 | val 0.80585
  Regression -> MSE: 0.000114, MAE: 0.008718, R²: -0.0216
  Directional -> Accuracy: 0.5172, MCC: 0.0000, F1: 0.6818

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...

[I 2026-02-22 20:47:42,144] Trial 7 finished with value: -0.011708992380332335 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 6, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.5, 'batch_size': 16, 'learning_rate': 0.00011440112020452205, 'weight_decay': 3.772148077644115e-05, 'lr_patience': 7, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 1.156304933349688, 'early_stopping_min_delta': 0.009365026424122201}. Best is trial 3 with value: -0.011473394984568777.

  Epoch 010 - train 0.43775 | val 0.80107
  Epoch 011 - train 0.43468 | val 0.83314
  Regression -> MSE: 0.000241, MAE: 0.012183, R²: -0.0480
  Directional -> Accuracy: 0.5238, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 36
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.38625 | val 0.81016
  Epoch 016 - train 0.38340 | val 0.85279
  Regression -> MSE: 0.000247, MAE: 0.012532, R²: -0.0493
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.6168

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 112). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.39015 | val 0.51338
  Epoch 020 - train 0.37885 | val 0.48728
  Epoch 030 - train 0.38632 | val 0.48504
  Regression -> MSE: 0.000659, MAE: 0.018784, R²: 0.0752
  Directional -> Accuracy: 0.6047, MCC: 0.0000, F1: 0.7536

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for AEP (109 < 112). Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 112). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.42842 | val 0.90706
  Epoch 020 - train 0.40445 | val 0.89169
  Epoch 030 - train 0.39481 | val 0.89194
  Regression -> MSE: 0.000320, MAE: 0.014525, R²: -0.0060
  Directional -> Accuracy: 0.5455, MCC: 0.1461, F1: 0.3750

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.33291 | val 0.58411
  Epoch 016 - train 0.32846 | val 0.50608
  Regression -> MSE: 0.000359, MAE: 0.014717, R²: -0.0069
  Directional -> Accuracy: 0.5417, MCC: 0.0000, F1: 0.7027

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.38551 | val 0.41381
  Epoch 020 - train 0.36879 | val 0.40341
  Epoch 030 - train 0.36429 | val 0.40406
  Regression -> MSE: 0.000215, MAE: 0.009726, R²: -0.0236
  Directional -> Accuracy: 0.5625, MCC: 0.1180, F1: 0.6316

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.37313 | val 0.87455
  Epoch 016 - train 0.36906 | val 0.90752
  Regression -> MSE: 0.000572, MAE: 0.018235, R²: -0.0212
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.43549 | val 0.58654
  Epoch 020 - train 0.40293 | val 0.60589
  Epoch 022 - train 0.39925 | val 0.62313
  Regression -> MSE: 0.000258, MAE: 0.012134, R²: -0.0122
  Directional -> Accuracy: 0.5909, MCC: 0.0687, F1: 0.2286

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 112). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 112). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.37310 | val 0.43735
  Epoch 016 - train 0.37138 | val 0.53808
  Regression -> MSE: 0.000579, MAE: 0.018789, R²: -0.0001
  Directional -> Accuracy: 0.5641, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.39088 | val 0.66435
  Epoch 016 - train 0.38857 | val 0.70624
  Regression -> MSE: 0.000382, MAE: 0.016026, R²: -0.0001
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 112). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 112). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 112). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.39562 | val 0.62534
  Epoch 020 - train 0.38930 | val 0.63133
  Epoch 022 - train 0.37970 | val 0.64436
  Regression -> MSE: 0.000247, MAE: 0.011924, R²: -0.0026
  Directional -> Accuracy: 0.4925, MCC: -0.0430, F1: 0.3929

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.35114 | val 0.86639
  Epoch 016 - train 0.37249 | val 1.02660
  Regression -> MSE: 0.000312, MAE: 0.013328, R²: -0.0010
  Directional -> Accuracy: 0.5532, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.43065 | val 0.56321
  Epoch 016 - train 0.42633 | val 0.58522
  Regression -> MSE: 0.000704, MAE: 0.019831, R²: -0.0133
  Directional -> Accuracy: 0.4727, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 112). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.39222 | val 0.45383
  Epoch 016 - train 0.38213 | val 0.53966
  Regression -> MSE: 0.000151, MAE: 0.009747, R²: -0.0415
  Directional -> Accuracy: 0.4792, MCC: 0.0000, F1: 0.6479

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 112). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.34814 | val 0.66584
  Epoch 016 - train 0.34407 | val 0.67449
  Regression -> MSE: 0.000229, MAE: 0.010667, R²: 0.0005
  Directional -> Accuracy: 0.5172, MCC: 0.0000, F1: 0.6818

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.39161 | val 1.22365
  Epoch 016 - train 0.37362 | val 1.36584
  Regression -> MSE: 0.000379, MAE: 0.016134, R²: -0.0135
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.40908 | val 0.54288
  Epoch 016 - train 0.40518 | val 0.59640
  Regression -> MSE: 0.000110, MAE: 0.007971, R²: -0.0086
  Directional -> Accuracy: 0.5373, MCC: 0.0000, F1: 0.6990

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 112). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.39364 | val 1.09076
  Epoch 016 - train 0.37856 | val 1.19169
  Regression -> MSE: 0.000151, MAE: 0.009694, R²: -0.0009
  Directional -> Accuracy: 0.6071, MCC: 0.0000, F1: 0.7556

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.40423 | val 0.46350
  Epoch 016 - train 0.40320 | val 0.46902
  Regression -> MSE: 0.000278, MAE: 0.013171, R²: -0.0040
  Directional -> Accuracy: 0.5890, MCC: 0.0000, F1: 0.7414

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.32628 | val 0.65503
  Epoch 020 - train 0.31150 | val 0.72280
  Epoch 022 - train 0.32523 | val 0.71241
  Regression -> MSE: 0.000182, MAE: 0.009654, R²: -0.1817
  Directional -> Accuracy: 0.4194, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 112). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.40065 | val 0.85289
  Epoch 016 - train 0.39753 | val 0.85544
  Regression -> MSE: 0.000242, MAE: 0.011080, R²: -0.0639
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.39401 | val 0.65837
  Epoch 016 - train 0.39948 | val 0.71196
  Regression -> MSE: 0.000154, MAE: 0.008629, R²: -0.0379
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 112). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 112). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 112). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.37593 | val 0.52726
  Epoch 016 - train 0.36768 | val 0.53932
  Regression -> MSE: 0.000176, MAE: 0.010493, R²: -0.0333
  Directional -> Accuracy: 0.4921, MCC: 0.0000, F1: 0.6596

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.40180 | val 0.62302
  Epoch 016 - train 0.40689 | val 0.70975
  Regression -> MSE: 0.000088, MAE: 0.007203, R²: 0.0027
  Directional -> Accuracy: 0.5818, MCC: 0.0000, F1: 0.7356

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.39056 | val 0.63286
  Epoch 020 - train 0.37331 | val 0.63961
  Regression -> MSE: 0.000216, MAE: 0.011182, R²: 0.0050
  Directional -> Accuracy: 0.5238, MCC: 0.1168, F1: 0.6429

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.35437 | val 0.36142
  Epoch 020 - train 0.33339 | val 0.36883
  Epoch 026 - train 0.33304 | val 0.36174
  Regression -> MSE: 0.000102, MAE: 0.008059, R²: -0.1346
  Directional -> Accuracy: 0.5660, MCC: 0.2449, F1: 0.4103

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.42684 | val 0.47439
  Epoch 016 - train 0.40457 | val 0.47841
  Regression -> MSE: 0.000094, MAE: 0.008332, R²: -0.0290
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.41794 | val 0.29078
  Epoch 016 - train 0.39307 | val 0.50405
  Regression -> MSE: 0.000286, MAE: 0.013305, R²: -0.0274
  Directional -> Accuracy: 0.5833, MCC: 0.0000, F1: 0.7368

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.39163 | val 0.59758
  Epoch 020 - train 0.38735 | val 0.63078
  Epoch 022 - train 0.37819 | val 0.63018
  Regression -> MSE: 0.000193, MAE: 0.007942, R²: -0.1236
  Directional -> Accuracy: 0.4630, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
Insufficient data for proper time series validation for MDT. Skipping...

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.42586 | val 0.92640
  Epoch 016 - train 0.40935 | val 1.01914
  Regression -> MSE: 0.000241, MAE: 0.010117, R²: -0.0073
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.41269 | val 0.53284
  Epoch 016 - train 0.41392 | val 0.56289
  Regression -> MSE: 0.000148, MAE: 0.008700, R²: -0.0408
  Directional -> Accuracy: 0.4500, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.39120 | val 0.63482
  Epoch 020 - train 0.37623 | val 0.62125
  Epoch 030 - train 0.36528 | val 0.61458
  Regression -> MSE: 0.000256, MAE: 0.012904, R²: -0.3449
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.33333 | val 0.57833
  Epoch 016 - train 0.32823 | val 0.58103
  Regression -> MSE: 0.000268, MAE: 0.010462, R²: -0.0083
  Directional -> Accuracy: 0.5571, MCC: 0.0000, F1: 0.7156

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 112). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.34684 | val 0.39669
  Epoch 016 - train 0.33359 | val 0.39799
  Regression -> MSE: 0.000208, MAE: 0.011051, R²: 0.0020
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 112). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.36348 | val 0.44639
  Epoch 016 - train 0.35767 | val 0.47364
  Regression -> MSE: 0.000357, MAE: 0.012316, R²: 0.0000
  Directional -> Accuracy: 0.4375, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.39290 | val 0.28374
  Epoch 020 - train 0.35566 | val 0.30808
  Epoch 027 - train 0.34391 | val 0.38434
  Regression -> MSE: 0.000111, MAE: 0.007734, R²: -0.1423
  Directional -> Accuracy: 0.5714, MCC: 0.1577, F1: 0.4000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.39852 | val 0.81207
  Epoch 020 - train 0.36893 | val 0.87207
  Epoch 022 - train 0.36533 | val 0.87588
  Regression -> MSE: 0.000229, MAE: 0.011661, R²: -0.0569
  Directional -> Accuracy: 0.4630, MCC: 0.0000, F1: 0.6329

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.37659 | val 1.03765
  Epoch 020 - train 0.36719 | val 1.16649
  Epoch 023 - train 0.35482 | val 1.16145
  Regression -> MSE: 0.000079, MAE: 0.006903, R²: -0.1060
  Directional -> Accuracy: 0.4545, MCC: 0.0269, F1: 0.3684

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 112). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for PPL (108 < 112). Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 112). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 112). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 112). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.40565 | val 0.30893
  Epoch 020 - train 0.38172 | val 0.25801
  Epoch 030 - train 0.36280 | val 0.25417
  Regression -> MSE: 0.000305, MAE: 0.012961, R²: -0.0224
  Directional -> Accuracy: 0.6000, MCC: 0.0000, F1: 0.2500

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 112). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 112). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 112). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.36901 | val 0.76193
  Epoch 016 - train 0.35294 | val 0.89601
  Regression -> MSE: 0.000078, MAE: 0.006940, R²: -0.0027
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 112). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 112). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 112). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 112). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.41544 | val 0.72929
  Epoch 016 - train 0.41061 | val 0.80240
  Regression -> MSE: 0.000288, MAE: 0.013930, R²: -0.0180
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.39260 | val 0.39840
  Epoch 020 - train 0.36603 | val 0.38658
  Epoch 030 - train 0.35965 | val 0.39096
  Regression -> MSE: 0.000111, MAE: 0.007536, R²: -0.0198
  Directional -> Accuracy: 0.5897, MCC: 0.0000, F1: 0.7419

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.41076 | val 0.69632
  Epoch 016 - train 0.42646 | val 0.77652
  Regression -> MSE: 0.000184, MAE: 0.010373, R²: -0.0124
  Directional -> Accuracy: 0.3778, MCC: 0.0000, F1: 0.5484

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.36915 | val 0.52346
  Epoch 016 - train 0.35513 | val 0.54018
  Regression -> MSE: 0.000231, MAE: 0.011924, R²: 0.0023
  Directional -> Accuracy: 0.5472, MCC: 0.0000, F1: 0.7073

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.37392 | val 0.75743
  Epoch 016 - train 0.36644 | val 0.86737
  Regression -> MSE: 0.000088, MAE: 0.007543, R²: -0.0067
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.42119 | val 0.87747
  Epoch 016 - train 0.40921 | val 0.93768
  Regression -> MSE: 0.000170, MAE: 0.010451, R²: -0.0029
  Directional -> Accuracy: 0.5098, MCC: 0.0000, F1: 0.0000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.37707 | val 0.68972
  Epoch 016 - train 0.37838 | val 0.77393
  Regression -> MSE: 0.000127, MAE: 0.009137, R²: -0.0744
  Directional -> Accuracy: 0.4906, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.42179 | val 0.81735
  Epoch 020 - train 0.39332 | val 0.81682

[I 2026-02-22 20:49:49,947] Trial 8 finished with value: -0.011479441159931296 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 36, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.4, 'dropout': 0.0, 'batch_size': 32, 'learning_rate': 0.000153803675678207, 'weight_decay': 1.1555136569836572e-06, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 30, 'huber_delta': 1.2009475075373248, 'early_stopping_min_delta': 0.009805461074679708}. Best is trial 3 with value: -0.011473394984568777.

  Epoch 028 - train 0.39094 | val 0.81154
  Regression -> MSE: 0.000253, MAE: 0.013078, R²: -0.0213
  Directional -> Accuracy: 0.5000, MCC: 0.0900, F1: 0.6329

================================================================================
Pipeline completed: 47/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (47, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 12
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.26155 | val 0.40038
  Epoch 020 - train 0.24236 | val 0.52406
  Epoch 028 - train 0.24392 | val 0.58052
  Regression -> MSE: 0.000248, MAE: 0.012470, R²: -0.0097
  Directional -> Accuracy: 0.5513, MCC: 0.2030, F1: 0.6392

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 88). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.26334 | val 0.27362
  Epoch 020 - train 0.25722 | val 0.26861
  Epoch 030 - train 0.24475 | val 0.29607
  Epoch 036 - train 0.24321 | val 0.28341
  Regression -> MSE: 0.000726, MAE: 0.020569, R²: -0.0505
  Directional -> Accuracy: 0.5532, MCC: 0.0000, F1: 0.7123

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 88). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.29250 | val 0.54027
  Epoch 020 - train 0.28520 | val 0.51049
  Epoch 030 - train 0.28117 | val 0.50125
  Epoch 040 - train 0.28162 | val 0.50833
  Epoch 050 - train 0.27077 | val 0.48268
  Regression -> MSE: 0.000437, MAE: 0.016802, R²: -0.2649
  Directional -> Accuracy: 0.4792, MCC: 0.1342, F1: 0.0741

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.22780 | val 0.29086
  Epoch 020 - train 0.22809 | val 0.44700
  Epoch 021 - train 0.22614 | val 0.43814
  Regression -> MSE: 0.000351, MAE: 0.014508, R²: -0.0165
  Directional -> Accuracy: 0.5395, MCC: 0.0409, F1: 0.6535

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.27019 | val 0.28320
  Epoch 020 - train 0.25158 | val 0.27849
  Epoch 030 - train 0.24628 | val 0.32304
  Epoch 034 - train 0.24500 | val 0.30530
  Regression -> MSE: 0.000191, MAE: 0.009109, R²: 0.0476
  Directional -> Accuracy: 0.7308, MCC: 0.4817, F1: 0.7879

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.26208 | val 0.60725
  Epoch 020 - train 0.24842 | val 0.65938
  Epoch 030 - train 0.23476 | val 0.69797
  Regression -> MSE: 0.000591, MAE: 0.018650, R²: -0.0318
  Directional -> Accuracy: 0.4898, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.29764 | val 0.39104
  Epoch 020 - train 0.28109 | val 0.42982
  Epoch 030 - train 0.27466 | val 0.47780
  Epoch 036 - train 0.25874 | val 0.45266
  Regression -> MSE: 0.000258, MAE: 0.012303, R²: -0.0494
  Directional -> Accuracy: 0.5286, MCC: 0.0352, F1: 0.4407

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 88). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 88). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.24365 | val 0.51591
  Epoch 020 - train 0.23525 | val 0.59627
  Epoch 021 - train 0.23932 | val 0.60322
  Regression -> MSE: 0.000635, MAE: 0.019847, R²: -0.0864
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.26095 | val 0.47397
  Epoch 020 - train 0.24673 | val 0.44259
  Epoch 030 - train 0.24379 | val 0.56043
  Epoch 039 - train 0.23412 | val 0.60350
  Regression -> MSE: 0.000441, MAE: 0.018104, R²: -0.3046
  Directional -> Accuracy: 0.3810, MCC: 0.0000, F1: 0.5517

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 88). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 88). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.28223 | val 0.41230
  Epoch 020 - train 0.25778 | val 0.44544
  Epoch 021 - train 0.26550 | val 0.45588
  Regression -> MSE: 0.000238, MAE: 0.011783, R²: 0.0019
  Directional -> Accuracy: 0.4366, MCC: 0.0000, F1: 0.6078

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.25194 | val 0.49473
  Epoch 020 - train 0.24044 | val 0.77137
  Epoch 021 - train 0.23600 | val 0.78841
  Regression -> MSE: 0.000306, MAE: 0.013536, R²: 0.0009
  Directional -> Accuracy: 0.5882, MCC: 0.2176, F1: 0.2759

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.28685 | val 0.37689
  Epoch 020 - train 0.27712 | val 0.62097
  Epoch 021 - train 0.27220 | val 0.62859
  Regression -> MSE: 0.000670, MAE: 0.019400, R²: -0.0004
  Directional -> Accuracy: 0.4915, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.27322 | val 0.29365
  Epoch 020 - train 0.25142 | val 0.32967
  Epoch 021 - train 0.25653 | val 0.34142
  Regression -> MSE: 0.000150, MAE: 0.009598, R²: -0.0024
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 88). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.24202 | val 0.42197
  Epoch 020 - train 0.23506 | val 0.48601
  Epoch 024 - train 0.22593 | val 0.49844
  Regression -> MSE: 0.000224, MAE: 0.010735, R²: 0.0019
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.26063 | val 0.69039
  Epoch 020 - train 0.23385 | val 0.75235
  Epoch 030 - train 0.24173 | val 0.74644
  Epoch 035 - train 0.23900 | val 0.70217
  Regression -> MSE: 0.000364, MAE: 0.016330, R²: 0.0329
  Directional -> Accuracy: 0.5094, MCC: 0.1871, F1: 0.6579

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.27758 | val 0.32707
  Epoch 020 - train 0.27024 | val 0.39929
  Epoch 024 - train 0.26432 | val 0.38945
  Regression -> MSE: 0.000107, MAE: 0.007875, R²: -0.0054
  Directional -> Accuracy: 0.5352, MCC: 0.0000, F1: 0.6972

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.27344 | val 0.54070
  Epoch 020 - train 0.25252 | val 0.60544
  Epoch 030 - train 0.25442 | val 0.60614
  Regression -> MSE: 0.000155, MAE: 0.009795, R²: 0.0293
  Directional -> Accuracy: 0.6167, MCC: 0.1697, F1: 0.7013

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.28001 | val 0.31085
  Epoch 020 - train 0.26732 | val 0.43238
  Epoch 021 - train 0.26727 | val 0.44956
  Regression -> MSE: 0.000279, MAE: 0.013409, R²: -0.0402
  Directional -> Accuracy: 0.3896, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.24847 | val 0.42821
  Epoch 020 - train 0.23104 | val 0.55431
  Epoch 025 - train 0.23313 | val 0.51214
  Regression -> MSE: 0.000162, MAE: 0.008978, R²: -0.0974
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 88). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.27456 | val 0.46432
  Epoch 020 - train 0.26664 | val 0.48664
  Epoch 030 - train 0.25021 | val 0.46394
  Epoch 040 - train 0.24658 | val 0.44961
  Epoch 050 - train 0.23056 | val 0.46853
  Regression -> MSE: 0.000632, MAE: 0.021185, R²: -1.7899
  Directional -> Accuracy: 0.4605, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.27875 | val 0.36625
  Epoch 020 - train 0.27977 | val 0.35688
  Epoch 030 - train 0.26460 | val 0.37799
  Epoch 037 - train 0.26533 | val 0.37005
  Regression -> MSE: 0.000227, MAE: 0.011611, R²: -0.5281
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 88). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 88). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 88). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.26690 | val 0.35829
  Epoch 020 - train 0.24908 | val 0.36273
  Epoch 026 - train 0.24570 | val 0.37122
  Regression -> MSE: 0.000185, MAE: 0.010572, R²: -0.0468
  Directional -> Accuracy: 0.5373, MCC: 0.0835, F1: 0.4561

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.28665 | val 0.36767
  Epoch 020 - train 0.27082 | val 0.43999
  Epoch 028 - train 0.26538 | val 0.46989
  Regression -> MSE: 0.000083, MAE: 0.006919, R²: 0.0048
  Directional -> Accuracy: 0.5593, MCC: 0.0299, F1: 0.6829

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.28162 | val 0.39868
  Epoch 020 - train 0.26899 | val 0.44768
  Epoch 021 - train 0.26711 | val 0.46745
  Regression -> MSE: 0.000224, MAE: 0.011291, R²: -0.0259
  Directional -> Accuracy: 0.5224, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.23312 | val 0.23916
  Epoch 020 - train 0.21971 | val 0.22128
  Epoch 030 - train 0.20760 | val 0.22067
  Epoch 040 - train 0.20664 | val 0.22489
  Epoch 042 - train 0.20708 | val 0.21902
  Regression -> MSE: 0.000124, MAE: 0.008968, R²: -0.3512
  Directional -> Accuracy: 0.4912, MCC: 0.0591, F1: 0.3556

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.29355 | val 0.16958
  Epoch 020 - train 0.27238 | val 0.17138
  Epoch 021 - train 0.26980 | val 0.17214
  Regression -> MSE: 0.000140, MAE: 0.009747, R²: -0.1171
  Directional -> Accuracy: 0.4167, MCC: 0.0000, F1: 0.5882

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.29033 | val 0.26448
  Epoch 020 - train 0.27160 | val 0.46516
  Epoch 026 - train 0.27053 | val 0.75996
  Regression -> MSE: 0.000240, MAE: 0.012795, R²: -0.0108
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.7429

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.27024 | val 0.36903
  Epoch 020 - train 0.26689 | val 0.39935
  Epoch 021 - train 0.25518 | val 0.40344
  Regression -> MSE: 0.000183, MAE: 0.007939, R²: -0.1171
  Directional -> Accuracy: 0.4483, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.28822 | val 0.22969
  Epoch 020 - train 0.27522 | val 0.23204
  Epoch 030 - train 0.26564 | val 0.38375
  Epoch 037 - train 0.24490 | val 0.49309
  Regression -> MSE: 0.000236, MAE: 0.012115, R²: -0.0058
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.27928 | val 0.48512
  Epoch 020 - train 0.26256 | val 0.51973
  Epoch 022 - train 0.27960 | val 0.52101
  Regression -> MSE: 0.000250, MAE: 0.010519, R²: 0.0012
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.28367 | val 0.45970
  Epoch 020 - train 0.27308 | val 0.48163
  Epoch 021 - train 0.26464 | val 0.48836
  Regression -> MSE: 0.000137, MAE: 0.008379, R²: -0.0284
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.27951 | val 0.40558
  Epoch 020 - train 0.26240 | val 0.51323
  Epoch 030 - train 0.24714 | val 0.58972
  Epoch 032 - train 0.24626 | val 0.57638
  Regression -> MSE: 0.000193, MAE: 0.010690, R²: -0.0239
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.23790 | val 0.37957
  Epoch 020 - train 0.22615 | val 0.38463
  Epoch 030 - train 0.22025 | val 0.40212
  Epoch 034 - train 0.21216 | val 0.38209
  Regression -> MSE: 0.000295, MAE: 0.011997, R²: -0.1417
  Directional -> Accuracy: 0.5405, MCC: 0.1186, F1: 0.5143

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 88). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.24290 | val 0.27799
  Epoch 020 - train 0.23436 | val 0.28710
  Epoch 021 - train 0.22666 | val 0.28907
  Regression -> MSE: 0.000162, MAE: 0.010172, R²: 0.0009
  Directional -> Accuracy: 0.4872, MCC: 0.0000, F1: 0.6552

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.24328 | val 0.32824
  Epoch 020 - train 0.24158 | val 0.39173
  Epoch 021 - train 0.23594 | val 0.40187
  Regression -> MSE: 0.000183, MAE: 0.010458, R²: -0.0033
  Directional -> Accuracy: 0.5333, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.26271 | val 0.27635
  Epoch 020 - train 0.24025 | val 0.29926
  Epoch 028 - train 0.24165 | val 0.30973
  Regression -> MSE: 0.000356, MAE: 0.012659, R²: -0.0214
  Directional -> Accuracy: 0.4265, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.28242 | val 0.19360
  Epoch 020 - train 0.25800 | val 0.19207
  Epoch 030 - train 0.25479 | val 0.20240
  Epoch 040 - train 0.23891 | val 0.21257
  Epoch 043 - train 0.22894 | val 0.22596
  Regression -> MSE: 0.000258, MAE: 0.012050, R²: -1.4845
  Directional -> Accuracy: 0.6364, MCC: 0.3062, F1: 0.5294

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.27951 | val 0.44123
  Epoch 020 - train 0.26549 | val 0.52191
  Epoch 021 - train 0.26575 | val 0.50990
  Regression -> MSE: 0.000216, MAE: 0.011213, R²: -0.0034
  Directional -> Accuracy: 0.5345, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.26556 | val 0.57643
  Epoch 020 - train 0.24536 | val 0.61209
  Epoch 026 - train 0.25253 | val 0.65470
  Regression -> MSE: 0.000084, MAE: 0.007200, R²: -0.0621
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 88). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 88). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 88). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 88). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.27294 | val 0.25883
  Epoch 020 - train 0.27256 | val 0.25495
  Epoch 030 - train 0.24856 | val 0.27649
  Epoch 040 - train 0.24027 | val 0.25457
  Epoch 050 - train 0.25579 | val 0.32055
  Regression -> MSE: 0.000842, MAE: 0.025886, R²: -1.5645
  Directional -> Accuracy: 0.3500, MCC: -0.0721, F1: 0.5000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 88). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.28450 | val 0.19378
  Epoch 020 - train 0.26737 | val 0.19708
  Epoch 024 - train 0.25642 | val 0.20494
  Regression -> MSE: 0.000248, MAE: 0.011197, R²: -0.0430
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.7000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 88). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 88). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.26196 | val 0.39263
  Epoch 020 - train 0.24765 | val 0.48862
  Epoch 025 - train 0.23984 | val 0.52502
  Regression -> MSE: 0.000082, MAE: 0.007003, R²: -0.0222
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 88). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 88). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 88). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.28550 | val 0.35619
  Epoch 020 - train 0.27198 | val 0.34803
  Epoch 030 - train 0.25665 | val 0.40121
  Epoch 036 - train 0.26110 | val 0.48147
  Regression -> MSE: 0.000366, MAE: 0.015333, R²: -0.0160
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.4000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.24757 | val 0.42576
  Epoch 020 - train 0.24164 | val 0.41936
  Epoch 030 - train 0.23329 | val 0.41101
  Epoch 040 - train 0.22732 | val 0.40363
  Epoch 050 - train 0.22002 | val 0.39964
  Regression -> MSE: 0.000096, MAE: 0.006942, R²: 0.0065

[I 2026-02-22 20:50:34,644] Trial 9 finished with value: -0.012181540669240026 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 12, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.1, 'batch_size': 64, 'learning_rate': 0.0008857956779333243, 'weight_decay': 0.00016892908533815831, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 50, 'huber_delta': 0.6167074462775695, 'early_stopping_min_delta': 0.0012537294775987872}. Best is trial 3 with value: -0.011473394984568777.

  Epoch 020 - train 0.26639 | val 0.96590
  Epoch 021 - train 0.26676 | val 0.96959
  Regression -> MSE: 0.000240, MAE: 0.012264, R²: -0.0275
  Directional -> Accuracy: 0.5161, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.44999 | val 0.82050
  Epoch 020 - train 0.43584 | val 0.86003
  Regression -> MSE: 0.000244, MAE: 0.012372, R²: -0.0152
  Directional -> Accuracy: 0.5921, MCC: 0.2925, F1: 0.6667

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.48607 | val 0.48905
  Epoch 015 - train 0.46684 | val 0.48090
  Regression -> MSE: 0.000693, MAE: 0.019483, R²: 0.0074
  Directional -> Accuracy: 0.6000, MCC: 0.1802, F1: 0.6538

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.49688 | val 1.04917
  Epoch 020 - train 0.46297 | val 1.03980
  Regression -> MSE: 0.000318, MAE: 0.014247, R²: -0.0115
  Directional -> Accuracy: 0.5435, MCC: 0.1633, F1: 0.3226

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.40662 | val 0.50339
  Epoch 011 - train 0.40921 | val 0.48510
  Regression -> MSE: 0.000353, MAE: 0.014643, R²: 0.0003
  Directional -> Accuracy: 0.5676, MCC: 0.1808, F1: 0.7143

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.46995 | val 0.45223
  Epoch 020 - train 0.47124 | val 0.43941
  Regression -> MSE: 0.000211, MAE: 0.010566, R²: -0.0226
  Directional -> Accuracy: 0.4400, MCC: -0.1267, F1: 0.1765

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.45431 | val 1.17342
  Epoch 012 - train 0.44383 | val 1.15521
  Regression -> MSE: 0.000589, MAE: 0.019056, R²: -0.0405
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.6471

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.45320 | val 0.71664
  Epoch 020 - train 0.47089 | val 0.68205
  Regression -> MSE: 0.000246, MAE: 0.012022, R²: 0.0101
  Directional -> Accuracy: 0.5294, MCC: 0.0663, F1: 0.4839

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.67479 | val 0.39123
  Epoch 015 - train 0.46354 | val 0.33851
  Regression -> MSE: 0.000609, MAE: 0.019195, R²: 0.0040
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.49168 | val 0.65445
  Epoch 013 - train 0.48902 | val 0.67695
  Regression -> MSE: 0.000377, MAE: 0.015538, R²: -0.0105
  Directional -> Accuracy: 0.5625, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.48997 | val 0.75849
  Epoch 011 - train 0.46693 | val 0.77988
  Regression -> MSE: 0.000243, MAE: 0.012036, R²: 0.0077
  Directional -> Accuracy: 0.4928, MCC: 0.0527, F1: 0.5455

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.48924 | val 0.82151
  Epoch 015 - train 0.45880 | val 0.90102
  Regression -> MSE: 0.000314, MAE: 0.013443, R²: -0.0042
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.47240 | val 0.65505
  Epoch 015 - train 0.49441 | val 0.64228
  Regression -> MSE: 0.000682, MAE: 0.019757, R²: 0.0048
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.48676 | val 0.59945
  Epoch 012 - train 0.47979 | val 0.63348
  Regression -> MSE: 0.000139, MAE: 0.009188, R²: -0.0034
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.41945 | val 0.75426
  Epoch 011 - train 0.40713 | val 0.74663
  Regression -> MSE: 0.000218, MAE: 0.010435, R²: 0.0368
  Directional -> Accuracy: 0.5500, MCC: 0.1048, F1: 0.6087

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.47240 | val 1.48775
  Epoch 011 - train 0.46946 | val 1.48954
  Regression -> MSE: 0.000370, MAE: 0.016090, R²: -0.0089
  Directional -> Accuracy: 0.4314, MCC: -0.1746, F1: 0.2927

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.49391 | val 0.50726
  Epoch 016 - train 0.50089 | val 0.50331
  Regression -> MSE: 0.000108, MAE: 0.007947, R²: 0.0042
  Directional -> Accuracy: 0.5072, MCC: -0.1063, F1: 0.6667

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.45024 | val 1.13363
  Epoch 020 - train 0.44739 | val 1.17912
  Regression -> MSE: 0.000161, MAE: 0.010118, R²: -0.0224
  Directional -> Accuracy: 0.5172, MCC: 0.1186, F1: 0.5000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.45389 | val 0.56614
  Epoch 012 - train 0.47593 | val 0.54901
  Regression -> MSE: 0.000295, MAE: 0.013930, R²: -0.0760
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.39929 | val 0.74024
  Epoch 020 - train 0.39303 | val 0.72406
  Regression -> MSE: 0.000251, MAE: 0.012340, R²: -0.6540
  Directional -> Accuracy: 0.4219, MCC: -0.0284, F1: 0.0513

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.48543 | val 1.01964
  Epoch 020 - train 0.46179 | val 1.01882
  Regression -> MSE: 0.000313, MAE: 0.013007, R²: -0.3774
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.44371 | val 0.78945
  Epoch 015 - train 0.44888 | val 0.74616
  Regression -> MSE: 0.000156, MAE: 0.008851, R²: -0.0851
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.44370 | val 0.66394
  Epoch 013 - train 0.45582 | val 0.66312
  Regression -> MSE: 0.000172, MAE: 0.010190, R²: -0.0391
  Directional -> Accuracy: 0.5846, MCC: 0.1795, F1: 0.5263

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.49068 | val 0.69636
  Epoch 020 - train 0.45635 | val 0.69747
  Regression -> MSE: 0.000089, MAE: 0.007386, R²: -0.0314
  Directional -> Accuracy: 0.5439, MCC: 0.1093, F1: 0.5357

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.48192 | val 0.71282
  Epoch 020 - train 0.46029 | val 0.76422
  Regression -> MSE: 0.000207, MAE: 0.010962, R²: 0.0173
  Directional -> Accuracy: 0.5846, MCC: 0.1798, F1: 0.6087

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.46643 | val 0.36842
  Epoch 020 - train 0.40238 | val 0.36012
  Regression -> MSE: 0.000093, MAE: 0.007856, R²: -0.0300
  Directional -> Accuracy: 0.6000, MCC: 0.1933, F1: 0.6333

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.51283 | val 0.41484
  Epoch 015 - train 0.54752 | val 0.39451
  Regression -> MSE: 0.000100, MAE: 0.008585, R²: -0.0073
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.52322 | val 0.47591
  Epoch 011 - train 0.48890 | val 0.47942
  Regression -> MSE: 0.000241, MAE: 0.012985, R²: -0.0181
  Directional -> Accuracy: 0.5714, MCC: 0.0589, F1: 0.7000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.46610 | val 0.60616
  Epoch 020 - train 0.45041 | val 0.61072
  Regression -> MSE: 0.000221, MAE: 0.009517, R²: -0.3043
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.65156 | val 0.30604
  Epoch 013 - train 0.58889 | val 0.31490
  Regression -> MSE: 0.000242, MAE: 0.012204, R²: -0.0003
  Directional -> Accuracy: 0.5250, MCC: 0.0453, F1: 0.5581

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.56029 | val 1.11536
  Epoch 012 - train 0.50258 | val 1.10397
  Regression -> MSE: 0.000222, MAE: 0.010226, R²: 0.0565
  Directional -> Accuracy: 0.4762, MCC: -0.0413, F1: 0.5000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.50413 | val 0.64565
  Epoch 017 - train 0.43667 | val 0.69449
  Regression -> MSE: 0.000138, MAE: 0.008338, R²: -0.0022
  Directional -> Accuracy: 0.5476, MCC: 0.1972, F1: 0.3871

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.46705 | val 0.76161
  Epoch 016 - train 0.46891 | val 0.77026
  Regression -> MSE: 0.000183, MAE: 0.010119, R²: -0.0005
  Directional -> Accuracy: 0.6122, MCC: 0.2724, F1: 0.7246

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.42883 | val 0.66388
  Epoch 011 - train 0.42433 | val 0.66917
  Regression -> MSE: 0.000272, MAE: 0.010745, R²: -0.0228
  Directional -> Accuracy: 0.5694, MCC: 0.1732, F1: 0.5373

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.44830 | val 0.56815
  Epoch 011 - train 0.43095 | val 0.57753
  Regression -> MSE: 0.000186, MAE: 0.010485, R²: -0.0161
  Directional -> Accuracy: 0.4884, MCC: -0.0238, F1: 0.4762

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.46639 | val 0.43771
  Epoch 012 - train 0.45030 | val 0.43501
  Regression -> MSE: 0.000364, MAE: 0.013272, R²: -0.0466
  Directional -> Accuracy: 0.4242, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.49538 | val 0.25728
  Epoch 011 - train 0.43285 | val 0.25365
  Regression -> MSE: 0.000121, MAE: 0.008298, R²: -0.1409
  Directional -> Accuracy: 0.6429, MCC: 0.3290, F1: 0.5714

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.49944 | val 0.88749
  Epoch 020 - train 0.46329 | val 0.88304
  Regression -> MSE: 0.000226, MAE: 0.011362, R²: -0.0276
  Directional -> Accuracy: 0.5179, MCC: 0.0234, F1: 0.4490

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.49609 | val 1.27921
  Epoch 012 - train 0.45915 | val 1.27267
  Regression -> MSE: 0.000075, MAE: 0.006788, R²: -0.0149
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.53729 | val 0.23978
  Epoch 015 - train 0.47632 | val 0.26729
  Regression -> MSE: 0.000351, MAE: 0.015900, R²: -0.1275
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.43896 | val 0.69660
  Epoch 013 - train 0.43347 | val 0.70004
  Regression -> MSE: 0.000077, MAE: 0.006910, R²: 0.0101
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.53200 | val 0.67334
  Epoch 019 - train 0.46579 | val 0.69476
  Regression -> MSE: 0.000299, MAE: 0.014354, R²: 0.0046
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.46286 | val 0.60818
  Epoch 016 - train 0.49480 | val 0.62591
  Regression -> MSE: 0.000105, MAE: 0.007285, R²: -0.0374
  Directional -> Accuracy: 0.6190, MCC: 0.2582, F1: 0.7500

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.53137 | val 0.84621
  Epoch 020 - train 0.47620 | val 0.83968
  Regression -> MSE: 0.000186, MAE: 0.010581, R²: -0.0627
  Directional -> Accuracy: 0.4167, MCC: 0.0000, F1: 0.5172

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.43767 | val 0.60700
  Epoch 020 - train 0.43616 | val 0.62869
  Regression -> MSE: 0.000226, MAE: 0.011676, R²: -0.0019
  Directional -> Accuracy: 0.5818, MCC: 0.1596, F1: 0.6102

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.47877 | val 0.69967
  Epoch 017 - train 0.46141 | val 0.67651
  Regression -> MSE: 0.000097, MAE: 0.007991, R²: -0.0345
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.52579 | val 1.02102
  Epoch 020 - train 0.48658 | val 1.02726
  Regression -> MSE: 0.000164, MAE: 0.010268, R²: 0.0137
  Directional -> Accuracy: 0.5472, MCC: 0.2018, F1: 0.6923

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.45967 | val 0.87207
  Epoch 011 - train 0.48555 | val 0.80983
  Regression -> MSE: 0.000120, MAE: 0.009118, R²: -0.0179
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.47598 | val 0.98338

[I 2026-02-22 20:52:50,888] Trial 10 finished with value: -0.011667158499353333 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.1, 'dropout': 0.8, 'batch_size': 64, 'learning_rate': 0.007536901282062639, 'weight_decay': 3.8790741729617675e-06, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 1.9081105523942616, 'early_stopping_min_delta': 0.0031584079854126068}. Best is trial 3 with value: -0.011473394984568777.

  Epoch 013 - train 0.50990 | val 1.02969
  Regression -> MSE: 0.000241, MAE: 0.012360, R²: -0.0039
  Directional -> Accuracy: 0.5167, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 36
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.30585 | val 0.99062
  Epoch 018 - train 0.23900 | val 1.03212
  Regression -> MSE: 0.000249, MAE: 0.012543, R²: -0.0601
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.6168

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 112). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.30139 | val 0.69510
  Epoch 020 - train 0.23233 | val 0.76634
  Regression -> MSE: 0.000693, MAE: 0.019159, R²: 0.0282
  Directional -> Accuracy: 0.6047, MCC: 0.0000, F1: 0.7536

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for AEP (109 < 112). Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 112). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.28877 | val 1.38292
  Epoch 016 - train 0.22051 | val 1.90860
  Regression -> MSE: 0.000321, MAE: 0.014669, R²: -0.0079
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.6866

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.30044 | val 0.72827
  Epoch 020 - train 0.23722 | val 0.88809
  Regression -> MSE: 0.000490, MAE: 0.018061, R²: -0.3731
  Directional -> Accuracy: 0.5139, MCC: 0.2231, F1: 0.1860

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.30455 | val 0.53233
  Epoch 020 - train 0.20595 | val 0.84705
  Regression -> MSE: 0.000196, MAE: 0.009062, R²: 0.0703
  Directional -> Accuracy: 0.7292, MCC: 0.4630, F1: 0.7636

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.21815 | val 1.21892
  Epoch 016 - train 0.15727 | val 1.40850
  Regression -> MSE: 0.000590, MAE: 0.018602, R²: -0.0529
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.31491 | val 1.89570
  Epoch 016 - train 0.24969 | val 1.60889
  Regression -> MSE: 0.000254, MAE: 0.012167, R²: 0.0044
  Directional -> Accuracy: 0.6061, MCC: 0.1491, F1: 0.0714

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 112). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 112). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.21269 | val 0.77640
  Epoch 016 - train 0.17744 | val 1.17149
  Regression -> MSE: 0.000594, MAE: 0.019108, R²: -0.0253
  Directional -> Accuracy: 0.4359, MCC: 0.0000, F1: 0.6071

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.25980 | val 0.79733
  Epoch 016 - train 0.19916 | val 1.32100
  Regression -> MSE: 0.000379, MAE: 0.016015, R²: 0.0061
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 112). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 112). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 112). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.30909 | val 1.15675
  Epoch 018 - train 0.23435 | val 1.56123
  Regression -> MSE: 0.000245, MAE: 0.011989, R²: 0.0053
  Directional -> Accuracy: 0.5224, MCC: 0.0906, F1: 0.5429

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.28344 | val 2.63179
  Epoch 016 - train 0.22671 | val 2.96714
  Regression -> MSE: 0.000311, MAE: 0.013403, R²: 0.0050
  Directional -> Accuracy: 0.6170, MCC: 0.2905, F1: 0.2500

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.29470 | val 0.94084
  Epoch 016 - train 0.23283 | val 1.02153
  Regression -> MSE: 0.000695, MAE: 0.019678, R²: -0.0000
  Directional -> Accuracy: 0.5455, MCC: 0.2652, F1: 0.2424

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 112). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.22883 | val 0.55078
  Epoch 020 - train 0.13968 | val 0.47798
  Regression -> MSE: 0.000176, MAE: 0.010233, R²: -0.2179
  Directional -> Accuracy: 0.6250, MCC: 0.2522, F1: 0.6250

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 112). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.30172 | val 0.83312
  Epoch 020 - train 0.20984 | val 1.27584
  Regression -> MSE: 0.000219, MAE: 0.010358, R²: 0.0454
  Directional -> Accuracy: 0.6034, MCC: 0.2079, F1: 0.6667

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.28921 | val 1.79075
  Epoch 017 - train 0.23159 | val 1.78416
  Regression -> MSE: 0.000372, MAE: 0.016191, R²: 0.0049
  Directional -> Accuracy: 0.4694, MCC: 0.0043, F1: 0.5806

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.30363 | val 1.09269
  Epoch 017 - train 0.23332 | val 1.19259
  Regression -> MSE: 0.000107, MAE: 0.007859, R²: 0.0240
  Directional -> Accuracy: 0.5373, MCC: 0.0419, F1: 0.6437

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 112). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.28696 | val 3.21493
  Epoch 016 - train 0.23594 | val 2.91412
  Regression -> MSE: 0.000150, MAE: 0.009722, R²: 0.0084
  Directional -> Accuracy: 0.6429, MCC: 0.2197, F1: 0.7297

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.30618 | val 1.02460
  Epoch 016 - train 0.23954 | val 0.76467
  Regression -> MSE: 0.000284, MAE: 0.013490, R²: -0.0262
  Directional -> Accuracy: 0.4110, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.27616 | val 1.27295
  Epoch 016 - train 0.22820 | val 1.24149
  Regression -> MSE: 0.000172, MAE: 0.009455, R²: -0.1175
  Directional -> Accuracy: 0.5161, MCC: 0.1463, F1: 0.4000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 112). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.30119 | val 1.07873
  Epoch 019 - train 0.20243 | val 1.14377
  Regression -> MSE: 0.000260, MAE: 0.011841, R²: -0.1422
  Directional -> Accuracy: 0.3889, MCC: -0.1942, F1: 0.2143

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.24612 | val 0.86475
  Epoch 016 - train 0.19058 | val 1.30833
  Regression -> MSE: 0.000147, MAE: 0.008295, R²: 0.0082
  Directional -> Accuracy: 0.6000, MCC: 0.0000, F1: 0.7500

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 112). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 112). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 112). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.31405 | val 0.78164
  Epoch 016 - train 0.26283 | val 0.72834
  Regression -> MSE: 0.000171, MAE: 0.010554, R²: -0.0022
  Directional -> Accuracy: 0.4921, MCC: 0.0000, F1: 0.6596

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.31049 | val 1.36615
  Epoch 016 - train 0.25084 | val 1.53453
  Regression -> MSE: 0.000088, MAE: 0.007222, R²: 0.0066
  Directional -> Accuracy: 0.5818, MCC: 0.0000, F1: 0.7356

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.29421 | val 1.38411
  Epoch 016 - train 0.25947 | val 0.96770
  Regression -> MSE: 0.000217, MAE: 0.011168, R²: -0.0031
  Directional -> Accuracy: 0.5238, MCC: 0.0086, F1: 0.0625

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.23579 | val 0.52276
  Epoch 019 - train 0.19037 | val 0.80223
  Regression -> MSE: 0.000090, MAE: 0.007788, R²: 0.0012
  Directional -> Accuracy: 0.5283, MCC: 0.0175, F1: 0.6269

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.28917 | val 0.51528
  Epoch 020 - train 0.19618 | val 0.74022
  Regression -> MSE: 0.000091, MAE: 0.008015, R²: 0.0096
  Directional -> Accuracy: 0.5238, MCC: 0.2810, F1: 0.6429

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.28242 | val 1.47421
  Epoch 016 - train 0.24940 | val 2.49251
  Regression -> MSE: 0.000283, MAE: 0.013227, R²: -0.0173
  Directional -> Accuracy: 0.5833, MCC: 0.0000, F1: 0.7368

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.29529 | val 0.68681
  Epoch 020 - train 0.20729 | val 0.88395
  Regression -> MSE: 0.000248, MAE: 0.010225, R²: -0.4428
  Directional -> Accuracy: 0.4630, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
Insufficient data for proper time series validation for MDT. Skipping...

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.25423 | val 1.16135
  Epoch 019 - train 0.17958 | val 1.27816
  Regression -> MSE: 0.000241, MAE: 0.010149, R²: -0.0047
  Directional -> Accuracy: 0.5750, MCC: 0.2847, F1: 0.7018

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.22643 | val 0.74699
  Epoch 016 - train 0.16686 | val 1.05004
  Regression -> MSE: 0.000146, MAE: 0.008572, R²: -0.0270
  Directional -> Accuracy: 0.6250, MCC: 0.2347, F1: 0.7170

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.28306 | val 0.70495
  Epoch 020 - train 0.18569 | val 0.82515
  Regression -> MSE: 0.000228, MAE: 0.011869, R²: -0.1944
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.26683 | val 0.86034
  Epoch 019 - train 0.20491 | val 1.03091
  Regression -> MSE: 0.000465, MAE: 0.015407, R²: -0.7512
  Directional -> Accuracy: 0.4429, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 112). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.23867 | val 0.49581
  Epoch 017 - train 0.18685 | val 0.71959
  Regression -> MSE: 0.000210, MAE: 0.011082, R²: -0.0083
  Directional -> Accuracy: 0.4694, MCC: 0.0000, F1: 0.6389

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 112). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.28502 | val 0.49618
  Epoch 020 - train 0.21309 | val 0.50120
  Regression -> MSE: 0.000434, MAE: 0.015581, R²: -0.2155
  Directional -> Accuracy: 0.5000, MCC: 0.2277, F1: 0.2000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.22587 | val 0.30235
  Epoch 020 - train 0.12815 | val 0.70400
  Regression -> MSE: 0.000112, MAE: 0.007872, R²: -0.1556
  Directional -> Accuracy: 0.5510, MCC: 0.1322, F1: 0.2667

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.27145 | val 1.15769
  Epoch 018 - train 0.18859 | val 1.38933
  Regression -> MSE: 0.000220, MAE: 0.011247, R²: -0.0135
  Directional -> Accuracy: 0.4815, MCC: 0.0016, F1: 0.5758

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.23534 | val 1.72556
  Epoch 016 - train 0.18217 | val 1.58986
  Regression -> MSE: 0.000081, MAE: 0.006953, R²: -0.1267
  Directional -> Accuracy: 0.3864, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 112). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for PPL (108 < 112). Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 112). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 112). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 112). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.26952 | val 0.28302
  Epoch 020 - train 0.18688 | val 0.35980
  Regression -> MSE: 0.000636, MAE: 0.020860, R²: -1.1296
  Directional -> Accuracy: 0.4000, MCC: 0.0434, F1: 0.4906

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 112). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 112). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 112). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.27480 | val 1.87609
  Epoch 017 - train 0.23219 | val 1.89412
  Regression -> MSE: 0.000079, MAE: 0.006940, R²: -0.0029
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 112). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 112). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 112). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 112). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.25924 | val 1.66470
  Epoch 016 - train 0.21180 | val 4.77139
  Regression -> MSE: 0.000288, MAE: 0.013939, R²: -0.0191
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.26514 | val 0.43260
  Epoch 016 - train 0.19679 | val 0.43553
  Regression -> MSE: 0.000110, MAE: 0.007588, R²: -0.0072
  Directional -> Accuracy: 0.5897, MCC: 0.0000, F1: 0.7419

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.25126 | val 0.94515
  Epoch 016 - train 0.18130 | val 1.07510
  Regression -> MSE: 0.000185, MAE: 0.010474, R²: -0.0173
  Directional -> Accuracy: 0.3778, MCC: 0.0000, F1: 0.5484

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.27990 | val 0.98141
  Epoch 016 - train 0.21633 | val 1.15216
  Regression -> MSE: 0.000234, MAE: 0.011904, R²: -0.0139
  Directional -> Accuracy: 0.5283, MCC: 0.2054, F1: 0.2857

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.25074 | val 1.50399
  Epoch 016 - train 0.21488 | val 1.96794
  Regression -> MSE: 0.000088, MAE: 0.007545, R²: -0.0033
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.30556 | val 3.45767
  Epoch 017 - train 0.20514 | val 5.98620
  Regression -> MSE: 0.000171, MAE: 0.010416, R²: -0.0049
  Directional -> Accuracy: 0.5294, MCC: 0.0557, F1: 0.4000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.29521 | val 1.44945
  Epoch 016 - train 0.22775 | val 1.79846
  Regression -> MSE: 0.000118, MAE: 0.009068, R²: -0.0006
  Directional -> Accuracy: 0.5094, MCC: 0.0000, F1: 0.6750

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.30731 | val 4.28774

[I 2026-02-22 20:55:14,106] Trial 11 finished with value: -0.01191862783283372 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 36, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.4, 'dropout': 0.0, 'batch_size': 32, 'learning_rate': 0.0008312350918012798, 'weight_decay': 7.756251273715813e-07, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 1.6374646793172536, 'early_stopping_min_delta': 0.005326759301606015}. Best is trial 3 with value: -0.011473394984568777.

  Epoch 016 - train 0.24153 | val 6.23528
  Regression -> MSE: 0.000247, MAE: 0.012610, R²: 0.0027
  Directional -> Accuracy: 0.6034, MCC: 0.1984, F1: 0.5490

================================================================================
Pipeline completed: 47/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (47, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 30
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.40550 | val 0.82375
  Epoch 020 - train 0.38247 | val 0.81422
  Regression -> MSE: 0.000264, MAE: 0.012742, R²: -0.1068
  Directional -> Accuracy: 0.4800, MCC: 0.1507, F1: 0.6355

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 106). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.42101 | val 0.51120
  Epoch 016 - train 0.40625 | val 0.56181
  Regression -> MSE: 0.000749, MAE: 0.020535, R²: -0.0621
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 106). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.43402 | val 0.97088
  Epoch 020 - train 0.41087 | val 1.03929
  Regression -> MSE: 0.000340, MAE: 0.014819, R²: -0.0569
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.34663 | val 0.47931
  Epoch 016 - train 0.33677 | val 0.52216
  Regression -> MSE: 0.000380, MAE: 0.015219, R²: -0.0667
  Directional -> Accuracy: 0.5342, MCC: 0.0000, F1: 0.6964

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.39349 | val 0.44698
  Epoch 020 - train 0.37997 | val 0.51277
  Regression -> MSE: 0.000212, MAE: 0.010281, R²: -0.0072
  Directional -> Accuracy: 0.5306, MCC: 0.0617, F1: 0.5306

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.40008 | val 1.01181
  Epoch 016 - train 0.39169 | val 1.15740
  Regression -> MSE: 0.000587, MAE: 0.018634, R²: -0.0227
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.40461 | val 0.67783
  Epoch 020 - train 0.38512 | val 0.73195
  Regression -> MSE: 0.000250, MAE: 0.012138, R²: 0.0065
  Directional -> Accuracy: 0.5373, MCC: 0.0673, F1: 0.4746

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 106). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 106). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.39847 | val 0.39698
  Epoch 016 - train 0.38768 | val 0.72713
  Regression -> MSE: 0.000625, MAE: 0.019734, R²: 0.0004
  Directional -> Accuracy: 0.5610, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.40370 | val 0.73857
  Epoch 016 - train 0.39506 | val 0.81220
  Regression -> MSE: 0.000375, MAE: 0.015854, R²: -0.0034
  Directional -> Accuracy: 0.4468, MCC: 0.0000, F1: 0.6176

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 106). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 106). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 106). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.41863 | val 0.87670
  Epoch 016 - train 0.40687 | val 0.84860
  Regression -> MSE: 0.000249, MAE: 0.012197, R²: -0.0006
  Directional -> Accuracy: 0.4265, MCC: 0.0000, F1: 0.5979

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.39087 | val 0.94802
  Epoch 016 - train 0.38632 | val 1.14087
  Regression -> MSE: 0.000331, MAE: 0.013561, R²: -0.0553
  Directional -> Accuracy: 0.5417, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.43594 | val 0.62148
  Epoch 020 - train 0.40853 | val 0.63623
  Regression -> MSE: 0.000673, MAE: 0.019418, R²: 0.0347
  Directional -> Accuracy: 0.6071, MCC: 0.2425, F1: 0.7027

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 106). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.43482 | val 0.62492
  Epoch 016 - train 0.41585 | val 0.94820
  Regression -> MSE: 0.000142, MAE: 0.009299, R²: -0.0017
  Directional -> Accuracy: 0.4898, MCC: 0.0000, F1: 0.6575

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 106). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.35232 | val 0.81081
  Epoch 016 - train 0.36046 | val 0.85389
  Regression -> MSE: 0.000230, MAE: 0.010748, R²: -0.0043
  Directional -> Accuracy: 0.5085, MCC: 0.0000, F1: 0.6742

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.40254 | val 1.40539
  Epoch 019 - train 0.37907 | val 1.35532
  Regression -> MSE: 0.000365, MAE: 0.015966, R²: 0.0027
  Directional -> Accuracy: 0.6000, MCC: 0.2451, F1: 0.6296

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.42979 | val 0.46055
  Epoch 020 - train 0.41207 | val 0.46785
  Regression -> MSE: 0.000111, MAE: 0.007958, R²: -0.0283
  Directional -> Accuracy: 0.5294, MCC: 0.0183, F1: 0.6735

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 106). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.40218 | val 1.12281
  Epoch 016 - train 0.38210 | val 1.12574
  Regression -> MSE: 0.000153, MAE: 0.009930, R²: -0.0292
  Directional -> Accuracy: 0.3860, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.40952 | val 0.68029
  Epoch 016 - train 0.39659 | val 0.78478
  Regression -> MSE: 0.000281, MAE: 0.013407, R²: -0.0172
  Directional -> Accuracy: 0.3919, MCC: -0.1417, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.34983 | val 0.82628
  Epoch 020 - train 0.33771 | val 0.88951
  Regression -> MSE: 0.000168, MAE: 0.009469, R²: -0.1087
  Directional -> Accuracy: 0.5238, MCC: 0.1884, F1: 0.4000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 106). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.41330 | val 1.00728
  Epoch 016 - train 0.39137 | val 1.01956
  Regression -> MSE: 0.000228, MAE: 0.010859, R²: -0.0151
  Directional -> Accuracy: 0.5479, MCC: 0.0000, F1: 0.7080

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.41576 | val 0.74294
  Epoch 016 - train 0.39362 | val 0.73679
  Regression -> MSE: 0.000148, MAE: 0.008464, R²: -0.0093
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 106). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 106). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 106). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.39141 | val 0.60473
  Epoch 020 - train 0.36995 | val 0.63420
  Regression -> MSE: 0.000173, MAE: 0.010622, R²: -0.0262
  Directional -> Accuracy: 0.5312, MCC: 0.0756, F1: 0.6341

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.42683 | val 0.71896
  Epoch 019 - train 0.40333 | val 0.80213
  Regression -> MSE: 0.000089, MAE: 0.007241, R²: -0.0080
  Directional -> Accuracy: 0.5714, MCC: 0.0833, F1: 0.6757

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.41007 | val 0.80603
  Epoch 016 - train 0.40192 | val 0.80864
  Regression -> MSE: 0.000216, MAE: 0.011012, R²: -0.0097
  Directional -> Accuracy: 0.5312, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.35638 | val 0.34758
  Epoch 020 - train 0.32636 | val 0.34762
  Regression -> MSE: 0.000094, MAE: 0.007952, R²: -0.0256
  Directional -> Accuracy: 0.5185, MCC: 0.0428, F1: 0.5185

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.44576 | val 0.41097
  Epoch 020 - train 0.39954 | val 0.42464
  Regression -> MSE: 0.000097, MAE: 0.008440, R²: -0.0026
  Directional -> Accuracy: 0.5116, MCC: 0.0866, F1: 0.5532

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.44438 | val 0.32406
  Epoch 016 - train 0.42873 | val 0.49232
  Regression -> MSE: 0.000289, MAE: 0.013355, R²: -0.0610
  Directional -> Accuracy: 0.4082, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.41145 | val 0.57943
  Epoch 020 - train 0.39783 | val 0.60280
  Regression -> MSE: 0.000193, MAE: 0.008020, R²: -0.1395
  Directional -> Accuracy: 0.5273, MCC: 0.2557, F1: 0.2353

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.41950 | val 0.30614
  Epoch 016 - train 0.43968 | val 0.30749
  Regression -> MSE: 0.000252, MAE: 0.012392, R²: -0.0020
  Directional -> Accuracy: 0.5526, MCC: 0.0000, F1: 0.7119

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.43268 | val 1.02145
  Epoch 016 - train 0.43473 | val 1.04986
  Regression -> MSE: 0.000235, MAE: 0.009900, R²: -0.0072
  Directional -> Accuracy: 0.5122, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.40848 | val 0.64681
  Epoch 016 - train 0.41018 | val 0.73913
  Regression -> MSE: 0.000141, MAE: 0.008392, R²: -0.0162
  Directional -> Accuracy: 0.5610, MCC: 0.0000, F1: 0.7188

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.40508 | val 0.66043
  Epoch 020 - train 0.37951 | val 0.66175
  Regression -> MSE: 0.000186, MAE: 0.010169, R²: 0.0028
  Directional -> Accuracy: 0.6042, MCC: 0.2680, F1: 0.7164

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.34848 | val 0.62565
  Epoch 020 - train 0.32986 | val 0.64588
  Regression -> MSE: 0.000281, MAE: 0.010847, R²: -0.0537
  Directional -> Accuracy: 0.5211, MCC: 0.1508, F1: 0.3704

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 106). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.37166 | val 0.52937
  Epoch 020 - train 0.36016 | val 0.50793
  Regression -> MSE: 0.000208, MAE: 0.011300, R²: -0.1069
  Directional -> Accuracy: 0.5238, MCC: 0.0337, F1: 0.4118

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 106). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.41367 | val 0.55260
  Epoch 016 - train 0.39699 | val 0.54329
  Regression -> MSE: 0.000377, MAE: 0.013461, R²: -0.0700
  Directional -> Accuracy: 0.4308, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.44795 | val 0.22381
  Epoch 020 - train 0.39035 | val 0.28275
  Regression -> MSE: 0.000120, MAE: 0.008371, R²: -0.0940
  Directional -> Accuracy: 0.6500, MCC: 0.3394, F1: 0.5882

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.40568 | val 0.83728
  Epoch 020 - train 0.37007 | val 0.95881
  Regression -> MSE: 0.000225, MAE: 0.011499, R²: -0.0041
  Directional -> Accuracy: 0.5091, MCC: -0.0219, F1: 0.3415

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.40129 | val 1.21173
  Epoch 016 - train 0.37603 | val 1.36497
  Regression -> MSE: 0.000077, MAE: 0.006795, R²: -0.0909
  Directional -> Accuracy: 0.4444, MCC: 0.0815, F1: 0.2857

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 106). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 106). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 106). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 106). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.38620 | val 0.23371
  Epoch 020 - train 0.36650 | val 0.18834
  Regression -> MSE: 0.000662, MAE: 0.022742, R²: -1.0795
  Directional -> Accuracy: 0.3261, MCC: 0.0000, F1: 0.4918

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 106). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 106). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 106). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.38570 | val 0.76920
  Epoch 016 - train 0.37471 | val 0.80767
  Regression -> MSE: 0.000080, MAE: 0.006852, R²: -0.0392
  Directional -> Accuracy: 0.5068, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 106). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 106). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 106). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 106). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.42649 | val 0.72814
  Epoch 020 - train 0.43509 | val 0.78454
  Regression -> MSE: 0.000279, MAE: 0.013905, R²: -0.0020
  Directional -> Accuracy: 0.4545, MCC: -0.0945, F1: 0.5200

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.42554 | val 0.51813
  Epoch 016 - train 0.41193 | val 0.52176
  Regression -> MSE: 0.000104, MAE: 0.007574, R²: -0.0027
  Directional -> Accuracy: 0.4146, MCC: 0.0000, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.47509 | val 0.81195
  Epoch 016 - train 0.42661 | val 0.84718
  Regression -> MSE: 0.000192, MAE: 0.010936, R²: -0.0758
  Directional -> Accuracy: 0.3696, MCC: 0.0000, F1: 0.5397

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.38352 | val 0.86445
  Epoch 016 - train 0.36658 | val 1.09859
  Regression -> MSE: 0.000238, MAE: 0.012097, R²: -0.0455
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.38736 | val 0.78648
  Epoch 016 - train 0.38021 | val 0.86248
  Regression -> MSE: 0.000088, MAE: 0.007523, R²: -0.0022
  Directional -> Accuracy: 0.4909, MCC: 0.0000, F1: 0.6585

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.44745 | val 0.96141
  Epoch 020 - train 0.42158 | val 0.97058
  Regression -> MSE: 0.000168, MAE: 0.010312, R²: -0.0083
  Directional -> Accuracy: 0.5577, MCC: 0.1690, F1: 0.6761

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.40455 | val 0.66392
  Epoch 020 - train 0.38305 | val 0.66659
  Regression -> MSE: 0.000137, MAE: 0.009577, R²: -0.1447
  Directional -> Accuracy: 0.4444, MCC: -0.2035, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.43652 | val 0.92989

[I 2026-02-22 20:57:27,750] Trial 12 finished with value: -0.011772775707454379 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 30, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.4, 'dropout': 0.2, 'batch_size': 32, 'learning_rate': 3.514069733018245e-05, 'weight_decay': 1.0228804524584499e-07, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 1.5113464401826682, 'early_stopping_min_delta': 0.0027650472378622907}. Best is trial 3 with value: -0.011473394984568777.

  Epoch 020 - train 0.42577 | val 0.94518
  Regression -> MSE: 0.000247, MAE: 0.012573, R²: -0.0118
  Directional -> Accuracy: 0.5254, MCC: 0.0171, F1: 0.1765

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.46450 | val 0.80712
  Epoch 020 - train 0.42651 | val 0.83355
  Regression -> MSE: 0.000249, MAE: 0.012594, R²: -0.0053
  Directional -> Accuracy: 0.5065, MCC: 0.1199, F1: 0.6275

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.45614 | val 0.46003
  Epoch 020 - train 0.42281 | val 0.47456
  Epoch 025 - train 0.42171 | val 0.46967
  Regression -> MSE: 0.000650, MAE: 0.018571, R²: 0.0509
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.46196 | val 1.00032
  Epoch 020 - train 0.46574 | val 0.99494
  Epoch 029 - train 0.45449 | val 0.99840
  Regression -> MSE: 0.000317, MAE: 0.014343, R²: -0.0217
  Directional -> Accuracy: 0.5319, MCC: 0.1854, F1: 0.2667

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.36470 | val 0.57270
  Epoch 016 - train 0.37372 | val 0.60500
  Regression -> MSE: 0.000369, MAE: 0.014883, R²: -0.0556
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.45588 | val 0.44143
  Epoch 020 - train 0.43466 | val 0.46695
  Epoch 023 - train 0.42528 | val 0.47405
  Regression -> MSE: 0.000199, MAE: 0.009549, R²: 0.0239
  Directional -> Accuracy: 0.6078, MCC: 0.3094, F1: 0.7297

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.42276 | val 1.19072
  Epoch 016 - train 0.40224 | val 1.19525
  Regression -> MSE: 0.000558, MAE: 0.018152, R²: -0.0059
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.46752 | val 0.66598
  Epoch 020 - train 0.43274 | val 0.68737
  Epoch 030 - train 0.43363 | val 0.68578
  Regression -> MSE: 0.000246, MAE: 0.011850, R²: -0.0035
  Directional -> Accuracy: 0.5362, MCC: 0.0046, F1: 0.3600

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.44679 | val 0.80335
  Epoch 016 - train 0.41563 | val 0.98915
  Regression -> MSE: 0.000622, MAE: 0.019716, R²: -0.0414
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.47895 | val 0.61264
  Epoch 020 - train 0.43404 | val 0.66710
  Epoch 021 - train 0.43303 | val 0.66764
  Regression -> MSE: 0.000375, MAE: 0.015675, R²: 0.0214
  Directional -> Accuracy: 0.5714, MCC: 0.2278, F1: 0.6441

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.48750 | val 0.81055
  Epoch 016 - train 0.46429 | val 0.79399
  Regression -> MSE: 0.000242, MAE: 0.011723, R²: -0.0021
  Directional -> Accuracy: 0.4714, MCC: 0.0000, F1: 0.5316

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.42956 | val 0.98000
  Epoch 016 - train 0.41782 | val 1.09550
  Regression -> MSE: 0.000310, MAE: 0.013821, R²: 0.0016
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.6301

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.49973 | val 0.65392
  Epoch 016 - train 0.46915 | val 0.67796
  Regression -> MSE: 0.000690, MAE: 0.019993, R²: -0.0190
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.47537 | val 0.60941
  Epoch 016 - train 0.47514 | val 0.59832
  Regression -> MSE: 0.000139, MAE: 0.009017, R²: -0.0097
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.40993 | val 0.73845
  Epoch 016 - train 0.39426 | val 0.72801
  Regression -> MSE: 0.000225, MAE: 0.010680, R²: 0.0001
  Directional -> Accuracy: 0.5902, MCC: 0.1804, F1: 0.6269

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.44773 | val 1.48574
  Epoch 016 - train 0.45106 | val 1.53242
  Regression -> MSE: 0.000364, MAE: 0.016048, R²: -0.0049
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.47096 | val 0.54532
  Epoch 016 - train 0.46285 | val 0.53926
  Regression -> MSE: 0.000107, MAE: 0.007910, R²: 0.0043
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.43571 | val 1.21182
  Epoch 016 - train 0.43549 | val 1.22421
  Regression -> MSE: 0.000156, MAE: 0.009728, R²: -0.0007
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.46537 | val 0.51742
  Epoch 016 - train 0.48493 | val 0.51754
  Regression -> MSE: 0.000273, MAE: 0.013085, R²: -0.0035
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.37729 | val 0.71376
  Epoch 020 - train 0.36662 | val 0.70815
  Epoch 030 - train 0.36454 | val 0.71592
  Regression -> MSE: 0.000186, MAE: 0.009859, R²: -0.2415
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.43963 | val 0.92525
  Epoch 020 - train 0.46109 | val 0.94192
  Epoch 025 - train 0.42438 | val 0.94210
  Regression -> MSE: 0.000363, MAE: 0.014499, R²: -0.6061
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.47079 | val 0.73452
  Epoch 020 - train 0.45006 | val 0.74873
  Regression -> MSE: 0.000144, MAE: 0.008408, R²: -0.0027
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.44186 | val 0.62384
  Epoch 017 - train 0.43635 | val 0.60781
  Regression -> MSE: 0.000166, MAE: 0.010564, R²: -0.0032
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.49113 | val 0.70418
  Epoch 016 - train 0.49910 | val 0.70470
  Regression -> MSE: 0.000086, MAE: 0.007119, R²: -0.0141
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.48865 | val 0.79901
  Epoch 016 - train 0.46556 | val 0.91003
  Regression -> MSE: 0.000212, MAE: 0.011133, R²: 0.0007
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.39995 | val 0.33879
  Epoch 020 - train 0.37653 | val 0.33645
  Epoch 024 - train 0.38108 | val 0.33519
  Regression -> MSE: 0.000092, MAE: 0.007806, R²: 0.0024
  Directional -> Accuracy: 0.5893, MCC: 0.1878, F1: 0.5965

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.50553 | val 0.37736
  Epoch 019 - train 0.48629 | val 0.37175
  Regression -> MSE: 0.000114, MAE: 0.009114, R²: -0.1050
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.47202 | val 0.67280
  Epoch 016 - train 0.48474 | val 0.69635
  Regression -> MSE: 0.000239, MAE: 0.012800, R²: -0.0307
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.45546 | val 0.63358
  Epoch 020 - train 0.44295 | val 0.62653
  Epoch 022 - train 0.43885 | val 0.62638
  Regression -> MSE: 0.000194, MAE: 0.008280, R²: -0.1630
  Directional -> Accuracy: 0.4737, MCC: 0.0228, F1: 0.3182

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.49166 | val 0.30881
  Epoch 016 - train 0.49719 | val 0.33062
  Regression -> MSE: 0.000240, MAE: 0.011937, R²: -0.0133
  Directional -> Accuracy: 0.4634, MCC: 0.0000, F1: 0.0000

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.52650 | val 1.08276
  Epoch 016 - train 0.46283 | val 1.14908
  Regression -> MSE: 0.000231, MAE: 0.009874, R²: -0.0011
  Directional -> Accuracy: 0.4884, MCC: -0.0145, F1: 0.5769

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.47333 | val 0.72717
  Epoch 016 - train 0.49932 | val 0.79606
  Regression -> MSE: 0.000136, MAE: 0.008266, R²: -0.0071
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.47290 | val 0.71886
  Epoch 016 - train 0.45139 | val 0.71349
  Regression -> MSE: 0.000194, MAE: 0.010480, R²: -0.0310
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.41816 | val 0.61630
  Epoch 020 - train 0.39450 | val 0.61449
  Epoch 021 - train 0.39243 | val 0.61443
  Regression -> MSE: 0.000295, MAE: 0.011443, R²: -0.1270
  Directional -> Accuracy: 0.5479, MCC: 0.1851, F1: 0.4407

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.55837 | val 0.38456
  Epoch 016 - train 0.45397 | val 0.41895
  Regression -> MSE: 0.000166, MAE: 0.010336, R²: 0.0019
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.43495 | val 0.61990
  Epoch 016 - train 0.39776 | val 0.63396
  Regression -> MSE: 0.000180, MAE: 0.010295, R²: -0.0008
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.43823 | val 0.45440
  Epoch 019 - train 0.41690 | val 0.45814
  Regression -> MSE: 0.000364, MAE: 0.013196, R²: -0.0616
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.51237 | val 0.22944
  Epoch 020 - train 0.43605 | val 0.25994
  Epoch 025 - train 0.39217 | val 0.25445
  Regression -> MSE: 0.000131, MAE: 0.008320, R²: -0.2461
  Directional -> Accuracy: 0.6512, MCC: 0.3392, F1: 0.5714

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.45110 | val 0.87833
  Epoch 018 - train 0.39264 | val 0.90315
  Regression -> MSE: 0.000221, MAE: 0.011365, R²: -0.0098
  Directional -> Accuracy: 0.5614, MCC: 0.1968, F1: 0.6575

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.46260 | val 1.28605
  Epoch 016 - train 0.44831 | val 1.36797
  Regression -> MSE: 0.000083, MAE: 0.007103, R²: -0.0685
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.47574 | val 0.27382
  Epoch 016 - train 0.46401 | val 0.29315
  Regression -> MSE: 0.000309, MAE: 0.013931, R²: -0.0061
  Directional -> Accuracy: 0.6327, MCC: 0.1028, F1: 0.2500

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.45207 | val 0.20967
  Epoch 020 - train 0.43808 | val 0.24716
  Epoch 023 - train 0.46855 | val 0.26240
  Regression -> MSE: 0.000257, MAE: 0.011454, R²: -0.0539
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.43491 | val 0.63272
  Epoch 019 - train 0.40835 | val 0.64247
  Regression -> MSE: 0.000080, MAE: 0.007098, R²: 0.0118
  Directional -> Accuracy: 0.5333, MCC: 0.2014, F1: 0.6789

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.46740 | val 0.64631
  Epoch 016 - train 0.49804 | val 0.75753
  Regression -> MSE: 0.000312, MAE: 0.014530, R²: -0.0156
  Directional -> Accuracy: 0.5319, MCC: 0.1506, F1: 0.6857

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.42203 | val 0.57700
  Epoch 020 - train 0.45575 | val 0.58345
  Epoch 023 - train 0.45635 | val 0.57992
  Regression -> MSE: 0.000097, MAE: 0.007083, R²: 0.0115
  Directional -> Accuracy: 0.5682, MCC: 0.0300, F1: 0.7164

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.52982 | val 0.78676
  Epoch 020 - train 0.49073 | val 0.79689
  Epoch 027 - train 0.46043 | val 0.78355
  Regression -> MSE: 0.000268, MAE: 0.013329, R²: -0.5596
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.45794 | val 0.66799
  Epoch 016 - train 0.41499 | val 0.67176
  Regression -> MSE: 0.000227, MAE: 0.011803, R²: -0.0165
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.43800 | val 0.68212
  Epoch 016 - train 0.42838 | val 0.69121
  Regression -> MSE: 0.000092, MAE: 0.007645, R²: 0.0024
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.49886 | val 1.10287
  Epoch 016 - train 0.47751 | val 1.10923
  Regression -> MSE: 0.000164, MAE: 0.010277, R²: -0.0027
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.47308 | val 0.78377
  Epoch 016 - train 0.46853 | val 0.81121
  Regression -> MSE: 0.000125, MAE: 0.009020, R²: -0.0757
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.48945 | val 0.92538

[I 2026-02-22 20:58:16,706] Trial 13 finished with value: -0.011561109054391307 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.4, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 0.0012217015269463615, 'weight_decay': 1.7188693751853703e-06, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 30, 'huber_delta': 1.7847568837984449, 'early_stopping_min_delta': 0.007721637562448721}. Best is trial 3 with value: -0.011473394984568777.

  Epoch 016 - train 0.45927 | val 0.93253
  Regression -> MSE: 0.000238, MAE: 0.012349, R²: -0.0054
  Directional -> Accuracy: 0.4754, MCC: -0.0732, F1: 0.3333

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 30
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.38694 | val 0.59261
  Epoch 016 - train 0.38288 | val 0.68581
  Regression -> MSE: 0.000258, MAE: 0.012883, R²: -0.0815
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.6239

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 106). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.40417 | val 0.38655
  Epoch 016 - train 0.38348 | val 0.40417
  Regression -> MSE: 0.000712, MAE: 0.019736, R²: -0.0099
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.7429

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 106). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.37268 | val 0.66120
  Epoch 020 - train 0.35585 | val 0.65724
  Regression -> MSE: 0.000321, MAE: 0.014605, R²: 0.0012
  Directional -> Accuracy: 0.5333, MCC: 0.0000, F1: 0.6957

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.30305 | val 0.35646
  Epoch 016 - train 0.30607 | val 0.55852
  Regression -> MSE: 0.000359, MAE: 0.014753, R²: -0.0066
  Directional -> Accuracy: 0.5342, MCC: 0.0000, F1: 0.6964

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.35560 | val 0.33884
  Epoch 020 - train 0.35191 | val 0.33025
  Regression -> MSE: 0.000204, MAE: 0.010029, R²: 0.0321
  Directional -> Accuracy: 0.5918, MCC: 0.2189, F1: 0.4737

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.33117 | val 0.63973
  Epoch 020 - train 0.33701 | val 0.63564
  Regression -> MSE: 0.000564, MAE: 0.018290, R²: 0.0187
  Directional -> Accuracy: 0.6222, MCC: 0.2890, F1: 0.4516

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.36212 | val 0.47557
  Epoch 016 - train 0.36895 | val 0.48103
  Regression -> MSE: 0.000252, MAE: 0.012124, R²: -0.0025
  Directional -> Accuracy: 0.5970, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 106). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 106). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.37919 | val 0.28660
  Epoch 016 - train 0.37047 | val 0.28727
  Regression -> MSE: 0.000633, MAE: 0.019924, R²: -0.0121
  Directional -> Accuracy: 0.5610, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.35473 | val 0.48716
  Epoch 016 - train 0.35077 | val 0.48806
  Regression -> MSE: 0.000384, MAE: 0.015623, R²: -0.0253
  Directional -> Accuracy: 0.5532, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 106). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 106). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 106). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.34901 | val 0.48718
  Epoch 016 - train 0.35022 | val 0.51890
  Regression -> MSE: 0.000250, MAE: 0.011984, R²: -0.0066
  Directional -> Accuracy: 0.5735, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.32469 | val 0.57182
  Epoch 020 - train 0.32001 | val 0.56654
  Regression -> MSE: 0.000325, MAE: 0.013446, R²: -0.0347
  Directional -> Accuracy: 0.5417, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.36966 | val 0.44790
  Epoch 020 - train 0.37697 | val 0.43776
  Regression -> MSE: 0.000681, MAE: 0.019650, R²: 0.0235
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 106). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.35596 | val 0.36527
  Epoch 020 - train 0.35268 | val 0.37162
  Regression -> MSE: 0.000141, MAE: 0.009295, R²: 0.0035
  Directional -> Accuracy: 0.4898, MCC: 0.0000, F1: 0.6575

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 106). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.31866 | val 0.51143
  Epoch 020 - train 0.32332 | val 0.50602
  Regression -> MSE: 0.000236, MAE: 0.010918, R²: -0.0302
  Directional -> Accuracy: 0.4915, MCC: -0.0095, F1: 0.3182

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.34830 | val 0.87572
  Epoch 016 - train 0.35610 | val 0.87817
  Regression -> MSE: 0.000368, MAE: 0.015955, R²: -0.0030
  Directional -> Accuracy: 0.5600, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.38720 | val 0.37120
  Epoch 016 - train 0.38473 | val 0.39195
  Regression -> MSE: 0.000108, MAE: 0.007925, R²: -0.0019
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 106). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.34741 | val 0.72302
  Epoch 016 - train 0.34501 | val 0.75581
  Regression -> MSE: 0.000149, MAE: 0.009461, R²: 0.0007
  Directional -> Accuracy: 0.6140, MCC: 0.0000, F1: 0.7609

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.39831 | val 0.36057
  Epoch 016 - train 0.40005 | val 0.36469
  Regression -> MSE: 0.000277, MAE: 0.013093, R²: -0.0010
  Directional -> Accuracy: 0.5946, MCC: 0.0000, F1: 0.7458

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.30734 | val 0.49941
  Epoch 020 - train 0.31308 | val 0.49561
  Regression -> MSE: 0.000187, MAE: 0.009908, R²: -0.2330
  Directional -> Accuracy: 0.4127, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 106). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.36219 | val 0.61247
  Epoch 020 - train 0.35881 | val 0.63291
  Regression -> MSE: 0.000243, MAE: 0.011021, R²: -0.0810
  Directional -> Accuracy: 0.4521, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.36703 | val 0.52205
  Epoch 016 - train 0.35808 | val 0.52777
  Regression -> MSE: 0.000147, MAE: 0.008355, R²: -0.0006
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 106). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 106). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 106). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.32483 | val 0.46512
  Epoch 016 - train 0.31679 | val 0.50549
  Regression -> MSE: 0.000168, MAE: 0.010625, R²: 0.0013
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.37221 | val 0.44677
  Epoch 016 - train 0.36812 | val 0.45124
  Regression -> MSE: 0.000089, MAE: 0.007263, R²: -0.0075
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.34460 | val 0.47639
  Epoch 016 - train 0.35441 | val 0.48739
  Regression -> MSE: 0.000216, MAE: 0.011032, R²: -0.0125
  Directional -> Accuracy: 0.5312, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.32762 | val 0.33560
  Epoch 016 - train 0.32304 | val 0.34678
  Regression -> MSE: 0.000092, MAE: 0.008035, R²: -0.0042
  Directional -> Accuracy: 0.5370, MCC: 0.0000, F1: 0.6988

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.35381 | val 0.35182
  Epoch 016 - train 0.36510 | val 0.35285
  Regression -> MSE: 0.000121, MAE: 0.009232, R²: -0.2544
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.5902

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.36540 | val 0.24468
  Epoch 016 - train 0.36115 | val 0.24482
  Regression -> MSE: 0.000279, MAE: 0.013093, R²: -0.0231
  Directional -> Accuracy: 0.5918, MCC: 0.0000, F1: 0.7436

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.34679 | val 0.44068
  Epoch 020 - train 0.34258 | val 0.41704
  Regression -> MSE: 0.000226, MAE: 0.009547, R²: -0.3330
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.37294 | val 0.29134
  Epoch 016 - train 0.36625 | val 0.29393
  Regression -> MSE: 0.000251, MAE: 0.012381, R²: -0.0009
  Directional -> Accuracy: 0.5526, MCC: 0.0000, F1: 0.7119

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.35351 | val 0.69313
  Epoch 016 - train 0.35012 | val 0.69586
  Regression -> MSE: 0.000234, MAE: 0.009884, R²: 0.0001
  Directional -> Accuracy: 0.4878, MCC: 0.0000, F1: 0.6557

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.36433 | val 0.42456
  Epoch 016 - train 0.35266 | val 0.42929
  Regression -> MSE: 0.000140, MAE: 0.008374, R²: -0.0083
  Directional -> Accuracy: 0.5610, MCC: 0.0000, F1: 0.7188

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.36513 | val 0.50346
  Epoch 016 - train 0.36741 | val 0.50527
  Regression -> MSE: 0.000187, MAE: 0.010381, R²: -0.0010
  Directional -> Accuracy: 0.5208, MCC: 0.0000, F1: 0.6849

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.32087 | val 0.44463
  Epoch 016 - train 0.31342 | val 0.44506
  Regression -> MSE: 0.000285, MAE: 0.011026, R²: -0.0702
  Directional -> Accuracy: 0.4366, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 106). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.32187 | val 0.37503
  Epoch 016 - train 0.32868 | val 0.38280
  Regression -> MSE: 0.000188, MAE: 0.010577, R²: -0.0001
  Directional -> Accuracy: 0.5238, MCC: 0.0374, F1: 0.4444

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 106). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.34073 | val 0.34972
  Epoch 016 - train 0.33895 | val 0.35790
  Regression -> MSE: 0.000354, MAE: 0.011885, R²: -0.0051
  Directional -> Accuracy: 0.5692, MCC: 0.0000, F1: 0.7255

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.37019 | val 0.19905
  Epoch 016 - train 0.36618 | val 0.19743
  Regression -> MSE: 0.000118, MAE: 0.008604, R²: -0.0720
  Directional -> Accuracy: 0.5250, MCC: 0.0000, F1: 0.6885

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.35433 | val 0.55358
  Epoch 020 - train 0.36175 | val 0.60047
  Regression -> MSE: 0.000226, MAE: 0.011538, R²: -0.0129
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.35545 | val 0.72327
  Epoch 016 - train 0.35800 | val 0.72221
  Regression -> MSE: 0.000080, MAE: 0.006966, R²: -0.1384
  Directional -> Accuracy: 0.3778, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 106). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 106). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 106). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 106). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.34848 | val 0.19872
  Epoch 016 - train 0.34759 | val 0.19821
  Regression -> MSE: 0.000336, MAE: 0.014901, R²: -0.0558
  Directional -> Accuracy: 0.3261, MCC: 0.0000, F1: 0.4918

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 106). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 106). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 106). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.34435 | val 0.49304
  Epoch 016 - train 0.34721 | val 0.49638
  Regression -> MSE: 0.000078, MAE: 0.006864, R²: -0.0033
  Directional -> Accuracy: 0.4932, MCC: 0.0000, F1: 0.6606

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 106). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 106). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 106). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 106). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.37451 | val 0.56341
  Epoch 016 - train 0.36416 | val 0.56825
  Regression -> MSE: 0.000288, MAE: 0.013916, R²: -0.0327
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.34912 | val 0.40692
  Epoch 016 - train 0.34008 | val 0.40848
  Regression -> MSE: 0.000105, MAE: 0.007222, R²: -0.0183
  Directional -> Accuracy: 0.5854, MCC: 0.0000, F1: 0.7385

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.36951 | val 0.49077
  Epoch 016 - train 0.38307 | val 0.49445
  Regression -> MSE: 0.000179, MAE: 0.009783, R²: 0.0003
  Directional -> Accuracy: 0.6304, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.32560 | val 0.40900
  Epoch 016 - train 0.32305 | val 0.41183
  Regression -> MSE: 0.000229, MAE: 0.011852, R²: -0.0097
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.34858 | val 0.46702
  Epoch 020 - train 0.35977 | val 0.46994
  Regression -> MSE: 0.000089, MAE: 0.007558, R²: -0.0155
  Directional -> Accuracy: 0.4909, MCC: -0.0411, F1: 0.2222

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.37905 | val 0.63041
  Epoch 016 - train 0.36328 | val 0.63494
  Regression -> MSE: 0.000168, MAE: 0.010431, R²: -0.0063
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.36402 | val 0.46672
  Epoch 016 - train 0.35570 | val 0.47015
  Regression -> MSE: 0.000127, MAE: 0.009269, R²: -0.0626
  Directional -> Accuracy: 0.4815, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.36057 | val 0.59616

[I 2026-02-22 20:59:56,086] Trial 14 finished with value: -0.011536788643521234 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 30, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.1, 'batch_size': 64, 'learning_rate': 1.175413784051553e-06, 'weight_decay': 2.107471077378617e-05, 'lr_patience': 7, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 0.7734933067891949, 'early_stopping_min_delta': 0.004370288476115183}. Best is trial 3 with value: -0.011473394984568777.

  Epoch 016 - train 0.35353 | val 0.60127
  Regression -> MSE: 0.000246, MAE: 0.012550, R²: -0.0071
  Directional -> Accuracy: 0.5254, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.43892 | val 0.72947
  Epoch 011 - train 0.44001 | val 0.72961
  Regression -> MSE: 0.000251, MAE: 0.012677, R²: -0.0123
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.47033 | val 0.44513
  Epoch 011 - train 0.46753 | val 0.44504
  Regression -> MSE: 0.000725, MAE: 0.020035, R²: -0.0595
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.43503 | val 0.89762
  Epoch 018 - train 0.45841 | val 0.90765
  Regression -> MSE: 0.000332, MAE: 0.015038, R²: -0.0710
  Directional -> Accuracy: 0.4681, MCC: -0.0934, F1: 0.5614

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.36471 | val 0.42585
  Epoch 011 - train 0.39843 | val 0.42607
  Regression -> MSE: 0.000358, MAE: 0.014715, R²: -0.0252
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.43540 | val 0.46603
  Epoch 011 - train 0.45168 | val 0.46568
  Regression -> MSE: 0.000204, MAE: 0.010000, R²: 0.0005
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.45757 | val 1.08009
  Epoch 011 - train 0.41613 | val 1.08034
  Regression -> MSE: 0.000562, MAE: 0.018216, R²: -0.0122
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.46295 | val 0.64587
  Epoch 011 - train 0.47028 | val 0.64716
  Regression -> MSE: 0.000246, MAE: 0.011998, R²: -0.0023
  Directional -> Accuracy: 0.5072, MCC: -0.0587, F1: 0.3200

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.51742 | val 0.95352
  Epoch 011 - train 0.43252 | val 1.00866
  Regression -> MSE: 0.000671, MAE: 0.020508, R²: -0.1232
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.44697 | val 0.60117
  Epoch 020 - train 0.43814 | val 0.59021
  Epoch 025 - train 0.38727 | val 0.61652
  Regression -> MSE: 0.000394, MAE: 0.016330, R²: -0.0275
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.41742 | val 0.66348
  Epoch 011 - train 0.44746 | val 0.66533
  Regression -> MSE: 0.000241, MAE: 0.011859, R²: 0.0029
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.40934 | val 0.73287
  Epoch 011 - train 0.50176 | val 0.73452
  Regression -> MSE: 0.000347, MAE: 0.013943, R²: -0.1172
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.44797 | val 0.66061
  Epoch 011 - train 0.47930 | val 0.66534
  Regression -> MSE: 0.000681, MAE: 0.019556, R²: -0.0050
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.44979 | val 0.58621
  Epoch 011 - train 0.43076 | val 0.61021
  Regression -> MSE: 0.000138, MAE: 0.009163, R²: -0.0009
  Directional -> Accuracy: 0.4419, MCC: -0.0259, F1: 0.6000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.41054 | val 0.66328
  Epoch 011 - train 0.40597 | val 0.66247
  Regression -> MSE: 0.000223, MAE: 0.010635, R²: 0.0070
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.44178 | val 1.26164
  Epoch 011 - train 0.43087 | val 1.26683
  Regression -> MSE: 0.000362, MAE: 0.015976, R²: 0.0006
  Directional -> Accuracy: 0.5769, MCC: 0.2324, F1: 0.6562

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.50982 | val 0.53904
  Epoch 011 - train 0.46154 | val 0.53308
  Regression -> MSE: 0.000107, MAE: 0.008068, R²: 0.0063
  Directional -> Accuracy: 0.4571, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.46133 | val 1.09149
  Epoch 011 - train 0.45137 | val 1.08444
  Regression -> MSE: 0.000166, MAE: 0.009732, R²: -0.0679
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.45810 | val 0.45584
  Epoch 016 - train 0.44383 | val 0.45709
  Regression -> MSE: 0.000348, MAE: 0.015473, R²: -0.2778
  Directional -> Accuracy: 0.4079, MCC: 0.0933, F1: 0.0426

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.35644 | val 0.79855
  Epoch 011 - train 0.38233 | val 0.79789
  Regression -> MSE: 0.000154, MAE: 0.008744, R²: -0.0300
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.44512 | val 0.85013
  Epoch 013 - train 0.43844 | val 0.84807
  Regression -> MSE: 0.000275, MAE: 0.012037, R²: -0.2167
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.45814 | val 0.63450
  Epoch 020 - train 0.43622 | val 0.62275
  Epoch 023 - train 0.44121 | val 0.62444
  Regression -> MSE: 0.000181, MAE: 0.010120, R²: -0.2621
  Directional -> Accuracy: 0.4167, MCC: 0.1615, F1: 0.1250

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.44499 | val 0.56018
  Epoch 011 - train 0.40209 | val 0.56332
  Regression -> MSE: 0.000165, MAE: 0.010222, R²: 0.0038
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.49537 | val 0.63438
  Epoch 011 - train 0.49018 | val 0.63686
  Regression -> MSE: 0.000087, MAE: 0.007174, R²: -0.0194
  Directional -> Accuracy: 0.5000, MCC: -0.0145, F1: 0.5538

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.44409 | val 0.77971
  Epoch 011 - train 0.45460 | val 0.79528
  Regression -> MSE: 0.000216, MAE: 0.011513, R²: -0.0183
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.38989 | val 0.33280
  Epoch 020 - train 0.38153 | val 0.32773
  Epoch 023 - train 0.34759 | val 0.32627
  Regression -> MSE: 0.000101, MAE: 0.008072, R²: -0.0936
  Directional -> Accuracy: 0.5536, MCC: 0.2064, F1: 0.4186

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.48725 | val 0.31842
  Epoch 020 - train 0.42168 | val 0.30105
  Epoch 023 - train 0.45330 | val 0.30328
  Regression -> MSE: 0.000099, MAE: 0.008356, R²: 0.0433
  Directional -> Accuracy: 0.6522, MCC: 0.2779, F1: 0.5000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.47480 | val 0.61244
  Epoch 011 - train 0.45031 | val 0.65769
  Regression -> MSE: 0.000242, MAE: 0.012921, R²: -0.0436
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.46544 | val 0.59793
  Epoch 011 - train 0.44967 | val 0.60025
  Regression -> MSE: 0.000184, MAE: 0.008012, R²: -0.1026
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.53947 | val 0.28837
  Epoch 011 - train 0.49805 | val 0.28876
  Regression -> MSE: 0.000241, MAE: 0.011996, R²: -0.0180
  Directional -> Accuracy: 0.4146, MCC: -0.1695, F1: 0.4286

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.43551 | val 0.94055
  Epoch 011 - train 0.44911 | val 0.94892
  Regression -> MSE: 0.000233, MAE: 0.009955, R²: -0.0089
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.52850 | val 0.70784
  Epoch 011 - train 0.48640 | val 0.72968
  Regression -> MSE: 0.000138, MAE: 0.008251, R²: -0.0188
  Directional -> Accuracy: 0.6977, MCC: 0.3936, F1: 0.7451

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.43994 | val 0.66832
  Epoch 011 - train 0.43555 | val 0.67007
  Regression -> MSE: 0.000190, MAE: 0.010385, R²: -0.0102
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.36736 | val 0.56732
  Epoch 011 - train 0.37975 | val 0.56791
  Regression -> MSE: 0.000278, MAE: 0.010860, R²: -0.0615
  Directional -> Accuracy: 0.4384, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.45280 | val 0.37384
  Epoch 011 - train 0.46365 | val 0.38634
  Regression -> MSE: 0.000166, MAE: 0.010368, R²: 0.0069
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.40033 | val 0.70763
  Epoch 011 - train 0.40426 | val 0.71891
  Regression -> MSE: 0.000181, MAE: 0.010311, R²: -0.0062
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.42863 | val 0.45850
  Epoch 011 - train 0.42932 | val 0.45757
  Regression -> MSE: 0.000354, MAE: 0.012573, R²: -0.0327
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.48859 | val 0.28924
  Epoch 011 - train 0.48497 | val 0.29674
  Regression -> MSE: 0.000131, MAE: 0.008600, R²: -0.2468
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.44611 | val 0.80728
  Epoch 013 - train 0.44363 | val 0.80983
  Regression -> MSE: 0.000225, MAE: 0.011485, R²: -0.0294
  Directional -> Accuracy: 0.4211, MCC: -0.1496, F1: 0.5075

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.44973 | val 1.05210
  Epoch 011 - train 0.46370 | val 1.06094
  Regression -> MSE: 0.000082, MAE: 0.007064, R²: -0.0583
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.46370 | val 0.32323
  Epoch 020 - train 0.44845 | val 0.28667
  Epoch 030 - train 0.41748 | val 0.28084
  Regression -> MSE: 0.000368, MAE: 0.016103, R²: -0.1947
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.48623 | val 0.21944
  Epoch 011 - train 0.50786 | val 0.22409
  Regression -> MSE: 0.000247, MAE: 0.011493, R²: -0.0123
  Directional -> Accuracy: 0.5789, MCC: 0.1783, F1: 0.5294

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.41474 | val 0.64820
  Epoch 011 - train 0.40844 | val 0.64816
  Regression -> MSE: 0.000083, MAE: 0.007057, R²: -0.0310
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.45489 | val 0.86839
  Epoch 011 - train 0.45281 | val 0.94889
  Regression -> MSE: 0.000326, MAE: 0.014838, R²: -0.0634
  Directional -> Accuracy: 0.4894, MCC: 0.0000, F1: 0.0000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.43207 | val 0.53732
  Epoch 011 - train 0.48652 | val 0.53758
  Regression -> MSE: 0.000100, MAE: 0.007185, R²: -0.0183
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.55597 | val 0.66365
  Epoch 011 - train 0.52105 | val 0.66534
  Regression -> MSE: 0.000172, MAE: 0.009596, R²: 0.0005
  Directional -> Accuracy: 0.5510, MCC: -0.0039, F1: 0.3125

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.41965 | val 0.58943
  Epoch 011 - train 0.41426 | val 0.58502
  Regression -> MSE: 0.000229, MAE: 0.011858, R²: -0.0258
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.43353 | val 0.60174
  Epoch 011 - train 0.41192 | val 0.60850
  Regression -> MSE: 0.000093, MAE: 0.007635, R²: -0.0023
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.44202 | val 0.88213
  Epoch 011 - train 0.47744 | val 0.88483
  Regression -> MSE: 0.000164, MAE: 0.010305, R²: -0.0037
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.42010 | val 0.77627
  Epoch 011 - train 0.42720 | val 0.78337
  Regression -> MSE: 0.000123, MAE: 0.009062, R²: -0.0653
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...

[I 2026-02-22 21:00:15,807] Trial 15 finished with value: -0.011607681910878626 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.4, 'dropout': 0.8, 'batch_size': 32, 'learning_rate': 0.0002997948369761317, 'weight_decay': 2.697443537488863e-07, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.3733158793480285, 'early_stopping_min_delta': 0.008588525604684285}. Best is trial 3 with value: -0.011473394984568777.

  Epoch 010 - train 0.45489 | val 0.89075
  Epoch 011 - train 0.44921 | val 0.89905
  Regression -> MSE: 0.000242, MAE: 0.012310, R²: -0.0212
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 30
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.30108 | val 0.62483
  Epoch 017 - train 0.26466 | val 0.70668
  Regression -> MSE: 0.000238, MAE: 0.012083, R²: 0.0056
  Directional -> Accuracy: 0.5200, MCC: -0.0544, F1: 0.1429

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 106). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.31186 | val 0.47953
  Epoch 019 - train 0.26591 | val 0.59550
  Regression -> MSE: 0.000742, MAE: 0.020223, R²: -0.0516
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 106). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.32028 | val 0.73716
  Epoch 020 - train 0.24711 | val 0.79255
  Regression -> MSE: 0.000336, MAE: 0.014869, R²: -0.0458
  Directional -> Accuracy: 0.4222, MCC: -0.2306, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.28653 | val 1.84991
  Epoch 020 - train 0.25738 | val 1.19253
  Regression -> MSE: 0.000417, MAE: 0.015805, R²: -0.1709
  Directional -> Accuracy: 0.4658, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.36075 | val 0.31049
  Epoch 020 - train 0.31184 | val 0.29819
  Regression -> MSE: 0.000227, MAE: 0.011296, R²: -0.0797
  Directional -> Accuracy: 0.5306, MCC: 0.0589, F1: 0.5660

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.32215 | val 0.99675
  Epoch 016 - train 0.24329 | val 0.88969
  Regression -> MSE: 0.000553, MAE: 0.018145, R²: 0.0370
  Directional -> Accuracy: 0.6000, MCC: 0.2310, F1: 0.6667

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.36812 | val 0.49081
  Epoch 020 - train 0.39334 | val 0.95854
  Regression -> MSE: 0.000252, MAE: 0.012527, R²: -0.0028
  Directional -> Accuracy: 0.5224, MCC: 0.2250, F1: 0.6098

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 106). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 106). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.21065 | val 0.53638
  Epoch 017 - train 0.14428 | val 0.52340
  Regression -> MSE: 0.000629, MAE: 0.019863, R²: -0.0059
  Directional -> Accuracy: 0.5610, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.35852 | val 0.57424
  Epoch 020 - train 0.30550 | val 0.62288
  Regression -> MSE: 0.000374, MAE: 0.015422, R²: 0.0014
  Directional -> Accuracy: 0.7021, MCC: 0.4129, F1: 0.5625

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 106). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 106). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 106). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.32681 | val 0.54746
  Epoch 016 - train 0.32032 | val 0.52918
  Regression -> MSE: 0.000256, MAE: 0.011914, R²: -0.0314
  Directional -> Accuracy: 0.5735, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.30893 | val 0.58492
  Epoch 020 - train 0.26473 | val 0.70844
  Regression -> MSE: 0.000358, MAE: 0.014034, R²: -0.1408
  Directional -> Accuracy: 0.5417, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.32576 | val 0.58234
  Epoch 017 - train 0.28422 | val 0.97866
  Regression -> MSE: 0.000683, MAE: 0.019675, R²: 0.0200
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 106). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.30888 | val 0.45975
  Epoch 019 - train 0.23058 | val 0.80842
  Regression -> MSE: 0.000144, MAE: 0.009418, R²: -0.0156
  Directional -> Accuracy: 0.4898, MCC: 0.0000, F1: 0.6575

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 106). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.27677 | val 0.56908
  Epoch 016 - train 0.23963 | val 0.58974
  Regression -> MSE: 0.000228, MAE: 0.010701, R²: 0.0034
  Directional -> Accuracy: 0.5085, MCC: 0.0462, F1: 0.2162

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.33651 | val 0.97115
  Epoch 020 - train 0.30819 | val 1.85918
  Regression -> MSE: 0.000361, MAE: 0.015896, R²: 0.0148
  Directional -> Accuracy: 0.4800, MCC: 0.1809, F1: 0.6286

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.36278 | val 0.39895
  Epoch 020 - train 0.40722 | val 0.58594
  Regression -> MSE: 0.000115, MAE: 0.008307, R²: -0.0647
  Directional -> Accuracy: 0.4706, MCC: -0.0625, F1: 0.5000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 106). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.34357 | val 0.85475
  Epoch 019 - train 0.30896 | val 0.84911
  Regression -> MSE: 0.000153, MAE: 0.009847, R²: -0.0274
  Directional -> Accuracy: 0.5439, MCC: -0.1129, F1: 0.6905

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.34798 | val 0.56339
  Epoch 020 - train 0.28819 | val 1.03415
  Regression -> MSE: 0.000282, MAE: 0.013444, R²: -0.0204
  Directional -> Accuracy: 0.4324, MCC: 0.1376, F1: 0.0870

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.29641 | val 0.52660
  Epoch 020 - train 0.24999 | val 0.67571
  Regression -> MSE: 0.000195, MAE: 0.010154, R²: -0.2876
  Directional -> Accuracy: 0.4127, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 106). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.34564 | val 0.84665
  Epoch 019 - train 0.28251 | val 0.74045
  Regression -> MSE: 0.000276, MAE: 0.011919, R²: -0.2275
  Directional -> Accuracy: 0.4521, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.32750 | val 0.61492
  Epoch 017 - train 0.28562 | val 0.65600
  Regression -> MSE: 0.000154, MAE: 0.008783, R²: -0.0492
  Directional -> Accuracy: 0.3913, MCC: -0.2132, F1: 0.4400

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 106). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 106). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 106). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.31921 | val 0.48950
  Epoch 020 - train 0.26672 | val 0.52771
  Regression -> MSE: 0.000177, MAE: 0.010558, R²: -0.0503
  Directional -> Accuracy: 0.5156, MCC: 0.0314, F1: 0.4918

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.31638 | val 0.56100
  Epoch 016 - train 0.35323 | val 0.62591
  Regression -> MSE: 0.000091, MAE: 0.007378, R²: -0.0323
  Directional -> Accuracy: 0.5536, MCC: 0.1491, F1: 0.5283

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.34906 | val 0.62941
  Epoch 016 - train 0.32077 | val 1.39548
  Regression -> MSE: 0.000212, MAE: 0.011249, R²: 0.0055
  Directional -> Accuracy: 0.5312, MCC: 0.0929, F1: 0.5946

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.28287 | val 0.31016
  Epoch 020 - train 0.23469 | val 0.37781
  Regression -> MSE: 0.000101, MAE: 0.008102, R²: -0.1066
  Directional -> Accuracy: 0.5741, MCC: 0.1838, F1: 0.5106

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.30886 | val 0.39793
  Epoch 016 - train 0.24626 | val 0.40045
  Regression -> MSE: 0.000103, MAE: 0.008682, R²: -0.0726
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.5902

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.31781 | val 0.25982
  Epoch 020 - train 0.24147 | val 0.40998
  Regression -> MSE: 0.000288, MAE: 0.013368, R²: -0.0570
  Directional -> Accuracy: 0.4898, MCC: 0.1114, F1: 0.3590

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.29141 | val 0.47176
  Epoch 020 - train 0.22020 | val 0.49010
  Regression -> MSE: 0.000311, MAE: 0.012459, R²: -0.8321
  Directional -> Accuracy: 0.5455, MCC: 0.2887, F1: 0.2857

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.27626 | val 0.30756
  Epoch 020 - train 0.17106 | val 0.27906
  Regression -> MSE: 0.000255, MAE: 0.012601, R²: -0.0155
  Directional -> Accuracy: 0.4474, MCC: -0.0249, F1: 0.0870

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.31393 | val 0.74865
  Epoch 020 - train 0.25242 | val 0.93978
  Regression -> MSE: 0.000242, MAE: 0.010277, R²: -0.0344
  Directional -> Accuracy: 0.5122, MCC: 0.0101, F1: 0.2308

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.36560 | val 0.48162
  Epoch 020 - train 0.24850 | val 0.64240
  Regression -> MSE: 0.000141, MAE: 0.008161, R²: -0.0132
  Directional -> Accuracy: 0.5854, MCC: 0.1289, F1: 0.7213

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.31542 | val 0.50160
  Epoch 020 - train 0.29222 | val 0.59040
  Regression -> MSE: 0.000228, MAE: 0.012334, R²: -0.2205
  Directional -> Accuracy: 0.5417, MCC: 0.0763, F1: 0.6667

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.29793 | val 0.48431
  Epoch 020 - train 0.26585 | val 0.51335
  Regression -> MSE: 0.000326, MAE: 0.012066, R²: -0.2231
  Directional -> Accuracy: 0.5070, MCC: 0.1231, F1: 0.3396

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 106). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.25178 | val 0.43336
  Epoch 019 - train 0.19724 | val 0.49097
  Regression -> MSE: 0.000189, MAE: 0.010610, R²: -0.0047
  Directional -> Accuracy: 0.4762, MCC: -0.0231, F1: 0.5926

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 106). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.31337 | val 0.36883
  Epoch 020 - train 0.28845 | val 0.34341
  Regression -> MSE: 0.000446, MAE: 0.015695, R²: -0.2663
  Directional -> Accuracy: 0.4462, MCC: 0.1087, F1: 0.0526

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.28053 | val 0.22756
  Epoch 016 - train 0.23455 | val 0.25758
  Regression -> MSE: 0.000116, MAE: 0.008455, R²: -0.0543
  Directional -> Accuracy: 0.5250, MCC: 0.0000, F1: 0.6885

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.31480 | val 0.61100
  Epoch 018 - train 0.28394 | val 0.75997
  Regression -> MSE: 0.000223, MAE: 0.011375, R²: 0.0028
  Directional -> Accuracy: 0.5636, MCC: 0.1023, F1: 0.1429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.30068 | val 0.87753
  Epoch 017 - train 0.22773 | val 1.05055
  Regression -> MSE: 0.000076, MAE: 0.006729, R²: -0.0765
  Directional -> Accuracy: 0.5333, MCC: 0.0187, F1: 0.6182

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 106). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 106). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 106). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 106). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.29569 | val 0.19941
  Epoch 020 - train 0.23812 | val 0.17998
  Regression -> MSE: 0.000383, MAE: 0.016723, R²: -0.2047
  Directional -> Accuracy: 0.3261, MCC: 0.0000, F1: 0.4918

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 106). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 106). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 106). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.28461 | val 0.79665
  Epoch 020 - train 0.22487 | val 0.89806
  Regression -> MSE: 0.000075, MAE: 0.006707, R²: 0.0261
  Directional -> Accuracy: 0.5753, MCC: 0.1509, F1: 0.5753

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 106). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 106). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 106). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 106). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.32458 | val 0.56640
  Epoch 020 - train 0.24947 | val 0.57141
  Regression -> MSE: 0.000271, MAE: 0.013733, R²: 0.0287
  Directional -> Accuracy: 0.5682, MCC: 0.1376, F1: 0.5957

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.33742 | val 0.44453
  Epoch 020 - train 0.24915 | val 0.43760
  Regression -> MSE: 0.000101, MAE: 0.007442, R²: 0.0190
  Directional -> Accuracy: 0.5610, MCC: 0.0802, F1: 0.6400

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.32010 | val 0.57428
  Epoch 017 - train 0.21195 | val 0.60808
  Regression -> MSE: 0.000188, MAE: 0.010701, R²: -0.0505
  Directional -> Accuracy: 0.3696, MCC: 0.0000, F1: 0.5397

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.32030 | val 0.47040
  Epoch 016 - train 0.26262 | val 0.63676
  Regression -> MSE: 0.000228, MAE: 0.011835, R²: -0.0045
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.35055 | val 0.56647
  Epoch 016 - train 0.31198 | val 0.74242
  Regression -> MSE: 0.000093, MAE: 0.007921, R²: -0.0683
  Directional -> Accuracy: 0.4909, MCC: 0.0000, F1: 0.6585

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.34405 | val 0.78132
  Epoch 017 - train 0.24999 | val 0.77854
  Regression -> MSE: 0.000173, MAE: 0.010634, R²: -0.0336
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.31237 | val 0.52428
  Epoch 017 - train 0.25361 | val 0.67647
  Regression -> MSE: 0.000131, MAE: 0.009282, R²: -0.0891
  Directional -> Accuracy: 0.4815, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.36607 | val 0.68875

[I 2026-02-22 21:02:01,348] Trial 16 finished with value: -0.011912588826410614 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 30, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.1, 'dropout': 0.0, 'batch_size': 64, 'learning_rate': 0.008156882445310376, 'weight_decay': 2.1964763927583206e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 0.8956942465868842, 'early_stopping_min_delta': 0.005831957200020591}. Best is trial 3 with value: -0.011473394984568777.

  Epoch 018 - train 0.29107 | val 0.89520
  Regression -> MSE: 0.000240, MAE: 0.012400, R²: 0.0166
  Directional -> Accuracy: 0.5932, MCC: 0.1804, F1: 0.5385

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: regression
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.40480 | val 0.73310
  Epoch 011 - train 0.43845 | val 0.72946
  Regression -> MSE: 0.000243, MAE: 0.012475, R²: -0.0125
  Directional -> Accuracy: 0.5132, MCC: 0.0667, F1: 0.5647

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.43931 | val 0.43511
  Epoch 011 - train 0.39372 | val 0.42759
  Regression -> MSE: 0.000718, MAE: 0.020080, R²: -0.0283
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.41441 | val 0.88780
  Epoch 016 - train 0.43200 | val 0.89144
  Regression -> MSE: 0.000324, MAE: 0.014579, R²: -0.0298
  Directional -> Accuracy: 0.4783, MCC: -0.0259, F1: 0.3333

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.35040 | val 0.41650
  Epoch 012 - train 0.34885 | val 0.44794
  Regression -> MSE: 0.000352, MAE: 0.014634, R²: 0.0030
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.40435 | val 0.38248
  Epoch 020 - train 0.40417 | val 0.38578
  Regression -> MSE: 0.000203, MAE: 0.009577, R²: 0.0165
  Directional -> Accuracy: 0.6200, MCC: 0.2375, F1: 0.6667

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.41909 | val 1.07410
  Epoch 011 - train 0.39107 | val 1.06075
  Regression -> MSE: 0.000575, MAE: 0.018401, R²: -0.0156
  Directional -> Accuracy: 0.4783, MCC: -0.1124, F1: 0.1429

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.42206 | val 0.63639
  Epoch 015 - train 0.41293 | val 0.59596
  Regression -> MSE: 0.000248, MAE: 0.012019, R²: 0.0019
  Directional -> Accuracy: 0.5441, MCC: 0.0659, F1: 0.4561

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.37588 | val 0.36982
  Epoch 011 - train 0.38821 | val 0.37386
  Regression -> MSE: 0.000612, MAE: 0.019399, R²: -0.0022
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.41128 | val 0.61014
  Epoch 011 - train 0.40971 | val 0.61380
  Regression -> MSE: 0.000400, MAE: 0.015933, R²: -0.0709
  Directional -> Accuracy: 0.5625, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.42131 | val 0.65026
  Epoch 012 - train 0.42300 | val 0.66615
  Regression -> MSE: 0.000244, MAE: 0.012153, R²: 0.0050
  Directional -> Accuracy: 0.4203, MCC: 0.0000, F1: 0.5918

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.39206 | val 0.76288
  Epoch 014 - train 0.39950 | val 0.76644
  Regression -> MSE: 0.000311, MAE: 0.013627, R²: 0.0031
  Directional -> Accuracy: 0.4694, MCC: 0.1303, F1: 0.6286

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.44113 | val 0.57776
  Epoch 015 - train 0.44189 | val 0.60144
  Regression -> MSE: 0.000677, MAE: 0.019353, R²: 0.0122
  Directional -> Accuracy: 0.5965, MCC: 0.2482, F1: 0.7013

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.43353 | val 0.68544
  Epoch 011 - train 0.43734 | val 0.73866
  Regression -> MSE: 0.000139, MAE: 0.009040, R²: -0.0046
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.38712 | val 0.66501
  Epoch 016 - train 0.36671 | val 0.69874
  Regression -> MSE: 0.000223, MAE: 0.010628, R²: 0.0158
  Directional -> Accuracy: 0.5167, MCC: 0.0343, F1: 0.5672

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.41873 | val 1.20605
  Epoch 020 - train 0.41322 | val 1.21924
  Epoch 022 - train 0.38820 | val 1.22564
  Regression -> MSE: 0.000368, MAE: 0.016070, R²: -0.0036
  Directional -> Accuracy: 0.5098, MCC: 0.0463, F1: 0.5455

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.42684 | val 0.48178
  Epoch 011 - train 0.43414 | val 0.49088
  Regression -> MSE: 0.000108, MAE: 0.007959, R²: 0.0023
  Directional -> Accuracy: 0.4783, MCC: -0.0447, F1: 0.5000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.39859 | val 0.92676
  Epoch 020 - train 0.38950 | val 0.94699
  Epoch 021 - train 0.39237 | val 0.94994
  Regression -> MSE: 0.000159, MAE: 0.009892, R²: -0.0077
  Directional -> Accuracy: 0.5862, MCC: -0.1477, F1: 0.7391

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.42936 | val 0.52294
  Epoch 011 - train 0.43643 | val 0.52079
  Regression -> MSE: 0.000322, MAE: 0.014790, R²: -0.1780
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.35346 | val 0.64328
  Epoch 020 - train 0.34113 | val 0.64168
  Epoch 027 - train 0.34376 | val 0.63754
  Regression -> MSE: 0.000196, MAE: 0.010145, R²: -0.2879
  Directional -> Accuracy: 0.4219, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.41729 | val 0.79333
  Epoch 020 - train 0.41050 | val 0.80366
  Epoch 021 - train 0.39770 | val 0.80502
  Regression -> MSE: 0.000329, MAE: 0.013525, R²: -0.4457
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.45231 | val 0.64319
  Epoch 011 - train 0.43788 | val 0.64167
  Regression -> MSE: 0.000148, MAE: 0.008523, R²: -0.0258
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.38759 | val 0.57864
  Epoch 011 - train 0.40626 | val 0.57906
  Regression -> MSE: 0.000176, MAE: 0.010332, R²: -0.0609
  Directional -> Accuracy: 0.5231, MCC: 0.1755, F1: 0.1143

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.42361 | val 0.58221
  Epoch 020 - train 0.42392 | val 0.58309
  Epoch 025 - train 0.42876 | val 0.58816
  Regression -> MSE: 0.000088, MAE: 0.007252, R²: -0.0136
  Directional -> Accuracy: 0.5614, MCC: 0.1133, F1: 0.6032

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.43176 | val 0.61753
  Epoch 017 - train 0.43148 | val 0.62045
  Regression -> MSE: 0.000212, MAE: 0.010895, R²: -0.0069
  Directional -> Accuracy: 0.5231, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.37824 | val 0.35290
  Epoch 020 - train 0.34718 | val 0.34269
  Epoch 030 - train 0.35884 | val 0.33913
  Regression -> MSE: 0.000092, MAE: 0.007878, R²: -0.0275
  Directional -> Accuracy: 0.5455, MCC: 0.0803, F1: 0.5902

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.45041 | val 0.35009
  Epoch 015 - train 0.43948 | val 0.35915
  Regression -> MSE: 0.000105, MAE: 0.008765, R²: -0.0560
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.46790 | val 0.42349
  Epoch 017 - train 0.43774 | val 0.42593
  Regression -> MSE: 0.000240, MAE: 0.012770, R²: -0.0142
  Directional -> Accuracy: 0.5476, MCC: 0.0168, F1: 0.6667

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.39967 | val 0.53270
  Epoch 015 - train 0.39269 | val 0.54481
  Regression -> MSE: 0.000211, MAE: 0.008779, R²: -0.2484
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.40802 | val 0.34283
  Epoch 013 - train 0.44230 | val 0.34146
  Regression -> MSE: 0.000243, MAE: 0.012130, R²: -0.0030
  Directional -> Accuracy: 0.5500, MCC: 0.0000, F1: 0.7097

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.43138 | val 0.93276
  Epoch 011 - train 0.41522 | val 0.92770
  Regression -> MSE: 0.000240, MAE: 0.010243, R²: -0.0168
  Directional -> Accuracy: 0.4762, MCC: 0.0000, F1: 0.6452

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.44213 | val 0.69924
  Epoch 011 - train 0.43916 | val 0.69330
  Regression -> MSE: 0.000141, MAE: 0.008433, R²: -0.0240
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.41933 | val 0.66201
  Epoch 014 - train 0.40622 | val 0.66499
  Regression -> MSE: 0.000191, MAE: 0.010460, R²: -0.0436
  Directional -> Accuracy: 0.3878, MCC: -0.2724, F1: 0.0625

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.35708 | val 0.56004
  Epoch 020 - train 0.34798 | val 0.55492
  Epoch 028 - train 0.32954 | val 0.54922
  Regression -> MSE: 0.000300, MAE: 0.011868, R²: -0.1310
  Directional -> Accuracy: 0.5139, MCC: 0.0916, F1: 0.4068

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.38031 | val 0.52209
  Epoch 017 - train 0.35997 | val 0.55380
  Regression -> MSE: 0.000184, MAE: 0.010505, R²: -0.0018
  Directional -> Accuracy: 0.5349, MCC: 0.2158, F1: 0.6774

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.41032 | val 0.42954
  Epoch 013 - train 0.38672 | val 0.43114
  Regression -> MSE: 0.000362, MAE: 0.013055, R²: -0.0417
  Directional -> Accuracy: 0.4242, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.42460 | val 0.25811
  Epoch 016 - train 0.42643 | val 0.27093
  Regression -> MSE: 0.000134, MAE: 0.008541, R²: -0.2720
  Directional -> Accuracy: 0.5238, MCC: 0.1168, F1: 0.2857

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.41850 | val 0.76067
  Epoch 012 - train 0.40789 | val 0.79068
  Regression -> MSE: 0.000230, MAE: 0.011548, R²: -0.0466
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.6341

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.40797 | val 1.04891
  Epoch 016 - train 0.39766 | val 1.07915
  Regression -> MSE: 0.000076, MAE: 0.006784, R²: -0.0225
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.40407 | val 0.28328
  Epoch 020 - train 0.38236 | val 0.22981
  Epoch 029 - train 0.39200 | val 0.25223
  Regression -> MSE: 0.000568, MAE: 0.020803, R²: -0.8243
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.39524 | val 0.63129
  Epoch 011 - train 0.38510 | val 0.63163
  Regression -> MSE: 0.000078, MAE: 0.006952, R²: -0.0017
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.42172 | val 0.59970
  Epoch 020 - train 0.42651 | val 0.59433
  Epoch 028 - train 0.40413 | val 0.59878
  Regression -> MSE: 0.000302, MAE: 0.014361, R²: -0.0041
  Directional -> Accuracy: 0.5556, MCC: 0.1395, F1: 0.6774

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.40780 | val 0.53443
  Epoch 020 - train 0.39358 | val 0.52782
  Epoch 030 - train 0.37447 | val 0.50650
  Regression -> MSE: 0.000101, MAE: 0.007079, R²: 0.0101
  Directional -> Accuracy: 0.5952, MCC: 0.1291, F1: 0.7119

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.47360 | val 0.70343
  Epoch 011 - train 0.45529 | val 0.70372
  Regression -> MSE: 0.000182, MAE: 0.010571, R²: -0.0391
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.38236 | val 0.52446
  Epoch 017 - train 0.37811 | val 0.53983
  Regression -> MSE: 0.000227, MAE: 0.011935, R²: -0.0078
  Directional -> Accuracy: 0.5091, MCC: -0.1773, F1: 0.6747

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.40859 | val 0.70372
  Epoch 011 - train 0.41151 | val 0.72999
  Regression -> MSE: 0.000098, MAE: 0.008020, R²: -0.0399
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.42673 | val 0.87780
  Epoch 011 - train 0.44435 | val 0.90238
  Regression -> MSE: 0.000168, MAE: 0.010470, R²: -0.0056
  Directional -> Accuracy: 0.5094, MCC: 0.0000, F1: 0.6750

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.40619 | val 0.66138
  Epoch 011 - train 0.40715 | val 0.65332
  Regression -> MSE: 0.000131, MAE: 0.009224, R²: -0.1121
  Directional -> Accuracy: 0.4727, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.45137 | val 0.80667

[I 2026-02-22 21:02:35,576] Trial 17 finished with value: -0.011769539877211464 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.4, 'dropout': 0.6000000000000001, 'batch_size': 64, 'learning_rate': 0.0019746665214548397, 'weight_decay': 1.0765297111661137e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.2598487657108217, 'early_stopping_min_delta': 0.0002677589148679903}. Best is trial 3 with value: -0.011473394984568777.

  Epoch 016 - train 0.43014 | val 0.81551
  Regression -> MSE: 0.000244, MAE: 0.012484, R²: -0.0168
  Directional -> Accuracy: 0.4833, MCC: -0.1796, F1: 0.0000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.39371 | val 0.79164
  Epoch 020 - train 0.37785 | val 0.82093
  Epoch 021 - train 0.37626 | val 0.81913
  Regression -> MSE: 0.000251, MAE: 0.012520, R²: -0.0126
  Directional -> Accuracy: 0.5325, MCC: 0.0527, F1: 0.4706

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.40096 | val 0.49659
  Epoch 020 - train 0.37405 | val 0.69732
  Epoch 021 - train 0.38766 | val 0.69530
  Regression -> MSE: 0.000654, MAE: 0.018613, R²: 0.0444
  Directional -> Accuracy: 0.5652, MCC: 0.0510, F1: 0.6970

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.42579 | val 0.97093
  Epoch 020 - train 0.41059 | val 0.98116
  Epoch 024 - train 0.40476 | val 0.98211
  Regression -> MSE: 0.000316, MAE: 0.014478, R²: -0.0186
  Directional -> Accuracy: 0.4894, MCC: -0.0200, F1: 0.5000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.32403 | val 3.07465
  Epoch 016 - train 0.32171 | val 3.04000
  Regression -> MSE: 0.000404, MAE: 0.015642, R²: -0.1553
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.39542 | val 0.48730
  Epoch 020 - train 0.37809 | val 0.55919
  Epoch 022 - train 0.37924 | val 0.55980
  Regression -> MSE: 0.000194, MAE: 0.009861, R²: 0.0449
  Directional -> Accuracy: 0.5882, MCC: 0.2986, F1: 0.4000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.37894 | val 1.13827
  Epoch 016 - train 0.37188 | val 1.13971
  Regression -> MSE: 0.000559, MAE: 0.018172, R²: -0.0071
  Directional -> Accuracy: 0.5319, MCC: 0.0687, F1: 0.2667

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.39638 | val 0.76273
  Epoch 019 - train 0.39600 | val 0.77790
  Regression -> MSE: 0.000242, MAE: 0.012133, R²: 0.0144
  Directional -> Accuracy: 0.5072, MCC: 0.0835, F1: 0.5405

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.40453 | val 0.68666
  Epoch 016 - train 0.36831 | val 0.84052
  Regression -> MSE: 0.000611, MAE: 0.019488, R²: -0.0231
  Directional -> Accuracy: 0.5227, MCC: -0.1523, F1: 0.0870

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.40382 | val 0.59539
  Epoch 016 - train 0.39977 | val 0.62181
  Regression -> MSE: 0.000392, MAE: 0.015977, R²: -0.0215
  Directional -> Accuracy: 0.3673, MCC: -0.2464, F1: 0.4364

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.39794 | val 0.89681
  Epoch 018 - train 0.38532 | val 0.92086
  Regression -> MSE: 0.000240, MAE: 0.011782, R²: 0.0069
  Directional -> Accuracy: 0.4286, MCC: -0.0355, F1: 0.5833

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.38063 | val 1.45705
  Epoch 016 - train 0.36309 | val 1.93678
  Regression -> MSE: 0.000312, MAE: 0.013658, R²: -0.0041
  Directional -> Accuracy: 0.4800, MCC: -0.0467, F1: 0.4348

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.42572 | val 0.71840
  Epoch 016 - train 0.41402 | val 0.82882
  Regression -> MSE: 0.000679, MAE: 0.019553, R²: -0.0025
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.42167 | val 0.73730
  Epoch 016 - train 0.38782 | val 1.02917
  Regression -> MSE: 0.000138, MAE: 0.009150, R²: -0.0018
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.36834 | val 0.72348
  Epoch 020 - train 0.33471 | val 0.79734
  Epoch 021 - train 0.34230 | val 0.80046
  Regression -> MSE: 0.000219, MAE: 0.010552, R²: 0.0263
  Directional -> Accuracy: 0.5410, MCC: 0.0817, F1: 0.5484

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.38848 | val 1.49300
  Epoch 020 - train 0.38744 | val 1.90086
  Regression -> MSE: 0.000358, MAE: 0.015852, R²: 0.0106
  Directional -> Accuracy: 0.6538, MCC: 0.3086, F1: 0.6400

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.42520 | val 0.51369
  Epoch 016 - train 0.40691 | val 0.51613
  Regression -> MSE: 0.000111, MAE: 0.007983, R²: -0.0290
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.38699 | val 1.26494
  Epoch 016 - train 0.38391 | val 1.37313
  Regression -> MSE: 0.000163, MAE: 0.010220, R²: -0.0454
  Directional -> Accuracy: 0.4237, MCC: 0.0347, F1: 0.2609

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.41488 | val 0.65663
  Epoch 016 - train 0.40093 | val 0.72169
  Regression -> MSE: 0.000283, MAE: 0.013612, R²: -0.0402
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.34568 | val 0.70425
  Epoch 020 - train 0.31572 | val 0.70060
  Epoch 027 - train 0.32089 | val 0.70182
  Regression -> MSE: 0.000262, MAE: 0.012713, R²: -0.7522
  Directional -> Accuracy: 0.4769, MCC: 0.0998, F1: 0.2917

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.39309 | val 0.88515
  Epoch 020 - train 0.37110 | val 0.92453
  Epoch 021 - train 0.38189 | val 0.92458
  Regression -> MSE: 0.000365, MAE: 0.014414, R²: -0.6142
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.41648 | val 0.74339
  Epoch 018 - train 0.37542 | val 0.92472
  Regression -> MSE: 0.000152, MAE: 0.008773, R²: -0.0582
  Directional -> Accuracy: 0.4375, MCC: 0.1233, F1: 0.2286

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.39082 | val 0.69044
  Epoch 016 - train 0.38984 | val 0.71820
  Regression -> MSE: 0.000171, MAE: 0.010225, R²: -0.0325
  Directional -> Accuracy: 0.6515, MCC: 0.3043, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.43951 | val 0.62964
  Epoch 020 - train 0.41197 | val 0.62647
  Epoch 029 - train 0.39753 | val 0.62460
  Regression -> MSE: 0.000089, MAE: 0.007184, R²: -0.0483
  Directional -> Accuracy: 0.5172, MCC: 0.1165, F1: 0.4167

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.40166 | val 2.24367
  Epoch 016 - train 0.40413 | val 2.51729
  Regression -> MSE: 0.000210, MAE: 0.011055, R²: 0.0091
  Directional -> Accuracy: 0.5606, MCC: 0.1782, F1: 0.6420

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.34387 | val 0.31769
  Epoch 020 - train 0.30797 | val 0.31039
  Epoch 030 - train 0.30233 | val 0.31512
  Regression -> MSE: 0.000104, MAE: 0.008241, R²: -0.1261
  Directional -> Accuracy: 0.5714, MCC: 0.1762, F1: 0.5385

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.43183 | val 0.33829
  Epoch 020 - train 0.38547 | val 0.32446
  Epoch 030 - train 0.39424 | val 0.32644
  Regression -> MSE: 0.000102, MAE: 0.008523, R²: 0.0128
  Directional -> Accuracy: 0.6087, MCC: 0.4024, F1: 0.6897

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.42861 | val 0.81554
  Epoch 016 - train 0.40259 | val 0.93246
  Regression -> MSE: 0.000246, MAE: 0.012998, R²: -0.0641
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.42370 | val 0.67064
  Epoch 016 - train 0.41253 | val 0.70707
  Regression -> MSE: 0.000170, MAE: 0.007810, R²: -0.0231
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.43079 | val 0.31216
  Epoch 020 - train 0.37429 | val 0.29419
  Epoch 030 - train 0.36705 | val 0.31063
  Regression -> MSE: 0.000218, MAE: 0.011488, R²: 0.0785
  Directional -> Accuracy: 0.5854, MCC: 0.1688, F1: 0.7018

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.41359 | val 1.00660
  Epoch 016 - train 0.41529 | val 1.05624
  Regression -> MSE: 0.000230, MAE: 0.009874, R²: 0.0027
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.41044 | val 0.67646
  Epoch 020 - train 0.37354 | val 0.80010
  Regression -> MSE: 0.000138, MAE: 0.008398, R²: -0.0195
  Directional -> Accuracy: 0.4186, MCC: -0.1533, F1: 0.1935

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.38828 | val 0.73446
  Epoch 016 - train 0.39701 | val 0.78481
  Regression -> MSE: 0.000188, MAE: 0.010378, R²: 0.0008
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.35197 | val 0.60774
  Epoch 020 - train 0.34010 | val 0.63342
  Epoch 021 - train 0.33244 | val 0.63488
  Regression -> MSE: 0.000362, MAE: 0.013105, R²: -0.3809
  Directional -> Accuracy: 0.5342, MCC: 0.1602, F1: 0.4138

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.39966 | val 0.35989
  Epoch 020 - train 0.36359 | val 0.52747
  Epoch 022 - train 0.34971 | val 0.61884
  Regression -> MSE: 0.000164, MAE: 0.010334, R²: 0.0190
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.36855 | val 0.63847
  Epoch 016 - train 0.36047 | val 0.67536
  Regression -> MSE: 0.000181, MAE: 0.010304, R²: -0.0082
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.36858 | val 0.45789
  Epoch 020 - train 0.36244 | val 0.47347
  Regression -> MSE: 0.000353, MAE: 0.013035, R²: -0.0305
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.42307 | val 0.22764
  Epoch 020 - train 0.39298 | val 0.30305
  Epoch 022 - train 0.36916 | val 0.30820
  Regression -> MSE: 0.000115, MAE: 0.008299, R²: -0.0942
  Directional -> Accuracy: 0.6047, MCC: 0.3278, F1: 0.7213

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.40817 | val 0.99018
  Epoch 019 - train 0.38630 | val 1.20265
  Regression -> MSE: 0.000218, MAE: 0.011276, R²: 0.0004
  Directional -> Accuracy: 0.4737, MCC: -0.0518, F1: 0.4643

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.38618 | val 1.16751
  Epoch 016 - train 0.37177 | val 1.28311
  Regression -> MSE: 0.000081, MAE: 0.007032, R²: -0.0489
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.39821 | val 0.31357
  Epoch 016 - train 0.40249 | val 0.34329
  Regression -> MSE: 0.000320, MAE: 0.014576, R²: -0.0414
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.42101 | val 0.20852
  Epoch 016 - train 0.42524 | val 0.21922
  Regression -> MSE: 0.000252, MAE: 0.011480, R²: -0.0343
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.35662 | val 0.63127
  Epoch 018 - train 0.35042 | val 0.64046
  Regression -> MSE: 0.000080, MAE: 0.007033, R²: 0.0121
  Directional -> Accuracy: 0.5200, MCC: 0.1633, F1: 0.6727

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.41349 | val 0.62815
  Epoch 020 - train 0.40788 | val 0.61802
  Epoch 029 - train 0.37328 | val 0.63170
  Regression -> MSE: 0.000311, MAE: 0.014358, R²: -0.0129
  Directional -> Accuracy: 0.5106, MCC: 0.0065, F1: 0.6567

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.37385 | val 0.57739
  Epoch 016 - train 0.36818 | val 0.58113
  Regression -> MSE: 0.000100, MAE: 0.007102, R²: -0.0212
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.43291 | val 0.71084
  Epoch 020 - train 0.36453 | val 0.70973
  Epoch 029 - train 0.36357 | val 0.70326
  Regression -> MSE: 0.000302, MAE: 0.014258, R²: -0.7551
  Directional -> Accuracy: 0.3878, MCC: -0.0687, F1: 0.5312

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.36938 | val 1.30941
  Epoch 016 - train 0.37212 | val 1.72622
  Regression -> MSE: 0.000223, MAE: 0.011726, R²: -0.0018
  Directional -> Accuracy: 0.6071, MCC: 0.2038, F1: 0.6857

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.39235 | val 0.76019
  Epoch 019 - train 0.37231 | val 0.86734
  Regression -> MSE: 0.000093, MAE: 0.007762, R²: -0.0066
  Directional -> Accuracy: 0.5088, MCC: 0.1809, F1: 0.6585

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.42581 | val 1.16303
  Epoch 016 - train 0.41318 | val 1.42774
  Regression -> MSE: 0.000168, MAE: 0.010327, R²: -0.0234
  Directional -> Accuracy: 0.4815, MCC: 0.0000, F1: 0.0000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.39300 | val 0.72540
  Epoch 016 - train 0.38479 | val 0.76034
  Regression -> MSE: 0.000119, MAE: 0.008994, R²: -0.0242
  Directional -> Accuracy: 0.5000, MCC: -0.0709, F1: 0.6585

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.41615 | val 0.93668

[I 2026-02-22 21:05:33,983] Trial 18 finished with value: -0.011693062208551694 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.30000000000000004, 'batch_size': 32, 'learning_rate': 5.453054099448074e-05, 'weight_decay': 9.821052471911984e-07, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 30, 'huber_delta': 1.5481748080521998, 'early_stopping_min_delta': 0.002113821849510393}. Best is trial 3 with value: -0.011473394984568777.

  Epoch 016 - train 0.40926 | val 0.94697
  Regression -> MSE: 0.000241, MAE: 0.012334, R²: -0.0182
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 36
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.43331 | val 0.92176
  Epoch 020 - train 0.42186 | val 1.15005
  Regression -> MSE: 0.000237, MAE: 0.012155, R²: -0.0052
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.6168

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 112). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.45976 | val 0.55895
  Epoch 020 - train 0.41512 | val 0.55170
  Regression -> MSE: 0.000719, MAE: 0.019748, R²: -0.0081
  Directional -> Accuracy: 0.6279, MCC: 0.1800, F1: 0.7241

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for AEP (109 < 112). Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 112). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.44908 | val 1.12660
  Epoch 020 - train 0.42645 | val 1.13148
  Regression -> MSE: 0.000318, MAE: 0.014551, R²: 0.0011
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.6866

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.39342 | val 0.51526
  Epoch 020 - train 0.37734 | val 0.55037
  Regression -> MSE: 0.000381, MAE: 0.015019, R²: -0.0689
  Directional -> Accuracy: 0.4583, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.45348 | val 0.46121
  Epoch 020 - train 0.42708 | val 0.44100
  Regression -> MSE: 0.000197, MAE: 0.009497, R²: 0.0635
  Directional -> Accuracy: 0.6875, MCC: 0.4320, F1: 0.6154

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.43271 | val 1.04215
  Epoch 020 - train 0.39702 | val 1.09008
  Regression -> MSE: 0.000572, MAE: 0.018229, R²: -0.0208
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.46013 | val 0.69011
  Epoch 020 - train 0.43501 | val 0.77222
  Regression -> MSE: 0.000254, MAE: 0.012152, R²: 0.0051
  Directional -> Accuracy: 0.5303, MCC: 0.0116, F1: 0.3922

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 112). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 112). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.40226 | val 0.56239
  Epoch 020 - train 0.40153 | val 0.65092
  Regression -> MSE: 0.000620, MAE: 0.019621, R²: -0.0707
  Directional -> Accuracy: 0.4359, MCC: 0.0000, F1: 0.6071

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.41643 | val 0.71826
  Epoch 020 - train 0.41527 | val 0.84130
  Regression -> MSE: 0.000385, MAE: 0.015816, R²: -0.0084
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 112). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 112). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 112). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.45113 | val 0.77947
  Epoch 020 - train 0.44486 | val 0.91822
  Regression -> MSE: 0.000249, MAE: 0.011702, R²: -0.0093
  Directional -> Accuracy: 0.6119, MCC: 0.1697, F1: 0.1875

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.40389 | val 0.86254
  Epoch 020 - train 0.42856 | val 0.87867
  Regression -> MSE: 0.000312, MAE: 0.013367, R²: 0.0008
  Directional -> Accuracy: 0.5532, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.49759 | val 0.65320
  Epoch 020 - train 0.46282 | val 0.68000
  Regression -> MSE: 0.000701, MAE: 0.019781, R²: -0.0079
  Directional -> Accuracy: 0.4727, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 112). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.44833 | val 0.54289
  Epoch 020 - train 0.44431 | val 0.57124
  Regression -> MSE: 0.000145, MAE: 0.009483, R²: 0.0002
  Directional -> Accuracy: 0.4792, MCC: 0.0000, F1: 0.6479

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 112). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.40166 | val 0.76919
  Epoch 020 - train 0.39122 | val 0.82657
  Regression -> MSE: 0.000222, MAE: 0.010525, R²: 0.0313
  Directional -> Accuracy: 0.5690, MCC: 0.1344, F1: 0.6377

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.45100 | val 1.56359
  Epoch 020 - train 0.41611 | val 1.73824
  Regression -> MSE: 0.000374, MAE: 0.016227, R²: -0.0015
  Directional -> Accuracy: 0.4898, MCC: -0.0101, F1: 0.4898

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.46171 | val 0.53333
  Epoch 020 - train 0.45801 | val 0.55942
  Regression -> MSE: 0.000108, MAE: 0.007935, R²: 0.0179
  Directional -> Accuracy: 0.5522, MCC: 0.1037, F1: 0.5714

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 112). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.43100 | val 1.25423
  Epoch 020 - train 0.43480 | val 1.35821
  Regression -> MSE: 0.000152, MAE: 0.009686, R²: -0.0023
  Directional -> Accuracy: 0.6071, MCC: 0.0000, F1: 0.7556

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.47551 | val 0.53541
  Epoch 020 - train 0.44400 | val 0.58836
  Regression -> MSE: 0.000297, MAE: 0.013949, R²: -0.0700
  Directional -> Accuracy: 0.4110, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.37873 | val 0.78537
  Epoch 020 - train 0.36633 | val 0.76435
  Regression -> MSE: 0.000205, MAE: 0.011121, R²: -0.3275
  Directional -> Accuracy: 0.4839, MCC: -0.1463, F1: 0.6190

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 112). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.44480 | val 1.10334
  Epoch 020 - train 0.43541 | val 1.14945
  Regression -> MSE: 0.000277, MAE: 0.012032, R²: -0.2158
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.42440 | val 0.80889
  Epoch 020 - train 0.42150 | val 0.81303
  Regression -> MSE: 0.000149, MAE: 0.008396, R²: -0.0080
  Directional -> Accuracy: 0.6000, MCC: 0.0000, F1: 0.7500

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 112). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 112). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 112). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.42526 | val 0.56891
  Epoch 020 - train 0.43316 | val 0.60629
  Regression -> MSE: 0.000182, MAE: 0.010489, R²: -0.0663
  Directional -> Accuracy: 0.5079, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.46308 | val 0.72223
  Epoch 020 - train 0.45597 | val 0.89156
  Regression -> MSE: 0.000089, MAE: 0.007267, R²: -0.0054
  Directional -> Accuracy: 0.5818, MCC: 0.0000, F1: 0.7356

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.44864 | val 0.75261
  Epoch 020 - train 0.42891 | val 0.82049
  Regression -> MSE: 0.000217, MAE: 0.011094, R²: -0.0020
  Directional -> Accuracy: 0.5556, MCC: 0.1077, F1: 0.3000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.40397 | val 0.40240
  Epoch 020 - train 0.35384 | val 0.36904
  Regression -> MSE: 0.000097, MAE: 0.008147, R²: -0.0773
  Directional -> Accuracy: 0.5283, MCC: 0.0740, F1: 0.5098

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.50506 | val 0.56619
  Epoch 020 - train 0.47017 | val 0.54832
  Regression -> MSE: 0.000100, MAE: 0.008433, R²: -0.0879
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.44647 | val 0.27605
  Epoch 020 - train 0.43693 | val 0.30669
  Regression -> MSE: 0.000294, MAE: 0.013490, R²: -0.0564
  Directional -> Accuracy: 0.4167, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.44756 | val 0.69869
  Epoch 020 - train 0.41865 | val 0.69240
  Regression -> MSE: 0.000211, MAE: 0.008613, R²: -0.2318
  Directional -> Accuracy: 0.4630, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
Insufficient data for proper time series validation for MDT. Skipping...

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.48158 | val 1.21917
  Epoch 020 - train 0.44447 | val 1.23940
  Regression -> MSE: 0.000239, MAE: 0.010092, R²: 0.0003
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.43495 | val 0.67214
  Epoch 020 - train 0.38694 | val 0.70782
  Regression -> MSE: 0.000152, MAE: 0.008941, R²: -0.0666
  Directional -> Accuracy: 0.4500, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.44891 | val 0.79764
  Epoch 020 - train 0.43718 | val 0.77802
  Regression -> MSE: 0.000195, MAE: 0.010677, R²: -0.0212
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.38534 | val 0.67667
  Epoch 020 - train 0.36748 | val 0.67984
  Regression -> MSE: 0.000277, MAE: 0.010981, R²: -0.0411
  Directional -> Accuracy: 0.5571, MCC: 0.1409, F1: 0.5373

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 112). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.41774 | val 0.47713
  Epoch 020 - train 0.38163 | val 0.46973
  Regression -> MSE: 0.000219, MAE: 0.011590, R²: -0.0526
  Directional -> Accuracy: 0.5306, MCC: 0.1820, F1: 0.6567

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 112). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.42586 | val 0.45151
  Epoch 020 - train 0.40938 | val 0.44172
  Regression -> MSE: 0.000376, MAE: 0.013549, R²: -0.0534
  Directional -> Accuracy: 0.4375, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.41938 | val 0.29751
  Epoch 020 - train 0.40327 | val 0.29438
  Regression -> MSE: 0.000100, MAE: 0.007845, R²: -0.0311
  Directional -> Accuracy: 0.4898, MCC: 0.0000, F1: 0.6575

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.46786 | val 1.00144
  Epoch 020 - train 0.43889 | val 1.03303
  Regression -> MSE: 0.000217, MAE: 0.011171, R²: -0.0008
  Directional -> Accuracy: 0.5370, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.43237 | val 1.37552
  Epoch 020 - train 0.41039 | val 1.39284
  Regression -> MSE: 0.000076, MAE: 0.006741, R²: -0.0649
  Directional -> Accuracy: 0.6136, MCC: 0.0927, F1: 0.7385

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 112). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for PPL (108 < 112). Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 112). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 112). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 112). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.48644 | val 0.27962
  Epoch 020 - train 0.46221 | val 0.28104
  Regression -> MSE: 0.000299, MAE: 0.013359, R²: -0.0033
  Directional -> Accuracy: 0.6667, MCC: 0.0000, F1: 0.0000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 112). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 112). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 112). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.40165 | val 0.69546
  Epoch 020 - train 0.39489 | val 0.98248
  Regression -> MSE: 0.000078, MAE: 0.006942, R²: -0.0001
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 112). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 112). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 112). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 112). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.47925 | val 0.78480
  Epoch 020 - train 0.43514 | val 0.77325
  Regression -> MSE: 0.000295, MAE: 0.014407, R²: -0.0422
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.44948 | val 0.47053
  Epoch 020 - train 0.40572 | val 0.46686
  Regression -> MSE: 0.000112, MAE: 0.007525, R²: -0.0274
  Directional -> Accuracy: 0.5897, MCC: 0.0000, F1: 0.7419

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.48035 | val 0.85565
  Epoch 020 - train 0.41665 | val 0.87212
  Regression -> MSE: 0.000183, MAE: 0.010011, R²: -0.0019
  Directional -> Accuracy: 0.3556, MCC: -0.1621, F1: 0.4912

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.41520 | val 0.61272
  Epoch 020 - train 0.41926 | val 0.67085
  Regression -> MSE: 0.000232, MAE: 0.011954, R²: -0.0032
  Directional -> Accuracy: 0.5472, MCC: 0.0000, F1: 0.7073

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.42153 | val 0.82476
  Epoch 020 - train 0.39898 | val 1.13221
  Regression -> MSE: 0.000088, MAE: 0.007501, R²: -0.0013
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.45946 | val 1.07381
  Epoch 020 - train 0.48214 | val 1.11300
  Regression -> MSE: 0.000169, MAE: 0.010415, R²: 0.0041
  Directional -> Accuracy: 0.5490, MCC: 0.1165, F1: 0.6230

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.44005 | val 0.84706
  Epoch 020 - train 0.41659 | val 1.21658
  Regression -> MSE: 0.000119, MAE: 0.009063, R²: -0.0060
  Directional -> Accuracy: 0.5094, MCC: 0.0000, F1: 0.6750

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.45777 | val 1.08792

[I 2026-02-22 21:07:18,088] Trial 19 finished with value: -0.011574439460537163 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 36, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.1, 'dropout': 0.4, 'batch_size': 64, 'learning_rate': 0.000217281092437681, 'weight_decay': 9.643051779138014e-06, 'lr_patience': 7, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 1.972005553148744, 'early_stopping_min_delta': 0.006393815247127875}. Best is trial 3 with value: -0.011473394984568777.

  Epoch 020 - train 0.44736 | val 1.43306
  Regression -> MSE: 0.000248, MAE: 0.012706, R²: -0.0031
  Directional -> Accuracy: 0.4655, MCC: 0.0000, F1: 0.6353

================================================================================
Pipeline completed: 47/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (47, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 30
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.36108 | val 0.74915
  Epoch 016 - train 0.35517 | val 0.74733
  Regression -> MSE: 0.000239, MAE: 0.012209, R²: 0.0007
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 106). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.36068 | val 0.40501
  Epoch 016 - train 0.34786 | val 0.43561
  Regression -> MSE: 0.000750, MAE: 0.020507, R²: -0.0629
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 106). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.37498 | val 0.76497
  Epoch 016 - train 0.36791 | val 0.77859
  Regression -> MSE: 0.000322, MAE: 0.014766, R²: -0.0027
  Directional -> Accuracy: 0.5333, MCC: 0.0000, F1: 0.6957

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.30116 | val 0.45836
  Epoch 016 - train 0.29485 | val 0.41507
  Regression -> MSE: 0.000374, MAE: 0.015055, R²: -0.0482
  Directional -> Accuracy: 0.5342, MCC: 0.0000, F1: 0.6964

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.36793 | val 0.36692
  Epoch 020 - train 0.34589 | val 0.41743
  Epoch 023 - train 0.34714 | val 0.42062
  Regression -> MSE: 0.000209, MAE: 0.009785, R²: 0.0066
  Directional -> Accuracy: 0.4898, MCC: -0.0606, F1: 0.6377

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.36552 | val 0.73221
  Epoch 016 - train 0.35512 | val 0.74278
  Regression -> MSE: 0.000585, MAE: 0.018585, R²: -0.0182
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.37642 | val 0.51482
  Epoch 020 - train 0.35436 | val 0.53902
  Epoch 021 - train 0.36040 | val 0.53994
  Regression -> MSE: 0.000257, MAE: 0.012499, R²: -0.0209
  Directional -> Accuracy: 0.5373, MCC: 0.0557, F1: 0.4561

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 106). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 106). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.37370 | val 0.33431
  Epoch 020 - train 0.35051 | val 0.41078
  Epoch 021 - train 0.34916 | val 0.42441
  Regression -> MSE: 0.000631, MAE: 0.019909, R²: -0.0086
  Directional -> Accuracy: 0.5366, MCC: -0.0096, F1: 0.2400

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.37345 | val 0.55352
  Epoch 016 - train 0.35116 | val 0.60375
  Regression -> MSE: 0.000385, MAE: 0.015655, R²: -0.0289
  Directional -> Accuracy: 0.5532, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 106). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 106). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 106). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.37070 | val 0.55706
  Epoch 016 - train 0.35234 | val 0.55509
  Regression -> MSE: 0.000257, MAE: 0.011959, R²: -0.0328
  Directional -> Accuracy: 0.5735, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.32515 | val 0.71224
  Epoch 016 - train 0.32603 | val 0.77860
  Regression -> MSE: 0.000323, MAE: 0.013497, R²: -0.0283
  Directional -> Accuracy: 0.5417, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.38286 | val 0.66370
  Epoch 016 - train 0.37264 | val 0.75611
  Regression -> MSE: 0.000694, MAE: 0.019818, R²: 0.0051
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 106). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.38497 | val 0.39482
  Epoch 020 - train 0.35103 | val 0.58276
  Regression -> MSE: 0.000142, MAE: 0.009315, R²: 0.0011
  Directional -> Accuracy: 0.4286, MCC: -0.1678, F1: 0.5625

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 106). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.32526 | val 0.58116
  Epoch 020 - train 0.31087 | val 0.58210
  Regression -> MSE: 0.000227, MAE: 0.010684, R²: 0.0091
  Directional -> Accuracy: 0.5593, MCC: 0.1240, F1: 0.5185

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.37914 | val 1.11735
  Epoch 016 - train 0.36029 | val 1.21453
  Regression -> MSE: 0.000370, MAE: 0.016339, R²: -0.0087
  Directional -> Accuracy: 0.4400, MCC: 0.0000, F1: 0.6111

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.38896 | val 0.48006
  Epoch 016 - train 0.38311 | val 0.45786
  Regression -> MSE: 0.000109, MAE: 0.007924, R²: -0.0085
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 106). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.34839 | val 1.11295
  Epoch 016 - train 0.34545 | val 1.13679
  Regression -> MSE: 0.000147, MAE: 0.009488, R²: 0.0143
  Directional -> Accuracy: 0.6140, MCC: 0.0000, F1: 0.7609

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.37403 | val 0.43645
  Epoch 016 - train 0.36243 | val 0.50258
  Regression -> MSE: 0.000280, MAE: 0.013289, R²: -0.0127
  Directional -> Accuracy: 0.5135, MCC: -0.1654, F1: 0.6667

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.30694 | val 0.56322
  Epoch 016 - train 0.30084 | val 0.58056
  Regression -> MSE: 0.000170, MAE: 0.009212, R²: -0.1212
  Directional -> Accuracy: 0.4127, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 106). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.37077 | val 0.77137
  Epoch 016 - train 0.36159 | val 0.78260
  Regression -> MSE: 0.000231, MAE: 0.010804, R²: -0.0280
  Directional -> Accuracy: 0.4247, MCC: -0.2124, F1: 0.5435

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.37837 | val 0.55734
  Epoch 020 - train 0.34790 | val 0.72931
  Epoch 022 - train 0.35079 | val 0.73217
  Regression -> MSE: 0.000156, MAE: 0.008798, R²: -0.0621
  Directional -> Accuracy: 0.4348, MCC: 0.0460, F1: 0.2353

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 106). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 106). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 106). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.33294 | val 0.49471
  Epoch 016 - train 0.32737 | val 0.51109
  Regression -> MSE: 0.000186, MAE: 0.010492, R²: -0.1039
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.42160 | val 0.57955
  Epoch 016 - train 0.40253 | val 0.58676
  Regression -> MSE: 0.000088, MAE: 0.007181, R²: 0.0010
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.36556 | val 0.66736
  Epoch 018 - train 0.35534 | val 0.68701
  Regression -> MSE: 0.000212, MAE: 0.011063, R²: 0.0074
  Directional -> Accuracy: 0.5312, MCC: 0.1183, F1: 0.6250

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.33576 | val 0.35470
  Epoch 020 - train 0.31209 | val 0.32626
  Epoch 030 - train 0.30068 | val 0.31838
  Regression -> MSE: 0.000100, MAE: 0.007933, R²: -0.0938
  Directional -> Accuracy: 0.5926, MCC: 0.2295, F1: 0.5217

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.37329 | val 0.36075
  Epoch 020 - train 0.35752 | val 0.36554
  Epoch 023 - train 0.37242 | val 0.36510
  Regression -> MSE: 0.000115, MAE: 0.009091, R²: -0.1989
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.5902

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.39462 | val 0.33425
  Epoch 016 - train 0.38633 | val 0.35094
  Regression -> MSE: 0.000274, MAE: 0.012969, R²: -0.0066
  Directional -> Accuracy: 0.5918, MCC: 0.0000, F1: 0.7436

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.37498 | val 0.51253
  Epoch 016 - train 0.36287 | val 0.51468
  Regression -> MSE: 0.000172, MAE: 0.007820, R²: -0.0127
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.37277 | val 0.30797
  Epoch 020 - train 0.35824 | val 0.30294
  Epoch 030 - train 0.35644 | val 0.31296
  Regression -> MSE: 0.000251, MAE: 0.012300, R²: 0.0027
  Directional -> Accuracy: 0.5526, MCC: 0.0249, F1: 0.7018

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.37491 | val 0.75924
  Epoch 016 - train 0.35543 | val 0.76559
  Regression -> MSE: 0.000235, MAE: 0.009865, R²: -0.0041
  Directional -> Accuracy: 0.5122, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.43291 | val 0.51102
  Epoch 016 - train 0.39996 | val 0.53599
  Regression -> MSE: 0.000144, MAE: 0.008474, R²: -0.0351
  Directional -> Accuracy: 0.4390, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.37377 | val 0.53860
  Epoch 016 - train 0.36524 | val 0.53532
  Regression -> MSE: 0.000192, MAE: 0.010424, R²: -0.0284
  Directional -> Accuracy: 0.4792, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.29836 | val 0.52157
  Epoch 016 - train 0.29034 | val 0.51249
  Regression -> MSE: 0.000285, MAE: 0.011023, R²: -0.0668
  Directional -> Accuracy: 0.4366, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 106). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.32371 | val 0.42611
  Epoch 020 - train 0.29896 | val 0.41196
  Epoch 030 - train 0.28626 | val 0.42008
  Regression -> MSE: 0.000182, MAE: 0.010511, R²: 0.0317
  Directional -> Accuracy: 0.5476, MCC: 0.0853, F1: 0.4571

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 106). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.34408 | val 0.35154
  Epoch 020 - train 0.32988 | val 0.35264
  Epoch 023 - train 0.32710 | val 0.35182
  Regression -> MSE: 0.000363, MAE: 0.013308, R²: -0.0324
  Directional -> Accuracy: 0.4769, MCC: 0.0612, F1: 0.2917

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.37541 | val 0.21007
  Epoch 016 - train 0.36266 | val 0.20836
  Regression -> MSE: 0.000120, MAE: 0.008644, R²: -0.0946
  Directional -> Accuracy: 0.5250, MCC: 0.0000, F1: 0.6885

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.35910 | val 0.61910
  Epoch 020 - train 0.35345 | val 0.60602
  Epoch 029 - train 0.32765 | val 0.61788
  Regression -> MSE: 0.000269, MAE: 0.013403, R²: -0.2033
  Directional -> Accuracy: 0.4545, MCC: -0.0864, F1: 0.4444

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.36440 | val 0.85540
  Epoch 016 - train 0.35934 | val 0.90492
  Regression -> MSE: 0.000083, MAE: 0.007062, R²: -0.1687
  Directional -> Accuracy: 0.3778, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 106). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 106). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 106). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 106). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.40311 | val 0.25621
  Epoch 016 - train 0.39313 | val 0.27065
  Regression -> MSE: 0.000359, MAE: 0.015901, R²: -0.1282
  Directional -> Accuracy: 0.3261, MCC: 0.0000, F1: 0.4918

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 106). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 106). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 106). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.34371 | val 0.91512
  Epoch 016 - train 0.32873 | val 0.99913
  Regression -> MSE: 0.000077, MAE: 0.006864, R²: -0.0020
  Directional -> Accuracy: 0.4932, MCC: 0.0000, F1: 0.6606

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 106). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 106). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 106). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 106). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.39583 | val 0.61914
  Epoch 016 - train 0.38205 | val 0.68388
  Regression -> MSE: 0.000283, MAE: 0.013877, R²: -0.0174
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.37478 | val 0.43443
  Epoch 020 - train 0.35921 | val 0.43085
  Epoch 026 - train 0.33128 | val 0.43169
  Regression -> MSE: 0.000100, MAE: 0.007198, R²: 0.0330
  Directional -> Accuracy: 0.7073, MCC: 0.3909, F1: 0.7857

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.38940 | val 0.57001
  Epoch 016 - train 0.38959 | val 0.59217
  Regression -> MSE: 0.000182, MAE: 0.010375, R²: -0.0167
  Directional -> Accuracy: 0.3696, MCC: 0.0000, F1: 0.5397

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.34527 | val 0.48028
  Epoch 016 - train 0.33857 | val 0.49988
  Regression -> MSE: 0.000228, MAE: 0.011771, R²: -0.0026
  Directional -> Accuracy: 0.5370, MCC: -0.0286, F1: 0.6835

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.38989 | val 0.54904
  Epoch 016 - train 0.36531 | val 0.53008
  Regression -> MSE: 0.000091, MAE: 0.007620, R²: -0.0401
  Directional -> Accuracy: 0.5091, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.38822 | val 0.74032
  Epoch 016 - train 0.39080 | val 0.75853
  Regression -> MSE: 0.000167, MAE: 0.010366, R²: -0.0009
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.35934 | val 0.49857
  Epoch 020 - train 0.33890 | val 0.50040
  Epoch 026 - train 0.34105 | val 0.50205
  Regression -> MSE: 0.000183, MAE: 0.010825, R²: -0.5269
  Directional -> Accuracy: 0.4815, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.38682 | val 0.79990

[I 2026-02-22 21:09:26,700] Trial 20 finished with value: -0.011649539059974375 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 30, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.4, 'dropout': 0.2, 'batch_size': 32, 'learning_rate': 1.6414036603081777e-05, 'weight_decay': 1.0620600917868051e-07, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 30, 'huber_delta': 0.9223618043133626, 'early_stopping_min_delta': 0.004512776589175656}. Best is trial 3 with value: -0.011473394984568777.

  Epoch 016 - train 0.37401 | val 0.82152
  Regression -> MSE: 0.000244, MAE: 0.012718, R²: -0.0009
  Directional -> Accuracy: 0.4746, MCC: 0.0000, F1: 0.6437

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 30
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.35950 | val 0.53153
  Epoch 020 - train 0.35214 | val 0.55188
  Regression -> MSE: 0.000243, MAE: 0.012452, R²: -0.0168
  Directional -> Accuracy: 0.4267, MCC: -0.1277, F1: 0.4691

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 106). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.33822 | val 0.35996
  Epoch 020 - train 0.35021 | val 0.33879
  Regression -> MSE: 0.000713, MAE: 0.020148, R²: -0.0110
  Directional -> Accuracy: 0.5000, MCC: -0.0169, F1: 0.5600

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 106). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.33819 | val 0.66802
  Epoch 020 - train 0.35110 | val 0.65956
  Regression -> MSE: 0.000325, MAE: 0.014809, R²: -0.0122
  Directional -> Accuracy: 0.5333, MCC: 0.0000, F1: 0.6957

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.32620 | val 0.33508
  Epoch 016 - train 0.31954 | val 0.40400
  Regression -> MSE: 0.000359, MAE: 0.014751, R²: -0.0059
  Directional -> Accuracy: 0.5342, MCC: 0.0000, F1: 0.6964

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.38518 | val 0.34271
  Epoch 020 - train 0.38402 | val 0.33881
  Regression -> MSE: 0.000223, MAE: 0.010637, R²: -0.0576
  Directional -> Accuracy: 0.5102, MCC: 0.0000, F1: 0.6757

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.33861 | val 0.65946
  Epoch 016 - train 0.33264 | val 0.65683
  Regression -> MSE: 0.000593, MAE: 0.018787, R²: -0.0327
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.37067 | val 0.47940
  Epoch 016 - train 0.36808 | val 0.50300
  Regression -> MSE: 0.000253, MAE: 0.012138, R²: -0.0045
  Directional -> Accuracy: 0.5970, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 106). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 106). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.35356 | val 0.29000
  Epoch 020 - train 0.37187 | val 0.27825
  Regression -> MSE: 0.000631, MAE: 0.019851, R²: -0.0086
  Directional -> Accuracy: 0.5610, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.36550 | val 0.53798
  Epoch 016 - train 0.35851 | val 0.54005
  Regression -> MSE: 0.000374, MAE: 0.015910, R²: 0.0005
  Directional -> Accuracy: 0.4468, MCC: 0.0000, F1: 0.6176

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 106). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 106). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 106). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.40993 | val 0.50185
  Epoch 016 - train 0.40827 | val 0.60546
  Regression -> MSE: 0.000253, MAE: 0.011967, R²: -0.0204
  Directional -> Accuracy: 0.5735, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.31230 | val 0.61232
  Epoch 016 - train 0.32329 | val 0.62813
  Regression -> MSE: 0.000314, MAE: 0.013680, R²: -0.0007
  Directional -> Accuracy: 0.4583, MCC: 0.0000, F1: 0.6286

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.37876 | val 0.44684
  Epoch 016 - train 0.37822 | val 0.45140
  Regression -> MSE: 0.000703, MAE: 0.020010, R²: -0.0085
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 106). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.36480 | val 0.37446
  Epoch 016 - train 0.36561 | val 0.37924
  Regression -> MSE: 0.000142, MAE: 0.009292, R²: 0.0000
  Directional -> Accuracy: 0.4898, MCC: 0.0000, F1: 0.6575

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 106). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.32101 | val 0.55097
  Epoch 016 - train 0.31558 | val 0.56454
  Regression -> MSE: 0.000230, MAE: 0.010876, R²: -0.0059
  Directional -> Accuracy: 0.5085, MCC: 0.0000, F1: 0.6742

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.34002 | val 0.88537
  Epoch 020 - train 0.34541 | val 0.86723
  Regression -> MSE: 0.000372, MAE: 0.016310, R²: -0.0139
  Directional -> Accuracy: 0.4200, MCC: -0.1361, F1: 0.4528

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.40553 | val 0.36205
  Epoch 016 - train 0.41476 | val 0.36710
  Regression -> MSE: 0.000111, MAE: 0.007932, R²: -0.0264
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 106). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.36037 | val 0.72104
  Epoch 016 - train 0.36192 | val 0.73152
  Regression -> MSE: 0.000148, MAE: 0.009363, R²: 0.0029
  Directional -> Accuracy: 0.6140, MCC: 0.0000, F1: 0.7609

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.36237 | val 0.36445
  Epoch 016 - train 0.35606 | val 0.40981
  Regression -> MSE: 0.000278, MAE: 0.013219, R²: -0.0070
  Directional -> Accuracy: 0.5946, MCC: 0.0000, F1: 0.7458

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.30383 | val 0.50442
  Epoch 016 - train 0.31539 | val 0.51098
  Regression -> MSE: 0.000167, MAE: 0.009123, R²: -0.0980
  Directional -> Accuracy: 0.4127, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 106). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.36639 | val 0.62504
  Epoch 020 - train 0.37039 | val 0.67843
  Regression -> MSE: 0.000227, MAE: 0.010650, R²: -0.0115
  Directional -> Accuracy: 0.5890, MCC: 0.1705, F1: 0.6250

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.35250 | val 0.50611
  Epoch 016 - train 0.35124 | val 0.50638
  Regression -> MSE: 0.000148, MAE: 0.008458, R²: -0.0084
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 106). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 106). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 106). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.33890 | val 0.43135
  Epoch 016 - train 0.32938 | val 0.44788
  Regression -> MSE: 0.000184, MAE: 0.010495, R²: -0.0960
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.37554 | val 0.44498
  Epoch 016 - train 0.36716 | val 0.44292
  Regression -> MSE: 0.000091, MAE: 0.007418, R²: -0.0399
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.36611 | val 0.48984
  Epoch 016 - train 0.36232 | val 0.48589
  Regression -> MSE: 0.000214, MAE: 0.011253, R²: -0.0038
  Directional -> Accuracy: 0.4688, MCC: 0.0000, F1: 0.6383

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.31506 | val 0.32244
  Epoch 020 - train 0.31638 | val 0.31506
  Regression -> MSE: 0.000096, MAE: 0.008155, R²: -0.0459
  Directional -> Accuracy: 0.5000, MCC: -0.0331, F1: 0.5970

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.35082 | val 0.35183
  Epoch 016 - train 0.35651 | val 0.35116
  Regression -> MSE: 0.000121, MAE: 0.009250, R²: -0.2603
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.5902

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.38156 | val 0.24774
  Epoch 016 - train 0.38613 | val 0.24701
  Regression -> MSE: 0.000276, MAE: 0.013045, R²: -0.0127
  Directional -> Accuracy: 0.5918, MCC: 0.0000, F1: 0.7436

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.35868 | val 0.45742
  Epoch 016 - train 0.34210 | val 0.47450
  Regression -> MSE: 0.000176, MAE: 0.007843, R²: -0.0396
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.36096 | val 0.32292
  Epoch 016 - train 0.37432 | val 0.32306
  Regression -> MSE: 0.000254, MAE: 0.012491, R²: -0.0114
  Directional -> Accuracy: 0.5526, MCC: 0.0000, F1: 0.7119

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.37589 | val 0.69215
  Epoch 016 - train 0.35932 | val 0.69432
  Regression -> MSE: 0.000234, MAE: 0.009875, R²: -0.0003
  Directional -> Accuracy: 0.4878, MCC: 0.0000, F1: 0.6557

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.37576 | val 0.44496
  Epoch 016 - train 0.37852 | val 0.44530
  Regression -> MSE: 0.000148, MAE: 0.008752, R²: -0.0623
  Directional -> Accuracy: 0.4390, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.38299 | val 0.49117
  Epoch 016 - train 0.38099 | val 0.49722
  Regression -> MSE: 0.000189, MAE: 0.010250, R²: -0.0127
  Directional -> Accuracy: 0.5208, MCC: 0.0352, F1: 0.5660

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.32708 | val 0.44809
  Epoch 016 - train 0.32717 | val 0.46048
  Regression -> MSE: 0.000281, MAE: 0.010886, R²: -0.0552
  Directional -> Accuracy: 0.4366, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 106). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.32625 | val 0.42864
  Epoch 016 - train 0.31195 | val 0.43096
  Regression -> MSE: 0.000197, MAE: 0.010959, R²: -0.0510
  Directional -> Accuracy: 0.4762, MCC: 0.0000, F1: 0.6452

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 106). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.35582 | val 0.35858
  Epoch 016 - train 0.36237 | val 0.36501
  Regression -> MSE: 0.000362, MAE: 0.012831, R²: -0.0299
  Directional -> Accuracy: 0.4308, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.38621 | val 0.20139
  Epoch 016 - train 0.37729 | val 0.20116
  Regression -> MSE: 0.000117, MAE: 0.008624, R²: -0.0622
  Directional -> Accuracy: 0.5250, MCC: 0.0000, F1: 0.6885

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.37139 | val 0.56016
  Epoch 016 - train 0.37492 | val 0.57821
  Regression -> MSE: 0.000224, MAE: 0.011451, R²: -0.0025
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.34712 | val 0.72477
  Epoch 016 - train 0.35586 | val 0.72629
  Regression -> MSE: 0.000083, MAE: 0.007060, R²: -0.1686
  Directional -> Accuracy: 0.3778, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 106). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 106). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 106). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 106). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.35057 | val 0.21079
  Epoch 016 - train 0.34462 | val 0.21132
  Regression -> MSE: 0.000348, MAE: 0.015521, R²: -0.0947
  Directional -> Accuracy: 0.3261, MCC: 0.0000, F1: 0.4918

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 106). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 106). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 106). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.34812 | val 0.49870
  Epoch 016 - train 0.35075 | val 0.50103
  Regression -> MSE: 0.000081, MAE: 0.006859, R²: -0.0466
  Directional -> Accuracy: 0.5068, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 106). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 106). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 106). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 106). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.37544 | val 0.53337
  Epoch 016 - train 0.35701 | val 0.53285
  Regression -> MSE: 0.000279, MAE: 0.013881, R²: -0.0017
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.33908 | val 0.38872
  Epoch 016 - train 0.34261 | val 0.38923
  Regression -> MSE: 0.000104, MAE: 0.007375, R²: -0.0017
  Directional -> Accuracy: 0.5854, MCC: 0.0000, F1: 0.7385

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.39110 | val 0.50505
  Epoch 016 - train 0.38232 | val 0.50489
  Regression -> MSE: 0.000184, MAE: 0.010536, R²: -0.0323
  Directional -> Accuracy: 0.3696, MCC: 0.0000, F1: 0.5397

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.31500 | val 0.41243
  Epoch 016 - train 0.32366 | val 0.41671
  Regression -> MSE: 0.000230, MAE: 0.011870, R²: -0.0123
  Directional -> Accuracy: 0.5000, MCC: 0.2169, F1: 0.1818

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.38128 | val 0.47170
  Epoch 016 - train 0.38021 | val 0.51219
  Regression -> MSE: 0.000089, MAE: 0.007555, R²: -0.0201
  Directional -> Accuracy: 0.5091, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.38321 | val 0.65486
  Epoch 016 - train 0.39187 | val 0.66702
  Regression -> MSE: 0.000167, MAE: 0.010357, R²: -0.0024
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.5806

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.35875 | val 0.49289
  Epoch 016 - train 0.37625 | val 0.52806
  Regression -> MSE: 0.000121, MAE: 0.009213, R²: -0.0125
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.36826 | val 0.61969

[I 2026-02-22 21:11:00,926] Trial 21 finished with value: -0.011601042942451262 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 30, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.1, 'batch_size': 64, 'learning_rate': 1.0377550151587941e-06, 'weight_decay': 2.933129382776564e-05, 'lr_patience': 7, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 0.778591554586541, 'early_stopping_min_delta': 0.0044099082186794}. Best is trial 3 with value: -0.011473394984568777.

  Epoch 016 - train 0.37014 | val 0.64833
  Regression -> MSE: 0.000244, MAE: 0.012681, R²: 0.0004
  Directional -> Accuracy: 0.4746, MCC: 0.0000, F1: 0.6437

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 36
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.35892 | val 0.55135
  Epoch 016 - train 0.35706 | val 0.59631
  Regression -> MSE: 0.000258, MAE: 0.012820, R²: -0.0970
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.6168

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 112). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.34035 | val 0.35922
  Epoch 020 - train 0.32635 | val 0.35401
  Regression -> MSE: 0.000773, MAE: 0.020791, R²: -0.0844
  Directional -> Accuracy: 0.3953, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for AEP (109 < 112). Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 112). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.34568 | val 0.63708
  Epoch 016 - train 0.34153 | val 0.63418
  Regression -> MSE: 0.000321, MAE: 0.014588, R²: -0.0076
  Directional -> Accuracy: 0.4318, MCC: -0.1412, F1: 0.4681

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.27345 | val 0.30301
  Epoch 016 - train 0.27704 | val 0.31485
  Regression -> MSE: 0.000374, MAE: 0.014905, R²: -0.0490
  Directional -> Accuracy: 0.4583, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.33627 | val 0.32897
  Epoch 016 - train 0.34111 | val 0.33119
  Regression -> MSE: 0.000210, MAE: 0.010177, R²: 0.0012
  Directional -> Accuracy: 0.5208, MCC: 0.0000, F1: 0.6849

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.33976 | val 0.65356
  Epoch 016 - train 0.33816 | val 0.68959
  Regression -> MSE: 0.000631, MAE: 0.019473, R²: -0.1261
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.33778 | val 0.43213
  Epoch 016 - train 0.33658 | val 0.43110
  Regression -> MSE: 0.000258, MAE: 0.012241, R²: -0.0101
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 112). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 112). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.33699 | val 0.36078
  Epoch 020 - train 0.33628 | val 0.35204
  Regression -> MSE: 0.000589, MAE: 0.019028, R²: -0.0167
  Directional -> Accuracy: 0.5128, MCC: -0.0425, F1: 0.2963

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.33771 | val 0.47906
  Epoch 016 - train 0.33457 | val 0.49288
  Regression -> MSE: 0.000382, MAE: 0.015905, R²: -0.0005
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 112). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 112). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 112). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.32944 | val 0.46233
  Epoch 016 - train 0.33421 | val 0.46648
  Regression -> MSE: 0.000248, MAE: 0.011837, R²: -0.0053
  Directional -> Accuracy: 0.5821, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.30468 | val 0.53323
  Epoch 020 - train 0.30899 | val 0.51860
  Regression -> MSE: 0.000313, MAE: 0.013268, R²: -0.0041
  Directional -> Accuracy: 0.5532, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.34307 | val 0.41001
  Epoch 016 - train 0.34413 | val 0.41289
  Regression -> MSE: 0.000694, MAE: 0.019668, R²: 0.0016
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 112). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.35985 | val 0.34671
  Epoch 016 - train 0.35032 | val 0.35374
  Regression -> MSE: 0.000145, MAE: 0.009441, R²: -0.0033
  Directional -> Accuracy: 0.4792, MCC: -0.0813, F1: 0.2424

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 112). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.29001 | val 0.48802
  Epoch 020 - train 0.29246 | val 0.47549
  Regression -> MSE: 0.000232, MAE: 0.010717, R²: -0.0108
  Directional -> Accuracy: 0.6034, MCC: 0.2055, F1: 0.6567

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.32653 | val 0.81122
  Epoch 016 - train 0.32883 | val 0.80808
  Regression -> MSE: 0.000381, MAE: 0.016123, R²: -0.0197
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.34593 | val 0.33921
  Epoch 020 - train 0.34419 | val 0.34370
  Regression -> MSE: 0.000111, MAE: 0.007957, R²: -0.0158
  Directional -> Accuracy: 0.5373, MCC: 0.0000, F1: 0.6990

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 112). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.32256 | val 0.64457
  Epoch 016 - train 0.32171 | val 0.65224
  Regression -> MSE: 0.000152, MAE: 0.009596, R²: -0.0044
  Directional -> Accuracy: 0.6071, MCC: 0.0000, F1: 0.7556

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.33562 | val 0.34825
  Epoch 016 - train 0.33505 | val 0.35683
  Regression -> MSE: 0.000279, MAE: 0.013204, R²: -0.0062
  Directional -> Accuracy: 0.5890, MCC: 0.0000, F1: 0.7414

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.28288 | val 0.47982
  Epoch 016 - train 0.28859 | val 0.49513
  Regression -> MSE: 0.000173, MAE: 0.009323, R²: -0.1202
  Directional -> Accuracy: 0.4194, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 112). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.34717 | val 0.56194
  Epoch 020 - train 0.35075 | val 0.61831
  Regression -> MSE: 0.000239, MAE: 0.010949, R²: -0.0521
  Directional -> Accuracy: 0.5278, MCC: 0.1569, F1: 0.3704

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.35123 | val 0.46604
  Epoch 020 - train 0.34419 | val 0.46034
  Regression -> MSE: 0.000154, MAE: 0.008371, R²: -0.0394
  Directional -> Accuracy: 0.5556, MCC: 0.1469, F1: 0.5652

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 112). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 112). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 112). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.36186 | val 0.41767
  Epoch 016 - train 0.36103 | val 0.42340
  Regression -> MSE: 0.000172, MAE: 0.010917, R²: -0.0069
  Directional -> Accuracy: 0.4921, MCC: 0.0000, F1: 0.6596

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.34836 | val 0.41856
  Epoch 020 - train 0.34951 | val 0.41003
  Regression -> MSE: 0.000090, MAE: 0.007321, R²: -0.0171
  Directional -> Accuracy: 0.5455, MCC: 0.1352, F1: 0.5283

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.34346 | val 0.44035
  Epoch 016 - train 0.33921 | val 0.44421
  Regression -> MSE: 0.000224, MAE: 0.011198, R²: -0.0337
  Directional -> Accuracy: 0.5238, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.30334 | val 0.31881
  Epoch 020 - train 0.29814 | val 0.29974
  Regression -> MSE: 0.000096, MAE: 0.008126, R²: -0.0681
  Directional -> Accuracy: 0.4717, MCC: -0.0740, F1: 0.5333

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.33372 | val 0.37748
  Epoch 020 - train 0.33137 | val 0.37181
  Regression -> MSE: 0.000101, MAE: 0.008591, R²: -0.1037
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.35033 | val 0.23594
  Epoch 016 - train 0.34242 | val 0.23684
  Regression -> MSE: 0.000285, MAE: 0.013293, R²: -0.0254
  Directional -> Accuracy: 0.5833, MCC: 0.0000, F1: 0.7368

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.32904 | val 0.44621
  Epoch 016 - train 0.33202 | val 0.45397
  Regression -> MSE: 0.000180, MAE: 0.007794, R²: -0.0511
  Directional -> Accuracy: 0.5556, MCC: 0.1397, F1: 0.5000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
Insufficient data for proper time series validation for MDT. Skipping...

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.32829 | val 0.66683
  Epoch 016 - train 0.31749 | val 0.67318
  Regression -> MSE: 0.000241, MAE: 0.010241, R²: -0.0074
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.34479 | val 0.37674
  Epoch 016 - train 0.37425 | val 0.38976
  Regression -> MSE: 0.000144, MAE: 0.008541, R²: -0.0114
  Directional -> Accuracy: 0.5500, MCC: 0.0000, F1: 0.7097

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.33659 | val 0.47353
  Epoch 016 - train 0.32902 | val 0.47418
  Regression -> MSE: 0.000191, MAE: 0.010565, R²: -0.0007
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.30024 | val 0.42745
  Epoch 016 - train 0.30033 | val 0.44234
  Regression -> MSE: 0.000273, MAE: 0.010567, R²: -0.0284
  Directional -> Accuracy: 0.4714, MCC: -0.1582, F1: 0.6105

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 112). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.31098 | val 0.29763
  Epoch 016 - train 0.29716 | val 0.30155
  Regression -> MSE: 0.000209, MAE: 0.011063, R²: -0.0011
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 112). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.30972 | val 0.32208
  Epoch 016 - train 0.30920 | val 0.32381
  Regression -> MSE: 0.000359, MAE: 0.012363, R²: -0.0057
  Directional -> Accuracy: 0.4375, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.36183 | val 0.23125
  Epoch 016 - train 0.36015 | val 0.23297
  Regression -> MSE: 0.000100, MAE: 0.007824, R²: -0.0276
  Directional -> Accuracy: 0.4898, MCC: 0.0000, F1: 0.6575

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.34793 | val 0.58027
  Epoch 016 - train 0.34614 | val 0.59467
  Regression -> MSE: 0.000223, MAE: 0.011453, R²: -0.0294
  Directional -> Accuracy: 0.4630, MCC: 0.0000, F1: 0.6329

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.34576 | val 0.69986
  Epoch 016 - train 0.33998 | val 0.69848
  Regression -> MSE: 0.000083, MAE: 0.007029, R²: -0.1534
  Directional -> Accuracy: 0.3864, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 112). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for PPL (108 < 112). Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 112). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 112). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 112). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.33721 | val 0.24662
  Epoch 016 - train 0.32885 | val 0.24605
  Regression -> MSE: 0.000316, MAE: 0.014743, R²: -0.0605
  Directional -> Accuracy: 0.3333, MCC: 0.0000, F1: 0.5000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 112). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 112). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 112). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.37650 | val 0.44499
  Epoch 016 - train 0.37335 | val 0.44667
  Regression -> MSE: 0.000079, MAE: 0.007004, R²: -0.0133
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 112). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 112). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 112). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 112). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.35779 | val 0.54512
  Epoch 016 - train 0.35829 | val 0.55309
  Regression -> MSE: 0.000290, MAE: 0.013945, R²: -0.0265
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.33475 | val 0.29226
  Epoch 016 - train 0.34115 | val 0.29208
  Regression -> MSE: 0.000109, MAE: 0.007862, R²: -0.0009
  Directional -> Accuracy: 0.4103, MCC: 0.0000, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.34387 | val 0.46254
  Epoch 016 - train 0.33743 | val 0.46273
  Regression -> MSE: 0.000183, MAE: 0.010081, R²: -0.0027
  Directional -> Accuracy: 0.3778, MCC: 0.0000, F1: 0.5484

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.30227 | val 0.39507
  Epoch 016 - train 0.29656 | val 0.39751
  Regression -> MSE: 0.000237, MAE: 0.012060, R²: -0.0267
  Directional -> Accuracy: 0.4528, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.34790 | val 0.44528
  Epoch 016 - train 0.34720 | val 0.44962
  Regression -> MSE: 0.000088, MAE: 0.007498, R²: -0.0051
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.36733 | val 0.57793
  Epoch 020 - train 0.36597 | val 0.58837
  Regression -> MSE: 0.000175, MAE: 0.010745, R²: -0.0278
  Directional -> Accuracy: 0.4902, MCC: 0.0000, F1: 0.6579

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.32576 | val 0.46393
  Epoch 016 - train 0.32001 | val 0.47775
  Regression -> MSE: 0.000122, MAE: 0.009103, R²: -0.0311
  Directional -> Accuracy: 0.4906, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.33113 | val 0.56752

[I 2026-02-22 21:12:49,689] Trial 22 finished with value: -0.011550515697213043 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 36, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.1, 'batch_size': 64, 'learning_rate': 1.6224089086402513e-06, 'weight_decay': 1.9446579706621726e-05, 'lr_patience': 7, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 0.6867427056985729, 'early_stopping_min_delta': 0.0038850587741819107}. Best is trial 3 with value: -0.011473394984568777.

  Epoch 020 - train 0.33522 | val 0.57251
  Regression -> MSE: 0.000251, MAE: 0.012564, R²: -0.0144
  Directional -> Accuracy: 0.5345, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 47/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (47, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 30
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.44182 | val 0.83924
  Epoch 016 - train 0.44332 | val 0.86912
  Regression -> MSE: 0.000242, MAE: 0.012366, R²: -0.0121
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.6239

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 106). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.42902 | val 0.47195
  Epoch 020 - train 0.41931 | val 0.47348
  Regression -> MSE: 0.000732, MAE: 0.020222, R²: -0.0378
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 106). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.46153 | val 1.05161
  Epoch 020 - train 0.44178 | val 1.02766
  Regression -> MSE: 0.000323, MAE: 0.014736, R²: -0.0051
  Directional -> Accuracy: 0.4889, MCC: -0.2017, F1: 0.6567

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.37362 | val 0.46895
  Epoch 016 - train 0.37512 | val 0.55494
  Regression -> MSE: 0.000356, MAE: 0.014713, R²: 0.0005
  Directional -> Accuracy: 0.5342, MCC: 0.0000, F1: 0.6964

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.43131 | val 0.44764
  Epoch 020 - train 0.41026 | val 0.42825
  Regression -> MSE: 0.000197, MAE: 0.009741, R²: 0.0626
  Directional -> Accuracy: 0.6735, MCC: 0.3536, F1: 0.6522

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.44003 | val 0.99035
  Epoch 020 - train 0.41953 | val 0.99122
  Regression -> MSE: 0.000589, MAE: 0.018689, R²: -0.0260
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.47359 | val 0.68287
  Epoch 020 - train 0.44253 | val 0.65277
  Regression -> MSE: 0.000258, MAE: 0.012115, R²: -0.0258
  Directional -> Accuracy: 0.5522, MCC: 0.0582, F1: 0.4231

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 106). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 106). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.43539 | val 0.40630
  Epoch 016 - train 0.39659 | val 0.42104
  Regression -> MSE: 0.000659, MAE: 0.020364, R²: -0.0534
  Directional -> Accuracy: 0.4390, MCC: 0.0000, F1: 0.6102

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.43868 | val 0.72257
  Epoch 016 - train 0.44677 | val 0.74049
  Regression -> MSE: 0.000374, MAE: 0.015808, R²: -0.0003
  Directional -> Accuracy: 0.4468, MCC: 0.0000, F1: 0.6176

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 106). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 106). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 106). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.44481 | val 0.73133
  Epoch 016 - train 0.43473 | val 0.75040
  Regression -> MSE: 0.000256, MAE: 0.011932, R²: -0.0294
  Directional -> Accuracy: 0.5735, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.41786 | val 0.82776
  Epoch 016 - train 0.39908 | val 0.84631
  Regression -> MSE: 0.000318, MAE: 0.013531, R²: -0.0147
  Directional -> Accuracy: 0.5417, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.45226 | val 0.66176
  Epoch 016 - train 0.46253 | val 0.68686
  Regression -> MSE: 0.000701, MAE: 0.019907, R²: -0.0053
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 106). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.42664 | val 0.53724
  Epoch 016 - train 0.44201 | val 0.58317
  Regression -> MSE: 0.000144, MAE: 0.009450, R²: -0.0156
  Directional -> Accuracy: 0.4898, MCC: 0.0000, F1: 0.6575

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 106). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.40366 | val 0.76507
  Epoch 020 - train 0.38267 | val 0.72677
  Regression -> MSE: 0.000226, MAE: 0.010672, R²: 0.0101
  Directional -> Accuracy: 0.5424, MCC: 0.0840, F1: 0.5574

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.43881 | val 1.46240
  Epoch 016 - train 0.41443 | val 1.49105
  Regression -> MSE: 0.000369, MAE: 0.015909, R²: -0.0064
  Directional -> Accuracy: 0.5600, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.46054 | val 0.51696
  Epoch 016 - train 0.43369 | val 0.55001
  Regression -> MSE: 0.000108, MAE: 0.007960, R²: 0.0002
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 106). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.42450 | val 1.18707
  Epoch 020 - train 0.41491 | val 1.20078
  Regression -> MSE: 0.000147, MAE: 0.009506, R²: 0.0150
  Directional -> Accuracy: 0.6491, MCC: 0.2367, F1: 0.7297

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.45842 | val 0.49521
  Epoch 019 - train 0.45372 | val 0.98553
  Regression -> MSE: 0.000277, MAE: 0.013085, R²: -0.0031
  Directional -> Accuracy: 0.5946, MCC: 0.0000, F1: 0.7458

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.36702 | val 0.76527
  Epoch 020 - train 0.35595 | val 0.72592
  Regression -> MSE: 0.000215, MAE: 0.010932, R²: -0.4129
  Directional -> Accuracy: 0.4127, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 106). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.43304 | val 1.04087
  Epoch 020 - train 0.40980 | val 1.23341
  Regression -> MSE: 0.000258, MAE: 0.011442, R²: -0.1482
  Directional -> Accuracy: 0.4521, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.43453 | val 0.76901
  Epoch 016 - train 0.43484 | val 0.76875
  Regression -> MSE: 0.000147, MAE: 0.008364, R²: 0.0006
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 106). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 106). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 106). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.41797 | val 0.61871
  Epoch 019 - train 0.41648 | val 0.62673
  Regression -> MSE: 0.000169, MAE: 0.010809, R²: -0.0055
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.43988 | val 0.66697
  Epoch 020 - train 0.44884 | val 0.77249
  Regression -> MSE: 0.000091, MAE: 0.007399, R²: -0.0329
  Directional -> Accuracy: 0.5179, MCC: 0.1009, F1: 0.4490

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.44162 | val 0.71734
  Epoch 016 - train 0.44262 | val 0.74501
  Regression -> MSE: 0.000214, MAE: 0.011043, R²: -0.0033
  Directional -> Accuracy: 0.5312, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.41528 | val 0.42563
  Epoch 020 - train 0.39981 | val 0.37644
  Regression -> MSE: 0.000100, MAE: 0.008140, R²: -0.0945
  Directional -> Accuracy: 0.5000, MCC: 0.0331, F1: 0.4000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.46344 | val 0.43516
  Epoch 016 - train 0.46026 | val 0.43290
  Regression -> MSE: 0.000108, MAE: 0.008836, R²: -0.1208
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.5902

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.48274 | val 0.27526
  Epoch 020 - train 0.46501 | val 0.27809
  Regression -> MSE: 0.000293, MAE: 0.013434, R²: -0.0762
  Directional -> Accuracy: 0.4082, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.43663 | val 0.64065
  Epoch 020 - train 0.42967 | val 0.62921
  Regression -> MSE: 0.000181, MAE: 0.007805, R²: -0.0689
  Directional -> Accuracy: 0.5636, MCC: 0.1006, F1: 0.6471

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.48562 | val 0.38832
  Epoch 016 - train 0.46696 | val 0.40030
  Regression -> MSE: 0.000255, MAE: 0.012503, R²: -0.0138
  Directional -> Accuracy: 0.5526, MCC: 0.0000, F1: 0.7119

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.46618 | val 1.15786
  Epoch 016 - train 0.46687 | val 1.17479
  Regression -> MSE: 0.000234, MAE: 0.009923, R²: -0.0018
  Directional -> Accuracy: 0.4878, MCC: 0.0000, F1: 0.6557

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.43148 | val 0.65053
  Epoch 016 - train 0.41742 | val 0.67338
  Regression -> MSE: 0.000143, MAE: 0.008487, R²: -0.0293
  Directional -> Accuracy: 0.4390, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.46897 | val 0.71001
  Epoch 016 - train 0.44393 | val 0.71171
  Regression -> MSE: 0.000195, MAE: 0.010502, R²: -0.0445
  Directional -> Accuracy: 0.4792, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.37397 | val 0.65661
  Epoch 020 - train 0.37053 | val 0.64814
  Regression -> MSE: 0.000367, MAE: 0.013158, R²: -0.3756
  Directional -> Accuracy: 0.5070, MCC: 0.1231, F1: 0.3396

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 106). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.38952 | val 0.53313
  Epoch 016 - train 0.38306 | val 0.53291
  Regression -> MSE: 0.000187, MAE: 0.010548, R²: 0.0028
  Directional -> Accuracy: 0.5238, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 106). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.42368 | val 0.45912
  Epoch 020 - train 0.40027 | val 0.48589
  Regression -> MSE: 0.000368, MAE: 0.013267, R²: -0.0458
  Directional -> Accuracy: 0.4308, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.45789 | val 0.23477
  Epoch 020 - train 0.41594 | val 0.23444
  Regression -> MSE: 0.000122, MAE: 0.008382, R²: -0.1081
  Directional -> Accuracy: 0.7250, MCC: 0.4701, F1: 0.7027

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.43243 | val 0.87036
  Epoch 016 - train 0.43665 | val 0.88261
  Regression -> MSE: 0.000225, MAE: 0.011502, R²: -0.0067
  Directional -> Accuracy: 0.4545, MCC: -0.0430, F1: 0.5714

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.44320 | val 1.21030
  Epoch 020 - train 0.42459 | val 1.39172
  Regression -> MSE: 0.000086, MAE: 0.007219, R²: -0.2236
  Directional -> Accuracy: 0.3778, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 106). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 106). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 106). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 106). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.43336 | val 0.25742
  Epoch 016 - train 0.42480 | val 0.25730
  Regression -> MSE: 0.000357, MAE: 0.015859, R²: -0.1204
  Directional -> Accuracy: 0.3261, MCC: 0.0000, F1: 0.4918

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 106). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 106). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 106). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.41306 | val 0.71504
  Epoch 016 - train 0.39322 | val 0.77516
  Regression -> MSE: 0.000080, MAE: 0.006848, R²: -0.0410
  Directional -> Accuracy: 0.5068, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 106). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 106). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 106). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 106). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.47209 | val 0.76319
  Epoch 016 - train 0.44994 | val 0.76434
  Regression -> MSE: 0.000279, MAE: 0.013883, R²: -0.0013
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.43733 | val 0.56754
  Epoch 016 - train 0.42928 | val 0.56664
  Regression -> MSE: 0.000105, MAE: 0.007235, R²: -0.0149
  Directional -> Accuracy: 0.5854, MCC: 0.0000, F1: 0.7385

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.44915 | val 0.77399
  Epoch 016 - train 0.44158 | val 0.77587
  Regression -> MSE: 0.000179, MAE: 0.009872, R²: 0.0000
  Directional -> Accuracy: 0.3696, MCC: 0.0000, F1: 0.5397

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.40827 | val 0.58478
  Epoch 016 - train 0.40347 | val 0.61813
  Regression -> MSE: 0.000228, MAE: 0.011845, R²: -0.0028
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.42973 | val 0.75823
  Epoch 016 - train 0.42222 | val 0.79206
  Regression -> MSE: 0.000090, MAE: 0.007735, R²: -0.0320
  Directional -> Accuracy: 0.4909, MCC: 0.0000, F1: 0.6585

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.48215 | val 1.02373
  Epoch 020 - train 0.45920 | val 1.01321
  Regression -> MSE: 0.000182, MAE: 0.010921, R²: -0.0905
  Directional -> Accuracy: 0.5192, MCC: 0.1400, F1: 0.6753

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.41543 | val 0.71308
  Epoch 020 - train 0.39821 | val 0.71231
  Regression -> MSE: 0.000128, MAE: 0.009351, R²: -0.0673
  Directional -> Accuracy: 0.4444, MCC: -0.2035, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.46713 | val 0.96374

[I 2026-02-22 21:14:29,204] Trial 23 finished with value: -0.011673995304765141 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 30, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.0, 'batch_size': 64, 'learning_rate': 8.942093274378157e-05, 'weight_decay': 3.5199515512396268e-06, 'lr_patience': 7, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 1.7443257417635119, 'early_stopping_min_delta': 0.0030453066902523087}. Best is trial 3 with value: -0.011473394984568777.

  Epoch 020 - train 0.44613 | val 0.95076
  Regression -> MSE: 0.000247, MAE: 0.012402, R²: -0.0111
  Directional -> Accuracy: 0.5424, MCC: 0.0764, F1: 0.1818

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.36152 | val 0.60446
  Epoch 020 - train 0.33587 | val 0.78389
  Regression -> MSE: 0.000247, MAE: 0.012411, R²: -0.0272
  Directional -> Accuracy: 0.5132, MCC: 0.1445, F1: 0.6263

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.35811 | val 0.39936
  Epoch 020 - train 0.33856 | val 0.39504
  Regression -> MSE: 0.000689, MAE: 0.019466, R²: 0.0122
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.38574 | val 0.78431
  Epoch 020 - train 0.35798 | val 0.78658
  Regression -> MSE: 0.000323, MAE: 0.014587, R²: -0.0275
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.30685 | val 0.37568
  Epoch 016 - train 0.30027 | val 0.44636
  Regression -> MSE: 0.000354, MAE: 0.014676, R²: -0.0025
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.35699 | val 0.37853
  Epoch 020 - train 0.35269 | val 0.37706
  Regression -> MSE: 0.000207, MAE: 0.009974, R²: -0.0032
  Directional -> Accuracy: 0.5200, MCC: 0.0000, F1: 0.6842

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.33133 | val 0.87767
  Epoch 016 - train 0.33542 | val 0.93232
  Regression -> MSE: 0.000587, MAE: 0.018677, R²: -0.0376
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.34505 | val 0.53954
  Epoch 020 - train 0.33926 | val 0.81714
  Regression -> MSE: 0.000246, MAE: 0.012149, R²: 0.0066
  Directional -> Accuracy: 0.4706, MCC: 0.0220, F1: 0.5135

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.31647 | val 0.39323
  Epoch 016 - train 0.33232 | val 0.44565
  Regression -> MSE: 0.000624, MAE: 0.019722, R²: -0.0217
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.34385 | val 0.53036
  Epoch 020 - train 0.32705 | val 0.53300
  Regression -> MSE: 0.000365, MAE: 0.015677, R²: 0.0218
  Directional -> Accuracy: 0.4375, MCC: 0.0000, F1: 0.6087

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.35995 | val 0.58214
  Epoch 016 - train 0.34537 | val 0.60619
  Regression -> MSE: 0.000245, MAE: 0.012056, R²: 0.0015
  Directional -> Accuracy: 0.4203, MCC: 0.0000, F1: 0.5918

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.32365 | val 0.68088
  Epoch 016 - train 0.31984 | val 0.72379
  Regression -> MSE: 0.000312, MAE: 0.013600, R²: 0.0014
  Directional -> Accuracy: 0.6327, MCC: 0.2556, F1: 0.4375

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.37597 | val 0.50121
  Epoch 016 - train 0.36094 | val 0.52869
  Regression -> MSE: 0.000688, MAE: 0.019694, R²: -0.0035
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.36796 | val 0.46700
  Epoch 016 - train 0.37412 | val 0.54237
  Regression -> MSE: 0.000140, MAE: 0.009216, R²: -0.0110
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.32646 | val 0.59254
  Epoch 016 - train 0.30049 | val 0.63769
  Regression -> MSE: 0.000227, MAE: 0.010672, R²: -0.0012
  Directional -> Accuracy: 0.5333, MCC: 0.0981, F1: 0.6585

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.35106 | val 1.02088
  Epoch 020 - train 0.33582 | val 0.97626
  Regression -> MSE: 0.000511, MAE: 0.018862, R²: -0.3932
  Directional -> Accuracy: 0.4510, MCC: 0.0000, F1: 0.6216

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.37892 | val 0.42220
  Epoch 016 - train 0.37434 | val 0.48489
  Regression -> MSE: 0.000108, MAE: 0.007934, R²: -0.0002
  Directional -> Accuracy: 0.5362, MCC: 0.0000, F1: 0.6981

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.34413 | val 0.82255
  Epoch 016 - train 0.34406 | val 0.90821
  Regression -> MSE: 0.000157, MAE: 0.009609, R²: 0.0017
  Directional -> Accuracy: 0.6207, MCC: 0.0000, F1: 0.7660

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.37573 | val 0.42941
  Epoch 019 - train 0.36722 | val 0.97409
  Regression -> MSE: 0.000273, MAE: 0.012998, R²: 0.0038
  Directional -> Accuracy: 0.6000, MCC: 0.0000, F1: 0.7500

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.30914 | val 0.58322
  Epoch 020 - train 0.30222 | val 0.62081
  Regression -> MSE: 0.000164, MAE: 0.009107, R²: -0.0775
  Directional -> Accuracy: 0.5156, MCC: 0.1933, F1: 0.3404

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.35911 | val 0.71389
  Epoch 020 - train 0.34324 | val 0.72118
  Regression -> MSE: 0.000505, MAE: 0.018247, R²: -1.2199
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.35843 | val 0.57833
  Epoch 016 - train 0.34920 | val 0.58001
  Regression -> MSE: 0.000145, MAE: 0.008382, R²: -0.0075
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.32271 | val 0.50610
  Epoch 016 - train 0.33904 | val 0.50359
  Regression -> MSE: 0.000169, MAE: 0.010277, R²: -0.0207
  Directional -> Accuracy: 0.5077, MCC: 0.0000, F1: 0.6735

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.37556 | val 0.51389
  Epoch 020 - train 0.35931 | val 0.59789
  Regression -> MSE: 0.000088, MAE: 0.007255, R²: -0.0162
  Directional -> Accuracy: 0.5614, MCC: 0.1400, F1: 0.5614

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.35999 | val 0.57005
  Epoch 016 - train 0.34543 | val 0.61987
  Regression -> MSE: 0.000213, MAE: 0.010988, R²: -0.0082
  Directional -> Accuracy: 0.5231, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.31466 | val 0.35668
  Epoch 020 - train 0.29408 | val 0.30978
  Regression -> MSE: 0.000096, MAE: 0.007968, R²: -0.0726
  Directional -> Accuracy: 0.4909, MCC: 0.0305, F1: 0.3636

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.38015 | val 0.34221
  Epoch 016 - train 0.36679 | val 0.34228
  Regression -> MSE: 0.000114, MAE: 0.009096, R²: -0.1441
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.37787 | val 0.38402
  Epoch 020 - train 0.35990 | val 0.38976
  Regression -> MSE: 0.000242, MAE: 0.012992, R²: -0.0232
  Directional -> Accuracy: 0.5476, MCC: 0.0574, F1: 0.6275

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.36114 | val 0.51157
  Epoch 020 - train 0.35693 | val 0.51677
  Regression -> MSE: 0.000180, MAE: 0.007905, R²: -0.0598
  Directional -> Accuracy: 0.5536, MCC: 0.1446, F1: 0.5098

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.38095 | val 0.30832
  Epoch 016 - train 0.36755 | val 0.31077
  Regression -> MSE: 0.000242, MAE: 0.012082, R²: 0.0003
  Directional -> Accuracy: 0.5500, MCC: 0.0000, F1: 0.7097

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.37017 | val 0.78282
  Epoch 016 - train 0.37256 | val 0.79029
  Regression -> MSE: 0.000236, MAE: 0.010040, R²: -0.0004
  Directional -> Accuracy: 0.5238, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.34976 | val 0.49622
  Epoch 016 - train 0.33386 | val 0.50985
  Regression -> MSE: 0.000139, MAE: 0.008385, R²: -0.0097
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.7077

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.33444 | val 0.58111
  Epoch 016 - train 0.34618 | val 0.57949
  Regression -> MSE: 0.000186, MAE: 0.010168, R²: -0.0163
  Directional -> Accuracy: 0.4694, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.31231 | val 0.50805
  Epoch 020 - train 0.28705 | val 0.50748
  Regression -> MSE: 0.000273, MAE: 0.010845, R²: -0.0275
  Directional -> Accuracy: 0.5694, MCC: 0.1429, F1: 0.5867

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.31616 | val 0.45258
  Epoch 016 - train 0.30659 | val 0.49528
  Regression -> MSE: 0.000186, MAE: 0.010490, R²: -0.0126
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.32607 | val 0.37842
  Epoch 020 - train 0.31928 | val 0.40827
  Regression -> MSE: 0.000361, MAE: 0.013294, R²: -0.0387
  Directional -> Accuracy: 0.4242, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.36771 | val 0.23905
  Epoch 016 - train 0.35718 | val 0.24338
  Regression -> MSE: 0.000127, MAE: 0.008525, R²: -0.1980
  Directional -> Accuracy: 0.4762, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.36161 | val 0.65274
  Epoch 016 - train 0.33703 | val 0.69368
  Regression -> MSE: 0.000226, MAE: 0.011489, R²: -0.0287
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.6341

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.34702 | val 0.88456
  Epoch 016 - train 0.33458 | val 0.89795
  Regression -> MSE: 0.000081, MAE: 0.007020, R²: -0.0923
  Directional -> Accuracy: 0.3913, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.33723 | val 0.25607
  Epoch 020 - train 0.30909 | val 0.23842
  Regression -> MSE: 0.000389, MAE: 0.016936, R²: -0.2493
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.32743 | val 0.55046
  Epoch 020 - train 0.31079 | val 1.00591
  Regression -> MSE: 0.000078, MAE: 0.006955, R²: -0.0049
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.36909 | val 0.55691
  Epoch 020 - train 0.35225 | val 0.55261
  Regression -> MSE: 0.000301, MAE: 0.014377, R²: -0.0019
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.35865 | val 0.52754
  Epoch 020 - train 0.33258 | val 0.50620
  Regression -> MSE: 0.000104, MAE: 0.007126, R²: -0.0262
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.37605 | val 0.58946
  Epoch 016 - train 0.38394 | val 0.58925
  Regression -> MSE: 0.000176, MAE: 0.009991, R²: -0.0022
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.33307 | val 0.47789
  Epoch 016 - train 0.33807 | val 0.52023
  Regression -> MSE: 0.000226, MAE: 0.011786, R²: -0.0038
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.34132 | val 0.52090
  Epoch 016 - train 0.32833 | val 0.73701
  Regression -> MSE: 0.000094, MAE: 0.007758, R²: -0.0037
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.35614 | val 0.73829
  Epoch 019 - train 0.35795 | val 0.74995
  Regression -> MSE: 0.000167, MAE: 0.010389, R²: -0.0001
  Directional -> Accuracy: 0.5094, MCC: 0.0000, F1: 0.6750

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.34553 | val 0.54333
  Epoch 016 - train 0.33087 | val 0.57388
  Regression -> MSE: 0.000128, MAE: 0.009187, R²: -0.0857
  Directional -> Accuracy: 0.4727, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.37495 | val 0.70817

[I 2026-02-22 21:15:54,878] Trial 24 finished with value: -0.011739897653999423 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 64, 'learning_rate': 0.0004186323629064937, 'weight_decay': 1.4414466877164678e-05, 'lr_patience': 7, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 1.0124458151509246, 'early_stopping_min_delta': 0.004820523696860524}. Best is trial 3 with value: -0.011473394984568777.

  Epoch 016 - train 0.36911 | val 0.71875
  Regression -> MSE: 0.000240, MAE: 0.012476, R²: -0.0002
  Directional -> Accuracy: 0.4833, MCC: 0.0000, F1: 0.6517

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 36
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.33535 | val 0.83353
  Epoch 013 - train 0.32872 | val 1.01246
  Regression -> MSE: 0.000253, MAE: 0.012615, R²: -0.0739
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.6168

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 112). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.33703 | val 0.47776
  Epoch 017 - train 0.32244 | val 0.61497
  Regression -> MSE: 0.000707, MAE: 0.019561, R²: 0.0085
  Directional -> Accuracy: 0.6047, MCC: 0.0000, F1: 0.7536

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for AEP (109 < 112). Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 112). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.34284 | val 0.89301
  Epoch 011 - train 0.33558 | val 0.88766
  Regression -> MSE: 0.000319, MAE: 0.014525, R²: -0.0020
  Directional -> Accuracy: 0.5455, MCC: 0.1596, F1: 0.6970

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.30382 | val 0.42228
  Epoch 011 - train 0.30051 | val 0.46020
  Regression -> MSE: 0.000370, MAE: 0.014842, R²: -0.0361
  Directional -> Accuracy: 0.4583, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.34071 | val 0.42243
  Epoch 018 - train 0.31186 | val 0.43815
  Regression -> MSE: 0.000194, MAE: 0.009279, R²: 0.0786
  Directional -> Accuracy: 0.7708, MCC: 0.5421, F1: 0.7755

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.29770 | val 0.89338
  Epoch 011 - train 0.29250 | val 0.93312
  Regression -> MSE: 0.000575, MAE: 0.018286, R²: -0.0269
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.35413 | val 0.66810
  Epoch 015 - train 0.34048 | val 0.84056
  Regression -> MSE: 0.000256, MAE: 0.012328, R²: -0.0021
  Directional -> Accuracy: 0.5152, MCC: 0.0196, F1: 0.4483

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 112). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 112). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.27984 | val 0.62338
  Epoch 011 - train 0.25232 | val 0.66954
  Regression -> MSE: 0.000612, MAE: 0.019460, R²: -0.0561
  Directional -> Accuracy: 0.4359, MCC: 0.0000, F1: 0.6071

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.30617 | val 0.65431
  Epoch 011 - train 0.30752 | val 0.66595
  Regression -> MSE: 0.000382, MAE: 0.015951, R²: -0.0005
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 112). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 112). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 112). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.35513 | val 0.68664
  Epoch 011 - train 0.34172 | val 0.74223
  Regression -> MSE: 0.000248, MAE: 0.011832, R²: -0.0064
  Directional -> Accuracy: 0.5821, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.30676 | val 0.83338
  Epoch 011 - train 0.30407 | val 0.83238
  Regression -> MSE: 0.000313, MAE: 0.013570, R²: -0.0011
  Directional -> Accuracy: 0.4468, MCC: 0.0000, F1: 0.6176

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.38272 | val 0.54272
  Epoch 011 - train 0.37429 | val 0.55477
  Regression -> MSE: 0.000692, MAE: 0.019595, R²: 0.0043
  Directional -> Accuracy: 0.5818, MCC: 0.1848, F1: 0.7013

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 112). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.34122 | val 0.51656
  Epoch 011 - train 0.32489 | val 0.50198
  Regression -> MSE: 0.000145, MAE: 0.009505, R²: -0.0011
  Directional -> Accuracy: 0.4792, MCC: 0.0000, F1: 0.6479

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 112). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.30751 | val 0.65918
  Epoch 015 - train 0.27333 | val 0.76325
  Regression -> MSE: 0.000224, MAE: 0.010548, R²: 0.0255
  Directional -> Accuracy: 0.5000, MCC: -0.0228, F1: 0.6133

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.33419 | val 1.17931
  Epoch 011 - train 0.32865 | val 1.17596
  Regression -> MSE: 0.000376, MAE: 0.016156, R²: -0.0060
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.35573 | val 0.56825
  Epoch 020 - train 0.33409 | val 0.60798
  Regression -> MSE: 0.000118, MAE: 0.008537, R²: -0.0813
  Directional -> Accuracy: 0.5672, MCC: 0.1521, F1: 0.5397

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 112). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.34184 | val 1.14917
  Epoch 011 - train 0.34513 | val 1.19849
  Regression -> MSE: 0.000149, MAE: 0.009493, R²: 0.0128
  Directional -> Accuracy: 0.6071, MCC: 0.0000, F1: 0.7556

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.36660 | val 0.46710
  Epoch 011 - train 0.36157 | val 0.47009
  Regression -> MSE: 0.000279, MAE: 0.013196, R²: -0.0062
  Directional -> Accuracy: 0.5890, MCC: 0.0000, F1: 0.7414

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.29947 | val 0.62686
  Epoch 020 - train 0.26708 | val 0.65710
  Regression -> MSE: 0.000287, MAE: 0.013348, R²: -0.8632
  Directional -> Accuracy: 0.4194, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 112). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.36221 | val 0.91490
  Epoch 013 - train 0.34447 | val 0.89393
  Regression -> MSE: 0.000247, MAE: 0.011166, R²: -0.0870
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.33502 | val 0.63534
  Epoch 018 - train 0.29507 | val 0.67772
  Regression -> MSE: 0.000155, MAE: 0.008612, R²: -0.0448
  Directional -> Accuracy: 0.4667, MCC: 0.0680, F1: 0.3333

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 112). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 112). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 112). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.33970 | val 0.55073
  Epoch 011 - train 0.34156 | val 0.55006
  Regression -> MSE: 0.000170, MAE: 0.010551, R²: 0.0053
  Directional -> Accuracy: 0.4921, MCC: 0.0000, F1: 0.6596

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.35682 | val 0.62926
  Epoch 011 - train 0.34826 | val 0.66029
  Regression -> MSE: 0.000092, MAE: 0.007396, R²: -0.0344
  Directional -> Accuracy: 0.5273, MCC: 0.1801, F1: 0.4091

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.33855 | val 0.61248
  Epoch 011 - train 0.33234 | val 0.64476
  Regression -> MSE: 0.000216, MAE: 0.011218, R²: 0.0014
  Directional -> Accuracy: 0.4762, MCC: 0.0000, F1: 0.6452

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.27525 | val 0.36132
  Epoch 020 - train 0.25498 | val 0.36649
  Regression -> MSE: 0.000105, MAE: 0.008240, R²: -0.1700
  Directional -> Accuracy: 0.4340, MCC: -0.0952, F1: 0.2500

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.35098 | val 0.47227
  Epoch 020 - train 0.30344 | val 0.46773
  Regression -> MSE: 0.000096, MAE: 0.008305, R²: -0.0513
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.34495 | val 0.32458
  Epoch 011 - train 0.34833 | val 0.32514
  Regression -> MSE: 0.000292, MAE: 0.013450, R²: -0.0510
  Directional -> Accuracy: 0.4167, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.33833 | val 0.56679
  Epoch 020 - train 0.30206 | val 0.59868
  Regression -> MSE: 0.000299, MAE: 0.012200, R²: -0.7394
  Directional -> Accuracy: 0.5000, MCC: 0.1821, F1: 0.1290

[49/88] Processing MDT...

Processing MDT (Healthcare)...
Insufficient data for proper time series validation for MDT. Skipping...

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.31992 | val 0.95210
  Epoch 011 - train 0.33843 | val 0.96150
  Regression -> MSE: 0.000240, MAE: 0.010112, R²: -0.0030
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.33988 | val 0.52366
  Epoch 011 - train 0.32869 | val 0.53924
  Regression -> MSE: 0.000144, MAE: 0.008497, R²: -0.0129
  Directional -> Accuracy: 0.5500, MCC: 0.0000, F1: 0.7097

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.34212 | val 0.62459
  Epoch 020 - train 0.29618 | val 0.65211
  Regression -> MSE: 0.000186, MAE: 0.010513, R²: 0.0242
  Directional -> Accuracy: 0.4681, MCC: -0.1036, F1: 0.6032

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.28611 | val 0.58844
  Epoch 016 - train 0.26193 | val 0.61325
  Regression -> MSE: 0.000295, MAE: 0.011380, R²: -0.1100
  Directional -> Accuracy: 0.4429, MCC: -0.0197, F1: 0.0488

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 112). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.27882 | val 0.42052
  Epoch 011 - train 0.28187 | val 0.41778
  Regression -> MSE: 0.000213, MAE: 0.011180, R²: -0.0223
  Directional -> Accuracy: 0.4694, MCC: 0.0000, F1: 0.6389

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 112). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.32233 | val 0.41220
  Epoch 015 - train 0.29108 | val 0.44980
  Regression -> MSE: 0.000368, MAE: 0.013126, R²: -0.0299
  Directional -> Accuracy: 0.4375, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.30448 | val 0.27801
  Epoch 011 - train 0.29698 | val 0.28021
  Regression -> MSE: 0.000101, MAE: 0.007796, R²: -0.0408
  Directional -> Accuracy: 0.4898, MCC: 0.0000, F1: 0.6575

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.34200 | val 0.79071
  Epoch 011 - train 0.33410 | val 0.81634
  Regression -> MSE: 0.000222, MAE: 0.011411, R²: -0.0222
  Directional -> Accuracy: 0.4630, MCC: 0.0000, F1: 0.6329

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.30458 | val 1.08020
  Epoch 011 - train 0.30031 | val 1.10416
  Regression -> MSE: 0.000076, MAE: 0.006724, R²: -0.0624
  Directional -> Accuracy: 0.6136, MCC: 0.0000, F1: 0.7606

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 112). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for PPL (108 < 112). Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 112). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 112). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 112). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.33593 | val 0.26554
  Epoch 020 - train 0.29032 | val 0.25338
  Regression -> MSE: 0.000330, MAE: 0.015023, R²: -0.1051
  Directional -> Accuracy: 0.3778, MCC: 0.0000, F1: 0.4815

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 112). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 112). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 112). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.31172 | val 0.74100
  Epoch 011 - train 0.31653 | val 0.74679
  Regression -> MSE: 0.000078, MAE: 0.006932, R²: 0.0029
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 112). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 112). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 112). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 112). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.32950 | val 0.67163
  Epoch 020 - train 0.26913 | val 0.69746
  Regression -> MSE: 0.000285, MAE: 0.013979, R²: -0.0082
  Directional -> Accuracy: 0.4884, MCC: -0.0528, F1: 0.6207

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.32990 | val 0.37871
  Epoch 011 - train 0.31449 | val 0.38038
  Regression -> MSE: 0.000110, MAE: 0.007621, R²: -0.0073
  Directional -> Accuracy: 0.5897, MCC: 0.0000, F1: 0.7419

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.36555 | val 0.68449
  Epoch 011 - train 0.36070 | val 0.68731
  Regression -> MSE: 0.000191, MAE: 0.010789, R²: -0.0473
  Directional -> Accuracy: 0.3778, MCC: 0.0000, F1: 0.5484

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.32243 | val 0.51860
  Epoch 011 - train 0.31731 | val 0.52503
  Regression -> MSE: 0.000237, MAE: 0.011980, R²: -0.0242
  Directional -> Accuracy: 0.4528, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.31431 | val 0.94712
  Epoch 011 - train 0.31502 | val 0.98083
  Regression -> MSE: 0.000088, MAE: 0.007520, R²: -0.0050
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.35464 | val 0.94285
  Epoch 013 - train 0.34125 | val 1.14440
  Regression -> MSE: 0.000169, MAE: 0.010453, R²: 0.0046
  Directional -> Accuracy: 0.4902, MCC: 0.0000, F1: 0.6579

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.32183 | val 0.67175
  Epoch 011 - train 0.31654 | val 0.64903
  Regression -> MSE: 0.000121, MAE: 0.009091, R²: -0.0212
  Directional -> Accuracy: 0.4717, MCC: -0.0537, F1: 0.3333

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...

[I 2026-02-22 21:16:51,974] Trial 25 finished with value: -0.011714188343808852 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 36, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.0, 'dropout': 0.1, 'batch_size': 64, 'learning_rate': 0.0025588919221751975, 'weight_decay': 5.220279094763737e-06, 'lr_patience': 7, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 1.1586634877862128, 'early_stopping_min_delta': 0.008463001274864126}. Best is trial 3 with value: -0.011473394984568777.

  Epoch 010 - train 0.34634 | val 0.93761
  Epoch 011 - train 0.34009 | val 1.21419
  Regression -> MSE: 0.000248, MAE: 0.012680, R²: -0.0018
  Directional -> Accuracy: 0.4655, MCC: 0.0000, F1: 0.6353

================================================================================
Pipeline completed: 47/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (47, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.41993 | val 0.71933
  Epoch 020 - train 0.41515 | val 0.72175
  Regression -> MSE: 0.000268, MAE: 0.013221, R²: -0.0820
  Directional -> Accuracy: 0.3766, MCC: -0.2358, F1: 0.4000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.43431 | val 0.81165
  Epoch 016 - train 0.42516 | val 0.76389
  Regression -> MSE: 0.000694, MAE: 0.019448, R²: -0.0139
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.45986 | val 0.95053
  Epoch 016 - train 0.46268 | val 0.96403
  Regression -> MSE: 0.000311, MAE: 0.014377, R²: -0.0015
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.33955 | val 0.71641
  Epoch 016 - train 0.33071 | val 0.81939
  Regression -> MSE: 0.000355, MAE: 0.014674, R²: -0.0160
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.42075 | val 0.61397
  Epoch 016 - train 0.41538 | val 0.67214
  Regression -> MSE: 0.000206, MAE: 0.010163, R²: -0.0102
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.40593 | val 1.10357
  Epoch 016 - train 0.41562 | val 1.12895
  Regression -> MSE: 0.000556, MAE: 0.018121, R²: -0.0022
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.46046 | val 0.66327
  Epoch 016 - train 0.45308 | val 0.64928
  Regression -> MSE: 0.000251, MAE: 0.011994, R²: -0.0210
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.49762 | val 0.57416
  Epoch 020 - train 0.44763 | val 0.56048
  Regression -> MSE: 0.000603, MAE: 0.019188, R²: -0.0088
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.44780 | val 0.64995
  Epoch 016 - train 0.42053 | val 0.67820
  Regression -> MSE: 0.000383, MAE: 0.016167, R²: 0.0022
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.43802 | val 0.71475
  Epoch 016 - train 0.43717 | val 0.76552
  Regression -> MSE: 0.000242, MAE: 0.011922, R²: -0.0024
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.41020 | val 0.71867
  Epoch 020 - train 0.41145 | val 0.74883
  Regression -> MSE: 0.000305, MAE: 0.013477, R²: 0.0200
  Directional -> Accuracy: 0.5800, MCC: 0.1716, F1: 0.2222

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.44908 | val 0.70182
  Epoch 016 - train 0.43874 | val 0.76104
  Regression -> MSE: 0.000682, MAE: 0.019561, R²: -0.0067
  Directional -> Accuracy: 0.3793, MCC: -0.2651, F1: 0.2174

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.44422 | val 0.91434
  Epoch 016 - train 0.42519 | val 1.00625
  Regression -> MSE: 0.000145, MAE: 0.009070, R²: -0.0484
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.39598 | val 0.77247
  Epoch 016 - train 0.38893 | val 0.75132
  Regression -> MSE: 0.000227, MAE: 0.010892, R²: -0.0096
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.46138 | val 1.45616
  Epoch 016 - train 0.43995 | val 1.42585
  Regression -> MSE: 0.000369, MAE: 0.015960, R²: -0.0198
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.45405 | val 0.48066
  Epoch 020 - train 0.42831 | val 0.48567
  Regression -> MSE: 0.000111, MAE: 0.008140, R²: -0.0335
  Directional -> Accuracy: 0.5143, MCC: -0.0215, F1: 0.6304

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.42467 | val 1.19368
  Epoch 016 - train 0.41256 | val 1.13934
  Regression -> MSE: 0.000158, MAE: 0.009624, R²: -0.0155
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.44202 | val 0.56459
  Epoch 016 - train 0.43044 | val 0.60405
  Regression -> MSE: 0.000277, MAE: 0.013311, R²: -0.0172
  Directional -> Accuracy: 0.4605, MCC: -0.0192, F1: 0.4384

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.36472 | val 0.69817
  Epoch 020 - train 0.35257 | val 0.67809
  Regression -> MSE: 0.000206, MAE: 0.010586, R²: -0.3788
  Directional -> Accuracy: 0.4769, MCC: 0.0091, F1: 0.4333

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.42621 | val 1.15675
  Epoch 017 - train 0.41944 | val 1.15482
  Regression -> MSE: 0.000262, MAE: 0.011547, R²: -0.1573
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.43511 | val 0.66026
  Epoch 020 - train 0.42829 | val 0.68560
  Regression -> MSE: 0.000154, MAE: 0.009044, R²: -0.0732
  Directional -> Accuracy: 0.5000, MCC: 0.1491, F1: 0.4286

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.40528 | val 0.54054
  Epoch 019 - train 0.41042 | val 0.57238
  Regression -> MSE: 0.000169, MAE: 0.010266, R²: -0.0238
  Directional -> Accuracy: 0.4848, MCC: -0.0325, F1: 0.5641

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.46313 | val 0.61697
  Epoch 016 - train 0.44165 | val 0.61996
  Regression -> MSE: 0.000086, MAE: 0.007087, R²: -0.0075
  Directional -> Accuracy: 0.5862, MCC: 0.1522, F1: 0.7333

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.44073 | val 0.88106
  Epoch 016 - train 0.43279 | val 0.82397
  Regression -> MSE: 0.000212, MAE: 0.011099, R²: -0.0022
  Directional -> Accuracy: 0.4242, MCC: -0.1446, F1: 0.5476

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.38939 | val 0.32992
  Epoch 020 - train 0.37602 | val 0.33119
  Regression -> MSE: 0.000110, MAE: 0.008287, R²: -0.1932
  Directional -> Accuracy: 0.5536, MCC: 0.2064, F1: 0.4186

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.44950 | val 0.33374
  Epoch 020 - train 0.44691 | val 0.33821
  Regression -> MSE: 0.000104, MAE: 0.008681, R²: -0.0070
  Directional -> Accuracy: 0.5870, MCC: 0.1754, F1: 0.5581

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.46365 | val 0.45606
  Epoch 016 - train 0.45484 | val 0.45517
  Regression -> MSE: 0.000233, MAE: 0.012592, R²: -0.0049
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.43956 | val 0.62140
  Epoch 016 - train 0.42616 | val 0.61550
  Regression -> MSE: 0.000174, MAE: 0.007858, R²: -0.0426
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.46756 | val 0.32175
  Epoch 016 - train 0.45062 | val 0.34104
  Regression -> MSE: 0.000238, MAE: 0.011902, R²: -0.0041
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.44408 | val 0.94658
  Epoch 020 - train 0.42180 | val 0.95914
  Regression -> MSE: 0.000238, MAE: 0.010010, R²: -0.0321
  Directional -> Accuracy: 0.4884, MCC: -0.0179, F1: 0.5417

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.47562 | val 0.64032
  Epoch 016 - train 0.45053 | val 0.65123
  Regression -> MSE: 0.000136, MAE: 0.008244, R²: -0.0078
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.43605 | val 0.66489
  Epoch 016 - train 0.43145 | val 0.68348
  Regression -> MSE: 0.000198, MAE: 0.010649, R²: -0.0524
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.36604 | val 0.60332
  Epoch 020 - train 0.36342 | val 0.58882
  Regression -> MSE: 0.000298, MAE: 0.011385, R²: -0.1375
  Directional -> Accuracy: 0.5205, MCC: 0.1094, F1: 0.4262

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.44739 | val 0.37147
  Epoch 016 - train 0.43832 | val 0.37427
  Regression -> MSE: 0.000170, MAE: 0.010400, R²: -0.0210
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.5778

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.41689 | val 0.62997
  Epoch 016 - train 0.40439 | val 0.65594
  Regression -> MSE: 0.000187, MAE: 0.010585, R²: -0.0385
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.43903 | val 0.40015
  Epoch 020 - train 0.40761 | val 0.39814
  Regression -> MSE: 0.000338, MAE: 0.012237, R²: 0.0136
  Directional -> Accuracy: 0.5522, MCC: 0.0367, F1: 0.6667

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.46857 | val 0.24272
  Epoch 020 - train 0.44140 | val 0.22705
  Regression -> MSE: 0.000132, MAE: 0.008645, R²: -0.2551
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.45247 | val 0.78330
  Epoch 016 - train 0.45050 | val 0.77389
  Regression -> MSE: 0.000219, MAE: 0.011309, R²: -0.0014
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.44369 | val 1.07491
  Epoch 016 - train 0.43457 | val 1.07676
  Regression -> MSE: 0.000091, MAE: 0.007441, R²: -0.1653
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.43219 | val 0.35665
  Epoch 016 - train 0.41947 | val 0.35510
  Regression -> MSE: 0.000327, MAE: 0.014872, R²: -0.0643
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.47472 | val 0.20902
  Epoch 016 - train 0.48836 | val 0.22787
  Regression -> MSE: 0.000247, MAE: 0.011520, R²: -0.0118
  Directional -> Accuracy: 0.5526, MCC: 0.0930, F1: 0.6667

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.38064 | val 0.64412
  Epoch 016 - train 0.38981 | val 0.67237
  Regression -> MSE: 0.000082, MAE: 0.007030, R²: -0.0177
  Directional -> Accuracy: 0.5067, MCC: 0.0032, F1: 0.0976

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.46005 | val 0.64824
  Epoch 016 - train 0.43515 | val 0.78780
  Regression -> MSE: 0.000315, MAE: 0.014552, R²: -0.0259
  Directional -> Accuracy: 0.4894, MCC: 0.0000, F1: 0.0000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.43425 | val 0.52107
  Epoch 020 - train 0.41310 | val 0.52882
  Regression -> MSE: 0.000099, MAE: 0.006997, R²: -0.0040
  Directional -> Accuracy: 0.5909, MCC: 0.1283, F1: 0.7273

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.47903 | val 0.72342
  Epoch 016 - train 0.46704 | val 0.76580
  Regression -> MSE: 0.000173, MAE: 0.009794, R²: -0.0044
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.40348 | val 0.59108
  Epoch 016 - train 0.40426 | val 0.62192
  Regression -> MSE: 0.000223, MAE: 0.011767, R²: -0.0009
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.43234 | val 0.66504
  Epoch 016 - train 0.42177 | val 0.73178
  Regression -> MSE: 0.000092, MAE: 0.007617, R²: 0.0052
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.45812 | val 0.89643
  Epoch 020 - train 0.45128 | val 0.91586
  Regression -> MSE: 0.000165, MAE: 0.010003, R²: -0.0066
  Directional -> Accuracy: 0.6111, MCC: 0.2202, F1: 0.6316

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.42205 | val 0.76636
  Epoch 016 - train 0.42136 | val 0.79597
  Regression -> MSE: 0.000122, MAE: 0.009004, R²: -0.0493
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.45210 | val 0.80343

[I 2026-02-22 21:18:58,238] Trial 26 finished with value: -0.011506684714028168 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.1, 'dropout': 0.0, 'batch_size': 32, 'learning_rate': 1.4655625936762082e-05, 'weight_decay': 1.5937872021084465e-06, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 1.452744297743753, 'early_stopping_min_delta': 0.006269402454434223}. Best is trial 3 with value: -0.011473394984568777.

  Epoch 020 - train 0.43431 | val 0.81757
  Regression -> MSE: 0.000270, MAE: 0.013010, R²: -0.1399
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.43593 | val 0.75709
  Epoch 020 - train 0.42921 | val 0.75159
  Regression -> MSE: 0.000264, MAE: 0.013097, R²: -0.0667
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.43538 | val 0.42611
  Epoch 016 - train 0.42868 | val 0.43574
  Regression -> MSE: 0.000730, MAE: 0.020106, R²: -0.0665
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.45005 | val 0.92526
  Epoch 020 - train 0.45448 | val 0.92144
  Regression -> MSE: 0.000312, MAE: 0.014241, R²: -0.0064
  Directional -> Accuracy: 0.5319, MCC: 0.0600, F1: 0.5600

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.34286 | val 1.35811
  Epoch 016 - train 0.34918 | val 1.51041
  Regression -> MSE: 0.000380, MAE: 0.015089, R²: -0.0867
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.42308 | val 0.40904
  Epoch 020 - train 0.42287 | val 0.43682
  Regression -> MSE: 0.000192, MAE: 0.009444, R²: 0.0592
  Directional -> Accuracy: 0.7255, MCC: 0.4530, F1: 0.7308

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.43302 | val 1.11042
  Epoch 019 - train 0.41326 | val 1.14108
  Regression -> MSE: 0.000561, MAE: 0.018188, R²: -0.0099
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.44804 | val 0.61558
  Epoch 020 - train 0.43279 | val 0.62435
  Regression -> MSE: 0.000246, MAE: 0.011886, R²: -0.0004
  Directional -> Accuracy: 0.5652, MCC: 0.0575, F1: 0.3750

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.44589 | val 0.80345
  Epoch 016 - train 0.43793 | val 0.86481
  Regression -> MSE: 0.000657, MAE: 0.020392, R²: -0.1003
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.44458 | val 0.75395
  Epoch 016 - train 0.44209 | val 0.88595
  Regression -> MSE: 0.000386, MAE: 0.016005, R²: -0.0066
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.44897 | val 0.74538
  Epoch 016 - train 0.44355 | val 0.80380
  Regression -> MSE: 0.000250, MAE: 0.011695, R²: -0.0351
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.41239 | val 0.72810
  Epoch 016 - train 0.39760 | val 0.79062
  Regression -> MSE: 0.000330, MAE: 0.013647, R²: -0.0607
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.49025 | val 0.85440
  Epoch 016 - train 0.47765 | val 0.85922
  Regression -> MSE: 0.000673, MAE: 0.019438, R²: 0.0064
  Directional -> Accuracy: 0.5345, MCC: 0.0711, F1: 0.5846

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.45204 | val 0.51372
  Epoch 016 - train 0.44239 | val 0.55565
  Regression -> MSE: 0.000139, MAE: 0.009070, R²: -0.0056
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.41023 | val 0.66479
  Epoch 020 - train 0.38984 | val 0.65030
  Regression -> MSE: 0.000229, MAE: 0.010797, R²: -0.0164
  Directional -> Accuracy: 0.5410, MCC: 0.2237, F1: 0.1765

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.48262 | val 1.58549
  Epoch 016 - train 0.45925 | val 1.69927
  Regression -> MSE: 0.000366, MAE: 0.016336, R²: -0.0099
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.46019 | val 0.55599
  Epoch 016 - train 0.44249 | val 0.57385
  Regression -> MSE: 0.000107, MAE: 0.007959, R²: 0.0061
  Directional -> Accuracy: 0.5571, MCC: 0.0940, F1: 0.6265

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.41686 | val 1.12207
  Epoch 016 - train 0.39302 | val 1.17128
  Regression -> MSE: 0.000157, MAE: 0.009820, R²: -0.0090
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.48114 | val 0.53185
  Epoch 016 - train 0.46901 | val 0.56779
  Regression -> MSE: 0.000273, MAE: 0.012951, R²: -0.0032
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.36286 | val 0.67493
  Epoch 020 - train 0.35107 | val 0.67385
  Regression -> MSE: 0.000189, MAE: 0.010090, R²: -0.2653
  Directional -> Accuracy: 0.4923, MCC: 0.1307, F1: 0.3265

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.44591 | val 0.94379
  Epoch 016 - train 0.42306 | val 0.93126
  Regression -> MSE: 0.000251, MAE: 0.011299, R²: -0.1104
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.47213 | val 0.70349
  Epoch 020 - train 0.42309 | val 0.75099
  Regression -> MSE: 0.000149, MAE: 0.008583, R²: -0.0397
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.40792 | val 0.63428
  Epoch 016 - train 0.42006 | val 0.63853
  Regression -> MSE: 0.000165, MAE: 0.010356, R²: -0.0002
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.52215 | val 0.83599
  Epoch 016 - train 0.50939 | val 0.81284
  Regression -> MSE: 0.000084, MAE: 0.007012, R²: 0.0109
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.44732 | val 0.64512
  Epoch 016 - train 0.43453 | val 0.64398
  Regression -> MSE: 0.000213, MAE: 0.011092, R²: -0.0061
  Directional -> Accuracy: 0.4848, MCC: -0.0304, F1: 0.4688

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.38779 | val 0.31728
  Epoch 020 - train 0.37593 | val 0.31382
  Regression -> MSE: 0.000122, MAE: 0.008664, R²: -0.3222
  Directional -> Accuracy: 0.5536, MCC: 0.2064, F1: 0.4186

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.46490 | val 0.31867
  Epoch 020 - train 0.45939 | val 0.31503
  Regression -> MSE: 0.000104, MAE: 0.008695, R²: -0.0090
  Directional -> Accuracy: 0.5435, MCC: 0.0553, F1: 0.4324

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.45119 | val 0.46918
  Epoch 016 - train 0.45163 | val 0.49111
  Regression -> MSE: 0.000243, MAE: 0.012931, R²: -0.0505
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.43576 | val 0.58624
  Epoch 016 - train 0.42759 | val 0.58672
  Regression -> MSE: 0.000182, MAE: 0.007995, R²: -0.0913
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.47736 | val 0.34743
  Epoch 016 - train 0.48206 | val 0.37949
  Regression -> MSE: 0.000239, MAE: 0.011929, R²: -0.0087
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.44331 | val 0.95886
  Epoch 016 - train 0.43259 | val 1.00198
  Regression -> MSE: 0.000230, MAE: 0.009880, R²: 0.0006
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.47154 | val 0.66103
  Epoch 016 - train 0.44061 | val 0.67076
  Regression -> MSE: 0.000136, MAE: 0.008298, R²: -0.0076
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.43685 | val 0.69231
  Epoch 016 - train 0.42082 | val 0.69481
  Regression -> MSE: 0.000188, MAE: 0.010377, R²: -0.0004
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.38888 | val 0.64524
  Epoch 016 - train 0.38427 | val 0.62880
  Regression -> MSE: 0.000263, MAE: 0.010629, R²: -0.0049
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.46021 | val 0.37662
  Epoch 020 - train 0.44339 | val 0.37399
  Regression -> MSE: 0.000161, MAE: 0.010246, R²: 0.0312
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.40434 | val 0.76076
  Epoch 016 - train 0.40086 | val 0.76400
  Regression -> MSE: 0.000194, MAE: 0.010904, R²: -0.0771
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.42835 | val 0.58895
  Epoch 016 - train 0.42350 | val 0.58192
  Regression -> MSE: 0.000375, MAE: 0.013523, R²: -0.0933
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.48552 | val 0.25463
  Epoch 016 - train 0.47853 | val 0.31038
  Regression -> MSE: 0.000108, MAE: 0.008362, R²: -0.0230
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.44804 | val 0.77834
  Epoch 020 - train 0.43002 | val 0.81977
  Regression -> MSE: 0.000227, MAE: 0.011463, R²: -0.0365
  Directional -> Accuracy: 0.4912, MCC: -0.1231, F1: 0.0645

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.45382 | val 1.06643
  Epoch 020 - train 0.42651 | val 1.09265
  Regression -> MSE: 0.000082, MAE: 0.007057, R²: -0.0510
  Directional -> Accuracy: 0.5319, MCC: -0.0346, F1: 0.6452

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.44963 | val 0.35573
  Epoch 016 - train 0.43852 | val 0.38346
  Regression -> MSE: 0.000329, MAE: 0.014940, R²: -0.0707
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.45488 | val 0.20940
  Epoch 020 - train 0.44035 | val 0.22661
  Regression -> MSE: 0.000258, MAE: 0.011491, R²: -0.0594
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.38991 | val 0.58465
  Epoch 020 - train 0.38501 | val 0.60080
  Regression -> MSE: 0.000079, MAE: 0.006915, R²: 0.0253
  Directional -> Accuracy: 0.5200, MCC: 0.0424, F1: 0.5500

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.45545 | val 0.60429
  Epoch 020 - train 0.44702 | val 0.73030
  Regression -> MSE: 0.000316, MAE: 0.014594, R²: -0.0304
  Directional -> Accuracy: 0.5106, MCC: 0.0283, F1: 0.4390

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.41478 | val 0.52921
  Epoch 016 - train 0.40927 | val 0.53522
  Regression -> MSE: 0.000098, MAE: 0.007271, R²: 0.0026
  Directional -> Accuracy: 0.4773, MCC: -0.0212, F1: 0.4651

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.47125 | val 0.72803
  Epoch 016 - train 0.46587 | val 0.75190
  Regression -> MSE: 0.000173, MAE: 0.010014, R²: -0.0076
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.40434 | val 0.66176
  Epoch 016 - train 0.39742 | val 0.71727
  Regression -> MSE: 0.000222, MAE: 0.011635, R²: 0.0052
  Directional -> Accuracy: 0.5893, MCC: 0.2108, F1: 0.7160

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.44834 | val 0.55934
  Epoch 016 - train 0.42577 | val 0.56174
  Regression -> MSE: 0.000093, MAE: 0.007648, R²: -0.0068
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.45716 | val 0.91162
  Epoch 020 - train 0.44413 | val 0.91481
  Regression -> MSE: 0.000168, MAE: 0.010412, R²: -0.0237
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.42477 | val 0.71396
  Epoch 016 - train 0.41545 | val 0.73753
  Regression -> MSE: 0.000119, MAE: 0.008967, R²: -0.0261
  Directional -> Accuracy: 0.5000, MCC: 0.0153, F1: 0.3913

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.46622 | val 0.89625

[I 2026-02-22 21:21:02,648] Trial 27 finished with value: -0.01151699231925878 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.1, 'dropout': 0.0, 'batch_size': 32, 'learning_rate': 1.2441976028893757e-05, 'weight_decay': 1.0781782719035901e-06, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 1.4952557408267662, 'early_stopping_min_delta': 0.00629263586281637}. Best is trial 3 with value: -0.011473394984568777.

  Epoch 016 - train 0.46048 | val 0.92772
  Regression -> MSE: 0.000239, MAE: 0.012415, R²: -0.0057
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: regression
Sequence length: 12
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.38340 | val 1.17438
  Epoch 020 - train 0.37523 | val 1.17885
  Epoch 021 - train 0.38154 | val 1.17912
  Regression -> MSE: 0.000245, MAE: 0.012487, R²: 0.0002
  Directional -> Accuracy: 0.5128, MCC: 0.1931, F1: 0.6415

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 88). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.39702 | val 0.42017
  Epoch 020 - train 0.40681 | val 0.42722
  Epoch 024 - train 0.38983 | val 0.42829
  Regression -> MSE: 0.000665, MAE: 0.018968, R²: 0.0387
  Directional -> Accuracy: 0.6596, MCC: 0.3839, F1: 0.7647

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 88). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.43233 | val 0.98482
  Epoch 020 - train 0.47338 | val 0.99931
  Epoch 021 - train 0.44747 | val 0.99944
  Regression -> MSE: 0.000353, MAE: 0.015094, R²: -0.0230
  Directional -> Accuracy: 0.5000, MCC: 0.0216, F1: 0.4545

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.35083 | val 0.45511
  Epoch 020 - train 0.35310 | val 0.48506
  Epoch 021 - train 0.33916 | val 0.48559
  Regression -> MSE: 0.000342, MAE: 0.014438, R²: 0.0083
  Directional -> Accuracy: 0.5395, MCC: 0.0000, F1: 0.7009

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.41242 | val 0.36134
  Epoch 020 - train 0.37442 | val 0.35897
  Epoch 029 - train 0.36976 | val 0.36350
  Regression -> MSE: 0.000192, MAE: 0.009088, R²: 0.0437
  Directional -> Accuracy: 0.7500, MCC: 0.4991, F1: 0.7869

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.38689 | val 1.03423
  Epoch 020 - train 0.39231 | val 1.04148
  Epoch 021 - train 0.38677 | val 1.04162
  Regression -> MSE: 0.000616, MAE: 0.019111, R²: -0.0765
  Directional -> Accuracy: 0.4898, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.43475 | val 0.60210
  Epoch 020 - train 0.42359 | val 0.62573
  Epoch 025 - train 0.43287 | val 0.63390
  Regression -> MSE: 0.000262, MAE: 0.012839, R²: -0.0653
  Directional -> Accuracy: 0.4571, MCC: 0.0133, F1: 0.5250

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 88). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 88). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.42777 | val 0.78147
  Epoch 020 - train 0.40842 | val 0.93835
  Epoch 021 - train 0.41927 | val 0.94048
  Regression -> MSE: 0.000603, MAE: 0.019179, R²: -0.0312
  Directional -> Accuracy: 0.4667, MCC: 0.0068, F1: 0.5385

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.42093 | val 0.75184
  Epoch 020 - train 0.39862 | val 0.79527
  Epoch 021 - train 0.40830 | val 0.79610
  Regression -> MSE: 0.000343, MAE: 0.014850, R²: -0.0150
  Directional -> Accuracy: 0.6190, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 88). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 88). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.41078 | val 0.84882
  Epoch 020 - train 0.40798 | val 0.87680
  Epoch 021 - train 0.41495 | val 0.87842
  Regression -> MSE: 0.000243, MAE: 0.011502, R²: -0.0214
  Directional -> Accuracy: 0.5915, MCC: 0.1409, F1: 0.2162

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.38665 | val 1.25088
  Epoch 020 - train 0.38890 | val 1.35774
  Epoch 021 - train 0.39882 | val 1.35882
  Regression -> MSE: 0.000308, MAE: 0.013599, R²: -0.0067
  Directional -> Accuracy: 0.4706, MCC: -0.0765, F1: 0.3721

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.46934 | val 0.69868
  Epoch 020 - train 0.44773 | val 0.73380
  Epoch 021 - train 0.44756 | val 0.73494
  Regression -> MSE: 0.000691, MAE: 0.019726, R²: -0.0315
  Directional -> Accuracy: 0.4915, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.41802 | val 0.57106
  Epoch 020 - train 0.41284 | val 0.60101
  Epoch 021 - train 0.41828 | val 0.60159
  Regression -> MSE: 0.000151, MAE: 0.009438, R²: -0.0074
  Directional -> Accuracy: 0.5682, MCC: 0.1054, F1: 0.3871

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 88). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.35646 | val 0.64753
  Epoch 020 - train 0.33994 | val 0.66464
  Epoch 023 - train 0.35424 | val 0.66596
  Regression -> MSE: 0.000226, MAE: 0.010809, R²: -0.0077
  Directional -> Accuracy: 0.4677, MCC: -0.0645, F1: 0.4590

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.43112 | val 1.92200
  Epoch 020 - train 0.41860 | val 2.04545
  Epoch 021 - train 0.39132 | val 2.04693
  Regression -> MSE: 0.000390, MAE: 0.016843, R²: -0.0375
  Directional -> Accuracy: 0.4717, MCC: 0.0000, F1: 0.6410

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.44415 | val 0.54630
  Epoch 020 - train 0.43242 | val 0.55524
  Epoch 021 - train 0.41877 | val 0.55535
  Regression -> MSE: 0.000104, MAE: 0.007864, R²: 0.0182
  Directional -> Accuracy: 0.5211, MCC: 0.0636, F1: 0.4688

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.41900 | val 1.39153
  Epoch 020 - train 0.39641 | val 1.46780
  Epoch 021 - train 0.41439 | val 1.46798
  Regression -> MSE: 0.000161, MAE: 0.010018, R²: -0.0045
  Directional -> Accuracy: 0.6167, MCC: 0.0000, F1: 0.7629

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.40414 | val 0.67640
  Epoch 020 - train 0.40123 | val 0.70783
  Epoch 021 - train 0.39844 | val 0.70885
  Regression -> MSE: 0.000272, MAE: 0.012910, R²: -0.0111
  Directional -> Accuracy: 0.6104, MCC: 0.0000, F1: 0.7581

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.36515 | val 0.66857
  Epoch 020 - train 0.34076 | val 0.66121
  Epoch 030 - train 0.32251 | val 0.65705
  Epoch 039 - train 0.31897 | val 0.67307
  Regression -> MSE: 0.000307, MAE: 0.014075, R²: -1.0860
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 88). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.41765 | val 0.90036
  Epoch 020 - train 0.41979 | val 0.87503
  Epoch 021 - train 0.42637 | val 0.87425
  Regression -> MSE: 0.000233, MAE: 0.010947, R²: -0.0273
  Directional -> Accuracy: 0.5921, MCC: 0.1892, F1: 0.5974

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.41197 | val 0.60666
  Epoch 020 - train 0.40000 | val 0.61674
  Epoch 021 - train 0.41451 | val 0.61681
  Regression -> MSE: 0.000155, MAE: 0.008950, R²: -0.0474
  Directional -> Accuracy: 0.5306, MCC: 0.1416, F1: 0.5306

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 88). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 88). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 88). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.40313 | val 0.54949
  Epoch 020 - train 0.38358 | val 0.55553
  Epoch 021 - train 0.38975 | val 0.55550
  Regression -> MSE: 0.000201, MAE: 0.010778, R²: -0.1335
  Directional -> Accuracy: 0.4925, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.43858 | val 0.66475
  Epoch 020 - train 0.41840 | val 0.68661
  Epoch 021 - train 0.43502 | val 0.68819
  Regression -> MSE: 0.000084, MAE: 0.007005, R²: -0.0018
  Directional -> Accuracy: 0.5593, MCC: -0.1126, F1: 0.7174

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.42417 | val 0.88825
  Epoch 020 - train 0.40788 | val 0.91591
  Epoch 021 - train 0.38298 | val 0.91837
  Regression -> MSE: 0.000226, MAE: 0.011318, R²: -0.0360
  Directional -> Accuracy: 0.5224, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.36193 | val 0.32904
  Epoch 020 - train 0.34883 | val 0.32016
  Epoch 030 - train 0.31034 | val 0.31774
  Epoch 040 - train 0.31663 | val 0.31899
  Regression -> MSE: 0.000095, MAE: 0.007816, R²: -0.0371
  Directional -> Accuracy: 0.5439, MCC: 0.1313, F1: 0.5000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.42164 | val 0.21580
  Epoch 020 - train 0.43269 | val 0.24636
  Epoch 021 - train 0.42627 | val 0.24692
  Regression -> MSE: 0.000144, MAE: 0.009840, R²: -0.1419
  Directional -> Accuracy: 0.4167, MCC: 0.0000, F1: 0.5882

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.42421 | val 0.46763
  Epoch 020 - train 0.42978 | val 0.54621
  Epoch 021 - train 0.42180 | val 0.54589
  Regression -> MSE: 0.000240, MAE: 0.012780, R²: -0.0090
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.7429

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.40982 | val 0.59791
  Epoch 020 - train 0.40532 | val 0.59984
  Epoch 021 - train 0.42543 | val 0.59976
  Regression -> MSE: 0.000191, MAE: 0.008257, R²: -0.1628
  Directional -> Accuracy: 0.4483, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.47562 | val 0.47682
  Epoch 020 - train 0.42777 | val 0.62780
  Epoch 021 - train 0.45084 | val 0.62934
  Regression -> MSE: 0.000239, MAE: 0.012079, R²: -0.0193
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.41328 | val 0.84376
  Epoch 020 - train 0.43997 | val 0.87721
  Epoch 021 - train 0.43937 | val 0.87735
  Regression -> MSE: 0.000251, MAE: 0.010485, R²: -0.0023
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.46727 | val 0.72295
  Epoch 020 - train 0.42716 | val 0.78943
  Epoch 021 - train 0.41401 | val 0.79009
  Regression -> MSE: 0.000133, MAE: 0.008212, R²: 0.0016
  Directional -> Accuracy: 0.5111, MCC: -0.0714, F1: 0.6667

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.41903 | val 0.60236
  Epoch 020 - train 0.39539 | val 0.61318
  Epoch 026 - train 0.40324 | val 0.61575
  Regression -> MSE: 0.000207, MAE: 0.011354, R²: -0.0990
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.37564 | val 0.58789
  Epoch 020 - train 0.34791 | val 0.58011
  Epoch 030 - train 0.33099 | val 0.58200
  Epoch 032 - train 0.33609 | val 0.58280
  Regression -> MSE: 0.000329, MAE: 0.012308, R²: -0.2721
  Directional -> Accuracy: 0.5270, MCC: 0.1525, F1: 0.4068

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 88). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.42925 | val 0.36659
  Epoch 020 - train 0.41239 | val 0.38445
  Epoch 021 - train 0.40705 | val 0.38441
  Regression -> MSE: 0.000160, MAE: 0.010099, R²: 0.0187
  Directional -> Accuracy: 0.5641, MCC: 0.1885, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.38195 | val 0.78035
  Epoch 020 - train 0.38254 | val 0.79449
  Epoch 021 - train 0.39512 | val 0.79388
  Regression -> MSE: 0.000215, MAE: 0.011680, R²: -0.1781
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.6364

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.37580 | val 0.44148
  Epoch 020 - train 0.38153 | val 0.44458
  Epoch 021 - train 0.37883 | val 0.44435
  Regression -> MSE: 0.000351, MAE: 0.012693, R²: -0.0049
  Directional -> Accuracy: 0.4265, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.45292 | val 0.27151
  Epoch 020 - train 0.44085 | val 0.27895
  Epoch 021 - train 0.43894 | val 0.27889
  Regression -> MSE: 0.000112, MAE: 0.008164, R²: -0.0847
  Directional -> Accuracy: 0.5682, MCC: 0.1690, F1: 0.6667

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.44075 | val 0.74943
  Epoch 020 - train 0.42708 | val 0.76334
  Epoch 021 - train 0.41556 | val 0.76381
  Regression -> MSE: 0.000216, MAE: 0.011281, R²: -0.0050
  Directional -> Accuracy: 0.5345, MCC: 0.0767, F1: 0.5424

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.40790 | val 1.05413
  Epoch 020 - train 0.38652 | val 1.07558
  Epoch 021 - train 0.39620 | val 1.07559
  Regression -> MSE: 0.000085, MAE: 0.007219, R²: -0.0640
  Directional -> Accuracy: 0.6042, MCC: -0.1130, F1: 0.7532

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 88). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 88). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 88). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 88). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.40824 | val 0.33435
  Epoch 020 - train 0.38914 | val 0.32704
  Epoch 030 - train 0.38219 | val 0.32482
  Epoch 032 - train 0.39054 | val 0.32356
  Regression -> MSE: 0.000444, MAE: 0.018112, R²: -0.3541
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 88). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.46984 | val 0.23483
  Epoch 020 - train 0.46771 | val 0.26257
  Epoch 021 - train 0.43401 | val 0.26425
  Regression -> MSE: 0.000240, MAE: 0.011279, R²: -0.0086
  Directional -> Accuracy: 0.4872, MCC: 0.0188, F1: 0.3333

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 88). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 88). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.39314 | val 0.56499
  Epoch 020 - train 0.38539 | val 0.57310
  Epoch 023 - train 0.36863 | val 0.57435
  Regression -> MSE: 0.000078, MAE: 0.006990, R²: 0.0264
  Directional -> Accuracy: 0.5395, MCC: 0.0859, F1: 0.6154

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 88). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 88). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 88). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.43628 | val 0.44986
  Epoch 020 - train 0.40828 | val 0.45629
  Epoch 030 - train 0.40227 | val 0.45909
  Regression -> MSE: 0.000355, MAE: 0.015375, R²: 0.0123
  Directional -> Accuracy: 0.4167, MCC: -0.1672, F1: 0.4400

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.43924 | val 0.65965
  Epoch 020 - train 0.41582 | val 0.67561
  Epoch 021 - train 0.40223 | val 0.67567
  Regression -> MSE: 0.000101, MAE: 0.007141, R²: -0.0432
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.45541 | val 0.96737
  Epoch 020 - train 0.43146 | val 1.03332
  Epoch 021 - train 0.44964 | val 1.03324
  Regression -> MSE: 0.000187, MAE: 0.010569, R²: -0.0345
  Directional -> Accuracy: 0.3659, MCC: 0.0000, F1: 0.5357

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.38353 | val 1.07674
  Epoch 020 - train 0.38596 | val 1.16815
  Epoch 021 - train 0.38037 | val 1.17045
  Regression -> MSE: 0.000223, MAE: 0.011576, R²: -0.0138
  Directional -> Accuracy: 0.5614, MCC: 0.2137, F1: 0.4186

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.43000 | val 0.82967

[I 2026-02-22 21:21:44,641] Trial 28 finished with value: -0.011735994477019833 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 12, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.0, 'dropout': 0.4, 'batch_size': 32, 'learning_rate': 0.00011103103171336403, 'weight_decay': 3.530095677975984e-07, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 50, 'huber_delta': 1.3949057938713139, 'early_stopping_min_delta': 0.008823573415152226}. Best is trial 3 with value: -0.011473394984568777.

  Epoch 026 - train 0.42863 | val 0.79557
  Regression -> MSE: 0.000244, MAE: 0.012420, R²: -0.0432
  Directional -> Accuracy: 0.5323, MCC: 0.1322, F1: 0.0645

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.52499 | val 0.83349
  Epoch 015 - train 0.52315 | val 0.83416
  Regression -> MSE: 0.000250, MAE: 0.012625, R²: -0.0098
  Directional -> Accuracy: 0.4805, MCC: 0.0327, F1: 0.6000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.49068 | val 0.48141
  Epoch 011 - train 0.48762 | val 0.48032
  Regression -> MSE: 0.000683, MAE: 0.019379, R²: 0.0019
  Directional -> Accuracy: 0.5870, MCC: 0.1168, F1: 0.7077

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.52717 | val 0.99594
  Epoch 015 - train 0.51944 | val 0.99697
  Regression -> MSE: 0.000316, MAE: 0.014591, R²: -0.0175
  Directional -> Accuracy: 0.4468, MCC: -0.2311, F1: 0.6061

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.42347 | val 0.89744
  Epoch 011 - train 0.44164 | val 0.91158
  Regression -> MSE: 0.000408, MAE: 0.015734, R²: -0.1685
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.56223 | val 0.56914
  Epoch 011 - train 0.55462 | val 0.57427
  Regression -> MSE: 0.000207, MAE: 0.010283, R²: -0.0145
  Directional -> Accuracy: 0.3529, MCC: -0.2938, F1: 0.2326

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.47849 | val 1.20918
  Epoch 011 - train 0.45426 | val 1.21060
  Regression -> MSE: 0.000572, MAE: 0.018374, R²: -0.0299
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.52158 | val 0.68229
  Epoch 011 - train 0.49167 | val 0.68183
  Regression -> MSE: 0.000245, MAE: 0.011953, R²: 0.0032
  Directional -> Accuracy: 0.5217, MCC: 0.0139, F1: 0.4211

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.54553 | val 0.80880
  Epoch 011 - train 0.51336 | val 0.81987
  Regression -> MSE: 0.000645, MAE: 0.020159, R²: -0.0791
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.51724 | val 0.62138
  Epoch 015 - train 0.55012 | val 0.63518
  Regression -> MSE: 0.000423, MAE: 0.016349, R²: -0.1030
  Directional -> Accuracy: 0.5714, MCC: 0.1599, F1: 0.0870

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.51861 | val 0.70404
  Epoch 011 - train 0.53860 | val 0.70488
  Regression -> MSE: 0.000245, MAE: 0.011704, R²: -0.0159
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.46298 | val 0.79850
  Epoch 014 - train 0.47131 | val 0.81272
  Regression -> MSE: 0.000328, MAE: 0.013688, R²: -0.0540
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.51605 | val 0.70423
  Epoch 011 - train 0.51810 | val 0.69841
  Regression -> MSE: 0.000680, MAE: 0.019552, R²: -0.0041
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.48725 | val 0.53487
  Epoch 011 - train 0.50780 | val 0.53888
  Regression -> MSE: 0.000139, MAE: 0.009150, R²: -0.0044
  Directional -> Accuracy: 0.4419, MCC: -0.0728, F1: 0.5200

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.58175 | val 0.99387
  Epoch 011 - train 0.54987 | val 0.99392
  Regression -> MSE: 0.000232, MAE: 0.011176, R²: -0.0292
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.50735 | val 1.66952
  Epoch 011 - train 0.57020 | val 1.69188
  Regression -> MSE: 0.000363, MAE: 0.016102, R²: -0.0020
  Directional -> Accuracy: 0.4615, MCC: -0.0223, F1: 0.6111

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.53390 | val 0.52381
  Epoch 011 - train 0.49796 | val 0.52473
  Regression -> MSE: 0.000110, MAE: 0.008168, R²: -0.0210
  Directional -> Accuracy: 0.4571, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.49488 | val 1.19810
  Epoch 011 - train 0.50907 | val 1.19649
  Regression -> MSE: 0.000167, MAE: 0.010458, R²: -0.0723
  Directional -> Accuracy: 0.3729, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.52420 | val 0.52818
  Epoch 011 - train 0.51603 | val 0.52854
  Regression -> MSE: 0.000285, MAE: 0.013675, R²: -0.0460
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.41353 | val 0.79436
  Epoch 011 - train 0.41064 | val 0.79901
  Regression -> MSE: 0.000156, MAE: 0.008795, R²: -0.0402
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.49853 | val 1.05773
  Epoch 011 - train 0.54560 | val 1.06060
  Regression -> MSE: 0.000230, MAE: 0.011152, R²: -0.0180
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.53661 | val 0.80253
  Epoch 011 - train 0.55100 | val 0.80900
  Regression -> MSE: 0.000146, MAE: 0.008426, R²: -0.0212
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.50339 | val 0.58072
  Epoch 014 - train 0.53504 | val 0.57920
  Regression -> MSE: 0.000170, MAE: 0.010764, R²: -0.0317
  Directional -> Accuracy: 0.4848, MCC: -0.0381, F1: 0.6047

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.58502 | val 0.94522
  Epoch 011 - train 0.54567 | val 0.95475
  Regression -> MSE: 0.000089, MAE: 0.007247, R²: -0.0412
  Directional -> Accuracy: 0.5000, MCC: -0.0455, F1: 0.5915

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.59508 | val 0.76709
  Epoch 011 - train 0.62275 | val 0.77030
  Regression -> MSE: 0.000212, MAE: 0.011068, R²: -0.0007
  Directional -> Accuracy: 0.5152, MCC: 0.0232, F1: 0.4667

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.49919 | val 0.39170
  Epoch 011 - train 0.53802 | val 0.39171
  Regression -> MSE: 0.000092, MAE: 0.008099, R²: 0.0055
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.49993 | val 0.33156
  Epoch 018 - train 0.51820 | val 0.33516
  Regression -> MSE: 0.000103, MAE: 0.008721, R²: 0.0051
  Directional -> Accuracy: 0.4348, MCC: -0.0510, F1: 0.5667

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.54551 | val 0.56224
  Epoch 011 - train 0.57171 | val 0.56876
  Regression -> MSE: 0.000243, MAE: 0.012933, R²: -0.0492
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.63320 | val 1.03332
  Epoch 011 - train 0.59850 | val 1.03532
  Regression -> MSE: 0.000170, MAE: 0.008005, R²: -0.0217
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.49282 | val 0.30471
  Epoch 020 - train 0.51635 | val 0.30685
  Regression -> MSE: 0.000246, MAE: 0.012017, R²: -0.0414
  Directional -> Accuracy: 0.5366, MCC: 0.0649, F1: 0.5778

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.51754 | val 1.03939
  Epoch 011 - train 0.52373 | val 1.03998
  Regression -> MSE: 0.000234, MAE: 0.009946, R²: -0.0151
  Directional -> Accuracy: 0.4186, MCC: -0.1993, F1: 0.5614

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.54952 | val 0.69062
  Epoch 011 - train 0.56466 | val 0.70404
  Regression -> MSE: 0.000132, MAE: 0.008122, R²: 0.0211
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.56477 | val 0.73232
  Epoch 020 - train 0.55099 | val 0.72619
  Regression -> MSE: 0.000236, MAE: 0.012339, R²: -0.2551
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.47805 | val 0.65673
  Epoch 011 - train 0.45188 | val 0.65925
  Regression -> MSE: 0.000292, MAE: 0.011389, R²: -0.1142
  Directional -> Accuracy: 0.4384, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.56401 | val 0.41356
  Epoch 011 - train 0.58420 | val 0.41961
  Regression -> MSE: 0.000168, MAE: 0.010395, R²: -0.0081
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.52610 | val 0.68577
  Epoch 011 - train 0.55269 | val 0.68793
  Regression -> MSE: 0.000198, MAE: 0.011036, R²: -0.0997
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.54425 | val 0.49208
  Epoch 011 - train 0.46700 | val 0.49404
  Regression -> MSE: 0.000352, MAE: 0.012364, R²: -0.0280
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.56726 | val 0.31539
  Epoch 011 - train 0.59092 | val 0.32361
  Regression -> MSE: 0.000116, MAE: 0.008338, R²: -0.1080
  Directional -> Accuracy: 0.6047, MCC: 0.2100, F1: 0.6047

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.59036 | val 1.03533
  Epoch 011 - train 0.55146 | val 1.03598
  Regression -> MSE: 0.000218, MAE: 0.011178, R²: 0.0041
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.50216 | val 1.17979
  Epoch 011 - train 0.51248 | val 1.18135
  Regression -> MSE: 0.000089, MAE: 0.007392, R²: -0.1504
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.55625 | val 0.29199
  Epoch 011 - train 0.48631 | val 0.29511
  Regression -> MSE: 0.000310, MAE: 0.013979, R²: -0.0071
  Directional -> Accuracy: 0.5510, MCC: 0.1002, F1: 0.4762

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.55240 | val 0.25855
  Epoch 011 - train 0.53810 | val 0.26561
  Regression -> MSE: 0.000249, MAE: 0.011457, R²: -0.0197
  Directional -> Accuracy: 0.6316, MCC: 0.2709, F1: 0.7083

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.56894 | val 0.75229
  Epoch 011 - train 0.56099 | val 0.75288
  Regression -> MSE: 0.000087, MAE: 0.007410, R²: -0.0739
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.53714 | val 0.74058
  Epoch 013 - train 0.49637 | val 0.80223
  Regression -> MSE: 0.000307, MAE: 0.014458, R²: -0.0009
  Directional -> Accuracy: 0.5319, MCC: 0.1506, F1: 0.6857

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.52845 | val 0.62436
  Epoch 011 - train 0.52615 | val 0.62870
  Regression -> MSE: 0.000100, MAE: 0.007075, R²: -0.0213
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.60191 | val 0.71309
  Epoch 020 - train 0.56554 | val 0.69998
  Epoch 030 - train 0.56981 | val 0.69923
  Regression -> MSE: 0.000194, MAE: 0.010228, R²: -0.1298
  Directional -> Accuracy: 0.4898, MCC: -0.1325, F1: 0.2424

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.46869 | val 0.62005
  Epoch 011 - train 0.50032 | val 0.62224
  Regression -> MSE: 0.000224, MAE: 0.011741, R²: -0.0030
  Directional -> Accuracy: 0.5536, MCC: 0.0801, F1: 0.6753

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.55548 | val 0.57516
  Epoch 011 - train 0.57321 | val 0.57533
  Regression -> MSE: 0.000093, MAE: 0.007626, R²: -0.0045
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.60991 | val 1.28231
  Epoch 011 - train 0.62313 | val 1.29523
  Regression -> MSE: 0.000171, MAE: 0.010561, R²: -0.0467
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.50117 | val 1.16680
  Epoch 011 - train 0.50413 | val 1.18484
  Regression -> MSE: 0.000119, MAE: 0.008984, R²: -0.0295
  Directional -> Accuracy: 0.5357, MCC: 0.0633, F1: 0.6061

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...

[I 2026-02-22 21:22:13,556] Trial 29 finished with value: -0.011575540020520317 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.1, 'dropout': 0.6000000000000001, 'batch_size': 32, 'learning_rate': 5.794037233819278e-06, 'weight_decay': 4.95969575820563e-07, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.7295827039951852, 'early_stopping_min_delta': 0.007653514990020071}. Best is trial 3 with value: -0.011473394984568777.

  Epoch 010 - train 0.59349 | val 1.07113
  Epoch 011 - train 0.59012 | val 1.07270
  Regression -> MSE: 0.000237, MAE: 0.012410, R²: 0.0005
  Directional -> Accuracy: 0.5574, MCC: 0.2398, F1: 0.6747

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: regression
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.46013 | val 0.72143
  Epoch 020 - train 0.44985 | val 0.71988
  Epoch 021 - train 0.47461 | val 0.72313
  Regression -> MSE: 0.000242, MAE: 0.012430, R²: -0.0054
  Directional -> Accuracy: 0.4079, MCC: -0.1942, F1: 0.3478

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.46787 | val 0.42317
  Epoch 020 - train 0.47913 | val 0.41696
  Epoch 030 - train 0.47958 | val 0.41364
  Epoch 040 - train 0.43878 | val 0.41167
  Epoch 050 - train 0.45170 | val 0.41427
  Regression -> MSE: 0.000729, MAE: 0.020133, R²: -0.0440
  Directional -> Accuracy: 0.4667, MCC: -0.0230, F1: 0.4286

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.46921 | val 0.94193
  Epoch 020 - train 0.49351 | val 0.93948
  Epoch 021 - train 0.51165 | val 0.93849
  Regression -> MSE: 0.000321, MAE: 0.014599, R²: -0.0208
  Directional -> Accuracy: 0.4348, MCC: -0.1434, F1: 0.5000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.37686 | val 0.71429
  Epoch 020 - train 0.34538 | val 0.74894
  Epoch 021 - train 0.38986 | val 0.73993
  Regression -> MSE: 0.000388, MAE: 0.015223, R²: -0.0997
  Directional -> Accuracy: 0.4595, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.47813 | val 0.42749
  Epoch 020 - train 0.45010 | val 0.41418
  Epoch 021 - train 0.46189 | val 0.41393
  Regression -> MSE: 0.000209, MAE: 0.010229, R²: -0.0142
  Directional -> Accuracy: 0.5200, MCC: 0.0000, F1: 0.6842

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.47613 | val 1.05719
  Epoch 020 - train 0.51380 | val 1.07186
  Epoch 021 - train 0.46649 | val 1.06383
  Regression -> MSE: 0.000608, MAE: 0.019024, R²: -0.0747
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.46417 | val 0.60789
  Epoch 020 - train 0.46548 | val 0.59991
  Epoch 021 - train 0.45714 | val 0.59898
  Regression -> MSE: 0.000249, MAE: 0.012022, R²: -0.0034
  Directional -> Accuracy: 0.5735, MCC: 0.0186, F1: 0.2564

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.44512 | val 0.44246
  Epoch 020 - train 0.43788 | val 0.46706
  Epoch 021 - train 0.44419 | val 0.46504
  Regression -> MSE: 0.000637, MAE: 0.020054, R²: -0.0429
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.43054 | val 0.57997
  Epoch 020 - train 0.44891 | val 0.58041
  Epoch 030 - train 0.44826 | val 0.58433
  Epoch 031 - train 0.47682 | val 0.58127
  Regression -> MSE: 0.000393, MAE: 0.015703, R²: -0.0533
  Directional -> Accuracy: 0.5625, MCC: 0.0263, F1: 0.0870

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.44539 | val 0.65152
  Epoch 020 - train 0.43846 | val 0.66147
  Epoch 021 - train 0.44812 | val 0.66279
  Regression -> MSE: 0.000247, MAE: 0.011863, R²: -0.0083
  Directional -> Accuracy: 0.4783, MCC: -0.0707, F1: 0.3793

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.45508 | val 0.90842
  Epoch 020 - train 0.42861 | val 0.91897
  Epoch 021 - train 0.44036 | val 0.92578
  Regression -> MSE: 0.000303, MAE: 0.013511, R²: 0.0298
  Directional -> Accuracy: 0.5714, MCC: 0.1081, F1: 0.4000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.47206 | val 0.60425
  Epoch 020 - train 0.46347 | val 0.60031
  Epoch 021 - train 0.49541 | val 0.60756
  Regression -> MSE: 0.000683, MAE: 0.019557, R²: 0.0034
  Directional -> Accuracy: 0.5088, MCC: 0.0294, F1: 0.3636

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.41272 | val 0.51897
  Epoch 020 - train 0.44652 | val 0.52210
  Epoch 021 - train 0.46714 | val 0.52125
  Regression -> MSE: 0.000143, MAE: 0.009307, R²: -0.0326
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.45081 | val 0.66342
  Epoch 020 - train 0.43350 | val 0.66007
  Epoch 021 - train 0.43890 | val 0.65795
  Regression -> MSE: 0.000233, MAE: 0.010928, R²: -0.0284
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.47493 | val 1.47285
  Epoch 020 - train 0.46716 | val 1.50174
  Epoch 021 - train 0.47499 | val 1.49782
  Regression -> MSE: 0.000370, MAE: 0.016420, R²: -0.0098
  Directional -> Accuracy: 0.4510, MCC: 0.0000, F1: 0.6216

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.48279 | val 0.46006
  Epoch 020 - train 0.50226 | val 0.46167
  Epoch 021 - train 0.46696 | val 0.46570
  Regression -> MSE: 0.000110, MAE: 0.008140, R²: -0.0161
  Directional -> Accuracy: 0.4638, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.43639 | val 1.06025
  Epoch 020 - train 0.47209 | val 1.06341
  Epoch 021 - train 0.44146 | val 1.05292
  Regression -> MSE: 0.000164, MAE: 0.009833, R²: -0.0402
  Directional -> Accuracy: 0.6207, MCC: 0.0000, F1: 0.7660

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.46441 | val 0.45881
  Epoch 020 - train 0.47629 | val 0.46004
  Epoch 021 - train 0.43992 | val 0.45831
  Regression -> MSE: 0.000282, MAE: 0.013399, R²: -0.0305
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.40486 | val 0.67772
  Epoch 020 - train 0.38804 | val 0.67182
  Epoch 021 - train 0.39711 | val 0.67054
  Regression -> MSE: 0.000159, MAE: 0.008931, R²: -0.0462
  Directional -> Accuracy: 0.5781, MCC: 0.0000, F1: 0.7327

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.50557 | val 0.94455
  Epoch 020 - train 0.48227 | val 0.91824
  Epoch 021 - train 0.47424 | val 0.91031
  Regression -> MSE: 0.000238, MAE: 0.011160, R²: -0.0474
  Directional -> Accuracy: 0.4054, MCC: -0.2107, F1: 0.4762

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.48200 | val 0.65149
  Epoch 020 - train 0.48670 | val 0.64485
  Epoch 021 - train 0.50057 | val 0.64399
  Regression -> MSE: 0.000161, MAE: 0.009057, R²: -0.1191
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.44486 | val 0.52426
  Epoch 020 - train 0.40186 | val 0.52196
  Epoch 021 - train 0.42871 | val 0.52197
  Regression -> MSE: 0.000170, MAE: 0.010429, R²: -0.0272
  Directional -> Accuracy: 0.5077, MCC: 0.0000, F1: 0.6735

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.46415 | val 0.57161
  Epoch 020 - train 0.48418 | val 0.57103
  Epoch 021 - train 0.48148 | val 0.57127
  Regression -> MSE: 0.000085, MAE: 0.007142, R²: 0.0147
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.43716 | val 0.60261
  Epoch 020 - train 0.43746 | val 0.59962
  Epoch 021 - train 0.44384 | val 0.60037
  Regression -> MSE: 0.000210, MAE: 0.011011, R²: 0.0051
  Directional -> Accuracy: 0.5538, MCC: 0.1327, F1: 0.6133

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.44569 | val 0.40674
  Epoch 020 - train 0.39709 | val 0.39693
  Epoch 021 - train 0.46173 | val 0.39372
  Regression -> MSE: 0.000102, MAE: 0.008121, R²: -0.1323
  Directional -> Accuracy: 0.4545, MCC: -0.0256, F1: 0.1176

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.50410 | val 0.35067
  Epoch 020 - train 0.49462 | val 0.35277
  Epoch 021 - train 0.43614 | val 0.35270
  Regression -> MSE: 0.000101, MAE: 0.008606, R²: -0.0124
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.48693 | val 0.42404
  Epoch 020 - train 0.49434 | val 0.42285
  Epoch 021 - train 0.51170 | val 0.42258
  Regression -> MSE: 0.000237, MAE: 0.012782, R²: -0.0015
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.44856 | val 0.62103
  Epoch 020 - train 0.47494 | val 0.61241
  Epoch 021 - train 0.49058 | val 0.61292
  Regression -> MSE: 0.000175, MAE: 0.007806, R²: -0.0315
  Directional -> Accuracy: 0.5893, MCC: 0.1970, F1: 0.5818

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.47521 | val 0.46699
  Epoch 020 - train 0.55433 | val 0.50995
  Epoch 021 - train 0.47084 | val 0.51883
  Regression -> MSE: 0.000249, MAE: 0.012221, R²: -0.0277
  Directional -> Accuracy: 0.5500, MCC: 0.0000, F1: 0.7097

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.46561 | val 0.89340
  Epoch 020 - train 0.44260 | val 0.88517
  Epoch 030 - train 0.44829 | val 0.88251
  Epoch 040 - train 0.48654 | val 0.88153
  Epoch 049 - train 0.43227 | val 0.88286
  Regression -> MSE: 0.000226, MAE: 0.010007, R²: 0.0415
  Directional -> Accuracy: 0.4762, MCC: -0.0195, F1: 0.6071

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.49985 | val 0.54862
  Epoch 020 - train 0.48085 | val 0.55457
  Epoch 021 - train 0.44992 | val 0.55295
  Regression -> MSE: 0.000138, MAE: 0.008276, R²: -0.0038
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.7077

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.45006 | val 0.68261
  Epoch 020 - train 0.46858 | val 0.67796
  Epoch 021 - train 0.45521 | val 0.67198
  Regression -> MSE: 0.000184, MAE: 0.010190, R²: -0.0073
  Directional -> Accuracy: 0.5306, MCC: 0.0229, F1: 0.6667

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.40381 | val 0.61487
  Epoch 020 - train 0.42129 | val 0.59015
  Epoch 021 - train 0.42198 | val 0.59351
  Regression -> MSE: 0.000265, MAE: 0.010678, R²: -0.0001
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.44941 | val 0.47951
  Epoch 020 - train 0.46461 | val 0.48763
  Epoch 021 - train 0.46546 | val 0.48728
  Regression -> MSE: 0.000192, MAE: 0.010755, R²: -0.0457
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.39862 | val 0.42235
  Epoch 020 - train 0.39828 | val 0.42229
  Epoch 021 - train 0.42019 | val 0.42233
  Regression -> MSE: 0.000348, MAE: 0.012256, R²: -0.0008
  Directional -> Accuracy: 0.4242, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.46748 | val 0.23119
  Epoch 020 - train 0.46291 | val 0.23476
  Epoch 021 - train 0.50981 | val 0.23504
  Regression -> MSE: 0.000118, MAE: 0.008409, R²: -0.1164
  Directional -> Accuracy: 0.5476, MCC: 0.0911, F1: 0.6780

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.50320 | val 0.77911
  Epoch 020 - train 0.46173 | val 0.77624
  Epoch 021 - train 0.50567 | val 0.77833
  Regression -> MSE: 0.000219, MAE: 0.011233, R²: 0.0017
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.44508 | val 1.01989
  Epoch 020 - train 0.42903 | val 1.01841
  Epoch 021 - train 0.44673 | val 1.01830
  Regression -> MSE: 0.000080, MAE: 0.006961, R²: -0.0789
  Directional -> Accuracy: 0.4130, MCC: 0.1195, F1: 0.0690

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.45534 | val 0.29294
  Epoch 020 - train 0.45603 | val 0.31583
  Epoch 021 - train 0.50814 | val 0.31335
  Regression -> MSE: 0.000346, MAE: 0.015588, R²: -0.1103
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.45113 | val 0.62010
  Epoch 020 - train 0.43651 | val 0.61124
  Epoch 021 - train 0.46384 | val 0.60995
  Regression -> MSE: 0.000079, MAE: 0.007013, R²: -0.0173
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.47485 | val 0.75679
  Epoch 020 - train 0.47151 | val 0.76463
  Epoch 021 - train 0.48104 | val 0.76874
  Regression -> MSE: 0.000297, MAE: 0.014287, R²: 0.0123
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.46627 | val 0.51587
  Epoch 020 - train 0.41415 | val 0.52360
  Epoch 021 - train 0.45512 | val 0.52460
  Regression -> MSE: 0.000099, MAE: 0.007335, R²: 0.0219
  Directional -> Accuracy: 0.5476, MCC: 0.2178, F1: 0.4242

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.51750 | val 0.72516
  Epoch 020 - train 0.50649 | val 0.73631
  Epoch 021 - train 0.49896 | val 0.73799
  Regression -> MSE: 0.000182, MAE: 0.010459, R²: -0.0358
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.43808 | val 0.60337
  Epoch 020 - train 0.42182 | val 0.59701
  Epoch 021 - train 0.41965 | val 0.59186
  Regression -> MSE: 0.000230, MAE: 0.011913, R²: -0.0180
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.46424 | val 0.56585
  Epoch 020 - train 0.41908 | val 0.58107
  Epoch 021 - train 0.46943 | val 0.57872
  Regression -> MSE: 0.000095, MAE: 0.007807, R²: -0.0092
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.47302 | val 0.89119
  Epoch 020 - train 0.49336 | val 0.88994

[I 2026-02-22 21:24:16,148] Trial 30 finished with value: -0.011562600612947374 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.6000000000000001, 'batch_size': 32, 'learning_rate': 1.9711346520692496e-05, 'weight_decay': 1.9533778788329263e-06, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 50, 'huber_delta': 1.2115609673809749, 'early_stopping_min_delta': 0.00664745305724061}. Best is trial 3 with value: -0.011473394984568777.

  Epoch 020 - train 0.47088 | val 0.78114
  Epoch 021 - train 0.48727 | val 0.78242
  Regression -> MSE: 0.000240, MAE: 0.012524, R²: 0.0002
  Directional -> Accuracy: 0.4833, MCC: 0.0000, F1: 0.6517

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.43402 | val 0.76453
  Epoch 016 - train 0.42496 | val 0.75700
  Regression -> MSE: 0.000249, MAE: 0.012622, R²: -0.0066
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.43610 | val 0.44191
  Epoch 020 - train 0.42434 | val 0.42766
  Regression -> MSE: 0.000643, MAE: 0.018662, R²: 0.0609
  Directional -> Accuracy: 0.6522, MCC: 0.2779, F1: 0.7333

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.47198 | val 0.98498
  Epoch 016 - train 0.45252 | val 0.99731
  Regression -> MSE: 0.000316, MAE: 0.014350, R²: -0.0182
  Directional -> Accuracy: 0.4894, MCC: 0.0471, F1: 0.2000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.34958 | val 1.03568
  Epoch 016 - train 0.35322 | val 1.27519
  Regression -> MSE: 0.000359, MAE: 0.014767, R²: -0.0278
  Directional -> Accuracy: 0.4800, MCC: -0.0573, F1: 0.5412

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.43183 | val 0.44512
  Epoch 020 - train 0.42334 | val 0.42899
  Regression -> MSE: 0.000204, MAE: 0.009301, R²: -0.0031
  Directional -> Accuracy: 0.6863, MCC: 0.3723, F1: 0.7333

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.41408 | val 1.08562
  Epoch 020 - train 0.41284 | val 1.13879
  Regression -> MSE: 0.000555, MAE: 0.018236, R²: 0.0010
  Directional -> Accuracy: 0.5957, MCC: 0.2361, F1: 0.3871

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.44605 | val 0.64105
  Epoch 020 - train 0.42998 | val 0.63271
  Regression -> MSE: 0.000240, MAE: 0.011736, R²: 0.0212
  Directional -> Accuracy: 0.5942, MCC: 0.1683, F1: 0.5172

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.43238 | val 0.58952
  Epoch 020 - train 0.43211 | val 0.54447
  Regression -> MSE: 0.000609, MAE: 0.019156, R²: -0.0185
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.41834 | val 0.59080
  Epoch 016 - train 0.41092 | val 0.60123
  Regression -> MSE: 0.000389, MAE: 0.015886, R²: -0.0131
  Directional -> Accuracy: 0.6327, MCC: 0.2576, F1: 0.5909

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.44292 | val 0.70414
  Epoch 020 - train 0.43288 | val 0.85715
  Regression -> MSE: 0.000248, MAE: 0.011930, R²: -0.0272
  Directional -> Accuracy: 0.4857, MCC: -0.0683, F1: 0.3571

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.40237 | val 1.08902
  Epoch 016 - train 0.39328 | val 1.19591
  Regression -> MSE: 0.000312, MAE: 0.013701, R²: -0.0048
  Directional -> Accuracy: 0.4400, MCC: -0.1048, F1: 0.6000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.47966 | val 0.67232
  Epoch 016 - train 0.46407 | val 0.64996
  Regression -> MSE: 0.000681, MAE: 0.019671, R²: -0.0059
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.43524 | val 0.48865
  Epoch 016 - train 0.42032 | val 0.58718
  Regression -> MSE: 0.000142, MAE: 0.009418, R²: -0.0309
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.39284 | val 0.66095
  Epoch 020 - train 0.39087 | val 0.65831
  Regression -> MSE: 0.000230, MAE: 0.011034, R²: -0.0212
  Directional -> Accuracy: 0.5410, MCC: 0.0995, F1: 0.4167

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.44152 | val 1.38497
  Epoch 016 - train 0.42871 | val 1.45982
  Regression -> MSE: 0.000364, MAE: 0.016266, R²: -0.0047
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.45442 | val 0.52747
  Epoch 016 - train 0.44301 | val 0.54122
  Regression -> MSE: 0.000108, MAE: 0.007946, R²: 0.0021
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.42217 | val 1.38120
  Epoch 016 - train 0.42681 | val 1.31243
  Regression -> MSE: 0.000156, MAE: 0.009516, R²: -0.0026
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.46786 | val 0.70173
  Epoch 016 - train 0.44741 | val 0.76947
  Regression -> MSE: 0.000282, MAE: 0.013485, R²: -0.0345
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.35754 | val 0.68783
  Epoch 020 - train 0.35249 | val 0.67918
  Regression -> MSE: 0.000206, MAE: 0.010893, R²: -0.3780
  Directional -> Accuracy: 0.4769, MCC: 0.0998, F1: 0.2917

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.45643 | val 0.95271
  Epoch 019 - train 0.43756 | val 1.06112
  Regression -> MSE: 0.000261, MAE: 0.011655, R²: -0.1527
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.43889 | val 0.79583
  Epoch 016 - train 0.43545 | val 0.79105
  Regression -> MSE: 0.000146, MAE: 0.008529, R²: -0.0160
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.43807 | val 0.58643
  Epoch 020 - train 0.41524 | val 0.57952
  Regression -> MSE: 0.000176, MAE: 0.010069, R²: -0.0631
  Directional -> Accuracy: 0.5758, MCC: 0.1541, F1: 0.5333

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.46098 | val 0.63964
  Epoch 020 - train 0.44824 | val 0.65491
  Regression -> MSE: 0.000085, MAE: 0.007068, R²: 0.0085
  Directional -> Accuracy: 0.6034, MCC: 0.1599, F1: 0.7013

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.44505 | val 0.75546
  Epoch 016 - train 0.43564 | val 0.78051
  Regression -> MSE: 0.000213, MAE: 0.011034, R²: -0.0075
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.38822 | val 0.32815
  Epoch 020 - train 0.36358 | val 0.31068
  Regression -> MSE: 0.000101, MAE: 0.008170, R²: -0.1015
  Directional -> Accuracy: 0.5714, MCC: 0.2187, F1: 0.4783

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.48006 | val 0.33320
  Epoch 020 - train 0.46870 | val 0.32528
  Regression -> MSE: 0.000098, MAE: 0.008332, R²: 0.0526
  Directional -> Accuracy: 0.6304, MCC: 0.3557, F1: 0.6792

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.46895 | val 0.45782
  Epoch 016 - train 0.45855 | val 0.49141
  Regression -> MSE: 0.000240, MAE: 0.012820, R²: -0.0348
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.44171 | val 0.61250
  Epoch 016 - train 0.42480 | val 0.61171
  Regression -> MSE: 0.000174, MAE: 0.007836, R²: -0.0469
  Directional -> Accuracy: 0.5439, MCC: 0.0737, F1: 0.5938

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.45455 | val 0.29813
  Epoch 016 - train 0.46102 | val 0.31042
  Regression -> MSE: 0.000238, MAE: 0.011904, R²: -0.0060
  Directional -> Accuracy: 0.5366, MCC: 0.0166, F1: 0.6885

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.46159 | val 0.93998
  Epoch 016 - train 0.44053 | val 0.98530
  Regression -> MSE: 0.000229, MAE: 0.009865, R²: 0.0045
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.46261 | val 0.67129
  Epoch 016 - train 0.46065 | val 0.70040
  Regression -> MSE: 0.000136, MAE: 0.008252, R²: -0.0082
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.44832 | val 0.65363
  Epoch 016 - train 0.42679 | val 0.66142
  Regression -> MSE: 0.000194, MAE: 0.010495, R²: -0.0298
  Directional -> Accuracy: 0.4200, MCC: -0.1394, F1: 0.2927

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.37572 | val 0.60237
  Epoch 019 - train 0.36414 | val 0.60056
  Regression -> MSE: 0.000289, MAE: 0.011630, R²: -0.1055
  Directional -> Accuracy: 0.5616, MCC: 0.1622, F1: 0.5294

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.45374 | val 0.35276
  Epoch 016 - train 0.44107 | val 0.37572
  Regression -> MSE: 0.000173, MAE: 0.010442, R²: -0.0392
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.39511 | val 0.56531
  Epoch 016 - train 0.39076 | val 0.61186
  Regression -> MSE: 0.000182, MAE: 0.010340, R²: -0.0116
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.42565 | val 0.46149
  Epoch 018 - train 0.41687 | val 0.47259
  Regression -> MSE: 0.000342, MAE: 0.011715, R²: 0.0032
  Directional -> Accuracy: 0.5224, MCC: -0.0478, F1: 0.6522

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.45349 | val 0.23247
  Epoch 016 - train 0.45486 | val 0.23654
  Regression -> MSE: 0.000117, MAE: 0.008368, R²: -0.1123
  Directional -> Accuracy: 0.4419, MCC: -0.1596, F1: 0.5714

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.43565 | val 0.83592
  Epoch 016 - train 0.43416 | val 0.86312
  Regression -> MSE: 0.000218, MAE: 0.011208, R²: 0.0023
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.42232 | val 1.13789
  Epoch 016 - train 0.42376 | val 1.15778
  Regression -> MSE: 0.000082, MAE: 0.007083, R²: -0.0616
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.42950 | val 0.36611
  Epoch 016 - train 0.43981 | val 0.36676
  Regression -> MSE: 0.000339, MAE: 0.015326, R²: -0.1018
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.50378 | val 0.22511
  Epoch 016 - train 0.49130 | val 0.24279
  Regression -> MSE: 0.000253, MAE: 0.011533, R²: -0.0392
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.38920 | val 0.60722
  Epoch 020 - train 0.38655 | val 0.64250
  Regression -> MSE: 0.000081, MAE: 0.007088, R²: -0.0007
  Directional -> Accuracy: 0.5333, MCC: 0.1182, F1: 0.6602

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.46557 | val 0.62944
  Epoch 020 - train 0.45937 | val 0.58685
  Regression -> MSE: 0.000310, MAE: 0.014378, R²: -0.0094
  Directional -> Accuracy: 0.4255, MCC: -0.1583, F1: 0.4906

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.46416 | val 0.61687
  Epoch 016 - train 0.44450 | val 0.62355
  Regression -> MSE: 0.000104, MAE: 0.007103, R²: -0.0625
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.45849 | val 0.68757
  Epoch 016 - train 0.45093 | val 0.70868
  Regression -> MSE: 0.000173, MAE: 0.009507, R²: -0.0042
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.42573 | val 0.77530
  Epoch 016 - train 0.40376 | val 0.83198
  Regression -> MSE: 0.000225, MAE: 0.011765, R²: -0.0082
  Directional -> Accuracy: 0.4643, MCC: -0.0453, F1: 0.3478

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.43145 | val 0.56282
  Epoch 020 - train 0.41749 | val 0.57947
  Regression -> MSE: 0.000092, MAE: 0.007625, R²: 0.0086
  Directional -> Accuracy: 0.5088, MCC: 0.1809, F1: 0.6585

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.47650 | val 0.92633
  Epoch 016 - train 0.46323 | val 0.91534
  Regression -> MSE: 0.000165, MAE: 0.010297, R²: -0.0071
  Directional -> Accuracy: 0.4630, MCC: -0.0661, F1: 0.3830

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.42565 | val 0.82880
  Epoch 016 - train 0.43050 | val 0.82711
  Regression -> MSE: 0.000116, MAE: 0.008900, R²: -0.0002
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.45149 | val 0.83728

[I 2026-02-22 21:26:19,443] Trial 31 finished with value: -0.011425014985750452 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.1, 'dropout': 0.0, 'batch_size': 32, 'learning_rate': 1.2483087732196388e-05, 'weight_decay': 1.057198459751683e-06, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 1.4789455235490498, 'early_stopping_min_delta': 0.006089313448266185}. Best is trial 31 with value: -0.011425014985750452.

  Epoch 016 - train 0.45244 | val 0.86443
  Regression -> MSE: 0.000240, MAE: 0.012339, R²: -0.0122
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.44837 | val 0.98050
  Epoch 016 - train 0.45351 | val 0.97008
  Regression -> MSE: 0.000258, MAE: 0.012969, R²: -0.0440
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.49081 | val 0.65137
  Epoch 016 - train 0.48957 | val 0.79423
  Regression -> MSE: 0.000702, MAE: 0.019646, R²: -0.0253
  Directional -> Accuracy: 0.4348, MCC: -0.0870, F1: 0.3500

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.47790 | val 1.00778
  Epoch 016 - train 0.47097 | val 1.03322
  Regression -> MSE: 0.000309, MAE: 0.014368, R²: 0.0051
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.38044 | val 0.49579
  Epoch 016 - train 0.37794 | val 0.55708
  Regression -> MSE: 0.000408, MAE: 0.015673, R²: -0.1685
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.48733 | val 0.50006
  Epoch 016 - train 0.48621 | val 0.49723
  Regression -> MSE: 0.000205, MAE: 0.009980, R²: -0.0076
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.44841 | val 1.17079
  Epoch 016 - train 0.43473 | val 1.20471
  Regression -> MSE: 0.000579, MAE: 0.018570, R²: -0.0431
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.45817 | val 0.65041
  Epoch 019 - train 0.45846 | val 0.65920
  Regression -> MSE: 0.000249, MAE: 0.011909, R²: -0.0126
  Directional -> Accuracy: 0.5217, MCC: -0.0209, F1: 0.3529

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.48942 | val 0.70046
  Epoch 016 - train 0.46748 | val 0.73201
  Regression -> MSE: 0.000623, MAE: 0.019737, R²: -0.0421
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.44393 | val 0.59330
  Epoch 016 - train 0.45507 | val 0.61296
  Regression -> MSE: 0.000392, MAE: 0.015925, R²: -0.0212
  Directional -> Accuracy: 0.5306, MCC: 0.0060, F1: 0.3030

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.47200 | val 0.69817
  Epoch 016 - train 0.45955 | val 0.69993
  Regression -> MSE: 0.000243, MAE: 0.012152, R²: -0.0052
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.43777 | val 0.74459
  Epoch 020 - train 0.43220 | val 0.75117
  Regression -> MSE: 0.000352, MAE: 0.014160, R²: -0.1327
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.46030 | val 0.68089
  Epoch 016 - train 0.46068 | val 0.69746
  Regression -> MSE: 0.000678, MAE: 0.019668, R²: -0.0011
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.44618 | val 0.56653
  Epoch 016 - train 0.43669 | val 0.54603
  Regression -> MSE: 0.000138, MAE: 0.009007, R²: -0.0012
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.40169 | val 0.82053
  Epoch 016 - train 0.39993 | val 0.81926
  Regression -> MSE: 0.000226, MAE: 0.010701, R²: -0.0030
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.47304 | val 1.38734
  Epoch 016 - train 0.47480 | val 1.38736
  Regression -> MSE: 0.000364, MAE: 0.015940, R²: -0.0064
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.52977 | val 0.57053
  Epoch 016 - train 0.49909 | val 0.55023
  Regression -> MSE: 0.000108, MAE: 0.008044, R²: -0.0011
  Directional -> Accuracy: 0.4571, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.42606 | val 1.12715
  Epoch 016 - train 0.42207 | val 1.16651
  Regression -> MSE: 0.000156, MAE: 0.009826, R²: -0.0034
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.47930 | val 0.50423
  Epoch 016 - train 0.46702 | val 0.50041
  Regression -> MSE: 0.000276, MAE: 0.013177, R²: -0.0138
  Directional -> Accuracy: 0.5789, MCC: 0.1396, F1: 0.6364

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.40658 | val 0.76244
  Epoch 020 - train 0.38003 | val 0.72266
  Regression -> MSE: 0.000186, MAE: 0.009454, R²: -0.2447
  Directional -> Accuracy: 0.5077, MCC: -0.0029, F1: 0.5676

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.46651 | val 0.92256
  Epoch 016 - train 0.44256 | val 0.92873
  Regression -> MSE: 0.000231, MAE: 0.011052, R²: -0.0190
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.46685 | val 0.70153
  Epoch 020 - train 0.44394 | val 0.69054
  Regression -> MSE: 0.000155, MAE: 0.008848, R²: -0.0834
  Directional -> Accuracy: 0.5833, MCC: 0.3478, F1: 0.5238

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.41419 | val 0.58969
  Epoch 016 - train 0.43421 | val 0.59329
  Regression -> MSE: 0.000172, MAE: 0.010203, R²: -0.0404
  Directional -> Accuracy: 0.5909, MCC: 0.1978, F1: 0.4906

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.47889 | val 0.64643
  Epoch 020 - train 0.47049 | val 0.65445
  Regression -> MSE: 0.000086, MAE: 0.007127, R²: -0.0118
  Directional -> Accuracy: 0.5517, MCC: 0.0687, F1: 0.6286

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.48721 | val 0.66723
  Epoch 016 - train 0.47905 | val 0.68097
  Regression -> MSE: 0.000216, MAE: 0.011046, R²: -0.0183
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.41785 | val 0.45089
  Epoch 016 - train 0.41950 | val 0.43326
  Regression -> MSE: 0.000097, MAE: 0.008189, R²: -0.0589
  Directional -> Accuracy: 0.5179, MCC: -0.0587, F1: 0.6582

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.53153 | val 0.55867
  Epoch 016 - train 0.50978 | val 0.78355
  Regression -> MSE: 0.000124, MAE: 0.009474, R²: -0.2012
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.48676 | val 0.50253
  Epoch 016 - train 0.47274 | val 0.56251
  Regression -> MSE: 0.000236, MAE: 0.012714, R²: -0.0217
  Directional -> Accuracy: 0.5116, MCC: 0.0680, F1: 0.4878

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.45728 | val 0.63731
  Epoch 016 - train 0.44110 | val 0.63636
  Regression -> MSE: 0.000174, MAE: 0.007890, R²: -0.0462
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.50065 | val 0.37606
  Epoch 016 - train 0.48839 | val 0.50233
  Regression -> MSE: 0.000237, MAE: 0.011875, R²: -0.0016
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.48036 | val 1.04488
  Epoch 016 - train 0.46620 | val 1.05816
  Regression -> MSE: 0.000234, MAE: 0.010128, R²: -0.0156
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.46286 | val 0.66762
  Epoch 016 - train 0.45161 | val 0.67473
  Regression -> MSE: 0.000135, MAE: 0.008233, R²: -0.0018
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.43059 | val 0.72000
  Epoch 016 - train 0.43966 | val 0.73732
  Regression -> MSE: 0.000193, MAE: 0.010457, R²: -0.0231
  Directional -> Accuracy: 0.5000, MCC: 0.0164, F1: 0.4681

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.38962 | val 0.73006
  Epoch 016 - train 0.39067 | val 0.72556
  Regression -> MSE: 0.000269, MAE: 0.010602, R²: -0.0286
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.46891 | val 0.39558
  Epoch 016 - train 0.47333 | val 0.42476
  Regression -> MSE: 0.000168, MAE: 0.010381, R²: -0.0091
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.41776 | val 0.50191
  Epoch 020 - train 0.41134 | val 0.50156
  Regression -> MSE: 0.000185, MAE: 0.010536, R²: -0.0292
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.44900 | val 0.46313
  Epoch 016 - train 0.43817 | val 0.45316
  Regression -> MSE: 0.000351, MAE: 0.012408, R²: -0.0236
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.48047 | val 0.23954
  Epoch 020 - train 0.46134 | val 0.22375
  Regression -> MSE: 0.000114, MAE: 0.008064, R²: -0.0833
  Directional -> Accuracy: 0.5581, MCC: 0.1140, F1: 0.5957

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.47635 | val 0.78585
  Epoch 020 - train 0.46519 | val 0.79064
  Regression -> MSE: 0.000272, MAE: 0.012687, R²: -0.2423
  Directional -> Accuracy: 0.4912, MCC: -0.1809, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.46709 | val 1.11883
  Epoch 020 - train 0.45383 | val 1.14206
  Regression -> MSE: 0.000100, MAE: 0.007823, R²: -0.2859
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.46047 | val 0.29956
  Epoch 020 - train 0.46557 | val 0.27993
  Regression -> MSE: 0.000322, MAE: 0.013880, R²: -0.0465
  Directional -> Accuracy: 0.4898, MCC: -0.2071, F1: 0.1379

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.52875 | val 0.19900
  Epoch 016 - train 0.51788 | val 0.21460
  Regression -> MSE: 0.000247, MAE: 0.011492, R²: -0.0128
  Directional -> Accuracy: 0.5263, MCC: 0.0358, F1: 0.6087

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.41537 | val 0.57928
  Epoch 020 - train 0.41231 | val 0.60044
  Regression -> MSE: 0.000083, MAE: 0.007191, R²: -0.0291
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.49965 | val 0.81353
  Epoch 016 - train 0.50448 | val 0.86264
  Regression -> MSE: 0.000315, MAE: 0.014521, R²: -0.0282
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.43971 | val 0.55831
  Epoch 020 - train 0.42761 | val 0.54844
  Regression -> MSE: 0.000099, MAE: 0.007200, R²: -0.0090
  Directional -> Accuracy: 0.6136, MCC: 0.2503, F1: 0.7463

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.51421 | val 0.74377
  Epoch 016 - train 0.51903 | val 0.75424
  Regression -> MSE: 0.000172, MAE: 0.009466, R²: -0.0037
  Directional -> Accuracy: 0.6122, MCC: 0.0861, F1: 0.2400

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.43198 | val 0.69654
  Epoch 016 - train 0.41353 | val 0.72466
  Regression -> MSE: 0.000225, MAE: 0.011829, R²: -0.0085
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.44436 | val 0.66190
  Epoch 016 - train 0.43461 | val 0.67576
  Regression -> MSE: 0.000095, MAE: 0.007861, R²: -0.0330
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.52040 | val 1.04545
  Epoch 016 - train 0.50238 | val 1.08666
  Regression -> MSE: 0.000164, MAE: 0.010269, R²: -0.0021
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.44273 | val 1.01194
  Epoch 016 - train 0.44378 | val 0.99376
  Regression -> MSE: 0.000116, MAE: 0.008821, R²: -0.0019
  Directional -> Accuracy: 0.5714, MCC: 0.2466, F1: 0.7073

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.50850 | val 0.95710

[I 2026-02-22 21:28:20,741] Trial 32 finished with value: -0.01150924198650869 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.1, 'dropout': 0.0, 'batch_size': 32, 'learning_rate': 6.011181825567894e-06, 'weight_decay': 6.522328312578788e-07, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 1.6181754361373821, 'early_stopping_min_delta': 0.007572829780882644}. Best is trial 31 with value: -0.011425014985750452.

  Epoch 016 - train 0.49825 | val 0.96100
  Regression -> MSE: 0.000239, MAE: 0.012287, R²: -0.0073
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: regression
Sequence length: 12
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.45359 | val 0.78887
  Epoch 018 - train 0.44783 | val 0.78329
  Regression -> MSE: 0.000249, MAE: 0.012672, R²: -0.0160
  Directional -> Accuracy: 0.4231, MCC: -0.1154, F1: 0.5455

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 88). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.49620 | val 0.54046
  Epoch 016 - train 0.49103 | val 0.56884
  Regression -> MSE: 0.000694, MAE: 0.019715, R²: -0.0040
  Directional -> Accuracy: 0.5532, MCC: 0.0000, F1: 0.7123

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 88). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.47309 | val 0.89473
  Epoch 016 - train 0.44645 | val 0.91730
  Regression -> MSE: 0.000344, MAE: 0.015072, R²: 0.0040
  Directional -> Accuracy: 0.5417, MCC: 0.0000, F1: 0.7027

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.38347 | val 0.41430
  Epoch 016 - train 0.36608 | val 0.40715
  Regression -> MSE: 0.000351, MAE: 0.014536, R²: -0.0190
  Directional -> Accuracy: 0.5132, MCC: -0.1519, F1: 0.6783

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.44686 | val 0.49006
  Epoch 016 - train 0.44115 | val 0.53761
  Regression -> MSE: 0.000203, MAE: 0.010229, R²: -0.0131
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.45930 | val 1.07692
  Epoch 016 - train 0.44357 | val 1.16535
  Regression -> MSE: 0.000581, MAE: 0.018450, R²: -0.0153
  Directional -> Accuracy: 0.4898, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.46001 | val 0.62680
  Epoch 016 - train 0.45608 | val 0.62146
  Regression -> MSE: 0.000247, MAE: 0.012038, R²: -0.0061
  Directional -> Accuracy: 0.6000, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 88). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 88). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.43118 | val 0.87575
  Epoch 016 - train 0.43028 | val 1.21815
  Regression -> MSE: 0.000629, MAE: 0.019703, R²: -0.0751
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.43903 | val 0.77722
  Epoch 016 - train 0.44733 | val 0.82528
  Regression -> MSE: 0.000339, MAE: 0.015220, R²: -0.0039
  Directional -> Accuracy: 0.3810, MCC: 0.0000, F1: 0.5517

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 88). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 88). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.49347 | val 0.64174
  Epoch 016 - train 0.47634 | val 0.64246
  Regression -> MSE: 0.000247, MAE: 0.011669, R²: -0.0364
  Directional -> Accuracy: 0.5634, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.43300 | val 0.85321
  Epoch 016 - train 0.42611 | val 0.99180
  Regression -> MSE: 0.000309, MAE: 0.013509, R²: -0.0104
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.49430 | val 0.57837
  Epoch 016 - train 0.50139 | val 0.58500
  Regression -> MSE: 0.000680, MAE: 0.019749, R²: -0.0164
  Directional -> Accuracy: 0.5085, MCC: 0.0000, F1: 0.6742

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.46435 | val 0.46077
  Epoch 016 - train 0.47543 | val 0.47359
  Regression -> MSE: 0.000150, MAE: 0.009551, R²: -0.0014
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 88). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.40429 | val 0.63667
  Epoch 020 - train 0.40856 | val 0.63253
  Regression -> MSE: 0.000224, MAE: 0.010709, R²: 0.0047
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.3673

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.43816 | val 1.27943
  Epoch 016 - train 0.44473 | val 1.29787
  Regression -> MSE: 0.000377, MAE: 0.016371, R²: -0.0035
  Directional -> Accuracy: 0.4717, MCC: 0.0000, F1: 0.6410

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.46385 | val 0.50187
  Epoch 016 - train 0.44243 | val 0.50499
  Regression -> MSE: 0.000108, MAE: 0.007852, R²: -0.0158
  Directional -> Accuracy: 0.5352, MCC: 0.0000, F1: 0.6972

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.42680 | val 1.05289
  Epoch 016 - train 0.42318 | val 1.07822
  Regression -> MSE: 0.000162, MAE: 0.010165, R²: -0.0121
  Directional -> Accuracy: 0.6333, MCC: 0.1337, F1: 0.7660

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.43353 | val 0.59090
  Epoch 016 - train 0.42263 | val 0.59616
  Regression -> MSE: 0.000269, MAE: 0.012909, R²: -0.0006
  Directional -> Accuracy: 0.6104, MCC: 0.0000, F1: 0.7581

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.36989 | val 0.68758
  Epoch 016 - train 0.36632 | val 0.68323
  Regression -> MSE: 0.000170, MAE: 0.009174, R²: -0.1527
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 88). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.47087 | val 0.88735
  Epoch 016 - train 0.46702 | val 0.88223
  Regression -> MSE: 0.000246, MAE: 0.011237, R²: -0.0843
  Directional -> Accuracy: 0.4605, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.51898 | val 0.97506
  Epoch 016 - train 0.51664 | val 1.14382
  Regression -> MSE: 0.000149, MAE: 0.008590, R²: -0.0078
  Directional -> Accuracy: 0.6327, MCC: 0.0000, F1: 0.7750

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 88). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 88). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 88). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.41820 | val 0.55748
  Epoch 016 - train 0.41613 | val 0.55945
  Regression -> MSE: 0.000178, MAE: 0.010996, R²: -0.0043
  Directional -> Accuracy: 0.5075, MCC: 0.0000, F1: 0.6733

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.51614 | val 0.67214
  Epoch 016 - train 0.49713 | val 0.65645
  Regression -> MSE: 0.000089, MAE: 0.007262, R²: -0.0654
  Directional -> Accuracy: 0.4237, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.48670 | val 0.62535
  Epoch 016 - train 0.48220 | val 0.62263
  Regression -> MSE: 0.000223, MAE: 0.011296, R²: -0.0217
  Directional -> Accuracy: 0.5224, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.39044 | val 0.32400
  Epoch 016 - train 0.38250 | val 0.32217
  Regression -> MSE: 0.000095, MAE: 0.008150, R²: -0.0366
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.45710 | val 0.19886
  Epoch 016 - train 0.45501 | val 0.20392
  Regression -> MSE: 0.000133, MAE: 0.009526, R²: -0.0602
  Directional -> Accuracy: 0.4167, MCC: 0.0000, F1: 0.5882

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.47512 | val 0.45482
  Epoch 016 - train 0.48564 | val 0.43923
  Regression -> MSE: 0.000239, MAE: 0.012801, R²: -0.0056
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.7429

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.51132 | val 0.71511
  Epoch 016 - train 0.50798 | val 0.71472
  Regression -> MSE: 0.000166, MAE: 0.007760, R²: -0.0158
  Directional -> Accuracy: 0.5517, MCC: 0.0000, F1: 0.7111

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.46500 | val 0.26017
  Epoch 020 - train 0.46539 | val 0.23193
  Regression -> MSE: 0.000241, MAE: 0.012134, R²: -0.0303
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.46974 | val 0.94255
  Epoch 016 - train 0.46852 | val 1.13503
  Regression -> MSE: 0.000250, MAE: 0.010502, R²: -0.0011
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.46995 | val 0.69816
  Epoch 020 - train 0.45566 | val 0.71661
  Regression -> MSE: 0.000142, MAE: 0.008286, R²: -0.0699
  Directional -> Accuracy: 0.5778, MCC: 0.1890, F1: 0.5128

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.49305 | val 0.64657
  Epoch 016 - train 0.48605 | val 0.65092
  Regression -> MSE: 0.000200, MAE: 0.010791, R²: -0.0620
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.43063 | val 0.69606
  Epoch 016 - train 0.41703 | val 0.68901
  Regression -> MSE: 0.000260, MAE: 0.010469, R²: -0.0080
  Directional -> Accuracy: 0.5676, MCC: 0.0000, F1: 0.7241

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 88). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.45844 | val 0.45630
  Epoch 016 - train 0.43560 | val 0.57466
  Regression -> MSE: 0.000167, MAE: 0.010222, R²: -0.0270
  Directional -> Accuracy: 0.4872, MCC: 0.0000, F1: 0.6552

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.39457 | val 0.61904
  Epoch 016 - train 0.38891 | val 0.63056
  Regression -> MSE: 0.000182, MAE: 0.010428, R²: 0.0049
  Directional -> Accuracy: 0.5111, MCC: 0.1357, F1: 0.6452

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.44194 | val 0.40936
  Epoch 016 - train 0.43257 | val 0.41051
  Regression -> MSE: 0.000358, MAE: 0.012737, R²: -0.0269
  Directional -> Accuracy: 0.4265, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.51539 | val 0.28437
  Epoch 016 - train 0.49801 | val 0.36180
  Regression -> MSE: 0.000117, MAE: 0.008250, R²: -0.1239
  Directional -> Accuracy: 0.5455, MCC: 0.1581, F1: 0.2308

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.47120 | val 0.91833
  Epoch 016 - train 0.46265 | val 0.97273
  Regression -> MSE: 0.000217, MAE: 0.011286, R²: -0.0112
  Directional -> Accuracy: 0.4828, MCC: 0.1236, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.45215 | val 1.01379
  Epoch 016 - train 0.45214 | val 1.00863
  Regression -> MSE: 0.000089, MAE: 0.007406, R²: -0.1250
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 88). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 88). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 88). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 88). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.47381 | val 0.29385
  Epoch 016 - train 0.45638 | val 0.30227
  Regression -> MSE: 0.000329, MAE: 0.014066, R²: -0.0034
  Directional -> Accuracy: 0.6500, MCC: 0.0000, F1: 0.0000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 88). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.49212 | val 0.24746
  Epoch 016 - train 0.46971 | val 0.25054
  Regression -> MSE: 0.000251, MAE: 0.011175, R²: -0.0541
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.7000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 88). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 88). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.42750 | val 0.56803
  Epoch 020 - train 0.41319 | val 0.57111
  Regression -> MSE: 0.000083, MAE: 0.007039, R²: -0.0390
  Directional -> Accuracy: 0.5132, MCC: 0.0676, F1: 0.0976

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 88). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 88). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 88). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.49545 | val 0.89655
  Epoch 016 - train 0.49508 | val 1.25785
  Regression -> MSE: 0.000372, MAE: 0.015385, R²: -0.0347
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.46560 | val 0.58039
  Epoch 020 - train 0.45792 | val 0.54036
  Regression -> MSE: 0.000098, MAE: 0.007273, R²: -0.0129
  Directional -> Accuracy: 0.4444, MCC: -0.1435, F1: 0.5283

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.48974 | val 0.77338
  Epoch 016 - train 0.47169 | val 0.79285
  Regression -> MSE: 0.000182, MAE: 0.010251, R²: -0.0040
  Directional -> Accuracy: 0.3659, MCC: 0.0000, F1: 0.5357

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.40471 | val 0.68504
  Epoch 016 - train 0.40487 | val 0.68771
  Regression -> MSE: 0.000221, MAE: 0.011643, R²: -0.0063
  Directional -> Accuracy: 0.5965, MCC: 0.2771, F1: 0.4889

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.44862 | val 0.68768
  Epoch 016 - train 0.45766 | val 0.69199
  Regression -> MSE: 0.000097, MAE: 0.007934, R²: -0.0582
  Directional -> Accuracy: 0.4828, MCC: 0.0000, F1: 0.6512

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.49359 | val 0.86082
  Epoch 020 - train 0.47693 | val 0.86135
  Regression -> MSE: 0.000166, MAE: 0.010336, R²: -0.0351
  Directional -> Accuracy: 0.4182, MCC: -0.1547, F1: 0.3043

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.44299 | val 0.67641
  Epoch 016 - train 0.43489 | val 0.68672
  Regression -> MSE: 0.000116, MAE: 0.008799, R²: -0.0179
  Directional -> Accuracy: 0.5263, MCC: 0.1360, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.48341 | val 0.81867

[I 2026-02-22 21:29:44,923] Trial 33 finished with value: -0.011511305725895876 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 12, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.0, 'dropout': 0.2, 'batch_size': 32, 'learning_rate': 2.505340173185501e-06, 'weight_decay': 2.1603583531127087e-07, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 1.4666866294075103, 'early_stopping_min_delta': 0.009877984499190435}. Best is trial 31 with value: -0.011425014985750452.

  Epoch 016 - train 0.45583 | val 0.82491
  Regression -> MSE: 0.000237, MAE: 0.012241, R²: -0.0133
  Directional -> Accuracy: 0.5161, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: regression
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.38816 | val 0.79183
  Epoch 016 - train 0.38491 | val 0.78323
  Regression -> MSE: 0.000246, MAE: 0.012522, R²: -0.0231
  Directional -> Accuracy: 0.4474, MCC: 0.0000, F1: 0.6182

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.40751 | val 0.50028
  Epoch 016 - train 0.38867 | val 0.49400
  Regression -> MSE: 0.000699, MAE: 0.019579, R²: -0.0014
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.41406 | val 0.87747
  Epoch 020 - train 0.40056 | val 0.88685
  Regression -> MSE: 0.000335, MAE: 0.014830, R²: -0.0664
  Directional -> Accuracy: 0.4565, MCC: -0.0767, F1: 0.3590

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.33395 | val 1.72538
  Epoch 016 - train 0.31932 | val 1.96321
  Regression -> MSE: 0.000355, MAE: 0.014711, R²: -0.0063
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.39341 | val 0.72386
  Epoch 017 - train 0.36814 | val 0.76627
  Regression -> MSE: 0.000207, MAE: 0.009924, R²: -0.0046
  Directional -> Accuracy: 0.6000, MCC: 0.1991, F1: 0.6667

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.35264 | val 1.15764
  Epoch 020 - train 0.34574 | val 1.41980
  Regression -> MSE: 0.000577, MAE: 0.018687, R²: -0.0199
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.39657 | val 0.84161
  Epoch 016 - train 0.37779 | val 0.86354
  Regression -> MSE: 0.000251, MAE: 0.011924, R²: -0.0130
  Directional -> Accuracy: 0.6029, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.41967 | val 0.32104
  Epoch 018 - train 0.38727 | val 0.46848
  Regression -> MSE: 0.000625, MAE: 0.019576, R²: -0.0236
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.38011 | val 0.87248
  Epoch 016 - train 0.37035 | val 0.92182
  Regression -> MSE: 0.000377, MAE: 0.015606, R²: -0.0107
  Directional -> Accuracy: 0.4792, MCC: 0.0115, F1: 0.5455

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.39172 | val 1.11885
  Epoch 016 - train 0.37890 | val 1.13703
  Regression -> MSE: 0.000243, MAE: 0.011964, R²: 0.0085
  Directional -> Accuracy: 0.5072, MCC: 0.1047, F1: 0.5750

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.37917 | val 1.12865
  Epoch 016 - train 0.35770 | val 1.15615
  Regression -> MSE: 0.000318, MAE: 0.013967, R²: -0.0170
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.44677 | val 0.80098
  Epoch 016 - train 0.44782 | val 0.76569
  Regression -> MSE: 0.000687, MAE: 0.019631, R²: -0.0017
  Directional -> Accuracy: 0.4912, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.38369 | val 0.88637
  Epoch 016 - train 0.37946 | val 1.04255
  Regression -> MSE: 0.000139, MAE: 0.009188, R²: -0.0083
  Directional -> Accuracy: 0.4762, MCC: 0.1419, F1: 0.6333

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.36121 | val 0.68130
  Epoch 016 - train 0.35031 | val 0.68607
  Regression -> MSE: 0.000227, MAE: 0.010726, R²: -0.0022
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.41279 | val 1.45377
  Epoch 016 - train 0.38741 | val 1.47650
  Regression -> MSE: 0.000375, MAE: 0.015921, R²: -0.0223
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.42696 | val 0.50688
  Epoch 016 - train 0.41284 | val 0.52801
  Regression -> MSE: 0.000111, MAE: 0.008198, R²: -0.0235
  Directional -> Accuracy: 0.4638, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.39427 | val 1.34693
  Epoch 016 - train 0.38888 | val 1.42750
  Regression -> MSE: 0.000159, MAE: 0.009643, R²: -0.0067
  Directional -> Accuracy: 0.6207, MCC: 0.0000, F1: 0.7660

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.39297 | val 0.75218
  Epoch 016 - train 0.39235 | val 0.92398
  Regression -> MSE: 0.000274, MAE: 0.013062, R²: -0.0013
  Directional -> Accuracy: 0.6000, MCC: 0.0000, F1: 0.7500

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.32954 | val 0.91391
  Epoch 017 - train 0.32332 | val 0.96630
  Regression -> MSE: 0.000173, MAE: 0.009327, R²: -0.1377
  Directional -> Accuracy: 0.4219, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.38066 | val 1.59219
  Epoch 016 - train 0.38027 | val 1.52668
  Regression -> MSE: 0.000273, MAE: 0.011911, R²: -0.2014
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.41062 | val 0.68442
  Epoch 019 - train 0.37792 | val 0.72053
  Regression -> MSE: 0.000141, MAE: 0.008642, R²: 0.0174
  Directional -> Accuracy: 0.5319, MCC: 0.0708, F1: 0.5769

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.38353 | val 0.74744
  Epoch 016 - train 0.38095 | val 0.79451
  Regression -> MSE: 0.000180, MAE: 0.010402, R²: -0.0883
  Directional -> Accuracy: 0.4923, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.40748 | val 0.72302
  Epoch 016 - train 0.41206 | val 0.71772
  Regression -> MSE: 0.000085, MAE: 0.007128, R²: 0.0156
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.40098 | val 0.65145
  Epoch 016 - train 0.38944 | val 0.65688
  Regression -> MSE: 0.000217, MAE: 0.010964, R²: -0.0286
  Directional -> Accuracy: 0.5231, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.33604 | val 0.38036
  Epoch 019 - train 0.32074 | val 0.40692
  Regression -> MSE: 0.000108, MAE: 0.008464, R²: -0.2041
  Directional -> Accuracy: 0.5455, MCC: 0.1826, F1: 0.3902

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.43630 | val 0.54190
  Epoch 016 - train 0.39246 | val 0.57516
  Regression -> MSE: 0.000112, MAE: 0.009059, R²: -0.1300
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.43887 | val 0.45237
  Epoch 020 - train 0.41014 | val 0.42530
  Regression -> MSE: 0.000237, MAE: 0.012601, R²: -0.0001
  Directional -> Accuracy: 0.5714, MCC: 0.0323, F1: 0.7188

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.38675 | val 0.56043
  Epoch 018 - train 0.37362 | val 0.57175
  Regression -> MSE: 0.000223, MAE: 0.009317, R²: -0.3151
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.44181 | val 0.73371
  Epoch 016 - train 0.41137 | val 0.83363
  Regression -> MSE: 0.000251, MAE: 0.012366, R²: -0.0382
  Directional -> Accuracy: 0.5500, MCC: 0.0000, F1: 0.7097

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.41254 | val 0.95577
  Epoch 016 - train 0.39581 | val 0.94367
  Regression -> MSE: 0.000236, MAE: 0.010098, R²: -0.0029
  Directional -> Accuracy: 0.4524, MCC: -0.1064, F1: 0.3784

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.45110 | val 0.65752
  Epoch 016 - train 0.43453 | val 0.64056
  Regression -> MSE: 0.000147, MAE: 0.008830, R²: -0.0694
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.37908 | val 0.71664
  Epoch 016 - train 0.37684 | val 0.72041
  Regression -> MSE: 0.000183, MAE: 0.010174, R²: -0.0016
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.33702 | val 0.58399
  Epoch 020 - train 0.32175 | val 0.58667
  Regression -> MSE: 0.000457, MAE: 0.015364, R²: -0.7226
  Directional -> Accuracy: 0.5139, MCC: 0.1147, F1: 0.3636

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.35667 | val 0.74737
  Epoch 016 - train 0.34990 | val 0.76839
  Regression -> MSE: 0.000192, MAE: 0.010707, R²: -0.0473
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.35738 | val 0.47119
  Epoch 018 - train 0.35356 | val 0.48678
  Regression -> MSE: 0.000353, MAE: 0.012801, R²: -0.0148
  Directional -> Accuracy: 0.4242, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.43924 | val 0.34090
  Epoch 016 - train 0.42903 | val 0.29627
  Regression -> MSE: 0.000133, MAE: 0.008641, R²: -0.2554
  Directional -> Accuracy: 0.4762, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.41168 | val 0.86939
  Epoch 016 - train 0.40566 | val 0.87904
  Regression -> MSE: 0.000220, MAE: 0.011309, R²: -0.0010
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.38517 | val 1.27937
  Epoch 016 - train 0.36797 | val 1.30798
  Regression -> MSE: 0.000081, MAE: 0.007051, R²: -0.1014
  Directional -> Accuracy: 0.3913, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.38509 | val 0.26822
  Epoch 020 - train 0.36097 | val 0.24331
  Regression -> MSE: 0.000810, MAE: 0.025330, R²: -1.6017
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.37171 | val 0.78150
  Epoch 016 - train 0.35962 | val 0.82377
  Regression -> MSE: 0.000086, MAE: 0.006982, R²: -0.0977
  Directional -> Accuracy: 0.5135, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.42878 | val 0.95793
  Epoch 018 - train 0.40309 | val 0.99457
  Regression -> MSE: 0.000303, MAE: 0.014466, R²: -0.0080
  Directional -> Accuracy: 0.5111, MCC: 0.0629, F1: 0.2143

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.42759 | val 0.51620
  Epoch 020 - train 0.36406 | val 0.52226
  Regression -> MSE: 0.000099, MAE: 0.006968, R²: 0.0268
  Directional -> Accuracy: 0.5952, MCC: 0.1680, F1: 0.6531

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.39965 | val 0.80439
  Epoch 016 - train 0.38413 | val 0.83568
  Regression -> MSE: 0.000176, MAE: 0.009799, R²: -0.0060
  Directional -> Accuracy: 0.5000, MCC: -0.1491, F1: 0.2000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.38576 | val 1.12822
  Epoch 016 - train 0.37781 | val 1.27154
  Regression -> MSE: 0.000224, MAE: 0.011766, R²: 0.0073
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.36676 | val 1.13339
  Epoch 016 - train 0.35776 | val 1.34185
  Regression -> MSE: 0.000095, MAE: 0.007775, R²: -0.0085
  Directional -> Accuracy: 0.4643, MCC: -0.2296, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.42975 | val 1.00937
  Epoch 016 - train 0.40666 | val 0.99492
  Regression -> MSE: 0.000172, MAE: 0.010461, R²: -0.0288
  Directional -> Accuracy: 0.4906, MCC: 0.0000, F1: 0.0000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.36685 | val 1.84365
  Epoch 016 - train 0.35805 | val 2.10782
  Regression -> MSE: 0.000125, MAE: 0.009128, R²: -0.0584
  Directional -> Accuracy: 0.4727, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.43643 | val 1.37001

[I 2026-02-22 21:33:19,716] Trial 34 finished with value: -0.011877671943278349 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.1, 'dropout': 0.0, 'batch_size': 16, 'learning_rate': 4.536672695356323e-05, 'weight_decay': 1.3930518551534e-06, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 1.3077151702854455, 'early_stopping_min_delta': 0.005758755539389768}. Best is trial 31 with value: -0.011425014985750452.

  Epoch 016 - train 0.42043 | val 1.61755
  Regression -> MSE: 0.000253, MAE: 0.012636, R²: -0.0523
  Directional -> Accuracy: 0.5167, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 12
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.42126 | val 0.84167
  Epoch 016 - train 0.43261 | val 0.86512
  Regression -> MSE: 0.000249, MAE: 0.012633, R²: -0.0124
  Directional -> Accuracy: 0.4487, MCC: 0.0000, F1: 0.6195

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 88). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.44713 | val 0.42496
  Epoch 016 - train 0.43044 | val 0.43404
  Regression -> MSE: 0.000698, MAE: 0.019717, R²: -0.0099
  Directional -> Accuracy: 0.5745, MCC: 0.1155, F1: 0.7143

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 88). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.50806 | val 0.95959
  Epoch 016 - train 0.49686 | val 0.96786
  Regression -> MSE: 0.000346, MAE: 0.015145, R²: -0.0026
  Directional -> Accuracy: 0.5417, MCC: 0.0000, F1: 0.7027

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.38033 | val 0.44072
  Epoch 016 - train 0.36996 | val 0.47598
  Regression -> MSE: 0.000345, MAE: 0.014457, R²: -0.0007
  Directional -> Accuracy: 0.5395, MCC: 0.0000, F1: 0.7009

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.46315 | val 0.42142
  Epoch 020 - train 0.47844 | val 0.39689
  Epoch 030 - train 0.43926 | val 0.38364
  Epoch 040 - train 0.40093 | val 0.38306
  Epoch 050 - train 0.42364 | val 0.37795
  Regression -> MSE: 0.000189, MAE: 0.008995, R²: 0.0572
  Directional -> Accuracy: 0.6923, MCC: 0.3784, F1: 0.7241

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.47370 | val 1.07077
  Epoch 020 - train 0.50781 | val 1.06753
  Epoch 030 - train 0.44404 | val 1.07896
  Epoch 033 - train 0.46657 | val 1.08833
  Regression -> MSE: 0.000588, MAE: 0.018561, R²: -0.0270
  Directional -> Accuracy: 0.4694, MCC: -0.0589, F1: 0.4348

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.47338 | val 0.72952
  Epoch 016 - train 0.47504 | val 0.73148
  Regression -> MSE: 0.000249, MAE: 0.011973, R²: -0.0125
  Directional -> Accuracy: 0.6000, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 88). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 88). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.48317 | val 0.62688
  Epoch 020 - train 0.46752 | val 0.58596
  Epoch 030 - train 0.45216 | val 0.59618
  Epoch 034 - train 0.44593 | val 0.60252
  Regression -> MSE: 0.000582, MAE: 0.018551, R²: 0.0043
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.45817 | val 0.75968
  Epoch 020 - train 0.43938 | val 0.77781
  Epoch 026 - train 0.45229 | val 0.78808
  Regression -> MSE: 0.000351, MAE: 0.015874, R²: -0.0393
  Directional -> Accuracy: 0.3810, MCC: 0.0000, F1: 0.5517

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 88). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 88). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.48153 | val 0.75113
  Epoch 016 - train 0.45756 | val 0.79006
  Regression -> MSE: 0.000241, MAE: 0.011546, R²: -0.0136
  Directional -> Accuracy: 0.5634, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.41735 | val 0.84483
  Epoch 016 - train 0.42214 | val 0.88537
  Regression -> MSE: 0.000307, MAE: 0.013562, R²: -0.0026
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.6400

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.48187 | val 0.62436
  Epoch 016 - train 0.46875 | val 0.68667
  Regression -> MSE: 0.000669, MAE: 0.019433, R²: 0.0002
  Directional -> Accuracy: 0.5085, MCC: 0.0000, F1: 0.6742

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.47626 | val 0.44976
  Epoch 020 - train 0.47690 | val 0.52802
  Regression -> MSE: 0.000154, MAE: 0.009798, R²: -0.0245
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 88). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.40807 | val 0.72141
  Epoch 016 - train 0.41867 | val 0.74560
  Regression -> MSE: 0.000227, MAE: 0.010798, R²: -0.0086
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.46568 | val 1.34530
  Epoch 016 - train 0.45359 | val 1.39633
  Regression -> MSE: 0.000379, MAE: 0.016355, R²: -0.0094
  Directional -> Accuracy: 0.5094, MCC: 0.0244, F1: 0.5185

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.47513 | val 0.50061
  Epoch 020 - train 0.46458 | val 0.51782
  Epoch 022 - train 0.46799 | val 0.52063
  Regression -> MSE: 0.000105, MAE: 0.007925, R²: 0.0153
  Directional -> Accuracy: 0.5493, MCC: 0.1942, F1: 0.3600

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.42920 | val 1.02052
  Epoch 020 - train 0.42952 | val 1.02041
  Epoch 028 - train 0.43115 | val 1.02035
  Regression -> MSE: 0.000164, MAE: 0.010084, R²: -0.0211
  Directional -> Accuracy: 0.5333, MCC: 0.1914, F1: 0.4815

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.44851 | val 0.43433
  Epoch 019 - train 0.45120 | val 0.45185
  Regression -> MSE: 0.000270, MAE: 0.012820, R²: -0.0055
  Directional -> Accuracy: 0.6104, MCC: 0.0000, F1: 0.7581

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.37835 | val 0.72752
  Epoch 020 - train 0.39468 | val 0.70272
  Epoch 030 - train 0.37577 | val 0.69203
  Epoch 040 - train 0.38348 | val 0.67904
  Epoch 050 - train 0.38066 | val 0.67368
  Regression -> MSE: 0.000194, MAE: 0.009921, R²: -0.3153
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 88). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.47152 | val 0.94701
  Epoch 016 - train 0.47909 | val 0.94456
  Regression -> MSE: 0.000239, MAE: 0.011051, R²: -0.0529
  Directional -> Accuracy: 0.4605, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.48042 | val 0.62456
  Epoch 020 - train 0.47536 | val 0.60436
  Epoch 030 - train 0.46775 | val 0.60497
  Epoch 040 - train 0.45851 | val 0.60309
  Regression -> MSE: 0.000157, MAE: 0.009214, R²: -0.0569
  Directional -> Accuracy: 0.4490, MCC: -0.0782, F1: 0.4906

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 88). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 88). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 88). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.43375 | val 0.57976
  Epoch 016 - train 0.42427 | val 0.59524
  Regression -> MSE: 0.000178, MAE: 0.010646, R²: -0.0052
  Directional -> Accuracy: 0.5075, MCC: 0.0000, F1: 0.6733

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.54091 | val 0.65941
  Epoch 016 - train 0.55627 | val 0.65593
  Regression -> MSE: 0.000091, MAE: 0.007364, R²: -0.0919
  Directional -> Accuracy: 0.4237, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.45445 | val 1.17779
  Epoch 018 - train 0.45122 | val 1.43547
  Regression -> MSE: 0.000219, MAE: 0.011302, R²: -0.0001
  Directional -> Accuracy: 0.5224, MCC: 0.0769, F1: 0.6098

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.40062 | val 0.32181
  Epoch 020 - train 0.38841 | val 0.33633
  Epoch 022 - train 0.41226 | val 0.33818
  Regression -> MSE: 0.000093, MAE: 0.007940, R²: -0.0113
  Directional -> Accuracy: 0.5614, MCC: 0.1400, F1: 0.5614

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.50042 | val 0.20746
  Epoch 016 - train 0.46725 | val 0.21057
  Regression -> MSE: 0.000127, MAE: 0.009271, R²: -0.0114
  Directional -> Accuracy: 0.5833, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.50361 | val 0.40565
  Epoch 016 - train 0.48081 | val 0.46691
  Regression -> MSE: 0.000250, MAE: 0.013146, R²: -0.0510
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.45267 | val 0.59606
  Epoch 020 - train 0.44012 | val 0.59759
  Epoch 022 - train 0.44008 | val 0.59445
  Regression -> MSE: 0.000184, MAE: 0.007959, R²: -0.1212
  Directional -> Accuracy: 0.5345, MCC: 0.1948, F1: 0.3415

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.51751 | val 0.29172
  Epoch 016 - train 0.51752 | val 0.29713
  Regression -> MSE: 0.000242, MAE: 0.012174, R²: -0.0316
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.51186 | val 0.78195
  Epoch 020 - train 0.53709 | val 0.75951
  Epoch 030 - train 0.54399 | val 0.76695
  Epoch 032 - train 0.51708 | val 0.76424
  Regression -> MSE: 0.000273, MAE: 0.011015, R²: -0.0897
  Directional -> Accuracy: 0.4889, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.47227 | val 0.74145
  Epoch 016 - train 0.46974 | val 0.75317
  Regression -> MSE: 0.000134, MAE: 0.008260, R²: -0.0102
  Directional -> Accuracy: 0.4444, MCC: -0.0945, F1: 0.3590

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.49892 | val 0.67668
  Epoch 016 - train 0.46765 | val 0.70532
  Regression -> MSE: 0.000195, MAE: 0.010600, R²: -0.0332
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.38725 | val 0.63826
  Epoch 016 - train 0.39204 | val 0.63924
  Regression -> MSE: 0.000272, MAE: 0.010727, R²: -0.0529
  Directional -> Accuracy: 0.4324, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 88). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.45602 | val 0.35731
  Epoch 020 - train 0.47213 | val 0.35262
  Epoch 030 - train 0.43452 | val 0.36302
  Regression -> MSE: 0.000160, MAE: 0.010125, R²: 0.0133
  Directional -> Accuracy: 0.5385, MCC: 0.0829, F1: 0.5714

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.42003 | val 0.52564
  Epoch 016 - train 0.39170 | val 0.56393
  Regression -> MSE: 0.000183, MAE: 0.010473, R²: -0.0019
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.6364

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.42860 | val 0.38021
  Epoch 020 - train 0.42854 | val 0.37745
  Epoch 028 - train 0.40911 | val 0.38330
  Regression -> MSE: 0.000457, MAE: 0.016307, R²: -0.3085
  Directional -> Accuracy: 0.4265, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.52529 | val 0.26420
  Epoch 020 - train 0.49859 | val 0.25793
  Epoch 028 - train 0.51149 | val 0.25817
  Regression -> MSE: 0.000122, MAE: 0.008512, R²: -0.1794
  Directional -> Accuracy: 0.4091, MCC: -0.1849, F1: 0.3500

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.48537 | val 0.79002
  Epoch 020 - train 0.47238 | val 0.76139
  Epoch 030 - train 0.46721 | val 0.75294
  Epoch 040 - train 0.45028 | val 0.75030
  Epoch 050 - train 0.46091 | val 0.75060
  Regression -> MSE: 0.000237, MAE: 0.011798, R²: -0.1020
  Directional -> Accuracy: 0.4655, MCC: -0.0540, F1: 0.5079

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.47114 | val 1.07306
  Epoch 016 - train 0.46294 | val 1.08727
  Regression -> MSE: 0.000095, MAE: 0.007636, R²: -0.1882
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 88). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 88). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 88). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 88). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.47914 | val 0.34321
  Epoch 016 - train 0.46608 | val 0.33912
  Regression -> MSE: 0.000345, MAE: 0.015553, R²: -0.0507
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 88). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.47815 | val 0.22181
  Epoch 016 - train 0.45750 | val 0.22276
  Regression -> MSE: 0.000243, MAE: 0.011252, R²: -0.0208
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.7000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 88). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 88). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.44581 | val 0.59448
  Epoch 020 - train 0.43320 | val 0.60610
  Epoch 022 - train 0.42270 | val 0.60739
  Regression -> MSE: 0.000078, MAE: 0.006965, R²: 0.0224
  Directional -> Accuracy: 0.5263, MCC: 0.1179, F1: 0.6727

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 88). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 88). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 88). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.49620 | val 0.47347
  Epoch 020 - train 0.46795 | val 0.54196
  Epoch 025 - train 0.47972 | val 0.55269
  Regression -> MSE: 0.000366, MAE: 0.015501, R²: -0.0179
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.44357 | val 0.59952
  Epoch 016 - train 0.45793 | val 0.61150
  Regression -> MSE: 0.000098, MAE: 0.007153, R²: -0.0165
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.47556 | val 0.80771
  Epoch 016 - train 0.49767 | val 0.85800
  Regression -> MSE: 0.000183, MAE: 0.010463, R²: -0.0145
  Directional -> Accuracy: 0.3659, MCC: 0.0000, F1: 0.5357

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.42776 | val 0.66381
  Epoch 016 - train 0.42719 | val 0.75403
  Regression -> MSE: 0.000219, MAE: 0.011629, R²: 0.0012
  Directional -> Accuracy: 0.5439, MCC: 0.0000, F1: 0.7045

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.51632 | val 0.71939
  Epoch 016 - train 0.48871 | val 0.78632
  Regression -> MSE: 0.000096, MAE: 0.007932, R²: -0.0548
  Directional -> Accuracy: 0.4828, MCC: 0.0000, F1: 0.6512

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.46281 | val 0.93263
  Epoch 020 - train 0.44985 | val 0.94491
  Epoch 025 - train 0.45786 | val 0.95154
  Regression -> MSE: 0.000163, MAE: 0.010038, R²: -0.0126
  Directional -> Accuracy: 0.5455, MCC: 0.0728, F1: 0.6575

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.45493 | val 0.64629
  Epoch 016 - train 0.46578 | val 0.64923
  Regression -> MSE: 0.000125, MAE: 0.008909, R²: -0.0927
  Directional -> Accuracy: 0.4912, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.50290 | val 0.95469

[I 2026-02-22 21:35:25,398] Trial 35 finished with value: -0.011625958052578982 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 12, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.1, 'batch_size': 32, 'learning_rate': 9.478335806114918e-06, 'weight_decay': 2.7848161151204444e-06, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 1.6424192389241012, 'early_stopping_min_delta': 0.00372876261188568}. Best is trial 31 with value: -0.011425014985750452.

  Epoch 016 - train 0.49958 | val 0.99236
  Regression -> MSE: 0.000236, MAE: 0.012234, R²: -0.0112
  Directional -> Accuracy: 0.5161, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.46713 | val 0.82074
  Epoch 016 - train 0.45954 | val 0.82072
  Regression -> MSE: 0.000248, MAE: 0.012291, R²: -0.0020
  Directional -> Accuracy: 0.5584, MCC: 0.1732, F1: 0.6222

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.48122 | val 0.45835
  Epoch 020 - train 0.47794 | val 0.45406
  Regression -> MSE: 0.000777, MAE: 0.020366, R²: -0.1351
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.49565 | val 1.14222
  Epoch 011 - train 0.50566 | val 1.14919
  Regression -> MSE: 0.000320, MAE: 0.014537, R²: -0.0329
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.44369 | val 0.65497
  Epoch 011 - train 0.42106 | val 0.65278
  Regression -> MSE: 0.000353, MAE: 0.014622, R²: -0.0103
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.47992 | val 0.44052
  Epoch 020 - train 0.47297 | val 0.43609
  Regression -> MSE: 0.000216, MAE: 0.010820, R²: -0.0608
  Directional -> Accuracy: 0.5686, MCC: 0.1775, F1: 0.4762

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.47564 | val 1.39790
  Epoch 011 - train 0.47294 | val 1.44182
  Regression -> MSE: 0.000560, MAE: 0.018219, R²: -0.0088
  Directional -> Accuracy: 0.4255, MCC: -0.1515, F1: 0.5091

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.46483 | val 0.68319
  Epoch 011 - train 0.46994 | val 0.68321
  Regression -> MSE: 0.000244, MAE: 0.012195, R²: 0.0050
  Directional -> Accuracy: 0.4203, MCC: 0.1002, F1: 0.5833

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.50468 | val 0.65217
  Epoch 017 - train 0.48556 | val 0.76191
  Regression -> MSE: 0.000612, MAE: 0.019396, R²: -0.0251
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.50395 | val 0.69974
  Epoch 011 - train 0.48950 | val 0.71715
  Regression -> MSE: 0.000444, MAE: 0.016796, R²: -0.1587
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.48905 | val 0.85340
  Epoch 011 - train 0.47178 | val 0.85173
  Regression -> MSE: 0.000242, MAE: 0.011972, R²: -0.0009
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.45768 | val 0.79010
  Epoch 017 - train 0.44599 | val 0.79429
  Regression -> MSE: 0.000380, MAE: 0.014242, R²: -0.2225
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.53882 | val 0.73202
  Epoch 011 - train 0.53123 | val 0.73436
  Regression -> MSE: 0.000684, MAE: 0.019582, R²: -0.0097
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.52314 | val 0.56984
  Epoch 011 - train 0.51690 | val 0.57031
  Regression -> MSE: 0.000144, MAE: 0.009346, R²: -0.0451
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.43965 | val 0.69922
  Epoch 018 - train 0.43101 | val 0.69895
  Regression -> MSE: 0.000240, MAE: 0.011346, R²: -0.0666
  Directional -> Accuracy: 0.5574, MCC: 0.1470, F1: 0.4000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.52787 | val 1.90474
  Epoch 011 - train 0.51552 | val 1.93431
  Regression -> MSE: 0.000362, MAE: 0.015993, R²: 0.0015
  Directional -> Accuracy: 0.5192, MCC: 0.0356, F1: 0.4898

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.53875 | val 0.54447
  Epoch 011 - train 0.52661 | val 0.54440
  Regression -> MSE: 0.000106, MAE: 0.007941, R²: 0.0206
  Directional -> Accuracy: 0.6286, MCC: 0.2442, F1: 0.6829

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.43826 | val 1.31875
  Epoch 011 - train 0.46604 | val 1.32073
  Regression -> MSE: 0.000156, MAE: 0.009837, R²: -0.0036
  Directional -> Accuracy: 0.6102, MCC: -0.1013, F1: 0.7579

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.50136 | val 0.62778
  Epoch 011 - train 0.47596 | val 0.62686
  Regression -> MSE: 0.000273, MAE: 0.013073, R²: -0.0025
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.40150 | val 0.76517
  Epoch 011 - train 0.39978 | val 0.76446
  Regression -> MSE: 0.000167, MAE: 0.009002, R²: -0.1147
  Directional -> Accuracy: 0.4308, MCC: -0.0760, F1: 0.3509

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.51240 | val 1.08055
  Epoch 011 - train 0.50385 | val 1.07891
  Regression -> MSE: 0.000226, MAE: 0.010739, R²: 0.0033
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.49384 | val 1.11235
  Epoch 011 - train 0.48802 | val 1.12343
  Regression -> MSE: 0.000144, MAE: 0.008322, R²: -0.0049
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.51003 | val 0.58488
  Epoch 011 - train 0.49441 | val 0.58503
  Regression -> MSE: 0.000182, MAE: 0.010387, R²: -0.1003
  Directional -> Accuracy: 0.5152, MCC: 0.0727, F1: 0.1111

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.50216 | val 0.71525
  Epoch 011 - train 0.50594 | val 0.71556
  Regression -> MSE: 0.000088, MAE: 0.007245, R²: -0.0376
  Directional -> Accuracy: 0.5000, MCC: 0.2369, F1: 0.2162

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.54931 | val 0.70583
  Epoch 015 - train 0.53367 | val 0.70294
  Regression -> MSE: 0.000215, MAE: 0.011254, R²: -0.0130
  Directional -> Accuracy: 0.4848, MCC: 0.0284, F1: 0.6222

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.46902 | val 0.50340
  Epoch 011 - train 0.47374 | val 0.50509
  Regression -> MSE: 0.000098, MAE: 0.008212, R²: -0.0681
  Directional -> Accuracy: 0.4286, MCC: -0.1476, F1: 0.4667

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.54768 | val 0.40947
  Epoch 011 - train 0.54985 | val 0.40985
  Regression -> MSE: 0.000111, MAE: 0.009131, R²: -0.0772
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.50077 | val 0.46227
  Epoch 013 - train 0.53332 | val 0.46178
  Regression -> MSE: 0.000231, MAE: 0.012501, R²: 0.0007
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.53260 | val 0.80557
  Epoch 011 - train 0.52546 | val 0.80925
  Regression -> MSE: 0.000172, MAE: 0.007861, R²: -0.0352
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.56973 | val 0.31649
  Epoch 011 - train 0.53509 | val 0.32254
  Regression -> MSE: 0.000235, MAE: 0.011852, R²: 0.0067
  Directional -> Accuracy: 0.5366, MCC: 0.0166, F1: 0.6885

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.48371 | val 1.12271
  Epoch 011 - train 0.46687 | val 1.13128
  Regression -> MSE: 0.000232, MAE: 0.009923, R²: -0.0050
  Directional -> Accuracy: 0.5814, MCC: 0.2280, F1: 0.6786

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.52040 | val 0.68357
  Epoch 020 - train 0.52974 | val 0.67696
  Epoch 024 - train 0.53182 | val 0.67739
  Regression -> MSE: 0.000142, MAE: 0.008418, R²: -0.0530
  Directional -> Accuracy: 0.5116, MCC: 0.0509, F1: 0.4324

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.50223 | val 0.69740
  Epoch 015 - train 0.50036 | val 0.70097
  Regression -> MSE: 0.000271, MAE: 0.013365, R²: -0.4379
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.44291 | val 0.68155
  Epoch 011 - train 0.44005 | val 0.68118
  Regression -> MSE: 0.000260, MAE: 0.010549, R²: 0.0085
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.47881 | val 0.41446
  Epoch 011 - train 0.50343 | val 0.42089
  Regression -> MSE: 0.000165, MAE: 0.010359, R²: 0.0085
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.48996 | val 0.58496
  Epoch 011 - train 0.47441 | val 0.58604
  Regression -> MSE: 0.000186, MAE: 0.010470, R²: -0.0312
  Directional -> Accuracy: 0.3409, MCC: -0.3240, F1: 0.2927

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.53549 | val 0.51719
  Epoch 011 - train 0.54248 | val 0.51767
  Regression -> MSE: 0.000366, MAE: 0.013286, R²: -0.0682
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.52021 | val 0.24116
  Epoch 011 - train 0.55373 | val 0.23895
  Regression -> MSE: 0.000120, MAE: 0.008516, R²: -0.1389
  Directional -> Accuracy: 0.3256, MCC: -0.3514, F1: 0.3556

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.51451 | val 0.84797
  Epoch 019 - train 0.50143 | val 0.84397
  Regression -> MSE: 0.000230, MAE: 0.011583, R²: -0.0532
  Directional -> Accuracy: 0.5439, MCC: 0.1235, F1: 0.6176

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.49632 | val 1.33458
  Epoch 011 - train 0.48349 | val 1.34097
  Regression -> MSE: 0.000090, MAE: 0.007407, R²: -0.1529
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.55780 | val 0.37043
  Epoch 011 - train 0.54948 | val 0.37532
  Regression -> MSE: 0.000344, MAE: 0.015522, R²: -0.1187
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.53130 | val 0.18866
  Epoch 018 - train 0.48513 | val 0.19332
  Regression -> MSE: 0.000256, MAE: 0.011896, R²: -0.0492
  Directional -> Accuracy: 0.4474, MCC: -0.1116, F1: 0.4878

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.54626 | val 0.72037
  Epoch 011 - train 0.55072 | val 0.71972
  Regression -> MSE: 0.000084, MAE: 0.007092, R²: -0.0360
  Directional -> Accuracy: 0.4933, MCC: -0.0201, F1: 0.3667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.50362 | val 0.62721
  Epoch 020 - train 0.49012 | val 0.62311
  Epoch 021 - train 0.49003 | val 0.62323
  Regression -> MSE: 0.000334, MAE: 0.014925, R²: -0.0873
  Directional -> Accuracy: 0.4894, MCC: -0.0111, F1: 0.2941

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.48167 | val 0.57594
  Epoch 020 - train 0.49268 | val 0.57366
  Epoch 021 - train 0.48901 | val 0.57364
  Regression -> MSE: 0.000107, MAE: 0.007189, R²: -0.0903
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.51981 | val 0.78836
  Epoch 011 - train 0.52455 | val 0.79312
  Regression -> MSE: 0.000174, MAE: 0.010046, R²: -0.0152
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.46049 | val 0.95184
  Epoch 011 - train 0.44305 | val 0.97482
  Regression -> MSE: 0.000236, MAE: 0.011967, R²: -0.0596
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.51778 | val 0.72600
  Epoch 011 - train 0.51926 | val 0.72569
  Regression -> MSE: 0.000093, MAE: 0.007674, R²: -0.0091
  Directional -> Accuracy: 0.4386, MCC: -0.1807, F1: 0.2000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.51343 | val 1.10184
  Epoch 011 - train 0.50672 | val 1.10873
  Regression -> MSE: 0.000164, MAE: 0.010284, R²: -0.0025
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.50231 | val 0.78414
  Epoch 011 - train 0.51387 | val 0.78703
  Regression -> MSE: 0.000136, MAE: 0.009189, R²: -0.1721
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...

[I 2026-02-22 21:35:56,259] Trial 36 finished with value: -0.011622566732302653 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.30000000000000004, 'batch_size': 32, 'learning_rate': 3.949157166210355e-06, 'weight_decay': 7.362781330772368e-06, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.822111087482365, 'early_stopping_min_delta': 0.005007952818272648}. Best is trial 31 with value: -0.011425014985750452.

  Epoch 010 - train 0.52463 | val 1.00492
  Epoch 011 - train 0.52118 | val 1.00605
  Regression -> MSE: 0.000236, MAE: 0.012391, R²: 0.0062
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.45064 | val 0.78495
  Epoch 020 - train 0.42803 | val 0.73914
  Regression -> MSE: 0.000259, MAE: 0.012829, R²: -0.0466
  Directional -> Accuracy: 0.5974, MCC: 0.1944, F1: 0.5753

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.46901 | val 0.46767
  Epoch 018 - train 0.43058 | val 0.52226
  Regression -> MSE: 0.000693, MAE: 0.019614, R²: -0.0121
  Directional -> Accuracy: 0.5000, MCC: -0.0488, F1: 0.5965

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.47463 | val 0.95928
  Epoch 016 - train 0.46938 | val 0.93113
  Regression -> MSE: 0.000313, MAE: 0.014466, R²: -0.0087
  Directional -> Accuracy: 0.5106, MCC: -0.0705, F1: 0.6667

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.36486 | val 0.51324
  Epoch 016 - train 0.37983 | val 0.67213
  Regression -> MSE: 0.000348, MAE: 0.014489, R²: 0.0043
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.43606 | val 0.40663
  Epoch 020 - train 0.42937 | val 0.42525
  Regression -> MSE: 0.000220, MAE: 0.010603, R²: -0.0802
  Directional -> Accuracy: 0.5882, MCC: 0.1718, F1: 0.6182

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.39989 | val 1.13247
  Epoch 016 - train 0.43175 | val 1.18791
  Regression -> MSE: 0.000575, MAE: 0.018474, R²: -0.0352
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.43853 | val 0.80939
  Epoch 017 - train 0.44559 | val 0.89916
  Regression -> MSE: 0.000243, MAE: 0.011903, R²: 0.0105
  Directional -> Accuracy: 0.4928, MCC: -0.0459, F1: 0.3860

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.41019 | val 0.67216
  Epoch 020 - train 0.43384 | val 0.63604
  Regression -> MSE: 0.000631, MAE: 0.019651, R²: -0.0567
  Directional -> Accuracy: 0.5227, MCC: 0.0721, F1: 0.5116

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.41364 | val 0.61672
  Epoch 016 - train 0.44877 | val 0.62446
  Regression -> MSE: 0.000395, MAE: 0.015947, R²: -0.0298
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.43225 | val 0.74428
  Epoch 017 - train 0.44740 | val 0.78639
  Regression -> MSE: 0.000241, MAE: 0.011981, R²: 0.0001
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.40272 | val 1.08748
  Epoch 016 - train 0.40692 | val 1.18005
  Regression -> MSE: 0.000310, MAE: 0.013669, R²: 0.0023
  Directional -> Accuracy: 0.5000, MCC: 0.0097, F1: 0.5098

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.45532 | val 0.61179
  Epoch 016 - train 0.44509 | val 0.60749
  Regression -> MSE: 0.000684, MAE: 0.019543, R²: -0.0094
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.41565 | val 0.56724
  Epoch 016 - train 0.45709 | val 0.58836
  Regression -> MSE: 0.000138, MAE: 0.009016, R²: 0.0024
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.39404 | val 0.63716
  Epoch 020 - train 0.39328 | val 0.64810
  Regression -> MSE: 0.000245, MAE: 0.011623, R²: -0.0911
  Directional -> Accuracy: 0.4918, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.47817 | val 1.37583
  Epoch 016 - train 0.45464 | val 1.42177
  Regression -> MSE: 0.000362, MAE: 0.015991, R²: 0.0013
  Directional -> Accuracy: 0.5577, MCC: 0.2521, F1: 0.6667

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.47894 | val 0.53182
  Epoch 016 - train 0.46718 | val 0.55686
  Regression -> MSE: 0.000109, MAE: 0.007976, R²: -0.0095
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.40375 | val 1.07595
  Epoch 016 - train 0.41896 | val 1.11180
  Regression -> MSE: 0.000159, MAE: 0.009982, R²: -0.0195
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.46729 | val 0.48040
  Epoch 016 - train 0.44673 | val 0.48853
  Regression -> MSE: 0.000281, MAE: 0.013029, R²: -0.0317
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.38407 | val 0.72922
  Epoch 020 - train 0.37315 | val 0.71595
  Regression -> MSE: 0.000177, MAE: 0.009866, R²: -0.1835
  Directional -> Accuracy: 0.5077, MCC: 0.1379, F1: 0.3846

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.45172 | val 1.01315
  Epoch 016 - train 0.47523 | val 0.94894
  Regression -> MSE: 0.000284, MAE: 0.012168, R²: -0.2550
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.44030 | val 0.66671
  Epoch 016 - train 0.44034 | val 0.67433
  Regression -> MSE: 0.000147, MAE: 0.008549, R²: -0.0236
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.44998 | val 0.53236
  Epoch 020 - train 0.43979 | val 0.56672
  Regression -> MSE: 0.000173, MAE: 0.010051, R²: -0.0452
  Directional -> Accuracy: 0.5606, MCC: 0.1260, F1: 0.4912

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.46562 | val 0.62060
  Epoch 016 - train 0.43506 | val 0.62492
  Regression -> MSE: 0.000086, MAE: 0.007065, R²: -0.0065
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.46697 | val 0.96433
  Epoch 016 - train 0.45270 | val 1.04486
  Regression -> MSE: 0.000211, MAE: 0.011073, R²: 0.0031
  Directional -> Accuracy: 0.5000, MCC: 0.0705, F1: 0.6292

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.39112 | val 0.31944
  Epoch 020 - train 0.39800 | val 0.31551
  Regression -> MSE: 0.000096, MAE: 0.007790, R²: -0.0459
  Directional -> Accuracy: 0.5893, MCC: 0.2499, F1: 0.5106

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.48438 | val 0.31386
  Epoch 020 - train 0.46689 | val 0.31185
  Regression -> MSE: 0.000107, MAE: 0.008594, R²: -0.0346
  Directional -> Accuracy: 0.6087, MCC: 0.2431, F1: 0.1818

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.47867 | val 0.43737
  Epoch 016 - train 0.47268 | val 0.47241
  Regression -> MSE: 0.000233, MAE: 0.012549, R²: -0.0045
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.43666 | val 0.60731
  Epoch 020 - train 0.43108 | val 0.57553
  Regression -> MSE: 0.000194, MAE: 0.008169, R²: -0.1672
  Directional -> Accuracy: 0.4912, MCC: -0.0199, F1: 0.5246

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.47709 | val 0.40691
  Epoch 016 - train 0.45386 | val 0.40048
  Regression -> MSE: 0.000240, MAE: 0.011987, R²: -0.0133
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.53445 | val 0.90933
  Epoch 016 - train 0.47108 | val 0.91206
  Regression -> MSE: 0.000230, MAE: 0.009868, R²: 0.0023
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.47770 | val 0.83717
  Epoch 016 - train 0.51583 | val 0.79252
  Regression -> MSE: 0.000145, MAE: 0.008794, R²: -0.0725
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.43892 | val 0.70358
  Epoch 016 - train 0.45153 | val 0.71014
  Regression -> MSE: 0.000187, MAE: 0.010383, R²: 0.0048
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.36848 | val 0.57750
  Epoch 018 - train 0.36946 | val 0.57842
  Regression -> MSE: 0.000302, MAE: 0.011224, R²: -0.1546
  Directional -> Accuracy: 0.4521, MCC: -0.0358, F1: 0.3103

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.47691 | val 0.49093
  Epoch 016 - train 0.42395 | val 0.45525
  Regression -> MSE: 0.000172, MAE: 0.010416, R²: -0.0303
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.37655 | val 0.66644
  Epoch 016 - train 0.40415 | val 0.67686
  Regression -> MSE: 0.000181, MAE: 0.010371, R²: -0.0035
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.42517 | val 0.37645
  Epoch 020 - train 0.40868 | val 0.37782
  Regression -> MSE: 0.000352, MAE: 0.013344, R²: -0.0279
  Directional -> Accuracy: 0.5075, MCC: 0.1239, F1: 0.3529

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.48918 | val 0.21675
  Epoch 020 - train 0.46809 | val 0.21998
  Regression -> MSE: 0.000115, MAE: 0.008263, R²: -0.0947
  Directional -> Accuracy: 0.6047, MCC: 0.2084, F1: 0.6383

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.45535 | val 0.77459
  Epoch 020 - train 0.40849 | val 0.78421
  Regression -> MSE: 0.000291, MAE: 0.013731, R²: -0.3308
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.46324 | val 1.23474
  Epoch 016 - train 0.43981 | val 1.30923
  Regression -> MSE: 0.000097, MAE: 0.007702, R²: -0.2474
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.45479 | val 0.27514
  Epoch 018 - train 0.42806 | val 0.27051
  Regression -> MSE: 0.000322, MAE: 0.014675, R²: -0.0459
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.49575 | val 0.20937
  Epoch 020 - train 0.47422 | val 0.20214
  Regression -> MSE: 0.000264, MAE: 0.011583, R²: -0.0836
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.40491 | val 0.67789
  Epoch 016 - train 0.39672 | val 0.70298
  Regression -> MSE: 0.000081, MAE: 0.007065, R²: -0.0009
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.48777 | val 0.72515
  Epoch 016 - train 0.48415 | val 0.71718
  Regression -> MSE: 0.000313, MAE: 0.014547, R²: -0.0208
  Directional -> Accuracy: 0.5319, MCC: 0.0678, F1: 0.5000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.44617 | val 0.59969
  Epoch 016 - train 0.43643 | val 0.60280
  Regression -> MSE: 0.000103, MAE: 0.007127, R²: -0.0454
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.46683 | val 0.75686
  Epoch 016 - train 0.46529 | val 0.76478
  Regression -> MSE: 0.000172, MAE: 0.009721, R²: 0.0013
  Directional -> Accuracy: 0.3265, MCC: -0.2807, F1: 0.4000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.44959 | val 0.62716
  Epoch 016 - train 0.42518 | val 0.61537
  Regression -> MSE: 0.000230, MAE: 0.011882, R²: -0.0318
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.42556 | val 0.65980
  Epoch 016 - train 0.42152 | val 0.71802
  Regression -> MSE: 0.000093, MAE: 0.007668, R²: -0.0039
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.46569 | val 0.92550
  Epoch 016 - train 0.45890 | val 0.92034
  Regression -> MSE: 0.000168, MAE: 0.010320, R²: -0.0260
  Directional -> Accuracy: 0.4815, MCC: 0.0000, F1: 0.0000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.45366 | val 0.63325
  Epoch 016 - train 0.43063 | val 0.63485
  Regression -> MSE: 0.000130, MAE: 0.009126, R²: -0.1235
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.43536 | val 0.85846

[I 2026-02-22 21:38:57,315] Trial 37 finished with value: -0.0115765923180389 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 2.7435191791363326e-05, 'weight_decay': 5.167128291121647e-06, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 1.4100462841487993, 'early_stopping_min_delta': 0.006937869808663945}. Best is trial 31 with value: -0.011425014985750452.

  Epoch 016 - train 0.45472 | val 0.87408
  Regression -> MSE: 0.000238, MAE: 0.012374, R²: -0.0025
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: regression
Sequence length: 12
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.47761 | val 1.06444
  Epoch 011 - train 0.47717 | val 1.05326
  Regression -> MSE: 0.000248, MAE: 0.012401, R²: -0.0084
  Directional -> Accuracy: 0.5513, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 88). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.49458 | val 0.43786
  Epoch 011 - train 0.47176 | val 0.43588
  Regression -> MSE: 0.000690, MAE: 0.019589, R²: 0.0013
  Directional -> Accuracy: 0.5532, MCC: 0.0000, F1: 0.7123

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 88). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.47317 | val 0.88408
  Epoch 011 - train 0.42882 | val 0.88419
  Regression -> MSE: 0.000347, MAE: 0.015141, R²: -0.0046
  Directional -> Accuracy: 0.5417, MCC: 0.0000, F1: 0.7027

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.39413 | val 0.46454
  Epoch 011 - train 0.39159 | val 0.45135
  Regression -> MSE: 0.000358, MAE: 0.014694, R²: -0.0368
  Directional -> Accuracy: 0.5395, MCC: 0.0000, F1: 0.7009

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.40139 | val 0.37523
  Epoch 020 - train 0.39536 | val 0.36803
  Regression -> MSE: 0.000207, MAE: 0.010265, R²: -0.0330
  Directional -> Accuracy: 0.4423, MCC: -0.0891, F1: 0.2927

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.41340 | val 0.89997
  Epoch 011 - train 0.42785 | val 0.90072
  Regression -> MSE: 0.000636, MAE: 0.019522, R²: -0.1117
  Directional -> Accuracy: 0.4898, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.45555 | val 0.55703
  Epoch 011 - train 0.43724 | val 0.55387
  Regression -> MSE: 0.000251, MAE: 0.012171, R²: -0.0228
  Directional -> Accuracy: 0.4429, MCC: -0.0719, F1: 0.4507

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 88). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 88). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.45742 | val 0.50446
  Epoch 018 - train 0.44119 | val 0.50395
  Regression -> MSE: 0.000591, MAE: 0.018998, R²: -0.0113
  Directional -> Accuracy: 0.5333, MCC: -0.0068, F1: 0.3226

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.40910 | val 0.71049
  Epoch 011 - train 0.41309 | val 0.71059
  Regression -> MSE: 0.000346, MAE: 0.015534, R²: -0.0233
  Directional -> Accuracy: 0.3810, MCC: 0.0000, F1: 0.5517

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 88). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 88). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.45442 | val 0.59561
  Epoch 011 - train 0.41763 | val 0.59652
  Regression -> MSE: 0.000239, MAE: 0.011919, R²: -0.0056
  Directional -> Accuracy: 0.4366, MCC: 0.0000, F1: 0.6078

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.43409 | val 0.85360
  Epoch 011 - train 0.39721 | val 0.86097
  Regression -> MSE: 0.000298, MAE: 0.013379, R²: 0.0244
  Directional -> Accuracy: 0.5882, MCC: 0.2176, F1: 0.2759

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.47041 | val 0.55652
  Epoch 011 - train 0.45804 | val 0.55608
  Regression -> MSE: 0.000676, MAE: 0.019624, R²: -0.0091
  Directional -> Accuracy: 0.5085, MCC: 0.0000, F1: 0.6742

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.40645 | val 0.47253
  Epoch 011 - train 0.43355 | val 0.48356
  Regression -> MSE: 0.000152, MAE: 0.009731, R²: -0.0141
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 88). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.43232 | val 0.62728
  Epoch 011 - train 0.40803 | val 0.62459
  Regression -> MSE: 0.000228, MAE: 0.010980, R²: -0.0160
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.43962 | val 1.07420
  Epoch 011 - train 0.44859 | val 1.07801
  Regression -> MSE: 0.000388, MAE: 0.016212, R²: -0.0330
  Directional -> Accuracy: 0.5283, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.45920 | val 0.46706
  Epoch 011 - train 0.46987 | val 0.46806
  Regression -> MSE: 0.000110, MAE: 0.008165, R²: -0.0364
  Directional -> Accuracy: 0.4648, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.42972 | val 0.98138
  Epoch 011 - train 0.42071 | val 0.97236
  Regression -> MSE: 0.000164, MAE: 0.009789, R²: -0.0268
  Directional -> Accuracy: 0.6167, MCC: 0.0000, F1: 0.7629

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.42929 | val 0.46136
  Epoch 011 - train 0.43911 | val 0.45224
  Regression -> MSE: 0.000271, MAE: 0.012728, R²: -0.0081
  Directional -> Accuracy: 0.6104, MCC: 0.0000, F1: 0.7581

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.38343 | val 0.59417
  Epoch 020 - train 0.37013 | val 0.59201
  Regression -> MSE: 0.000271, MAE: 0.013344, R²: -0.8398
  Directional -> Accuracy: 0.5606, MCC: 0.2134, F1: 0.5085

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 88). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.46913 | val 0.74450
  Epoch 011 - train 0.45656 | val 0.74315
  Regression -> MSE: 0.000233, MAE: 0.011063, R²: -0.0280
  Directional -> Accuracy: 0.4342, MCC: -0.2181, F1: 0.5743

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.45464 | val 0.60122
  Epoch 011 - train 0.43658 | val 0.60055
  Regression -> MSE: 0.000174, MAE: 0.009740, R²: -0.1752
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 88). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 88). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 88). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.40351 | val 0.51657
  Epoch 011 - train 0.42752 | val 0.51875
  Regression -> MSE: 0.000193, MAE: 0.010731, R²: -0.0910
  Directional -> Accuracy: 0.4776, MCC: -0.0422, F1: 0.3860

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.50266 | val 0.55923
  Epoch 011 - train 0.50973 | val 0.55388
  Regression -> MSE: 0.000096, MAE: 0.007519, R²: -0.1467
  Directional -> Accuracy: 0.3559, MCC: -0.2555, F1: 0.2963

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.42275 | val 0.53470
  Epoch 011 - train 0.41266 | val 0.53476
  Regression -> MSE: 0.000221, MAE: 0.011248, R²: -0.0099
  Directional -> Accuracy: 0.5075, MCC: -0.0262, F1: 0.1951

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.41248 | val 0.31529
  Epoch 011 - train 0.41733 | val 0.31226
  Regression -> MSE: 0.000098, MAE: 0.008278, R²: -0.0677
  Directional -> Accuracy: 0.4912, MCC: -0.1288, F1: 0.6329

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.49477 | val 0.19694
  Epoch 011 - train 0.48452 | val 0.20095
  Regression -> MSE: 0.000139, MAE: 0.009664, R²: -0.1051
  Directional -> Accuracy: 0.4167, MCC: 0.0000, F1: 0.5882

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.47464 | val 0.36204
  Epoch 011 - train 0.45199 | val 0.36300
  Regression -> MSE: 0.000248, MAE: 0.013072, R²: -0.0426
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.43577 | val 0.58615
  Epoch 011 - train 0.44503 | val 0.58178
  Regression -> MSE: 0.000168, MAE: 0.007935, R²: -0.0241
  Directional -> Accuracy: 0.5517, MCC: 0.0000, F1: 0.7111

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.50882 | val 0.27886
  Epoch 011 - train 0.52647 | val 0.29011
  Regression -> MSE: 0.000237, MAE: 0.011974, R²: -0.0100
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.45070 | val 0.66827
  Epoch 018 - train 0.47125 | val 0.66961
  Regression -> MSE: 0.000275, MAE: 0.011090, R²: -0.1006
  Directional -> Accuracy: 0.4667, MCC: -0.0672, F1: 0.4783

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.47846 | val 0.73615
  Epoch 011 - train 0.51599 | val 0.74233
  Regression -> MSE: 0.000136, MAE: 0.008501, R²: -0.0234
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.46752 | val 0.54446
  Epoch 011 - train 0.44617 | val 0.54362
  Regression -> MSE: 0.000208, MAE: 0.011140, R²: -0.1031
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.37979 | val 0.60638
  Epoch 011 - train 0.38560 | val 0.60286
  Regression -> MSE: 0.000262, MAE: 0.010627, R²: -0.0136
  Directional -> Accuracy: 0.5676, MCC: 0.0000, F1: 0.7241

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 88). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.42111 | val 0.41547
  Epoch 020 - train 0.40463 | val 0.37662
  Regression -> MSE: 0.000177, MAE: 0.010426, R²: -0.0882
  Directional -> Accuracy: 0.4872, MCC: 0.0000, F1: 0.6552

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.41459 | val 0.46863
  Epoch 011 - train 0.40801 | val 0.47150
  Regression -> MSE: 0.000185, MAE: 0.010546, R²: -0.0103
  Directional -> Accuracy: 0.4667, MCC: -0.0144, F1: 0.6250

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.39917 | val 0.45689
  Epoch 011 - train 0.42579 | val 0.45409
  Regression -> MSE: 0.000384, MAE: 0.013837, R²: -0.0991
  Directional -> Accuracy: 0.4265, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.45568 | val 0.30210
  Epoch 011 - train 0.46883 | val 0.31171
  Regression -> MSE: 0.000118, MAE: 0.008493, R²: -0.1392
  Directional -> Accuracy: 0.2727, MCC: -0.4725, F1: 0.3600

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.43938 | val 0.77008
  Epoch 011 - train 0.42971 | val 0.76625
  Regression -> MSE: 0.000219, MAE: 0.011238, R²: -0.0178
  Directional -> Accuracy: 0.5000, MCC: 0.0500, F1: 0.6027

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.47605 | val 0.98182
  Epoch 011 - train 0.47972 | val 0.97300
  Regression -> MSE: 0.000126, MAE: 0.008943, R²: -0.5841
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 88). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 88). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 88). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 88). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.41700 | val 0.35292
  Epoch 011 - train 0.40284 | val 0.35789
  Regression -> MSE: 0.000336, MAE: 0.014992, R²: -0.0238
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 88). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.47163 | val 0.23940
  Epoch 011 - train 0.46800 | val 0.24091
  Regression -> MSE: 0.000242, MAE: 0.011242, R²: -0.0171
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.7000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 88). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 88). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.43810 | val 0.58906
  Epoch 011 - train 0.44105 | val 0.59053
  Regression -> MSE: 0.000089, MAE: 0.007180, R²: -0.1057
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 88). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 88). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 88). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.47406 | val 0.48119
  Epoch 011 - train 0.43663 | val 0.47912
  Regression -> MSE: 0.000364, MAE: 0.015391, R²: -0.0113
  Directional -> Accuracy: 0.5208, MCC: 0.1459, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.40823 | val 0.50033
  Epoch 020 - train 0.42113 | val 0.50130
  Regression -> MSE: 0.000093, MAE: 0.007055, R²: 0.0400
  Directional -> Accuracy: 0.5333, MCC: 0.0219, F1: 0.6316

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.46086 | val 0.59472
  Epoch 018 - train 0.45730 | val 0.61764
  Regression -> MSE: 0.000187, MAE: 0.010460, R²: -0.0357
  Directional -> Accuracy: 0.4146, MCC: 0.1720, F1: 0.5556

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.37681 | val 0.57378
  Epoch 011 - train 0.37328 | val 0.57597
  Regression -> MSE: 0.000223, MAE: 0.011635, R²: -0.0152
  Directional -> Accuracy: 0.5789, MCC: 0.1883, F1: 0.5385

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.44152 | val 0.46698
  Epoch 011 - train 0.44077 | val 0.46691
  Regression -> MSE: 0.000104, MAE: 0.008064, R²: -0.1376
  Directional -> Accuracy: 0.5172, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.47932 | val 0.76123
  Epoch 011 - train 0.45793 | val 0.75912
  Regression -> MSE: 0.000161, MAE: 0.010077, R²: -0.0027
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.42115 | val 0.82886
  Epoch 011 - train 0.42756 | val 0.83250
  Regression -> MSE: 0.000115, MAE: 0.008792, R²: -0.0107
  Directional -> Accuracy: 0.5088, MCC: 0.0139, F1: 0.5625

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...

[I 2026-02-22 21:39:10,141] Trial 38 finished with value: -0.011747659825060233 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 12, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.0, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 6.348270691986444e-05, 'weight_decay': 0.0008364263183436573, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 1.1058965237761313, 'early_stopping_min_delta': 0.009229652783765026}. Best is trial 31 with value: -0.011425014985750452.

  Epoch 010 - train 0.43845 | val 0.71118
  Epoch 011 - train 0.45976 | val 0.71092
  Regression -> MSE: 0.000238, MAE: 0.012243, R²: -0.0191
  Directional -> Accuracy: 0.5161, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: regression
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.42267 | val 0.73664
  Epoch 020 - train 0.41150 | val 0.70885
  Epoch 030 - train 0.40238 | val 0.70374
  Epoch 040 - train 0.39714 | val 0.70927
  Epoch 041 - train 0.39808 | val 0.71361
  Regression -> MSE: 0.000264, MAE: 0.012938, R²: -0.0971
  Directional -> Accuracy: 0.5000, MCC: 0.1154, F1: 0.6200

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.39224 | val 0.44456
  Epoch 020 - train 0.39669 | val 0.44734
  Epoch 021 - train 0.40374 | val 0.44787
  Regression -> MSE: 0.000704, MAE: 0.019739, R²: -0.0089
  Directional -> Accuracy: 0.6889, MCC: 0.3728, F1: 0.7200

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.43110 | val 0.90605
  Epoch 020 - train 0.42064 | val 0.88076
  Epoch 030 - train 0.41044 | val 0.88128
  Epoch 040 - train 0.42488 | val 0.88203
  Regression -> MSE: 0.000348, MAE: 0.014881, R²: -0.1070
  Directional -> Accuracy: 0.5217, MCC: 0.2041, F1: 0.1538

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.34450 | val 1.01605
  Epoch 020 - train 0.33720 | val 1.26707
  Epoch 021 - train 0.34334 | val 1.27521
  Regression -> MSE: 0.000365, MAE: 0.014821, R²: -0.0341
  Directional -> Accuracy: 0.4730, MCC: 0.0200, F1: 0.1702

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.42088 | val 0.40920
  Epoch 020 - train 0.41042 | val 0.42514
  Epoch 029 - train 0.39485 | val 0.44458
  Regression -> MSE: 0.000221, MAE: 0.010155, R²: -0.0712
  Directional -> Accuracy: 0.5000, MCC: -0.0333, F1: 0.6269

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.40977 | val 0.95740
  Epoch 020 - train 0.38254 | val 1.07208
  Epoch 025 - train 0.38293 | val 1.11356
  Regression -> MSE: 0.000594, MAE: 0.018971, R²: -0.0503
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.40256 | val 0.83520
  Epoch 020 - train 0.41045 | val 0.86194
  Epoch 021 - train 0.40414 | val 0.85334
  Regression -> MSE: 0.000252, MAE: 0.012004, R²: -0.0178
  Directional -> Accuracy: 0.6029, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.42408 | val 0.37508
  Epoch 020 - train 0.39894 | val 0.41669
  Epoch 021 - train 0.39481 | val 0.40703
  Regression -> MSE: 0.000612, MAE: 0.019470, R²: -0.0017
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.41657 | val 0.70078
  Epoch 020 - train 0.42207 | val 0.75231
  Epoch 021 - train 0.39274 | val 0.75121
  Regression -> MSE: 0.000374, MAE: 0.015958, R²: -0.0022
  Directional -> Accuracy: 0.4375, MCC: 0.0000, F1: 0.6087

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.42787 | val 0.70734
  Epoch 020 - train 0.43673 | val 0.73189
  Epoch 021 - train 0.40116 | val 0.74576
  Regression -> MSE: 0.000250, MAE: 0.012469, R²: -0.0191
  Directional -> Accuracy: 0.4203, MCC: 0.0000, F1: 0.5918

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.41461 | val 1.07338
  Epoch 020 - train 0.39934 | val 1.09868
  Epoch 021 - train 0.40095 | val 1.08617
  Regression -> MSE: 0.000325, MAE: 0.014163, R²: -0.0401
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.43885 | val 0.60296
  Epoch 020 - train 0.43686 | val 0.59859
  Epoch 021 - train 0.45182 | val 0.60314
  Regression -> MSE: 0.000690, MAE: 0.019578, R²: -0.0060
  Directional -> Accuracy: 0.5263, MCC: 0.0600, F1: 0.6582

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.41680 | val 0.96455
  Epoch 020 - train 0.43329 | val 1.04955
  Epoch 021 - train 0.40945 | val 1.10764
  Regression -> MSE: 0.000137, MAE: 0.008907, R²: 0.0102
  Directional -> Accuracy: 0.6429, MCC: 0.2706, F1: 0.5455

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.38585 | val 0.61129
  Epoch 020 - train 0.37287 | val 0.59892
  Epoch 030 - train 0.36160 | val 0.60287
  Epoch 033 - train 0.37009 | val 0.60365
  Regression -> MSE: 0.000223, MAE: 0.010700, R²: 0.0174
  Directional -> Accuracy: 0.5333, MCC: 0.0981, F1: 0.2632

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.40636 | val 1.20719
  Epoch 020 - train 0.38596 | val 1.28279
  Epoch 028 - train 0.40887 | val 1.32441
  Regression -> MSE: 0.000378, MAE: 0.016374, R²: -0.0310
  Directional -> Accuracy: 0.5490, MCC: 0.1526, F1: 0.6102

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.44282 | val 0.53684
  Epoch 020 - train 0.44225 | val 0.53980
  Epoch 021 - train 0.42559 | val 0.54578
  Regression -> MSE: 0.000107, MAE: 0.007970, R²: 0.0143
  Directional -> Accuracy: 0.5217, MCC: 0.0978, F1: 0.3774

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.39692 | val 1.24651
  Epoch 020 - train 0.39097 | val 1.29612
  Epoch 021 - train 0.39822 | val 1.30539
  Regression -> MSE: 0.000162, MAE: 0.010156, R²: -0.0246
  Directional -> Accuracy: 0.4310, MCC: -0.1253, F1: 0.4762

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.40723 | val 0.55095
  Epoch 020 - train 0.40982 | val 0.62869
  Epoch 021 - train 0.40306 | val 0.64135
  Regression -> MSE: 0.000279, MAE: 0.013366, R²: -0.0187
  Directional -> Accuracy: 0.4667, MCC: -0.1846, F1: 0.6000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.36585 | val 0.70032
  Epoch 020 - train 0.36122 | val 0.71916
  Epoch 021 - train 0.34648 | val 0.72348
  Regression -> MSE: 0.000148, MAE: 0.008822, R²: 0.0246
  Directional -> Accuracy: 0.5781, MCC: 0.0000, F1: 0.7327

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.40206 | val 1.07282
  Epoch 020 - train 0.39118 | val 1.16391
  Epoch 021 - train 0.41195 | val 1.15779
  Regression -> MSE: 0.000245, MAE: 0.011145, R²: -0.0780
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.43219 | val 0.68277
  Epoch 020 - train 0.42158 | val 0.69675
  Epoch 021 - train 0.40475 | val 0.69844
  Regression -> MSE: 0.000145, MAE: 0.008388, R²: -0.0072
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.38659 | val 0.53593
  Epoch 020 - train 0.39510 | val 0.55580
  Epoch 026 - train 0.39405 | val 0.56295
  Regression -> MSE: 0.000181, MAE: 0.010406, R²: -0.0933
  Directional -> Accuracy: 0.4769, MCC: -0.0449, F1: 0.2917

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.43448 | val 0.60427
  Epoch 020 - train 0.43287 | val 0.58900
  Epoch 021 - train 0.43592 | val 0.58911
  Regression -> MSE: 0.000093, MAE: 0.007467, R²: -0.0749
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.41077 | val 0.88450
  Epoch 020 - train 0.41209 | val 0.85426
  Epoch 021 - train 0.39775 | val 0.83196
  Regression -> MSE: 0.000209, MAE: 0.010968, R²: 0.0090
  Directional -> Accuracy: 0.5077, MCC: 0.0451, F1: 0.6000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.36506 | val 0.32857
  Epoch 020 - train 0.35218 | val 0.34567
  Epoch 024 - train 0.33928 | val 0.34873
  Regression -> MSE: 0.000094, MAE: 0.007870, R²: -0.0455
  Directional -> Accuracy: 0.5455, MCC: 0.1826, F1: 0.3902

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.44499 | val 0.48468
  Epoch 020 - train 0.43467 | val 0.53077
  Epoch 021 - train 0.41944 | val 0.53469
  Regression -> MSE: 0.000102, MAE: 0.008656, R²: -0.0220
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.45313 | val 0.41344
  Epoch 020 - train 0.45963 | val 0.41212
  Epoch 030 - train 0.45010 | val 0.40404
  Epoch 040 - train 0.43331 | val 0.40248
  Epoch 050 - train 0.42407 | val 0.39967
  Regression -> MSE: 0.000237, MAE: 0.012834, R²: -0.0024
  Directional -> Accuracy: 0.5238, MCC: -0.1171, F1: 0.6774

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.42362 | val 0.50702
  Epoch 020 - train 0.41038 | val 0.51661
  Epoch 030 - train 0.40712 | val 0.53054
  Epoch 031 - train 0.40238 | val 0.52978
  Regression -> MSE: 0.000428, MAE: 0.016064, R²: -1.5259
  Directional -> Accuracy: 0.5000, MCC: 0.2137, F1: 0.1765

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.41383 | val 0.32464
  Epoch 020 - train 0.40574 | val 0.32766
  Epoch 021 - train 0.44491 | val 0.32500
  Regression -> MSE: 0.000245, MAE: 0.012170, R²: -0.0118
  Directional -> Accuracy: 0.6000, MCC: 0.1759, F1: 0.7037

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.42468 | val 0.98029
  Epoch 020 - train 0.42032 | val 0.96845
  Epoch 021 - train 0.42695 | val 0.97213
  Regression -> MSE: 0.000238, MAE: 0.010109, R²: -0.0104
  Directional -> Accuracy: 0.3571, MCC: -0.2821, F1: 0.4000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.42128 | val 0.57618
  Epoch 020 - train 0.43497 | val 0.60130
  Epoch 021 - train 0.43117 | val 0.60882
  Regression -> MSE: 0.000140, MAE: 0.008516, R²: -0.0180
  Directional -> Accuracy: 0.3571, MCC: -0.3125, F1: 0.0690

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.41651 | val 0.66258
  Epoch 020 - train 0.41296 | val 0.69168
  Epoch 021 - train 0.41974 | val 0.69766
  Regression -> MSE: 0.000188, MAE: 0.010254, R²: -0.0246
  Directional -> Accuracy: 0.3878, MCC: -0.2340, F1: 0.1667

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.35218 | val 0.59270
  Epoch 020 - train 0.34798 | val 0.59059
  Epoch 021 - train 0.35328 | val 0.58883
  Regression -> MSE: 0.000276, MAE: 0.010706, R²: -0.0407
  Directional -> Accuracy: 0.5139, MCC: 0.0652, F1: 0.4615

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.38822 | val 0.74894
  Epoch 020 - train 0.36231 | val 0.69932
  Epoch 021 - train 0.36893 | val 0.70975
  Regression -> MSE: 0.000199, MAE: 0.010987, R²: -0.0827
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.38455 | val 0.42780
  Epoch 020 - train 0.37606 | val 0.45033
  Epoch 021 - train 0.38995 | val 0.44667
  Regression -> MSE: 0.000338, MAE: 0.011723, R²: 0.0291
  Directional -> Accuracy: 0.6212, MCC: 0.2034, F1: 0.6988

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.44302 | val 0.23390
  Epoch 020 - train 0.42472 | val 0.23067
  Epoch 027 - train 0.43116 | val 0.23270
  Regression -> MSE: 0.000141, MAE: 0.008734, R²: -0.3336
  Directional -> Accuracy: 0.5238, MCC: 0.1168, F1: 0.2857

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.42286 | val 0.75817
  Epoch 020 - train 0.41591 | val 0.74381
  Epoch 021 - train 0.39814 | val 0.74409
  Regression -> MSE: 0.000222, MAE: 0.011352, R²: -0.0100
  Directional -> Accuracy: 0.4821, MCC: -0.0234, F1: 0.5085

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.42026 | val 1.07198
  Epoch 020 - train 0.41679 | val 1.10633
  Epoch 023 - train 0.40175 | val 1.12053
  Regression -> MSE: 0.000082, MAE: 0.007058, R²: -0.1161
  Directional -> Accuracy: 0.3913, MCC: -0.1786, F1: 0.3913

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.42835 | val 0.27621
  Epoch 020 - train 0.39709 | val 0.26225
  Epoch 030 - train 0.39030 | val 0.26843
  Epoch 040 - train 0.40251 | val 0.26356
  Epoch 050 - train 0.38825 | val 0.26901
  Regression -> MSE: 0.000593, MAE: 0.021359, R²: -0.9032
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.39825 | val 0.65816
  Epoch 020 - train 0.37515 | val 0.69230
  Epoch 021 - train 0.37137 | val 0.69437
  Regression -> MSE: 0.000077, MAE: 0.006894, R²: 0.0088
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.43449 | val 0.67511
  Epoch 020 - train 0.42616 | val 0.68253
  Epoch 021 - train 0.43741 | val 0.65136
  Regression -> MSE: 0.000306, MAE: 0.014420, R²: -0.0181
  Directional -> Accuracy: 0.4889, MCC: 0.0000, F1: 0.0000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.40331 | val 0.61829
  Epoch 020 - train 0.41143 | val 0.61791
  Epoch 021 - train 0.41491 | val 0.61824
  Regression -> MSE: 0.000105, MAE: 0.007231, R²: -0.0372
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.46139 | val 0.75223
  Epoch 020 - train 0.43046 | val 0.76350
  Epoch 021 - train 0.45868 | val 0.77314
  Regression -> MSE: 0.000178, MAE: 0.010304, R²: -0.0135
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.39144 | val 0.50225
  Epoch 020 - train 0.38617 | val 0.51315
  Epoch 026 - train 0.38228 | val 0.51754
  Regression -> MSE: 0.000236, MAE: 0.011732, R²: -0.0482
  Directional -> Accuracy: 0.5273, MCC: 0.1143, F1: 0.4091

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.37601 | val 0.98010
  Epoch 020 - train 0.37244 | val 1.11916
  Epoch 021 - train 0.38835 | val 1.07118
  Regression -> MSE: 0.000094, MAE: 0.007763, R²: -0.0043

[I 2026-02-22 21:46:41,454] Trial 39 finished with value: -0.011851374405326395 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.0, 'batch_size': 16, 'learning_rate': 1.926065466425208e-05, 'weight_decay': 5.331132479829993e-07, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 50, 'huber_delta': 1.2862153767582432, 'early_stopping_min_delta': 0.008102094531962683}. Best is trial 31 with value: -0.011425014985750452.

  Epoch 021 - train 0.40743 | val 0.92188
  Regression -> MSE: 0.000242, MAE: 0.012409, R²: -0.0086
  Directional -> Accuracy: 0.5333, MCC: 0.0842, F1: 0.1250

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 6
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.39524 | val 0.78606
  Epoch 015 - train 0.38373 | val 0.88289
  Regression -> MSE: 0.000258, MAE: 0.012880, R²: -0.0502
  Directional -> Accuracy: 0.4810, MCC: 0.1272, F1: 0.6239

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 82). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.41044 | val 0.39886
  Epoch 017 - train 0.40886 | val 0.40090
  Regression -> MSE: 0.000649, MAE: 0.018772, R²: 0.0409
  Directional -> Accuracy: 0.5417, MCC: -0.1286, F1: 0.7027

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 82). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.44960 | val 1.01010
  Epoch 011 - train 0.44183 | val 1.02380
  Regression -> MSE: 0.000364, MAE: 0.015283, R²: -0.0470
  Directional -> Accuracy: 0.4694, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.34688 | val 0.43018
  Epoch 011 - train 0.34984 | val 0.43243
  Regression -> MSE: 0.000374, MAE: 0.014965, R²: -0.0536
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.40013 | val 0.38488
  Epoch 020 - train 0.39752 | val 0.36959
  Epoch 030 - train 0.37775 | val 0.35630
  Regression -> MSE: 0.000199, MAE: 0.009269, R²: -0.0032
  Directional -> Accuracy: 0.6604, MCC: 0.3780, F1: 0.7500

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.40999 | val 1.10843
  Epoch 020 - train 0.36839 | val 1.09507
  Epoch 023 - train 0.37039 | val 1.09669
  Regression -> MSE: 0.000498, MAE: 0.017464, R²: -0.0040
  Directional -> Accuracy: 0.4878, MCC: -0.1407, F1: 0.0870

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.42734 | val 0.70497
  Epoch 015 - train 0.41124 | val 0.76609
  Regression -> MSE: 0.000252, MAE: 0.012286, R²: 0.0177
  Directional -> Accuracy: 0.5211, MCC: 0.0509, F1: 0.4848

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 82). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 82). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.42919 | val 0.63595
  Epoch 011 - train 0.41202 | val 0.64781
  Regression -> MSE: 0.000588, MAE: 0.019053, R²: -0.0379
  Directional -> Accuracy: 0.4043, MCC: 0.0000, F1: 0.5758

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.42899 | val 0.71396
  Epoch 011 - train 0.42017 | val 0.71870
  Regression -> MSE: 0.000386, MAE: 0.016103, R²: -0.0037
  Directional -> Accuracy: 0.3953, MCC: 0.0000, F1: 0.5667

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 82). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 82). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.42591 | val 0.68061
  Epoch 011 - train 0.42784 | val 0.68494
  Regression -> MSE: 0.000238, MAE: 0.011792, R²: -0.0001
  Directional -> Accuracy: 0.4306, MCC: 0.0000, F1: 0.6019

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.38780 | val 0.80665
  Epoch 011 - train 0.39596 | val 0.81318
  Regression -> MSE: 0.000307, MAE: 0.013649, R²: 0.0009
  Directional -> Accuracy: 0.5000, MCC: 0.1852, F1: 0.6486

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.44549 | val 0.61840
  Epoch 011 - train 0.44134 | val 0.63386
  Regression -> MSE: 0.000659, MAE: 0.019201, R²: -0.0003
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.43129 | val 0.51597
  Epoch 011 - train 0.41309 | val 0.53835
  Regression -> MSE: 0.000148, MAE: 0.009514, R²: -0.0080
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.6364

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 82). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.37983 | val 0.63617
  Epoch 020 - train 0.35337 | val 0.66048
  Regression -> MSE: 0.000220, MAE: 0.010843, R²: 0.0229
  Directional -> Accuracy: 0.5238, MCC: 0.0474, F1: 0.5161

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.39644 | val 1.61251
  Epoch 011 - train 0.40097 | val 1.81106
  Regression -> MSE: 0.000393, MAE: 0.016585, R²: -0.0266
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.41978 | val 0.54790
  Epoch 014 - train 0.40928 | val 0.56013
  Regression -> MSE: 0.000107, MAE: 0.007822, R²: -0.0142
  Directional -> Accuracy: 0.5278, MCC: -0.0196, F1: 0.6731

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.40378 | val 1.08895
  Epoch 011 - train 0.40749 | val 1.11224
  Regression -> MSE: 0.000158, MAE: 0.009756, R²: -0.0022
  Directional -> Accuracy: 0.6066, MCC: 0.0000, F1: 0.7551

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.41531 | val 0.73192
  Epoch 013 - train 0.40563 | val 0.79197
  Regression -> MSE: 0.000273, MAE: 0.013167, R²: -0.0061
  Directional -> Accuracy: 0.5385, MCC: 0.0574, F1: 0.6000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.36716 | val 0.66967
  Epoch 020 - train 0.34935 | val 0.66343
  Epoch 030 - train 0.32932 | val 0.66380
  Regression -> MSE: 0.000247, MAE: 0.012385, R²: -0.5966
  Directional -> Accuracy: 0.4179, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 82). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.41523 | val 0.83493
  Epoch 017 - train 0.39764 | val 0.84623
  Regression -> MSE: 0.000296, MAE: 0.012605, R²: -0.2792
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.40751 | val 0.60494
  Epoch 017 - train 0.38729 | val 0.63167
  Regression -> MSE: 0.000155, MAE: 0.008993, R²: -0.0419
  Directional -> Accuracy: 0.5800, MCC: 0.0624, F1: 0.6866

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 82). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 82). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 82). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.42472 | val 0.57860
  Epoch 015 - train 0.41469 | val 0.59594
  Regression -> MSE: 0.000182, MAE: 0.011055, R²: -0.0014
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.43726 | val 0.77310
  Epoch 011 - train 0.42347 | val 0.81054
  Regression -> MSE: 0.000082, MAE: 0.006800, R²: 0.0023
  Directional -> Accuracy: 0.5833, MCC: 0.0000, F1: 0.7368

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.39680 | val 0.68950
  Epoch 011 - train 0.38876 | val 0.68036
  Regression -> MSE: 0.000217, MAE: 0.011158, R²: -0.0090
  Directional -> Accuracy: 0.5147, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.37888 | val 0.29101
  Epoch 020 - train 0.34512 | val 0.28779
  Epoch 024 - train 0.33884 | val 0.29206
  Regression -> MSE: 0.000113, MAE: 0.008381, R²: -0.2535
  Directional -> Accuracy: 0.5690, MCC: 0.1996, F1: 0.4898

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.43546 | val 0.18961
  Epoch 014 - train 0.41552 | val 0.23835
  Regression -> MSE: 0.000132, MAE: 0.009483, R²: -0.0545
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.43198 | val 0.22744
  Epoch 011 - train 0.42345 | val 0.23388
  Regression -> MSE: 0.000309, MAE: 0.013996, R²: -0.0599
  Directional -> Accuracy: 0.4889, MCC: 0.0379, F1: 0.4651

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.41614 | val 0.56784
  Epoch 018 - train 0.41038 | val 0.58214
  Regression -> MSE: 0.000198, MAE: 0.008274, R²: -0.2274
  Directional -> Accuracy: 0.5085, MCC: 0.1857, F1: 0.2564

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.45546 | val 0.41451
  Epoch 011 - train 0.43385 | val 0.41547
  Regression -> MSE: 0.000230, MAE: 0.011836, R²: 0.0023
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.6866

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.42460 | val 0.68938
  Epoch 011 - train 0.45052 | val 0.69020
  Regression -> MSE: 0.000259, MAE: 0.010751, R²: 0.0012
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.44131 | val 0.66322
  Epoch 011 - train 0.42629 | val 0.66476
  Regression -> MSE: 0.000143, MAE: 0.008597, R²: -0.0224
  Directional -> Accuracy: 0.4565, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.41541 | val 0.66336
  Epoch 017 - train 0.38148 | val 0.74191
  Regression -> MSE: 0.000186, MAE: 0.010432, R²: 0.0014
  Directional -> Accuracy: 0.5192, MCC: 0.0077, F1: 0.6753

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.36115 | val 0.59785
  Epoch 016 - train 0.35687 | val 0.60737
  Regression -> MSE: 0.000309, MAE: 0.011471, R²: -0.1834
  Directional -> Accuracy: 0.5333, MCC: 0.1340, F1: 0.4444

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 82). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.41412 | val 0.47813
  Epoch 020 - train 0.39868 | val 0.45420
  Epoch 029 - train 0.37227 | val 0.48487
  Regression -> MSE: 0.000203, MAE: 0.011381, R²: -0.2554
  Directional -> Accuracy: 0.4878, MCC: 0.0000, F1: 0.6557

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.37510 | val 0.46812
  Epoch 011 - train 0.36543 | val 0.49043
  Regression -> MSE: 0.000217, MAE: 0.011158, R²: -0.0153
  Directional -> Accuracy: 0.4565, MCC: 0.0000, F1: 0.6269

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.40972 | val 0.38968
  Epoch 019 - train 0.39716 | val 0.39592
  Regression -> MSE: 0.000447, MAE: 0.016454, R²: -0.3005
  Directional -> Accuracy: 0.4203, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.40013 | val 0.25459
  Epoch 020 - train 0.34617 | val 0.26529
  Epoch 021 - train 0.37516 | val 0.26618
  Regression -> MSE: 0.000141, MAE: 0.008523, R²: -0.3901
  Directional -> Accuracy: 0.4889, MCC: -0.0069, F1: 0.1481

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.41331 | val 0.68028
  Epoch 020 - train 0.38725 | val 0.68418
  Regression -> MSE: 0.000215, MAE: 0.011155, R²: -0.0181
  Directional -> Accuracy: 0.5424, MCC: 0.0712, F1: 0.2286

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.42250 | val 1.19560
  Epoch 011 - train 0.41709 | val 1.24936
  Regression -> MSE: 0.000092, MAE: 0.007540, R²: -0.1505
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 82). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 82). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 82). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 82). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.41019 | val 0.31391
  Epoch 011 - train 0.42073 | val 0.31492
  Regression -> MSE: 0.000314, MAE: 0.013747, R²: -0.0012
  Directional -> Accuracy: 0.6667, MCC: 0.0000, F1: 0.0000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 82). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.41495 | val 0.23761
  Epoch 020 - train 0.41119 | val 0.23442
  Epoch 024 - train 0.37657 | val 0.22831
  Regression -> MSE: 0.000234, MAE: 0.010821, R²: -0.0243
  Directional -> Accuracy: 0.5854, MCC: 0.1691, F1: 0.6222

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 82). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 82). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.38569 | val 0.67763
  Epoch 015 - train 0.38738 | val 0.75556
  Regression -> MSE: 0.000080, MAE: 0.007064, R²: 0.0164
  Directional -> Accuracy: 0.5325, MCC: 0.1201, F1: 0.6786

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 82). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 82). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.46256 | val 0.46488
  Epoch 011 - train 0.45569 | val 0.46723
  Regression -> MSE: 0.000379, MAE: 0.015676, R²: -0.0241
  Directional -> Accuracy: 0.4898, MCC: 0.0000, F1: 0.6575

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.41543 | val 0.62764
  Epoch 013 - train 0.38356 | val 0.63560
  Regression -> MSE: 0.000097, MAE: 0.007027, R²: -0.0260
  Directional -> Accuracy: 0.5745, MCC: 0.0000, F1: 0.7297

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.43314 | val 0.77091
  Epoch 011 - train 0.43879 | val 0.78917
  Regression -> MSE: 0.000195, MAE: 0.010785, R²: -0.0219
  Directional -> Accuracy: 0.3571, MCC: 0.0000, F1: 0.5263

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.39783 | val 0.58009
  Epoch 011 - train 0.39026 | val 0.58451
  Regression -> MSE: 0.000215, MAE: 0.011469, R²: 0.0041
  Directional -> Accuracy: 0.5517, MCC: 0.0000, F1: 0.7111

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.40748 | val 0.65734
  Epoch 011 - train 0.39845 | val 0.66987
  Regression -> MSE: 0.000091, MAE: 0.007541, R²: -0.0112
  Directional -> Accuracy: 0.4915, MCC: 0.0000, F1: 0.6591

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.44429 | val 1.27419
  Epoch 011 - train 0.44703 | val 1.31730
  Regression -> MSE: 0.000158, MAE: 0.009967, R²: 0.0024
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.40212 | val 0.75669
  Epoch 011 - train 0.40084 | val 0.77002
  Regression -> MSE: 0.000113, MAE: 0.008684, R²: -0.0072
  Directional -> Accuracy: 0.5172, MCC: 0.0000, F1: 0.6818

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...

[I 2026-02-22 21:47:12,638] Trial 40 finished with value: -0.011715398688939721 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 6, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.1, 'dropout': 0.1, 'batch_size': 32, 'learning_rate': 0.00014874883980415128, 'weight_decay': 7.006035049801518e-05, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.58189946269729, 'early_stopping_min_delta': 0.001820340462454305}. Best is trial 31 with value: -0.011425014985750452.

  Epoch 010 - train 0.44429 | val 1.00657
  Epoch 011 - train 0.43452 | val 1.04269
  Regression -> MSE: 0.000230, MAE: 0.012156, R²: 0.0017
  Directional -> Accuracy: 0.4762, MCC: 0.0000, F1: 0.6452

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.44751 | val 0.77152
  Epoch 020 - train 0.43817 | val 0.78195
  Regression -> MSE: 0.000262, MAE: 0.013021, R²: -0.0584
  Directional -> Accuracy: 0.4156, MCC: -0.1619, F1: 0.4156

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.43476 | val 0.49682
  Epoch 016 - train 0.43072 | val 0.49682
  Regression -> MSE: 0.000685, MAE: 0.019300, R²: -0.0009
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.52853 | val 1.20234
  Epoch 016 - train 0.50070 | val 1.23234
  Regression -> MSE: 0.000324, MAE: 0.014601, R²: -0.0446
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.38349 | val 0.45846
  Epoch 016 - train 0.37250 | val 0.46358
  Regression -> MSE: 0.000351, MAE: 0.014568, R²: -0.0051
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.46427 | val 0.46105
  Epoch 019 - train 0.44981 | val 0.45422
  Regression -> MSE: 0.000202, MAE: 0.009737, R²: 0.0067
  Directional -> Accuracy: 0.6078, MCC: 0.2270, F1: 0.7059

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.44132 | val 1.16222
  Epoch 016 - train 0.44011 | val 1.16901
  Regression -> MSE: 0.000564, MAE: 0.018241, R²: -0.0167
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.47179 | val 0.73411
  Epoch 016 - train 0.46720 | val 0.73506
  Regression -> MSE: 0.000247, MAE: 0.011916, R²: -0.0048
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.49104 | val 0.71976
  Epoch 016 - train 0.47818 | val 0.86228
  Regression -> MSE: 0.000614, MAE: 0.019552, R²: -0.0273
  Directional -> Accuracy: 0.5000, MCC: 0.0722, F1: 0.5417

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.48846 | val 0.66204
  Epoch 016 - train 0.48111 | val 0.74910
  Regression -> MSE: 0.000386, MAE: 0.016071, R²: -0.0071
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.44912 | val 0.74673
  Epoch 018 - train 0.44327 | val 0.80244
  Regression -> MSE: 0.000241, MAE: 0.011797, R²: 0.0037
  Directional -> Accuracy: 0.4429, MCC: 0.0407, F1: 0.5979

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.45093 | val 0.78793
  Epoch 016 - train 0.45200 | val 0.81522
  Regression -> MSE: 0.000320, MAE: 0.013601, R²: -0.0280
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.55479 | val 0.68532
  Epoch 016 - train 0.51828 | val 0.67304
  Regression -> MSE: 0.000692, MAE: 0.019823, R²: -0.0220
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.44441 | val 0.48231
  Epoch 020 - train 0.43309 | val 0.49992
  Regression -> MSE: 0.000162, MAE: 0.009926, R²: -0.1692
  Directional -> Accuracy: 0.4884, MCC: 0.0464, F1: 0.5769

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.41602 | val 0.77900
  Epoch 016 - train 0.40811 | val 0.77498
  Regression -> MSE: 0.000225, MAE: 0.010737, R²: -0.0007
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.45515 | val 1.42863
  Epoch 016 - train 0.45456 | val 1.43085
  Regression -> MSE: 0.000362, MAE: 0.016091, R²: 0.0008
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.50384 | val 0.51446
  Epoch 018 - train 0.47638 | val 0.53076
  Regression -> MSE: 0.000104, MAE: 0.007942, R²: 0.0324
  Directional -> Accuracy: 0.6143, MCC: 0.2155, F1: 0.6667

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.44969 | val 1.12213
  Epoch 016 - train 0.44514 | val 1.13130
  Regression -> MSE: 0.000157, MAE: 0.009884, R²: -0.0084
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.53829 | val 0.72566
  Epoch 016 - train 0.53423 | val 0.71205
  Regression -> MSE: 0.000292, MAE: 0.013952, R²: -0.0726
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.39375 | val 0.73677
  Epoch 020 - train 0.37657 | val 0.72490
  Regression -> MSE: 0.000181, MAE: 0.009808, R²: -0.2108
  Directional -> Accuracy: 0.5692, MCC: 0.2643, F1: 0.4815

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.45555 | val 0.91819
  Epoch 018 - train 0.43920 | val 0.92820
  Regression -> MSE: 0.000253, MAE: 0.011309, R²: -0.1172
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.43835 | val 0.70567
  Epoch 016 - train 0.43495 | val 0.70509
  Regression -> MSE: 0.000153, MAE: 0.008831, R²: -0.0699
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.44368 | val 0.69514
  Epoch 016 - train 0.44835 | val 0.69855
  Regression -> MSE: 0.000174, MAE: 0.010262, R²: -0.0538
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.50997 | val 0.68826
  Epoch 016 - train 0.51084 | val 0.68588
  Regression -> MSE: 0.000086, MAE: 0.007080, R²: -0.0061
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.46060 | val 0.67924
  Epoch 016 - train 0.45994 | val 0.67462
  Regression -> MSE: 0.000212, MAE: 0.011104, R²: -0.0003
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.48122 | val 0.37033
  Epoch 020 - train 0.46248 | val 0.34926
  Regression -> MSE: 0.000134, MAE: 0.009336, R²: -0.4596
  Directional -> Accuracy: 0.5000, MCC: 0.0996, F1: 0.3000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.47096 | val 0.33632
  Epoch 016 - train 0.45637 | val 0.33327
  Regression -> MSE: 0.000104, MAE: 0.008789, R²: -0.0071
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.47759 | val 0.44832
  Epoch 016 - train 0.48075 | val 0.45157
  Regression -> MSE: 0.000233, MAE: 0.012608, R²: -0.0058
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.45398 | val 0.64231
  Epoch 016 - train 0.45498 | val 0.64402
  Regression -> MSE: 0.000190, MAE: 0.008170, R²: -0.1446
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.45369 | val 0.29322
  Epoch 016 - train 0.46041 | val 0.29357
  Regression -> MSE: 0.000236, MAE: 0.011816, R²: 0.0035
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.49996 | val 1.02451
  Epoch 016 - train 0.48550 | val 1.04441
  Regression -> MSE: 0.000231, MAE: 0.009954, R²: -0.0009
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.48416 | val 0.68632
  Epoch 020 - train 0.47244 | val 0.67912
  Regression -> MSE: 0.000133, MAE: 0.008415, R²: 0.0142
  Directional -> Accuracy: 0.5581, MCC: 0.1655, F1: 0.7077

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.46264 | val 0.69958
  Epoch 016 - train 0.47550 | val 0.70646
  Regression -> MSE: 0.000197, MAE: 0.010605, R²: -0.0459
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.41198 | val 0.60296
  Epoch 020 - train 0.40316 | val 0.60256
  Regression -> MSE: 0.000272, MAE: 0.010823, R²: -0.0372
  Directional -> Accuracy: 0.5205, MCC: 0.0572, F1: 0.5205

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.46780 | val 0.38366
  Epoch 016 - train 0.47238 | val 0.38221
  Regression -> MSE: 0.000168, MAE: 0.010383, R²: -0.0089
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.41769 | val 0.60778
  Epoch 016 - train 0.40437 | val 0.67175
  Regression -> MSE: 0.000181, MAE: 0.010279, R²: -0.0068
  Directional -> Accuracy: 0.4773, MCC: -0.0965, F1: 0.2069

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.50378 | val 0.43174
  Epoch 020 - train 0.48130 | val 0.42081
  Regression -> MSE: 0.000352, MAE: 0.012856, R²: -0.0261
  Directional -> Accuracy: 0.5522, MCC: 0.0519, F1: 0.6512

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.49001 | val 0.25900
  Epoch 016 - train 0.49466 | val 0.26829
  Regression -> MSE: 0.000125, MAE: 0.008422, R²: -0.1897
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.45699 | val 0.83948
  Epoch 019 - train 0.45794 | val 0.85367
  Regression -> MSE: 0.000218, MAE: 0.011159, R²: 0.0024
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.46846 | val 1.09868
  Epoch 020 - train 0.46455 | val 1.09752
  Regression -> MSE: 0.000092, MAE: 0.007507, R²: -0.1877
  Directional -> Accuracy: 0.3830, MCC: -0.0508, F1: 0.0645

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.46994 | val 0.30801
  Epoch 016 - train 0.46285 | val 0.31425
  Regression -> MSE: 0.000317, MAE: 0.014359, R²: -0.0313
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.52859 | val 0.19233
  Epoch 016 - train 0.50838 | val 0.19103
  Regression -> MSE: 0.000246, MAE: 0.011443, R²: -0.0108
  Directional -> Accuracy: 0.6316, MCC: 0.2584, F1: 0.6667

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.43738 | val 0.60844
  Epoch 020 - train 0.41505 | val 0.62672
  Regression -> MSE: 0.000085, MAE: 0.007075, R²: -0.0544
  Directional -> Accuracy: 0.5467, MCC: 0.1639, F1: 0.1905

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.50312 | val 0.62587
  Epoch 020 - train 0.49469 | val 0.60731
  Regression -> MSE: 0.000321, MAE: 0.014471, R²: -0.0460
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.46754 | val 0.56674
  Epoch 020 - train 0.47127 | val 0.56532
  Regression -> MSE: 0.000101, MAE: 0.007191, R²: -0.0313
  Directional -> Accuracy: 0.5227, MCC: -0.1902, F1: 0.6866

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.54960 | val 0.71398
  Epoch 020 - train 0.51223 | val 0.70418
  Regression -> MSE: 0.000268, MAE: 0.012294, R²: -0.5600
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.43367 | val 0.63566
  Epoch 016 - train 0.43820 | val 0.62584
  Regression -> MSE: 0.000226, MAE: 0.011858, R²: -0.0141
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.45057 | val 0.66748
  Epoch 016 - train 0.44083 | val 0.68426
  Regression -> MSE: 0.000094, MAE: 0.007747, R²: -0.0182
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.50025 | val 1.00413
  Epoch 016 - train 0.48258 | val 1.01630
  Regression -> MSE: 0.000164, MAE: 0.010295, R²: -0.0023
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.44552 | val 0.78303
  Epoch 016 - train 0.45772 | val 0.79503
  Regression -> MSE: 0.000119, MAE: 0.008998, R²: -0.0263
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.46875 | val 0.91545

[I 2026-02-22 21:49:19,434] Trial 41 finished with value: -0.011567542638507664 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.1, 'dropout': 0.0, 'batch_size': 32, 'learning_rate': 5.720945845405703e-06, 'weight_decay': 6.028695056049027e-07, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 1.6440065675942979, 'early_stopping_min_delta': 0.007165971546806944}. Best is trial 31 with value: -0.011425014985750452.

  Epoch 016 - train 0.47742 | val 0.92794
  Regression -> MSE: 0.000242, MAE: 0.012368, R²: -0.0192
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.46867 | val 0.76526
  Epoch 016 - train 0.46378 | val 0.76211
  Regression -> MSE: 0.000248, MAE: 0.012618, R²: -0.0037
  Directional -> Accuracy: 0.4286, MCC: -0.1524, F1: 0.3714

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.46737 | val 0.48844
  Epoch 016 - train 0.45787 | val 0.51617
  Regression -> MSE: 0.000694, MAE: 0.019474, R²: -0.0134
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.47527 | val 0.98330
  Epoch 016 - train 0.48228 | val 1.00136
  Regression -> MSE: 0.000322, MAE: 0.014551, R²: -0.0391
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.37316 | val 0.44329
  Epoch 016 - train 0.36461 | val 0.45393
  Regression -> MSE: 0.000353, MAE: 0.014668, R²: -0.0092
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.45297 | val 0.51928
  Epoch 016 - train 0.46645 | val 0.51702
  Regression -> MSE: 0.000206, MAE: 0.010166, R²: -0.0130
  Directional -> Accuracy: 0.4902, MCC: -0.1289, F1: 0.6486

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.46536 | val 1.13765
  Epoch 016 - train 0.47242 | val 1.20366
  Regression -> MSE: 0.000551, MAE: 0.018083, R²: 0.0077
  Directional -> Accuracy: 0.4894, MCC: 0.0000, F1: 0.6571

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.44484 | val 0.66470
  Epoch 016 - train 0.44440 | val 0.66313
  Regression -> MSE: 0.000246, MAE: 0.012110, R²: -0.0010
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.44625 | val 0.64232
  Epoch 020 - train 0.43499 | val 0.66714
  Regression -> MSE: 0.000605, MAE: 0.019254, R²: -0.0124
  Directional -> Accuracy: 0.5909, MCC: 0.1003, F1: 0.3571

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.46412 | val 0.63617
  Epoch 016 - train 0.45642 | val 0.62381
  Regression -> MSE: 0.000381, MAE: 0.016098, R²: 0.0057
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.47393 | val 0.70634
  Epoch 016 - train 0.47367 | val 0.70434
  Regression -> MSE: 0.000245, MAE: 0.012304, R²: -0.0143
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.44423 | val 0.70096
  Epoch 020 - train 0.44488 | val 0.69947
  Regression -> MSE: 0.000350, MAE: 0.014064, R²: -0.1267
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.47327 | val 0.56748
  Epoch 020 - train 0.44761 | val 0.57030
  Regression -> MSE: 0.000706, MAE: 0.020126, R²: -0.0420
  Directional -> Accuracy: 0.4828, MCC: -0.0476, F1: 0.6154

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.45265 | val 0.79534
  Epoch 016 - train 0.44561 | val 0.92806
  Regression -> MSE: 0.000140, MAE: 0.009022, R²: -0.0130
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.41849 | val 0.71319
  Epoch 016 - train 0.40525 | val 0.71914
  Regression -> MSE: 0.000224, MAE: 0.010731, R²: 0.0022
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.46405 | val 1.31892
  Epoch 016 - train 0.45557 | val 1.31951
  Regression -> MSE: 0.000362, MAE: 0.016185, R²: -0.0001
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.48840 | val 0.70404
  Epoch 016 - train 0.49165 | val 0.68849
  Regression -> MSE: 0.000110, MAE: 0.008001, R²: -0.0209
  Directional -> Accuracy: 0.5571, MCC: 0.0890, F1: 0.7048

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.45770 | val 1.15112
  Epoch 016 - train 0.44527 | val 1.15049
  Regression -> MSE: 0.000169, MAE: 0.010551, R²: -0.0858
  Directional -> Accuracy: 0.3729, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.50447 | val 0.89586
  Epoch 016 - train 0.49434 | val 0.84306
  Regression -> MSE: 0.000298, MAE: 0.013114, R²: -0.0953
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.38979 | val 0.70977
  Epoch 016 - train 0.38300 | val 0.70776
  Regression -> MSE: 0.000166, MAE: 0.009087, R²: -0.1068
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.51329 | val 0.95858
  Epoch 018 - train 0.48734 | val 0.95334
  Regression -> MSE: 0.000268, MAE: 0.011713, R²: -0.1865
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.46821 | val 0.64935
  Epoch 020 - train 0.45725 | val 0.65069
  Regression -> MSE: 0.000160, MAE: 0.009330, R²: -0.1168
  Directional -> Accuracy: 0.3750, MCC: -0.1155, F1: 0.2105

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.47293 | val 0.84107
  Epoch 016 - train 0.47835 | val 0.82767
  Regression -> MSE: 0.000165, MAE: 0.010609, R²: 0.0027
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.51166 | val 0.66106
  Epoch 016 - train 0.51039 | val 0.66339
  Regression -> MSE: 0.000085, MAE: 0.007034, R²: -0.0016
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.48144 | val 1.00438
  Epoch 016 - train 0.46881 | val 0.97436
  Regression -> MSE: 0.000215, MAE: 0.011137, R²: -0.0129
  Directional -> Accuracy: 0.5152, MCC: 0.0011, F1: 0.3333

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.40070 | val 0.39126
  Epoch 016 - train 0.39157 | val 0.38893
  Regression -> MSE: 0.000096, MAE: 0.008123, R²: -0.0479
  Directional -> Accuracy: 0.5714, MCC: 0.1057, F1: 0.6667

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.48480 | val 0.35204
  Epoch 016 - train 0.49734 | val 0.38209
  Regression -> MSE: 0.000105, MAE: 0.008848, R²: -0.0136
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.48251 | val 0.49549
  Epoch 016 - train 0.48093 | val 0.52332
  Regression -> MSE: 0.000231, MAE: 0.012538, R²: 0.0001
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.45624 | val 0.68344
  Epoch 016 - train 0.45963 | val 0.68645
  Regression -> MSE: 0.000177, MAE: 0.007937, R²: -0.0625
  Directional -> Accuracy: 0.4737, MCC: -0.1635, F1: 0.6154

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.47543 | val 0.28769
  Epoch 020 - train 0.45362 | val 0.34650
  Regression -> MSE: 0.000240, MAE: 0.011946, R²: -0.0157
  Directional -> Accuracy: 0.4878, MCC: -0.1407, F1: 0.6441

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.47385 | val 0.92900
  Epoch 016 - train 0.46411 | val 0.95481
  Regression -> MSE: 0.000230, MAE: 0.009856, R²: 0.0027
  Directional -> Accuracy: 0.4884, MCC: -0.0397, F1: 0.3125

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.45703 | val 0.67350
  Epoch 016 - train 0.46291 | val 0.72034
  Regression -> MSE: 0.000137, MAE: 0.008244, R²: -0.0154
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.45676 | val 0.65221
  Epoch 016 - train 0.45313 | val 0.65540
  Regression -> MSE: 0.000201, MAE: 0.010747, R²: -0.0662
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.38564 | val 0.71209
  Epoch 016 - train 0.38870 | val 0.70085
  Regression -> MSE: 0.000267, MAE: 0.010585, R²: -0.0185
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.47323 | val 0.38638
  Epoch 016 - train 0.45518 | val 0.44334
  Regression -> MSE: 0.000174, MAE: 0.010446, R²: -0.0410
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.41146 | val 0.53259
  Epoch 016 - train 0.40216 | val 0.56479
  Regression -> MSE: 0.000182, MAE: 0.010296, R²: -0.0112
  Directional -> Accuracy: 0.4545, MCC: -0.1668, F1: 0.1429

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.48511 | val 0.54115
  Epoch 016 - train 0.47441 | val 0.52956
  Regression -> MSE: 0.000347, MAE: 0.011791, R²: -0.0139
  Directional -> Accuracy: 0.5821, MCC: 0.0958, F1: 0.7200

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.49817 | val 0.25558
  Epoch 016 - train 0.49051 | val 0.27365
  Regression -> MSE: 0.000125, MAE: 0.008405, R²: -0.1898
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.43942 | val 0.81417
  Epoch 019 - train 0.44630 | val 0.81405
  Regression -> MSE: 0.000221, MAE: 0.011313, R²: -0.0115
  Directional -> Accuracy: 0.5439, MCC: 0.0710, F1: 0.2778

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.45299 | val 1.05329
  Epoch 020 - train 0.44301 | val 1.05297
  Regression -> MSE: 0.000087, MAE: 0.007350, R²: -0.1258
  Directional -> Accuracy: 0.4255, MCC: -0.0182, F1: 0.3077

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.43968 | val 0.31522
  Epoch 016 - train 0.43593 | val 0.32491
  Regression -> MSE: 0.000321, MAE: 0.014593, R²: -0.0438
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.47959 | val 0.20867
  Epoch 016 - train 0.48042 | val 0.20881
  Regression -> MSE: 0.000252, MAE: 0.011497, R²: -0.0330
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.42013 | val 0.56295
  Epoch 020 - train 0.43077 | val 0.56604
  Regression -> MSE: 0.000089, MAE: 0.007625, R²: -0.1020
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.48895 | val 0.60933
  Epoch 020 - train 0.45809 | val 0.56035
  Regression -> MSE: 0.000301, MAE: 0.014619, R²: 0.0203
  Directional -> Accuracy: 0.5319, MCC: 0.0852, F1: 0.3889

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.44770 | val 0.51277
  Epoch 020 - train 0.45208 | val 0.50478
  Regression -> MSE: 0.000096, MAE: 0.007165, R²: 0.0178
  Directional -> Accuracy: 0.6136, MCC: 0.1841, F1: 0.7119

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.46149 | val 0.69175
  Epoch 020 - train 0.47326 | val 0.69691
  Regression -> MSE: 0.000172, MAE: 0.009417, R²: 0.0004
  Directional -> Accuracy: 0.6122, MCC: 0.0861, F1: 0.2400

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.41168 | val 0.67705
  Epoch 016 - train 0.40732 | val 0.70182
  Regression -> MSE: 0.000223, MAE: 0.011784, R²: 0.0008
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.44349 | val 0.77306
  Epoch 016 - train 0.43699 | val 0.80885
  Regression -> MSE: 0.000092, MAE: 0.007668, R²: 0.0008
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.48616 | val 0.91305
  Epoch 020 - train 0.48741 | val 0.91572
  Regression -> MSE: 0.000170, MAE: 0.010459, R²: -0.0367
  Directional -> Accuracy: 0.4630, MCC: -0.0695, F1: 0.1714

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.47615 | val 0.67918
  Epoch 016 - train 0.47050 | val 0.67779
  Regression -> MSE: 0.000131, MAE: 0.009125, R²: -0.1328
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.46993 | val 0.83249

[I 2026-02-22 21:51:22,224] Trial 42 finished with value: -0.01149572454535134 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.1, 'dropout': 0.0, 'batch_size': 32, 'learning_rate': 2.444485534220497e-06, 'weight_decay': 1.1305948031824483e-06, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 1.4549391563394476, 'early_stopping_min_delta': 0.007449246037429216}. Best is trial 31 with value: -0.011425014985750452.

  Epoch 016 - train 0.46460 | val 0.83120
  Regression -> MSE: 0.000246, MAE: 0.012381, R²: -0.0366
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: regression
Sequence length: 12
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.42925 | val 0.67825
  Epoch 016 - train 0.42211 | val 0.68170
  Regression -> MSE: 0.000247, MAE: 0.012552, R²: -0.0041
  Directional -> Accuracy: 0.4487, MCC: 0.0000, F1: 0.6195

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 88). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.45540 | val 0.41878
  Epoch 016 - train 0.45661 | val 0.43723
  Regression -> MSE: 0.000702, MAE: 0.019797, R²: -0.0149
  Directional -> Accuracy: 0.4468, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 88). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.45852 | val 0.89364
  Epoch 016 - train 0.46532 | val 0.88691
  Regression -> MSE: 0.000351, MAE: 0.015051, R²: -0.0167
  Directional -> Accuracy: 0.6042, MCC: 0.2338, F1: 0.7246

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.40419 | val 0.39383
  Epoch 020 - train 0.40164 | val 0.40062
  Regression -> MSE: 0.000370, MAE: 0.014915, R²: -0.0722
  Directional -> Accuracy: 0.4605, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.43908 | val 0.43611
  Epoch 020 - train 0.43266 | val 0.44633
  Regression -> MSE: 0.000195, MAE: 0.009472, R²: 0.0271
  Directional -> Accuracy: 0.6923, MCC: 0.4024, F1: 0.6800

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.44081 | val 1.05942
  Epoch 016 - train 0.45602 | val 1.06722
  Regression -> MSE: 0.000569, MAE: 0.018355, R²: 0.0050
  Directional -> Accuracy: 0.5102, MCC: 0.0000, F1: 0.6757

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.47717 | val 0.64329
  Epoch 016 - train 0.47547 | val 0.64198
  Regression -> MSE: 0.000249, MAE: 0.011973, R²: -0.0122
  Directional -> Accuracy: 0.6000, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 88). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 88). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.44642 | val 0.64417
  Epoch 020 - train 0.46675 | val 0.63752
  Regression -> MSE: 0.000589, MAE: 0.018590, R²: -0.0073
  Directional -> Accuracy: 0.6222, MCC: 0.1924, F1: 0.4138

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.44923 | val 0.77265
  Epoch 016 - train 0.44276 | val 0.80997
  Regression -> MSE: 0.000338, MAE: 0.015073, R²: -0.0004
  Directional -> Accuracy: 0.3810, MCC: 0.0000, F1: 0.5517

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 88). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 88). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.51090 | val 0.90979
  Epoch 016 - train 0.51648 | val 0.85663
  Regression -> MSE: 0.000241, MAE: 0.011819, R²: -0.0121
  Directional -> Accuracy: 0.4366, MCC: -0.0312, F1: 0.5918

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.43000 | val 0.84736
  Epoch 016 - train 0.44053 | val 0.84475
  Regression -> MSE: 0.000305, MAE: 0.013557, R²: 0.0024
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.6400

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.48422 | val 0.99012
  Epoch 016 - train 0.48878 | val 1.02744
  Regression -> MSE: 0.000674, MAE: 0.019542, R²: -0.0073
  Directional -> Accuracy: 0.5085, MCC: 0.0112, F1: 0.5915

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.48098 | val 0.51906
  Epoch 016 - train 0.47817 | val 0.55547
  Regression -> MSE: 0.000152, MAE: 0.009402, R²: -0.0169
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 88). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.38933 | val 0.63851
  Epoch 020 - train 0.41380 | val 0.62814
  Regression -> MSE: 0.000231, MAE: 0.010963, R²: -0.0295
  Directional -> Accuracy: 0.4839, MCC: -0.0323, F1: 0.4839

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.47056 | val 1.29474
  Epoch 016 - train 0.47098 | val 1.27763
  Regression -> MSE: 0.000390, MAE: 0.016346, R²: -0.0384
  Directional -> Accuracy: 0.5283, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.50577 | val 0.52603
  Epoch 016 - train 0.50136 | val 0.51781
  Regression -> MSE: 0.000107, MAE: 0.007982, R²: -0.0090
  Directional -> Accuracy: 0.4648, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.43366 | val 1.15825
  Epoch 016 - train 0.43397 | val 1.17526
  Regression -> MSE: 0.000161, MAE: 0.009873, R²: -0.0079
  Directional -> Accuracy: 0.6167, MCC: 0.0000, F1: 0.7629

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.45370 | val 0.41138
  Epoch 016 - train 0.44953 | val 0.40996
  Regression -> MSE: 0.000269, MAE: 0.012841, R²: -0.0033
  Directional -> Accuracy: 0.6104, MCC: 0.0000, F1: 0.7581

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.37268 | val 0.76903
  Epoch 016 - train 0.37877 | val 0.76530
  Regression -> MSE: 0.000152, MAE: 0.008640, R²: -0.0303
  Directional -> Accuracy: 0.5606, MCC: -0.0487, F1: 0.7071

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 88). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.50711 | val 0.95290
  Epoch 016 - train 0.50938 | val 0.93858
  Regression -> MSE: 0.000248, MAE: 0.011220, R²: -0.0927
  Directional -> Accuracy: 0.4605, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.45039 | val 0.61571
  Epoch 019 - train 0.45934 | val 0.62214
  Regression -> MSE: 0.000162, MAE: 0.009065, R²: -0.0947
  Directional -> Accuracy: 0.4694, MCC: 0.0469, F1: 0.4348

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 88). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 88). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 88). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.46918 | val 0.52057
  Epoch 016 - train 0.47725 | val 0.52218
  Regression -> MSE: 0.000197, MAE: 0.010732, R²: -0.1110
  Directional -> Accuracy: 0.4925, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.49634 | val 0.67506
  Epoch 016 - train 0.49269 | val 0.68494
  Regression -> MSE: 0.000083, MAE: 0.006941, R²: 0.0045
  Directional -> Accuracy: 0.5763, MCC: 0.0000, F1: 0.7312

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.47392 | val 0.59329
  Epoch 020 - train 0.45348 | val 0.59399
  Regression -> MSE: 0.000216, MAE: 0.011465, R²: 0.0108
  Directional -> Accuracy: 0.4627, MCC: -0.1287, F1: 0.6327

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.41827 | val 0.32765
  Epoch 016 - train 0.41297 | val 0.32910
  Regression -> MSE: 0.000096, MAE: 0.008117, R²: -0.0520
  Directional -> Accuracy: 0.5789, MCC: 0.1809, F1: 0.5714

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.47775 | val 0.19530
  Epoch 020 - train 0.49057 | val 0.20064
  Regression -> MSE: 0.000149, MAE: 0.009982, R²: -0.1890
  Directional -> Accuracy: 0.4167, MCC: 0.0000, F1: 0.5882

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.48972 | val 0.41680
  Epoch 016 - train 0.48967 | val 0.44098
  Regression -> MSE: 0.000240, MAE: 0.012835, R²: -0.0073
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.7429

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.44916 | val 0.61637
  Epoch 016 - train 0.45425 | val 0.61758
  Regression -> MSE: 0.000167, MAE: 0.007744, R²: -0.0176
  Directional -> Accuracy: 0.5517, MCC: 0.0000, F1: 0.7111

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.53564 | val 0.39947
  Epoch 016 - train 0.50710 | val 0.67991
  Regression -> MSE: 0.000239, MAE: 0.012085, R²: -0.0207
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.46985 | val 0.74771
  Epoch 016 - train 0.47776 | val 0.74828
  Regression -> MSE: 0.000254, MAE: 0.010475, R²: -0.0147
  Directional -> Accuracy: 0.4889, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.49690 | val 0.73015
  Epoch 020 - train 0.47493 | val 0.73008
  Regression -> MSE: 0.000134, MAE: 0.008354, R²: -0.0037
  Directional -> Accuracy: 0.5111, MCC: -0.0138, F1: 0.6207

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.44732 | val 0.63017
  Epoch 016 - train 0.43161 | val 0.62859
  Regression -> MSE: 0.000194, MAE: 0.010509, R²: -0.0278
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.38812 | val 0.68519
  Epoch 016 - train 0.38580 | val 0.68068
  Regression -> MSE: 0.000260, MAE: 0.010557, R²: -0.0060
  Directional -> Accuracy: 0.5676, MCC: 0.0000, F1: 0.7241

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 88). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.43511 | val 0.37151
  Epoch 016 - train 0.43416 | val 0.37944
  Regression -> MSE: 0.000162, MAE: 0.010163, R²: 0.0033
  Directional -> Accuracy: 0.4872, MCC: 0.0000, F1: 0.6552

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.44666 | val 0.67433
  Epoch 016 - train 0.44853 | val 0.71688
  Regression -> MSE: 0.000194, MAE: 0.010867, R²: -0.0606
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.6364

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.46600 | val 0.49392
  Epoch 016 - train 0.46064 | val 0.49241
  Regression -> MSE: 0.000353, MAE: 0.012394, R²: -0.0106
  Directional -> Accuracy: 0.4265, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.47868 | val 0.26431
  Epoch 016 - train 0.48695 | val 0.26773
  Regression -> MSE: 0.000111, MAE: 0.008260, R²: -0.0674
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.51335 | val 0.71612
  Epoch 020 - train 0.48691 | val 0.71099
  Regression -> MSE: 0.000216, MAE: 0.011114, R²: -0.0060
  Directional -> Accuracy: 0.5172, MCC: 0.0346, F1: 0.5000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.45000 | val 1.02889
  Epoch 016 - train 0.44652 | val 1.04408
  Regression -> MSE: 0.000090, MAE: 0.007470, R²: -0.1348
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 88). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 88). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 88). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 88). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.46050 | val 0.32604
  Epoch 016 - train 0.46978 | val 0.34691
  Regression -> MSE: 0.000336, MAE: 0.014932, R²: -0.0237
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 88). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.48822 | val 0.25859
  Epoch 016 - train 0.47527 | val 0.26410
  Regression -> MSE: 0.000251, MAE: 0.011190, R²: -0.0534
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.7000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 88). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 88). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.43617 | val 0.60080
  Epoch 016 - train 0.42483 | val 0.60029
  Regression -> MSE: 0.000081, MAE: 0.007056, R²: -0.0158
  Directional -> Accuracy: 0.4211, MCC: -0.1857, F1: 0.2143

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 88). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 88). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 88). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.47657 | val 0.47621
  Epoch 016 - train 0.47524 | val 0.48102
  Regression -> MSE: 0.000359, MAE: 0.015298, R²: 0.0012
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.47994 | val 0.55283
  Epoch 020 - train 0.47962 | val 0.52251
  Regression -> MSE: 0.000095, MAE: 0.007208, R²: 0.0195
  Directional -> Accuracy: 0.5556, MCC: 0.1581, F1: 0.5000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.48297 | val 0.74011
  Epoch 016 - train 0.47418 | val 0.77414
  Regression -> MSE: 0.000181, MAE: 0.009963, R²: 0.0014
  Directional -> Accuracy: 0.3659, MCC: 0.0000, F1: 0.5357

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.42427 | val 0.59566
  Epoch 016 - train 0.41841 | val 0.59563
  Regression -> MSE: 0.000221, MAE: 0.011688, R²: -0.0060
  Directional -> Accuracy: 0.4561, MCC: -0.1351, F1: 0.5634

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.44512 | val 0.57024
  Epoch 020 - train 0.44826 | val 0.57076
  Regression -> MSE: 0.000098, MAE: 0.008213, R²: -0.0690
  Directional -> Accuracy: 0.4828, MCC: 0.0000, F1: 0.6512

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.48219 | val 1.01984
  Epoch 016 - train 0.48581 | val 1.05881
  Regression -> MSE: 0.000161, MAE: 0.010157, R²: -0.0039
  Directional -> Accuracy: 0.4909, MCC: -0.1839, F1: 0.6585

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.46986 | val 0.65763
  Epoch 018 - train 0.44759 | val 0.64864
  Regression -> MSE: 0.000124, MAE: 0.008876, R²: -0.0852
  Directional -> Accuracy: 0.4912, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.47583 | val 0.85898

[I 2026-02-22 21:52:50,807] Trial 43 finished with value: -0.011478481701179634 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 12, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.1, 'dropout': 0.1, 'batch_size': 32, 'learning_rate': 2.2444187787683552e-06, 'weight_decay': 1.2867572037213946e-06, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 1.465860377035162, 'early_stopping_min_delta': 0.005322723941206834}. Best is trial 31 with value: -0.011425014985750452.

  Epoch 018 - train 0.46310 | val 0.86004
  Regression -> MSE: 0.000238, MAE: 0.012255, R²: -0.0206
  Directional -> Accuracy: 0.5161, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: regression
Sequence length: 12
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.41110 | val 0.64783
  Epoch 020 - train 0.38963 | val 0.64859
  Regression -> MSE: 0.000253, MAE: 0.012913, R²: -0.0321
  Directional -> Accuracy: 0.4615, MCC: -0.0047, F1: 0.5882

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 88). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.42804 | val 0.45055
  Epoch 016 - train 0.42761 | val 0.45969
  Regression -> MSE: 0.000694, MAE: 0.019663, R²: -0.0032
  Directional -> Accuracy: 0.5532, MCC: 0.0000, F1: 0.7123

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 88). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.43601 | val 0.91417
  Epoch 016 - train 0.43822 | val 0.95725
  Regression -> MSE: 0.000354, MAE: 0.015099, R²: -0.0264
  Directional -> Accuracy: 0.6042, MCC: 0.2441, F1: 0.5581

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.34661 | val 0.39967
  Epoch 018 - train 0.34717 | val 0.40883
  Regression -> MSE: 0.000356, MAE: 0.014737, R²: -0.0308
  Directional -> Accuracy: 0.5789, MCC: 0.1375, F1: 0.6800

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.41235 | val 0.40818
  Epoch 016 - train 0.40611 | val 0.40643
  Regression -> MSE: 0.000200, MAE: 0.009864, R²: 0.0024
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.7000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.41336 | val 1.00523
  Epoch 016 - train 0.40923 | val 1.01882
  Regression -> MSE: 0.000591, MAE: 0.018616, R²: -0.0324
  Directional -> Accuracy: 0.4898, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.45706 | val 0.59222
  Epoch 020 - train 0.43147 | val 0.58167
  Regression -> MSE: 0.000268, MAE: 0.012576, R²: -0.0885
  Directional -> Accuracy: 0.5571, MCC: 0.0829, F1: 0.4561

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 88). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 88). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.47179 | val 0.81382
  Epoch 016 - train 0.45669 | val 0.91366
  Regression -> MSE: 0.000648, MAE: 0.020044, R²: -0.1091
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.41896 | val 0.73629
  Epoch 016 - train 0.41525 | val 0.72987
  Regression -> MSE: 0.000338, MAE: 0.014840, R²: 0.0013
  Directional -> Accuracy: 0.3810, MCC: -0.1001, F1: 0.5000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 88). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 88). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.42255 | val 0.79554
  Epoch 016 - train 0.41532 | val 0.83009
  Regression -> MSE: 0.000238, MAE: 0.011891, R²: 0.0010
  Directional -> Accuracy: 0.4366, MCC: 0.0000, F1: 0.6078

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.40097 | val 0.69056
  Epoch 020 - train 0.37936 | val 0.71268
  Regression -> MSE: 0.000375, MAE: 0.014060, R²: -0.2243
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.44432 | val 0.72264
  Epoch 016 - train 0.44172 | val 0.75144
  Regression -> MSE: 0.000673, MAE: 0.019451, R²: -0.0054
  Directional -> Accuracy: 0.4746, MCC: -0.0488, F1: 0.4364

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.42399 | val 0.71116
  Epoch 016 - train 0.41287 | val 1.14263
  Regression -> MSE: 0.000149, MAE: 0.009403, R²: 0.0032
  Directional -> Accuracy: 0.6364, MCC: 0.2673, F1: 0.4667

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 88). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.37723 | val 0.64393
  Epoch 020 - train 0.37005 | val 0.63605
  Regression -> MSE: 0.000224, MAE: 0.010922, R²: 0.0051
  Directional -> Accuracy: 0.4677, MCC: -0.0816, F1: 0.5926

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.43324 | val 1.20737
  Epoch 016 - train 0.42322 | val 1.18981
  Regression -> MSE: 0.000384, MAE: 0.016330, R²: -0.0208
  Directional -> Accuracy: 0.5283, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.44999 | val 0.51943
  Epoch 016 - train 0.43762 | val 0.52256
  Regression -> MSE: 0.000112, MAE: 0.007942, R²: -0.0566
  Directional -> Accuracy: 0.5352, MCC: 0.0000, F1: 0.6972

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.43986 | val 1.23780
  Epoch 016 - train 0.43044 | val 1.19049
  Regression -> MSE: 0.000161, MAE: 0.009951, R²: -0.0053
  Directional -> Accuracy: 0.6167, MCC: 0.0000, F1: 0.7629

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.44015 | val 0.44228
  Epoch 016 - train 0.42640 | val 0.47862
  Regression -> MSE: 0.000274, MAE: 0.012773, R²: -0.0199
  Directional -> Accuracy: 0.6104, MCC: 0.0000, F1: 0.7581

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.38464 | val 0.87608
  Epoch 016 - train 0.37446 | val 0.83296
  Regression -> MSE: 0.000150, MAE: 0.008707, R²: -0.0206
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.7429

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 88). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.42343 | val 0.84037
  Epoch 018 - train 0.41329 | val 0.82792
  Regression -> MSE: 0.000249, MAE: 0.011348, R²: -0.0979
  Directional -> Accuracy: 0.4605, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.44063 | val 0.76078
  Epoch 016 - train 0.43357 | val 0.76908
  Regression -> MSE: 0.000172, MAE: 0.009551, R²: -0.1615
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 88). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 88). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 88). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.40117 | val 0.56379
  Epoch 016 - train 0.39294 | val 0.57858
  Regression -> MSE: 0.000178, MAE: 0.010745, R²: -0.0074
  Directional -> Accuracy: 0.5075, MCC: 0.0000, F1: 0.6733

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.44894 | val 0.61097
  Epoch 016 - train 0.43727 | val 0.61831
  Regression -> MSE: 0.000083, MAE: 0.006885, R²: 0.0079
  Directional -> Accuracy: 0.5763, MCC: 0.0000, F1: 0.7312

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.46273 | val 0.58790
  Epoch 016 - train 0.45251 | val 0.62903
  Regression -> MSE: 0.000220, MAE: 0.011356, R²: -0.0049
  Directional -> Accuracy: 0.4776, MCC: -0.0113, F1: 0.6316

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.39458 | val 0.34352
  Epoch 016 - train 0.38776 | val 0.32966
  Regression -> MSE: 0.000099, MAE: 0.008198, R²: -0.0765
  Directional -> Accuracy: 0.5439, MCC: 0.1963, F1: 0.4091

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.47045 | val 0.23617
  Epoch 016 - train 0.46775 | val 0.26913
  Regression -> MSE: 0.000144, MAE: 0.009829, R²: -0.1422
  Directional -> Accuracy: 0.4167, MCC: 0.0000, F1: 0.5882

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.45043 | val 0.38465
  Epoch 016 - train 0.44124 | val 0.40133
  Regression -> MSE: 0.000243, MAE: 0.012925, R²: -0.0212
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.7429

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.40566 | val 0.50681
  Epoch 020 - train 0.39418 | val 0.49229
  Regression -> MSE: 0.000281, MAE: 0.011867, R²: -0.7160
  Directional -> Accuracy: 0.4828, MCC: 0.1085, F1: 0.1667

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.47390 | val 0.28158
  Epoch 016 - train 0.47561 | val 0.44862
  Regression -> MSE: 0.000239, MAE: 0.012051, R²: -0.0190
  Directional -> Accuracy: 0.3953, MCC: -0.2152, F1: 0.4348

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.45606 | val 0.94371
  Epoch 016 - train 0.44409 | val 1.12529
  Regression -> MSE: 0.000250, MAE: 0.010539, R²: 0.0004
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.45085 | val 0.69258
  Epoch 016 - train 0.44432 | val 0.70298
  Regression -> MSE: 0.000133, MAE: 0.008237, R²: 0.0019
  Directional -> Accuracy: 0.5333, MCC: 0.0144, F1: 0.6866

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.45166 | val 0.62593
  Epoch 016 - train 0.43393 | val 0.65793
  Regression -> MSE: 0.000194, MAE: 0.010590, R²: -0.0318
  Directional -> Accuracy: 0.4706, MCC: -0.0119, F1: 0.0690

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.37858 | val 0.66456
  Epoch 016 - train 0.37215 | val 0.66388
  Regression -> MSE: 0.000261, MAE: 0.010430, R²: -0.0095
  Directional -> Accuracy: 0.5676, MCC: 0.0227, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 88). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.43757 | val 0.35172
  Epoch 016 - train 0.43156 | val 0.35112
  Regression -> MSE: 0.000165, MAE: 0.010111, R²: -0.0164
  Directional -> Accuracy: 0.5128, MCC: 0.0000, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.37345 | val 0.53024
  Epoch 016 - train 0.35908 | val 0.57565
  Regression -> MSE: 0.000182, MAE: 0.010386, R²: 0.0062
  Directional -> Accuracy: 0.5556, MCC: 0.1612, F1: 0.0909

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.42549 | val 0.40115
  Epoch 016 - train 0.40537 | val 0.39569
  Regression -> MSE: 0.000357, MAE: 0.011978, R²: -0.0225
  Directional -> Accuracy: 0.5735, MCC: 0.0000, F1: 0.7290

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.48502 | val 0.27048
  Epoch 020 - train 0.46127 | val 0.25012
  Regression -> MSE: 0.000150, MAE: 0.009063, R²: -0.4490
  Directional -> Accuracy: 0.5227, MCC: 0.1525, F1: 0.0870

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.44366 | val 0.70400
  Epoch 016 - train 0.44044 | val 0.69725
  Regression -> MSE: 0.000219, MAE: 0.011357, R²: -0.0172
  Directional -> Accuracy: 0.4655, MCC: 0.0000, F1: 0.6353

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.44883 | val 0.98535
  Epoch 016 - train 0.44052 | val 1.03435
  Regression -> MSE: 0.000087, MAE: 0.007324, R²: -0.0963
  Directional -> Accuracy: 0.5208, MCC: 0.0990, F1: 0.5306

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 88). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 88). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 88). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 88). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.43170 | val 0.35910
  Epoch 016 - train 0.44352 | val 0.41177
  Regression -> MSE: 0.000353, MAE: 0.015900, R²: -0.0758
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 88). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.44778 | val 0.25124
  Epoch 016 - train 0.44358 | val 0.32068
  Regression -> MSE: 0.000243, MAE: 0.011222, R²: -0.0221
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.7000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 88). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 88). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.40764 | val 0.60979
  Epoch 016 - train 0.40238 | val 0.63976
  Regression -> MSE: 0.000081, MAE: 0.007073, R²: -0.0104
  Directional -> Accuracy: 0.4868, MCC: -0.1155, F1: 0.6549

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 88). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 88). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 88). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.43776 | val 0.47386
  Epoch 020 - train 0.43890 | val 0.47731
  Regression -> MSE: 0.000353, MAE: 0.015248, R²: 0.0188
  Directional -> Accuracy: 0.4792, MCC: -0.0682, F1: 0.6269

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.43229 | val 0.51028
  Epoch 020 - train 0.40581 | val 0.52170
  Regression -> MSE: 0.000094, MAE: 0.007103, R²: 0.0260
  Directional -> Accuracy: 0.4667, MCC: -0.0219, F1: 0.3684

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.47270 | val 0.81647
  Epoch 016 - train 0.45747 | val 0.91904
  Regression -> MSE: 0.000181, MAE: 0.010064, R²: -0.0003
  Directional -> Accuracy: 0.3659, MCC: 0.0000, F1: 0.5357

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.44564 | val 0.58927
  Epoch 016 - train 0.42870 | val 0.57847
  Regression -> MSE: 0.000232, MAE: 0.011957, R²: -0.0577
  Directional -> Accuracy: 0.5439, MCC: 0.0000, F1: 0.7045

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.43075 | val 0.83580
  Epoch 016 - train 0.42493 | val 0.87505
  Regression -> MSE: 0.000095, MAE: 0.007871, R²: -0.0427
  Directional -> Accuracy: 0.4828, MCC: 0.0000, F1: 0.6512

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.44801 | val 0.85238
  Epoch 016 - train 0.44564 | val 0.87684
  Regression -> MSE: 0.000161, MAE: 0.010080, R²: 0.0014
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.40901 | val 0.61047
  Epoch 016 - train 0.40525 | val 0.61974
  Regression -> MSE: 0.000116, MAE: 0.008787, R²: -0.0211
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.46714 | val 0.80315

[I 2026-02-22 21:55:12,633] Trial 44 finished with value: -0.011647723099298376 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 12, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.0, 'dropout': 0.1, 'batch_size': 32, 'learning_rate': 3.1877243383400735e-06, 'weight_decay': 1.8210743304531688e-07, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 1.346156268126235, 'early_stopping_min_delta': 0.005205181184326793}. Best is trial 31 with value: -0.011425014985750452.

  Epoch 016 - train 0.45001 | val 0.83333
  Regression -> MSE: 0.000249, MAE: 0.012530, R²: -0.0677
  Directional -> Accuracy: 0.5161, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: regression
Sequence length: 6
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.45007 | val 0.91947
  Epoch 016 - train 0.46271 | val 0.91442
  Regression -> MSE: 0.000256, MAE: 0.012982, R²: -0.0405
  Directional -> Accuracy: 0.4430, MCC: 0.0000, F1: 0.6140

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 82). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.43810 | val 0.42649
  Epoch 016 - train 0.43597 | val 0.42637
  Regression -> MSE: 0.000683, MAE: 0.019559, R²: -0.0082
  Directional -> Accuracy: 0.5625, MCC: 0.0000, F1: 0.7200

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 82). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.44349 | val 0.99617
  Epoch 016 - train 0.44131 | val 0.99777
  Regression -> MSE: 0.000355, MAE: 0.015370, R²: -0.0221
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.37026 | val 0.56206
  Epoch 016 - train 0.36536 | val 0.54347
  Regression -> MSE: 0.000370, MAE: 0.014973, R²: -0.0409
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.46485 | val 0.48845
  Epoch 016 - train 0.46092 | val 0.49650
  Regression -> MSE: 0.000203, MAE: 0.010372, R²: -0.0249
  Directional -> Accuracy: 0.4717, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.42736 | val 1.15883
  Epoch 016 - train 0.42506 | val 1.18971
  Regression -> MSE: 0.000519, MAE: 0.017700, R²: -0.0461
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.42743 | val 0.55326
  Epoch 016 - train 0.43012 | val 0.55253
  Regression -> MSE: 0.000262, MAE: 0.012306, R²: -0.0220
  Directional -> Accuracy: 0.5915, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 82). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 82). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.44936 | val 0.62306
  Epoch 020 - train 0.46346 | val 0.64435
  Regression -> MSE: 0.000620, MAE: 0.019560, R²: -0.0946
  Directional -> Accuracy: 0.4043, MCC: 0.0000, F1: 0.5758

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.43751 | val 0.73620
  Epoch 016 - train 0.44221 | val 0.77991
  Regression -> MSE: 0.000390, MAE: 0.015695, R²: -0.0136
  Directional -> Accuracy: 0.4186, MCC: -0.2040, F1: 0.2857

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 82). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 82). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.46239 | val 0.57787
  Epoch 016 - train 0.45305 | val 0.57657
  Regression -> MSE: 0.000241, MAE: 0.011760, R²: -0.0119
  Directional -> Accuracy: 0.4861, MCC: -0.0125, F1: 0.4789

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.41207 | val 0.83854
  Epoch 016 - train 0.40497 | val 0.85113
  Regression -> MSE: 0.000309, MAE: 0.013854, R²: -0.0050
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.47720 | val 0.89148
  Epoch 016 - train 0.46895 | val 0.90245
  Regression -> MSE: 0.000662, MAE: 0.019315, R²: -0.0046
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.44522 | val 0.41881
  Epoch 020 - train 0.42763 | val 0.42515
  Regression -> MSE: 0.000147, MAE: 0.009475, R²: -0.0032
  Directional -> Accuracy: 0.4444, MCC: -0.0901, F1: 0.5763

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 82). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.38559 | val 0.61687
  Epoch 017 - train 0.37985 | val 0.61670
  Regression -> MSE: 0.000224, MAE: 0.010850, R²: 0.0046
  Directional -> Accuracy: 0.4921, MCC: -0.0108, F1: 0.5676

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.46653 | val 1.94997
  Epoch 016 - train 0.45917 | val 1.99383
  Regression -> MSE: 0.000380, MAE: 0.016756, R²: 0.0074
  Directional -> Accuracy: 0.4815, MCC: 0.0000, F1: 0.6500

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.44607 | val 0.48797
  Epoch 016 - train 0.44404 | val 0.48843
  Regression -> MSE: 0.000104, MAE: 0.007774, R²: 0.0072
  Directional -> Accuracy: 0.5833, MCC: 0.1873, F1: 0.7170

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.44135 | val 0.83439
  Epoch 016 - train 0.43847 | val 0.83831
  Regression -> MSE: 0.000160, MAE: 0.010004, R²: -0.0130
  Directional -> Accuracy: 0.5574, MCC: -0.0094, F1: 0.6824

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.44641 | val 0.44659
  Epoch 016 - train 0.44080 | val 0.44896
  Regression -> MSE: 0.000274, MAE: 0.013082, R²: -0.0125
  Directional -> Accuracy: 0.5897, MCC: -0.0926, F1: 0.7419

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.43617 | val 0.75705
  Epoch 016 - train 0.42685 | val 0.75608
  Regression -> MSE: 0.000171, MAE: 0.009357, R²: -0.1060
  Directional -> Accuracy: 0.5672, MCC: 0.2405, F1: 0.4912

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 82). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.47892 | val 0.76647
  Epoch 016 - train 0.47231 | val 0.76320
  Regression -> MSE: 0.000235, MAE: 0.010984, R²: -0.0150
  Directional -> Accuracy: 0.6623, MCC: 0.3139, F1: 0.7234

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.42370 | val 0.58153
  Epoch 016 - train 0.43076 | val 0.58945
  Regression -> MSE: 0.000153, MAE: 0.008887, R²: -0.0237
  Directional -> Accuracy: 0.6200, MCC: 0.0000, F1: 0.7654

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 82). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 82). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 82). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.41451 | val 0.51205
  Epoch 016 - train 0.40944 | val 0.51347
  Regression -> MSE: 0.000192, MAE: 0.010770, R²: -0.0562
  Directional -> Accuracy: 0.5294, MCC: 0.0605, F1: 0.4667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.47454 | val 0.56572
  Epoch 016 - train 0.47624 | val 0.56507
  Regression -> MSE: 0.000082, MAE: 0.006854, R²: 0.0049
  Directional -> Accuracy: 0.5833, MCC: 0.0000, F1: 0.7368

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.48502 | val 1.08516
  Epoch 016 - train 0.48378 | val 1.08832
  Regression -> MSE: 0.000234, MAE: 0.011393, R²: -0.0879
  Directional -> Accuracy: 0.5147, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.39100 | val 0.33287
  Epoch 016 - train 0.37864 | val 0.33189
  Regression -> MSE: 0.000102, MAE: 0.008225, R²: -0.1362
  Directional -> Accuracy: 0.4483, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.43617 | val 0.19445
  Epoch 016 - train 0.44059 | val 0.20945
  Regression -> MSE: 0.000129, MAE: 0.009385, R²: -0.0327
  Directional -> Accuracy: 0.3673, MCC: -0.2500, F1: 0.3673

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.44138 | val 0.24537
  Epoch 016 - train 0.43597 | val 0.25851
  Regression -> MSE: 0.000318, MAE: 0.014159, R²: -0.0910
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.43664 | val 0.46720
  Epoch 020 - train 0.42845 | val 0.46695
  Regression -> MSE: 0.000386, MAE: 0.015177, R²: -1.3985
  Directional -> Accuracy: 0.4407, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.47286 | val 0.41790
  Epoch 016 - train 0.46078 | val 0.42826
  Regression -> MSE: 0.000234, MAE: 0.011955, R²: -0.0152
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.6866

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.45962 | val 0.64538
  Epoch 016 - train 0.44121 | val 0.64928
  Regression -> MSE: 0.000258, MAE: 0.010759, R²: 0.0055
  Directional -> Accuracy: 0.4565, MCC: -0.1054, F1: 0.2424

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.47209 | val 0.76411
  Epoch 016 - train 0.47262 | val 0.84056
  Regression -> MSE: 0.000152, MAE: 0.008987, R²: -0.0845
  Directional -> Accuracy: 0.4565, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.47152 | val 0.66527
  Epoch 016 - train 0.47691 | val 0.66591
  Regression -> MSE: 0.000186, MAE: 0.010475, R²: -0.0017
  Directional -> Accuracy: 0.5192, MCC: 0.0000, F1: 0.6835

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.37906 | val 0.57517
  Epoch 016 - train 0.38223 | val 0.57406
  Regression -> MSE: 0.000270, MAE: 0.010758, R²: -0.0339
  Directional -> Accuracy: 0.4667, MCC: 0.0316, F1: 0.2308

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 82). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.42346 | val 0.51018
  Epoch 016 - train 0.42088 | val 0.55691
  Regression -> MSE: 0.000165, MAE: 0.010078, R²: -0.0187
  Directional -> Accuracy: 0.5122, MCC: 0.0000, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.40047 | val 0.40179
  Epoch 016 - train 0.38401 | val 0.40323
  Regression -> MSE: 0.000220, MAE: 0.011229, R²: -0.0298
  Directional -> Accuracy: 0.4565, MCC: 0.0000, F1: 0.6269

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.43212 | val 0.45879
  Epoch 016 - train 0.43065 | val 0.45550
  Regression -> MSE: 0.000357, MAE: 0.012506, R²: -0.0375
  Directional -> Accuracy: 0.3768, MCC: -0.2150, F1: 0.0444

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.44851 | val 0.24997
  Epoch 020 - train 0.43813 | val 0.26411
  Regression -> MSE: 0.000110, MAE: 0.008067, R²: -0.0882
  Directional -> Accuracy: 0.5333, MCC: 0.0653, F1: 0.5532

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.46469 | val 0.63875
  Epoch 016 - train 0.46227 | val 0.63738
  Regression -> MSE: 0.000213, MAE: 0.011010, R²: -0.0087
  Directional -> Accuracy: 0.4746, MCC: -0.0284, F1: 0.5753

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.43636 | val 0.94299
  Epoch 016 - train 0.43423 | val 0.94147
  Regression -> MSE: 0.000081, MAE: 0.007093, R²: -0.0212
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.7595

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 82). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 82). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 82). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 82). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.41867 | val 0.38872
  Epoch 016 - train 0.41987 | val 0.40017
  Regression -> MSE: 0.000330, MAE: 0.015176, R²: -0.0509
  Directional -> Accuracy: 0.3333, MCC: 0.0000, F1: 0.5000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 82). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.44407 | val 0.30209
  Epoch 019 - train 0.42377 | val 0.30949
  Regression -> MSE: 0.000251, MAE: 0.011151, R²: -0.1008
  Directional -> Accuracy: 0.4878, MCC: -0.1543, F1: 0.6557

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 82). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 82). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.42460 | val 0.55584
  Epoch 016 - train 0.42479 | val 0.55217
  Regression -> MSE: 0.000082, MAE: 0.007178, R²: -0.0062
  Directional -> Accuracy: 0.5065, MCC: 0.0000, F1: 0.6724

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 82). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 82). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.44761 | val 0.42203
  Epoch 016 - train 0.45175 | val 0.43718
  Regression -> MSE: 0.000371, MAE: 0.015618, R²: -0.0039
  Directional -> Accuracy: 0.4898, MCC: 0.0000, F1: 0.6575

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.45228 | val 0.49926
  Epoch 018 - train 0.44545 | val 0.50381
  Regression -> MSE: 0.000095, MAE: 0.007252, R²: -0.0014
  Directional -> Accuracy: 0.4894, MCC: 0.0512, F1: 0.4000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.45883 | val 0.62354
  Epoch 020 - train 0.46331 | val 0.61380
  Regression -> MSE: 0.000234, MAE: 0.010950, R²: -0.2265
  Directional -> Accuracy: 0.6429, MCC: 0.0667, F1: 0.1176

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.48507 | val 1.04518
  Epoch 016 - train 0.49262 | val 1.05424
  Regression -> MSE: 0.000252, MAE: 0.012502, R²: -0.1669
  Directional -> Accuracy: 0.4483, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.45749 | val 0.51857
  Epoch 016 - train 0.47391 | val 0.51933
  Regression -> MSE: 0.000090, MAE: 0.007520, R²: -0.0028
  Directional -> Accuracy: 0.4915, MCC: 0.0000, F1: 0.6591

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.49924 | val 0.93687
  Epoch 016 - train 0.49502 | val 0.94083
  Regression -> MSE: 0.000167, MAE: 0.010324, R²: -0.0531
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.0000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.45817 | val 0.55833
  Epoch 020 - train 0.45070 | val 0.55509
  Regression -> MSE: 0.000191, MAE: 0.011054, R²: -0.7007
  Directional -> Accuracy: 0.4828, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.42740 | val 0.71357
  Epoch 018 - train 0.43288 | val 0.71448
  Regression -> MSE: 0.000244, MAE: 0.012324, R²: -0.0604
  Directional -> Accuracy: 0.5238, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan

[I 2026-02-22 21:55:32,186] Trial 45 finished with value: -0.011810852882496545 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 6, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 32, 'learning_rate': 2.2575851541309563e-06, 'weight_decay': 8.869541740816201e-07, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 1.2120969205014067, 'early_stopping_min_delta': 0.0037721319536803194}. Best is trial 31 with value: -0.011425014985750452.

Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: regression
Sequence length: 12
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.59119 | val 0.72968
  Epoch 016 - train 0.55605 | val 0.72922
  Regression -> MSE: 0.000247, MAE: 0.012541, R²: -0.0043
  Directional -> Accuracy: 0.5513, MCC: 0.0167, F1: 0.0541

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 88). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.55029 | val 0.45543
  Epoch 020 - train 0.55996 | val 0.45122
  Regression -> MSE: 0.000697, MAE: 0.019881, R²: -0.0085
  Directional -> Accuracy: 0.5532, MCC: 0.1936, F1: 0.4324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 88). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.61900 | val 1.01994
  Epoch 016 - train 0.57744 | val 1.02852
  Regression -> MSE: 0.000356, MAE: 0.015141, R²: -0.0315
  Directional -> Accuracy: 0.5625, MCC: 0.1566, F1: 0.5116

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.53131 | val 0.50490
  Epoch 016 - train 0.49990 | val 0.51974
  Regression -> MSE: 0.000354, MAE: 0.014536, R²: -0.0253
  Directional -> Accuracy: 0.4605, MCC: -0.0308, F1: 0.1961

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.55502 | val 0.47743
  Epoch 016 - train 0.54161 | val 0.47882
  Regression -> MSE: 0.000200, MAE: 0.010075, R²: 0.0044
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.59998 | val 1.24942
  Epoch 016 - train 0.61174 | val 1.39977
  Regression -> MSE: 0.000569, MAE: 0.018276, R²: 0.0066
  Directional -> Accuracy: 0.5102, MCC: 0.0156, F1: 0.5714

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.62172 | val 0.75998
  Epoch 016 - train 0.59271 | val 0.75770
  Regression -> MSE: 0.000248, MAE: 0.012363, R²: -0.0087
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.5714

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 88). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 88). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.59244 | val 0.72592
  Epoch 016 - train 0.60006 | val 0.77825
  Regression -> MSE: 0.000616, MAE: 0.019473, R²: -0.0532
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.60821 | val 0.88927
  Epoch 016 - train 0.60305 | val 0.91200
  Regression -> MSE: 0.000343, MAE: 0.015388, R²: -0.0150
  Directional -> Accuracy: 0.3810, MCC: 0.0000, F1: 0.5517

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 88). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 88). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.60113 | val 0.75525
  Epoch 016 - train 0.60294 | val 0.74885
  Regression -> MSE: 0.000243, MAE: 0.011534, R²: -0.0191
  Directional -> Accuracy: 0.5634, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.54947 | val 0.87810
  Epoch 016 - train 0.56244 | val 0.88435
  Regression -> MSE: 0.000310, MAE: 0.013571, R²: -0.0126
  Directional -> Accuracy: 0.4510, MCC: -0.1906, F1: 0.1250

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.54354 | val 0.61620
  Epoch 016 - train 0.55343 | val 0.61849
  Regression -> MSE: 0.000670, MAE: 0.019457, R²: -0.0011
  Directional -> Accuracy: 0.5085, MCC: 0.0000, F1: 0.6742

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.58318 | val 0.51903
  Epoch 016 - train 0.69160 | val 0.52482
  Regression -> MSE: 0.000151, MAE: 0.009432, R²: -0.0089
  Directional -> Accuracy: 0.5455, MCC: 0.0199, F1: 0.0909

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 88). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.59076 | val 0.86788
  Epoch 016 - train 0.64128 | val 0.86169
  Regression -> MSE: 0.000225, MAE: 0.010795, R²: -0.0009
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.63129 | val 1.49800
  Epoch 016 - train 0.59944 | val 1.50569
  Regression -> MSE: 0.000380, MAE: 0.016364, R²: -0.0111
  Directional -> Accuracy: 0.4717, MCC: -0.0700, F1: 0.3913

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.61358 | val 0.52851
  Epoch 016 - train 0.58809 | val 0.52214
  Regression -> MSE: 0.000106, MAE: 0.007943, R²: 0.0023
  Directional -> Accuracy: 0.4648, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.61830 | val 1.20131
  Epoch 016 - train 0.57747 | val 1.20810
  Regression -> MSE: 0.000161, MAE: 0.009762, R²: -0.0053
  Directional -> Accuracy: 0.6167, MCC: 0.0000, F1: 0.7629

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.60824 | val 0.45730
  Epoch 016 - train 0.58954 | val 0.45786
  Regression -> MSE: 0.000277, MAE: 0.013381, R²: -0.0300
  Directional -> Accuracy: 0.3896, MCC: -0.1616, F1: 0.3562

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.49232 | val 0.78656
  Epoch 016 - train 0.48246 | val 0.78770
  Regression -> MSE: 0.000172, MAE: 0.009262, R²: -0.1657
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 88). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.67206 | val 1.16117
  Epoch 016 - train 0.71499 | val 1.16572
  Regression -> MSE: 0.000252, MAE: 0.011367, R²: -0.1122
  Directional -> Accuracy: 0.4605, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.54091 | val 0.95523
  Epoch 016 - train 0.62228 | val 0.99834
  Regression -> MSE: 0.000150, MAE: 0.008704, R²: -0.0091
  Directional -> Accuracy: 0.6327, MCC: 0.0000, F1: 0.7750

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 88). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 88). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 88). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.58667 | val 0.54965
  Epoch 016 - train 0.58827 | val 0.54955
  Regression -> MSE: 0.000182, MAE: 0.010578, R²: -0.0303
  Directional -> Accuracy: 0.4925, MCC: -0.1213, F1: 0.6600

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.57961 | val 0.71735
  Epoch 016 - train 0.60307 | val 0.71665
  Regression -> MSE: 0.000087, MAE: 0.007142, R²: -0.0411
  Directional -> Accuracy: 0.4915, MCC: 0.1392, F1: 0.2857

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.56150 | val 0.66107
  Epoch 016 - train 0.56749 | val 0.65793
  Regression -> MSE: 0.000219, MAE: 0.011328, R²: -0.0003
  Directional -> Accuracy: 0.5224, MCC: 0.0620, F1: 0.5789

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.52235 | val 0.35575
  Epoch 020 - train 0.58402 | val 0.35211
  Regression -> MSE: 0.000114, MAE: 0.008963, R²: -0.2412
  Directional -> Accuracy: 0.3860, MCC: -0.2320, F1: 0.4262

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.55953 | val 0.19876
  Epoch 016 - train 0.55643 | val 0.20320
  Regression -> MSE: 0.000138, MAE: 0.009658, R²: -0.0960
  Directional -> Accuracy: 0.4167, MCC: 0.0000, F1: 0.5882

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.66344 | val 0.40037
  Epoch 016 - train 0.61252 | val 0.40228
  Regression -> MSE: 0.000241, MAE: 0.012887, R²: -0.0140
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.7429

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.54929 | val 0.66592
  Epoch 016 - train 0.55844 | val 0.66515
  Regression -> MSE: 0.000176, MAE: 0.007797, R²: -0.0764
  Directional -> Accuracy: 0.5517, MCC: 0.2036, F1: 0.4091

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.63869 | val 0.36653
  Epoch 016 - train 0.75880 | val 0.52085
  Regression -> MSE: 0.000238, MAE: 0.011993, R²: -0.0160
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.64396 | val 0.98623
  Epoch 016 - train 0.67691 | val 1.00384
  Regression -> MSE: 0.000251, MAE: 0.010577, R²: -0.0012
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.59011 | val 0.80510
  Epoch 016 - train 0.60179 | val 0.82189
  Regression -> MSE: 0.000138, MAE: 0.008534, R²: -0.0376
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.58374 | val 0.76412
  Epoch 016 - train 0.59827 | val 0.77314
  Regression -> MSE: 0.000187, MAE: 0.010497, R²: 0.0058
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.55285 | val 0.68774
  Epoch 016 - train 0.54194 | val 0.69945
  Regression -> MSE: 0.000269, MAE: 0.010591, R²: -0.0394
  Directional -> Accuracy: 0.4730, MCC: -0.0473, F1: 0.4935

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 88). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.55348 | val 0.41837
  Epoch 016 - train 0.61600 | val 0.45363
  Regression -> MSE: 0.000165, MAE: 0.010209, R²: -0.0143
  Directional -> Accuracy: 0.4872, MCC: 0.0000, F1: 0.6552

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.49283 | val 0.56185
  Epoch 016 - train 0.53594 | val 0.56412
  Regression -> MSE: 0.000188, MAE: 0.010676, R²: -0.0311
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.6364

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.49178 | val 0.40586
  Epoch 020 - train 0.50846 | val 0.40511
  Regression -> MSE: 0.000363, MAE: 0.012461, R²: -0.0413
  Directional -> Accuracy: 0.4118, MCC: -0.1057, F1: 0.2000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.59620 | val 0.25761
  Epoch 020 - train 0.64099 | val 0.25076
  Regression -> MSE: 0.000130, MAE: 0.008207, R²: -0.2577
  Directional -> Accuracy: 0.6136, MCC: 0.3107, F1: 0.4138

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.73956 | val 0.96217
  Epoch 016 - train 0.58153 | val 0.96780
  Regression -> MSE: 0.000220, MAE: 0.011353, R²: -0.0229
  Directional -> Accuracy: 0.4655, MCC: 0.0000, F1: 0.6353

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.63075 | val 1.17666
  Epoch 016 - train 0.59412 | val 1.18901
  Regression -> MSE: 0.000084, MAE: 0.007179, R²: -0.0547
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 88). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 88). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 88). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 88). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.56780 | val 0.40306
  Epoch 016 - train 0.59801 | val 0.41497
  Regression -> MSE: 0.000354, MAE: 0.016008, R²: -0.0794
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 88). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.60015 | val 0.24286
  Epoch 016 - train 0.60897 | val 0.24809
  Regression -> MSE: 0.000248, MAE: 0.011169, R²: -0.0410
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.7000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 88). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 88). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.68583 | val 0.71678
  Epoch 016 - train 0.70539 | val 0.70981
  Regression -> MSE: 0.000085, MAE: 0.007082, R²: -0.0576
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 88). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 88). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 88). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.59549 | val 0.55191
  Epoch 016 - train 0.61240 | val 0.55703
  Regression -> MSE: 0.000369, MAE: 0.015342, R²: -0.0256
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.58721 | val 0.58303
  Epoch 020 - train 0.54814 | val 0.56541
  Regression -> MSE: 0.000099, MAE: 0.007020, R²: -0.0232
  Directional -> Accuracy: 0.5778, MCC: 0.1195, F1: 0.7164

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.59092 | val 0.81407
  Epoch 020 - train 0.59277 | val 0.80140
  Regression -> MSE: 0.000185, MAE: 0.009615, R²: -0.0242
  Directional -> Accuracy: 0.6341, MCC: 0.0916, F1: 0.2105

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.58240 | val 0.61699
  Epoch 016 - train 0.59677 | val 0.61822
  Regression -> MSE: 0.000220, MAE: 0.011645, R²: -0.0008
  Directional -> Accuracy: 0.5439, MCC: 0.0000, F1: 0.7045

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.53993 | val 0.68650
  Epoch 016 - train 0.63075 | val 0.68432
  Regression -> MSE: 0.000090, MAE: 0.007582, R²: 0.0123
  Directional -> Accuracy: 0.5862, MCC: 0.1807, F1: 0.4286

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.60450 | val 1.00922
  Epoch 016 - train 0.63977 | val 1.01409
  Regression -> MSE: 0.000162, MAE: 0.010167, R²: -0.0071
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.57919 | val 0.69330
  Epoch 018 - train 0.63955 | val 0.69157
  Regression -> MSE: 0.000129, MAE: 0.009001, R²: -0.1273
  Directional -> Accuracy: 0.4737, MCC: -0.1360, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.57062 | val 1.05010

[I 2026-02-22 21:56:59,611] Trial 46 finished with value: -0.01153683789311741 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 12, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.4, 'dropout': 0.8, 'batch_size': 32, 'learning_rate': 1.5446343467669965e-06, 'weight_decay': 2.857269691703273e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 1.8461795911597085, 'early_stopping_min_delta': 0.005817869897187494}. Best is trial 31 with value: -0.011425014985750452.

  Epoch 016 - train 0.56480 | val 1.06203
  Regression -> MSE: 0.000244, MAE: 0.012335, R²: -0.0443
  Directional -> Accuracy: 0.5161, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: regression
Sequence length: 6
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.09706 | val 0.13931
  Epoch 014 - train 0.09652 | val 0.14355
  Regression -> MSE: 0.000276, MAE: 0.013110, R²: -0.1211
  Directional -> Accuracy: 0.5063, MCC: 0.1209, F1: 0.6139

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 82). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.09966 | val 0.21552
  Epoch 011 - train 0.10243 | val 0.15515
  Regression -> MSE: 0.000859, MAE: 0.022108, R²: -0.2684
  Directional -> Accuracy: 0.4375, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 82). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.10522 | val 0.32277
  Epoch 011 - train 0.11121 | val 0.23714
  Regression -> MSE: 0.000415, MAE: 0.015869, R²: -0.1948
  Directional -> Accuracy: 0.5102, MCC: 0.0835, F1: 0.2941

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.08628 | val 0.23402
  Epoch 011 - train 0.08724 | val 0.18722
  Regression -> MSE: 0.000365, MAE: 0.014818, R²: -0.0282
  Directional -> Accuracy: 0.5195, MCC: 0.0527, F1: 0.5067

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.10632 | val 0.11318
  Epoch 011 - train 0.10604 | val 0.10957
  Regression -> MSE: 0.000207, MAE: 0.010221, R²: -0.0453
  Directional -> Accuracy: 0.6604, MCC: 0.3166, F1: 0.6897

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.09056 | val 0.21992
  Epoch 012 - train 0.08575 | val 0.25504
  Regression -> MSE: 0.000490, MAE: 0.017334, R²: 0.0127
  Directional -> Accuracy: 0.4634, MCC: -0.0472, F1: 0.5417

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.10877 | val 0.25886
  Epoch 011 - train 0.10724 | val 0.15588
  Regression -> MSE: 0.000258, MAE: 0.012682, R²: -0.0066
  Directional -> Accuracy: 0.5070, MCC: 0.0727, F1: 0.5333

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 82). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 82). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.10179 | val 0.20087
  Epoch 013 - train 0.08319 | val 0.20633
  Regression -> MSE: 0.000615, MAE: 0.019117, R²: -0.0847
  Directional -> Accuracy: 0.5957, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.10172 | val 0.16813
  Epoch 012 - train 0.09433 | val 0.18252
  Regression -> MSE: 0.000418, MAE: 0.015996, R²: -0.0871
  Directional -> Accuracy: 0.6047, MCC: 0.0473, F1: 0.1053

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 82). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 82). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.10278 | val 0.17267
  Epoch 011 - train 0.10063 | val 0.27092
  Regression -> MSE: 0.000265, MAE: 0.012816, R²: -0.1116
  Directional -> Accuracy: 0.5417, MCC: 0.0921, F1: 0.5217

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.09791 | val 0.17162
  Epoch 011 - train 0.09487 | val 0.17786
  Regression -> MSE: 0.000301, MAE: 0.013663, R²: 0.0202
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.11045 | val 0.14039
  Epoch 011 - train 0.10902 | val 0.13662
  Regression -> MSE: 0.000751, MAE: 0.020866, R²: -0.1403
  Directional -> Accuracy: 0.4000, MCC: -0.2364, F1: 0.5263

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.09778 | val 0.12640
  Epoch 011 - train 0.10092 | val 0.12958
  Regression -> MSE: 0.000147, MAE: 0.009085, R²: -0.0014
  Directional -> Accuracy: 0.5111, MCC: 0.0364, F1: 0.5417

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 82). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.09905 | val 0.14464
  Epoch 011 - train 0.10076 | val 0.14110
  Regression -> MSE: 0.000218, MAE: 0.010853, R²: 0.0294
  Directional -> Accuracy: 0.5079, MCC: 0.0116, F1: 0.4151

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.10401 | val 0.34012
  Epoch 012 - train 0.10275 | val 0.38476
  Regression -> MSE: 0.000382, MAE: 0.016552, R²: 0.0021
  Directional -> Accuracy: 0.5370, MCC: 0.1092, F1: 0.6269

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.11193 | val 0.16450
  Epoch 011 - train 0.10900 | val 0.24581
  Regression -> MSE: 0.000135, MAE: 0.009218, R²: -0.2825
  Directional -> Accuracy: 0.4167, MCC: -0.1572, F1: 0.4000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.10186 | val 0.27756
  Epoch 011 - train 0.10257 | val 0.30502
  Regression -> MSE: 0.000161, MAE: 0.009721, R²: -0.0217
  Directional -> Accuracy: 0.6230, MCC: 0.2282, F1: 0.6761

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.10308 | val 0.14101
  Epoch 012 - train 0.10376 | val 0.14221
  Regression -> MSE: 0.000278, MAE: 0.013306, R²: -0.0245
  Directional -> Accuracy: 0.4359, MCC: 0.1624, F1: 0.1200

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.09935 | val 0.15906
  Epoch 018 - train 0.09576 | val 0.18790
  Regression -> MSE: 0.000250, MAE: 0.012601, R²: -0.6122
  Directional -> Accuracy: 0.4627, MCC: 0.0675, F1: 0.2500

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 82). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.10715 | val 0.16969
  Epoch 013 - train 0.10459 | val 0.16833
  Regression -> MSE: 0.000237, MAE: 0.011066, R²: -0.0242
  Directional -> Accuracy: 0.5455, MCC: 0.1317, F1: 0.4776

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.09553 | val 0.18340
  Epoch 011 - train 0.09579 | val 0.20209
  Regression -> MSE: 0.000157, MAE: 0.009101, R²: -0.0540
  Directional -> Accuracy: 0.6200, MCC: 0.0000, F1: 0.7654

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 82). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 82). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 82). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.09849 | val 0.20068
  Epoch 011 - train 0.09943 | val 0.21157
  Regression -> MSE: 0.000208, MAE: 0.011550, R²: -0.1424
  Directional -> Accuracy: 0.4706, MCC: -0.0589, F1: 0.4857

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.11037 | val 0.16597
  Epoch 011 - train 0.10854 | val 0.19416
  Regression -> MSE: 0.000096, MAE: 0.007710, R²: -0.1680
  Directional -> Accuracy: 0.6000, MCC: 0.1869, F1: 0.6471

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.10936 | val 0.16218
  Epoch 011 - train 0.10862 | val 0.16972
  Regression -> MSE: 0.000238, MAE: 0.011869, R²: -0.1071
  Directional -> Accuracy: 0.5294, MCC: 0.0511, F1: 0.3846

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.09072 | val 0.10771
  Epoch 013 - train 0.09002 | val 0.09456
  Regression -> MSE: 0.000117, MAE: 0.008749, R²: -0.3032
  Directional -> Accuracy: 0.4483, MCC: -0.0197, F1: 0.0588

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.09407 | val 0.51061
  Epoch 012 - train 0.09923 | val 0.57447
  Regression -> MSE: 0.000130, MAE: 0.009390, R²: -0.0368
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.10471 | val 0.08959
  Epoch 011 - train 0.10353 | val 0.07537
  Regression -> MSE: 0.000298, MAE: 0.013506, R²: -0.0237
  Directional -> Accuracy: 0.5778, MCC: 0.0454, F1: 0.6984

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.10359 | val 0.16858
  Epoch 013 - train 0.10376 | val 0.15207
  Regression -> MSE: 0.000265, MAE: 0.011256, R²: -0.6451
  Directional -> Accuracy: 0.4407, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.09785 | val 0.19582
  Epoch 011 - train 0.09773 | val 0.22298
  Regression -> MSE: 0.000227, MAE: 0.012021, R²: 0.0152
  Directional -> Accuracy: 0.4545, MCC: -0.0981, F1: 0.5000

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.09934 | val 0.14793
  Epoch 011 - train 0.09698 | val 0.14968
  Regression -> MSE: 0.000259, MAE: 0.010924, R²: -0.0012
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.5106

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.10322 | val 0.17801
  Epoch 012 - train 0.10744 | val 0.19914
  Regression -> MSE: 0.000164, MAE: 0.009180, R²: -0.1721
  Directional -> Accuracy: 0.5435, MCC: 0.0000, F1: 0.7042

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.11243 | val 0.14055
  Epoch 011 - train 0.10678 | val 0.16121
  Regression -> MSE: 0.000191, MAE: 0.010400, R²: -0.0285
  Directional -> Accuracy: 0.5000, MCC: -0.0142, F1: 0.5806

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.09196 | val 0.17468
  Epoch 012 - train 0.09298 | val 0.14204
  Regression -> MSE: 0.000317, MAE: 0.012338, R²: -0.2154
  Directional -> Accuracy: 0.4800, MCC: 0.0511, F1: 0.2909

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 82). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.09124 | val 0.12255
  Epoch 011 - train 0.09909 | val 0.13263
  Regression -> MSE: 0.000167, MAE: 0.010410, R²: -0.0325
  Directional -> Accuracy: 0.4878, MCC: 0.0000, F1: 0.6557

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.09126 | val 0.20364
  Epoch 011 - train 0.08757 | val 0.12996
  Regression -> MSE: 0.000211, MAE: 0.011071, R²: 0.0148
  Directional -> Accuracy: 0.4783, MCC: -0.0142, F1: 0.5385

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.10099 | val 0.10829
  Epoch 014 - train 0.09927 | val 0.11820
  Regression -> MSE: 0.000350, MAE: 0.012795, R²: -0.0168
  Directional -> Accuracy: 0.4638, MCC: 0.0217, F1: 0.3273

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.09796 | val 0.13195
  Epoch 011 - train 0.10665 | val 0.10981
  Regression -> MSE: 0.000131, MAE: 0.008243, R²: -0.2904
  Directional -> Accuracy: 0.5778, MCC: 0.2528, F1: 0.3448

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.10571 | val 0.15166
  Epoch 013 - train 0.10518 | val 0.18789
  Regression -> MSE: 0.000221, MAE: 0.011431, R²: -0.0432
  Directional -> Accuracy: 0.4576, MCC: -0.0780, F1: 0.4839

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.10155 | val 0.29126
  Epoch 017 - train 0.09608 | val 0.25279
  Regression -> MSE: 0.000091, MAE: 0.007602, R²: -0.1467
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.7595

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 82). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 82). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 82). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 82). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.10085 | val 0.09930
  Epoch 015 - train 0.09494 | val 0.10903
  Regression -> MSE: 0.000391, MAE: 0.017186, R²: -0.2457
  Directional -> Accuracy: 0.3333, MCC: 0.0000, F1: 0.5000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 82). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.09590 | val 0.14096
  Epoch 011 - train 0.09183 | val 0.10085
  Regression -> MSE: 0.000255, MAE: 0.011188, R²: -0.1155
  Directional -> Accuracy: 0.5122, MCC: 0.0290, F1: 0.4737

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 82). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 82). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.10202 | val 0.23287
  Epoch 017 - train 0.09858 | val 0.25142
  Regression -> MSE: 0.000141, MAE: 0.010077, R²: -0.7178
  Directional -> Accuracy: 0.5065, MCC: 0.0000, F1: 0.6724

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 82). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 82). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.10389 | val 0.21505
  Epoch 011 - train 0.10719 | val 0.23202
  Regression -> MSE: 0.000377, MAE: 0.015579, R²: -0.0190
  Directional -> Accuracy: 0.4694, MCC: -0.0601, F1: 0.4800

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.09769 | val 0.16759
  Epoch 015 - train 0.09436 | val 0.14538
  Regression -> MSE: 0.000087, MAE: 0.006826, R²: 0.0842
  Directional -> Accuracy: 0.5745, MCC: 0.0981, F1: 0.6667

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.10123 | val 0.18418
  Epoch 020 - train 0.09063 | val 0.19253
  Epoch 023 - train 0.07933 | val 0.18096
  Regression -> MSE: 0.000296, MAE: 0.014532, R²: -0.5467
  Directional -> Accuracy: 0.3571, MCC: 0.0000, F1: 0.5263

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.10146 | val 0.14902
  Epoch 012 - train 0.10212 | val 0.16613
  Regression -> MSE: 0.000231, MAE: 0.011735, R²: -0.0662
  Directional -> Accuracy: 0.5345, MCC: 0.1708, F1: 0.3721

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.09554 | val 0.18475
  Epoch 011 - train 0.08984 | val 0.16931
  Regression -> MSE: 0.000091, MAE: 0.007597, R²: -0.0077
  Directional -> Accuracy: 0.5424, MCC: 0.1510, F1: 0.6667

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.10812 | val 0.34895
  Epoch 011 - train 0.10699 | val 0.33002
  Regression -> MSE: 0.000159, MAE: 0.009942, R²: -0.0034
  Directional -> Accuracy: 0.4821, MCC: -0.0029, F1: 0.3556

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.09975 | val 0.25547
  Epoch 012 - train 0.09340 | val 0.20062
  Regression -> MSE: 0.000118, MAE: 0.008843, R²: -0.0559
  Directional -> Accuracy: 0.4483, MCC: -0.1001, F1: 0.2727

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...

[I 2026-02-22 21:57:36,104] Trial 47 finished with value: -0.012121769778749751 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 6, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.1, 'dropout': 0.30000000000000004, 'batch_size': 16, 'learning_rate': 0.006068141308134474, 'weight_decay': 0.0002872450235978588, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.17603850624918238, 'early_stopping_min_delta': 0.00945633463082632}. Best is trial 31 with value: -0.011425014985750452.

  Epoch 010 - train 0.10967 | val 0.16292
  Epoch 011 - train 0.11021 | val 0.16122
  Regression -> MSE: 0.000227, MAE: 0.012032, R²: 0.0145
  Directional -> Accuracy: 0.5556, MCC: 0.1348, F1: 0.6111

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.38840 | val 1.44700
  Epoch 020 - train 0.36341 | val 1.39157
  Regression -> MSE: 0.000244, MAE: 0.012325, R²: -0.0130
  Directional -> Accuracy: 0.6316, MCC: 0.3032, F1: 0.6585

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.37388 | val 0.49985
  Epoch 016 - train 0.34286 | val 0.59904
  Regression -> MSE: 0.000710, MAE: 0.019825, R²: -0.0170
  Directional -> Accuracy: 0.6667, MCC: 0.2984, F1: 0.7458

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.42815 | val 1.01005
  Epoch 020 - train 0.37170 | val 1.04195
  Regression -> MSE: 0.000321, MAE: 0.014672, R²: -0.0200
  Directional -> Accuracy: 0.5000, MCC: -0.0421, F1: 0.6349

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.32937 | val 0.94545
  Epoch 016 - train 0.33055 | val 0.86285
  Regression -> MSE: 0.000401, MAE: 0.015448, R²: -0.1346
  Directional -> Accuracy: 0.4595, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.41431 | val 0.48121
  Epoch 020 - train 0.35680 | val 0.61673
  Regression -> MSE: 0.000209, MAE: 0.009982, R²: -0.0122
  Directional -> Accuracy: 0.5200, MCC: 0.0000, F1: 0.6842

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.36650 | val 1.10480
  Epoch 016 - train 0.32419 | val 1.49495
  Regression -> MSE: 0.000576, MAE: 0.018437, R²: -0.0181
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.42733 | val 0.79999
  Epoch 019 - train 0.38668 | val 1.16201
  Regression -> MSE: 0.000246, MAE: 0.011835, R²: 0.0090
  Directional -> Accuracy: 0.6324, MCC: 0.2145, F1: 0.1379

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.35711 | val 0.47830
  Epoch 016 - train 0.34420 | val 1.01543
  Regression -> MSE: 0.000623, MAE: 0.019700, R²: -0.0203
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.37862 | val 0.69918
  Epoch 020 - train 0.38679 | val 1.19418
  Regression -> MSE: 0.000369, MAE: 0.015661, R²: 0.0104
  Directional -> Accuracy: 0.4375, MCC: 0.0000, F1: 0.6087

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.39261 | val 0.93085
  Epoch 016 - train 0.35950 | val 0.94010
  Regression -> MSE: 0.000246, MAE: 0.011800, R²: -0.0057
  Directional -> Accuracy: 0.5652, MCC: -0.0376, F1: 0.0625

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.37833 | val 1.16265
  Epoch 016 - train 0.34809 | val 1.60215
  Regression -> MSE: 0.000319, MAE: 0.013480, R²: -0.0215
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.41890 | val 0.97102
  Epoch 016 - train 0.41067 | val 1.37149
  Regression -> MSE: 0.000683, MAE: 0.019548, R²: 0.0034
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.39215 | val 1.00284
  Epoch 016 - train 0.36817 | val 1.65998
  Regression -> MSE: 0.000139, MAE: 0.008978, R²: -0.0050
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.34009 | val 0.78912
  Epoch 016 - train 0.31069 | val 0.80899
  Regression -> MSE: 0.000226, MAE: 0.010692, R²: -0.0000
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.39502 | val 1.61823
  Epoch 020 - train 0.36228 | val 1.88621
  Regression -> MSE: 0.000361, MAE: 0.015945, R²: 0.0163
  Directional -> Accuracy: 0.4706, MCC: 0.0338, F1: 0.6087

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.39396 | val 0.61800
  Epoch 019 - train 0.37808 | val 0.64266
  Regression -> MSE: 0.000106, MAE: 0.007927, R²: 0.0206
  Directional -> Accuracy: 0.4928, MCC: -0.0051, F1: 0.4776

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.40285 | val 1.35157
  Epoch 016 - train 0.37428 | val 1.54307
  Regression -> MSE: 0.000163, MAE: 0.010210, R²: -0.0350
  Directional -> Accuracy: 0.3793, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.39510 | val 1.46795
  Epoch 016 - train 0.39153 | val 1.41438
  Regression -> MSE: 0.000277, MAE: 0.013243, R²: -0.0120
  Directional -> Accuracy: 0.6000, MCC: 0.0000, F1: 0.7500

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.33861 | val 0.75324
  Epoch 020 - train 0.31546 | val 0.80433
  Regression -> MSE: 0.000206, MAE: 0.010541, R²: -0.3590
  Directional -> Accuracy: 0.4219, MCC: -0.0284, F1: 0.0513

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.38837 | val 1.23463
  Epoch 019 - train 0.34838 | val 1.42842
  Regression -> MSE: 0.000338, MAE: 0.013815, R²: -0.4869
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.37523 | val 0.84765
  Epoch 016 - train 0.33051 | val 1.15363
  Regression -> MSE: 0.000151, MAE: 0.008674, R²: -0.0483
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.39630 | val 0.62785
  Epoch 016 - train 0.39363 | val 0.62958
  Regression -> MSE: 0.000175, MAE: 0.010289, R²: -0.0541
  Directional -> Accuracy: 0.4923, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.41578 | val 0.68199
  Epoch 020 - train 0.35638 | val 0.96881
  Regression -> MSE: 0.000095, MAE: 0.007518, R²: -0.0908
  Directional -> Accuracy: 0.5088, MCC: 0.0937, F1: 0.3913

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.40094 | val 0.77778
  Epoch 020 - train 0.33412 | val 0.81082
  Regression -> MSE: 0.000222, MAE: 0.011831, R²: -0.0513
  Directional -> Accuracy: 0.4923, MCC: -0.0077, F1: 0.5217

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.32462 | val 0.33699
  Epoch 020 - train 0.30915 | val 0.39326
  Regression -> MSE: 0.000105, MAE: 0.008180, R²: -0.1684
  Directional -> Accuracy: 0.4727, MCC: 0.0090, F1: 0.2564

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.40858 | val 0.37483
  Epoch 020 - train 0.37515 | val 0.41234
  Regression -> MSE: 0.000108, MAE: 0.008843, R²: -0.0850
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.43832 | val 0.50460
  Epoch 020 - train 0.39376 | val 0.95910
  Regression -> MSE: 0.000239, MAE: 0.012896, R²: -0.0093
  Directional -> Accuracy: 0.5238, MCC: -0.1936, F1: 0.6875

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.41731 | val 0.63677
  Epoch 018 - train 0.36373 | val 0.67806
  Regression -> MSE: 0.000180, MAE: 0.007926, R²: -0.0632
  Directional -> Accuracy: 0.5893, MCC: 0.1602, F1: 0.6462

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.37046 | val 0.30136
  Epoch 016 - train 0.42082 | val 0.32185
  Regression -> MSE: 0.000242, MAE: 0.012108, R²: 0.0004
  Directional -> Accuracy: 0.5500, MCC: 0.0000, F1: 0.7097

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.42605 | val 1.02365
  Epoch 020 - train 0.38569 | val 1.51798
  Regression -> MSE: 0.000239, MAE: 0.010218, R²: -0.0132
  Directional -> Accuracy: 0.4048, MCC: -0.1866, F1: 0.4898

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.37251 | val 0.65180
  Epoch 016 - train 0.35906 | val 0.87823
  Regression -> MSE: 0.000143, MAE: 0.008571, R²: -0.0408
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.38120 | val 0.68670
  Epoch 020 - train 0.33803 | val 0.70196
  Regression -> MSE: 0.000264, MAE: 0.012906, R²: -0.4401
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.34725 | val 0.71684
  Epoch 020 - train 0.32479 | val 0.85180
  Regression -> MSE: 0.000284, MAE: 0.010985, R²: -0.0706
  Directional -> Accuracy: 0.5278, MCC: 0.1291, F1: 0.4138

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.35799 | val 0.72401
  Epoch 016 - train 0.34258 | val 0.85289
  Regression -> MSE: 0.000184, MAE: 0.010437, R²: -0.0017
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.37440 | val 0.47935
  Epoch 020 - train 0.33019 | val 0.53294
  Regression -> MSE: 0.000350, MAE: 0.012674, R²: -0.0055
  Directional -> Accuracy: 0.4091, MCC: -0.1445, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.33001 | val 0.22601
  Epoch 020 - train 0.31340 | val 0.31519
  Regression -> MSE: 0.000118, MAE: 0.008173, R²: -0.1203
  Directional -> Accuracy: 0.6429, MCC: 0.3127, F1: 0.5946

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.38429 | val 0.94531
  Epoch 020 - train 0.33481 | val 1.25142
  Regression -> MSE: 0.000223, MAE: 0.011449, R²: -0.0158
  Directional -> Accuracy: 0.4643, MCC: -0.0620, F1: 0.4828

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.35111 | val 1.41674
  Epoch 020 - train 0.34420 | val 1.95085
  Regression -> MSE: 0.000077, MAE: 0.006833, R²: -0.0462
  Directional -> Accuracy: 0.5435, MCC: 0.0124, F1: 0.6441

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.39508 | val 0.22512
  Epoch 020 - train 0.32573 | val 0.28075
  Regression -> MSE: 0.000366, MAE: 0.016318, R²: -0.1752
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.36949 | val 1.02338
  Epoch 018 - train 0.32314 | val 1.13232
  Regression -> MSE: 0.000076, MAE: 0.006842, R²: 0.0205
  Directional -> Accuracy: 0.5000, MCC: 0.0466, F1: 0.6476

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.40968 | val 0.65453
  Epoch 020 - train 0.35029 | val 1.06785
  Regression -> MSE: 0.000302, MAE: 0.014377, R²: -0.0034
  Directional -> Accuracy: 0.5333, MCC: 0.0696, F1: 0.5116

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.35414 | val 0.60214
  Epoch 016 - train 0.32419 | val 0.60682
  Regression -> MSE: 0.000103, MAE: 0.007250, R²: -0.0092
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.37236 | val 0.79989
  Epoch 020 - train 0.35341 | val 0.79172
  Regression -> MSE: 0.000562, MAE: 0.020901, R²: -2.2031
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.38316 | val 0.69785
  Epoch 016 - train 0.35824 | val 1.16435
  Regression -> MSE: 0.000231, MAE: 0.011934, R²: -0.0241
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.38440 | val 1.34277
  Epoch 016 - train 0.37204 | val 1.51733
  Regression -> MSE: 0.000094, MAE: 0.007773, R²: -0.0041
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.42491 | val 0.98769
  Epoch 020 - train 0.37686 | val 1.03362
  Regression -> MSE: 0.000166, MAE: 0.010347, R²: 0.0068
  Directional -> Accuracy: 0.5094, MCC: 0.0000, F1: 0.6750

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.38689 | val 0.93153
  Epoch 016 - train 0.37085 | val 1.04423
  Regression -> MSE: 0.000123, MAE: 0.009113, R²: -0.0459
  Directional -> Accuracy: 0.4727, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.39577 | val 1.42036

[I 2026-02-22 22:00:36,013] Trial 48 finished with value: -0.011914356550901985 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.1, 'batch_size': 32, 'learning_rate': 0.0006288289349020091, 'weight_decay': 1.241304971515014e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 1.6993877151216763, 'early_stopping_min_delta': 0.005342847911983809}. Best is trial 31 with value: -0.011425014985750452.

  Epoch 016 - train 0.38970 | val 1.65388
  Regression -> MSE: 0.000244, MAE: 0.012461, R²: -0.0175
  Directional -> Accuracy: 0.5167, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: regression
Sequence length: 12
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.32747 | val 0.84722
  Epoch 016 - train 0.29268 | val 0.62787
  Regression -> MSE: 0.000252, MAE: 0.012605, R²: -0.0260
  Directional -> Accuracy: 0.5256, MCC: -0.0376, F1: 0.1778

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 88). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.31312 | val 0.37546
  Epoch 016 - train 0.26912 | val 0.37328
  Regression -> MSE: 0.000753, MAE: 0.020014, R²: -0.0896
  Directional -> Accuracy: 0.4681, MCC: -0.0445, F1: 0.4444

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 88). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.34490 | val 0.89900
  Epoch 016 - train 0.34210 | val 1.02096
  Regression -> MSE: 0.000338, MAE: 0.014897, R²: 0.0204
  Directional -> Accuracy: 0.5417, MCC: 0.0316, F1: 0.6765

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.29235 | val 0.36566
  Epoch 017 - train 0.26632 | val 0.32280
  Regression -> MSE: 0.000346, MAE: 0.014418, R²: -0.0036
  Directional -> Accuracy: 0.4868, MCC: -0.0801, F1: 0.6061

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.32021 | val 0.38535
  Epoch 020 - train 0.26340 | val 0.93510
  Regression -> MSE: 0.000183, MAE: 0.009420, R²: 0.0884
  Directional -> Accuracy: 0.5962, MCC: 0.1852, F1: 0.6316

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.26718 | val 0.99757
  Epoch 016 - train 0.23826 | val 1.07172
  Regression -> MSE: 0.000649, MAE: 0.019674, R²: -0.1337
  Directional -> Accuracy: 0.5510, MCC: 0.2502, F1: 0.2143

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.35707 | val 0.55208
  Epoch 019 - train 0.27921 | val 0.79341
  Regression -> MSE: 0.000249, MAE: 0.012290, R²: -0.0119
  Directional -> Accuracy: 0.5000, MCC: 0.0235, F1: 0.4776

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 88). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 88). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.26602 | val 1.13793
  Epoch 016 - train 0.21424 | val 1.43157
  Regression -> MSE: 0.000633, MAE: 0.019610, R²: -0.0823
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.28529 | val 0.68250
  Epoch 017 - train 0.27239 | val 0.67099
  Regression -> MSE: 0.000338, MAE: 0.014739, R²: 0.0009
  Directional -> Accuracy: 0.6190, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 88). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 88). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.33516 | val 0.85336
  Epoch 017 - train 0.26932 | val 0.93814
  Regression -> MSE: 0.000252, MAE: 0.012285, R²: -0.0603
  Directional -> Accuracy: 0.3803, MCC: -0.2050, F1: 0.4762

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.28392 | val 1.60036
  Epoch 016 - train 0.25442 | val 1.60792
  Regression -> MSE: 0.000298, MAE: 0.013454, R²: 0.0249
  Directional -> Accuracy: 0.5294, MCC: 0.0556, F1: 0.5000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.36238 | val 0.92735
  Epoch 016 - train 0.32718 | val 1.09609
  Regression -> MSE: 0.000650, MAE: 0.018983, R²: 0.0292
  Directional -> Accuracy: 0.6102, MCC: 0.2207, F1: 0.6102

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.28965 | val 0.50713
  Epoch 017 - train 0.23835 | val 0.60478
  Regression -> MSE: 0.000155, MAE: 0.009714, R²: -0.0362
  Directional -> Accuracy: 0.3864, MCC: -0.2108, F1: 0.4906

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 88). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.29530 | val 0.94230
  Epoch 016 - train 0.27645 | val 1.22180
  Regression -> MSE: 0.000221, MAE: 0.010751, R²: 0.0171
  Directional -> Accuracy: 0.5323, MCC: 0.0690, F1: 0.4314

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.28204 | val 2.05354
  Epoch 016 - train 0.25258 | val 1.89044
  Regression -> MSE: 0.000376, MAE: 0.016571, R²: -0.0009
  Directional -> Accuracy: 0.4717, MCC: 0.0000, F1: 0.6410

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.33551 | val 0.45202
  Epoch 016 - train 0.26678 | val 0.56202
  Regression -> MSE: 0.000104, MAE: 0.007817, R²: 0.0225
  Directional -> Accuracy: 0.5493, MCC: 0.0816, F1: 0.6190

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.33191 | val 1.13555
  Epoch 017 - train 0.27625 | val 1.23452
  Regression -> MSE: 0.000165, MAE: 0.010132, R²: -0.0326
  Directional -> Accuracy: 0.5500, MCC: 0.0242, F1: 0.6494

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.33587 | val 0.60392
  Epoch 017 - train 0.30873 | val 0.55209
  Regression -> MSE: 0.000276, MAE: 0.013330, R²: -0.0283
  Directional -> Accuracy: 0.4675, MCC: 0.1004, F1: 0.3279

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.28256 | val 0.57252
  Epoch 020 - train 0.25134 | val 0.59113
  Regression -> MSE: 0.000205, MAE: 0.010777, R²: -0.3899
  Directional -> Accuracy: 0.4848, MCC: 0.1240, F1: 0.3200

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 88). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.32789 | val 0.76812
  Epoch 016 - train 0.24751 | val 0.85939
  Regression -> MSE: 0.000236, MAE: 0.011198, R²: -0.0427
  Directional -> Accuracy: 0.4737, MCC: -0.0850, F1: 0.5652

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.33537 | val 0.50044
  Epoch 020 - train 0.25124 | val 0.45880
  Regression -> MSE: 0.000195, MAE: 0.010818, R²: -0.3119
  Directional -> Accuracy: 0.3673, MCC: -0.2696, F1: 0.4364

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 88). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 88). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 88). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.35152 | val 0.65596
  Epoch 020 - train 0.28541 | val 0.70249
  Regression -> MSE: 0.000240, MAE: 0.011807, R²: -0.3533
  Directional -> Accuracy: 0.4925, MCC: -0.0077, F1: 0.2917

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.33949 | val 0.56310
  Epoch 016 - train 0.32852 | val 0.86416
  Regression -> MSE: 0.000091, MAE: 0.007306, R²: -0.0917
  Directional -> Accuracy: 0.5085, MCC: 0.0412, F1: 0.5085

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.33061 | val 1.13653
  Epoch 017 - train 0.28100 | val 1.26072
  Regression -> MSE: 0.000247, MAE: 0.011826, R²: -0.1297
  Directional -> Accuracy: 0.5224, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.26543 | val 0.30862
  Epoch 016 - train 0.22910 | val 0.34625
  Regression -> MSE: 0.000110, MAE: 0.008474, R²: -0.2048
  Directional -> Accuracy: 0.5088, MCC: 0.1288, F1: 0.3333

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.33273 | val 0.28013
  Epoch 018 - train 0.23403 | val 0.85569
  Regression -> MSE: 0.000127, MAE: 0.009237, R²: -0.0065
  Directional -> Accuracy: 0.5833, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.32550 | val 0.53091
  Epoch 017 - train 0.25647 | val 0.74044
  Regression -> MSE: 0.000243, MAE: 0.012783, R²: -0.0209
  Directional -> Accuracy: 0.6364, MCC: 0.3407, F1: 0.6190

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.33559 | val 0.50158
  Epoch 016 - train 0.28421 | val 0.66144
  Regression -> MSE: 0.000303, MAE: 0.012411, R²: -0.8514
  Directional -> Accuracy: 0.5000, MCC: 0.1533, F1: 0.2162

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.31641 | val 0.50501
  Epoch 016 - train 0.28774 | val 0.39521
  Regression -> MSE: 0.000237, MAE: 0.012162, R²: -0.0131
  Directional -> Accuracy: 0.5581, MCC: 0.1297, F1: 0.5366

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.35529 | val 0.77426
  Epoch 017 - train 0.29517 | val 0.93238
  Regression -> MSE: 0.000246, MAE: 0.010585, R²: 0.0157
  Directional -> Accuracy: 0.5111, MCC: 0.0149, F1: 0.5926

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.27917 | val 0.93045
  Epoch 017 - train 0.23368 | val 0.91883
  Regression -> MSE: 0.000145, MAE: 0.008415, R²: -0.0907
  Directional -> Accuracy: 0.5333, MCC: 0.0000, F1: 0.6957

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.31977 | val 0.51990
  Epoch 018 - train 0.25697 | val 0.55355
  Regression -> MSE: 0.000197, MAE: 0.010535, R²: -0.0476
  Directional -> Accuracy: 0.4706, MCC: -0.0556, F1: 0.4706

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.30327 | val 0.54717
  Epoch 020 - train 0.25237 | val 0.76540
  Regression -> MSE: 0.000295, MAE: 0.011948, R²: -0.1411
  Directional -> Accuracy: 0.5811, MCC: 0.1795, F1: 0.5867

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 88). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.24010 | val 0.33515
  Epoch 017 - train 0.18953 | val 0.35144
  Regression -> MSE: 0.000165, MAE: 0.010432, R²: -0.0137
  Directional -> Accuracy: 0.5385, MCC: 0.2266, F1: 0.6786

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.24511 | val 0.56180
  Epoch 017 - train 0.20823 | val 0.70642
  Regression -> MSE: 0.000197, MAE: 0.010745, R²: -0.0786
  Directional -> Accuracy: 0.5111, MCC: 0.0238, F1: 0.5000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.32149 | val 0.41039
  Epoch 016 - train 0.24166 | val 0.47260
  Regression -> MSE: 0.000441, MAE: 0.015668, R²: -0.2635
  Directional -> Accuracy: 0.4265, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.28660 | val 0.57725
  Epoch 018 - train 0.22960 | val 0.44411
  Regression -> MSE: 0.000118, MAE: 0.007905, R²: -0.1332
  Directional -> Accuracy: 0.6364, MCC: 0.3254, F1: 0.5000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.34992 | val 0.61105
  Epoch 018 - train 0.30939 | val 0.60763
  Regression -> MSE: 0.000231, MAE: 0.011625, R²: -0.0740
  Directional -> Accuracy: 0.5000, MCC: 0.0283, F1: 0.5672

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.27794 | val 1.20847
  Epoch 017 - train 0.21129 | val 1.27867
  Regression -> MSE: 0.000087, MAE: 0.007263, R²: -0.0973
  Directional -> Accuracy: 0.6042, MCC: 0.0176, F1: 0.7397

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 88). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 88). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 88). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 88). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.29643 | val 0.40856
  Epoch 017 - train 0.22076 | val 0.49226
  Regression -> MSE: 0.000337, MAE: 0.014930, R²: -0.0279
  Directional -> Accuracy: 0.3500, MCC: -0.0721, F1: 0.5000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 88). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.29268 | val 0.28486
  Epoch 016 - train 0.18496 | val 0.38783
  Regression -> MSE: 0.000268, MAE: 0.011725, R²: -0.1247
  Directional -> Accuracy: 0.3846, MCC: -0.2182, F1: 0.2941

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 88). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 88). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.31750 | val 0.82525
  Epoch 018 - train 0.28223 | val 0.73874
  Regression -> MSE: 0.000080, MAE: 0.007009, R²: 0.0078
  Directional -> Accuracy: 0.5132, MCC: 0.0349, F1: 0.6337

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 88). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 88). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 88). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.28993 | val 0.52543
  Epoch 017 - train 0.22632 | val 1.58251
  Regression -> MSE: 0.000341, MAE: 0.014879, R²: 0.0524
  Directional -> Accuracy: 0.5625, MCC: 0.1601, F1: 0.6667

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.27535 | val 0.48125
  Epoch 019 - train 0.21935 | val 0.54392
  Regression -> MSE: 0.000103, MAE: 0.007396, R²: -0.0645
  Directional -> Accuracy: 0.4889, MCC: -0.0925, F1: 0.6102

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.22389 | val 0.86174
  Epoch 016 - train 0.14598 | val 0.89049
  Regression -> MSE: 0.000188, MAE: 0.010759, R²: -0.0408
  Directional -> Accuracy: 0.3659, MCC: 0.0000, F1: 0.5357

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.31772 | val 0.51645
  Epoch 020 - train 0.28331 | val 0.46754
  Regression -> MSE: 0.000255, MAE: 0.012497, R²: -0.1621
  Directional -> Accuracy: 0.4912, MCC: 0.1746, F1: 0.1212

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.31229 | val 1.76049
  Epoch 016 - train 0.28743 | val 1.66668
  Regression -> MSE: 0.000111, MAE: 0.008746, R²: -0.2203
  Directional -> Accuracy: 0.4828, MCC: 0.0000, F1: 0.6512

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.38305 | val 0.76165
  Epoch 017 - train 0.35656 | val 0.97634
  Regression -> MSE: 0.000166, MAE: 0.010347, R²: -0.0348
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.30728 | val 0.73488
  Epoch 016 - train 0.27574 | val 0.64110
  Regression -> MSE: 0.000126, MAE: 0.008963, R²: -0.1059
  Directional -> Accuracy: 0.4386, MCC: -0.2399, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.33314 | val 0.66841

[I 2026-02-22 22:03:02,696] Trial 49 finished with value: -0.011880635567608273 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 12, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.0, 'batch_size': 32, 'learning_rate': 0.0045484611935440065, 'weight_decay': 3.5648419474097886e-07, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 0.9743944481434279, 'early_stopping_min_delta': 0.008114073249983358}. Best is trial 31 with value: -0.011425014985750452.

  Epoch 017 - train 0.29734 | val 0.67947
  Regression -> MSE: 0.000236, MAE: 0.012158, R²: -0.0099
  Directional -> Accuracy: 0.5645, MCC: 0.1356, F1: 0.3721

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.51408 | val 0.98187
  Epoch 020 - train 0.51616 | val 0.98460
  Epoch 021 - train 0.51858 | val 0.98458
  Regression -> MSE: 0.000253, MAE: 0.012738, R²: -0.0220
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.46821 | val 0.52366
  Epoch 020 - train 0.46946 | val 0.57255
  Epoch 021 - train 0.46462 | val 0.57240
  Regression -> MSE: 0.000691, MAE: 0.019496, R²: -0.0099
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.45291 | val 0.98679
  Epoch 020 - train 0.47153 | val 1.00062
  Epoch 021 - train 0.47063 | val 1.00050
  Regression -> MSE: 0.000312, MAE: 0.014519, R²: -0.0068
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.38118 | val 0.47685
  Epoch 020 - train 0.37650 | val 0.48131
  Epoch 021 - train 0.37370 | val 0.48143
  Regression -> MSE: 0.000348, MAE: 0.014586, R²: 0.0039
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.47983 | val 0.88573
  Epoch 020 - train 0.47776 | val 0.94984
  Epoch 021 - train 0.47594 | val 0.94971
  Regression -> MSE: 0.000205, MAE: 0.010204, R²: -0.0062
  Directional -> Accuracy: 0.4118, MCC: -0.1941, F1: 0.4828

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.44866 | val 1.18889
  Epoch 020 - train 0.43833 | val 1.28293
  Epoch 021 - train 0.44313 | val 1.28357
  Regression -> MSE: 0.000559, MAE: 0.018134, R²: -0.0077
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.48668 | val 0.73743
  Epoch 020 - train 0.48158 | val 0.73536
  Epoch 021 - train 0.47278 | val 0.73528
  Regression -> MSE: 0.000249, MAE: 0.012304, R²: -0.0133
  Directional -> Accuracy: 0.3478, MCC: -0.3002, F1: 0.5161

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.47731 | val 0.62819
  Epoch 020 - train 0.47570 | val 0.61519
  Epoch 030 - train 0.46939 | val 0.61371
  Regression -> MSE: 0.000596, MAE: 0.019309, R²: 0.0029
  Directional -> Accuracy: 0.5000, MCC: 0.0722, F1: 0.5417

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.46026 | val 0.59156
  Epoch 020 - train 0.45006 | val 0.60193
  Epoch 027 - train 0.45838 | val 0.60184
  Regression -> MSE: 0.000405, MAE: 0.016085, R²: -0.0552
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.51504 | val 0.76261
  Epoch 020 - train 0.51391 | val 0.75789
  Epoch 021 - train 0.50594 | val 0.75771
  Regression -> MSE: 0.000244, MAE: 0.011708, R²: -0.0116
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.43710 | val 0.81201
  Epoch 020 - train 0.43199 | val 0.83274
  Epoch 021 - train 0.44065 | val 0.83290
  Regression -> MSE: 0.000328, MAE: 0.013643, R²: -0.0546
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.47778 | val 0.85606
  Epoch 020 - train 0.46629 | val 0.87751
  Epoch 021 - train 0.46162 | val 0.87757
  Regression -> MSE: 0.000672, MAE: 0.019413, R²: 0.0076
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.46241 | val 0.48269
  Epoch 020 - train 0.44950 | val 0.49920
  Epoch 026 - train 0.46262 | val 0.49846
  Regression -> MSE: 0.000144, MAE: 0.009369, R²: -0.0396
  Directional -> Accuracy: 0.3953, MCC: -0.1823, F1: 0.5357

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.40590 | val 0.94197
  Epoch 020 - train 0.39968 | val 0.95229
  Epoch 021 - train 0.40733 | val 0.95218
  Regression -> MSE: 0.000231, MAE: 0.010897, R²: -0.0286
  Directional -> Accuracy: 0.4918, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.45324 | val 1.45156
  Epoch 020 - train 0.45489 | val 1.48239
  Epoch 021 - train 0.44807 | val 1.48236
  Regression -> MSE: 0.000365, MAE: 0.015995, R²: -0.0082
  Directional -> Accuracy: 0.4808, MCC: -0.0696, F1: 0.3415

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.50588 | val 0.50678
  Epoch 020 - train 0.49762 | val 0.50450
  Epoch 021 - train 0.51015 | val 0.50434
  Regression -> MSE: 0.000109, MAE: 0.007991, R²: -0.0132
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.46056 | val 1.38696
  Epoch 020 - train 0.47256 | val 1.44743
  Epoch 023 - train 0.48566 | val 1.44736
  Regression -> MSE: 0.000160, MAE: 0.010028, R²: -0.0272
  Directional -> Accuracy: 0.5763, MCC: 0.2826, F1: 0.5455

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.46648 | val 0.67634
  Epoch 020 - train 0.46375 | val 0.69669
  Epoch 023 - train 0.46350 | val 0.69883
  Regression -> MSE: 0.000270, MAE: 0.012892, R²: 0.0071
  Directional -> Accuracy: 0.6053, MCC: 0.1375, F1: 0.7000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.52427 | val 1.00677
  Epoch 020 - train 0.52814 | val 1.00017
  Epoch 021 - train 0.52538 | val 0.99991
  Regression -> MSE: 0.000151, MAE: 0.009090, R²: -0.0095
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.50695 | val 1.07600
  Epoch 020 - train 0.50083 | val 1.06289
  Epoch 021 - train 0.49829 | val 1.06250
  Regression -> MSE: 0.000232, MAE: 0.010874, R²: -0.0235
  Directional -> Accuracy: 0.6000, MCC: 0.1777, F1: 0.6875

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.49648 | val 0.70010
  Epoch 020 - train 0.49054 | val 0.69331
  Epoch 030 - train 0.47714 | val 0.69075
  Regression -> MSE: 0.000150, MAE: 0.008782, R²: -0.0437
  Directional -> Accuracy: 0.5000, MCC: -0.0216, F1: 0.5714

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.48081 | val 0.67991
  Epoch 020 - train 0.48042 | val 0.67964
  Epoch 021 - train 0.47585 | val 0.67958
  Regression -> MSE: 0.000166, MAE: 0.010776, R²: -0.0062
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.49537 | val 0.67977
  Epoch 020 - train 0.49651 | val 0.68004
  Epoch 021 - train 0.49591 | val 0.67998
  Regression -> MSE: 0.000089, MAE: 0.007226, R²: -0.0394
  Directional -> Accuracy: 0.4138, MCC: -0.1050, F1: 0.1500

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.50590 | val 0.77332
  Epoch 020 - train 0.49636 | val 0.77814
  Epoch 021 - train 0.49443 | val 0.77827
  Regression -> MSE: 0.000215, MAE: 0.011025, R²: -0.0128
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.46189 | val 0.38666
  Epoch 020 - train 0.45337 | val 0.38766
  Epoch 023 - train 0.44757 | val 0.38737
  Regression -> MSE: 0.000093, MAE: 0.008099, R²: -0.0147
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.48629 | val 0.31993
  Epoch 020 - train 0.47944 | val 0.35336
  Epoch 029 - train 0.47808 | val 0.35606
  Regression -> MSE: 0.000114, MAE: 0.008837, R²: -0.1041
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.48141 | val 0.69360
  Epoch 020 - train 0.47765 | val 0.81593
  Epoch 021 - train 0.47000 | val 0.81626
  Regression -> MSE: 0.000241, MAE: 0.012865, R²: -0.0431
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.44064 | val 0.56959
  Epoch 020 - train 0.43550 | val 0.57138
  Epoch 026 - train 0.44303 | val 0.57152
  Regression -> MSE: 0.000203, MAE: 0.008718, R²: -0.2215
  Directional -> Accuracy: 0.4737, MCC: -0.0509, F1: 0.5000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.47774 | val 0.30052
  Epoch 020 - train 0.47007 | val 0.30025
  Epoch 021 - train 0.48812 | val 0.30015
  Regression -> MSE: 0.000239, MAE: 0.011949, R²: -0.0100
  Directional -> Accuracy: 0.4878, MCC: 0.1469, F1: 0.0870

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.44455 | val 1.02839
  Epoch 020 - train 0.45938 | val 1.03247
  Epoch 021 - train 0.47009 | val 1.03245
  Regression -> MSE: 0.000232, MAE: 0.009996, R²: -0.0079
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.52348 | val 0.71567
  Epoch 020 - train 0.51222 | val 0.72533
  Epoch 021 - train 0.52628 | val 0.72542
  Regression -> MSE: 0.000139, MAE: 0.008452, R²: -0.0328
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.47394 | val 0.66320
  Epoch 020 - train 0.47346 | val 0.66864
  Epoch 025 - train 0.48088 | val 0.66861
  Regression -> MSE: 0.000186, MAE: 0.010457, R²: 0.0114
  Directional -> Accuracy: 0.5200, MCC: -0.0146, F1: 0.6471

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.42896 | val 0.62553
  Epoch 020 - train 0.41784 | val 0.62417
  Epoch 024 - train 0.42174 | val 0.62392
  Regression -> MSE: 0.000293, MAE: 0.011418, R²: -0.1194
  Directional -> Accuracy: 0.4521, MCC: -0.1207, F1: 0.5238

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.50311 | val 0.36583
  Epoch 020 - train 0.47678 | val 0.37028
  Epoch 021 - train 0.48905 | val 0.37108
  Regression -> MSE: 0.000167, MAE: 0.010395, R²: -0.0028
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.41011 | val 0.50375
  Epoch 020 - train 0.40219 | val 0.49530
  Epoch 030 - train 0.39515 | val 0.49347
  Regression -> MSE: 0.000190, MAE: 0.010853, R²: -0.0531
  Directional -> Accuracy: 0.4091, MCC: -0.1843, F1: 0.3810

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.47173 | val 0.46024
  Epoch 020 - train 0.47512 | val 0.45917
  Epoch 021 - train 0.46909 | val 0.45913
  Regression -> MSE: 0.000345, MAE: 0.011906, R²: -0.0056
  Directional -> Accuracy: 0.4627, MCC: -0.0306, F1: 0.4000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.50830 | val 0.26614
  Epoch 020 - train 0.47752 | val 0.28411
  Epoch 021 - train 0.51161 | val 0.28423
  Regression -> MSE: 0.000123, MAE: 0.008428, R²: -0.1695
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.46523 | val 1.03009
  Epoch 020 - train 0.46682 | val 1.05243
  Epoch 021 - train 0.46788 | val 1.05218
  Regression -> MSE: 0.000220, MAE: 0.011366, R²: -0.0048
  Directional -> Accuracy: 0.4035, MCC: -0.2073, F1: 0.3200

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.47325 | val 1.15371
  Epoch 020 - train 0.47662 | val 1.17472
  Epoch 021 - train 0.48231 | val 1.17466
  Regression -> MSE: 0.000082, MAE: 0.007085, R²: -0.0614
  Directional -> Accuracy: 0.5957, MCC: -0.1162, F1: 0.7467

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.45855 | val 0.25491
  Epoch 020 - train 0.45671 | val 0.25682
  Epoch 030 - train 0.44442 | val 0.25790
  Regression -> MSE: 0.000319, MAE: 0.013848, R²: -0.0372
  Directional -> Accuracy: 0.6327, MCC: 0.2926, F1: 0.5909

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.48113 | val 0.20810
  Epoch 020 - train 0.47482 | val 0.21347
  Epoch 021 - train 0.46125 | val 0.21342
  Regression -> MSE: 0.000256, MAE: 0.011510, R²: -0.0501
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.45185 | val 0.65661
  Epoch 020 - train 0.44646 | val 0.65226
  Epoch 021 - train 0.44277 | val 0.65214
  Regression -> MSE: 0.000083, MAE: 0.007061, R²: -0.0311
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.50330 | val 0.67908
  Epoch 020 - train 0.50766 | val 0.72704
  Epoch 021 - train 0.50306 | val 0.72727
  Regression -> MSE: 0.000306, MAE: 0.014509, R²: 0.0036
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.44116 | val 0.60557
  Epoch 020 - train 0.42894 | val 0.61334
  Epoch 029 - train 0.42515 | val 0.61386
  Regression -> MSE: 0.000100, MAE: 0.007157, R²: -0.0213
  Directional -> Accuracy: 0.5682, MCC: 0.0300, F1: 0.7164

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.49871 | val 0.76621
  Epoch 020 - train 0.49478 | val 0.82928
  Epoch 021 - train 0.48583 | val 0.83049
  Regression -> MSE: 0.000173, MAE: 0.010015, R²: -0.0089
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.43681 | val 1.26542
  Epoch 020 - train 0.43044 | val 1.33249
  Epoch 021 - train 0.43407 | val 1.33253
  Regression -> MSE: 0.000227, MAE: 0.011751, R²: -0.0191
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.49748 | val 0.67207
  Epoch 020 - train 0.49227 | val 0.67180
  Epoch 021 - train 0.48224 | val 0.67169
  Regression -> MSE: 0.000091, MAE: 0.007585, R²: 0.0104
  Directional -> Accuracy: 0.5263, MCC: 0.0690, F1: 0.5714

[86/88] Processing WFC...


[I 2026-02-22 22:03:35,867] Trial 50 finished with value: -0.01146470841965933 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.4, 'dropout': 0.2, 'batch_size': 32, 'learning_rate': 8.424502113900088e-06, 'weight_decay': 2.376089148678279e-06, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 1.5629517037246912, 'early_stopping_min_delta': 0.002521953617343932}. Best is trial 31 with value: -0.011425014985750452.

  Epoch 020 - train 0.49954 | val 0.86141
  Epoch 025 - train 0.47874 | val 0.86074
  Regression -> MSE: 0.000253, MAE: 0.012668, R²: -0.0687
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.47733 | val 0.88173
  Epoch 020 - train 0.46770 | val 0.88255
  Epoch 021 - train 0.47096 | val 0.88246
  Regression -> MSE: 0.000248, MAE: 0.012522, R²: -0.0019
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.50592 | val 0.44921
  Epoch 020 - train 0.49366 | val 0.47862
  Epoch 026 - train 0.47634 | val 0.47976
  Regression -> MSE: 0.000723, MAE: 0.019843, R²: -0.0568
  Directional -> Accuracy: 0.4348, MCC: -0.0693, F1: 0.2778

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.50126 | val 1.14167
  Epoch 020 - train 0.50720 | val 1.29077
  Epoch 021 - train 0.50403 | val 1.29088
  Regression -> MSE: 0.000314, MAE: 0.014541, R²: -0.0107
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.37629 | val 0.40320
  Epoch 020 - train 0.36358 | val 0.40685
  Epoch 023 - train 0.36077 | val 0.40739
  Regression -> MSE: 0.000351, MAE: 0.014562, R²: -0.0049
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.44382 | val 0.65430
  Epoch 020 - train 0.44132 | val 0.71566
  Epoch 021 - train 0.43349 | val 0.71561
  Regression -> MSE: 0.000202, MAE: 0.010041, R²: 0.0063
  Directional -> Accuracy: 0.5686, MCC: 0.2079, F1: 0.4211

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.45039 | val 1.18083
  Epoch 020 - train 0.44443 | val 1.26443
  Epoch 023 - train 0.43586 | val 1.26572
  Regression -> MSE: 0.000557, MAE: 0.018173, R²: -0.0030
  Directional -> Accuracy: 0.5957, MCC: 0.2361, F1: 0.3871

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.48400 | val 0.75163
  Epoch 020 - train 0.47801 | val 0.74880
  Epoch 021 - train 0.46584 | val 0.74866
  Regression -> MSE: 0.000247, MAE: 0.012022, R²: -0.0045
  Directional -> Accuracy: 0.5072, MCC: 0.0231, F1: 0.4688

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.47861 | val 0.72943
  Epoch 020 - train 0.46579 | val 0.78120
  Epoch 021 - train 0.47866 | val 0.78166
  Regression -> MSE: 0.000626, MAE: 0.019766, R²: -0.0482
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.46296 | val 0.61390
  Epoch 020 - train 0.45863 | val 0.61101
  Epoch 030 - train 0.45498 | val 0.60995
  Regression -> MSE: 0.000465, MAE: 0.017141, R²: -0.2124
  Directional -> Accuracy: 0.4694, MCC: -0.2120, F1: 0.0714

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.46470 | val 0.69960
  Epoch 020 - train 0.46148 | val 0.70504
  Epoch 025 - train 0.45420 | val 0.70562
  Regression -> MSE: 0.000242, MAE: 0.011873, R²: -0.0011
  Directional -> Accuracy: 0.4571, MCC: -0.0274, F1: 0.5250

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.46559 | val 0.71235
  Epoch 020 - train 0.44825 | val 0.71306
  Epoch 027 - train 0.45617 | val 0.71279
  Regression -> MSE: 0.000386, MAE: 0.014668, R²: -0.2425
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.46920 | val 0.72008
  Epoch 020 - train 0.47050 | val 0.73157
  Epoch 021 - train 0.47024 | val 0.73159
  Regression -> MSE: 0.000674, MAE: 0.019390, R²: 0.0046
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.44314 | val 0.51626
  Epoch 020 - train 0.45930 | val 0.51911
  Epoch 021 - train 0.45332 | val 0.51905
  Regression -> MSE: 0.000143, MAE: 0.009449, R²: -0.0376
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.41575 | val 0.70805
  Epoch 020 - train 0.40401 | val 0.70775
  Epoch 021 - train 0.41337 | val 0.70771
  Regression -> MSE: 0.000228, MAE: 0.010798, R²: -0.0150
  Directional -> Accuracy: 0.4754, MCC: -0.0795, F1: 0.0588

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.46200 | val 1.36554
  Epoch 020 - train 0.46902 | val 1.37240
  Epoch 021 - train 0.47672 | val 1.37264
  Regression -> MSE: 0.000364, MAE: 0.016018, R²: -0.0059
  Directional -> Accuracy: 0.3846, MCC: -0.2463, F1: 0.3043

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.49140 | val 0.52774
  Epoch 020 - train 0.48916 | val 0.52362
  Epoch 022 - train 0.48595 | val 0.52322
  Regression -> MSE: 0.000106, MAE: 0.007940, R²: 0.0147
  Directional -> Accuracy: 0.5571, MCC: 0.0876, F1: 0.6437

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.49235 | val 1.76382
  Epoch 020 - train 0.48279 | val 1.82630
  Epoch 021 - train 0.48459 | val 1.82609
  Regression -> MSE: 0.000173, MAE: 0.010640, R²: -0.1110
  Directional -> Accuracy: 0.3729, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.45837 | val 0.59496
  Epoch 020 - train 0.45582 | val 0.59882
  Epoch 021 - train 0.46195 | val 0.59889
  Regression -> MSE: 0.000286, MAE: 0.013693, R²: -0.0524
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.42392 | val 0.83450
  Epoch 020 - train 0.41889 | val 0.83264
  Epoch 021 - train 0.41619 | val 0.83256
  Regression -> MSE: 0.000154, MAE: 0.008759, R²: -0.0273
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.45852 | val 0.92989
  Epoch 020 - train 0.45946 | val 0.92549
  Epoch 021 - train 0.46106 | val 0.92537
  Regression -> MSE: 0.000236, MAE: 0.011035, R²: -0.0421
  Directional -> Accuracy: 0.4267, MCC: -0.1539, F1: 0.4691

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.46610 | val 0.73495
  Epoch 020 - train 0.44554 | val 0.74763
  Epoch 021 - train 0.44459 | val 0.74766
  Regression -> MSE: 0.000150, MAE: 0.008718, R²: -0.0481
  Directional -> Accuracy: 0.4583, MCC: -0.1556, F1: 0.5667

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.45494 | val 0.55320
  Epoch 020 - train 0.45896 | val 0.55346
  Epoch 021 - train 0.46503 | val 0.55347
  Regression -> MSE: 0.000176, MAE: 0.010240, R²: -0.0625
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.48979 | val 0.65247
  Epoch 020 - train 0.48487 | val 0.65355
  Epoch 021 - train 0.47624 | val 0.65353
  Regression -> MSE: 0.000087, MAE: 0.007134, R²: -0.0194
  Directional -> Accuracy: 0.5172, MCC: 0.0445, F1: 0.5333

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.51541 | val 1.18687
  Epoch 020 - train 0.50357 | val 1.17446
  Epoch 021 - train 0.49321 | val 1.17389
  Regression -> MSE: 0.000214, MAE: 0.011310, R²: -0.0085
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.41770 | val 0.33009
  Epoch 020 - train 0.41215 | val 0.32633
  Epoch 030 - train 0.42248 | val 0.32404
  Regression -> MSE: 0.000092, MAE: 0.007899, R²: -0.0017
  Directional -> Accuracy: 0.5179, MCC: -0.0435, F1: 0.6494

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.49109 | val 0.52044
  Epoch 020 - train 0.47869 | val 0.86910
  Epoch 021 - train 0.50949 | val 0.87856
  Regression -> MSE: 0.000117, MAE: 0.009247, R²: -0.1314
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.48298 | val 0.48190
  Epoch 020 - train 0.48324 | val 0.51575
  Epoch 021 - train 0.48676 | val 0.51614
  Regression -> MSE: 0.000232, MAE: 0.012498, R²: -0.0036
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.43331 | val 0.53646
  Epoch 020 - train 0.44698 | val 0.53243
  Epoch 030 - train 0.43692 | val 0.53113
  Regression -> MSE: 0.000247, MAE: 0.010259, R²: -0.4828
  Directional -> Accuracy: 0.5088, MCC: 0.2428, F1: 0.2222

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.49956 | val 0.33907
  Epoch 020 - train 0.50654 | val 0.44173
  Epoch 021 - train 0.47962 | val 0.44495
  Regression -> MSE: 0.000236, MAE: 0.011877, R²: 0.0005
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.46338 | val 1.00520
  Epoch 020 - train 0.47617 | val 1.04130
  Epoch 021 - train 0.48926 | val 1.04170
  Regression -> MSE: 0.000229, MAE: 0.009881, R²: 0.0060
  Directional -> Accuracy: 0.4884, MCC: -0.0094, F1: 0.6207

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.46584 | val 0.66605
  Epoch 020 - train 0.46773 | val 0.70314
  Epoch 021 - train 0.46428 | val 0.70337
  Regression -> MSE: 0.000135, MAE: 0.008199, R²: -0.0002
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.48558 | val 0.68488
  Epoch 020 - train 0.48899 | val 0.68925
  Epoch 021 - train 0.48545 | val 0.68926
  Regression -> MSE: 0.000193, MAE: 0.010495, R²: -0.0242
  Directional -> Accuracy: 0.4400, MCC: -0.1042, F1: 0.3913

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.48142 | val 0.83502
  Epoch 020 - train 0.46562 | val 0.83106
  Epoch 021 - train 0.46552 | val 0.83092
  Regression -> MSE: 0.000267, MAE: 0.010951, R²: -0.0194
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.47599 | val 0.52617
  Epoch 020 - train 0.50143 | val 0.88016
  Epoch 021 - train 0.49266 | val 0.89530
  Regression -> MSE: 0.000174, MAE: 0.010425, R²: -0.0450
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.41701 | val 0.69130
  Epoch 020 - train 0.42289 | val 0.73500
  Epoch 021 - train 0.40846 | val 0.73502
  Regression -> MSE: 0.000183, MAE: 0.010435, R²: -0.0177
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.58482 | val 0.52397
  Epoch 020 - train 0.58144 | val 0.51974
  Epoch 021 - train 0.58944 | val 0.51959
  Regression -> MSE: 0.000365, MAE: 0.012126, R²: -0.0653
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.64106 | val 0.64743
  Epoch 020 - train 0.63566 | val 1.20594
  Epoch 021 - train 0.61018 | val 1.20940
  Regression -> MSE: 0.000125, MAE: 0.008518, R²: -0.1899
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.46488 | val 0.78939
  Epoch 020 - train 0.46556 | val 0.80511
  Epoch 027 - train 0.44963 | val 0.80599
  Regression -> MSE: 0.000217, MAE: 0.011115, R²: 0.0080
  Directional -> Accuracy: 0.5614, MCC: 0.1326, F1: 0.2424

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.45042 | val 1.13728
  Epoch 020 - train 0.45809 | val 1.15153
  Epoch 021 - train 0.44595 | val 1.15160
  Regression -> MSE: 0.000089, MAE: 0.007370, R²: -0.1437
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.46764 | val 0.33921
  Epoch 020 - train 0.46224 | val 0.29453
  Epoch 030 - train 0.46539 | val 0.28975
  Regression -> MSE: 0.000436, MAE: 0.017669, R²: -0.4158
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.47105 | val 0.20898
  Epoch 020 - train 0.50399 | val 0.25344
  Epoch 021 - train 0.48914 | val 0.25650
  Regression -> MSE: 0.000247, MAE: 0.011492, R²: -0.0150
  Directional -> Accuracy: 0.4737, MCC: -0.1537, F1: 0.6296

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.44179 | val 0.62117
  Epoch 020 - train 0.44148 | val 0.62008
  Epoch 021 - train 0.43700 | val 0.62004
  Regression -> MSE: 0.000083, MAE: 0.007074, R²: -0.0214
  Directional -> Accuracy: 0.5600, MCC: 0.1324, F1: 0.4000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.52849 | val 0.64549
  Epoch 020 - train 0.51198 | val 0.66323
  Epoch 021 - train 0.50685 | val 0.66321
  Regression -> MSE: 0.000309, MAE: 0.014519, R²: -0.0076
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.47468 | val 0.52052
  Epoch 020 - train 0.48273 | val 0.51709
  Epoch 030 - train 0.44340 | val 0.51699
  Regression -> MSE: 0.000100, MAE: 0.007409, R²: -0.0137
  Directional -> Accuracy: 0.4773, MCC: 0.0187, F1: 0.3784

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.49473 | val 0.76519
  Epoch 020 - train 0.50920 | val 0.79914
  Epoch 021 - train 0.47967 | val 0.79935
  Regression -> MSE: 0.000176, MAE: 0.010209, R²: -0.0223
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.43225 | val 0.65680
  Epoch 020 - train 0.42640 | val 0.66611
  Epoch 021 - train 0.43025 | val 0.66600
  Regression -> MSE: 0.000223, MAE: 0.011720, R²: -0.0004
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.47769 | val 1.00478
  Epoch 020 - train 0.47999 | val 1.02796
  Epoch 021 - train 0.46775 | val 1.02804
  Regression -> MSE: 0.000095, MAE: 0.007855, R²: -0.0293

[I 2026-02-22 22:04:08,564] Trial 51 finished with value: -0.011625332564673938 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.4, 'dropout': 0.2, 'batch_size': 32, 'learning_rate': 8.202466953560436e-06, 'weight_decay': 2.3998330667250214e-06, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 1.5684747284542648, 'early_stopping_min_delta': 0.0023121909843443395}. Best is trial 31 with value: -0.011425014985750452.

  Epoch 020 - train 0.48214 | val 1.37810
  Epoch 021 - train 0.49048 | val 1.37819
  Regression -> MSE: 0.000241, MAE: 0.012236, R²: -0.0154
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.47438 | val 0.81235
  Epoch 020 - train 0.47175 | val 0.81036
  Epoch 024 - train 0.47224 | val 0.80997
  Regression -> MSE: 0.000266, MAE: 0.013035, R²: -0.0733
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.47000 | val 0.41714
  Epoch 020 - train 0.47965 | val 0.41009
  Epoch 030 - train 0.47208 | val 0.41016
  Regression -> MSE: 0.000772, MAE: 0.020737, R²: -0.1275
  Directional -> Accuracy: 0.4783, MCC: -0.0496, F1: 0.5200

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.49428 | val 0.92042
  Epoch 020 - train 0.48590 | val 0.92310
  Epoch 028 - train 0.49970 | val 0.92292
  Regression -> MSE: 0.000314, MAE: 0.014254, R²: -0.0119
  Directional -> Accuracy: 0.5745, MCC: 0.1455, F1: 0.6000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.47720 | val 2.06254
  Epoch 020 - train 0.47016 | val 2.04893
  Epoch 021 - train 0.47527 | val 2.04833
  Regression -> MSE: 0.000382, MAE: 0.015083, R²: -0.0934
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.50101 | val 0.43601
  Epoch 020 - train 0.49541 | val 0.45516
  Epoch 027 - train 0.50488 | val 0.45515
  Regression -> MSE: 0.000207, MAE: 0.009744, R²: -0.0143
  Directional -> Accuracy: 0.6863, MCC: 0.3808, F1: 0.6800

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.47569 | val 1.54317
  Epoch 020 - train 0.47723 | val 1.93660
  Epoch 021 - train 0.47586 | val 1.93852
  Regression -> MSE: 0.000606, MAE: 0.019037, R²: -0.0921
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.45035 | val 0.78652
  Epoch 020 - train 0.45243 | val 0.78732
  Epoch 022 - train 0.46346 | val 0.78723
  Regression -> MSE: 0.000242, MAE: 0.012116, R²: 0.0152
  Directional -> Accuracy: 0.4928, MCC: 0.1234, F1: 0.5783

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.47622 | val 0.62176
  Epoch 020 - train 0.46289 | val 0.63604
  Epoch 030 - train 0.48173 | val 0.64114
  Regression -> MSE: 0.000617, MAE: 0.019723, R²: -0.0332
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.4500

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.44472 | val 0.67207
  Epoch 020 - train 0.43880 | val 0.68608
  Epoch 021 - train 0.44209 | val 0.68604
  Regression -> MSE: 0.000383, MAE: 0.015957, R²: 0.0010
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.47825 | val 0.94048
  Epoch 020 - train 0.47441 | val 0.93972
  Epoch 021 - train 0.47545 | val 0.93953
  Regression -> MSE: 0.000242, MAE: 0.011839, R²: -0.0021
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.46853 | val 0.78882
  Epoch 020 - train 0.46339 | val 0.81306
  Epoch 025 - train 0.46600 | val 0.81361
  Regression -> MSE: 0.000332, MAE: 0.013901, R²: -0.0677
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.49517 | val 0.87854
  Epoch 020 - train 0.50078 | val 0.91012
  Epoch 021 - train 0.49386 | val 0.91009
  Regression -> MSE: 0.000680, MAE: 0.019564, R²: -0.0038
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.44418 | val 0.60376
  Epoch 020 - train 0.44904 | val 0.63535
  Epoch 021 - train 0.44937 | val 0.63549
  Regression -> MSE: 0.000137, MAE: 0.008996, R²: 0.0063
  Directional -> Accuracy: 0.5814, MCC: 0.1240, F1: 0.1818

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.40716 | val 0.71402
  Epoch 020 - train 0.41024 | val 0.71511
  Epoch 021 - train 0.41370 | val 0.71510
  Regression -> MSE: 0.000228, MAE: 0.010781, R²: -0.0125
  Directional -> Accuracy: 0.4918, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.46801 | val 1.27839
  Epoch 020 - train 0.45857 | val 1.27931
  Epoch 029 - train 0.45457 | val 1.27936
  Regression -> MSE: 0.000354, MAE: 0.015704, R²: 0.0220
  Directional -> Accuracy: 0.5962, MCC: 0.2117, F1: 0.6182

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.48268 | val 0.52507
  Epoch 020 - train 0.48397 | val 0.52466
  Epoch 021 - train 0.48716 | val 0.52463
  Regression -> MSE: 0.000112, MAE: 0.008013, R²: -0.0403
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.46504 | val 1.05405
  Epoch 020 - train 0.45642 | val 1.05348
  Epoch 021 - train 0.46231 | val 1.05352
  Regression -> MSE: 0.000157, MAE: 0.009957, R²: -0.0074
  Directional -> Accuracy: 0.6102, MCC: 0.1437, F1: 0.7013

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.47359 | val 0.85913
  Epoch 020 - train 0.46989 | val 0.86442
  Epoch 021 - train 0.46968 | val 0.86445
  Regression -> MSE: 0.000286, MAE: 0.013728, R²: -0.0512
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.41377 | val 0.80615
  Epoch 020 - train 0.41526 | val 0.80544
  Epoch 021 - train 0.41453 | val 0.80537
  Regression -> MSE: 0.000150, MAE: 0.008744, R²: -0.0012
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.47200 | val 0.93297
  Epoch 020 - train 0.46907 | val 0.93130
  Epoch 021 - train 0.46859 | val 0.93123
  Regression -> MSE: 0.000255, MAE: 0.011388, R²: -0.1253
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.45413 | val 0.83715
  Epoch 020 - train 0.45298 | val 0.90021
  Epoch 023 - train 0.46047 | val 0.90034
  Regression -> MSE: 0.000159, MAE: 0.009069, R²: -0.1116
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.42186 | val 0.55476
  Epoch 020 - train 0.41412 | val 0.55429
  Epoch 025 - train 0.41646 | val 0.55418
  Regression -> MSE: 0.000169, MAE: 0.010527, R²: -0.0232
  Directional -> Accuracy: 0.4394, MCC: -0.1482, F1: 0.5647

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.48872 | val 0.66965
  Epoch 020 - train 0.47523 | val 0.67326
  Epoch 021 - train 0.47330 | val 0.67326
  Regression -> MSE: 0.000086, MAE: 0.007111, R²: -0.0080
  Directional -> Accuracy: 0.5517, MCC: 0.0687, F1: 0.6286

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.49457 | val 0.64230
  Epoch 020 - train 0.49237 | val 0.63706
  Epoch 030 - train 0.48784 | val 0.63360
  Regression -> MSE: 0.000314, MAE: 0.014509, R²: -0.4817
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.40380 | val 0.43129
  Epoch 020 - train 0.40679 | val 0.43345
  Epoch 021 - train 0.40491 | val 0.43342
  Regression -> MSE: 0.000093, MAE: 0.008084, R²: -0.0059
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.49880 | val 0.32833
  Epoch 020 - train 0.49531 | val 0.33745
  Epoch 026 - train 0.49134 | val 0.33814
  Regression -> MSE: 0.000105, MAE: 0.008799, R²: -0.0164
  Directional -> Accuracy: 0.4348, MCC: -0.0280, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.49824 | val 0.50309
  Epoch 020 - train 0.49335 | val 0.52315
  Epoch 021 - train 0.49268 | val 0.52312
  Regression -> MSE: 0.000232, MAE: 0.012577, R²: -0.0030
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.47883 | val 0.58858
  Epoch 020 - train 0.47815 | val 0.58900
  Epoch 024 - train 0.47438 | val 0.58883
  Regression -> MSE: 0.000206, MAE: 0.008768, R²: -0.2402
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.49570 | val 0.47265
  Epoch 020 - train 0.48431 | val 0.66713
  Epoch 021 - train 0.49096 | val 0.66957
  Regression -> MSE: 0.000240, MAE: 0.011978, R²: -0.0154
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.48520 | val 1.11461
  Epoch 020 - train 0.47158 | val 1.24212
  Epoch 021 - train 0.48852 | val 1.24285
  Regression -> MSE: 0.000235, MAE: 0.010081, R²: -0.0216
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.47471 | val 0.73438
  Epoch 020 - train 0.46626 | val 0.74680
  Epoch 021 - train 0.46284 | val 0.74688
  Regression -> MSE: 0.000146, MAE: 0.008739, R²: -0.0826
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.47806 | val 0.67445
  Epoch 020 - train 0.46406 | val 0.67588
  Epoch 021 - train 0.46620 | val 0.67588
  Regression -> MSE: 0.000202, MAE: 0.010847, R²: -0.0749
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.41072 | val 0.60406
  Epoch 020 - train 0.41004 | val 0.60368
  Epoch 023 - train 0.41094 | val 0.60362
  Regression -> MSE: 0.000272, MAE: 0.010788, R²: -0.0384
  Directional -> Accuracy: 0.5205, MCC: 0.0894, F1: 0.4615

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.50140 | val 0.36678
  Epoch 020 - train 0.50511 | val 0.39361
  Epoch 021 - train 0.51439 | val 0.39765
  Regression -> MSE: 0.000170, MAE: 0.010369, R²: -0.0221
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.42883 | val 0.61405
  Epoch 020 - train 0.43794 | val 0.64656
  Epoch 021 - train 0.45251 | val 0.64657
  Regression -> MSE: 0.000197, MAE: 0.010910, R²: -0.0970
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.46645 | val 0.40929
  Epoch 020 - train 0.45981 | val 0.40655
  Epoch 030 - train 0.45441 | val 0.40453
  Regression -> MSE: 0.000386, MAE: 0.012991, R²: -0.1272
  Directional -> Accuracy: 0.5373, MCC: -0.1532, F1: 0.6990

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.46681 | val 0.23365
  Epoch 020 - train 0.47055 | val 0.25930
  Epoch 025 - train 0.47067 | val 0.25994
  Regression -> MSE: 0.000116, MAE: 0.008312, R²: -0.1076
  Directional -> Accuracy: 0.4884, MCC: -0.0318, F1: 0.5600

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.48213 | val 0.89497
  Epoch 020 - train 0.49194 | val 0.89650
  Epoch 021 - train 0.49278 | val 0.89642
  Regression -> MSE: 0.000219, MAE: 0.011343, R²: -0.0037
  Directional -> Accuracy: 0.4211, MCC: -0.2822, F1: 0.0571

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.47824 | val 1.09662
  Epoch 020 - train 0.46754 | val 1.09950
  Epoch 021 - train 0.46665 | val 1.09948
  Regression -> MSE: 0.000087, MAE: 0.007287, R²: -0.1244
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.48234 | val 0.38154
  Epoch 020 - train 0.47550 | val 0.41014
  Epoch 021 - train 0.48486 | val 0.41018
  Regression -> MSE: 0.000338, MAE: 0.015241, R²: -0.0991
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.51556 | val 0.20652
  Epoch 020 - train 0.49898 | val 0.21327
  Epoch 021 - train 0.51604 | val 0.21395
  Regression -> MSE: 0.000254, MAE: 0.011549, R²: -0.0417
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.45505 | val 0.67139
  Epoch 020 - train 0.44585 | val 0.67303
  Epoch 021 - train 0.44817 | val 0.67306
  Regression -> MSE: 0.000086, MAE: 0.007080, R²: -0.0675
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.48688 | val 0.59340
  Epoch 020 - train 0.48460 | val 0.65276
  Epoch 026 - train 0.47890 | val 0.65430
  Regression -> MSE: 0.000341, MAE: 0.015268, R²: -0.1107
  Directional -> Accuracy: 0.4894, MCC: 0.0000, F1: 0.0000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.42880 | val 0.55082
  Epoch 020 - train 0.42978 | val 0.55443
  Epoch 021 - train 0.42103 | val 0.55447
  Regression -> MSE: 0.000098, MAE: 0.007133, R²: -0.0003
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.49918 | val 0.69517
  Epoch 020 - train 0.49330 | val 0.68625
  Epoch 030 - train 0.49117 | val 0.68650
  Regression -> MSE: 0.000218, MAE: 0.011987, R²: -0.2680
  Directional -> Accuracy: 0.3673, MCC: -0.1539, F1: 0.4918

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.44324 | val 0.62574
  Epoch 020 - train 0.44148 | val 0.63120
  Epoch 021 - train 0.43621 | val 0.63119
  Regression -> MSE: 0.000227, MAE: 0.011873, R²: -0.0190
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.45391 | val 0.59302
  Epoch 020 - train 0.46673 | val 0.59441
  Epoch 021 - train 0.46375 | val 0.59441
  Regression -> MSE: 0.000094, MAE: 0.007755, R²: -0.0170

[I 2026-02-22 22:04:42,089] Trial 52 finished with value: -0.011696392304646086 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.4, 'dropout': 0.1, 'batch_size': 32, 'learning_rate': 3.823788345115023e-06, 'weight_decay': 4.766687198290858e-06, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 1.5144790916738486, 'early_stopping_min_delta': 0.002598350384671237}. Best is trial 31 with value: -0.011425014985750452.

  Epoch 020 - train 0.46474 | val 0.87889
  Epoch 021 - train 0.46264 | val 0.87890
  Regression -> MSE: 0.000242, MAE: 0.012303, R²: -0.0206
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.22771 | val 0.31514
  Epoch 020 - train 0.22738 | val 0.31532
  Epoch 024 - train 0.22734 | val 0.31533
  Regression -> MSE: 0.000255, MAE: 0.012856, R²: -0.0282
  Directional -> Accuracy: 0.4675, MCC: 0.0289, F1: 0.6168

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.23792 | val 0.21817
  Epoch 020 - train 0.23740 | val 0.22506
  Epoch 025 - train 0.23733 | val 0.22513
  Regression -> MSE: 0.000733, MAE: 0.019899, R²: -0.0714
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.24416 | val 0.46497
  Epoch 020 - train 0.24395 | val 0.48229
  Epoch 021 - train 0.24395 | val 0.48230
  Regression -> MSE: 0.000316, MAE: 0.014538, R²: -0.0200
  Directional -> Accuracy: 0.4255, MCC: -0.1737, F1: 0.5091

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.18582 | val 0.28147
  Epoch 020 - train 0.18556 | val 0.28274
  Epoch 021 - train 0.18556 | val 0.28277
  Regression -> MSE: 0.000391, MAE: 0.015299, R²: -0.1203
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.22588 | val 0.24248
  Epoch 020 - train 0.22576 | val 0.24453
  Epoch 021 - train 0.22576 | val 0.24453
  Regression -> MSE: 0.000201, MAE: 0.010068, R²: 0.0120
  Directional -> Accuracy: 0.5098, MCC: 0.1905, F1: 0.1379

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.23507 | val 0.51231
  Epoch 020 - train 0.23486 | val 0.49948
  Epoch 021 - train 0.23486 | val 0.49889
  Regression -> MSE: 0.000572, MAE: 0.018416, R²: -0.0306
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.23705 | val 0.30729
  Epoch 020 - train 0.23682 | val 0.30774
  Epoch 021 - train 0.23681 | val 0.30774
  Regression -> MSE: 0.000252, MAE: 0.012032, R²: -0.0255
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.23170 | val 0.28731
  Epoch 020 - train 0.23111 | val 0.28647
  Epoch 030 - train 0.23089 | val 0.28730
  Regression -> MSE: 0.000594, MAE: 0.019135, R²: 0.0063
  Directional -> Accuracy: 0.6136, MCC: 0.1390, F1: 0.2609

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.22517 | val 0.27683
  Epoch 020 - train 0.22446 | val 0.27414
  Epoch 030 - train 0.22378 | val 0.27402
  Regression -> MSE: 0.000441, MAE: 0.016807, R²: -0.1485
  Directional -> Accuracy: 0.4082, MCC: -0.2014, F1: 0.3256

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.23181 | val 0.34456
  Epoch 020 - train 0.23151 | val 0.34437
  Epoch 021 - train 0.23150 | val 0.34435
  Regression -> MSE: 0.000242, MAE: 0.011757, R²: -0.0037
  Directional -> Accuracy: 0.4143, MCC: -0.0962, F1: 0.5591

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.21308 | val 0.33745
  Epoch 020 - train 0.21275 | val 0.33877
  Epoch 023 - train 0.21272 | val 0.33881
  Regression -> MSE: 0.000332, MAE: 0.013645, R²: -0.0663
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.23644 | val 0.27920
  Epoch 020 - train 0.23621 | val 0.27996
  Epoch 021 - train 0.23621 | val 0.27997
  Regression -> MSE: 0.000677, MAE: 0.019464, R²: -0.0002
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.25215 | val 0.23167
  Epoch 020 - train 0.25125 | val 0.23393
  Epoch 029 - train 0.25103 | val 0.23393
  Regression -> MSE: 0.000140, MAE: 0.009195, R²: -0.0097
  Directional -> Accuracy: 0.4651, MCC: 0.0118, F1: 0.5818

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.21016 | val 0.28726
  Epoch 020 - train 0.20966 | val 0.28629
  Epoch 030 - train 0.20918 | val 0.28614
  Regression -> MSE: 0.000239, MAE: 0.011316, R²: -0.0621
  Directional -> Accuracy: 0.5082, MCC: 0.0455, F1: 0.2105

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.22306 | val 0.53041
  Epoch 020 - train 0.22293 | val 0.54650
  Epoch 021 - train 0.22292 | val 0.54650
  Regression -> MSE: 0.000370, MAE: 0.015977, R²: -0.0216
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.26491 | val 0.27755
  Epoch 020 - train 0.26456 | val 0.27768
  Epoch 021 - train 0.26455 | val 0.27766
  Regression -> MSE: 0.000118, MAE: 0.008168, R²: -0.0913
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.22557 | val 0.43037
  Epoch 020 - train 0.22538 | val 0.43141
  Epoch 021 - train 0.22537 | val 0.43140
  Regression -> MSE: 0.000159, MAE: 0.009591, R²: -0.0226
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.23499 | val 0.42771
  Epoch 020 - train 0.23470 | val 0.43023
  Epoch 021 - train 0.23469 | val 0.43025
  Regression -> MSE: 0.000289, MAE: 0.013379, R²: -0.0618
  Directional -> Accuracy: 0.5000, MCC: 0.1529, F1: 0.3871

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.21079 | val 0.31380
  Epoch 020 - train 0.21054 | val 0.31362
  Epoch 021 - train 0.21053 | val 0.31362
  Regression -> MSE: 0.000165, MAE: 0.009016, R²: -0.1041
  Directional -> Accuracy: 0.4308, MCC: -0.0852, F1: 0.3729

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.26495 | val 0.44812
  Epoch 020 - train 0.26449 | val 0.44756
  Epoch 021 - train 0.26448 | val 0.44754
  Regression -> MSE: 0.000227, MAE: 0.010987, R²: -0.0023
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.22973 | val 0.28923
  Epoch 020 - train 0.22933 | val 0.29087
  Epoch 027 - train 0.22926 | val 0.29087
  Regression -> MSE: 0.000151, MAE: 0.008879, R²: -0.0559
  Directional -> Accuracy: 0.4583, MCC: -0.0436, F1: 0.4800

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.21138 | val 0.30470
  Epoch 020 - train 0.21130 | val 0.30527
  Epoch 021 - train 0.21129 | val 0.30527
  Regression -> MSE: 0.000174, MAE: 0.010167, R²: -0.0502
  Directional -> Accuracy: 0.5455, MCC: 0.1004, F1: 0.4231

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.25427 | val 0.31935
  Epoch 020 - train 0.25408 | val 0.32148
  Epoch 021 - train 0.25408 | val 0.32148
  Regression -> MSE: 0.000090, MAE: 0.007284, R²: -0.0577
  Directional -> Accuracy: 0.4310, MCC: -0.0263, F1: 0.0571

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.24848 | val 0.35625
  Epoch 020 - train 0.24803 | val 0.35658
  Epoch 021 - train 0.24802 | val 0.35658
  Regression -> MSE: 0.000214, MAE: 0.011099, R²: -0.0096
  Directional -> Accuracy: 0.5152, MCC: 0.0196, F1: 0.4483

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.23714 | val 0.24398
  Epoch 020 - train 0.23683 | val 0.24619
  Epoch 021 - train 0.23682 | val 0.24619
  Regression -> MSE: 0.000092, MAE: 0.008083, R²: 0.0055
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.23008 | val 0.17931
  Epoch 020 - train 0.22982 | val 0.19701
  Epoch 027 - train 0.22976 | val 0.19925
  Regression -> MSE: 0.000105, MAE: 0.008686, R²: -0.0226
  Directional -> Accuracy: 0.5217, MCC: 0.0496, F1: 0.5000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.24572 | val 0.23471
  Epoch 020 - train 0.24559 | val 0.23857
  Epoch 021 - train 0.24559 | val 0.23857
  Regression -> MSE: 0.000232, MAE: 0.012520, R²: -0.0022
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.24021 | val 0.32098
  Epoch 020 - train 0.23997 | val 0.32179
  Epoch 021 - train 0.23996 | val 0.32179
  Regression -> MSE: 0.000170, MAE: 0.007886, R²: -0.0199
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.23891 | val 0.19958
  Epoch 020 - train 0.23880 | val 0.22401
  Epoch 021 - train 0.23880 | val 0.22463
  Regression -> MSE: 0.000237, MAE: 0.011871, R²: -0.0028
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.25173 | val 0.38981
  Epoch 020 - train 0.25150 | val 0.40445
  Epoch 021 - train 0.25150 | val 0.40448
  Regression -> MSE: 0.000229, MAE: 0.009854, R²: 0.0052
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.26150 | val 0.38805
  Epoch 020 - train 0.26128 | val 0.42612
  Epoch 021 - train 0.26127 | val 0.42628
  Regression -> MSE: 0.000147, MAE: 0.008777, R²: -0.0926
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.23539 | val 0.28915
  Epoch 020 - train 0.23447 | val 0.28848
  Epoch 030 - train 0.23414 | val 0.28861
  Regression -> MSE: 0.000198, MAE: 0.010651, R²: -0.0512
  Directional -> Accuracy: 0.6000, MCC: 0.1948, F1: 0.6296

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.20212 | val 0.26403
  Epoch 020 - train 0.20190 | val 0.26434
  Epoch 023 - train 0.20188 | val 0.26437
  Regression -> MSE: 0.000294, MAE: 0.011388, R²: -0.1240
  Directional -> Accuracy: 0.4384, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.22970 | val 0.20169
  Epoch 020 - train 0.22951 | val 0.22263
  Epoch 021 - train 0.22951 | val 0.22445
  Regression -> MSE: 0.000171, MAE: 0.010411, R²: -0.0250
  Directional -> Accuracy: 0.4211, MCC: -0.2335, F1: 0.0833

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.20973 | val 0.24706
  Epoch 020 - train 0.20959 | val 0.25076
  Epoch 021 - train 0.20959 | val 0.25076
  Regression -> MSE: 0.000180, MAE: 0.010283, R²: 0.0009
  Directional -> Accuracy: 0.5000, MCC: 0.1457, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.22212 | val 0.24373
  Epoch 020 - train 0.22166 | val 0.24390
  Epoch 021 - train 0.22164 | val 0.24390
  Regression -> MSE: 0.000353, MAE: 0.012606, R²: -0.0295
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.24885 | val 0.14987
  Epoch 020 - train 0.24872 | val 0.15560
  Epoch 021 - train 0.24872 | val 0.15560
  Regression -> MSE: 0.000113, MAE: 0.008365, R²: -0.0779
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.23236 | val 0.33040
  Epoch 020 - train 0.23214 | val 0.33131
  Epoch 021 - train 0.23214 | val 0.33131
  Regression -> MSE: 0.000219, MAE: 0.011350, R²: -0.0029
  Directional -> Accuracy: 0.4561, MCC: -0.0974, F1: 0.3922

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.23334 | val 0.45921
  Epoch 020 - train 0.23313 | val 0.46929
  Epoch 021 - train 0.23312 | val 0.46929
  Regression -> MSE: 0.000091, MAE: 0.007470, R²: -0.1772
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.23810 | val 0.19463
  Epoch 020 - train 0.23740 | val 0.18178
  Epoch 030 - train 0.23670 | val 0.18065
  Regression -> MSE: 0.000368, MAE: 0.016060, R²: -0.1954
  Directional -> Accuracy: 0.3878, MCC: -0.0228, F1: 0.5161

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.26039 | val 0.14232
  Epoch 020 - train 0.26023 | val 0.14980
  Epoch 021 - train 0.26023 | val 0.14999
  Regression -> MSE: 0.000247, MAE: 0.011503, R²: -0.0135
  Directional -> Accuracy: 0.5263, MCC: 0.0181, F1: 0.6667

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.24191 | val 0.30378
  Epoch 020 - train 0.24154 | val 0.30388
  Epoch 021 - train 0.24153 | val 0.30388
  Regression -> MSE: 0.000083, MAE: 0.007076, R²: -0.0311
  Directional -> Accuracy: 0.4667, MCC: -0.2014, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.22688 | val 0.29184
  Epoch 020 - train 0.22654 | val 0.30795
  Epoch 027 - train 0.22648 | val 0.30819
  Regression -> MSE: 0.000329, MAE: 0.014815, R²: -0.0738
  Directional -> Accuracy: 0.4894, MCC: -0.0168, F1: 0.4286

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.23796 | val 0.31268
  Epoch 020 - train 0.23777 | val 0.33855
  Epoch 021 - train 0.23776 | val 0.33908
  Regression -> MSE: 0.000104, MAE: 0.007100, R²: -0.0618
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.24749 | val 0.29287
  Epoch 020 - train 0.24734 | val 0.30997
  Epoch 021 - train 0.24733 | val 0.31032
  Regression -> MSE: 0.000175, MAE: 0.010124, R²: -0.0164
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.21772 | val 0.44580
  Epoch 020 - train 0.21756 | val 0.45790
  Epoch 021 - train 0.21756 | val 0.45790
  Regression -> MSE: 0.000226, MAE: 0.011711, R²: -0.0117
  Directional -> Accuracy: 0.5000, MCC: 0.0601, F1: 0.3000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.23379 | val 0.30078
  Epoch 020 - train 0.23355 | val 0.30180
  Epoch 021 - train 0.23354 | val 0.30180
  Regression -> MSE: 0.000093, MAE: 0.007698, R²: -0.0046

[I 2026-02-22 22:05:14,981] Trial 53 finished with value: -0.01154206532251373 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.4, 'dropout': 0.0, 'batch_size': 32, 'learning_rate': 1.97098483374174e-06, 'weight_decay': 8.542963173905832e-07, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.3973907328617242, 'early_stopping_min_delta': 0.0010345123871439458}. Best is trial 31 with value: -0.011425014985750452.

  Epoch 020 - train 0.23130 | val 0.35640
  Epoch 021 - train 0.23130 | val 0.35641
  Regression -> MSE: 0.000238, MAE: 0.012440, R²: -0.0052
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 12
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.44944 | val 0.72604
  Epoch 020 - train 0.44012 | val 0.73125
  Epoch 028 - train 0.43837 | val 0.73310
  Regression -> MSE: 0.000241, MAE: 0.012407, R²: 0.0186
  Directional -> Accuracy: 0.5641, MCC: 0.1465, F1: 0.5750

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 88). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.49828 | val 0.43805
  Epoch 020 - train 0.48864 | val 0.43228
  Epoch 030 - train 0.47519 | val 0.43128
  Regression -> MSE: 0.000651, MAE: 0.018999, R²: 0.0590
  Directional -> Accuracy: 0.6170, MCC: 0.2097, F1: 0.7000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 88). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.47290 | val 1.03112
  Epoch 020 - train 0.47595 | val 1.03665
  Epoch 021 - train 0.47805 | val 1.03652
  Regression -> MSE: 0.000346, MAE: 0.015120, R²: -0.0029
  Directional -> Accuracy: 0.5417, MCC: 0.0000, F1: 0.7027

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.42645 | val 0.48486
  Epoch 020 - train 0.41400 | val 0.51346
  Epoch 021 - train 0.41664 | val 0.51538
  Regression -> MSE: 0.000369, MAE: 0.014835, R²: -0.0700
  Directional -> Accuracy: 0.4737, MCC: 0.0049, F1: 0.2308

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.45597 | val 0.45444
  Epoch 020 - train 0.44251 | val 0.45898
  Epoch 025 - train 0.44617 | val 0.45845
  Regression -> MSE: 0.000192, MAE: 0.009963, R²: 0.0431
  Directional -> Accuracy: 0.5962, MCC: 0.1814, F1: 0.6441

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.43230 | val 1.20557
  Epoch 020 - train 0.42546 | val 1.29437
  Epoch 021 - train 0.43077 | val 1.29475
  Regression -> MSE: 0.000617, MAE: 0.019129, R²: -0.0781
  Directional -> Accuracy: 0.4898, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.49157 | val 0.70496
  Epoch 020 - train 0.48999 | val 0.70558
  Epoch 021 - train 0.49236 | val 0.70569
  Regression -> MSE: 0.000245, MAE: 0.012020, R²: 0.0031
  Directional -> Accuracy: 0.5429, MCC: 0.0934, F1: 0.5000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 88). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 88). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.48906 | val 0.70632
  Epoch 020 - train 0.48596 | val 0.66579
  Epoch 030 - train 0.47913 | val 0.67536
  Regression -> MSE: 0.000663, MAE: 0.019814, R²: -0.1334
  Directional -> Accuracy: 0.4444, MCC: 0.1289, F1: 0.6032

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.47752 | val 0.80294
  Epoch 020 - train 0.46782 | val 0.79291
  Epoch 030 - train 0.46180 | val 0.79438
  Regression -> MSE: 0.000372, MAE: 0.016382, R²: -0.1012
  Directional -> Accuracy: 0.3810, MCC: 0.0000, F1: 0.5517

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 88). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 88). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.52812 | val 0.72906
  Epoch 020 - train 0.52325 | val 0.73004
  Epoch 021 - train 0.51987 | val 0.73010
  Regression -> MSE: 0.000241, MAE: 0.011639, R²: -0.0129
  Directional -> Accuracy: 0.4930, MCC: 0.0208, F1: 0.5263

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.47824 | val 0.90662
  Epoch 020 - train 0.45647 | val 0.93464
  Epoch 021 - train 0.46425 | val 0.93616
  Regression -> MSE: 0.000308, MAE: 0.013564, R²: -0.0059
  Directional -> Accuracy: 0.4510, MCC: -0.1209, F1: 0.3333

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.50268 | val 0.66663
  Epoch 020 - train 0.49138 | val 0.66068
  Epoch 021 - train 0.49182 | val 0.66014
  Regression -> MSE: 0.000676, MAE: 0.019814, R²: -0.0097
  Directional -> Accuracy: 0.5085, MCC: 0.0000, F1: 0.6742

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.48841 | val 0.58934
  Epoch 020 - train 0.48746 | val 0.68825
  Epoch 021 - train 0.48278 | val 0.68688
  Regression -> MSE: 0.000152, MAE: 0.009706, R²: -0.0119
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 88). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.43246 | val 0.72813
  Epoch 020 - train 0.42229 | val 0.73230
  Epoch 023 - train 0.42433 | val 0.73255
  Regression -> MSE: 0.000230, MAE: 0.010889, R²: -0.0248
  Directional -> Accuracy: 0.5323, MCC: 0.1826, F1: 0.1212

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.48122 | val 1.43364
  Epoch 020 - train 0.47593 | val 1.44895
  Epoch 021 - train 0.47218 | val 1.44980
  Regression -> MSE: 0.000375, MAE: 0.016418, R²: 0.0033
  Directional -> Accuracy: 0.4717, MCC: 0.0000, F1: 0.6410

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.49653 | val 0.59793
  Epoch 020 - train 0.48510 | val 0.58590
  Epoch 021 - train 0.47963 | val 0.58498
  Regression -> MSE: 0.000108, MAE: 0.007923, R²: -0.0147
  Directional -> Accuracy: 0.4789, MCC: -0.2277, F1: 0.6476

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.43872 | val 1.16486
  Epoch 020 - train 0.44421 | val 1.17261
  Epoch 021 - train 0.44273 | val 1.17260
  Regression -> MSE: 0.000163, MAE: 0.010272, R²: -0.0210
  Directional -> Accuracy: 0.5167, MCC: 0.0183, F1: 0.5797

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.44511 | val 0.49640
  Epoch 020 - train 0.44720 | val 0.49046
  Epoch 021 - train 0.44834 | val 0.49004
  Regression -> MSE: 0.000288, MAE: 0.013723, R²: -0.0714
  Directional -> Accuracy: 0.3896, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.45432 | val 0.79692
  Epoch 020 - train 0.44219 | val 0.79048
  Epoch 021 - train 0.44057 | val 0.78991
  Regression -> MSE: 0.000168, MAE: 0.009227, R²: -0.1431
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 88). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.46683 | val 1.06004
  Epoch 020 - train 0.47245 | val 1.05846
  Epoch 022 - train 0.46194 | val 1.05795
  Regression -> MSE: 0.000234, MAE: 0.010988, R²: -0.0340
  Directional -> Accuracy: 0.5658, MCC: 0.1925, F1: 0.4590

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.48864 | val 0.67604
  Epoch 020 - train 0.49602 | val 0.69366
  Epoch 025 - train 0.47612 | val 0.69238
  Regression -> MSE: 0.000151, MAE: 0.008615, R²: -0.0199
  Directional -> Accuracy: 0.6327, MCC: 0.0000, F1: 0.7750

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 88). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 88). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 88). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.51519 | val 0.54376
  Epoch 020 - train 0.50323 | val 0.54196
  Epoch 024 - train 0.50057 | val 0.54152
  Regression -> MSE: 0.000251, MAE: 0.011960, R²: -0.4174
  Directional -> Accuracy: 0.4925, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.53351 | val 0.68871
  Epoch 020 - train 0.52721 | val 0.68647
  Epoch 021 - train 0.53762 | val 0.68627
  Regression -> MSE: 0.000086, MAE: 0.007115, R²: -0.0263
  Directional -> Accuracy: 0.4407, MCC: -0.1647, F1: 0.5352

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.52495 | val 1.52691
  Epoch 020 - train 0.52206 | val 1.52596
  Epoch 021 - train 0.52886 | val 1.52549
  Regression -> MSE: 0.000237, MAE: 0.011539, R²: -0.0856
  Directional -> Accuracy: 0.5224, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.43182 | val 0.36029
  Epoch 020 - train 0.42570 | val 0.35520
  Epoch 021 - train 0.42125 | val 0.35477
  Regression -> MSE: 0.000100, MAE: 0.008280, R²: -0.0942
  Directional -> Accuracy: 0.4561, MCC: 0.0076, F1: 0.2051

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.48301 | val 0.20547
  Epoch 020 - train 0.48211 | val 0.24069
  Epoch 021 - train 0.46973 | val 0.24189
  Regression -> MSE: 0.000139, MAE: 0.009691, R²: -0.1082
  Directional -> Accuracy: 0.4167, MCC: 0.0000, F1: 0.5882

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.50222 | val 0.40216
  Epoch 020 - train 0.49656 | val 0.40730
  Epoch 021 - train 0.49268 | val 0.40742
  Regression -> MSE: 0.000239, MAE: 0.012799, R²: -0.0049
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.7429

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.48542 | val 0.60533
  Epoch 020 - train 0.47689 | val 0.60011
  Epoch 030 - train 0.46564 | val 0.59590
  Regression -> MSE: 0.000203, MAE: 0.008184, R²: -0.2384
  Directional -> Accuracy: 0.5172, MCC: 0.1595, F1: 0.3000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.47321 | val 0.24811
  Epoch 020 - train 0.48182 | val 0.29105
  Epoch 021 - train 0.47518 | val 0.29167
  Regression -> MSE: 0.000236, MAE: 0.012020, R²: -0.0083
  Directional -> Accuracy: 0.3721, MCC: -0.3093, F1: 0.4906

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.46792 | val 1.07560
  Epoch 020 - train 0.46780 | val 1.15173
  Epoch 021 - train 0.47291 | val 1.15189
  Regression -> MSE: 0.000251, MAE: 0.010565, R²: -0.0028
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.46395 | val 0.81558
  Epoch 020 - train 0.46515 | val 0.86408
  Epoch 021 - train 0.46173 | val 0.86458
  Regression -> MSE: 0.000135, MAE: 0.008158, R²: -0.0117
  Directional -> Accuracy: 0.5333, MCC: 0.0000, F1: 0.6957

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.52855 | val 0.64751
  Epoch 020 - train 0.50943 | val 0.64892
  Epoch 027 - train 0.50772 | val 0.64956
  Regression -> MSE: 0.000248, MAE: 0.012659, R²: -0.3188
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.51453 | val 1.05777
  Epoch 020 - train 0.49757 | val 1.03206
  Epoch 021 - train 0.49925 | val 1.03011
  Regression -> MSE: 0.000264, MAE: 0.010987, R²: -0.0223
  Directional -> Accuracy: 0.5676, MCC: 0.0000, F1: 0.7241

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 88). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.53854 | val 0.38343
  Epoch 020 - train 0.52818 | val 0.42752
  Epoch 021 - train 0.51886 | val 0.43048
  Regression -> MSE: 0.000165, MAE: 0.010206, R²: -0.0123
  Directional -> Accuracy: 0.4872, MCC: 0.0000, F1: 0.6552

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.43252 | val 0.63003
  Epoch 020 - train 0.41947 | val 0.65214
  Epoch 021 - train 0.43030 | val 0.65254
  Regression -> MSE: 0.000183, MAE: 0.010429, R²: -0.0010
  Directional -> Accuracy: 0.5333, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.47623 | val 0.45221
  Epoch 020 - train 0.46577 | val 0.44570
  Epoch 021 - train 0.46985 | val 0.44521
  Regression -> MSE: 0.000352, MAE: 0.012313, R²: -0.0084
  Directional -> Accuracy: 0.4265, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.50365 | val 0.29220
  Epoch 020 - train 0.50566 | val 0.28239
  Epoch 030 - train 0.49716 | val 0.28149
  Regression -> MSE: 0.000110, MAE: 0.008169, R²: -0.0571
  Directional -> Accuracy: 0.5455, MCC: 0.1325, F1: 0.6667

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.53605 | val 0.94004
  Epoch 020 - train 0.52075 | val 0.95293
  Epoch 021 - train 0.53065 | val 0.95332
  Regression -> MSE: 0.000216, MAE: 0.011134, R²: -0.0028
  Directional -> Accuracy: 0.5345, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.52130 | val 1.13379
  Epoch 020 - train 0.51150 | val 1.12421
  Epoch 030 - train 0.49770 | val 1.12174
  Regression -> MSE: 0.000123, MAE: 0.008945, R²: -0.5438
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 88). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 88). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 88). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 88). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.51410 | val 0.47245
  Epoch 020 - train 0.51345 | val 0.54997
  Epoch 021 - train 0.50658 | val 0.55002
  Regression -> MSE: 0.000357, MAE: 0.016246, R²: -0.0890
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 88). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.51983 | val 0.22655
  Epoch 020 - train 0.53507 | val 0.32078
  Epoch 021 - train 0.53823 | val 0.33161
  Regression -> MSE: 0.000246, MAE: 0.011229, R²: -0.0333
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.7000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 88). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 88). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.47982 | val 0.65613
  Epoch 020 - train 0.47761 | val 0.65617
  Epoch 021 - train 0.46857 | val 0.65617
  Regression -> MSE: 0.000081, MAE: 0.007107, R²: -0.0124
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 88). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 88). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 88). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.50783 | val 0.66410
  Epoch 020 - train 0.50588 | val 0.83420
  Epoch 021 - train 0.50483 | val 0.83440
  Regression -> MSE: 0.000362, MAE: 0.015295, R²: -0.0054
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.48191 | val 0.75480
  Epoch 020 - train 0.45964 | val 0.80644
  Epoch 021 - train 0.47313 | val 0.80719
  Regression -> MSE: 0.000102, MAE: 0.007106, R²: -0.0576
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.55112 | val 0.81334
  Epoch 020 - train 0.55481 | val 0.80411
  Epoch 021 - train 0.54600 | val 0.80417
  Regression -> MSE: 0.000182, MAE: 0.009771, R²: -0.0070
  Directional -> Accuracy: 0.6341, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.44936 | val 0.77761
  Epoch 020 - train 0.44871 | val 0.79456
  Epoch 021 - train 0.44493 | val 0.79540
  Regression -> MSE: 0.000225, MAE: 0.011840, R²: -0.0247
  Directional -> Accuracy: 0.4561, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.50332 | val 0.61621
  Epoch 020 - train 0.49609 | val 0.60884
  Epoch 021 - train 0.49664 | val 0.60817
  Regression -> MSE: 0.000093, MAE: 0.007649, R²: -0.0137

[I 2026-02-22 22:05:39,355] Trial 54 finished with value: -0.011687845950075658 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 12, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.4, 'dropout': 0.1, 'batch_size': 32, 'learning_rate': 8.678766211434427e-06, 'weight_decay': 7.964086827546587e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 1.904242043914873, 'early_stopping_min_delta': 0.0040151049023678135}. Best is trial 31 with value: -0.011425014985750452.

  Epoch 020 - train 0.53336 | val 1.27043
  Epoch 021 - train 0.52990 | val 1.26537
  Regression -> MSE: 0.000255, MAE: 0.012589, R²: -0.0908
  Directional -> Accuracy: 0.5161, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.44703 | val 0.79485
  Epoch 020 - train 0.44435 | val 0.84991
  Epoch 021 - train 0.44428 | val 0.85066
  Regression -> MSE: 0.000263, MAE: 0.013089, R²: -0.0632
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.46787 | val 0.48349
  Epoch 020 - train 0.46467 | val 0.52713
  Epoch 021 - train 0.46458 | val 0.52929
  Regression -> MSE: 0.000684, MAE: 0.019375, R²: 0.0011
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.45438 | val 0.93972
  Epoch 020 - train 0.44897 | val 0.92701
  Epoch 030 - train 0.44442 | val 0.91461
  Regression -> MSE: 0.000311, MAE: 0.014526, R²: -0.0038
  Directional -> Accuracy: 0.5106, MCC: -0.0019, F1: 0.5965

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.39240 | val 0.71700
  Epoch 020 - train 0.38729 | val 0.98410
  Epoch 021 - train 0.38716 | val 0.97940
  Regression -> MSE: 0.000356, MAE: 0.014712, R²: -0.0199
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.51664 | val 0.55632
  Epoch 020 - train 0.51095 | val 0.73210
  Epoch 021 - train 0.51080 | val 0.73702
  Regression -> MSE: 0.000205, MAE: 0.010353, R²: -0.0064
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.49601 | val 1.15767
  Epoch 020 - train 0.49241 | val 1.24522
  Epoch 021 - train 0.49232 | val 1.25422
  Regression -> MSE: 0.000596, MAE: 0.018918, R²: -0.0745
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.45093 | val 0.62878
  Epoch 020 - train 0.44428 | val 0.61879
  Epoch 030 - train 0.44045 | val 0.62210
  Regression -> MSE: 0.000254, MAE: 0.012168, R²: -0.0340
  Directional -> Accuracy: 0.4493, MCC: -0.0417, F1: 0.4865

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.45367 | val 0.69065
  Epoch 020 - train 0.45184 | val 0.76466
  Epoch 021 - train 0.45180 | val 0.77682
  Regression -> MSE: 0.000632, MAE: 0.019908, R²: -0.0583
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.43928 | val 0.64113
  Epoch 020 - train 0.43776 | val 0.69751
  Epoch 021 - train 0.43772 | val 0.70425
  Regression -> MSE: 0.000383, MAE: 0.016181, R²: 0.0024
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.45804 | val 0.78040
  Epoch 020 - train 0.45546 | val 0.89231
  Epoch 021 - train 0.45539 | val 0.89252
  Regression -> MSE: 0.000245, MAE: 0.011592, R²: -0.0162
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.42343 | val 0.72841
  Epoch 020 - train 0.41553 | val 0.71862
  Epoch 030 - train 0.41017 | val 0.72357
  Regression -> MSE: 0.000370, MAE: 0.014254, R²: -0.1899
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.44595 | val 0.59614
  Epoch 020 - train 0.44455 | val 0.65645
  Epoch 021 - train 0.44451 | val 0.65941
  Regression -> MSE: 0.000676, MAE: 0.019461, R²: 0.0024
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.52420 | val 0.66749
  Epoch 020 - train 0.52019 | val 1.50375
  Epoch 021 - train 0.52009 | val 1.60890
  Regression -> MSE: 0.000142, MAE: 0.008958, R²: -0.0265
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.40746 | val 0.70268
  Epoch 020 - train 0.39813 | val 0.67440
  Epoch 030 - train 0.39060 | val 0.66598
  Regression -> MSE: 0.000219, MAE: 0.010475, R²: 0.0245
  Directional -> Accuracy: 0.5738, MCC: 0.1489, F1: 0.6286

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.46209 | val 1.29936
  Epoch 020 - train 0.45822 | val 1.30618
  Epoch 021 - train 0.45812 | val 1.30621
  Regression -> MSE: 0.000362, MAE: 0.016103, R²: -0.0004
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.46812 | val 0.51294
  Epoch 020 - train 0.46559 | val 0.60588
  Epoch 021 - train 0.46552 | val 0.60699
  Regression -> MSE: 0.000109, MAE: 0.007917, R²: -0.0059
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.46416 | val 1.00338
  Epoch 020 - train 0.46095 | val 1.49468
  Epoch 021 - train 0.46078 | val 1.52165
  Regression -> MSE: 0.000160, MAE: 0.010090, R²: -0.0256
  Directional -> Accuracy: 0.5593, MCC: 0.2314, F1: 0.5357

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.44231 | val 0.47109
  Epoch 020 - train 0.44052 | val 0.50687
  Epoch 021 - train 0.44042 | val 0.50774
  Regression -> MSE: 0.000272, MAE: 0.013058, R²: 0.0007
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.40121 | val 0.69913
  Epoch 020 - train 0.39707 | val 0.72378
  Epoch 021 - train 0.39686 | val 0.72399
  Regression -> MSE: 0.000162, MAE: 0.008970, R²: -0.0851
  Directional -> Accuracy: 0.4308, MCC: -0.1921, F1: 0.5316

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.43866 | val 0.84086
  Epoch 020 - train 0.43133 | val 0.87149
  Epoch 029 - train 0.42988 | val 0.87443
  Regression -> MSE: 0.000272, MAE: 0.012105, R²: -0.2017
  Directional -> Accuracy: 0.3600, MCC: -0.2747, F1: 0.1724

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.44359 | val 0.65866
  Epoch 020 - train 0.43695 | val 0.65762
  Epoch 030 - train 0.43455 | val 0.65314
  Regression -> MSE: 0.000178, MAE: 0.009796, R²: -0.2385
  Directional -> Accuracy: 0.4375, MCC: 0.0762, F1: 0.2703

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.43291 | val 0.61553
  Epoch 020 - train 0.43076 | val 0.64268
  Epoch 021 - train 0.43070 | val 0.64254
  Regression -> MSE: 0.000165, MAE: 0.010609, R²: 0.0036
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.45615 | val 0.62510
  Epoch 020 - train 0.45253 | val 0.63223
  Epoch 021 - train 0.45239 | val 0.63266
  Regression -> MSE: 0.000085, MAE: 0.007020, R²: 0.0043
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.49199 | val 0.65108
  Epoch 020 - train 0.48818 | val 0.67063
  Epoch 021 - train 0.48809 | val 0.67091
  Regression -> MSE: 0.000218, MAE: 0.011046, R²: -0.0284
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.41500 | val 0.37994
  Epoch 020 - train 0.40716 | val 0.38274
  Epoch 021 - train 0.40679 | val 0.38249
  Regression -> MSE: 0.000104, MAE: 0.008276, R²: -0.1280
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.47769 | val 0.34650
  Epoch 020 - train 0.47616 | val 0.35191
  Epoch 021 - train 0.47613 | val 0.35278
  Regression -> MSE: 0.000112, MAE: 0.009082, R²: -0.0819
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.50671 | val 0.48413
  Epoch 020 - train 0.50378 | val 0.65187
  Epoch 021 - train 0.50371 | val 0.66792
  Regression -> MSE: 0.000233, MAE: 0.012500, R²: -0.0067
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.46819 | val 0.56254
  Epoch 020 - train 0.45473 | val 0.56422
  Epoch 030 - train 0.45045 | val 0.56683
  Regression -> MSE: 0.000203, MAE: 0.008645, R²: -0.2200
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.44104 | val 0.29738
  Epoch 020 - train 0.43905 | val 0.29521
  Epoch 021 - train 0.43885 | val 0.29468
  Regression -> MSE: 0.000236, MAE: 0.011843, R²: 0.0024
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.44883 | val 0.91745
  Epoch 020 - train 0.44419 | val 0.92322
  Epoch 021 - train 0.44408 | val 0.92422
  Regression -> MSE: 0.000231, MAE: 0.009871, R²: -0.0030
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.47436 | val 0.63314
  Epoch 020 - train 0.47235 | val 0.67699
  Epoch 021 - train 0.47229 | val 0.68420
  Regression -> MSE: 0.000137, MAE: 0.008279, R²: -0.0138
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.45044 | val 0.64894
  Epoch 020 - train 0.44764 | val 0.66201
  Epoch 021 - train 0.44757 | val 0.66265
  Regression -> MSE: 0.000195, MAE: 0.010517, R²: -0.0371
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.38324 | val 0.59935
  Epoch 020 - train 0.37844 | val 0.59433
  Epoch 030 - train 0.37429 | val 0.59171
  Regression -> MSE: 0.000320, MAE: 0.011712, R²: -0.2222
  Directional -> Accuracy: 0.5205, MCC: 0.2644, F1: 0.2553

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.51273 | val 0.35987
  Epoch 020 - train 0.50946 | val 0.36513
  Epoch 021 - train 0.50937 | val 0.36608
  Regression -> MSE: 0.000170, MAE: 0.010375, R²: -0.0172
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.39184 | val 0.55641
  Epoch 020 - train 0.38942 | val 0.61994
  Epoch 021 - train 0.38936 | val 0.62517
  Regression -> MSE: 0.000184, MAE: 0.010486, R²: -0.0234
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.42395 | val 0.42176
  Epoch 020 - train 0.41451 | val 0.39970
  Epoch 030 - train 0.40761 | val 0.39976
  Regression -> MSE: 0.000327, MAE: 0.011934, R²: 0.0444
  Directional -> Accuracy: 0.5075, MCC: 0.1239, F1: 0.3529

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.45637 | val 0.24513
  Epoch 020 - train 0.44980 | val 0.25011
  Epoch 021 - train 0.44948 | val 0.25104
  Regression -> MSE: 0.000123, MAE: 0.008419, R²: -0.1701
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.45489 | val 0.76518
  Epoch 020 - train 0.44462 | val 0.78940
  Epoch 021 - train 0.44413 | val 0.79159
  Regression -> MSE: 0.000220, MAE: 0.011344, R²: -0.0049
  Directional -> Accuracy: 0.4737, MCC: -0.0882, F1: 0.2857

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.44297 | val 1.06096
  Epoch 020 - train 0.44144 | val 1.07246
  Epoch 021 - train 0.44140 | val 1.07334
  Regression -> MSE: 0.000091, MAE: 0.007460, R²: -0.1716
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.48314 | val 0.26352
  Epoch 020 - train 0.47063 | val 0.25618
  Epoch 030 - train 0.45909 | val 0.24737
  Regression -> MSE: 0.000312, MAE: 0.012989, R²: -0.0156
  Directional -> Accuracy: 0.6531, MCC: 0.1894, F1: 0.1053

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.50408 | val 0.20071
  Epoch 020 - train 0.49237 | val 0.19135
  Epoch 030 - train 0.48379 | val 0.20191
  Regression -> MSE: 0.000256, MAE: 0.011464, R²: -0.0484
  Directional -> Accuracy: 0.5000, MCC: -0.0574, F1: 0.6415

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.46572 | val 0.60188
  Epoch 020 - train 0.46056 | val 0.60573
  Epoch 021 - train 0.46043 | val 0.60574
  Regression -> MSE: 0.000088, MAE: 0.007116, R²: -0.0866
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.45461 | val 0.67905
  Epoch 020 - train 0.45285 | val 0.70043
  Epoch 021 - train 0.45281 | val 0.69795
  Regression -> MSE: 0.000312, MAE: 0.014522, R²: -0.0166
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.41488 | val 0.59280
  Epoch 020 - train 0.41259 | val 0.58087
  Epoch 030 - train 0.41037 | val 0.56677
  Regression -> MSE: 0.000098, MAE: 0.007112, R²: 0.0036
  Directional -> Accuracy: 0.6136, MCC: 0.2503, F1: 0.7463

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.50727 | val 0.70970
  Epoch 020 - train 0.50515 | val 0.71647
  Epoch 021 - train 0.50509 | val 0.71727
  Regression -> MSE: 0.000175, MAE: 0.010141, R²: -0.0174
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.40589 | val 0.58222
  Epoch 020 - train 0.40382 | val 0.85413
  Epoch 021 - train 0.40373 | val 0.87123
  Regression -> MSE: 0.000225, MAE: 0.011822, R²: -0.0086
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.45798 | val 0.55886
  Epoch 020 - train 0.45304 | val 0.57227
  Epoch 021 - train 0.45283 | val 0.57264
  Regression -> MSE: 0.000092, MAE: 0.007635, R²: 0.0007
  Directional -> Accuracy: 0.4912, MCC: -0.0148, F1: 0.4912


[I 2026-02-22 22:07:05,910] Trial 55 finished with value: -0.011517100972667914 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.4, 'dropout': 0.0, 'batch_size': 64, 'learning_rate': 4.358146453380115e-06, 'weight_decay': 3.177241461759986e-06, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 1.4301822755920508, 'early_stopping_min_delta': 0.004744286021063843}. Best is trial 31 with value: -0.011425014985750452.

  Epoch 020 - train 0.45120 | val 0.91016
  Epoch 021 - train 0.45116 | val 0.91694
  Regression -> MSE: 0.000238, MAE: 0.012352, R²: -0.0033
  Directional -> Accuracy: 0.5738, MCC: 0.1567, F1: 0.5938

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.46249 | val 0.80116
  Epoch 011 - train 0.47081 | val 0.80201
  Regression -> MSE: 0.000241, MAE: 0.012366, R²: -0.0018
  Directional -> Accuracy: 0.5132, MCC: 0.0126, F1: 0.4478

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.43980 | val 0.64352
  Epoch 011 - train 0.45531 | val 0.65012
  Regression -> MSE: 0.000688, MAE: 0.019441, R²: 0.0135
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.46887 | val 0.92882
  Epoch 015 - train 0.44727 | val 0.94927
  Regression -> MSE: 0.000320, MAE: 0.014436, R²: -0.0159
  Directional -> Accuracy: 0.5435, MCC: 0.0961, F1: 0.5116

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.43763 | val 1.45407
  Epoch 011 - train 0.42805 | val 1.45856
  Regression -> MSE: 0.000376, MAE: 0.015105, R²: -0.0631
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.47620 | val 0.50765
  Epoch 011 - train 0.48134 | val 0.51178
  Regression -> MSE: 0.000214, MAE: 0.010313, R²: -0.0380
  Directional -> Accuracy: 0.5200, MCC: 0.0000, F1: 0.6842

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.43587 | val 0.97893
  Epoch 011 - train 0.45091 | val 0.97993
  Regression -> MSE: 0.000564, MAE: 0.018340, R²: 0.0031
  Directional -> Accuracy: 0.4565, MCC: -0.0851, F1: 0.6032

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.46107 | val 0.61235
  Epoch 019 - train 0.47078 | val 0.61136
  Regression -> MSE: 0.000254, MAE: 0.012757, R²: -0.0256
  Directional -> Accuracy: 0.4265, MCC: 0.0405, F1: 0.5618

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.46319 | val 0.52251
  Epoch 011 - train 0.45718 | val 0.53675
  Regression -> MSE: 0.000672, MAE: 0.020435, R²: -0.1000
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.46699 | val 0.70287
  Epoch 011 - train 0.45673 | val 0.71241
  Regression -> MSE: 0.000373, MAE: 0.016001, R²: 0.0004
  Directional -> Accuracy: 0.4375, MCC: 0.0000, F1: 0.6087

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.45756 | val 0.66843
  Epoch 014 - train 0.47135 | val 0.66860
  Regression -> MSE: 0.000246, MAE: 0.011928, R²: -0.0055
  Directional -> Accuracy: 0.5072, MCC: 0.0361, F1: 0.5000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.45830 | val 0.72675
  Epoch 018 - train 0.48218 | val 0.72762
  Regression -> MSE: 0.000308, MAE: 0.013536, R²: 0.0134
  Directional -> Accuracy: 0.5714, MCC: 0.1005, F1: 0.2759

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.53916 | val 0.69123
  Epoch 011 - train 0.55649 | val 0.69367
  Regression -> MSE: 0.000704, MAE: 0.019817, R²: -0.0260
  Directional -> Accuracy: 0.4912, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.54112 | val 0.58792
  Epoch 011 - train 0.50757 | val 0.60348
  Regression -> MSE: 0.000140, MAE: 0.009198, R²: -0.0111
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.43799 | val 0.72887
  Epoch 013 - train 0.40381 | val 0.73688
  Regression -> MSE: 0.000225, MAE: 0.010689, R²: 0.0044
  Directional -> Accuracy: 0.4833, MCC: -0.0370, F1: 0.3404

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.48523 | val 1.33316
  Epoch 011 - train 0.48904 | val 1.33930
  Regression -> MSE: 0.000370, MAE: 0.016052, R²: -0.0081
  Directional -> Accuracy: 0.4902, MCC: -0.1094, F1: 0.1875

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.50115 | val 0.46717
  Epoch 019 - train 0.47486 | val 0.46616
  Regression -> MSE: 0.000104, MAE: 0.007799, R²: 0.0331
  Directional -> Accuracy: 0.5652, MCC: 0.1442, F1: 0.5455

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.44819 | val 1.30750
  Epoch 011 - train 0.43741 | val 1.31567
  Regression -> MSE: 0.000158, MAE: 0.009664, R²: -0.0046
  Directional -> Accuracy: 0.6207, MCC: 0.0000, F1: 0.7660

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.46917 | val 0.46277
  Epoch 011 - train 0.46035 | val 0.46288
  Regression -> MSE: 0.000278, MAE: 0.013227, R²: -0.0150
  Directional -> Accuracy: 0.4933, MCC: -0.0109, F1: 0.5366

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.36247 | val 0.70337
  Epoch 013 - train 0.37046 | val 0.70421
  Regression -> MSE: 0.000159, MAE: 0.008987, R²: -0.0480
  Directional -> Accuracy: 0.5156, MCC: -0.0299, F1: 0.6173

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.55023 | val 0.90743
  Epoch 013 - train 0.52482 | val 0.90781
  Regression -> MSE: 0.000239, MAE: 0.011003, R²: -0.0513
  Directional -> Accuracy: 0.5405, MCC: 0.1426, F1: 0.4516

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.47126 | val 0.70709
  Epoch 014 - train 0.49944 | val 0.75448
  Regression -> MSE: 0.000146, MAE: 0.008349, R²: -0.0169
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.45015 | val 0.58386
  Epoch 011 - train 0.42790 | val 0.58498
  Regression -> MSE: 0.000173, MAE: 0.010213, R²: -0.0463
  Directional -> Accuracy: 0.6000, MCC: 0.2359, F1: 0.4800

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.56465 | val 0.64660
  Epoch 011 - train 0.55693 | val 0.64842
  Regression -> MSE: 0.000087, MAE: 0.007213, R²: -0.0083
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.51005 | val 0.90527
  Epoch 011 - train 0.48000 | val 0.90491
  Regression -> MSE: 0.000219, MAE: 0.011014, R²: -0.0389
  Directional -> Accuracy: 0.5231, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.54091 | val 0.43918
  Epoch 011 - train 0.55747 | val 0.43909
  Regression -> MSE: 0.000091, MAE: 0.008021, R²: -0.0113
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.49599 | val 0.36154
  Epoch 011 - train 0.46925 | val 0.36311
  Regression -> MSE: 0.000106, MAE: 0.008886, R²: -0.0693
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.50404 | val 0.43945
  Epoch 011 - train 0.50196 | val 0.44133
  Regression -> MSE: 0.000241, MAE: 0.013015, R²: -0.0188
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.48465 | val 0.61106
  Epoch 011 - train 0.50044 | val 0.61317
  Regression -> MSE: 0.000195, MAE: 0.008296, R²: -0.1525
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.48957 | val 0.35046
  Epoch 011 - train 0.46586 | val 0.36395
  Regression -> MSE: 0.000242, MAE: 0.012073, R²: -0.0008
  Directional -> Accuracy: 0.5500, MCC: 0.0000, F1: 0.7097

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.45187 | val 0.92378
  Epoch 011 - train 0.46096 | val 0.92551
  Regression -> MSE: 0.000236, MAE: 0.010043, R²: 0.0011
  Directional -> Accuracy: 0.5000, MCC: -0.0793, F1: 0.0870

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.47243 | val 0.64031
  Epoch 011 - train 0.47867 | val 0.65454
  Regression -> MSE: 0.000140, MAE: 0.008383, R²: -0.0136
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.7077

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.43954 | val 0.69983
  Epoch 011 - train 0.46178 | val 0.70082
  Regression -> MSE: 0.000183, MAE: 0.010240, R²: -0.0002
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.38950 | val 0.69831
  Epoch 011 - train 0.38704 | val 0.69905
  Regression -> MSE: 0.000265, MAE: 0.010621, R²: 0.0008
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.47632 | val 0.52872
  Epoch 015 - train 0.48049 | val 0.53948
  Regression -> MSE: 0.000203, MAE: 0.011207, R²: -0.1098
  Directional -> Accuracy: 0.4419, MCC: -0.2093, F1: 0.0769

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.45496 | val 0.41870
  Epoch 015 - train 0.44052 | val 0.41833
  Regression -> MSE: 0.000355, MAE: 0.012450, R²: -0.0197
  Directional -> Accuracy: 0.4394, MCC: 0.0140, F1: 0.1395

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.52228 | val 0.23759
  Epoch 018 - train 0.50076 | val 0.24326
  Regression -> MSE: 0.000132, MAE: 0.008874, R²: -0.2462
  Directional -> Accuracy: 0.3571, MCC: -0.2897, F1: 0.2286

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.46423 | val 0.74167
  Epoch 016 - train 0.47348 | val 0.74498
  Regression -> MSE: 0.000221, MAE: 0.011034, R²: -0.0044
  Directional -> Accuracy: 0.5893, MCC: 0.1949, F1: 0.6102

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.47973 | val 1.06782
  Epoch 014 - train 0.51801 | val 1.06823
  Regression -> MSE: 0.000092, MAE: 0.007456, R²: -0.2484
  Directional -> Accuracy: 0.3913, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.43983 | val 0.25649
  Epoch 011 - train 0.51787 | val 0.25674
  Regression -> MSE: 0.000321, MAE: 0.014382, R²: -0.0300
  Directional -> Accuracy: 0.3333, MCC: -0.1687, F1: 0.4839

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.42972 | val 0.67559
  Epoch 011 - train 0.43873 | val 0.67600
  Regression -> MSE: 0.000078, MAE: 0.006943, R²: -0.0005
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.50619 | val 0.85070
  Epoch 011 - train 0.51049 | val 0.89319
  Regression -> MSE: 0.000313, MAE: 0.014378, R²: -0.0415
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.50812 | val 0.55922
  Epoch 011 - train 0.47363 | val 0.56183
  Regression -> MSE: 0.000105, MAE: 0.007275, R²: -0.0324
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.54699 | val 0.77483
  Epoch 011 - train 0.51625 | val 0.79145
  Regression -> MSE: 0.000179, MAE: 0.010332, R²: -0.0211
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.41938 | val 0.61905
  Epoch 011 - train 0.41728 | val 0.62375
  Regression -> MSE: 0.000227, MAE: 0.011745, R²: -0.0050
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.45683 | val 0.61967
  Epoch 011 - train 0.46334 | val 0.61959
  Regression -> MSE: 0.000095, MAE: 0.007855, R²: -0.0083
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.57198 | val 0.99014
  Epoch 011 - train 0.58118 | val 0.99344
  Regression -> MSE: 0.000170, MAE: 0.010493, R²: -0.0173
  Directional -> Accuracy: 0.4906, MCC: 0.0000, F1: 0.0000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.48175 | val 0.65574
  Epoch 011 - train 0.46742 | val 0.65848
  Regression -> MSE: 0.000135, MAE: 0.009309, R²: -0.1441
  Directional -> Accuracy: 0.4727, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...

[I 2026-02-22 22:07:27,883] Trial 56 finished with value: -0.011535605025435084 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.4, 'dropout': 0.5, 'batch_size': 32, 'learning_rate': 1.2982345538634525e-06, 'weight_decay': 1.7469061099963462e-06, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 1.3408602594405081, 'early_stopping_min_delta': 0.003259753308420187}. Best is trial 31 with value: -0.011425014985750452.

  Epoch 010 - train 0.50347 | val 1.21793
  Epoch 011 - train 0.49750 | val 1.24304
  Regression -> MSE: 0.000239, MAE: 0.012518, R²: 0.0046
  Directional -> Accuracy: 0.4833, MCC: 0.0000, F1: 0.6517

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.38026 | val 0.68757
  Epoch 020 - train 0.35552 | val 1.21902
  Epoch 022 - train 0.35763 | val 1.31777
  Regression -> MSE: 0.000244, MAE: 0.012382, R²: -0.0141
  Directional -> Accuracy: 0.5000, MCC: 0.1154, F1: 0.6200

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.36828 | val 0.42029
  Epoch 020 - train 0.35547 | val 0.44583
  Epoch 026 - train 0.36531 | val 0.44651
  Regression -> MSE: 0.000682, MAE: 0.019362, R²: 0.0224
  Directional -> Accuracy: 0.6000, MCC: 0.1764, F1: 0.7429

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.41233 | val 0.88049
  Epoch 020 - train 0.37752 | val 0.87036
  Epoch 030 - train 0.36907 | val 0.90359
  Regression -> MSE: 0.000365, MAE: 0.015416, R²: -0.1588
  Directional -> Accuracy: 0.6087, MCC: 0.2423, F1: 0.5500

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.33379 | val 0.40030
  Epoch 016 - train 0.33128 | val 0.43251
  Regression -> MSE: 0.000353, MAE: 0.014682, R²: 0.0004
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.40043 | val 0.39979
  Epoch 020 - train 0.37755 | val 0.46329
  Epoch 028 - train 0.36082 | val 0.50065
  Regression -> MSE: 0.000199, MAE: 0.009680, R²: 0.0358
  Directional -> Accuracy: 0.5600, MCC: 0.1141, F1: 0.6452

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.35832 | val 0.98675
  Epoch 016 - train 0.33904 | val 1.19460
  Regression -> MSE: 0.000565, MAE: 0.018375, R²: 0.0016
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.6471

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.39274 | val 0.63433
  Epoch 020 - train 0.37724 | val 0.74764
  Epoch 021 - train 0.37519 | val 0.77445
  Regression -> MSE: 0.000251, MAE: 0.011904, R²: -0.0109
  Directional -> Accuracy: 0.6029, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.32887 | val 0.39438
  Epoch 016 - train 0.34574 | val 0.48482
  Regression -> MSE: 0.000619, MAE: 0.019593, R²: -0.0127
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.36203 | val 0.56245
  Epoch 016 - train 0.34671 | val 0.59137
  Regression -> MSE: 0.000380, MAE: 0.015597, R²: -0.0180
  Directional -> Accuracy: 0.5625, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.37543 | val 0.64011
  Epoch 020 - train 0.35085 | val 0.67659
  Epoch 022 - train 0.36416 | val 0.66124
  Regression -> MSE: 0.000243, MAE: 0.011842, R²: 0.0064
  Directional -> Accuracy: 0.4783, MCC: -0.0139, F1: 0.4857

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.34230 | val 0.73085
  Epoch 016 - train 0.35244 | val 0.88188
  Regression -> MSE: 0.000319, MAE: 0.013488, R²: -0.0221
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.42843 | val 0.55838
  Epoch 020 - train 0.38314 | val 0.82480
  Epoch 022 - train 0.37976 | val 0.79156
  Regression -> MSE: 0.000681, MAE: 0.019694, R²: 0.0077
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.38882 | val 0.50060
  Epoch 016 - train 0.39516 | val 0.63709
  Regression -> MSE: 0.000147, MAE: 0.009511, R²: -0.0627
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.31588 | val 0.66940
  Epoch 016 - train 0.34213 | val 0.77490
  Regression -> MSE: 0.000228, MAE: 0.010704, R²: -0.0067
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.37877 | val 1.17467
  Epoch 020 - train 0.34318 | val 1.62333
  Epoch 027 - train 0.33744 | val 1.66430
  Regression -> MSE: 0.000382, MAE: 0.016751, R²: -0.0429
  Directional -> Accuracy: 0.4510, MCC: 0.0000, F1: 0.6216

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.41851 | val 0.47123
  Epoch 016 - train 0.38427 | val 0.55676
  Regression -> MSE: 0.000110, MAE: 0.007947, R²: -0.0171
  Directional -> Accuracy: 0.5362, MCC: 0.0000, F1: 0.6981

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.35990 | val 0.94337
  Epoch 016 - train 0.35966 | val 0.99339
  Regression -> MSE: 0.000158, MAE: 0.009772, R²: 0.0010
  Directional -> Accuracy: 0.6207, MCC: 0.0000, F1: 0.7660

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.40071 | val 0.45968
  Epoch 016 - train 0.40192 | val 0.68057
  Regression -> MSE: 0.000274, MAE: 0.013036, R²: 0.0003
  Directional -> Accuracy: 0.6000, MCC: 0.0000, F1: 0.7500

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.32885 | val 0.63502
  Epoch 020 - train 0.31430 | val 0.63327
  Epoch 028 - train 0.32633 | val 0.64277
  Regression -> MSE: 0.000188, MAE: 0.010067, R²: -0.2380
  Directional -> Accuracy: 0.4219, MCC: -0.0509, F1: 0.1395

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.36840 | val 0.83536
  Epoch 020 - train 0.36849 | val 0.82566
  Epoch 030 - train 0.35260 | val 0.89205
  Regression -> MSE: 0.000271, MAE: 0.011847, R²: -0.1909
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.38884 | val 0.65194
  Epoch 016 - train 0.37583 | val 0.66559
  Regression -> MSE: 0.000147, MAE: 0.008485, R²: -0.0193
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.36527 | val 0.55128
  Epoch 016 - train 0.35478 | val 0.58840
  Regression -> MSE: 0.000174, MAE: 0.010307, R²: -0.0493
  Directional -> Accuracy: 0.4000, MCC: -0.2061, F1: 0.2909

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.40349 | val 0.57798
  Epoch 020 - train 0.37563 | val 0.64386
  Epoch 022 - train 0.36428 | val 0.63560
  Regression -> MSE: 0.000089, MAE: 0.007335, R²: -0.0280
  Directional -> Accuracy: 0.5439, MCC: 0.1093, F1: 0.5357

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.38045 | val 0.62356
  Epoch 016 - train 0.35543 | val 0.65171
  Regression -> MSE: 0.000218, MAE: 0.010997, R²: -0.0322
  Directional -> Accuracy: 0.5231, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.34126 | val 0.37645
  Epoch 020 - train 0.31570 | val 0.34687
  Epoch 030 - train 0.28508 | val 0.34801
  Regression -> MSE: 0.000116, MAE: 0.008483, R²: -0.2855
  Directional -> Accuracy: 0.4364, MCC: -0.0924, F1: 0.1143

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.40815 | val 0.35171
  Epoch 016 - train 0.39907 | val 0.35337
  Regression -> MSE: 0.000101, MAE: 0.008634, R²: -0.0138
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.41542 | val 0.41565
  Epoch 016 - train 0.38308 | val 0.44741
  Regression -> MSE: 0.000238, MAE: 0.012883, R²: -0.0064
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.38930 | val 0.56174
  Epoch 020 - train 0.36665 | val 0.55586
  Epoch 030 - train 0.36304 | val 0.57075
  Regression -> MSE: 0.000190, MAE: 0.008023, R²: -0.1219
  Directional -> Accuracy: 0.5179, MCC: 0.0797, F1: 0.4490

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.41175 | val 0.34655
  Epoch 016 - train 0.35953 | val 0.34524
  Regression -> MSE: 0.000245, MAE: 0.012207, R²: -0.0113
  Directional -> Accuracy: 0.5500, MCC: 0.0000, F1: 0.7097

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.39876 | val 0.89823
  Epoch 016 - train 0.38375 | val 0.90909
  Regression -> MSE: 0.000236, MAE: 0.010047, R²: -0.0005
  Directional -> Accuracy: 0.5238, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.44753 | val 0.55475
  Epoch 018 - train 0.37270 | val 0.64672
  Regression -> MSE: 0.000142, MAE: 0.008444, R²: -0.0287
  Directional -> Accuracy: 0.4286, MCC: -0.1070, F1: 0.2000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.38985 | val 0.65099
  Epoch 020 - train 0.35845 | val 0.66404
  Epoch 024 - train 0.34669 | val 0.70250
  Regression -> MSE: 0.000186, MAE: 0.010441, R²: -0.0158
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.32754 | val 0.55797
  Epoch 020 - train 0.31931 | val 0.58929
  Epoch 028 - train 0.29551 | val 0.57052
  Regression -> MSE: 0.000351, MAE: 0.012964, R²: -0.3209
  Directional -> Accuracy: 0.5278, MCC: 0.1419, F1: 0.3929

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.33981 | val 0.51613
  Epoch 016 - train 0.32725 | val 0.55543
  Regression -> MSE: 0.000184, MAE: 0.010447, R²: -0.0048
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.36349 | val 0.40933
  Epoch 020 - train 0.34364 | val 0.53952
  Epoch 024 - train 0.32824 | val 0.50670
  Regression -> MSE: 0.000360, MAE: 0.013058, R²: -0.0354
  Directional -> Accuracy: 0.4242, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.37022 | val 0.23085
  Epoch 016 - train 0.39770 | val 0.23293
  Regression -> MSE: 0.000112, MAE: 0.008323, R²: -0.0559
  Directional -> Accuracy: 0.5238, MCC: 0.0000, F1: 0.6875

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.37795 | val 0.73464
  Epoch 018 - train 0.37286 | val 0.76716
  Regression -> MSE: 0.000223, MAE: 0.011387, R²: -0.0152
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.6341

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.37230 | val 1.03179
  Epoch 016 - train 0.37211 | val 1.07788
  Regression -> MSE: 0.000077, MAE: 0.006829, R²: -0.0426
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.38153 | val 0.23881
  Epoch 016 - train 0.37542 | val 0.23859
  Regression -> MSE: 0.000315, MAE: 0.014030, R²: -0.0105
  Directional -> Accuracy: 0.6458, MCC: 0.0000, F1: 0.0000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.34859 | val 0.63622
  Epoch 018 - train 0.34610 | val 1.01331
  Regression -> MSE: 0.000078, MAE: 0.006889, R²: 0.0026
  Directional -> Accuracy: 0.5676, MCC: 0.1940, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.39666 | val 0.60948
  Epoch 020 - train 0.36398 | val 0.65038
  Epoch 028 - train 0.35022 | val 0.79460
  Regression -> MSE: 0.000300, MAE: 0.014312, R²: 0.0025
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.37885 | val 0.56395
  Epoch 020 - train 0.35026 | val 0.53132
  Epoch 030 - train 0.33291 | val 0.49616
  Regression -> MSE: 0.000103, MAE: 0.007072, R²: -0.0091
  Directional -> Accuracy: 0.5714, MCC: 0.0589, F1: 0.7000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.40639 | val 0.67119
  Epoch 016 - train 0.41333 | val 0.66959
  Regression -> MSE: 0.000176, MAE: 0.009797, R²: -0.0016
  Directional -> Accuracy: 0.4792, MCC: -0.0990, F1: 0.3243

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.36488 | val 0.52941
  Epoch 016 - train 0.35625 | val 0.57568
  Regression -> MSE: 0.000225, MAE: 0.011799, R²: 0.0009
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.37662 | val 0.60025
  Epoch 016 - train 0.33572 | val 0.94842
  Regression -> MSE: 0.000095, MAE: 0.007790, R²: -0.0087
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.40596 | val 0.83539
  Epoch 016 - train 0.39862 | val 0.91030
  Regression -> MSE: 0.000167, MAE: 0.010435, R²: -0.0015
  Directional -> Accuracy: 0.5094, MCC: 0.0000, F1: 0.6750

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.36635 | val 0.62133
  Epoch 016 - train 0.35540 | val 0.74023
  Regression -> MSE: 0.000126, MAE: 0.009177, R²: -0.0728
  Directional -> Accuracy: 0.4727, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.41834 | val 0.78883
  Epoch 020 - train 0.36941 | val 0.84821

[I 2026-02-22 22:08:43,950] Trial 57 finished with value: -0.011550485461925828 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.2, 'batch_size': 64, 'learning_rate': 0.0013079843728764087, 'weight_decay': 1.2798783613159244e-06, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 30, 'huber_delta': 1.2568571685971421, 'early_stopping_min_delta': 0.003519000067402753}. Best is trial 31 with value: -0.011425014985750452.

  Epoch 026 - train 0.36658 | val 0.85296
  Regression -> MSE: 0.000236, MAE: 0.012175, R²: 0.0177
  Directional -> Accuracy: 0.6167, MCC: 0.2358, F1: 0.5306

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.41891 | val 0.66394
  Epoch 016 - train 0.41610 | val 0.65780
  Regression -> MSE: 0.000248, MAE: 0.012536, R²: -0.0021
  Directional -> Accuracy: 0.5195, MCC: -0.0246, F1: 0.2449

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.47495 | val 0.85431
  Epoch 016 - train 0.45759 | val 0.85894
  Regression -> MSE: 0.000689, MAE: 0.019396, R²: -0.0060
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.42846 | val 0.84571
  Epoch 016 - train 0.41821 | val 0.84883
  Regression -> MSE: 0.000310, MAE: 0.014437, R²: 0.0000
  Directional -> Accuracy: 0.5106, MCC: 0.0092, F1: 0.5660

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.37527 | val 0.54553
  Epoch 016 - train 0.37184 | val 0.46599
  Regression -> MSE: 0.000355, MAE: 0.014662, R²: -0.0151
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.43743 | val 0.59522
  Epoch 016 - train 0.43850 | val 0.60599
  Regression -> MSE: 0.000210, MAE: 0.010564, R²: -0.0316
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.41189 | val 1.36193
  Epoch 016 - train 0.39916 | val 1.52136
  Regression -> MSE: 0.000568, MAE: 0.018276, R²: -0.0235
  Directional -> Accuracy: 0.4468, MCC: -0.1704, F1: 0.1333

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.41578 | val 0.62341
  Epoch 016 - train 0.41547 | val 0.62983
  Regression -> MSE: 0.000245, MAE: 0.012251, R²: 0.0003
  Directional -> Accuracy: 0.3913, MCC: -0.1302, F1: 0.5000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.42099 | val 0.61712
  Epoch 016 - train 0.42719 | val 0.61468
  Regression -> MSE: 0.000634, MAE: 0.020010, R²: -0.0614
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.39235 | val 0.51937
  Epoch 020 - train 0.39034 | val 0.50656
  Regression -> MSE: 0.000433, MAE: 0.016386, R²: -0.1294
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.41591 | val 0.66193
  Epoch 016 - train 0.41718 | val 0.63382
  Regression -> MSE: 0.000247, MAE: 0.012471, R²: -0.0244
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.38053 | val 0.66616
  Epoch 016 - train 0.38617 | val 0.66573
  Regression -> MSE: 0.000315, MAE: 0.013543, R²: -0.0141
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.44723 | val 0.79083
  Epoch 016 - train 0.44927 | val 0.79391
  Regression -> MSE: 0.000678, MAE: 0.019396, R²: -0.0006
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.40463 | val 0.70650
  Epoch 016 - train 0.41123 | val 0.76755
  Regression -> MSE: 0.000137, MAE: 0.009039, R²: 0.0077
  Directional -> Accuracy: 0.4884, MCC: -0.0044, F1: 0.5000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.38084 | val 0.65456
  Epoch 016 - train 0.37403 | val 0.65578
  Regression -> MSE: 0.000226, MAE: 0.010702, R²: -0.0060
  Directional -> Accuracy: 0.5246, MCC: 0.0466, F1: 0.5797

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.40418 | val 1.14411
  Epoch 016 - train 0.39026 | val 1.14533
  Regression -> MSE: 0.000365, MAE: 0.015903, R²: -0.0083
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.43137 | val 0.53072
  Epoch 016 - train 0.43572 | val 0.52209
  Regression -> MSE: 0.000110, MAE: 0.007928, R²: -0.0189
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.38975 | val 0.93311
  Epoch 016 - train 0.39159 | val 0.93168
  Regression -> MSE: 0.000158, MAE: 0.009776, R²: -0.0109
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.42845 | val 0.59607
  Epoch 016 - train 0.42715 | val 0.57837
  Regression -> MSE: 0.000286, MAE: 0.012982, R²: -0.0496
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.38058 | val 0.68210
  Epoch 016 - train 0.37605 | val 0.68351
  Regression -> MSE: 0.000151, MAE: 0.008879, R²: -0.0077
  Directional -> Accuracy: 0.5692, MCC: 0.0093, F1: 0.7083

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.41959 | val 0.73227
  Epoch 016 - train 0.40952 | val 0.72673
  Regression -> MSE: 0.000246, MAE: 0.011149, R²: -0.0857
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.42599 | val 0.57398
  Epoch 020 - train 0.40625 | val 0.58124
  Regression -> MSE: 0.000168, MAE: 0.009332, R²: -0.1689
  Directional -> Accuracy: 0.3958, MCC: -0.0176, F1: 0.1714

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.41023 | val 0.59549
  Epoch 016 - train 0.40170 | val 0.58283
  Regression -> MSE: 0.000179, MAE: 0.010757, R²: -0.0806
  Directional -> Accuracy: 0.3939, MCC: -0.2186, F1: 0.4595

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.44767 | val 0.56626
  Epoch 016 - train 0.44412 | val 0.56443
  Regression -> MSE: 0.000089, MAE: 0.007243, R²: -0.0439
  Directional -> Accuracy: 0.4655, MCC: -0.0951, F1: 0.5373

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.40725 | val 0.60838
  Epoch 016 - train 0.40336 | val 0.62463
  Regression -> MSE: 0.000214, MAE: 0.011059, R²: -0.0087
  Directional -> Accuracy: 0.5000, MCC: -0.0365, F1: 0.2979

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.38708 | val 0.43280
  Epoch 016 - train 0.38964 | val 0.42195
  Regression -> MSE: 0.000100, MAE: 0.008231, R²: -0.0823
  Directional -> Accuracy: 0.4464, MCC: -0.2064, F1: 0.5867

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.41542 | val 0.31671
  Epoch 019 - train 0.42331 | val 0.34155
  Regression -> MSE: 0.000105, MAE: 0.008799, R²: -0.0150
  Directional -> Accuracy: 0.4783, MCC: -0.0156, F1: 0.5000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.49337 | val 1.10683
  Epoch 016 - train 0.49109 | val 1.11346
  Regression -> MSE: 0.000248, MAE: 0.012795, R²: -0.0732
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.40461 | val 0.54486
  Epoch 016 - train 0.41372 | val 0.54355
  Regression -> MSE: 0.000184, MAE: 0.008014, R²: -0.1048
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.46732 | val 0.30212
  Epoch 016 - train 0.45656 | val 0.34216
  Regression -> MSE: 0.000240, MAE: 0.011957, R²: -0.0148
  Directional -> Accuracy: 0.4878, MCC: 0.1469, F1: 0.0870

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.42706 | val 0.80191
  Epoch 020 - train 0.43006 | val 0.80473
  Regression -> MSE: 0.000237, MAE: 0.010362, R²: -0.0292
  Directional -> Accuracy: 0.5814, MCC: 0.2280, F1: 0.6786

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.41487 | val 0.53265
  Epoch 020 - train 0.42608 | val 0.53126
  Regression -> MSE: 0.000134, MAE: 0.008531, R²: 0.0056
  Directional -> Accuracy: 0.5116, MCC: -0.0724, F1: 0.6667

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.41787 | val 0.59555
  Epoch 016 - train 0.40185 | val 0.59607
  Regression -> MSE: 0.000189, MAE: 0.010443, R²: -0.0023
  Directional -> Accuracy: 0.5200, MCC: -0.1319, F1: 0.6842

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.37824 | val 0.53169
  Epoch 016 - train 0.36986 | val 0.53028
  Regression -> MSE: 0.000273, MAE: 0.010870, R²: -0.0426
  Directional -> Accuracy: 0.5068, MCC: 0.0948, F1: 0.3793

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.39980 | val 0.33256
  Epoch 020 - train 0.40493 | val 0.34813
  Regression -> MSE: 0.000169, MAE: 0.010431, R²: -0.0142
  Directional -> Accuracy: 0.4211, MCC: -0.2037, F1: 0.1538

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.40829 | val 0.47128
  Epoch 020 - train 0.40042 | val 0.47933
  Regression -> MSE: 0.000192, MAE: 0.010764, R²: -0.0653
  Directional -> Accuracy: 0.4545, MCC: -0.1668, F1: 0.1429

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.41220 | val 0.43236
  Epoch 016 - train 0.39264 | val 0.42905
  Regression -> MSE: 0.000348, MAE: 0.011742, R²: -0.0155
  Directional -> Accuracy: 0.6119, MCC: 0.1940, F1: 0.7347

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.46908 | val 0.34918
  Epoch 016 - train 0.47586 | val 0.38045
  Regression -> MSE: 0.000126, MAE: 0.008408, R²: -0.1969
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.41304 | val 0.69359
  Epoch 016 - train 0.41559 | val 0.70101
  Regression -> MSE: 0.000221, MAE: 0.011347, R²: -0.0104
  Directional -> Accuracy: 0.4737, MCC: -0.0243, F1: 0.5946

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.42177 | val 0.96956
  Epoch 016 - train 0.41439 | val 0.96794
  Regression -> MSE: 0.000092, MAE: 0.007463, R²: -0.1783
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.45525 | val 0.45527
  Epoch 016 - train 0.45146 | val 0.48901
  Regression -> MSE: 0.000345, MAE: 0.015418, R²: -0.1221
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.53540 | val 0.19122
  Epoch 016 - train 0.55007 | val 0.21000
  Regression -> MSE: 0.000247, MAE: 0.011606, R²: -0.0120
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.0000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.39611 | val 0.53833
  Epoch 016 - train 0.38928 | val 0.54393
  Regression -> MSE: 0.000080, MAE: 0.007066, R²: 0.0049
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.43283 | val 0.52011
  Epoch 020 - train 0.42251 | val 0.52142
  Regression -> MSE: 0.000326, MAE: 0.014692, R²: -0.0626
  Directional -> Accuracy: 0.5319, MCC: 0.1036, F1: 0.3125

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.41248 | val 0.48405
  Epoch 020 - train 0.41938 | val 0.48067
  Regression -> MSE: 0.000101, MAE: 0.007396, R²: -0.0249
  Directional -> Accuracy: 0.4545, MCC: -0.0506, F1: 0.4000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.42430 | val 0.58216
  Epoch 020 - train 0.43094 | val 0.57598
  Regression -> MSE: 0.000202, MAE: 0.011511, R²: -0.1782
  Directional -> Accuracy: 0.4082, MCC: -0.0342, F1: 0.5246

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.37567 | val 0.55007
  Epoch 016 - train 0.38095 | val 0.54193
  Regression -> MSE: 0.000231, MAE: 0.012090, R²: -0.0351
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.39956 | val 0.56348
  Epoch 016 - train 0.40866 | val 0.56546
  Regression -> MSE: 0.000096, MAE: 0.007943, R²: -0.0419
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.43554 | val 0.76063
  Epoch 020 - train 0.42711 | val 0.76147
  Regression -> MSE: 0.000166, MAE: 0.010338, R²: -0.0124
  Directional -> Accuracy: 0.4444, MCC: -0.1048, F1: 0.3478

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.39454 | val 0.62254
  Epoch 016 - train 0.40232 | val 0.61892
  Regression -> MSE: 0.000127, MAE: 0.009044, R²: -0.0987
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.41750 | val 0.72830

[I 2026-02-22 22:11:22,537] Trial 58 finished with value: -0.011567787483134131 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.1, 'dropout': 0.0, 'batch_size': 32, 'learning_rate': 2.6697694505534574e-06, 'weight_decay': 3.7998376350814124e-06, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 1.0973191337905386, 'early_stopping_min_delta': 0.0016346891323880436}. Best is trial 31 with value: -0.011425014985750452.

  Epoch 018 - train 0.41634 | val 0.73802
  Regression -> MSE: 0.000239, MAE: 0.012449, R²: -0.0066
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 12
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.42676 | val 0.70514
  Epoch 020 - train 0.41260 | val 0.70539
  Regression -> MSE: 0.000255, MAE: 0.012791, R²: -0.0391
  Directional -> Accuracy: 0.4615, MCC: -0.1225, F1: 0.3000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 88). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.42772 | val 0.43261
  Epoch 020 - train 0.41933 | val 0.44872
  Regression -> MSE: 0.000681, MAE: 0.019398, R²: 0.0144
  Directional -> Accuracy: 0.5957, MCC: 0.2346, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 88). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.48889 | val 1.01545
  Epoch 016 - train 0.47700 | val 1.02389
  Regression -> MSE: 0.000346, MAE: 0.015092, R²: -0.0008
  Directional -> Accuracy: 0.5417, MCC: 0.0000, F1: 0.7027

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.38718 | val 0.68911
  Epoch 016 - train 0.38571 | val 0.63973
  Regression -> MSE: 0.000348, MAE: 0.014456, R²: -0.0078
  Directional -> Accuracy: 0.5395, MCC: 0.0000, F1: 0.7009

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.46005 | val 0.48981
  Epoch 016 - train 0.44770 | val 0.48650
  Regression -> MSE: 0.000204, MAE: 0.010371, R²: -0.0191
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.44850 | val 1.14167
  Epoch 016 - train 0.44769 | val 1.18032
  Regression -> MSE: 0.000580, MAE: 0.018439, R²: -0.0135
  Directional -> Accuracy: 0.4898, MCC: -0.0090, F1: 0.2424

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.46137 | val 0.84127
  Epoch 016 - train 0.44454 | val 0.84784
  Regression -> MSE: 0.000246, MAE: 0.012251, R²: -0.0007
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.5714

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 88). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 88). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.45741 | val 0.75819
  Epoch 016 - train 0.45302 | val 0.87434
  Regression -> MSE: 0.000606, MAE: 0.019280, R²: -0.0365
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.44897 | val 0.86472
  Epoch 016 - train 0.45404 | val 0.88120
  Regression -> MSE: 0.000341, MAE: 0.014824, R²: -0.0090
  Directional -> Accuracy: 0.6190, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 88). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 88). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.46402 | val 0.92380
  Epoch 016 - train 0.45172 | val 0.90454
  Regression -> MSE: 0.000238, MAE: 0.011680, R²: -0.0015
  Directional -> Accuracy: 0.4366, MCC: 0.0000, F1: 0.6078

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.41964 | val 0.97037
  Epoch 016 - train 0.41998 | val 0.99521
  Regression -> MSE: 0.000318, MAE: 0.013628, R²: -0.0407
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.51132 | val 0.82897
  Epoch 016 - train 0.50128 | val 0.83194
  Regression -> MSE: 0.000686, MAE: 0.019798, R²: -0.0251
  Directional -> Accuracy: 0.5085, MCC: 0.0000, F1: 0.6742

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.46058 | val 0.47142
  Epoch 016 - train 0.45595 | val 0.47550
  Regression -> MSE: 0.000154, MAE: 0.009864, R²: -0.0297
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 88). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.40015 | val 0.69441
  Epoch 020 - train 0.39018 | val 0.69731
  Regression -> MSE: 0.000231, MAE: 0.010884, R²: -0.0278
  Directional -> Accuracy: 0.5323, MCC: 0.0674, F1: 0.5915

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.45598 | val 1.53635
  Epoch 016 - train 0.45322 | val 1.59807
  Regression -> MSE: 0.000377, MAE: 0.016510, R²: -0.0033
  Directional -> Accuracy: 0.4717, MCC: 0.0000, F1: 0.6410

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.49043 | val 0.61312
  Epoch 016 - train 0.49025 | val 0.60323
  Regression -> MSE: 0.000105, MAE: 0.007851, R²: 0.0101
  Directional -> Accuracy: 0.5211, MCC: 0.0375, F1: 0.5526

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.43726 | val 1.02027
  Epoch 020 - train 0.42493 | val 1.02315
  Regression -> MSE: 0.000176, MAE: 0.010710, R²: -0.0963
  Directional -> Accuracy: 0.4833, MCC: -0.0504, F1: 0.5507

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.43495 | val 1.21794
  Epoch 016 - train 0.42749 | val 1.15025
  Regression -> MSE: 0.000291, MAE: 0.012964, R²: -0.0833
  Directional -> Accuracy: 0.6104, MCC: 0.0000, F1: 0.7581

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.38063 | val 0.67770
  Epoch 020 - train 0.37810 | val 0.67130
  Regression -> MSE: 0.000185, MAE: 0.010385, R²: -0.2555
  Directional -> Accuracy: 0.5909, MCC: 0.0470, F1: 0.7327

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 88). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.50230 | val 1.39098
  Epoch 016 - train 0.49143 | val 1.33841
  Regression -> MSE: 0.000232, MAE: 0.011268, R²: -0.0243
  Directional -> Accuracy: 0.5395, MCC: 0.0000, F1: 0.7009

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.44845 | val 0.57937
  Epoch 020 - train 0.43470 | val 0.60528
  Regression -> MSE: 0.000181, MAE: 0.010188, R²: -0.2233
  Directional -> Accuracy: 0.4286, MCC: 0.1946, F1: 0.1765

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 88). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 88). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 88). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.42816 | val 0.51257
  Epoch 020 - train 0.42318 | val 0.52243
  Regression -> MSE: 0.000191, MAE: 0.010704, R²: -0.0766
  Directional -> Accuracy: 0.5522, MCC: 0.1084, F1: 0.5161

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.46036 | val 0.65365
  Epoch 016 - train 0.45838 | val 0.65682
  Regression -> MSE: 0.000084, MAE: 0.006940, R²: -0.0002
  Directional -> Accuracy: 0.5763, MCC: 0.0000, F1: 0.7312

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.45504 | val 0.74991
  Epoch 016 - train 0.44141 | val 0.78006
  Regression -> MSE: 0.000219, MAE: 0.011432, R²: -0.0022
  Directional -> Accuracy: 0.4776, MCC: -0.0079, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.39155 | val 0.31791
  Epoch 020 - train 0.37690 | val 0.31164
  Regression -> MSE: 0.000126, MAE: 0.009096, R²: -0.3718
  Directional -> Accuracy: 0.4737, MCC: 0.1044, F1: 0.1667

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.48075 | val 0.22127
  Epoch 016 - train 0.48908 | val 0.25925
  Regression -> MSE: 0.000132, MAE: 0.009480, R²: -0.0537
  Directional -> Accuracy: 0.4167, MCC: 0.0000, F1: 0.5882

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.50047 | val 0.46087
  Epoch 016 - train 0.49537 | val 0.50360
  Regression -> MSE: 0.000246, MAE: 0.013037, R²: -0.0356
  Directional -> Accuracy: 0.5227, MCC: 0.0212, F1: 0.5882

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.45001 | val 0.66244
  Epoch 016 - train 0.43713 | val 0.66474
  Regression -> MSE: 0.000189, MAE: 0.008194, R²: -0.1535
  Directional -> Accuracy: 0.4483, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.46012 | val 0.26172
  Epoch 016 - train 0.44629 | val 0.26332
  Regression -> MSE: 0.000235, MAE: 0.011955, R²: -0.0044
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.46910 | val 0.83706
  Epoch 020 - train 0.46812 | val 0.81908
  Regression -> MSE: 0.000253, MAE: 0.010498, R²: -0.0104
  Directional -> Accuracy: 0.4667, MCC: -0.0672, F1: 0.4783

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.47837 | val 0.79424
  Epoch 016 - train 0.47296 | val 0.83074
  Regression -> MSE: 0.000133, MAE: 0.008291, R²: 0.0012
  Directional -> Accuracy: 0.5111, MCC: 0.0299, F1: 0.5000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.44483 | val 0.71167
  Epoch 020 - train 0.44073 | val 0.70819
  Regression -> MSE: 0.000233, MAE: 0.011708, R²: -0.2392
  Directional -> Accuracy: 0.4706, MCC: -0.0291, F1: 0.2703

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.40002 | val 0.75503
  Epoch 016 - train 0.39273 | val 0.75043
  Regression -> MSE: 0.000259, MAE: 0.010484, R²: -0.0017
  Directional -> Accuracy: 0.5676, MCC: 0.0000, F1: 0.7241

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 88). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.44659 | val 0.35176
  Epoch 016 - train 0.43980 | val 0.35684
  Regression -> MSE: 0.000163, MAE: 0.010142, R²: -0.0040
  Directional -> Accuracy: 0.5385, MCC: 0.1037, F1: 0.1818

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.38253 | val 0.68963
  Epoch 016 - train 0.38942 | val 0.74048
  Regression -> MSE: 0.000189, MAE: 0.010663, R²: -0.0364
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.6364

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.45089 | val 0.42370
  Epoch 016 - train 0.44236 | val 0.41717
  Regression -> MSE: 0.000355, MAE: 0.011998, R²: -0.0178
  Directional -> Accuracy: 0.5735, MCC: 0.0000, F1: 0.7290

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.47815 | val 0.26945
  Epoch 016 - train 0.47455 | val 0.27748
  Regression -> MSE: 0.000112, MAE: 0.008339, R²: -0.0808
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.47592 | val 0.95826
  Epoch 016 - train 0.47032 | val 0.94632
  Regression -> MSE: 0.000220, MAE: 0.011334, R²: -0.0234
  Directional -> Accuracy: 0.4655, MCC: 0.0000, F1: 0.6353

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.46690 | val 1.05389
  Epoch 020 - train 0.43596 | val 1.02735
  Regression -> MSE: 0.000140, MAE: 0.009564, R²: -0.7641
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 88). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 88). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 88). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 88). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.48367 | val 0.31490
  Epoch 020 - train 0.46068 | val 0.32048
  Regression -> MSE: 0.000331, MAE: 0.013215, R²: -0.0085
  Directional -> Accuracy: 0.6250, MCC: -0.1175, F1: 0.0000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 88). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.51543 | val 0.22785
  Epoch 016 - train 0.50561 | val 0.31211
  Regression -> MSE: 0.000245, MAE: 0.011356, R²: -0.0313
  Directional -> Accuracy: 0.4615, MCC: -0.1409, F1: 0.5882

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 88). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 88). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.44062 | val 0.66873
  Epoch 016 - train 0.43999 | val 0.66615
  Regression -> MSE: 0.000083, MAE: 0.007101, R²: -0.0339
  Directional -> Accuracy: 0.4474, MCC: -0.1443, F1: 0.1600

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 88). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 88). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 88). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.53133 | val 1.02967
  Epoch 016 - train 0.52581 | val 1.28668
  Regression -> MSE: 0.000382, MAE: 0.015455, R²: -0.0617
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.44024 | val 0.57144
  Epoch 020 - train 0.44455 | val 0.57263
  Regression -> MSE: 0.000097, MAE: 0.007170, R²: -0.0046
  Directional -> Accuracy: 0.4889, MCC: -0.1118, F1: 0.6230

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.47706 | val 0.75981
  Epoch 020 - train 0.44013 | val 0.76957
  Regression -> MSE: 0.000187, MAE: 0.010000, R²: -0.0328
  Directional -> Accuracy: 0.6098, MCC: 0.4314, F1: 0.6522

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.41436 | val 0.64681
  Epoch 016 - train 0.41309 | val 0.64232
  Regression -> MSE: 0.000223, MAE: 0.011773, R²: -0.0138
  Directional -> Accuracy: 0.5439, MCC: 0.0000, F1: 0.7045

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.43451 | val 0.54384
  Epoch 020 - train 0.42273 | val 0.54940
  Regression -> MSE: 0.000098, MAE: 0.007772, R²: -0.0683
  Directional -> Accuracy: 0.4828, MCC: -0.0290, F1: 0.5161

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.48895 | val 1.03305
  Epoch 016 - train 0.47341 | val 1.05328
  Regression -> MSE: 0.000162, MAE: 0.010062, R²: -0.0077
  Directional -> Accuracy: 0.5818, MCC: 0.1784, F1: 0.5490

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.47199 | val 0.85560
  Epoch 016 - train 0.46343 | val 0.87734
  Regression -> MSE: 0.000115, MAE: 0.008809, R²: -0.0079
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...

[I 2026-02-22 22:11:41,870] Trial 59 finished with value: -0.011638401227001528 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 12, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.1, 'batch_size': 32, 'learning_rate': 3.558843956424001e-05, 'weight_decay': 2.107977983994389e-06, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 1.6763929407087559, 'early_stopping_min_delta': 0.005577975591507063}. Best is trial 31 with value: -0.011425014985750452.

  Epoch 010 - train 0.55986 | val 1.32398
  Epoch 016 - train 0.55845 | val 1.30332
  Regression -> MSE: 0.000260, MAE: 0.012715, R²: -0.1114
  Directional -> Accuracy: 0.5161, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.46267 | val 1.40393
  Epoch 011 - train 0.46243 | val 1.45327
  Regression -> MSE: 0.000276, MAE: 0.013381, R²: -0.1150
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.51407 | val 0.49723
  Epoch 011 - train 0.50377 | val 0.50407
  Regression -> MSE: 0.000718, MAE: 0.019960, R²: -0.0493
  Directional -> Accuracy: 0.4130, MCC: -0.1383, F1: 0.3415

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.49737 | val 0.98384
  Epoch 011 - train 0.49688 | val 0.98713
  Regression -> MSE: 0.000308, MAE: 0.014246, R²: 0.0059
  Directional -> Accuracy: 0.5745, MCC: 0.1522, F1: 0.6970

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.37655 | val 0.50813
  Epoch 011 - train 0.37051 | val 0.52008
  Regression -> MSE: 0.000387, MAE: 0.015187, R²: -0.1081
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.44873 | val 0.45801
  Epoch 011 - train 0.45046 | val 0.45786
  Regression -> MSE: 0.000204, MAE: 0.010084, R²: -0.0035
  Directional -> Accuracy: 0.5098, MCC: -0.0106, F1: 0.6154

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.45971 | val 1.14149
  Epoch 011 - train 0.45572 | val 1.14523
  Regression -> MSE: 0.000555, MAE: 0.018185, R²: 0.0011
  Directional -> Accuracy: 0.4894, MCC: 0.0000, F1: 0.6571

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.50456 | val 0.67486
  Epoch 011 - train 0.48964 | val 0.67644
  Regression -> MSE: 0.000253, MAE: 0.012599, R²: -0.0302
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.50188 | val 0.85057
  Epoch 011 - train 0.50223 | val 0.86202
  Regression -> MSE: 0.000699, MAE: 0.021048, R²: -0.1703
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.49814 | val 0.56394
  Epoch 011 - train 0.50502 | val 0.56361
  Regression -> MSE: 0.000405, MAE: 0.016149, R²: -0.0569
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.47265 | val 0.68538
  Epoch 011 - train 0.45846 | val 0.68616
  Regression -> MSE: 0.000245, MAE: 0.011644, R²: -0.0130
  Directional -> Accuracy: 0.5571, MCC: 0.0402, F1: 0.3111

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.47263 | val 0.94460
  Epoch 011 - train 0.47231 | val 0.96570
  Regression -> MSE: 0.000311, MAE: 0.013867, R²: 0.0004
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.6301

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.46325 | val 0.59720
  Epoch 011 - train 0.46377 | val 0.59693
  Regression -> MSE: 0.000677, MAE: 0.019485, R²: -0.0003
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6588

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.44664 | val 0.51595
  Epoch 011 - train 0.44447 | val 0.52086
  Regression -> MSE: 0.000138, MAE: 0.009192, R²: -0.0021
  Directional -> Accuracy: 0.4186, MCC: -0.1150, F1: 0.5455

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.43430 | val 0.75874
  Epoch 011 - train 0.43316 | val 0.76505
  Regression -> MSE: 0.000227, MAE: 0.010849, R²: -0.0113
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.48974 | val 1.32463
  Epoch 011 - train 0.48837 | val 1.32558
  Regression -> MSE: 0.000367, MAE: 0.015977, R²: -0.0142
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.49970 | val 0.52924
  Epoch 011 - train 0.49113 | val 0.53278
  Regression -> MSE: 0.000111, MAE: 0.007943, R²: -0.0287
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.44572 | val 1.12288
  Epoch 011 - train 0.45405 | val 1.14547
  Regression -> MSE: 0.000160, MAE: 0.010133, R²: -0.0267
  Directional -> Accuracy: 0.4407, MCC: -0.0219, F1: 0.4000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.49351 | val 0.52899
  Epoch 011 - train 0.49018 | val 0.53391
  Regression -> MSE: 0.000275, MAE: 0.012961, R²: -0.0098
  Directional -> Accuracy: 0.5921, MCC: 0.0029, F1: 0.7350

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.44596 | val 0.72949
  Epoch 011 - train 0.44984 | val 0.72716
  Regression -> MSE: 0.000163, MAE: 0.008944, R²: -0.0889
  Directional -> Accuracy: 0.4769, MCC: -0.1873, F1: 0.6222

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.51628 | val 0.95553
  Epoch 011 - train 0.52161 | val 0.95790
  Regression -> MSE: 0.000227, MAE: 0.011051, R²: -0.0047
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.46671 | val 0.68448
  Epoch 011 - train 0.44976 | val 0.68552
  Regression -> MSE: 0.000145, MAE: 0.008492, R²: -0.0142
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.43670 | val 0.59201
  Epoch 011 - train 0.44047 | val 0.59642
  Regression -> MSE: 0.000173, MAE: 0.010257, R²: -0.0475
  Directional -> Accuracy: 0.5455, MCC: 0.0911, F1: 0.5312

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.48447 | val 0.65367
  Epoch 011 - train 0.49208 | val 0.65697
  Regression -> MSE: 0.000085, MAE: 0.007032, R²: 0.0073
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.47206 | val 0.73198
  Epoch 011 - train 0.47115 | val 0.74019
  Regression -> MSE: 0.000214, MAE: 0.011057, R²: -0.0087
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.41224 | val 0.34469
  Epoch 018 - train 0.40815 | val 0.34356
  Regression -> MSE: 0.000094, MAE: 0.008037, R²: -0.0217
  Directional -> Accuracy: 0.5536, MCC: 0.0867, F1: 0.6154

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.50466 | val 0.45002
  Epoch 011 - train 0.50537 | val 0.45342
  Regression -> MSE: 0.000139, MAE: 0.009850, R²: -0.3499
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.54065 | val 0.73751
  Epoch 011 - train 0.55268 | val 0.79745
  Regression -> MSE: 0.000236, MAE: 0.012525, R²: -0.0185
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.43322 | val 0.61680
  Epoch 011 - train 0.44661 | val 0.61996
  Regression -> MSE: 0.000177, MAE: 0.007908, R²: -0.0611
  Directional -> Accuracy: 0.5789, MCC: 0.1053, F1: 0.6923

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.48603 | val 0.33583
  Epoch 011 - train 0.48991 | val 0.33687
  Regression -> MSE: 0.000240, MAE: 0.012027, R²: -0.0144
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.46742 | val 1.01689
  Epoch 011 - train 0.47654 | val 1.02105
  Regression -> MSE: 0.000234, MAE: 0.010136, R²: -0.0166
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.54302 | val 0.64182
  Epoch 011 - train 0.51244 | val 0.64563
  Regression -> MSE: 0.000136, MAE: 0.008178, R²: -0.0046
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.49012 | val 0.71145
  Epoch 011 - train 0.49381 | val 0.71771
  Regression -> MSE: 0.000193, MAE: 0.010444, R²: -0.0235
  Directional -> Accuracy: 0.4800, MCC: -0.0215, F1: 0.4348

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.40475 | val 0.60745
  Epoch 011 - train 0.40230 | val 0.60839
  Regression -> MSE: 0.000267, MAE: 0.010540, R²: -0.0191
  Directional -> Accuracy: 0.5616, MCC: 0.1446, F1: 0.5556

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.47006 | val 0.34339
  Epoch 020 - train 0.45544 | val 0.34202
  Epoch 023 - train 0.45779 | val 0.34627
  Regression -> MSE: 0.000165, MAE: 0.010440, R²: 0.0076
  Directional -> Accuracy: 0.5263, MCC: 0.0538, F1: 0.5714

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.41476 | val 0.53297
  Epoch 011 - train 0.41708 | val 0.53121
  Regression -> MSE: 0.000180, MAE: 0.010291, R²: 0.0008
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.46538 | val 0.43906
  Epoch 011 - train 0.45717 | val 0.44213
  Regression -> MSE: 0.000338, MAE: 0.011948, R²: 0.0122
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.50504 | val 0.23664
  Epoch 011 - train 0.52040 | val 0.23617
  Regression -> MSE: 0.000110, MAE: 0.008406, R²: -0.0428
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.47583 | val 0.80584
  Epoch 014 - train 0.47394 | val 0.82571
  Regression -> MSE: 0.000218, MAE: 0.011221, R²: 0.0022
  Directional -> Accuracy: 0.5439, MCC: 0.0705, F1: 0.3500

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.49309 | val 1.11527
  Epoch 011 - train 0.49413 | val 1.11727
  Regression -> MSE: 0.000097, MAE: 0.007684, R²: -0.2513
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.47492 | val 0.42814
  Epoch 011 - train 0.47354 | val 0.43047
  Regression -> MSE: 0.000373, MAE: 0.016320, R²: -0.2116
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.51859 | val 0.17147
  Epoch 020 - train 0.51002 | val 0.15014
  Epoch 029 - train 0.51445 | val 0.15064
  Regression -> MSE: 0.000266, MAE: 0.011691, R²: -0.0924
  Directional -> Accuracy: 0.4737, MCC: -0.1217, F1: 0.6154

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.42292 | val 0.61456
  Epoch 011 - train 0.42723 | val 0.61626
  Regression -> MSE: 0.000080, MAE: 0.007058, R²: 0.0065
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.49561 | val 0.63408
  Epoch 011 - train 0.50241 | val 0.63600
  Regression -> MSE: 0.000310, MAE: 0.014532, R²: -0.0100
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.46202 | val 0.55212
  Epoch 011 - train 0.47022 | val 0.55455
  Regression -> MSE: 0.000098, MAE: 0.007255, R²: 0.0020
  Directional -> Accuracy: 0.5227, MCC: -0.0045, F1: 0.6182

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.51264 | val 0.72526
  Epoch 011 - train 0.51049 | val 0.72577
  Regression -> MSE: 0.000172, MAE: 0.009734, R²: 0.0016
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.44226 | val 0.62102
  Epoch 011 - train 0.43190 | val 0.62600
  Regression -> MSE: 0.000223, MAE: 0.011789, R²: 0.0011
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.45091 | val 0.64834
  Epoch 011 - train 0.45601 | val 0.65951
  Regression -> MSE: 0.000095, MAE: 0.007772, R²: -0.0244
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.49718 | val 1.13633
  Epoch 011 - train 0.49185 | val 1.16652
  Regression -> MSE: 0.000168, MAE: 0.010299, R²: -0.0278
  Directional -> Accuracy: 0.4815, MCC: 0.0000, F1: 0.0000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.44029 | val 0.68237
  Epoch 011 - train 0.45323 | val 0.68723
  Regression -> MSE: 0.000125, MAE: 0.009034, R²: -0.0795
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...

[I 2026-02-22 22:12:01,110] Trial 60 finished with value: -0.011545143703355198 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.1, 'dropout': 0.1, 'batch_size': 64, 'learning_rate': 1.1915047061972446e-05, 'weight_decay': 6.780137184302327e-07, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 1.5358099600902548, 'early_stopping_min_delta': 0.004177632412970334}. Best is trial 31 with value: -0.011425014985750452.

  Epoch 010 - train 0.49521 | val 0.86880
  Epoch 014 - train 0.49034 | val 0.90409
  Regression -> MSE: 0.000245, MAE: 0.012413, R²: -0.0331
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.43263 | val 1.29757
  Epoch 016 - train 0.42662 | val 1.14567
  Regression -> MSE: 0.000264, MAE: 0.013056, R²: -0.0655
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.42203 | val 0.49593
  Epoch 016 - train 0.42066 | val 0.57660
  Regression -> MSE: 0.000730, MAE: 0.020040, R²: -0.0661
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.45637 | val 0.94545
  Epoch 020 - train 0.43994 | val 0.92491
  Regression -> MSE: 0.000314, MAE: 0.014462, R²: -0.0116
  Directional -> Accuracy: 0.4681, MCC: -0.0934, F1: 0.5614

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.33895 | val 0.91733
  Epoch 016 - train 0.33661 | val 1.10212
  Regression -> MSE: 0.000356, MAE: 0.014695, R²: -0.0192
  Directional -> Accuracy: 0.5200, MCC: -0.0969, F1: 0.6786

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.41896 | val 0.58503
  Epoch 016 - train 0.41050 | val 0.60596
  Regression -> MSE: 0.000203, MAE: 0.010231, R²: 0.0018
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.41435 | val 1.11626
  Epoch 016 - train 0.40243 | val 1.13628
  Regression -> MSE: 0.000557, MAE: 0.018153, R²: -0.0040
  Directional -> Accuracy: 0.4894, MCC: -0.0258, F1: 0.4286

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.42845 | val 0.70114
  Epoch 018 - train 0.42650 | val 0.72921
  Regression -> MSE: 0.000244, MAE: 0.012055, R²: 0.0058
  Directional -> Accuracy: 0.4928, MCC: 0.1456, F1: 0.5882

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.41649 | val 0.57606
  Epoch 020 - train 0.41602 | val 0.54431
  Regression -> MSE: 0.000673, MAE: 0.020154, R²: -0.1268
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.41686 | val 0.54636
  Epoch 020 - train 0.42475 | val 0.55922
  Regression -> MSE: 0.000441, MAE: 0.016669, R²: -0.1489
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.42166 | val 0.70814
  Epoch 016 - train 0.41147 | val 0.71966
  Regression -> MSE: 0.000246, MAE: 0.011626, R²: -0.0209
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.43277 | val 0.72147
  Epoch 016 - train 0.40610 | val 0.80391
  Regression -> MSE: 0.000336, MAE: 0.013740, R²: -0.0803
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.44424 | val 0.68569
  Epoch 016 - train 0.43676 | val 0.68708
  Regression -> MSE: 0.000680, MAE: 0.019437, R²: -0.0034
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.45305 | val 0.46284
  Epoch 020 - train 0.41637 | val 0.47156
  Regression -> MSE: 0.000141, MAE: 0.009034, R²: -0.0178
  Directional -> Accuracy: 0.5349, MCC: 0.0905, F1: 0.5455

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.37433 | val 0.69929
  Epoch 016 - train 0.37467 | val 0.68723
  Regression -> MSE: 0.000227, MAE: 0.010741, R²: -0.0071
  Directional -> Accuracy: 0.4918, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.42995 | val 1.36634
  Epoch 016 - train 0.42530 | val 1.39465
  Regression -> MSE: 0.000361, MAE: 0.016048, R²: 0.0021
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.44866 | val 0.47090
  Epoch 020 - train 0.43302 | val 0.51775
  Regression -> MSE: 0.000107, MAE: 0.008060, R²: 0.0070
  Directional -> Accuracy: 0.5000, MCC: 0.0599, F1: 0.3396

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.40592 | val 1.12753
  Epoch 016 - train 0.41246 | val 1.20711
  Regression -> MSE: 0.000157, MAE: 0.009861, R²: -0.0048
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.43397 | val 0.46837
  Epoch 020 - train 0.41821 | val 0.53825
  Regression -> MSE: 0.000276, MAE: 0.013427, R²: -0.0160
  Directional -> Accuracy: 0.4605, MCC: -0.0306, F1: 0.4533

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.35088 | val 0.69647
  Epoch 020 - train 0.34669 | val 0.67952
  Regression -> MSE: 0.000343, MAE: 0.015214, R²: -1.2900
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.41672 | val 1.07392
  Epoch 017 - train 0.41914 | val 1.05632
  Regression -> MSE: 0.000247, MAE: 0.011154, R²: -0.0899
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.43220 | val 0.64426
  Epoch 020 - train 0.42233 | val 0.66877
  Regression -> MSE: 0.000156, MAE: 0.008963, R²: -0.0875
  Directional -> Accuracy: 0.4375, MCC: 0.2000, F1: 0.1818

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.42033 | val 0.64260
  Epoch 016 - train 0.39675 | val 0.65945
  Regression -> MSE: 0.000170, MAE: 0.010586, R²: -0.0292
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.44806 | val 0.62575
  Epoch 020 - train 0.42852 | val 0.64480
  Regression -> MSE: 0.000090, MAE: 0.007297, R²: -0.0542
  Directional -> Accuracy: 0.4138, MCC: -0.1048, F1: 0.1053

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.44939 | val 0.65890
  Epoch 016 - train 0.43032 | val 0.66591
  Regression -> MSE: 0.000215, MAE: 0.011436, R²: -0.0133
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.39170 | val 0.34782
  Epoch 020 - train 0.36969 | val 0.31325
  Regression -> MSE: 0.000116, MAE: 0.008777, R²: -0.2563
  Directional -> Accuracy: 0.5357, MCC: 0.1728, F1: 0.3810

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.47021 | val 0.31894
  Epoch 020 - train 0.45081 | val 0.31976
  Regression -> MSE: 0.000104, MAE: 0.008744, R²: -0.0118
  Directional -> Accuracy: 0.5000, MCC: 0.0356, F1: 0.5306

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.50873 | val 0.73090
  Epoch 016 - train 0.49004 | val 0.88528
  Regression -> MSE: 0.000253, MAE: 0.013193, R²: -0.0945
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.40811 | val 0.59890
  Epoch 016 - train 0.41769 | val 0.59574
  Regression -> MSE: 0.000179, MAE: 0.008012, R²: -0.0777
  Directional -> Accuracy: 0.4035, MCC: -0.1771, F1: 0.3929

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.43392 | val 0.33716
  Epoch 016 - train 0.43665 | val 0.36267
  Regression -> MSE: 0.000238, MAE: 0.011879, R²: -0.0056
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.44519 | val 1.04057
  Epoch 016 - train 0.41986 | val 1.10876
  Regression -> MSE: 0.000236, MAE: 0.010258, R²: -0.0253
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.45861 | val 0.69466
  Epoch 016 - train 0.45496 | val 0.71183
  Regression -> MSE: 0.000142, MAE: 0.008572, R²: -0.0492
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.42042 | val 0.71389
  Epoch 016 - train 0.40483 | val 0.74916
  Regression -> MSE: 0.000189, MAE: 0.010431, R²: -0.0014
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.37246 | val 0.57694
  Epoch 020 - train 0.35822 | val 0.57988
  Regression -> MSE: 0.000374, MAE: 0.013167, R²: -0.4278
  Directional -> Accuracy: 0.5068, MCC: 0.1076, F1: 0.3571

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.45409 | val 0.35342
  Epoch 020 - train 0.41716 | val 0.35905
  Regression -> MSE: 0.000170, MAE: 0.010370, R²: -0.0209
  Directional -> Accuracy: 0.6053, MCC: 0.2132, F1: 0.6341

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.37609 | val 0.60995
  Epoch 016 - train 0.37189 | val 0.67097
  Regression -> MSE: 0.000181, MAE: 0.010332, R²: -0.0068
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.40489 | val 0.43872
  Epoch 016 - train 0.39823 | val 0.44255
  Regression -> MSE: 0.000348, MAE: 0.012241, R²: -0.0142
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.46659 | val 0.22030
  Epoch 020 - train 0.42503 | val 0.22172
  Regression -> MSE: 0.000111, MAE: 0.008179, R²: -0.0605
  Directional -> Accuracy: 0.6279, MCC: 0.3713, F1: 0.7333

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.42345 | val 0.74261
  Epoch 020 - train 0.40233 | val 0.76956
  Regression -> MSE: 0.000224, MAE: 0.011480, R²: -0.0245
  Directional -> Accuracy: 0.4912, MCC: -0.0185, F1: 0.4727

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.44130 | val 1.10837
  Epoch 016 - train 0.43411 | val 1.16097
  Regression -> MSE: 0.000095, MAE: 0.007602, R²: -0.2246
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.42556 | val 0.30924
  Epoch 016 - train 0.42934 | val 0.31767
  Regression -> MSE: 0.000329, MAE: 0.014959, R²: -0.0697
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.45740 | val 0.22647
  Epoch 016 - train 0.45402 | val 0.23324
  Regression -> MSE: 0.000265, MAE: 0.011545, R²: -0.0850
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.39150 | val 0.67546
  Epoch 016 - train 0.38397 | val 0.68401
  Regression -> MSE: 0.000083, MAE: 0.007048, R²: -0.0313
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.46263 | val 0.66056
  Epoch 016 - train 0.45064 | val 0.66707
  Regression -> MSE: 0.000308, MAE: 0.014482, R²: -0.0045
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.42243 | val 0.53755
  Epoch 016 - train 0.42311 | val 0.55104
  Regression -> MSE: 0.000098, MAE: 0.007283, R²: 0.0056
  Directional -> Accuracy: 0.4545, MCC: -0.0389, F1: 0.3684

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.44780 | val 0.72366
  Epoch 016 - train 0.43893 | val 0.75558
  Regression -> MSE: 0.000171, MAE: 0.009621, R²: 0.0021
  Directional -> Accuracy: 0.5306, MCC: 0.3249, F1: 0.6230

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.40449 | val 0.59870
  Epoch 016 - train 0.39614 | val 0.63156
  Regression -> MSE: 0.000225, MAE: 0.011803, R²: -0.0086
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.40983 | val 0.62229
  Epoch 016 - train 0.40276 | val 0.66957
  Regression -> MSE: 0.000093, MAE: 0.007640, R²: -0.0024
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.44649 | val 0.98905
  Epoch 016 - train 0.43164 | val 1.03640
  Regression -> MSE: 0.000166, MAE: 0.010304, R²: -0.0119
  Directional -> Accuracy: 0.4815, MCC: 0.0000, F1: 0.0000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.41117 | val 0.78714
  Epoch 016 - train 0.39145 | val 0.83297
  Regression -> MSE: 0.000127, MAE: 0.009059, R²: -0.0995
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.44128 | val 0.84359

[I 2026-02-22 22:14:07,209] Trial 61 finished with value: -0.011708819784233968 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.1, 'dropout': 0.0, 'batch_size': 32, 'learning_rate': 2.3046884708455885e-05, 'weight_decay': 1.4706268730928133e-06, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 1.4388103080157202, 'early_stopping_min_delta': 0.006038791277055885}. Best is trial 31 with value: -0.011425014985750452.

  Epoch 020 - train 0.41691 | val 0.96865
  Regression -> MSE: 0.000242, MAE: 0.012319, R²: -0.0194
  Directional -> Accuracy: 0.5902, MCC: 0.1741, F1: 0.5283

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.44735 | val 0.80770
  Epoch 016 - train 0.43766 | val 0.81520
  Regression -> MSE: 0.000248, MAE: 0.012544, R²: -0.0007
  Directional -> Accuracy: 0.5195, MCC: -0.0708, F1: 0.0976

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.43454 | val 0.45336
  Epoch 020 - train 0.41940 | val 0.50891
  Regression -> MSE: 0.000686, MAE: 0.019688, R²: -0.0021
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.45403 | val 0.91332
  Epoch 020 - train 0.44706 | val 0.90855
  Regression -> MSE: 0.000329, MAE: 0.014617, R²: -0.0617
  Directional -> Accuracy: 0.4681, MCC: -0.0417, F1: 0.3590

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.34985 | val 0.74510
  Epoch 016 - train 0.33934 | val 0.84347
  Regression -> MSE: 0.000361, MAE: 0.014779, R²: -0.0335
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.42484 | val 0.51432
  Epoch 016 - train 0.41247 | val 0.52082
  Regression -> MSE: 0.000204, MAE: 0.010199, R²: -0.0024
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.49282 | val 1.12377
  Epoch 016 - train 0.46299 | val 1.13935
  Regression -> MSE: 0.000560, MAE: 0.018217, R²: -0.0082
  Directional -> Accuracy: 0.4894, MCC: 0.0000, F1: 0.6571

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.45617 | val 0.62974
  Epoch 020 - train 0.43550 | val 0.62052
  Regression -> MSE: 0.000255, MAE: 0.012730, R²: -0.0401
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.45379 | val 0.58995
  Epoch 020 - train 0.42657 | val 0.57152
  Regression -> MSE: 0.000609, MAE: 0.019042, R²: -0.0185
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.43530 | val 0.63345
  Epoch 016 - train 0.44539 | val 0.65053
  Regression -> MSE: 0.000388, MAE: 0.015987, R²: -0.0124
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.43260 | val 0.65372
  Epoch 020 - train 0.43223 | val 0.72141
  Regression -> MSE: 0.000241, MAE: 0.012108, R²: 0.0010
  Directional -> Accuracy: 0.5000, MCC: 0.0527, F1: 0.5455

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.42151 | val 1.12338
  Epoch 016 - train 0.41980 | val 1.20022
  Regression -> MSE: 0.000312, MAE: 0.013876, R²: -0.0037
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.6301

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.46954 | val 0.70171
  Epoch 016 - train 0.45124 | val 0.69273
  Regression -> MSE: 0.000690, MAE: 0.019928, R²: -0.0188
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.43353 | val 0.51162
  Epoch 016 - train 0.43971 | val 0.61249
  Regression -> MSE: 0.000138, MAE: 0.009174, R²: -0.0011
  Directional -> Accuracy: 0.5116, MCC: 0.1767, F1: 0.6316

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.38747 | val 0.73776
  Epoch 016 - train 0.39445 | val 0.72879
  Regression -> MSE: 0.000228, MAE: 0.010913, R²: -0.0139
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.46070 | val 1.31343
  Epoch 016 - train 0.44517 | val 1.34142
  Regression -> MSE: 0.000364, MAE: 0.016256, R²: -0.0057
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.45779 | val 0.50535
  Epoch 016 - train 0.45180 | val 0.50552
  Regression -> MSE: 0.000110, MAE: 0.007990, R²: -0.0168
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.41825 | val 0.97740
  Epoch 020 - train 0.40482 | val 1.00375
  Regression -> MSE: 0.000157, MAE: 0.009644, R²: -0.0059
  Directional -> Accuracy: 0.6441, MCC: 0.1703, F1: 0.7789

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.44410 | val 0.55297
  Epoch 016 - train 0.43119 | val 0.57464
  Regression -> MSE: 0.000286, MAE: 0.013664, R²: -0.0508
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.37815 | val 0.74844
  Epoch 020 - train 0.36335 | val 0.73755
  Regression -> MSE: 0.000183, MAE: 0.009758, R²: -0.2238
  Directional -> Accuracy: 0.4462, MCC: -0.0365, F1: 0.3571

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.42244 | val 0.86959
  Epoch 020 - train 0.41437 | val 0.88802
  Regression -> MSE: 0.000316, MAE: 0.013090, R²: -0.3966
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.44003 | val 0.75496
  Epoch 016 - train 0.44117 | val 0.78548
  Regression -> MSE: 0.000150, MAE: 0.008700, R²: -0.0469
  Directional -> Accuracy: 0.6042, MCC: 0.2494, F1: 0.6275

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.41205 | val 0.56055
  Epoch 016 - train 0.41109 | val 0.57022
  Regression -> MSE: 0.000175, MAE: 0.010289, R²: -0.0569
  Directional -> Accuracy: 0.5455, MCC: 0.1476, F1: 0.2500

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.46366 | val 0.65426
  Epoch 016 - train 0.45305 | val 0.65428
  Regression -> MSE: 0.000085, MAE: 0.007019, R²: 0.0058
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.44157 | val 0.71181
  Epoch 016 - train 0.43328 | val 0.76087
  Regression -> MSE: 0.000212, MAE: 0.011194, R²: 0.0007
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.40896 | val 0.39530
  Epoch 016 - train 0.39117 | val 0.37935
  Regression -> MSE: 0.000094, MAE: 0.008160, R²: -0.0176
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.46057 | val 0.32002
  Epoch 020 - train 0.45323 | val 0.33523
  Regression -> MSE: 0.000103, MAE: 0.008669, R²: 0.0058
  Directional -> Accuracy: 0.5435, MCC: 0.1833, F1: 0.6182

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.47594 | val 0.57587
  Epoch 016 - train 0.46969 | val 0.69174
  Regression -> MSE: 0.000233, MAE: 0.012632, R²: -0.0079
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.42144 | val 0.54295
  Epoch 020 - train 0.41272 | val 0.53995
  Regression -> MSE: 0.000213, MAE: 0.009277, R²: -0.2826
  Directional -> Accuracy: 0.4737, MCC: -0.0255, F1: 0.4444

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.45720 | val 0.29745
  Epoch 020 - train 0.44106 | val 0.27108
  Regression -> MSE: 0.000230, MAE: 0.011767, R²: 0.0294
  Directional -> Accuracy: 0.5854, MCC: 0.1890, F1: 0.7119

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.47130 | val 0.94116
  Epoch 016 - train 0.45516 | val 0.95734
  Regression -> MSE: 0.000231, MAE: 0.009874, R²: -0.0021
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.46574 | val 0.65478
  Epoch 016 - train 0.45378 | val 0.67331
  Regression -> MSE: 0.000139, MAE: 0.008340, R²: -0.0308
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.44937 | val 0.68928
  Epoch 016 - train 0.43011 | val 0.70178
  Regression -> MSE: 0.000189, MAE: 0.010354, R²: -0.0019
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.37515 | val 0.63529
  Epoch 016 - train 0.37426 | val 0.62596
  Regression -> MSE: 0.000261, MAE: 0.010484, R²: 0.0022
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.47535 | val 0.40311
  Epoch 016 - train 0.45705 | val 0.48658
  Regression -> MSE: 0.000172, MAE: 0.010389, R²: -0.0300
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.40957 | val 0.71155
  Epoch 016 - train 0.39473 | val 0.74492
  Regression -> MSE: 0.000185, MAE: 0.010510, R²: -0.0260
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.41182 | val 0.43693
  Epoch 020 - train 0.39897 | val 0.44413
  Regression -> MSE: 0.000371, MAE: 0.013480, R²: -0.0822
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.47051 | val 0.24857
  Epoch 016 - train 0.45934 | val 0.27522
  Regression -> MSE: 0.000117, MAE: 0.008314, R²: -0.1132
  Directional -> Accuracy: 0.6047, MCC: 0.2270, F1: 0.5405

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.45031 | val 0.75952
  Epoch 020 - train 0.42557 | val 0.75357
  Regression -> MSE: 0.000224, MAE: 0.011384, R²: -0.0228
  Directional -> Accuracy: 0.4912, MCC: -0.0112, F1: 0.5085

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.43923 | val 1.08502
  Epoch 016 - train 0.43607 | val 1.13052
  Regression -> MSE: 0.000092, MAE: 0.007499, R²: -0.1861
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.46288 | val 0.33487
  Epoch 020 - train 0.42925 | val 0.32309
  Regression -> MSE: 0.000330, MAE: 0.014468, R²: -0.0722
  Directional -> Accuracy: 0.4898, MCC: 0.0792, F1: 0.5098

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.47983 | val 0.19020
  Epoch 016 - train 0.45235 | val 0.19161
  Regression -> MSE: 0.000246, MAE: 0.011539, R²: -0.0085
  Directional -> Accuracy: 0.4474, MCC: -0.1132, F1: 0.0870

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.40122 | val 0.67116
  Epoch 016 - train 0.39712 | val 0.68126
  Regression -> MSE: 0.000086, MAE: 0.007075, R²: -0.0678
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.47097 | val 0.64674
  Epoch 016 - train 0.45596 | val 0.64804
  Regression -> MSE: 0.000308, MAE: 0.014474, R²: -0.0052
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.45179 | val 0.51127
  Epoch 016 - train 0.43957 | val 0.51878
  Regression -> MSE: 0.000098, MAE: 0.007431, R²: -0.0018
  Directional -> Accuracy: 0.4318, MCC: 0.0000, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.48324 | val 0.69924
  Epoch 016 - train 0.47617 | val 0.71695
  Regression -> MSE: 0.000173, MAE: 0.009461, R²: -0.0064
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.40433 | val 0.61639
  Epoch 016 - train 0.40098 | val 0.65744
  Regression -> MSE: 0.000223, MAE: 0.011775, R²: -0.0014
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.44008 | val 0.61682
  Epoch 016 - train 0.43276 | val 0.64285
  Regression -> MSE: 0.000092, MAE: 0.007658, R²: -0.0011
  Directional -> Accuracy: 0.5263, MCC: 0.1409, F1: 0.6494

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.46798 | val 1.01412
  Epoch 016 - train 0.45870 | val 1.07511
  Regression -> MSE: 0.000164, MAE: 0.010293, R²: -0.0042
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.44444 | val 0.75774
  Epoch 016 - train 0.43181 | val 0.74238
  Regression -> MSE: 0.000117, MAE: 0.008923, R²: -0.0136
  Directional -> Accuracy: 0.5357, MCC: 0.1397, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.46470 | val 0.91230

[I 2026-02-22 22:16:11,793] Trial 62 finished with value: -0.011564392952525508 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.1, 'dropout': 0.0, 'batch_size': 32, 'learning_rate': 1.3211776747436029e-05, 'weight_decay': 1.0038559394892462e-06, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 1.4648874022579206, 'early_stopping_min_delta': 0.006516373207198828}. Best is trial 31 with value: -0.011425014985750452.

  Epoch 016 - train 0.46613 | val 0.90680
  Regression -> MSE: 0.000239, MAE: 0.012585, R²: -0.0073
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.45747 | val 1.33479
  Epoch 016 - train 0.44871 | val 1.25290
  Regression -> MSE: 0.000271, MAE: 0.013255, R²: -0.0951
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.49171 | val 0.54264
  Epoch 016 - train 0.47400 | val 0.55555
  Regression -> MSE: 0.000699, MAE: 0.019618, R²: -0.0216
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.46930 | val 1.02599
  Epoch 019 - train 0.48732 | val 1.04212
  Regression -> MSE: 0.000312, MAE: 0.014287, R²: -0.0059
  Directional -> Accuracy: 0.5957, MCC: 0.2559, F1: 0.4865

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.39473 | val 0.41932
  Epoch 020 - train 0.37474 | val 0.41869
  Regression -> MSE: 0.000353, MAE: 0.014612, R²: -0.0096
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.45109 | val 0.51109
  Epoch 016 - train 0.45247 | val 0.50724
  Regression -> MSE: 0.000202, MAE: 0.010116, R²: 0.0061
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.44361 | val 1.25503
  Epoch 016 - train 0.45249 | val 1.27899
  Regression -> MSE: 0.000590, MAE: 0.018739, R²: -0.0633
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.48502 | val 0.72991
  Epoch 016 - train 0.47660 | val 0.71231
  Regression -> MSE: 0.000250, MAE: 0.012437, R²: -0.0196
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.45286 | val 0.79733
  Epoch 016 - train 0.45378 | val 0.92246
  Regression -> MSE: 0.000648, MAE: 0.020204, R²: -0.0850
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.46894 | val 0.58426
  Epoch 020 - train 0.44189 | val 0.59709
  Regression -> MSE: 0.000432, MAE: 0.016551, R²: -0.1257
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.47489 | val 0.82963
  Epoch 016 - train 0.46280 | val 0.85971
  Regression -> MSE: 0.000248, MAE: 0.011662, R²: -0.0273
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.45556 | val 0.74940
  Epoch 020 - train 0.43272 | val 0.76903
  Regression -> MSE: 0.000327, MAE: 0.013690, R²: -0.0532
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.49477 | val 0.64358
  Epoch 016 - train 0.48849 | val 0.65972
  Regression -> MSE: 0.000684, MAE: 0.019854, R²: -0.0105
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.55965 | val 0.50812
  Epoch 020 - train 0.53271 | val 0.57250
  Regression -> MSE: 0.000142, MAE: 0.009100, R²: -0.0242
  Directional -> Accuracy: 0.4884, MCC: -0.0044, F1: 0.5000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.42604 | val 0.72362
  Epoch 016 - train 0.41519 | val 0.72034
  Regression -> MSE: 0.000226, MAE: 0.010720, R²: -0.0041
  Directional -> Accuracy: 0.4426, MCC: -0.1137, F1: 0.3929

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.51416 | val 1.52062
  Epoch 016 - train 0.49588 | val 1.53316
  Regression -> MSE: 0.000363, MAE: 0.016165, R²: -0.0013
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.47641 | val 0.52196
  Epoch 016 - train 0.46376 | val 0.53029
  Regression -> MSE: 0.000109, MAE: 0.008111, R²: -0.0087
  Directional -> Accuracy: 0.4571, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.45037 | val 1.25918
  Epoch 016 - train 0.44259 | val 1.32815
  Regression -> MSE: 0.000159, MAE: 0.010042, R²: -0.0198
  Directional -> Accuracy: 0.5932, MCC: 0.1973, F1: 0.6364

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.46118 | val 0.51788
  Epoch 016 - train 0.45171 | val 0.53754
  Regression -> MSE: 0.000271, MAE: 0.012855, R²: 0.0030
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.39846 | val 0.84919
  Epoch 016 - train 0.38007 | val 0.83281
  Regression -> MSE: 0.000162, MAE: 0.008957, R²: -0.0845
  Directional -> Accuracy: 0.5077, MCC: -0.0029, F1: 0.5676

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.50497 | val 0.98892
  Epoch 016 - train 0.47532 | val 0.98915
  Regression -> MSE: 0.000245, MAE: 0.011200, R²: -0.0829
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.46900 | val 0.80880
  Epoch 016 - train 0.46902 | val 0.84439
  Regression -> MSE: 0.000155, MAE: 0.008877, R²: -0.0786
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.45480 | val 0.55060
  Epoch 020 - train 0.44435 | val 0.54915
  Regression -> MSE: 0.000172, MAE: 0.010419, R²: -0.0397
  Directional -> Accuracy: 0.4697, MCC: -0.0643, F1: 0.5455

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.50515 | val 0.70197
  Epoch 016 - train 0.49728 | val 0.67988
  Regression -> MSE: 0.000089, MAE: 0.007279, R²: -0.0472
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.47403 | val 0.66026
  Epoch 020 - train 0.45960 | val 0.72125
  Regression -> MSE: 0.000219, MAE: 0.011524, R²: -0.0324
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.42101 | val 0.35296
  Epoch 020 - train 0.39849 | val 0.33540
  Regression -> MSE: 0.000103, MAE: 0.008387, R²: -0.1156
  Directional -> Accuracy: 0.5000, MCC: 0.0460, F1: 0.4167

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.50386 | val 0.34940
  Epoch 020 - train 0.49113 | val 0.48118
  Regression -> MSE: 0.000101, MAE: 0.008572, R²: 0.0209
  Directional -> Accuracy: 0.5870, MCC: 0.1252, F1: 0.3871

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.49704 | val 0.52403
  Epoch 016 - train 0.49945 | val 0.53877
  Regression -> MSE: 0.000232, MAE: 0.012530, R²: -0.0042
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.44740 | val 0.60597
  Epoch 020 - train 0.44929 | val 0.60172
  Regression -> MSE: 0.000178, MAE: 0.008079, R²: -0.0724
  Directional -> Accuracy: 0.4737, MCC: -0.0688, F1: 0.5312

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.47058 | val 0.29938
  Epoch 020 - train 0.46421 | val 0.30593
  Regression -> MSE: 0.000233, MAE: 0.011747, R²: 0.0136
  Directional -> Accuracy: 0.5854, MCC: 0.2437, F1: 0.7213

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.45213 | val 1.05843
  Epoch 016 - train 0.45637 | val 1.09791
  Regression -> MSE: 0.000230, MAE: 0.009893, R²: 0.0032
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.48282 | val 0.73713
  Epoch 016 - train 0.48037 | val 0.76237
  Regression -> MSE: 0.000143, MAE: 0.008686, R²: -0.0597
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.49392 | val 0.67473
  Epoch 020 - train 0.47671 | val 0.67358
  Regression -> MSE: 0.000353, MAE: 0.015751, R²: -0.8743
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.43426 | val 0.63078
  Epoch 016 - train 0.42720 | val 0.62976
  Regression -> MSE: 0.000274, MAE: 0.010731, R²: -0.0453
  Directional -> Accuracy: 0.3836, MCC: -0.2725, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.47565 | val 0.36960
  Epoch 020 - train 0.46300 | val 0.39780
  Regression -> MSE: 0.000162, MAE: 0.010309, R²: 0.0279
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.41275 | val 0.61535
  Epoch 016 - train 0.41111 | val 0.63327
  Regression -> MSE: 0.000182, MAE: 0.010384, R²: -0.0140
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.44289 | val 0.43912
  Epoch 016 - train 0.43206 | val 0.44095
  Regression -> MSE: 0.000344, MAE: 0.011749, R²: -0.0032
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.48380 | val 0.28322
  Epoch 016 - train 0.48832 | val 0.39807
  Regression -> MSE: 0.000111, MAE: 0.008339, R²: -0.0527
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.49744 | val 0.86255
  Epoch 019 - train 0.46886 | val 0.90308
  Regression -> MSE: 0.000219, MAE: 0.011237, R²: -0.0037
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.49314 | val 1.37982
  Epoch 016 - train 0.49556 | val 1.52928
  Regression -> MSE: 0.000079, MAE: 0.006936, R²: -0.0227
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.48982 | val 0.31452
  Epoch 020 - train 0.47622 | val 0.32769
  Regression -> MSE: 0.000343, MAE: 0.015425, R²: -0.1161
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.51030 | val 0.17435
  Epoch 020 - train 0.48585 | val 0.17865
  Regression -> MSE: 0.000259, MAE: 0.011904, R²: -0.0633
  Directional -> Accuracy: 0.4737, MCC: -0.0272, F1: 0.2857

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.48806 | val 0.67603
  Epoch 016 - train 0.46857 | val 0.67162
  Regression -> MSE: 0.000088, MAE: 0.007167, R²: -0.0915
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.50169 | val 0.65126
  Epoch 016 - train 0.49209 | val 0.69940
  Regression -> MSE: 0.000308, MAE: 0.014494, R²: -0.0023
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.51387 | val 0.63952
  Epoch 016 - train 0.50315 | val 0.64801
  Regression -> MSE: 0.000104, MAE: 0.007105, R²: -0.0579
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.56352 | val 0.82190
  Epoch 016 - train 0.55799 | val 0.83055
  Regression -> MSE: 0.000179, MAE: 0.010427, R²: -0.0411
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.42535 | val 0.61661
  Epoch 016 - train 0.42525 | val 0.63981
  Regression -> MSE: 0.000228, MAE: 0.011922, R²: -0.0204
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.49961 | val 0.69252
  Epoch 016 - train 0.47528 | val 0.65191
  Regression -> MSE: 0.000093, MAE: 0.007663, R²: -0.0070
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.48317 | val 0.98439
  Epoch 020 - train 0.46581 | val 0.99826
  Regression -> MSE: 0.000167, MAE: 0.010329, R²: -0.0187
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.45599 | val 0.72587
  Epoch 016 - train 0.44210 | val 0.74849
  Regression -> MSE: 0.000128, MAE: 0.009086, R²: -0.1013
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.47752 | val 0.93794

[I 2026-02-22 22:18:13,931] Trial 63 finished with value: -0.01162884459328445 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.1, 'dropout': 0.0, 'batch_size': 32, 'learning_rate': 7.533178279494494e-06, 'weight_decay': 1.763618979610007e-06, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 1.7696650861266139, 'early_stopping_min_delta': 0.006910424179620218}. Best is trial 31 with value: -0.011425014985750452.

  Epoch 016 - train 0.47821 | val 0.95140
  Regression -> MSE: 0.000238, MAE: 0.012315, R²: -0.0028
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.40688 | val 0.76250
  Epoch 016 - train 0.38843 | val 0.78529
  Regression -> MSE: 0.000249, MAE: 0.012635, R²: -0.0072
  Directional -> Accuracy: 0.4416, MCC: -0.0911, F1: 0.5057

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.40369 | val 0.59021
  Epoch 016 - train 0.39534 | val 0.74757
  Regression -> MSE: 0.000690, MAE: 0.019420, R²: -0.0075
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.43846 | val 0.97623
  Epoch 020 - train 0.41618 | val 0.95322
  Regression -> MSE: 0.000336, MAE: 0.014655, R²: -0.0844
  Directional -> Accuracy: 0.4681, MCC: -0.0195, F1: 0.1379

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.32922 | val 1.49189
  Epoch 016 - train 0.31494 | val 1.45907
  Regression -> MSE: 0.000403, MAE: 0.015575, R²: -0.1549
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.39150 | val 0.57833
  Epoch 016 - train 0.39115 | val 0.58787
  Regression -> MSE: 0.000203, MAE: 0.010009, R²: 0.0045
  Directional -> Accuracy: 0.7059, MCC: 0.4110, F1: 0.7458

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.37691 | val 1.15086
  Epoch 016 - train 0.36368 | val 1.16903
  Regression -> MSE: 0.000568, MAE: 0.018302, R²: -0.0226
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.42400 | val 0.77243
  Epoch 017 - train 0.40649 | val 0.79662
  Regression -> MSE: 0.000246, MAE: 0.012232, R²: -0.0012
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.38720 | val 0.78022
  Epoch 020 - train 0.36182 | val 0.72917
  Regression -> MSE: 0.000710, MAE: 0.020537, R²: -0.1887
  Directional -> Accuracy: 0.5909, MCC: 0.1398, F1: 0.4706

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.42069 | val 0.62809
  Epoch 016 - train 0.39195 | val 0.63680
  Regression -> MSE: 0.000394, MAE: 0.015957, R²: -0.0275
  Directional -> Accuracy: 0.5714, MCC: 0.1016, F1: 0.3226

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.40307 | val 0.95173
  Epoch 016 - train 0.39654 | val 0.82591
  Regression -> MSE: 0.000241, MAE: 0.011930, R²: 0.0023
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.37214 | val 1.58337
  Epoch 016 - train 0.37396 | val 1.82663
  Regression -> MSE: 0.000308, MAE: 0.013739, R²: 0.0083
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.6301

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.42968 | val 0.73419
  Epoch 016 - train 0.41391 | val 0.76893
  Regression -> MSE: 0.000675, MAE: 0.019439, R²: 0.0039
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.39869 | val 0.62834
  Epoch 016 - train 0.38772 | val 0.78473
  Regression -> MSE: 0.000139, MAE: 0.009128, R²: -0.0040
  Directional -> Accuracy: 0.4651, MCC: -0.0150, F1: 0.5490

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.36581 | val 0.63920
  Epoch 020 - train 0.35767 | val 0.64674
  Regression -> MSE: 0.000224, MAE: 0.010622, R²: 0.0025
  Directional -> Accuracy: 0.5902, MCC: 0.1848, F1: 0.5614

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.40502 | val 1.67514
  Epoch 016 - train 0.37765 | val 1.97238
  Regression -> MSE: 0.000365, MAE: 0.015947, R²: -0.0065
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.41275 | val 0.57361
  Epoch 016 - train 0.39577 | val 0.57329
  Regression -> MSE: 0.000110, MAE: 0.007947, R²: -0.0205
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.39304 | val 1.45377
  Epoch 016 - train 0.39416 | val 1.71218
  Regression -> MSE: 0.000154, MAE: 0.009538, R²: 0.0149
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.42554 | val 0.81152
  Epoch 016 - train 0.41753 | val 0.81813
  Regression -> MSE: 0.000274, MAE: 0.013126, R²: -0.0071
  Directional -> Accuracy: 0.5395, MCC: 0.1356, F1: 0.5333

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.33644 | val 0.72356
  Epoch 020 - train 0.32118 | val 0.71999
  Regression -> MSE: 0.000178, MAE: 0.009877, R²: -0.1875
  Directional -> Accuracy: 0.4923, MCC: 0.1307, F1: 0.3265

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.39926 | val 0.99419
  Epoch 018 - train 0.37427 | val 1.02945
  Regression -> MSE: 0.000321, MAE: 0.013246, R²: -0.4205
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.40965 | val 0.70470
  Epoch 020 - train 0.37212 | val 0.87598
  Regression -> MSE: 0.000169, MAE: 0.009760, R²: -0.1792
  Directional -> Accuracy: 0.4583, MCC: 0.2335, F1: 0.2353

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.39514 | val 0.70740
  Epoch 016 - train 0.38597 | val 0.76528
  Regression -> MSE: 0.000181, MAE: 0.010344, R²: -0.0959
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.43990 | val 0.68871
  Epoch 016 - train 0.41853 | val 0.72824
  Regression -> MSE: 0.000085, MAE: 0.007065, R²: -0.0007
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.42106 | val 0.89477
  Epoch 016 - train 0.39909 | val 1.12784
  Regression -> MSE: 0.000214, MAE: 0.011073, R²: -0.0120
  Directional -> Accuracy: 0.5303, MCC: 0.0192, F1: 0.1622

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.36282 | val 0.30827
  Epoch 020 - train 0.31833 | val 0.31861
  Regression -> MSE: 0.000110, MAE: 0.008568, R²: -0.1933
  Directional -> Accuracy: 0.5536, MCC: 0.1704, F1: 0.4681

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.44407 | val 0.33068
  Epoch 020 - train 0.41233 | val 0.34465
  Regression -> MSE: 0.000126, MAE: 0.009323, R²: -0.2228
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.44145 | val 0.80944
  Epoch 016 - train 0.43331 | val 1.02632
  Regression -> MSE: 0.000236, MAE: 0.012716, R²: -0.0192
  Directional -> Accuracy: 0.4884, MCC: -0.0197, F1: 0.5217

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.41293 | val 0.63005
  Epoch 019 - train 0.39205 | val 0.66767
  Regression -> MSE: 0.000175, MAE: 0.007779, R²: -0.0516
  Directional -> Accuracy: 0.6140, MCC: 0.1966, F1: 0.6944

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.39415 | val 0.29364
  Epoch 016 - train 0.38517 | val 0.30498
  Regression -> MSE: 0.000236, MAE: 0.011846, R²: 0.0027
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.41410 | val 1.06097
  Epoch 016 - train 0.39599 | val 1.10558
  Regression -> MSE: 0.000235, MAE: 0.010075, R²: -0.0201
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.43067 | val 0.68376
  Epoch 016 - train 0.39085 | val 0.76554
  Regression -> MSE: 0.000137, MAE: 0.008192, R²: -0.0129
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.38244 | val 0.80595
  Epoch 018 - train 0.36238 | val 0.90956
  Regression -> MSE: 0.000187, MAE: 0.010413, R²: 0.0079
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.35682 | val 0.63207
  Epoch 020 - train 0.33037 | val 0.64510
  Regression -> MSE: 0.000318, MAE: 0.012229, R²: -0.2150
  Directional -> Accuracy: 0.5342, MCC: 0.1140, F1: 0.4848

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.39121 | val 0.44999
  Epoch 016 - train 0.39110 | val 0.72260
  Regression -> MSE: 0.000166, MAE: 0.010353, R²: 0.0036
  Directional -> Accuracy: 0.5263, MCC: 0.0619, F1: 0.3571

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.37385 | val 0.71893
  Epoch 016 - train 0.35299 | val 0.75217
  Regression -> MSE: 0.000181, MAE: 0.010343, R²: -0.0051
  Directional -> Accuracy: 0.4091, MCC: -0.2831, F1: 0.5806

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.36817 | val 0.57013
  Epoch 016 - train 0.37057 | val 0.57890
  Regression -> MSE: 0.000347, MAE: 0.012342, R²: -0.0114
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.40892 | val 0.23710
  Epoch 020 - train 0.35759 | val 0.30346
  Regression -> MSE: 0.000120, MAE: 0.008318, R²: -0.1392
  Directional -> Accuracy: 0.5814, MCC: 0.1746, F1: 0.5263

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.39894 | val 1.01874
  Epoch 016 - train 0.38934 | val 1.12440
  Regression -> MSE: 0.000219, MAE: 0.011305, R²: -0.0015
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.40414 | val 1.32145
  Epoch 018 - train 0.37071 | val 1.63340
  Regression -> MSE: 0.000088, MAE: 0.007336, R²: -0.1277
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.38859 | val 0.34259
  Epoch 020 - train 0.35767 | val 0.30200
  Regression -> MSE: 0.000849, MAE: 0.025646, R²: -1.7594
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.41954 | val 0.22304
  Epoch 016 - train 0.39417 | val 0.26939
  Regression -> MSE: 0.000249, MAE: 0.011519, R²: -0.0195
  Directional -> Accuracy: 0.5526, MCC: 0.1054, F1: 0.5641

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.37218 | val 0.76809
  Epoch 016 - train 0.35357 | val 0.83591
  Regression -> MSE: 0.000080, MAE: 0.007056, R²: 0.0077
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.44600 | val 0.58975
  Epoch 020 - train 0.39702 | val 0.61166
  Regression -> MSE: 0.000338, MAE: 0.015045, R²: -0.1019
  Directional -> Accuracy: 0.4894, MCC: 0.0000, F1: 0.0000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.36253 | val 0.55613
  Epoch 020 - train 0.32817 | val 0.53937
  Regression -> MSE: 0.000093, MAE: 0.006765, R²: 0.0537
  Directional -> Accuracy: 0.6818, MCC: 0.3735, F1: 0.7742

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.40855 | val 0.73995
  Epoch 016 - train 0.40116 | val 0.74544
  Regression -> MSE: 0.000171, MAE: 0.009720, R²: 0.0021
  Directional -> Accuracy: 0.4286, MCC: 0.0116, F1: 0.5333

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.37630 | val 1.20081
  Epoch 016 - train 0.36549 | val 1.54365
  Regression -> MSE: 0.000231, MAE: 0.011955, R²: -0.0382
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.37716 | val 1.08532
  Epoch 016 - train 0.37963 | val 1.14600
  Regression -> MSE: 0.000092, MAE: 0.007620, R²: 0.0065
  Directional -> Accuracy: 0.5789, MCC: 0.1803, F1: 0.2941

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.42163 | val 0.95883
  Epoch 019 - train 0.39196 | val 1.01788
  Regression -> MSE: 0.000162, MAE: 0.010102, R²: 0.0107
  Directional -> Accuracy: 0.5926, MCC: 0.1823, F1: 0.6207

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.40567 | val 0.82578
  Epoch 016 - train 0.38141 | val 0.78339
  Regression -> MSE: 0.000116, MAE: 0.008873, R²: 0.0001
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.42773 | val 1.32276

[I 2026-02-22 22:20:18,684] Trial 64 finished with value: -0.011799536048356344 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.0, 'batch_size': 32, 'learning_rate': 0.00016729848394305305, 'weight_decay': 1.3596845027730466e-05, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 1.5579756841217323, 'early_stopping_min_delta': 0.006183775882287343}. Best is trial 31 with value: -0.011425014985750452.

  Epoch 016 - train 0.40725 | val 1.33912
  Regression -> MSE: 0.000236, MAE: 0.012436, R²: 0.0051
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: regression
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.35145 | val 1.13066
  Epoch 019 - train 0.31441 | val 1.27873
  Regression -> MSE: 0.000248, MAE: 0.012554, R²: -0.0299
  Directional -> Accuracy: 0.5132, MCC: 0.1951, F1: 0.6408

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.33636 | val 0.50732
  Epoch 016 - train 0.30719 | val 0.53153
  Regression -> MSE: 0.000701, MAE: 0.019653, R²: -0.0042
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.37695 | val 0.96534
  Epoch 016 - train 0.34535 | val 0.97591
  Regression -> MSE: 0.000321, MAE: 0.014545, R²: -0.0205
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.29793 | val 0.47024
  Epoch 016 - train 0.28810 | val 0.53573
  Regression -> MSE: 0.000359, MAE: 0.014780, R²: -0.0171
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.35493 | val 0.44338
  Epoch 020 - train 0.31570 | val 0.57116
  Regression -> MSE: 0.000198, MAE: 0.009555, R²: 0.0418
  Directional -> Accuracy: 0.7200, MCC: 0.4566, F1: 0.7667

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.32538 | val 0.98187
  Epoch 020 - train 0.26857 | val 1.13401
  Regression -> MSE: 0.000565, MAE: 0.018832, R²: 0.0013
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.6471

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.34774 | val 0.91652
  Epoch 016 - train 0.33137 | val 0.78357
  Regression -> MSE: 0.000247, MAE: 0.011850, R²: 0.0058
  Directional -> Accuracy: 0.5294, MCC: -0.0521, F1: 0.2727

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.31539 | val 0.46185
  Epoch 016 - train 0.28523 | val 0.99691
  Regression -> MSE: 0.000614, MAE: 0.019493, R²: -0.0047
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.32265 | val 0.69322
  Epoch 016 - train 0.31889 | val 0.97012
  Regression -> MSE: 0.000374, MAE: 0.015699, R²: -0.0036
  Directional -> Accuracy: 0.4375, MCC: 0.0000, F1: 0.6087

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.33841 | val 0.98094
  Epoch 016 - train 0.32975 | val 1.01311
  Regression -> MSE: 0.000243, MAE: 0.012055, R²: 0.0069
  Directional -> Accuracy: 0.4203, MCC: 0.0000, F1: 0.5918

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.32652 | val 1.60811
  Epoch 016 - train 0.31477 | val 2.09646
  Regression -> MSE: 0.000314, MAE: 0.013475, R²: -0.0048
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.35478 | val 1.07851
  Epoch 016 - train 0.33511 | val 1.06073
  Regression -> MSE: 0.000679, MAE: 0.019442, R²: 0.0096
  Directional -> Accuracy: 0.6140, MCC: 0.2282, F1: 0.6452

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.32632 | val 1.13328
  Epoch 016 - train 0.32691 | val 1.62889
  Regression -> MSE: 0.000139, MAE: 0.008971, R²: -0.0042
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.31445 | val 0.72697
  Epoch 016 - train 0.27624 | val 0.87368
  Regression -> MSE: 0.000227, MAE: 0.010684, R²: -0.0023
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.33548 | val 1.56000
  Epoch 016 - train 0.32441 | val 1.62059
  Regression -> MSE: 0.000365, MAE: 0.016172, R²: 0.0050
  Directional -> Accuracy: 0.4510, MCC: 0.0000, F1: 0.6216

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.36723 | val 0.55567
  Epoch 016 - train 0.33347 | val 0.57202
  Regression -> MSE: 0.000108, MAE: 0.007926, R²: -0.0041
  Directional -> Accuracy: 0.5362, MCC: 0.0000, F1: 0.6981

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.33822 | val 1.36108
  Epoch 016 - train 0.31916 | val 1.55444
  Regression -> MSE: 0.000157, MAE: 0.009856, R²: 0.0052
  Directional -> Accuracy: 0.6379, MCC: 0.1397, F1: 0.7640

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.35946 | val 1.27016
  Epoch 016 - train 0.33352 | val 1.34515
  Regression -> MSE: 0.000286, MAE: 0.013659, R²: -0.0449
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.31645 | val 0.71069
  Epoch 020 - train 0.28897 | val 0.69989
  Regression -> MSE: 0.000186, MAE: 0.009951, R²: -0.2239
  Directional -> Accuracy: 0.4219, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.33811 | val 0.90107
  Epoch 019 - train 0.30673 | val 0.94882
  Regression -> MSE: 0.000433, MAE: 0.016191, R²: -0.9023
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.31913 | val 0.76394
  Epoch 016 - train 0.27992 | val 0.78016
  Regression -> MSE: 0.000143, MAE: 0.008308, R²: 0.0088
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.35289 | val 0.60871
  Epoch 016 - train 0.33103 | val 0.62912
  Regression -> MSE: 0.000175, MAE: 0.010212, R²: -0.0571
  Directional -> Accuracy: 0.5077, MCC: 0.0699, F1: 0.1111

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.37284 | val 0.77743
  Epoch 017 - train 0.33671 | val 0.80706
  Regression -> MSE: 0.000092, MAE: 0.007436, R²: -0.0569
  Directional -> Accuracy: 0.4912, MCC: 0.0465, F1: 0.3830

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.35735 | val 0.96426
  Epoch 016 - train 0.33100 | val 0.99309
  Regression -> MSE: 0.000211, MAE: 0.011007, R²: -0.0002
  Directional -> Accuracy: 0.5077, MCC: 0.0133, F1: 0.4839

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.30178 | val 0.32095
  Epoch 020 - train 0.24923 | val 0.36274
  Regression -> MSE: 0.000110, MAE: 0.008248, R²: -0.2231
  Directional -> Accuracy: 0.5455, MCC: 0.1365, F1: 0.4681

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.35080 | val 0.41265
  Epoch 016 - train 0.33499 | val 0.58318
  Regression -> MSE: 0.000110, MAE: 0.008976, R²: -0.1091
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.37871 | val 0.39975
  Epoch 020 - train 0.35170 | val 0.71844
  Regression -> MSE: 0.000239, MAE: 0.012792, R²: -0.0095
  Directional -> Accuracy: 0.5714, MCC: 0.0589, F1: 0.7000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.35104 | val 0.63258
  Epoch 016 - train 0.32413 | val 0.66093
  Regression -> MSE: 0.000188, MAE: 0.008121, R²: -0.1091
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.35326 | val 0.29578
  Epoch 020 - train 0.31484 | val 0.33448
  Regression -> MSE: 0.000233, MAE: 0.011978, R²: 0.0384
  Directional -> Accuracy: 0.6250, MCC: 0.2659, F1: 0.7368

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.35851 | val 0.89140
  Epoch 020 - train 0.31879 | val 0.95036
  Regression -> MSE: 0.000235, MAE: 0.010123, R²: 0.0030
  Directional -> Accuracy: 0.5476, MCC: 0.1064, F1: 0.5778

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.34142 | val 0.66612
  Epoch 016 - train 0.31511 | val 0.87049
  Regression -> MSE: 0.000139, MAE: 0.008381, R²: -0.0074
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.7077

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.33834 | val 0.67927
  Epoch 019 - train 0.30800 | val 0.71473
  Regression -> MSE: 0.000182, MAE: 0.010224, R²: 0.0053
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.29461 | val 0.59679
  Epoch 016 - train 0.29160 | val 0.65154
  Regression -> MSE: 0.000286, MAE: 0.011051, R²: -0.0758
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.31124 | val 0.76636
  Epoch 016 - train 0.28696 | val 0.75914
  Regression -> MSE: 0.000191, MAE: 0.010699, R²: -0.0407
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.30959 | val 0.46670
  Epoch 019 - train 0.28810 | val 0.48914
  Regression -> MSE: 0.000348, MAE: 0.012669, R²: -0.0022
  Directional -> Accuracy: 0.4242, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.31745 | val 0.22730
  Epoch 020 - train 0.27901 | val 0.32333
  Regression -> MSE: 0.000145, MAE: 0.008722, R²: -0.3759
  Directional -> Accuracy: 0.6190, MCC: 0.2864, F1: 0.5294

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.34313 | val 0.94424
  Epoch 016 - train 0.32745 | val 1.22000
  Regression -> MSE: 0.000223, MAE: 0.011385, R²: -0.0144
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.6341

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.33449 | val 1.31711
  Epoch 016 - train 0.30040 | val 1.64026
  Regression -> MSE: 0.000077, MAE: 0.006807, R²: -0.0377
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.34494 | val 0.25318
  Epoch 020 - train 0.31206 | val 0.21548
  Regression -> MSE: 0.000506, MAE: 0.019314, R²: -0.6241
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.30884 | val 0.89676
  Epoch 018 - train 0.26276 | val 1.02046
  Regression -> MSE: 0.000078, MAE: 0.006967, R²: -0.0056
  Directional -> Accuracy: 0.5135, MCC: 0.0684, F1: 0.6400

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.34790 | val 0.69109
  Epoch 019 - train 0.29905 | val 0.74135
  Regression -> MSE: 0.000302, MAE: 0.014377, R²: -0.0045
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.32279 | val 0.60750
  Epoch 016 - train 0.30446 | val 0.61517
  Regression -> MSE: 0.000105, MAE: 0.007197, R²: -0.0322
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.32825 | val 0.70303
  Epoch 020 - train 0.28236 | val 0.73856
  Regression -> MSE: 0.000373, MAE: 0.016380, R²: -1.1278
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.32918 | val 0.81659
  Epoch 016 - train 0.31042 | val 1.16998
  Regression -> MSE: 0.000227, MAE: 0.011748, R²: -0.0053
  Directional -> Accuracy: 0.6909, MCC: 0.3748, F1: 0.7213

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.33449 | val 1.21227
  Epoch 016 - train 0.30354 | val 1.30432
  Regression -> MSE: 0.000094, MAE: 0.007804, R²: -0.0060
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.38542 | val 0.98867
  Epoch 019 - train 0.34157 | val 0.94115
  Regression -> MSE: 0.000166, MAE: 0.010273, R²: 0.0021
  Directional -> Accuracy: 0.5660, MCC: 0.1322, F1: 0.6230

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.33931 | val 0.85220
  Epoch 017 - train 0.31176 | val 0.87795
  Regression -> MSE: 0.000120, MAE: 0.009057, R²: -0.0222
  Directional -> Accuracy: 0.5636, MCC: 0.2052, F1: 0.7073

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.36508 | val 1.65916

[I 2026-02-22 22:22:48,874] Trial 65 finished with value: -0.011834891451763066 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.0, 'dropout': 0.30000000000000004, 'batch_size': 32, 'learning_rate': 0.0002930414701667558, 'weight_decay': 4.814930569264357e-07, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 1.3914686297015812, 'early_stopping_min_delta': 0.007443564471538585}. Best is trial 31 with value: -0.011425014985750452.

  Epoch 016 - train 0.33984 | val 2.03169
  Regression -> MSE: 0.000241, MAE: 0.012478, R²: -0.0010
  Directional -> Accuracy: 0.4833, MCC: 0.0000, F1: 0.6517

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 12
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.35127 | val 0.73975
  Epoch 020 - train 0.34444 | val 0.76484
  Epoch 021 - train 0.32774 | val 0.75615
  Regression -> MSE: 0.000251, MAE: 0.012734, R²: -0.0225
  Directional -> Accuracy: 0.4487, MCC: 0.0000, F1: 0.6195

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 88). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.37372 | val 0.49617
  Epoch 020 - train 0.33919 | val 0.50197
  Epoch 021 - train 0.35488 | val 0.49733
  Regression -> MSE: 0.000694, MAE: 0.019635, R²: -0.0034
  Directional -> Accuracy: 0.5532, MCC: 0.0000, F1: 0.7123

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 88). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.40396 | val 0.79588
  Epoch 020 - train 0.38834 | val 0.78132
  Epoch 030 - train 0.35898 | val 0.79520
  Regression -> MSE: 0.000367, MAE: 0.015544, R²: -0.0633
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.5200

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.31523 | val 0.68137
  Epoch 020 - train 0.29820 | val 0.90479
  Epoch 021 - train 0.30231 | val 0.98656
  Regression -> MSE: 0.000379, MAE: 0.014974, R²: -0.0983
  Directional -> Accuracy: 0.4605, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.36047 | val 0.41684
  Epoch 020 - train 0.33933 | val 0.39535
  Epoch 030 - train 0.33406 | val 0.43932
  Regression -> MSE: 0.000180, MAE: 0.009230, R²: 0.1013
  Directional -> Accuracy: 0.6154, MCC: 0.2315, F1: 0.6296

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.37179 | val 1.49513
  Epoch 020 - train 0.35392 | val 2.10114
  Epoch 021 - train 0.35773 | val 2.10552
  Regression -> MSE: 0.000583, MAE: 0.018473, R²: -0.0193
  Directional -> Accuracy: 0.4898, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.39261 | val 0.68828
  Epoch 020 - train 0.38360 | val 0.83856
  Epoch 023 - train 0.36895 | val 0.90361
  Regression -> MSE: 0.000250, MAE: 0.012508, R²: -0.0183
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.5714

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 88). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 88). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.34568 | val 0.78578
  Epoch 020 - train 0.35129 | val 1.05573
  Epoch 021 - train 0.34143 | val 1.09090
  Regression -> MSE: 0.000606, MAE: 0.019260, R²: -0.0370
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.38549 | val 0.71560
  Epoch 020 - train 0.34130 | val 0.71661
  Epoch 028 - train 0.33569 | val 0.71596
  Regression -> MSE: 0.000333, MAE: 0.014836, R²: 0.0161
  Directional -> Accuracy: 0.4524, MCC: 0.0512, F1: 0.5306

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 88). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 88). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.37630 | val 0.99679
  Epoch 020 - train 0.36080 | val 1.49055
  Epoch 021 - train 0.34883 | val 1.49946
  Regression -> MSE: 0.000238, MAE: 0.011699, R²: -0.0005
  Directional -> Accuracy: 0.4366, MCC: 0.0000, F1: 0.6078

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.34427 | val 1.03362
  Epoch 020 - train 0.32905 | val 1.05971
  Epoch 021 - train 0.32428 | val 1.08094
  Regression -> MSE: 0.000306, MAE: 0.013589, R²: 0.0002
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.6400

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.41881 | val 0.86982
  Epoch 020 - train 0.39971 | val 1.02886
  Epoch 023 - train 0.40156 | val 0.92793
  Regression -> MSE: 0.000669, MAE: 0.019549, R²: 0.0011
  Directional -> Accuracy: 0.5085, MCC: 0.0000, F1: 0.6742

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.37624 | val 0.65259
  Epoch 020 - train 0.35149 | val 0.62739
  Epoch 021 - train 0.35209 | val 0.62414
  Regression -> MSE: 0.000150, MAE: 0.009499, R²: -0.0009
  Directional -> Accuracy: 0.5682, MCC: 0.1910, F1: 0.6275

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 88). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.33322 | val 0.62460
  Epoch 020 - train 0.31888 | val 0.61145
  Epoch 030 - train 0.31156 | val 0.61118
  Regression -> MSE: 0.000236, MAE: 0.011321, R²: -0.0504
  Directional -> Accuracy: 0.5645, MCC: 0.1754, F1: 0.6747

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.35948 | val 1.18194
  Epoch 020 - train 0.33945 | val 1.35776
  Epoch 021 - train 0.33561 | val 1.38253
  Regression -> MSE: 0.000381, MAE: 0.016357, R²: -0.0139
  Directional -> Accuracy: 0.5283, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.38503 | val 0.60721
  Epoch 020 - train 0.36534 | val 0.67526
  Epoch 021 - train 0.36142 | val 0.64340
  Regression -> MSE: 0.000106, MAE: 0.007848, R²: 0.0038
  Directional -> Accuracy: 0.5915, MCC: 0.2622, F1: 0.7238

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.37620 | val 0.97372
  Epoch 020 - train 0.34356 | val 0.97487
  Epoch 021 - train 0.35179 | val 0.97827
  Regression -> MSE: 0.000164, MAE: 0.010261, R²: -0.0226
  Directional -> Accuracy: 0.4167, MCC: -0.1557, F1: 0.4615

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.36962 | val 0.99964
  Epoch 020 - train 0.35564 | val 1.03432
  Epoch 021 - train 0.36078 | val 0.98539
  Regression -> MSE: 0.000283, MAE: 0.013585, R²: -0.0538
  Directional -> Accuracy: 0.3896, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.31581 | val 0.68099
  Epoch 020 - train 0.31114 | val 0.68146
  Epoch 021 - train 0.29598 | val 0.67995
  Regression -> MSE: 0.000158, MAE: 0.008805, R²: -0.0734
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 88). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.37393 | val 0.74728
  Epoch 020 - train 0.36022 | val 0.76037
  Epoch 023 - train 0.33984 | val 0.76256
  Regression -> MSE: 0.000265, MAE: 0.011791, R²: -0.1697
  Directional -> Accuracy: 0.4605, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.38056 | val 0.61699
  Epoch 020 - train 0.35817 | val 0.81048
  Epoch 026 - train 0.36152 | val 0.88926
  Regression -> MSE: 0.000154, MAE: 0.009061, R²: -0.0352
  Directional -> Accuracy: 0.4694, MCC: -0.1695, F1: 0.5938

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 88). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 88). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 88). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.36647 | val 0.68048
  Epoch 020 - train 0.34761 | val 0.64395
  Epoch 021 - train 0.34695 | val 0.65606
  Regression -> MSE: 0.000178, MAE: 0.010641, R²: -0.0023
  Directional -> Accuracy: 0.5075, MCC: 0.0000, F1: 0.6733

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.40627 | val 0.88399
  Epoch 020 - train 0.36581 | val 1.20863
  Epoch 024 - train 0.37091 | val 1.33650
  Regression -> MSE: 0.000084, MAE: 0.006974, R²: -0.0037
  Directional -> Accuracy: 0.5932, MCC: 0.1861, F1: 0.6250

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.36274 | val 0.86278
  Epoch 020 - train 0.34160 | val 0.66456
  Epoch 021 - train 0.33206 | val 0.67138
  Regression -> MSE: 0.000226, MAE: 0.011282, R²: -0.0319
  Directional -> Accuracy: 0.5224, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.32306 | val 0.30351
  Epoch 020 - train 0.28630 | val 0.35518
  Epoch 025 - train 0.28059 | val 0.38096
  Regression -> MSE: 0.000097, MAE: 0.008098, R²: -0.0615
  Directional -> Accuracy: 0.5614, MCC: 0.1505, F1: 0.5455

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.37556 | val 0.26003
  Epoch 020 - train 0.37829 | val 0.34671
  Epoch 021 - train 0.36650 | val 0.35537
  Regression -> MSE: 0.000142, MAE: 0.009769, R²: -0.1274
  Directional -> Accuracy: 0.4167, MCC: 0.0000, F1: 0.5882

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.39821 | val 0.36771
  Epoch 020 - train 0.37674 | val 0.39685
  Epoch 021 - train 0.39616 | val 0.38612
  Regression -> MSE: 0.000246, MAE: 0.013031, R²: -0.0331
  Directional -> Accuracy: 0.4773, MCC: 0.0133, F1: 0.4390

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.37730 | val 0.53790
  Epoch 020 - train 0.37238 | val 0.61619
  Epoch 025 - train 0.35027 | val 0.64842
  Regression -> MSE: 0.000202, MAE: 0.008604, R²: -0.2307
  Directional -> Accuracy: 0.4483, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.38565 | val 0.27319
  Epoch 020 - train 0.37220 | val 0.31304
  Epoch 021 - train 0.37054 | val 0.31709
  Regression -> MSE: 0.000235, MAE: 0.011970, R²: -0.0050
  Directional -> Accuracy: 0.5814, MCC: 0.1489, F1: 0.6786

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.40684 | val 1.12625
  Epoch 020 - train 0.37692 | val 1.45225
  Epoch 021 - train 0.38009 | val 1.46357
  Regression -> MSE: 0.000250, MAE: 0.010456, R²: 0.0015
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.41372 | val 0.92420
  Epoch 020 - train 0.37397 | val 1.22489
  Epoch 021 - train 0.36727 | val 1.26500
  Regression -> MSE: 0.000133, MAE: 0.008207, R²: -0.0006
  Directional -> Accuracy: 0.5333, MCC: 0.0000, F1: 0.6957

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.37609 | val 0.63641
  Epoch 020 - train 0.34099 | val 0.62478
  Epoch 024 - train 0.35021 | val 0.61987
  Regression -> MSE: 0.000189, MAE: 0.010437, R²: -0.0048
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.33370 | val 0.55225
  Epoch 020 - train 0.32636 | val 0.54895
  Epoch 030 - train 0.30959 | val 0.53958
  Regression -> MSE: 0.000375, MAE: 0.013240, R²: -0.4513
  Directional -> Accuracy: 0.5676, MCC: 0.2241, F1: 0.4839

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 88). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.34522 | val 0.35122
  Epoch 020 - train 0.32029 | val 0.37272
  Epoch 028 - train 0.31104 | val 0.38570
  Regression -> MSE: 0.000157, MAE: 0.010080, R²: 0.0354
  Directional -> Accuracy: 0.5128, MCC: 0.0324, F1: 0.5581

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.32890 | val 0.55517
  Epoch 020 - train 0.29937 | val 0.60590
  Epoch 021 - train 0.32847 | val 0.62484
  Regression -> MSE: 0.000188, MAE: 0.010682, R²: -0.0304
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.6364

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.34112 | val 0.78384
  Epoch 020 - train 0.31038 | val 0.84268
  Epoch 023 - train 0.32249 | val 0.82273
  Regression -> MSE: 0.000354, MAE: 0.012807, R²: -0.0137
  Directional -> Accuracy: 0.4265, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.39341 | val 0.25623
  Epoch 020 - train 0.34557 | val 0.32597
  Epoch 030 - train 0.30850 | val 0.43899
  Regression -> MSE: 0.000162, MAE: 0.009016, R²: -0.5622
  Directional -> Accuracy: 0.6364, MCC: 0.3062, F1: 0.5294

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.38110 | val 1.08774
  Epoch 020 - train 0.36442 | val 1.26310
  Epoch 023 - train 0.35585 | val 1.33113
  Regression -> MSE: 0.000218, MAE: 0.011324, R²: -0.0141
  Directional -> Accuracy: 0.4483, MCC: -0.1037, F1: 0.4286

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.35635 | val 1.04323
  Epoch 020 - train 0.34275 | val 1.24195
  Epoch 021 - train 0.33589 | val 1.27476
  Regression -> MSE: 0.000098, MAE: 0.007766, R²: -0.2335
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 88). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 88). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 88). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 88). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.36901 | val 0.34170
  Epoch 020 - train 0.34365 | val 0.31897
  Epoch 030 - train 0.32980 | val 0.32262
  Regression -> MSE: 0.000370, MAE: 0.015261, R²: -0.1282
  Directional -> Accuracy: 0.4750, MCC: -0.1353, F1: 0.2759

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 88). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.39708 | val 0.27433
  Epoch 020 - train 0.36277 | val 0.47387
  Epoch 021 - train 0.37498 | val 0.46539
  Regression -> MSE: 0.000240, MAE: 0.011306, R²: -0.0082
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.0000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 88). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 88). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.35116 | val 1.06550
  Epoch 020 - train 0.32948 | val 1.14987
  Epoch 021 - train 0.32474 | val 1.20875
  Regression -> MSE: 0.000085, MAE: 0.007071, R²: -0.0595
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 88). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 88). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 88). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.41001 | val 0.53866
  Epoch 020 - train 0.39461 | val 0.55209
  Epoch 024 - train 0.38429 | val 0.53348
  Regression -> MSE: 0.000358, MAE: 0.015284, R²: 0.0047
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.37131 | val 0.60151
  Epoch 020 - train 0.34204 | val 0.73867
  Epoch 021 - train 0.35905 | val 0.73242
  Regression -> MSE: 0.000098, MAE: 0.007144, R²: -0.0103
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.40151 | val 1.10995
  Epoch 020 - train 0.34837 | val 1.37699
  Epoch 021 - train 0.35080 | val 1.37958
  Regression -> MSE: 0.000181, MAE: 0.010265, R²: -0.0035
  Directional -> Accuracy: 0.3659, MCC: 0.0000, F1: 0.5357

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.35091 | val 1.30694
  Epoch 020 - train 0.33874 | val 1.88127
  Epoch 021 - train 0.33330 | val 1.95745
  Regression -> MSE: 0.000220, MAE: 0.011628, R²: -0.0016
  Directional -> Accuracy: 0.5439, MCC: 0.0000, F1: 0.7045

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.36376 | val 1.11614
  Epoch 020 - train 0.33502 | val 1.31835
  Epoch 021 - train 0.35445 | val 1.34666
  Regression -> MSE: 0.000094, MAE: 0.007769, R²: -0.0251

[I 2026-02-22 22:24:55,470] Trial 66 finished with value: -0.011706117853703504 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 12, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.1, 'dropout': 0.1, 'batch_size': 16, 'learning_rate': 8.298212172260744e-05, 'weight_decay': 4.173753178641147e-06, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 1.2029621419144956, 'early_stopping_min_delta': 0.004589788364974896}. Best is trial 31 with value: -0.011425014985750452.

  Epoch 020 - train 0.37469 | val 1.29116
  Epoch 021 - train 0.36580 | val 1.38766
  Regression -> MSE: 0.000238, MAE: 0.012230, R²: -0.0175
  Directional -> Accuracy: 0.5161, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.42866 | val 0.75903
  Epoch 016 - train 0.41701 | val 0.77802
  Regression -> MSE: 0.000252, MAE: 0.012737, R²: -0.0179
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.44836 | val 0.47486
  Epoch 020 - train 0.43094 | val 0.43797
  Regression -> MSE: 0.000694, MAE: 0.019296, R²: -0.0136
  Directional -> Accuracy: 0.6304, MCC: 0.2904, F1: 0.6222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.45920 | val 0.95190
  Epoch 020 - train 0.45998 | val 0.94258
  Regression -> MSE: 0.000308, MAE: 0.014341, R²: 0.0087
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.35410 | val 0.41647
  Epoch 016 - train 0.34161 | val 0.45976
  Regression -> MSE: 0.000367, MAE: 0.014861, R²: -0.0507
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.43368 | val 0.47910
  Epoch 020 - train 0.43029 | val 0.45262
  Regression -> MSE: 0.000202, MAE: 0.010029, R²: 0.0101
  Directional -> Accuracy: 0.5686, MCC: 0.1343, F1: 0.5926

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.41486 | val 1.12296
  Epoch 016 - train 0.40427 | val 1.12199
  Regression -> MSE: 0.000561, MAE: 0.018183, R²: -0.0110
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.44094 | val 0.64952
  Epoch 020 - train 0.43833 | val 0.64936
  Regression -> MSE: 0.000256, MAE: 0.011954, R²: -0.0434
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.40548 | val 0.70482
  Epoch 016 - train 0.40502 | val 0.70480
  Regression -> MSE: 0.000642, MAE: 0.020102, R²: -0.0747
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.43485 | val 0.61127
  Epoch 016 - train 0.42418 | val 0.61988
  Regression -> MSE: 0.000385, MAE: 0.016070, R²: -0.0049
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.44889 | val 0.65626
  Epoch 020 - train 0.44519 | val 0.75774
  Regression -> MSE: 0.000240, MAE: 0.011873, R²: 0.0052
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.40500 | val 0.83620
  Epoch 016 - train 0.39440 | val 0.91381
  Regression -> MSE: 0.000312, MAE: 0.013794, R²: -0.0019
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.6301

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.44953 | val 0.60413
  Epoch 016 - train 0.44316 | val 0.66879
  Regression -> MSE: 0.000677, MAE: 0.019468, R²: 0.0006
  Directional -> Accuracy: 0.6207, MCC: 0.2894, F1: 0.7027

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.42966 | val 0.48810
  Epoch 016 - train 0.41859 | val 0.49894
  Regression -> MSE: 0.000138, MAE: 0.009150, R²: -0.0019
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.39138 | val 0.70639
  Epoch 020 - train 0.37501 | val 0.69981
  Regression -> MSE: 0.000224, MAE: 0.010537, R²: 0.0043
  Directional -> Accuracy: 0.5082, MCC: 0.0089, F1: 0.6154

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.43409 | val 1.30584
  Epoch 016 - train 0.42110 | val 1.33202
  Regression -> MSE: 0.000370, MAE: 0.015933, R²: -0.0221
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.46112 | val 0.49104
  Epoch 016 - train 0.46044 | val 0.49900
  Regression -> MSE: 0.000109, MAE: 0.007944, R²: -0.0073
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.39982 | val 0.98345
  Epoch 020 - train 0.39861 | val 0.97066
  Regression -> MSE: 0.000161, MAE: 0.010151, R²: -0.0319
  Directional -> Accuracy: 0.4576, MCC: 0.1745, F1: 0.2727

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.44616 | val 0.47019
  Epoch 016 - train 0.44569 | val 0.51640
  Regression -> MSE: 0.000273, MAE: 0.013105, R²: -0.0044
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.35612 | val 0.72401
  Epoch 020 - train 0.35072 | val 0.71305
  Regression -> MSE: 0.000166, MAE: 0.009128, R²: -0.1101
  Directional -> Accuracy: 0.5077, MCC: 0.0077, F1: 0.5556

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.42901 | val 0.85093
  Epoch 020 - train 0.41078 | val 0.85895
  Regression -> MSE: 0.000293, MAE: 0.012403, R²: -0.2939
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.45575 | val 0.70120
  Epoch 020 - train 0.43635 | val 0.68557
  Regression -> MSE: 0.000147, MAE: 0.008780, R²: -0.0259
  Directional -> Accuracy: 0.5417, MCC: 0.1556, F1: 0.5417

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.41657 | val 0.56456
  Epoch 016 - train 0.41006 | val 0.58286
  Regression -> MSE: 0.000166, MAE: 0.010340, R²: -0.0070
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.45426 | val 0.64073
  Epoch 016 - train 0.44913 | val 0.64851
  Regression -> MSE: 0.000085, MAE: 0.007031, R²: -0.0001
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.45543 | val 0.65310
  Epoch 016 - train 0.46314 | val 0.67228
  Regression -> MSE: 0.000217, MAE: 0.011041, R²: -0.0243
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.40661 | val 0.36673
  Epoch 020 - train 0.39736 | val 0.33580
  Regression -> MSE: 0.000097, MAE: 0.007943, R²: -0.0565
  Directional -> Accuracy: 0.5714, MCC: 0.2385, F1: 0.4545

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.44184 | val 0.34464
  Epoch 016 - train 0.43795 | val 0.34286
  Regression -> MSE: 0.000110, MAE: 0.009040, R²: -0.0699
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.46006 | val 0.43862
  Epoch 016 - train 0.45732 | val 0.45020
  Regression -> MSE: 0.000232, MAE: 0.012572, R²: -0.0027
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.44102 | val 0.58303
  Epoch 016 - train 0.43082 | val 0.58751
  Regression -> MSE: 0.000186, MAE: 0.008088, R²: -0.1200
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.43264 | val 0.31362
  Epoch 016 - train 0.44900 | val 0.31775
  Regression -> MSE: 0.000237, MAE: 0.011878, R²: -0.0030
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.48808 | val 0.93575
  Epoch 016 - train 0.46638 | val 0.93643
  Regression -> MSE: 0.000231, MAE: 0.009866, R²: -0.0016
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.46230 | val 0.62725
  Epoch 016 - train 0.45723 | val 0.63234
  Regression -> MSE: 0.000135, MAE: 0.008190, R²: 0.0007
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.43441 | val 0.67326
  Epoch 020 - train 0.41955 | val 0.66114
  Regression -> MSE: 0.000191, MAE: 0.010466, R²: -0.0143
  Directional -> Accuracy: 0.5000, MCC: -0.0602, F1: 0.6269

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.37442 | val 0.59330
  Epoch 020 - train 0.36760 | val 0.61612
  Regression -> MSE: 0.000269, MAE: 0.010761, R²: -0.0281
  Directional -> Accuracy: 0.5479, MCC: 0.1291, F1: 0.5217

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.43198 | val 0.35920
  Epoch 016 - train 0.42766 | val 0.35826
  Regression -> MSE: 0.000167, MAE: 0.010372, R²: -0.0006
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.37646 | val 0.53215
  Epoch 016 - train 0.37643 | val 0.54642
  Regression -> MSE: 0.000181, MAE: 0.010345, R²: -0.0043
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.41096 | val 0.41831
  Epoch 020 - train 0.40127 | val 0.42767
  Regression -> MSE: 0.000335, MAE: 0.011976, R²: 0.0234
  Directional -> Accuracy: 0.4627, MCC: 0.1532, F1: 0.1000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.46219 | val 0.23111
  Epoch 020 - train 0.44516 | val 0.22519
  Regression -> MSE: 0.000114, MAE: 0.008215, R²: -0.0808
  Directional -> Accuracy: 0.5581, MCC: 0.1182, F1: 0.6415

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.44896 | val 0.77618
  Epoch 020 - train 0.42307 | val 0.83266
  Regression -> MSE: 0.000220, MAE: 0.011314, R²: -0.0054
  Directional -> Accuracy: 0.5088, MCC: 0.0398, F1: 0.5758

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.43255 | val 1.07762
  Epoch 016 - train 0.42791 | val 1.07649
  Regression -> MSE: 0.000090, MAE: 0.007442, R²: -0.1648
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.43979 | val 0.28836
  Epoch 016 - train 0.42399 | val 0.29027
  Regression -> MSE: 0.000313, MAE: 0.014132, R²: -0.0175
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.44150 | val 0.21941
  Epoch 020 - train 0.42873 | val 0.21390
  Regression -> MSE: 0.000260, MAE: 0.011466, R²: -0.0656
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.40130 | val 0.58674
  Epoch 020 - train 0.38896 | val 0.57778
  Regression -> MSE: 0.000080, MAE: 0.007017, R²: 0.0113
  Directional -> Accuracy: 0.5333, MCC: 0.2014, F1: 0.6789

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.49405 | val 0.67044
  Epoch 020 - train 0.46756 | val 0.62619
  Regression -> MSE: 0.000307, MAE: 0.014435, R²: 0.0009
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.43637 | val 0.51527
  Epoch 016 - train 0.41999 | val 0.51390
  Regression -> MSE: 0.000098, MAE: 0.007370, R²: -0.0006
  Directional -> Accuracy: 0.4318, MCC: 0.0000, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.44931 | val 0.70549
  Epoch 016 - train 0.45745 | val 0.70814
  Regression -> MSE: 0.000172, MAE: 0.009796, R²: -0.0023
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.39982 | val 0.57830
  Epoch 016 - train 0.39656 | val 0.57679
  Regression -> MSE: 0.000227, MAE: 0.011862, R²: -0.0173
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.43362 | val 0.56113
  Epoch 016 - train 0.43125 | val 0.59527
  Regression -> MSE: 0.000092, MAE: 0.007631, R²: 0.0017
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.46293 | val 0.90186
  Epoch 016 - train 0.45052 | val 0.93782
  Regression -> MSE: 0.000164, MAE: 0.010268, R²: -0.0024
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.41374 | val 0.66053
  Epoch 016 - train 0.41729 | val 0.68515
  Regression -> MSE: 0.000121, MAE: 0.008985, R²: -0.0425
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.45652 | val 0.83931

[I 2026-02-22 22:26:36,686] Trial 67 finished with value: -0.011441022091635387 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.0, 'batch_size': 64, 'learning_rate': 3.3632420135502945e-05, 'weight_decay': 2.3265345062598457e-06, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 1.5000176648865198, 'early_stopping_min_delta': 0.005424338858433804}. Best is trial 31 with value: -0.011425014985750452.

  Epoch 016 - train 0.45795 | val 0.85614
  Regression -> MSE: 0.000245, MAE: 0.012370, R²: -0.0347
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 36
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.41894 | val 0.83049
  Epoch 016 - train 0.40480 | val 0.90097
  Regression -> MSE: 0.000235, MAE: 0.012082, R²: 0.0001
  Directional -> Accuracy: 0.5541, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 112). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.44054 | val 0.53043
  Epoch 016 - train 0.42980 | val 0.53684
  Regression -> MSE: 0.000758, MAE: 0.020590, R²: -0.0632
  Directional -> Accuracy: 0.3953, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for AEP (109 < 112). Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 112). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.42788 | val 1.04242
  Epoch 020 - train 0.41450 | val 1.05576
  Regression -> MSE: 0.000331, MAE: 0.014611, R²: -0.0400
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.36995 | val 0.50312
  Epoch 016 - train 0.35932 | val 0.51580
  Regression -> MSE: 0.000385, MAE: 0.015077, R²: -0.0777
  Directional -> Accuracy: 0.4583, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.44757 | val 0.44884
  Epoch 020 - train 0.41451 | val 0.39164
  Regression -> MSE: 0.000204, MAE: 0.009824, R²: 0.0303
  Directional -> Accuracy: 0.5625, MCC: 0.2174, F1: 0.7042

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.38628 | val 0.96723
  Epoch 020 - train 0.35367 | val 1.05398
  Regression -> MSE: 0.000555, MAE: 0.018044, R²: 0.0097
  Directional -> Accuracy: 0.6136, MCC: 0.3581, F1: 0.3704

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.44457 | val 0.64008
  Epoch 020 - train 0.41364 | val 0.62545
  Regression -> MSE: 0.000254, MAE: 0.012337, R²: 0.0041
  Directional -> Accuracy: 0.4697, MCC: -0.0788, F1: 0.3860

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 112). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 112). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.39389 | val 0.49820
  Epoch 016 - train 0.40042 | val 0.51752
  Regression -> MSE: 0.000595, MAE: 0.019182, R²: -0.0273
  Directional -> Accuracy: 0.4359, MCC: 0.0000, F1: 0.6071

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.42051 | val 0.70648
  Epoch 016 - train 0.39157 | val 0.76776
  Regression -> MSE: 0.000383, MAE: 0.015844, R²: -0.0049
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 112). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 112). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 112). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.42194 | val 0.74655
  Epoch 016 - train 0.40386 | val 0.94843
  Regression -> MSE: 0.000247, MAE: 0.012134, R²: -0.0021
  Directional -> Accuracy: 0.4179, MCC: 0.0000, F1: 0.5895

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.39961 | val 0.84260
  Epoch 016 - train 0.38940 | val 0.90239
  Regression -> MSE: 0.000312, MAE: 0.013334, R²: 0.0009
  Directional -> Accuracy: 0.5532, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.45168 | val 0.61294
  Epoch 020 - train 0.42203 | val 0.63486
  Regression -> MSE: 0.000679, MAE: 0.019497, R²: 0.0233
  Directional -> Accuracy: 0.5273, MCC: 0.0106, F1: 0.6829

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 112). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.41664 | val 0.51004
  Epoch 020 - train 0.39903 | val 0.56388
  Regression -> MSE: 0.000150, MAE: 0.009702, R²: -0.0397
  Directional -> Accuracy: 0.4792, MCC: 0.0000, F1: 0.6479

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 112). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.37028 | val 0.72942
  Epoch 020 - train 0.34444 | val 0.76292
  Regression -> MSE: 0.000226, MAE: 0.010610, R²: 0.0139
  Directional -> Accuracy: 0.4828, MCC: -0.0676, F1: 0.6053

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.39976 | val 1.43088
  Epoch 016 - train 0.40419 | val 1.50131
  Regression -> MSE: 0.000373, MAE: 0.016144, R²: 0.0003
  Directional -> Accuracy: 0.5714, MCC: 0.1599, F1: 0.0870

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.44119 | val 0.50481
  Epoch 016 - train 0.41989 | val 0.54863
  Regression -> MSE: 0.000109, MAE: 0.008037, R²: 0.0009
  Directional -> Accuracy: 0.4776, MCC: 0.0144, F1: 0.2222

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 112). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.38524 | val 1.14415
  Epoch 016 - train 0.38327 | val 1.23352
  Regression -> MSE: 0.000152, MAE: 0.009767, R²: -0.0055
  Directional -> Accuracy: 0.6071, MCC: 0.0000, F1: 0.7556

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.43631 | val 0.49741
  Epoch 016 - train 0.41628 | val 0.59237
  Regression -> MSE: 0.000278, MAE: 0.013072, R²: -0.0045
  Directional -> Accuracy: 0.5890, MCC: 0.0000, F1: 0.7414

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.35404 | val 0.76132
  Epoch 020 - train 0.33293 | val 0.73097
  Regression -> MSE: 0.000311, MAE: 0.014494, R²: -1.0169
  Directional -> Accuracy: 0.4516, MCC: 0.0901, F1: 0.1500

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 112). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.42645 | val 0.97131
  Epoch 020 - train 0.40934 | val 1.07522
  Regression -> MSE: 0.000292, MAE: 0.012422, R²: -0.2817
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.42605 | val 0.74289
  Epoch 016 - train 0.40849 | val 0.75552
  Regression -> MSE: 0.000149, MAE: 0.008341, R²: -0.0047
  Directional -> Accuracy: 0.6000, MCC: 0.0000, F1: 0.7500

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 112). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 112). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 112). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.41530 | val 0.57044
  Epoch 016 - train 0.39952 | val 0.57670
  Regression -> MSE: 0.000172, MAE: 0.010573, R²: -0.0078
  Directional -> Accuracy: 0.4921, MCC: 0.0000, F1: 0.6596

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.45494 | val 0.65463
  Epoch 020 - train 0.42160 | val 0.90697
  Regression -> MSE: 0.000092, MAE: 0.007427, R²: -0.0329
  Directional -> Accuracy: 0.5636, MCC: 0.1811, F1: 0.5385

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.42478 | val 0.68237
  Epoch 020 - train 0.40976 | val 0.72200
  Regression -> MSE: 0.000216, MAE: 0.011397, R²: 0.0016
  Directional -> Accuracy: 0.5556, MCC: 0.1720, F1: 0.6500

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.37089 | val 0.38585
  Epoch 020 - train 0.35870 | val 0.36176
  Regression -> MSE: 0.000101, MAE: 0.008109, R²: -0.1215
  Directional -> Accuracy: 0.5472, MCC: 0.2095, F1: 0.3684

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.43936 | val 0.55103
  Epoch 020 - train 0.42967 | val 0.53671
  Regression -> MSE: 0.000104, MAE: 0.008604, R²: -0.1300
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.45185 | val 0.28134
  Epoch 020 - train 0.42493 | val 0.30166
  Regression -> MSE: 0.000288, MAE: 0.013358, R²: -0.0353
  Directional -> Accuracy: 0.5208, MCC: -0.2182, F1: 0.6849

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.40025 | val 0.64489
  Epoch 020 - train 0.38142 | val 0.64194
  Regression -> MSE: 0.000255, MAE: 0.010611, R²: -0.4824
  Directional -> Accuracy: 0.4630, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
Insufficient data for proper time series validation for MDT. Skipping...

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.41936 | val 1.09070
  Epoch 016 - train 0.41073 | val 1.10669
  Regression -> MSE: 0.000240, MAE: 0.010092, R²: -0.0026
  Directional -> Accuracy: 0.4750, MCC: -0.0501, F1: 0.4878

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.43356 | val 0.59238
  Epoch 016 - train 0.41457 | val 0.60225
  Regression -> MSE: 0.000147, MAE: 0.008574, R²: -0.0317
  Directional -> Accuracy: 0.4500, MCC: -0.0580, F1: 0.3125

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.42905 | val 0.70003
  Epoch 020 - train 0.40942 | val 0.67970
  Regression -> MSE: 0.000208, MAE: 0.011255, R²: -0.0924
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.35210 | val 0.64103
  Epoch 020 - train 0.34018 | val 0.64512
  Regression -> MSE: 0.000334, MAE: 0.012184, R²: -0.2587
  Directional -> Accuracy: 0.5143, MCC: 0.1300, F1: 0.3462

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 112). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.37363 | val 0.48467
  Epoch 020 - train 0.32945 | val 0.47134
  Regression -> MSE: 0.000277, MAE: 0.013066, R²: -0.3287
  Directional -> Accuracy: 0.4694, MCC: 0.0000, F1: 0.6389

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 112). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.39535 | val 0.43705
  Epoch 020 - train 0.37282 | val 0.43606
  Regression -> MSE: 0.000348, MAE: 0.012143, R²: 0.0248
  Directional -> Accuracy: 0.5469, MCC: 0.1738, F1: 0.4528

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.45394 | val 0.29976
  Epoch 020 - train 0.40878 | val 0.29112
  Regression -> MSE: 0.000105, MAE: 0.007662, R²: -0.0829
  Directional -> Accuracy: 0.6939, MCC: 0.4008, F1: 0.6341

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.43324 | val 0.92854
  Epoch 016 - train 0.42140 | val 0.94549
  Regression -> MSE: 0.000217, MAE: 0.011227, R²: -0.0015
  Directional -> Accuracy: 0.5370, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.42018 | val 1.22922
  Epoch 020 - train 0.39189 | val 1.29984
  Regression -> MSE: 0.000078, MAE: 0.006797, R²: -0.0826
  Directional -> Accuracy: 0.5000, MCC: 0.1347, F1: 0.4211

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 112). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for PPL (108 < 112). Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 112). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 112). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 112). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.41312 | val 0.27882
  Epoch 016 - train 0.40060 | val 0.28012
  Regression -> MSE: 0.000301, MAE: 0.013617, R²: -0.0094
  Directional -> Accuracy: 0.6667, MCC: 0.0000, F1: 0.0000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 112). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 112). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 112). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.38852 | val 0.64989
  Epoch 020 - train 0.35905 | val 0.72400
  Regression -> MSE: 0.000077, MAE: 0.006875, R²: 0.0134
  Directional -> Accuracy: 0.5278, MCC: 0.1690, F1: 0.6792

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 112). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 112). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 112). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 112). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.44626 | val 0.76601
  Epoch 016 - train 0.43623 | val 0.77285
  Regression -> MSE: 0.000283, MAE: 0.013954, R²: -0.0002
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.42857 | val 0.43752
  Epoch 016 - train 0.42549 | val 0.43770
  Regression -> MSE: 0.000110, MAE: 0.008030, R²: -0.0153
  Directional -> Accuracy: 0.4103, MCC: 0.0000, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.44147 | val 0.80085
  Epoch 016 - train 0.43611 | val 0.81211
  Regression -> MSE: 0.000184, MAE: 0.010315, R²: -0.0089
  Directional -> Accuracy: 0.3778, MCC: 0.0000, F1: 0.5484

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.40772 | val 0.60577
  Epoch 016 - train 0.38675 | val 0.86118
  Regression -> MSE: 0.000230, MAE: 0.011899, R²: 0.0034
  Directional -> Accuracy: 0.5472, MCC: 0.0000, F1: 0.7073

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.40689 | val 0.79803
  Epoch 016 - train 0.39229 | val 1.03259
  Regression -> MSE: 0.000088, MAE: 0.007522, R²: -0.0023
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.44322 | val 0.98274
  Epoch 016 - train 0.42138 | val 0.98552
  Regression -> MSE: 0.000171, MAE: 0.010458, R²: -0.0035
  Directional -> Accuracy: 0.5098, MCC: 0.0000, F1: 0.0000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.42317 | val 0.73812
  Epoch 016 - train 0.41240 | val 0.82618
  Regression -> MSE: 0.000124, MAE: 0.009103, R²: -0.0488
  Directional -> Accuracy: 0.4906, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.43862 | val 0.94779

[I 2026-02-22 22:30:06,799] Trial 68 finished with value: -0.01175989171774733 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 36, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.1, 'batch_size': 64, 'learning_rate': 3.4557874649214215e-05, 'weight_decay': 5.754212337257029e-06, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 1.5900342564190038, 'early_stopping_min_delta': 0.0051235388807178}. Best is trial 31 with value: -0.011425014985750452.

  Epoch 020 - train 0.42299 | val 1.12112
  Regression -> MSE: 0.000247, MAE: 0.012721, R²: 0.0035
  Directional -> Accuracy: 0.4655, MCC: 0.0000, F1: 0.6353

================================================================================
Pipeline completed: 47/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (47, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.40237 | val 0.78842
  Epoch 020 - train 0.39843 | val 1.12245
  Epoch 024 - train 0.40230 | val 1.11642
  Regression -> MSE: 0.000251, MAE: 0.012629, R²: -0.0438
  Directional -> Accuracy: 0.4474, MCC: 0.0000, F1: 0.6182

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.41377 | val 0.45099
  Epoch 016 - train 0.41194 | val 0.45020
  Regression -> MSE: 0.000728, MAE: 0.020199, R²: -0.0435
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.47378 | val 1.00326
  Epoch 020 - train 0.42729 | val 0.98904
  Epoch 030 - train 0.43538 | val 1.06885
  Regression -> MSE: 0.000332, MAE: 0.014769, R²: -0.0565
  Directional -> Accuracy: 0.4565, MCC: -0.0851, F1: 0.1379

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.38182 | val 0.44965
  Epoch 020 - train 0.36165 | val 0.54100
  Epoch 024 - train 0.36125 | val 0.49820
  Regression -> MSE: 0.000358, MAE: 0.014808, R²: -0.0142
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.44068 | val 0.44392
  Epoch 020 - train 0.41587 | val 0.39135
  Epoch 030 - train 0.39890 | val 0.38907
  Regression -> MSE: 0.000224, MAE: 0.010646, R²: -0.0850
  Directional -> Accuracy: 0.5600, MCC: 0.2125, F1: 0.7027

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.39546 | val 1.10322
  Epoch 016 - train 0.36511 | val 1.17330
  Regression -> MSE: 0.000569, MAE: 0.018338, R²: -0.0058
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.42343 | val 0.64904
  Epoch 020 - train 0.40925 | val 0.91011
  Epoch 024 - train 0.39144 | val 0.93799
  Regression -> MSE: 0.000245, MAE: 0.012107, R²: 0.0102
  Directional -> Accuracy: 0.5147, MCC: 0.0962, F1: 0.5352

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.39767 | val 0.44394
  Epoch 016 - train 0.36187 | val 0.49182
  Regression -> MSE: 0.000654, MAE: 0.020247, R²: -0.0705
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.41545 | val 0.63268
  Epoch 016 - train 0.41476 | val 0.64214
  Regression -> MSE: 0.000375, MAE: 0.015652, R²: -0.0053
  Directional -> Accuracy: 0.4375, MCC: 0.0000, F1: 0.6087

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.44529 | val 0.73033
  Epoch 020 - train 0.39984 | val 0.78272
  Epoch 027 - train 0.38599 | val 0.89944
  Regression -> MSE: 0.000242, MAE: 0.011767, R²: 0.0105
  Directional -> Accuracy: 0.5507, MCC: 0.0563, F1: 0.4151

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.40435 | val 0.84401
  Epoch 016 - train 0.39860 | val 0.97490
  Regression -> MSE: 0.000312, MAE: 0.013680, R²: -0.0003
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.44761 | val 0.65172
  Epoch 016 - train 0.43762 | val 0.66453
  Regression -> MSE: 0.000690, MAE: 0.019620, R²: -0.0054
  Directional -> Accuracy: 0.4912, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.41335 | val 0.56259
  Epoch 016 - train 0.42105 | val 0.73873
  Regression -> MSE: 0.000145, MAE: 0.009453, R²: -0.0507
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.37571 | val 0.72879
  Epoch 016 - train 0.36886 | val 0.78838
  Regression -> MSE: 0.000227, MAE: 0.010670, R²: -0.0015
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.42514 | val 1.42010
  Epoch 016 - train 0.38903 | val 1.53589
  Regression -> MSE: 0.000366, MAE: 0.016219, R²: 0.0006
  Directional -> Accuracy: 0.4510, MCC: 0.0000, F1: 0.6216

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.43310 | val 0.50953
  Epoch 016 - train 0.40414 | val 0.56033
  Regression -> MSE: 0.000110, MAE: 0.007939, R²: -0.0142
  Directional -> Accuracy: 0.5362, MCC: 0.0000, F1: 0.6981

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.41383 | val 1.08705
  Epoch 016 - train 0.41152 | val 1.09154
  Regression -> MSE: 0.000159, MAE: 0.009970, R²: -0.0114
  Directional -> Accuracy: 0.6207, MCC: 0.0000, F1: 0.7660

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.46291 | val 0.52600
  Epoch 016 - train 0.42617 | val 0.74714
  Regression -> MSE: 0.000287, MAE: 0.013670, R²: -0.0480
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.35837 | val 0.70121
  Epoch 020 - train 0.34506 | val 0.87305
  Epoch 028 - train 0.33563 | val 0.95134
  Regression -> MSE: 0.000189, MAE: 0.009861, R²: -0.2436
  Directional -> Accuracy: 0.4531, MCC: 0.0577, F1: 0.1860

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.42587 | val 0.96102
  Epoch 020 - train 0.39029 | val 0.98660
  Epoch 026 - train 0.40368 | val 0.95662
  Regression -> MSE: 0.000330, MAE: 0.013540, R²: -0.4501
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.42689 | val 0.74205
  Epoch 016 - train 0.42908 | val 0.75539
  Regression -> MSE: 0.000146, MAE: 0.008430, R²: -0.0124
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.42457 | val 0.58094
  Epoch 016 - train 0.40767 | val 0.61494
  Regression -> MSE: 0.000173, MAE: 0.010272, R²: -0.0415
  Directional -> Accuracy: 0.6154, MCC: 0.2327, F1: 0.6032

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.45259 | val 0.66336
  Epoch 016 - train 0.43114 | val 0.68416
  Regression -> MSE: 0.000088, MAE: 0.007220, R²: -0.0128
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.43954 | val 0.73131
  Epoch 016 - train 0.41113 | val 0.84687
  Regression -> MSE: 0.000217, MAE: 0.010985, R²: -0.0278
  Directional -> Accuracy: 0.5231, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.37695 | val 0.38983
  Epoch 020 - train 0.33831 | val 0.32418
  Epoch 030 - train 0.33438 | val 0.31939
  Regression -> MSE: 0.000114, MAE: 0.008585, R²: -0.2683
  Directional -> Accuracy: 0.4364, MCC: -0.0924, F1: 0.1143

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.48033 | val 0.38176
  Epoch 020 - train 0.46298 | val 0.37830
  Epoch 030 - train 0.43568 | val 0.36781
  Regression -> MSE: 0.000108, MAE: 0.008760, R²: -0.0844
  Directional -> Accuracy: 0.4667, MCC: 0.0445, F1: 0.5714

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.45075 | val 0.45427
  Epoch 016 - train 0.43757 | val 0.45679
  Regression -> MSE: 0.000242, MAE: 0.013030, R²: -0.0221
  Directional -> Accuracy: 0.5476, MCC: -0.1353, F1: 0.7077

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.42575 | val 0.60602
  Epoch 020 - train 0.41658 | val 0.59740
  Epoch 030 - train 0.39035 | val 0.59142
  Regression -> MSE: 0.000217, MAE: 0.008949, R²: -0.2807
  Directional -> Accuracy: 0.4821, MCC: 0.0788, F1: 0.2162

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.46068 | val 0.33662
  Epoch 020 - train 0.42410 | val 0.32753
  Epoch 030 - train 0.40952 | val 0.31239
  Regression -> MSE: 0.000232, MAE: 0.011793, R²: 0.0428
  Directional -> Accuracy: 0.5500, MCC: 0.0000, F1: 0.7097

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.44056 | val 1.03015
  Epoch 016 - train 0.41073 | val 1.03428
  Regression -> MSE: 0.000236, MAE: 0.010035, R²: -0.0006
  Directional -> Accuracy: 0.5238, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.42085 | val 0.63692
  Epoch 016 - train 0.39154 | val 0.67661
  Regression -> MSE: 0.000142, MAE: 0.008495, R²: -0.0306
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.42616 | val 0.72278
  Epoch 020 - train 0.39326 | val 0.73768
  Epoch 029 - train 0.38559 | val 0.73568
  Regression -> MSE: 0.000186, MAE: 0.010704, R²: -0.0172
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.37051 | val 0.63875
  Epoch 020 - train 0.34053 | val 0.61981
  Epoch 030 - train 0.33688 | val 0.62148
  Regression -> MSE: 0.000359, MAE: 0.013159, R²: -0.3528
  Directional -> Accuracy: 0.5000, MCC: 0.0747, F1: 0.3571

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.39018 | val 0.55663
  Epoch 016 - train 0.37841 | val 0.60324
  Regression -> MSE: 0.000183, MAE: 0.010383, R²: 0.0023
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.40106 | val 0.43079
  Epoch 020 - train 0.36368 | val 0.50573
  Epoch 026 - train 0.36471 | val 0.51066
  Regression -> MSE: 0.000367, MAE: 0.013191, R²: -0.0562
  Directional -> Accuracy: 0.4242, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.39013 | val 0.24799
  Epoch 020 - train 0.40608 | val 0.24338
  Epoch 027 - train 0.35790 | val 0.25461
  Regression -> MSE: 0.000128, MAE: 0.008344, R²: -0.2106
  Directional -> Accuracy: 0.5476, MCC: 0.1494, F1: 0.3871

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.41396 | val 0.83816
  Epoch 016 - train 0.43024 | val 0.86760
  Regression -> MSE: 0.000221, MAE: 0.011310, R²: -0.0032
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.38923 | val 1.21236
  Epoch 016 - train 0.42375 | val 1.25406
  Regression -> MSE: 0.000076, MAE: 0.006794, R²: -0.0335
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.39857 | val 0.28894
  Epoch 020 - train 0.35742 | val 0.26967
  Epoch 030 - train 0.37731 | val 0.24964
  Regression -> MSE: 0.000869, MAE: 0.026175, R²: -1.7912
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.40294 | val 0.68407
  Epoch 016 - train 0.38425 | val 0.96062
  Regression -> MSE: 0.000078, MAE: 0.006921, R²: 0.0003
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.41777 | val 0.66158
  Epoch 016 - train 0.42961 | val 0.65924
  Regression -> MSE: 0.000303, MAE: 0.014399, R²: -0.0075
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.43353 | val 0.64518
  Epoch 020 - train 0.40475 | val 0.62298
  Epoch 030 - train 0.36693 | val 0.59548
  Regression -> MSE: 0.000102, MAE: 0.007051, R²: -0.0050
  Directional -> Accuracy: 0.5952, MCC: 0.1334, F1: 0.7302

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.42432 | val 0.78120
  Epoch 016 - train 0.42896 | val 0.78134
  Regression -> MSE: 0.000175, MAE: 0.009799, R²: -0.0003
  Directional -> Accuracy: 0.4792, MCC: 0.0580, F1: 0.5098

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.41652 | val 0.58953
  Epoch 016 - train 0.39215 | val 0.61224
  Regression -> MSE: 0.000228, MAE: 0.011839, R²: -0.0101
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.40329 | val 0.66847
  Epoch 016 - train 0.40736 | val 0.86481
  Regression -> MSE: 0.000094, MAE: 0.007748, R²: 0.0005
  Directional -> Accuracy: 0.5000, MCC: 0.0709, F1: 0.6500

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.44162 | val 1.00888
  Epoch 016 - train 0.43599 | val 1.01516
  Regression -> MSE: 0.000170, MAE: 0.010412, R²: -0.0201
  Directional -> Accuracy: 0.4906, MCC: 0.0000, F1: 0.0000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.40370 | val 0.70801
  Epoch 016 - train 0.42016 | val 0.82221
  Regression -> MSE: 0.000126, MAE: 0.009159, R²: -0.0670
  Directional -> Accuracy: 0.4727, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.44212 | val 0.93080

[I 2026-02-22 22:32:34,516] Trial 69 finished with value: -0.011919977602670695 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.4, 'dropout': 0.2, 'batch_size': 64, 'learning_rate': 0.00044750883342214884, 'weight_decay': 2.19802765614607e-06, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 30, 'huber_delta': 1.6891918471673846, 'early_stopping_min_delta': 0.0055048267141354044}. Best is trial 31 with value: -0.011425014985750452.

  Epoch 016 - train 0.43929 | val 0.98255
  Regression -> MSE: 0.000243, MAE: 0.012435, R²: -0.0119
  Directional -> Accuracy: 0.5167, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 30
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.35447 | val 0.88776
  Epoch 011 - train 0.35942 | val 0.90290
  Regression -> MSE: 0.000238, MAE: 0.012176, R²: 0.0031
  Directional -> Accuracy: 0.5733, MCC: 0.1264, F1: 0.2000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 106). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.34283 | val 0.43543
  Epoch 020 - train 0.30461 | val 1.01484
  Regression -> MSE: 0.000696, MAE: 0.019354, R²: 0.0123
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.7429

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 106). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.36510 | val 0.93233
  Epoch 020 - train 0.31948 | val 0.94146
  Regression -> MSE: 0.000357, MAE: 0.015685, R²: -0.1102
  Directional -> Accuracy: 0.4889, MCC: 0.0138, F1: 0.3429

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.31498 | val 0.49937
  Epoch 012 - train 0.30693 | val 0.51327
  Regression -> MSE: 0.000361, MAE: 0.014765, R²: -0.0133
  Directional -> Accuracy: 0.5342, MCC: 0.0000, F1: 0.6964

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.34735 | val 0.38861
  Epoch 020 - train 0.30576 | val 0.43989
  Regression -> MSE: 0.000210, MAE: 0.009853, R²: 0.0025
  Directional -> Accuracy: 0.5918, MCC: 0.1883, F1: 0.6552

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.31358 | val 0.94478
  Epoch 011 - train 0.30707 | val 0.94096
  Regression -> MSE: 0.000575, MAE: 0.018435, R²: -0.0004
  Directional -> Accuracy: 0.5556, MCC: 0.1632, F1: 0.2308

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.36136 | val 0.86414
  Epoch 016 - train 0.33376 | val 0.85005
  Regression -> MSE: 0.000253, MAE: 0.012109, R²: -0.0043
  Directional -> Accuracy: 0.5373, MCC: 0.0557, F1: 0.4561

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 106). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 106). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.27808 | val 0.46421
  Epoch 011 - train 0.28664 | val 0.46849
  Regression -> MSE: 0.000659, MAE: 0.020354, R²: -0.0539
  Directional -> Accuracy: 0.4390, MCC: 0.0000, F1: 0.6102

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.34247 | val 0.68360
  Epoch 018 - train 0.31087 | val 0.95473
  Regression -> MSE: 0.000372, MAE: 0.015990, R²: 0.0053
  Directional -> Accuracy: 0.4468, MCC: 0.0000, F1: 0.6176

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 106). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 106). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 106). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.35999 | val 0.70453
  Epoch 017 - train 0.33402 | val 0.90981
  Regression -> MSE: 0.000265, MAE: 0.012012, R²: -0.0654
  Directional -> Accuracy: 0.5588, MCC: 0.0345, F1: 0.2857

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.34047 | val 0.76228
  Epoch 011 - train 0.34009 | val 0.75361
  Regression -> MSE: 0.000323, MAE: 0.013520, R²: -0.0300
  Directional -> Accuracy: 0.5417, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.38068 | val 0.59364
  Epoch 011 - train 0.35392 | val 0.60425
  Regression -> MSE: 0.000697, MAE: 0.019823, R²: 0.0013
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 106). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.34424 | val 0.56979
  Epoch 013 - train 0.32593 | val 0.72076
  Regression -> MSE: 0.000142, MAE: 0.009313, R²: 0.0002
  Directional -> Accuracy: 0.4898, MCC: 0.0000, F1: 0.6575

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 106). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.30857 | val 0.73661
  Epoch 011 - train 0.29460 | val 0.76058
  Regression -> MSE: 0.000228, MAE: 0.010650, R²: 0.0047
  Directional -> Accuracy: 0.5424, MCC: 0.1394, F1: 0.6824

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.35658 | val 1.27101
  Epoch 020 - train 0.31174 | val 1.59800
  Regression -> MSE: 0.000362, MAE: 0.015789, R²: 0.0116
  Directional -> Accuracy: 0.5600, MCC: 0.0987, F1: 0.4762

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.35162 | val 0.57019
  Epoch 013 - train 0.34951 | val 0.56763
  Regression -> MSE: 0.000107, MAE: 0.007884, R²: 0.0120
  Directional -> Accuracy: 0.5147, MCC: 0.0039, F1: 0.6118

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 106). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.36046 | val 1.06721
  Epoch 012 - train 0.34195 | val 1.14461
  Regression -> MSE: 0.000149, MAE: 0.009622, R²: 0.0007
  Directional -> Accuracy: 0.6140, MCC: 0.0000, F1: 0.7609

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.37282 | val 0.60472
  Epoch 011 - train 0.37731 | val 0.63344
  Regression -> MSE: 0.000293, MAE: 0.013864, R²: -0.0585
  Directional -> Accuracy: 0.4054, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.29971 | val 0.67018
  Epoch 018 - train 0.28110 | val 0.80307
  Regression -> MSE: 0.000192, MAE: 0.010077, R²: -0.2628
  Directional -> Accuracy: 0.4127, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 106). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.34721 | val 1.01576
  Epoch 014 - train 0.31382 | val 1.07979
  Regression -> MSE: 0.000256, MAE: 0.011360, R²: -0.1365
  Directional -> Accuracy: 0.4521, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.34810 | val 0.69641
  Epoch 011 - train 0.34006 | val 0.70275
  Regression -> MSE: 0.000151, MAE: 0.008619, R²: -0.0275
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 106). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 106). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 106). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.35740 | val 0.56568
  Epoch 014 - train 0.34441 | val 0.61694
  Regression -> MSE: 0.000177, MAE: 0.010587, R²: -0.0537
  Directional -> Accuracy: 0.5156, MCC: 0.0314, F1: 0.4918

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.34954 | val 0.63251
  Epoch 014 - train 0.33490 | val 0.91179
  Regression -> MSE: 0.000092, MAE: 0.007413, R²: -0.0432
  Directional -> Accuracy: 0.5000, MCC: 0.1833, F1: 0.2632

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.35391 | val 1.07493
  Epoch 013 - train 0.31213 | val 1.18748
  Regression -> MSE: 0.000211, MAE: 0.011053, R²: 0.0101
  Directional -> Accuracy: 0.4531, MCC: -0.0705, F1: 0.5679

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.29361 | val 0.33607
  Epoch 020 - train 0.25052 | val 0.68029
  Regression -> MSE: 0.000104, MAE: 0.008170, R²: -0.1419
  Directional -> Accuracy: 0.4259, MCC: -0.1628, F1: 0.0606

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.37957 | val 0.40715
  Epoch 020 - train 0.30405 | val 0.40191
  Regression -> MSE: 0.000124, MAE: 0.009129, R²: -0.2925
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.5902

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.38475 | val 0.28655
  Epoch 017 - train 0.36817 | val 0.54964
  Regression -> MSE: 0.000282, MAE: 0.013110, R²: -0.0328
  Directional -> Accuracy: 0.5714, MCC: 0.1199, F1: 0.6316

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.35713 | val 0.58666
  Epoch 019 - train 0.31841 | val 0.69434
  Regression -> MSE: 0.000199, MAE: 0.008159, R²: -0.1713
  Directional -> Accuracy: 0.5455, MCC: 0.2887, F1: 0.2857

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.35289 | val 0.33475
  Epoch 014 - train 0.33310 | val 0.35898
  Regression -> MSE: 0.000250, MAE: 0.012378, R²: 0.0052
  Directional -> Accuracy: 0.5526, MCC: 0.0000, F1: 0.7119

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.38369 | val 1.08771
  Epoch 011 - train 0.37492 | val 1.10624
  Regression -> MSE: 0.000233, MAE: 0.009920, R²: 0.0009
  Directional -> Accuracy: 0.4878, MCC: 0.0000, F1: 0.6557

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.34841 | val 0.60999
  Epoch 013 - train 0.33346 | val 0.65885
  Regression -> MSE: 0.000147, MAE: 0.008476, R²: -0.0538
  Directional -> Accuracy: 0.4390, MCC: -0.0790, F1: 0.3429

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.34182 | val 0.63001
  Epoch 020 - train 0.30163 | val 0.70260
  Regression -> MSE: 0.000196, MAE: 0.010708, R²: -0.0530
  Directional -> Accuracy: 0.5000, MCC: -0.0053, F1: 0.5385

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.29448 | val 0.61219
  Epoch 017 - train 0.27782 | val 0.69167
  Regression -> MSE: 0.000320, MAE: 0.011951, R²: -0.1987
  Directional -> Accuracy: 0.4930, MCC: 0.0939, F1: 0.3077

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 106). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.30007 | val 0.54320
  Epoch 012 - train 0.28672 | val 0.54273
  Regression -> MSE: 0.000190, MAE: 0.010759, R²: -0.0140
  Directional -> Accuracy: 0.4762, MCC: 0.0000, F1: 0.6452

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 106). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.33100 | val 0.43785
  Epoch 014 - train 0.30790 | val 0.45969
  Regression -> MSE: 0.000348, MAE: 0.012038, R²: 0.0118
  Directional -> Accuracy: 0.4923, MCC: 0.2228, F1: 0.1951

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.32453 | val 0.25565
  Epoch 020 - train 0.26991 | val 0.26969
  Regression -> MSE: 0.000133, MAE: 0.008359, R²: -0.2140
  Directional -> Accuracy: 0.7250, MCC: 0.4701, F1: 0.7027

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.33722 | val 0.83816
  Epoch 016 - train 0.31038 | val 0.91860
  Regression -> MSE: 0.000233, MAE: 0.011839, R²: -0.0419
  Directional -> Accuracy: 0.4182, MCC: -0.1415, F1: 0.4839

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.30510 | val 1.17832
  Epoch 011 - train 0.29930 | val 1.22963
  Regression -> MSE: 0.000075, MAE: 0.006701, R²: -0.0631
  Directional -> Accuracy: 0.6222, MCC: 0.0000, F1: 0.7671

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 106). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 106). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 106). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 106). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.32500 | val 0.20479
  Epoch 020 - train 0.30031 | val 0.17679
  Regression -> MSE: 0.000547, MAE: 0.020397, R²: -0.7195
  Directional -> Accuracy: 0.3261, MCC: 0.0000, F1: 0.4918

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 106). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 106). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 106). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.32340 | val 0.86806
  Epoch 012 - train 0.30810 | val 0.99958
  Regression -> MSE: 0.000077, MAE: 0.006854, R²: 0.0038
  Directional -> Accuracy: 0.4932, MCC: 0.0000, F1: 0.6606

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 106). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 106). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 106). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 106). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.36213 | val 0.71033
  Epoch 011 - train 0.37182 | val 0.71698
  Regression -> MSE: 0.000279, MAE: 0.013883, R²: -0.0016
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.33451 | val 0.49623
  Epoch 020 - train 0.24146 | val 0.48973
  Regression -> MSE: 0.000103, MAE: 0.007028, R²: 0.0032
  Directional -> Accuracy: 0.5854, MCC: 0.0570, F1: 0.7213

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.32687 | val 0.70006
  Epoch 013 - train 0.32853 | val 0.70458
  Regression -> MSE: 0.000182, MAE: 0.010342, R²: -0.0195
  Directional -> Accuracy: 0.3696, MCC: 0.0000, F1: 0.5397

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.32356 | val 0.61852
  Epoch 012 - train 0.33193 | val 0.68542
  Regression -> MSE: 0.000234, MAE: 0.012015, R²: -0.0302
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.34266 | val 0.95980
  Epoch 012 - train 0.33074 | val 1.20069
  Regression -> MSE: 0.000089, MAE: 0.007672, R²: -0.0209
  Directional -> Accuracy: 0.4909, MCC: 0.0000, F1: 0.6585

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.39037 | val 0.92325
  Epoch 020 - train 0.31398 | val 0.99118
  Regression -> MSE: 0.000208, MAE: 0.011921, R²: -0.2474
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.32485 | val 0.66510
  Epoch 012 - train 0.32282 | val 0.70870
  Regression -> MSE: 0.000123, MAE: 0.009239, R²: -0.0287
  Directional -> Accuracy: 0.5000, MCC: 0.0148, F1: 0.4000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.37089 | val 0.85069

[I 2026-02-22 22:33:52,117] Trial 70 finished with value: -0.01174578145199752 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 30, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.0, 'batch_size': 64, 'learning_rate': 0.003148906825890743, 'weight_decay': 7.728123071642659e-07, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 1.3577128377968575, 'early_stopping_min_delta': 0.00028485630753378923}. Best is trial 31 with value: -0.011425014985750452.

  Epoch 018 - train 0.34619 | val 1.22346
  Regression -> MSE: 0.000237, MAE: 0.012442, R²: 0.0284
  Directional -> Accuracy: 0.5593, MCC: 0.1651, F1: 0.6389

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.42531 | val 0.74924
  Epoch 020 - train 0.41868 | val 0.77051
  Regression -> MSE: 0.000253, MAE: 0.012771, R²: -0.0226
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.49577 | val 0.49243
  Epoch 016 - train 0.47446 | val 0.50310
  Regression -> MSE: 0.000687, MAE: 0.019406, R²: -0.0041
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.47518 | val 0.94946
  Epoch 016 - train 0.48054 | val 0.94646
  Regression -> MSE: 0.000310, MAE: 0.014399, R²: -0.0005
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.35983 | val 0.43236
  Epoch 016 - train 0.35655 | val 0.62723
  Regression -> MSE: 0.000364, MAE: 0.014809, R²: -0.0410
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.45672 | val 0.45472
  Epoch 016 - train 0.44674 | val 0.45387
  Regression -> MSE: 0.000210, MAE: 0.010218, R²: -0.0337
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.43284 | val 1.15166
  Epoch 016 - train 0.42614 | val 1.17074
  Regression -> MSE: 0.000588, MAE: 0.018728, R²: -0.0600
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.44330 | val 0.63378
  Epoch 016 - train 0.43482 | val 0.65395
  Regression -> MSE: 0.000245, MAE: 0.011966, R²: 0.0020
  Directional -> Accuracy: 0.5507, MCC: 0.1697, F1: 0.5753

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.44863 | val 0.66656
  Epoch 016 - train 0.43517 | val 0.66580
  Regression -> MSE: 0.000625, MAE: 0.019799, R²: -0.0462
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.43030 | val 0.58772
  Epoch 016 - train 0.43503 | val 0.59708
  Regression -> MSE: 0.000390, MAE: 0.015965, R²: -0.0160
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.44675 | val 0.66688
  Epoch 016 - train 0.44388 | val 0.66504
  Regression -> MSE: 0.000244, MAE: 0.011654, R²: -0.0121
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.42224 | val 0.82216
  Epoch 016 - train 0.41655 | val 0.87934
  Regression -> MSE: 0.000312, MAE: 0.013803, R²: -0.0032
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.6301

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.44877 | val 0.58313
  Epoch 016 - train 0.44780 | val 0.58144
  Regression -> MSE: 0.000681, MAE: 0.019640, R²: -0.0062
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.43513 | val 0.49447
  Epoch 016 - train 0.43746 | val 0.49844
  Regression -> MSE: 0.000138, MAE: 0.009062, R²: 0.0000
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.44541 | val 0.71246
  Epoch 020 - train 0.43425 | val 0.69923
  Regression -> MSE: 0.000231, MAE: 0.010971, R²: -0.0254
  Directional -> Accuracy: 0.5246, MCC: 0.1312, F1: 0.6813

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.42739 | val 1.31075
  Epoch 016 - train 0.41783 | val 1.32577
  Regression -> MSE: 0.000363, MAE: 0.016028, R²: -0.0034
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.44885 | val 0.49803
  Epoch 016 - train 0.45064 | val 0.53098
  Regression -> MSE: 0.000108, MAE: 0.007979, R²: -0.0004
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.41025 | val 1.00613
  Epoch 020 - train 0.40318 | val 1.00119
  Regression -> MSE: 0.000154, MAE: 0.009721, R²: 0.0121
  Directional -> Accuracy: 0.5932, MCC: 0.0981, F1: 0.6923

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.46655 | val 0.47519
  Epoch 016 - train 0.46391 | val 0.48948
  Regression -> MSE: 0.000277, MAE: 0.013277, R²: -0.0169
  Directional -> Accuracy: 0.6184, MCC: 0.1632, F1: 0.7129

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.37865 | val 0.70567
  Epoch 016 - train 0.37889 | val 0.71279
  Regression -> MSE: 0.000167, MAE: 0.009130, R²: -0.1180
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.48035 | val 0.86687
  Epoch 020 - train 0.44458 | val 0.85612
  Regression -> MSE: 0.000318, MAE: 0.013205, R²: -0.4046
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.42874 | val 0.68636
  Epoch 020 - train 0.43816 | val 0.66602
  Regression -> MSE: 0.000156, MAE: 0.008938, R²: -0.0900
  Directional -> Accuracy: 0.4167, MCC: 0.1615, F1: 0.1250

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.43760 | val 0.56216
  Epoch 016 - train 0.42702 | val 0.58504
  Regression -> MSE: 0.000168, MAE: 0.010293, R²: -0.0167
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.47102 | val 0.62995
  Epoch 016 - train 0.46570 | val 0.62929
  Regression -> MSE: 0.000087, MAE: 0.007156, R²: -0.0227
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.45176 | val 0.64556
  Epoch 016 - train 0.44448 | val 0.80652
  Regression -> MSE: 0.000211, MAE: 0.011123, R²: 0.0016
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.39230 | val 0.37142
  Epoch 020 - train 0.38558 | val 0.32309
  Regression -> MSE: 0.000094, MAE: 0.007867, R²: -0.0254
  Directional -> Accuracy: 0.5714, MCC: 0.2385, F1: 0.4545

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.46493 | val 0.33163
  Epoch 016 - train 0.46184 | val 0.33221
  Regression -> MSE: 0.000104, MAE: 0.008814, R²: -0.0118
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.47007 | val 0.43694
  Epoch 016 - train 0.46135 | val 0.44174
  Regression -> MSE: 0.000233, MAE: 0.012622, R²: -0.0083
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.44073 | val 0.59017
  Epoch 020 - train 0.43123 | val 0.55921
  Regression -> MSE: 0.000214, MAE: 0.008980, R²: -0.2839
  Directional -> Accuracy: 0.4561, MCC: -0.0157, F1: 0.2791

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.47758 | val 0.29314
  Epoch 016 - train 0.45131 | val 0.29167
  Regression -> MSE: 0.000237, MAE: 0.011861, R²: -0.0001
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.44459 | val 0.95432
  Epoch 016 - train 0.44051 | val 0.95503
  Regression -> MSE: 0.000231, MAE: 0.009897, R²: -0.0014
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.45858 | val 0.62426
  Epoch 016 - train 0.43717 | val 0.63268
  Regression -> MSE: 0.000135, MAE: 0.008175, R²: -0.0021
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.50316 | val 0.64645
  Epoch 016 - train 0.47860 | val 0.64891
  Regression -> MSE: 0.000199, MAE: 0.010685, R²: -0.0579
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.38735 | val 0.60151
  Epoch 016 - train 0.37519 | val 0.59925
  Regression -> MSE: 0.000267, MAE: 0.010560, R²: -0.0195
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.45882 | val 0.36364
  Epoch 016 - train 0.44609 | val 0.36334
  Regression -> MSE: 0.000166, MAE: 0.010366, R²: 0.0024
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.38400 | val 0.52084
  Epoch 016 - train 0.38532 | val 0.52963
  Regression -> MSE: 0.000179, MAE: 0.010306, R²: 0.0026
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.42508 | val 0.42804
  Epoch 020 - train 0.40551 | val 0.42194
  Regression -> MSE: 0.000349, MAE: 0.012532, R²: -0.0197
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.44728 | val 0.23445
  Epoch 016 - train 0.46339 | val 0.23264
  Regression -> MSE: 0.000115, MAE: 0.008326, R²: -0.0935
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.45644 | val 0.77450
  Epoch 020 - train 0.43916 | val 0.76300
  Regression -> MSE: 0.000222, MAE: 0.011365, R²: -0.0137
  Directional -> Accuracy: 0.5088, MCC: 0.0262, F1: 0.5333

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.44878 | val 1.07716
  Epoch 016 - train 0.44397 | val 1.07819
  Regression -> MSE: 0.000085, MAE: 0.007217, R²: -0.0979
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.45544 | val 0.27733
  Epoch 016 - train 0.43857 | val 0.27891
  Regression -> MSE: 0.000311, MAE: 0.014009, R²: -0.0105
  Directional -> Accuracy: 0.3469, MCC: -0.1894, F1: 0.5152

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.51437 | val 0.22133
  Epoch 016 - train 0.49726 | val 0.22188
  Regression -> MSE: 0.000259, MAE: 0.011496, R²: -0.0640
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.41857 | val 0.58808
  Epoch 020 - train 0.40777 | val 0.58922
  Regression -> MSE: 0.000081, MAE: 0.007105, R²: -0.0013
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.45545 | val 0.63365
  Epoch 016 - train 0.46492 | val 0.63695
  Regression -> MSE: 0.000308, MAE: 0.014471, R²: -0.0028
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.47757 | val 0.60751
  Epoch 016 - train 0.45691 | val 0.60913
  Regression -> MSE: 0.000104, MAE: 0.007114, R²: -0.0588
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.47058 | val 0.69957
  Epoch 016 - train 0.45798 | val 0.69940
  Regression -> MSE: 0.000173, MAE: 0.009497, R²: -0.0066
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.40167 | val 0.57278
  Epoch 016 - train 0.39974 | val 0.57332
  Regression -> MSE: 0.000227, MAE: 0.011829, R²: -0.0167
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.45033 | val 0.56743
  Epoch 016 - train 0.44422 | val 0.59212
  Regression -> MSE: 0.000093, MAE: 0.007667, R²: -0.0024
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.45316 | val 0.90045
  Epoch 016 - train 0.46800 | val 0.89804
  Regression -> MSE: 0.000164, MAE: 0.010261, R²: -0.0013
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.43338 | val 0.67942
  Epoch 016 - train 0.43056 | val 0.68066
  Regression -> MSE: 0.000117, MAE: 0.008933, R²: -0.0059
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.45598 | val 0.83161

[I 2026-02-22 22:35:28,497] Trial 71 finished with value: -0.011489067365580159 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.1, 'dropout': 0.0, 'batch_size': 64, 'learning_rate': 1.3207563205051704e-05, 'weight_decay': 1.5211103961058725e-06, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 1.490321854824002, 'early_stopping_min_delta': 0.00655015070737919}. Best is trial 31 with value: -0.011425014985750452.

  Epoch 020 - train 0.44800 | val 0.81492
  Regression -> MSE: 0.000245, MAE: 0.012459, R²: -0.0338
  Directional -> Accuracy: 0.5082, MCC: -0.1229, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.44366 | val 0.79420
  Epoch 016 - train 0.43171 | val 0.85683
  Regression -> MSE: 0.000256, MAE: 0.012893, R²: -0.0359
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.44287 | val 0.45106
  Epoch 016 - train 0.44075 | val 0.45624
  Regression -> MSE: 0.000701, MAE: 0.019633, R²: -0.0246
  Directional -> Accuracy: 0.4348, MCC: -0.0604, F1: 0.2353

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.45786 | val 0.96308
  Epoch 016 - train 0.45484 | val 0.96262
  Regression -> MSE: 0.000316, MAE: 0.014474, R²: -0.0183
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.35958 | val 0.39625
  Epoch 016 - train 0.35900 | val 0.46705
  Regression -> MSE: 0.000350, MAE: 0.014595, R²: -0.0022
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.43862 | val 0.46317
  Epoch 016 - train 0.44168 | val 0.47181
  Regression -> MSE: 0.000206, MAE: 0.010123, R²: -0.0132
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.44506 | val 1.12579
  Epoch 016 - train 0.42687 | val 1.12638
  Regression -> MSE: 0.000558, MAE: 0.018153, R²: -0.0047
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.46600 | val 0.64171
  Epoch 020 - train 0.44848 | val 0.62469
  Regression -> MSE: 0.000243, MAE: 0.011882, R²: 0.0112
  Directional -> Accuracy: 0.5217, MCC: 0.0471, F1: 0.4762

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.44244 | val 0.63614
  Epoch 016 - train 0.44254 | val 0.63731
  Regression -> MSE: 0.000612, MAE: 0.019506, R²: -0.0236
  Directional -> Accuracy: 0.5909, MCC: 0.0735, F1: 0.2500

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.46096 | val 0.58123
  Epoch 016 - train 0.45411 | val 0.58076
  Regression -> MSE: 0.000393, MAE: 0.015945, R²: -0.0238
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.45787 | val 0.67884
  Epoch 016 - train 0.44960 | val 0.71419
  Regression -> MSE: 0.000244, MAE: 0.011657, R²: -0.0105
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.41271 | val 0.77983
  Epoch 016 - train 0.40418 | val 0.78847
  Regression -> MSE: 0.000311, MAE: 0.013659, R²: -0.0007
  Directional -> Accuracy: 0.4400, MCC: -0.1548, F1: 0.6111

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.47826 | val 0.60678
  Epoch 016 - train 0.47304 | val 0.63588
  Regression -> MSE: 0.000677, MAE: 0.019461, R²: 0.0000
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.43770 | val 0.48931
  Epoch 016 - train 0.43082 | val 0.50988
  Regression -> MSE: 0.000139, MAE: 0.009212, R²: -0.0048
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.42451 | val 0.71897
  Epoch 016 - train 0.40855 | val 0.71994
  Regression -> MSE: 0.000226, MAE: 0.010859, R²: -0.0052
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.48125 | val 1.31765
  Epoch 016 - train 0.46964 | val 1.32115
  Regression -> MSE: 0.000368, MAE: 0.015942, R²: -0.0172
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.46885 | val 0.49170
  Epoch 016 - train 0.45430 | val 0.51189
  Regression -> MSE: 0.000111, MAE: 0.007957, R²: -0.0277
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.43345 | val 1.04667
  Epoch 016 - train 0.42470 | val 1.13571
  Regression -> MSE: 0.000156, MAE: 0.009629, R²: -0.0009
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.45089 | val 0.47836
  Epoch 016 - train 0.45181 | val 0.53276
  Regression -> MSE: 0.000273, MAE: 0.013072, R²: -0.0016
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.39420 | val 0.71130
  Epoch 016 - train 0.37552 | val 0.74056
  Regression -> MSE: 0.000168, MAE: 0.009149, R²: -0.1231
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.44893 | val 0.87817
  Epoch 020 - train 0.42519 | val 0.86233
  Regression -> MSE: 0.000272, MAE: 0.011860, R²: -0.2026
  Directional -> Accuracy: 0.4400, MCC: -0.1277, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.48484 | val 0.67521
  Epoch 016 - train 0.46360 | val 0.68538
  Regression -> MSE: 0.000158, MAE: 0.009022, R²: -0.1020
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.41696 | val 0.55614
  Epoch 016 - train 0.40534 | val 0.55689
  Regression -> MSE: 0.000167, MAE: 0.010328, R²: -0.0090
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.48134 | val 0.63792
  Epoch 016 - train 0.47670 | val 0.63395
  Regression -> MSE: 0.000090, MAE: 0.007300, R²: -0.0556
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.45360 | val 0.65199
  Epoch 016 - train 0.45374 | val 0.67643
  Regression -> MSE: 0.000212, MAE: 0.011089, R²: -0.0023
  Directional -> Accuracy: 0.4091, MCC: -0.1722, F1: 0.4935

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.40462 | val 0.36224
  Epoch 016 - train 0.39621 | val 0.36188
  Regression -> MSE: 0.000094, MAE: 0.008109, R²: -0.0193
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.45705 | val 0.35919
  Epoch 016 - train 0.45927 | val 0.36142
  Regression -> MSE: 0.000114, MAE: 0.009139, R²: -0.1018
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.47706 | val 0.44322
  Epoch 016 - train 0.46696 | val 0.44428
  Regression -> MSE: 0.000238, MAE: 0.012762, R²: -0.0262
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.43212 | val 0.57839
  Epoch 020 - train 0.43295 | val 0.56077
  Regression -> MSE: 0.000196, MAE: 0.008368, R²: -0.1782
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.46698 | val 0.29008
  Epoch 016 - train 0.45412 | val 0.29064
  Regression -> MSE: 0.000239, MAE: 0.011938, R²: -0.0101
  Directional -> Accuracy: 0.4634, MCC: 0.0000, F1: 0.0000

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.46819 | val 0.96031
  Epoch 016 - train 0.44879 | val 0.95898
  Regression -> MSE: 0.000231, MAE: 0.009898, R²: -0.0021
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.48333 | val 0.64153
  Epoch 016 - train 0.47924 | val 0.64052
  Regression -> MSE: 0.000136, MAE: 0.008263, R²: -0.0089
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.45689 | val 0.65306
  Epoch 020 - train 0.43625 | val 0.65288
  Regression -> MSE: 0.000214, MAE: 0.011199, R²: -0.1343
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.38747 | val 0.60038
  Epoch 020 - train 0.37182 | val 0.58340
  Regression -> MSE: 0.000280, MAE: 0.011108, R²: -0.0710
  Directional -> Accuracy: 0.5342, MCC: 0.1465, F1: 0.4333

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.44824 | val 0.36512
  Epoch 016 - train 0.44163 | val 0.36958
  Regression -> MSE: 0.000166, MAE: 0.010363, R²: 0.0025
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.42271 | val 0.50345
  Epoch 016 - train 0.41177 | val 0.50754
  Regression -> MSE: 0.000180, MAE: 0.010261, R²: -0.0015
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.52003 | val 0.43571
  Epoch 016 - train 0.48803 | val 0.44821
  Regression -> MSE: 0.000346, MAE: 0.011696, R²: -0.0095
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.45592 | val 0.25860
  Epoch 020 - train 0.45049 | val 0.23844
  Regression -> MSE: 0.000126, MAE: 0.008371, R²: -0.1993
  Directional -> Accuracy: 0.5349, MCC: 0.1084, F1: 0.3333

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.45048 | val 0.78690
  Epoch 016 - train 0.45096 | val 0.80131
  Regression -> MSE: 0.000218, MAE: 0.011290, R²: 0.0004
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.45467 | val 1.09158
  Epoch 016 - train 0.45309 | val 1.09374
  Regression -> MSE: 0.000091, MAE: 0.007444, R²: -0.1658
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.44897 | val 0.34860
  Epoch 016 - train 0.44807 | val 0.34440
  Regression -> MSE: 0.000337, MAE: 0.015235, R²: -0.0945
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.47232 | val 0.19566
  Epoch 016 - train 0.45828 | val 0.19706
  Regression -> MSE: 0.000245, MAE: 0.011571, R²: -0.0039
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.0000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.43306 | val 0.59828
  Epoch 016 - train 0.42374 | val 0.60752
  Regression -> MSE: 0.000083, MAE: 0.007049, R²: -0.0256
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.47147 | val 0.62980
  Epoch 016 - train 0.45073 | val 0.62704
  Regression -> MSE: 0.000307, MAE: 0.014481, R²: -0.0020
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.43390 | val 0.59480
  Epoch 016 - train 0.41538 | val 0.59801
  Regression -> MSE: 0.000102, MAE: 0.007115, R²: -0.0423
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.48547 | val 0.73262
  Epoch 016 - train 0.47560 | val 0.73243
  Regression -> MSE: 0.000176, MAE: 0.010256, R²: -0.0262
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.39979 | val 0.57653
  Epoch 016 - train 0.41650 | val 0.58335
  Regression -> MSE: 0.000223, MAE: 0.011768, R²: -0.0016
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.45227 | val 0.57273
  Epoch 016 - train 0.44151 | val 0.57915
  Regression -> MSE: 0.000093, MAE: 0.007664, R²: -0.0024
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.46989 | val 0.91658
  Epoch 016 - train 0.46279 | val 0.93663
  Regression -> MSE: 0.000164, MAE: 0.010232, R²: 0.0014
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.42345 | val 0.66686
  Epoch 016 - train 0.42615 | val 0.67296
  Regression -> MSE: 0.000119, MAE: 0.008966, R²: -0.0281
  Directional -> Accuracy: 0.5000, MCC: -0.0065, F1: 0.5484

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.47026 | val 0.86496

[I 2026-02-22 22:37:02,810] Trial 72 finished with value: -0.01148667359062533 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.1, 'dropout': 0.0, 'batch_size': 64, 'learning_rate': 1.0842189727716455e-05, 'weight_decay': 1.1104488960521475e-06, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 1.519762477180628, 'early_stopping_min_delta': 0.007278052023409756}. Best is trial 31 with value: -0.011425014985750452.

  Epoch 016 - train 0.45633 | val 0.88582
  Regression -> MSE: 0.000237, MAE: 0.012388, R²: 0.0009
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.45434 | val 0.81045
  Epoch 016 - train 0.45183 | val 0.91645
  Regression -> MSE: 0.000260, MAE: 0.013007, R²: -0.0503
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.44837 | val 0.43606
  Epoch 016 - train 0.44273 | val 0.43630
  Regression -> MSE: 0.000717, MAE: 0.019888, R²: -0.0467
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.46095 | val 0.95616
  Epoch 016 - train 0.46192 | val 0.95583
  Regression -> MSE: 0.000312, MAE: 0.014428, R²: -0.0071
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.37008 | val 0.39629
  Epoch 016 - train 0.36104 | val 0.49761
  Regression -> MSE: 0.000349, MAE: 0.014574, R²: 0.0002
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.47599 | val 0.46248
  Epoch 016 - train 0.47376 | val 0.47348
  Regression -> MSE: 0.000207, MAE: 0.010117, R²: -0.0152
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.42649 | val 1.14530
  Epoch 020 - train 0.43167 | val 1.13475
  Regression -> MSE: 0.000595, MAE: 0.018879, R²: -0.0725
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.46643 | val 0.64932
  Epoch 016 - train 0.47008 | val 0.65732
  Regression -> MSE: 0.000249, MAE: 0.011924, R²: -0.0132
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.43096 | val 0.62495
  Epoch 016 - train 0.45687 | val 0.62109
  Regression -> MSE: 0.000609, MAE: 0.019438, R²: -0.0194
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.43336 | val 0.58099
  Epoch 016 - train 0.43815 | val 0.58030
  Regression -> MSE: 0.000394, MAE: 0.015963, R²: -0.0281
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.45136 | val 0.68336
  Epoch 016 - train 0.44783 | val 0.72750
  Regression -> MSE: 0.000245, MAE: 0.011636, R²: -0.0129
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.42121 | val 0.75619
  Epoch 016 - train 0.41734 | val 0.78547
  Regression -> MSE: 0.000315, MAE: 0.013598, R²: -0.0127
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.48168 | val 0.59292
  Epoch 016 - train 0.47358 | val 0.61094
  Regression -> MSE: 0.000681, MAE: 0.019609, R²: -0.0058
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.44343 | val 0.49093
  Epoch 016 - train 0.43714 | val 0.49497
  Regression -> MSE: 0.000138, MAE: 0.009095, R²: 0.0004
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.39967 | val 0.71177
  Epoch 016 - train 0.39418 | val 0.71051
  Regression -> MSE: 0.000226, MAE: 0.010802, R²: -0.0039
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.47232 | val 1.32006
  Epoch 016 - train 0.45454 | val 1.33068
  Regression -> MSE: 0.000372, MAE: 0.015942, R²: -0.0269
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.47494 | val 0.48929
  Epoch 020 - train 0.46807 | val 0.47602
  Regression -> MSE: 0.000112, MAE: 0.008328, R²: -0.0399
  Directional -> Accuracy: 0.4286, MCC: -0.1573, F1: 0.4872

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.42549 | val 1.01478
  Epoch 016 - train 0.43018 | val 1.03552
  Regression -> MSE: 0.000157, MAE: 0.009805, R²: -0.0043
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.45282 | val 0.47470
  Epoch 016 - train 0.44377 | val 0.47741
  Regression -> MSE: 0.000278, MAE: 0.013339, R²: -0.0209
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.36888 | val 0.70984
  Epoch 016 - train 0.37092 | val 0.70978
  Regression -> MSE: 0.000162, MAE: 0.008959, R²: -0.0820
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.44885 | val 0.88540
  Epoch 016 - train 0.43791 | val 0.90987
  Regression -> MSE: 0.000228, MAE: 0.010880, R²: -0.0074
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.47014 | val 0.67663
  Epoch 016 - train 0.45545 | val 0.68885
  Regression -> MSE: 0.000151, MAE: 0.008758, R²: -0.0568
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.42377 | val 0.58818
  Epoch 020 - train 0.41424 | val 0.58593
  Regression -> MSE: 0.000165, MAE: 0.010638, R²: 0.0009
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.45954 | val 0.63363
  Epoch 020 - train 0.46120 | val 0.62793
  Regression -> MSE: 0.000089, MAE: 0.007257, R²: -0.0497
  Directional -> Accuracy: 0.5172, MCC: 0.1165, F1: 0.4167

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.46055 | val 0.64759
  Epoch 016 - train 0.44817 | val 0.75036
  Regression -> MSE: 0.000213, MAE: 0.011054, R²: -0.0044
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.44048 | val 0.38299
  Epoch 020 - train 0.42269 | val 0.35420
  Regression -> MSE: 0.000114, MAE: 0.008479, R²: -0.2425
  Directional -> Accuracy: 0.4643, MCC: 0.1211, F1: 0.0625

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.44391 | val 0.33348
  Epoch 016 - train 0.45567 | val 0.33313
  Regression -> MSE: 0.000105, MAE: 0.008844, R²: -0.0176
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.55673 | val 0.44980
  Epoch 016 - train 0.54144 | val 0.45925
  Regression -> MSE: 0.000232, MAE: 0.012515, R²: -0.0012
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.43732 | val 0.59055
  Epoch 016 - train 0.43515 | val 0.60448
  Regression -> MSE: 0.000185, MAE: 0.008068, R²: -0.1142
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.47604 | val 0.29432
  Epoch 020 - train 0.47030 | val 0.28549
  Regression -> MSE: 0.000237, MAE: 0.011851, R²: -0.0004
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.46350 | val 0.94302
  Epoch 016 - train 0.44736 | val 0.94637
  Regression -> MSE: 0.000231, MAE: 0.009867, R²: -0.0012
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.50800 | val 0.66878
  Epoch 016 - train 0.48646 | val 0.66944
  Regression -> MSE: 0.000140, MAE: 0.008414, R²: -0.0356
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.46251 | val 0.66651
  Epoch 016 - train 0.45387 | val 0.67480
  Regression -> MSE: 0.000190, MAE: 0.010371, R²: -0.0103
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.38371 | val 0.59436
  Epoch 020 - train 0.37886 | val 0.59886
  Regression -> MSE: 0.000273, MAE: 0.010782, R²: -0.0421
  Directional -> Accuracy: 0.5205, MCC: 0.1094, F1: 0.4262

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.47236 | val 0.37241
  Epoch 016 - train 0.47155 | val 0.37166
  Regression -> MSE: 0.000167, MAE: 0.010366, R²: -0.0044
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.40794 | val 0.55006
  Epoch 016 - train 0.40626 | val 0.56788
  Regression -> MSE: 0.000184, MAE: 0.010478, R²: -0.0215
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.42229 | val 0.42805
  Epoch 020 - train 0.42042 | val 0.41618
  Regression -> MSE: 0.000347, MAE: 0.012451, R²: -0.0115
  Directional -> Accuracy: 0.4328, MCC: -0.0425, F1: 0.1364

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.48866 | val 0.24205
  Epoch 016 - train 0.48000 | val 0.24310
  Regression -> MSE: 0.000119, MAE: 0.008366, R²: -0.1301
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.47468 | val 0.78909
  Epoch 016 - train 0.46705 | val 0.82056
  Regression -> MSE: 0.000219, MAE: 0.011297, R²: -0.0007
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.48397 | val 1.08994
  Epoch 016 - train 0.46422 | val 1.09484
  Regression -> MSE: 0.000083, MAE: 0.007095, R²: -0.0658
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.44093 | val 0.28544
  Epoch 016 - train 0.42918 | val 0.28541
  Regression -> MSE: 0.000314, MAE: 0.014160, R²: -0.0192
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.43356 | val 0.23381
  Epoch 016 - train 0.44500 | val 0.23473
  Regression -> MSE: 0.000261, MAE: 0.011492, R²: -0.0707
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.44049 | val 0.59094
  Epoch 016 - train 0.42619 | val 0.59696
  Regression -> MSE: 0.000081, MAE: 0.007079, R²: -0.0024
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.47405 | val 0.60364
  Epoch 016 - train 0.46643 | val 0.60632
  Regression -> MSE: 0.000309, MAE: 0.014516, R²: -0.0068
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.47469 | val 0.53313
  Epoch 016 - train 0.45464 | val 0.53054
  Regression -> MSE: 0.000098, MAE: 0.007246, R²: -0.0024
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.50092 | val 0.70326
  Epoch 016 - train 0.49713 | val 0.70390
  Regression -> MSE: 0.000172, MAE: 0.009585, R²: -0.0003
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.43435 | val 0.57738
  Epoch 016 - train 0.41954 | val 0.58126
  Regression -> MSE: 0.000223, MAE: 0.011741, R²: -0.0006
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.44331 | val 0.57616
  Epoch 016 - train 0.42844 | val 0.57849
  Regression -> MSE: 0.000094, MAE: 0.007728, R²: -0.0144
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.52144 | val 0.92597
  Epoch 016 - train 0.50868 | val 0.94377
  Regression -> MSE: 0.000165, MAE: 0.010283, R²: -0.0056
  Directional -> Accuracy: 0.4259, MCC: -0.1555, F1: 0.4746

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.43915 | val 0.64353
  Epoch 016 - train 0.44318 | val 0.64735
  Regression -> MSE: 0.000126, MAE: 0.009038, R²: -0.0878
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.48333 | val 0.84173

[I 2026-02-22 22:38:37,472] Trial 73 finished with value: -0.011447420285368921 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.1, 'dropout': 0.0, 'batch_size': 64, 'learning_rate': 1.0084296301606557e-05, 'weight_decay': 2.659875448495318e-06, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 1.5136250171276495, 'early_stopping_min_delta': 0.006592105733096827}. Best is trial 31 with value: -0.011425014985750452.

  Epoch 016 - train 0.46086 | val 0.84158
  Regression -> MSE: 0.000241, MAE: 0.012339, R²: -0.0175
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.44137 | val 0.79210
  Epoch 016 - train 0.44085 | val 0.79416
  Regression -> MSE: 0.000251, MAE: 0.012713, R²: -0.0157
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.46584 | val 0.47003
  Epoch 020 - train 0.43982 | val 0.44148
  Regression -> MSE: 0.000682, MAE: 0.019191, R²: 0.0042
  Directional -> Accuracy: 0.6087, MCC: 0.1780, F1: 0.7000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.46841 | val 0.99688
  Epoch 020 - train 0.47254 | val 0.98250
  Regression -> MSE: 0.000319, MAE: 0.014519, R²: -0.0267
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.39347 | val 0.50258
  Epoch 016 - train 0.38310 | val 0.67374
  Regression -> MSE: 0.000396, MAE: 0.015369, R²: -0.1324
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.44160 | val 0.45748
  Epoch 020 - train 0.42427 | val 0.43484
  Regression -> MSE: 0.000206, MAE: 0.010342, R²: -0.0116
  Directional -> Accuracy: 0.5490, MCC: 0.1136, F1: 0.5106

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.46177 | val 1.16195
  Epoch 016 - train 0.44635 | val 1.16603
  Regression -> MSE: 0.000556, MAE: 0.018198, R²: -0.0009
  Directional -> Accuracy: 0.4894, MCC: 0.0000, F1: 0.6571

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.47579 | val 0.68453
  Epoch 016 - train 0.46823 | val 0.70989
  Regression -> MSE: 0.000252, MAE: 0.011961, R²: -0.0251
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.48933 | val 0.76460
  Epoch 020 - train 0.46044 | val 0.75688
  Regression -> MSE: 0.000655, MAE: 0.020297, R²: -0.0957
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.46669 | val 0.64310
  Epoch 016 - train 0.44895 | val 0.64206
  Regression -> MSE: 0.000384, MAE: 0.016165, R²: -0.0002
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.49583 | val 0.70651
  Epoch 016 - train 0.49534 | val 0.76196
  Regression -> MSE: 0.000245, MAE: 0.011637, R²: -0.0156
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.41722 | val 0.76788
  Epoch 016 - train 0.41322 | val 0.84364
  Regression -> MSE: 0.000321, MAE: 0.013593, R²: -0.0322
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.46812 | val 0.60172
  Epoch 016 - train 0.46322 | val 0.61560
  Regression -> MSE: 0.000682, MAE: 0.019681, R²: -0.0068
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.45232 | val 0.51246
  Epoch 016 - train 0.44766 | val 0.52761
  Regression -> MSE: 0.000138, MAE: 0.009032, R²: -0.0019
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.42834 | val 0.72980
  Epoch 020 - train 0.41419 | val 0.72535
  Regression -> MSE: 0.000225, MAE: 0.010775, R²: 0.0003
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.44473 | val 1.37229
  Epoch 016 - train 0.44267 | val 1.37658
  Regression -> MSE: 0.000363, MAE: 0.016023, R²: -0.0015
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.48039 | val 0.50115
  Epoch 016 - train 0.47218 | val 0.51872
  Regression -> MSE: 0.000108, MAE: 0.007954, R²: -0.0050
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.44744 | val 1.03081
  Epoch 020 - train 0.42536 | val 1.04606
  Regression -> MSE: 0.000162, MAE: 0.010141, R²: -0.0365
  Directional -> Accuracy: 0.4407, MCC: 0.0413, F1: 0.3265

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.46048 | val 0.48282
  Epoch 016 - train 0.46003 | val 0.52785
  Regression -> MSE: 0.000272, MAE: 0.013000, R²: -0.0012
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.38185 | val 0.74669
  Epoch 020 - train 0.38173 | val 0.72639
  Regression -> MSE: 0.000171, MAE: 0.009297, R²: -0.1403
  Directional -> Accuracy: 0.4154, MCC: -0.1590, F1: 0.4412

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.45911 | val 0.89765
  Epoch 020 - train 0.44176 | val 0.86068
  Regression -> MSE: 0.000377, MAE: 0.014851, R²: -0.6661
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.44440 | val 0.69740
  Epoch 016 - train 0.45404 | val 0.70297
  Regression -> MSE: 0.000154, MAE: 0.008847, R²: -0.0717
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.42704 | val 0.54970
  Epoch 016 - train 0.43995 | val 0.56338
  Regression -> MSE: 0.000180, MAE: 0.010317, R²: -0.0868
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.46944 | val 0.65439
  Epoch 016 - train 0.46737 | val 0.65408
  Regression -> MSE: 0.000086, MAE: 0.007089, R²: -0.0088
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.48823 | val 0.69911
  Epoch 016 - train 0.47906 | val 0.75447
  Regression -> MSE: 0.000218, MAE: 0.011054, R²: -0.0313
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.41545 | val 0.36045
  Epoch 020 - train 0.40091 | val 0.34161
  Regression -> MSE: 0.000095, MAE: 0.007858, R²: -0.0306
  Directional -> Accuracy: 0.5714, MCC: 0.1762, F1: 0.5385

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.49213 | val 0.38540
  Epoch 020 - train 0.47930 | val 0.37546
  Regression -> MSE: 0.000117, MAE: 0.009233, R²: -0.1335
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.47980 | val 0.44651
  Epoch 016 - train 0.50180 | val 0.45261
  Regression -> MSE: 0.000233, MAE: 0.012602, R²: -0.0051
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.45266 | val 0.58930
  Epoch 020 - train 0.44707 | val 0.57275
  Regression -> MSE: 0.000199, MAE: 0.008321, R²: -0.1937
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.46384 | val 0.29180
  Epoch 016 - train 0.46125 | val 0.29286
  Regression -> MSE: 0.000237, MAE: 0.011892, R²: -0.0037
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.47471 | val 0.99508
  Epoch 020 - train 0.43381 | val 0.98607
  Regression -> MSE: 0.000229, MAE: 0.009881, R²: 0.0055
  Directional -> Accuracy: 0.4884, MCC: -0.0162, F1: 0.5600

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.47698 | val 0.68461
  Epoch 016 - train 0.48660 | val 0.69616
  Regression -> MSE: 0.000139, MAE: 0.008352, R²: -0.0286
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.46092 | val 0.70691
  Epoch 020 - train 0.44380 | val 0.69619
  Regression -> MSE: 0.000193, MAE: 0.010777, R²: -0.0274
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.42851 | val 0.63247
  Epoch 020 - train 0.40197 | val 0.59348
  Regression -> MSE: 0.000274, MAE: 0.010548, R²: -0.0469
  Directional -> Accuracy: 0.5616, MCC: 0.0980, F1: 0.6279

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.47877 | val 0.37528
  Epoch 016 - train 0.47680 | val 0.37394
  Regression -> MSE: 0.000168, MAE: 0.010365, R²: -0.0051
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.40356 | val 0.52117
  Epoch 016 - train 0.39203 | val 0.52831
  Regression -> MSE: 0.000181, MAE: 0.010268, R²: -0.0040
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.45941 | val 0.43064
  Epoch 020 - train 0.43445 | val 0.41055
  Regression -> MSE: 0.000343, MAE: 0.011799, R²: -0.0008
  Directional -> Accuracy: 0.4179, MCC: -0.1089, F1: 0.2642

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.50382 | val 0.24140
  Epoch 016 - train 0.50396 | val 0.23808
  Regression -> MSE: 0.000117, MAE: 0.008335, R²: -0.1169
  Directional -> Accuracy: 0.5116, MCC: 0.0397, F1: 0.3636

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.45632 | val 0.83104
  Epoch 020 - train 0.46021 | val 0.80286
  Regression -> MSE: 0.000224, MAE: 0.011363, R²: -0.0261
  Directional -> Accuracy: 0.5088, MCC: 0.1231, F1: 0.6500

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.45620 | val 1.13566
  Epoch 020 - train 0.46237 | val 1.12719
  Regression -> MSE: 0.000092, MAE: 0.007495, R²: -0.1807
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.45360 | val 0.28218
  Epoch 016 - train 0.43801 | val 0.28292
  Regression -> MSE: 0.000313, MAE: 0.014140, R²: -0.0183
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.51526 | val 0.19709
  Epoch 016 - train 0.48187 | val 0.19923
  Regression -> MSE: 0.000249, MAE: 0.011512, R²: -0.0199
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.41925 | val 0.59524
  Epoch 020 - train 0.42692 | val 0.61294
  Regression -> MSE: 0.000083, MAE: 0.007239, R²: -0.0283
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.47941 | val 0.63015
  Epoch 020 - train 0.47922 | val 0.60617
  Regression -> MSE: 0.000307, MAE: 0.014456, R²: -0.0005
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.46844 | val 0.54338
  Epoch 016 - train 0.43846 | val 0.54507
  Regression -> MSE: 0.000098, MAE: 0.007276, R²: -0.0007
  Directional -> Accuracy: 0.4091, MCC: -0.3283, F1: 0.5667

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.48194 | val 0.73776
  Epoch 016 - train 0.46440 | val 0.74308
  Regression -> MSE: 0.000172, MAE: 0.009618, R²: 0.0005
  Directional -> Accuracy: 0.4286, MCC: -0.0338, F1: 0.5000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.44606 | val 0.58886
  Epoch 020 - train 0.42658 | val 0.58286
  Regression -> MSE: 0.000219, MAE: 0.011450, R²: 0.0161
  Directional -> Accuracy: 0.6250, MCC: 0.2607, F1: 0.7200

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.44016 | val 0.58074
  Epoch 016 - train 0.42884 | val 0.61118
  Regression -> MSE: 0.000093, MAE: 0.007645, R²: -0.0029
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.49795 | val 0.94193
  Epoch 020 - train 0.45001 | val 0.93659
  Regression -> MSE: 0.000165, MAE: 0.010340, R²: -0.0085
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.44532 | val 0.68304
  Epoch 016 - train 0.44127 | val 0.70512
  Regression -> MSE: 0.000122, MAE: 0.009002, R²: -0.0508
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.47838 | val 0.87865

[I 2026-02-22 22:40:17,987] Trial 74 finished with value: -0.011523321217832309 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.1, 'batch_size': 64, 'learning_rate': 2.73508297511815e-05, 'weight_decay': 3.211914042616003e-06, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 1.6403931140632493, 'early_stopping_min_delta': 0.006020303889538527}. Best is trial 31 with value: -0.011425014985750452.

  Epoch 016 - train 0.46698 | val 0.91202
  Regression -> MSE: 0.000243, MAE: 0.012353, R²: -0.0246
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 12
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.44476 | val 0.70757
  Epoch 016 - train 0.43844 | val 0.74510
  Regression -> MSE: 0.000252, MAE: 0.012758, R²: -0.0246
  Directional -> Accuracy: 0.4487, MCC: 0.0000, F1: 0.6195

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 88). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.43513 | val 0.42198
  Epoch 016 - train 0.46986 | val 0.42761
  Regression -> MSE: 0.000695, MAE: 0.019680, R²: -0.0057
  Directional -> Accuracy: 0.5532, MCC: 0.0000, F1: 0.7123

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 88). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.50125 | val 0.89992
  Epoch 016 - train 0.48769 | val 0.91626
  Regression -> MSE: 0.000360, MAE: 0.015196, R²: -0.0414
  Directional -> Accuracy: 0.4583, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.40045 | val 0.39101
  Epoch 020 - train 0.38959 | val 0.40171
  Epoch 022 - train 0.40796 | val 0.40291
  Regression -> MSE: 0.000356, MAE: 0.014603, R²: -0.0321
  Directional -> Accuracy: 0.4605, MCC: -0.0571, F1: 0.3881

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.45569 | val 0.44873
  Epoch 020 - train 0.45050 | val 0.41567
  Epoch 030 - train 0.46333 | val 0.40530
  Epoch 040 - train 0.43860 | val 0.40257
  Epoch 050 - train 0.43396 | val 0.39964
  Regression -> MSE: 0.000196, MAE: 0.009936, R²: 0.0228
  Directional -> Accuracy: 0.5577, MCC: 0.1782, F1: 0.4390

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.44887 | val 1.05154
  Epoch 020 - train 0.43359 | val 1.03617
  Epoch 030 - train 0.43992 | val 1.11390
  Epoch 032 - train 0.42618 | val 1.13344
  Regression -> MSE: 0.000587, MAE: 0.018658, R²: -0.0254
  Directional -> Accuracy: 0.4898, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.50180 | val 0.63507
  Epoch 016 - train 0.50656 | val 0.64332
  Regression -> MSE: 0.000248, MAE: 0.011974, R²: -0.0075
  Directional -> Accuracy: 0.6000, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 88). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 88). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.50580 | val 0.69823
  Epoch 020 - train 0.50022 | val 0.67150
  Epoch 030 - train 0.49403 | val 0.62442
  Epoch 040 - train 0.47530 | val 0.58135
  Epoch 050 - train 0.43806 | val 0.57138
  Regression -> MSE: 0.000600, MAE: 0.018995, R²: -0.0272
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.50073 | val 0.77388
  Epoch 016 - train 0.44628 | val 0.77608
  Regression -> MSE: 0.000338, MAE: 0.015020, R²: -0.0011
  Directional -> Accuracy: 0.3810, MCC: 0.0000, F1: 0.5517

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 88). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 88). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.46379 | val 0.64485
  Epoch 020 - train 0.44783 | val 0.72121
  Epoch 026 - train 0.45336 | val 0.76936
  Regression -> MSE: 0.000239, MAE: 0.011579, R²: -0.0028
  Directional -> Accuracy: 0.4930, MCC: -0.0160, F1: 0.4545

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.44235 | val 0.80371
  Epoch 016 - train 0.44668 | val 0.84240
  Regression -> MSE: 0.000306, MAE: 0.013632, R²: 0.0004
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.6400

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.50651 | val 0.57188
  Epoch 016 - train 0.48913 | val 0.57968
  Regression -> MSE: 0.000670, MAE: 0.019423, R²: -0.0001
  Directional -> Accuracy: 0.5085, MCC: 0.0000, F1: 0.6742

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.52014 | val 0.43820
  Epoch 020 - train 0.43577 | val 0.43361
  Epoch 030 - train 0.48034 | val 0.42980
  Epoch 040 - train 0.41801 | val 0.42281
  Epoch 050 - train 0.43795 | val 0.42690
  Regression -> MSE: 0.000157, MAE: 0.009678, R²: -0.0485
  Directional -> Accuracy: 0.5455, MCC: 0.1683, F1: 0.6296

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 88). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.44538 | val 0.66629
  Epoch 020 - train 0.42783 | val 0.64361
  Epoch 030 - train 0.41097 | val 0.63531
  Epoch 040 - train 0.42369 | val 0.63472
  Regression -> MSE: 0.000235, MAE: 0.011277, R²: -0.0459
  Directional -> Accuracy: 0.4677, MCC: -0.0662, F1: 0.4000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.45464 | val 1.27657
  Epoch 016 - train 0.45713 | val 1.28560
  Regression -> MSE: 0.000377, MAE: 0.016390, R²: -0.0031
  Directional -> Accuracy: 0.4717, MCC: 0.0000, F1: 0.6410

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.49760 | val 0.50315
  Epoch 016 - train 0.47726 | val 0.52945
  Regression -> MSE: 0.000107, MAE: 0.008021, R²: -0.0091
  Directional -> Accuracy: 0.4648, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.42188 | val 0.98673
  Epoch 016 - train 0.42948 | val 0.99490
  Regression -> MSE: 0.000160, MAE: 0.009913, R²: -0.0007
  Directional -> Accuracy: 0.6167, MCC: 0.0000, F1: 0.7629

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.44936 | val 0.42104
  Epoch 016 - train 0.44597 | val 0.43406
  Regression -> MSE: 0.000282, MAE: 0.013506, R²: -0.0481
  Directional -> Accuracy: 0.3896, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.43376 | val 0.78851
  Epoch 016 - train 0.42146 | val 0.85485
  Regression -> MSE: 0.000149, MAE: 0.008684, R²: -0.0110
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.7429

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 88). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.48095 | val 0.85316
  Epoch 020 - train 0.47282 | val 0.83335
  Epoch 030 - train 0.44530 | val 0.82890
  Epoch 040 - train 0.46971 | val 0.82838
  Regression -> MSE: 0.000281, MAE: 0.012179, R²: -0.2419
  Directional -> Accuracy: 0.4605, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.47012 | val 0.62662
  Epoch 016 - train 0.47488 | val 0.62724
  Regression -> MSE: 0.000149, MAE: 0.008562, R²: -0.0031
  Directional -> Accuracy: 0.6327, MCC: 0.0000, F1: 0.7750

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 88). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 88). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 88). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.44833 | val 0.51897
  Epoch 016 - train 0.41211 | val 0.53890
  Regression -> MSE: 0.000185, MAE: 0.010599, R²: -0.0448
  Directional -> Accuracy: 0.4925, MCC: -0.1213, F1: 0.6600

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.48339 | val 0.61544
  Epoch 016 - train 0.47969 | val 0.61739
  Regression -> MSE: 0.000084, MAE: 0.006952, R²: 0.0003
  Directional -> Accuracy: 0.5763, MCC: 0.0000, F1: 0.7312

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.46599 | val 0.60855
  Epoch 016 - train 0.48917 | val 0.71169
  Regression -> MSE: 0.000219, MAE: 0.011308, R²: -0.0040
  Directional -> Accuracy: 0.5373, MCC: 0.0869, F1: 0.5753

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.40953 | val 0.33650
  Epoch 020 - train 0.43228 | val 0.32816
  Epoch 030 - train 0.40832 | val 0.32756
  Epoch 032 - train 0.37605 | val 0.32647
  Regression -> MSE: 0.000098, MAE: 0.008131, R²: -0.0744
  Directional -> Accuracy: 0.5439, MCC: 0.1963, F1: 0.4091

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.48590 | val 0.20730
  Epoch 016 - train 0.50885 | val 0.20898
  Regression -> MSE: 0.000128, MAE: 0.009304, R²: -0.0157
  Directional -> Accuracy: 0.4167, MCC: -0.2634, F1: 0.1765

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.50501 | val 0.37747
  Epoch 016 - train 0.48868 | val 0.37643
  Regression -> MSE: 0.000242, MAE: 0.012909, R²: -0.0170
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.7429

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.48691 | val 0.60839
  Epoch 016 - train 0.47139 | val 0.61880
  Regression -> MSE: 0.000167, MAE: 0.007730, R²: -0.0220
  Directional -> Accuracy: 0.5517, MCC: 0.0000, F1: 0.7111

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.49279 | val 0.26081
  Epoch 016 - train 0.46725 | val 0.26303
  Regression -> MSE: 0.000236, MAE: 0.011949, R²: -0.0059
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.46010 | val 0.85198
  Epoch 016 - train 0.46773 | val 0.86192
  Regression -> MSE: 0.000252, MAE: 0.010607, R²: -0.0058
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.42160 | val 0.69909
  Epoch 016 - train 0.47292 | val 0.70154
  Regression -> MSE: 0.000134, MAE: 0.008152, R²: -0.0035
  Directional -> Accuracy: 0.5333, MCC: 0.0000, F1: 0.6957

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.47329 | val 0.64433
  Epoch 020 - train 0.47455 | val 0.62791
  Epoch 030 - train 0.46802 | val 0.62327
  Epoch 038 - train 0.44917 | val 0.62219
  Regression -> MSE: 0.000210, MAE: 0.010848, R²: -0.1159
  Directional -> Accuracy: 0.4902, MCC: 0.0169, F1: 0.3158

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.42829 | val 0.61308
  Epoch 016 - train 0.41664 | val 0.61402
  Regression -> MSE: 0.000270, MAE: 0.010648, R²: -0.0452
  Directional -> Accuracy: 0.4324, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 88). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.49811 | val 0.36332
  Epoch 016 - train 0.44220 | val 0.36715
  Regression -> MSE: 0.000164, MAE: 0.010154, R²: -0.0064
  Directional -> Accuracy: 0.5641, MCC: 0.1379, F1: 0.6047

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.44149 | val 0.52004
  Epoch 020 - train 0.42468 | val 0.49442
  Epoch 030 - train 0.43104 | val 0.51090
  Epoch 035 - train 0.41545 | val 0.51822
  Regression -> MSE: 0.000186, MAE: 0.010605, R²: -0.0166
  Directional -> Accuracy: 0.4000, MCC: -0.2004, F1: 0.5263

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.46819 | val 0.40305
  Epoch 020 - train 0.47659 | val 0.38042
  Epoch 030 - train 0.42848 | val 0.37566
  Epoch 040 - train 0.44378 | val 0.37469
  Regression -> MSE: 0.000343, MAE: 0.012287, R²: 0.0183
  Directional -> Accuracy: 0.5588, MCC: 0.1528, F1: 0.5455

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.46143 | val 0.26225
  Epoch 020 - train 0.48018 | val 0.25467
  Epoch 030 - train 0.46659 | val 0.24988
  Epoch 040 - train 0.45977 | val 0.24982
  Epoch 048 - train 0.45944 | val 0.25023
  Regression -> MSE: 0.000134, MAE: 0.008320, R²: -0.2923
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0833

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.51490 | val 0.73854
  Epoch 016 - train 0.47095 | val 0.74012
  Regression -> MSE: 0.000216, MAE: 0.011218, R²: -0.0042
  Directional -> Accuracy: 0.4483, MCC: -0.0992, F1: 0.4483

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.49280 | val 1.02061
  Epoch 016 - train 0.48762 | val 1.02092
  Regression -> MSE: 0.000088, MAE: 0.007337, R²: -0.1011
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 88). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 88). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 88). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 88). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.55525 | val 0.34997
  Epoch 016 - train 0.46261 | val 0.35221
  Regression -> MSE: 0.000351, MAE: 0.015844, R²: -0.0682
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 88). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.48299 | val 0.21737
  Epoch 016 - train 0.52080 | val 0.21775
  Regression -> MSE: 0.000242, MAE: 0.011262, R²: -0.0173
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.7000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 88). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 88). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.44008 | val 0.58826
  Epoch 016 - train 0.43125 | val 0.60166
  Regression -> MSE: 0.000081, MAE: 0.007051, R²: -0.0044
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 88). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 88). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 88). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.46564 | val 0.51603
  Epoch 016 - train 0.48998 | val 0.51602
  Regression -> MSE: 0.000366, MAE: 0.015333, R²: -0.0169
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.45559 | val 0.56471
  Epoch 016 - train 0.46498 | val 0.56306
  Regression -> MSE: 0.000097, MAE: 0.007219, R²: -0.0019
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.53335 | val 0.72996
  Epoch 016 - train 0.51968 | val 0.73266
  Regression -> MSE: 0.000181, MAE: 0.009942, R²: -0.0013
  Directional -> Accuracy: 0.4878, MCC: -0.0050, F1: 0.4324

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.45350 | val 0.57526
  Epoch 016 - train 0.44516 | val 0.60770
  Regression -> MSE: 0.000223, MAE: 0.011739, R²: -0.0142
  Directional -> Accuracy: 0.4561, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.49261 | val 0.57840
  Epoch 016 - train 0.47838 | val 0.61336
  Regression -> MSE: 0.000093, MAE: 0.007690, R²: -0.0140
  Directional -> Accuracy: 0.4828, MCC: 0.0000, F1: 0.6512

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.50694 | val 0.88633
  Epoch 016 - train 0.48554 | val 0.90008
  Regression -> MSE: 0.000161, MAE: 0.010083, R²: -0.0012
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.44862 | val 0.63804
  Epoch 016 - train 0.45226 | val 0.66457
  Regression -> MSE: 0.000118, MAE: 0.008843, R²: -0.0373
  Directional -> Accuracy: 0.4912, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.49639 | val 0.83803

[I 2026-02-22 22:41:45,446] Trial 75 finished with value: -0.011519928142575653 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 12, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.1, 'dropout': 0.5, 'batch_size': 64, 'learning_rate': 1.0209340170573111e-05, 'weight_decay': 8.920537614371311e-06, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 1.522829080826698, 'early_stopping_min_delta': 0.004877465513024297}. Best is trial 31 with value: -0.011425014985750452.

  Epoch 016 - train 0.47011 | val 0.84804
  Regression -> MSE: 0.000234, MAE: 0.012268, R²: -0.0006
  Directional -> Accuracy: 0.4839, MCC: 0.0000, F1: 0.6522

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.47816 | val 0.83913
  Epoch 016 - train 0.46279 | val 0.84875
  Regression -> MSE: 0.000257, MAE: 0.012902, R²: -0.0366
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.49876 | val 0.48805
  Epoch 020 - train 0.46902 | val 0.46296
  Regression -> MSE: 0.000696, MAE: 0.019676, R²: -0.0161
  Directional -> Accuracy: 0.5000, MCC: -0.0115, F1: 0.5490

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.46001 | val 1.02935
  Epoch 016 - train 0.50435 | val 1.03277
  Regression -> MSE: 0.000311, MAE: 0.014405, R²: -0.0041
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.40063 | val 0.41845
  Epoch 016 - train 0.39326 | val 0.43674
  Regression -> MSE: 0.000355, MAE: 0.014703, R²: -0.0176
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.46672 | val 0.50064
  Epoch 020 - train 0.45646 | val 0.45012
  Regression -> MSE: 0.000201, MAE: 0.009969, R²: 0.0134
  Directional -> Accuracy: 0.6471, MCC: 0.3202, F1: 0.6087

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.48834 | val 1.20745
  Epoch 016 - train 0.46282 | val 1.21541
  Regression -> MSE: 0.000561, MAE: 0.018182, R²: -0.0108
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.49994 | val 0.67355
  Epoch 020 - train 0.45651 | val 0.68107
  Regression -> MSE: 0.000244, MAE: 0.011864, R²: 0.0054
  Directional -> Accuracy: 0.5362, MCC: 0.0383, F1: 0.4286

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.49918 | val 0.72696
  Epoch 020 - train 0.46598 | val 0.69640
  Regression -> MSE: 0.000613, MAE: 0.019542, R²: -0.0264
  Directional -> Accuracy: 0.4773, MCC: -0.1336, F1: 0.2581

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.48835 | val 0.64956
  Epoch 016 - train 0.43984 | val 0.66645
  Regression -> MSE: 0.000385, MAE: 0.016117, R²: -0.0032
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.47479 | val 0.71747
  Epoch 016 - train 0.46983 | val 0.72488
  Regression -> MSE: 0.000242, MAE: 0.011783, R²: -0.0004
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.45954 | val 0.82181
  Epoch 016 - train 0.45236 | val 0.86423
  Regression -> MSE: 0.000312, MAE: 0.013662, R²: -0.0028
  Directional -> Accuracy: 0.5400, MCC: 0.0164, F1: 0.0800

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.50740 | val 0.62308
  Epoch 016 - train 0.48488 | val 0.63055
  Regression -> MSE: 0.000679, MAE: 0.019548, R²: -0.0020
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.47882 | val 0.53908
  Epoch 016 - train 0.45866 | val 0.56288
  Regression -> MSE: 0.000138, MAE: 0.009040, R²: -0.0016
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.43613 | val 0.72590
  Epoch 020 - train 0.41855 | val 0.70685
  Regression -> MSE: 0.000217, MAE: 0.010529, R²: 0.0363
  Directional -> Accuracy: 0.5574, MCC: 0.1142, F1: 0.6087

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.47082 | val 1.44861
  Epoch 016 - train 0.45173 | val 1.47630
  Regression -> MSE: 0.000365, MAE: 0.015979, R²: -0.0065
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.54106 | val 0.54144
  Epoch 016 - train 0.50226 | val 0.54265
  Regression -> MSE: 0.000111, MAE: 0.008242, R²: -0.0279
  Directional -> Accuracy: 0.4571, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.46398 | val 1.10433
  Epoch 016 - train 0.41723 | val 1.15840
  Regression -> MSE: 0.000161, MAE: 0.010114, R²: -0.0300
  Directional -> Accuracy: 0.5763, MCC: 0.1190, F1: 0.6479

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.47350 | val 0.51222
  Epoch 016 - train 0.49172 | val 0.63005
  Regression -> MSE: 0.000284, MAE: 0.013600, R²: -0.0427
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.40016 | val 0.72625
  Epoch 020 - train 0.39375 | val 0.70857
  Regression -> MSE: 0.000186, MAE: 0.009837, R²: -0.2408
  Directional -> Accuracy: 0.4462, MCC: -0.0140, F1: 0.3077

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.48327 | val 0.94917
  Epoch 020 - train 0.48010 | val 1.07154
  Regression -> MSE: 0.000256, MAE: 0.011419, R²: -0.1325
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.48600 | val 0.71828
  Epoch 016 - train 0.50529 | val 0.72777
  Regression -> MSE: 0.000155, MAE: 0.008902, R²: -0.0822
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.51603 | val 0.62364
  Epoch 016 - train 0.49059 | val 0.63348
  Regression -> MSE: 0.000166, MAE: 0.010713, R²: -0.0057
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.49058 | val 0.68748
  Epoch 016 - train 0.47202 | val 0.68764
  Regression -> MSE: 0.000089, MAE: 0.007230, R²: -0.0402
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.48744 | val 0.69730
  Epoch 016 - train 0.49683 | val 0.72910
  Regression -> MSE: 0.000212, MAE: 0.011138, R²: 0.0003
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.44430 | val 0.38060
  Epoch 020 - train 0.42366 | val 0.34509
  Regression -> MSE: 0.000102, MAE: 0.008269, R²: -0.1076
  Directional -> Accuracy: 0.5357, MCC: 0.1728, F1: 0.3810

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.52939 | val 0.35183
  Epoch 016 - train 0.48993 | val 0.34888
  Regression -> MSE: 0.000106, MAE: 0.008907, R²: -0.0324
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.52403 | val 0.47612
  Epoch 016 - train 0.49244 | val 0.48695
  Regression -> MSE: 0.000240, MAE: 0.012855, R²: -0.0384
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.45650 | val 0.64634
  Epoch 016 - train 0.46884 | val 0.64136
  Regression -> MSE: 0.000171, MAE: 0.007823, R²: -0.0278
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.49791 | val 0.30100
  Epoch 016 - train 0.51379 | val 0.30405
  Regression -> MSE: 0.000236, MAE: 0.011856, R²: 0.0005
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.51339 | val 1.02501
  Epoch 016 - train 0.49984 | val 1.02221
  Regression -> MSE: 0.000231, MAE: 0.009862, R²: -0.0014
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.57497 | val 0.66831
  Epoch 016 - train 0.59163 | val 0.67100
  Regression -> MSE: 0.000135, MAE: 0.008175, R²: 0.0005
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.49310 | val 0.69915
  Epoch 016 - train 0.52262 | val 0.70404
  Regression -> MSE: 0.000197, MAE: 0.010614, R²: -0.0477
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.47570 | val 0.67067
  Epoch 016 - train 0.45828 | val 0.67856
  Regression -> MSE: 0.000263, MAE: 0.010578, R²: -0.0037
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.50223 | val 0.37881
  Epoch 020 - train 0.50538 | val 0.36820
  Regression -> MSE: 0.000165, MAE: 0.010324, R²: 0.0070
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.43627 | val 0.55313
  Epoch 016 - train 0.40663 | val 0.57469
  Regression -> MSE: 0.000180, MAE: 0.010298, R²: 0.0005
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.48253 | val 0.43315
  Epoch 020 - train 0.47177 | val 0.41524
  Regression -> MSE: 0.000332, MAE: 0.011673, R²: 0.0313
  Directional -> Accuracy: 0.6119, MCC: 0.1980, F1: 0.6750

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.52357 | val 0.25783
  Epoch 016 - train 0.47924 | val 0.25292
  Regression -> MSE: 0.000124, MAE: 0.008427, R²: -0.1774
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.48371 | val 0.84127
  Epoch 016 - train 0.48479 | val 0.84052
  Regression -> MSE: 0.000219, MAE: 0.011269, R²: -0.0001
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.49335 | val 1.19379
  Epoch 016 - train 0.46368 | val 1.19194
  Regression -> MSE: 0.000091, MAE: 0.007450, R²: -0.1673
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.47983 | val 0.27953
  Epoch 016 - train 0.44546 | val 0.28068
  Regression -> MSE: 0.000312, MAE: 0.014084, R²: -0.0145
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.48712 | val 0.20041
  Epoch 016 - train 0.46369 | val 0.20043
  Regression -> MSE: 0.000252, MAE: 0.011487, R²: -0.0347
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.45410 | val 0.62499
  Epoch 016 - train 0.46623 | val 0.62795
  Regression -> MSE: 0.000081, MAE: 0.007102, R²: -0.0031
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.54305 | val 0.62843
  Epoch 020 - train 0.52735 | val 0.61219
  Regression -> MSE: 0.000305, MAE: 0.014407, R²: 0.0056
  Directional -> Accuracy: 0.5745, MCC: 0.2144, F1: 0.6970

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.43187 | val 0.57043
  Epoch 016 - train 0.47208 | val 0.56887
  Regression -> MSE: 0.000099, MAE: 0.007208, R²: -0.0057
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.51566 | val 0.76746
  Epoch 016 - train 0.46605 | val 0.76594
  Regression -> MSE: 0.000172, MAE: 0.009544, R²: -0.0030
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.43687 | val 0.61455
  Epoch 016 - train 0.45264 | val 0.69332
  Regression -> MSE: 0.000223, MAE: 0.011745, R²: 0.0009
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.47980 | val 0.62773
  Epoch 016 - train 0.44805 | val 0.64281
  Regression -> MSE: 0.000095, MAE: 0.007785, R²: -0.0254
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.50835 | val 1.05413
  Epoch 016 - train 0.51925 | val 1.11459
  Regression -> MSE: 0.000168, MAE: 0.010322, R²: -0.0262
  Directional -> Accuracy: 0.4815, MCC: 0.0000, F1: 0.0000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.47706 | val 0.69552
  Epoch 016 - train 0.47834 | val 0.69604
  Regression -> MSE: 0.000123, MAE: 0.008996, R²: -0.0590
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.51649 | val 0.92688

[I 2026-02-22 22:43:47,664] Trial 76 finished with value: -0.011449898363004354 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 64, 'learning_rate': 1.8540613503478483e-05, 'weight_decay': 2.7063350871679604e-06, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 1.819841391827203, 'early_stopping_min_delta': 0.008920105009463122}. Best is trial 31 with value: -0.011425014985750452.

  Epoch 016 - train 0.49036 | val 0.97014
  Regression -> MSE: 0.000240, MAE: 0.012339, R²: -0.0138
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.50023 | val 0.83694
  Epoch 016 - train 0.48355 | val 0.85946
  Regression -> MSE: 0.000241, MAE: 0.012328, R²: -0.0020
  Directional -> Accuracy: 0.5789, MCC: 0.1291, F1: 0.2000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.45923 | val 0.48218
  Epoch 016 - train 0.47554 | val 0.48181
  Regression -> MSE: 0.000711, MAE: 0.019904, R²: -0.0193
  Directional -> Accuracy: 0.5333, MCC: 0.0367, F1: 0.6038

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.52886 | val 1.05775
  Epoch 016 - train 0.53046 | val 1.05729
  Regression -> MSE: 0.000314, MAE: 0.014448, R²: 0.0004
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.6857

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.44155 | val 0.47329
  Epoch 016 - train 0.43551 | val 0.47839
  Regression -> MSE: 0.000364, MAE: 0.014826, R²: -0.0315
  Directional -> Accuracy: 0.4865, MCC: 0.1537, F1: 0.0952

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.46605 | val 0.45360
  Epoch 020 - train 0.48407 | val 0.42880
  Regression -> MSE: 0.000214, MAE: 0.010477, R²: -0.0394
  Directional -> Accuracy: 0.4000, MCC: -0.2202, F1: 0.4828

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.50323 | val 1.11202
  Epoch 020 - train 0.49613 | val 1.07035
  Regression -> MSE: 0.000547, MAE: 0.018203, R²: 0.0342
  Directional -> Accuracy: 0.5000, MCC: 0.0421, F1: 0.6230

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.51023 | val 0.69685
  Epoch 016 - train 0.47638 | val 0.69533
  Regression -> MSE: 0.000252, MAE: 0.011976, R²: -0.0147
  Directional -> Accuracy: 0.6029, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.48972 | val 0.39546
  Epoch 020 - train 0.51754 | val 0.37950
  Regression -> MSE: 0.000625, MAE: 0.019822, R²: -0.0223
  Directional -> Accuracy: 0.3810, MCC: -0.2340, F1: 0.3500

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.50698 | val 0.64468
  Epoch 016 - train 0.49197 | val 0.64433
  Regression -> MSE: 0.000376, MAE: 0.015611, R²: -0.0068
  Directional -> Accuracy: 0.4375, MCC: 0.0000, F1: 0.6087

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.55121 | val 0.78143
  Epoch 016 - train 0.50081 | val 0.79709
  Regression -> MSE: 0.000250, MAE: 0.011788, R²: -0.0203
  Directional -> Accuracy: 0.5797, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.44102 | val 0.87902
  Epoch 016 - train 0.42201 | val 0.93680
  Regression -> MSE: 0.000312, MAE: 0.013626, R²: 0.0009
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.51849 | val 0.63485
  Epoch 020 - train 0.50154 | val 0.61973
  Regression -> MSE: 0.000673, MAE: 0.019395, R²: 0.0188
  Directional -> Accuracy: 0.5965, MCC: 0.2309, F1: 0.6933

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.59144 | val 0.58870
  Epoch 016 - train 0.56181 | val 0.60386
  Regression -> MSE: 0.000138, MAE: 0.009024, R²: 0.0032
  Directional -> Accuracy: 0.5238, MCC: 0.0673, F1: 0.5455

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.46525 | val 0.80887
  Epoch 016 - train 0.44874 | val 0.89148
  Regression -> MSE: 0.000227, MAE: 0.010741, R²: -0.0023
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.56605 | val 1.48930
  Epoch 016 - train 0.56295 | val 1.52160
  Regression -> MSE: 0.000376, MAE: 0.015995, R²: -0.0263
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.54580 | val 0.51742
  Epoch 016 - train 0.51112 | val 0.52162
  Regression -> MSE: 0.000109, MAE: 0.008053, R²: -0.0081
  Directional -> Accuracy: 0.4638, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.51753 | val 1.16019
  Epoch 016 - train 0.50362 | val 1.18626
  Regression -> MSE: 0.000162, MAE: 0.010066, R²: -0.0257
  Directional -> Accuracy: 0.5690, MCC: -0.1135, F1: 0.7191

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.49795 | val 0.56026
  Epoch 016 - train 0.48137 | val 0.78060
  Regression -> MSE: 0.000288, MAE: 0.013735, R²: -0.0536
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.45086 | val 0.76393
  Epoch 020 - train 0.42804 | val 0.74987
  Regression -> MSE: 0.000185, MAE: 0.009514, R²: -0.2208
  Directional -> Accuracy: 0.4688, MCC: 0.0245, F1: 0.3462

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.51377 | val 1.03940
  Epoch 020 - train 0.49142 | val 1.03661
  Regression -> MSE: 0.000254, MAE: 0.011641, R²: -0.1162
  Directional -> Accuracy: 0.4189, MCC: -0.1954, F1: 0.5057

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.50444 | val 0.75728
  Epoch 016 - train 0.48159 | val 0.76787
  Regression -> MSE: 0.000153, MAE: 0.008712, R²: -0.0602
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.50119 | val 0.62533
  Epoch 016 - train 0.48131 | val 0.67099
  Regression -> MSE: 0.000173, MAE: 0.010255, R²: -0.0416
  Directional -> Accuracy: 0.6462, MCC: 0.2940, F1: 0.6761

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.52805 | val 0.69066
  Epoch 016 - train 0.51604 | val 0.71043
  Regression -> MSE: 0.000088, MAE: 0.007261, R²: -0.0182
  Directional -> Accuracy: 0.5614, MCC: 0.0981, F1: 0.6269

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.51857 | val 0.79915
  Epoch 016 - train 0.53608 | val 0.81455
  Regression -> MSE: 0.000212, MAE: 0.011036, R²: -0.0067
  Directional -> Accuracy: 0.4154, MCC: -0.1717, F1: 0.3871

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.47107 | val 0.37508
  Epoch 020 - train 0.48141 | val 0.33335
  Regression -> MSE: 0.000093, MAE: 0.007994, R²: -0.0356
  Directional -> Accuracy: 0.5818, MCC: 0.1596, F1: 0.6102

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.57513 | val 0.39298
  Epoch 016 - train 0.51849 | val 0.38941
  Regression -> MSE: 0.000109, MAE: 0.008949, R²: -0.0965
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.56259 | val 0.47802
  Epoch 016 - train 0.51213 | val 0.49785
  Regression -> MSE: 0.000238, MAE: 0.012874, R²: -0.0068
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.53938 | val 0.66153
  Epoch 016 - train 0.45437 | val 0.69695
  Regression -> MSE: 0.000178, MAE: 0.007985, R²: -0.0495
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.54788 | val 0.35426
  Epoch 016 - train 0.57552 | val 0.36487
  Regression -> MSE: 0.000246, MAE: 0.012231, R²: -0.0162
  Directional -> Accuracy: 0.5500, MCC: 0.0000, F1: 0.7097

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.50291 | val 1.13026
  Epoch 016 - train 0.52297 | val 1.13349
  Regression -> MSE: 0.000236, MAE: 0.010101, R²: -0.0023
  Directional -> Accuracy: 0.4762, MCC: 0.0000, F1: 0.6452

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.48495 | val 0.64484
  Epoch 016 - train 0.53444 | val 0.64761
  Regression -> MSE: 0.000139, MAE: 0.008411, R²: -0.0095
  Directional -> Accuracy: 0.5000, MCC: 0.0454, F1: 0.4000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.52595 | val 0.77615
  Epoch 020 - train 0.52470 | val 0.76301
  Regression -> MSE: 0.000220, MAE: 0.010916, R²: -0.2042
  Directional -> Accuracy: 0.5510, MCC: 0.1553, F1: 0.4211

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.43595 | val 0.69274
  Epoch 016 - train 0.42310 | val 0.69151
  Regression -> MSE: 0.000267, MAE: 0.010667, R²: -0.0060
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.43656 | val 0.66608
  Epoch 016 - train 0.45927 | val 0.72704
  Regression -> MSE: 0.000194, MAE: 0.010747, R²: -0.0564
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.53262 | val 0.49297
  Epoch 016 - train 0.50478 | val 0.52003
  Regression -> MSE: 0.000352, MAE: 0.012293, R²: -0.0128
  Directional -> Accuracy: 0.4242, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.53153 | val 0.26330
  Epoch 016 - train 0.51780 | val 0.26908
  Regression -> MSE: 0.000125, MAE: 0.008471, R²: -0.1783
  Directional -> Accuracy: 0.4762, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.50034 | val 0.88910
  Epoch 016 - train 0.51379 | val 0.89362
  Regression -> MSE: 0.000225, MAE: 0.011417, R²: -0.0233
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.6341

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.43005 | val 1.30467
  Epoch 016 - train 0.43080 | val 1.31100
  Regression -> MSE: 0.000089, MAE: 0.007345, R²: -0.1990
  Directional -> Accuracy: 0.3913, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.63591 | val 0.30737
  Epoch 016 - train 0.52182 | val 0.30455
  Regression -> MSE: 0.000336, MAE: 0.015181, R²: -0.0796
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.48388 | val 0.72034
  Epoch 016 - train 0.46852 | val 0.74212
  Regression -> MSE: 0.000080, MAE: 0.006880, R²: -0.0231
  Directional -> Accuracy: 0.5135, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.53361 | val 0.69934
  Epoch 016 - train 0.52021 | val 0.73834
  Regression -> MSE: 0.000301, MAE: 0.014359, R²: -0.0005
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.52488 | val 0.59256
  Epoch 016 - train 0.51642 | val 0.59036
  Regression -> MSE: 0.000102, MAE: 0.007440, R²: 0.0013
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.62989 | val 0.84802
  Epoch 016 - train 0.63024 | val 0.85826
  Regression -> MSE: 0.000177, MAE: 0.009994, R²: -0.0063
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.49045 | val 0.61214
  Epoch 016 - train 0.44365 | val 0.61899
  Regression -> MSE: 0.000228, MAE: 0.011900, R²: -0.0114
  Directional -> Accuracy: 0.3455, MCC: -0.3298, F1: 0.4194

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.53382 | val 0.66219
  Epoch 016 - train 0.53977 | val 0.66209
  Regression -> MSE: 0.000095, MAE: 0.007767, R²: -0.0089
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.55011 | val 1.08457
  Epoch 016 - train 0.55748 | val 1.10521
  Regression -> MSE: 0.000169, MAE: 0.010445, R²: -0.0147
  Directional -> Accuracy: 0.4906, MCC: 0.0000, F1: 0.0000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.46490 | val 0.72976
  Epoch 016 - train 0.45877 | val 0.76004
  Regression -> MSE: 0.000125, MAE: 0.009163, R²: -0.0644
  Directional -> Accuracy: 0.4727, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.50326 | val 0.98787

[I 2026-02-22 22:44:59,260] Trial 77 finished with value: -0.011550904747740712 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.6000000000000001, 'batch_size': 64, 'learning_rate': 1.72759901738528e-05, 'weight_decay': 2.516168570832306e-06, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 1.9358262289998724, 'early_stopping_min_delta': 0.009534139502633848}. Best is trial 31 with value: -0.011425014985750452.

  Epoch 016 - train 0.48941 | val 1.04423
  Regression -> MSE: 0.000242, MAE: 0.012476, R²: -0.0062
  Directional -> Accuracy: 0.4500, MCC: -0.1001, F1: 0.4407

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.47569 | val 0.81250
  Epoch 020 - train 0.44054 | val 0.84330
  Regression -> MSE: 0.000249, MAE: 0.012621, R²: -0.0074
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.45270 | val 0.46232
  Epoch 020 - train 0.43466 | val 0.46537
  Regression -> MSE: 0.000704, MAE: 0.019676, R²: -0.0278
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.50505 | val 1.02140
  Epoch 020 - train 0.48248 | val 1.01285
  Regression -> MSE: 0.000314, MAE: 0.014433, R²: -0.0108
  Directional -> Accuracy: 0.5532, MCC: 0.0961, F1: 0.6038

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.39080 | val 0.42212
  Epoch 020 - train 0.38787 | val 0.45682
  Regression -> MSE: 0.000361, MAE: 0.014778, R²: -0.0325
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.46416 | val 0.48167
  Epoch 020 - train 0.43609 | val 0.45674
  Regression -> MSE: 0.000197, MAE: 0.009883, R²: 0.0303
  Directional -> Accuracy: 0.7059, MCC: 0.4919, F1: 0.6341

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.48740 | val 1.23285
  Epoch 020 - train 0.45483 | val 1.20608
  Regression -> MSE: 0.000585, MAE: 0.018638, R²: -0.0533
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.47128 | val 0.66968
  Epoch 020 - train 0.48521 | val 0.66837
  Regression -> MSE: 0.000243, MAE: 0.011833, R²: 0.0085
  Directional -> Accuracy: 0.5507, MCC: 0.0631, F1: 0.4364

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.46551 | val 0.66468
  Epoch 020 - train 0.44936 | val 0.66919
  Regression -> MSE: 0.000611, MAE: 0.019483, R²: -0.0220
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.47725 | val 0.60970
  Epoch 020 - train 0.46550 | val 0.65388
  Regression -> MSE: 0.000391, MAE: 0.015903, R²: -0.0204
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.48538 | val 0.71935
  Epoch 020 - train 0.44177 | val 0.77724
  Regression -> MSE: 0.000246, MAE: 0.011629, R²: -0.0209
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.46200 | val 0.85229
  Epoch 020 - train 0.44880 | val 1.07623
  Regression -> MSE: 0.000310, MAE: 0.013689, R²: 0.0016
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.6301

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.48483 | val 0.63451
  Epoch 020 - train 0.47540 | val 0.65241
  Regression -> MSE: 0.000677, MAE: 0.019462, R²: 0.0010
  Directional -> Accuracy: 0.6034, MCC: 0.2739, F1: 0.7013

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.45510 | val 0.50187
  Epoch 020 - train 0.45168 | val 0.56553
  Regression -> MSE: 0.000144, MAE: 0.009464, R²: -0.0410
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.41541 | val 0.73074
  Epoch 020 - train 0.42727 | val 0.75307
  Regression -> MSE: 0.000225, MAE: 0.010697, R²: -0.0011
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.44015 | val 1.44442
  Epoch 020 - train 0.43951 | val 1.50968
  Regression -> MSE: 0.000364, MAE: 0.015996, R²: -0.0047
  Directional -> Accuracy: 0.5769, MCC: 0.2160, F1: 0.1538

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.49104 | val 0.51484
  Epoch 020 - train 0.47037 | val 0.54533
  Regression -> MSE: 0.000108, MAE: 0.007955, R²: -0.0016
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.47897 | val 1.08839
  Epoch 020 - train 0.45189 | val 1.16005
  Regression -> MSE: 0.000162, MAE: 0.010212, R²: -0.0416
  Directional -> Accuracy: 0.3729, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.47882 | val 0.52145
  Epoch 020 - train 0.48586 | val 0.97474
  Regression -> MSE: 0.000274, MAE: 0.013121, R²: -0.0071
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.37052 | val 0.77293
  Epoch 020 - train 0.39709 | val 0.72186
  Regression -> MSE: 0.000226, MAE: 0.011459, R²: -0.5094
  Directional -> Accuracy: 0.4154, MCC: -0.0306, F1: 0.0500

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.46963 | val 0.94187
  Epoch 020 - train 0.42985 | val 0.96539
  Regression -> MSE: 0.000397, MAE: 0.015302, R²: -0.7534
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.45845 | val 0.74051
  Epoch 020 - train 0.44402 | val 0.72648
  Regression -> MSE: 0.000148, MAE: 0.008644, R²: -0.0335
  Directional -> Accuracy: 0.5208, MCC: -0.0337, F1: 0.6230

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.44749 | val 0.60987
  Epoch 020 - train 0.45250 | val 0.60698
  Regression -> MSE: 0.000165, MAE: 0.010544, R²: 0.0004
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.46263 | val 0.67432
  Epoch 020 - train 0.47727 | val 0.69555
  Regression -> MSE: 0.000086, MAE: 0.007099, R²: -0.0059
  Directional -> Accuracy: 0.5517, MCC: 0.0951, F1: 0.5938

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.47118 | val 0.68458
  Epoch 020 - train 0.47448 | val 0.89794
  Regression -> MSE: 0.000212, MAE: 0.011278, R²: 0.0005
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.41305 | val 0.35816
  Epoch 020 - train 0.40354 | val 0.32896
  Regression -> MSE: 0.000096, MAE: 0.008067, R²: -0.0413
  Directional -> Accuracy: 0.5714, MCC: 0.2385, F1: 0.4545

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.54354 | val 0.34528
  Epoch 020 - train 0.49806 | val 0.34200
  Regression -> MSE: 0.000103, MAE: 0.008735, R²: -0.0019
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.50348 | val 0.47336
  Epoch 020 - train 0.47688 | val 0.46525
  Regression -> MSE: 0.000241, MAE: 0.012886, R²: -0.0433
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.43730 | val 0.61295
  Epoch 020 - train 0.44002 | val 0.61036
  Regression -> MSE: 0.000193, MAE: 0.008240, R²: -0.1587
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.46207 | val 0.33527
  Epoch 020 - train 0.51135 | val 0.34202
  Regression -> MSE: 0.000240, MAE: 0.012006, R²: -0.0131
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.45030 | val 1.02503
  Epoch 020 - train 0.48047 | val 1.03743
  Regression -> MSE: 0.000230, MAE: 0.009861, R²: 0.0012
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.47770 | val 0.69894
  Epoch 020 - train 0.44644 | val 0.71427
  Regression -> MSE: 0.000138, MAE: 0.008313, R²: -0.0255
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.45046 | val 0.70393
  Epoch 020 - train 0.43587 | val 0.76250
  Regression -> MSE: 0.000194, MAE: 0.010453, R²: -0.0282
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.41649 | val 0.62422
  Epoch 020 - train 0.38266 | val 0.61475
  Regression -> MSE: 0.000284, MAE: 0.011170, R²: -0.0828
  Directional -> Accuracy: 0.4521, MCC: -0.0046, F1: 0.2000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.45922 | val 0.36206
  Epoch 020 - train 0.42721 | val 0.35889
  Regression -> MSE: 0.000166, MAE: 0.010362, R²: 0.0025
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.40880 | val 0.55311
  Epoch 020 - train 0.40897 | val 0.59867
  Regression -> MSE: 0.000181, MAE: 0.010338, R²: -0.0032
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.46177 | val 0.43276
  Epoch 020 - train 0.43549 | val 0.44234
  Regression -> MSE: 0.000334, MAE: 0.011660, R²: 0.0263
  Directional -> Accuracy: 0.5672, MCC: 0.1149, F1: 0.6234

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.46235 | val 0.25125
  Epoch 020 - train 0.45051 | val 0.23861
  Regression -> MSE: 0.000120, MAE: 0.008288, R²: -0.1404
  Directional -> Accuracy: 0.6279, MCC: 0.2817, F1: 0.5556

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.46567 | val 0.83945
  Epoch 020 - train 0.46425 | val 0.85090
  Regression -> MSE: 0.000219, MAE: 0.011282, R²: -0.0011
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.44352 | val 1.18450
  Epoch 020 - train 0.43381 | val 1.19333
  Regression -> MSE: 0.000095, MAE: 0.007598, R²: -0.2208
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.44116 | val 0.28837
  Epoch 020 - train 0.44174 | val 0.28771
  Regression -> MSE: 0.000314, MAE: 0.014171, R²: -0.0194
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.55221 | val 0.19904
  Epoch 020 - train 0.46984 | val 0.20769
  Regression -> MSE: 0.000246, MAE: 0.011541, R²: -0.0087
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.0000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.48952 | val 0.63109
  Epoch 020 - train 0.43415 | val 0.66271
  Regression -> MSE: 0.000085, MAE: 0.007060, R²: -0.0558
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.50561 | val 0.62853
  Epoch 020 - train 0.47209 | val 0.62437
  Regression -> MSE: 0.000308, MAE: 0.014510, R²: -0.0031
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.45354 | val 0.54691
  Epoch 020 - train 0.44729 | val 0.54301
  Regression -> MSE: 0.000098, MAE: 0.007367, R²: -0.0027
  Directional -> Accuracy: 0.4318, MCC: 0.0000, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.49385 | val 0.78393
  Epoch 020 - train 0.45184 | val 0.78720
  Regression -> MSE: 0.000174, MAE: 0.010069, R²: -0.0125
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.42035 | val 0.63141
  Epoch 020 - train 0.42389 | val 0.69168
  Regression -> MSE: 0.000230, MAE: 0.011889, R²: -0.0313
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.45172 | val 0.62644
  Epoch 020 - train 0.47380 | val 0.70796
  Regression -> MSE: 0.000095, MAE: 0.007794, R²: -0.0260
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.47579 | val 0.98673
  Epoch 020 - train 0.47614 | val 1.07015
  Regression -> MSE: 0.000164, MAE: 0.010260, R²: -0.0008
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.43979 | val 0.69392
  Epoch 020 - train 0.45315 | val 0.80476
  Regression -> MSE: 0.000125, MAE: 0.009036, R²: -0.0795
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.47692 | val 0.92319

[I 2026-02-22 22:47:25,430] Trial 78 finished with value: -0.011581822359758819 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.5, 'batch_size': 64, 'learning_rate': 5.6926223923894594e-05, 'weight_decay': 6.896853526165756e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 1.7887230316709202, 'early_stopping_min_delta': 0.009084946875360008}. Best is trial 31 with value: -0.011425014985750452.

  Epoch 020 - train 0.45631 | val 1.10377
  Regression -> MSE: 0.000238, MAE: 0.012337, R²: -0.0037
  Directional -> Accuracy: 0.5246, MCC: 0.0091, F1: 0.0645

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 12
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.52271 | val 0.82773
  Epoch 011 - train 0.52933 | val 0.84838
  Regression -> MSE: 0.000265, MAE: 0.013149, R²: -0.0780
  Directional -> Accuracy: 0.4487, MCC: 0.0000, F1: 0.6195

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 88). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.58109 | val 0.46251
  Epoch 011 - train 0.51532 | val 0.46270
  Regression -> MSE: 0.000691, MAE: 0.019590, R²: 0.0006
  Directional -> Accuracy: 0.5532, MCC: 0.0000, F1: 0.7123

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 88). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.57178 | val 0.93961
  Epoch 011 - train 0.53320 | val 0.94022
  Regression -> MSE: 0.000348, MAE: 0.015031, R²: -0.0076
  Directional -> Accuracy: 0.5417, MCC: 0.0000, F1: 0.7027

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.44550 | val 0.44270
  Epoch 011 - train 0.45355 | val 0.45247
  Regression -> MSE: 0.000348, MAE: 0.014466, R²: -0.0081
  Directional -> Accuracy: 0.5395, MCC: 0.0000, F1: 0.7009

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.55704 | val 0.44702
  Epoch 011 - train 0.57919 | val 0.44807
  Regression -> MSE: 0.000201, MAE: 0.010102, R²: 0.0001
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.55816 | val 1.09242
  Epoch 020 - train 0.49135 | val 1.07216
  Epoch 024 - train 0.54843 | val 1.08626
  Regression -> MSE: 0.000593, MAE: 0.018752, R²: -0.0365
  Directional -> Accuracy: 0.4898, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.51022 | val 0.64807
  Epoch 011 - train 0.50829 | val 0.64719
  Regression -> MSE: 0.000246, MAE: 0.012177, R²: 0.0001
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.5714

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 88). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 88). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.57197 | val 0.66960
  Epoch 011 - train 0.56595 | val 0.67082
  Regression -> MSE: 0.000603, MAE: 0.019200, R²: -0.0314
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.49389 | val 0.81455
  Epoch 011 - train 0.45821 | val 0.81559
  Regression -> MSE: 0.000340, MAE: 0.015245, R²: -0.0064
  Directional -> Accuracy: 0.3810, MCC: 0.0000, F1: 0.5517

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 88). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 88). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.51581 | val 0.68280
  Epoch 011 - train 0.49812 | val 0.68443
  Regression -> MSE: 0.000238, MAE: 0.011753, R²: -0.0001
  Directional -> Accuracy: 0.4366, MCC: 0.0000, F1: 0.6078

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.50730 | val 0.81263
  Epoch 011 - train 0.51588 | val 0.81017
  Regression -> MSE: 0.000305, MAE: 0.013597, R²: 0.0017
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.6400

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.57207 | val 0.59695
  Epoch 011 - train 0.56006 | val 0.59918
  Regression -> MSE: 0.000682, MAE: 0.019835, R²: -0.0182
  Directional -> Accuracy: 0.5085, MCC: 0.0000, F1: 0.6742

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.58118 | val 0.45628
  Epoch 011 - train 0.58496 | val 0.45907
  Regression -> MSE: 0.000151, MAE: 0.009651, R²: -0.0056
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 88). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.52323 | val 0.68221
  Epoch 020 - train 0.45761 | val 0.67890
  Regression -> MSE: 0.000224, MAE: 0.010653, R²: 0.0042
  Directional -> Accuracy: 0.5645, MCC: 0.1754, F1: 0.3415

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.53374 | val 1.35252
  Epoch 011 - train 0.52334 | val 1.35424
  Regression -> MSE: 0.000387, MAE: 0.016319, R²: -0.0295
  Directional -> Accuracy: 0.5283, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.54137 | val 0.49684
  Epoch 020 - train 0.55391 | val 0.48738
  Epoch 027 - train 0.52948 | val 0.48811
  Regression -> MSE: 0.000108, MAE: 0.007926, R²: -0.0164
  Directional -> Accuracy: 0.5493, MCC: 0.0693, F1: 0.6735

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.59281 | val 1.05678
  Epoch 011 - train 0.52733 | val 1.06070
  Regression -> MSE: 0.000162, MAE: 0.010130, R²: -0.0114
  Directional -> Accuracy: 0.6167, MCC: 0.0000, F1: 0.7629

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.52689 | val 0.42495
  Epoch 011 - train 0.53908 | val 0.42887
  Regression -> MSE: 0.000269, MAE: 0.012906, R²: -0.0006
  Directional -> Accuracy: 0.6104, MCC: 0.0000, F1: 0.7581

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.48766 | val 0.73742
  Epoch 011 - train 0.44802 | val 0.74241
  Regression -> MSE: 0.000162, MAE: 0.008933, R²: -0.0974
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 88). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.57687 | val 0.92959
  Epoch 011 - train 0.56868 | val 0.93007
  Regression -> MSE: 0.000238, MAE: 0.011080, R²: -0.0483
  Directional -> Accuracy: 0.4605, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.55071 | val 0.66445
  Epoch 011 - train 0.54781 | val 0.66866
  Regression -> MSE: 0.000151, MAE: 0.008717, R²: -0.0207
  Directional -> Accuracy: 0.6327, MCC: 0.0000, F1: 0.7750

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 88). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 88). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 88). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.51597 | val 0.52903
  Epoch 011 - train 0.49843 | val 0.53048
  Regression -> MSE: 0.000184, MAE: 0.010583, R²: -0.0415
  Directional -> Accuracy: 0.4925, MCC: -0.0206, F1: 0.5641

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.53151 | val 0.66310
  Epoch 011 - train 0.55054 | val 0.66286
  Regression -> MSE: 0.000084, MAE: 0.006900, R²: -0.0072
  Directional -> Accuracy: 0.5763, MCC: 0.0000, F1: 0.7312

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.55178 | val 0.63516
  Epoch 011 - train 0.54482 | val 0.63618
  Regression -> MSE: 0.000221, MAE: 0.011285, R²: -0.0129
  Directional -> Accuracy: 0.5224, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.48433 | val 0.32770
  Epoch 011 - train 0.50273 | val 0.32796
  Regression -> MSE: 0.000094, MAE: 0.008132, R²: -0.0298
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.69821 | val 0.19631
  Epoch 011 - train 0.62226 | val 0.19653
  Regression -> MSE: 0.000137, MAE: 0.009653, R²: -0.0917
  Directional -> Accuracy: 0.4167, MCC: 0.0000, F1: 0.5882

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.52879 | val 0.38972
  Epoch 011 - train 0.49869 | val 0.38995
  Regression -> MSE: 0.000239, MAE: 0.012799, R²: -0.0054
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.7429

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.51885 | val 0.62167
  Epoch 011 - train 0.51474 | val 0.62052
  Regression -> MSE: 0.000168, MAE: 0.007742, R²: -0.0260
  Directional -> Accuracy: 0.5517, MCC: 0.0000, F1: 0.7111

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.56465 | val 0.25099
  Epoch 011 - train 0.54662 | val 0.25206
  Regression -> MSE: 0.000235, MAE: 0.011921, R²: -0.0011
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.57034 | val 0.85823
  Epoch 020 - train 0.59893 | val 0.84853
  Epoch 026 - train 0.51733 | val 0.85884
  Regression -> MSE: 0.000259, MAE: 0.010723, R²: -0.0356
  Directional -> Accuracy: 0.4444, MCC: -0.1425, F1: 0.5614

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.48642 | val 0.73754
  Epoch 011 - train 0.53014 | val 0.73722
  Regression -> MSE: 0.000133, MAE: 0.008168, R²: -0.0010
  Directional -> Accuracy: 0.5333, MCC: 0.0000, F1: 0.6957

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.51788 | val 0.69689
  Epoch 011 - train 0.51427 | val 0.69915
  Regression -> MSE: 0.000190, MAE: 0.010405, R²: -0.0096
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.51875 | val 0.69915
  Epoch 011 - train 0.53943 | val 0.70781
  Regression -> MSE: 0.000262, MAE: 0.010512, R²: -0.0130
  Directional -> Accuracy: 0.5676, MCC: 0.0000, F1: 0.7241

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 88). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.53650 | val 0.40769
  Epoch 011 - train 0.54096 | val 0.40818
  Regression -> MSE: 0.000166, MAE: 0.010240, R²: -0.0238
  Directional -> Accuracy: 0.4872, MCC: 0.0000, F1: 0.6552

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.50103 | val 0.51137
  Epoch 020 - train 0.52152 | val 0.49142
  Epoch 030 - train 0.47503 | val 0.49997
  Regression -> MSE: 0.000195, MAE: 0.010724, R²: -0.0667
  Directional -> Accuracy: 0.5333, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.49686 | val 0.40217
  Epoch 020 - train 0.48188 | val 0.39080
  Epoch 024 - train 0.48397 | val 0.39084
  Regression -> MSE: 0.000362, MAE: 0.012854, R²: -0.0369
  Directional -> Accuracy: 0.4265, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.56615 | val 0.26159
  Epoch 011 - train 0.53135 | val 0.26106
  Regression -> MSE: 0.000113, MAE: 0.008223, R²: -0.0946
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.50132 | val 0.76889
  Epoch 011 - train 0.49400 | val 0.76859
  Regression -> MSE: 0.000215, MAE: 0.011149, R²: -0.0014
  Directional -> Accuracy: 0.5345, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.54347 | val 1.09096
  Epoch 011 - train 0.55972 | val 1.08932
  Regression -> MSE: 0.000085, MAE: 0.007202, R²: -0.0624
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 88). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 88). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 88). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 88). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.59082 | val 0.28244
  Epoch 011 - train 0.61111 | val 0.28218
  Regression -> MSE: 0.000328, MAE: 0.013935, R²: 0.0002
  Directional -> Accuracy: 0.6500, MCC: 0.0000, F1: 0.0000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 88). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.52555 | val 0.21302
  Epoch 011 - train 0.56117 | val 0.21366
  Regression -> MSE: 0.000242, MAE: 0.011301, R²: -0.0151
  Directional -> Accuracy: 0.4872, MCC: 0.1502, F1: 0.0909

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 88). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 88). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.55699 | val 0.60648
  Epoch 020 - train 0.54672 | val 0.58876
  Epoch 024 - train 0.55125 | val 0.58927
  Regression -> MSE: 0.000087, MAE: 0.007147, R²: -0.0887
  Directional -> Accuracy: 0.5526, MCC: 0.1291, F1: 0.3704

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 88). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 88). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 88). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.53347 | val 0.48169
  Epoch 020 - train 0.56661 | val 0.46639
  Epoch 023 - train 0.53612 | val 0.47005
  Regression -> MSE: 0.000367, MAE: 0.015504, R²: -0.0200
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.51802 | val 0.57229
  Epoch 011 - train 0.49505 | val 0.57242
  Regression -> MSE: 0.000096, MAE: 0.007277, R²: 0.0021
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.59171 | val 0.85442
  Epoch 011 - train 0.53442 | val 0.85582
  Regression -> MSE: 0.000185, MAE: 0.010566, R²: -0.0227
  Directional -> Accuracy: 0.3659, MCC: 0.0000, F1: 0.5357

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.48204 | val 0.58018
  Epoch 011 - train 0.46738 | val 0.58254
  Regression -> MSE: 0.000220, MAE: 0.011630, R²: -0.0028
  Directional -> Accuracy: 0.5439, MCC: 0.0000, F1: 0.7045

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.54416 | val 0.63571
  Epoch 011 - train 0.54606 | val 0.64179
  Regression -> MSE: 0.000095, MAE: 0.007838, R²: -0.0379
  Directional -> Accuracy: 0.4828, MCC: 0.0000, F1: 0.6512

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.58026 | val 0.95261
  Epoch 011 - train 0.53820 | val 0.95569
  Regression -> MSE: 0.000161, MAE: 0.010136, R²: -0.0043
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.57490 | val 0.68542
  Epoch 011 - train 0.57953 | val 0.69032
  Regression -> MSE: 0.000118, MAE: 0.008850, R²: -0.0332
  Directional -> Accuracy: 0.4386, MCC: -0.1300, F1: 0.2727

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...

[I 2026-02-22 22:48:12,755] Trial 79 finished with value: -0.011498044921054527 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 12, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 64, 'learning_rate': 6.9681045095997124e-06, 'weight_decay': 4.164164107613228e-06, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.7314467480033344, 'early_stopping_min_delta': 0.0099917491308145}. Best is trial 31 with value: -0.011425014985750452.

  Epoch 010 - train 0.53236 | val 0.87735
  Epoch 011 - train 0.55129 | val 0.87589
  Regression -> MSE: 0.000235, MAE: 0.012289, R²: -0.0080
  Directional -> Accuracy: 0.3871, MCC: -0.2403, F1: 0.5000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.45118 | val 0.82951
  Epoch 016 - train 0.43807 | val 0.88883
  Regression -> MSE: 0.000248, MAE: 0.012552, R²: -0.0013
  Directional -> Accuracy: 0.4935, MCC: 0.1347, F1: 0.6355

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.49282 | val 0.48094
  Epoch 020 - train 0.43271 | val 0.45493
  Regression -> MSE: 0.000685, MAE: 0.019306, R²: 0.0001
  Directional -> Accuracy: 0.5435, MCC: 0.0447, F1: 0.6316

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.49156 | val 1.03065
  Epoch 020 - train 0.46402 | val 1.00958
  Regression -> MSE: 0.000319, MAE: 0.014664, R²: -0.0281
  Directional -> Accuracy: 0.4681, MCC: -0.2449, F1: 0.6377

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.40184 | val 0.50325
  Epoch 016 - train 0.38966 | val 0.61980
  Regression -> MSE: 0.000398, MAE: 0.015420, R²: -0.1399
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.48389 | val 0.48499
  Epoch 016 - train 0.44312 | val 0.49119
  Regression -> MSE: 0.000202, MAE: 0.010103, R²: 0.0100
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.42598 | val 1.19929
  Epoch 020 - train 0.43114 | val 1.18572
  Regression -> MSE: 0.000562, MAE: 0.018245, R²: -0.0125
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.47604 | val 0.68344
  Epoch 020 - train 0.45789 | val 0.68799
  Regression -> MSE: 0.000242, MAE: 0.011738, R²: 0.0122
  Directional -> Accuracy: 0.6232, MCC: 0.1659, F1: 0.3500

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.46680 | val 0.71839
  Epoch 016 - train 0.47787 | val 0.71562
  Regression -> MSE: 0.000626, MAE: 0.019838, R²: -0.0482
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.47199 | val 0.59101
  Epoch 016 - train 0.47304 | val 0.59083
  Regression -> MSE: 0.000411, MAE: 0.016255, R²: -0.0705
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.47194 | val 0.73251
  Epoch 016 - train 0.44442 | val 0.77653
  Regression -> MSE: 0.000241, MAE: 0.011908, R²: 0.0021
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.44330 | val 0.93561
  Epoch 016 - train 0.43882 | val 1.23611
  Regression -> MSE: 0.000312, MAE: 0.013823, R²: -0.0025
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.6301

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.47805 | val 0.65496
  Epoch 016 - train 0.45169 | val 0.71382
  Regression -> MSE: 0.000677, MAE: 0.019424, R²: 0.0011
  Directional -> Accuracy: 0.5345, MCC: 0.1890, F1: 0.1290

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.44552 | val 0.58007
  Epoch 016 - train 0.42771 | val 0.69070
  Regression -> MSE: 0.000139, MAE: 0.009014, R²: -0.0025
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.44549 | val 0.74167
  Epoch 016 - train 0.41868 | val 0.73526
  Regression -> MSE: 0.000225, MAE: 0.010707, R²: -0.0018
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.45207 | val 1.46266
  Epoch 016 - train 0.44959 | val 1.50098
  Regression -> MSE: 0.000363, MAE: 0.016139, R²: -0.0023
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.48493 | val 0.52488
  Epoch 016 - train 0.47270 | val 0.52827
  Regression -> MSE: 0.000112, MAE: 0.007978, R²: -0.0371
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.45794 | val 1.11858
  Epoch 020 - train 0.43476 | val 1.04490
  Regression -> MSE: 0.000165, MAE: 0.010172, R²: -0.0584
  Directional -> Accuracy: 0.5254, MCC: 0.2408, F1: 0.4400

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.47801 | val 0.51217
  Epoch 016 - train 0.45627 | val 0.57915
  Regression -> MSE: 0.000277, MAE: 0.013290, R²: -0.0189
  Directional -> Accuracy: 0.4737, MCC: -0.1966, F1: 0.6154

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.37697 | val 0.76074
  Epoch 016 - train 0.39003 | val 0.77143
  Regression -> MSE: 0.000160, MAE: 0.008849, R²: -0.0669
  Directional -> Accuracy: 0.5385, MCC: 0.1561, F1: 0.4828

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.47035 | val 0.96674
  Epoch 020 - train 0.42765 | val 0.99703
  Regression -> MSE: 0.000234, MAE: 0.011078, R²: -0.0351
  Directional -> Accuracy: 0.4267, MCC: -0.1731, F1: 0.5057

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.51166 | val 0.81183
  Epoch 016 - train 0.50616 | val 0.87768
  Regression -> MSE: 0.000144, MAE: 0.008344, R²: -0.0070
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.46144 | val 0.60278
  Epoch 016 - train 0.43026 | val 0.61948
  Regression -> MSE: 0.000164, MAE: 0.010300, R²: 0.0049
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.49905 | val 0.69356
  Epoch 016 - train 0.47517 | val 0.69165
  Regression -> MSE: 0.000085, MAE: 0.007042, R²: 0.0050
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.47528 | val 0.70806
  Epoch 016 - train 0.47308 | val 0.71532
  Regression -> MSE: 0.000215, MAE: 0.011060, R²: -0.0158
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.43267 | val 0.36597
  Epoch 020 - train 0.39843 | val 0.34369
  Regression -> MSE: 0.000099, MAE: 0.008245, R²: -0.0732
  Directional -> Accuracy: 0.4821, MCC: -0.0359, F1: 0.5085

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.52976 | val 0.34413
  Epoch 016 - train 0.55748 | val 0.34033
  Regression -> MSE: 0.000103, MAE: 0.008716, R²: -0.0010
  Directional -> Accuracy: 0.5870, MCC: 0.1700, F1: 0.0952

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.52334 | val 0.48907
  Epoch 016 - train 0.50645 | val 0.52728
  Regression -> MSE: 0.000238, MAE: 0.012764, R²: -0.0281
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.47211 | val 0.65248
  Epoch 020 - train 0.44333 | val 0.61470
  Regression -> MSE: 0.000197, MAE: 0.008406, R²: -0.1864
  Directional -> Accuracy: 0.4737, MCC: 0.0359, F1: 0.2857

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.51411 | val 0.29349
  Epoch 016 - train 0.50335 | val 0.29346
  Regression -> MSE: 0.000237, MAE: 0.011885, R²: -0.0040
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.46168 | val 1.06506
  Epoch 016 - train 0.46761 | val 1.08667
  Regression -> MSE: 0.000232, MAE: 0.009938, R²: -0.0064
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.54363 | val 0.73624
  Epoch 016 - train 0.47766 | val 0.75325
  Regression -> MSE: 0.000144, MAE: 0.008644, R²: -0.0638
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.48624 | val 0.70765
  Epoch 016 - train 0.45780 | val 0.74490
  Regression -> MSE: 0.000198, MAE: 0.010649, R²: -0.0511
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.38881 | val 0.62762
  Epoch 020 - train 0.39097 | val 0.61918
  Regression -> MSE: 0.000312, MAE: 0.011871, R²: -0.1897
  Directional -> Accuracy: 0.5479, MCC: 0.1851, F1: 0.4407

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.45002 | val 0.36086
  Epoch 020 - train 0.45169 | val 0.36682
  Regression -> MSE: 0.000163, MAE: 0.010328, R²: 0.0242
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.40433 | val 0.55002
  Epoch 016 - train 0.40776 | val 0.55744
  Regression -> MSE: 0.000180, MAE: 0.010301, R²: -0.0017
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.46065 | val 0.41096
  Epoch 020 - train 0.44681 | val 0.41952
  Regression -> MSE: 0.000332, MAE: 0.011687, R²: 0.0309
  Directional -> Accuracy: 0.6418, MCC: 0.2704, F1: 0.6842

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.49749 | val 0.23554
  Epoch 016 - train 0.46234 | val 0.23473
  Regression -> MSE: 0.000113, MAE: 0.008305, R²: -0.0704
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.45795 | val 0.84142
  Epoch 016 - train 0.45598 | val 0.90437
  Regression -> MSE: 0.000219, MAE: 0.011288, R²: -0.0004
  Directional -> Accuracy: 0.5263, MCC: 0.0101, F1: 0.0690

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.46435 | val 1.19657
  Epoch 016 - train 0.44190 | val 1.23026
  Regression -> MSE: 0.000086, MAE: 0.007231, R²: -0.1026
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.49891 | val 0.28867
  Epoch 016 - train 0.44201 | val 0.28637
  Regression -> MSE: 0.000315, MAE: 0.014239, R²: -0.0253
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.48591 | val 0.19852
  Epoch 016 - train 0.44106 | val 0.20596
  Regression -> MSE: 0.000248, MAE: 0.011543, R²: -0.0160
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.0000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.43287 | val 0.62450
  Epoch 020 - train 0.41040 | val 0.62743
  Regression -> MSE: 0.000082, MAE: 0.007146, R²: -0.0190
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.50510 | val 0.64769
  Epoch 016 - train 0.48171 | val 0.66404
  Regression -> MSE: 0.000309, MAE: 0.014516, R²: -0.0074
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.47338 | val 0.61272
  Epoch 016 - train 0.45511 | val 0.61041
  Regression -> MSE: 0.000101, MAE: 0.007127, R²: -0.0267
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.47952 | val 0.79106
  Epoch 016 - train 0.48926 | val 0.79450
  Regression -> MSE: 0.000173, MAE: 0.009944, R²: -0.0075
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.42093 | val 0.62083
  Epoch 016 - train 0.41916 | val 0.65507
  Regression -> MSE: 0.000225, MAE: 0.011827, R²: -0.0094
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.43697 | val 0.65720
  Epoch 016 - train 0.44836 | val 0.72826
  Regression -> MSE: 0.000093, MAE: 0.007708, R²: -0.0109
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.53260 | val 1.10403
  Epoch 016 - train 0.49835 | val 1.17997
  Regression -> MSE: 0.000170, MAE: 0.010364, R²: -0.0390
  Directional -> Accuracy: 0.4815, MCC: 0.0000, F1: 0.0000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.45798 | val 0.73264
  Epoch 016 - train 0.45104 | val 0.88155
  Regression -> MSE: 0.000127, MAE: 0.009053, R²: -0.0931
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.48724 | val 0.95525

[I 2026-02-22 22:49:11,093] Trial 80 finished with value: -0.011465351311930754 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.4, 'batch_size': 64, 'learning_rate': 3.931678079643095e-05, 'weight_decay': 1.2299242115244662e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 1.8392825629472904, 'early_stopping_min_delta': 0.008331507506416758}. Best is trial 31 with value: -0.011425014985750452.

  Epoch 016 - train 0.46342 | val 1.04843
  Regression -> MSE: 0.000236, MAE: 0.012294, R²: 0.0052
  Directional -> Accuracy: 0.5410, MCC: 0.1055, F1: 0.6000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.46089 | val 0.86953
  Epoch 016 - train 0.45228 | val 0.88036
  Regression -> MSE: 0.000248, MAE: 0.012550, R²: -0.0010
  Directional -> Accuracy: 0.4416, MCC: -0.2484, F1: 0.0851

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.48320 | val 0.46891
  Epoch 016 - train 0.46766 | val 0.47961
  Regression -> MSE: 0.000715, MAE: 0.019926, R²: -0.0442
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.48234 | val 1.05885
  Epoch 016 - train 0.48046 | val 1.06246
  Regression -> MSE: 0.000310, MAE: 0.014422, R²: -0.0004
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.38408 | val 0.50027
  Epoch 016 - train 0.38029 | val 0.53610
  Regression -> MSE: 0.000361, MAE: 0.014774, R²: -0.0323
  Directional -> Accuracy: 0.4667, MCC: 0.0160, F1: 0.1667

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.47716 | val 0.46768
  Epoch 020 - train 0.44953 | val 0.43863
  Regression -> MSE: 0.000211, MAE: 0.010249, R²: -0.0344
  Directional -> Accuracy: 0.5294, MCC: 0.0119, F1: 0.6842

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.46751 | val 1.23456
  Epoch 020 - train 0.41747 | val 1.22214
  Regression -> MSE: 0.000616, MAE: 0.019539, R²: -0.1101
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.49705 | val 0.73181
  Epoch 016 - train 0.48228 | val 0.72307
  Regression -> MSE: 0.000251, MAE: 0.011945, R²: -0.0228
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.46850 | val 0.71324
  Epoch 020 - train 0.46517 | val 0.68105
  Regression -> MSE: 0.000608, MAE: 0.019289, R²: -0.0174
  Directional -> Accuracy: 0.6818, MCC: 0.3320, F1: 0.5882

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.43625 | val 0.62847
  Epoch 016 - train 0.42893 | val 0.67245
  Regression -> MSE: 0.000391, MAE: 0.015899, R²: -0.0203
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.45141 | val 0.74585
  Epoch 016 - train 0.44044 | val 0.77509
  Regression -> MSE: 0.000244, MAE: 0.011677, R²: -0.0109
  Directional -> Accuracy: 0.5571, MCC: -0.1043, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.41232 | val 0.91659
  Epoch 016 - train 0.40749 | val 1.13852
  Regression -> MSE: 0.000311, MAE: 0.013737, R²: -0.0013
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.6301

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.48230 | val 0.62618
  Epoch 016 - train 0.46575 | val 0.68962
  Regression -> MSE: 0.000684, MAE: 0.019779, R²: -0.0102
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.46794 | val 0.50950
  Epoch 016 - train 0.44545 | val 0.56900
  Regression -> MSE: 0.000146, MAE: 0.009567, R²: -0.0583
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.44032 | val 0.73770
  Epoch 016 - train 0.40618 | val 0.74496
  Regression -> MSE: 0.000227, MAE: 0.010738, R²: -0.0085
  Directional -> Accuracy: 0.4918, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.48269 | val 1.53611
  Epoch 016 - train 0.45628 | val 1.63006
  Regression -> MSE: 0.000363, MAE: 0.016239, R²: -0.0031
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.49795 | val 0.52904
  Epoch 016 - train 0.47008 | val 0.53319
  Regression -> MSE: 0.000110, MAE: 0.007961, R²: -0.0229
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.43448 | val 1.13672
  Epoch 020 - train 0.42408 | val 1.25743
  Regression -> MSE: 0.000157, MAE: 0.009990, R²: -0.0084
  Directional -> Accuracy: 0.5254, MCC: 0.0036, F1: 0.6111

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.48874 | val 0.51110
  Epoch 016 - train 0.45506 | val 0.57170
  Regression -> MSE: 0.000273, MAE: 0.013046, R²: -0.0045
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.37354 | val 0.73939
  Epoch 020 - train 0.36991 | val 0.75253
  Regression -> MSE: 0.000211, MAE: 0.010899, R²: -0.4100
  Directional -> Accuracy: 0.4615, MCC: 0.0668, F1: 0.2553

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.44666 | val 1.00196
  Epoch 020 - train 0.42957 | val 1.03839
  Regression -> MSE: 0.000288, MAE: 0.012334, R²: -0.2747
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.51380 | val 0.82697
  Epoch 016 - train 0.49432 | val 0.81877
  Regression -> MSE: 0.000147, MAE: 0.008465, R²: -0.0226
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.43891 | val 0.60229
  Epoch 016 - train 0.43537 | val 0.61954
  Regression -> MSE: 0.000167, MAE: 0.010333, R²: -0.0097
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.47069 | val 0.70546
  Epoch 016 - train 0.45009 | val 0.71403
  Regression -> MSE: 0.000085, MAE: 0.007055, R²: -0.0006
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.45361 | val 0.75721
  Epoch 016 - train 0.46933 | val 0.85773
  Regression -> MSE: 0.000212, MAE: 0.011081, R²: -0.0004
  Directional -> Accuracy: 0.4848, MCC: 0.1167, F1: 0.6458

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.41809 | val 0.35523
  Epoch 020 - train 0.38875 | val 0.32646
  Regression -> MSE: 0.000104, MAE: 0.008239, R²: -0.1276
  Directional -> Accuracy: 0.5179, MCC: 0.0797, F1: 0.4490

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.50115 | val 0.36594
  Epoch 020 - train 0.47477 | val 0.35237
  Regression -> MSE: 0.000105, MAE: 0.008769, R²: -0.0160
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.51107 | val 0.47341
  Epoch 016 - train 0.49477 | val 0.48321
  Regression -> MSE: 0.000232, MAE: 0.012533, R²: -0.0014
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.45428 | val 0.63915
  Epoch 016 - train 0.42750 | val 0.63772
  Regression -> MSE: 0.000178, MAE: 0.007968, R²: -0.0717
  Directional -> Accuracy: 0.3684, MCC: -0.2349, F1: 0.2174

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.50398 | val 0.32493
  Epoch 020 - train 0.46579 | val 0.31461
  Regression -> MSE: 0.000234, MAE: 0.011974, R²: 0.0121
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.48978 | val 1.09643
  Epoch 016 - train 0.45889 | val 1.09872
  Regression -> MSE: 0.000231, MAE: 0.009950, R²: -0.0042
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.49655 | val 0.70802
  Epoch 016 - train 0.47841 | val 0.71301
  Regression -> MSE: 0.000138, MAE: 0.008281, R²: -0.0211
  Directional -> Accuracy: 0.4884, MCC: 0.0323, F1: 0.2667

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.47424 | val 0.73839
  Epoch 016 - train 0.46863 | val 0.78975
  Regression -> MSE: 0.000197, MAE: 0.010610, R²: -0.0456
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.40811 | val 0.64779
  Epoch 020 - train 0.39138 | val 0.63235
  Regression -> MSE: 0.000329, MAE: 0.012148, R²: -0.2577
  Directional -> Accuracy: 0.5342, MCC: 0.1602, F1: 0.4138

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.45900 | val 0.36685
  Epoch 020 - train 0.44388 | val 0.35453
  Regression -> MSE: 0.000161, MAE: 0.010245, R²: 0.0340
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.41116 | val 0.60113
  Epoch 016 - train 0.43314 | val 0.62059
  Regression -> MSE: 0.000187, MAE: 0.010621, R²: -0.0394
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.43512 | val 0.43158
  Epoch 020 - train 0.41908 | val 0.44052
  Regression -> MSE: 0.000350, MAE: 0.012745, R²: -0.0216
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.50498 | val 0.24721
  Epoch 016 - train 0.48488 | val 0.24411
  Regression -> MSE: 0.000119, MAE: 0.008371, R²: -0.1310
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.47409 | val 0.87177
  Epoch 016 - train 0.45782 | val 0.88846
  Regression -> MSE: 0.000219, MAE: 0.011277, R²: -0.0002
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.46572 | val 1.25777
  Epoch 016 - train 0.45608 | val 1.30837
  Regression -> MSE: 0.000083, MAE: 0.007107, R²: -0.0702
  Directional -> Accuracy: 0.5532, MCC: -0.1299, F1: 0.7042

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.46450 | val 0.28121
  Epoch 016 - train 0.47381 | val 0.28169
  Regression -> MSE: 0.000313, MAE: 0.014124, R²: -0.0164
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.54081 | val 0.18319
  Epoch 016 - train 0.47761 | val 0.18024
  Regression -> MSE: 0.000247, MAE: 0.011573, R²: -0.0149
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.0000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.43981 | val 0.63526
  Epoch 016 - train 0.43368 | val 0.64285
  Regression -> MSE: 0.000081, MAE: 0.007054, R²: -0.0045
  Directional -> Accuracy: 0.4800, MCC: -0.0463, F1: 0.3810

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.51514 | val 0.72050
  Epoch 016 - train 0.49852 | val 0.72548
  Regression -> MSE: 0.000315, MAE: 0.014518, R²: -0.0273
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.47522 | val 0.61345
  Epoch 016 - train 0.44016 | val 0.61128
  Regression -> MSE: 0.000101, MAE: 0.007117, R²: -0.0301
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.49428 | val 0.81351
  Epoch 016 - train 0.45739 | val 0.82158
  Regression -> MSE: 0.000172, MAE: 0.009755, R²: -0.0035
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.44659 | val 0.74143
  Epoch 016 - train 0.43324 | val 1.10824
  Regression -> MSE: 0.000229, MAE: 0.011881, R²: -0.0278
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.45595 | val 0.64549
  Epoch 016 - train 0.44033 | val 0.69471
  Regression -> MSE: 0.000093, MAE: 0.007698, R²: -0.0105
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.48273 | val 1.06553
  Epoch 016 - train 0.47200 | val 1.17541
  Regression -> MSE: 0.000164, MAE: 0.010238, R²: 0.0013
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.45635 | val 0.77476
  Epoch 016 - train 0.43701 | val 0.85424
  Regression -> MSE: 0.000121, MAE: 0.008952, R²: -0.0411
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.48612 | val 1.00625

[I 2026-02-22 22:50:08,312] Trial 81 finished with value: -0.011553661308622554 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.4, 'batch_size': 64, 'learning_rate': 4.508241294780077e-05, 'weight_decay': 1.1341655827623438e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 1.98650743802817, 'early_stopping_min_delta': 0.00971422748388695}. Best is trial 31 with value: -0.011425014985750452.

  Epoch 016 - train 0.49044 | val 1.02356
  Regression -> MSE: 0.000238, MAE: 0.012437, R²: -0.0039
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.47023 | val 0.90561
  Epoch 016 - train 0.45087 | val 0.91354
  Regression -> MSE: 0.000257, MAE: 0.012929, R²: -0.0392
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.53728 | val 0.45523
  Epoch 020 - train 0.48285 | val 0.46362
  Regression -> MSE: 0.000731, MAE: 0.020303, R²: -0.0679
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.47938 | val 1.05350
  Epoch 016 - train 0.50009 | val 1.05741
  Regression -> MSE: 0.000313, MAE: 0.014454, R²: -0.0092
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.41928 | val 0.44398
  Epoch 016 - train 0.40202 | val 0.49810
  Regression -> MSE: 0.000350, MAE: 0.014605, R²: -0.0019
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.46347 | val 0.49292
  Epoch 020 - train 0.45642 | val 0.48971
  Regression -> MSE: 0.000201, MAE: 0.009983, R²: 0.0134
  Directional -> Accuracy: 0.5098, MCC: -0.0242, F1: 0.6377

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.47441 | val 1.31532
  Epoch 016 - train 0.47214 | val 1.40167
  Regression -> MSE: 0.000590, MAE: 0.018736, R²: -0.0627
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.48558 | val 0.71148
  Epoch 016 - train 0.48857 | val 0.72289
  Regression -> MSE: 0.000250, MAE: 0.011933, R²: -0.0198
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.46054 | val 0.78612
  Epoch 020 - train 0.47859 | val 0.74848
  Regression -> MSE: 0.000614, MAE: 0.019437, R²: -0.0278
  Directional -> Accuracy: 0.5909, MCC: 0.1538, F1: 0.5000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.54686 | val 0.59978
  Epoch 016 - train 0.52167 | val 0.60740
  Regression -> MSE: 0.000411, MAE: 0.016261, R²: -0.0723
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.49290 | val 0.77378
  Epoch 016 - train 0.47856 | val 0.75135
  Regression -> MSE: 0.000243, MAE: 0.011763, R²: -0.0057
  Directional -> Accuracy: 0.4714, MCC: -0.0088, F1: 0.5195

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.47092 | val 0.77995
  Epoch 016 - train 0.44597 | val 0.83448
  Regression -> MSE: 0.000326, MAE: 0.013619, R²: -0.0489
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.50276 | val 0.70883
  Epoch 016 - train 0.50575 | val 0.80994
  Regression -> MSE: 0.000688, MAE: 0.019551, R²: -0.0161
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.52420 | val 0.53463
  Epoch 016 - train 0.46123 | val 0.55904
  Regression -> MSE: 0.000138, MAE: 0.009057, R²: 0.0010
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.43273 | val 0.71791
  Epoch 016 - train 0.41136 | val 0.72768
  Regression -> MSE: 0.000228, MAE: 0.010787, R²: -0.0158
  Directional -> Accuracy: 0.4918, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.47181 | val 1.50167
  Epoch 016 - train 0.49730 | val 1.53945
  Regression -> MSE: 0.000362, MAE: 0.016134, R²: -0.0003
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.50314 | val 0.53198
  Epoch 016 - train 0.48761 | val 0.54222
  Regression -> MSE: 0.000109, MAE: 0.007950, R²: -0.0073
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.56923 | val 1.17612
  Epoch 016 - train 0.51704 | val 1.35599
  Regression -> MSE: 0.000167, MAE: 0.010424, R²: -0.0741
  Directional -> Accuracy: 0.3729, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.49433 | val 0.49605
  Epoch 020 - train 0.48333 | val 0.50615
  Regression -> MSE: 0.000272, MAE: 0.013113, R²: 0.0008
  Directional -> Accuracy: 0.5789, MCC: 0.0194, F1: 0.7091

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.39699 | val 0.75056
  Epoch 020 - train 0.37942 | val 0.72409
  Regression -> MSE: 0.000223, MAE: 0.011398, R²: -0.4920
  Directional -> Accuracy: 0.4615, MCC: 0.0914, F1: 0.2222

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.44334 | val 1.01935
  Epoch 020 - train 0.46707 | val 1.25087
  Regression -> MSE: 0.000300, MAE: 0.012660, R²: -0.3278
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.49563 | val 0.75495
  Epoch 020 - train 0.47381 | val 0.73960
  Regression -> MSE: 0.000148, MAE: 0.008583, R²: -0.0352
  Directional -> Accuracy: 0.6042, MCC: -0.1130, F1: 0.7532

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.45314 | val 0.63320
  Epoch 016 - train 0.43572 | val 0.62886
  Regression -> MSE: 0.000167, MAE: 0.010738, R²: -0.0112
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.51231 | val 0.70378
  Epoch 016 - train 0.48059 | val 0.72168
  Regression -> MSE: 0.000084, MAE: 0.007027, R²: 0.0088
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.49907 | val 0.96494
  Epoch 016 - train 0.47673 | val 1.08107
  Regression -> MSE: 0.000214, MAE: 0.011170, R²: -0.0094
  Directional -> Accuracy: 0.4545, MCC: -0.0861, F1: 0.6170

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.42615 | val 0.38821
  Epoch 020 - train 0.40220 | val 0.36706
  Regression -> MSE: 0.000107, MAE: 0.008478, R²: -0.1573
  Directional -> Accuracy: 0.4821, MCC: 0.0435, F1: 0.2927

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.53000 | val 0.35493
  Epoch 016 - train 0.51956 | val 0.35622
  Regression -> MSE: 0.000104, MAE: 0.008766, R²: -0.0070
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.53978 | val 0.46428
  Epoch 020 - train 0.49662 | val 0.46849
  Regression -> MSE: 0.000233, MAE: 0.012593, R²: -0.0052
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.46255 | val 0.61436
  Epoch 020 - train 0.45166 | val 0.58011
  Regression -> MSE: 0.000261, MAE: 0.011102, R²: -0.5668
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.49015 | val 0.28895
  Epoch 016 - train 0.49059 | val 0.28798
  Regression -> MSE: 0.000238, MAE: 0.011912, R²: -0.0050
  Directional -> Accuracy: 0.5122, MCC: 0.0416, F1: 0.4737

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.46414 | val 1.04969
  Epoch 020 - train 0.46271 | val 1.03322
  Regression -> MSE: 0.000230, MAE: 0.010007, R²: 0.0006
  Directional -> Accuracy: 0.4651, MCC: -0.0691, F1: 0.5818

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.47834 | val 0.69964
  Epoch 016 - train 0.47293 | val 0.71400
  Regression -> MSE: 0.000136, MAE: 0.008255, R²: -0.0049
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.49215 | val 0.71464
  Epoch 016 - train 0.46842 | val 0.72087
  Regression -> MSE: 0.000196, MAE: 0.010548, R²: -0.0415
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.45766 | val 0.65206
  Epoch 016 - train 0.42616 | val 0.66597
  Regression -> MSE: 0.000270, MAE: 0.010644, R²: -0.0312
  Directional -> Accuracy: 0.5753, MCC: 0.3173, F1: 0.4151

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.46086 | val 0.36476
  Epoch 016 - train 0.49549 | val 0.36443
  Regression -> MSE: 0.000167, MAE: 0.010357, R²: -0.0047
  Directional -> Accuracy: 0.5526, MCC: 0.1291, F1: 0.6531

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.43804 | val 0.53864
  Epoch 016 - train 0.42559 | val 0.55533
  Regression -> MSE: 0.000181, MAE: 0.010310, R²: -0.0055
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.45186 | val 0.43919
  Epoch 020 - train 0.43575 | val 0.43306
  Regression -> MSE: 0.000361, MAE: 0.013253, R²: -0.0531
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.52237 | val 0.25599
  Epoch 016 - train 0.49282 | val 0.25103
  Regression -> MSE: 0.000123, MAE: 0.008427, R²: -0.1732
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.46478 | val 0.84581
  Epoch 020 - train 0.45222 | val 0.89661
  Regression -> MSE: 0.000221, MAE: 0.011281, R²: -0.0102
  Directional -> Accuracy: 0.5263, MCC: 0.0358, F1: 0.4000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.51436 | val 1.22401
  Epoch 016 - train 0.49672 | val 1.22420
  Regression -> MSE: 0.000082, MAE: 0.007052, R²: -0.0544
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.49915 | val 0.30541
  Epoch 016 - train 0.44555 | val 0.31111
  Regression -> MSE: 0.000318, MAE: 0.014394, R²: -0.0338
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.48979 | val 0.21670
  Epoch 016 - train 0.46841 | val 0.22657
  Regression -> MSE: 0.000252, MAE: 0.011458, R²: -0.0356
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.44804 | val 0.64976
  Epoch 016 - train 0.45346 | val 0.66254
  Regression -> MSE: 0.000084, MAE: 0.007053, R²: -0.0399
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.51596 | val 0.62955
  Epoch 020 - train 0.50639 | val 0.62764
  Regression -> MSE: 0.000319, MAE: 0.014638, R²: -0.0404
  Directional -> Accuracy: 0.4681, MCC: -0.0620, F1: 0.2857

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.46717 | val 0.58601
  Epoch 016 - train 0.48530 | val 0.58128
  Regression -> MSE: 0.000100, MAE: 0.007180, R²: -0.0137
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.49536 | val 0.78835
  Epoch 016 - train 0.50337 | val 0.79028
  Regression -> MSE: 0.000172, MAE: 0.009573, R²: -0.0032
  Directional -> Accuracy: 0.6122, MCC: 0.0687, F1: 0.1739

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.42938 | val 0.63478
  Epoch 016 - train 0.43154 | val 0.84807
  Regression -> MSE: 0.000223, MAE: 0.011715, R²: 0.0014
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.49610 | val 0.61229
  Epoch 016 - train 0.46828 | val 0.66496
  Regression -> MSE: 0.000093, MAE: 0.007660, R²: -0.0077
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.46968 | val 1.02961
  Epoch 016 - train 0.47280 | val 1.04633
  Regression -> MSE: 0.000164, MAE: 0.010287, R²: -0.0045
  Directional -> Accuracy: 0.5370, MCC: 0.1425, F1: 0.6914

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.47385 | val 0.70611
  Epoch 020 - train 0.45114 | val 0.69276
  Regression -> MSE: 0.000150, MAE: 0.009526, R²: -0.2910
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.49262 | val 0.98481

[I 2026-02-22 22:51:06,882] Trial 82 finished with value: -0.011631109386699754 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 64, 'learning_rate': 2.1864356595590895e-05, 'weight_decay': 2.160111455689417e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 1.9122874353712966, 'early_stopping_min_delta': 0.008897675623236973}. Best is trial 31 with value: -0.011425014985750452.

  Epoch 016 - train 0.47119 | val 1.02978
  Regression -> MSE: 0.000237, MAE: 0.012473, R²: -0.0011
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.46489 | val 0.89731
  Epoch 016 - train 0.44360 | val 0.91401
  Regression -> MSE: 0.000263, MAE: 0.013083, R²: -0.0635
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.46099 | val 0.46047
  Epoch 020 - train 0.46929 | val 0.44812
  Regression -> MSE: 0.000672, MAE: 0.019366, R²: 0.0189
  Directional -> Accuracy: 0.6087, MCC: 0.2137, F1: 0.6400

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.49195 | val 1.05784
  Epoch 016 - train 0.46801 | val 1.07420
  Regression -> MSE: 0.000318, MAE: 0.014489, R²: -0.0260
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.37896 | val 0.54839
  Epoch 016 - train 0.38481 | val 0.89199
  Regression -> MSE: 0.000353, MAE: 0.014635, R²: -0.0107
  Directional -> Accuracy: 0.5867, MCC: 0.1582, F1: 0.7103

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.49227 | val 0.46721
  Epoch 020 - train 0.43983 | val 0.44979
  Regression -> MSE: 0.000202, MAE: 0.009941, R²: 0.0102
  Directional -> Accuracy: 0.5882, MCC: 0.1674, F1: 0.6667

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.44481 | val 1.23728
  Epoch 016 - train 0.42546 | val 1.26720
  Regression -> MSE: 0.000561, MAE: 0.018185, R²: -0.0110
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.47822 | val 0.68676
  Epoch 020 - train 0.46431 | val 0.70648
  Regression -> MSE: 0.000244, MAE: 0.011996, R²: 0.0054
  Directional -> Accuracy: 0.5507, MCC: -0.0374, F1: 0.2051

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.50041 | val 0.71144
  Epoch 020 - train 0.47470 | val 0.70062
  Regression -> MSE: 0.000621, MAE: 0.019704, R²: -0.0401
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.45801 | val 0.60666
  Epoch 016 - train 0.45936 | val 0.62865
  Regression -> MSE: 0.000402, MAE: 0.016090, R²: -0.0477
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.45794 | val 0.76764
  Epoch 016 - train 0.44701 | val 0.84361
  Regression -> MSE: 0.000243, MAE: 0.011631, R²: -0.0085
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.43009 | val 0.93089
  Epoch 016 - train 0.42435 | val 1.04807
  Regression -> MSE: 0.000310, MAE: 0.013832, R²: 0.0028
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.6301

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.49441 | val 0.69457
  Epoch 016 - train 0.47001 | val 0.81413
  Regression -> MSE: 0.000677, MAE: 0.019441, R²: 0.0001
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.46598 | val 0.54303
  Epoch 016 - train 0.46698 | val 0.56945
  Regression -> MSE: 0.000139, MAE: 0.009039, R²: -0.0072
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.42911 | val 0.70130
  Epoch 020 - train 0.39505 | val 0.71618
  Regression -> MSE: 0.000231, MAE: 0.010947, R²: -0.0252
  Directional -> Accuracy: 0.4918, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.45442 | val 1.51580
  Epoch 016 - train 0.42905 | val 1.65751
  Regression -> MSE: 0.000363, MAE: 0.016009, R²: -0.0028
  Directional -> Accuracy: 0.5385, MCC: 0.1809, F1: 0.6471

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.47454 | val 0.51953
  Epoch 016 - train 0.46872 | val 0.53234
  Regression -> MSE: 0.000108, MAE: 0.008070, R²: -0.0031
  Directional -> Accuracy: 0.4857, MCC: 0.1024, F1: 0.1429

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.45607 | val 1.11336
  Epoch 016 - train 0.44681 | val 1.23718
  Regression -> MSE: 0.000161, MAE: 0.010121, R²: -0.0306
  Directional -> Accuracy: 0.3729, MCC: -0.0884, F1: 0.1395

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.46851 | val 0.51529
  Epoch 016 - train 0.47440 | val 0.63331
  Regression -> MSE: 0.000272, MAE: 0.012995, R²: 0.0014
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.39046 | val 0.81026
  Epoch 016 - train 0.38272 | val 0.83123
  Regression -> MSE: 0.000155, MAE: 0.008776, R²: -0.0382
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.48800 | val 0.97755
  Epoch 020 - train 0.45190 | val 1.08723
  Regression -> MSE: 0.000251, MAE: 0.011286, R²: -0.1079
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.48220 | val 0.74481
  Epoch 020 - train 0.45987 | val 0.70905
  Regression -> MSE: 0.000183, MAE: 0.010205, R²: -0.2783
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.43822 | val 0.57812
  Epoch 016 - train 0.42800 | val 0.58636
  Regression -> MSE: 0.000172, MAE: 0.010259, R²: -0.0408
  Directional -> Accuracy: 0.5455, MCC: 0.0937, F1: 0.5946

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.47991 | val 0.68956
  Epoch 016 - train 0.47705 | val 0.72313
  Regression -> MSE: 0.000090, MAE: 0.007297, R²: -0.0554
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.48379 | val 0.73845
  Epoch 016 - train 0.45886 | val 0.87692
  Regression -> MSE: 0.000215, MAE: 0.011048, R²: -0.0151
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.44854 | val 0.36714
  Epoch 020 - train 0.41786 | val 0.33067
  Regression -> MSE: 0.000105, MAE: 0.008315, R²: -0.1359
  Directional -> Accuracy: 0.5179, MCC: 0.1373, F1: 0.3415

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.52764 | val 0.34545
  Epoch 016 - train 0.51685 | val 0.34225
  Regression -> MSE: 0.000104, MAE: 0.008789, R²: -0.0088
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.52694 | val 0.47758
  Epoch 016 - train 0.50465 | val 0.47392
  Regression -> MSE: 0.000232, MAE: 0.012492, R²: -0.0036
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.42751 | val 0.62704
  Epoch 020 - train 0.45034 | val 0.59034
  Regression -> MSE: 0.000195, MAE: 0.008218, R²: -0.1700
  Directional -> Accuracy: 0.4912, MCC: -0.0199, F1: 0.5246

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.48880 | val 0.34738
  Epoch 016 - train 0.44751 | val 0.35552
  Regression -> MSE: 0.000241, MAE: 0.012043, R²: -0.0199
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.50074 | val 1.05727
  Epoch 020 - train 0.43849 | val 1.05347
  Regression -> MSE: 0.000231, MAE: 0.009882, R²: -0.0032
  Directional -> Accuracy: 0.4651, MCC: -0.0660, F1: 0.5490

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.44368 | val 0.68255
  Epoch 016 - train 0.43550 | val 0.71119
  Regression -> MSE: 0.000135, MAE: 0.008168, R²: 0.0018
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.46423 | val 0.71953
  Epoch 016 - train 0.44147 | val 0.76207
  Regression -> MSE: 0.000197, MAE: 0.010615, R²: -0.0489
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.40872 | val 0.64561
  Epoch 016 - train 0.39451 | val 0.63725
  Regression -> MSE: 0.000271, MAE: 0.010658, R²: -0.0351
  Directional -> Accuracy: 0.4658, MCC: -0.1602, F1: 0.5979

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.44315 | val 0.35984
  Epoch 020 - train 0.43614 | val 0.36184
  Regression -> MSE: 0.000161, MAE: 0.010292, R²: 0.0311
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.43542 | val 0.52875
  Epoch 016 - train 0.39846 | val 0.52993
  Regression -> MSE: 0.000182, MAE: 0.010332, R²: -0.0123
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.43919 | val 0.44428
  Epoch 020 - train 0.41363 | val 0.44675
  Regression -> MSE: 0.000371, MAE: 0.013347, R²: -0.0837
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.51223 | val 0.23434
  Epoch 016 - train 0.50370 | val 0.23324
  Regression -> MSE: 0.000113, MAE: 0.008333, R²: -0.0786
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.46545 | val 0.84924
  Epoch 016 - train 0.44912 | val 0.84869
  Regression -> MSE: 0.000218, MAE: 0.011327, R²: 0.0004
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.51461 | val 1.22156
  Epoch 016 - train 0.45222 | val 1.23357
  Regression -> MSE: 0.000085, MAE: 0.007190, R²: -0.0933
  Directional -> Accuracy: 0.3830, MCC: -0.0734, F1: 0.1212

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.49153 | val 0.34505
  Epoch 016 - train 0.52745 | val 0.35629
  Regression -> MSE: 0.000327, MAE: 0.014875, R²: -0.0626
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.52291 | val 0.20047
  Epoch 016 - train 0.45586 | val 0.20852
  Regression -> MSE: 0.000247, MAE: 0.011517, R²: -0.0148
  Directional -> Accuracy: 0.4737, MCC: -0.0882, F1: 0.5833

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.46791 | val 0.63054
  Epoch 016 - train 0.44225 | val 0.63136
  Regression -> MSE: 0.000081, MAE: 0.007117, R²: -0.0051
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.48675 | val 0.64455
  Epoch 020 - train 0.47296 | val 0.61598
  Regression -> MSE: 0.000313, MAE: 0.014630, R²: -0.0201
  Directional -> Accuracy: 0.4894, MCC: -0.0065, F1: 0.1429

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.49071 | val 0.57928
  Epoch 016 - train 0.47304 | val 0.57516
  Regression -> MSE: 0.000100, MAE: 0.007198, R²: -0.0154
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.48585 | val 0.78541
  Epoch 016 - train 0.48342 | val 0.78946
  Regression -> MSE: 0.000172, MAE: 0.009709, R²: 0.0009
  Directional -> Accuracy: 0.3878, MCC: -0.1018, F1: 0.5000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.42228 | val 0.61668
  Epoch 020 - train 0.40784 | val 0.61533
  Regression -> MSE: 0.000225, MAE: 0.011500, R²: -0.0093
  Directional -> Accuracy: 0.6429, MCC: 0.2831, F1: 0.7143

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.46146 | val 0.59714
  Epoch 020 - train 0.47756 | val 0.61838
  Regression -> MSE: 0.000094, MAE: 0.007688, R²: -0.0188
  Directional -> Accuracy: 0.4561, MCC: -0.0710, F1: 0.5867

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.52680 | val 1.03192
  Epoch 016 - train 0.48903 | val 1.10500
  Regression -> MSE: 0.000164, MAE: 0.010277, R²: -0.0018
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.45537 | val 0.68495
  Epoch 016 - train 0.44608 | val 0.72314
  Regression -> MSE: 0.000126, MAE: 0.009049, R²: -0.0829
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.48980 | val 0.95042

[I 2026-02-22 22:52:06,269] Trial 83 finished with value: -0.011486089341770646 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.4, 'batch_size': 64, 'learning_rate': 3.437250897579637e-05, 'weight_decay': 6.35695010521085e-06, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 1.867471437577312, 'early_stopping_min_delta': 0.008514779382605281}. Best is trial 31 with value: -0.011425014985750452.

  Epoch 016 - train 0.49774 | val 1.00649
  Regression -> MSE: 0.000239, MAE: 0.012298, R²: -0.0070
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.46863 | val 0.86709
  Epoch 016 - train 0.46977 | val 1.16663
  Regression -> MSE: 0.000247, MAE: 0.012501, R²: 0.0023
  Directional -> Accuracy: 0.5584, MCC: 0.2275, F1: 0.6531

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.44888 | val 0.46315
  Epoch 016 - train 0.47744 | val 0.45977
  Regression -> MSE: 0.000687, MAE: 0.019402, R²: -0.0041
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.57192 | val 1.01762
  Epoch 016 - train 0.52840 | val 1.04070
  Regression -> MSE: 0.000332, MAE: 0.014663, R²: -0.0706
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.42807 | val 0.41242
  Epoch 016 - train 0.40605 | val 0.49392
  Regression -> MSE: 0.000363, MAE: 0.014790, R²: -0.0381
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.48857 | val 0.44322
  Epoch 020 - train 0.46214 | val 0.41545
  Regression -> MSE: 0.000195, MAE: 0.009522, R²: 0.0426
  Directional -> Accuracy: 0.6471, MCC: 0.2917, F1: 0.6667

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.47173 | val 1.22360
  Epoch 016 - train 0.44587 | val 1.26935
  Regression -> MSE: 0.000586, MAE: 0.018668, R²: -0.0549
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.51273 | val 0.66971
  Epoch 016 - train 0.50831 | val 0.66552
  Regression -> MSE: 0.000246, MAE: 0.012073, R²: -0.0039
  Directional -> Accuracy: 0.4348, MCC: 0.0227, F1: 0.5618

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.50979 | val 0.81482
  Epoch 016 - train 0.47662 | val 0.85921
  Regression -> MSE: 0.000670, MAE: 0.020523, R²: -0.1214
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.51761 | val 0.59697
  Epoch 016 - train 0.48040 | val 0.59680
  Regression -> MSE: 0.000392, MAE: 0.016057, R²: -0.0211
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.51621 | val 0.76402
  Epoch 016 - train 0.52918 | val 0.90207
  Regression -> MSE: 0.000247, MAE: 0.011660, R²: -0.0243
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.42849 | val 0.80105
  Epoch 016 - train 0.44003 | val 0.85324
  Regression -> MSE: 0.000313, MAE: 0.013634, R²: -0.0060
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.50643 | val 0.61223
  Epoch 016 - train 0.51279 | val 0.65092
  Regression -> MSE: 0.000686, MAE: 0.019848, R²: -0.0123
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.47805 | val 0.52861
  Epoch 016 - train 0.48109 | val 0.60795
  Regression -> MSE: 0.000138, MAE: 0.009152, R²: -0.0014
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.41739 | val 0.70580
  Epoch 016 - train 0.40789 | val 0.71806
  Regression -> MSE: 0.000229, MAE: 0.010782, R²: -0.0190
  Directional -> Accuracy: 0.5082, MCC: 0.1270, F1: 0.0625

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.46192 | val 1.37490
  Epoch 016 - train 0.49822 | val 1.40113
  Regression -> MSE: 0.000363, MAE: 0.016167, R²: -0.0037
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.51940 | val 0.49467
  Epoch 016 - train 0.51088 | val 0.48926
  Regression -> MSE: 0.000108, MAE: 0.008015, R²: -0.0019
  Directional -> Accuracy: 0.4714, MCC: -0.0791, F1: 0.5432

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.47093 | val 1.20329
  Epoch 016 - train 0.45631 | val 1.37411
  Regression -> MSE: 0.000158, MAE: 0.009551, R²: -0.0124
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.47352 | val 0.51517
  Epoch 016 - train 0.46687 | val 0.61581
  Regression -> MSE: 0.000287, MAE: 0.013712, R²: -0.0549
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.47552 | val 0.81870
  Epoch 016 - train 0.45854 | val 0.91188
  Regression -> MSE: 0.000185, MAE: 0.009801, R²: -0.2346
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.46902 | val 0.90926
  Epoch 016 - train 0.48386 | val 0.90177
  Regression -> MSE: 0.000245, MAE: 0.011156, R²: -0.0831
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.48574 | val 0.68154
  Epoch 020 - train 0.48893 | val 0.68717
  Regression -> MSE: 0.000152, MAE: 0.008834, R²: -0.0594
  Directional -> Accuracy: 0.4583, MCC: 0.1627, F1: 0.2778

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.43513 | val 0.58518
  Epoch 016 - train 0.44318 | val 0.58763
  Regression -> MSE: 0.000165, MAE: 0.010427, R²: -0.0014
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.50924 | val 0.66999
  Epoch 016 - train 0.52681 | val 0.69164
  Regression -> MSE: 0.000087, MAE: 0.007177, R²: -0.0262
  Directional -> Accuracy: 0.4828, MCC: -0.1339, F1: 0.6154

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.44903 | val 0.65726
  Epoch 016 - train 0.48586 | val 0.67290
  Regression -> MSE: 0.000211, MAE: 0.011115, R²: 0.0046
  Directional -> Accuracy: 0.5455, MCC: 0.1765, F1: 0.6512

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.50991 | val 0.41398
  Epoch 016 - train 0.49746 | val 0.46022
  Regression -> MSE: 0.000099, MAE: 0.008200, R²: -0.0741
  Directional -> Accuracy: 0.4107, MCC: -0.1723, F1: 0.4211

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.50387 | val 0.35907
  Epoch 016 - train 0.51649 | val 0.36584
  Regression -> MSE: 0.000111, MAE: 0.009076, R²: -0.0778
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.47999 | val 0.45676
  Epoch 016 - train 0.50688 | val 0.46330
  Regression -> MSE: 0.000240, MAE: 0.012841, R²: -0.0369
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.50866 | val 0.58460
  Epoch 020 - train 0.47150 | val 0.57401
  Regression -> MSE: 0.000242, MAE: 0.010360, R²: -0.4512
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.49409 | val 0.31422
  Epoch 020 - train 0.53449 | val 0.30109
  Regression -> MSE: 0.000240, MAE: 0.012040, R²: -0.0149
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.45907 | val 1.00181
  Epoch 020 - train 0.47323 | val 0.99160
  Regression -> MSE: 0.000235, MAE: 0.010273, R²: -0.0188
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.47523 | val 0.67671
  Epoch 020 - train 0.46273 | val 0.67145
  Regression -> MSE: 0.000138, MAE: 0.008204, R²: -0.0250
  Directional -> Accuracy: 0.6047, MCC: 0.2152, F1: 0.6047

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.46172 | val 0.70930
  Epoch 016 - train 0.46162 | val 0.72034
  Regression -> MSE: 0.000188, MAE: 0.010482, R²: 0.0020
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.47238 | val 0.65285
  Epoch 016 - train 0.47116 | val 0.77467
  Regression -> MSE: 0.000279, MAE: 0.010933, R²: -0.0648
  Directional -> Accuracy: 0.4384, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.48067 | val 0.36578
  Epoch 016 - train 0.47199 | val 0.37160
  Regression -> MSE: 0.000167, MAE: 0.010352, R²: -0.0021
  Directional -> Accuracy: 0.4737, MCC: -0.0555, F1: 0.5455

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.42204 | val 0.54786
  Epoch 016 - train 0.43621 | val 0.59125
  Regression -> MSE: 0.000181, MAE: 0.010321, R²: -0.0036
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.44964 | val 0.44745
  Epoch 016 - train 0.44992 | val 0.45068
  Regression -> MSE: 0.000347, MAE: 0.012056, R²: -0.0125
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.51069 | val 0.26220
  Epoch 016 - train 0.52199 | val 0.28385
  Regression -> MSE: 0.000121, MAE: 0.008369, R²: -0.1483
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.57152 | val 0.84476
  Epoch 016 - train 0.54600 | val 0.89319
  Regression -> MSE: 0.000224, MAE: 0.011438, R²: -0.0247
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.52277 | val 1.12331
  Epoch 016 - train 0.51703 | val 1.12479
  Regression -> MSE: 0.000096, MAE: 0.007636, R²: -0.2328
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.49949 | val 0.30002
  Epoch 016 - train 0.49390 | val 0.30369
  Regression -> MSE: 0.000319, MAE: 0.014506, R²: -0.0357
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.46614 | val 0.20677
  Epoch 020 - train 0.50287 | val 0.18281
  Regression -> MSE: 0.000258, MAE: 0.011657, R²: -0.0591
  Directional -> Accuracy: 0.4737, MCC: -0.2236, F1: 0.6429

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.44922 | val 0.57572
  Epoch 020 - train 0.44413 | val 0.57087
  Regression -> MSE: 0.000082, MAE: 0.007120, R²: -0.0119
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.49269 | val 0.62186
  Epoch 016 - train 0.50358 | val 0.64187
  Regression -> MSE: 0.000309, MAE: 0.014521, R²: -0.0065
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.45840 | val 0.54581
  Epoch 016 - train 0.49109 | val 0.54962
  Regression -> MSE: 0.000098, MAE: 0.007243, R²: -0.0017
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.50906 | val 0.73103
  Epoch 016 - train 0.52648 | val 0.73643
  Regression -> MSE: 0.000172, MAE: 0.009767, R²: -0.0005
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.45514 | val 0.58652
  Epoch 016 - train 0.43613 | val 0.60539
  Regression -> MSE: 0.000222, MAE: 0.011710, R²: 0.0045
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.50297 | val 0.57851
  Epoch 016 - train 0.50199 | val 0.58911
  Regression -> MSE: 0.000092, MAE: 0.007631, R²: -0.0015
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.50152 | val 0.96325
  Epoch 016 - train 0.50285 | val 1.00788
  Regression -> MSE: 0.000164, MAE: 0.010226, R²: -0.0021
  Directional -> Accuracy: 0.5741, MCC: 0.1436, F1: 0.6230

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.45953 | val 0.70613
  Epoch 016 - train 0.46373 | val 0.75947
  Regression -> MSE: 0.000118, MAE: 0.008957, R²: -0.0177
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.50604 | val 0.87834

[I 2026-02-22 22:53:02,502] Trial 84 finished with value: -0.011551754103928391 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.4, 'dropout': 0.4, 'batch_size': 64, 'learning_rate': 4.68993846817358e-06, 'weight_decay': 2.6858356973797e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 1.6017734417594003, 'early_stopping_min_delta': 0.008668280281984473}. Best is trial 31 with value: -0.011425014985750452.

  Epoch 016 - train 0.50339 | val 0.89215
  Regression -> MSE: 0.000238, MAE: 0.012435, R²: -0.0027
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.49543 | val 0.93822
  Epoch 016 - train 0.48090 | val 0.98279
  Regression -> MSE: 0.000272, MAE: 0.013284, R²: -0.0971
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.47591 | val 0.59624
  Epoch 016 - train 0.46187 | val 0.73644
  Regression -> MSE: 0.000691, MAE: 0.019441, R²: -0.0101
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.48692 | val 1.01383
  Epoch 020 - train 0.47622 | val 0.99703
  Regression -> MSE: 0.000326, MAE: 0.014740, R²: -0.0512
  Directional -> Accuracy: 0.4468, MCC: -0.0872, F1: 0.3158

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.40980 | val 0.55252
  Epoch 016 - train 0.40556 | val 0.74296
  Regression -> MSE: 0.000356, MAE: 0.014714, R²: -0.0200
  Directional -> Accuracy: 0.4533, MCC: -0.1732, F1: 0.5859

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.45885 | val 0.47235
  Epoch 020 - train 0.45071 | val 0.47679
  Regression -> MSE: 0.000203, MAE: 0.010156, R²: 0.0031
  Directional -> Accuracy: 0.5294, MCC: 0.2357, F1: 0.2000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.49585 | val 1.21643
  Epoch 016 - train 0.47800 | val 1.24300
  Regression -> MSE: 0.000561, MAE: 0.018220, R²: -0.0104
  Directional -> Accuracy: 0.4043, MCC: -0.2191, F1: 0.5333

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.48006 | val 0.67908
  Epoch 020 - train 0.47505 | val 0.67431
  Regression -> MSE: 0.000253, MAE: 0.012056, R²: -0.0301
  Directional -> Accuracy: 0.5217, MCC: 0.0471, F1: 0.4762

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.50123 | val 0.61968
  Epoch 016 - train 0.49752 | val 0.61891
  Regression -> MSE: 0.000599, MAE: 0.019117, R²: -0.0025
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.46627 | val 0.58973
  Epoch 016 - train 0.45162 | val 0.59456
  Regression -> MSE: 0.000414, MAE: 0.016309, R²: -0.0795
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.46520 | val 0.75295
  Epoch 016 - train 0.46641 | val 0.84739
  Regression -> MSE: 0.000241, MAE: 0.011974, R²: 0.0012
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.45346 | val 0.93415
  Epoch 016 - train 0.43376 | val 1.25587
  Regression -> MSE: 0.000313, MAE: 0.013612, R²: -0.0057
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.49706 | val 0.62543
  Epoch 020 - train 0.50009 | val 0.61333
  Regression -> MSE: 0.000659, MAE: 0.019318, R²: 0.0277
  Directional -> Accuracy: 0.5690, MCC: 0.1543, F1: 0.6479

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.48697 | val 0.49679
  Epoch 016 - train 0.48006 | val 0.51421
  Regression -> MSE: 0.000141, MAE: 0.009392, R²: -0.0233
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.42981 | val 0.71286
  Epoch 020 - train 0.42379 | val 0.69549
  Regression -> MSE: 0.000226, MAE: 0.010863, R²: -0.0049
  Directional -> Accuracy: 0.4426, MCC: -0.1136, F1: 0.4138

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.48608 | val 1.43435
  Epoch 016 - train 0.45032 | val 1.43886
  Regression -> MSE: 0.000375, MAE: 0.015930, R²: -0.0362
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.48260 | val 0.52984
  Epoch 016 - train 0.48922 | val 0.54373
  Regression -> MSE: 0.000107, MAE: 0.008027, R²: 0.0034
  Directional -> Accuracy: 0.4714, MCC: 0.0526, F1: 0.0976

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.47677 | val 1.11253
  Epoch 016 - train 0.45467 | val 1.25947
  Regression -> MSE: 0.000161, MAE: 0.010107, R²: -0.0316
  Directional -> Accuracy: 0.5763, MCC: 0.2104, F1: 0.5902

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.46931 | val 0.49320
  Epoch 016 - train 0.48428 | val 0.53897
  Regression -> MSE: 0.000272, MAE: 0.013026, R²: 0.0009
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.40730 | val 0.73600
  Epoch 020 - train 0.38598 | val 0.75813
  Regression -> MSE: 0.000160, MAE: 0.008933, R²: -0.0719
  Directional -> Accuracy: 0.5385, MCC: 0.0807, F1: 0.5714

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.47047 | val 1.01399
  Epoch 016 - train 0.46146 | val 1.00661
  Regression -> MSE: 0.000233, MAE: 0.010907, R²: -0.0313
  Directional -> Accuracy: 0.5600, MCC: 0.1654, F1: 0.4923

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.49246 | val 0.74022
  Epoch 016 - train 0.49457 | val 0.78674
  Regression -> MSE: 0.000152, MAE: 0.008752, R²: -0.0588
  Directional -> Accuracy: 0.3750, MCC: -0.0778, F1: 0.1176

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.47081 | val 0.56956
  Epoch 016 - train 0.44543 | val 0.58634
  Regression -> MSE: 0.000183, MAE: 0.010392, R²: -0.1085
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.50679 | val 0.71332
  Epoch 016 - train 0.50524 | val 0.73506
  Regression -> MSE: 0.000090, MAE: 0.007319, R²: -0.0585
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.47900 | val 0.67217
  Epoch 020 - train 0.46205 | val 0.67237
  Regression -> MSE: 0.000211, MAE: 0.011209, R²: 0.0024
  Directional -> Accuracy: 0.5152, MCC: 0.0950, F1: 0.6279

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.41220 | val 0.35843
  Epoch 020 - train 0.40834 | val 0.35519
  Regression -> MSE: 0.000090, MAE: 0.007924, R²: 0.0176
  Directional -> Accuracy: 0.5714, MCC: 0.0967, F1: 0.7073

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.48918 | val 0.36889
  Epoch 016 - train 0.49817 | val 0.36927
  Regression -> MSE: 0.000112, MAE: 0.009095, R²: -0.0815
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.46567 | val 0.48173
  Epoch 016 - train 0.48544 | val 0.49324
  Regression -> MSE: 0.000232, MAE: 0.012494, R²: -0.0042
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.46144 | val 0.63962
  Epoch 016 - train 0.46562 | val 0.66878
  Regression -> MSE: 0.000182, MAE: 0.007995, R²: -0.0934
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.48568 | val 0.29051
  Epoch 016 - train 0.48054 | val 0.29452
  Regression -> MSE: 0.000238, MAE: 0.011930, R²: -0.0077
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.47422 | val 1.06405
  Epoch 016 - train 0.46691 | val 1.11440
  Regression -> MSE: 0.000232, MAE: 0.009925, R²: -0.0066
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.48555 | val 0.68769
  Epoch 016 - train 0.47958 | val 0.71689
  Regression -> MSE: 0.000137, MAE: 0.008243, R²: -0.0159
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.50781 | val 0.69322
  Epoch 020 - train 0.48503 | val 0.69276
  Regression -> MSE: 0.000197, MAE: 0.010983, R²: -0.0481
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.41462 | val 0.63201
  Epoch 020 - train 0.41550 | val 0.63478
  Regression -> MSE: 0.000271, MAE: 0.010603, R²: -0.0359
  Directional -> Accuracy: 0.5205, MCC: 0.0723, F1: 0.4928

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.48368 | val 0.35452
  Epoch 016 - train 0.49924 | val 0.35253
  Regression -> MSE: 0.000166, MAE: 0.010374, R²: 0.0013
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.42575 | val 0.54360
  Epoch 020 - train 0.42153 | val 0.53379
  Regression -> MSE: 0.000190, MAE: 0.010651, R²: -0.0543
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.44755 | val 0.42435
  Epoch 020 - train 0.44369 | val 0.42498
  Regression -> MSE: 0.000349, MAE: 0.012519, R²: -0.0188
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.55035 | val 0.28335
  Epoch 016 - train 0.54695 | val 0.32027
  Regression -> MSE: 0.000127, MAE: 0.008549, R²: -0.2102
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.46437 | val 0.87067
  Epoch 016 - train 0.45613 | val 0.89313
  Regression -> MSE: 0.000220, MAE: 0.011370, R²: -0.0085
  Directional -> Accuracy: 0.4561, MCC: -0.1409, F1: 0.6265

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.44745 | val 1.19243
  Epoch 016 - train 0.45147 | val 1.21101
  Regression -> MSE: 0.000089, MAE: 0.007385, R²: -0.1462
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.48086 | val 0.29094
  Epoch 016 - train 0.46963 | val 0.29392
  Regression -> MSE: 0.000319, MAE: 0.014463, R²: -0.0365
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.51840 | val 0.22274
  Epoch 020 - train 0.51379 | val 0.20856
  Regression -> MSE: 0.000263, MAE: 0.011619, R²: -0.0803
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.44028 | val 0.62408
  Epoch 016 - train 0.44144 | val 0.62639
  Regression -> MSE: 0.000081, MAE: 0.007065, R²: -0.0024
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.57780 | val 0.63809
  Epoch 016 - train 0.54994 | val 0.65369
  Regression -> MSE: 0.000311, MAE: 0.014555, R²: -0.0126
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.46096 | val 0.59205
  Epoch 016 - train 0.50726 | val 0.59620
  Regression -> MSE: 0.000100, MAE: 0.007165, R²: -0.0162
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.50276 | val 0.79593
  Epoch 016 - train 0.50729 | val 0.79495
  Regression -> MSE: 0.000178, MAE: 0.010401, R²: -0.0354
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.43616 | val 0.60807
  Epoch 016 - train 0.44773 | val 0.65840
  Regression -> MSE: 0.000224, MAE: 0.011800, R²: -0.0062
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.47448 | val 0.59895
  Epoch 016 - train 0.45000 | val 0.63271
  Regression -> MSE: 0.000092, MAE: 0.007607, R²: 0.0085
  Directional -> Accuracy: 0.6316, MCC: 0.2599, F1: 0.6038

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.49405 | val 1.00590
  Epoch 016 - train 0.49654 | val 1.02362
  Regression -> MSE: 0.000164, MAE: 0.010275, R²: -0.0026
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.45794 | val 0.68256
  Epoch 020 - train 0.44761 | val 0.67822
  Regression -> MSE: 0.000256, MAE: 0.012295, R²: -1.2100
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.49907 | val 0.97317

[I 2026-02-22 22:53:34,403] Trial 85 finished with value: -0.011548249603162307 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.30000000000000004, 'batch_size': 64, 'learning_rate': 1.6196222624248336e-05, 'weight_decay': 1.998628853200471e-06, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 1.8054498495176576, 'early_stopping_min_delta': 0.00822142369945555}. Best is trial 31 with value: -0.011425014985750452.

  Epoch 016 - train 0.48434 | val 1.18323
  Regression -> MSE: 0.000243, MAE: 0.012331, R²: -0.0229
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 12
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.45363 | val 0.72694
  Epoch 016 - train 0.46912 | val 0.75136
  Regression -> MSE: 0.000247, MAE: 0.012570, R²: -0.0056
  Directional -> Accuracy: 0.4487, MCC: 0.0000, F1: 0.6195

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 88). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.50556 | val 0.43462
  Epoch 016 - train 0.48645 | val 0.43648
  Regression -> MSE: 0.000700, MAE: 0.019751, R²: -0.0122
  Directional -> Accuracy: 0.5532, MCC: 0.0000, F1: 0.7123

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 88). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.53226 | val 0.94449
  Epoch 020 - train 0.52418 | val 0.94693
  Regression -> MSE: 0.000369, MAE: 0.015117, R²: -0.0687
  Directional -> Accuracy: 0.4583, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.44859 | val 0.41047
  Epoch 016 - train 0.43865 | val 0.43450
  Regression -> MSE: 0.000353, MAE: 0.014553, R²: -0.0237
  Directional -> Accuracy: 0.4342, MCC: -0.1280, F1: 0.4416

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.49164 | val 0.42126
  Epoch 020 - train 0.45564 | val 0.37978
  Regression -> MSE: 0.000196, MAE: 0.009433, R²: 0.0245
  Directional -> Accuracy: 0.6538, MCC: 0.3536, F1: 0.7500

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.49315 | val 1.09940
  Epoch 016 - train 0.43858 | val 1.09576
  Regression -> MSE: 0.000600, MAE: 0.018820, R²: -0.0487
  Directional -> Accuracy: 0.4898, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.53937 | val 0.64034
  Epoch 020 - train 0.51174 | val 0.65357
  Regression -> MSE: 0.000244, MAE: 0.012142, R²: 0.0055
  Directional -> Accuracy: 0.5000, MCC: 0.0479, F1: 0.5070

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 88). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 88). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.54881 | val 0.79475
  Epoch 016 - train 0.48823 | val 0.80102
  Regression -> MSE: 0.000650, MAE: 0.020111, R²: -0.1125
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.52403 | val 0.79319
  Epoch 020 - train 0.50194 | val 0.77947
  Regression -> MSE: 0.000336, MAE: 0.015170, R²: 0.0053
  Directional -> Accuracy: 0.3810, MCC: 0.0000, F1: 0.5517

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 88). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 88). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.48872 | val 0.71477
  Epoch 016 - train 0.52232 | val 0.76614
  Regression -> MSE: 0.000247, MAE: 0.011551, R²: -0.0358
  Directional -> Accuracy: 0.5634, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.49501 | val 0.80557
  Epoch 016 - train 0.50310 | val 0.88051
  Regression -> MSE: 0.000308, MAE: 0.013531, R²: -0.0052
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.56566 | val 0.61173
  Epoch 016 - train 0.53694 | val 0.64646
  Regression -> MSE: 0.000672, MAE: 0.019429, R²: -0.0032
  Directional -> Accuracy: 0.4915, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.61558 | val 0.45708
  Epoch 016 - train 0.51211 | val 0.46444
  Regression -> MSE: 0.000155, MAE: 0.009867, R²: -0.0341
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 88). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.44531 | val 0.68703
  Epoch 016 - train 0.46677 | val 0.68200
  Regression -> MSE: 0.000228, MAE: 0.010862, R²: -0.0150
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.50098 | val 1.36326
  Epoch 016 - train 0.53276 | val 1.36985
  Regression -> MSE: 0.000377, MAE: 0.016381, R²: -0.0036
  Directional -> Accuracy: 0.4717, MCC: 0.0000, F1: 0.6410

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.50698 | val 0.50902
  Epoch 020 - train 0.50109 | val 0.49987
  Regression -> MSE: 0.000105, MAE: 0.007843, R²: 0.0125
  Directional -> Accuracy: 0.5211, MCC: 0.0019, F1: 0.6383

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.49015 | val 1.04831
  Epoch 016 - train 0.51849 | val 1.04683
  Regression -> MSE: 0.000161, MAE: 0.010077, R²: -0.0076
  Directional -> Accuracy: 0.6167, MCC: 0.0000, F1: 0.7629

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.48149 | val 0.44111
  Epoch 016 - train 0.49282 | val 0.53326
  Regression -> MSE: 0.000277, MAE: 0.013309, R²: -0.0317
  Directional -> Accuracy: 0.3896, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.45153 | val 0.71500
  Epoch 020 - train 0.44277 | val 0.70196
  Regression -> MSE: 0.000196, MAE: 0.010307, R²: -0.3285
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 88). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.55464 | val 0.91363
  Epoch 020 - train 0.51916 | val 0.91038
  Regression -> MSE: 0.000274, MAE: 0.011972, R²: -0.2082
  Directional -> Accuracy: 0.4605, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.51097 | val 0.62809
  Epoch 016 - train 0.55623 | val 0.63423
  Regression -> MSE: 0.000160, MAE: 0.009096, R²: -0.0800
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 88). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 88). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 88). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.51059 | val 0.55943
  Epoch 016 - train 0.48420 | val 0.56406
  Regression -> MSE: 0.000177, MAE: 0.010771, R²: -0.0011
  Directional -> Accuracy: 0.5075, MCC: 0.0000, F1: 0.6733

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.48017 | val 0.64741
  Epoch 016 - train 0.49146 | val 0.65446
  Regression -> MSE: 0.000085, MAE: 0.007021, R²: -0.0126
  Directional -> Accuracy: 0.5763, MCC: 0.0000, F1: 0.7312

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.49482 | val 0.63660
  Epoch 020 - train 0.46538 | val 0.67132
  Regression -> MSE: 0.000218, MAE: 0.011290, R²: 0.0044
  Directional -> Accuracy: 0.5075, MCC: 0.0402, F1: 0.5926

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.48536 | val 0.33047
  Epoch 020 - train 0.48511 | val 0.30025
  Regression -> MSE: 0.000093, MAE: 0.008011, R²: -0.0178
  Directional -> Accuracy: 0.5965, MCC: 0.1560, F1: 0.6849

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.52293 | val 0.19651
  Epoch 016 - train 0.52257 | val 0.19486
  Regression -> MSE: 0.000141, MAE: 0.009772, R²: -0.1240
  Directional -> Accuracy: 0.4167, MCC: 0.0000, F1: 0.5882

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.54337 | val 0.39659
  Epoch 020 - train 0.51665 | val 0.40311
  Regression -> MSE: 0.000240, MAE: 0.012842, R²: -0.0103
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.7429

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.51456 | val 0.60294
  Epoch 016 - train 0.49517 | val 0.60900
  Regression -> MSE: 0.000176, MAE: 0.007804, R²: -0.0711
  Directional -> Accuracy: 0.4483, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.50832 | val 0.26616
  Epoch 016 - train 0.51673 | val 0.26695
  Regression -> MSE: 0.000237, MAE: 0.011991, R²: -0.0109
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.51614 | val 0.81783
  Epoch 016 - train 0.58020 | val 0.82719
  Regression -> MSE: 0.000251, MAE: 0.010422, R²: -0.0034
  Directional -> Accuracy: 0.4889, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.55800 | val 0.73818
  Epoch 016 - train 0.57345 | val 0.74114
  Regression -> MSE: 0.000133, MAE: 0.008175, R²: -0.0013
  Directional -> Accuracy: 0.5333, MCC: 0.0000, F1: 0.6957

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.49385 | val 0.68066
  Epoch 020 - train 0.53301 | val 0.67729
  Regression -> MSE: 0.000194, MAE: 0.010868, R²: -0.0303
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.46147 | val 0.63377
  Epoch 020 - train 0.44043 | val 0.62522
  Regression -> MSE: 0.000298, MAE: 0.011698, R²: -0.1547
  Directional -> Accuracy: 0.4459, MCC: 0.1022, F1: 0.0465

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 88). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.59466 | val 0.36036
  Epoch 016 - train 0.49824 | val 0.35886
  Regression -> MSE: 0.000164, MAE: 0.010154, R²: -0.0073
  Directional -> Accuracy: 0.4615, MCC: -0.1312, F1: 0.1600

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.47153 | val 0.56733
  Epoch 016 - train 0.44632 | val 0.58386
  Regression -> MSE: 0.000190, MAE: 0.010746, R²: -0.0404
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.6364

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.50961 | val 0.41327
  Epoch 020 - train 0.45580 | val 0.40119
  Regression -> MSE: 0.000407, MAE: 0.014607, R²: -0.1675
  Directional -> Accuracy: 0.4265, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.53626 | val 0.26515
  Epoch 016 - train 0.54298 | val 0.26360
  Regression -> MSE: 0.000109, MAE: 0.008215, R²: -0.0511
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.57918 | val 0.80623
  Epoch 020 - train 0.53179 | val 0.79739
  Regression -> MSE: 0.000235, MAE: 0.012000, R²: -0.0938
  Directional -> Accuracy: 0.4655, MCC: 0.0000, F1: 0.6353

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.53668 | val 1.11884
  Epoch 016 - train 0.53006 | val 1.13688
  Regression -> MSE: 0.000082, MAE: 0.007104, R²: -0.0359
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 88). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 88). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 88). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 88). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.53193 | val 0.30762
  Epoch 016 - train 0.56917 | val 0.30984
  Regression -> MSE: 0.000330, MAE: 0.014527, R²: -0.0068
  Directional -> Accuracy: 0.3250, MCC: -0.2182, F1: 0.4906

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 88). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.57220 | val 0.22006
  Epoch 016 - train 0.62963 | val 0.22001
  Regression -> MSE: 0.000243, MAE: 0.011235, R²: -0.0233
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.7000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 88). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 88). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.54034 | val 0.61702
  Epoch 020 - train 0.47049 | val 0.63909
  Regression -> MSE: 0.000081, MAE: 0.006968, R²: -0.0087
  Directional -> Accuracy: 0.5132, MCC: 0.0455, F1: 0.1778

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 88). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 88). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 88). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.57948 | val 0.49870
  Epoch 020 - train 0.52924 | val 0.47716
  Regression -> MSE: 0.000353, MAE: 0.015190, R²: 0.0187
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.46709 | val 0.59741
  Epoch 016 - train 0.51776 | val 0.59468
  Regression -> MSE: 0.000097, MAE: 0.007175, R²: -0.0057
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.52057 | val 0.77467
  Epoch 016 - train 0.50624 | val 0.80082
  Regression -> MSE: 0.000181, MAE: 0.009859, R²: -0.0018
  Directional -> Accuracy: 0.6341, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.50560 | val 0.61524
  Epoch 016 - train 0.46081 | val 0.66625
  Regression -> MSE: 0.000227, MAE: 0.011823, R²: -0.0343
  Directional -> Accuracy: 0.4561, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.53345 | val 0.56991
  Epoch 016 - train 0.52264 | val 0.57308
  Regression -> MSE: 0.000092, MAE: 0.007638, R²: -0.0107
  Directional -> Accuracy: 0.5172, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.55184 | val 0.95789
  Epoch 016 - train 0.52810 | val 0.96320
  Regression -> MSE: 0.000161, MAE: 0.010087, R²: -0.0040
  Directional -> Accuracy: 0.5818, MCC: 0.1547, F1: 0.6567

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.55250 | val 0.67336
  Epoch 016 - train 0.49891 | val 0.70204
  Regression -> MSE: 0.000119, MAE: 0.008827, R²: -0.0460
  Directional -> Accuracy: 0.4912, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.52644 | val 0.87860

[I 2026-02-22 22:55:04,646] Trial 86 finished with value: -0.011619734495027905 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 12, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.8, 'batch_size': 64, 'learning_rate': 8.651262784960172e-05, 'weight_decay': 2.8146798818500925e-06, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 1.7308072754162485, 'early_stopping_min_delta': 0.006865647530186735}. Best is trial 31 with value: -0.011425014985750452.

  Epoch 016 - train 0.53793 | val 0.91784
  Regression -> MSE: 0.000241, MAE: 0.012275, R²: -0.0334
  Directional -> Accuracy: 0.5161, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.40989 | val 0.77404
  Epoch 020 - train 0.39729 | val 0.78903
  Epoch 028 - train 0.39324 | val 0.81361
  Regression -> MSE: 0.000251, MAE: 0.012555, R²: -0.0136
  Directional -> Accuracy: 0.5195, MCC: -0.0112, F1: 0.3019

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.42277 | val 0.46711
  Epoch 020 - train 0.42769 | val 0.45068
  Epoch 030 - train 0.38997 | val 0.47157
  Regression -> MSE: 0.000660, MAE: 0.018779, R²: 0.0355
  Directional -> Accuracy: 0.5870, MCC: 0.1236, F1: 0.7246

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.44121 | val 0.98193
  Epoch 020 - train 0.42372 | val 0.97505
  Epoch 030 - train 0.40073 | val 0.98827
  Epoch 032 - train 0.40977 | val 0.98673
  Regression -> MSE: 0.000320, MAE: 0.014528, R²: -0.0317
  Directional -> Accuracy: 0.5319, MCC: 0.0712, F1: 0.5217

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.35356 | val 0.48794
  Epoch 016 - train 0.34446 | val 0.61172
  Regression -> MSE: 0.000351, MAE: 0.014586, R²: -0.0060
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.40882 | val 0.46347
  Epoch 020 - train 0.39953 | val 0.44141
  Epoch 030 - train 0.39410 | val 0.46434
  Regression -> MSE: 0.000197, MAE: 0.009934, R²: 0.0321
  Directional -> Accuracy: 0.6275, MCC: 0.2598, F1: 0.7077

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.41713 | val 1.20156
  Epoch 020 - train 0.38313 | val 1.17547
  Epoch 030 - train 0.35156 | val 1.13966
  Epoch 040 - train 0.35488 | val 1.15896
  Epoch 043 - train 0.33634 | val 1.16930
  Regression -> MSE: 0.000609, MAE: 0.019874, R²: -0.0963
  Directional -> Accuracy: 0.5319, MCC: 0.0926, F1: 0.1538

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.44045 | val 0.64886
  Epoch 020 - train 0.40074 | val 0.69726
  Epoch 022 - train 0.41410 | val 0.70282
  Regression -> MSE: 0.000246, MAE: 0.012000, R²: -0.0023
  Directional -> Accuracy: 0.4203, MCC: -0.1541, F1: 0.3750

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.41761 | val 0.69156
  Epoch 016 - train 0.38818 | val 0.69558
  Regression -> MSE: 0.000625, MAE: 0.019817, R²: -0.0463
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.41175 | val 0.59935
  Epoch 016 - train 0.38814 | val 0.65222
  Regression -> MSE: 0.000402, MAE: 0.016090, R²: -0.0480
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.41178 | val 0.69848
  Epoch 016 - train 0.43131 | val 0.71850
  Regression -> MSE: 0.000241, MAE: 0.011947, R²: 0.0004
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.40675 | val 0.88248
  Epoch 016 - train 0.39003 | val 0.99302
  Regression -> MSE: 0.000312, MAE: 0.013699, R²: -0.0031
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.6301

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.43177 | val 0.60745
  Epoch 016 - train 0.42270 | val 0.64698
  Regression -> MSE: 0.000679, MAE: 0.019623, R²: -0.0025
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.38761 | val 0.54570
  Epoch 016 - train 0.39011 | val 0.59029
  Regression -> MSE: 0.000139, MAE: 0.009001, R²: -0.0057
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.38525 | val 0.68944
  Epoch 020 - train 0.36456 | val 0.70548
  Epoch 028 - train 0.34840 | val 0.72399
  Regression -> MSE: 0.000220, MAE: 0.010484, R²: 0.0205
  Directional -> Accuracy: 0.6230, MCC: 0.2462, F1: 0.6230

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.42500 | val 1.40884
  Epoch 016 - train 0.39749 | val 1.48084
  Regression -> MSE: 0.000366, MAE: 0.015977, R²: -0.0118
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.45041 | val 0.49067
  Epoch 020 - train 0.40899 | val 0.52348
  Epoch 023 - train 0.39791 | val 0.53681
  Regression -> MSE: 0.000106, MAE: 0.007944, R²: 0.0177
  Directional -> Accuracy: 0.4714, MCC: -0.0574, F1: 0.4932

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.39859 | val 1.07466
  Epoch 016 - train 0.40816 | val 1.17452
  Regression -> MSE: 0.000156, MAE: 0.009676, R²: 0.0015
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.44598 | val 0.64024
  Epoch 016 - train 0.44384 | val 1.08132
  Regression -> MSE: 0.000293, MAE: 0.013912, R²: -0.0752
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.35468 | val 0.71422
  Epoch 020 - train 0.34710 | val 0.72047
  Epoch 029 - train 0.33435 | val 0.71356
  Regression -> MSE: 0.000274, MAE: 0.013088, R²: -0.8344
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.42118 | val 0.90330
  Epoch 020 - train 0.40084 | val 0.91305
  Epoch 026 - train 0.39257 | val 0.92000
  Regression -> MSE: 0.000442, MAE: 0.016574, R²: -0.9516
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.45272 | val 0.71863
  Epoch 020 - train 0.42546 | val 0.72809
  Epoch 023 - train 0.40263 | val 0.74938
  Regression -> MSE: 0.000144, MAE: 0.008401, R²: -0.0036
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.41037 | val 0.57592
  Epoch 020 - train 0.39636 | val 0.57125
  Epoch 025 - train 0.39241 | val 0.57134
  Regression -> MSE: 0.000164, MAE: 0.010330, R²: 0.0048
  Directional -> Accuracy: 0.4545, MCC: -0.2182, F1: 0.6250

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.44289 | val 0.65823
  Epoch 016 - train 0.42864 | val 0.66289
  Regression -> MSE: 0.000086, MAE: 0.007067, R²: -0.0047
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.43546 | val 0.67617
  Epoch 020 - train 0.41929 | val 0.78173
  Regression -> MSE: 0.000213, MAE: 0.011319, R²: -0.0035
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.37107 | val 0.35061
  Epoch 020 - train 0.34602 | val 0.31709
  Epoch 030 - train 0.33084 | val 0.30683
  Epoch 040 - train 0.33609 | val 0.30659
  Epoch 041 - train 0.31494 | val 0.30630
  Regression -> MSE: 0.000109, MAE: 0.008389, R²: -0.1848
  Directional -> Accuracy: 0.5357, MCC: 0.1728, F1: 0.3810

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.45818 | val 0.35242
  Epoch 020 - train 0.44564 | val 0.33225
  Epoch 030 - train 0.43534 | val 0.34829
  Epoch 032 - train 0.40522 | val 0.35257
  Regression -> MSE: 0.000101, MAE: 0.008554, R²: 0.0224
  Directional -> Accuracy: 0.5652, MCC: 0.1154, F1: 0.5000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.45553 | val 0.45436
  Epoch 016 - train 0.43510 | val 0.47099
  Regression -> MSE: 0.000232, MAE: 0.012532, R²: -0.0009
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.41708 | val 0.60501
  Epoch 020 - train 0.39574 | val 0.60057
  Epoch 028 - train 0.40478 | val 0.60945
  Regression -> MSE: 0.000189, MAE: 0.008152, R²: -0.1380
  Directional -> Accuracy: 0.5965, MCC: 0.2112, F1: 0.5965

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.45292 | val 0.29562
  Epoch 016 - train 0.43843 | val 0.30683
  Regression -> MSE: 0.000238, MAE: 0.011947, R²: -0.0080
  Directional -> Accuracy: 0.4634, MCC: -0.0361, F1: 0.2667

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.46618 | val 0.99157
  Epoch 016 - train 0.43360 | val 1.01365
  Regression -> MSE: 0.000231, MAE: 0.009863, R²: -0.0004
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.42858 | val 0.67149
  Epoch 016 - train 0.40580 | val 0.70516
  Regression -> MSE: 0.000136, MAE: 0.008229, R²: -0.0065
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.41557 | val 0.68413
  Epoch 016 - train 0.41420 | val 0.69931
  Regression -> MSE: 0.000193, MAE: 0.010443, R²: -0.0268
  Directional -> Accuracy: 0.4400, MCC: -0.1548, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.37675 | val 0.62082
  Epoch 016 - train 0.36383 | val 0.61612
  Regression -> MSE: 0.000266, MAE: 0.010543, R²: -0.0176
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.41768 | val 0.38234
  Epoch 016 - train 0.40801 | val 0.40779
  Regression -> MSE: 0.000170, MAE: 0.010370, R²: -0.0191
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.39214 | val 0.56763
  Epoch 016 - train 0.36075 | val 0.61910
  Regression -> MSE: 0.000181, MAE: 0.010369, R²: -0.0067
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.41546 | val 0.42517
  Epoch 020 - train 0.39836 | val 0.43782
  Epoch 026 - train 0.37595 | val 0.44163
  Regression -> MSE: 0.000351, MAE: 0.012663, R²: -0.0245
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.42481 | val 0.23239
  Epoch 020 - train 0.37898 | val 0.22787
  Epoch 030 - train 0.37300 | val 0.24093
  Regression -> MSE: 0.000125, MAE: 0.008258, R²: -0.1924
  Directional -> Accuracy: 0.6977, MCC: 0.4094, F1: 0.6667

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.42555 | val 0.82140
  Epoch 016 - train 0.42237 | val 0.84038
  Regression -> MSE: 0.000219, MAE: 0.011290, R²: -0.0023
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.42791 | val 1.13596
  Epoch 020 - train 0.38970 | val 1.20157
  Epoch 022 - train 0.40225 | val 1.24132
  Regression -> MSE: 0.000086, MAE: 0.007229, R²: -0.1010
  Directional -> Accuracy: 0.4255, MCC: 0.0074, F1: 0.2703

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.43451 | val 0.35271
  Epoch 020 - train 0.39015 | val 0.30933
  Epoch 030 - train 0.36367 | val 0.26437
  Epoch 040 - train 0.35684 | val 0.24018
  Epoch 050 - train 0.34625 | val 0.23021
  Regression -> MSE: 0.000745, MAE: 0.023519, R²: -1.4214
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.46556 | val 0.21049
  Epoch 016 - train 0.43411 | val 0.22548
  Regression -> MSE: 0.000244, MAE: 0.011541, R²: 0.0004
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.0000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.41964 | val 0.61154
  Epoch 016 - train 0.38072 | val 0.66607
  Regression -> MSE: 0.000083, MAE: 0.007032, R²: -0.0324
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.42998 | val 0.61261
  Epoch 020 - train 0.42617 | val 0.61987
  Epoch 026 - train 0.39453 | val 0.64627
  Regression -> MSE: 0.000330, MAE: 0.014789, R²: -0.0772
  Directional -> Accuracy: 0.4681, MCC: -0.0764, F1: 0.1379

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.42171 | val 0.56732
  Epoch 016 - train 0.41147 | val 0.57397
  Regression -> MSE: 0.000098, MAE: 0.007180, R²: 0.0000
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.41865 | val 0.75128
  Epoch 016 - train 0.42489 | val 0.75772
  Regression -> MSE: 0.000172, MAE: 0.009618, R²: -0.0009
  Directional -> Accuracy: 0.5102, MCC: 0.0256, F1: 0.4545

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.38816 | val 0.63701
  Epoch 016 - train 0.37725 | val 0.89152
  Regression -> MSE: 0.000223, MAE: 0.011763, R²: -0.0002
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.41450 | val 0.58325
  Epoch 016 - train 0.37890 | val 0.66645
  Regression -> MSE: 0.000092, MAE: 0.007635, R²: -0.0019
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.45284 | val 0.99450
  Epoch 016 - train 0.43590 | val 1.05858
  Regression -> MSE: 0.000165, MAE: 0.010291, R²: -0.0078
  Directional -> Accuracy: 0.4815, MCC: 0.0000, F1: 0.0000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.42386 | val 0.76014
  Epoch 016 - train 0.41711 | val 0.86326
  Regression -> MSE: 0.000116, MAE: 0.008925, R²: -0.0004
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.44263 | val 0.92679

[I 2026-02-22 22:56:22,388] Trial 87 finished with value: -0.01181365191296889 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.4, 'dropout': 0.30000000000000004, 'batch_size': 64, 'learning_rate': 6.735005801103101e-05, 'weight_decay': 1.5492557379463016e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 1.6661296613568346, 'early_stopping_min_delta': 0.009124937356284361}. Best is trial 31 with value: -0.011425014985750452.

  Epoch 016 - train 0.42844 | val 1.06567
  Regression -> MSE: 0.000237, MAE: 0.012352, R²: -0.0008
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.42013 | val 0.73283
  Epoch 020 - train 0.44829 | val 0.74039
  Epoch 021 - train 0.43112 | val 0.73752
  Regression -> MSE: 0.000240, MAE: 0.012290, R²: -0.0002
  Directional -> Accuracy: 0.5658, MCC: 0.1475, F1: 0.5714

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.45712 | val 0.49808
  Epoch 020 - train 0.42661 | val 0.48058
  Epoch 021 - train 0.45145 | val 0.47426
  Regression -> MSE: 0.000712, MAE: 0.019848, R²: -0.0199
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.46182 | val 0.95867
  Epoch 020 - train 0.50681 | val 0.94424
  Epoch 021 - train 0.52313 | val 0.94407
  Regression -> MSE: 0.000315, MAE: 0.014494, R²: -0.0012
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.6857

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.38451 | val 0.60134
  Epoch 020 - train 0.37550 | val 0.59136
  Epoch 021 - train 0.39357 | val 0.58981
  Regression -> MSE: 0.000361, MAE: 0.014790, R²: -0.0233
  Directional -> Accuracy: 0.4595, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.43918 | val 0.43450
  Epoch 020 - train 0.42237 | val 0.42552
  Epoch 030 - train 0.44400 | val 0.43112
  Regression -> MSE: 0.000218, MAE: 0.010134, R²: -0.0564
  Directional -> Accuracy: 0.5200, MCC: 0.0225, F1: 0.6250

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.44264 | val 1.07772
  Epoch 020 - train 0.44553 | val 1.04433
  Epoch 021 - train 0.40718 | val 1.03495
  Regression -> MSE: 0.000601, MAE: 0.018891, R²: -0.0615
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.48238 | val 0.59617
  Epoch 020 - train 0.46145 | val 0.63146
  Epoch 030 - train 0.45428 | val 0.69510
  Regression -> MSE: 0.000259, MAE: 0.012068, R²: -0.0448
  Directional -> Accuracy: 0.5441, MCC: -0.1097, F1: 0.1143

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.47238 | val 0.33915
  Epoch 020 - train 0.44173 | val 0.39859
  Epoch 021 - train 0.45807 | val 0.39044
  Regression -> MSE: 0.000612, MAE: 0.019434, R²: -0.0017
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.48647 | val 0.59413
  Epoch 020 - train 0.43595 | val 0.57207
  Epoch 030 - train 0.43552 | val 0.60985
  Regression -> MSE: 0.000447, MAE: 0.016711, R²: -0.1983
  Directional -> Accuracy: 0.5625, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.48522 | val 0.90288
  Epoch 020 - train 0.44465 | val 0.78182
  Epoch 021 - train 0.46300 | val 0.80282
  Regression -> MSE: 0.000246, MAE: 0.012191, R²: -0.0031
  Directional -> Accuracy: 0.4203, MCC: 0.0000, F1: 0.5918

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.45143 | val 0.99974
  Epoch 020 - train 0.42192 | val 1.01543
  Epoch 021 - train 0.44769 | val 0.98357
  Regression -> MSE: 0.000316, MAE: 0.013842, R²: -0.0123
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.49616 | val 0.67105
  Epoch 020 - train 0.47447 | val 0.66053
  Epoch 021 - train 0.48351 | val 0.65938
  Regression -> MSE: 0.000700, MAE: 0.019789, R²: -0.0213
  Directional -> Accuracy: 0.4912, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.49258 | val 1.01776
  Epoch 020 - train 0.43449 | val 1.07906
  Epoch 021 - train 0.46737 | val 1.07673
  Regression -> MSE: 0.000137, MAE: 0.009011, R²: 0.0039
  Directional -> Accuracy: 0.5238, MCC: 0.0389, F1: 0.4737

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.39927 | val 0.66847
  Epoch 020 - train 0.38732 | val 0.66289
  Epoch 021 - train 0.40159 | val 0.66355
  Regression -> MSE: 0.000228, MAE: 0.010733, R²: -0.0087
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.45956 | val 1.60154
  Epoch 020 - train 0.44996 | val 1.59293
  Epoch 021 - train 0.40599 | val 1.58142
  Regression -> MSE: 0.000368, MAE: 0.016315, R²: -0.0026
  Directional -> Accuracy: 0.4510, MCC: 0.0000, F1: 0.6216

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.47031 | val 0.49013
  Epoch 020 - train 0.44268 | val 0.49414
  Epoch 023 - train 0.46286 | val 0.49780
  Regression -> MSE: 0.000108, MAE: 0.007821, R²: -0.0022
  Directional -> Accuracy: 0.6087, MCC: 0.2651, F1: 0.7273

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.45754 | val 1.02955
  Epoch 020 - train 0.43103 | val 1.07981
  Epoch 021 - train 0.42854 | val 1.07218
  Regression -> MSE: 0.000159, MAE: 0.009920, R²: -0.0072
  Directional -> Accuracy: 0.6207, MCC: 0.0000, F1: 0.7660

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.44219 | val 0.52898
  Epoch 020 - train 0.45203 | val 0.60547
  Epoch 021 - train 0.45514 | val 0.63205
  Regression -> MSE: 0.000280, MAE: 0.013371, R²: -0.0219
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.40017 | val 0.66856
  Epoch 020 - train 0.40826 | val 0.66063
  Epoch 030 - train 0.38905 | val 0.66051
  Regression -> MSE: 0.000201, MAE: 0.010797, R²: -0.3243
  Directional -> Accuracy: 0.5000, MCC: 0.1376, F1: 0.3333

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.45322 | val 0.84166
  Epoch 020 - train 0.42707 | val 0.93616
  Epoch 024 - train 0.46035 | val 0.96053
  Regression -> MSE: 0.000279, MAE: 0.012025, R²: -0.2281
  Directional -> Accuracy: 0.4595, MCC: 0.1050, F1: 0.0476

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.47751 | val 0.66848
  Epoch 020 - train 0.45812 | val 0.66233
  Epoch 021 - train 0.43589 | val 0.67139
  Regression -> MSE: 0.000148, MAE: 0.008554, R²: -0.0290
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.43551 | val 0.54089
  Epoch 020 - train 0.40293 | val 0.55254
  Epoch 021 - train 0.44367 | val 0.55280
  Regression -> MSE: 0.000176, MAE: 0.010320, R²: -0.0639
  Directional -> Accuracy: 0.4923, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.49266 | val 0.67603
  Epoch 020 - train 0.48325 | val 0.66604
  Epoch 021 - train 0.47928 | val 0.66135
  Regression -> MSE: 0.000087, MAE: 0.007122, R²: -0.0086
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.45377 | val 0.79350
  Epoch 020 - train 0.45937 | val 0.77197
  Epoch 021 - train 0.45502 | val 0.77086
  Regression -> MSE: 0.000213, MAE: 0.011284, R²: -0.0088
  Directional -> Accuracy: 0.4769, MCC: 0.0000, F1: 0.6458

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.41723 | val 0.34791
  Epoch 020 - train 0.40139 | val 0.33253
  Epoch 030 - train 0.40254 | val 0.33490
  Regression -> MSE: 0.000093, MAE: 0.007913, R²: -0.0335
  Directional -> Accuracy: 0.5818, MCC: 0.1733, F1: 0.5818

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.53361 | val 0.45737
  Epoch 020 - train 0.47734 | val 0.49839
  Epoch 025 - train 0.52829 | val 0.49196
  Regression -> MSE: 0.000102, MAE: 0.008627, R²: -0.0233
  Directional -> Accuracy: 0.4000, MCC: -0.1323, F1: 0.5574

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.54948 | val 0.50623
  Epoch 020 - train 0.50774 | val 0.49430
  Epoch 021 - train 0.54914 | val 0.49450
  Regression -> MSE: 0.000255, MAE: 0.013339, R²: -0.0747
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.44155 | val 0.52718
  Epoch 020 - train 0.43846 | val 0.52323
  Epoch 024 - train 0.43516 | val 0.52302
  Regression -> MSE: 0.000221, MAE: 0.009213, R²: -0.3057
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.45994 | val 0.32165
  Epoch 020 - train 0.46627 | val 0.37343
  Epoch 026 - train 0.45322 | val 0.36532
  Regression -> MSE: 0.000243, MAE: 0.012108, R²: -0.0030
  Directional -> Accuracy: 0.5500, MCC: 0.0000, F1: 0.7097

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.54756 | val 1.17580
  Epoch 020 - train 0.53164 | val 1.19851
  Epoch 021 - train 0.52028 | val 1.18878
  Regression -> MSE: 0.000237, MAE: 0.010172, R²: -0.0038
  Directional -> Accuracy: 0.4762, MCC: 0.0000, F1: 0.6452

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.53715 | val 0.71201
  Epoch 020 - train 0.46411 | val 0.74969
  Epoch 021 - train 0.45310 | val 0.74214
  Regression -> MSE: 0.000141, MAE: 0.008452, R²: -0.0251
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.45622 | val 0.67428
  Epoch 020 - train 0.46160 | val 0.68617
  Epoch 024 - train 0.42413 | val 0.68459
  Regression -> MSE: 0.000196, MAE: 0.010882, R²: -0.0711
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.38725 | val 0.58614
  Epoch 020 - train 0.39374 | val 0.58777
  Epoch 021 - train 0.38549 | val 0.58677
  Regression -> MSE: 0.000272, MAE: 0.010666, R²: -0.0265
  Directional -> Accuracy: 0.5278, MCC: 0.0319, F1: 0.5952

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.45938 | val 0.71384
  Epoch 020 - train 0.41438 | val 0.73849
  Epoch 021 - train 0.41824 | val 0.74903
  Regression -> MSE: 0.000195, MAE: 0.010815, R²: -0.0652
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.45003 | val 0.43644
  Epoch 020 - train 0.41872 | val 0.44299
  Epoch 029 - train 0.41972 | val 0.44230
  Regression -> MSE: 0.000460, MAE: 0.016539, R²: -0.3230
  Directional -> Accuracy: 0.4242, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.47737 | val 0.25064
  Epoch 020 - train 0.46809 | val 0.24903
  Epoch 021 - train 0.48193 | val 0.25182
  Regression -> MSE: 0.000123, MAE: 0.008450, R²: -0.1637
  Directional -> Accuracy: 0.4762, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.53060 | val 1.07989
  Epoch 020 - train 0.48702 | val 0.98850
  Epoch 021 - train 0.49801 | val 0.96986
  Regression -> MSE: 0.000221, MAE: 0.011246, R²: -0.0051
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.46490 | val 1.05654
  Epoch 020 - train 0.47963 | val 1.05963
  Epoch 021 - train 0.45590 | val 1.05948
  Regression -> MSE: 0.000080, MAE: 0.006970, R²: -0.0788
  Directional -> Accuracy: 0.3913, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.46029 | val 0.26832
  Epoch 020 - train 0.45115 | val 0.26029
  Epoch 021 - train 0.43970 | val 0.26136
  Regression -> MSE: 0.000319, MAE: 0.014288, R²: -0.0233
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.42956 | val 0.64801
  Epoch 020 - train 0.42535 | val 0.64367
  Epoch 021 - train 0.42121 | val 0.64388
  Regression -> MSE: 0.000078, MAE: 0.006928, R²: 0.0020
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.47955 | val 0.63411
  Epoch 020 - train 0.45275 | val 0.62969
  Epoch 021 - train 0.47588 | val 0.62841
  Regression -> MSE: 0.000303, MAE: 0.014398, R²: -0.0079
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.50478 | val 0.52118
  Epoch 020 - train 0.41081 | val 0.51557
  Epoch 030 - train 0.42336 | val 0.52374
  Regression -> MSE: 0.000106, MAE: 0.007369, R²: -0.0424
  Directional -> Accuracy: 0.4286, MCC: -0.2282, F1: 0.5556

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.54243 | val 0.76281
  Epoch 020 - train 0.50827 | val 0.76380
  Epoch 021 - train 0.50117 | val 0.75775
  Regression -> MSE: 0.000181, MAE: 0.010534, R²: -0.0341
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.47204 | val 0.53786
  Epoch 020 - train 0.41103 | val 0.54141
  Epoch 023 - train 0.45813 | val 0.54600
  Regression -> MSE: 0.000227, MAE: 0.011647, R²: -0.0049
  Directional -> Accuracy: 0.5273, MCC: -0.0585, F1: 0.6829

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.43190 | val 0.61312
  Epoch 020 - train 0.42934 | val 0.65359
  Epoch 023 - train 0.43925 | val 0.66896
  Regression -> MSE: 0.000095, MAE: 0.007772, R²: -0.0071
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.50916 | val 1.03221
  Epoch 020 - train 0.51958 | val 1.01112
  Epoch 021 - train 0.50625 | val 1.01786
  Regression -> MSE: 0.000171, MAE: 0.010468, R²: -0.0280
  Directional -> Accuracy: 0.4906, MCC: 0.0000, F1: 0.0000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.42314 | val 0.83139

[I 2026-02-22 23:01:11,052] Trial 88 finished with value: -0.011716648580362981 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.6000000000000001, 'batch_size': 16, 'learning_rate': 2.566509709614597e-05, 'weight_decay': 4.9546047572832714e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 1.3044579413966504, 'early_stopping_min_delta': 0.005519339373539032}. Best is trial 31 with value: -0.011425014985750452.

  Epoch 030 - train 0.43842 | val 0.80141
  Regression -> MSE: 0.000256, MAE: 0.012740, R²: -0.0672
  Directional -> Accuracy: 0.5167, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: regression
Sequence length: 6
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.39883 | val 1.26194
  Epoch 012 - train 0.39809 | val 1.37810
  Regression -> MSE: 0.000248, MAE: 0.012600, R²: -0.0071
  Directional -> Accuracy: 0.4937, MCC: 0.1595, F1: 0.6296

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 82). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.45195 | val 0.43827
  Epoch 013 - train 0.40214 | val 0.44316
  Regression -> MSE: 0.000657, MAE: 0.018979, R²: 0.0294
  Directional -> Accuracy: 0.5625, MCC: 0.0000, F1: 0.7200

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 82). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.43945 | val 1.06340
  Epoch 011 - train 0.45794 | val 1.07913
  Regression -> MSE: 0.000347, MAE: 0.015194, R²: 0.0007
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.36650 | val 0.42749
  Epoch 013 - train 0.36816 | val 0.54698
  Regression -> MSE: 0.000362, MAE: 0.014720, R²: -0.0184
  Directional -> Accuracy: 0.5584, MCC: 0.1289, F1: 0.5526

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.41600 | val 0.37800
  Epoch 020 - train 0.41057 | val 0.40890
  Regression -> MSE: 0.000208, MAE: 0.009922, R²: -0.0495
  Directional -> Accuracy: 0.6038, MCC: 0.3024, F1: 0.7273

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.38884 | val 1.44354
  Epoch 017 - train 0.36788 | val 1.53011
  Regression -> MSE: 0.000541, MAE: 0.018475, R²: -0.0896
  Directional -> Accuracy: 0.4634, MCC: 0.0000, F1: 0.6333

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.44438 | val 0.75525
  Epoch 012 - train 0.43008 | val 0.69307
  Regression -> MSE: 0.000256, MAE: 0.012221, R²: 0.0039
  Directional -> Accuracy: 0.5211, MCC: 0.0299, F1: 0.4516

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 82). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 82). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.37600 | val 1.06211
  Epoch 011 - train 0.38600 | val 1.11091
  Regression -> MSE: 0.000687, MAE: 0.020734, R²: -0.2127
  Directional -> Accuracy: 0.4043, MCC: 0.0000, F1: 0.5758

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.41069 | val 0.83394
  Epoch 012 - train 0.42457 | val 0.93164
  Regression -> MSE: 0.000380, MAE: 0.015652, R²: 0.0129
  Directional -> Accuracy: 0.4884, MCC: 0.0320, F1: 0.5000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 82). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 82). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.43418 | val 0.82276
  Epoch 011 - train 0.41968 | val 0.76241
  Regression -> MSE: 0.000238, MAE: 0.011677, R²: 0.0026
  Directional -> Accuracy: 0.4722, MCC: 0.0574, F1: 0.5870

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.40384 | val 0.98138
  Epoch 011 - train 0.40192 | val 0.94973
  Regression -> MSE: 0.000304, MAE: 0.013789, R²: 0.0105
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.43556 | val 0.80230
  Epoch 011 - train 0.43666 | val 0.77391
  Regression -> MSE: 0.000651, MAE: 0.018899, R²: 0.0114
  Directional -> Accuracy: 0.5500, MCC: 0.1809, F1: 0.2286

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.43566 | val 0.55033
  Epoch 011 - train 0.39540 | val 0.64356
  Regression -> MSE: 0.000148, MAE: 0.009354, R²: -0.0095
  Directional -> Accuracy: 0.6222, MCC: 0.2357, F1: 0.5405

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 82). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.36486 | val 0.71567
  Epoch 016 - train 0.35927 | val 0.78017
  Regression -> MSE: 0.000218, MAE: 0.010719, R²: 0.0319
  Directional -> Accuracy: 0.5556, MCC: 0.1256, F1: 0.6216

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.38273 | val 1.50216
  Epoch 012 - train 0.39593 | val 1.65837
  Regression -> MSE: 0.000388, MAE: 0.016627, R²: -0.0134
  Directional -> Accuracy: 0.5185, MCC: 0.0626, F1: 0.6061

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.42938 | val 0.56515
  Epoch 014 - train 0.43298 | val 0.54039
  Regression -> MSE: 0.000103, MAE: 0.007717, R²: 0.0255
  Directional -> Accuracy: 0.5833, MCC: 0.1488, F1: 0.6512

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.42150 | val 1.11513
  Epoch 011 - train 0.38146 | val 1.11659
  Regression -> MSE: 0.000160, MAE: 0.010046, R²: -0.0105
  Directional -> Accuracy: 0.6066, MCC: 0.0000, F1: 0.7551

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.40740 | val 0.69087
  Epoch 011 - train 0.39314 | val 0.66400
  Regression -> MSE: 0.000295, MAE: 0.014022, R²: -0.0896
  Directional -> Accuracy: 0.3974, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.35377 | val 0.70305
  Epoch 019 - train 0.33277 | val 0.74884
  Regression -> MSE: 0.000183, MAE: 0.010167, R²: -0.1813
  Directional -> Accuracy: 0.4627, MCC: 0.0915, F1: 0.2174

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 82). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.45192 | val 0.99605
  Epoch 015 - train 0.41024 | val 1.01579
  Regression -> MSE: 0.000354, MAE: 0.014216, R²: -0.5300
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.41170 | val 0.80038
  Epoch 011 - train 0.43135 | val 0.83024
  Regression -> MSE: 0.000162, MAE: 0.009196, R²: -0.0863
  Directional -> Accuracy: 0.3800, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 82). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 82). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 82). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.42092 | val 0.53095
  Epoch 011 - train 0.41729 | val 0.53133
  Regression -> MSE: 0.000188, MAE: 0.010851, R²: -0.0331
  Directional -> Accuracy: 0.4853, MCC: -0.1222, F1: 0.6535

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.42203 | val 0.77892
  Epoch 015 - train 0.42572 | val 0.85545
  Regression -> MSE: 0.000080, MAE: 0.006874, R²: 0.0272
  Directional -> Accuracy: 0.6500, MCC: 0.2652, F1: 0.7586

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.42103 | val 0.96697
  Epoch 014 - train 0.39353 | val 0.80517
  Regression -> MSE: 0.000216, MAE: 0.010990, R²: -0.0012
  Directional -> Accuracy: 0.6176, MCC: 0.2762, F1: 0.4348

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.36208 | val 0.28423
  Epoch 018 - train 0.34307 | val 0.28719
  Regression -> MSE: 0.000112, MAE: 0.008502, R²: -0.2435
  Directional -> Accuracy: 0.5172, MCC: 0.1180, F1: 0.3636

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.43022 | val 0.18456
  Epoch 011 - train 0.41654 | val 0.18328
  Regression -> MSE: 0.000136, MAE: 0.009616, R²: -0.0894
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.41306 | val 0.20151
  Epoch 011 - train 0.40649 | val 0.22301
  Regression -> MSE: 0.000298, MAE: 0.013738, R²: -0.0232
  Directional -> Accuracy: 0.6000, MCC: 0.0000, F1: 0.7500

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.41891 | val 0.62698
  Epoch 011 - train 0.42368 | val 0.62678
  Regression -> MSE: 0.000186, MAE: 0.008007, R²: -0.1575
  Directional -> Accuracy: 0.4407, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.43471 | val 0.43833
  Epoch 013 - train 0.40569 | val 0.51296
  Regression -> MSE: 0.000232, MAE: 0.011885, R²: -0.0055
  Directional -> Accuracy: 0.4773, MCC: -0.1439, F1: 0.6349

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.45548 | val 0.76884
  Epoch 011 - train 0.44002 | val 0.77032
  Regression -> MSE: 0.000259, MAE: 0.010809, R²: -0.0003
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.43424 | val 0.79160
  Epoch 011 - train 0.40799 | val 0.83855
  Regression -> MSE: 0.000141, MAE: 0.008445, R²: -0.0044
  Directional -> Accuracy: 0.5435, MCC: 0.0000, F1: 0.7042

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.40589 | val 0.73632
  Epoch 014 - train 0.39403 | val 0.85357
  Regression -> MSE: 0.000197, MAE: 0.010599, R²: -0.0590
  Directional -> Accuracy: 0.5000, MCC: 0.0142, F1: 0.4091

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.39432 | val 0.78108
  Epoch 014 - train 0.37937 | val 0.90784
  Regression -> MSE: 0.000278, MAE: 0.011207, R²: -0.0659
  Directional -> Accuracy: 0.5333, MCC: 0.1052, F1: 0.4928

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 82). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.42067 | val 0.50464
  Epoch 020 - train 0.38682 | val 0.52724
  Regression -> MSE: 0.000192, MAE: 0.011380, R²: -0.1865
  Directional -> Accuracy: 0.5366, MCC: 0.2210, F1: 0.6780

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.38595 | val 0.51352
  Epoch 020 - train 0.35263 | val 0.63026
  Regression -> MSE: 0.000270, MAE: 0.012908, R²: -0.2615
  Directional -> Accuracy: 0.5217, MCC: 0.1798, F1: 0.6452

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.40308 | val 0.44601
  Epoch 019 - train 0.36268 | val 0.46894
  Regression -> MSE: 0.000769, MAE: 0.023829, R²: -1.2347
  Directional -> Accuracy: 0.4203, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.43174 | val 0.25247
  Epoch 020 - train 0.35487 | val 0.26241
  Regression -> MSE: 0.000172, MAE: 0.009624, R²: -0.6978
  Directional -> Accuracy: 0.6222, MCC: 0.3089, F1: 0.4848

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.41694 | val 0.81000
  Epoch 011 - train 0.40174 | val 0.83879
  Regression -> MSE: 0.000220, MAE: 0.011349, R²: -0.0414
  Directional -> Accuracy: 0.4746, MCC: 0.0000, F1: 0.6437

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.42811 | val 1.27312
  Epoch 012 - train 0.42298 | val 1.31951
  Regression -> MSE: 0.000085, MAE: 0.007270, R²: -0.0694
  Directional -> Accuracy: 0.5306, MCC: 0.0209, F1: 0.6102

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 82). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 82). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 82). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 82). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.41065 | val 0.31163
  Epoch 019 - train 0.36609 | val 0.32471
  Regression -> MSE: 0.000370, MAE: 0.015701, R²: -0.1793
  Directional -> Accuracy: 0.3810, MCC: 0.0574, F1: 0.5000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 82). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.39049 | val 0.20944
  Epoch 015 - train 0.39649 | val 0.24089
  Regression -> MSE: 0.000242, MAE: 0.011082, R²: -0.0592
  Directional -> Accuracy: 0.4390, MCC: -0.2146, F1: 0.5965

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 82). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 82). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.38234 | val 1.48572
  Epoch 012 - train 0.36430 | val 1.90588
  Regression -> MSE: 0.000081, MAE: 0.007107, R²: 0.0097
  Directional -> Accuracy: 0.5065, MCC: 0.0000, F1: 0.6724

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 82). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 82). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.42693 | val 0.60990
  Epoch 013 - train 0.43416 | val 0.59118
  Regression -> MSE: 0.000387, MAE: 0.015761, R²: -0.0467
  Directional -> Accuracy: 0.4898, MCC: 0.0000, F1: 0.6575

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.37947 | val 0.63529
  Epoch 020 - train 0.36650 | val 0.60929
  Regression -> MSE: 0.000096, MAE: 0.006777, R²: -0.0100
  Directional -> Accuracy: 0.6170, MCC: 0.2002, F1: 0.7429

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.36650 | val 0.95866
  Epoch 011 - train 0.39053 | val 0.92674
  Regression -> MSE: 0.000206, MAE: 0.011363, R²: -0.0800
  Directional -> Accuracy: 0.3571, MCC: 0.0000, F1: 0.5263

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.42021 | val 0.86487
  Epoch 011 - train 0.42113 | val 0.93435
  Regression -> MSE: 0.000217, MAE: 0.011397, R²: -0.0017
  Directional -> Accuracy: 0.6724, MCC: 0.3763, F1: 0.6545

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.39133 | val 0.69222
  Epoch 012 - train 0.37660 | val 0.85240
  Regression -> MSE: 0.000090, MAE: 0.007594, R²: -0.0036
  Directional -> Accuracy: 0.4915, MCC: 0.0000, F1: 0.6591

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.41625 | val 1.24622
  Epoch 013 - train 0.41075 | val 1.42353
  Regression -> MSE: 0.000157, MAE: 0.009870, R²: 0.0082
  Directional -> Accuracy: 0.5179, MCC: -0.0271, F1: 0.6582

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.41600 | val 0.81043
  Epoch 011 - train 0.39994 | val 0.89483
  Regression -> MSE: 0.000113, MAE: 0.008672, R²: -0.0083
  Directional -> Accuracy: 0.5172, MCC: 0.0000, F1: 0.6818

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...

[I 2026-02-22 23:01:39,168] Trial 89 finished with value: -0.012003628398941426 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 6, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.4, 'dropout': 0.2, 'batch_size': 64, 'learning_rate': 0.001398735718890165, 'weight_decay': 5.147412755445001e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 1.8669433861820157, 'early_stopping_min_delta': 0.00424703309907354}. Best is trial 31 with value: -0.011425014985750452.

  Epoch 010 - train 0.42336 | val 1.40041
  Epoch 011 - train 0.41484 | val 1.52463
  Regression -> MSE: 0.000232, MAE: 0.012046, R²: -0.0087
  Directional -> Accuracy: 0.5238, MCC: 0.0086, F1: 0.0625

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.36516 | val 0.54463
  Epoch 016 - train 0.35397 | val 0.56788
  Regression -> MSE: 0.000250, MAE: 0.012624, R²: -0.0096
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.37850 | val 0.33866
  Epoch 016 - train 0.34775 | val 0.35938
  Regression -> MSE: 0.000684, MAE: 0.019305, R²: 0.0012
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.39849 | val 0.66220
  Epoch 016 - train 0.36608 | val 0.66540
  Regression -> MSE: 0.000316, MAE: 0.014415, R²: -0.0171
  Directional -> Accuracy: 0.5319, MCC: 0.0850, F1: 0.4762

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.29908 | val 0.33739
  Epoch 016 - train 0.28865 | val 0.33820
  Regression -> MSE: 0.000351, MAE: 0.014609, R²: -0.0045
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.37607 | val 0.35890
  Epoch 020 - train 0.35538 | val 0.35149
  Regression -> MSE: 0.000216, MAE: 0.010102, R²: -0.0613
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.35893 | val 0.81001
  Epoch 016 - train 0.36249 | val 0.85401
  Regression -> MSE: 0.000562, MAE: 0.018354, R²: -0.0129
  Directional -> Accuracy: 0.4468, MCC: -0.1357, F1: 0.5938

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.39348 | val 0.49807
  Epoch 016 - train 0.38405 | val 0.49889
  Regression -> MSE: 0.000249, MAE: 0.011877, R²: -0.0135
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.41133 | val 0.47057
  Epoch 016 - train 0.36576 | val 0.47917
  Regression -> MSE: 0.000609, MAE: 0.019458, R²: -0.0188
  Directional -> Accuracy: 0.5682, MCC: -0.0066, F1: 0.1739

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.37375 | val 0.44350
  Epoch 016 - train 0.34190 | val 0.45261
  Regression -> MSE: 0.000407, MAE: 0.016182, R²: -0.0604
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.36212 | val 0.50919
  Epoch 016 - train 0.36939 | val 0.53512
  Regression -> MSE: 0.000242, MAE: 0.011919, R²: -0.0015
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.36380 | val 0.60771
  Epoch 016 - train 0.32017 | val 0.70855
  Regression -> MSE: 0.000315, MAE: 0.013560, R²: -0.0138
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.34657 | val 0.45580
  Epoch 016 - train 0.34838 | val 0.47474
  Regression -> MSE: 0.000678, MAE: 0.019483, R²: -0.0005
  Directional -> Accuracy: 0.5172, MCC: 0.1325, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.36733 | val 0.39107
  Epoch 016 - train 0.36498 | val 0.43017
  Regression -> MSE: 0.000139, MAE: 0.009264, R²: -0.0086
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.35614 | val 0.59137
  Epoch 016 - train 0.35581 | val 0.61961
  Regression -> MSE: 0.000226, MAE: 0.010847, R²: -0.0057
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.34998 | val 1.04147
  Epoch 016 - train 0.34242 | val 1.33929
  Regression -> MSE: 0.000360, MAE: 0.016134, R²: 0.0048
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.41016 | val 0.36935
  Epoch 016 - train 0.36794 | val 0.37619
  Regression -> MSE: 0.000108, MAE: 0.007997, R²: 0.0027
  Directional -> Accuracy: 0.4714, MCC: -0.2545, F1: 0.6408

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.36506 | val 0.68783
  Epoch 016 - train 0.34462 | val 0.71156
  Regression -> MSE: 0.000163, MAE: 0.010208, R²: -0.0451
  Directional -> Accuracy: 0.4407, MCC: -0.0921, F1: 0.4762

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.38543 | val 0.38417
  Epoch 016 - train 0.37123 | val 0.43680
  Regression -> MSE: 0.000273, MAE: 0.013109, R²: -0.0031
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.33830 | val 0.50383
  Epoch 016 - train 0.31360 | val 0.51892
  Regression -> MSE: 0.000172, MAE: 0.009275, R²: -0.1529
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.39805 | val 0.59361
  Epoch 016 - train 0.36376 | val 0.60122
  Regression -> MSE: 0.000235, MAE: 0.011015, R²: -0.0376
  Directional -> Accuracy: 0.4267, MCC: -0.1392, F1: 0.4267

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.37389 | val 0.49648
  Epoch 016 - train 0.38903 | val 0.52209
  Regression -> MSE: 0.000146, MAE: 0.008503, R²: -0.0211
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.35608 | val 0.44283
  Epoch 016 - train 0.33498 | val 0.44046
  Regression -> MSE: 0.000164, MAE: 0.010297, R²: 0.0093
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.37540 | val 0.46476
  Epoch 016 - train 0.37386 | val 0.50468
  Regression -> MSE: 0.000086, MAE: 0.007077, R²: -0.0063
  Directional -> Accuracy: 0.5690, MCC: 0.1089, F1: 0.6377

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.36953 | val 0.45916
  Epoch 020 - train 0.34402 | val 0.46588
  Regression -> MSE: 0.000210, MAE: 0.011112, R²: 0.0096
  Directional -> Accuracy: 0.5152, MCC: 0.1086, F1: 0.6364

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.34078 | val 0.29677
  Epoch 020 - train 0.32683 | val 0.29040
  Regression -> MSE: 0.000099, MAE: 0.008104, R²: -0.0760
  Directional -> Accuracy: 0.5179, MCC: 0.0437, F1: 0.5263

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.37749 | val 0.26315
  Epoch 016 - train 0.39322 | val 0.26366
  Regression -> MSE: 0.000103, MAE: 0.008714, R²: -0.0013
  Directional -> Accuracy: 0.6522, MCC: 0.3643, F1: 0.6800

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.38533 | val 0.34395
  Epoch 020 - train 0.36534 | val 0.33988
  Regression -> MSE: 0.000236, MAE: 0.012665, R²: -0.0195
  Directional -> Accuracy: 0.5814, MCC: 0.0908, F1: 0.6897

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.34672 | val 0.43838
  Epoch 020 - train 0.32517 | val 0.43287
  Regression -> MSE: 0.000182, MAE: 0.008016, R²: -0.0962
  Directional -> Accuracy: 0.5965, MCC: 0.1707, F1: 0.6567

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.42046 | val 0.30223
  Epoch 016 - train 0.39099 | val 0.31529
  Regression -> MSE: 0.000236, MAE: 0.011903, R²: 0.0028
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.37428 | val 0.69293
  Epoch 016 - train 0.35105 | val 0.71216
  Regression -> MSE: 0.000233, MAE: 0.010108, R²: -0.0130
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.39556 | val 0.48556
  Epoch 020 - train 0.37978 | val 0.48279
  Regression -> MSE: 0.000135, MAE: 0.008234, R²: -0.0020
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.39713 | val 0.49398
  Epoch 016 - train 0.37580 | val 0.50532
  Regression -> MSE: 0.000197, MAE: 0.010633, R²: -0.0465
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.33042 | val 0.43409
  Epoch 016 - train 0.32002 | val 0.43165
  Regression -> MSE: 0.000279, MAE: 0.010931, R²: -0.0645
  Directional -> Accuracy: 0.4384, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.36206 | val 0.30021
  Epoch 016 - train 0.36834 | val 0.30734
  Regression -> MSE: 0.000166, MAE: 0.010311, R²: 0.0066
  Directional -> Accuracy: 0.5263, MCC: 0.0679, F1: 0.3077

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.34288 | val 0.37683
  Epoch 016 - train 0.32882 | val 0.38101
  Regression -> MSE: 0.000184, MAE: 0.010477, R²: -0.0208
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.33723 | val 0.33358
  Epoch 020 - train 0.32021 | val 0.33635
  Regression -> MSE: 0.000334, MAE: 0.011643, R²: 0.0259
  Directional -> Accuracy: 0.5522, MCC: 0.0807, F1: 0.6154

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.39609 | val 0.20580
  Epoch 020 - train 0.36636 | val 0.20401
  Regression -> MSE: 0.000125, MAE: 0.008485, R²: -0.1899
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.38256 | val 0.55199
  Epoch 016 - train 0.37548 | val 0.55939
  Regression -> MSE: 0.000219, MAE: 0.011296, R²: -0.0018
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.35805 | val 0.73150
  Epoch 016 - train 0.34859 | val 0.74487
  Regression -> MSE: 0.000084, MAE: 0.007148, R²: -0.0782
  Directional -> Accuracy: 0.4894, MCC: 0.0699, F1: 0.4545

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.38286 | val 0.25232
  Epoch 016 - train 0.34047 | val 0.24795
  Regression -> MSE: 0.000314, MAE: 0.014160, R²: -0.0202
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.37328 | val 0.21514
  Epoch 016 - train 0.37837 | val 0.22029
  Regression -> MSE: 0.000260, MAE: 0.011488, R²: -0.0646
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.36471 | val 0.48003
  Epoch 016 - train 0.35183 | val 0.47547
  Regression -> MSE: 0.000082, MAE: 0.007151, R²: -0.0147
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.35871 | val 0.48068
  Epoch 016 - train 0.35124 | val 0.48846
  Regression -> MSE: 0.000311, MAE: 0.014559, R²: -0.0141
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.38151 | val 0.43567
  Epoch 016 - train 0.39614 | val 0.44021
  Regression -> MSE: 0.000099, MAE: 0.007145, R²: -0.0098
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.45660 | val 0.49142
  Epoch 016 - train 0.41789 | val 0.49623
  Regression -> MSE: 0.000172, MAE: 0.009657, R²: 0.0002
  Directional -> Accuracy: 0.4286, MCC: -0.0711, F1: 0.4615

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.33868 | val 0.43477
  Epoch 016 - train 0.31840 | val 0.46127
  Regression -> MSE: 0.000224, MAE: 0.011801, R²: -0.0060
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.37406 | val 0.44308
  Epoch 016 - train 0.37475 | val 0.47597
  Regression -> MSE: 0.000095, MAE: 0.007799, R²: -0.0318
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.39193 | val 0.63913
  Epoch 016 - train 0.38149 | val 0.64790
  Regression -> MSE: 0.000164, MAE: 0.010274, R²: -0.0026
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.36664 | val 0.49576
  Epoch 016 - train 0.34862 | val 0.50317
  Regression -> MSE: 0.000117, MAE: 0.008929, R²: -0.0110
  Directional -> Accuracy: 0.5357, MCC: 0.1397, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...

[I 2026-02-22 23:01:58,617] Trial 90 finished with value: -0.011414558399902668 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 64, 'learning_rate': 0.00014722048745863505, 'weight_decay': 3.5146957339231114e-06, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 0.8038902503666738, 'early_stopping_min_delta': 0.009514803592115964}. Best is trial 90 with value: -0.011414558399902668.

  Epoch 010 - train 0.36698 | val 0.56825
  Epoch 016 - train 0.37064 | val 0.56598
  Regression -> MSE: 0.000243, MAE: 0.012372, R²: -0.0230
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.36170 | val 0.55617
  Epoch 016 - train 0.35944 | val 0.54744
  Regression -> MSE: 0.000255, MAE: 0.012863, R²: -0.0303
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.33488 | val 0.34443
  Epoch 020 - train 0.33528 | val 0.35539
  Regression -> MSE: 0.000683, MAE: 0.019239, R²: 0.0018
  Directional -> Accuracy: 0.5870, MCC: 0.1462, F1: 0.6545

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.39419 | val 0.69852
  Epoch 016 - train 0.38297 | val 0.69938
  Regression -> MSE: 0.000324, MAE: 0.014558, R²: -0.0445
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.29665 | val 0.39749
  Epoch 016 - train 0.30081 | val 0.44394
  Regression -> MSE: 0.000372, MAE: 0.014976, R²: -0.0651
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.35241 | val 0.36808
  Epoch 016 - train 0.36837 | val 0.37179
  Regression -> MSE: 0.000209, MAE: 0.010264, R²: -0.0266
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.35892 | val 0.79128
  Epoch 020 - train 0.34895 | val 0.79493
  Regression -> MSE: 0.000539, MAE: 0.017839, R²: 0.0286
  Directional -> Accuracy: 0.6596, MCC: 0.3261, F1: 0.6000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.37493 | val 0.48122
  Epoch 020 - train 0.36295 | val 0.47190
  Regression -> MSE: 0.000249, MAE: 0.011831, R²: -0.0127
  Directional -> Accuracy: 0.5797, MCC: 0.0156, F1: 0.1714

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.37490 | val 0.58529
  Epoch 016 - train 0.37439 | val 0.59504
  Regression -> MSE: 0.000654, MAE: 0.020395, R²: -0.0953
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.33441 | val 0.46599
  Epoch 016 - train 0.34856 | val 0.47219
  Regression -> MSE: 0.000391, MAE: 0.015930, R²: -0.0195
  Directional -> Accuracy: 0.5918, MCC: 0.2014, F1: 0.6000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.36843 | val 0.50031
  Epoch 016 - train 0.37355 | val 0.50192
  Regression -> MSE: 0.000244, MAE: 0.011612, R²: -0.0122
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.37465 | val 0.56089
  Epoch 016 - train 0.31726 | val 0.57449
  Regression -> MSE: 0.000328, MAE: 0.013648, R²: -0.0550
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.40878 | val 0.46285
  Epoch 016 - train 0.37806 | val 0.48151
  Regression -> MSE: 0.000681, MAE: 0.019553, R²: -0.0053
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.39255 | val 0.37026
  Epoch 016 - train 0.41712 | val 0.38157
  Regression -> MSE: 0.000155, MAE: 0.009843, R²: -0.1200
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.33217 | val 0.51398
  Epoch 016 - train 0.31105 | val 0.51592
  Regression -> MSE: 0.000226, MAE: 0.010737, R²: -0.0049
  Directional -> Accuracy: 0.5410, MCC: 0.0869, F1: 0.6410

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.33088 | val 0.89200
  Epoch 016 - train 0.34350 | val 0.89042
  Regression -> MSE: 0.000365, MAE: 0.016011, R²: -0.0066
  Directional -> Accuracy: 0.4423, MCC: -0.1782, F1: 0.2162

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.38487 | val 0.37007
  Epoch 016 - train 0.37953 | val 0.37271
  Regression -> MSE: 0.000108, MAE: 0.008000, R²: -0.0030
  Directional -> Accuracy: 0.5000, MCC: -0.0375, F1: 0.5977

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.38170 | val 0.71902
  Epoch 016 - train 0.38408 | val 0.76448
  Regression -> MSE: 0.000162, MAE: 0.010168, R²: -0.0368
  Directional -> Accuracy: 0.3729, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.37463 | val 0.49477
  Epoch 016 - train 0.35926 | val 0.56086
  Regression -> MSE: 0.000301, MAE: 0.014193, R²: -0.1064
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.33726 | val 0.54071
  Epoch 016 - train 0.29857 | val 0.54185
  Regression -> MSE: 0.000155, MAE: 0.008862, R²: -0.0375
  Directional -> Accuracy: 0.5538, MCC: 0.0256, F1: 0.6667

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.38341 | val 0.59672
  Epoch 020 - train 0.36028 | val 0.58411
  Regression -> MSE: 0.000232, MAE: 0.010538, R²: -0.0261
  Directional -> Accuracy: 0.6667, MCC: 0.3214, F1: 0.7191

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.37672 | val 0.49701
  Epoch 016 - train 0.36359 | val 0.56571
  Regression -> MSE: 0.000146, MAE: 0.008537, R²: -0.0216
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.33867 | val 0.45542
  Epoch 016 - train 0.31794 | val 0.46480
  Regression -> MSE: 0.000175, MAE: 0.010231, R²: -0.0581
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.36500 | val 0.46411
  Epoch 016 - train 0.38018 | val 0.46346
  Regression -> MSE: 0.000088, MAE: 0.007194, R²: -0.0325
  Directional -> Accuracy: 0.4828, MCC: -0.0882, F1: 0.5833

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.36964 | val 0.48039
  Epoch 016 - train 0.35579 | val 0.49164
  Regression -> MSE: 0.000213, MAE: 0.011105, R²: -0.0035
  Directional -> Accuracy: 0.4394, MCC: -0.1052, F1: 0.5432

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.33965 | val 0.29691
  Epoch 020 - train 0.31253 | val 0.28561
  Regression -> MSE: 0.000094, MAE: 0.007959, R²: -0.0229
  Directional -> Accuracy: 0.5714, MCC: 0.2023, F1: 0.5000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.37315 | val 0.28484
  Epoch 020 - train 0.38060 | val 0.26602
  Regression -> MSE: 0.000116, MAE: 0.009150, R²: -0.1292
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.37369 | val 0.35305
  Epoch 016 - train 0.34647 | val 0.36112
  Regression -> MSE: 0.000235, MAE: 0.012715, R²: -0.0169
  Directional -> Accuracy: 0.5581, MCC: -0.1309, F1: 0.7164

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.39269 | val 0.43285
  Epoch 020 - train 0.33936 | val 0.44441
  Regression -> MSE: 0.000195, MAE: 0.008187, R²: -0.1710
  Directional -> Accuracy: 0.5439, MCC: 0.3032, F1: 0.3158

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.39062 | val 0.27628
  Epoch 016 - train 0.39173 | val 0.27668
  Regression -> MSE: 0.000235, MAE: 0.011834, R²: 0.0074
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.38526 | val 0.68477
  Epoch 016 - train 0.35634 | val 0.68714
  Regression -> MSE: 0.000233, MAE: 0.010055, R²: -0.0120
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.39116 | val 0.49330
  Epoch 016 - train 0.37551 | val 0.51546
  Regression -> MSE: 0.000139, MAE: 0.008379, R²: -0.0300
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.39862 | val 0.48336
  Epoch 016 - train 0.38680 | val 0.48002
  Regression -> MSE: 0.000202, MAE: 0.010797, R²: -0.0750
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.31626 | val 0.44888
  Epoch 016 - train 0.31036 | val 0.45210
  Regression -> MSE: 0.000271, MAE: 0.010671, R²: -0.0337
  Directional -> Accuracy: 0.4521, MCC: -0.0983, F1: 0.4872

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.35670 | val 0.30602
  Epoch 016 - train 0.33582 | val 0.31108
  Regression -> MSE: 0.000167, MAE: 0.010361, R²: -0.0000
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.33963 | val 0.40107
  Epoch 016 - train 0.33055 | val 0.41984
  Regression -> MSE: 0.000181, MAE: 0.010371, R²: -0.0081
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.33981 | val 0.33988
  Epoch 020 - train 0.32038 | val 0.34216
  Regression -> MSE: 0.000349, MAE: 0.012347, R²: -0.0185
  Directional -> Accuracy: 0.3881, MCC: -0.1812, F1: 0.2264

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.43376 | val 0.21342
  Epoch 016 - train 0.40461 | val 0.21586
  Regression -> MSE: 0.000110, MAE: 0.008284, R²: -0.0505
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.37429 | val 0.56281
  Epoch 016 - train 0.36995 | val 0.57865
  Regression -> MSE: 0.000219, MAE: 0.011351, R²: -0.0037
  Directional -> Accuracy: 0.4035, MCC: -0.2478, F1: 0.1905

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.39297 | val 0.75305
  Epoch 020 - train 0.38465 | val 0.73716
  Regression -> MSE: 0.000081, MAE: 0.006994, R²: -0.0376
  Directional -> Accuracy: 0.5957, MCC: -0.1162, F1: 0.7467

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.37754 | val 0.30304
  Epoch 016 - train 0.34055 | val 0.29971
  Regression -> MSE: 0.000350, MAE: 0.015693, R²: -0.1372
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.37970 | val 0.19175
  Epoch 016 - train 0.37516 | val 0.20750
  Regression -> MSE: 0.000258, MAE: 0.011487, R²: -0.0580
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.35214 | val 0.43780
  Epoch 020 - train 0.33281 | val 0.44453
  Regression -> MSE: 0.000084, MAE: 0.007226, R²: -0.0407
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.38872 | val 0.47408
  Epoch 020 - train 0.36465 | val 0.46071
  Regression -> MSE: 0.000310, MAE: 0.014487, R²: -0.0113
  Directional -> Accuracy: 0.4681, MCC: -0.0603, F1: 0.3902

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.39744 | val 0.44822
  Epoch 016 - train 0.37296 | val 0.44673
  Regression -> MSE: 0.000102, MAE: 0.007102, R²: -0.0412
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.46081 | val 0.50845
  Epoch 016 - train 0.40368 | val 0.50625
  Regression -> MSE: 0.000172, MAE: 0.009895, R²: -0.0011
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.35465 | val 0.46143
  Epoch 016 - train 0.32842 | val 0.48969
  Regression -> MSE: 0.000225, MAE: 0.011797, R²: -0.0093
  Directional -> Accuracy: 0.5536, MCC: 0.2915, F1: 0.2857

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.37187 | val 0.42754
  Epoch 016 - train 0.35014 | val 0.44024
  Regression -> MSE: 0.000092, MAE: 0.007666, R²: -0.0005
  Directional -> Accuracy: 0.4912, MCC: 0.0254, F1: 0.6133

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.43841 | val 0.83918
  Epoch 016 - train 0.42110 | val 0.88440
  Regression -> MSE: 0.000173, MAE: 0.010324, R²: -0.0568
  Directional -> Accuracy: 0.4815, MCC: 0.0000, F1: 0.0000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.37424 | val 0.56469
  Epoch 016 - train 0.37141 | val 0.59203
  Regression -> MSE: 0.000117, MAE: 0.008990, R²: -0.0070
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...

[I 2026-02-22 23:02:18,573] Trial 91 finished with value: -0.011493379250862 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 64, 'learning_rate': 0.0001771033884514207, 'weight_decay': 3.5148104467935985e-06, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 0.8291193171608334, 'early_stopping_min_delta': 0.00973869233935386}. Best is trial 90 with value: -0.011414558399902668.

  Epoch 010 - train 0.38019 | val 0.59867
  Epoch 016 - train 0.37158 | val 0.61015
  Regression -> MSE: 0.000238, MAE: 0.012422, R²: -0.0025
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.31056 | val 0.43674
  Epoch 016 - train 0.28359 | val 0.52140
  Regression -> MSE: 0.000247, MAE: 0.012523, R²: 0.0014
  Directional -> Accuracy: 0.6104, MCC: 0.2143, F1: 0.5714

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.29887 | val 0.27784
  Epoch 016 - train 0.31412 | val 0.27817
  Regression -> MSE: 0.000686, MAE: 0.019409, R²: -0.0021
  Directional -> Accuracy: 0.5652, MCC: 0.0510, F1: 0.6970

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.32124 | val 0.53369
  Epoch 016 - train 0.30271 | val 0.53766
  Regression -> MSE: 0.000310, MAE: 0.014433, R²: 0.0001
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.25816 | val 0.25186
  Epoch 016 - train 0.24760 | val 0.24023
  Regression -> MSE: 0.000350, MAE: 0.014548, R²: -0.0032
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.33586 | val 0.29333
  Epoch 016 - train 0.30515 | val 0.28919
  Regression -> MSE: 0.000209, MAE: 0.010225, R²: -0.0270
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.28111 | val 0.61099
  Epoch 020 - train 0.28559 | val 0.59245
  Regression -> MSE: 0.000573, MAE: 0.018737, R²: -0.0331
  Directional -> Accuracy: 0.4468, MCC: -0.1069, F1: 0.4348

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.30608 | val 0.37056
  Epoch 020 - train 0.30187 | val 0.37150
  Regression -> MSE: 0.000238, MAE: 0.011894, R²: 0.0294
  Directional -> Accuracy: 0.5507, MCC: 0.2027, F1: 0.5974

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.31811 | val 0.39084
  Epoch 016 - train 0.30627 | val 0.39838
  Regression -> MSE: 0.000616, MAE: 0.019715, R²: -0.0316
  Directional -> Accuracy: 0.4091, MCC: -0.1132, F1: 0.4800

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.29407 | val 0.39382
  Epoch 016 - train 0.29730 | val 0.40722
  Regression -> MSE: 0.000381, MAE: 0.016078, R²: 0.0065
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.28412 | val 0.38801
  Epoch 016 - train 0.28945 | val 0.39385
  Regression -> MSE: 0.000241, MAE: 0.011953, R²: 0.0020
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.27854 | val 0.48241
  Epoch 016 - train 0.28345 | val 0.55823
  Regression -> MSE: 0.000313, MAE: 0.013557, R²: -0.0079
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.30830 | val 0.35544
  Epoch 016 - train 0.30088 | val 0.38980
  Regression -> MSE: 0.000688, MAE: 0.019751, R²: -0.0163
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.30483 | val 0.39315
  Epoch 016 - train 0.28649 | val 0.51119
  Regression -> MSE: 0.000141, MAE: 0.009007, R²: -0.0175
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.25850 | val 0.39156
  Epoch 016 - train 0.26361 | val 0.39445
  Regression -> MSE: 0.000226, MAE: 0.010698, R²: -0.0044
  Directional -> Accuracy: 0.5246, MCC: 0.1281, F1: 0.1714

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.30451 | val 0.66872
  Epoch 016 - train 0.28167 | val 0.66704
  Regression -> MSE: 0.000366, MAE: 0.016000, R²: -0.0108
  Directional -> Accuracy: 0.5192, MCC: -0.1296, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.32735 | val 0.32227
  Epoch 016 - train 0.31156 | val 0.31917
  Regression -> MSE: 0.000112, MAE: 0.008269, R²: -0.0402
  Directional -> Accuracy: 0.4571, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.28180 | val 0.53642
  Epoch 016 - train 0.28405 | val 0.56110
  Regression -> MSE: 0.000161, MAE: 0.010150, R²: -0.0344
  Directional -> Accuracy: 0.4068, MCC: -0.2804, F1: 0.5333

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.29893 | val 0.30057
  Epoch 016 - train 0.31491 | val 0.30891
  Regression -> MSE: 0.000274, MAE: 0.012958, R²: -0.0055
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.26927 | val 0.39853
  Epoch 020 - train 0.25991 | val 0.38663
  Regression -> MSE: 0.000182, MAE: 0.009652, R²: -0.2198
  Directional -> Accuracy: 0.4923, MCC: -0.0289, F1: 0.5479

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.28808 | val 0.45713
  Epoch 016 - train 0.28943 | val 0.46905
  Regression -> MSE: 0.000246, MAE: 0.011218, R²: -0.0881
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.33377 | val 0.37630
  Epoch 020 - train 0.30059 | val 0.37489
  Regression -> MSE: 0.000154, MAE: 0.008741, R²: -0.0725
  Directional -> Accuracy: 0.5208, MCC: 0.1816, F1: 0.4651

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.28246 | val 0.35201
  Epoch 016 - train 0.27966 | val 0.35009
  Regression -> MSE: 0.000174, MAE: 0.010208, R²: -0.0511
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0571

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.34514 | val 0.37022
  Epoch 016 - train 0.32172 | val 0.37575
  Regression -> MSE: 0.000093, MAE: 0.007436, R²: -0.0871
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.29893 | val 0.38658
  Epoch 016 - train 0.28929 | val 0.41849
  Regression -> MSE: 0.000213, MAE: 0.011028, R²: -0.0049
  Directional -> Accuracy: 0.5152, MCC: 0.0051, F1: 0.3600

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.29196 | val 0.25057
  Epoch 020 - train 0.25780 | val 0.23811
  Regression -> MSE: 0.000096, MAE: 0.007957, R²: -0.0466
  Directional -> Accuracy: 0.5893, MCC: 0.2195, F1: 0.5490

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.34254 | val 0.25399
  Epoch 020 - train 0.33503 | val 0.24431
  Regression -> MSE: 0.000128, MAE: 0.009614, R²: -0.2425
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.34333 | val 0.28870
  Epoch 016 - train 0.31162 | val 0.30024
  Regression -> MSE: 0.000238, MAE: 0.012801, R²: -0.0303
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.29926 | val 0.36017
  Epoch 016 - train 0.28633 | val 0.37107
  Regression -> MSE: 0.000186, MAE: 0.008080, R²: -0.1163
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.31111 | val 0.23669
  Epoch 016 - train 0.27498 | val 0.23676
  Regression -> MSE: 0.000236, MAE: 0.011833, R²: 0.0012
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.28263 | val 0.52873
  Epoch 016 - train 0.28061 | val 0.53752
  Regression -> MSE: 0.000236, MAE: 0.010129, R²: -0.0222
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.33173 | val 0.37668
  Epoch 016 - train 0.29866 | val 0.40243
  Regression -> MSE: 0.000135, MAE: 0.008261, R²: 0.0000
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.30142 | val 0.38869
  Epoch 016 - train 0.29355 | val 0.39167
  Regression -> MSE: 0.000188, MAE: 0.010407, R²: 0.0004
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.27699 | val 0.33688
  Epoch 020 - train 0.25326 | val 0.33389
  Regression -> MSE: 0.000272, MAE: 0.010794, R²: -0.0405
  Directional -> Accuracy: 0.5068, MCC: -0.0015, F1: 0.5610

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.34139 | val 0.25419
  Epoch 020 - train 0.30107 | val 0.24635
  Regression -> MSE: 0.000166, MAE: 0.010345, R²: 0.0066
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.30074 | val 0.31568
  Epoch 016 - train 0.27921 | val 0.32559
  Regression -> MSE: 0.000183, MAE: 0.010385, R²: -0.0159
  Directional -> Accuracy: 0.4091, MCC: -0.1843, F1: 0.3810

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.29282 | val 0.29344
  Epoch 016 - train 0.28652 | val 0.29595
  Regression -> MSE: 0.000356, MAE: 0.012756, R²: -0.0392
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.35117 | val 0.19645
  Epoch 016 - train 0.32105 | val 0.21980
  Regression -> MSE: 0.000126, MAE: 0.008439, R²: -0.1963
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.29302 | val 0.43711
  Epoch 016 - train 0.30851 | val 0.44434
  Regression -> MSE: 0.000220, MAE: 0.011354, R²: -0.0065
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.28630 | val 0.54604
  Epoch 016 - train 0.28281 | val 0.55023
  Regression -> MSE: 0.000093, MAE: 0.007516, R²: -0.1927
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.28357 | val 0.22864
  Epoch 016 - train 0.26859 | val 0.22997
  Regression -> MSE: 0.000321, MAE: 0.014535, R²: -0.0431
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.34171 | val 0.15775
  Epoch 016 - train 0.32009 | val 0.16390
  Regression -> MSE: 0.000247, MAE: 0.011537, R²: -0.0116
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.0000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.29025 | val 0.35759
  Epoch 016 - train 0.27420 | val 0.35832
  Regression -> MSE: 0.000081, MAE: 0.007079, R²: -0.0031
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.31964 | val 0.36558
  Epoch 020 - train 0.32096 | val 0.35532
  Regression -> MSE: 0.000320, MAE: 0.014656, R²: -0.0440
  Directional -> Accuracy: 0.3830, MCC: -0.2344, F1: 0.3256

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.31903 | val 0.34041
  Epoch 016 - train 0.27962 | val 0.34340
  Regression -> MSE: 0.000099, MAE: 0.007141, R²: -0.0055
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.33403 | val 0.38203
  Epoch 016 - train 0.34366 | val 0.39043
  Regression -> MSE: 0.000173, MAE: 0.009530, R²: -0.0041
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.33072 | val 0.44117
  Epoch 016 - train 0.29798 | val 0.56395
  Regression -> MSE: 0.000235, MAE: 0.011953, R²: -0.0531
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.31467 | val 0.33085
  Epoch 016 - train 0.29350 | val 0.34287
  Regression -> MSE: 0.000092, MAE: 0.007612, R²: 0.0062
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.32812 | val 0.49263
  Epoch 016 - train 0.31764 | val 0.49739
  Regression -> MSE: 0.000164, MAE: 0.010277, R²: -0.0036
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.30099 | val 0.38592
  Epoch 016 - train 0.28631 | val 0.39726
  Regression -> MSE: 0.000125, MAE: 0.009017, R²: -0.0760
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...

[I 2026-02-22 23:02:37,954] Trial 92 finished with value: -0.01149059525291885 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 64, 'learning_rate': 0.00023990726079906315, 'weight_decay': 2.4734806343826746e-06, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 0.5650058863737935, 'early_stopping_min_delta': 0.008345866666374853}. Best is trial 90 with value: -0.011414558399902668.

  Epoch 010 - train 0.30570 | val 0.43874
  Epoch 016 - train 0.30585 | val 0.44219
  Regression -> MSE: 0.000238, MAE: 0.012329, R²: -0.0028
  Directional -> Accuracy: 0.5246, MCC: 0.0370, F1: 0.4314

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.40898 | val 0.60258
  Epoch 020 - train 0.40619 | val 0.59394
  Regression -> MSE: 0.000245, MAE: 0.012397, R²: 0.0102
  Directional -> Accuracy: 0.5584, MCC: 0.0770, F1: 0.1500

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.41947 | val 0.40739
  Epoch 016 - train 0.41020 | val 0.40196
  Regression -> MSE: 0.000693, MAE: 0.019459, R²: -0.0129
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.45168 | val 0.77621
  Epoch 016 - train 0.40625 | val 0.78242
  Regression -> MSE: 0.000311, MAE: 0.014421, R²: -0.0011
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.35471 | val 0.36144
  Epoch 016 - train 0.32978 | val 0.36363
  Regression -> MSE: 0.000381, MAE: 0.015106, R²: -0.0907
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.43709 | val 0.40862
  Epoch 020 - train 0.40494 | val 0.38973
  Regression -> MSE: 0.000213, MAE: 0.010103, R²: -0.0480
  Directional -> Accuracy: 0.5098, MCC: -0.1333, F1: 0.6753

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.45588 | val 0.92419
  Epoch 016 - train 0.37879 | val 0.92595
  Regression -> MSE: 0.000554, MAE: 0.018206, R²: 0.0012
  Directional -> Accuracy: 0.4894, MCC: 0.0000, F1: 0.6571

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.41441 | val 0.56267
  Epoch 016 - train 0.41007 | val 0.55805
  Regression -> MSE: 0.000246, MAE: 0.011943, R²: -0.0002
  Directional -> Accuracy: 0.5797, MCC: 0.0547, F1: 0.2927

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.42348 | val 0.65126
  Epoch 016 - train 0.44223 | val 0.67035
  Regression -> MSE: 0.000648, MAE: 0.020157, R²: -0.0840
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.37304 | val 0.50013
  Epoch 016 - train 0.38179 | val 0.49783
  Regression -> MSE: 0.000392, MAE: 0.015937, R²: -0.0229
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.40364 | val 0.56836
  Epoch 016 - train 0.42047 | val 0.57448
  Regression -> MSE: 0.000242, MAE: 0.011782, R²: -0.0036
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.41911 | val 0.70435
  Epoch 016 - train 0.40489 | val 0.74124
  Regression -> MSE: 0.000305, MAE: 0.013614, R²: 0.0200
  Directional -> Accuracy: 0.4600, MCC: -0.0602, F1: 0.5091

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.43321 | val 0.53017
  Epoch 016 - train 0.42684 | val 0.54611
  Regression -> MSE: 0.000679, MAE: 0.019504, R²: -0.0027
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.41651 | val 0.41591
  Epoch 016 - train 0.39819 | val 0.43270
  Regression -> MSE: 0.000142, MAE: 0.009382, R²: -0.0303
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.35306 | val 0.57636
  Epoch 020 - train 0.34414 | val 0.57045
  Regression -> MSE: 0.000235, MAE: 0.011015, R²: -0.0426
  Directional -> Accuracy: 0.4754, MCC: -0.0560, F1: 0.5429

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.40379 | val 1.06631
  Epoch 016 - train 0.40374 | val 1.08274
  Regression -> MSE: 0.000364, MAE: 0.015973, R²: -0.0046
  Directional -> Accuracy: 0.5192, MCC: 0.0185, F1: 0.4186

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.43696 | val 0.45240
  Epoch 016 - train 0.40521 | val 0.45625
  Regression -> MSE: 0.000109, MAE: 0.008104, R²: -0.0141
  Directional -> Accuracy: 0.4000, MCC: -0.2112, F1: 0.0870

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.42744 | val 0.77734
  Epoch 020 - train 0.38139 | val 0.78205
  Regression -> MSE: 0.000159, MAE: 0.009862, R²: -0.0213
  Directional -> Accuracy: 0.6102, MCC: 0.0975, F1: 0.7229

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.41311 | val 0.41427
  Epoch 016 - train 0.40868 | val 0.41358
  Regression -> MSE: 0.000271, MAE: 0.013014, R²: 0.0024
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.37943 | val 0.57901
  Epoch 020 - train 0.34720 | val 0.57227
  Regression -> MSE: 0.000220, MAE: 0.011382, R²: -0.4712
  Directional -> Accuracy: 0.4769, MCC: 0.0468, F1: 0.3704

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.42589 | val 0.74720
  Epoch 016 - train 0.39762 | val 0.79007
  Regression -> MSE: 0.000245, MAE: 0.011172, R²: -0.0845
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.41925 | val 0.58833
  Epoch 016 - train 0.42534 | val 0.60531
  Regression -> MSE: 0.000142, MAE: 0.008297, R²: 0.0064
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.42279 | val 0.51766
  Epoch 020 - train 0.38382 | val 0.50471
  Regression -> MSE: 0.000172, MAE: 0.010753, R²: -0.0401
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.42643 | val 0.52886
  Epoch 016 - train 0.41714 | val 0.52895
  Regression -> MSE: 0.000086, MAE: 0.007092, R²: -0.0108
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.40771 | val 0.54872
  Epoch 020 - train 0.41831 | val 0.58856
  Regression -> MSE: 0.000213, MAE: 0.010999, R²: -0.0070
  Directional -> Accuracy: 0.5606, MCC: 0.1248, F1: 0.2162

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.43462 | val 0.34338
  Epoch 020 - train 0.36508 | val 0.32319
  Regression -> MSE: 0.000095, MAE: 0.007985, R²: -0.0284
  Directional -> Accuracy: 0.5893, MCC: 0.2195, F1: 0.5490

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.45563 | val 0.32772
  Epoch 016 - train 0.45064 | val 0.33268
  Regression -> MSE: 0.000116, MAE: 0.009263, R²: -0.1292
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.43173 | val 0.41205
  Epoch 016 - train 0.43094 | val 0.42071
  Regression -> MSE: 0.000245, MAE: 0.012970, R²: -0.0572
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.40869 | val 0.48264
  Epoch 020 - train 0.39052 | val 0.48450
  Regression -> MSE: 0.000196, MAE: 0.008319, R²: -0.1756
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.38857 | val 0.31322
  Epoch 016 - train 0.44180 | val 0.32152
  Regression -> MSE: 0.000238, MAE: 0.011932, R²: -0.0042
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.51326 | val 0.77156
  Epoch 016 - train 0.47723 | val 0.78492
  Regression -> MSE: 0.000230, MAE: 0.009859, R²: 0.0035
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.44671 | val 0.52169
  Epoch 016 - train 0.42010 | val 0.53545
  Regression -> MSE: 0.000136, MAE: 0.008170, R²: -0.0069
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.39981 | val 0.54793
  Epoch 016 - train 0.39411 | val 0.54653
  Regression -> MSE: 0.000195, MAE: 0.010529, R²: -0.0382
  Directional -> Accuracy: 0.4200, MCC: -0.1405, F1: 0.2162

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.35661 | val 0.49270
  Epoch 020 - train 0.34367 | val 0.49892
  Regression -> MSE: 0.000268, MAE: 0.010770, R²: -0.0241
  Directional -> Accuracy: 0.5616, MCC: 0.1530, F1: 0.5429

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.40785 | val 0.34627
  Epoch 016 - train 0.46252 | val 0.34787
  Regression -> MSE: 0.000167, MAE: 0.010341, R²: 0.0002
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.38399 | val 0.45083
  Epoch 016 - train 0.35050 | val 0.45609
  Regression -> MSE: 0.000180, MAE: 0.010261, R²: -0.0013
  Directional -> Accuracy: 0.5455, MCC: 0.1041, F1: 0.5833

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.38818 | val 0.38469
  Epoch 016 - train 0.37509 | val 0.39484
  Regression -> MSE: 0.000346, MAE: 0.011713, R²: -0.0091
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.45615 | val 0.23839
  Epoch 016 - train 0.47078 | val 0.24600
  Regression -> MSE: 0.000124, MAE: 0.008459, R²: -0.1782
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.44512 | val 0.65725
  Epoch 016 - train 0.43313 | val 0.67910
  Regression -> MSE: 0.000219, MAE: 0.011276, R²: -0.0024
  Directional -> Accuracy: 0.5789, MCC: 0.1593, F1: 0.3684

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.41891 | val 0.86164
  Epoch 016 - train 0.40972 | val 0.88762
  Regression -> MSE: 0.000085, MAE: 0.007184, R²: -0.0899
  Directional -> Accuracy: 0.4468, MCC: -0.0240, F1: 0.4091

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.41671 | val 0.27342
  Epoch 016 - train 0.41252 | val 0.28115
  Regression -> MSE: 0.000313, MAE: 0.014088, R²: -0.0163
  Directional -> Accuracy: 0.3469, MCC: -0.1852, F1: 0.4483

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.41745 | val 0.21807
  Epoch 016 - train 0.44815 | val 0.23616
  Regression -> MSE: 0.000244, MAE: 0.011451, R²: -0.0001
  Directional -> Accuracy: 0.5526, MCC: 0.1116, F1: 0.5405

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.40771 | val 0.50314
  Epoch 020 - train 0.37048 | val 0.52219
  Regression -> MSE: 0.000082, MAE: 0.007153, R²: -0.0157
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.40868 | val 0.54940
  Epoch 020 - train 0.43442 | val 0.52127
  Regression -> MSE: 0.000331, MAE: 0.014480, R²: -0.0800
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.43005 | val 0.47777
  Epoch 016 - train 0.38921 | val 0.48653
  Regression -> MSE: 0.000099, MAE: 0.007159, R²: -0.0124
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.46432 | val 0.58028
  Epoch 016 - train 0.43006 | val 0.57920
  Regression -> MSE: 0.000175, MAE: 0.010132, R²: -0.0165
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.38087 | val 0.48453
  Epoch 016 - train 0.37108 | val 0.56577
  Regression -> MSE: 0.000226, MAE: 0.011822, R²: -0.0140
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.39703 | val 0.48757
  Epoch 016 - train 0.39305 | val 0.49838
  Regression -> MSE: 0.000093, MAE: 0.007671, R²: -0.0059
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.42455 | val 0.76643
  Epoch 016 - train 0.42814 | val 0.76953
  Regression -> MSE: 0.000169, MAE: 0.010356, R²: -0.0335
  Directional -> Accuracy: 0.4815, MCC: 0.0000, F1: 0.0000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.41547 | val 0.62490
  Epoch 016 - train 0.40671 | val 0.69273
  Regression -> MSE: 0.000116, MAE: 0.008891, R²: 0.0008
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...

[I 2026-02-22 23:02:57,828] Trial 93 finished with value: -0.011483117884678967 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 64, 'learning_rate': 0.00012546405211864896, 'weight_decay': 1.1232248735511133e-05, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 1.0286568373673697, 'early_stopping_min_delta': 0.007790771637658127}. Best is trial 90 with value: -0.011414558399902668.

  Epoch 010 - train 0.43469 | val 0.69509
  Epoch 016 - train 0.41338 | val 0.72906
  Regression -> MSE: 0.000236, MAE: 0.012251, R²: 0.0047
  Directional -> Accuracy: 0.5902, MCC: 0.1752, F1: 0.5455

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.35675 | val 0.51928
  Epoch 020 - train 0.36022 | val 0.48828
  Regression -> MSE: 0.000273, MAE: 0.013308, R²: -0.1046
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.36936 | val 0.31853
  Epoch 016 - train 0.35253 | val 0.32255
  Regression -> MSE: 0.000706, MAE: 0.019721, R²: -0.0318
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.37820 | val 0.61888
  Epoch 016 - train 0.37745 | val 0.62106
  Regression -> MSE: 0.000311, MAE: 0.014418, R²: -0.0039
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.32927 | val 0.27045
  Epoch 016 - train 0.30441 | val 0.27341
  Regression -> MSE: 0.000380, MAE: 0.015081, R²: -0.0888
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.39272 | val 0.35749
  Epoch 016 - train 0.38700 | val 0.38932
  Regression -> MSE: 0.000205, MAE: 0.010064, R²: -0.0065
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.39946 | val 0.74251
  Epoch 016 - train 0.36578 | val 0.76947
  Regression -> MSE: 0.000568, MAE: 0.018319, R²: -0.0237
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.42140 | val 0.45940
  Epoch 016 - train 0.41412 | val 0.45000
  Regression -> MSE: 0.000254, MAE: 0.012651, R²: -0.0354
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.32393 | val 0.54169
  Epoch 016 - train 0.41445 | val 0.55202
  Regression -> MSE: 0.000663, MAE: 0.020436, R²: -0.1099
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.36485 | val 0.43916
  Epoch 020 - train 0.37977 | val 0.43702
  Regression -> MSE: 0.000390, MAE: 0.016364, R²: -0.0176
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.40087 | val 0.51173
  Epoch 016 - train 0.40189 | val 0.53202
  Regression -> MSE: 0.000242, MAE: 0.011756, R²: -0.0017
  Directional -> Accuracy: 0.4143, MCC: -0.1020, F1: 0.5393

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.37475 | val 0.54206
  Epoch 016 - train 0.35693 | val 0.60065
  Regression -> MSE: 0.000316, MAE: 0.013598, R²: -0.0162
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.44050 | val 0.41715
  Epoch 016 - train 0.41739 | val 0.45738
  Regression -> MSE: 0.000682, MAE: 0.019615, R²: -0.0062
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.31297 | val 0.35173
  Epoch 016 - train 0.33442 | val 0.35546
  Regression -> MSE: 0.000138, MAE: 0.009133, R²: 0.0024
  Directional -> Accuracy: 0.3953, MCC: -0.1763, F1: 0.5185

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.36151 | val 0.47355
  Epoch 020 - train 0.39706 | val 0.46391
  Regression -> MSE: 0.000255, MAE: 0.011499, R²: -0.1316
  Directional -> Accuracy: 0.4590, MCC: -0.0843, F1: 0.2979

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.39257 | val 0.80550
  Epoch 016 - train 0.40365 | val 0.88826
  Regression -> MSE: 0.000361, MAE: 0.015989, R²: 0.0021
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.39239 | val 0.39473
  Epoch 016 - train 0.39402 | val 0.40363
  Regression -> MSE: 0.000110, MAE: 0.008153, R²: -0.0193
  Directional -> Accuracy: 0.4571, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.38161 | val 0.64352
  Epoch 016 - train 0.35699 | val 0.69211
  Regression -> MSE: 0.000158, MAE: 0.009753, R²: -0.0107
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.41030 | val 0.38401
  Epoch 016 - train 0.40530 | val 0.44595
  Regression -> MSE: 0.000274, MAE: 0.013050, R²: -0.0056
  Directional -> Accuracy: 0.6184, MCC: 0.1128, F1: 0.7563

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.35265 | val 0.48482
  Epoch 016 - train 0.34767 | val 0.48423
  Regression -> MSE: 0.000152, MAE: 0.008787, R²: -0.0176
  Directional -> Accuracy: 0.5385, MCC: -0.0044, F1: 0.6512

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.41961 | val 0.58619
  Epoch 016 - train 0.42092 | val 0.57336
  Regression -> MSE: 0.000232, MAE: 0.011295, R²: -0.0245
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.38342 | val 0.46129
  Epoch 016 - train 0.37631 | val 0.46194
  Regression -> MSE: 0.000143, MAE: 0.008283, R²: -0.0004
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.36103 | val 0.40308
  Epoch 016 - train 0.37633 | val 0.40344
  Regression -> MSE: 0.000176, MAE: 0.010312, R²: -0.0625
  Directional -> Accuracy: 0.4848, MCC: -0.0727, F1: 0.0556

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.40696 | val 0.41802
  Epoch 016 - train 0.36974 | val 0.41698
  Regression -> MSE: 0.000087, MAE: 0.007148, R²: -0.0193
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.37725 | val 0.43173
  Epoch 016 - train 0.37991 | val 0.42960
  Regression -> MSE: 0.000215, MAE: 0.011078, R²: -0.0144
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.36234 | val 0.30618
  Epoch 016 - train 0.37566 | val 0.31038
  Regression -> MSE: 0.000103, MAE: 0.008328, R²: -0.1162
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.38352 | val 0.25232
  Epoch 016 - train 0.37380 | val 0.25240
  Regression -> MSE: 0.000105, MAE: 0.008849, R²: -0.0198
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.38124 | val 0.33269
  Epoch 016 - train 0.37331 | val 0.34709
  Regression -> MSE: 0.000237, MAE: 0.012737, R²: -0.0225
  Directional -> Accuracy: 0.4419, MCC: -0.0089, F1: 0.2500

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.36340 | val 0.41012
  Epoch 020 - train 0.35631 | val 0.40403
  Regression -> MSE: 0.000196, MAE: 0.008520, R²: -0.1751
  Directional -> Accuracy: 0.5439, MCC: 0.3032, F1: 0.3158

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.41429 | val 0.26172
  Epoch 016 - train 0.42166 | val 0.26798
  Regression -> MSE: 0.000237, MAE: 0.011857, R²: -0.0002
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.39625 | val 0.60417
  Epoch 020 - train 0.40361 | val 0.58629
  Regression -> MSE: 0.000225, MAE: 0.010021, R²: 0.0216
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.41266 | val 0.47427
  Epoch 016 - train 0.42218 | val 0.48442
  Regression -> MSE: 0.000144, MAE: 0.008743, R²: -0.0673
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.36487 | val 0.45515
  Epoch 016 - train 0.37179 | val 0.45763
  Regression -> MSE: 0.000191, MAE: 0.010437, R²: -0.0149
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.34781 | val 0.44193
  Epoch 016 - train 0.33172 | val 0.44351
  Regression -> MSE: 0.000264, MAE: 0.010549, R²: -0.0099
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.40927 | val 0.27927
  Epoch 016 - train 0.39619 | val 0.28066
  Regression -> MSE: 0.000172, MAE: 0.010414, R²: -0.0305
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.41542 | val 0.37631
  Epoch 016 - train 0.38787 | val 0.38485
  Regression -> MSE: 0.000184, MAE: 0.010404, R²: -0.0203
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.36302 | val 0.32589
  Epoch 016 - train 0.36407 | val 0.32784
  Regression -> MSE: 0.000354, MAE: 0.012686, R²: -0.0320
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.44025 | val 0.19338
  Epoch 016 - train 0.40882 | val 0.20087
  Regression -> MSE: 0.000113, MAE: 0.008330, R²: -0.0751
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.42623 | val 0.50956
  Epoch 016 - train 0.41159 | val 0.53239
  Regression -> MSE: 0.000220, MAE: 0.011247, R²: -0.0050
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.39720 | val 0.67997
  Epoch 016 - train 0.41302 | val 0.70266
  Regression -> MSE: 0.000089, MAE: 0.007379, R²: -0.1428
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.36188 | val 0.28267
  Epoch 016 - train 0.36377 | val 0.28689
  Regression -> MSE: 0.000329, MAE: 0.014898, R²: -0.0698
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.34237 | val 0.19175
  Epoch 020 - train 0.38598 | val 0.18289
  Regression -> MSE: 0.000263, MAE: 0.011508, R²: -0.0797
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.40992 | val 0.50506
  Epoch 016 - train 0.40968 | val 0.53898
  Regression -> MSE: 0.000087, MAE: 0.007097, R²: -0.0714
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.42959 | val 0.44707
  Epoch 020 - train 0.36259 | val 0.43782
  Regression -> MSE: 0.000293, MAE: 0.014246, R²: 0.0445
  Directional -> Accuracy: 0.5319, MCC: 0.0926, F1: 0.6765

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.32852 | val 0.41140
  Epoch 016 - train 0.35456 | val 0.41010
  Regression -> MSE: 0.000100, MAE: 0.007067, R²: -0.0218
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.43650 | val 0.44327
  Epoch 016 - train 0.43509 | val 0.44579
  Regression -> MSE: 0.000171, MAE: 0.009655, R²: 0.0025
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.33039 | val 0.38844
  Epoch 016 - train 0.37533 | val 0.39271
  Regression -> MSE: 0.000223, MAE: 0.011712, R²: 0.0009
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.38385 | val 0.39622
  Epoch 016 - train 0.34993 | val 0.40907
  Regression -> MSE: 0.000097, MAE: 0.008032, R²: -0.0561
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.38959 | val 0.60312
  Epoch 016 - train 0.40407 | val 0.63576
  Regression -> MSE: 0.000167, MAE: 0.010357, R²: -0.0169
  Directional -> Accuracy: 0.4815, MCC: 0.0000, F1: 0.0000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.38010 | val 0.47408
  Epoch 016 - train 0.36895 | val 0.58117
  Regression -> MSE: 0.000120, MAE: 0.008964, R²: -0.0390
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...

[I 2026-02-22 23:03:17,088] Trial 94 finished with value: -0.011524229197325429 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.8, 'batch_size': 64, 'learning_rate': 4.4744919269061314e-05, 'weight_decay': 4.330764860365477e-06, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 0.7066615875743132, 'early_stopping_min_delta': 0.008895937388623166}. Best is trial 90 with value: -0.011414558399902668.

  Epoch 010 - train 0.36698 | val 0.52836
  Epoch 016 - train 0.37475 | val 0.53369
  Regression -> MSE: 0.000240, MAE: 0.012364, R²: -0.0137
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.34944 | val 0.55199
  Epoch 020 - train 0.33734 | val 0.58955
  Regression -> MSE: 0.000255, MAE: 0.012834, R²: -0.0318
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.34071 | val 0.35546
  Epoch 016 - train 0.33460 | val 0.38220
  Regression -> MSE: 0.000683, MAE: 0.019394, R²: 0.0023
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.36686 | val 0.69557
  Epoch 020 - train 0.35604 | val 0.67885
  Regression -> MSE: 0.000319, MAE: 0.014104, R²: -0.0276
  Directional -> Accuracy: 0.5532, MCC: 0.1581, F1: 0.4324

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.29374 | val 0.30385
  Epoch 020 - train 0.28070 | val 0.30356
  Regression -> MSE: 0.000353, MAE: 0.014663, R²: -0.0119
  Directional -> Accuracy: 0.5467, MCC: 0.0223, F1: 0.6964

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.35110 | val 0.36794
  Epoch 020 - train 0.33822 | val 0.37665
  Regression -> MSE: 0.000207, MAE: 0.009791, R²: -0.0169
  Directional -> Accuracy: 0.5882, MCC: 0.1947, F1: 0.7042

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.34205 | val 0.83317
  Epoch 016 - train 0.33662 | val 0.84454
  Regression -> MSE: 0.000561, MAE: 0.018241, R²: -0.0099
  Directional -> Accuracy: 0.4894, MCC: 0.0000, F1: 0.6571

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.37237 | val 0.51199
  Epoch 020 - train 0.36062 | val 0.49242
  Regression -> MSE: 0.000250, MAE: 0.012285, R²: -0.0182
  Directional -> Accuracy: 0.4203, MCC: -0.0653, F1: 0.5122

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.36559 | val 0.57616
  Epoch 016 - train 0.35538 | val 0.60476
  Regression -> MSE: 0.000645, MAE: 0.020149, R²: -0.0802
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.35582 | val 0.49252
  Epoch 020 - train 0.34146 | val 0.47804
  Regression -> MSE: 0.000372, MAE: 0.015614, R²: 0.0292
  Directional -> Accuracy: 0.6735, MCC: 0.3335, F1: 0.6000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.34794 | val 0.53554
  Epoch 016 - train 0.34327 | val 0.55750
  Regression -> MSE: 0.000242, MAE: 0.011699, R²: -0.0023
  Directional -> Accuracy: 0.5000, MCC: 0.0251, F1: 0.5070

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.32648 | val 0.61571
  Epoch 016 - train 0.31982 | val 0.64221
  Regression -> MSE: 0.000313, MAE: 0.013659, R²: -0.0060
  Directional -> Accuracy: 0.5000, MCC: -0.1242, F1: 0.0741

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.36574 | val 0.48481
  Epoch 016 - train 0.35958 | val 0.53178
  Regression -> MSE: 0.000671, MAE: 0.019327, R²: 0.0098
  Directional -> Accuracy: 0.6379, MCC: 0.2760, F1: 0.6441

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.36422 | val 0.37907
  Epoch 020 - train 0.34758 | val 0.42251
  Regression -> MSE: 0.000148, MAE: 0.009517, R²: -0.0715
  Directional -> Accuracy: 0.4419, MCC: -0.0993, F1: 0.4545

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.32372 | val 0.53433
  Epoch 020 - train 0.30692 | val 0.51576
  Regression -> MSE: 0.000241, MAE: 0.011294, R²: -0.0725
  Directional -> Accuracy: 0.4754, MCC: -0.0466, F1: 0.4074

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.34578 | val 0.94231
  Epoch 016 - train 0.34013 | val 1.00102
  Regression -> MSE: 0.000361, MAE: 0.015902, R²: 0.0021
  Directional -> Accuracy: 0.5962, MCC: 0.1782, F1: 0.4324

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.37042 | val 0.40302
  Epoch 016 - train 0.36271 | val 0.42104
  Regression -> MSE: 0.000108, MAE: 0.007990, R²: -0.0005
  Directional -> Accuracy: 0.5286, MCC: -0.1105, F1: 0.6916

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.33692 | val 0.79123
  Epoch 016 - train 0.33163 | val 0.87733
  Regression -> MSE: 0.000158, MAE: 0.009901, R²: -0.0105
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.36664 | val 0.38820
  Epoch 016 - train 0.35977 | val 0.39474
  Regression -> MSE: 0.000281, MAE: 0.013024, R²: -0.0328
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.30960 | val 0.52894
  Epoch 020 - train 0.29289 | val 0.52661
  Regression -> MSE: 0.000146, MAE: 0.008870, R²: 0.0270
  Directional -> Accuracy: 0.6000, MCC: 0.1483, F1: 0.7451

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.35693 | val 0.62263
  Epoch 016 - train 0.34938 | val 0.64999
  Regression -> MSE: 0.000248, MAE: 0.011247, R²: -0.0951
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.36092 | val 0.54426
  Epoch 016 - train 0.35381 | val 0.56711
  Regression -> MSE: 0.000145, MAE: 0.008460, R²: -0.0090
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.34075 | val 0.44618
  Epoch 020 - train 0.32260 | val 0.44104
  Regression -> MSE: 0.000204, MAE: 0.010852, R²: -0.2377
  Directional -> Accuracy: 0.5152, MCC: 0.0381, F1: 0.3043

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.37003 | val 0.47062
  Epoch 020 - train 0.35826 | val 0.46012
  Regression -> MSE: 0.000085, MAE: 0.007110, R²: -0.0015
  Directional -> Accuracy: 0.5690, MCC: 0.1545, F1: 0.5763

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.35906 | val 0.52984
  Epoch 016 - train 0.35409 | val 0.54425
  Regression -> MSE: 0.000217, MAE: 0.011044, R²: -0.0267
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.31977 | val 0.30510
  Epoch 020 - train 0.30218 | val 0.28260
  Regression -> MSE: 0.000106, MAE: 0.008299, R²: -0.1502
  Directional -> Accuracy: 0.5179, MCC: 0.1373, F1: 0.3415

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.36453 | val 0.28193
  Epoch 020 - train 0.35389 | val 0.27675
  Regression -> MSE: 0.000102, MAE: 0.008619, R²: 0.0126
  Directional -> Accuracy: 0.6304, MCC: 0.3081, F1: 0.6531

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.37118 | val 0.37220
  Epoch 016 - train 0.36554 | val 0.39188
  Regression -> MSE: 0.000238, MAE: 0.012814, R²: -0.0293
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.35359 | val 0.44436
  Epoch 020 - train 0.34076 | val 0.46858
  Regression -> MSE: 0.000235, MAE: 0.010098, R²: -0.4127
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.37477 | val 0.28686
  Epoch 016 - train 0.36880 | val 0.28807
  Regression -> MSE: 0.000237, MAE: 0.011860, R²: -0.0019
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.34525 | val 0.69130
  Epoch 016 - train 0.33980 | val 0.70458
  Regression -> MSE: 0.000229, MAE: 0.009860, R²: 0.0057
  Directional -> Accuracy: 0.5116, MCC: 0.0162, F1: 0.4000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.37890 | val 0.49645
  Epoch 016 - train 0.36897 | val 0.50898
  Regression -> MSE: 0.000136, MAE: 0.008311, R²: -0.0105
  Directional -> Accuracy: 0.4186, MCC: -0.2849, F1: 0.5763

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.38234 | val 0.52635
  Epoch 020 - train 0.35943 | val 0.51872
  Regression -> MSE: 0.000199, MAE: 0.010639, R²: -0.0582
  Directional -> Accuracy: 0.4600, MCC: -0.0551, F1: 0.3721

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.29622 | val 0.47024
  Epoch 020 - train 0.28626 | val 0.49646
  Regression -> MSE: 0.000264, MAE: 0.010551, R²: -0.0077
  Directional -> Accuracy: 0.5890, MCC: 0.1418, F1: 0.6739

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.34090 | val 0.32075
  Epoch 016 - train 0.33532 | val 0.32138
  Regression -> MSE: 0.000167, MAE: 0.010390, R²: -0.0034
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.32339 | val 0.44683
  Epoch 016 - train 0.31579 | val 0.53492
  Regression -> MSE: 0.000180, MAE: 0.010292, R²: -0.0013
  Directional -> Accuracy: 0.4773, MCC: -0.2085, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.33873 | val 0.34969
  Epoch 020 - train 0.32458 | val 0.36034
  Regression -> MSE: 0.000341, MAE: 0.012028, R²: 0.0050
  Directional -> Accuracy: 0.4627, MCC: -0.0306, F1: 0.4000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.37254 | val 0.21634
  Epoch 016 - train 0.36548 | val 0.21759
  Regression -> MSE: 0.000119, MAE: 0.008319, R²: -0.1333
  Directional -> Accuracy: 0.5116, MCC: 0.0849, F1: 0.1600

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.36359 | val 0.59441
  Epoch 016 - train 0.35690 | val 0.63194
  Regression -> MSE: 0.000220, MAE: 0.011252, R²: -0.0058
  Directional -> Accuracy: 0.4912, MCC: 0.0663, F1: 0.6420

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.35634 | val 0.77016
  Epoch 016 - train 0.34711 | val 0.76964
  Regression -> MSE: 0.000084, MAE: 0.007159, R²: -0.0851
  Directional -> Accuracy: 0.5106, MCC: -0.0465, F1: 0.6102

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.33949 | val 0.27277
  Epoch 016 - train 0.33318 | val 0.27782
  Regression -> MSE: 0.000317, MAE: 0.014428, R²: -0.0309
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.36909 | val 0.18861
  Epoch 020 - train 0.35401 | val 0.20027
  Regression -> MSE: 0.000256, MAE: 0.011471, R²: -0.0511
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.34012 | val 0.45959
  Epoch 020 - train 0.32319 | val 0.45003
  Regression -> MSE: 0.000082, MAE: 0.007213, R²: -0.0168
  Directional -> Accuracy: 0.5067, MCC: 0.0499, F1: 0.6542

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.37049 | val 0.50219
  Epoch 016 - train 0.36423 | val 0.50225
  Regression -> MSE: 0.000307, MAE: 0.014480, R²: -0.0012
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.34330 | val 0.42923
  Epoch 016 - train 0.33676 | val 0.43862
  Regression -> MSE: 0.000097, MAE: 0.007207, R²: 0.0077
  Directional -> Accuracy: 0.6591, MCC: 0.3221, F1: 0.7619

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.38987 | val 0.50627
  Epoch 016 - train 0.38145 | val 0.50421
  Regression -> MSE: 0.000174, MAE: 0.010002, R²: -0.0109
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.32543 | val 0.45606
  Epoch 016 - train 0.31634 | val 0.47030
  Regression -> MSE: 0.000224, MAE: 0.011772, R²: -0.0040
  Directional -> Accuracy: 0.4286, MCC: -0.3225, F1: 0.6000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.35342 | val 0.44907
  Epoch 020 - train 0.34012 | val 0.44835
  Regression -> MSE: 0.000094, MAE: 0.007711, R²: -0.0181
  Directional -> Accuracy: 0.4561, MCC: -0.0911, F1: 0.6173

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.36683 | val 0.68756
  Epoch 016 - train 0.36106 | val 0.71684
  Regression -> MSE: 0.000165, MAE: 0.010311, R²: -0.0080
  Directional -> Accuracy: 0.4259, MCC: -0.1509, F1: 0.2439

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.34156 | val 0.49275
  Epoch 016 - train 0.33463 | val 0.49578
  Regression -> MSE: 0.000122, MAE: 0.008980, R²: -0.0486
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...

[I 2026-02-22 23:03:37,916] Trial 95 finished with value: -0.011471410370964106 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.0, 'batch_size': 64, 'learning_rate': 7.476565637283398e-05, 'weight_decay': 1.3379740239580343e-06, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 0.8663282604091616, 'early_stopping_min_delta': 0.00788992258453479}. Best is trial 90 with value: -0.011414558399902668.

  Epoch 010 - train 0.36684 | val 0.81676
  Epoch 016 - train 0.35828 | val 1.11356
  Regression -> MSE: 0.000237, MAE: 0.012533, R²: 0.0014
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.44461 | val 0.72476
  Epoch 016 - train 0.43094 | val 0.84351
  Regression -> MSE: 0.000279, MAE: 0.013501, R²: -0.1251
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.41273 | val 0.35033
  Epoch 016 - train 0.39146 | val 0.35015
  Regression -> MSE: 0.000715, MAE: 0.019891, R²: -0.0443
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.44131 | val 0.67095
  Epoch 020 - train 0.40579 | val 0.67267
  Regression -> MSE: 0.000302, MAE: 0.014215, R²: 0.0255
  Directional -> Accuracy: 0.5532, MCC: 0.1572, F1: 0.7042

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.35800 | val 0.40133
  Epoch 016 - train 0.37950 | val 0.48561
  Regression -> MSE: 0.000401, MAE: 0.015542, R²: -0.1488
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.45047 | val 0.37002
  Epoch 016 - train 0.42535 | val 0.37432
  Regression -> MSE: 0.000202, MAE: 0.010030, R²: 0.0063
  Directional -> Accuracy: 0.6471, MCC: 0.3499, F1: 0.5714

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.39011 | val 0.79033
  Epoch 020 - train 0.43216 | val 0.76722
  Regression -> MSE: 0.000535, MAE: 0.017897, R²: 0.0362
  Directional -> Accuracy: 0.5745, MCC: 0.1726, F1: 0.3750

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.42328 | val 0.51995
  Epoch 016 - train 0.42722 | val 0.53734
  Regression -> MSE: 0.000248, MAE: 0.011933, R²: -0.0100
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.39424 | val 0.56935
  Epoch 020 - train 0.38630 | val 0.53422
  Regression -> MSE: 0.000630, MAE: 0.019941, R²: -0.0550
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.43899 | val 0.43955
  Epoch 020 - train 0.40357 | val 0.44055
  Regression -> MSE: 0.000456, MAE: 0.017034, R²: -0.1889
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.42175 | val 0.50302
  Epoch 016 - train 0.41810 | val 0.50724
  Regression -> MSE: 0.000242, MAE: 0.011913, R²: -0.0029
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.38134 | val 0.63060
  Epoch 016 - train 0.40719 | val 0.63055
  Regression -> MSE: 0.000313, MAE: 0.013780, R²: -0.0078
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.6301

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.42528 | val 0.49475
  Epoch 016 - train 0.46652 | val 0.59042
  Regression -> MSE: 0.000689, MAE: 0.019781, R²: -0.0173
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.41372 | val 0.38433
  Epoch 016 - train 0.42085 | val 0.39294
  Regression -> MSE: 0.000138, MAE: 0.009074, R²: 0.0011
  Directional -> Accuracy: 0.4884, MCC: -0.1124, F1: 0.2143

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.37606 | val 0.52345
  Epoch 016 - train 0.36416 | val 0.53021
  Regression -> MSE: 0.000231, MAE: 0.010874, R²: -0.0251
  Directional -> Accuracy: 0.4918, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.41672 | val 0.91378
  Epoch 016 - train 0.44714 | val 0.95099
  Regression -> MSE: 0.000363, MAE: 0.016137, R²: -0.0023
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.45668 | val 0.38935
  Epoch 016 - train 0.46088 | val 0.39397
  Regression -> MSE: 0.000108, MAE: 0.008068, R²: -0.0007
  Directional -> Accuracy: 0.4714, MCC: 0.0191, F1: 0.1778

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.38553 | val 0.69608
  Epoch 016 - train 0.37925 | val 0.71052
  Regression -> MSE: 0.000157, MAE: 0.009604, R²: -0.0088
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.42821 | val 0.38349
  Epoch 016 - train 0.46443 | val 0.38291
  Regression -> MSE: 0.000273, MAE: 0.013037, R²: -0.0018
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.41113 | val 0.53573
  Epoch 016 - train 0.40657 | val 0.53073
  Regression -> MSE: 0.000167, MAE: 0.009137, R²: -0.1156
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.51158 | val 0.63663
  Epoch 016 - train 0.49557 | val 0.65716
  Regression -> MSE: 0.000258, MAE: 0.011469, R²: -0.1407
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.40495 | val 0.49693
  Epoch 016 - train 0.43121 | val 0.51063
  Regression -> MSE: 0.000150, MAE: 0.008676, R²: -0.0462
  Directional -> Accuracy: 0.5625, MCC: 0.2437, F1: 0.5333

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.41132 | val 0.50608
  Epoch 016 - train 0.36505 | val 0.52641
  Regression -> MSE: 0.000167, MAE: 0.010136, R²: -0.0101
  Directional -> Accuracy: 0.5606, MCC: 0.1414, F1: 0.6506

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.41906 | val 0.46617
  Epoch 016 - train 0.44137 | val 0.47372
  Regression -> MSE: 0.000085, MAE: 0.007057, R²: 0.0024
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.43667 | val 0.49573
  Epoch 016 - train 0.42779 | val 0.48860
  Regression -> MSE: 0.000217, MAE: 0.011544, R²: -0.0243
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.41275 | val 0.31949
  Epoch 016 - train 0.42502 | val 0.32181
  Regression -> MSE: 0.000098, MAE: 0.008198, R²: -0.0675
  Directional -> Accuracy: 0.4643, MCC: -0.1124, F1: 0.5588

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.40416 | val 0.27488
  Epoch 016 - train 0.40922 | val 0.27753
  Regression -> MSE: 0.000106, MAE: 0.008918, R²: -0.0316
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.42000 | val 0.34797
  Epoch 016 - train 0.39330 | val 0.35421
  Regression -> MSE: 0.000234, MAE: 0.012653, R²: -0.0099
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.43696 | val 0.43725
  Epoch 020 - train 0.40189 | val 0.44047
  Regression -> MSE: 0.000210, MAE: 0.009157, R²: -0.2638
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.43137 | val 0.27744
  Epoch 016 - train 0.42364 | val 0.28180
  Regression -> MSE: 0.000235, MAE: 0.011812, R²: 0.0061
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.43475 | val 0.66501
  Epoch 020 - train 0.44128 | val 0.65684
  Regression -> MSE: 0.000230, MAE: 0.010113, R²: 0.0027
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.43291 | val 0.48983
  Epoch 016 - train 0.44956 | val 0.50800
  Regression -> MSE: 0.000140, MAE: 0.008304, R²: -0.0362
  Directional -> Accuracy: 0.4419, MCC: -0.0940, F1: 0.2000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.38303 | val 0.48226
  Epoch 020 - train 0.40906 | val 0.47421
  Regression -> MSE: 0.000203, MAE: 0.011131, R²: -0.0758
  Directional -> Accuracy: 0.5200, MCC: -0.0254, F1: 0.6571

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.42159 | val 0.55920
  Epoch 016 - train 0.40270 | val 0.58175
  Regression -> MSE: 0.000268, MAE: 0.010814, R²: -0.0229
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.44551 | val 0.29883
  Epoch 020 - train 0.43894 | val 0.29564
  Regression -> MSE: 0.000180, MAE: 0.010562, R²: -0.0816
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.40432 | val 0.40152
  Epoch 016 - train 0.34604 | val 0.41638
  Regression -> MSE: 0.000179, MAE: 0.010285, R²: 0.0080
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.41347 | val 0.34755
  Epoch 016 - train 0.42255 | val 0.34875
  Regression -> MSE: 0.000340, MAE: 0.011973, R²: 0.0072
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.45511 | val 0.21205
  Epoch 016 - train 0.44778 | val 0.21786
  Regression -> MSE: 0.000128, MAE: 0.008491, R²: -0.2145
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.41525 | val 0.56045
  Epoch 016 - train 0.42792 | val 0.56439
  Regression -> MSE: 0.000219, MAE: 0.011292, R²: -0.0020
  Directional -> Accuracy: 0.5439, MCC: 0.0911, F1: 0.1333

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.42322 | val 0.73282
  Epoch 016 - train 0.40631 | val 0.74948
  Regression -> MSE: 0.000089, MAE: 0.007390, R²: -0.1501
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.39563 | val 0.25173
  Epoch 016 - train 0.40427 | val 0.25682
  Regression -> MSE: 0.000315, MAE: 0.014245, R²: -0.0251
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.43423 | val 0.18402
  Epoch 016 - train 0.46388 | val 0.18599
  Regression -> MSE: 0.000247, MAE: 0.011588, R²: -0.0131
  Directional -> Accuracy: 0.4211, MCC: -0.1898, F1: 0.0833

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.46622 | val 0.45964
  Epoch 016 - train 0.47174 | val 0.46686
  Regression -> MSE: 0.000082, MAE: 0.007102, R²: -0.0088
  Directional -> Accuracy: 0.4533, MCC: -0.1639, F1: 0.6168

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.44943 | val 0.54611
  Epoch 016 - train 0.43166 | val 0.58433
  Regression -> MSE: 0.000313, MAE: 0.014495, R²: -0.0209
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.41662 | val 0.43198
  Epoch 016 - train 0.41349 | val 0.43394
  Regression -> MSE: 0.000100, MAE: 0.007158, R²: -0.0160
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.41366 | val 0.49742
  Epoch 016 - train 0.42678 | val 0.50112
  Regression -> MSE: 0.000173, MAE: 0.009870, R²: -0.0076
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.46830 | val 0.52745
  Epoch 016 - train 0.38233 | val 0.66497
  Regression -> MSE: 0.000233, MAE: 0.011929, R²: -0.0432
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.45579 | val 0.42801
  Epoch 016 - train 0.44525 | val 0.43223
  Regression -> MSE: 0.000093, MAE: 0.007676, R²: -0.0050
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.40062 | val 0.68527
  Epoch 016 - train 0.41905 | val 0.73708
  Regression -> MSE: 0.000166, MAE: 0.010296, R²: -0.0114
  Directional -> Accuracy: 0.4815, MCC: 0.0000, F1: 0.0000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.42895 | val 0.48279
  Epoch 016 - train 0.44729 | val 0.50790
  Regression -> MSE: 0.000126, MAE: 0.009051, R²: -0.0906
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...

[I 2026-02-22 23:03:57,210] Trial 96 finished with value: -0.011543085187920632 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 64, 'learning_rate': 3.210517693465743e-05, 'weight_decay': 1.6730220941251815e-06, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 0.81862064873191, 'early_stopping_min_delta': 0.0028097727292014764}. Best is trial 90 with value: -0.011414558399902668.

  Epoch 010 - train 0.40330 | val 0.64262
  Epoch 016 - train 0.40281 | val 0.80661
  Regression -> MSE: 0.000238, MAE: 0.012378, R²: -0.0032
  Directional -> Accuracy: 0.4754, MCC: -0.0244, F1: 0.5897

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.29170 | val 0.55780
  Epoch 016 - train 0.23084 | val 0.80745
  Regression -> MSE: 0.000251, MAE: 0.012643, R²: -0.0129
  Directional -> Accuracy: 0.4545, MCC: -0.0652, F1: 0.5116

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.25348 | val 0.31975
  Epoch 016 - train 0.23885 | val 0.40626
  Regression -> MSE: 0.000680, MAE: 0.019183, R²: 0.0070
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.26296 | val 0.67346
  Epoch 016 - train 0.22279 | val 0.72666
  Regression -> MSE: 0.000313, MAE: 0.014504, R²: -0.0085
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.22440 | val 0.72793
  Epoch 016 - train 0.19888 | val 1.22052
  Regression -> MSE: 0.000363, MAE: 0.014779, R²: -0.0389
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.25490 | val 0.33003
  Epoch 020 - train 0.20080 | val 0.33672
  Regression -> MSE: 0.000204, MAE: 0.009581, R²: -0.0027
  Directional -> Accuracy: 0.5294, MCC: 0.0119, F1: 0.6842

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.24194 | val 0.72968
  Epoch 017 - train 0.19758 | val 0.74097
  Regression -> MSE: 0.000543, MAE: 0.017989, R²: 0.0211
  Directional -> Accuracy: 0.4894, MCC: 0.0000, F1: 0.6571

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.26476 | val 0.50626
  Epoch 017 - train 0.23437 | val 0.64696
  Regression -> MSE: 0.000243, MAE: 0.012156, R²: 0.0086
  Directional -> Accuracy: 0.4928, MCC: 0.0458, F1: 0.5205

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.19907 | val 0.63850
  Epoch 017 - train 0.14694 | val 0.80220
  Regression -> MSE: 0.000640, MAE: 0.019955, R²: -0.0718
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.24702 | val 0.44388
  Epoch 020 - train 0.17647 | val 0.63591
  Regression -> MSE: 0.000385, MAE: 0.016046, R²: -0.0043
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.28858 | val 0.49518
  Epoch 016 - train 0.24487 | val 0.55289
  Regression -> MSE: 0.000242, MAE: 0.012036, R²: -0.0020
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.23223 | val 0.81530
  Epoch 019 - train 0.16739 | val 1.46036
  Regression -> MSE: 0.000305, MAE: 0.013466, R²: 0.0193
  Directional -> Accuracy: 0.5800, MCC: 0.2212, F1: 0.1600

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.26173 | val 0.48335
  Epoch 017 - train 0.21071 | val 0.66544
  Regression -> MSE: 0.000664, MAE: 0.019159, R²: 0.0198
  Directional -> Accuracy: 0.6897, MCC: 0.3946, F1: 0.7273

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.24207 | val 0.45379
  Epoch 016 - train 0.20412 | val 0.69306
  Regression -> MSE: 0.000137, MAE: 0.009089, R²: 0.0068
  Directional -> Accuracy: 0.5349, MCC: 0.1847, F1: 0.6296

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.25095 | val 0.49127
  Epoch 019 - train 0.19223 | val 0.54861
  Regression -> MSE: 0.000225, MAE: 0.010635, R²: 0.0007
  Directional -> Accuracy: 0.5410, MCC: 0.0958, F1: 0.6585

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.24217 | val 0.98417
  Epoch 020 - train 0.20849 | val 1.52147
  Regression -> MSE: 0.000360, MAE: 0.016142, R²: 0.0063
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.26212 | val 0.42468
  Epoch 016 - train 0.21669 | val 0.53283
  Regression -> MSE: 0.000108, MAE: 0.008041, R²: -0.0002
  Directional -> Accuracy: 0.4714, MCC: -0.0925, F1: 0.5647

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.25675 | val 0.80462
  Epoch 016 - train 0.20181 | val 1.09096
  Regression -> MSE: 0.000158, MAE: 0.009884, R²: -0.0156
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.27788 | val 0.45455
  Epoch 016 - train 0.24791 | val 1.11473
  Regression -> MSE: 0.000277, MAE: 0.013239, R²: -0.0192
  Directional -> Accuracy: 0.5658, MCC: 0.1072, F1: 0.6292

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.22992 | val 0.43904
  Epoch 020 - train 0.20028 | val 0.45611
  Regression -> MSE: 0.000198, MAE: 0.010565, R²: -0.3203
  Directional -> Accuracy: 0.4769, MCC: 0.0998, F1: 0.2917

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.27576 | val 0.59754
  Epoch 018 - train 0.20698 | val 0.66517
  Regression -> MSE: 0.000250, MAE: 0.011264, R²: -0.1055
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.25073 | val 0.55027
  Epoch 016 - train 0.20291 | val 0.72222
  Regression -> MSE: 0.000160, MAE: 0.009085, R²: -0.1156
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.26089 | val 0.46373
  Epoch 016 - train 0.21498 | val 0.49179
  Regression -> MSE: 0.000176, MAE: 0.010245, R²: -0.0657
  Directional -> Accuracy: 0.5303, MCC: 0.0707, F1: 0.3673

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.24712 | val 0.47468
  Epoch 016 - train 0.22684 | val 0.54702
  Regression -> MSE: 0.000086, MAE: 0.007082, R²: -0.0050
  Directional -> Accuracy: 0.5517, MCC: 0.0601, F1: 0.6389

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.25429 | val 0.46784
  Epoch 017 - train 0.22434 | val 0.65045
  Regression -> MSE: 0.000212, MAE: 0.011101, R²: -0.0027
  Directional -> Accuracy: 0.4848, MCC: 0.0081, F1: 0.5952

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.21550 | val 0.27117
  Epoch 020 - train 0.17329 | val 0.29672
  Regression -> MSE: 0.000111, MAE: 0.008471, R²: -0.2057
  Directional -> Accuracy: 0.3929, MCC: -0.1869, F1: 0.2273

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.24863 | val 0.28524
  Epoch 016 - train 0.18850 | val 0.33176
  Regression -> MSE: 0.000110, MAE: 0.008998, R²: -0.0635
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.26700 | val 0.35510
  Epoch 020 - train 0.19004 | val 1.01838
  Regression -> MSE: 0.000231, MAE: 0.012325, R²: 0.0018
  Directional -> Accuracy: 0.6279, MCC: 0.2078, F1: 0.7143

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.24353 | val 0.43172
  Epoch 016 - train 0.20817 | val 0.49974
  Regression -> MSE: 0.000181, MAE: 0.007987, R²: -0.0848
  Directional -> Accuracy: 0.4561, MCC: -0.0820, F1: 0.4746

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.22393 | val 0.27301
  Epoch 016 - train 0.17190 | val 0.33681
  Regression -> MSE: 0.000236, MAE: 0.011922, R²: 0.0020
  Directional -> Accuracy: 0.4878, MCC: -0.0121, F1: 0.4615

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.22635 | val 0.63407
  Epoch 016 - train 0.18618 | val 0.61805
  Regression -> MSE: 0.000230, MAE: 0.009899, R²: 0.0000
  Directional -> Accuracy: 0.4651, MCC: -0.0746, F1: 0.4103

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.23964 | val 0.47063
  Epoch 017 - train 0.19203 | val 0.69182
  Regression -> MSE: 0.000136, MAE: 0.008211, R²: -0.0074
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.24781 | val 0.46591
  Epoch 016 - train 0.18635 | val 0.64850
  Regression -> MSE: 0.000199, MAE: 0.010642, R²: -0.0578
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.22650 | val 0.39778
  Epoch 020 - train 0.17952 | val 0.46843
  Regression -> MSE: 0.000321, MAE: 0.012233, R²: -0.2277
  Directional -> Accuracy: 0.4521, MCC: -0.0358, F1: 0.3103

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.18888 | val 0.36380
  Epoch 016 - train 0.13269 | val 0.53635
  Regression -> MSE: 0.000155, MAE: 0.010181, R²: 0.0726
  Directional -> Accuracy: 0.5526, MCC: 0.1132, F1: 0.6222

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.20494 | val 0.42234
  Epoch 016 - train 0.17659 | val 0.48755
  Regression -> MSE: 0.000181, MAE: 0.010350, R²: -0.0048
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.25330 | val 0.35751
  Epoch 016 - train 0.23149 | val 0.38830
  Regression -> MSE: 0.000343, MAE: 0.011877, R²: -0.0002
  Directional -> Accuracy: 0.4478, MCC: 0.1075, F1: 0.0513

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.20335 | val 0.21156
  Epoch 016 - train 0.14797 | val 0.29898
  Regression -> MSE: 0.000119, MAE: 0.008212, R²: -0.1291
  Directional -> Accuracy: 0.6744, MCC: 0.3810, F1: 0.6111

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.23993 | val 0.55786
  Epoch 016 - train 0.20686 | val 0.64583
  Regression -> MSE: 0.000220, MAE: 0.011297, R²: -0.0055
  Directional -> Accuracy: 0.5614, MCC: 0.2181, F1: 0.6667

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.22892 | val 0.68346
  Epoch 016 - train 0.18239 | val 0.68402
  Regression -> MSE: 0.000090, MAE: 0.007426, R²: -0.1600
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.24514 | val 0.24262
  Epoch 017 - train 0.20154 | val 0.25077
  Regression -> MSE: 0.000310, MAE: 0.013831, R²: -0.0074
  Directional -> Accuracy: 0.6122, MCC: 0.0228, F1: 0.1739

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.20562 | val 0.23212
  Epoch 017 - train 0.13553 | val 0.30853
  Regression -> MSE: 0.000249, MAE: 0.011483, R²: -0.0194
  Directional -> Accuracy: 0.4211, MCC: -0.2079, F1: 0.5417

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.25691 | val 0.54102
  Epoch 019 - train 0.19373 | val 0.66362
  Regression -> MSE: 0.000081, MAE: 0.007067, R²: -0.0001
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.26336 | val 0.44489
  Epoch 017 - train 0.23209 | val 0.59846
  Regression -> MSE: 0.000324, MAE: 0.014653, R²: -0.0548
  Directional -> Accuracy: 0.4468, MCC: -0.1229, F1: 0.1875

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.23484 | val 0.37900
  Epoch 020 - train 0.17527 | val 0.41722
  Regression -> MSE: 0.000099, MAE: 0.007091, R²: -0.0056
  Directional -> Accuracy: 0.5682, MCC: 0.1041, F1: 0.6415

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.23495 | val 0.47628
  Epoch 017 - train 0.13347 | val 0.54930
  Regression -> MSE: 0.000175, MAE: 0.010042, R²: -0.0187
  Directional -> Accuracy: 0.3673, MCC: -0.1462, F1: 0.5231

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.22636 | val 0.42394
  Epoch 016 - train 0.20545 | val 0.45945
  Regression -> MSE: 0.000225, MAE: 0.011875, R²: -0.0092
  Directional -> Accuracy: 0.4643, MCC: -0.2067, F1: 0.6250

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.23179 | val 0.60092
  Epoch 016 - train 0.15683 | val 0.82312
  Regression -> MSE: 0.000096, MAE: 0.007889, R²: -0.0359
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.29294 | val 0.64170
  Epoch 016 - train 0.21347 | val 0.97093
  Regression -> MSE: 0.000164, MAE: 0.010184, R²: 0.0005
  Directional -> Accuracy: 0.5556, MCC: 0.1126, F1: 0.5556

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.24798 | val 0.49123
  Epoch 016 - train 0.19736 | val 0.49911
  Regression -> MSE: 0.000122, MAE: 0.009008, R²: -0.0552
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.27304 | val 0.79979

[I 2026-02-22 23:04:33,385] Trial 97 finished with value: -0.011467654915408833 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.0, 'batch_size': 64, 'learning_rate': 0.009853047586803158, 'weight_decay': 3.499495747217405e-06, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 0.7132799821570663, 'early_stopping_min_delta': 0.007995238026050046}. Best is trial 90 with value: -0.011414558399902668.

  Epoch 020 - train 0.18502 | val 1.09783
  Regression -> MSE: 0.000230, MAE: 0.012358, R²: 0.0318
  Directional -> Accuracy: 0.5574, MCC: 0.1904, F1: 0.6582

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.27154 | val 0.47989
  Epoch 016 - train 0.24329 | val 0.56733
  Regression -> MSE: 0.000247, MAE: 0.012445, R²: 0.0039
  Directional -> Accuracy: 0.5844, MCC: 0.1945, F1: 0.6098

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.27786 | val 0.31273
  Epoch 016 - train 0.25092 | val 0.30517
  Regression -> MSE: 0.000675, MAE: 0.019157, R²: 0.0136
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.27821 | val 0.57235
  Epoch 016 - train 0.27626 | val 0.57584
  Regression -> MSE: 0.000313, MAE: 0.014466, R²: -0.0077
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.22926 | val 0.46247
  Epoch 016 - train 0.21700 | val 0.78851
  Regression -> MSE: 0.000350, MAE: 0.014565, R²: -0.0024
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.27718 | val 0.31247
  Epoch 020 - train 0.25299 | val 0.46040
  Regression -> MSE: 0.000203, MAE: 0.009974, R²: 0.0039
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.25607 | val 0.64755
  Epoch 020 - train 0.22583 | val 0.66516
  Regression -> MSE: 0.000573, MAE: 0.018562, R²: -0.0318
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.29173 | val 0.41184
  Epoch 018 - train 0.27048 | val 0.48546
  Regression -> MSE: 0.000242, MAE: 0.011995, R²: 0.0130
  Directional -> Accuracy: 0.5652, MCC: 0.1531, F1: 0.5455

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.29144 | val 0.48744
  Epoch 016 - train 0.24646 | val 0.55070
  Regression -> MSE: 0.000602, MAE: 0.019235, R²: -0.0074
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.27506 | val 0.40171
  Epoch 020 - train 0.23741 | val 0.52820
  Regression -> MSE: 0.000381, MAE: 0.015887, R²: 0.0076
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.26683 | val 0.44302
  Epoch 016 - train 0.25571 | val 0.45054
  Regression -> MSE: 0.000241, MAE: 0.011841, R²: 0.0024
  Directional -> Accuracy: 0.4143, MCC: -0.1390, F1: 0.5859

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.25365 | val 0.79029
  Epoch 016 - train 0.23964 | val 1.14019
  Regression -> MSE: 0.000304, MAE: 0.013640, R²: 0.0209
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.6301

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.28349 | val 0.41643
  Epoch 016 - train 0.26828 | val 0.47239
  Regression -> MSE: 0.000673, MAE: 0.019357, R²: 0.0069
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.27066 | val 0.35249
  Epoch 016 - train 0.25673 | val 0.43039
  Regression -> MSE: 0.000137, MAE: 0.009079, R²: 0.0095
  Directional -> Accuracy: 0.5581, MCC: 0.1997, F1: 0.6275

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.24969 | val 0.42211
  Epoch 016 - train 0.22247 | val 0.42637
  Regression -> MSE: 0.000227, MAE: 0.010712, R²: -0.0101
  Directional -> Accuracy: 0.4918, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.25626 | val 0.89095
  Epoch 016 - train 0.23900 | val 1.05922
  Regression -> MSE: 0.000363, MAE: 0.016233, R²: -0.0019
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.28028 | val 0.37210
  Epoch 016 - train 0.26408 | val 0.40101
  Regression -> MSE: 0.000109, MAE: 0.008078, R²: -0.0129
  Directional -> Accuracy: 0.4143, MCC: -0.2377, F1: 0.5393

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.26115 | val 0.59432
  Epoch 016 - train 0.25039 | val 0.65595
  Regression -> MSE: 0.000161, MAE: 0.010159, R²: -0.0358
  Directional -> Accuracy: 0.4068, MCC: -0.0642, F1: 0.3137

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.27627 | val 0.39311
  Epoch 016 - train 0.26755 | val 0.45315
  Regression -> MSE: 0.000295, MAE: 0.014025, R²: -0.0851
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.24348 | val 0.41915
  Epoch 020 - train 0.21453 | val 0.42554
  Regression -> MSE: 0.000203, MAE: 0.010497, R²: -0.3579
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.27742 | val 0.47464
  Epoch 020 - train 0.23512 | val 0.51410
  Regression -> MSE: 0.000294, MAE: 0.012401, R²: -0.2977
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.26193 | val 0.45575
  Epoch 016 - train 0.25158 | val 0.58992
  Regression -> MSE: 0.000145, MAE: 0.008502, R²: -0.0115
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.26267 | val 0.38188
  Epoch 016 - train 0.24971 | val 0.39299
  Regression -> MSE: 0.000174, MAE: 0.010295, R²: -0.0558
  Directional -> Accuracy: 0.4848, MCC: -0.0407, F1: 0.2273

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.28014 | val 0.38473
  Epoch 016 - train 0.26680 | val 0.41405
  Regression -> MSE: 0.000084, MAE: 0.007005, R²: 0.0192
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.26883 | val 0.41809
  Epoch 018 - train 0.25924 | val 0.44913
  Regression -> MSE: 0.000211, MAE: 0.010997, R²: 0.0056
  Directional -> Accuracy: 0.5000, MCC: -0.0018, F1: 0.4762

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.23474 | val 0.25112
  Epoch 020 - train 0.21929 | val 0.23368
  Regression -> MSE: 0.000114, MAE: 0.008496, R²: -0.2432
  Directional -> Accuracy: 0.5000, MCC: 0.0565, F1: 0.3913

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.27526 | val 0.24639
  Epoch 016 - train 0.26982 | val 0.25706
  Regression -> MSE: 0.000107, MAE: 0.008894, R²: -0.0394
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.29761 | val 0.30940
  Epoch 016 - train 0.26346 | val 0.30211
  Regression -> MSE: 0.000235, MAE: 0.012628, R²: -0.0131
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.26741 | val 0.38262
  Epoch 020 - train 0.24884 | val 0.41397
  Regression -> MSE: 0.000182, MAE: 0.007858, R²: -0.0914
  Directional -> Accuracy: 0.5965, MCC: 0.1707, F1: 0.6567

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.28980 | val 0.24668
  Epoch 016 - train 0.25514 | val 0.25258
  Regression -> MSE: 0.000236, MAE: 0.011923, R²: 0.0031
  Directional -> Accuracy: 0.5366, MCC: 0.0587, F1: 0.5957

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.24492 | val 0.58708
  Epoch 016 - train 0.23598 | val 0.64130
  Regression -> MSE: 0.000231, MAE: 0.009939, R²: -0.0023
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.26520 | val 0.44373
  Epoch 018 - train 0.24995 | val 0.54946
  Regression -> MSE: 0.000138, MAE: 0.008273, R²: -0.0198
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.27400 | val 0.43660
  Epoch 019 - train 0.25546 | val 0.47106
  Regression -> MSE: 0.000190, MAE: 0.010507, R²: -0.0100
  Directional -> Accuracy: 0.5400, MCC: 0.0164, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.23089 | val 0.38003
  Epoch 020 - train 0.21129 | val 0.40962
  Regression -> MSE: 0.000314, MAE: 0.011998, R²: -0.2008
  Directional -> Accuracy: 0.4521, MCC: -0.0137, F1: 0.2308

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.25016 | val 0.27905
  Epoch 016 - train 0.23636 | val 0.36418
  Regression -> MSE: 0.000163, MAE: 0.010298, R²: 0.0248
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.24270 | val 0.33462
  Epoch 016 - train 0.23335 | val 0.34596
  Regression -> MSE: 0.000177, MAE: 0.010218, R²: 0.0170
  Directional -> Accuracy: 0.5227, MCC: 0.1145, F1: 0.6441

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.26115 | val 0.30338
  Epoch 016 - train 0.25675 | val 0.32132
  Regression -> MSE: 0.000349, MAE: 0.011892, R²: -0.0173
  Directional -> Accuracy: 0.4776, MCC: -0.0977, F1: 0.5783

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.26890 | val 0.18047
  Epoch 016 - train 0.25096 | val 0.19985
  Regression -> MSE: 0.000115, MAE: 0.008085, R²: -0.0919
  Directional -> Accuracy: 0.6977, MCC: 0.4094, F1: 0.6667

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.26967 | val 0.51521
  Epoch 016 - train 0.24495 | val 0.60107
  Regression -> MSE: 0.000219, MAE: 0.011292, R²: -0.0028
  Directional -> Accuracy: 0.5088, MCC: -0.1268, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.26313 | val 0.62354
  Epoch 016 - train 0.24218 | val 0.63659
  Regression -> MSE: 0.000085, MAE: 0.007193, R²: -0.0963
  Directional -> Accuracy: 0.3830, MCC: -0.0734, F1: 0.1212

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.26114 | val 0.24917
  Epoch 020 - train 0.25701 | val 0.23533
  Regression -> MSE: 0.000456, MAE: 0.018167, R²: -0.4832
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.25375 | val 0.18166
  Epoch 016 - train 0.25379 | val 0.19694
  Regression -> MSE: 0.000253, MAE: 0.011402, R²: -0.0377
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.26485 | val 0.49849
  Epoch 016 - train 0.24729 | val 0.61319
  Regression -> MSE: 0.000080, MAE: 0.007026, R²: 0.0125
  Directional -> Accuracy: 0.5200, MCC: 0.1155, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.28724 | val 0.40776
  Epoch 016 - train 0.27608 | val 0.41139
  Regression -> MSE: 0.000307, MAE: 0.014483, R²: -0.0019
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.26744 | val 0.35184
  Epoch 016 - train 0.22299 | val 0.35943
  Regression -> MSE: 0.000099, MAE: 0.007262, R²: -0.0032
  Directional -> Accuracy: 0.5227, MCC: -0.1902, F1: 0.6866

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.26065 | val 0.41970
  Epoch 016 - train 0.24977 | val 0.41145
  Regression -> MSE: 0.000177, MAE: 0.010298, R²: -0.0327
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.24938 | val 0.48389
  Epoch 016 - train 0.23446 | val 0.60934
  Regression -> MSE: 0.000222, MAE: 0.011651, R²: 0.0060
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.26870 | val 0.43003
  Epoch 016 - train 0.25879 | val 0.60059
  Regression -> MSE: 0.000096, MAE: 0.007879, R²: -0.0445
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.29246 | val 0.70519
  Epoch 016 - train 0.27908 | val 0.84705
  Regression -> MSE: 0.000163, MAE: 0.010183, R²: 0.0064
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.24778 | val 0.40893
  Epoch 016 - train 0.23430 | val 0.44578
  Regression -> MSE: 0.000120, MAE: 0.008961, R²: -0.0363
  Directional -> Accuracy: 0.5179, MCC: 0.0766, F1: 0.3077

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.27356 | val 0.58742

[I 2026-02-22 23:05:09,547] Trial 98 finished with value: -0.011567683306292027 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.5, 'batch_size': 64, 'learning_rate': 0.005699213298321651, 'weight_decay': 8.539526141742442e-06, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 0.6297978065256421, 'early_stopping_min_delta': 0.007840515304864758}. Best is trial 90 with value: -0.011414558399902668.

  Epoch 016 - train 0.25952 | val 0.91384
  Regression -> MSE: 0.000237, MAE: 0.012469, R²: 0.0018
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.23941 | val 0.46367
  Epoch 020 - train 0.20091 | val 0.57358
  Regression -> MSE: 0.000262, MAE: 0.012531, R²: -0.0568
  Directional -> Accuracy: 0.5584, MCC: 0.1139, F1: 0.5278

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.23961 | val 0.31385
  Epoch 020 - train 0.18824 | val 0.34896
  Regression -> MSE: 0.000658, MAE: 0.018834, R²: 0.0381
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.25100 | val 0.62171
  Epoch 020 - train 0.18199 | val 0.64282
  Regression -> MSE: 0.000315, MAE: 0.014461, R²: -0.0163
  Directional -> Accuracy: 0.5532, MCC: 0.1581, F1: 0.4324

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.24012 | val 0.76272
  Epoch 020 - train 0.18928 | val 1.61591
  Regression -> MSE: 0.000346, MAE: 0.014484, R²: 0.0098
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.24810 | val 0.32341
  Epoch 020 - train 0.19856 | val 0.50121
  Regression -> MSE: 0.000204, MAE: 0.010026, R²: 0.0001
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.21039 | val 0.69711
  Epoch 020 - train 0.15587 | val 0.88014
  Regression -> MSE: 0.000562, MAE: 0.018640, R²: -0.0121
  Directional -> Accuracy: 0.5745, MCC: 0.1489, F1: 0.5000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.27113 | val 0.49150
  Epoch 020 - train 0.21495 | val 0.66420
  Regression -> MSE: 0.000248, MAE: 0.011967, R²: -0.0104
  Directional -> Accuracy: 0.5797, MCC: -0.1002, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.18174 | val 0.54710
  Epoch 020 - train 0.12386 | val 0.77301
  Regression -> MSE: 0.000610, MAE: 0.019430, R²: -0.0204
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.22444 | val 0.41505
  Epoch 020 - train 0.16543 | val 0.60010
  Regression -> MSE: 0.000402, MAE: 0.016702, R²: -0.0475
  Directional -> Accuracy: 0.4490, MCC: -0.0212, F1: 0.6087

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.29605 | val 0.48061
  Epoch 020 - train 0.19888 | val 0.70149
  Regression -> MSE: 0.000244, MAE: 0.011855, R²: -0.0123
  Directional -> Accuracy: 0.4286, MCC: -0.0786, F1: 0.5238

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.23106 | val 0.54824
  Epoch 020 - train 0.17910 | val 1.14974
  Regression -> MSE: 0.000311, MAE: 0.013509, R²: -0.0010
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.24048 | val 0.42836
  Epoch 020 - train 0.20130 | val 0.70401
  Regression -> MSE: 0.000677, MAE: 0.019521, R²: 0.0009
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.23120 | val 0.35829
  Epoch 020 - train 0.16875 | val 0.33357
  Regression -> MSE: 0.000140, MAE: 0.009279, R²: -0.0100
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.21344 | val 0.50394
  Epoch 020 - train 0.18097 | val 0.57457
  Regression -> MSE: 0.000227, MAE: 0.010764, R²: -0.0108
  Directional -> Accuracy: 0.4918, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.23496 | val 0.93278
  Epoch 020 - train 0.19520 | val 2.24562
  Regression -> MSE: 0.000361, MAE: 0.016163, R²: 0.0021
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.26192 | val 0.43598
  Epoch 020 - train 0.18580 | val 0.64818
  Regression -> MSE: 0.000108, MAE: 0.008088, R²: 0.0022
  Directional -> Accuracy: 0.4571, MCC: -0.0309, F1: 0.1739

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.23110 | val 0.63700
  Epoch 020 - train 0.16813 | val 0.81775
  Regression -> MSE: 0.000159, MAE: 0.009969, R²: -0.0194
  Directional -> Accuracy: 0.6780, MCC: 0.2590, F1: 0.7865

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.26199 | val 0.35580
  Epoch 020 - train 0.22296 | val 0.62480
  Regression -> MSE: 0.000275, MAE: 0.013042, R²: -0.0124
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.22199 | val 0.44594
  Epoch 020 - train 0.19420 | val 0.43897
  Regression -> MSE: 0.000211, MAE: 0.011060, R²: -0.4092
  Directional -> Accuracy: 0.4769, MCC: 0.0998, F1: 0.2917

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.26719 | val 0.52334
  Epoch 020 - train 0.20918 | val 0.68537
  Regression -> MSE: 0.000279, MAE: 0.012017, R²: -0.2345
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.23223 | val 0.45169
  Epoch 020 - train 0.18687 | val 0.90419
  Regression -> MSE: 0.000159, MAE: 0.009089, R²: -0.1121
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.25506 | val 0.41272
  Epoch 020 - train 0.21279 | val 0.43663
  Regression -> MSE: 0.000177, MAE: 0.010308, R²: -0.0735
  Directional -> Accuracy: 0.5303, MCC: 0.1054, F1: 0.2051

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.25152 | val 0.42056
  Epoch 020 - train 0.19512 | val 0.50799
  Regression -> MSE: 0.000086, MAE: 0.007066, R²: -0.0088
  Directional -> Accuracy: 0.5517, MCC: 0.1362, F1: 0.5357

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.26713 | val 0.46852
  Epoch 020 - train 0.21409 | val 0.77811
  Regression -> MSE: 0.000211, MAE: 0.011003, R²: 0.0024
  Directional -> Accuracy: 0.5303, MCC: 0.0589, F1: 0.5079

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.19613 | val 0.27729
  Epoch 020 - train 0.16771 | val 0.29029
  Regression -> MSE: 0.000117, MAE: 0.008564, R²: -0.2664
  Directional -> Accuracy: 0.5536, MCC: 0.3111, F1: 0.3243

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.23464 | val 0.27411
  Epoch 020 - train 0.15464 | val 0.30560
  Regression -> MSE: 0.000111, MAE: 0.009029, R²: -0.0780
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.25321 | val 0.32070
  Epoch 020 - train 0.19208 | val 0.39445
  Regression -> MSE: 0.000240, MAE: 0.012277, R²: -0.0348
  Directional -> Accuracy: 0.5581, MCC: 0.0427, F1: 0.6667

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.24891 | val 0.42205
  Epoch 020 - train 0.20099 | val 0.52524
  Regression -> MSE: 0.000193, MAE: 0.008079, R²: -0.1573
  Directional -> Accuracy: 0.5614, MCC: 0.3307, F1: 0.3590

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.22169 | val 0.27755
  Epoch 020 - train 0.15797 | val 0.36277
  Regression -> MSE: 0.000235, MAE: 0.011851, R²: 0.0053
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.21145 | val 0.62661
  Epoch 020 - train 0.14996 | val 0.65314
  Regression -> MSE: 0.000233, MAE: 0.010053, R²: -0.0103
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.23034 | val 0.45092
  Epoch 020 - train 0.17586 | val 0.52179
  Regression -> MSE: 0.000139, MAE: 0.008395, R²: -0.0272
  Directional -> Accuracy: 0.4186, MCC: -0.1489, F1: 0.2424

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.21808 | val 0.47527
  Epoch 020 - train 0.16778 | val 0.66804
  Regression -> MSE: 0.000194, MAE: 0.010464, R²: -0.0308
  Directional -> Accuracy: 0.4800, MCC: -0.0088, F1: 0.3810

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.21738 | val 0.41375
  Epoch 020 - train 0.18159 | val 0.44469
  Regression -> MSE: 0.000271, MAE: 0.010705, R²: -0.0353
  Directional -> Accuracy: 0.4247, MCC: -0.1140, F1: 0.3438

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.20176 | val 0.28268
  Epoch 020 - train 0.11314 | val 0.33464
  Regression -> MSE: 0.000166, MAE: 0.010350, R²: 0.0067
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.19513 | val 0.36790
  Epoch 020 - train 0.16669 | val 0.39031
  Regression -> MSE: 0.000181, MAE: 0.010305, R²: -0.0065
  Directional -> Accuracy: 0.5227, MCC: 0.0547, F1: 0.5532

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.25158 | val 0.37479
  Epoch 020 - train 0.20480 | val 0.41404
  Regression -> MSE: 0.000348, MAE: 0.011800, R²: -0.0163
  Directional -> Accuracy: 0.5522, MCC: -0.0188, F1: 0.7000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.19430 | val 0.19450
  Epoch 020 - train 0.15448 | val 0.28455
  Regression -> MSE: 0.000118, MAE: 0.008245, R²: -0.1204
  Directional -> Accuracy: 0.6744, MCC: 0.3810, F1: 0.6111

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.21592 | val 0.60391
  Epoch 020 - train 0.16697 | val 1.03800
  Regression -> MSE: 0.000221, MAE: 0.011278, R²: -0.0105
  Directional -> Accuracy: 0.5088, MCC: 0.1809, F1: 0.6585

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.21571 | val 0.67955
  Epoch 020 - train 0.15687 | val 0.75512
  Regression -> MSE: 0.000085, MAE: 0.007210, R²: -0.0934
  Directional -> Accuracy: 0.4255, MCC: 0.0391, F1: 0.2286

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.23015 | val 0.23190
  Epoch 020 - train 0.16822 | val 0.22370
  Regression -> MSE: 0.000343, MAE: 0.015617, R²: -0.1166
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.20445 | val 0.19917
  Epoch 020 - train 0.09702 | val 0.26441
  Regression -> MSE: 0.000251, MAE: 0.011481, R²: -0.0279
  Directional -> Accuracy: 0.5263, MCC: 0.0403, F1: 0.5909

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.25666 | val 0.50417
  Epoch 020 - train 0.20469 | val 0.73978
  Regression -> MSE: 0.000081, MAE: 0.007118, R²: -0.0043
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.23514 | val 0.42852
  Epoch 020 - train 0.16075 | val 0.54769
  Regression -> MSE: 0.000314, MAE: 0.014527, R²: -0.0220
  Directional -> Accuracy: 0.5532, MCC: 0.1151, F1: 0.6557

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.21927 | val 0.38745
  Epoch 020 - train 0.15415 | val 0.37016
  Regression -> MSE: 0.000098, MAE: 0.007122, R²: 0.0067
  Directional -> Accuracy: 0.5682, MCC: 0.0300, F1: 0.7164

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.23164 | val 0.45092
  Epoch 020 - train 0.13766 | val 0.48028
  Regression -> MSE: 0.000172, MAE: 0.009753, R²: -0.0010
  Directional -> Accuracy: 0.3469, MCC: -0.2592, F1: 0.5152

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.21168 | val 0.42602
  Epoch 020 - train 0.17828 | val 0.96740
  Regression -> MSE: 0.000222, MAE: 0.011748, R²: 0.0050
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.22189 | val 0.46244
  Epoch 020 - train 0.15463 | val 0.74957
  Regression -> MSE: 0.000092, MAE: 0.007705, R²: -0.0011
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.26709 | val 0.69373
  Epoch 020 - train 0.19310 | val 1.47919
  Regression -> MSE: 0.000164, MAE: 0.010219, R²: 0.0011
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.22040 | val 0.43484
  Epoch 020 - train 0.18798 | val 0.48136
  Regression -> MSE: 0.000123, MAE: 0.009051, R²: -0.0616
  Directional -> Accuracy: 0.4464, MCC: -0.1995, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.24663 | val 0.51391

[I 2026-02-22 23:07:35,785] Trial 99 finished with value: -0.011510016986753404 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.0, 'batch_size': 64, 'learning_rate': 0.0022735344070854667, 'weight_decay': 3.553696940921476e-06, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.7096710116024043, 'early_stopping_min_delta': 0.00796544879003817}. Best is trial 90 with value: -0.011414558399902668.

  Epoch 020 - train 0.19733 | val 1.66021
  Regression -> MSE: 0.000237, MAE: 0.012750, R²: 0.0001
  Directional -> Accuracy: 0.5410, MCC: 0.2042, F1: 0.6667

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.28977 | val 0.75900
  Epoch 015 - train 0.27685 | val 0.79569
  Regression -> MSE: 0.000252, MAE: 0.012712, R²: -0.0198
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.28616 | val 0.33940
  Epoch 017 - train 0.26995 | val 0.38064
  Regression -> MSE: 0.000657, MAE: 0.018835, R²: 0.0402
  Directional -> Accuracy: 0.5870, MCC: 0.1700, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.31958 | val 0.70815
  Epoch 011 - train 0.30939 | val 0.71468
  Regression -> MSE: 0.000323, MAE: 0.014610, R²: -0.0419
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.25346 | val 0.72389
  Epoch 011 - train 0.25172 | val 0.73391
  Regression -> MSE: 0.000348, MAE: 0.014491, R²: 0.0038
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.29023 | val 0.45681
  Epoch 011 - train 0.28973 | val 0.45178
  Regression -> MSE: 0.000203, MAE: 0.010058, R²: 0.0032
  Directional -> Accuracy: 0.5490, MCC: 0.0855, F1: 0.6849

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.28218 | val 0.78417
  Epoch 011 - train 0.26301 | val 0.78772
  Regression -> MSE: 0.000572, MAE: 0.018439, R²: -0.0297
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.32184 | val 0.48218
  Epoch 011 - train 0.29912 | val 0.50487
  Regression -> MSE: 0.000247, MAE: 0.011943, R²: -0.0079
  Directional -> Accuracy: 0.6087, MCC: 0.1133, F1: 0.2286

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.25592 | val 0.67632
  Epoch 011 - train 0.24509 | val 0.68491
  Regression -> MSE: 0.000615, MAE: 0.019564, R²: -0.0289
  Directional -> Accuracy: 0.4318, MCC: -0.1145, F1: 0.4186

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.27306 | val 0.44919
  Epoch 017 - train 0.25005 | val 0.53041
  Regression -> MSE: 0.000395, MAE: 0.016265, R²: -0.0287
  Directional -> Accuracy: 0.4082, MCC: -0.1804, F1: 0.5672

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.27464 | val 0.49833
  Epoch 011 - train 0.29451 | val 0.50433
  Regression -> MSE: 0.000241, MAE: 0.011795, R²: 0.0005
  Directional -> Accuracy: 0.4571, MCC: 0.0888, F1: 0.6042

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.26164 | val 0.71075
  Epoch 011 - train 0.26457 | val 0.76575
  Regression -> MSE: 0.000312, MAE: 0.013521, R²: -0.0047
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.30141 | val 0.47156
  Epoch 011 - train 0.31392 | val 0.50320
  Regression -> MSE: 0.000672, MAE: 0.019424, R²: 0.0076
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.29734 | val 0.44807
  Epoch 012 - train 0.28550 | val 0.45894
  Regression -> MSE: 0.000138, MAE: 0.008976, R²: 0.0032
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.25417 | val 0.50776
  Epoch 011 - train 0.25091 | val 0.50742
  Regression -> MSE: 0.000223, MAE: 0.010634, R²: 0.0087
  Directional -> Accuracy: 0.5410, MCC: 0.1872, F1: 0.6889

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.28963 | val 1.03111
  Epoch 012 - train 0.29320 | val 0.94552
  Regression -> MSE: 0.000361, MAE: 0.016059, R²: 0.0030
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.30857 | val 0.44617
  Epoch 011 - train 0.29913 | val 0.45268
  Regression -> MSE: 0.000109, MAE: 0.008113, R²: -0.0117
  Directional -> Accuracy: 0.4571, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.28168 | val 0.72183
  Epoch 011 - train 0.27686 | val 0.72429
  Regression -> MSE: 0.000160, MAE: 0.010111, R²: -0.0240
  Directional -> Accuracy: 0.4576, MCC: 0.0064, F1: 0.4286

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.30314 | val 0.57798
  Epoch 011 - train 0.30178 | val 0.67638
  Regression -> MSE: 0.000285, MAE: 0.013674, R²: -0.0464
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.26699 | val 0.48645
  Epoch 019 - train 0.24209 | val 0.50026
  Regression -> MSE: 0.000211, MAE: 0.010842, R²: -0.4076
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.28877 | val 0.58227
  Epoch 017 - train 0.26953 | val 0.65889
  Regression -> MSE: 0.000412, MAE: 0.015526, R²: -0.8206
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.29108 | val 0.48242
  Epoch 011 - train 0.30225 | val 0.49496
  Regression -> MSE: 0.000148, MAE: 0.008695, R²: -0.0351
  Directional -> Accuracy: 0.5000, MCC: -0.0216, F1: 0.5714

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.27850 | val 0.45407
  Epoch 011 - train 0.28029 | val 0.46528
  Regression -> MSE: 0.000172, MAE: 0.010305, R²: -0.0403
  Directional -> Accuracy: 0.4545, MCC: -0.0925, F1: 0.5000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.30917 | val 0.47133
  Epoch 011 - train 0.30017 | val 0.48203
  Regression -> MSE: 0.000086, MAE: 0.007127, R²: -0.0124
  Directional -> Accuracy: 0.5517, MCC: 0.0425, F1: 0.6579

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.30285 | val 0.48895
  Epoch 011 - train 0.29529 | val 0.57565
  Regression -> MSE: 0.000211, MAE: 0.011230, R²: 0.0039
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.25472 | val 0.28382
  Epoch 020 - train 0.22971 | val 0.30800
  Regression -> MSE: 0.000110, MAE: 0.008574, R²: -0.1984
  Directional -> Accuracy: 0.4821, MCC: 0.1096, F1: 0.1714

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.30421 | val 0.28311
  Epoch 011 - train 0.31265 | val 0.27462
  Regression -> MSE: 0.000107, MAE: 0.008877, R²: -0.0410
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.31773 | val 0.34380
  Epoch 011 - train 0.29940 | val 0.34238
  Regression -> MSE: 0.000237, MAE: 0.012737, R²: -0.0257
  Directional -> Accuracy: 0.5814, MCC: 0.1539, F1: 0.6250

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.30193 | val 0.42540
  Epoch 011 - train 0.29295 | val 0.42379
  Regression -> MSE: 0.000192, MAE: 0.008173, R²: -0.1512
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.30894 | val 0.33397
  Epoch 013 - train 0.28659 | val 0.36973
  Regression -> MSE: 0.000234, MAE: 0.011854, R²: 0.0125
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.28494 | val 0.68014
  Epoch 011 - train 0.28279 | val 0.69244
  Regression -> MSE: 0.000232, MAE: 0.009921, R²: -0.0048
  Directional -> Accuracy: 0.4419, MCC: -0.1169, F1: 0.4286

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.32355 | val 0.50133
  Epoch 015 - train 0.27526 | val 0.56057
  Regression -> MSE: 0.000138, MAE: 0.008327, R²: -0.0204
  Directional -> Accuracy: 0.4419, MCC: -0.2062, F1: 0.5862

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.30287 | val 0.49175
  Epoch 011 - train 0.29163 | val 0.48858
  Regression -> MSE: 0.000199, MAE: 0.010674, R²: -0.0594
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.25562 | val 0.43877
  Epoch 019 - train 0.23149 | val 0.47861
  Regression -> MSE: 0.000302, MAE: 0.011656, R²: -0.1520
  Directional -> Accuracy: 0.5068, MCC: 0.0836, F1: 0.4000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.28360 | val 0.32787
  Epoch 011 - train 0.25785 | val 0.33173
  Regression -> MSE: 0.000164, MAE: 0.010339, R²: 0.0172
  Directional -> Accuracy: 0.4737, MCC: -0.0529, F1: 0.5000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.26477 | val 0.39055
  Epoch 012 - train 0.25703 | val 0.41094
  Regression -> MSE: 0.000179, MAE: 0.010317, R²: 0.0041
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.29507 | val 0.38553
  Epoch 011 - train 0.28368 | val 0.38422
  Regression -> MSE: 0.000344, MAE: 0.012023, R²: -0.0041
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.28320 | val 0.20791
  Epoch 011 - train 0.26744 | val 0.21287
  Regression -> MSE: 0.000115, MAE: 0.008179, R²: -0.0952
  Directional -> Accuracy: 0.6977, MCC: 0.4009, F1: 0.6829

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.27386 | val 0.56610
  Epoch 011 - train 0.26751 | val 0.58366
  Regression -> MSE: 0.000219, MAE: 0.011334, R²: -0.0017
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.28445 | val 0.72784
  Epoch 011 - train 0.27169 | val 0.73924
  Regression -> MSE: 0.000086, MAE: 0.007275, R²: -0.1115
  Directional -> Accuracy: 0.4043, MCC: 0.0267, F1: 0.1250

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.28900 | val 0.26393
  Epoch 017 - train 0.25666 | val 0.25132
  Regression -> MSE: 0.000336, MAE: 0.015215, R²: -0.0915
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.27105 | val 0.21254
  Epoch 011 - train 0.28844 | val 0.21074
  Regression -> MSE: 0.000256, MAE: 0.011436, R²: -0.0516
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.27726 | val 0.51721
  Epoch 017 - train 0.24856 | val 0.72088
  Regression -> MSE: 0.000081, MAE: 0.007092, R²: -0.0030
  Directional -> Accuracy: 0.4800, MCC: -0.1178, F1: 0.6486

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.30812 | val 0.46358
  Epoch 020 - train 0.24982 | val 0.54987
  Regression -> MSE: 0.000328, MAE: 0.014902, R²: -0.0691
  Directional -> Accuracy: 0.4894, MCC: -0.0125, F1: 0.3333

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.27556 | val 0.43329
  Epoch 020 - train 0.23910 | val 0.39198
  Regression -> MSE: 0.000100, MAE: 0.007071, R²: -0.0232
  Directional -> Accuracy: 0.6136, MCC: 0.2503, F1: 0.7463

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.30298 | val 0.49261
  Epoch 011 - train 0.29380 | val 0.49010
  Regression -> MSE: 0.000182, MAE: 0.010511, R²: -0.0565
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.27219 | val 0.60914
  Epoch 011 - train 0.24470 | val 0.56564
  Regression -> MSE: 0.000225, MAE: 0.011777, R²: -0.0095
  Directional -> Accuracy: 0.5000, MCC: 0.1192, F1: 0.1765

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.26601 | val 0.48152
  Epoch 011 - train 0.27278 | val 0.50791
  Regression -> MSE: 0.000096, MAE: 0.007958, R²: -0.0454
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.31975 | val 0.67741
  Epoch 011 - train 0.31533 | val 0.77147
  Regression -> MSE: 0.000163, MAE: 0.010135, R²: 0.0049
  Directional -> Accuracy: 0.6111, MCC: 0.2193, F1: 0.6441

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.28277 | val 0.46515
  Epoch 011 - train 0.26307 | val 0.47691
  Regression -> MSE: 0.000126, MAE: 0.009060, R²: -0.0850
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...

[I 2026-02-22 23:08:03,789] Trial 100 finished with value: -0.01161671902178493 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 64, 'learning_rate': 0.004319442388619306, 'weight_decay': 6.1811461663132285e-06, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 0.7880570229298388, 'early_stopping_min_delta': 0.009417095875973112}. Best is trial 90 with value: -0.011414558399902668.

  Epoch 010 - train 0.29948 | val 0.68843
  Epoch 011 - train 0.29317 | val 0.74651
  Regression -> MSE: 0.000238, MAE: 0.012468, R²: -0.0055
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.26659 | val 0.83055
  Epoch 020 - train 0.20808 | val 0.62648
  Regression -> MSE: 0.000251, MAE: 0.012488, R²: -0.0123
  Directional -> Accuracy: 0.5844, MCC: 0.1430, F1: 0.4074

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.28710 | val 0.37838
  Epoch 017 - train 0.23497 | val 0.44440
  Regression -> MSE: 0.000676, MAE: 0.019282, R²: 0.0124
  Directional -> Accuracy: 0.6304, MCC: 0.2573, F1: 0.7463

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.29235 | val 0.74025
  Epoch 016 - train 0.23940 | val 0.75784
  Regression -> MSE: 0.000333, MAE: 0.014629, R²: -0.0736
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.23915 | val 1.44741
  Epoch 016 - train 0.22985 | val 1.83574
  Regression -> MSE: 0.000365, MAE: 0.014790, R²: -0.0447
  Directional -> Accuracy: 0.4667, MCC: 0.1059, F1: 0.0476

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.26700 | val 0.55681
  Epoch 016 - train 0.24052 | val 0.69506
  Regression -> MSE: 0.000203, MAE: 0.010202, R²: 0.0027
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.23764 | val 0.83450
  Epoch 020 - train 0.18508 | val 0.87969
  Regression -> MSE: 0.000576, MAE: 0.018875, R²: -0.0372
  Directional -> Accuracy: 0.5319, MCC: 0.0764, F1: 0.2143

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.30959 | val 0.61115
  Epoch 020 - train 0.20479 | val 0.63515
  Regression -> MSE: 0.000252, MAE: 0.011993, R²: -0.0247
  Directional -> Accuracy: 0.6087, MCC: 0.1239, F1: 0.3077

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.20250 | val 0.60766
  Epoch 016 - train 0.16245 | val 0.74402
  Regression -> MSE: 0.000611, MAE: 0.019448, R²: -0.0234
  Directional -> Accuracy: 0.5682, MCC: 0.0691, F1: 0.3871

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.24956 | val 0.50846
  Epoch 020 - train 0.17850 | val 0.73599
  Regression -> MSE: 0.000373, MAE: 0.015727, R²: 0.0275
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.27864 | val 0.69354
  Epoch 016 - train 0.23463 | val 0.88193
  Regression -> MSE: 0.000245, MAE: 0.011688, R²: -0.0158
  Directional -> Accuracy: 0.5000, MCC: -0.0630, F1: 0.3137

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.23401 | val 1.21782
  Epoch 017 - train 0.18723 | val 2.27817
  Regression -> MSE: 0.000315, MAE: 0.013553, R²: -0.0139
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.26179 | val 0.49724
  Epoch 016 - train 0.21393 | val 0.60361
  Regression -> MSE: 0.000671, MAE: 0.019453, R²: 0.0095
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.25285 | val 0.42642
  Epoch 020 - train 0.15899 | val 0.52957
  Regression -> MSE: 0.000225, MAE: 0.011492, R²: -0.6250
  Directional -> Accuracy: 0.6512, MCC: 0.2839, F1: 0.5714

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.23282 | val 0.62198
  Epoch 016 - train 0.19963 | val 0.67738
  Regression -> MSE: 0.000223, MAE: 0.010630, R²: 0.0081
  Directional -> Accuracy: 0.5902, MCC: 0.3037, F1: 0.7126

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.25305 | val 0.97601
  Epoch 016 - train 0.22659 | val 0.97505
  Regression -> MSE: 0.000363, MAE: 0.015938, R²: -0.0020
  Directional -> Accuracy: 0.5769, MCC: 0.1338, F1: 0.3889

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.28191 | val 0.56522
  Epoch 016 - train 0.23582 | val 0.69047
  Regression -> MSE: 0.000110, MAE: 0.008117, R²: -0.0175
  Directional -> Accuracy: 0.3714, MCC: -0.2475, F1: 0.2143

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.25180 | val 0.95734
  Epoch 016 - train 0.21345 | val 1.06022
  Regression -> MSE: 0.000158, MAE: 0.009846, R²: -0.0117
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.29684 | val 0.99235
  Epoch 016 - train 0.26014 | val 1.84382
  Regression -> MSE: 0.000277, MAE: 0.013169, R²: -0.0173
  Directional -> Accuracy: 0.5921, MCC: 0.1221, F1: 0.6804

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.24567 | val 0.51123
  Epoch 020 - train 0.24835 | val 0.58457
  Regression -> MSE: 0.000208, MAE: 0.010909, R²: -0.3923
  Directional -> Accuracy: 0.4462, MCC: 0.0859, F1: 0.1429

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.30562 | val 0.68517
  Epoch 017 - train 0.23135 | val 1.06833
  Regression -> MSE: 0.000245, MAE: 0.011026, R²: -0.0825
  Directional -> Accuracy: 0.5333, MCC: 0.1783, F1: 0.3396

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.27269 | val 0.67942
  Epoch 016 - train 0.22678 | val 0.80334
  Regression -> MSE: 0.000147, MAE: 0.008575, R²: -0.0240
  Directional -> Accuracy: 0.6667, MCC: 0.2277, F1: 0.7778

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.26717 | val 0.50088
  Epoch 016 - train 0.23671 | val 0.49551
  Regression -> MSE: 0.000166, MAE: 0.010412, R²: -0.0060
  Directional -> Accuracy: 0.4848, MCC: -0.1240, F1: 0.6531

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.29327 | val 0.48345
  Epoch 019 - train 0.21048 | val 0.50181
  Regression -> MSE: 0.000083, MAE: 0.006966, R²: 0.0238
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.27700 | val 0.60502
  Epoch 017 - train 0.22085 | val 0.89418
  Regression -> MSE: 0.000211, MAE: 0.011238, R²: 0.0016
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.21131 | val 0.29587
  Epoch 020 - train 0.16311 | val 0.34360
  Regression -> MSE: 0.000102, MAE: 0.008383, R²: -0.1091
  Directional -> Accuracy: 0.4286, MCC: -0.1399, F1: 0.4483

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.26509 | val 0.29585
  Epoch 016 - train 0.19316 | val 0.35753
  Regression -> MSE: 0.000105, MAE: 0.008816, R²: -0.0223
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.27637 | val 0.38502
  Epoch 020 - train 0.20608 | val 0.64950
  Regression -> MSE: 0.000235, MAE: 0.012512, R²: -0.0151
  Directional -> Accuracy: 0.5814, MCC: 0.1539, F1: 0.6250

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.26201 | val 0.50309
  Epoch 016 - train 0.23011 | val 0.56177
  Regression -> MSE: 0.000184, MAE: 0.007926, R²: -0.1029
  Directional -> Accuracy: 0.5439, MCC: 0.2554, F1: 0.3500

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.23223 | val 0.35327
  Epoch 016 - train 0.19589 | val 0.43818
  Regression -> MSE: 0.000235, MAE: 0.011820, R²: 0.0083
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.22673 | val 0.76736
  Epoch 016 - train 0.19279 | val 0.81565
  Regression -> MSE: 0.000231, MAE: 0.009915, R²: -0.0030
  Directional -> Accuracy: 0.4651, MCC: -0.0716, F1: 0.4390

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.24973 | val 0.52174
  Epoch 016 - train 0.20333 | val 0.65685
  Regression -> MSE: 0.000137, MAE: 0.008229, R²: -0.0150
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.25290 | val 0.52167
  Epoch 016 - train 0.19441 | val 0.66012
  Regression -> MSE: 0.000192, MAE: 0.010439, R²: -0.0191
  Directional -> Accuracy: 0.5600, MCC: 0.0902, F1: 0.6857

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.24499 | val 0.47765
  Epoch 017 - train 0.22294 | val 0.54884
  Regression -> MSE: 0.000268, MAE: 0.010680, R²: -0.0240
  Directional -> Accuracy: 0.5342, MCC: 0.1345, F1: 0.4516

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.21053 | val 0.44445
  Epoch 016 - train 0.12817 | val 0.69577
  Regression -> MSE: 0.000164, MAE: 0.010277, R²: 0.0147
  Directional -> Accuracy: 0.5526, MCC: 0.1443, F1: 0.3200

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.21653 | val 0.43818
  Epoch 020 - train 0.15511 | val 0.58627
  Regression -> MSE: 0.000184, MAE: 0.010463, R²: -0.0217
  Directional -> Accuracy: 0.4773, MCC: -0.0279, F1: 0.5660

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.24846 | val 0.43930
  Epoch 016 - train 0.23124 | val 0.44970
  Regression -> MSE: 0.000344, MAE: 0.011978, R²: -0.0054
  Directional -> Accuracy: 0.3731, MCC: -0.2259, F1: 0.1250

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.21594 | val 0.22815
  Epoch 016 - train 0.16279 | val 0.30069
  Regression -> MSE: 0.000120, MAE: 0.008317, R²: -0.1456
  Directional -> Accuracy: 0.4884, MCC: -0.0094, F1: 0.2143

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.27555 | val 0.85511
  Epoch 016 - train 0.21225 | val 0.92268
  Regression -> MSE: 0.000222, MAE: 0.011364, R²: -0.0155
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.24346 | val 0.84141
  Epoch 016 - train 0.20070 | val 1.08027
  Regression -> MSE: 0.000083, MAE: 0.007122, R²: -0.0741
  Directional -> Accuracy: 0.5532, MCC: 0.1965, F1: 0.5333

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.25294 | val 0.29051
  Epoch 020 - train 0.17807 | val 0.23989
  Regression -> MSE: 0.000766, MAE: 0.024054, R²: -1.4899
  Directional -> Accuracy: 0.3469, MCC: -0.1586, F1: 0.5000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.22661 | val 0.20576
  Epoch 016 - train 0.15583 | val 0.22018
  Regression -> MSE: 0.000255, MAE: 0.011395, R²: -0.0463
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.25829 | val 0.77992
  Epoch 018 - train 0.21195 | val 1.14716
  Regression -> MSE: 0.000080, MAE: 0.007009, R²: 0.0148
  Directional -> Accuracy: 0.5067, MCC: 0.0143, F1: 0.5195

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.27619 | val 0.50615
  Epoch 016 - train 0.21655 | val 0.56910
  Regression -> MSE: 0.000306, MAE: 0.014477, R²: 0.0015
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.24631 | val 0.47773
  Epoch 020 - train 0.17678 | val 0.48955
  Regression -> MSE: 0.000102, MAE: 0.007160, R²: -0.0358
  Directional -> Accuracy: 0.5909, MCC: 0.1283, F1: 0.7273

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.23762 | val 0.54321
  Epoch 016 - train 0.16061 | val 0.58180
  Regression -> MSE: 0.000180, MAE: 0.010458, R²: -0.0494
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.22608 | val 0.71596
  Epoch 016 - train 0.17986 | val 1.23033
  Regression -> MSE: 0.000226, MAE: 0.011786, R²: -0.0135
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.24070 | val 0.66539
  Epoch 018 - train 0.17989 | val 0.93934
  Regression -> MSE: 0.000094, MAE: 0.007789, R²: -0.0170
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.32769 | val 0.82234
  Epoch 016 - train 0.22256 | val 1.40695
  Regression -> MSE: 0.000162, MAE: 0.010199, R²: 0.0078
  Directional -> Accuracy: 0.5185, MCC: 0.0073, F1: 0.6750

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.24382 | val 0.56544
  Epoch 016 - train 0.22094 | val 0.69677
  Regression -> MSE: 0.000115, MAE: 0.008860, R²: 0.0089
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.25324 | val 1.42488

[I 2026-02-22 23:08:42,845] Trial 101 finished with value: -0.011685077558821344 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.0, 'batch_size': 64, 'learning_rate': 0.0066761805284928305, 'weight_decay': 1.3201602887688571e-06, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 0.890406644912954, 'early_stopping_min_delta': 0.008744190323066564}. Best is trial 90 with value: -0.011414558399902668.

  Epoch 016 - train 0.20689 | val 2.80616
  Regression -> MSE: 0.000238, MAE: 0.012380, R²: -0.0046
  Directional -> Accuracy: 0.5082, MCC: 0.0781, F1: 0.6341

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.37545 | val 0.57380
  Epoch 020 - train 0.37085 | val 0.60716
  Regression -> MSE: 0.000254, MAE: 0.012804, R²: -0.0260
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.39991 | val 0.44410
  Epoch 016 - train 0.40281 | val 0.50461
  Regression -> MSE: 0.000683, MAE: 0.019353, R²: 0.0019
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.38295 | val 0.75451
  Epoch 016 - train 0.38073 | val 0.80041
  Regression -> MSE: 0.000313, MAE: 0.014519, R²: -0.0076
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.30838 | val 0.35568
  Epoch 016 - train 0.30120 | val 0.35444
  Regression -> MSE: 0.000351, MAE: 0.014602, R²: -0.0057
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.38292 | val 0.40066
  Epoch 016 - train 0.38291 | val 0.41676
  Regression -> MSE: 0.000205, MAE: 0.010326, R²: -0.0071
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.35075 | val 0.81809
  Epoch 020 - train 0.34735 | val 0.82015
  Regression -> MSE: 0.000560, MAE: 0.018657, R²: -0.0087
  Directional -> Accuracy: 0.4894, MCC: 0.0000, F1: 0.6571

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.39926 | val 0.53217
  Epoch 016 - train 0.39425 | val 0.53421
  Regression -> MSE: 0.000247, MAE: 0.012118, R²: -0.0068
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.36084 | val 0.51452
  Epoch 016 - train 0.36141 | val 0.53353
  Regression -> MSE: 0.000615, MAE: 0.019585, R²: -0.0302
  Directional -> Accuracy: 0.4545, MCC: -0.0094, F1: 0.5200

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.36038 | val 0.48263
  Epoch 016 - train 0.35014 | val 0.51072
  Regression -> MSE: 0.000388, MAE: 0.015843, R²: -0.0124
  Directional -> Accuracy: 0.6122, MCC: 0.2178, F1: 0.3448

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.37147 | val 0.52647
  Epoch 016 - train 0.35897 | val 0.51957
  Regression -> MSE: 0.000243, MAE: 0.011901, R²: -0.0077
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.33388 | val 0.59927
  Epoch 016 - train 0.32991 | val 0.61582
  Regression -> MSE: 0.000312, MAE: 0.013621, R²: -0.0020
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.40060 | val 0.49093
  Epoch 016 - train 0.39924 | val 0.53067
  Regression -> MSE: 0.000692, MAE: 0.019877, R²: -0.0214
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.38705 | val 0.37707
  Epoch 016 - train 0.38569 | val 0.38571
  Regression -> MSE: 0.000139, MAE: 0.009264, R²: -0.0050
  Directional -> Accuracy: 0.4419, MCC: -0.0259, F1: 0.6000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.34084 | val 0.53373
  Epoch 016 - train 0.33934 | val 0.54761
  Regression -> MSE: 0.000229, MAE: 0.010851, R²: -0.0200
  Directional -> Accuracy: 0.4918, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.37714 | val 0.98094
  Epoch 016 - train 0.37262 | val 1.05757
  Regression -> MSE: 0.000364, MAE: 0.016244, R²: -0.0057
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.39457 | val 0.41323
  Epoch 016 - train 0.38876 | val 0.41591
  Regression -> MSE: 0.000109, MAE: 0.008133, R²: -0.0127
  Directional -> Accuracy: 0.4571, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.37947 | val 0.74573
  Epoch 016 - train 0.36749 | val 0.79994
  Regression -> MSE: 0.000156, MAE: 0.009610, R²: -0.0025
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.37462 | val 0.45196
  Epoch 016 - train 0.37108 | val 0.55460
  Regression -> MSE: 0.000282, MAE: 0.013539, R²: -0.0360
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.34804 | val 0.57293
  Epoch 016 - train 0.34059 | val 0.58790
  Regression -> MSE: 0.000178, MAE: 0.009526, R²: -0.1900
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.38938 | val 0.62875
  Epoch 016 - train 0.38365 | val 0.63761
  Regression -> MSE: 0.000246, MAE: 0.011214, R²: -0.0890
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.38150 | val 0.51496
  Epoch 016 - train 0.37903 | val 0.52060
  Regression -> MSE: 0.000145, MAE: 0.008436, R²: -0.0120
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.35718 | val 0.44468
  Epoch 016 - train 0.35227 | val 0.44811
  Regression -> MSE: 0.000180, MAE: 0.010309, R²: -0.0923
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.42125 | val 0.48881
  Epoch 016 - train 0.41235 | val 0.50955
  Regression -> MSE: 0.000087, MAE: 0.007133, R²: -0.0173
  Directional -> Accuracy: 0.5690, MCC: 0.0263, F1: 0.7191

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.41783 | val 0.51244
  Epoch 016 - train 0.40999 | val 0.50860
  Regression -> MSE: 0.000218, MAE: 0.011620, R²: -0.0280
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.33347 | val 0.31731
  Epoch 020 - train 0.33399 | val 0.31037
  Regression -> MSE: 0.000114, MAE: 0.008820, R²: -0.2389
  Directional -> Accuracy: 0.4643, MCC: 0.0541, F1: 0.1176

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.40639 | val 0.27272
  Epoch 016 - train 0.39540 | val 0.27271
  Regression -> MSE: 0.000102, MAE: 0.008669, R²: 0.0072
  Directional -> Accuracy: 0.5870, MCC: 0.2359, F1: 0.6275

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.39456 | val 0.36999
  Epoch 016 - train 0.39391 | val 0.37319
  Regression -> MSE: 0.000231, MAE: 0.012488, R²: 0.0016
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.36584 | val 0.46886
  Epoch 016 - train 0.35718 | val 0.47868
  Regression -> MSE: 0.000177, MAE: 0.007893, R²: -0.0617
  Directional -> Accuracy: 0.5614, MCC: 0.0773, F1: 0.6575

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.39699 | val 0.27238
  Epoch 016 - train 0.39197 | val 0.27198
  Regression -> MSE: 0.000239, MAE: 0.011877, R²: -0.0111
  Directional -> Accuracy: 0.5366, MCC: 0.0166, F1: 0.6885

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.37407 | val 0.75248
  Epoch 016 - train 0.36714 | val 0.78998
  Regression -> MSE: 0.000234, MAE: 0.010060, R²: -0.0154
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.41078 | val 0.48588
  Epoch 016 - train 0.40254 | val 0.49330
  Regression -> MSE: 0.000137, MAE: 0.008236, R²: -0.0128
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.37367 | val 0.50759
  Epoch 020 - train 0.36789 | val 0.50575
  Regression -> MSE: 0.000201, MAE: 0.010574, R²: -0.0698
  Directional -> Accuracy: 0.5600, MCC: 0.1542, F1: 0.5000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.32259 | val 0.46908
  Epoch 016 - train 0.31283 | val 0.47007
  Regression -> MSE: 0.000274, MAE: 0.010712, R²: -0.0452
  Directional -> Accuracy: 0.4384, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.35807 | val 0.32759
  Epoch 016 - train 0.36090 | val 0.32674
  Regression -> MSE: 0.000167, MAE: 0.010347, R²: -0.0029
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.33038 | val 0.40188
  Epoch 016 - train 0.32589 | val 0.39753
  Regression -> MSE: 0.000182, MAE: 0.010397, R²: -0.0125
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.34806 | val 0.37868
  Epoch 016 - train 0.34605 | val 0.39442
  Regression -> MSE: 0.000347, MAE: 0.012362, R²: -0.0122
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.39109 | val 0.21725
  Epoch 016 - train 0.39418 | val 0.21793
  Regression -> MSE: 0.000124, MAE: 0.008407, R²: -0.1761
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.38066 | val 0.60888
  Epoch 016 - train 0.37483 | val 0.63533
  Regression -> MSE: 0.000222, MAE: 0.011364, R²: -0.0149
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.37490 | val 0.76189
  Epoch 016 - train 0.36219 | val 0.76685
  Regression -> MSE: 0.000085, MAE: 0.007222, R²: -0.0980
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.39297 | val 0.30919
  Epoch 016 - train 0.38962 | val 0.31865
  Regression -> MSE: 0.000342, MAE: 0.015476, R²: -0.1105
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.40225 | val 0.17700
  Epoch 016 - train 0.39878 | val 0.17582
  Regression -> MSE: 0.000250, MAE: 0.011511, R²: -0.0250
  Directional -> Accuracy: 0.5526, MCC: 0.1733, F1: 0.7018

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.35066 | val 0.46508
  Epoch 020 - train 0.34642 | val 0.45858
  Regression -> MSE: 0.000082, MAE: 0.007221, R²: -0.0165
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.39148 | val 0.51838
  Epoch 020 - train 0.38237 | val 0.49227
  Regression -> MSE: 0.000321, MAE: 0.014687, R²: -0.0465
  Directional -> Accuracy: 0.4468, MCC: -0.1169, F1: 0.5185

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.34352 | val 0.45284
  Epoch 016 - train 0.34499 | val 0.45685
  Regression -> MSE: 0.000100, MAE: 0.007110, R²: -0.0172
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.40122 | val 0.50168
  Epoch 020 - train 0.38578 | val 0.48844
  Regression -> MSE: 0.000175, MAE: 0.009401, R²: -0.0175
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.35978 | val 0.45784
  Epoch 016 - train 0.35624 | val 0.47707
  Regression -> MSE: 0.000229, MAE: 0.011920, R²: -0.0275
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.36658 | val 0.42734
  Epoch 016 - train 0.35776 | val 0.42875
  Regression -> MSE: 0.000092, MAE: 0.007636, R²: 0.0011
  Directional -> Accuracy: 0.5263, MCC: 0.0329, F1: 0.3721

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.40616 | val 0.72062
  Epoch 016 - train 0.39790 | val 0.79470
  Regression -> MSE: 0.000165, MAE: 0.010296, R²: -0.0059
  Directional -> Accuracy: 0.4815, MCC: -0.0447, F1: 0.5333

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.36147 | val 0.48852
  Epoch 016 - train 0.35843 | val 0.48795
  Regression -> MSE: 0.000122, MAE: 0.008967, R²: -0.0493
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...

[I 2026-02-22 23:09:02,546] Trial 102 finished with value: -0.011501060064353403 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.1, 'batch_size': 64, 'learning_rate': 1.897809294136919e-05, 'weight_decay': 2.6938537561226738e-06, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 0.8688994912241952, 'early_stopping_min_delta': 0.008374340734200458}. Best is trial 90 with value: -0.011414558399902668.

  Epoch 010 - train 0.37380 | val 0.62535
  Epoch 016 - train 0.37838 | val 0.65107
  Regression -> MSE: 0.000239, MAE: 0.012314, R²: -0.0097
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.42710 | val 0.76516
  Epoch 020 - train 0.40875 | val 0.79358
  Regression -> MSE: 0.000258, MAE: 0.012834, R²: -0.0407
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.42364 | val 0.43500
  Epoch 020 - train 0.40945 | val 0.42662
  Regression -> MSE: 0.000721, MAE: 0.019547, R²: -0.0528
  Directional -> Accuracy: 0.5000, MCC: 0.2317, F1: 0.2069

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.45243 | val 0.96046
  Epoch 016 - train 0.44443 | val 0.97075
  Regression -> MSE: 0.000311, MAE: 0.014392, R²: -0.0010
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.35630 | val 0.38506
  Epoch 020 - train 0.34474 | val 0.39339
  Regression -> MSE: 0.000364, MAE: 0.014690, R²: -0.0423
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.44046 | val 0.51581
  Epoch 016 - train 0.42564 | val 0.50739
  Regression -> MSE: 0.000208, MAE: 0.010371, R²: -0.0190
  Directional -> Accuracy: 0.4118, MCC: -0.1947, F1: 0.1176

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.42017 | val 1.12723
  Epoch 016 - train 0.40828 | val 1.12605
  Regression -> MSE: 0.000578, MAE: 0.018558, R²: -0.0416
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.44642 | val 0.63642
  Epoch 020 - train 0.43300 | val 0.63752
  Regression -> MSE: 0.000245, MAE: 0.012314, R²: 0.0016
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.43304 | val 0.69170
  Epoch 016 - train 0.42238 | val 0.69564
  Regression -> MSE: 0.000632, MAE: 0.019878, R²: -0.0572
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.42701 | val 0.57151
  Epoch 016 - train 0.41802 | val 0.58244
  Regression -> MSE: 0.000404, MAE: 0.016112, R²: -0.0523
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.43594 | val 0.68563
  Epoch 016 - train 0.42926 | val 0.70577
  Regression -> MSE: 0.000241, MAE: 0.011723, R²: 0.0014
  Directional -> Accuracy: 0.4286, MCC: -0.0355, F1: 0.5833

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.38079 | val 0.82202
  Epoch 016 - train 0.37500 | val 1.10570
  Regression -> MSE: 0.000323, MAE: 0.013624, R²: -0.0393
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.50211 | val 0.72676
  Epoch 016 - train 0.48427 | val 0.86650
  Regression -> MSE: 0.000694, MAE: 0.019685, R²: -0.0252
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.43111 | val 0.56799
  Epoch 016 - train 0.41951 | val 0.68168
  Regression -> MSE: 0.000139, MAE: 0.009039, R²: -0.0087
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.38407 | val 0.68295
  Epoch 020 - train 0.36675 | val 0.75877
  Regression -> MSE: 0.000221, MAE: 0.010573, R²: 0.0184
  Directional -> Accuracy: 0.5410, MCC: 0.0843, F1: 0.6316

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.43331 | val 1.34270
  Epoch 016 - train 0.42416 | val 1.38825
  Regression -> MSE: 0.000362, MAE: 0.016086, R²: 0.0011
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.45619 | val 0.50429
  Epoch 016 - train 0.44446 | val 0.50034
  Regression -> MSE: 0.000110, MAE: 0.008130, R²: -0.0158
  Directional -> Accuracy: 0.4571, MCC: -0.0212, F1: 0.0952

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.42463 | val 1.01021
  Epoch 016 - train 0.41287 | val 1.05506
  Regression -> MSE: 0.000162, MAE: 0.010218, R²: -0.0413
  Directional -> Accuracy: 0.3729, MCC: -0.0884, F1: 0.1395

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.43575 | val 0.47519
  Epoch 016 - train 0.42683 | val 0.54984
  Regression -> MSE: 0.000273, MAE: 0.013113, R²: -0.0041
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.35903 | val 0.67477
  Epoch 020 - train 0.34604 | val 0.67312
  Regression -> MSE: 0.000178, MAE: 0.009481, R²: -0.1890
  Directional -> Accuracy: 0.3846, MCC: -0.1597, F1: 0.1667

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.42739 | val 0.85606
  Epoch 020 - train 0.40766 | val 0.85118
  Regression -> MSE: 0.000251, MAE: 0.011425, R²: -0.1079
  Directional -> Accuracy: 0.4667, MCC: -0.0379, F1: 0.3939

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.42349 | val 0.66013
  Epoch 020 - train 0.40657 | val 0.69061
  Regression -> MSE: 0.000149, MAE: 0.008715, R²: -0.0405
  Directional -> Accuracy: 0.5417, MCC: 0.2914, F1: 0.4500

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.40689 | val 0.55536
  Epoch 016 - train 0.39921 | val 0.58479
  Regression -> MSE: 0.000170, MAE: 0.010312, R²: -0.0264
  Directional -> Accuracy: 0.4697, MCC: -0.1270, F1: 0.6316

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.44016 | val 0.62703
  Epoch 016 - train 0.43009 | val 0.63500
  Regression -> MSE: 0.000090, MAE: 0.007274, R²: -0.0504
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.43490 | val 0.67596
  Epoch 016 - train 0.42789 | val 0.73408
  Regression -> MSE: 0.000215, MAE: 0.011022, R²: -0.0132
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.37522 | val 0.34882
  Epoch 020 - train 0.36104 | val 0.32962
  Regression -> MSE: 0.000100, MAE: 0.008221, R²: -0.0914
  Directional -> Accuracy: 0.4821, MCC: 0.0435, F1: 0.2927

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.47420 | val 0.33109
  Epoch 016 - train 0.46528 | val 0.33305
  Regression -> MSE: 0.000104, MAE: 0.008751, R²: -0.0077
  Directional -> Accuracy: 0.3913, MCC: -0.1953, F1: 0.4167

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.45382 | val 0.44727
  Epoch 016 - train 0.44850 | val 0.44680
  Regression -> MSE: 0.000232, MAE: 0.012507, R²: -0.0004
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.42533 | val 0.58776
  Epoch 016 - train 0.41399 | val 0.58497
  Regression -> MSE: 0.000179, MAE: 0.008024, R²: -0.0785
  Directional -> Accuracy: 0.3684, MCC: -0.2434, F1: 0.3333

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.45024 | val 0.33963
  Epoch 016 - train 0.44157 | val 0.37857
  Regression -> MSE: 0.000238, MAE: 0.011916, R²: -0.0083
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.43679 | val 0.97054
  Epoch 016 - train 0.42629 | val 0.98322
  Regression -> MSE: 0.000232, MAE: 0.009980, R²: -0.0088
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.45212 | val 0.64747
  Epoch 020 - train 0.43001 | val 0.65861
  Regression -> MSE: 0.000144, MAE: 0.008411, R²: -0.0649
  Directional -> Accuracy: 0.5349, MCC: 0.1359, F1: 0.3750

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.44472 | val 0.67299
  Epoch 016 - train 0.43101 | val 0.68293
  Regression -> MSE: 0.000190, MAE: 0.010361, R²: -0.0081
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.37148 | val 0.59459
  Epoch 020 - train 0.35836 | val 0.60391
  Regression -> MSE: 0.000286, MAE: 0.011028, R²: -0.0921
  Directional -> Accuracy: 0.4384, MCC: -0.0299, F1: 0.0889

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.49924 | val 0.40432
  Epoch 016 - train 0.48021 | val 0.40357
  Regression -> MSE: 0.000173, MAE: 0.010397, R²: -0.0351
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.37817 | val 0.51956
  Epoch 016 - train 0.37062 | val 0.54101
  Regression -> MSE: 0.000180, MAE: 0.010300, R²: -0.0012
  Directional -> Accuracy: 0.5000, MCC: 0.1457, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.42498 | val 0.39732
  Epoch 020 - train 0.40765 | val 0.37947
  Regression -> MSE: 0.000335, MAE: 0.012413, R²: 0.0227
  Directional -> Accuracy: 0.5672, MCC: 0.1013, F1: 0.6420

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.50548 | val 0.24051
  Epoch 016 - train 0.48171 | val 0.24270
  Regression -> MSE: 0.000109, MAE: 0.008335, R²: -0.0394
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.45664 | val 0.85993
  Epoch 016 - train 0.43998 | val 0.84388
  Regression -> MSE: 0.000228, MAE: 0.011565, R²: -0.0452
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.45403 | val 1.11305
  Epoch 016 - train 0.43654 | val 1.15323
  Regression -> MSE: 0.000079, MAE: 0.006925, R²: -0.0215
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.43641 | val 0.35596
  Epoch 016 - train 0.42492 | val 0.35620
  Regression -> MSE: 0.000341, MAE: 0.015398, R²: -0.1097
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.45440 | val 0.20732
  Epoch 016 - train 0.43614 | val 0.22045
  Regression -> MSE: 0.000249, MAE: 0.011426, R²: -0.0205
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.41181 | val 0.59185
  Epoch 016 - train 0.39841 | val 0.60172
  Regression -> MSE: 0.000082, MAE: 0.007057, R²: -0.0189
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.49571 | val 0.70448
  Epoch 016 - train 0.47851 | val 0.73154
  Regression -> MSE: 0.000313, MAE: 0.014497, R²: -0.0212
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.43072 | val 0.54858
  Epoch 016 - train 0.42054 | val 0.55605
  Regression -> MSE: 0.000099, MAE: 0.007161, R²: -0.0105
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.46977 | val 0.71429
  Epoch 016 - train 0.45787 | val 0.71890
  Regression -> MSE: 0.000172, MAE: 0.009788, R²: -0.0018
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.38902 | val 0.59185
  Epoch 016 - train 0.37975 | val 0.60654
  Regression -> MSE: 0.000224, MAE: 0.011807, R²: -0.0054
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.41718 | val 0.57064
  Epoch 016 - train 0.41002 | val 0.58529
  Regression -> MSE: 0.000093, MAE: 0.007695, R²: -0.0114
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.45584 | val 0.93082
  Epoch 020 - train 0.43650 | val 0.91543
  Regression -> MSE: 0.000171, MAE: 0.010475, R²: -0.0463
  Directional -> Accuracy: 0.5556, MCC: 0.1310, F1: 0.6842

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.42310 | val 0.69266
  Epoch 016 - train 0.41478 | val 0.72773
  Regression -> MSE: 0.000120, MAE: 0.008996, R²: -0.0377
  Directional -> Accuracy: 0.5357, MCC: 0.1303, F1: 0.3158

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.45270 | val 0.84009

[I 2026-02-22 23:09:39,361] Trial 103 finished with value: -0.01149793605915021 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.0, 'batch_size': 64, 'learning_rate': 5.436546927532285e-05, 'weight_decay': 2.0336606778647043e-06, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 1.4894545163107966, 'early_stopping_min_delta': 0.00596074337894219}. Best is trial 90 with value: -0.011414558399902668.

  Epoch 016 - train 0.44442 | val 0.87973
  Regression -> MSE: 0.000238, MAE: 0.012344, R²: -0.0050
  Directional -> Accuracy: 0.5246, MCC: 0.0130, F1: 0.1212

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 12
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.34938 | val 0.54979
  Epoch 016 - train 0.33896 | val 0.56015
  Regression -> MSE: 0.000258, MAE: 0.012989, R²: -0.0518
  Directional -> Accuracy: 0.4487, MCC: 0.0000, F1: 0.6195

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 88). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.37230 | val 0.35393
  Epoch 016 - train 0.36538 | val 0.36916
  Regression -> MSE: 0.000703, MAE: 0.019835, R²: -0.0173
  Directional -> Accuracy: 0.5319, MCC: 0.0273, F1: 0.6207

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 88). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.37734 | val 0.69984
  Epoch 016 - train 0.37153 | val 0.70684
  Regression -> MSE: 0.000346, MAE: 0.015020, R²: -0.0023
  Directional -> Accuracy: 0.5417, MCC: 0.0000, F1: 0.7027

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.30283 | val 0.32095
  Epoch 016 - train 0.29837 | val 0.32925
  Regression -> MSE: 0.000347, MAE: 0.014451, R²: -0.0051
  Directional -> Accuracy: 0.5395, MCC: 0.0000, F1: 0.7009

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.37175 | val 0.36870
  Epoch 020 - train 0.35205 | val 0.35102
  Regression -> MSE: 0.000186, MAE: 0.009510, R²: 0.0719
  Directional -> Accuracy: 0.6923, MCC: 0.4501, F1: 0.6364

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.36289 | val 0.80774
  Epoch 020 - train 0.34822 | val 0.87444
  Regression -> MSE: 0.000577, MAE: 0.018429, R²: -0.0083
  Directional -> Accuracy: 0.4898, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.38472 | val 0.50324
  Epoch 020 - train 0.37532 | val 0.51077
  Regression -> MSE: 0.000250, MAE: 0.012325, R²: -0.0168
  Directional -> Accuracy: 0.4000, MCC: -0.0733, F1: 0.5333

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 88). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 88). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.35768 | val 0.68382
  Epoch 016 - train 0.34624 | val 0.75264
  Regression -> MSE: 0.000661, MAE: 0.020210, R²: -0.1301
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.36062 | val 0.63073
  Epoch 020 - train 0.35006 | val 0.61403
  Regression -> MSE: 0.000346, MAE: 0.015661, R²: -0.0243
  Directional -> Accuracy: 0.3810, MCC: 0.0000, F1: 0.5517

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 88). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 88). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.36794 | val 0.53141
  Epoch 016 - train 0.36164 | val 0.55385
  Regression -> MSE: 0.000240, MAE: 0.011595, R²: -0.0079
  Directional -> Accuracy: 0.4366, MCC: -0.1225, F1: 0.4118

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.35105 | val 0.58940
  Epoch 016 - train 0.34049 | val 0.62910
  Regression -> MSE: 0.000325, MAE: 0.013573, R²: -0.0612
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.37686 | val 0.48501
  Epoch 016 - train 0.37143 | val 0.50898
  Regression -> MSE: 0.000671, MAE: 0.019392, R²: -0.0020
  Directional -> Accuracy: 0.4915, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.41176 | val 0.44230
  Epoch 016 - train 0.39451 | val 0.52408
  Regression -> MSE: 0.000157, MAE: 0.009421, R²: -0.0503
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 88). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.33018 | val 0.54059
  Epoch 016 - train 0.32130 | val 0.55023
  Regression -> MSE: 0.000226, MAE: 0.010782, R²: -0.0068
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.36947 | val 0.97082
  Epoch 016 - train 0.36024 | val 0.97394
  Regression -> MSE: 0.000376, MAE: 0.016569, R²: -0.0015
  Directional -> Accuracy: 0.4717, MCC: 0.0000, F1: 0.6410

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.39425 | val 0.40296
  Epoch 020 - train 0.37649 | val 0.40573
  Regression -> MSE: 0.000105, MAE: 0.007706, R²: 0.0163
  Directional -> Accuracy: 0.5634, MCC: 0.1397, F1: 0.7048

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.34454 | val 0.76178
  Epoch 016 - train 0.34000 | val 0.78976
  Regression -> MSE: 0.000158, MAE: 0.009825, R²: 0.0126
  Directional -> Accuracy: 0.6167, MCC: 0.0000, F1: 0.7629

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.36352 | val 0.56049
  Epoch 016 - train 0.35583 | val 0.82967
  Regression -> MSE: 0.000291, MAE: 0.013941, R²: -0.0824
  Directional -> Accuracy: 0.3896, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.32213 | val 0.56851
  Epoch 016 - train 0.31549 | val 0.58234
  Regression -> MSE: 0.000168, MAE: 0.009082, R²: -0.1370
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 88). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.37750 | val 0.63662
  Epoch 020 - train 0.35787 | val 0.63254
  Regression -> MSE: 0.000249, MAE: 0.011339, R²: -0.0996
  Directional -> Accuracy: 0.5395, MCC: 0.1667, F1: 0.3636

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.38171 | val 0.48418
  Epoch 016 - train 0.37404 | val 0.47886
  Regression -> MSE: 0.000154, MAE: 0.008863, R²: -0.0364
  Directional -> Accuracy: 0.6327, MCC: 0.0000, F1: 0.7750

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 88). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 88). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 88). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.34286 | val 0.49007
  Epoch 016 - train 0.33500 | val 0.49889
  Regression -> MSE: 0.000179, MAE: 0.010562, R²: -0.0104
  Directional -> Accuracy: 0.5075, MCC: 0.0000, F1: 0.6733

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.40806 | val 0.48152
  Epoch 020 - train 0.38373 | val 0.47826
  Regression -> MSE: 0.000094, MAE: 0.007336, R²: -0.1226
  Directional -> Accuracy: 0.4915, MCC: 0.1131, F1: 0.3182

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.37451 | val 0.49578
  Epoch 016 - train 0.36834 | val 0.50428
  Regression -> MSE: 0.000225, MAE: 0.011262, R²: -0.0281
  Directional -> Accuracy: 0.5224, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.37170 | val 0.31176
  Epoch 016 - train 0.34715 | val 0.31020
  Regression -> MSE: 0.000092, MAE: 0.008117, R²: -0.0015
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.40065 | val 0.19897
  Epoch 016 - train 0.39412 | val 0.20550
  Regression -> MSE: 0.000131, MAE: 0.009451, R²: -0.0410
  Directional -> Accuracy: 0.4167, MCC: 0.0000, F1: 0.5882

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.38013 | val 0.35441
  Epoch 016 - train 0.37436 | val 0.37560
  Regression -> MSE: 0.000255, MAE: 0.013252, R²: -0.0704
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.37557 | val 0.47957
  Epoch 020 - train 0.36365 | val 0.47023
  Regression -> MSE: 0.000189, MAE: 0.008078, R²: -0.1506
  Directional -> Accuracy: 0.5345, MCC: 0.2769, F1: 0.2703

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.39438 | val 0.23799
  Epoch 016 - train 0.38631 | val 0.23639
  Regression -> MSE: 0.000235, MAE: 0.011955, R²: -0.0044
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.35932 | val 0.63638
  Epoch 016 - train 0.35499 | val 0.66780
  Regression -> MSE: 0.000250, MAE: 0.010414, R²: 0.0023
  Directional -> Accuracy: 0.4889, MCC: -0.0832, F1: 0.6462

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.39664 | val 0.54790
  Epoch 016 - train 0.38812 | val 0.55014
  Regression -> MSE: 0.000133, MAE: 0.008161, R²: 0.0039
  Directional -> Accuracy: 0.5333, MCC: 0.0000, F1: 0.6957

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.38424 | val 0.52195
  Epoch 020 - train 0.36781 | val 0.51071
  Regression -> MSE: 0.000195, MAE: 0.010871, R²: -0.0346
  Directional -> Accuracy: 0.4314, MCC: -0.1667, F1: 0.5246

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.33528 | val 0.50987
  Epoch 016 - train 0.32371 | val 0.51263
  Regression -> MSE: 0.000267, MAE: 0.010543, R²: -0.0324
  Directional -> Accuracy: 0.5405, MCC: -0.0880, F1: 0.6964

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 88). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.35866 | val 0.35753
  Epoch 020 - train 0.34452 | val 0.33588
  Regression -> MSE: 0.000164, MAE: 0.010289, R²: -0.0066
  Directional -> Accuracy: 0.4872, MCC: 0.0000, F1: 0.6552

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.34135 | val 0.43425
  Epoch 016 - train 0.33093 | val 0.47465
  Regression -> MSE: 0.000184, MAE: 0.010485, R²: -0.0049
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.6364

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.33610 | val 0.32789
  Epoch 020 - train 0.32797 | val 0.33030
  Regression -> MSE: 0.000362, MAE: 0.012972, R²: -0.0388
  Directional -> Accuracy: 0.4265, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.45530 | val 0.24383
  Epoch 016 - train 0.44314 | val 0.25244
  Regression -> MSE: 0.000107, MAE: 0.008235, R²: -0.0341
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.37306 | val 0.57115
  Epoch 016 - train 0.36440 | val 0.58125
  Regression -> MSE: 0.000216, MAE: 0.011194, R²: -0.0061
  Directional -> Accuracy: 0.5000, MCC: 0.0900, F1: 0.6329

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.38296 | val 0.76401
  Epoch 016 - train 0.37267 | val 0.76932
  Regression -> MSE: 0.000094, MAE: 0.007588, R²: -0.1780
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 88). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 88). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 88). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 88). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.36066 | val 0.32876
  Epoch 020 - train 0.34833 | val 0.31070
  Regression -> MSE: 0.000451, MAE: 0.018662, R²: -0.3757
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 88). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.38899 | val 0.20424
  Epoch 016 - train 0.38145 | val 0.20410
  Regression -> MSE: 0.000241, MAE: 0.011295, R²: -0.0146
  Directional -> Accuracy: 0.4359, MCC: -0.1448, F1: 0.5000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 88). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 88). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.34227 | val 0.48782
  Epoch 016 - train 0.33575 | val 0.49324
  Regression -> MSE: 0.000080, MAE: 0.007047, R²: 0.0049
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 88). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 88). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 88). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.40794 | val 0.49900
  Epoch 016 - train 0.39686 | val 0.53133
  Regression -> MSE: 0.000370, MAE: 0.015349, R²: -0.0291
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.42076 | val 0.45382
  Epoch 016 - train 0.38856 | val 0.45059
  Regression -> MSE: 0.000097, MAE: 0.007310, R²: -0.0074
  Directional -> Accuracy: 0.4222, MCC: -0.1195, F1: 0.0714

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.39572 | val 0.58045
  Epoch 016 - train 0.38649 | val 0.64527
  Regression -> MSE: 0.000181, MAE: 0.009890, R²: -0.0030
  Directional -> Accuracy: 0.6341, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.35947 | val 0.48252
  Epoch 016 - train 0.34723 | val 0.50078
  Regression -> MSE: 0.000222, MAE: 0.011772, R²: -0.0093
  Directional -> Accuracy: 0.5439, MCC: 0.0000, F1: 0.7045

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.37245 | val 0.48459
  Epoch 016 - train 0.36409 | val 0.52609
  Regression -> MSE: 0.000092, MAE: 0.007672, R²: -0.0122
  Directional -> Accuracy: 0.4828, MCC: 0.0000, F1: 0.6512

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.41519 | val 0.79294
  Epoch 016 - train 0.40231 | val 0.86443
  Regression -> MSE: 0.000171, MAE: 0.010278, R²: -0.0608
  Directional -> Accuracy: 0.4727, MCC: 0.0000, F1: 0.0000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.36379 | val 0.54137
  Epoch 016 - train 0.35584 | val 0.59878
  Regression -> MSE: 0.000115, MAE: 0.008814, R²: -0.0046
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...

[I 2026-02-22 23:09:53,981] Trial 104 finished with value: -0.011632359048576171 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 12, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.1, 'dropout': 0.0, 'batch_size': 64, 'learning_rate': 7.112135030756763e-05, 'weight_decay': 8.952325567770343e-07, 'lr_patience': 7, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 0.9431948071480228, 'early_stopping_min_delta': 0.005694236349682475}. Best is trial 90 with value: -0.011414558399902668.

  Epoch 010 - train 0.40185 | val 0.64090
  Epoch 016 - train 0.38687 | val 0.71885
  Regression -> MSE: 0.000241, MAE: 0.012245, R²: -0.0318
  Directional -> Accuracy: 0.5161, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: regression
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.36002 | val 0.57339
  Epoch 016 - train 0.35662 | val 0.59213
  Regression -> MSE: 0.000246, MAE: 0.012507, R²: -0.0223
  Directional -> Accuracy: 0.4342, MCC: -0.0797, F1: 0.5743

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.34106 | val 0.35782
  Epoch 016 - train 0.33870 | val 0.37459
  Regression -> MSE: 0.000714, MAE: 0.019755, R²: -0.0229
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.34029 | val 0.62936
  Epoch 020 - train 0.33844 | val 0.62595
  Regression -> MSE: 0.000327, MAE: 0.014659, R²: -0.0394
  Directional -> Accuracy: 0.4348, MCC: -0.2227, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.29039 | val 0.32836
  Epoch 016 - train 0.28743 | val 0.32466
  Regression -> MSE: 0.000356, MAE: 0.014664, R²: -0.0070
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.34274 | val 0.36447
  Epoch 016 - train 0.33986 | val 0.37571
  Regression -> MSE: 0.000208, MAE: 0.010322, R²: -0.0064
  Directional -> Accuracy: 0.3800, MCC: -0.3459, F1: 0.5373

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.32557 | val 0.68589
  Epoch 016 - train 0.32373 | val 0.69252
  Regression -> MSE: 0.000557, MAE: 0.018260, R²: 0.0154
  Directional -> Accuracy: 0.6522, MCC: 0.3218, F1: 0.6800

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.34317 | val 0.47458
  Epoch 016 - train 0.34197 | val 0.47631
  Regression -> MSE: 0.000249, MAE: 0.011912, R²: -0.0032
  Directional -> Accuracy: 0.5441, MCC: -0.1465, F1: 0.0606

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.35944 | val 0.41544
  Epoch 016 - train 0.35637 | val 0.44111
  Regression -> MSE: 0.000676, MAE: 0.020440, R²: -0.1056
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.35262 | val 0.46496
  Epoch 016 - train 0.35034 | val 0.47798
  Regression -> MSE: 0.000374, MAE: 0.015696, R²: -0.0034
  Directional -> Accuracy: 0.4375, MCC: 0.0000, F1: 0.6087

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.35540 | val 0.49515
  Epoch 016 - train 0.35207 | val 0.49577
  Regression -> MSE: 0.000246, MAE: 0.012128, R²: -0.0035
  Directional -> Accuracy: 0.4203, MCC: 0.0000, F1: 0.5918

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.32762 | val 0.61168
  Epoch 016 - train 0.32484 | val 0.62065
  Regression -> MSE: 0.000324, MAE: 0.013740, R²: -0.0372
  Directional -> Accuracy: 0.5102, MCC: 0.0355, F1: 0.5200

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.35734 | val 0.42824
  Epoch 016 - train 0.35504 | val 0.43732
  Regression -> MSE: 0.000686, MAE: 0.019673, R²: -0.0002
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.37078 | val 0.43124
  Epoch 016 - train 0.36722 | val 0.46788
  Regression -> MSE: 0.000154, MAE: 0.009841, R²: -0.1161
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.30896 | val 0.49430
  Epoch 016 - train 0.30739 | val 0.49371
  Regression -> MSE: 0.000231, MAE: 0.010856, R²: -0.0183
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.35192 | val 0.82706
  Epoch 020 - train 0.34472 | val 0.82614
  Regression -> MSE: 0.000514, MAE: 0.018894, R²: -0.4033
  Directional -> Accuracy: 0.4510, MCC: 0.0000, F1: 0.6216

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.37230 | val 0.42068
  Epoch 016 - train 0.37018 | val 0.41682
  Regression -> MSE: 0.000113, MAE: 0.008099, R²: -0.0430
  Directional -> Accuracy: 0.4783, MCC: -0.0490, F1: 0.5135

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.34854 | val 0.76633
  Epoch 016 - train 0.34516 | val 0.80770
  Regression -> MSE: 0.000160, MAE: 0.009613, R²: -0.0145
  Directional -> Accuracy: 0.6207, MCC: 0.0000, F1: 0.7660

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.34872 | val 0.55618
  Epoch 016 - train 0.34662 | val 0.60139
  Regression -> MSE: 0.000347, MAE: 0.015401, R²: -0.2669
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.36956 | val 0.60164
  Epoch 016 - train 0.36229 | val 0.60579
  Regression -> MSE: 0.000180, MAE: 0.010011, R²: -0.1881
  Directional -> Accuracy: 0.4844, MCC: -0.1933, F1: 0.6374

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.37465 | val 0.61852
  Epoch 016 - train 0.37149 | val 0.62828
  Regression -> MSE: 0.000232, MAE: 0.010913, R²: -0.0217
  Directional -> Accuracy: 0.5541, MCC: 0.0000, F1: 0.7130

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.37857 | val 0.50271
  Epoch 020 - train 0.37367 | val 0.49010
  Regression -> MSE: 0.000159, MAE: 0.008858, R²: -0.1072
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.30811 | val 0.47852
  Epoch 016 - train 0.30717 | val 0.48511
  Regression -> MSE: 0.000169, MAE: 0.010279, R²: -0.0203
  Directional -> Accuracy: 0.5231, MCC: 0.0462, F1: 0.6353

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.35314 | val 0.43203
  Epoch 016 - train 0.35067 | val 0.43447
  Regression -> MSE: 0.000086, MAE: 0.007210, R²: 0.0046
  Directional -> Accuracy: 0.5439, MCC: 0.0500, F1: 0.6286

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.34974 | val 0.50334
  Epoch 016 - train 0.34738 | val 0.53168
  Regression -> MSE: 0.000212, MAE: 0.011059, R²: -0.0066
  Directional -> Accuracy: 0.4769, MCC: -0.0428, F1: 0.4848

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.31551 | val 0.32807
  Epoch 020 - train 0.30897 | val 0.31756
  Regression -> MSE: 0.000101, MAE: 0.008425, R²: -0.1274
  Directional -> Accuracy: 0.5091, MCC: -0.0659, F1: 0.6494

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.34383 | val 0.29882
  Epoch 016 - train 0.34262 | val 0.31119
  Regression -> MSE: 0.000108, MAE: 0.008877, R²: -0.0839
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.37157 | val 0.32961
  Epoch 016 - train 0.36882 | val 0.33540
  Regression -> MSE: 0.000238, MAE: 0.012920, R²: -0.0060
  Directional -> Accuracy: 0.5238, MCC: -0.1936, F1: 0.6875

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.33085 | val 0.43291
  Epoch 016 - train 0.32935 | val 0.43971
  Regression -> MSE: 0.000185, MAE: 0.008036, R²: -0.0921
  Directional -> Accuracy: 0.5000, MCC: 0.2137, F1: 0.1765

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.35646 | val 0.31719
  Epoch 016 - train 0.35481 | val 0.33100
  Regression -> MSE: 0.000249, MAE: 0.012223, R²: -0.0273
  Directional -> Accuracy: 0.5500, MCC: 0.0000, F1: 0.7097

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.36276 | val 0.64347
  Epoch 016 - train 0.35942 | val 0.65015
  Regression -> MSE: 0.000236, MAE: 0.010048, R²: 0.0006
  Directional -> Accuracy: 0.5000, MCC: 0.0196, F1: 0.5714

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.37516 | val 0.45674
  Epoch 016 - train 0.37340 | val 0.48046
  Regression -> MSE: 0.000149, MAE: 0.008937, R²: -0.0847
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.33421 | val 0.48990
  Epoch 016 - train 0.33283 | val 0.48970
  Regression -> MSE: 0.000184, MAE: 0.010146, R²: -0.0071
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.29576 | val 0.46722
  Epoch 016 - train 0.29290 | val 0.46878
  Regression -> MSE: 0.000267, MAE: 0.010650, R²: -0.0042
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.31380 | val 0.41903
  Epoch 016 - train 0.31188 | val 0.43599
  Regression -> MSE: 0.000186, MAE: 0.010486, R²: -0.0159
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.33916 | val 0.35394
  Epoch 016 - train 0.33405 | val 0.35425
  Regression -> MSE: 0.000359, MAE: 0.012616, R²: -0.0322
  Directional -> Accuracy: 0.4242, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.39380 | val 0.22038
  Epoch 016 - train 0.39102 | val 0.22745
  Regression -> MSE: 0.000137, MAE: 0.008720, R²: -0.2917
  Directional -> Accuracy: 0.4762, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.33448 | val 0.53395
  Epoch 016 - train 0.33365 | val 0.53482
  Regression -> MSE: 0.000219, MAE: 0.011190, R²: 0.0039
  Directional -> Accuracy: 0.5714, MCC: 0.1316, F1: 0.2941

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.34248 | val 0.74837
  Epoch 016 - train 0.34063 | val 0.76575
  Regression -> MSE: 0.000075, MAE: 0.006740, R²: -0.0149
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.35342 | val 0.20926
  Epoch 016 - train 0.35130 | val 0.21053
  Regression -> MSE: 0.000310, MAE: 0.013658, R²: 0.0059
  Directional -> Accuracy: 0.6667, MCC: 0.1877, F1: 0.3333

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.33613 | val 0.49383
  Epoch 016 - train 0.33302 | val 0.49703
  Regression -> MSE: 0.000081, MAE: 0.006923, R²: -0.0333
  Directional -> Accuracy: 0.5135, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.36057 | val 0.47255
  Epoch 020 - train 0.35554 | val 0.45513
  Regression -> MSE: 0.000291, MAE: 0.014157, R²: 0.0334
  Directional -> Accuracy: 0.5111, MCC: 0.0103, F1: 0.6333

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.32828 | val 0.43223
  Epoch 020 - train 0.32595 | val 0.42819
  Regression -> MSE: 0.000103, MAE: 0.007168, R²: -0.0136
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.36759 | val 0.48400
  Epoch 016 - train 0.36554 | val 0.48625
  Regression -> MSE: 0.000175, MAE: 0.009824, R²: -0.0004
  Directional -> Accuracy: 0.4375, MCC: -0.0348, F1: 0.4706

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.33192 | val 0.46039
  Epoch 016 - train 0.32794 | val 0.47705
  Regression -> MSE: 0.000241, MAE: 0.012005, R²: -0.0672
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.35994 | val 0.44027
  Epoch 016 - train 0.35564 | val 0.44341
  Regression -> MSE: 0.000096, MAE: 0.007819, R²: -0.0200
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.37209 | val 0.60079
  Epoch 016 - train 0.36971 | val 0.60157
  Regression -> MSE: 0.000165, MAE: 0.010356, R²: 0.0089
  Directional -> Accuracy: 0.5094, MCC: 0.0000, F1: 0.6750

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.34058 | val 0.50617
  Epoch 016 - train 0.33694 | val 0.50506
  Regression -> MSE: 0.000117, MAE: 0.009020, R²: 0.0052
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...

[I 2026-02-22 23:10:13,765] Trial 105 finished with value: -0.011630183045329747 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.0, 'batch_size': 64, 'learning_rate': 1.452201859940409e-05, 'weight_decay': 3.0049703177004364e-06, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 0.7465426116431857, 'early_stopping_min_delta': 0.005239400948266867}. Best is trial 90 with value: -0.011414558399902668.

  Epoch 010 - train 0.35069 | val 0.57195
  Epoch 016 - train 0.34860 | val 0.57218
  Regression -> MSE: 0.000244, MAE: 0.012514, R²: -0.0166
  Directional -> Accuracy: 0.5000, MCC: -0.0080, F1: 0.4231

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.23164 | val 0.44506
  Epoch 016 - train 0.19742 | val 0.55918
  Regression -> MSE: 0.000249, MAE: 0.012505, R²: -0.0044
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.22665 | val 0.26639
  Epoch 017 - train 0.19510 | val 0.27635
  Regression -> MSE: 0.000674, MAE: 0.018947, R²: 0.0152
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.23518 | val 0.53325
  Epoch 016 - train 0.21972 | val 0.53701
  Regression -> MSE: 0.000320, MAE: 0.014595, R²: -0.0310
  Directional -> Accuracy: 0.4894, MCC: 0.1383, F1: 0.0769

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.19715 | val 0.64885
  Epoch 016 - train 0.17238 | val 1.02771
  Regression -> MSE: 0.000353, MAE: 0.014616, R²: -0.0114
  Directional -> Accuracy: 0.5600, MCC: 0.1298, F1: 0.5600

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.21474 | val 0.33681
  Epoch 016 - train 0.19096 | val 0.33989
  Regression -> MSE: 0.000205, MAE: 0.010109, R²: -0.0075
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.21112 | val 0.57818
  Epoch 020 - train 0.18951 | val 0.58021
  Regression -> MSE: 0.000579, MAE: 0.019189, R²: -0.0428
  Directional -> Accuracy: 0.4894, MCC: -0.0237, F1: 0.4545

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.23345 | val 0.42701
  Epoch 016 - train 0.20558 | val 0.54154
  Regression -> MSE: 0.000249, MAE: 0.011946, R²: -0.0155
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.18715 | val 0.46454
  Epoch 016 - train 0.16949 | val 0.50081
  Regression -> MSE: 0.000603, MAE: 0.019222, R²: -0.0093
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.21376 | val 0.35517
  Epoch 016 - train 0.19255 | val 0.42654
  Regression -> MSE: 0.000385, MAE: 0.015847, R²: -0.0047
  Directional -> Accuracy: 0.5918, MCC: 0.2636, F1: 0.6552

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.21867 | val 0.40099
  Epoch 016 - train 0.18479 | val 0.46782
  Regression -> MSE: 0.000246, MAE: 0.011654, R²: -0.0190
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.20388 | val 0.66640
  Epoch 017 - train 0.18174 | val 0.82323
  Regression -> MSE: 0.000308, MAE: 0.013627, R²: 0.0099
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.6301

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.22491 | val 0.35962
  Epoch 016 - train 0.20959 | val 0.40683
  Regression -> MSE: 0.000673, MAE: 0.019453, R²: 0.0065
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.21228 | val 0.30602
  Epoch 019 - train 0.17782 | val 0.37898
  Regression -> MSE: 0.000143, MAE: 0.009251, R²: -0.0382
  Directional -> Accuracy: 0.4884, MCC: 0.1965, F1: 0.6333

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.18747 | val 0.40473
  Epoch 016 - train 0.16413 | val 0.43427
  Regression -> MSE: 0.000225, MAE: 0.010691, R²: -0.0013
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.20964 | val 0.67626
  Epoch 016 - train 0.18866 | val 0.96322
  Regression -> MSE: 0.000368, MAE: 0.015895, R²: -0.0164
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.22343 | val 0.37342
  Epoch 017 - train 0.20452 | val 0.38272
  Regression -> MSE: 0.000105, MAE: 0.007965, R²: 0.0233
  Directional -> Accuracy: 0.5143, MCC: 0.0117, F1: 0.5750

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.21171 | val 0.60784
  Epoch 016 - train 0.19081 | val 0.73714
  Regression -> MSE: 0.000158, MAE: 0.009682, R²: -0.0112
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.24776 | val 0.35711
  Epoch 016 - train 0.22522 | val 0.52523
  Regression -> MSE: 0.000288, MAE: 0.013793, R²: -0.0599
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.20019 | val 0.38601
  Epoch 020 - train 0.16952 | val 0.40446
  Regression -> MSE: 0.000253, MAE: 0.012449, R²: -0.6892
  Directional -> Accuracy: 0.4000, MCC: -0.1483, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.23150 | val 0.43465
  Epoch 017 - train 0.18779 | val 0.48720
  Regression -> MSE: 0.000310, MAE: 0.012925, R²: -0.3707
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.22745 | val 0.37371
  Epoch 016 - train 0.20451 | val 0.44542
  Regression -> MSE: 0.000144, MAE: 0.008438, R²: -0.0036
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.20872 | val 0.35177
  Epoch 016 - train 0.19339 | val 0.34811
  Regression -> MSE: 0.000167, MAE: 0.010025, R²: -0.0109
  Directional -> Accuracy: 0.6364, MCC: 0.2732, F1: 0.6250

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.23008 | val 0.35688
  Epoch 020 - train 0.18464 | val 0.38459
  Regression -> MSE: 0.000082, MAE: 0.006990, R²: 0.0356
  Directional -> Accuracy: 0.5690, MCC: 0.1170, F1: 0.6269

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.22379 | val 0.42299
  Epoch 016 - train 0.20074 | val 0.45418
  Regression -> MSE: 0.000213, MAE: 0.011124, R²: -0.0043
  Directional -> Accuracy: 0.4545, MCC: -0.0721, F1: 0.5385

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.18966 | val 0.24113
  Epoch 017 - train 0.16934 | val 0.25496
  Regression -> MSE: 0.000096, MAE: 0.007957, R²: -0.0407
  Directional -> Accuracy: 0.5536, MCC: 0.1446, F1: 0.5098

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.22191 | val 0.22235
  Epoch 017 - train 0.19454 | val 0.24261
  Regression -> MSE: 0.000105, MAE: 0.008812, R²: -0.0142
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.22615 | val 0.28090
  Epoch 020 - train 0.19741 | val 0.37679
  Regression -> MSE: 0.000234, MAE: 0.012613, R²: -0.0117
  Directional -> Accuracy: 0.5116, MCC: 0.0511, F1: 0.5116

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.21738 | val 0.36059
  Epoch 020 - train 0.17838 | val 0.38079
  Regression -> MSE: 0.000206, MAE: 0.008646, R²: -0.2407
  Directional -> Accuracy: 0.5088, MCC: 0.1880, F1: 0.2632

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.21513 | val 0.26585
  Epoch 016 - train 0.19626 | val 0.28206
  Regression -> MSE: 0.000234, MAE: 0.011883, R²: 0.0090
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.19839 | val 0.58868
  Epoch 016 - train 0.19591 | val 0.71146
  Regression -> MSE: 0.000231, MAE: 0.009927, R²: -0.0035
  Directional -> Accuracy: 0.5116, MCC: 0.0353, F1: 0.5882

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.21308 | val 0.40217
  Epoch 017 - train 0.18845 | val 0.50653
  Regression -> MSE: 0.000135, MAE: 0.008243, R²: -0.0005
  Directional -> Accuracy: 0.6047, MCC: 0.2937, F1: 0.7302

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.22645 | val 0.40284
  Epoch 016 - train 0.18756 | val 0.50294
  Regression -> MSE: 0.000192, MAE: 0.010434, R²: -0.0224
  Directional -> Accuracy: 0.4600, MCC: -0.0835, F1: 0.4906

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.19031 | val 0.36010
  Epoch 018 - train 0.16831 | val 0.38311
  Regression -> MSE: 0.000268, MAE: 0.010754, R²: -0.0251
  Directional -> Accuracy: 0.5616, MCC: 0.1160, F1: 0.6000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.18174 | val 0.28805
  Epoch 016 - train 0.15182 | val 0.36955
  Regression -> MSE: 0.000164, MAE: 0.010286, R²: 0.0177
  Directional -> Accuracy: 0.5526, MCC: 0.1443, F1: 0.3200

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.18930 | val 0.34079
  Epoch 016 - train 0.16240 | val 0.34978
  Regression -> MSE: 0.000184, MAE: 0.010521, R²: -0.0235
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.22615 | val 0.31377
  Epoch 016 - train 0.19528 | val 0.31894
  Regression -> MSE: 0.000341, MAE: 0.011701, R²: 0.0057
  Directional -> Accuracy: 0.5970, MCC: 0.1589, F1: 0.6747

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.18791 | val 0.21494
  Epoch 016 - train 0.17417 | val 0.26203
  Regression -> MSE: 0.000111, MAE: 0.008183, R²: -0.0583
  Directional -> Accuracy: 0.5349, MCC: 0.1579, F1: 0.6875

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.20258 | val 0.43054
  Epoch 016 - train 0.18869 | val 0.53620
  Regression -> MSE: 0.000223, MAE: 0.011379, R²: -0.0191
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.21150 | val 0.56370
  Epoch 016 - train 0.18553 | val 0.58857
  Regression -> MSE: 0.000083, MAE: 0.007138, R²: -0.0735
  Directional -> Accuracy: 0.4043, MCC: -0.0814, F1: 0.3000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.19950 | val 0.23257
  Epoch 017 - train 0.19319 | val 0.23485
  Regression -> MSE: 0.000334, MAE: 0.015129, R²: -0.0854
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.21897 | val 0.18081
  Epoch 018 - train 0.18665 | val 0.21161
  Regression -> MSE: 0.000246, MAE: 0.011504, R²: -0.0108
  Directional -> Accuracy: 0.5526, MCC: 0.1286, F1: 0.4848

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.20358 | val 0.36492
  Epoch 016 - train 0.19101 | val 0.47216
  Regression -> MSE: 0.000080, MAE: 0.007035, R²: 0.0061
  Directional -> Accuracy: 0.4800, MCC: -0.0378, F1: 0.5618

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.23608 | val 0.37460
  Epoch 016 - train 0.21679 | val 0.41427
  Regression -> MSE: 0.000311, MAE: 0.014553, R²: -0.0151
  Directional -> Accuracy: 0.5319, MCC: 0.1506, F1: 0.6857

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.21000 | val 0.31779
  Epoch 016 - train 0.18566 | val 0.31398
  Regression -> MSE: 0.000097, MAE: 0.007194, R²: 0.0163
  Directional -> Accuracy: 0.5455, MCC: 0.0621, F1: 0.6154

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.21402 | val 0.39579
  Epoch 018 - train 0.18546 | val 0.42195
  Regression -> MSE: 0.000172, MAE: 0.009673, R²: -0.0028
  Directional -> Accuracy: 0.3878, MCC: -0.0861, F1: 0.5161

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.19749 | val 0.40282
  Epoch 016 - train 0.18331 | val 0.55217
  Regression -> MSE: 0.000224, MAE: 0.011821, R²: -0.0039
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.21147 | val 0.42520
  Epoch 016 - train 0.18178 | val 0.71021
  Regression -> MSE: 0.000096, MAE: 0.007881, R²: -0.0374
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.21448 | val 0.59779
  Epoch 016 - train 0.20252 | val 0.63339
  Regression -> MSE: 0.000164, MAE: 0.010177, R²: 0.0007
  Directional -> Accuracy: 0.6111, MCC: 0.2193, F1: 0.6441

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.21654 | val 0.40691
  Epoch 016 - train 0.19221 | val 0.43991
  Regression -> MSE: 0.000126, MAE: 0.009118, R²: -0.0863
  Directional -> Accuracy: 0.4286, MCC: -0.2466, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.22711 | val 0.45103

[I 2026-02-22 23:10:49,137] Trial 106 finished with value: -0.011517764307528839 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.1, 'dropout': 0.1, 'batch_size': 64, 'learning_rate': 0.008059280693300764, 'weight_decay': 1.7793575849757863e-06, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 0.5409112413953441, 'early_stopping_min_delta': 0.008026130438502138}. Best is trial 90 with value: -0.011414558399902668.

  Epoch 016 - train 0.18407 | val 0.90803
  Regression -> MSE: 0.000237, MAE: 0.012388, R²: -0.0013
  Directional -> Accuracy: 0.4918, MCC: 0.0647, F1: 0.6437

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.36704 | val 0.91341
  Epoch 016 - train 0.34559 | val 1.03588
  Regression -> MSE: 0.000247, MAE: 0.012477, R²: 0.0023
  Directional -> Accuracy: 0.4805, MCC: 0.0054, F1: 0.5652

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.35338 | val 0.61987
  Epoch 019 - train 0.31941 | val 0.75231
  Regression -> MSE: 0.000644, MAE: 0.018319, R²: 0.0599
  Directional -> Accuracy: 0.6304, MCC: 0.2573, F1: 0.7463

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.39326 | val 1.05112
  Epoch 016 - train 0.37137 | val 1.05768
  Regression -> MSE: 0.000315, MAE: 0.014460, R²: -0.0143
  Directional -> Accuracy: 0.5319, MCC: 0.0417, F1: 0.6207

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.29449 | val 1.57101
  Epoch 016 - train 0.27419 | val 1.65571
  Regression -> MSE: 0.000388, MAE: 0.015222, R²: -0.1117
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.36683 | val 1.27520
  Epoch 016 - train 0.33881 | val 1.36030
  Regression -> MSE: 0.000205, MAE: 0.010326, R²: -0.0049
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.32502 | val 1.99193
  Epoch 016 - train 0.29749 | val 2.15430
  Regression -> MSE: 0.000558, MAE: 0.018146, R²: -0.0050
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.37965 | val 0.69225
  Epoch 016 - train 0.35424 | val 0.72069
  Regression -> MSE: 0.000249, MAE: 0.011931, R²: -0.0136
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.38483 | val 0.92292
  Epoch 016 - train 0.35828 | val 0.95782
  Regression -> MSE: 0.000623, MAE: 0.019745, R²: -0.0433
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.37136 | val 0.95205
  Epoch 016 - train 0.34580 | val 1.00811
  Regression -> MSE: 0.000395, MAE: 0.015987, R²: -0.0300
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.37219 | val 0.97781
  Epoch 016 - train 0.34665 | val 0.90154
  Regression -> MSE: 0.000240, MAE: 0.011758, R²: 0.0048
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.33858 | val 2.39739
  Epoch 016 - train 0.31700 | val 2.49980
  Regression -> MSE: 0.000317, MAE: 0.014080, R²: -0.0208
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.6301

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.37375 | val 0.91055
  Epoch 016 - train 0.34881 | val 1.05363
  Regression -> MSE: 0.000677, MAE: 0.019481, R²: 0.0003
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.36411 | val 0.77202
  Epoch 016 - train 0.33701 | val 0.89032
  Regression -> MSE: 0.000139, MAE: 0.009262, R²: -0.0090
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.31477 | val 0.86010
  Epoch 020 - train 0.27915 | val 1.36722
  Regression -> MSE: 0.000237, MAE: 0.011676, R²: -0.0547
  Directional -> Accuracy: 0.5574, MCC: 0.1393, F1: 0.4255

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.36676 | val 1.31497
  Epoch 020 - train 0.31941 | val 1.29891
  Regression -> MSE: 0.000450, MAE: 0.017786, R²: -0.2414
  Directional -> Accuracy: 0.4808, MCC: 0.1296, F1: 0.6400

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.37923 | val 0.60516
  Epoch 016 - train 0.35265 | val 0.61537
  Regression -> MSE: 0.000108, MAE: 0.007952, R²: -0.0029
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.35153 | val 2.46405
  Epoch 018 - train 0.32677 | val 3.05444
  Regression -> MSE: 0.000169, MAE: 0.010516, R²: -0.0821
  Directional -> Accuracy: 0.4407, MCC: 0.0681, F1: 0.2979

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.37407 | val 1.02204
  Epoch 016 - train 0.34456 | val 1.18153
  Regression -> MSE: 0.000275, MAE: 0.013161, R²: -0.0120
  Directional -> Accuracy: 0.6184, MCC: 0.1880, F1: 0.6947

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.29476 | val 0.71763
  Epoch 019 - train 0.26755 | val 0.71868
  Regression -> MSE: 0.000216, MAE: 0.011152, R²: -0.4432
  Directional -> Accuracy: 0.5231, MCC: 0.0770, F1: 0.5231

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.36327 | val 0.94358
  Epoch 017 - train 0.33359 | val 0.96147
  Regression -> MSE: 0.000293, MAE: 0.012505, R²: -0.2969
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.36146 | val 1.19594
  Epoch 016 - train 0.33271 | val 1.20408
  Regression -> MSE: 0.000151, MAE: 0.008735, R²: -0.0557
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.35859 | val 0.67106
  Epoch 016 - train 0.33761 | val 0.70359
  Regression -> MSE: 0.000166, MAE: 0.010777, R²: -0.0072
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.40875 | val 0.81505
  Epoch 016 - train 0.38574 | val 0.84770
  Regression -> MSE: 0.000085, MAE: 0.007041, R²: 0.0079
  Directional -> Accuracy: 0.5862, MCC: 0.1522, F1: 0.7333

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.36497 | val 0.92741
  Epoch 016 - train 0.33710 | val 1.09026
  Regression -> MSE: 0.000211, MAE: 0.010948, R²: 0.0027
  Directional -> Accuracy: 0.5758, MCC: 0.1493, F1: 0.3333

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.32976 | val 0.30649
  Epoch 019 - train 0.30011 | val 0.30910
  Regression -> MSE: 0.000124, MAE: 0.008845, R²: -0.3459
  Directional -> Accuracy: 0.5536, MCC: 0.1867, F1: 0.4444

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.39284 | val 0.30949
  Epoch 020 - train 0.33826 | val 0.29926
  Regression -> MSE: 0.000240, MAE: 0.012993, R²: -1.3299
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.39776 | val 1.39702
  Epoch 016 - train 0.37511 | val 1.93390
  Regression -> MSE: 0.000233, MAE: 0.012571, R²: -0.0049
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.37332 | val 0.66270
  Epoch 016 - train 0.35253 | val 0.66906
  Regression -> MSE: 0.000181, MAE: 0.007926, R²: -0.0877
  Directional -> Accuracy: 0.5439, MCC: 0.2554, F1: 0.3500

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.36791 | val 0.46619
  Epoch 016 - train 0.33037 | val 0.48032
  Regression -> MSE: 0.000236, MAE: 0.011862, R²: 0.0006
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.36091 | val 1.06679
  Epoch 016 - train 0.33159 | val 1.08797
  Regression -> MSE: 0.000233, MAE: 0.010058, R²: -0.0118
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.39378 | val 0.95890
  Epoch 016 - train 0.36220 | val 1.04656
  Regression -> MSE: 0.000138, MAE: 0.008234, R²: -0.0189
  Directional -> Accuracy: 0.6279, MCC: 0.2484, F1: 0.6667

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.38119 | val 0.70616
  Epoch 018 - train 0.34706 | val 0.72734
  Regression -> MSE: 0.000217, MAE: 0.011375, R²: -0.1522
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.30944 | val 0.75995
  Epoch 018 - train 0.28360 | val 0.79333
  Regression -> MSE: 0.000491, MAE: 0.016212, R²: -0.8759
  Directional -> Accuracy: 0.5342, MCC: 0.1602, F1: 0.4138

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.38606 | val 0.47178
  Epoch 020 - train 0.33480 | val 0.81591
  Regression -> MSE: 0.000162, MAE: 0.010358, R²: 0.0267
  Directional -> Accuracy: 0.5526, MCC: 0.1443, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.33496 | val 0.64207
  Epoch 016 - train 0.31171 | val 0.62939
  Regression -> MSE: 0.000182, MAE: 0.010369, R²: -0.0127
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.34883 | val 0.41214
  Epoch 020 - train 0.30345 | val 0.40501
  Regression -> MSE: 0.001302, MAE: 0.032621, R²: -2.8004
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.38539 | val 0.24927
  Epoch 020 - train 0.32837 | val 0.26435
  Regression -> MSE: 0.000121, MAE: 0.007940, R²: -0.1486
  Directional -> Accuracy: 0.6279, MCC: 0.2632, F1: 0.6000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.33828 | val 0.93282
  Epoch 018 - train 0.30196 | val 1.08904
  Regression -> MSE: 0.000234, MAE: 0.011947, R²: -0.0705
  Directional -> Accuracy: 0.4912, MCC: -0.0262, F1: 0.4314

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.36284 | val 2.00883
  Epoch 016 - train 0.33169 | val 2.33789
  Regression -> MSE: 0.000078, MAE: 0.006935, R²: -0.0043
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.38834 | val 0.25347
  Epoch 020 - train 0.33652 | val 0.25788
  Regression -> MSE: 0.000316, MAE: 0.013510, R²: -0.0265
  Directional -> Accuracy: 0.6735, MCC: 0.3543, F1: 0.6190

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.37579 | val 0.29629
  Epoch 016 - train 0.34257 | val 0.39569
  Regression -> MSE: 0.000254, MAE: 0.011441, R²: -0.0427
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.33633 | val 0.92255
  Epoch 016 - train 0.31710 | val 0.97895
  Regression -> MSE: 0.000082, MAE: 0.007005, R²: -0.0147
  Directional -> Accuracy: 0.5333, MCC: 0.1219, F1: 0.1463

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.39001 | val 1.29267
  Epoch 019 - train 0.34094 | val 1.58543
  Regression -> MSE: 0.000316, MAE: 0.014415, R²: -0.0289
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.35619 | val 0.59455
  Epoch 016 - train 0.32900 | val 0.60914
  Regression -> MSE: 0.000099, MAE: 0.007177, R²: -0.0122
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.37670 | val 0.82622
  Epoch 016 - train 0.33670 | val 0.81773
  Regression -> MSE: 0.000175, MAE: 0.010230, R²: -0.0181
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.34249 | val 0.80847
  Epoch 016 - train 0.32250 | val 0.93324
  Regression -> MSE: 0.000225, MAE: 0.011835, R²: -0.0072
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.34147 | val 0.98313
  Epoch 016 - train 0.31530 | val 1.01273
  Regression -> MSE: 0.000099, MAE: 0.008100, R²: -0.0742
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.39561 | val 1.04364
  Epoch 016 - train 0.37289 | val 1.10403
  Regression -> MSE: 0.000163, MAE: 0.010179, R²: 0.0044
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.36167 | val 0.66508
  Epoch 016 - train 0.33381 | val 0.67572
  Regression -> MSE: 0.000124, MAE: 0.008978, R²: -0.0721
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.38481 | val 0.85805

[I 2026-02-22 23:11:50,108] Trial 107 finished with value: -0.012217994955791673 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.0, 'batch_size': 16, 'learning_rate': 0.00010460600261250245, 'weight_decay': 4.595863172659634e-06, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 1.6183423556119805, 'early_stopping_min_delta': 0.006694435142771038}. Best is trial 90 with value: -0.011414558399902668.

  Epoch 020 - train 0.32977 | val 0.90979
  Regression -> MSE: 0.000341, MAE: 0.014341, R²: -0.4365
  Directional -> Accuracy: 0.5738, MCC: 0.1593, F1: 0.3158

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.33122 | val 0.83897
  Epoch 020 - train 0.26695 | val 1.37232
  Regression -> MSE: 0.000256, MAE: 0.012839, R²: -0.0337
  Directional -> Accuracy: 0.4416, MCC: -0.0858, F1: 0.6055

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.34032 | val 0.43720
  Epoch 017 - train 0.27814 | val 0.50823
  Regression -> MSE: 0.000683, MAE: 0.019536, R²: 0.0026
  Directional -> Accuracy: 0.5000, MCC: 0.0232, F1: 0.4889

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.34744 | val 0.93959
  Epoch 016 - train 0.28862 | val 1.05851
  Regression -> MSE: 0.000317, MAE: 0.014404, R²: -0.0233
  Directional -> Accuracy: 0.5532, MCC: 0.1581, F1: 0.4324

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.29430 | val 1.98966
  Epoch 016 - train 0.26194 | val 2.98667
  Regression -> MSE: 0.000357, MAE: 0.014633, R²: -0.0214
  Directional -> Accuracy: 0.5067, MCC: 0.0328, F1: 0.4789

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.32154 | val 0.53655
  Epoch 016 - train 0.27476 | val 0.71467
  Regression -> MSE: 0.000202, MAE: 0.009987, R²: 0.0087
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.29959 | val 1.14703
  Epoch 016 - train 0.24713 | val 1.13987
  Regression -> MSE: 0.000550, MAE: 0.018182, R²: 0.0087
  Directional -> Accuracy: 0.4894, MCC: 0.0000, F1: 0.6571

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.34160 | val 0.79158
  Epoch 017 - train 0.29572 | val 1.46220
  Regression -> MSE: 0.000243, MAE: 0.011999, R²: 0.0101
  Directional -> Accuracy: 0.5072, MCC: 0.0578, F1: 0.5143

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.27792 | val 0.61776
  Epoch 020 - train 0.19643 | val 0.70602
  Regression -> MSE: 0.000608, MAE: 0.019361, R²: -0.0178
  Directional -> Accuracy: 0.5909, MCC: 0.0872, F1: 0.3077

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.31867 | val 0.62829
  Epoch 017 - train 0.23585 | val 1.05008
  Regression -> MSE: 0.000380, MAE: 0.015966, R²: 0.0098
  Directional -> Accuracy: 0.4490, MCC: -0.0383, F1: 0.5846

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.35993 | val 0.71208
  Epoch 017 - train 0.27497 | val 1.57961
  Regression -> MSE: 0.000241, MAE: 0.011797, R²: 0.0024
  Directional -> Accuracy: 0.4286, MCC: -0.0722, F1: 0.5349

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.29049 | val 1.69376
  Epoch 018 - train 0.23804 | val 2.75221
  Regression -> MSE: 0.000298, MAE: 0.013489, R²: 0.0407
  Directional -> Accuracy: 0.5400, MCC: 0.0905, F1: 0.5490

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.33363 | val 0.60539
  Epoch 017 - train 0.27024 | val 0.78228
  Regression -> MSE: 0.000675, MAE: 0.019476, R²: 0.0036
  Directional -> Accuracy: 0.5172, MCC: 0.1325, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.31582 | val 0.51289
  Epoch 016 - train 0.24364 | val 0.78934
  Regression -> MSE: 0.000143, MAE: 0.009453, R²: -0.0373
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.30821 | val 0.71543
  Epoch 016 - train 0.27239 | val 0.84921
  Regression -> MSE: 0.000224, MAE: 0.010610, R²: 0.0037
  Directional -> Accuracy: 0.5246, MCC: 0.0813, F1: 0.2927

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.33044 | val 1.50615
  Epoch 017 - train 0.28066 | val 2.48838
  Regression -> MSE: 0.000370, MAE: 0.015993, R²: -0.0217
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.36420 | val 0.60909
  Epoch 017 - train 0.27467 | val 0.65067
  Regression -> MSE: 0.000108, MAE: 0.007919, R²: -0.0019
  Directional -> Accuracy: 0.5429, MCC: 0.0391, F1: 0.6667

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.30564 | val 1.15102
  Epoch 016 - train 0.25822 | val 1.52956
  Regression -> MSE: 0.000158, MAE: 0.009705, R²: -0.0126
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.36551 | val 1.01007
  Epoch 016 - train 0.29803 | val 2.51024
  Regression -> MSE: 0.000273, MAE: 0.013122, R²: -0.0039
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.30531 | val 0.63133
  Epoch 020 - train 0.24561 | val 0.71419
  Regression -> MSE: 0.000220, MAE: 0.011030, R²: -0.4715
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.30224 | val 0.85855
  Epoch 019 - train 0.27196 | val 1.38023
  Regression -> MSE: 0.000277, MAE: 0.011952, R²: -0.2227
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.32435 | val 0.63995
  Epoch 020 - train 0.24185 | val 1.05121
  Regression -> MSE: 0.000153, MAE: 0.008880, R²: -0.0685
  Directional -> Accuracy: 0.4375, MCC: 0.1233, F1: 0.2286

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.32341 | val 0.60979
  Epoch 016 - train 0.29332 | val 0.70870
  Regression -> MSE: 0.000171, MAE: 0.010345, R²: -0.0376
  Directional -> Accuracy: 0.4697, MCC: -0.0606, F1: 0.4615

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.32932 | val 0.77214
  Epoch 017 - train 0.24153 | val 0.89422
  Regression -> MSE: 0.000083, MAE: 0.006968, R²: 0.0285
  Directional -> Accuracy: 0.6034, MCC: 0.1743, F1: 0.6761

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.31404 | val 1.02482
  Epoch 017 - train 0.24549 | val 1.84847
  Regression -> MSE: 0.000212, MAE: 0.011228, R²: 0.0013
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.28315 | val 0.28849
  Epoch 020 - train 0.21623 | val 0.32141
  Regression -> MSE: 0.000113, MAE: 0.008411, R²: -0.2255
  Directional -> Accuracy: 0.5179, MCC: 0.0131, F1: 0.5846

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.32925 | val 0.32993
  Epoch 016 - train 0.25612 | val 0.40671
  Regression -> MSE: 0.000103, MAE: 0.008648, R²: 0.0049
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.37000 | val 0.38406
  Epoch 020 - train 0.25791 | val 0.60192
  Regression -> MSE: 0.000228, MAE: 0.012530, R²: 0.0128
  Directional -> Accuracy: 0.5581, MCC: 0.0089, F1: 0.6885

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.32398 | val 0.58947
  Epoch 018 - train 0.28097 | val 0.60615
  Regression -> MSE: 0.000235, MAE: 0.009898, R²: -0.4107
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.29708 | val 0.43466
  Epoch 016 - train 0.23027 | val 0.68653
  Regression -> MSE: 0.000234, MAE: 0.011809, R²: 0.0098
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.29218 | val 1.30665
  Epoch 017 - train 0.24101 | val 1.59367
  Regression -> MSE: 0.000230, MAE: 0.009907, R²: 0.0036
  Directional -> Accuracy: 0.5349, MCC: 0.0716, F1: 0.5455

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.29049 | val 0.69807
  Epoch 016 - train 0.23491 | val 0.96850
  Regression -> MSE: 0.000140, MAE: 0.008235, R²: -0.0340
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.30368 | val 0.65098
  Epoch 020 - train 0.22267 | val 0.71049
  Regression -> MSE: 0.000413, MAE: 0.016574, R²: -1.1920
  Directional -> Accuracy: 0.4000, MCC: -0.1839, F1: 0.2857

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.31848 | val 0.57800
  Epoch 020 - train 0.23601 | val 0.74583
  Regression -> MSE: 0.000286, MAE: 0.011321, R²: -0.0927
  Directional -> Accuracy: 0.4932, MCC: 0.0475, F1: 0.3934

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.27006 | val 0.40859
  Epoch 016 - train 0.14986 | val 0.50362
  Regression -> MSE: 0.000157, MAE: 0.010206, R²: 0.0591
  Directional -> Accuracy: 0.4737, MCC: -0.0555, F1: 0.5455

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.25719 | val 0.53915
  Epoch 016 - train 0.22960 | val 0.61326
  Regression -> MSE: 0.000183, MAE: 0.010476, R²: -0.0191
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.31961 | val 0.45481
  Epoch 017 - train 0.28562 | val 0.54390
  Regression -> MSE: 0.000343, MAE: 0.012284, R²: -0.0014
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.26827 | val 0.23640
  Epoch 020 - train 0.18026 | val 0.46082
  Regression -> MSE: 0.000123, MAE: 0.008189, R²: -0.1688
  Directional -> Accuracy: 0.6279, MCC: 0.2967, F1: 0.5294

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.31558 | val 0.93402
  Epoch 016 - train 0.23757 | val 1.16230
  Regression -> MSE: 0.000220, MAE: 0.011339, R²: -0.0046
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.31018 | val 1.11388
  Epoch 016 - train 0.24523 | val 1.32285
  Regression -> MSE: 0.000081, MAE: 0.007006, R²: -0.0433
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.29832 | val 0.28280
  Epoch 020 - train 0.22882 | val 0.28197
  Regression -> MSE: 0.000489, MAE: 0.018884, R²: -0.5895
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.25820 | val 0.24193
  Epoch 016 - train 0.20543 | val 0.28055
  Regression -> MSE: 0.000252, MAE: 0.011358, R²: -0.0317
  Directional -> Accuracy: 0.5263, MCC: 0.0228, F1: 0.6538

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.30331 | val 0.68212
  Epoch 020 - train 0.25136 | val 0.91437
  Regression -> MSE: 0.000080, MAE: 0.007010, R²: 0.0113
  Directional -> Accuracy: 0.5467, MCC: 0.1682, F1: 0.6731

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.33752 | val 0.63815
  Epoch 017 - train 0.22561 | val 0.80561
  Regression -> MSE: 0.000311, MAE: 0.014528, R²: -0.0153
  Directional -> Accuracy: 0.4681, MCC: -0.1460, F1: 0.6269

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.31099 | val 0.57005
  Epoch 020 - train 0.22184 | val 0.52692
  Regression -> MSE: 0.000103, MAE: 0.007061, R²: -0.0530
  Directional -> Accuracy: 0.5682, MCC: 0.0747, F1: 0.6780

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.28790 | val 0.72643
  Epoch 016 - train 0.18026 | val 0.85099
  Regression -> MSE: 0.000174, MAE: 0.010003, R²: -0.0107
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.27801 | val 1.00205
  Epoch 016 - train 0.26559 | val 1.04668
  Regression -> MSE: 0.000223, MAE: 0.011673, R²: 0.0018
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.27369 | val 0.92202
  Epoch 018 - train 0.18751 | val 1.10169
  Regression -> MSE: 0.000093, MAE: 0.007730, R²: -0.0059
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.32769 | val 1.24295
  Epoch 016 - train 0.27857 | val 1.88381
  Regression -> MSE: 0.000163, MAE: 0.010240, R²: 0.0070
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.29923 | val 0.61970
  Epoch 016 - train 0.25937 | val 0.77773
  Regression -> MSE: 0.000134, MAE: 0.009191, R²: -0.1569
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.37693 | val 1.41887

[I 2026-02-22 23:12:27,523] Trial 108 finished with value: -0.011715125573548646 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.1, 'batch_size': 64, 'learning_rate': 0.009341504953100667, 'weight_decay': 1.4762903678659235e-06, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 1.4015215488504875, 'early_stopping_min_delta': 0.009266797814669984}. Best is trial 90 with value: -0.011414558399902668.

  Epoch 018 - train 0.25585 | val 2.85753
  Regression -> MSE: 0.000241, MAE: 0.012370, R²: -0.0181
  Directional -> Accuracy: 0.5082, MCC: -0.0338, F1: 0.1667

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.30013 | val 0.51539
  Epoch 020 - train 0.24201 | val 0.70052
  Regression -> MSE: 0.000272, MAE: 0.012751, R²: -0.0989
  Directional -> Accuracy: 0.5974, MCC: 0.1783, F1: 0.3673

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.30184 | val 0.37099
  Epoch 020 - train 0.21386 | val 0.40107
  Regression -> MSE: 0.000728, MAE: 0.019855, R²: -0.0636
  Directional -> Accuracy: 0.5217, MCC: 0.0382, F1: 0.5600

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.29915 | val 0.80648
  Epoch 020 - train 0.17980 | val 0.83211
  Regression -> MSE: 0.000313, MAE: 0.014465, R²: -0.0095
  Directional -> Accuracy: 0.4468, MCC: -0.1581, F1: 0.5667

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.24783 | val 0.89113
  Epoch 020 - train 0.20297 | val 1.58890
  Regression -> MSE: 0.000356, MAE: 0.014692, R²: -0.0197
  Directional -> Accuracy: 0.5467, MCC: 0.0765, F1: 0.6047

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.29713 | val 0.53286
  Epoch 020 - train 0.22308 | val 0.64293
  Regression -> MSE: 0.000208, MAE: 0.010375, R²: -0.0221
  Directional -> Accuracy: 0.5294, MCC: 0.0119, F1: 0.6842

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.30165 | val 0.89491
  Epoch 020 - train 0.17883 | val 0.88978
  Regression -> MSE: 0.000526, MAE: 0.017628, R²: 0.0523
  Directional -> Accuracy: 0.6383, MCC: 0.2772, F1: 0.6383

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.29235 | val 0.57134
  Epoch 020 - train 0.19404 | val 0.76449
  Regression -> MSE: 0.000245, MAE: 0.011863, R²: 0.0005
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.22360 | val 0.74373
  Epoch 020 - train 0.14217 | val 0.87238
  Regression -> MSE: 0.000618, MAE: 0.019580, R²: -0.0342
  Directional -> Accuracy: 0.4318, MCC: -0.0172, F1: 0.5455

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.28498 | val 0.66395
  Epoch 020 - train 0.22016 | val 0.97292
  Regression -> MSE: 0.000387, MAE: 0.015923, R²: -0.0101
  Directional -> Accuracy: 0.5510, MCC: 0.1091, F1: 0.5417

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.30884 | val 0.58299
  Epoch 020 - train 0.21418 | val 0.78738
  Regression -> MSE: 0.000240, MAE: 0.011744, R²: 0.0057
  Directional -> Accuracy: 0.5571, MCC: 0.1328, F1: 0.5507

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.26031 | val 1.14000
  Epoch 020 - train 0.20388 | val 1.83329
  Regression -> MSE: 0.000303, MAE: 0.013556, R²: 0.0256
  Directional -> Accuracy: 0.6400, MCC: 0.2848, F1: 0.4706

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.29133 | val 0.67539
  Epoch 020 - train 0.20761 | val 0.97512
  Regression -> MSE: 0.000645, MAE: 0.018919, R²: 0.0477
  Directional -> Accuracy: 0.6207, MCC: 0.2894, F1: 0.7027

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.26914 | val 0.44276
  Epoch 020 - train 0.15891 | val 0.83716
  Regression -> MSE: 0.000140, MAE: 0.009203, R²: -0.0110
  Directional -> Accuracy: 0.4651, MCC: -0.0261, F1: 0.5306

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.24943 | val 0.59262
  Epoch 020 - train 0.18644 | val 0.63942
  Regression -> MSE: 0.000225, MAE: 0.010594, R²: -0.0021
  Directional -> Accuracy: 0.5410, MCC: 0.1202, F1: 0.3333

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.28991 | val 1.40430
  Epoch 020 - train 0.21052 | val 2.00116
  Regression -> MSE: 0.000364, MAE: 0.016263, R²: -0.0055
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.30372 | val 0.53541
  Epoch 020 - train 0.20878 | val 0.72330
  Regression -> MSE: 0.000108, MAE: 0.008014, R²: -0.0050
  Directional -> Accuracy: 0.5000, MCC: -0.0314, F1: 0.5882

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.28769 | val 1.18892
  Epoch 020 - train 0.20210 | val 1.22880
  Regression -> MSE: 0.000160, MAE: 0.009960, R²: -0.0256
  Directional -> Accuracy: 0.5763, MCC: -0.1785, F1: 0.7312

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.31897 | val 0.67442
  Epoch 020 - train 0.23774 | val 0.97746
  Regression -> MSE: 0.000279, MAE: 0.013422, R²: -0.0261
  Directional -> Accuracy: 0.3947, MCC: -0.1463, F1: 0.3429

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.26915 | val 0.59393
  Epoch 020 - train 0.22207 | val 0.56541
  Regression -> MSE: 0.000203, MAE: 0.010455, R²: -0.3540
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.31131 | val 0.71096
  Epoch 020 - train 0.23505 | val 0.75572
  Regression -> MSE: 0.000299, MAE: 0.012611, R²: -0.3194
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.30297 | val 0.60377
  Epoch 020 - train 0.20663 | val 0.74239
  Regression -> MSE: 0.000144, MAE: 0.008753, R²: -0.0055
  Directional -> Accuracy: 0.5625, MCC: 0.1870, F1: 0.5714

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.28672 | val 0.55469
  Epoch 020 - train 0.22799 | val 0.57843
  Regression -> MSE: 0.000175, MAE: 0.010248, R²: -0.0571
  Directional -> Accuracy: 0.5152, MCC: 0.0381, F1: 0.3043

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.31237 | val 0.66379
  Epoch 020 - train 0.25987 | val 0.76044
  Regression -> MSE: 0.000085, MAE: 0.007031, R²: 0.0044
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.27919 | val 0.72124
  Epoch 020 - train 0.20216 | val 0.86522
  Regression -> MSE: 0.000212, MAE: 0.011134, R²: 0.0007
  Directional -> Accuracy: 0.4394, MCC: -0.1156, F1: 0.5843

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.23735 | val 0.33885
  Epoch 020 - train 0.18035 | val 0.39287
  Regression -> MSE: 0.000111, MAE: 0.008398, R²: -0.2051
  Directional -> Accuracy: 0.5536, MCC: 0.2064, F1: 0.4186

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.30267 | val 0.35589
  Epoch 020 - train 0.20549 | val 0.77140
  Regression -> MSE: 0.000105, MAE: 0.008829, R²: -0.0163
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.31016 | val 0.40821
  Epoch 020 - train 0.23288 | val 0.47956
  Regression -> MSE: 0.000234, MAE: 0.012570, R²: -0.0093
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.28389 | val 0.52766
  Epoch 020 - train 0.21459 | val 0.61933
  Regression -> MSE: 0.000181, MAE: 0.007978, R²: -0.0870
  Directional -> Accuracy: 0.4386, MCC: -0.0236, F1: 0.0588

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.28383 | val 0.37622
  Epoch 020 - train 0.18023 | val 0.54655
  Regression -> MSE: 0.000236, MAE: 0.011940, R²: 0.0032
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.24907 | val 0.86600
  Epoch 020 - train 0.17435 | val 0.91895
  Regression -> MSE: 0.000232, MAE: 0.009945, R²: -0.0067
  Directional -> Accuracy: 0.4651, MCC: -0.0716, F1: 0.4390

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.28393 | val 0.57943
  Epoch 020 - train 0.17459 | val 0.78415
  Regression -> MSE: 0.000138, MAE: 0.008162, R²: -0.0229
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.26289 | val 0.64492
  Epoch 020 - train 0.18270 | val 0.82677
  Regression -> MSE: 0.000193, MAE: 0.010622, R²: -0.0229
  Directional -> Accuracy: 0.4600, MCC: -0.0451, F1: 0.3077

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.26260 | val 0.49139
  Epoch 020 - train 0.20868 | val 0.51342
  Regression -> MSE: 0.000281, MAE: 0.010998, R²: -0.0739
  Directional -> Accuracy: 0.5342, MCC: 0.1602, F1: 0.4138

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.24309 | val 0.36504
  Epoch 020 - train 0.14869 | val 0.44504
  Regression -> MSE: 0.000159, MAE: 0.010324, R²: 0.0446
  Directional -> Accuracy: 0.4737, MCC: -0.0555, F1: 0.5455

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.23242 | val 0.51821
  Epoch 020 - train 0.17342 | val 0.50502
  Regression -> MSE: 0.000179, MAE: 0.010309, R²: 0.0058
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.29287 | val 0.52989
  Epoch 020 - train 0.21173 | val 0.47227
  Regression -> MSE: 0.000357, MAE: 0.012935, R²: -0.0423
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.23074 | val 0.31279
  Epoch 020 - train 0.14787 | val 0.45401
  Regression -> MSE: 0.000111, MAE: 0.008026, R²: -0.0561
  Directional -> Accuracy: 0.6047, MCC: 0.2147, F1: 0.6667

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.26566 | val 0.79068
  Epoch 020 - train 0.20924 | val 1.23126
  Regression -> MSE: 0.000218, MAE: 0.011246, R²: 0.0008
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.27258 | val 0.96007
  Epoch 020 - train 0.19800 | val 1.05972
  Regression -> MSE: 0.000084, MAE: 0.007155, R²: -0.0837
  Directional -> Accuracy: 0.4468, MCC: -0.0843, F1: 0.4800

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.24951 | val 0.27765
  Epoch 020 - train 0.17230 | val 0.27877
  Regression -> MSE: 0.000480, MAE: 0.018588, R²: -0.5600
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.23887 | val 0.28768
  Epoch 020 - train 0.09721 | val 0.38049
  Regression -> MSE: 0.000249, MAE: 0.011474, R²: -0.0213
  Directional -> Accuracy: 0.5526, MCC: 0.1789, F1: 0.3704

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.26934 | val 0.63179
  Epoch 020 - train 0.21272 | val 0.85847
  Regression -> MSE: 0.000080, MAE: 0.007026, R²: 0.0140
  Directional -> Accuracy: 0.5200, MCC: 0.1633, F1: 0.6727

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.25535 | val 0.53980
  Epoch 020 - train 0.15669 | val 0.78852
  Regression -> MSE: 0.000309, MAE: 0.014499, R²: -0.0084
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.27314 | val 0.46647
  Epoch 020 - train 0.18130 | val 0.48298
  Regression -> MSE: 0.000099, MAE: 0.007360, R²: -0.0114
  Directional -> Accuracy: 0.3864, MCC: -0.2031, F1: 0.0690

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.24264 | val 0.57954
  Epoch 020 - train 0.10924 | val 0.77348
  Regression -> MSE: 0.000178, MAE: 0.010253, R²: -0.0374
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.25747 | val 0.59755
  Epoch 020 - train 0.18451 | val 0.55160
  Regression -> MSE: 0.000223, MAE: 0.011708, R²: 0.0011
  Directional -> Accuracy: 0.5893, MCC: 0.1766, F1: 0.6102

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.26644 | val 0.72649
  Epoch 020 - train 0.13826 | val 0.82363
  Regression -> MSE: 0.000093, MAE: 0.007757, R²: -0.0121
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.30964 | val 0.95458
  Epoch 020 - train 0.19549 | val 1.30961
  Regression -> MSE: 0.000161, MAE: 0.010120, R²: 0.0170
  Directional -> Accuracy: 0.5741, MCC: 0.1568, F1: 0.6761

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.28018 | val 0.58652
  Epoch 020 - train 0.21001 | val 0.64310
  Regression -> MSE: 0.000122, MAE: 0.009021, R²: -0.0556
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.27473 | val 1.32486

[I 2026-02-22 23:12:50,875] Trial 109 finished with value: -0.011579755553299735 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.1, 'dropout': 0.0, 'batch_size': 64, 'learning_rate': 0.009865222003732748, 'weight_decay': 1.0928428170746254e-06, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.9803667876770106, 'early_stopping_min_delta': 0.00716293288588655}. Best is trial 90 with value: -0.011414558399902668.

  Epoch 020 - train 0.19476 | val 2.12676
  Regression -> MSE: 0.000242, MAE: 0.012703, R²: -0.0191
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 12
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.28141 | val 0.41358
  Epoch 011 - train 0.27952 | val 0.41523
  Regression -> MSE: 0.000245, MAE: 0.012446, R²: 0.0012
  Directional -> Accuracy: 0.5513, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 88). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.32322 | val 0.28120
  Epoch 011 - train 0.31980 | val 0.28127
  Regression -> MSE: 0.000707, MAE: 0.019920, R²: -0.0231
  Directional -> Accuracy: 0.4468, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 88). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.35011 | val 0.54795
  Epoch 011 - train 0.32848 | val 0.54725
  Regression -> MSE: 0.000348, MAE: 0.015045, R²: -0.0075
  Directional -> Accuracy: 0.5417, MCC: 0.0000, F1: 0.7027

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.25920 | val 0.26286
  Epoch 011 - train 0.25116 | val 0.26406
  Regression -> MSE: 0.000345, MAE: 0.014450, R²: -0.0005
  Directional -> Accuracy: 0.5395, MCC: 0.0000, F1: 0.7009

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.30946 | val 0.31220
  Epoch 020 - train 0.30265 | val 0.29012
  Regression -> MSE: 0.000186, MAE: 0.009442, R²: 0.0715
  Directional -> Accuracy: 0.6538, MCC: 0.3880, F1: 0.5714

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.28983 | val 0.63233
  Epoch 011 - train 0.28825 | val 0.63159
  Regression -> MSE: 0.000586, MAE: 0.018528, R²: -0.0238
  Directional -> Accuracy: 0.4898, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.33001 | val 0.41398
  Epoch 011 - train 0.32852 | val 0.41340
  Regression -> MSE: 0.000248, MAE: 0.012023, R²: -0.0102
  Directional -> Accuracy: 0.6000, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 88). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 88). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.32759 | val 0.47164
  Epoch 011 - train 0.31818 | val 0.47274
  Regression -> MSE: 0.000635, MAE: 0.019859, R²: -0.0863
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.29017 | val 0.48803
  Epoch 011 - train 0.30331 | val 0.48719
  Regression -> MSE: 0.000340, MAE: 0.014813, R²: -0.0059
  Directional -> Accuracy: 0.6190, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 88). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 88). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.31096 | val 0.43287
  Epoch 011 - train 0.31079 | val 0.43491
  Regression -> MSE: 0.000241, MAE: 0.011518, R²: -0.0101
  Directional -> Accuracy: 0.5634, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.28387 | val 0.51452
  Epoch 011 - train 0.28104 | val 0.52109
  Regression -> MSE: 0.000306, MAE: 0.013552, R²: -0.0015
  Directional -> Accuracy: 0.4314, MCC: -0.1387, F1: 0.4082

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.32496 | val 0.37534
  Epoch 011 - train 0.33103 | val 0.37852
  Regression -> MSE: 0.000672, MAE: 0.019514, R²: -0.0043
  Directional -> Accuracy: 0.5085, MCC: 0.0000, F1: 0.6742

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.30570 | val 0.29872
  Epoch 011 - train 0.31351 | val 0.29965
  Regression -> MSE: 0.000155, MAE: 0.009865, R²: -0.0335
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 88). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.28996 | val 0.42259
  Epoch 020 - train 0.27622 | val 0.41903
  Regression -> MSE: 0.000225, MAE: 0.010771, R²: -0.0019
  Directional -> Accuracy: 0.4839, MCC: -0.0422, F1: 0.2381

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.30423 | val 0.72148
  Epoch 011 - train 0.31472 | val 0.72168
  Regression -> MSE: 0.000375, MAE: 0.016463, R²: 0.0028
  Directional -> Accuracy: 0.4717, MCC: 0.0000, F1: 0.6410

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.31895 | val 0.33941
  Epoch 011 - train 0.32279 | val 0.33840
  Regression -> MSE: 0.000108, MAE: 0.007994, R²: -0.0136
  Directional -> Accuracy: 0.4648, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.29645 | val 0.57464
  Epoch 011 - train 0.29960 | val 0.57666
  Regression -> MSE: 0.000161, MAE: 0.009833, R²: -0.0066
  Directional -> Accuracy: 0.6167, MCC: 0.0000, F1: 0.7629

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.32125 | val 0.32926
  Epoch 011 - train 0.30830 | val 0.34536
  Regression -> MSE: 0.000285, MAE: 0.013686, R²: -0.0611
  Directional -> Accuracy: 0.3896, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.28548 | val 0.44560
  Epoch 018 - train 0.26513 | val 0.48406
  Regression -> MSE: 0.000160, MAE: 0.009040, R²: -0.0849
  Directional -> Accuracy: 0.5606, MCC: 0.2134, F1: 0.5085

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 88). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.34845 | val 0.50479
  Epoch 011 - train 0.33757 | val 0.50380
  Regression -> MSE: 0.000255, MAE: 0.011437, R²: -0.1255
  Directional -> Accuracy: 0.4605, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.32570 | val 0.39703
  Epoch 011 - train 0.33323 | val 0.39851
  Regression -> MSE: 0.000150, MAE: 0.008596, R²: -0.0099
  Directional -> Accuracy: 0.6327, MCC: 0.0000, F1: 0.7750

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 88). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 88). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 88). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.28786 | val 0.37352
  Epoch 011 - train 0.28704 | val 0.37484
  Regression -> MSE: 0.000187, MAE: 0.010616, R²: -0.0569
  Directional -> Accuracy: 0.5224, MCC: 0.1728, F1: 0.1111

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.29903 | val 0.38726
  Epoch 011 - train 0.32028 | val 0.39021
  Regression -> MSE: 0.000084, MAE: 0.006947, R²: 0.0019
  Directional -> Accuracy: 0.5763, MCC: 0.0000, F1: 0.7312

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.31431 | val 0.38288
  Epoch 011 - train 0.31549 | val 0.38243
  Regression -> MSE: 0.000219, MAE: 0.011334, R²: -0.0041
  Directional -> Accuracy: 0.4776, MCC: 0.0000, F1: 0.6465

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.27222 | val 0.23864
  Epoch 020 - train 0.26760 | val 0.21818
  Regression -> MSE: 0.000092, MAE: 0.007896, R²: -0.0084
  Directional -> Accuracy: 0.5439, MCC: 0.1587, F1: 0.4583

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.31565 | val 0.17472
  Epoch 011 - train 0.32943 | val 0.17443
  Regression -> MSE: 0.000131, MAE: 0.009451, R²: -0.0405
  Directional -> Accuracy: 0.4167, MCC: 0.0000, F1: 0.5882

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.33551 | val 0.27527
  Epoch 020 - train 0.30423 | val 0.30043
  Regression -> MSE: 0.000239, MAE: 0.012793, R²: -0.0057
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.7429

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.31416 | val 0.38608
  Epoch 020 - train 0.29507 | val 0.35381
  Regression -> MSE: 0.000190, MAE: 0.007855, R²: -0.1598
  Directional -> Accuracy: 0.5690, MCC: 0.1255, F1: 0.6154

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.32998 | val 0.22282
  Epoch 011 - train 0.31628 | val 0.22286
  Regression -> MSE: 0.000235, MAE: 0.011932, R²: -0.0027
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.29489 | val 0.47930
  Epoch 011 - train 0.29363 | val 0.48041
  Regression -> MSE: 0.000251, MAE: 0.010425, R²: -0.0037
  Directional -> Accuracy: 0.4889, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.33138 | val 0.46469
  Epoch 011 - train 0.33519 | val 0.46524
  Regression -> MSE: 0.000135, MAE: 0.008318, R²: -0.0181
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.31894 | val 0.41328
  Epoch 011 - train 0.32276 | val 0.41205
  Regression -> MSE: 0.000190, MAE: 0.010424, R²: -0.0073
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.27298 | val 0.38750
  Epoch 020 - train 0.27006 | val 0.38137
  Regression -> MSE: 0.000333, MAE: 0.012354, R²: -0.2897
  Directional -> Accuracy: 0.4459, MCC: 0.0025, F1: 0.1633

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 88). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.29066 | val 0.28546
  Epoch 011 - train 0.29739 | val 0.28527
  Regression -> MSE: 0.000162, MAE: 0.010168, R²: 0.0017
  Directional -> Accuracy: 0.4872, MCC: 0.0000, F1: 0.6552

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.29556 | val 0.33405
  Epoch 011 - train 0.27051 | val 0.33589
  Regression -> MSE: 0.000183, MAE: 0.010419, R²: -0.0015
  Directional -> Accuracy: 0.5333, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.30497 | val 0.27939
  Epoch 019 - train 0.29331 | val 0.28102
  Regression -> MSE: 0.000369, MAE: 0.013299, R²: -0.0582
  Directional -> Accuracy: 0.4265, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.33036 | val 0.20584
  Epoch 011 - train 0.32858 | val 0.20602
  Regression -> MSE: 0.000124, MAE: 0.008344, R²: -0.1915
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.31132 | val 0.45540
  Epoch 011 - train 0.31108 | val 0.45860
  Regression -> MSE: 0.000216, MAE: 0.011219, R²: -0.0059
  Directional -> Accuracy: 0.4483, MCC: -0.0880, F1: 0.5000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.34210 | val 0.57305
  Epoch 011 - train 0.32811 | val 0.57333
  Regression -> MSE: 0.000106, MAE: 0.008093, R²: -0.3388
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 88). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 88). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 88). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 88). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.31545 | val 0.24109
  Epoch 011 - train 0.31203 | val 0.24231
  Regression -> MSE: 0.000335, MAE: 0.014931, R²: -0.0218
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 88). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.34771 | val 0.18598
  Epoch 011 - train 0.32895 | val 0.18605
  Regression -> MSE: 0.000242, MAE: 0.011257, R²: -0.0175
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.7000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 88). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 88). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.28641 | val 0.39115
  Epoch 017 - train 0.27705 | val 0.41480
  Regression -> MSE: 0.000080, MAE: 0.006964, R²: 0.0048
  Directional -> Accuracy: 0.5921, MCC: 0.1848, F1: 0.5753

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 88). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 88). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 88). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.32118 | val 0.36546
  Epoch 011 - train 0.30642 | val 0.36694
  Regression -> MSE: 0.000360, MAE: 0.015296, R²: -0.0001
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.29071 | val 0.42392
  Epoch 011 - train 0.28708 | val 0.42346
  Regression -> MSE: 0.000102, MAE: 0.007128, R²: -0.0574
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.32676 | val 0.44589
  Epoch 011 - train 0.32690 | val 0.44934
  Regression -> MSE: 0.000181, MAE: 0.009947, R²: 0.0008
  Directional -> Accuracy: 0.5122, MCC: 0.3145, F1: 0.6000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.29273 | val 0.36081
  Epoch 011 - train 0.28550 | val 0.36118
  Regression -> MSE: 0.000220, MAE: 0.011697, R²: -0.0038
  Directional -> Accuracy: 0.5439, MCC: 0.0000, F1: 0.7045

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.30190 | val 0.35166
  Epoch 011 - train 0.30664 | val 0.35213
  Regression -> MSE: 0.000092, MAE: 0.007649, R²: -0.0091
  Directional -> Accuracy: 0.4828, MCC: 0.0000, F1: 0.6512

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.33745 | val 0.53091
  Epoch 011 - train 0.33247 | val 0.53058
  Regression -> MSE: 0.000162, MAE: 0.010116, R²: -0.0059
  Directional -> Accuracy: 0.4545, MCC: -0.0804, F1: 0.4000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.30542 | val 0.40530
  Epoch 011 - train 0.30161 | val 0.41145
  Regression -> MSE: 0.000125, MAE: 0.008918, R²: -0.0938
  Directional -> Accuracy: 0.4912, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...

[I 2026-02-22 23:14:14,647] Trial 110 finished with value: -0.011537506018247127 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 12, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 64, 'learning_rate': 4.102478881589861e-05, 'weight_decay': 2.1889290215539596e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 0.6495928827032025, 'early_stopping_min_delta': 0.006317318427549584}. Best is trial 90 with value: -0.011414558399902668.

  Epoch 010 - train 0.32472 | val 0.48230
  Epoch 011 - train 0.31513 | val 0.48262
  Regression -> MSE: 0.000241, MAE: 0.012289, R²: -0.0324
  Directional -> Accuracy: 0.5161, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.42241 | val 0.76889
  Epoch 020 - train 0.40744 | val 0.76141
  Epoch 028 - train 0.40511 | val 0.78624
  Regression -> MSE: 0.000264, MAE: 0.013064, R²: -0.0655
  Directional -> Accuracy: 0.4416, MCC: -0.1186, F1: 0.4110

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.42026 | val 0.45762
  Epoch 016 - train 0.39561 | val 0.49260
  Regression -> MSE: 0.000719, MAE: 0.019932, R²: -0.0508
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.47046 | val 0.97550
  Epoch 020 - train 0.45267 | val 0.94485
  Epoch 030 - train 0.44894 | val 0.92622
  Regression -> MSE: 0.000311, MAE: 0.014529, R²: -0.0036
  Directional -> Accuracy: 0.5532, MCC: 0.1572, F1: 0.7042

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.34253 | val 0.65300
  Epoch 016 - train 0.33902 | val 0.70718
  Regression -> MSE: 0.000397, MAE: 0.015414, R²: -0.1359
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.41062 | val 0.43790
  Epoch 020 - train 0.40027 | val 0.48844
  Epoch 024 - train 0.40513 | val 0.48616
  Regression -> MSE: 0.000203, MAE: 0.009928, R²: 0.0036
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.42386 | val 1.12701
  Epoch 020 - train 0.40480 | val 1.20476
  Epoch 025 - train 0.39974 | val 1.23220
  Regression -> MSE: 0.000552, MAE: 0.018098, R²: 0.0051
  Directional -> Accuracy: 0.5532, MCC: 0.1357, F1: 0.2759

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.43968 | val 0.66374
  Epoch 016 - train 0.43621 | val 0.67615
  Regression -> MSE: 0.000246, MAE: 0.011904, R²: -0.0038
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.40574 | val 0.76410
  Epoch 016 - train 0.40088 | val 0.82746
  Regression -> MSE: 0.000651, MAE: 0.020254, R²: -0.0899
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.42760 | val 0.57848
  Epoch 016 - train 0.41401 | val 0.61529
  Regression -> MSE: 0.000400, MAE: 0.016056, R²: -0.0427
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.42925 | val 0.73449
  Epoch 016 - train 0.41922 | val 0.74784
  Regression -> MSE: 0.000246, MAE: 0.011633, R²: -0.0184
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.40783 | val 1.13237
  Epoch 016 - train 0.39126 | val 1.65112
  Regression -> MSE: 0.000328, MAE: 0.013633, R²: -0.0546
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.45154 | val 0.62803
  Epoch 016 - train 0.43796 | val 0.65048
  Regression -> MSE: 0.000675, MAE: 0.019436, R²: 0.0028
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.42192 | val 0.58755
  Epoch 016 - train 0.41298 | val 0.88197
  Regression -> MSE: 0.000141, MAE: 0.009345, R²: -0.0207
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.39326 | val 0.71314
  Epoch 020 - train 0.36375 | val 0.69902
  Epoch 030 - train 0.35892 | val 0.68996
  Regression -> MSE: 0.000234, MAE: 0.011214, R²: -0.0384
  Directional -> Accuracy: 0.5574, MCC: 0.1332, F1: 0.4490

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.44498 | val 1.41024
  Epoch 016 - train 0.41533 | val 1.51529
  Regression -> MSE: 0.000363, MAE: 0.016230, R²: -0.0023
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.44365 | val 0.51831
  Epoch 016 - train 0.42371 | val 0.54861
  Regression -> MSE: 0.000108, MAE: 0.007944, R²: -0.0054
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.39915 | val 1.11800
  Epoch 016 - train 0.39604 | val 1.24583
  Regression -> MSE: 0.000157, MAE: 0.009865, R²: -0.0082
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.43297 | val 0.54739
  Epoch 016 - train 0.44176 | val 0.53791
  Regression -> MSE: 0.000272, MAE: 0.013041, R²: -0.0008
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.35234 | val 0.70526
  Epoch 020 - train 0.34597 | val 0.70244
  Epoch 024 - train 0.33634 | val 0.70809
  Regression -> MSE: 0.000196, MAE: 0.010288, R²: -0.3086
  Directional -> Accuracy: 0.4769, MCC: 0.1610, F1: 0.2273

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.41839 | val 0.93264
  Epoch 020 - train 0.40564 | val 0.98012
  Regression -> MSE: 0.000272, MAE: 0.011791, R²: -0.2011
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.45536 | val 0.67470
  Epoch 020 - train 0.42992 | val 0.69742
  Epoch 024 - train 0.43520 | val 0.70700
  Regression -> MSE: 0.000154, MAE: 0.008927, R²: -0.0728
  Directional -> Accuracy: 0.4167, MCC: 0.0000, F1: 0.2632

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.40251 | val 0.56847
  Epoch 016 - train 0.39535 | val 0.58796
  Regression -> MSE: 0.000170, MAE: 0.010260, R²: -0.0312
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.46038 | val 0.74416
  Epoch 020 - train 0.44410 | val 0.89268
  Regression -> MSE: 0.000087, MAE: 0.007176, R²: -0.0262
  Directional -> Accuracy: 0.5172, MCC: 0.0882, F1: 0.4615

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.42997 | val 0.94222
  Epoch 020 - train 0.42057 | val 1.20627
  Regression -> MSE: 0.000211, MAE: 0.011037, R²: 0.0059
  Directional -> Accuracy: 0.5455, MCC: 0.0787, F1: 0.4643

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.38172 | val 0.34766
  Epoch 020 - train 0.36625 | val 0.35554
  Epoch 022 - train 0.34948 | val 0.35211
  Regression -> MSE: 0.000091, MAE: 0.007904, R²: 0.0145
  Directional -> Accuracy: 0.5893, MCC: 0.1535, F1: 0.7160

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.42404 | val 0.34666
  Epoch 016 - train 0.43744 | val 0.34325
  Regression -> MSE: 0.000110, MAE: 0.009047, R²: -0.0705
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.45288 | val 0.46306
  Epoch 016 - train 0.43756 | val 0.62640
  Regression -> MSE: 0.000232, MAE: 0.012511, R²: -0.0003
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.40854 | val 0.58347
  Epoch 020 - train 0.41031 | val 0.62484
  Epoch 021 - train 0.39783 | val 0.63047
  Regression -> MSE: 0.000184, MAE: 0.008016, R²: -0.1049
  Directional -> Accuracy: 0.4912, MCC: 0.0465, F1: 0.3830

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.47885 | val 0.29141
  Epoch 016 - train 0.43958 | val 0.30116
  Regression -> MSE: 0.000238, MAE: 0.011891, R²: -0.0046
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.44311 | val 0.98856
  Epoch 016 - train 0.43026 | val 0.99947
  Regression -> MSE: 0.000231, MAE: 0.009952, R²: -0.0044
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.45153 | val 0.67572
  Epoch 016 - train 0.41877 | val 0.72444
  Regression -> MSE: 0.000139, MAE: 0.008387, R²: -0.0326
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.42341 | val 0.69272
  Epoch 016 - train 0.41523 | val 0.73314
  Regression -> MSE: 0.000189, MAE: 0.010446, R²: -0.0028
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.36820 | val 0.58850
  Epoch 020 - train 0.36127 | val 0.59482
  Epoch 022 - train 0.36349 | val 0.59471
  Regression -> MSE: 0.000303, MAE: 0.011745, R²: -0.1572
  Directional -> Accuracy: 0.4658, MCC: 0.0914, F1: 0.1333

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.40769 | val 0.36290
  Epoch 020 - train 0.41247 | val 0.44055
  Epoch 024 - train 0.42347 | val 0.59755
  Regression -> MSE: 0.000164, MAE: 0.010344, R²: 0.0135
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.38593 | val 0.55886
  Epoch 016 - train 0.39215 | val 0.66964
  Regression -> MSE: 0.000181, MAE: 0.010266, R²: -0.0032
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.42258 | val 0.43142
  Epoch 016 - train 0.39663 | val 0.46234
  Regression -> MSE: 0.000345, MAE: 0.011699, R²: -0.0083
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.45113 | val 0.23340
  Epoch 020 - train 0.42968 | val 0.29772
  Epoch 026 - train 0.41076 | val 0.32159
  Regression -> MSE: 0.000127, MAE: 0.008337, R²: -0.2053
  Directional -> Accuracy: 0.5814, MCC: 0.2280, F1: 0.4000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.42219 | val 0.85859
  Epoch 020 - train 0.39978 | val 1.03934
  Epoch 021 - train 0.40839 | val 1.04769
  Regression -> MSE: 0.000227, MAE: 0.011662, R²: -0.0395
  Directional -> Accuracy: 0.4386, MCC: -0.1225, F1: 0.5789

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.42866 | val 1.15308
  Epoch 016 - train 0.41138 | val 1.40977
  Regression -> MSE: 0.000086, MAE: 0.007270, R²: -0.1120
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.42205 | val 0.32398
  Epoch 016 - train 0.42005 | val 0.32653
  Regression -> MSE: 0.000327, MAE: 0.014854, R²: -0.0617
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.45893 | val 0.19987
  Epoch 016 - train 0.43459 | val 0.21611
  Regression -> MSE: 0.000245, MAE: 0.011563, R²: -0.0057
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.0000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.37971 | val 0.70192
  Epoch 016 - train 0.37126 | val 0.78186
  Regression -> MSE: 0.000084, MAE: 0.007048, R²: -0.0443
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.43742 | val 0.60540
  Epoch 020 - train 0.42088 | val 0.64097
  Epoch 027 - train 0.41417 | val 0.68656
  Regression -> MSE: 0.000309, MAE: 0.014497, R²: -0.0080
  Directional -> Accuracy: 0.5532, MCC: 0.1224, F1: 0.4615

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.42907 | val 0.57322
  Epoch 020 - train 0.39026 | val 0.55617
  Epoch 030 - train 0.38295 | val 0.53063
  Regression -> MSE: 0.000097, MAE: 0.007094, R²: 0.0145
  Directional -> Accuracy: 0.6591, MCC: 0.3028, F1: 0.7541

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.47002 | val 0.71314
  Epoch 016 - train 0.43338 | val 0.71473
  Regression -> MSE: 0.000172, MAE: 0.009593, R²: -0.0009
  Directional -> Accuracy: 0.6327, MCC: 0.1814, F1: 0.1000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.39983 | val 0.65047
  Epoch 016 - train 0.39416 | val 0.80024
  Regression -> MSE: 0.000225, MAE: 0.011806, R²: -0.0097
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.41323 | val 0.63041
  Epoch 016 - train 0.40180 | val 0.68000
  Regression -> MSE: 0.000094, MAE: 0.007767, R²: -0.0214
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.44752 | val 1.00132
  Epoch 016 - train 0.43320 | val 1.13865
  Regression -> MSE: 0.000165, MAE: 0.010256, R²: -0.0073
  Directional -> Accuracy: 0.5000, MCC: 0.0521, F1: 0.1818

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.43267 | val 0.82017
  Epoch 016 - train 0.40577 | val 0.91416
  Regression -> MSE: 0.000120, MAE: 0.008976, R²: -0.0364
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.44421 | val 0.86486

[I 2026-02-22 23:15:27,529] Trial 111 finished with value: -0.01152575447848015 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.4, 'dropout': 0.0, 'batch_size': 32, 'learning_rate': 0.00013239408706646814, 'weight_decay': 7.823198431898578e-07, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 30, 'huber_delta': 1.559270029427568, 'early_stopping_min_delta': 0.009617678315012292}. Best is trial 90 with value: -0.011414558399902668.

  Epoch 016 - train 0.43566 | val 0.88832
  Regression -> MSE: 0.000238, MAE: 0.012357, R²: -0.0018
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 30
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.41246 | val 0.65888
  Epoch 020 - train 0.40236 | val 0.65524
  Epoch 025 - train 0.39799 | val 0.65462
  Regression -> MSE: 0.000263, MAE: 0.013161, R²: -0.0989
  Directional -> Accuracy: 0.4000, MCC: -0.1943, F1: 0.5455

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 106). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.42020 | val 0.42453
  Epoch 020 - train 0.40455 | val 0.58407
  Epoch 022 - train 0.40240 | val 0.58763
  Regression -> MSE: 0.000713, MAE: 0.019846, R²: -0.0117
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.7429

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 106). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.41422 | val 0.83706
  Epoch 020 - train 0.40807 | val 0.84717
  Epoch 025 - train 0.40597 | val 0.84455
  Regression -> MSE: 0.000326, MAE: 0.014570, R²: -0.0139
  Directional -> Accuracy: 0.6000, MCC: 0.2619, F1: 0.5000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.33896 | val 0.43143
  Epoch 020 - train 0.33264 | val 0.45439
  Epoch 021 - train 0.33225 | val 0.45460
  Regression -> MSE: 0.000358, MAE: 0.014708, R²: -0.0035
  Directional -> Accuracy: 0.5342, MCC: 0.0000, F1: 0.6964

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.42797 | val 0.42470
  Epoch 016 - train 0.42085 | val 0.45376
  Regression -> MSE: 0.000211, MAE: 0.010309, R²: -0.0044
  Directional -> Accuracy: 0.5102, MCC: 0.0000, F1: 0.6757

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.41776 | val 0.84391
  Epoch 020 - train 0.40422 | val 0.90680
  Epoch 025 - train 0.39950 | val 0.92598
  Regression -> MSE: 0.000621, MAE: 0.019407, R²: -0.0803
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.41099 | val 0.57448
  Epoch 020 - train 0.40391 | val 0.60203
  Epoch 021 - train 0.40338 | val 0.60246
  Regression -> MSE: 0.000252, MAE: 0.012202, R²: -0.0031
  Directional -> Accuracy: 0.3881, MCC: -0.1750, F1: 0.4225

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 106). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 106). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.39616 | val 0.31053
  Epoch 016 - train 0.39104 | val 0.35222
  Regression -> MSE: 0.000625, MAE: 0.019719, R²: 0.0006
  Directional -> Accuracy: 0.5610, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.41709 | val 0.58396
  Epoch 016 - train 0.41199 | val 0.59879
  Regression -> MSE: 0.000388, MAE: 0.015717, R²: -0.0379
  Directional -> Accuracy: 0.5532, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 106). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 106). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 106). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.42368 | val 0.64787
  Epoch 016 - train 0.41836 | val 0.66943
  Regression -> MSE: 0.000248, MAE: 0.012065, R²: -0.0001
  Directional -> Accuracy: 0.4265, MCC: 0.0000, F1: 0.5979

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.36930 | val 0.71685
  Epoch 016 - train 0.36552 | val 0.79268
  Regression -> MSE: 0.000327, MAE: 0.013519, R²: -0.0409
  Directional -> Accuracy: 0.5417, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.44548 | val 0.68208
  Epoch 016 - train 0.43899 | val 0.90675
  Regression -> MSE: 0.000702, MAE: 0.019947, R²: -0.0070
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 106). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.41079 | val 0.45902
  Epoch 016 - train 0.40734 | val 0.46229
  Regression -> MSE: 0.000143, MAE: 0.009265, R²: -0.0066
  Directional -> Accuracy: 0.5102, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 106). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.40312 | val 0.68347
  Epoch 016 - train 0.39173 | val 0.69565
  Regression -> MSE: 0.000230, MAE: 0.010900, R²: -0.0078
  Directional -> Accuracy: 0.5085, MCC: 0.0000, F1: 0.6742

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.43258 | val 1.14037
  Epoch 020 - train 0.41768 | val 1.15421
  Epoch 024 - train 0.41388 | val 1.15596
  Regression -> MSE: 0.000376, MAE: 0.016579, R²: -0.0261
  Directional -> Accuracy: 0.4400, MCC: 0.0000, F1: 0.6111

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.42590 | val 0.44941
  Epoch 016 - train 0.42052 | val 0.46387
  Regression -> MSE: 0.000109, MAE: 0.007900, R²: -0.0069
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 106). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.39163 | val 1.00430
  Epoch 016 - train 0.38791 | val 1.07564
  Regression -> MSE: 0.000149, MAE: 0.009372, R²: -0.0009
  Directional -> Accuracy: 0.6140, MCC: 0.0000, F1: 0.7609

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.42042 | val 0.52404
  Epoch 016 - train 0.41344 | val 0.53611
  Regression -> MSE: 0.000281, MAE: 0.013071, R²: -0.0179
  Directional -> Accuracy: 0.5946, MCC: 0.0000, F1: 0.7458

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.35651 | val 0.65720
  Epoch 020 - train 0.34492 | val 0.64574
  Epoch 030 - train 0.33643 | val 0.63673
  Regression -> MSE: 0.000156, MAE: 0.008874, R²: -0.0248
  Directional -> Accuracy: 0.5873, MCC: 0.2508, F1: 0.5517

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 106). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.46467 | val 1.11258
  Epoch 016 - train 0.45502 | val 1.10138
  Regression -> MSE: 0.000225, MAE: 0.010803, R²: -0.0024
  Directional -> Accuracy: 0.5479, MCC: 0.0000, F1: 0.7080

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.40301 | val 0.63781
  Epoch 016 - train 0.39900 | val 0.66001
  Regression -> MSE: 0.000148, MAE: 0.008442, R²: -0.0058
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 106). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 106). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 106). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.37970 | val 0.63799
  Epoch 016 - train 0.37452 | val 0.66945
  Regression -> MSE: 0.000172, MAE: 0.010446, R²: -0.0213
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.43663 | val 0.56763
  Epoch 016 - train 0.42987 | val 0.55368
  Regression -> MSE: 0.000094, MAE: 0.007519, R²: -0.0648
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.41320 | val 0.92288
  Epoch 016 - train 0.40590 | val 1.07851
  Regression -> MSE: 0.000214, MAE: 0.011070, R²: -0.0015
  Directional -> Accuracy: 0.4688, MCC: 0.0000, F1: 0.6383

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.38351 | val 0.38329
  Epoch 016 - train 0.37210 | val 0.38224
  Regression -> MSE: 0.000092, MAE: 0.008041, R²: -0.0047
  Directional -> Accuracy: 0.5370, MCC: 0.0000, F1: 0.6988

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.43030 | val 0.40852
  Epoch 016 - train 0.42674 | val 0.39809
  Regression -> MSE: 0.000119, MAE: 0.009177, R²: -0.2344
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.5902

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.44849 | val 0.29097
  Epoch 016 - train 0.44477 | val 0.31029
  Regression -> MSE: 0.000273, MAE: 0.012938, R²: -0.0012
  Directional -> Accuracy: 0.5918, MCC: 0.0000, F1: 0.7436

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.41016 | val 0.55768
  Epoch 016 - train 0.40617 | val 0.58278
  Regression -> MSE: 0.000182, MAE: 0.007918, R²: -0.0754
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.42847 | val 0.32135
  Epoch 016 - train 0.42357 | val 0.32067
  Regression -> MSE: 0.000251, MAE: 0.012380, R²: -0.0011
  Directional -> Accuracy: 0.5526, MCC: 0.0000, F1: 0.7119

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.40518 | val 0.97912
  Epoch 016 - train 0.40214 | val 1.02922
  Regression -> MSE: 0.000236, MAE: 0.010083, R²: -0.0085
  Directional -> Accuracy: 0.4878, MCC: 0.0000, F1: 0.6557

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.43040 | val 0.53552
  Epoch 016 - train 0.42636 | val 0.56440
  Regression -> MSE: 0.000142, MAE: 0.008424, R²: -0.0176
  Directional -> Accuracy: 0.4634, MCC: 0.0598, F1: 0.1538

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.41954 | val 0.63082
  Epoch 016 - train 0.41395 | val 0.67978
  Regression -> MSE: 0.000188, MAE: 0.010228, R²: -0.0069
  Directional -> Accuracy: 0.5208, MCC: 0.0000, F1: 0.6849

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.36264 | val 0.55935
  Epoch 016 - train 0.35380 | val 0.56006
  Regression -> MSE: 0.000280, MAE: 0.010866, R²: -0.0500
  Directional -> Accuracy: 0.4366, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 106). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.34605 | val 0.49044
  Epoch 020 - train 0.34090 | val 0.47206
  Epoch 028 - train 0.33780 | val 0.47423
  Regression -> MSE: 0.000194, MAE: 0.010909, R²: -0.0329
  Directional -> Accuracy: 0.5000, MCC: 0.1489, F1: 0.6557

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 106). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.40805 | val 0.42180
  Epoch 016 - train 0.39770 | val 0.41544
  Regression -> MSE: 0.000356, MAE: 0.011887, R²: -0.0117
  Directional -> Accuracy: 0.5692, MCC: 0.0000, F1: 0.7255

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.42432 | val 0.24893
  Epoch 016 - train 0.41991 | val 0.25913
  Regression -> MSE: 0.000134, MAE: 0.008825, R²: -0.2156
  Directional -> Accuracy: 0.4750, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.45144 | val 0.73714
  Epoch 016 - train 0.43649 | val 0.87919
  Regression -> MSE: 0.000225, MAE: 0.011475, R²: -0.0041
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.41242 | val 0.95084
  Epoch 016 - train 0.40617 | val 1.08284
  Regression -> MSE: 0.000089, MAE: 0.007294, R²: -0.2539
  Directional -> Accuracy: 0.3778, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 106). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 106). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 106). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 106). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.41735 | val 0.20550
  Epoch 016 - train 0.41052 | val 0.21286
  Regression -> MSE: 0.000319, MAE: 0.013619, R²: -0.0010
  Directional -> Accuracy: 0.6739, MCC: 0.0000, F1: 0.0000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 106). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 106). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 106). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.38777 | val 0.60877
  Epoch 016 - train 0.37965 | val 0.60727
  Regression -> MSE: 0.000077, MAE: 0.006874, R²: 0.0024
  Directional -> Accuracy: 0.4932, MCC: 0.0000, F1: 0.6606

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 106). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 106). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 106). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 106). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.43437 | val 0.65962
  Epoch 020 - train 0.42483 | val 0.67447
  Epoch 027 - train 0.42037 | val 0.68549
  Regression -> MSE: 0.000279, MAE: 0.013874, R²: -0.0021
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.50169 | val 0.52447
  Epoch 016 - train 0.49345 | val 0.55621
  Regression -> MSE: 0.000109, MAE: 0.007208, R²: -0.0552
  Directional -> Accuracy: 0.5854, MCC: 0.0000, F1: 0.7385

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.46184 | val 0.65410
  Epoch 016 - train 0.45556 | val 0.67199
  Regression -> MSE: 0.000185, MAE: 0.010570, R²: -0.0359
  Directional -> Accuracy: 0.3696, MCC: 0.0000, F1: 0.5397

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.37380 | val 0.49346
  Epoch 016 - train 0.36925 | val 0.50565
  Regression -> MSE: 0.000227, MAE: 0.011833, R²: -0.0004
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.39817 | val 0.59244
  Epoch 020 - train 0.38700 | val 0.59287
  Epoch 027 - train 0.38253 | val 0.60269
  Regression -> MSE: 0.000111, MAE: 0.008396, R²: -0.2689
  Directional -> Accuracy: 0.5091, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.42682 | val 0.85639
  Epoch 016 - train 0.42305 | val 0.87905
  Regression -> MSE: 0.000169, MAE: 0.010345, R²: -0.0108
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.40745 | val 0.59012
  Epoch 016 - train 0.40222 | val 0.59646
  Regression -> MSE: 0.000134, MAE: 0.009348, R²: -0.1155
  Directional -> Accuracy: 0.4815, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.43388 | val 0.76807

[I 2026-02-22 23:17:11,074] Trial 112 finished with value: -0.011553261024507296 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 30, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.0, 'dropout': 0.0, 'batch_size': 32, 'learning_rate': 6.341115725365579e-06, 'weight_decay': 3.5563448603402e-06, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 30, 'huber_delta': 1.1488898707146835, 'early_stopping_min_delta': 0.009096591813768738}. Best is trial 90 with value: -0.011414558399902668.

  Epoch 016 - train 0.42855 | val 0.82062
  Regression -> MSE: 0.000254, MAE: 0.012634, R²: -0.0413
  Directional -> Accuracy: 0.5254, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 36
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.38059 | val 0.96137
  Epoch 016 - train 0.37729 | val 1.09626
  Regression -> MSE: 0.000239, MAE: 0.012211, R²: -0.0138
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.6168

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 112). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.38185 | val 0.49738
  Epoch 020 - train 0.36125 | val 0.48570
  Epoch 030 - train 0.32578 | val 0.51940
  Regression -> MSE: 0.000686, MAE: 0.019302, R²: 0.0372
  Directional -> Accuracy: 0.6047, MCC: 0.0000, F1: 0.7536

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for AEP (109 < 112). Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 112). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.39283 | val 1.10280
  Epoch 016 - train 0.38977 | val 1.34446
  Regression -> MSE: 0.000322, MAE: 0.014621, R²: -0.0107
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.32908 | val 0.50140
  Epoch 016 - train 0.32216 | val 0.46715
  Regression -> MSE: 0.000360, MAE: 0.014677, R²: -0.0078
  Directional -> Accuracy: 0.5417, MCC: 0.0000, F1: 0.7027

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.38456 | val 0.42842
  Epoch 020 - train 0.36092 | val 0.50807
  Epoch 021 - train 0.35678 | val 0.48697
  Regression -> MSE: 0.000209, MAE: 0.009924, R²: 0.0070
  Directional -> Accuracy: 0.5833, MCC: 0.1617, F1: 0.6429

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.36096 | val 0.94673
  Epoch 020 - train 0.32315 | val 1.33654
  Epoch 021 - train 0.32072 | val 1.40074
  Regression -> MSE: 0.000580, MAE: 0.018445, R²: -0.0356
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.38197 | val 0.90569
  Epoch 016 - train 0.38603 | val 1.04876
  Regression -> MSE: 0.000256, MAE: 0.012258, R²: -0.0022
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 112). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 112). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.33979 | val 0.57685
  Epoch 016 - train 0.34638 | val 0.76359
  Regression -> MSE: 0.000620, MAE: 0.019599, R²: -0.0706
  Directional -> Accuracy: 0.4359, MCC: 0.0000, F1: 0.6071

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.37524 | val 0.70174
  Epoch 020 - train 0.32922 | val 0.96738
  Epoch 023 - train 0.32584 | val 0.89655
  Regression -> MSE: 0.000360, MAE: 0.015482, R²: 0.0563
  Directional -> Accuracy: 0.5000, MCC: 0.2317, F1: 0.6349

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 112). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 112). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 112). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.38346 | val 1.25535
  Epoch 016 - train 0.36275 | val 1.90016
  Regression -> MSE: 0.000248, MAE: 0.012197, R²: -0.0037
  Directional -> Accuracy: 0.4179, MCC: 0.0000, F1: 0.5895

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.35217 | val 0.92181
  Epoch 016 - train 0.33634 | val 1.05026
  Regression -> MSE: 0.000314, MAE: 0.013323, R²: -0.0075
  Directional -> Accuracy: 0.5532, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.41913 | val 0.60483
  Epoch 016 - train 0.43138 | val 0.72686
  Regression -> MSE: 0.000694, MAE: 0.019644, R²: 0.0019
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 112). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.39013 | val 0.54980
  Epoch 016 - train 0.35580 | val 0.92409
  Regression -> MSE: 0.000149, MAE: 0.009702, R²: -0.0320
  Directional -> Accuracy: 0.4792, MCC: 0.0000, F1: 0.6479

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 112). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.34065 | val 0.79293
  Epoch 016 - train 0.33683 | val 0.96042
  Regression -> MSE: 0.000228, MAE: 0.010610, R²: 0.0052
  Directional -> Accuracy: 0.5172, MCC: 0.0000, F1: 0.6818

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.36711 | val 1.29490
  Epoch 020 - train 0.34236 | val 1.36331
  Epoch 024 - train 0.32676 | val 1.31847
  Regression -> MSE: 0.000373, MAE: 0.016501, R²: 0.0027
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.39260 | val 0.62652
  Epoch 016 - train 0.39416 | val 0.77827
  Regression -> MSE: 0.000109, MAE: 0.008077, R²: 0.0005
  Directional -> Accuracy: 0.4627, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 112). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.37394 | val 1.20001
  Epoch 016 - train 0.36722 | val 1.40846
  Regression -> MSE: 0.000153, MAE: 0.009832, R²: -0.0080
  Directional -> Accuracy: 0.6071, MCC: 0.0000, F1: 0.7556

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.40642 | val 0.78313
  Epoch 016 - train 0.39065 | val 0.55469
  Regression -> MSE: 0.000277, MAE: 0.013089, R²: -0.0006
  Directional -> Accuracy: 0.5890, MCC: 0.0000, F1: 0.7414

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.32150 | val 0.69001
  Epoch 020 - train 0.30045 | val 0.74836
  Epoch 026 - train 0.29000 | val 0.82134
  Regression -> MSE: 0.000183, MAE: 0.010098, R²: -0.1882
  Directional -> Accuracy: 0.4677, MCC: 0.0095, F1: 0.3774

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 112). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.39308 | val 0.91955
  Epoch 020 - train 0.36000 | val 0.97382
  Epoch 021 - train 0.34709 | val 0.97976
  Regression -> MSE: 0.000273, MAE: 0.012055, R²: -0.2015
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.40033 | val 0.70703
  Epoch 016 - train 0.40275 | val 0.82744
  Regression -> MSE: 0.000151, MAE: 0.008539, R²: -0.0221
  Directional -> Accuracy: 0.6000, MCC: 0.0000, F1: 0.7500

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 112). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 112). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 112). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.38487 | val 0.61533
  Epoch 016 - train 0.36391 | val 0.61847
  Regression -> MSE: 0.000177, MAE: 0.010452, R²: -0.0386
  Directional -> Accuracy: 0.6032, MCC: 0.2114, F1: 0.5283

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.41450 | val 0.80073
  Epoch 020 - train 0.39834 | val 0.84433
  Regression -> MSE: 0.000091, MAE: 0.007369, R²: -0.0214
  Directional -> Accuracy: 0.5455, MCC: 0.1352, F1: 0.5283

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.37875 | val 0.65146
  Epoch 020 - train 0.33856 | val 1.03282
  Epoch 025 - train 0.33491 | val 0.92852
  Regression -> MSE: 0.000233, MAE: 0.012381, R²: -0.0753
  Directional -> Accuracy: 0.4762, MCC: -0.0124, F1: 0.6292

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.32463 | val 0.34962
  Epoch 020 - train 0.30057 | val 0.41718
  Epoch 025 - train 0.29389 | val 0.40471
  Regression -> MSE: 0.000117, MAE: 0.008617, R²: -0.2962
  Directional -> Accuracy: 0.5094, MCC: 0.0917, F1: 0.3500

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.41614 | val 0.51217
  Epoch 016 - train 0.41970 | val 0.54644
  Regression -> MSE: 0.000096, MAE: 0.008397, R²: -0.0487
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.40132 | val 0.46081
  Epoch 016 - train 0.36137 | val 1.31614
  Regression -> MSE: 0.000293, MAE: 0.013477, R²: -0.0547
  Directional -> Accuracy: 0.4167, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.38170 | val 0.64165
  Epoch 020 - train 0.34456 | val 0.63719
  Epoch 023 - train 0.35220 | val 0.63907
  Regression -> MSE: 0.000192, MAE: 0.007875, R²: -0.1165
  Directional -> Accuracy: 0.5000, MCC: -0.0028, F1: 0.5263

[49/88] Processing MDT...

Processing MDT (Healthcare)...
Insufficient data for proper time series validation for MDT. Skipping...

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.41870 | val 1.14116
  Epoch 016 - train 0.37251 | val 1.40863
  Regression -> MSE: 0.000240, MAE: 0.010143, R²: -0.0011
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.37253 | val 0.58584
  Epoch 016 - train 0.35489 | val 0.73065
  Regression -> MSE: 0.000143, MAE: 0.008443, R²: -0.0014
  Directional -> Accuracy: 0.5500, MCC: 0.0000, F1: 0.7097

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.37641 | val 0.67308
  Epoch 020 - train 0.35896 | val 0.66302
  Epoch 030 - train 0.33129 | val 0.62507
  Regression -> MSE: 0.000356, MAE: 0.013915, R²: -0.8692
  Directional -> Accuracy: 0.5532, MCC: 0.1357, F1: 0.6769

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.33332 | val 0.64506
  Epoch 020 - train 0.31522 | val 0.70640
  Regression -> MSE: 0.000292, MAE: 0.011387, R²: -0.1003
  Directional -> Accuracy: 0.5714, MCC: 0.2208, F1: 0.4828

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 112). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.31090 | val 0.48572
  Epoch 018 - train 0.33312 | val 0.51898
  Regression -> MSE: 0.000222, MAE: 0.011457, R²: -0.0638
  Directional -> Accuracy: 0.4694, MCC: 0.0000, F1: 0.6389

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 112). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.36098 | val 0.47208
  Epoch 018 - train 0.32404 | val 0.53958
  Regression -> MSE: 0.000361, MAE: 0.012632, R²: -0.0090
  Directional -> Accuracy: 0.4375, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.32004 | val 0.28519
  Epoch 020 - train 0.31355 | val 0.35361
  Epoch 024 - train 0.30921 | val 0.50889
  Regression -> MSE: 0.000111, MAE: 0.007685, R²: -0.1412
  Directional -> Accuracy: 0.6327, MCC: 0.2754, F1: 0.5500

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.35777 | val 0.89000
  Epoch 020 - train 0.34690 | val 0.91946
  Epoch 024 - train 0.32799 | val 0.93936
  Regression -> MSE: 0.000233, MAE: 0.011844, R²: -0.0717
  Directional -> Accuracy: 0.5000, MCC: 0.0408, F1: 0.5846

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.34864 | val 1.28039
  Epoch 016 - train 0.32559 | val 1.53738
  Regression -> MSE: 0.000082, MAE: 0.006996, R²: -0.1425
  Directional -> Accuracy: 0.3864, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 112). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for PPL (108 < 112). Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 112). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 112). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 112). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.33886 | val 0.26242
  Epoch 020 - train 0.40147 | val 0.25932
  Epoch 029 - train 0.30197 | val 0.26262
  Regression -> MSE: 0.000302, MAE: 0.013530, R²: -0.0130
  Directional -> Accuracy: 0.5333, MCC: -0.0328, F1: 0.3226

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 112). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 112). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 112). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.36077 | val 1.23436
  Epoch 016 - train 0.32409 | val 1.62521
  Regression -> MSE: 0.000081, MAE: 0.006936, R²: -0.0386
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 112). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 112). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 112). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 112). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.38727 | val 0.80870
  Epoch 016 - train 0.36927 | val 1.05809
  Regression -> MSE: 0.000289, MAE: 0.013939, R²: -0.0206
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.36064 | val 0.40808
  Epoch 016 - train 0.32983 | val 0.40889
  Regression -> MSE: 0.000109, MAE: 0.007881, R²: -0.0008
  Directional -> Accuracy: 0.4103, MCC: 0.0000, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.38537 | val 0.82615
  Epoch 016 - train 0.38768 | val 1.00995
  Regression -> MSE: 0.000189, MAE: 0.010674, R²: -0.0344
  Directional -> Accuracy: 0.3778, MCC: 0.0000, F1: 0.5484

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.36032 | val 0.58832
  Epoch 016 - train 0.33026 | val 0.61638
  Regression -> MSE: 0.000231, MAE: 0.011946, R²: -0.0012
  Directional -> Accuracy: 0.5472, MCC: 0.0000, F1: 0.7073

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.34160 | val 0.94684
  Epoch 016 - train 0.32448 | val 1.35108
  Regression -> MSE: 0.000087, MAE: 0.007480, R²: 0.0068
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.42117 | val 1.27080
  Epoch 016 - train 0.39506 | val 1.82759
  Regression -> MSE: 0.000171, MAE: 0.010551, R²: -0.0041
  Directional -> Accuracy: 0.4902, MCC: 0.0000, F1: 0.6579

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.35348 | val 0.83685
  Epoch 016 - train 0.36312 | val 1.08294
  Regression -> MSE: 0.000122, MAE: 0.009087, R²: -0.0320
  Directional -> Accuracy: 0.4906, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.39633 | val 1.00693

[I 2026-02-22 23:19:17,949] Trial 113 finished with value: -0.011657796482979864 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 36, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.1, 'batch_size': 32, 'learning_rate': 0.0008255068231040764, 'weight_decay': 6.084164801099738e-07, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 30, 'huber_delta': 1.4360799569537919, 'early_stopping_min_delta': 0.004961169622340664}. Best is trial 90 with value: -0.011414558399902668.

  Epoch 016 - train 0.38531 | val 1.13474
  Regression -> MSE: 0.000249, MAE: 0.012637, R²: -0.0041
  Directional -> Accuracy: 0.5345, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 47/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (47, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.47174 | val 0.68594
  Epoch 020 - train 0.45492 | val 0.68798
  Epoch 022 - train 0.46332 | val 0.68846
  Regression -> MSE: 0.000262, MAE: 0.013086, R²: -0.0591
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.47744 | val 0.52741
  Epoch 016 - train 0.49130 | val 0.75537
  Regression -> MSE: 0.000688, MAE: 0.019401, R²: -0.0048
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.44606 | val 0.90390
  Epoch 016 - train 0.48850 | val 0.98019
  Regression -> MSE: 0.000324, MAE: 0.014561, R²: -0.0428
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.35312 | val 0.42432
  Epoch 016 - train 0.34680 | val 0.43997
  Regression -> MSE: 0.000350, MAE: 0.014574, R²: -0.0024
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.46884 | val 0.45226
  Epoch 016 - train 0.44192 | val 0.47056
  Regression -> MSE: 0.000204, MAE: 0.010127, R²: -0.0002
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.42815 | val 1.03204
  Epoch 020 - train 0.43496 | val 1.09472
  Epoch 027 - train 0.43030 | val 1.12325
  Regression -> MSE: 0.000575, MAE: 0.018590, R²: -0.0367
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.43813 | val 0.61410
  Epoch 016 - train 0.45073 | val 0.61756
  Regression -> MSE: 0.000251, MAE: 0.011955, R²: -0.0220
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.45426 | val 0.73790
  Epoch 016 - train 0.42667 | val 0.76760
  Regression -> MSE: 0.000673, MAE: 0.020574, R²: -0.1262
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.43106 | val 0.56420
  Epoch 016 - train 0.43435 | val 0.58348
  Regression -> MSE: 0.000390, MAE: 0.015937, R²: -0.0174
  Directional -> Accuracy: 0.5102, MCC: 0.0447, F1: 0.5385

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.45129 | val 0.68633
  Epoch 016 - train 0.45307 | val 0.68555
  Regression -> MSE: 0.000241, MAE: 0.011924, R²: -0.0000
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.41884 | val 0.73972
  Epoch 016 - train 0.42006 | val 0.79828
  Regression -> MSE: 0.000318, MAE: 0.013589, R²: -0.0242
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.46776 | val 0.55928
  Epoch 016 - train 0.47021 | val 0.56391
  Regression -> MSE: 0.000679, MAE: 0.019562, R²: -0.0023
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.50704 | val 0.45608
  Epoch 020 - train 0.47985 | val 0.70968
  Regression -> MSE: 0.000139, MAE: 0.009175, R²: -0.0058
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.41307 | val 0.68438
  Epoch 016 - train 0.41018 | val 0.70685
  Regression -> MSE: 0.000225, MAE: 0.010739, R²: 0.0014
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.47206 | val 1.19515
  Epoch 016 - train 0.45907 | val 1.22061
  Regression -> MSE: 0.000372, MAE: 0.015936, R²: -0.0284
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.55073 | val 0.84073
  Epoch 016 - train 0.54623 | val 0.88876
  Regression -> MSE: 0.000112, MAE: 0.008302, R²: -0.0386
  Directional -> Accuracy: 0.4571, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.40722 | val 0.94674
  Epoch 016 - train 0.41968 | val 0.96683
  Regression -> MSE: 0.000156, MAE: 0.009626, R²: -0.0011
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.45918 | val 0.52061
  Epoch 016 - train 0.46453 | val 0.52821
  Regression -> MSE: 0.000282, MAE: 0.013492, R²: -0.0357
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.38326 | val 0.79521
  Epoch 016 - train 0.37848 | val 0.80851
  Regression -> MSE: 0.000161, MAE: 0.008950, R²: -0.0790
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.48146 | val 0.93022
  Epoch 016 - train 0.48914 | val 0.93028
  Regression -> MSE: 0.000244, MAE: 0.011186, R²: -0.0790
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.43367 | val 0.62171
  Epoch 020 - train 0.44042 | val 0.63557
  Epoch 026 - train 0.42605 | val 0.63448
  Regression -> MSE: 0.000153, MAE: 0.008729, R²: -0.0645
  Directional -> Accuracy: 0.5417, MCC: -0.0795, F1: 0.6765

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.40113 | val 0.53122
  Epoch 016 - train 0.39909 | val 0.53201
  Regression -> MSE: 0.000167, MAE: 0.010278, R²: -0.0138
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.49933 | val 0.62841
  Epoch 016 - train 0.49066 | val 0.63226
  Regression -> MSE: 0.000096, MAE: 0.007546, R²: -0.1243
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.46852 | val 0.76502
  Epoch 016 - train 0.47838 | val 0.77759
  Regression -> MSE: 0.000214, MAE: 0.011428, R²: -0.0122
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.43203 | val 0.39302
  Epoch 016 - train 0.42184 | val 0.40006
  Regression -> MSE: 0.000093, MAE: 0.008104, R²: -0.0061
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.44182 | val 0.35395
  Epoch 016 - train 0.46494 | val 0.40794
  Regression -> MSE: 0.000113, MAE: 0.009121, R²: -0.0944
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.47931 | val 0.41516
  Epoch 016 - train 0.46164 | val 0.43725
  Regression -> MSE: 0.000232, MAE: 0.012569, R²: -0.0032
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.45705 | val 0.59016
  Epoch 016 - train 0.44600 | val 0.60687
  Regression -> MSE: 0.000176, MAE: 0.007868, R²: -0.0558
  Directional -> Accuracy: 0.5789, MCC: 0.1193, F1: 0.6667

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.45018 | val 0.32828
  Epoch 016 - train 0.44498 | val 0.37611
  Regression -> MSE: 0.000238, MAE: 0.011900, R²: -0.0045
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.52638 | val 0.85115
  Epoch 016 - train 0.50508 | val 0.85312
  Regression -> MSE: 0.000231, MAE: 0.009866, R²: -0.0021
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.48271 | val 0.58551
  Epoch 016 - train 0.48127 | val 0.58851
  Regression -> MSE: 0.000135, MAE: 0.008238, R²: 0.0008
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.44227 | val 0.61660
  Epoch 016 - train 0.43252 | val 0.62688
  Regression -> MSE: 0.000192, MAE: 0.010413, R²: -0.0209
  Directional -> Accuracy: 0.4600, MCC: -0.0905, F1: 0.5091

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.40013 | val 0.68674
  Epoch 016 - train 0.39641 | val 0.68730
  Regression -> MSE: 0.000278, MAE: 0.010846, R²: -0.0607
  Directional -> Accuracy: 0.4384, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.46939 | val 0.35098
  Epoch 016 - train 0.49525 | val 0.34810
  Regression -> MSE: 0.000168, MAE: 0.010378, R²: -0.0052
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.43076 | val 0.50743
  Epoch 016 - train 0.40633 | val 0.53702
  Regression -> MSE: 0.000184, MAE: 0.010490, R²: -0.0233
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.43329 | val 0.43759
  Epoch 016 - train 0.43041 | val 0.44139
  Regression -> MSE: 0.000344, MAE: 0.011996, R²: -0.0030
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.47791 | val 0.23115
  Epoch 016 - train 0.49413 | val 0.24065
  Regression -> MSE: 0.000114, MAE: 0.008336, R²: -0.0820
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.47684 | val 0.88698
  Epoch 016 - train 0.48075 | val 0.97863
  Regression -> MSE: 0.000220, MAE: 0.011359, R²: -0.0083
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.43559 | val 0.98414
  Epoch 016 - train 0.43285 | val 0.99570
  Regression -> MSE: 0.000088, MAE: 0.007350, R²: -0.1354
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.46969 | val 0.27682
  Epoch 016 - train 0.44103 | val 0.27967
  Regression -> MSE: 0.000312, MAE: 0.014073, R²: -0.0139
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.48376 | val 0.19399
  Epoch 016 - train 0.45396 | val 0.19198
  Regression -> MSE: 0.000246, MAE: 0.011565, R²: -0.0072
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.0000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.47216 | val 0.62051
  Epoch 016 - train 0.46620 | val 0.62006
  Regression -> MSE: 0.000087, MAE: 0.007084, R²: -0.0711
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.47534 | val 0.60531
  Epoch 016 - train 0.44511 | val 0.63544
  Regression -> MSE: 0.000307, MAE: 0.014482, R²: -0.0005
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.45418 | val 0.50642
  Epoch 016 - train 0.46238 | val 0.51210
  Regression -> MSE: 0.000099, MAE: 0.007219, R²: -0.0055
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.49283 | val 0.65374
  Epoch 016 - train 0.48507 | val 0.68660
  Regression -> MSE: 0.000172, MAE: 0.009633, R²: 0.0009
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.41105 | val 0.61154
  Epoch 016 - train 0.41580 | val 0.66270
  Regression -> MSE: 0.000227, MAE: 0.011819, R²: -0.0192
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.44516 | val 0.53500
  Epoch 016 - train 0.41797 | val 0.53287
  Regression -> MSE: 0.000094, MAE: 0.007756, R²: -0.0191
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.46301 | val 0.86946
  Epoch 020 - train 0.47360 | val 1.04223
  Epoch 021 - train 0.46265 | val 1.04226
  Regression -> MSE: 0.000165, MAE: 0.010248, R²: -0.0067
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.48392 | val 0.63277
  Epoch 016 - train 0.47513 | val 0.65181
  Regression -> MSE: 0.000129, MAE: 0.009079, R²: -0.1137
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.44972 | val 0.79920

[I 2026-02-22 23:20:24,991] Trial 114 finished with value: -0.011468104721169419 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.30000000000000004, 'batch_size': 32, 'learning_rate': 3.216143904255897e-06, 'weight_decay': 2.3654957122646747e-06, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 1.2608720918631655, 'early_stopping_min_delta': 0.007473604015368686}. Best is trial 90 with value: -0.011414558399902668.

  Epoch 016 - train 0.46063 | val 0.82751
  Regression -> MSE: 0.000240, MAE: 0.012344, R²: -0.0116
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.47565 | val 0.72007
  Epoch 016 - train 0.46292 | val 0.72661
  Regression -> MSE: 0.000248, MAE: 0.012550, R²: -0.0012
  Directional -> Accuracy: 0.4416, MCC: -0.0778, F1: 0.5567

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.43705 | val 0.42473
  Epoch 016 - train 0.43592 | val 0.43816
  Regression -> MSE: 0.000695, MAE: 0.019509, R²: -0.0152
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.46650 | val 0.87078
  Epoch 020 - train 0.47624 | val 0.86357
  Epoch 030 - train 0.45929 | val 0.85572
  Epoch 040 - train 0.45813 | val 0.85318
  Epoch 048 - train 0.45898 | val 0.85039
  Regression -> MSE: 0.000309, MAE: 0.014430, R²: 0.0030
  Directional -> Accuracy: 0.4894, MCC: -0.0709, F1: 0.6129

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.37842 | val 0.37734
  Epoch 020 - train 0.37184 | val 0.35100
  Epoch 030 - train 0.35890 | val 0.34933
  Epoch 040 - train 0.34013 | val 0.34926
  Epoch 042 - train 0.33972 | val 0.35013
  Regression -> MSE: 0.000341, MAE: 0.014381, R²: 0.0250
  Directional -> Accuracy: 0.5733, MCC: 0.1154, F1: 0.6735

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.47502 | val 0.47742
  Epoch 016 - train 0.45964 | val 0.55749
  Regression -> MSE: 0.000208, MAE: 0.010188, R²: -0.0225
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.41672 | val 1.06131
  Epoch 016 - train 0.42414 | val 1.07215
  Regression -> MSE: 0.000589, MAE: 0.018777, R²: -0.0619
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.46597 | val 0.59652
  Epoch 016 - train 0.44975 | val 0.59938
  Regression -> MSE: 0.000246, MAE: 0.011956, R²: -0.0022
  Directional -> Accuracy: 0.5652, MCC: 0.0355, F1: 0.3182

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.46027 | val 0.61877
  Epoch 016 - train 0.42762 | val 0.63386
  Regression -> MSE: 0.000618, MAE: 0.019670, R²: -0.0351
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.48206 | val 0.52765
  Epoch 016 - train 0.47252 | val 0.54081
  Regression -> MSE: 0.000415, MAE: 0.016321, R²: -0.0809
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.44052 | val 0.66148
  Epoch 016 - train 0.44232 | val 0.66506
  Regression -> MSE: 0.000242, MAE: 0.011760, R²: -0.0013
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.39102 | val 0.73450
  Epoch 016 - train 0.41888 | val 0.75313
  Regression -> MSE: 0.000312, MAE: 0.013690, R²: -0.0019
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.6301

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.46460 | val 0.57210
  Epoch 016 - train 0.46812 | val 0.58230
  Regression -> MSE: 0.000680, MAE: 0.019595, R²: -0.0045
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.55718 | val 0.63146
  Epoch 016 - train 0.52106 | val 1.16512
  Regression -> MSE: 0.000150, MAE: 0.009704, R²: -0.0853
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.50011 | val 0.83479
  Epoch 016 - train 0.47301 | val 0.94090
  Regression -> MSE: 0.000229, MAE: 0.011019, R²: -0.0190
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.45728 | val 1.18849
  Epoch 016 - train 0.44163 | val 1.18757
  Regression -> MSE: 0.000371, MAE: 0.015940, R²: -0.0240
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.49864 | val 0.49898
  Epoch 016 - train 0.48616 | val 0.49702
  Regression -> MSE: 0.000110, MAE: 0.008170, R²: -0.0157
  Directional -> Accuracy: 0.4571, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.44296 | val 0.89602
  Epoch 016 - train 0.44326 | val 0.90452
  Regression -> MSE: 0.000162, MAE: 0.010190, R²: -0.0412
  Directional -> Accuracy: 0.3729, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.44909 | val 0.49653
  Epoch 016 - train 0.45571 | val 0.50011
  Regression -> MSE: 0.000282, MAE: 0.013488, R²: -0.0348
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.39759 | val 0.73104
  Epoch 016 - train 0.36818 | val 0.74150
  Regression -> MSE: 0.000158, MAE: 0.008838, R²: -0.0546
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.44423 | val 0.84056
  Epoch 016 - train 0.46009 | val 0.84065
  Regression -> MSE: 0.000235, MAE: 0.010994, R²: -0.0366
  Directional -> Accuracy: 0.4133, MCC: -0.2045, F1: 0.5000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.46420 | val 0.62810
  Epoch 020 - train 0.46206 | val 0.71377
  Epoch 021 - train 0.48945 | val 0.71112
  Regression -> MSE: 0.000148, MAE: 0.008680, R²: -0.0333
  Directional -> Accuracy: 0.5208, MCC: 0.0759, F1: 0.5490

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.42216 | val 0.52441
  Epoch 016 - train 0.42679 | val 0.52923
  Regression -> MSE: 0.000174, MAE: 0.010258, R²: -0.0538
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.48522 | val 0.57394
  Epoch 020 - train 0.47394 | val 0.57085
  Epoch 023 - train 0.47017 | val 0.57210
  Regression -> MSE: 0.000095, MAE: 0.007449, R²: -0.1149
  Directional -> Accuracy: 0.4483, MCC: 0.0018, F1: 0.2000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.45700 | val 0.59124
  Epoch 020 - train 0.43845 | val 0.61853
  Epoch 022 - train 0.43341 | val 0.62793
  Regression -> MSE: 0.000211, MAE: 0.011163, R²: 0.0051
  Directional -> Accuracy: 0.5000, MCC: 0.0365, F1: 0.5926

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.41595 | val 0.36380
  Epoch 016 - train 0.40649 | val 0.36278
  Regression -> MSE: 0.000093, MAE: 0.008105, R²: -0.0153
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.47711 | val 0.34170
  Epoch 016 - train 0.45252 | val 0.39276
  Regression -> MSE: 0.000110, MAE: 0.009039, R²: -0.0679
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.52518 | val 0.46751
  Epoch 016 - train 0.53174 | val 0.54495
  Regression -> MSE: 0.000234, MAE: 0.012480, R²: -0.0094
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.43623 | val 0.55155
  Epoch 016 - train 0.45977 | val 0.56117
  Regression -> MSE: 0.000183, MAE: 0.008023, R²: -0.1011
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.45048 | val 0.31502
  Epoch 020 - train 0.46673 | val 0.28334
  Epoch 030 - train 0.48428 | val 0.29061
  Epoch 033 - train 0.46643 | val 0.29287
  Regression -> MSE: 0.000236, MAE: 0.011827, R²: 0.0037
  Directional -> Accuracy: 0.5366, MCC: 0.0361, F1: 0.6545

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.45508 | val 0.89359
  Epoch 016 - train 0.44983 | val 0.90407
  Regression -> MSE: 0.000232, MAE: 0.010007, R²: -0.0083
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.45855 | val 0.58393
  Epoch 020 - train 0.47384 | val 0.55959
  Epoch 030 - train 0.44161 | val 0.56005
  Epoch 032 - train 0.43223 | val 0.56022
  Regression -> MSE: 0.000146, MAE: 0.008228, R²: -0.0851
  Directional -> Accuracy: 0.6279, MCC: 0.2522, F1: 0.6522

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.44438 | val 0.62196
  Epoch 016 - train 0.46604 | val 0.64736
  Regression -> MSE: 0.000199, MAE: 0.010704, R²: -0.0586
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.37938 | val 0.63910
  Epoch 016 - train 0.38673 | val 0.63614
  Regression -> MSE: 0.000267, MAE: 0.010551, R²: -0.0187
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.43361 | val 0.34792
  Epoch 020 - train 0.44568 | val 0.34588
  Epoch 029 - train 0.43715 | val 0.39794
  Regression -> MSE: 0.000167, MAE: 0.010389, R²: -0.0031
  Directional -> Accuracy: 0.6053, MCC: 0.2132, F1: 0.5714

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.43247 | val 0.46665
  Epoch 016 - train 0.42634 | val 0.46893
  Regression -> MSE: 0.000182, MAE: 0.010336, R²: -0.0090
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.41418 | val 0.44701
  Epoch 016 - train 0.44026 | val 0.44928
  Regression -> MSE: 0.000349, MAE: 0.012359, R²: -0.0179
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.46992 | val 0.23743
  Epoch 016 - train 0.48809 | val 0.23879
  Regression -> MSE: 0.000120, MAE: 0.008366, R²: -0.1408
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.44393 | val 0.72696
  Epoch 020 - train 0.43837 | val 0.76748
  Regression -> MSE: 0.000221, MAE: 0.011329, R²: -0.0128
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.43647 | val 0.98577
  Epoch 016 - train 0.40167 | val 1.01853
  Regression -> MSE: 0.000084, MAE: 0.007147, R²: -0.0801
  Directional -> Accuracy: 0.4043, MCC: -0.0814, F1: 0.3000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.49421 | val 0.27937
  Epoch 016 - train 0.49287 | val 0.27589
  Regression -> MSE: 0.000311, MAE: 0.014011, R²: -0.0112
  Directional -> Accuracy: 0.4286, MCC: -0.1100, F1: 0.3913

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.49658 | val 0.23015
  Epoch 020 - train 0.49109 | val 0.21121
  Epoch 030 - train 0.46760 | val 0.20381
  Epoch 036 - train 0.48160 | val 0.20475
  Regression -> MSE: 0.000271, MAE: 0.011641, R²: -0.1100
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.46044 | val 0.61031
  Epoch 016 - train 0.43480 | val 0.59756
  Regression -> MSE: 0.000082, MAE: 0.007136, R²: -0.0103
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.45142 | val 0.55687
  Epoch 020 - train 0.45065 | val 0.83194
  Epoch 021 - train 0.44094 | val 0.84974
  Regression -> MSE: 0.000315, MAE: 0.014546, R²: -0.0278
  Directional -> Accuracy: 0.4894, MCC: 0.0000, F1: 0.0000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.44421 | val 0.49238
  Epoch 016 - train 0.44816 | val 0.49817
  Regression -> MSE: 0.000098, MAE: 0.007326, R²: 0.0006
  Directional -> Accuracy: 0.4318, MCC: 0.0000, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.46505 | val 0.64797
  Epoch 016 - train 0.47779 | val 0.66016
  Regression -> MSE: 0.000172, MAE: 0.009732, R²: -0.0008
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.40731 | val 0.59169
  Epoch 016 - train 0.42838 | val 0.69720
  Regression -> MSE: 0.000226, MAE: 0.011812, R²: -0.0114
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.45099 | val 0.58151
  Epoch 016 - train 0.45276 | val 0.60537
  Regression -> MSE: 0.000093, MAE: 0.007668, R²: -0.0042
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.47045 | val 0.82228
  Epoch 016 - train 0.47458 | val 0.83419
  Regression -> MSE: 0.000165, MAE: 0.010326, R²: -0.0076
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.42554 | val 0.69172
  Epoch 016 - train 0.41215 | val 0.77744
  Regression -> MSE: 0.000121, MAE: 0.008970, R²: -0.0436
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.44334 | val 0.89440

[I 2026-02-22 23:21:40,123] Trial 115 finished with value: -0.011464141324031564 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 32, 'learning_rate': 9.022559055560413e-06, 'weight_decay': 2.3979694964092775e-06, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 1.2634511194740197, 'early_stopping_min_delta': 0.007328804961557187}. Best is trial 90 with value: -0.011414558399902668.

  Epoch 016 - train 0.46383 | val 0.99531
  Regression -> MSE: 0.000236, MAE: 0.012426, R²: 0.0035
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.42990 | val 0.66367
  Epoch 016 - train 0.43434 | val 0.71539
  Regression -> MSE: 0.000257, MAE: 0.012916, R²: -0.0384
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.41345 | val 0.38819
  Epoch 020 - train 0.42306 | val 0.37861
  Epoch 030 - train 0.41421 | val 0.38511
  Epoch 031 - train 0.43927 | val 0.38521
  Regression -> MSE: 0.000683, MAE: 0.019440, R²: 0.0028
  Directional -> Accuracy: 0.5435, MCC: 0.1123, F1: 0.5333

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.41333 | val 0.81352
  Epoch 016 - train 0.42296 | val 0.81953
  Regression -> MSE: 0.000311, MAE: 0.014422, R²: -0.0011
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.33270 | val 0.34548
  Epoch 016 - train 0.33395 | val 0.44135
  Regression -> MSE: 0.000350, MAE: 0.014604, R²: -0.0032
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.47883 | val 0.45360
  Epoch 016 - train 0.48497 | val 0.47966
  Regression -> MSE: 0.000208, MAE: 0.010512, R²: -0.0193
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.41883 | val 0.98219
  Epoch 016 - train 0.41035 | val 1.00804
  Regression -> MSE: 0.000592, MAE: 0.018810, R²: -0.0670
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.44065 | val 0.56444
  Epoch 016 - train 0.44049 | val 0.59517
  Regression -> MSE: 0.000247, MAE: 0.011929, R²: -0.0074
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.46671 | val 0.61987
  Epoch 016 - train 0.46329 | val 0.63089
  Regression -> MSE: 0.000637, MAE: 0.020029, R²: -0.0664
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.40005 | val 0.55326
  Epoch 016 - train 0.42058 | val 0.55866
  Regression -> MSE: 0.000386, MAE: 0.016122, R²: -0.0055
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.43008 | val 0.58488
  Epoch 016 - train 0.41985 | val 0.58941
  Regression -> MSE: 0.000243, MAE: 0.012158, R²: -0.0064
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.38896 | val 0.64813
  Epoch 020 - train 0.39045 | val 0.62991
  Epoch 030 - train 0.37951 | val 0.63453
  Regression -> MSE: 0.000349, MAE: 0.013820, R²: -0.1227
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.44108 | val 0.50966
  Epoch 016 - train 0.42709 | val 0.51581
  Regression -> MSE: 0.000679, MAE: 0.019566, R²: -0.0027
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.44220 | val 0.41812
  Epoch 016 - train 0.45225 | val 0.42209
  Regression -> MSE: 0.000143, MAE: 0.009432, R²: -0.0357
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.39719 | val 0.59202
  Epoch 016 - train 0.39170 | val 0.60234
  Regression -> MSE: 0.000228, MAE: 0.010795, R²: -0.0143
  Directional -> Accuracy: 0.4918, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.43606 | val 1.07122
  Epoch 016 - train 0.42603 | val 1.07408
  Regression -> MSE: 0.000373, MAE: 0.015937, R²: -0.0301
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.43563 | val 0.43673
  Epoch 016 - train 0.43448 | val 0.45328
  Regression -> MSE: 0.000110, MAE: 0.007951, R²: -0.0156
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.39531 | val 0.82023
  Epoch 016 - train 0.39556 | val 0.83339
  Regression -> MSE: 0.000158, MAE: 0.009912, R²: -0.0138
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.46000 | val 0.48969
  Epoch 016 - train 0.44693 | val 0.72555
  Regression -> MSE: 0.000297, MAE: 0.014085, R²: -0.0920
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.35647 | val 0.60504
  Epoch 020 - train 0.35470 | val 0.59372
  Epoch 030 - train 0.34529 | val 0.59233
  Epoch 031 - train 0.35689 | val 0.59194
  Regression -> MSE: 0.000164, MAE: 0.009062, R²: -0.0953
  Directional -> Accuracy: 0.6000, MCC: 0.1447, F1: 0.6905

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.40991 | val 0.71075
  Epoch 020 - train 0.44210 | val 0.70581
  Epoch 027 - train 0.41545 | val 0.70341
  Regression -> MSE: 0.000285, MAE: 0.012137, R²: -0.2609
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.41368 | val 0.57328
  Epoch 016 - train 0.43514 | val 0.56809
  Regression -> MSE: 0.000152, MAE: 0.008772, R²: -0.0599
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.52162 | val 0.50158
  Epoch 016 - train 0.51176 | val 0.56682
  Regression -> MSE: 0.000188, MAE: 0.010480, R²: -0.1377
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.45688 | val 0.53370
  Epoch 016 - train 0.43972 | val 0.53302
  Regression -> MSE: 0.000087, MAE: 0.007124, R²: -0.0160
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.45286 | val 0.57690
  Epoch 016 - train 0.44667 | val 0.58467
  Regression -> MSE: 0.000216, MAE: 0.011550, R²: -0.0204
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.39389 | val 0.34694
  Epoch 016 - train 0.38567 | val 0.35260
  Regression -> MSE: 0.000097, MAE: 0.008163, R²: -0.0522
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.43998 | val 0.30315
  Epoch 016 - train 0.42600 | val 0.30255
  Regression -> MSE: 0.000106, MAE: 0.008883, R²: -0.0249
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.46328 | val 0.39564
  Epoch 016 - train 0.48372 | val 0.40275
  Regression -> MSE: 0.000232, MAE: 0.012577, R²: -0.0032
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.41242 | val 0.51028
  Epoch 016 - train 0.40392 | val 0.50808
  Regression -> MSE: 0.000189, MAE: 0.008152, R²: -0.1351
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.43432 | val 0.29231
  Epoch 016 - train 0.43694 | val 0.29308
  Regression -> MSE: 0.000236, MAE: 0.011859, R²: 0.0008
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.40205 | val 0.81483
  Epoch 016 - train 0.41244 | val 0.81802
  Regression -> MSE: 0.000232, MAE: 0.009999, R²: -0.0088
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.46002 | val 0.53975
  Epoch 016 - train 0.46083 | val 0.53807
  Regression -> MSE: 0.000135, MAE: 0.008234, R²: 0.0002
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.42367 | val 0.56232
  Epoch 016 - train 0.43155 | val 0.56413
  Regression -> MSE: 0.000199, MAE: 0.010698, R²: -0.0585
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.39590 | val 0.53545
  Epoch 016 - train 0.39092 | val 0.54748
  Regression -> MSE: 0.000265, MAE: 0.010517, R²: -0.0105
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.42596 | val 0.33878
  Epoch 016 - train 0.43725 | val 0.33900
  Regression -> MSE: 0.000171, MAE: 0.010384, R²: -0.0256
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.41621 | val 0.44677
  Epoch 016 - train 0.41727 | val 0.44904
  Regression -> MSE: 0.000180, MAE: 0.010269, R²: -0.0024
  Directional -> Accuracy: 0.5682, MCC: 0.1412, F1: 0.5778

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.39368 | val 0.40381
  Epoch 016 - train 0.39920 | val 0.42274
  Regression -> MSE: 0.000346, MAE: 0.012169, R²: -0.0099
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.45489 | val 0.23293
  Epoch 016 - train 0.40862 | val 0.23661
  Regression -> MSE: 0.000121, MAE: 0.008386, R²: -0.1515
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.42867 | val 0.66012
  Epoch 016 - train 0.40994 | val 0.67024
  Regression -> MSE: 0.000221, MAE: 0.011376, R²: -0.0094
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.42419 | val 0.89197
  Epoch 016 - train 0.41459 | val 0.89589
  Regression -> MSE: 0.000087, MAE: 0.007295, R²: -0.1194
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.41058 | val 0.27864
  Epoch 016 - train 0.40534 | val 0.28283
  Regression -> MSE: 0.000313, MAE: 0.014126, R²: -0.0170
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.46300 | val 0.19010
  Epoch 016 - train 0.48509 | val 0.18930
  Regression -> MSE: 0.000249, MAE: 0.011534, R²: -0.0227
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.40192 | val 0.52882
  Epoch 016 - train 0.38837 | val 0.56202
  Regression -> MSE: 0.000081, MAE: 0.007059, R²: -0.0020
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.46500 | val 0.53812
  Epoch 016 - train 0.45117 | val 0.54276
  Regression -> MSE: 0.000311, MAE: 0.014528, R²: -0.0121
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.42569 | val 0.52128
  Epoch 020 - train 0.41785 | val 0.50945
  Epoch 030 - train 0.40647 | val 0.48216
  Epoch 040 - train 0.42422 | val 0.45635
  Epoch 050 - train 0.41165 | val 0.44604
  Regression -> MSE: 0.000097, MAE: 0.007111, R²: 0.0090
  Directional -> Accuracy: 0.5455, MCC: 0.0389, F1: 0.6429

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.46555 | val 0.58612
  Epoch 016 - train 0.46457 | val 0.58487
  Regression -> MSE: 0.000172, MAE: 0.009739, R²: -0.0015
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.37779 | val 0.51349
  Epoch 016 - train 0.38020 | val 0.51795
  Regression -> MSE: 0.000229, MAE: 0.011871, R²: -0.0266
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.42278 | val 0.47880
  Epoch 016 - train 0.41835 | val 0.47844
  Regression -> MSE: 0.000093, MAE: 0.007635, R²: -0.0039
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.41575 | val 0.82176
  Epoch 016 - train 0.42171 | val 0.85096
  Regression -> MSE: 0.000169, MAE: 0.010301, R²: -0.0342
  Directional -> Accuracy: 0.4815, MCC: 0.0000, F1: 0.0000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.39963 | val 0.57963
  Epoch 016 - train 0.40257 | val 0.59188
  Regression -> MSE: 0.000117, MAE: 0.008948, R²: -0.0118
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.42519 | val 0.71511

[I 2026-02-22 23:22:32,739] Trial 116 finished with value: -0.011514971462280879 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.30000000000000004, 'batch_size': 64, 'learning_rate': 3.546723801202319e-06, 'weight_decay': 5.3610384680007185e-06, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 1.0797674599031402, 'early_stopping_min_delta': 0.007486702340677511}. Best is trial 90 with value: -0.011414558399902668.

  Epoch 016 - train 0.42280 | val 0.79189
  Regression -> MSE: 0.000237, MAE: 0.012367, R²: -0.0002
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.41784 | val 0.71790
  Epoch 016 - train 0.43270 | val 0.73042
  Regression -> MSE: 0.000252, MAE: 0.012722, R²: -0.0179
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.46767 | val 0.45116
  Epoch 016 - train 0.45887 | val 0.71088
  Regression -> MSE: 0.000717, MAE: 0.019903, R²: -0.0467
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.44254 | val 0.83141
  Epoch 016 - train 0.43718 | val 0.85062
  Regression -> MSE: 0.000311, MAE: 0.014440, R²: -0.0015
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.33794 | val 0.38397
  Epoch 016 - train 0.32498 | val 0.40267
  Regression -> MSE: 0.000350, MAE: 0.014600, R²: -0.0018
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.44262 | val 0.45765
  Epoch 016 - train 0.45056 | val 0.52907
  Regression -> MSE: 0.000205, MAE: 0.010175, R²: -0.0044
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.47532 | val 0.97025
  Epoch 020 - train 0.44252 | val 1.36197
  Epoch 022 - train 0.42569 | val 1.39911
  Regression -> MSE: 0.000565, MAE: 0.018255, R²: -0.0176
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.44256 | val 0.59968
  Epoch 016 - train 0.42760 | val 0.59833
  Regression -> MSE: 0.000246, MAE: 0.012085, R²: -0.0010
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.53289 | val 0.77012
  Epoch 016 - train 0.48914 | val 0.91605
  Regression -> MSE: 0.000686, MAE: 0.020812, R²: -0.1485
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.42234 | val 0.52807
  Epoch 016 - train 0.40946 | val 0.54235
  Regression -> MSE: 0.000396, MAE: 0.015986, R²: -0.0332
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.43333 | val 0.59413
  Epoch 016 - train 0.43897 | val 0.59922
  Regression -> MSE: 0.000243, MAE: 0.011691, R²: -0.0076
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.39319 | val 0.65103
  Epoch 020 - train 0.43349 | val 0.64966
  Epoch 025 - train 0.41598 | val 0.66123
  Regression -> MSE: 0.000321, MAE: 0.013621, R²: -0.0332
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.44788 | val 0.58074
  Epoch 016 - train 0.45221 | val 0.60400
  Regression -> MSE: 0.000678, MAE: 0.019528, R²: -0.0014
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.41950 | val 0.49835
  Epoch 016 - train 0.43175 | val 0.57936
  Regression -> MSE: 0.000139, MAE: 0.009017, R²: -0.0089
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.37882 | val 0.62378
  Epoch 016 - train 0.40891 | val 0.63580
  Regression -> MSE: 0.000226, MAE: 0.010701, R²: -0.0054
  Directional -> Accuracy: 0.4918, MCC: -0.0141, F1: 0.4561

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.43612 | val 1.17313
  Epoch 016 - train 0.43214 | val 1.33864
  Regression -> MSE: 0.000363, MAE: 0.016044, R²: -0.0024
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.44800 | val 0.44803
  Epoch 016 - train 0.43411 | val 0.45034
  Regression -> MSE: 0.000111, MAE: 0.007960, R²: -0.0301
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.41824 | val 0.83437
  Epoch 020 - train 0.41401 | val 0.82859
  Epoch 030 - train 0.39899 | val 0.83066
  Epoch 035 - train 0.39548 | val 0.82721
  Regression -> MSE: 0.000164, MAE: 0.010102, R²: -0.0508
  Directional -> Accuracy: 0.5593, MCC: 0.0402, F1: 0.6579

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.44521 | val 0.47956
  Epoch 016 - train 0.44306 | val 0.48878
  Regression -> MSE: 0.000275, MAE: 0.013172, R²: -0.0091
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.37996 | val 0.63054
  Epoch 020 - train 0.36980 | val 0.62798
  Regression -> MSE: 0.000164, MAE: 0.008944, R²: -0.0948
  Directional -> Accuracy: 0.5385, MCC: 0.1274, F1: 0.5161

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.42328 | val 0.76593
  Epoch 020 - train 0.42024 | val 0.78105
  Regression -> MSE: 0.000233, MAE: 0.010836, R²: -0.0291
  Directional -> Accuracy: 0.5733, MCC: 0.1808, F1: 0.5294

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.44683 | val 0.69574
  Epoch 016 - train 0.43971 | val 0.85052
  Regression -> MSE: 0.000143, MAE: 0.008314, R²: -0.0008
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.43800 | val 0.57802
  Epoch 016 - train 0.41951 | val 0.58926
  Regression -> MSE: 0.000165, MAE: 0.010635, R²: -0.0015
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.44781 | val 0.54709
  Epoch 020 - train 0.45087 | val 0.54718
  Epoch 023 - train 0.44838 | val 0.54739
  Regression -> MSE: 0.000093, MAE: 0.007429, R²: -0.0879
  Directional -> Accuracy: 0.4655, MCC: 0.0286, F1: 0.2791

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.41907 | val 0.57039
  Epoch 016 - train 0.41603 | val 0.56420
  Regression -> MSE: 0.000212, MAE: 0.011139, R²: -0.0006
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.40609 | val 0.36205
  Epoch 016 - train 0.39924 | val 0.36031
  Regression -> MSE: 0.000100, MAE: 0.008208, R²: -0.0811
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.43932 | val 0.32330
  Epoch 016 - train 0.44766 | val 0.32427
  Regression -> MSE: 0.000113, MAE: 0.009108, R²: -0.0913
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.46751 | val 0.46685
  Epoch 016 - train 0.46900 | val 0.55496
  Regression -> MSE: 0.000245, MAE: 0.012972, R²: -0.0582
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.40539 | val 0.51965
  Epoch 020 - train 0.41237 | val 0.51328
  Epoch 027 - train 0.42281 | val 0.51442
  Regression -> MSE: 0.000453, MAE: 0.016383, R²: -1.7213
  Directional -> Accuracy: 0.4737, MCC: 0.1685, F1: 0.1176

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.46423 | val 0.35576
  Epoch 016 - train 0.46608 | val 0.45205
  Regression -> MSE: 0.000240, MAE: 0.012013, R²: -0.0140
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.42699 | val 0.87328
  Epoch 016 - train 0.44887 | val 0.92938
  Regression -> MSE: 0.000234, MAE: 0.010104, R²: -0.0157
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.48232 | val 0.54328
  Epoch 016 - train 0.46417 | val 0.60045
  Regression -> MSE: 0.000135, MAE: 0.008179, R²: 0.0025
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.44624 | val 0.58871
  Epoch 016 - train 0.45363 | val 0.60412
  Regression -> MSE: 0.000192, MAE: 0.010392, R²: -0.0198
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.36209 | val 0.57934
  Epoch 016 - train 0.36457 | val 0.57962
  Regression -> MSE: 0.000266, MAE: 0.010526, R²: -0.0163
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.40939 | val 0.35401
  Epoch 016 - train 0.40426 | val 0.35395
  Regression -> MSE: 0.000167, MAE: 0.010362, R²: -0.0037
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.39429 | val 0.46952
  Epoch 016 - train 0.35857 | val 0.49606
  Regression -> MSE: 0.000180, MAE: 0.010261, R²: -0.0028
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.43753 | val 0.41225
  Epoch 016 - train 0.41654 | val 0.41644
  Regression -> MSE: 0.000345, MAE: 0.012021, R²: -0.0059
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.45717 | val 0.24896
  Epoch 016 - train 0.45791 | val 0.24373
  Regression -> MSE: 0.000128, MAE: 0.008524, R²: -0.2163
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.43291 | val 0.69202
  Epoch 016 - train 0.41572 | val 0.70236
  Regression -> MSE: 0.000219, MAE: 0.011278, R²: -0.0009
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.43193 | val 0.93683
  Epoch 016 - train 0.44751 | val 1.00142
  Regression -> MSE: 0.000082, MAE: 0.007071, R²: -0.0596
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.42381 | val 0.30538
  Epoch 016 - train 0.42891 | val 0.29987
  Regression -> MSE: 0.000322, MAE: 0.014619, R²: -0.0465
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.48211 | val 0.21554
  Epoch 016 - train 0.48042 | val 0.21730
  Regression -> MSE: 0.000256, MAE: 0.011463, R²: -0.0497
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.41638 | val 0.55348
  Epoch 016 - train 0.40508 | val 0.55611
  Regression -> MSE: 0.000081, MAE: 0.007069, R²: -0.0052
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.47401 | val 0.56935
  Epoch 020 - train 0.43637 | val 0.55434
  Epoch 029 - train 0.45282 | val 0.56499
  Regression -> MSE: 0.000337, MAE: 0.015083, R²: -0.0995
  Directional -> Accuracy: 0.4681, MCC: -0.1506, F1: 0.0000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.45624 | val 0.55297
  Epoch 016 - train 0.46687 | val 0.57545
  Regression -> MSE: 0.000103, MAE: 0.007110, R²: -0.0526
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.49297 | val 0.61990
  Epoch 016 - train 0.47564 | val 0.62375
  Regression -> MSE: 0.000176, MAE: 0.010262, R²: -0.0269
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.43509 | val 0.51523
  Epoch 016 - train 0.42771 | val 0.51540
  Regression -> MSE: 0.000224, MAE: 0.011786, R²: -0.0024
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.42494 | val 0.50581
  Epoch 016 - train 0.41336 | val 0.50349
  Regression -> MSE: 0.000093, MAE: 0.007663, R²: -0.0039
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.46995 | val 0.77659
  Epoch 016 - train 0.46930 | val 0.79236
  Regression -> MSE: 0.000164, MAE: 0.010264, R²: -0.0019
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.44101 | val 0.57009
  Epoch 020 - train 0.42315 | val 0.57381
  Epoch 023 - train 0.41877 | val 0.57725
  Regression -> MSE: 0.000123, MAE: 0.008881, R²: -0.0632
  Directional -> Accuracy: 0.5000, MCC: 0.0227, F1: 0.3333

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.43988 | val 0.72573

[I 2026-02-22 23:23:44,624] Trial 117 finished with value: -0.011641838206359119 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 32, 'learning_rate': 8.352642265486958e-06, 'weight_decay': 2.5516233740399966e-06, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 1.1364468300681834, 'early_stopping_min_delta': 0.007647861751036166}. Best is trial 90 with value: -0.011414558399902668.

  Epoch 016 - train 0.44566 | val 0.74828
  Regression -> MSE: 0.000246, MAE: 0.012379, R²: -0.0367
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.41234 | val 0.60076
  Epoch 016 - train 0.40715 | val 0.59931
  Regression -> MSE: 0.000266, MAE: 0.013160, R²: -0.0755
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.45165 | val 0.35810
  Epoch 016 - train 0.43136 | val 0.37674
  Regression -> MSE: 0.000731, MAE: 0.020116, R²: -0.0683
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.38442 | val 0.70290
  Epoch 016 - train 0.40491 | val 0.70210
  Regression -> MSE: 0.000311, MAE: 0.014421, R²: -0.0030
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.32430 | val 0.36409
  Epoch 016 - train 0.32442 | val 0.52893
  Regression -> MSE: 0.000356, MAE: 0.014682, R²: -0.0193
  Directional -> Accuracy: 0.5333, MCC: 0.0188, F1: 0.6465

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.42965 | val 0.47958
  Epoch 016 - train 0.41906 | val 0.60581
  Regression -> MSE: 0.000203, MAE: 0.010169, R²: 0.0053
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.35938 | val 0.88930
  Epoch 016 - train 0.37146 | val 0.97175
  Regression -> MSE: 0.000575, MAE: 0.018429, R²: -0.0363
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.41670 | val 0.50428
  Epoch 016 - train 0.40249 | val 0.50707
  Regression -> MSE: 0.000249, MAE: 0.011984, R²: -0.0144
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.40393 | val 0.49730
  Epoch 016 - train 0.40333 | val 0.50444
  Regression -> MSE: 0.000609, MAE: 0.019431, R²: -0.0190
  Directional -> Accuracy: 0.6364, MCC: 0.2082, F1: 0.3333

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.39014 | val 0.45542
  Epoch 016 - train 0.37933 | val 0.45489
  Regression -> MSE: 0.000406, MAE: 0.016181, R²: -0.0583
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.38424 | val 0.52763
  Epoch 016 - train 0.40156 | val 0.53170
  Regression -> MSE: 0.000243, MAE: 0.011802, R²: -0.0047
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.36639 | val 0.61491
  Epoch 016 - train 0.35356 | val 0.64254
  Regression -> MSE: 0.000308, MAE: 0.013649, R²: 0.0079
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.6301

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.44314 | val 0.48321
  Epoch 016 - train 0.43831 | val 0.56442
  Regression -> MSE: 0.000687, MAE: 0.019648, R²: -0.0145
  Directional -> Accuracy: 0.4483, MCC: -0.2335, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.37932 | val 0.39504
  Epoch 016 - train 0.39404 | val 0.39942
  Regression -> MSE: 0.000139, MAE: 0.009036, R²: -0.0045
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.34016 | val 0.54748
  Epoch 016 - train 0.33579 | val 0.56017
  Regression -> MSE: 0.000225, MAE: 0.010718, R²: -0.0009
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.36197 | val 0.91566
  Epoch 016 - train 0.38025 | val 0.92104
  Regression -> MSE: 0.000369, MAE: 0.015950, R²: -0.0198
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.50297 | val 0.46524
  Epoch 016 - train 0.49008 | val 0.52735
  Regression -> MSE: 0.000110, MAE: 0.007989, R²: -0.0206
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.36388 | val 0.70233
  Epoch 020 - train 0.35841 | val 0.71474
  Epoch 025 - train 0.33865 | val 0.71426
  Regression -> MSE: 0.000156, MAE: 0.009567, R²: 0.0002
  Directional -> Accuracy: 0.5932, MCC: 0.0253, F1: 0.7209

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.41261 | val 0.42758
  Epoch 016 - train 0.40265 | val 0.51316
  Regression -> MSE: 0.000279, MAE: 0.012937, R²: -0.0238
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.36351 | val 0.53300
  Epoch 020 - train 0.36918 | val 0.52523
  Epoch 030 - train 0.35683 | val 0.52323
  Epoch 039 - train 0.32986 | val 0.52150
  Regression -> MSE: 0.000186, MAE: 0.010178, R²: -0.2438
  Directional -> Accuracy: 0.4769, MCC: -0.1464, F1: 0.6047

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.38316 | val 0.61769
  Epoch 016 - train 0.38818 | val 0.62629
  Regression -> MSE: 0.000235, MAE: 0.011070, R²: -0.0400
  Directional -> Accuracy: 0.4000, MCC: -0.2462, F1: 0.5055

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.43233 | val 0.53804
  Epoch 016 - train 0.42552 | val 0.62897
  Regression -> MSE: 0.000147, MAE: 0.008534, R²: -0.0245
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.35992 | val 0.45335
  Epoch 016 - train 0.35526 | val 0.45957
  Regression -> MSE: 0.000171, MAE: 0.010245, R²: -0.0324
  Directional -> Accuracy: 0.5152, MCC: 0.0312, F1: 0.5676

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.41613 | val 0.49327
  Epoch 016 - train 0.40561 | val 0.50919
  Regression -> MSE: 0.000089, MAE: 0.007241, R²: -0.0400
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.38886 | val 0.47477
  Epoch 020 - train 0.38423 | val 0.48676
  Epoch 022 - train 0.38650 | val 0.48688
  Regression -> MSE: 0.000213, MAE: 0.011287, R²: -0.0039
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.37656 | val 0.34181
  Epoch 016 - train 0.37004 | val 0.36124
  Regression -> MSE: 0.000095, MAE: 0.008113, R²: -0.0360
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.41178 | val 0.28045
  Epoch 016 - train 0.41955 | val 0.28800
  Regression -> MSE: 0.000105, MAE: 0.008836, R²: -0.0208
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.43965 | val 0.35212
  Epoch 016 - train 0.41583 | val 0.35579
  Regression -> MSE: 0.000233, MAE: 0.012652, R²: -0.0086
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.39239 | val 0.45318
  Epoch 020 - train 0.37379 | val 0.44496
  Epoch 030 - train 0.38060 | val 0.44328
  Epoch 040 - train 0.35926 | val 0.44225
  Regression -> MSE: 0.000235, MAE: 0.010134, R²: -0.4126
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.39818 | val 0.27204
  Epoch 020 - train 0.40785 | val 0.31033
  Epoch 021 - train 0.36633 | val 0.32204
  Regression -> MSE: 0.000237, MAE: 0.011839, R²: 0.0001
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.38792 | val 0.70584
  Epoch 016 - train 0.40294 | val 0.70561
  Regression -> MSE: 0.000233, MAE: 0.010042, R²: -0.0130
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.44476 | val 0.47953
  Epoch 020 - train 0.44013 | val 0.48032
  Epoch 028 - train 0.41845 | val 0.48970
  Regression -> MSE: 0.000146, MAE: 0.008502, R²: -0.0841
  Directional -> Accuracy: 0.6047, MCC: 0.2242, F1: 0.5854

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.47334 | val 0.59313
  Epoch 016 - train 0.48138 | val 0.67415
  Regression -> MSE: 0.000188, MAE: 0.010480, R²: 0.0014
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.31563 | val 0.46085
  Epoch 020 - train 0.32063 | val 0.48073
  Regression -> MSE: 0.000279, MAE: 0.010969, R²: -0.0648
  Directional -> Accuracy: 0.4932, MCC: 0.1111, F1: 0.2745

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.37903 | val 0.30891
  Epoch 016 - train 0.39279 | val 0.30878
  Regression -> MSE: 0.000166, MAE: 0.010349, R²: 0.0054
  Directional -> Accuracy: 0.4737, MCC: -0.0555, F1: 0.3750

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.37444 | val 0.42449
  Epoch 016 - train 0.32727 | val 0.43659
  Regression -> MSE: 0.000185, MAE: 0.010522, R²: -0.0294
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.38787 | val 0.37508
  Epoch 016 - train 0.39506 | val 0.39297
  Regression -> MSE: 0.000346, MAE: 0.011707, R²: -0.0111
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.43100 | val 0.20501
  Epoch 016 - train 0.42167 | val 0.20202
  Regression -> MSE: 0.000111, MAE: 0.008313, R²: -0.0522
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.39395 | val 0.57264
  Epoch 016 - train 0.40404 | val 0.58086
  Regression -> MSE: 0.000220, MAE: 0.011355, R²: -0.0044
  Directional -> Accuracy: 0.4211, MCC: -0.1685, F1: 0.3529

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.38543 | val 0.76136
  Epoch 016 - train 0.40355 | val 0.77014
  Regression -> MSE: 0.000095, MAE: 0.007580, R²: -0.2174
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.36616 | val 0.26785
  Epoch 016 - train 0.38548 | val 0.28036
  Regression -> MSE: 0.000311, MAE: 0.013968, R²: -0.0104
  Directional -> Accuracy: 0.4898, MCC: -0.0611, F1: 0.3590

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.41453 | val 0.18499
  Epoch 016 - train 0.39289 | val 0.18399
  Regression -> MSE: 0.000255, MAE: 0.011489, R²: -0.0444
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.37930 | val 0.44738
  Epoch 020 - train 0.36899 | val 0.45370
  Epoch 027 - train 0.35275 | val 0.45499
  Regression -> MSE: 0.000079, MAE: 0.006974, R²: 0.0190
  Directional -> Accuracy: 0.5200, MCC: 0.0621, F1: 0.6327

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.40943 | val 0.49985
  Epoch 016 - train 0.39189 | val 0.51811
  Regression -> MSE: 0.000306, MAE: 0.014468, R²: 0.0025
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.38878 | val 0.45039
  Epoch 016 - train 0.39282 | val 0.45414
  Regression -> MSE: 0.000100, MAE: 0.007103, R²: -0.0174
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.41424 | val 0.51689
  Epoch 016 - train 0.41038 | val 0.51941
  Regression -> MSE: 0.000175, MAE: 0.010156, R²: -0.0192
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.35463 | val 0.50230
  Epoch 016 - train 0.36488 | val 0.57184
  Regression -> MSE: 0.000233, MAE: 0.011939, R²: -0.0438
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.40215 | val 0.45132
  Epoch 016 - train 0.38984 | val 0.51069
  Regression -> MSE: 0.000093, MAE: 0.007642, R²: -0.0023
  Directional -> Accuracy: 0.5263, MCC: 0.0101, F1: 0.0690

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.41154 | val 0.65771
  Epoch 016 - train 0.40748 | val 0.68653
  Regression -> MSE: 0.000164, MAE: 0.010197, R²: 0.0002
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.35097 | val 0.49008
  Epoch 020 - train 0.34404 | val 0.49287
  Epoch 022 - train 0.37148 | val 0.49344
  Regression -> MSE: 0.000123, MAE: 0.009013, R²: -0.0623
  Directional -> Accuracy: 0.4464, MCC: -0.1058, F1: 0.2439

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.40685 | val 0.60951

[I 2026-02-22 23:24:20,223] Trial 118 finished with value: -0.011502462246338087 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.5, 'batch_size': 64, 'learning_rate': 5.143730080193481e-06, 'weight_decay': 7.164120276186942e-06, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 0.8594546991800782, 'early_stopping_min_delta': 0.007324232171907383}. Best is trial 90 with value: -0.011414558399902668.

  Epoch 016 - train 0.38909 | val 0.62034
  Regression -> MSE: 0.000237, MAE: 0.012356, R²: 0.0009
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.41792 | val 0.70839
  Epoch 020 - train 0.42260 | val 0.70234
  Epoch 022 - train 0.42394 | val 0.70476
  Regression -> MSE: 0.000249, MAE: 0.012502, R²: -0.0041
  Directional -> Accuracy: 0.4805, MCC: 0.0962, F1: 0.6296

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.47208 | val 0.40692
  Epoch 020 - train 0.41820 | val 0.40645
  Epoch 027 - train 0.41051 | val 0.41212
  Regression -> MSE: 0.000643, MAE: 0.018830, R²: 0.0611
  Directional -> Accuracy: 0.5652, MCC: 0.1154, F1: 0.6154

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.52021 | val 0.96132
  Epoch 016 - train 0.50470 | val 1.06370
  Regression -> MSE: 0.000327, MAE: 0.014608, R²: -0.0541
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.34728 | val 0.40157
  Epoch 016 - train 0.32814 | val 0.43949
  Regression -> MSE: 0.000375, MAE: 0.014989, R²: -0.0728
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.44164 | val 0.43726
  Epoch 016 - train 0.44008 | val 0.45227
  Regression -> MSE: 0.000209, MAE: 0.010178, R²: -0.0249
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.41292 | val 1.04774
  Epoch 020 - train 0.40713 | val 1.00575
  Epoch 030 - train 0.41222 | val 1.00934
  Epoch 032 - train 0.40892 | val 1.01123
  Regression -> MSE: 0.000560, MAE: 0.018289, R²: -0.0094
  Directional -> Accuracy: 0.4468, MCC: -0.1519, F1: 0.1875

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.46188 | val 0.62309
  Epoch 016 - train 0.45070 | val 0.63075
  Regression -> MSE: 0.000254, MAE: 0.012020, R²: -0.0360
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.43777 | val 0.57605
  Epoch 020 - train 0.42915 | val 0.58519
  Epoch 028 - train 0.42837 | val 0.59954
  Regression -> MSE: 0.000608, MAE: 0.019317, R²: -0.0183
  Directional -> Accuracy: 0.5682, MCC: 0.0842, F1: 0.4242

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.41894 | val 0.53714
  Epoch 016 - train 0.42552 | val 0.53913
  Regression -> MSE: 0.000398, MAE: 0.016009, R²: -0.0364
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.44097 | val 0.62838
  Epoch 016 - train 0.44588 | val 0.63359
  Regression -> MSE: 0.000242, MAE: 0.011769, R²: -0.0030
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.40843 | val 0.72453
  Epoch 016 - train 0.40383 | val 0.77400
  Regression -> MSE: 0.000314, MAE: 0.013618, R²: -0.0101
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.46592 | val 0.57639
  Epoch 016 - train 0.46430 | val 0.57454
  Regression -> MSE: 0.000686, MAE: 0.019765, R²: -0.0126
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.45092 | val 0.44875
  Epoch 016 - train 0.40809 | val 0.45592
  Regression -> MSE: 0.000139, MAE: 0.009220, R²: -0.0070
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.42661 | val 0.63503
  Epoch 016 - train 0.40354 | val 0.63125
  Regression -> MSE: 0.000232, MAE: 0.010971, R²: -0.0314
  Directional -> Accuracy: 0.4918, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.44480 | val 1.17415
  Epoch 016 - train 0.41323 | val 1.22477
  Regression -> MSE: 0.000367, MAE: 0.015938, R²: -0.0144
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.44988 | val 0.55869
  Epoch 016 - train 0.44676 | val 0.58430
  Regression -> MSE: 0.000108, MAE: 0.007941, R²: 0.0029
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.39435 | val 1.00272
  Epoch 016 - train 0.40772 | val 1.07424
  Regression -> MSE: 0.000157, MAE: 0.009826, R²: -0.0066
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.44669 | val 0.49620
  Epoch 016 - train 0.45293 | val 0.47202
  Regression -> MSE: 0.000280, MAE: 0.012896, R²: -0.0283
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.38512 | val 0.66885
  Epoch 016 - train 0.38922 | val 0.66647
  Regression -> MSE: 0.000162, MAE: 0.008954, R²: -0.0797
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.48581 | val 1.25786
  Epoch 016 - train 0.47214 | val 1.17834
  Regression -> MSE: 0.000227, MAE: 0.010945, R²: -0.0044
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.47651 | val 0.63960
  Epoch 016 - train 0.47827 | val 0.73011
  Regression -> MSE: 0.000156, MAE: 0.008904, R²: -0.0848
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.41405 | val 0.58164
  Epoch 016 - train 0.40447 | val 0.60077
  Regression -> MSE: 0.000167, MAE: 0.010279, R²: -0.0134
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.45079 | val 0.57825
  Epoch 020 - train 0.44207 | val 0.58428
  Epoch 023 - train 0.45708 | val 0.58616
  Regression -> MSE: 0.000093, MAE: 0.007422, R²: -0.0890
  Directional -> Accuracy: 0.5172, MCC: 0.1015, F1: 0.4400

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.47640 | val 0.59507
  Epoch 016 - train 0.46798 | val 0.60081
  Regression -> MSE: 0.000217, MAE: 0.011038, R²: -0.0247
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.42100 | val 0.42010
  Epoch 016 - train 0.39255 | val 0.41954
  Regression -> MSE: 0.000099, MAE: 0.008203, R²: -0.0773
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.47413 | val 0.32175
  Epoch 016 - train 0.44595 | val 0.33932
  Regression -> MSE: 0.000105, MAE: 0.008841, R²: -0.0171
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.51186 | val 0.43076
  Epoch 016 - train 0.51980 | val 0.44903
  Regression -> MSE: 0.000243, MAE: 0.012922, R²: -0.0502
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.43527 | val 0.52357
  Epoch 020 - train 0.41411 | val 0.52530
  Epoch 024 - train 0.43856 | val 0.52561
  Regression -> MSE: 0.000183, MAE: 0.008245, R²: -0.0988
  Directional -> Accuracy: 0.5263, MCC: 0.0596, F1: 0.5424

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.50362 | val 0.30238
  Epoch 020 - train 0.47735 | val 0.28127
  Epoch 030 - train 0.48551 | val 0.28339
  Epoch 034 - train 0.46829 | val 0.28296
  Regression -> MSE: 0.000231, MAE: 0.011784, R²: 0.0217
  Directional -> Accuracy: 0.5366, MCC: 0.0166, F1: 0.6885

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.47334 | val 0.87244
  Epoch 016 - train 0.45914 | val 0.88095
  Regression -> MSE: 0.000231, MAE: 0.009898, R²: -0.0034
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.47332 | val 0.58134
  Epoch 016 - train 0.46187 | val 0.59318
  Regression -> MSE: 0.000135, MAE: 0.008211, R²: 0.0012
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.47050 | val 0.61568
  Epoch 016 - train 0.46461 | val 0.65828
  Regression -> MSE: 0.000202, MAE: 0.010822, R²: -0.0754
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.40210 | val 0.56320
  Epoch 016 - train 0.36905 | val 0.55807
  Regression -> MSE: 0.000274, MAE: 0.010767, R²: -0.0476
  Directional -> Accuracy: 0.4384, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.44410 | val 0.36015
  Epoch 020 - train 0.40590 | val 0.35498
  Epoch 027 - train 0.41205 | val 0.39778
  Regression -> MSE: 0.000165, MAE: 0.010364, R²: 0.0070
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.40550 | val 0.50300
  Epoch 016 - train 0.40950 | val 0.52319
  Regression -> MSE: 0.000184, MAE: 0.010472, R²: -0.0228
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.43528 | val 0.48831
  Epoch 016 - train 0.43180 | val 0.48374
  Regression -> MSE: 0.000361, MAE: 0.012989, R²: -0.0537
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.46160 | val 0.22854
  Epoch 016 - train 0.43793 | val 0.22966
  Regression -> MSE: 0.000114, MAE: 0.008334, R²: -0.0858
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.47839 | val 0.75337
  Epoch 016 - train 0.44770 | val 0.76343
  Regression -> MSE: 0.000225, MAE: 0.011495, R²: -0.0295
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.44660 | val 0.98230
  Epoch 016 - train 0.42247 | val 0.98819
  Regression -> MSE: 0.000082, MAE: 0.007045, R²: -0.0512
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.44559 | val 0.35316
  Epoch 020 - train 0.41594 | val 0.29591
  Epoch 030 - train 0.42016 | val 0.28883
  Epoch 040 - train 0.44637 | val 0.28983
  Epoch 041 - train 0.42384 | val 0.28840
  Regression -> MSE: 0.000351, MAE: 0.015751, R²: -0.1396
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.46487 | val 0.19974
  Epoch 020 - train 0.49083 | val 0.18818
  Epoch 030 - train 0.42312 | val 0.18465
  Epoch 036 - train 0.45398 | val 0.18812
  Regression -> MSE: 0.000249, MAE: 0.011455, R²: -0.0234
  Directional -> Accuracy: 0.6316, MCC: 0.2626, F1: 0.6957

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.42670 | val 0.57424
  Epoch 016 - train 0.40890 | val 0.58588
  Regression -> MSE: 0.000082, MAE: 0.007051, R²: -0.0192
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.45430 | val 0.62677
  Epoch 020 - train 0.45117 | val 0.55794
  Epoch 030 - train 0.44159 | val 0.54471
  Epoch 039 - train 0.41832 | val 0.54526
  Regression -> MSE: 0.000306, MAE: 0.014491, R²: 0.0019
  Directional -> Accuracy: 0.5106, MCC: 0.0081, F1: 0.6462

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.44652 | val 0.49217
  Epoch 016 - train 0.41314 | val 0.52314
  Regression -> MSE: 0.000098, MAE: 0.007341, R²: -0.0002
  Directional -> Accuracy: 0.4318, MCC: 0.0000, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.52600 | val 0.65991
  Epoch 016 - train 0.53225 | val 0.67298
  Regression -> MSE: 0.000175, MAE: 0.010156, R²: -0.0181
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.40957 | val 0.53029
  Epoch 020 - train 0.39079 | val 0.52915
  Epoch 025 - train 0.39828 | val 0.52927
  Regression -> MSE: 0.000236, MAE: 0.011876, R²: -0.0579
  Directional -> Accuracy: 0.5536, MCC: 0.1377, F1: 0.4898

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.46574 | val 0.52001
  Epoch 016 - train 0.45510 | val 0.53159
  Regression -> MSE: 0.000092, MAE: 0.007630, R²: 0.0002
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.47688 | val 0.87814
  Epoch 016 - train 0.46540 | val 0.94483
  Regression -> MSE: 0.000164, MAE: 0.010261, R²: -0.0002
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.42678 | val 0.61720
  Epoch 016 - train 0.43301 | val 0.65445
  Regression -> MSE: 0.000118, MAE: 0.008949, R²: -0.0215
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.44311 | val 0.78496

[I 2026-02-22 23:25:34,712] Trial 119 finished with value: -0.01147827714615578 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.30000000000000004, 'batch_size': 32, 'learning_rate': 1.0728611434488067e-05, 'weight_decay': 4.2570766980234495e-06, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 1.248960754296669, 'early_stopping_min_delta': 0.006812796124817937}. Best is trial 90 with value: -0.011414558399902668.

  Epoch 016 - train 0.44489 | val 0.82696
  Regression -> MSE: 0.000242, MAE: 0.012335, R²: -0.0197
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.35245 | val 0.49920
  Epoch 020 - train 0.35230 | val 0.50782
  Epoch 021 - train 0.33810 | val 0.50795
  Regression -> MSE: 0.000250, MAE: 0.012635, R²: -0.0082
  Directional -> Accuracy: 0.4805, MCC: -0.0379, F1: 0.4595

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.33809 | val 0.33139
  Epoch 020 - train 0.35236 | val 0.31951
  Epoch 028 - train 0.33625 | val 0.32068
  Regression -> MSE: 0.000643, MAE: 0.018814, R²: 0.0602
  Directional -> Accuracy: 0.6522, MCC: 0.2779, F1: 0.7333

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.36170 | val 0.64572
  Epoch 016 - train 0.35469 | val 0.64292
  Regression -> MSE: 0.000309, MAE: 0.014400, R²: 0.0027
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.31848 | val 0.29297
  Epoch 016 - train 0.31982 | val 0.30555
  Regression -> MSE: 0.000350, MAE: 0.014597, R²: -0.0024
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.35968 | val 0.36335
  Epoch 016 - train 0.36663 | val 0.37901
  Regression -> MSE: 0.000204, MAE: 0.010076, R²: -0.0016
  Directional -> Accuracy: 0.5098, MCC: -0.0106, F1: 0.6154

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.35888 | val 0.75092
  Epoch 020 - train 0.36565 | val 0.74505
  Epoch 028 - train 0.34152 | val 0.74584
  Regression -> MSE: 0.000556, MAE: 0.018502, R²: -0.0019
  Directional -> Accuracy: 0.4894, MCC: 0.0000, F1: 0.6571

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.36981 | val 0.48265
  Epoch 016 - train 0.37641 | val 0.48621
  Regression -> MSE: 0.000248, MAE: 0.012007, R²: -0.0109
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.38930 | val 0.55324
  Epoch 016 - train 0.36439 | val 0.55870
  Regression -> MSE: 0.000649, MAE: 0.020244, R²: -0.0868
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.34586 | val 0.45199
  Epoch 016 - train 0.34341 | val 0.46172
  Regression -> MSE: 0.000387, MAE: 0.015933, R²: -0.0099
  Directional -> Accuracy: 0.4898, MCC: 0.1862, F1: 0.6377

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.37778 | val 0.55642
  Epoch 016 - train 0.38420 | val 0.59103
  Regression -> MSE: 0.000252, MAE: 0.011676, R²: -0.0447
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.33286 | val 0.63182
  Epoch 016 - train 0.32932 | val 0.77422
  Regression -> MSE: 0.000315, MAE: 0.013590, R²: -0.0139
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.39798 | val 0.44698
  Epoch 016 - train 0.36442 | val 0.47823
  Regression -> MSE: 0.000681, MAE: 0.019656, R²: -0.0062
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.35118 | val 0.36030
  Epoch 016 - train 0.34284 | val 0.37338
  Regression -> MSE: 0.000141, MAE: 0.009362, R²: -0.0226
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.33525 | val 0.47870
  Epoch 020 - train 0.33082 | val 0.46796
  Epoch 030 - train 0.32838 | val 0.46860
  Epoch 032 - train 0.33259 | val 0.46868
  Regression -> MSE: 0.000237, MAE: 0.011025, R²: -0.0517
  Directional -> Accuracy: 0.5410, MCC: 0.2237, F1: 0.1765

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.35525 | val 0.82615
  Epoch 016 - train 0.34744 | val 0.83066
  Regression -> MSE: 0.000366, MAE: 0.015940, R²: -0.0109
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.40170 | val 0.37374
  Epoch 016 - train 0.38810 | val 0.37854
  Regression -> MSE: 0.000109, MAE: 0.008121, R²: -0.0087
  Directional -> Accuracy: 0.4571, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.35074 | val 0.72832
  Epoch 016 - train 0.37104 | val 0.81248
  Regression -> MSE: 0.000161, MAE: 0.010138, R²: -0.0306
  Directional -> Accuracy: 0.4407, MCC: -0.0027, F1: 0.3774

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.38144 | val 0.40010
  Epoch 016 - train 0.38299 | val 0.43216
  Regression -> MSE: 0.000301, MAE: 0.014213, R²: -0.1047
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.32140 | val 0.57158
  Epoch 016 - train 0.33613 | val 0.62110
  Regression -> MSE: 0.000155, MAE: 0.008743, R²: -0.0340
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.36297 | val 0.56141
  Epoch 020 - train 0.35651 | val 0.55443
  Epoch 030 - train 0.37172 | val 0.55109
  Epoch 031 - train 0.35052 | val 0.55083
  Regression -> MSE: 0.000236, MAE: 0.010835, R²: -0.0418
  Directional -> Accuracy: 0.6000, MCC: 0.1973, F1: 0.6250

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.35604 | val 0.47390
  Epoch 020 - train 0.32876 | val 0.47016
  Epoch 028 - train 0.35148 | val 0.47020
  Regression -> MSE: 0.000146, MAE: 0.008536, R²: -0.0207
  Directional -> Accuracy: 0.6458, MCC: 0.1883, F1: 0.7792

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.33661 | val 0.43319
  Epoch 016 - train 0.33719 | val 0.43798
  Regression -> MSE: 0.000168, MAE: 0.010264, R²: -0.0175
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.38460 | val 0.44356
  Epoch 016 - train 0.37697 | val 0.44507
  Regression -> MSE: 0.000088, MAE: 0.007205, R²: -0.0319
  Directional -> Accuracy: 0.3966, MCC: -0.1743, F1: 0.3396

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.37264 | val 0.44620
  Epoch 016 - train 0.36402 | val 0.46337
  Regression -> MSE: 0.000214, MAE: 0.011111, R²: -0.0087
  Directional -> Accuracy: 0.5000, MCC: -0.0590, F1: 0.1951

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.33779 | val 0.30133
  Epoch 020 - train 0.32885 | val 0.29625
  Epoch 030 - train 0.31303 | val 0.29108
  Epoch 040 - train 0.31789 | val 0.28695
  Epoch 042 - train 0.32214 | val 0.28617
  Regression -> MSE: 0.000095, MAE: 0.008066, R²: -0.0342
  Directional -> Accuracy: 0.5714, MCC: 0.1102, F1: 0.6571

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.38099 | val 0.26049
  Epoch 020 - train 0.38719 | val 0.28834
  Epoch 023 - train 0.37031 | val 0.31368
  Regression -> MSE: 0.000103, MAE: 0.008685, R²: -0.0017
  Directional -> Accuracy: 0.6087, MCC: 0.1953, F1: 0.5263

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.41852 | val 0.34381
  Epoch 016 - train 0.42918 | val 0.39646
  Regression -> MSE: 0.000232, MAE: 0.012587, R²: -0.0015
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.35641 | val 0.43920
  Epoch 020 - train 0.35782 | val 0.42430
  Epoch 030 - train 0.35845 | val 0.41986
  Epoch 033 - train 0.36462 | val 0.41930
  Regression -> MSE: 0.000239, MAE: 0.010688, R²: -0.4383
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.34777 | val 0.26548
  Epoch 016 - train 0.37139 | val 0.26225
  Regression -> MSE: 0.000237, MAE: 0.011850, R²: -0.0008
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.33105 | val 0.64156
  Epoch 016 - train 0.33284 | val 0.64259
  Regression -> MSE: 0.000232, MAE: 0.010045, R²: -0.0067
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.37759 | val 0.50411
  Epoch 016 - train 0.37937 | val 0.55713
  Regression -> MSE: 0.000139, MAE: 0.008363, R²: -0.0284
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.35523 | val 0.47937
  Epoch 016 - train 0.37094 | val 0.49884
  Regression -> MSE: 0.000197, MAE: 0.010629, R²: -0.0459
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.33516 | val 0.47105
  Epoch 016 - train 0.33512 | val 0.48135
  Regression -> MSE: 0.000263, MAE: 0.010506, R²: -0.0051
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.35554 | val 0.30488
  Epoch 016 - train 0.36506 | val 0.32435
  Regression -> MSE: 0.000174, MAE: 0.010427, R²: -0.0446
  Directional -> Accuracy: 0.4737, MCC: -0.0619, F1: 0.2857

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.38981 | val 0.44166
  Epoch 016 - train 0.38097 | val 0.46340
  Regression -> MSE: 0.000192, MAE: 0.010744, R²: -0.0683
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.35066 | val 0.33899
  Epoch 016 - train 0.35054 | val 0.33453
  Regression -> MSE: 0.000348, MAE: 0.012057, R²: -0.0159
  Directional -> Accuracy: 0.3881, MCC: -0.1859, F1: 0.1277

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.40029 | val 0.20512
  Epoch 016 - train 0.39587 | val 0.21442
  Regression -> MSE: 0.000115, MAE: 0.008326, R²: -0.0914
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.35535 | val 0.52730
  Epoch 016 - train 0.35273 | val 0.55683
  Regression -> MSE: 0.000218, MAE: 0.011281, R²: 0.0010
  Directional -> Accuracy: 0.5088, MCC: -0.0458, F1: 0.1250

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.40905 | val 0.75444
  Epoch 016 - train 0.39664 | val 0.81599
  Regression -> MSE: 0.000080, MAE: 0.006949, R²: -0.0270
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.38580 | val 0.32455
  Epoch 016 - train 0.38490 | val 0.33874
  Regression -> MSE: 0.000358, MAE: 0.015956, R²: -0.1647
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.38518 | val 0.20053
  Epoch 016 - train 0.45178 | val 0.22363
  Regression -> MSE: 0.000256, MAE: 0.011558, R²: -0.0486
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.35302 | val 0.44610
  Epoch 016 - train 0.34188 | val 0.45177
  Regression -> MSE: 0.000081, MAE: 0.007090, R²: 0.0021
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.39730 | val 0.48981
  Epoch 016 - train 0.38897 | val 0.53368
  Regression -> MSE: 0.000307, MAE: 0.014520, R²: -0.0007
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.37022 | val 0.38706
  Epoch 016 - train 0.38117 | val 0.38696
  Regression -> MSE: 0.000097, MAE: 0.007200, R²: 0.0085
  Directional -> Accuracy: 0.6136, MCC: 0.2503, F1: 0.7463

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.39609 | val 0.47396
  Epoch 016 - train 0.39631 | val 0.47661
  Regression -> MSE: 0.000171, MAE: 0.009489, R²: 0.0029
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.34189 | val 0.41657
  Epoch 016 - train 0.33154 | val 0.44874
  Regression -> MSE: 0.000224, MAE: 0.011727, R²: -0.0053
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.35520 | val 0.42673
  Epoch 016 - train 0.36345 | val 0.45849
  Regression -> MSE: 0.000094, MAE: 0.007743, R²: -0.0188
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.38513 | val 0.62421
  Epoch 020 - train 0.39410 | val 0.65106
  Epoch 024 - train 0.39142 | val 0.65358
  Regression -> MSE: 0.000164, MAE: 0.010115, R²: -0.0038
  Directional -> Accuracy: 0.5370, MCC: 0.0676, F1: 0.5902

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.37435 | val 0.58299
  Epoch 016 - train 0.38167 | val 0.68367
  Regression -> MSE: 0.000116, MAE: 0.008878, R²: 0.0013
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...

[I 2026-02-22 23:25:56,927] Trial 120 finished with value: -0.01151045670219008 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.5, 'batch_size': 64, 'learning_rate': 2.322773730175488e-05, 'weight_decay': 3.1529278470915048e-06, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 0.7610900123388582, 'early_stopping_min_delta': 0.0071187092124736845}. Best is trial 90 with value: -0.011414558399902668.

  Epoch 010 - train 0.37296 | val 0.60364
  Epoch 016 - train 0.37051 | val 0.64857
  Regression -> MSE: 0.000247, MAE: 0.012418, R²: -0.0432
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.42341 | val 0.74727
  Epoch 016 - train 0.43329 | val 0.74472
  Regression -> MSE: 0.000252, MAE: 0.012715, R²: -0.0160
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.44033 | val 0.43031
  Epoch 020 - train 0.42816 | val 0.44968
  Epoch 027 - train 0.42231 | val 0.45964
  Regression -> MSE: 0.000665, MAE: 0.019139, R²: 0.0279
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.47815 | val 0.90295
  Epoch 016 - train 0.49036 | val 0.94711
  Regression -> MSE: 0.000312, MAE: 0.014424, R²: -0.0073
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.34292 | val 0.43875
  Epoch 016 - train 0.33770 | val 0.45925
  Regression -> MSE: 0.000369, MAE: 0.014892, R²: -0.0564
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.44998 | val 0.58232
  Epoch 016 - train 0.44923 | val 0.75152
  Regression -> MSE: 0.000208, MAE: 0.010546, R²: -0.0228
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.44692 | val 1.08835
  Epoch 016 - train 0.42535 | val 1.12117
  Regression -> MSE: 0.000586, MAE: 0.018695, R²: -0.0561
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.45802 | val 0.59113
  Epoch 020 - train 0.44744 | val 0.58813
  Epoch 025 - train 0.44896 | val 0.58778
  Regression -> MSE: 0.000244, MAE: 0.012077, R²: 0.0043
  Directional -> Accuracy: 0.5072, MCC: -0.0218, F1: 0.3929

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.44169 | val 0.55900
  Epoch 020 - train 0.44208 | val 0.52158
  Epoch 030 - train 0.43865 | val 0.55119
  Epoch 032 - train 0.44623 | val 0.54732
  Regression -> MSE: 0.000651, MAE: 0.019882, R²: -0.0900
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.43081 | val 0.55219
  Epoch 016 - train 0.41599 | val 0.55308
  Regression -> MSE: 0.000397, MAE: 0.015989, R²: -0.0338
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.44416 | val 0.90984
  Epoch 016 - train 0.43218 | val 0.97198
  Regression -> MSE: 0.000241, MAE: 0.011851, R²: 0.0014
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.39905 | val 0.71279
  Epoch 016 - train 0.41339 | val 0.75414
  Regression -> MSE: 0.000320, MAE: 0.013587, R²: -0.0283
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.46846 | val 0.66948
  Epoch 016 - train 0.46911 | val 0.78173
  Regression -> MSE: 0.000678, MAE: 0.019567, R²: -0.0013
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.44811 | val 0.51446
  Epoch 016 - train 0.44198 | val 0.67874
  Regression -> MSE: 0.000138, MAE: 0.009083, R²: 0.0006
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.39914 | val 0.68597
  Epoch 016 - train 0.41956 | val 0.69779
  Regression -> MSE: 0.000226, MAE: 0.010696, R²: -0.0033
  Directional -> Accuracy: 0.5082, MCC: 0.0394, F1: 0.2500

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.45791 | val 1.17855
  Epoch 020 - train 0.43862 | val 1.17911
  Epoch 026 - train 0.43143 | val 1.19102
  Regression -> MSE: 0.000358, MAE: 0.015964, R²: 0.0114
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.47692 | val 0.51168
  Epoch 016 - train 0.46410 | val 0.51628
  Regression -> MSE: 0.000110, MAE: 0.007953, R²: -0.0169
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.41021 | val 0.91793
  Epoch 016 - train 0.40427 | val 0.93622
  Regression -> MSE: 0.000156, MAE: 0.009744, R²: -0.0032
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.48194 | val 0.48400
  Epoch 016 - train 0.45374 | val 0.47879
  Regression -> MSE: 0.000273, MAE: 0.013078, R²: -0.0020
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.40786 | val 0.66121
  Epoch 016 - train 0.39814 | val 0.65861
  Regression -> MSE: 0.000172, MAE: 0.009266, R²: -0.1480
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.44118 | val 0.85015
  Epoch 019 - train 0.43984 | val 0.86431
  Regression -> MSE: 0.000243, MAE: 0.011226, R²: -0.0760
  Directional -> Accuracy: 0.4267, MCC: -0.1192, F1: 0.1224

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.46877 | val 0.64989
  Epoch 016 - train 0.44681 | val 0.69060
  Regression -> MSE: 0.000149, MAE: 0.008651, R²: -0.0395
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.40577 | val 0.54129
  Epoch 016 - train 0.40984 | val 0.54961
  Regression -> MSE: 0.000166, MAE: 0.010343, R²: -0.0020
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.48336 | val 0.58968
  Epoch 020 - train 0.46524 | val 0.58918
  Epoch 025 - train 0.49031 | val 0.59050
  Regression -> MSE: 0.000086, MAE: 0.007110, R²: -0.0047
  Directional -> Accuracy: 0.5000, MCC: -0.1813, F1: 0.6588

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.44388 | val 0.62203
  Epoch 016 - train 0.43680 | val 0.63150
  Regression -> MSE: 0.000212, MAE: 0.011113, R²: -0.0023
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.40956 | val 0.35209
  Epoch 020 - train 0.41997 | val 0.36778
  Epoch 022 - train 0.39336 | val 0.36752
  Regression -> MSE: 0.000095, MAE: 0.008097, R²: -0.0348
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.51900 | val 0.31734
  Epoch 020 - train 0.48513 | val 0.31492
  Epoch 028 - train 0.49281 | val 0.34157
  Regression -> MSE: 0.000102, MAE: 0.008665, R²: 0.0088
  Directional -> Accuracy: 0.5000, MCC: 0.2317, F1: 0.6349

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.52558 | val 0.43904
  Epoch 016 - train 0.50364 | val 0.42987
  Regression -> MSE: 0.000244, MAE: 0.012946, R²: -0.0554
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.45446 | val 0.56017
  Epoch 020 - train 0.43766 | val 0.54477
  Epoch 030 - train 0.43125 | val 0.54202
  Epoch 033 - train 0.42202 | val 0.54265
  Regression -> MSE: 0.000223, MAE: 0.010310, R²: -0.3385
  Directional -> Accuracy: 0.4211, MCC: -0.2579, F1: 0.5600

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.46559 | val 0.29686
  Epoch 016 - train 0.46153 | val 0.29316
  Regression -> MSE: 0.000236, MAE: 0.011855, R²: 0.0004
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.41683 | val 0.93403
  Epoch 016 - train 0.44307 | val 0.97399
  Regression -> MSE: 0.000235, MAE: 0.010130, R²: -0.0176
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.48629 | val 0.59284
  Epoch 016 - train 0.44916 | val 0.60603
  Regression -> MSE: 0.000135, MAE: 0.008238, R²: -0.0020
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.45232 | val 0.64026
  Epoch 016 - train 0.46496 | val 0.65122
  Regression -> MSE: 0.000189, MAE: 0.010432, R²: -0.0015
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.38701 | val 0.56187
  Epoch 020 - train 0.37292 | val 0.56018
  Epoch 022 - train 0.38666 | val 0.55886
  Regression -> MSE: 0.000276, MAE: 0.011122, R²: -0.0540
  Directional -> Accuracy: 0.5616, MCC: 0.1225, F1: 0.5897

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.51029 | val 0.35790
  Epoch 016 - train 0.45386 | val 0.36159
  Regression -> MSE: 0.000167, MAE: 0.010367, R²: -0.0024
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.47875 | val 0.56077
  Epoch 016 - train 0.46131 | val 0.59940
  Regression -> MSE: 0.000196, MAE: 0.010873, R²: -0.0877
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.41278 | val 0.42527
  Epoch 016 - train 0.42196 | val 0.42811
  Regression -> MSE: 0.000344, MAE: 0.012071, R²: -0.0052
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.49227 | val 0.25880
  Epoch 016 - train 0.48595 | val 0.26396
  Regression -> MSE: 0.000127, MAE: 0.008514, R²: -0.2105
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.44869 | val 0.75609
  Epoch 016 - train 0.44461 | val 0.78133
  Regression -> MSE: 0.000219, MAE: 0.011262, R²: -0.0003
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.47120 | val 0.97807
  Epoch 020 - train 0.46766 | val 0.96115
  Epoch 030 - train 0.43194 | val 0.95883
  Epoch 035 - train 0.42201 | val 0.96132
  Regression -> MSE: 0.000120, MAE: 0.008684, R²: -0.5438
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.44979 | val 0.30074
  Epoch 016 - train 0.42336 | val 0.29833
  Regression -> MSE: 0.000319, MAE: 0.014430, R²: -0.0361
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.45083 | val 0.21692
  Epoch 016 - train 0.46428 | val 0.21553
  Regression -> MSE: 0.000259, MAE: 0.011496, R²: -0.0631
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.43975 | val 0.58616
  Epoch 016 - train 0.42246 | val 0.58776
  Regression -> MSE: 0.000085, MAE: 0.007059, R²: -0.0548
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.45761 | val 0.63273
  Epoch 016 - train 0.42731 | val 0.65741
  Regression -> MSE: 0.000309, MAE: 0.014492, R²: -0.0079
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.46258 | val 0.49013
  Epoch 016 - train 0.46968 | val 0.50341
  Regression -> MSE: 0.000098, MAE: 0.007389, R²: -0.0012
  Directional -> Accuracy: 0.4318, MCC: 0.0000, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.49171 | val 0.65827
  Epoch 020 - train 0.48831 | val 0.65191
  Epoch 028 - train 0.43388 | val 0.65498
  Regression -> MSE: 0.000171, MAE: 0.009816, R²: 0.0025
  Directional -> Accuracy: 0.4490, MCC: 0.0855, F1: 0.5574

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.41598 | val 0.55513
  Epoch 016 - train 0.39486 | val 0.60261
  Regression -> MSE: 0.000223, MAE: 0.011748, R²: -0.0005
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.47714 | val 0.52942
  Epoch 016 - train 0.45488 | val 0.54294
  Regression -> MSE: 0.000093, MAE: 0.007649, R²: -0.0072
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.47926 | val 0.85585
  Epoch 020 - train 0.43884 | val 0.86363
  Epoch 024 - train 0.46270 | val 0.86537
  Regression -> MSE: 0.000163, MAE: 0.010089, R²: 0.0061
  Directional -> Accuracy: 0.6111, MCC: 0.2196, F1: 0.6557

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.43141 | val 0.59610
  Epoch 016 - train 0.43429 | val 0.60514
  Regression -> MSE: 0.000131, MAE: 0.009128, R²: -0.1286
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.49765 | val 0.81297

[I 2026-02-22 23:27:12,523] Trial 121 finished with value: -0.011537605002819412 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 32, 'learning_rate': 1.1021778476967968e-05, 'weight_decay': 4.082062427607754e-06, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 1.2913909255990286, 'early_stopping_min_delta': 0.006724837396633741}. Best is trial 90 with value: -0.011414558399902668.

  Epoch 016 - train 0.47242 | val 0.81559
  Regression -> MSE: 0.000248, MAE: 0.012429, R²: -0.0453
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.43412 | val 0.65826
  Epoch 020 - train 0.42532 | val 0.65494
  Epoch 030 - train 0.40385 | val 0.65660
  Epoch 037 - train 0.41480 | val 0.65638
  Regression -> MSE: 0.000252, MAE: 0.012523, R²: -0.0160
  Directional -> Accuracy: 0.5455, MCC: 0.0541, F1: 0.3636

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.41515 | val 0.46377
  Epoch 016 - train 0.41779 | val 0.54918
  Regression -> MSE: 0.000686, MAE: 0.019348, R²: -0.0028
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.54946 | val 0.89768
  Epoch 016 - train 0.53131 | val 0.95340
  Regression -> MSE: 0.000328, MAE: 0.014599, R²: -0.0586
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.35245 | val 0.40136
  Epoch 016 - train 0.33392 | val 0.45717
  Regression -> MSE: 0.000373, MAE: 0.014956, R²: -0.0676
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.41686 | val 0.47055
  Epoch 016 - train 0.42700 | val 0.49050
  Regression -> MSE: 0.000206, MAE: 0.010425, R²: -0.0141
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.45351 | val 1.06648
  Epoch 016 - train 0.43371 | val 1.08671
  Regression -> MSE: 0.000621, MAE: 0.019517, R²: -0.1188
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.44949 | val 0.58758
  Epoch 020 - train 0.45104 | val 0.57684
  Epoch 030 - train 0.41724 | val 0.57316
  Epoch 034 - train 0.42434 | val 0.57498
  Regression -> MSE: 0.000263, MAE: 0.012996, R²: -0.0727
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.44442 | val 0.60872
  Epoch 016 - train 0.41972 | val 0.69062
  Regression -> MSE: 0.000611, MAE: 0.019505, R²: -0.0235
  Directional -> Accuracy: 0.6136, MCC: 0.1390, F1: 0.2609

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.40908 | val 0.56716
  Epoch 020 - train 0.40788 | val 0.54740
  Epoch 030 - train 0.40644 | val 0.54820
  Epoch 035 - train 0.40262 | val 0.54848
  Regression -> MSE: 0.000389, MAE: 0.015785, R²: -0.0130
  Directional -> Accuracy: 0.6735, MCC: 0.3356, F1: 0.6190

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.44759 | val 0.66378
  Epoch 016 - train 0.43355 | val 0.64977
  Regression -> MSE: 0.000244, MAE: 0.012277, R²: -0.0123
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.40899 | val 0.67215
  Epoch 020 - train 0.39469 | val 0.70835
  Epoch 023 - train 0.40338 | val 0.71640
  Regression -> MSE: 0.000317, MAE: 0.013548, R²: -0.0208
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.44477 | val 0.61895
  Epoch 016 - train 0.45699 | val 0.69212
  Regression -> MSE: 0.000677, MAE: 0.019502, R²: 0.0007
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.46707 | val 0.44312
  Epoch 020 - train 0.44544 | val 0.44568
  Epoch 023 - train 0.42086 | val 0.44105
  Regression -> MSE: 0.000139, MAE: 0.009164, R²: -0.0067
  Directional -> Accuracy: 0.4651, MCC: 0.0306, F1: 0.5965

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.38697 | val 0.62123
  Epoch 020 - train 0.37909 | val 0.61743
  Epoch 030 - train 0.37508 | val 0.61165
  Epoch 037 - train 0.38513 | val 0.61033
  Regression -> MSE: 0.000230, MAE: 0.010857, R²: -0.0245
  Directional -> Accuracy: 0.5246, MCC: 0.0648, F1: 0.3830

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.43249 | val 1.19248
  Epoch 016 - train 0.43224 | val 1.27159
  Regression -> MSE: 0.000363, MAE: 0.016176, R²: -0.0012
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.42863 | val 0.46962
  Epoch 016 - train 0.43294 | val 0.48458
  Regression -> MSE: 0.000111, MAE: 0.007956, R²: -0.0251
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.43464 | val 1.09722
  Epoch 016 - train 0.41703 | val 1.17650
  Regression -> MSE: 0.000157, MAE: 0.009524, R²: -0.0062
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.44921 | val 0.47678
  Epoch 016 - train 0.44376 | val 0.48454
  Regression -> MSE: 0.000274, MAE: 0.012919, R²: -0.0052
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.35839 | val 0.64797
  Epoch 020 - train 0.36235 | val 0.62897
  Epoch 030 - train 0.34149 | val 0.62555
  Epoch 040 - train 0.35967 | val 0.62051
  Epoch 048 - train 0.34718 | val 0.62835
  Regression -> MSE: 0.000270, MAE: 0.012767, R²: -0.8046
  Directional -> Accuracy: 0.4615, MCC: 0.1262, F1: 0.1860

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.45888 | val 0.94136
  Epoch 016 - train 0.43820 | val 0.95145
  Regression -> MSE: 0.000237, MAE: 0.010977, R²: -0.0453
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.44311 | val 0.61824
  Epoch 016 - train 0.44514 | val 0.63186
  Regression -> MSE: 0.000149, MAE: 0.008631, R²: -0.0363
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.41013 | val 0.53952
  Epoch 016 - train 0.41002 | val 0.55065
  Regression -> MSE: 0.000173, MAE: 0.010258, R²: -0.0484
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.45264 | val 0.56642
  Epoch 020 - train 0.46088 | val 0.57396
  Epoch 023 - train 0.46086 | val 0.57360
  Regression -> MSE: 0.000085, MAE: 0.007056, R²: 0.0016
  Directional -> Accuracy: 0.5345, MCC: 0.0845, F1: 0.5424

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.45721 | val 1.04560
  Epoch 016 - train 0.42725 | val 1.04399
  Regression -> MSE: 0.000216, MAE: 0.011005, R²: -0.0185
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.38282 | val 0.36121
  Epoch 016 - train 0.39305 | val 0.35963
  Regression -> MSE: 0.000100, MAE: 0.008220, R²: -0.0896
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.43533 | val 0.32208
  Epoch 016 - train 0.43957 | val 0.33127
  Regression -> MSE: 0.000109, MAE: 0.008987, R²: -0.0548
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.45885 | val 0.42976
  Epoch 016 - train 0.46586 | val 0.52644
  Regression -> MSE: 0.000234, MAE: 0.012640, R²: -0.0129
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.43436 | val 0.53670
  Epoch 020 - train 0.41083 | val 0.53536
  Epoch 025 - train 0.42238 | val 0.53873
  Regression -> MSE: 0.000183, MAE: 0.008348, R²: -0.0979
  Directional -> Accuracy: 0.4561, MCC: -0.1441, F1: 0.5634

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.46207 | val 0.29282
  Epoch 016 - train 0.45674 | val 0.32536
  Regression -> MSE: 0.000237, MAE: 0.011868, R²: -0.0007
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.50470 | val 0.83901
  Epoch 016 - train 0.46804 | val 0.83756
  Regression -> MSE: 0.000230, MAE: 0.009864, R²: 0.0000
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.44240 | val 0.57053
  Epoch 016 - train 0.44936 | val 0.60901
  Regression -> MSE: 0.000135, MAE: 0.008167, R²: 0.0001
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.42669 | val 0.61002
  Epoch 016 - train 0.41295 | val 0.61418
  Regression -> MSE: 0.000190, MAE: 0.010372, R²: -0.0068
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.39198 | val 0.54665
  Epoch 016 - train 0.36334 | val 0.54504
  Regression -> MSE: 0.000276, MAE: 0.010814, R²: -0.0545
  Directional -> Accuracy: 0.4384, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.44109 | val 0.34767
  Epoch 016 - train 0.40505 | val 0.34678
  Regression -> MSE: 0.000167, MAE: 0.010368, R²: -0.0024
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.39381 | val 0.52088
  Epoch 016 - train 0.39110 | val 0.61746
  Regression -> MSE: 0.000179, MAE: 0.010281, R²: 0.0027
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.40853 | val 0.40254
  Epoch 020 - train 0.39308 | val 0.41151
  Epoch 021 - train 0.41000 | val 0.41364
  Regression -> MSE: 0.000331, MAE: 0.011690, R²: 0.0328
  Directional -> Accuracy: 0.5672, MCC: 0.1757, F1: 0.5397

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.48186 | val 0.23810
  Epoch 016 - train 0.47868 | val 0.28737
  Regression -> MSE: 0.000110, MAE: 0.008308, R²: -0.0495
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.42427 | val 0.70196
  Epoch 020 - train 0.40694 | val 0.72109
  Epoch 022 - train 0.40636 | val 0.72372
  Regression -> MSE: 0.000223, MAE: 0.011543, R²: -0.0188
  Directional -> Accuracy: 0.4912, MCC: 0.1268, F1: 0.6506

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.45049 | val 0.95921
  Epoch 016 - train 0.41770 | val 0.96489
  Regression -> MSE: 0.000085, MAE: 0.007200, R²: -0.0940
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.42225 | val 0.29576
  Epoch 020 - train 0.41812 | val 0.25326
  Epoch 030 - train 0.40276 | val 0.24244
  Epoch 038 - train 0.39929 | val 0.24056
  Regression -> MSE: 0.000437, MAE: 0.017972, R²: -0.4201
  Directional -> Accuracy: 0.3469, MCC: -0.1894, F1: 0.5152

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.48270 | val 0.19927
  Epoch 016 - train 0.49046 | val 0.21187
  Regression -> MSE: 0.000247, MAE: 0.011551, R²: -0.0135
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.0000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.39129 | val 0.51503
  Epoch 020 - train 0.38527 | val 0.51787
  Epoch 024 - train 0.38254 | val 0.52009
  Regression -> MSE: 0.000085, MAE: 0.007401, R²: -0.0484
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.46631 | val 0.55435
  Epoch 020 - train 0.44435 | val 0.54738
  Epoch 027 - train 0.45660 | val 0.55283
  Regression -> MSE: 0.000316, MAE: 0.014728, R²: -0.0313
  Directional -> Accuracy: 0.5319, MCC: 0.1460, F1: 0.2143

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.41187 | val 0.48227
  Epoch 016 - train 0.40337 | val 0.48532
  Regression -> MSE: 0.000098, MAE: 0.007329, R²: -0.0003
  Directional -> Accuracy: 0.4318, MCC: 0.0000, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.48835 | val 0.63214
  Epoch 016 - train 0.44496 | val 0.64347
  Regression -> MSE: 0.000172, MAE: 0.009721, R²: 0.0012
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.40105 | val 0.57265
  Epoch 016 - train 0.39655 | val 0.57790
  Regression -> MSE: 0.000227, MAE: 0.011840, R²: -0.0189
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.40978 | val 0.56421
  Epoch 016 - train 0.41810 | val 0.57541
  Regression -> MSE: 0.000095, MAE: 0.007839, R²: -0.0304
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.45689 | val 0.83133
  Epoch 020 - train 0.44864 | val 0.84699
  Epoch 022 - train 0.45405 | val 0.85231
  Regression -> MSE: 0.000172, MAE: 0.010504, R²: -0.0520
  Directional -> Accuracy: 0.4815, MCC: 0.0000, F1: 0.0000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.41704 | val 0.73686
  Epoch 016 - train 0.42902 | val 0.75742
  Regression -> MSE: 0.000117, MAE: 0.008920, R²: -0.0099
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.44653 | val 0.74874
  Epoch 020 - train 0.44320 | val 0.74418

[I 2026-02-22 23:28:37,721] Trial 122 finished with value: -0.011637828792721593 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.30000000000000004, 'batch_size': 32, 'learning_rate': 1.5731084758389993e-05, 'weight_decay': 1.8636953730347344e-06, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 1.2182583913461973, 'early_stopping_min_delta': 0.006873653317441479}. Best is trial 90 with value: -0.011414558399902668.

  Epoch 029 - train 0.44912 | val 0.75802
  Regression -> MSE: 0.000260, MAE: 0.013148, R²: -0.0981
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.46735 | val 0.69729
  Epoch 016 - train 0.46561 | val 0.70150
  Regression -> MSE: 0.000248, MAE: 0.012575, R²: -0.0020
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.45110 | val 0.43296
  Epoch 016 - train 0.43376 | val 0.47734
  Regression -> MSE: 0.000690, MAE: 0.019453, R²: -0.0078
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.46914 | val 0.87910
  Epoch 016 - train 0.45733 | val 0.89481
  Regression -> MSE: 0.000313, MAE: 0.014409, R²: -0.0083
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.40704 | val 0.69475
  Epoch 016 - train 0.39138 | val 0.61950
  Regression -> MSE: 0.000351, MAE: 0.014594, R²: -0.0039
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.44740 | val 0.43259
  Epoch 020 - train 0.46655 | val 0.41535
  Epoch 030 - train 0.44810 | val 0.41024
  Epoch 036 - train 0.43601 | val 0.40953
  Regression -> MSE: 0.000202, MAE: 0.010148, R²: 0.0058
  Directional -> Accuracy: 0.6078, MCC: 0.2637, F1: 0.5238

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.41511 | val 1.03130
  Epoch 020 - train 0.41296 | val 1.03168
  Epoch 028 - train 0.42840 | val 1.04460
  Regression -> MSE: 0.000556, MAE: 0.018146, R²: -0.0013
  Directional -> Accuracy: 0.5106, MCC: 0.0045, F1: 0.0800

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.46272 | val 0.61443
  Epoch 016 - train 0.42942 | val 0.61824
  Regression -> MSE: 0.000247, MAE: 0.012303, R²: -0.0065
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.42605 | val 0.61097
  Epoch 016 - train 0.42389 | val 0.61518
  Regression -> MSE: 0.000616, MAE: 0.019619, R²: -0.0313
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.47191 | val 0.57991
  Epoch 016 - train 0.46588 | val 0.61582
  Regression -> MSE: 0.000387, MAE: 0.016095, R²: -0.0079
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.44702 | val 0.61853
  Epoch 016 - train 0.46911 | val 0.62676
  Regression -> MSE: 0.000245, MAE: 0.011645, R²: -0.0132
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.43059 | val 0.69650
  Epoch 020 - train 0.41711 | val 0.69577
  Epoch 026 - train 0.41225 | val 0.71112
  Regression -> MSE: 0.000315, MAE: 0.013523, R²: -0.0127
  Directional -> Accuracy: 0.5200, MCC: -0.0146, F1: 0.2500

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.47610 | val 0.56603
  Epoch 016 - train 0.46449 | val 0.57025
  Regression -> MSE: 0.000683, MAE: 0.019550, R²: -0.0086
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.48958 | val 0.45350
  Epoch 016 - train 0.45144 | val 0.46527
  Regression -> MSE: 0.000146, MAE: 0.009537, R²: -0.0532
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.38424 | val 0.69447
  Epoch 016 - train 0.39502 | val 0.69301
  Regression -> MSE: 0.000228, MAE: 0.010965, R²: -0.0147
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.45532 | val 1.21411
  Epoch 016 - train 0.45975 | val 1.25853
  Regression -> MSE: 0.000364, MAE: 0.016003, R²: -0.0052
  Directional -> Accuracy: 0.5000, MCC: -0.1225, F1: 0.0714

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.49270 | val 0.46160
  Epoch 020 - train 0.47711 | val 0.47864
  Epoch 021 - train 0.46734 | val 0.48145
  Regression -> MSE: 0.000109, MAE: 0.007931, R²: -0.0106
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.42045 | val 0.88509
  Epoch 020 - train 0.42649 | val 0.86745
  Epoch 030 - train 0.43447 | val 0.86632
  Epoch 040 - train 0.41052 | val 0.86931
  Epoch 047 - train 0.41027 | val 0.86929
  Regression -> MSE: 0.000162, MAE: 0.010014, R²: -0.0376
  Directional -> Accuracy: 0.5424, MCC: -0.0717, F1: 0.6747

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.43077 | val 0.48396
  Epoch 016 - train 0.43785 | val 0.49223
  Regression -> MSE: 0.000280, MAE: 0.013422, R²: -0.0292
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.43411 | val 0.74971
  Epoch 016 - train 0.42403 | val 0.76402
  Regression -> MSE: 0.000151, MAE: 0.008744, R²: -0.0121
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.46034 | val 0.83004
  Epoch 020 - train 0.45564 | val 0.83393
  Regression -> MSE: 0.000240, MAE: 0.010986, R²: -0.0594
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.45711 | val 0.62119
  Epoch 016 - train 0.46174 | val 0.62935
  Regression -> MSE: 0.000149, MAE: 0.008625, R²: -0.0367
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.40442 | val 0.53689
  Epoch 016 - train 0.40678 | val 0.54166
  Regression -> MSE: 0.000168, MAE: 0.010265, R²: -0.0198
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.53962 | val 0.62547
  Epoch 016 - train 0.51194 | val 0.64809
  Regression -> MSE: 0.000085, MAE: 0.007024, R²: -0.0026
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.43605 | val 0.61398
  Epoch 016 - train 0.43018 | val 0.61643
  Regression -> MSE: 0.000212, MAE: 0.011100, R²: -0.0012
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.39721 | val 0.35919
  Epoch 016 - train 0.42137 | val 0.35319
  Regression -> MSE: 0.000098, MAE: 0.008171, R²: -0.0598
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.46024 | val 0.32439
  Epoch 016 - train 0.44427 | val 0.34823
  Regression -> MSE: 0.000106, MAE: 0.008893, R²: -0.0301
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.45136 | val 0.42524
  Epoch 016 - train 0.43715 | val 0.51452
  Regression -> MSE: 0.000233, MAE: 0.012599, R²: -0.0047
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.44855 | val 0.50567
  Epoch 020 - train 0.44452 | val 0.50630
  Epoch 025 - train 0.44569 | val 0.50604
  Regression -> MSE: 0.000216, MAE: 0.008841, R²: -0.2986
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.43217 | val 0.32374
  Epoch 016 - train 0.44713 | val 0.33664
  Regression -> MSE: 0.000238, MAE: 0.011917, R²: -0.0059
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.43987 | val 0.90037
  Epoch 016 - train 0.46185 | val 0.89924
  Regression -> MSE: 0.000234, MAE: 0.010087, R²: -0.0134
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.48343 | val 0.58531
  Epoch 016 - train 0.48585 | val 0.60098
  Regression -> MSE: 0.000135, MAE: 0.008216, R²: -0.0022
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.47713 | val 0.61694
  Epoch 016 - train 0.49089 | val 0.62445
  Regression -> MSE: 0.000190, MAE: 0.010372, R²: -0.0087
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.39657 | val 0.55356
  Epoch 016 - train 0.38212 | val 0.55045
  Regression -> MSE: 0.000277, MAE: 0.010836, R²: -0.0573
  Directional -> Accuracy: 0.4384, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.44454 | val 0.35907
  Epoch 016 - train 0.44583 | val 0.35806
  Regression -> MSE: 0.000167, MAE: 0.010368, R²: -0.0009
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.39243 | val 0.47019
  Epoch 020 - train 0.41494 | val 0.50591
  Epoch 023 - train 0.38158 | val 0.51018
  Regression -> MSE: 0.000177, MAE: 0.010180, R²: 0.0169
  Directional -> Accuracy: 0.5455, MCC: 0.1668, F1: 0.6552

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.40128 | val 0.41576
  Epoch 020 - train 0.39770 | val 0.41446
  Epoch 030 - train 0.39479 | val 0.41617
  Epoch 032 - train 0.41077 | val 0.41702
  Regression -> MSE: 0.000380, MAE: 0.013728, R²: -0.1085
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.48957 | val 0.22817
  Epoch 016 - train 0.51944 | val 0.22961
  Regression -> MSE: 0.000111, MAE: 0.008332, R²: -0.0521
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.47955 | val 0.71630
  Epoch 016 - train 0.46589 | val 0.73257
  Regression -> MSE: 0.000219, MAE: 0.011285, R²: -0.0009
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.45197 | val 0.96295
  Epoch 020 - train 0.44896 | val 0.95241
  Epoch 030 - train 0.43634 | val 0.95914
  Regression -> MSE: 0.000079, MAE: 0.006984, R²: -0.0192
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.42241 | val 0.28136
  Epoch 016 - train 0.46243 | val 0.29253
  Regression -> MSE: 0.000311, MAE: 0.014039, R²: -0.0125
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.41985 | val 0.20171
  Epoch 016 - train 0.42918 | val 0.19748
  Regression -> MSE: 0.000253, MAE: 0.011473, R²: -0.0390
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.42916 | val 0.55567
  Epoch 020 - train 0.42654 | val 0.54592
  Epoch 030 - train 0.42849 | val 0.54113
  Epoch 040 - train 0.39578 | val 0.53747
  Epoch 050 - train 0.38982 | val 0.53769
  Regression -> MSE: 0.000090, MAE: 0.007654, R²: -0.1079
  Directional -> Accuracy: 0.5333, MCC: 0.2014, F1: 0.6789

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.46631 | val 0.59539
  Epoch 016 - train 0.45393 | val 0.60202
  Regression -> MSE: 0.000307, MAE: 0.014492, R²: -0.0002
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.45187 | val 0.49468
  Epoch 016 - train 0.41039 | val 0.49139
  Regression -> MSE: 0.000098, MAE: 0.007256, R²: 0.0002
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.53302 | val 0.64875
  Epoch 016 - train 0.46389 | val 0.66771
  Regression -> MSE: 0.000172, MAE: 0.009704, R²: 0.0005
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.42315 | val 0.67241
  Epoch 016 - train 0.42931 | val 0.69310
  Regression -> MSE: 0.000228, MAE: 0.011915, R²: -0.0245
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.43769 | val 0.52932
  Epoch 016 - train 0.44161 | val 0.53260
  Regression -> MSE: 0.000092, MAE: 0.007634, R²: -0.0004
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.49821 | val 0.98054
  Epoch 016 - train 0.51093 | val 1.12027
  Regression -> MSE: 0.000168, MAE: 0.010313, R²: -0.0265
  Directional -> Accuracy: 0.4815, MCC: 0.0000, F1: 0.0000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.43216 | val 0.60941
  Epoch 016 - train 0.41393 | val 0.61086
  Regression -> MSE: 0.000121, MAE: 0.008981, R²: -0.0444
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.49215 | val 0.76300

[I 2026-02-22 23:30:01,514] Trial 123 finished with value: -0.011465641245763934 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 32, 'learning_rate': 6.9669808357855625e-06, 'weight_decay': 4.652557685057509e-06, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 1.256665031976291, 'early_stopping_min_delta': 0.006430625559920244}. Best is trial 90 with value: -0.011414558399902668.

  Epoch 016 - train 0.50254 | val 0.75875
  Regression -> MSE: 0.000244, MAE: 0.012338, R²: -0.0278
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.46300 | val 0.82529
  Epoch 019 - train 0.46310 | val 0.80722
  Regression -> MSE: 0.000253, MAE: 0.012803, R²: -0.0208
  Directional -> Accuracy: 0.4156, MCC: -0.1456, F1: 0.5455

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.54984 | val 0.45650
  Epoch 016 - train 0.52182 | val 0.76564
  Regression -> MSE: 0.000700, MAE: 0.019651, R²: -0.0232
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.48395 | val 0.93905
  Epoch 016 - train 0.48314 | val 1.02745
  Regression -> MSE: 0.000311, MAE: 0.014455, R²: -0.0016
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.40948 | val 0.38991
  Epoch 016 - train 0.38549 | val 0.37305
  Regression -> MSE: 0.000351, MAE: 0.014602, R²: -0.0034
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.46267 | val 0.43250
  Epoch 020 - train 0.43239 | val 0.43437
  Epoch 025 - train 0.45853 | val 0.43520
  Regression -> MSE: 0.000199, MAE: 0.009606, R²: 0.0220
  Directional -> Accuracy: 0.6471, MCC: 0.2938, F1: 0.7097

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.44026 | val 1.08046
  Epoch 016 - train 0.41169 | val 1.09616
  Regression -> MSE: 0.000579, MAE: 0.018578, R²: -0.0435
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.43891 | val 0.61286
  Epoch 016 - train 0.44860 | val 0.61193
  Regression -> MSE: 0.000247, MAE: 0.012259, R²: -0.0051
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.46005 | val 0.70307
  Epoch 016 - train 0.46379 | val 0.75362
  Regression -> MSE: 0.000645, MAE: 0.020163, R²: -0.0791
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.45286 | val 0.54621
  Epoch 016 - train 0.43673 | val 0.55031
  Regression -> MSE: 0.000404, MAE: 0.016121, R²: -0.0524
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.47930 | val 0.68937
  Epoch 016 - train 0.45801 | val 0.69534
  Regression -> MSE: 0.000244, MAE: 0.011695, R²: -0.0104
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.42409 | val 0.73413
  Epoch 020 - train 0.43322 | val 0.76231
  Epoch 024 - train 0.42465 | val 0.76642
  Regression -> MSE: 0.000314, MAE: 0.013530, R²: -0.0088
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.54013 | val 0.55198
  Epoch 020 - train 0.51908 | val 0.55535
  Epoch 025 - train 0.52135 | val 0.55689
  Regression -> MSE: 0.000715, MAE: 0.020465, R²: -0.0553
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.48983 | val 0.46827
  Epoch 016 - train 0.48471 | val 0.48685
  Regression -> MSE: 0.000141, MAE: 0.009345, R²: -0.0211
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.40858 | val 0.67150
  Epoch 016 - train 0.39891 | val 0.67425
  Regression -> MSE: 0.000225, MAE: 0.010711, R²: 0.0011
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.45546 | val 1.26265
  Epoch 016 - train 0.45762 | val 1.29936
  Regression -> MSE: 0.000362, MAE: 0.016053, R²: -0.0007
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.47285 | val 0.51329
  Epoch 016 - train 0.49879 | val 0.53093
  Regression -> MSE: 0.000110, MAE: 0.008187, R²: -0.0178
  Directional -> Accuracy: 0.4571, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.43420 | val 0.99428
  Epoch 016 - train 0.42827 | val 1.02666
  Regression -> MSE: 0.000157, MAE: 0.009906, R²: -0.0089
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.46539 | val 0.47330
  Epoch 016 - train 0.45161 | val 0.47181
  Regression -> MSE: 0.000274, MAE: 0.013129, R²: -0.0066
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.36718 | val 0.63945
  Epoch 020 - train 0.34695 | val 0.63617
  Epoch 022 - train 0.35079 | val 0.64034
  Regression -> MSE: 0.000157, MAE: 0.008758, R²: -0.0511
  Directional -> Accuracy: 0.5538, MCC: 0.0963, F1: 0.6027

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.43912 | val 0.80051
  Epoch 020 - train 0.43542 | val 0.79472
  Epoch 030 - train 0.43069 | val 0.79179
  Epoch 032 - train 0.45133 | val 0.79167
  Regression -> MSE: 0.000328, MAE: 0.013725, R²: -0.4516
  Directional -> Accuracy: 0.3600, MCC: -0.2812, F1: 0.1429

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.47930 | val 0.77930
  Epoch 016 - train 0.49039 | val 0.96409
  Regression -> MSE: 0.000144, MAE: 0.008387, R²: -0.0053
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.42548 | val 0.55744
  Epoch 016 - train 0.43758 | val 0.57111
  Regression -> MSE: 0.000181, MAE: 0.010341, R²: -0.0943
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.46475 | val 0.65090
  Epoch 016 - train 0.46484 | val 0.69260
  Regression -> MSE: 0.000085, MAE: 0.007037, R²: 0.0037
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.46322 | val 0.62420
  Epoch 020 - train 0.44895 | val 0.64539
  Epoch 022 - train 0.44385 | val 0.64787
  Regression -> MSE: 0.000208, MAE: 0.010942, R²: 0.0181
  Directional -> Accuracy: 0.6212, MCC: 0.2383, F1: 0.5902

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.39247 | val 0.35066
  Epoch 020 - train 0.41039 | val 0.34028
  Epoch 030 - train 0.40656 | val 0.33772
  Epoch 038 - train 0.39268 | val 0.33486
  Regression -> MSE: 0.000102, MAE: 0.008141, R²: -0.1083
  Directional -> Accuracy: 0.5893, MCC: 0.2195, F1: 0.5490

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.46088 | val 0.35044
  Epoch 016 - train 0.48485 | val 0.40061
  Regression -> MSE: 0.000112, MAE: 0.009112, R²: -0.0907
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.49366 | val 0.43144
  Epoch 016 - train 0.48799 | val 0.49118
  Regression -> MSE: 0.000232, MAE: 0.012532, R²: -0.0006
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.45668 | val 0.57382
  Epoch 016 - train 0.46105 | val 0.58791
  Regression -> MSE: 0.000181, MAE: 0.007977, R²: -0.0874
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.49970 | val 0.29460
  Epoch 016 - train 0.47843 | val 0.29354
  Regression -> MSE: 0.000237, MAE: 0.011863, R²: -0.0005
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.43950 | val 0.94912
  Epoch 016 - train 0.49456 | val 1.02592
  Regression -> MSE: 0.000234, MAE: 0.010099, R²: -0.0141
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.45725 | val 0.61388
  Epoch 016 - train 0.47686 | val 0.63022
  Regression -> MSE: 0.000138, MAE: 0.008299, R²: -0.0211
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.55235 | val 0.69737
  Epoch 016 - train 0.53995 | val 0.73287
  Regression -> MSE: 0.000189, MAE: 0.010563, R²: -0.0018
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.39218 | val 0.56675
  Epoch 020 - train 0.40202 | val 0.56391
  Epoch 026 - train 0.39820 | val 0.56096
  Regression -> MSE: 0.000287, MAE: 0.011595, R²: -0.0961
  Directional -> Accuracy: 0.4795, MCC: -0.0162, F1: 0.4571

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.47739 | val 0.37597
  Epoch 016 - train 0.46183 | val 0.37641
  Regression -> MSE: 0.000169, MAE: 0.010380, R²: -0.0152
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.42732 | val 0.46639
  Epoch 020 - train 0.39747 | val 0.43931
  Epoch 029 - train 0.41400 | val 0.44574
  Regression -> MSE: 0.000188, MAE: 0.010576, R²: -0.0461
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.43317 | val 0.40098
  Epoch 020 - train 0.41966 | val 0.39097
  Epoch 028 - train 0.42295 | val 0.38960
  Regression -> MSE: 0.000419, MAE: 0.015377, R²: -0.2220
  Directional -> Accuracy: 0.4478, MCC: 0.0435, F1: 0.0976

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.51462 | val 0.26435
  Epoch 016 - train 0.47514 | val 0.30952
  Regression -> MSE: 0.000124, MAE: 0.008434, R²: -0.1766
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.51990 | val 0.85211
  Epoch 016 - train 0.51641 | val 0.90689
  Regression -> MSE: 0.000225, MAE: 0.011481, R²: -0.0281
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.43600 | val 1.03070
  Epoch 016 - train 0.43337 | val 1.06347
  Regression -> MSE: 0.000096, MAE: 0.007629, R²: -0.2321
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.45478 | val 0.28860
  Epoch 016 - train 0.45797 | val 0.29001
  Regression -> MSE: 0.000315, MAE: 0.014200, R²: -0.0225
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.51126 | val 0.23025
  Epoch 016 - train 0.50424 | val 0.23061
  Regression -> MSE: 0.000264, MAE: 0.011531, R²: -0.0839
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.42762 | val 0.62718
  Epoch 016 - train 0.44468 | val 0.64594
  Regression -> MSE: 0.000082, MAE: 0.007049, R²: -0.0123
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.47570 | val 0.66846
  Epoch 016 - train 0.49359 | val 0.70502
  Regression -> MSE: 0.000314, MAE: 0.014508, R²: -0.0224
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.48741 | val 0.51111
  Epoch 020 - train 0.46916 | val 0.49905
  Epoch 030 - train 0.44896 | val 0.49391
  Epoch 040 - train 0.43222 | val 0.48903
  Regression -> MSE: 0.000105, MAE: 0.007262, R²: -0.0654
  Directional -> Accuracy: 0.4773, MCC: -0.2127, F1: 0.6349

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.53103 | val 0.66046
  Epoch 016 - train 0.49654 | val 0.66604
  Regression -> MSE: 0.000172, MAE: 0.009718, R²: -0.0010
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.40080 | val 0.60395
  Epoch 016 - train 0.41790 | val 0.63442
  Regression -> MSE: 0.000223, MAE: 0.011733, R²: -0.0020
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.45920 | val 0.59306
  Epoch 016 - train 0.46277 | val 0.63468
  Regression -> MSE: 0.000092, MAE: 0.007657, R²: -0.0021
  Directional -> Accuracy: 0.4211, MCC: -0.1543, F1: 0.5352

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.49496 | val 0.98849
  Epoch 016 - train 0.49411 | val 1.09917
  Regression -> MSE: 0.000168, MAE: 0.010323, R²: -0.0289
  Directional -> Accuracy: 0.4815, MCC: 0.0000, F1: 0.0000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.46487 | val 0.64458
  Epoch 016 - train 0.42421 | val 0.66539
  Regression -> MSE: 0.000122, MAE: 0.008987, R²: -0.0530
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.51515 | val 0.91219

[I 2026-02-22 23:31:18,585] Trial 124 finished with value: -0.011600110151292609 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 32, 'learning_rate': 7.314993020537702e-06, 'weight_decay': 2.4314719232087087e-06, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 1.3311393323183203, 'early_stopping_min_delta': 0.008200378143553245}. Best is trial 90 with value: -0.011414558399902668.

  Epoch 016 - train 0.51562 | val 0.99953
  Regression -> MSE: 0.000238, MAE: 0.012529, R²: -0.0035
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.52366 | val 1.14113
  Epoch 016 - train 0.50100 | val 1.16224
  Regression -> MSE: 0.000269, MAE: 0.013239, R²: -0.0884
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.48683 | val 0.46046
  Epoch 016 - train 0.45683 | val 0.48612
  Regression -> MSE: 0.000708, MAE: 0.019767, R²: -0.0342
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.49584 | val 0.98707
  Epoch 020 - train 0.49682 | val 0.98722
  Epoch 026 - train 0.51893 | val 0.98533
  Regression -> MSE: 0.000317, MAE: 0.014344, R²: -0.0212
  Directional -> Accuracy: 0.5106, MCC: 0.0092, F1: 0.5660

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.40174 | val 0.51627
  Epoch 016 - train 0.39610 | val 0.54898
  Regression -> MSE: 0.000384, MAE: 0.015163, R²: -0.1006
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.50058 | val 0.49509
  Epoch 016 - train 0.48058 | val 0.52284
  Regression -> MSE: 0.000204, MAE: 0.010121, R²: -0.0017
  Directional -> Accuracy: 0.5098, MCC: 0.1289, F1: 0.1935

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.43958 | val 1.18675
  Epoch 020 - train 0.45576 | val 1.16755
  Epoch 030 - train 0.50188 | val 1.18024
  Regression -> MSE: 0.000560, MAE: 0.018168, R²: -0.0094
  Directional -> Accuracy: 0.5532, MCC: 0.1296, F1: 0.6316

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.49190 | val 0.68431
  Epoch 016 - train 0.48981 | val 0.68214
  Regression -> MSE: 0.000247, MAE: 0.011938, R²: -0.0064
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.48338 | val 0.75821
  Epoch 020 - train 0.45159 | val 0.62577
  Epoch 030 - train 0.44303 | val 0.58735
  Epoch 040 - train 0.45462 | val 0.58075
  Epoch 050 - train 0.47087 | val 0.57521
  Regression -> MSE: 0.000641, MAE: 0.019830, R²: -0.0727
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.44720 | val 0.59036
  Epoch 020 - train 0.47174 | val 0.57733
  Epoch 030 - train 0.44869 | val 0.58136
  Regression -> MSE: 0.000408, MAE: 0.016149, R²: -0.0637
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.47379 | val 0.77139
  Epoch 016 - train 0.47124 | val 0.77798
  Regression -> MSE: 0.000242, MAE: 0.011982, R²: -0.0019
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.46912 | val 0.75245
  Epoch 020 - train 0.42691 | val 0.77490
  Epoch 022 - train 0.48250 | val 0.77477
  Regression -> MSE: 0.000336, MAE: 0.013698, R²: -0.0822
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.53717 | val 0.61494
  Epoch 016 - train 0.49013 | val 0.62786
  Regression -> MSE: 0.000680, MAE: 0.019596, R²: -0.0034
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.50604 | val 0.49319
  Epoch 016 - train 0.52104 | val 0.50227
  Regression -> MSE: 0.000142, MAE: 0.009386, R²: -0.0276
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.40171 | val 0.72551
  Epoch 016 - train 0.43855 | val 0.74948
  Regression -> MSE: 0.000229, MAE: 0.010821, R²: -0.0185
  Directional -> Accuracy: 0.4918, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.50161 | val 1.40007
  Epoch 016 - train 0.50651 | val 1.42108
  Regression -> MSE: 0.000368, MAE: 0.015941, R²: -0.0161
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.51515 | val 0.51486
  Epoch 016 - train 0.52679 | val 0.51067
  Regression -> MSE: 0.000108, MAE: 0.008004, R²: -0.0024
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.48270 | val 1.15818
  Epoch 020 - train 0.46757 | val 1.30902
  Epoch 021 - train 0.45789 | val 1.30594
  Regression -> MSE: 0.000158, MAE: 0.009900, R²: -0.0133
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.48574 | val 0.53256
  Epoch 016 - train 0.48921 | val 0.52484
  Regression -> MSE: 0.000289, MAE: 0.013821, R²: -0.0614
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.41259 | val 0.75710
  Epoch 016 - train 0.40238 | val 0.75284
  Regression -> MSE: 0.000165, MAE: 0.009074, R²: -0.1063
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.49384 | val 0.93837
  Epoch 020 - train 0.45159 | val 0.92972
  Epoch 021 - train 0.46660 | val 0.92838
  Regression -> MSE: 0.000244, MAE: 0.011166, R²: -0.0797
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.45965 | val 0.80313
  Epoch 016 - train 0.47250 | val 0.95750
  Regression -> MSE: 0.000145, MAE: 0.008486, R²: -0.0143
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.46155 | val 0.54629
  Epoch 020 - train 0.44611 | val 0.54614
  Epoch 021 - train 0.44472 | val 0.54575
  Regression -> MSE: 0.000176, MAE: 0.010518, R²: -0.0635
  Directional -> Accuracy: 0.4091, MCC: -0.1861, F1: 0.3390

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.51362 | val 0.70713
  Epoch 016 - train 0.53065 | val 0.70945
  Regression -> MSE: 0.000093, MAE: 0.007453, R²: -0.0958
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.49464 | val 0.69079
  Epoch 016 - train 0.49489 | val 0.69382
  Regression -> MSE: 0.000215, MAE: 0.011052, R²: -0.0147
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.43341 | val 0.35468
  Epoch 020 - train 0.41423 | val 0.35262
  Epoch 022 - train 0.40556 | val 0.35166
  Regression -> MSE: 0.000091, MAE: 0.007938, R²: 0.0064
  Directional -> Accuracy: 0.5000, MCC: -0.0565, F1: 0.6111

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.53010 | val 0.37125
  Epoch 016 - train 0.52365 | val 0.37886
  Regression -> MSE: 0.000115, MAE: 0.009181, R²: -0.1166
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.50894 | val 0.45642
  Epoch 016 - train 0.47066 | val 0.46801
  Regression -> MSE: 0.000232, MAE: 0.012578, R²: -0.0029
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.51539 | val 0.74886
  Epoch 016 - train 0.51586 | val 0.80082
  Regression -> MSE: 0.000174, MAE: 0.007891, R²: -0.0471
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.52992 | val 0.29529
  Epoch 020 - train 0.52893 | val 0.38959
  Epoch 027 - train 0.52016 | val 0.57234
  Regression -> MSE: 0.000235, MAE: 0.011877, R²: 0.0061
  Directional -> Accuracy: 0.5366, MCC: 0.0241, F1: 0.6780

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.49709 | val 1.01790
  Epoch 020 - train 0.50829 | val 0.98231
  Epoch 030 - train 0.51098 | val 0.98439
  Epoch 032 - train 0.50148 | val 0.98511
  Regression -> MSE: 0.000239, MAE: 0.009952, R²: -0.0356
  Directional -> Accuracy: 0.5581, MCC: 0.1154, F1: 0.4571

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.49381 | val 0.70474
  Epoch 020 - train 0.47645 | val 0.68531
  Epoch 030 - train 0.49171 | val 0.68989
  Epoch 035 - train 0.49228 | val 0.69119
  Regression -> MSE: 0.000131, MAE: 0.008385, R²: 0.0301
  Directional -> Accuracy: 0.4186, MCC: -0.1934, F1: 0.5098

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.49260 | val 0.67997
  Epoch 020 - train 0.47752 | val 0.68091
  Epoch 028 - train 0.47417 | val 0.68455
  Regression -> MSE: 0.000289, MAE: 0.013663, R²: -0.5343
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.41583 | val 0.91453
  Epoch 016 - train 0.44416 | val 0.88262
  Regression -> MSE: 0.000262, MAE: 0.010626, R²: -0.0009
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.48477 | val 0.35938
  Epoch 020 - train 0.50173 | val 0.35147
  Epoch 030 - train 0.45814 | val 0.35167
  Epoch 038 - train 0.45453 | val 0.35793
  Regression -> MSE: 0.000166, MAE: 0.010401, R²: 0.0062
  Directional -> Accuracy: 0.4737, MCC: -0.0529, F1: 0.4444

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.43968 | val 0.51784
  Epoch 016 - train 0.41926 | val 0.52232
  Regression -> MSE: 0.000180, MAE: 0.010264, R²: -0.0020
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.44374 | val 0.46796
  Epoch 016 - train 0.43340 | val 0.47609
  Regression -> MSE: 0.000344, MAE: 0.011965, R²: -0.0037
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.53972 | val 0.27463
  Epoch 016 - train 0.53286 | val 0.28717
  Regression -> MSE: 0.000126, MAE: 0.008483, R²: -0.2005
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.48038 | val 0.88052
  Epoch 016 - train 0.49109 | val 0.88557
  Regression -> MSE: 0.000220, MAE: 0.011335, R²: -0.0056
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.48562 | val 1.15099
  Epoch 016 - train 0.46600 | val 1.15196
  Regression -> MSE: 0.000083, MAE: 0.007093, R²: -0.0651
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.48785 | val 0.34130
  Epoch 016 - train 0.47234 | val 0.34414
  Regression -> MSE: 0.000334, MAE: 0.015135, R²: -0.0857
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.54499 | val 0.19246
  Epoch 020 - train 0.52680 | val 0.18146
  Epoch 030 - train 0.53134 | val 0.16804
  Epoch 040 - train 0.51764 | val 0.17056
  Epoch 041 - train 0.51532 | val 0.17071
  Regression -> MSE: 0.000254, MAE: 0.011467, R²: -0.0411
  Directional -> Accuracy: 0.4737, MCC: -0.1021, F1: 0.6000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.46020 | val 0.63547
  Epoch 016 - train 0.46741 | val 0.63370
  Regression -> MSE: 0.000081, MAE: 0.007074, R²: -0.0032
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.53674 | val 0.69125
  Epoch 016 - train 0.52714 | val 0.70080
  Regression -> MSE: 0.000312, MAE: 0.014494, R²: -0.0163
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.43649 | val 0.58604
  Epoch 020 - train 0.48166 | val 0.54644
  Epoch 030 - train 0.46455 | val 0.54350
  Epoch 039 - train 0.47337 | val 0.54537
  Regression -> MSE: 0.000111, MAE: 0.007229, R²: -0.1253
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.50795 | val 0.74992
  Epoch 016 - train 0.52691 | val 0.76904
  Regression -> MSE: 0.000173, MAE: 0.009487, R²: -0.0046
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.42956 | val 0.62116
  Epoch 016 - train 0.43301 | val 0.61294
  Regression -> MSE: 0.000225, MAE: 0.011800, R²: -0.0085
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.45797 | val 0.65847
  Epoch 016 - train 0.45198 | val 0.69901
  Regression -> MSE: 0.000093, MAE: 0.007678, R²: -0.0061
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.55963 | val 0.99341
  Epoch 016 - train 0.51954 | val 1.01476
  Regression -> MSE: 0.000165, MAE: 0.010304, R²: -0.0105
  Directional -> Accuracy: 0.4815, MCC: 0.0000, F1: 0.0000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.59140 | val 0.82792
  Epoch 016 - train 0.58702 | val 0.84401
  Regression -> MSE: 0.000137, MAE: 0.009287, R²: -0.1860
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.47112 | val 1.04242

[I 2026-02-22 23:32:35,576] Trial 125 finished with value: -0.011552120043685428 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 32, 'learning_rate': 9.349092356292024e-06, 'weight_decay': 5.708278286110313e-06, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 1.6953843048314687, 'early_stopping_min_delta': 0.006208305199845381}. Best is trial 90 with value: -0.011414558399902668.

  Epoch 016 - train 0.48915 | val 1.08197
  Regression -> MSE: 0.000237, MAE: 0.012404, R²: 0.0002
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.47321 | val 0.83916
  Epoch 020 - train 0.50094 | val 0.83866
  Epoch 026 - train 0.48055 | val 0.84059
  Regression -> MSE: 0.000265, MAE: 0.013128, R²: -0.0721
  Directional -> Accuracy: 0.4935, MCC: 0.1347, F1: 0.6355

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.43413 | val 0.49718
  Epoch 020 - train 0.44596 | val 0.50175
  Epoch 021 - train 0.43226 | val 0.49899
  Regression -> MSE: 0.000713, MAE: 0.019868, R²: -0.0413
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.46981 | val 1.02276
  Epoch 020 - train 0.47873 | val 1.01675
  Epoch 021 - train 0.48939 | val 1.01854
  Regression -> MSE: 0.000310, MAE: 0.014419, R²: 0.0005
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.40460 | val 0.53514
  Epoch 020 - train 0.40239 | val 0.54309
  Epoch 021 - train 0.39862 | val 0.54273
  Regression -> MSE: 0.000352, MAE: 0.014646, R²: -0.0075
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.48506 | val 0.71311
  Epoch 020 - train 0.46792 | val 0.66352
  Epoch 021 - train 0.45803 | val 0.65106
  Regression -> MSE: 0.000210, MAE: 0.010213, R²: -0.0317
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.45752 | val 1.28139
  Epoch 020 - train 0.46168 | val 1.26870
  Epoch 021 - train 0.45416 | val 1.27794
  Regression -> MSE: 0.000567, MAE: 0.018304, R²: -0.0217
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.49097 | val 0.82579
  Epoch 020 - train 0.51111 | val 0.82275
  Epoch 021 - train 0.49426 | val 0.82477
  Regression -> MSE: 0.000246, MAE: 0.012113, R²: -0.0009
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.49352 | val 0.70223
  Epoch 020 - train 0.48291 | val 0.64324
  Epoch 030 - train 0.47978 | val 0.63983
  Epoch 037 - train 0.47083 | val 0.63866
  Regression -> MSE: 0.000628, MAE: 0.019447, R²: -0.0504
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.47885 | val 0.64480
  Epoch 020 - train 0.45277 | val 0.64852
  Epoch 021 - train 0.47368 | val 0.65276
  Regression -> MSE: 0.000395, MAE: 0.015960, R²: -0.0290
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.46493 | val 0.71716
  Epoch 020 - train 0.49950 | val 0.73037
  Epoch 021 - train 0.46653 | val 0.73143
  Regression -> MSE: 0.000242, MAE: 0.011755, R²: -0.0010
  Directional -> Accuracy: 0.4286, MCC: -0.0355, F1: 0.5833

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.44029 | val 1.16023
  Epoch 020 - train 0.44222 | val 1.21618
  Epoch 021 - train 0.44634 | val 1.21344
  Regression -> MSE: 0.000317, MAE: 0.013564, R²: -0.0205
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.49698 | val 0.70757
  Epoch 020 - train 0.47672 | val 0.70259
  Epoch 021 - train 0.49714 | val 0.70804
  Regression -> MSE: 0.000684, MAE: 0.019735, R²: -0.0102
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.52436 | val 0.63695
  Epoch 020 - train 0.50193 | val 0.72858
  Epoch 021 - train 0.48200 | val 0.76175
  Regression -> MSE: 0.000144, MAE: 0.009480, R²: -0.0424
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.46056 | val 0.70554
  Epoch 020 - train 0.41566 | val 0.69766
  Epoch 030 - train 0.44315 | val 0.69197
  Epoch 040 - train 0.40425 | val 0.69295
  Epoch 042 - train 0.41402 | val 0.69064
  Regression -> MSE: 0.000246, MAE: 0.011658, R²: -0.0932
  Directional -> Accuracy: 0.4918, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.47705 | val 1.38451
  Epoch 020 - train 0.49550 | val 1.37784
  Epoch 030 - train 0.47200 | val 1.38944
  Epoch 031 - train 0.44554 | val 1.38410
  Regression -> MSE: 0.000373, MAE: 0.015969, R²: -0.0302
  Directional -> Accuracy: 0.5769, MCC: 0.1488, F1: 0.5417

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.51006 | val 0.50847
  Epoch 020 - train 0.48032 | val 0.52651
  Epoch 023 - train 0.47835 | val 0.53221
  Regression -> MSE: 0.000107, MAE: 0.007985, R²: 0.0099
  Directional -> Accuracy: 0.5429, MCC: 0.1191, F1: 0.4839

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.44620 | val 1.07010
  Epoch 020 - train 0.44420 | val 1.09827
  Epoch 026 - train 0.42976 | val 1.09851
  Regression -> MSE: 0.000156, MAE: 0.010002, R²: -0.0007
  Directional -> Accuracy: 0.5085, MCC: 0.1829, F1: 0.4314

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.47821 | val 0.51330
  Epoch 020 - train 0.47259 | val 0.50955
  Epoch 021 - train 0.46736 | val 0.50805
  Regression -> MSE: 0.000274, MAE: 0.013114, R²: -0.0064
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.40701 | val 0.79096
  Epoch 020 - train 0.40439 | val 0.79225
  Epoch 023 - train 0.39026 | val 0.79001
  Regression -> MSE: 0.000161, MAE: 0.009147, R²: -0.0764
  Directional -> Accuracy: 0.4615, MCC: -0.0074, F1: 0.3860

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.49818 | val 1.00808
  Epoch 020 - train 0.50846 | val 1.03879
  Epoch 021 - train 0.47189 | val 1.02829
  Regression -> MSE: 0.000232, MAE: 0.010962, R²: -0.0266
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.49360 | val 0.75925
  Epoch 020 - train 0.49859 | val 0.75679
  Epoch 021 - train 0.50607 | val 0.74854
  Regression -> MSE: 0.000146, MAE: 0.008523, R²: -0.0202
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.46460 | val 0.60427
  Epoch 020 - train 0.47478 | val 0.60386
  Epoch 021 - train 0.44226 | val 0.60614
  Regression -> MSE: 0.000165, MAE: 0.010536, R²: 0.0009
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.50010 | val 0.73814
  Epoch 020 - train 0.51038 | val 0.74281
  Epoch 021 - train 0.49794 | val 0.75219
  Regression -> MSE: 0.000085, MAE: 0.007042, R²: 0.0011
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.47816 | val 0.76016
  Epoch 020 - train 0.52398 | val 0.77250
  Epoch 021 - train 0.48446 | val 0.76319
  Regression -> MSE: 0.000213, MAE: 0.011304, R²: -0.0074
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.42679 | val 0.33413
  Epoch 020 - train 0.42504 | val 0.32234
  Epoch 030 - train 0.41815 | val 0.31130
  Epoch 040 - train 0.40253 | val 0.30376
  Epoch 048 - train 0.41201 | val 0.30602
  Regression -> MSE: 0.000096, MAE: 0.007840, R²: -0.0397
  Directional -> Accuracy: 0.5536, MCC: 0.1704, F1: 0.4681

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.52829 | val 0.34125
  Epoch 020 - train 0.47668 | val 0.34038
  Epoch 021 - train 0.47943 | val 0.33892
  Regression -> MSE: 0.000103, MAE: 0.008717, R²: -0.0005
  Directional -> Accuracy: 0.5652, MCC: 0.1154, F1: 0.5000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.48503 | val 0.46589
  Epoch 020 - train 0.50904 | val 0.47784
  Epoch 021 - train 0.49089 | val 0.47610
  Regression -> MSE: 0.000232, MAE: 0.012569, R²: -0.0030
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.49145 | val 0.78104
  Epoch 020 - train 0.48088 | val 0.76334
  Epoch 021 - train 0.48521 | val 0.76684
  Regression -> MSE: 0.000171, MAE: 0.007839, R²: -0.0258
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.49142 | val 0.29622
  Epoch 020 - train 0.52902 | val 0.33912
  Epoch 028 - train 0.50799 | val 0.35430
  Regression -> MSE: 0.000239, MAE: 0.011807, R²: -0.0095
  Directional -> Accuracy: 0.5854, MCC: 0.1890, F1: 0.7119

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.56619 | val 1.45919
  Epoch 020 - train 0.57378 | val 1.56101
  Epoch 021 - train 0.54951 | val 1.56221
  Regression -> MSE: 0.000237, MAE: 0.010258, R²: -0.0270
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.54490 | val 0.83037
  Epoch 020 - train 0.52131 | val 0.88119
  Epoch 021 - train 0.52518 | val 0.89496
  Regression -> MSE: 0.000142, MAE: 0.008517, R²: -0.0490
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.51290 | val 0.75340
  Epoch 020 - train 0.47456 | val 0.75393
  Epoch 021 - train 0.50234 | val 0.75116
  Regression -> MSE: 0.000189, MAE: 0.010559, R²: -0.0012
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.41436 | val 0.63995
  Epoch 020 - train 0.38975 | val 0.62936
  Epoch 030 - train 0.40311 | val 0.62231
  Epoch 040 - train 0.41303 | val 0.61833
  Epoch 050 - train 0.38024 | val 0.61629
  Regression -> MSE: 0.000366, MAE: 0.013227, R²: -0.3969
  Directional -> Accuracy: 0.5068, MCC: 0.2396, F1: 0.2174

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.49835 | val 0.36620
  Epoch 020 - train 0.46495 | val 0.46519
  Epoch 029 - train 0.49644 | val 0.46525
  Regression -> MSE: 0.000164, MAE: 0.010324, R²: 0.0163
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.44625 | val 0.50682
  Epoch 020 - train 0.42483 | val 0.51261
  Epoch 027 - train 0.40632 | val 0.51999
  Regression -> MSE: 0.000181, MAE: 0.010392, R²: -0.0070
  Directional -> Accuracy: 0.5455, MCC: 0.0932, F1: 0.5455

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.46370 | val 0.41605
  Epoch 020 - train 0.47252 | val 0.41222
  Epoch 028 - train 0.45040 | val 0.41163
  Regression -> MSE: 0.000333, MAE: 0.012139, R²: 0.0289
  Directional -> Accuracy: 0.6567, MCC: 0.2934, F1: 0.7089

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.51844 | val 0.22965
  Epoch 020 - train 0.51824 | val 0.22892
  Epoch 030 - train 0.49884 | val 0.22979
  Epoch 031 - train 0.48807 | val 0.22872
  Regression -> MSE: 0.000111, MAE: 0.008437, R²: -0.0602
  Directional -> Accuracy: 0.5116, MCC: 0.0074, F1: 0.6557

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.49223 | val 0.84264
  Epoch 020 - train 0.45845 | val 0.83929
  Epoch 024 - train 0.47693 | val 0.83611
  Regression -> MSE: 0.000228, MAE: 0.011490, R²: -0.0454
  Directional -> Accuracy: 0.4912, MCC: 0.0187, F1: 0.6027

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.48193 | val 1.30182
  Epoch 020 - train 0.46745 | val 1.37036
  Epoch 021 - train 0.48588 | val 1.38032
  Regression -> MSE: 0.000092, MAE: 0.007488, R²: -0.1801
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.46327 | val 0.38952
  Epoch 020 - train 0.47493 | val 0.41472
  Epoch 021 - train 0.47608 | val 0.42232
  Regression -> MSE: 0.000319, MAE: 0.014463, R²: -0.0367
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.51627 | val 0.23921
  Epoch 020 - train 0.52448 | val 0.31498
  Epoch 021 - train 0.50492 | val 0.31148
  Regression -> MSE: 0.000254, MAE: 0.011454, R²: -0.0435
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.45515 | val 0.67008
  Epoch 020 - train 0.45125 | val 0.65603
  Epoch 021 - train 0.47878 | val 0.65730
  Regression -> MSE: 0.000081, MAE: 0.007093, R²: -0.0008
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.51970 | val 0.87229
  Epoch 020 - train 0.48517 | val 0.84596
  Epoch 021 - train 0.47258 | val 0.83665
  Regression -> MSE: 0.000310, MAE: 0.014531, R²: -0.0097
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.51646 | val 0.53620
  Epoch 020 - train 0.49517 | val 0.53512
  Epoch 030 - train 0.51641 | val 0.54325
  Epoch 034 - train 0.46626 | val 0.54360
  Regression -> MSE: 0.000095, MAE: 0.007332, R²: 0.0345
  Directional -> Accuracy: 0.4545, MCC: 0.0029, F1: 0.2500

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.54233 | val 0.88719
  Epoch 020 - train 0.53489 | val 0.91657
  Epoch 021 - train 0.56173 | val 0.91190
  Regression -> MSE: 0.000176, MAE: 0.010191, R²: -0.0214
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.49523 | val 0.67344
  Epoch 020 - train 0.44616 | val 0.67109
  Epoch 021 - train 0.45149 | val 0.66824

[I 2026-02-22 23:38:02,605] Trial 126 finished with value: -0.011530399953905984 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 5.330230494491554e-06, 'weight_decay': 3.0299547904746242e-06, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 50, 'huber_delta': 1.7679406011176484, 'early_stopping_min_delta': 0.007940400589707184}. Best is trial 90 with value: -0.011414558399902668.

  Epoch 024 - train 0.48007 | val 0.91263
  Regression -> MSE: 0.000244, MAE: 0.012407, R²: -0.0269
  Directional -> Accuracy: 0.5410, MCC: 0.0871, F1: 0.1250

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.47047 | val 0.92575
  Epoch 015 - train 0.44202 | val 0.94567
  Regression -> MSE: 0.000255, MAE: 0.012872, R²: -0.0315
  Directional -> Accuracy: 0.4416, MCC: -0.1257, F1: 0.6126

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.45308 | val 0.48153
  Epoch 011 - train 0.44719 | val 0.48686
  Regression -> MSE: 0.000692, MAE: 0.019477, R²: -0.0105
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.49003 | val 1.04616
  Epoch 011 - train 0.50050 | val 1.04606
  Regression -> MSE: 0.000324, MAE: 0.014560, R²: -0.0458
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.39706 | val 0.43961
  Epoch 011 - train 0.37908 | val 0.44874
  Regression -> MSE: 0.000351, MAE: 0.014630, R²: -0.0051
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.45311 | val 0.47304
  Epoch 018 - train 0.44360 | val 0.53679
  Regression -> MSE: 0.000201, MAE: 0.010000, R²: 0.0127
  Directional -> Accuracy: 0.6078, MCC: 0.3034, F1: 0.4737

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.46347 | val 1.19383
  Epoch 011 - train 0.45083 | val 1.19606
  Regression -> MSE: 0.000556, MAE: 0.018135, R²: -0.0021
  Directional -> Accuracy: 0.5532, MCC: 0.1390, F1: 0.6441

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.45862 | val 0.68298
  Epoch 011 - train 0.46812 | val 0.68042
  Regression -> MSE: 0.000247, MAE: 0.011934, R²: -0.0058
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.46680 | val 0.73838
  Epoch 011 - train 0.44594 | val 0.74612
  Regression -> MSE: 0.000629, MAE: 0.019864, R²: -0.0521
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.49309 | val 0.61712
  Epoch 020 - train 0.44297 | val 0.61928
  Epoch 021 - train 0.44495 | val 0.62002
  Regression -> MSE: 0.000400, MAE: 0.016047, R²: -0.0434
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.46351 | val 0.80195
  Epoch 011 - train 0.47950 | val 0.82500
  Regression -> MSE: 0.000242, MAE: 0.011782, R²: -0.0039
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.43660 | val 0.92129
  Epoch 011 - train 0.43151 | val 0.97309
  Regression -> MSE: 0.000311, MAE: 0.013644, R²: -0.0003
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.49249 | val 0.68583
  Epoch 011 - train 0.47968 | val 0.69983
  Regression -> MSE: 0.000678, MAE: 0.019485, R²: -0.0011
  Directional -> Accuracy: 0.5345, MCC: 0.0913, F1: 0.3077

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.45691 | val 0.51740
  Epoch 011 - train 0.45484 | val 0.53120
  Regression -> MSE: 0.000142, MAE: 0.009369, R²: -0.0259
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.43677 | val 0.83838
  Epoch 011 - train 0.42666 | val 0.86410
  Regression -> MSE: 0.000225, MAE: 0.010702, R²: -0.0017
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.46141 | val 1.47416
  Epoch 011 - train 0.47213 | val 1.50745
  Regression -> MSE: 0.000369, MAE: 0.015942, R²: -0.0194
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.49180 | val 0.53052
  Epoch 016 - train 0.45387 | val 0.57301
  Regression -> MSE: 0.000106, MAE: 0.007877, R²: 0.0131
  Directional -> Accuracy: 0.5429, MCC: 0.0391, F1: 0.6667

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.43943 | val 1.29496
  Epoch 011 - train 0.43106 | val 1.40089
  Regression -> MSE: 0.000155, MAE: 0.009638, R²: 0.0066
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.46537 | val 0.49383
  Epoch 011 - train 0.47142 | val 0.49212
  Regression -> MSE: 0.000272, MAE: 0.012983, R²: -0.0002
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.37430 | val 0.74620
  Epoch 019 - train 0.37069 | val 0.74267
  Regression -> MSE: 0.000194, MAE: 0.010266, R²: -0.2979
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.45558 | val 1.00975
  Epoch 014 - train 0.45733 | val 1.01718
  Regression -> MSE: 0.000264, MAE: 0.011713, R²: -0.1659
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.46645 | val 0.76231
  Epoch 011 - train 0.45455 | val 0.78540
  Regression -> MSE: 0.000145, MAE: 0.008432, R²: -0.0101
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.46457 | val 0.60622
  Epoch 011 - train 0.45314 | val 0.62084
  Regression -> MSE: 0.000169, MAE: 0.010248, R²: -0.0232
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.48772 | val 0.69840
  Epoch 011 - train 0.48536 | val 0.70466
  Regression -> MSE: 0.000088, MAE: 0.007187, R²: -0.0299
  Directional -> Accuracy: 0.4310, MCC: -0.0263, F1: 0.0571

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.47572 | val 1.11729
  Epoch 014 - train 0.46521 | val 1.29051
  Regression -> MSE: 0.000210, MAE: 0.011091, R²: 0.0076
  Directional -> Accuracy: 0.5000, MCC: 0.0310, F1: 0.5823

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.41154 | val 0.36572
  Epoch 020 - train 0.41394 | val 0.34786
  Epoch 027 - train 0.42854 | val 0.34922
  Regression -> MSE: 0.000093, MAE: 0.007701, R²: -0.0154
  Directional -> Accuracy: 0.5893, MCC: 0.1970, F1: 0.5818

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.45749 | val 0.34577
  Epoch 011 - train 0.49764 | val 0.34629
  Regression -> MSE: 0.000103, MAE: 0.008716, R²: -0.0009
  Directional -> Accuracy: 0.5435, MCC: 0.0877, F1: 0.5116

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.48698 | val 0.51301
  Epoch 011 - train 0.49406 | val 0.55721
  Regression -> MSE: 0.000231, MAE: 0.012532, R²: 0.0002
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.47151 | val 0.61591
  Epoch 020 - train 0.43294 | val 0.62549
  Regression -> MSE: 0.000178, MAE: 0.008064, R²: -0.0719
  Directional -> Accuracy: 0.5263, MCC: -0.0115, F1: 0.6400

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.46470 | val 0.30107
  Epoch 011 - train 0.48679 | val 0.30293
  Regression -> MSE: 0.000237, MAE: 0.011874, R²: -0.0027
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.52132 | val 1.03138
  Epoch 011 - train 0.50921 | val 1.03231
  Regression -> MSE: 0.000230, MAE: 0.009853, R²: 0.0007
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.47844 | val 0.71622
  Epoch 019 - train 0.43184 | val 0.76342
  Regression -> MSE: 0.000141, MAE: 0.008395, R²: -0.0461
  Directional -> Accuracy: 0.3721, MCC: -0.2973, F1: 0.0690

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.46652 | val 0.71842
  Epoch 011 - train 0.49206 | val 0.72301
  Regression -> MSE: 0.000200, MAE: 0.010728, R²: -0.0640
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.42232 | val 0.64292
  Epoch 015 - train 0.39737 | val 0.63187
  Regression -> MSE: 0.000276, MAE: 0.010968, R²: -0.0559
  Directional -> Accuracy: 0.5205, MCC: 0.2216, F1: 0.2857

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.46599 | val 0.38470
  Epoch 020 - train 0.46076 | val 0.35356
  Epoch 029 - train 0.45741 | val 0.37864
  Regression -> MSE: 0.000166, MAE: 0.010492, R²: 0.0038
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.42439 | val 0.68030
  Epoch 011 - train 0.42035 | val 0.73057
  Regression -> MSE: 0.000181, MAE: 0.010365, R²: -0.0056
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.43813 | val 0.46547
  Epoch 015 - train 0.44242 | val 0.47712
  Regression -> MSE: 0.000355, MAE: 0.012678, R²: -0.0349
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.48038 | val 0.23902
  Epoch 011 - train 0.50996 | val 0.23947
  Regression -> MSE: 0.000114, MAE: 0.008322, R²: -0.0858
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.45883 | val 0.86480
  Epoch 011 - train 0.44221 | val 0.88300
  Regression -> MSE: 0.000219, MAE: 0.011284, R²: -0.0016
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.46976 | val 1.19355
  Epoch 016 - train 0.44726 | val 1.49740
  Regression -> MSE: 0.000091, MAE: 0.007453, R²: -0.1664
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.42176 | val 0.27154
  Epoch 011 - train 0.43987 | val 0.27245
  Regression -> MSE: 0.000310, MAE: 0.013876, R²: -0.0064
  Directional -> Accuracy: 0.6327, MCC: 0.0000, F1: 0.0000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.42857 | val 0.21387
  Epoch 011 - train 0.49055 | val 0.21470
  Regression -> MSE: 0.000255, MAE: 0.011460, R²: -0.0473
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.45307 | val 0.73967
  Epoch 011 - train 0.44822 | val 0.75957
  Regression -> MSE: 0.000082, MAE: 0.007056, R²: -0.0135
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.50163 | val 0.64816
  Epoch 020 - train 0.47520 | val 0.77828
  Epoch 023 - train 0.46095 | val 0.82853
  Regression -> MSE: 0.000307, MAE: 0.014418, R²: -0.0020
  Directional -> Accuracy: 0.5106, MCC: 0.0045, F1: 0.6667

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.42443 | val 0.54515
  Epoch 011 - train 0.47297 | val 0.54388
  Regression -> MSE: 0.000098, MAE: 0.007346, R²: -0.0007
  Directional -> Accuracy: 0.4318, MCC: 0.0000, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.52671 | val 0.78768
  Epoch 011 - train 0.47126 | val 0.78808
  Regression -> MSE: 0.000174, MAE: 0.010021, R²: -0.0109
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.44168 | val 0.66311
  Epoch 011 - train 0.42706 | val 0.67683
  Regression -> MSE: 0.000225, MAE: 0.011801, R²: -0.0092
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.45827 | val 0.63164
  Epoch 011 - train 0.47768 | val 0.62790
  Regression -> MSE: 0.000095, MAE: 0.007791, R²: -0.0262
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.48573 | val 1.18535
  Epoch 011 - train 0.48853 | val 1.26818
  Regression -> MSE: 0.000164, MAE: 0.010263, R²: -0.0019
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.45775 | val 0.87245
  Epoch 011 - train 0.46523 | val 0.90365
  Regression -> MSE: 0.000117, MAE: 0.008938, R²: -0.0096
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...

[I 2026-02-22 23:39:46,866] Trial 127 finished with value: -0.011454664253802298 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 32, 'learning_rate': 2.940310568258317e-05, 'weight_decay': 1.2948880385500169e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 1.82189443026793, 'early_stopping_min_delta': 0.00858521337696399}. Best is trial 90 with value: -0.011414558399902668.

  Epoch 010 - train 0.48873 | val 1.14582
  Epoch 011 - train 0.48838 | val 1.17703
  Regression -> MSE: 0.000237, MAE: 0.012461, R²: -0.0001
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.48121 | val 0.81579
  Epoch 020 - train 0.44834 | val 0.79667
  Epoch 030 - train 0.45595 | val 0.78526
  Epoch 036 - train 0.43639 | val 0.78037
  Regression -> MSE: 0.000301, MAE: 0.013600, R²: -0.2172
  Directional -> Accuracy: 0.4805, MCC: -0.0696, F1: 0.3548

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.47889 | val 0.46366
  Epoch 011 - train 0.46160 | val 0.46569
  Regression -> MSE: 0.000713, MAE: 0.019833, R²: -0.0417
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.49013 | val 1.02194
  Epoch 020 - train 0.50321 | val 1.01592
  Epoch 024 - train 0.49566 | val 1.01477
  Regression -> MSE: 0.000312, MAE: 0.014545, R²: -0.0064
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.42955 | val 1.18328
  Epoch 011 - train 0.43412 | val 1.16282
  Regression -> MSE: 0.000411, MAE: 0.015749, R²: -0.1762
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.45782 | val 0.44157
  Epoch 020 - train 0.46951 | val 0.42506
  Epoch 022 - train 0.45623 | val 0.42708
  Regression -> MSE: 0.000210, MAE: 0.010085, R²: -0.0297
  Directional -> Accuracy: 0.4902, MCC: -0.0518, F1: 0.5938

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.48149 | val 1.23200
  Epoch 011 - train 0.46344 | val 1.23136
  Regression -> MSE: 0.000590, MAE: 0.018780, R²: -0.0635
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.49322 | val 0.68805
  Epoch 011 - train 0.48587 | val 0.68676
  Regression -> MSE: 0.000246, MAE: 0.012040, R²: -0.0013
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.48223 | val 0.74291
  Epoch 011 - train 0.48270 | val 0.74750
  Regression -> MSE: 0.000633, MAE: 0.019960, R²: -0.0601
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.48072 | val 0.62289
  Epoch 020 - train 0.45746 | val 0.60449
  Epoch 029 - train 0.44445 | val 0.60610
  Regression -> MSE: 0.000414, MAE: 0.016160, R²: -0.0782
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.47105 | val 0.82527
  Epoch 014 - train 0.47106 | val 0.84841
  Regression -> MSE: 0.000241, MAE: 0.011928, R²: 0.0028
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.48253 | val 0.76435
  Epoch 020 - train 0.45294 | val 0.77918
  Regression -> MSE: 0.000331, MAE: 0.013604, R²: -0.0659
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.49704 | val 0.65088
  Epoch 011 - train 0.48829 | val 0.66157
  Regression -> MSE: 0.000679, MAE: 0.019590, R²: -0.0029
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.46737 | val 0.51452
  Epoch 017 - train 0.48538 | val 0.54806
  Regression -> MSE: 0.000139, MAE: 0.009245, R²: -0.0078
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.42128 | val 0.70723
  Epoch 020 - train 0.41515 | val 0.69822
  Epoch 027 - train 0.40053 | val 0.69705
  Regression -> MSE: 0.000224, MAE: 0.010516, R²: 0.0025
  Directional -> Accuracy: 0.5738, MCC: 0.1564, F1: 0.5185

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.46813 | val 1.65611
  Epoch 011 - train 0.49127 | val 1.79944
  Regression -> MSE: 0.000370, MAE: 0.015915, R²: -0.0210
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.50503 | val 0.54015
  Epoch 011 - train 0.49847 | val 0.53891
  Regression -> MSE: 0.000110, MAE: 0.008195, R²: -0.0209
  Directional -> Accuracy: 0.4571, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.45221 | val 1.37774
  Epoch 011 - train 0.45446 | val 1.46580
  Regression -> MSE: 0.000158, MAE: 0.009973, R²: -0.0159
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.47670 | val 0.59958
  Epoch 011 - train 0.50813 | val 0.60809
  Regression -> MSE: 0.000286, MAE: 0.013658, R²: -0.0509
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.40413 | val 0.76263
  Epoch 011 - train 0.41213 | val 0.76128
  Regression -> MSE: 0.000168, MAE: 0.009167, R²: -0.1233
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.47157 | val 1.12044
  Epoch 014 - train 0.46540 | val 1.13362
  Regression -> MSE: 0.000243, MAE: 0.011116, R²: -0.0743
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.46152 | val 0.73407
  Epoch 011 - train 0.50525 | val 0.75478
  Regression -> MSE: 0.000151, MAE: 0.008745, R²: -0.0558
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.45613 | val 0.60502
  Epoch 018 - train 0.47599 | val 0.61017
  Regression -> MSE: 0.000171, MAE: 0.010831, R²: -0.0345
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6452

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.55630 | val 0.71365
  Epoch 011 - train 0.52396 | val 0.71761
  Regression -> MSE: 0.000091, MAE: 0.007356, R²: -0.0699
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.50700 | val 1.44360
  Epoch 014 - train 0.46837 | val 1.72622
  Regression -> MSE: 0.000210, MAE: 0.011052, R²: 0.0085
  Directional -> Accuracy: 0.5909, MCC: 0.1996, F1: 0.6197

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.45705 | val 0.34827
  Epoch 020 - train 0.42677 | val 0.33356
  Epoch 023 - train 0.40529 | val 0.33311
  Regression -> MSE: 0.000092, MAE: 0.007816, R²: 0.0025
  Directional -> Accuracy: 0.5893, MCC: 0.1878, F1: 0.5965

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.51075 | val 0.34835
  Epoch 011 - train 0.51361 | val 0.34802
  Regression -> MSE: 0.000104, MAE: 0.008769, R²: -0.0047
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.53441 | val 0.50385
  Epoch 011 - train 0.54454 | val 0.53934
  Regression -> MSE: 0.000234, MAE: 0.012655, R²: -0.0118
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.51215 | val 0.59541
  Epoch 017 - train 0.47873 | val 0.61465
  Regression -> MSE: 0.000209, MAE: 0.008899, R²: -0.2557
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.53383 | val 0.30123
  Epoch 011 - train 0.48570 | val 0.29992
  Regression -> MSE: 0.000237, MAE: 0.011868, R²: -0.0013
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.53656 | val 1.04822
  Epoch 011 - train 0.48005 | val 1.04962
  Regression -> MSE: 0.000230, MAE: 0.009873, R²: 0.0001
  Directional -> Accuracy: 0.4419, MCC: -0.2676, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.53473 | val 0.68981
  Epoch 011 - train 0.52206 | val 0.69490
  Regression -> MSE: 0.000135, MAE: 0.008224, R²: -0.0008
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.47867 | val 0.73460
  Epoch 011 - train 0.48432 | val 0.73898
  Regression -> MSE: 0.000190, MAE: 0.010371, R²: -0.0073
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.42662 | val 0.68844
  Epoch 011 - train 0.43548 | val 0.69168
  Regression -> MSE: 0.000268, MAE: 0.010589, R²: -0.0251
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.47428 | val 0.36511
  Epoch 011 - train 0.45230 | val 0.36493
  Regression -> MSE: 0.000167, MAE: 0.010377, R²: -0.0020
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.45413 | val 0.59659
  Epoch 011 - train 0.42503 | val 0.59636
  Regression -> MSE: 0.000189, MAE: 0.010650, R²: -0.0487
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.46677 | val 0.45144
  Epoch 011 - train 0.45150 | val 0.45188
  Regression -> MSE: 0.000343, MAE: 0.011710, R²: -0.0005
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.50731 | val 0.25334
  Epoch 011 - train 0.46855 | val 0.25250
  Regression -> MSE: 0.000124, MAE: 0.008446, R²: -0.1827
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.46203 | val 0.94427
  Epoch 011 - train 0.47899 | val 0.96857
  Regression -> MSE: 0.000219, MAE: 0.011284, R²: -0.0006
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.52287 | val 1.20698
  Epoch 011 - train 0.53513 | val 1.21139
  Regression -> MSE: 0.000097, MAE: 0.007679, R²: -0.2465
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.47474 | val 0.32158
  Epoch 011 - train 0.49250 | val 0.32441
  Regression -> MSE: 0.000322, MAE: 0.014614, R²: -0.0457
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.51014 | val 0.19522
  Epoch 011 - train 0.51394 | val 0.19616
  Regression -> MSE: 0.000247, MAE: 0.011530, R²: -0.0122
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.0000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.45829 | val 0.69406
  Epoch 011 - train 0.44516 | val 0.69657
  Regression -> MSE: 0.000082, MAE: 0.007059, R²: -0.0126
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.52198 | val 0.63250
  Epoch 011 - train 0.53222 | val 0.63207
  Regression -> MSE: 0.000308, MAE: 0.014510, R²: -0.0045
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.49763 | val 0.55795
  Epoch 011 - train 0.52979 | val 0.55812
  Regression -> MSE: 0.000098, MAE: 0.007327, R²: 0.0009
  Directional -> Accuracy: 0.4318, MCC: 0.0000, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.50648 | val 0.78062
  Epoch 011 - train 0.49994 | val 0.78229
  Regression -> MSE: 0.000172, MAE: 0.009631, R²: -0.0001
  Directional -> Accuracy: 0.3878, MCC: -0.1167, F1: 0.4828

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.45639 | val 0.62791
  Epoch 011 - train 0.45607 | val 0.63165
  Regression -> MSE: 0.000224, MAE: 0.011749, R²: -0.0042
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.45175 | val 0.75153
  Epoch 011 - train 0.48300 | val 0.77388
  Regression -> MSE: 0.000095, MAE: 0.007834, R²: -0.0321
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.50826 | val 1.06414
  Epoch 011 - train 0.51108 | val 1.06984
  Regression -> MSE: 0.000169, MAE: 0.010331, R²: -0.0295
  Directional -> Accuracy: 0.4815, MCC: 0.0000, F1: 0.0000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.45401 | val 0.72168
  Epoch 011 - train 0.45341 | val 0.72414
  Regression -> MSE: 0.000120, MAE: 0.008973, R²: -0.0368
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...

[I 2026-02-22 23:40:41,727] Trial 128 finished with value: -0.011534927292018516 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 32, 'learning_rate': 2.0606793112235113e-05, 'weight_decay': 2.0514102836960895e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 1.8468805599115283, 'early_stopping_min_delta': 0.008554525428017592}. Best is trial 90 with value: -0.011414558399902668.

  Epoch 010 - train 0.52266 | val 0.94285
  Epoch 011 - train 0.52095 | val 0.94866
  Regression -> MSE: 0.000240, MAE: 0.012334, R²: -0.0105
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.45670 | val 0.98586
  Epoch 016 - train 0.44626 | val 0.96635
  Regression -> MSE: 0.000249, MAE: 0.012623, R²: -0.0071
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.46122 | val 0.46757
  Epoch 016 - train 0.46542 | val 0.49416
  Regression -> MSE: 0.000706, MAE: 0.019721, R²: -0.0311
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.48704 | val 1.04561
  Epoch 020 - train 0.48926 | val 1.06017
  Epoch 025 - train 0.49116 | val 1.05838
  Regression -> MSE: 0.000320, MAE: 0.014406, R²: -0.0326
  Directional -> Accuracy: 0.5319, MCC: 0.1529, F1: 0.3125

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.39538 | val 1.49034
  Epoch 016 - train 0.36541 | val 1.79636
  Regression -> MSE: 0.000351, MAE: 0.014615, R²: -0.0045
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.46605 | val 0.43028
  Epoch 020 - train 0.43694 | val 0.45304
  Epoch 025 - train 0.41031 | val 0.46468
  Regression -> MSE: 0.000194, MAE: 0.009313, R²: 0.0462
  Directional -> Accuracy: 0.6471, MCC: 0.3495, F1: 0.7429

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.48153 | val 1.24006
  Epoch 020 - train 0.45139 | val 1.28140
  Epoch 029 - train 0.46067 | val 1.36554
  Regression -> MSE: 0.000541, MAE: 0.018008, R²: 0.0261
  Directional -> Accuracy: 0.5106, MCC: 0.0153, F1: 0.4103

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.47332 | val 0.68924
  Epoch 020 - train 0.47522 | val 0.71224
  Epoch 021 - train 0.45926 | val 0.71532
  Regression -> MSE: 0.000243, MAE: 0.011987, R²: 0.0106
  Directional -> Accuracy: 0.5217, MCC: 0.0471, F1: 0.4762

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.45629 | val 0.77798
  Epoch 020 - train 0.44272 | val 0.60476
  Epoch 030 - train 0.44132 | val 0.59644
  Epoch 039 - train 0.42435 | val 0.61409
  Regression -> MSE: 0.000668, MAE: 0.020168, R²: -0.1181
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.46728 | val 0.62032
  Epoch 016 - train 0.45765 | val 0.64900
  Regression -> MSE: 0.000391, MAE: 0.015984, R²: -0.0192
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.47138 | val 1.09274
  Epoch 019 - train 0.43199 | val 1.15202
  Regression -> MSE: 0.000241, MAE: 0.011814, R²: 0.0033
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.43991 | val 0.95558
  Epoch 016 - train 0.43942 | val 1.25118
  Regression -> MSE: 0.000317, MAE: 0.013588, R²: -0.0206
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.48682 | val 0.66731
  Epoch 016 - train 0.46172 | val 0.69507
  Regression -> MSE: 0.000682, MAE: 0.019514, R²: -0.0069
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.46439 | val 0.53897
  Epoch 016 - train 0.47563 | val 0.72070
  Regression -> MSE: 0.000144, MAE: 0.009454, R²: -0.0388
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.44322 | val 0.78605
  Epoch 016 - train 0.44128 | val 0.78540
  Regression -> MSE: 0.000224, MAE: 0.010666, R²: 0.0033
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.47448 | val 1.48623
  Epoch 020 - train 0.42184 | val 1.95302
  Epoch 021 - train 0.45127 | val 2.01285
  Regression -> MSE: 0.000366, MAE: 0.015934, R²: -0.0093
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.47133 | val 0.55859
  Epoch 020 - train 0.45814 | val 0.58522
  Regression -> MSE: 0.000107, MAE: 0.007900, R²: 0.0115
  Directional -> Accuracy: 0.4857, MCC: -0.0898, F1: 0.6087

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.44902 | val 1.37346
  Epoch 016 - train 0.42435 | val 1.62387
  Regression -> MSE: 0.000156, MAE: 0.009638, R²: -0.0032
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.48502 | val 0.54150
  Epoch 016 - train 0.45631 | val 0.56788
  Regression -> MSE: 0.000272, MAE: 0.012941, R²: 0.0004
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.38232 | val 0.76367
  Epoch 020 - train 0.38622 | val 0.75954
  Epoch 023 - train 0.36837 | val 0.75661
  Regression -> MSE: 0.000239, MAE: 0.011840, R²: -0.5977
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.42606 | val 1.06435
  Epoch 020 - train 0.44079 | val 1.12230
  Epoch 021 - train 0.44499 | val 1.12026
  Regression -> MSE: 0.000262, MAE: 0.011639, R²: -0.1600
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.48367 | val 0.74102
  Epoch 020 - train 0.43007 | val 0.70421
  Epoch 030 - train 0.43692 | val 0.71273
  Epoch 036 - train 0.43377 | val 0.71269
  Regression -> MSE: 0.000175, MAE: 0.010119, R²: -0.2205
  Directional -> Accuracy: 0.4583, MCC: 0.2335, F1: 0.2353

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.45664 | val 0.61159
  Epoch 016 - train 0.45290 | val 0.64506
  Regression -> MSE: 0.000173, MAE: 0.010292, R²: -0.0443
  Directional -> Accuracy: 0.3939, MCC: -0.2186, F1: 0.3103

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.49452 | val 0.73173
  Epoch 016 - train 0.48149 | val 0.75416
  Regression -> MSE: 0.000085, MAE: 0.007057, R²: -0.0031
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.48548 | val 0.98554
  Epoch 016 - train 0.47357 | val 1.06835
  Regression -> MSE: 0.000214, MAE: 0.011046, R²: -0.0098
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.43280 | val 0.31508
  Epoch 020 - train 0.41570 | val 0.29402
  Epoch 030 - train 0.38309 | val 0.29150
  Epoch 031 - train 0.37299 | val 0.29398
  Regression -> MSE: 0.000112, MAE: 0.008778, R²: -0.2158
  Directional -> Accuracy: 0.5357, MCC: 0.1728, F1: 0.3810

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.47549 | val 0.35767
  Epoch 016 - train 0.49254 | val 0.36812
  Regression -> MSE: 0.000104, MAE: 0.008813, R²: -0.0120
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.49538 | val 0.49174
  Epoch 016 - train 0.48884 | val 0.67358
  Regression -> MSE: 0.000232, MAE: 0.012554, R²: -0.0009
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.46588 | val 0.61567
  Epoch 020 - train 0.45923 | val 0.63194
  Epoch 023 - train 0.44911 | val 0.63595
  Regression -> MSE: 0.000195, MAE: 0.008363, R²: -0.1713
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.47096 | val 0.33496
  Epoch 020 - train 0.44349 | val 0.29712
  Epoch 030 - train 0.47504 | val 0.29804
  Epoch 033 - train 0.45741 | val 0.30135
  Regression -> MSE: 0.000225, MAE: 0.011621, R²: 0.0479
  Directional -> Accuracy: 0.5122, MCC: -0.1469, F1: 0.6774

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.48096 | val 1.12446
  Epoch 016 - train 0.48905 | val 1.14498
  Regression -> MSE: 0.000234, MAE: 0.010037, R²: -0.0135
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.48009 | val 0.75432
  Epoch 016 - train 0.46292 | val 0.82874
  Regression -> MSE: 0.000140, MAE: 0.008422, R²: -0.0374
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.46181 | val 0.80133
  Epoch 016 - train 0.46149 | val 0.85410
  Regression -> MSE: 0.000191, MAE: 0.010375, R²: -0.0168
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.39747 | val 0.62110
  Epoch 020 - train 0.39580 | val 0.62113
  Epoch 023 - train 0.39172 | val 0.61969
  Regression -> MSE: 0.000341, MAE: 0.012483, R²: -0.3006
  Directional -> Accuracy: 0.4932, MCC: 0.2127, F1: 0.1778

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.47103 | val 0.36431
  Epoch 016 - train 0.42113 | val 0.37254
  Regression -> MSE: 0.000166, MAE: 0.010363, R²: 0.0021
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.42033 | val 0.56815
  Epoch 016 - train 0.39754 | val 0.61232
  Regression -> MSE: 0.000180, MAE: 0.010326, R²: -0.0012
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.46289 | val 0.45137
  Epoch 020 - train 0.45179 | val 0.45030
  Epoch 026 - train 0.45248 | val 0.45428
  Regression -> MSE: 0.000433, MAE: 0.015930, R²: -0.2643
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.47720 | val 0.24620
  Epoch 020 - train 0.46174 | val 0.24581
  Epoch 030 - train 0.46641 | val 0.25806
  Regression -> MSE: 0.000159, MAE: 0.009181, R²: -0.5152
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.45630 | val 0.85043
  Epoch 020 - train 0.45783 | val 0.89127
  Epoch 025 - train 0.45506 | val 0.90383
  Regression -> MSE: 0.000247, MAE: 0.012459, R²: -0.1300
  Directional -> Accuracy: 0.4386, MCC: -0.1124, F1: 0.5000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.46864 | val 1.29982
  Epoch 016 - train 0.45932 | val 1.56942
  Regression -> MSE: 0.000083, MAE: 0.007102, R²: -0.0684
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.44681 | val 0.27758
  Epoch 016 - train 0.44687 | val 0.28825
  Regression -> MSE: 0.000310, MAE: 0.013955, R²: -0.0093
  Directional -> Accuracy: 0.6327, MCC: 0.0000, F1: 0.0000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.51139 | val 0.20057
  Epoch 016 - train 0.50030 | val 0.20540
  Regression -> MSE: 0.000248, MAE: 0.011513, R²: -0.0191
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.42143 | val 0.73993
  Epoch 016 - train 0.42192 | val 0.73921
  Regression -> MSE: 0.000085, MAE: 0.007065, R²: -0.0560
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.48304 | val 0.63220
  Epoch 016 - train 0.47765 | val 0.72586
  Regression -> MSE: 0.000309, MAE: 0.014526, R²: -0.0086
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.46553 | val 0.58302
  Epoch 016 - train 0.43680 | val 0.59497
  Regression -> MSE: 0.000098, MAE: 0.007249, R²: 0.0018
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.50271 | val 0.81076
  Epoch 016 - train 0.50132 | val 0.81108
  Regression -> MSE: 0.000173, MAE: 0.009969, R²: -0.0089
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.42651 | val 0.67072
  Epoch 016 - train 0.42497 | val 0.71751
  Regression -> MSE: 0.000225, MAE: 0.011780, R²: -0.0084
  Directional -> Accuracy: 0.5179, MCC: 0.0878, F1: 0.3721

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.43933 | val 0.69101
  Epoch 016 - train 0.45206 | val 0.81169
  Regression -> MSE: 0.000092, MAE: 0.007636, R²: 0.0016
  Directional -> Accuracy: 0.5965, MCC: 0.1894, F1: 0.5660

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.48802 | val 1.10330
  Epoch 016 - train 0.48394 | val 1.30782
  Regression -> MSE: 0.000165, MAE: 0.010280, R²: -0.0053
  Directional -> Accuracy: 0.5000, MCC: -0.1324, F1: 0.6667

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.43288 | val 0.80142
  Epoch 016 - train 0.44133 | val 0.83251
  Regression -> MSE: 0.000116, MAE: 0.008906, R²: -0.0016
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.50915 | val 1.05667

[I 2026-02-22 23:45:29,169] Trial 129 finished with value: -0.011645763339382385 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 32, 'learning_rate': 2.9813620572583213e-05, 'weight_decay': 1.6320976208242297e-05, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 1.9613018454685016, 'early_stopping_min_delta': 0.006487103571795646}. Best is trial 90 with value: -0.011414558399902668.

  Epoch 016 - train 0.47068 | val 1.22636
  Regression -> MSE: 0.000241, MAE: 0.012337, R²: -0.0169
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.30186 | val 0.43471
  Epoch 016 - train 0.31519 | val 0.43464
  Regression -> MSE: 0.000248, MAE: 0.012542, R²: -0.0009
  Directional -> Accuracy: 0.4805, MCC: 0.0962, F1: 0.6296

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.28228 | val 0.28881
  Epoch 016 - train 0.30593 | val 0.30463
  Regression -> MSE: 0.000685, MAE: 0.019354, R²: -0.0007
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.32605 | val 0.60249
  Epoch 016 - train 0.31945 | val 0.61592
  Regression -> MSE: 0.000322, MAE: 0.014607, R²: -0.0391
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.27982 | val 0.30199
  Epoch 016 - train 0.27113 | val 0.29732
  Regression -> MSE: 0.000349, MAE: 0.014546, R²: 0.0020
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.31662 | val 0.37474
  Epoch 016 - train 0.30707 | val 0.38348
  Regression -> MSE: 0.000209, MAE: 0.010470, R²: -0.0253
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.33484 | val 0.61513
  Epoch 016 - train 0.32060 | val 0.61692
  Regression -> MSE: 0.000558, MAE: 0.018251, R²: -0.0045
  Directional -> Accuracy: 0.4894, MCC: 0.0000, F1: 0.6571

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.30704 | val 0.39190
  Epoch 016 - train 0.29678 | val 0.39018
  Regression -> MSE: 0.000247, MAE: 0.011928, R²: -0.0070
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.32466 | val 0.63712
  Epoch 016 - train 0.33151 | val 0.81847
  Regression -> MSE: 0.000693, MAE: 0.020867, R²: -0.1591
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.28775 | val 0.36500
  Epoch 020 - train 0.29238 | val 0.41800
  Epoch 021 - train 0.28856 | val 0.41676
  Regression -> MSE: 0.000488, MAE: 0.017257, R²: -0.2721
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.31731 | val 0.43093
  Epoch 016 - train 0.32839 | val 0.43299
  Regression -> MSE: 0.000247, MAE: 0.011649, R²: -0.0215
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.27774 | val 0.53835
  Epoch 016 - train 0.27845 | val 0.54745
  Regression -> MSE: 0.000309, MAE: 0.013697, R²: 0.0056
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.6301

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.30543 | val 0.40174
  Epoch 016 - train 0.31640 | val 0.40301
  Regression -> MSE: 0.000680, MAE: 0.019617, R²: -0.0040
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.32672 | val 0.30392
  Epoch 016 - train 0.33132 | val 0.30761
  Regression -> MSE: 0.000145, MAE: 0.009535, R²: -0.0504
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.27456 | val 0.40871
  Epoch 020 - train 0.26331 | val 0.40956
  Regression -> MSE: 0.000225, MAE: 0.010661, R²: -0.0021
  Directional -> Accuracy: 0.5902, MCC: 0.2209, F1: 0.6914

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.31059 | val 0.66771
  Epoch 016 - train 0.30840 | val 0.66715
  Regression -> MSE: 0.000370, MAE: 0.015930, R²: -0.0224
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.32665 | val 0.34506
  Epoch 016 - train 0.32732 | val 0.34419
  Regression -> MSE: 0.000112, MAE: 0.007978, R²: -0.0393
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.28942 | val 0.53082
  Epoch 016 - train 0.30066 | val 0.53086
  Regression -> MSE: 0.000159, MAE: 0.009966, R²: -0.0216
  Directional -> Accuracy: 0.5763, MCC: 0.0129, F1: 0.6988

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.32082 | val 0.33846
  Epoch 016 - train 0.30558 | val 0.33853
  Regression -> MSE: 0.000273, MAE: 0.012819, R²: -0.0049
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.31287 | val 0.57755
  Epoch 016 - train 0.31256 | val 0.57040
  Regression -> MSE: 0.000152, MAE: 0.008788, R²: -0.0136
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.32896 | val 0.47995
  Epoch 016 - train 0.33140 | val 0.47666
  Regression -> MSE: 0.000260, MAE: 0.011548, R²: -0.1499
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.32767 | val 0.58629
  Epoch 016 - train 0.31799 | val 0.61433
  Regression -> MSE: 0.000149, MAE: 0.008606, R²: -0.0373
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.31216 | val 0.40279
  Epoch 016 - train 0.31666 | val 0.39871
  Regression -> MSE: 0.000182, MAE: 0.010381, R²: -0.0994
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.33971 | val 0.44337
  Epoch 016 - train 0.31508 | val 0.44474
  Regression -> MSE: 0.000087, MAE: 0.007084, R²: -0.0152
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.30306 | val 0.37473
  Epoch 016 - train 0.31826 | val 0.37717
  Regression -> MSE: 0.000211, MAE: 0.011082, R²: 0.0044
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.30095 | val 0.28511
  Epoch 016 - train 0.28723 | val 0.28494
  Regression -> MSE: 0.000093, MAE: 0.008153, R²: -0.0124
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.33428 | val 0.30298
  Epoch 016 - train 0.35254 | val 0.37093
  Regression -> MSE: 0.000125, MAE: 0.009503, R²: -0.2110
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.34001 | val 0.39560
  Epoch 016 - train 0.32971 | val 0.43437
  Regression -> MSE: 0.000243, MAE: 0.012912, R²: -0.0493
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.30065 | val 0.37335
  Epoch 016 - train 0.30204 | val 0.37351
  Regression -> MSE: 0.000189, MAE: 0.008101, R²: -0.1349
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.31008 | val 0.24723
  Epoch 016 - train 0.28744 | val 0.25275
  Regression -> MSE: 0.000236, MAE: 0.011858, R²: 0.0008
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.30269 | val 0.51445
  Epoch 020 - train 0.30188 | val 0.51417
  Epoch 022 - train 0.29775 | val 0.51426
  Regression -> MSE: 0.000238, MAE: 0.010141, R²: -0.0333
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.32853 | val 0.36632
  Epoch 016 - train 0.32056 | val 0.39734
  Regression -> MSE: 0.000136, MAE: 0.008199, R²: -0.0049
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.32585 | val 0.42519
  Epoch 016 - train 0.32245 | val 0.42819
  Regression -> MSE: 0.000190, MAE: 0.010388, R²: -0.0084
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.28260 | val 0.40161
  Epoch 016 - train 0.27636 | val 0.40071
  Regression -> MSE: 0.000277, MAE: 0.010921, R²: -0.0566
  Directional -> Accuracy: 0.4384, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.31755 | val 0.25165
  Epoch 016 - train 0.30804 | val 0.25842
  Regression -> MSE: 0.000175, MAE: 0.010466, R²: -0.0472
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.27904 | val 0.30814
  Epoch 020 - train 0.27726 | val 0.30935
  Epoch 022 - train 0.27783 | val 0.30873
  Regression -> MSE: 0.000179, MAE: 0.010261, R²: 0.0054
  Directional -> Accuracy: 0.4091, MCC: -0.1767, F1: 0.4800

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.28737 | val 0.28905
  Epoch 016 - train 0.28640 | val 0.28901
  Regression -> MSE: 0.000347, MAE: 0.012208, R²: -0.0113
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.29828 | val 0.17195
  Epoch 016 - train 0.34937 | val 0.17148
  Regression -> MSE: 0.000115, MAE: 0.008365, R²: -0.0931
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.32092 | val 0.43843
  Epoch 016 - train 0.33656 | val 0.43745
  Regression -> MSE: 0.000219, MAE: 0.011297, R²: -0.0031
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.30394 | val 0.59583
  Epoch 016 - train 0.29345 | val 0.60117
  Regression -> MSE: 0.000082, MAE: 0.007064, R²: -0.0568
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.31114 | val 0.26271
  Epoch 016 - train 0.32657 | val 0.26898
  Regression -> MSE: 0.000335, MAE: 0.015148, R²: -0.0882
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.33503 | val 0.16245
  Epoch 016 - train 0.34958 | val 0.16931
  Regression -> MSE: 0.000246, MAE: 0.011578, R²: -0.0103
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.0000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.29657 | val 0.37033
  Epoch 016 - train 0.29877 | val 0.36899
  Regression -> MSE: 0.000081, MAE: 0.007073, R²: -0.0021
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.31489 | val 0.37628
  Epoch 020 - train 0.29868 | val 0.37212
  Epoch 027 - train 0.29209 | val 0.37235
  Regression -> MSE: 0.000313, MAE: 0.014546, R²: -0.0188
  Directional -> Accuracy: 0.5745, MCC: 0.1828, F1: 0.4444

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.31221 | val 0.33906
  Epoch 020 - train 0.31644 | val 0.33642
  Epoch 025 - train 0.30405 | val 0.33728
  Regression -> MSE: 0.000097, MAE: 0.007300, R²: 0.0124
  Directional -> Accuracy: 0.4545, MCC: -0.0506, F1: 0.4000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.32594 | val 0.37773
  Epoch 016 - train 0.30676 | val 0.38943
  Regression -> MSE: 0.000172, MAE: 0.009866, R²: -0.0024
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.28804 | val 0.52616
  Epoch 016 - train 0.29783 | val 0.52339
  Regression -> MSE: 0.000223, MAE: 0.011815, R²: -0.0021
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.30128 | val 0.47576
  Epoch 016 - train 0.30448 | val 0.48683
  Regression -> MSE: 0.000093, MAE: 0.007721, R²: -0.0089
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.31305 | val 0.51738
  Epoch 016 - train 0.31382 | val 0.51673
  Regression -> MSE: 0.000164, MAE: 0.010242, R²: -0.0025
  Directional -> Accuracy: 0.6111, MCC: 0.2193, F1: 0.6441

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.32813 | val 0.41672
  Epoch 016 - train 0.31756 | val 0.42062
  Regression -> MSE: 0.000119, MAE: 0.008963, R²: -0.0243
  Directional -> Accuracy: 0.5179, MCC: 0.0413, F1: 0.4906

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.30229 | val 0.48877

[I 2026-02-22 23:46:28,341] Trial 130 finished with value: -0.011511380161204019 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 32, 'learning_rate': 2.942504983354281e-06, 'weight_decay': 1.0471616767628112e-05, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 0.5759181922501108, 'early_stopping_min_delta': 0.007679522824147758}. Best is trial 90 with value: -0.011414558399902668.

  Epoch 016 - train 0.32403 | val 0.49139
  Regression -> MSE: 0.000243, MAE: 0.012317, R²: -0.0262
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.41995 | val 0.66943
  Epoch 020 - train 0.43085 | val 0.66805
  Epoch 021 - train 0.39731 | val 0.66781
  Regression -> MSE: 0.000255, MAE: 0.012917, R²: -0.0309
  Directional -> Accuracy: 0.4675, MCC: 0.0490, F1: 0.6239

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.42991 | val 0.46217
  Epoch 011 - train 0.43311 | val 0.47050
  Regression -> MSE: 0.000696, MAE: 0.019530, R²: -0.0166
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.43255 | val 0.83108
  Epoch 020 - train 0.43024 | val 0.80302
  Epoch 027 - train 0.42440 | val 0.80289
  Regression -> MSE: 0.000324, MAE: 0.014458, R²: -0.0436
  Directional -> Accuracy: 0.4681, MCC: -0.0135, F1: 0.0741

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.36347 | val 0.42534
  Epoch 011 - train 0.34979 | val 0.44225
  Regression -> MSE: 0.000354, MAE: 0.014669, R²: -0.0144
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.43524 | val 0.53612
  Epoch 011 - train 0.42992 | val 0.55256
  Regression -> MSE: 0.000208, MAE: 0.010523, R²: -0.0223
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.39636 | val 0.99319
  Epoch 011 - train 0.39212 | val 0.99222
  Regression -> MSE: 0.000556, MAE: 0.018151, R²: -0.0015
  Directional -> Accuracy: 0.4894, MCC: 0.0000, F1: 0.6571

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.47424 | val 0.66274
  Epoch 011 - train 0.47118 | val 0.66584
  Regression -> MSE: 0.000253, MAE: 0.011984, R²: -0.0313
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.42451 | val 0.56312
  Epoch 011 - train 0.46663 | val 0.56335
  Regression -> MSE: 0.000608, MAE: 0.019416, R²: -0.0171
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.42044 | val 0.57067
  Epoch 011 - train 0.45146 | val 0.56791
  Regression -> MSE: 0.000384, MAE: 0.016116, R²: -0.0014
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.42939 | val 0.64036
  Epoch 011 - train 0.42157 | val 0.65109
  Regression -> MSE: 0.000242, MAE: 0.011735, R²: -0.0033
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.41936 | val 0.66313
  Epoch 011 - train 0.38837 | val 0.66634
  Regression -> MSE: 0.000321, MAE: 0.013583, R²: -0.0324
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.44065 | val 0.56972
  Epoch 011 - train 0.43090 | val 0.57172
  Regression -> MSE: 0.000675, MAE: 0.019444, R²: 0.0031
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.41873 | val 0.44862
  Epoch 011 - train 0.42931 | val 0.46150
  Regression -> MSE: 0.000144, MAE: 0.009475, R²: -0.0427
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.38921 | val 0.67243
  Epoch 011 - train 0.37900 | val 0.69030
  Regression -> MSE: 0.000226, MAE: 0.010719, R²: -0.0050
  Directional -> Accuracy: 0.4918, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.42828 | val 1.14917
  Epoch 011 - train 0.42484 | val 1.15301
  Regression -> MSE: 0.000362, MAE: 0.016162, R²: -0.0003
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.44578 | val 0.45733
  Epoch 020 - train 0.44268 | val 0.45651
  Epoch 021 - train 0.44768 | val 0.45785
  Regression -> MSE: 0.000111, MAE: 0.008179, R²: -0.0314
  Directional -> Accuracy: 0.5429, MCC: 0.1119, F1: 0.5000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.41023 | val 1.05746
  Epoch 011 - train 0.42402 | val 1.11796
  Regression -> MSE: 0.000162, MAE: 0.010196, R²: -0.0402
  Directional -> Accuracy: 0.3729, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.43994 | val 0.48177
  Epoch 011 - train 0.44649 | val 0.49271
  Regression -> MSE: 0.000278, MAE: 0.012889, R²: -0.0231
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.35771 | val 0.63470
  Epoch 020 - train 0.35733 | val 0.62529
  Epoch 025 - train 0.36524 | val 0.62294
  Regression -> MSE: 0.000224, MAE: 0.011446, R²: -0.5008
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.46005 | val 0.75654
  Epoch 011 - train 0.44456 | val 0.75823
  Regression -> MSE: 0.000239, MAE: 0.011035, R²: -0.0578
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.41304 | val 0.61420
  Epoch 011 - train 0.45297 | val 0.61611
  Regression -> MSE: 0.000146, MAE: 0.008512, R²: -0.0185
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.39521 | val 0.52676
  Epoch 011 - train 0.38592 | val 0.53062
  Regression -> MSE: 0.000170, MAE: 0.010255, R²: -0.0309
  Directional -> Accuracy: 0.5152, MCC: 0.0492, F1: 0.6522

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.44749 | val 0.56779
  Epoch 011 - train 0.44468 | val 0.56656
  Regression -> MSE: 0.000088, MAE: 0.007209, R²: -0.0372
  Directional -> Accuracy: 0.4310, MCC: -0.1255, F1: 0.4407

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.44900 | val 0.56500
  Epoch 018 - train 0.44293 | val 0.58599
  Regression -> MSE: 0.000218, MAE: 0.011457, R²: -0.0274
  Directional -> Accuracy: 0.5303, MCC: 0.0589, F1: 0.5079

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.38091 | val 0.34004
  Epoch 020 - train 0.36951 | val 0.33121
  Epoch 021 - train 0.38051 | val 0.32977
  Regression -> MSE: 0.000092, MAE: 0.007947, R²: 0.0057
  Directional -> Accuracy: 0.5357, MCC: -0.0292, F1: 0.6829

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.46456 | val 0.31977
  Epoch 011 - train 0.45515 | val 0.32199
  Regression -> MSE: 0.000106, MAE: 0.008888, R²: -0.0277
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.45078 | val 0.45395
  Epoch 011 - train 0.44566 | val 0.47100
  Regression -> MSE: 0.000240, MAE: 0.012832, R²: -0.0349
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.42296 | val 0.54194
  Epoch 011 - train 0.44112 | val 0.54137
  Regression -> MSE: 0.000176, MAE: 0.007876, R²: -0.0561
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.42787 | val 0.28909
  Epoch 011 - train 0.46084 | val 0.28848
  Regression -> MSE: 0.000237, MAE: 0.011864, R²: -0.0022
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.44578 | val 0.86739
  Epoch 011 - train 0.42029 | val 0.86775
  Regression -> MSE: 0.000233, MAE: 0.010053, R²: -0.0113
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.43568 | val 0.56278
  Epoch 011 - train 0.45521 | val 0.56628
  Regression -> MSE: 0.000136, MAE: 0.008182, R²: -0.0098
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.42774 | val 0.61416
  Epoch 011 - train 0.40454 | val 0.61955
  Regression -> MSE: 0.000189, MAE: 0.010421, R²: -0.0020
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.38361 | val 0.52668
  Epoch 019 - train 0.34986 | val 0.52455
  Regression -> MSE: 0.000358, MAE: 0.012921, R²: -0.3659
  Directional -> Accuracy: 0.4384, MCC: -0.0495, F1: 0.1961

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.40433 | val 0.34967
  Epoch 011 - train 0.42751 | val 0.34886
  Regression -> MSE: 0.000167, MAE: 0.010364, R²: 0.0010
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.38646 | val 0.49078
  Epoch 011 - train 0.40202 | val 0.49327
  Regression -> MSE: 0.000182, MAE: 0.010399, R²: -0.0116
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.45007 | val 0.43926
  Epoch 011 - train 0.43170 | val 0.43862
  Regression -> MSE: 0.000347, MAE: 0.012264, R²: -0.0135
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.47131 | val 0.25852
  Epoch 011 - train 0.50028 | val 0.25867
  Regression -> MSE: 0.000129, MAE: 0.008544, R²: -0.2247
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.40598 | val 0.73117
  Epoch 011 - train 0.43840 | val 0.73773
  Regression -> MSE: 0.000219, MAE: 0.011309, R²: -0.0011
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.44745 | val 0.95500
  Epoch 011 - train 0.44104 | val 0.95618
  Regression -> MSE: 0.000081, MAE: 0.007029, R²: -0.0474
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.43765 | val 0.30832
  Epoch 011 - train 0.44868 | val 0.30832
  Regression -> MSE: 0.000322, MAE: 0.014610, R²: -0.0471
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.49130 | val 0.18950
  Epoch 011 - train 0.45239 | val 0.18940
  Regression -> MSE: 0.000247, MAE: 0.011528, R²: -0.0112
  Directional -> Accuracy: 0.4737, MCC: -0.0181, F1: 0.1667

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.39045 | val 0.64796
  Epoch 011 - train 0.38388 | val 0.65053
  Regression -> MSE: 0.000081, MAE: 0.007053, R²: -0.0055
  Directional -> Accuracy: 0.5200, MCC: 0.1155, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.47560 | val 0.62079
  Epoch 011 - train 0.44592 | val 0.62826
  Regression -> MSE: 0.000308, MAE: 0.014478, R²: -0.0038
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.45401 | val 0.56112
  Epoch 011 - train 0.43446 | val 0.56363
  Regression -> MSE: 0.000103, MAE: 0.007112, R²: -0.0509
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.45852 | val 0.62437
  Epoch 011 - train 0.46672 | val 0.62567
  Regression -> MSE: 0.000172, MAE: 0.009734, R²: -0.0001
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.43013 | val 0.67728
  Epoch 011 - train 0.43779 | val 0.71403
  Regression -> MSE: 0.000226, MAE: 0.011808, R²: -0.0144
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.40731 | val 0.52199
  Epoch 011 - train 0.43138 | val 0.52849
  Regression -> MSE: 0.000093, MAE: 0.007669, R²: -0.0062
  Directional -> Accuracy: 0.3509, MCC: -0.3191, F1: 0.2449

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.47974 | val 0.89848
  Epoch 011 - train 0.44650 | val 0.92196
  Regression -> MSE: 0.000168, MAE: 0.010317, R²: -0.0255
  Directional -> Accuracy: 0.4815, MCC: 0.0000, F1: 0.0000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.40978 | val 0.75714
  Epoch 011 - train 0.41324 | val 0.81366
  Regression -> MSE: 0.000129, MAE: 0.009076, R²: -0.1130
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...

[I 2026-02-22 23:48:10,042] Trial 131 finished with value: -0.01153428840484496 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 32, 'learning_rate': 1.2806430841426628e-05, 'weight_decay': 1.2943442543335232e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 1.1831121293402835, 'early_stopping_min_delta': 0.00829686068529591}. Best is trial 90 with value: -0.011414558399902668.

  Epoch 010 - train 0.43465 | val 0.80770
  Epoch 011 - train 0.42037 | val 0.82787
  Regression -> MSE: 0.000238, MAE: 0.012375, R²: -0.0027
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.45824 | val 0.84022
  Epoch 015 - train 0.42860 | val 0.85572
  Regression -> MSE: 0.000259, MAE: 0.012950, R²: -0.0480
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.43426 | val 0.46320
  Epoch 018 - train 0.42508 | val 0.55868
  Regression -> MSE: 0.000667, MAE: 0.018957, R²: 0.0256
  Directional -> Accuracy: 0.5870, MCC: 0.1202, F1: 0.6984

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.50067 | val 1.01272
  Epoch 020 - train 0.50241 | val 0.97813
  Epoch 025 - train 0.48449 | val 0.98581
  Regression -> MSE: 0.000308, MAE: 0.014451, R²: 0.0077
  Directional -> Accuracy: 0.5957, MCC: 0.2784, F1: 0.7246

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.36984 | val 0.93005
  Epoch 011 - train 0.37951 | val 0.99537
  Regression -> MSE: 0.000350, MAE: 0.014565, R²: -0.0011
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.47585 | val 0.59440
  Epoch 011 - train 0.46822 | val 0.66090
  Regression -> MSE: 0.000203, MAE: 0.010075, R²: 0.0045
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.51901 | val 1.28166
  Epoch 011 - train 0.49784 | val 1.28350
  Regression -> MSE: 0.000627, MAE: 0.019691, R²: -0.1287
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.47225 | val 0.68801
  Epoch 015 - train 0.46660 | val 0.71520
  Regression -> MSE: 0.000243, MAE: 0.011846, R²: 0.0105
  Directional -> Accuracy: 0.5217, MCC: 0.0471, F1: 0.4762

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.47728 | val 0.76863
  Epoch 020 - train 0.37537 | val 0.66635
  Epoch 030 - train 0.46069 | val 0.67731
  Epoch 032 - train 0.40635 | val 0.67390
  Regression -> MSE: 0.000616, MAE: 0.019155, R²: -0.0312
  Directional -> Accuracy: 0.6136, MCC: 0.1511, F1: 0.3704

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.44428 | val 0.63337
  Epoch 011 - train 0.47250 | val 0.63644
  Regression -> MSE: 0.000385, MAE: 0.015990, R²: -0.0044
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.47387 | val 0.79612
  Epoch 011 - train 0.48142 | val 0.79278
  Regression -> MSE: 0.000246, MAE: 0.011622, R²: -0.0193
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.42048 | val 0.84374
  Epoch 011 - train 0.39847 | val 0.87009
  Regression -> MSE: 0.000313, MAE: 0.013619, R²: -0.0070
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.48879 | val 0.65728
  Epoch 011 - train 0.47647 | val 0.67889
  Regression -> MSE: 0.000679, MAE: 0.019568, R²: -0.0019
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.45690 | val 0.55771
  Epoch 011 - train 0.45713 | val 0.57342
  Regression -> MSE: 0.000138, MAE: 0.009051, R²: -0.0019
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.42814 | val 0.70787
  Epoch 018 - train 0.41740 | val 0.71909
  Regression -> MSE: 0.000222, MAE: 0.010581, R²: 0.0142
  Directional -> Accuracy: 0.5410, MCC: 0.0864, F1: 0.5000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.47596 | val 1.47990
  Epoch 011 - train 0.46198 | val 1.50074
  Regression -> MSE: 0.000364, MAE: 0.016052, R²: -0.0042
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.46109 | val 0.52658
  Epoch 015 - train 0.47570 | val 0.51899
  Regression -> MSE: 0.000109, MAE: 0.007907, R²: -0.0146
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.44942 | val 1.18360
  Epoch 011 - train 0.42145 | val 1.20935
  Regression -> MSE: 0.000159, MAE: 0.010028, R²: -0.0210
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.48147 | val 0.57101
  Epoch 011 - train 0.48166 | val 0.58681
  Regression -> MSE: 0.000273, MAE: 0.013042, R²: -0.0023
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.41533 | val 0.79637
  Epoch 011 - train 0.40550 | val 0.79876
  Regression -> MSE: 0.000174, MAE: 0.009314, R²: -0.1605
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.45724 | val 0.93447
  Epoch 017 - train 0.43849 | val 0.98293
  Regression -> MSE: 0.000387, MAE: 0.014978, R²: -0.7120
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.47036 | val 0.72201
  Epoch 011 - train 0.45171 | val 0.72370
  Regression -> MSE: 0.000152, MAE: 0.008791, R²: -0.0613
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.42782 | val 0.62856
  Epoch 011 - train 0.44019 | val 0.63156
  Regression -> MSE: 0.000166, MAE: 0.010388, R²: -0.0025
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.48767 | val 0.68846
  Epoch 011 - train 0.50056 | val 0.68797
  Regression -> MSE: 0.000086, MAE: 0.007056, R²: -0.0039
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.49655 | val 1.44098
  Epoch 011 - train 0.48663 | val 1.52152
  Regression -> MSE: 0.000212, MAE: 0.011132, R²: 0.0011
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.43020 | val 0.33212
  Epoch 020 - train 0.42411 | val 0.32773
  Epoch 021 - train 0.40114 | val 0.32806
  Regression -> MSE: 0.000097, MAE: 0.008005, R²: -0.0562
  Directional -> Accuracy: 0.5893, MCC: 0.2075, F1: 0.5660

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.48497 | val 0.36775
  Epoch 020 - train 0.48484 | val 0.34156
  Epoch 025 - train 0.45225 | val 0.34813
  Regression -> MSE: 0.000103, MAE: 0.008539, R²: 0.0034
  Directional -> Accuracy: 0.6087, MCC: 0.3213, F1: 0.6667

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.47717 | val 0.50653
  Epoch 011 - train 0.47446 | val 0.53947
  Regression -> MSE: 0.000233, MAE: 0.012618, R²: -0.0085
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.48503 | val 0.68513
  Epoch 011 - train 0.45913 | val 0.69679
  Regression -> MSE: 0.000171, MAE: 0.007779, R²: -0.0278
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.45517 | val 0.31031
  Epoch 020 - train 0.47079 | val 0.29585
  Epoch 024 - train 0.47032 | val 0.29923
  Regression -> MSE: 0.000234, MAE: 0.011791, R²: 0.0088
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.50611 | val 1.08674
  Epoch 011 - train 0.48195 | val 1.09087
  Regression -> MSE: 0.000233, MAE: 0.010095, R²: -0.0130
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.48055 | val 0.71489
  Epoch 020 - train 0.50330 | val 0.76765
  Regression -> MSE: 0.000142, MAE: 0.008421, R²: -0.0551
  Directional -> Accuracy: 0.3953, MCC: -0.2013, F1: 0.2353

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.47781 | val 0.73086
  Epoch 011 - train 0.48329 | val 0.73531
  Regression -> MSE: 0.000189, MAE: 0.010482, R²: -0.0057
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.40948 | val 0.62087
  Epoch 017 - train 0.42404 | val 0.62278
  Regression -> MSE: 0.000297, MAE: 0.011523, R²: -0.1324
  Directional -> Accuracy: 0.4384, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.44099 | val 0.36507
  Epoch 011 - train 0.41775 | val 0.36553
  Regression -> MSE: 0.000167, MAE: 0.010365, R²: -0.0021
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.42325 | val 0.62663
  Epoch 011 - train 0.44485 | val 0.63379
  Regression -> MSE: 0.000190, MAE: 0.010683, R²: -0.0560
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.45809 | val 0.44414
  Epoch 011 - train 0.45866 | val 0.44809
  Regression -> MSE: 0.000350, MAE: 0.011784, R²: -0.0221
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.52460 | val 0.23047
  Epoch 011 - train 0.47537 | val 0.22993
  Regression -> MSE: 0.000114, MAE: 0.008318, R²: -0.0872
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.47701 | val 0.85455
  Epoch 011 - train 0.45625 | val 0.86141
  Regression -> MSE: 0.000221, MAE: 0.011370, R²: -0.0127
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.48728 | val 1.19841
  Epoch 020 - train 0.48115 | val 1.21972
  Epoch 021 - train 0.46836 | val 1.22153
  Regression -> MSE: 0.000096, MAE: 0.007652, R²: -0.2381
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.46181 | val 0.34155
  Epoch 011 - train 0.46754 | val 0.34305
  Regression -> MSE: 0.000329, MAE: 0.014947, R²: -0.0706
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.47452 | val 0.19555
  Epoch 011 - train 0.49053 | val 0.19562
  Regression -> MSE: 0.000246, MAE: 0.011550, R²: -0.0093
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.0000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.46500 | val 0.65646
  Epoch 011 - train 0.45821 | val 0.65883
  Regression -> MSE: 0.000081, MAE: 0.007067, R²: 0.0035
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.49813 | val 0.61842
  Epoch 018 - train 0.49460 | val 0.98109
  Regression -> MSE: 0.000316, MAE: 0.014578, R²: -0.0297
  Directional -> Accuracy: 0.4681, MCC: -0.0926, F1: 0.0741

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.46224 | val 0.58178
  Epoch 020 - train 0.44702 | val 0.54459
  Epoch 030 - train 0.45250 | val 0.53822
  Regression -> MSE: 0.000095, MAE: 0.006981, R²: 0.0309
  Directional -> Accuracy: 0.6136, MCC: 0.1841, F1: 0.7119

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.54648 | val 0.79376
  Epoch 020 - train 0.54199 | val 0.77820
  Epoch 025 - train 0.49498 | val 0.78386
  Regression -> MSE: 0.000181, MAE: 0.010521, R²: -0.0550
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.46826 | val 0.63234
  Epoch 011 - train 0.47885 | val 0.64765
  Regression -> MSE: 0.000225, MAE: 0.011794, R²: -0.0110
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.44676 | val 0.73140
  Epoch 011 - train 0.44909 | val 0.78976
  Regression -> MSE: 0.000092, MAE: 0.007629, R²: -0.0002
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.48597 | val 1.10914
  Epoch 011 - train 0.46796 | val 1.15963
  Regression -> MSE: 0.000164, MAE: 0.010241, R²: -0.0017
  Directional -> Accuracy: 0.5556, MCC: 0.1198, F1: 0.6757

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.46143 | val 0.80995
  Epoch 011 - train 0.46017 | val 0.81954
  Regression -> MSE: 0.000118, MAE: 0.008960, R²: -0.0201
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...

[I 2026-02-22 23:49:59,997] Trial 132 finished with value: -0.01153650973831029 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.5, 'batch_size': 32, 'learning_rate': 3.70796569806684e-05, 'weight_decay': 8.169528678924553e-06, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 1.8222376845144597, 'early_stopping_min_delta': 0.008873289049109789}. Best is trial 90 with value: -0.011414558399902668.

  Epoch 010 - train 0.48693 | val 1.05495
  Epoch 011 - train 0.49329 | val 1.09520
  Regression -> MSE: 0.000237, MAE: 0.012324, R²: 0.0017
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.45583 | val 0.84104
  Epoch 020 - train 0.45143 | val 0.86266
  Epoch 023 - train 0.44010 | val 0.87419
  Regression -> MSE: 0.000246, MAE: 0.012442, R²: 0.0051
  Directional -> Accuracy: 0.5714, MCC: 0.1524, F1: 0.5714

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.46179 | val 0.46801
  Epoch 020 - train 0.45260 | val 0.46226
  Epoch 026 - train 0.44230 | val 0.47219
  Regression -> MSE: 0.000684, MAE: 0.019166, R²: 0.0008
  Directional -> Accuracy: 0.6304, MCC: 0.2440, F1: 0.6792

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.48770 | val 1.03506
  Epoch 020 - train 0.49049 | val 1.03210
  Epoch 026 - train 0.47007 | val 1.03870
  Regression -> MSE: 0.000318, MAE: 0.014489, R²: -0.0246
  Directional -> Accuracy: 0.4894, MCC: 0.0150, F1: 0.3333

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.39420 | val 0.51991
  Epoch 011 - train 0.40654 | val 0.55643
  Regression -> MSE: 0.000366, MAE: 0.014849, R²: -0.0492
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.47100 | val 0.46220
  Epoch 020 - train 0.45459 | val 0.43048
  Epoch 030 - train 0.44583 | val 0.43722
  Epoch 034 - train 0.43433 | val 0.44352
  Regression -> MSE: 0.000199, MAE: 0.009600, R²: 0.0224
  Directional -> Accuracy: 0.6471, MCC: 0.3873, F1: 0.7500

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.44787 | val 1.22270
  Epoch 020 - train 0.45923 | val 1.21934
  Epoch 025 - train 0.44625 | val 1.23549
  Regression -> MSE: 0.000573, MAE: 0.018469, R²: -0.0324
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.46080 | val 0.66361
  Epoch 019 - train 0.46091 | val 0.74267
  Regression -> MSE: 0.000241, MAE: 0.011955, R²: 0.0193
  Directional -> Accuracy: 0.5362, MCC: 0.1057, F1: 0.5294

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.48758 | val 0.77860
  Epoch 020 - train 0.41533 | val 0.76819
  Epoch 030 - train 0.43939 | val 0.76712
  Epoch 037 - train 0.39875 | val 0.77429
  Regression -> MSE: 0.000648, MAE: 0.019827, R²: -0.0850
  Directional -> Accuracy: 0.4318, MCC: -0.0534, F1: 0.5098

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.47040 | val 0.62781
  Epoch 011 - train 0.46884 | val 0.63066
  Regression -> MSE: 0.000389, MAE: 0.015951, R²: -0.0151
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.46846 | val 0.74161
  Epoch 013 - train 0.47044 | val 0.76256
  Regression -> MSE: 0.000241, MAE: 0.011854, R²: -0.0002
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.43860 | val 0.84013
  Epoch 011 - train 0.42936 | val 0.85334
  Regression -> MSE: 0.000315, MAE: 0.013619, R²: -0.0121
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.50163 | val 0.67059
  Epoch 011 - train 0.50092 | val 0.67612
  Regression -> MSE: 0.000683, MAE: 0.019510, R²: -0.0080
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.49881 | val 0.51500
  Epoch 011 - train 0.46820 | val 0.51813
  Regression -> MSE: 0.000144, MAE: 0.009443, R²: -0.0393
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.40863 | val 0.74470
  Epoch 020 - train 0.40717 | val 0.74445
  Epoch 025 - train 0.40393 | val 0.74725
  Regression -> MSE: 0.000218, MAE: 0.010624, R²: 0.0326
  Directional -> Accuracy: 0.5246, MCC: 0.0470, F1: 0.5672

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.45125 | val 1.48874
  Epoch 011 - train 0.45827 | val 1.49236
  Regression -> MSE: 0.000362, MAE: 0.016162, R²: -0.0001
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.50198 | val 0.51936
  Epoch 018 - train 0.46128 | val 0.56055
  Regression -> MSE: 0.000107, MAE: 0.007984, R²: 0.0100
  Directional -> Accuracy: 0.5714, MCC: 0.1573, F1: 0.5588

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.43106 | val 1.11827
  Epoch 020 - train 0.44479 | val 1.19154
  Regression -> MSE: 0.000157, MAE: 0.009993, R²: -0.0104
  Directional -> Accuracy: 0.6271, MCC: 0.2333, F1: 0.6857

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.47119 | val 0.51467
  Epoch 011 - train 0.47598 | val 0.52343
  Regression -> MSE: 0.000274, MAE: 0.013154, R²: -0.0072
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.40929 | val 0.75448
  Epoch 020 - train 0.37440 | val 0.72669
  Epoch 030 - train 0.36539 | val 0.72638
  Epoch 033 - train 0.37293 | val 0.72916
  Regression -> MSE: 0.000227, MAE: 0.011241, R²: -0.5172
  Directional -> Accuracy: 0.4308, MCC: -0.0236, F1: 0.2128

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.45925 | val 0.97669
  Epoch 020 - train 0.46164 | val 0.94832
  Epoch 030 - train 0.44034 | val 0.94450
  Epoch 040 - train 0.44333 | val 0.95315
  Epoch 041 - train 0.43063 | val 0.95784
  Regression -> MSE: 0.000396, MAE: 0.015279, R²: -0.7487
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.46878 | val 0.73864
  Epoch 011 - train 0.46526 | val 0.74159
  Regression -> MSE: 0.000153, MAE: 0.008812, R²: -0.0684
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.43476 | val 0.57395
  Epoch 011 - train 0.44591 | val 0.57398
  Regression -> MSE: 0.000173, MAE: 0.010275, R²: -0.0442
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.4923

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.48480 | val 0.69971
  Epoch 016 - train 0.46489 | val 0.71717
  Regression -> MSE: 0.000085, MAE: 0.007039, R²: 0.0041
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.44410 | val 0.70252
  Epoch 019 - train 0.44062 | val 1.06852
  Regression -> MSE: 0.000210, MAE: 0.011202, R²: 0.0077
  Directional -> Accuracy: 0.5000, MCC: 0.0365, F1: 0.5926

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.41144 | val 0.35329
  Epoch 020 - train 0.38351 | val 0.32234
  Epoch 030 - train 0.39478 | val 0.32870
  Regression -> MSE: 0.000094, MAE: 0.007971, R²: -0.0247
  Directional -> Accuracy: 0.5536, MCC: 0.1867, F1: 0.4444

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.48490 | val 0.35104
  Epoch 020 - train 0.47269 | val 0.34949
  Epoch 025 - train 0.46167 | val 0.35058
  Regression -> MSE: 0.000105, MAE: 0.008857, R²: -0.0227
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.47395 | val 0.46565
  Epoch 018 - train 0.47342 | val 0.48877
  Regression -> MSE: 0.000232, MAE: 0.012566, R²: -0.0037
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.47097 | val 0.61926
  Epoch 020 - train 0.44784 | val 0.60872
  Epoch 026 - train 0.45781 | val 0.60955
  Regression -> MSE: 0.000198, MAE: 0.008367, R²: -0.1879
  Directional -> Accuracy: 0.4561, MCC: -0.0251, F1: 0.3111

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.49527 | val 0.30183
  Epoch 011 - train 0.45375 | val 0.30231
  Regression -> MSE: 0.000237, MAE: 0.011859, R²: -0.0006
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.48633 | val 1.07702
  Epoch 011 - train 0.48762 | val 1.07964
  Regression -> MSE: 0.000231, MAE: 0.009908, R²: -0.0011
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.49182 | val 0.71597
  Epoch 011 - train 0.47768 | val 0.71748
  Regression -> MSE: 0.000138, MAE: 0.008314, R²: -0.0242
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.45750 | val 0.75564
  Epoch 020 - train 0.44933 | val 0.76026
  Epoch 023 - train 0.46468 | val 0.76598
  Regression -> MSE: 0.000189, MAE: 0.010494, R²: -0.0022
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.41774 | val 0.65019
  Epoch 020 - train 0.40278 | val 0.63928
  Epoch 024 - train 0.40740 | val 0.64687
  Regression -> MSE: 0.000308, MAE: 0.011687, R²: -0.1753
  Directional -> Accuracy: 0.5068, MCC: 0.2396, F1: 0.2174

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.45286 | val 0.37667
  Epoch 020 - train 0.43958 | val 0.35997
  Epoch 030 - train 0.40144 | val 0.39198
  Epoch 032 - train 0.43333 | val 0.41000
  Regression -> MSE: 0.000162, MAE: 0.010394, R²: 0.0274
  Directional -> Accuracy: 0.5263, MCC: 0.0679, F1: 0.6400

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.40668 | val 0.56060
  Epoch 011 - train 0.39305 | val 0.56235
  Regression -> MSE: 0.000181, MAE: 0.010346, R²: -0.0039
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.45393 | val 0.43600
  Epoch 020 - train 0.44037 | val 0.43199
  Epoch 030 - train 0.42060 | val 0.43250
  Epoch 035 - train 0.42210 | val 0.43404
  Regression -> MSE: 0.000403, MAE: 0.014687, R²: -0.1756
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.48678 | val 0.23763
  Epoch 020 - train 0.45432 | val 0.22956
  Epoch 030 - train 0.42432 | val 0.23459
  Regression -> MSE: 0.000128, MAE: 0.008294, R²: -0.2176
  Directional -> Accuracy: 0.6279, MCC: 0.3176, F1: 0.5000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.46059 | val 0.87694
  Epoch 020 - train 0.44854 | val 0.87563
  Epoch 023 - train 0.44839 | val 0.88272
  Regression -> MSE: 0.000238, MAE: 0.011997, R²: -0.0888
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.45732 | val 1.23191
  Epoch 011 - train 0.47189 | val 1.23454
  Regression -> MSE: 0.000080, MAE: 0.006978, R²: -0.0347
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.47372 | val 0.28602
  Epoch 011 - train 0.46927 | val 0.28630
  Regression -> MSE: 0.000312, MAE: 0.014054, R²: -0.0133
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.45104 | val 0.19935
  Epoch 011 - train 0.49480 | val 0.20000
  Regression -> MSE: 0.000249, MAE: 0.011486, R²: -0.0219
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.43902 | val 0.64883
  Epoch 011 - train 0.44649 | val 0.65416
  Regression -> MSE: 0.000087, MAE: 0.007092, R²: -0.0717
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.48414 | val 0.64584
  Epoch 020 - train 0.48610 | val 0.62167
  Epoch 030 - train 0.43753 | val 0.62571
  Regression -> MSE: 0.000316, MAE: 0.014610, R²: -0.0296
  Directional -> Accuracy: 0.4681, MCC: -0.0687, F1: 0.1935

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.43606 | val 0.62223
  Epoch 020 - train 0.46250 | val 0.61444
  Epoch 030 - train 0.41284 | val 0.60407
  Epoch 040 - train 0.44155 | val 0.60030
  Epoch 050 - train 0.42442 | val 0.59615
  Regression -> MSE: 0.000104, MAE: 0.007382, R²: -0.0606
  Directional -> Accuracy: 0.4773, MCC: -0.2757, F1: 0.6462

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.47457 | val 0.79137
  Epoch 011 - train 0.51056 | val 0.79196
  Regression -> MSE: 0.000172, MAE: 0.009577, R²: -0.0010
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.42998 | val 0.62072
  Epoch 011 - train 0.43854 | val 0.62300
  Regression -> MSE: 0.000224, MAE: 0.011788, R²: -0.0033
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.46051 | val 0.65367
  Epoch 011 - train 0.46723 | val 0.65748
  Regression -> MSE: 0.000096, MAE: 0.007851, R²: -0.0361
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.48137 | val 1.05266
  Epoch 011 - train 0.48183 | val 1.05673
  Regression -> MSE: 0.000166, MAE: 0.010295, R²: -0.0150
  Directional -> Accuracy: 0.4815, MCC: 0.0000, F1: 0.0000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.47089 | val 0.70164
  Epoch 011 - train 0.45514 | val 0.70663
  Regression -> MSE: 0.000132, MAE: 0.009133, R²: -0.1362
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...

[I 2026-02-22 23:51:37,642] Trial 133 finished with value: -0.011625300441084918 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.30000000000000004, 'batch_size': 64, 'learning_rate': 5.235246239519175e-05, 'weight_decay': 2.0898609078086906e-06, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 1.904413119414707, 'early_stopping_min_delta': 0.0010367737645081297}. Best is trial 90 with value: -0.011414558399902668.

  Epoch 010 - train 0.48076 | val 0.95983
  Epoch 011 - train 0.47692 | val 0.96377
  Regression -> MSE: 0.000238, MAE: 0.012339, R²: -0.0042
  Directional -> Accuracy: 0.5410, MCC: 0.0871, F1: 0.1250

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.42051 | val 1.05396
  Epoch 011 - train 0.40432 | val 1.03327
  Regression -> MSE: 0.000248, MAE: 0.012557, R²: -0.0020
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.40305 | val 0.44947
  Epoch 011 - train 0.39606 | val 0.47267
  Regression -> MSE: 0.000716, MAE: 0.019873, R²: -0.0454
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.42327 | val 0.91685
  Epoch 011 - train 0.43632 | val 0.92103
  Regression -> MSE: 0.000310, MAE: 0.014384, R²: 0.0004
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.33723 | val 1.12008
  Epoch 011 - train 0.33035 | val 1.14322
  Regression -> MSE: 0.000364, MAE: 0.014822, R²: -0.0419
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.40998 | val 0.41675
  Epoch 019 - train 0.39944 | val 0.43280
  Regression -> MSE: 0.000207, MAE: 0.009993, R²: -0.0189
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.39367 | val 1.06928
  Epoch 017 - train 0.35991 | val 1.13500
  Regression -> MSE: 0.000565, MAE: 0.018263, R²: -0.0181
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.42920 | val 0.64710
  Epoch 014 - train 0.43361 | val 0.65751
  Regression -> MSE: 0.000245, MAE: 0.012300, R²: 0.0000
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.46879 | val 0.59658
  Epoch 011 - train 0.47480 | val 0.59922
  Regression -> MSE: 0.000606, MAE: 0.019364, R²: -0.0147
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.46623 | val 0.62119
  Epoch 011 - train 0.43765 | val 0.62517
  Regression -> MSE: 0.000384, MAE: 0.016117, R²: 0.0000
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.42889 | val 0.71632
  Epoch 015 - train 0.41369 | val 0.73004
  Regression -> MSE: 0.000243, MAE: 0.011858, R²: -0.0065
  Directional -> Accuracy: 0.4429, MCC: -0.0123, F1: 0.5714

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.37860 | val 0.98122
  Epoch 011 - train 0.38507 | val 1.02008
  Regression -> MSE: 0.000308, MAE: 0.013598, R²: 0.0087
  Directional -> Accuracy: 0.6200, MCC: 0.2766, F1: 0.3448

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.45445 | val 0.98412
  Epoch 011 - train 0.43300 | val 1.02098
  Regression -> MSE: 0.000683, MAE: 0.019498, R²: -0.0089
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.42609 | val 0.48806
  Epoch 017 - train 0.39772 | val 0.64854
  Regression -> MSE: 0.000145, MAE: 0.009207, R²: -0.0485
  Directional -> Accuracy: 0.4419, MCC: -0.0993, F1: 0.4545

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.38301 | val 0.70088
  Epoch 011 - train 0.37470 | val 0.70433
  Regression -> MSE: 0.000225, MAE: 0.010691, R²: -0.0011
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.42354 | val 1.30429
  Epoch 011 - train 0.42073 | val 1.32688
  Regression -> MSE: 0.000362, MAE: 0.016134, R²: -0.0009
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.43198 | val 0.56831
  Epoch 011 - train 0.43327 | val 0.57670
  Regression -> MSE: 0.000107, MAE: 0.007970, R²: 0.0055
  Directional -> Accuracy: 0.5286, MCC: -0.0023, F1: 0.6598

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.39964 | val 1.12748
  Epoch 011 - train 0.38991 | val 1.15813
  Regression -> MSE: 0.000157, MAE: 0.009593, R²: -0.0045
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.42495 | val 0.73293
  Epoch 011 - train 0.42795 | val 0.72751
  Regression -> MSE: 0.000292, MAE: 0.013902, R²: -0.0740
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.34946 | val 0.69743
  Epoch 011 - train 0.35747 | val 0.69743
  Regression -> MSE: 0.000162, MAE: 0.008940, R²: -0.0799
  Directional -> Accuracy: 0.4615, MCC: 0.0914, F1: 0.2222

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.42516 | val 0.80521
  Epoch 018 - train 0.40672 | val 0.82147
  Regression -> MSE: 0.000264, MAE: 0.011471, R²: -0.1683
  Directional -> Accuracy: 0.5200, MCC: 0.1092, F1: 0.3793

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.41187 | val 0.91989
  Epoch 011 - train 0.42122 | val 0.99273
  Regression -> MSE: 0.000156, MAE: 0.008951, R²: -0.0892
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.40597 | val 0.59014
  Epoch 011 - train 0.40629 | val 0.59950
  Regression -> MSE: 0.000165, MAE: 0.010447, R²: -0.0005
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.46417 | val 0.62078
  Epoch 011 - train 0.43980 | val 0.62109
  Regression -> MSE: 0.000088, MAE: 0.007185, R²: -0.0297
  Directional -> Accuracy: 0.4828, MCC: -0.1546, F1: 0.6250

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.42763 | val 0.75491
  Epoch 014 - train 0.41469 | val 0.86161
  Regression -> MSE: 0.000215, MAE: 0.011279, R²: -0.0141
  Directional -> Accuracy: 0.5303, MCC: 0.0665, F1: 0.5373

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.37705 | val 0.33739
  Epoch 017 - train 0.35954 | val 0.33200
  Regression -> MSE: 0.000095, MAE: 0.007835, R²: -0.0276
  Directional -> Accuracy: 0.6071, MCC: 0.2386, F1: 0.5926

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.44941 | val 0.39909
  Epoch 011 - train 0.46329 | val 0.41019
  Regression -> MSE: 0.000120, MAE: 0.009356, R²: -0.1642
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.44833 | val 0.49664
  Epoch 011 - train 0.44875 | val 0.52408
  Regression -> MSE: 0.000232, MAE: 0.012587, R²: -0.0029
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.41734 | val 0.53769
  Epoch 019 - train 0.40834 | val 0.54996
  Regression -> MSE: 0.000216, MAE: 0.009556, R²: -0.2984
  Directional -> Accuracy: 0.4561, MCC: 0.1181, F1: 0.0606

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.45527 | val 0.29521
  Epoch 020 - train 0.43489 | val 0.30704
  Epoch 022 - train 0.41670 | val 0.32116
  Regression -> MSE: 0.000237, MAE: 0.011983, R²: -0.0040
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.42568 | val 0.94890
  Epoch 011 - train 0.42543 | val 0.95076
  Regression -> MSE: 0.000234, MAE: 0.010075, R²: -0.0141
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.44489 | val 0.61749
  Epoch 011 - train 0.44254 | val 0.61682
  Regression -> MSE: 0.000137, MAE: 0.008259, R²: -0.0122
  Directional -> Accuracy: 0.5814, MCC: 0.1627, F1: 0.7000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.41312 | val 0.69614
  Epoch 011 - train 0.40633 | val 0.70952
  Regression -> MSE: 0.000192, MAE: 0.010392, R²: -0.0188
  Directional -> Accuracy: 0.4800, MCC: -0.0612, F1: 0.5517

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.34707 | val 0.61361
  Epoch 011 - train 0.35891 | val 0.61098
  Regression -> MSE: 0.000270, MAE: 0.010616, R²: -0.0322
  Directional -> Accuracy: 0.5479, MCC: 0.0358, F1: 0.6598

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.41402 | val 0.36089
  Epoch 020 - train 0.41888 | val 0.37556
  Epoch 022 - train 0.38712 | val 0.39865
  Regression -> MSE: 0.000165, MAE: 0.010371, R²: 0.0108
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.38427 | val 0.59987
  Epoch 011 - train 0.36979 | val 0.62027
  Regression -> MSE: 0.000179, MAE: 0.010269, R²: 0.0043
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.41434 | val 0.41335
  Epoch 020 - train 0.38346 | val 0.40538
  Regression -> MSE: 0.000369, MAE: 0.013465, R²: -0.0762
  Directional -> Accuracy: 0.5970, MCC: 0.2264, F1: 0.5846

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.45650 | val 0.23612
  Epoch 011 - train 0.47256 | val 0.23860
  Regression -> MSE: 0.000111, MAE: 0.008378, R²: -0.0517
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.42008 | val 0.74282
  Epoch 018 - train 0.41150 | val 0.78868
  Regression -> MSE: 0.000225, MAE: 0.011298, R²: -0.0312
  Directional -> Accuracy: 0.5614, MCC: 0.1418, F1: 0.6032

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.44387 | val 1.03525
  Epoch 011 - train 0.45166 | val 1.03844
  Regression -> MSE: 0.000087, MAE: 0.007294, R²: -0.1190
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.42643 | val 0.34443
  Epoch 011 - train 0.42010 | val 0.34594
  Regression -> MSE: 0.000329, MAE: 0.014960, R²: -0.0705
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.43594 | val 0.20267
  Epoch 011 - train 0.45931 | val 0.20355
  Regression -> MSE: 0.000254, MAE: 0.011497, R²: -0.0421
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.39216 | val 0.61820
  Epoch 011 - train 0.38328 | val 0.62428
  Regression -> MSE: 0.000081, MAE: 0.007107, R²: -0.0036
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.44927 | val 0.58125
  Epoch 018 - train 0.43326 | val 0.87265
  Regression -> MSE: 0.000320, MAE: 0.014665, R²: -0.0422
  Directional -> Accuracy: 0.4894, MCC: 0.0000, F1: 0.0000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.41224 | val 0.60931
  Epoch 011 - train 0.40438 | val 0.61294
  Regression -> MSE: 0.000104, MAE: 0.007115, R²: -0.0574
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.47826 | val 0.67778
  Epoch 011 - train 0.47847 | val 0.67917
  Regression -> MSE: 0.000173, MAE: 0.009496, R²: -0.0061
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.39593 | val 0.67319
  Epoch 011 - train 0.38956 | val 0.69717
  Regression -> MSE: 0.000231, MAE: 0.011893, R²: -0.0346
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.40070 | val 0.53797
  Epoch 016 - train 0.38945 | val 0.56055
  Regression -> MSE: 0.000100, MAE: 0.007898, R²: -0.0820
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.43843 | val 0.94472
  Epoch 011 - train 0.43387 | val 0.95573
  Regression -> MSE: 0.000165, MAE: 0.010255, R²: -0.0099
  Directional -> Accuracy: 0.5185, MCC: 0.1890, F1: 0.1333

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.39049 | val 0.66952
  Epoch 011 - train 0.39669 | val 0.68188
  Regression -> MSE: 0.000120, MAE: 0.008977, R²: -0.0364
  Directional -> Accuracy: 0.4464, MCC: -0.1167, F1: 0.1622

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...

[I 2026-02-22 23:52:41,758] Trial 134 finished with value: -0.01152667629380447 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 32, 'learning_rate': 2.5974435797232843e-05, 'weight_decay': 1.474419465058635e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 1.3737046024037158, 'early_stopping_min_delta': 0.008490314914097435}. Best is trial 90 with value: -0.011414558399902668.

  Epoch 010 - train 0.44656 | val 0.80631
  Epoch 011 - train 0.44029 | val 0.80547
  Regression -> MSE: 0.000244, MAE: 0.012340, R²: -0.0268
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.45985 | val 0.75957
  Epoch 016 - train 0.45220 | val 0.78711
  Regression -> MSE: 0.000247, MAE: 0.012488, R²: 0.0029
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.45771 | val 0.46170
  Epoch 016 - train 0.43969 | val 0.46993
  Regression -> MSE: 0.000686, MAE: 0.019351, R²: -0.0025
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.51400 | val 0.97434
  Epoch 016 - train 0.47858 | val 0.98534
  Regression -> MSE: 0.000317, MAE: 0.014490, R²: -0.0221
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.40044 | val 0.45243
  Epoch 016 - train 0.40599 | val 0.60474
  Regression -> MSE: 0.000351, MAE: 0.014617, R²: -0.0042
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.48447 | val 0.48007
  Epoch 016 - train 0.48272 | val 0.55144
  Regression -> MSE: 0.000206, MAE: 0.010130, R²: -0.0097
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.47227 | val 1.12840
  Epoch 016 - train 0.47858 | val 1.12441
  Regression -> MSE: 0.000554, MAE: 0.018145, R²: 0.0012
  Directional -> Accuracy: 0.4894, MCC: 0.0000, F1: 0.6571

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.48005 | val 0.66738
  Epoch 016 - train 0.47672 | val 0.67279
  Regression -> MSE: 0.000250, MAE: 0.012533, R²: -0.0204
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.49854 | val 0.59780
  Epoch 016 - train 0.52014 | val 0.58924
  Regression -> MSE: 0.000600, MAE: 0.019198, R²: -0.0050
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.47980 | val 0.57464
  Epoch 016 - train 0.44645 | val 0.57890
  Regression -> MSE: 0.000399, MAE: 0.016037, R²: -0.0391
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.47337 | val 0.76137
  Epoch 016 - train 0.49137 | val 0.77881
  Regression -> MSE: 0.000246, MAE: 0.012414, R²: -0.0196
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.41670 | val 0.73414
  Epoch 016 - train 0.45687 | val 0.78178
  Regression -> MSE: 0.000331, MAE: 0.013643, R²: -0.0661
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.50193 | val 0.59997
  Epoch 016 - train 0.48276 | val 0.63181
  Regression -> MSE: 0.000687, MAE: 0.019828, R²: -0.0137
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.55196 | val 0.48951
  Epoch 016 - train 0.51336 | val 0.49209
  Regression -> MSE: 0.000138, MAE: 0.009092, R²: -0.0008
  Directional -> Accuracy: 0.4884, MCC: -0.0759, F1: 0.3125

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.42283 | val 0.68589
  Epoch 016 - train 0.40940 | val 0.70501
  Regression -> MSE: 0.000226, MAE: 0.010710, R²: -0.0047
  Directional -> Accuracy: 0.4098, MCC: -0.1819, F1: 0.3333

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.46964 | val 1.32602
  Epoch 016 - train 0.46280 | val 1.32518
  Regression -> MSE: 0.000363, MAE: 0.016007, R²: -0.0032
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.54042 | val 0.57838
  Epoch 016 - train 0.52955 | val 0.66973
  Regression -> MSE: 0.000111, MAE: 0.008225, R²: -0.0292
  Directional -> Accuracy: 0.4571, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.45294 | val 0.99562
  Epoch 020 - train 0.45041 | val 1.02201
  Regression -> MSE: 0.000162, MAE: 0.010100, R²: -0.0361
  Directional -> Accuracy: 0.5254, MCC: 0.1564, F1: 0.5000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.49483 | val 0.49901
  Epoch 016 - train 0.49237 | val 0.58939
  Regression -> MSE: 0.000274, MAE: 0.013113, R²: -0.0063
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.41054 | val 0.71491
  Epoch 016 - train 0.41003 | val 0.74755
  Regression -> MSE: 0.000170, MAE: 0.009209, R²: -0.1378
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.47394 | val 0.95774
  Epoch 016 - train 0.47594 | val 1.00628
  Regression -> MSE: 0.000229, MAE: 0.010994, R²: -0.0111
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.52514 | val 0.68561
  Epoch 016 - train 0.46476 | val 0.81243
  Regression -> MSE: 0.000147, MAE: 0.008578, R²: -0.0285
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.44235 | val 0.56176
  Epoch 016 - train 0.43948 | val 0.56751
  Regression -> MSE: 0.000168, MAE: 0.010310, R²: -0.0168
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.50341 | val 0.63547
  Epoch 020 - train 0.47573 | val 0.64303
  Regression -> MSE: 0.000088, MAE: 0.007205, R²: -0.0287
  Directional -> Accuracy: 0.5172, MCC: 0.0762, F1: 0.4815

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.48850 | val 0.66798
  Epoch 016 - train 0.47668 | val 0.68072
  Regression -> MSE: 0.000215, MAE: 0.011025, R²: -0.0130
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.40762 | val 0.36145
  Epoch 016 - train 0.40067 | val 0.36176
  Regression -> MSE: 0.000094, MAE: 0.008106, R²: -0.0188
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.47129 | val 0.35522
  Epoch 016 - train 0.47351 | val 0.35761
  Regression -> MSE: 0.000112, MAE: 0.009110, R²: -0.0895
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.50437 | val 0.45846
  Epoch 016 - train 0.50418 | val 0.46553
  Regression -> MSE: 0.000232, MAE: 0.012495, R²: -0.0017
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.49981 | val 0.63063
  Epoch 016 - train 0.50958 | val 0.64321
  Regression -> MSE: 0.000170, MAE: 0.007838, R²: -0.0239
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.50227 | val 0.31760
  Epoch 016 - train 0.47198 | val 0.34333
  Regression -> MSE: 0.000237, MAE: 0.011872, R²: -0.0007
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.44805 | val 1.02740
  Epoch 016 - train 0.44305 | val 1.05524
  Regression -> MSE: 0.000235, MAE: 0.010174, R²: -0.0215
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.51507 | val 0.62310
  Epoch 016 - train 0.53488 | val 0.62540
  Regression -> MSE: 0.000135, MAE: 0.008159, R²: 0.0025
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.48708 | val 0.67193
  Epoch 016 - train 0.50596 | val 0.70054
  Regression -> MSE: 0.000197, MAE: 0.010596, R²: -0.0454
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.39899 | val 0.61948
  Epoch 016 - train 0.41201 | val 0.63070
  Regression -> MSE: 0.000263, MAE: 0.010525, R²: -0.0058
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.54818 | val 0.40761
  Epoch 016 - train 0.52835 | val 0.41631
  Regression -> MSE: 0.000172, MAE: 0.010406, R²: -0.0347
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.47212 | val 0.50051
  Epoch 016 - train 0.44314 | val 0.50187
  Regression -> MSE: 0.000181, MAE: 0.010284, R²: -0.0055
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.46287 | val 0.43447
  Epoch 016 - train 0.46100 | val 0.43928
  Regression -> MSE: 0.000344, MAE: 0.011907, R²: -0.0039
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.54368 | val 0.23936
  Epoch 016 - train 0.52894 | val 0.24641
  Regression -> MSE: 0.000112, MAE: 0.008332, R²: -0.0681
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.48397 | val 0.78281
  Epoch 020 - train 0.48949 | val 0.78576
  Regression -> MSE: 0.000222, MAE: 0.011332, R²: -0.0141
  Directional -> Accuracy: 0.5263, MCC: 0.0145, F1: 0.1290

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.45510 | val 1.08787
  Epoch 020 - train 0.45087 | val 1.07728
  Regression -> MSE: 0.000083, MAE: 0.007078, R²: -0.0648
  Directional -> Accuracy: 0.4894, MCC: -0.0373, F1: 0.5556

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.48929 | val 0.33622
  Epoch 016 - train 0.49974 | val 0.33743
  Regression -> MSE: 0.000331, MAE: 0.014996, R²: -0.0750
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.51429 | val 0.21355
  Epoch 016 - train 0.52533 | val 0.21750
  Regression -> MSE: 0.000256, MAE: 0.011490, R²: -0.0520
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.47594 | val 0.61074
  Epoch 016 - train 0.47446 | val 0.61711
  Regression -> MSE: 0.000085, MAE: 0.007063, R²: -0.0480
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.48600 | val 0.62576
  Epoch 020 - train 0.48531 | val 0.60688
  Regression -> MSE: 0.000304, MAE: 0.014438, R²: 0.0101
  Directional -> Accuracy: 0.5532, MCC: 0.1357, F1: 0.6769

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.48152 | val 0.62521
  Epoch 016 - train 0.48295 | val 0.62574
  Regression -> MSE: 0.000105, MAE: 0.007126, R²: -0.0706
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.49971 | val 0.71516
  Epoch 016 - train 0.51274 | val 0.71760
  Regression -> MSE: 0.000172, MAE: 0.009852, R²: -0.0036
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.41483 | val 0.59851
  Epoch 016 - train 0.42414 | val 0.67197
  Regression -> MSE: 0.000223, MAE: 0.011744, R²: -0.0006
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.48358 | val 0.61936
  Epoch 016 - train 0.47176 | val 0.67087
  Regression -> MSE: 0.000097, MAE: 0.007939, R²: -0.0467
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.48486 | val 0.94431
  Epoch 016 - train 0.49334 | val 0.94713
  Regression -> MSE: 0.000165, MAE: 0.010288, R²: -0.0104
  Directional -> Accuracy: 0.4815, MCC: 0.0000, F1: 0.0000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.52849 | val 0.74682
  Epoch 016 - train 0.51139 | val 0.90373
  Regression -> MSE: 0.000116, MAE: 0.008931, R²: -0.0016
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.48403 | val 0.84803

[I 2026-02-22 23:53:12,651] Trial 135 finished with value: -0.011437668047717063 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.30000000000000004, 'batch_size': 64, 'learning_rate': 1.8298022534926318e-05, 'weight_decay': 4.919467448936656e-06, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 1.537159744878948, 'early_stopping_min_delta': 0.007311058075169055}. Best is trial 90 with value: -0.011414558399902668.

  Epoch 016 - train 0.49776 | val 0.85266
  Regression -> MSE: 0.000239, MAE: 0.012367, R²: -0.0057
  Directional -> Accuracy: 0.3607, MCC: -0.2746, F1: 0.4000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.41272 | val 0.69622
  Epoch 016 - train 0.40843 | val 0.72560
  Regression -> MSE: 0.000261, MAE: 0.013029, R²: -0.0557
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.42416 | val 0.38917
  Epoch 016 - train 0.42901 | val 0.40630
  Regression -> MSE: 0.000729, MAE: 0.020068, R²: -0.0645
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.43457 | val 0.79974
  Epoch 016 - train 0.43465 | val 0.79747
  Regression -> MSE: 0.000310, MAE: 0.014443, R²: -0.0004
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.34635 | val 0.35961
  Epoch 016 - train 0.32210 | val 0.47557
  Regression -> MSE: 0.000349, MAE: 0.014548, R²: 0.0006
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.45413 | val 0.41746
  Epoch 016 - train 0.44432 | val 0.42295
  Regression -> MSE: 0.000211, MAE: 0.010261, R²: -0.0385
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.41184 | val 0.94107
  Epoch 016 - train 0.41114 | val 0.94512
  Regression -> MSE: 0.000581, MAE: 0.018622, R²: -0.0472
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.43579 | val 0.57662
  Epoch 016 - train 0.44241 | val 0.59034
  Regression -> MSE: 0.000253, MAE: 0.011983, R²: -0.0303
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.41649 | val 0.55517
  Epoch 020 - train 0.42478 | val 0.53289
  Epoch 030 - train 0.41055 | val 0.49705
  Epoch 040 - train 0.43897 | val 0.47305
  Epoch 050 - train 0.39886 | val 0.47203
  Regression -> MSE: 0.000595, MAE: 0.018872, R²: 0.0036
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.40426 | val 0.53324
  Epoch 020 - train 0.39210 | val 0.52077
  Epoch 030 - train 0.41647 | val 0.51539
  Epoch 035 - train 0.37643 | val 0.51524
  Regression -> MSE: 0.000436, MAE: 0.017651, R²: -0.1364
  Directional -> Accuracy: 0.4082, MCC: -0.1804, F1: 0.5672

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.45018 | val 0.61271
  Epoch 016 - train 0.43156 | val 0.63054
  Regression -> MSE: 0.000244, MAE: 0.012226, R²: -0.0111
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.39436 | val 0.70797
  Epoch 016 - train 0.38114 | val 0.71566
  Regression -> MSE: 0.000312, MAE: 0.013841, R²: -0.0022
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.6301

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.43803 | val 0.50971
  Epoch 016 - train 0.42474 | val 0.53132
  Regression -> MSE: 0.000680, MAE: 0.019598, R²: -0.0039
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.44766 | val 0.41499
  Epoch 016 - train 0.42873 | val 0.41639
  Regression -> MSE: 0.000144, MAE: 0.009472, R²: -0.0428
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.37699 | val 0.61683
  Epoch 016 - train 0.36138 | val 0.63070
  Regression -> MSE: 0.000226, MAE: 0.010794, R²: -0.0062
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.41976 | val 1.05871
  Epoch 016 - train 0.40827 | val 1.07243
  Regression -> MSE: 0.000365, MAE: 0.015933, R²: -0.0068
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.43844 | val 0.44338
  Epoch 016 - train 0.42437 | val 0.46921
  Regression -> MSE: 0.000109, MAE: 0.008081, R²: -0.0075
  Directional -> Accuracy: 0.4571, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.50209 | val 0.80090
  Epoch 016 - train 0.45342 | val 0.86558
  Regression -> MSE: 0.000169, MAE: 0.010522, R²: -0.0845
  Directional -> Accuracy: 0.3729, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.43298 | val 0.42594
  Epoch 016 - train 0.41914 | val 0.44764
  Regression -> MSE: 0.000273, MAE: 0.012971, R²: -0.0018
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.36204 | val 0.62685
  Epoch 016 - train 0.37448 | val 0.64400
  Regression -> MSE: 0.000156, MAE: 0.008808, R²: -0.0432
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.42961 | val 0.71614
  Epoch 020 - train 0.42145 | val 0.75331
  Epoch 023 - train 0.43765 | val 0.75433
  Regression -> MSE: 0.000226, MAE: 0.010728, R²: 0.0026
  Directional -> Accuracy: 0.6267, MCC: 0.2371, F1: 0.6889

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.42437 | val 0.59421
  Epoch 016 - train 0.43842 | val 0.61659
  Regression -> MSE: 0.000143, MAE: 0.008316, R²: 0.0003
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.39050 | val 0.49019
  Epoch 016 - train 0.39951 | val 0.49812
  Regression -> MSE: 0.000170, MAE: 0.010257, R²: -0.0287
  Directional -> Accuracy: 0.4697, MCC: -0.0707, F1: 0.5783

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.44188 | val 0.53864
  Epoch 016 - train 0.44731 | val 0.54191
  Regression -> MSE: 0.000092, MAE: 0.007383, R²: -0.0746
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.42739 | val 0.54387
  Epoch 016 - train 0.41338 | val 0.55458
  Regression -> MSE: 0.000213, MAE: 0.011068, R²: -0.0044
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.39540 | val 0.34602
  Epoch 016 - train 0.39424 | val 0.35169
  Regression -> MSE: 0.000103, MAE: 0.008281, R²: -0.1152
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.41171 | val 0.29961
  Epoch 016 - train 0.41824 | val 0.30187
  Regression -> MSE: 0.000106, MAE: 0.008868, R²: -0.0253
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.41667 | val 0.39313
  Epoch 020 - train 0.41940 | val 0.38726
  Epoch 029 - train 0.41498 | val 0.38711
  Regression -> MSE: 0.000237, MAE: 0.012753, R²: -0.0240
  Directional -> Accuracy: 0.4419, MCC: -0.1872, F1: 0.5556

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.40813 | val 0.50882
  Epoch 016 - train 0.40489 | val 0.51387
  Regression -> MSE: 0.000181, MAE: 0.007975, R²: -0.0879
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.45154 | val 0.29548
  Epoch 020 - train 0.44762 | val 0.28569
  Epoch 030 - train 0.41386 | val 0.28082
  Epoch 036 - train 0.41827 | val 0.28049
  Regression -> MSE: 0.000236, MAE: 0.011856, R²: 0.0016
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.41161 | val 0.82199
  Epoch 016 - train 0.41162 | val 0.83997
  Regression -> MSE: 0.000235, MAE: 0.010041, R²: -0.0183
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.47459 | val 0.52410
  Epoch 016 - train 0.46596 | val 0.52765
  Regression -> MSE: 0.000134, MAE: 0.008193, R²: 0.0079
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.42355 | val 0.57183
  Epoch 016 - train 0.40931 | val 0.59208
  Regression -> MSE: 0.000190, MAE: 0.010379, R²: -0.0083
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.36916 | val 0.50800
  Epoch 016 - train 0.36672 | val 0.51109
  Regression -> MSE: 0.000271, MAE: 0.010647, R²: -0.0349
  Directional -> Accuracy: 0.4521, MCC: -0.0788, F1: 0.4444

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.40672 | val 0.34091
  Epoch 020 - train 0.41484 | val 0.33363
  Epoch 030 - train 0.39018 | val 0.34860
  Epoch 031 - train 0.39747 | val 0.35292
  Regression -> MSE: 0.000165, MAE: 0.010373, R²: 0.0128
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.39583 | val 0.46703
  Epoch 016 - train 0.39678 | val 0.48379
  Regression -> MSE: 0.000182, MAE: 0.010413, R²: -0.0132
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.46151 | val 0.40393
  Epoch 016 - train 0.45883 | val 0.42102
  Regression -> MSE: 0.000348, MAE: 0.011723, R²: -0.0143
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.45080 | val 0.21997
  Epoch 016 - train 0.44892 | val 0.22666
  Regression -> MSE: 0.000115, MAE: 0.008361, R²: -0.0951
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.40917 | val 0.64993
  Epoch 016 - train 0.40687 | val 0.65672
  Regression -> MSE: 0.000219, MAE: 0.011292, R²: -0.0000
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.40589 | val 0.89289
  Epoch 016 - train 0.40186 | val 0.90214
  Regression -> MSE: 0.000081, MAE: 0.006993, R²: -0.0381
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.40276 | val 0.33052
  Epoch 016 - train 0.40185 | val 0.32892
  Regression -> MSE: 0.000337, MAE: 0.015242, R²: -0.0954
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.46730 | val 0.19661
  Epoch 016 - train 0.48737 | val 0.20088
  Regression -> MSE: 0.000246, MAE: 0.011580, R²: -0.0096
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.0000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.40373 | val 0.52323
  Epoch 016 - train 0.40733 | val 0.54448
  Regression -> MSE: 0.000081, MAE: 0.007059, R²: -0.0045
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.43701 | val 0.52865
  Epoch 016 - train 0.42962 | val 0.52579
  Regression -> MSE: 0.000312, MAE: 0.014535, R²: -0.0161
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.42384 | val 0.47855
  Epoch 016 - train 0.40555 | val 0.48317
  Regression -> MSE: 0.000099, MAE: 0.007181, R²: -0.0078
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.48658 | val 0.58550
  Epoch 016 - train 0.45550 | val 0.58793
  Regression -> MSE: 0.000173, MAE: 0.009954, R²: -0.0073
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.43194 | val 0.50769
  Epoch 016 - train 0.41799 | val 0.53186
  Regression -> MSE: 0.000232, MAE: 0.011981, R²: -0.0416
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.39690 | val 0.49164
  Epoch 016 - train 0.38462 | val 0.50521
  Regression -> MSE: 0.000093, MAE: 0.007674, R²: -0.0053
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.43950 | val 0.74424
  Epoch 016 - train 0.43818 | val 0.75510
  Regression -> MSE: 0.000164, MAE: 0.010294, R²: -0.0023
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.40516 | val 0.54723
  Epoch 016 - train 0.41188 | val 0.55344
  Regression -> MSE: 0.000123, MAE: 0.009017, R²: -0.0636
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.42828 | val 0.68776

[I 2026-02-22 23:53:44,833] Trial 136 finished with value: -0.011489232407207775 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.30000000000000004, 'batch_size': 64, 'learning_rate': 1.7808380115593908e-05, 'weight_decay': 3.5012351824417653e-06, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 1.053927812997794, 'early_stopping_min_delta': 0.007357048828347181}. Best is trial 90 with value: -0.011414558399902668.

  Epoch 016 - train 0.41349 | val 0.72641
  Regression -> MSE: 0.000241, MAE: 0.012323, R²: -0.0153
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.45446 | val 0.80684
  Epoch 020 - train 0.44864 | val 0.80374
  Regression -> MSE: 0.000259, MAE: 0.012921, R²: -0.0474
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.50694 | val 0.48836
  Epoch 016 - train 0.49766 | val 0.50620
  Regression -> MSE: 0.000689, MAE: 0.019433, R²: -0.0071
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.49719 | val 0.98691
  Epoch 016 - train 0.48481 | val 0.99315
  Regression -> MSE: 0.000316, MAE: 0.014467, R²: -0.0183
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.43135 | val 0.47460
  Epoch 016 - train 0.41712 | val 0.66405
  Regression -> MSE: 0.000351, MAE: 0.014571, R²: -0.0042
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.47380 | val 0.45851
  Epoch 016 - train 0.45006 | val 0.46922
  Regression -> MSE: 0.000205, MAE: 0.010093, R²: -0.0086
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.47068 | val 1.14930
  Epoch 016 - train 0.45337 | val 1.14902
  Regression -> MSE: 0.000564, MAE: 0.018243, R²: -0.0166
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.49768 | val 0.65042
  Epoch 020 - train 0.48746 | val 0.65107
  Regression -> MSE: 0.000249, MAE: 0.012309, R²: -0.0138
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.45898 | val 0.67609
  Epoch 020 - train 0.45469 | val 0.65613
  Regression -> MSE: 0.000617, MAE: 0.019605, R²: -0.0323
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.46952 | val 0.60343
  Epoch 016 - train 0.46256 | val 0.61731
  Regression -> MSE: 0.000389, MAE: 0.015976, R²: -0.0128
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.48088 | val 0.68472
  Epoch 016 - train 0.47361 | val 0.70419
  Regression -> MSE: 0.000245, MAE: 0.011658, R²: -0.0149
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.43740 | val 0.79283
  Epoch 016 - train 0.46496 | val 0.82618
  Regression -> MSE: 0.000311, MAE: 0.013642, R²: 0.0010
  Directional -> Accuracy: 0.5600, MCC: 0.1048, F1: 0.1538

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.50127 | val 0.60907
  Epoch 020 - train 0.47335 | val 0.60451
  Regression -> MSE: 0.000683, MAE: 0.019562, R²: -0.0077
  Directional -> Accuracy: 0.4310, MCC: -0.1826, F1: 0.5714

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.46950 | val 0.49202
  Epoch 016 - train 0.49167 | val 0.51106
  Regression -> MSE: 0.000139, MAE: 0.009240, R²: -0.0081
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.42490 | val 0.71508
  Epoch 020 - train 0.41806 | val 0.70333
  Regression -> MSE: 0.000223, MAE: 0.010741, R²: 0.0099
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.47180 | val 1.36944
  Epoch 016 - train 0.47423 | val 1.39163
  Regression -> MSE: 0.000363, MAE: 0.016220, R²: -0.0027
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.48334 | val 0.50387
  Epoch 016 - train 0.47052 | val 0.51025
  Regression -> MSE: 0.000111, MAE: 0.007966, R²: -0.0280
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.44371 | val 1.04599
  Epoch 020 - train 0.45737 | val 1.02337
  Regression -> MSE: 0.000154, MAE: 0.009772, R²: 0.0127
  Directional -> Accuracy: 0.6610, MCC: 0.2392, F1: 0.7500

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.54549 | val 0.47900
  Epoch 016 - train 0.54251 | val 0.48367
  Regression -> MSE: 0.000273, MAE: 0.012957, R²: -0.0023
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.39146 | val 0.71593
  Epoch 020 - train 0.38059 | val 0.69232
  Regression -> MSE: 0.000210, MAE: 0.010689, R²: -0.4044
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.46140 | val 0.89069
  Epoch 020 - train 0.45662 | val 0.88395
  Regression -> MSE: 0.000248, MAE: 0.011268, R²: -0.0942
  Directional -> Accuracy: 0.5333, MCC: 0.1079, F1: 0.4615

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.47612 | val 0.69604
  Epoch 016 - train 0.48306 | val 0.69228
  Regression -> MSE: 0.000145, MAE: 0.008461, R²: -0.0130
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.46809 | val 0.58590
  Epoch 016 - train 0.44152 | val 0.58171
  Regression -> MSE: 0.000165, MAE: 0.010542, R²: 0.0017
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.49018 | val 0.64350
  Epoch 016 - train 0.46358 | val 0.64314
  Regression -> MSE: 0.000088, MAE: 0.007190, R²: -0.0307
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.51737 | val 0.67343
  Epoch 016 - train 0.51677 | val 0.70159
  Regression -> MSE: 0.000215, MAE: 0.011049, R²: -0.0136
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.41573 | val 0.35940
  Epoch 020 - train 0.41101 | val 0.33916
  Regression -> MSE: 0.000096, MAE: 0.008086, R²: -0.0401
  Directional -> Accuracy: 0.5000, MCC: -0.0278, F1: 0.5758

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.49994 | val 0.35620
  Epoch 020 - train 0.49820 | val 0.34331
  Regression -> MSE: 0.000107, MAE: 0.008915, R²: -0.0380
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.47452 | val 0.44523
  Epoch 016 - train 0.49356 | val 0.44700
  Regression -> MSE: 0.000236, MAE: 0.012708, R²: -0.0195
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.47021 | val 0.58504
  Epoch 020 - train 0.44724 | val 0.56210
  Regression -> MSE: 0.000193, MAE: 0.008270, R²: -0.1591
  Directional -> Accuracy: 0.4386, MCC: -0.1505, F1: 0.5152

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.49927 | val 0.31650
  Epoch 016 - train 0.49867 | val 0.31564
  Regression -> MSE: 0.000238, MAE: 0.011895, R²: -0.0055
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.52996 | val 1.04823
  Epoch 016 - train 0.51548 | val 1.06214
  Regression -> MSE: 0.000237, MAE: 0.010249, R²: -0.0274
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.48293 | val 0.64929
  Epoch 016 - train 0.48943 | val 0.64852
  Regression -> MSE: 0.000136, MAE: 0.008254, R²: -0.0047
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.47851 | val 0.66347
  Epoch 016 - train 0.47030 | val 0.66924
  Regression -> MSE: 0.000202, MAE: 0.010797, R²: -0.0716
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.38908 | val 0.61886
  Epoch 016 - train 0.39285 | val 0.61455
  Regression -> MSE: 0.000264, MAE: 0.010504, R²: -0.0101
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.49367 | val 0.36247
  Epoch 016 - train 0.50268 | val 0.36408
  Regression -> MSE: 0.000168, MAE: 0.010367, R²: -0.0088
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.42252 | val 0.57474
  Epoch 016 - train 0.44400 | val 0.57744
  Regression -> MSE: 0.000189, MAE: 0.010650, R²: -0.0491
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.44471 | val 0.42868
  Epoch 020 - train 0.44928 | val 0.41846
  Regression -> MSE: 0.000340, MAE: 0.012015, R²: 0.0072
  Directional -> Accuracy: 0.5672, MCC: 0.1875, F1: 0.5246

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.51092 | val 0.23442
  Epoch 016 - train 0.49758 | val 0.23480
  Regression -> MSE: 0.000112, MAE: 0.008325, R²: -0.0641
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.47979 | val 0.80321
  Epoch 016 - train 0.45767 | val 0.80847
  Regression -> MSE: 0.000219, MAE: 0.011305, R²: -0.0006
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.51697 | val 1.12048
  Epoch 016 - train 0.48967 | val 1.12197
  Regression -> MSE: 0.000082, MAE: 0.007039, R²: -0.0502
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.46289 | val 0.29349
  Epoch 016 - train 0.45290 | val 0.29178
  Regression -> MSE: 0.000317, MAE: 0.014354, R²: -0.0309
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.47066 | val 0.20216
  Epoch 016 - train 0.50285 | val 0.20054
  Regression -> MSE: 0.000253, MAE: 0.011486, R²: -0.0376
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.44165 | val 0.59581
  Epoch 020 - train 0.44623 | val 0.59049
  Regression -> MSE: 0.000081, MAE: 0.007094, R²: -0.0055
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.57061 | val 0.68077
  Epoch 016 - train 0.55710 | val 0.70952
  Regression -> MSE: 0.000311, MAE: 0.014496, R²: -0.0130
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.48606 | val 0.58755
  Epoch 016 - train 0.46903 | val 0.58869
  Regression -> MSE: 0.000101, MAE: 0.007104, R²: -0.0259
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.51567 | val 0.74167
  Epoch 016 - train 0.48578 | val 0.74351
  Regression -> MSE: 0.000174, MAE: 0.010074, R²: -0.0132
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.50961 | val 0.63358
  Epoch 016 - train 0.48279 | val 0.71532
  Regression -> MSE: 0.000232, MAE: 0.011920, R²: -0.0389
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.42244 | val 0.58061
  Epoch 016 - train 0.45293 | val 0.60529
  Regression -> MSE: 0.000093, MAE: 0.007670, R²: -0.0041
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.51176 | val 0.93643
  Epoch 016 - train 0.51725 | val 0.93785
  Regression -> MSE: 0.000164, MAE: 0.010261, R²: -0.0018
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.45972 | val 0.64982
  Epoch 016 - train 0.49087 | val 0.66346
  Regression -> MSE: 0.000131, MAE: 0.009130, R²: -0.1317
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.46172 | val 0.86659

[I 2026-02-22 23:55:26,515] Trial 137 finished with value: -0.011477486006488836 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 64, 'learning_rate': 1.3421664497332444e-05, 'weight_decay': 2.693178222260959e-06, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 1.5837878317352745, 'early_stopping_min_delta': 0.007054577135166224}. Best is trial 90 with value: -0.011414558399902668.

  Epoch 016 - train 0.47870 | val 0.88627
  Regression -> MSE: 0.000237, MAE: 0.012327, R²: -0.0005
  Directional -> Accuracy: 0.5902, MCC: 0.1874, F1: 0.6032

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.46618 | val 0.81026
  Epoch 016 - train 0.45031 | val 0.81584
  Regression -> MSE: 0.000248, MAE: 0.012572, R²: -0.0021
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.47982 | val 0.53361
  Epoch 016 - train 0.46570 | val 0.57038
  Regression -> MSE: 0.000688, MAE: 0.019407, R²: -0.0054
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.48145 | val 0.96224
  Epoch 016 - train 0.46779 | val 0.99320
  Regression -> MSE: 0.000312, MAE: 0.014510, R²: -0.0069
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.39632 | val 0.44122
  Epoch 016 - train 0.37561 | val 0.45818
  Regression -> MSE: 0.000364, MAE: 0.014800, R²: -0.0427
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.46198 | val 0.44611
  Epoch 020 - train 0.43776 | val 0.46528
  Regression -> MSE: 0.000206, MAE: 0.010156, R²: -0.0128
  Directional -> Accuracy: 0.5098, MCC: 0.0048, F1: 0.5763

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.44319 | val 1.12662
  Epoch 020 - train 0.44686 | val 1.11602
  Regression -> MSE: 0.000535, MAE: 0.017950, R²: 0.0370
  Directional -> Accuracy: 0.5106, MCC: 0.0183, F1: 0.4651

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.46317 | val 0.68795
  Epoch 019 - train 0.45138 | val 0.70897
  Regression -> MSE: 0.000245, MAE: 0.012148, R²: 0.0026
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.44579 | val 0.76855
  Epoch 016 - train 0.43097 | val 0.79809
  Regression -> MSE: 0.000661, MAE: 0.020410, R²: -0.1067
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.48413 | val 0.55170
  Epoch 020 - train 0.46148 | val 0.53112
  Regression -> MSE: 0.000388, MAE: 0.016231, R²: -0.0127
  Directional -> Accuracy: 0.4286, MCC: -0.1118, F1: 0.5882

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.45526 | val 0.66239
  Epoch 016 - train 0.47422 | val 0.67727
  Regression -> MSE: 0.000245, MAE: 0.011644, R²: -0.0132
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.43771 | val 0.75298
  Epoch 020 - train 0.43652 | val 0.77920
  Regression -> MSE: 0.000312, MAE: 0.013264, R²: -0.0024
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.53226 | val 0.68310
  Epoch 016 - train 0.49689 | val 0.73067
  Regression -> MSE: 0.000694, MAE: 0.020049, R²: -0.0245
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.46646 | val 0.51248
  Epoch 016 - train 0.46866 | val 0.56778
  Regression -> MSE: 0.000139, MAE: 0.009183, R²: -0.0052
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.41437 | val 0.69700
  Epoch 016 - train 0.41946 | val 0.72529
  Regression -> MSE: 0.000231, MAE: 0.010913, R²: -0.0270
  Directional -> Accuracy: 0.4918, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.44361 | val 1.37483
  Epoch 016 - train 0.44863 | val 1.49625
  Regression -> MSE: 0.000362, MAE: 0.016142, R²: 0.0003
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.50721 | val 0.49863
  Epoch 016 - train 0.47340 | val 0.49582
  Regression -> MSE: 0.000108, MAE: 0.007976, R²: 0.0005
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.44634 | val 1.10416
  Epoch 016 - train 0.44497 | val 1.17323
  Regression -> MSE: 0.000156, MAE: 0.009520, R²: -0.0015
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.47651 | val 0.54138
  Epoch 016 - train 0.48484 | val 0.55183
  Regression -> MSE: 0.000281, MAE: 0.013429, R²: -0.0310
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.38553 | val 0.70437
  Epoch 020 - train 0.38603 | val 0.70282
  Regression -> MSE: 0.000170, MAE: 0.009436, R²: -0.1340
  Directional -> Accuracy: 0.5538, MCC: 0.1985, F1: 0.4912

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.46803 | val 0.85806
  Epoch 020 - train 0.44553 | val 0.85289
  Regression -> MSE: 0.000289, MAE: 0.012452, R²: -0.2774
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.47670 | val 0.72840
  Epoch 016 - train 0.47631 | val 0.79270
  Regression -> MSE: 0.000144, MAE: 0.008328, R²: -0.0018
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.46007 | val 0.54257
  Epoch 016 - train 0.46080 | val 0.54397
  Regression -> MSE: 0.000172, MAE: 0.010265, R²: -0.0425
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.50288 | val 0.67355
  Epoch 016 - train 0.50693 | val 0.69555
  Regression -> MSE: 0.000086, MAE: 0.007033, R²: -0.0039
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.48175 | val 0.82722
  Epoch 016 - train 0.46732 | val 0.80149
  Regression -> MSE: 0.000213, MAE: 0.011101, R²: -0.0038
  Directional -> Accuracy: 0.4242, MCC: -0.1413, F1: 0.4722

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.42234 | val 0.33198
  Epoch 020 - train 0.40483 | val 0.33233
  Regression -> MSE: 0.000108, MAE: 0.008435, R²: -0.1761
  Directional -> Accuracy: 0.4643, MCC: 0.1211, F1: 0.0625

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.52904 | val 0.32927
  Epoch 016 - train 0.52409 | val 0.33527
  Regression -> MSE: 0.000104, MAE: 0.008763, R²: -0.0063
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.49589 | val 0.47706
  Epoch 016 - train 0.48540 | val 0.54618
  Regression -> MSE: 0.000232, MAE: 0.012579, R²: -0.0034
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.46228 | val 0.59075
  Epoch 016 - train 0.46108 | val 0.59081
  Regression -> MSE: 0.000175, MAE: 0.007872, R²: -0.0536
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.54826 | val 0.34847
  Epoch 016 - train 0.52087 | val 0.35605
  Regression -> MSE: 0.000241, MAE: 0.012091, R²: -0.0205
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.46394 | val 1.01104
  Epoch 016 - train 0.46039 | val 1.07510
  Regression -> MSE: 0.000234, MAE: 0.010132, R²: -0.0161
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.50261 | val 0.64609
  Epoch 016 - train 0.48767 | val 0.69297
  Regression -> MSE: 0.000136, MAE: 0.008273, R²: -0.0083
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.46006 | val 0.66522
  Epoch 016 - train 0.47218 | val 0.67932
  Regression -> MSE: 0.000193, MAE: 0.010422, R²: -0.0232
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.43000 | val 0.59735
  Epoch 016 - train 0.42976 | val 0.59505
  Regression -> MSE: 0.000278, MAE: 0.010907, R²: -0.0626
  Directional -> Accuracy: 0.4384, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.46748 | val 0.35737
  Epoch 016 - train 0.45469 | val 0.35895
  Regression -> MSE: 0.000168, MAE: 0.010373, R²: -0.0051
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.43391 | val 0.50037
  Epoch 016 - train 0.40471 | val 0.51044
  Regression -> MSE: 0.000181, MAE: 0.010282, R²: -0.0047
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.45174 | val 0.45954
  Epoch 016 - train 0.44740 | val 0.45899
  Regression -> MSE: 0.000345, MAE: 0.011696, R²: -0.0068
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.46385 | val 0.23308
  Epoch 016 - train 0.47733 | val 0.23252
  Regression -> MSE: 0.000114, MAE: 0.008335, R²: -0.0827
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.45318 | val 0.77781
  Epoch 020 - train 0.45331 | val 0.77248
  Regression -> MSE: 0.000225, MAE: 0.011541, R²: -0.0312
  Directional -> Accuracy: 0.5263, MCC: 0.0970, F1: 0.6197

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.49146 | val 1.06133
  Epoch 020 - train 0.49696 | val 1.12732
  Regression -> MSE: 0.000084, MAE: 0.007151, R²: -0.0861
  Directional -> Accuracy: 0.5106, MCC: 0.1042, F1: 0.4889

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.46750 | val 0.31722
  Epoch 016 - train 0.43792 | val 0.33607
  Regression -> MSE: 0.000322, MAE: 0.014599, R²: -0.0452
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.47820 | val 0.20076
  Epoch 016 - train 0.49313 | val 0.19912
  Regression -> MSE: 0.000253, MAE: 0.011474, R²: -0.0374
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.44111 | val 0.57459
  Epoch 020 - train 0.40759 | val 0.57333
  Regression -> MSE: 0.000081, MAE: 0.007043, R²: -0.0010
  Directional -> Accuracy: 0.5600, MCC: 0.1202, F1: 0.5600

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.46567 | val 0.64289
  Epoch 016 - train 0.47564 | val 0.76607
  Regression -> MSE: 0.000308, MAE: 0.014513, R²: -0.0029
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.44584 | val 0.60553
  Epoch 016 - train 0.47860 | val 0.62921
  Regression -> MSE: 0.000104, MAE: 0.007112, R²: -0.0549
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.53717 | val 0.71637
  Epoch 020 - train 0.52495 | val 0.69968
  Regression -> MSE: 0.000177, MAE: 0.009447, R²: -0.0317
  Directional -> Accuracy: 0.6122, MCC: 0.0475, F1: 0.0952

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.44441 | val 0.60852
  Epoch 016 - train 0.45959 | val 0.63120
  Regression -> MSE: 0.000224, MAE: 0.011792, R²: -0.0040
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.45683 | val 0.63009
  Epoch 016 - train 0.43882 | val 0.68096
  Regression -> MSE: 0.000095, MAE: 0.007804, R²: -0.0260
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.49121 | val 0.89094
  Epoch 016 - train 0.46473 | val 0.89589
  Regression -> MSE: 0.000164, MAE: 0.010260, R²: -0.0017
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.44631 | val 0.65027
  Epoch 016 - train 0.47059 | val 0.65517
  Regression -> MSE: 0.000120, MAE: 0.008978, R²: -0.0349
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.47756 | val 0.93962

[I 2026-02-22 23:56:35,735] Trial 138 finished with value: -0.011462711417765998 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.30000000000000004, 'batch_size': 32, 'learning_rate': 8.76575043215955e-06, 'weight_decay': 1.6615714224797982e-06, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 1.4822809682680167, 'early_stopping_min_delta': 0.007616182976525034}. Best is trial 90 with value: -0.011414558399902668.

  Epoch 016 - train 0.47642 | val 1.01374
  Regression -> MSE: 0.000240, MAE: 0.012342, R²: -0.0112
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.16465 | val 0.23485
  Epoch 016 - train 0.16301 | val 0.23163
  Regression -> MSE: 0.000256, MAE: 0.012885, R²: -0.0340
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.16111 | val 0.18410
  Epoch 016 - train 0.15927 | val 0.19475
  Regression -> MSE: 0.000683, MAE: 0.019328, R²: 0.0020
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.17194 | val 0.27754
  Epoch 016 - train 0.17148 | val 0.28641
  Regression -> MSE: 0.000310, MAE: 0.014375, R²: 0.0017
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.14017 | val 0.19584
  Epoch 016 - train 0.13656 | val 0.18486
  Regression -> MSE: 0.000350, MAE: 0.014602, R²: -0.0029
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.16488 | val 0.17939
  Epoch 016 - train 0.16427 | val 0.18716
  Regression -> MSE: 0.000206, MAE: 0.010379, R²: -0.0122
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.16366 | val 0.32751
  Epoch 016 - train 0.15940 | val 0.33731
  Regression -> MSE: 0.000589, MAE: 0.018764, R²: -0.0616
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.17090 | val 0.21427
  Epoch 016 - train 0.17126 | val 0.21218
  Regression -> MSE: 0.000246, MAE: 0.011992, R²: -0.0004
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.17155 | val 0.24501
  Epoch 016 - train 0.15473 | val 0.25649
  Regression -> MSE: 0.000650, MAE: 0.020233, R²: -0.0878
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.16090 | val 0.21611
  Epoch 016 - train 0.16045 | val 0.21625
  Regression -> MSE: 0.000384, MAE: 0.016162, R²: -0.0013
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.15856 | val 0.23264
  Epoch 016 - train 0.15813 | val 0.25016
  Regression -> MSE: 0.000244, MAE: 0.012221, R²: -0.0090
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.16125 | val 0.24782
  Epoch 016 - train 0.15336 | val 0.24651
  Regression -> MSE: 0.000311, MAE: 0.013683, R²: -0.0009
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.6301

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.17406 | val 0.20081
  Epoch 016 - train 0.16937 | val 0.20223
  Regression -> MSE: 0.000684, MAE: 0.019535, R²: -0.0098
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.17194 | val 0.17158
  Epoch 016 - train 0.16593 | val 0.21045
  Regression -> MSE: 0.000144, MAE: 0.009496, R²: -0.0456
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.15396 | val 0.21938
  Epoch 016 - train 0.15512 | val 0.21798
  Regression -> MSE: 0.000225, MAE: 0.010694, R²: -0.0024
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.16083 | val 0.35446
  Epoch 016 - train 0.15355 | val 0.37509
  Regression -> MSE: 0.000372, MAE: 0.015940, R²: -0.0282
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.17521 | val 0.18018
  Epoch 016 - train 0.17421 | val 0.18244
  Regression -> MSE: 0.000109, MAE: 0.007957, R²: -0.0077
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.16527 | val 0.29013
  Epoch 016 - train 0.15818 | val 0.30524
  Regression -> MSE: 0.000157, MAE: 0.009546, R²: -0.0070
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.17011 | val 0.18234
  Epoch 016 - train 0.16803 | val 0.17769
  Regression -> MSE: 0.000273, MAE: 0.012969, R²: -0.0015
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.15036 | val 0.22227
  Epoch 016 - train 0.14953 | val 0.22172
  Regression -> MSE: 0.000160, MAE: 0.008927, R²: -0.0729
  Directional -> Accuracy: 0.4154, MCC: -0.0306, F1: 0.0500

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.16925 | val 0.24577
  Epoch 016 - train 0.17092 | val 0.24527
  Regression -> MSE: 0.000235, MAE: 0.010979, R²: -0.0399
  Directional -> Accuracy: 0.4800, MCC: 0.1507, F1: 0.0930

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.18162 | val 0.21658
  Epoch 016 - train 0.18025 | val 0.22638
  Regression -> MSE: 0.000152, MAE: 0.008804, R²: -0.0635
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.17378 | val 0.21661
  Epoch 016 - train 0.16868 | val 0.22173
  Regression -> MSE: 0.000165, MAE: 0.010483, R²: 0.0006
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.17680 | val 0.21178
  Epoch 016 - train 0.17821 | val 0.21656
  Regression -> MSE: 0.000089, MAE: 0.007240, R²: -0.0421
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.17121 | val 0.21081
  Epoch 016 - train 0.16723 | val 0.21462
  Regression -> MSE: 0.000213, MAE: 0.011079, R²: -0.0046
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.16763 | val 0.14981
  Epoch 016 - train 0.16198 | val 0.15226
  Regression -> MSE: 0.000102, MAE: 0.008260, R²: -0.1052
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.18254 | val 0.13620
  Epoch 016 - train 0.17020 | val 0.13699
  Regression -> MSE: 0.000111, MAE: 0.009065, R²: -0.0757
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.17688 | val 0.15936
  Epoch 016 - train 0.17132 | val 0.16137
  Regression -> MSE: 0.000235, MAE: 0.012682, R²: -0.0160
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.17753 | val 0.19687
  Epoch 016 - train 0.17071 | val 0.19629
  Regression -> MSE: 0.000185, MAE: 0.008058, R²: -0.1097
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.19130 | val 0.16727
  Epoch 016 - train 0.19786 | val 0.23418
  Regression -> MSE: 0.000240, MAE: 0.012034, R²: -0.0150
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.16070 | val 0.27196
  Epoch 020 - train 0.17045 | val 0.26422
  Regression -> MSE: 0.000233, MAE: 0.010022, R²: -0.0100
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.16745 | val 0.21125
  Epoch 020 - train 0.17379 | val 0.20937
  Regression -> MSE: 0.000136, MAE: 0.008198, R²: -0.0055
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.17449 | val 0.22020
  Epoch 016 - train 0.17068 | val 0.22497
  Regression -> MSE: 0.000189, MAE: 0.010392, R²: -0.0055
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.14824 | val 0.18193
  Epoch 020 - train 0.14881 | val 0.18123
  Regression -> MSE: 0.000283, MAE: 0.010962, R²: -0.0795
  Directional -> Accuracy: 0.4932, MCC: -0.0402, F1: 0.5647

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.16796 | val 0.14007
  Epoch 016 - train 0.16599 | val 0.14222
  Regression -> MSE: 0.000169, MAE: 0.010366, R²: -0.0135
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.15642 | val 0.17154
  Epoch 016 - train 0.15654 | val 0.17921
  Regression -> MSE: 0.000181, MAE: 0.010300, R²: -0.0068
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.15712 | val 0.15725
  Epoch 016 - train 0.15430 | val 0.15826
  Regression -> MSE: 0.000343, MAE: 0.011949, R²: 0.0000
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.18939 | val 0.10763
  Epoch 016 - train 0.18437 | val 0.11094
  Regression -> MSE: 0.000112, MAE: 0.008308, R²: -0.0666
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.16567 | val 0.24203
  Epoch 016 - train 0.17011 | val 0.26220
  Regression -> MSE: 0.000220, MAE: 0.011341, R²: -0.0065
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.16501 | val 0.28858
  Epoch 016 - train 0.16103 | val 0.29642
  Regression -> MSE: 0.000095, MAE: 0.007606, R²: -0.2230
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.17638 | val 0.12973
  Epoch 016 - train 0.16771 | val 0.12891
  Regression -> MSE: 0.000314, MAE: 0.014198, R²: -0.0217
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.17523 | val 0.09918
  Epoch 016 - train 0.17286 | val 0.09992
  Regression -> MSE: 0.000245, MAE: 0.011560, R²: -0.0067
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.0000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.16356 | val 0.20662
  Epoch 016 - train 0.16154 | val 0.20848
  Regression -> MSE: 0.000083, MAE: 0.007037, R²: -0.0289
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.16655 | val 0.21660
  Epoch 016 - train 0.16252 | val 0.20975
  Regression -> MSE: 0.000308, MAE: 0.014481, R²: -0.0050
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.16917 | val 0.18188
  Epoch 016 - train 0.16283 | val 0.18180
  Regression -> MSE: 0.000098, MAE: 0.007259, R²: -0.0012
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.17820 | val 0.20079
  Epoch 016 - train 0.17258 | val 0.20046
  Regression -> MSE: 0.000172, MAE: 0.009718, R²: 0.0005
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.16259 | val 0.20198
  Epoch 016 - train 0.15856 | val 0.20657
  Regression -> MSE: 0.000225, MAE: 0.011778, R²: -0.0077
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.15940 | val 0.19159
  Epoch 016 - train 0.15896 | val 0.19719
  Regression -> MSE: 0.000094, MAE: 0.007744, R²: -0.0182
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.17446 | val 0.26657
  Epoch 016 - train 0.17625 | val 0.26700
  Regression -> MSE: 0.000166, MAE: 0.010307, R²: -0.0138
  Directional -> Accuracy: 0.4815, MCC: 0.0000, F1: 0.0000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.16943 | val 0.21599
  Epoch 016 - train 0.16763 | val 0.22596
  Regression -> MSE: 0.000118, MAE: 0.008954, R²: -0.0153
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.17042 | val 0.27019

[I 2026-02-22 23:58:42,825] Trial 139 finished with value: -0.011465720459177809 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.30000000000000004, 'batch_size': 32, 'learning_rate': 9.645972791655072e-06, 'weight_decay': 5.045543399238563e-06, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 0.2650952074663746, 'early_stopping_min_delta': 0.007555793183801669}. Best is trial 90 with value: -0.011414558399902668.

  Epoch 016 - train 0.16718 | val 0.29395
  Regression -> MSE: 0.000237, MAE: 0.012431, R²: -0.0008
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.26756 | val 0.36061
  Epoch 020 - train 0.26685 | val 0.35636
  Regression -> MSE: 0.000277, MAE: 0.013429, R²: -0.1202
  Directional -> Accuracy: 0.4545, MCC: -0.0149, F1: 0.6182

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.24911 | val 0.23262
  Epoch 020 - train 0.24361 | val 0.28319
  Regression -> MSE: 0.000682, MAE: 0.019014, R²: 0.0042
  Directional -> Accuracy: 0.5870, MCC: 0.1202, F1: 0.6984

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.25803 | val 0.42940
  Epoch 020 - train 0.25479 | val 0.41682
  Regression -> MSE: 0.000334, MAE: 0.014722, R²: -0.0777
  Directional -> Accuracy: 0.5106, MCC: 0.0845, F1: 0.3030

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.22600 | val 0.33792
  Epoch 016 - train 0.22524 | val 0.31417
  Regression -> MSE: 0.000350, MAE: 0.014594, R²: -0.0028
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.28169 | val 0.27774
  Epoch 016 - train 0.27990 | val 0.29711
  Regression -> MSE: 0.000211, MAE: 0.010220, R²: -0.0338
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.25473 | val 0.51751
  Epoch 016 - train 0.25251 | val 0.53350
  Regression -> MSE: 0.000604, MAE: 0.019098, R²: -0.0881
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.26731 | val 0.31676
  Epoch 016 - train 0.26341 | val 0.31774
  Regression -> MSE: 0.000246, MAE: 0.011986, R²: -0.0019
  Directional -> Accuracy: 0.3913, MCC: -0.1105, F1: 0.5435

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.24505 | val 0.34082
  Epoch 016 - train 0.25619 | val 0.33325
  Regression -> MSE: 0.000626, MAE: 0.019816, R²: -0.0477
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.23595 | val 0.30105
  Epoch 016 - train 0.23769 | val 0.30403
  Regression -> MSE: 0.000400, MAE: 0.016056, R²: -0.0434
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.25266 | val 0.32352
  Epoch 016 - train 0.24012 | val 0.32440
  Regression -> MSE: 0.000242, MAE: 0.011981, R²: -0.0023
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.23241 | val 0.35965
  Epoch 016 - train 0.22384 | val 0.37781
  Regression -> MSE: 0.000320, MAE: 0.013586, R²: -0.0292
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.26206 | val 0.31284
  Epoch 016 - train 0.25986 | val 0.32446
  Regression -> MSE: 0.000680, MAE: 0.019579, R²: -0.0039
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.25034 | val 0.25084
  Epoch 016 - train 0.23430 | val 0.24883
  Regression -> MSE: 0.000140, MAE: 0.009306, R²: -0.0160
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.22914 | val 0.35569
  Epoch 016 - train 0.21651 | val 0.36105
  Regression -> MSE: 0.000225, MAE: 0.010708, R²: -0.0023
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.24378 | val 0.53539
  Epoch 020 - train 0.24304 | val 0.52991
  Regression -> MSE: 0.000380, MAE: 0.015648, R²: -0.0489
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.27528 | val 0.27346
  Epoch 016 - train 0.27172 | val 0.26995
  Regression -> MSE: 0.000111, MAE: 0.008222, R²: -0.0254
  Directional -> Accuracy: 0.4571, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.24380 | val 0.44408
  Epoch 016 - train 0.24889 | val 0.46254
  Regression -> MSE: 0.000161, MAE: 0.010154, R²: -0.0359
  Directional -> Accuracy: 0.3729, MCC: -0.1882, F1: 0.3509

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.24340 | val 0.26693
  Epoch 016 - train 0.24935 | val 0.26872
  Regression -> MSE: 0.000285, MAE: 0.013644, R²: -0.0482
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.23757 | val 0.33776
  Epoch 016 - train 0.22694 | val 0.33568
  Regression -> MSE: 0.000163, MAE: 0.008984, R²: -0.0888
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.25817 | val 0.37254
  Epoch 016 - train 0.25347 | val 0.37145
  Regression -> MSE: 0.000227, MAE: 0.010869, R²: -0.0034
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.26795 | val 0.32013
  Epoch 016 - train 0.26608 | val 0.32853
  Regression -> MSE: 0.000155, MAE: 0.008912, R²: -0.0828
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.23519 | val 0.30629
  Epoch 016 - train 0.24424 | val 0.30739
  Regression -> MSE: 0.000166, MAE: 0.010382, R²: -0.0017
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.26812 | val 0.31146
  Epoch 016 - train 0.25517 | val 0.31094
  Regression -> MSE: 0.000086, MAE: 0.007117, R²: -0.0137
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.26144 | val 0.38424
  Epoch 016 - train 0.25946 | val 0.37454
  Regression -> MSE: 0.000215, MAE: 0.011473, R²: -0.0157
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.23922 | val 0.21283
  Epoch 020 - train 0.23965 | val 0.20805
  Regression -> MSE: 0.000093, MAE: 0.008074, R²: -0.0051
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.25347 | val 0.20270
  Epoch 020 - train 0.25189 | val 0.18136
  Regression -> MSE: 0.000113, MAE: 0.008784, R²: -0.0973
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.26461 | val 0.24074
  Epoch 016 - train 0.27031 | val 0.25355
  Regression -> MSE: 0.000232, MAE: 0.012578, R²: -0.0041
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.24650 | val 0.28437
  Epoch 020 - train 0.25213 | val 0.28249
  Regression -> MSE: 0.000234, MAE: 0.009981, R²: -0.4033
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.24962 | val 0.22160
  Epoch 016 - train 0.26694 | val 0.22442
  Regression -> MSE: 0.000240, MAE: 0.012003, R²: -0.0130
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.24072 | val 0.43075
  Epoch 016 - train 0.24566 | val 0.43701
  Regression -> MSE: 0.000233, MAE: 0.010052, R²: -0.0112
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.26637 | val 0.29525
  Epoch 016 - train 0.26664 | val 0.29715
  Regression -> MSE: 0.000136, MAE: 0.008212, R²: -0.0043
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.24727 | val 0.33103
  Epoch 016 - train 0.24960 | val 0.33765
  Regression -> MSE: 0.000191, MAE: 0.010379, R²: -0.0157
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.21677 | val 0.37025
  Epoch 016 - train 0.22365 | val 0.36633
  Regression -> MSE: 0.000264, MAE: 0.010498, R²: -0.0081
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.23760 | val 0.21684
  Epoch 016 - train 0.23744 | val 0.21413
  Regression -> MSE: 0.000167, MAE: 0.010367, R²: -0.0022
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.22637 | val 0.26212
  Epoch 016 - train 0.23543 | val 0.27651
  Regression -> MSE: 0.000180, MAE: 0.010310, R²: -0.0017
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.24657 | val 0.23505
  Epoch 016 - train 0.23755 | val 0.23262
  Regression -> MSE: 0.000348, MAE: 0.011736, R²: -0.0161
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.25751 | val 0.15125
  Epoch 016 - train 0.27332 | val 0.15421
  Regression -> MSE: 0.000117, MAE: 0.008334, R²: -0.1112
  Directional -> Accuracy: 0.6047, MCC: 0.2082, F1: 0.6222

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.25955 | val 0.38504
  Epoch 016 - train 0.25296 | val 0.41348
  Regression -> MSE: 0.000220, MAE: 0.011342, R²: -0.0055
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.25094 | val 0.47701
  Epoch 016 - train 0.25033 | val 0.50860
  Regression -> MSE: 0.000083, MAE: 0.007105, R²: -0.0688
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.24892 | val 0.18011
  Epoch 016 - train 0.24553 | val 0.17808
  Regression -> MSE: 0.000310, MAE: 0.013930, R²: -0.0073
  Directional -> Accuracy: 0.6327, MCC: 0.0000, F1: 0.0000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.28812 | val 0.14284
  Epoch 016 - train 0.27680 | val 0.15175
  Regression -> MSE: 0.000246, MAE: 0.011579, R²: -0.0076
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.0000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.24472 | val 0.32119
  Epoch 016 - train 0.24151 | val 0.31623
  Regression -> MSE: 0.000081, MAE: 0.007100, R²: -0.0035
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.27181 | val 0.30961
  Epoch 020 - train 0.25421 | val 0.31059
  Regression -> MSE: 0.000317, MAE: 0.014563, R²: -0.0328
  Directional -> Accuracy: 0.4894, MCC: -0.0045, F1: 0.0769

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.27504 | val 0.30598
  Epoch 016 - train 0.26371 | val 0.30893
  Regression -> MSE: 0.000103, MAE: 0.007106, R²: -0.0525
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.27621 | val 0.31808
  Epoch 016 - train 0.27936 | val 0.32612
  Regression -> MSE: 0.000174, MAE: 0.009452, R²: -0.0101
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.23376 | val 0.28812
  Epoch 020 - train 0.22964 | val 0.29485
  Regression -> MSE: 0.000225, MAE: 0.011831, R²: -0.0088
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.23826 | val 0.31060
  Epoch 016 - train 0.23999 | val 0.33915
  Regression -> MSE: 0.000092, MAE: 0.007651, R²: 0.0011
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.27381 | val 0.40983
  Epoch 016 - train 0.27334 | val 0.41523
  Regression -> MSE: 0.000164, MAE: 0.010273, R²: -0.0021
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.24701 | val 0.35485
  Epoch 016 - train 0.24613 | val 0.39225
  Regression -> MSE: 0.000126, MAE: 0.009035, R²: -0.0878
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.25326 | val 0.38656

[I 2026-02-23 00:00:56,841] Trial 140 finished with value: -0.01148300515511672 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.30000000000000004, 'batch_size': 32, 'learning_rate': 8.550499681610988e-06, 'weight_decay': 4.929365172395854e-06, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 0.4448093915191127, 'early_stopping_min_delta': 0.007653295436927472}. Best is trial 90 with value: -0.011414558399902668.

  Epoch 016 - train 0.25440 | val 0.38964
  Regression -> MSE: 0.000238, MAE: 0.012374, R²: -0.0031
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.19781 | val 0.29887
  Epoch 016 - train 0.19388 | val 0.29824
  Regression -> MSE: 0.000251, MAE: 0.012701, R²: -0.0151
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.19685 | val 0.18349
  Epoch 016 - train 0.19995 | val 0.18424
  Regression -> MSE: 0.000697, MAE: 0.019549, R²: -0.0176
  Directional -> Accuracy: 0.6304, MCC: 0.3012, F1: 0.7536

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.20198 | val 0.32584
  Epoch 020 - train 0.19915 | val 0.31574
  Regression -> MSE: 0.000325, MAE: 0.014321, R²: -0.0479
  Directional -> Accuracy: 0.4894, MCC: 0.0471, F1: 0.2000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.16365 | val 0.20627
  Epoch 016 - train 0.16225 | val 0.22031
  Regression -> MSE: 0.000350, MAE: 0.014591, R²: -0.0017
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.20134 | val 0.19834
  Epoch 016 - train 0.20289 | val 0.19591
  Regression -> MSE: 0.000204, MAE: 0.010240, R²: -0.0039
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.18456 | val 0.37583
  Epoch 016 - train 0.19178 | val 0.37566
  Regression -> MSE: 0.000558, MAE: 0.018148, R²: -0.0048
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.20457 | val 0.25456
  Epoch 016 - train 0.20360 | val 0.25305
  Regression -> MSE: 0.000246, MAE: 0.011934, R²: -0.0036
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.21547 | val 0.24881
  Epoch 016 - train 0.20552 | val 0.24366
  Regression -> MSE: 0.000616, MAE: 0.019617, R²: -0.0311
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.18474 | val 0.24452
  Epoch 016 - train 0.18259 | val 0.24375
  Regression -> MSE: 0.000388, MAE: 0.015958, R²: -0.0111
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.20866 | val 0.26782
  Epoch 016 - train 0.20431 | val 0.27042
  Regression -> MSE: 0.000246, MAE: 0.011626, R²: -0.0207
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.18689 | val 0.31287
  Epoch 016 - train 0.19596 | val 0.33597
  Regression -> MSE: 0.000311, MAE: 0.013800, R²: -0.0001
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.6301

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.20892 | val 0.25725
  Epoch 016 - train 0.20358 | val 0.27419
  Regression -> MSE: 0.000682, MAE: 0.019534, R²: -0.0076
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.20155 | val 0.20649
  Epoch 016 - train 0.20193 | val 0.20918
  Regression -> MSE: 0.000138, MAE: 0.009070, R²: 0.0016
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.18529 | val 0.28163
  Epoch 016 - train 0.18405 | val 0.27401
  Regression -> MSE: 0.000227, MAE: 0.010920, R²: -0.0100
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.20010 | val 0.41602
  Epoch 016 - train 0.19714 | val 0.42330
  Regression -> MSE: 0.000366, MAE: 0.015951, R²: -0.0104
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.20945 | val 0.23192
  Epoch 016 - train 0.21126 | val 0.23448
  Regression -> MSE: 0.000108, MAE: 0.007959, R²: -0.0057
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.18910 | val 0.36721
  Epoch 016 - train 0.18546 | val 0.40141
  Regression -> MSE: 0.000158, MAE: 0.009910, R²: -0.0109
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.20569 | val 0.23365
  Epoch 016 - train 0.20150 | val 0.22796
  Regression -> MSE: 0.000273, MAE: 0.012975, R²: -0.0042
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.18254 | val 0.26538
  Epoch 016 - train 0.18167 | val 0.26493
  Regression -> MSE: 0.000166, MAE: 0.009094, R²: -0.1091
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.19817 | val 0.28660
  Epoch 016 - train 0.19360 | val 0.28430
  Regression -> MSE: 0.000240, MAE: 0.011103, R²: -0.0596
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.20486 | val 0.24716
  Epoch 016 - train 0.19471 | val 0.25349
  Regression -> MSE: 0.000152, MAE: 0.008763, R²: -0.0599
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.18588 | val 0.22959
  Epoch 016 - train 0.18228 | val 0.22996
  Regression -> MSE: 0.000177, MAE: 0.010278, R²: -0.0701
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.20357 | val 0.22998
  Epoch 020 - train 0.19981 | val 0.22654
  Regression -> MSE: 0.000082, MAE: 0.006901, R²: 0.0367
  Directional -> Accuracy: 0.6207, MCC: 0.2288, F1: 0.7442

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.20387 | val 0.25547
  Epoch 016 - train 0.19729 | val 0.26884
  Regression -> MSE: 0.000212, MAE: 0.011081, R²: -0.0014
  Directional -> Accuracy: 0.4697, MCC: -0.0343, F1: 0.5679

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.18652 | val 0.17068
  Epoch 020 - train 0.18321 | val 0.16642
  Regression -> MSE: 0.000098, MAE: 0.008003, R²: -0.0679
  Directional -> Accuracy: 0.5714, MCC: 0.2385, F1: 0.4545

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.20642 | val 0.15821
  Epoch 016 - train 0.20163 | val 0.16257
  Regression -> MSE: 0.000110, MAE: 0.009022, R²: -0.0644
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.22012 | val 0.21174
  Epoch 016 - train 0.22247 | val 0.22873
  Regression -> MSE: 0.000233, MAE: 0.012494, R²: -0.0053
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.19395 | val 0.25226
  Epoch 016 - train 0.19834 | val 0.26338
  Regression -> MSE: 0.000180, MAE: 0.007965, R²: -0.0803
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.19878 | val 0.16152
  Epoch 016 - train 0.19249 | val 0.16026
  Regression -> MSE: 0.000239, MAE: 0.011935, R²: -0.0104
  Directional -> Accuracy: 0.4878, MCC: -0.0050, F1: 0.4324

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.18733 | val 0.32538
  Epoch 020 - train 0.19206 | val 0.31398
  Regression -> MSE: 0.000223, MAE: 0.009876, R²: 0.0313
  Directional -> Accuracy: 0.5349, MCC: 0.2158, F1: 0.6774

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.19692 | val 0.24238
  Epoch 016 - train 0.20314 | val 0.23871
  Regression -> MSE: 0.000137, MAE: 0.008287, R²: -0.0171
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.18889 | val 0.26266
  Epoch 016 - train 0.19579 | val 0.27225
  Regression -> MSE: 0.000202, MAE: 0.010822, R²: -0.0744
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.17825 | val 0.22104
  Epoch 020 - train 0.17179 | val 0.22529
  Regression -> MSE: 0.000275, MAE: 0.010903, R²: -0.0497
  Directional -> Accuracy: 0.5068, MCC: 0.1226, F1: 0.3333

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.20400 | val 0.18106
  Epoch 016 - train 0.20902 | val 0.18847
  Regression -> MSE: 0.000169, MAE: 0.010365, R²: -0.0141
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.19788 | val 0.20253
  Epoch 016 - train 0.19148 | val 0.22686
  Regression -> MSE: 0.000183, MAE: 0.010396, R²: -0.0182
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.19115 | val 0.18235
  Epoch 016 - train 0.18183 | val 0.18024
  Regression -> MSE: 0.000351, MAE: 0.012437, R²: -0.0236
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.20702 | val 0.12206
  Epoch 016 - train 0.20540 | val 0.12280
  Regression -> MSE: 0.000122, MAE: 0.008403, R²: -0.1632
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.19858 | val 0.26700
  Epoch 016 - train 0.20314 | val 0.27035
  Regression -> MSE: 0.000220, MAE: 0.011342, R²: -0.0076
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.20905 | val 0.34453
  Epoch 016 - train 0.20642 | val 0.35153
  Regression -> MSE: 0.000094, MAE: 0.007578, R²: -0.2137
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.21229 | val 0.15556
  Epoch 016 - train 0.19980 | val 0.16228
  Regression -> MSE: 0.000322, MAE: 0.014640, R²: -0.0476
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.20699 | val 0.11297
  Epoch 016 - train 0.21006 | val 0.11241
  Regression -> MSE: 0.000249, MAE: 0.011524, R²: -0.0204
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.18955 | val 0.24371
  Epoch 016 - train 0.18641 | val 0.24470
  Regression -> MSE: 0.000081, MAE: 0.007108, R²: -0.0042
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.20705 | val 0.25019
  Epoch 016 - train 0.19329 | val 0.25115
  Regression -> MSE: 0.000307, MAE: 0.014472, R²: -0.0017
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.18942 | val 0.21091
  Epoch 016 - train 0.19859 | val 0.21063
  Regression -> MSE: 0.000098, MAE: 0.007281, R²: -0.0013
  Directional -> Accuracy: 0.5455, MCC: 0.0981, F1: 0.5652

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.21411 | val 0.24038
  Epoch 016 - train 0.20348 | val 0.24990
  Regression -> MSE: 0.000172, MAE: 0.009593, R²: 0.0004
  Directional -> Accuracy: 0.6327, MCC: 0.1814, F1: 0.1000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.18498 | val 0.25127
  Epoch 016 - train 0.17258 | val 0.25491
  Regression -> MSE: 0.000228, MAE: 0.011800, R²: -0.0203
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.20207 | val 0.21413
  Epoch 016 - train 0.20028 | val 0.21435
  Regression -> MSE: 0.000093, MAE: 0.007649, R²: -0.0040
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.21129 | val 0.30426
  Epoch 016 - train 0.20779 | val 0.30281
  Regression -> MSE: 0.000164, MAE: 0.010243, R²: 0.0002
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.19577 | val 0.25474
  Epoch 016 - train 0.19125 | val 0.26029
  Regression -> MSE: 0.000118, MAE: 0.008955, R²: -0.0149
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.19622 | val 0.33552

[I 2026-02-23 00:03:08,489] Trial 141 finished with value: -0.011428648201245445 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.30000000000000004, 'batch_size': 32, 'learning_rate': 4.212584413150942e-06, 'weight_decay': 6.2863550497526815e-06, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 0.3203851700463535, 'early_stopping_min_delta': 0.0075206068245579905}. Best is trial 90 with value: -0.011414558399902668.

  Epoch 016 - train 0.19391 | val 0.40430
  Regression -> MSE: 0.000239, MAE: 0.012314, R²: -0.0090
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.17560 | val 0.24081
  Epoch 016 - train 0.17290 | val 0.24172
  Regression -> MSE: 0.000249, MAE: 0.012622, R²: -0.0076
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.16306 | val 0.15895
  Epoch 016 - train 0.16848 | val 0.17854
  Regression -> MSE: 0.000686, MAE: 0.019359, R²: -0.0014
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.17447 | val 0.27896
  Epoch 020 - train 0.17279 | val 0.27437
  Regression -> MSE: 0.000316, MAE: 0.014405, R²: -0.0183
  Directional -> Accuracy: 0.5106, MCC: -0.0150, F1: 0.6230

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.15113 | val 0.19000
  Epoch 016 - train 0.14370 | val 0.20811
  Regression -> MSE: 0.000355, MAE: 0.014686, R²: -0.0170
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.17158 | val 0.16789
  Epoch 016 - train 0.17196 | val 0.16777
  Regression -> MSE: 0.000209, MAE: 0.010147, R²: -0.0251
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.16742 | val 0.32331
  Epoch 016 - train 0.16393 | val 0.32573
  Regression -> MSE: 0.000568, MAE: 0.018329, R²: -0.0240
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.17691 | val 0.22205
  Epoch 016 - train 0.17563 | val 0.21788
  Regression -> MSE: 0.000247, MAE: 0.011954, R²: -0.0083
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.17316 | val 0.22946
  Epoch 016 - train 0.16223 | val 0.24228
  Regression -> MSE: 0.000624, MAE: 0.019755, R²: -0.0437
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.17257 | val 0.22378
  Epoch 016 - train 0.16865 | val 0.24119
  Regression -> MSE: 0.000384, MAE: 0.016096, R²: -0.0018
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.17998 | val 0.22302
  Epoch 016 - train 0.17682 | val 0.22476
  Regression -> MSE: 0.000241, MAE: 0.011816, R²: -0.0002
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.16181 | val 0.24556
  Epoch 016 - train 0.15535 | val 0.24401
  Regression -> MSE: 0.000314, MAE: 0.013614, R²: -0.0101
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.17671 | val 0.20910
  Epoch 016 - train 0.17037 | val 0.21034
  Regression -> MSE: 0.000677, MAE: 0.019460, R²: -0.0002
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.17582 | val 0.16563
  Epoch 020 - train 0.16967 | val 0.17308
  Regression -> MSE: 0.000152, MAE: 0.009693, R²: -0.1018
  Directional -> Accuracy: 0.4419, MCC: -0.0259, F1: 0.6000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.15693 | val 0.21196
  Epoch 020 - train 0.16047 | val 0.20692
  Regression -> MSE: 0.000251, MAE: 0.011468, R²: -0.1140
  Directional -> Accuracy: 0.4426, MCC: -0.1455, F1: 0.1500

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.16242 | val 0.35456
  Epoch 016 - train 0.16148 | val 0.36432
  Regression -> MSE: 0.000373, MAE: 0.015925, R²: -0.0304
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.18297 | val 0.17356
  Epoch 016 - train 0.17853 | val 0.17505
  Regression -> MSE: 0.000111, MAE: 0.007959, R²: -0.0269
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.16829 | val 0.32186
  Epoch 016 - train 0.16118 | val 0.35021
  Regression -> MSE: 0.000156, MAE: 0.009714, R²: -0.0020
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.17393 | val 0.19263
  Epoch 016 - train 0.17347 | val 0.19977
  Regression -> MSE: 0.000290, MAE: 0.013809, R²: -0.0647
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.15715 | val 0.22854
  Epoch 020 - train 0.15646 | val 0.22619
  Regression -> MSE: 0.000167, MAE: 0.009733, R²: -0.1185
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.18845 | val 0.28783
  Epoch 016 - train 0.18524 | val 0.27709
  Regression -> MSE: 0.000227, MAE: 0.010964, R²: -0.0018
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.17630 | val 0.21210
  Epoch 016 - train 0.17745 | val 0.21165
  Regression -> MSE: 0.000144, MAE: 0.008412, R²: -0.0062
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.16902 | val 0.20849
  Epoch 016 - train 0.16744 | val 0.20835
  Regression -> MSE: 0.000176, MAE: 0.010279, R²: -0.0649
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.18126 | val 0.19984
  Epoch 016 - train 0.17645 | val 0.20110
  Regression -> MSE: 0.000090, MAE: 0.007331, R²: -0.0613
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.20036 | val 0.24486
  Epoch 016 - train 0.19237 | val 0.25244
  Regression -> MSE: 0.000217, MAE: 0.011034, R²: -0.0253
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.16345 | val 0.15872
  Epoch 016 - train 0.16057 | val 0.15981
  Regression -> MSE: 0.000101, MAE: 0.008249, R²: -0.1018
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.17221 | val 0.13341
  Epoch 016 - train 0.17595 | val 0.13880
  Regression -> MSE: 0.000105, MAE: 0.008823, R²: -0.0141
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.17959 | val 0.16759
  Epoch 016 - train 0.17348 | val 0.17045
  Regression -> MSE: 0.000237, MAE: 0.012754, R²: -0.0243
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.17574 | val 0.20972
  Epoch 016 - train 0.16922 | val 0.21164
  Regression -> MSE: 0.000177, MAE: 0.007900, R²: -0.0663
  Directional -> Accuracy: 0.5614, MCC: 0.2530, F1: 0.4186

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.17331 | val 0.14328
  Epoch 016 - train 0.18312 | val 0.15346
  Regression -> MSE: 0.000237, MAE: 0.011859, R²: -0.0007
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.17378 | val 0.28674
  Epoch 016 - train 0.17344 | val 0.29469
  Regression -> MSE: 0.000234, MAE: 0.010140, R²: -0.0161
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.17407 | val 0.20950
  Epoch 016 - train 0.17869 | val 0.21469
  Regression -> MSE: 0.000136, MAE: 0.008248, R²: -0.0059
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.16636 | val 0.22042
  Epoch 016 - train 0.18077 | val 0.22278
  Regression -> MSE: 0.000194, MAE: 0.010492, R²: -0.0308
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.15187 | val 0.19428
  Epoch 016 - train 0.15247 | val 0.19410
  Regression -> MSE: 0.000278, MAE: 0.010883, R²: -0.0619
  Directional -> Accuracy: 0.4384, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.16494 | val 0.14300
  Epoch 016 - train 0.16367 | val 0.14338
  Regression -> MSE: 0.000168, MAE: 0.010369, R²: -0.0084
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.15861 | val 0.18105
  Epoch 016 - train 0.15631 | val 0.20025
  Regression -> MSE: 0.000181, MAE: 0.010289, R²: -0.0053
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.16970 | val 0.15374
  Epoch 020 - train 0.16571 | val 0.15306
  Regression -> MSE: 0.000345, MAE: 0.012024, R²: -0.0075
  Directional -> Accuracy: 0.4328, MCC: -0.0884, F1: 0.3448

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.18906 | val 0.11109
  Epoch 016 - train 0.18790 | val 0.11261
  Regression -> MSE: 0.000113, MAE: 0.008339, R²: -0.0756
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.18012 | val 0.23939
  Epoch 016 - train 0.17883 | val 0.23958
  Regression -> MSE: 0.000220, MAE: 0.011361, R²: -0.0087
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.17132 | val 0.30277
  Epoch 016 - train 0.17146 | val 0.32287
  Regression -> MSE: 0.000089, MAE: 0.007389, R²: -0.1481
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.17542 | val 0.13375
  Epoch 016 - train 0.18222 | val 0.13218
  Regression -> MSE: 0.000318, MAE: 0.014398, R²: -0.0339
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.18559 | val 0.10216
  Epoch 016 - train 0.18772 | val 0.10055
  Regression -> MSE: 0.000252, MAE: 0.011478, R²: -0.0355
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.16347 | val 0.21264
  Epoch 016 - train 0.16244 | val 0.21160
  Regression -> MSE: 0.000082, MAE: 0.007062, R²: -0.0116
  Directional -> Accuracy: 0.4800, MCC: -0.1155, F1: 0.0488

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.16889 | val 0.21110
  Epoch 016 - train 0.17540 | val 0.21518
  Regression -> MSE: 0.000307, MAE: 0.014506, R²: -0.0015
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.16007 | val 0.19321
  Epoch 016 - train 0.17619 | val 0.19077
  Regression -> MSE: 0.000099, MAE: 0.007142, R²: -0.0114
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.18976 | val 0.20825
  Epoch 016 - train 0.18309 | val 0.21449
  Regression -> MSE: 0.000172, MAE: 0.009850, R²: -0.0036
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.16538 | val 0.20761
  Epoch 016 - train 0.16555 | val 0.21080
  Regression -> MSE: 0.000223, MAE: 0.011774, R²: 0.0003
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.17837 | val 0.19362
  Epoch 016 - train 0.17219 | val 0.19617
  Regression -> MSE: 0.000093, MAE: 0.007700, R²: -0.0109
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.18353 | val 0.26776
  Epoch 016 - train 0.18011 | val 0.27112
  Regression -> MSE: 0.000164, MAE: 0.010251, R²: -0.0004
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.16954 | val 0.21597
  Epoch 016 - train 0.17129 | val 0.21780
  Regression -> MSE: 0.000120, MAE: 0.008980, R²: -0.0351
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.17092 | val 0.29495

[I 2026-02-23 00:05:19,899] Trial 142 finished with value: -0.011463755352822147 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.30000000000000004, 'batch_size': 32, 'learning_rate': 4.371074013493719e-06, 'weight_decay': 6.384443344176078e-06, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 0.27199782558260477, 'early_stopping_min_delta': 0.0072206285944179365}. Best is trial 90 with value: -0.011414558399902668.

  Epoch 016 - train 0.16816 | val 0.33784
  Regression -> MSE: 0.000237, MAE: 0.012363, R²: -0.0004
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.16455 | val 0.21713
  Epoch 016 - train 0.16723 | val 0.21802
  Regression -> MSE: 0.000250, MAE: 0.012647, R²: -0.0103
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.15916 | val 0.15760
  Epoch 016 - train 0.15976 | val 0.16704
  Regression -> MSE: 0.000697, MAE: 0.019553, R²: -0.0177
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.16935 | val 0.27967
  Epoch 016 - train 0.17020 | val 0.29194
  Regression -> MSE: 0.000311, MAE: 0.014411, R²: -0.0022
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.13980 | val 0.13510
  Epoch 016 - train 0.13363 | val 0.13774
  Regression -> MSE: 0.000351, MAE: 0.014579, R²: -0.0060
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.16365 | val 0.16580
  Epoch 016 - train 0.16821 | val 0.15856
  Regression -> MSE: 0.000205, MAE: 0.010134, R²: -0.0081
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.16453 | val 0.31111
  Epoch 016 - train 0.15769 | val 0.31259
  Regression -> MSE: 0.000560, MAE: 0.018164, R²: -0.0080
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.16914 | val 0.20411
  Epoch 016 - train 0.17231 | val 0.20297
  Regression -> MSE: 0.000247, MAE: 0.011922, R²: -0.0078
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.17803 | val 0.18768
  Epoch 020 - train 0.17817 | val 0.16999
  Regression -> MSE: 0.000628, MAE: 0.019431, R²: -0.0517
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.15594 | val 0.20062
  Epoch 016 - train 0.15207 | val 0.20894
  Regression -> MSE: 0.000393, MAE: 0.015934, R²: -0.0243
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.17102 | val 0.21401
  Epoch 016 - train 0.16561 | val 0.21525
  Regression -> MSE: 0.000244, MAE: 0.011656, R²: -0.0118
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.15275 | val 0.24089
  Epoch 016 - train 0.15189 | val 0.25199
  Regression -> MSE: 0.000316, MAE: 0.013596, R²: -0.0178
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.16961 | val 0.19989
  Epoch 016 - train 0.16958 | val 0.21063
  Regression -> MSE: 0.000679, MAE: 0.019496, R²: -0.0018
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.16734 | val 0.18889
  Epoch 016 - train 0.16744 | val 0.20932
  Regression -> MSE: 0.000138, MAE: 0.009076, R²: -0.0010
  Directional -> Accuracy: 0.6047, MCC: 0.2482, F1: 0.1905

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.14908 | val 0.20987
  Epoch 016 - train 0.14583 | val 0.21010
  Regression -> MSE: 0.000230, MAE: 0.010848, R²: -0.0211
  Directional -> Accuracy: 0.4918, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.16428 | val 0.33819
  Epoch 016 - train 0.15906 | val 0.34148
  Regression -> MSE: 0.000367, MAE: 0.015951, R²: -0.0147
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.17184 | val 0.17544
  Epoch 016 - train 0.17307 | val 0.17655
  Regression -> MSE: 0.000108, MAE: 0.007976, R²: -0.0039
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.16012 | val 0.29083
  Epoch 016 - train 0.16235 | val 0.30251
  Regression -> MSE: 0.000156, MAE: 0.009689, R²: -0.0001
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.16705 | val 0.16917
  Epoch 016 - train 0.16575 | val 0.17495
  Regression -> MSE: 0.000273, MAE: 0.013095, R²: -0.0043
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.14714 | val 0.22695
  Epoch 016 - train 0.14772 | val 0.22651
  Regression -> MSE: 0.000170, MAE: 0.009230, R²: -0.1390
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.16880 | val 0.23135
  Epoch 016 - train 0.16661 | val 0.23168
  Regression -> MSE: 0.000227, MAE: 0.010884, R²: -0.0035
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.16509 | val 0.22296
  Epoch 016 - train 0.16185 | val 0.26073
  Regression -> MSE: 0.000150, MAE: 0.008676, R²: -0.0434
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.15580 | val 0.19228
  Epoch 016 - train 0.15392 | val 0.19363
  Regression -> MSE: 0.000182, MAE: 0.010334, R²: -0.0989
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.17441 | val 0.19778
  Epoch 016 - train 0.18007 | val 0.19589
  Regression -> MSE: 0.000094, MAE: 0.007479, R²: -0.1007
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.16056 | val 0.28033
  Epoch 016 - train 0.16242 | val 0.30295
  Regression -> MSE: 0.000213, MAE: 0.011055, R²: -0.0040
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.15107 | val 0.14989
  Epoch 016 - train 0.15279 | val 0.14748
  Regression -> MSE: 0.000101, MAE: 0.008253, R²: -0.1010
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.18176 | val 0.12615
  Epoch 016 - train 0.18119 | val 0.12624
  Regression -> MSE: 0.000103, MAE: 0.008720, R²: -0.0032
  Directional -> Accuracy: 0.5217, MCC: 0.0156, F1: 0.4211

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.17899 | val 0.15974
  Epoch 016 - train 0.17110 | val 0.16690
  Regression -> MSE: 0.000232, MAE: 0.012585, R²: -0.0042
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.16420 | val 0.20692
  Epoch 016 - train 0.16459 | val 0.21148
  Regression -> MSE: 0.000172, MAE: 0.007838, R²: -0.0321
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.18274 | val 0.14655
  Epoch 016 - train 0.17529 | val 0.15064
  Regression -> MSE: 0.000239, MAE: 0.011948, R²: -0.0089
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.16825 | val 0.27057
  Epoch 016 - train 0.15792 | val 0.27349
  Regression -> MSE: 0.000234, MAE: 0.010107, R²: -0.0158
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.17768 | val 0.21444
  Epoch 020 - train 0.17499 | val 0.19970
  Regression -> MSE: 0.000127, MAE: 0.008227, R²: 0.0591
  Directional -> Accuracy: 0.5581, MCC: 0.0933, F1: 0.6667

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.15753 | val 0.21270
  Epoch 016 - train 0.16324 | val 0.21945
  Regression -> MSE: 0.000190, MAE: 0.010377, R²: -0.0098
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.14402 | val 0.18718
  Epoch 016 - train 0.14444 | val 0.18736
  Regression -> MSE: 0.000275, MAE: 0.010763, R²: -0.0496
  Directional -> Accuracy: 0.4384, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.15540 | val 0.14234
  Epoch 016 - train 0.14824 | val 0.14106
  Regression -> MSE: 0.000167, MAE: 0.010366, R²: 0.0004
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.14615 | val 0.17036
  Epoch 020 - train 0.14867 | val 0.16709
  Regression -> MSE: 0.000172, MAE: 0.010133, R²: 0.0457
  Directional -> Accuracy: 0.4545, MCC: -0.0795, F1: 0.5714

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.15679 | val 0.15683
  Epoch 016 - train 0.15726 | val 0.15730
  Regression -> MSE: 0.000347, MAE: 0.011746, R²: -0.0139
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.17594 | val 0.10887
  Epoch 016 - train 0.18451 | val 0.11808
  Regression -> MSE: 0.000128, MAE: 0.008538, R²: -0.2218
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.17389 | val 0.23741
  Epoch 016 - train 0.16734 | val 0.26422
  Regression -> MSE: 0.000221, MAE: 0.011357, R²: -0.0092
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.17242 | val 0.29285
  Epoch 016 - train 0.17757 | val 0.32078
  Regression -> MSE: 0.000088, MAE: 0.007356, R²: -0.1371
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.16558 | val 0.12342
  Epoch 016 - train 0.15257 | val 0.12486
  Regression -> MSE: 0.000310, MAE: 0.013929, R²: -0.0086
  Directional -> Accuracy: 0.6327, MCC: 0.0000, F1: 0.0000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.16694 | val 0.09923
  Epoch 016 - train 0.17033 | val 0.10083
  Regression -> MSE: 0.000250, MAE: 0.011498, R²: -0.0258
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.15261 | val 0.18820
  Epoch 020 - train 0.15443 | val 0.18635
  Regression -> MSE: 0.000086, MAE: 0.007434, R²: -0.0697
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.16904 | val 0.21134
  Epoch 020 - train 0.16067 | val 0.20827
  Regression -> MSE: 0.000302, MAE: 0.014470, R²: 0.0148
  Directional -> Accuracy: 0.4894, MCC: -0.1443, F1: 0.6571

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.16700 | val 0.17436
  Epoch 016 - train 0.16199 | val 0.17542
  Regression -> MSE: 0.000098, MAE: 0.007335, R²: -0.0018
  Directional -> Accuracy: 0.4318, MCC: 0.0000, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.18050 | val 0.19525
  Epoch 016 - train 0.16863 | val 0.19529
  Regression -> MSE: 0.000173, MAE: 0.009941, R²: -0.0070
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.15577 | val 0.21154
  Epoch 016 - train 0.15215 | val 0.24441
  Regression -> MSE: 0.000226, MAE: 0.011808, R²: -0.0137
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.15826 | val 0.18432
  Epoch 016 - train 0.15966 | val 0.18860
  Regression -> MSE: 0.000093, MAE: 0.007666, R²: -0.0047
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.17894 | val 0.25814
  Epoch 016 - train 0.17276 | val 0.25742
  Regression -> MSE: 0.000167, MAE: 0.010317, R²: -0.0197
  Directional -> Accuracy: 0.4815, MCC: 0.0000, F1: 0.0000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.16088 | val 0.22821
  Epoch 016 - train 0.15676 | val 0.23888
  Regression -> MSE: 0.000120, MAE: 0.008979, R²: -0.0337
  Directional -> Accuracy: 0.4464, MCC: -0.1995, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.16813 | val 0.24157

[I 2026-02-23 00:07:30,320] Trial 143 finished with value: -0.011397192428235973 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.30000000000000004, 'batch_size': 32, 'learning_rate': 6.306341269633193e-06, 'weight_decay': 7.1658745115180986e-06, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 0.25826966042862093, 'early_stopping_min_delta': 0.007263284657932136}. Best is trial 143 with value: -0.011397192428235973.

  Epoch 016 - train 0.17479 | val 0.25857
  Regression -> MSE: 0.000244, MAE: 0.012353, R²: -0.0288
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.15935 | val 0.21303
  Epoch 016 - train 0.15898 | val 0.21278
  Regression -> MSE: 0.000250, MAE: 0.012657, R²: -0.0105
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.16125 | val 0.16021
  Epoch 016 - train 0.16086 | val 0.18162
  Regression -> MSE: 0.000700, MAE: 0.019629, R²: -0.0226
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.16798 | val 0.26085
  Epoch 020 - train 0.16758 | val 0.26399
  Regression -> MSE: 0.000296, MAE: 0.013752, R²: 0.0470
  Directional -> Accuracy: 0.6596, MCC: 0.3138, F1: 0.6923

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.14608 | val 0.17325
  Epoch 016 - train 0.13558 | val 0.16814
  Regression -> MSE: 0.000351, MAE: 0.014619, R²: -0.0044
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.16554 | val 0.17298
  Epoch 016 - train 0.16638 | val 0.18972
  Regression -> MSE: 0.000204, MAE: 0.010223, R²: -0.0026
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.15229 | val 0.31266
  Epoch 016 - train 0.15302 | val 0.32122
  Regression -> MSE: 0.000588, MAE: 0.018725, R²: -0.0586
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.16267 | val 0.19672
  Epoch 016 - train 0.16240 | val 0.19611
  Regression -> MSE: 0.000246, MAE: 0.011954, R²: -0.0005
  Directional -> Accuracy: 0.4638, MCC: -0.0383, F1: 0.4638

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.16994 | val 0.19370
  Epoch 020 - train 0.18042 | val 0.18228
  Regression -> MSE: 0.000604, MAE: 0.019239, R²: -0.0105
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.16595 | val 0.18814
  Epoch 016 - train 0.16576 | val 0.18727
  Regression -> MSE: 0.000410, MAE: 0.016247, R²: -0.0701
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.17315 | val 0.21054
  Epoch 016 - train 0.17370 | val 0.21033
  Regression -> MSE: 0.000244, MAE: 0.012207, R²: -0.0087
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.14852 | val 0.24527
  Epoch 016 - train 0.14743 | val 0.25325
  Regression -> MSE: 0.000311, MAE: 0.013746, R²: 0.0012
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.6301

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.16614 | val 0.18928
  Epoch 016 - train 0.16795 | val 0.19031
  Regression -> MSE: 0.000682, MAE: 0.019562, R²: -0.0076
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.15691 | val 0.16177
  Epoch 016 - train 0.16021 | val 0.18547
  Regression -> MSE: 0.000145, MAE: 0.009515, R²: -0.0500
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.15159 | val 0.20679
  Epoch 016 - train 0.14927 | val 0.20503
  Regression -> MSE: 0.000226, MAE: 0.010711, R²: -0.0042
  Directional -> Accuracy: 0.4918, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.15896 | val 0.33144
  Epoch 016 - train 0.15711 | val 0.33988
  Regression -> MSE: 0.000365, MAE: 0.015987, R²: -0.0066
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.16675 | val 0.16139
  Epoch 020 - train 0.16895 | val 0.16152
  Regression -> MSE: 0.000106, MAE: 0.008031, R²: 0.0155
  Directional -> Accuracy: 0.4857, MCC: 0.0091, F1: 0.3793

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.16692 | val 0.26716
  Epoch 016 - train 0.15834 | val 0.26733
  Regression -> MSE: 0.000157, MAE: 0.009856, R²: -0.0072
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.16755 | val 0.16824
  Epoch 016 - train 0.16485 | val 0.16791
  Regression -> MSE: 0.000273, MAE: 0.012942, R²: -0.0021
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.15140 | val 0.22529
  Epoch 016 - train 0.15256 | val 0.22749
  Regression -> MSE: 0.000171, MAE: 0.009219, R²: -0.1408
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.17730 | val 0.25836
  Epoch 016 - train 0.17744 | val 0.25851
  Regression -> MSE: 0.000242, MAE: 0.011103, R²: -0.0680
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.16726 | val 0.19956
  Epoch 016 - train 0.16468 | val 0.20134
  Regression -> MSE: 0.000144, MAE: 0.008399, R²: -0.0065
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.15186 | val 0.18801
  Epoch 016 - train 0.15141 | val 0.18731
  Regression -> MSE: 0.000176, MAE: 0.010304, R²: -0.0659
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.16626 | val 0.18663
  Epoch 016 - train 0.16889 | val 0.18673
  Regression -> MSE: 0.000086, MAE: 0.007085, R²: -0.0082
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.17164 | val 0.22795
  Epoch 016 - train 0.16878 | val 0.23646
  Regression -> MSE: 0.000213, MAE: 0.011064, R²: -0.0060
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.14997 | val 0.14478
  Epoch 016 - train 0.14235 | val 0.14361
  Regression -> MSE: 0.000093, MAE: 0.008101, R²: -0.0154
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.17354 | val 0.13989
  Epoch 016 - train 0.17488 | val 0.14913
  Regression -> MSE: 0.000119, MAE: 0.009295, R²: -0.1498
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.16739 | val 0.15243
  Epoch 016 - train 0.16936 | val 0.15201
  Regression -> MSE: 0.000237, MAE: 0.012756, R²: -0.0242
  Directional -> Accuracy: 0.4186, MCC: -0.0789, F1: 0.2424

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.15773 | val 0.19051
  Epoch 016 - train 0.15388 | val 0.19151
  Regression -> MSE: 0.000176, MAE: 0.007878, R²: -0.0561
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.16688 | val 0.13816
  Epoch 016 - train 0.15993 | val 0.13780
  Regression -> MSE: 0.000237, MAE: 0.011867, R²: -0.0007
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.16648 | val 0.26458
  Epoch 016 - train 0.16414 | val 0.26936
  Regression -> MSE: 0.000234, MAE: 0.010087, R²: -0.0133
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.16640 | val 0.18592
  Epoch 016 - train 0.16406 | val 0.18910
  Regression -> MSE: 0.000135, MAE: 0.008175, R²: 0.0012
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.16165 | val 0.20598
  Epoch 016 - train 0.16210 | val 0.21102
  Regression -> MSE: 0.000190, MAE: 0.010385, R²: -0.0096
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.14936 | val 0.20066
  Epoch 016 - train 0.14937 | val 0.19981
  Regression -> MSE: 0.000262, MAE: 0.010507, R²: 0.0005
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.16376 | val 0.14840
  Epoch 016 - train 0.16140 | val 0.14661
  Regression -> MSE: 0.000170, MAE: 0.010385, R²: -0.0211
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.14299 | val 0.17265
  Epoch 016 - train 0.14847 | val 0.17609
  Regression -> MSE: 0.000182, MAE: 0.010393, R²: -0.0096
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.16717 | val 0.15103
  Epoch 016 - train 0.16549 | val 0.15176
  Regression -> MSE: 0.000348, MAE: 0.012250, R²: -0.0144
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.16941 | val 0.10387
  Epoch 016 - train 0.17342 | val 0.10603
  Regression -> MSE: 0.000113, MAE: 0.008297, R²: -0.0775
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.17056 | val 0.22151
  Epoch 016 - train 0.17301 | val 0.22233
  Regression -> MSE: 0.000219, MAE: 0.011325, R²: -0.0021
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.15611 | val 0.28225
  Epoch 016 - train 0.15837 | val 0.29715
  Regression -> MSE: 0.000094, MAE: 0.007559, R²: -0.2059
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.15422 | val 0.12817
  Epoch 016 - train 0.15867 | val 0.12800
  Regression -> MSE: 0.000323, MAE: 0.014671, R²: -0.0502
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.17237 | val 0.10506
  Epoch 016 - train 0.17824 | val 0.10686
  Regression -> MSE: 0.000260, MAE: 0.011493, R²: -0.0673
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.15903 | val 0.19841
  Epoch 016 - train 0.15431 | val 0.19999
  Regression -> MSE: 0.000081, MAE: 0.007072, R²: -0.0026
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.17127 | val 0.19841
  Epoch 016 - train 0.17074 | val 0.19957
  Regression -> MSE: 0.000309, MAE: 0.014517, R²: -0.0072
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.15681 | val 0.17646
  Epoch 016 - train 0.16049 | val 0.17643
  Regression -> MSE: 0.000098, MAE: 0.007230, R²: -0.0021
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.18623 | val 0.19059
  Epoch 016 - train 0.17073 | val 0.18923
  Regression -> MSE: 0.000172, MAE: 0.009606, R²: 0.0002
  Directional -> Accuracy: 0.4898, MCC: -0.2382, F1: 0.0741

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.15143 | val 0.18315
  Epoch 016 - train 0.14901 | val 0.18521
  Regression -> MSE: 0.000227, MAE: 0.011866, R²: -0.0195
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.17287 | val 0.21380
  Epoch 016 - train 0.17498 | val 0.23445
  Regression -> MSE: 0.000093, MAE: 0.007662, R²: -0.0031
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.17754 | val 0.25074
  Epoch 016 - train 0.17913 | val 0.25773
  Regression -> MSE: 0.000165, MAE: 0.010313, R²: -0.0059
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.15563 | val 0.19749
  Epoch 016 - train 0.15436 | val 0.19786
  Regression -> MSE: 0.000117, MAE: 0.008950, R²: -0.0124
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.16894 | val 0.22153

[I 2026-02-23 00:09:37,310] Trial 144 finished with value: -0.01143651063351737 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.30000000000000004, 'batch_size': 32, 'learning_rate': 4.252606844866232e-06, 'weight_decay': 9.473329262712777e-06, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 0.2518098408188221, 'early_stopping_min_delta': 0.006979744009230752}. Best is trial 143 with value: -0.011397192428235973.

  Epoch 016 - train 0.16136 | val 0.22239
  Regression -> MSE: 0.000247, MAE: 0.012406, R²: -0.0396
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.16040 | val 0.21688
  Epoch 016 - train 0.16600 | val 0.21701
  Regression -> MSE: 0.000252, MAE: 0.012712, R²: -0.0163
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.16758 | val 0.15474
  Epoch 016 - train 0.16508 | val 0.16090
  Regression -> MSE: 0.000704, MAE: 0.019675, R²: -0.0278
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.16990 | val 0.27391
  Epoch 016 - train 0.16647 | val 0.27144
  Regression -> MSE: 0.000320, MAE: 0.014520, R²: -0.0313
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.14060 | val 0.14336
  Epoch 016 - train 0.13571 | val 0.14422
  Regression -> MSE: 0.000356, MAE: 0.014690, R²: -0.0184
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.18239 | val 0.18427
  Epoch 016 - train 0.17964 | val 0.18942
  Regression -> MSE: 0.000206, MAE: 0.010363, R²: -0.0103
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.18109 | val 0.33842
  Epoch 016 - train 0.17850 | val 0.39005
  Regression -> MSE: 0.000613, MAE: 0.019288, R²: -0.1046
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.17034 | val 0.21825
  Epoch 016 - train 0.17010 | val 0.21818
  Regression -> MSE: 0.000248, MAE: 0.011960, R²: -0.0118
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.15661 | val 0.23063
  Epoch 016 - train 0.15943 | val 0.23789
  Regression -> MSE: 0.000639, MAE: 0.020069, R²: -0.0702
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.15946 | val 0.20910
  Epoch 016 - train 0.15920 | val 0.21035
  Regression -> MSE: 0.000385, MAE: 0.016073, R²: -0.0046
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.16175 | val 0.21672
  Epoch 016 - train 0.16231 | val 0.22109
  Regression -> MSE: 0.000243, MAE: 0.012129, R²: -0.0047
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.15469 | val 0.24625
  Epoch 016 - train 0.15326 | val 0.27418
  Regression -> MSE: 0.000315, MAE: 0.013598, R²: -0.0143
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.16958 | val 0.20184
  Epoch 016 - train 0.16592 | val 0.20294
  Regression -> MSE: 0.000682, MAE: 0.019535, R²: -0.0074
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.17385 | val 0.19874
  Epoch 016 - train 0.17054 | val 0.26176
  Regression -> MSE: 0.000138, MAE: 0.009040, R²: 0.0004
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.16077 | val 0.20629
  Epoch 016 - train 0.15353 | val 0.20803
  Regression -> MSE: 0.000228, MAE: 0.010780, R²: -0.0134
  Directional -> Accuracy: 0.4918, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.16545 | val 0.34675
  Epoch 016 - train 0.15944 | val 0.36166
  Regression -> MSE: 0.000367, MAE: 0.015955, R²: -0.0135
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.17989 | val 0.17503
  Epoch 016 - train 0.18061 | val 0.17476
  Regression -> MSE: 0.000108, MAE: 0.007963, R²: -0.0048
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.16762 | val 0.29022
  Epoch 016 - train 0.16133 | val 0.30032
  Regression -> MSE: 0.000157, MAE: 0.009871, R²: -0.0062
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.17074 | val 0.18289
  Epoch 016 - train 0.17194 | val 0.18758
  Regression -> MSE: 0.000288, MAE: 0.013736, R²: -0.0585
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.14775 | val 0.21909
  Epoch 016 - train 0.15114 | val 0.21820
  Regression -> MSE: 0.000154, MAE: 0.008756, R²: -0.0293
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.17403 | val 0.25478
  Epoch 016 - train 0.17631 | val 0.25071
  Regression -> MSE: 0.000229, MAE: 0.010905, R²: -0.0140
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.17329 | val 0.20628
  Epoch 016 - train 0.16297 | val 0.20970
  Regression -> MSE: 0.000151, MAE: 0.008744, R²: -0.0557
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.15573 | val 0.19970
  Epoch 016 - train 0.15624 | val 0.20107
  Regression -> MSE: 0.000170, MAE: 0.010269, R²: -0.0311
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.17593 | val 0.20095
  Epoch 016 - train 0.16591 | val 0.20050
  Regression -> MSE: 0.000092, MAE: 0.007372, R²: -0.0758
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.16997 | val 0.20050
  Epoch 016 - train 0.17363 | val 0.19979
  Regression -> MSE: 0.000216, MAE: 0.011046, R²: -0.0214
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.16764 | val 0.15979
  Epoch 016 - train 0.16083 | val 0.16433
  Regression -> MSE: 0.000101, MAE: 0.008253, R²: -0.1006
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.16129 | val 0.14602
  Epoch 016 - train 0.16916 | val 0.14898
  Regression -> MSE: 0.000122, MAE: 0.009393, R²: -0.1807
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.18150 | val 0.18392
  Epoch 016 - train 0.17459 | val 0.24752
  Regression -> MSE: 0.000237, MAE: 0.012746, R²: -0.0242
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.15874 | val 0.18419
  Epoch 020 - train 0.16030 | val 0.18419
  Regression -> MSE: 0.000203, MAE: 0.008783, R²: -0.2215
  Directional -> Accuracy: 0.5439, MCC: 0.2554, F1: 0.3500

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.16905 | val 0.14307
  Epoch 016 - train 0.16518 | val 0.14069
  Regression -> MSE: 0.000238, MAE: 0.011909, R²: -0.0048
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.16364 | val 0.27779
  Epoch 016 - train 0.16685 | val 0.29304
  Regression -> MSE: 0.000234, MAE: 0.010094, R²: -0.0144
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.17830 | val 0.19285
  Epoch 016 - train 0.17262 | val 0.19845
  Regression -> MSE: 0.000135, MAE: 0.008223, R²: -0.0020
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.16941 | val 0.20819
  Epoch 016 - train 0.17190 | val 0.20921
  Regression -> MSE: 0.000196, MAE: 0.010560, R²: -0.0416
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.15018 | val 0.19401
  Epoch 020 - train 0.14385 | val 0.19538
  Regression -> MSE: 0.000306, MAE: 0.011765, R²: -0.1670
  Directional -> Accuracy: 0.5342, MCC: 0.1602, F1: 0.4138

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.15379 | val 0.14238
  Epoch 016 - train 0.16021 | val 0.13949
  Regression -> MSE: 0.000167, MAE: 0.010367, R²: -0.0014
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.15126 | val 0.18232
  Epoch 016 - train 0.15169 | val 0.19897
  Regression -> MSE: 0.000188, MAE: 0.010619, R²: -0.0433
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.16838 | val 0.16924
  Epoch 016 - train 0.16207 | val 0.16808
  Regression -> MSE: 0.000348, MAE: 0.011738, R²: -0.0150
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.18854 | val 0.10790
  Epoch 016 - train 0.18659 | val 0.10716
  Regression -> MSE: 0.000109, MAE: 0.008341, R²: -0.0359
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.17229 | val 0.22843
  Epoch 016 - train 0.16838 | val 0.23274
  Regression -> MSE: 0.000219, MAE: 0.011271, R²: -0.0009
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.16767 | val 0.27822
  Epoch 020 - train 0.16399 | val 0.28302
  Regression -> MSE: 0.000101, MAE: 0.007834, R²: -0.2981
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.16447 | val 0.13368
  Epoch 016 - train 0.16667 | val 0.13920
  Regression -> MSE: 0.000324, MAE: 0.014716, R²: -0.0526
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.17507 | val 0.09737
  Epoch 016 - train 0.17938 | val 0.09645
  Regression -> MSE: 0.000246, MAE: 0.011571, R²: -0.0079
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.0000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.16985 | val 0.24015
  Epoch 016 - train 0.16642 | val 0.24010
  Regression -> MSE: 0.000081, MAE: 0.007111, R²: -0.0048
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.17658 | val 0.20402
  Epoch 016 - train 0.17340 | val 0.20694
  Regression -> MSE: 0.000309, MAE: 0.014526, R²: -0.0085
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.17893 | val 0.18976
  Epoch 016 - train 0.18036 | val 0.18939
  Regression -> MSE: 0.000100, MAE: 0.007122, R²: -0.0170
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.18563 | val 0.20311
  Epoch 016 - train 0.18592 | val 0.20894
  Regression -> MSE: 0.000172, MAE: 0.009559, R²: -0.0013
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.15429 | val 0.18406
  Epoch 020 - train 0.15702 | val 0.19749
  Regression -> MSE: 0.000226, MAE: 0.011417, R²: -0.0153
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.16766 | val 0.18547
  Epoch 020 - train 0.16606 | val 0.18210
  Regression -> MSE: 0.000097, MAE: 0.007860, R²: -0.0510
  Directional -> Accuracy: 0.5263, MCC: 0.0101, F1: 0.0690

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.17602 | val 0.26355
  Epoch 016 - train 0.17306 | val 0.27046
  Regression -> MSE: 0.000164, MAE: 0.010277, R²: -0.0039
  Directional -> Accuracy: 0.5000, MCC: -0.0719, F1: 0.6582

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.15693 | val 0.20687
  Epoch 016 - train 0.15582 | val 0.21356
  Regression -> MSE: 0.000122, MAE: 0.009000, R²: -0.0534
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.16463 | val 0.28243

[I 2026-02-23 00:11:47,120] Trial 145 finished with value: -0.011531631372025017 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.30000000000000004, 'batch_size': 32, 'learning_rate': 4.397395260913177e-06, 'weight_decay': 9.576746852118538e-06, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 0.2595996922942452, 'early_stopping_min_delta': 0.006957839503765125}. Best is trial 143 with value: -0.011397192428235973.

  Epoch 016 - train 0.17115 | val 0.30785
  Regression -> MSE: 0.000237, MAE: 0.012475, R²: -0.0006
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.21484 | val 0.31335
  Epoch 016 - train 0.21751 | val 0.30829
  Regression -> MSE: 0.000257, MAE: 0.012909, R²: -0.0377
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.20889 | val 0.19894
  Epoch 016 - train 0.19963 | val 0.20610
  Regression -> MSE: 0.000691, MAE: 0.019469, R²: -0.0091
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.22977 | val 0.34992
  Epoch 016 - train 0.21953 | val 0.35345
  Regression -> MSE: 0.000316, MAE: 0.014470, R²: -0.0173
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.16834 | val 0.25931
  Epoch 016 - train 0.16832 | val 0.27943
  Regression -> MSE: 0.000377, MAE: 0.015040, R²: -0.0803
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.21426 | val 0.22077
  Epoch 016 - train 0.20858 | val 0.22629
  Regression -> MSE: 0.000206, MAE: 0.010397, R²: -0.0132
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.21272 | val 0.40078
  Epoch 016 - train 0.20139 | val 0.41697
  Regression -> MSE: 0.000559, MAE: 0.018196, R²: -0.0065
  Directional -> Accuracy: 0.4681, MCC: -0.1506, F1: 0.6377

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.20884 | val 0.28642
  Epoch 016 - train 0.21208 | val 0.28423
  Regression -> MSE: 0.000251, MAE: 0.012548, R²: -0.0225
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.20140 | val 0.30754
  Epoch 016 - train 0.21370 | val 0.30743
  Regression -> MSE: 0.000664, MAE: 0.020457, R²: -0.1121
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.19274 | val 0.24274
  Epoch 016 - train 0.19630 | val 0.24685
  Regression -> MSE: 0.000407, MAE: 0.016187, R²: -0.0612
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.20286 | val 0.28496
  Epoch 016 - train 0.20407 | val 0.28149
  Regression -> MSE: 0.000244, MAE: 0.012233, R²: -0.0098
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.19029 | val 0.30334
  Epoch 016 - train 0.18714 | val 0.30858
  Regression -> MSE: 0.000314, MAE: 0.013616, R²: -0.0083
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.22719 | val 0.25115
  Epoch 016 - train 0.21966 | val 0.25521
  Regression -> MSE: 0.000685, MAE: 0.019816, R²: -0.0121
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.23738 | val 0.23271
  Epoch 016 - train 0.23196 | val 0.27677
  Regression -> MSE: 0.000139, MAE: 0.009007, R²: -0.0033
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.19580 | val 0.28618
  Epoch 016 - train 0.18761 | val 0.28207
  Regression -> MSE: 0.000227, MAE: 0.010920, R²: -0.0105
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.19877 | val 0.43369
  Epoch 016 - train 0.20351 | val 0.46006
  Regression -> MSE: 0.000366, MAE: 0.015961, R²: -0.0101
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.21294 | val 0.20220
  Epoch 020 - train 0.21785 | val 0.20824
  Regression -> MSE: 0.000108, MAE: 0.007918, R²: 0.0013
  Directional -> Accuracy: 0.5429, MCC: 0.0263, F1: 0.6863

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.18903 | val 0.44737
  Epoch 016 - train 0.19447 | val 0.50630
  Regression -> MSE: 0.000158, MAE: 0.009967, R²: -0.0144
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.22065 | val 0.27531
  Epoch 016 - train 0.21641 | val 0.28636
  Regression -> MSE: 0.000281, MAE: 0.013467, R²: -0.0322
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.18987 | val 0.26898
  Epoch 020 - train 0.18476 | val 0.26705
  Regression -> MSE: 0.000177, MAE: 0.009703, R²: -0.1821
  Directional -> Accuracy: 0.4769, MCC: -0.0442, F1: 0.5143

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.21024 | val 0.30751
  Epoch 016 - train 0.21265 | val 0.30548
  Regression -> MSE: 0.000236, MAE: 0.011032, R²: -0.0416
  Directional -> Accuracy: 0.3467, MCC: -0.2938, F1: 0.2899

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.20298 | val 0.25881
  Epoch 016 - train 0.20468 | val 0.26570
  Regression -> MSE: 0.000151, MAE: 0.008712, R²: -0.0510
  Directional -> Accuracy: 0.5625, MCC: 0.0348, F1: 0.6667

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.19457 | val 0.24997
  Epoch 016 - train 0.19590 | val 0.25172
  Regression -> MSE: 0.000168, MAE: 0.010294, R²: -0.0161
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.21765 | val 0.24406
  Epoch 016 - train 0.21289 | val 0.24334
  Regression -> MSE: 0.000088, MAE: 0.007220, R²: -0.0366
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.21407 | val 0.25348
  Epoch 016 - train 0.20618 | val 0.24793
  Regression -> MSE: 0.000213, MAE: 0.011079, R²: -0.0060
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.18564 | val 0.18052
  Epoch 020 - train 0.18361 | val 0.17279
  Regression -> MSE: 0.000101, MAE: 0.008267, R²: -0.0970
  Directional -> Accuracy: 0.4643, MCC: 0.0017, F1: 0.2500

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.20128 | val 0.15625
  Epoch 016 - train 0.19800 | val 0.15597
  Regression -> MSE: 0.000104, MAE: 0.008789, R²: -0.0094
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.22217 | val 0.19756
  Epoch 016 - train 0.21898 | val 0.19910
  Regression -> MSE: 0.000232, MAE: 0.012573, R²: -0.0028
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.21989 | val 0.27224
  Epoch 016 - train 0.22349 | val 0.28148
  Regression -> MSE: 0.000171, MAE: 0.007846, R²: -0.0259
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.21684 | val 0.16953
  Epoch 016 - train 0.21243 | val 0.18000
  Regression -> MSE: 0.000239, MAE: 0.011934, R²: -0.0090
  Directional -> Accuracy: 0.4390, MCC: -0.1701, F1: 0.0000

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.21136 | val 0.32991
  Epoch 016 - train 0.21045 | val 0.33178
  Regression -> MSE: 0.000231, MAE: 0.009877, R²: -0.0008
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.20660 | val 0.24052
  Epoch 016 - train 0.20911 | val 0.24372
  Regression -> MSE: 0.000135, MAE: 0.008191, R²: 0.0004
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.20972 | val 0.26279
  Epoch 016 - train 0.21153 | val 0.26526
  Regression -> MSE: 0.000192, MAE: 0.010427, R²: -0.0210
  Directional -> Accuracy: 0.4800, MCC: -0.0467, F1: 0.5185

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.18519 | val 0.25290
  Epoch 016 - train 0.18385 | val 0.25232
  Regression -> MSE: 0.000262, MAE: 0.010531, R²: -0.0004
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.19885 | val 0.17319
  Epoch 016 - train 0.20821 | val 0.17226
  Regression -> MSE: 0.000167, MAE: 0.010370, R²: 0.0005
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.19646 | val 0.20644
  Epoch 016 - train 0.19285 | val 0.20691
  Regression -> MSE: 0.000181, MAE: 0.010322, R²: -0.0075
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.21055 | val 0.20367
  Epoch 016 - train 0.20822 | val 0.20165
  Regression -> MSE: 0.000351, MAE: 0.011799, R²: -0.0251
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.23110 | val 0.12805
  Epoch 016 - train 0.23553 | val 0.12965
  Regression -> MSE: 0.000122, MAE: 0.008392, R²: -0.1594
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.20544 | val 0.30111
  Epoch 016 - train 0.20955 | val 0.30487
  Regression -> MSE: 0.000225, MAE: 0.011472, R²: -0.0306
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.20473 | val 0.38357
  Epoch 016 - train 0.20508 | val 0.43235
  Regression -> MSE: 0.000086, MAE: 0.007250, R²: -0.1065
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.24296 | val 0.15421
  Epoch 016 - train 0.22541 | val 0.15554
  Regression -> MSE: 0.000312, MAE: 0.014065, R²: -0.0131
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.21267 | val 0.12105
  Epoch 016 - train 0.22514 | val 0.11955
  Regression -> MSE: 0.000253, MAE: 0.011474, R²: -0.0394
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.20121 | val 0.27448
  Epoch 016 - train 0.20333 | val 0.27337
  Regression -> MSE: 0.000085, MAE: 0.007061, R²: -0.0493
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.20598 | val 0.26563
  Epoch 016 - train 0.20335 | val 0.27034
  Regression -> MSE: 0.000309, MAE: 0.014480, R²: -0.0072
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.20670 | val 0.24701
  Epoch 016 - train 0.20312 | val 0.24348
  Regression -> MSE: 0.000102, MAE: 0.007106, R²: -0.0407
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.23096 | val 0.25126
  Epoch 016 - train 0.21634 | val 0.25440
  Regression -> MSE: 0.000176, MAE: 0.010201, R²: -0.0216
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.19299 | val 0.28163
  Epoch 016 - train 0.18872 | val 0.31554
  Regression -> MSE: 0.000223, MAE: 0.011742, R²: -0.0020
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.20818 | val 0.27733
  Epoch 016 - train 0.19976 | val 0.29489
  Regression -> MSE: 0.000099, MAE: 0.008075, R²: -0.0719
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.22342 | val 0.33103
  Epoch 016 - train 0.21998 | val 0.33685
  Regression -> MSE: 0.000168, MAE: 0.010330, R²: -0.0280
  Directional -> Accuracy: 0.4815, MCC: 0.0000, F1: 0.0000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.19767 | val 0.25474
  Epoch 016 - train 0.19238 | val 0.25728
  Regression -> MSE: 0.000121, MAE: 0.008982, R²: -0.0415
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.21291 | val 0.29701

[I 2026-02-23 00:14:31,944] Trial 146 finished with value: -0.01149008290074258 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.30000000000000004, 'batch_size': 32, 'learning_rate': 3.9582114727779114e-06, 'weight_decay': 7.092210712162263e-06, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 0.3386992963965814, 'early_stopping_min_delta': 0.007220343594205443}. Best is trial 143 with value: -0.011397192428235973.

  Epoch 016 - train 0.20565 | val 0.30670
  Regression -> MSE: 0.000242, MAE: 0.012329, R²: -0.0203
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.15570 | val 0.20177
  Epoch 020 - train 0.15453 | val 0.20333
  Regression -> MSE: 0.000250, MAE: 0.012657, R²: -0.0103
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.15381 | val 0.15204
  Epoch 020 - train 0.15168 | val 0.15897
  Regression -> MSE: 0.000702, MAE: 0.019633, R²: -0.0251
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.15690 | val 0.26125
  Epoch 020 - train 0.15647 | val 0.26849
  Regression -> MSE: 0.000310, MAE: 0.014384, R²: 0.0004
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.12888 | val 0.14954
  Epoch 020 - train 0.13086 | val 0.17161
  Regression -> MSE: 0.000350, MAE: 0.014566, R²: -0.0008
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.16269 | val 0.16207
  Epoch 020 - train 0.16870 | val 0.16218
  Regression -> MSE: 0.000205, MAE: 0.010113, R²: -0.0052
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.15082 | val 0.29528
  Epoch 020 - train 0.14584 | val 0.31103
  Regression -> MSE: 0.000570, MAE: 0.018360, R²: -0.0261
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.16069 | val 0.20413
  Epoch 020 - train 0.15808 | val 0.20463
  Regression -> MSE: 0.000252, MAE: 0.011970, R²: -0.0248
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.15747 | val 0.22759
  Epoch 020 - train 0.15947 | val 0.26747
  Regression -> MSE: 0.000641, MAE: 0.020081, R²: -0.0721
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.14769 | val 0.18842
  Epoch 020 - train 0.14381 | val 0.18587
  Regression -> MSE: 0.000392, MAE: 0.015924, R²: -0.0228
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.16101 | val 0.21195
  Epoch 020 - train 0.15799 | val 0.20735
  Regression -> MSE: 0.000243, MAE: 0.012121, R²: -0.0057
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.13942 | val 0.23061
  Epoch 020 - train 0.14868 | val 0.23661
  Regression -> MSE: 0.000315, MAE: 0.013617, R²: -0.0124
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.16173 | val 0.18212
  Epoch 020 - train 0.15824 | val 0.18454
  Regression -> MSE: 0.000680, MAE: 0.019607, R²: -0.0045
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.16183 | val 0.15565
  Epoch 020 - train 0.15638 | val 0.16068
  Regression -> MSE: 0.000140, MAE: 0.009304, R²: -0.0148
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.14439 | val 0.21382
  Epoch 020 - train 0.14434 | val 0.20979
  Regression -> MSE: 0.000223, MAE: 0.010811, R²: 0.0066
  Directional -> Accuracy: 0.5410, MCC: 0.1872, F1: 0.6889

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.15306 | val 0.32051
  Epoch 020 - train 0.14961 | val 0.33165
  Regression -> MSE: 0.000370, MAE: 0.015913, R²: -0.0229
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.17401 | val 0.18183
  Epoch 020 - train 0.16448 | val 0.17682
  Regression -> MSE: 0.000110, MAE: 0.008207, R²: -0.0231
  Directional -> Accuracy: 0.4571, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.14838 | val 0.27200
  Epoch 020 - train 0.14539 | val 0.28458
  Regression -> MSE: 0.000157, MAE: 0.009569, R²: -0.0064
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.16594 | val 0.19827
  Epoch 020 - train 0.16155 | val 0.18749
  Regression -> MSE: 0.000277, MAE: 0.012943, R²: -0.0171
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.14918 | val 0.20641
  Epoch 020 - train 0.13951 | val 0.20376
  Regression -> MSE: 0.000158, MAE: 0.008839, R²: -0.0565
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.16242 | val 0.24699
  Epoch 020 - train 0.16214 | val 0.24512
  Regression -> MSE: 0.000245, MAE: 0.011173, R²: -0.0810
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.16005 | val 0.19748
  Epoch 020 - train 0.15685 | val 0.20221
  Regression -> MSE: 0.000153, MAE: 0.008839, R²: -0.0708
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.14903 | val 0.18322
  Epoch 020 - train 0.14866 | val 0.18396
  Regression -> MSE: 0.000170, MAE: 0.010260, R²: -0.0281
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.17322 | val 0.20807
  Epoch 020 - train 0.17285 | val 0.21156
  Regression -> MSE: 0.000093, MAE: 0.007448, R²: -0.0938
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.15901 | val 0.18890
  Epoch 020 - train 0.15882 | val 0.18640
  Regression -> MSE: 0.000212, MAE: 0.011170, R²: -0.0002
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.15807 | val 0.14906
  Epoch 020 - train 0.15180 | val 0.15122
  Regression -> MSE: 0.000093, MAE: 0.008103, R²: -0.0065
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.16723 | val 0.12099
  Epoch 020 - train 0.16600 | val 0.13688
  Regression -> MSE: 0.000105, MAE: 0.008847, R²: -0.0186
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.17418 | val 0.17547
  Epoch 020 - train 0.16985 | val 0.22098
  Regression -> MSE: 0.000232, MAE: 0.012513, R²: -0.0006
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.15452 | val 0.19552
  Epoch 020 - train 0.15592 | val 0.20003
  Regression -> MSE: 0.000174, MAE: 0.007847, R²: -0.0458
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.16532 | val 0.13759
  Epoch 020 - train 0.16436 | val 0.13470
  Regression -> MSE: 0.000238, MAE: 0.011893, R²: -0.0047
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.15537 | val 0.26058
  Epoch 020 - train 0.15037 | val 0.27484
  Regression -> MSE: 0.000233, MAE: 0.010042, R²: -0.0105
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.16132 | val 0.20678
  Epoch 020 - train 0.16283 | val 0.21315
  Regression -> MSE: 0.000142, MAE: 0.008550, R²: -0.0516
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.16078 | val 0.20246
  Epoch 020 - train 0.15365 | val 0.20593
  Regression -> MSE: 0.000198, MAE: 0.010635, R²: -0.0490
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.14044 | val 0.17522
  Epoch 020 - train 0.13859 | val 0.17708
  Regression -> MSE: 0.000271, MAE: 0.010655, R²: -0.0368
  Directional -> Accuracy: 0.4932, MCC: 0.0797, F1: 0.3273

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.14397 | val 0.13406
  Epoch 020 - train 0.14613 | val 0.14145
  Regression -> MSE: 0.000167, MAE: 0.010365, R²: -0.0037
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.14659 | val 0.16029
  Epoch 020 - train 0.14305 | val 0.16752
  Regression -> MSE: 0.000180, MAE: 0.010261, R²: -0.0014
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.15383 | val 0.15494
  Epoch 020 - train 0.15160 | val 0.15462
  Regression -> MSE: 0.000356, MAE: 0.012703, R²: -0.0379
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.16578 | val 0.10273
  Epoch 020 - train 0.16745 | val 0.10156
  Regression -> MSE: 0.000128, MAE: 0.008537, R²: -0.2217
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.15300 | val 0.21693
  Epoch 020 - train 0.15644 | val 0.21781
  Regression -> MSE: 0.000219, MAE: 0.011288, R²: -0.0016
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.15521 | val 0.27961
  Epoch 020 - train 0.15919 | val 0.28275
  Regression -> MSE: 0.000081, MAE: 0.006997, R²: -0.0393
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.15701 | val 0.12194
  Epoch 020 - train 0.15285 | val 0.11922
  Regression -> MSE: 0.000318, MAE: 0.014358, R²: -0.0321
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.16800 | val 0.09716
  Epoch 020 - train 0.17052 | val 0.10132
  Regression -> MSE: 0.000252, MAE: 0.011485, R²: -0.0317
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.15051 | val 0.19636
  Epoch 020 - train 0.14535 | val 0.19699
  Regression -> MSE: 0.000086, MAE: 0.007071, R²: -0.0653
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.15896 | val 0.20778
  Epoch 020 - train 0.15767 | val 0.23592
  Regression -> MSE: 0.000307, MAE: 0.014486, R²: 0.0008
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.16138 | val 0.17222
  Epoch 020 - train 0.15701 | val 0.18716
  Regression -> MSE: 0.000099, MAE: 0.007246, R²: -0.0034
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.17561 | val 0.19234
  Epoch 020 - train 0.17741 | val 0.19386
  Regression -> MSE: 0.000178, MAE: 0.010348, R²: -0.0339
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.14674 | val 0.18734
  Epoch 020 - train 0.14435 | val 0.19423
  Regression -> MSE: 0.000224, MAE: 0.011794, R²: -0.0045
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.15565 | val 0.17299
  Epoch 020 - train 0.15795 | val 0.17056
  Regression -> MSE: 0.000093, MAE: 0.007672, R²: -0.0041
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.16571 | val 0.25521
  Epoch 020 - train 0.16454 | val 0.27060
  Regression -> MSE: 0.000164, MAE: 0.010265, R²: -0.0006
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.16349 | val 0.21095
  Epoch 020 - train 0.15498 | val 0.23005
  Regression -> MSE: 0.000123, MAE: 0.009001, R²: -0.0569
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.17116 | val 0.22561

[I 2026-02-23 00:17:11,378] Trial 147 finished with value: -0.011459489794023075 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 32, 'learning_rate': 6.060935844083306e-06, 'weight_decay': 1.1914422409324827e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.2452936213054369, 'early_stopping_min_delta': 0.0072249764621545995}. Best is trial 143 with value: -0.011397192428235973.

  Epoch 020 - train 0.16971 | val 0.24617
  Regression -> MSE: 0.000238, MAE: 0.012505, R²: -0.0027
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.15405 | val 0.21807
  Epoch 020 - train 0.15642 | val 0.21633
  Regression -> MSE: 0.000257, MAE: 0.012930, R²: -0.0397
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.16091 | val 0.15611
  Epoch 020 - train 0.15527 | val 0.15579
  Regression -> MSE: 0.000693, MAE: 0.019494, R²: -0.0128
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.15683 | val 0.25725
  Epoch 020 - train 0.16309 | val 0.26194
  Regression -> MSE: 0.000311, MAE: 0.014460, R²: -0.0013
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.12964 | val 0.21945
  Epoch 020 - train 0.12362 | val 0.24224
  Regression -> MSE: 0.000350, MAE: 0.014581, R²: -0.0029
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.14863 | val 0.14979
  Epoch 020 - train 0.15152 | val 0.15186
  Regression -> MSE: 0.000206, MAE: 0.010062, R²: -0.0113
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.15353 | val 0.28851
  Epoch 020 - train 0.16209 | val 0.28921
  Regression -> MSE: 0.000563, MAE: 0.018232, R²: -0.0149
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.16146 | val 0.19479
  Epoch 020 - train 0.15836 | val 0.19297
  Regression -> MSE: 0.000246, MAE: 0.012118, R²: -0.0011
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.15486 | val 0.22400
  Epoch 020 - train 0.15648 | val 0.24476
  Regression -> MSE: 0.000649, MAE: 0.020234, R²: -0.0867
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.14472 | val 0.19425
  Epoch 020 - train 0.14324 | val 0.19116
  Regression -> MSE: 0.000386, MAE: 0.016140, R²: -0.0063
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.16059 | val 0.20108
  Epoch 020 - train 0.16013 | val 0.20195
  Regression -> MSE: 0.000246, MAE: 0.011662, R²: -0.0187
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.14138 | val 0.22542
  Epoch 020 - train 0.14735 | val 0.23152
  Regression -> MSE: 0.000311, MAE: 0.013674, R²: -0.0012
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.6301

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.18323 | val 0.22663
  Epoch 020 - train 0.17796 | val 0.24814
  Regression -> MSE: 0.000685, MAE: 0.019723, R²: -0.0112
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.14518 | val 0.15217
  Epoch 020 - train 0.14398 | val 0.15835
  Regression -> MSE: 0.000143, MAE: 0.009428, R²: -0.0366
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.14262 | val 0.20322
  Epoch 020 - train 0.13531 | val 0.20143
  Regression -> MSE: 0.000225, MAE: 0.010724, R²: -0.0000
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.15261 | val 0.31198
  Epoch 020 - train 0.15008 | val 0.31788
  Regression -> MSE: 0.000367, MAE: 0.015967, R²: -0.0141
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.15945 | val 0.16805
  Epoch 020 - train 0.15076 | val 0.17566
  Regression -> MSE: 0.000108, MAE: 0.008038, R²: 0.0014
  Directional -> Accuracy: 0.4571, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.15468 | val 0.27275
  Epoch 020 - train 0.15262 | val 0.28929
  Regression -> MSE: 0.000164, MAE: 0.010307, R²: -0.0548
  Directional -> Accuracy: 0.3729, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.15511 | val 0.15827
  Epoch 020 - train 0.15504 | val 0.16164
  Regression -> MSE: 0.000273, MAE: 0.012942, R²: -0.0038
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.14155 | val 0.20475
  Epoch 020 - train 0.13892 | val 0.20279
  Regression -> MSE: 0.000170, MAE: 0.009210, R²: -0.1362
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.17678 | val 0.26269
  Epoch 020 - train 0.16983 | val 0.26017
  Regression -> MSE: 0.000252, MAE: 0.011349, R²: -0.1143
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.16499 | val 0.19647
  Epoch 020 - train 0.16406 | val 0.20116
  Regression -> MSE: 0.000144, MAE: 0.008377, R²: -0.0063
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.14731 | val 0.19293
  Epoch 020 - train 0.14356 | val 0.19075
  Regression -> MSE: 0.000165, MAE: 0.010475, R²: 0.0008
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.16279 | val 0.18239
  Epoch 020 - train 0.15844 | val 0.18670
  Regression -> MSE: 0.000090, MAE: 0.007309, R²: -0.0572
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.15343 | val 0.19622
  Epoch 020 - train 0.15655 | val 0.19874
  Regression -> MSE: 0.000213, MAE: 0.011059, R²: -0.0072
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.13948 | val 0.14047
  Epoch 020 - train 0.14690 | val 0.13864
  Regression -> MSE: 0.000095, MAE: 0.008101, R²: -0.0292
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.15873 | val 0.12276
  Epoch 020 - train 0.15994 | val 0.11988
  Regression -> MSE: 0.000109, MAE: 0.009005, R²: -0.0598
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.16193 | val 0.15000
  Epoch 020 - train 0.15745 | val 0.16368
  Regression -> MSE: 0.000232, MAE: 0.012572, R²: -0.0037
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.15441 | val 0.17343
  Epoch 020 - train 0.15019 | val 0.17275
  Regression -> MSE: 0.000219, MAE: 0.009339, R²: -0.3164
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.16144 | val 0.14012
  Epoch 020 - train 0.17427 | val 0.14045
  Regression -> MSE: 0.000241, MAE: 0.012043, R²: -0.0168
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.16473 | val 0.24313
  Epoch 020 - train 0.16851 | val 0.24422
  Regression -> MSE: 0.000230, MAE: 0.009855, R²: 0.0001
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.16425 | val 0.18130
  Epoch 020 - train 0.16833 | val 0.17755
  Regression -> MSE: 0.000126, MAE: 0.008279, R²: 0.0647
  Directional -> Accuracy: 0.5814, MCC: 0.1489, F1: 0.6786

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.15345 | val 0.19533
  Epoch 020 - train 0.15455 | val 0.19436
  Regression -> MSE: 0.000191, MAE: 0.010703, R²: -0.0122
  Directional -> Accuracy: 0.4800, MCC: -0.2332, F1: 0.6486

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.13685 | val 0.18699
  Epoch 020 - train 0.14113 | val 0.18249
  Regression -> MSE: 0.000276, MAE: 0.010767, R²: -0.0532
  Directional -> Accuracy: 0.4384, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.15332 | val 0.14308
  Epoch 020 - train 0.14726 | val 0.14532
  Regression -> MSE: 0.000169, MAE: 0.010373, R²: -0.0169
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.14352 | val 0.15976
  Epoch 020 - train 0.14900 | val 0.17595
  Regression -> MSE: 0.000181, MAE: 0.010268, R²: -0.0041
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.15268 | val 0.14138
  Epoch 020 - train 0.14424 | val 0.14308
  Regression -> MSE: 0.000343, MAE: 0.011760, R²: -0.0001
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.17733 | val 0.10234
  Epoch 020 - train 0.17177 | val 0.10815
  Regression -> MSE: 0.000129, MAE: 0.008554, R²: -0.2283
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.15721 | val 0.21516
  Epoch 020 - train 0.15478 | val 0.21972
  Regression -> MSE: 0.000220, MAE: 0.011322, R²: -0.0063
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.15851 | val 0.28219
  Epoch 020 - train 0.15602 | val 0.29501
  Regression -> MSE: 0.000081, MAE: 0.007005, R²: -0.0414
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.16187 | val 0.13353
  Epoch 020 - train 0.15953 | val 0.13232
  Regression -> MSE: 0.000340, MAE: 0.015347, R²: -0.1046
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.16572 | val 0.09399
  Epoch 020 - train 0.16567 | val 0.10110
  Regression -> MSE: 0.000248, MAE: 0.011523, R²: -0.0159
  Directional -> Accuracy: 0.5526, MCC: 0.1132, F1: 0.6909

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.15294 | val 0.18273
  Epoch 020 - train 0.14642 | val 0.18246
  Regression -> MSE: 0.000084, MAE: 0.007049, R²: -0.0355
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.15001 | val 0.19311
  Epoch 020 - train 0.15710 | val 0.17938
  Regression -> MSE: 0.000309, MAE: 0.014479, R²: -0.0059
  Directional -> Accuracy: 0.5957, MCC: 0.1993, F1: 0.5581

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.16296 | val 0.16266
  Epoch 020 - train 0.16139 | val 0.17026
  Regression -> MSE: 0.000099, MAE: 0.007414, R²: -0.0046
  Directional -> Accuracy: 0.4318, MCC: 0.0000, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.16339 | val 0.18749
  Epoch 020 - train 0.16051 | val 0.18453
  Regression -> MSE: 0.000172, MAE: 0.009503, R²: -0.0035
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.14406 | val 0.18076
  Epoch 020 - train 0.14308 | val 0.18183
  Regression -> MSE: 0.000228, MAE: 0.011846, R²: -0.0236
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.16841 | val 0.17044
  Epoch 020 - train 0.16934 | val 0.16799
  Regression -> MSE: 0.000093, MAE: 0.007663, R²: -0.0106
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.16722 | val 0.24134
  Epoch 020 - train 0.16638 | val 0.24195
  Regression -> MSE: 0.000164, MAE: 0.010275, R²: -0.0033
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.15609 | val 0.19125
  Epoch 020 - train 0.15387 | val 0.19143
  Regression -> MSE: 0.000118, MAE: 0.008954, R²: -0.0137
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.16140 | val 0.23436

[I 2026-02-23 00:19:49,966] Trial 148 finished with value: -0.011497341093605767 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.30000000000000004, 'batch_size': 32, 'learning_rate': 6.559217375994767e-06, 'weight_decay': 1.443362283201747e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.2403413082696633, 'early_stopping_min_delta': 0.007086540387053435}. Best is trial 143 with value: -0.011397192428235973.

  Epoch 020 - train 0.16124 | val 0.24536
  Regression -> MSE: 0.000237, MAE: 0.012373, R²: 0.0015
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.09029 | val 0.13441
  Epoch 020 - train 0.08851 | val 0.13414
  Regression -> MSE: 0.000262, MAE: 0.013075, R²: -0.0602
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.08893 | val 0.08606
  Epoch 020 - train 0.08719 | val 0.09433
  Regression -> MSE: 0.000700, MAE: 0.019608, R²: -0.0228
  Directional -> Accuracy: 0.5000, MCC: -0.0488, F1: 0.5965

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.09432 | val 0.14228
  Epoch 020 - train 0.09464 | val 0.14149
  Regression -> MSE: 0.000318, MAE: 0.014476, R²: -0.0240
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.07405 | val 0.12505
  Epoch 020 - train 0.07668 | val 0.14529
  Regression -> MSE: 0.000351, MAE: 0.014604, R²: -0.0040
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.09318 | val 0.09976
  Epoch 020 - train 0.09298 | val 0.10579
  Regression -> MSE: 0.000206, MAE: 0.010364, R²: -0.0115
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.08138 | val 0.16233
  Epoch 020 - train 0.08143 | val 0.16795
  Regression -> MSE: 0.000576, MAE: 0.018500, R²: -0.0368
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.09354 | val 0.11015
  Epoch 020 - train 0.09289 | val 0.11101
  Regression -> MSE: 0.000246, MAE: 0.011935, R²: -0.0038
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.09094 | val 0.11511
  Epoch 020 - train 0.09007 | val 0.13159
  Regression -> MSE: 0.000616, MAE: 0.019609, R²: -0.0309
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.08479 | val 0.11190
  Epoch 020 - train 0.08632 | val 0.10725
  Regression -> MSE: 0.000384, MAE: 0.016138, R²: 0.0001
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.09036 | val 0.13412
  Epoch 020 - train 0.08908 | val 0.14280
  Regression -> MSE: 0.000242, MAE: 0.012030, R²: -0.0021
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.08342 | val 0.13561
  Epoch 020 - train 0.08292 | val 0.15056
  Regression -> MSE: 0.000311, MAE: 0.013739, R²: 0.0003
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.6301

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.08715 | val 0.11138
  Epoch 020 - train 0.08919 | val 0.11530
  Regression -> MSE: 0.000679, MAE: 0.019480, R²: -0.0022
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.08550 | val 0.09215
  Epoch 020 - train 0.08406 | val 0.09166
  Regression -> MSE: 0.000139, MAE: 0.009038, R²: -0.0048
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.08515 | val 0.11680
  Epoch 020 - train 0.08134 | val 0.11660
  Regression -> MSE: 0.000227, MAE: 0.010737, R²: -0.0085
  Directional -> Accuracy: 0.4918, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.08617 | val 0.18473
  Epoch 020 - train 0.08710 | val 0.20023
  Regression -> MSE: 0.000362, MAE: 0.016071, R²: -0.0006
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.09050 | val 0.10138
  Epoch 020 - train 0.09154 | val 0.10355
  Regression -> MSE: 0.000108, MAE: 0.008026, R²: 0.0005
  Directional -> Accuracy: 0.4857, MCC: 0.1024, F1: 0.1429

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.08681 | val 0.14257
  Epoch 020 - train 0.08699 | val 0.14480
  Regression -> MSE: 0.000156, MAE: 0.009598, R²: -0.0035
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.09066 | val 0.10346
  Epoch 020 - train 0.08853 | val 0.10606
  Regression -> MSE: 0.000274, MAE: 0.013139, R²: -0.0075
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.08396 | val 0.12688
  Epoch 020 - train 0.08474 | val 0.12618
  Regression -> MSE: 0.000155, MAE: 0.008771, R²: -0.0357
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.09256 | val 0.12721
  Epoch 020 - train 0.09194 | val 0.12539
  Regression -> MSE: 0.000248, MAE: 0.011272, R²: -0.0953
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.09099 | val 0.10976
  Epoch 020 - train 0.09115 | val 0.10828
  Regression -> MSE: 0.000146, MAE: 0.008490, R²: -0.0162
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.08824 | val 0.11265
  Epoch 020 - train 0.08686 | val 0.11353
  Regression -> MSE: 0.000165, MAE: 0.010566, R²: -0.0013
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.09547 | val 0.10569
  Epoch 020 - train 0.09289 | val 0.10415
  Regression -> MSE: 0.000086, MAE: 0.007076, R²: -0.0068
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.09079 | val 0.12708
  Epoch 020 - train 0.09042 | val 0.12409
  Regression -> MSE: 0.000212, MAE: 0.011214, R²: -0.0015
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.08945 | val 0.08448
  Epoch 020 - train 0.08973 | val 0.08434
  Regression -> MSE: 0.000092, MAE: 0.008096, R²: -0.0049
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.09594 | val 0.07123
  Epoch 020 - train 0.09403 | val 0.07985
  Regression -> MSE: 0.000103, MAE: 0.008698, R²: 0.0002
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.09166 | val 0.09188
  Epoch 020 - train 0.09281 | val 0.10357
  Regression -> MSE: 0.000239, MAE: 0.012803, R²: -0.0311
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.09112 | val 0.09921
  Epoch 020 - train 0.08893 | val 0.09873
  Regression -> MSE: 0.000187, MAE: 0.008097, R²: -0.1257
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.09172 | val 0.07731
  Epoch 020 - train 0.09466 | val 0.07737
  Regression -> MSE: 0.000236, MAE: 0.011859, R²: 0.0008
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.09173 | val 0.14071
  Epoch 020 - train 0.08621 | val 0.14214
  Regression -> MSE: 0.000231, MAE: 0.009912, R²: -0.0014
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.09786 | val 0.10336
  Epoch 020 - train 0.09689 | val 0.10431
  Regression -> MSE: 0.000135, MAE: 0.008168, R²: -0.0016
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.09122 | val 0.11228
  Epoch 020 - train 0.09239 | val 0.11241
  Regression -> MSE: 0.000201, MAE: 0.010761, R²: -0.0678
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.08123 | val 0.10192
  Epoch 020 - train 0.08193 | val 0.10126
  Regression -> MSE: 0.000266, MAE: 0.010524, R²: -0.0158
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.09551 | val 0.07981
  Epoch 020 - train 0.09366 | val 0.09952
  Regression -> MSE: 0.000167, MAE: 0.010367, R²: -0.0023
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.08221 | val 0.08979
  Epoch 020 - train 0.08389 | val 0.09212
  Regression -> MSE: 0.000181, MAE: 0.010268, R²: -0.0030
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.08839 | val 0.08946
  Epoch 020 - train 0.08663 | val 0.08797
  Regression -> MSE: 0.000347, MAE: 0.012233, R²: -0.0141
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.09928 | val 0.06061
  Epoch 020 - train 0.09625 | val 0.06206
  Regression -> MSE: 0.000114, MAE: 0.008318, R²: -0.0852
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.09185 | val 0.12015
  Epoch 020 - train 0.09196 | val 0.12162
  Regression -> MSE: 0.000221, MAE: 0.011351, R²: -0.0090
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.08773 | val 0.15304
  Epoch 020 - train 0.08832 | val 0.15638
  Regression -> MSE: 0.000082, MAE: 0.007047, R²: -0.0519
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.09260 | val 0.07417
  Epoch 020 - train 0.08959 | val 0.07282
  Regression -> MSE: 0.000328, MAE: 0.014875, R²: -0.0651
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.09503 | val 0.05754
  Epoch 020 - train 0.09255 | val 0.06273
  Regression -> MSE: 0.000254, MAE: 0.011469, R²: -0.0405
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.08497 | val 0.10744
  Epoch 020 - train 0.08508 | val 0.10713
  Regression -> MSE: 0.000081, MAE: 0.007067, R²: 0.0003
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.08752 | val 0.10864
  Epoch 020 - train 0.08758 | val 0.11319
  Regression -> MSE: 0.000309, MAE: 0.014527, R²: -0.0083
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.08465 | val 0.10291
  Epoch 020 - train 0.07858 | val 0.10284
  Regression -> MSE: 0.000100, MAE: 0.007122, R²: -0.0166
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.09942 | val 0.10898
  Epoch 020 - train 0.10025 | val 0.11557
  Regression -> MSE: 0.000173, MAE: 0.009482, R²: -0.0043
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.08782 | val 0.10809
  Epoch 020 - train 0.08660 | val 0.12600
  Regression -> MSE: 0.000224, MAE: 0.011796, R²: -0.0038
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.08902 | val 0.09923
  Epoch 020 - train 0.08686 | val 0.10032
  Regression -> MSE: 0.000092, MAE: 0.007635, R²: 0.0002
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.09890 | val 0.15094
  Epoch 020 - train 0.09776 | val 0.17759
  Regression -> MSE: 0.000165, MAE: 0.010284, R²: -0.0047
  Directional -> Accuracy: 0.4815, MCC: -0.0889, F1: 0.6216

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.08723 | val 0.10987
  Epoch 020 - train 0.08772 | val 0.11251
  Regression -> MSE: 0.000117, MAE: 0.008927, R²: -0.0075
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.10011 | val 0.14241

[I 2026-02-23 00:22:26,863] Trial 149 finished with value: -0.011432553614579481 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 32, 'learning_rate': 5.737386895458817e-06, 'weight_decay': 1.7620225023100065e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.12973195739674281, 'early_stopping_min_delta': 0.0066247314736280335}. Best is trial 143 with value: -0.011397192428235973.

  Epoch 020 - train 0.09718 | val 0.15870
  Regression -> MSE: 0.000236, MAE: 0.012389, R²: 0.0033
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.09434 | val 0.13457
  Epoch 016 - train 0.09357 | val 0.13868
  Regression -> MSE: 0.000248, MAE: 0.012563, R²: -0.0024
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.08688 | val 0.08330
  Epoch 016 - train 0.08496 | val 0.08827
  Regression -> MSE: 0.000698, MAE: 0.019581, R²: -0.0196
  Directional -> Accuracy: 0.5652, MCC: 0.0782, F1: 0.6667

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.09057 | val 0.13980
  Epoch 016 - train 0.09154 | val 0.13881
  Regression -> MSE: 0.000312, MAE: 0.014418, R²: -0.0060
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.07659 | val 0.14286
  Epoch 016 - train 0.07436 | val 0.15918
  Regression -> MSE: 0.000382, MAE: 0.015121, R²: -0.0926
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.08915 | val 0.08816
  Epoch 016 - train 0.08944 | val 0.08717
  Regression -> MSE: 0.000206, MAE: 0.010389, R²: -0.0122
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.08368 | val 0.16144
  Epoch 016 - train 0.08283 | val 0.16148
  Regression -> MSE: 0.000579, MAE: 0.018561, R²: -0.0424
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.09059 | val 0.10829
  Epoch 016 - train 0.08933 | val 0.10865
  Regression -> MSE: 0.000247, MAE: 0.011920, R²: -0.0080
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.08728 | val 0.11099
  Epoch 016 - train 0.08720 | val 0.11799
  Regression -> MSE: 0.000613, MAE: 0.019554, R²: -0.0265
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.08874 | val 0.10863
  Epoch 016 - train 0.08670 | val 0.10748
  Regression -> MSE: 0.000385, MAE: 0.016074, R²: -0.0046
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.09004 | val 0.11364
  Epoch 016 - train 0.08818 | val 0.11386
  Regression -> MSE: 0.000245, MAE: 0.012327, R²: -0.0146
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.08303 | val 0.12604
  Epoch 016 - train 0.08013 | val 0.12436
  Regression -> MSE: 0.000311, MAE: 0.013770, R²: 0.0005
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.6301

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.08958 | val 0.10706
  Epoch 016 - train 0.08789 | val 0.10968
  Regression -> MSE: 0.000676, MAE: 0.019466, R²: 0.0016
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.09064 | val 0.08783
  Epoch 016 - train 0.08679 | val 0.09485
  Regression -> MSE: 0.000143, MAE: 0.009426, R²: -0.0348
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.08143 | val 0.11347
  Epoch 020 - train 0.08195 | val 0.11060
  Regression -> MSE: 0.000267, MAE: 0.012322, R²: -0.1860
  Directional -> Accuracy: 0.4262, MCC: -0.1731, F1: 0.1860

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.09104 | val 0.17765
  Epoch 016 - train 0.08716 | val 0.18576
  Regression -> MSE: 0.000362, MAE: 0.016070, R²: 0.0012
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.09169 | val 0.09173
  Epoch 016 - train 0.08927 | val 0.09125
  Regression -> MSE: 0.000108, MAE: 0.007984, R²: -0.0016
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.08804 | val 0.15316
  Epoch 016 - train 0.08381 | val 0.16086
  Regression -> MSE: 0.000157, MAE: 0.009526, R²: -0.0049
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.08736 | val 0.09146
  Epoch 016 - train 0.08727 | val 0.09050
  Regression -> MSE: 0.000277, MAE: 0.013280, R²: -0.0171
  Directional -> Accuracy: 0.5789, MCC: -0.0138, F1: 0.7193

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.07974 | val 0.12160
  Epoch 016 - train 0.07999 | val 0.12121
  Regression -> MSE: 0.000157, MAE: 0.008813, R²: -0.0499
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.08857 | val 0.12585
  Epoch 016 - train 0.08962 | val 0.12641
  Regression -> MSE: 0.000229, MAE: 0.010892, R²: -0.0141
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.08913 | val 0.10758
  Epoch 016 - train 0.08939 | val 0.10866
  Regression -> MSE: 0.000144, MAE: 0.008299, R²: -0.0019
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.08947 | val 0.10181
  Epoch 016 - train 0.09191 | val 0.10132
  Regression -> MSE: 0.000185, MAE: 0.010405, R²: -0.1220
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.08969 | val 0.10549
  Epoch 016 - train 0.09076 | val 0.10699
  Regression -> MSE: 0.000086, MAE: 0.007113, R²: -0.0138
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.08820 | val 0.15190
  Epoch 016 - train 0.08775 | val 0.15345
  Regression -> MSE: 0.000213, MAE: 0.011245, R²: -0.0046
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.07975 | val 0.08045
  Epoch 016 - train 0.08133 | val 0.08043
  Regression -> MSE: 0.000094, MAE: 0.008088, R²: -0.0183
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.09017 | val 0.06921
  Epoch 016 - train 0.09192 | val 0.06996
  Regression -> MSE: 0.000103, MAE: 0.008705, R²: -0.0006
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.09126 | val 0.08673
  Epoch 016 - train 0.09039 | val 0.09050
  Regression -> MSE: 0.000240, MAE: 0.012844, R²: -0.0373
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.08659 | val 0.10888
  Epoch 016 - train 0.08728 | val 0.11178
  Regression -> MSE: 0.000173, MAE: 0.007847, R²: -0.0387
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.09073 | val 0.07650
  Epoch 016 - train 0.09271 | val 0.07891
  Regression -> MSE: 0.000239, MAE: 0.011934, R²: -0.0096
  Directional -> Accuracy: 0.4146, MCC: -0.1890, F1: 0.0769

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.09391 | val 0.13436
  Epoch 016 - train 0.09430 | val 0.13381
  Regression -> MSE: 0.000231, MAE: 0.009879, R²: -0.0015
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.09365 | val 0.10947
  Epoch 016 - train 0.08959 | val 0.10863
  Regression -> MSE: 0.000140, MAE: 0.008431, R²: -0.0388
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.08941 | val 0.11217
  Epoch 016 - train 0.08990 | val 0.11648
  Regression -> MSE: 0.000197, MAE: 0.010608, R²: -0.0452
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.07841 | val 0.10957
  Epoch 016 - train 0.07733 | val 0.10918
  Regression -> MSE: 0.000268, MAE: 0.010555, R²: -0.0218
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.08491 | val 0.07870
  Epoch 016 - train 0.08264 | val 0.07910
  Regression -> MSE: 0.000168, MAE: 0.010372, R²: -0.0075
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.08276 | val 0.08935
  Epoch 016 - train 0.08482 | val 0.09483
  Regression -> MSE: 0.000180, MAE: 0.010246, R²: 0.0020
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.08546 | val 0.08378
  Epoch 016 - train 0.08543 | val 0.08344
  Regression -> MSE: 0.000347, MAE: 0.012198, R²: -0.0132
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.09690 | val 0.05885
  Epoch 016 - train 0.09281 | val 0.05835
  Regression -> MSE: 0.000125, MAE: 0.008473, R²: -0.1936
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.09596 | val 0.12091
  Epoch 016 - train 0.08905 | val 0.12033
  Regression -> MSE: 0.000221, MAE: 0.011381, R²: -0.0129
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.08670 | val 0.14639
  Epoch 016 - train 0.08583 | val 0.14722
  Regression -> MSE: 0.000092, MAE: 0.007500, R²: -0.1852
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.08655 | val 0.06908
  Epoch 016 - train 0.08756 | val 0.06774
  Regression -> MSE: 0.000316, MAE: 0.014312, R²: -0.0278
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.09036 | val 0.05687
  Epoch 016 - train 0.09070 | val 0.05531
  Regression -> MSE: 0.000258, MAE: 0.011489, R²: -0.0576
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.08635 | val 0.10447
  Epoch 016 - train 0.08587 | val 0.10448
  Regression -> MSE: 0.000082, MAE: 0.007056, R²: -0.0174
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.09941 | val 0.10669
  Epoch 016 - train 0.09573 | val 0.10699
  Regression -> MSE: 0.000309, MAE: 0.014525, R²: -0.0078
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.08749 | val 0.09722
  Epoch 016 - train 0.08350 | val 0.09673
  Regression -> MSE: 0.000099, MAE: 0.007190, R²: -0.0039
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.09520 | val 0.10441
  Epoch 016 - train 0.09778 | val 0.10809
  Regression -> MSE: 0.000176, MAE: 0.010198, R²: -0.0215
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.08158 | val 0.10106
  Epoch 016 - train 0.08080 | val 0.11089
  Regression -> MSE: 0.000223, MAE: 0.011721, R²: 0.0007
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.08691 | val 0.09634
  Epoch 016 - train 0.08515 | val 0.09811
  Regression -> MSE: 0.000093, MAE: 0.007687, R²: -0.0089
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.09116 | val 0.13542
  Epoch 016 - train 0.09176 | val 0.14016
  Regression -> MSE: 0.000164, MAE: 0.010266, R²: -0.0008
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.08366 | val 0.10848
  Epoch 016 - train 0.08548 | val 0.10972
  Regression -> MSE: 0.000118, MAE: 0.008962, R²: -0.0199
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.08879 | val 0.12065

[I 2026-02-23 00:24:34,807] Trial 150 finished with value: -0.01147823022553641 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 32, 'learning_rate': 5.5920482958464895e-06, 'weight_decay': 2.4661529526919603e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 0.12688747985376178, 'early_stopping_min_delta': 0.006691517209771732}. Best is trial 143 with value: -0.011397192428235973.

  Epoch 016 - train 0.08928 | val 0.12076
  Regression -> MSE: 0.000241, MAE: 0.012327, R²: -0.0162
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.14098 | val 0.28819
  Epoch 020 - train 0.14182 | val 0.28824
  Regression -> MSE: 0.000255, MAE: 0.012835, R²: -0.0288
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.14556 | val 0.12696
  Epoch 020 - train 0.14199 | val 0.13367
  Regression -> MSE: 0.000728, MAE: 0.020071, R²: -0.0640
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.14987 | val 0.22466
  Epoch 020 - train 0.14766 | val 0.23194
  Regression -> MSE: 0.000317, MAE: 0.014486, R²: -0.0215
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.11874 | val 0.14263
  Epoch 020 - train 0.11562 | val 0.14442
  Regression -> MSE: 0.000372, MAE: 0.014951, R²: -0.0642
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.13934 | val 0.14726
  Epoch 020 - train 0.13688 | val 0.15240
  Regression -> MSE: 0.000205, MAE: 0.010310, R²: -0.0075
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.13367 | val 0.26057
  Epoch 020 - train 0.13663 | val 0.27147
  Regression -> MSE: 0.000568, MAE: 0.018311, R²: -0.0240
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.13913 | val 0.17886
  Epoch 020 - train 0.13946 | val 0.17792
  Regression -> MSE: 0.000246, MAE: 0.012101, R²: -0.0011
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.14162 | val 0.18716
  Epoch 020 - train 0.13453 | val 0.17123
  Regression -> MSE: 0.000649, MAE: 0.020026, R²: -0.0862
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.12703 | val 0.17704
  Epoch 020 - train 0.12812 | val 0.17845
  Regression -> MSE: 0.000384, MAE: 0.016130, R²: -0.0003
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.13627 | val 0.18190
  Epoch 020 - train 0.13450 | val 0.17553
  Regression -> MSE: 0.000243, MAE: 0.012132, R²: -0.0070
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.12938 | val 0.19107
  Epoch 020 - train 0.12764 | val 0.19506
  Regression -> MSE: 0.000320, MAE: 0.013575, R²: -0.0285
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.14454 | val 0.16066
  Epoch 020 - train 0.14247 | val 0.16573
  Regression -> MSE: 0.000679, MAE: 0.019564, R²: -0.0023
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.13448 | val 0.14530
  Epoch 020 - train 0.13477 | val 0.17367
  Regression -> MSE: 0.000139, MAE: 0.009182, R²: -0.0036
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.12702 | val 0.18037
  Epoch 020 - train 0.12773 | val 0.18130
  Regression -> MSE: 0.000225, MAE: 0.010693, R²: -0.0006
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.13204 | val 0.27486
  Epoch 020 - train 0.13547 | val 0.27533
  Regression -> MSE: 0.000365, MAE: 0.015974, R²: -0.0086
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.14282 | val 0.14394
  Epoch 020 - train 0.14089 | val 0.14453
  Regression -> MSE: 0.000108, MAE: 0.008073, R²: -0.0025
  Directional -> Accuracy: 0.4571, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.13779 | val 0.22442
  Epoch 020 - train 0.13621 | val 0.23534
  Regression -> MSE: 0.000162, MAE: 0.010158, R²: -0.0373
  Directional -> Accuracy: 0.3898, MCC: -0.2234, F1: 0.4545

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.13751 | val 0.13839
  Epoch 020 - train 0.14027 | val 0.14141
  Regression -> MSE: 0.000275, MAE: 0.013166, R²: -0.0088
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.12755 | val 0.27707
  Epoch 020 - train 0.12646 | val 0.27670
  Regression -> MSE: 0.000153, MAE: 0.008728, R²: -0.0195
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.13868 | val 0.19365
  Epoch 020 - train 0.13993 | val 0.19795
  Regression -> MSE: 0.000227, MAE: 0.010924, R²: -0.0028
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.14311 | val 0.17970
  Epoch 020 - train 0.13690 | val 0.18957
  Regression -> MSE: 0.000144, MAE: 0.008338, R²: -0.0032
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.13225 | val 0.16241
  Epoch 020 - train 0.13361 | val 0.16375
  Regression -> MSE: 0.000175, MAE: 0.010251, R²: -0.0569
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.14402 | val 0.16062
  Epoch 020 - train 0.13690 | val 0.16522
  Regression -> MSE: 0.000089, MAE: 0.007268, R²: -0.0467
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.14766 | val 0.16970
  Epoch 020 - train 0.14594 | val 0.17001
  Regression -> MSE: 0.000215, MAE: 0.011044, R²: -0.0165
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.13362 | val 0.12773
  Epoch 020 - train 0.12751 | val 0.12737
  Regression -> MSE: 0.000094, MAE: 0.008105, R²: -0.0199
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.14308 | val 0.11639
  Epoch 020 - train 0.13654 | val 0.12632
  Regression -> MSE: 0.000115, MAE: 0.009166, R²: -0.1114
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.14042 | val 0.14429
  Epoch 020 - train 0.14347 | val 0.18156
  Regression -> MSE: 0.000239, MAE: 0.012804, R²: -0.0306
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.13195 | val 0.16077
  Epoch 020 - train 0.13168 | val 0.16014
  Regression -> MSE: 0.000183, MAE: 0.008007, R²: -0.0981
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.13971 | val 0.11640
  Epoch 020 - train 0.14111 | val 0.12196
  Regression -> MSE: 0.000239, MAE: 0.011946, R²: -0.0118
  Directional -> Accuracy: 0.4634, MCC: 0.0000, F1: 0.0000

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.13626 | val 0.21706
  Epoch 020 - train 0.13502 | val 0.21548
  Regression -> MSE: 0.000231, MAE: 0.009925, R²: -0.0021
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.14628 | val 0.15818
  Epoch 020 - train 0.14506 | val 0.16056
  Regression -> MSE: 0.000135, MAE: 0.008179, R²: 0.0002
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.14493 | val 0.16853
  Epoch 020 - train 0.14221 | val 0.16893
  Regression -> MSE: 0.000197, MAE: 0.010574, R²: -0.0455
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.12547 | val 0.16919
  Epoch 020 - train 0.12498 | val 0.16886
  Regression -> MSE: 0.000282, MAE: 0.011032, R²: -0.0762
  Directional -> Accuracy: 0.4384, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.13748 | val 0.12216
  Epoch 020 - train 0.12192 | val 0.12682
  Regression -> MSE: 0.000168, MAE: 0.010373, R²: -0.0053
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.13598 | val 0.15618
  Epoch 020 - train 0.12980 | val 0.17242
  Regression -> MSE: 0.000189, MAE: 0.010668, R²: -0.0527
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.13301 | val 0.13166
  Epoch 020 - train 0.12944 | val 0.13161
  Regression -> MSE: 0.000344, MAE: 0.011702, R²: -0.0050
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.14352 | val 0.09207
  Epoch 020 - train 0.14547 | val 0.09274
  Regression -> MSE: 0.000110, MAE: 0.008336, R²: -0.0434
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.14716 | val 0.18961
  Epoch 020 - train 0.14589 | val 0.18698
  Regression -> MSE: 0.000222, MAE: 0.011394, R²: -0.0164
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.14031 | val 0.24002
  Epoch 020 - train 0.13697 | val 0.24259
  Regression -> MSE: 0.000081, MAE: 0.006987, R²: -0.0370
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.13606 | val 0.11677
  Epoch 020 - train 0.13655 | val 0.11182
  Regression -> MSE: 0.000337, MAE: 0.015270, R²: -0.0971
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.16238 | val 0.08657
  Epoch 020 - train 0.15663 | val 0.09361
  Regression -> MSE: 0.000253, MAE: 0.011468, R²: -0.0372
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.15471 | val 0.18747
  Epoch 020 - train 0.15166 | val 0.18645
  Regression -> MSE: 0.000082, MAE: 0.007141, R²: -0.0109
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.13729 | val 0.16819
  Epoch 020 - train 0.13140 | val 0.16698
  Regression -> MSE: 0.000307, MAE: 0.014493, R²: -0.0007
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.14383 | val 0.14655
  Epoch 020 - train 0.14307 | val 0.14784
  Regression -> MSE: 0.000098, MAE: 0.007306, R²: -0.0001
  Directional -> Accuracy: 0.5000, MCC: 0.1676, F1: 0.2667

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.14222 | val 0.16348
  Epoch 020 - train 0.14358 | val 0.17023
  Regression -> MSE: 0.000173, MAE: 0.009948, R²: -0.0075
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.12693 | val 0.15353
  Epoch 020 - train 0.12511 | val 0.16307
  Regression -> MSE: 0.000224, MAE: 0.011747, R²: -0.0051
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.13400 | val 0.15521
  Epoch 020 - train 0.12891 | val 0.15785
  Regression -> MSE: 0.000093, MAE: 0.007686, R²: -0.0071
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.14463 | val 0.21226
  Epoch 020 - train 0.14391 | val 0.21318
  Regression -> MSE: 0.000164, MAE: 0.010269, R²: -0.0015
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.13504 | val 0.20586
  Epoch 020 - train 0.13002 | val 0.24375
  Regression -> MSE: 0.000121, MAE: 0.008981, R²: -0.0475
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.14390 | val 0.18803

[I 2026-02-23 00:27:15,423] Trial 151 finished with value: -0.011483990298472668 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 32, 'learning_rate': 4.780573504191313e-06, 'weight_decay': 1.667876961790204e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.20853785015146728, 'early_stopping_min_delta': 0.007324684756673203}. Best is trial 143 with value: -0.011397192428235973.

  Epoch 020 - train 0.14112 | val 0.18866
  Regression -> MSE: 0.000237, MAE: 0.012400, R²: 0.0012
  Directional -> Accuracy: 0.5410, MCC: 0.1555, F1: 0.6500

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.19399 | val 0.26531
  Epoch 020 - train 0.19125 | val 0.26343
  Regression -> MSE: 0.000248, MAE: 0.012494, R²: -0.0006
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.19069 | val 0.18028
  Epoch 020 - train 0.19148 | val 0.18409
  Regression -> MSE: 0.000693, MAE: 0.019505, R²: -0.0120
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.20076 | val 0.33179
  Epoch 020 - train 0.19684 | val 0.34714
  Regression -> MSE: 0.000313, MAE: 0.014441, R²: -0.0088
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.16784 | val 0.37992
  Epoch 020 - train 0.16378 | val 0.42063
  Regression -> MSE: 0.000376, MAE: 0.015002, R²: -0.0754
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.19107 | val 0.19241
  Epoch 020 - train 0.19137 | val 0.18928
  Regression -> MSE: 0.000204, MAE: 0.010173, R²: -0.0013
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.18432 | val 0.36240
  Epoch 020 - train 0.18038 | val 0.38429
  Regression -> MSE: 0.000550, MAE: 0.018007, R²: 0.0099
  Directional -> Accuracy: 0.5532, MCC: 0.1044, F1: 0.5116

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.19136 | val 0.25586
  Epoch 020 - train 0.19386 | val 0.25548
  Regression -> MSE: 0.000249, MAE: 0.011931, R²: -0.0151
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.19046 | val 0.24847
  Epoch 020 - train 0.18448 | val 0.23593
  Regression -> MSE: 0.000601, MAE: 0.019279, R²: -0.0063
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.18037 | val 0.22783
  Epoch 020 - train 0.18188 | val 0.23891
  Regression -> MSE: 0.000407, MAE: 0.016182, R²: -0.0608
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.19181 | val 0.25214
  Epoch 020 - train 0.19299 | val 0.26013
  Regression -> MSE: 0.000246, MAE: 0.011645, R²: -0.0170
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.17586 | val 0.29758
  Epoch 020 - train 0.17691 | val 0.34538
  Regression -> MSE: 0.000311, MAE: 0.013632, R²: 0.0007
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.20086 | val 0.25988
  Epoch 020 - train 0.19857 | val 0.28071
  Regression -> MSE: 0.000686, MAE: 0.019595, R²: -0.0131
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.19081 | val 0.19928
  Epoch 020 - train 0.17891 | val 0.21098
  Regression -> MSE: 0.000138, MAE: 0.009087, R²: -0.0017
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.17708 | val 0.25710
  Epoch 020 - train 0.17814 | val 0.25500
  Regression -> MSE: 0.000225, MAE: 0.010711, R²: -0.0015
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.18408 | val 0.41940
  Epoch 020 - train 0.19020 | val 0.46271
  Regression -> MSE: 0.000362, MAE: 0.016059, R²: 0.0015
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.20378 | val 0.20065
  Epoch 020 - train 0.19746 | val 0.20040
  Regression -> MSE: 0.000110, MAE: 0.008203, R²: -0.0225
  Directional -> Accuracy: 0.4571, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.18927 | val 0.35657
  Epoch 020 - train 0.18388 | val 0.39600
  Regression -> MSE: 0.000156, MAE: 0.009658, R²: 0.0012
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.19262 | val 0.19543
  Epoch 020 - train 0.19154 | val 0.19686
  Regression -> MSE: 0.000294, MAE: 0.013987, R²: -0.0800
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.16982 | val 0.25631
  Epoch 020 - train 0.17488 | val 0.25470
  Regression -> MSE: 0.000169, MAE: 0.009182, R²: -0.1316
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.20279 | val 0.32409
  Epoch 020 - train 0.19531 | val 0.30893
  Regression -> MSE: 0.000227, MAE: 0.010980, R²: -0.0029
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.18466 | val 0.24115
  Epoch 020 - train 0.18718 | val 0.24514
  Regression -> MSE: 0.000149, MAE: 0.008629, R²: -0.0376
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.18134 | val 0.23171
  Epoch 020 - train 0.18190 | val 0.23196
  Regression -> MSE: 0.000166, MAE: 0.010355, R²: -0.0056
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.20094 | val 0.23464
  Epoch 020 - train 0.19425 | val 0.24396
  Regression -> MSE: 0.000092, MAE: 0.007417, R²: -0.0850
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.18917 | val 0.24335
  Epoch 020 - train 0.18246 | val 0.24582
  Regression -> MSE: 0.000212, MAE: 0.011166, R²: -0.0001
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.17168 | val 0.17171
  Epoch 020 - train 0.17046 | val 0.16234
  Regression -> MSE: 0.000114, MAE: 0.008538, R²: -0.2339
  Directional -> Accuracy: 0.5000, MCC: 0.0996, F1: 0.3000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.19814 | val 0.15108
  Epoch 020 - train 0.19244 | val 0.16000
  Regression -> MSE: 0.000108, MAE: 0.008947, R²: -0.0424
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.20685 | val 0.18584
  Epoch 020 - train 0.19925 | val 0.19262
  Regression -> MSE: 0.000236, MAE: 0.012718, R²: -0.0178
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.18608 | val 0.22249
  Epoch 020 - train 0.18637 | val 0.21540
  Regression -> MSE: 0.000192, MAE: 0.008433, R²: -0.1546
  Directional -> Accuracy: 0.4737, MCC: -0.0339, F1: 0.4643

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.19719 | val 0.16054
  Epoch 020 - train 0.20168 | val 0.20875
  Regression -> MSE: 0.000236, MAE: 0.011860, R²: 0.0011
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.19449 | val 0.30938
  Epoch 020 - train 0.20387 | val 0.32300
  Regression -> MSE: 0.000230, MAE: 0.009862, R²: 0.0005
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.20868 | val 0.27150
  Epoch 020 - train 0.20496 | val 0.32649
  Regression -> MSE: 0.000145, MAE: 0.008727, R²: -0.0725
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.20123 | val 0.25629
  Epoch 020 - train 0.19237 | val 0.26570
  Regression -> MSE: 0.000189, MAE: 0.010390, R²: -0.0052
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.17022 | val 0.22929
  Epoch 020 - train 0.16750 | val 0.22661
  Regression -> MSE: 0.000262, MAE: 0.010585, R²: -0.0006
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.21120 | val 0.18640
  Epoch 020 - train 0.21204 | val 0.21623
  Regression -> MSE: 0.000172, MAE: 0.010401, R²: -0.0301
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.18081 | val 0.19435
  Epoch 020 - train 0.17922 | val 0.23482
  Regression -> MSE: 0.000181, MAE: 0.010270, R²: -0.0030
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.18843 | val 0.18721
  Epoch 020 - train 0.17476 | val 0.18554
  Regression -> MSE: 0.000344, MAE: 0.012013, R²: -0.0034
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.19582 | val 0.12219
  Epoch 020 - train 0.19418 | val 0.14609
  Regression -> MSE: 0.000118, MAE: 0.008359, R²: -0.1222
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.19741 | val 0.26355
  Epoch 020 - train 0.18535 | val 0.26740
  Regression -> MSE: 0.000219, MAE: 0.011217, R²: -0.0024
  Directional -> Accuracy: 0.5263, MCC: 0.0882, F1: 0.6087

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.18521 | val 0.33346
  Epoch 020 - train 0.18055 | val 0.33398
  Regression -> MSE: 0.000089, MAE: 0.007379, R²: -0.1442
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.19185 | val 0.15021
  Epoch 020 - train 0.18839 | val 0.15960
  Regression -> MSE: 0.000319, MAE: 0.014430, R²: -0.0365
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.21276 | val 0.12066
  Epoch 020 - train 0.21086 | val 0.13821
  Regression -> MSE: 0.000254, MAE: 0.011457, R²: -0.0407
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.19117 | val 0.24978
  Epoch 020 - train 0.18567 | val 0.24246
  Regression -> MSE: 0.000081, MAE: 0.007109, R²: -0.0049
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.19449 | val 0.23424
  Epoch 020 - train 0.19209 | val 0.24543
  Regression -> MSE: 0.000332, MAE: 0.014998, R²: -0.0821
  Directional -> Accuracy: 0.4894, MCC: 0.0000, F1: 0.0000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.19230 | val 0.21594
  Epoch 020 - train 0.18942 | val 0.20692
  Regression -> MSE: 0.000100, MAE: 0.007278, R²: -0.0142
  Directional -> Accuracy: 0.5227, MCC: -0.1902, F1: 0.6866

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.19839 | val 0.23114
  Epoch 020 - train 0.21097 | val 0.22702
  Regression -> MSE: 0.000173, MAE: 0.009853, R²: -0.0095
  Directional -> Accuracy: 0.3878, MCC: -0.0861, F1: 0.5161

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.18262 | val 0.25251
  Epoch 020 - train 0.18027 | val 0.27469
  Regression -> MSE: 0.000223, MAE: 0.011776, R²: -0.0021
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.18387 | val 0.21624
  Epoch 020 - train 0.18304 | val 0.22591
  Regression -> MSE: 0.000093, MAE: 0.007658, R²: -0.0101
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.20693 | val 0.30043
  Epoch 020 - train 0.20077 | val 0.30739
  Regression -> MSE: 0.000164, MAE: 0.010261, R²: -0.0008
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.19114 | val 0.26915
  Epoch 020 - train 0.18907 | val 0.27729
  Regression -> MSE: 0.000119, MAE: 0.008975, R²: -0.0244
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.18532 | val 0.26761

[I 2026-02-23 00:29:59,718] Trial 152 finished with value: -0.01146333258957475 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 32, 'learning_rate': 7.000134824986896e-06, 'weight_decay': 9.925601093911322e-06, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.31170661805535854, 'early_stopping_min_delta': 0.006111150298087423}. Best is trial 143 with value: -0.011397192428235973.

  Epoch 020 - train 0.18613 | val 0.27312
  Regression -> MSE: 0.000242, MAE: 0.012353, R²: -0.0204
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.20390 | val 0.26863
  Epoch 020 - train 0.20900 | val 0.26801
  Regression -> MSE: 0.000252, MAE: 0.012820, R²: -0.0166
  Directional -> Accuracy: 0.4286, MCC: -0.1166, F1: 0.5769

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.20344 | val 0.18565
  Epoch 020 - train 0.20723 | val 0.19907
  Regression -> MSE: 0.000731, MAE: 0.020102, R²: -0.0683
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.19692 | val 0.33297
  Epoch 020 - train 0.20232 | val 0.33376
  Regression -> MSE: 0.000324, MAE: 0.014554, R²: -0.0459
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.16569 | val 0.18886
  Epoch 020 - train 0.16414 | val 0.18327
  Regression -> MSE: 0.000358, MAE: 0.014723, R²: -0.0239
  Directional -> Accuracy: 0.4800, MCC: 0.0969, F1: 0.1333

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.20595 | val 0.20379
  Epoch 020 - train 0.19957 | val 0.20142
  Regression -> MSE: 0.000205, MAE: 0.010293, R²: -0.0066
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.19056 | val 0.38391
  Epoch 020 - train 0.19427 | val 0.37579
  Regression -> MSE: 0.000584, MAE: 0.018627, R²: -0.0523
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.19970 | val 0.24399
  Epoch 020 - train 0.20065 | val 0.24289
  Regression -> MSE: 0.000248, MAE: 0.012297, R²: -0.0090
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.18407 | val 0.25305
  Epoch 020 - train 0.19165 | val 0.25534
  Regression -> MSE: 0.000614, MAE: 0.019565, R²: -0.0274
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.18846 | val 0.23012
  Epoch 020 - train 0.18528 | val 0.22902
  Regression -> MSE: 0.000411, MAE: 0.016255, R²: -0.0707
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.19908 | val 0.28350
  Epoch 020 - train 0.19595 | val 0.28224
  Regression -> MSE: 0.000242, MAE: 0.011763, R²: -0.0014
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.18222 | val 0.27924
  Epoch 020 - train 0.18069 | val 0.27695
  Regression -> MSE: 0.000324, MAE: 0.013609, R²: -0.0436
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.20857 | val 0.26530
  Epoch 020 - train 0.20101 | val 0.29506
  Regression -> MSE: 0.000681, MAE: 0.019508, R²: -0.0049
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.20367 | val 0.20098
  Epoch 020 - train 0.20692 | val 0.22055
  Regression -> MSE: 0.000142, MAE: 0.009363, R²: -0.0244
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.18304 | val 0.25089
  Epoch 020 - train 0.18454 | val 0.25241
  Regression -> MSE: 0.000224, MAE: 0.010624, R²: 0.0021
  Directional -> Accuracy: 0.5082, MCC: 0.0455, F1: 0.2105

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.19887 | val 0.42067
  Epoch 020 - train 0.18911 | val 0.43307
  Regression -> MSE: 0.000367, MAE: 0.015961, R²: -0.0123
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.21358 | val 0.22064
  Epoch 020 - train 0.21040 | val 0.22494
  Regression -> MSE: 0.000112, MAE: 0.007954, R²: -0.0344
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.19814 | val 0.32706
  Epoch 020 - train 0.19543 | val 0.32987
  Regression -> MSE: 0.000157, MAE: 0.009763, R²: -0.0040
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.21397 | val 0.20703
  Epoch 020 - train 0.20751 | val 0.21159
  Regression -> MSE: 0.000290, MAE: 0.013832, R²: -0.0666
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.18113 | val 0.26875
  Epoch 020 - train 0.17951 | val 0.26892
  Regression -> MSE: 0.000160, MAE: 0.008888, R²: -0.0674
  Directional -> Accuracy: 0.4769, MCC: -0.0233, F1: 0.4848

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.20560 | val 0.29498
  Epoch 020 - train 0.20789 | val 0.29256
  Regression -> MSE: 0.000227, MAE: 0.010955, R²: -0.0025
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.19888 | val 0.26133
  Epoch 020 - train 0.19866 | val 0.29737
  Regression -> MSE: 0.000153, MAE: 0.008821, R²: -0.0685
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.19495 | val 0.23061
  Epoch 020 - train 0.20084 | val 0.23181
  Regression -> MSE: 0.000167, MAE: 0.010319, R²: -0.0105
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.21439 | val 0.23636
  Epoch 020 - train 0.22060 | val 0.25021
  Regression -> MSE: 0.000089, MAE: 0.007241, R²: -0.0414
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.20016 | val 0.25743
  Epoch 020 - train 0.20425 | val 0.26056
  Regression -> MSE: 0.000217, MAE: 0.011045, R²: -0.0240
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.19495 | val 0.19567
  Epoch 020 - train 0.19298 | val 0.19758
  Regression -> MSE: 0.000093, MAE: 0.008115, R²: -0.0135
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.19056 | val 0.15138
  Epoch 020 - train 0.20087 | val 0.15424
  Regression -> MSE: 0.000105, MAE: 0.008863, R²: -0.0228
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.19727 | val 0.18595
  Epoch 020 - train 0.19662 | val 0.18616
  Regression -> MSE: 0.000234, MAE: 0.012649, R²: -0.0106
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.18815 | val 0.21884
  Epoch 020 - train 0.19546 | val 0.21566
  Regression -> MSE: 0.000203, MAE: 0.008645, R²: -0.2168
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.20572 | val 0.17326
  Epoch 020 - train 0.19754 | val 0.21507
  Regression -> MSE: 0.000237, MAE: 0.011870, R²: -0.0007
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.20018 | val 0.34249
  Epoch 020 - train 0.19270 | val 0.37473
  Regression -> MSE: 0.000234, MAE: 0.010053, R²: -0.0133
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.20333 | val 0.23467
  Epoch 020 - train 0.19603 | val 0.25121
  Regression -> MSE: 0.000135, MAE: 0.008173, R²: -0.0031
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.21482 | val 0.25956
  Epoch 020 - train 0.21663 | val 0.26871
  Regression -> MSE: 0.000198, MAE: 0.010645, R²: -0.0518
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.18246 | val 0.26700
  Epoch 020 - train 0.17701 | val 0.26371
  Regression -> MSE: 0.000265, MAE: 0.010533, R²: -0.0137
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.18713 | val 0.16428
  Epoch 020 - train 0.19353 | val 0.16406
  Regression -> MSE: 0.000167, MAE: 0.010365, R²: 0.0006
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.18471 | val 0.19836
  Epoch 020 - train 0.18420 | val 0.20628
  Regression -> MSE: 0.000181, MAE: 0.010263, R²: -0.0033
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.21530 | val 0.20009
  Epoch 020 - train 0.20370 | val 0.19855
  Regression -> MSE: 0.000343, MAE: 0.011850, R²: -0.0020
  Directional -> Accuracy: 0.4627, MCC: -0.0306, F1: 0.4000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.20674 | val 0.12423
  Epoch 020 - train 0.21190 | val 0.13020
  Regression -> MSE: 0.000115, MAE: 0.008344, R²: -0.0980
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.19910 | val 0.26805
  Epoch 020 - train 0.19912 | val 0.26571
  Regression -> MSE: 0.000219, MAE: 0.011308, R²: -0.0027
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.20107 | val 0.34774
  Epoch 020 - train 0.20514 | val 0.36358
  Regression -> MSE: 0.000098, MAE: 0.007719, R²: -0.2619
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.19247 | val 0.15564
  Epoch 020 - train 0.18329 | val 0.16086
  Regression -> MSE: 0.000320, MAE: 0.014505, R²: -0.0396
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.22714 | val 0.11539
  Epoch 020 - train 0.21434 | val 0.12110
  Regression -> MSE: 0.000248, MAE: 0.011505, R²: -0.0160
  Directional -> Accuracy: 0.5789, MCC: 0.2485, F1: 0.7143

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.19269 | val 0.24165
  Epoch 020 - train 0.19584 | val 0.24002
  Regression -> MSE: 0.000081, MAE: 0.007053, R²: -0.0053
  Directional -> Accuracy: 0.5333, MCC: 0.1332, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.20079 | val 0.25471
  Epoch 020 - train 0.20355 | val 0.29556
  Regression -> MSE: 0.000306, MAE: 0.014487, R²: 0.0014
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.19003 | val 0.22143
  Epoch 020 - train 0.19052 | val 0.23049
  Regression -> MSE: 0.000099, MAE: 0.007198, R²: -0.0034
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.22193 | val 0.24205
  Epoch 020 - train 0.21861 | val 0.25729
  Regression -> MSE: 0.000172, MAE: 0.009803, R²: -0.0025
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.18424 | val 0.28105
  Epoch 020 - train 0.18524 | val 0.34072
  Regression -> MSE: 0.000233, MAE: 0.012145, R²: -0.0457
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.20297 | val 0.29333
  Epoch 020 - train 0.20437 | val 0.32399
  Regression -> MSE: 0.000093, MAE: 0.007679, R²: -0.0051
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.21341 | val 0.31426
  Epoch 020 - train 0.21254 | val 0.32247
  Regression -> MSE: 0.000164, MAE: 0.010259, R²: -0.0012
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.19934 | val 0.27628
  Epoch 020 - train 0.19783 | val 0.29044
  Regression -> MSE: 0.000122, MAE: 0.008990, R²: -0.0482
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.20251 | val 0.28861

[I 2026-02-23 00:32:41,297] Trial 153 finished with value: -0.01148477970189481 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 32, 'learning_rate': 1.9149650140110146e-06, 'weight_decay': 9.477572058866576e-06, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.3232172253529486, 'early_stopping_min_delta': 0.007024534803287229}. Best is trial 143 with value: -0.011397192428235973.

  Epoch 020 - train 0.20405 | val 0.29032
  Regression -> MSE: 0.000243, MAE: 0.012338, R²: -0.0234
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.10317 | val 0.14769
  Epoch 020 - train 0.10439 | val 0.14740
  Regression -> MSE: 0.000251, MAE: 0.012696, R²: -0.0143
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.10634 | val 0.09760
  Epoch 020 - train 0.10228 | val 0.11019
  Regression -> MSE: 0.000698, MAE: 0.019584, R²: -0.0201
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.11951 | val 0.17140
  Epoch 020 - train 0.11438 | val 0.17970
  Regression -> MSE: 0.000311, MAE: 0.014463, R²: -0.0009
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.08454 | val 0.09371
  Epoch 020 - train 0.08681 | val 0.10240
  Regression -> MSE: 0.000350, MAE: 0.014611, R²: -0.0026
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.10875 | val 0.09958
  Epoch 020 - train 0.10975 | val 0.09818
  Regression -> MSE: 0.000205, MAE: 0.010053, R²: -0.0090
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.10135 | val 0.19199
  Epoch 020 - train 0.09776 | val 0.19279
  Regression -> MSE: 0.000570, MAE: 0.018374, R²: -0.0273
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.10702 | val 0.13100
  Epoch 020 - train 0.10473 | val 0.12834
  Regression -> MSE: 0.000249, MAE: 0.012409, R²: -0.0139
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.10249 | val 0.14397
  Epoch 020 - train 0.10143 | val 0.16048
  Regression -> MSE: 0.000639, MAE: 0.020067, R²: -0.0701
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.09970 | val 0.12459
  Epoch 020 - train 0.09584 | val 0.12319
  Regression -> MSE: 0.000389, MAE: 0.016016, R²: -0.0150
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.10876 | val 0.14231
  Epoch 020 - train 0.11012 | val 0.15020
  Regression -> MSE: 0.000244, MAE: 0.011663, R²: -0.0123
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.09622 | val 0.15541
  Epoch 020 - train 0.09744 | val 0.17712
  Regression -> MSE: 0.000311, MAE: 0.013651, R²: 0.0004
  Directional -> Accuracy: 0.6000, MCC: 0.2274, F1: 0.2857

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.10556 | val 0.12224
  Epoch 020 - train 0.10831 | val 0.12265
  Regression -> MSE: 0.000681, MAE: 0.019621, R²: -0.0057
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.10752 | val 0.11008
  Epoch 020 - train 0.10471 | val 0.12278
  Regression -> MSE: 0.000139, MAE: 0.009206, R²: -0.0046
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.09348 | val 0.14330
  Epoch 020 - train 0.09537 | val 0.14659
  Regression -> MSE: 0.000226, MAE: 0.010708, R²: -0.0050
  Directional -> Accuracy: 0.4098, MCC: -0.1882, F1: 0.4706

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.10761 | val 0.21726
  Epoch 020 - train 0.10834 | val 0.23781
  Regression -> MSE: 0.000364, MAE: 0.016265, R²: -0.0048
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.10795 | val 0.11059
  Epoch 020 - train 0.10578 | val 0.10955
  Regression -> MSE: 0.000108, MAE: 0.008059, R²: -0.0029
  Directional -> Accuracy: 0.4571, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.09933 | val 0.18037
  Epoch 020 - train 0.09887 | val 0.19105
  Regression -> MSE: 0.000156, MAE: 0.009587, R²: -0.0028
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.10451 | val 0.10401
  Epoch 020 - train 0.10449 | val 0.10638
  Regression -> MSE: 0.000272, MAE: 0.012934, R²: -0.0010
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.09721 | val 0.13776
  Epoch 020 - train 0.09494 | val 0.13811
  Regression -> MSE: 0.000162, MAE: 0.008989, R²: -0.0856
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.10289 | val 0.14240
  Epoch 020 - train 0.10148 | val 0.13953
  Regression -> MSE: 0.000228, MAE: 0.010863, R²: -0.0076
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.11265 | val 0.12720
  Epoch 020 - train 0.10856 | val 0.12799
  Regression -> MSE: 0.000156, MAE: 0.008930, R²: -0.0856
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.09780 | val 0.12742
  Epoch 020 - train 0.09437 | val 0.12901
  Regression -> MSE: 0.000165, MAE: 0.010483, R²: 0.0035
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.10693 | val 0.12467
  Epoch 020 - train 0.10546 | val 0.12372
  Regression -> MSE: 0.000085, MAE: 0.007053, R²: -0.0032
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.10848 | val 0.16335
  Epoch 020 - train 0.10094 | val 0.18704
  Regression -> MSE: 0.000212, MAE: 0.011106, R²: 0.0005
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.10018 | val 0.09403
  Epoch 020 - train 0.09361 | val 0.09161
  Regression -> MSE: 0.000094, MAE: 0.008115, R²: -0.0266
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.10544 | val 0.08602
  Epoch 020 - train 0.10635 | val 0.09549
  Regression -> MSE: 0.000111, MAE: 0.009056, R²: -0.0748
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.10827 | val 0.09819
  Epoch 020 - train 0.10892 | val 0.09990
  Regression -> MSE: 0.000232, MAE: 0.012513, R²: -0.0002
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.10227 | val 0.12919
  Epoch 020 - train 0.09916 | val 0.13239
  Regression -> MSE: 0.000184, MAE: 0.008048, R²: -0.1050
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.10794 | val 0.09083
  Epoch 020 - train 0.10889 | val 0.09056
  Regression -> MSE: 0.000238, MAE: 0.011935, R²: -0.0072
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.10466 | val 0.15962
  Epoch 020 - train 0.10494 | val 0.15832
  Regression -> MSE: 0.000231, MAE: 0.009899, R²: -0.0019
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.11136 | val 0.11753
  Epoch 020 - train 0.10615 | val 0.11467
  Regression -> MSE: 0.000138, MAE: 0.008279, R²: -0.0203
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.10486 | val 0.12949
  Epoch 020 - train 0.10185 | val 0.13401
  Regression -> MSE: 0.000195, MAE: 0.010512, R²: -0.0341
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.09275 | val 0.12783
  Epoch 020 - train 0.09437 | val 0.12504
  Regression -> MSE: 0.000276, MAE: 0.010795, R²: -0.0521
  Directional -> Accuracy: 0.4384, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.10181 | val 0.08688
  Epoch 020 - train 0.09881 | val 0.08510
  Regression -> MSE: 0.000166, MAE: 0.010365, R²: 0.0030
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.09730 | val 0.10729
  Epoch 020 - train 0.09869 | val 0.11169
  Regression -> MSE: 0.000181, MAE: 0.010342, R²: -0.0036
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.09733 | val 0.09726
  Epoch 020 - train 0.09542 | val 0.09780
  Regression -> MSE: 0.000344, MAE: 0.011711, R²: -0.0035
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.11179 | val 0.06747
  Epoch 020 - train 0.10875 | val 0.06752
  Regression -> MSE: 0.000117, MAE: 0.008346, R²: -0.1088
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.10300 | val 0.14881
  Epoch 020 - train 0.10267 | val 0.15616
  Regression -> MSE: 0.000219, MAE: 0.011284, R²: -0.0014
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.10450 | val 0.17638
  Epoch 020 - train 0.10101 | val 0.18922
  Regression -> MSE: 0.000087, MAE: 0.007290, R²: -0.1177
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.10338 | val 0.09182
  Epoch 020 - train 0.10393 | val 0.08818
  Regression -> MSE: 0.000347, MAE: 0.015601, R²: -0.1292
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.10880 | val 0.06279
  Epoch 020 - train 0.10638 | val 0.06404
  Regression -> MSE: 0.000251, MAE: 0.011517, R²: -0.0277
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.09903 | val 0.13012
  Epoch 020 - train 0.09982 | val 0.12915
  Regression -> MSE: 0.000083, MAE: 0.007041, R²: -0.0318
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.10098 | val 0.12312
  Epoch 020 - train 0.10585 | val 0.13114
  Regression -> MSE: 0.000309, MAE: 0.014525, R²: -0.0080
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.10228 | val 0.10700
  Epoch 020 - train 0.09949 | val 0.10614
  Regression -> MSE: 0.000098, MAE: 0.007342, R²: -0.0007
  Directional -> Accuracy: 0.4318, MCC: 0.0000, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.10994 | val 0.12206
  Epoch 020 - train 0.11059 | val 0.13278
  Regression -> MSE: 0.000172, MAE: 0.009771, R²: -0.0015
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.10252 | val 0.11939
  Epoch 020 - train 0.09885 | val 0.12186
  Regression -> MSE: 0.000227, MAE: 0.011880, R²: -0.0199
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.10383 | val 0.11903
  Epoch 020 - train 0.10162 | val 0.11980
  Regression -> MSE: 0.000096, MAE: 0.007866, R²: -0.0372
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.11012 | val 0.16917
  Epoch 020 - train 0.10913 | val 0.17505
  Regression -> MSE: 0.000166, MAE: 0.010266, R²: -0.0118
  Directional -> Accuracy: 0.4815, MCC: 0.0000, F1: 0.0000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.11115 | val 0.12733
  Epoch 020 - train 0.10449 | val 0.12735
  Regression -> MSE: 0.000128, MAE: 0.009058, R²: -0.1007
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.10579 | val 0.14144

[I 2026-02-23 00:35:29,519] Trial 154 finished with value: -0.011462878342163587 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.30000000000000004, 'batch_size': 32, 'learning_rate': 5.98166725220311e-06, 'weight_decay': 1.8163758530976944e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.1504791003952474, 'early_stopping_min_delta': 0.0061522252681734104}. Best is trial 143 with value: -0.011397192428235973.

  Epoch 020 - train 0.10076 | val 0.13841
  Regression -> MSE: 0.000237, MAE: 0.012394, R²: -0.0013
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.08149 | val 0.10991
  Epoch 020 - train 0.08186 | val 0.10957
  Regression -> MSE: 0.000251, MAE: 0.012693, R²: -0.0143
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.08366 | val 0.07839
  Epoch 020 - train 0.08394 | val 0.07858
  Regression -> MSE: 0.000698, MAE: 0.019569, R²: -0.0189
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.09254 | val 0.13393
  Epoch 020 - train 0.08848 | val 0.13530
  Regression -> MSE: 0.000316, MAE: 0.014469, R²: -0.0192
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.07765 | val 0.07352
  Epoch 020 - train 0.07146 | val 0.08034
  Regression -> MSE: 0.000352, MAE: 0.014608, R²: -0.0074
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.08321 | val 0.08441
  Epoch 020 - train 0.07952 | val 0.08543
  Regression -> MSE: 0.000204, MAE: 0.010134, R²: -0.0027
  Directional -> Accuracy: 0.4902, MCC: 0.0466, F1: 0.1875

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.07756 | val 0.15118
  Epoch 020 - train 0.07624 | val 0.15286
  Regression -> MSE: 0.000565, MAE: 0.018245, R²: -0.0178
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.08683 | val 0.10095
  Epoch 020 - train 0.08147 | val 0.10036
  Regression -> MSE: 0.000250, MAE: 0.011936, R²: -0.0189
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.08392 | val 0.11763
  Epoch 020 - train 0.08275 | val 0.14059
  Regression -> MSE: 0.000639, MAE: 0.020052, R²: -0.0690
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.08723 | val 0.10325
  Epoch 020 - train 0.08538 | val 0.10285
  Regression -> MSE: 0.000387, MAE: 0.016171, R²: -0.0088
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.08432 | val 0.10583
  Epoch 020 - train 0.08348 | val 0.10673
  Regression -> MSE: 0.000243, MAE: 0.012136, R²: -0.0063
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.07878 | val 0.12769
  Epoch 020 - train 0.07908 | val 0.12927
  Regression -> MSE: 0.000312, MAE: 0.013809, R²: -0.0030
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.6301

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.08759 | val 0.10075
  Epoch 020 - train 0.08637 | val 0.10481
  Regression -> MSE: 0.000685, MAE: 0.019820, R²: -0.0113
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.08651 | val 0.08241
  Epoch 020 - train 0.08051 | val 0.08362
  Regression -> MSE: 0.000140, MAE: 0.009287, R²: -0.0136
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.08198 | val 0.10631
  Epoch 020 - train 0.08049 | val 0.10625
  Regression -> MSE: 0.000225, MAE: 0.010711, R²: -0.0006
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.08798 | val 0.17416
  Epoch 020 - train 0.08518 | val 0.18463
  Regression -> MSE: 0.000364, MAE: 0.016280, R²: -0.0060
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.09044 | val 0.09598
  Epoch 020 - train 0.08960 | val 0.09536
  Regression -> MSE: 0.000108, MAE: 0.008044, R²: -0.0021
  Directional -> Accuracy: 0.4571, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.08715 | val 0.15909
  Epoch 020 - train 0.08561 | val 0.16833
  Regression -> MSE: 0.000156, MAE: 0.009593, R²: -0.0021
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.08447 | val 0.08821
  Epoch 020 - train 0.08658 | val 0.09028
  Regression -> MSE: 0.000293, MAE: 0.013936, R²: -0.0762
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.08046 | val 0.10823
  Epoch 020 - train 0.07611 | val 0.10755
  Regression -> MSE: 0.000151, MAE: 0.008764, R²: -0.0083
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.08692 | val 0.11422
  Epoch 020 - train 0.08662 | val 0.11428
  Regression -> MSE: 0.000247, MAE: 0.011204, R²: -0.0931
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.08665 | val 0.10704
  Epoch 020 - train 0.08238 | val 0.11157
  Regression -> MSE: 0.000144, MAE: 0.008351, R²: -0.0038
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.07996 | val 0.09434
  Epoch 020 - train 0.07993 | val 0.09500
  Regression -> MSE: 0.000183, MAE: 0.010365, R²: -0.1083
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.08969 | val 0.10844
  Epoch 020 - train 0.08927 | val 0.11050
  Regression -> MSE: 0.000093, MAE: 0.007444, R²: -0.0921
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.09134 | val 0.12562
  Epoch 020 - train 0.08500 | val 0.11711
  Regression -> MSE: 0.000215, MAE: 0.011485, R²: -0.0165
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.07569 | val 0.07356
  Epoch 020 - train 0.07489 | val 0.07201
  Regression -> MSE: 0.000095, MAE: 0.008094, R²: -0.0303
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.08822 | val 0.06495
  Epoch 020 - train 0.08735 | val 0.06813
  Regression -> MSE: 0.000104, MAE: 0.008789, R²: -0.0089
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.08638 | val 0.08092
  Epoch 020 - train 0.08450 | val 0.09021
  Regression -> MSE: 0.000232, MAE: 0.012587, R²: -0.0030
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.08096 | val 0.09572
  Epoch 020 - train 0.08076 | val 0.09448
  Regression -> MSE: 0.000173, MAE: 0.007863, R²: -0.0420
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.08427 | val 0.07150
  Epoch 020 - train 0.08320 | val 0.07307
  Regression -> MSE: 0.000237, MAE: 0.011862, R²: -0.0011
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.08635 | val 0.12759
  Epoch 020 - train 0.08504 | val 0.13071
  Regression -> MSE: 0.000231, MAE: 0.009865, R²: -0.0011
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.08487 | val 0.10044
  Epoch 020 - train 0.08387 | val 0.09862
  Regression -> MSE: 0.000138, MAE: 0.008293, R²: -0.0187
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.08387 | val 0.10636
  Epoch 020 - train 0.08508 | val 0.10874
  Regression -> MSE: 0.000193, MAE: 0.010413, R²: -0.0235
  Directional -> Accuracy: 0.5000, MCC: 0.0097, F1: 0.4898

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.07612 | val 0.09066
  Epoch 020 - train 0.07479 | val 0.08951
  Regression -> MSE: 0.000299, MAE: 0.011702, R²: -0.1422
  Directional -> Accuracy: 0.5479, MCC: 0.1713, F1: 0.4590

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.08297 | val 0.07071
  Epoch 020 - train 0.08079 | val 0.07146
  Regression -> MSE: 0.000167, MAE: 0.010371, R²: -0.0018
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.07365 | val 0.08441
  Epoch 020 - train 0.07583 | val 0.08863
  Regression -> MSE: 0.000182, MAE: 0.010384, R²: -0.0091
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.07960 | val 0.07783
  Epoch 020 - train 0.07647 | val 0.07795
  Regression -> MSE: 0.000344, MAE: 0.011692, R²: -0.0045
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.08818 | val 0.05581
  Epoch 020 - train 0.08686 | val 0.05862
  Regression -> MSE: 0.000120, MAE: 0.008363, R²: -0.1455
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.09028 | val 0.12984
  Epoch 020 - train 0.08819 | val 0.13314
  Regression -> MSE: 0.000224, MAE: 0.011449, R²: -0.0269
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.09071 | val 0.14968
  Epoch 020 - train 0.08550 | val 0.16730
  Regression -> MSE: 0.000081, MAE: 0.007013, R²: -0.0439
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.08160 | val 0.07133
  Epoch 020 - train 0.08355 | val 0.07332
  Regression -> MSE: 0.000336, MAE: 0.015224, R²: -0.0918
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.09070 | val 0.05198
  Epoch 020 - train 0.09066 | val 0.05386
  Regression -> MSE: 0.000248, MAE: 0.011509, R²: -0.0192
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.08124 | val 0.10172
  Epoch 020 - train 0.07633 | val 0.10163
  Regression -> MSE: 0.000081, MAE: 0.007064, R²: -0.0006
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.08819 | val 0.10468
  Epoch 020 - train 0.08481 | val 0.10416
  Regression -> MSE: 0.000307, MAE: 0.014472, R²: -0.0018
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.08118 | val 0.09112
  Epoch 020 - train 0.08066 | val 0.09180
  Regression -> MSE: 0.000099, MAE: 0.007181, R²: -0.0063
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.08810 | val 0.09834
  Epoch 020 - train 0.08887 | val 0.10185
  Regression -> MSE: 0.000176, MAE: 0.010258, R²: -0.0259
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.07538 | val 0.09344
  Epoch 020 - train 0.07629 | val 0.09704
  Regression -> MSE: 0.000223, MAE: 0.011765, R²: -0.0015
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.08366 | val 0.08957
  Epoch 020 - train 0.08357 | val 0.09095
  Regression -> MSE: 0.000092, MAE: 0.007645, R²: -0.0020
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.08873 | val 0.13023
  Epoch 020 - train 0.08940 | val 0.13054
  Regression -> MSE: 0.000168, MAE: 0.010317, R²: -0.0245
  Directional -> Accuracy: 0.4815, MCC: 0.0000, F1: 0.0000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.08206 | val 0.10468
  Epoch 020 - train 0.08247 | val 0.10397
  Regression -> MSE: 0.000117, MAE: 0.008930, R²: -0.0068
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.08299 | val 0.11129

[I 2026-02-23 00:38:13,246] Trial 155 finished with value: -0.0114910592244397 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.30000000000000004, 'batch_size': 32, 'learning_rate': 6.301589832095303e-06, 'weight_decay': 3.255344383290146e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.11872639283741517, 'early_stopping_min_delta': 0.005952581532673928}. Best is trial 143 with value: -0.011397192428235973.

  Epoch 020 - train 0.08437 | val 0.11471
  Regression -> MSE: 0.000239, MAE: 0.012342, R²: -0.0096
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.11127 | val 0.14960
  Epoch 020 - train 0.11346 | val 0.15005
  Regression -> MSE: 0.000251, MAE: 0.012666, R²: -0.0120
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.11355 | val 0.10644
  Epoch 020 - train 0.11677 | val 0.10933
  Regression -> MSE: 0.000707, MAE: 0.019730, R²: -0.0324
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.11401 | val 0.18632
  Epoch 020 - train 0.12090 | val 0.18839
  Regression -> MSE: 0.000319, MAE: 0.014511, R²: -0.0282
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.09919 | val 0.10392
  Epoch 020 - train 0.09731 | val 0.10654
  Regression -> MSE: 0.000362, MAE: 0.014778, R²: -0.0352
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.12267 | val 0.11943
  Epoch 020 - train 0.11865 | val 0.11959
  Regression -> MSE: 0.000209, MAE: 0.010203, R²: -0.0259
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.11074 | val 0.21245
  Epoch 020 - train 0.10743 | val 0.21937
  Regression -> MSE: 0.000572, MAE: 0.018412, R²: -0.0302
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.11609 | val 0.14365
  Epoch 020 - train 0.11375 | val 0.14491
  Regression -> MSE: 0.000246, MAE: 0.011929, R²: -0.0016
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.11571 | val 0.14317
  Epoch 020 - train 0.11362 | val 0.13145
  Regression -> MSE: 0.000606, MAE: 0.019358, R²: -0.0150
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.10936 | val 0.13439
  Epoch 020 - train 0.10882 | val 0.13565
  Regression -> MSE: 0.000404, MAE: 0.016119, R²: -0.0524
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.12231 | val 0.17613
  Epoch 020 - train 0.11824 | val 0.18237
  Regression -> MSE: 0.000245, MAE: 0.011646, R²: -0.0139
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.11230 | val 0.17603
  Epoch 020 - train 0.11076 | val 0.19832
  Regression -> MSE: 0.000311, MAE: 0.013711, R²: -0.0010
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.6301

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.11556 | val 0.13583
  Epoch 020 - train 0.11933 | val 0.14000
  Regression -> MSE: 0.000678, MAE: 0.019524, R²: -0.0008
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.11533 | val 0.12408
  Epoch 020 - train 0.11499 | val 0.13866
  Regression -> MSE: 0.000138, MAE: 0.009037, R²: -0.0011
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.10362 | val 0.14933
  Epoch 020 - train 0.10276 | val 0.15301
  Regression -> MSE: 0.000217, MAE: 0.010596, R²: 0.0367
  Directional -> Accuracy: 0.5246, MCC: 0.0474, F1: 0.6234

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.11162 | val 0.22977
  Epoch 020 - train 0.11375 | val 0.23266
  Regression -> MSE: 0.000366, MAE: 0.015962, R²: -0.0106
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.11956 | val 0.13273
  Epoch 020 - train 0.11667 | val 0.13116
  Regression -> MSE: 0.000109, MAE: 0.008090, R²: -0.0078
  Directional -> Accuracy: 0.4571, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.11122 | val 0.21176
  Epoch 020 - train 0.11208 | val 0.22474
  Regression -> MSE: 0.000156, MAE: 0.009705, R²: -0.0009
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.11558 | val 0.12486
  Epoch 020 - train 0.11593 | val 0.12713
  Regression -> MSE: 0.000281, MAE: 0.013500, R²: -0.0336
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.10151 | val 0.15009
  Epoch 020 - train 0.10406 | val 0.15079
  Regression -> MSE: 0.000167, MAE: 0.009106, R²: -0.1141
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.11674 | val 0.16391
  Epoch 020 - train 0.11313 | val 0.16337
  Regression -> MSE: 0.000233, MAE: 0.010947, R²: -0.0279
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.11942 | val 0.14067
  Epoch 020 - train 0.11992 | val 0.14345
  Regression -> MSE: 0.000153, MAE: 0.008820, R²: -0.0671
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.11065 | val 0.13460
  Epoch 020 - train 0.10522 | val 0.13340
  Regression -> MSE: 0.000166, MAE: 0.010562, R²: -0.0047
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.12712 | val 0.14782
  Epoch 020 - train 0.12520 | val 0.14921
  Regression -> MSE: 0.000091, MAE: 0.007337, R²: -0.0654
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.11408 | val 0.15342
  Epoch 020 - train 0.11329 | val 0.16493
  Regression -> MSE: 0.000214, MAE: 0.011378, R²: -0.0082
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.10223 | val 0.10586
  Epoch 020 - train 0.10214 | val 0.10717
  Regression -> MSE: 0.000095, MAE: 0.008102, R²: -0.0295
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.11593 | val 0.09181
  Epoch 020 - train 0.11995 | val 0.08789
  Regression -> MSE: 0.000110, MAE: 0.009040, R²: -0.0689
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.12681 | val 0.10780
  Epoch 020 - train 0.12579 | val 0.11258
  Regression -> MSE: 0.000235, MAE: 0.012674, R²: -0.0138
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.11469 | val 0.12921
  Epoch 020 - train 0.11255 | val 0.12865
  Regression -> MSE: 0.000181, MAE: 0.007941, R²: -0.0896
  Directional -> Accuracy: 0.5789, MCC: 0.3571, F1: 0.4000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.11845 | val 0.09844
  Epoch 020 - train 0.11706 | val 0.10050
  Regression -> MSE: 0.000237, MAE: 0.011860, R²: -0.0008
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.11049 | val 0.17675
  Epoch 020 - train 0.11073 | val 0.17318
  Regression -> MSE: 0.000230, MAE: 0.009870, R²: 0.0014
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.11869 | val 0.14161
  Epoch 020 - train 0.12167 | val 0.14249
  Regression -> MSE: 0.000140, MAE: 0.008394, R²: -0.0362
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.12060 | val 0.14630
  Epoch 020 - train 0.11912 | val 0.14616
  Regression -> MSE: 0.000188, MAE: 0.010492, R²: -0.0001
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.10092 | val 0.13064
  Epoch 020 - train 0.09973 | val 0.12883
  Regression -> MSE: 0.000277, MAE: 0.010826, R²: -0.0580
  Directional -> Accuracy: 0.4384, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.10903 | val 0.09621
  Epoch 020 - train 0.10615 | val 0.09785
  Regression -> MSE: 0.000168, MAE: 0.010368, R²: -0.0080
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.10767 | val 0.11547
  Epoch 020 - train 0.10574 | val 0.12033
  Regression -> MSE: 0.000181, MAE: 0.010355, R²: -0.0050
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.10964 | val 0.11164
  Epoch 020 - train 0.10849 | val 0.11270
  Regression -> MSE: 0.000343, MAE: 0.011826, R²: -0.0020
  Directional -> Accuracy: 0.4925, MCC: -0.0336, F1: 0.5526

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.12424 | val 0.07577
  Epoch 020 - train 0.12098 | val 0.08319
  Regression -> MSE: 0.000123, MAE: 0.008405, R²: -0.1677
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.12410 | val 0.16283
  Epoch 020 - train 0.12079 | val 0.17581
  Regression -> MSE: 0.000219, MAE: 0.011276, R²: -0.0006
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.11525 | val 0.20682
  Epoch 020 - train 0.11820 | val 0.22107
  Regression -> MSE: 0.000080, MAE: 0.006973, R²: -0.0335
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.11456 | val 0.09430
  Epoch 020 - train 0.11177 | val 0.09814
  Regression -> MSE: 0.000325, MAE: 0.014775, R²: -0.0575
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.12159 | val 0.07156
  Epoch 020 - train 0.12397 | val 0.07582
  Regression -> MSE: 0.000250, MAE: 0.011492, R²: -0.0239
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.10581 | val 0.13516
  Epoch 020 - train 0.10680 | val 0.13462
  Regression -> MSE: 0.000081, MAE: 0.007051, R²: -0.0072
  Directional -> Accuracy: 0.5200, MCC: 0.0377, F1: 0.4194

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.11859 | val 0.14019
  Epoch 020 - train 0.11167 | val 0.14032
  Regression -> MSE: 0.000310, MAE: 0.014534, R²: -0.0100
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.11048 | val 0.13262
  Epoch 020 - train 0.11054 | val 0.12482
  Regression -> MSE: 0.000097, MAE: 0.007133, R²: 0.0150
  Directional -> Accuracy: 0.5682, MCC: 0.0435, F1: 0.7077

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.12898 | val 0.13739
  Epoch 020 - train 0.13067 | val 0.14261
  Regression -> MSE: 0.000176, MAE: 0.010243, R²: -0.0243
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.10594 | val 0.12979
  Epoch 020 - train 0.10725 | val 0.13031
  Regression -> MSE: 0.000223, MAE: 0.011760, R²: 0.0003
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.11450 | val 0.13276
  Epoch 020 - train 0.11193 | val 0.13536
  Regression -> MSE: 0.000093, MAE: 0.007689, R²: -0.0095
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.12415 | val 0.17895
  Epoch 020 - train 0.12769 | val 0.17681
  Regression -> MSE: 0.000165, MAE: 0.010291, R²: -0.0082
  Directional -> Accuracy: 0.4815, MCC: 0.0000, F1: 0.0000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.11227 | val 0.15616
  Epoch 020 - train 0.11183 | val 0.15445
  Regression -> MSE: 0.000122, MAE: 0.008996, R²: -0.0504
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.11526 | val 0.15979

[I 2026-02-23 00:40:56,015] Trial 156 finished with value: -0.011446522754452026 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 32, 'learning_rate': 3.7530598850688458e-06, 'weight_decay': 1.9009880447712753e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.1695156292430235, 'early_stopping_min_delta': 0.006123229524208996}. Best is trial 143 with value: -0.011397192428235973.

  Epoch 020 - train 0.11533 | val 0.16592
  Regression -> MSE: 0.000240, MAE: 0.012334, R²: -0.0103
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.10406 | val 0.16110
  Epoch 020 - train 0.10306 | val 0.16194
  Regression -> MSE: 0.000248, MAE: 0.012577, R²: -0.0033
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.10881 | val 0.10907
  Epoch 020 - train 0.10726 | val 0.13309
  Regression -> MSE: 0.000710, MAE: 0.019802, R²: -0.0377
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.11855 | val 0.17552
  Epoch 020 - train 0.11557 | val 0.18084
  Regression -> MSE: 0.000311, MAE: 0.014484, R²: -0.0040
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.09127 | val 0.10577
  Epoch 020 - train 0.08864 | val 0.11718
  Regression -> MSE: 0.000360, MAE: 0.014767, R²: -0.0305
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.10883 | val 0.10756
  Epoch 020 - train 0.10337 | val 0.11427
  Regression -> MSE: 0.000204, MAE: 0.010198, R²: -0.0036
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.09921 | val 0.19536
  Epoch 020 - train 0.10118 | val 0.23021
  Regression -> MSE: 0.000565, MAE: 0.018272, R²: -0.0183
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.10724 | val 0.13346
  Epoch 020 - train 0.10930 | val 0.13479
  Regression -> MSE: 0.000246, MAE: 0.011950, R²: -0.0020
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.11418 | val 0.14942
  Epoch 020 - train 0.11207 | val 0.17328
  Regression -> MSE: 0.000640, MAE: 0.020076, R²: -0.0704
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.09541 | val 0.12822
  Epoch 020 - train 0.10138 | val 0.12543
  Regression -> MSE: 0.000391, MAE: 0.015925, R²: -0.0202
  Directional -> Accuracy: 0.5510, MCC: 0.0383, F1: 0.2143

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.10728 | val 0.15571
  Epoch 020 - train 0.10410 | val 0.15204
  Regression -> MSE: 0.000243, MAE: 0.012151, R²: -0.0064
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.11027 | val 0.14956
  Epoch 020 - train 0.10991 | val 0.15014
  Regression -> MSE: 0.000320, MAE: 0.013596, R²: -0.0306
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.10882 | val 0.12735
  Epoch 020 - train 0.10921 | val 0.12750
  Regression -> MSE: 0.000683, MAE: 0.019516, R²: -0.0084
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.10431 | val 0.11565
  Epoch 020 - train 0.10305 | val 0.12288
  Regression -> MSE: 0.000140, MAE: 0.008988, R²: -0.0146
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.09648 | val 0.13726
  Epoch 020 - train 0.09759 | val 0.13706
  Regression -> MSE: 0.000225, MAE: 0.010731, R²: 0.0000
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.10569 | val 0.21220
  Epoch 020 - train 0.10207 | val 0.21512
  Regression -> MSE: 0.000364, MAE: 0.016028, R²: -0.0038
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.11295 | val 0.11260
  Epoch 020 - train 0.10792 | val 0.11363
  Regression -> MSE: 0.000108, MAE: 0.008093, R²: -0.0037
  Directional -> Accuracy: 0.4571, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.11471 | val 0.17208
  Epoch 020 - train 0.11156 | val 0.18164
  Regression -> MSE: 0.000157, MAE: 0.009823, R²: -0.0084
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.10841 | val 0.11578
  Epoch 020 - train 0.10947 | val 0.11327
  Regression -> MSE: 0.000274, MAE: 0.012916, R²: -0.0055
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.10103 | val 0.14588
  Epoch 020 - train 0.09732 | val 0.14236
  Regression -> MSE: 0.000153, MAE: 0.008734, R²: -0.0206
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.10811 | val 0.14858
  Epoch 020 - train 0.10683 | val 0.14916
  Regression -> MSE: 0.000232, MAE: 0.010914, R²: -0.0247
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.10495 | val 0.13001
  Epoch 020 - train 0.10588 | val 0.12974
  Regression -> MSE: 0.000144, MAE: 0.008398, R²: -0.0070
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.10194 | val 0.12629
  Epoch 020 - train 0.10409 | val 0.12570
  Regression -> MSE: 0.000167, MAE: 0.010281, R²: -0.0102
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.11055 | val 0.12261
  Epoch 020 - train 0.10754 | val 0.12191
  Regression -> MSE: 0.000086, MAE: 0.007097, R²: -0.0088
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.10381 | val 0.15326
  Epoch 020 - train 0.10662 | val 0.14601
  Regression -> MSE: 0.000214, MAE: 0.011071, R²: -0.0083
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.09905 | val 0.09292
  Epoch 020 - train 0.09850 | val 0.09114
  Regression -> MSE: 0.000092, MAE: 0.007891, R²: 0.0027
  Directional -> Accuracy: 0.5536, MCC: 0.0682, F1: 0.6479

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.10670 | val 0.08521
  Epoch 020 - train 0.10729 | val 0.09376
  Regression -> MSE: 0.000105, MAE: 0.008861, R²: -0.0221
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.11795 | val 0.10257
  Epoch 020 - train 0.11544 | val 0.10467
  Regression -> MSE: 0.000232, MAE: 0.012503, R²: -0.0007
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.11005 | val 0.13564
  Epoch 020 - train 0.10759 | val 0.13698
  Regression -> MSE: 0.000174, MAE: 0.007876, R²: -0.0477
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.11119 | val 0.09388
  Epoch 020 - train 0.10901 | val 0.09247
  Regression -> MSE: 0.000238, MAE: 0.011913, R²: -0.0066
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.10665 | val 0.16683
  Epoch 020 - train 0.10570 | val 0.17529
  Regression -> MSE: 0.000230, MAE: 0.009858, R²: 0.0000
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.11311 | val 0.12720
  Epoch 020 - train 0.10701 | val 0.12718
  Regression -> MSE: 0.000136, MAE: 0.008245, R²: -0.0061
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.11073 | val 0.13432
  Epoch 020 - train 0.10772 | val 0.13538
  Regression -> MSE: 0.000191, MAE: 0.010379, R²: -0.0128
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.09535 | val 0.12477
  Epoch 020 - train 0.09461 | val 0.12317
  Regression -> MSE: 0.000270, MAE: 0.010630, R²: -0.0329
  Directional -> Accuracy: 0.4521, MCC: -0.0851, F1: 0.4595

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.09521 | val 0.08982
  Epoch 020 - train 0.09459 | val 0.09023
  Regression -> MSE: 0.000166, MAE: 0.010364, R²: 0.0028
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.09519 | val 0.10913
  Epoch 020 - train 0.09409 | val 0.11256
  Regression -> MSE: 0.000181, MAE: 0.010375, R²: -0.0081
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.09728 | val 0.10320
  Epoch 020 - train 0.09907 | val 0.10396
  Regression -> MSE: 0.000348, MAE: 0.012280, R²: -0.0152
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.11831 | val 0.07144
  Epoch 020 - train 0.11695 | val 0.07177
  Regression -> MSE: 0.000112, MAE: 0.008317, R²: -0.0675
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.10975 | val 0.14660
  Epoch 020 - train 0.11180 | val 0.14520
  Regression -> MSE: 0.000218, MAE: 0.011293, R²: 0.0004
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.11322 | val 0.18630
  Epoch 020 - train 0.11450 | val 0.18525
  Regression -> MSE: 0.000081, MAE: 0.007006, R²: -0.0419
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.10712 | val 0.09057
  Epoch 020 - train 0.10546 | val 0.08379
  Regression -> MSE: 0.000319, MAE: 0.014270, R²: -0.0375
  Directional -> Accuracy: 0.4490, MCC: 0.1075, F1: 0.5424

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.11694 | val 0.06768
  Epoch 020 - train 0.11256 | val 0.06580
  Regression -> MSE: 0.000255, MAE: 0.011456, R²: -0.0461
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.10061 | val 0.12598
  Epoch 020 - train 0.10147 | val 0.12436
  Regression -> MSE: 0.000081, MAE: 0.007084, R²: -0.0000
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.12083 | val 0.13014
  Epoch 020 - train 0.11606 | val 0.13064
  Regression -> MSE: 0.000308, MAE: 0.014518, R²: -0.0046
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.10202 | val 0.11493
  Epoch 020 - train 0.10219 | val 0.12659
  Regression -> MSE: 0.000098, MAE: 0.007340, R²: 0.0021
  Directional -> Accuracy: 0.4318, MCC: 0.0000, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.12816 | val 0.12530
  Epoch 020 - train 0.12984 | val 0.13018
  Regression -> MSE: 0.000173, MAE: 0.009477, R²: -0.0081
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.09735 | val 0.12403
  Epoch 020 - train 0.09635 | val 0.12825
  Regression -> MSE: 0.000223, MAE: 0.011742, R²: 0.0009
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.10449 | val 0.11519
  Epoch 020 - train 0.10702 | val 0.11675
  Regression -> MSE: 0.000092, MAE: 0.007639, R²: 0.0010
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.11109 | val 0.16530
  Epoch 020 - train 0.11138 | val 0.16502
  Regression -> MSE: 0.000165, MAE: 0.010279, R²: -0.0090
  Directional -> Accuracy: 0.4815, MCC: 0.0000, F1: 0.0000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.10622 | val 0.13618
  Epoch 020 - train 0.10347 | val 0.13775
  Regression -> MSE: 0.000118, MAE: 0.008961, R²: -0.0214
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.11055 | val 0.16091

[I 2026-02-23 00:43:38,981] Trial 157 finished with value: -0.011387287234516647 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 32, 'learning_rate': 7.498771084517247e-06, 'weight_decay': 1.8245076690059687e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.15730088250319868, 'early_stopping_min_delta': 0.006147002612434458}. Best is trial 157 with value: -0.011387287234516647.

  Epoch 020 - train 0.10919 | val 0.17410
  Regression -> MSE: 0.000238, MAE: 0.012424, R²: -0.0019
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.10792 | val 0.15244
  Epoch 020 - train 0.10787 | val 0.15001
  Regression -> MSE: 0.000268, MAE: 0.013202, R²: -0.0821
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.11705 | val 0.13135
  Epoch 020 - train 0.11343 | val 0.16907
  Regression -> MSE: 0.000685, MAE: 0.019380, R²: -0.0008
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.11081 | val 0.16912
  Epoch 020 - train 0.10973 | val 0.16564
  Regression -> MSE: 0.000338, MAE: 0.014508, R²: -0.0890
  Directional -> Accuracy: 0.4894, MCC: 0.0705, F1: 0.1429

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.08992 | val 0.14464
  Epoch 020 - train 0.08882 | val 0.13706
  Regression -> MSE: 0.000367, MAE: 0.014858, R²: -0.0493
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.10788 | val 0.11078
  Epoch 020 - train 0.10920 | val 0.11489
  Regression -> MSE: 0.000206, MAE: 0.010133, R²: -0.0108
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.09833 | val 0.19739
  Epoch 020 - train 0.09900 | val 0.20479
  Regression -> MSE: 0.000567, MAE: 0.018309, R²: -0.0213
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.11493 | val 0.13562
  Epoch 020 - train 0.11085 | val 0.13454
  Regression -> MSE: 0.000246, MAE: 0.012240, R²: -0.0031
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.10309 | val 0.13716
  Epoch 020 - train 0.10528 | val 0.15755
  Regression -> MSE: 0.000620, MAE: 0.019695, R²: -0.0379
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.10301 | val 0.12861
  Epoch 020 - train 0.10210 | val 0.12620
  Regression -> MSE: 0.000392, MAE: 0.015943, R²: -0.0228
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.10871 | val 0.13693
  Epoch 020 - train 0.10649 | val 0.13659
  Regression -> MSE: 0.000245, MAE: 0.011641, R²: -0.0156
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.10327 | val 0.15202
  Epoch 020 - train 0.10257 | val 0.15718
  Regression -> MSE: 0.000319, MAE: 0.013590, R²: -0.0273
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.11107 | val 0.13282
  Epoch 020 - train 0.10943 | val 0.14433
  Regression -> MSE: 0.000679, MAE: 0.019577, R²: -0.0029
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.11430 | val 0.10965
  Epoch 020 - train 0.11240 | val 0.10850
  Regression -> MSE: 0.000138, MAE: 0.009063, R²: -0.0022
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.10175 | val 0.13418
  Epoch 020 - train 0.09984 | val 0.14137
  Regression -> MSE: 0.000231, MAE: 0.010889, R²: -0.0248
  Directional -> Accuracy: 0.4918, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.10879 | val 0.20912
  Epoch 020 - train 0.10705 | val 0.21322
  Regression -> MSE: 0.000366, MAE: 0.015966, R²: -0.0112
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.11067 | val 0.11291
  Epoch 020 - train 0.11110 | val 0.11377
  Regression -> MSE: 0.000110, MAE: 0.007957, R²: -0.0207
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.10852 | val 0.19300
  Epoch 020 - train 0.10792 | val 0.20613
  Regression -> MSE: 0.000157, MAE: 0.009799, R²: -0.0060
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.11372 | val 0.11286
  Epoch 020 - train 0.11284 | val 0.11093
  Regression -> MSE: 0.000273, MAE: 0.012935, R²: -0.0022
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.10130 | val 0.15275
  Epoch 020 - train 0.09744 | val 0.15593
  Regression -> MSE: 0.000164, MAE: 0.009049, R²: -0.0941
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.11713 | val 0.16090
  Epoch 020 - train 0.11272 | val 0.15775
  Regression -> MSE: 0.000250, MAE: 0.011332, R²: -0.1068
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.10880 | val 0.13225
  Epoch 020 - train 0.10725 | val 0.13272
  Regression -> MSE: 0.000146, MAE: 0.008523, R²: -0.0210
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.11018 | val 0.12646
  Epoch 020 - train 0.10782 | val 0.12623
  Regression -> MSE: 0.000170, MAE: 0.010267, R²: -0.0296
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.11799 | val 0.13687
  Epoch 020 - train 0.11725 | val 0.14240
  Regression -> MSE: 0.000085, MAE: 0.007037, R²: 0.0024
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.11104 | val 0.16350
  Epoch 020 - train 0.11060 | val 0.15880
  Regression -> MSE: 0.000214, MAE: 0.011367, R²: -0.0094
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.10024 | val 0.09554
  Epoch 020 - train 0.09800 | val 0.09460
  Regression -> MSE: 0.000094, MAE: 0.008089, R²: -0.0208
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.10878 | val 0.08789
  Epoch 020 - train 0.10921 | val 0.08426
  Regression -> MSE: 0.000111, MAE: 0.009076, R²: -0.0805
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.11022 | val 0.10202
  Epoch 020 - train 0.10918 | val 0.10400
  Regression -> MSE: 0.000232, MAE: 0.012504, R²: -0.0004
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.10571 | val 0.12780
  Epoch 020 - train 0.10781 | val 0.12787
  Regression -> MSE: 0.000173, MAE: 0.007857, R²: -0.0416
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.12069 | val 0.09979
  Epoch 020 - train 0.11490 | val 0.12182
  Regression -> MSE: 0.000240, MAE: 0.012041, R²: -0.0163
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.10357 | val 0.16927
  Epoch 020 - train 0.10279 | val 0.17484
  Regression -> MSE: 0.000231, MAE: 0.009914, R²: -0.0024
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.11313 | val 0.13958
  Epoch 020 - train 0.11188 | val 0.13781
  Regression -> MSE: 0.000144, MAE: 0.008674, R²: -0.0672
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.10701 | val 0.13516
  Epoch 020 - train 0.10819 | val 0.13571
  Regression -> MSE: 0.000189, MAE: 0.010447, R²: -0.0020
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.10112 | val 0.15038
  Epoch 020 - train 0.10137 | val 0.14818
  Regression -> MSE: 0.000263, MAE: 0.010715, R²: -0.0050
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.10641 | val 0.09659
  Epoch 020 - train 0.10377 | val 0.09483
  Regression -> MSE: 0.000169, MAE: 0.010366, R²: -0.0126
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.09777 | val 0.10788
  Epoch 020 - train 0.09742 | val 0.11013
  Regression -> MSE: 0.000180, MAE: 0.010248, R²: -0.0009
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.10233 | val 0.10628
  Epoch 020 - train 0.10020 | val 0.10839
  Regression -> MSE: 0.000343, MAE: 0.011981, R²: 0.0002
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.11515 | val 0.07043
  Epoch 020 - train 0.11314 | val 0.07001
  Regression -> MSE: 0.000121, MAE: 0.008393, R²: -0.1534
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.11198 | val 0.14546
  Epoch 020 - train 0.10816 | val 0.14813
  Regression -> MSE: 0.000219, MAE: 0.011267, R²: -0.0012
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.10544 | val 0.17813
  Epoch 020 - train 0.10489 | val 0.17765
  Regression -> MSE: 0.000094, MAE: 0.007556, R²: -0.2053
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.12047 | val 0.09990
  Epoch 020 - train 0.12504 | val 0.10978
  Regression -> MSE: 0.000354, MAE: 0.015809, R²: -0.1522
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.11492 | val 0.06659
  Epoch 020 - train 0.11296 | val 0.07218
  Regression -> MSE: 0.000247, MAE: 0.011508, R²: -0.0152
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.10329 | val 0.13103
  Epoch 020 - train 0.10058 | val 0.12878
  Regression -> MSE: 0.000081, MAE: 0.007062, R²: -0.0037
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.10587 | val 0.13736
  Epoch 020 - train 0.10791 | val 0.16230
  Regression -> MSE: 0.000308, MAE: 0.014510, R²: -0.0043
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.12028 | val 0.11383
  Epoch 020 - train 0.11290 | val 0.11248
  Regression -> MSE: 0.000098, MAE: 0.007278, R²: -0.0011
  Directional -> Accuracy: 0.4318, MCC: -0.0843, F1: 0.3243

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.11918 | val 0.12909
  Epoch 020 - train 0.11131 | val 0.12510
  Regression -> MSE: 0.000173, MAE: 0.009483, R²: -0.0051
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.10366 | val 0.11716
  Epoch 020 - train 0.09750 | val 0.11782
  Regression -> MSE: 0.000223, MAE: 0.011754, R²: -0.0008
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.10807 | val 0.12341
  Epoch 020 - train 0.10640 | val 0.12277
  Regression -> MSE: 0.000095, MAE: 0.007848, R²: -0.0333
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.10840 | val 0.17986
  Epoch 020 - train 0.11299 | val 0.18744
  Regression -> MSE: 0.000166, MAE: 0.010252, R²: -0.0116
  Directional -> Accuracy: 0.4815, MCC: 0.0000, F1: 0.0000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.10743 | val 0.13757
  Epoch 020 - train 0.10717 | val 0.14228
  Regression -> MSE: 0.000131, MAE: 0.009134, R²: -0.1329
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.10701 | val 0.15188

[I 2026-02-23 00:46:22,026] Trial 158 finished with value: -0.011468238417233056 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 32, 'learning_rate': 3.541345497898795e-06, 'weight_decay': 2.0790048431990293e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.15801390129829485, 'early_stopping_min_delta': 0.006287192278135053}. Best is trial 157 with value: -0.011387287234516647.

  Epoch 020 - train 0.10736 | val 0.15054
  Regression -> MSE: 0.000237, MAE: 0.012386, R²: 0.0003
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.12857 | val 0.18036
  Epoch 020 - train 0.12823 | val 0.17967
  Regression -> MSE: 0.000250, MAE: 0.012665, R²: -0.0116
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.13260 | val 0.14342
  Epoch 020 - train 0.13023 | val 0.16041
  Regression -> MSE: 0.000687, MAE: 0.019399, R²: -0.0042
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.13452 | val 0.21541
  Epoch 020 - train 0.13269 | val 0.21868
  Regression -> MSE: 0.000311, MAE: 0.014468, R²: -0.0022
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.12666 | val 0.12024
  Epoch 020 - train 0.12228 | val 0.11232
  Regression -> MSE: 0.000351, MAE: 0.014588, R²: -0.0036
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.13738 | val 0.13751
  Epoch 020 - train 0.13331 | val 0.13582
  Regression -> MSE: 0.000206, MAE: 0.010359, R²: -0.0111
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.13202 | val 0.25641
  Epoch 020 - train 0.13171 | val 0.30946
  Regression -> MSE: 0.000568, MAE: 0.018319, R²: -0.0236
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.14106 | val 0.16998
  Epoch 020 - train 0.13921 | val 0.16666
  Regression -> MSE: 0.000247, MAE: 0.012279, R²: -0.0057
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.13510 | val 0.17810
  Epoch 020 - train 0.13242 | val 0.16487
  Regression -> MSE: 0.000636, MAE: 0.020118, R²: -0.0642
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.12770 | val 0.16327
  Epoch 020 - train 0.12400 | val 0.16578
  Regression -> MSE: 0.000391, MAE: 0.015966, R²: -0.0186
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.13394 | val 0.17365
  Epoch 020 - train 0.13381 | val 0.17816
  Regression -> MSE: 0.000242, MAE: 0.011755, R²: -0.0037
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.12629 | val 0.19803
  Epoch 020 - train 0.12335 | val 0.22767
  Regression -> MSE: 0.000314, MAE: 0.013591, R²: -0.0108
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.14024 | val 0.16201
  Epoch 020 - train 0.14332 | val 0.16672
  Regression -> MSE: 0.000680, MAE: 0.019578, R²: -0.0033
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.13527 | val 0.14072
  Epoch 020 - train 0.13007 | val 0.14673
  Regression -> MSE: 0.000138, MAE: 0.009057, R²: -0.0010
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.12410 | val 0.17720
  Epoch 020 - train 0.11747 | val 0.18013
  Regression -> MSE: 0.000228, MAE: 0.010777, R²: -0.0140
  Directional -> Accuracy: 0.4918, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.12706 | val 0.26179
  Epoch 020 - train 0.12523 | val 0.25835
  Regression -> MSE: 0.000362, MAE: 0.016106, R²: 0.0005
  Directional -> Accuracy: 0.4808, MCC: 0.0403, F1: 0.6197

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.13523 | val 0.13447
  Epoch 020 - train 0.13380 | val 0.13746
  Regression -> MSE: 0.000108, MAE: 0.007957, R²: -0.0038
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.13096 | val 0.21455
  Epoch 020 - train 0.13272 | val 0.21644
  Regression -> MSE: 0.000157, MAE: 0.009869, R²: -0.0101
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.13847 | val 0.13428
  Epoch 020 - train 0.13218 | val 0.13429
  Regression -> MSE: 0.000274, MAE: 0.012935, R²: -0.0077
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.12067 | val 0.17708
  Epoch 020 - train 0.11985 | val 0.17632
  Regression -> MSE: 0.000152, MAE: 0.008750, R²: -0.0136
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.13586 | val 0.18835
  Epoch 020 - train 0.13483 | val 0.19364
  Regression -> MSE: 0.000228, MAE: 0.010894, R²: -0.0087
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.13445 | val 0.16608
  Epoch 020 - train 0.12889 | val 0.17695
  Regression -> MSE: 0.000151, MAE: 0.008715, R²: -0.0511
  Directional -> Accuracy: 0.5208, MCC: -0.2641, F1: 0.6849

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.12608 | val 0.15747
  Epoch 020 - train 0.12779 | val 0.15850
  Regression -> MSE: 0.000171, MAE: 0.010269, R²: -0.0350
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.13678 | val 0.16012
  Epoch 020 - train 0.13745 | val 0.15998
  Regression -> MSE: 0.000087, MAE: 0.007150, R²: -0.0215
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.13201 | val 0.19398
  Epoch 020 - train 0.13117 | val 0.18558
  Regression -> MSE: 0.000212, MAE: 0.011145, R²: -0.0014
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.12177 | val 0.11700
  Epoch 020 - train 0.12184 | val 0.11246
  Regression -> MSE: 0.000097, MAE: 0.008139, R²: -0.0502
  Directional -> Accuracy: 0.6071, MCC: 0.1995, F1: 0.6562

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.13883 | val 0.10278
  Epoch 020 - train 0.13327 | val 0.10198
  Regression -> MSE: 0.000103, MAE: 0.008680, R²: 0.0015
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.13939 | val 0.13761
  Epoch 020 - train 0.13890 | val 0.16717
  Regression -> MSE: 0.000245, MAE: 0.012961, R²: -0.0579
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.13779 | val 0.16124
  Epoch 020 - train 0.12864 | val 0.16316
  Regression -> MSE: 0.000186, MAE: 0.008086, R²: -0.1192
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.13733 | val 0.11252
  Epoch 020 - train 0.13509 | val 0.11335
  Regression -> MSE: 0.000238, MAE: 0.011910, R²: -0.0062
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.13523 | val 0.20782
  Epoch 020 - train 0.13458 | val 0.21292
  Regression -> MSE: 0.000231, MAE: 0.009861, R²: -0.0010
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.13324 | val 0.15704
  Epoch 020 - train 0.13608 | val 0.16400
  Regression -> MSE: 0.000136, MAE: 0.008197, R²: -0.0060
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.13171 | val 0.16673
  Epoch 020 - train 0.13513 | val 0.16687
  Regression -> MSE: 0.000189, MAE: 0.010406, R²: -0.0061
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.12048 | val 0.17068
  Epoch 020 - train 0.12061 | val 0.16494
  Regression -> MSE: 0.000267, MAE: 0.010563, R²: -0.0194
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.12552 | val 0.11592
  Epoch 020 - train 0.12230 | val 0.11214
  Regression -> MSE: 0.000167, MAE: 0.010360, R²: -0.0041
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.12277 | val 0.13232
  Epoch 020 - train 0.12156 | val 0.13311
  Regression -> MSE: 0.000181, MAE: 0.010274, R²: -0.0044
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.13455 | val 0.12458
  Epoch 020 - train 0.12656 | val 0.12488
  Regression -> MSE: 0.000345, MAE: 0.011716, R²: -0.0061
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.14534 | val 0.08528
  Epoch 020 - train 0.14083 | val 0.08980
  Regression -> MSE: 0.000117, MAE: 0.008336, R²: -0.1112
  Directional -> Accuracy: 0.5349, MCC: 0.0733, F1: 0.6552

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.13831 | val 0.18215
  Epoch 020 - train 0.13296 | val 0.18530
  Regression -> MSE: 0.000219, MAE: 0.011279, R²: -0.0001
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.13178 | val 0.22502
  Epoch 020 - train 0.12686 | val 0.22678
  Regression -> MSE: 0.000088, MAE: 0.007326, R²: -0.1285
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.12864 | val 0.10377
  Epoch 020 - train 0.13288 | val 0.11662
  Regression -> MSE: 0.000317, MAE: 0.014339, R²: -0.0294
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.14394 | val 0.07963
  Epoch 020 - train 0.14111 | val 0.07985
  Regression -> MSE: 0.000247, MAE: 0.011552, R²: -0.0129
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.0000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.12764 | val 0.16310
  Epoch 020 - train 0.12949 | val 0.16202
  Regression -> MSE: 0.000081, MAE: 0.007115, R²: -0.0056
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.13562 | val 0.17322
  Epoch 020 - train 0.13766 | val 0.16960
  Regression -> MSE: 0.000310, MAE: 0.014494, R²: -0.0102
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.12980 | val 0.14338
  Epoch 020 - train 0.12614 | val 0.14739
  Regression -> MSE: 0.000098, MAE: 0.007275, R²: -0.0002
  Directional -> Accuracy: 0.4773, MCC: -0.0087, F1: 0.4390

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.14605 | val 0.15775
  Epoch 020 - train 0.14917 | val 0.16341
  Regression -> MSE: 0.000174, MAE: 0.010107, R²: -0.0150
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.12260 | val 0.14861
  Epoch 020 - train 0.11730 | val 0.14954
  Regression -> MSE: 0.000224, MAE: 0.011790, R²: -0.0037
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.12980 | val 0.15389
  Epoch 020 - train 0.12789 | val 0.15929
  Regression -> MSE: 0.000092, MAE: 0.007644, R²: 0.0004
  Directional -> Accuracy: 0.4737, MCC: -0.0101, F1: 0.6341

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.13975 | val 0.20456
  Epoch 020 - train 0.13815 | val 0.20980
  Regression -> MSE: 0.000163, MAE: 0.010226, R²: 0.0017
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.13419 | val 0.16573
  Epoch 020 - train 0.13177 | val 0.17136
  Regression -> MSE: 0.000132, MAE: 0.009154, R²: -0.1429
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.13582 | val 0.18335

[I 2026-02-23 00:49:05,640] Trial 159 finished with value: -0.011416948749238627 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 32, 'learning_rate': 5.555007150093783e-06, 'weight_decay': 5.4453477921549946e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.20089270988830532, 'early_stopping_min_delta': 0.005748383844526415}. Best is trial 157 with value: -0.011387287234516647.

  Epoch 020 - train 0.13365 | val 0.18882
  Regression -> MSE: 0.000238, MAE: 0.012350, R²: -0.0028
  Directional -> Accuracy: 0.5246, MCC: 0.2165, F1: 0.6667

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.14036 | val 0.19203
  Epoch 020 - train 0.13944 | val 0.19249
  Regression -> MSE: 0.000262, MAE: 0.013046, R²: -0.0570
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.13366 | val 0.13405
  Epoch 020 - train 0.13703 | val 0.13646
  Regression -> MSE: 0.000685, MAE: 0.019376, R²: -0.0003
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.13718 | val 0.22484
  Epoch 020 - train 0.14546 | val 0.22553
  Regression -> MSE: 0.000313, MAE: 0.014427, R²: -0.0093
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.11515 | val 0.16970
  Epoch 020 - train 0.11543 | val 0.16938
  Regression -> MSE: 0.000358, MAE: 0.014720, R²: -0.0239
  Directional -> Accuracy: 0.4667, MCC: -0.0469, F1: 0.4286

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.13592 | val 0.13507
  Epoch 020 - train 0.14083 | val 0.13398
  Regression -> MSE: 0.000207, MAE: 0.010126, R²: -0.0177
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.13987 | val 0.25893
  Epoch 020 - train 0.13507 | val 0.26097
  Regression -> MSE: 0.000565, MAE: 0.018249, R²: -0.0176
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.14489 | val 0.17504
  Epoch 020 - train 0.14455 | val 0.16964
  Regression -> MSE: 0.000249, MAE: 0.012453, R²: -0.0156
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.13917 | val 0.18755
  Epoch 020 - train 0.13773 | val 0.18221
  Regression -> MSE: 0.000645, MAE: 0.020228, R²: -0.0803
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.14140 | val 0.16797
  Epoch 020 - train 0.13887 | val 0.18458
  Regression -> MSE: 0.000395, MAE: 0.015970, R²: -0.0294
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.13599 | val 0.19330
  Epoch 020 - train 0.13401 | val 0.20130
  Regression -> MSE: 0.000241, MAE: 0.011874, R²: 0.0012
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.12544 | val 0.20201
  Epoch 020 - train 0.12294 | val 0.20829
  Regression -> MSE: 0.000312, MAE: 0.013631, R²: -0.0041
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.15564 | val 0.17534
  Epoch 020 - train 0.14833 | val 0.18044
  Regression -> MSE: 0.000685, MAE: 0.019771, R²: -0.0107
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.13998 | val 0.13699
  Epoch 020 - train 0.13400 | val 0.15634
  Regression -> MSE: 0.000141, MAE: 0.009326, R²: -0.0187
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.12918 | val 0.18053
  Epoch 020 - train 0.12707 | val 0.18133
  Regression -> MSE: 0.000230, MAE: 0.010859, R²: -0.0213
  Directional -> Accuracy: 0.4918, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.13821 | val 0.33032
  Epoch 020 - train 0.13742 | val 0.40582
  Regression -> MSE: 0.000363, MAE: 0.016204, R²: -0.0012
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.14445 | val 0.14525
  Epoch 020 - train 0.14154 | val 0.15334
  Regression -> MSE: 0.000108, MAE: 0.008013, R²: -0.0014
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.13479 | val 0.23499
  Epoch 020 - train 0.13395 | val 0.24895
  Regression -> MSE: 0.000155, MAE: 0.009658, R²: 0.0039
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.13697 | val 0.18885
  Epoch 020 - train 0.13568 | val 0.18448
  Regression -> MSE: 0.000283, MAE: 0.013544, R²: -0.0389
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.12848 | val 0.18512
  Epoch 020 - train 0.12566 | val 0.18400
  Regression -> MSE: 0.000158, MAE: 0.008830, R²: -0.0535
  Directional -> Accuracy: 0.6000, MCC: 0.1483, F1: 0.7451

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.15431 | val 0.19959
  Epoch 020 - train 0.14591 | val 0.19662
  Regression -> MSE: 0.000259, MAE: 0.011534, R²: -0.1434
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.13978 | val 0.16957
  Epoch 020 - train 0.13635 | val 0.16828
  Regression -> MSE: 0.000149, MAE: 0.008913, R²: -0.0393
  Directional -> Accuracy: 0.3542, MCC: -0.2530, F1: 0.3673

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.13612 | val 0.16336
  Epoch 020 - train 0.13214 | val 0.16265
  Regression -> MSE: 0.000166, MAE: 0.010592, R²: -0.0036
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.14303 | val 0.15835
  Epoch 020 - train 0.14156 | val 0.15709
  Regression -> MSE: 0.000099, MAE: 0.007577, R²: -0.1621
  Directional -> Accuracy: 0.4655, MCC: -0.0555, F1: 0.4746

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.13745 | val 0.16575
  Epoch 020 - train 0.13532 | val 0.16465
  Regression -> MSE: 0.000212, MAE: 0.011237, R²: -0.0033
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.12272 | val 0.11894
  Epoch 020 - train 0.12324 | val 0.11328
  Regression -> MSE: 0.000113, MAE: 0.008622, R²: -0.2321
  Directional -> Accuracy: 0.4286, MCC: -0.1054, F1: 0.0588

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.13773 | val 0.10619
  Epoch 020 - train 0.13359 | val 0.10801
  Regression -> MSE: 0.000105, MAE: 0.008817, R²: -0.0144
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.15334 | val 0.13827
  Epoch 020 - train 0.15022 | val 0.15431
  Regression -> MSE: 0.000236, MAE: 0.012715, R²: -0.0204
  Directional -> Accuracy: 0.6047, MCC: 0.1508, F1: 0.7018

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.13900 | val 0.15997
  Epoch 020 - train 0.13499 | val 0.15757
  Regression -> MSE: 0.000198, MAE: 0.008500, R²: -0.1881
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.14871 | val 0.11852
  Epoch 020 - train 0.15045 | val 0.12189
  Regression -> MSE: 0.000237, MAE: 0.011884, R²: -0.0033
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.13213 | val 0.22069
  Epoch 020 - train 0.13902 | val 0.22155
  Regression -> MSE: 0.000233, MAE: 0.010016, R²: -0.0092
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.14204 | val 0.17482
  Epoch 020 - train 0.14861 | val 0.18811
  Regression -> MSE: 0.000138, MAE: 0.008340, R²: -0.0250
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.13556 | val 0.17370
  Epoch 020 - train 0.13485 | val 0.17550
  Regression -> MSE: 0.000199, MAE: 0.010663, R²: -0.0544
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.12676 | val 0.15752
  Epoch 020 - train 0.12159 | val 0.15590
  Regression -> MSE: 0.000281, MAE: 0.011023, R²: -0.0728
  Directional -> Accuracy: 0.4110, MCC: -0.1457, F1: 0.3385

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.13566 | val 0.12045
  Epoch 020 - train 0.13572 | val 0.11474
  Regression -> MSE: 0.000168, MAE: 0.010411, R²: -0.0066
  Directional -> Accuracy: 0.4474, MCC: -0.2357, F1: 0.6182

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.12640 | val 0.14508
  Epoch 020 - train 0.12810 | val 0.15481
  Regression -> MSE: 0.000181, MAE: 0.010308, R²: -0.0030
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.12643 | val 0.12983
  Epoch 020 - train 0.12569 | val 0.12964
  Regression -> MSE: 0.000346, MAE: 0.012144, R²: -0.0094
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.14991 | val 0.09326
  Epoch 020 - train 0.15191 | val 0.11019
  Regression -> MSE: 0.000112, MAE: 0.008314, R²: -0.0653
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.13455 | val 0.18324
  Epoch 020 - train 0.13517 | val 0.18775
  Regression -> MSE: 0.000219, MAE: 0.011109, R²: -0.0007
  Directional -> Accuracy: 0.6491, MCC: 0.3109, F1: 0.6667

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.13630 | val 0.23947
  Epoch 020 - train 0.13618 | val 0.24651
  Regression -> MSE: 0.000089, MAE: 0.007368, R²: -0.1414
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.13555 | val 0.11174
  Epoch 020 - train 0.13586 | val 0.13271
  Regression -> MSE: 0.000323, MAE: 0.014678, R²: -0.0503
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.14790 | val 0.08598
  Epoch 020 - train 0.14458 | val 0.08902
  Regression -> MSE: 0.000254, MAE: 0.011475, R²: -0.0420
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.13185 | val 0.16406
  Epoch 020 - train 0.12888 | val 0.16748
  Regression -> MSE: 0.000082, MAE: 0.007049, R²: -0.0125
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.14167 | val 0.16937
  Epoch 020 - train 0.13612 | val 0.16389
  Regression -> MSE: 0.000332, MAE: 0.014855, R²: -0.0830
  Directional -> Accuracy: 0.4681, MCC: -0.0644, F1: 0.2424

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.14930 | val 0.15337
  Epoch 020 - train 0.14454 | val 0.14835
  Regression -> MSE: 0.000097, MAE: 0.007195, R²: 0.0149
  Directional -> Accuracy: 0.5909, MCC: 0.1663, F1: 0.6400

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.15126 | val 0.16405
  Epoch 020 - train 0.14824 | val 0.17098
  Regression -> MSE: 0.000173, MAE: 0.009962, R²: -0.0077
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.12550 | val 0.16582
  Epoch 020 - train 0.12631 | val 0.16949
  Regression -> MSE: 0.000226, MAE: 0.011779, R²: -0.0142
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.13239 | val 0.16102
  Epoch 020 - train 0.13828 | val 0.16580
  Regression -> MSE: 0.000092, MAE: 0.007666, R²: -0.0018
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.14718 | val 0.22588
  Epoch 020 - train 0.14443 | val 0.24714
  Regression -> MSE: 0.000166, MAE: 0.010284, R²: -0.0109
  Directional -> Accuracy: 0.4815, MCC: 0.0000, F1: 0.0000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.15206 | val 0.21926
  Epoch 020 - train 0.15006 | val 0.24732
  Regression -> MSE: 0.000116, MAE: 0.008923, R²: -0.0039
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.14144 | val 0.18814

[I 2026-02-23 00:51:49,363] Trial 160 finished with value: -0.011537443044102482 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 32, 'learning_rate': 4.934876563950005e-06, 'weight_decay': 1.2518804342701118e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.20976499119984326, 'early_stopping_min_delta': 0.005761890063950325}. Best is trial 157 with value: -0.011387287234516647.

  Epoch 020 - train 0.13997 | val 0.18733
  Regression -> MSE: 0.000248, MAE: 0.012612, R²: -0.0443
  Directional -> Accuracy: 0.4918, MCC: -0.0669, F1: 0.2051

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.11084 | val 0.14195
  Epoch 020 - train 0.10734 | val 0.14019
  Regression -> MSE: 0.000254, MAE: 0.012713, R²: -0.0272
  Directional -> Accuracy: 0.5195, MCC: 0.0427, F1: 0.5067

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.10457 | val 0.10257
  Epoch 020 - train 0.10044 | val 0.10864
  Regression -> MSE: 0.000709, MAE: 0.019776, R²: -0.0352
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.11708 | val 0.17511
  Epoch 020 - train 0.12276 | val 0.17190
  Regression -> MSE: 0.000327, MAE: 0.014550, R²: -0.0539
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.09282 | val 0.14805
  Epoch 020 - train 0.09105 | val 0.16629
  Regression -> MSE: 0.000357, MAE: 0.014697, R²: -0.0212
  Directional -> Accuracy: 0.5867, MCC: 0.1603, F1: 0.6353

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.11684 | val 0.10966
  Epoch 020 - train 0.11159 | val 0.10608
  Regression -> MSE: 0.000211, MAE: 0.010228, R²: -0.0360
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.09853 | val 0.19926
  Epoch 020 - train 0.09925 | val 0.21102
  Regression -> MSE: 0.000564, MAE: 0.018246, R²: -0.0166
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.11160 | val 0.13902
  Epoch 020 - train 0.10941 | val 0.14036
  Regression -> MSE: 0.000245, MAE: 0.012008, R²: 0.0031
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.10998 | val 0.12805
  Epoch 020 - train 0.10934 | val 0.13171
  Regression -> MSE: 0.000604, MAE: 0.019302, R²: -0.0102
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.11242 | val 0.14072
  Epoch 020 - train 0.10574 | val 0.15076
  Regression -> MSE: 0.000384, MAE: 0.016165, R²: -0.0012
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.10633 | val 0.15142
  Epoch 020 - train 0.10611 | val 0.15344
  Regression -> MSE: 0.000247, MAE: 0.011625, R²: -0.0210
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.09956 | val 0.17037
  Epoch 020 - train 0.10223 | val 0.19053
  Regression -> MSE: 0.000313, MAE: 0.013621, R²: -0.0069
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.11249 | val 0.12878
  Epoch 020 - train 0.10976 | val 0.13655
  Regression -> MSE: 0.000678, MAE: 0.019540, R²: -0.0017
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.10560 | val 0.10894
  Epoch 020 - train 0.10774 | val 0.10926
  Regression -> MSE: 0.000141, MAE: 0.009336, R²: -0.0205
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.10255 | val 0.15772
  Epoch 020 - train 0.10250 | val 0.16054
  Regression -> MSE: 0.000227, MAE: 0.010882, R²: -0.0072
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.11042 | val 0.22069
  Epoch 020 - train 0.10744 | val 0.22848
  Regression -> MSE: 0.000365, MAE: 0.015975, R²: -0.0087
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.11842 | val 0.11200
  Epoch 020 - train 0.11353 | val 0.11039
  Regression -> MSE: 0.000108, MAE: 0.008051, R²: -0.0025
  Directional -> Accuracy: 0.4571, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.10662 | val 0.17474
  Epoch 020 - train 0.10335 | val 0.17859
  Regression -> MSE: 0.000157, MAE: 0.009847, R²: -0.0079
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.11096 | val 0.11038
  Epoch 020 - train 0.10950 | val 0.10847
  Regression -> MSE: 0.000272, MAE: 0.013002, R²: -0.0012
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.10076 | val 0.15553
  Epoch 020 - train 0.09959 | val 0.15219
  Regression -> MSE: 0.000155, MAE: 0.008774, R²: -0.0366
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.11272 | val 0.16057
  Epoch 020 - train 0.11172 | val 0.16082
  Regression -> MSE: 0.000234, MAE: 0.010929, R²: -0.0345
  Directional -> Accuracy: 0.5067, MCC: 0.0573, F1: 0.4127

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.11101 | val 0.13745
  Epoch 020 - train 0.10915 | val 0.15613
  Regression -> MSE: 0.000146, MAE: 0.008476, R²: -0.0151
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.10091 | val 0.12838
  Epoch 020 - train 0.10122 | val 0.12885
  Regression -> MSE: 0.000166, MAE: 0.010359, R²: -0.0042
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.11077 | val 0.12811
  Epoch 020 - train 0.11148 | val 0.13047
  Regression -> MSE: 0.000087, MAE: 0.007142, R²: -0.0193
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.10975 | val 0.13203
  Epoch 020 - train 0.10949 | val 0.13536
  Regression -> MSE: 0.000212, MAE: 0.011097, R²: -0.0021
  Directional -> Accuracy: 0.4848, MCC: -0.0011, F1: 0.5750

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.10217 | val 0.10333
  Epoch 020 - train 0.10347 | val 0.10375
  Regression -> MSE: 0.000093, MAE: 0.008093, R²: -0.0063
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.11659 | val 0.08493
  Epoch 020 - train 0.11457 | val 0.09576
  Regression -> MSE: 0.000103, MAE: 0.008743, R²: -0.0017
  Directional -> Accuracy: 0.4565, MCC: 0.1307, F1: 0.6154

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.11589 | val 0.11244
  Epoch 020 - train 0.10995 | val 0.17030
  Regression -> MSE: 0.000233, MAE: 0.012591, R²: -0.0045
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.10454 | val 0.12682
  Epoch 020 - train 0.10534 | val 0.12624
  Regression -> MSE: 0.000174, MAE: 0.007864, R²: -0.0479
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.11897 | val 0.09721
  Epoch 020 - train 0.11407 | val 0.09551
  Regression -> MSE: 0.000240, MAE: 0.012027, R²: -0.0138
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.10659 | val 0.16842
  Epoch 020 - train 0.10898 | val 0.16628
  Regression -> MSE: 0.000230, MAE: 0.009866, R²: -0.0001
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.11374 | val 0.13917
  Epoch 020 - train 0.11434 | val 0.14513
  Regression -> MSE: 0.000140, MAE: 0.008422, R²: -0.0359
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.11480 | val 0.14559
  Epoch 020 - train 0.11268 | val 0.15305
  Regression -> MSE: 0.000189, MAE: 0.010411, R²: -0.0033
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.09360 | val 0.11949
  Epoch 020 - train 0.09795 | val 0.11890
  Regression -> MSE: 0.000270, MAE: 0.010608, R²: -0.0294
  Directional -> Accuracy: 0.5342, MCC: 0.0282, F1: 0.6222

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.11005 | val 0.09144
  Epoch 020 - train 0.10891 | val 0.09152
  Regression -> MSE: 0.000168, MAE: 0.010375, R²: -0.0103
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.10170 | val 0.12686
  Epoch 020 - train 0.10423 | val 0.13629
  Regression -> MSE: 0.000188, MAE: 0.010645, R²: -0.0456
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.10624 | val 0.10644
  Epoch 020 - train 0.10080 | val 0.10764
  Regression -> MSE: 0.000343, MAE: 0.011919, R²: -0.0013
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.11204 | val 0.07276
  Epoch 020 - train 0.11366 | val 0.07655
  Regression -> MSE: 0.000113, MAE: 0.008311, R²: -0.0767
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.11042 | val 0.15895
  Epoch 020 - train 0.11100 | val 0.15916
  Regression -> MSE: 0.000225, MAE: 0.011456, R²: -0.0281
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.10802 | val 0.18432
  Epoch 020 - train 0.10746 | val 0.19737
  Regression -> MSE: 0.000088, MAE: 0.007347, R²: -0.1344
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.11656 | val 0.10094
  Epoch 020 - train 0.11739 | val 0.11519
  Regression -> MSE: 0.000349, MAE: 0.015631, R²: -0.1333
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.11033 | val 0.07602
  Epoch 020 - train 0.11342 | val 0.08109
  Regression -> MSE: 0.000264, MAE: 0.011529, R²: -0.0814
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.10773 | val 0.12711
  Epoch 020 - train 0.10626 | val 0.12799
  Regression -> MSE: 0.000082, MAE: 0.007063, R²: -0.0110
  Directional -> Accuracy: 0.4800, MCC: -0.0582, F1: 0.2642

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.10894 | val 0.13326
  Epoch 020 - train 0.11150 | val 0.13365
  Regression -> MSE: 0.000309, MAE: 0.014523, R²: -0.0081
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.11891 | val 0.12999
  Epoch 020 - train 0.11411 | val 0.13503
  Regression -> MSE: 0.000102, MAE: 0.007116, R²: -0.0344
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.11817 | val 0.12868
  Epoch 020 - train 0.11620 | val 0.13756
  Regression -> MSE: 0.000172, MAE: 0.009731, R²: -0.0007
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.10115 | val 0.12931
  Epoch 020 - train 0.09914 | val 0.13029
  Regression -> MSE: 0.000227, MAE: 0.011818, R²: -0.0167
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.11200 | val 0.12861
  Epoch 020 - train 0.10845 | val 0.13772
  Regression -> MSE: 0.000093, MAE: 0.007692, R²: -0.0108
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.11758 | val 0.17282
  Epoch 020 - train 0.11446 | val 0.17252
  Regression -> MSE: 0.000168, MAE: 0.010326, R²: -0.0242
  Directional -> Accuracy: 0.4815, MCC: 0.0000, F1: 0.0000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.10737 | val 0.13330
  Epoch 020 - train 0.10621 | val 0.13425
  Regression -> MSE: 0.000118, MAE: 0.008960, R²: -0.0195
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.10844 | val 0.14864

[I 2026-02-23 00:54:31,730] Trial 161 finished with value: -0.011434714936644268 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 32, 'learning_rate': 5.8407357564593396e-06, 'weight_decay': 3.4995646079064956e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.16037132633291143, 'early_stopping_min_delta': 0.006506083437983805}. Best is trial 157 with value: -0.011387287234516647.

  Epoch 020 - train 0.11127 | val 0.15224
  Regression -> MSE: 0.000240, MAE: 0.012330, R²: -0.0115
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.07592 | val 0.11627
  Epoch 020 - train 0.07558 | val 0.11663
  Regression -> MSE: 0.000257, MAE: 0.012920, R²: -0.0383
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.07749 | val 0.07785
  Epoch 020 - train 0.07667 | val 0.09802
  Regression -> MSE: 0.000689, MAE: 0.019446, R²: -0.0070
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.07780 | val 0.12002
  Epoch 020 - train 0.07952 | val 0.12287
  Regression -> MSE: 0.000324, MAE: 0.014543, R²: -0.0431
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.06188 | val 0.06346
  Epoch 020 - train 0.06202 | val 0.06627
  Regression -> MSE: 0.000349, MAE: 0.014587, R²: -0.0004
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.07828 | val 0.06969
  Epoch 020 - train 0.07521 | val 0.07073
  Regression -> MSE: 0.000203, MAE: 0.010039, R²: 0.0008
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.07091 | val 0.13210
  Epoch 020 - train 0.06869 | val 0.14559
  Regression -> MSE: 0.000603, MAE: 0.019071, R²: -0.0856
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.07508 | val 0.09288
  Epoch 020 - train 0.07493 | val 0.09409
  Regression -> MSE: 0.000245, MAE: 0.012005, R²: 0.0005
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.07241 | val 0.09674
  Epoch 020 - train 0.07275 | val 0.10000
  Regression -> MSE: 0.000628, MAE: 0.019860, R²: -0.0517
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.07255 | val 0.09048
  Epoch 020 - train 0.07385 | val 0.10145
  Regression -> MSE: 0.000391, MAE: 0.015929, R²: -0.0204
  Directional -> Accuracy: 0.5306, MCC: -0.0332, F1: 0.1481

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.07771 | val 0.09694
  Epoch 020 - train 0.07374 | val 0.10172
  Regression -> MSE: 0.000242, MAE: 0.011938, R²: -0.0011
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.06793 | val 0.10402
  Epoch 020 - train 0.06773 | val 0.10493
  Regression -> MSE: 0.000311, MAE: 0.013654, R²: -0.0011
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.07547 | val 0.08661
  Epoch 020 - train 0.07380 | val 0.08820
  Regression -> MSE: 0.000678, MAE: 0.019526, R²: -0.0006
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.07637 | val 0.07597
  Epoch 020 - train 0.07395 | val 0.08079
  Regression -> MSE: 0.000138, MAE: 0.009053, R²: -0.0007
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.06899 | val 0.10111
  Epoch 020 - train 0.06923 | val 0.10497
  Regression -> MSE: 0.000225, MAE: 0.010720, R²: 0.0018
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.07161 | val 0.14801
  Epoch 020 - train 0.07248 | val 0.14728
  Regression -> MSE: 0.000363, MAE: 0.016178, R²: -0.0010
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.07909 | val 0.08145
  Epoch 020 - train 0.07761 | val 0.08179
  Regression -> MSE: 0.000110, MAE: 0.008224, R²: -0.0230
  Directional -> Accuracy: 0.4571, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.07320 | val 0.12689
  Epoch 020 - train 0.07233 | val 0.13698
  Regression -> MSE: 0.000159, MAE: 0.010003, R²: -0.0210
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.07535 | val 0.07583
  Epoch 020 - train 0.07292 | val 0.07661
  Regression -> MSE: 0.000272, MAE: 0.013008, R²: 0.0008
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.06923 | val 0.10035
  Epoch 020 - train 0.07017 | val 0.10012
  Regression -> MSE: 0.000166, MAE: 0.009099, R²: -0.1094
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.07582 | val 0.10400
  Epoch 020 - train 0.07475 | val 0.10361
  Regression -> MSE: 0.000239, MAE: 0.011039, R²: -0.0571
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.07433 | val 0.09017
  Epoch 020 - train 0.07380 | val 0.09301
  Regression -> MSE: 0.000150, MAE: 0.008671, R²: -0.0455
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.07180 | val 0.08498
  Epoch 020 - train 0.06858 | val 0.08511
  Regression -> MSE: 0.000174, MAE: 0.010276, R²: -0.0552
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.07570 | val 0.08543
  Epoch 020 - train 0.07447 | val 0.08657
  Regression -> MSE: 0.000087, MAE: 0.007163, R²: -0.0224
  Directional -> Accuracy: 0.5690, MCC: 0.1089, F1: 0.6377

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.07425 | val 0.10619
  Epoch 020 - train 0.07380 | val 0.11248
  Regression -> MSE: 0.000214, MAE: 0.011055, R²: -0.0098
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.07386 | val 0.07639
  Epoch 020 - train 0.07184 | val 0.07829
  Regression -> MSE: 0.000101, MAE: 0.008252, R²: -0.0960
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.07462 | val 0.05794
  Epoch 020 - train 0.07600 | val 0.05884
  Regression -> MSE: 0.000103, MAE: 0.008688, R²: -0.0000
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.07709 | val 0.07112
  Epoch 020 - train 0.07420 | val 0.07690
  Regression -> MSE: 0.000233, MAE: 0.012591, R²: -0.0047
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.07193 | val 0.08881
  Epoch 020 - train 0.07080 | val 0.08935
  Regression -> MSE: 0.000177, MAE: 0.007897, R²: -0.0625
  Directional -> Accuracy: 0.5965, MCC: 0.2157, F1: 0.7356

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.07309 | val 0.06303
  Epoch 020 - train 0.07433 | val 0.06236
  Regression -> MSE: 0.000237, MAE: 0.011887, R²: -0.0026
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.07410 | val 0.11505
  Epoch 020 - train 0.07606 | val 0.11816
  Regression -> MSE: 0.000231, MAE: 0.009935, R²: -0.0040
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.07868 | val 0.08737
  Epoch 020 - train 0.07705 | val 0.09042
  Regression -> MSE: 0.000135, MAE: 0.008218, R²: -0.0005
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.07480 | val 0.09458
  Epoch 020 - train 0.07668 | val 0.09539
  Regression -> MSE: 0.000189, MAE: 0.010533, R²: -0.0021
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.06818 | val 0.08325
  Epoch 020 - train 0.06633 | val 0.08304
  Regression -> MSE: 0.000268, MAE: 0.010588, R²: -0.0249
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.07509 | val 0.06303
  Epoch 020 - train 0.07683 | val 0.07057
  Regression -> MSE: 0.000172, MAE: 0.010400, R²: -0.0298
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.06775 | val 0.07866
  Epoch 020 - train 0.06850 | val 0.08436
  Regression -> MSE: 0.000184, MAE: 0.010487, R²: -0.0239
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.07389 | val 0.07260
  Epoch 020 - train 0.07262 | val 0.07285
  Regression -> MSE: 0.000347, MAE: 0.011739, R²: -0.0132
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.08457 | val 0.04959
  Epoch 020 - train 0.08325 | val 0.05252
  Regression -> MSE: 0.000120, MAE: 0.008373, R²: -0.1411
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.07408 | val 0.09888
  Epoch 020 - train 0.07327 | val 0.09945
  Regression -> MSE: 0.000220, MAE: 0.011351, R²: -0.0065
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.06989 | val 0.12192
  Epoch 020 - train 0.07262 | val 0.12225
  Regression -> MSE: 0.000088, MAE: 0.007330, R²: -0.1290
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.07584 | val 0.05636
  Epoch 020 - train 0.07184 | val 0.06113
  Regression -> MSE: 0.000308, MAE: 0.013742, R²: -0.0026
  Directional -> Accuracy: 0.6327, MCC: 0.0000, F1: 0.0000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.08725 | val 0.05309
  Epoch 020 - train 0.08612 | val 0.05388
  Regression -> MSE: 0.000267, MAE: 0.011555, R²: -0.0938
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.07097 | val 0.08967
  Epoch 020 - train 0.06971 | val 0.08976
  Regression -> MSE: 0.000084, MAE: 0.007043, R²: -0.0353
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.07485 | val 0.09152
  Epoch 020 - train 0.07406 | val 0.09847
  Regression -> MSE: 0.000307, MAE: 0.014499, R²: -0.0004
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.07602 | val 0.08618
  Epoch 020 - train 0.07485 | val 0.08251
  Regression -> MSE: 0.000102, MAE: 0.007116, R²: -0.0378
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.07730 | val 0.08851
  Epoch 020 - train 0.07663 | val 0.09811
  Regression -> MSE: 0.000172, MAE: 0.009633, R²: 0.0004
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.06948 | val 0.11089
  Epoch 020 - train 0.06860 | val 0.11605
  Regression -> MSE: 0.000226, MAE: 0.011776, R²: -0.0147
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.07238 | val 0.08910
  Epoch 020 - train 0.07299 | val 0.09190
  Regression -> MSE: 0.000097, MAE: 0.007935, R²: -0.0470
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.07680 | val 0.11071
  Epoch 020 - train 0.07892 | val 0.11162
  Regression -> MSE: 0.000164, MAE: 0.010239, R²: 0.0010
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.07990 | val 0.09260
  Epoch 020 - train 0.07877 | val 0.09416
  Regression -> MSE: 0.000136, MAE: 0.009251, R²: -0.1732
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.07742 | val 0.10943

[I 2026-02-23 00:57:06,832] Trial 162 finished with value: -0.011428353953968785 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 32, 'learning_rate': 4.180037684619605e-06, 'weight_decay': 8.061710111939379e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.1045470362013955, 'early_stopping_min_delta': 0.006584934753224473}. Best is trial 157 with value: -0.011387287234516647.

  Epoch 020 - train 0.07486 | val 0.10971
  Regression -> MSE: 0.000239, MAE: 0.012352, R²: -0.0089
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.12437 | val 0.17238
  Epoch 020 - train 0.12272 | val 0.17303
  Regression -> MSE: 0.000258, MAE: 0.012959, R²: -0.0440
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.12218 | val 0.11530
  Epoch 020 - train 0.12226 | val 0.13744
  Regression -> MSE: 0.000687, MAE: 0.019379, R²: -0.0042
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.12614 | val 0.20294
  Epoch 020 - train 0.12381 | val 0.21067
  Regression -> MSE: 0.000311, MAE: 0.014448, R²: -0.0012
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.11212 | val 0.10690
  Epoch 020 - train 0.11094 | val 0.11254
  Regression -> MSE: 0.000349, MAE: 0.014552, R²: 0.0022
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.12981 | val 0.12231
  Epoch 020 - train 0.12341 | val 0.11797
  Regression -> MSE: 0.000207, MAE: 0.010145, R²: -0.0175
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.11464 | val 0.23455
  Epoch 020 - train 0.11302 | val 0.23549
  Regression -> MSE: 0.000598, MAE: 0.018947, R²: -0.0766
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.12521 | val 0.15249
  Epoch 020 - train 0.12490 | val 0.15188
  Regression -> MSE: 0.000251, MAE: 0.011951, R²: -0.0207
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.13331 | val 0.15084
  Epoch 020 - train 0.13001 | val 0.17050
  Regression -> MSE: 0.000606, MAE: 0.019374, R²: -0.0147
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.11565 | val 0.14795
  Epoch 020 - train 0.11866 | val 0.15517
  Regression -> MSE: 0.000400, MAE: 0.016052, R²: -0.0421
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.12724 | val 0.18297
  Epoch 020 - train 0.12162 | val 0.20217
  Regression -> MSE: 0.000242, MAE: 0.011962, R²: -0.0005
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.11757 | val 0.17606
  Epoch 020 - train 0.11930 | val 0.17763
  Regression -> MSE: 0.000311, MAE: 0.013687, R²: -0.0007
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.6301

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.12965 | val 0.14168
  Epoch 020 - train 0.12399 | val 0.14760
  Regression -> MSE: 0.000684, MAE: 0.019790, R²: -0.0106
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.12237 | val 0.13128
  Epoch 020 - train 0.11957 | val 0.15572
  Regression -> MSE: 0.000138, MAE: 0.009055, R²: -0.0013
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.11763 | val 0.16485
  Epoch 020 - train 0.11590 | val 0.16495
  Regression -> MSE: 0.000223, MAE: 0.010737, R²: 0.0065
  Directional -> Accuracy: 0.5246, MCC: 0.1312, F1: 0.6813

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.12657 | val 0.24559
  Epoch 020 - train 0.12542 | val 0.24472
  Regression -> MSE: 0.000366, MAE: 0.015965, R²: -0.0110
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.13496 | val 0.13228
  Epoch 020 - train 0.13083 | val 0.12959
  Regression -> MSE: 0.000110, MAE: 0.007965, R²: -0.0194
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.12839 | val 0.22107
  Epoch 020 - train 0.12888 | val 0.23878
  Regression -> MSE: 0.000160, MAE: 0.010057, R²: -0.0241
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.12816 | val 0.13668
  Epoch 020 - train 0.12518 | val 0.13926
  Regression -> MSE: 0.000281, MAE: 0.013487, R²: -0.0337
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.11106 | val 0.18074
  Epoch 020 - train 0.11098 | val 0.18046
  Regression -> MSE: 0.000167, MAE: 0.009127, R²: -0.1180
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.12963 | val 0.19215
  Epoch 020 - train 0.12493 | val 0.18884
  Regression -> MSE: 0.000227, MAE: 0.010915, R²: -0.0029
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.11995 | val 0.15353
  Epoch 020 - train 0.11912 | val 0.16170
  Regression -> MSE: 0.000148, MAE: 0.008581, R²: -0.0290
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.11665 | val 0.14780
  Epoch 020 - train 0.11272 | val 0.14933
  Regression -> MSE: 0.000168, MAE: 0.010289, R²: -0.0161
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.13165 | val 0.14317
  Epoch 020 - train 0.12967 | val 0.14382
  Regression -> MSE: 0.000086, MAE: 0.007080, R²: -0.0075
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.13085 | val 0.15690
  Epoch 020 - train 0.12710 | val 0.15540
  Regression -> MSE: 0.000215, MAE: 0.011050, R²: -0.0172
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.12348 | val 0.12041
  Epoch 020 - train 0.11743 | val 0.11834
  Regression -> MSE: 0.000100, MAE: 0.008211, R²: -0.0813
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.12314 | val 0.09699
  Epoch 020 - train 0.12029 | val 0.10437
  Regression -> MSE: 0.000109, MAE: 0.009002, R²: -0.0611
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.12769 | val 0.12304
  Epoch 020 - train 0.12434 | val 0.16048
  Regression -> MSE: 0.000232, MAE: 0.012583, R²: -0.0044
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.12578 | val 0.15044
  Epoch 020 - train 0.13020 | val 0.15273
  Regression -> MSE: 0.000173, MAE: 0.007854, R²: -0.0403
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.12861 | val 0.10668
  Epoch 020 - train 0.13169 | val 0.11400
  Regression -> MSE: 0.000237, MAE: 0.011869, R²: -0.0018
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.12731 | val 0.19367
  Epoch 020 - train 0.12555 | val 0.19420
  Regression -> MSE: 0.000231, MAE: 0.009937, R²: -0.0035
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.13304 | val 0.15586
  Epoch 020 - train 0.13436 | val 0.19292
  Regression -> MSE: 0.000137, MAE: 0.008293, R²: -0.0147
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.12697 | val 0.15196
  Epoch 020 - train 0.12315 | val 0.15150
  Regression -> MSE: 0.000196, MAE: 0.010563, R²: -0.0411
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.11253 | val 0.16111
  Epoch 020 - train 0.11059 | val 0.15979
  Regression -> MSE: 0.000270, MAE: 0.010629, R²: -0.0312
  Directional -> Accuracy: 0.4795, MCC: -0.1914, F1: 0.6346

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.13518 | val 0.10348
  Epoch 020 - train 0.12806 | val 0.10398
  Regression -> MSE: 0.000168, MAE: 0.010375, R²: -0.0055
  Directional -> Accuracy: 0.4474, MCC: -0.1091, F1: 0.5116

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.11667 | val 0.12882
  Epoch 020 - train 0.11044 | val 0.13638
  Regression -> MSE: 0.000182, MAE: 0.010408, R²: -0.0120
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.11564 | val 0.11892
  Epoch 020 - train 0.11850 | val 0.11731
  Regression -> MSE: 0.000346, MAE: 0.011721, R²: -0.0103
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.13278 | val 0.08274
  Epoch 020 - train 0.13472 | val 0.08662
  Regression -> MSE: 0.000111, MAE: 0.008298, R²: -0.0593
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.12798 | val 0.17704
  Epoch 020 - train 0.12847 | val 0.19446
  Regression -> MSE: 0.000219, MAE: 0.011325, R²: -0.0036
  Directional -> Accuracy: 0.4737, MCC: -0.0882, F1: 0.2857

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.11753 | val 0.20808
  Epoch 020 - train 0.12041 | val 0.20993
  Regression -> MSE: 0.000089, MAE: 0.007396, R²: -0.1498
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.11977 | val 0.09365
  Epoch 020 - train 0.12145 | val 0.09422
  Regression -> MSE: 0.000315, MAE: 0.014262, R²: -0.0246
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.13457 | val 0.07544
  Epoch 020 - train 0.13951 | val 0.07941
  Regression -> MSE: 0.000247, MAE: 0.011550, R²: -0.0123
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.0000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.11904 | val 0.15473
  Epoch 020 - train 0.11671 | val 0.15360
  Regression -> MSE: 0.000081, MAE: 0.007066, R²: -0.0013
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.12560 | val 0.15137
  Epoch 020 - train 0.12303 | val 0.14709
  Regression -> MSE: 0.000315, MAE: 0.014656, R²: -0.0262
  Directional -> Accuracy: 0.3617, MCC: -0.2940, F1: 0.4444

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.12914 | val 0.14262
  Epoch 020 - train 0.12606 | val 0.14709
  Regression -> MSE: 0.000100, MAE: 0.007123, R²: -0.0222
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.13356 | val 0.14462
  Epoch 020 - train 0.13030 | val 0.14160
  Regression -> MSE: 0.000174, MAE: 0.010072, R²: -0.0125
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.11576 | val 0.14078
  Epoch 020 - train 0.11727 | val 0.14392
  Regression -> MSE: 0.000227, MAE: 0.011848, R²: -0.0171
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.12646 | val 0.14482
  Epoch 020 - train 0.12367 | val 0.14969
  Regression -> MSE: 0.000094, MAE: 0.007722, R²: -0.0141
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.12823 | val 0.18893
  Epoch 020 - train 0.13123 | val 0.18723
  Regression -> MSE: 0.000166, MAE: 0.010295, R²: -0.0131
  Directional -> Accuracy: 0.4815, MCC: 0.0000, F1: 0.0000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.12006 | val 0.15172
  Epoch 020 - train 0.11974 | val 0.15317
  Regression -> MSE: 0.000120, MAE: 0.008962, R²: -0.0339
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.13066 | val 0.17882

[I 2026-02-23 00:59:38,993] Trial 163 finished with value: -0.011441263350652604 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 32, 'learning_rate': 2.7092863390896306e-06, 'weight_decay': 3.9516550075008986e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.1843152837969896, 'early_stopping_min_delta': 0.006546103684794348}. Best is trial 157 with value: -0.011387287234516647.

  Epoch 020 - train 0.13672 | val 0.18058
  Regression -> MSE: 0.000238, MAE: 0.012488, R²: -0.0027
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.07456 | val 0.10648
  Epoch 020 - train 0.07392 | val 0.10580
  Regression -> MSE: 0.000249, MAE: 0.012629, R²: -0.0076
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.07590 | val 0.07001
  Epoch 020 - train 0.07523 | val 0.07030
  Regression -> MSE: 0.000689, MAE: 0.019441, R²: -0.0060
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.07961 | val 0.12250
  Epoch 020 - train 0.08038 | val 0.13376
  Regression -> MSE: 0.000325, MAE: 0.014546, R²: -0.0476
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.06339 | val 0.07602
  Epoch 020 - train 0.06375 | val 0.07989
  Regression -> MSE: 0.000369, MAE: 0.014893, R²: -0.0557
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.08200 | val 0.07906
  Epoch 020 - train 0.07894 | val 0.08189
  Regression -> MSE: 0.000205, MAE: 0.010082, R²: -0.0070
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.06829 | val 0.13637
  Epoch 020 - train 0.07082 | val 0.13515
  Regression -> MSE: 0.000601, MAE: 0.019027, R²: -0.0828
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.07614 | val 0.09673
  Epoch 020 - train 0.07667 | val 0.09557
  Regression -> MSE: 0.000245, MAE: 0.011997, R²: -0.0000
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.07672 | val 0.10568
  Epoch 020 - train 0.07334 | val 0.09838
  Regression -> MSE: 0.000650, MAE: 0.020346, R²: -0.0874
  Directional -> Accuracy: 0.3636, MCC: -0.2106, F1: 0.4615

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.07097 | val 0.08941
  Epoch 020 - train 0.06884 | val 0.08700
  Regression -> MSE: 0.000392, MAE: 0.015952, R²: -0.0216
  Directional -> Accuracy: 0.5102, MCC: -0.0869, F1: 0.1429

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.07529 | val 0.09321
  Epoch 020 - train 0.07582 | val 0.09440
  Regression -> MSE: 0.000244, MAE: 0.012246, R²: -0.0104
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.07137 | val 0.10401
  Epoch 020 - train 0.07063 | val 0.10548
  Regression -> MSE: 0.000314, MAE: 0.013606, R²: -0.0100
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.07653 | val 0.08536
  Epoch 020 - train 0.07771 | val 0.08636
  Regression -> MSE: 0.000684, MAE: 0.019545, R²: -0.0106
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.07593 | val 0.07398
  Epoch 020 - train 0.07318 | val 0.07697
  Regression -> MSE: 0.000142, MAE: 0.009398, R²: -0.0312
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.07197 | val 0.09953
  Epoch 020 - train 0.07241 | val 0.09888
  Regression -> MSE: 0.000226, MAE: 0.010835, R²: -0.0051
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.07336 | val 0.15234
  Epoch 020 - train 0.07445 | val 0.16018
  Regression -> MSE: 0.000362, MAE: 0.016071, R²: -0.0006
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.08071 | val 0.08725
  Epoch 020 - train 0.08097 | val 0.08717
  Regression -> MSE: 0.000108, MAE: 0.007995, R²: -0.0040
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.07244 | val 0.12524
  Epoch 020 - train 0.07158 | val 0.13092
  Regression -> MSE: 0.000156, MAE: 0.009762, R²: -0.0036
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.08001 | val 0.07668
  Epoch 020 - train 0.07744 | val 0.07765
  Regression -> MSE: 0.000276, MAE: 0.013250, R²: -0.0138
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.07239 | val 0.10196
  Epoch 020 - train 0.07281 | val 0.10117
  Regression -> MSE: 0.000170, MAE: 0.009231, R²: -0.1383
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.07565 | val 0.11476
  Epoch 020 - train 0.07663 | val 0.11745
  Regression -> MSE: 0.000233, MAE: 0.010930, R²: -0.0318
  Directional -> Accuracy: 0.5600, MCC: 0.1421, F1: 0.5352

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.07768 | val 0.09806
  Epoch 020 - train 0.07648 | val 0.10925
  Regression -> MSE: 0.000147, MAE: 0.008537, R²: -0.0248
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.07560 | val 0.09625
  Epoch 020 - train 0.07221 | val 0.09741
  Regression -> MSE: 0.000166, MAE: 0.010718, R²: -0.0076
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.07723 | val 0.09387
  Epoch 020 - train 0.07593 | val 0.09649
  Regression -> MSE: 0.000086, MAE: 0.007061, R²: -0.0043
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.07668 | val 0.12918
  Epoch 020 - train 0.07570 | val 0.12886
  Regression -> MSE: 0.000215, MAE: 0.011059, R²: -0.0146
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.06947 | val 0.07082
  Epoch 020 - train 0.06879 | val 0.07048
  Regression -> MSE: 0.000099, MAE: 0.008210, R²: -0.0768
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.07568 | val 0.06342
  Epoch 020 - train 0.07567 | val 0.06686
  Regression -> MSE: 0.000113, MAE: 0.009125, R²: -0.1002
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.07886 | val 0.07457
  Epoch 020 - train 0.07871 | val 0.07761
  Regression -> MSE: 0.000232, MAE: 0.012499, R²: -0.0013
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.07423 | val 0.09261
  Epoch 020 - train 0.07366 | val 0.09446
  Regression -> MSE: 0.000178, MAE: 0.007923, R²: -0.0678
  Directional -> Accuracy: 0.4737, MCC: 0.0728, F1: 0.2105

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.08098 | val 0.06407
  Epoch 020 - train 0.07700 | val 0.06472
  Regression -> MSE: 0.000237, MAE: 0.011886, R²: -0.0033
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.07178 | val 0.11705
  Epoch 020 - train 0.07524 | val 0.11452
  Regression -> MSE: 0.000233, MAE: 0.010047, R²: -0.0129
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.07946 | val 0.08715
  Epoch 020 - train 0.07914 | val 0.08881
  Regression -> MSE: 0.000135, MAE: 0.008198, R²: -0.0013
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.08068 | val 0.09325
  Epoch 020 - train 0.07639 | val 0.09218
  Regression -> MSE: 0.000188, MAE: 0.010496, R²: -0.0006
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.06875 | val 0.09603
  Epoch 020 - train 0.06794 | val 0.09575
  Regression -> MSE: 0.000275, MAE: 0.010803, R²: -0.0501
  Directional -> Accuracy: 0.4384, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.07509 | val 0.06415
  Epoch 020 - train 0.07303 | val 0.06510
  Regression -> MSE: 0.000167, MAE: 0.010375, R²: -0.0019
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.06964 | val 0.07663
  Epoch 020 - train 0.06805 | val 0.07526
  Regression -> MSE: 0.000184, MAE: 0.010479, R²: -0.0221
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.06955 | val 0.07001
  Epoch 020 - train 0.06907 | val 0.07101
  Regression -> MSE: 0.000342, MAE: 0.011883, R²: 0.0013
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.07987 | val 0.05239
  Epoch 020 - train 0.08066 | val 0.05281
  Regression -> MSE: 0.000109, MAE: 0.008362, R²: -0.0347
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.07781 | val 0.11187
  Epoch 020 - train 0.07656 | val 0.12272
  Regression -> MSE: 0.000222, MAE: 0.011402, R²: -0.0172
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.07416 | val 0.12414
  Epoch 020 - train 0.07489 | val 0.12505
  Regression -> MSE: 0.000088, MAE: 0.007340, R²: -0.1329
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.07312 | val 0.05637
  Epoch 020 - train 0.07642 | val 0.05550
  Regression -> MSE: 0.000308, MAE: 0.013753, R²: -0.0021
  Directional -> Accuracy: 0.6327, MCC: 0.0000, F1: 0.0000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.07923 | val 0.04928
  Epoch 020 - train 0.07375 | val 0.04927
  Regression -> MSE: 0.000257, MAE: 0.011479, R²: -0.0551
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.07763 | val 0.09139
  Epoch 020 - train 0.07551 | val 0.09126
  Regression -> MSE: 0.000084, MAE: 0.007051, R²: -0.0353
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.07645 | val 0.09030
  Epoch 020 - train 0.07650 | val 0.09653
  Regression -> MSE: 0.000310, MAE: 0.014521, R²: -0.0091
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.06814 | val 0.08169
  Epoch 020 - train 0.06709 | val 0.08628
  Regression -> MSE: 0.000099, MAE: 0.007213, R²: -0.0037
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.08019 | val 0.08697
  Epoch 020 - train 0.07901 | val 0.08748
  Regression -> MSE: 0.000172, MAE: 0.009740, R²: -0.0008
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.07157 | val 0.08552
  Epoch 020 - train 0.06924 | val 0.08740
  Regression -> MSE: 0.000224, MAE: 0.011781, R²: -0.0038
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.07650 | val 0.08337
  Epoch 020 - train 0.07790 | val 0.08277
  Regression -> MSE: 0.000093, MAE: 0.007671, R²: -0.0055
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.08067 | val 0.11353
  Epoch 020 - train 0.07637 | val 0.11369
  Regression -> MSE: 0.000165, MAE: 0.010284, R²: -0.0051
  Directional -> Accuracy: 0.5370, MCC: 0.0899, F1: 0.6835

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.07409 | val 0.09188
  Epoch 020 - train 0.07501 | val 0.09408
  Regression -> MSE: 0.000121, MAE: 0.008983, R²: -0.0465
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.07605 | val 0.11423

[I 2026-02-23 01:02:16,723] Trial 164 finished with value: -0.011461803418428618 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 32, 'learning_rate': 2.8288254420632205e-06, 'weight_decay': 7.671703967230985e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.10624039640208294, 'early_stopping_min_delta': 0.006437650640207638}. Best is trial 157 with value: -0.011387287234516647.

  Epoch 020 - train 0.07514 | val 0.12062
  Regression -> MSE: 0.000237, MAE: 0.012430, R²: -0.0007
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.12023 | val 0.16264
  Epoch 020 - train 0.12175 | val 0.16330
  Regression -> MSE: 0.000249, MAE: 0.012619, R²: -0.0071
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.13084 | val 0.11377
  Epoch 020 - train 0.13378 | val 0.11496
  Regression -> MSE: 0.000726, MAE: 0.020028, R²: -0.0612
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.12817 | val 0.20134
  Epoch 020 - train 0.12610 | val 0.20402
  Regression -> MSE: 0.000311, MAE: 0.014404, R²: -0.0012
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.10567 | val 0.13306
  Epoch 020 - train 0.10178 | val 0.12983
  Regression -> MSE: 0.000354, MAE: 0.014658, R²: -0.0148
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.12205 | val 0.12946
  Epoch 020 - train 0.12327 | val 0.13249
  Regression -> MSE: 0.000205, MAE: 0.010252, R²: -0.0059
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.12136 | val 0.22856
  Epoch 020 - train 0.11883 | val 0.23159
  Regression -> MSE: 0.000565, MAE: 0.018252, R²: -0.0174
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.12855 | val 0.15436
  Epoch 020 - train 0.12597 | val 0.15325
  Regression -> MSE: 0.000247, MAE: 0.012288, R²: -0.0072
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.12138 | val 0.16851
  Epoch 020 - train 0.12615 | val 0.14312
  Regression -> MSE: 0.000608, MAE: 0.019489, R²: -0.0182
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.12655 | val 0.15851
  Epoch 020 - train 0.12678 | val 0.16096
  Regression -> MSE: 0.000385, MAE: 0.016165, R²: -0.0025
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.12249 | val 0.15565
  Epoch 020 - train 0.12604 | val 0.15563
  Regression -> MSE: 0.000242, MAE: 0.011836, R²: -0.0026
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.12034 | val 0.21786
  Epoch 020 - train 0.12151 | val 0.26071
  Regression -> MSE: 0.000312, MAE: 0.013817, R²: -0.0021
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.6301

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.12735 | val 0.14585
  Epoch 020 - train 0.12709 | val 0.14909
  Regression -> MSE: 0.000682, MAE: 0.019541, R²: -0.0075
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.12606 | val 0.15677
  Epoch 020 - train 0.12391 | val 0.20431
  Regression -> MSE: 0.000138, MAE: 0.009025, R²: -0.0005
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.11717 | val 0.16375
  Epoch 020 - train 0.11028 | val 0.16079
  Regression -> MSE: 0.000239, MAE: 0.011180, R²: -0.0604
  Directional -> Accuracy: 0.4918, MCC: -0.0226, F1: 0.5634

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.12257 | val 0.25171
  Epoch 020 - train 0.12425 | val 0.27819
  Regression -> MSE: 0.000363, MAE: 0.016200, R²: -0.0018
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.12799 | val 0.12887
  Epoch 020 - train 0.12175 | val 0.12947
  Regression -> MSE: 0.000108, MAE: 0.008074, R²: -0.0025
  Directional -> Accuracy: 0.4571, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.12268 | val 0.23565
  Epoch 020 - train 0.12000 | val 0.24991
  Regression -> MSE: 0.000157, MAE: 0.009889, R²: -0.0084
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.12590 | val 0.14360
  Epoch 020 - train 0.12134 | val 0.14700
  Regression -> MSE: 0.000273, MAE: 0.013006, R²: -0.0020
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.10859 | val 0.17175
  Epoch 020 - train 0.11104 | val 0.17305
  Regression -> MSE: 0.000164, MAE: 0.009052, R²: -0.0972
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.12752 | val 0.17472
  Epoch 020 - train 0.12306 | val 0.17430
  Regression -> MSE: 0.000248, MAE: 0.011283, R²: -0.0970
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.13002 | val 0.15381
  Epoch 020 - train 0.12663 | val 0.15361
  Regression -> MSE: 0.000153, MAE: 0.008816, R²: -0.0669
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.11884 | val 0.14015
  Epoch 020 - train 0.11881 | val 0.14031
  Regression -> MSE: 0.000182, MAE: 0.010352, R²: -0.0990
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.12855 | val 0.15093
  Epoch 020 - train 0.12903 | val 0.15181
  Regression -> MSE: 0.000091, MAE: 0.007354, R²: -0.0700
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.12577 | val 0.19827
  Epoch 020 - train 0.12149 | val 0.20178
  Regression -> MSE: 0.000213, MAE: 0.011285, R²: -0.0054
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.11821 | val 0.11280
  Epoch 020 - train 0.11194 | val 0.11138
  Regression -> MSE: 0.000098, MAE: 0.008185, R²: -0.0678
  Directional -> Accuracy: 0.4821, MCC: -0.0054, F1: 0.4314

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.12562 | val 0.09643
  Epoch 020 - train 0.12313 | val 0.09768
  Regression -> MSE: 0.000104, MAE: 0.008760, R²: -0.0048
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.13055 | val 0.12017
  Epoch 020 - train 0.13058 | val 0.12363
  Regression -> MSE: 0.000231, MAE: 0.012517, R²: -0.0000
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.11794 | val 0.14453
  Epoch 020 - train 0.12184 | val 0.14454
  Regression -> MSE: 0.000171, MAE: 0.007830, R²: -0.0295
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.13035 | val 0.11107
  Epoch 020 - train 0.12834 | val 0.10786
  Regression -> MSE: 0.000241, MAE: 0.012061, R²: -0.0178
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.12482 | val 0.20364
  Epoch 020 - train 0.12381 | val 0.21498
  Regression -> MSE: 0.000236, MAE: 0.010182, R²: -0.0220
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.13775 | val 0.15998
  Epoch 020 - train 0.13139 | val 0.16926
  Regression -> MSE: 0.000140, MAE: 0.008439, R²: -0.0361
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.13669 | val 0.16523
  Epoch 020 - train 0.13545 | val 0.16865
  Regression -> MSE: 0.000188, MAE: 0.010521, R²: 0.0003
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.11237 | val 0.15229
  Epoch 020 - train 0.11072 | val 0.15190
  Regression -> MSE: 0.000263, MAE: 0.010520, R²: -0.0056
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.13334 | val 0.10364
  Epoch 020 - train 0.13305 | val 0.10498
  Regression -> MSE: 0.000170, MAE: 0.010369, R²: -0.0186
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.11691 | val 0.12969
  Epoch 020 - train 0.11709 | val 0.13799
  Regression -> MSE: 0.000181, MAE: 0.010375, R²: -0.0074
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.11544 | val 0.11715
  Epoch 020 - train 0.11011 | val 0.11737
  Regression -> MSE: 0.000344, MAE: 0.011693, R²: -0.0041
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.13186 | val 0.07982
  Epoch 020 - train 0.13380 | val 0.08126
  Regression -> MSE: 0.000120, MAE: 0.008366, R²: -0.1396
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.12756 | val 0.17745
  Epoch 020 - train 0.12710 | val 0.17997
  Regression -> MSE: 0.000220, MAE: 0.011334, R²: -0.0070
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.12764 | val 0.22501
  Epoch 020 - train 0.12487 | val 0.24259
  Regression -> MSE: 0.000081, MAE: 0.006987, R²: -0.0369
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.12495 | val 0.10998
  Epoch 020 - train 0.12469 | val 0.11895
  Regression -> MSE: 0.000342, MAE: 0.015437, R²: -0.1131
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.13691 | val 0.07817
  Epoch 020 - train 0.13481 | val 0.08782
  Regression -> MSE: 0.000245, MAE: 0.011581, R²: -0.0052
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.0000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.11851 | val 0.15145
  Epoch 020 - train 0.11671 | val 0.15161
  Regression -> MSE: 0.000081, MAE: 0.007128, R²: -0.0081
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.13209 | val 0.16807
  Epoch 020 - train 0.12868 | val 0.17735
  Regression -> MSE: 0.000313, MAE: 0.014504, R²: -0.0215
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.12053 | val 0.14191
  Epoch 020 - train 0.11870 | val 0.14576
  Regression -> MSE: 0.000100, MAE: 0.007116, R²: -0.0185
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.13225 | val 0.14890
  Epoch 020 - train 0.13294 | val 0.15046
  Regression -> MSE: 0.000173, MAE: 0.009466, R²: -0.0090
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.11120 | val 0.14170
  Epoch 020 - train 0.11548 | val 0.14325
  Regression -> MSE: 0.000225, MAE: 0.011788, R²: -0.0094
  Directional -> Accuracy: 0.5000, MCC: 0.1792, F1: 0.1250

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.11901 | val 0.14681
  Epoch 020 - train 0.12061 | val 0.15771
  Regression -> MSE: 0.000093, MAE: 0.007681, R²: -0.0081
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.13060 | val 0.19403
  Epoch 020 - train 0.12907 | val 0.19785
  Regression -> MSE: 0.000168, MAE: 0.010325, R²: -0.0280
  Directional -> Accuracy: 0.4815, MCC: 0.0000, F1: 0.0000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.12688 | val 0.16235
  Epoch 020 - train 0.12561 | val 0.16370
  Regression -> MSE: 0.000117, MAE: 0.008941, R²: -0.0118
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.12322 | val 0.17117

[I 2026-02-23 01:04:50,555] Trial 165 finished with value: -0.0114661884838817 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 32, 'learning_rate': 4.009453407346569e-06, 'weight_decay': 6.173605270092738e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.18462675118026492, 'early_stopping_min_delta': 0.006568835311295703}. Best is trial 157 with value: -0.011387287234516647.

  Epoch 020 - train 0.12350 | val 0.17316
  Regression -> MSE: 0.000243, MAE: 0.012341, R²: -0.0247
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.22284 | val 0.35420
  Epoch 020 - train 0.22787 | val 0.35230
  Regression -> MSE: 0.000248, MAE: 0.012577, R²: -0.0031
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.23288 | val 0.21265
  Epoch 020 - train 0.22819 | val 0.21881
  Regression -> MSE: 0.000728, MAE: 0.020063, R²: -0.0629
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.23550 | val 0.38019
  Epoch 020 - train 0.23742 | val 0.37249
  Regression -> MSE: 0.000317, MAE: 0.014342, R²: -0.0224
  Directional -> Accuracy: 0.4894, MCC: -0.0255, F1: 0.5200

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.18959 | val 0.23954
  Epoch 020 - train 0.19063 | val 0.23285
  Regression -> MSE: 0.000354, MAE: 0.014659, R²: -0.0133
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.23881 | val 0.23762
  Epoch 020 - train 0.22980 | val 0.24057
  Regression -> MSE: 0.000204, MAE: 0.010098, R²: -0.0014
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.20817 | val 0.45124
  Epoch 020 - train 0.22107 | val 0.46534
  Regression -> MSE: 0.000565, MAE: 0.018262, R²: -0.0179
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.24257 | val 0.29430
  Epoch 020 - train 0.23332 | val 0.28815
  Regression -> MSE: 0.000247, MAE: 0.012228, R²: -0.0053
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.21802 | val 0.30775
  Epoch 020 - train 0.22860 | val 0.28278
  Regression -> MSE: 0.000602, MAE: 0.018892, R²: -0.0084
  Directional -> Accuracy: 0.6364, MCC: 0.2170, F1: 0.4667

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.21519 | val 0.27424
  Epoch 020 - train 0.22132 | val 0.28167
  Regression -> MSE: 0.000402, MAE: 0.016097, R²: -0.0484
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.23208 | val 0.32182
  Epoch 020 - train 0.22885 | val 0.33410
  Regression -> MSE: 0.000242, MAE: 0.011925, R²: -0.0015
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.21192 | val 0.32884
  Epoch 020 - train 0.21278 | val 0.34304
  Regression -> MSE: 0.000326, MAE: 0.013608, R²: -0.0469
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.24801 | val 0.29487
  Epoch 020 - train 0.24431 | val 0.33456
  Regression -> MSE: 0.000687, MAE: 0.019876, R²: -0.0151
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.24827 | val 0.22561
  Epoch 020 - train 0.24278 | val 0.22424
  Regression -> MSE: 0.000145, MAE: 0.009517, R²: -0.0495
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.20294 | val 0.30868
  Epoch 020 - train 0.20353 | val 0.31709
  Regression -> MSE: 0.000227, MAE: 0.010729, R²: -0.0074
  Directional -> Accuracy: 0.4918, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.21499 | val 0.48903
  Epoch 020 - train 0.21430 | val 0.49532
  Regression -> MSE: 0.000363, MAE: 0.016094, R²: -0.0012
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.23559 | val 0.23170
  Epoch 020 - train 0.23924 | val 0.23066
  Regression -> MSE: 0.000106, MAE: 0.007840, R²: 0.0155
  Directional -> Accuracy: 0.6429, MCC: 0.2753, F1: 0.7126

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.23725 | val 0.39643
  Epoch 020 - train 0.23643 | val 0.40371
  Regression -> MSE: 0.000158, MAE: 0.009947, R²: -0.0142
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.23473 | val 0.23716
  Epoch 020 - train 0.24113 | val 0.23842
  Regression -> MSE: 0.000285, MAE: 0.013626, R²: -0.0471
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.22300 | val 0.34904
  Epoch 020 - train 0.21816 | val 0.35252
  Regression -> MSE: 0.000153, MAE: 0.008766, R²: -0.0206
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.24180 | val 0.45024
  Epoch 020 - train 0.23854 | val 0.44677
  Regression -> MSE: 0.000228, MAE: 0.011004, R²: -0.0068
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.22940 | val 0.29995
  Epoch 020 - train 0.22699 | val 0.33191
  Regression -> MSE: 0.000151, MAE: 0.008719, R²: -0.0519
  Directional -> Accuracy: 0.5208, MCC: -0.0337, F1: 0.6230

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.24042 | val 0.28460
  Epoch 020 - train 0.23698 | val 0.28254
  Regression -> MSE: 0.000185, MAE: 0.010408, R²: -0.1173
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.25235 | val 0.28439
  Epoch 020 - train 0.24977 | val 0.28495
  Regression -> MSE: 0.000085, MAE: 0.007024, R²: -0.0021
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.22752 | val 0.28321
  Epoch 020 - train 0.22658 | val 0.27752
  Regression -> MSE: 0.000213, MAE: 0.011363, R²: -0.0075
  Directional -> Accuracy: 0.4848, MCC: 0.0201, F1: 0.6136

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.23456 | val 0.20860
  Epoch 020 - train 0.22529 | val 0.20276
  Regression -> MSE: 0.000105, MAE: 0.008360, R²: -0.1432
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.22885 | val 0.18601
  Epoch 020 - train 0.23923 | val 0.17587
  Regression -> MSE: 0.000111, MAE: 0.008839, R²: -0.0785
  Directional -> Accuracy: 0.5000, MCC: 0.1654, F1: 0.6230

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.23752 | val 0.22334
  Epoch 020 - train 0.24461 | val 0.22365
  Regression -> MSE: 0.000242, MAE: 0.012892, R²: -0.0454
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.24671 | val 0.30123
  Epoch 020 - train 0.23419 | val 0.30491
  Regression -> MSE: 0.000169, MAE: 0.007789, R²: -0.0142
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.24983 | val 0.19076
  Epoch 020 - train 0.25220 | val 0.18979
  Regression -> MSE: 0.000237, MAE: 0.011864, R²: -0.0007
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.22351 | val 0.37835
  Epoch 020 - train 0.23056 | val 0.39002
  Regression -> MSE: 0.000231, MAE: 0.009902, R²: -0.0033
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.23987 | val 0.29033
  Epoch 020 - train 0.23424 | val 0.28893
  Regression -> MSE: 0.000137, MAE: 0.008293, R²: -0.0116
  Directional -> Accuracy: 0.5116, MCC: 0.0217, F1: 0.5333

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.22714 | val 0.29375
  Epoch 020 - train 0.22334 | val 0.29542
  Regression -> MSE: 0.000189, MAE: 0.010423, R²: -0.0036
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.21007 | val 0.28127
  Epoch 020 - train 0.20820 | val 0.27966
  Regression -> MSE: 0.000276, MAE: 0.010819, R²: -0.0541
  Directional -> Accuracy: 0.4384, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.21999 | val 0.19370
  Epoch 020 - train 0.21307 | val 0.18613
  Regression -> MSE: 0.000166, MAE: 0.010406, R²: 0.0013
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.20602 | val 0.23200
  Epoch 020 - train 0.20653 | val 0.24297
  Regression -> MSE: 0.000180, MAE: 0.010320, R²: 0.0006
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.21084 | val 0.20365
  Epoch 020 - train 0.21339 | val 0.20315
  Regression -> MSE: 0.000341, MAE: 0.011947, R²: 0.0048
  Directional -> Accuracy: 0.4925, MCC: 0.0538, F1: 0.3929

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.24119 | val 0.13998
  Epoch 020 - train 0.24292 | val 0.15472
  Regression -> MSE: 0.000117, MAE: 0.008352, R²: -0.1124
  Directional -> Accuracy: 0.4419, MCC: -0.1596, F1: 0.5714

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.24434 | val 0.31640
  Epoch 020 - train 0.23205 | val 0.31897
  Regression -> MSE: 0.000220, MAE: 0.011321, R²: -0.0045
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.22534 | val 0.40697
  Epoch 020 - train 0.23158 | val 0.41541
  Regression -> MSE: 0.000086, MAE: 0.007250, R²: -0.1076
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.22276 | val 0.18812
  Epoch 020 - train 0.23842 | val 0.18781
  Regression -> MSE: 0.000329, MAE: 0.014929, R²: -0.0682
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.25071 | val 0.13003
  Epoch 020 - train 0.24384 | val 0.13917
  Regression -> MSE: 0.000245, MAE: 0.011550, R²: -0.0042
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.0000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.22917 | val 0.29254
  Epoch 020 - train 0.22466 | val 0.29021
  Regression -> MSE: 0.000083, MAE: 0.007052, R²: -0.0249
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.23274 | val 0.28850
  Epoch 020 - train 0.23270 | val 0.29113
  Regression -> MSE: 0.000309, MAE: 0.014519, R²: -0.0059
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.24427 | val 0.24846
  Epoch 020 - train 0.23560 | val 0.24225
  Regression -> MSE: 0.000102, MAE: 0.007371, R²: -0.0436
  Directional -> Accuracy: 0.4091, MCC: -0.2206, F1: 0.5000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.25650 | val 0.28917
  Epoch 020 - train 0.25750 | val 0.32120
  Regression -> MSE: 0.000172, MAE: 0.009550, R²: -0.0023
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.22339 | val 0.27062
  Epoch 020 - train 0.21852 | val 0.26947
  Regression -> MSE: 0.000224, MAE: 0.011785, R²: -0.0027
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.22545 | val 0.25884
  Epoch 020 - train 0.21776 | val 0.26114
  Regression -> MSE: 0.000095, MAE: 0.007819, R²: -0.0286
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.24882 | val 0.36525
  Epoch 020 - train 0.24671 | val 0.38125
  Regression -> MSE: 0.000168, MAE: 0.010361, R²: -0.0253
  Directional -> Accuracy: 0.4259, MCC: -0.1437, F1: 0.3404

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.22127 | val 0.30478
  Epoch 020 - train 0.21835 | val 0.30862
  Regression -> MSE: 0.000119, MAE: 0.008969, R²: -0.0290
  Directional -> Accuracy: 0.4107, MCC: -0.2188, F1: 0.1081

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.23180 | val 0.35558

[I 2026-02-23 01:07:27,842] Trial 166 finished with value: -0.011453559442517627 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 32, 'learning_rate': 2.182924165224902e-06, 'weight_decay': 0.00010698087504579206, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.390700018943921, 'early_stopping_min_delta': 0.00587190115385748}. Best is trial 157 with value: -0.011387287234516647.

  Epoch 020 - train 0.23784 | val 0.37181
  Regression -> MSE: 0.000238, MAE: 0.012333, R²: -0.0020
  Directional -> Accuracy: 0.6066, MCC: 0.2103, F1: 0.5000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.24335 | val 0.32245
  Epoch 020 - train 0.24096 | val 0.32151
  Regression -> MSE: 0.000248, MAE: 0.012566, R²: -0.0018
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.26360 | val 0.22302
  Epoch 020 - train 0.25949 | val 0.28901
  Regression -> MSE: 0.000704, MAE: 0.019686, R²: -0.0291
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.25470 | val 0.41068
  Epoch 020 - train 0.25282 | val 0.41551
  Regression -> MSE: 0.000319, MAE: 0.014517, R²: -0.0294
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.19972 | val 0.21328
  Epoch 020 - train 0.19776 | val 0.20712
  Regression -> MSE: 0.000351, MAE: 0.014607, R²: -0.0054
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.26493 | val 0.26898
  Epoch 020 - train 0.25960 | val 0.28035
  Regression -> MSE: 0.000206, MAE: 0.010404, R²: -0.0122
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.22691 | val 0.47127
  Epoch 020 - train 0.22949 | val 0.49769
  Regression -> MSE: 0.000556, MAE: 0.018182, R²: -0.0017
  Directional -> Accuracy: 0.4894, MCC: 0.0000, F1: 0.6571

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.25072 | val 0.29779
  Epoch 020 - train 0.24574 | val 0.29240
  Regression -> MSE: 0.000274, MAE: 0.013446, R²: -0.1167
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.23707 | val 0.35500
  Epoch 020 - train 0.24804 | val 0.33420
  Regression -> MSE: 0.000605, MAE: 0.019101, R²: -0.0131
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.22394 | val 0.29576
  Epoch 020 - train 0.21680 | val 0.28966
  Regression -> MSE: 0.000421, MAE: 0.016217, R²: -0.0985
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.23943 | val 0.31513
  Epoch 020 - train 0.23360 | val 0.31661
  Regression -> MSE: 0.000242, MAE: 0.012028, R²: -0.0018
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.21840 | val 0.38738
  Epoch 020 - train 0.21119 | val 0.43657
  Regression -> MSE: 0.000313, MAE: 0.013604, R²: -0.0051
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.25612 | val 0.31305
  Epoch 020 - train 0.25318 | val 0.32398
  Regression -> MSE: 0.000687, MAE: 0.019865, R²: -0.0150
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.23524 | val 0.24654
  Epoch 020 - train 0.22937 | val 0.28032
  Regression -> MSE: 0.000141, MAE: 0.009310, R²: -0.0172
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.23004 | val 0.33137
  Epoch 020 - train 0.23388 | val 0.33657
  Regression -> MSE: 0.000228, MAE: 0.010764, R²: -0.0127
  Directional -> Accuracy: 0.4918, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.23802 | val 0.50771
  Epoch 020 - train 0.23771 | val 0.52368
  Regression -> MSE: 0.000368, MAE: 0.015954, R²: -0.0163
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.24759 | val 0.25231
  Epoch 020 - train 0.24368 | val 0.25835
  Regression -> MSE: 0.000108, MAE: 0.007982, R²: 0.0013
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.23747 | val 0.40789
  Epoch 020 - train 0.23544 | val 0.42680
  Regression -> MSE: 0.000158, MAE: 0.009924, R²: -0.0135
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.23483 | val 0.37275
  Epoch 020 - train 0.24026 | val 0.38708
  Regression -> MSE: 0.000285, MAE: 0.013642, R²: -0.0484
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.22053 | val 0.32586
  Epoch 020 - train 0.22253 | val 0.32371
  Regression -> MSE: 0.000174, MAE: 0.009360, R²: -0.1661
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.24169 | val 0.40112
  Epoch 020 - train 0.24397 | val 0.39810
  Regression -> MSE: 0.000248, MAE: 0.011278, R²: -0.0966
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.23839 | val 0.30968
  Epoch 020 - train 0.22745 | val 0.31889
  Regression -> MSE: 0.000145, MAE: 0.008451, R²: -0.0110
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.21857 | val 0.29280
  Epoch 020 - train 0.22670 | val 0.29662
  Regression -> MSE: 0.000172, MAE: 0.010252, R²: -0.0420
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.26152 | val 0.31988
  Epoch 020 - train 0.26192 | val 0.32341
  Regression -> MSE: 0.000093, MAE: 0.007416, R²: -0.0863
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.23622 | val 0.34435
  Epoch 020 - train 0.23603 | val 0.36236
  Regression -> MSE: 0.000213, MAE: 0.011056, R²: -0.0066
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.21608 | val 0.20236
  Epoch 020 - train 0.21521 | val 0.19970
  Regression -> MSE: 0.000098, MAE: 0.008286, R²: -0.0635
  Directional -> Accuracy: 0.4643, MCC: -0.1124, F1: 0.5588

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.26094 | val 0.19199
  Epoch 020 - train 0.24259 | val 0.19242
  Regression -> MSE: 0.000114, MAE: 0.009147, R²: -0.1026
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.24248 | val 0.22443
  Epoch 020 - train 0.23993 | val 0.23498
  Regression -> MSE: 0.000232, MAE: 0.012509, R²: -0.0006
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.25001 | val 0.33478
  Epoch 020 - train 0.24445 | val 0.34287
  Regression -> MSE: 0.000169, MAE: 0.007827, R²: -0.0153
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.25089 | val 0.19281
  Epoch 020 - train 0.24420 | val 0.20193
  Regression -> MSE: 0.000238, MAE: 0.011918, R²: -0.0070
  Directional -> Accuracy: 0.5610, MCC: 0.1145, F1: 0.7000

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.25364 | val 0.38544
  Epoch 020 - train 0.25345 | val 0.38514
  Regression -> MSE: 0.000231, MAE: 0.009869, R²: -0.0017
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.25739 | val 0.30094
  Epoch 020 - train 0.24991 | val 0.29534
  Regression -> MSE: 0.000136, MAE: 0.008295, R²: -0.0040
  Directional -> Accuracy: 0.5581, MCC: 0.1504, F1: 0.4865

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.24896 | val 0.30959
  Epoch 020 - train 0.24015 | val 0.30890
  Regression -> MSE: 0.000188, MAE: 0.010432, R²: 0.0008
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.21878 | val 0.27125
  Epoch 020 - train 0.21836 | val 0.27088
  Regression -> MSE: 0.000267, MAE: 0.010553, R²: -0.0190
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.22695 | val 0.19635
  Epoch 020 - train 0.23364 | val 0.19416
  Regression -> MSE: 0.000168, MAE: 0.010374, R²: -0.0067
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.21071 | val 0.25895
  Epoch 020 - train 0.20972 | val 0.27517
  Regression -> MSE: 0.000188, MAE: 0.010615, R²: -0.0435
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.25396 | val 0.22918
  Epoch 020 - train 0.24058 | val 0.22893
  Regression -> MSE: 0.000354, MAE: 0.012662, R²: -0.0334
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.25129 | val 0.14388
  Epoch 020 - train 0.25518 | val 0.16429
  Regression -> MSE: 0.000124, MAE: 0.008446, R²: -0.1832
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.24227 | val 0.34092
  Epoch 020 - train 0.23982 | val 0.35283
  Regression -> MSE: 0.000219, MAE: 0.011287, R²: -0.0002
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.23596 | val 0.42588
  Epoch 020 - train 0.23446 | val 0.43049
  Regression -> MSE: 0.000088, MAE: 0.007320, R²: -0.1275
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.26177 | val 0.19942
  Epoch 020 - train 0.24404 | val 0.23672
  Regression -> MSE: 0.000331, MAE: 0.015034, R²: -0.0767
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.26189 | val 0.14088
  Epoch 020 - train 0.25564 | val 0.12976
  Regression -> MSE: 0.000258, MAE: 0.011564, R²: -0.0571
  Directional -> Accuracy: 0.5000, MCC: -0.0574, F1: 0.6415

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.23695 | val 0.28817
  Epoch 020 - train 0.23437 | val 0.28820
  Regression -> MSE: 0.000089, MAE: 0.007165, R²: -0.1044
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.23211 | val 0.30065
  Epoch 020 - train 0.23969 | val 0.32758
  Regression -> MSE: 0.000309, MAE: 0.014529, R²: -0.0083
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.22242 | val 0.28892
  Epoch 020 - train 0.21830 | val 0.27648
  Regression -> MSE: 0.000093, MAE: 0.007055, R²: 0.0512
  Directional -> Accuracy: 0.5909, MCC: 0.1474, F1: 0.6667

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.27042 | val 0.30362
  Epoch 020 - train 0.26789 | val 0.34482
  Regression -> MSE: 0.000172, MAE: 0.009532, R²: -0.0036
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.22060 | val 0.25803
  Epoch 020 - train 0.22076 | val 0.26343
  Regression -> MSE: 0.000221, MAE: 0.011454, R²: 0.0073
  Directional -> Accuracy: 0.5893, MCC: 0.2108, F1: 0.7160

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.23512 | val 0.28840
  Epoch 020 - train 0.24604 | val 0.28726
  Regression -> MSE: 0.000095, MAE: 0.007787, R²: -0.0247
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.25525 | val 0.38738
  Epoch 020 - train 0.24490 | val 0.39949
  Regression -> MSE: 0.000164, MAE: 0.010247, R²: -0.0008
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.25507 | val 0.33270
  Epoch 020 - train 0.25183 | val 0.33871
  Regression -> MSE: 0.000134, MAE: 0.009192, R²: -0.1551
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.24658 | val 0.37425

[I 2026-02-23 01:10:05,733] Trial 167 finished with value: -0.011500742573138274 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 32, 'learning_rate': 2.2004310891780943e-06, 'weight_decay': 0.0001387575038637532, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.409917732231768, 'early_stopping_min_delta': 0.005428718267597438}. Best is trial 157 with value: -0.011387287234516647.

  Epoch 020 - train 0.24406 | val 0.39178
  Regression -> MSE: 0.000239, MAE: 0.012329, R²: -0.0070
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.13650 | val 0.18130
  Epoch 020 - train 0.13083 | val 0.18146
  Regression -> MSE: 0.000256, MAE: 0.012885, R²: -0.0342
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.12959 | val 0.14040
  Epoch 020 - train 0.12769 | val 0.15058
  Regression -> MSE: 0.000683, MAE: 0.019307, R²: 0.0023
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.13429 | val 0.21449
  Epoch 020 - train 0.13832 | val 0.21123
  Regression -> MSE: 0.000352, MAE: 0.015119, R²: -0.1333
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.11283 | val 0.24204
  Epoch 020 - train 0.11031 | val 0.26379
  Regression -> MSE: 0.000363, MAE: 0.014793, R²: -0.0390
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.13486 | val 0.13849
  Epoch 020 - train 0.13411 | val 0.16013
  Regression -> MSE: 0.000208, MAE: 0.010144, R²: -0.0212
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.12541 | val 0.24954
  Epoch 020 - train 0.13016 | val 0.24745
  Regression -> MSE: 0.000578, MAE: 0.018568, R²: -0.0414
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.13442 | val 0.16736
  Epoch 020 - train 0.13897 | val 0.16736
  Regression -> MSE: 0.000245, MAE: 0.012077, R²: -0.0001
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.13430 | val 0.19804
  Epoch 020 - train 0.13553 | val 0.19920
  Regression -> MSE: 0.000662, MAE: 0.020433, R²: -0.1085
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.12739 | val 0.15844
  Epoch 020 - train 0.12765 | val 0.15644
  Regression -> MSE: 0.000397, MAE: 0.016009, R²: -0.0358
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.13962 | val 0.17491
  Epoch 020 - train 0.13643 | val 0.17614
  Regression -> MSE: 0.000243, MAE: 0.011695, R²: -0.0059
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.13314 | val 0.25528
  Epoch 020 - train 0.13658 | val 0.31145
  Regression -> MSE: 0.000314, MAE: 0.013955, R²: -0.0099
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.6301

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.13552 | val 0.15476
  Epoch 020 - train 0.13587 | val 0.15444
  Regression -> MSE: 0.000678, MAE: 0.019528, R²: -0.0010
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.13603 | val 0.14421
  Epoch 020 - train 0.13604 | val 0.20127
  Regression -> MSE: 0.000141, MAE: 0.009322, R²: -0.0198
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.13412 | val 0.21114
  Epoch 020 - train 0.13101 | val 0.21613
  Regression -> MSE: 0.000229, MAE: 0.011022, R²: -0.0187
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.13524 | val 0.27674
  Epoch 020 - train 0.13248 | val 0.29346
  Regression -> MSE: 0.000362, MAE: 0.016049, R²: -0.0002
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.13512 | val 0.13768
  Epoch 020 - train 0.13666 | val 0.13827
  Regression -> MSE: 0.000108, MAE: 0.007996, R²: -0.0016
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.13491 | val 0.21938
  Epoch 020 - train 0.13236 | val 0.21764
  Regression -> MSE: 0.000156, MAE: 0.009537, R²: -0.0026
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.13412 | val 0.15071
  Epoch 020 - train 0.13413 | val 0.15533
  Regression -> MSE: 0.000279, MAE: 0.013390, R²: -0.0252
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.12430 | val 0.17781
  Epoch 020 - train 0.12778 | val 0.17763
  Regression -> MSE: 0.000154, MAE: 0.008758, R²: -0.0298
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.15014 | val 0.20872
  Epoch 020 - train 0.14658 | val 0.20898
  Regression -> MSE: 0.000252, MAE: 0.011335, R²: -0.1117
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.13451 | val 0.16914
  Epoch 020 - train 0.13627 | val 0.17416
  Regression -> MSE: 0.000152, MAE: 0.008764, R²: -0.0584
  Directional -> Accuracy: 0.3333, MCC: -0.2335, F1: 0.0588

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.12739 | val 0.16704
  Epoch 020 - train 0.12663 | val 0.16905
  Regression -> MSE: 0.000165, MAE: 0.010540, R²: -0.0016
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.13710 | val 0.15339
  Epoch 020 - train 0.13627 | val 0.15312
  Regression -> MSE: 0.000086, MAE: 0.007108, R²: -0.0128
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.14425 | val 0.16554
  Epoch 020 - train 0.14314 | val 0.16750
  Regression -> MSE: 0.000214, MAE: 0.011051, R²: -0.0114
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.12742 | val 0.12435
  Epoch 020 - train 0.12663 | val 0.12519
  Regression -> MSE: 0.000097, MAE: 0.008144, R²: -0.0506
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.14092 | val 0.10532
  Epoch 020 - train 0.15143 | val 0.11864
  Regression -> MSE: 0.000103, MAE: 0.008725, R²: -0.0009
  Directional -> Accuracy: 0.4783, MCC: -0.0742, F1: 0.3684

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.13752 | val 0.12794
  Epoch 020 - train 0.13957 | val 0.13563
  Regression -> MSE: 0.000232, MAE: 0.012570, R²: -0.0033
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.13324 | val 0.16297
  Epoch 020 - train 0.13188 | val 0.16193
  Regression -> MSE: 0.000170, MAE: 0.007806, R²: -0.0231
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.13686 | val 0.11458
  Epoch 020 - train 0.13051 | val 0.11547
  Regression -> MSE: 0.000237, MAE: 0.011869, R²: -0.0015
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.13236 | val 0.21326
  Epoch 020 - train 0.13397 | val 0.21579
  Regression -> MSE: 0.000231, MAE: 0.009941, R²: -0.0033
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.14644 | val 0.15253
  Epoch 020 - train 0.14731 | val 0.17820
  Regression -> MSE: 0.000136, MAE: 0.008169, R²: -0.0077
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.13957 | val 0.17573
  Epoch 020 - train 0.14218 | val 0.17644
  Regression -> MSE: 0.000188, MAE: 0.010533, R²: -0.0002
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.12427 | val 0.16029
  Epoch 020 - train 0.12531 | val 0.15988
  Regression -> MSE: 0.000262, MAE: 0.010531, R²: 0.0007
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.13312 | val 0.11668
  Epoch 020 - train 0.13218 | val 0.11592
  Regression -> MSE: 0.000167, MAE: 0.010365, R²: -0.0019
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.15084 | val 0.16911
  Epoch 020 - train 0.14745 | val 0.21511
  Regression -> MSE: 0.000193, MAE: 0.010811, R²: -0.0704
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.13066 | val 0.12603
  Epoch 020 - train 0.13531 | val 0.12642
  Regression -> MSE: 0.000346, MAE: 0.011712, R²: -0.0097
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.14587 | val 0.09184
  Epoch 020 - train 0.14353 | val 0.09510
  Regression -> MSE: 0.000110, MAE: 0.008324, R²: -0.0443
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.13885 | val 0.18969
  Epoch 020 - train 0.13007 | val 0.19535
  Regression -> MSE: 0.000219, MAE: 0.011281, R²: -0.0001
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.13229 | val 0.23216
  Epoch 020 - train 0.13236 | val 0.24292
  Regression -> MSE: 0.000087, MAE: 0.007276, R²: -0.1150
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.13038 | val 0.11152
  Epoch 020 - train 0.13111 | val 0.12557
  Regression -> MSE: 0.000328, MAE: 0.014908, R²: -0.0658
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.15281 | val 0.08189
  Epoch 020 - train 0.15419 | val 0.08743
  Regression -> MSE: 0.000247, MAE: 0.011523, R²: -0.0146
  Directional -> Accuracy: 0.5000, MCC: 0.0429, F1: 0.2963

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.14337 | val 0.17682
  Epoch 020 - train 0.13882 | val 0.17916
  Regression -> MSE: 0.000084, MAE: 0.007045, R²: -0.0373
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.15064 | val 0.17337
  Epoch 020 - train 0.14895 | val 0.16010
  Regression -> MSE: 0.000316, MAE: 0.014830, R²: -0.0302
  Directional -> Accuracy: 0.3830, MCC: -0.2344, F1: 0.3256

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.12524 | val 0.15712
  Epoch 020 - train 0.12978 | val 0.15283
  Regression -> MSE: 0.000100, MAE: 0.007050, R²: -0.0150
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.15002 | val 0.15957
  Epoch 020 - train 0.14582 | val 0.15479
  Regression -> MSE: 0.000176, MAE: 0.010200, R²: -0.0219
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.12783 | val 0.16613
  Epoch 020 - train 0.12863 | val 0.17127
  Regression -> MSE: 0.000224, MAE: 0.011725, R²: -0.0062
  Directional -> Accuracy: 0.6429, MCC: 0.3341, F1: 0.5833

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.13238 | val 0.14561
  Epoch 020 - train 0.13242 | val 0.14328
  Regression -> MSE: 0.000105, MAE: 0.008337, R²: -0.1408
  Directional -> Accuracy: 0.4737, MCC: -0.0418, F1: 0.5161

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.14612 | val 0.20976
  Epoch 020 - train 0.14132 | val 0.21228
  Regression -> MSE: 0.000164, MAE: 0.010252, R²: -0.0010
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.13870 | val 0.16463
  Epoch 020 - train 0.14042 | val 0.16367
  Regression -> MSE: 0.000123, MAE: 0.009005, R²: -0.0581
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.13862 | val 0.18721

[I 2026-02-23 01:12:41,673] Trial 168 finished with value: -0.011493738842422526 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 32, 'learning_rate': 2.49218058597437e-06, 'weight_decay': 3.33798157135082e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.20282000783887538, 'early_stopping_min_delta': 0.005920149083696899}. Best is trial 157 with value: -0.011387287234516647.

  Epoch 020 - train 0.13567 | val 0.18735
  Regression -> MSE: 0.000245, MAE: 0.012369, R²: -0.0349
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.11228 | val 0.14648
  Epoch 020 - train 0.11050 | val 0.14775
  Regression -> MSE: 0.000257, MAE: 0.012950, R²: -0.0383
  Directional -> Accuracy: 0.4156, MCC: -0.1550, F1: 0.5631

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.11894 | val 0.10405
  Epoch 020 - train 0.11533 | val 0.10819
  Regression -> MSE: 0.000699, MAE: 0.019613, R²: -0.0216
  Directional -> Accuracy: 0.4783, MCC: -0.1433, F1: 0.6129

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.11389 | val 0.18282
  Epoch 020 - train 0.11356 | val 0.18498
  Regression -> MSE: 0.000327, MAE: 0.014583, R²: -0.0535
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.09284 | val 0.09845
  Epoch 020 - train 0.09091 | val 0.09925
  Regression -> MSE: 0.000352, MAE: 0.014643, R²: -0.0088
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.11759 | val 0.11792
  Epoch 020 - train 0.11695 | val 0.12936
  Regression -> MSE: 0.000208, MAE: 0.010136, R²: -0.0196
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.10493 | val 0.20673
  Epoch 020 - train 0.10416 | val 0.21258
  Regression -> MSE: 0.000569, MAE: 0.018347, R²: -0.0258
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.11326 | val 0.14201
  Epoch 020 - train 0.11401 | val 0.14011
  Regression -> MSE: 0.000246, MAE: 0.012146, R²: -0.0019
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.11299 | val 0.14301
  Epoch 020 - train 0.10857 | val 0.14442
  Regression -> MSE: 0.000622, MAE: 0.019759, R²: -0.0417
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.10627 | val 0.12972
  Epoch 020 - train 0.11055 | val 0.13096
  Regression -> MSE: 0.000409, MAE: 0.016232, R²: -0.0674
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.11293 | val 0.14440
  Epoch 020 - train 0.11233 | val 0.14343
  Regression -> MSE: 0.000242, MAE: 0.011781, R²: -0.0031
  Directional -> Accuracy: 0.4286, MCC: -0.0248, F1: 0.5918

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.10218 | val 0.15790
  Epoch 020 - train 0.10097 | val 0.16254
  Regression -> MSE: 0.000316, MAE: 0.013587, R²: -0.0153
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.12175 | val 0.13672
  Epoch 020 - train 0.12105 | val 0.14520
  Regression -> MSE: 0.000681, MAE: 0.019534, R²: -0.0059
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.10844 | val 0.11056
  Epoch 020 - train 0.10468 | val 0.11679
  Regression -> MSE: 0.000141, MAE: 0.009332, R²: -0.0203
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.10406 | val 0.15240
  Epoch 020 - train 0.10378 | val 0.15427
  Regression -> MSE: 0.000226, MAE: 0.010790, R²: -0.0039
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.10767 | val 0.21562
  Epoch 020 - train 0.10817 | val 0.23324
  Regression -> MSE: 0.000369, MAE: 0.015921, R²: -0.0200
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.12177 | val 0.12644
  Epoch 020 - train 0.11786 | val 0.12808
  Regression -> MSE: 0.000109, MAE: 0.007930, R²: -0.0089
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.10744 | val 0.19996
  Epoch 020 - train 0.10481 | val 0.21757
  Regression -> MSE: 0.000156, MAE: 0.009556, R²: -0.0010
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.11913 | val 0.11553
  Epoch 020 - train 0.11488 | val 0.11555
  Regression -> MSE: 0.000275, MAE: 0.012877, R²: -0.0103
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.10338 | val 0.15221
  Epoch 020 - train 0.10325 | val 0.15232
  Regression -> MSE: 0.000151, MAE: 0.008763, R²: -0.0068
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.11658 | val 0.19378
  Epoch 020 - train 0.11663 | val 0.18851
  Regression -> MSE: 0.000227, MAE: 0.010967, R²: -0.0031
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.11440 | val 0.13636
  Epoch 020 - train 0.11013 | val 0.13705
  Regression -> MSE: 0.000150, MAE: 0.008675, R²: -0.0458
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.10966 | val 0.13335
  Epoch 020 - train 0.10835 | val 0.13339
  Regression -> MSE: 0.000169, MAE: 0.010278, R²: -0.0199
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.11346 | val 0.13426
  Epoch 020 - train 0.11329 | val 0.13518
  Regression -> MSE: 0.000085, MAE: 0.007046, R²: -0.0004
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.11102 | val 0.16996
  Epoch 020 - train 0.11208 | val 0.16179
  Regression -> MSE: 0.000214, MAE: 0.011362, R²: -0.0098
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.10027 | val 0.09726
  Epoch 020 - train 0.09830 | val 0.09528
  Regression -> MSE: 0.000098, MAE: 0.008171, R²: -0.0672
  Directional -> Accuracy: 0.4643, MCC: 0.1211, F1: 0.0625

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.11175 | val 0.09164
  Epoch 020 - train 0.10819 | val 0.09399
  Regression -> MSE: 0.000110, MAE: 0.009029, R²: -0.0651
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.11701 | val 0.10612
  Epoch 020 - train 0.11899 | val 0.10934
  Regression -> MSE: 0.000234, MAE: 0.012627, R²: -0.0100
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.11122 | val 0.12989
  Epoch 020 - train 0.11010 | val 0.12986
  Regression -> MSE: 0.000184, MAE: 0.008039, R²: -0.1050
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.11850 | val 0.09446
  Epoch 020 - train 0.11647 | val 0.10132
  Regression -> MSE: 0.000238, MAE: 0.011902, R²: -0.0055
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.11436 | val 0.17707
  Epoch 020 - train 0.11460 | val 0.18455
  Regression -> MSE: 0.000232, MAE: 0.009929, R²: -0.0052
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.11031 | val 0.13452
  Epoch 020 - train 0.11211 | val 0.13793
  Regression -> MSE: 0.000136, MAE: 0.008241, R²: -0.0068
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.11871 | val 0.14689
  Epoch 020 - train 0.11447 | val 0.15183
  Regression -> MSE: 0.000188, MAE: 0.010454, R²: -0.0004
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.10156 | val 0.13205
  Epoch 020 - train 0.09858 | val 0.13007
  Regression -> MSE: 0.000262, MAE: 0.010563, R²: -0.0023
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.10696 | val 0.09475
  Epoch 020 - train 0.10078 | val 0.09747
  Regression -> MSE: 0.000167, MAE: 0.010369, R²: -0.0002
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.11351 | val 0.12264
  Epoch 020 - train 0.10940 | val 0.12836
  Regression -> MSE: 0.000191, MAE: 0.010715, R²: -0.0621
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.10977 | val 0.11039
  Epoch 020 - train 0.10799 | val 0.10948
  Regression -> MSE: 0.000348, MAE: 0.012240, R²: -0.0160
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.12331 | val 0.07652
  Epoch 020 - train 0.11887 | val 0.10196
  Regression -> MSE: 0.000114, MAE: 0.008323, R²: -0.0872
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.11556 | val 0.15874
  Epoch 020 - train 0.11690 | val 0.15738
  Regression -> MSE: 0.000224, MAE: 0.011450, R²: -0.0237
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.11358 | val 0.18641
  Epoch 020 - train 0.11011 | val 0.19243
  Regression -> MSE: 0.000087, MAE: 0.007277, R²: -0.1149
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.10535 | val 0.08536
  Epoch 020 - train 0.10844 | val 0.09575
  Regression -> MSE: 0.000310, MAE: 0.013933, R²: -0.0074
  Directional -> Accuracy: 0.6327, MCC: 0.0000, F1: 0.0000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.12455 | val 0.07703
  Epoch 020 - train 0.12159 | val 0.07973
  Regression -> MSE: 0.000264, MAE: 0.011534, R²: -0.0846
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.11374 | val 0.13348
  Epoch 020 - train 0.10993 | val 0.13223
  Regression -> MSE: 0.000081, MAE: 0.007087, R²: -0.0002
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.10977 | val 0.13514
  Epoch 020 - train 0.11043 | val 0.13317
  Regression -> MSE: 0.000310, MAE: 0.014438, R²: -0.0089
  Directional -> Accuracy: 0.5106, MCC: 0.0183, F1: 0.5490

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.10825 | val 0.12290
  Epoch 020 - train 0.10593 | val 0.12245
  Regression -> MSE: 0.000099, MAE: 0.007194, R²: -0.0054
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.11943 | val 0.13176
  Epoch 020 - train 0.11967 | val 0.14034
  Regression -> MSE: 0.000172, MAE: 0.009757, R²: -0.0010
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.10803 | val 0.13043
  Epoch 020 - train 0.10264 | val 0.13501
  Regression -> MSE: 0.000225, MAE: 0.011794, R²: -0.0072
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.11365 | val 0.12744
  Epoch 020 - train 0.10983 | val 0.12935
  Regression -> MSE: 0.000092, MAE: 0.007640, R²: 0.0025
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.11973 | val 0.17388
  Epoch 020 - train 0.11781 | val 0.17775
  Regression -> MSE: 0.000164, MAE: 0.010283, R²: -0.0036
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.11000 | val 0.13619
  Epoch 020 - train 0.11238 | val 0.13886
  Regression -> MSE: 0.000117, MAE: 0.008952, R²: -0.0114
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.11525 | val 0.15436

[I 2026-02-23 01:15:15,453] Trial 169 finished with value: -0.01142300866963991 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 32, 'learning_rate': 3.2453291685415247e-06, 'weight_decay': 7.795050668850418e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.1637659537279887, 'early_stopping_min_delta': 0.0056447179902184026}. Best is trial 157 with value: -0.011387287234516647.

  Epoch 020 - train 0.11626 | val 0.15903
  Regression -> MSE: 0.000237, MAE: 0.012402, R²: 0.0022
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.10069 | val 0.13365
  Epoch 020 - train 0.10084 | val 0.13233
  Regression -> MSE: 0.000250, MAE: 0.012658, R²: -0.0112
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.10371 | val 0.09314
  Epoch 020 - train 0.09994 | val 0.09214
  Regression -> MSE: 0.000704, MAE: 0.019661, R²: -0.0281
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.10267 | val 0.16112
  Epoch 020 - train 0.10314 | val 0.16347
  Regression -> MSE: 0.000310, MAE: 0.014385, R²: -0.0008
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.08341 | val 0.10163
  Epoch 020 - train 0.08311 | val 0.09704
  Regression -> MSE: 0.000352, MAE: 0.014621, R²: -0.0063
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.11105 | val 0.11031
  Epoch 020 - train 0.10987 | val 0.12099
  Regression -> MSE: 0.000208, MAE: 0.010170, R²: -0.0224
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.09718 | val 0.19219
  Epoch 020 - train 0.09294 | val 0.21850
  Regression -> MSE: 0.000585, MAE: 0.018673, R²: -0.0539
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.09960 | val 0.12549
  Epoch 020 - train 0.09925 | val 0.12771
  Regression -> MSE: 0.000245, MAE: 0.011968, R²: 0.0004
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.09688 | val 0.14183
  Epoch 020 - train 0.09787 | val 0.16169
  Regression -> MSE: 0.000641, MAE: 0.020097, R²: -0.0728
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.09880 | val 0.11755
  Epoch 020 - train 0.09469 | val 0.11940
  Regression -> MSE: 0.000405, MAE: 0.016151, R²: -0.0566
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.10918 | val 0.13209
  Epoch 020 - train 0.10873 | val 0.13501
  Regression -> MSE: 0.000244, MAE: 0.011669, R²: -0.0107
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.09327 | val 0.14844
  Epoch 020 - train 0.09065 | val 0.15720
  Regression -> MSE: 0.000311, MAE: 0.013632, R²: 0.0003
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.10699 | val 0.12391
  Epoch 020 - train 0.10521 | val 0.12746
  Regression -> MSE: 0.000681, MAE: 0.019529, R²: -0.0051
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.10478 | val 0.09876
  Epoch 020 - train 0.10102 | val 0.11265
  Regression -> MSE: 0.000147, MAE: 0.009597, R²: -0.0652
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.09182 | val 0.12869
  Epoch 020 - train 0.08909 | val 0.12787
  Regression -> MSE: 0.000228, MAE: 0.010768, R²: -0.0139
  Directional -> Accuracy: 0.4918, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.10412 | val 0.19923
  Epoch 020 - train 0.10208 | val 0.20133
  Regression -> MSE: 0.000364, MAE: 0.016268, R²: -0.0051
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.10389 | val 0.10200
  Epoch 020 - train 0.10512 | val 0.10030
  Regression -> MSE: 0.000108, MAE: 0.007954, R²: -0.0049
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.09834 | val 0.16134
  Epoch 020 - train 0.09797 | val 0.16441
  Regression -> MSE: 0.000156, MAE: 0.009559, R²: -0.0015
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.11038 | val 0.10572
  Epoch 020 - train 0.10653 | val 0.10441
  Regression -> MSE: 0.000274, MAE: 0.012948, R²: -0.0074
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.09004 | val 0.13531
  Epoch 020 - train 0.08812 | val 0.13506
  Regression -> MSE: 0.000153, MAE: 0.008739, R²: -0.0215
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.10396 | val 0.13987
  Epoch 020 - train 0.10260 | val 0.14275
  Regression -> MSE: 0.000229, MAE: 0.010914, R²: -0.0125
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.09937 | val 0.12331
  Epoch 020 - train 0.10025 | val 0.13126
  Regression -> MSE: 0.000152, MAE: 0.008798, R²: -0.0622
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.09380 | val 0.11693
  Epoch 020 - train 0.09771 | val 0.11709
  Regression -> MSE: 0.000167, MAE: 0.010269, R²: -0.0137
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.11007 | val 0.12125
  Epoch 020 - train 0.10432 | val 0.12074
  Regression -> MSE: 0.000089, MAE: 0.007282, R²: -0.0501
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.10400 | val 0.16524
  Epoch 020 - train 0.10346 | val 0.16390
  Regression -> MSE: 0.000212, MAE: 0.011189, R²: -0.0026
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.09328 | val 0.09245
  Epoch 020 - train 0.08867 | val 0.09136
  Regression -> MSE: 0.000093, MAE: 0.008082, R²: -0.0050
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.10083 | val 0.08461
  Epoch 020 - train 0.09876 | val 0.07936
  Regression -> MSE: 0.000104, MAE: 0.008667, R²: -0.0082
  Directional -> Accuracy: 0.4565, MCC: 0.0541, F1: 0.6032

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.10481 | val 0.09619
  Epoch 020 - train 0.10083 | val 0.10709
  Regression -> MSE: 0.000234, MAE: 0.012643, R²: -0.0102
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.10076 | val 0.11797
  Epoch 020 - train 0.09745 | val 0.11925
  Regression -> MSE: 0.000181, MAE: 0.007984, R²: -0.0888
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.10274 | val 0.08515
  Epoch 020 - train 0.10425 | val 0.08511
  Regression -> MSE: 0.000238, MAE: 0.011911, R²: -0.0059
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.09488 | val 0.16092
  Epoch 020 - train 0.09840 | val 0.17486
  Regression -> MSE: 0.000232, MAE: 0.009988, R²: -0.0063
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.10704 | val 0.12641
  Epoch 020 - train 0.10829 | val 0.12161
  Regression -> MSE: 0.000145, MAE: 0.008394, R²: -0.0754
  Directional -> Accuracy: 0.5814, MCC: 0.1627, F1: 0.7000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.10043 | val 0.12457
  Epoch 020 - train 0.09860 | val 0.12544
  Regression -> MSE: 0.000190, MAE: 0.010378, R²: -0.0095
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.09119 | val 0.11662
  Epoch 020 - train 0.09014 | val 0.11742
  Regression -> MSE: 0.000271, MAE: 0.010655, R²: -0.0344
  Directional -> Accuracy: 0.4384, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.09867 | val 0.08875
  Epoch 020 - train 0.09236 | val 0.08438
  Regression -> MSE: 0.000162, MAE: 0.010310, R²: 0.0261
  Directional -> Accuracy: 0.4474, MCC: -0.2357, F1: 0.6182

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.09389 | val 0.10163
  Epoch 020 - train 0.09284 | val 0.10580
  Regression -> MSE: 0.000180, MAE: 0.010293, R²: 0.0004
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.09810 | val 0.09351
  Epoch 020 - train 0.09676 | val 0.09278
  Regression -> MSE: 0.000342, MAE: 0.011883, R²: 0.0005
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.11010 | val 0.06546
  Epoch 020 - train 0.10929 | val 0.06507
  Regression -> MSE: 0.000118, MAE: 0.008344, R²: -0.1259
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.09968 | val 0.13712
  Epoch 020 - train 0.09979 | val 0.14189
  Regression -> MSE: 0.000219, MAE: 0.011302, R²: -0.0013
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.09972 | val 0.16864
  Epoch 020 - train 0.10240 | val 0.17123
  Regression -> MSE: 0.000086, MAE: 0.007264, R²: -0.1109
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.10101 | val 0.07376
  Epoch 020 - train 0.10025 | val 0.07051
  Regression -> MSE: 0.000309, MAE: 0.013871, R²: -0.0039
  Directional -> Accuracy: 0.6327, MCC: 0.0000, F1: 0.0000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.11084 | val 0.06747
  Epoch 020 - train 0.10814 | val 0.06929
  Regression -> MSE: 0.000262, MAE: 0.011509, R²: -0.0740
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.10160 | val 0.12312
  Epoch 020 - train 0.10096 | val 0.12351
  Regression -> MSE: 0.000086, MAE: 0.007076, R²: -0.0639
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.10480 | val 0.13654
  Epoch 020 - train 0.10713 | val 0.16803
  Regression -> MSE: 0.000314, MAE: 0.014506, R²: -0.0220
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.09554 | val 0.10951
  Epoch 020 - train 0.09481 | val 0.10809
  Regression -> MSE: 0.000099, MAE: 0.007190, R²: -0.0056
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.10995 | val 0.12013
  Epoch 020 - train 0.10692 | val 0.13715
  Regression -> MSE: 0.000172, MAE: 0.009634, R²: 0.0008
  Directional -> Accuracy: 0.3673, MCC: -0.1814, F1: 0.5373

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.09925 | val 0.13101
  Epoch 020 - train 0.09354 | val 0.14401
  Regression -> MSE: 0.000224, MAE: 0.011795, R²: -0.0043
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.09884 | val 0.11013
  Epoch 020 - train 0.09827 | val 0.11073
  Regression -> MSE: 0.000093, MAE: 0.007690, R²: -0.0089
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.10663 | val 0.14982
  Epoch 020 - train 0.10925 | val 0.14936
  Regression -> MSE: 0.000164, MAE: 0.010267, R²: -0.0022
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.10228 | val 0.13092
  Epoch 020 - train 0.10012 | val 0.13785
  Regression -> MSE: 0.000116, MAE: 0.008949, R²: -0.0039
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.10048 | val 0.14458

[I 2026-02-23 01:17:48,327] Trial 170 finished with value: -0.0114088590847577 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 32, 'learning_rate': 3.2833689341866525e-06, 'weight_decay': 4.06770157202193e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.14566384860129378, 'early_stopping_min_delta': 0.005581832768246703}. Best is trial 157 with value: -0.011387287234516647.

  Epoch 020 - train 0.09910 | val 0.14848
  Regression -> MSE: 0.000238, MAE: 0.012356, R²: -0.0044
  Directional -> Accuracy: 0.4754, MCC: -0.0633, F1: 0.3846

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.10980 | val 0.14052
  Epoch 020 - train 0.10973 | val 0.14026
  Regression -> MSE: 0.000257, MAE: 0.012796, R²: -0.0386
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.10444 | val 0.10866
  Epoch 020 - train 0.10318 | val 0.12229
  Regression -> MSE: 0.000691, MAE: 0.019454, R²: -0.0090
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.10407 | val 0.16710
  Epoch 020 - train 0.10752 | val 0.16611
  Regression -> MSE: 0.000312, MAE: 0.014404, R²: -0.0044
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.09523 | val 0.11832
  Epoch 020 - train 0.09006 | val 0.11741
  Regression -> MSE: 0.000359, MAE: 0.014753, R²: -0.0283
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.10628 | val 0.11201
  Epoch 020 - train 0.10812 | val 0.11421
  Regression -> MSE: 0.000205, MAE: 0.010321, R²: -0.0083
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.09938 | val 0.19630
  Epoch 020 - train 0.09970 | val 0.20030
  Regression -> MSE: 0.000576, MAE: 0.018503, R²: -0.0376
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.10810 | val 0.13445
  Epoch 020 - train 0.10490 | val 0.13564
  Regression -> MSE: 0.000246, MAE: 0.012010, R²: -0.0010
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.10301 | val 0.13632
  Epoch 020 - train 0.10238 | val 0.13833
  Regression -> MSE: 0.000629, MAE: 0.019872, R²: -0.0521
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.10344 | val 0.12824
  Epoch 020 - train 0.10007 | val 0.12264
  Regression -> MSE: 0.000449, MAE: 0.016821, R²: -0.1704
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.09967 | val 0.14110
  Epoch 020 - train 0.10048 | val 0.14937
  Regression -> MSE: 0.000244, MAE: 0.012215, R²: -0.0089
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.09986 | val 0.16108
  Epoch 020 - train 0.10037 | val 0.17324
  Regression -> MSE: 0.000311, MAE: 0.013642, R²: -0.0013
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.10758 | val 0.14146
  Epoch 020 - train 0.10740 | val 0.15844
  Regression -> MSE: 0.000682, MAE: 0.019553, R²: -0.0073
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.10640 | val 0.10599
  Epoch 020 - train 0.10770 | val 0.10981
  Regression -> MSE: 0.000139, MAE: 0.009187, R²: -0.0056
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.09713 | val 0.13704
  Epoch 020 - train 0.09679 | val 0.13380
  Regression -> MSE: 0.000215, MAE: 0.010519, R²: 0.0442
  Directional -> Accuracy: 0.5738, MCC: 0.1467, F1: 0.5938

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.10341 | val 0.21276
  Epoch 020 - train 0.10283 | val 0.21672
  Regression -> MSE: 0.000369, MAE: 0.015923, R²: -0.0199
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.11558 | val 0.12194
  Epoch 020 - train 0.11528 | val 0.11922
  Regression -> MSE: 0.000111, MAE: 0.007966, R²: -0.0327
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.10117 | val 0.18384
  Epoch 020 - train 0.10292 | val 0.19758
  Regression -> MSE: 0.000160, MAE: 0.010076, R²: -0.0250
  Directional -> Accuracy: 0.6102, MCC: 0.0423, F1: 0.7416

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.10652 | val 0.10536
  Epoch 020 - train 0.10503 | val 0.10474
  Regression -> MSE: 0.000274, MAE: 0.013143, R²: -0.0061
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.09679 | val 0.13743
  Epoch 020 - train 0.09565 | val 0.13623
  Regression -> MSE: 0.000156, MAE: 0.008785, R²: -0.0407
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.10955 | val 0.14794
  Epoch 020 - train 0.10937 | val 0.14918
  Regression -> MSE: 0.000229, MAE: 0.010847, R²: -0.0135
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.10809 | val 0.12948
  Epoch 020 - train 0.10171 | val 0.13079
  Regression -> MSE: 0.000146, MAE: 0.008507, R²: -0.0181
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.10317 | val 0.12755
  Epoch 020 - train 0.10198 | val 0.12774
  Regression -> MSE: 0.000178, MAE: 0.010303, R²: -0.0771
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.11459 | val 0.13164
  Epoch 020 - train 0.11279 | val 0.13224
  Regression -> MSE: 0.000095, MAE: 0.007528, R²: -0.1172
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.10758 | val 0.14590
  Epoch 020 - train 0.10282 | val 0.14116
  Regression -> MSE: 0.000216, MAE: 0.011051, R²: -0.0182
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.10417 | val 0.10142
  Epoch 020 - train 0.10922 | val 0.10443
  Regression -> MSE: 0.000093, MAE: 0.008101, R²: -0.0063
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.11007 | val 0.09377
  Epoch 020 - train 0.10830 | val 0.10305
  Regression -> MSE: 0.000121, MAE: 0.009368, R²: -0.1712
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.11211 | val 0.10961
  Epoch 020 - train 0.11274 | val 0.12128
  Regression -> MSE: 0.000246, MAE: 0.012989, R²: -0.0622
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.10323 | val 0.13039
  Epoch 020 - train 0.10299 | val 0.13374
  Regression -> MSE: 0.000175, MAE: 0.007872, R²: -0.0518
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.10338 | val 0.08957
  Epoch 020 - train 0.10279 | val 0.09036
  Regression -> MSE: 0.000237, MAE: 0.011866, R²: -0.0013
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.10440 | val 0.16359
  Epoch 020 - train 0.10135 | val 0.16152
  Regression -> MSE: 0.000231, MAE: 0.009934, R²: -0.0038
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.11058 | val 0.12969
  Epoch 020 - train 0.11205 | val 0.14110
  Regression -> MSE: 0.000137, MAE: 0.008261, R²: -0.0139
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.11400 | val 0.13806
  Epoch 020 - train 0.11139 | val 0.13854
  Regression -> MSE: 0.000189, MAE: 0.010560, R²: -0.0015
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.09549 | val 0.12369
  Epoch 020 - train 0.09306 | val 0.12337
  Regression -> MSE: 0.000283, MAE: 0.011039, R²: -0.0798
  Directional -> Accuracy: 0.4384, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.10950 | val 0.08855
  Epoch 020 - train 0.11159 | val 0.09721
  Regression -> MSE: 0.000168, MAE: 0.010371, R²: -0.0102
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.09904 | val 0.11171
  Epoch 020 - train 0.09779 | val 0.11189
  Regression -> MSE: 0.000188, MAE: 0.010649, R²: -0.0469
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.10158 | val 0.09937
  Epoch 020 - train 0.09971 | val 0.09912
  Regression -> MSE: 0.000343, MAE: 0.011928, R²: -0.0020
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.11197 | val 0.06934
  Epoch 020 - train 0.11065 | val 0.07145
  Regression -> MSE: 0.000117, MAE: 0.008348, R²: -0.1094
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.10708 | val 0.14251
  Epoch 020 - train 0.10622 | val 0.14252
  Regression -> MSE: 0.000224, MAE: 0.011439, R²: -0.0259
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.10519 | val 0.18407
  Epoch 020 - train 0.10491 | val 0.19523
  Regression -> MSE: 0.000081, MAE: 0.006985, R²: -0.0367
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.10466 | val 0.09158
  Epoch 020 - train 0.10205 | val 0.08515
  Regression -> MSE: 0.000355, MAE: 0.015802, R²: -0.1530
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.10878 | val 0.06972
  Epoch 020 - train 0.11113 | val 0.06587
  Regression -> MSE: 0.000269, MAE: 0.011493, R²: -0.1016
  Directional -> Accuracy: 0.5526, MCC: 0.1733, F1: 0.7018

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.10465 | val 0.13803
  Epoch 020 - train 0.10678 | val 0.13552
  Regression -> MSE: 0.000081, MAE: 0.007082, R²: -0.0006
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.10812 | val 0.12748
  Epoch 020 - train 0.10589 | val 0.12447
  Regression -> MSE: 0.000313, MAE: 0.014533, R²: -0.0209
  Directional -> Accuracy: 0.4468, MCC: -0.1044, F1: 0.4091

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.10449 | val 0.11467
  Epoch 020 - train 0.10280 | val 0.11359
  Regression -> MSE: 0.000099, MAE: 0.007191, R²: -0.0083
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.11572 | val 0.12576
  Epoch 020 - train 0.12054 | val 0.13625
  Regression -> MSE: 0.000174, MAE: 0.010065, R²: -0.0128
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.10719 | val 0.12689
  Epoch 020 - train 0.10734 | val 0.12817
  Regression -> MSE: 0.000228, MAE: 0.011829, R²: -0.0237
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.10405 | val 0.11288
  Epoch 020 - train 0.09915 | val 0.11154
  Regression -> MSE: 0.000092, MAE: 0.007567, R²: 0.0026
  Directional -> Accuracy: 0.5088, MCC: 0.0075, F1: 0.4400

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.11172 | val 0.16094
  Epoch 020 - train 0.10870 | val 0.16451
  Regression -> MSE: 0.000164, MAE: 0.010249, R²: 0.0001
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.10321 | val 0.13322
  Epoch 020 - train 0.10419 | val 0.13658
  Regression -> MSE: 0.000131, MAE: 0.009126, R²: -0.1314
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.10537 | val 0.14388

[I 2026-02-23 01:20:22,937] Trial 171 finished with value: -0.011503414730241097 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 32, 'learning_rate': 3.779401053062412e-06, 'weight_decay': 4.454519388138714e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.153896054373343, 'early_stopping_min_delta': 0.005562972095784373}. Best is trial 157 with value: -0.011387287234516647.

  Epoch 020 - train 0.10501 | val 0.14924
  Regression -> MSE: 0.000243, MAE: 0.012345, R²: -0.0264
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.12326 | val 0.18603
  Epoch 020 - train 0.12259 | val 0.18955
  Regression -> MSE: 0.000266, MAE: 0.013157, R²: -0.0749
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.11886 | val 0.11409
  Epoch 020 - train 0.11572 | val 0.15243
  Regression -> MSE: 0.000696, MAE: 0.019523, R²: -0.0162
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.11943 | val 0.19037
  Epoch 020 - train 0.11984 | val 0.18596
  Regression -> MSE: 0.000306, MAE: 0.014132, R²: 0.0147
  Directional -> Accuracy: 0.5319, MCC: 0.0290, F1: 0.6562

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.10685 | val 0.33837
  Epoch 020 - train 0.10644 | val 0.35170
  Regression -> MSE: 0.000420, MAE: 0.015987, R²: -0.2018
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.12446 | val 0.11935
  Epoch 020 - train 0.12615 | val 0.11843
  Regression -> MSE: 0.000208, MAE: 0.010129, R²: -0.0202
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.11610 | val 0.22900
  Epoch 020 - train 0.11522 | val 0.24684
  Regression -> MSE: 0.000597, MAE: 0.018907, R²: -0.0753
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.12417 | val 0.14669
  Epoch 020 - train 0.12505 | val 0.14636
  Regression -> MSE: 0.000247, MAE: 0.011954, R²: -0.0047
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.11681 | val 0.16332
  Epoch 020 - train 0.12032 | val 0.16437
  Regression -> MSE: 0.000644, MAE: 0.020154, R²: -0.0783
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.11127 | val 0.14218
  Epoch 020 - train 0.11544 | val 0.14322
  Regression -> MSE: 0.000395, MAE: 0.015975, R²: -0.0307
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.12230 | val 0.15425
  Epoch 020 - train 0.12151 | val 0.15977
  Regression -> MSE: 0.000243, MAE: 0.011721, R²: -0.0045
  Directional -> Accuracy: 0.4571, MCC: -0.0589, F1: 0.4722

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.11823 | val 0.16802
  Epoch 020 - train 0.11481 | val 0.16838
  Regression -> MSE: 0.000314, MAE: 0.013661, R²: -0.0089
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.13503 | val 0.14703
  Epoch 020 - train 0.13340 | val 0.15300
  Regression -> MSE: 0.000680, MAE: 0.019516, R²: -0.0040
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.12189 | val 0.11441
  Epoch 020 - train 0.12445 | val 0.11273
  Regression -> MSE: 0.000144, MAE: 0.009459, R²: -0.0399
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.10988 | val 0.15305
  Epoch 020 - train 0.11028 | val 0.15588
  Regression -> MSE: 0.000224, MAE: 0.010678, R²: 0.0043
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.11441 | val 0.23522
  Epoch 020 - train 0.11463 | val 0.23714
  Regression -> MSE: 0.000362, MAE: 0.016082, R²: 0.0016
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.12131 | val 0.12313
  Epoch 020 - train 0.12133 | val 0.12524
  Regression -> MSE: 0.000109, MAE: 0.007956, R²: -0.0103
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.11735 | val 0.19623
  Epoch 020 - train 0.11836 | val 0.19995
  Regression -> MSE: 0.000157, MAE: 0.009714, R²: -0.0048
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.11946 | val 0.13164
  Epoch 020 - train 0.12315 | val 0.13138
  Regression -> MSE: 0.000276, MAE: 0.013251, R²: -0.0135
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.11251 | val 0.15792
  Epoch 020 - train 0.11052 | val 0.15772
  Regression -> MSE: 0.000164, MAE: 0.009050, R²: -0.0979
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.12268 | val 0.18850
  Epoch 020 - train 0.12106 | val 0.19105
  Regression -> MSE: 0.000235, MAE: 0.010924, R²: -0.0376
  Directional -> Accuracy: 0.5467, MCC: 0.1503, F1: 0.4516

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.12240 | val 0.15049
  Epoch 020 - train 0.11948 | val 0.15627
  Regression -> MSE: 0.000152, MAE: 0.008787, R²: -0.0626
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.11469 | val 0.13975
  Epoch 020 - train 0.11610 | val 0.14075
  Regression -> MSE: 0.000177, MAE: 0.010307, R²: -0.0691
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.12176 | val 0.13784
  Epoch 020 - train 0.12458 | val 0.13887
  Regression -> MSE: 0.000088, MAE: 0.007226, R²: -0.0382
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.11604 | val 0.15934
  Epoch 020 - train 0.11822 | val 0.16047
  Regression -> MSE: 0.000214, MAE: 0.011054, R²: -0.0114
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.11588 | val 0.11534
  Epoch 020 - train 0.11264 | val 0.11649
  Regression -> MSE: 0.000103, MAE: 0.008301, R²: -0.1185
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.13904 | val 0.09309
  Epoch 020 - train 0.13726 | val 0.11862
  Regression -> MSE: 0.000103, MAE: 0.008734, R²: -0.0021
  Directional -> Accuracy: 0.4348, MCC: -0.0870, F1: 0.5000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.12372 | val 0.11643
  Epoch 020 - train 0.12032 | val 0.14444
  Regression -> MSE: 0.000232, MAE: 0.012571, R²: -0.0020
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.11984 | val 0.15692
  Epoch 020 - train 0.11809 | val 0.15993
  Regression -> MSE: 0.000169, MAE: 0.007816, R²: -0.0129
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.12307 | val 0.10533
  Epoch 020 - train 0.11912 | val 0.14339
  Regression -> MSE: 0.000236, MAE: 0.011857, R²: 0.0003
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.11473 | val 0.18470
  Epoch 020 - train 0.11581 | val 0.18461
  Regression -> MSE: 0.000230, MAE: 0.009869, R²: -0.0002
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.12926 | val 0.14185
  Epoch 020 - train 0.12989 | val 0.14805
  Regression -> MSE: 0.000136, MAE: 0.008209, R²: -0.0054
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.12020 | val 0.15070
  Epoch 020 - train 0.11790 | val 0.15393
  Regression -> MSE: 0.000191, MAE: 0.010389, R²: -0.0134
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.11021 | val 0.14683
  Epoch 020 - train 0.10990 | val 0.14673
  Regression -> MSE: 0.000263, MAE: 0.010513, R²: -0.0056
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.11813 | val 0.10089
  Epoch 020 - train 0.11898 | val 0.10981
  Regression -> MSE: 0.000168, MAE: 0.010371, R²: -0.0089
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.11287 | val 0.12851
  Epoch 020 - train 0.11552 | val 0.14867
  Regression -> MSE: 0.000183, MAE: 0.010419, R²: -0.0147
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.12189 | val 0.11556
  Epoch 020 - train 0.11764 | val 0.11442
  Regression -> MSE: 0.000348, MAE: 0.011768, R²: -0.0170
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.12455 | val 0.07805
  Epoch 020 - train 0.12700 | val 0.07971
  Regression -> MSE: 0.000114, MAE: 0.008304, R²: -0.0850
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.11790 | val 0.16326
  Epoch 020 - train 0.11810 | val 0.16588
  Regression -> MSE: 0.000219, MAE: 0.011323, R²: -0.0024
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.11231 | val 0.20587
  Epoch 020 - train 0.11926 | val 0.22402
  Regression -> MSE: 0.000087, MAE: 0.007275, R²: -0.1141
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.11478 | val 0.09899
  Epoch 020 - train 0.11644 | val 0.09220
  Regression -> MSE: 0.000315, MAE: 0.013632, R²: -0.0249
  Directional -> Accuracy: 0.6122, MCC: 0.0973, F1: 0.3448

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.12682 | val 0.07391
  Epoch 020 - train 0.13313 | val 0.07368
  Regression -> MSE: 0.000256, MAE: 0.011463, R²: -0.0501
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.11794 | val 0.15884
  Epoch 020 - train 0.11813 | val 0.15674
  Regression -> MSE: 0.000081, MAE: 0.007074, R²: 0.0017
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.12343 | val 0.15297
  Epoch 020 - train 0.12284 | val 0.15993
  Regression -> MSE: 0.000308, MAE: 0.014476, R²: -0.0042
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.11624 | val 0.14148
  Epoch 020 - train 0.11139 | val 0.13803
  Regression -> MSE: 0.000102, MAE: 0.007103, R²: -0.0427
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.13198 | val 0.14018
  Epoch 020 - train 0.12990 | val 0.14717
  Regression -> MSE: 0.000173, MAE: 0.009948, R²: -0.0072
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.10868 | val 0.14334
  Epoch 020 - train 0.11131 | val 0.14587
  Regression -> MSE: 0.000223, MAE: 0.011733, R²: -0.0010
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.12337 | val 0.13582
  Epoch 020 - train 0.12170 | val 0.13820
  Regression -> MSE: 0.000092, MAE: 0.007646, R²: -0.0001
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.12415 | val 0.19027
  Epoch 020 - train 0.12453 | val 0.19146
  Regression -> MSE: 0.000168, MAE: 0.010317, R²: -0.0275
  Directional -> Accuracy: 0.4815, MCC: 0.0000, F1: 0.0000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.12277 | val 0.14796
  Epoch 020 - train 0.12023 | val 0.15300
  Regression -> MSE: 0.000121, MAE: 0.008987, R²: -0.0397
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.12096 | val 0.17897

[I 2026-02-23 01:22:56,750] Trial 172 finished with value: -0.011434699667895478 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 32, 'learning_rate': 1.7006217863507753e-06, 'weight_decay': 5.650644926432932e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.17643625751440908, 'early_stopping_min_delta': 0.0056588606896009405}. Best is trial 157 with value: -0.011387287234516647.

  Epoch 020 - train 0.12331 | val 0.18859
  Regression -> MSE: 0.000238, MAE: 0.012331, R²: -0.0047
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.12302 | val 0.15951
  Epoch 020 - train 0.12602 | val 0.15854
  Regression -> MSE: 0.000258, MAE: 0.012977, R²: -0.0418
  Directional -> Accuracy: 0.4545, MCC: -0.0855, F1: 0.4474

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.11717 | val 0.11573
  Epoch 020 - train 0.11713 | val 0.15791
  Regression -> MSE: 0.000686, MAE: 0.019377, R²: -0.0025
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.13095 | val 0.20388
  Epoch 020 - train 0.12871 | val 0.20537
  Regression -> MSE: 0.000323, MAE: 0.014565, R²: -0.0422
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.10563 | val 0.15071
  Epoch 020 - train 0.10790 | val 0.15856
  Regression -> MSE: 0.000380, MAE: 0.015087, R²: -0.0883
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.12388 | val 0.12880
  Epoch 020 - train 0.12534 | val 0.13806
  Regression -> MSE: 0.000204, MAE: 0.010056, R²: -0.0022
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.11974 | val 0.23293
  Epoch 020 - train 0.11943 | val 0.24022
  Regression -> MSE: 0.000604, MAE: 0.019074, R²: -0.0874
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.12573 | val 0.15760
  Epoch 020 - train 0.12744 | val 0.16015
  Regression -> MSE: 0.000245, MAE: 0.012106, R²: 0.0025
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.11950 | val 0.15803
  Epoch 020 - train 0.12253 | val 0.16349
  Regression -> MSE: 0.000624, MAE: 0.019766, R²: -0.0440
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.11599 | val 0.14792
  Epoch 020 - train 0.11505 | val 0.14396
  Regression -> MSE: 0.000441, MAE: 0.016767, R²: -0.1498
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.12299 | val 0.15604
  Epoch 020 - train 0.12023 | val 0.15747
  Regression -> MSE: 0.000243, MAE: 0.011672, R²: -0.0066
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.11787 | val 0.18951
  Epoch 020 - train 0.11659 | val 0.20153
  Regression -> MSE: 0.000312, MAE: 0.013695, R²: -0.0027
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.6301

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.13321 | val 0.16925
  Epoch 020 - train 0.13046 | val 0.18687
  Regression -> MSE: 0.000687, MAE: 0.019770, R²: -0.0142
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.12386 | val 0.11847
  Epoch 020 - train 0.12146 | val 0.12658
  Regression -> MSE: 0.000141, MAE: 0.009344, R²: -0.0208
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.11479 | val 0.16304
  Epoch 020 - train 0.11239 | val 0.16678
  Regression -> MSE: 0.000227, MAE: 0.010738, R²: -0.0078
  Directional -> Accuracy: 0.4918, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.12511 | val 0.24715
  Epoch 020 - train 0.12281 | val 0.25427
  Regression -> MSE: 0.000365, MAE: 0.015972, R²: -0.0084
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.13189 | val 0.13080
  Epoch 020 - train 0.13098 | val 0.13085
  Regression -> MSE: 0.000109, MAE: 0.007952, R²: -0.0102
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.12190 | val 0.20365
  Epoch 020 - train 0.11914 | val 0.20591
  Regression -> MSE: 0.000158, MAE: 0.009953, R²: -0.0152
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.12645 | val 0.12543
  Epoch 020 - train 0.12911 | val 0.12501
  Regression -> MSE: 0.000273, MAE: 0.013088, R²: -0.0022
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.11073 | val 0.16191
  Epoch 020 - train 0.10941 | val 0.16244
  Regression -> MSE: 0.000150, MAE: 0.008728, R²: -0.0056
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.14103 | val 0.21550
  Epoch 020 - train 0.13947 | val 0.21272
  Regression -> MSE: 0.000226, MAE: 0.010943, R²: -0.0005
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.12458 | val 0.17829
  Epoch 020 - train 0.12364 | val 0.22665
  Regression -> MSE: 0.000145, MAE: 0.008472, R²: -0.0115
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.11702 | val 0.14219
  Epoch 020 - train 0.11451 | val 0.14260
  Regression -> MSE: 0.000175, MAE: 0.010276, R²: -0.0569
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.12479 | val 0.14636
  Epoch 020 - train 0.12392 | val 0.15273
  Regression -> MSE: 0.000087, MAE: 0.007146, R²: -0.0201
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.12325 | val 0.15220
  Epoch 020 - train 0.12516 | val 0.15325
  Regression -> MSE: 0.000217, MAE: 0.011036, R²: -0.0245
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.11838 | val 0.11320
  Epoch 020 - train 0.11364 | val 0.11575
  Regression -> MSE: 0.000094, MAE: 0.008107, R²: -0.0236
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.12868 | val 0.09984
  Epoch 020 - train 0.12511 | val 0.10845
  Regression -> MSE: 0.000114, MAE: 0.009144, R²: -0.1024
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.12886 | val 0.11761
  Epoch 020 - train 0.12248 | val 0.12925
  Regression -> MSE: 0.000233, MAE: 0.012600, R²: -0.0054
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.11987 | val 0.14628
  Epoch 020 - train 0.12159 | val 0.14822
  Regression -> MSE: 0.000185, MAE: 0.008069, R²: -0.1130
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.12421 | val 0.10404
  Epoch 020 - train 0.12223 | val 0.12269
  Regression -> MSE: 0.000237, MAE: 0.011891, R²: -0.0040
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.12263 | val 0.18969
  Epoch 020 - train 0.12499 | val 0.19163
  Regression -> MSE: 0.000231, MAE: 0.009867, R²: -0.0005
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.12885 | val 0.13827
  Epoch 020 - train 0.13186 | val 0.14153
  Regression -> MSE: 0.000134, MAE: 0.008249, R²: 0.0096
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.13026 | val 0.15475
  Epoch 020 - train 0.12839 | val 0.16014
  Regression -> MSE: 0.000196, MAE: 0.010555, R²: -0.0394
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.11711 | val 0.13879
  Epoch 020 - train 0.11502 | val 0.13832
  Regression -> MSE: 0.000276, MAE: 0.010800, R²: -0.0524
  Directional -> Accuracy: 0.4384, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.12266 | val 0.11761
  Epoch 020 - train 0.12224 | val 0.13423
  Regression -> MSE: 0.000171, MAE: 0.010400, R²: -0.0287
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.11092 | val 0.12574
  Epoch 020 - train 0.11689 | val 0.12393
  Regression -> MSE: 0.000182, MAE: 0.010411, R²: -0.0125
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.12350 | val 0.11577
  Epoch 020 - train 0.12197 | val 0.11658
  Regression -> MSE: 0.000343, MAE: 0.011896, R²: -0.0001
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.13184 | val 0.07930
  Epoch 020 - train 0.12648 | val 0.08009
  Regression -> MSE: 0.000118, MAE: 0.008371, R²: -0.1209
  Directional -> Accuracy: 0.3488, MCC: -0.3432, F1: 0.1250

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.12466 | val 0.16495
  Epoch 020 - train 0.12461 | val 0.16538
  Regression -> MSE: 0.000225, MAE: 0.011452, R²: -0.0281
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.12414 | val 0.20744
  Epoch 020 - train 0.12512 | val 0.21054
  Regression -> MSE: 0.000085, MAE: 0.007200, R²: -0.0949
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.14060 | val 0.10595
  Epoch 020 - train 0.14043 | val 0.12904
  Regression -> MSE: 0.000332, MAE: 0.015067, R²: -0.0793
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.13230 | val 0.07922
  Epoch 020 - train 0.13610 | val 0.08012
  Regression -> MSE: 0.000258, MAE: 0.011469, R²: -0.0567
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.13204 | val 0.15235
  Epoch 020 - train 0.13093 | val 0.15440
  Regression -> MSE: 0.000087, MAE: 0.007094, R²: -0.0742
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.12666 | val 0.15277
  Epoch 020 - train 0.12329 | val 0.14864
  Regression -> MSE: 0.000310, MAE: 0.014646, R²: -0.0092
  Directional -> Accuracy: 0.4681, MCC: -0.0929, F1: 0.5902

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.12808 | val 0.13222
  Epoch 020 - train 0.12976 | val 0.12803
  Regression -> MSE: 0.000098, MAE: 0.007244, R²: -0.0003
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.13284 | val 0.14570
  Epoch 020 - train 0.13414 | val 0.15213
  Regression -> MSE: 0.000174, MAE: 0.010089, R²: -0.0137
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.11717 | val 0.14410
  Epoch 020 - train 0.11932 | val 0.15184
  Regression -> MSE: 0.000223, MAE: 0.011780, R²: -0.0019
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.11717 | val 0.14860
  Epoch 020 - train 0.12048 | val 0.15676
  Regression -> MSE: 0.000093, MAE: 0.007682, R²: -0.0068
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.13274 | val 0.18827
  Epoch 020 - train 0.12818 | val 0.18891
  Regression -> MSE: 0.000164, MAE: 0.010272, R²: -0.0019
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.11723 | val 0.15237
  Epoch 020 - train 0.11579 | val 0.15392
  Regression -> MSE: 0.000127, MAE: 0.009053, R²: -0.0932
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.12747 | val 0.20155

[I 2026-02-23 01:25:30,190] Trial 173 finished with value: -0.011488677348416623 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 32, 'learning_rate': 1.3080282048782824e-06, 'weight_decay': 5.165948366488318e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.18222824871082766, 'early_stopping_min_delta': 0.005615772592585679}. Best is trial 157 with value: -0.011387287234516647.

  Epoch 020 - train 0.12702 | val 0.21068
  Regression -> MSE: 0.000238, MAE: 0.012466, R²: -0.0015
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.07230 | val 0.09506
  Epoch 020 - train 0.07127 | val 0.09593
  Regression -> MSE: 0.000251, MAE: 0.012683, R²: -0.0134
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.06872 | val 0.06831
  Epoch 020 - train 0.06956 | val 0.07656
  Regression -> MSE: 0.000696, MAE: 0.019538, R²: -0.0162
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.07470 | val 0.11628
  Epoch 020 - train 0.07470 | val 0.11750
  Regression -> MSE: 0.000318, MAE: 0.014506, R²: -0.0253
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.05992 | val 0.06348
  Epoch 020 - train 0.06128 | val 0.06572
  Regression -> MSE: 0.000357, MAE: 0.014720, R²: -0.0222
  Directional -> Accuracy: 0.5333, MCC: -0.0286, F1: 0.6847

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.07107 | val 0.07412
  Epoch 020 - train 0.07064 | val 0.08787
  Regression -> MSE: 0.000204, MAE: 0.010052, R²: -0.0013
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.06993 | val 0.13008
  Epoch 020 - train 0.06948 | val 0.13433
  Regression -> MSE: 0.000557, MAE: 0.018146, R²: -0.0042
  Directional -> Accuracy: 0.5319, MCC: 0.0607, F1: 0.3889

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.07929 | val 0.09169
  Epoch 020 - train 0.07804 | val 0.09041
  Regression -> MSE: 0.000246, MAE: 0.011979, R²: -0.0010
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.06997 | val 0.09933
  Epoch 020 - train 0.07139 | val 0.10064
  Regression -> MSE: 0.000648, MAE: 0.020224, R²: -0.0846
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.06988 | val 0.08869
  Epoch 020 - train 0.07000 | val 0.08675
  Regression -> MSE: 0.000386, MAE: 0.016173, R²: -0.0062
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.07347 | val 0.09079
  Epoch 020 - train 0.07265 | val 0.09190
  Regression -> MSE: 0.000242, MAE: 0.011783, R²: -0.0023
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.06794 | val 0.10196
  Epoch 020 - train 0.06799 | val 0.10168
  Regression -> MSE: 0.000311, MAE: 0.013655, R²: -0.0013
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.07579 | val 0.09304
  Epoch 020 - train 0.07439 | val 0.09817
  Regression -> MSE: 0.000682, MAE: 0.019577, R²: -0.0076
  Directional -> Accuracy: 0.4310, MCC: -0.2265, F1: 0.0571

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.07021 | val 0.07530
  Epoch 020 - train 0.07066 | val 0.09059
  Regression -> MSE: 0.000140, MAE: 0.009281, R²: -0.0123
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.06564 | val 0.09590
  Epoch 020 - train 0.06474 | val 0.09772
  Regression -> MSE: 0.000228, MAE: 0.010770, R²: -0.0137
  Directional -> Accuracy: 0.4918, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.07003 | val 0.14046
  Epoch 020 - train 0.07008 | val 0.14411
  Regression -> MSE: 0.000366, MAE: 0.015981, R²: -0.0103
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.07672 | val 0.08332
  Epoch 020 - train 0.07374 | val 0.08275
  Regression -> MSE: 0.000109, MAE: 0.007969, R²: -0.0127
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.07077 | val 0.11943
  Epoch 020 - train 0.07064 | val 0.13016
  Regression -> MSE: 0.000162, MAE: 0.010164, R²: -0.0364
  Directional -> Accuracy: 0.3220, MCC: -0.2742, F1: 0.2308

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.07339 | val 0.07988
  Epoch 020 - train 0.07174 | val 0.07986
  Regression -> MSE: 0.000277, MAE: 0.013290, R²: -0.0180
  Directional -> Accuracy: 0.4079, MCC: -0.1317, F1: 0.3836

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.07131 | val 0.10569
  Epoch 020 - train 0.07049 | val 0.10708
  Regression -> MSE: 0.000151, MAE: 0.008754, R²: -0.0089
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.07418 | val 0.10071
  Epoch 020 - train 0.07199 | val 0.10084
  Regression -> MSE: 0.000228, MAE: 0.010910, R²: -0.0064
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.07539 | val 0.09126
  Epoch 020 - train 0.07524 | val 0.10305
  Regression -> MSE: 0.000151, MAE: 0.008702, R²: -0.0502
  Directional -> Accuracy: 0.5625, MCC: 0.0121, F1: 0.6769

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.06962 | val 0.09255
  Epoch 020 - train 0.06880 | val 0.09442
  Regression -> MSE: 0.000166, MAE: 0.010530, R²: -0.0024
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.07225 | val 0.08614
  Epoch 020 - train 0.07234 | val 0.08649
  Regression -> MSE: 0.000087, MAE: 0.007133, R²: -0.0177
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.07639 | val 0.08766
  Epoch 020 - train 0.07550 | val 0.08779
  Regression -> MSE: 0.000212, MAE: 0.011094, R²: 0.0006
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.06591 | val 0.06406
  Epoch 020 - train 0.06818 | val 0.06407
  Regression -> MSE: 0.000095, MAE: 0.008101, R²: -0.0312
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.07134 | val 0.05802
  Epoch 020 - train 0.07456 | val 0.06762
  Regression -> MSE: 0.000106, MAE: 0.008888, R²: -0.0271
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.07180 | val 0.06932
  Epoch 020 - train 0.07244 | val 0.07254
  Regression -> MSE: 0.000237, MAE: 0.012730, R²: -0.0219
  Directional -> Accuracy: 0.5116, MCC: 0.0044, F1: 0.5714

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.06783 | val 0.08620
  Epoch 020 - train 0.06923 | val 0.08657
  Regression -> MSE: 0.000178, MAE: 0.007906, R²: -0.0679
  Directional -> Accuracy: 0.5614, MCC: 0.2530, F1: 0.4186

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.07022 | val 0.06158
  Epoch 020 - train 0.07280 | val 0.06780
  Regression -> MSE: 0.000239, MAE: 0.011926, R²: -0.0089
  Directional -> Accuracy: 0.6341, MCC: 0.3071, F1: 0.7368

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.07442 | val 0.11368
  Epoch 020 - train 0.07111 | val 0.12165
  Regression -> MSE: 0.000233, MAE: 0.010057, R²: -0.0116
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.07921 | val 0.09759
  Epoch 020 - train 0.08106 | val 0.11234
  Regression -> MSE: 0.000144, MAE: 0.008736, R²: -0.0703
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.07496 | val 0.08940
  Epoch 020 - train 0.07434 | val 0.08911
  Regression -> MSE: 0.000189, MAE: 0.010447, R²: -0.0015
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.06513 | val 0.08754
  Epoch 020 - train 0.06323 | val 0.08737
  Regression -> MSE: 0.000262, MAE: 0.010620, R²: -0.0001
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.06931 | val 0.06055
  Epoch 020 - train 0.06472 | val 0.06052
  Regression -> MSE: 0.000169, MAE: 0.010366, R²: -0.0137
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.06693 | val 0.07271
  Epoch 020 - train 0.06749 | val 0.07371
  Regression -> MSE: 0.000180, MAE: 0.010306, R²: -0.0008
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.06636 | val 0.06843
  Epoch 020 - train 0.06583 | val 0.06907
  Regression -> MSE: 0.000345, MAE: 0.012092, R²: -0.0082
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.07457 | val 0.04788
  Epoch 020 - train 0.07623 | val 0.04652
  Regression -> MSE: 0.000114, MAE: 0.008323, R²: -0.0807
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.07371 | val 0.09566
  Epoch 020 - train 0.07549 | val 0.09660
  Regression -> MSE: 0.000219, MAE: 0.011300, R²: -0.0025
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.07009 | val 0.11835
  Epoch 020 - train 0.06977 | val 0.12389
  Regression -> MSE: 0.000093, MAE: 0.007551, R²: -0.2035
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.07427 | val 0.06026
  Epoch 020 - train 0.07109 | val 0.05668
  Regression -> MSE: 0.000335, MAE: 0.015193, R²: -0.0895
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.07869 | val 0.04922
  Epoch 020 - train 0.07743 | val 0.04850
  Regression -> MSE: 0.000263, MAE: 0.011516, R²: -0.0774
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.07309 | val 0.10151
  Epoch 020 - train 0.07291 | val 0.10456
  Regression -> MSE: 0.000083, MAE: 0.007042, R²: -0.0320
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.07314 | val 0.08938
  Epoch 020 - train 0.07003 | val 0.09704
  Regression -> MSE: 0.000308, MAE: 0.014505, R²: -0.0031
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.06914 | val 0.08246
  Epoch 020 - train 0.07101 | val 0.08334
  Regression -> MSE: 0.000101, MAE: 0.007114, R²: -0.0234
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.08156 | val 0.08481
  Epoch 020 - train 0.08327 | val 0.09682
  Regression -> MSE: 0.000172, MAE: 0.009539, R²: -0.0033
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.06948 | val 0.08393
  Epoch 020 - train 0.06615 | val 0.08758
  Regression -> MSE: 0.000225, MAE: 0.011817, R²: -0.0088
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.07322 | val 0.07904
  Epoch 020 - train 0.07437 | val 0.07972
  Regression -> MSE: 0.000093, MAE: 0.007649, R²: -0.0058
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.07788 | val 0.10652
  Epoch 020 - train 0.07711 | val 0.10568
  Regression -> MSE: 0.000164, MAE: 0.010276, R²: -0.0029
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.07026 | val 0.09328
  Epoch 020 - train 0.06878 | val 0.09862
  Regression -> MSE: 0.000123, MAE: 0.009000, R²: -0.0598
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.07289 | val 0.09874

[I 2026-02-23 01:28:11,274] Trial 174 finished with value: -0.011459307366521086 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 32, 'learning_rate': 2.7516671951717795e-06, 'weight_decay': 8.354366136944152e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.10137033540984056, 'early_stopping_min_delta': 0.00523459282608765}. Best is trial 157 with value: -0.011387287234516647.

  Epoch 020 - train 0.07179 | val 0.09932
  Regression -> MSE: 0.000239, MAE: 0.012351, R²: -0.0070
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.14747 | val 0.19220
  Epoch 020 - train 0.14618 | val 0.19214
  Regression -> MSE: 0.000249, MAE: 0.012609, R²: -0.0057
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.14854 | val 0.14762
  Epoch 020 - train 0.14387 | val 0.15373
  Regression -> MSE: 0.000688, MAE: 0.019363, R²: -0.0046
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.14624 | val 0.23685
  Epoch 020 - train 0.15022 | val 0.23434
  Regression -> MSE: 0.000321, MAE: 0.014501, R²: -0.0333
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.12216 | val 0.24328
  Epoch 020 - train 0.11981 | val 0.26147
  Regression -> MSE: 0.000357, MAE: 0.014709, R²: -0.0214
  Directional -> Accuracy: 0.5067, MCC: 0.0328, F1: 0.4789

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.14731 | val 0.14195
  Epoch 020 - train 0.13921 | val 0.14516
  Regression -> MSE: 0.000205, MAE: 0.010066, R²: -0.0089
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.13941 | val 0.28158
  Epoch 020 - train 0.14428 | val 0.28972
  Regression -> MSE: 0.000611, MAE: 0.019270, R²: -0.1014
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.14786 | val 0.18385
  Epoch 020 - train 0.14838 | val 0.18657
  Regression -> MSE: 0.000246, MAE: 0.011931, R²: -0.0004
  Directional -> Accuracy: 0.6087, MCC: 0.1467, F1: 0.0690

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.15034 | val 0.22125
  Epoch 020 - train 0.15462 | val 0.24378
  Regression -> MSE: 0.000670, MAE: 0.020566, R²: -0.1210
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.14280 | val 0.18577
  Epoch 020 - train 0.14377 | val 0.18104
  Regression -> MSE: 0.000379, MAE: 0.015802, R²: 0.0109
  Directional -> Accuracy: 0.5510, MCC: 0.1907, F1: 0.6333

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.15041 | val 0.19328
  Epoch 020 - train 0.14609 | val 0.19105
  Regression -> MSE: 0.000244, MAE: 0.011673, R²: -0.0089
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.14559 | val 0.20146
  Epoch 020 - train 0.14052 | val 0.20231
  Regression -> MSE: 0.000323, MAE: 0.013603, R²: -0.0399
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.14969 | val 0.17060
  Epoch 020 - train 0.14673 | val 0.17486
  Regression -> MSE: 0.000683, MAE: 0.019705, R²: -0.0088
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.17232 | val 0.20298
  Epoch 020 - train 0.16659 | val 0.31217
  Regression -> MSE: 0.000140, MAE: 0.008995, R²: -0.0099
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.13761 | val 0.22256
  Epoch 020 - train 0.13350 | val 0.24019
  Regression -> MSE: 0.000229, MAE: 0.010830, R²: -0.0193
  Directional -> Accuracy: 0.4918, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.13548 | val 0.29293
  Epoch 020 - train 0.13770 | val 0.29548
  Regression -> MSE: 0.000362, MAE: 0.016116, R²: -0.0005
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.16065 | val 0.16897
  Epoch 020 - train 0.15965 | val 0.16681
  Regression -> MSE: 0.000109, MAE: 0.008129, R²: -0.0119
  Directional -> Accuracy: 0.4571, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.14128 | val 0.23988
  Epoch 020 - train 0.13938 | val 0.24684
  Regression -> MSE: 0.000161, MAE: 0.010110, R²: -0.0304
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.14898 | val 0.17675
  Epoch 020 - train 0.14731 | val 0.17681
  Regression -> MSE: 0.000294, MAE: 0.013985, R²: -0.0803
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.12930 | val 0.19889
  Epoch 020 - train 0.12779 | val 0.19831
  Regression -> MSE: 0.000164, MAE: 0.009046, R²: -0.0980
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.16280 | val 0.20898
  Epoch 020 - train 0.15541 | val 0.20417
  Regression -> MSE: 0.000237, MAE: 0.010990, R²: -0.0453
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.14805 | val 0.18571
  Epoch 020 - train 0.15033 | val 0.19098
  Regression -> MSE: 0.000151, MAE: 0.008751, R²: -0.0549
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.13291 | val 0.17934
  Epoch 020 - train 0.13336 | val 0.18250
  Regression -> MSE: 0.000173, MAE: 0.010249, R²: -0.0459
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.15056 | val 0.16823
  Epoch 020 - train 0.14727 | val 0.16668
  Regression -> MSE: 0.000085, MAE: 0.007035, R²: 0.0021
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.14285 | val 0.19778
  Epoch 020 - train 0.14627 | val 0.19191
  Regression -> MSE: 0.000212, MAE: 0.011189, R²: -0.0022
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.13374 | val 0.12827
  Epoch 020 - train 0.13277 | val 0.12923
  Regression -> MSE: 0.000096, MAE: 0.008125, R²: -0.0412
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.15214 | val 0.12055
  Epoch 020 - train 0.15118 | val 0.11032
  Regression -> MSE: 0.000113, MAE: 0.008986, R²: -0.0944
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.15163 | val 0.13940
  Epoch 020 - train 0.15330 | val 0.14355
  Regression -> MSE: 0.000233, MAE: 0.012593, R²: -0.0046
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.14649 | val 0.17016
  Epoch 020 - train 0.15006 | val 0.17004
  Regression -> MSE: 0.000179, MAE: 0.007949, R²: -0.0744
  Directional -> Accuracy: 0.4561, MCC: -0.1198, F1: 0.5373

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.14727 | val 0.12283
  Epoch 020 - train 0.14612 | val 0.12930
  Regression -> MSE: 0.000237, MAE: 0.011895, R²: -0.0040
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.14271 | val 0.22782
  Epoch 020 - train 0.14128 | val 0.23224
  Regression -> MSE: 0.000231, MAE: 0.009876, R²: -0.0011
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.15549 | val 0.17954
  Epoch 020 - train 0.15356 | val 0.17505
  Regression -> MSE: 0.000137, MAE: 0.008299, R²: -0.0181
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.14617 | val 0.17946
  Epoch 020 - train 0.14222 | val 0.17758
  Regression -> MSE: 0.000186, MAE: 0.010433, R²: 0.0106
  Directional -> Accuracy: 0.5800, MCC: 0.1445, F1: 0.6957

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.13083 | val 0.17451
  Epoch 020 - train 0.12720 | val 0.17145
  Regression -> MSE: 0.000278, MAE: 0.010878, R²: -0.0613
  Directional -> Accuracy: 0.4384, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.13684 | val 0.13054
  Epoch 020 - train 0.14320 | val 0.12536
  Regression -> MSE: 0.000169, MAE: 0.010365, R²: -0.0123
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.13325 | val 0.15099
  Epoch 020 - train 0.12875 | val 0.15992
  Regression -> MSE: 0.000180, MAE: 0.010302, R²: -0.0011
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.16172 | val 0.15370
  Epoch 020 - train 0.15702 | val 0.14999
  Regression -> MSE: 0.000349, MAE: 0.012275, R²: -0.0189
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.15803 | val 0.09698
  Epoch 020 - train 0.15296 | val 0.09966
  Regression -> MSE: 0.000129, MAE: 0.008549, R²: -0.2257
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.14654 | val 0.20081
  Epoch 020 - train 0.14418 | val 0.20019
  Regression -> MSE: 0.000224, MAE: 0.011441, R²: -0.0229
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.14184 | val 0.24636
  Epoch 020 - train 0.14456 | val 0.24620
  Regression -> MSE: 0.000087, MAE: 0.007291, R²: -0.1183
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.14071 | val 0.10846
  Epoch 020 - train 0.14251 | val 0.11331
  Regression -> MSE: 0.000310, MAE: 0.013919, R²: -0.0069
  Directional -> Accuracy: 0.6327, MCC: 0.0000, F1: 0.0000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.15403 | val 0.08887
  Epoch 020 - train 0.15128 | val 0.09323
  Regression -> MSE: 0.000245, MAE: 0.011562, R²: -0.0064
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.0000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.14343 | val 0.18166
  Epoch 020 - train 0.14362 | val 0.18414
  Regression -> MSE: 0.000081, MAE: 0.007070, R²: -0.0067
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.14432 | val 0.17861
  Epoch 020 - train 0.14343 | val 0.16647
  Regression -> MSE: 0.000298, MAE: 0.014407, R²: 0.0288
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.14467 | val 0.16331
  Epoch 020 - train 0.14066 | val 0.16585
  Regression -> MSE: 0.000099, MAE: 0.007166, R²: -0.0063
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.15095 | val 0.17206
  Epoch 020 - train 0.15583 | val 0.17413
  Regression -> MSE: 0.000175, MAE: 0.010160, R²: -0.0194
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.13541 | val 0.16382
  Epoch 020 - train 0.13462 | val 0.16363
  Regression -> MSE: 0.000223, MAE: 0.011782, R²: -0.0015
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.14373 | val 0.16102
  Epoch 020 - train 0.14461 | val 0.16201
  Regression -> MSE: 0.000093, MAE: 0.007643, R²: -0.0042
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.14874 | val 0.23236
  Epoch 020 - train 0.15014 | val 0.25462
  Regression -> MSE: 0.000164, MAE: 0.010253, R²: 0.0007
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.14361 | val 0.18073
  Epoch 020 - train 0.13623 | val 0.18353
  Regression -> MSE: 0.000117, MAE: 0.008949, R²: -0.0128
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.14666 | val 0.20252

[I 2026-02-23 01:30:52,909] Trial 175 finished with value: -0.011475558252397135 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 32, 'learning_rate': 3.4045753674547454e-06, 'weight_decay': 5.831224942916226e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.222644609825251, 'early_stopping_min_delta': 0.0063347133349728494}. Best is trial 157 with value: -0.011387287234516647.

  Epoch 020 - train 0.14207 | val 0.20349
  Regression -> MSE: 0.000246, MAE: 0.012387, R²: -0.0369
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.18640 | val 0.27655
  Epoch 020 - train 0.18066 | val 0.27414
  Regression -> MSE: 0.000252, MAE: 0.012768, R²: -0.0161
  Directional -> Accuracy: 0.4026, MCC: -0.1862, F1: 0.4103

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.21218 | val 0.20019
  Epoch 020 - train 0.21329 | val 0.26810
  Regression -> MSE: 0.000684, MAE: 0.019364, R²: 0.0005
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.18331 | val 0.30737
  Epoch 020 - train 0.18963 | val 0.31359
  Regression -> MSE: 0.000310, MAE: 0.014414, R²: 0.0002
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.15424 | val 0.17689
  Epoch 020 - train 0.15254 | val 0.18896
  Regression -> MSE: 0.000349, MAE: 0.014564, R²: 0.0015
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.19752 | val 0.19590
  Epoch 020 - train 0.20194 | val 0.21453
  Regression -> MSE: 0.000208, MAE: 0.010147, R²: -0.0236
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.18094 | val 0.35323
  Epoch 020 - train 0.17242 | val 0.35735
  Regression -> MSE: 0.000572, MAE: 0.018405, R²: -0.0295
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.19099 | val 0.22645
  Epoch 020 - train 0.19033 | val 0.22495
  Regression -> MSE: 0.000264, MAE: 0.012319, R²: -0.0756
  Directional -> Accuracy: 0.5797, MCC: 0.0754, F1: 0.3556

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.19174 | val 0.25165
  Epoch 020 - train 0.18897 | val 0.24665
  Regression -> MSE: 0.000633, MAE: 0.019953, R²: -0.0590
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.18159 | val 0.21579
  Epoch 020 - train 0.18048 | val 0.21263
  Regression -> MSE: 0.000506, MAE: 0.017857, R²: -0.3186
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.19062 | val 0.24042
  Epoch 020 - train 0.19798 | val 0.24223
  Regression -> MSE: 0.000243, MAE: 0.011731, R²: -0.0049
  Directional -> Accuracy: 0.4000, MCC: -0.1443, F1: 0.5116

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.19259 | val 0.28043
  Epoch 020 - train 0.19668 | val 0.29089
  Regression -> MSE: 0.000312, MAE: 0.013797, R²: -0.0022
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.6301

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.18901 | val 0.21151
  Epoch 020 - train 0.18617 | val 0.21897
  Regression -> MSE: 0.000684, MAE: 0.019705, R²: -0.0094
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.19374 | val 0.18135
  Epoch 020 - train 0.18939 | val 0.18746
  Regression -> MSE: 0.000139, MAE: 0.009236, R²: -0.0081
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.17362 | val 0.25705
  Epoch 020 - train 0.16736 | val 0.25526
  Regression -> MSE: 0.000228, MAE: 0.010959, R²: -0.0126
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.19792 | val 0.40108
  Epoch 020 - train 0.19810 | val 0.42401
  Regression -> MSE: 0.000373, MAE: 0.015941, R²: -0.0305
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.19657 | val 0.21280
  Epoch 020 - train 0.19299 | val 0.21414
  Regression -> MSE: 0.000108, MAE: 0.007930, R²: -0.0026
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.19201 | val 0.29053
  Epoch 020 - train 0.18837 | val 0.29006
  Regression -> MSE: 0.000169, MAE: 0.010532, R²: -0.0872
  Directional -> Accuracy: 0.3729, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.19322 | val 0.19391
  Epoch 020 - train 0.19014 | val 0.19606
  Regression -> MSE: 0.000282, MAE: 0.013478, R²: -0.0347
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.17301 | val 0.27670
  Epoch 020 - train 0.17873 | val 0.28722
  Regression -> MSE: 0.000162, MAE: 0.009008, R²: -0.0857
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.19331 | val 0.27288
  Epoch 020 - train 0.19548 | val 0.27244
  Regression -> MSE: 0.000241, MAE: 0.011073, R²: -0.0632
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.19378 | val 0.23821
  Epoch 020 - train 0.18616 | val 0.24271
  Regression -> MSE: 0.000143, MAE: 0.008313, R²: -0.0006
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.17940 | val 0.21421
  Epoch 020 - train 0.17045 | val 0.21506
  Regression -> MSE: 0.000178, MAE: 0.010317, R²: -0.0793
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.20647 | val 0.22377
  Epoch 020 - train 0.20236 | val 0.22697
  Regression -> MSE: 0.000086, MAE: 0.007098, R²: -0.0104
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.19140 | val 0.26145
  Epoch 020 - train 0.18512 | val 0.26501
  Regression -> MSE: 0.000214, MAE: 0.011365, R²: -0.0086
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.17666 | val 0.17206
  Epoch 020 - train 0.17573 | val 0.17442
  Regression -> MSE: 0.000104, MAE: 0.008314, R²: -0.1313
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.19333 | val 0.15595
  Epoch 020 - train 0.18633 | val 0.18132
  Regression -> MSE: 0.000114, MAE: 0.009140, R²: -0.1012
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.18265 | val 0.18657
  Epoch 020 - train 0.19125 | val 0.21216
  Regression -> MSE: 0.000233, MAE: 0.012612, R²: -0.0071
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.18259 | val 0.21620
  Epoch 020 - train 0.18039 | val 0.21762
  Regression -> MSE: 0.000188, MAE: 0.008149, R²: -0.1325
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.19782 | val 0.15344
  Epoch 020 - train 0.19472 | val 0.15635
  Regression -> MSE: 0.000237, MAE: 0.011880, R²: -0.0022
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.19465 | val 0.29609
  Epoch 020 - train 0.18432 | val 0.32168
  Regression -> MSE: 0.000231, MAE: 0.009874, R²: -0.0006
  Directional -> Accuracy: 0.4419, MCC: -0.1182, F1: 0.5385

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.18834 | val 0.21761
  Epoch 020 - train 0.18867 | val 0.23801
  Regression -> MSE: 0.000146, MAE: 0.008412, R²: -0.0780
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.18630 | val 0.23292
  Epoch 020 - train 0.18454 | val 0.23499
  Regression -> MSE: 0.000196, MAE: 0.010569, R²: -0.0418
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.16549 | val 0.21208
  Epoch 020 - train 0.16662 | val 0.21244
  Regression -> MSE: 0.000281, MAE: 0.010984, R²: -0.0734
  Directional -> Accuracy: 0.4384, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.17869 | val 0.15852
  Epoch 020 - train 0.17627 | val 0.15661
  Regression -> MSE: 0.000167, MAE: 0.010379, R²: -0.0045
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.16840 | val 0.18978
  Epoch 020 - train 0.16234 | val 0.19879
  Regression -> MSE: 0.000180, MAE: 0.010296, R²: -0.0002
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.17481 | val 0.17028
  Epoch 020 - train 0.17840 | val 0.16735
  Regression -> MSE: 0.000344, MAE: 0.011985, R²: -0.0041
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.20423 | val 0.12079
  Epoch 020 - train 0.19902 | val 0.12152
  Regression -> MSE: 0.000110, MAE: 0.008327, R²: -0.0478
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.20907 | val 0.34887
  Epoch 020 - train 0.21224 | val 0.37636
  Regression -> MSE: 0.000223, MAE: 0.011445, R²: -0.0210
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.18945 | val 0.32349
  Epoch 020 - train 0.18900 | val 0.32879
  Regression -> MSE: 0.000088, MAE: 0.007333, R²: -0.1308
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.18096 | val 0.14445
  Epoch 020 - train 0.18007 | val 0.13958
  Regression -> MSE: 0.000320, MAE: 0.014523, R²: -0.0406
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.19566 | val 0.10866
  Epoch 020 - train 0.19018 | val 0.10627
  Regression -> MSE: 0.000253, MAE: 0.011469, R²: -0.0392
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.17608 | val 0.22588
  Epoch 020 - train 0.17106 | val 0.22617
  Regression -> MSE: 0.000081, MAE: 0.007077, R²: 0.0004
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.20020 | val 0.22969
  Epoch 020 - train 0.18964 | val 0.24237
  Regression -> MSE: 0.000309, MAE: 0.014519, R²: -0.0076
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.17503 | val 0.19688
  Epoch 020 - train 0.17975 | val 0.20968
  Regression -> MSE: 0.000098, MAE: 0.007292, R²: 0.0017
  Directional -> Accuracy: 0.4318, MCC: 0.0000, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.20108 | val 0.22023
  Epoch 020 - train 0.19498 | val 0.21289
  Regression -> MSE: 0.000172, MAE: 0.009615, R²: -0.0028
  Directional -> Accuracy: 0.5714, MCC: 0.0711, F1: 0.4000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.17379 | val 0.21492
  Epoch 020 - train 0.17881 | val 0.21974
  Regression -> MSE: 0.000223, MAE: 0.011788, R²: -0.0016
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.18192 | val 0.20711
  Epoch 020 - train 0.18488 | val 0.21661
  Regression -> MSE: 0.000093, MAE: 0.007640, R²: -0.0039
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.19716 | val 0.28710
  Epoch 020 - train 0.19366 | val 0.28724
  Regression -> MSE: 0.000165, MAE: 0.010274, R²: -0.0050
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.17198 | val 0.24576
  Epoch 020 - train 0.17447 | val 0.26722
  Regression -> MSE: 0.000124, MAE: 0.009021, R²: -0.0738
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.18507 | val 0.26466

[I 2026-02-23 01:33:32,644] Trial 176 finished with value: -0.011513585322418234 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 32, 'learning_rate': 1.8370658891602482e-06, 'weight_decay': 4.503662489069512e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.2954740557989979, 'early_stopping_min_delta': 0.006064949098131896}. Best is trial 157 with value: -0.011387287234516647.

  Epoch 020 - train 0.18699 | val 0.26677
  Regression -> MSE: 0.000238, MAE: 0.012485, R²: -0.0027
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.09924 | val 0.12961
  Epoch 020 - train 0.09575 | val 0.12997
  Regression -> MSE: 0.000248, MAE: 0.012508, R²: -0.0005
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.10260 | val 0.09502
  Epoch 020 - train 0.10004 | val 0.10001
  Regression -> MSE: 0.000697, MAE: 0.019580, R²: -0.0187
  Directional -> Accuracy: 0.5435, MCC: -0.1307, F1: 0.7042

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.10132 | val 0.16302
  Epoch 020 - train 0.10102 | val 0.16039
  Regression -> MSE: 0.000316, MAE: 0.014471, R²: -0.0197
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.08501 | val 0.08837
  Epoch 020 - train 0.08304 | val 0.09196
  Regression -> MSE: 0.000360, MAE: 0.014750, R²: -0.0309
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.10392 | val 0.10238
  Epoch 020 - train 0.10412 | val 0.10172
  Regression -> MSE: 0.000204, MAE: 0.010098, R²: -0.0033
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.09498 | val 0.18113
  Epoch 020 - train 0.09755 | val 0.20988
  Regression -> MSE: 0.000556, MAE: 0.018180, R²: -0.0021
  Directional -> Accuracy: 0.5106, MCC: 0.0045, F1: 0.0800

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.10712 | val 0.12684
  Epoch 020 - train 0.10279 | val 0.12769
  Regression -> MSE: 0.000247, MAE: 0.011925, R²: -0.0069
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.09657 | val 0.13484
  Epoch 020 - train 0.10208 | val 0.12747
  Regression -> MSE: 0.000630, MAE: 0.019854, R²: -0.0542
  Directional -> Accuracy: 0.4318, MCC: 0.0417, F1: 0.5763

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.09663 | val 0.12236
  Epoch 020 - train 0.09769 | val 0.12165
  Regression -> MSE: 0.000388, MAE: 0.016037, R²: -0.0127
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.10577 | val 0.13820
  Epoch 020 - train 0.10180 | val 0.14331
  Regression -> MSE: 0.000247, MAE: 0.011636, R²: -0.0219
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.09557 | val 0.14279
  Epoch 020 - train 0.09521 | val 0.14502
  Regression -> MSE: 0.000312, MAE: 0.013649, R²: -0.0036
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.10350 | val 0.12333
  Epoch 020 - train 0.10494 | val 0.12965
  Regression -> MSE: 0.000680, MAE: 0.019511, R²: -0.0038
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.09739 | val 0.10492
  Epoch 020 - train 0.10095 | val 0.11157
  Regression -> MSE: 0.000139, MAE: 0.009030, R²: -0.0041
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.09323 | val 0.13492
  Epoch 020 - train 0.09214 | val 0.13293
  Regression -> MSE: 0.000227, MAE: 0.010902, R²: -0.0077
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.09925 | val 0.20787
  Epoch 020 - train 0.09738 | val 0.20695
  Regression -> MSE: 0.000362, MAE: 0.016038, R²: -0.0006
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.10346 | val 0.10408
  Epoch 020 - train 0.10288 | val 0.10420
  Regression -> MSE: 0.000108, MAE: 0.007946, R²: -0.0019
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.09874 | val 0.15702
  Epoch 020 - train 0.09807 | val 0.15808
  Regression -> MSE: 0.000156, MAE: 0.009588, R²: -0.0019
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.10211 | val 0.10692
  Epoch 020 - train 0.10186 | val 0.11037
  Regression -> MSE: 0.000272, MAE: 0.012943, R²: 0.0006
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.09234 | val 0.13187
  Epoch 020 - train 0.08927 | val 0.13158
  Regression -> MSE: 0.000152, MAE: 0.008737, R²: -0.0167
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.10963 | val 0.13814
  Epoch 020 - train 0.10616 | val 0.13624
  Regression -> MSE: 0.000242, MAE: 0.011093, R²: -0.0682
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.10798 | val 0.12532
  Epoch 020 - train 0.10635 | val 0.12906
  Regression -> MSE: 0.000150, MAE: 0.008696, R²: -0.0476
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.09467 | val 0.11611
  Epoch 020 - train 0.09285 | val 0.11544
  Regression -> MSE: 0.000165, MAE: 0.010450, R²: 0.0012
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.10718 | val 0.11495
  Epoch 020 - train 0.10904 | val 0.11532
  Regression -> MSE: 0.000089, MAE: 0.007282, R²: -0.0423
  Directional -> Accuracy: 0.5517, MCC: 0.1248, F1: 0.5517

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.09834 | val 0.12884
  Epoch 020 - train 0.09814 | val 0.13265
  Regression -> MSE: 0.000212, MAE: 0.011071, R²: -0.0013
  Directional -> Accuracy: 0.5152, MCC: 0.0051, F1: 0.3600

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.09422 | val 0.09049
  Epoch 020 - train 0.09177 | val 0.08918
  Regression -> MSE: 0.000098, MAE: 0.008159, R²: -0.0615
  Directional -> Accuracy: 0.6071, MCC: 0.2284, F1: 0.6071

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.09674 | val 0.07856
  Epoch 020 - train 0.09951 | val 0.07943
  Regression -> MSE: 0.000104, MAE: 0.008775, R²: -0.0068
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.10246 | val 0.09807
  Epoch 020 - train 0.10529 | val 0.12625
  Regression -> MSE: 0.000233, MAE: 0.012613, R²: -0.0075
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.10920 | val 0.11708
  Epoch 020 - train 0.10916 | val 0.11979
  Regression -> MSE: 0.000181, MAE: 0.007988, R²: -0.0882
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.10322 | val 0.08875
  Epoch 020 - train 0.10122 | val 0.08985
  Regression -> MSE: 0.000238, MAE: 0.011938, R²: -0.0066
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.10250 | val 0.16315
  Epoch 020 - train 0.10598 | val 0.16997
  Regression -> MSE: 0.000235, MAE: 0.010139, R²: -0.0180
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.10774 | val 0.12716
  Epoch 020 - train 0.10048 | val 0.12715
  Regression -> MSE: 0.000139, MAE: 0.008415, R²: -0.0318
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.09960 | val 0.12724
  Epoch 020 - train 0.09868 | val 0.12886
  Regression -> MSE: 0.000190, MAE: 0.010353, R²: -0.0092
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.08783 | val 0.11501
  Epoch 020 - train 0.08785 | val 0.11409
  Regression -> MSE: 0.000267, MAE: 0.010543, R²: -0.0182
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.09699 | val 0.08655
  Epoch 020 - train 0.09693 | val 0.08485
  Regression -> MSE: 0.000167, MAE: 0.010374, R²: -0.0029
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.09138 | val 0.10858
  Epoch 020 - train 0.09124 | val 0.12818
  Regression -> MSE: 0.000183, MAE: 0.010423, R²: -0.0170
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.09945 | val 0.09703
  Epoch 020 - train 0.09943 | val 0.09682
  Regression -> MSE: 0.000344, MAE: 0.011981, R²: -0.0041
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.10574 | val 0.06626
  Epoch 020 - train 0.10262 | val 0.06639
  Regression -> MSE: 0.000124, MAE: 0.008437, R²: -0.1789
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.10762 | val 0.13924
  Epoch 020 - train 0.10952 | val 0.14182
  Regression -> MSE: 0.000222, MAE: 0.011406, R²: -0.0152
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.10328 | val 0.16758
  Epoch 020 - train 0.10168 | val 0.17180
  Regression -> MSE: 0.000087, MAE: 0.007275, R²: -0.1140
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.10774 | val 0.07576
  Epoch 020 - train 0.10790 | val 0.07973
  Regression -> MSE: 0.000308, MAE: 0.013668, R²: -0.0018
  Directional -> Accuracy: 0.6327, MCC: 0.0000, F1: 0.0000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.11175 | val 0.06348
  Epoch 020 - train 0.11059 | val 0.07071
  Regression -> MSE: 0.000245, MAE: 0.011559, R²: -0.0052
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.0000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.09548 | val 0.11866
  Epoch 020 - train 0.09235 | val 0.11818
  Regression -> MSE: 0.000082, MAE: 0.007056, R²: -0.0142
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.10003 | val 0.12326
  Epoch 020 - train 0.10071 | val 0.13291
  Regression -> MSE: 0.000307, MAE: 0.014506, R²: -0.0010
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.09559 | val 0.11081
  Epoch 020 - train 0.09816 | val 0.11262
  Regression -> MSE: 0.000099, MAE: 0.007193, R²: -0.0041
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.10776 | val 0.11574
  Epoch 020 - train 0.10701 | val 0.11495
  Regression -> MSE: 0.000172, MAE: 0.009798, R²: -0.0017
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.09943 | val 0.11849
  Epoch 020 - train 0.09818 | val 0.12033
  Regression -> MSE: 0.000225, MAE: 0.011806, R²: -0.0076
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.09949 | val 0.13127
  Epoch 020 - train 0.09860 | val 0.14581
  Regression -> MSE: 0.000093, MAE: 0.007691, R²: -0.0083
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.10824 | val 0.15173
  Epoch 020 - train 0.10820 | val 0.15293
  Regression -> MSE: 0.000164, MAE: 0.010282, R²: -0.0025
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.10220 | val 0.12349
  Epoch 020 - train 0.10334 | val 0.12461
  Regression -> MSE: 0.000121, MAE: 0.008985, R²: -0.0434
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.10448 | val 0.13812

[I 2026-02-23 01:36:14,145] Trial 177 finished with value: -0.011393302765348567 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 32, 'learning_rate': 3.196861883993194e-06, 'weight_decay': 4.276236502374101e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.14613724157585978, 'early_stopping_min_delta': 0.005799456178594611}. Best is trial 157 with value: -0.011387287234516647.

  Epoch 020 - train 0.10264 | val 0.13835
  Regression -> MSE: 0.000238, MAE: 0.012327, R²: -0.0022
  Directional -> Accuracy: 0.5738, MCC: 0.1722, F1: 0.2778

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.10383 | val 0.13640
  Epoch 020 - train 0.10308 | val 0.13672
  Regression -> MSE: 0.000248, MAE: 0.012519, R²: 0.0000
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.10380 | val 0.09766
  Epoch 020 - train 0.10171 | val 0.10773
  Regression -> MSE: 0.000688, MAE: 0.019410, R²: -0.0057
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.10987 | val 0.16799
  Epoch 020 - train 0.10806 | val 0.16562
  Regression -> MSE: 0.000323, MAE: 0.014565, R²: -0.0403
  Directional -> Accuracy: 0.5106, MCC: 0.0255, F1: 0.5106

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.09453 | val 0.09352
  Epoch 020 - train 0.09256 | val 0.09502
  Regression -> MSE: 0.000349, MAE: 0.014580, R²: -0.0005
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.11201 | val 0.10706
  Epoch 020 - train 0.10665 | val 0.10768
  Regression -> MSE: 0.000207, MAE: 0.010145, R²: -0.0151
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.09795 | val 0.19160
  Epoch 020 - train 0.10179 | val 0.19187
  Regression -> MSE: 0.000568, MAE: 0.018324, R²: -0.0223
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.11381 | val 0.15649
  Epoch 020 - train 0.11174 | val 0.15240
  Regression -> MSE: 0.000249, MAE: 0.012424, R²: -0.0141
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.10118 | val 0.14313
  Epoch 020 - train 0.10112 | val 0.14973
  Regression -> MSE: 0.000637, MAE: 0.020022, R²: -0.0655
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.10096 | val 0.12592
  Epoch 020 - train 0.09486 | val 0.12855
  Regression -> MSE: 0.000397, MAE: 0.016008, R²: -0.0361
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.10495 | val 0.13366
  Epoch 020 - train 0.10340 | val 0.13665
  Regression -> MSE: 0.000243, MAE: 0.011712, R²: -0.0050
  Directional -> Accuracy: 0.5000, MCC: 0.0083, F1: 0.4776

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.09921 | val 0.16830
  Epoch 020 - train 0.09838 | val 0.19338
  Regression -> MSE: 0.000312, MAE: 0.013646, R²: -0.0030
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.10898 | val 0.12257
  Epoch 020 - train 0.11382 | val 0.12385
  Regression -> MSE: 0.000681, MAE: 0.019593, R²: -0.0060
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.10826 | val 0.10605
  Epoch 020 - train 0.10809 | val 0.10776
  Regression -> MSE: 0.000139, MAE: 0.009224, R²: -0.0076
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.09409 | val 0.13704
  Epoch 020 - train 0.09744 | val 0.13642
  Regression -> MSE: 0.000225, MAE: 0.010687, R²: 0.0005
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.10121 | val 0.20737
  Epoch 020 - train 0.09900 | val 0.20853
  Regression -> MSE: 0.000367, MAE: 0.015955, R²: -0.0141
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.11494 | val 0.12494
  Epoch 020 - train 0.11622 | val 0.12292
  Regression -> MSE: 0.000109, MAE: 0.007972, R²: -0.0071
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.10108 | val 0.17138
  Epoch 020 - train 0.10560 | val 0.17426
  Regression -> MSE: 0.000158, MAE: 0.009826, R²: -0.0107
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.10533 | val 0.10634
  Epoch 020 - train 0.10671 | val 0.10590
  Regression -> MSE: 0.000276, MAE: 0.013230, R²: -0.0133
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.09654 | val 0.13801
  Epoch 020 - train 0.09510 | val 0.13804
  Regression -> MSE: 0.000160, MAE: 0.008922, R²: -0.0720
  Directional -> Accuracy: 0.4615, MCC: 0.1262, F1: 0.1860

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.10808 | val 0.16698
  Epoch 020 - train 0.10680 | val 0.16356
  Regression -> MSE: 0.000234, MAE: 0.010929, R²: -0.0339
  Directional -> Accuracy: 0.5333, MCC: 0.1473, F1: 0.3860

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.10183 | val 0.12922
  Epoch 020 - train 0.10349 | val 0.13203
  Regression -> MSE: 0.000144, MAE: 0.008343, R²: -0.0021
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.10211 | val 0.12716
  Epoch 020 - train 0.09989 | val 0.12770
  Regression -> MSE: 0.000165, MAE: 0.010428, R²: -0.0004
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.10922 | val 0.12108
  Epoch 020 - train 0.10861 | val 0.12311
  Regression -> MSE: 0.000086, MAE: 0.007114, R²: -0.0134
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.10812 | val 0.14335
  Epoch 020 - train 0.10659 | val 0.14230
  Regression -> MSE: 0.000214, MAE: 0.011405, R²: -0.0121
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.10074 | val 0.10151
  Epoch 020 - train 0.09715 | val 0.10235
  Regression -> MSE: 0.000096, MAE: 0.008135, R²: -0.0454
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.10966 | val 0.08188
  Epoch 020 - train 0.10664 | val 0.08515
  Regression -> MSE: 0.000103, MAE: 0.008722, R²: -0.0005
  Directional -> Accuracy: 0.5435, MCC: 0.0658, F1: 0.4615

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.11804 | val 0.10060
  Epoch 020 - train 0.11342 | val 0.10424
  Regression -> MSE: 0.000234, MAE: 0.012658, R²: -0.0131
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.10435 | val 0.12409
  Epoch 020 - train 0.10161 | val 0.12528
  Regression -> MSE: 0.000178, MAE: 0.007922, R²: -0.0722
  Directional -> Accuracy: 0.4912, MCC: 0.1491, F1: 0.2162

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.10940 | val 0.08997
  Epoch 020 - train 0.10912 | val 0.09600
  Regression -> MSE: 0.000237, MAE: 0.011884, R²: -0.0029
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.10628 | val 0.16182
  Epoch 020 - train 0.10442 | val 0.16609
  Regression -> MSE: 0.000231, MAE: 0.009865, R²: -0.0019
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.10676 | val 0.12855
  Epoch 020 - train 0.10702 | val 0.13065
  Regression -> MSE: 0.000137, MAE: 0.008274, R²: -0.0135
  Directional -> Accuracy: 0.5581, MCC: 0.1092, F1: 0.5957

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.10814 | val 0.13060
  Epoch 020 - train 0.10406 | val 0.13168
  Regression -> MSE: 0.000192, MAE: 0.010421, R²: -0.0216
  Directional -> Accuracy: 0.4600, MCC: -0.0983, F1: 0.5263

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.09893 | val 0.13157
  Epoch 020 - train 0.10090 | val 0.13117
  Regression -> MSE: 0.000264, MAE: 0.010529, R²: -0.0074
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.12459 | val 0.09757
  Epoch 020 - train 0.11702 | val 0.12587
  Regression -> MSE: 0.000168, MAE: 0.010373, R²: -0.0104
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.10076 | val 0.11998
  Epoch 020 - train 0.09532 | val 0.15078
  Regression -> MSE: 0.000181, MAE: 0.010352, R²: -0.0046
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.09917 | val 0.09403
  Epoch 020 - train 0.10005 | val 0.09355
  Regression -> MSE: 0.000342, MAE: 0.011732, R²: 0.0013
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.12397 | val 0.07509
  Epoch 020 - train 0.12161 | val 0.12277
  Regression -> MSE: 0.000131, MAE: 0.008581, R²: -0.2423
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.11782 | val 0.15770
  Epoch 020 - train 0.11433 | val 0.15982
  Regression -> MSE: 0.000226, MAE: 0.011507, R²: -0.0352
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.10232 | val 0.17872
  Epoch 020 - train 0.10137 | val 0.18478
  Regression -> MSE: 0.000085, MAE: 0.007216, R²: -0.0986
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.11015 | val 0.08823
  Epoch 020 - train 0.10473 | val 0.08940
  Regression -> MSE: 0.000329, MAE: 0.014941, R²: -0.0694
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.11458 | val 0.06770
  Epoch 020 - train 0.11555 | val 0.07056
  Regression -> MSE: 0.000254, MAE: 0.011467, R²: -0.0432
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.10355 | val 0.12514
  Epoch 020 - train 0.10239 | val 0.12544
  Regression -> MSE: 0.000083, MAE: 0.007050, R²: -0.0286
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.10764 | val 0.13531
  Epoch 020 - train 0.10901 | val 0.17831
  Regression -> MSE: 0.000307, MAE: 0.014491, R²: -0.0013
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.10639 | val 0.11869
  Epoch 020 - train 0.10265 | val 0.11411
  Regression -> MSE: 0.000100, MAE: 0.007136, R²: -0.0179
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.11305 | val 0.12162
  Epoch 020 - train 0.11248 | val 0.12991
  Regression -> MSE: 0.000172, MAE: 0.009710, R²: -0.0002
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.10069 | val 0.11653
  Epoch 020 - train 0.09765 | val 0.11738
  Regression -> MSE: 0.000223, MAE: 0.011747, R²: -0.0005
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.10720 | val 0.11857
  Epoch 020 - train 0.10089 | val 0.11986
  Regression -> MSE: 0.000093, MAE: 0.007688, R²: -0.0095
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.12107 | val 0.16209
  Epoch 020 - train 0.12117 | val 0.16932
  Regression -> MSE: 0.000165, MAE: 0.010314, R²: -0.0081
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.10490 | val 0.13005
  Epoch 020 - train 0.10521 | val 0.13072
  Regression -> MSE: 0.000131, MAE: 0.009116, R²: -0.1284
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.11189 | val 0.15179

[I 2026-02-23 01:38:56,615] Trial 178 finished with value: -0.011423874683893569 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 32, 'learning_rate': 3.214259084287978e-06, 'weight_decay': 4.072252634284812e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.15377945430420112, 'early_stopping_min_delta': 0.0056281151190323555}. Best is trial 157 with value: -0.011387287234516647.

  Epoch 020 - train 0.11027 | val 0.15448
  Regression -> MSE: 0.000246, MAE: 0.012381, R²: -0.0383
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.09758 | val 0.14310
  Epoch 020 - train 0.09703 | val 0.14457
  Regression -> MSE: 0.000248, MAE: 0.012581, R²: -0.0034
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.09412 | val 0.09273
  Epoch 020 - train 0.09222 | val 0.09272
  Regression -> MSE: 0.000696, MAE: 0.019543, R²: -0.0172
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.09839 | val 0.15469
  Epoch 020 - train 0.10115 | val 0.14904
  Regression -> MSE: 0.000364, MAE: 0.015488, R²: -0.1726
  Directional -> Accuracy: 0.4681, MCC: -0.0375, F1: 0.3243

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.08835 | val 0.17440
  Epoch 020 - train 0.08808 | val 0.16986
  Regression -> MSE: 0.000354, MAE: 0.014664, R²: -0.0147
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.09922 | val 0.10421
  Epoch 020 - train 0.09912 | val 0.12137
  Regression -> MSE: 0.000204, MAE: 0.010122, R²: -0.0008
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.09121 | val 0.17936
  Epoch 020 - train 0.09157 | val 0.18490
  Regression -> MSE: 0.000567, MAE: 0.018284, R²: -0.0206
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.10676 | val 0.14851
  Epoch 020 - train 0.10663 | val 0.14822
  Regression -> MSE: 0.000252, MAE: 0.012573, R²: -0.0258
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.09542 | val 0.13712
  Epoch 020 - train 0.09103 | val 0.17068
  Regression -> MSE: 0.000632, MAE: 0.019933, R²: -0.0585
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.09276 | val 0.12035
  Epoch 020 - train 0.09525 | val 0.12254
  Regression -> MSE: 0.000389, MAE: 0.016003, R²: -0.0128
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.09523 | val 0.14098
  Epoch 020 - train 0.09551 | val 0.15284
  Regression -> MSE: 0.000241, MAE: 0.011949, R²: -0.0000
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.08956 | val 0.13993
  Epoch 020 - train 0.08855 | val 0.13362
  Regression -> MSE: 0.000317, MAE: 0.013539, R²: -0.0185
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.10495 | val 0.12257
  Epoch 020 - train 0.10492 | val 0.12679
  Regression -> MSE: 0.000680, MAE: 0.019586, R²: -0.0037
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.09851 | val 0.09966
  Epoch 020 - train 0.09941 | val 0.10156
  Regression -> MSE: 0.000138, MAE: 0.009035, R²: 0.0008
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.09176 | val 0.13896
  Epoch 020 - train 0.09038 | val 0.14127
  Regression -> MSE: 0.000225, MAE: 0.010789, R²: -0.0020
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.09439 | val 0.19712
  Epoch 020 - train 0.09639 | val 0.20088
  Regression -> MSE: 0.000362, MAE: 0.016102, R²: -0.0001
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.10211 | val 0.10068
  Epoch 020 - train 0.10169 | val 0.10131
  Regression -> MSE: 0.000111, MAE: 0.007958, R²: -0.0309
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.09702 | val 0.15860
  Epoch 020 - train 0.09834 | val 0.15983
  Regression -> MSE: 0.000157, MAE: 0.009810, R²: -0.0080
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.09735 | val 0.09827
  Epoch 020 - train 0.09752 | val 0.09875
  Regression -> MSE: 0.000278, MAE: 0.013321, R²: -0.0203
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.09020 | val 0.13629
  Epoch 020 - train 0.08944 | val 0.13591
  Regression -> MSE: 0.000154, MAE: 0.008749, R²: -0.0308
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.10137 | val 0.14010
  Epoch 020 - train 0.09920 | val 0.13871
  Regression -> MSE: 0.000240, MAE: 0.011065, R²: -0.0600
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.10075 | val 0.11947
  Epoch 020 - train 0.09712 | val 0.12074
  Regression -> MSE: 0.000150, MAE: 0.008679, R²: -0.0443
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.09407 | val 0.11512
  Epoch 020 - train 0.09603 | val 0.11550
  Regression -> MSE: 0.000165, MAE: 0.010439, R²: -0.0001
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.10620 | val 0.11775
  Epoch 020 - train 0.10022 | val 0.11645
  Regression -> MSE: 0.000086, MAE: 0.007072, R²: -0.0070
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.09510 | val 0.12550
  Epoch 020 - train 0.09495 | val 0.13127
  Regression -> MSE: 0.000212, MAE: 0.011250, R²: -0.0006
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.08823 | val 0.08542
  Epoch 020 - train 0.08882 | val 0.08371
  Regression -> MSE: 0.000088, MAE: 0.007785, R²: 0.0462
  Directional -> Accuracy: 0.5536, MCC: 0.0373, F1: 0.6914

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.11252 | val 0.07726
  Epoch 020 - train 0.11035 | val 0.09165
  Regression -> MSE: 0.000103, MAE: 0.008663, R²: 0.0020
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.10337 | val 0.09449
  Epoch 020 - train 0.10182 | val 0.09336
  Regression -> MSE: 0.000243, MAE: 0.012912, R²: -0.0490
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.09800 | val 0.12222
  Epoch 020 - train 0.09652 | val 0.12551
  Regression -> MSE: 0.000178, MAE: 0.007934, R²: -0.0708
  Directional -> Accuracy: 0.4737, MCC: -0.0339, F1: 0.4643

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.09601 | val 0.08504
  Epoch 020 - train 0.10025 | val 0.08559
  Regression -> MSE: 0.000237, MAE: 0.011866, R²: -0.0007
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.10092 | val 0.15135
  Epoch 020 - train 0.10440 | val 0.15177
  Regression -> MSE: 0.000231, MAE: 0.009873, R²: -0.0018
  Directional -> Accuracy: 0.4884, MCC: -0.0261, F1: 0.4500

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.10002 | val 0.11279
  Epoch 020 - train 0.10508 | val 0.11126
  Regression -> MSE: 0.000135, MAE: 0.008179, R²: -0.0007
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.10120 | val 0.11953
  Epoch 020 - train 0.09711 | val 0.12062
  Regression -> MSE: 0.000201, MAE: 0.010739, R²: -0.0649
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.09675 | val 0.13167
  Epoch 020 - train 0.09738 | val 0.13179
  Regression -> MSE: 0.000262, MAE: 0.010580, R²: -0.0003
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.09640 | val 0.08310
  Epoch 020 - train 0.10307 | val 0.08709
  Regression -> MSE: 0.000168, MAE: 0.010365, R²: -0.0095
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.09379 | val 0.09790
  Epoch 020 - train 0.09391 | val 0.09773
  Regression -> MSE: 0.000180, MAE: 0.010265, R²: -0.0002
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.09728 | val 0.09338
  Epoch 020 - train 0.09520 | val 0.09373
  Regression -> MSE: 0.000343, MAE: 0.011903, R²: -0.0015
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.10877 | val 0.06428
  Epoch 020 - train 0.10942 | val 0.06462
  Regression -> MSE: 0.000119, MAE: 0.008329, R²: -0.1291
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.10617 | val 0.13356
  Epoch 020 - train 0.10591 | val 0.13530
  Regression -> MSE: 0.000219, MAE: 0.011270, R²: -0.0003
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.09888 | val 0.16478
  Epoch 020 - train 0.09755 | val 0.16862
  Regression -> MSE: 0.000095, MAE: 0.007621, R²: -0.2281
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.10648 | val 0.08640
  Epoch 020 - train 0.10105 | val 0.09748
  Regression -> MSE: 0.000337, MAE: 0.015256, R²: -0.0959
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.10676 | val 0.06182
  Epoch 020 - train 0.10703 | val 0.06710
  Regression -> MSE: 0.000245, MAE: 0.011561, R²: -0.0038
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.0000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.09403 | val 0.11819
  Epoch 020 - train 0.09572 | val 0.11779
  Regression -> MSE: 0.000082, MAE: 0.007123, R²: -0.0086
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.10007 | val 0.12632
  Epoch 020 - train 0.09970 | val 0.11719
  Regression -> MSE: 0.000327, MAE: 0.014829, R²: -0.0655
  Directional -> Accuracy: 0.4468, MCC: -0.1151, F1: 0.2353

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.09957 | val 0.11634
  Epoch 020 - train 0.10265 | val 0.11529
  Regression -> MSE: 0.000103, MAE: 0.007111, R²: -0.0448
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.10965 | val 0.11792
  Epoch 020 - train 0.10560 | val 0.12172
  Regression -> MSE: 0.000172, MAE: 0.009562, R²: 0.0005
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.09785 | val 0.13726
  Epoch 020 - train 0.09462 | val 0.15068
  Regression -> MSE: 0.000227, MAE: 0.011799, R²: -0.0180
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.09697 | val 0.11559
  Epoch 020 - train 0.09588 | val 0.11621
  Regression -> MSE: 0.000092, MAE: 0.007660, R²: -0.0006
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.10565 | val 0.14846
  Epoch 020 - train 0.10437 | val 0.14994
  Regression -> MSE: 0.000165, MAE: 0.010320, R²: -0.0073
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.09794 | val 0.12709
  Epoch 020 - train 0.09533 | val 0.13077
  Regression -> MSE: 0.000117, MAE: 0.008936, R²: -0.0115
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.10165 | val 0.13581

[I 2026-02-23 01:41:38,458] Trial 179 finished with value: -0.01146703384825486 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 32, 'learning_rate': 2.8470984860597574e-06, 'weight_decay': 3.8580824811019635e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.1423340055180575, 'early_stopping_min_delta': 0.00503977031964216}. Best is trial 157 with value: -0.011387287234516647.

  Epoch 020 - train 0.09745 | val 0.14057
  Regression -> MSE: 0.000238, MAE: 0.012379, R²: -0.0024
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.13203 | val 0.16747
  Epoch 020 - train 0.13044 | val 0.16759
  Regression -> MSE: 0.000271, MAE: 0.013375, R²: -0.0959
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.12321 | val 0.12552
  Epoch 020 - train 0.12399 | val 0.15454
  Regression -> MSE: 0.000719, MAE: 0.019944, R²: -0.0500
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.13320 | val 0.20342
  Epoch 020 - train 0.13203 | val 0.20613
  Regression -> MSE: 0.000353, MAE: 0.014955, R²: -0.1376
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.10842 | val 0.10766
  Epoch 020 - train 0.10712 | val 0.10817
  Regression -> MSE: 0.000350, MAE: 0.014584, R²: -0.0028
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.13760 | val 0.13269
  Epoch 020 - train 0.13361 | val 0.13726
  Regression -> MSE: 0.000204, MAE: 0.010054, R²: -0.0026
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.12495 | val 0.25430
  Epoch 020 - train 0.11747 | val 0.26442
  Regression -> MSE: 0.000612, MAE: 0.019250, R²: -0.1033
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.13501 | val 0.18062
  Epoch 020 - train 0.13771 | val 0.18270
  Regression -> MSE: 0.000253, MAE: 0.012006, R²: -0.0313
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.12559 | val 0.14946
  Epoch 020 - train 0.12910 | val 0.14194
  Regression -> MSE: 0.000605, MAE: 0.019238, R²: -0.0121
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.11894 | val 0.14846
  Epoch 020 - train 0.12800 | val 0.14943
  Regression -> MSE: 0.000400, MAE: 0.016051, R²: -0.0430
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.13792 | val 0.17424
  Epoch 020 - train 0.13223 | val 0.17250
  Regression -> MSE: 0.000242, MAE: 0.011755, R²: -0.0037
  Directional -> Accuracy: 0.4143, MCC: -0.1390, F1: 0.5859

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.11948 | val 0.17628
  Epoch 020 - train 0.11942 | val 0.17659
  Regression -> MSE: 0.000326, MAE: 0.013616, R²: -0.0491
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.13670 | val 0.16617
  Epoch 020 - train 0.13987 | val 0.17111
  Regression -> MSE: 0.000689, MAE: 0.019937, R²: -0.0178
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.12639 | val 0.12360
  Epoch 020 - train 0.12390 | val 0.12258
  Regression -> MSE: 0.000142, MAE: 0.009385, R²: -0.0289
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.12154 | val 0.18467
  Epoch 020 - train 0.12117 | val 0.18776
  Regression -> MSE: 0.000226, MAE: 0.010720, R²: -0.0055
  Directional -> Accuracy: 0.4918, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.12951 | val 0.26132
  Epoch 020 - train 0.13013 | val 0.26244
  Regression -> MSE: 0.000364, MAE: 0.016250, R²: -0.0044
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.13252 | val 0.14732
  Epoch 020 - train 0.12908 | val 0.14896
  Regression -> MSE: 0.000110, MAE: 0.008205, R²: -0.0218
  Directional -> Accuracy: 0.4571, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.12698 | val 0.19575
  Epoch 020 - train 0.12769 | val 0.19596
  Regression -> MSE: 0.000164, MAE: 0.010054, R²: -0.0497
  Directional -> Accuracy: 0.5254, MCC: -0.0542, F1: 0.6410

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.13257 | val 0.13482
  Epoch 020 - train 0.13117 | val 0.13539
  Regression -> MSE: 0.000281, MAE: 0.013492, R²: -0.0330
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.11919 | val 0.18193
  Epoch 020 - train 0.11627 | val 0.18368
  Regression -> MSE: 0.000160, MAE: 0.008923, R²: -0.0670
  Directional -> Accuracy: 0.5231, MCC: 0.1653, F1: 0.4151

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.12967 | val 0.17782
  Epoch 020 - train 0.13009 | val 0.17762
  Regression -> MSE: 0.000228, MAE: 0.010873, R²: -0.0070
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.12866 | val 0.15563
  Epoch 020 - train 0.12804 | val 0.15726
  Regression -> MSE: 0.000147, MAE: 0.008542, R²: -0.0230
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.12092 | val 0.14755
  Epoch 020 - train 0.11894 | val 0.14766
  Regression -> MSE: 0.000172, MAE: 0.010259, R²: -0.0410
  Directional -> Accuracy: 0.4697, MCC: -0.0609, F1: 0.4444

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.13071 | val 0.15842
  Epoch 020 - train 0.13229 | val 0.15889
  Regression -> MSE: 0.000086, MAE: 0.007124, R²: -0.0133
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.12596 | val 0.15887
  Epoch 020 - train 0.12772 | val 0.16078
  Regression -> MSE: 0.000213, MAE: 0.011063, R²: -0.0042
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.12287 | val 0.12050
  Epoch 020 - train 0.12078 | val 0.11798
  Regression -> MSE: 0.000098, MAE: 0.008196, R²: -0.0701
  Directional -> Accuracy: 0.3929, MCC: -0.2386, F1: 0.4688

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.12029 | val 0.10769
  Epoch 020 - train 0.12755 | val 0.10489
  Regression -> MSE: 0.000119, MAE: 0.009305, R²: -0.1527
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.13948 | val 0.13008
  Epoch 020 - train 0.13314 | val 0.15162
  Regression -> MSE: 0.000231, MAE: 0.012509, R²: 0.0001
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.12711 | val 0.15636
  Epoch 020 - train 0.12243 | val 0.15517
  Regression -> MSE: 0.000172, MAE: 0.007836, R²: -0.0349
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.14169 | val 0.10706
  Epoch 020 - train 0.13440 | val 0.10558
  Regression -> MSE: 0.000239, MAE: 0.011926, R²: -0.0093
  Directional -> Accuracy: 0.5122, MCC: -0.0202, F1: 0.6296

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.12827 | val 0.20119
  Epoch 020 - train 0.13192 | val 0.20152
  Regression -> MSE: 0.000231, MAE: 0.009925, R²: -0.0017
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.13204 | val 0.15858
  Epoch 020 - train 0.13042 | val 0.16081
  Regression -> MSE: 0.000138, MAE: 0.008316, R²: -0.0195
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.13395 | val 0.15699
  Epoch 020 - train 0.12906 | val 0.15806
  Regression -> MSE: 0.000195, MAE: 0.010506, R²: -0.0359
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.11638 | val 0.15797
  Epoch 020 - train 0.11589 | val 0.15732
  Regression -> MSE: 0.000265, MAE: 0.010507, R²: -0.0120
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.12364 | val 0.10975
  Epoch 020 - train 0.12322 | val 0.11696
  Regression -> MSE: 0.000166, MAE: 0.010362, R²: 0.0014
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.11913 | val 0.13871
  Epoch 020 - train 0.10972 | val 0.14266
  Regression -> MSE: 0.000180, MAE: 0.010287, R²: 0.0004
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.12682 | val 0.11827
  Epoch 020 - train 0.12541 | val 0.11760
  Regression -> MSE: 0.000343, MAE: 0.011731, R²: -0.0010
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.13670 | val 0.08166
  Epoch 020 - train 0.13471 | val 0.09424
  Regression -> MSE: 0.000126, MAE: 0.008489, R²: -0.2028
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.14445 | val 0.16999
  Epoch 020 - train 0.14580 | val 0.17076
  Regression -> MSE: 0.000218, MAE: 0.011239, R²: 0.0016
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.12522 | val 0.21367
  Epoch 020 - train 0.12371 | val 0.21578
  Regression -> MSE: 0.000087, MAE: 0.007307, R²: -0.1224
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.12152 | val 0.10102
  Epoch 020 - train 0.12487 | val 0.09688
  Regression -> MSE: 0.000322, MAE: 0.014611, R²: -0.0458
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.13816 | val 0.08455
  Epoch 020 - train 0.13978 | val 0.08739
  Regression -> MSE: 0.000260, MAE: 0.011493, R²: -0.0661
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.12780 | val 0.15737
  Epoch 020 - train 0.12553 | val 0.15734
  Regression -> MSE: 0.000081, MAE: 0.007069, R²: -0.0062
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.12882 | val 0.15625
  Epoch 020 - train 0.12725 | val 0.15889
  Regression -> MSE: 0.000307, MAE: 0.014489, R²: -0.0010
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.12911 | val 0.15655
  Epoch 020 - train 0.13212 | val 0.15348
  Regression -> MSE: 0.000105, MAE: 0.007125, R²: -0.0692
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.13766 | val 0.15315
  Epoch 020 - train 0.13626 | val 0.15627
  Regression -> MSE: 0.000177, MAE: 0.010309, R²: -0.0311
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.12196 | val 0.14724
  Epoch 020 - train 0.11829 | val 0.14824
  Regression -> MSE: 0.000224, MAE: 0.011775, R²: -0.0031
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.12859 | val 0.14436
  Epoch 020 - train 0.12739 | val 0.14524
  Regression -> MSE: 0.000093, MAE: 0.007672, R²: -0.0047
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.13358 | val 0.19558
  Epoch 020 - train 0.13505 | val 0.19690
  Regression -> MSE: 0.000164, MAE: 0.010275, R²: -0.0009
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.12529 | val 0.15394
  Epoch 020 - train 0.12603 | val 0.15576
  Regression -> MSE: 0.000116, MAE: 0.008913, R²: -0.0029
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.12836 | val 0.17714

[I 2026-02-23 01:43:27,377] Trial 180 finished with value: -0.011483080431958176 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 32, 'learning_rate': 1.5176181472050624e-06, 'weight_decay': 6.48639690639438e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.19063115835998773, 'early_stopping_min_delta': 0.005732104865214025}. Best is trial 157 with value: -0.011387287234516647.

  Epoch 020 - train 0.12892 | val 0.17879
  Regression -> MSE: 0.000240, MAE: 0.012330, R²: -0.0121
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.10460 | val 0.13923
  Epoch 020 - train 0.10544 | val 0.13910
  Regression -> MSE: 0.000247, MAE: 0.012500, R²: 0.0011
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.10484 | val 0.09871
  Epoch 020 - train 0.10171 | val 0.09750
  Regression -> MSE: 0.000701, MAE: 0.019624, R²: -0.0234
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.11129 | val 0.17317
  Epoch 020 - train 0.11160 | val 0.17340
  Regression -> MSE: 0.000310, MAE: 0.014392, R²: 0.0008
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.09557 | val 0.09005
  Epoch 020 - train 0.09022 | val 0.09211
  Regression -> MSE: 0.000350, MAE: 0.014581, R²: -0.0006
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.10739 | val 0.10253
  Epoch 020 - train 0.10942 | val 0.10262
  Regression -> MSE: 0.000208, MAE: 0.010242, R²: -0.0220
  Directional -> Accuracy: 0.5098, MCC: 0.0280, F1: 0.4898

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.10569 | val 0.19990
  Epoch 020 - train 0.10223 | val 0.20157
  Regression -> MSE: 0.000604, MAE: 0.019133, R²: -0.0886
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.10985 | val 0.13571
  Epoch 020 - train 0.11056 | val 0.13518
  Regression -> MSE: 0.000246, MAE: 0.011921, R²: -0.0015
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.11297 | val 0.15869
  Epoch 020 - train 0.10727 | val 0.17350
  Regression -> MSE: 0.000665, MAE: 0.020484, R²: -0.1135
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.10530 | val 0.13086
  Epoch 020 - train 0.10155 | val 0.13337
  Regression -> MSE: 0.000391, MAE: 0.015938, R²: -0.0202
  Directional -> Accuracy: 0.5918, MCC: 0.1633, F1: 0.5000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.11028 | val 0.14233
  Epoch 020 - train 0.10818 | val 0.14404
  Regression -> MSE: 0.000247, MAE: 0.011624, R²: -0.0236
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.10238 | val 0.15125
  Epoch 020 - train 0.10166 | val 0.14898
  Regression -> MSE: 0.000334, MAE: 0.013844, R²: -0.0758
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.11423 | val 0.12827
  Epoch 020 - train 0.11281 | val 0.12889
  Regression -> MSE: 0.000680, MAE: 0.019513, R²: -0.0042
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.10828 | val 0.11070
  Epoch 020 - train 0.10709 | val 0.11444
  Regression -> MSE: 0.000139, MAE: 0.009205, R²: -0.0067
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.10066 | val 0.14519
  Epoch 020 - train 0.10054 | val 0.14635
  Regression -> MSE: 0.000226, MAE: 0.010744, R²: -0.0028
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.11058 | val 0.20843
  Epoch 020 - train 0.10619 | val 0.20627
  Regression -> MSE: 0.000363, MAE: 0.016138, R²: -0.0028
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.11036 | val 0.11154
  Epoch 020 - train 0.11398 | val 0.11218
  Regression -> MSE: 0.000108, MAE: 0.008058, R²: -0.0018
  Directional -> Accuracy: 0.4571, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.10122 | val 0.19066
  Epoch 020 - train 0.10567 | val 0.20089
  Regression -> MSE: 0.000156, MAE: 0.009681, R²: -0.0009
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.10755 | val 0.10988
  Epoch 020 - train 0.10921 | val 0.10956
  Regression -> MSE: 0.000273, MAE: 0.013116, R²: -0.0045
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.10023 | val 0.15057
  Epoch 020 - train 0.09903 | val 0.15247
  Regression -> MSE: 0.000163, MAE: 0.009019, R²: -0.0926
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.11027 | val 0.15607
  Epoch 020 - train 0.11050 | val 0.15331
  Regression -> MSE: 0.000232, MAE: 0.010966, R²: -0.0252
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.11370 | val 0.13378
  Epoch 020 - train 0.11369 | val 0.13704
  Regression -> MSE: 0.000152, MAE: 0.008753, R²: -0.0572
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.10500 | val 0.12878
  Epoch 020 - train 0.10288 | val 0.12901
  Regression -> MSE: 0.000167, MAE: 0.010354, R²: -0.0125
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.12063 | val 0.14859
  Epoch 020 - train 0.12331 | val 0.15584
  Regression -> MSE: 0.000096, MAE: 0.007565, R²: -0.1308
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.11686 | val 0.16084
  Epoch 020 - train 0.11461 | val 0.17573
  Regression -> MSE: 0.000216, MAE: 0.011033, R²: -0.0194
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.10119 | val 0.09856
  Epoch 020 - train 0.10316 | val 0.09647
  Regression -> MSE: 0.000101, MAE: 0.008224, R²: -0.0939
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.10564 | val 0.08487
  Epoch 020 - train 0.10669 | val 0.08625
  Regression -> MSE: 0.000105, MAE: 0.008833, R²: -0.0167
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.11024 | val 0.10254
  Epoch 020 - train 0.10833 | val 0.10442
  Regression -> MSE: 0.000236, MAE: 0.012719, R²: -0.0202
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.10746 | val 0.12629
  Epoch 020 - train 0.10814 | val 0.12495
  Regression -> MSE: 0.000186, MAE: 0.008079, R²: -0.1160
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.11027 | val 0.09187
  Epoch 020 - train 0.10428 | val 0.09262
  Regression -> MSE: 0.000238, MAE: 0.011903, R²: -0.0044
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.10422 | val 0.16668
  Epoch 020 - train 0.10715 | val 0.16623
  Regression -> MSE: 0.000230, MAE: 0.009869, R²: 0.0009
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.11591 | val 0.12354
  Epoch 020 - train 0.11361 | val 0.13185
  Regression -> MSE: 0.000135, MAE: 0.008173, R²: -0.0010
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.10620 | val 0.13564
  Epoch 020 - train 0.10518 | val 0.13606
  Regression -> MSE: 0.000191, MAE: 0.010373, R²: -0.0126
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.09761 | val 0.12264
  Epoch 020 - train 0.09775 | val 0.12263
  Regression -> MSE: 0.000272, MAE: 0.010686, R²: -0.0398
  Directional -> Accuracy: 0.4384, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.10121 | val 0.09299
  Epoch 020 - train 0.09992 | val 0.09476
  Regression -> MSE: 0.000167, MAE: 0.010368, R²: -0.0016
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.09668 | val 0.10987
  Epoch 020 - train 0.10011 | val 0.11677
  Regression -> MSE: 0.000180, MAE: 0.010312, R²: -0.0013
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.10363 | val 0.10520
  Epoch 020 - train 0.10418 | val 0.10490
  Regression -> MSE: 0.000344, MAE: 0.011865, R²: -0.0052
  Directional -> Accuracy: 0.4478, MCC: -0.0284, F1: 0.2745

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.11401 | val 0.07216
  Epoch 020 - train 0.11728 | val 0.07032
  Regression -> MSE: 0.000128, MAE: 0.008511, R²: -0.2131
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.11288 | val 0.14574
  Epoch 020 - train 0.11388 | val 0.15070
  Regression -> MSE: 0.000217, MAE: 0.010942, R²: 0.0074
  Directional -> Accuracy: 0.5965, MCC: 0.1860, F1: 0.5106

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.11874 | val 0.19151
  Epoch 020 - train 0.11433 | val 0.20036
  Regression -> MSE: 0.000083, MAE: 0.007086, R²: -0.0636
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.10333 | val 0.09043
  Epoch 020 - train 0.10350 | val 0.09083
  Regression -> MSE: 0.000329, MAE: 0.014957, R²: -0.0702
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.11412 | val 0.06983
  Epoch 020 - train 0.11459 | val 0.06884
  Regression -> MSE: 0.000258, MAE: 0.011476, R²: -0.0567
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.10430 | val 0.12944
  Epoch 020 - train 0.10364 | val 0.12919
  Regression -> MSE: 0.000083, MAE: 0.007057, R²: -0.0214
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.11431 | val 0.13530
  Epoch 020 - train 0.11003 | val 0.13662
  Regression -> MSE: 0.000307, MAE: 0.014495, R²: -0.0005
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.11505 | val 0.11464
  Epoch 020 - train 0.10839 | val 0.11295
  Regression -> MSE: 0.000098, MAE: 0.007283, R²: -0.0014
  Directional -> Accuracy: 0.3636, MCC: -0.2404, F1: 0.1765

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.11260 | val 0.12804
  Epoch 020 - train 0.11517 | val 0.14147
  Regression -> MSE: 0.000172, MAE: 0.009758, R²: -0.0020
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.10215 | val 0.12127
  Epoch 020 - train 0.10211 | val 0.12333
  Regression -> MSE: 0.000224, MAE: 0.011790, R²: -0.0032
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.10260 | val 0.12974
  Epoch 020 - train 0.10175 | val 0.13435
  Regression -> MSE: 0.000097, MAE: 0.007976, R²: -0.0544
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.11465 | val 0.16290
  Epoch 020 - train 0.10868 | val 0.16350
  Regression -> MSE: 0.000164, MAE: 0.010257, R²: -0.0006
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.10440 | val 0.13246
  Epoch 020 - train 0.10539 | val 0.13236
  Regression -> MSE: 0.000122, MAE: 0.008993, R²: -0.0491
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.10826 | val 0.14725

[I 2026-02-23 01:46:08,370] Trial 181 finished with value: -0.01145541883433228 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 32, 'learning_rate': 3.2020462402611907e-06, 'weight_decay': 0.00010051901327425715, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.1584601166534444, 'early_stopping_min_delta': 0.005417268907348043}. Best is trial 157 with value: -0.011387287234516647.

  Epoch 020 - train 0.10811 | val 0.14584
  Regression -> MSE: 0.000245, MAE: 0.012359, R²: -0.0316
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.14710 | val 0.22267
  Epoch 020 - train 0.14581 | val 0.22339
  Regression -> MSE: 0.000269, MAE: 0.013233, R²: -0.0866
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.14411 | val 0.14725
  Epoch 020 - train 0.14219 | val 0.15703
  Regression -> MSE: 0.000696, MAE: 0.019556, R²: -0.0172
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.14662 | val 0.23964
  Epoch 020 - train 0.15039 | val 0.25538
  Regression -> MSE: 0.000310, MAE: 0.014422, R²: 0.0018
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.12927 | val 0.14244
  Epoch 020 - train 0.12846 | val 0.13727
  Regression -> MSE: 0.000351, MAE: 0.014574, R²: -0.0054
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.14344 | val 0.13976
  Epoch 020 - train 0.13956 | val 0.13407
  Regression -> MSE: 0.000219, MAE: 0.010646, R²: -0.0765
  Directional -> Accuracy: 0.4118, MCC: -0.1757, F1: 0.4231

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.13704 | val 0.27084
  Epoch 020 - train 0.13534 | val 0.27190
  Regression -> MSE: 0.000565, MAE: 0.018246, R²: -0.0175
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.14241 | val 0.18285
  Epoch 020 - train 0.14755 | val 0.18222
  Regression -> MSE: 0.000246, MAE: 0.011938, R²: -0.0026
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.15120 | val 0.16830
  Epoch 020 - train 0.14874 | val 0.15172
  Regression -> MSE: 0.000605, MAE: 0.019074, R²: -0.0126
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.13747 | val 0.17247
  Epoch 020 - train 0.13616 | val 0.17493
  Regression -> MSE: 0.000400, MAE: 0.016058, R²: -0.0435
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.14297 | val 0.19441
  Epoch 020 - train 0.13816 | val 0.19499
  Regression -> MSE: 0.000242, MAE: 0.011790, R²: -0.0014
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.13775 | val 0.20500
  Epoch 020 - train 0.13430 | val 0.21359
  Regression -> MSE: 0.000323, MAE: 0.013600, R²: -0.0374
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.14679 | val 0.17525
  Epoch 020 - train 0.14711 | val 0.18588
  Regression -> MSE: 0.000676, MAE: 0.019455, R²: 0.0022
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.14420 | val 0.14257
  Epoch 020 - train 0.13646 | val 0.13946
  Regression -> MSE: 0.000141, MAE: 0.009336, R²: -0.0212
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.13917 | val 0.18676
  Epoch 020 - train 0.13439 | val 0.18742
  Regression -> MSE: 0.000230, MAE: 0.010888, R²: -0.0228
  Directional -> Accuracy: 0.4918, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.15269 | val 0.29289
  Epoch 020 - train 0.14904 | val 0.29917
  Regression -> MSE: 0.000362, MAE: 0.016125, R²: 0.0000
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.14764 | val 0.16218
  Epoch 020 - train 0.14530 | val 0.16235
  Regression -> MSE: 0.000108, MAE: 0.008088, R²: -0.0054
  Directional -> Accuracy: 0.4571, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.15197 | val 0.29734
  Epoch 020 - train 0.15372 | val 0.34696
  Regression -> MSE: 0.000157, MAE: 0.009533, R²: -0.0099
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.15124 | val 0.23751
  Epoch 020 - train 0.15211 | val 0.25531
  Regression -> MSE: 0.000275, MAE: 0.013182, R²: -0.0106
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.13766 | val 0.19268
  Epoch 020 - train 0.13156 | val 0.19311
  Regression -> MSE: 0.000157, MAE: 0.008819, R²: -0.0482
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.16034 | val 0.23231
  Epoch 020 - train 0.15122 | val 0.22283
  Regression -> MSE: 0.000232, MAE: 0.010908, R²: -0.0252
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.14750 | val 0.17840
  Epoch 020 - train 0.14655 | val 0.18634
  Regression -> MSE: 0.000143, MAE: 0.008310, R²: -0.0004
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.13800 | val 0.17634
  Epoch 020 - train 0.14058 | val 0.17883
  Regression -> MSE: 0.000166, MAE: 0.010499, R²: -0.0048
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.15210 | val 0.18050
  Epoch 020 - train 0.15299 | val 0.18013
  Regression -> MSE: 0.000091, MAE: 0.007338, R²: -0.0651
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.14454 | val 0.18158
  Epoch 020 - train 0.13979 | val 0.18295
  Regression -> MSE: 0.000212, MAE: 0.011145, R²: -0.0006
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.13040 | val 0.12492
  Epoch 020 - train 0.13437 | val 0.12525
  Regression -> MSE: 0.000095, MAE: 0.007930, R²: -0.0281
  Directional -> Accuracy: 0.5893, MCC: 0.1659, F1: 0.6349

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.14883 | val 0.11914
  Epoch 020 - train 0.15335 | val 0.11224
  Regression -> MSE: 0.000108, MAE: 0.009006, R²: -0.0505
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.14877 | val 0.14310
  Epoch 020 - train 0.14266 | val 0.15579
  Regression -> MSE: 0.000242, MAE: 0.012901, R²: -0.0475
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.13825 | val 0.18272
  Epoch 020 - train 0.13866 | val 0.19128
  Regression -> MSE: 0.000184, MAE: 0.008034, R²: -0.1027
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.15491 | val 0.12270
  Epoch 020 - train 0.14438 | val 0.13317
  Regression -> MSE: 0.000237, MAE: 0.011885, R²: -0.0035
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.14175 | val 0.22891
  Epoch 020 - train 0.14539 | val 0.23311
  Regression -> MSE: 0.000231, MAE: 0.009872, R²: -0.0013
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.14782 | val 0.17334
  Epoch 020 - train 0.14880 | val 0.17958
  Regression -> MSE: 0.000135, MAE: 0.008206, R²: -0.0022
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.14832 | val 0.18562
  Epoch 020 - train 0.14374 | val 0.18669
  Regression -> MSE: 0.000192, MAE: 0.010395, R²: -0.0183
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.13616 | val 0.20308
  Epoch 020 - train 0.12974 | val 0.20138
  Regression -> MSE: 0.000269, MAE: 0.010604, R²: -0.0268
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.13496 | val 0.12456
  Epoch 020 - train 0.13764 | val 0.12728
  Regression -> MSE: 0.000167, MAE: 0.010377, R²: -0.0046
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.13798 | val 0.14949
  Epoch 020 - train 0.13486 | val 0.16017
  Regression -> MSE: 0.000182, MAE: 0.010382, R²: -0.0090
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.13768 | val 0.13593
  Epoch 020 - train 0.13616 | val 0.13504
  Regression -> MSE: 0.000354, MAE: 0.012609, R²: -0.0318
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.16395 | val 0.09781
  Epoch 020 - train 0.16238 | val 0.11103
  Regression -> MSE: 0.000112, MAE: 0.008334, R²: -0.0666
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.16011 | val 0.20624
  Epoch 020 - train 0.15650 | val 0.20488
  Regression -> MSE: 0.000227, MAE: 0.011553, R²: -0.0406
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.13679 | val 0.26215
  Epoch 020 - train 0.14354 | val 0.27613
  Regression -> MSE: 0.000087, MAE: 0.007290, R²: -0.1186
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.14079 | val 0.11236
  Epoch 020 - train 0.14379 | val 0.11508
  Regression -> MSE: 0.000316, MAE: 0.014285, R²: -0.0274
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.15046 | val 0.09290
  Epoch 020 - train 0.15253 | val 0.09209
  Regression -> MSE: 0.000256, MAE: 0.011456, R²: -0.0487
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.14328 | val 0.17555
  Epoch 020 - train 0.13701 | val 0.17479
  Regression -> MSE: 0.000085, MAE: 0.007061, R²: -0.0580
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.15085 | val 0.17618
  Epoch 020 - train 0.14043 | val 0.18166
  Regression -> MSE: 0.000308, MAE: 0.014509, R²: -0.0026
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.14382 | val 0.15912
  Epoch 020 - train 0.14343 | val 0.15754
  Regression -> MSE: 0.000099, MAE: 0.007213, R²: -0.0056
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.16089 | val 0.17228
  Epoch 020 - train 0.15457 | val 0.17003
  Regression -> MSE: 0.000175, MAE: 0.010210, R²: -0.0212
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.13441 | val 0.16872
  Epoch 020 - train 0.13466 | val 0.17114
  Regression -> MSE: 0.000224, MAE: 0.011772, R²: -0.0033
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.14103 | val 0.15693
  Epoch 020 - train 0.13770 | val 0.15728
  Regression -> MSE: 0.000094, MAE: 0.007740, R²: -0.0178
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.15008 | val 0.23285
  Epoch 020 - train 0.14974 | val 0.23259
  Regression -> MSE: 0.000166, MAE: 0.010296, R²: -0.0127
  Directional -> Accuracy: 0.4815, MCC: 0.0000, F1: 0.0000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.14296 | val 0.17347
  Epoch 020 - train 0.14033 | val 0.17584
  Regression -> MSE: 0.000126, MAE: 0.009044, R²: -0.0877
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.14822 | val 0.19887

[I 2026-02-23 01:48:51,162] Trial 182 finished with value: -0.011441436057688143 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 32, 'learning_rate': 4.770060885825507e-06, 'weight_decay': 2.984608720578814e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.22174693323395206, 'early_stopping_min_delta': 0.005832111832572022}. Best is trial 157 with value: -0.011387287234516647.

  Epoch 020 - train 0.14546 | val 0.19758
  Regression -> MSE: 0.000243, MAE: 0.012345, R²: -0.0248
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.17971 | val 0.28765
  Epoch 020 - train 0.17548 | val 0.29284
  Regression -> MSE: 0.000250, MAE: 0.012671, R²: -0.0114
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.17347 | val 0.16228
  Epoch 020 - train 0.17427 | val 0.17325
  Regression -> MSE: 0.000689, MAE: 0.019434, R²: -0.0070
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.19336 | val 0.31009
  Epoch 020 - train 0.18918 | val 0.32828
  Regression -> MSE: 0.000327, MAE: 0.014583, R²: -0.0542
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.15501 | val 0.22581
  Epoch 020 - train 0.15261 | val 0.19466
  Regression -> MSE: 0.000357, MAE: 0.014726, R²: -0.0228
  Directional -> Accuracy: 0.4800, MCC: -0.1504, F1: 0.6286

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.17804 | val 0.17373
  Epoch 020 - train 0.17651 | val 0.17179
  Regression -> MSE: 0.000213, MAE: 0.010632, R²: -0.0453
  Directional -> Accuracy: 0.4314, MCC: -0.1502, F1: 0.4912

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.16516 | val 0.34092
  Epoch 020 - train 0.16665 | val 0.34057
  Regression -> MSE: 0.000564, MAE: 0.018250, R²: -0.0161
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.18064 | val 0.21542
  Epoch 020 - train 0.17792 | val 0.21220
  Regression -> MSE: 0.000247, MAE: 0.012069, R²: -0.0069
  Directional -> Accuracy: 0.4928, MCC: 0.0726, F1: 0.5455

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.19438 | val 0.22570
  Epoch 020 - train 0.19120 | val 0.23204
  Regression -> MSE: 0.000617, MAE: 0.019636, R²: -0.0322
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.16800 | val 0.22207
  Epoch 020 - train 0.16662 | val 0.22656
  Regression -> MSE: 0.000387, MAE: 0.015998, R²: -0.0089
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.17888 | val 0.24786
  Epoch 020 - train 0.17758 | val 0.25731
  Regression -> MSE: 0.000242, MAE: 0.011873, R²: -0.0003
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.16537 | val 0.27949
  Epoch 020 - train 0.16054 | val 0.30984
  Regression -> MSE: 0.000311, MAE: 0.013677, R²: -0.0007
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.6301

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.19523 | val 0.22262
  Epoch 020 - train 0.19024 | val 0.23847
  Regression -> MSE: 0.000686, MAE: 0.019811, R²: -0.0130
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.17852 | val 0.17625
  Epoch 020 - train 0.17411 | val 0.18926
  Regression -> MSE: 0.000144, MAE: 0.009480, R²: -0.0431
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.16197 | val 0.24131
  Epoch 020 - train 0.16313 | val 0.25854
  Regression -> MSE: 0.000227, MAE: 0.010751, R²: -0.0103
  Directional -> Accuracy: 0.4918, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.17748 | val 0.37242
  Epoch 020 - train 0.17311 | val 0.37330
  Regression -> MSE: 0.000363, MAE: 0.016059, R²: -0.0015
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.18208 | val 0.18383
  Epoch 020 - train 0.18090 | val 0.18006
  Regression -> MSE: 0.000108, MAE: 0.008241, R²: -0.0047
  Directional -> Accuracy: 0.4714, MCC: 0.0191, F1: 0.1778

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.17374 | val 0.30524
  Epoch 020 - train 0.17019 | val 0.30952
  Regression -> MSE: 0.000158, MAE: 0.009576, R²: -0.0111
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.18175 | val 0.18175
  Epoch 020 - train 0.17546 | val 0.18239
  Regression -> MSE: 0.000272, MAE: 0.012974, R²: -0.0003
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.17121 | val 0.24075
  Epoch 020 - train 0.16508 | val 0.23816
  Regression -> MSE: 0.000165, MAE: 0.009046, R²: -0.1033
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.19327 | val 0.31015
  Epoch 020 - train 0.18607 | val 0.29717
  Regression -> MSE: 0.000227, MAE: 0.010957, R²: -0.0015
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.18649 | val 0.25760
  Epoch 020 - train 0.18564 | val 0.29830
  Regression -> MSE: 0.000144, MAE: 0.008310, R²: -0.0021
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.16976 | val 0.20336
  Epoch 020 - train 0.16434 | val 0.20446
  Regression -> MSE: 0.000167, MAE: 0.010334, R²: -0.0120
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.4923

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.19005 | val 0.23153
  Epoch 020 - train 0.19242 | val 0.23289
  Regression -> MSE: 0.000091, MAE: 0.007340, R²: -0.0637
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.17769 | val 0.21975
  Epoch 020 - train 0.16884 | val 0.22059
  Regression -> MSE: 0.000212, MAE: 0.011195, R²: -0.0005
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.16485 | val 0.16933
  Epoch 020 - train 0.16355 | val 0.16640
  Regression -> MSE: 0.000092, MAE: 0.008105, R²: -0.0032
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.18633 | val 0.13760
  Epoch 020 - train 0.18253 | val 0.13953
  Regression -> MSE: 0.000106, MAE: 0.008874, R²: -0.0246
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.19346 | val 0.17349
  Epoch 020 - train 0.19411 | val 0.18288
  Regression -> MSE: 0.000238, MAE: 0.012795, R²: -0.0300
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.17620 | val 0.21462
  Epoch 020 - train 0.16978 | val 0.21493
  Regression -> MSE: 0.000176, MAE: 0.007879, R²: -0.0566
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.17999 | val 0.15385
  Epoch 020 - train 0.18081 | val 0.15117
  Regression -> MSE: 0.000238, MAE: 0.011887, R²: -0.0047
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.17071 | val 0.29431
  Epoch 020 - train 0.16952 | val 0.29574
  Regression -> MSE: 0.000234, MAE: 0.010117, R²: -0.0165
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.18276 | val 0.21821
  Epoch 020 - train 0.17892 | val 0.23183
  Regression -> MSE: 0.000137, MAE: 0.008272, R²: -0.0152
  Directional -> Accuracy: 0.5581, MCC: 0.1297, F1: 0.5366

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.17635 | val 0.22885
  Epoch 020 - train 0.17472 | val 0.23412
  Regression -> MSE: 0.000194, MAE: 0.010460, R²: -0.0284
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.15825 | val 0.22271
  Epoch 020 - train 0.15874 | val 0.22163
  Regression -> MSE: 0.000267, MAE: 0.010547, R²: -0.0199
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.18142 | val 0.14806
  Epoch 020 - train 0.17713 | val 0.15823
  Regression -> MSE: 0.000169, MAE: 0.010356, R²: -0.0112
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.16479 | val 0.18749
  Epoch 020 - train 0.16185 | val 0.20542
  Regression -> MSE: 0.000182, MAE: 0.010411, R²: -0.0133
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.15841 | val 0.16719
  Epoch 020 - train 0.15977 | val 0.16962
  Regression -> MSE: 0.000342, MAE: 0.011897, R²: 0.0008
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.19271 | val 0.11346
  Epoch 020 - train 0.18585 | val 0.11294
  Regression -> MSE: 0.000124, MAE: 0.008437, R²: -0.1759
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.19004 | val 0.24469
  Epoch 020 - train 0.18731 | val 0.24283
  Regression -> MSE: 0.000219, MAE: 0.011327, R²: -0.0037
  Directional -> Accuracy: 0.5789, MCC: 0.2822, F1: 0.6842

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.19606 | val 0.31002
  Epoch 020 - train 0.19385 | val 0.31648
  Regression -> MSE: 0.000097, MAE: 0.007668, R²: -0.2446
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.16872 | val 0.14968
  Epoch 020 - train 0.17282 | val 0.15263
  Regression -> MSE: 0.000335, MAE: 0.015197, R²: -0.0898
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.20263 | val 0.10533
  Epoch 020 - train 0.19664 | val 0.10892
  Regression -> MSE: 0.000245, MAE: 0.011559, R²: -0.0041
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.0000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.17045 | val 0.21773
  Epoch 020 - train 0.16984 | val 0.21710
  Regression -> MSE: 0.000081, MAE: 0.007091, R²: -0.0012
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.17917 | val 0.22074
  Epoch 020 - train 0.17631 | val 0.22279
  Regression -> MSE: 0.000306, MAE: 0.014484, R²: 0.0011
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.18708 | val 0.21048
  Epoch 020 - train 0.18302 | val 0.19624
  Regression -> MSE: 0.000108, MAE: 0.007217, R²: -0.0992
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.20383 | val 0.21938
  Epoch 020 - train 0.20239 | val 0.24613
  Regression -> MSE: 0.000172, MAE: 0.009665, R²: -0.0009
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.17700 | val 0.20047
  Epoch 020 - train 0.17733 | val 0.20488
  Regression -> MSE: 0.000226, MAE: 0.011820, R²: -0.0126
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.18844 | val 0.19461
  Epoch 020 - train 0.18856 | val 0.19475
  Regression -> MSE: 0.000093, MAE: 0.007655, R²: -0.0103
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.18842 | val 0.27743
  Epoch 020 - train 0.18591 | val 0.27960
  Regression -> MSE: 0.000164, MAE: 0.010245, R²: -0.0001
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.18490 | val 0.23080
  Epoch 020 - train 0.17915 | val 0.23653
  Regression -> MSE: 0.000118, MAE: 0.008954, R²: -0.0148
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.18117 | val 0.25329

[I 2026-02-23 01:51:33,667] Trial 183 finished with value: -0.011457602650165051 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 32, 'learning_rate': 4.612020760190532e-06, 'weight_decay': 3.086496568210939e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.28417386804817124, 'early_stopping_min_delta': 0.005749931573827065}. Best is trial 157 with value: -0.011387287234516647.

  Epoch 020 - train 0.17897 | val 0.25938
  Regression -> MSE: 0.000240, MAE: 0.012337, R²: -0.0112
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.13645 | val 0.17868
  Epoch 020 - train 0.13389 | val 0.17785
  Regression -> MSE: 0.000264, MAE: 0.013117, R²: -0.0672
  Directional -> Accuracy: 0.4286, MCC: -0.1136, F1: 0.5217

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.13690 | val 0.13290
  Epoch 020 - train 0.13914 | val 0.15269
  Regression -> MSE: 0.000711, MAE: 0.019816, R²: -0.0387
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.14674 | val 0.22764
  Epoch 020 - train 0.14017 | val 0.22417
  Regression -> MSE: 0.000319, MAE: 0.014507, R²: -0.0286
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.11847 | val 0.12789
  Epoch 020 - train 0.11468 | val 0.13885
  Regression -> MSE: 0.000349, MAE: 0.014575, R²: 0.0002
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.14092 | val 0.14428
  Epoch 020 - train 0.13474 | val 0.14756
  Regression -> MSE: 0.000204, MAE: 0.010083, R²: -0.0006
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.13389 | val 0.26300
  Epoch 020 - train 0.12828 | val 0.27220
  Regression -> MSE: 0.000576, MAE: 0.018496, R²: -0.0375
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.13769 | val 0.16956
  Epoch 020 - train 0.13649 | val 0.16955
  Regression -> MSE: 0.000249, MAE: 0.011938, R²: -0.0152
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.13869 | val 0.17029
  Epoch 020 - train 0.14038 | val 0.18302
  Regression -> MSE: 0.000607, MAE: 0.019406, R²: -0.0167
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.12888 | val 0.17379
  Epoch 020 - train 0.13157 | val 0.17004
  Regression -> MSE: 0.000396, MAE: 0.016093, R²: -0.0327
  Directional -> Accuracy: 0.5714, MCC: 0.1126, F1: 0.4324

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.15315 | val 0.19070
  Epoch 020 - train 0.14580 | val 0.19141
  Regression -> MSE: 0.000245, MAE: 0.011656, R²: -0.0145
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.13967 | val 0.19739
  Epoch 020 - train 0.13246 | val 0.20496
  Regression -> MSE: 0.000324, MAE: 0.013605, R²: -0.0433
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.13913 | val 0.16376
  Epoch 020 - train 0.14423 | val 0.16701
  Regression -> MSE: 0.000677, MAE: 0.019496, R²: -0.0000
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.14293 | val 0.13893
  Epoch 020 - train 0.13973 | val 0.15078
  Regression -> MSE: 0.000140, MAE: 0.009263, R²: -0.0105
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.12877 | val 0.17986
  Epoch 020 - train 0.12892 | val 0.17959
  Regression -> MSE: 0.000230, MAE: 0.010861, R²: -0.0227
  Directional -> Accuracy: 0.4918, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.13490 | val 0.28188
  Epoch 020 - train 0.13291 | val 0.28387
  Regression -> MSE: 0.000370, MAE: 0.015933, R²: -0.0215
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.14548 | val 0.15098
  Epoch 020 - train 0.14263 | val 0.15158
  Regression -> MSE: 0.000109, MAE: 0.008132, R²: -0.0099
  Directional -> Accuracy: 0.4571, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.13222 | val 0.23035
  Epoch 020 - train 0.13426 | val 0.23064
  Regression -> MSE: 0.000157, MAE: 0.009713, R²: -0.0054
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.14071 | val 0.15531
  Epoch 020 - train 0.14231 | val 0.15327
  Regression -> MSE: 0.000284, MAE: 0.013588, R²: -0.0439
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.12805 | val 0.21297
  Epoch 020 - train 0.12710 | val 0.21033
  Regression -> MSE: 0.000155, MAE: 0.008768, R²: -0.0355
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.13651 | val 0.19881
  Epoch 020 - train 0.14020 | val 0.19615
  Regression -> MSE: 0.000234, MAE: 0.010952, R²: -0.0344
  Directional -> Accuracy: 0.4533, MCC: -0.1503, F1: 0.5684

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.14352 | val 0.17119
  Epoch 020 - train 0.13359 | val 0.17583
  Regression -> MSE: 0.000144, MAE: 0.008340, R²: -0.0020
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.12955 | val 0.16938
  Epoch 020 - train 0.12889 | val 0.17053
  Regression -> MSE: 0.000165, MAE: 0.010561, R²: -0.0008
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.14545 | val 0.16397
  Epoch 020 - train 0.14011 | val 0.16604
  Regression -> MSE: 0.000087, MAE: 0.007145, R²: -0.0205
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.14082 | val 0.17466
  Epoch 020 - train 0.13350 | val 0.17332
  Regression -> MSE: 0.000212, MAE: 0.011210, R²: -0.0026
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.12906 | val 0.12713
  Epoch 020 - train 0.12957 | val 0.12401
  Regression -> MSE: 0.000095, MAE: 0.008107, R²: -0.0269
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.14391 | val 0.10778
  Epoch 020 - train 0.13970 | val 0.10815
  Regression -> MSE: 0.000104, MAE: 0.008812, R²: -0.0110
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.14598 | val 0.14046
  Epoch 020 - train 0.14746 | val 0.16502
  Regression -> MSE: 0.000235, MAE: 0.012674, R²: -0.0150
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.13925 | val 0.16574
  Epoch 020 - train 0.13799 | val 0.16555
  Regression -> MSE: 0.000179, MAE: 0.007946, R²: -0.0739
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.14574 | val 0.11789
  Epoch 020 - train 0.14455 | val 0.11721
  Regression -> MSE: 0.000237, MAE: 0.011869, R²: -0.0006
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.13428 | val 0.22402
  Epoch 020 - train 0.13380 | val 0.23145
  Regression -> MSE: 0.000232, MAE: 0.009991, R²: -0.0049
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.14559 | val 0.17035
  Epoch 020 - train 0.14051 | val 0.16575
  Regression -> MSE: 0.000137, MAE: 0.008173, R²: -0.0180
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.14616 | val 0.18190
  Epoch 020 - train 0.13801 | val 0.18692
  Regression -> MSE: 0.000191, MAE: 0.010389, R²: -0.0148
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.13418 | val 0.15418
  Epoch 020 - train 0.13027 | val 0.15243
  Regression -> MSE: 0.000269, MAE: 0.010592, R²: -0.0254
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.13631 | val 0.12477
  Epoch 020 - train 0.13524 | val 0.12220
  Regression -> MSE: 0.000169, MAE: 0.010369, R²: -0.0127
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.12431 | val 0.13942
  Epoch 020 - train 0.12559 | val 0.14626
  Regression -> MSE: 0.000179, MAE: 0.010263, R²: 0.0027
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.13050 | val 0.13033
  Epoch 020 - train 0.13140 | val 0.12966
  Regression -> MSE: 0.000343, MAE: 0.011888, R²: -0.0011
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.14428 | val 0.09051
  Epoch 020 - train 0.14651 | val 0.09345
  Regression -> MSE: 0.000125, MAE: 0.008456, R²: -0.1879
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.14469 | val 0.19866
  Epoch 020 - train 0.13899 | val 0.20167
  Regression -> MSE: 0.000219, MAE: 0.011337, R²: -0.0042
  Directional -> Accuracy: 0.5088, MCC: 0.1809, F1: 0.6585

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.13542 | val 0.23310
  Epoch 020 - train 0.13304 | val 0.23748
  Regression -> MSE: 0.000086, MAE: 0.007265, R²: -0.1117
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.13471 | val 0.11230
  Epoch 020 - train 0.13952 | val 0.11746
  Regression -> MSE: 0.000325, MAE: 0.014761, R²: -0.0557
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.15197 | val 0.08449
  Epoch 020 - train 0.15600 | val 0.09407
  Regression -> MSE: 0.000246, MAE: 0.011564, R²: -0.0073
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.0000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.13685 | val 0.17256
  Epoch 020 - train 0.13125 | val 0.16998
  Regression -> MSE: 0.000081, MAE: 0.007056, R²: -0.0041
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.14076 | val 0.17609
  Epoch 020 - train 0.13998 | val 0.17142
  Regression -> MSE: 0.000308, MAE: 0.014479, R²: -0.0029
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.15134 | val 0.14487
  Epoch 020 - train 0.14765 | val 0.14849
  Regression -> MSE: 0.000099, MAE: 0.007413, R²: -0.0040
  Directional -> Accuracy: 0.4318, MCC: 0.0000, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.14975 | val 0.16456
  Epoch 020 - train 0.14840 | val 0.16505
  Regression -> MSE: 0.000172, MAE: 0.009531, R²: -0.0024
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.13285 | val 0.17718
  Epoch 020 - train 0.13343 | val 0.18731
  Regression -> MSE: 0.000226, MAE: 0.011787, R²: -0.0135
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.13903 | val 0.16122
  Epoch 020 - train 0.13616 | val 0.16343
  Regression -> MSE: 0.000094, MAE: 0.007736, R²: -0.0149
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.14074 | val 0.22749
  Epoch 020 - train 0.14333 | val 0.23971
  Regression -> MSE: 0.000168, MAE: 0.010307, R²: -0.0241
  Directional -> Accuracy: 0.4815, MCC: 0.0000, F1: 0.0000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.13260 | val 0.17146
  Epoch 020 - train 0.13545 | val 0.17449
  Regression -> MSE: 0.000124, MAE: 0.009014, R²: -0.0708
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.13968 | val 0.22494

[I 2026-02-23 01:54:15,862] Trial 184 finished with value: -0.01142706779114669 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 32, 'learning_rate': 5.1191699773194406e-06, 'weight_decay': 3.8767659546800065e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.21131804691748426, 'early_stopping_min_delta': 0.005291338397024014}. Best is trial 157 with value: -0.011387287234516647.

  Epoch 020 - train 0.14096 | val 0.26429
  Regression -> MSE: 0.000239, MAE: 0.012323, R²: -0.0090
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.07521 | val 0.09631
  Epoch 020 - train 0.07370 | val 0.09526
  Regression -> MSE: 0.000257, MAE: 0.012927, R²: -0.0397
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.07366 | val 0.06865
  Epoch 020 - train 0.07231 | val 0.06952
  Regression -> MSE: 0.000721, MAE: 0.019977, R²: -0.0531
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.07475 | val 0.11619
  Epoch 020 - train 0.07730 | val 0.11728
  Regression -> MSE: 0.000310, MAE: 0.014409, R²: -0.0009
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.06146 | val 0.06757
  Epoch 020 - train 0.06093 | val 0.07364
  Regression -> MSE: 0.000355, MAE: 0.014679, R²: -0.0164
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.07899 | val 0.07483
  Epoch 020 - train 0.07815 | val 0.08115
  Regression -> MSE: 0.000206, MAE: 0.010066, R²: -0.0096
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.07252 | val 0.13106
  Epoch 020 - train 0.07036 | val 0.14425
  Regression -> MSE: 0.000573, MAE: 0.018442, R²: -0.0319
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.07754 | val 0.09206
  Epoch 020 - train 0.07513 | val 0.09243
  Regression -> MSE: 0.000249, MAE: 0.011943, R²: -0.0130
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.08349 | val 0.08398
  Epoch 020 - train 0.08055 | val 0.07723
  Regression -> MSE: 0.000604, MAE: 0.019109, R²: -0.0111
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.07197 | val 0.08965
  Epoch 020 - train 0.07014 | val 0.08844
  Regression -> MSE: 0.000386, MAE: 0.016117, R²: -0.0055
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.07183 | val 0.09160
  Epoch 020 - train 0.07041 | val 0.09460
  Regression -> MSE: 0.000244, MAE: 0.012249, R²: -0.0101
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.07249 | val 0.10714
  Epoch 020 - train 0.07088 | val 0.11762
  Regression -> MSE: 0.000327, MAE: 0.013625, R²: -0.0504
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.07366 | val 0.08725
  Epoch 020 - train 0.07706 | val 0.09391
  Regression -> MSE: 0.000678, MAE: 0.019526, R²: -0.0009
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.07277 | val 0.07826
  Epoch 020 - train 0.07555 | val 0.09151
  Regression -> MSE: 0.000138, MAE: 0.009104, R²: 0.0003
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.06759 | val 0.09848
  Epoch 020 - train 0.06676 | val 0.09888
  Regression -> MSE: 0.000225, MAE: 0.010691, R²: -0.0013
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.07507 | val 0.14264
  Epoch 020 - train 0.07447 | val 0.14459
  Regression -> MSE: 0.000372, MAE: 0.015933, R²: -0.0264
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.07682 | val 0.07474
  Epoch 020 - train 0.07587 | val 0.07540
  Regression -> MSE: 0.000107, MAE: 0.008033, R²: 0.0036
  Directional -> Accuracy: 0.4571, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.07333 | val 0.11679
  Epoch 020 - train 0.07095 | val 0.11817
  Regression -> MSE: 0.000157, MAE: 0.009808, R²: -0.0101
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.07539 | val 0.07653
  Epoch 020 - train 0.07364 | val 0.07555
  Regression -> MSE: 0.000275, MAE: 0.013160, R²: -0.0096
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.06798 | val 0.10175
  Epoch 020 - train 0.06657 | val 0.10202
  Regression -> MSE: 0.000153, MAE: 0.008748, R²: -0.0261
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.07920 | val 0.11080
  Epoch 020 - train 0.07707 | val 0.10772
  Regression -> MSE: 0.000227, MAE: 0.010923, R²: -0.0024
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.07252 | val 0.09165
  Epoch 020 - train 0.07249 | val 0.10704
  Regression -> MSE: 0.000143, MAE: 0.008305, R²: -0.0006
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.07011 | val 0.08694
  Epoch 020 - train 0.06969 | val 0.08730
  Regression -> MSE: 0.000168, MAE: 0.010279, R²: -0.0185
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.07611 | val 0.08390
  Epoch 020 - train 0.07588 | val 0.08522
  Regression -> MSE: 0.000086, MAE: 0.007084, R²: -0.0069
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.07329 | val 0.11048
  Epoch 020 - train 0.07288 | val 0.11356
  Regression -> MSE: 0.000214, MAE: 0.011075, R²: -0.0120
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.06829 | val 0.06581
  Epoch 020 - train 0.06645 | val 0.06456
  Regression -> MSE: 0.000094, MAE: 0.008086, R²: -0.0218
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.07786 | val 0.06278
  Epoch 020 - train 0.07903 | val 0.05994
  Regression -> MSE: 0.000115, MAE: 0.009166, R²: -0.1115
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.07534 | val 0.07068
  Epoch 020 - train 0.07597 | val 0.07020
  Regression -> MSE: 0.000238, MAE: 0.012780, R²: -0.0270
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.07245 | val 0.08199
  Epoch 020 - train 0.07261 | val 0.07982
  Regression -> MSE: 0.000211, MAE: 0.009230, R²: -0.2693
  Directional -> Accuracy: 0.5614, MCC: 0.2858, F1: 0.3902

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.07067 | val 0.06269
  Epoch 020 - train 0.07410 | val 0.06195
  Regression -> MSE: 0.000237, MAE: 0.011870, R²: -0.0017
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.07396 | val 0.11328
  Epoch 020 - train 0.06985 | val 0.12096
  Regression -> MSE: 0.000230, MAE: 0.009865, R²: -0.0002
  Directional -> Accuracy: 0.5581, MCC: 0.1239, F1: 0.5957

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.08010 | val 0.09471
  Epoch 020 - train 0.07827 | val 0.10665
  Regression -> MSE: 0.000140, MAE: 0.008454, R²: -0.0397
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.07454 | val 0.09311
  Epoch 020 - train 0.07333 | val 0.09363
  Regression -> MSE: 0.000189, MAE: 0.010484, R²: -0.0016
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.06659 | val 0.08626
  Epoch 020 - train 0.06688 | val 0.08507
  Regression -> MSE: 0.000269, MAE: 0.010586, R²: -0.0263
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.06643 | val 0.06320
  Epoch 020 - train 0.06784 | val 0.06297
  Regression -> MSE: 0.000167, MAE: 0.010370, R²: -0.0003
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.07024 | val 0.07304
  Epoch 020 - train 0.06903 | val 0.07280
  Regression -> MSE: 0.000180, MAE: 0.010301, R²: -0.0004
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.06958 | val 0.07107
  Epoch 020 - train 0.06770 | val 0.07132
  Regression -> MSE: 0.000347, MAE: 0.011731, R²: -0.0117
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.07909 | val 0.04874
  Epoch 020 - train 0.07791 | val 0.05146
  Regression -> MSE: 0.000113, MAE: 0.008344, R²: -0.0794
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.07779 | val 0.10269
  Epoch 020 - train 0.07245 | val 0.10776
  Regression -> MSE: 0.000218, MAE: 0.011282, R²: 0.0004
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.07577 | val 0.12134
  Epoch 020 - train 0.07348 | val 0.12104
  Regression -> MSE: 0.000083, MAE: 0.007115, R²: -0.0714
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.07609 | val 0.05480
  Epoch 020 - train 0.07638 | val 0.05548
  Regression -> MSE: 0.000310, MAE: 0.013962, R²: -0.0092
  Directional -> Accuracy: 0.6327, MCC: 0.0000, F1: 0.0000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.07812 | val 0.04501
  Epoch 020 - train 0.07489 | val 0.04381
  Regression -> MSE: 0.000249, MAE: 0.011513, R²: -0.0231
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.06942 | val 0.08546
  Epoch 020 - train 0.06909 | val 0.08611
  Regression -> MSE: 0.000084, MAE: 0.007042, R²: -0.0365
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.07161 | val 0.08965
  Epoch 020 - train 0.06823 | val 0.08999
  Regression -> MSE: 0.000307, MAE: 0.014495, R²: 0.0001
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.07095 | val 0.08419
  Epoch 020 - train 0.07058 | val 0.08242
  Regression -> MSE: 0.000101, MAE: 0.007102, R²: -0.0259
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.08190 | val 0.08855
  Epoch 020 - train 0.08229 | val 0.09289
  Regression -> MSE: 0.000173, MAE: 0.009483, R²: -0.0070
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.06749 | val 0.08116
  Epoch 020 - train 0.06852 | val 0.08245
  Regression -> MSE: 0.000223, MAE: 0.011743, R²: 0.0000
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.07267 | val 0.08780
  Epoch 020 - train 0.07159 | val 0.09134
  Regression -> MSE: 0.000094, MAE: 0.007763, R²: -0.0211
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.07663 | val 0.11336
  Epoch 020 - train 0.07587 | val 0.12351
  Regression -> MSE: 0.000164, MAE: 0.010252, R²: 0.0003
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.07297 | val 0.08913
  Epoch 020 - train 0.07227 | val 0.09176
  Regression -> MSE: 0.000122, MAE: 0.008996, R²: -0.0509
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.07723 | val 0.12715

[I 2026-02-23 01:56:53,571] Trial 185 finished with value: -0.01141102030554968 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 32, 'learning_rate': 5.350965691881926e-06, 'weight_decay': 4.108172514311195e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.10378826475701408, 'early_stopping_min_delta': 0.005347275191532856}. Best is trial 157 with value: -0.011387287234516647.

  Epoch 020 - train 0.07636 | val 0.14383
  Regression -> MSE: 0.000240, MAE: 0.012326, R²: -0.0119
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.08299 | val 0.10649
  Epoch 020 - train 0.08322 | val 0.10655
  Regression -> MSE: 0.000248, MAE: 0.012532, R²: -0.0004
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.08376 | val 0.08435
  Epoch 020 - train 0.08224 | val 0.10649
  Regression -> MSE: 0.000683, MAE: 0.019346, R²: 0.0027
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.08493 | val 0.13005
  Epoch 020 - train 0.08227 | val 0.12839
  Regression -> MSE: 0.000310, MAE: 0.014411, R²: -0.0002
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.06814 | val 0.11692
  Epoch 020 - train 0.07164 | val 0.12691
  Regression -> MSE: 0.000353, MAE: 0.014635, R²: -0.0098
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.08905 | val 0.08977
  Epoch 020 - train 0.08747 | val 0.09802
  Regression -> MSE: 0.000204, MAE: 0.010122, R²: -0.0006
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.08169 | val 0.14789
  Epoch 020 - train 0.07831 | val 0.14909
  Regression -> MSE: 0.000559, MAE: 0.018168, R²: -0.0077
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.08127 | val 0.11062
  Epoch 020 - train 0.08223 | val 0.11355
  Regression -> MSE: 0.000247, MAE: 0.011917, R²: -0.0070
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.08791 | val 0.09296
  Epoch 020 - train 0.08653 | val 0.09336
  Regression -> MSE: 0.000602, MAE: 0.019255, R²: -0.0071
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.07699 | val 0.09842
  Epoch 020 - train 0.07928 | val 0.09704
  Regression -> MSE: 0.000389, MAE: 0.015952, R²: -0.0148
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.08465 | val 0.10537
  Epoch 020 - train 0.08277 | val 0.10602
  Regression -> MSE: 0.000246, MAE: 0.011652, R²: -0.0185
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.07589 | val 0.11571
  Epoch 020 - train 0.07222 | val 0.11713
  Regression -> MSE: 0.000313, MAE: 0.013606, R²: -0.0062
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.08426 | val 0.09985
  Epoch 020 - train 0.08280 | val 0.10372
  Regression -> MSE: 0.000677, MAE: 0.019478, R²: -0.0001
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.4314

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.08539 | val 0.08459
  Epoch 020 - train 0.08554 | val 0.08405
  Regression -> MSE: 0.000138, MAE: 0.009064, R²: -0.0009
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.07936 | val 0.10078
  Epoch 020 - train 0.08093 | val 0.10070
  Regression -> MSE: 0.000231, MAE: 0.010944, R²: -0.0287
  Directional -> Accuracy: 0.4918, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.08998 | val 0.16465
  Epoch 020 - train 0.08916 | val 0.16746
  Regression -> MSE: 0.000362, MAE: 0.016062, R²: -0.0007
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.08334 | val 0.08260
  Epoch 020 - train 0.08385 | val 0.08225
  Regression -> MSE: 0.000108, MAE: 0.008068, R²: -0.0022
  Directional -> Accuracy: 0.4571, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.08137 | val 0.12808
  Epoch 020 - train 0.08046 | val 0.12702
  Regression -> MSE: 0.000161, MAE: 0.010153, R²: -0.0347
  Directional -> Accuracy: 0.3729, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.08556 | val 0.08723
  Epoch 020 - train 0.08290 | val 0.08648
  Regression -> MSE: 0.000276, MAE: 0.012920, R²: -0.0148
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.07585 | val 0.11233
  Epoch 020 - train 0.07728 | val 0.11344
  Regression -> MSE: 0.000156, MAE: 0.008801, R²: -0.0453
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.09287 | val 0.12523
  Epoch 020 - train 0.09532 | val 0.12547
  Regression -> MSE: 0.000248, MAE: 0.011267, R²: -0.0977
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.08211 | val 0.10283
  Epoch 020 - train 0.08301 | val 0.10712
  Regression -> MSE: 0.000152, MAE: 0.008773, R²: -0.0599
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.07949 | val 0.09643
  Epoch 020 - train 0.07929 | val 0.09609
  Regression -> MSE: 0.000177, MAE: 0.010301, R²: -0.0698
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.08473 | val 0.10741
  Epoch 020 - train 0.08673 | val 0.11413
  Regression -> MSE: 0.000085, MAE: 0.007017, R²: 0.0009
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.08455 | val 0.09817
  Epoch 020 - train 0.08171 | val 0.09865
  Regression -> MSE: 0.000212, MAE: 0.011170, R²: 0.0010
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.07709 | val 0.07457
  Epoch 020 - train 0.07866 | val 0.07588
  Regression -> MSE: 0.000097, MAE: 0.008148, R²: -0.0508
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.08238 | val 0.06949
  Epoch 020 - train 0.08507 | val 0.07062
  Regression -> MSE: 0.000116, MAE: 0.009210, R²: -0.1264
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.08355 | val 0.07864
  Epoch 020 - train 0.08347 | val 0.08453
  Regression -> MSE: 0.000234, MAE: 0.012620, R²: -0.0090
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.08130 | val 0.09574
  Epoch 020 - train 0.08359 | val 0.09403
  Regression -> MSE: 0.000204, MAE: 0.008935, R²: -0.2283
  Directional -> Accuracy: 0.6140, MCC: 0.1966, F1: 0.6944

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.08796 | val 0.07568
  Epoch 020 - train 0.08549 | val 0.08138
  Regression -> MSE: 0.000240, MAE: 0.012040, R²: -0.0143
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.08229 | val 0.13344
  Epoch 020 - train 0.08217 | val 0.14579
  Regression -> MSE: 0.000235, MAE: 0.010162, R²: -0.0190
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.08482 | val 0.09812
  Epoch 020 - train 0.08613 | val 0.09604
  Regression -> MSE: 0.000136, MAE: 0.008269, R²: -0.0103
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.08895 | val 0.10877
  Epoch 020 - train 0.08767 | val 0.11427
  Regression -> MSE: 0.000188, MAE: 0.010412, R²: -0.0010
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.07398 | val 0.09135
  Epoch 020 - train 0.07629 | val 0.09204
  Regression -> MSE: 0.000318, MAE: 0.012252, R²: -0.2131
  Directional -> Accuracy: 0.4384, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.07749 | val 0.07071
  Epoch 020 - train 0.07690 | val 0.07718
  Regression -> MSE: 0.000167, MAE: 0.010368, R²: -0.0010
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.07877 | val 0.08257
  Epoch 020 - train 0.07756 | val 0.08473
  Regression -> MSE: 0.000180, MAE: 0.010254, R²: -0.0023
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.08398 | val 0.08024
  Epoch 020 - train 0.08152 | val 0.08058
  Regression -> MSE: 0.000345, MAE: 0.012090, R²: -0.0083
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.08505 | val 0.05416
  Epoch 020 - train 0.08907 | val 0.05420
  Regression -> MSE: 0.000120, MAE: 0.008350, R²: -0.1384
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.08517 | val 0.10721
  Epoch 020 - train 0.08557 | val 0.10772
  Regression -> MSE: 0.000219, MAE: 0.011296, R²: -0.0008
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.08385 | val 0.13910
  Epoch 020 - train 0.08531 | val 0.14282
  Regression -> MSE: 0.000082, MAE: 0.007059, R²: -0.0555
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.08220 | val 0.06187
  Epoch 020 - train 0.07804 | val 0.06041
  Regression -> MSE: 0.000312, MAE: 0.014066, R²: -0.0153
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.08861 | val 0.05063
  Epoch 020 - train 0.08908 | val 0.05152
  Regression -> MSE: 0.000247, MAE: 0.011555, R²: -0.0147
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.0000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.08025 | val 0.09770
  Epoch 020 - train 0.07872 | val 0.09800
  Regression -> MSE: 0.000082, MAE: 0.007058, R²: -0.0093
  Directional -> Accuracy: 0.5333, MCC: 0.0779, F1: 0.6067

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.08030 | val 0.10152
  Epoch 020 - train 0.08038 | val 0.09905
  Regression -> MSE: 0.000307, MAE: 0.014489, R²: -0.0009
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.08985 | val 0.08423
  Epoch 020 - train 0.08939 | val 0.08307
  Regression -> MSE: 0.000099, MAE: 0.007420, R²: -0.0042
  Directional -> Accuracy: 0.4318, MCC: 0.0000, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.08893 | val 0.09550
  Epoch 020 - train 0.08791 | val 0.09799
  Regression -> MSE: 0.000172, MAE: 0.009757, R²: -0.0023
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.07546 | val 0.09455
  Epoch 020 - train 0.07925 | val 0.09552
  Regression -> MSE: 0.000225, MAE: 0.011781, R²: -0.0105
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.08474 | val 0.09473
  Epoch 020 - train 0.08037 | val 0.09579
  Regression -> MSE: 0.000093, MAE: 0.007665, R²: -0.0033
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.08837 | val 0.12311
  Epoch 020 - train 0.08630 | val 0.12562
  Regression -> MSE: 0.000164, MAE: 0.010248, R²: -0.0006
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.08034 | val 0.11009
  Epoch 020 - train 0.07700 | val 0.11817
  Regression -> MSE: 0.000120, MAE: 0.008974, R²: -0.0335
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.08433 | val 0.11140

[I 2026-02-23 01:59:29,151] Trial 186 finished with value: -0.011448594843160399 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 32, 'learning_rate': 1.0243720284342194e-06, 'weight_decay': 5.294890232176985e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.11711076458442626, 'early_stopping_min_delta': 0.0051884107648235145}. Best is trial 157 with value: -0.011387287234516647.

  Epoch 020 - train 0.08205 | val 0.11033
  Regression -> MSE: 0.000243, MAE: 0.012338, R²: -0.0266
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.06892 | val 0.10126
  Epoch 020 - train 0.06700 | val 0.10946
  Regression -> MSE: 0.000251, MAE: 0.012673, R²: -0.0124
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.06525 | val 0.07084
  Epoch 020 - train 0.06752 | val 0.07870
  Regression -> MSE: 0.000696, MAE: 0.019551, R²: -0.0174
  Directional -> Accuracy: 0.6304, MCC: 0.2287, F1: 0.7119

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.07363 | val 0.11904
  Epoch 020 - train 0.06878 | val 0.12125
  Regression -> MSE: 0.000320, MAE: 0.014499, R²: -0.0316
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.05810 | val 0.15849
  Epoch 020 - train 0.05605 | val 0.20866
  Regression -> MSE: 0.000349, MAE: 0.014591, R²: 0.0005
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.06995 | val 0.08527
  Epoch 020 - train 0.06698 | val 0.11609
  Regression -> MSE: 0.000204, MAE: 0.010038, R²: -0.0015
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.06595 | val 0.13486
  Epoch 020 - train 0.06232 | val 0.14281
  Regression -> MSE: 0.000577, MAE: 0.018523, R²: -0.0392
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.07195 | val 0.09484
  Epoch 020 - train 0.06854 | val 0.09809
  Regression -> MSE: 0.000250, MAE: 0.012535, R²: -0.0195
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.06695 | val 0.10360
  Epoch 020 - train 0.06179 | val 0.13053
  Regression -> MSE: 0.000646, MAE: 0.020197, R²: -0.0820
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.06698 | val 0.09009
  Epoch 020 - train 0.05944 | val 0.09076
  Regression -> MSE: 0.000389, MAE: 0.016000, R²: -0.0145
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.06867 | val 0.09838
  Epoch 020 - train 0.06623 | val 0.09732
  Regression -> MSE: 0.000242, MAE: 0.011736, R²: -0.0007
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.06350 | val 0.11509
  Epoch 020 - train 0.06346 | val 0.14936
  Regression -> MSE: 0.000317, MAE: 0.013585, R²: -0.0204
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.06938 | val 0.10099
  Epoch 020 - train 0.07052 | val 0.11096
  Regression -> MSE: 0.000676, MAE: 0.019499, R²: 0.0018
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.06819 | val 0.07728
  Epoch 020 - train 0.06534 | val 0.09573
  Regression -> MSE: 0.000138, MAE: 0.009115, R²: -0.0012
  Directional -> Accuracy: 0.4186, MCC: -0.1734, F1: 0.5902

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.06401 | val 0.09442
  Epoch 020 - train 0.06247 | val 0.09835
  Regression -> MSE: 0.000218, MAE: 0.010531, R²: 0.0299
  Directional -> Accuracy: 0.6393, MCC: 0.3080, F1: 0.7105

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.06737 | val 0.14653
  Epoch 020 - train 0.06619 | val 0.15585
  Regression -> MSE: 0.000363, MAE: 0.016227, R²: -0.0029
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.07173 | val 0.08163
  Epoch 020 - train 0.06790 | val 0.08638
  Regression -> MSE: 0.000109, MAE: 0.008109, R²: -0.0085
  Directional -> Accuracy: 0.4571, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.06597 | val 0.18379
  Epoch 020 - train 0.06609 | val 0.21439
  Regression -> MSE: 0.000156, MAE: 0.009564, R²: -0.0001
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.07082 | val 0.08861
  Epoch 020 - train 0.06951 | val 0.09117
  Regression -> MSE: 0.000279, MAE: 0.013385, R²: -0.0249
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.06172 | val 0.09487
  Epoch 020 - train 0.05817 | val 0.09329
  Regression -> MSE: 0.000251, MAE: 0.012210, R²: -0.6805
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.06906 | val 0.12140
  Epoch 020 - train 0.06590 | val 0.12894
  Regression -> MSE: 0.000248, MAE: 0.011270, R²: -0.0978
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.07007 | val 0.09229
  Epoch 020 - train 0.06441 | val 0.10798
  Regression -> MSE: 0.000144, MAE: 0.008423, R²: -0.0074
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.06803 | val 0.09635
  Epoch 020 - train 0.06521 | val 0.09671
  Regression -> MSE: 0.000167, MAE: 0.010273, R²: -0.0112
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.07159 | val 0.08864
  Epoch 020 - train 0.06804 | val 0.09433
  Regression -> MSE: 0.000085, MAE: 0.007049, R²: -0.0021
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.06734 | val 0.14416
  Epoch 020 - train 0.06497 | val 0.14824
  Regression -> MSE: 0.000213, MAE: 0.011287, R²: -0.0044
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.06198 | val 0.06271
  Epoch 020 - train 0.06208 | val 0.06163
  Regression -> MSE: 0.000133, MAE: 0.008877, R²: -0.4487
  Directional -> Accuracy: 0.5893, MCC: 0.2335, F1: 0.5306

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.06886 | val 0.06035
  Epoch 020 - train 0.06891 | val 0.06523
  Regression -> MSE: 0.000116, MAE: 0.009202, R²: -0.1223
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.07285 | val 0.07608
  Epoch 020 - train 0.06986 | val 0.09793
  Regression -> MSE: 0.000232, MAE: 0.012523, R²: -0.0007
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.06878 | val 0.08868
  Epoch 020 - train 0.06524 | val 0.09351
  Regression -> MSE: 0.000175, MAE: 0.007876, R²: -0.0519
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.07631 | val 0.06769
  Epoch 020 - train 0.07115 | val 0.06407
  Regression -> MSE: 0.000241, MAE: 0.012077, R²: -0.0185
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.06574 | val 0.11612
  Epoch 020 - train 0.06470 | val 0.12483
  Regression -> MSE: 0.000230, MAE: 0.009863, R²: 0.0000
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.06686 | val 0.08993
  Epoch 020 - train 0.06995 | val 0.12552
  Regression -> MSE: 0.000137, MAE: 0.008272, R²: -0.0113
  Directional -> Accuracy: 0.5581, MCC: 0.1655, F1: 0.7077

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.06711 | val 0.09660
  Epoch 020 - train 0.06727 | val 0.10599
  Regression -> MSE: 0.000189, MAE: 0.010397, R²: -0.0035
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.06246 | val 0.09008
  Epoch 020 - train 0.06093 | val 0.09017
  Regression -> MSE: 0.000271, MAE: 0.010644, R²: -0.0344
  Directional -> Accuracy: 0.4384, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.06102 | val 0.06361
  Epoch 020 - train 0.06164 | val 0.06900
  Regression -> MSE: 0.000167, MAE: 0.010368, R²: 0.0009
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.06413 | val 0.07748
  Epoch 020 - train 0.06228 | val 0.09726
  Regression -> MSE: 0.000181, MAE: 0.010318, R²: -0.0073
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.06429 | val 0.07600
  Epoch 020 - train 0.06232 | val 0.08219
  Regression -> MSE: 0.000347, MAE: 0.012206, R²: -0.0118
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.07093 | val 0.05001
  Epoch 020 - train 0.06455 | val 0.05809
  Regression -> MSE: 0.000119, MAE: 0.008351, R²: -0.1332
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.06929 | val 0.11394
  Epoch 020 - train 0.06654 | val 0.13121
  Regression -> MSE: 0.000225, MAE: 0.011483, R²: -0.0299
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.06490 | val 0.12777
  Epoch 020 - train 0.06416 | val 0.14889
  Regression -> MSE: 0.000093, MAE: 0.007552, R²: -0.2036
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.06584 | val 0.06423
  Epoch 020 - train 0.06288 | val 0.05488
  Regression -> MSE: 0.000744, MAE: 0.023758, R²: -1.4175
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.07364 | val 0.05022
  Epoch 020 - train 0.06614 | val 0.05637
  Regression -> MSE: 0.000259, MAE: 0.011490, R²: -0.0625
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.06608 | val 0.09680
  Epoch 020 - train 0.06142 | val 0.10939
  Regression -> MSE: 0.000081, MAE: 0.007056, R²: -0.0059
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.06812 | val 0.08921
  Epoch 020 - train 0.06792 | val 0.14358
  Regression -> MSE: 0.000307, MAE: 0.014494, R²: -0.0002
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.06629 | val 0.08493
  Epoch 020 - train 0.06175 | val 0.08181
  Regression -> MSE: 0.000101, MAE: 0.007109, R²: -0.0266
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.07257 | val 0.08686
  Epoch 020 - train 0.07077 | val 0.09492
  Regression -> MSE: 0.000172, MAE: 0.009678, R²: 0.0005
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.06671 | val 0.09143
  Epoch 020 - train 0.06220 | val 0.10892
  Regression -> MSE: 0.000224, MAE: 0.011751, R²: -0.0026
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.06659 | val 0.09692
  Epoch 020 - train 0.06497 | val 0.13439
  Regression -> MSE: 0.000093, MAE: 0.007642, R²: -0.0031
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.07267 | val 0.12503
  Epoch 020 - train 0.06949 | val 0.16013
  Regression -> MSE: 0.000164, MAE: 0.010267, R²: -0.0044
  Directional -> Accuracy: 0.5370, MCC: 0.0899, F1: 0.6835

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.06414 | val 0.10147
  Epoch 020 - train 0.06385 | val 0.12265
  Regression -> MSE: 0.000125, MAE: 0.009030, R²: -0.0746
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.07017 | val 0.10898

[I 2026-02-23 02:02:06,311] Trial 187 finished with value: -0.011710431811050788 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 32, 'learning_rate': 0.00019697666054085876, 'weight_decay': 8.491605194834047e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.10620172946064932, 'early_stopping_min_delta': 0.005348495082434492}. Best is trial 157 with value: -0.011387287234516647.

  Epoch 020 - train 0.06780 | val 0.13031
  Regression -> MSE: 0.000237, MAE: 0.012371, R²: 0.0027
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.16244 | val 0.24545
  Epoch 020 - train 0.15677 | val 0.24724
  Regression -> MSE: 0.000255, MAE: 0.012860, R²: -0.0316
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.14895 | val 0.14828
  Epoch 020 - train 0.15365 | val 0.15056
  Regression -> MSE: 0.000689, MAE: 0.019415, R²: -0.0068
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.16347 | val 0.26098
  Epoch 020 - train 0.16000 | val 0.26653
  Regression -> MSE: 0.000313, MAE: 0.014432, R²: -0.0092
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.14141 | val 0.29956
  Epoch 020 - train 0.14039 | val 0.33709
  Regression -> MSE: 0.000363, MAE: 0.014820, R²: -0.0398
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.15882 | val 0.15360
  Epoch 020 - train 0.15659 | val 0.16870
  Regression -> MSE: 0.000200, MAE: 0.009781, R²: 0.0198
  Directional -> Accuracy: 0.6078, MCC: 0.2270, F1: 0.7059

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.14691 | val 0.29347
  Epoch 020 - train 0.15021 | val 0.30010
  Regression -> MSE: 0.000555, MAE: 0.018172, R²: 0.0007
  Directional -> Accuracy: 0.4894, MCC: 0.0000, F1: 0.6571

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.15684 | val 0.19739
  Epoch 020 - train 0.15678 | val 0.19565
  Regression -> MSE: 0.000246, MAE: 0.011996, R²: -0.0022
  Directional -> Accuracy: 0.3913, MCC: -0.1133, F1: 0.5532

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.15144 | val 0.22835
  Epoch 020 - train 0.15512 | val 0.28267
  Regression -> MSE: 0.000641, MAE: 0.020099, R²: -0.0734
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.15937 | val 0.20496
  Epoch 020 - train 0.15922 | val 0.21950
  Regression -> MSE: 0.000383, MAE: 0.016158, R²: 0.0026
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.15501 | val 0.19810
  Epoch 020 - train 0.15413 | val 0.19934
  Regression -> MSE: 0.000244, MAE: 0.011667, R²: -0.0122
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.14645 | val 0.25008
  Epoch 020 - train 0.14476 | val 0.28558
  Regression -> MSE: 0.000312, MAE: 0.013704, R²: -0.0020
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.6301

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.15554 | val 0.18396
  Epoch 020 - train 0.15683 | val 0.18537
  Regression -> MSE: 0.000678, MAE: 0.019489, R²: -0.0005
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.16066 | val 0.15880
  Epoch 020 - train 0.15457 | val 0.16486
  Regression -> MSE: 0.000147, MAE: 0.009584, R²: -0.0611
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.14442 | val 0.21147
  Epoch 020 - train 0.13903 | val 0.21478
  Regression -> MSE: 0.000225, MAE: 0.010721, R²: -0.0005
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.15370 | val 0.32050
  Epoch 020 - train 0.15009 | val 0.32193
  Regression -> MSE: 0.000363, MAE: 0.016042, R²: -0.0025
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.16544 | val 0.16007
  Epoch 020 - train 0.16137 | val 0.15948
  Regression -> MSE: 0.000105, MAE: 0.007932, R²: 0.0271
  Directional -> Accuracy: 0.5143, MCC: 0.0414, F1: 0.5000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.15596 | val 0.30402
  Epoch 020 - train 0.15214 | val 0.33747
  Regression -> MSE: 0.000161, MAE: 0.010119, R²: -0.0305
  Directional -> Accuracy: 0.4915, MCC: -0.1303, F1: 0.6154

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.15621 | val 0.16658
  Epoch 020 - train 0.15491 | val 0.16888
  Regression -> MSE: 0.000273, MAE: 0.012965, R²: -0.0020
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.14383 | val 0.22247
  Epoch 020 - train 0.14136 | val 0.22169
  Regression -> MSE: 0.000157, MAE: 0.008826, R²: -0.0520
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.15631 | val 0.22058
  Epoch 020 - train 0.15680 | val 0.22006
  Regression -> MSE: 0.000230, MAE: 0.010895, R²: -0.0181
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.14801 | val 0.19763
  Epoch 020 - train 0.14780 | val 0.20324
  Regression -> MSE: 0.000152, MAE: 0.008788, R²: -0.0623
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.14385 | val 0.18465
  Epoch 020 - train 0.14426 | val 0.18525
  Regression -> MSE: 0.000176, MAE: 0.010286, R²: -0.0644
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.16223 | val 0.18952
  Epoch 020 - train 0.16091 | val 0.19572
  Regression -> MSE: 0.000088, MAE: 0.007220, R²: -0.0348
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.15299 | val 0.18811
  Epoch 020 - train 0.15345 | val 0.18996
  Regression -> MSE: 0.000213, MAE: 0.011058, R²: -0.0073
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.14548 | val 0.13759
  Epoch 020 - train 0.14368 | val 0.13513
  Regression -> MSE: 0.000095, MAE: 0.008114, R²: -0.0346
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.16158 | val 0.12931
  Epoch 020 - train 0.15554 | val 0.12272
  Regression -> MSE: 0.000115, MAE: 0.009109, R²: -0.1116
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.15947 | val 0.15159
  Epoch 020 - train 0.15665 | val 0.15336
  Regression -> MSE: 0.000237, MAE: 0.012753, R²: -0.0234
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.15188 | val 0.18971
  Epoch 020 - train 0.15025 | val 0.19189
  Regression -> MSE: 0.000182, MAE: 0.008002, R²: -0.0942
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.15863 | val 0.13688
  Epoch 020 - train 0.16048 | val 0.12982
  Regression -> MSE: 0.000231, MAE: 0.011848, R²: 0.0241
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.16058 | val 0.24813
  Epoch 020 - train 0.14878 | val 0.25762
  Regression -> MSE: 0.000231, MAE: 0.009891, R²: -0.0034
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.15967 | val 0.19425
  Epoch 020 - train 0.16018 | val 0.21638
  Regression -> MSE: 0.000136, MAE: 0.008233, R²: -0.0080
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.15422 | val 0.19950
  Epoch 020 - train 0.15228 | val 0.20130
  Regression -> MSE: 0.000193, MAE: 0.010454, R²: -0.0274
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.14426 | val 0.17123
  Epoch 020 - train 0.14065 | val 0.17063
  Regression -> MSE: 0.000281, MAE: 0.011194, R²: -0.0719
  Directional -> Accuracy: 0.4658, MCC: 0.0194, F1: 0.2642

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.14907 | val 0.12970
  Epoch 020 - train 0.14673 | val 0.12727
  Regression -> MSE: 0.000169, MAE: 0.010371, R²: -0.0111
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.14366 | val 0.16095
  Epoch 020 - train 0.13976 | val 0.16620
  Regression -> MSE: 0.000183, MAE: 0.010439, R²: -0.0168
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.14589 | val 0.14712
  Epoch 020 - train 0.14245 | val 0.14733
  Regression -> MSE: 0.000352, MAE: 0.012506, R²: -0.0280
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.16917 | val 0.10255
  Epoch 020 - train 0.17254 | val 0.10148
  Regression -> MSE: 0.000111, MAE: 0.008299, R²: -0.0514
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.15976 | val 0.21249
  Epoch 020 - train 0.15625 | val 0.21634
  Regression -> MSE: 0.000220, MAE: 0.011327, R²: -0.0053
  Directional -> Accuracy: 0.4737, MCC: -0.0101, F1: 0.6341

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.16081 | val 0.27126
  Epoch 020 - train 0.16102 | val 0.27020
  Regression -> MSE: 0.000082, MAE: 0.007039, R²: -0.0498
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.14947 | val 0.11705
  Epoch 020 - train 0.14444 | val 0.11791
  Regression -> MSE: 0.000310, MAE: 0.013957, R²: -0.0083
  Directional -> Accuracy: 0.6531, MCC: 0.1894, F1: 0.1053

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.17953 | val 0.09491
  Epoch 020 - train 0.17506 | val 0.09821
  Regression -> MSE: 0.000254, MAE: 0.011461, R²: -0.0436
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.15412 | val 0.18722
  Epoch 020 - train 0.15261 | val 0.18547
  Regression -> MSE: 0.000081, MAE: 0.007081, R²: -0.0015
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.16429 | val 0.20673
  Epoch 020 - train 0.16352 | val 0.22631
  Regression -> MSE: 0.000311, MAE: 0.014492, R²: -0.0126
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.15239 | val 0.16869
  Epoch 020 - train 0.14880 | val 0.16220
  Regression -> MSE: 0.000100, MAE: 0.007197, R²: -0.0173
  Directional -> Accuracy: 0.5000, MCC: -0.1676, F1: 0.6562

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.17399 | val 0.19107
  Epoch 020 - train 0.16631 | val 0.20127
  Regression -> MSE: 0.000177, MAE: 0.010282, R²: -0.0279
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.14185 | val 0.17303
  Epoch 020 - train 0.14320 | val 0.18248
  Regression -> MSE: 0.000222, MAE: 0.011503, R²: 0.0030
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.14704 | val 0.16877
  Epoch 020 - train 0.14910 | val 0.16795
  Regression -> MSE: 0.000108, MAE: 0.008361, R²: -0.1729
  Directional -> Accuracy: 0.3684, MCC: -0.2626, F1: 0.4545

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.16084 | val 0.25842
  Epoch 020 - train 0.15921 | val 0.27038
  Regression -> MSE: 0.000165, MAE: 0.010288, R²: -0.0085
  Directional -> Accuracy: 0.4815, MCC: 0.0000, F1: 0.0000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.15267 | val 0.19198
  Epoch 020 - train 0.14835 | val 0.19732
  Regression -> MSE: 0.000119, MAE: 0.008973, R²: -0.0271
  Directional -> Accuracy: 0.4821, MCC: -0.0519, F1: 0.5672

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.16162 | val 0.26377

[I 2026-02-23 02:04:41,104] Trial 188 finished with value: -0.011451786787162936 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 32, 'learning_rate': 5.435294433443804e-06, 'weight_decay': 4.04569927812623e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.2424027825409666, 'early_stopping_min_delta': 0.005623593796841272}. Best is trial 157 with value: -0.011387287234516647.

  Epoch 020 - train 0.15545 | val 0.30035
  Regression -> MSE: 0.000236, MAE: 0.012387, R²: 0.0035
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.10511 | val 0.13803
  Epoch 020 - train 0.10663 | val 0.13582
  Regression -> MSE: 0.000248, MAE: 0.012521, R²: 0.0001
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.10270 | val 0.12399
  Epoch 020 - train 0.09800 | val 0.12168
  Regression -> MSE: 0.000694, MAE: 0.019519, R²: -0.0145
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.10582 | val 0.16926
  Epoch 020 - train 0.10460 | val 0.16868
  Regression -> MSE: 0.000313, MAE: 0.014398, R²: -0.0092
  Directional -> Accuracy: 0.6170, MCC: 0.2800, F1: 0.7273

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.09575 | val 0.09140
  Epoch 020 - train 0.09265 | val 0.09335
  Regression -> MSE: 0.000350, MAE: 0.014590, R²: -0.0034
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.10752 | val 0.15102
  Epoch 020 - train 0.10315 | val 0.14959
  Regression -> MSE: 0.000204, MAE: 0.010165, R²: 0.0001
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.10196 | val 0.23587
  Epoch 020 - train 0.09865 | val 0.23202
  Regression -> MSE: 0.000586, MAE: 0.018687, R²: -0.0555
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.10648 | val 0.13039
  Epoch 020 - train 0.10502 | val 0.12457
  Regression -> MSE: 0.000246, MAE: 0.012146, R²: -0.0042
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.09914 | val 0.14762
  Epoch 020 - train 0.10197 | val 0.15605
  Regression -> MSE: 0.000641, MAE: 0.020111, R²: -0.0735
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.09412 | val 0.12466
  Epoch 020 - train 0.09024 | val 0.12444
  Regression -> MSE: 0.000390, MAE: 0.015900, R²: -0.0179
  Directional -> Accuracy: 0.6939, MCC: 0.3797, F1: 0.5946

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.09862 | val 0.12848
  Epoch 020 - train 0.09992 | val 0.12943
  Regression -> MSE: 0.000242, MAE: 0.011784, R²: -0.0029
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.10068 | val 0.14035
  Epoch 020 - train 0.09472 | val 0.14773
  Regression -> MSE: 0.000325, MAE: 0.013617, R²: -0.0464
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.10600 | val 0.11720
  Epoch 020 - train 0.10307 | val 0.12090
  Regression -> MSE: 0.000690, MAE: 0.019911, R²: -0.0195
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.10034 | val 0.12139
  Epoch 020 - train 0.09848 | val 0.12309
  Regression -> MSE: 0.000139, MAE: 0.009046, R²: -0.0059
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.09029 | val 0.13604
  Epoch 020 - train 0.09050 | val 0.13668
  Regression -> MSE: 0.000225, MAE: 0.010692, R²: -0.0018
  Directional -> Accuracy: 0.6066, MCC: 0.2297, F1: 0.5385

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.09928 | val 0.19781
  Epoch 020 - train 0.09786 | val 0.19924
  Regression -> MSE: 0.000361, MAE: 0.016107, R²: 0.0044
  Directional -> Accuracy: 0.5000, MCC: 0.1852, F1: 0.6486

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.10464 | val 0.11255
  Epoch 020 - train 0.10314 | val 0.11407
  Regression -> MSE: 0.000110, MAE: 0.008206, R²: -0.0217
  Directional -> Accuracy: 0.4571, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.10143 | val 0.16227
  Epoch 020 - train 0.09867 | val 0.16613
  Regression -> MSE: 0.000156, MAE: 0.009758, R²: -0.0038
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.10243 | val 0.10424
  Epoch 020 - train 0.10251 | val 0.10506
  Regression -> MSE: 0.000273, MAE: 0.012927, R²: -0.0021
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.09133 | val 0.13453
  Epoch 020 - train 0.09107 | val 0.13380
  Regression -> MSE: 0.000151, MAE: 0.008753, R²: -0.0108
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.10293 | val 0.15728
  Epoch 020 - train 0.10129 | val 0.15338
  Regression -> MSE: 0.000243, MAE: 0.011147, R²: -0.0757
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.10064 | val 0.14189
  Epoch 020 - train 0.09802 | val 0.14219
  Regression -> MSE: 0.000150, MAE: 0.008665, R²: -0.0445
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.10197 | val 0.11999
  Epoch 020 - train 0.09734 | val 0.12021
  Regression -> MSE: 0.000165, MAE: 0.010559, R²: 0.0008
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.10674 | val 0.12022
  Epoch 020 - train 0.10363 | val 0.12091
  Regression -> MSE: 0.000093, MAE: 0.007467, R²: -0.0971
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.10173 | val 0.12523
  Epoch 020 - train 0.10163 | val 0.13370
  Regression -> MSE: 0.000212, MAE: 0.011181, R²: 0.0007
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.09596 | val 0.09145
  Epoch 020 - train 0.09403 | val 0.09004
  Regression -> MSE: 0.000097, MAE: 0.008080, R²: -0.0552
  Directional -> Accuracy: 0.5536, MCC: 0.0299, F1: 0.6988

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.10684 | val 0.08467
  Epoch 020 - train 0.10238 | val 0.08407
  Regression -> MSE: 0.000112, MAE: 0.009085, R²: -0.0824
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.11500 | val 0.16183
  Epoch 020 - train 0.10988 | val 0.16736
  Regression -> MSE: 0.000234, MAE: 0.012657, R²: -0.0121
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.10015 | val 0.11609
  Epoch 020 - train 0.09782 | val 0.11563
  Regression -> MSE: 0.000191, MAE: 0.008107, R²: -0.1467
  Directional -> Accuracy: 0.5263, MCC: 0.1125, F1: 0.4490

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.10890 | val 0.09597
  Epoch 020 - train 0.10975 | val 0.10627
  Regression -> MSE: 0.000239, MAE: 0.011964, R²: -0.0108
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.10261 | val 0.17739
  Epoch 020 - train 0.10188 | val 0.17911
  Regression -> MSE: 0.000235, MAE: 0.010134, R²: -0.0190
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.10117 | val 0.11530
  Epoch 020 - train 0.10978 | val 0.11548
  Regression -> MSE: 0.000138, MAE: 0.008431, R²: -0.0226
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.10273 | val 0.12698
  Epoch 020 - train 0.09824 | val 0.12751
  Regression -> MSE: 0.000198, MAE: 0.010658, R²: -0.0512
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.08942 | val 0.11604
  Epoch 020 - train 0.08779 | val 0.11456
  Regression -> MSE: 0.000264, MAE: 0.010515, R²: -0.0089
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.09373 | val 0.08709
  Epoch 020 - train 0.09561 | val 0.08890
  Regression -> MSE: 0.000168, MAE: 0.010364, R²: -0.0081
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.09843 | val 0.11337
  Epoch 020 - train 0.09653 | val 0.11131
  Regression -> MSE: 0.000181, MAE: 0.010316, R²: -0.0065
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.09825 | val 0.09709
  Epoch 020 - train 0.09389 | val 0.09612
  Regression -> MSE: 0.000345, MAE: 0.012097, R²: -0.0061
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.10797 | val 0.06538
  Epoch 020 - train 0.10870 | val 0.06635
  Regression -> MSE: 0.000110, MAE: 0.008308, R²: -0.0462
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.10713 | val 0.14807
  Epoch 020 - train 0.10404 | val 0.14222
  Regression -> MSE: 0.000223, MAE: 0.011426, R²: -0.0188
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.10028 | val 0.17155
  Epoch 020 - train 0.09846 | val 0.17358
  Regression -> MSE: 0.000085, MAE: 0.007209, R²: -0.0974
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.09971 | val 0.08102
  Epoch 020 - train 0.09792 | val 0.07825
  Regression -> MSE: 0.000428, MAE: 0.017882, R²: -0.3910
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.10651 | val 0.06937
  Epoch 020 - train 0.11170 | val 0.08283
  Regression -> MSE: 0.000261, MAE: 0.011510, R²: -0.0723
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.11356 | val 0.17332
  Epoch 020 - train 0.11074 | val 0.17294
  Regression -> MSE: 0.000087, MAE: 0.007093, R²: -0.0744
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.10045 | val 0.12579
  Epoch 020 - train 0.10342 | val 0.12631
  Regression -> MSE: 0.000311, MAE: 0.014527, R²: -0.0122
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.10388 | val 0.12467
  Epoch 020 - train 0.09794 | val 0.13217
  Regression -> MSE: 0.000101, MAE: 0.007105, R²: -0.0300
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.10380 | val 0.12713
  Epoch 020 - train 0.10404 | val 0.12936
  Regression -> MSE: 0.000172, MAE: 0.009752, R²: -0.0016
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.09712 | val 0.12163
  Epoch 020 - train 0.09383 | val 0.11937
  Regression -> MSE: 0.000231, MAE: 0.011922, R²: -0.0375
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.09758 | val 0.11124
  Epoch 020 - train 0.09735 | val 0.11125
  Regression -> MSE: 0.000093, MAE: 0.007671, R²: -0.0044
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.10418 | val 0.15615
  Epoch 020 - train 0.10582 | val 0.15803
  Regression -> MSE: 0.000164, MAE: 0.010247, R²: -0.0015
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.10161 | val 0.14398
  Epoch 020 - train 0.09662 | val 0.14324
  Regression -> MSE: 0.000124, MAE: 0.009019, R²: -0.0725
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.10483 | val 0.13819

[I 2026-02-23 02:08:30,934] Trial 189 finished with value: -0.011526584651086256 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 16, 'learning_rate': 7.404030361043481e-06, 'weight_decay': 0.00020387657688901223, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.1497765804530154, 'early_stopping_min_delta': 0.004827624958138064}. Best is trial 157 with value: -0.011387287234516647.

  Epoch 020 - train 0.10425 | val 0.13737
  Regression -> MSE: 0.000237, MAE: 0.012393, R²: 0.0027
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.14019 | val 0.18612
  Epoch 020 - train 0.13696 | val 0.18587
  Regression -> MSE: 0.000245, MAE: 0.012486, R²: 0.0092
  Directional -> Accuracy: 0.4675, MCC: -0.0664, F1: 0.4384

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.13870 | val 0.13727
  Epoch 020 - train 0.13647 | val 0.14452
  Regression -> MSE: 0.000693, MAE: 0.019491, R²: -0.0128
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.14951 | val 0.23460
  Epoch 020 - train 0.14461 | val 0.23248
  Regression -> MSE: 0.000329, MAE: 0.014615, R²: -0.0590
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.12339 | val 0.22049
  Epoch 020 - train 0.12522 | val 0.23802
  Regression -> MSE: 0.000362, MAE: 0.014810, R²: -0.0361
  Directional -> Accuracy: 0.4267, MCC: -0.1818, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.15043 | val 0.14452
  Epoch 020 - train 0.14193 | val 0.15206
  Regression -> MSE: 0.000203, MAE: 0.010090, R²: 0.0028
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.13711 | val 0.26472
  Epoch 020 - train 0.13535 | val 0.26239
  Regression -> MSE: 0.000559, MAE: 0.018158, R²: -0.0072
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.14614 | val 0.17821
  Epoch 020 - train 0.14608 | val 0.17840
  Regression -> MSE: 0.000250, MAE: 0.011955, R²: -0.0167
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.14890 | val 0.16771
  Epoch 020 - train 0.14855 | val 0.15727
  Regression -> MSE: 0.000612, MAE: 0.019324, R²: -0.0237
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.13191 | val 0.17502
  Epoch 020 - train 0.13546 | val 0.16224
  Regression -> MSE: 0.000425, MAE: 0.016515, R²: -0.1075
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.14883 | val 0.20253
  Epoch 020 - train 0.14450 | val 0.20999
  Regression -> MSE: 0.000248, MAE: 0.011645, R²: -0.0252
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.13044 | val 0.20032
  Epoch 020 - train 0.13129 | val 0.20081
  Regression -> MSE: 0.000313, MAE: 0.013617, R²: -0.0059
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.14365 | val 0.17751
  Epoch 020 - train 0.14695 | val 0.19195
  Regression -> MSE: 0.000685, MAE: 0.019803, R²: -0.0117
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.15036 | val 0.16853
  Epoch 020 - train 0.14794 | val 0.21334
  Regression -> MSE: 0.000139, MAE: 0.009019, R²: -0.0065
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.13228 | val 0.17994
  Epoch 020 - train 0.13358 | val 0.17723
  Regression -> MSE: 0.000218, MAE: 0.010705, R²: 0.0296
  Directional -> Accuracy: 0.4918, MCC: -0.0721, F1: 0.6517

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.13968 | val 0.29391
  Epoch 020 - train 0.13844 | val 0.30481
  Regression -> MSE: 0.000362, MAE: 0.016153, R²: -0.0002
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.14925 | val 0.14522
  Epoch 020 - train 0.14348 | val 0.15032
  Regression -> MSE: 0.000108, MAE: 0.007942, R²: 0.0023
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.13995 | val 0.25549
  Epoch 020 - train 0.13735 | val 0.28214
  Regression -> MSE: 0.000161, MAE: 0.010130, R²: -0.0310
  Directional -> Accuracy: 0.4576, MCC: -0.0832, F1: 0.5152

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.14420 | val 0.14523
  Epoch 020 - train 0.14247 | val 0.14706
  Regression -> MSE: 0.000273, MAE: 0.012947, R²: -0.0020
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.12825 | val 0.18073
  Epoch 020 - train 0.12619 | val 0.17999
  Regression -> MSE: 0.000284, MAE: 0.013435, R²: -0.8970
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.14735 | val 0.20340
  Epoch 020 - train 0.14180 | val 0.20651
  Regression -> MSE: 0.000227, MAE: 0.010888, R²: -0.0020
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.15063 | val 0.17483
  Epoch 020 - train 0.14174 | val 0.17555
  Regression -> MSE: 0.000150, MAE: 0.008710, R²: -0.0482
  Directional -> Accuracy: 0.5833, MCC: -0.1615, F1: 0.7368

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.13437 | val 0.17221
  Epoch 020 - train 0.13329 | val 0.17518
  Regression -> MSE: 0.000169, MAE: 0.010263, R²: -0.0257
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.14438 | val 0.16379
  Epoch 020 - train 0.14462 | val 0.16407
  Regression -> MSE: 0.000095, MAE: 0.007481, R²: -0.1122
  Directional -> Accuracy: 0.5000, MCC: 0.1008, F1: 0.3556

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.14991 | val 0.17530
  Epoch 020 - train 0.14452 | val 0.17807
  Regression -> MSE: 0.000216, MAE: 0.011045, R²: -0.0186
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.12924 | val 0.12166
  Epoch 020 - train 0.12877 | val 0.11948
  Regression -> MSE: 0.000098, MAE: 0.008170, R²: -0.0604
  Directional -> Accuracy: 0.5357, MCC: 0.1020, F1: 0.5000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.14268 | val 0.11781
  Epoch 020 - train 0.14080 | val 0.13014
  Regression -> MSE: 0.000112, MAE: 0.009095, R²: -0.0854
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.15002 | val 0.13903
  Epoch 020 - train 0.14637 | val 0.15036
  Regression -> MSE: 0.000234, MAE: 0.012637, R²: -0.0106
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.13814 | val 0.17168
  Epoch 020 - train 0.13924 | val 0.17293
  Regression -> MSE: 0.000182, MAE: 0.007989, R²: -0.0929
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.15204 | val 0.11980
  Epoch 020 - train 0.14525 | val 0.12015
  Regression -> MSE: 0.000237, MAE: 0.011892, R²: -0.0038
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.14657 | val 0.22328
  Epoch 020 - train 0.14773 | val 0.22239
  Regression -> MSE: 0.000231, MAE: 0.009886, R²: -0.0021
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.14766 | val 0.16890
  Epoch 020 - train 0.14795 | val 0.16927
  Regression -> MSE: 0.000136, MAE: 0.008250, R²: -0.0060
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.14520 | val 0.18266
  Epoch 020 - train 0.14295 | val 0.18059
  Regression -> MSE: 0.000188, MAE: 0.010465, R²: 0.0001
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.12022 | val 0.15609
  Epoch 020 - train 0.12235 | val 0.15560
  Regression -> MSE: 0.000269, MAE: 0.010608, R²: -0.0285
  Directional -> Accuracy: 0.5342, MCC: 0.0144, F1: 0.6383

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.13049 | val 0.12002
  Epoch 020 - train 0.13281 | val 0.11681
  Regression -> MSE: 0.000167, MAE: 0.010375, R²: -0.0018
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.13068 | val 0.14616
  Epoch 020 - train 0.13016 | val 0.14353
  Regression -> MSE: 0.000200, MAE: 0.010975, R²: -0.1124
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.13144 | val 0.13643
  Epoch 020 - train 0.13080 | val 0.13848
  Regression -> MSE: 0.000343, MAE: 0.011983, R²: -0.0013
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.14811 | val 0.09254
  Epoch 020 - train 0.14384 | val 0.09672
  Regression -> MSE: 0.000114, MAE: 0.008316, R²: -0.0848
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.14398 | val 0.18776
  Epoch 020 - train 0.14156 | val 0.18941
  Regression -> MSE: 0.000219, MAE: 0.011311, R²: -0.0018
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.14247 | val 0.26158
  Epoch 020 - train 0.14013 | val 0.30309
  Regression -> MSE: 0.000083, MAE: 0.007119, R²: -0.0723
  Directional -> Accuracy: 0.5532, MCC: 0.0240, F1: 0.6557

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.13674 | val 0.10339
  Epoch 020 - train 0.13651 | val 0.09829
  Regression -> MSE: 0.000331, MAE: 0.015135, R²: -0.0759
  Directional -> Accuracy: 0.4286, MCC: 0.1946, F1: 0.5625

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.14831 | val 0.08752
  Epoch 020 - train 0.15537 | val 0.09738
  Regression -> MSE: 0.000245, MAE: 0.011565, R²: -0.0033
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.0000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.13511 | val 0.18064
  Epoch 020 - train 0.13394 | val 0.18385
  Regression -> MSE: 0.000084, MAE: 0.007046, R²: -0.0355
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.14080 | val 0.17854
  Epoch 020 - train 0.14098 | val 0.18200
  Regression -> MSE: 0.000308, MAE: 0.014474, R²: -0.0030
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.13185 | val 0.14760
  Epoch 020 - train 0.13408 | val 0.14882
  Regression -> MSE: 0.000098, MAE: 0.007352, R²: -0.0011
  Directional -> Accuracy: 0.4318, MCC: 0.0000, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.15587 | val 0.17213
  Epoch 020 - train 0.15398 | val 0.17507
  Regression -> MSE: 0.000173, MAE: 0.009480, R²: -0.0064
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.13468 | val 0.16378
  Epoch 020 - train 0.12860 | val 0.16680
  Regression -> MSE: 0.000223, MAE: 0.011771, R²: -0.0002
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.14510 | val 0.15680
  Epoch 020 - train 0.14811 | val 0.15422
  Regression -> MSE: 0.000093, MAE: 0.007647, R²: -0.0025
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.14475 | val 0.22850
  Epoch 020 - train 0.14700 | val 0.23218
  Regression -> MSE: 0.000168, MAE: 0.010301, R²: -0.0250
  Directional -> Accuracy: 0.4815, MCC: 0.0000, F1: 0.0000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.13948 | val 0.17122
  Epoch 020 - train 0.13987 | val 0.17049
  Regression -> MSE: 0.000131, MAE: 0.009138, R²: -0.1341
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.14110 | val 0.20057

[I 2026-02-23 02:11:06,522] Trial 190 finished with value: -0.0115318147434427 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 32, 'learning_rate': 5.3124904665653635e-06, 'weight_decay': 6.73430573348729e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.21644564927475002, 'early_stopping_min_delta': 0.0055198442421715834}. Best is trial 157 with value: -0.011387287234516647.

  Epoch 020 - train 0.13944 | val 0.20232
  Regression -> MSE: 0.000237, MAE: 0.012384, R²: 0.0011
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.12777 | val 0.19491
  Epoch 020 - train 0.12439 | val 0.19477
  Regression -> MSE: 0.000256, MAE: 0.012882, R²: -0.0343
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.13253 | val 0.11538
  Epoch 020 - train 0.13303 | val 0.11488
  Regression -> MSE: 0.000722, MAE: 0.019981, R²: -0.0540
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.12429 | val 0.20269
  Epoch 020 - train 0.12997 | val 0.20104
  Regression -> MSE: 0.000320, MAE: 0.014502, R²: -0.0299
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.11595 | val 0.20460
  Epoch 020 - train 0.11485 | val 0.22223
  Regression -> MSE: 0.000366, MAE: 0.014836, R²: -0.0486
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.12418 | val 0.12124
  Epoch 020 - train 0.12439 | val 0.12057
  Regression -> MSE: 0.000204, MAE: 0.010123, R²: -0.0022
  Directional -> Accuracy: 0.5490, MCC: 0.2223, F1: 0.3030

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.12153 | val 0.24203
  Epoch 020 - train 0.12014 | val 0.28737
  Regression -> MSE: 0.000587, MAE: 0.018714, R²: -0.0582
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.13061 | val 0.15388
  Epoch 020 - train 0.12836 | val 0.15005
  Regression -> MSE: 0.000245, MAE: 0.012464, R²: 0.0006
  Directional -> Accuracy: 0.4783, MCC: 0.0778, F1: 0.5610

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.12420 | val 0.15482
  Epoch 020 - train 0.12002 | val 0.19562
  Regression -> MSE: 0.000606, MAE: 0.019370, R²: -0.0146
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.12104 | val 0.14894
  Epoch 020 - train 0.11485 | val 0.14967
  Regression -> MSE: 0.000398, MAE: 0.016022, R²: -0.0380
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.12765 | val 0.17716
  Epoch 020 - train 0.13051 | val 0.18329
  Regression -> MSE: 0.000244, MAE: 0.011650, R²: -0.0110
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.11474 | val 0.17658
  Epoch 020 - train 0.11439 | val 0.17243
  Regression -> MSE: 0.000319, MAE: 0.013579, R²: -0.0268
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.13071 | val 0.14887
  Epoch 020 - train 0.12740 | val 0.15150
  Regression -> MSE: 0.000676, MAE: 0.019467, R²: 0.0012
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.12882 | val 0.13569
  Epoch 020 - train 0.12718 | val 0.14307
  Regression -> MSE: 0.000138, MAE: 0.009045, R²: -0.0005
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.12497 | val 0.16427
  Epoch 020 - train 0.12126 | val 0.16783
  Regression -> MSE: 0.000232, MAE: 0.010940, R²: -0.0300
  Directional -> Accuracy: 0.4918, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.12684 | val 0.25227
  Epoch 020 - train 0.12242 | val 0.25186
  Regression -> MSE: 0.000362, MAE: 0.016103, R²: 0.0001
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.13492 | val 0.15108
  Epoch 020 - train 0.13507 | val 0.15190
  Regression -> MSE: 0.000110, MAE: 0.008185, R²: -0.0185
  Directional -> Accuracy: 0.4571, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.12541 | val 0.24791
  Epoch 020 - train 0.12374 | val 0.27152
  Regression -> MSE: 0.000156, MAE: 0.009661, R²: -0.0012
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.12771 | val 0.13926
  Epoch 020 - train 0.12544 | val 0.13792
  Regression -> MSE: 0.000273, MAE: 0.012956, R²: -0.0043
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.11595 | val 0.16486
  Epoch 020 - train 0.11341 | val 0.16514
  Regression -> MSE: 0.000151, MAE: 0.008749, R²: -0.0066
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.12707 | val 0.17377
  Epoch 020 - train 0.12416 | val 0.17354
  Regression -> MSE: 0.000239, MAE: 0.011217, R²: -0.0584
  Directional -> Accuracy: 0.4000, MCC: -0.1791, F1: 0.3077

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.12552 | val 0.16062
  Epoch 020 - train 0.12548 | val 0.17257
  Regression -> MSE: 0.000149, MAE: 0.008628, R²: -0.0366
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.11786 | val 0.14689
  Epoch 020 - train 0.11462 | val 0.14755
  Regression -> MSE: 0.000168, MAE: 0.010245, R²: -0.0174
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.13018 | val 0.15672
  Epoch 020 - train 0.12968 | val 0.15846
  Regression -> MSE: 0.000086, MAE: 0.007031, R²: -0.0054
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.12027 | val 0.15022
  Epoch 020 - train 0.11896 | val 0.14935
  Regression -> MSE: 0.000212, MAE: 0.011189, R²: -0.0015
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.11328 | val 0.10844
  Epoch 020 - train 0.11210 | val 0.10651
  Regression -> MSE: 0.000097, MAE: 0.008061, R²: -0.0493
  Directional -> Accuracy: 0.5536, MCC: 0.1446, F1: 0.5098

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.12222 | val 0.09739
  Epoch 020 - train 0.12343 | val 0.09665
  Regression -> MSE: 0.000107, MAE: 0.008918, R²: -0.0362
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.12900 | val 0.11893
  Epoch 020 - train 0.13130 | val 0.12740
  Regression -> MSE: 0.000232, MAE: 0.012580, R²: -0.0030
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.12529 | val 0.15025
  Epoch 020 - train 0.12456 | val 0.14779
  Regression -> MSE: 0.000171, MAE: 0.007846, R²: -0.0274
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.12377 | val 0.10596
  Epoch 020 - train 0.12751 | val 0.10489
  Regression -> MSE: 0.000237, MAE: 0.011863, R²: -0.0002
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.12729 | val 0.19300
  Epoch 020 - train 0.12600 | val 0.19941
  Regression -> MSE: 0.000230, MAE: 0.009869, R²: 0.0015
  Directional -> Accuracy: 0.4651, MCC: -0.1579, F1: 0.6349

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.12852 | val 0.14611
  Epoch 020 - train 0.12897 | val 0.14400
  Regression -> MSE: 0.000134, MAE: 0.008206, R²: 0.0083
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.12638 | val 0.15575
  Epoch 020 - train 0.12416 | val 0.15412
  Regression -> MSE: 0.000238, MAE: 0.012199, R²: -0.2660
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.11773 | val 0.15425
  Epoch 020 - train 0.11620 | val 0.15439
  Regression -> MSE: 0.000275, MAE: 0.010780, R²: -0.0485
  Directional -> Accuracy: 0.4384, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.13082 | val 0.11409
  Epoch 020 - train 0.12195 | val 0.11234
  Regression -> MSE: 0.000170, MAE: 0.010383, R²: -0.0204
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.11992 | val 0.14078
  Epoch 020 - train 0.12347 | val 0.17968
  Regression -> MSE: 0.000181, MAE: 0.010363, R²: -0.0049
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.11589 | val 0.11818
  Epoch 020 - train 0.11535 | val 0.11810
  Regression -> MSE: 0.000350, MAE: 0.012368, R²: -0.0209
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.13670 | val 0.08047
  Epoch 020 - train 0.13225 | val 0.08081
  Regression -> MSE: 0.000121, MAE: 0.008374, R²: -0.1472
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.12928 | val 0.17097
  Epoch 020 - train 0.12708 | val 0.16976
  Regression -> MSE: 0.000223, MAE: 0.011426, R²: -0.0203
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.12479 | val 0.21422
  Epoch 020 - train 0.12223 | val 0.22000
  Regression -> MSE: 0.000089, MAE: 0.007385, R²: -0.1468
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.12630 | val 0.10854
  Epoch 020 - train 0.12919 | val 0.10568
  Regression -> MSE: 0.000325, MAE: 0.014802, R²: -0.0573
  Directional -> Accuracy: 0.3469, MCC: -0.1894, F1: 0.5152

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.13924 | val 0.07672
  Epoch 020 - train 0.13603 | val 0.08524
  Regression -> MSE: 0.000246, MAE: 0.011562, R²: -0.0101
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.0000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.12117 | val 0.15683
  Epoch 020 - train 0.12116 | val 0.15541
  Regression -> MSE: 0.000082, MAE: 0.007058, R²: -0.0160
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.12838 | val 0.16419
  Epoch 020 - train 0.12360 | val 0.17090
  Regression -> MSE: 0.000310, MAE: 0.014494, R²: -0.0105
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.11306 | val 0.14340
  Epoch 020 - train 0.11649 | val 0.14601
  Regression -> MSE: 0.000100, MAE: 0.007119, R²: -0.0218
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.13649 | val 0.15467
  Epoch 020 - train 0.13162 | val 0.17234
  Regression -> MSE: 0.000177, MAE: 0.010316, R²: -0.0313
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.11724 | val 0.14212
  Epoch 020 - train 0.11740 | val 0.14184
  Regression -> MSE: 0.000225, MAE: 0.011780, R²: -0.0108
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.12437 | val 0.15656
  Epoch 020 - train 0.12031 | val 0.16805
  Regression -> MSE: 0.000094, MAE: 0.007764, R²: -0.0204
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.13944 | val 0.28467
  Epoch 020 - train 0.13501 | val 0.35333
  Regression -> MSE: 0.000169, MAE: 0.010303, R²: -0.0339
  Directional -> Accuracy: 0.4815, MCC: 0.0000, F1: 0.0000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.12470 | val 0.14996
  Epoch 020 - train 0.12281 | val 0.15050
  Regression -> MSE: 0.000125, MAE: 0.009018, R²: -0.0765
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.12297 | val 0.17228

[I 2026-02-23 02:13:42,541] Trial 191 finished with value: -0.011494691790775209 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 32, 'learning_rate': 4.1695780303833925e-06, 'weight_decay': 3.584004533815451e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.18620179498955264, 'early_stopping_min_delta': 0.0047029048272136395}. Best is trial 157 with value: -0.011387287234516647.

  Epoch 020 - train 0.12627 | val 0.17282
  Regression -> MSE: 0.000238, MAE: 0.012358, R²: -0.0036
  Directional -> Accuracy: 0.4754, MCC: -0.0130, F1: 0.6279

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.11654 | val 0.14999
  Epoch 020 - train 0.11090 | val 0.15062
  Regression -> MSE: 0.000247, MAE: 0.012518, R²: 0.0004
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.11069 | val 0.10553
  Epoch 020 - train 0.10694 | val 0.10744
  Regression -> MSE: 0.000686, MAE: 0.019348, R²: -0.0015
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.11701 | val 0.18289
  Epoch 020 - train 0.11542 | val 0.18578
  Regression -> MSE: 0.000310, MAE: 0.014398, R²: 0.0002
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.10300 | val 0.15977
  Epoch 020 - train 0.09980 | val 0.14102
  Regression -> MSE: 0.000349, MAE: 0.014570, R²: 0.0003
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.11553 | val 0.11875
  Epoch 020 - train 0.11014 | val 0.12385
  Regression -> MSE: 0.000206, MAE: 0.010443, R²: -0.0134
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.10465 | val 0.20607
  Epoch 020 - train 0.10355 | val 0.23329
  Regression -> MSE: 0.000560, MAE: 0.018241, R²: -0.0094
  Directional -> Accuracy: 0.5106, MCC: 0.0045, F1: 0.0800

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.11635 | val 0.13768
  Epoch 020 - train 0.11556 | val 0.13679
  Regression -> MSE: 0.000246, MAE: 0.012169, R²: -0.0019
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.11472 | val 0.13950
  Epoch 020 - train 0.11693 | val 0.15298
  Regression -> MSE: 0.000610, MAE: 0.019484, R²: -0.0214
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.11143 | val 0.13913
  Epoch 020 - train 0.10807 | val 0.13607
  Regression -> MSE: 0.000386, MAE: 0.016048, R²: -0.0068
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.10955 | val 0.14724
  Epoch 020 - train 0.10981 | val 0.14903
  Regression -> MSE: 0.000242, MAE: 0.012107, R²: -0.0043
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.10556 | val 0.17195
  Epoch 020 - train 0.10617 | val 0.18273
  Regression -> MSE: 0.000311, MAE: 0.013790, R²: 0.0005
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.6301

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.11782 | val 0.13132
  Epoch 020 - train 0.11796 | val 0.13231
  Regression -> MSE: 0.000687, MAE: 0.019857, R²: -0.0139
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.11665 | val 0.11628
  Epoch 020 - train 0.11235 | val 0.12127
  Regression -> MSE: 0.000139, MAE: 0.009040, R²: -0.0028
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.10566 | val 0.15204
  Epoch 020 - train 0.10426 | val 0.15386
  Regression -> MSE: 0.000225, MAE: 0.010713, R²: -0.0005
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.10926 | val 0.22574
  Epoch 020 - train 0.11004 | val 0.22619
  Regression -> MSE: 0.000372, MAE: 0.015930, R²: -0.0276
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.11669 | val 0.11677
  Epoch 020 - train 0.11750 | val 0.11633
  Regression -> MSE: 0.000109, MAE: 0.008123, R²: -0.0082
  Directional -> Accuracy: 0.4571, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.10968 | val 0.20332
  Epoch 020 - train 0.10800 | val 0.21776
  Regression -> MSE: 0.000161, MAE: 0.010124, R²: -0.0306
  Directional -> Accuracy: 0.4746, MCC: -0.0570, F1: 0.5373

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.11494 | val 0.13597
  Epoch 020 - train 0.11507 | val 0.14030
  Regression -> MSE: 0.000274, MAE: 0.013102, R²: -0.0054
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.10225 | val 0.15054
  Epoch 020 - train 0.10278 | val 0.14942
  Regression -> MSE: 0.000163, MAE: 0.009023, R²: -0.0916
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.11746 | val 0.16214
  Epoch 020 - train 0.11581 | val 0.15999
  Regression -> MSE: 0.000226, MAE: 0.010903, R²: -0.0006
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.11813 | val 0.13870
  Epoch 020 - train 0.11308 | val 0.15518
  Regression -> MSE: 0.000143, MAE: 0.008303, R²: 0.0014
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.11613 | val 0.16379
  Epoch 020 - train 0.11323 | val 0.16678
  Regression -> MSE: 0.000165, MAE: 0.010497, R²: 0.0022
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.11307 | val 0.13296
  Epoch 020 - train 0.11630 | val 0.13368
  Regression -> MSE: 0.000086, MAE: 0.007088, R²: -0.0104
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.11246 | val 0.14582
  Epoch 020 - train 0.11280 | val 0.14804
  Regression -> MSE: 0.000213, MAE: 0.011098, R²: -0.0034
  Directional -> Accuracy: 0.4545, MCC: -0.1149, F1: 0.3333

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.10614 | val 0.10501
  Epoch 020 - train 0.10448 | val 0.10510
  Regression -> MSE: 0.000094, MAE: 0.008097, R²: -0.0202
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.11666 | val 0.09585
  Epoch 020 - train 0.11954 | val 0.10191
  Regression -> MSE: 0.000114, MAE: 0.009143, R²: -0.1013
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.11961 | val 0.10748
  Epoch 020 - train 0.11950 | val 0.10724
  Regression -> MSE: 0.000232, MAE: 0.012576, R²: -0.0040
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.10797 | val 0.13439
  Epoch 020 - train 0.10922 | val 0.13300
  Regression -> MSE: 0.000174, MAE: 0.007857, R²: -0.0429
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.11884 | val 0.09594
  Epoch 020 - train 0.11618 | val 0.11179
  Regression -> MSE: 0.000237, MAE: 0.011885, R²: -0.0032
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.11080 | val 0.17885
  Epoch 020 - train 0.11352 | val 0.18445
  Regression -> MSE: 0.000231, MAE: 0.009931, R²: -0.0013
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.12287 | val 0.13039
  Epoch 020 - train 0.12157 | val 0.12439
  Regression -> MSE: 0.000137, MAE: 0.008255, R²: -0.0121
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.11714 | val 0.14480
  Epoch 020 - train 0.11893 | val 0.14323
  Regression -> MSE: 0.000188, MAE: 0.010447, R²: -0.0009
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.10404 | val 0.13275
  Epoch 020 - train 0.09945 | val 0.13147
  Regression -> MSE: 0.000278, MAE: 0.010870, R²: -0.0612
  Directional -> Accuracy: 0.4384, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.10489 | val 0.09551
  Epoch 020 - train 0.09926 | val 0.09753
  Regression -> MSE: 0.000166, MAE: 0.010360, R²: 0.0050
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.10551 | val 0.11356
  Epoch 020 - train 0.10802 | val 0.11439
  Regression -> MSE: 0.000181, MAE: 0.010280, R²: -0.0058
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.10899 | val 0.11165
  Epoch 020 - train 0.10469 | val 0.11329
  Regression -> MSE: 0.000352, MAE: 0.012591, R²: -0.0288
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.12510 | val 0.07554
  Epoch 020 - train 0.12190 | val 0.07424
  Regression -> MSE: 0.000111, MAE: 0.008340, R²: -0.0565
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.11563 | val 0.15145
  Epoch 020 - train 0.11765 | val 0.15180
  Regression -> MSE: 0.000219, MAE: 0.011323, R²: -0.0027
  Directional -> Accuracy: 0.5263, MCC: 0.0145, F1: 0.1290

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.12272 | val 0.19835
  Epoch 020 - train 0.11612 | val 0.20656
  Regression -> MSE: 0.000082, MAE: 0.007074, R²: -0.0604
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.11830 | val 0.08631
  Epoch 020 - train 0.11750 | val 0.09226
  Regression -> MSE: 0.000308, MAE: 0.013742, R²: -0.0024
  Directional -> Accuracy: 0.6327, MCC: 0.0000, F1: 0.0000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.12599 | val 0.07381
  Epoch 020 - train 0.11972 | val 0.07357
  Regression -> MSE: 0.000260, MAE: 0.011492, R²: -0.0674
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.11463 | val 0.13814
  Epoch 020 - train 0.11185 | val 0.13878
  Regression -> MSE: 0.000082, MAE: 0.007054, R²: -0.0146
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.11588 | val 0.14648
  Epoch 020 - train 0.11779 | val 0.13517
  Regression -> MSE: 0.000310, MAE: 0.014462, R²: -0.0092
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.11397 | val 0.13270
  Epoch 020 - train 0.11421 | val 0.13553
  Regression -> MSE: 0.000101, MAE: 0.007110, R²: -0.0264
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.12168 | val 0.13248
  Epoch 020 - train 0.12154 | val 0.12868
  Regression -> MSE: 0.000174, MAE: 0.010051, R²: -0.0122
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.10718 | val 0.12465
  Epoch 020 - train 0.10723 | val 0.12912
  Regression -> MSE: 0.000224, MAE: 0.011796, R²: -0.0057
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.11025 | val 0.12662
  Epoch 020 - train 0.11309 | val 0.12819
  Regression -> MSE: 0.000094, MAE: 0.007723, R²: -0.0142
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.12193 | val 0.18343
  Epoch 020 - train 0.11833 | val 0.19193
  Regression -> MSE: 0.000167, MAE: 0.010312, R²: -0.0224
  Directional -> Accuracy: 0.4815, MCC: 0.0000, F1: 0.0000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.11347 | val 0.15327
  Epoch 020 - train 0.11158 | val 0.15685
  Regression -> MSE: 0.000117, MAE: 0.008939, R²: -0.0100
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.12187 | val 0.15894

[I 2026-02-23 02:16:18,232] Trial 192 finished with value: -0.011419356092631379 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 32, 'learning_rate': 3.4198657461532195e-06, 'weight_decay': 4.50794953757194e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.1676519349372728, 'early_stopping_min_delta': 0.006731161652447149}. Best is trial 157 with value: -0.011387287234516647.

  Epoch 020 - train 0.11770 | val 0.16192
  Regression -> MSE: 0.000241, MAE: 0.012337, R²: -0.0165
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.10355 | val 0.16255
  Epoch 020 - train 0.10169 | val 0.16363
  Regression -> MSE: 0.000264, MAE: 0.013101, R²: -0.0663
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.10775 | val 0.10081
  Epoch 020 - train 0.10652 | val 0.13746
  Regression -> MSE: 0.000723, MAE: 0.019998, R²: -0.0555
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.10451 | val 0.16101
  Epoch 020 - train 0.10164 | val 0.15764
  Regression -> MSE: 0.000326, MAE: 0.014557, R²: -0.0495
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.08439 | val 0.12170
  Epoch 020 - train 0.08495 | val 0.14038
  Regression -> MSE: 0.000349, MAE: 0.014547, R²: 0.0017
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.10640 | val 0.09684
  Epoch 020 - train 0.10029 | val 0.09439
  Regression -> MSE: 0.000217, MAE: 0.010730, R²: -0.0638
  Directional -> Accuracy: 0.5294, MCC: 0.1007, F1: 0.4000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.09622 | val 0.18936
  Epoch 020 - train 0.09365 | val 0.23779
  Regression -> MSE: 0.000569, MAE: 0.018342, R²: -0.0257
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.10234 | val 0.11902
  Epoch 020 - train 0.10093 | val 0.11850
  Regression -> MSE: 0.000245, MAE: 0.011944, R²: 0.0002
  Directional -> Accuracy: 0.6087, MCC: 0.1753, F1: 0.4906

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.10449 | val 0.11815
  Epoch 020 - train 0.10080 | val 0.12445
  Regression -> MSE: 0.000605, MAE: 0.019346, R²: -0.0120
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.09417 | val 0.11663
  Epoch 020 - train 0.09531 | val 0.11835
  Regression -> MSE: 0.000399, MAE: 0.016045, R²: -0.0408
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.09919 | val 0.12557
  Epoch 020 - train 0.09184 | val 0.12727
  Regression -> MSE: 0.000241, MAE: 0.011920, R²: 0.0002
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.09416 | val 0.13558
  Epoch 020 - train 0.09373 | val 0.13837
  Regression -> MSE: 0.000324, MAE: 0.013603, R²: -0.0408
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.10649 | val 0.11503
  Epoch 020 - train 0.10037 | val 0.11709
  Regression -> MSE: 0.000680, MAE: 0.019538, R²: -0.0047
  Directional -> Accuracy: 0.4655, MCC: -0.1890, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.10038 | val 0.11041
  Epoch 020 - train 0.09788 | val 0.13260
  Regression -> MSE: 0.000139, MAE: 0.009002, R²: -0.0077
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.09341 | val 0.13064
  Epoch 020 - train 0.09402 | val 0.12987
  Regression -> MSE: 0.000225, MAE: 0.010692, R²: 0.0016
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.09908 | val 0.19448
  Epoch 020 - train 0.09817 | val 0.19524
  Regression -> MSE: 0.000363, MAE: 0.016217, R²: -0.0027
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.10377 | val 0.10620
  Epoch 020 - train 0.10394 | val 0.10657
  Regression -> MSE: 0.000110, MAE: 0.007957, R²: -0.0219
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.09874 | val 0.15690
  Epoch 020 - train 0.09611 | val 0.15696
  Regression -> MSE: 0.000160, MAE: 0.010071, R²: -0.0246
  Directional -> Accuracy: 0.6102, MCC: -0.0189, F1: 0.7527

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.10116 | val 0.11901
  Epoch 020 - train 0.10013 | val 0.12243
  Regression -> MSE: 0.000290, MAE: 0.013832, R²: -0.0654
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.08977 | val 0.13899
  Epoch 020 - train 0.08800 | val 0.13931
  Regression -> MSE: 0.000152, MAE: 0.008725, R²: -0.0151
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.10207 | val 0.13961
  Epoch 020 - train 0.09801 | val 0.13932
  Regression -> MSE: 0.000235, MAE: 0.010973, R²: -0.0402
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.09816 | val 0.12735
  Epoch 020 - train 0.09699 | val 0.14946
  Regression -> MSE: 0.000143, MAE: 0.008280, R²: 0.0047
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.09648 | val 0.12586
  Epoch 020 - train 0.09508 | val 0.12718
  Regression -> MSE: 0.000165, MAE: 0.010472, R²: 0.0034
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.10332 | val 0.11617
  Epoch 020 - train 0.10110 | val 0.11520
  Regression -> MSE: 0.000085, MAE: 0.007025, R²: -0.0016
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.10083 | val 0.15728
  Epoch 020 - train 0.09957 | val 0.17529
  Regression -> MSE: 0.000212, MAE: 0.011244, R²: -0.0011
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.09301 | val 0.09471
  Epoch 020 - train 0.09030 | val 0.09331
  Regression -> MSE: 0.000098, MAE: 0.008182, R²: -0.0657
  Directional -> Accuracy: 0.4464, MCC: -0.2064, F1: 0.5867

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.10055 | val 0.07781
  Epoch 020 - train 0.10156 | val 0.08831
  Regression -> MSE: 0.000104, MAE: 0.008788, R²: -0.0080
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.10564 | val 0.09736
  Epoch 020 - train 0.10897 | val 0.10764
  Regression -> MSE: 0.000232, MAE: 0.012514, R²: -0.0004
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.09808 | val 0.11316
  Epoch 020 - train 0.09848 | val 0.11346
  Regression -> MSE: 0.000183, MAE: 0.008006, R²: -0.0966
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.10407 | val 0.08479
  Epoch 020 - train 0.10389 | val 0.08662
  Regression -> MSE: 0.000236, MAE: 0.011857, R²: 0.0005
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.10045 | val 0.15715
  Epoch 020 - train 0.09616 | val 0.16178
  Regression -> MSE: 0.000233, MAE: 0.010056, R²: -0.0118
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.10173 | val 0.12396
  Epoch 020 - train 0.10212 | val 0.11872
  Regression -> MSE: 0.000134, MAE: 0.008067, R²: 0.0043
  Directional -> Accuracy: 0.5116, MCC: -0.0323, F1: 0.6441

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.10384 | val 0.12121
  Epoch 020 - train 0.09916 | val 0.12391
  Regression -> MSE: 0.000196, MAE: 0.010535, R²: -0.0387
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.09298 | val 0.13359
  Epoch 020 - train 0.09174 | val 0.13189
  Regression -> MSE: 0.000266, MAE: 0.010552, R²: -0.0162
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.09295 | val 0.08805
  Epoch 020 - train 0.09194 | val 0.08163
  Regression -> MSE: 0.000165, MAE: 0.010344, R²: 0.0115
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.09000 | val 0.10693
  Epoch 020 - train 0.08958 | val 0.11001
  Regression -> MSE: 0.000189, MAE: 0.010658, R²: -0.0490
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.09590 | val 0.09560
  Epoch 020 - train 0.09598 | val 0.09676
  Regression -> MSE: 0.000342, MAE: 0.011807, R²: 0.0009
  Directional -> Accuracy: 0.5373, MCC: 0.1486, F1: 0.4561

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.10908 | val 0.06515
  Epoch 020 - train 0.10584 | val 0.06649
  Regression -> MSE: 0.000125, MAE: 0.008473, R²: -0.1918
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.09658 | val 0.13399
  Epoch 020 - train 0.09688 | val 0.13772
  Regression -> MSE: 0.000220, MAE: 0.011338, R²: -0.0062
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.10370 | val 0.16200
  Epoch 020 - train 0.10411 | val 0.16062
  Regression -> MSE: 0.000086, MAE: 0.007233, R²: -0.1027
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.10492 | val 0.09535
  Epoch 020 - train 0.10638 | val 0.12026
  Regression -> MSE: 0.000355, MAE: 0.015824, R²: -0.1543
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.10553 | val 0.06666
  Epoch 020 - train 0.10339 | val 0.06874
  Regression -> MSE: 0.000261, MAE: 0.011500, R²: -0.0690
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.09695 | val 0.12480
  Epoch 020 - train 0.09850 | val 0.12445
  Regression -> MSE: 0.000086, MAE: 0.007068, R²: -0.0631
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.10321 | val 0.13363
  Epoch 020 - train 0.10029 | val 0.16613
  Regression -> MSE: 0.000309, MAE: 0.014485, R²: -0.0072
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.10268 | val 0.11579
  Epoch 020 - train 0.10020 | val 0.11443
  Regression -> MSE: 0.000102, MAE: 0.007117, R²: -0.0434
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.10291 | val 0.11470
  Epoch 020 - train 0.10551 | val 0.11772
  Regression -> MSE: 0.000173, MAE: 0.009971, R²: -0.0090
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.09091 | val 0.11513
  Epoch 020 - train 0.09161 | val 0.11811
  Regression -> MSE: 0.000224, MAE: 0.011743, R²: -0.0047
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.09393 | val 0.10955
  Epoch 020 - train 0.09662 | val 0.10787
  Regression -> MSE: 0.000094, MAE: 0.007724, R²: -0.0144
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.10624 | val 0.15270
  Epoch 020 - train 0.10770 | val 0.15777
  Regression -> MSE: 0.000164, MAE: 0.010264, R²: -0.0042
  Directional -> Accuracy: 0.5370, MCC: 0.0648, F1: 0.6479

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.10072 | val 0.11864
  Epoch 020 - train 0.10055 | val 0.11977
  Regression -> MSE: 0.000122, MAE: 0.008996, R²: -0.0547
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.10026 | val 0.13983

[I 2026-02-23 02:18:54,197] Trial 193 finished with value: -0.011472304489132348 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 32, 'learning_rate': 3.273997445018537e-06, 'weight_decay': 5.050745537809084e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.14319822267020652, 'early_stopping_min_delta': 0.005067275561942168}. Best is trial 157 with value: -0.011387287234516647.

  Epoch 020 - train 0.10077 | val 0.14069
  Regression -> MSE: 0.000240, MAE: 0.012350, R²: -0.0132
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.07624 | val 0.10658
  Epoch 020 - train 0.07577 | val 0.10686
  Regression -> MSE: 0.000251, MAE: 0.012696, R²: -0.0145
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.07179 | val 0.07225
  Epoch 020 - train 0.07158 | val 0.07614
  Regression -> MSE: 0.000684, MAE: 0.019351, R²: 0.0001
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.07654 | val 0.11863
  Epoch 020 - train 0.07452 | val 0.11742
  Regression -> MSE: 0.000310, MAE: 0.014403, R²: 0.0013
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.06275 | val 0.07932
  Epoch 020 - train 0.06223 | val 0.08440
  Regression -> MSE: 0.000378, MAE: 0.015043, R²: -0.0826
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.07900 | val 0.07876
  Epoch 020 - train 0.07729 | val 0.08416
  Regression -> MSE: 0.000204, MAE: 0.010177, R²: -0.0021
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.07446 | val 0.13419
  Epoch 020 - train 0.07304 | val 0.15597
  Regression -> MSE: 0.000578, MAE: 0.018545, R²: -0.0412
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.07457 | val 0.09158
  Epoch 020 - train 0.07648 | val 0.09176
  Regression -> MSE: 0.000245, MAE: 0.011936, R²: -0.0000
  Directional -> Accuracy: 0.5217, MCC: -0.0335, F1: 0.3265

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.07679 | val 0.09348
  Epoch 020 - train 0.07737 | val 0.09506
  Regression -> MSE: 0.000618, MAE: 0.019644, R²: -0.0338
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.07680 | val 0.08558
  Epoch 020 - train 0.07413 | val 0.08498
  Regression -> MSE: 0.000409, MAE: 0.016218, R²: -0.0654
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.07101 | val 0.09999
  Epoch 020 - train 0.07438 | val 0.10308
  Regression -> MSE: 0.000242, MAE: 0.011709, R²: -0.0033
  Directional -> Accuracy: 0.4286, MCC: -0.0355, F1: 0.5833

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.06886 | val 0.10234
  Epoch 020 - train 0.07160 | val 0.10003
  Regression -> MSE: 0.000311, MAE: 0.013670, R²: 0.0001
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.6301

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.07934 | val 0.09756
  Epoch 020 - train 0.07675 | val 0.11189
  Regression -> MSE: 0.000677, MAE: 0.019515, R²: 0.0000
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.07548 | val 0.07643
  Epoch 020 - train 0.07337 | val 0.08474
  Regression -> MSE: 0.000139, MAE: 0.009190, R²: -0.0052
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.06929 | val 0.09873
  Epoch 020 - train 0.06776 | val 0.09868
  Regression -> MSE: 0.000225, MAE: 0.010753, R²: -0.0001
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.07645 | val 0.14800
  Epoch 020 - train 0.07504 | val 0.15618
  Regression -> MSE: 0.000363, MAE: 0.016191, R²: -0.0018
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.07743 | val 0.07698
  Epoch 020 - train 0.07811 | val 0.07773
  Regression -> MSE: 0.000108, MAE: 0.008020, R²: 0.0007
  Directional -> Accuracy: 0.5143, MCC: 0.1288, F1: 0.2917

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.07522 | val 0.12991
  Epoch 020 - train 0.07298 | val 0.13462
  Regression -> MSE: 0.000155, MAE: 0.009552, R²: 0.0052
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.07643 | val 0.07842
  Epoch 020 - train 0.07824 | val 0.07661
  Regression -> MSE: 0.000272, MAE: 0.013000, R²: 0.0004
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.06943 | val 0.10112
  Epoch 020 - train 0.06744 | val 0.10028
  Regression -> MSE: 0.000152, MAE: 0.008733, R²: -0.0178
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.07892 | val 0.10482
  Epoch 020 - train 0.07674 | val 0.10442
  Regression -> MSE: 0.000256, MAE: 0.011438, R²: -0.1304
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.07389 | val 0.09137
  Epoch 020 - train 0.07169 | val 0.09818
  Regression -> MSE: 0.000143, MAE: 0.008288, R²: 0.0013
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.06929 | val 0.08780
  Epoch 020 - train 0.07173 | val 0.08890
  Regression -> MSE: 0.000175, MAE: 0.010251, R²: -0.0597
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.07862 | val 0.09645
  Epoch 020 - train 0.07831 | val 0.09754
  Regression -> MSE: 0.000092, MAE: 0.007361, R²: -0.0738
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.07782 | val 0.08835
  Epoch 020 - train 0.07421 | val 0.08842
  Regression -> MSE: 0.000214, MAE: 0.011392, R²: -0.0092
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.06843 | val 0.06838
  Epoch 020 - train 0.06897 | val 0.06593
  Regression -> MSE: 0.000094, MAE: 0.008090, R²: -0.0188
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.07444 | val 0.05976
  Epoch 020 - train 0.07130 | val 0.05822
  Regression -> MSE: 0.000107, MAE: 0.008925, R²: -0.0379
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.07967 | val 0.07420
  Epoch 020 - train 0.07873 | val 0.08349
  Regression -> MSE: 0.000231, MAE: 0.012530, R²: 0.0004
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.07320 | val 0.08628
  Epoch 020 - train 0.07263 | val 0.08512
  Regression -> MSE: 0.000188, MAE: 0.008133, R²: -0.1303
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.07570 | val 0.06424
  Epoch 020 - train 0.07724 | val 0.06524
  Regression -> MSE: 0.000238, MAE: 0.011912, R²: -0.0046
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.07357 | val 0.11893
  Epoch 020 - train 0.07466 | val 0.12214
  Regression -> MSE: 0.000235, MAE: 0.010136, R²: -0.0179
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.07810 | val 0.09254
  Epoch 020 - train 0.07622 | val 0.09416
  Regression -> MSE: 0.000139, MAE: 0.008356, R²: -0.0307
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.07357 | val 0.09319
  Epoch 020 - train 0.07629 | val 0.09539
  Regression -> MSE: 0.000197, MAE: 0.010600, R²: -0.0461
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.07699 | val 0.11179
  Epoch 020 - train 0.07442 | val 0.11112
  Regression -> MSE: 0.000262, MAE: 0.010616, R²: -0.0023
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.07724 | val 0.06321
  Epoch 020 - train 0.07365 | val 0.06435
  Regression -> MSE: 0.000167, MAE: 0.010367, R²: -0.0034
  Directional -> Accuracy: 0.5526, MCC: 0.1091, F1: 0.4848

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.07002 | val 0.07764
  Epoch 020 - train 0.07311 | val 0.08631
  Regression -> MSE: 0.000183, MAE: 0.010418, R²: -0.0144
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.07613 | val 0.07711
  Epoch 020 - train 0.07227 | val 0.07820
  Regression -> MSE: 0.000357, MAE: 0.012802, R²: -0.0426
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.08142 | val 0.05071
  Epoch 020 - train 0.07838 | val 0.05076
  Regression -> MSE: 0.000112, MAE: 0.008310, R²: -0.0680
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.07467 | val 0.10005
  Epoch 020 - train 0.07243 | val 0.09934
  Regression -> MSE: 0.000218, MAE: 0.011273, R²: 0.0003
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.07074 | val 0.12577
  Epoch 020 - train 0.07250 | val 0.12317
  Regression -> MSE: 0.000081, MAE: 0.007032, R²: -0.0481
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.07260 | val 0.05924
  Epoch 020 - train 0.07381 | val 0.05818
  Regression -> MSE: 0.000319, MAE: 0.014457, R²: -0.0366
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.08098 | val 0.04777
  Epoch 020 - train 0.07976 | val 0.05175
  Regression -> MSE: 0.000251, MAE: 0.011482, R²: -0.0312
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.07388 | val 0.08981
  Epoch 020 - train 0.07307 | val 0.09011
  Regression -> MSE: 0.000081, MAE: 0.007062, R²: -0.0070
  Directional -> Accuracy: 0.5067, MCC: 0.1147, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.07437 | val 0.09173
  Epoch 020 - train 0.07301 | val 0.09330
  Regression -> MSE: 0.000307, MAE: 0.014471, R²: -0.0017
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.07450 | val 0.08234
  Epoch 020 - train 0.07434 | val 0.08959
  Regression -> MSE: 0.000099, MAE: 0.007239, R²: -0.0044
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.08384 | val 0.08626
  Epoch 020 - train 0.08144 | val 0.09072
  Regression -> MSE: 0.000173, MAE: 0.009931, R²: -0.0061
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.06940 | val 0.08427
  Epoch 020 - train 0.06972 | val 0.08420
  Regression -> MSE: 0.000223, MAE: 0.011770, R²: -0.0006
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.07283 | val 0.08722
  Epoch 020 - train 0.07136 | val 0.08991
  Regression -> MSE: 0.000093, MAE: 0.007713, R²: -0.0120
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.07781 | val 0.11187
  Epoch 020 - train 0.07901 | val 0.11463
  Regression -> MSE: 0.000164, MAE: 0.010249, R²: -0.0014
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.07314 | val 0.09706
  Epoch 020 - train 0.07274 | val 0.10131
  Regression -> MSE: 0.000122, MAE: 0.008987, R²: -0.0537
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.08011 | val 0.10525

[I 2026-02-23 02:21:30,659] Trial 194 finished with value: -0.01144588210086643 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 32, 'learning_rate': 4.4431460855316284e-06, 'weight_decay': 4.430061382392458e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.10580359308872782, 'early_stopping_min_delta': 0.006769571944353759}. Best is trial 157 with value: -0.011387287234516647.

  Epoch 020 - train 0.07565 | val 0.10895
  Regression -> MSE: 0.000238, MAE: 0.012359, R²: -0.0025
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.17151 | val 0.22841
  Epoch 020 - train 0.16563 | val 0.22706
  Regression -> MSE: 0.000271, MAE: 0.013271, R²: -0.0938
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.16733 | val 0.18605
  Epoch 020 - train 0.16350 | val 0.22982
  Regression -> MSE: 0.000686, MAE: 0.019383, R²: -0.0022
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.15996 | val 0.26479
  Epoch 020 - train 0.16152 | val 0.27444
  Regression -> MSE: 0.000311, MAE: 0.014405, R²: -0.0036
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.13019 | val 0.16779
  Epoch 020 - train 0.13074 | val 0.17563
  Regression -> MSE: 0.000380, MAE: 0.015078, R²: -0.0877
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.16949 | val 0.18015
  Epoch 020 - train 0.16419 | val 0.20589
  Regression -> MSE: 0.000204, MAE: 0.010097, R²: -0.0013
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.14414 | val 0.30980
  Epoch 020 - train 0.14916 | val 0.31741
  Regression -> MSE: 0.000571, MAE: 0.018380, R²: -0.0282
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.16657 | val 0.21981
  Epoch 020 - train 0.16775 | val 0.21632
  Regression -> MSE: 0.000251, MAE: 0.011953, R²: -0.0215
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.16008 | val 0.19787
  Epoch 020 - train 0.15675 | val 0.22786
  Regression -> MSE: 0.000605, MAE: 0.019330, R²: -0.0118
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.15199 | val 0.19135
  Epoch 020 - train 0.15137 | val 0.19521
  Regression -> MSE: 0.000402, MAE: 0.016094, R²: -0.0492
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.16237 | val 0.20510
  Epoch 020 - train 0.15724 | val 0.20574
  Regression -> MSE: 0.000242, MAE: 0.011806, R²: -0.0009
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.15141 | val 0.23533
  Epoch 020 - train 0.14793 | val 0.25514
  Regression -> MSE: 0.000319, MAE: 0.013593, R²: -0.0255
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.17147 | val 0.19627
  Epoch 020 - train 0.17253 | val 0.19702
  Regression -> MSE: 0.000681, MAE: 0.019527, R²: -0.0060
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.16433 | val 0.17116
  Epoch 020 - train 0.16255 | val 0.21514
  Regression -> MSE: 0.000139, MAE: 0.009067, R²: -0.0041
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.14283 | val 0.23271
  Epoch 020 - train 0.14452 | val 0.23990
  Regression -> MSE: 0.000226, MAE: 0.010729, R²: -0.0062
  Directional -> Accuracy: 0.4918, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.15782 | val 0.32635
  Epoch 020 - train 0.15772 | val 0.32799
  Regression -> MSE: 0.000361, MAE: 0.015967, R²: 0.0018
  Directional -> Accuracy: 0.5962, MCC: 0.1787, F1: 0.5116

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.16477 | val 0.16884
  Epoch 020 - train 0.16587 | val 0.16998
  Regression -> MSE: 0.000108, MAE: 0.007978, R²: -0.0017
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.15570 | val 0.27363
  Epoch 020 - train 0.15163 | val 0.28688
  Regression -> MSE: 0.000156, MAE: 0.009690, R²: -0.0036
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.16396 | val 0.16012
  Epoch 020 - train 0.15608 | val 0.16141
  Regression -> MSE: 0.000274, MAE: 0.013154, R²: -0.0076
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.14983 | val 0.22594
  Epoch 020 - train 0.14613 | val 0.22276
  Regression -> MSE: 0.000159, MAE: 0.008857, R²: -0.0600
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.17368 | val 0.27337
  Epoch 020 - train 0.17654 | val 0.27826
  Regression -> MSE: 0.000248, MAE: 0.011215, R²: -0.0949
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.15985 | val 0.20259
  Epoch 020 - train 0.15383 | val 0.21079
  Regression -> MSE: 0.000152, MAE: 0.008802, R²: -0.0637
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.15673 | val 0.21269
  Epoch 020 - train 0.15099 | val 0.21604
  Regression -> MSE: 0.000166, MAE: 0.010618, R²: -0.0023
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.16787 | val 0.19377
  Epoch 020 - train 0.16759 | val 0.19514
  Regression -> MSE: 0.000085, MAE: 0.007041, R²: -0.0012
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.16292 | val 0.21431
  Epoch 020 - train 0.15915 | val 0.22476
  Regression -> MSE: 0.000215, MAE: 0.011037, R²: -0.0149
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.15242 | val 0.14545
  Epoch 020 - train 0.15261 | val 0.14433
  Regression -> MSE: 0.000100, MAE: 0.008208, R²: -0.0831
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.15932 | val 0.12673
  Epoch 020 - train 0.15853 | val 0.14987
  Regression -> MSE: 0.000105, MAE: 0.008864, R²: -0.0223
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.16128 | val 0.16007
  Epoch 020 - train 0.15719 | val 0.18574
  Regression -> MSE: 0.000235, MAE: 0.012668, R²: -0.0148
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.15381 | val 0.19492
  Epoch 020 - train 0.15385 | val 0.19424
  Regression -> MSE: 0.000176, MAE: 0.007876, R²: -0.0550
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.16813 | val 0.14484
  Epoch 020 - train 0.16634 | val 0.14341
  Regression -> MSE: 0.000240, MAE: 0.012041, R²: -0.0164
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.16096 | val 0.26894
  Epoch 020 - train 0.16195 | val 0.27882
  Regression -> MSE: 0.000234, MAE: 0.010124, R²: -0.0167
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.16241 | val 0.19521
  Epoch 020 - train 0.16533 | val 0.19577
  Regression -> MSE: 0.000137, MAE: 0.008265, R²: -0.0118
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.15538 | val 0.20716
  Epoch 020 - train 0.15997 | val 0.21052
  Regression -> MSE: 0.000196, MAE: 0.010583, R²: -0.0419
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.14272 | val 0.21867
  Epoch 020 - train 0.13924 | val 0.21144
  Regression -> MSE: 0.000278, MAE: 0.010882, R²: -0.0622
  Directional -> Accuracy: 0.4384, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.14945 | val 0.13460
  Epoch 020 - train 0.14899 | val 0.13698
  Regression -> MSE: 0.000170, MAE: 0.010364, R²: -0.0174
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.15383 | val 0.17011
  Epoch 020 - train 0.14856 | val 0.16469
  Regression -> MSE: 0.000178, MAE: 0.010427, R²: 0.0112
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.15706 | val 0.16444
  Epoch 020 - train 0.15067 | val 0.16425
  Regression -> MSE: 0.000344, MAE: 0.011836, R²: -0.0027
  Directional -> Accuracy: 0.4925, MCC: -0.0090, F1: 0.5143

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.16810 | val 0.10410
  Epoch 020 - train 0.16444 | val 0.11639
  Regression -> MSE: 0.000114, MAE: 0.008322, R²: -0.0826
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.16156 | val 0.23271
  Epoch 020 - train 0.15724 | val 0.25264
  Regression -> MSE: 0.000225, MAE: 0.011479, R²: -0.0308
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.16238 | val 0.27921
  Epoch 020 - train 0.15971 | val 0.28107
  Regression -> MSE: 0.000099, MAE: 0.007767, R²: -0.2758
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.15823 | val 0.14356
  Epoch 020 - train 0.16389 | val 0.14751
  Regression -> MSE: 0.000345, MAE: 0.015533, R²: -0.1227
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.17392 | val 0.10484
  Epoch 020 - train 0.17696 | val 0.10825
  Regression -> MSE: 0.000258, MAE: 0.011489, R²: -0.0579
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.15329 | val 0.19693
  Epoch 020 - train 0.15296 | val 0.19584
  Regression -> MSE: 0.000081, MAE: 0.007113, R²: -0.0047
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.16291 | val 0.21279
  Epoch 020 - train 0.16041 | val 0.23951
  Regression -> MSE: 0.000307, MAE: 0.014471, R²: -0.0015
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.18640 | val 0.18146
  Epoch 020 - train 0.17892 | val 0.18740
  Regression -> MSE: 0.000099, MAE: 0.007158, R²: -0.0104
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.17868 | val 0.19472
  Epoch 020 - train 0.17460 | val 0.21086
  Regression -> MSE: 0.000173, MAE: 0.009937, R²: -0.0067
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.15054 | val 0.17814
  Epoch 020 - train 0.14325 | val 0.18446
  Regression -> MSE: 0.000234, MAE: 0.011977, R²: -0.0481
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.16441 | val 0.19454
  Epoch 020 - train 0.16493 | val 0.20277
  Regression -> MSE: 0.000092, MAE: 0.007647, R²: 0.0008
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.17434 | val 0.24971
  Epoch 020 - train 0.17210 | val 0.24872
  Regression -> MSE: 0.000164, MAE: 0.010250, R²: -0.0004
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.15896 | val 0.19485
  Epoch 020 - train 0.15452 | val 0.20357
  Regression -> MSE: 0.000132, MAE: 0.009148, R²: -0.1403
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.16639 | val 0.22577

[I 2026-02-23 02:24:07,039] Trial 195 finished with value: -0.01147675926194192 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.1, 'batch_size': 32, 'learning_rate': 5.810685794912885e-06, 'weight_decay': 2.649224372949425e-05, 'lr_patience': 7, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.25195585685266086, 'early_stopping_min_delta': 0.0053295162736600385}. Best is trial 157 with value: -0.011387287234516647.

  Epoch 020 - train 0.16060 | val 0.22576
  Regression -> MSE: 0.000241, MAE: 0.012338, R²: -0.0170
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.20682 | val 0.28590
  Epoch 020 - train 0.20317 | val 0.28526
  Regression -> MSE: 0.000248, MAE: 0.012535, R²: -0.0008
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.20232 | val 0.19557
  Epoch 020 - train 0.20292 | val 0.20901
  Regression -> MSE: 0.000706, MAE: 0.019725, R²: -0.0307
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.20857 | val 0.35116
  Epoch 020 - train 0.20051 | val 0.36514
  Regression -> MSE: 0.000310, MAE: 0.014433, R²: -0.0004
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.18654 | val 0.18549
  Epoch 020 - train 0.19004 | val 0.19090
  Regression -> MSE: 0.000350, MAE: 0.014564, R²: -0.0017
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.20521 | val 0.20787
  Epoch 020 - train 0.20812 | val 0.20833
  Regression -> MSE: 0.000205, MAE: 0.010104, R²: -0.0087
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.20104 | val 0.41235
  Epoch 020 - train 0.19132 | val 0.41616
  Regression -> MSE: 0.000592, MAE: 0.018813, R²: -0.0668
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.22016 | val 0.30919
  Epoch 020 - train 0.21891 | val 0.31016
  Regression -> MSE: 0.000251, MAE: 0.011943, R²: -0.0233
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.21044 | val 0.27526
  Epoch 020 - train 0.19730 | val 0.29263
  Regression -> MSE: 0.000623, MAE: 0.019745, R²: -0.0425
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.19880 | val 0.24686
  Epoch 020 - train 0.19991 | val 0.24382
  Regression -> MSE: 0.000399, MAE: 0.016032, R²: -0.0395
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.20500 | val 0.30078
  Epoch 020 - train 0.19945 | val 0.31342
  Regression -> MSE: 0.000241, MAE: 0.011827, R²: 0.0008
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.19804 | val 0.28979
  Epoch 020 - train 0.19537 | val 0.28785
  Regression -> MSE: 0.000356, MAE: 0.014017, R²: -0.1450
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.21181 | val 0.24926
  Epoch 020 - train 0.21338 | val 0.26074
  Regression -> MSE: 0.000687, MAE: 0.019862, R²: -0.0148
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.20880 | val 0.20896
  Epoch 020 - train 0.20571 | val 0.24061
  Regression -> MSE: 0.000144, MAE: 0.009495, R²: -0.0448
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.19663 | val 0.29927
  Epoch 020 - train 0.18953 | val 0.30317
  Regression -> MSE: 0.000226, MAE: 0.010811, R²: -0.0034
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.21421 | val 0.43434
  Epoch 020 - train 0.20607 | val 0.43607
  Regression -> MSE: 0.000373, MAE: 0.015937, R²: -0.0297
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.21644 | val 0.21029
  Epoch 020 - train 0.21692 | val 0.21364
  Regression -> MSE: 0.000107, MAE: 0.008017, R²: 0.0094
  Directional -> Accuracy: 0.5429, MCC: 0.1891, F1: 0.3600

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.20644 | val 0.35314
  Epoch 020 - train 0.20200 | val 0.35803
  Regression -> MSE: 0.000156, MAE: 0.009763, R²: -0.0038
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.21467 | val 0.23016
  Epoch 020 - train 0.21820 | val 0.23021
  Regression -> MSE: 0.000285, MAE: 0.013620, R²: -0.0462
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.18896 | val 0.28717
  Epoch 020 - train 0.18344 | val 0.28751
  Regression -> MSE: 0.000171, MAE: 0.009232, R²: -0.1411
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.21383 | val 0.31859
  Epoch 020 - train 0.21050 | val 0.32869
  Regression -> MSE: 0.000235, MAE: 0.010948, R²: -0.0365
  Directional -> Accuracy: 0.5067, MCC: 0.2161, F1: 0.1778

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.20461 | val 0.26396
  Epoch 020 - train 0.20714 | val 0.27149
  Regression -> MSE: 0.000144, MAE: 0.008363, R²: -0.0039
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.20335 | val 0.28155
  Epoch 020 - train 0.20463 | val 0.28920
  Regression -> MSE: 0.000166, MAE: 0.010624, R²: -0.0038
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.21641 | val 0.24625
  Epoch 020 - train 0.20824 | val 0.24999
  Regression -> MSE: 0.000085, MAE: 0.007154, R²: -0.0003
  Directional -> Accuracy: 0.5517, MCC: 0.0687, F1: 0.6286

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.20506 | val 0.27584
  Epoch 020 - train 0.20242 | val 0.28198
  Regression -> MSE: 0.000212, MAE: 0.011166, R²: 0.0008
  Directional -> Accuracy: 0.4848, MCC: -0.0089, F1: 0.5526

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.18931 | val 0.20281
  Epoch 020 - train 0.19104 | val 0.20225
  Regression -> MSE: 0.000103, MAE: 0.008276, R²: -0.1137
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.21855 | val 0.18079
  Epoch 020 - train 0.21222 | val 0.19570
  Regression -> MSE: 0.000121, MAE: 0.009370, R²: -0.1719
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.22519 | val 0.19793
  Epoch 020 - train 0.21839 | val 0.23748
  Regression -> MSE: 0.000240, MAE: 0.012865, R²: -0.0390
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.20767 | val 0.25994
  Epoch 020 - train 0.20266 | val 0.26182
  Regression -> MSE: 0.000174, MAE: 0.007857, R²: -0.0457
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.22391 | val 0.17898
  Epoch 020 - train 0.22875 | val 0.19805
  Regression -> MSE: 0.000237, MAE: 0.011873, R²: -0.0014
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.20525 | val 0.33297
  Epoch 020 - train 0.20763 | val 0.33025
  Regression -> MSE: 0.000231, MAE: 0.009874, R²: -0.0026
  Directional -> Accuracy: 0.5116, MCC: 0.0288, F1: 0.5532

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.21924 | val 0.24343
  Epoch 020 - train 0.21243 | val 0.24058
  Regression -> MSE: 0.000135, MAE: 0.008285, R²: 0.0027
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.20862 | val 0.26985
  Epoch 020 - train 0.20256 | val 0.27698
  Regression -> MSE: 0.000195, MAE: 0.010544, R²: -0.0376
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.19443 | val 0.26043
  Epoch 020 - train 0.18539 | val 0.25466
  Regression -> MSE: 0.000263, MAE: 0.010548, R²: -0.0044
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.19655 | val 0.17311
  Epoch 020 - train 0.19135 | val 0.18045
  Regression -> MSE: 0.000169, MAE: 0.010365, R²: -0.0130
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.19077 | val 0.21714
  Epoch 020 - train 0.19056 | val 0.24686
  Regression -> MSE: 0.000181, MAE: 0.010349, R²: -0.0037
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.19964 | val 0.19309
  Epoch 020 - train 0.19408 | val 0.19491
  Regression -> MSE: 0.000343, MAE: 0.011762, R²: -0.0022
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.22006 | val 0.12932
  Epoch 020 - train 0.22465 | val 0.13691
  Regression -> MSE: 0.000117, MAE: 0.008325, R²: -0.1109
  Directional -> Accuracy: 0.5581, MCC: 0.1182, F1: 0.6415

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.21093 | val 0.29298
  Epoch 020 - train 0.20063 | val 0.31011
  Regression -> MSE: 0.000219, MAE: 0.011295, R²: -0.0005
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.21117 | val 0.38387
  Epoch 020 - train 0.20398 | val 0.44277
  Regression -> MSE: 0.000081, MAE: 0.007009, R²: -0.0427
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.21369 | val 0.15505
  Epoch 020 - train 0.21641 | val 0.15499
  Regression -> MSE: 0.000312, MAE: 0.014097, R²: -0.0149
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.22935 | val 0.13424
  Epoch 020 - train 0.22025 | val 0.12973
  Regression -> MSE: 0.000265, MAE: 0.011601, R²: -0.0863
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.19590 | val 0.25452
  Epoch 020 - train 0.19140 | val 0.25351
  Regression -> MSE: 0.000085, MAE: 0.007066, R²: -0.0570
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.20897 | val 0.25975
  Epoch 020 - train 0.21124 | val 0.25532
  Regression -> MSE: 0.000305, MAE: 0.014475, R²: 0.0043
  Directional -> Accuracy: 0.5319, MCC: 0.0926, F1: 0.6765

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.20575 | val 0.22231
  Epoch 020 - train 0.20984 | val 0.23702
  Regression -> MSE: 0.000098, MAE: 0.007382, R²: -0.0006
  Directional -> Accuracy: 0.4318, MCC: 0.0000, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.22643 | val 0.25402
  Epoch 020 - train 0.22747 | val 0.26060
  Regression -> MSE: 0.000173, MAE: 0.009943, R²: -0.0065
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.19452 | val 0.23176
  Epoch 020 - train 0.19567 | val 0.23362
  Regression -> MSE: 0.000226, MAE: 0.011835, R²: -0.0128
  Directional -> Accuracy: 0.4821, MCC: -0.1659, F1: 0.6420

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.20732 | val 0.25119
  Epoch 020 - train 0.20177 | val 0.26699
  Regression -> MSE: 0.000092, MAE: 0.007643, R²: 0.0004
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.21980 | val 0.32952
  Epoch 020 - train 0.21656 | val 0.33231
  Regression -> MSE: 0.000164, MAE: 0.010259, R²: -0.0000
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.20293 | val 0.26442
  Epoch 020 - train 0.20539 | val 0.26481
  Regression -> MSE: 0.000118, MAE: 0.008937, R²: -0.0141
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.20665 | val 0.32723

[I 2026-02-23 02:26:45,047] Trial 196 finished with value: -0.0114587388128946 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 32, 'learning_rate': 3.625081315579124e-06, 'weight_decay': 7.294273913872952e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.34411062091437183, 'early_stopping_min_delta': 0.005863608043968148}. Best is trial 157 with value: -0.011387287234516647.

  Epoch 020 - train 0.20844 | val 0.35655
  Regression -> MSE: 0.000245, MAE: 0.012370, R²: -0.0346
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.09965 | val 0.12982
  Epoch 020 - train 0.09823 | val 0.12792
  Regression -> MSE: 0.000256, MAE: 0.012900, R²: -0.0358
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.09394 | val 0.09077
  Epoch 020 - train 0.09641 | val 0.11162
  Regression -> MSE: 0.000683, MAE: 0.019330, R²: 0.0019
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.10060 | val 0.15888
  Epoch 020 - train 0.10000 | val 0.16412
  Regression -> MSE: 0.000310, MAE: 0.014395, R²: 0.0005
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.08208 | val 0.08354
  Epoch 020 - train 0.08285 | val 0.08924
  Regression -> MSE: 0.000374, MAE: 0.014971, R²: -0.0703
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.10378 | val 0.09961
  Epoch 020 - train 0.09927 | val 0.09838
  Regression -> MSE: 0.000204, MAE: 0.010107, R²: -0.0011
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.09490 | val 0.17916
  Epoch 020 - train 0.09049 | val 0.17684
  Regression -> MSE: 0.000581, MAE: 0.018614, R²: -0.0474
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.10041 | val 0.12173
  Epoch 020 - train 0.10008 | val 0.12207
  Regression -> MSE: 0.000246, MAE: 0.011942, R²: -0.0026
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.09556 | val 0.13026
  Epoch 020 - train 0.09877 | val 0.10849
  Regression -> MSE: 0.000602, MAE: 0.019084, R²: -0.0078
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.10468 | val 0.11218
  Epoch 020 - train 0.10280 | val 0.11851
  Regression -> MSE: 0.000410, MAE: 0.016234, R²: -0.0676
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.09901 | val 0.12661
  Epoch 020 - train 0.09434 | val 0.12616
  Regression -> MSE: 0.000243, MAE: 0.012113, R²: -0.0050
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.09159 | val 0.16995
  Epoch 020 - train 0.09190 | val 0.21127
  Regression -> MSE: 0.000311, MAE: 0.013709, R²: 0.0001
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.6301

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.10132 | val 0.11563
  Epoch 020 - train 0.10280 | val 0.11849
  Regression -> MSE: 0.000684, MAE: 0.019780, R²: -0.0093
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.10045 | val 0.11330
  Epoch 020 - train 0.09780 | val 0.14058
  Regression -> MSE: 0.000138, MAE: 0.009048, R²: -0.0005
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.09144 | val 0.13400
  Epoch 020 - train 0.09092 | val 0.13010
  Regression -> MSE: 0.000227, MAE: 0.010903, R²: -0.0090
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.09615 | val 0.19526
  Epoch 020 - train 0.09422 | val 0.19698
  Regression -> MSE: 0.000364, MAE: 0.016003, R²: -0.0059
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.10329 | val 0.11080
  Epoch 020 - train 0.10193 | val 0.10971
  Regression -> MSE: 0.000109, MAE: 0.008140, R²: -0.0137
  Directional -> Accuracy: 0.4571, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.09280 | val 0.16306
  Epoch 020 - train 0.09225 | val 0.17270
  Regression -> MSE: 0.000157, MAE: 0.009839, R²: -0.0053
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.09999 | val 0.10448
  Epoch 020 - train 0.09794 | val 0.10727
  Regression -> MSE: 0.000279, MAE: 0.013372, R²: -0.0252
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.08658 | val 0.13582
  Epoch 020 - train 0.08769 | val 0.13702
  Regression -> MSE: 0.000165, MAE: 0.009073, R²: -0.1022
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.09829 | val 0.14411
  Epoch 020 - train 0.09781 | val 0.14658
  Regression -> MSE: 0.000238, MAE: 0.011045, R²: -0.0540
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.09969 | val 0.11904
  Epoch 020 - train 0.09839 | val 0.12095
  Regression -> MSE: 0.000143, MAE: 0.008302, R²: 0.0001
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.09231 | val 0.11358
  Epoch 020 - train 0.09175 | val 0.11374
  Regression -> MSE: 0.000176, MAE: 0.010282, R²: -0.0627
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.10724 | val 0.11887
  Epoch 020 - train 0.10389 | val 0.12092
  Regression -> MSE: 0.000086, MAE: 0.007093, R²: -0.0087
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.09663 | val 0.12429
  Epoch 020 - train 0.09633 | val 0.12511
  Regression -> MSE: 0.000212, MAE: 0.011085, R²: -0.0021
  Directional -> Accuracy: 0.4242, MCC: -0.1416, F1: 0.5366

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.09175 | val 0.08883
  Epoch 020 - train 0.09040 | val 0.08530
  Regression -> MSE: 0.000098, MAE: 0.008180, R²: -0.0694
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.09669 | val 0.07706
  Epoch 020 - train 0.09622 | val 0.07816
  Regression -> MSE: 0.000103, MAE: 0.008703, R²: -0.0006
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.10005 | val 0.09539
  Epoch 020 - train 0.10068 | val 0.10456
  Regression -> MSE: 0.000232, MAE: 0.012575, R²: -0.0031
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.09450 | val 0.11440
  Epoch 020 - train 0.09350 | val 0.11412
  Regression -> MSE: 0.000182, MAE: 0.007991, R²: -0.0909
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.11118 | val 0.08875
  Epoch 020 - train 0.11032 | val 0.08664
  Regression -> MSE: 0.000241, MAE: 0.012090, R²: -0.0207
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.09857 | val 0.15211
  Epoch 020 - train 0.10030 | val 0.15318
  Regression -> MSE: 0.000230, MAE: 0.009876, R²: 0.0005
  Directional -> Accuracy: 0.4419, MCC: -0.1198, F1: 0.4000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.10119 | val 0.12552
  Epoch 020 - train 0.09921 | val 0.13018
  Regression -> MSE: 0.000140, MAE: 0.008443, R²: -0.0405
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.10296 | val 0.12372
  Epoch 020 - train 0.09949 | val 0.12132
  Regression -> MSE: 0.000189, MAE: 0.010402, R²: -0.0056
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.09078 | val 0.12684
  Epoch 020 - train 0.08705 | val 0.12615
  Regression -> MSE: 0.000271, MAE: 0.010630, R²: -0.0333
  Directional -> Accuracy: 0.4658, MCC: -0.0607, F1: 0.4800

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.09510 | val 0.09227
  Epoch 020 - train 0.09105 | val 0.09243
  Regression -> MSE: 0.000171, MAE: 0.010394, R²: -0.0256
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.08955 | val 0.10013
  Epoch 020 - train 0.08874 | val 0.10473
  Regression -> MSE: 0.000183, MAE: 0.010421, R²: -0.0149
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.09429 | val 0.09848
  Epoch 020 - train 0.09475 | val 0.09819
  Regression -> MSE: 0.000343, MAE: 0.011728, R²: -0.0020
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.10856 | val 0.06581
  Epoch 020 - train 0.10460 | val 0.06632
  Regression -> MSE: 0.000129, MAE: 0.008560, R²: -0.2289
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.09953 | val 0.14016
  Epoch 020 - train 0.10046 | val 0.14093
  Regression -> MSE: 0.000219, MAE: 0.011307, R²: -0.0016
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.09692 | val 0.16865
  Epoch 020 - train 0.09784 | val 0.18960
  Regression -> MSE: 0.000089, MAE: 0.007371, R²: -0.1422
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.09497 | val 0.07370
  Epoch 020 - train 0.09721 | val 0.07426
  Regression -> MSE: 0.000310, MAE: 0.013981, R²: -0.0086
  Directional -> Accuracy: 0.6122, MCC: 0.2883, F1: 0.5957

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.11665 | val 0.06857
  Epoch 020 - train 0.11644 | val 0.07442
  Regression -> MSE: 0.000265, MAE: 0.011538, R²: -0.0863
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.09483 | val 0.11360
  Epoch 020 - train 0.09240 | val 0.11739
  Regression -> MSE: 0.000081, MAE: 0.007084, R²: -0.0000
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.10199 | val 0.12734
  Epoch 020 - train 0.09933 | val 0.12254
  Regression -> MSE: 0.000312, MAE: 0.014497, R²: -0.0182
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.09936 | val 0.10368
  Epoch 020 - train 0.10024 | val 0.10183
  Regression -> MSE: 0.000098, MAE: 0.007291, R²: 0.0018
  Directional -> Accuracy: 0.4318, MCC: 0.0000, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.10508 | val 0.11560
  Epoch 020 - train 0.10622 | val 0.11763
  Regression -> MSE: 0.000174, MAE: 0.010071, R²: -0.0130
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.09161 | val 0.10809
  Epoch 020 - train 0.09182 | val 0.10736
  Regression -> MSE: 0.000223, MAE: 0.011736, R²: -0.0022
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.10245 | val 0.10697
  Epoch 020 - train 0.09662 | val 0.10448
  Regression -> MSE: 0.000092, MAE: 0.007634, R²: 0.0011
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.10601 | val 0.16309
  Epoch 020 - train 0.10212 | val 0.17547
  Regression -> MSE: 0.000168, MAE: 0.010328, R²: -0.0262
  Directional -> Accuracy: 0.4815, MCC: 0.0000, F1: 0.0000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.09259 | val 0.11813
  Epoch 020 - train 0.09341 | val 0.11933
  Regression -> MSE: 0.000123, MAE: 0.009003, R²: -0.0630
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.10020 | val 0.13398

[I 2026-02-23 02:29:22,949] Trial 197 finished with value: -0.011430650373334435 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 32, 'learning_rate': 7.527932667131816e-06, 'weight_decay': 2.3861732039332825e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.14293388877976126, 'early_stopping_min_delta': 0.006374918662607069}. Best is trial 157 with value: -0.011387287234516647.

  Epoch 020 - train 0.09591 | val 0.13891
  Regression -> MSE: 0.000240, MAE: 0.012332, R²: -0.0114
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.10002 | val 0.12575
  Epoch 020 - train 0.09801 | val 0.12511
  Regression -> MSE: 0.000248, MAE: 0.012529, R²: -0.0011
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.09956 | val 0.09388
  Epoch 020 - train 0.09914 | val 0.09653
  Regression -> MSE: 0.000692, MAE: 0.019510, R²: -0.0104
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.09926 | val 0.15735
  Epoch 020 - train 0.10282 | val 0.15560
  Regression -> MSE: 0.000312, MAE: 0.014469, R²: -0.0042
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.08536 | val 0.10700
  Epoch 020 - train 0.08229 | val 0.12107
  Regression -> MSE: 0.000355, MAE: 0.014709, R²: -0.0153
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.09673 | val 0.09706
  Epoch 020 - train 0.09755 | val 0.09628
  Regression -> MSE: 0.000205, MAE: 0.010259, R²: -0.0044
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.09625 | val 0.17997
  Epoch 020 - train 0.09479 | val 0.18111
  Regression -> MSE: 0.000593, MAE: 0.018810, R²: -0.0677
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.10489 | val 0.12751
  Epoch 020 - train 0.10342 | val 0.12717
  Regression -> MSE: 0.000253, MAE: 0.011971, R²: -0.0306
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.09937 | val 0.12903
  Epoch 020 - train 0.09610 | val 0.12098
  Regression -> MSE: 0.000622, MAE: 0.019754, R²: -0.0409
  Directional -> Accuracy: 0.4773, MCC: 0.0534, F1: 0.5490

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.09536 | val 0.12704
  Epoch 020 - train 0.09082 | val 0.12982
  Regression -> MSE: 0.000387, MAE: 0.016184, R²: -0.0081
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.10372 | val 0.13010
  Epoch 020 - train 0.10168 | val 0.13397
  Regression -> MSE: 0.000252, MAE: 0.011690, R²: -0.0436
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.08945 | val 0.13768
  Epoch 020 - train 0.09230 | val 0.13852
  Regression -> MSE: 0.000312, MAE: 0.013655, R²: -0.0030
  Directional -> Accuracy: 0.4800, MCC: -0.0338, F1: 0.4800

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.10001 | val 0.11546
  Epoch 020 - train 0.10144 | val 0.11489
  Regression -> MSE: 0.000680, MAE: 0.019607, R²: -0.0040
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.09592 | val 0.10096
  Epoch 020 - train 0.09358 | val 0.10362
  Regression -> MSE: 0.000142, MAE: 0.009357, R²: -0.0249
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.09540 | val 0.14073
  Epoch 020 - train 0.09720 | val 0.13740
  Regression -> MSE: 0.000230, MAE: 0.010851, R²: -0.0233
  Directional -> Accuracy: 0.4918, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.09902 | val 0.20156
  Epoch 020 - train 0.09891 | val 0.20374
  Regression -> MSE: 0.000363, MAE: 0.015947, R²: -0.0015
  Directional -> Accuracy: 0.6346, MCC: 0.2902, F1: 0.4242

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.10419 | val 0.11349
  Epoch 020 - train 0.10322 | val 0.11054
  Regression -> MSE: 0.000108, MAE: 0.007998, R²: 0.0004
  Directional -> Accuracy: 0.5143, MCC: 0.0017, F1: 0.5952

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.09661 | val 0.16791
  Epoch 020 - train 0.09626 | val 0.17583
  Regression -> MSE: 0.000159, MAE: 0.009712, R²: -0.0174
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.10408 | val 0.10200
  Epoch 020 - train 0.10111 | val 0.10082
  Regression -> MSE: 0.000276, MAE: 0.012883, R²: -0.0161
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.08704 | val 0.13227
  Epoch 020 - train 0.08620 | val 0.13031
  Regression -> MSE: 0.000157, MAE: 0.008809, R²: -0.0521
  Directional -> Accuracy: 0.5077, MCC: -0.1571, F1: 0.6596

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.10557 | val 0.14488
  Epoch 020 - train 0.10261 | val 0.14237
  Regression -> MSE: 0.000256, MAE: 0.011444, R²: -0.1306
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.10948 | val 0.12984
  Epoch 020 - train 0.10490 | val 0.12717
  Regression -> MSE: 0.000143, MAE: 0.008267, R²: 0.0051
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.09248 | val 0.11944
  Epoch 020 - train 0.09487 | val 0.11979
  Regression -> MSE: 0.000165, MAE: 0.010395, R²: 0.0023
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.10362 | val 0.12462
  Epoch 020 - train 0.10300 | val 0.12070
  Regression -> MSE: 0.000089, MAE: 0.007253, R²: -0.0439
  Directional -> Accuracy: 0.4138, MCC: -0.1078, F1: 0.1905

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.10509 | val 0.12627
  Epoch 020 - train 0.10398 | val 0.13439
  Regression -> MSE: 0.000218, MAE: 0.011054, R²: -0.0301
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.09288 | val 0.10158
  Epoch 020 - train 0.09312 | val 0.09577
  Regression -> MSE: 0.000097, MAE: 0.008184, R²: -0.0559
  Directional -> Accuracy: 0.5357, MCC: -0.0136, F1: 0.6750

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.10201 | val 0.08022
  Epoch 020 - train 0.10269 | val 0.07842
  Regression -> MSE: 0.000109, MAE: 0.009022, R²: -0.0586
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.10487 | val 0.09663
  Epoch 020 - train 0.10313 | val 0.10082
  Regression -> MSE: 0.000233, MAE: 0.012622, R²: -0.0060
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.09968 | val 0.11346
  Epoch 020 - train 0.09796 | val 0.11184
  Regression -> MSE: 0.000190, MAE: 0.008196, R²: -0.1409
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.10462 | val 0.08495
  Epoch 020 - train 0.10250 | val 0.08566
  Regression -> MSE: 0.000241, MAE: 0.011957, R²: -0.0168
  Directional -> Accuracy: 0.4634, MCC: 0.0000, F1: 0.0000

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.09994 | val 0.16490
  Epoch 020 - train 0.09567 | val 0.17318
  Regression -> MSE: 0.000232, MAE: 0.010035, R²: -0.0074
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.10130 | val 0.11480
  Epoch 020 - train 0.10235 | val 0.11483
  Regression -> MSE: 0.000136, MAE: 0.008254, R²: -0.0097
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.09874 | val 0.12235
  Epoch 020 - train 0.09922 | val 0.12309
  Regression -> MSE: 0.000203, MAE: 0.010832, R²: -0.0786
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.09473 | val 0.10559
  Epoch 020 - train 0.08708 | val 0.10603
  Regression -> MSE: 0.000277, MAE: 0.010856, R²: -0.0568
  Directional -> Accuracy: 0.4384, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.09849 | val 0.08200
  Epoch 020 - train 0.09480 | val 0.08487
  Regression -> MSE: 0.000166, MAE: 0.010367, R²: 0.0053
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.09700 | val 0.11873
  Epoch 020 - train 0.09811 | val 0.12176
  Regression -> MSE: 0.000188, MAE: 0.010605, R²: -0.0457
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.09433 | val 0.09519
  Epoch 020 - train 0.09385 | val 0.09443
  Regression -> MSE: 0.000350, MAE: 0.012321, R²: -0.0209
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.10509 | val 0.06579
  Epoch 020 - train 0.10569 | val 0.06960
  Regression -> MSE: 0.000125, MAE: 0.008474, R²: -0.1884
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.09814 | val 0.14012
  Epoch 020 - train 0.09729 | val 0.14063
  Regression -> MSE: 0.000223, MAE: 0.011430, R²: -0.0194
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.09826 | val 0.17219
  Epoch 020 - train 0.09601 | val 0.17302
  Regression -> MSE: 0.000084, MAE: 0.007134, R²: -0.0778
  Directional -> Accuracy: 0.5532, MCC: -0.0220, F1: 0.6769

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.09962 | val 0.07522
  Epoch 020 - train 0.09990 | val 0.07424
  Regression -> MSE: 0.000309, MAE: 0.013849, R²: -0.0036
  Directional -> Accuracy: 0.6327, MCC: 0.0000, F1: 0.0000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.10468 | val 0.06090
  Epoch 020 - train 0.10127 | val 0.06759
  Regression -> MSE: 0.000252, MAE: 0.011494, R²: -0.0332
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.10582 | val 0.11574
  Epoch 020 - train 0.10013 | val 0.11473
  Regression -> MSE: 0.000083, MAE: 0.007190, R²: -0.0248
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.10047 | val 0.13062
  Epoch 020 - train 0.09963 | val 0.13214
  Regression -> MSE: 0.000306, MAE: 0.014462, R²: 0.0015
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.09610 | val 0.10376
  Epoch 020 - train 0.09634 | val 0.10766
  Regression -> MSE: 0.000097, MAE: 0.007334, R²: 0.0095
  Directional -> Accuracy: 0.4318, MCC: 0.0000, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.10608 | val 0.12036
  Epoch 020 - train 0.10761 | val 0.12036
  Regression -> MSE: 0.000176, MAE: 0.010210, R²: -0.0223
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.09573 | val 0.14732
  Epoch 020 - train 0.09704 | val 0.14935
  Regression -> MSE: 0.000227, MAE: 0.011815, R²: -0.0182
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.09683 | val 0.11197
  Epoch 020 - train 0.09616 | val 0.11225
  Regression -> MSE: 0.000094, MAE: 0.007766, R²: -0.0228
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.10360 | val 0.15120
  Epoch 020 - train 0.10498 | val 0.15215
  Regression -> MSE: 0.000164, MAE: 0.010248, R²: 0.0007
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.09745 | val 0.12032
  Epoch 020 - train 0.09655 | val 0.11930
  Regression -> MSE: 0.000118, MAE: 0.008919, R²: -0.0179
  Directional -> Accuracy: 0.6071, MCC: 0.3245, F1: 0.7250

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.10387 | val 0.18985

[I 2026-02-23 02:31:48,183] Trial 198 finished with value: -0.011463036421762572 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 32, 'learning_rate': 7.508125771026019e-06, 'weight_decay': 2.5529673534192743e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.1442859563802421, 'early_stopping_min_delta': 0.006424002254214879}. Best is trial 157 with value: -0.011387287234516647.

  Epoch 020 - train 0.10440 | val 0.19587
  Regression -> MSE: 0.000237, MAE: 0.012460, R²: 0.0017
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.12710 | val 0.15594
  Epoch 020 - train 0.12514 | val 0.15581
  Regression -> MSE: 0.000267, MAE: 0.012978, R²: -0.0791
  Directional -> Accuracy: 0.5455, MCC: 0.0265, F1: 0.1463

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.13681 | val 0.13678
  Epoch 020 - train 0.13207 | val 0.18560
  Regression -> MSE: 0.000686, MAE: 0.019392, R²: -0.0028
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.12898 | val 0.20400
  Epoch 020 - train 0.12527 | val 0.20934
  Regression -> MSE: 0.000311, MAE: 0.014414, R²: -0.0011
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.10197 | val 0.12948
  Epoch 020 - train 0.10086 | val 0.14051
  Regression -> MSE: 0.000358, MAE: 0.014728, R²: -0.0262
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.12346 | val 0.11952
  Epoch 020 - train 0.12065 | val 0.11618
  Regression -> MSE: 0.000201, MAE: 0.009975, R²: 0.0141
  Directional -> Accuracy: 0.5882, MCC: 0.1757, F1: 0.6038

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.13083 | val 0.22841
  Epoch 020 - train 0.12365 | val 0.22640
  Regression -> MSE: 0.000558, MAE: 0.018165, R²: -0.0050
  Directional -> Accuracy: 0.4043, MCC: -0.2000, F1: 0.5000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.13976 | val 0.21116
  Epoch 020 - train 0.13930 | val 0.20669
  Regression -> MSE: 0.000246, MAE: 0.012065, R²: -0.0032
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.12451 | val 0.17482
  Epoch 020 - train 0.12484 | val 0.15799
  Regression -> MSE: 0.000625, MAE: 0.019888, R²: -0.0469
  Directional -> Accuracy: 0.4091, MCC: -0.1132, F1: 0.4800

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.12220 | val 0.14851
  Epoch 020 - train 0.11692 | val 0.14947
  Regression -> MSE: 0.000453, MAE: 0.016846, R²: -0.1809
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.12269 | val 0.16520
  Epoch 020 - train 0.12204 | val 0.16372
  Regression -> MSE: 0.000242, MAE: 0.011959, R²: -0.0009
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.11569 | val 0.17178
  Epoch 020 - train 0.11771 | val 0.17081
  Regression -> MSE: 0.000341, MAE: 0.013942, R²: -0.0954
  Directional -> Accuracy: 0.5200, MCC: -0.0401, F1: 0.1429

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.13289 | val 0.14278
  Epoch 020 - train 0.12986 | val 0.14368
  Regression -> MSE: 0.000677, MAE: 0.019504, R²: 0.0004
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.12521 | val 0.12031
  Epoch 020 - train 0.12573 | val 0.11772
  Regression -> MSE: 0.000142, MAE: 0.009374, R²: -0.0256
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.11743 | val 0.15456
  Epoch 020 - train 0.12140 | val 0.15265
  Regression -> MSE: 0.000238, MAE: 0.010982, R²: -0.0579
  Directional -> Accuracy: 0.4590, MCC: -0.0806, F1: 0.3774

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.12134 | val 0.25389
  Epoch 020 - train 0.11981 | val 0.28740
  Regression -> MSE: 0.000365, MAE: 0.015931, R²: -0.0079
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.12961 | val 0.13833
  Epoch 020 - train 0.12859 | val 0.13778
  Regression -> MSE: 0.000108, MAE: 0.007982, R²: -0.0013
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.12700 | val 0.20851
  Epoch 020 - train 0.12887 | val 0.21214
  Regression -> MSE: 0.000156, MAE: 0.009556, R²: -0.0039
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.12584 | val 0.14900
  Epoch 020 - train 0.12361 | val 0.15225
  Regression -> MSE: 0.000273, MAE: 0.013097, R²: -0.0041
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.11535 | val 0.16012
  Epoch 020 - train 0.11338 | val 0.15930
  Regression -> MSE: 0.000170, MAE: 0.009220, R²: -0.1357
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.12784 | val 0.17021
  Epoch 020 - train 0.12781 | val 0.16996
  Regression -> MSE: 0.000239, MAE: 0.011035, R²: -0.0546
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.12468 | val 0.15873
  Epoch 020 - train 0.12800 | val 0.16470
  Regression -> MSE: 0.000147, MAE: 0.008542, R²: -0.0227
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.12430 | val 0.15436
  Epoch 020 - train 0.12609 | val 0.15630
  Regression -> MSE: 0.000167, MAE: 0.010674, R²: -0.0087
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.13515 | val 0.14489
  Epoch 020 - train 0.13559 | val 0.14423
  Regression -> MSE: 0.000094, MAE: 0.007476, R²: -0.1008
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.12247 | val 0.14915
  Epoch 020 - train 0.12440 | val 0.14850
  Regression -> MSE: 0.000212, MAE: 0.011126, R²: 0.0005
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.11477 | val 0.11036
  Epoch 020 - train 0.11462 | val 0.10740
  Regression -> MSE: 0.000105, MAE: 0.008378, R²: -0.1424
  Directional -> Accuracy: 0.4107, MCC: -0.1511, F1: 0.3265

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.12467 | val 0.09760
  Epoch 020 - train 0.13258 | val 0.10270
  Regression -> MSE: 0.000107, MAE: 0.008922, R²: -0.0405
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.13067 | val 0.11654
  Epoch 020 - train 0.13002 | val 0.11541
  Regression -> MSE: 0.000233, MAE: 0.012599, R²: -0.0055
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.13176 | val 0.14351
  Epoch 020 - train 0.13441 | val 0.14380
  Regression -> MSE: 0.000191, MAE: 0.008216, R²: -0.1466
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.12336 | val 0.10815
  Epoch 020 - train 0.12454 | val 0.10619
  Regression -> MSE: 0.000238, MAE: 0.011911, R²: -0.0049
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.13058 | val 0.19436
  Epoch 020 - train 0.13253 | val 0.19484
  Regression -> MSE: 0.000231, MAE: 0.009876, R²: -0.0005
  Directional -> Accuracy: 0.4884, MCC: -0.0238, F1: 0.4762

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.12915 | val 0.14934
  Epoch 020 - train 0.12791 | val 0.19448
  Regression -> MSE: 0.000135, MAE: 0.008187, R²: 0.0021
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.13900 | val 0.15360
  Epoch 020 - train 0.12931 | val 0.15011
  Regression -> MSE: 0.000189, MAE: 0.010343, R²: -0.0013
  Directional -> Accuracy: 0.5200, MCC: 0.0018, F1: 0.6250

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.11391 | val 0.14056
  Epoch 020 - train 0.11167 | val 0.13977
  Regression -> MSE: 0.000267, MAE: 0.010541, R²: -0.0182
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.11129 | val 0.10406
  Epoch 020 - train 0.10891 | val 0.10415
  Regression -> MSE: 0.000169, MAE: 0.010366, R²: -0.0140
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.12051 | val 0.13832
  Epoch 020 - train 0.11837 | val 0.14779
  Regression -> MSE: 0.000189, MAE: 0.010633, R²: -0.0482
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.11717 | val 0.11730
  Epoch 020 - train 0.11250 | val 0.11815
  Regression -> MSE: 0.000343, MAE: 0.011978, R²: -0.0010
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.13917 | val 0.08438
  Epoch 020 - train 0.13439 | val 0.09423
  Regression -> MSE: 0.000130, MAE: 0.008566, R²: -0.2402
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.12326 | val 0.18937
  Epoch 020 - train 0.12539 | val 0.20060
  Regression -> MSE: 0.000219, MAE: 0.011288, R²: -0.0000
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.12496 | val 0.22067
  Epoch 020 - train 0.12095 | val 0.27850
  Regression -> MSE: 0.000086, MAE: 0.007233, R²: -0.1013
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.12295 | val 0.09216
  Epoch 020 - train 0.12146 | val 0.08856
  Regression -> MSE: 0.000309, MAE: 0.013875, R²: -0.0055
  Directional -> Accuracy: 0.6327, MCC: 0.0000, F1: 0.0000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.14004 | val 0.07656
  Epoch 020 - train 0.14147 | val 0.08128
  Regression -> MSE: 0.000245, MAE: 0.011557, R²: -0.0068
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.0000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.12459 | val 0.15002
  Epoch 020 - train 0.12376 | val 0.15031
  Regression -> MSE: 0.000081, MAE: 0.007082, R²: -0.0007
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.12456 | val 0.15694
  Epoch 020 - train 0.12898 | val 0.15690
  Regression -> MSE: 0.000308, MAE: 0.014481, R²: -0.0025
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.13013 | val 0.12876
  Epoch 020 - train 0.12832 | val 0.12593
  Regression -> MSE: 0.000098, MAE: 0.007378, R²: -0.0020
  Directional -> Accuracy: 0.4318, MCC: 0.0000, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.13818 | val 0.14616
  Epoch 020 - train 0.13121 | val 0.15290
  Regression -> MSE: 0.000173, MAE: 0.009935, R²: -0.0052
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.11768 | val 0.15216
  Epoch 020 - train 0.11627 | val 0.16014
  Regression -> MSE: 0.000224, MAE: 0.011816, R²: -0.0052
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.12766 | val 0.14413
  Epoch 020 - train 0.12903 | val 0.14771
  Regression -> MSE: 0.000093, MAE: 0.007678, R²: -0.0074
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.12854 | val 0.19545
  Epoch 020 - train 0.13026 | val 0.20964
  Regression -> MSE: 0.000164, MAE: 0.010261, R²: -0.0009
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.12750 | val 0.15920
  Epoch 020 - train 0.12469 | val 0.15743
  Regression -> MSE: 0.000125, MAE: 0.009041, R²: -0.0825
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.13929 | val 0.17318

[I 2026-02-23 02:34:26,248] Trial 199 finished with value: -0.011467146445319383 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.30000000000000004, 'batch_size': 32, 'learning_rate': 2.404118939556085e-06, 'weight_decay': 5.601457125371472e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.1858535568994415, 'early_stopping_min_delta': 0.006230567372692175}. Best is trial 157 with value: -0.011387287234516647.

  Epoch 020 - train 0.13755 | val 0.17360
  Regression -> MSE: 0.000238, MAE: 0.012367, R²: -0.0025
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.15369 | val 0.22223
  Epoch 020 - train 0.15626 | val 0.22250
  Regression -> MSE: 0.000253, MAE: 0.012737, R²: -0.0219
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.15463 | val 0.15219
  Epoch 020 - train 0.15604 | val 0.15593
  Regression -> MSE: 0.000705, MAE: 0.019719, R²: -0.0305
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.15179 | val 0.25151
  Epoch 020 - train 0.15113 | val 0.25002
  Regression -> MSE: 0.000311, MAE: 0.014478, R²: -0.0015
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.13181 | val 0.14658
  Epoch 020 - train 0.12817 | val 0.14242
  Regression -> MSE: 0.000352, MAE: 0.014663, R²: -0.0079
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.15795 | val 0.16401
  Epoch 020 - train 0.15573 | val 0.16682
  Regression -> MSE: 0.000206, MAE: 0.010374, R²: -0.0117
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.14248 | val 0.28915
  Epoch 020 - train 0.14588 | val 0.28934
  Regression -> MSE: 0.000586, MAE: 0.018709, R²: -0.0556
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.14814 | val 0.19412
  Epoch 020 - train 0.15267 | val 0.19396
  Regression -> MSE: 0.000244, MAE: 0.012017, R²: 0.0041
  Directional -> Accuracy: 0.4638, MCC: 0.0205, F1: 0.5316

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.14535 | val 0.16551
  Epoch 020 - train 0.15436 | val 0.16227
  Regression -> MSE: 0.000629, MAE: 0.019620, R²: -0.0532
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.13570 | val 0.19218
  Epoch 020 - train 0.13742 | val 0.19620
  Regression -> MSE: 0.000387, MAE: 0.015849, R²: -0.0089
  Directional -> Accuracy: 0.6327, MCC: 0.2973, F1: 0.6538

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.15723 | val 0.22931
  Epoch 020 - train 0.15553 | val 0.22651
  Regression -> MSE: 0.000248, MAE: 0.012521, R²: -0.0256
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.14150 | val 0.20881
  Epoch 020 - train 0.13857 | val 0.20969
  Regression -> MSE: 0.000323, MAE: 0.013612, R²: -0.0399
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.15590 | val 0.18699
  Epoch 020 - train 0.15718 | val 0.18917
  Regression -> MSE: 0.000674, MAE: 0.019399, R²: 0.0048
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.14961 | val 0.21566
  Epoch 020 - train 0.14617 | val 0.23139
  Regression -> MSE: 0.000138, MAE: 0.009072, R²: -0.0009
  Directional -> Accuracy: 0.5814, MCC: 0.1240, F1: 0.1818

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.14724 | val 0.20470
  Epoch 020 - train 0.14484 | val 0.20510
  Regression -> MSE: 0.000227, MAE: 0.010952, R²: -0.0099
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.15130 | val 0.30590
  Epoch 020 - train 0.15579 | val 0.30597
  Regression -> MSE: 0.000361, MAE: 0.016145, R²: 0.0028
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.15936 | val 0.15988
  Epoch 020 - train 0.15595 | val 0.15870
  Regression -> MSE: 0.000110, MAE: 0.008175, R²: -0.0191
  Directional -> Accuracy: 0.4571, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.15011 | val 0.30973
  Epoch 020 - train 0.14852 | val 0.31471
  Regression -> MSE: 0.000157, MAE: 0.009889, R²: -0.0066
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.14974 | val 0.22796
  Epoch 020 - train 0.14784 | val 0.22305
  Regression -> MSE: 0.000290, MAE: 0.013805, R²: -0.0669
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.14489 | val 0.21893
  Epoch 020 - train 0.14228 | val 0.21655
  Regression -> MSE: 0.000153, MAE: 0.008838, R²: -0.0211
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.16190 | val 0.23764
  Epoch 020 - train 0.15968 | val 0.23326
  Regression -> MSE: 0.000230, MAE: 0.011012, R²: -0.0162
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.15970 | val 0.21830
  Epoch 020 - train 0.16230 | val 0.21922
  Regression -> MSE: 0.000146, MAE: 0.008472, R²: -0.0216
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.14534 | val 0.17019
  Epoch 020 - train 0.14312 | val 0.17101
  Regression -> MSE: 0.000177, MAE: 0.010263, R²: -0.0691
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.15712 | val 0.20494
  Epoch 020 - train 0.15323 | val 0.20348
  Regression -> MSE: 0.000096, MAE: 0.007586, R²: -0.1321
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.14780 | val 0.24885
  Epoch 020 - train 0.14774 | val 0.24677
  Regression -> MSE: 0.000216, MAE: 0.011476, R²: -0.0196
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.14222 | val 0.14154
  Epoch 020 - train 0.14217 | val 0.14216
  Regression -> MSE: 0.000096, MAE: 0.008155, R²: -0.0479
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.15791 | val 0.12076
  Epoch 020 - train 0.15563 | val 0.13181
  Regression -> MSE: 0.000104, MAE: 0.008795, R²: -0.0044
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.14937 | val 0.15245
  Epoch 020 - train 0.15491 | val 0.15293
  Regression -> MSE: 0.000233, MAE: 0.012607, R²: -0.0077
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.15380 | val 0.20887
  Epoch 020 - train 0.15094 | val 0.20999
  Regression -> MSE: 0.000177, MAE: 0.007915, R²: -0.0642
  Directional -> Accuracy: 0.5263, MCC: -0.1044, F1: 0.6824

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.14726 | val 0.12541
  Epoch 020 - train 0.14779 | val 0.13028
  Regression -> MSE: 0.000236, MAE: 0.011845, R²: 0.0044
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.16917 | val 0.23480
  Epoch 020 - train 0.15883 | val 0.23746
  Regression -> MSE: 0.000230, MAE: 0.009864, R²: 0.0001
  Directional -> Accuracy: 0.5814, MCC: 0.1673, F1: 0.4706

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.16672 | val 0.21040
  Epoch 020 - train 0.16175 | val 0.21845
  Regression -> MSE: 0.000145, MAE: 0.008773, R²: -0.0744
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.15440 | val 0.20245
  Epoch 020 - train 0.15262 | val 0.20433
  Regression -> MSE: 0.000188, MAE: 0.010590, R²: -0.0010
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.13495 | val 0.17147
  Epoch 020 - train 0.13607 | val 0.17120
  Regression -> MSE: 0.000270, MAE: 0.010616, R²: -0.0306
  Directional -> Accuracy: 0.5479, MCC: 0.1054, F1: 0.5600

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.15153 | val 0.15438
  Epoch 020 - train 0.14568 | val 0.21671
  Regression -> MSE: 0.000168, MAE: 0.010364, R²: -0.0098
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.14202 | val 0.15374
  Epoch 020 - train 0.14290 | val 0.16055
  Regression -> MSE: 0.000181, MAE: 0.010321, R²: -0.0072
  Directional -> Accuracy: 0.5227, MCC: 0.0547, F1: 0.5532

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.14634 | val 0.15374
  Epoch 020 - train 0.15002 | val 0.15209
  Regression -> MSE: 0.000355, MAE: 0.011853, R²: -0.0372
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.15949 | val 0.09770
  Epoch 020 - train 0.16271 | val 0.09752
  Regression -> MSE: 0.000117, MAE: 0.008360, R²: -0.1096
  Directional -> Accuracy: 0.3721, MCC: -0.2967, F1: 0.4906

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.14761 | val 0.20886
  Epoch 020 - train 0.14753 | val 0.20952
  Regression -> MSE: 0.000220, MAE: 0.011316, R²: -0.0086
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.14981 | val 0.27026
  Epoch 020 - train 0.14684 | val 0.27683
  Regression -> MSE: 0.000086, MAE: 0.007234, R²: -0.1024
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.15620 | val 0.12083
  Epoch 020 - train 0.15180 | val 0.13552
  Regression -> MSE: 0.000310, MAE: 0.013837, R²: -0.0074
  Directional -> Accuracy: 0.6327, MCC: 0.0000, F1: 0.0000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.15802 | val 0.09409
  Epoch 020 - train 0.15182 | val 0.09206
  Regression -> MSE: 0.000258, MAE: 0.011475, R²: -0.0569
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.14635 | val 0.18991
  Epoch 020 - train 0.15106 | val 0.19184
  Regression -> MSE: 0.000084, MAE: 0.007078, R²: -0.0357
  Directional -> Accuracy: 0.5067, MCC: 0.0022, F1: 0.0513

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.15254 | val 0.18617
  Epoch 020 - train 0.15462 | val 0.18292
  Regression -> MSE: 0.000313, MAE: 0.014223, R²: -0.0212
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.15367 | val 0.15525
  Epoch 020 - train 0.15351 | val 0.14803
  Regression -> MSE: 0.000097, MAE: 0.007213, R²: 0.0153
  Directional -> Accuracy: 0.5227, MCC: 0.0212, F1: 0.5882

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.15533 | val 0.18691
  Epoch 020 - train 0.14921 | val 0.19906
  Regression -> MSE: 0.000173, MAE: 0.009832, R²: -0.0045
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.14563 | val 0.32247
  Epoch 020 - train 0.14789 | val 0.32542
  Regression -> MSE: 0.000243, MAE: 0.012156, R²: -0.0886
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.15005 | val 0.17498
  Epoch 020 - train 0.14779 | val 0.17467
  Regression -> MSE: 0.000094, MAE: 0.007741, R²: -0.0204
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.16235 | val 0.26731
  Epoch 020 - train 0.15779 | val 0.27397
  Regression -> MSE: 0.000165, MAE: 0.010261, R²: -0.0083
  Directional -> Accuracy: 0.5000, MCC: 0.0521, F1: 0.1818

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.14684 | val 0.19548
  Epoch 020 - train 0.14531 | val 0.19487
  Regression -> MSE: 0.000121, MAE: 0.008957, R²: -0.0432
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.15476 | val 0.23545

[I 2026-02-23 02:35:43,566] Trial 200 finished with value: -0.011462824665763436 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 32, 'learning_rate': 1.6347641052744257e-06, 'weight_decay': 3.62036390240975e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.23032995361683395, 'early_stopping_min_delta': 0.006749865249097592}. Best is trial 157 with value: -0.011387287234516647.

  Epoch 020 - train 0.15499 | val 0.23529
  Regression -> MSE: 0.000243, MAE: 0.012380, R²: -0.0229
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.07482 | val 0.10008
  Epoch 020 - train 0.07354 | val 0.09972
  Regression -> MSE: 0.000248, MAE: 0.012537, R²: -0.0004
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.07082 | val 0.06896
  Epoch 020 - train 0.06963 | val 0.07307
  Regression -> MSE: 0.000697, MAE: 0.019570, R²: -0.0188
  Directional -> Accuracy: 0.6087, MCC: 0.1761, F1: 0.7188

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.07230 | val 0.11429
  Epoch 020 - train 0.07346 | val 0.11320
  Regression -> MSE: 0.000323, MAE: 0.014539, R²: -0.0410
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.06076 | val 0.05935
  Epoch 020 - train 0.05993 | val 0.05981
  Regression -> MSE: 0.000350, MAE: 0.014591, R²: -0.0031
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.07051 | val 0.07425
  Epoch 020 - train 0.06996 | val 0.08114
  Regression -> MSE: 0.000204, MAE: 0.010156, R²: 0.0002
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.06817 | val 0.12970
  Epoch 020 - train 0.06570 | val 0.12815
  Regression -> MSE: 0.000575, MAE: 0.018476, R²: -0.0361
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.07218 | val 0.08616
  Epoch 020 - train 0.07166 | val 0.08597
  Regression -> MSE: 0.000253, MAE: 0.011992, R²: -0.0301
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.07300 | val 0.10331
  Epoch 020 - train 0.07156 | val 0.10147
  Regression -> MSE: 0.000667, MAE: 0.020495, R²: -0.1159
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.07442 | val 0.08379
  Epoch 020 - train 0.07321 | val 0.08819
  Regression -> MSE: 0.000396, MAE: 0.015995, R²: -0.0331
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.07321 | val 0.09441
  Epoch 020 - train 0.07119 | val 0.09176
  Regression -> MSE: 0.000243, MAE: 0.012077, R²: -0.0053
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.07624 | val 0.09873
  Epoch 020 - train 0.07329 | val 0.09869
  Regression -> MSE: 0.000318, MAE: 0.013588, R²: -0.0240
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.07314 | val 0.08678
  Epoch 020 - train 0.07309 | val 0.08880
  Regression -> MSE: 0.000681, MAE: 0.019524, R²: -0.0057
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.07488 | val 0.07088
  Epoch 020 - train 0.07275 | val 0.07162
  Regression -> MSE: 0.000142, MAE: 0.009372, R²: -0.0273
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.06931 | val 0.08836
  Epoch 020 - train 0.06847 | val 0.08805
  Regression -> MSE: 0.000227, MAE: 0.010751, R²: -0.0105
  Directional -> Accuracy: 0.4918, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.07311 | val 0.14415
  Epoch 020 - train 0.07338 | val 0.14925
  Regression -> MSE: 0.000362, MAE: 0.016077, R²: -0.0000
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.07787 | val 0.07458
  Epoch 020 - train 0.07560 | val 0.07534
  Regression -> MSE: 0.000108, MAE: 0.008052, R²: -0.0025
  Directional -> Accuracy: 0.4571, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.06906 | val 0.11955
  Epoch 020 - train 0.06911 | val 0.12431
  Regression -> MSE: 0.000156, MAE: 0.009690, R²: -0.0003
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.07215 | val 0.07170
  Epoch 020 - train 0.07286 | val 0.07161
  Regression -> MSE: 0.000287, MAE: 0.013709, R²: -0.0548
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.06776 | val 0.09335
  Epoch 020 - train 0.06708 | val 0.09293
  Regression -> MSE: 0.000169, MAE: 0.009182, R²: -0.1299
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.07276 | val 0.10264
  Epoch 020 - train 0.07214 | val 0.10096
  Regression -> MSE: 0.000248, MAE: 0.011275, R²: -0.0963
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.07280 | val 0.08715
  Epoch 020 - train 0.07356 | val 0.08731
  Regression -> MSE: 0.000143, MAE: 0.008311, R²: -0.0002
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.06844 | val 0.08711
  Epoch 020 - train 0.06852 | val 0.08783
  Regression -> MSE: 0.000166, MAE: 0.010592, R²: -0.0030
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.07204 | val 0.08227
  Epoch 020 - train 0.07451 | val 0.08370
  Regression -> MSE: 0.000087, MAE: 0.007156, R²: -0.0224
  Directional -> Accuracy: 0.5690, MCC: 0.0557, F1: 0.6988

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.07125 | val 0.08436
  Epoch 020 - train 0.07092 | val 0.08802
  Regression -> MSE: 0.000214, MAE: 0.011368, R²: -0.0091
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.06575 | val 0.06716
  Epoch 020 - train 0.06626 | val 0.06800
  Regression -> MSE: 0.000093, MAE: 0.008101, R²: -0.0124
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.07365 | val 0.05621
  Epoch 020 - train 0.07232 | val 0.05591
  Regression -> MSE: 0.000106, MAE: 0.008877, R²: -0.0246
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.07484 | val 0.06817
  Epoch 020 - train 0.07200 | val 0.06928
  Regression -> MSE: 0.000232, MAE: 0.012584, R²: -0.0043
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.07059 | val 0.08302
  Epoch 020 - train 0.07047 | val 0.08363
  Regression -> MSE: 0.000186, MAE: 0.008083, R²: -0.1203
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.07675 | val 0.06462
  Epoch 020 - train 0.07714 | val 0.06932
  Regression -> MSE: 0.000239, MAE: 0.011951, R²: -0.0095
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.07089 | val 0.11388
  Epoch 020 - train 0.06938 | val 0.12118
  Regression -> MSE: 0.000233, MAE: 0.010026, R²: -0.0099
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.07491 | val 0.08178
  Epoch 020 - train 0.07337 | val 0.08289
  Regression -> MSE: 0.000135, MAE: 0.008193, R²: -0.0004
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.07462 | val 0.09297
  Epoch 020 - train 0.07399 | val 0.09326
  Regression -> MSE: 0.000189, MAE: 0.010437, R²: -0.0021
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.06260 | val 0.08238
  Epoch 020 - train 0.06372 | val 0.08250
  Regression -> MSE: 0.000275, MAE: 0.010758, R²: -0.0493
  Directional -> Accuracy: 0.4384, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.07797 | val 0.06087
  Epoch 020 - train 0.07107 | val 0.06189
  Regression -> MSE: 0.000171, MAE: 0.010387, R²: -0.0258
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.06921 | val 0.08200
  Epoch 020 - train 0.07000 | val 0.08991
  Regression -> MSE: 0.000185, MAE: 0.010551, R²: -0.0305
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.06764 | val 0.06812
  Epoch 020 - train 0.06716 | val 0.06910
  Regression -> MSE: 0.000344, MAE: 0.011701, R²: -0.0050
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.07851 | val 0.04901
  Epoch 020 - train 0.07795 | val 0.05358
  Regression -> MSE: 0.000117, MAE: 0.008336, R²: -0.1124
  Directional -> Accuracy: 0.4884, MCC: -0.0261, F1: 0.5217

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.07554 | val 0.09739
  Epoch 020 - train 0.07572 | val 0.09695
  Regression -> MSE: 0.000219, MAE: 0.011306, R²: -0.0018
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.07144 | val 0.11926
  Epoch 020 - train 0.07054 | val 0.12421
  Regression -> MSE: 0.000085, MAE: 0.007195, R²: -0.0931
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.07115 | val 0.06084
  Epoch 020 - train 0.06943 | val 0.05717
  Regression -> MSE: 0.000336, MAE: 0.015208, R²: -0.0916
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.08187 | val 0.04439
  Epoch 020 - train 0.07873 | val 0.04400
  Regression -> MSE: 0.000245, MAE: 0.011580, R²: -0.0063
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.0000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.07011 | val 0.08508
  Epoch 020 - train 0.06928 | val 0.08598
  Regression -> MSE: 0.000083, MAE: 0.007051, R²: -0.0259
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.07082 | val 0.08968
  Epoch 020 - train 0.07279 | val 0.09615
  Regression -> MSE: 0.000307, MAE: 0.014497, R²: -0.0010
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.07329 | val 0.07558
  Epoch 020 - train 0.07325 | val 0.07760
  Regression -> MSE: 0.000099, MAE: 0.007314, R²: -0.0054
  Directional -> Accuracy: 0.3636, MCC: -0.3103, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.07579 | val 0.08516
  Epoch 020 - train 0.07466 | val 0.09219
  Regression -> MSE: 0.000172, MAE: 0.009729, R²: -0.0008
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.06546 | val 0.08819
  Epoch 020 - train 0.06685 | val 0.09215
  Regression -> MSE: 0.000223, MAE: 0.011758, R²: -0.0004
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.07342 | val 0.07705
  Epoch 020 - train 0.07207 | val 0.07585
  Regression -> MSE: 0.000092, MAE: 0.007643, R²: -0.0001
  Directional -> Accuracy: 0.4737, MCC: -0.0418, F1: 0.5161

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.07483 | val 0.10760
  Epoch 020 - train 0.07513 | val 0.10825
  Regression -> MSE: 0.000164, MAE: 0.010259, R²: -0.0004
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.07120 | val 0.08875
  Epoch 020 - train 0.07104 | val 0.08852
  Regression -> MSE: 0.000125, MAE: 0.009025, R²: -0.0756
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.07012 | val 0.11515

[I 2026-02-23 02:38:25,047] Trial 201 finished with value: -0.011479598958403654 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 32, 'learning_rate': 5.0506159389983134e-06, 'weight_decay': 2.419054072585664e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.10123388047033152, 'early_stopping_min_delta': 0.006077859727973203}. Best is trial 157 with value: -0.011387287234516647.

  Epoch 020 - train 0.07118 | val 0.12225
  Regression -> MSE: 0.000241, MAE: 0.012351, R²: -0.0171
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.11163 | val 0.17022
  Epoch 020 - train 0.11130 | val 0.16926
  Regression -> MSE: 0.000267, MAE: 0.013161, R²: -0.0765
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.10388 | val 0.10182
  Epoch 020 - train 0.10321 | val 0.10490
  Regression -> MSE: 0.000699, MAE: 0.019595, R²: -0.0213
  Directional -> Accuracy: 0.6522, MCC: 0.3643, F1: 0.6190

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.11487 | val 0.18258
  Epoch 020 - train 0.11646 | val 0.19137
  Regression -> MSE: 0.000311, MAE: 0.014440, R²: -0.0019
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.09196 | val 0.12569
  Epoch 020 - train 0.09031 | val 0.13792
  Regression -> MSE: 0.000353, MAE: 0.014639, R²: -0.0116
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.11355 | val 0.10639
  Epoch 020 - train 0.10876 | val 0.10185
  Regression -> MSE: 0.000207, MAE: 0.010206, R²: -0.0143
  Directional -> Accuracy: 0.5490, MCC: 0.0806, F1: 0.6761

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.10386 | val 0.20237
  Epoch 020 - train 0.10360 | val 0.20331
  Regression -> MSE: 0.000565, MAE: 0.018266, R²: -0.0187
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.11136 | val 0.13283
  Epoch 020 - train 0.11174 | val 0.13311
  Regression -> MSE: 0.000245, MAE: 0.012046, R²: 0.0019
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.10718 | val 0.16277
  Epoch 020 - train 0.10529 | val 0.17257
  Regression -> MSE: 0.000667, MAE: 0.020502, R²: -0.1161
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.10288 | val 0.13058
  Epoch 020 - train 0.10577 | val 0.12684
  Regression -> MSE: 0.000392, MAE: 0.015991, R²: -0.0221
  Directional -> Accuracy: 0.3265, MCC: -0.3373, F1: 0.4211

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.11062 | val 0.14513
  Epoch 020 - train 0.10889 | val 0.14675
  Regression -> MSE: 0.000246, MAE: 0.011629, R²: -0.0183
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.10113 | val 0.16133
  Epoch 020 - train 0.10143 | val 0.16868
  Regression -> MSE: 0.000313, MAE: 0.013655, R²: -0.0055
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.11316 | val 0.13261
  Epoch 020 - train 0.11085 | val 0.13309
  Regression -> MSE: 0.000681, MAE: 0.019522, R²: -0.0059
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.10685 | val 0.10891
  Epoch 020 - train 0.10547 | val 0.10944
  Regression -> MSE: 0.000146, MAE: 0.009575, R²: -0.0557
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.10266 | val 0.15795
  Epoch 020 - train 0.10355 | val 0.15554
  Regression -> MSE: 0.000224, MAE: 0.010709, R²: 0.0053
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.10952 | val 0.21578
  Epoch 020 - train 0.10547 | val 0.21725
  Regression -> MSE: 0.000365, MAE: 0.015991, R²: -0.0067
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.11177 | val 0.11284
  Epoch 020 - train 0.11061 | val 0.11739
  Regression -> MSE: 0.000108, MAE: 0.007994, R²: 0.0020
  Directional -> Accuracy: 0.5429, MCC: 0.0430, F1: 0.6596

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.10399 | val 0.18453
  Epoch 020 - train 0.10262 | val 0.19850
  Regression -> MSE: 0.000156, MAE: 0.009689, R²: 0.0017
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.10805 | val 0.10877
  Epoch 020 - train 0.10708 | val 0.10947
  Regression -> MSE: 0.000272, MAE: 0.013023, R²: 0.0017
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.10034 | val 0.14760
  Epoch 020 - train 0.09978 | val 0.14691
  Regression -> MSE: 0.000162, MAE: 0.008951, R²: -0.0822
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.11126 | val 0.15148
  Epoch 020 - train 0.11288 | val 0.15057
  Regression -> MSE: 0.000246, MAE: 0.011210, R²: -0.0867
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.11310 | val 0.13847
  Epoch 020 - train 0.10905 | val 0.14120
  Regression -> MSE: 0.000143, MAE: 0.008303, R²: 0.0001
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.10491 | val 0.13250
  Epoch 020 - train 0.10006 | val 0.13339
  Regression -> MSE: 0.000166, MAE: 0.010307, R²: -0.0044
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.11614 | val 0.12807
  Epoch 020 - train 0.11816 | val 0.12837
  Regression -> MSE: 0.000085, MAE: 0.007057, R²: -0.0032
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.11042 | val 0.13364
  Epoch 020 - train 0.10866 | val 0.13221
  Regression -> MSE: 0.000215, MAE: 0.011054, R²: -0.0148
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.10124 | val 0.09782
  Epoch 020 - train 0.09998 | val 0.09748
  Regression -> MSE: 0.000093, MAE: 0.008094, R²: -0.0078
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.11285 | val 0.08994
  Epoch 020 - train 0.10831 | val 0.08595
  Regression -> MSE: 0.000112, MAE: 0.009095, R²: -0.0869
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.11289 | val 0.10582
  Epoch 020 - train 0.11189 | val 0.11388
  Regression -> MSE: 0.000232, MAE: 0.012587, R²: -0.0034
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.10905 | val 0.13569
  Epoch 020 - train 0.10710 | val 0.13724
  Regression -> MSE: 0.000173, MAE: 0.007849, R²: -0.0412
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.11163 | val 0.09581
  Epoch 020 - train 0.11185 | val 0.09333
  Regression -> MSE: 0.000238, MAE: 0.011941, R²: -0.0071
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.12216 | val 0.16702
  Epoch 020 - train 0.11374 | val 0.16850
  Regression -> MSE: 0.000231, MAE: 0.009861, R²: -0.0010
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.11006 | val 0.12869
  Epoch 020 - train 0.11096 | val 0.13174
  Regression -> MSE: 0.000135, MAE: 0.008198, R²: -0.0015
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.11159 | val 0.13752
  Epoch 020 - train 0.10814 | val 0.13472
  Regression -> MSE: 0.000189, MAE: 0.010460, R²: -0.0014
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.10206 | val 0.13743
  Epoch 020 - train 0.09695 | val 0.13496
  Regression -> MSE: 0.000263, MAE: 0.010598, R²: -0.0058
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.10588 | val 0.09370
  Epoch 020 - train 0.10925 | val 0.09352
  Regression -> MSE: 0.000167, MAE: 0.010377, R²: -0.0020
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.10491 | val 0.10821
  Epoch 020 - train 0.10391 | val 0.10868
  Regression -> MSE: 0.000182, MAE: 0.010309, R²: -0.0091
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.10320 | val 0.10360
  Epoch 020 - train 0.10283 | val 0.10537
  Regression -> MSE: 0.000342, MAE: 0.011862, R²: 0.0033
  Directional -> Accuracy: 0.4179, MCC: -0.0955, F1: 0.1333

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.11614 | val 0.07133
  Epoch 020 - train 0.11725 | val 0.07458
  Regression -> MSE: 0.000121, MAE: 0.008394, R²: -0.1545
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.11411 | val 0.15060
  Epoch 020 - train 0.11277 | val 0.15372
  Regression -> MSE: 0.000219, MAE: 0.011270, R²: -0.0006
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.10655 | val 0.19361
  Epoch 020 - train 0.10372 | val 0.20944
  Regression -> MSE: 0.000083, MAE: 0.007104, R²: -0.0682
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.10457 | val 0.08847
  Epoch 020 - train 0.10580 | val 0.08157
  Regression -> MSE: 0.000384, MAE: 0.016733, R²: -0.2471
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.11653 | val 0.06580
  Epoch 020 - train 0.11637 | val 0.06503
  Regression -> MSE: 0.000247, MAE: 0.011538, R²: -0.0128
  Directional -> Accuracy: 0.5000, MCC: 0.0574, F1: 0.2400

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.11367 | val 0.13846
  Epoch 020 - train 0.10658 | val 0.13945
  Regression -> MSE: 0.000081, MAE: 0.007067, R²: -0.0073
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.10816 | val 0.14108
  Epoch 020 - train 0.10733 | val 0.13205
  Regression -> MSE: 0.000308, MAE: 0.014333, R²: -0.0037
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.11954 | val 0.11395
  Epoch 020 - train 0.11777 | val 0.10955
  Regression -> MSE: 0.000102, MAE: 0.007548, R²: -0.0364
  Directional -> Accuracy: 0.4091, MCC: -0.1749, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.11849 | val 0.12974
  Epoch 020 - train 0.11605 | val 0.13559
  Regression -> MSE: 0.000172, MAE: 0.009677, R²: 0.0006
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.10649 | val 0.14201
  Epoch 020 - train 0.10496 | val 0.14812
  Regression -> MSE: 0.000228, MAE: 0.011825, R²: -0.0225
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.10959 | val 0.11871
  Epoch 020 - train 0.10620 | val 0.12116
  Regression -> MSE: 0.000093, MAE: 0.007664, R²: -0.0085
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.11730 | val 0.16647
  Epoch 020 - train 0.11970 | val 0.17026
  Regression -> MSE: 0.000165, MAE: 0.010306, R²: -0.0068
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.10727 | val 0.13674
  Epoch 020 - train 0.10465 | val 0.13789
  Regression -> MSE: 0.000118, MAE: 0.008950, R²: -0.0153
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.11181 | val 0.15975

[I 2026-02-23 02:41:02,999] Trial 202 finished with value: -0.011469672449817926 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 32, 'learning_rate': 6.065846787077196e-06, 'weight_decay': 4.745093592923954e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.16073410941834096, 'early_stopping_min_delta': 0.005606866777358956}. Best is trial 157 with value: -0.011387287234516647.

  Epoch 020 - train 0.10949 | val 0.17461
  Regression -> MSE: 0.000240, MAE: 0.012330, R²: -0.0114
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.09363 | val 0.12940
  Epoch 020 - train 0.08993 | val 0.13038
  Regression -> MSE: 0.000249, MAE: 0.012625, R²: -0.0070
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.08987 | val 0.09784
  Epoch 020 - train 0.08817 | val 0.11263
  Regression -> MSE: 0.000689, MAE: 0.019419, R²: -0.0060
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.09509 | val 0.14868
  Epoch 020 - train 0.09392 | val 0.15275
  Regression -> MSE: 0.000313, MAE: 0.014422, R²: -0.0077
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.07862 | val 0.08346
  Epoch 020 - train 0.07951 | val 0.08400
  Regression -> MSE: 0.000366, MAE: 0.014838, R²: -0.0479
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.09902 | val 0.10221
  Epoch 020 - train 0.09639 | val 0.10564
  Regression -> MSE: 0.000207, MAE: 0.010140, R²: -0.0185
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.08452 | val 0.16803
  Epoch 020 - train 0.08507 | val 0.16187
  Regression -> MSE: 0.000607, MAE: 0.019651, R²: -0.0939
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.09110 | val 0.11263
  Epoch 020 - train 0.09340 | val 0.11183
  Regression -> MSE: 0.000247, MAE: 0.012186, R²: -0.0046
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.09740 | val 0.10560
  Epoch 020 - train 0.10154 | val 0.09760
  Regression -> MSE: 0.000597, MAE: 0.018938, R²: 0.0013
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.09012 | val 0.11075
  Epoch 020 - train 0.08755 | val 0.11810
  Regression -> MSE: 0.000391, MAE: 0.015975, R²: -0.0189
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.09444 | val 0.11953
  Epoch 020 - train 0.09160 | val 0.12175
  Regression -> MSE: 0.000242, MAE: 0.011726, R²: -0.0042
  Directional -> Accuracy: 0.4429, MCC: -0.0227, F1: 0.5618

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.08535 | val 0.12900
  Epoch 020 - train 0.07955 | val 0.12919
  Regression -> MSE: 0.000311, MAE: 0.013640, R²: 0.0008
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.09542 | val 0.11219
  Epoch 020 - train 0.09647 | val 0.11695
  Regression -> MSE: 0.000679, MAE: 0.019558, R²: -0.0026
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.10046 | val 0.08991
  Epoch 020 - train 0.09579 | val 0.09001
  Regression -> MSE: 0.000138, MAE: 0.009097, R²: -0.0003
  Directional -> Accuracy: 0.5814, MCC: 0.1348, F1: 0.4706

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.08722 | val 0.11192
  Epoch 020 - train 0.08682 | val 0.11398
  Regression -> MSE: 0.000228, MAE: 0.010763, R²: -0.0119
  Directional -> Accuracy: 0.4918, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.09359 | val 0.18062
  Epoch 020 - train 0.08979 | val 0.18348
  Regression -> MSE: 0.000368, MAE: 0.015943, R²: -0.0157
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.09549 | val 0.09016
  Epoch 020 - train 0.09224 | val 0.08929
  Regression -> MSE: 0.000108, MAE: 0.007958, R²: -0.0035
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.09250 | val 0.14800
  Epoch 020 - train 0.08821 | val 0.15604
  Regression -> MSE: 0.000163, MAE: 0.010257, R²: -0.0484
  Directional -> Accuracy: 0.3729, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.09425 | val 0.09717
  Epoch 020 - train 0.09411 | val 0.09633
  Regression -> MSE: 0.000294, MAE: 0.013996, R²: -0.0790
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.08208 | val 0.12865
  Epoch 020 - train 0.08182 | val 0.12916
  Regression -> MSE: 0.000152, MAE: 0.008733, R²: -0.0158
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.09431 | val 0.13048
  Epoch 020 - train 0.09306 | val 0.12975
  Regression -> MSE: 0.000226, MAE: 0.010857, R²: 0.0014
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.09058 | val 0.11478
  Epoch 020 - train 0.09093 | val 0.12852
  Regression -> MSE: 0.000147, MAE: 0.008566, R²: -0.0279
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.08763 | val 0.12451
  Epoch 020 - train 0.09073 | val 0.12623
  Regression -> MSE: 0.000165, MAE: 0.010544, R²: -0.0009
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.09268 | val 0.11021
  Epoch 020 - train 0.09454 | val 0.11022
  Regression -> MSE: 0.000088, MAE: 0.007209, R²: -0.0335
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.09201 | val 0.11175
  Epoch 020 - train 0.09052 | val 0.11227
  Regression -> MSE: 0.000213, MAE: 0.011057, R²: -0.0067
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.08420 | val 0.08996
  Epoch 020 - train 0.08187 | val 0.09009
  Regression -> MSE: 0.000093, MAE: 0.008098, R²: -0.0103
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.09247 | val 0.07382
  Epoch 020 - train 0.08979 | val 0.07633
  Regression -> MSE: 0.000110, MAE: 0.009018, R²: -0.0649
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.09397 | val 0.09164
  Epoch 020 - train 0.09541 | val 0.09395
  Regression -> MSE: 0.000244, MAE: 0.012942, R²: -0.0533
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.09398 | val 0.10517
  Epoch 020 - train 0.08994 | val 0.10354
  Regression -> MSE: 0.000173, MAE: 0.007840, R²: -0.0409
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.09930 | val 0.07802
  Epoch 020 - train 0.09671 | val 0.07860
  Regression -> MSE: 0.000238, MAE: 0.011882, R²: -0.0044
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.09421 | val 0.14099
  Epoch 020 - train 0.09524 | val 0.14236
  Regression -> MSE: 0.000231, MAE: 0.009888, R²: -0.0010
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.09541 | val 0.11642
  Epoch 020 - train 0.09465 | val 0.11707
  Regression -> MSE: 0.000142, MAE: 0.008584, R²: -0.0508
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.09249 | val 0.11147
  Epoch 020 - train 0.09298 | val 0.11263
  Regression -> MSE: 0.000199, MAE: 0.010681, R²: -0.0550
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.07997 | val 0.10082
  Epoch 020 - train 0.07934 | val 0.10085
  Regression -> MSE: 0.000262, MAE: 0.010494, R²: -0.0023
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.08777 | val 0.07677
  Epoch 020 - train 0.08719 | val 0.07913
  Regression -> MSE: 0.000168, MAE: 0.010369, R²: -0.0108
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.08790 | val 0.09656
  Epoch 020 - train 0.08766 | val 0.10565
  Regression -> MSE: 0.000181, MAE: 0.010267, R²: -0.0031
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.09764 | val 0.09277
  Epoch 020 - train 0.09342 | val 0.09330
  Regression -> MSE: 0.000346, MAE: 0.012112, R²: -0.0104
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.10067 | val 0.05990
  Epoch 020 - train 0.10132 | val 0.06395
  Regression -> MSE: 0.000116, MAE: 0.008351, R²: -0.0991
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.09677 | val 0.12648
  Epoch 020 - train 0.09226 | val 0.12518
  Regression -> MSE: 0.000227, MAE: 0.011536, R²: -0.0375
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.09506 | val 0.15008
  Epoch 020 - train 0.09413 | val 0.15106
  Regression -> MSE: 0.000088, MAE: 0.007343, R²: -0.1335
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.08770 | val 0.06819
  Epoch 020 - train 0.08582 | val 0.06730
  Regression -> MSE: 0.000308, MAE: 0.013798, R²: -0.0024
  Directional -> Accuracy: 0.6327, MCC: 0.0000, F1: 0.0000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.10146 | val 0.05624
  Epoch 020 - train 0.10068 | val 0.05675
  Regression -> MSE: 0.000246, MAE: 0.011549, R²: -0.0111
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.0000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.08743 | val 0.10678
  Epoch 020 - train 0.08470 | val 0.10602
  Regression -> MSE: 0.000082, MAE: 0.007042, R²: -0.0200
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.09209 | val 0.10959
  Epoch 020 - train 0.09144 | val 0.11419
  Regression -> MSE: 0.000309, MAE: 0.014514, R²: -0.0066
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.09248 | val 0.09436
  Epoch 020 - train 0.08994 | val 0.09463
  Regression -> MSE: 0.000099, MAE: 0.007396, R²: -0.0045
  Directional -> Accuracy: 0.4318, MCC: 0.0000, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.10113 | val 0.11159
  Epoch 020 - train 0.10071 | val 0.12083
  Regression -> MSE: 0.000173, MAE: 0.009462, R²: -0.0095
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.08931 | val 0.11503
  Epoch 020 - train 0.08822 | val 0.12629
  Regression -> MSE: 0.000223, MAE: 0.011783, R²: -0.0021
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.09251 | val 0.09915
  Epoch 020 - train 0.09206 | val 0.09805
  Regression -> MSE: 0.000094, MAE: 0.007739, R²: -0.0159
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.09432 | val 0.13818
  Epoch 020 - train 0.09538 | val 0.14112
  Regression -> MSE: 0.000164, MAE: 0.010248, R²: 0.0007
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.08935 | val 0.11050
  Epoch 020 - train 0.09035 | val 0.11055
  Regression -> MSE: 0.000117, MAE: 0.008954, R²: -0.0121
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.09191 | val 0.13504

[I 2026-02-23 02:43:43,682] Trial 203 finished with value: -0.011448379668693519 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 32, 'learning_rate': 3.928819515116163e-06, 'weight_decay': 9.286720511420362e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.13138291129348614, 'early_stopping_min_delta': 0.006314527884291092}. Best is trial 157 with value: -0.011387287234516647.

  Epoch 020 - train 0.08993 | val 0.13586
  Regression -> MSE: 0.000237, MAE: 0.012431, R²: 0.0010
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.17649 | val 0.30453
  Epoch 020 - train 0.17352 | val 0.30515
  Regression -> MSE: 0.000252, MAE: 0.012708, R²: -0.0159
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.16952 | val 0.16023
  Epoch 020 - train 0.16774 | val 0.16220
  Regression -> MSE: 0.000679, MAE: 0.019355, R²: 0.0075
  Directional -> Accuracy: 0.5870, MCC: 0.1700, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.18129 | val 0.29238
  Epoch 020 - train 0.17583 | val 0.30389
  Regression -> MSE: 0.000311, MAE: 0.014454, R²: -0.0014
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.15105 | val 0.40485
  Epoch 020 - train 0.14721 | val 0.42079
  Regression -> MSE: 0.000395, MAE: 0.015360, R²: -0.1309
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.19012 | val 0.19687
  Epoch 020 - train 0.19095 | val 0.22669
  Regression -> MSE: 0.000208, MAE: 0.010492, R²: -0.0209
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.15798 | val 0.33314
  Epoch 020 - train 0.16256 | val 0.34218
  Regression -> MSE: 0.000589, MAE: 0.018747, R²: -0.0607
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.17557 | val 0.21658
  Epoch 020 - train 0.17540 | val 0.21717
  Regression -> MSE: 0.000249, MAE: 0.011961, R²: -0.0141
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.18802 | val 0.20789
  Epoch 020 - train 0.18482 | val 0.19884
  Regression -> MSE: 0.000602, MAE: 0.019218, R²: -0.0078
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.16939 | val 0.21717
  Epoch 020 - train 0.17034 | val 0.20970
  Regression -> MSE: 0.000440, MAE: 0.016775, R²: -0.1467
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.17821 | val 0.22303
  Epoch 020 - train 0.17902 | val 0.22249
  Regression -> MSE: 0.000241, MAE: 0.011809, R²: -0.0002
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.15973 | val 0.25864
  Epoch 020 - train 0.15129 | val 0.25992
  Regression -> MSE: 0.000312, MAE: 0.013624, R²: -0.0033
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.18079 | val 0.21185
  Epoch 020 - train 0.17948 | val 0.21736
  Regression -> MSE: 0.000684, MAE: 0.019757, R²: -0.0103
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.17212 | val 0.18361
  Epoch 020 - train 0.17628 | val 0.24293
  Regression -> MSE: 0.000144, MAE: 0.009451, R²: -0.0390
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.16074 | val 0.25334
  Epoch 020 - train 0.15810 | val 0.26515
  Regression -> MSE: 0.000229, MAE: 0.010831, R²: -0.0200
  Directional -> Accuracy: 0.4918, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.16471 | val 0.35518
  Epoch 020 - train 0.16691 | val 0.36285
  Regression -> MSE: 0.000372, MAE: 0.015946, R²: -0.0269
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.18295 | val 0.18190
  Epoch 020 - train 0.18600 | val 0.18220
  Regression -> MSE: 0.000108, MAE: 0.007965, R²: -0.0032
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.17100 | val 0.29852
  Epoch 020 - train 0.16725 | val 0.31678
  Regression -> MSE: 0.000156, MAE: 0.009556, R²: -0.0001
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.17885 | val 0.17133
  Epoch 020 - train 0.18025 | val 0.17105
  Regression -> MSE: 0.000276, MAE: 0.013280, R²: -0.0158
  Directional -> Accuracy: 0.5132, MCC: -0.0776, F1: 0.6337

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.16087 | val 0.23831
  Epoch 020 - train 0.15592 | val 0.23715
  Regression -> MSE: 0.000152, MAE: 0.008737, R²: -0.0162
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.18546 | val 0.24685
  Epoch 020 - train 0.18127 | val 0.24744
  Regression -> MSE: 0.000229, MAE: 0.010858, R²: -0.0122
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.16928 | val 0.22342
  Epoch 020 - train 0.16846 | val 0.23477
  Regression -> MSE: 0.000148, MAE: 0.008603, R²: -0.0329
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.16614 | val 0.20052
  Epoch 020 - train 0.16160 | val 0.20065
  Regression -> MSE: 0.000169, MAE: 0.010263, R²: -0.0212
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.18329 | val 0.19888
  Epoch 020 - train 0.18539 | val 0.19958
  Regression -> MSE: 0.000086, MAE: 0.007123, R²: -0.0087
  Directional -> Accuracy: 0.5862, MCC: 0.1841, F1: 0.6000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.17533 | val 0.21556
  Epoch 020 - train 0.17290 | val 0.21620
  Regression -> MSE: 0.000217, MAE: 0.011035, R²: -0.0250
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.16328 | val 0.14766
  Epoch 020 - train 0.15499 | val 0.14845
  Regression -> MSE: 0.000099, MAE: 0.008223, R²: -0.0789
  Directional -> Accuracy: 0.4286, MCC: -0.1152, F1: 0.3600

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.18256 | val 0.13618
  Epoch 020 - train 0.18100 | val 0.14008
  Regression -> MSE: 0.000108, MAE: 0.008951, R²: -0.0448
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.17789 | val 0.16343
  Epoch 020 - train 0.18202 | val 0.16500
  Regression -> MSE: 0.000233, MAE: 0.012609, R²: -0.0077
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.17089 | val 0.21035
  Epoch 020 - train 0.16904 | val 0.21239
  Regression -> MSE: 0.000190, MAE: 0.008186, R²: -0.1399
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.18614 | val 0.14833
  Epoch 020 - train 0.19088 | val 0.14535
  Regression -> MSE: 0.000238, MAE: 0.011925, R²: -0.0069
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.17597 | val 0.27670
  Epoch 020 - train 0.17958 | val 0.28003
  Regression -> MSE: 0.000230, MAE: 0.009886, R²: 0.0004
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.18227 | val 0.20769
  Epoch 020 - train 0.17950 | val 0.20094
  Regression -> MSE: 0.000137, MAE: 0.008219, R²: -0.0152
  Directional -> Accuracy: 0.5349, MCC: 0.0435, F1: 0.6296

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.17466 | val 0.21620
  Epoch 020 - train 0.16839 | val 0.21410
  Regression -> MSE: 0.000191, MAE: 0.010385, R²: -0.0144
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.16614 | val 0.21501
  Epoch 020 - train 0.15879 | val 0.21413
  Regression -> MSE: 0.000262, MAE: 0.010541, R²: -0.0005
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.16850 | val 0.15074
  Epoch 020 - train 0.17614 | val 0.15177
  Regression -> MSE: 0.000167, MAE: 0.010374, R²: -0.0041
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.16546 | val 0.17716
  Epoch 020 - train 0.16550 | val 0.20268
  Regression -> MSE: 0.000180, MAE: 0.010241, R²: 0.0011
  Directional -> Accuracy: 0.6136, MCC: 0.2833, F1: 0.3704

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.16950 | val 0.16285
  Epoch 020 - train 0.16710 | val 0.16239
  Regression -> MSE: 0.000355, MAE: 0.012654, R²: -0.0351
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.20081 | val 0.11300
  Epoch 020 - train 0.19083 | val 0.12347
  Regression -> MSE: 0.000112, MAE: 0.008332, R²: -0.0610
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.17520 | val 0.23915
  Epoch 020 - train 0.17338 | val 0.24115
  Regression -> MSE: 0.000221, MAE: 0.011408, R²: -0.0131
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.17149 | val 0.29611
  Epoch 020 - train 0.17011 | val 0.29794
  Regression -> MSE: 0.000088, MAE: 0.007327, R²: -0.1285
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.18001 | val 0.12823
  Epoch 020 - train 0.17296 | val 0.12849
  Regression -> MSE: 0.000310, MAE: 0.013939, R²: -0.0070
  Directional -> Accuracy: 0.6327, MCC: 0.0000, F1: 0.0000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.17377 | val 0.10738
  Epoch 020 - train 0.17824 | val 0.11655
  Regression -> MSE: 0.000253, MAE: 0.011467, R²: -0.0374
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.17558 | val 0.21692
  Epoch 020 - train 0.17031 | val 0.21918
  Regression -> MSE: 0.000081, MAE: 0.007064, R²: -0.0031
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.17428 | val 0.21599
  Epoch 020 - train 0.17293 | val 0.20337
  Regression -> MSE: 0.000317, MAE: 0.014921, R²: -0.0343
  Directional -> Accuracy: 0.4468, MCC: -0.1357, F1: 0.1333

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.16690 | val 0.19580
  Epoch 020 - train 0.17170 | val 0.20291
  Regression -> MSE: 0.000100, MAE: 0.007145, R²: -0.0131
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.19117 | val 0.21526
  Epoch 020 - train 0.18895 | val 0.24153
  Regression -> MSE: 0.000176, MAE: 0.010240, R²: -0.0243
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.16611 | val 0.19589
  Epoch 020 - train 0.15378 | val 0.19626
  Regression -> MSE: 0.000224, MAE: 0.011793, R²: -0.0067
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.17359 | val 0.20795
  Epoch 020 - train 0.17804 | val 0.21899
  Regression -> MSE: 0.000092, MAE: 0.007654, R²: 0.0008
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.18501 | val 0.27740
  Epoch 020 - train 0.18828 | val 0.29385
  Regression -> MSE: 0.000164, MAE: 0.010277, R²: -0.0022
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.16904 | val 0.22183
  Epoch 020 - train 0.16763 | val 0.22803
  Regression -> MSE: 0.000118, MAE: 0.008948, R²: -0.0169
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.17757 | val 0.29614

[I 2026-02-23 02:46:21,686] Trial 204 finished with value: -0.011458998037048869 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.30000000000000004, 'batch_size': 32, 'learning_rate': 3.0879915149529166e-06, 'weight_decay': 2.964950902971271e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.27371642752414715, 'early_stopping_min_delta': 0.0059593636849423325}. Best is trial 157 with value: -0.011387287234516647.

  Epoch 020 - train 0.17960 | val 0.32736
  Regression -> MSE: 0.000242, MAE: 0.012332, R²: -0.0192
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.12691 | val 0.17428
  Epoch 020 - train 0.12966 | val 0.17634
  Regression -> MSE: 0.000249, MAE: 0.012620, R²: -0.0062
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.13322 | val 0.14756
  Epoch 020 - train 0.12557 | val 0.20329
  Regression -> MSE: 0.000693, MAE: 0.019518, R²: -0.0124
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.12984 | val 0.21243
  Epoch 020 - train 0.13209 | val 0.21197
  Regression -> MSE: 0.000311, MAE: 0.014413, R²: -0.0040
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.10893 | val 0.17139
  Epoch 020 - train 0.10712 | val 0.19868
  Regression -> MSE: 0.000357, MAE: 0.014701, R²: -0.0220
  Directional -> Accuracy: 0.5067, MCC: 0.0328, F1: 0.4789

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.13149 | val 0.13247
  Epoch 020 - train 0.12586 | val 0.15221
  Regression -> MSE: 0.000204, MAE: 0.010142, R²: -0.0021
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.12741 | val 0.25829
  Epoch 020 - train 0.12369 | val 0.26592
  Regression -> MSE: 0.000612, MAE: 0.019278, R²: -0.1017
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.13157 | val 0.16164
  Epoch 020 - train 0.12891 | val 0.16417
  Regression -> MSE: 0.000247, MAE: 0.012215, R²: -0.0046
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.12246 | val 0.17113
  Epoch 020 - train 0.13139 | val 0.18172
  Regression -> MSE: 0.000627, MAE: 0.019822, R²: -0.0488
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.11879 | val 0.16127
  Epoch 020 - train 0.12151 | val 0.15528
  Regression -> MSE: 0.000387, MAE: 0.016046, R²: -0.0077
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.12609 | val 0.16962
  Epoch 020 - train 0.12664 | val 0.16976
  Regression -> MSE: 0.000242, MAE: 0.012072, R²: -0.0040
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.11675 | val 0.18421
  Epoch 020 - train 0.11693 | val 0.18022
  Regression -> MSE: 0.000308, MAE: 0.013637, R²: 0.0098
  Directional -> Accuracy: 0.6200, MCC: 0.2766, F1: 0.3448

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.13665 | val 0.15632
  Epoch 020 - train 0.13374 | val 0.16027
  Regression -> MSE: 0.000683, MAE: 0.019530, R²: -0.0090
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.12423 | val 0.13454
  Epoch 020 - train 0.12436 | val 0.15262
  Regression -> MSE: 0.000142, MAE: 0.009403, R²: -0.0313
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.12082 | val 0.18106
  Epoch 020 - train 0.11660 | val 0.18402
  Regression -> MSE: 0.000224, MAE: 0.010677, R²: 0.0022
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.12958 | val 0.26504
  Epoch 020 - train 0.12832 | val 0.26596
  Regression -> MSE: 0.000363, MAE: 0.016203, R²: -0.0018
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.13844 | val 0.13048
  Epoch 020 - train 0.13542 | val 0.13069
  Regression -> MSE: 0.000108, MAE: 0.007971, R²: 0.0003
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.13013 | val 0.21783
  Epoch 020 - train 0.12763 | val 0.22220
  Regression -> MSE: 0.000156, MAE: 0.009539, R²: -0.0014
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.13129 | val 0.12955
  Epoch 020 - train 0.12905 | val 0.12875
  Regression -> MSE: 0.000275, MAE: 0.013226, R²: -0.0124
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.11118 | val 0.17316
  Epoch 020 - train 0.11439 | val 0.17130
  Regression -> MSE: 0.000155, MAE: 0.008769, R²: -0.0373
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.13109 | val 0.18124
  Epoch 020 - train 0.12974 | val 0.18429
  Regression -> MSE: 0.000228, MAE: 0.010871, R²: -0.0091
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.13181 | val 0.16344
  Epoch 020 - train 0.13373 | val 0.16985
  Regression -> MSE: 0.000147, MAE: 0.008562, R²: -0.0252
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.12931 | val 0.16697
  Epoch 020 - train 0.12543 | val 0.16988
  Regression -> MSE: 0.000165, MAE: 0.010509, R²: -0.0015
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.13874 | val 0.15071
  Epoch 020 - train 0.13786 | val 0.15603
  Regression -> MSE: 0.000091, MAE: 0.007369, R²: -0.0712
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.12981 | val 0.25198
  Epoch 020 - train 0.13220 | val 0.28117
  Regression -> MSE: 0.000211, MAE: 0.011125, R²: 0.0020
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.11909 | val 0.11557
  Epoch 020 - train 0.11708 | val 0.11336
  Regression -> MSE: 0.000101, MAE: 0.008240, R²: -0.1013
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.13203 | val 0.10240
  Epoch 020 - train 0.13416 | val 0.10811
  Regression -> MSE: 0.000107, MAE: 0.008930, R²: -0.0388
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.13684 | val 0.15749
  Epoch 020 - train 0.13849 | val 0.22839
  Regression -> MSE: 0.000245, MAE: 0.012983, R²: -0.0606
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.12375 | val 0.15686
  Epoch 020 - train 0.13076 | val 0.15933
  Regression -> MSE: 0.000180, MAE: 0.007941, R²: -0.0814
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.13552 | val 0.11374
  Epoch 020 - train 0.13402 | val 0.11065
  Regression -> MSE: 0.000239, MAE: 0.011974, R²: -0.0097
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.13494 | val 0.21535
  Epoch 020 - train 0.14194 | val 0.22313
  Regression -> MSE: 0.000237, MAE: 0.010260, R²: -0.0269
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.13202 | val 0.14935
  Epoch 020 - train 0.13231 | val 0.14939
  Regression -> MSE: 0.000135, MAE: 0.008180, R²: -0.0022
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.13112 | val 0.16157
  Epoch 020 - train 0.12894 | val 0.16103
  Regression -> MSE: 0.000201, MAE: 0.010746, R²: -0.0666
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.11435 | val 0.14621
  Epoch 020 - train 0.11428 | val 0.14578
  Regression -> MSE: 0.000269, MAE: 0.010587, R²: -0.0266
  Directional -> Accuracy: 0.5479, MCC: -0.0210, F1: 0.6972

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.12078 | val 0.11008
  Epoch 020 - train 0.11915 | val 0.11046
  Regression -> MSE: 0.000167, MAE: 0.010365, R²: 0.0005
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.11837 | val 0.13525
  Epoch 020 - train 0.11346 | val 0.13672
  Regression -> MSE: 0.000185, MAE: 0.010531, R²: -0.0283
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.13183 | val 0.12721
  Epoch 020 - train 0.12907 | val 0.12726
  Regression -> MSE: 0.000343, MAE: 0.011893, R²: -0.0014
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.14501 | val 0.08652
  Epoch 020 - train 0.14036 | val 0.09188
  Regression -> MSE: 0.000111, MAE: 0.008313, R²: -0.0589
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.12874 | val 0.17305
  Epoch 020 - train 0.12742 | val 0.17426
  Regression -> MSE: 0.000220, MAE: 0.011361, R²: -0.0079
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.13389 | val 0.22550
  Epoch 020 - train 0.12764 | val 0.23335
  Regression -> MSE: 0.000084, MAE: 0.007132, R²: -0.0770
  Directional -> Accuracy: 0.5957, MCC: 0.0615, F1: 0.7164

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.12392 | val 0.09611
  Epoch 020 - train 0.12447 | val 0.09146
  Regression -> MSE: 0.000310, MAE: 0.013958, R²: -0.0084
  Directional -> Accuracy: 0.6122, MCC: -0.0180, F1: 0.0952

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.12996 | val 0.08341
  Epoch 020 - train 0.13606 | val 0.08584
  Regression -> MSE: 0.000257, MAE: 0.011471, R²: -0.0523
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.12782 | val 0.15562
  Epoch 020 - train 0.12313 | val 0.15630
  Regression -> MSE: 0.000083, MAE: 0.007052, R²: -0.0235
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.12760 | val 0.15927
  Epoch 020 - train 0.12498 | val 0.17370
  Regression -> MSE: 0.000307, MAE: 0.014497, R²: -0.0010
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.12617 | val 0.15792
  Epoch 020 - train 0.13516 | val 0.15670
  Regression -> MSE: 0.000103, MAE: 0.007113, R²: -0.0523
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.13952 | val 0.15573
  Epoch 020 - train 0.13841 | val 0.15979
  Regression -> MSE: 0.000173, MAE: 0.009478, R²: -0.0075
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.12348 | val 0.14772
  Epoch 020 - train 0.11962 | val 0.15102
  Regression -> MSE: 0.000223, MAE: 0.011745, R²: -0.0002
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.12581 | val 0.14811
  Epoch 020 - train 0.12645 | val 0.15829
  Regression -> MSE: 0.000093, MAE: 0.007639, R²: -0.0030
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.13617 | val 0.19951
  Epoch 020 - train 0.13600 | val 0.20253
  Regression -> MSE: 0.000164, MAE: 0.010283, R²: -0.0026
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.12894 | val 0.16133
  Epoch 020 - train 0.12292 | val 0.16889
  Regression -> MSE: 0.000134, MAE: 0.009208, R²: -0.1563
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.13103 | val 0.18119

[I 2026-02-23 02:48:59,026] Trial 205 finished with value: -0.011449471213942472 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 32, 'learning_rate': 7.434558738808073e-06, 'weight_decay': 5.81308109163694e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.19566728319493443, 'early_stopping_min_delta': 0.006893693605815472}. Best is trial 157 with value: -0.011387287234516647.

  Epoch 020 - train 0.13557 | val 0.18247
  Regression -> MSE: 0.000237, MAE: 0.012373, R²: -0.0014
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.14513 | val 0.19249
  Epoch 020 - train 0.14270 | val 0.19234
  Regression -> MSE: 0.000249, MAE: 0.012605, R²: -0.0044
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.15321 | val 0.18695
  Epoch 020 - train 0.15164 | val 0.22938
  Regression -> MSE: 0.000686, MAE: 0.019445, R²: -0.0028
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.15996 | val 0.25034
  Epoch 020 - train 0.15719 | val 0.27096
  Regression -> MSE: 0.000312, MAE: 0.014509, R²: -0.0067
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.11956 | val 0.17189
  Epoch 020 - train 0.12244 | val 0.14609
  Regression -> MSE: 0.000351, MAE: 0.014616, R²: -0.0043
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.14877 | val 0.14303
  Epoch 020 - train 0.14508 | val 0.13992
  Regression -> MSE: 0.000209, MAE: 0.010434, R²: -0.0282
  Directional -> Accuracy: 0.3529, MCC: -0.2938, F1: 0.2326

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.13672 | val 0.26822
  Epoch 020 - train 0.13219 | val 0.27036
  Regression -> MSE: 0.000555, MAE: 0.018139, R²: 0.0001
  Directional -> Accuracy: 0.4894, MCC: 0.0000, F1: 0.6571

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.15079 | val 0.18168
  Epoch 020 - train 0.14715 | val 0.18121
  Regression -> MSE: 0.000247, MAE: 0.012215, R²: -0.0055
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.14368 | val 0.17856
  Epoch 020 - train 0.14254 | val 0.19903
  Regression -> MSE: 0.000609, MAE: 0.019432, R²: -0.0187
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.13974 | val 0.17380
  Epoch 020 - train 0.13533 | val 0.17151
  Regression -> MSE: 0.000390, MAE: 0.015973, R²: -0.0167
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.13877 | val 0.18446
  Epoch 020 - train 0.13992 | val 0.18472
  Regression -> MSE: 0.000243, MAE: 0.011659, R²: -0.0084
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.14156 | val 0.20166
  Epoch 020 - train 0.13679 | val 0.20266
  Regression -> MSE: 0.000319, MAE: 0.013591, R²: -0.0273
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.15462 | val 0.19386
  Epoch 020 - train 0.14098 | val 0.22259
  Regression -> MSE: 0.000684, MAE: 0.019549, R²: -0.0102
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.15183 | val 0.16880
  Epoch 020 - train 0.14185 | val 0.26785
  Regression -> MSE: 0.000138, MAE: 0.009148, R²: -0.0021
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.13794 | val 0.18732
  Epoch 020 - train 0.13053 | val 0.18731
  Regression -> MSE: 0.000220, MAE: 0.010708, R²: 0.0202
  Directional -> Accuracy: 0.4590, MCC: -0.1319, F1: 0.6024

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.14609 | val 0.29382
  Epoch 020 - train 0.13996 | val 0.29414
  Regression -> MSE: 0.000362, MAE: 0.016146, R²: 0.0001
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.15381 | val 0.16084
  Epoch 020 - train 0.15003 | val 0.16343
  Regression -> MSE: 0.000108, MAE: 0.007997, R²: 0.0007
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.14534 | val 0.24271
  Epoch 020 - train 0.13876 | val 0.25003
  Regression -> MSE: 0.000157, MAE: 0.009792, R²: -0.0050
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.14722 | val 0.14960
  Epoch 020 - train 0.14714 | val 0.15015
  Regression -> MSE: 0.000286, MAE: 0.013674, R²: -0.0516
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.13094 | val 0.20369
  Epoch 020 - train 0.12186 | val 0.20172
  Regression -> MSE: 0.000159, MAE: 0.008871, R²: -0.0628
  Directional -> Accuracy: 0.5077, MCC: -0.0912, F1: 0.6364

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.15762 | val 0.26994
  Epoch 020 - train 0.15486 | val 0.26337
  Regression -> MSE: 0.000229, MAE: 0.010906, R²: -0.0118
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.14199 | val 0.18049
  Epoch 020 - train 0.14088 | val 0.18148
  Regression -> MSE: 0.000148, MAE: 0.008609, R²: -0.0315
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.13820 | val 0.16290
  Epoch 020 - train 0.13868 | val 0.16208
  Regression -> MSE: 0.000175, MAE: 0.010279, R²: -0.0605
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.15197 | val 0.18678
  Epoch 020 - train 0.14612 | val 0.19892
  Regression -> MSE: 0.000085, MAE: 0.007033, R²: 0.0038
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.14122 | val 0.19287
  Epoch 020 - train 0.13908 | val 0.18923
  Regression -> MSE: 0.000212, MAE: 0.011106, R²: -0.0007
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.13647 | val 0.12697
  Epoch 020 - train 0.13333 | val 0.12435
  Regression -> MSE: 0.000096, MAE: 0.007994, R²: -0.0420
  Directional -> Accuracy: 0.5536, MCC: 0.1078, F1: 0.5763

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.14920 | val 0.11155
  Epoch 020 - train 0.15134 | val 0.11650
  Regression -> MSE: 0.000105, MAE: 0.008849, R²: -0.0188
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.15475 | val 0.14374
  Epoch 020 - train 0.14956 | val 0.15557
  Regression -> MSE: 0.000232, MAE: 0.012507, R²: -0.0003
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.14558 | val 0.17819
  Epoch 020 - train 0.14451 | val 0.17710
  Regression -> MSE: 0.000171, MAE: 0.007817, R²: -0.0274
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.15300 | val 0.12673
  Epoch 020 - train 0.14673 | val 0.13380
  Regression -> MSE: 0.000237, MAE: 0.011882, R²: -0.0037
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.14508 | val 0.23394
  Epoch 020 - train 0.14100 | val 0.25545
  Regression -> MSE: 0.000232, MAE: 0.009949, R²: -0.0051
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.15540 | val 0.16842
  Epoch 020 - train 0.15100 | val 0.16459
  Regression -> MSE: 0.000131, MAE: 0.008208, R²: 0.0299
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.14177 | val 0.18239
  Epoch 020 - train 0.14392 | val 0.18484
  Regression -> MSE: 0.000194, MAE: 0.010460, R²: -0.0307
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.12600 | val 0.16057
  Epoch 020 - train 0.12705 | val 0.16178
  Regression -> MSE: 0.000271, MAE: 0.010651, R²: -0.0350
  Directional -> Accuracy: 0.4384, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.13308 | val 0.12225
  Epoch 020 - train 0.13596 | val 0.12205
  Regression -> MSE: 0.000167, MAE: 0.010370, R²: -0.0010
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.13847 | val 0.15162
  Epoch 020 - train 0.13342 | val 0.15546
  Regression -> MSE: 0.000184, MAE: 0.010456, R²: -0.0207
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.14415 | val 0.14806
  Epoch 020 - train 0.13808 | val 0.14969
  Regression -> MSE: 0.000349, MAE: 0.011775, R²: -0.0183
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.16888 | val 0.10098
  Epoch 020 - train 0.16448 | val 0.12061
  Regression -> MSE: 0.000109, MAE: 0.008318, R²: -0.0336
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.16064 | val 0.20178
  Epoch 020 - train 0.15681 | val 0.20284
  Regression -> MSE: 0.000221, MAE: 0.011372, R²: -0.0133
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.13791 | val 0.25907
  Epoch 020 - train 0.13808 | val 0.30457
  Regression -> MSE: 0.000095, MAE: 0.007620, R²: -0.2266
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.15084 | val 0.12449
  Epoch 020 - train 0.15043 | val 0.14463
  Regression -> MSE: 0.000332, MAE: 0.015056, R²: -0.0784
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.15080 | val 0.08678
  Epoch 020 - train 0.14963 | val 0.08709
  Regression -> MSE: 0.000250, MAE: 0.011507, R²: -0.0251
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.13559 | val 0.16753
  Epoch 020 - train 0.13351 | val 0.16669
  Regression -> MSE: 0.000079, MAE: 0.007017, R²: 0.0179
  Directional -> Accuracy: 0.5067, MCC: 0.1147, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.14997 | val 0.17418
  Epoch 020 - train 0.14471 | val 0.21102
  Regression -> MSE: 0.000305, MAE: 0.014482, R²: 0.0057
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.14047 | val 0.15856
  Epoch 020 - train 0.13883 | val 0.15709
  Regression -> MSE: 0.000099, MAE: 0.007192, R²: -0.0056
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.15177 | val 0.17117
  Epoch 020 - train 0.15393 | val 0.17816
  Regression -> MSE: 0.000172, MAE: 0.009625, R²: 0.0002
  Directional -> Accuracy: 0.4694, MCC: -0.0395, F1: 0.4348

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.13398 | val 0.16967
  Epoch 020 - train 0.13039 | val 0.17774
  Regression -> MSE: 0.000227, MAE: 0.011823, R²: -0.0165
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.14202 | val 0.17071
  Epoch 020 - train 0.14435 | val 0.17198
  Regression -> MSE: 0.000097, MAE: 0.007952, R²: -0.0483
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.15208 | val 0.23363
  Epoch 020 - train 0.14899 | val 0.23633
  Regression -> MSE: 0.000165, MAE: 0.010267, R²: -0.0049
  Directional -> Accuracy: 0.5370, MCC: 0.0845, F1: 0.4898

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.14550 | val 0.18392
  Epoch 020 - train 0.14001 | val 0.19065
  Regression -> MSE: 0.000121, MAE: 0.008995, R²: -0.0471
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.14715 | val 0.20797

[I 2026-02-23 02:51:37,152] Trial 206 finished with value: -0.011418708020995975 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 32, 'learning_rate': 4.576425186652937e-06, 'weight_decay': 4.069150415539562e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.22074384707896003, 'early_stopping_min_delta': 0.0054666757709550306}. Best is trial 157 with value: -0.011387287234516647.

  Epoch 020 - train 0.14800 | val 0.22375
  Regression -> MSE: 0.000244, MAE: 0.012352, R²: -0.0293
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.13956 | val 0.18311
  Epoch 020 - train 0.14348 | val 0.18240
  Regression -> MSE: 0.000252, MAE: 0.012762, R²: -0.0181
  Directional -> Accuracy: 0.4416, MCC: -0.1186, F1: 0.4110

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.14394 | val 0.13550
  Epoch 020 - train 0.13728 | val 0.14342
  Regression -> MSE: 0.000700, MAE: 0.019622, R²: -0.0232
  Directional -> Accuracy: 0.4130, MCC: -0.1252, F1: 0.2703

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.15684 | val 0.23386
  Epoch 020 - train 0.15414 | val 0.23980
  Regression -> MSE: 0.000310, MAE: 0.014396, R²: 0.0019
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.12319 | val 0.17080
  Epoch 020 - train 0.12002 | val 0.17694
  Regression -> MSE: 0.000356, MAE: 0.014694, R²: -0.0189
  Directional -> Accuracy: 0.4933, MCC: -0.0819, F1: 0.6200

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.15798 | val 0.14725
  Epoch 020 - train 0.15219 | val 0.14438
  Regression -> MSE: 0.000209, MAE: 0.010188, R²: -0.0253
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.14963 | val 0.26733
  Epoch 020 - train 0.14842 | val 0.27400
  Regression -> MSE: 0.000559, MAE: 0.018189, R²: -0.0072
  Directional -> Accuracy: 0.4255, MCC: -0.1506, F1: 0.4000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.14800 | val 0.18151
  Epoch 020 - train 0.14865 | val 0.18189
  Regression -> MSE: 0.000250, MAE: 0.011950, R²: -0.0179
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.15209 | val 0.17624
  Epoch 020 - train 0.14596 | val 0.17214
  Regression -> MSE: 0.000598, MAE: 0.019173, R²: -0.0011
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.12978 | val 0.17376
  Epoch 020 - train 0.12955 | val 0.16800
  Regression -> MSE: 0.000441, MAE: 0.016810, R²: -0.1496
  Directional -> Accuracy: 0.4898, MCC: -0.2305, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.14048 | val 0.19169
  Epoch 020 - train 0.14185 | val 0.19558
  Regression -> MSE: 0.000245, MAE: 0.011622, R²: -0.0135
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.13104 | val 0.20682
  Epoch 020 - train 0.13717 | val 0.20738
  Regression -> MSE: 0.000314, MAE: 0.013634, R²: -0.0106
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.14924 | val 0.16367
  Epoch 020 - train 0.14673 | val 0.16452
  Regression -> MSE: 0.000678, MAE: 0.019464, R²: -0.0009
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.14723 | val 0.14250
  Epoch 020 - train 0.14440 | val 0.15800
  Regression -> MSE: 0.000143, MAE: 0.009260, R²: -0.0315
  Directional -> Accuracy: 0.4884, MCC: 0.0316, F1: 0.5600

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.12775 | val 0.18062
  Epoch 020 - train 0.12877 | val 0.18120
  Regression -> MSE: 0.000228, MAE: 0.010791, R²: -0.0152
  Directional -> Accuracy: 0.4918, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.14215 | val 0.29578
  Epoch 020 - train 0.13722 | val 0.30573
  Regression -> MSE: 0.000373, MAE: 0.015918, R²: -0.0296
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.15240 | val 0.14918
  Epoch 020 - train 0.14878 | val 0.15245
  Regression -> MSE: 0.000108, MAE: 0.007946, R²: -0.0031
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.14229 | val 0.26638
  Epoch 020 - train 0.13856 | val 0.28392
  Regression -> MSE: 0.000157, MAE: 0.009526, R²: -0.0088
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.15249 | val 0.19216
  Epoch 020 - train 0.14509 | val 0.17650
  Regression -> MSE: 0.000273, MAE: 0.012974, R²: -0.0042
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.13180 | val 0.19852
  Epoch 020 - train 0.12866 | val 0.19406
  Regression -> MSE: 0.000156, MAE: 0.008798, R²: -0.0442
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.15448 | val 0.22541
  Epoch 020 - train 0.14494 | val 0.22129
  Regression -> MSE: 0.000232, MAE: 0.010967, R²: -0.0242
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.13897 | val 0.18213
  Epoch 020 - train 0.14144 | val 0.18715
  Regression -> MSE: 0.000146, MAE: 0.008501, R²: -0.0164
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.13417 | val 0.16524
  Epoch 020 - train 0.13284 | val 0.16438
  Regression -> MSE: 0.000177, MAE: 0.010291, R²: -0.0723
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.15051 | val 0.17401
  Epoch 020 - train 0.15182 | val 0.17450
  Regression -> MSE: 0.000085, MAE: 0.007038, R²: -0.0022
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.14010 | val 0.17987
  Epoch 020 - train 0.14159 | val 0.17825
  Regression -> MSE: 0.000214, MAE: 0.011410, R²: -0.0111
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.13688 | val 0.13058
  Epoch 020 - train 0.13449 | val 0.12783
  Regression -> MSE: 0.000093, MAE: 0.008096, R²: -0.0092
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.14451 | val 0.11464
  Epoch 020 - train 0.14723 | val 0.11249
  Regression -> MSE: 0.000110, MAE: 0.009012, R²: -0.0627
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.15600 | val 0.14607
  Epoch 020 - train 0.15188 | val 0.18722
  Regression -> MSE: 0.000233, MAE: 0.012617, R²: -0.0083
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.14306 | val 0.17789
  Epoch 020 - train 0.14775 | val 0.17541
  Regression -> MSE: 0.000169, MAE: 0.007830, R²: -0.0184
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.14949 | val 0.11974
  Epoch 020 - train 0.15466 | val 0.12039
  Regression -> MSE: 0.000239, MAE: 0.011939, R²: -0.0111
  Directional -> Accuracy: 0.4634, MCC: 0.0000, F1: 0.0000

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.15299 | val 0.22733
  Epoch 020 - train 0.15635 | val 0.22549
  Regression -> MSE: 0.000231, MAE: 0.009896, R²: -0.0004
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.14588 | val 0.17096
  Epoch 020 - train 0.14274 | val 0.18825
  Regression -> MSE: 0.000135, MAE: 0.008172, R²: 0.0017
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.15738 | val 0.18355
  Epoch 020 - train 0.15590 | val 0.18942
  Regression -> MSE: 0.000199, MAE: 0.010690, R²: -0.0550
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.13302 | val 0.16269
  Epoch 020 - train 0.13136 | val 0.16101
  Regression -> MSE: 0.000265, MAE: 0.010508, R²: -0.0116
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.15002 | val 0.11959
  Epoch 020 - train 0.13963 | val 0.13478
  Regression -> MSE: 0.000168, MAE: 0.010364, R²: -0.0090
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.13283 | val 0.14818
  Epoch 020 - train 0.13170 | val 0.15584
  Regression -> MSE: 0.000182, MAE: 0.010324, R²: -0.0090
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.13694 | val 0.12536
  Epoch 020 - train 0.13564 | val 0.12618
  Regression -> MSE: 0.000344, MAE: 0.011941, R²: -0.0028
  Directional -> Accuracy: 0.4627, MCC: -0.1240, F1: 0.5610

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.15700 | val 0.09279
  Epoch 020 - train 0.15104 | val 0.10090
  Regression -> MSE: 0.000120, MAE: 0.008352, R²: -0.1371
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.14951 | val 0.19480
  Epoch 020 - train 0.14138 | val 0.19477
  Regression -> MSE: 0.000219, MAE: 0.011266, R²: -0.0007
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.14311 | val 0.25061
  Epoch 020 - train 0.14408 | val 0.25576
  Regression -> MSE: 0.000081, MAE: 0.007016, R²: -0.0448
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.14472 | val 0.10823
  Epoch 020 - train 0.15073 | val 0.10995
  Regression -> MSE: 0.000310, MAE: 0.013909, R²: -0.0075
  Directional -> Accuracy: 0.6327, MCC: 0.0000, F1: 0.0000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.15036 | val 0.08766
  Epoch 020 - train 0.15659 | val 0.08898
  Regression -> MSE: 0.000251, MAE: 0.011494, R²: -0.0299
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.13789 | val 0.17028
  Epoch 020 - train 0.13707 | val 0.17096
  Regression -> MSE: 0.000081, MAE: 0.007081, R²: 0.0001
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.13749 | val 0.17473
  Epoch 020 - train 0.13914 | val 0.20635
  Regression -> MSE: 0.000307, MAE: 0.014476, R²: -0.0001
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.14586 | val 0.17702
  Epoch 020 - train 0.13970 | val 0.19357
  Regression -> MSE: 0.000103, MAE: 0.007108, R²: -0.0504
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.15487 | val 0.17693
  Epoch 020 - train 0.14985 | val 0.18255
  Regression -> MSE: 0.000174, MAE: 0.009448, R²: -0.0126
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.13352 | val 0.15832
  Epoch 020 - train 0.13381 | val 0.15794
  Regression -> MSE: 0.000226, MAE: 0.011837, R²: -0.0148
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.15002 | val 0.16183
  Epoch 020 - train 0.14497 | val 0.16189
  Regression -> MSE: 0.000094, MAE: 0.007753, R²: -0.0193
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.15305 | val 0.22252
  Epoch 020 - train 0.14645 | val 0.22430
  Regression -> MSE: 0.000164, MAE: 0.010266, R²: -0.0032
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.14784 | val 0.18758
  Epoch 020 - train 0.14769 | val 0.19545
  Regression -> MSE: 0.000129, MAE: 0.009080, R²: -0.1169
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.14709 | val 0.19913

[I 2026-02-23 02:54:15,550] Trial 207 finished with value: -0.01137496405368131 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 32, 'learning_rate': 4.4612771066622406e-06, 'weight_decay': 3.465120935964356e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.219380129211455, 'early_stopping_min_delta': 0.005727392184121634}. Best is trial 207 with value: -0.01137496405368131.

  Epoch 020 - train 0.14799 | val 0.20329
  Regression -> MSE: 0.000244, MAE: 0.012350, R²: -0.0272
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.18721 | val 0.24705
  Epoch 020 - train 0.18541 | val 0.24616
  Regression -> MSE: 0.000250, MAE: 0.012649, R²: -0.0102
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.17763 | val 0.17376
  Epoch 020 - train 0.17486 | val 0.18840
  Regression -> MSE: 0.000708, MAE: 0.019764, R²: -0.0343
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.18224 | val 0.30404
  Epoch 020 - train 0.18003 | val 0.30082
  Regression -> MSE: 0.000322, MAE: 0.014529, R²: -0.0378
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.14763 | val 0.15189
  Epoch 020 - train 0.14598 | val 0.15429
  Regression -> MSE: 0.000378, MAE: 0.015049, R²: -0.0825
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.18112 | val 0.19123
  Epoch 020 - train 0.17908 | val 0.20064
  Regression -> MSE: 0.000206, MAE: 0.010073, R²: -0.0097
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.18149 | val 0.35686
  Epoch 020 - train 0.17465 | val 0.40681
  Regression -> MSE: 0.000573, MAE: 0.018436, R²: -0.0321
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.19189 | val 0.23188
  Epoch 020 - train 0.18910 | val 0.23002
  Regression -> MSE: 0.000246, MAE: 0.012091, R²: -0.0006
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.18996 | val 0.22874
  Epoch 020 - train 0.18241 | val 0.21486
  Regression -> MSE: 0.000619, MAE: 0.019645, R²: -0.0358
  Directional -> Accuracy: 0.4318, MCC: -0.1145, F1: 0.4186

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.20030 | val 0.23359
  Epoch 020 - train 0.20433 | val 0.24011
  Regression -> MSE: 0.000384, MAE: 0.016136, R²: -0.0011
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.17761 | val 0.23137
  Epoch 020 - train 0.17922 | val 0.23484
  Regression -> MSE: 0.000242, MAE: 0.012010, R²: -0.0021
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.17271 | val 0.27371
  Epoch 020 - train 0.17339 | val 0.27529
  Regression -> MSE: 0.000311, MAE: 0.013690, R²: -0.0005
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.6301

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.18680 | val 0.23017
  Epoch 020 - train 0.18207 | val 0.24191
  Regression -> MSE: 0.000686, MAE: 0.019818, R²: -0.0125
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.17738 | val 0.18573
  Epoch 020 - train 0.17666 | val 0.17823
  Regression -> MSE: 0.000144, MAE: 0.009316, R²: -0.0452
  Directional -> Accuracy: 0.4186, MCC: -0.1854, F1: 0.3243

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.16764 | val 0.25068
  Epoch 020 - train 0.17002 | val 0.25160
  Regression -> MSE: 0.000226, MAE: 0.010813, R²: -0.0037
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.17941 | val 0.38385
  Epoch 020 - train 0.17510 | val 0.41456
  Regression -> MSE: 0.000369, MAE: 0.015947, R²: -0.0199
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.19338 | val 0.18663
  Epoch 020 - train 0.19485 | val 0.18529
  Regression -> MSE: 0.000110, MAE: 0.007947, R²: -0.0157
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.17626 | val 0.31431
  Epoch 020 - train 0.17584 | val 0.32423
  Regression -> MSE: 0.000156, MAE: 0.009697, R²: -0.0032
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.18898 | val 0.19264
  Epoch 020 - train 0.18869 | val 0.19854
  Regression -> MSE: 0.000285, MAE: 0.013650, R²: -0.0488
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.16715 | val 0.24091
  Epoch 020 - train 0.16460 | val 0.23992
  Regression -> MSE: 0.000157, MAE: 0.008811, R²: -0.0488
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.19451 | val 0.27795
  Epoch 020 - train 0.18893 | val 0.26961
  Regression -> MSE: 0.000227, MAE: 0.010998, R²: -0.0040
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.19666 | val 0.24370
  Epoch 020 - train 0.18873 | val 0.28557
  Regression -> MSE: 0.000150, MAE: 0.008675, R²: -0.0451
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.17941 | val 0.22986
  Epoch 020 - train 0.17604 | val 0.23514
  Regression -> MSE: 0.000165, MAE: 0.010345, R²: 0.0003
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.18607 | val 0.22693
  Epoch 020 - train 0.18828 | val 0.22698
  Regression -> MSE: 0.000093, MAE: 0.007435, R²: -0.0874
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.19401 | val 0.22712
  Epoch 020 - train 0.18568 | val 0.22761
  Regression -> MSE: 0.000213, MAE: 0.011080, R²: -0.0056
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.17128 | val 0.16317
  Epoch 020 - train 0.17760 | val 0.16083
  Regression -> MSE: 0.000094, MAE: 0.008103, R²: -0.0175
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.18627 | val 0.14203
  Epoch 020 - train 0.19003 | val 0.17545
  Regression -> MSE: 0.000105, MAE: 0.008851, R²: -0.0192
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.19223 | val 0.17945
  Epoch 020 - train 0.19491 | val 0.17532
  Regression -> MSE: 0.000244, MAE: 0.012937, R²: -0.0523
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.17449 | val 0.21540
  Epoch 020 - train 0.17123 | val 0.21418
  Regression -> MSE: 0.000203, MAE: 0.008965, R²: -0.2207
  Directional -> Accuracy: 0.4386, MCC: -0.0841, F1: 0.3600

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.18032 | val 0.15789
  Epoch 020 - train 0.17939 | val 0.15600
  Regression -> MSE: 0.000238, MAE: 0.011927, R²: -0.0071
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.17645 | val 0.29352
  Epoch 020 - train 0.17604 | val 0.29818
  Regression -> MSE: 0.000231, MAE: 0.009892, R²: -0.0020
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.18896 | val 0.22884
  Epoch 020 - train 0.18537 | val 0.24125
  Regression -> MSE: 0.000137, MAE: 0.008309, R²: -0.0174
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.18738 | val 0.24071
  Epoch 020 - train 0.18193 | val 0.24558
  Regression -> MSE: 0.000188, MAE: 0.010469, R²: 0.0004
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.16330 | val 0.21223
  Epoch 020 - train 0.16000 | val 0.21283
  Regression -> MSE: 0.000265, MAE: 0.010516, R²: -0.0124
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.20189 | val 0.17242
  Epoch 020 - train 0.19652 | val 0.19057
  Regression -> MSE: 0.000171, MAE: 0.010394, R²: -0.0248
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.19299 | val 0.22437
  Epoch 020 - train 0.18796 | val 0.30239
  Regression -> MSE: 0.000181, MAE: 0.010377, R²: -0.0071
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.17200 | val 0.18479
  Epoch 020 - train 0.17340 | val 0.18654
  Regression -> MSE: 0.000345, MAE: 0.012026, R²: -0.0064
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.19658 | val 0.11376
  Epoch 020 - train 0.19618 | val 0.11594
  Regression -> MSE: 0.000120, MAE: 0.008367, R²: -0.1457
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.19038 | val 0.26026
  Epoch 020 - train 0.18871 | val 0.26507
  Regression -> MSE: 0.000219, MAE: 0.011269, R²: -0.0024
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.17777 | val 0.32010
  Epoch 020 - train 0.18001 | val 0.32181
  Regression -> MSE: 0.000082, MAE: 0.007080, R²: -0.0617
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.18304 | val 0.16524
  Epoch 020 - train 0.18932 | val 0.17229
  Regression -> MSE: 0.000354, MAE: 0.015791, R²: -0.1493
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.19181 | val 0.10583
  Epoch 020 - train 0.20453 | val 0.10736
  Regression -> MSE: 0.000248, MAE: 0.011515, R²: -0.0185
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.17224 | val 0.23320
  Epoch 020 - train 0.17221 | val 0.23401
  Regression -> MSE: 0.000082, MAE: 0.007062, R²: -0.0140
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.18328 | val 0.22865
  Epoch 020 - train 0.18094 | val 0.23707
  Regression -> MSE: 0.000307, MAE: 0.014506, R²: -0.0011
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.18116 | val 0.19497
  Epoch 020 - train 0.17194 | val 0.19848
  Regression -> MSE: 0.000098, MAE: 0.007286, R²: -0.0005
  Directional -> Accuracy: 0.4318, MCC: 0.0000, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.20205 | val 0.22336
  Epoch 020 - train 0.20235 | val 0.25439
  Regression -> MSE: 0.000172, MAE: 0.009838, R²: -0.0027
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.17329 | val 0.21674
  Epoch 020 - train 0.16899 | val 0.22004
  Regression -> MSE: 0.000224, MAE: 0.011754, R²: -0.0044
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.17258 | val 0.20489
  Epoch 020 - train 0.17228 | val 0.20736
  Regression -> MSE: 0.000095, MAE: 0.007814, R²: -0.0285
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.19072 | val 0.29390
  Epoch 020 - train 0.18939 | val 0.32493
  Regression -> MSE: 0.000164, MAE: 0.010272, R²: -0.0019
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.18317 | val 0.22359
  Epoch 020 - train 0.17580 | val 0.22357
  Regression -> MSE: 0.000118, MAE: 0.008941, R²: -0.0178
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.18305 | val 0.25895

[I 2026-02-23 02:57:02,043] Trial 208 finished with value: -0.01150664837514987 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 32, 'learning_rate': 4.227366529785436e-06, 'weight_decay': 3.7765753870515596e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.29145879972771127, 'early_stopping_min_delta': 0.005741294231555634}. Best is trial 207 with value: -0.01137496405368131.

  Epoch 020 - train 0.18661 | val 0.25827
  Regression -> MSE: 0.000238, MAE: 0.012467, R²: -0.0022
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.14576 | val 0.20113
  Epoch 020 - train 0.14480 | val 0.20074
  Regression -> MSE: 0.000260, MAE: 0.013014, R²: -0.0518
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.14335 | val 0.13921
  Epoch 020 - train 0.14328 | val 0.13914
  Regression -> MSE: 0.000706, MAE: 0.019732, R²: -0.0318
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.15399 | val 0.24650
  Epoch 020 - train 0.15537 | val 0.25186
  Regression -> MSE: 0.000311, MAE: 0.014411, R²: -0.0029
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.12303 | val 0.12732
  Epoch 020 - train 0.12114 | val 0.13163
  Regression -> MSE: 0.000371, MAE: 0.014926, R²: -0.0622
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.14532 | val 0.16651
  Epoch 020 - train 0.14897 | val 0.17665
  Regression -> MSE: 0.000208, MAE: 0.010517, R²: -0.0195
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.14259 | val 0.27669
  Epoch 020 - train 0.13574 | val 0.27727
  Regression -> MSE: 0.000561, MAE: 0.018179, R²: -0.0100
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.15031 | val 0.19176
  Epoch 020 - train 0.14943 | val 0.19162
  Regression -> MSE: 0.000246, MAE: 0.011947, R²: -0.0016
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.16789 | val 0.18423
  Epoch 020 - train 0.16731 | val 0.16554
  Regression -> MSE: 0.000617, MAE: 0.019505, R²: -0.0326
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.14024 | val 0.18120
  Epoch 020 - train 0.13938 | val 0.18390
  Regression -> MSE: 0.000393, MAE: 0.015935, R²: -0.0243
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.14807 | val 0.21983
  Epoch 020 - train 0.14571 | val 0.22700
  Regression -> MSE: 0.000241, MAE: 0.011877, R²: 0.0003
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.13485 | val 0.21136
  Epoch 020 - train 0.13391 | val 0.21227
  Regression -> MSE: 0.000320, MAE: 0.013586, R²: -0.0278
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.15401 | val 0.17805
  Epoch 020 - train 0.15005 | val 0.17797
  Regression -> MSE: 0.000679, MAE: 0.019536, R²: -0.0029
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.14860 | val 0.15198
  Epoch 020 - train 0.14573 | val 0.15263
  Regression -> MSE: 0.000139, MAE: 0.009136, R²: -0.0026
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.14192 | val 0.18642
  Epoch 020 - train 0.13910 | val 0.20131
  Regression -> MSE: 0.000223, MAE: 0.010631, R²: 0.0090
  Directional -> Accuracy: 0.5738, MCC: 0.1473, F1: 0.5806

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.14713 | val 0.30829
  Epoch 020 - train 0.14942 | val 0.31857
  Regression -> MSE: 0.000368, MAE: 0.015948, R²: -0.0171
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.15571 | val 0.15988
  Epoch 020 - train 0.15443 | val 0.16092
  Regression -> MSE: 0.000108, MAE: 0.008073, R²: -0.0030
  Directional -> Accuracy: 0.4571, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.15081 | val 0.24953
  Epoch 020 - train 0.14563 | val 0.25631
  Regression -> MSE: 0.000156, MAE: 0.009595, R²: 0.0010
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.14827 | val 0.17304
  Epoch 020 - train 0.14491 | val 0.17724
  Regression -> MSE: 0.000291, MAE: 0.013886, R²: -0.0709
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.13392 | val 0.20049
  Epoch 020 - train 0.13023 | val 0.20011
  Regression -> MSE: 0.000166, MAE: 0.009104, R²: -0.1098
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.15267 | val 0.21336
  Epoch 020 - train 0.15341 | val 0.21567
  Regression -> MSE: 0.000251, MAE: 0.011324, R²: -0.1078
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.15030 | val 0.18499
  Epoch 020 - train 0.14447 | val 0.18891
  Regression -> MSE: 0.000153, MAE: 0.008836, R²: -0.0700
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.13919 | val 0.17194
  Epoch 020 - train 0.14253 | val 0.17170
  Regression -> MSE: 0.000174, MAE: 0.010277, R²: -0.0509
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.16263 | val 0.18515
  Epoch 020 - train 0.15432 | val 0.18799
  Regression -> MSE: 0.000086, MAE: 0.007110, R²: -0.0108
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.15427 | val 0.18234
  Epoch 020 - train 0.15092 | val 0.19069
  Regression -> MSE: 0.000217, MAE: 0.011034, R²: -0.0235
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.15188 | val 0.14281
  Epoch 020 - train 0.14609 | val 0.13946
  Regression -> MSE: 0.000103, MAE: 0.008277, R²: -0.1180
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.14656 | val 0.12021
  Epoch 020 - train 0.14504 | val 0.11751
  Regression -> MSE: 0.000112, MAE: 0.009077, R²: -0.0815
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.15354 | val 0.14464
  Epoch 020 - train 0.15171 | val 0.14531
  Regression -> MSE: 0.000239, MAE: 0.012807, R²: -0.0317
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.14568 | val 0.19031
  Epoch 020 - train 0.14635 | val 0.19401
  Regression -> MSE: 0.000168, MAE: 0.007818, R²: -0.0114
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.15938 | val 0.12797
  Epoch 020 - train 0.15259 | val 0.13629
  Regression -> MSE: 0.000237, MAE: 0.011854, R²: -0.0004
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.14606 | val 0.24165
  Epoch 020 - train 0.14120 | val 0.25713
  Regression -> MSE: 0.000232, MAE: 0.009989, R²: -0.0085
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.16164 | val 0.19616
  Epoch 020 - train 0.15683 | val 0.21217
  Regression -> MSE: 0.000141, MAE: 0.008471, R²: -0.0443
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.15236 | val 0.18737
  Epoch 020 - train 0.15236 | val 0.19006
  Regression -> MSE: 0.000203, MAE: 0.010889, R²: -0.0807
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.14036 | val 0.16483
  Epoch 020 - train 0.13553 | val 0.16342
  Regression -> MSE: 0.000282, MAE: 0.011023, R²: -0.0770
  Directional -> Accuracy: 0.5342, MCC: 0.0966, F1: 0.5143

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.13670 | val 0.13263
  Epoch 020 - train 0.13818 | val 0.12546
  Regression -> MSE: 0.000164, MAE: 0.010300, R²: 0.0170
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.13984 | val 0.14831
  Epoch 020 - train 0.13616 | val 0.15319
  Regression -> MSE: 0.000181, MAE: 0.010305, R²: -0.0062
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.14805 | val 0.13911
  Epoch 020 - train 0.14197 | val 0.13665
  Regression -> MSE: 0.000344, MAE: 0.012014, R²: -0.0048
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.15911 | val 0.09487
  Epoch 020 - train 0.15867 | val 0.11238
  Regression -> MSE: 0.000113, MAE: 0.008333, R²: -0.0755
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.14642 | val 0.20782
  Epoch 020 - train 0.15237 | val 0.22264
  Regression -> MSE: 0.000222, MAE: 0.011407, R²: -0.0147
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.15734 | val 0.27453
  Epoch 020 - train 0.15814 | val 0.30931
  Regression -> MSE: 0.000081, MAE: 0.006984, R²: -0.0364
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.14941 | val 0.10988
  Epoch 020 - train 0.14755 | val 0.11002
  Regression -> MSE: 0.000310, MAE: 0.013945, R²: -0.0085
  Directional -> Accuracy: 0.6327, MCC: 0.0000, F1: 0.0000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.15949 | val 0.09168
  Epoch 020 - train 0.15798 | val 0.10448
  Regression -> MSE: 0.000246, MAE: 0.011556, R²: -0.0075
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.0000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.14308 | val 0.17352
  Epoch 020 - train 0.14383 | val 0.17383
  Regression -> MSE: 0.000087, MAE: 0.007482, R²: -0.0814
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.15469 | val 0.19209
  Epoch 020 - train 0.15326 | val 0.18068
  Regression -> MSE: 0.000311, MAE: 0.014603, R²: -0.0132
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.15138 | val 0.15509
  Epoch 020 - train 0.15145 | val 0.15491
  Regression -> MSE: 0.000099, MAE: 0.007450, R²: -0.0082
  Directional -> Accuracy: 0.4318, MCC: 0.0000, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.16880 | val 0.17425
  Epoch 020 - train 0.15975 | val 0.16816
  Regression -> MSE: 0.000173, MAE: 0.009482, R²: -0.0093
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.13465 | val 0.17804
  Epoch 020 - train 0.13746 | val 0.18089
  Regression -> MSE: 0.000228, MAE: 0.011831, R²: -0.0204
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.15407 | val 0.16294
  Epoch 020 - train 0.14722 | val 0.16167
  Regression -> MSE: 0.000093, MAE: 0.007670, R²: -0.0027
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.15718 | val 0.23639
  Epoch 020 - train 0.15706 | val 0.23756
  Regression -> MSE: 0.000164, MAE: 0.010273, R²: -0.0044
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.15172 | val 0.18634
  Epoch 020 - train 0.14637 | val 0.18895
  Regression -> MSE: 0.000125, MAE: 0.009034, R²: -0.0805
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.14516 | val 0.27160

[I 2026-02-23 02:59:46,057] Trial 209 finished with value: -0.011466499552709078 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 32, 'learning_rate': 5.0628237135295845e-06, 'weight_decay': 3.204395513979585e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.22988985651691007, 'early_stopping_min_delta': 0.005336974838804342}. Best is trial 207 with value: -0.01137496405368131.

  Epoch 020 - train 0.14851 | val 0.31101
  Regression -> MSE: 0.000237, MAE: 0.012334, R²: 0.0008
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.11075 | val 0.14819
  Epoch 020 - train 0.11280 | val 0.14910
  Regression -> MSE: 0.000252, MAE: 0.012746, R²: -0.0196
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.11195 | val 0.10518
  Epoch 020 - train 0.11276 | val 0.10355
  Regression -> MSE: 0.000678, MAE: 0.019418, R²: 0.0089
  Directional -> Accuracy: 0.5652, MCC: 0.0782, F1: 0.6667

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.11917 | val 0.18282
  Epoch 020 - train 0.12140 | val 0.17695
  Regression -> MSE: 0.000311, MAE: 0.013983, R²: -0.0037
  Directional -> Accuracy: 0.6596, MCC: 0.3212, F1: 0.6667

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.09851 | val 0.09532
  Epoch 020 - train 0.09601 | val 0.09632
  Regression -> MSE: 0.000350, MAE: 0.014598, R²: -0.0027
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.10866 | val 0.10813
  Epoch 020 - train 0.10910 | val 0.10679
  Regression -> MSE: 0.000198, MAE: 0.009424, R²: 0.0255
  Directional -> Accuracy: 0.7255, MCC: 0.4632, F1: 0.7742

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.11123 | val 0.21418
  Epoch 020 - train 0.10809 | val 0.20700
  Regression -> MSE: 0.000610, MAE: 0.019334, R²: -0.0982
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.11614 | val 0.13641
  Epoch 020 - train 0.11282 | val 0.13615
  Regression -> MSE: 0.000246, MAE: 0.012067, R²: -0.0008
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.11426 | val 0.13898
  Epoch 020 - train 0.11079 | val 0.15435
  Regression -> MSE: 0.000608, MAE: 0.019423, R²: -0.0177
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.12277 | val 0.14526
  Epoch 020 - train 0.11876 | val 0.16096
  Regression -> MSE: 0.000385, MAE: 0.016115, R²: -0.0024
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.11963 | val 0.14701
  Epoch 020 - train 0.11815 | val 0.14812
  Regression -> MSE: 0.000245, MAE: 0.011656, R²: -0.0165
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.10555 | val 0.16324
  Epoch 020 - train 0.10321 | val 0.17116
  Regression -> MSE: 0.000312, MAE: 0.013629, R²: -0.0047
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.12291 | val 0.13146
  Epoch 020 - train 0.12365 | val 0.13203
  Regression -> MSE: 0.000683, MAE: 0.019676, R²: -0.0086
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.11527 | val 0.12500
  Epoch 020 - train 0.11476 | val 0.14413
  Regression -> MSE: 0.000138, MAE: 0.009042, R²: -0.0002
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.10449 | val 0.15676
  Epoch 020 - train 0.10603 | val 0.15870
  Regression -> MSE: 0.000225, MAE: 0.010698, R²: 0.0004
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.11218 | val 0.22047
  Epoch 020 - train 0.11036 | val 0.22395
  Regression -> MSE: 0.000368, MAE: 0.015953, R²: -0.0161
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.12207 | val 0.11821
  Epoch 020 - train 0.11888 | val 0.11861
  Regression -> MSE: 0.000108, MAE: 0.008022, R²: -0.0034
  Directional -> Accuracy: 0.4857, MCC: -0.1004, F1: 0.6170

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.11148 | val 0.19296
  Epoch 020 - train 0.11134 | val 0.20583
  Regression -> MSE: 0.000161, MAE: 0.010130, R²: -0.0321
  Directional -> Accuracy: 0.3729, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.11459 | val 0.11661
  Epoch 020 - train 0.11392 | val 0.11568
  Regression -> MSE: 0.000276, MAE: 0.012893, R²: -0.0145
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.10158 | val 0.15932
  Epoch 020 - train 0.10083 | val 0.15659
  Regression -> MSE: 0.000157, MAE: 0.008831, R²: -0.0514
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.11652 | val 0.17187
  Epoch 020 - train 0.11628 | val 0.16827
  Regression -> MSE: 0.000233, MAE: 0.010939, R²: -0.0295
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.12170 | val 0.14199
  Epoch 020 - train 0.12217 | val 0.15263
  Regression -> MSE: 0.000144, MAE: 0.008388, R²: -0.0052
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.10756 | val 0.13212
  Epoch 020 - train 0.10819 | val 0.13205
  Regression -> MSE: 0.000165, MAE: 0.010491, R²: 0.0027
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.11212 | val 0.13702
  Epoch 020 - train 0.11918 | val 0.13968
  Regression -> MSE: 0.000086, MAE: 0.007066, R²: -0.0046
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.11317 | val 0.14082
  Epoch 020 - train 0.11239 | val 0.14211
  Regression -> MSE: 0.000214, MAE: 0.011349, R²: -0.0084
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.11822 | val 0.11060
  Epoch 020 - train 0.11395 | val 0.11416
  Regression -> MSE: 0.000092, MAE: 0.008095, R²: -0.0007
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.11437 | val 0.08948
  Epoch 020 - train 0.10897 | val 0.09044
  Regression -> MSE: 0.000102, MAE: 0.008764, R²: 0.0074
  Directional -> Accuracy: 0.4783, MCC: 0.1870, F1: 0.6250

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.11493 | val 0.10610
  Epoch 020 - train 0.11735 | val 0.10504
  Regression -> MSE: 0.000235, MAE: 0.012702, R²: -0.0161
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.12185 | val 0.15264
  Epoch 020 - train 0.12037 | val 0.15711
  Regression -> MSE: 0.000170, MAE: 0.007814, R²: -0.0198
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.11191 | val 0.09543
  Epoch 020 - train 0.11117 | val 0.09971
  Regression -> MSE: 0.000237, MAE: 0.011869, R²: -0.0002
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.11199 | val 0.17520
  Epoch 020 - train 0.11697 | val 0.17354
  Regression -> MSE: 0.000231, MAE: 0.009908, R²: -0.0029
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.11796 | val 0.14331
  Epoch 020 - train 0.11261 | val 0.15012
  Regression -> MSE: 0.000141, MAE: 0.008486, R²: -0.0472
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.11510 | val 0.13900
  Epoch 020 - train 0.11193 | val 0.14083
  Regression -> MSE: 0.000199, MAE: 0.010693, R²: -0.0595
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.10212 | val 0.12853
  Epoch 020 - train 0.09957 | val 0.12757
  Regression -> MSE: 0.000281, MAE: 0.010963, R²: -0.0722
  Directional -> Accuracy: 0.4384, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.10899 | val 0.09432
  Epoch 020 - train 0.10690 | val 0.09859
  Regression -> MSE: 0.000168, MAE: 0.010368, R²: -0.0051
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.10718 | val 0.12171
  Epoch 020 - train 0.10971 | val 0.14839
  Regression -> MSE: 0.000180, MAE: 0.010261, R²: -0.0014
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.10782 | val 0.10669
  Epoch 020 - train 0.10514 | val 0.10831
  Regression -> MSE: 0.000344, MAE: 0.011689, R²: -0.0034
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.12318 | val 0.07653
  Epoch 020 - train 0.12304 | val 0.08638
  Regression -> MSE: 0.000112, MAE: 0.008320, R²: -0.0619
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.11895 | val 0.15431
  Epoch 020 - train 0.11314 | val 0.15908
  Regression -> MSE: 0.000220, MAE: 0.011363, R²: -0.0087
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.11943 | val 0.18711
  Epoch 020 - train 0.11680 | val 0.19010
  Regression -> MSE: 0.000097, MAE: 0.007671, R²: -0.2452
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.10644 | val 0.09561
  Epoch 020 - train 0.10956 | val 0.09534
  Regression -> MSE: 0.000339, MAE: 0.015318, R²: -0.1013
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.12754 | val 0.07065
  Epoch 020 - train 0.12397 | val 0.07596
  Regression -> MSE: 0.000251, MAE: 0.011484, R²: -0.0284
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.11973 | val 0.15614
  Epoch 020 - train 0.11708 | val 0.15612
  Regression -> MSE: 0.000085, MAE: 0.007064, R²: -0.0492
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.11711 | val 0.14789
  Epoch 020 - train 0.11535 | val 0.18926
  Regression -> MSE: 0.000308, MAE: 0.014502, R²: -0.0027
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.11051 | val 0.12582
  Epoch 020 - train 0.10716 | val 0.13169
  Regression -> MSE: 0.000099, MAE: 0.007201, R²: -0.0081
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.11968 | val 0.13431
  Epoch 020 - train 0.11783 | val 0.13488
  Regression -> MSE: 0.000177, MAE: 0.010293, R²: -0.0295
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.10328 | val 0.12542
  Epoch 020 - train 0.10214 | val 0.12463
  Regression -> MSE: 0.000224, MAE: 0.011741, R²: -0.0041
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.11167 | val 0.12450
  Epoch 020 - train 0.11358 | val 0.12706
  Regression -> MSE: 0.000093, MAE: 0.007681, R²: -0.0068
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.11892 | val 0.17183
  Epoch 020 - train 0.11586 | val 0.17822
  Regression -> MSE: 0.000164, MAE: 0.010218, R²: 0.0012
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.11412 | val 0.13570
  Epoch 020 - train 0.11489 | val 0.14039
  Regression -> MSE: 0.000122, MAE: 0.008995, R²: -0.0517
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.11300 | val 0.15738

[I 2026-02-23 03:02:29,875] Trial 210 finished with value: -0.011433730811121225 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 32, 'learning_rate': 3.5002314136354508e-06, 'weight_decay': 4.034742871373603e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.1658194451534255, 'early_stopping_min_delta': 0.00551409991548758}. Best is trial 207 with value: -0.01137496405368131.

  Epoch 020 - train 0.11199 | val 0.16182
  Regression -> MSE: 0.000243, MAE: 0.012352, R²: -0.0267
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.11832 | val 0.15922
  Epoch 020 - train 0.12039 | val 0.15893
  Regression -> MSE: 0.000259, MAE: 0.012968, R²: -0.0451
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.12583 | val 0.11318
  Epoch 020 - train 0.12100 | val 0.14532
  Regression -> MSE: 0.000718, MAE: 0.019924, R²: -0.0488
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.12660 | val 0.19269
  Epoch 020 - train 0.12249 | val 0.19070
  Regression -> MSE: 0.000310, MAE: 0.014398, R²: -0.0005
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.10795 | val 0.17163
  Epoch 020 - train 0.10548 | val 0.18990
  Regression -> MSE: 0.000383, MAE: 0.015121, R²: -0.0958
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.12437 | val 0.11583
  Epoch 020 - train 0.12148 | val 0.11416
  Regression -> MSE: 0.000211, MAE: 0.010443, R²: -0.0379
  Directional -> Accuracy: 0.5686, MCC: 0.1434, F1: 0.6944

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.12089 | val 0.22331
  Epoch 020 - train 0.11695 | val 0.24065
  Regression -> MSE: 0.000562, MAE: 0.018191, R²: -0.0118
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.12671 | val 0.17059
  Epoch 020 - train 0.12273 | val 0.17170
  Regression -> MSE: 0.000246, MAE: 0.011999, R²: -0.0020
  Directional -> Accuracy: 0.4638, MCC: 0.0075, F1: 0.5195

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.11271 | val 0.15531
  Epoch 020 - train 0.12168 | val 0.16377
  Regression -> MSE: 0.000616, MAE: 0.019615, R²: -0.0312
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.11319 | val 0.14141
  Epoch 020 - train 0.10736 | val 0.14417
  Regression -> MSE: 0.000402, MAE: 0.016082, R²: -0.0468
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.12148 | val 0.17621
  Epoch 020 - train 0.11947 | val 0.18128
  Regression -> MSE: 0.000245, MAE: 0.011628, R²: -0.0139
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.11702 | val 0.16396
  Epoch 020 - train 0.11236 | val 0.16520
  Regression -> MSE: 0.000326, MAE: 0.013620, R²: -0.0480
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.12212 | val 0.14185
  Epoch 020 - train 0.12212 | val 0.14311
  Regression -> MSE: 0.000678, MAE: 0.019507, R²: -0.0007
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.11463 | val 0.12185
  Epoch 020 - train 0.11847 | val 0.12055
  Regression -> MSE: 0.000141, MAE: 0.009243, R²: -0.0199
  Directional -> Accuracy: 0.4884, MCC: -0.0617, F1: 0.3529

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.11581 | val 0.16660
  Epoch 020 - train 0.11586 | val 0.16442
  Regression -> MSE: 0.000228, MAE: 0.010965, R²: -0.0131
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.12374 | val 0.24102
  Epoch 020 - train 0.12258 | val 0.24050
  Regression -> MSE: 0.000373, MAE: 0.015933, R²: -0.0292
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.12443 | val 0.12797
  Epoch 020 - train 0.12742 | val 0.12774
  Regression -> MSE: 0.000108, MAE: 0.008000, R²: -0.0017
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.12480 | val 0.23641
  Epoch 020 - train 0.12328 | val 0.27336
  Regression -> MSE: 0.000162, MAE: 0.010165, R²: -0.0371
  Directional -> Accuracy: 0.3729, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.13318 | val 0.22831
  Epoch 020 - train 0.13076 | val 0.24645
  Regression -> MSE: 0.000285, MAE: 0.013656, R²: -0.0486
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.10949 | val 0.16201
  Epoch 020 - train 0.10860 | val 0.16152
  Regression -> MSE: 0.000154, MAE: 0.008762, R²: -0.0322
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.12206 | val 0.17064
  Epoch 020 - train 0.11780 | val 0.16911
  Regression -> MSE: 0.000230, MAE: 0.010933, R²: -0.0152
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.12601 | val 0.15184
  Epoch 020 - train 0.12362 | val 0.15783
  Regression -> MSE: 0.000154, MAE: 0.008837, R²: -0.0712
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.11431 | val 0.13615
  Epoch 020 - train 0.11689 | val 0.13424
  Regression -> MSE: 0.000181, MAE: 0.010339, R²: -0.0968
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.12263 | val 0.14054
  Epoch 020 - train 0.12533 | val 0.14253
  Regression -> MSE: 0.000086, MAE: 0.007083, R²: -0.0072
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.11738 | val 0.15356
  Epoch 020 - train 0.11897 | val 0.16235
  Regression -> MSE: 0.000212, MAE: 0.011237, R²: -0.0023
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.10819 | val 0.10480
  Epoch 020 - train 0.10890 | val 0.10326
  Regression -> MSE: 0.000097, MAE: 0.008147, R²: -0.0513
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.12369 | val 0.09526
  Epoch 020 - train 0.11843 | val 0.09707
  Regression -> MSE: 0.000104, MAE: 0.008788, R²: -0.0133
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.12322 | val 0.11348
  Epoch 020 - train 0.12219 | val 0.11571
  Regression -> MSE: 0.000241, MAE: 0.012864, R²: -0.0409
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.11737 | val 0.15202
  Epoch 020 - train 0.11728 | val 0.15701
  Regression -> MSE: 0.000179, MAE: 0.007944, R²: -0.0743
  Directional -> Accuracy: 0.4737, MCC: -0.0688, F1: 0.5312

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.12421 | val 0.10661
  Epoch 020 - train 0.12509 | val 0.11095
  Regression -> MSE: 0.000239, MAE: 0.011954, R²: -0.0096
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.11684 | val 0.19168
  Epoch 020 - train 0.11822 | val 0.19173
  Regression -> MSE: 0.000233, MAE: 0.010029, R²: -0.0116
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.12570 | val 0.14868
  Epoch 020 - train 0.12288 | val 0.14637
  Regression -> MSE: 0.000139, MAE: 0.008349, R²: -0.0260
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.12281 | val 0.14971
  Epoch 020 - train 0.12407 | val 0.15126
  Regression -> MSE: 0.000189, MAE: 0.010426, R²: -0.0045
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.10655 | val 0.13150
  Epoch 020 - train 0.10511 | val 0.13124
  Regression -> MSE: 0.000276, MAE: 0.010836, R²: -0.0557
  Directional -> Accuracy: 0.4384, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.10925 | val 0.10027
  Epoch 020 - train 0.11295 | val 0.10113
  Regression -> MSE: 0.000166, MAE: 0.010364, R²: 0.0012
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.11018 | val 0.12815
  Epoch 020 - train 0.10793 | val 0.15534
  Regression -> MSE: 0.000181, MAE: 0.010332, R²: -0.0039
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.12127 | val 0.11539
  Epoch 020 - train 0.11959 | val 0.11498
  Regression -> MSE: 0.000344, MAE: 0.011762, R²: -0.0027
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.12377 | val 0.07786
  Epoch 020 - train 0.12990 | val 0.08147
  Regression -> MSE: 0.000120, MAE: 0.008376, R²: -0.1422
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.13054 | val 0.16262
  Epoch 020 - train 0.12910 | val 0.16358
  Regression -> MSE: 0.000219, MAE: 0.011272, R²: -0.0002
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.11911 | val 0.20191
  Epoch 020 - train 0.11880 | val 0.21013
  Regression -> MSE: 0.000085, MAE: 0.007213, R²: -0.0974
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.11596 | val 0.10408
  Epoch 020 - train 0.11270 | val 0.10713
  Regression -> MSE: 0.000339, MAE: 0.015314, R²: -0.1011
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.13546 | val 0.07358
  Epoch 020 - train 0.13011 | val 0.07653
  Regression -> MSE: 0.000252, MAE: 0.011484, R²: -0.0347
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.11578 | val 0.14547
  Epoch 020 - train 0.11150 | val 0.14523
  Regression -> MSE: 0.000085, MAE: 0.007066, R²: -0.0550
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.12215 | val 0.15339
  Epoch 020 - train 0.12274 | val 0.16450
  Regression -> MSE: 0.000307, MAE: 0.014496, R²: -0.0004
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.11663 | val 0.14026
  Epoch 020 - train 0.11950 | val 0.13753
  Regression -> MSE: 0.000101, MAE: 0.007109, R²: -0.0279
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.13228 | val 0.14108
  Epoch 020 - train 0.12511 | val 0.14826
  Regression -> MSE: 0.000172, MAE: 0.009839, R²: -0.0033
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.11425 | val 0.14748
  Epoch 020 - train 0.11933 | val 0.15823
  Regression -> MSE: 0.000225, MAE: 0.011798, R²: -0.0070
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.11978 | val 0.13219
  Epoch 020 - train 0.11889 | val 0.13187
  Regression -> MSE: 0.000095, MAE: 0.007828, R²: -0.0312
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.12519 | val 0.18178
  Epoch 020 - train 0.12383 | val 0.18160
  Regression -> MSE: 0.000164, MAE: 0.010255, R²: -0.0019
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.11311 | val 0.16006
  Epoch 020 - train 0.11672 | val 0.16657
  Regression -> MSE: 0.000118, MAE: 0.008947, R²: -0.0200
  Directional -> Accuracy: 0.6250, MCC: 0.3210, F1: 0.7273

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.12473 | val 0.17060

[I 2026-02-23 03:05:13,605] Trial 211 finished with value: -0.011476553054038482 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 32, 'learning_rate': 3.068570637240125e-06, 'weight_decay': 4.465968639458953e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.17823867809498414, 'early_stopping_min_delta': 0.005546921789617717}. Best is trial 207 with value: -0.01137496405368131.

  Epoch 020 - train 0.12611 | val 0.17470
  Regression -> MSE: 0.000238, MAE: 0.012388, R²: -0.0033
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.10108 | val 0.14326
  Epoch 020 - train 0.10111 | val 0.14619
  Regression -> MSE: 0.000247, MAE: 0.012512, R²: 0.0012
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.09909 | val 0.09877
  Epoch 020 - train 0.09961 | val 0.10306
  Regression -> MSE: 0.000706, MAE: 0.019719, R²: -0.0308
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.11031 | val 0.16961
  Epoch 020 - train 0.10687 | val 0.17206
  Regression -> MSE: 0.000322, MAE: 0.014529, R²: -0.0373
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.08748 | val 0.11363
  Epoch 020 - train 0.08689 | val 0.10576
  Regression -> MSE: 0.000361, MAE: 0.014781, R²: -0.0329
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.10699 | val 0.10396
  Epoch 020 - train 0.10562 | val 0.10720
  Regression -> MSE: 0.000204, MAE: 0.010036, R²: -0.0037
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.09436 | val 0.19120
  Epoch 020 - train 0.09771 | val 0.19531
  Regression -> MSE: 0.000585, MAE: 0.018660, R²: -0.0536
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.10949 | val 0.12914
  Epoch 020 - train 0.10590 | val 0.12946
  Regression -> MSE: 0.000252, MAE: 0.011971, R²: -0.0278
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.10730 | val 0.14003
  Epoch 020 - train 0.10205 | val 0.15202
  Regression -> MSE: 0.000633, MAE: 0.019950, R²: -0.0587
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.09975 | val 0.12054
  Epoch 020 - train 0.09872 | val 0.12286
  Regression -> MSE: 0.000409, MAE: 0.016224, R²: -0.0663
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.10361 | val 0.14540
  Epoch 020 - train 0.10356 | val 0.14363
  Regression -> MSE: 0.000242, MAE: 0.011943, R²: -0.0012
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.09847 | val 0.15611
  Epoch 020 - train 0.09667 | val 0.16465
  Regression -> MSE: 0.000312, MAE: 0.013690, R²: -0.0036
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.6301

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.10809 | val 0.12361
  Epoch 020 - train 0.10970 | val 0.13515
  Regression -> MSE: 0.000679, MAE: 0.019540, R²: -0.0022
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.11991 | val 0.13911
  Epoch 020 - train 0.11624 | val 0.19375
  Regression -> MSE: 0.000139, MAE: 0.008993, R²: -0.0078
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.10363 | val 0.13515
  Epoch 020 - train 0.10291 | val 0.13265
  Regression -> MSE: 0.000224, MAE: 0.010503, R²: 0.0058
  Directional -> Accuracy: 0.5738, MCC: 0.1467, F1: 0.5938

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.10230 | val 0.21211
  Epoch 020 - train 0.09957 | val 0.22901
  Regression -> MSE: 0.000363, MAE: 0.016071, R²: -0.0014
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.10803 | val 0.11810
  Epoch 020 - train 0.10770 | val 0.11817
  Regression -> MSE: 0.000108, MAE: 0.008090, R²: -0.0059
  Directional -> Accuracy: 0.4571, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.11107 | val 0.17197
  Epoch 020 - train 0.10632 | val 0.18314
  Regression -> MSE: 0.000164, MAE: 0.010271, R²: -0.0507
  Directional -> Accuracy: 0.3729, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.10602 | val 0.10531
  Epoch 020 - train 0.10756 | val 0.10532
  Regression -> MSE: 0.000272, MAE: 0.013039, R²: 0.0001
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.09550 | val 0.14037
  Epoch 020 - train 0.09428 | val 0.13872
  Regression -> MSE: 0.000154, MAE: 0.008754, R²: -0.0306
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.11254 | val 0.15553
  Epoch 020 - train 0.11118 | val 0.15536
  Regression -> MSE: 0.000228, MAE: 0.010910, R²: -0.0095
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.11030 | val 0.12912
  Epoch 020 - train 0.11192 | val 0.12988
  Regression -> MSE: 0.000143, MAE: 0.008301, R²: -0.0000
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.09739 | val 0.12498
  Epoch 020 - train 0.09779 | val 0.12725
  Regression -> MSE: 0.000173, MAE: 0.010252, R²: -0.0485
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.10788 | val 0.12134
  Epoch 020 - train 0.11179 | val 0.12089
  Regression -> MSE: 0.000085, MAE: 0.007050, R²: -0.0031
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.10039 | val 0.13285
  Epoch 020 - train 0.10176 | val 0.14742
  Regression -> MSE: 0.000214, MAE: 0.011419, R²: -0.0110
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.09702 | val 0.09701
  Epoch 020 - train 0.09442 | val 0.09461
  Regression -> MSE: 0.000103, MAE: 0.008303, R²: -0.1175
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.10749 | val 0.08519
  Epoch 020 - train 0.10802 | val 0.08409
  Regression -> MSE: 0.000111, MAE: 0.009072, R²: -0.0800
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.10922 | val 0.10218
  Epoch 020 - train 0.10552 | val 0.11065
  Regression -> MSE: 0.000232, MAE: 0.012548, R²: -0.0009
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.10290 | val 0.11583
  Epoch 020 - train 0.09923 | val 0.11550
  Regression -> MSE: 0.000194, MAE: 0.009267, R²: -0.1654
  Directional -> Accuracy: 0.4211, MCC: -0.2830, F1: 0.5714

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.10717 | val 0.09359
  Epoch 020 - train 0.10866 | val 0.09236
  Regression -> MSE: 0.000240, MAE: 0.012032, R²: -0.0148
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.10823 | val 0.15920
  Epoch 020 - train 0.11094 | val 0.16076
  Regression -> MSE: 0.000231, MAE: 0.009868, R²: -0.0010
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.10941 | val 0.13074
  Epoch 020 - train 0.10861 | val 0.15499
  Regression -> MSE: 0.000137, MAE: 0.008297, R²: -0.0170
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.10912 | val 0.13185
  Epoch 020 - train 0.10460 | val 0.13241
  Regression -> MSE: 0.000189, MAE: 0.010406, R²: -0.0043
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.09202 | val 0.11484
  Epoch 020 - train 0.09064 | val 0.11554
  Regression -> MSE: 0.000270, MAE: 0.010629, R²: -0.0325
  Directional -> Accuracy: 0.5342, MCC: 0.1465, F1: 0.4333

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.09751 | val 0.08752
  Epoch 020 - train 0.10087 | val 0.08773
  Regression -> MSE: 0.000169, MAE: 0.010362, R²: -0.0155
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.09502 | val 0.12117
  Epoch 020 - train 0.09943 | val 0.14218
  Regression -> MSE: 0.000181, MAE: 0.010373, R²: -0.0069
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.09617 | val 0.09883
  Epoch 020 - train 0.09452 | val 0.09913
  Regression -> MSE: 0.000347, MAE: 0.012186, R²: -0.0118
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.11444 | val 0.07030
  Epoch 020 - train 0.11276 | val 0.07126
  Regression -> MSE: 0.000131, MAE: 0.008598, R²: -0.2458
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.11165 | val 0.15048
  Epoch 020 - train 0.11059 | val 0.15284
  Regression -> MSE: 0.000224, MAE: 0.011441, R²: -0.0231
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.10348 | val 0.17694
  Epoch 020 - train 0.10540 | val 0.18210
  Regression -> MSE: 0.000083, MAE: 0.007103, R²: -0.0682
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.10031 | val 0.07799
  Epoch 020 - train 0.10027 | val 0.07539
  Regression -> MSE: 0.000309, MAE: 0.013829, R²: -0.0039
  Directional -> Accuracy: 0.6327, MCC: 0.0000, F1: 0.0000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.11692 | val 0.06390
  Epoch 020 - train 0.11459 | val 0.06190
  Regression -> MSE: 0.000250, MAE: 0.011506, R²: -0.0267
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.10213 | val 0.12248
  Epoch 020 - train 0.09934 | val 0.12232
  Regression -> MSE: 0.000081, MAE: 0.007110, R²: -0.0048
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.10412 | val 0.12774
  Epoch 020 - train 0.10285 | val 0.13440
  Regression -> MSE: 0.000308, MAE: 0.014502, R²: -0.0025
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.09983 | val 0.12181
  Epoch 020 - train 0.10105 | val 0.11662
  Regression -> MSE: 0.000096, MAE: 0.007209, R²: 0.0205
  Directional -> Accuracy: 0.5000, MCC: -0.0617, F1: 0.6071

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.11367 | val 0.12219
  Epoch 020 - train 0.11093 | val 0.12433
  Regression -> MSE: 0.000172, MAE: 0.009558, R²: -0.0016
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.09678 | val 0.12323
  Epoch 020 - train 0.09619 | val 0.12324
  Regression -> MSE: 0.000223, MAE: 0.011748, R²: 0.0000
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.10512 | val 0.11881
  Epoch 020 - train 0.10448 | val 0.11697
  Regression -> MSE: 0.000095, MAE: 0.007812, R²: -0.0293
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.11209 | val 0.15756
  Epoch 020 - train 0.11190 | val 0.15945
  Regression -> MSE: 0.000164, MAE: 0.010275, R²: -0.0028
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.10525 | val 0.12700
  Epoch 020 - train 0.10139 | val 0.12751
  Regression -> MSE: 0.000129, MAE: 0.009068, R²: -0.1090
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.11197 | val 0.14753

[I 2026-02-23 03:07:57,418] Trial 212 finished with value: -0.011455934031791187 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 32, 'learning_rate': 3.541871212803405e-06, 'weight_decay': 3.783766431502145e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.15240103873201177, 'early_stopping_min_delta': 0.005158131463055785}. Best is trial 207 with value: -0.01137496405368131.

  Epoch 020 - train 0.11172 | val 0.14833
  Regression -> MSE: 0.000238, MAE: 0.012487, R²: -0.0043
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.14035 | val 0.18461
  Epoch 020 - train 0.14171 | val 0.18457
  Regression -> MSE: 0.000253, MAE: 0.012777, R²: -0.0227
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.13696 | val 0.13395
  Epoch 020 - train 0.13506 | val 0.13704
  Regression -> MSE: 0.000705, MAE: 0.019730, R²: -0.0306
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.14950 | val 0.23183
  Epoch 020 - train 0.15373 | val 0.23314
  Regression -> MSE: 0.000320, MAE: 0.014508, R²: -0.0310
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.11456 | val 0.12309
  Epoch 020 - train 0.11690 | val 0.11845
  Regression -> MSE: 0.000357, MAE: 0.014718, R²: -0.0219
  Directional -> Accuracy: 0.5067, MCC: -0.1859, F1: 0.6726

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.13519 | val 0.13768
  Epoch 020 - train 0.14024 | val 0.14654
  Regression -> MSE: 0.000206, MAE: 0.010094, R²: -0.0130
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.13182 | val 0.26228
  Epoch 020 - train 0.12853 | val 0.28569
  Regression -> MSE: 0.000570, MAE: 0.018381, R²: -0.0271
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.14682 | val 0.18399
  Epoch 020 - train 0.14347 | val 0.18280
  Regression -> MSE: 0.000248, MAE: 0.011952, R²: -0.0100
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.14202 | val 0.18953
  Epoch 020 - train 0.14347 | val 0.18038
  Regression -> MSE: 0.000652, MAE: 0.020219, R²: -0.0905
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.16187 | val 0.18969
  Epoch 020 - train 0.15892 | val 0.23906
  Regression -> MSE: 0.000382, MAE: 0.016172, R²: 0.0036
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.14331 | val 0.17832
  Epoch 020 - train 0.14040 | val 0.18027
  Regression -> MSE: 0.000242, MAE: 0.012087, R²: -0.0044
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.12546 | val 0.20198
  Epoch 020 - train 0.13037 | val 0.20222
  Regression -> MSE: 0.000311, MAE: 0.013657, R²: -0.0002
  Directional -> Accuracy: 0.4800, MCC: -0.0018, F1: 0.5667

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.14556 | val 0.16477
  Epoch 020 - train 0.14462 | val 0.16291
  Regression -> MSE: 0.000679, MAE: 0.019505, R²: -0.0023
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.15973 | val 0.15661
  Epoch 020 - train 0.15671 | val 0.20377
  Regression -> MSE: 0.000139, MAE: 0.009228, R²: -0.0071
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.12755 | val 0.18731
  Epoch 020 - train 0.13206 | val 0.18899
  Regression -> MSE: 0.000226, MAE: 0.010726, R²: -0.0069
  Directional -> Accuracy: 0.4918, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.13963 | val 0.28327
  Epoch 020 - train 0.13372 | val 0.28383
  Regression -> MSE: 0.000363, MAE: 0.016013, R²: -0.0027
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.14200 | val 0.14797
  Epoch 020 - train 0.14513 | val 0.15133
  Regression -> MSE: 0.000108, MAE: 0.007964, R²: -0.0054
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.14142 | val 0.22884
  Epoch 020 - train 0.14095 | val 0.23102
  Regression -> MSE: 0.000158, MAE: 0.009906, R²: -0.0124
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.14345 | val 0.14990
  Epoch 020 - train 0.14368 | val 0.14815
  Regression -> MSE: 0.000278, MAE: 0.013324, R²: -0.0199
  Directional -> Accuracy: 0.4211, MCC: -0.0329, F1: 0.2667

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.12810 | val 0.19002
  Epoch 020 - train 0.13127 | val 0.19094
  Regression -> MSE: 0.000159, MAE: 0.008903, R²: -0.0650
  Directional -> Accuracy: 0.5692, MCC: 0.1921, F1: 0.5484

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.13927 | val 0.19531
  Epoch 020 - train 0.14294 | val 0.19608
  Regression -> MSE: 0.000347, MAE: 0.013992, R²: -0.5341
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.14198 | val 0.17869
  Epoch 020 - train 0.14430 | val 0.17945
  Regression -> MSE: 0.000144, MAE: 0.008350, R²: -0.0038
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.13125 | val 0.16902
  Epoch 020 - train 0.12997 | val 0.16955
  Regression -> MSE: 0.000167, MAE: 0.010309, R²: -0.0085
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.14920 | val 0.18199
  Epoch 020 - train 0.14880 | val 0.18718
  Regression -> MSE: 0.000085, MAE: 0.007021, R²: -0.0009
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.14242 | val 0.17122
  Epoch 020 - train 0.14264 | val 0.17869
  Regression -> MSE: 0.000213, MAE: 0.011291, R²: -0.0050
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.13641 | val 0.12774
  Epoch 020 - train 0.13265 | val 0.12196
  Regression -> MSE: 0.000118, MAE: 0.008807, R²: -0.2815
  Directional -> Accuracy: 0.4464, MCC: -0.0207, F1: 0.0606

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.13998 | val 0.11531
  Epoch 020 - train 0.13605 | val 0.10966
  Regression -> MSE: 0.000109, MAE: 0.008969, R²: -0.0584
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.14631 | val 0.15934
  Epoch 020 - train 0.14798 | val 0.26732
  Regression -> MSE: 0.000239, MAE: 0.012829, R²: -0.0346
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.13663 | val 0.16645
  Epoch 020 - train 0.14130 | val 0.16781
  Regression -> MSE: 0.000181, MAE: 0.007981, R²: -0.0880
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.14676 | val 0.12046
  Epoch 020 - train 0.14597 | val 0.12587
  Regression -> MSE: 0.000237, MAE: 0.011861, R²: -0.0006
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.14820 | val 0.22279
  Epoch 020 - train 0.14246 | val 0.22313
  Regression -> MSE: 0.000231, MAE: 0.009897, R²: -0.0013
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.13927 | val 0.17193
  Epoch 020 - train 0.14537 | val 0.18896
  Regression -> MSE: 0.000135, MAE: 0.008236, R²: -0.0031
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.14259 | val 0.18143
  Epoch 020 - train 0.14348 | val 0.18626
  Regression -> MSE: 0.000194, MAE: 0.010471, R²: -0.0296
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.12736 | val 0.16110
  Epoch 020 - train 0.13044 | val 0.16101
  Regression -> MSE: 0.000274, MAE: 0.010763, R²: -0.0467
  Directional -> Accuracy: 0.4384, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.14545 | val 0.13489
  Epoch 020 - train 0.14403 | val 0.14907
  Regression -> MSE: 0.000171, MAE: 0.010393, R²: -0.0255
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.13240 | val 0.15712
  Epoch 020 - train 0.13653 | val 0.17896
  Regression -> MSE: 0.000185, MAE: 0.010525, R²: -0.0273
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.13465 | val 0.13188
  Epoch 020 - train 0.13061 | val 0.13274
  Regression -> MSE: 0.000347, MAE: 0.011725, R²: -0.0121
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.15153 | val 0.09187
  Epoch 020 - train 0.15043 | val 0.09461
  Regression -> MSE: 0.000123, MAE: 0.008423, R²: -0.1703
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.15090 | val 0.20945
  Epoch 020 - train 0.14667 | val 0.21000
  Regression -> MSE: 0.000227, MAE: 0.011528, R²: -0.0384
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.14287 | val 0.24527
  Epoch 020 - train 0.14090 | val 0.25369
  Regression -> MSE: 0.000090, MAE: 0.007433, R²: -0.1617
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.14773 | val 0.12508
  Epoch 020 - train 0.14494 | val 0.12354
  Regression -> MSE: 0.000348, MAE: 0.015603, R²: -0.1303
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.15631 | val 0.08538
  Epoch 020 - train 0.15665 | val 0.08705
  Regression -> MSE: 0.000245, MAE: 0.011560, R²: -0.0054
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.0000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.15692 | val 0.17951
  Epoch 020 - train 0.15102 | val 0.18342
  Regression -> MSE: 0.000083, MAE: 0.007061, R²: -0.0322
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.14267 | val 0.18462
  Epoch 020 - train 0.14479 | val 0.21034
  Regression -> MSE: 0.000307, MAE: 0.014486, R²: -0.0002
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.14305 | val 0.14859
  Epoch 020 - train 0.14650 | val 0.14947
  Regression -> MSE: 0.000098, MAE: 0.007397, R²: -0.0016
  Directional -> Accuracy: 0.4318, MCC: 0.0000, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.15104 | val 0.16940
  Epoch 020 - train 0.15211 | val 0.17124
  Regression -> MSE: 0.000174, MAE: 0.010097, R²: -0.0134
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.13660 | val 0.16857
  Epoch 020 - train 0.13977 | val 0.18001
  Regression -> MSE: 0.000229, MAE: 0.011938, R²: -0.0277
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.14822 | val 0.15033
  Epoch 020 - train 0.14020 | val 0.15060
  Regression -> MSE: 0.000092, MAE: 0.007656, R²: -0.0003
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.15349 | val 0.21778
  Epoch 020 - train 0.14841 | val 0.21884
  Regression -> MSE: 0.000165, MAE: 0.010304, R²: -0.0049
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.14166 | val 0.18698
  Epoch 020 - train 0.13862 | val 0.18607
  Regression -> MSE: 0.000118, MAE: 0.008944, R²: -0.0145
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.14229 | val 0.20061

[I 2026-02-23 03:10:41,427] Trial 213 finished with value: -0.01156109039587878 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 32, 'learning_rate': 4.398727766197782e-06, 'weight_decay': 2.4049806949728954e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.21564027026657173, 'early_stopping_min_delta': 0.00595947301951286}. Best is trial 207 with value: -0.01137496405368131.

  Epoch 020 - train 0.13905 | val 0.20237
  Regression -> MSE: 0.000241, MAE: 0.012338, R²: -0.0167
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.09976 | val 0.12978
  Epoch 020 - train 0.09688 | val 0.12922
  Regression -> MSE: 0.000256, MAE: 0.012888, R²: -0.0344
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.10505 | val 0.09313
  Epoch 020 - train 0.09964 | val 0.09566
  Regression -> MSE: 0.000696, MAE: 0.019554, R²: -0.0170
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.10580 | val 0.16004
  Epoch 020 - train 0.10313 | val 0.15880
  Regression -> MSE: 0.000318, MAE: 0.014490, R²: -0.0247
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.08439 | val 0.16747
  Epoch 020 - train 0.08343 | val 0.18775
  Regression -> MSE: 0.000349, MAE: 0.014571, R²: 0.0003
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.10134 | val 0.10004
  Epoch 020 - train 0.10087 | val 0.10666
  Regression -> MSE: 0.000204, MAE: 0.010133, R²: -0.0005
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.09455 | val 0.18140
  Epoch 020 - train 0.09601 | val 0.18200
  Regression -> MSE: 0.000558, MAE: 0.018152, R²: -0.0058
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.10410 | val 0.13743
  Epoch 020 - train 0.10193 | val 0.13094
  Regression -> MSE: 0.000252, MAE: 0.012587, R²: -0.0268
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.09903 | val 0.12569
  Epoch 020 - train 0.09593 | val 0.14788
  Regression -> MSE: 0.000613, MAE: 0.019539, R²: -0.0255
  Directional -> Accuracy: 0.4091, MCC: -0.0585, F1: 0.5517

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.09966 | val 0.12310
  Epoch 020 - train 0.09989 | val 0.12467
  Regression -> MSE: 0.000386, MAE: 0.016092, R²: -0.0064
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.09907 | val 0.13022
  Epoch 020 - train 0.09532 | val 0.13251
  Regression -> MSE: 0.000242, MAE: 0.011766, R²: -0.0004
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.10018 | val 0.13601
  Epoch 020 - train 0.09892 | val 0.13775
  Regression -> MSE: 0.000329, MAE: 0.013644, R²: -0.0596
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.10465 | val 0.11503
  Epoch 020 - train 0.09983 | val 0.11772
  Regression -> MSE: 0.000680, MAE: 0.019616, R²: -0.0045
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.10353 | val 0.10167
  Epoch 020 - train 0.09918 | val 0.12147
  Regression -> MSE: 0.000139, MAE: 0.009162, R²: -0.0027
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.09096 | val 0.13379
  Epoch 020 - train 0.09173 | val 0.13324
  Regression -> MSE: 0.000226, MAE: 0.010880, R²: -0.0058
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.10774 | val 0.20517
  Epoch 020 - train 0.10606 | val 0.21532
  Regression -> MSE: 0.000369, MAE: 0.015932, R²: -0.0200
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.10446 | val 0.10563
  Epoch 020 - train 0.10240 | val 0.10327
  Regression -> MSE: 0.000109, MAE: 0.008131, R²: -0.0103
  Directional -> Accuracy: 0.4571, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.10537 | val 0.19204
  Epoch 020 - train 0.10552 | val 0.21182
  Regression -> MSE: 0.000163, MAE: 0.010266, R²: -0.0486
  Directional -> Accuracy: 0.3729, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.10254 | val 0.10656
  Epoch 020 - train 0.09933 | val 0.10121
  Regression -> MSE: 0.000273, MAE: 0.012963, R²: -0.0019
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.08985 | val 0.14935
  Epoch 020 - train 0.08903 | val 0.15505
  Regression -> MSE: 0.000161, MAE: 0.008948, R²: -0.0794
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.10759 | val 0.14819
  Epoch 020 - train 0.10156 | val 0.14737
  Regression -> MSE: 0.000252, MAE: 0.011357, R²: -0.1138
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.10544 | val 0.12727
  Epoch 020 - train 0.10655 | val 0.13824
  Regression -> MSE: 0.000153, MAE: 0.008838, R²: -0.0686
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.10747 | val 0.13989
  Epoch 020 - train 0.10228 | val 0.14322
  Regression -> MSE: 0.000168, MAE: 0.010844, R²: -0.0188
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.10712 | val 0.12413
  Epoch 020 - train 0.10769 | val 0.12992
  Regression -> MSE: 0.000086, MAE: 0.007127, R²: -0.0149
  Directional -> Accuracy: 0.5862, MCC: 0.1522, F1: 0.7333

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.09798 | val 0.12298
  Epoch 020 - train 0.09593 | val 0.12264
  Regression -> MSE: 0.000214, MAE: 0.011049, R²: -0.0126
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.09217 | val 0.08702
  Epoch 020 - train 0.09254 | val 0.08519
  Regression -> MSE: 0.000097, MAE: 0.008155, R²: -0.0546
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.10547 | val 0.08324
  Epoch 020 - train 0.09883 | val 0.08104
  Regression -> MSE: 0.000117, MAE: 0.009234, R²: -0.1327
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.10178 | val 0.09652
  Epoch 020 - train 0.10438 | val 0.10372
  Regression -> MSE: 0.000233, MAE: 0.012593, R²: -0.0046
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.09910 | val 0.11135
  Epoch 020 - train 0.09858 | val 0.11064
  Regression -> MSE: 0.000192, MAE: 0.008243, R²: -0.1531
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.10212 | val 0.08590
  Epoch 020 - train 0.09979 | val 0.08660
  Regression -> MSE: 0.000237, MAE: 0.011864, R²: -0.0008
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.09518 | val 0.15697
  Epoch 020 - train 0.09848 | val 0.15886
  Regression -> MSE: 0.000232, MAE: 0.009957, R²: -0.0055
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.10342 | val 0.11311
  Epoch 020 - train 0.10255 | val 0.11178
  Regression -> MSE: 0.000135, MAE: 0.008174, R²: -0.0017
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.09742 | val 0.12578
  Epoch 020 - train 0.09846 | val 0.12794
  Regression -> MSE: 0.000189, MAE: 0.010403, R²: -0.0045
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.09366 | val 0.13637
  Epoch 020 - train 0.09412 | val 0.13520
  Regression -> MSE: 0.000283, MAE: 0.011059, R²: -0.0794
  Directional -> Accuracy: 0.4384, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.08863 | val 0.08631
  Epoch 020 - train 0.09157 | val 0.08489
  Regression -> MSE: 0.000167, MAE: 0.010367, R²: -0.0024
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.08979 | val 0.09965
  Epoch 020 - train 0.08912 | val 0.11021
  Regression -> MSE: 0.000184, MAE: 0.010457, R²: -0.0208
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.10058 | val 0.09531
  Epoch 020 - train 0.09773 | val 0.09190
  Regression -> MSE: 0.000354, MAE: 0.011849, R²: -0.0324
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.10653 | val 0.06657
  Epoch 020 - train 0.10390 | val 0.06942
  Regression -> MSE: 0.000129, MAE: 0.008541, R²: -0.2268
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.09649 | val 0.13282
  Epoch 020 - train 0.09770 | val 0.13488
  Regression -> MSE: 0.000219, MAE: 0.011320, R²: -0.0025
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.09943 | val 0.17226
  Epoch 020 - train 0.10247 | val 0.17815
  Regression -> MSE: 0.000081, MAE: 0.007013, R²: -0.0430
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.09962 | val 0.09070
  Epoch 020 - train 0.09606 | val 0.10015
  Regression -> MSE: 0.000345, MAE: 0.015507, R²: -0.1203
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.10981 | val 0.06341
  Epoch 020 - train 0.10823 | val 0.07168
  Regression -> MSE: 0.000249, MAE: 0.011513, R²: -0.0208
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.09644 | val 0.11980
  Epoch 020 - train 0.09177 | val 0.11893
  Regression -> MSE: 0.000081, MAE: 0.007095, R²: -0.0014
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.10419 | val 0.12274
  Epoch 020 - train 0.10169 | val 0.12349
  Regression -> MSE: 0.000303, MAE: 0.014442, R²: 0.0128
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.10529 | val 0.10730
  Epoch 020 - train 0.10158 | val 0.11280
  Regression -> MSE: 0.000098, MAE: 0.007275, R²: 0.0001
  Directional -> Accuracy: 0.5682, MCC: 0.2920, F1: 0.4242

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.10706 | val 0.12178
  Epoch 020 - train 0.10515 | val 0.12597
  Regression -> MSE: 0.000173, MAE: 0.009454, R²: -0.0082
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.08940 | val 0.10983
  Epoch 020 - train 0.09138 | val 0.10998
  Regression -> MSE: 0.000223, MAE: 0.011741, R²: 0.0001
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.09985 | val 0.11160
  Epoch 020 - train 0.09901 | val 0.11405
  Regression -> MSE: 0.000092, MAE: 0.007636, R²: -0.0003
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.10854 | val 0.15791
  Epoch 020 - train 0.10488 | val 0.16132
  Regression -> MSE: 0.000167, MAE: 0.010286, R²: -0.0171
  Directional -> Accuracy: 0.4815, MCC: 0.0000, F1: 0.0000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.10284 | val 0.12994
  Epoch 020 - train 0.09939 | val 0.13289
  Regression -> MSE: 0.000123, MAE: 0.009016, R²: -0.0638
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.10295 | val 0.13543

[I 2026-02-23 03:13:26,102] Trial 214 finished with value: -0.011482064341359496 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 32, 'learning_rate': 6.560494326718918e-06, 'weight_decay': 6.424529973128618e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.1452445169562647, 'early_stopping_min_delta': 0.0057387974037298615}. Best is trial 207 with value: -0.01137496405368131.

  Epoch 020 - train 0.10251 | val 0.13668
  Regression -> MSE: 0.000238, MAE: 0.012382, R²: -0.0016
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.16084 | val 0.21159
  Epoch 020 - train 0.16162 | val 0.21269
  Regression -> MSE: 0.000247, MAE: 0.012511, R²: 0.0005
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.15823 | val 0.15175
  Epoch 020 - train 0.15462 | val 0.18204
  Regression -> MSE: 0.000685, MAE: 0.019338, R²: -0.0003
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.16155 | val 0.26094
  Epoch 020 - train 0.15796 | val 0.26467
  Regression -> MSE: 0.000315, MAE: 0.014425, R²: -0.0140
  Directional -> Accuracy: 0.5319, MCC: 0.1314, F1: 0.3529

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.13605 | val 0.17015
  Epoch 020 - train 0.13490 | val 0.16039
  Regression -> MSE: 0.000351, MAE: 0.014567, R²: -0.0041
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.15952 | val 0.16232
  Epoch 020 - train 0.16020 | val 0.16013
  Regression -> MSE: 0.000209, MAE: 0.010145, R²: -0.0269
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.15110 | val 0.29944
  Epoch 020 - train 0.14901 | val 0.29901
  Regression -> MSE: 0.000556, MAE: 0.018247, R²: -0.0023
  Directional -> Accuracy: 0.4894, MCC: -0.0183, F1: 0.5200

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.17004 | val 0.20516
  Epoch 020 - train 0.16534 | val 0.20074
  Regression -> MSE: 0.000246, MAE: 0.012013, R²: -0.0016
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.15302 | val 0.23211
  Epoch 020 - train 0.15688 | val 0.20750
  Regression -> MSE: 0.000605, MAE: 0.019299, R²: -0.0126
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.15364 | val 0.19144
  Epoch 020 - train 0.15428 | val 0.20739
  Regression -> MSE: 0.000404, MAE: 0.016132, R²: -0.0540
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.15911 | val 0.21232
  Epoch 020 - train 0.15844 | val 0.21675
  Regression -> MSE: 0.000243, MAE: 0.012120, R²: -0.0060
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.14661 | val 0.22582
  Epoch 020 - train 0.14375 | val 0.22389
  Regression -> MSE: 0.000318, MAE: 0.013556, R²: -0.0233
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.17220 | val 0.19820
  Epoch 020 - train 0.17365 | val 0.20271
  Regression -> MSE: 0.000681, MAE: 0.019513, R²: -0.0062
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.18242 | val 0.19884
  Epoch 020 - train 0.18252 | val 0.26284
  Regression -> MSE: 0.000140, MAE: 0.008996, R²: -0.0167
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.15691 | val 0.24491
  Epoch 020 - train 0.15292 | val 0.25276
  Regression -> MSE: 0.000228, MAE: 0.010981, R²: -0.0144
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.16245 | val 0.32774
  Epoch 020 - train 0.16095 | val 0.32578
  Regression -> MSE: 0.000371, MAE: 0.015656, R²: -0.0257
  Directional -> Accuracy: 0.6154, MCC: 0.2467, F1: 0.3750

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.16767 | val 0.16253
  Epoch 020 - train 0.16910 | val 0.16192
  Regression -> MSE: 0.000106, MAE: 0.007932, R²: 0.0184
  Directional -> Accuracy: 0.5571, MCC: 0.1198, F1: 0.5634

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.15475 | val 0.29985
  Epoch 020 - train 0.15048 | val 0.31631
  Regression -> MSE: 0.000156, MAE: 0.009729, R²: 0.0002
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.16302 | val 0.17633
  Epoch 020 - train 0.16689 | val 0.17742
  Regression -> MSE: 0.000282, MAE: 0.013489, R²: -0.0351
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.14949 | val 0.22270
  Epoch 020 - train 0.14586 | val 0.22089
  Regression -> MSE: 0.000159, MAE: 0.008850, R²: -0.0596
  Directional -> Accuracy: 0.6154, MCC: 0.1622, F1: 0.7253

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.16111 | val 0.22633
  Epoch 020 - train 0.16449 | val 0.22606
  Regression -> MSE: 0.000231, MAE: 0.010896, R²: -0.0211
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.16118 | val 0.20164
  Epoch 020 - train 0.15856 | val 0.20243
  Regression -> MSE: 0.000154, MAE: 0.008870, R²: -0.0753
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.15299 | val 0.19284
  Epoch 020 - train 0.15256 | val 0.19451
  Regression -> MSE: 0.000165, MAE: 0.010588, R²: -0.0005
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.16516 | val 0.19828
  Epoch 020 - train 0.17271 | val 0.20006
  Regression -> MSE: 0.000085, MAE: 0.007035, R²: -0.0029
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.16066 | val 0.19745
  Epoch 020 - train 0.16016 | val 0.20060
  Regression -> MSE: 0.000212, MAE: 0.011192, R²: -0.0017
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.14592 | val 0.14170
  Epoch 020 - train 0.14527 | val 0.14096
  Regression -> MSE: 0.000103, MAE: 0.008433, R²: -0.1157
  Directional -> Accuracy: 0.4643, MCC: -0.1728, F1: 0.6053

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.17326 | val 0.14314
  Epoch 020 - train 0.16613 | val 0.15890
  Regression -> MSE: 0.000122, MAE: 0.009397, R²: -0.1800
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.17003 | val 0.15521
  Epoch 020 - train 0.16185 | val 0.18027
  Regression -> MSE: 0.000232, MAE: 0.012558, R²: -0.0021
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.15778 | val 0.17995
  Epoch 020 - train 0.14977 | val 0.17756
  Regression -> MSE: 0.000194, MAE: 0.008433, R²: -0.1680
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.16419 | val 0.13748
  Epoch 020 - train 0.16677 | val 0.14323
  Regression -> MSE: 0.000237, MAE: 0.011861, R²: -0.0006
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.16004 | val 0.25887
  Epoch 020 - train 0.15384 | val 0.27636
  Regression -> MSE: 0.000231, MAE: 0.009882, R²: -0.0011
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.16484 | val 0.20008
  Epoch 020 - train 0.16716 | val 0.20155
  Regression -> MSE: 0.000138, MAE: 0.008344, R²: -0.0246
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.17262 | val 0.20178
  Epoch 020 - train 0.16260 | val 0.20905
  Regression -> MSE: 0.000198, MAE: 0.010654, R²: -0.0529
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.14298 | val 0.18728
  Epoch 020 - train 0.13578 | val 0.18794
  Regression -> MSE: 0.000272, MAE: 0.010922, R²: -0.0389
  Directional -> Accuracy: 0.5616, MCC: 0.1446, F1: 0.5556

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.16420 | val 0.13513
  Epoch 020 - train 0.15895 | val 0.13089
  Regression -> MSE: 0.000168, MAE: 0.010427, R²: -0.0100
  Directional -> Accuracy: 0.3684, MCC: -0.2774, F1: 0.2500

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.14622 | val 0.16662
  Epoch 020 - train 0.14360 | val 0.18074
  Regression -> MSE: 0.000180, MAE: 0.010262, R²: 0.0007
  Directional -> Accuracy: 0.5000, MCC: 0.0424, F1: 0.6207

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.15449 | val 0.15962
  Epoch 020 - train 0.14747 | val 0.15896
  Regression -> MSE: 0.000351, MAE: 0.012466, R²: -0.0249
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.17251 | val 0.10380
  Epoch 020 - train 0.16986 | val 0.10264
  Regression -> MSE: 0.000125, MAE: 0.008457, R²: -0.1879
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.16850 | val 0.23676
  Epoch 020 - train 0.16789 | val 0.24632
  Regression -> MSE: 0.000219, MAE: 0.011289, R²: -0.0001
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.16125 | val 0.28976
  Epoch 020 - train 0.15981 | val 0.31709
  Regression -> MSE: 0.000083, MAE: 0.007092, R²: -0.0648
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.15972 | val 0.13729
  Epoch 020 - train 0.15649 | val 0.14912
  Regression -> MSE: 0.000335, MAE: 0.015186, R²: -0.0893
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.17008 | val 0.09633
  Epoch 020 - train 0.16626 | val 0.10244
  Regression -> MSE: 0.000250, MAE: 0.011507, R²: -0.0265
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.15574 | val 0.20242
  Epoch 020 - train 0.14432 | val 0.20395
  Regression -> MSE: 0.000081, MAE: 0.007091, R²: -0.0005
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.16683 | val 0.21415
  Epoch 020 - train 0.16528 | val 0.29994
  Regression -> MSE: 0.000307, MAE: 0.014499, R²: -0.0015
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.15225 | val 0.18353
  Epoch 020 - train 0.15511 | val 0.19116
  Regression -> MSE: 0.000100, MAE: 0.007128, R²: -0.0171
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.17795 | val 0.18916
  Epoch 020 - train 0.16705 | val 0.18895
  Regression -> MSE: 0.000172, MAE: 0.009736, R²: -0.0007
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.14744 | val 0.18877
  Epoch 020 - train 0.14889 | val 0.19506
  Regression -> MSE: 0.000225, MAE: 0.011808, R²: -0.0110
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.15895 | val 0.17868
  Epoch 020 - train 0.15740 | val 0.18104
  Regression -> MSE: 0.000094, MAE: 0.007710, R²: -0.0139
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.16776 | val 0.25073
  Epoch 020 - train 0.17081 | val 0.26012
  Regression -> MSE: 0.000164, MAE: 0.010259, R²: -0.0014
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.14874 | val 0.21155
  Epoch 020 - train 0.14918 | val 0.22267
  Regression -> MSE: 0.000121, MAE: 0.008983, R²: -0.0457
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.15966 | val 0.24197

[I 2026-02-23 03:16:10,016] Trial 215 finished with value: -0.011455976628091174 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 32, 'learning_rate': 5.175367311998027e-06, 'weight_decay': 4.6438165352472666e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.24965465065027448, 'early_stopping_min_delta': 0.00537687408054755}. Best is trial 207 with value: -0.01137496405368131.

  Epoch 020 - train 0.15389 | val 0.25697
  Regression -> MSE: 0.000239, MAE: 0.012337, R²: -0.0092
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.13226 | val 0.18464
  Epoch 020 - train 0.12959 | val 0.18422
  Regression -> MSE: 0.000255, MAE: 0.012855, R²: -0.0306
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.12657 | val 0.12763
  Epoch 020 - train 0.12817 | val 0.14713
  Regression -> MSE: 0.000695, MAE: 0.019526, R²: -0.0151
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.13251 | val 0.21629
  Epoch 020 - train 0.13380 | val 0.21606
  Regression -> MSE: 0.000315, MAE: 0.014455, R²: -0.0150
  Directional -> Accuracy: 0.4894, MCC: 0.1383, F1: 0.0769

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.11742 | val 0.13158
  Epoch 020 - train 0.11333 | val 0.13977
  Regression -> MSE: 0.000391, MAE: 0.015284, R²: -0.1181
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.13680 | val 0.12944
  Epoch 020 - train 0.13136 | val 0.12921
  Regression -> MSE: 0.000206, MAE: 0.010142, R²: -0.0138
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.12562 | val 0.24601
  Epoch 020 - train 0.11778 | val 0.24604
  Regression -> MSE: 0.000600, MAE: 0.018904, R²: -0.0813
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.13639 | val 0.16258
  Epoch 020 - train 0.13557 | val 0.16220
  Regression -> MSE: 0.000254, MAE: 0.012000, R²: -0.0336
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.13397 | val 0.15981
  Epoch 020 - train 0.13603 | val 0.14690
  Regression -> MSE: 0.000616, MAE: 0.019135, R²: -0.0318
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.12359 | val 0.15849
  Epoch 020 - train 0.12016 | val 0.15675
  Regression -> MSE: 0.000394, MAE: 0.015942, R²: -0.0262
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.12769 | val 0.17380
  Epoch 020 - train 0.12928 | val 0.17352
  Regression -> MSE: 0.000243, MAE: 0.011713, R²: -0.0045
  Directional -> Accuracy: 0.5143, MCC: 0.0589, F1: 0.5278

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.12384 | val 0.18455
  Epoch 020 - train 0.12738 | val 0.18477
  Regression -> MSE: 0.000315, MAE: 0.013599, R²: -0.0116
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.14271 | val 0.15193
  Epoch 020 - train 0.13920 | val 0.15349
  Regression -> MSE: 0.000689, MAE: 0.019901, R²: -0.0171
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.13595 | val 0.14298
  Epoch 020 - train 0.13652 | val 0.14728
  Regression -> MSE: 0.000138, MAE: 0.009027, R²: -0.0022
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.12346 | val 0.16639
  Epoch 020 - train 0.11830 | val 0.16612
  Regression -> MSE: 0.000221, MAE: 0.010554, R²: 0.0160
  Directional -> Accuracy: 0.5246, MCC: 0.0476, F1: 0.5538

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.12724 | val 0.26285
  Epoch 020 - train 0.12596 | val 0.26697
  Regression -> MSE: 0.000362, MAE: 0.016053, R²: 0.0004
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.13680 | val 0.12992
  Epoch 020 - train 0.13721 | val 0.12955
  Regression -> MSE: 0.000108, MAE: 0.007960, R²: -0.0025
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.12402 | val 0.21984
  Epoch 020 - train 0.12653 | val 0.22886
  Regression -> MSE: 0.000162, MAE: 0.010184, R²: -0.0382
  Directional -> Accuracy: 0.3729, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.13466 | val 0.15178
  Epoch 020 - train 0.13505 | val 0.15162
  Regression -> MSE: 0.000283, MAE: 0.013571, R²: -0.0405
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.12336 | val 0.19136
  Epoch 020 - train 0.12285 | val 0.19110
  Regression -> MSE: 0.000152, MAE: 0.008735, R²: -0.0155
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.13606 | val 0.20866
  Epoch 020 - train 0.13330 | val 0.20588
  Regression -> MSE: 0.000232, MAE: 0.010885, R²: -0.0240
  Directional -> Accuracy: 0.5600, MCC: 0.0787, F1: 0.7027

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.13231 | val 0.16260
  Epoch 020 - train 0.13628 | val 0.16465
  Regression -> MSE: 0.000150, MAE: 0.008667, R²: -0.0432
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.12822 | val 0.15895
  Epoch 020 - train 0.12796 | val 0.15798
  Regression -> MSE: 0.000172, MAE: 0.010284, R²: -0.0424
  Directional -> Accuracy: 0.3485, MCC: -0.3150, F1: 0.2456

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.13904 | val 0.15957
  Epoch 020 - train 0.13465 | val 0.16517
  Regression -> MSE: 0.000086, MAE: 0.007097, R²: -0.0096
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.13260 | val 0.19761
  Epoch 020 - train 0.13710 | val 0.19570
  Regression -> MSE: 0.000213, MAE: 0.011065, R²: -0.0042
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.12011 | val 0.11035
  Epoch 020 - train 0.12241 | val 0.10876
  Regression -> MSE: 0.000095, MAE: 0.008100, R²: -0.0315
  Directional -> Accuracy: 0.5536, MCC: 0.1003, F1: 0.5902

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.13667 | val 0.10315
  Epoch 020 - train 0.13435 | val 0.10790
  Regression -> MSE: 0.000105, MAE: 0.008838, R²: -0.0195
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.14244 | val 0.12521
  Epoch 020 - train 0.14090 | val 0.12625
  Regression -> MSE: 0.000232, MAE: 0.012564, R²: -0.0020
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.12930 | val 0.15287
  Epoch 020 - train 0.12587 | val 0.15294
  Regression -> MSE: 0.000186, MAE: 0.008065, R²: -0.1161
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.13797 | val 0.11431
  Epoch 020 - train 0.13380 | val 0.11541
  Regression -> MSE: 0.000237, MAE: 0.011875, R²: -0.0030
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.13351 | val 0.21851
  Epoch 020 - train 0.13448 | val 0.22876
  Regression -> MSE: 0.000236, MAE: 0.010195, R²: -0.0230
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.14147 | val 0.16396
  Epoch 020 - train 0.13304 | val 0.16142
  Regression -> MSE: 0.000138, MAE: 0.008328, R²: -0.0225
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.13265 | val 0.16355
  Epoch 020 - train 0.13201 | val 0.16223
  Regression -> MSE: 0.000191, MAE: 0.010400, R²: -0.0131
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.11842 | val 0.15747
  Epoch 020 - train 0.11947 | val 0.15639
  Regression -> MSE: 0.000268, MAE: 0.010578, R²: -0.0241
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.12831 | val 0.12080
  Epoch 020 - train 0.12714 | val 0.13373
  Regression -> MSE: 0.000169, MAE: 0.010368, R²: -0.0111
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.12366 | val 0.13194
  Epoch 020 - train 0.12166 | val 0.13293
  Regression -> MSE: 0.000182, MAE: 0.010331, R²: -0.0090
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.13363 | val 0.12768
  Epoch 020 - train 0.13439 | val 0.12888
  Regression -> MSE: 0.000343, MAE: 0.011773, R²: -0.0006
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.13966 | val 0.08712
  Epoch 020 - train 0.13862 | val 0.08928
  Regression -> MSE: 0.000112, MAE: 0.008338, R²: -0.0699
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.13344 | val 0.19495
  Epoch 020 - train 0.12665 | val 0.20912
  Regression -> MSE: 0.000224, MAE: 0.011443, R²: -0.0228
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.13605 | val 0.21596
  Epoch 020 - train 0.12937 | val 0.21698
  Regression -> MSE: 0.000096, MAE: 0.007663, R²: -0.2366
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.12847 | val 0.10875
  Epoch 020 - train 0.12530 | val 0.10301
  Regression -> MSE: 0.000330, MAE: 0.014995, R²: -0.0733
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.13739 | val 0.08771
  Epoch 020 - train 0.13952 | val 0.08810
  Regression -> MSE: 0.000262, MAE: 0.011505, R²: -0.0736
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.13155 | val 0.16066
  Epoch 020 - train 0.12764 | val 0.15948
  Regression -> MSE: 0.000083, MAE: 0.007050, R²: -0.0267
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.14018 | val 0.15913
  Epoch 020 - train 0.14261 | val 0.20193
  Regression -> MSE: 0.000310, MAE: 0.014529, R²: -0.0112
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.12310 | val 0.14899
  Epoch 020 - train 0.12560 | val 0.14987
  Regression -> MSE: 0.000099, MAE: 0.007145, R²: -0.0130
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.13981 | val 0.15733
  Epoch 020 - train 0.13628 | val 0.16144
  Regression -> MSE: 0.000175, MAE: 0.010178, R²: -0.0202
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.12069 | val 0.15339
  Epoch 020 - train 0.12407 | val 0.15865
  Regression -> MSE: 0.000223, MAE: 0.011774, R²: -0.0020
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.13778 | val 0.17794
  Epoch 020 - train 0.13540 | val 0.18573
  Regression -> MSE: 0.000098, MAE: 0.008053, R²: -0.0670
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.13920 | val 0.20265
  Epoch 020 - train 0.13702 | val 0.20490
  Regression -> MSE: 0.000164, MAE: 0.010285, R²: -0.0033
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.12959 | val 0.16045
  Epoch 020 - train 0.12743 | val 0.16105
  Regression -> MSE: 0.000125, MAE: 0.009028, R²: -0.0806
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.13253 | val 0.19412

[I 2026-02-23 03:18:53,572] Trial 216 finished with value: -0.011466146311813776 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 32, 'learning_rate': 3.533573902470329e-06, 'weight_decay': 2.9573836886287042e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.19891936381878997, 'early_stopping_min_delta': 0.006593162685358241}. Best is trial 207 with value: -0.01137496405368131.

  Epoch 020 - train 0.13725 | val 0.19844
  Regression -> MSE: 0.000245, MAE: 0.012371, R²: -0.0337
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.11792 | val 0.16884
  Epoch 020 - train 0.11579 | val 0.16827
  Regression -> MSE: 0.000248, MAE: 0.012562, R²: -0.0020
  Directional -> Accuracy: 0.4156, MCC: -0.2206, F1: 0.5872

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.11662 | val 0.14989
  Epoch 020 - train 0.12170 | val 0.23418
  Regression -> MSE: 0.000687, MAE: 0.019367, R²: -0.0037
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.11850 | val 0.18746
  Epoch 020 - train 0.11609 | val 0.18611
  Regression -> MSE: 0.000313, MAE: 0.014425, R²: -0.0089
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.10753 | val 0.09778
  Epoch 020 - train 0.10614 | val 0.09616
  Regression -> MSE: 0.000350, MAE: 0.014570, R²: -0.0006
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.11231 | val 0.11329
  Epoch 020 - train 0.11778 | val 0.11951
  Regression -> MSE: 0.000207, MAE: 0.010082, R²: -0.0178
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.11169 | val 0.21855
  Epoch 020 - train 0.11199 | val 0.22353
  Regression -> MSE: 0.000591, MAE: 0.018799, R²: -0.0653
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.11771 | val 0.14923
  Epoch 020 - train 0.11755 | val 0.15011
  Regression -> MSE: 0.000246, MAE: 0.012162, R²: -0.0011
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.11062 | val 0.15558
  Epoch 020 - train 0.11123 | val 0.17492
  Regression -> MSE: 0.000631, MAE: 0.019928, R²: -0.0562
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.11133 | val 0.13745
  Epoch 020 - train 0.11093 | val 0.13668
  Regression -> MSE: 0.000399, MAE: 0.016038, R²: -0.0401
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.12510 | val 0.14895
  Epoch 020 - train 0.12338 | val 0.14813
  Regression -> MSE: 0.000242, MAE: 0.011843, R²: -0.0005
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.10940 | val 0.17726
  Epoch 020 - train 0.11029 | val 0.19171
  Regression -> MSE: 0.000314, MAE: 0.013639, R²: -0.0084
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.12416 | val 0.14716
  Epoch 020 - train 0.12608 | val 0.15659
  Regression -> MSE: 0.000680, MAE: 0.019539, R²: -0.0041
  Directional -> Accuracy: 0.4828, MCC: -0.0778, F1: 0.6429

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.10869 | val 0.11454
  Epoch 020 - train 0.10925 | val 0.12052
  Regression -> MSE: 0.000145, MAE: 0.009507, R²: -0.0479
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.10845 | val 0.15804
  Epoch 020 - train 0.10824 | val 0.15670
  Regression -> MSE: 0.000226, MAE: 0.010827, R²: -0.0053
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.11535 | val 0.23579
  Epoch 020 - train 0.11135 | val 0.25016
  Regression -> MSE: 0.000370, MAE: 0.015938, R²: -0.0227
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.12168 | val 0.11964
  Epoch 020 - train 0.12045 | val 0.11995
  Regression -> MSE: 0.000110, MAE: 0.008180, R²: -0.0164
  Directional -> Accuracy: 0.4571, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.11466 | val 0.19735
  Epoch 020 - train 0.11226 | val 0.20026
  Regression -> MSE: 0.000156, MAE: 0.009829, R²: -0.0035
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.13032 | val 0.17040
  Epoch 020 - train 0.13056 | val 0.17315
  Regression -> MSE: 0.000301, MAE: 0.014199, R²: -0.1061
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.12198 | val 0.18972
  Epoch 020 - train 0.12032 | val 0.19380
  Regression -> MSE: 0.000175, MAE: 0.009373, R²: -0.1689
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.12409 | val 0.17248
  Epoch 020 - train 0.12181 | val 0.17415
  Regression -> MSE: 0.000231, MAE: 0.010859, R²: -0.0198
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.11290 | val 0.14352
  Epoch 020 - train 0.11094 | val 0.14721
  Regression -> MSE: 0.000144, MAE: 0.008369, R²: -0.0034
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.11168 | val 0.13980
  Epoch 020 - train 0.10945 | val 0.14043
  Regression -> MSE: 0.000167, MAE: 0.010277, R²: -0.0130
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.12666 | val 0.13615
  Epoch 020 - train 0.12331 | val 0.13498
  Regression -> MSE: 0.000085, MAE: 0.007063, R²: -0.0022
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.11661 | val 0.14120
  Epoch 020 - train 0.11538 | val 0.14353
  Regression -> MSE: 0.000212, MAE: 0.011234, R²: -0.0028
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.10887 | val 0.10581
  Epoch 020 - train 0.10659 | val 0.10609
  Regression -> MSE: 0.000096, MAE: 0.008116, R²: -0.0414
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.12357 | val 0.09072
  Epoch 020 - train 0.12130 | val 0.09069
  Regression -> MSE: 0.000104, MAE: 0.008770, R²: -0.0057
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.13541 | val 0.12983
  Epoch 020 - train 0.13253 | val 0.17902
  Regression -> MSE: 0.000233, MAE: 0.012488, R²: -0.0063
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.11501 | val 0.14560
  Epoch 020 - train 0.11277 | val 0.14731
  Regression -> MSE: 0.000180, MAE: 0.007969, R²: -0.0825
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.12954 | val 0.10347
  Epoch 020 - train 0.12985 | val 0.12022
  Regression -> MSE: 0.000237, MAE: 0.011891, R²: -0.0034
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.11292 | val 0.18736
  Epoch 020 - train 0.11096 | val 0.18544
  Regression -> MSE: 0.000235, MAE: 0.010131, R²: -0.0179
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.12420 | val 0.13845
  Epoch 020 - train 0.12285 | val 0.14300
  Regression -> MSE: 0.000135, MAE: 0.008225, R²: -0.0030
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.12692 | val 0.14056
  Epoch 020 - train 0.12495 | val 0.13894
  Regression -> MSE: 0.000198, MAE: 0.010643, R²: -0.0533
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.10777 | val 0.13454
  Epoch 020 - train 0.10745 | val 0.13282
  Regression -> MSE: 0.000263, MAE: 0.010524, R²: -0.0049
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.11096 | val 0.09753
  Epoch 020 - train 0.10865 | val 0.09703
  Regression -> MSE: 0.000166, MAE: 0.010358, R²: 0.0022
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.11334 | val 0.11704
  Epoch 020 - train 0.11211 | val 0.12384
  Regression -> MSE: 0.000181, MAE: 0.010288, R²: -0.0070
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.10732 | val 0.10488
  Epoch 020 - train 0.10986 | val 0.10465
  Regression -> MSE: 0.000342, MAE: 0.011838, R²: 0.0029
  Directional -> Accuracy: 0.4627, MCC: 0.0930, F1: 0.1429

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.12070 | val 0.07710
  Epoch 020 - train 0.12682 | val 0.08254
  Regression -> MSE: 0.000124, MAE: 0.008436, R²: -0.1781
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.11882 | val 0.16622
  Epoch 020 - train 0.11827 | val 0.16408
  Regression -> MSE: 0.000223, MAE: 0.011444, R²: -0.0207
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.11427 | val 0.21370
  Epoch 020 - train 0.11442 | val 0.26148
  Regression -> MSE: 0.000089, MAE: 0.007385, R²: -0.1457
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.11518 | val 0.10365
  Epoch 020 - train 0.11669 | val 0.10426
  Regression -> MSE: 0.000346, MAE: 0.015537, R²: -0.1241
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.13490 | val 0.06982
  Epoch 020 - train 0.12807 | val 0.06845
  Regression -> MSE: 0.000248, MAE: 0.011527, R²: -0.0170
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.11686 | val 0.15201
  Epoch 020 - train 0.11777 | val 0.15084
  Regression -> MSE: 0.000081, MAE: 0.007114, R²: -0.0050
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.12089 | val 0.14427
  Epoch 020 - train 0.12346 | val 0.14541
  Regression -> MSE: 0.000307, MAE: 0.014477, R²: -0.0010
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.12076 | val 0.14192
  Epoch 020 - train 0.11696 | val 0.14814
  Regression -> MSE: 0.000104, MAE: 0.007112, R²: -0.0578
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.12594 | val 0.13572
  Epoch 020 - train 0.11880 | val 0.13788
  Regression -> MSE: 0.000172, MAE: 0.009602, R²: 0.0000
  Directional -> Accuracy: 0.6327, MCC: 0.1814, F1: 0.1000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.10659 | val 0.13590
  Epoch 020 - train 0.10649 | val 0.14162
  Regression -> MSE: 0.000224, MAE: 0.011792, R²: -0.0030
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.11659 | val 0.14240
  Epoch 020 - train 0.11577 | val 0.15311
  Regression -> MSE: 0.000093, MAE: 0.007684, R²: -0.0072
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.11949 | val 0.18356
  Epoch 020 - train 0.11788 | val 0.19088
  Regression -> MSE: 0.000164, MAE: 0.010276, R²: -0.0013
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.11292 | val 0.16542
  Epoch 020 - train 0.11210 | val 0.17925
  Regression -> MSE: 0.000122, MAE: 0.008988, R²: -0.0515
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.11930 | val 0.19212

[I 2026-02-23 03:21:38,615] Trial 217 finished with value: -0.011474312113898134 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 32, 'learning_rate': 2.328986187726609e-06, 'weight_decay': 3.483628191699658e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.1720452085908508, 'early_stopping_min_delta': 0.006153128018542182}. Best is trial 207 with value: -0.01137496405368131.

  Epoch 020 - train 0.12178 | val 0.20605
  Regression -> MSE: 0.000237, MAE: 0.012493, R²: -0.0004
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.06885 | val 0.09283
  Epoch 020 - train 0.06987 | val 0.09300
  Regression -> MSE: 0.000258, MAE: 0.012935, R²: -0.0406
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.06993 | val 0.06672
  Epoch 020 - train 0.06840 | val 0.06956
  Regression -> MSE: 0.000711, MAE: 0.019820, R²: -0.0393
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.07305 | val 0.10997
  Epoch 020 - train 0.07285 | val 0.10711
  Regression -> MSE: 0.000355, MAE: 0.014993, R²: -0.1430
  Directional -> Accuracy: 0.4894, MCC: 0.0705, F1: 0.1429

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.06155 | val 0.07710
  Epoch 020 - train 0.06083 | val 0.09796
  Regression -> MSE: 0.000352, MAE: 0.014607, R²: -0.0064
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.06923 | val 0.07168
  Epoch 020 - train 0.06946 | val 0.07558
  Regression -> MSE: 0.000206, MAE: 0.010083, R²: -0.0136
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.06841 | val 0.13272
  Epoch 020 - train 0.06690 | val 0.13771
  Regression -> MSE: 0.000586, MAE: 0.018693, R²: -0.0561
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.07194 | val 0.09833
  Epoch 020 - train 0.07282 | val 0.09568
  Regression -> MSE: 0.000248, MAE: 0.012236, R²: -0.0091
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.06720 | val 0.10732
  Epoch 020 - train 0.06861 | val 0.13215
  Regression -> MSE: 0.000662, MAE: 0.020419, R²: -0.1079
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.07379 | val 0.08762
  Epoch 020 - train 0.07457 | val 0.10295
  Regression -> MSE: 0.000393, MAE: 0.015946, R²: -0.0255
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.07160 | val 0.09147
  Epoch 020 - train 0.06907 | val 0.09336
  Regression -> MSE: 0.000241, MAE: 0.011932, R²: -0.0001
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.06691 | val 0.09733
  Epoch 020 - train 0.06307 | val 0.09817
  Regression -> MSE: 0.000317, MAE: 0.013585, R²: -0.0208
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.07312 | val 0.08066
  Epoch 020 - train 0.07195 | val 0.08136
  Regression -> MSE: 0.000683, MAE: 0.019686, R²: -0.0083
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.06962 | val 0.06889
  Epoch 020 - train 0.06832 | val 0.06953
  Regression -> MSE: 0.000138, MAE: 0.009132, R²: -0.0011
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.06701 | val 0.09253
  Epoch 020 - train 0.06682 | val 0.09049
  Regression -> MSE: 0.000225, MAE: 0.010747, R²: 0.0006
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.07220 | val 0.13834
  Epoch 020 - train 0.07267 | val 0.14097
  Regression -> MSE: 0.000368, MAE: 0.015953, R²: -0.0164
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.07443 | val 0.07797
  Epoch 020 - train 0.07295 | val 0.07695
  Regression -> MSE: 0.000111, MAE: 0.008248, R²: -0.0289
  Directional -> Accuracy: 0.4571, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.06949 | val 0.11657
  Epoch 020 - train 0.06658 | val 0.12347
  Regression -> MSE: 0.000162, MAE: 0.010192, R²: -0.0411
  Directional -> Accuracy: 0.3729, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.07349 | val 0.07242
  Epoch 020 - train 0.06986 | val 0.07268
  Regression -> MSE: 0.000291, MAE: 0.013865, R²: -0.0692
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.06662 | val 0.09235
  Epoch 020 - train 0.06610 | val 0.09054
  Regression -> MSE: 0.000152, MAE: 0.008743, R²: -0.0184
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.07378 | val 0.10348
  Epoch 020 - train 0.07208 | val 0.10833
  Regression -> MSE: 0.000236, MAE: 0.010994, R²: -0.0440
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.07036 | val 0.08665
  Epoch 020 - train 0.07062 | val 0.08764
  Regression -> MSE: 0.000150, MAE: 0.008705, R²: -0.0489
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.06660 | val 0.08380
  Epoch 020 - train 0.06431 | val 0.08464
  Regression -> MSE: 0.000168, MAE: 0.010276, R²: -0.0185
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.07452 | val 0.08393
  Epoch 020 - train 0.07233 | val 0.08762
  Regression -> MSE: 0.000086, MAE: 0.007095, R²: -0.0110
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.07175 | val 0.08492
  Epoch 020 - train 0.07021 | val 0.08486
  Regression -> MSE: 0.000212, MAE: 0.011120, R²: 0.0007
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.06785 | val 0.06517
  Epoch 020 - train 0.06807 | val 0.06299
  Regression -> MSE: 0.000093, MAE: 0.008113, R²: -0.0128
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.07125 | val 0.05831
  Epoch 020 - train 0.07134 | val 0.05701
  Regression -> MSE: 0.000111, MAE: 0.009063, R²: -0.0762
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.07589 | val 0.06901
  Epoch 020 - train 0.07580 | val 0.07052
  Regression -> MSE: 0.000244, MAE: 0.012947, R²: -0.0556
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.06802 | val 0.08359
  Epoch 020 - train 0.06838 | val 0.08431
  Regression -> MSE: 0.000187, MAE: 0.008114, R²: -0.1250
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.07433 | val 0.06636
  Epoch 020 - train 0.07432 | val 0.06758
  Regression -> MSE: 0.000241, MAE: 0.012081, R²: -0.0192
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.07738 | val 0.10872
  Epoch 020 - train 0.07391 | val 0.11222
  Regression -> MSE: 0.000231, MAE: 0.009864, R²: -0.0012
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.07365 | val 0.08328
  Epoch 020 - train 0.07490 | val 0.08202
  Regression -> MSE: 0.000136, MAE: 0.008255, R²: -0.0096
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.07217 | val 0.08984
  Epoch 020 - train 0.06769 | val 0.09032
  Regression -> MSE: 0.000193, MAE: 0.010425, R²: -0.0241
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.06300 | val 0.08498
  Epoch 020 - train 0.06131 | val 0.08348
  Regression -> MSE: 0.000267, MAE: 0.010562, R²: -0.0204
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.06793 | val 0.06002
  Epoch 020 - train 0.06838 | val 0.05980
  Regression -> MSE: 0.000168, MAE: 0.010365, R²: -0.0054
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.06927 | val 0.07345
  Epoch 020 - train 0.06890 | val 0.07597
  Regression -> MSE: 0.000180, MAE: 0.010299, R²: -0.0016
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.07135 | val 0.06826
  Epoch 020 - train 0.06735 | val 0.06834
  Regression -> MSE: 0.000345, MAE: 0.011701, R²: -0.0057
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.07665 | val 0.04817
  Epoch 020 - train 0.07546 | val 0.05000
  Regression -> MSE: 0.000125, MAE: 0.008463, R²: -0.1937
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.07737 | val 0.09503
  Epoch 020 - train 0.07278 | val 0.09826
  Regression -> MSE: 0.000221, MAE: 0.011380, R²: -0.0117
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.07099 | val 0.11894
  Epoch 020 - train 0.07055 | val 0.12269
  Regression -> MSE: 0.000084, MAE: 0.007128, R²: -0.0761
  Directional -> Accuracy: 0.5957, MCC: 0.0392, F1: 0.7246

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.07024 | val 0.05838
  Epoch 020 - train 0.06734 | val 0.05682
  Regression -> MSE: 0.000321, MAE: 0.014579, R²: -0.0446
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.07452 | val 0.04661
  Epoch 020 - train 0.07308 | val 0.04685
  Regression -> MSE: 0.000255, MAE: 0.011463, R²: -0.0459
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.06911 | val 0.08903
  Epoch 020 - train 0.06890 | val 0.08931
  Regression -> MSE: 0.000081, MAE: 0.007101, R²: -0.0041
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.07124 | val 0.08647
  Epoch 020 - train 0.07181 | val 0.09361
  Regression -> MSE: 0.000311, MAE: 0.014533, R²: -0.0131
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.06613 | val 0.08333
  Epoch 020 - train 0.06571 | val 0.08276
  Regression -> MSE: 0.000102, MAE: 0.007118, R²: -0.0361
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.07629 | val 0.08347
  Epoch 020 - train 0.07430 | val 0.08579
  Regression -> MSE: 0.000174, MAE: 0.010059, R²: -0.0124
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.06635 | val 0.07798
  Epoch 020 - train 0.06546 | val 0.07815
  Regression -> MSE: 0.000224, MAE: 0.011782, R²: -0.0041
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.06934 | val 0.08135
  Epoch 020 - train 0.06891 | val 0.09043
  Regression -> MSE: 0.000092, MAE: 0.007627, R²: 0.0012
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.07275 | val 0.10814
  Epoch 020 - train 0.07292 | val 0.10974
  Regression -> MSE: 0.000165, MAE: 0.010277, R²: -0.0057
  Directional -> Accuracy: 0.4815, MCC: 0.0000, F1: 0.0000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.07096 | val 0.08911
  Epoch 020 - train 0.06854 | val 0.09153
  Regression -> MSE: 0.000123, MAE: 0.009002, R²: -0.0595
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.07422 | val 0.10257

[I 2026-02-23 03:24:25,730] Trial 218 finished with value: -0.011493069996309875 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.1, 'batch_size': 32, 'learning_rate': 5.70930912016322e-06, 'weight_decay': 1.47707771875434e-07, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.1006551130689171, 'early_stopping_min_delta': 0.005539388931327744}. Best is trial 207 with value: -0.01137496405368131.

  Epoch 020 - train 0.07350 | val 0.10171
  Regression -> MSE: 0.000243, MAE: 0.012348, R²: -0.0260
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.20730 | val 0.34690
  Epoch 020 - train 0.20084 | val 0.34508
  Regression -> MSE: 0.000253, MAE: 0.012750, R²: -0.0200
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.18144 | val 0.17621
  Epoch 020 - train 0.17992 | val 0.18173
  Regression -> MSE: 0.000703, MAE: 0.019674, R²: -0.0263
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.21479 | val 0.31085
  Epoch 020 - train 0.20891 | val 0.30712
  Regression -> MSE: 0.000311, MAE: 0.014347, R²: -0.0027
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.15720 | val 0.16250
  Epoch 020 - train 0.15052 | val 0.16716
  Regression -> MSE: 0.000354, MAE: 0.014664, R²: -0.0149
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.19923 | val 0.21847
  Epoch 020 - train 0.19485 | val 0.22957
  Regression -> MSE: 0.000208, MAE: 0.010478, R²: -0.0193
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.18663 | val 0.37228
  Epoch 020 - train 0.18387 | val 0.36994
  Regression -> MSE: 0.000604, MAE: 0.019078, R²: -0.0874
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.19394 | val 0.27233
  Epoch 020 - train 0.19314 | val 0.27081
  Regression -> MSE: 0.000250, MAE: 0.011951, R²: -0.0188
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.19199 | val 0.23818
  Epoch 020 - train 0.19218 | val 0.29040
  Regression -> MSE: 0.000609, MAE: 0.019450, R²: -0.0194
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.21673 | val 0.22045
  Epoch 020 - train 0.20431 | val 0.26590
  Regression -> MSE: 0.000412, MAE: 0.016281, R²: -0.0751
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.18430 | val 0.25270
  Epoch 020 - train 0.17925 | val 0.25519
  Regression -> MSE: 0.000242, MAE: 0.011719, R²: -0.0031
  Directional -> Accuracy: 0.4714, MCC: -0.0254, F1: 0.4932

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.17782 | val 0.26526
  Epoch 020 - train 0.17405 | val 0.25972
  Regression -> MSE: 0.000341, MAE: 0.013697, R²: -0.0977
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.20190 | val 0.24318
  Epoch 020 - train 0.19415 | val 0.25746
  Regression -> MSE: 0.000687, MAE: 0.019559, R²: -0.0144
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.19656 | val 0.20731
  Epoch 020 - train 0.18856 | val 0.27423
  Regression -> MSE: 0.000143, MAE: 0.009427, R²: -0.0338
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.17320 | val 0.26291
  Epoch 020 - train 0.17500 | val 0.26628
  Regression -> MSE: 0.000228, MAE: 0.010761, R²: -0.0121
  Directional -> Accuracy: 0.4918, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.17902 | val 0.39374
  Epoch 020 - train 0.18275 | val 0.39638
  Regression -> MSE: 0.000363, MAE: 0.016031, R²: -0.0020
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.19714 | val 0.20233
  Epoch 020 - train 0.20251 | val 0.20778
  Regression -> MSE: 0.000109, MAE: 0.007943, R²: -0.0071
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.17900 | val 0.32043
  Epoch 020 - train 0.18546 | val 0.32825
  Regression -> MSE: 0.000156, MAE: 0.009552, R²: -0.0035
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.19106 | val 0.20716
  Epoch 020 - train 0.18773 | val 0.21063
  Regression -> MSE: 0.000286, MAE: 0.013635, R²: -0.0496
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.20599 | val 0.28609
  Epoch 020 - train 0.19959 | val 0.28269
  Regression -> MSE: 0.000150, MAE: 0.008805, R²: -0.0052
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.19855 | val 0.27660
  Epoch 020 - train 0.19463 | val 0.27444
  Regression -> MSE: 0.000248, MAE: 0.011250, R²: -0.0966
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.20345 | val 0.25287
  Epoch 020 - train 0.19616 | val 0.28177
  Regression -> MSE: 0.000144, MAE: 0.008365, R²: -0.0046
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.18308 | val 0.22800
  Epoch 020 - train 0.18013 | val 0.22785
  Regression -> MSE: 0.000184, MAE: 0.011272, R²: -0.1116
  Directional -> Accuracy: 0.4697, MCC: -0.0786, F1: 0.5977

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.19529 | val 0.23042
  Epoch 020 - train 0.19627 | val 0.23332
  Regression -> MSE: 0.000087, MAE: 0.007167, R²: -0.0250
  Directional -> Accuracy: 0.6034, MCC: 0.1753, F1: 0.7356

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.19080 | val 0.23354
  Epoch 020 - train 0.18441 | val 0.23589
  Regression -> MSE: 0.000215, MAE: 0.011049, R²: -0.0151
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.17612 | val 0.16918
  Epoch 020 - train 0.17251 | val 0.16583
  Regression -> MSE: 0.000093, MAE: 0.008097, R²: -0.0144
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.18904 | val 0.14822
  Epoch 020 - train 0.18530 | val 0.16336
  Regression -> MSE: 0.000105, MAE: 0.008864, R²: -0.0211
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.20120 | val 0.18220
  Epoch 020 - train 0.19818 | val 0.18213
  Regression -> MSE: 0.000234, MAE: 0.012647, R²: -0.0110
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.18605 | val 0.22640
  Epoch 020 - train 0.18734 | val 0.22717
  Regression -> MSE: 0.000188, MAE: 0.008115, R²: -0.1285
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.19991 | val 0.15757
  Epoch 020 - train 0.19819 | val 0.15929
  Regression -> MSE: 0.000237, MAE: 0.011863, R²: -0.0006
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.18637 | val 0.30968
  Epoch 020 - train 0.17682 | val 0.31795
  Regression -> MSE: 0.000232, MAE: 0.009939, R²: -0.0048
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.20163 | val 0.24663
  Epoch 020 - train 0.20401 | val 0.25141
  Regression -> MSE: 0.000141, MAE: 0.008492, R²: -0.0443
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.20092 | val 0.24500
  Epoch 020 - train 0.19382 | val 0.25228
  Regression -> MSE: 0.000198, MAE: 0.010628, R²: -0.0494
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.17269 | val 0.22090
  Epoch 020 - train 0.16923 | val 0.21830
  Regression -> MSE: 0.000263, MAE: 0.010509, R²: -0.0042
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.19071 | val 0.15840
  Epoch 020 - train 0.18688 | val 0.16183
  Regression -> MSE: 0.000167, MAE: 0.010367, R²: 0.0010
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.18882 | val 0.22035
  Epoch 020 - train 0.19589 | val 0.23482
  Regression -> MSE: 0.000194, MAE: 0.010860, R²: -0.0762
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.19632 | val 0.18264
  Epoch 020 - train 0.18185 | val 0.17854
  Regression -> MSE: 0.000346, MAE: 0.012138, R²: -0.0097
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.20245 | val 0.12426
  Epoch 020 - train 0.20494 | val 0.12804
  Regression -> MSE: 0.000130, MAE: 0.008573, R²: -0.2401
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.19599 | val 0.26890
  Epoch 020 - train 0.19910 | val 0.27455
  Regression -> MSE: 0.000219, MAE: 0.011283, R²: -0.0005
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.19253 | val 0.34191
  Epoch 020 - train 0.18268 | val 0.36204
  Regression -> MSE: 0.000083, MAE: 0.007111, R²: -0.0712
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.21526 | val 0.17882
  Epoch 020 - train 0.20561 | val 0.20815
  Regression -> MSE: 0.000354, MAE: 0.015791, R²: -0.1521
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.20327 | val 0.10896
  Epoch 020 - train 0.20275 | val 0.10860
  Regression -> MSE: 0.000246, MAE: 0.011540, R²: -0.0110
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.0000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.18214 | val 0.23003
  Epoch 020 - train 0.18193 | val 0.23128
  Regression -> MSE: 0.000083, MAE: 0.007048, R²: -0.0264
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.19307 | val 0.23495
  Epoch 020 - train 0.19720 | val 0.22457
  Regression -> MSE: 0.000295, MAE: 0.014321, R²: 0.0370
  Directional -> Accuracy: 0.5745, MCC: 0.1726, F1: 0.6774

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.19543 | val 0.21036
  Epoch 020 - train 0.19464 | val 0.21676
  Regression -> MSE: 0.000099, MAE: 0.007211, R²: -0.0046
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.20371 | val 0.23006
  Epoch 020 - train 0.19510 | val 0.22922
  Regression -> MSE: 0.000175, MAE: 0.010109, R²: -0.0163
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.17815 | val 0.23277
  Epoch 020 - train 0.17830 | val 0.23796
  Regression -> MSE: 0.000223, MAE: 0.011755, R²: 0.0006
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.20335 | val 0.24155
  Epoch 020 - train 0.20123 | val 0.25614
  Regression -> MSE: 0.000092, MAE: 0.007637, R²: -0.0011
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.19299 | val 0.29677
  Epoch 020 - train 0.19731 | val 0.29910
  Regression -> MSE: 0.000164, MAE: 0.010257, R²: -0.0022
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.18927 | val 0.23221
  Epoch 020 - train 0.18738 | val 0.23363
  Regression -> MSE: 0.000127, MAE: 0.009047, R²: -0.0916
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.19410 | val 0.27066

[I 2026-02-23 03:27:09,410] Trial 219 finished with value: -0.01150981413274387 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 32, 'learning_rate': 4.001264776928017e-06, 'weight_decay': 5.186644895465431e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.30677856919384305, 'early_stopping_min_delta': 0.0058269647279249204}. Best is trial 207 with value: -0.01137496405368131.

  Epoch 020 - train 0.18620 | val 0.27154
  Regression -> MSE: 0.000238, MAE: 0.012382, R²: -0.0041
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.09467 | val 0.12428
  Epoch 020 - train 0.09757 | val 0.12404
  Regression -> MSE: 0.000247, MAE: 0.012530, R²: 0.0016
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.09375 | val 0.11632
  Epoch 020 - train 0.09692 | val 0.12219
  Regression -> MSE: 0.000692, MAE: 0.019500, R²: -0.0110
  Directional -> Accuracy: 0.6087, MCC: 0.2385, F1: 0.6087

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.09855 | val 0.14708
  Epoch 020 - train 0.09996 | val 0.14676
  Regression -> MSE: 0.000309, MAE: 0.014424, R²: 0.0032
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.08276 | val 0.08370
  Epoch 020 - train 0.08414 | val 0.08237
  Regression -> MSE: 0.000348, MAE: 0.014527, R²: 0.0047
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.10439 | val 0.09426
  Epoch 020 - train 0.10234 | val 0.09494
  Regression -> MSE: 0.000207, MAE: 0.010140, R²: -0.0154
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.08331 | val 0.16965
  Epoch 020 - train 0.08755 | val 0.17058
  Regression -> MSE: 0.000591, MAE: 0.018799, R²: -0.0642
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.09574 | val 0.12114
  Epoch 020 - train 0.09535 | val 0.12106
  Regression -> MSE: 0.000248, MAE: 0.011957, R²: -0.0087
  Directional -> Accuracy: 0.5942, MCC: 0.0880, F1: 0.3000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.10166 | val 0.11295
  Epoch 020 - train 0.09767 | val 0.11637
  Regression -> MSE: 0.000605, MAE: 0.019342, R²: -0.0127
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.09293 | val 0.11808
  Epoch 020 - train 0.09170 | val 0.11755
  Regression -> MSE: 0.000384, MAE: 0.016127, R²: -0.0002
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.09665 | val 0.11815
  Epoch 020 - train 0.09678 | val 0.11786
  Regression -> MSE: 0.000246, MAE: 0.011679, R²: -0.0189
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.08816 | val 0.13095
  Epoch 020 - train 0.09055 | val 0.13135
  Regression -> MSE: 0.000330, MAE: 0.013657, R²: -0.0599
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.09828 | val 0.10891
  Epoch 020 - train 0.09557 | val 0.10955
  Regression -> MSE: 0.000676, MAE: 0.019590, R²: 0.0022
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.09778 | val 0.12586
  Epoch 020 - train 0.09539 | val 0.12859
  Regression -> MSE: 0.000140, MAE: 0.009001, R²: -0.0145
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.08773 | val 0.12513
  Epoch 020 - train 0.08812 | val 0.12567
  Regression -> MSE: 0.000228, MAE: 0.010803, R²: -0.0135
  Directional -> Accuracy: 0.4426, MCC: -0.1699, F1: 0.5854

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.08931 | val 0.19796
  Epoch 020 - train 0.08772 | val 0.20000
  Regression -> MSE: 0.000365, MAE: 0.015957, R²: -0.0074
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.09894 | val 0.09683
  Epoch 020 - train 0.09844 | val 0.09742
  Regression -> MSE: 0.000110, MAE: 0.008216, R²: -0.0242
  Directional -> Accuracy: 0.4571, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.10157 | val 0.15547
  Epoch 020 - train 0.09899 | val 0.15632
  Regression -> MSE: 0.000156, MAE: 0.009480, R²: 0.0004
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.09963 | val 0.10026
  Epoch 020 - train 0.10050 | val 0.09998
  Regression -> MSE: 0.000273, MAE: 0.012929, R²: -0.0038
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.08571 | val 0.11873
  Epoch 020 - train 0.08521 | val 0.11953
  Regression -> MSE: 0.000159, MAE: 0.008829, R²: -0.0605
  Directional -> Accuracy: 0.5077, MCC: 0.0077, F1: 0.5556

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.10397 | val 0.13843
  Epoch 020 - train 0.10227 | val 0.13726
  Regression -> MSE: 0.000255, MAE: 0.011339, R²: -0.1251
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.09419 | val 0.11555
  Epoch 020 - train 0.09611 | val 0.11615
  Regression -> MSE: 0.000143, MAE: 0.008296, R²: 0.0038
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.09193 | val 0.11436
  Epoch 020 - train 0.09274 | val 0.11456
  Regression -> MSE: 0.000180, MAE: 0.010295, R²: -0.0896
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.09835 | val 0.10786
  Epoch 020 - train 0.09768 | val 0.10770
  Regression -> MSE: 0.000093, MAE: 0.007462, R²: -0.0870
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.09532 | val 0.13344
  Epoch 020 - train 0.09224 | val 0.12698
  Regression -> MSE: 0.000217, MAE: 0.011550, R²: -0.0250
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.09394 | val 0.09052
  Epoch 020 - train 0.09151 | val 0.09092
  Regression -> MSE: 0.000093, MAE: 0.008044, R²: -0.0147
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.10012 | val 0.07372
  Epoch 020 - train 0.10072 | val 0.07368
  Regression -> MSE: 0.000103, MAE: 0.008764, R²: -0.0009
  Directional -> Accuracy: 0.4783, MCC: 0.1150, F1: 0.6129

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.10257 | val 0.10989
  Epoch 020 - train 0.10025 | val 0.11083
  Regression -> MSE: 0.000232, MAE: 0.012499, R²: -0.0026
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.09683 | val 0.11156
  Epoch 020 - train 0.09508 | val 0.11165
  Regression -> MSE: 0.000175, MAE: 0.007822, R²: -0.0506
  Directional -> Accuracy: 0.5263, MCC: 0.0688, F1: 0.5263

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.09849 | val 0.08380
  Epoch 020 - train 0.09829 | val 0.08289
  Regression -> MSE: 0.000238, MAE: 0.011917, R²: -0.0082
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.09161 | val 0.14667
  Epoch 020 - train 0.08990 | val 0.14725
  Regression -> MSE: 0.000230, MAE: 0.009924, R²: 0.0029
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.09559 | val 0.12005
  Epoch 020 - train 0.09637 | val 0.12034
  Regression -> MSE: 0.000136, MAE: 0.008332, R²: -0.0095
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.09910 | val 0.11934
  Epoch 020 - train 0.10008 | val 0.11992
  Regression -> MSE: 0.000191, MAE: 0.010383, R²: -0.0141
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.08656 | val 0.11194
  Epoch 020 - train 0.08383 | val 0.11156
  Regression -> MSE: 0.000284, MAE: 0.011129, R²: -0.0846
  Directional -> Accuracy: 0.4384, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.09245 | val 0.07894
  Epoch 020 - train 0.08612 | val 0.07876
  Regression -> MSE: 0.000171, MAE: 0.010391, R²: -0.0288
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.09101 | val 0.12206
  Epoch 020 - train 0.09144 | val 0.12271
  Regression -> MSE: 0.000199, MAE: 0.010965, R²: -0.1073
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.09670 | val 0.09148
  Epoch 020 - train 0.09576 | val 0.09119
  Regression -> MSE: 0.000362, MAE: 0.013129, R²: -0.0573
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.12011 | val 0.10917
  Epoch 020 - train 0.11515 | val 0.12700
  Regression -> MSE: 0.000106, MAE: 0.008465, R²: -0.0107
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.09514 | val 0.13149
  Epoch 020 - train 0.09602 | val 0.13298
  Regression -> MSE: 0.000218, MAE: 0.011228, R²: 0.0019
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.09114 | val 0.19229
  Epoch 020 - train 0.09092 | val 0.19639
  Regression -> MSE: 0.000079, MAE: 0.006947, R²: -0.0232
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.09078 | val 0.07838
  Epoch 020 - train 0.09445 | val 0.08143
  Regression -> MSE: 0.000315, MAE: 0.014212, R²: -0.0227
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.10233 | val 0.06142
  Epoch 020 - train 0.10001 | val 0.06304
  Regression -> MSE: 0.000251, MAE: 0.011483, R²: -0.0284
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.09001 | val 0.11979
  Epoch 020 - train 0.09051 | val 0.11892
  Regression -> MSE: 0.000080, MAE: 0.007053, R²: 0.0062
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.09578 | val 0.11434
  Epoch 020 - train 0.09198 | val 0.11527
  Regression -> MSE: 0.000309, MAE: 0.014520, R²: -0.0073
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.09805 | val 0.10190
  Epoch 020 - train 0.09785 | val 0.10108
  Regression -> MSE: 0.000100, MAE: 0.007179, R²: -0.0134
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.10377 | val 0.13035
  Epoch 020 - train 0.10228 | val 0.14149
  Regression -> MSE: 0.000173, MAE: 0.009579, R²: -0.0065
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.09170 | val 0.10437
  Epoch 020 - train 0.08968 | val 0.10415
  Regression -> MSE: 0.000224, MAE: 0.011799, R²: -0.0067
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.09884 | val 0.10887
  Epoch 020 - train 0.09662 | val 0.10837
  Regression -> MSE: 0.000093, MAE: 0.007666, R²: -0.0109
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.09789 | val 0.14957
  Epoch 020 - train 0.09983 | val 0.14975
  Regression -> MSE: 0.000163, MAE: 0.010224, R²: 0.0018
  Directional -> Accuracy: 0.5000, MCC: -0.1324, F1: 0.6667

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.09343 | val 0.12523
  Epoch 020 - train 0.08823 | val 0.12712
  Regression -> MSE: 0.000121, MAE: 0.009015, R²: -0.0455
  Directional -> Accuracy: 0.4286, MCC: -0.2466, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.09989 | val 0.14875

[I 2026-02-23 03:28:56,097] Trial 220 finished with value: -0.011428921152724892 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 32, 'learning_rate': 2.8214946055053566e-06, 'weight_decay': 7.096069747534942e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.13547540339240127, 'early_stopping_min_delta': 0.0049892352148134325}. Best is trial 207 with value: -0.01137496405368131.

  Epoch 020 - train 0.09790 | val 0.14829
  Regression -> MSE: 0.000245, MAE: 0.012348, R²: -0.0351
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.10039 | val 0.12548
  Epoch 020 - train 0.09546 | val 0.12623
  Regression -> MSE: 0.000259, MAE: 0.013001, R²: -0.0458
  Directional -> Accuracy: 0.4156, MCC: -0.1437, F1: 0.5361

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.10077 | val 0.14328
  Epoch 020 - train 0.09684 | val 0.14942
  Regression -> MSE: 0.000698, MAE: 0.019562, R²: -0.0203
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.10085 | val 0.16083
  Epoch 020 - train 0.10030 | val 0.16154
  Regression -> MSE: 0.000312, MAE: 0.014427, R²: -0.0063
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.08815 | val 0.13490
  Epoch 020 - train 0.08455 | val 0.13709
  Regression -> MSE: 0.000398, MAE: 0.015486, R²: -0.1400
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.11064 | val 0.10867
  Epoch 020 - train 0.10846 | val 0.10917
  Regression -> MSE: 0.000206, MAE: 0.010002, R²: -0.0105
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.08989 | val 0.19083
  Epoch 020 - train 0.09389 | val 0.19610
  Regression -> MSE: 0.000578, MAE: 0.018531, R²: -0.0421
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.10611 | val 0.12824
  Epoch 020 - train 0.10449 | val 0.12813
  Regression -> MSE: 0.000252, MAE: 0.011980, R²: -0.0280
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.09971 | val 0.12839
  Epoch 020 - train 0.10008 | val 0.13142
  Regression -> MSE: 0.000623, MAE: 0.019688, R²: -0.0421
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.09569 | val 0.11629
  Epoch 020 - train 0.09337 | val 0.11671
  Regression -> MSE: 0.000398, MAE: 0.015988, R²: -0.0370
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.10537 | val 0.12617
  Epoch 020 - train 0.10281 | val 0.12547
  Regression -> MSE: 0.000242, MAE: 0.011811, R²: -0.0034
  Directional -> Accuracy: 0.3857, MCC: -0.1925, F1: 0.5376

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.09142 | val 0.15426
  Epoch 020 - train 0.08895 | val 0.15358
  Regression -> MSE: 0.000309, MAE: 0.013607, R²: 0.0066
  Directional -> Accuracy: 0.6000, MCC: 0.2737, F1: 0.2308

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.10458 | val 0.12611
  Epoch 020 - train 0.10584 | val 0.12526
  Regression -> MSE: 0.000688, MAE: 0.019695, R²: -0.0158
  Directional -> Accuracy: 0.2931, MCC: -0.4629, F1: 0.4225

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.10040 | val 0.10133
  Epoch 020 - train 0.09887 | val 0.10336
  Regression -> MSE: 0.000144, MAE: 0.009455, R²: -0.0392
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.09032 | val 0.13157
  Epoch 020 - train 0.09215 | val 0.13114
  Regression -> MSE: 0.000227, MAE: 0.010761, R²: -0.0113
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.09933 | val 0.19750
  Epoch 020 - train 0.09601 | val 0.19751
  Regression -> MSE: 0.000381, MAE: 0.015928, R²: -0.0515
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.10962 | val 0.11858
  Epoch 020 - train 0.10900 | val 0.11691
  Regression -> MSE: 0.000111, MAE: 0.008112, R²: -0.0292
  Directional -> Accuracy: 0.4571, MCC: -0.0993, F1: 0.5128

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.09771 | val 0.15872
  Epoch 020 - train 0.09482 | val 0.16003
  Regression -> MSE: 0.000159, MAE: 0.009880, R²: -0.0207
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.10168 | val 0.10125
  Epoch 020 - train 0.10106 | val 0.10036
  Regression -> MSE: 0.000274, MAE: 0.013143, R²: -0.0066
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.09211 | val 0.13150
  Epoch 020 - train 0.09309 | val 0.13083
  Regression -> MSE: 0.000153, MAE: 0.008824, R²: -0.0242
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.10899 | val 0.16814
  Epoch 020 - train 0.10913 | val 0.16568
  Regression -> MSE: 0.000234, MAE: 0.011370, R²: -0.0326
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.10640 | val 0.16130
  Epoch 020 - train 0.10375 | val 0.15995
  Regression -> MSE: 0.000144, MAE: 0.008348, R²: -0.0031
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.09329 | val 0.11964
  Epoch 020 - train 0.09370 | val 0.12029
  Regression -> MSE: 0.000165, MAE: 0.010284, R²: 0.0020
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.10513 | val 0.11769
  Epoch 020 - train 0.10296 | val 0.11744
  Regression -> MSE: 0.000087, MAE: 0.007150, R²: -0.0189
  Directional -> Accuracy: 0.5517, MCC: 0.0514, F1: 0.6486

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.10466 | val 0.12174
  Epoch 020 - train 0.10566 | val 0.12221
  Regression -> MSE: 0.000213, MAE: 0.011290, R²: -0.0049
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.09196 | val 0.08738
  Epoch 020 - train 0.09486 | val 0.08709
  Regression -> MSE: 0.000097, MAE: 0.008176, R²: -0.0484
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.10098 | val 0.07837
  Epoch 020 - train 0.10511 | val 0.08008
  Regression -> MSE: 0.000103, MAE: 0.008716, R²: 0.0014
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.10456 | val 0.12658
  Epoch 020 - train 0.10358 | val 0.13115
  Regression -> MSE: 0.000232, MAE: 0.012526, R²: -0.0039
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.09138 | val 0.11124
  Epoch 020 - train 0.09564 | val 0.11120
  Regression -> MSE: 0.000212, MAE: 0.008850, R²: -0.2739
  Directional -> Accuracy: 0.5088, MCC: 0.2428, F1: 0.2222

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.10529 | val 0.08574
  Epoch 020 - train 0.10392 | val 0.08609
  Regression -> MSE: 0.000237, MAE: 0.011947, R²: -0.0033
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.10172 | val 0.15170
  Epoch 020 - train 0.10014 | val 0.15140
  Regression -> MSE: 0.000231, MAE: 0.009899, R²: -0.0027
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.10610 | val 0.14414
  Epoch 020 - train 0.10012 | val 0.15461
  Regression -> MSE: 0.000141, MAE: 0.008488, R²: -0.0468
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.10283 | val 0.13148
  Epoch 020 - train 0.10379 | val 0.13145
  Regression -> MSE: 0.000188, MAE: 0.010465, R²: 0.0008
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.08732 | val 0.13715
  Epoch 020 - train 0.08606 | val 0.13505
  Regression -> MSE: 0.000275, MAE: 0.010765, R²: -0.0504
  Directional -> Accuracy: 0.4247, MCC: -0.1768, F1: 0.5000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.09598 | val 0.09320
  Epoch 020 - train 0.09501 | val 0.10122
  Regression -> MSE: 0.000170, MAE: 0.010380, R²: -0.0209
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.09251 | val 0.09874
  Epoch 020 - train 0.09265 | val 0.09875
  Regression -> MSE: 0.000179, MAE: 0.010223, R²: 0.0058
  Directional -> Accuracy: 0.5000, MCC: 0.0424, F1: 0.6207

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.09578 | val 0.09823
  Epoch 020 - train 0.09755 | val 0.09763
  Regression -> MSE: 0.000348, MAE: 0.012046, R²: -0.0169
  Directional -> Accuracy: 0.3731, MCC: -0.2357, F1: 0.0870

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.11430 | val 0.07399
  Epoch 020 - train 0.11102 | val 0.07858
  Regression -> MSE: 0.000111, MAE: 0.008371, R²: -0.0604
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.10605 | val 0.13427
  Epoch 020 - train 0.10875 | val 0.13419
  Regression -> MSE: 0.000219, MAE: 0.011279, R²: -0.0032
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.10040 | val 0.16984
  Epoch 020 - train 0.10073 | val 0.16979
  Regression -> MSE: 0.000098, MAE: 0.007716, R²: -0.2602
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.09506 | val 0.06939
  Epoch 020 - train 0.09750 | val 0.06865
  Regression -> MSE: 0.000308, MAE: 0.013760, R²: -0.0016
  Directional -> Accuracy: 0.6327, MCC: 0.0820, F1: 0.1818

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.11029 | val 0.06118
  Epoch 020 - train 0.10432 | val 0.06554
  Regression -> MSE: 0.000247, MAE: 0.011511, R²: -0.0149
  Directional -> Accuracy: 0.4474, MCC: -0.1192, F1: 0.5116

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.09480 | val 0.11768
  Epoch 020 - train 0.09385 | val 0.11718
  Regression -> MSE: 0.000082, MAE: 0.007067, R²: -0.0137
  Directional -> Accuracy: 0.5200, MCC: 0.0377, F1: 0.4194

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.10320 | val 0.12391
  Epoch 020 - train 0.09803 | val 0.12117
  Regression -> MSE: 0.000308, MAE: 0.014458, R²: -0.0042
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.11008 | val 0.10591
  Epoch 020 - train 0.10930 | val 0.10640
  Regression -> MSE: 0.000097, MAE: 0.007349, R²: 0.0100
  Directional -> Accuracy: 0.4318, MCC: 0.0000, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.10962 | val 0.11474
  Epoch 020 - train 0.11041 | val 0.11699
  Regression -> MSE: 0.000174, MAE: 0.009410, R²: -0.0136
  Directional -> Accuracy: 0.6122, MCC: 0.0475, F1: 0.0952

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.09241 | val 0.12426
  Epoch 020 - train 0.09258 | val 0.12452
  Regression -> MSE: 0.000228, MAE: 0.011900, R²: -0.0240
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.09676 | val 0.11473
  Epoch 020 - train 0.09754 | val 0.11428
  Regression -> MSE: 0.000092, MAE: 0.007623, R²: 0.0039
  Directional -> Accuracy: 0.5439, MCC: 0.0888, F1: 0.5357

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.10684 | val 0.14879
  Epoch 020 - train 0.10418 | val 0.14929
  Regression -> MSE: 0.000163, MAE: 0.010210, R²: 0.0017
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.09627 | val 0.13272
  Epoch 020 - train 0.09203 | val 0.13143
  Regression -> MSE: 0.000123, MAE: 0.009037, R²: -0.0596
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.09646 | val 0.13623

[I 2026-02-23 03:30:41,230] Trial 221 finished with value: -0.011458030632454702 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 32, 'learning_rate': 2.007090017135368e-06, 'weight_decay': 7.726254089457049e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.14321755156684945, 'early_stopping_min_delta': 0.004881306879864803}. Best is trial 207 with value: -0.01137496405368131.

  Epoch 020 - train 0.09784 | val 0.13584
  Regression -> MSE: 0.000242, MAE: 0.012407, R²: -0.0197
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.14036 | val 0.19413
  Epoch 020 - train 0.14350 | val 0.19443
  Regression -> MSE: 0.000248, MAE: 0.012611, R²: -0.0029
  Directional -> Accuracy: 0.5455, MCC: 0.1715, F1: 0.6316

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.13962 | val 0.15144
  Epoch 020 - train 0.13449 | val 0.15145
  Regression -> MSE: 0.000677, MAE: 0.019176, R²: 0.0115
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.15222 | val 0.23049
  Epoch 020 - train 0.15076 | val 0.23136
  Regression -> MSE: 0.000311, MAE: 0.014394, R²: -0.0019
  Directional -> Accuracy: 0.4681, MCC: -0.1034, F1: 0.5763

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.12115 | val 0.12849
  Epoch 020 - train 0.12148 | val 0.13163
  Regression -> MSE: 0.000351, MAE: 0.014631, R²: -0.0060
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.14179 | val 0.14232
  Epoch 020 - train 0.14047 | val 0.14177
  Regression -> MSE: 0.000204, MAE: 0.010243, R²: -0.0032
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.12859 | val 0.26362
  Epoch 020 - train 0.13210 | val 0.26333
  Regression -> MSE: 0.000555, MAE: 0.018114, R²: -0.0002
  Directional -> Accuracy: 0.5319, MCC: 0.0603, F1: 0.4500

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.14546 | val 0.18039
  Epoch 020 - train 0.14626 | val 0.17960
  Regression -> MSE: 0.000245, MAE: 0.011996, R²: 0.0015
  Directional -> Accuracy: 0.5217, MCC: 0.0471, F1: 0.4762

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.14770 | val 0.18422
  Epoch 020 - train 0.14577 | val 0.18134
  Regression -> MSE: 0.000614, MAE: 0.019537, R²: -0.0277
  Directional -> Accuracy: 0.5000, MCC: 0.0722, F1: 0.5417

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.13707 | val 0.18006
  Epoch 020 - train 0.13710 | val 0.18379
  Regression -> MSE: 0.000398, MAE: 0.016026, R²: -0.0375
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.15107 | val 0.21390
  Epoch 020 - train 0.15529 | val 0.20883
  Regression -> MSE: 0.000248, MAE: 0.012491, R²: -0.0252
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.13511 | val 0.20020
  Epoch 020 - train 0.13996 | val 0.20125
  Regression -> MSE: 0.000322, MAE: 0.013636, R²: -0.0347
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.15134 | val 0.17251
  Epoch 020 - train 0.15052 | val 0.17336
  Regression -> MSE: 0.000678, MAE: 0.019502, R²: -0.0007
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.16841 | val 0.23078
  Epoch 020 - train 0.16454 | val 0.24619
  Regression -> MSE: 0.000141, MAE: 0.009010, R²: -0.0170
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.12927 | val 0.17914
  Epoch 020 - train 0.13395 | val 0.17863
  Regression -> MSE: 0.000218, MAE: 0.010670, R²: 0.0302
  Directional -> Accuracy: 0.5410, MCC: 0.0809, F1: 0.5625

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.14262 | val 0.29407
  Epoch 020 - train 0.14221 | val 0.29386
  Regression -> MSE: 0.000372, MAE: 0.015935, R²: -0.0262
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.14892 | val 0.15371
  Epoch 020 - train 0.14950 | val 0.15387
  Regression -> MSE: 0.000108, MAE: 0.007984, R²: -0.0037
  Directional -> Accuracy: 0.5571, MCC: 0.0890, F1: 0.7048

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.13691 | val 0.26871
  Epoch 020 - train 0.13896 | val 0.27429
  Regression -> MSE: 0.000158, MAE: 0.009970, R²: -0.0149
  Directional -> Accuracy: 0.6441, MCC: 0.2059, F1: 0.7342

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.15671 | val 0.17557
  Epoch 020 - train 0.14709 | val 0.17181
  Regression -> MSE: 0.000274, MAE: 0.013093, R²: -0.0068
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.14054 | val 0.21882
  Epoch 020 - train 0.13590 | val 0.21606
  Regression -> MSE: 0.000153, MAE: 0.008795, R²: -0.0253
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.15590 | val 0.21739
  Epoch 020 - train 0.15446 | val 0.21655
  Regression -> MSE: 0.000227, MAE: 0.010972, R²: -0.0036
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.14702 | val 0.20738
  Epoch 020 - train 0.14798 | val 0.20825
  Regression -> MSE: 0.000146, MAE: 0.008508, R²: -0.0169
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.13523 | val 0.17355
  Epoch 020 - train 0.13702 | val 0.17559
  Regression -> MSE: 0.000175, MAE: 0.010294, R²: -0.0591
  Directional -> Accuracy: 0.4545, MCC: -0.1220, F1: 0.1818

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.15020 | val 0.17248
  Epoch 020 - train 0.15144 | val 0.17225
  Regression -> MSE: 0.000086, MAE: 0.007110, R²: -0.0148
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.14710 | val 0.17762
  Epoch 020 - train 0.14848 | val 0.17809
  Regression -> MSE: 0.000216, MAE: 0.011069, R²: -0.0179
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.13260 | val 0.13018
  Epoch 020 - train 0.13253 | val 0.12932
  Regression -> MSE: 0.000100, MAE: 0.008211, R²: -0.0880
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.14299 | val 0.14750
  Epoch 020 - train 0.14237 | val 0.18613
  Regression -> MSE: 0.000110, MAE: 0.009055, R²: -0.0714
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.14722 | val 0.13840
  Epoch 020 - train 0.15260 | val 0.13998
  Regression -> MSE: 0.000237, MAE: 0.012738, R²: -0.0222
  Directional -> Accuracy: 0.4651, MCC: -0.1076, F1: 0.5490

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.14845 | val 0.17595
  Epoch 020 - train 0.13985 | val 0.17569
  Regression -> MSE: 0.000172, MAE: 0.007771, R²: -0.0341
  Directional -> Accuracy: 0.5263, MCC: 0.0509, F1: 0.5574

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.14838 | val 0.12855
  Epoch 020 - train 0.15140 | val 0.12837
  Regression -> MSE: 0.000240, MAE: 0.012061, R²: -0.0156
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.14173 | val 0.23540
  Epoch 020 - train 0.14470 | val 0.23379
  Regression -> MSE: 0.000234, MAE: 0.010061, R²: -0.0151
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.15169 | val 0.19790
  Epoch 020 - train 0.14917 | val 0.20694
  Regression -> MSE: 0.000143, MAE: 0.008575, R²: -0.0584
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.14599 | val 0.18337
  Epoch 020 - train 0.14787 | val 0.18334
  Regression -> MSE: 0.000189, MAE: 0.010455, R²: -0.0016
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.13724 | val 0.20936
  Epoch 020 - train 0.14044 | val 0.20521
  Regression -> MSE: 0.000267, MAE: 0.010879, R²: -0.0212
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.13361 | val 0.12075
  Epoch 020 - train 0.13657 | val 0.12494
  Regression -> MSE: 0.000167, MAE: 0.010352, R²: -0.0005
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.14135 | val 0.15927
  Epoch 020 - train 0.13599 | val 0.16118
  Regression -> MSE: 0.000184, MAE: 0.010342, R²: -0.0202
  Directional -> Accuracy: 0.4545, MCC: -0.1201, F1: 0.2941

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.15410 | val 0.16753
  Epoch 020 - train 0.15211 | val 0.16473
  Regression -> MSE: 0.000360, MAE: 0.011930, R²: -0.0506
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.15482 | val 0.09541
  Epoch 020 - train 0.14890 | val 0.09806
  Regression -> MSE: 0.000128, MAE: 0.008496, R²: -0.2182
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.15107 | val 0.20363
  Epoch 020 - train 0.15033 | val 0.20342
  Regression -> MSE: 0.000226, MAE: 0.011544, R²: -0.0343
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.14407 | val 0.26304
  Epoch 020 - train 0.14728 | val 0.26431
  Regression -> MSE: 0.000082, MAE: 0.007066, R²: -0.0599
  Directional -> Accuracy: 0.5745, MCC: -0.0391, F1: 0.7143

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.15447 | val 0.14582
  Epoch 020 - train 0.14335 | val 0.14950
  Regression -> MSE: 0.000361, MAE: 0.015993, R²: -0.1736
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.15914 | val 0.08951
  Epoch 020 - train 0.15171 | val 0.10111
  Regression -> MSE: 0.000249, MAE: 0.011645, R²: -0.0201
  Directional -> Accuracy: 0.4211, MCC: -0.1565, F1: 0.2143

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.13503 | val 0.16991
  Epoch 020 - train 0.13452 | val 0.16987
  Regression -> MSE: 0.000080, MAE: 0.007072, R²: 0.0056
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.14525 | val 0.19894
  Epoch 020 - train 0.14699 | val 0.21039
  Regression -> MSE: 0.000305, MAE: 0.014461, R²: 0.0049
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.14260 | val 0.15743
  Epoch 020 - train 0.13903 | val 0.15683
  Regression -> MSE: 0.000099, MAE: 0.007196, R²: -0.0092
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.16327 | val 0.18576
  Epoch 020 - train 0.16210 | val 0.19880
  Regression -> MSE: 0.000176, MAE: 0.010271, R²: -0.0256
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.13491 | val 0.22255
  Epoch 020 - train 0.13850 | val 0.22330
  Regression -> MSE: 0.000227, MAE: 0.011748, R²: -0.0171
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.14643 | val 0.15900
  Epoch 020 - train 0.14408 | val 0.15978
  Regression -> MSE: 0.000091, MAE: 0.007607, R²: 0.0103
  Directional -> Accuracy: 0.5789, MCC: 0.2313, F1: 0.6667

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.15487 | val 0.22270
  Epoch 020 - train 0.15179 | val 0.22293
  Regression -> MSE: 0.000165, MAE: 0.010293, R²: -0.0074
  Directional -> Accuracy: 0.4259, MCC: -0.2320, F1: 0.5753

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.14807 | val 0.17422
  Epoch 020 - train 0.14236 | val 0.17427
  Regression -> MSE: 0.000123, MAE: 0.009016, R²: -0.0594
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.14098 | val 0.19978

[I 2026-02-23 03:32:25,948] Trial 222 finished with value: -0.011458875060333926 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 32, 'learning_rate': 2.6161902879174723e-06, 'weight_decay': 0.00012012788243550219, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.21812484977795868, 'early_stopping_min_delta': 0.005151916899558418}. Best is trial 207 with value: -0.01137496405368131.

  Epoch 020 - train 0.14449 | val 0.20060
  Regression -> MSE: 0.000240, MAE: 0.012341, R²: -0.0101
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.12084 | val 0.17758
  Epoch 020 - train 0.11947 | val 0.17952
  Regression -> MSE: 0.000250, MAE: 0.012637, R²: -0.0091
  Directional -> Accuracy: 0.4805, MCC: -0.0829, F1: 0.3103

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.12244 | val 0.14883
  Epoch 020 - train 0.11727 | val 0.15235
  Regression -> MSE: 0.000720, MAE: 0.019936, R²: -0.0524
  Directional -> Accuracy: 0.4565, MCC: 0.0245, F1: 0.1935

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.12325 | val 0.19989
  Epoch 020 - train 0.12739 | val 0.20142
  Regression -> MSE: 0.000311, MAE: 0.014437, R²: -0.0009
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.11433 | val 0.26270
  Epoch 020 - train 0.11079 | val 0.24161
  Regression -> MSE: 0.000373, MAE: 0.014979, R²: -0.0688
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.12277 | val 0.12949
  Epoch 020 - train 0.12581 | val 0.13043
  Regression -> MSE: 0.000206, MAE: 0.010011, R²: -0.0125
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.11354 | val 0.22266
  Epoch 020 - train 0.11883 | val 0.22722
  Regression -> MSE: 0.000555, MAE: 0.018104, R²: 0.0001
  Directional -> Accuracy: 0.5532, MCC: 0.1357, F1: 0.2759

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.12811 | val 0.16599
  Epoch 020 - train 0.13180 | val 0.16701
  Regression -> MSE: 0.000249, MAE: 0.011982, R²: -0.0134
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.12054 | val 0.14227
  Epoch 020 - train 0.11979 | val 0.14834
  Regression -> MSE: 0.000605, MAE: 0.019317, R²: -0.0133
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.11927 | val 0.14567
  Epoch 020 - train 0.11516 | val 0.14597
  Regression -> MSE: 0.000386, MAE: 0.015890, R²: -0.0065
  Directional -> Accuracy: 0.4286, MCC: -0.1599, F1: 0.6000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.11972 | val 0.15392
  Epoch 020 - train 0.12040 | val 0.15551
  Regression -> MSE: 0.000244, MAE: 0.012250, R²: -0.0090
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.11501 | val 0.16905
  Epoch 020 - train 0.11294 | val 0.17022
  Regression -> MSE: 0.000320, MAE: 0.013663, R²: -0.0292
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.12084 | val 0.14064
  Epoch 020 - train 0.12062 | val 0.14124
  Regression -> MSE: 0.000671, MAE: 0.019341, R²: 0.0096
  Directional -> Accuracy: 0.6207, MCC: 0.2894, F1: 0.7027

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.12458 | val 0.13905
  Epoch 020 - train 0.12287 | val 0.14709
  Regression -> MSE: 0.000138, MAE: 0.009116, R²: -0.0011
  Directional -> Accuracy: 0.5349, MCC: 0.2232, F1: 0.6429

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.12596 | val 0.15060
  Epoch 020 - train 0.12522 | val 0.14972
  Regression -> MSE: 0.000232, MAE: 0.011024, R²: -0.0306
  Directional -> Accuracy: 0.4918, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.11380 | val 0.24490
  Epoch 020 - train 0.11729 | val 0.24608
  Regression -> MSE: 0.000362, MAE: 0.016060, R²: 0.0007
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.12489 | val 0.13821
  Epoch 020 - train 0.12502 | val 0.13806
  Regression -> MSE: 0.000108, MAE: 0.007879, R²: 0.0029
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.11729 | val 0.20939
  Epoch 020 - train 0.11439 | val 0.21422
  Regression -> MSE: 0.000157, MAE: 0.009783, R²: -0.0090
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.11559 | val 0.14953
  Epoch 020 - train 0.11939 | val 0.15030
  Regression -> MSE: 0.000281, MAE: 0.013471, R²: -0.0309
  Directional -> Accuracy: 0.4605, MCC: 0.1641, F1: 0.2264

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.11098 | val 0.16516
  Epoch 020 - train 0.10934 | val 0.16411
  Regression -> MSE: 0.000155, MAE: 0.008760, R²: -0.0365
  Directional -> Accuracy: 0.5538, MCC: -0.0133, F1: 0.6882

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.12535 | val 0.17032
  Epoch 020 - train 0.12295 | val 0.17078
  Regression -> MSE: 0.000264, MAE: 0.011683, R²: -0.1667
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.12197 | val 0.15437
  Epoch 020 - train 0.12073 | val 0.15579
  Regression -> MSE: 0.000151, MAE: 0.008711, R²: -0.0513
  Directional -> Accuracy: 0.5208, MCC: -0.1981, F1: 0.6761

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.11693 | val 0.14275
  Epoch 020 - train 0.11502 | val 0.14296
  Regression -> MSE: 0.000168, MAE: 0.010400, R²: -0.0189
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.12483 | val 0.14419
  Epoch 020 - train 0.12700 | val 0.14406
  Regression -> MSE: 0.000085, MAE: 0.007026, R²: 0.0082
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.11949 | val 0.16088
  Epoch 020 - train 0.12116 | val 0.16474
  Regression -> MSE: 0.000211, MAE: 0.011126, R²: 0.0029
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.11470 | val 0.11530
  Epoch 020 - train 0.11440 | val 0.11512
  Regression -> MSE: 0.000094, MAE: 0.008100, R²: -0.0245
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.12226 | val 0.09448
  Epoch 020 - train 0.12218 | val 0.09485
  Regression -> MSE: 0.000109, MAE: 0.008997, R²: -0.0585
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.12616 | val 0.11413
  Epoch 020 - train 0.12788 | val 0.11458
  Regression -> MSE: 0.000232, MAE: 0.012494, R²: -0.0006
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.11690 | val 0.14914
  Epoch 020 - train 0.11829 | val 0.14842
  Regression -> MSE: 0.000173, MAE: 0.008009, R²: -0.0399
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.12322 | val 0.10478
  Epoch 020 - train 0.11918 | val 0.10632
  Regression -> MSE: 0.000238, MAE: 0.011915, R²: -0.0079
  Directional -> Accuracy: 0.5610, MCC: 0.1701, F1: 0.7097

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.11872 | val 0.20251
  Epoch 020 - train 0.11782 | val 0.20375
  Regression -> MSE: 0.000236, MAE: 0.010230, R²: -0.0250
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.12579 | val 0.15472
  Epoch 020 - train 0.12350 | val 0.15645
  Regression -> MSE: 0.000145, MAE: 0.008702, R²: -0.0712
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.12454 | val 0.15272
  Epoch 020 - train 0.12197 | val 0.15212
  Regression -> MSE: 0.000195, MAE: 0.010535, R²: -0.0370
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.10489 | val 0.14388
  Epoch 020 - train 0.10178 | val 0.14411
  Regression -> MSE: 0.000278, MAE: 0.010814, R²: -0.0629
  Directional -> Accuracy: 0.4247, MCC: -0.1291, F1: 0.4000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.11686 | val 0.09968
  Epoch 020 - train 0.11017 | val 0.10045
  Regression -> MSE: 0.000167, MAE: 0.010368, R²: -0.0042
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.12323 | val 0.15774
  Epoch 020 - train 0.12214 | val 0.16008
  Regression -> MSE: 0.000189, MAE: 0.010786, R²: -0.0529
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.11689 | val 0.10934
  Epoch 020 - train 0.11415 | val 0.10977
  Regression -> MSE: 0.000342, MAE: 0.011923, R²: 0.0017
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.12734 | val 0.07953
  Epoch 020 - train 0.12971 | val 0.08092
  Regression -> MSE: 0.000117, MAE: 0.008244, R²: -0.1134
  Directional -> Accuracy: 0.6744, MCC: 0.4004, F1: 0.5882

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.12738 | val 0.17109
  Epoch 020 - train 0.12444 | val 0.17378
  Regression -> MSE: 0.000220, MAE: 0.011350, R²: -0.0050
  Directional -> Accuracy: 0.3509, MCC: -0.3421, F1: 0.1778

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.12118 | val 0.20487
  Epoch 020 - train 0.11961 | val 0.20494
  Regression -> MSE: 0.000081, MAE: 0.006997, R²: -0.0412
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.11539 | val 0.10294
  Epoch 020 - train 0.12021 | val 0.10264
  Regression -> MSE: 0.000325, MAE: 0.014690, R²: -0.0555
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.13230 | val 0.08690
  Epoch 020 - train 0.13419 | val 0.09759
  Regression -> MSE: 0.000255, MAE: 0.011430, R²: -0.0465
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.12222 | val 0.15457
  Epoch 020 - train 0.11797 | val 0.15541
  Regression -> MSE: 0.000087, MAE: 0.007107, R²: -0.0780
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.11751 | val 0.14812
  Epoch 020 - train 0.11339 | val 0.15123
  Regression -> MSE: 0.000314, MAE: 0.014572, R²: -0.0232
  Directional -> Accuracy: 0.5319, MCC: 0.2064, F1: 0.1538

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.13444 | val 0.12971
  Epoch 020 - train 0.12906 | val 0.13225
  Regression -> MSE: 0.000099, MAE: 0.007357, R²: -0.0045
  Directional -> Accuracy: 0.4545, MCC: 0.0538, F1: 0.1429

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.12781 | val 0.13471
  Epoch 020 - train 0.12383 | val 0.13314
  Regression -> MSE: 0.000182, MAE: 0.010564, R²: -0.0610
  Directional -> Accuracy: 0.4286, MCC: -0.0530, F1: 0.4815

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.11666 | val 0.13604
  Epoch 020 - train 0.11656 | val 0.13653
  Regression -> MSE: 0.000226, MAE: 0.011871, R²: -0.0152
  Directional -> Accuracy: 0.3750, MCC: -0.2598, F1: 0.4262

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.11887 | val 0.12898
  Epoch 020 - train 0.12018 | val 0.12914
  Regression -> MSE: 0.000094, MAE: 0.007674, R²: -0.0155
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.13295 | val 0.21461
  Epoch 020 - train 0.13001 | val 0.21849
  Regression -> MSE: 0.000168, MAE: 0.010295, R²: -0.0288
  Directional -> Accuracy: 0.4815, MCC: 0.0000, F1: 0.0000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.11846 | val 0.14841
  Epoch 020 - train 0.11897 | val 0.14929
  Regression -> MSE: 0.000128, MAE: 0.009058, R²: -0.1077
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.11689 | val 0.19501

[I 2026-02-23 03:34:09,486] Trial 223 finished with value: -0.011478508360197261 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 32, 'learning_rate': 2.8972173895921674e-06, 'weight_decay': 4.148402883309968e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.17699822511877134, 'early_stopping_min_delta': 0.004607522788894029}. Best is trial 207 with value: -0.01137496405368131.

  Epoch 020 - train 0.12134 | val 0.19687
  Regression -> MSE: 0.000241, MAE: 0.012257, R²: -0.0165
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.09891 | val 0.13731
  Epoch 020 - train 0.09687 | val 0.13673
  Regression -> MSE: 0.000257, MAE: 0.012894, R²: -0.0363
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.08850 | val 0.09325
  Epoch 020 - train 0.09247 | val 0.12126
  Regression -> MSE: 0.000705, MAE: 0.019746, R²: -0.0305
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.09609 | val 0.14481
  Epoch 020 - train 0.09390 | val 0.14658
  Regression -> MSE: 0.000315, MAE: 0.014459, R²: -0.0169
  Directional -> Accuracy: 0.5319, MCC: 0.1529, F1: 0.3125

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.08670 | val 0.14179
  Epoch 020 - train 0.08372 | val 0.12770
  Regression -> MSE: 0.000354, MAE: 0.014640, R²: -0.0148
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.09836 | val 0.10546
  Epoch 020 - train 0.09831 | val 0.11346
  Regression -> MSE: 0.000206, MAE: 0.010389, R²: -0.0130
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.09795 | val 0.16282
  Epoch 020 - train 0.09362 | val 0.17226
  Regression -> MSE: 0.000558, MAE: 0.018171, R²: -0.0056
  Directional -> Accuracy: 0.4043, MCC: -0.1949, F1: 0.3636

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.09242 | val 0.11080
  Epoch 020 - train 0.09024 | val 0.11088
  Regression -> MSE: 0.000247, MAE: 0.012266, R²: -0.0057
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.08919 | val 0.11387
  Epoch 020 - train 0.08683 | val 0.12272
  Regression -> MSE: 0.000611, MAE: 0.019510, R²: -0.0234
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.09325 | val 0.11140
  Epoch 020 - train 0.08968 | val 0.11702
  Regression -> MSE: 0.000388, MAE: 0.016047, R²: -0.0107
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.09494 | val 0.12115
  Epoch 020 - train 0.09060 | val 0.11813
  Regression -> MSE: 0.000243, MAE: 0.012147, R²: -0.0075
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.08390 | val 0.12905
  Epoch 020 - train 0.08724 | val 0.12917
  Regression -> MSE: 0.000311, MAE: 0.013795, R²: -0.0001
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.6301

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.09429 | val 0.10490
  Epoch 020 - train 0.09854 | val 0.10727
  Regression -> MSE: 0.000680, MAE: 0.019572, R²: -0.0045
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.09417 | val 0.09052
  Epoch 020 - train 0.09486 | val 0.09266
  Regression -> MSE: 0.000142, MAE: 0.009387, R²: -0.0276
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.08456 | val 0.11788
  Epoch 020 - train 0.08487 | val 0.11852
  Regression -> MSE: 0.000226, MAE: 0.010782, R²: -0.0045
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.08804 | val 0.18656
  Epoch 020 - train 0.08830 | val 0.20673
  Regression -> MSE: 0.000364, MAE: 0.016046, R²: -0.0042
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.09109 | val 0.10395
  Epoch 020 - train 0.09044 | val 0.10493
  Regression -> MSE: 0.000108, MAE: 0.008094, R²: -0.0045
  Directional -> Accuracy: 0.4571, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.08844 | val 0.17002
  Epoch 020 - train 0.08792 | val 0.17756
  Regression -> MSE: 0.000158, MAE: 0.009923, R²: -0.0124
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.10059 | val 0.12401
  Epoch 020 - train 0.10203 | val 0.11986
  Regression -> MSE: 0.000279, MAE: 0.012899, R²: -0.0251
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.08859 | val 0.13052
  Epoch 020 - train 0.08696 | val 0.13134
  Regression -> MSE: 0.000161, MAE: 0.008943, R²: -0.0732
  Directional -> Accuracy: 0.4769, MCC: 0.0998, F1: 0.2917

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.09494 | val 0.13071
  Epoch 020 - train 0.09446 | val 0.13102
  Regression -> MSE: 0.000228, MAE: 0.010966, R²: -0.0095
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.09672 | val 0.11708
  Epoch 020 - train 0.09300 | val 0.12763
  Regression -> MSE: 0.000148, MAE: 0.008622, R²: -0.0346
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.09175 | val 0.11356
  Epoch 020 - train 0.09119 | val 0.11354
  Regression -> MSE: 0.000167, MAE: 0.010718, R²: -0.0099
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.09423 | val 0.10642
  Epoch 020 - train 0.09178 | val 0.10553
  Regression -> MSE: 0.000090, MAE: 0.007297, R²: -0.0547
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.09179 | val 0.13366
  Epoch 020 - train 0.09147 | val 0.13578
  Regression -> MSE: 0.000214, MAE: 0.011396, R²: -0.0124
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.08344 | val 0.08323
  Epoch 020 - train 0.08515 | val 0.08173
  Regression -> MSE: 0.000103, MAE: 0.008275, R²: -0.1160
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.09180 | val 0.07187
  Epoch 020 - train 0.08943 | val 0.07093
  Regression -> MSE: 0.000108, MAE: 0.008963, R²: -0.0503
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.09162 | val 0.09045
  Epoch 020 - train 0.09497 | val 0.10300
  Regression -> MSE: 0.000232, MAE: 0.012589, R²: -0.0041
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.08973 | val 0.10565
  Epoch 020 - train 0.08891 | val 0.10566
  Regression -> MSE: 0.000176, MAE: 0.007885, R²: -0.0573
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.10083 | val 0.07998
  Epoch 020 - train 0.09914 | val 0.10587
  Regression -> MSE: 0.000237, MAE: 0.011870, R²: -0.0009
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.09037 | val 0.13968
  Epoch 020 - train 0.08913 | val 0.14884
  Regression -> MSE: 0.000230, MAE: 0.009865, R²: 0.0006
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.09554 | val 0.10467
  Epoch 020 - train 0.09518 | val 0.10151
  Regression -> MSE: 0.000136, MAE: 0.008238, R²: -0.0067
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.08808 | val 0.11265
  Epoch 020 - train 0.08683 | val 0.11755
  Regression -> MSE: 0.000189, MAE: 0.010469, R²: -0.0025
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.08480 | val 0.10702
  Epoch 020 - train 0.08319 | val 0.10460
  Regression -> MSE: 0.000263, MAE: 0.010516, R²: -0.0033
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.08538 | val 0.07626
  Epoch 020 - train 0.08708 | val 0.07906
  Regression -> MSE: 0.000170, MAE: 0.010374, R²: -0.0209
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.09154 | val 0.09616
  Epoch 020 - train 0.08778 | val 0.10216
  Regression -> MSE: 0.000182, MAE: 0.010402, R²: -0.0112
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.08485 | val 0.08778
  Epoch 020 - train 0.08513 | val 0.08699
  Regression -> MSE: 0.000343, MAE: 0.011669, R²: -0.0007
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.10060 | val 0.06001
  Epoch 020 - train 0.09817 | val 0.06132
  Regression -> MSE: 0.000113, MAE: 0.008317, R²: -0.0790
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.08937 | val 0.12179
  Epoch 020 - train 0.09009 | val 0.12454
  Regression -> MSE: 0.000219, MAE: 0.011293, R²: 0.0000
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.09240 | val 0.15258
  Epoch 020 - train 0.09258 | val 0.16130
  Regression -> MSE: 0.000091, MAE: 0.007482, R²: -0.1775
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.08930 | val 0.06944
  Epoch 020 - train 0.08992 | val 0.07517
  Regression -> MSE: 0.000308, MAE: 0.013836, R²: -0.0025
  Directional -> Accuracy: 0.6327, MCC: 0.0000, F1: 0.0000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.09770 | val 0.05735
  Epoch 020 - train 0.09425 | val 0.05986
  Regression -> MSE: 0.000254, MAE: 0.011486, R²: -0.0410
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.08673 | val 0.10830
  Epoch 020 - train 0.08615 | val 0.10779
  Regression -> MSE: 0.000081, MAE: 0.007058, R²: -0.0001
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.09193 | val 0.11152
  Epoch 020 - train 0.09864 | val 0.15880
  Regression -> MSE: 0.000313, MAE: 0.014549, R²: -0.0210
  Directional -> Accuracy: 0.4894, MCC: 0.0000, F1: 0.0000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.09883 | val 0.09572
  Epoch 020 - train 0.09337 | val 0.09329
  Regression -> MSE: 0.000098, MAE: 0.007239, R²: -0.0010
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.09226 | val 0.10670
  Epoch 020 - train 0.09733 | val 0.11330
  Regression -> MSE: 0.000172, MAE: 0.009719, R²: -0.0005
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.08534 | val 0.11520
  Epoch 020 - train 0.08667 | val 0.12101
  Regression -> MSE: 0.000224, MAE: 0.011801, R²: -0.0056
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.09448 | val 0.10178
  Epoch 020 - train 0.09160 | val 0.10356
  Regression -> MSE: 0.000092, MAE: 0.007654, R²: -0.0015
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.09603 | val 0.13753
  Epoch 020 - train 0.09517 | val 0.14096
  Regression -> MSE: 0.000164, MAE: 0.010227, R²: 0.0008
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.09592 | val 0.11509
  Epoch 020 - train 0.09309 | val 0.11667
  Regression -> MSE: 0.000118, MAE: 0.008969, R²: -0.0222
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.09730 | val 0.13174

[I 2026-02-23 03:35:59,843] Trial 224 finished with value: -0.011436053273217374 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 32, 'learning_rate': 4.465650888924176e-06, 'weight_decay': 6.202882763723275e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.1294484842340652, 'early_stopping_min_delta': 0.005459141264152373}. Best is trial 207 with value: -0.01137496405368131.

  Epoch 020 - train 0.09428 | val 0.13819
  Regression -> MSE: 0.000238, MAE: 0.012348, R²: -0.0018
  Directional -> Accuracy: 0.5738, MCC: 0.2442, F1: 0.6750

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.09800 | val 0.14321
  Epoch 020 - train 0.09960 | val 0.14176
  Regression -> MSE: 0.000264, MAE: 0.013064, R²: -0.0672
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.09670 | val 0.12331
  Epoch 020 - train 0.09313 | val 0.12990
  Regression -> MSE: 0.000709, MAE: 0.019787, R²: -0.0362
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.09385 | val 0.15013
  Epoch 020 - train 0.09352 | val 0.14898
  Regression -> MSE: 0.000318, MAE: 0.014564, R²: -0.0252
  Directional -> Accuracy: 0.3830, MCC: -0.2309, F1: 0.3830

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.08055 | val 0.09202
  Epoch 020 - train 0.08180 | val 0.10104
  Regression -> MSE: 0.000353, MAE: 0.014710, R²: -0.0114
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.09178 | val 0.08568
  Epoch 020 - train 0.09248 | val 0.08568
  Regression -> MSE: 0.000206, MAE: 0.010069, R²: -0.0099
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.08979 | val 0.17898
  Epoch 020 - train 0.08818 | val 0.18707
  Regression -> MSE: 0.000566, MAE: 0.018279, R²: -0.0193
  Directional -> Accuracy: 0.4894, MCC: -0.0237, F1: 0.4545

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.08915 | val 0.11153
  Epoch 020 - train 0.09087 | val 0.11124
  Regression -> MSE: 0.000245, MAE: 0.011835, R²: 0.0037
  Directional -> Accuracy: 0.5217, MCC: -0.0089, F1: 0.3774

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.10085 | val 0.10691
  Epoch 020 - train 0.09626 | val 0.10389
  Regression -> MSE: 0.000609, MAE: 0.019216, R²: -0.0186
  Directional -> Accuracy: 0.5909, MCC: 0.0585, F1: 0.1818

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.08868 | val 0.10284
  Epoch 020 - train 0.08619 | val 0.10234
  Regression -> MSE: 0.000414, MAE: 0.016314, R²: -0.0786
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.09700 | val 0.13099
  Epoch 020 - train 0.09639 | val 0.12507
  Regression -> MSE: 0.000244, MAE: 0.012236, R²: -0.0125
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.08932 | val 0.12778
  Epoch 020 - train 0.08928 | val 0.12637
  Regression -> MSE: 0.000340, MAE: 0.013748, R²: -0.0941
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.09378 | val 0.12146
  Epoch 020 - train 0.09470 | val 0.12332
  Regression -> MSE: 0.000678, MAE: 0.019478, R²: -0.0010
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.09188 | val 0.09516
  Epoch 020 - train 0.09484 | val 0.09500
  Regression -> MSE: 0.000143, MAE: 0.009410, R²: -0.0323
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.08505 | val 0.11809
  Epoch 020 - train 0.08411 | val 0.11741
  Regression -> MSE: 0.000229, MAE: 0.010792, R²: -0.0168
  Directional -> Accuracy: 0.4918, MCC: -0.0098, F1: 0.3404

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.09278 | val 0.18078
  Epoch 020 - train 0.09174 | val 0.18091
  Regression -> MSE: 0.000361, MAE: 0.016074, R²: 0.0027
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.09445 | val 0.09407
  Epoch 020 - train 0.09277 | val 0.09308
  Regression -> MSE: 0.000108, MAE: 0.007964, R²: 0.0031
  Directional -> Accuracy: 0.5714, MCC: 0.1869, F1: 0.7170

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.08893 | val 0.16745
  Epoch 020 - train 0.08917 | val 0.16827
  Regression -> MSE: 0.000156, MAE: 0.009610, R²: -0.0003
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.09427 | val 0.09516
  Epoch 020 - train 0.09237 | val 0.09434
  Regression -> MSE: 0.000280, MAE: 0.013120, R²: -0.0282
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.08238 | val 0.12404
  Epoch 020 - train 0.08046 | val 0.12240
  Regression -> MSE: 0.000160, MAE: 0.008909, R²: -0.0714
  Directional -> Accuracy: 0.4615, MCC: -0.1147, F1: 0.5455

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.09222 | val 0.12821
  Epoch 020 - train 0.09177 | val 0.12894
  Regression -> MSE: 0.000244, MAE: 0.011101, R²: -0.0763
  Directional -> Accuracy: 0.5200, MCC: 0.2434, F1: 0.2174

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.09411 | val 0.11359
  Epoch 020 - train 0.09332 | val 0.11424
  Regression -> MSE: 0.000143, MAE: 0.008278, R²: 0.0030
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.08669 | val 0.11110
  Epoch 020 - train 0.08574 | val 0.11122
  Regression -> MSE: 0.000166, MAE: 0.010274, R²: -0.0029
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.09657 | val 0.10698
  Epoch 020 - train 0.09347 | val 0.10639
  Regression -> MSE: 0.000087, MAE: 0.007155, R²: -0.0207
  Directional -> Accuracy: 0.5862, MCC: 0.1220, F1: 0.6842

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.09161 | val 0.10942
  Epoch 020 - train 0.09117 | val 0.11035
  Regression -> MSE: 0.000212, MAE: 0.011119, R²: -0.0033
  Directional -> Accuracy: 0.5000, MCC: 0.1118, F1: 0.6452

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.08808 | val 0.09178
  Epoch 020 - train 0.08725 | val 0.08989
  Regression -> MSE: 0.000102, MAE: 0.008281, R²: -0.1058
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.09660 | val 0.07705
  Epoch 020 - train 0.09377 | val 0.08140
  Regression -> MSE: 0.000107, MAE: 0.008946, R²: -0.0411
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.09420 | val 0.11552
  Epoch 020 - train 0.09318 | val 0.12067
  Regression -> MSE: 0.000243, MAE: 0.012921, R²: -0.0503
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.09029 | val 0.10499
  Epoch 020 - train 0.09037 | val 0.10466
  Regression -> MSE: 0.000178, MAE: 0.007948, R²: -0.0700
  Directional -> Accuracy: 0.5263, MCC: 0.0255, F1: 0.5970

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.09673 | val 0.07840
  Epoch 020 - train 0.09096 | val 0.08308
  Regression -> MSE: 0.000236, MAE: 0.011851, R²: 0.0032
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.09094 | val 0.15515
  Epoch 020 - train 0.09257 | val 0.16326
  Regression -> MSE: 0.000234, MAE: 0.010076, R²: -0.0140
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.09246 | val 0.11790
  Epoch 020 - train 0.09420 | val 0.11762
  Regression -> MSE: 0.000142, MAE: 0.008479, R²: -0.0508
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.09371 | val 0.11745
  Epoch 020 - train 0.09306 | val 0.11827
  Regression -> MSE: 0.000190, MAE: 0.010457, R²: -0.0105
  Directional -> Accuracy: 0.5000, MCC: -0.1242, F1: 0.6575

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.08835 | val 0.12250
  Epoch 020 - train 0.08739 | val 0.12108
  Regression -> MSE: 0.000265, MAE: 0.010583, R²: -0.0125
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.08028 | val 0.07466
  Epoch 020 - train 0.08726 | val 0.07753
  Regression -> MSE: 0.000167, MAE: 0.010388, R²: -0.0039
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.09158 | val 0.10063
  Epoch 020 - train 0.09297 | val 0.10011
  Regression -> MSE: 0.000197, MAE: 0.010947, R²: -0.0956
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.09098 | val 0.09058
  Epoch 020 - train 0.09076 | val 0.08948
  Regression -> MSE: 0.000349, MAE: 0.011777, R²: -0.0200
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.10311 | val 0.06461
  Epoch 020 - train 0.10102 | val 0.06593
  Regression -> MSE: 0.000114, MAE: 0.008302, R²: -0.0830
  Directional -> Accuracy: 0.5116, MCC: 0.0051, F1: 0.6667

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.09585 | val 0.12804
  Epoch 020 - train 0.09469 | val 0.12973
  Regression -> MSE: 0.000218, MAE: 0.011255, R²: 0.0019
  Directional -> Accuracy: 0.5965, MCC: 0.2896, F1: 0.2581

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.09145 | val 0.15625
  Epoch 020 - train 0.08831 | val 0.15913
  Regression -> MSE: 0.000087, MAE: 0.007269, R²: -0.1155
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.09130 | val 0.07196
  Epoch 020 - train 0.08919 | val 0.07190
  Regression -> MSE: 0.000318, MAE: 0.014418, R²: -0.0350
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.09066 | val 0.05820
  Epoch 020 - train 0.09361 | val 0.06565
  Regression -> MSE: 0.000245, MAE: 0.011531, R²: -0.0051
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.0000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.09608 | val 0.10581
  Epoch 020 - train 0.09219 | val 0.10577
  Regression -> MSE: 0.000081, MAE: 0.007074, R²: -0.0026
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.09017 | val 0.11008
  Epoch 020 - train 0.08914 | val 0.11034
  Regression -> MSE: 0.000306, MAE: 0.014455, R²: 0.0037
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.09355 | val 0.10348
  Epoch 020 - train 0.08954 | val 0.10307
  Regression -> MSE: 0.000100, MAE: 0.007099, R²: -0.0148
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.09852 | val 0.10821
  Epoch 020 - train 0.09965 | val 0.11183
  Regression -> MSE: 0.000172, MAE: 0.009683, R²: -0.0000
  Directional -> Accuracy: 0.4286, MCC: 0.0116, F1: 0.5333

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.08490 | val 0.10061
  Epoch 020 - train 0.08575 | val 0.10039
  Regression -> MSE: 0.000226, MAE: 0.011858, R²: -0.0149
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.08984 | val 0.10159
  Epoch 020 - train 0.08874 | val 0.10218
  Regression -> MSE: 0.000093, MAE: 0.007660, R²: -0.0087
  Directional -> Accuracy: 0.5088, MCC: -0.0458, F1: 0.1250

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.09923 | val 0.14977
  Epoch 020 - train 0.09576 | val 0.14984
  Regression -> MSE: 0.000169, MAE: 0.010348, R²: -0.0351
  Directional -> Accuracy: 0.4815, MCC: 0.0000, F1: 0.0000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.09427 | val 0.12179
  Epoch 020 - train 0.09679 | val 0.12068
  Regression -> MSE: 0.000128, MAE: 0.009045, R²: -0.1021
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.09182 | val 0.13801

[I 2026-02-23 03:37:43,230] Trial 225 finished with value: -0.011439581841432109 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 32, 'learning_rate': 5.3362808684266205e-06, 'weight_decay': 6.604389137259828e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.13126668855898477, 'early_stopping_min_delta': 0.004998252853203524}. Best is trial 207 with value: -0.01137496405368131.

  Epoch 020 - train 0.09425 | val 0.13860
  Regression -> MSE: 0.000238, MAE: 0.012219, R²: -0.0048
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.09487 | val 0.12124
  Epoch 020 - train 0.09268 | val 0.12089
  Regression -> MSE: 0.000257, MAE: 0.012917, R²: -0.0393
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.09302 | val 0.09268
  Epoch 020 - train 0.09186 | val 0.09352
  Regression -> MSE: 0.000683, MAE: 0.019334, R²: 0.0023
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.09366 | val 0.14684
  Epoch 020 - train 0.09342 | val 0.14539
  Regression -> MSE: 0.000323, MAE: 0.014528, R²: -0.0399
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.08381 | val 0.09149
  Epoch 020 - train 0.08372 | val 0.08909
  Regression -> MSE: 0.000352, MAE: 0.014600, R²: -0.0070
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.09398 | val 0.09497
  Epoch 020 - train 0.09360 | val 0.09258
  Regression -> MSE: 0.000206, MAE: 0.010086, R²: -0.0112
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.08903 | val 0.17668
  Epoch 020 - train 0.09131 | val 0.22474
  Regression -> MSE: 0.000566, MAE: 0.018251, R²: -0.0188
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.10180 | val 0.13280
  Epoch 020 - train 0.10139 | val 0.13398
  Regression -> MSE: 0.000250, MAE: 0.011971, R²: -0.0183
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.09494 | val 0.10850
  Epoch 020 - train 0.09622 | val 0.10247
  Regression -> MSE: 0.000597, MAE: 0.019209, R²: 0.0010
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.08607 | val 0.11172
  Epoch 020 - train 0.08384 | val 0.11101
  Regression -> MSE: 0.000389, MAE: 0.015905, R²: -0.0143
  Directional -> Accuracy: 0.5918, MCC: 0.1826, F1: 0.5652

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.09186 | val 0.11795
  Epoch 020 - train 0.09330 | val 0.11914
  Regression -> MSE: 0.000243, MAE: 0.011701, R²: -0.0085
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.08494 | val 0.15280
  Epoch 020 - train 0.08350 | val 0.17582
  Regression -> MSE: 0.000314, MAE: 0.013617, R²: -0.0084
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.09634 | val 0.10905
  Epoch 020 - train 0.09589 | val 0.11038
  Regression -> MSE: 0.000678, MAE: 0.019493, R²: -0.0012
  Directional -> Accuracy: 0.4655, MCC: -0.1361, F1: 0.0606

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.09338 | val 0.10069
  Epoch 020 - train 0.09441 | val 0.11385
  Regression -> MSE: 0.000138, MAE: 0.009036, R²: -0.0003
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.08989 | val 0.12825
  Epoch 020 - train 0.08813 | val 0.12879
  Regression -> MSE: 0.000228, MAE: 0.010942, R²: -0.0135
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.09137 | val 0.18226
  Epoch 020 - train 0.09546 | val 0.17796
  Regression -> MSE: 0.000375, MAE: 0.016430, R²: -0.0362
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.10031 | val 0.09627
  Epoch 020 - train 0.09868 | val 0.09680
  Regression -> MSE: 0.000108, MAE: 0.008116, R²: -0.0039
  Directional -> Accuracy: 0.4571, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.09533 | val 0.16807
  Epoch 020 - train 0.09391 | val 0.17283
  Regression -> MSE: 0.000157, MAE: 0.009515, R²: -0.0064
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.09239 | val 0.09809
  Epoch 020 - train 0.09399 | val 0.09832
  Regression -> MSE: 0.000272, MAE: 0.013080, R²: -0.0011
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.08848 | val 0.12629
  Epoch 020 - train 0.08704 | val 0.12606
  Regression -> MSE: 0.000152, MAE: 0.008744, R²: -0.0148
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.10056 | val 0.13714
  Epoch 020 - train 0.09986 | val 0.13797
  Regression -> MSE: 0.000231, MAE: 0.010910, R²: -0.0200
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.09742 | val 0.13261
  Epoch 020 - train 0.09928 | val 0.15253
  Regression -> MSE: 0.000150, MAE: 0.008700, R²: -0.0478
  Directional -> Accuracy: 0.6458, MCC: 0.1883, F1: 0.7792

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.09067 | val 0.11213
  Epoch 020 - train 0.08909 | val 0.11215
  Regression -> MSE: 0.000172, MAE: 0.010251, R²: -0.0393
  Directional -> Accuracy: 0.5455, MCC: 0.0954, F1: 0.6053

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.09647 | val 0.10812
  Epoch 020 - train 0.09764 | val 0.10918
  Regression -> MSE: 0.000093, MAE: 0.007456, R²: -0.0913
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.09980 | val 0.15709
  Epoch 020 - train 0.09498 | val 0.16321
  Regression -> MSE: 0.000212, MAE: 0.011074, R²: -0.0009
  Directional -> Accuracy: 0.5909, MCC: 0.1717, F1: 0.4906

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.08627 | val 0.08073
  Epoch 020 - train 0.08571 | val 0.08148
  Regression -> MSE: 0.000096, MAE: 0.008127, R²: -0.0440
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.10004 | val 0.07278
  Epoch 020 - train 0.09998 | val 0.07647
  Regression -> MSE: 0.000103, MAE: 0.008743, R²: -0.0014
  Directional -> Accuracy: 0.4783, MCC: 0.1870, F1: 0.6250

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.09910 | val 0.08979
  Epoch 020 - train 0.09720 | val 0.09318
  Regression -> MSE: 0.000232, MAE: 0.012584, R²: -0.0038
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.09357 | val 0.10567
  Epoch 020 - train 0.09330 | val 0.10572
  Regression -> MSE: 0.000187, MAE: 0.008121, R²: -0.1260
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.09962 | val 0.08334
  Epoch 020 - train 0.09813 | val 0.08417
  Regression -> MSE: 0.000240, MAE: 0.012018, R²: -0.0140
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.09735 | val 0.14345
  Epoch 020 - train 0.09734 | val 0.14432
  Regression -> MSE: 0.000232, MAE: 0.009941, R²: -0.0050
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.09593 | val 0.10869
  Epoch 020 - train 0.09574 | val 0.10702
  Regression -> MSE: 0.000136, MAE: 0.008234, R²: -0.0051
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.09597 | val 0.11552
  Epoch 020 - train 0.09536 | val 0.11649
  Regression -> MSE: 0.000191, MAE: 0.010410, R²: -0.0136
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.08675 | val 0.10723
  Epoch 020 - train 0.09052 | val 0.10644
  Regression -> MSE: 0.000261, MAE: 0.010574, R²: 0.0023
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.09974 | val 0.08504
  Epoch 020 - train 0.10174 | val 0.10270
  Regression -> MSE: 0.000168, MAE: 0.010364, R²: -0.0070
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.08602 | val 0.09632
  Epoch 020 - train 0.08584 | val 0.09854
  Regression -> MSE: 0.000186, MAE: 0.010559, R²: -0.0340
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.09106 | val 0.09279
  Epoch 020 - train 0.09062 | val 0.09274
  Regression -> MSE: 0.000342, MAE: 0.011825, R²: 0.0025
  Directional -> Accuracy: 0.5224, MCC: 0.1968, F1: 0.3333

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.09839 | val 0.06152
  Epoch 020 - train 0.10228 | val 0.06354
  Regression -> MSE: 0.000120, MAE: 0.008359, R²: -0.1424
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.09712 | val 0.13211
  Epoch 020 - train 0.09657 | val 0.13379
  Regression -> MSE: 0.000219, MAE: 0.011335, R²: -0.0017
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.09241 | val 0.14953
  Epoch 020 - train 0.08953 | val 0.14743
  Regression -> MSE: 0.000096, MAE: 0.007739, R²: -0.2423
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.09090 | val 0.06940
  Epoch 020 - train 0.09001 | val 0.06810
  Regression -> MSE: 0.000311, MAE: 0.014012, R²: -0.0101
  Directional -> Accuracy: 0.4694, MCC: 0.1428, F1: 0.5517

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.10702 | val 0.06248
  Epoch 020 - train 0.10271 | val 0.06236
  Regression -> MSE: 0.000264, MAE: 0.011531, R²: -0.0816
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.09094 | val 0.10849
  Epoch 020 - train 0.08788 | val 0.10801
  Regression -> MSE: 0.000082, MAE: 0.007062, R²: -0.0158
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.10050 | val 0.12481
  Epoch 020 - train 0.10138 | val 0.14903
  Regression -> MSE: 0.000313, MAE: 0.014505, R²: -0.0211
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.09840 | val 0.11020
  Epoch 020 - train 0.09612 | val 0.11906
  Regression -> MSE: 0.000101, MAE: 0.007108, R²: -0.0313
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.10281 | val 0.11107
  Epoch 020 - train 0.10002 | val 0.11734
  Regression -> MSE: 0.000173, MAE: 0.009497, R²: -0.0039
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.09021 | val 0.11771
  Epoch 020 - train 0.08878 | val 0.12070
  Regression -> MSE: 0.000225, MAE: 0.011798, R²: -0.0103
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.09268 | val 0.10655
  Epoch 020 - train 0.09378 | val 0.10661
  Regression -> MSE: 0.000095, MAE: 0.007844, R²: -0.0327
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.09939 | val 0.14838
  Epoch 020 - train 0.10023 | val 0.15121
  Regression -> MSE: 0.000164, MAE: 0.010271, R²: -0.0010
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.09211 | val 0.12611
  Epoch 020 - train 0.09143 | val 0.12940
  Regression -> MSE: 0.000118, MAE: 0.008952, R²: -0.0174
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.09895 | val 0.13660

[I 2026-02-23 03:39:33,544] Trial 226 finished with value: -0.011396437614062978 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 32, 'learning_rate': 3.2749839229456592e-06, 'weight_decay': 5.683158756564359e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.13406671459791847, 'early_stopping_min_delta': 0.005460096311057946}. Best is trial 207 with value: -0.01137496405368131.

  Epoch 020 - train 0.09685 | val 0.13637
  Regression -> MSE: 0.000237, MAE: 0.012441, R²: 0.0005
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.12047 | val 0.16859
  Epoch 020 - train 0.11930 | val 0.16701
  Regression -> MSE: 0.000251, MAE: 0.012664, R²: -0.0120
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.11939 | val 0.10979
  Epoch 020 - train 0.12240 | val 0.11205
  Regression -> MSE: 0.000687, MAE: 0.019383, R²: -0.0033
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.12866 | val 0.20023
  Epoch 020 - train 0.12308 | val 0.21013
  Regression -> MSE: 0.000314, MAE: 0.014452, R²: -0.0132
  Directional -> Accuracy: 0.5532, MCC: 0.1572, F1: 0.7042

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.10856 | val 0.11618
  Epoch 020 - train 0.10682 | val 0.11849
  Regression -> MSE: 0.000351, MAE: 0.014624, R²: -0.0045
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.12512 | val 0.12546
  Epoch 020 - train 0.12581 | val 0.12570
  Regression -> MSE: 0.000207, MAE: 0.010375, R²: -0.0147
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.10945 | val 0.22165
  Epoch 020 - train 0.10866 | val 0.21961
  Regression -> MSE: 0.000586, MAE: 0.018687, R²: -0.0552
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.12052 | val 0.15264
  Epoch 020 - train 0.12635 | val 0.15402
  Regression -> MSE: 0.000247, MAE: 0.012297, R²: -0.0064
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.12394 | val 0.14199
  Epoch 020 - train 0.11890 | val 0.13609
  Regression -> MSE: 0.000599, MAE: 0.019115, R²: -0.0032
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.12053 | val 0.13918
  Epoch 020 - train 0.11739 | val 0.13522
  Regression -> MSE: 0.000402, MAE: 0.016103, R²: -0.0491
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.13377 | val 0.22276
  Epoch 020 - train 0.13225 | val 0.23264
  Regression -> MSE: 0.000251, MAE: 0.011634, R²: -0.0408
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.11590 | val 0.18088
  Epoch 020 - train 0.12019 | val 0.20285
  Regression -> MSE: 0.000323, MAE: 0.013604, R²: -0.0391
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.12130 | val 0.14314
  Epoch 020 - train 0.12173 | val 0.15053
  Regression -> MSE: 0.000684, MAE: 0.019712, R²: -0.0096
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.12788 | val 0.13024
  Epoch 020 - train 0.12864 | val 0.14847
  Regression -> MSE: 0.000139, MAE: 0.009013, R²: -0.0039
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.11789 | val 0.17356
  Epoch 020 - train 0.11575 | val 0.17708
  Regression -> MSE: 0.000226, MAE: 0.010712, R²: -0.0053
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.11926 | val 0.25138
  Epoch 020 - train 0.12377 | val 0.26034
  Regression -> MSE: 0.000366, MAE: 0.015961, R²: -0.0096
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.12442 | val 0.13335
  Epoch 020 - train 0.12386 | val 0.13613
  Regression -> MSE: 0.000108, MAE: 0.007962, R²: -0.0056
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.11761 | val 0.20499
  Epoch 020 - train 0.11473 | val 0.20758
  Regression -> MSE: 0.000157, MAE: 0.009757, R²: -0.0042
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.12137 | val 0.12740
  Epoch 020 - train 0.12047 | val 0.12734
  Regression -> MSE: 0.000274, MAE: 0.013126, R²: -0.0067
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.11337 | val 0.16242
  Epoch 020 - train 0.11172 | val 0.16142
  Regression -> MSE: 0.000172, MAE: 0.009292, R²: -0.1524
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.12725 | val 0.19285
  Epoch 020 - train 0.12891 | val 0.18902
  Regression -> MSE: 0.000233, MAE: 0.010938, R²: -0.0290
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.13712 | val 0.15478
  Epoch 020 - train 0.13370 | val 0.15541
  Regression -> MSE: 0.000144, MAE: 0.008328, R²: -0.0023
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.11354 | val 0.13986
  Epoch 020 - train 0.11161 | val 0.14059
  Regression -> MSE: 0.000168, MAE: 0.010257, R²: -0.0166
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.12739 | val 0.13858
  Epoch 020 - train 0.12834 | val 0.13912
  Regression -> MSE: 0.000089, MAE: 0.007251, R²: -0.0415
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.12038 | val 0.16167
  Epoch 020 - train 0.11791 | val 0.16432
  Regression -> MSE: 0.000212, MAE: 0.011083, R²: -0.0022
  Directional -> Accuracy: 0.5455, MCC: 0.0992, F1: 0.5588

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.11337 | val 0.11384
  Epoch 020 - train 0.11465 | val 0.11302
  Regression -> MSE: 0.000103, MAE: 0.008254, R²: -0.1154
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.11879 | val 0.09780
  Epoch 020 - train 0.12100 | val 0.10149
  Regression -> MSE: 0.000111, MAE: 0.009068, R²: -0.0762
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.11711 | val 0.11382
  Epoch 020 - train 0.12094 | val 0.11422
  Regression -> MSE: 0.000233, MAE: 0.012629, R²: -0.0087
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.12200 | val 0.13595
  Epoch 020 - train 0.11875 | val 0.13590
  Regression -> MSE: 0.000187, MAE: 0.008098, R²: -0.1229
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.12030 | val 0.10227
  Epoch 020 - train 0.12235 | val 0.10495
  Regression -> MSE: 0.000236, MAE: 0.011856, R²: 0.0002
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.12155 | val 0.18777
  Epoch 020 - train 0.12148 | val 0.18954
  Regression -> MSE: 0.000230, MAE: 0.009877, R²: 0.0003
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.13928 | val 0.16776
  Epoch 020 - train 0.14146 | val 0.22786
  Regression -> MSE: 0.000139, MAE: 0.008421, R²: -0.0331
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.12436 | val 0.15203
  Epoch 020 - train 0.11943 | val 0.15373
  Regression -> MSE: 0.000192, MAE: 0.010393, R²: -0.0191
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.10992 | val 0.14975
  Epoch 020 - train 0.10711 | val 0.15155
  Regression -> MSE: 0.000270, MAE: 0.010639, R²: -0.0304
  Directional -> Accuracy: 0.5753, MCC: 0.1768, F1: 0.5634

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.12109 | val 0.10417
  Epoch 020 - train 0.11583 | val 0.10878
  Regression -> MSE: 0.000167, MAE: 0.010362, R²: -0.0004
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.11603 | val 0.11791
  Epoch 020 - train 0.11224 | val 0.12302
  Regression -> MSE: 0.000182, MAE: 0.010300, R²: -0.0102
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.11665 | val 0.11560
  Epoch 020 - train 0.11685 | val 0.11583
  Regression -> MSE: 0.000347, MAE: 0.012201, R²: -0.0124
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.13300 | val 0.07798
  Epoch 020 - train 0.13176 | val 0.08105
  Regression -> MSE: 0.000116, MAE: 0.008333, R²: -0.1055
  Directional -> Accuracy: 0.5116, MCC: 0.0051, F1: 0.6667

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.12492 | val 0.17435
  Epoch 020 - train 0.12225 | val 0.18461
  Regression -> MSE: 0.000220, MAE: 0.011305, R²: -0.0057
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.12236 | val 0.19718
  Epoch 020 - train 0.12388 | val 0.19719
  Regression -> MSE: 0.000091, MAE: 0.007450, R²: -0.1680
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.11904 | val 0.09255
  Epoch 020 - train 0.11641 | val 0.09433
  Regression -> MSE: 0.000313, MAE: 0.014130, R²: -0.0175
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.13368 | val 0.08379
  Epoch 020 - train 0.12969 | val 0.08424
  Regression -> MSE: 0.000263, MAE: 0.011527, R²: -0.0804
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.12278 | val 0.16044
  Epoch 020 - train 0.12097 | val 0.16071
  Regression -> MSE: 0.000086, MAE: 0.007075, R²: -0.0670
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.11845 | val 0.15231
  Epoch 020 - train 0.11867 | val 0.14578
  Regression -> MSE: 0.000305, MAE: 0.014435, R²: 0.0049
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.11827 | val 0.14182
  Epoch 020 - train 0.11392 | val 0.13841
  Regression -> MSE: 0.000102, MAE: 0.007107, R²: -0.0430
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.12830 | val 0.14077
  Epoch 020 - train 0.12497 | val 0.14773
  Regression -> MSE: 0.000172, MAE: 0.009826, R²: -0.0032
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.11274 | val 0.14356
  Epoch 020 - train 0.11422 | val 0.15199
  Regression -> MSE: 0.000226, MAE: 0.011847, R²: -0.0142
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.12016 | val 0.13014
  Epoch 020 - train 0.12036 | val 0.13192
  Regression -> MSE: 0.000092, MAE: 0.007639, R²: 0.0002
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.12904 | val 0.18063
  Epoch 020 - train 0.12857 | val 0.18065
  Regression -> MSE: 0.000164, MAE: 0.010263, R²: -0.0038
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.12240 | val 0.14830
  Epoch 020 - train 0.11880 | val 0.14748
  Regression -> MSE: 0.000117, MAE: 0.008949, R²: -0.0123
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.11997 | val 0.16300

[I 2026-02-23 03:41:23,565] Trial 227 finished with value: -0.011413073342186178 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 32, 'learning_rate': 3.3062912270735814e-06, 'weight_decay': 5.2880770686336237e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.1776295205480132, 'early_stopping_min_delta': 0.005651300845275379}. Best is trial 207 with value: -0.01137496405368131.

  Epoch 020 - train 0.11862 | val 0.16285
  Regression -> MSE: 0.000240, MAE: 0.012340, R²: -0.0125
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.13532 | val 0.17281
  Epoch 020 - train 0.13346 | val 0.17170
  Regression -> MSE: 0.000262, MAE: 0.012987, R²: -0.0579
  Directional -> Accuracy: 0.4935, MCC: -0.0922, F1: 0.2041

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.13054 | val 0.12519
  Epoch 020 - train 0.13021 | val 0.12613
  Regression -> MSE: 0.000690, MAE: 0.019417, R²: -0.0080
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.14105 | val 0.22700
  Epoch 020 - train 0.13855 | val 0.24249
  Regression -> MSE: 0.000330, MAE: 0.014610, R²: -0.0628
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.11162 | val 0.16237
  Epoch 020 - train 0.11045 | val 0.16964
  Regression -> MSE: 0.000349, MAE: 0.014568, R²: -0.0001
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.13057 | val 0.12583
  Epoch 020 - train 0.12977 | val 0.12911
  Regression -> MSE: 0.000199, MAE: 0.009735, R²: 0.0233
  Directional -> Accuracy: 0.6078, MCC: 0.2173, F1: 0.6154

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.12785 | val 0.26390
  Epoch 020 - train 0.13098 | val 0.30692
  Regression -> MSE: 0.000611, MAE: 0.019225, R²: -0.0998
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.13433 | val 0.16719
  Epoch 020 - train 0.13521 | val 0.16670
  Regression -> MSE: 0.000246, MAE: 0.011938, R²: -0.0001
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.13233 | val 0.16578
  Epoch 020 - train 0.12980 | val 0.16348
  Regression -> MSE: 0.000612, MAE: 0.019527, R²: -0.0245
  Directional -> Accuracy: 0.4773, MCC: -0.1601, F1: 0.2069

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.14237 | val 0.16473
  Epoch 020 - train 0.14066 | val 0.16798
  Regression -> MSE: 0.000387, MAE: 0.016086, R²: -0.0092
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.13362 | val 0.17387
  Epoch 020 - train 0.13276 | val 0.17726
  Regression -> MSE: 0.000244, MAE: 0.011663, R²: -0.0126
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.12146 | val 0.21101
  Epoch 020 - train 0.11964 | val 0.26753
  Regression -> MSE: 0.000313, MAE: 0.013602, R²: -0.0051
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.14279 | val 0.16868
  Epoch 020 - train 0.14294 | val 0.16261
  Regression -> MSE: 0.000692, MAE: 0.020015, R²: -0.0225
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.13556 | val 0.13194
  Epoch 020 - train 0.13287 | val 0.14791
  Regression -> MSE: 0.000144, MAE: 0.009488, R²: -0.0455
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.12648 | val 0.19815
  Epoch 020 - train 0.12546 | val 0.18908
  Regression -> MSE: 0.000226, MAE: 0.010800, R²: -0.0053
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.13299 | val 0.26540
  Epoch 020 - train 0.13047 | val 0.26741
  Regression -> MSE: 0.000366, MAE: 0.015774, R²: -0.0104
  Directional -> Accuracy: 0.5962, MCC: 0.2214, F1: 0.2759

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.15414 | val 0.17308
  Epoch 020 - train 0.15158 | val 0.17500
  Regression -> MSE: 0.000112, MAE: 0.008303, R²: -0.0393
  Directional -> Accuracy: 0.4571, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.12613 | val 0.21804
  Epoch 020 - train 0.12556 | val 0.23055
  Regression -> MSE: 0.000157, MAE: 0.009795, R²: -0.0101
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.13553 | val 0.13692
  Epoch 020 - train 0.13294 | val 0.13856
  Regression -> MSE: 0.000280, MAE: 0.013413, R²: -0.0294
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.12084 | val 0.18267
  Epoch 020 - train 0.11958 | val 0.18363
  Regression -> MSE: 0.000163, MAE: 0.009013, R²: -0.0920
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.14166 | val 0.20060
  Epoch 020 - train 0.13946 | val 0.20097
  Regression -> MSE: 0.000231, MAE: 0.010856, R²: -0.0221
  Directional -> Accuracy: 0.6533, MCC: 0.2957, F1: 0.7234

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.13400 | val 0.17888
  Epoch 020 - train 0.12990 | val 0.22986
  Regression -> MSE: 0.000143, MAE: 0.008299, R²: 0.0019
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.12884 | val 0.15807
  Epoch 020 - train 0.12969 | val 0.15738
  Regression -> MSE: 0.000180, MAE: 0.010319, R²: -0.0906
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.13337 | val 0.16881
  Epoch 020 - train 0.13521 | val 0.17037
  Regression -> MSE: 0.000085, MAE: 0.007033, R²: -0.0000
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.13112 | val 0.16229
  Epoch 020 - train 0.12761 | val 0.16423
  Regression -> MSE: 0.000213, MAE: 0.011061, R²: -0.0060
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.12619 | val 0.12388
  Epoch 020 - train 0.12342 | val 0.12342
  Regression -> MSE: 0.000093, MAE: 0.008106, R²: -0.0154
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.13176 | val 0.10510
  Epoch 020 - train 0.13101 | val 0.12282
  Regression -> MSE: 0.000104, MAE: 0.008807, R²: -0.0132
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.13566 | val 0.12670
  Epoch 020 - train 0.13699 | val 0.14845
  Regression -> MSE: 0.000237, MAE: 0.012765, R²: -0.0260
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.13370 | val 0.15334
  Epoch 020 - train 0.13005 | val 0.15330
  Regression -> MSE: 0.000180, MAE: 0.007967, R²: -0.0844
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.14083 | val 0.11352
  Epoch 020 - train 0.13907 | val 0.13156
  Regression -> MSE: 0.000237, MAE: 0.011878, R²: -0.0027
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.12997 | val 0.21310
  Epoch 020 - train 0.12471 | val 0.21696
  Regression -> MSE: 0.000231, MAE: 0.009888, R²: -0.0021
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.14132 | val 0.17410
  Epoch 020 - train 0.13832 | val 0.18778
  Regression -> MSE: 0.000142, MAE: 0.008536, R²: -0.0493
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.13778 | val 0.16895
  Epoch 020 - train 0.13365 | val 0.17013
  Regression -> MSE: 0.000191, MAE: 0.010359, R²: -0.0149
  Directional -> Accuracy: 0.6000, MCC: 0.2737, F1: 0.7297

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.11711 | val 0.16901
  Epoch 020 - train 0.11810 | val 0.16773
  Regression -> MSE: 0.000262, MAE: 0.010532, R²: -0.0011
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.11932 | val 0.11298
  Epoch 020 - train 0.11924 | val 0.11064
  Regression -> MSE: 0.000166, MAE: 0.010359, R²: 0.0019
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.12171 | val 0.13649
  Epoch 020 - train 0.11703 | val 0.13684
  Regression -> MSE: 0.000180, MAE: 0.010581, R²: -0.0023
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.13553 | val 0.12334
  Epoch 020 - train 0.12842 | val 0.12283
  Regression -> MSE: 0.000347, MAE: 0.011723, R²: -0.0115
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.14209 | val 0.08631
  Epoch 020 - train 0.14164 | val 0.09706
  Regression -> MSE: 0.000116, MAE: 0.008340, R²: -0.1041
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.13938 | val 0.20645
  Epoch 020 - train 0.13755 | val 0.22879
  Regression -> MSE: 0.000224, MAE: 0.011444, R²: -0.0237
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.14353 | val 0.22702
  Epoch 020 - train 0.14413 | val 0.23394
  Regression -> MSE: 0.000098, MAE: 0.007743, R²: -0.2675
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.13408 | val 0.10623
  Epoch 020 - train 0.13362 | val 0.10910
  Regression -> MSE: 0.000320, MAE: 0.014496, R²: -0.0401
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.14080 | val 0.08607
  Epoch 020 - train 0.14759 | val 0.08337
  Regression -> MSE: 0.000261, MAE: 0.011501, R²: -0.0693
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.13099 | val 0.16606
  Epoch 020 - train 0.12694 | val 0.16604
  Regression -> MSE: 0.000081, MAE: 0.007073, R²: 0.0002
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.13562 | val 0.15969
  Epoch 020 - train 0.13226 | val 0.16772
  Regression -> MSE: 0.000308, MAE: 0.014515, R²: -0.0049
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.12565 | val 0.14788
  Epoch 020 - train 0.12812 | val 0.14043
  Regression -> MSE: 0.000092, MAE: 0.007012, R²: 0.0679
  Directional -> Accuracy: 0.6364, MCC: 0.2400, F1: 0.7143

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.13921 | val 0.15940
  Epoch 020 - train 0.14078 | val 0.16482
  Regression -> MSE: 0.000173, MAE: 0.009458, R²: -0.0052
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.12200 | val 0.16502
  Epoch 020 - train 0.11984 | val 0.17402
  Regression -> MSE: 0.000226, MAE: 0.011815, R²: -0.0141
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.12685 | val 0.14689
  Epoch 020 - train 0.12590 | val 0.14687
  Regression -> MSE: 0.000092, MAE: 0.007639, R²: -0.0005
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.13424 | val 0.21553
  Epoch 020 - train 0.13443 | val 0.22821
  Regression -> MSE: 0.000165, MAE: 0.010284, R²: -0.0089
  Directional -> Accuracy: 0.4815, MCC: 0.0000, F1: 0.0000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.13578 | val 0.17650
  Epoch 020 - train 0.13412 | val 0.18694
  Regression -> MSE: 0.000120, MAE: 0.008971, R²: -0.0383
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.13795 | val 0.18971

[I 2026-02-23 03:43:12,175] Trial 228 finished with value: -0.01143362084249264 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.0, 'dropout': 0.2, 'batch_size': 32, 'learning_rate': 3.1964330531742007e-06, 'weight_decay': 5.2701473095236024e-05, 'lr_patience': 7, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.20128452152198006, 'early_stopping_min_delta': 0.005713777988327211}. Best is trial 207 with value: -0.01137496405368131.

  Epoch 020 - train 0.13451 | val 0.20207
  Regression -> MSE: 0.000237, MAE: 0.012361, R²: -0.0004
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.14072 | val 0.18458
  Epoch 020 - train 0.14093 | val 0.18536
  Regression -> MSE: 0.000247, MAE: 0.012514, R²: 0.0023
  Directional -> Accuracy: 0.5974, MCC: 0.2564, F1: 0.2051

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.13728 | val 0.18425
  Epoch 020 - train 0.13562 | val 0.19356
  Regression -> MSE: 0.000686, MAE: 0.019220, R²: -0.0014
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.14022 | val 0.25022
  Epoch 020 - train 0.14390 | val 0.25627
  Regression -> MSE: 0.000314, MAE: 0.014363, R²: -0.0131
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.11599 | val 0.42447
  Epoch 020 - train 0.11309 | val 0.42329
  Regression -> MSE: 0.000371, MAE: 0.014870, R²: -0.0618
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.13788 | val 0.13649
  Epoch 020 - train 0.13763 | val 0.13734
  Regression -> MSE: 0.000204, MAE: 0.010203, R²: -0.0009
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.13646 | val 0.29160
  Epoch 020 - train 0.13507 | val 0.33222
  Regression -> MSE: 0.000550, MAE: 0.018221, R²: 0.0087
  Directional -> Accuracy: 0.4894, MCC: 0.0000, F1: 0.6571

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.14428 | val 0.18350
  Epoch 020 - train 0.14356 | val 0.18083
  Regression -> MSE: 0.000252, MAE: 0.012034, R²: -0.0264
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.14239 | val 0.24033
  Epoch 020 - train 0.13960 | val 0.31411
  Regression -> MSE: 0.000666, MAE: 0.020482, R²: -0.1145
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.13741 | val 0.17297
  Epoch 020 - train 0.13533 | val 0.16956
  Regression -> MSE: 0.000391, MAE: 0.016159, R²: -0.0191
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.14238 | val 0.18143
  Epoch 020 - train 0.14165 | val 0.17816
  Regression -> MSE: 0.000244, MAE: 0.011750, R²: -0.0110
  Directional -> Accuracy: 0.4429, MCC: -0.0921, F1: 0.4507

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.13959 | val 0.20647
  Epoch 020 - train 0.13676 | val 0.21870
  Regression -> MSE: 0.000312, MAE: 0.013814, R²: -0.0022
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.6301

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.14450 | val 0.16950
  Epoch 020 - train 0.14466 | val 0.17010
  Regression -> MSE: 0.000686, MAE: 0.019684, R²: -0.0134
  Directional -> Accuracy: 0.4828, MCC: -0.1325, F1: 0.6512

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.14421 | val 0.15591
  Epoch 020 - train 0.14409 | val 0.16692
  Regression -> MSE: 0.000140, MAE: 0.009294, R²: -0.0137
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.12687 | val 0.17782
  Epoch 020 - train 0.12382 | val 0.17788
  Regression -> MSE: 0.000228, MAE: 0.010769, R²: -0.0120
  Directional -> Accuracy: 0.4918, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.14064 | val 0.28332
  Epoch 020 - train 0.13950 | val 0.28449
  Regression -> MSE: 0.000372, MAE: 0.015938, R²: -0.0262
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.15028 | val 0.16893
  Epoch 020 - train 0.14797 | val 0.16635
  Regression -> MSE: 0.000110, MAE: 0.007958, R²: -0.0153
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.14274 | val 0.23767
  Epoch 020 - train 0.14186 | val 0.24599
  Regression -> MSE: 0.000157, MAE: 0.009662, R²: -0.0050
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.13999 | val 0.25779
  Epoch 020 - train 0.13895 | val 0.25737
  Regression -> MSE: 0.000288, MAE: 0.013695, R²: -0.0574
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.12572 | val 0.18728
  Epoch 020 - train 0.12467 | val 0.18648
  Regression -> MSE: 0.000158, MAE: 0.008860, R²: -0.0573
  Directional -> Accuracy: 0.5538, MCC: 0.0365, F1: 0.6588

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.14290 | val 0.20204
  Epoch 020 - train 0.14216 | val 0.20134
  Regression -> MSE: 0.000229, MAE: 0.011022, R²: -0.0114
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.14172 | val 0.19866
  Epoch 020 - train 0.14131 | val 0.20494
  Regression -> MSE: 0.000144, MAE: 0.008323, R²: -0.0039
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.12996 | val 0.15999
  Epoch 020 - train 0.13012 | val 0.16063
  Regression -> MSE: 0.000214, MAE: 0.011543, R²: -0.2963
  Directional -> Accuracy: 0.5606, MCC: 0.1361, F1: 0.4314

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.14339 | val 0.17059
  Epoch 020 - train 0.14133 | val 0.17104
  Regression -> MSE: 0.000085, MAE: 0.007057, R²: -0.0001
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.13751 | val 0.17324
  Epoch 020 - train 0.13698 | val 0.17326
  Regression -> MSE: 0.000213, MAE: 0.011224, R²: -0.0074
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.12469 | val 0.11598
  Epoch 020 - train 0.12254 | val 0.11348
  Regression -> MSE: 0.000096, MAE: 0.008279, R²: -0.0446
  Directional -> Accuracy: 0.4821, MCC: -0.0604, F1: 0.5538

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.13923 | val 0.11225
  Epoch 020 - train 0.14315 | val 0.11182
  Regression -> MSE: 0.000115, MAE: 0.009211, R²: -0.1197
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.14981 | val 0.22667
  Epoch 020 - train 0.14486 | val 0.29208
  Regression -> MSE: 0.000232, MAE: 0.012535, R²: -0.0038
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.14313 | val 0.15415
  Epoch 020 - train 0.14434 | val 0.15402
  Regression -> MSE: 0.000222, MAE: 0.009558, R²: -0.3334
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.14264 | val 0.11750
  Epoch 020 - train 0.14100 | val 0.11792
  Regression -> MSE: 0.000238, MAE: 0.011925, R²: -0.0056
  Directional -> Accuracy: 0.6098, MCC: 0.2100, F1: 0.6923

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.14589 | val 0.24996
  Epoch 020 - train 0.15101 | val 0.27454
  Regression -> MSE: 0.000233, MAE: 0.010061, R²: -0.0114
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.14811 | val 0.16925
  Epoch 020 - train 0.14453 | val 0.16441
  Regression -> MSE: 0.000131, MAE: 0.008061, R²: 0.0306
  Directional -> Accuracy: 0.5349, MCC: 0.0282, F1: 0.6667

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.14462 | val 0.17642
  Epoch 020 - train 0.14428 | val 0.17570
  Regression -> MSE: 0.000209, MAE: 0.011124, R²: -0.1108
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.12570 | val 0.16187
  Epoch 020 - train 0.12650 | val 0.16189
  Regression -> MSE: 0.000275, MAE: 0.010803, R²: -0.0497
  Directional -> Accuracy: 0.4932, MCC: 0.1639, F1: 0.2128

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.13051 | val 0.12256
  Epoch 020 - train 0.13264 | val 0.15954
  Regression -> MSE: 0.000166, MAE: 0.010344, R²: 0.0070
  Directional -> Accuracy: 0.5526, MCC: 0.1291, F1: 0.3704

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.14393 | val 0.16223
  Epoch 020 - train 0.14577 | val 0.17326
  Regression -> MSE: 0.000190, MAE: 0.010642, R²: -0.0536
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.12904 | val 0.13955
  Epoch 020 - train 0.12605 | val 0.13866
  Regression -> MSE: 0.000342, MAE: 0.011959, R²: 0.0028
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.14426 | val 0.09344
  Epoch 020 - train 0.14531 | val 0.09539
  Regression -> MSE: 0.000114, MAE: 0.008212, R²: -0.0841
  Directional -> Accuracy: 0.5349, MCC: 0.0658, F1: 0.6000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.14398 | val 0.20856
  Epoch 020 - train 0.14225 | val 0.21001
  Regression -> MSE: 0.000218, MAE: 0.011225, R²: 0.0009
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.13586 | val 0.23929
  Epoch 020 - train 0.13843 | val 0.23928
  Regression -> MSE: 0.000090, MAE: 0.007409, R²: -0.1556
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.13283 | val 0.11154
  Epoch 020 - train 0.13129 | val 0.11289
  Regression -> MSE: 0.000319, MAE: 0.014367, R²: -0.0380
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.15672 | val 0.10273
  Epoch 020 - train 0.15764 | val 0.11702
  Regression -> MSE: 0.000260, MAE: 0.011486, R²: -0.0673
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.13740 | val 0.17816
  Epoch 020 - train 0.13514 | val 0.17743
  Regression -> MSE: 0.000082, MAE: 0.007111, R²: -0.0148
  Directional -> Accuracy: 0.4400, MCC: -0.1235, F1: 0.5227

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.14061 | val 0.17285
  Epoch 020 - train 0.13959 | val 0.18162
  Regression -> MSE: 0.000304, MAE: 0.014396, R²: 0.0090
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.14388 | val 0.14265
  Epoch 020 - train 0.14425 | val 0.14698
  Regression -> MSE: 0.000098, MAE: 0.007321, R²: 0.0011
  Directional -> Accuracy: 0.4318, MCC: 0.0000, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.15265 | val 0.15394
  Epoch 020 - train 0.15397 | val 0.15676
  Regression -> MSE: 0.000178, MAE: 0.009486, R²: -0.0364
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.13269 | val 0.18190
  Epoch 020 - train 0.12654 | val 0.18398
  Regression -> MSE: 0.000224, MAE: 0.011737, R²: -0.0055
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.14136 | val 0.17378
  Epoch 020 - train 0.13495 | val 0.17385
  Regression -> MSE: 0.000099, MAE: 0.008117, R²: -0.0766
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.14283 | val 0.23873
  Epoch 020 - train 0.14493 | val 0.23928
  Regression -> MSE: 0.000164, MAE: 0.010249, R²: -0.0022
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.14025 | val 0.21368
  Epoch 020 - train 0.13558 | val 0.21213
  Regression -> MSE: 0.000117, MAE: 0.008896, R²: -0.0053
  Directional -> Accuracy: 0.5536, MCC: 0.1032, F1: 0.6479

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.13978 | val 0.19820

[I 2026-02-23 03:44:53,197] Trial 229 finished with value: -0.011511651328682823 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.0, 'dropout': 0.2, 'batch_size': 32, 'learning_rate': 3.132443350172503e-06, 'weight_decay': 5.1305465975765194e-05, 'lr_patience': 7, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.21188025831963836, 'early_stopping_min_delta': 0.0053090740805566815}. Best is trial 207 with value: -0.01137496405368131.

  Epoch 020 - train 0.13758 | val 0.19761
  Regression -> MSE: 0.000238, MAE: 0.012412, R²: -0.0026
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.07077 | val 0.10146
  Epoch 020 - train 0.07057 | val 0.10339
  Regression -> MSE: 0.000253, MAE: 0.012768, R²: -0.0221
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.07614 | val 0.08056
  Epoch 020 - train 0.07593 | val 0.09237
  Regression -> MSE: 0.000731, MAE: 0.020113, R²: -0.0676
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.07566 | val 0.12067
  Epoch 020 - train 0.07483 | val 0.13269
  Regression -> MSE: 0.000324, MAE: 0.014558, R²: -0.0449
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.06038 | val 0.06639
  Epoch 020 - train 0.05998 | val 0.06982
  Regression -> MSE: 0.000351, MAE: 0.014614, R²: -0.0052
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.07242 | val 0.07128
  Epoch 020 - train 0.07132 | val 0.06899
  Regression -> MSE: 0.000211, MAE: 0.010217, R²: -0.0346
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.07041 | val 0.14196
  Epoch 020 - train 0.07111 | val 0.18327
  Regression -> MSE: 0.000592, MAE: 0.018800, R²: -0.0668
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.07143 | val 0.08831
  Epoch 020 - train 0.07262 | val 0.08863
  Regression -> MSE: 0.000246, MAE: 0.011944, R²: -0.0008
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.07354 | val 0.09195
  Epoch 020 - train 0.07307 | val 0.07749
  Regression -> MSE: 0.000589, MAE: 0.018989, R²: 0.0146
  Directional -> Accuracy: 0.5682, MCC: -0.0417, F1: 0.0952

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.06978 | val 0.08802
  Epoch 020 - train 0.06783 | val 0.08929
  Regression -> MSE: 0.000391, MAE: 0.015930, R²: -0.0203
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.07784 | val 0.10107
  Epoch 020 - train 0.07619 | val 0.09982
  Regression -> MSE: 0.000246, MAE: 0.011682, R²: -0.0175
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.06689 | val 0.10867
  Epoch 020 - train 0.06725 | val 0.11692
  Regression -> MSE: 0.000311, MAE: 0.013717, R²: -0.0012
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.6301

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.07330 | val 0.08947
  Epoch 020 - train 0.07263 | val 0.09346
  Regression -> MSE: 0.000683, MAE: 0.019536, R²: -0.0078
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.06846 | val 0.07900
  Epoch 020 - train 0.06765 | val 0.08826
  Regression -> MSE: 0.000139, MAE: 0.009086, R²: -0.0026
  Directional -> Accuracy: 0.6047, MCC: 0.1753, F1: 0.4138

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.06534 | val 0.10990
  Epoch 020 - train 0.06533 | val 0.11828
  Regression -> MSE: 0.000225, MAE: 0.010810, R²: 0.0002
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.06902 | val 0.16154
  Epoch 020 - train 0.06942 | val 0.21967
  Regression -> MSE: 0.000366, MAE: 0.015973, R²: -0.0109
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.07478 | val 0.08102
  Epoch 020 - train 0.07459 | val 0.08258
  Regression -> MSE: 0.000108, MAE: 0.007953, R²: -0.0013
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.06988 | val 0.14313
  Epoch 020 - train 0.06956 | val 0.15864
  Regression -> MSE: 0.000159, MAE: 0.010036, R²: -0.0198
  Directional -> Accuracy: 0.6102, MCC: 0.1437, F1: 0.7013

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.07658 | val 0.08205
  Epoch 020 - train 0.07568 | val 0.08521
  Regression -> MSE: 0.000276, MAE: 0.013259, R²: -0.0151
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.06659 | val 0.09841
  Epoch 020 - train 0.06585 | val 0.09565
  Regression -> MSE: 0.000153, MAE: 0.008729, R²: -0.0254
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.07418 | val 0.10562
  Epoch 020 - train 0.07333 | val 0.10678
  Regression -> MSE: 0.000245, MAE: 0.011177, R²: -0.0812
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.07549 | val 0.09125
  Epoch 020 - train 0.07492 | val 0.09426
  Regression -> MSE: 0.000150, MAE: 0.008718, R²: -0.0485
  Directional -> Accuracy: 0.4375, MCC: -0.2437, F1: 0.5714

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.07324 | val 0.09227
  Epoch 020 - train 0.07264 | val 0.09439
  Regression -> MSE: 0.000165, MAE: 0.010498, R²: 0.0006
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.07506 | val 0.09043
  Epoch 020 - train 0.07422 | val 0.09004
  Regression -> MSE: 0.000091, MAE: 0.007353, R²: -0.0699
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.07103 | val 0.09734
  Epoch 020 - train 0.07157 | val 0.09755
  Regression -> MSE: 0.000213, MAE: 0.011087, R²: -0.0036
  Directional -> Accuracy: 0.4848, MCC: -0.0421, F1: 0.4138

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.07123 | val 0.07520
  Epoch 020 - train 0.07057 | val 0.07865
  Regression -> MSE: 0.000097, MAE: 0.008148, R²: -0.0566
  Directional -> Accuracy: 0.5893, MCC: 0.1535, F1: 0.7160

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.07561 | val 0.05678
  Epoch 020 - train 0.07367 | val 0.06248
  Regression -> MSE: 0.000103, MAE: 0.008720, R²: 0.0003
  Directional -> Accuracy: 0.4348, MCC: -0.0510, F1: 0.5667

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.07278 | val 0.06976
  Epoch 020 - train 0.07343 | val 0.07148
  Regression -> MSE: 0.000239, MAE: 0.012834, R²: -0.0340
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.07188 | val 0.08948
  Epoch 020 - train 0.07103 | val 0.08813
  Regression -> MSE: 0.000170, MAE: 0.007812, R²: -0.0235
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.07752 | val 0.06368
  Epoch 020 - train 0.07722 | val 0.06415
  Regression -> MSE: 0.000238, MAE: 0.011941, R²: -0.0077
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.07261 | val 0.11559
  Epoch 020 - train 0.07112 | val 0.11847
  Regression -> MSE: 0.000234, MAE: 0.010110, R²: -0.0134
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.07217 | val 0.08873
  Epoch 020 - train 0.07236 | val 0.08967
  Regression -> MSE: 0.000139, MAE: 0.008352, R²: -0.0281
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.08053 | val 0.09932
  Epoch 020 - train 0.08034 | val 0.10438
  Regression -> MSE: 0.000189, MAE: 0.010583, R²: -0.0036
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.06721 | val 0.08232
  Epoch 020 - train 0.06643 | val 0.08199
  Regression -> MSE: 0.000279, MAE: 0.010904, R²: -0.0641
  Directional -> Accuracy: 0.4384, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.06614 | val 0.06298
  Epoch 020 - train 0.06655 | val 0.06435
  Regression -> MSE: 0.000167, MAE: 0.010368, R²: -0.0048
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.06671 | val 0.07228
  Epoch 020 - train 0.06698 | val 0.07605
  Regression -> MSE: 0.000180, MAE: 0.010305, R²: -0.0017
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.07169 | val 0.06935
  Epoch 020 - train 0.07011 | val 0.06919
  Regression -> MSE: 0.000344, MAE: 0.011701, R²: -0.0041
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.08111 | val 0.04951
  Epoch 020 - train 0.08200 | val 0.06227
  Regression -> MSE: 0.000120, MAE: 0.008364, R²: -0.1426
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.07793 | val 0.09922
  Epoch 020 - train 0.07671 | val 0.10230
  Regression -> MSE: 0.000219, MAE: 0.011279, R²: -0.0008
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.07464 | val 0.11943
  Epoch 020 - train 0.07421 | val 0.11955
  Regression -> MSE: 0.000089, MAE: 0.007369, R²: -0.1422
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.07019 | val 0.06012
  Epoch 020 - train 0.06952 | val 0.06715
  Regression -> MSE: 0.000322, MAE: 0.014631, R²: -0.0461
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.07928 | val 0.05123
  Epoch 020 - train 0.07961 | val 0.05167
  Regression -> MSE: 0.000264, MAE: 0.011522, R²: -0.0809
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.06956 | val 0.08712
  Epoch 020 - train 0.06958 | val 0.08679
  Regression -> MSE: 0.000081, MAE: 0.007080, R²: 0.0007
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.07414 | val 0.09330
  Epoch 020 - train 0.07453 | val 0.09131
  Regression -> MSE: 0.000311, MAE: 0.014498, R²: -0.0138
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.07101 | val 0.07761
  Epoch 020 - train 0.07304 | val 0.07831
  Regression -> MSE: 0.000098, MAE: 0.007262, R²: -0.0014
  Directional -> Accuracy: 0.5000, MCC: -0.1283, F1: 0.6452

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.08046 | val 0.08703
  Epoch 020 - train 0.07979 | val 0.09738
  Regression -> MSE: 0.000172, MAE: 0.009659, R²: -0.0001
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.07012 | val 0.09222
  Epoch 020 - train 0.06944 | val 0.09266
  Regression -> MSE: 0.000231, MAE: 0.011937, R²: -0.0346
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.07543 | val 0.08402
  Epoch 020 - train 0.07451 | val 0.08409
  Regression -> MSE: 0.000092, MAE: 0.007653, R²: -0.0021
  Directional -> Accuracy: 0.5439, MCC: 0.1810, F1: 0.6579

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.08344 | val 0.12049
  Epoch 020 - train 0.08233 | val 0.12380
  Regression -> MSE: 0.000168, MAE: 0.010305, R²: -0.0278
  Directional -> Accuracy: 0.4815, MCC: 0.0000, F1: 0.0000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.07316 | val 0.09722
  Epoch 020 - train 0.07192 | val 0.10429
  Regression -> MSE: 0.000117, MAE: 0.008933, R²: -0.0102
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.07975 | val 0.12045

[I 2026-02-23 03:46:43,822] Trial 230 finished with value: -0.011444425430770297 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.0, 'dropout': 0.1, 'batch_size': 32, 'learning_rate': 2.5464376188918086e-06, 'weight_decay': 7.258733290643692e-05, 'lr_patience': 7, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.10332492907467793, 'early_stopping_min_delta': 0.005659168430459875}. Best is trial 207 with value: -0.01137496405368131.

  Epoch 020 - train 0.07994 | val 0.13699
  Regression -> MSE: 0.000237, MAE: 0.012406, R²: 0.0009
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.12838 | val 0.16963
  Epoch 020 - train 0.12656 | val 0.16850
  Regression -> MSE: 0.000259, MAE: 0.012983, R²: -0.0472
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.13478 | val 0.12177
  Epoch 020 - train 0.12954 | val 0.13620
  Regression -> MSE: 0.000714, MAE: 0.019879, R²: -0.0437
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.13364 | val 0.20871
  Epoch 020 - train 0.13068 | val 0.21662
  Regression -> MSE: 0.000320, MAE: 0.014490, R²: -0.0299
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.10584 | val 0.10865
  Epoch 020 - train 0.10487 | val 0.11010
  Regression -> MSE: 0.000358, MAE: 0.014734, R²: -0.0248
  Directional -> Accuracy: 0.4400, MCC: -0.0761, F1: 0.1250

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.13325 | val 0.12757
  Epoch 020 - train 0.12860 | val 0.12873
  Regression -> MSE: 0.000209, MAE: 0.010159, R²: -0.0239
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.13233 | val 0.24715
  Epoch 020 - train 0.13216 | val 0.27228
  Regression -> MSE: 0.000604, MAE: 0.019090, R²: -0.0876
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.13179 | val 0.18796
  Epoch 020 - train 0.13802 | val 0.18636
  Regression -> MSE: 0.000248, MAE: 0.012326, R²: -0.0109
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.12464 | val 0.16448
  Epoch 020 - train 0.11697 | val 0.18048
  Regression -> MSE: 0.000618, MAE: 0.019651, R²: -0.0349
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.12356 | val 0.15362
  Epoch 020 - train 0.12438 | val 0.15569
  Regression -> MSE: 0.000389, MAE: 0.015986, R²: -0.0146
  Directional -> Accuracy: 0.3673, MCC: -0.3303, F1: 0.5373

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.13446 | val 0.24774
  Epoch 020 - train 0.12872 | val 0.24463
  Regression -> MSE: 0.000244, MAE: 0.012228, R²: -0.0105
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.11607 | val 0.17536
  Epoch 020 - train 0.11502 | val 0.17504
  Regression -> MSE: 0.000313, MAE: 0.013576, R²: -0.0074
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.13186 | val 0.15405
  Epoch 020 - train 0.13334 | val 0.15827
  Regression -> MSE: 0.000693, MAE: 0.020022, R²: -0.0237
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.12796 | val 0.12706
  Epoch 020 - train 0.12413 | val 0.12866
  Regression -> MSE: 0.000140, MAE: 0.009286, R²: -0.0129
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.11965 | val 0.16486
  Epoch 020 - train 0.11414 | val 0.16673
  Regression -> MSE: 0.000225, MAE: 0.010736, R²: -0.0013
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.12300 | val 0.25725
  Epoch 020 - train 0.12482 | val 0.28463
  Regression -> MSE: 0.000363, MAE: 0.016048, R²: -0.0011
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.13634 | val 0.14244
  Epoch 020 - train 0.13671 | val 0.14065
  Regression -> MSE: 0.000109, MAE: 0.007977, R²: -0.0116
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.12239 | val 0.21898
  Epoch 020 - train 0.12101 | val 0.22728
  Regression -> MSE: 0.000157, MAE: 0.009645, R²: -0.0054
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.12917 | val 0.12839
  Epoch 020 - train 0.13238 | val 0.12703
  Regression -> MSE: 0.000275, MAE: 0.012942, R²: -0.0096
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.11587 | val 0.16939
  Epoch 020 - train 0.11292 | val 0.16885
  Regression -> MSE: 0.000167, MAE: 0.009121, R²: -0.1154
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.13744 | val 0.19927
  Epoch 020 - train 0.14152 | val 0.19999
  Regression -> MSE: 0.000227, MAE: 0.010959, R²: -0.0045
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.13381 | val 0.16540
  Epoch 020 - train 0.13300 | val 0.16801
  Regression -> MSE: 0.000143, MAE: 0.008317, R²: -0.0007
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.12717 | val 0.14956
  Epoch 020 - train 0.12826 | val 0.15012
  Regression -> MSE: 0.000185, MAE: 0.010408, R²: -0.1217
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.13036 | val 0.14891
  Epoch 020 - train 0.13501 | val 0.15093
  Regression -> MSE: 0.000088, MAE: 0.007194, R²: -0.0313
  Directional -> Accuracy: 0.4138, MCC: -0.1111, F1: 0.0556

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.12180 | val 0.18706
  Epoch 020 - train 0.12172 | val 0.19556
  Regression -> MSE: 0.000212, MAE: 0.011221, R²: 0.0009
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.12663 | val 0.11705
  Epoch 020 - train 0.12229 | val 0.11768
  Regression -> MSE: 0.000093, MAE: 0.008118, R²: -0.0148
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.13754 | val 0.09737
  Epoch 020 - train 0.13642 | val 0.09676
  Regression -> MSE: 0.000103, MAE: 0.008720, R²: 0.0000
  Directional -> Accuracy: 0.5000, MCC: -0.1654, F1: 0.0800

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.12884 | val 0.12990
  Epoch 020 - train 0.12667 | val 0.16486
  Regression -> MSE: 0.000232, MAE: 0.012582, R²: -0.0025
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.12706 | val 0.14768
  Epoch 020 - train 0.12107 | val 0.14842
  Regression -> MSE: 0.000183, MAE: 0.008010, R²: -0.0988
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.13151 | val 0.10563
  Epoch 020 - train 0.13776 | val 0.10679
  Regression -> MSE: 0.000240, MAE: 0.011963, R²: -0.0158
  Directional -> Accuracy: 0.4634, MCC: 0.0000, F1: 0.0000

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.13972 | val 0.19533
  Epoch 020 - train 0.14193 | val 0.19577
  Regression -> MSE: 0.000231, MAE: 0.009871, R²: -0.0035
  Directional -> Accuracy: 0.4419, MCC: -0.1150, F1: 0.4545

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.13486 | val 0.15826
  Epoch 020 - train 0.13883 | val 0.14771
  Regression -> MSE: 0.000161, MAE: 0.009274, R²: -0.1947
  Directional -> Accuracy: 0.4884, MCC: 0.0323, F1: 0.2667

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.13375 | val 0.15436
  Epoch 020 - train 0.13771 | val 0.15485
  Regression -> MSE: 0.000194, MAE: 0.010454, R²: -0.0291
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.11501 | val 0.15368
  Epoch 020 - train 0.11661 | val 0.15319
  Regression -> MSE: 0.000261, MAE: 0.010591, R²: 0.0041
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.12215 | val 0.10572
  Epoch 020 - train 0.11946 | val 0.10651
  Regression -> MSE: 0.000169, MAE: 0.010377, R²: -0.0114
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.12099 | val 0.12686
  Epoch 020 - train 0.11765 | val 0.12742
  Regression -> MSE: 0.000183, MAE: 0.010426, R²: -0.0169
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.13339 | val 0.13047
  Epoch 020 - train 0.13208 | val 0.13169
  Regression -> MSE: 0.000343, MAE: 0.011776, R²: -0.0006
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.13672 | val 0.08401
  Epoch 020 - train 0.13690 | val 0.09053
  Regression -> MSE: 0.000115, MAE: 0.008337, R²: -0.0933
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.12845 | val 0.17026
  Epoch 020 - train 0.12891 | val 0.17186
  Regression -> MSE: 0.000218, MAE: 0.011280, R²: 0.0006
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.12578 | val 0.21641
  Epoch 020 - train 0.12728 | val 0.21866
  Regression -> MSE: 0.000081, MAE: 0.007024, R²: -0.0458
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.12113 | val 0.09777
  Epoch 020 - train 0.12100 | val 0.09503
  Regression -> MSE: 0.000317, MAE: 0.014373, R²: -0.0316
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.14135 | val 0.08092
  Epoch 020 - train 0.13509 | val 0.08487
  Regression -> MSE: 0.000253, MAE: 0.011462, R²: -0.0367
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.12136 | val 0.16116
  Epoch 020 - train 0.12618 | val 0.16078
  Regression -> MSE: 0.000082, MAE: 0.007069, R²: -0.0121
  Directional -> Accuracy: 0.4400, MCC: -0.1600, F1: 0.1923

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.14604 | val 0.17411
  Epoch 020 - train 0.14269 | val 0.21941
  Regression -> MSE: 0.000312, MAE: 0.014494, R²: -0.0160
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.12132 | val 0.13586
  Epoch 020 - train 0.11567 | val 0.13957
  Regression -> MSE: 0.000098, MAE: 0.007275, R²: -0.0015
  Directional -> Accuracy: 0.5000, MCC: 0.0321, F1: 0.4762

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.13121 | val 0.14538
  Epoch 020 - train 0.13689 | val 0.15020
  Regression -> MSE: 0.000172, MAE: 0.009617, R²: -0.0000
  Directional -> Accuracy: 0.5306, MCC: 0.0771, F1: 0.4889

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.11745 | val 0.14849
  Epoch 020 - train 0.11521 | val 0.14874
  Regression -> MSE: 0.000227, MAE: 0.011818, R²: -0.0197
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.12918 | val 0.14564
  Epoch 020 - train 0.12453 | val 0.14933
  Regression -> MSE: 0.000093, MAE: 0.007686, R²: -0.0077
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.13100 | val 0.19532
  Epoch 020 - train 0.12932 | val 0.20162
  Regression -> MSE: 0.000164, MAE: 0.010265, R²: -0.0030
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.12356 | val 0.16232
  Epoch 020 - train 0.12231 | val 0.17133
  Regression -> MSE: 0.000131, MAE: 0.009123, R²: -0.1286
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.12590 | val 0.17880

[I 2026-02-23 03:48:33,761] Trial 231 finished with value: -0.011465867827292541 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 32, 'learning_rate': 3.3515325845907043e-06, 'weight_decay': 5.4390364764319755e-05, 'lr_patience': 7, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.18881904070613367, 'early_stopping_min_delta': 0.005613609651102258}. Best is trial 207 with value: -0.01137496405368131.

  Epoch 020 - train 0.12635 | val 0.17999
  Regression -> MSE: 0.000239, MAE: 0.012331, R²: -0.0086
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.27495 | val 0.38419
  Epoch 020 - train 0.26993 | val 0.38592
  Regression -> MSE: 0.000252, MAE: 0.012738, R²: -0.0180
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.26544 | val 0.24983
  Epoch 020 - train 0.25625 | val 0.24155
  Regression -> MSE: 0.000725, MAE: 0.020177, R²: -0.0594
  Directional -> Accuracy: 0.4348, MCC: -0.0693, F1: 0.2778

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.28658 | val 0.47104
  Epoch 020 - train 0.28493 | val 0.47479
  Regression -> MSE: 0.000311, MAE: 0.014497, R²: -0.0040
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.21175 | val 0.26486
  Epoch 020 - train 0.21080 | val 0.27129
  Regression -> MSE: 0.000377, MAE: 0.015023, R²: -0.0791
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.25923 | val 0.27026
  Epoch 020 - train 0.25323 | val 0.26028
  Regression -> MSE: 0.000206, MAE: 0.010420, R²: -0.0099
  Directional -> Accuracy: 0.4706, MCC: -0.0119, F1: 0.0690

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.25625 | val 0.54524
  Epoch 020 - train 0.25616 | val 0.52609
  Regression -> MSE: 0.000673, MAE: 0.020273, R²: -0.2123
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.28160 | val 0.36400
  Epoch 020 - train 0.27955 | val 0.35882
  Regression -> MSE: 0.000249, MAE: 0.012329, R²: -0.0128
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.26393 | val 0.38233
  Epoch 020 - train 0.26345 | val 0.41131
  Regression -> MSE: 0.000631, MAE: 0.019908, R²: -0.0563
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.25243 | val 0.32021
  Epoch 020 - train 0.25039 | val 0.32320
  Regression -> MSE: 0.000421, MAE: 0.016364, R²: -0.0964
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.26989 | val 0.37474
  Epoch 020 - train 0.26253 | val 0.37609
  Regression -> MSE: 0.000246, MAE: 0.011657, R²: -0.0178
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.25494 | val 0.52113
  Epoch 020 - train 0.24779 | val 0.65655
  Regression -> MSE: 0.000312, MAE: 0.013823, R²: -0.0020
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.6301

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.27520 | val 0.33705
  Epoch 020 - train 0.26929 | val 0.35074
  Regression -> MSE: 0.000681, MAE: 0.019568, R²: -0.0049
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.26971 | val 0.34755
  Epoch 020 - train 0.26084 | val 0.53609
  Regression -> MSE: 0.000138, MAE: 0.009131, R²: -0.0005
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.23817 | val 0.40405
  Epoch 020 - train 0.23767 | val 0.41168
  Regression -> MSE: 0.000227, MAE: 0.010940, R²: -0.0107
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.25738 | val 0.59738
  Epoch 020 - train 0.25478 | val 0.62549
  Regression -> MSE: 0.000362, MAE: 0.016099, R²: -0.0003
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.31568 | val 0.40094
  Epoch 020 - train 0.31387 | val 0.41716
  Regression -> MSE: 0.000113, MAE: 0.007980, R²: -0.0440
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.26421 | val 0.44299
  Epoch 020 - train 0.26148 | val 0.44970
  Regression -> MSE: 0.000176, MAE: 0.010689, R²: -0.1266
  Directional -> Accuracy: 0.4237, MCC: -0.1903, F1: 0.5143

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.26708 | val 0.31745
  Epoch 020 - train 0.26753 | val 0.33140
  Regression -> MSE: 0.000276, MAE: 0.013242, R²: -0.0140
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.24237 | val 0.42261
  Epoch 020 - train 0.24220 | val 0.42689
  Regression -> MSE: 0.000163, MAE: 0.009016, R²: -0.0864
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.27036 | val 0.40106
  Epoch 020 - train 0.26280 | val 0.40011
  Regression -> MSE: 0.000247, MAE: 0.011702, R²: -0.0897
  Directional -> Accuracy: 0.4400, MCC: -0.1244, F1: 0.4750

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.27338 | val 0.38585
  Epoch 020 - train 0.27284 | val 0.55756
  Regression -> MSE: 0.000145, MAE: 0.008472, R²: -0.0146
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.25925 | val 0.31895
  Epoch 020 - train 0.25940 | val 0.31761
  Regression -> MSE: 0.000176, MAE: 0.010304, R²: -0.0625
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.28325 | val 0.35664
  Epoch 020 - train 0.27911 | val 0.37204
  Regression -> MSE: 0.000086, MAE: 0.007050, R²: -0.0047
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.25800 | val 0.36370
  Epoch 020 - train 0.25401 | val 0.37868
  Regression -> MSE: 0.000212, MAE: 0.011090, R²: 0.0005
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.25920 | val 0.28275
  Epoch 020 - train 0.25574 | val 0.28837
  Regression -> MSE: 0.000103, MAE: 0.008325, R²: -0.1197
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.27731 | val 0.22365
  Epoch 020 - train 0.27393 | val 0.26466
  Regression -> MSE: 0.000111, MAE: 0.009077, R²: -0.0780
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.27685 | val 0.26450
  Epoch 020 - train 0.27249 | val 0.27809
  Regression -> MSE: 0.000234, MAE: 0.012639, R²: -0.0100
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.26379 | val 0.31805
  Epoch 020 - train 0.25408 | val 0.31750
  Regression -> MSE: 0.000180, MAE: 0.007963, R²: -0.0824
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.28144 | val 0.21434
  Epoch 020 - train 0.27732 | val 0.24298
  Regression -> MSE: 0.000236, MAE: 0.011887, R²: 0.0006
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.27736 | val 0.47608
  Epoch 020 - train 0.27371 | val 0.47681
  Regression -> MSE: 0.000236, MAE: 0.010208, R²: -0.0237
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.27551 | val 0.31516
  Epoch 020 - train 0.27928 | val 0.31723
  Regression -> MSE: 0.000135, MAE: 0.008171, R²: -0.0010
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.26495 | val 0.36112
  Epoch 020 - train 0.26526 | val 0.37707
  Regression -> MSE: 0.000188, MAE: 0.010468, R²: 0.0009
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.23937 | val 0.42871
  Epoch 020 - train 0.23128 | val 0.44138
  Regression -> MSE: 0.000271, MAE: 0.010647, R²: -0.0348
  Directional -> Accuracy: 0.4384, MCC: -0.0209, F1: 0.0465

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.24926 | val 0.22769
  Epoch 020 - train 0.25630 | val 0.22935
  Regression -> MSE: 0.000167, MAE: 0.010373, R²: -0.0013
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.25088 | val 0.29504
  Epoch 020 - train 0.24403 | val 0.33855
  Regression -> MSE: 0.000182, MAE: 0.010387, R²: -0.0088
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.27229 | val 0.28383
  Epoch 020 - train 0.26378 | val 0.28196
  Regression -> MSE: 0.000345, MAE: 0.011725, R²: -0.0056
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.28352 | val 0.16004
  Epoch 020 - train 0.28108 | val 0.15920
  Regression -> MSE: 0.000113, MAE: 0.008320, R²: -0.0759
  Directional -> Accuracy: 0.5116, MCC: 0.0111, F1: 0.6316

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.28195 | val 0.41725
  Epoch 020 - train 0.27599 | val 0.43353
  Regression -> MSE: 0.000221, MAE: 0.011371, R²: -0.0107
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.28870 | val 0.49366
  Epoch 020 - train 0.27966 | val 0.49418
  Regression -> MSE: 0.000082, MAE: 0.007077, R²: -0.0601
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.25637 | val 0.19863
  Epoch 020 - train 0.26505 | val 0.20399
  Regression -> MSE: 0.000312, MAE: 0.014064, R²: -0.0138
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.26811 | val 0.15363
  Epoch 020 - train 0.27439 | val 0.16101
  Regression -> MSE: 0.000252, MAE: 0.011475, R²: -0.0345
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.26759 | val 0.35360
  Epoch 020 - train 0.26235 | val 0.34905
  Regression -> MSE: 0.000082, MAE: 0.007053, R²: -0.0169
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.27092 | val 0.35348
  Epoch 020 - train 0.27016 | val 0.38769
  Regression -> MSE: 0.000308, MAE: 0.014507, R²: -0.0038
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.27886 | val 0.29655
  Epoch 020 - train 0.27360 | val 0.28989
  Regression -> MSE: 0.000098, MAE: 0.007255, R²: -0.0013
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.29555 | val 0.33776
  Epoch 020 - train 0.29283 | val 0.34301
  Regression -> MSE: 0.000175, MAE: 0.010148, R²: -0.0179
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.24615 | val 0.31763
  Epoch 020 - train 0.24838 | val 0.32828
  Regression -> MSE: 0.000228, MAE: 0.011873, R²: -0.0226
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.28071 | val 0.33694
  Epoch 020 - train 0.27253 | val 0.34831
  Regression -> MSE: 0.000093, MAE: 0.007645, R²: -0.0056
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.30503 | val 0.44728
  Epoch 020 - train 0.30241 | val 0.46901
  Regression -> MSE: 0.000164, MAE: 0.010278, R²: -0.0024
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.27986 | val 0.33655
  Epoch 020 - train 0.28070 | val 0.34302
  Regression -> MSE: 0.000128, MAE: 0.009062, R²: -0.1043
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.27459 | val 0.44805

[I 2026-02-23 03:50:22,009] Trial 232 finished with value: -0.01153670437560462 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.0, 'dropout': 0.2, 'batch_size': 32, 'learning_rate': 3.6077659018910777e-06, 'weight_decay': 4.4062455169545825e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.4911627079753498, 'early_stopping_min_delta': 0.005891167634850218}. Best is trial 207 with value: -0.01137496405368131.

  Epoch 020 - train 0.27534 | val 0.47103
  Regression -> MSE: 0.000242, MAE: 0.012345, R²: -0.0200
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.12481 | val 0.20095
  Epoch 020 - train 0.12158 | val 0.19994
  Regression -> MSE: 0.000270, MAE: 0.013238, R²: -0.0894
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.11981 | val 0.10896
  Epoch 020 - train 0.11677 | val 0.10521
  Regression -> MSE: 0.000792, MAE: 0.020465, R²: -0.1574
  Directional -> Accuracy: 0.4348, MCC: -0.0870, F1: 0.3500

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.12834 | val 0.19295
  Epoch 020 - train 0.12667 | val 0.19911
  Regression -> MSE: 0.000313, MAE: 0.014522, R²: -0.0079
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.10937 | val 0.19033
  Epoch 020 - train 0.11085 | val 0.18679
  Regression -> MSE: 0.000352, MAE: 0.014582, R²: -0.0085
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.12105 | val 0.12047
  Epoch 020 - train 0.12152 | val 0.12107
  Regression -> MSE: 0.000204, MAE: 0.010145, R²: -0.0014
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.11518 | val 0.21533
  Epoch 020 - train 0.10967 | val 0.23037
  Regression -> MSE: 0.000562, MAE: 0.018201, R²: -0.0132
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.12280 | val 0.15273
  Epoch 020 - train 0.12536 | val 0.14853
  Regression -> MSE: 0.000247, MAE: 0.011961, R²: -0.0082
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.11761 | val 0.15499
  Epoch 020 - train 0.12062 | val 0.15367
  Regression -> MSE: 0.000631, MAE: 0.019929, R²: -0.0569
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.11162 | val 0.14173
  Epoch 020 - train 0.10890 | val 0.15714
  Regression -> MSE: 0.000395, MAE: 0.015975, R²: -0.0298
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.11262 | val 0.16280
  Epoch 020 - train 0.11418 | val 0.16520
  Regression -> MSE: 0.000242, MAE: 0.012090, R²: -0.0038
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.11712 | val 0.15600
  Epoch 020 - train 0.11190 | val 0.16223
  Regression -> MSE: 0.000349, MAE: 0.013895, R²: -0.1219
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.11294 | val 0.13975
  Epoch 020 - train 0.11800 | val 0.14198
  Regression -> MSE: 0.000677, MAE: 0.019453, R²: 0.0002
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.11736 | val 0.11451
  Epoch 020 - train 0.11080 | val 0.11793
  Regression -> MSE: 0.000139, MAE: 0.009253, R²: -0.0095
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.10908 | val 0.15579
  Epoch 020 - train 0.10994 | val 0.15475
  Regression -> MSE: 0.000225, MAE: 0.010714, R²: 0.0016
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.11182 | val 0.23533
  Epoch 020 - train 0.11182 | val 0.24220
  Regression -> MSE: 0.000370, MAE: 0.015923, R²: -0.0226
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.13169 | val 0.13534
  Epoch 020 - train 0.13199 | val 0.13558
  Regression -> MSE: 0.000108, MAE: 0.007999, R²: -0.0038
  Directional -> Accuracy: 0.4714, MCC: -0.1087, F1: 0.5843

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.11258 | val 0.20445
  Epoch 020 - train 0.11003 | val 0.21632
  Regression -> MSE: 0.000156, MAE: 0.009564, R²: 0.0003
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.12327 | val 0.11691
  Epoch 020 - train 0.12032 | val 0.11671
  Regression -> MSE: 0.000280, MAE: 0.013421, R²: -0.0303
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.11460 | val 0.16197
  Epoch 020 - train 0.11362 | val 0.16203
  Regression -> MSE: 0.000163, MAE: 0.009021, R²: -0.0885
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.12087 | val 0.20342
  Epoch 020 - train 0.11663 | val 0.20338
  Regression -> MSE: 0.000233, MAE: 0.010973, R²: -0.0319
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.12283 | val 0.14242
  Epoch 020 - train 0.12421 | val 0.14753
  Regression -> MSE: 0.000153, MAE: 0.008825, R²: -0.0686
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.11092 | val 0.14763
  Epoch 020 - train 0.10814 | val 0.14797
  Regression -> MSE: 0.000165, MAE: 0.010613, R²: 0.0013
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.12864 | val 0.15220
  Epoch 020 - train 0.12330 | val 0.15455
  Regression -> MSE: 0.000088, MAE: 0.007210, R²: -0.0343
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.11773 | val 0.20200
  Epoch 020 - train 0.11748 | val 0.20649
  Regression -> MSE: 0.000214, MAE: 0.011058, R²: -0.0097
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.11171 | val 0.10463
  Epoch 020 - train 0.10839 | val 0.10718
  Regression -> MSE: 0.000094, MAE: 0.008080, R²: -0.0240
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.11415 | val 0.09653
  Epoch 020 - train 0.11183 | val 0.09903
  Regression -> MSE: 0.000113, MAE: 0.009126, R²: -0.0968
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.12741 | val 0.11556
  Epoch 020 - train 0.12666 | val 0.12908
  Regression -> MSE: 0.000237, MAE: 0.012762, R²: -0.0259
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.11715 | val 0.13628
  Epoch 020 - train 0.11697 | val 0.13693
  Regression -> MSE: 0.000186, MAE: 0.008085, R²: -0.1200
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.12069 | val 0.10265
  Epoch 020 - train 0.12449 | val 0.10612
  Regression -> MSE: 0.000239, MAE: 0.011974, R²: -0.0104
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.11575 | val 0.18109
  Epoch 020 - train 0.11530 | val 0.17896
  Regression -> MSE: 0.000232, MAE: 0.009981, R²: -0.0062
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.11660 | val 0.13346
  Epoch 020 - train 0.12395 | val 0.13451
  Regression -> MSE: 0.000135, MAE: 0.008178, R²: 0.0023
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.11302 | val 0.14235
  Epoch 020 - train 0.11321 | val 0.14081
  Regression -> MSE: 0.000196, MAE: 0.010663, R²: -0.0408
  Directional -> Accuracy: 0.4800, MCC: -0.0276, F1: 0.4583

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.10664 | val 0.14139
  Epoch 020 - train 0.10168 | val 0.14093
  Regression -> MSE: 0.000273, MAE: 0.010721, R²: -0.0416
  Directional -> Accuracy: 0.4384, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.11902 | val 0.09612
  Epoch 020 - train 0.11697 | val 0.09714
  Regression -> MSE: 0.000167, MAE: 0.010371, R²: -0.0017
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.11875 | val 0.13630
  Epoch 020 - train 0.11741 | val 0.15541
  Regression -> MSE: 0.000186, MAE: 0.010554, R²: -0.0343
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.10891 | val 0.11035
  Epoch 020 - train 0.10908 | val 0.11062
  Regression -> MSE: 0.000344, MAE: 0.012039, R²: -0.0035
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.12293 | val 0.07680
  Epoch 020 - train 0.12413 | val 0.07951
  Regression -> MSE: 0.000126, MAE: 0.008486, R²: -0.1953
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.12250 | val 0.15928
  Epoch 020 - train 0.12343 | val 0.16082
  Regression -> MSE: 0.000219, MAE: 0.011306, R²: -0.0014
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.11741 | val 0.19240
  Epoch 020 - train 0.11623 | val 0.19747
  Regression -> MSE: 0.000085, MAE: 0.007219, R²: -0.1005
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.11593 | val 0.08822
  Epoch 020 - train 0.10955 | val 0.08601
  Regression -> MSE: 0.000315, MAE: 0.014242, R²: -0.0228
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.12531 | val 0.07071
  Epoch 020 - train 0.13019 | val 0.07625
  Regression -> MSE: 0.000247, MAE: 0.011518, R²: -0.0131
  Directional -> Accuracy: 0.6053, MCC: 0.3148, F1: 0.4444

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.11573 | val 0.14171
  Epoch 020 - train 0.11166 | val 0.14089
  Regression -> MSE: 0.000085, MAE: 0.007051, R²: -0.0547
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.11356 | val 0.14551
  Epoch 020 - train 0.11720 | val 0.15794
  Regression -> MSE: 0.000309, MAE: 0.014517, R²: -0.0063
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.11671 | val 0.12286
  Epoch 020 - train 0.11492 | val 0.12264
  Regression -> MSE: 0.000098, MAE: 0.007294, R²: 0.0004
  Directional -> Accuracy: 0.4318, MCC: 0.0000, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.12318 | val 0.13593
  Epoch 020 - train 0.12114 | val 0.13893
  Regression -> MSE: 0.000172, MAE: 0.009827, R²: -0.0025
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.10884 | val 0.12990
  Epoch 020 - train 0.11130 | val 0.13136
  Regression -> MSE: 0.000226, MAE: 0.011835, R²: -0.0144
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.11774 | val 0.12727
  Epoch 020 - train 0.11248 | val 0.13088
  Regression -> MSE: 0.000092, MAE: 0.007646, R²: 0.0022
  Directional -> Accuracy: 0.5263, MCC: 0.1217, F1: 0.6400

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.12577 | val 0.17780
  Epoch 020 - train 0.12342 | val 0.17925
  Regression -> MSE: 0.000164, MAE: 0.010254, R²: -0.0006
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.11730 | val 0.14157
  Epoch 020 - train 0.11317 | val 0.14823
  Regression -> MSE: 0.000124, MAE: 0.009021, R²: -0.0739
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.11820 | val 0.15944

[I 2026-02-23 03:52:12,555] Trial 233 finished with value: -0.01148256697544664 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 32, 'learning_rate': 2.7759577962842897e-06, 'weight_decay': 8.522225551018941e-05, 'lr_patience': 7, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.17087499978552514, 'early_stopping_min_delta': 0.0054854800331160195}. Best is trial 207 with value: -0.01137496405368131.

  Epoch 020 - train 0.11617 | val 0.16133
  Regression -> MSE: 0.000237, MAE: 0.012346, R²: -0.0003
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.09788 | val 0.12454
  Epoch 020 - train 0.09747 | val 0.12447
  Regression -> MSE: 0.000249, MAE: 0.012575, R²: -0.0038
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.09589 | val 0.09148
  Epoch 020 - train 0.09650 | val 0.09214
  Regression -> MSE: 0.000704, MAE: 0.019668, R²: -0.0278
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.09838 | val 0.16002
  Epoch 020 - train 0.09394 | val 0.16324
  Regression -> MSE: 0.000311, MAE: 0.014486, R²: -0.0026
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.09279 | val 0.10810
  Epoch 020 - train 0.08926 | val 0.10278
  Regression -> MSE: 0.000350, MAE: 0.014559, R²: -0.0031
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.09840 | val 0.10149
  Epoch 020 - train 0.09726 | val 0.10239
  Regression -> MSE: 0.000204, MAE: 0.010131, R²: -0.0006
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.09813 | val 0.17512
  Epoch 020 - train 0.10319 | val 0.17580
  Regression -> MSE: 0.000557, MAE: 0.018162, R²: -0.0036
  Directional -> Accuracy: 0.4894, MCC: 0.0000, F1: 0.6571

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.09649 | val 0.12382
  Epoch 020 - train 0.09882 | val 0.12468
  Regression -> MSE: 0.000245, MAE: 0.012214, R²: 0.0004
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.10310 | val 0.12031
  Epoch 020 - train 0.10009 | val 0.11566
  Regression -> MSE: 0.000611, MAE: 0.019490, R²: -0.0219
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.09520 | val 0.11200
  Epoch 020 - train 0.09673 | val 0.11290
  Regression -> MSE: 0.000409, MAE: 0.016226, R²: -0.0665
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.10062 | val 0.12637
  Epoch 020 - train 0.09689 | val 0.12458
  Regression -> MSE: 0.000242, MAE: 0.011988, R²: -0.0026
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.10593 | val 0.14058
  Epoch 020 - train 0.09887 | val 0.14339
  Regression -> MSE: 0.000327, MAE: 0.013643, R²: -0.0514
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.10020 | val 0.11754
  Epoch 020 - train 0.09989 | val 0.11885
  Regression -> MSE: 0.000678, MAE: 0.019509, R²: -0.0004
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.09948 | val 0.09667
  Epoch 020 - train 0.09770 | val 0.09842
  Regression -> MSE: 0.000147, MAE: 0.009576, R²: -0.0630
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.08868 | val 0.13789
  Epoch 020 - train 0.09268 | val 0.13940
  Regression -> MSE: 0.000227, MAE: 0.010936, R²: -0.0096
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.10268 | val 0.20829
  Epoch 020 - train 0.10234 | val 0.23011
  Regression -> MSE: 0.000371, MAE: 0.015936, R²: -0.0233
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.10837 | val 0.11460
  Epoch 020 - train 0.10722 | val 0.11375
  Regression -> MSE: 0.000110, MAE: 0.008210, R²: -0.0236
  Directional -> Accuracy: 0.4571, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.09485 | val 0.17827
  Epoch 020 - train 0.09732 | val 0.18353
  Regression -> MSE: 0.000156, MAE: 0.009528, R²: -0.0033
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.09814 | val 0.10672
  Epoch 020 - train 0.09813 | val 0.10602
  Regression -> MSE: 0.000281, MAE: 0.013493, R²: -0.0338
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.09066 | val 0.13759
  Epoch 020 - train 0.09023 | val 0.13646
  Regression -> MSE: 0.000159, MAE: 0.008864, R²: -0.0624
  Directional -> Accuracy: 0.5231, MCC: -0.0998, F1: 0.6667

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.10300 | val 0.13986
  Epoch 020 - train 0.10140 | val 0.13918
  Regression -> MSE: 0.000232, MAE: 0.010923, R²: -0.0233
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.10203 | val 0.12176
  Epoch 020 - train 0.10120 | val 0.12210
  Regression -> MSE: 0.000143, MAE: 0.008319, R²: 0.0008
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.09352 | val 0.11433
  Epoch 020 - train 0.08995 | val 0.11444
  Regression -> MSE: 0.000166, MAE: 0.010362, R²: -0.0056
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.10139 | val 0.12053
  Epoch 020 - train 0.10228 | val 0.11967
  Regression -> MSE: 0.000094, MAE: 0.007492, R²: -0.1072
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.09710 | val 0.22682
  Epoch 020 - train 0.09678 | val 0.22895
  Regression -> MSE: 0.000212, MAE: 0.011204, R²: -0.0031
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.09398 | val 0.09588
  Epoch 020 - train 0.09574 | val 0.09863
  Regression -> MSE: 0.000096, MAE: 0.008112, R²: -0.0383
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.09647 | val 0.08222
  Epoch 020 - train 0.09834 | val 0.08033
  Regression -> MSE: 0.000115, MAE: 0.009170, R²: -0.1117
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.09962 | val 0.09211
  Epoch 020 - train 0.10080 | val 0.09336
  Regression -> MSE: 0.000233, MAE: 0.012618, R²: -0.0078
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.09657 | val 0.10760
  Epoch 020 - train 0.09420 | val 0.10739
  Regression -> MSE: 0.000218, MAE: 0.009272, R²: -0.3092
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.10076 | val 0.08669
  Epoch 020 - train 0.10023 | val 0.10482
  Regression -> MSE: 0.000237, MAE: 0.011868, R²: -0.0016
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.09584 | val 0.15539
  Epoch 020 - train 0.09714 | val 0.15417
  Regression -> MSE: 0.000235, MAE: 0.010181, R²: -0.0192
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.10059 | val 0.12615
  Epoch 020 - train 0.10101 | val 0.12931
  Regression -> MSE: 0.000143, MAE: 0.008602, R²: -0.0595
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.10294 | val 0.12498
  Epoch 020 - train 0.10391 | val 0.12601
  Regression -> MSE: 0.000190, MAE: 0.010458, R²: -0.0077
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.08747 | val 0.11672
  Epoch 020 - train 0.09045 | val 0.11618
  Regression -> MSE: 0.000262, MAE: 0.010615, R²: -0.0009
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.09517 | val 0.08274
  Epoch 020 - train 0.09583 | val 0.08639
  Regression -> MSE: 0.000168, MAE: 0.010364, R²: -0.0053
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6122

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.08821 | val 0.10575
  Epoch 020 - train 0.08922 | val 0.12098
  Regression -> MSE: 0.000179, MAE: 0.010241, R²: 0.0047
  Directional -> Accuracy: 0.5682, MCC: 0.2145, F1: 0.6667

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.09270 | val 0.08990
  Epoch 020 - train 0.09181 | val 0.09012
  Regression -> MSE: 0.000342, MAE: 0.011901, R²: 0.0006
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.10578 | val 0.06469
  Epoch 020 - train 0.10381 | val 0.06699
  Regression -> MSE: 0.000111, MAE: 0.008313, R²: -0.0550
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.10396 | val 0.12814
  Epoch 020 - train 0.10155 | val 0.12908
  Regression -> MSE: 0.000222, MAE: 0.011392, R²: -0.0173
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.09261 | val 0.16873
  Epoch 020 - train 0.09261 | val 0.18278
  Regression -> MSE: 0.000088, MAE: 0.007329, R²: -0.1298
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.09589 | val 0.07735
  Epoch 020 - train 0.09112 | val 0.08464
  Regression -> MSE: 0.000315, MAE: 0.014230, R²: -0.0230
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.10530 | val 0.06077
  Epoch 020 - train 0.10201 | val 0.06181
  Regression -> MSE: 0.000253, MAE: 0.011476, R²: -0.0358
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.10018 | val 0.11914
  Epoch 020 - train 0.09778 | val 0.11940
  Regression -> MSE: 0.000083, MAE: 0.007039, R²: -0.0258
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.10086 | val 0.12820
  Epoch 020 - train 0.10003 | val 0.14789
  Regression -> MSE: 0.000308, MAE: 0.014473, R²: -0.0042
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.09166 | val 0.10549
  Epoch 020 - train 0.09238 | val 0.11184
  Regression -> MSE: 0.000098, MAE: 0.007243, R²: -0.0002
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.10612 | val 0.11328
  Epoch 020 - train 0.10571 | val 0.11441
  Regression -> MSE: 0.000174, MAE: 0.010062, R²: -0.0128
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.09580 | val 0.10797
  Epoch 020 - train 0.09629 | val 0.10720
  Regression -> MSE: 0.000227, MAE: 0.011828, R²: -0.0185
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.09668 | val 0.10687
  Epoch 020 - train 0.09446 | val 0.10605
  Regression -> MSE: 0.000097, MAE: 0.007962, R²: -0.0543
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.10320 | val 0.16147
  Epoch 020 - train 0.10533 | val 0.17077
  Regression -> MSE: 0.000165, MAE: 0.010294, R²: -0.0098
  Directional -> Accuracy: 0.4815, MCC: 0.0000, F1: 0.0000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.10004 | val 0.12982
  Epoch 020 - train 0.10002 | val 0.13301
  Regression -> MSE: 0.000117, MAE: 0.008924, R²: -0.0073
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.09995 | val 0.18649

[I 2026-02-23 03:54:02,933] Trial 234 finished with value: -0.011480477309569432 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 32, 'learning_rate': 3.896365362538652e-06, 'weight_decay': 5.828292841417732e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.14061424944928563, 'early_stopping_min_delta': 0.005704344058311181}. Best is trial 207 with value: -0.01137496405368131.

  Epoch 020 - train 0.09901 | val 0.20006
  Regression -> MSE: 0.000238, MAE: 0.012566, R²: -0.0044
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.15010 | val 0.23350
  Epoch 020 - train 0.15216 | val 0.23074
  Regression -> MSE: 0.000250, MAE: 0.012648, R²: -0.0097
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.15131 | val 0.15004
  Epoch 020 - train 0.14810 | val 0.14999
  Regression -> MSE: 0.000724, MAE: 0.020024, R²: -0.0574
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.15129 | val 0.25189
  Epoch 020 - train 0.15474 | val 0.25165
  Regression -> MSE: 0.000312, MAE: 0.014417, R²: -0.0045
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.12198 | val 0.31712
  Epoch 020 - train 0.12352 | val 0.30476
  Regression -> MSE: 0.000354, MAE: 0.014677, R²: -0.0141
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.15014 | val 0.16074
  Epoch 020 - train 0.14872 | val 0.16229
  Regression -> MSE: 0.000203, MAE: 0.010067, R²: 0.0050
  Directional -> Accuracy: 0.5882, MCC: 0.2986, F1: 0.4000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.14238 | val 0.28645
  Epoch 020 - train 0.13985 | val 0.28678
  Regression -> MSE: 0.000575, MAE: 0.018478, R²: -0.0351
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.15235 | val 0.20390
  Epoch 020 - train 0.14945 | val 0.20430
  Regression -> MSE: 0.000246, MAE: 0.011902, R²: -0.0037
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.15700 | val 0.17066
  Epoch 020 - train 0.15998 | val 0.15986
  Regression -> MSE: 0.000604, MAE: 0.019593, R²: -0.0102
  Directional -> Accuracy: 0.4773, MCC: -0.1601, F1: 0.2069

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.14515 | val 0.18747
  Epoch 020 - train 0.14961 | val 0.18766
  Regression -> MSE: 0.000386, MAE: 0.016108, R²: -0.0056
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.16276 | val 0.24707
  Epoch 020 - train 0.16152 | val 0.24425
  Regression -> MSE: 0.000252, MAE: 0.011661, R²: -0.0449
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.15281 | val 0.20505
  Epoch 020 - train 0.15449 | val 0.20549
  Regression -> MSE: 0.000328, MAE: 0.013633, R²: -0.0545
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.16415 | val 0.22153
  Epoch 020 - train 0.16322 | val 0.22058
  Regression -> MSE: 0.000686, MAE: 0.019720, R²: -0.0125
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.15808 | val 0.28591
  Epoch 020 - train 0.15873 | val 0.27770
  Regression -> MSE: 0.000140, MAE: 0.008998, R²: -0.0143
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.14042 | val 0.19637
  Epoch 020 - train 0.14101 | val 0.19558
  Regression -> MSE: 0.000237, MAE: 0.011003, R²: -0.0530
  Directional -> Accuracy: 0.4918, MCC: -0.0043, F1: 0.1143

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.15533 | val 0.31809
  Epoch 020 - train 0.15065 | val 0.31604
  Regression -> MSE: 0.000362, MAE: 0.016202, R²: -0.0008
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.16151 | val 0.15834
  Epoch 020 - train 0.15495 | val 0.15851
  Regression -> MSE: 0.000108, MAE: 0.007943, R²: 0.0008
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.15727 | val 0.23588
  Epoch 020 - train 0.15359 | val 0.23506
  Regression -> MSE: 0.000162, MAE: 0.009842, R²: -0.0408
  Directional -> Accuracy: 0.4915, MCC: -0.1079, F1: 0.6053

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.15375 | val 0.16670
  Epoch 020 - train 0.15406 | val 0.16561
  Regression -> MSE: 0.000298, MAE: 0.014099, R²: -0.0965
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.13568 | val 0.20367
  Epoch 020 - train 0.13544 | val 0.20293
  Regression -> MSE: 0.000164, MAE: 0.009050, R²: -0.0985
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.15402 | val 0.21888
  Epoch 020 - train 0.14760 | val 0.21654
  Regression -> MSE: 0.000235, MAE: 0.010927, R²: -0.0371
  Directional -> Accuracy: 0.5733, MCC: 0.2544, F1: 0.4286

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.15987 | val 0.18809
  Epoch 020 - train 0.15576 | val 0.18748
  Regression -> MSE: 0.000144, MAE: 0.008317, R²: -0.0013
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.14794 | val 0.19182
  Epoch 020 - train 0.14606 | val 0.19231
  Regression -> MSE: 0.000166, MAE: 0.010380, R²: -0.0071
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.15384 | val 0.19312
  Epoch 020 - train 0.16014 | val 0.19396
  Regression -> MSE: 0.000087, MAE: 0.007134, R²: -0.0174
  Directional -> Accuracy: 0.5690, MCC: 0.1441, F1: 0.5902

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.15806 | val 0.19580
  Epoch 020 - train 0.15201 | val 0.19676
  Regression -> MSE: 0.000216, MAE: 0.011034, R²: -0.0211
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.14431 | val 0.13013
  Epoch 020 - train 0.14141 | val 0.12772
  Regression -> MSE: 0.000137, MAE: 0.009844, R²: -0.4883
  Directional -> Accuracy: 0.3929, MCC: -0.2386, F1: 0.4688

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.14725 | val 0.13630
  Epoch 020 - train 0.15715 | val 0.13605
  Regression -> MSE: 0.000112, MAE: 0.009082, R²: -0.0812
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.15856 | val 0.15855
  Epoch 020 - train 0.15310 | val 0.15550
  Regression -> MSE: 0.000233, MAE: 0.012604, R²: -0.0056
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.15580 | val 0.18596
  Epoch 020 - train 0.14856 | val 0.18579
  Regression -> MSE: 0.000179, MAE: 0.007953, R²: -0.0763
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.14812 | val 0.15288
  Epoch 020 - train 0.14351 | val 0.17985
  Regression -> MSE: 0.000238, MAE: 0.011897, R²: -0.0042
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.15647 | val 0.23106
  Epoch 020 - train 0.15813 | val 0.23135
  Regression -> MSE: 0.000230, MAE: 0.009854, R²: 0.0008
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.15727 | val 0.18936
  Epoch 020 - train 0.14821 | val 0.19255
  Regression -> MSE: 0.000135, MAE: 0.008184, R²: -0.0037
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.15293 | val 0.19232
  Epoch 020 - train 0.15203 | val 0.19239
  Regression -> MSE: 0.000191, MAE: 0.010388, R²: -0.0166
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.13589 | val 0.18156
  Epoch 020 - train 0.13829 | val 0.18205
  Regression -> MSE: 0.000276, MAE: 0.010825, R²: -0.0558
  Directional -> Accuracy: 0.4932, MCC: 0.0797, F1: 0.3273

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.14678 | val 0.14402
  Epoch 020 - train 0.14843 | val 0.17337
  Regression -> MSE: 0.000168, MAE: 0.010367, R²: -0.0092
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.13949 | val 0.14943
  Epoch 020 - train 0.13834 | val 0.14996
  Regression -> MSE: 0.000177, MAE: 0.010296, R²: 0.0182
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.14731 | val 0.14524
  Epoch 020 - train 0.14206 | val 0.14276
  Regression -> MSE: 0.000344, MAE: 0.011767, R²: -0.0047
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.16797 | val 0.09885
  Epoch 020 - train 0.16352 | val 0.09830
  Regression -> MSE: 0.000118, MAE: 0.008338, R²: -0.1216
  Directional -> Accuracy: 0.5116, MCC: 0.0397, F1: 0.3636

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.15981 | val 0.20533
  Epoch 020 - train 0.15533 | val 0.20495
  Regression -> MSE: 0.000221, MAE: 0.011374, R²: -0.0116
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.15077 | val 0.27993
  Epoch 020 - train 0.15084 | val 0.28051
  Regression -> MSE: 0.000091, MAE: 0.007447, R²: -0.1660
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.15385 | val 0.14513
  Epoch 020 - train 0.15109 | val 0.14884
  Regression -> MSE: 0.000328, MAE: 0.014947, R²: -0.0676
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.15813 | val 0.08956
  Epoch 020 - train 0.15447 | val 0.09388
  Regression -> MSE: 0.000249, MAE: 0.011503, R²: -0.0226
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.14902 | val 0.18849
  Epoch 020 - train 0.14750 | val 0.18951
  Regression -> MSE: 0.000081, MAE: 0.007091, R²: -0.0011
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.15305 | val 0.18754
  Epoch 020 - train 0.15525 | val 0.18641
  Regression -> MSE: 0.000307, MAE: 0.014495, R²: -0.0000
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.14356 | val 0.16950
  Epoch 020 - train 0.13842 | val 0.17302
  Regression -> MSE: 0.000100, MAE: 0.007131, R²: -0.0196
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.16562 | val 0.20477
  Epoch 020 - train 0.16155 | val 0.21796
  Regression -> MSE: 0.000172, MAE: 0.009514, R²: -0.0031
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.14662 | val 0.17748
  Epoch 020 - train 0.13900 | val 0.17769
  Regression -> MSE: 0.000224, MAE: 0.011759, R²: -0.0060
  Directional -> Accuracy: 0.5000, MCC: -0.0731, F1: 0.6410

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.15710 | val 0.16649
  Epoch 020 - train 0.15327 | val 0.16498
  Regression -> MSE: 0.000092, MAE: 0.007646, R²: 0.0024
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.15791 | val 0.23722
  Epoch 020 - train 0.15545 | val 0.23681
  Regression -> MSE: 0.000167, MAE: 0.010310, R²: -0.0218
  Directional -> Accuracy: 0.4815, MCC: 0.0000, F1: 0.0000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.15181 | val 0.20070
  Epoch 020 - train 0.14382 | val 0.20356
  Regression -> MSE: 0.000124, MAE: 0.009020, R²: -0.0726
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.15394 | val 0.23464

[I 2026-02-23 03:56:55,953] Trial 235 finished with value: -0.0114771593613211 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 16, 'learning_rate': 2.5056263750350433e-06, 'weight_decay': 5.1145058385170084e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.23236645535397488, 'early_stopping_min_delta': 0.006046313908292613}. Best is trial 207 with value: -0.01137496405368131.

  Epoch 020 - train 0.15161 | val 0.23433
  Regression -> MSE: 0.000237, MAE: 0.012364, R²: 0.0002
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.11795 | val 0.16719
  Epoch 020 - train 0.11946 | val 0.16427
  Regression -> MSE: 0.000249, MAE: 0.012598, R²: -0.0043
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.11028 | val 0.12279
  Epoch 020 - train 0.11579 | val 0.13041
  Regression -> MSE: 0.000720, MAE: 0.019968, R²: -0.0521
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.12716 | val 0.20688
  Epoch 020 - train 0.12308 | val 0.20604
  Regression -> MSE: 0.000312, MAE: 0.014499, R²: -0.0061
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.09851 | val 0.16657
  Epoch 020 - train 0.09854 | val 0.22227
  Regression -> MSE: 0.000380, MAE: 0.015083, R²: -0.0869
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.11785 | val 0.12384
  Epoch 020 - train 0.11407 | val 0.14192
  Regression -> MSE: 0.000198, MAE: 0.009825, R²: 0.0256
  Directional -> Accuracy: 0.7059, MCC: 0.4354, F1: 0.6809

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.11274 | val 0.23381
  Epoch 020 - train 0.11232 | val 0.24437
  Regression -> MSE: 0.000556, MAE: 0.018138, R²: -0.0017
  Directional -> Accuracy: 0.5319, MCC: 0.1194, F1: 0.6562

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.12285 | val 0.15864
  Epoch 020 - train 0.12015 | val 0.16419
  Regression -> MSE: 0.000250, MAE: 0.011939, R²: -0.0177
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.12376 | val 0.16149
  Epoch 020 - train 0.11326 | val 0.22908
  Regression -> MSE: 0.000606, MAE: 0.019356, R²: -0.0143
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.10944 | val 0.15138
  Epoch 020 - train 0.10860 | val 0.15485
  Regression -> MSE: 0.000396, MAE: 0.015885, R²: -0.0318
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.11963 | val 0.18956
  Epoch 020 - train 0.11441 | val 0.17621
  Regression -> MSE: 0.000242, MAE: 0.012027, R²: -0.0022
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.10551 | val 0.22832
  Epoch 020 - train 0.10730 | val 0.28714
  Regression -> MSE: 0.000312, MAE: 0.013633, R²: -0.0028
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.12273 | val 0.15370
  Epoch 020 - train 0.11681 | val 0.16794
  Regression -> MSE: 0.000675, MAE: 0.019427, R²: 0.0036
  Directional -> Accuracy: 0.6724, MCC: 0.3450, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.11371 | val 0.17613
  Epoch 020 - train 0.11111 | val 0.20969
  Regression -> MSE: 0.000139, MAE: 0.009010, R²: -0.0069
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.10893 | val 0.17197
  Epoch 020 - train 0.10373 | val 0.16172
  Regression -> MSE: 0.000223, MAE: 0.010472, R²: 0.0091
  Directional -> Accuracy: 0.6066, MCC: 0.2334, F1: 0.6842

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.11837 | val 0.24526
  Epoch 020 - train 0.11665 | val 0.25323
  Regression -> MSE: 0.000354, MAE: 0.015865, R²: 0.0229
  Directional -> Accuracy: 0.5000, MCC: 0.0740, F1: 0.6176

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.12378 | val 0.13165
  Epoch 020 - train 0.12028 | val 0.13874
  Regression -> MSE: 0.000110, MAE: 0.007954, R²: -0.0206
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.11479 | val 0.25113
  Epoch 020 - train 0.11839 | val 0.30931
  Regression -> MSE: 0.000156, MAE: 0.009558, R²: -0.0033
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.12436 | val 0.16741
  Epoch 020 - train 0.12300 | val 0.16501
  Regression -> MSE: 0.000288, MAE: 0.013758, R²: -0.0575
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.10966 | val 0.16739
  Epoch 020 - train 0.10438 | val 0.16756
  Regression -> MSE: 0.000152, MAE: 0.008735, R²: -0.0179
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.12226 | val 0.18396
  Epoch 020 - train 0.11805 | val 0.18436
  Regression -> MSE: 0.000238, MAE: 0.011027, R²: -0.0500
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.11888 | val 0.15903
  Epoch 020 - train 0.11740 | val 0.16488
  Regression -> MSE: 0.000144, MAE: 0.008328, R²: -0.0038
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.11562 | val 0.16785
  Epoch 020 - train 0.11055 | val 0.17103
  Regression -> MSE: 0.000178, MAE: 0.010298, R²: -0.0796
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.12533 | val 0.15350
  Epoch 020 - train 0.12158 | val 0.16405
  Regression -> MSE: 0.000088, MAE: 0.007222, R²: -0.0369
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.11863 | val 0.15885
  Epoch 020 - train 0.11577 | val 0.19060
  Regression -> MSE: 0.000212, MAE: 0.011124, R²: -0.0016
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.10611 | val 0.10324
  Epoch 020 - train 0.10338 | val 0.09882
  Regression -> MSE: 0.000092, MAE: 0.007750, R²: 0.0034
  Directional -> Accuracy: 0.5179, MCC: 0.0909, F1: 0.4255

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.12002 | val 0.10202
  Epoch 020 - train 0.11748 | val 0.10598
  Regression -> MSE: 0.000109, MAE: 0.008788, R²: -0.0529
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.12481 | val 0.12863
  Epoch 020 - train 0.12190 | val 0.16059
  Regression -> MSE: 0.000235, MAE: 0.012666, R²: -0.0140
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.11911 | val 0.15059
  Epoch 020 - train 0.11094 | val 0.14843
  Regression -> MSE: 0.000186, MAE: 0.007890, R²: -0.1196
  Directional -> Accuracy: 0.5614, MCC: 0.1898, F1: 0.4898

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.12714 | val 0.11141
  Epoch 020 - train 0.12668 | val 0.10629
  Regression -> MSE: 0.000229, MAE: 0.011773, R²: 0.0323
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.11899 | val 0.20557
  Epoch 020 - train 0.11266 | val 0.21224
  Regression -> MSE: 0.000233, MAE: 0.010046, R²: -0.0114
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.12516 | val 0.16187
  Epoch 020 - train 0.11545 | val 0.16645
  Regression -> MSE: 0.000142, MAE: 0.008576, R²: -0.0551
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.11615 | val 0.16389
  Epoch 020 - train 0.11121 | val 0.17562
  Regression -> MSE: 0.000191, MAE: 0.010383, R²: -0.0124
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.10685 | val 0.14986
  Epoch 020 - train 0.10282 | val 0.17043
  Regression -> MSE: 0.000272, MAE: 0.010742, R²: -0.0398
  Directional -> Accuracy: 0.5342, MCC: 0.1465, F1: 0.4333

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.11371 | val 0.10791
  Epoch 020 - train 0.10814 | val 0.12157
  Regression -> MSE: 0.000167, MAE: 0.010367, R²: 0.0003
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.11286 | val 0.14010
  Epoch 020 - train 0.10533 | val 0.16087
  Regression -> MSE: 0.000182, MAE: 0.010409, R²: -0.0127
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.11497 | val 0.12331
  Epoch 020 - train 0.10687 | val 0.12689
  Regression -> MSE: 0.000341, MAE: 0.011931, R²: 0.0034
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.12374 | val 0.08121
  Epoch 020 - train 0.11830 | val 0.08821
  Regression -> MSE: 0.000117, MAE: 0.008302, R²: -0.1108
  Directional -> Accuracy: 0.6744, MCC: 0.3810, F1: 0.6111

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.11967 | val 0.17443
  Epoch 020 - train 0.11826 | val 0.17520
  Regression -> MSE: 0.000224, MAE: 0.011442, R²: -0.0243
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.11829 | val 0.23485
  Epoch 020 - train 0.11533 | val 0.31198
  Regression -> MSE: 0.000088, MAE: 0.007343, R²: -0.1327
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.11723 | val 0.09750
  Epoch 020 - train 0.11338 | val 0.09304
  Regression -> MSE: 0.000664, MAE: 0.022337, R²: -1.1594
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.13165 | val 0.07980
  Epoch 020 - train 0.11927 | val 0.08852
  Regression -> MSE: 0.000247, MAE: 0.011537, R²: -0.0150
  Directional -> Accuracy: 0.5000, MCC: 0.0326, F1: 0.3448

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.10876 | val 0.15939
  Epoch 020 - train 0.10385 | val 0.17379
  Regression -> MSE: 0.000081, MAE: 0.007124, R²: -0.0083
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.11853 | val 0.15333
  Epoch 020 - train 0.11588 | val 0.20410
  Regression -> MSE: 0.000306, MAE: 0.014479, R²: 0.0017
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.11686 | val 0.13697
  Epoch 020 - train 0.11376 | val 0.13834
  Regression -> MSE: 0.000098, MAE: 0.007255, R²: 0.0002
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.12675 | val 0.15225
  Epoch 020 - train 0.12148 | val 0.16996
  Regression -> MSE: 0.000172, MAE: 0.009561, R²: -0.0014
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.11333 | val 0.14337
  Epoch 020 - train 0.11011 | val 0.14510
  Regression -> MSE: 0.000224, MAE: 0.011801, R²: -0.0033
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.11627 | val 0.15521
  Epoch 020 - train 0.11014 | val 0.17658
  Regression -> MSE: 0.000094, MAE: 0.007750, R²: -0.0217
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.12455 | val 0.21895
  Epoch 020 - train 0.12018 | val 0.30166
  Regression -> MSE: 0.000164, MAE: 0.010268, R²: -0.0018
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.11790 | val 0.15397
  Epoch 020 - train 0.11035 | val 0.17179
  Regression -> MSE: 0.000122, MAE: 0.008985, R²: -0.0566
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.12652 | val 0.21531

[I 2026-02-23 03:58:42,390] Trial 236 finished with value: -0.011553199676074625 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 32, 'learning_rate': 0.00015262273027737204, 'weight_decay': 3.915708088172763e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.19025680590548735, 'early_stopping_min_delta': 0.005216571430370681}. Best is trial 207 with value: -0.01137496405368131.

  Epoch 020 - train 0.11899 | val 0.23499
  Regression -> MSE: 0.000237, MAE: 0.012425, R²: 0.0007
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.07335 | val 0.09069
  Epoch 020 - train 0.07304 | val 0.09047
  Regression -> MSE: 0.000248, MAE: 0.012518, R²: 0.0001
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.07777 | val 0.06651
  Epoch 020 - train 0.07687 | val 0.07526
  Regression -> MSE: 0.000689, MAE: 0.019443, R²: -0.0070
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.07490 | val 0.11475
  Epoch 020 - train 0.07197 | val 0.11760
  Regression -> MSE: 0.000311, MAE: 0.014383, R²: -0.0013
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.06220 | val 0.06139
  Epoch 020 - train 0.06286 | val 0.06182
  Regression -> MSE: 0.000375, MAE: 0.015009, R²: -0.0743
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.07540 | val 0.07344
  Epoch 020 - train 0.07553 | val 0.07644
  Regression -> MSE: 0.000204, MAE: 0.010143, R²: -0.0031
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.07116 | val 0.12929
  Epoch 020 - train 0.06873 | val 0.12982
  Regression -> MSE: 0.000571, MAE: 0.018384, R²: -0.0286
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.07503 | val 0.08939
  Epoch 020 - train 0.07436 | val 0.08992
  Regression -> MSE: 0.000253, MAE: 0.011982, R²: -0.0308
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.07210 | val 0.08967
  Epoch 020 - train 0.07405 | val 0.09409
  Regression -> MSE: 0.000613, MAE: 0.019524, R²: -0.0252
  Directional -> Accuracy: 0.5455, MCC: 0.0760, F1: 0.4737

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.07191 | val 0.08813
  Epoch 020 - train 0.07125 | val 0.08731
  Regression -> MSE: 0.000386, MAE: 0.016108, R²: -0.0063
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.07190 | val 0.11929
  Epoch 020 - train 0.07117 | val 0.11925
  Regression -> MSE: 0.000243, MAE: 0.011674, R²: -0.0074
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.07339 | val 0.09579
  Epoch 020 - train 0.07423 | val 0.10191
  Regression -> MSE: 0.000353, MAE: 0.013858, R²: -0.1342
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.07766 | val 0.08992
  Epoch 020 - train 0.07547 | val 0.09228
  Regression -> MSE: 0.000681, MAE: 0.019562, R²: -0.0060
  Directional -> Accuracy: 0.4655, MCC: -0.1890, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.07770 | val 0.08951
  Epoch 020 - train 0.07514 | val 0.10392
  Regression -> MSE: 0.000139, MAE: 0.008987, R²: -0.0032
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.06680 | val 0.11028
  Epoch 020 - train 0.06746 | val 0.11866
  Regression -> MSE: 0.000227, MAE: 0.010728, R²: -0.0084
  Directional -> Accuracy: 0.4918, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.07520 | val 0.14618
  Epoch 020 - train 0.07527 | val 0.15001
  Regression -> MSE: 0.000363, MAE: 0.016219, R²: -0.0022
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.07529 | val 0.08115
  Epoch 020 - train 0.07482 | val 0.08191
  Regression -> MSE: 0.000108, MAE: 0.007993, R²: -0.0032
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.06968 | val 0.11725
  Epoch 020 - train 0.06782 | val 0.11972
  Regression -> MSE: 0.000156, MAE: 0.009714, R²: -0.0033
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.07480 | val 0.07332
  Epoch 020 - train 0.07586 | val 0.07444
  Regression -> MSE: 0.000273, MAE: 0.013087, R²: -0.0027
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.06803 | val 0.09986
  Epoch 020 - train 0.06851 | val 0.10035
  Regression -> MSE: 0.000163, MAE: 0.009005, R²: -0.0879
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.07419 | val 0.09897
  Epoch 020 - train 0.07300 | val 0.09874
  Regression -> MSE: 0.000234, MAE: 0.010959, R²: -0.0354
  Directional -> Accuracy: 0.4267, MCC: -0.1731, F1: 0.5057

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.07052 | val 0.09118
  Epoch 020 - train 0.07069 | val 0.09602
  Regression -> MSE: 0.000148, MAE: 0.008592, R²: -0.0331
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.06685 | val 0.08644
  Epoch 020 - train 0.06735 | val 0.08674
  Regression -> MSE: 0.000167, MAE: 0.010310, R²: -0.0107
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.07520 | val 0.08449
  Epoch 020 - train 0.07475 | val 0.08467
  Regression -> MSE: 0.000087, MAE: 0.007147, R²: -0.0207
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.07074 | val 0.08955
  Epoch 020 - train 0.07241 | val 0.09063
  Regression -> MSE: 0.000212, MAE: 0.011084, R²: -0.0024
  Directional -> Accuracy: 0.5000, MCC: 0.0055, F1: 0.5075

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.06683 | val 0.06462
  Epoch 020 - train 0.06701 | val 0.06449
  Regression -> MSE: 0.000094, MAE: 0.008112, R²: -0.0216
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.08362 | val 0.05609
  Epoch 020 - train 0.08148 | val 0.05822
  Regression -> MSE: 0.000103, MAE: 0.008675, R²: -0.0007
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.07855 | val 0.07233
  Epoch 020 - train 0.07799 | val 0.08693
  Regression -> MSE: 0.000231, MAE: 0.012524, R²: -0.0000
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.07293 | val 0.08955
  Epoch 020 - train 0.07178 | val 0.09071
  Regression -> MSE: 0.000171, MAE: 0.007823, R²: -0.0299
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.07858 | val 0.06137
  Epoch 020 - train 0.07622 | val 0.06482
  Regression -> MSE: 0.000237, MAE: 0.011873, R²: -0.0016
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.07131 | val 0.11248
  Epoch 020 - train 0.07220 | val 0.11918
  Regression -> MSE: 0.000230, MAE: 0.009865, R²: 0.0021
  Directional -> Accuracy: 0.4884, MCC: -0.0051, F1: 0.6452

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.07583 | val 0.08807
  Epoch 020 - train 0.07647 | val 0.08996
  Regression -> MSE: 0.000138, MAE: 0.008359, R²: -0.0251
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.07180 | val 0.08938
  Epoch 020 - train 0.07357 | val 0.09036
  Regression -> MSE: 0.000196, MAE: 0.010540, R²: -0.0391
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.06394 | val 0.08374
  Epoch 020 - train 0.06633 | val 0.08356
  Regression -> MSE: 0.000262, MAE: 0.010508, R²: 0.0001
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.06291 | val 0.06059
  Epoch 020 - train 0.06584 | val 0.06084
  Regression -> MSE: 0.000167, MAE: 0.010367, R²: -0.0016
  Directional -> Accuracy: 0.4737, MCC: -0.0555, F1: 0.5455

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.06650 | val 0.07397
  Epoch 020 - train 0.06763 | val 0.07586
  Regression -> MSE: 0.000185, MAE: 0.010536, R²: -0.0287
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.07160 | val 0.06794
  Epoch 020 - train 0.07239 | val 0.06770
  Regression -> MSE: 0.000345, MAE: 0.012060, R²: -0.0065
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.07728 | val 0.05063
  Epoch 020 - train 0.07595 | val 0.05616
  Regression -> MSE: 0.000111, MAE: 0.008334, R²: -0.0594
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.07854 | val 0.10289
  Epoch 020 - train 0.07870 | val 0.10620
  Regression -> MSE: 0.000218, MAE: 0.011288, R²: 0.0011
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.07132 | val 0.11761
  Epoch 020 - train 0.07543 | val 0.12745
  Regression -> MSE: 0.000089, MAE: 0.007381, R²: -0.1457
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.07302 | val 0.05775
  Epoch 020 - train 0.06850 | val 0.05501
  Regression -> MSE: 0.000322, MAE: 0.014637, R²: -0.0482
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.07189 | val 0.04773
  Epoch 020 - train 0.07338 | val 0.04760
  Regression -> MSE: 0.000258, MAE: 0.011479, R²: -0.0588
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.07514 | val 0.08639
  Epoch 020 - train 0.07416 | val 0.08648
  Regression -> MSE: 0.000083, MAE: 0.007060, R²: -0.0300
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.07305 | val 0.08704
  Epoch 020 - train 0.07462 | val 0.08983
  Regression -> MSE: 0.000308, MAE: 0.014507, R²: -0.0026
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.06796 | val 0.08313
  Epoch 020 - train 0.06763 | val 0.08518
  Regression -> MSE: 0.000101, MAE: 0.007104, R²: -0.0284
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.07269 | val 0.08280
  Epoch 020 - train 0.07687 | val 0.08174
  Regression -> MSE: 0.000173, MAE: 0.009505, R²: -0.0045
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.06756 | val 0.10771
  Epoch 020 - train 0.06753 | val 0.11877
  Regression -> MSE: 0.000224, MAE: 0.011711, R²: -0.0026
  Directional -> Accuracy: 0.6071, MCC: 0.2563, F1: 0.7250

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.07398 | val 0.07772
  Epoch 020 - train 0.07318 | val 0.07852
  Regression -> MSE: 0.000093, MAE: 0.007638, R²: -0.0045
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.07681 | val 0.11108
  Epoch 020 - train 0.07729 | val 0.11390
  Regression -> MSE: 0.000167, MAE: 0.010311, R²: -0.0188
  Directional -> Accuracy: 0.4815, MCC: 0.0000, F1: 0.0000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.07098 | val 0.09028
  Epoch 020 - train 0.07046 | val 0.09257
  Regression -> MSE: 0.000118, MAE: 0.008949, R²: -0.0163
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.07695 | val 0.09938

[I 2026-02-23 04:00:29,950] Trial 237 finished with value: -0.011398438945815548 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 32, 'learning_rate': 1.800859774159284e-06, 'weight_decay': 6.858998789956581e-05, 'lr_patience': 7, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.10128119447537835, 'early_stopping_min_delta': 0.005878092621697523}. Best is trial 207 with value: -0.01137496405368131.

  Epoch 020 - train 0.07744 | val 0.10031
  Regression -> MSE: 0.000245, MAE: 0.012367, R²: -0.0349
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.07494 | val 0.10100
  Epoch 020 - train 0.07524 | val 0.10075
  Regression -> MSE: 0.000251, MAE: 0.012700, R²: -0.0144
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.07524 | val 0.07087
  Epoch 020 - train 0.07459 | val 0.06806
  Regression -> MSE: 0.000688, MAE: 0.019370, R²: -0.0045
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.07911 | val 0.12372
  Epoch 020 - train 0.07738 | val 0.12775
  Regression -> MSE: 0.000312, MAE: 0.014488, R²: -0.0046
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.06478 | val 0.08288
  Epoch 020 - train 0.06598 | val 0.08447
  Regression -> MSE: 0.000390, MAE: 0.015258, R²: -0.1159
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.07931 | val 0.07903
  Epoch 020 - train 0.07776 | val 0.08013
  Regression -> MSE: 0.000204, MAE: 0.010222, R²: -0.0040
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.07287 | val 0.13425
  Epoch 020 - train 0.07291 | val 0.13524
  Regression -> MSE: 0.000560, MAE: 0.018173, R²: -0.0086
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.07858 | val 0.09661
  Epoch 020 - train 0.08047 | val 0.09699
  Regression -> MSE: 0.000249, MAE: 0.011936, R²: -0.0132
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.07570 | val 0.10128
  Epoch 020 - train 0.07535 | val 0.10344
  Regression -> MSE: 0.000637, MAE: 0.020033, R²: -0.0664
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.07518 | val 0.09570
  Epoch 020 - train 0.07445 | val 0.09515
  Regression -> MSE: 0.000384, MAE: 0.016192, R²: -0.0004
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.07269 | val 0.09912
  Epoch 020 - train 0.07408 | val 0.09926
  Regression -> MSE: 0.000247, MAE: 0.011622, R²: -0.0220
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.06850 | val 0.11625
  Epoch 020 - train 0.06864 | val 0.12301
  Regression -> MSE: 0.000311, MAE: 0.013746, R²: 0.0011
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.6301

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.08234 | val 0.09913
  Epoch 020 - train 0.08104 | val 0.10530
  Regression -> MSE: 0.000682, MAE: 0.019643, R²: -0.0063
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.07678 | val 0.08157
  Epoch 020 - train 0.07766 | val 0.08410
  Regression -> MSE: 0.000139, MAE: 0.009028, R²: -0.0052
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.06871 | val 0.09476
  Epoch 020 - train 0.06746 | val 0.09558
  Regression -> MSE: 0.000223, MAE: 0.010685, R²: 0.0096
  Directional -> Accuracy: 0.5902, MCC: 0.1925, F1: 0.5283

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.07251 | val 0.15570
  Epoch 020 - train 0.07262 | val 0.16954
  Regression -> MSE: 0.000365, MAE: 0.015979, R²: -0.0082
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.08034 | val 0.07961
  Epoch 020 - train 0.07750 | val 0.08094
  Regression -> MSE: 0.000110, MAE: 0.008202, R²: -0.0208
  Directional -> Accuracy: 0.4571, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.07348 | val 0.11983
  Epoch 020 - train 0.07064 | val 0.12097
  Regression -> MSE: 0.000157, MAE: 0.009855, R²: -0.0100
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.07736 | val 0.08984
  Epoch 020 - train 0.07568 | val 0.08886
  Regression -> MSE: 0.000275, MAE: 0.012907, R²: -0.0108
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.07571 | val 0.11459
  Epoch 020 - train 0.07423 | val 0.11773
  Regression -> MSE: 0.000154, MAE: 0.008750, R²: -0.0276
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.07988 | val 0.11119
  Epoch 020 - train 0.08046 | val 0.11057
  Regression -> MSE: 0.000248, MAE: 0.011285, R²: -0.0965
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.07668 | val 0.09982
  Epoch 020 - train 0.07776 | val 0.11444
  Regression -> MSE: 0.000151, MAE: 0.008710, R²: -0.0505
  Directional -> Accuracy: 0.5208, MCC: 0.0759, F1: 0.5490

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.07536 | val 0.09660
  Epoch 020 - train 0.07505 | val 0.09716
  Regression -> MSE: 0.000166, MAE: 0.010681, R²: -0.0054
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.08031 | val 0.09309
  Epoch 020 - train 0.08045 | val 0.09340
  Regression -> MSE: 0.000090, MAE: 0.007308, R²: -0.0553
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.07961 | val 0.09533
  Epoch 020 - train 0.07856 | val 0.09675
  Regression -> MSE: 0.000212, MAE: 0.011236, R²: -0.0026
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.07824 | val 0.07259
  Epoch 020 - train 0.07715 | val 0.07412
  Regression -> MSE: 0.000094, MAE: 0.008114, R²: -0.0243
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.07737 | val 0.05940
  Epoch 020 - train 0.07741 | val 0.06098
  Regression -> MSE: 0.000105, MAE: 0.008834, R²: -0.0162
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.07952 | val 0.07095
  Epoch 020 - train 0.07747 | val 0.07658
  Regression -> MSE: 0.000237, MAE: 0.012736, R²: -0.0230
  Directional -> Accuracy: 0.5581, MCC: 0.1872, F1: 0.5128

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.07594 | val 0.09347
  Epoch 020 - train 0.07268 | val 0.09534
  Regression -> MSE: 0.000178, MAE: 0.007919, R²: -0.0687
  Directional -> Accuracy: 0.4386, MCC: -0.0639, F1: 0.2727

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.07678 | val 0.06474
  Epoch 020 - train 0.07798 | val 0.06782
  Regression -> MSE: 0.000238, MAE: 0.011926, R²: -0.0070
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.07842 | val 0.12052
  Epoch 020 - train 0.07238 | val 0.12556
  Regression -> MSE: 0.000237, MAE: 0.010288, R²: -0.0299
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.08237 | val 0.09495
  Epoch 020 - train 0.08215 | val 0.09578
  Regression -> MSE: 0.000141, MAE: 0.008466, R²: -0.0417
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.07792 | val 0.09491
  Epoch 020 - train 0.07679 | val 0.09569
  Regression -> MSE: 0.000189, MAE: 0.010438, R²: -0.0031
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.06795 | val 0.08299
  Epoch 020 - train 0.06874 | val 0.08327
  Regression -> MSE: 0.000264, MAE: 0.010526, R²: -0.0096
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.07247 | val 0.06334
  Epoch 020 - train 0.07203 | val 0.07122
  Regression -> MSE: 0.000165, MAE: 0.010354, R²: 0.0085
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.06787 | val 0.07726
  Epoch 020 - train 0.06809 | val 0.07678
  Regression -> MSE: 0.000185, MAE: 0.010530, R²: -0.0275
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.07368 | val 0.07040
  Epoch 020 - train 0.07260 | val 0.07043
  Regression -> MSE: 0.000345, MAE: 0.012058, R²: -0.0063
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.08438 | val 0.04988
  Epoch 020 - train 0.08134 | val 0.04942
  Regression -> MSE: 0.000120, MAE: 0.008389, R²: -0.1396
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.07527 | val 0.10255
  Epoch 020 - train 0.07549 | val 0.10507
  Regression -> MSE: 0.000219, MAE: 0.011311, R²: -0.0010
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.07306 | val 0.12374
  Epoch 020 - train 0.07242 | val 0.12328
  Regression -> MSE: 0.000092, MAE: 0.007482, R²: -0.1789
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.07779 | val 0.06374
  Epoch 020 - train 0.07437 | val 0.06716
  Regression -> MSE: 0.000338, MAE: 0.015299, R²: -0.0974
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.07958 | val 0.04632
  Epoch 020 - train 0.08282 | val 0.04578
  Regression -> MSE: 0.000246, MAE: 0.011561, R²: -0.0089
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.0000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.07804 | val 0.10223
  Epoch 020 - train 0.07883 | val 0.10077
  Regression -> MSE: 0.000081, MAE: 0.007106, R²: -0.0075
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.07449 | val 0.09274
  Epoch 020 - train 0.07419 | val 0.09353
  Regression -> MSE: 0.000308, MAE: 0.014479, R²: -0.0051
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.06961 | val 0.08917
  Epoch 020 - train 0.07406 | val 0.09381
  Regression -> MSE: 0.000102, MAE: 0.007108, R²: -0.0391
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.08437 | val 0.09340
  Epoch 020 - train 0.08254 | val 0.10892
  Regression -> MSE: 0.000172, MAE: 0.009510, R²: -0.0012
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.07221 | val 0.08851
  Epoch 020 - train 0.07126 | val 0.09064
  Regression -> MSE: 0.000223, MAE: 0.011790, R²: 0.0000
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.07469 | val 0.08604
  Epoch 020 - train 0.07571 | val 0.08660
  Regression -> MSE: 0.000095, MAE: 0.007810, R²: -0.0280
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.08089 | val 0.11236
  Epoch 020 - train 0.07971 | val 0.11272
  Regression -> MSE: 0.000164, MAE: 0.010268, R²: -0.0023
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.07643 | val 0.09703
  Epoch 020 - train 0.07570 | val 0.10026
  Regression -> MSE: 0.000120, MAE: 0.008979, R²: -0.0365
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.08250 | val 0.10523

[I 2026-02-23 04:02:16,947] Trial 238 finished with value: -0.011475955064778894 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 32, 'learning_rate': 2.025788759209431e-06, 'weight_decay': 2.912667078296721e-07, 'lr_patience': 7, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.10617317820781871, 'early_stopping_min_delta': 0.005912874274860741}. Best is trial 207 with value: -0.01137496405368131.

  Epoch 020 - train 0.07966 | val 0.10615
  Regression -> MSE: 0.000238, MAE: 0.012510, R²: -0.0035
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.07193 | val 0.09307
  Epoch 020 - train 0.07142 | val 0.09318
  Regression -> MSE: 0.000248, MAE: 0.012576, R²: -0.0030
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.07480 | val 0.06781
  Epoch 020 - train 0.07380 | val 0.07138
  Regression -> MSE: 0.000724, MAE: 0.019989, R²: -0.0578
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.08322 | val 0.12140
  Epoch 020 - train 0.08167 | val 0.12352
  Regression -> MSE: 0.000342, MAE: 0.014821, R²: -0.1036
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.06225 | val 0.09370
  Epoch 020 - train 0.05928 | val 0.09368
  Regression -> MSE: 0.000371, MAE: 0.014933, R²: -0.0618
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.07119 | val 0.08219
  Epoch 020 - train 0.07198 | val 0.09170
  Regression -> MSE: 0.000206, MAE: 0.010324, R²: -0.0096
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.07119 | val 0.13837
  Epoch 020 - train 0.06768 | val 0.17166
  Regression -> MSE: 0.000588, MAE: 0.018713, R²: -0.0587
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.07587 | val 0.08957
  Epoch 020 - train 0.07429 | val 0.08955
  Regression -> MSE: 0.000250, MAE: 0.011958, R²: -0.0204
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.07053 | val 0.09007
  Epoch 020 - train 0.06900 | val 0.09298
  Regression -> MSE: 0.000620, MAE: 0.019680, R²: -0.0377
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.06633 | val 0.08671
  Epoch 020 - train 0.06930 | val 0.08756
  Regression -> MSE: 0.000391, MAE: 0.015984, R²: -0.0196
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.07153 | val 0.09309
  Epoch 020 - train 0.07117 | val 0.09392
  Regression -> MSE: 0.000244, MAE: 0.011651, R²: -0.0119
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.06852 | val 0.09451
  Epoch 020 - train 0.06934 | val 0.10308
  Regression -> MSE: 0.000316, MAE: 0.013584, R²: -0.0159
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.07458 | val 0.08798
  Epoch 020 - train 0.07362 | val 0.08812
  Regression -> MSE: 0.000693, MAE: 0.020002, R²: -0.0229
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.07135 | val 0.07119
  Epoch 020 - train 0.07413 | val 0.08165
  Regression -> MSE: 0.000139, MAE: 0.009197, R²: -0.0042
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.06653 | val 0.09002
  Epoch 020 - train 0.06625 | val 0.09008
  Regression -> MSE: 0.000228, MAE: 0.010767, R²: -0.0134
  Directional -> Accuracy: 0.4918, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.07949 | val 0.14754
  Epoch 020 - train 0.07671 | val 0.15830
  Regression -> MSE: 0.000367, MAE: 0.016360, R²: -0.0128
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.07472 | val 0.07483
  Epoch 020 - train 0.07597 | val 0.07492
  Regression -> MSE: 0.000108, MAE: 0.008018, R²: 0.0003
  Directional -> Accuracy: 0.4000, MCC: -0.2683, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.07227 | val 0.12431
  Epoch 020 - train 0.07078 | val 0.12845
  Regression -> MSE: 0.000160, MAE: 0.010037, R²: -0.0249
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.07327 | val 0.07216
  Epoch 020 - train 0.07154 | val 0.07244
  Regression -> MSE: 0.000279, MAE: 0.013367, R²: -0.0238
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.06623 | val 0.09735
  Epoch 020 - train 0.06680 | val 0.09690
  Regression -> MSE: 0.000150, MAE: 0.008756, R²: -0.0055
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.07283 | val 0.10491
  Epoch 020 - train 0.07157 | val 0.10575
  Regression -> MSE: 0.000235, MAE: 0.010977, R²: -0.0393
  Directional -> Accuracy: 0.4400, MCC: -0.0875, F1: 0.0455

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.07236 | val 0.09382
  Epoch 020 - train 0.07277 | val 0.10394
  Regression -> MSE: 0.000156, MAE: 0.008971, R²: -0.0911
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.07244 | val 0.09202
  Epoch 020 - train 0.07268 | val 0.09155
  Regression -> MSE: 0.000174, MAE: 0.010298, R²: -0.0526
  Directional -> Accuracy: 0.5152, MCC: 0.1240, F1: 0.0588

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.07320 | val 0.08260
  Epoch 020 - train 0.07514 | val 0.08452
  Regression -> MSE: 0.000087, MAE: 0.007141, R²: -0.0196
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.07302 | val 0.09240
  Epoch 020 - train 0.07215 | val 0.09009
  Regression -> MSE: 0.000212, MAE: 0.011109, R²: -0.0017
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.07023 | val 0.06449
  Epoch 020 - train 0.06835 | val 0.06444
  Regression -> MSE: 0.000103, MAE: 0.008307, R²: -0.1222
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.07096 | val 0.05912
  Epoch 020 - train 0.07145 | val 0.06600
  Regression -> MSE: 0.000107, MAE: 0.008915, R²: -0.0348
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.07975 | val 0.07060
  Epoch 020 - train 0.07592 | val 0.07997
  Regression -> MSE: 0.000236, MAE: 0.012699, R²: -0.0186
  Directional -> Accuracy: 0.6047, MCC: 0.1428, F1: 0.7119

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.06890 | val 0.08391
  Epoch 020 - train 0.06955 | val 0.08421
  Regression -> MSE: 0.000179, MAE: 0.007950, R²: -0.0758
  Directional -> Accuracy: 0.4737, MCC: -0.0339, F1: 0.4643

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.07312 | val 0.06175
  Epoch 020 - train 0.07176 | val 0.06217
  Regression -> MSE: 0.000236, MAE: 0.011856, R²: 0.0004
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.07228 | val 0.10904
  Epoch 020 - train 0.07075 | val 0.10909
  Regression -> MSE: 0.000231, MAE: 0.009900, R²: -0.0043
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.07315 | val 0.08409
  Epoch 020 - train 0.07464 | val 0.08210
  Regression -> MSE: 0.000137, MAE: 0.008285, R²: -0.0133
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.07873 | val 0.09244
  Epoch 020 - train 0.07875 | val 0.09255
  Regression -> MSE: 0.000188, MAE: 0.010515, R²: -0.0002
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.06511 | val 0.08420
  Epoch 020 - train 0.06474 | val 0.08412
  Regression -> MSE: 0.000268, MAE: 0.010597, R²: -0.0251
  Directional -> Accuracy: 0.5616, MCC: 0.0436, F1: 0.6981

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.06838 | val 0.06021
  Epoch 020 - train 0.06875 | val 0.06071
  Regression -> MSE: 0.000169, MAE: 0.010362, R²: -0.0122
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.06823 | val 0.07002
  Epoch 020 - train 0.06763 | val 0.07000
  Regression -> MSE: 0.000179, MAE: 0.010239, R²: 0.0033
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.07402 | val 0.07322
  Epoch 020 - train 0.07342 | val 0.07333
  Regression -> MSE: 0.000347, MAE: 0.012158, R²: -0.0133
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.07828 | val 0.05071
  Epoch 020 - train 0.07987 | val 0.05950
  Regression -> MSE: 0.000110, MAE: 0.008317, R²: -0.0465
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.07186 | val 0.09463
  Epoch 020 - train 0.07281 | val 0.09550
  Regression -> MSE: 0.000219, MAE: 0.011337, R²: -0.0038
  Directional -> Accuracy: 0.5263, MCC: 0.0101, F1: 0.0690

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.07479 | val 0.11803
  Epoch 020 - train 0.07385 | val 0.12112
  Regression -> MSE: 0.000095, MAE: 0.007621, R²: -0.2289
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.06915 | val 0.05838
  Epoch 020 - train 0.06916 | val 0.05532
  Regression -> MSE: 0.000328, MAE: 0.014911, R²: -0.0659
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.08068 | val 0.04805
  Epoch 020 - train 0.07795 | val 0.04508
  Regression -> MSE: 0.000264, MAE: 0.011548, R²: -0.0846
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.06970 | val 0.08721
  Epoch 020 - train 0.06956 | val 0.08684
  Regression -> MSE: 0.000082, MAE: 0.007068, R²: -0.0103
  Directional -> Accuracy: 0.4400, MCC: -0.1402, F1: 0.2759

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.07300 | val 0.08956
  Epoch 020 - train 0.07171 | val 0.11221
  Regression -> MSE: 0.000310, MAE: 0.014523, R²: -0.0101
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.06713 | val 0.08277
  Epoch 020 - train 0.06733 | val 0.08242
  Regression -> MSE: 0.000100, MAE: 0.007115, R²: -0.0224
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.07761 | val 0.08108
  Epoch 020 - train 0.07831 | val 0.08116
  Regression -> MSE: 0.000172, MAE: 0.009782, R²: -0.0022
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.06623 | val 0.08030
  Epoch 020 - train 0.06545 | val 0.08429
  Regression -> MSE: 0.000227, MAE: 0.011827, R²: -0.0188
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.06922 | val 0.07477
  Epoch 020 - train 0.06969 | val 0.07408
  Regression -> MSE: 0.000094, MAE: 0.007714, R²: -0.0136
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.07429 | val 0.10779
  Epoch 020 - train 0.07473 | val 0.10839
  Regression -> MSE: 0.000164, MAE: 0.010254, R²: -0.0001
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.07077 | val 0.09141
  Epoch 020 - train 0.06889 | val 0.09337
  Regression -> MSE: 0.000119, MAE: 0.008954, R²: -0.0247
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.07320 | val 0.11192

[I 2026-02-23 04:04:05,822] Trial 239 finished with value: -0.011486909258425222 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 32, 'learning_rate': 3.188215086397494e-06, 'weight_decay': 0.00010716101020395548, 'lr_patience': 7, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.10094935113235604, 'early_stopping_min_delta': 0.006234002386978488}. Best is trial 207 with value: -0.01137496405368131.

  Epoch 020 - train 0.07114 | val 0.12005
  Regression -> MSE: 0.000237, MAE: 0.012378, R²: 0.0006
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.11291 | val 0.15499
  Epoch 020 - train 0.11452 | val 0.15175
  Regression -> MSE: 0.000249, MAE: 0.012483, R²: -0.0041
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.10550 | val 0.10082
  Epoch 020 - train 0.10357 | val 0.10078
  Regression -> MSE: 0.000700, MAE: 0.019719, R²: -0.0222
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.10727 | val 0.17953
  Epoch 020 - train 0.10732 | val 0.18154
  Regression -> MSE: 0.000310, MAE: 0.014447, R²: 0.0001
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.08501 | val 0.10158
  Epoch 020 - train 0.08527 | val 0.10189
  Regression -> MSE: 0.000370, MAE: 0.014945, R²: -0.0592
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.10100 | val 0.09900
  Epoch 020 - train 0.10185 | val 0.10003
  Regression -> MSE: 0.000208, MAE: 0.010214, R²: -0.0232
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.09116 | val 0.19381
  Epoch 020 - train 0.09344 | val 0.19734
  Regression -> MSE: 0.000561, MAE: 0.018207, R²: -0.0103
  Directional -> Accuracy: 0.4681, MCC: -0.0619, F1: 0.4898

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.10420 | val 0.12945
  Epoch 020 - train 0.10324 | val 0.12912
  Regression -> MSE: 0.000250, MAE: 0.011898, R²: -0.0205
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.09633 | val 0.11893
  Epoch 020 - train 0.09315 | val 0.12160
  Regression -> MSE: 0.000606, MAE: 0.019341, R²: -0.0137
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.10055 | val 0.12523
  Epoch 020 - train 0.09897 | val 0.12571
  Regression -> MSE: 0.000389, MAE: 0.015914, R²: -0.0135
  Directional -> Accuracy: 0.5918, MCC: 0.1751, F1: 0.5455

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.09892 | val 0.14027
  Epoch 020 - train 0.09697 | val 0.13831
  Regression -> MSE: 0.000244, MAE: 0.011692, R²: -0.0096
  Directional -> Accuracy: 0.5571, MCC: 0.0123, F1: 0.2051

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.09049 | val 0.14429
  Epoch 020 - train 0.09256 | val 0.14542
  Regression -> MSE: 0.000319, MAE: 0.013605, R²: -0.0265
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.10134 | val 0.12665
  Epoch 020 - train 0.10366 | val 0.12683
  Regression -> MSE: 0.000677, MAE: 0.019448, R²: -0.0002
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.09859 | val 0.09697
  Epoch 020 - train 0.09595 | val 0.09731
  Regression -> MSE: 0.000144, MAE: 0.009465, R²: -0.0430
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.09287 | val 0.12463
  Epoch 020 - train 0.09307 | val 0.12486
  Regression -> MSE: 0.000232, MAE: 0.010959, R²: -0.0310
  Directional -> Accuracy: 0.4918, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.09875 | val 0.20374
  Epoch 020 - train 0.09895 | val 0.20436
  Regression -> MSE: 0.000362, MAE: 0.016069, R²: 0.0005
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.10180 | val 0.11307
  Epoch 020 - train 0.10457 | val 0.11274
  Regression -> MSE: 0.000111, MAE: 0.008094, R²: -0.0287
  Directional -> Accuracy: 0.5286, MCC: -0.0191, F1: 0.6733

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.10163 | val 0.18814
  Epoch 020 - train 0.10032 | val 0.19318
  Regression -> MSE: 0.000160, MAE: 0.010091, R²: -0.0250
  Directional -> Accuracy: 0.5424, MCC: 0.2653, F1: 0.4706

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.10083 | val 0.11374
  Epoch 020 - train 0.10023 | val 0.11378
  Regression -> MSE: 0.000272, MAE: 0.013070, R²: 0.0019
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.09654 | val 0.16939
  Epoch 020 - train 0.09547 | val 0.16662
  Regression -> MSE: 0.000154, MAE: 0.008973, R²: -0.0267
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.10800 | val 0.14177
  Epoch 020 - train 0.10985 | val 0.14089
  Regression -> MSE: 0.000242, MAE: 0.011130, R²: -0.0707
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.10515 | val 0.21135
  Epoch 020 - train 0.10433 | val 0.21631
  Regression -> MSE: 0.000174, MAE: 0.009721, R²: -0.2129
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.09157 | val 0.12036
  Epoch 020 - train 0.09333 | val 0.12047
  Regression -> MSE: 0.000171, MAE: 0.010229, R²: -0.0364
  Directional -> Accuracy: 0.6212, MCC: 0.2481, F1: 0.6575

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.10720 | val 0.12698
  Epoch 020 - train 0.10491 | val 0.12676
  Regression -> MSE: 0.000086, MAE: 0.007164, R²: -0.0147
  Directional -> Accuracy: 0.5862, MCC: 0.1952, F1: 0.5862

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.10361 | val 0.13030
  Epoch 020 - train 0.10237 | val 0.12578
  Regression -> MSE: 0.000215, MAE: 0.011501, R²: -0.0168
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.09276 | val 0.09151
  Epoch 020 - train 0.09513 | val 0.09082
  Regression -> MSE: 0.000092, MAE: 0.007997, R²: -0.0047
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.09681 | val 0.09136
  Epoch 020 - train 0.10200 | val 0.10868
  Regression -> MSE: 0.000107, MAE: 0.008942, R²: -0.0409
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.10513 | val 0.10211
  Epoch 020 - train 0.10789 | val 0.10241
  Regression -> MSE: 0.000243, MAE: 0.012934, R²: -0.0498
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.09827 | val 0.11181
  Epoch 020 - train 0.09796 | val 0.11172
  Regression -> MSE: 0.000179, MAE: 0.008006, R²: -0.0785
  Directional -> Accuracy: 0.4211, MCC: -0.2054, F1: 0.5217

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.10187 | val 0.08522
  Epoch 020 - train 0.09902 | val 0.08637
  Regression -> MSE: 0.000236, MAE: 0.011911, R²: 0.0005
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.10915 | val 0.16142
  Epoch 020 - train 0.10754 | val 0.16801
  Regression -> MSE: 0.000228, MAE: 0.009855, R²: 0.0096
  Directional -> Accuracy: 0.5349, MCC: 0.0783, F1: 0.5833

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.09855 | val 0.13859
  Epoch 020 - train 0.10165 | val 0.13917
  Regression -> MSE: 0.000142, MAE: 0.008497, R²: -0.0515
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.10340 | val 0.12679
  Epoch 020 - train 0.10003 | val 0.12691
  Regression -> MSE: 0.000200, MAE: 0.010693, R²: -0.0634
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.09418 | val 0.11913
  Epoch 020 - train 0.08934 | val 0.12022
  Regression -> MSE: 0.000266, MAE: 0.010559, R²: -0.0147
  Directional -> Accuracy: 0.5479, MCC: 0.1054, F1: 0.5600

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.09097 | val 0.08252
  Epoch 020 - train 0.09115 | val 0.08542
  Regression -> MSE: 0.000167, MAE: 0.010381, R²: 0.0001
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.09039 | val 0.10336
  Epoch 020 - train 0.09041 | val 0.10395
  Regression -> MSE: 0.000182, MAE: 0.010413, R²: -0.0101
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.09704 | val 0.09855
  Epoch 020 - train 0.09608 | val 0.09805
  Regression -> MSE: 0.000348, MAE: 0.011798, R²: -0.0157
  Directional -> Accuracy: 0.5224, MCC: -0.0619, F1: 0.6596

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.10585 | val 0.08727
  Epoch 020 - train 0.10572 | val 0.10014
  Regression -> MSE: 0.000109, MAE: 0.008379, R²: -0.0349
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.11084 | val 0.13405
  Epoch 020 - train 0.10650 | val 0.13368
  Regression -> MSE: 0.000219, MAE: 0.011313, R²: -0.0009
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.10222 | val 0.17237
  Epoch 020 - train 0.10396 | val 0.17245
  Regression -> MSE: 0.000093, MAE: 0.007524, R²: -0.1987
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.09970 | val 0.08120
  Epoch 020 - train 0.09934 | val 0.08336
  Regression -> MSE: 0.000314, MAE: 0.014166, R²: -0.0196
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.10864 | val 0.07018
  Epoch 020 - train 0.10812 | val 0.07657
  Regression -> MSE: 0.000257, MAE: 0.011452, R²: -0.0532
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.09763 | val 0.11488
  Epoch 020 - train 0.09604 | val 0.11472
  Regression -> MSE: 0.000083, MAE: 0.007020, R²: -0.0253
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.10199 | val 0.16421
  Epoch 020 - train 0.10312 | val 0.18815
  Regression -> MSE: 0.000305, MAE: 0.014453, R²: 0.0074
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.09422 | val 0.10944
  Epoch 020 - train 0.09760 | val 0.11374
  Regression -> MSE: 0.000098, MAE: 0.007162, R²: -0.0018
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.11042 | val 0.13055
  Epoch 020 - train 0.10680 | val 0.13666
  Regression -> MSE: 0.000177, MAE: 0.010253, R²: -0.0272
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.09497 | val 0.12521
  Epoch 020 - train 0.09446 | val 0.12698
  Regression -> MSE: 0.000225, MAE: 0.011863, R²: -0.0104
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.09715 | val 0.10863
  Epoch 020 - train 0.09757 | val 0.10860
  Regression -> MSE: 0.000096, MAE: 0.007838, R²: -0.0352
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.10733 | val 0.15385
  Epoch 020 - train 0.10625 | val 0.15450
  Regression -> MSE: 0.000169, MAE: 0.010338, R²: -0.0309
  Directional -> Accuracy: 0.4815, MCC: 0.0000, F1: 0.0000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.09996 | val 0.15027
  Epoch 020 - train 0.09620 | val 0.14951
  Regression -> MSE: 0.000116, MAE: 0.008928, R²: -0.0040
  Directional -> Accuracy: 0.5536, MCC: 0.1995, F1: 0.6988

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.10658 | val 0.25232

[I 2026-02-23 04:04:55,351] Trial 240 finished with value: -0.011468877067661523 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 32, 'learning_rate': 4.61165647413164e-06, 'weight_decay': 7.59937851627726e-05, 'lr_patience': 7, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.14404102183220507, 'early_stopping_min_delta': 0.00537022814594989}. Best is trial 207 with value: -0.01137496405368131.

  Epoch 020 - train 0.10361 | val 0.25456
  Regression -> MSE: 0.000235, MAE: 0.012389, R²: 0.0087
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.11322 | val 0.15657
  Epoch 020 - train 0.11630 | val 0.15589
  Regression -> MSE: 0.000264, MAE: 0.013087, R²: -0.0644
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.10981 | val 0.10888
  Epoch 020 - train 0.11267 | val 0.11214
  Regression -> MSE: 0.000686, MAE: 0.019352, R²: -0.0025
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.11856 | val 0.18677
  Epoch 020 - train 0.11996 | val 0.18732
  Regression -> MSE: 0.000321, MAE: 0.014510, R²: -0.0350
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.09620 | val 0.12820
  Epoch 020 - train 0.09680 | val 0.13010
  Regression -> MSE: 0.000381, MAE: 0.015100, R²: -0.0903
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.11512 | val 0.12017
  Epoch 020 - train 0.11271 | val 0.12119
  Regression -> MSE: 0.000204, MAE: 0.010091, R²: -0.0041
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.11301 | val 0.21295
  Epoch 020 - train 0.10957 | val 0.21690
  Regression -> MSE: 0.000550, MAE: 0.018070, R²: 0.0088
  Directional -> Accuracy: 0.5319, MCC: 0.0620, F1: 0.3529

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.11941 | val 0.17678
  Epoch 020 - train 0.12292 | val 0.17754
  Regression -> MSE: 0.000248, MAE: 0.012251, R²: -0.0088
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.12465 | val 0.16313
  Epoch 020 - train 0.11931 | val 0.16306
  Regression -> MSE: 0.000646, MAE: 0.020179, R²: -0.0806
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.11410 | val 0.13996
  Epoch 020 - train 0.11790 | val 0.15797
  Regression -> MSE: 0.000399, MAE: 0.016044, R²: -0.0404
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.11900 | val 0.14559
  Epoch 020 - train 0.11660 | val 0.14508
  Regression -> MSE: 0.000243, MAE: 0.011701, R²: -0.0057
  Directional -> Accuracy: 0.5143, MCC: -0.0472, F1: 0.2917

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.10997 | val 0.18927
  Epoch 020 - train 0.11249 | val 0.21087
  Regression -> MSE: 0.000311, MAE: 0.013688, R²: 0.0003
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.6301

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.12642 | val 0.15140
  Epoch 020 - train 0.12576 | val 0.15907
  Regression -> MSE: 0.000679, MAE: 0.019569, R²: -0.0030
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.12280 | val 0.12387
  Epoch 020 - train 0.12004 | val 0.12352
  Regression -> MSE: 0.000138, MAE: 0.009024, R²: -0.0017
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.10785 | val 0.17309
  Epoch 020 - train 0.10456 | val 0.17953
  Regression -> MSE: 0.000225, MAE: 0.010691, R²: 0.0010
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.11710 | val 0.22878
  Epoch 020 - train 0.11891 | val 0.22866
  Regression -> MSE: 0.000362, MAE: 0.016085, R²: -0.0003
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.12379 | val 0.13501
  Epoch 020 - train 0.12267 | val 0.13637
  Regression -> MSE: 0.000108, MAE: 0.007975, R²: -0.0023
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.12425 | val 0.19167
  Epoch 020 - train 0.12316 | val 0.19396
  Regression -> MSE: 0.000156, MAE: 0.009667, R²: 0.0016
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.12175 | val 0.12618
  Epoch 020 - train 0.12021 | val 0.12780
  Regression -> MSE: 0.000294, MAE: 0.013965, R²: -0.0809
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.11505 | val 0.15482
  Epoch 020 - train 0.11124 | val 0.15481
  Regression -> MSE: 0.000168, MAE: 0.009163, R²: -0.1239
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.12646 | val 0.18463
  Epoch 020 - train 0.12889 | val 0.18489
  Regression -> MSE: 0.000244, MAE: 0.011167, R²: -0.0780
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.13399 | val 0.17998
  Epoch 020 - train 0.13073 | val 0.20348
  Regression -> MSE: 0.000144, MAE: 0.008330, R²: -0.0032
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.10820 | val 0.13862
  Epoch 020 - train 0.10742 | val 0.13841
  Regression -> MSE: 0.000165, MAE: 0.010424, R²: 0.0021
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.12054 | val 0.14337
  Epoch 020 - train 0.12255 | val 0.14343
  Regression -> MSE: 0.000092, MAE: 0.007395, R²: -0.0799
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.11805 | val 0.14132
  Epoch 020 - train 0.11853 | val 0.14123
  Regression -> MSE: 0.000213, MAE: 0.011303, R²: -0.0043
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.10880 | val 0.10297
  Epoch 020 - train 0.10593 | val 0.10312
  Regression -> MSE: 0.000095, MAE: 0.008077, R²: -0.0270
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.11757 | val 0.09615
  Epoch 020 - train 0.11731 | val 0.10281
  Regression -> MSE: 0.000111, MAE: 0.009072, R²: -0.0799
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.12630 | val 0.12713
  Epoch 020 - train 0.12718 | val 0.16125
  Regression -> MSE: 0.000233, MAE: 0.012588, R²: -0.0047
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.11582 | val 0.14199
  Epoch 020 - train 0.11495 | val 0.14262
  Regression -> MSE: 0.000174, MAE: 0.007880, R²: -0.0456
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.12463 | val 0.10314
  Epoch 020 - train 0.12208 | val 0.09942
  Regression -> MSE: 0.000239, MAE: 0.012017, R²: -0.0125
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.11960 | val 0.18533
  Epoch 020 - train 0.11526 | val 0.18395
  Regression -> MSE: 0.000235, MAE: 0.010159, R²: -0.0193
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.12004 | val 0.13958
  Epoch 020 - train 0.11669 | val 0.13531
  Regression -> MSE: 0.000133, MAE: 0.008100, R²: 0.0179
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.11926 | val 0.14543
  Epoch 020 - train 0.11951 | val 0.14423
  Regression -> MSE: 0.000190, MAE: 0.010376, R²: -0.0101
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.11363 | val 0.13926
  Epoch 020 - train 0.11444 | val 0.13904
  Regression -> MSE: 0.000276, MAE: 0.010827, R²: -0.0533
  Directional -> Accuracy: 0.4384, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.12082 | val 0.10450
  Epoch 020 - train 0.11684 | val 0.10457
  Regression -> MSE: 0.000168, MAE: 0.010371, R²: -0.0078
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.11703 | val 0.13454
  Epoch 020 - train 0.11599 | val 0.14573
  Regression -> MSE: 0.000188, MAE: 0.010609, R²: -0.0441
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.11824 | val 0.11366
  Epoch 020 - train 0.11831 | val 0.11403
  Regression -> MSE: 0.000343, MAE: 0.011806, R²: -0.0017
  Directional -> Accuracy: 0.4627, MCC: -0.1357, F1: 0.5714

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.12257 | val 0.07632
  Epoch 020 - train 0.12356 | val 0.08105
  Regression -> MSE: 0.000121, MAE: 0.008389, R²: -0.1536
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.11897 | val 0.19791
  Epoch 020 - train 0.11927 | val 0.20118
  Regression -> MSE: 0.000224, MAE: 0.011447, R²: -0.0251
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.11968 | val 0.19538
  Epoch 020 - train 0.11701 | val 0.19835
  Regression -> MSE: 0.000097, MAE: 0.007664, R²: -0.2428
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.10817 | val 0.08466
  Epoch 020 - train 0.11116 | val 0.08299
  Regression -> MSE: 0.000309, MAE: 0.013914, R²: -0.0041
  Directional -> Accuracy: 0.6531, MCC: 0.1852, F1: 0.3704

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.12029 | val 0.07517
  Epoch 020 - train 0.12507 | val 0.07434
  Regression -> MSE: 0.000256, MAE: 0.011469, R²: -0.0497
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.11326 | val 0.14352
  Epoch 020 - train 0.11159 | val 0.14377
  Regression -> MSE: 0.000083, MAE: 0.007036, R²: -0.0237
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.12059 | val 0.15214
  Epoch 020 - train 0.12427 | val 0.15718
  Regression -> MSE: 0.000313, MAE: 0.014507, R²: -0.0211
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.11237 | val 0.13126
  Epoch 020 - train 0.11002 | val 0.13407
  Regression -> MSE: 0.000099, MAE: 0.007167, R²: -0.0093
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.12581 | val 0.14089
  Epoch 020 - train 0.12931 | val 0.15244
  Regression -> MSE: 0.000172, MAE: 0.009724, R²: 0.0009
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.11119 | val 0.13496
  Epoch 020 - train 0.11243 | val 0.14420
  Regression -> MSE: 0.000224, MAE: 0.011751, R²: -0.0037
  Directional -> Accuracy: 0.5179, MCC: -0.1255, F1: 0.6824

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.11942 | val 0.13336
  Epoch 020 - train 0.12117 | val 0.13352
  Regression -> MSE: 0.000094, MAE: 0.007669, R²: -0.0135
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.12643 | val 0.17976
  Epoch 020 - train 0.12214 | val 0.18082
  Regression -> MSE: 0.000164, MAE: 0.010253, R²: 0.0003
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.11388 | val 0.14582
  Epoch 020 - train 0.11187 | val 0.14847
  Regression -> MSE: 0.000121, MAE: 0.008997, R²: -0.0448
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.12412 | val 0.18492

[I 2026-02-23 04:06:41,389] Trial 241 finished with value: -0.01146082899471514 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 32, 'learning_rate': 1.2346420553256933e-06, 'weight_decay': 4.35734769048626e-05, 'lr_patience': 7, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.1731512512071685, 'early_stopping_min_delta': 0.005726558746972215}. Best is trial 207 with value: -0.01137496405368131.

  Epoch 020 - train 0.12302 | val 0.18715
  Regression -> MSE: 0.000241, MAE: 0.012342, R²: -0.0144
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.14432 | val 0.21493
  Epoch 020 - train 0.14455 | val 0.21516
  Regression -> MSE: 0.000267, MAE: 0.013174, R²: -0.0770
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.13924 | val 0.12809
  Epoch 020 - train 0.13699 | val 0.14579
  Regression -> MSE: 0.000707, MAE: 0.019742, R²: -0.0321
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.14455 | val 0.23001
  Epoch 020 - train 0.14709 | val 0.23587
  Regression -> MSE: 0.000314, MAE: 0.014442, R²: -0.0116
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.11801 | val 0.12143
  Epoch 020 - train 0.11342 | val 0.12175
  Regression -> MSE: 0.000370, MAE: 0.014919, R²: -0.0606
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.14243 | val 0.14045
  Epoch 020 - train 0.14716 | val 0.14719
  Regression -> MSE: 0.000205, MAE: 0.010325, R²: -0.0083
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.12880 | val 0.26235
  Epoch 020 - train 0.12419 | val 0.28804
  Regression -> MSE: 0.000557, MAE: 0.018155, R²: -0.0037
  Directional -> Accuracy: 0.4894, MCC: -0.0125, F1: 0.5862

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.14509 | val 0.17115
  Epoch 020 - train 0.14487 | val 0.17028
  Regression -> MSE: 0.000247, MAE: 0.012209, R²: -0.0077
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.14157 | val 0.21990
  Epoch 020 - train 0.13976 | val 0.26753
  Regression -> MSE: 0.000669, MAE: 0.020513, R²: -0.1195
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.13231 | val 0.17695
  Epoch 020 - train 0.13072 | val 0.17738
  Regression -> MSE: 0.000385, MAE: 0.016153, R²: -0.0024
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.15266 | val 0.18840
  Epoch 020 - train 0.15605 | val 0.18870
  Regression -> MSE: 0.000249, MAE: 0.011667, R²: -0.0309
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.13285 | val 0.19550
  Epoch 020 - train 0.13803 | val 0.19404
  Regression -> MSE: 0.000329, MAE: 0.013872, R²: -0.0569
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.14712 | val 0.16327
  Epoch 020 - train 0.14604 | val 0.16418
  Regression -> MSE: 0.000678, MAE: 0.019501, R²: -0.0007
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.15366 | val 0.17428
  Epoch 020 - train 0.15324 | val 0.21119
  Regression -> MSE: 0.000138, MAE: 0.009142, R²: -0.0010
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.13764 | val 0.18503
  Epoch 020 - train 0.13353 | val 0.18820
  Regression -> MSE: 0.000230, MAE: 0.010853, R²: -0.0223
  Directional -> Accuracy: 0.4918, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.13685 | val 0.29386
  Epoch 020 - train 0.13711 | val 0.30912
  Regression -> MSE: 0.000366, MAE: 0.015982, R²: -0.0119
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.14586 | val 0.14763
  Epoch 020 - train 0.14456 | val 0.14715
  Regression -> MSE: 0.000109, MAE: 0.007957, R²: -0.0121
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.13520 | val 0.22790
  Epoch 020 - train 0.13703 | val 0.23316
  Regression -> MSE: 0.000156, MAE: 0.009775, R²: -0.0034
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.15184 | val 0.17377
  Epoch 020 - train 0.14488 | val 0.17591
  Regression -> MSE: 0.000272, MAE: 0.013032, R²: -0.0006
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.13157 | val 0.18768
  Epoch 020 - train 0.12733 | val 0.18681
  Regression -> MSE: 0.000163, MAE: 0.008989, R²: -0.0893
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.14895 | val 0.26634
  Epoch 020 - train 0.15200 | val 0.26551
  Regression -> MSE: 0.000229, MAE: 0.010940, R²: -0.0126
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.14151 | val 0.18353
  Epoch 020 - train 0.14410 | val 0.19650
  Regression -> MSE: 0.000149, MAE: 0.008648, R²: -0.0387
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.13587 | val 0.17003
  Epoch 020 - train 0.13300 | val 0.17004
  Regression -> MSE: 0.000165, MAE: 0.010426, R²: 0.0023
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.15136 | val 0.16426
  Epoch 020 - train 0.14716 | val 0.16283
  Regression -> MSE: 0.000092, MAE: 0.007381, R²: -0.0768
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.14440 | val 0.18691
  Epoch 020 - train 0.14181 | val 0.18769
  Regression -> MSE: 0.000213, MAE: 0.011300, R²: -0.0063
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.13047 | val 0.12853
  Epoch 020 - train 0.12857 | val 0.12936
  Regression -> MSE: 0.000093, MAE: 0.008094, R²: -0.0154
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.14933 | val 0.10845
  Epoch 020 - train 0.14487 | val 0.11749
  Regression -> MSE: 0.000103, MAE: 0.008713, R²: 0.0018
  Directional -> Accuracy: 0.5652, MCC: 0.1801, F1: 0.6000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.14294 | val 0.15608
  Epoch 020 - train 0.14386 | val 0.17854
  Regression -> MSE: 0.000242, MAE: 0.012896, R²: -0.0454
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.14033 | val 0.16962
  Epoch 020 - train 0.14030 | val 0.16889
  Regression -> MSE: 0.000170, MAE: 0.007805, R²: -0.0221
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.15572 | val 0.13118
  Epoch 020 - train 0.15542 | val 0.16812
  Regression -> MSE: 0.000241, MAE: 0.012090, R²: -0.0185
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.14173 | val 0.22803
  Epoch 020 - train 0.14323 | val 0.26381
  Regression -> MSE: 0.000233, MAE: 0.010050, R²: -0.0125
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.13947 | val 0.17046
  Epoch 020 - train 0.14410 | val 0.16676
  Regression -> MSE: 0.000136, MAE: 0.008224, R²: -0.0044
  Directional -> Accuracy: 0.6047, MCC: 0.2937, F1: 0.7302

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.14655 | val 0.18446
  Epoch 020 - train 0.14461 | val 0.18671
  Regression -> MSE: 0.000188, MAE: 0.010538, R²: -0.0007
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.13164 | val 0.16642
  Epoch 020 - train 0.13157 | val 0.16752
  Regression -> MSE: 0.000275, MAE: 0.010811, R²: -0.0505
  Directional -> Accuracy: 0.4384, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.14267 | val 0.11971
  Epoch 020 - train 0.13706 | val 0.12265
  Regression -> MSE: 0.000168, MAE: 0.010383, R²: -0.0080
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.13564 | val 0.15582
  Epoch 020 - train 0.13516 | val 0.16654
  Regression -> MSE: 0.000188, MAE: 0.010648, R²: -0.0463
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.14062 | val 0.13304
  Epoch 020 - train 0.14025 | val 0.13319
  Regression -> MSE: 0.000342, MAE: 0.011745, R²: 0.0009
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.14885 | val 0.09000
  Epoch 020 - train 0.14931 | val 0.09512
  Regression -> MSE: 0.000129, MAE: 0.008552, R²: -0.2242
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.14977 | val 0.19346
  Epoch 020 - train 0.14884 | val 0.19577
  Regression -> MSE: 0.000223, MAE: 0.011394, R²: -0.0200
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.13754 | val 0.23665
  Epoch 020 - train 0.13426 | val 0.23651
  Regression -> MSE: 0.000086, MAE: 0.007232, R²: -0.1029
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.14139 | val 0.10640
  Epoch 020 - train 0.13532 | val 0.10607
  Regression -> MSE: 0.000317, MAE: 0.014352, R²: -0.0302
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.15210 | val 0.09077
  Epoch 020 - train 0.14607 | val 0.09131
  Regression -> MSE: 0.000260, MAE: 0.011496, R²: -0.0677
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.13831 | val 0.17932
  Epoch 020 - train 0.14157 | val 0.18150
  Regression -> MSE: 0.000081, MAE: 0.007060, R²: -0.0024
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.14052 | val 0.16913
  Epoch 020 - train 0.14635 | val 0.17684
  Regression -> MSE: 0.000309, MAE: 0.014514, R²: -0.0069
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.14095 | val 0.14763
  Epoch 020 - train 0.14731 | val 0.15541
  Regression -> MSE: 0.000098, MAE: 0.007341, R²: -0.0012
  Directional -> Accuracy: 0.4318, MCC: 0.0000, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.14944 | val 0.16541
  Epoch 020 - train 0.14432 | val 0.17025
  Regression -> MSE: 0.000175, MAE: 0.010112, R²: -0.0156
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.13032 | val 0.15339
  Epoch 020 - train 0.12435 | val 0.15186
  Regression -> MSE: 0.000224, MAE: 0.011405, R²: -0.0029
  Directional -> Accuracy: 0.6607, MCC: 0.3160, F1: 0.7164

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.14302 | val 0.15297
  Epoch 020 - train 0.13962 | val 0.15347
  Regression -> MSE: 0.000092, MAE: 0.007645, R²: -0.0003
  Directional -> Accuracy: 0.4737, MCC: -0.0358, F1: 0.5455

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.15047 | val 0.21184
  Epoch 020 - train 0.15112 | val 0.21339
  Regression -> MSE: 0.000164, MAE: 0.010249, R²: -0.0007
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.14515 | val 0.20657
  Epoch 020 - train 0.14312 | val 0.21381
  Regression -> MSE: 0.000117, MAE: 0.008938, R²: -0.0117
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.15991 | val 0.22532

[I 2026-02-23 04:08:27,551] Trial 242 finished with value: -0.011477760642034974 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 32, 'learning_rate': 1.6539358200809243e-06, 'weight_decay': 6.371534459889302e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.21130438706572013, 'early_stopping_min_delta': 0.00553738920720129}. Best is trial 207 with value: -0.01137496405368131.

  Epoch 020 - train 0.15839 | val 0.23524
  Regression -> MSE: 0.000238, MAE: 0.012503, R²: -0.0016
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.09698 | val 0.13607
  Epoch 020 - train 0.09575 | val 0.13537
  Regression -> MSE: 0.000258, MAE: 0.012935, R²: -0.0411
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.09578 | val 0.09111
  Epoch 020 - train 0.09481 | val 0.09508
  Regression -> MSE: 0.000688, MAE: 0.019410, R²: -0.0051
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.10225 | val 0.16191
  Epoch 020 - train 0.09916 | val 0.16917
  Regression -> MSE: 0.000311, MAE: 0.014479, R²: -0.0030
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.08528 | val 0.08341
  Epoch 020 - train 0.08346 | val 0.08397
  Regression -> MSE: 0.000350, MAE: 0.014612, R²: -0.0030
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.09957 | val 0.09857
  Epoch 020 - train 0.09915 | val 0.09909
  Regression -> MSE: 0.000204, MAE: 0.010201, R²: -0.0025
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.09504 | val 0.18581
  Epoch 020 - train 0.09685 | val 0.21372
  Regression -> MSE: 0.000570, MAE: 0.018340, R²: -0.0265
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.09878 | val 0.12440
  Epoch 020 - train 0.09806 | val 0.12477
  Regression -> MSE: 0.000251, MAE: 0.011948, R²: -0.0227
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.09925 | val 0.12093
  Epoch 020 - train 0.09736 | val 0.13073
  Regression -> MSE: 0.000612, MAE: 0.019521, R²: -0.0243
  Directional -> Accuracy: 0.5455, MCC: -0.1023, F1: 0.0909

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.09458 | val 0.11954
  Epoch 020 - train 0.09392 | val 0.11771
  Regression -> MSE: 0.000387, MAE: 0.016090, R²: -0.0092
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.10219 | val 0.12548
  Epoch 020 - train 0.10144 | val 0.12362
  Regression -> MSE: 0.000242, MAE: 0.011883, R²: -0.0022
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.09041 | val 0.13419
  Epoch 020 - train 0.09340 | val 0.13375
  Regression -> MSE: 0.000318, MAE: 0.013586, R²: -0.0212
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.09902 | val 0.11787
  Epoch 020 - train 0.09891 | val 0.11900
  Regression -> MSE: 0.000682, MAE: 0.019527, R²: -0.0065
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.10358 | val 0.10467
  Epoch 020 - train 0.10151 | val 0.10748
  Regression -> MSE: 0.000138, MAE: 0.009043, R²: -0.0003
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.09124 | val 0.15172
  Epoch 020 - train 0.09061 | val 0.15779
  Regression -> MSE: 0.000225, MAE: 0.010712, R²: -0.0020
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.09701 | val 0.18735
  Epoch 020 - train 0.09469 | val 0.18989
  Regression -> MSE: 0.000366, MAE: 0.015953, R²: -0.0117
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.09868 | val 0.10829
  Epoch 020 - train 0.10160 | val 0.10871
  Regression -> MSE: 0.000109, MAE: 0.008006, R²: -0.0085
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.09457 | val 0.16743
  Epoch 020 - train 0.09521 | val 0.17104
  Regression -> MSE: 0.000156, MAE: 0.009590, R²: -0.0003
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.09555 | val 0.10937
  Epoch 020 - train 0.09702 | val 0.11030
  Regression -> MSE: 0.000271, MAE: 0.012915, R²: 0.0032
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.08685 | val 0.13403
  Epoch 020 - train 0.08908 | val 0.13426
  Regression -> MSE: 0.000159, MAE: 0.008866, R²: -0.0646
  Directional -> Accuracy: 0.5385, MCC: 0.1147, F1: 0.5312

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.09602 | val 0.13540
  Epoch 020 - train 0.09814 | val 0.13443
  Regression -> MSE: 0.000236, MAE: 0.010984, R²: -0.0430
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.09831 | val 0.12158
  Epoch 020 - train 0.10097 | val 0.12425
  Regression -> MSE: 0.000144, MAE: 0.008361, R²: -0.0037
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.10259 | val 0.11152
  Epoch 020 - train 0.10128 | val 0.11176
  Regression -> MSE: 0.000166, MAE: 0.010338, R²: -0.0055
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.10171 | val 0.11775
  Epoch 020 - train 0.10117 | val 0.11811
  Regression -> MSE: 0.000091, MAE: 0.007331, R²: -0.0626
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.09758 | val 0.12316
  Epoch 020 - train 0.09668 | val 0.12278
  Regression -> MSE: 0.000212, MAE: 0.011213, R²: 0.0001
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.08963 | val 0.08917
  Epoch 020 - train 0.09243 | val 0.08858
  Regression -> MSE: 0.000095, MAE: 0.008113, R²: -0.0270
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.09807 | val 0.08633
  Epoch 020 - train 0.09788 | val 0.08598
  Regression -> MSE: 0.000121, MAE: 0.009375, R²: -0.1739
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.10783 | val 0.11417
  Epoch 020 - train 0.11004 | val 0.13021
  Regression -> MSE: 0.000248, MAE: 0.013039, R²: -0.0696
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.09895 | val 0.11198
  Epoch 020 - train 0.09956 | val 0.11235
  Regression -> MSE: 0.000185, MAE: 0.008078, R²: -0.1144
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.10010 | val 0.08363
  Epoch 020 - train 0.10060 | val 0.08196
  Regression -> MSE: 0.000238, MAE: 0.011909, R²: -0.0057
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.09719 | val 0.15326
  Epoch 020 - train 0.10124 | val 0.19217
  Regression -> MSE: 0.000231, MAE: 0.009891, R²: -0.0012
  Directional -> Accuracy: 0.4651, MCC: -0.0658, F1: 0.5306

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.09885 | val 0.10895
  Epoch 020 - train 0.10091 | val 0.10964
  Regression -> MSE: 0.000135, MAE: 0.008173, R²: -0.0009
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.10116 | val 0.12706
  Epoch 020 - train 0.10167 | val 0.12992
  Regression -> MSE: 0.000189, MAE: 0.010422, R²: -0.0049
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.08561 | val 0.10679
  Epoch 020 - train 0.08591 | val 0.10644
  Regression -> MSE: 0.000280, MAE: 0.010949, R²: -0.0682
  Directional -> Accuracy: 0.4384, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.09754 | val 0.08161
  Epoch 020 - train 0.09676 | val 0.08033
  Regression -> MSE: 0.000167, MAE: 0.010371, R²: -0.0006
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.09429 | val 0.09722
  Epoch 020 - train 0.09636 | val 0.09633
  Regression -> MSE: 0.000182, MAE: 0.010339, R²: -0.0101
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.09551 | val 0.09392
  Epoch 020 - train 0.09503 | val 0.09454
  Regression -> MSE: 0.000344, MAE: 0.012067, R²: -0.0050
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.10586 | val 0.06529
  Epoch 020 - train 0.10460 | val 0.06650
  Regression -> MSE: 0.000128, MAE: 0.008513, R²: -0.2168
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.10227 | val 0.14683
  Epoch 020 - train 0.10288 | val 0.14770
  Regression -> MSE: 0.000220, MAE: 0.011345, R²: -0.0071
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.09232 | val 0.18006
  Epoch 020 - train 0.09460 | val 0.21514
  Regression -> MSE: 0.000089, MAE: 0.007379, R²: -0.1428
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.09453 | val 0.08594
  Epoch 020 - train 0.09230 | val 0.08303
  Regression -> MSE: 0.000343, MAE: 0.015457, R²: -0.1154
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.10034 | val 0.05982
  Epoch 020 - train 0.10486 | val 0.05949
  Regression -> MSE: 0.000246, MAE: 0.011569, R²: -0.0070
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.0000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.09100 | val 0.11455
  Epoch 020 - train 0.09256 | val 0.11427
  Regression -> MSE: 0.000082, MAE: 0.007038, R²: -0.0158
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.10098 | val 0.12492
  Epoch 020 - train 0.10111 | val 0.13405
  Regression -> MSE: 0.000309, MAE: 0.014491, R²: -0.0078
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.09851 | val 0.10459
  Epoch 020 - train 0.09901 | val 0.10968
  Regression -> MSE: 0.000098, MAE: 0.007280, R²: 0.0027
  Directional -> Accuracy: 0.4318, MCC: 0.0000, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.09791 | val 0.11571
  Epoch 020 - train 0.09784 | val 0.13292
  Regression -> MSE: 0.000176, MAE: 0.010226, R²: -0.0250
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.09354 | val 0.12326
  Epoch 020 - train 0.09465 | val 0.12988
  Regression -> MSE: 0.000224, MAE: 0.011798, R²: -0.0041
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.09606 | val 0.11259
  Epoch 020 - train 0.09433 | val 0.11279
  Regression -> MSE: 0.000094, MAE: 0.007792, R²: -0.0202
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.09875 | val 0.15275
  Epoch 020 - train 0.09958 | val 0.15510
  Regression -> MSE: 0.000164, MAE: 0.010260, R²: -0.0018
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.09978 | val 0.12541
  Epoch 020 - train 0.10015 | val 0.12563
  Regression -> MSE: 0.000118, MAE: 0.008975, R²: -0.0199
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.10116 | val 0.14826

[I 2026-02-23 04:10:13,557] Trial 243 finished with value: -0.011461093852939695 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 32, 'learning_rate': 2.2507917694185717e-06, 'weight_decay': 5.20678308870632e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.14043120350431706, 'early_stopping_min_delta': 0.005999060651356916}. Best is trial 207 with value: -0.01137496405368131.

  Epoch 020 - train 0.09727 | val 0.15223
  Regression -> MSE: 0.000239, MAE: 0.012359, R²: -0.0068
  Directional -> Accuracy: 0.4426, MCC: -0.2109, F1: 0.1053

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.16869 | val 0.26772
  Epoch 020 - train 0.17025 | val 0.26585
  Regression -> MSE: 0.000250, MAE: 0.012641, R²: -0.0101
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.17381 | val 0.17146
  Epoch 020 - train 0.17329 | val 0.16853
  Regression -> MSE: 0.000686, MAE: 0.019405, R²: -0.0025
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.18061 | val 0.29392
  Epoch 020 - train 0.18028 | val 0.31034
  Regression -> MSE: 0.000317, MAE: 0.014497, R²: -0.0223
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.15390 | val 0.18705
  Epoch 020 - train 0.14749 | val 0.18289
  Regression -> MSE: 0.000353, MAE: 0.014638, R²: -0.0113
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.17292 | val 0.17320
  Epoch 020 - train 0.17391 | val 0.17530
  Regression -> MSE: 0.000204, MAE: 0.010226, R²: -0.0031
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.17726 | val 0.34662
  Epoch 020 - train 0.17276 | val 0.37825
  Regression -> MSE: 0.000599, MAE: 0.018972, R²: -0.0788
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.17344 | val 0.22581
  Epoch 020 - train 0.17523 | val 0.22750
  Regression -> MSE: 0.000247, MAE: 0.011938, R²: -0.0075
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.17508 | val 0.24477
  Epoch 020 - train 0.17034 | val 0.21036
  Regression -> MSE: 0.000603, MAE: 0.019364, R²: -0.0097
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.17162 | val 0.23353
  Epoch 020 - train 0.16312 | val 0.27769
  Regression -> MSE: 0.000384, MAE: 0.016110, R²: -0.0008
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.17848 | val 0.22635
  Epoch 020 - train 0.18403 | val 0.22783
  Regression -> MSE: 0.000242, MAE: 0.011981, R²: -0.0010
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.15686 | val 0.27195
  Epoch 020 - train 0.15733 | val 0.28323
  Regression -> MSE: 0.000310, MAE: 0.013717, R²: 0.0016
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.6301

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.18072 | val 0.24928
  Epoch 020 - train 0.18223 | val 0.26161
  Regression -> MSE: 0.000681, MAE: 0.019619, R²: -0.0059
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.18255 | val 0.17465
  Epoch 020 - train 0.17904 | val 0.19348
  Regression -> MSE: 0.000139, MAE: 0.009217, R²: -0.0076
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.16915 | val 0.26404
  Epoch 020 - train 0.17272 | val 0.26656
  Regression -> MSE: 0.000228, MAE: 0.010962, R²: -0.0155
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.17204 | val 0.35299
  Epoch 020 - train 0.16984 | val 0.35483
  Regression -> MSE: 0.000371, MAE: 0.015937, R²: -0.0237
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.18008 | val 0.19546
  Epoch 020 - train 0.18298 | val 0.20022
  Regression -> MSE: 0.000110, MAE: 0.007954, R²: -0.0223
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.16531 | val 0.30601
  Epoch 020 - train 0.16700 | val 0.32082
  Regression -> MSE: 0.000161, MAE: 0.010138, R²: -0.0320
  Directional -> Accuracy: 0.3559, MCC: -0.2461, F1: 0.3667

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.17184 | val 0.21683
  Epoch 020 - train 0.17617 | val 0.22188
  Regression -> MSE: 0.000274, MAE: 0.013109, R²: -0.0070
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.15365 | val 0.24304
  Epoch 020 - train 0.15290 | val 0.24658
  Regression -> MSE: 0.000167, MAE: 0.009106, R²: -0.1182
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.18620 | val 0.28567
  Epoch 020 - train 0.18501 | val 0.28726
  Regression -> MSE: 0.000247, MAE: 0.011204, R²: -0.0916
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.18269 | val 0.22979
  Epoch 020 - train 0.17862 | val 0.24847
  Regression -> MSE: 0.000153, MAE: 0.008802, R²: -0.0648
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.16507 | val 0.20063
  Epoch 020 - train 0.16240 | val 0.19972
  Regression -> MSE: 0.000178, MAE: 0.010320, R²: -0.0753
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.17858 | val 0.21941
  Epoch 020 - train 0.17973 | val 0.22245
  Regression -> MSE: 0.000088, MAE: 0.007224, R²: -0.0376
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.17366 | val 0.21208
  Epoch 020 - train 0.16579 | val 0.21297
  Regression -> MSE: 0.000212, MAE: 0.011163, R²: -0.0006
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.16021 | val 0.15938
  Epoch 020 - train 0.16099 | val 0.16092
  Regression -> MSE: 0.000101, MAE: 0.008240, R²: -0.0937
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.17179 | val 0.15132
  Epoch 020 - train 0.17545 | val 0.18281
  Regression -> MSE: 0.000116, MAE: 0.009194, R²: -0.1214
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.17882 | val 0.16277
  Epoch 020 - train 0.17950 | val 0.15822
  Regression -> MSE: 0.000233, MAE: 0.012390, R²: -0.0045
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.17395 | val 0.20766
  Epoch 020 - train 0.17372 | val 0.20477
  Regression -> MSE: 0.000185, MAE: 0.008084, R²: -0.1092
  Directional -> Accuracy: 0.5088, MCC: 0.1095, F1: 0.3636

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.18670 | val 0.14771
  Epoch 020 - train 0.17800 | val 0.15206
  Regression -> MSE: 0.000237, MAE: 0.011875, R²: -0.0013
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.16934 | val 0.28537
  Epoch 020 - train 0.16340 | val 0.29858
  Regression -> MSE: 0.000232, MAE: 0.009988, R²: -0.0078
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.18739 | val 0.20379
  Epoch 020 - train 0.18538 | val 0.21313
  Regression -> MSE: 0.000135, MAE: 0.008175, R²: -0.0011
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.18366 | val 0.21630
  Epoch 020 - train 0.18076 | val 0.21767
  Regression -> MSE: 0.000196, MAE: 0.010556, R²: -0.0394
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.15366 | val 0.20127
  Epoch 020 - train 0.15066 | val 0.20008
  Regression -> MSE: 0.000269, MAE: 0.010610, R²: -0.0281
  Directional -> Accuracy: 0.5205, MCC: 0.0162, F1: 0.5882

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.15954 | val 0.14756
  Epoch 020 - train 0.16150 | val 0.15781
  Regression -> MSE: 0.000165, MAE: 0.010342, R²: 0.0081
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.16526 | val 0.17356
  Epoch 020 - train 0.16161 | val 0.17034
  Regression -> MSE: 0.000190, MAE: 0.010648, R²: -0.0573
  Directional -> Accuracy: 0.4545, MCC: -0.1988, F1: 0.0769

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.17573 | val 0.16794
  Epoch 020 - train 0.16623 | val 0.16796
  Regression -> MSE: 0.000350, MAE: 0.011810, R²: -0.0209
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.18947 | val 0.11563
  Epoch 020 - train 0.18815 | val 0.13113
  Regression -> MSE: 0.000113, MAE: 0.008349, R²: -0.0779
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.17144 | val 0.24678
  Epoch 020 - train 0.16990 | val 0.25124
  Regression -> MSE: 0.000224, MAE: 0.011442, R²: -0.0248
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.16783 | val 0.31450
  Epoch 020 - train 0.16791 | val 0.32789
  Regression -> MSE: 0.000088, MAE: 0.007334, R²: -0.1305
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.16001 | val 0.13520
  Epoch 020 - train 0.16747 | val 0.13010
  Regression -> MSE: 0.000321, MAE: 0.014568, R²: -0.0428
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.20439 | val 0.09904
  Epoch 020 - train 0.18836 | val 0.09189
  Regression -> MSE: 0.000251, MAE: 0.011770, R²: -0.0291
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.0000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.17206 | val 0.20925
  Epoch 020 - train 0.16978 | val 0.20787
  Regression -> MSE: 0.000081, MAE: 0.007097, R²: -0.0034
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.17425 | val 0.21382
  Epoch 020 - train 0.17396 | val 0.20462
  Regression -> MSE: 0.000315, MAE: 0.014535, R²: -0.0273
  Directional -> Accuracy: 0.5745, MCC: 0.1828, F1: 0.4444

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.16767 | val 0.18778
  Epoch 020 - train 0.16825 | val 0.19742
  Regression -> MSE: 0.000098, MAE: 0.007300, R²: 0.0002
  Directional -> Accuracy: 0.4318, MCC: 0.0000, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.18260 | val 0.20739
  Epoch 020 - train 0.18264 | val 0.21715
  Regression -> MSE: 0.000172, MAE: 0.009730, R²: -0.0004
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.16322 | val 0.19555
  Epoch 020 - train 0.16064 | val 0.19759
  Regression -> MSE: 0.000224, MAE: 0.011774, R²: -0.0034
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.17064 | val 0.20521
  Epoch 020 - train 0.17013 | val 0.20875
  Regression -> MSE: 0.000093, MAE: 0.007683, R²: -0.0075
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.18299 | val 0.27501
  Epoch 020 - train 0.18072 | val 0.27497
  Regression -> MSE: 0.000166, MAE: 0.010293, R²: -0.0133
  Directional -> Accuracy: 0.4815, MCC: 0.0000, F1: 0.0000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.16328 | val 0.22554
  Epoch 020 - train 0.16455 | val 0.23060
  Regression -> MSE: 0.000119, MAE: 0.008958, R²: -0.0281
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.17864 | val 0.24872

[I 2026-02-23 04:12:00,040] Trial 244 finished with value: -0.011466683577435051 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 32, 'learning_rate': 3.86802254093497e-06, 'weight_decay': 9.230168768735449e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.2742238916886513, 'early_stopping_min_delta': 0.005809261809591249}. Best is trial 207 with value: -0.01137496405368131.

  Epoch 020 - train 0.17473 | val 0.25431
  Regression -> MSE: 0.000239, MAE: 0.012347, R²: -0.0067
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.11203 | val 0.14957
  Epoch 020 - train 0.10854 | val 0.15057
  Regression -> MSE: 0.000254, MAE: 0.012822, R²: -0.0272
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.10752 | val 0.10996
  Epoch 020 - train 0.10745 | val 0.11223
  Regression -> MSE: 0.000697, MAE: 0.019557, R²: -0.0175
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.11615 | val 0.17882
  Epoch 020 - train 0.10991 | val 0.17979
  Regression -> MSE: 0.000315, MAE: 0.014451, R²: -0.0156
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.09496 | val 0.13007
  Epoch 020 - train 0.09525 | val 0.13196
  Regression -> MSE: 0.000363, MAE: 0.014791, R²: -0.0405
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.11182 | val 0.11016
  Epoch 020 - train 0.11521 | val 0.11235
  Regression -> MSE: 0.000205, MAE: 0.010073, R²: -0.0051
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.10426 | val 0.20457
  Epoch 020 - train 0.10575 | val 0.20803
  Regression -> MSE: 0.000588, MAE: 0.018732, R²: -0.0594
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.11392 | val 0.14213
  Epoch 020 - train 0.11467 | val 0.14391
  Regression -> MSE: 0.000247, MAE: 0.011929, R²: -0.0067
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.11480 | val 0.15767
  Epoch 020 - train 0.10914 | val 0.16965
  Regression -> MSE: 0.000643, MAE: 0.020119, R²: -0.0755
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.11120 | val 0.12950
  Epoch 020 - train 0.10672 | val 0.12661
  Regression -> MSE: 0.000527, MAE: 0.018087, R²: -0.3749
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.11747 | val 0.21471
  Epoch 020 - train 0.11598 | val 0.21824
  Regression -> MSE: 0.000242, MAE: 0.011787, R²: -0.0029
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.10096 | val 0.16743
  Epoch 020 - train 0.10251 | val 0.17293
  Regression -> MSE: 0.000312, MAE: 0.013636, R²: -0.0046
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.11432 | val 0.13760
  Epoch 020 - train 0.11550 | val 0.14806
  Regression -> MSE: 0.000682, MAE: 0.019655, R²: -0.0067
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.11606 | val 0.10787
  Epoch 020 - train 0.11446 | val 0.11525
  Regression -> MSE: 0.000145, MAE: 0.009507, R²: -0.0472
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.10349 | val 0.14065
  Epoch 020 - train 0.09785 | val 0.14513
  Regression -> MSE: 0.000220, MAE: 0.010674, R²: 0.0202
  Directional -> Accuracy: 0.5246, MCC: 0.0647, F1: 0.6667

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.11086 | val 0.22625
  Epoch 020 - train 0.11017 | val 0.23153
  Regression -> MSE: 0.000369, MAE: 0.015935, R²: -0.0188
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.11912 | val 0.11288
  Epoch 020 - train 0.11653 | val 0.11181
  Regression -> MSE: 0.000111, MAE: 0.007972, R²: -0.0319
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.10782 | val 0.17535
  Epoch 020 - train 0.10831 | val 0.17795
  Regression -> MSE: 0.000157, MAE: 0.009776, R²: -0.0077
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.11726 | val 0.12403
  Epoch 020 - train 0.11686 | val 0.12380
  Regression -> MSE: 0.000279, MAE: 0.012857, R²: -0.0259
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.10781 | val 0.15382
  Epoch 020 - train 0.10500 | val 0.15416
  Regression -> MSE: 0.000164, MAE: 0.009025, R²: -0.0958
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.12074 | val 0.17061
  Epoch 020 - train 0.11709 | val 0.16975
  Regression -> MSE: 0.000231, MAE: 0.010925, R²: -0.0203
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.11383 | val 0.13579
  Epoch 020 - train 0.11120 | val 0.13690
  Regression -> MSE: 0.000146, MAE: 0.008493, R²: -0.0155
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.10368 | val 0.13263
  Epoch 020 - train 0.10394 | val 0.13191
  Regression -> MSE: 0.000165, MAE: 0.010577, R²: -0.0011
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.11793 | val 0.13907
  Epoch 020 - train 0.11822 | val 0.14064
  Regression -> MSE: 0.000085, MAE: 0.007034, R²: 0.0028
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.12232 | val 0.15425
  Epoch 020 - train 0.11845 | val 0.15282
  Regression -> MSE: 0.000216, MAE: 0.011065, R²: -0.0182
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.10621 | val 0.09916
  Epoch 020 - train 0.10472 | val 0.09921
  Regression -> MSE: 0.000094, MAE: 0.008103, R²: -0.0246
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.11715 | val 0.08671
  Epoch 020 - train 0.11590 | val 0.09557
  Regression -> MSE: 0.000103, MAE: 0.008688, R²: 0.0006
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.11405 | val 0.11303
  Epoch 020 - train 0.11721 | val 0.11591
  Regression -> MSE: 0.000243, MAE: 0.012911, R²: -0.0496
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.11504 | val 0.13904
  Epoch 020 - train 0.11005 | val 0.14203
  Regression -> MSE: 0.000172, MAE: 0.007827, R²: -0.0319
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.11178 | val 0.09550
  Epoch 020 - train 0.11527 | val 0.09829
  Regression -> MSE: 0.000237, MAE: 0.011858, R²: -0.0013
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.11380 | val 0.17506
  Epoch 020 - train 0.11253 | val 0.17893
  Regression -> MSE: 0.000232, MAE: 0.009995, R²: -0.0064
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.11487 | val 0.13338
  Epoch 020 - train 0.11116 | val 0.14388
  Regression -> MSE: 0.000135, MAE: 0.008221, R²: -0.0026
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.11254 | val 0.13625
  Epoch 020 - train 0.11601 | val 0.13526
  Regression -> MSE: 0.000289, MAE: 0.013283, R²: -0.5334
  Directional -> Accuracy: 0.5200, MCC: 0.1027, F1: 0.3684

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.10235 | val 0.12100
  Epoch 020 - train 0.10529 | val 0.12115
  Regression -> MSE: 0.000275, MAE: 0.010974, R²: -0.0491
  Directional -> Accuracy: 0.5753, MCC: 0.1684, F1: 0.5753

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.11858 | val 0.09874
  Epoch 020 - train 0.10899 | val 0.09882
  Regression -> MSE: 0.000168, MAE: 0.010363, R²: -0.0085
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.10542 | val 0.11459
  Epoch 020 - train 0.10430 | val 0.12269
  Regression -> MSE: 0.000180, MAE: 0.010247, R²: -0.0002
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.11079 | val 0.11215
  Epoch 020 - train 0.11442 | val 0.11275
  Regression -> MSE: 0.000346, MAE: 0.011707, R²: -0.0104
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.12499 | val 0.07471
  Epoch 020 - train 0.12395 | val 0.07845
  Regression -> MSE: 0.000113, MAE: 0.008343, R²: -0.0728
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.11752 | val 0.17150
  Epoch 020 - train 0.11840 | val 0.17665
  Regression -> MSE: 0.000221, MAE: 0.011383, R²: -0.0121
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.10597 | val 0.18459
  Epoch 020 - train 0.10911 | val 0.18074
  Regression -> MSE: 0.000104, MAE: 0.007993, R²: -0.3454
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.10715 | val 0.08868
  Epoch 020 - train 0.10891 | val 0.08770
  Regression -> MSE: 0.000321, MAE: 0.014571, R²: -0.0446
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.12516 | val 0.07273
  Epoch 020 - train 0.12016 | val 0.07503
  Regression -> MSE: 0.000257, MAE: 0.011480, R²: -0.0557
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.11500 | val 0.14120
  Epoch 020 - train 0.11135 | val 0.14013
  Regression -> MSE: 0.000081, MAE: 0.007069, R²: -0.0024
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.10844 | val 0.13614
  Epoch 020 - train 0.10782 | val 0.13741
  Regression -> MSE: 0.000309, MAE: 0.014519, R²: -0.0068
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.11678 | val 0.11705
  Epoch 020 - train 0.12178 | val 0.11866
  Regression -> MSE: 0.000099, MAE: 0.007326, R²: -0.0047
  Directional -> Accuracy: 0.4091, MCC: -0.1283, F1: 0.0714

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.12112 | val 0.13158
  Epoch 020 - train 0.11309 | val 0.14006
  Regression -> MSE: 0.000174, MAE: 0.010050, R²: -0.0129
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.10147 | val 0.13942
  Epoch 020 - train 0.09833 | val 0.14606
  Regression -> MSE: 0.000223, MAE: 0.011762, R²: -0.0021
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.10960 | val 0.12820
  Epoch 020 - train 0.11029 | val 0.13127
  Regression -> MSE: 0.000092, MAE: 0.007648, R²: 0.0003
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.12116 | val 0.17256
  Epoch 020 - train 0.12115 | val 0.17506
  Regression -> MSE: 0.000164, MAE: 0.010290, R²: -0.0024
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.10894 | val 0.12874
  Epoch 020 - train 0.10870 | val 0.12801
  Regression -> MSE: 0.000126, MAE: 0.009239, R²: -0.0880
  Directional -> Accuracy: 0.4821, MCC: -0.0124, F1: 0.1714

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.11642 | val 0.16760

[I 2026-02-23 04:13:47,302] Trial 245 finished with value: -0.011553130756444895 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 32, 'learning_rate': 1.8002778900829203e-06, 'weight_decay': 2.7487026283052777e-05, 'lr_patience': 7, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.16322626424014544, 'early_stopping_min_delta': 0.0054253475320214925}. Best is trial 207 with value: -0.01137496405368131.

  Epoch 020 - train 0.11261 | val 0.17265
  Regression -> MSE: 0.000240, MAE: 0.012324, R²: -0.0106
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.14074 | val 0.19456
  Epoch 020 - train 0.13836 | val 0.19671
  Regression -> MSE: 0.000248, MAE: 0.012531, R²: -0.0003
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.12729 | val 0.12405
  Epoch 020 - train 0.12674 | val 0.14020
  Regression -> MSE: 0.000690, MAE: 0.019443, R²: -0.0087
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.13116 | val 0.21656
  Epoch 020 - train 0.13041 | val 0.21913
  Regression -> MSE: 0.000311, MAE: 0.014453, R²: -0.0017
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.11003 | val 0.14861
  Epoch 020 - train 0.11036 | val 0.16757
  Regression -> MSE: 0.000351, MAE: 0.014591, R²: -0.0035
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.13604 | val 0.13625
  Epoch 020 - train 0.13660 | val 0.13955
  Regression -> MSE: 0.000204, MAE: 0.010163, R²: -0.0037
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.12623 | val 0.25031
  Epoch 020 - train 0.12251 | val 0.26388
  Regression -> MSE: 0.000563, MAE: 0.018219, R²: -0.0146
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.14545 | val 0.18482
  Epoch 020 - train 0.13777 | val 0.18788
  Regression -> MSE: 0.000250, MAE: 0.011938, R²: -0.0197
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.13188 | val 0.18288
  Epoch 020 - train 0.12855 | val 0.20562
  Regression -> MSE: 0.000636, MAE: 0.020007, R²: -0.0644
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.13653 | val 0.16939
  Epoch 020 - train 0.12843 | val 0.17675
  Regression -> MSE: 0.000384, MAE: 0.016141, R²: -0.0021
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.12791 | val 0.16950
  Epoch 020 - train 0.12970 | val 0.16964
  Regression -> MSE: 0.000243, MAE: 0.012102, R²: -0.0045
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.12489 | val 0.19017
  Epoch 020 - train 0.12850 | val 0.18824
  Regression -> MSE: 0.000320, MAE: 0.013599, R²: -0.0286
  Directional -> Accuracy: 0.5200, MCC: -0.0401, F1: 0.1429

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.13296 | val 0.16865
  Epoch 020 - train 0.14148 | val 0.18203
  Regression -> MSE: 0.000676, MAE: 0.019458, R²: 0.0020
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.13566 | val 0.13202
  Epoch 020 - train 0.13492 | val 0.12829
  Regression -> MSE: 0.000139, MAE: 0.009221, R²: -0.0073
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.12852 | val 0.16809
  Epoch 020 - train 0.12338 | val 0.17181
  Regression -> MSE: 0.000229, MAE: 0.010808, R²: -0.0166
  Directional -> Accuracy: 0.4918, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.12537 | val 0.26787
  Epoch 020 - train 0.12796 | val 0.27574
  Regression -> MSE: 0.000365, MAE: 0.015964, R²: -0.0066
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.13772 | val 0.13745
  Epoch 020 - train 0.13688 | val 0.13534
  Regression -> MSE: 0.000108, MAE: 0.008074, R²: -0.0034
  Directional -> Accuracy: 0.4571, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.13968 | val 0.23905
  Epoch 020 - train 0.14056 | val 0.25324
  Regression -> MSE: 0.000156, MAE: 0.009530, R²: -0.0013
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.13621 | val 0.13936
  Epoch 020 - train 0.13341 | val 0.13922
  Regression -> MSE: 0.000273, MAE: 0.013102, R²: -0.0040
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.12389 | val 0.17752
  Epoch 020 - train 0.12229 | val 0.17806
  Regression -> MSE: 0.000156, MAE: 0.008801, R²: -0.0434
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.13236 | val 0.20594
  Epoch 020 - train 0.13486 | val 0.21086
  Regression -> MSE: 0.000238, MAE: 0.011030, R²: -0.0530
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.12894 | val 0.16468
  Epoch 020 - train 0.13132 | val 0.16739
  Regression -> MSE: 0.000145, MAE: 0.008485, R²: -0.0150
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.12456 | val 0.16372
  Epoch 020 - train 0.12802 | val 0.16582
  Regression -> MSE: 0.000165, MAE: 0.010673, R²: -0.0006
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.13783 | val 0.16096
  Epoch 020 - train 0.13607 | val 0.16207
  Regression -> MSE: 0.000087, MAE: 0.007123, R²: -0.0171
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.13230 | val 0.16006
  Epoch 020 - train 0.13052 | val 0.16009
  Regression -> MSE: 0.000215, MAE: 0.011040, R²: -0.0151
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.12311 | val 0.12026
  Epoch 020 - train 0.12070 | val 0.11689
  Regression -> MSE: 0.000095, MAE: 0.008127, R²: -0.0364
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.14751 | val 0.10369
  Epoch 020 - train 0.14756 | val 0.11666
  Regression -> MSE: 0.000103, MAE: 0.008731, R²: -0.0021
  Directional -> Accuracy: 0.4565, MCC: -0.0339, F1: 0.5283

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.13919 | val 0.12516
  Epoch 020 - train 0.13457 | val 0.13830
  Regression -> MSE: 0.000231, MAE: 0.012528, R²: 0.0005
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.12922 | val 0.15945
  Epoch 020 - train 0.12721 | val 0.15925
  Regression -> MSE: 0.000172, MAE: 0.007832, R²: -0.0356
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.13770 | val 0.11309
  Epoch 020 - train 0.13797 | val 0.11254
  Regression -> MSE: 0.000237, MAE: 0.011869, R²: -0.0013
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.13642 | val 0.20830
  Epoch 020 - train 0.13193 | val 0.21103
  Regression -> MSE: 0.000231, MAE: 0.009955, R²: -0.0026
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.13928 | val 0.16479
  Epoch 020 - train 0.13452 | val 0.18247
  Regression -> MSE: 0.000136, MAE: 0.008242, R²: -0.0074
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.12923 | val 0.16557
  Epoch 020 - train 0.12886 | val 0.16574
  Regression -> MSE: 0.000191, MAE: 0.010388, R²: -0.0129
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.11709 | val 0.17164
  Epoch 020 - train 0.11630 | val 0.16907
  Regression -> MSE: 0.000272, MAE: 0.010649, R²: -0.0378
  Directional -> Accuracy: 0.4795, MCC: 0.0049, F1: 0.4062

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.12837 | val 0.11588
  Epoch 020 - train 0.13300 | val 0.10734
  Regression -> MSE: 0.000163, MAE: 0.010401, R²: 0.0239
  Directional -> Accuracy: 0.4737, MCC: -0.0580, F1: 0.5652

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.12461 | val 0.13423
  Epoch 020 - train 0.11759 | val 0.13138
  Regression -> MSE: 0.000176, MAE: 0.010132, R²: 0.0224
  Directional -> Accuracy: 0.5455, MCC: 0.1596, F1: 0.0909

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.12381 | val 0.12578
  Epoch 020 - train 0.12668 | val 0.12428
  Regression -> MSE: 0.000347, MAE: 0.011725, R²: -0.0125
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.14573 | val 0.08669
  Epoch 020 - train 0.14310 | val 0.08704
  Regression -> MSE: 0.000124, MAE: 0.008436, R²: -0.1793
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.13006 | val 0.18452
  Epoch 020 - train 0.12645 | val 0.19652
  Regression -> MSE: 0.000220, MAE: 0.011324, R²: -0.0051
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.13029 | val 0.22718
  Epoch 020 - train 0.12978 | val 0.24478
  Regression -> MSE: 0.000085, MAE: 0.007191, R²: -0.0914
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.14356 | val 0.11034
  Epoch 020 - train 0.13597 | val 0.11663
  Regression -> MSE: 0.000331, MAE: 0.015057, R²: -0.0776
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.13676 | val 0.08041
  Epoch 020 - train 0.14538 | val 0.08123
  Regression -> MSE: 0.000252, MAE: 0.011501, R²: -0.0340
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.13752 | val 0.16050
  Epoch 020 - train 0.13303 | val 0.15922
  Regression -> MSE: 0.000082, MAE: 0.007141, R²: -0.0112
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.13810 | val 0.16000
  Epoch 020 - train 0.13260 | val 0.16577
  Regression -> MSE: 0.000308, MAE: 0.014508, R²: -0.0027
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.12340 | val 0.15593
  Epoch 020 - train 0.12511 | val 0.16716
  Regression -> MSE: 0.000101, MAE: 0.007118, R²: -0.0249
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.14152 | val 0.15789
  Epoch 020 - train 0.13880 | val 0.15875
  Regression -> MSE: 0.000172, MAE: 0.009636, R²: 0.0006
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.12405 | val 0.15238
  Epoch 020 - train 0.12760 | val 0.15285
  Regression -> MSE: 0.000223, MAE: 0.011771, R²: -0.0006
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.13072 | val 0.14688
  Epoch 020 - train 0.12926 | val 0.14964
  Regression -> MSE: 0.000092, MAE: 0.007654, R²: -0.0004
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.14129 | val 0.22538
  Epoch 020 - train 0.14157 | val 0.25010
  Regression -> MSE: 0.000167, MAE: 0.010304, R²: -0.0223
  Directional -> Accuracy: 0.4815, MCC: 0.0000, F1: 0.0000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.12669 | val 0.16482
  Epoch 020 - train 0.12783 | val 0.16854
  Regression -> MSE: 0.000130, MAE: 0.009090, R²: -0.1181
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.13343 | val 0.18734

[I 2026-02-23 04:16:26,108] Trial 246 finished with value: -0.011402852248563468 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 32, 'learning_rate': 3.171176576786607e-06, 'weight_decay': 3.3171995752674886e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.19961302306068188, 'early_stopping_min_delta': 0.005045846355261012}. Best is trial 207 with value: -0.01137496405368131.

  Epoch 020 - train 0.13281 | val 0.19135
  Regression -> MSE: 0.000238, MAE: 0.012332, R²: -0.0020
  Directional -> Accuracy: 0.6066, MCC: 0.2076, F1: 0.5385

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.16081 | val 0.20558
  Epoch 020 - train 0.15935 | val 0.20559
  Regression -> MSE: 0.000256, MAE: 0.012926, R²: -0.0324
  Directional -> Accuracy: 0.4805, MCC: 0.1491, F1: 0.6364

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.17005 | val 0.14567
  Epoch 020 - train 0.17097 | val 0.15082
  Regression -> MSE: 0.000707, MAE: 0.019744, R²: -0.0323
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.16076 | val 0.26223
  Epoch 020 - train 0.16649 | val 0.26971
  Regression -> MSE: 0.000315, MAE: 0.014456, R²: -0.0168
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.13563 | val 0.17682
  Epoch 020 - train 0.13584 | val 0.17489
  Regression -> MSE: 0.000352, MAE: 0.014596, R²: -0.0079
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.15349 | val 0.14950
  Epoch 020 - train 0.15034 | val 0.14743
  Regression -> MSE: 0.000198, MAE: 0.009799, R²: 0.0260
  Directional -> Accuracy: 0.5882, MCC: 0.2652, F1: 0.7200

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.15594 | val 0.30400
  Epoch 020 - train 0.15829 | val 0.29860
  Regression -> MSE: 0.000574, MAE: 0.018628, R²: -0.0345
  Directional -> Accuracy: 0.5532, MCC: 0.1590, F1: 0.2222

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.16460 | val 0.20302
  Epoch 020 - train 0.16336 | val 0.19939
  Regression -> MSE: 0.000246, MAE: 0.011997, R²: -0.0009
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.15467 | val 0.23620
  Epoch 020 - train 0.15536 | val 0.25921
  Regression -> MSE: 0.000664, MAE: 0.020456, R²: -0.1119
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.15168 | val 0.19329
  Epoch 020 - train 0.14854 | val 0.19623
  Regression -> MSE: 0.000388, MAE: 0.015972, R²: -0.0126
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.15793 | val 0.20465
  Epoch 020 - train 0.15702 | val 0.20838
  Regression -> MSE: 0.000243, MAE: 0.011676, R²: -0.0064
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.14675 | val 0.22009
  Epoch 020 - train 0.14654 | val 0.21971
  Regression -> MSE: 0.000319, MAE: 0.013582, R²: -0.0275
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.16521 | val 0.18856
  Epoch 020 - train 0.16232 | val 0.19916
  Regression -> MSE: 0.000680, MAE: 0.019586, R²: -0.0036
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.16945 | val 0.17303
  Epoch 020 - train 0.17050 | val 0.18041
  Regression -> MSE: 0.000140, MAE: 0.009003, R²: -0.0134
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.14315 | val 0.20612
  Epoch 020 - train 0.15019 | val 0.20997
  Regression -> MSE: 0.000226, MAE: 0.010717, R²: -0.0055
  Directional -> Accuracy: 0.4590, MCC: -0.0906, F1: 0.2326

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.18717 | val 0.34615
  Epoch 020 - train 0.17803 | val 0.44043
  Regression -> MSE: 0.000363, MAE: 0.016220, R²: -0.0029
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.16563 | val 0.16071
  Epoch 020 - train 0.16609 | val 0.16233
  Regression -> MSE: 0.000109, MAE: 0.007955, R²: -0.0059
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.15561 | val 0.27146
  Epoch 020 - train 0.15486 | val 0.29241
  Regression -> MSE: 0.000160, MAE: 0.010048, R²: -0.0233
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.17333 | val 0.16943
  Epoch 020 - train 0.16824 | val 0.17535
  Regression -> MSE: 0.000287, MAE: 0.013709, R²: -0.0530
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.13930 | val 0.21635
  Epoch 020 - train 0.14017 | val 0.21388
  Regression -> MSE: 0.000165, MAE: 0.009093, R²: -0.1057
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.17023 | val 0.26847
  Epoch 020 - train 0.16170 | val 0.26209
  Regression -> MSE: 0.000231, MAE: 0.010901, R²: -0.0221
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.15789 | val 0.19969
  Epoch 020 - train 0.15408 | val 0.21351
  Regression -> MSE: 0.000154, MAE: 0.008846, R²: -0.0740
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.15602 | val 0.18622
  Epoch 020 - train 0.15216 | val 0.18718
  Regression -> MSE: 0.000173, MAE: 0.010279, R²: -0.0481
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.16996 | val 0.21090
  Epoch 020 - train 0.17252 | val 0.21567
  Regression -> MSE: 0.000087, MAE: 0.007140, R²: -0.0193
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.15483 | val 0.20399
  Epoch 020 - train 0.15582 | val 0.21955
  Regression -> MSE: 0.000212, MAE: 0.011255, R²: -0.0014
  Directional -> Accuracy: 0.5000, MCC: 0.0310, F1: 0.5823

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.15674 | val 0.14749
  Epoch 020 - train 0.15525 | val 0.15234
  Regression -> MSE: 0.000095, MAE: 0.008108, R²: -0.0318
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.15944 | val 0.12142
  Epoch 020 - train 0.15974 | val 0.12215
  Regression -> MSE: 0.000105, MAE: 0.008840, R²: -0.0168
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.16920 | val 0.15440
  Epoch 020 - train 0.16275 | val 0.16193
  Regression -> MSE: 0.000238, MAE: 0.012781, R²: -0.0280
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.15831 | val 0.17985
  Epoch 020 - train 0.16286 | val 0.18132
  Regression -> MSE: 0.000188, MAE: 0.008103, R²: -0.1266
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.15901 | val 0.13280
  Epoch 020 - train 0.16450 | val 0.15295
  Regression -> MSE: 0.000239, MAE: 0.011931, R²: -0.0102
  Directional -> Accuracy: 0.4390, MCC: -0.1145, F1: 0.0800

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.15770 | val 0.25436
  Epoch 020 - train 0.15161 | val 0.25621
  Regression -> MSE: 0.000232, MAE: 0.010047, R²: -0.0086
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.16389 | val 0.20574
  Epoch 020 - train 0.16672 | val 0.20854
  Regression -> MSE: 0.000141, MAE: 0.008496, R²: -0.0445
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.15682 | val 0.20205
  Epoch 020 - train 0.15236 | val 0.20681
  Regression -> MSE: 0.000194, MAE: 0.010489, R²: -0.0325
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.14028 | val 0.20824
  Epoch 020 - train 0.14150 | val 0.20677
  Regression -> MSE: 0.000268, MAE: 0.010566, R²: -0.0223
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.14765 | val 0.13256
  Epoch 020 - train 0.14678 | val 0.13958
  Regression -> MSE: 0.000168, MAE: 0.010367, R²: -0.0069
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.15886 | val 0.15578
  Epoch 020 - train 0.14641 | val 0.15250
  Regression -> MSE: 0.000190, MAE: 0.010807, R²: -0.0564
  Directional -> Accuracy: 0.5682, MCC: 0.1727, F1: 0.2400

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.16470 | val 0.15353
  Epoch 020 - train 0.16269 | val 0.15389
  Regression -> MSE: 0.000348, MAE: 0.011736, R²: -0.0151
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.17800 | val 0.10486
  Epoch 020 - train 0.17738 | val 0.11029
  Regression -> MSE: 0.000109, MAE: 0.008369, R²: -0.0410
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.16076 | val 0.21632
  Epoch 020 - train 0.15620 | val 0.21505
  Regression -> MSE: 0.000223, MAE: 0.011410, R²: -0.0197
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.16539 | val 0.26962
  Epoch 020 - train 0.16073 | val 0.27390
  Regression -> MSE: 0.000095, MAE: 0.007620, R²: -0.2288
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.15635 | val 0.11831
  Epoch 020 - train 0.15486 | val 0.11649
  Regression -> MSE: 0.000312, MAE: 0.014050, R²: -0.0130
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.17272 | val 0.10185
  Epoch 020 - train 0.17528 | val 0.09889
  Regression -> MSE: 0.000261, MAE: 0.011498, R²: -0.0696
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.14879 | val 0.18784
  Epoch 020 - train 0.14786 | val 0.18687
  Regression -> MSE: 0.000081, MAE: 0.007057, R²: -0.0042
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.17927 | val 0.21794
  Epoch 020 - train 0.17404 | val 0.25512
  Regression -> MSE: 0.000315, MAE: 0.014523, R²: -0.0270
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.14943 | val 0.18194
  Epoch 020 - train 0.15158 | val 0.18566
  Regression -> MSE: 0.000100, MAE: 0.007121, R²: -0.0185
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.17612 | val 0.18998
  Epoch 020 - train 0.17272 | val 0.19881
  Regression -> MSE: 0.000172, MAE: 0.009732, R²: -0.0007
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.14940 | val 0.17463
  Epoch 020 - train 0.15082 | val 0.17996
  Regression -> MSE: 0.000228, MAE: 0.011651, R²: -0.0244
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.15989 | val 0.18554
  Epoch 020 - train 0.15590 | val 0.19374
  Regression -> MSE: 0.000092, MAE: 0.007643, R²: -0.0002
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.16520 | val 0.24849
  Epoch 020 - train 0.16287 | val 0.25885
  Regression -> MSE: 0.000164, MAE: 0.010284, R²: -0.0039
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.16024 | val 0.21103
  Epoch 020 - train 0.15866 | val 0.22141
  Regression -> MSE: 0.000120, MAE: 0.008981, R²: -0.0324
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.15440 | val 0.23966

[I 2026-02-23 04:19:10,465] Trial 247 finished with value: -0.011463867388508561 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 32, 'learning_rate': 3.152457965259605e-06, 'weight_decay': 3.4767023139536044e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.24437687746448228, 'early_stopping_min_delta': 0.005026267817799973}. Best is trial 207 with value: -0.01137496405368131.

  Epoch 020 - train 0.15655 | val 0.25070
  Regression -> MSE: 0.000238, MAE: 0.012397, R²: -0.0041
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.13481 | val 0.20831
  Epoch 020 - train 0.13698 | val 0.21075
  Regression -> MSE: 0.000253, MAE: 0.012775, R²: -0.0231
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.12969 | val 0.12797
  Epoch 020 - train 0.12681 | val 0.13721
  Regression -> MSE: 0.000686, MAE: 0.019359, R²: -0.0017
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.13375 | val 0.21643
  Epoch 020 - train 0.13478 | val 0.22195
  Regression -> MSE: 0.000310, MAE: 0.014371, R²: -0.0005
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.11666 | val 0.18375
  Epoch 020 - train 0.11765 | val 0.19675
  Regression -> MSE: 0.000372, MAE: 0.014948, R²: -0.0662
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.13753 | val 0.13262
  Epoch 020 - train 0.13429 | val 0.13585
  Regression -> MSE: 0.000205, MAE: 0.010096, R²: -0.0070
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.12281 | val 0.25512
  Epoch 020 - train 0.12619 | val 0.25988
  Regression -> MSE: 0.000569, MAE: 0.018340, R²: -0.0252
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.14168 | val 0.16219
  Epoch 020 - train 0.14077 | val 0.16305
  Regression -> MSE: 0.000247, MAE: 0.012426, R²: -0.0066
  Directional -> Accuracy: 0.4348, MCC: 0.0455, F1: 0.5714

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.12974 | val 0.20212
  Epoch 020 - train 0.13537 | val 0.21495
  Regression -> MSE: 0.000672, MAE: 0.020567, R²: -0.1242
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.12601 | val 0.16520
  Epoch 020 - train 0.12859 | val 0.16791
  Regression -> MSE: 0.000391, MAE: 0.015948, R²: -0.0187
  Directional -> Accuracy: 0.5510, MCC: 0.1289, F1: 0.5769

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.13797 | val 0.18207
  Epoch 020 - train 0.14022 | val 0.18804
  Regression -> MSE: 0.000246, MAE: 0.011673, R²: -0.0183
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.12220 | val 0.20645
  Epoch 020 - train 0.12628 | val 0.20859
  Regression -> MSE: 0.000312, MAE: 0.013623, R²: -0.0023
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.13792 | val 0.16158
  Epoch 020 - train 0.13854 | val 0.16260
  Regression -> MSE: 0.000678, MAE: 0.019490, R²: -0.0011
  Directional -> Accuracy: 0.4655, MCC: -0.1132, F1: 0.6173

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.15171 | val 0.20005
  Epoch 020 - train 0.14893 | val 0.28094
  Regression -> MSE: 0.000140, MAE: 0.008993, R²: -0.0134
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.12689 | val 0.20333
  Epoch 020 - train 0.12442 | val 0.20955
  Regression -> MSE: 0.000225, MAE: 0.010685, R²: -0.0022
  Directional -> Accuracy: 0.5082, MCC: 0.0081, F1: 0.6250

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.13345 | val 0.28871
  Epoch 020 - train 0.12898 | val 0.29462
  Regression -> MSE: 0.000362, MAE: 0.016116, R²: -0.0001
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.14045 | val 0.14432
  Epoch 020 - train 0.14198 | val 0.14244
  Regression -> MSE: 0.000108, MAE: 0.008040, R²: -0.0027
  Directional -> Accuracy: 0.4571, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.13480 | val 0.22366
  Epoch 020 - train 0.13219 | val 0.22815
  Regression -> MSE: 0.000157, MAE: 0.009875, R²: -0.0074
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.13729 | val 0.16243
  Epoch 020 - train 0.13813 | val 0.16018
  Regression -> MSE: 0.000274, MAE: 0.012925, R²: -0.0081
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.12299 | val 0.18681
  Epoch 020 - train 0.12548 | val 0.18755
  Regression -> MSE: 0.000151, MAE: 0.008735, R²: -0.0124
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.15101 | val 0.20596
  Epoch 020 - train 0.15116 | val 0.20649
  Regression -> MSE: 0.000258, MAE: 0.011523, R²: -0.1417
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.13361 | val 0.17088
  Epoch 020 - train 0.13660 | val 0.17478
  Regression -> MSE: 0.000147, MAE: 0.008540, R²: -0.0233
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.12763 | val 0.16861
  Epoch 020 - train 0.12669 | val 0.16908
  Regression -> MSE: 0.000165, MAE: 0.010345, R²: -0.0015
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.14195 | val 0.16867
  Epoch 020 - train 0.14113 | val 0.16700
  Regression -> MSE: 0.000094, MAE: 0.007477, R²: -0.1012
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.13849 | val 0.16781
  Epoch 020 - train 0.13952 | val 0.16570
  Regression -> MSE: 0.000213, MAE: 0.011339, R²: -0.0071
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.12977 | val 0.12349
  Epoch 020 - train 0.12146 | val 0.12136
  Regression -> MSE: 0.000096, MAE: 0.008134, R²: -0.0443
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.14761 | val 0.10601
  Epoch 020 - train 0.14596 | val 0.10862
  Regression -> MSE: 0.000103, MAE: 0.008668, R²: 0.0023
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.15178 | val 0.14214
  Epoch 020 - train 0.15151 | val 0.14683
  Regression -> MSE: 0.000244, MAE: 0.012935, R²: -0.0526
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.13697 | val 0.16053
  Epoch 020 - train 0.13447 | val 0.16214
  Regression -> MSE: 0.000175, MAE: 0.007878, R²: -0.0514
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.13452 | val 0.11449
  Epoch 020 - train 0.14323 | val 0.11505
  Regression -> MSE: 0.000239, MAE: 0.011936, R²: -0.0108
  Directional -> Accuracy: 0.4634, MCC: 0.0000, F1: 0.0000

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.13964 | val 0.21225
  Epoch 020 - train 0.13711 | val 0.21259
  Regression -> MSE: 0.000231, MAE: 0.009869, R²: -0.0011
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.14427 | val 0.17900
  Epoch 020 - train 0.14671 | val 0.20307
  Regression -> MSE: 0.000143, MAE: 0.008548, R²: -0.0566
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.13880 | val 0.17301
  Epoch 020 - train 0.13292 | val 0.17676
  Regression -> MSE: 0.000192, MAE: 0.010383, R²: -0.0172
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.12359 | val 0.17746
  Epoch 020 - train 0.11972 | val 0.17636
  Regression -> MSE: 0.000261, MAE: 0.010516, R²: 0.0017
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.12628 | val 0.11343
  Epoch 020 - train 0.12248 | val 0.11391
  Regression -> MSE: 0.000171, MAE: 0.010381, R²: -0.0236
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.13305 | val 0.14567
  Epoch 020 - train 0.12541 | val 0.14435
  Regression -> MSE: 0.000250, MAE: 0.012040, R²: -0.3885
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.12837 | val 0.13357
  Epoch 020 - train 0.12901 | val 0.13463
  Regression -> MSE: 0.000350, MAE: 0.012415, R²: -0.0216
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.13993 | val 0.08711
  Epoch 020 - train 0.14361 | val 0.08747
  Regression -> MSE: 0.000114, MAE: 0.008329, R²: -0.0875
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.13705 | val 0.18732
  Epoch 020 - train 0.13235 | val 0.18577
  Regression -> MSE: 0.000226, MAE: 0.011482, R²: -0.0328
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.13501 | val 0.23844
  Epoch 020 - train 0.13446 | val 0.25244
  Regression -> MSE: 0.000086, MAE: 0.007267, R²: -0.1116
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.13464 | val 0.10415
  Epoch 020 - train 0.13147 | val 0.11442
  Regression -> MSE: 0.000311, MAE: 0.014023, R²: -0.0113
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.13694 | val 0.08783
  Epoch 020 - train 0.14003 | val 0.08262
  Regression -> MSE: 0.000260, MAE: 0.011495, R²: -0.0651
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.12636 | val 0.15678
  Epoch 020 - train 0.12993 | val 0.15637
  Regression -> MSE: 0.000082, MAE: 0.007085, R²: -0.0100
  Directional -> Accuracy: 0.4933, MCC: -0.0022, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.13304 | val 0.17332
  Epoch 020 - train 0.13894 | val 0.17280
  Regression -> MSE: 0.000310, MAE: 0.014486, R²: -0.0097
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.13015 | val 0.15124
  Epoch 020 - train 0.13315 | val 0.15072
  Regression -> MSE: 0.000099, MAE: 0.007159, R²: -0.0073
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.14511 | val 0.15730
  Epoch 020 - train 0.14663 | val 0.15193
  Regression -> MSE: 0.000176, MAE: 0.009908, R²: -0.0235
  Directional -> Accuracy: 0.3878, MCC: -0.0861, F1: 0.5161

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.12393 | val 0.17586
  Epoch 020 - train 0.12798 | val 0.17975
  Regression -> MSE: 0.000224, MAE: 0.011787, R²: -0.0055
  Directional -> Accuracy: 0.4464, MCC: -0.1158, F1: 0.4918

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.14321 | val 0.16762
  Epoch 020 - train 0.13584 | val 0.17021
  Regression -> MSE: 0.000098, MAE: 0.008045, R²: -0.0657
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.14303 | val 0.21593
  Epoch 020 - train 0.14066 | val 0.22027
  Regression -> MSE: 0.000164, MAE: 0.010265, R²: -0.0019
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.14451 | val 0.19847
  Epoch 020 - train 0.14315 | val 0.20800
  Regression -> MSE: 0.000126, MAE: 0.009032, R²: -0.0831
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.14121 | val 0.29888

[I 2026-02-23 04:20:58,304] Trial 248 finished with value: -0.011493161502245936 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 32, 'learning_rate': 4.502910221078993e-06, 'weight_decay': 3.081404774535413e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.20607710983410107, 'early_stopping_min_delta': 0.005186772385357181}. Best is trial 207 with value: -0.01137496405368131.

  Epoch 020 - train 0.14544 | val 0.29724
  Regression -> MSE: 0.000238, MAE: 0.012385, R²: -0.0051
  Directional -> Accuracy: 0.4918, MCC: 0.1229, F1: 0.6517

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.07797 | val 0.09760
  Epoch 020 - train 0.07635 | val 0.09795
  Regression -> MSE: 0.000264, MAE: 0.013141, R²: -0.0681
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.07271 | val 0.08704
  Epoch 020 - train 0.07249 | val 0.09669
  Regression -> MSE: 0.000713, MAE: 0.019842, R²: -0.0417
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.07508 | val 0.11507
  Epoch 020 - train 0.07280 | val 0.11427
  Regression -> MSE: 0.000311, MAE: 0.014486, R²: -0.0028
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.06045 | val 0.07939
  Epoch 020 - train 0.06152 | val 0.08026
  Regression -> MSE: 0.000351, MAE: 0.014579, R²: -0.0038
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.07201 | val 0.06861
  Epoch 020 - train 0.07034 | val 0.06936
  Regression -> MSE: 0.000210, MAE: 0.010454, R²: -0.0293
  Directional -> Accuracy: 0.5686, MCC: 0.1502, F1: 0.5417

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.06757 | val 0.13000
  Epoch 020 - train 0.06770 | val 0.13095
  Regression -> MSE: 0.000591, MAE: 0.018781, R²: -0.0648
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.07252 | val 0.08850
  Epoch 020 - train 0.07346 | val 0.08878
  Regression -> MSE: 0.000250, MAE: 0.011927, R²: -0.0176
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.06806 | val 0.09834
  Epoch 020 - train 0.06997 | val 0.11534
  Regression -> MSE: 0.000626, MAE: 0.019808, R²: -0.0474
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.07218 | val 0.08161
  Epoch 020 - train 0.07039 | val 0.08213
  Regression -> MSE: 0.000407, MAE: 0.016188, R²: -0.0603
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.07398 | val 0.08885
  Epoch 020 - train 0.07296 | val 0.08854
  Regression -> MSE: 0.000244, MAE: 0.011612, R²: -0.0125
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.06746 | val 0.11172
  Epoch 020 - train 0.06814 | val 0.11442
  Regression -> MSE: 0.000317, MAE: 0.013595, R²: -0.0198
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.07360 | val 0.08531
  Epoch 020 - train 0.07343 | val 0.08553
  Regression -> MSE: 0.000681, MAE: 0.019521, R²: -0.0050
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.07286 | val 0.06973
  Epoch 020 - train 0.07398 | val 0.07021
  Regression -> MSE: 0.000139, MAE: 0.009139, R²: -0.0038
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.06678 | val 0.10069
  Epoch 020 - train 0.06650 | val 0.10001
  Regression -> MSE: 0.000225, MAE: 0.010691, R²: -0.0025
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.07150 | val 0.13574
  Epoch 020 - train 0.06861 | val 0.13548
  Regression -> MSE: 0.000368, MAE: 0.015909, R²: -0.0168
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.07506 | val 0.09164
  Epoch 020 - train 0.07374 | val 0.09016
  Regression -> MSE: 0.000107, MAE: 0.007958, R²: 0.0044
  Directional -> Accuracy: 0.5714, MCC: 0.1152, F1: 0.6875

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.06992 | val 0.11851
  Epoch 020 - train 0.07075 | val 0.11995
  Regression -> MSE: 0.000155, MAE: 0.009611, R²: 0.0044
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.07615 | val 0.08696
  Epoch 020 - train 0.07534 | val 0.08434
  Regression -> MSE: 0.000277, MAE: 0.012922, R²: -0.0166
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.06331 | val 0.09140
  Epoch 020 - train 0.06402 | val 0.09118
  Regression -> MSE: 0.000164, MAE: 0.009020, R²: -0.0973
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.07416 | val 0.10241
  Epoch 020 - train 0.07431 | val 0.10194
  Regression -> MSE: 0.000233, MAE: 0.011003, R²: -0.0296
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.07754 | val 0.09305
  Epoch 020 - train 0.07407 | val 0.09396
  Regression -> MSE: 0.000150, MAE: 0.008661, R²: -0.0469
  Directional -> Accuracy: 0.6458, MCC: 0.1585, F1: 0.7671

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.06841 | val 0.08734
  Epoch 020 - train 0.06861 | val 0.08726
  Regression -> MSE: 0.000163, MAE: 0.010280, R²: 0.0163
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.07579 | val 0.08405
  Epoch 020 - train 0.07569 | val 0.08442
  Regression -> MSE: 0.000086, MAE: 0.007069, R²: -0.0044
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.07248 | val 0.09861
  Epoch 020 - train 0.07149 | val 0.10554
  Regression -> MSE: 0.000211, MAE: 0.011057, R²: 0.0059
  Directional -> Accuracy: 0.5152, MCC: 0.0620, F1: 0.5897

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.06518 | val 0.06186
  Epoch 020 - train 0.06558 | val 0.06178
  Regression -> MSE: 0.000099, MAE: 0.008158, R²: -0.0704
  Directional -> Accuracy: 0.5000, MCC: 0.0996, F1: 0.3000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.07176 | val 0.05717
  Epoch 020 - train 0.07155 | val 0.05497
  Regression -> MSE: 0.000116, MAE: 0.009192, R²: -0.1227
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.07467 | val 0.08008
  Epoch 020 - train 0.07286 | val 0.08301
  Regression -> MSE: 0.000235, MAE: 0.012665, R²: -0.0162
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.07330 | val 0.08785
  Epoch 020 - train 0.07134 | val 0.08758
  Regression -> MSE: 0.000187, MAE: 0.008123, R²: -0.1245
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.07887 | val 0.06130
  Epoch 020 - train 0.07549 | val 0.06335
  Regression -> MSE: 0.000238, MAE: 0.011894, R²: -0.0062
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.07056 | val 0.10986
  Epoch 020 - train 0.06950 | val 0.10982
  Regression -> MSE: 0.000235, MAE: 0.010164, R²: -0.0181
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.07218 | val 0.08353
  Epoch 020 - train 0.07400 | val 0.08305
  Regression -> MSE: 0.000136, MAE: 0.008312, R²: -0.0064
  Directional -> Accuracy: 0.3953, MCC: -0.1983, F1: 0.2778

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.08163 | val 0.09421
  Epoch 020 - train 0.07886 | val 0.09393
  Regression -> MSE: 0.000190, MAE: 0.010625, R²: -0.0092
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.06443 | val 0.09229
  Epoch 020 - train 0.06367 | val 0.09099
  Regression -> MSE: 0.000271, MAE: 0.010708, R²: -0.0357
  Directional -> Accuracy: 0.4932, MCC: -0.0643, F1: 0.5934

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.06925 | val 0.06188
  Epoch 020 - train 0.06670 | val 0.06527
  Regression -> MSE: 0.000166, MAE: 0.010358, R²: 0.0049
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.06523 | val 0.07291
  Epoch 020 - train 0.06617 | val 0.07526
  Regression -> MSE: 0.000181, MAE: 0.010281, R²: -0.0040
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.06911 | val 0.07035
  Epoch 020 - train 0.06883 | val 0.06990
  Regression -> MSE: 0.000345, MAE: 0.011778, R²: -0.0083
  Directional -> Accuracy: 0.5224, MCC: -0.0478, F1: 0.6522

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.08180 | val 0.05670
  Epoch 020 - train 0.08025 | val 0.06366
  Regression -> MSE: 0.000113, MAE: 0.008259, R²: -0.0771
  Directional -> Accuracy: 0.5349, MCC: 0.0977, F1: 0.6774

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.07382 | val 0.09719
  Epoch 020 - train 0.07157 | val 0.09558
  Regression -> MSE: 0.000221, MAE: 0.011414, R²: -0.0133
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.07471 | val 0.13610
  Epoch 020 - train 0.07488 | val 0.14072
  Regression -> MSE: 0.000081, MAE: 0.007028, R²: -0.0469
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.06717 | val 0.05488
  Epoch 020 - train 0.07159 | val 0.05473
  Regression -> MSE: 0.000314, MAE: 0.014225, R²: -0.0212
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.08191 | val 0.04856
  Epoch 020 - train 0.07878 | val 0.05435
  Regression -> MSE: 0.000255, MAE: 0.011472, R²: -0.0447
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.06950 | val 0.08537
  Epoch 020 - train 0.06880 | val 0.08470
  Regression -> MSE: 0.000083, MAE: 0.007047, R²: -0.0217
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.07293 | val 0.08795
  Epoch 020 - train 0.07286 | val 0.09128
  Regression -> MSE: 0.000310, MAE: 0.014517, R²: -0.0090
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.07244 | val 0.08146
  Epoch 020 - train 0.07415 | val 0.08698
  Regression -> MSE: 0.000099, MAE: 0.007173, R²: -0.0094
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.07860 | val 0.08298
  Epoch 020 - train 0.07483 | val 0.08423
  Regression -> MSE: 0.000172, MAE: 0.009650, R²: -0.0002
  Directional -> Accuracy: 0.3673, MCC: -0.1741, F1: 0.4561

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.06534 | val 0.08013
  Epoch 020 - train 0.06474 | val 0.07954
  Regression -> MSE: 0.000223, MAE: 0.011759, R²: 0.0003
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.07188 | val 0.07477
  Epoch 020 - train 0.07242 | val 0.07480
  Regression -> MSE: 0.000093, MAE: 0.007673, R²: -0.0074
  Directional -> Accuracy: 0.4737, MCC: -0.0556, F1: 0.4444

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.07822 | val 0.11150
  Epoch 020 - train 0.07433 | val 0.11146
  Regression -> MSE: 0.000166, MAE: 0.010295, R²: -0.0112
  Directional -> Accuracy: 0.4815, MCC: 0.0000, F1: 0.0000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.07219 | val 0.09144
  Epoch 020 - train 0.06952 | val 0.09070
  Regression -> MSE: 0.000129, MAE: 0.009095, R²: -0.1090
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.07124 | val 0.09554

[I 2026-02-23 04:23:24,090] Trial 249 finished with value: -0.011429598928282898 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 32, 'learning_rate': 2.837960584556252e-06, 'weight_decay': 2.2053552878989197e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.10064178195416718, 'early_stopping_min_delta': 0.004817769410149073}. Best is trial 207 with value: -0.01137496405368131.

  Epoch 020 - train 0.07241 | val 0.09634
  Regression -> MSE: 0.000244, MAE: 0.012362, R²: -0.0305
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Saved Optuna results to ../results/benchmarking/regression/optuna_tuning_base_1H.csv